### ISSUE TITLE
Affix Plugin Flickering at bottom in IE (8 - 11)

### ISSUE THREAD

**Issue by seanriceaz** [twbs/bootstrap#12373]
Affix appears to be removing and re-adding the "affix-bottom" class to the affixed element at the bottom of the screen as the user scrolls in small increments up/down.

This is especially noticeable when the footer is very tall, and the affixed element is tall as well.

You can see it happening in IE on the bootstrap site overlapping the footer: 
![image](https://f.cloud.github.com/assets/455287/2001078/6ad4d1da-8586-11e3-8aa4-1acc27fec865.png)

Perhaps this has to do with a pixel-rounding issue, or maybe the scroll event handling is strange in IE?

**Comment by mdo** [comment]
Punting on this. I'd still love to see a fix, but it's not paramount we address this given v3's trajectory.

**Comment by gpakosz** [comment]
@mdo what's the benefit of closing this exactly? one more greenlight?

imho leaving it open == acknowledging the issue exists.
fixing it, in whatever milestone is another story

**Comment by mdo** [comment]
Big changes are in for v4 and we're punting on non-critical fixes from here out to prep for that.

**Comment by beloculus** [comment]
Just to circle back on this in case anyone else finds this thread after encountering this issue:

I was experiencing it in 3.2.3, but upgrading to 3.3.6 fixed the issue for me. So, despite the fact that this issue was closed, it seems to have been fixed anyway?

**Comment by gleighfield** [comment]
The above worked for me - many thanks @beloculus
