### ISSUE TITLE
Can't scroll to last collapsed navbar item on mobile when there are many items

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#12738]
[Original title: Expanded navbar on mobile (landscape) is cut off]
/CC @mdo

**Comment by maniqui** [comment]
Can confirm this affects browsing on Android 2.3.6.

A possible fix taken from this SO answer:
http://stackoverflow.com/a/25060926/2461947

```
 .navbar-collapse::-webkit-scrollbar {
    width: 20px;
}
.navbar-collapse::-webkit-scrollbar-track {
    background-color: lightgray;
}
.navbar-collapse::-webkit-scrollbar-thumb {
    background-color: lightblue;
}
```

You can test it here:
http://jsbin.com/gibufafico [1]

Pros:

* now you can scroll an overflowed `.navbar-collapse`

Cons:

* styles will probably apply to every Webkit-based browsers, not only those old versions (ie. browser on Android 2.3.6) that don't work properly. Not sure if there is a way to scope the fix to old browsers.
* for the scroll to work, you have to tap on the "scrollbar-track". The "scrollbar-thumb" won't work (ie. you can't drag it as you would expect).

[1]: QR for your convenience:

![QR](http://api.qrserver.com/v1/create-qr-code/?color=000000&bgcolor=FFFFFF&data=http%3A%2F%2Fjsbin.com%2Fgibufafico&qzone=1&margin=0&size=200x200&ecc=L)

**Comment by twbs-lmvtfy** [comment]
Hi @maniqui!

You appear to have posted a live example (http://jsbin.com/gibufafico/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 11, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.1.1
* line 84, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.1.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by maniqui** [comment]
@twbs-lmvtfy: fixed.

**Comment by XhmikosR** [comment]
I really need to test this...

**Comment by carasmo** [comment]
https://output.jsbin.com/lufuxo  == navbar-fixed-top can't get to menu items when the viewport is shorter than the height of the menu on small viewport widths.

**Comment by twbs-lmvtfy** [comment]
Hi @carasmo!

You appear to have posted a live example (https://jsbin.com/lufuxo/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by XhmikosR** [comment]
This is still valid.

I managed to pinpoint the version where this started to break. 3.1.1 works fine, 3.2.0 and on has the problem.

We really need to find a solution for this.

**Comment by XhmikosR** [comment]
Actually, scratch that. The issue I see is different than this.

Something changed with the navbar's height.

**Comment by BroZeus** [comment]
Adding height and overflow styling with important tag after boostrap css has been included seems to fix problem for me. Here's how : 
`<style>
.navbar .navbar-collapse.in
{
max-height:300px!important;
overflow-y:scroll!important;
overflow-x:hidden!important;
}
</style>`

**Comment by exnariman** [comment]
I can confirm @BroZeus solution works.

**Comment by the94air** [comment]
yaaa  @BroZeus  way work very fine

**Comment by betterm** [comment]
@BroZeus solution works

**Comment by DaniSpringer** [comment]
@BroZeus still works. Personally had to change max-height to `340px`

**Comment by allurewebsolutions** [comment]
Instead of setting a max-height that may be less than optimal you could go with:

`.navbar .navbar-collapse.in {
      max-height: 100vh !important;
      overflow-y: scroll !important;
     overflow-x: hidden !important;
    }`

**Comment by niftylettuce** [comment]
thanks @allurewebsolutions, including this by default with https://crocodilejs.com

**Comment by troytempleman** [comment]
This might be even better, so that your nav can go to the bottom if necessary:

`.navbar .navbar-collapse.in { max-height: 80vh !important; overflow-y: scroll !important; overflow-x: hidden !important; }`
