### ISSUE TITLE
sticky :hover on mobile causes bad UX for button checkbox/radio groups toggle

### ISSUE THREAD

**Issue by iatek** [twbs/bootstrap#12832]
It looks like `data-toggle="buttons"` does not correctly toggle the button state on mobile devices..

You can see this behavior here:

http://www.bootply.com/render/116436

Tested on iPhone (iOS7)

**Comment by mdo** [comment]
Punting this to v4.

**Comment by cvrebert** [comment]
Docs to crib from:
https://github.com/google/WebFundamentals/blob/44c287c222dd6ede629a700ac3ddd8112674c46e/src/_langs/en/fundamentals/input/touch/activestates/index.markdown

**Comment by cvrebert** [comment]
Final note: We're looking at making`:hover` and `:active` styles more distinct from each other in Bootstrap v4.
