### ISSUE TITLE
Improve accessibility for the carousel plugin

### ISSUE THREAD

**Issue by bassettsj** [twbs/bootstrap#13556]
I do like that the carousel is discouraged entirely if you care  at all about accessibility, which you should, but if bootstrap is going to still support the thing, can we look at including the changes from [Paypal's a11y bootstrap plugin](https://github.com/paypal/bootstrap-accessibility-plugin/#carousel)?

### Carousel
1.~~Prevent automatic cycling of the carousel.~~
2. ~~Prevent wrapping to first item on next button navigation or wrapping to last item on previous button navigation.~~
3. ~~Add role of listbox for carousel div.~~
4. Add ARIA role of option, aria-selected, and tabIndex for individual carousel items.
5. ~~Add role of button for previous and next anchor links and a hidden screen reader text of "Previous" and "Next".~~
6. ~~Add keydown event listener for the carousel to work with keyboard.~~
7. Dynamically change tabIndex and aria-selected property of active and inactive tabs.
8. Remove display:none and hide (offscreen) of the inactive carousel items, so that screen readers can count the total number of carousel items.

**Comment by mdo** [comment]
What's the status of this?

/cc @patrickhlauke

**Comment by juthilo** [comment]
Is there anything in here not covered by #14097 or can we close this/punt to v4 as well?

**Comment by jongund** [comment]
Please review the latest version of the PayPal Accessibility Plugin Carousel Accessibility features:

See example that also outlines the feautres:
http://jongund.github.io/aria-examples/bootstrap-carousel/carousel-3.html

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
