### ISSUE TITLE
affix-top is not applied properly on Windows Chrome (& IE11?)

### ISSUE THREAD

**Issue by xPaw** [twbs/bootstrap#13613]
It is possible to go to the top of the page, without the plugin assigning affix-top classname.

Here's an example:
![14 05 16 6cwp5](https://cloud.githubusercontent.com/assets/613331/3001517/1d0a574c-dd31-11e3-875b-d496d697100a.png)

It's really easy to reproduce by pressing `end` and then `home` buttons.

**Comment by mdo** [comment]
Punting on this for v4.
