### ISSUE TITLE
Only react to keydown in `role=listbox` when it actually is a dropdown

### ISSUE THREAD

**Issue by canibanoglu** [twbs/bootstrap#13956]
Hello,

I have noticed that Bootstrap will initialize a Bootstrap widget whenever it sees an element with ``role=listbox`` but this has some side effects when you're working with other libraries, such as Kendo UI. As such, when ``bootstrap.js`` is included in a project which also uses Kendo UI and when one initializes a KendoDropDownList that element will respond to events defined in both frameworks and that can have some adverse effects.

Shouldn't Bootstrap also check whether the element's class list contains one of Bootstrap's classes?

Thought of filing this issue for Kendo but upon further thought, ``role=listbox`` might affect other libraries out there, so decided to file it here. 

There are a couple of different solutions to this and as soon as I get some feedback I could make a PR to implement the change(s).

Thank you!

**Comment by mdo** [comment]
Punting given backward compatibility concerns and age of PR.

**Comment by mikestu** [comment]
Does "Punting" mean you will never fix it, because it is just old?  Could you please clarify why this was just closed?  Thanks!

**Comment by kkirsche** [comment]
Age and punting means usually that won't be in V3 but if the issue still occurs and is causing problems in V4 it will be able to be revisited with a new issue. Mdo may have meant something slightly different, but that's my understanding.

**Comment by mikestu** [comment]
If I can even find where we hit this with a project, I will try to repro it one day if that project is upgraded to V4 in the future.  I will point out that this was a confirmed bug by multiple individuals though, so it would have been nice if the milestone were just changed to V4 instead...it's your project though.  Thanks...

**Comment by Casimodo72** [comment]
Version 3.3.5 healed a related or this issue for me - I used 3.3.4 before that. Before that version, Kendo UI's DropDownList closed and opened on every arrow key stroke (up/down).
