### ISSUE TITLE
Popover text being cut off in docs example

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#13969]
Originally from [here](https://github.com/twbs/bootstrap/issues/13937#issuecomment-47287168)

![2014-06-27_01-11-21](https://cloud.githubusercontent.com/assets/349621/3405593/41826092-fd7f-11e3-8e48-776ba102ea1e.png)

**Comment by mdo** [comment]
Adjusting the width of a popover feels wrong. Tooltips, sure, but popovers feel like more important elements and should be more carefully placed in your pages. For our docs, we're kinda fucked, unless we simply reorder those buttons (which I'd accept a PR for here in v3).
