### ISSUE TITLE
Tooltip unnecessarily breaks into multiple lines when positioned to the right

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap#13987]
A tooltip breaks into multiple lines when it is positioned to the right, even though there is enough space for it to move further to the left. This doesn't happen if it is positioned to the left.

See [this example](http://jsbin.com/xugez/1). (Uses #13718.)

---

Split out from https://github.com/twbs/bootstrap/issues/13902#issuecomment-46882090

**Comment by mdo** [comment]
Punting as a won't fix—v4 includes a new positioning library for our affix, tooltips, and popovers.
