### ISSUE TITLE
Scrollspy detect links with absolute urls

### ISSUE THREAD

**Issue by danschumann** [twbs/bootstrap#14187]
So I had a scrollspy not working and I had to read the source to discover the problem.  Not too bad, but I wonder if it could be more programmer friendly.

Currently, it listens only to links that begin with `#`, however links on my page `/section/help` were `/section/help#hash`.  I figure you could detect the `location`,

Would it be more programmer friendly to also match `help#hash`, `/section/help#hash`, `http://samedomain.com/section/help#hash`?

something like this?

    var relativeURL, linkURL, match;

    // href = anchor href

    // match last part of url
    relativeURL = /[^\/]+$/.exec(location.pathname);

    // matches url parts before the hash in the anchor href
    linkURL = /[^\#]*(?=#)/.exec(href); 

    relativeURL && (relativeURL = relativeURL[0]);
    linkURL     && (linkURL = linkURL[0]);
    match = (linkURL &&
      (
        // relative
        linkURL == relativeURL ||
        // absolute
        linkURL == location.pathname || 
        // domain with no trailing / in link
        linkURL == location.href || 
        // domain with trailing /
        linkURL + '/' == location.href
      )
    )

There may be some edge cases with ending slashes anyway.  Also, there would be issues with /section/index.html not matching /section.  There may be better code out there that already detects urls in a better way.

**Comment by DArtagan** [comment]
Maybe I took way too simplistic/naive approach to this:

In .map of scrollspy I replaced `var $href = /^#./.test(href) && $(href)` with:
```javascript
if (/.*#\w*/.test(href)) {
    var $href = href.match(/#\w*/)[0]
}
var $href = $($href)
```
Please, someone point out what I'm overlooking and how this is likely to fail catastrophically.

**Comment by cvrebert** [comment]
@DArtagan `\w` ==== `[A-Za-z0-9_]`
Even HTML4 allows some additional punctuation besides underscores, and HTML5 is extremely liberal about what's permitted as an `id`: https://mathiasbynens.be/notes/html5-id-class

**Comment by DArtagan** [comment]
Right, totally, thanks @cvrebert.  How about just a complete wildcard after the hash?

**Comment by kkirsche** [comment]
For HTML 4, the answer is technically ([Source](http://www.w3.org/TR/html4/types.html#type-id)):
<blockquote>
ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
</blockquote>

HTML5 is more liberal allowing almost anything ([source](http://www.w3.org/TR/html5/dom.html#the-id-attribute):
<blockquote>
...must contain at least one character. The value must not contain any space characters.

There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
</blockquote

**Comment by cvrebert** [comment]
So, we got sidetracked a bit here. Supporting HTML5's more liberal IDs, which seems pretty simple and has been done in some other parts of the code (e.g. a87b150bc771e3bc6e62fd2ca8a4ea938c48e28c), isn't actually germane to this issue. 
The tricky part for this issue is properly dealing with `http://same.domain/same-page#myfragment` vs. `http://external.domain/bar#myfragment` vs. `/other-page#myfragment`

**Comment by mdo** [comment]
Punting as a won't fix for now, in both v3 and v4.

**Comment by cervengoc** [comment]
Why not just simply matching for example the current `location.pathname` against the link's `href`, and if it's the same,, treat it as an internal `#` navigation.
