### ISSUE TITLE
Option for automatically making button doing a toggle 'pushed' while toggle open

### ISSUE THREAD

**Issue by tjcrowder** [twbs/bootstrap#14679]
Since Issue #7011 has been declined, a much more limited use case: A means of specifying that a button with `data-toggle` will show "pushed" when the toggle is open (or optionally, when it's closed). For instance, a button that shows a dropdown would be pushed while the dropdown is showing, and not when it isn't.

One possibility would be a `data-push` attribute:

    <button data-toggle="dropdown" data-push="open">Open The Thingy</button>

Possible values for `data-push`:

1. "open" - Show button pushed when toggle is showing something, not pushed when not showing the thing.
2. "closed" - Opposite of "open"
3. No value at all (e.g., `<button data-toggle="dropdown" data-push>Foo</button>`): Same as "open"

**Comment by cvrebert** [comment]
@tjcrowder Could you give an example of a use-case you're currently having trouble with that this feature would solve?

**Comment by mdo** [comment]
Punt on adding this to v3?

**Comment by mdo** [comment]
Punting.

**Comment by patrickhlauke** [comment]
If the button is part of a disclosure widget (e.g. it opens/closes a menu, or a panel) it would/should have an `aria-expanded` boolean that gets set...this could be used for styling purposes, without inventing a new attribute.

**Comment by tjcrowder** [comment]
@cvrebert : Sorry, I didn't get notified of your comment. Use case is really simple: We want the button that opens/closes a drop-down to show pushed when the dropdown is open.

@patrickhlauke : That's an okay workaround, but of course means we have to repeat the styling that's already specified for pushed buttons. Another way we can work around it, without having to repeat the styling, is to listen for dropdowns opening, find the relevant button, and add the `active` class to it. If Bootstrap optionally added the `action` class, boom, we'd be done.

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 1:17 AM, "T.J. Crowder" <notifications@github.com> wrote:
>
> @cvrebert : Sorry, I didn't get notified of your comment. Use case is
really simple: We want the button that opens/closes a drop-down to show
pushed when the dropdown is open.
>
> @patrickhlauke : That's an okay workaround, but of course means we have
to repeat the styling that's already specified for pushed buttons. Another
way we can work around it, without having to repeat the styling, is to
listen for dropdowns opening, find the relevant button, and add the active
class to it. If Bootstrap optionally added the action class, boom, we'd be
done.
