### ISSUE TITLE
Affix problem, bouncing at the bottom on scroll

### ISSUE THREAD

**Issue by bjorncm** [twbs/bootstrap#14738]
It think it has something to do with the PPI or resolution of the screen, because the problem only occurs on tablets and small notebooks.

Screenshot attached of the bootstrap website:
![schermafbeelding 2014-10-06 om 15 47 19](https://cloud.githubusercontent.com/assets/3530597/4526535/21c4bf4e-4d60-11e4-8f4f-3b83a1ca4ebe.png)

Screenshot taken on a 13" Macbook Air with Chrome 37.0.2062.124 and Mac OS X 10.8.5

**Comment by mdo** [comment]
Punting on this for v4.
