### ISSUE TITLE
Tooltip don't respect dynamically changed title attribute

### ISSUE THREAD

**Issue by valllabh** [twbs/bootstrap#14769]
Tooltip don't respect dynamically changed title attribute.

**Comment by addremove** [comment]
Similar issue here. The dynamic title option doesn't update the tooltip content either.

**Comment by Isaac-Kleinman** [comment]
I believe the dynamic title option is not working due to this issue: #15359; the value of the `title` attribute gets removed and added to the `original-title` attribute.

**Comment by mdo** [comment]
Closing as a dupe bug report of #15359.

**Comment by BDhara** [comment]
try this 
$('a[rel="tooltip"]').tooltip({
                    placement: 'right',
                    animated: 'fade'
                }).attr('data-original-title', 'Dimension:' + data[n].Dimension );
