### ISSUE TITLE
scrollspy.js: multiple data targets

### ISSUE THREAD

**Issue by toxsid** [twbs/bootstrap#14776]
I was working on a project that needed two scrollspy data targets on a single page. I hope in future releases scrollspy.js can support multiple menus. In the meantime I have come up with a hack-ish solution to get it to work so you can see how other users may want to implement:

http://jsfiddle.net/MUpz5/50/

**Comment by cvrebert** [comment]
Added to our internal list for consideration for Bootstrap v4.
