### ISSUE TITLE
iPad modal <select> bug

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#14975]
When popping up a modal on a page that is scrolled down, then opening a `<select>` within the modal, the page jumps up. All elements on the modal are shifted in a way that they no longer line up with the actual visuals. It's tough to explain, so I put together a demo:

https://github.com/CaptSaltyJack/bootstrap-select-bug

Once it's broken and the modal button and dropdown no longer work, try tapping slightly above them. You'll see what I mean about the touch areas being displaced. Once you scroll to the top of the page, the modal elements work again as expected.

**Comment by hkailantzis** [comment]
had same problem in one of our projects. setting oveflow:hidden and position:fixed to the body (to really disable page scrolling in iOS), seems to solve it, in my case. iPad Mini, iOS 8.4. Looks like iOS/Safari issue still.

**Comment by cvrebert** [comment]
Was able to reproduce this on Sauce Labs in the iPad simulator running iOS 8.4.
iPad uses a different `<select>` menu widget than iPhone, and I couldn't manage to repro this on an iPhone.

**Comment by cvrebert** [comment]
Still repros with iOS 9.0 and iOS 9.1 beta.

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=150079

**Comment by Tiendq** [comment]
Can someone confirm if this issue is fixed? I see the WebKit bug Resolved/Fixed but still experience it with BS4 (alpha 5) on iOS 10.2

**Comment by cvrebert** [comment]
Most likely the WebKit version with the fix has not yet made its way into an iOS release. Not every iOS release updates WebKit.
