### ISSUE TITLE
call popover('show') when the trigger is 'manual' change configuration

### ISSUE THREAD

**Issue by rkmax** [twbs/bootstrap#15027]
Example

I have a element list with a css class `has-my-popover` and i setup popover with the following

```javascript
$(document).popover({
  'selector': '.has-my-popover',
  'trigger': 'manual'
});
```

if i click over the element the popover isn't showed and that's good. Now when i execute `$('.has-my-popover').eq(1).popover('show')` the popover is showed i expected but if i clicks the element the popover hides and if clisc again the popover is showed. i want trigger to continue working manual

**Comment by cvrebert** [comment]
@hnrch02 Seems like this is just a misunderstanding of how the plugin works rather than any actual bug. Can we close this?

**Comment by hnrch02** [comment]
Yeah.
