### ISSUE TITLE
Document how to properly handle modals with dynamic content height

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap#15106]
Modals with dynamic content height should call `$('#myModal').data('bs.modal').handleUpdate()` whenever the content updates. Only necessary when the update happens while it is shown though.

**Comment by ghprod** [comment]
for now i call it manually .. and its worked .. thanks ;)

```
$('#myModal').data('bs.modal').handleUpdate()
```

**Comment by jfjauvin** [comment]
Until this gets resolved, I created a passive fix:
(Using v3.3.2)

```
$(document).on('shown.bs.modal', function (e) {
	$(e.target).before($(e.target).find('.modal-backdrop').clone().css('z-index', $(e.target).css('z-index')-1)); 
	$(e.target).find('.modal-backdrop').removeClass('in').css('transition', 'none');
});

$(document).on('hide.bs.modal', function (e) {
	$(e.target).prev('.modal-backdrop').remove();
});
```

**Comment by xtrepo** [comment]
position: fixed;
  bottom: 0;
  right: 15px;
