### ISSUE TITLE
Horizontal scrollbar in docs

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#15100]
For example, in http://getbootstrap.com/css/ happens for width >=768px and <= 782px

![2014-11-12_19-17-48](https://cloud.githubusercontent.com/assets/349621/5014750/efe4dbe0-6aa0-11e4-92fb-21fec86544c4.png)

/CC @mdo

**Comment by ncla** [comment]
This also seems to happen if you have a `.container` inside `.container-fluid`, although the documentation says that
> Note that, due to padding and more, neither container is nestable.

**Comment by cvrebert** [comment]
@mdo Ping. Any thoughts on @XhmikosR's suggestion/findings?

**Comment by XhmikosR** [comment]
Not sure if it's worth spending any time on this since v4 will change
stuff. Though personally I'd like to have this sorted regardless.
