### ISSUE TITLE
Clarification on "Context-specific usage"

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#15130]
Currently, at the end of http://getbootstrap.com/css/#buttons-disabled there's the callout:

> Context-specific usage
> While button classes can be used on `<a>` and `<button>` elements, only `<button>` elements are supported within our nav and navbar components.

I'm not quite clear here what exactly this refers to...is it related just to the ``.disabled`` class, as that's the heading/section this callout is under? Or does it also apply to ``.active``, in which case this needs to be "one level up" in terms of where it's located in the doc's hierarchy?

Further, does the second part of the sentence actually mean "... , they are only supported for ``<button>`` elements when used within a nav or navbar component." ?

/cc @cvrebert

**Comment by mdo** [comment]
Closing as I think the changes that need doing are done here.
