### ISSUE TITLE
The .navbar-toggle Button Moves Outside the Viewport

### ISSUE THREAD

**Issue by bobmclaren** [twbs/bootstrap#15155]
The .navbar-toggle button that displays when .navbar-fixed-top bar collapses does not behave correctly under Safari for iOS.

As shown in the link below, when opened in Mobile Safari, the .navbar-toggle button moves outside the viewport off to the right, stretching to the width of the body content.

http://s.bootply.com/render/07oYTfT72j

This may be a bug in Safari, as this behavior does not occur in Mobile Chrome.

**Comment by mdo** [comment]
Punting as a won't fix given the changes coming in v4 for navbars.
