### ISSUE TITLE
Prevent Tab link to add active class to Parent li

### ISSUE THREAD

**Issue by moinakbarali** [twbs/bootstrap#15186]
When I click on a link which has `data-toggle="tab"` inside `li` it automatically add `active` class to parent `li`.

Is there a way I can prevent bootstrap tabs link to add `active` class to current parent `li` because I want to do it manually?

**Comment by mdo** [comment]
I don't think we'll be adding anything to the project to do this. Thanks though.

**Comment by redbmk** [comment]
@mdo, Does [this line](https://github.com/twbs/bootstrap/blob/master/js/tab.js#L91) in tab.js not seem like it is unintentionally always adding the `active` class to the dropdown? An example would be if you had tabs nested inside a dropdown. It seems like a bug and this one-line fix might solve @moinakbarali's issue:

```diff
-      if (element.parent('.dropdown-menu')) {
+      if (element.parent('.dropdown-menu').length) {
```

**Comment by cvrebert** [comment]
Yeah, that's definitely a bug. Opened #15630.
