### ISSUE TITLE
JQMIGRATE: jQuery.fn.attr('checked') may use property instead of attribute 

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#15190]
Hey guys,

I noticed that jQuery Migrate complains about the use of .attr throughout Bootstrap and was wondering if you would be interested in having a pull request made that changes all .attr's to .prop's to avoid these warnings.

Thanks guys!

-Kevin

From jQuery Migrate:
__JQMIGRATE: jQuery.fn.attr('selected') may use property instead of attribute__

__Cause:__ Prior to jQuery 1.9, $().attr("checked") etc. would sometimes use the checked|selected property instead of the attribute when interacting with non-XML elements, despite the fact that browsers and the HTML specifications allow the properties (current state) to differ from the attributes (initial/default state). This was a holdover from earlier versions of jQuery that did not offer $().prop.

__Solution:__ Boolean properties should generally not be passed to $().attr at all; replace with $().prop unless you truly intend to update the underlying HTML attribute.

**Comment by cvrebert** [comment]
@kkirsche Could you point out some specific problematic sections of the code? Thanks!

**Comment by kkirsche** [comment]
I believe I may have been mistaken and it was through implementation of it through AngularJS that I saw it pointing to bootstrap in the stack trace. 

I'll make a final check on that tomorrow morning and let you know for sure so this can be closed if necessary. Sorry for the inconvenience.

**Comment by cvrebert** [comment]
Thanks for double-checking :smile:
