### ISSUE TITLE
Standalone Collapse Component Broken

### ISSUE THREAD

**Issue by bakim** [twbs/bootstrap#15201]
Went through Bootstrap 3's customize and removed all but navs / navbar / forms for css.
Downloaded JS Component for Collapse
HTML Markup is copy-pasted exactly as is from online documentation  

Attempted to recreate collapse menu and the styling works, but the nav menu's initial state at the 767px
default breakpoint for col-sm remains open. The button to toggle the nav visibility sets attribute aria-expanded="true" but the menu remains open.  
Please advise.

**Comment by cvrebert** [comment]
Closing due to lack of response from OP.
