### ISSUE TITLE
scrolling DOM element with popover attached to .btn-group 

### ISSUE THREAD

**Issue by asong91** [twbs/bootstrap#15223]
If a popover is generated on a .btn-group documentation states that "container: "body"" must be included. If the button is in a scrolling div though, the popover won't stay attached when scrolled. Excuse my messy example, but here it is demonstrated: http://jsfiddle.net/Br4Zg/1003/

**Comment by peterblazejewicz** [comment]
The fix for @asong91 use-case is to use some parent of button/input group as container (`.td-container` would work). Maybe dropping specific selector from documentation will be sufficient?

> When using popovers on elements within a .btn-group or an .input-group, you'll have to specify the option `container` (documented below) - usually using `body` selector or in some cases (like scrolled content) other parent element of these components

**Comment by mdo** [comment]
Punting as a won't fix for now, but I *believe* this is going to be addressed in v4's redone JS.
