### ISSUE TITLE
Fire an event when the current tab is clicked

### ISSUE THREAD

**Issue by eca-readonly** [twbs/bootstrap#15233]
Currently when the active tab element is clicked (aka re-selected) no event is fired,
something similar to **shown.bs.tab**

**Comment by cvrebert** [comment]
@eca-readonly What's you use case? Seems simple enough to setup your own click handler for that niche case.

**Comment by kkirsche** [comment]
@cvrebert didn't make the issue but would it be worth adding to easily allow AJAX functions to be called if a tab is re-selected. Essentially assuming a user would expect clicking it again to refresh the tab and  check for new data? I believe a custom button to refresh would be clearer but figured I'd offer a possible use case.

**Comment by mdo** [comment]
Punting on adding this to v3.
