### ISSUE TITLE
Affix jumps before returning to its original position

### ISSUE THREAD

**Issue by enriqg9** [twbs/bootstrap#15248]
Heres a [JSFiddle](http://jsfiddle.net/enriqg9/516pbyyn/) using BS 3.3.1 to better explain my problem. This does not happen in this [fiddle](http://jsfiddle.net/enriqg9/8nkndpen/) using BS 3.0.0.

To replicate scroll past the blue header in the fiddles then slowly scroll back up until you reach the blue header again. You'll see that in BS 3.0.0 the affixed div returns to its original position without jumping.

**Comment by tobscure** [comment]
Same issue here.

**Comment by enriqg9** [comment]
This was fixed in [3.3.2](http://jsfiddle.net/enriqg9/gr2mg4bt/)
