### ISSUE TITLE
Popover stays hidden if closed by a double-click

### ISSUE THREAD

**Issue by morille** [twbs/bootstrap#15251]
Bootsrap 3.3.1 on Chrome 39 and Windows 8
You can check directly with the live demo from the doc: http://getbootstrap.com/javascript/#popovers
Just click one time one the button to open the popover, then double-click the button, the popover hides and won't show again.
Seems that in the "Tooltip.prototype.hide" complete function, forcing to always detach the tip fixes that issue.
Cheers,
Romain.

**Comment by cvrebert** [comment]
Confirmed as of v3.3.2 on OS X Chrome.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
