### ISSUE TITLE
Stateful button example javascript code is misleading

### ISSUE THREAD

**Issue by thawn** [twbs/bootstrap#15276]
Here is the example code from the documentation
```javascript
<script>
  $('#myButton').on('click', function () {
    var $btn = $(this).button('loading')
    // business logic...
    $btn.button('reset')
  })
</script>
```
However if I replace //business logic with some simple code that does an expensive calculation or with loading an external website (exactly the kind of operation where you need the stateful button), the button changes state only after the code finishes execution and then quickly changes back.
What I needed to do to make this work was something like the code that makes the example on the getbootstrap.com website work. The timeout gives the browser time to render the change in the button:
```javascript
<script>
  $('#myButton').on('click', function () {
    var $btn = $(this).button('loading')
   setTimeout(function () {
       // business logic...
       $btn.button('reset')
   },100)
  })
</script>
```
I suggest to change the documentation example accordingly.

Here is a jsfiddle demonstrating the solution:
http://jsfiddle.net/kvsh7LuL/7/
Here is my question on stackoverflow
http://stackoverflow.com/questions/27169537

**Comment by thawn** [comment]
@peterblazejewicz 
Sorry for the late reply.
Your code works beautifully thank you very much. IMHO this code would be an ideal example for the documentation.

**Comment by peterblazejewicz** [comment]
@thawn You're welcome!

**Comment by thawn** [comment]
@patrickhlauke I think we could move forward with updating the documentation according to peter's example. If you agree, what would be the correct way to go about it?

**Comment by fat** [comment]
yeah… you just need to understand how event loops work – dont think it's up to our documentation to explain that
