### ISSUE TITLE
IE8 wraps label text when it shouldn't

### ISSUE THREAD

**Issue by borissamardzija** [twbs/bootstrap#15275]
Hello,

a [fix] (https://github.com/twbs/bootstrap/commit/6f6bce5944bd0e6ab36ab6b39339f381d8a80b2a) that solved https://github.com/twbs/bootstrap/issues/13141 is now causing another misbehavior of label in IE8 when using Bootstrap 3.3.1. Reverting to 3.1.1 solves that problem.

It seems that now label width cannot be correctly calculated and breaks when it's floating.

I believe that @ahocquet also noticed this and mentioned in https://github.com/twbs/bootstrap/issues/13141#issuecomment-49712359

For now, as a workaround for this problem, we detect ie8 using conditional comments and override max-width with something like this

```css
.lt-ie9 label {
	max-width: inherit;
}
```

**Reduced examples**

http://sandbox.boris-samardzija.from.hr/bootstrap/bootstrap-3.3.1.html
http://sandbox.boris-samardzija.from.hr/bootstrap/bootstrap-3.1.1.html

**Screenshots**

Problematic label wrapping in 3.3.1

![bootstrap-3 3 1](https://cloud.githubusercontent.com/assets/1290335/5278203/13876892-7ad7-11e4-945f-4a3f66713c4e.png)

Seems okay in 3.1.1

![bootstrap-3 1 1](https://cloud.githubusercontent.com/assets/1290335/5278205/1da5dafc-7ad7-11e4-9f6c-f1ac8dba4706.png)

**Comment by cvrebert** [comment]
JS Bin for posterity: http://jsbin.com/baqilu/2

**Comment by kkirsche** [comment]
Is there a reason we are using `display: inline-block` instead of simply `display: inline`? Changing to `display: inline;` fixes this issue in IE 8 with no noticeable issues in the JSBin on other browsers (that I can see). Let me know if you want this as a pull request

**Comment by kkirsche** [comment]
Just wanted to follow up regarding this and see if there is a reason we are using `display: inline-block` instead of simply `display: inline`?

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by cvrebert** [comment]
The last change was from `block` to `inline-block`, in fe8061b84ecdda5ea70514fe487e2f46564439e2.

**Comment by borissamardzija** [comment]
@kkirsche, try that on "Basic example" on http://getbootstrap.com/css/#forms and you will notice that there is difference in margins (bottom margin will be ignored).

Label element is inline by default, but in order to use margins and/or width/height, it must be `inline-block` or `block`.

This seems to be caused by unfortunate combination of `inline-block` and `max-width`, so I would suggest to find another solution for #13141 *which is also IE8 bug) that wouldn't stop us from using `inline-block` on labels (which is working okay in modern browsers).

**Comment by kkirsche** [comment]
I see what you mean @borissamardzija — thanks for sharing that example, I was just looking at the JSBin

**Comment by mdo** [comment]
Yup, for all the reasons @borissamardzija mentioned.

**Comment by mdo** [comment]
Punting as a won't fix as well for now.
