### ISSUE TITLE
Can dismissible popover work without href="#" ?

### ISSUE THREAD

**Issue by bartvanderwal** [twbs/bootstrap#15277]
The dismissable popover is not working for me in Bootstrap 3.3.1. No popup window appears anymore when I add a `data-trigger="focus"` attribute.

See this fiddle:
http://jsfiddle.net/bartvanderwal/qjaL0tp4/

By comparing it in detail with the standard Bootstrap example on your website I found out that this can be fixed by adding a `href="#'`. See this Fiddle:
http://jsfiddle.net/bartvanderwal/29hbf4no/

But I'd prefer not to need a `href` :smile:, and that does works for the non-dismissable version, so it'd be more consistent.

**Comment by cvrebert** [comment]
I tested http://jsbin.com/zuzoce/3 (which removes the `href="#"`) on all our supported platforms, and it seems to still work fine. And it's valid HTML5.
@patrickhlauke @mdo So, you guys okay with removing the `href="#"` from [the dismissible popover example](http://getbootstrap.com/javascript/#callout-popover-dismiss-click)?

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/zuzoce/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 17, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Removing the href is fine by me.

**Comment by Bounpakhong** [comment]
Why all you don't use `href="#_"` :)
