### ISSUE TITLE
Popover Position With Responsive Images in Content

### ISSUE THREAD

**Issue by drewcovi** [twbs/bootstrap#15282]
It seems that position for the popover is determined prior to any images being loaded in the popover content, which can often throw off placement substantially.

Is it simply not possible to have responsive layouts within popovers? Or is there a reason the popover can't wait for all content to be loaded first?

**Comment by mkorfmann** [comment]
I'm also having this issue.

**Comment by ilgooz** [comment]
+1

**Comment by fat** [comment]
adding a note to add a test for this in v4. in the meantime - you could preload your images in js
