### ISSUE TITLE
Enable possibility to use a jQuery element for scrollspy target

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [twbs/bootstrap#15301]
Currently it only allows a string selector.

I am using inside an angular directive that wraps the menu that uses scrollspy. The jquery element is instantiated elsewhere, so repeating the selector for the scrollspy declaration goes against the DRY principle (if I change the id, I need to remember changing in the Javascript side):

```javascript
link: function( scope, element ) {
	$( "body" ).scrollspy({
		// "element" is the target I want to use here,
		// there is no need to repeat the selector
		target: "#chapter-menu"
	});
}
```

**Comment by mdo** [comment]
Is this something we need to leave open as a fix for v3 @cvrebert, or do we punt on it?

**Comment by FagnerMartinsBrack** [comment]
I edited the original post to clarify the issue.

I don't know what "punt" would mean here, but I just want to point out this is a valid use case. As far as I know Bootstrap should act as a middle man between development strategies and UI behavior, building the APIs without destroying the benefit of separation of concerns between DOM elements and behavior for other frameworks or development practices.

That is much more reasonable if the fix represents a simple change in a configuration input.

**Comment by mdo** [comment]
We're punting—closing—any issues that are feature requests as v3 won't be having any new features on account of us trying to get v4 out. I'm asking if we believe this to be a feature request or an important (bug) fix worthy of adding to v3.

**Comment by fat** [comment]
hm yeah it is a feature request – that said, i'm surprised the api was like that to begin with, we're usually pretty good about accepting jquery like objects. i'll add a note for this for v4, thanks for reporting
