### ISSUE TITLE
Collapse with parent assumes .panel

### ISSUE THREAD

**Issue by alexrussell** [twbs/bootstrap#15341]
The collapse plugin, when used with `data-parent="{selector}"`, appears to assume that you are using panels (presumably because of the original accordion use-case). [Line 49 of the plugin](https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L49) has a specific reliance on `.panel` in the code, but is there any reason for this? I have code that has a similar close-all-others-within-a-container mechanism, but has very little need of using panels. Is this something that can/should be changed (now that #15241 is merged, reducing the emphasis on accordions using panels) or is there a good reason for the reliance on panels?

**Comment by cvrebert** [comment]
@fat I believe we decided to punt this to v4, correct?

**Comment by mdo** [comment]
Yeah this will change in v4.
