### ISSUE TITLE
In Chrome/Safari, iframe inside a modal makes the main window scroll when iframe src contains a hashbang

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [twbs/bootstrap#15349]
Window 7 x64
Chrome 39.0.2171.95 m

**Description**:
When changing the src of an iframe and that src contains a hashbang, the browser native scrolling makes the `top` window also be scrolled. I could reproduce when changing the src after a modal is shown and the body of the modal contains the iframe element.

**Reproducing**

I couldn't manage to make it work in a JSfiddle and it seems the problem requires that the files are served through a server, so I prepared the steps to reproduce the issue (file contents below):

1. Install node-static to start a basic server

```shell
$ npm install -g node-static
```

2. Run the following command in the directory where lies the files `test.html` and `inner.html`

```shell
$ static -p 8000
```

3. Access `http://localhost:8000/test.html`
4. Position the scroll in the top (it will be default the first time you access, of course)
5. Click in the first button

What happens? The top window (the one containing the iframe) will scroll down when the iframe window jumps to the hashbang target.

It strongly feels like a browser issue, since it only happens on Windows 7 x64 in "Chrome 39.0.2171.95 m" (and "Safari 5.1.7 (7534.57.2)"), but I choose to report here because it may be related to the way bootstrap modals are built.

Doesn't happen on Windows 7 x64 in Firefox 34.0, IE 11.0.9600.17501 and Opera 12.16 build 1860.

### Files

They are all self contained, put them in the same directory (or use the plunkr below).

**test.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.js"></script>
  </head>
  <body>
    <div class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Modal</h4>
          </div>
          <div class="modal-body">
            <iframe></iframe>
          </div>
        </div>
      </div>
    </div>
    
    <script>
    $( ".modal" ).modal({
        show: false
      })
      .on( "shown.bs.modal", function() {
        $( ".modal" ).find( "iframe" )[ 0 ].src = "inner.html#target";
      });
      window.preview = function() {
        $( ".modal" ).modal( "show" );
      };
    </script>
    
    <textarea rows="20"></textarea>
    <div>
      <button onclick="preview()">
        Click and window will scroll down
      </button>
    </div>
    
    <textarea rows="20"></textarea>
    <div>
      <button onclick="preview()">
        Click and window will scroll down
      </button>
    </div>
    
    <textarea rows="20"></textarea>
    <div>
      <button onclick="preview()">
        Click and window will scroll down
      </button>
    </div>
    
    <textarea rows="20"></textarea>
    <div>
      <buttononclick="preview()">
        Click and window will scroll down
      </button>
    </div>
  </body>
</html>
```

**inner.html**
```html
<div style="padding-top: 5000px">
  <p id="target">
    This scrolling is a problem *devil*  -->
  </p>
</div>
```

http://plnkr.co/edit/ph2j5xkCYNMbXGx3o1Nf?p=preview

**Comment by cvrebert** [comment]
I can confirm this on OS X Yosemite in Safari 8.0.3 and Chrome 40. Doesn't happen in Firefox.

**Comment by cvrebert** [comment]
The problem isn't specifically Bootstrap-related. Here's a Bootstrap-free version of your Plunk that exhibits the same bug: http://plnkr.co/edit/bKBag3Tfs5QYvwywMk24?p=preview

So this is definitely a browser bug rather than a Bootstrap bug.
I would encourage you to file bugs with Chromium and WebKit regarding this (see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#reporting-upstream-browser-bugs if you need info on how to do that).
But I don't see any reasonable workaround we could apply for this at the Bootstrap level.

**Comment by FagnerMartinsBrack** [comment]
@cvrebert Did you managed to find out what is the exact problem?

**Comment by FagnerMartinsBrack** [comment]
https://code.google.com/p/chromium/issues/detail?id=462809&thanks=462809&ts=1425085817

**Comment by cvrebert** [comment]
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=148626
