### ISSUE TITLE
How to avoid tooltips adding `title` & `data-original-title` attributes to DOM?

### ISSUE THREAD

**Issue by ricardopolo** [twbs/bootstrap#15359]
In Bootstrap Tooltip.js you can use HTML data attributes to define title of the tooltip
````html
<button data-toggle="tooltip" data-placement="left" title="Tooltip on left">Button</button>
````
And then using Javascript intialize it
````js
  $('[data-toggle="tooltip"]').tooltip()
````

We have a requirement where we need tooltips without modifiying the HTML (using data attributes). The tooltips are shown in the WYSIWYG [Summernote](https://github.com/summernote/summernote) editor and we don't want the user change them using the HTML editor.

So we initialize the tooltips using only Javascript. The title and the placement are specified using JS and not HTML.
````js
  $('[data-toggle="tooltip"]').tooltip({ 'placement': 'left' , 'title' : 'Toolt on left'})
````

It works. Shows the tooltip as expected but it changes the HTML adding this attributes to the element 
```html
data-original-title="" title=""
```

Do you know why this happen? Do you know if we can avoid this feature and not modifiy the HTML after the tooltip is shown? If not, can we work in a PR to avoid this feature?

Thanks

**Comment by aug-riedinger** [comment]
This is #14769 I'd like to discuss, but it has been closed in favor of this one, while I'm unclear on how those two are related.

Basically, I don't understand why not doint what @peterblazejewicz suggested: 

```
$btn.tooltip({
  title: function(){
    return $(this).attr('title');
  }
});
```

As far as I am concerned, I see the tooltip as a title improved (as the `title` attribute cannot really considered as a UI element as it is now). For this reason, I completely makes sense to read its value when displaying the title.

I guess I'll have to customize my own version of bootstrap again on this.

Thanks for any replies

**Comment by DumboJet** [comment]
+1
This always created problems for me.

**Comment by MadLittleMods** [comment]
:+1:

**Comment by akolechkin** [comment]
:+1:

**Comment by koxu1996** [comment]
I found solution here: http://stackoverflow.com/questions/27235776/can-i-still-use-the-title-attribute-on-bootstrap-popovers Add ```data-selector="true"``` and you will get original title working.

**Comment by webjohan** [comment]
Some WCAG validators doesn't like empty title attributes for links and reports errors.

Suggested improvement:

Let the show/hide functions handle the removing/clearing of the title attribute.

show:
(when setting attribute aria-describedby)
Remove title/set title empty

hide:
(when removing aria-describedby)
add the original title back to title-attribute

getTitle:
Don't set title=''

Is this a possible solution?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by 1dd0** [comment]
just set `selector: true` property to avoid using (and fixing/overeriding) target element title attribute

**Comment by jcmalek** [comment]
This is still an issue in v4 of Bootstrap.

**Comment by cvrebert** [comment]
Given the massive changes in v4, I'd advise opening a new issue for any current problems.
