### ISSUE TITLE
Content outside modal still accessible while modal is shown

### ISSUE THREAD

**Issue by tejastank** [twbs/bootstrap#15389]
Hello,

Model popup works fine with desktop layout and during popup not allow to edit back container or back page.

But same things in mobile devices issue, during model popup, it easily allows to edit background content or page even it model.

Things works well in desktop layout, same not work on mobile layout.

Its critical bug on bootstrap framework, I hope you test same and fix it quickly. 

If any things I miss, please let me guide.

Thanks,
Tejas Tank.
SnippetBucket.com
https://twitter.com/snippetbucket

**Comment by cvrebert** [comment]
Closing due to lack of response.

**Comment by tejastank** [comment]
I had build application where dynamic model is created and shown.

Its working fine and not allow to access back container, but in mobile device it react differently.

My App is private can't share live access, but I will try do send sceenshot or test....


Thanks,

**Comment by cvrebert** [comment]
Screenshots don't help. We need a live example/testcase of some kind (e.g. JS Bin).
If you post such an example/testcase, I will be happy to reopen this bug.
