### ISSUE TITLE
Affix flickering in Chrome when there is an iframe containing Flash object

### ISSUE THREAD

**Issue by stalinone** [twbs/bootstrap#15390]
Browser: Chrome 39.0.2171.71 (Win 7, Win 8.1)
Bootstrap version: 3.3.0+

I put my code in gist [here](https://gist.github.com/anonymous/0316e5b716395f57c2eb). On the top is a navbar set as affix, and on the right there is a iframe, with given width and height, contains only one Flash element. When I scroll down from the top of page using mouse wheel quickly, the affix element keeps flickering.

_(Disclaimer: to show the effect of iframe contains Flash object I randomly googled an example script from a commercial website called bannersnack.com.. not sure if this is appropriate)_

- I tested 3.2.0, 3.3.0, 3.3.1, and latest commit to `bootstrap.css` and `bootstrap.js` which is 181f4aebea957f364a1b42a6331d0fa4624cf5e9 . All 3.3.0+ can reproduce this problem. However, I found that if I mix the css from 3.2.0 with any version of `bootstrap.js`, it will not flicker.
- I tested Firefox 34 and IE 11, both seem freed from this problem.
- In the gist I styled `position: absolute` on the containing div, though the position/float seems have nothing to do with the flickering.
- I tried replacing Flash object as image, and it seems no flickering.

**Comment by cvrebert** [comment]
FWIW, I can't repro on Mac Chrome.

**Comment by cvrebert** [comment]
Seems reproducible in Win 8.1 Chrome 39 on Sauce Labs.

**Comment by cvrebert** [comment]
@fat Should we close this as a problem on Pepper Flash's side that we can't remedy from the Bootstrap side?

**Comment by stalinone** [comment]
Seems adding `.translate3d(0, 0, 0);` to `.affix` could workaround this problem but I'm well aware that there was tons of pain as this was reverted in 3e8cddf. Just leave these here for references.

**Comment by mdo** [comment]
Yeah, we can;t use the 3d hack.

**Comment by cvrebert** [comment]
@mdo What would be your opinion on closing this as CantFix?

**Comment by mdo** [comment]
Closing as a can't fix sounds fine by me.
