### ISSUE TITLE
npm package has some cruft in it

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15397]
e.g. There's no reason for it to include `/test-infra/`.
CC: @XhmikosR

**Comment by ZDroid** [comment]
I guess this is enough to be added in `package.json``:

```json
"files": [
  "fonts",
  "grunt",
  "js",
  "less",
  "Gruntfile.js",
  "LICENSE"
],
```

Note: Readme file is auto-included.

**Comment by XhmikosR** [comment]
So, @cvrebert do you want me to make a PR for this? Or @ZDroid maybe.

**Comment by cvrebert** [comment]
Yes. I don't plan to make any PR myself.
