### ISSUE TITLE
Popover doesn't typecheck result of content function

### ISSUE THREAD

**Issue by OlafurTr** [twbs/bootstrap#15400]
Content is referenced with an associative array of functions.

Saw this bug reported before in 3.1 but this is happening in 3.3.1

JSfiddle example: http://jsfiddle.net/Rufal/dcobygpo/4/

**Comment by cvrebert** [comment]
User-provided functions whose return values we should consider typechecking:
* Tooltip+Popover
  * `title`
  * `placement`
* Popover
  * `content`

**Comment by fat** [comment]
we are going to add more robust option typechecking in v4 - this is already being tracked. thanks!
