### ISSUE TITLE
Add search feature to the docs

### ISSUE THREAD

**Issue by wesleycoder** [twbs/bootstrap#15403]
Me and a lot of my colleagues would appreciate so much to have a search field in the site getbootstrap.com because many "starters" keep going back in the documentation and having trouble in finding some content.

What do you think about it?

**Comment by Tjoosten** [comment]
+1

**Comment by BytewaveMLP** [comment]
Though it might be a hard thing to implement, :+1:.

**Comment by technofreaky** [comment]
+1

**Comment by mdo** [comment]
This is coming for sure in v4. I'll look into implementing it in v3 as well.

**Comment by wesleycoder** [comment]
@mdo Thanks for the attention! :metal:
Should I keep this thread open till v4 :question:

**Comment by mdo** [comment]
I don't think there's anything super straightforward we can do to add search to v3.

The way we're doing it in v4 is with https://github.com/christian-fei/Simple-Jekyll-Search, which essentially requires the search results to be their own pages/posts. Currently we don't do that in v3, so the best we could do is use tags or categories. However, matching that and showing the relationship in the results sounds a little difficult and cumbersome.
