### ISSUE TITLE
.navbar-nav dropdowns can only be closed by tapping their .dropdown-toggle on touch devices

### ISSUE THREAD

**Issue by elstgav** [twbs/bootstrap#15405]
On the mobile navbar, dropdowns are set to `position: static` to override the `absolute` position they normally have. However this prevents the dropdown from having a z-index. The z-index is necessary to ensure the dropdown's contents appear above the `.dropdown-backdrop` on mobile.

To fix, set the mobile dropdowns to `position: relative`;

``` scss
  @media (max-width: @grid-float-breakpoint-max) {
    // Dropdowns get custom display when collapsed
    .open .dropdown-menu {
      position: relative;
      …
    }
  }

**Comment by cvrebert** [comment]
@juthilo @mdo @XhmikosR @hnrch02 Anyone else able to check whether the fix makes a difference for them? No difference for me on Android, and I don't own an iPad.

**Comment by kkirsche** [comment]
For me broken and fixed do the same functional thing but fixed changes the nav at height when in portrait mode on iPad 3 with iOS 8.1.3

**Comment by cvrebert** [comment]
What do you mean by "changes the nav at height"?

**Comment by hnrch02** [comment]
It makes a difference for me both on my physical device and in the simulator, see the following screencast:
![Screencast](https://cloud.githubusercontent.com/assets/1068978/6386209/d7d1804e-bd75-11e4-8bb7-55eab6e15057.gif)

**Comment by hnrch02** [comment]
Re

> What do you mean by "changes the nav at height"?

![Screencast](https://cloud.githubusercontent.com/assets/1068978/6386231/54ce75ca-bd76-11e4-9f54-5fa1bb206101.gif)

**Comment by cvrebert** [comment]
I would call that change in expansion behavior a bug, so the `position:relative` change doesn't seem acceptable in its current form, IMHO..

**Comment by elstgav** [comment]
I'm not able to reproduce the height issue on my iPad (iPad Air, iOS 8.2). At this point I'm pretty removed from the bug (haven't been working in Bootstrap for a while) and am okay with closing it; I don't think the bug with closing behavior was that major to begin with.

**Comment by mdo** [comment]
Punting for the time being then.

**Comment by julmot** [comment]
I just installed the latest bootstrap version and I am still not able to close the navbar dropdown on tap somewhere else than the dropdown toggle.

**Comment by julmot** [comment]
Using Fastclick fixes this issue as this triggers the click event on touchstart that would otherwise not get fired.
