### ISSUE TITLE
Inline forms are being displayed incorrectly in IE8

### ISSUE THREAD

**Issue by jonathannaguin** [twbs/bootstrap#15410]
Inline forms are supposed to be rendered as left-aligned. 
We can see this in Google Chrome and Firefox, but we are having problems with the same mark-up in IE8. 
What we are experiencing is:
- The label of an input group is displayed on top the group instead of on the left.
- The checkbox is displayed on top its label instead of being on its right.

This issue is easy to reproduce using the webpage of the project (http://getbootstrap.com/css/#forms).
I have attached a capture of this rendered in Google Chrome and another capture rendered in IE8.

> Notice I have removed the class "sr-only" from the username label so we can see clearly the problem with labels.

![capture google chrome](https://cloud.githubusercontent.com/assets/265395/5502467/72dbb662-8762-11e4-87bd-ba289c6910d3.png)
![capture ie8](https://cloud.githubusercontent.com/assets/265395/5502466/72d7c66a-8762-11e4-9cba-2a90506ae6a8.PNG)

**Comment by cvrebert** [comment]
Possibly related to #15275.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Probably punting as a won't fix honestly.
