### ISSUE TITLE
Glyphicon unicode BMP

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#15419]
Per @cvrebert:

> The `.glyphicon-door` and `.glyphicon-key` added by this are outside of the Unicode BMP, which will cause a partial recurrence of #10106!

Introduced after upgrading to Glyphicons v1.9.

**Comment by PowerGamer1** [comment]
Both `.glyphicon-door` and `.glyphicon-key` seems to have been reassigned to a BMP in the latest (1.9.2 as of this post) Glyphicons font - to UTF+E207 and UTF+E208 respectively (see http://glyphicons.com/). Can these icons be restored for use in bootstrap now please?
