### ISSUE TITLE
tooltip placement problem

### ISSUE THREAD

**Issue by imarkdesigns** [twbs/bootstrap#15434]
Hi, I would like to know if this is common or something... Because every time I will add the tooltip on my tag, the only thing that appear to be working is the "left" data-placement position.

Please have a look on my screenshot where my tooltip data-placement was position to "bottom" and the text cut the whole width.

![screenshot 2014-12-24 08 50 34](https://cloud.githubusercontent.com/assets/1100419/5544795/f565508e-8b4a-11e4-9b1d-6f129decd543.png)

**Comment by cvrebert** [comment]
Closing due to lack of response.
