### ISSUE TITLE
Document that calling tooltip/popover .show()/.hide() qualifies as manual triggering

### ISSUE THREAD

**Issue by markkolich** [twbs/bootstrap#15465]
According to http://getbootstrap.com/javascript/#popovers there doesn't appear to be a way to auto-hide a popover, that is manually shown/triggered, after some interval.

As such, I end up doing this in my application:

```javascript
button.popover('show');

setTimeout(function() {
  button.popover('hide');
}, button.attr('data-delay-hide') || 2000);
```

Looking at the documentation on the `data-delay` attribute for popovers, I see "does not apply to manual trigger type".  I conjecture my `button.popover('show')` falls into this manual trigger category and as a result I'm responsible for hiding the popover myself?

Somewhat expected, I tried `<button data-delay='{"hide":3000}'>` without the JS above and this failed miserably.

Shouldn't a popover I trigger manually be hidden after the hide delay I provide in the `data-delay` attribute?  If not, I'd like to suggest an update the documentation at http://getbootstrap.com/javascript/#popovers to be a bit clearer with a red callout highlighting this limitation.

**Comment by markkolich** [comment]
Thanks for the clarifications.

> Philosophically speaking, honoring delay in the manual case makes things less manual, and as you've shown, the behavior you desire is still easy to implement even without this feature.

Yep, understandable.

To be honest, I think the way it behaves now is fine.  At first, I was a bit "ugh, really?" when I realized that I had to `setTimeout` all over the place to hide manually triggered popovers, but given the design and some further reflection I think this makes sense.

> We're trying to cut down on callouts actually (it's a "if everything is top-priority, then nothing is" problem). Given that we've had few, if any, other complaints about this particular issue, a callout doesn't seem warranted yet.

Sure &mdash; a callout is overkill.

Just a quick note in the docs somewhere in the section covering popovers would suffice, I think.

**Comment by addremove** [comment]
If I call `show` on a tooltip, it still respects the `hide` delay (despite it being a `manual` trigger). 

http://jsfiddle.net/on6czwz2/2/ . Is my understanding of this issue incorrect?

**Comment by twbs-lmvtfy** [comment]
Hi @addremove!

You appear to have posted a live example (http://fiddle.jshell.net/on6czwz2/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 51, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by addremove** [comment]
If I call show on a tooltip, it still respects the hide delay (despite it being a manual trigger).

http://jsfiddle.net/on6czwz2/3/ . Is my understanding of this issue incorrect?

**Comment by cvrebert** [comment]
Your `$(this).tooltip('show')` counts as manually triggering a `show`.
In contrast, the hiding when the mouse hovers away is automatic; indeed, your example code contains no manual `.tooltip('hide')`. You could disable the automatic hover event handler by setting the `trigger` option to an appropriate value.

In other words, the manual-ness only applies to the immediate action and doesn't infect other actions (like the subsequent `hide`).

**Comment by addremove** [comment]
> In other words, the manual-ness only applies to the immediate action and doesn't infect other actions (like the subsequent hide).

Thanks for clarifying. This wasn't apparent from the docs.
