### ISSUE TITLE
modal stops showing after a few shows/hides

### ISSUE THREAD

**Issue by kittenkong** [twbs/bootstrap#15481]
I'm using a modal for data entry that gets shown and hidden again multiple times per session, however it seems to stop opening after between 1 and 5 cycles.

I am showing/hiding the modal with jquery 
$('#modComposeMessage').modal("show");

**Comment by peterblazejewicz** [comment]
@kittenkong Can you provide an example of your modal implementation using a service like for example jsbin.com?

**Comment by cvrebert** [comment]
Also, please state which browser and OS you're experiencing the problem on.

**Comment by cvrebert** [comment]
Closing due to lack of response. Happy to reopen if responses to the above request+questions are given.
