### ISSUE TITLE
bootstrap css problem

### ISSUE THREAD

**Issue by joebnb** [twbs/bootstrap#15480]
![image](https://cloud.githubusercontent.com/assets/1646883/5592935/05a1ac0e-9226-11e4-80f5-584196a80046.png)
if i add navbar-brand,
![image](https://cloud.githubusercontent.com/assets/1646883/5592942/203f57dc-9226-11e4-905a-6b64712c6a26.png)

navbar-brand will display like this
.......................
this is i want
![image](https://cloud.githubusercontent.com/assets/1646883/5592947/85e4a344-9226-11e4-9fd4-23efc9d5ca8a.png)

BTW 
mobile first but off canvas less

**Comment by mdo** [comment]
You'll need to override things as you start to customize the navbar—we require a specific markup structure for that component. As you change that, expect to have to make style changes as well.
