### ISSUE TITLE
Bootstrap Carousel slider not showing item contents in firefox

### ISSUE THREAD

**Issue by samarthsikotara** [twbs/bootstrap#15488]
I have a bootstrap.css code of carousel slide below: 
@media all and (transform-3d),(-webkit-transform-3d) {....CSS of Slider--- }

Slider is working in chrome perfectly but in firefox mozilla it only shows small left & right arrows without item div's content. so I changed for working in mozilla

@media all and (transform-3d),(-webkit-transform-3d) and (-moz-transform-3d)  {....CSS of Slider--- }

still not working..can anyone help me out in that? thanks.

**Comment by peterblazejewicz** [comment]
I think media-query based detection is still not supported in FF (at least on OS X FF+FFDev I've tested);
http://www.quirksmode.org/css/tests/mediaqueries/animation.html
Also mentioned in comments to pull request that added media-query based detection support:
https://github.com/twbs/bootstrap/pull/13074

@samarthsikotara the carousel should work - but without hardware acceleration. If you have content missing can you please post a link or repeatable example via jsbin.com?
btw: Modernizr feature detection works fine under FF/FFDev

**Comment by cvrebert** [comment]
Yeah, can't help unless you post a JS Bin that demonstrates the problem.

**Comment by samarthsikotara** [comment]
@cvrebert @peterblazejewicz have a look into both links and CSS
1) Working in chrome but not in firefox:
 @media all and (transform-3d),(-webkit-transform-3d) {....CSS of Slider--- }
    http://roofz.herokuapp.com/test
2) not working in both browsers: 
@media all and (transform-3d),(-webkit-transform-3d) and (-moz-transform-3d) {....CSS of Slider--- }
    http://roofz.herokuapp.com/test1

**Comment by samarthsikotara** [comment]
but when I removed media queries from CSS. it was working fine in both browsers.

**Comment by cvrebert** [comment]
@samarthsikotara Sorry, but you're going to have to simplify it further:
* Remove jQuery UI
* Remove as much irrelevant CSS as possible (Skeleton, Marvel, etc.)
* Use http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.css

**Comment by samarthsikotara** [comment]
Yes finally I solved that problem. thanks :)

**Comment by samarthsikotara** [comment]
@cvrebert  here I use minified javascript https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js

if I remove jQuery UI then it throws an error - an undefined function in console output.

**Comment by cvrebert** [comment]
You need to include jQuery but not jQuery UI. jQuery is distinct from jQuery UI.

**Comment by cvrebert** [comment]
And obviously remove any uses of jQuery UI widgets from the example.

**Comment by cvrebert** [comment]
> 2) not working in both browsers: 
> ```css
> @media all and (transform-3d),(-webkit-transform-3d) and (-moz-transform-3d) {....CSS of Slider--- }
> ```

Well, right, that should instead be:
```css
@media all and (transform-3d),(-webkit-transform-3d),(-moz-transform-3d) {....CSS of Slider--- }
```

**Comment by cvrebert** [comment]
Although as @peterblazejewicz said, Firefox doesn't appear to support `-moz-transform-3d` as a `@media` query feature.

**Comment by samarthsikotara** [comment]
I tried your above your suggestions but still not getting proper output. Firefox doesn't appear to support -moz-transform-3d as a @media query feature. preferably I don't really need to put this chaos stuff under a media query.

**Comment by cvrebert** [comment]
@samarthsikotara Could you please post a further-simplified example of the original problem, as I requested earlier? (i.e. no jQuery-UI, etc.)

**Comment by samarthsikotara** [comment]
@cvrebert I've simplified a webpage as per your requested steps. 

1) Removed jQuery UI
2) Removed irrelevant CSS as possible (Skeleton)
3) Used http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.css

working in both browsers perfectly without changing anything. :)
https://roofz.herokuapp.com/test

**Comment by cvrebert** [comment]
Cool, closing this as not a Bootstrap bug then.
