### ISSUE TITLE
v3.3.1 possible issue with long modal being unscrollable

### ISSUE THREAD

**Issue by rhill45** [twbs/bootstrap#15489]
I have two modals on my page, the first one functions fine, the second one is larger and when I use mouse wheel over scroll the background scrolls (I've noticed this prob in FF, S, Chr, IE). Both modals are laid out in a pretty similar fashion in respect to tags so I'm to wonder if it's an issue because there is two on the page? I'm using the 3.3.1 cdn for both js and css.

 I'm leaving out some of the repetitive parts of the code (which does make the modal smaller) if moderators want full code please request:

            
        <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" data-backdrop="static">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <form class="avatar-form" action="crop-avatar.php" enctype="multipart/form-data" method="post">
                <div class="modal-header">
                  <button class="close" id="refresh1" data-dismiss="modal" type="button">&times;</button>
                  <h1 class="modal-title" id="avatar-modal-label" style="border:none;">Add new listing: Image
                    <h6>Required</h6>
                  </h1>
                </div>
                <div class="modal-body">
                  <div class="avatar-body">
                    <div class="avatar-upload">
                      <input class="avatar-src" name="avatar_src" type="hidden">
                      <label for="avatarInput">Local upload</label>
                      <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                    </div>
                    <div class="row">
                      <div class="col-md-9">
                        <div class="avatar-wrapper"></div>
                      </div>
                      <div class="col-md-3">
                        <div class="avatar-preview preview-sm"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button class="btn btn-default" id="refresh2" data-dismiss="modal" data-dismiss="alert" type="button">
                  Close
                  </button>
                  <button id="nxtbutton" class="btn btn-primary avatar-save" type="submit">Save</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
        </div>
        
        <div id="modal1-container" class="m1container">
          <div class="modal fade" id="modal1" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" data-backdrop="static">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <form name="data-form" class="data-form" method="post" action="add-list.php" enctype="multipart/form-data">
                  <div class="modal-header">
                    <button type="button" id="close" class="close" data-dismiss="modal">&times;</button>
                    <h1 class="modal-title" id="avatar-modal-label" style="border:none;">Add new listing: File and Data</h1>
                  </div>
                  <div class="modal-body">
                    <fieldset >
                      <legend style="display: inline;">
                      PDF File Upload
                      <h6 style="display: inline;">Required</h6>
                      </legend>
                      <label style="margin-left:30px;" for="fileUpload">Select pdf file from computer</label>
                      <input style="display: inline; margin-left:10px;" class="fileUpload" name="flyer" type="file"  />
                    </fieldset>
                    <br />
                    <fieldset>
                      <legend style="display: inline;">
                      Designation
                      <h6 style="display: inline;"><strong>Required</strong> - Defaults to "Listings"</h6>
                      </legend>
                      <p style="padding-left:30%;">
                        <input name="transaction" type="radio" value="0" checked="checked"/>
                        <label>Listings</label>
                        <input style="margin-left:100px;" name="transaction" type="radio" value="1"/>
                        <label>Recent Transactions</label>
                      </p>
                      <p style="padding-left:30%;">
                        <input name="transaction" type="radio"  value="2"/>
                        <label>Both</label>
                        <input style="margin-left:120px;"  name="transaction" type="radio" value="3"/>
                        <label>Save, don't publish</label>
                      </p>
                    </fieldset>
                    <legend>Listing Data</legend>
                    <fieldset style="margin-left:30px;">
                      <P class="h4" style="display: inline;">Title</P>
                      <h6 style="display: inline;"><strong>Required</strong> - Maximum 57 Characters</h6>
                      <br />
                      <textarea name="title" cols="90" rows="1" required id="title" placeholder="Required (Max 57)" style="vertical-align:middle"></textarea>
                      <br />
                      <P class="h4" style="display: inline;">Address</P>
                      <h6 style="display: inline;">Maximum 50 Characters</h6>
                      <br />
                    </fieldset>
                  </div>
                  <div class="modal-footer">
                    <input class="avatar-src" name="avatar_src" type="hidden">
                    <input class="avatar-id" id="avatar_id" name="id" value="">
                    <button id="dformclose" class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
                    <button id="nxtbutttwo" class="btn btn-primary avatar-save" type="submit">Save Listing</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

**Comment by mdo** [comment]
Can't help you without a live example (try http://jsbin.com).

**Comment by rhill45** [comment]
http://www.mblistings.com/members_area/add_listings.php
I removed the session so you can just access my page. You will need to upload any image into the first modal in order to pull up the 2nd one - which is the one having the issue.

**Comment by claudchan** [comment]
Same issue. 
Notice that 3.3.1 the backdrop position is set to absolute. If content is static height (no increasing after modal shown) is fine. Try put accordion inside the modal and put long text inside the hidden panel. Once you expand you will notice the issue.

**Comment by claudchan** [comment]
Hi @rhill45,
When the 2nd modal pull up, the <body> class="modal-open" is removed.
You may consider to code this way:

$('#myModal').on('hidden', function () {
  // Load up a new modal...
  $('#myModalNew').modal('show');
})

**Comment by rhill45** [comment]
@claudchan Your definitely right about the body class getting lost...good eye by the way. However binding the events is not working, I posted a question on SE

http://stackoverflow.com/q/27807225/4208890?sem=2 

with no quick replies

The page I referenced
 http://www.mblistings.com/members_area/add_listings.php
is still open if you want to look. 

currently running is 

          this.$avatarModal.modal("hide");
	  this.$avatarModal.on('hidden.bs.modal', function () {
          this.$modaldata.modal("show");
});

there is a css hack that will work around this by placing a scroll bar within the modal:

.modal-body {
    max-height: calc(100vh - 212px);
    overflow-y: auto
}

but I would love to get this working right.

**Comment by rhill45** [comment]
I posted a separate issue for the method / event incompatibility, fyi

**Comment by rhill45** [comment]
solved thank you @claudchan

**Comment by claudchan** [comment]
Glad that you have solve it!

**Comment by rhill45** [comment]
THank you @claudchan moving it after the .on statement works as well
