### ISSUE TITLE
Feedback idea: color attributes in separate css file

### ISSUE THREAD

**Issue by gareth-gillman** [twbs/bootstrap#15485]
I have started using BS on all my projects but one thing that is a slight (but not big) annoyance is I either need to remove the default colors set in bootstrap.css or overwrite it in my own css.

Now what would be easier if there was a bootstrap-colors.css file where all the colours (a tags, menu etc) were so we can just amend that file without having to do the above options. I have put one together in my copy of BS I use for my projects but it would be a nice to have in future.

It does mean 1 more http request for the load of BS but it would make BS easier to use out of the box

I would put in a pull-request but I don't use Less and wouldn't know where to start

**Comment by cvrebert** [comment]
>  I either need to remove the default colors set in bootstrap.css or overwrite it in my own css.

You're missing option three: Compile Bootstrap from its LESS source and just adjust the values of the LESS color variables. Thus, bootstrap.css will have your desired colors to begin with.

**Comment by mdo** [comment]
We won't be splitting anything up like this, at least in v3.
