### ISSUE TITLE
Modal background scrollable on iOS devices

### ISSUE THREAD

**Issue by dapperdanhorvath** [twbs/bootstrap#15492]
When a modal window is open, the background of the window is scrollable in Safari on iOS devices (tested with iOS 8.1.2, iPhone and iPad). On desktop browsers, the "overflow:hidden" property of the "modal-open" class (which gets applied to the "body" tag) correctly prevents scrolling, but this isn't the case on iOS devices.

Live demo: http://getbootstrap.com/javascript/#modals (click/touch "Launch demo modal" and observe background scrolling).

**Comment by cvrebert** [comment]
I think you're encountering the "Overflow and scrolling" caveat explained on http://getbootstrap.com/getting-started/#support-fixed-position-keyboards ?

**Comment by dapperdanhorvath** [comment]
Yes, that's exactly right. It appears that this is not a bug but an Android/iOS browser support issue, so I will close this issue.
