### ISSUE TITLE
Glyphicons break .btn-group-lg height in Win Chrome

### ISSUE THREAD

**Issue by noilly** [twbs/bootstrap#15497]
Using a glyphicon in a large, split button dropdown causes the dropdown to be smaller in height than the button with the glyphicon.

The following will reproduce the issue:

```html
<div class="btn-group btn-group-lg">
    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="#">Action</a></li>
    </ul>
</div>
```

![capture](https://cloud.githubusercontent.com/assets/7479776/5622164/65445122-958a-11e4-9181-52233012116c.PNG)

Using Bootstrap 3.3.1

**Comment by cvrebert** [comment]
JS Fiddle: http://jsfiddle.net/7x3h9p29/2/
@noilly I can't repro on Mac Chrome. What OS and browser are you using?

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/7x3h9p29/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by noilly** [comment]
Windows 8.1 Pro and Chrome 39.0.2171.95 m (64-bit)

I see the same issue when viewing your fiddle.

**Comment by cvrebert** [comment]
I can't reproduce in Win 8.1 Chrome 39 on Sauce Labs:
![normal-zoom](https://cloud.githubusercontent.com/assets/419884/5623309/873d1752-9506-11e4-9756-a23b41329bca.png)

Works fine even zoomed @ 175%:
![175pct-zoom](https://cloud.githubusercontent.com/assets/419884/5623312/96a06f1e-9506-11e4-93d1-4015396a8d39.png)

**Comment by noilly** [comment]
Hmm, I don't know what to say, I'm definitely getting the issue.

![capture](https://cloud.githubusercontent.com/assets/7479776/5623344/4572b0d2-959e-11e4-96c6-2e9a7328c00c.PNG)

**Comment by cvrebert** [comment]
@juthilo @hnrch02 @XhmikosR Anyone else able to test this on Windows?

**Comment by noilly** [comment]
I thought the previous screenshot was a bit small, so I took a new one at 100%, and got this:

![capture](https://cloud.githubusercontent.com/assets/7479776/5623495/e06721ca-95a0-11e4-9377-caa60a4709ca.PNG)

and then I thought I would check it out at 150%, and got this:

![capture](https://cloud.githubusercontent.com/assets/7479776/5623503/0ecdafb6-95a1-11e4-8e65-771deb73e3a5.PNG)

**Comment by XhmikosR** [comment]
I can confirm this happens, but only for 100%. Any other zoom and the glitch goes away for me. I'd say it's a Chrome issue, but we need to verify this.

**Comment by chrisvogt** [comment]
Interesting - this appears to go away if you force the style `border-top: 1px` on the left-hand button containing the icon.

**Comment by Coupoholics** [comment]
On my pc, the left button is taller when zoom level is 67% or 50%. (Equal height when zoom level >= 75%)

Win7, Chrome 39.0.2171.95 (64-bit)
System DPI: 125%

**Comment by patrickhlauke** [comment]
it seems the culprit may be the line height of 23.94xxx leading to some rounding issue in chrome. left button is 24px tall, while right one only 23px for some reason...

**Comment by XhmikosR** [comment]
One of the few times Firefox behaves properly and Chrome fails :p

**Comment by XhmikosR** [comment]
Did you check the minified CSS? We might need to tweak clean CSS settings.

**Comment by cvrebert** [comment]
Perhaps we should use an expression [e.g. `((4/3))`] and let Less calculate it out to whatever number of decimal places it's configured to use?

**Comment by mdo** [comment]
Compiled and compiled minified CSS looks good.

**Comment by XhmikosR** [comment]
If it has the same digits I guess we are fine.

I brought this up because I remember some issues with clean-css precision
in the past.
