### ISSUE TITLE
Improve visibility of text in <small> elements within panel-title of panel-primary

### ISSUE THREAD

**Issue by Prismapanda** [twbs/bootstrap#15493]
When using the <small> Element within 'panel-title' classed headline of a 'panel-primary' the text is not readable. This is similar to #12397 and #13377.

See example: http://jsfiddle.net/9hfdyha5/2/

**Comment by twbs-lmvtfy** [comment]
Hi @Prismapanda!

You appear to have posted a live example (http://fiddle.jshell.net/9hfdyha5/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Prismapanda** [comment]
Fixed example (JQuery added)

http://jsfiddle.net/9hfdyha5/2/
