### ISSUE TITLE
.col-md-1 elements are displayed in block Level elements in IE 8

### ISSUE THREAD

**Issue by mujuburcs** [twbs/bootstrap#15490]
I tried the link http://getbootstrap.com/css/

.col-md-*  elements are displayed as block level elements in Internet exlporer 8 Kindly explain and solve the issue.

Respond.js is not working fine in bootstrap.

![image](https://cloud.githubusercontent.com/assets/4193291/5611803/591f81b2-94f1-11e4-8a62-76f7bb7e8b54.png)

**Comment by cvrebert** [comment]
Unable to reproduce. Perhaps you have JavaScript disabled?

**Comment by mujuburcs** [comment]
Hi,
 I haven't disabled javascript in IE.Attached my Internet explorer version info for you kind reference.
I tried with IE9 ,Chrome It is working fine.

![internet explorer version](https://cloud.githubusercontent.com/assets/4193291/5625236/1cb1366a-959d-11e4-92f3-c09950e63d45.JPG)

**Comment by cvrebert** [comment]
Your IE8 is outdated. The final version of IE8 was 8.0.7601.17514. Use Windows Update.

**Comment by cvrebert** [comment]
Duplicate of #15045 and https://github.com/scottjehl/Respond/issues/310
