### ISSUE TITLE
.modal('show') method does not run when executed within the hidden.bs.modal event

### ISSUE THREAD

**Issue by rhill45** [twbs/bootstrap#15508]
the following does not work (the second modal does not open).

        this.$avatarModal.modal('hide');
	    this.$avatarModal.on('hidden.bs.modal', function () {
          this.$modaldata.modal('show');
    });

However, If i replace the show event with an alert, the alert opens:

        this.$avatarModal.modal("hide");
	    this.$avatarModal.on('hidden.bs.modal', function () {
          window.alert('hidden event fired!');
    });

This tells me that all the commands here are working, however having the 'show' method within the hidden.bs.modal event event does not seem to work. 

Is there a reason for this incompatibility?

**Comment by rhill45** [comment]
solved: this.- has has a different value inside a function, and needs to be defined as a variable.

the following works

          this.$avatarModal.modal('hide');
	  var $modaldata = this.$modaldata;
	  this.$avatarModal.on('hidden.bs.modal', function () {
        $modaldata.modal('show');
});

**Comment by cvrebert** [comment]
Also, you need to move the `.modal('hide')` to come after the `.on(...)`
