### ISSUE TITLE
Text rendering temporarily changes during carousel transition in WebKit/Blink

### ISSUE THREAD

**Issue by lchoros** [twbs/bootstrap#15506]
Hi, I tried use carousel example. But there is small bug e.g. if you go to carousel example and you change background color to black and fonts to red/darkred then you will see that text is affected by carousel. When carousel slide, fonts are changing for 1 second maybe less
![helpscreen](https://cloud.githubusercontent.com/assets/9035485/5631674/2d3df2a2-95c0-11e4-83e1-459b57d1d386.png)
edit: http://getbootstrap.com/examples/carousel/ i used carousel from here

**Comment by lchoros** [comment]
http://getbootstrap.com/examples/carousel/  i used carousel from here

**Comment by mdo** [comment]
You're likely seeing a rendering bug by the browser—as I recall there's not much we can do about it.

**Comment by lchoros** [comment]
Hi,
i found out that for this caorusel: http://getbootstrap.com/javascript/#carousel   everything is fine.

**Comment by cvrebert** [comment]
Sounds like http://stackoverflow.com/questions/12502234/how-to-prevent-webkit-text-rendering-change-during-css-transition

**Comment by mdo** [comment]
Yup, that. But we can't use the hardware acceleration trick because it causes a number of other problems. Punting as a won't fix.

**Comment by cvrebert** [comment]
Possibly fixed in WebKit Nightly: https://bugs.webkit.org/show_bug.cgi?id=23364
