### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by MajidCS** [twbs/bootstrap#15509]
Hi,

There are millions of people who write from right to left, so we wish to support RTL .

The biggest problem in Bootstrap that it does not support RTL .

Please do not marginalize this community.

Thank you,

**Comment by MajidCS** [comment]
Why there are so many threads and so far does not support RTL ?

Is team bootstrap does not care about us!

**Comment by cvrebert** [comment]
We did briefly try, but then got some pushback about it and reverted our attempt; see #13564. Also, nobody on the Core Team personally uses an RTL language or has any urgent need for RTL support, which makes adding that feature both more difficult and lower priority.

If we do add RTL support, we want to do it properly.
At this point, we're unlikely to take a look at RTL again until after the initial release of v4.0.0.
And yes, please search in the future before opening new issues :smile:

**Comment by StevenBlack** [comment]
@MajidCS check out [morteza/bootstrap-rtl](https://github.com/morteza/bootstrap-rtl) — it's ongoing and actively developed.

**Comment by rafalp** [comment]
@hooramin please respect creator's right to use his/her judgement when choosing prorities.

I'm sure they understand importance of supporting rtl languages, but it is their *sacred right* as open source developers to say "delivering something useful to *us* comes first, sorry!".

There's also no need for suggesting ill will on the side of other party, after all they are sharing their work with you for free and on liberal license. Working on such extremly popular open source project requires dealing with *unimaginable* burden that we as users interested in it's wellbeing should do our best to minify, not add to. 💖

**Comment by patrickhlauke** [comment]
open to well-crafted and complete PRs to add RTL to v4. however, these will then also need to be thoroughly reviewed before being merged.

a reminder also that the vast majority of core team members are doing this on a volunteer basis.

**Comment by parsmizban** [comment]
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck

**Comment by rafalp** [comment]
@parsmizban please don't bump all RTL issues on tracker. This is messing up with people who use "last updated" feature to browse those as well as send quite a plenty of notifications out.

**Comment by parsmizban** [comment]
@rafalp, Sorry just wanted to help to whos are seeking for RTL compatibility
