### ISSUE TITLE
Consider adding "bootstrap-X.Y.Z/" to the zip path of the dist downloads

### ISSUE THREAD

**Issue by zoowar** [twbs/bootstrap#15501]
Consider adding "bootstrap-x.y.a/" to the zip path so that files unzip into a versioned bootstrap directory.

Currently, the zip file unzips into "dist/" regardless of which version is unzipped in the current directory. I would be nice if the bootstrap-3.3.1-dist.zip unzipped into "bootstrap-3.3.1/dist/".

**Comment by cvrebert** [comment]
:+1: We'd just need to update our internal steps-to-perform-a-release document going forward.

**Comment by zoowar** [comment]
I don't use bower. Would this change affect bower user path expectation?

**Comment by cvrebert** [comment]
Shouldn't affect Bower since it uses git tags, not GitHub Release downloads.

**Comment by mdo** [comment]
This was done for v3.3.2 actually.
