### ISSUE TITLE
Heading + Small + Pulling

### ISSUE THREAD

**Issue by Nagle** [twbs/bootstrap#15510]
[Reduced Test Case ](http://jsfiddle.net/xnjcqb9o/1/embedded/result/)(jsfiddle)

Problems:
- baseline alignment of `<small class='pull-right'>` in relation to `<h1>`,`<h2>`…
- `<h1>`+`<small>` has spacing in between while `<h2>`,`<h3>`… do not

**Comment by twbs-lmvtfy** [comment]
Hi @Nagle!

You appear to have posted a live example (http://fiddle.jshell.net/xnjcqb9o/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
The horizontal spacing thing appears to be a vagary of the browser/platform font engine; not sure we can do much there.
Isn't the vertical alignment thing just a matter of "well, that's how floats work"? Granted, it would be wonderful if @mdo has some magic up his sleeve to make this case "just work".

**Comment by mdo** [comment]
Sorry, but this is just how floats work, nothing to do here.
