### ISSUE TITLE
Minor CSS Issue

### ISSUE THREAD

**Issue by ppumkin** [twbs/bootstrap#15514]
/*!
 * Bootstrap v2.2.2

Embedded tables should not have styles applied on the nth rows, since the parent table already has the style applied and any children will  just be default "transparent" 

![image](https://cloud.githubusercontent.com/assets/1249683/5647149/2494aa68-967b-11e4-9596-9efaebf062ce.png)

A quick simple fix to add > after table.striped 

**Line 2358
````
.table-striped > tbody > tr:nth-child(odd) > td,
.table-striped > tbody > tr:nth-child(odd) > th {
  background-color: #f9f9f9;
}
```

I am sure there are going to many other issues like this and I hope this solves this styling issue.
I am aware that embedded tables wont be styled.... but maybe they need other styling rather than normal?

**Comment by cvrebert** [comment]
Bootstrap v2 is no longer supported and hasn't been for quite some time.
Please try asking on StackOverflow (or similar forums) instead.
