### ISSUE TITLE
Bootstrap modal working incorrectly with bootcards

### ISSUE THREAD

**Issue by vamsiampolu** [twbs/bootstrap#15517]
Modal does not work properly when using `bootstrap 3.3.2` with `bootcards`,[this plunkr](http://plnkr.co/edit/OsUiWKFGEqR5rJTjpl9E?p=preview) uses 3.3.2 to show a modal.The result looks like this.However it works perfectly when loaded with `bootstrap 3.2.0` [here](http://plnkr.co/edit/icoOyW5gcxQVX0D0vsBE?p=preview)

I do not know if this is a bootstrap issue or an issue with the bootcards plugin.

**Comment by twbs-lmvtfy** [comment]
Hi @vamsiampolu!

You appear to have posted a live example (http://run.plnkr.co/plunks/icoOyW5gcxQVX0D0vsBE/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 25, column 13: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-body` must be a child of `.modal-content`
* line 25, column 13: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-footer` must be a child of `.modal-content`
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 5, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.1 ; saw what appears to be usage of Bootstrap 3.2.0
* line 8, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.1 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @vamsiampolu!

You appear to have posted a live example (http://run.plnkr.co/plunks/OsUiWKFGEqR5rJTjpl9E/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 25, column 13: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-body` must be a child of `.modal-content`
* line 25, column 13: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-footer` must be a child of `.modal-content`
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
We can't help you with issues involving third-party plugins.
Please file an issue with https://github.com/bootcards/bootcards instead.

**Comment by cvrebert** [comment]
Also, see the above Bootlint errors that @twbs-lmvtfy has pointed out.
