### ISSUE TITLE
IE8 first select class="form-control"

### ISSUE THREAD

**Issue by matherton** [twbs/bootstrap#15529]
I have just found a bug in bootstrap 3 that occurs in IE8. The first select class form-control makes the drop down unelectable with the mouse. If you place:

select class="form-control" style="display:none"

above the first drop down on your page your drop down will work as expected in IE.

**Comment by cvrebert** [comment]
Please post the HTML for a simple example that demonstrates the problem.

**Comment by cvrebert** [comment]
@matherton Ping.

**Comment by cvrebert** [comment]
Closing due to lack of response.
