### ISSUE TITLE
navbar: multiple dropdowns don't work

### ISSUE THREAD

**Issue by wolfy1339** [twbs/bootstrap#15525]
On <a href="http://files.brilliant-minds.tk/Organize-Post.html">my page</a>, I have a navbar that has two dropdown menus, but as you can see, only the first one get's styled.
I have double checked my classes and asked on IRC and even ran the W3 Validator but nothing works.

**Comment by juthilo** [comment]
Triple-check your classes: the second `dropdwn-menu` [sic!] is missing an "o".
