### ISSUE TITLE
Affix sidebar width changes

### ISSUE THREAD

**Issue by browniebroke** [twbs/bootstrap#15528]
This is a suggestion for an improvement I've thought about. I also looked up if it was duplicated, but couldn't find anything.

A known limitation of the affix plugin is the width of the element gets lost when the affix kicks in, as we can see in this example:
http://jsfiddle.net/brunoalla/kmrjmgLm/

From a quick google search, the fix is easy, it's up to the developer to add the width explicitly in the CSS.

However, in the case where the `.affix` is wrapped in a grid column `.col-xs-*`, `.col-sm-*`, `.col-md-*` or `.col-lg-*`, it should be feasible to set the correct width within bootstrap's CSS, by including definitions along the lines of:

    .col-sm-3>.affix {
        width: <col-sm-3-width>;
    }

As illustrated in this modified fiddle: http://jsfiddle.net/brunoalla/cuzy6r7L/

I know it's documented that affix plugin provides the minimum CSS, and I'm not sure where this definition would stand between the grid framework mixins and the affix plugin, but I feel like this bit could be shipped with bootstrap.

Thanks

**Comment by twbs-lmvtfy** [comment]
Hi @browniebroke!

You appear to have posted a live example (http://fiddle.jshell.net/brunoalla/cuzy6r7L/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.1 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @browniebroke!

You appear to have posted a live example (http://fiddle.jshell.net/brunoalla/kmrjmgLm/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.1 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by browniebroke** [comment]
I think I understood while refreshing the fiddle why it's not implemented: the width is in percent, not px. And for an affixed element, it's in percent from the whole page... Sorry :(

**Comment by cvrebert** [comment]
@browniebroke So, can we close this?
