### ISSUE TITLE
v3.3.0 & v3.3.1: Tooltips and popovers with selector throw an error when being destroyed

### ISSUE THREAD

**Issue by DanielApt** [twbs/bootstrap#15521]
I've created some tooltips using the selector property:
```
$('body').tooltip({
    selector: '[data-toggle=tooltip]';
});
```

Afterwards I destroy them using:
`$('body').tooltip('destroy');`

This throws an error:
`Uncaught TypeError: undefined is not a function`

The same applies for popovers.

For an example see http://jsfiddle.net/DanielApt/rvqd7cyv/

**Comment by cvrebert** [comment]
Probably fixed by #15466. Could you re-test using the latest code in `master`?

**Comment by DanielApt** [comment]
Yup, just re-tested. There are no issues anymore. When could we expect to see this in a release?

**Comment by cvrebert** [comment]
I'm hoping "soon", but there's currently no definite timeline.

**Comment by DanielApt** [comment]
No worries. Not sure about github / open source protocol… Does this issue stay open until a release, or can we close it already?

**Comment by DanielApt** [comment]
Oh nvm, I see you've closed it.
