### ISSUE TITLE
abusing the priviliage of stupidity 

### ISSUE THREAD

**Issue by cheezedigital** [twbs/bootstrap#15538]
application.html.haml file
.navbar-collapse.collapse
          %ul.nav.navbar-nav
            - if current_user?
              %li= link_to user_email, "#"
              %li= link_to "Dashboard", account_dashboard_index_path
              %li= link_to "Change Password", account_change_password_index_path
              - if current_user.has_role?(:sub_super_user, true)
                %li= link_to 'Users', account_users_path
              %ul.nav.navbar-nav.pull-right
                %li= link_to "Logoff", logoff_index_path
        / /.nav-collapse

css file 
.nav.navbar-nav.pull-right {

}
as simple as this probably is, I'm having a tough time trying to figure out what the selector style is supposed to be. I'd like to have the following pull right. 
 %ul.nav.navbar-nav.pull-right
                %li= link_to "Logoff", logoff_index_path 

any help would be appreciated.

**Comment by cvrebert** [comment]
Please direct how-to/troubleshooting questions to StackOverflow. Thanks!
