### ISSUE TITLE
When i click on tab i lose data and code not looping throw Model again ?

### ISSUE THREAD

**Issue by ahmedamen** [twbs/bootstrap#15537]
Hi

i have try to loop throw data in "Categories" Table and it works - i got data when i open View in first time but if i click on a tab to see its content i got only first record ?

i don't know why i lose all data i got in first time ?

Razor Code:
```
@section personAds{
    <h2 class="title text-center">Person Ads</h2>
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#propertytab" data-toggle="tab">Home</a></li>
            <li><a href="#carstab" data-toggle="tab">Cars</a></li>
        </ul>
    </div>
    <div class="tab-content">

        @foreach (var personItems in Model.Where(isCompany => isCompany.isCompany == false))
        {
            <div class="tab-pane fade active in" id="propertytab">
                <div class="col-sm-3">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfoslide text-center">
                                <img src="@Url.Content(personItems.catImage)" alt="" />
                                <h4>@personItems.catName</h4>
                                <a href="#" class="btn btn-default plus-info"><i class="@personItems.classIcon"></i>More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-pane fade" id="carstab">
                <div class="col-sm-3">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfoslide text-center">
                                <img src="@Url.Content(personItems.catImage)" alt="" />
                                <h4>@personItems.catName</h4>
                                <a href="#" class="btn btn-default plus-info"><i class="@personItems.classIcon"></i>More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
```
 Controller Code:

        public ActionResult Contact()
        {
            var model = _db.Categories.ToList();
            return View(model);
        }

GOShopeDbContext Code:

    public partial class GoShopeDB : DbContext
    {
        public GoShopeDB()
            : base("name=GoShopeDB")
        {
        }

        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<SubCats> SubCats { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }

Categories Code:

    public partial class Categories
    {
        [Key]
        public int catId { get; set; }

        [StringLength(100)]
        public string catName { get; set; }

        [StringLength(100)]
        public string catImage { get; set; }

        [StringLength(200)]
        public string classIcon { get; set; }

        public bool isCompany { get; set; }
    }

and i try to remove where condition and i got same result - when i click on any tab i got only first record ?!

**Comment by cvrebert** [comment]
Sorry, but this issue tracker is for bugs in Bootstrap itself, not for requests for help regarding how to properly use Bootstrap. And server-side code is completely off-topic here.
Please direct your question to a more appropriate forum, such as StackOverflow. Thanks!
