### ISSUE TITLE
CSS3 3D transforms for Carousel aren't used in Firefox

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15534]
So, it turns out that the media query we're using (https://github.com/twbs/bootstrap/blob/72a91b0205b3a76baebb68aeac8030fd015d906b/less/carousel.less#L29 ) evaluates to false in Firefox. (Also, the unprefixed `transform-3d` media feature doesn't seem to exist; there's only [`-webkit-transform-3d`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-transform-3d))
Testcase: http://jsbin.com/lewuza/5/edit
I'm thinking we could duplicate the styles in an `@supports` feature query, which Firefox does support (again, see testcase).

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/lewuza/5/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Looks like this would require https://github.com/less/less.js/pull/2473, but there hasn't yet been a Less.js release since that PR was merged.

**Comment by cvrebert** [comment]
@mdo You okay if we punt this to v4 since it's an enhancement?

**Comment by mdo** [comment]
Yup!

**Comment by cvrebert** [comment]
Reopening for v4.

**Comment by mdo** [comment]
@cvrebert You have a commit referencing this issue—is that branch ready to be opened as a PR?

**Comment by cvrebert** [comment]
No, that commit was against v3.
