### ISSUE TITLE
"Mad Libs"-style forms

### ISSUE THREAD

**Issue by kwladyka** [twbs/bootstrap#15541]
Hi,

In my opinion bootstrap twitter need ***additional class for natural language forms***.

Simply explanation what is "natural language form"
http://goodui.org/#48

My example how it looks and it works with wide width:
![vtp70](https://cloud.githubusercontent.com/assets/3903726/5695430/ae4ebc5a-99a3-11e4-8ac1-22ec9a5fc26e.png)

But the problem is when the width is narrow:
![2zfxn](https://cloud.githubusercontent.com/assets/3903726/5695434/ca6af660-99a3-11e4-8689-eb5bd2ac3fe3.png)

It shouldn't move to other rows in that case. What i found it's because of ```class="form-control"``` but when i remove this class i also lose how fields appear.

***I want have responsive natural language form, but i don't see technical option in bootstrap twitter to do that in easy way. Only one option what i see is copy CSS for "form-control" to another class but without CSS moving forms to new lines.***

I am writing about that also there:
http://stackoverflow.com/questions/27856466/bootstrap-twitter-3-natural-language-forms

**Comment by cvrebert** [comment]
You basically need to override the `width: 100%` part of `form-control`. Seems like the exact desired width might be very different for each field.

**Comment by mdo** [comment]
We won't be supporting that anytime soon. Thanks though!

**Comment by kwladyka** [comment]
@cvrebert no, override width: 100% it's not the only one thing, because fields jumping to new lines. How to solve that?

**Comment by patrickhlauke** [comment]
@kwladyka ``display:inline`` would be a start...

**Comment by kwladyka** [comment]
Yes, it works when display:inlnie is set on form-group and form-control. Sorry.
