### ISSUE TITLE
bar appears

### ISSUE THREAD

**Issue by UPanel** [twbs/bootstrap#15546]
How can I fix this - or delete the bar at the bottom?
![boot](https://cloud.githubusercontent.com/assets/8117694/5704725/4504e68a-9a74-11e4-89a0-2ca0575932eb.jpg)

**Comment by vaughany** [comment]
You might need to wrap all your body content in `<div class="container">`?

**Comment by UPanel** [comment]
But then the divs are smaller:
![1](https://cloud.githubusercontent.com/assets/8117694/5704894/916f5efa-9a75-11e4-8450-7b430ea2b8cd.JPG)

**Comment by UPanel** [comment]
okay I find out, that you can edit the container size in the css file ;)

**Comment by BytewaveMLP** [comment]
You could always use `.container-fluid`.
