### ISSUE TITLE
Bootstrap. Newbie needs advice

### ISSUE THREAD

**Issue by RayFromTLC** [twbs/bootstrap#15545]
Hi, 
I am very new and green so please forgive the basic question. 
When I create a site using Bootstrap  I believe that I include the link to the Bootstrap CDN file in the head section of each page and I also include a link to my own css style sheet. Is that correct? Or can I put the cdn file links in my style sheet and then just put a link to the style sheet in the html head section of every page?
Same question re the java script. Do I link to the cdn file on every page of my site?
Thanks

**Comment by patrickhlauke** [comment]
Please refer to the basic template and examples in http://getbootstrap.com/getting-started/ (but replace the references to ``css/bootstrap.min.css`` and ``js/bootstrap.min.js`` with references to the CDN versions). For any other questions on how to actually use Bootstrap, please ask on Stackoverflow.
