### ISSUE TITLE
Modal underneath content

### ISSUE THREAD

**Issue by notflip** [twbs/bootstrap#15544]
I have an issue in which on smaller screens the modal pops up but it's underneath the content all the way down the page.

![bmdl](https://cloud.githubusercontent.com/assets/4146384/5700157/543e8304-9a38-11e4-8e5b-b8de40f79bd1.jpg)

**Comment by cvrebert** [comment]
For troubleshooting questions, please [Bootlint](https://github.com/twbs/bootlint) your page and try asking on StackOverflow first. If after those steps you still believe there's a bug in Bootstrap itself, then open a new issue that includes a simple live example (e.g. JS Bin) demonstrating the problem.
Thanks!
