### ISSUE TITLE
Normalize.less causing span bug within contenteditable regions with Chrome

### ISSUE THREAD

**Issue by bearded-avenger** [twbs/bootstrap#15543]
I've got a content editable region, and when backspacing it creates an inline span element. Here's a link that explains what's happening.

http://www.neotericdesign.com/blog/2013/3/working-around-chrome-s-contenteditable-span-bug

You would think this has nothing to do with Bootstrap, but that's how it ended up unfortunately. Specifically the normalize .less. I had two different versions of markup and the bug was happening on one, but not the other.

After replacing the normalize.less file with another version of a reset, the problem completely disappeared. So to clarify, something within the normalize.less file is causing that behavior in Chrome. I haven't gone through and figured out what is causing it. I'm still celebrating having fixed this rather crippling Chromium bug. ;)

Here's what I replaced it with.

```
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
    display: block;
}
body {
    line-height: 1;
}
ol, ul {
    list-style: none;
}
blockquote, q {
    quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
    content: '';
    content: none;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
}
```
For lack of better description, I'm not sure if your normalize is considered a "reset" or not. Either way I appreciate all the work you all have put into Bootstrap. Just wanted to document this here in case anyone looked it up.

The problem could very well be within contenteditable still, but alas there report is here.

**Comment by cvrebert** [comment]
`normalize.less` is just a vendored copy of Normalize.css. Please file a bug with the upstream project: https://github.com/necolas/normalize.css/
Thanks!
