### ISSUE TITLE
Horizontal Description List breaks when <dd></dd> element is empty

### ISSUE THREAD

**Issue by xabra** [twbs/bootstrap#15554]
Referring to the Bootstrap+Angular code below, all the description items `<dd>` following an undefined item get shifted up.  An item might be undefined, for example, because the corresponding database item does not exist.  

```html
<dl class="dl-horizontal">
	<dt>Title</dt>   <dd>{{doc.title}}</dd>
	<dt>Description</dt>   <dd>{{doc.description}}</dd>
	<dt>Number</dt>   <dd>{{doc.documentNum}}</dd>
</dl>
```

So, rather than producing a blank space on the right, across from the corresponding `<dt>`, subsequent `<dd>` items in the right-hand column are shifted up and out of sync with the left-hand column.

Example:
In the code above, if `doc.description` is undefined, then `doc.documentNum` will appear directly to the right of "Description" when it is rendered:

> **Title**                 MyTitle
> **Description**     12345
> **Number**           

when it ought to do this:
> **Title**                 MyTitle
> **Description**
> **Number**           12345

**Comment by cvrebert** [comment]
I can't reproduce with http://jsbin.com/paxica/4/edit on Mac Chrome:
![dlhoriz](https://cloud.githubusercontent.com/assets/419884/5717497/79483e8c-9ab6-11e4-8a4d-48d7f8923263.png)

**Comment by xabra** [comment]
cvrebert, 
Thank you.  You are correct.  I was using bootstrap 3.1.1.  
3.3.1 fixes the problem.
