### ISSUE TITLE
Tooltip font in 3.3.1 set to default

### ISSUE THREAD

**Issue by Khrysller** [twbs/bootstrap#15556]
I am using:
`<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400'>`

For all of my page, and after testing with bootstrap 3.3.1 the tooltip lost and now is using the default font. On the left the version before 3.3.1 with the Roboto Condensed font. On the right the 3.3.1.

![fonte](https://cloud.githubusercontent.com/assets/5774516/5722297/2d9c040c-9b22-11e4-9cab-602906e52ef9.jpg)

PS.: The font for the whole document stays with Roboto Condensed

**Comment by cvrebert** [comment]
Yes, this was done to fix #15046. See https://github.com/twbs/bootstrap/commit/2862c30320e8a1c0499f4bd83141e0c6cd959f1e#diff-8
You'll need to override those font settings.

**Comment by mdo** [comment]
Closing per @cvrebert's comment. We could say `inherit`, but that'd just lead to some problems I think.
