### ISSUE TITLE
Add flexgrid note to docs

### ISSUE THREAD

**Issue by homerjam** [twbs/bootstrap#15568]
This project covers my needs nicely - could be worth adding a note to the docs?

https://github.com/ptb/flexgrid

ps. I've made a PR to it which actually adds the necessary `flex-basis` attribute

**Comment by mdo** [comment]
Thanks, but I don't think we need to mention the project on our end. Folks will come along expecting us to offer some kind of support—even if it's just knowing the basics of that project—and we can't get into that.
