### ISSUE TITLE
Difference between carousel.less and boostrap.css

### ISSUE THREAD

**Issue by alberto-bottarini** [twbs/bootstrap#15564]
Hi, I got a quick reading of builded css downloaded from bootstrap website 3.3.1 and i see this:
    
    .carousel-inner > .item.next,
     .carousel-inner > .item.active.right {
        left: 0;
        -webkit-transform: translate3d(100%, 0, 0);
        transform: translate3d(100%, 0, 0);
      }

But inside carousel.less I see this:
    
    &.next,
    &.active.right {
        transform: translate3d(100%, 0, 0);
        left: 0;
      }

Building from less, I get some animation problem inside safari that requires -webkit prefix. 
How about that issue?

Thanks

**Comment by alberto-bottarini** [comment]
Ok, my mistake.
This WAS an error, fixed on 3.3.1

**Comment by cvrebert** [comment]
@alberto-bottarini You'll need to use Autoprefixer going forward; see 15473.
