### ISSUE TITLE
.btn-group-xs does not shrink nested badges

### ISSUE THREAD

**Issue by QuentinFchx** [twbs/bootstrap#15561]
The class `.btn-group-xs` does not shrink badges (`.badge`) presents in subsequents `.btn`

The [modification](https://github.com/twbs/bootstrap/blob/master/less/badges.less#L31) applied to badges when used inside `.btn-xs` is not applied when you use a group of buttons with the class `.btn-group-xs`.

[JSBin demonstrating the issue](http://jsbin.com/gegiyanezi/1/edit?html,output)

**Comment by mdo** [comment]
Fixed by #15628.
