### ISSUE TITLE
CSS Image rules standalone class

### ISSUE THREAD

**Issue by Merg1255** [twbs/bootstrap#15562]
Hi! I would like to ask if it would be possible to isolate the css rules for an image to an exclusive class. What I mean is, if the rules for the blue border and hover were not associated with img elements, we could use also use them to other elements.

**Comment by cvrebert** [comment]
FWIW, the blue border comes from the `.tab-focus()` mixin.

**Comment by Merg1255** [comment]
thanks, I had to inspect the rules and create a new class. That's why I thought it might be convenient for also others to have it as a standalone class for any element.

**Comment by mdo** [comment]
Punting on any other changes here. Nothing planned for v4 yet and no new additions to v3.
