### ISSUE TITLE
Showing tooltip removes space between trigger <span>s

### ISSUE THREAD

**Issue by ricardopolo** [twbs/bootstrap#15570]
In some code that is inside an HTML table if you have two spans with tooltips separated with an space, after the tooltip is shown in the first word the space is lost.

In this example John Doe, after show the tooltip in John you see JohnDoe.
![fasdf](https://cloud.githubusercontent.com/assets/1263856/5752106/d91e28da-9c3c-11e4-8dd4-30f930f463ab.gif)

This is javascript that we use for tooltips
````Js
$('.signtul-keyword').tooltip({ 'placement': 'bottom'})
````

This is the HTML
````html
<table>

<tbody>

<tr>

<td style="width: 256.4pt; padding: 3.75pt 0cm 3.75pt 7.5pt; height: 1pt;" width="513">
<p style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;">
<span style="font-size: 10.5pt; font-family: 'Segoe UI', sans-serif; color: #006196;">
<span title="First Name" class="signtul-keyword">John</span> <span title="Last Name" class="signtul-keyword">Doe</span>
</span>
</p>

</td>

</tr>

</tbody>

</table>
````

This is the Css
````css
.signtul-keyword:hover {
    background-color: #cccccc;
}
````

You might think why we have that complicated HTML but this is not in our control. This is a field the user can change so we should expected code disorder like this.
Any idea about why the Tooltip does not work in this HTML and how can we fix it?

**Comment by cvrebert** [comment]
JS Bin of the example: http://jsbin.com/moqimo/2/edit
Confirmed in Mac Chrome.

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/moqimo/2/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 19, column 87: The ```` width ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Without obsolete `width` attribute: http://jsbin.com/catisi/1/edit

**Comment by sdufel** [comment]
This is also an issue with any inline-block elements separated by space.

**Comment by wojarski** [comment]
The problem derives from from the fact that the tooltip div is inserted right next to the hovered element - in this case span which is an inline element. This breakes HTML for some browsers and may distort displaying inline elements as well.
I see two solutions here:
* usage of &nbsp; is sufficient
* modification of bootstrap's Tooltip.show() function - instead of inserting it next to the element:
this.options.container ? $tip.appendTo(this.options.container) : $tip.insertAfter(this.$element)
 it could be inserted e.g at the end of the document: 
this.options.container ? $tip.appendTo(this.options.container) : $("body").append($tip)

**Comment by peterblazejewicz** [comment]
It's also sufficient to add `display: inline-block;` to this target span:
http://jsbin.com/zicire/2/edit

**Comment by mdo** [comment]
Yeah, I'm fine punting on this given the `inline-block` solution and that this is just how HTML handles the white spaces between elements. Also giving thought to, in v4, changing from JS-based tooltips to only CSS-based ones. *Might* avoid some of this, but who knows.

**Comment by ricardopolo** [comment]
@peterblazejewicz @mdo As I said an HTML solution is not valid because the HTML is managed by the user.

**Comment by mdo** [comment]
And does the `container` option not help at all?

**Comment by ricardopolo** [comment]
@mdo can you explain me a littel bit more about the `container' option? Is in the HTML or modifying the JS fo Boostrap?

**Comment by peterblazejewicz** [comment]
@ricardopolo the problem is that content is added/replaced as is - within your elements as explained - try to attach tooltips to a most parent container of your text and see difference, using your sample:
```JavaScript
$(function () {
  $('.signtul-keyword').tooltip({ 'placement': 'bottom', 'container': 'table'});
});
```

**Comment by ricardopolo** [comment]
@peterblazejewicz options works!!!! Thank you.

But... the HTML is not controlled by me, so in some ocassions it is not inside a table.
Using 
````
 $('.signtul-keyword').tooltip({ 'placement': 'bottom', 'container': 'table'});
````

Works for this scenario, but not when the HTML is not inside a table.

Any idea?

**Comment by peterblazejewicz** [comment]
@ricardopolo - some parent - and it needs to be unique OK?, which holds your generated, dynamic content. We just don't know - for such questions like please use http://stackoverflow.com/questions/tagged/twitter-bootstrap

**Comment by ricardopolo** [comment]
Using @peterblazejewicz the issue was fixed.

For our case, calling:
````
$('.signtul-keyword').tooltip({ 'placement': 'bottom', 'container': '.keyword-container'})
````

Fixes the issue. Keyword container is the Div withing the tooltips appear.
