### ISSUE TITLE
.transition-property mixin with multiple values

### ISSUE THREAD

**Issue by adrianpuescu** [twbs/bootstrap#15572]
Using more than one properties in the '.transition-property' mixin is messing the compiler.
Example: `.transition-property(left, opacity);`

I found a possible solution:
```
.transition-property (@value1,@value2:X,...)
{
    @value: ~`"@{arguments}".replace(/[\[\]]|\,\sX/g, '')`;

    -webkit-transition-property: @value;
    -moz-transition-property: @value;
    -ms-transition-property: @value;
    -o-transition-property: @value;
    transition-property: @value;
}
```

**Comment by mdo** [comment]
Since we've deprecated the vendor mixins, I don't think we'll change anything here in v3.

**Comment by cvrebert** [comment]
Sounds okay to me.
@adrianpuescu Our vendor prefix mixins [have been deprecated](https://github.com/twbs/bootstrap/blob/149dac0a5873ff8547495dd21c5d65f8b24abf75/less/mixins/vendor-prefixes.less#L3) in favor of using [Autoprefixer](https://github.com/postcss/autoprefixer). We recommend other folks also adopt Autoprefixer (or similar automated solutions) going forward.
