### ISSUE TITLE
Add methods to check if widgets are currently shown/expanded/visible or not

### ISSUE THREAD

**Issue by addremove** [twbs/bootstrap#15573]
I'm surprised there's no request for a function that tells if a tooltip (or popover) is visible or maybe I missed it in the issues. The closest I could find was [this on Stackoverflow](http://stackoverflow.com/q/13442749/) (these are workarounds and could break unexpectedly in a future update). 

How about something like: 

      Tooltip.prototype.isVisible = function (obj) {
        var self = ...
        if (self && self.$tip && self.$tip.is(':visible')) {
          return true;
        } else {
          return false;
        }

I understand that it isn't completely deterministic since the result could change due to an animation timeout or mouse event.

**Comment by cvrebert** [comment]
What's your use case?

**Comment by addremove** [comment]
I'm frequently updating the tooltip title while it's visible to the user using `data-original-title` (unfortunately, another undocumented  property). Whether the title changes or not, I call `tooltip('show')`, which results in flicker. Ideally I should call it only when (i) the title needs to be updated or (ii) the tooltip has been hidden due to loss of focus. The second scenario requires checking for tooltip visibility.

**Comment by peterblazejewicz** [comment]
for reference: quick solution:
```JavaScript
$(selector).data('bs.tooltip') && $(selector).data('bs.tooltip').$tip.is(':visible');
```

**Comment by getub** [comment]
I find this more direct & short

    function isVisible($input){
        return ($input.attr('aria-describedby').length != 0)
    }

Between this and @peterblazejewicz 's solution which one's more robust and tolerant to future changes?

**Comment by Merg1255** [comment]
You should create a new report for any undocumented features you believe should be in there.

@mdo Could we have a formal way of checking visibility also for other elements? That could be consistent with the same function name on popover or tooltips.

**Comment by cvrebert** [comment]
It's more up to @fat since he's the JS plugin meister.
Adding a "is shown?" method to the widgets does sound reasonable to me, fwiw.
It'd probably get punted to v4 though.

**Comment by addremove** [comment]
It'll be good to have an `:animated` selector ([like this in jQuery](http://api.jquery.com/animated-selector/))

**Comment by Merg1255** [comment]
Right. Should make it for v4. "is shown" seems nice.

**Comment by mdo** [comment]
Punting to v4.

**Comment by otr-tomek** [comment]
```
var $is_visible = $item.attr('aria-describedby') || false;
				if (!$is_visible) {
					$item.tooltip('show');
				}
```
