### ISSUE TITLE
Not the correct size in the text input if I use the .form-group-lg in a horizontal form

### ISSUE THREAD

**Issue by Nikolay-Lipovtsev** [twbs/bootstrap#15571]
When I create a horizontal form with class size, the text input is generated with incorrect height. It is created with height 68px (the correct height for the Bootstrap official documentation is 46px).

This is my html:
```html
<form role="form" class="form-horizontal" id="new_user" action="/users" accept-charset="UTF-8" method="post">
  ...
  <div class="form-group form-group-lg">
    <label class="control-label col-sm-2" for="user_name">Control size</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" name="user[name]" id="user_name">
    </div>
  </div>
</form>
```

I think this is happening because in CSS of `.form-group.form-group-lg > .form-control` remains `height: auto`;

This is my large input:
![2015-01-14 19 11 39](https://cloud.githubusercontent.com/assets/5441376/5752741/2d381156-9c8d-11e4-930a-7577b4896155.png)

This is normal large input:
![2015-01-14 19 12 18](https://cloud.githubusercontent.com/assets/5441376/5752744/370db82a-9c8d-11e4-8cf4-61f03b60a69d.png)

CSS:
![2015-01-15 8 06 33](https://cloud.githubusercontent.com/assets/5441376/5752764/85350f44-9c8d-11e4-9a87-87111ce46214.png)

I use:
Safari 8.0.2 (10600.2.5)

Gems:
rails 4.2.0
sass-rails 4.0.5
sass 3.2.19
bootstrap-sass 3.3.1.0

**Comment by cvrebert** [comment]
Please post a JS Bin version of your example.

**Comment by Nikolay-Lipovtsev** [comment]
@cvrebert  http://jsbin.com/rudawazowe/2/edit
But in JS Bin it is ok

**Comment by twbs-lmvtfy** [comment]
Hi @Nikolay-Lipovtsev!

You appear to have posted a live example (http://jsbin.com/rudawazowe/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@Nikolay-Lipovtsev Does the issue occur on your own site if you use `http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css` instead of bootstrap-sass?

**Comment by Nikolay-Lipovtsev** [comment]
@cvrebert with `http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css` it is ok

**Comment by cvrebert** [comment]
Then if there is a bug in our code rather than your code, it's presumably a bug in bootstrap-sass. Please file an issue at https://github.com/twbs/bootstrap-sass Thanks!

**Comment by cvrebert** [comment]
X-Ref: https://github.com/twbs/bootstrap-sass/issues/823
