### ISSUE TITLE
.media-left should use margin instead of padding

### ISSUE THREAD

**Issue by mschipperheyn** [twbs/bootstrap#15587]
I just moved from 3.1 to 3.3 and I'm seeing a padding on the `.media-left`. Doesn't make sense to me as it screws up everything inside the `.media-left` item. Margin is much more natural approach for this.

Having experimented a little more with this after my entire layout collapsed I can say I'm not happy with the way media was changed. Padding inside the `.media-left` doesn't make sense at all (what if you have a border on `.media-left`?). I always hated the `overflow:hidden` problems the old `.media` created, but I guess I'll use the old one and try to work around that issue.

**Comment by mschipperheyn** [comment]
I guess with this approach you are forced to add an extra media-left wrapper around your a href="" class="circled-user-image", in stead of just putting href="" class="circled-user-image pull-left" like before, in order for the entire column not to be clickable and the image not being distorted in case it's treated as a background-image. Not exactly an elegant solution. Adds a lot of html boilerplate crud.

**Comment by mdo** [comment]
Yeah, not sure there's much else we can do here. Definitely not in v3 though—limiting those changes as much as we can to keep v4 moving.
