### ISSUE TITLE
Tag versions on gh-pages branch as well.

### ISSUE THREAD

**Issue by stefanmaric** [twbs/bootstrap#15586]
The `gh-pages` branch is very useful because it offers a downloadable version of Bootstraps' docs that do not require Jekyll.

I'm building a boilerplate repo to create Bootstrap themes, similar to [divshot/themestrap](https://github.com/divshot/themestrap), with the difference that it will only require `npm` and `bower` to be installed (no gulp, no ruby, no jekyll), it relies on npm scripts and it downloads Bootstraps' docs from Github requesting the `gh-pages` branch as zip, so one can test during theme development.

It works smoothly, but it can only download the latest state of the docs. If we start building a Bootstrap theme using, let's say, `v3.3.0`, after the `v4.0.0` release we cannot use the script to test the theme anymore because markup won't match.

There's a simple way to provide downloadable compiled docs as zip for every single Bootstrap release: manually tagging references to historical states of the `gh-pages` branch according to Bootstrap's releases, with some nomenclature like `v3.3.0-docs`.

Taking into account what @mdo said in #12915, this is a scalable solution due git's nature and Github's features; tags and branches behave kinda the same for these purposes.

If there's a more practical way to download compiled docs for a given Bootstrap release that I'm missing, please let me know and excuse me.

Regards.

**Comment by mdo** [comment]
The docs are tagged when we do a release, they're just not compiled. You can download the release and run the development commands in our readme to start them up. Then you can use that local copy of the docs for all you need.

**Comment by stefanmaric** [comment]
Sure they are included; my intention is to get a ready to browse docs without installing ruby and some gems. You know, making it just a bit more accessible. :)

Is this issue a totally no-go? I guess I can open a repo dedicated to publish Bootstrap's compiled docs and set some hooks with RSS. Not ideal, but it will work.

Best.

**Comment by mdo** [comment]
Yeah, we won't be doing it ourselves. Sorry about that, but I'd like to keep our deployment process as straightforward as possible.
