### ISSUE TITLE
Problem triggering a modal from menu dropdown on mobile

### ISSUE THREAD

**Issue by Cederman** [twbs/bootstrap#15595]
Hi,
I have a dropdown menu that opens a modal when clicked on. However, it never triggers when using mobiles. Does it have something to do with click/touch input?

Anyone who has any tips? I mean, it's not an uncommon feature =)

**Comment by cvrebert** [comment]
Please direct troubleshooting/how-to questions to StackOverflow. Thanks!

**Comment by Cederman** [comment]
But is it experter behaviour? I regard this as a bug, not lack of information.

**Comment by mdo** [comment]
You should be able to open a modal from a link within a dropdown menu as far as I know.

**Comment by Cederman** [comment]
Anyone who can replicate my issue?

The syntax is the same as proposed on the site:
```html
<li class="active dropdown open">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true"><i class="fa fa-list"></i> Tasks<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="/tasks"><i class="fa fa-bars"></i> Show all tasks</a></li>
						<li class="divider"></li>
						<li><a data-toggle="modal" data-target="#add-task-modal"><i class="fa fa-plus-square"></i> Add new task</a></li>
					</ul>
				</li>
```
