### ISSUE TITLE
.dropup should be mentioned in main Dropdown docs

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15597]
It's not currently mentioned in http://getbootstrap.com/components/#dropdowns but ought to be.
Right now it's only documented in the context of button groups (http://getbootstrap.com/components/#btn-dropdowns-dropup).
Refs #15142.

**Comment by mdo** [comment]
If there's something minimal we can do, I'm fine with it, but I don't want to be duplicating more things.
