### ISSUE TITLE
Derivation of @popover-max-width's value?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15608]
So, the default `@popover-max-width` is 276px, which seems particularly arbitrary. (275px could at least be rationalized as a multiple of 25 (and 25 itself can be rationalized, what with 25-cent coins etc.).) So how was its peculiar value arrived at?

**Comment by mdo** [comment]
Prior to `box-sizing` perhaps? I don't have a good reason off the top of my head other than that perhaps.

**Comment by cvrebert** [comment]
Okay. Added a note to revisit the value in v4.
