### ISSUE TITLE
checkbox/radio issues

### ISSUE THREAD

**Issue by jfoegen** [twbs/bootstrap#15603]
I am converting a project over from 3.1 to 3.3.1 and noticed my checkboxes were taking more height than they did previously.  Most were written before as:
```html
<div class="btn-group">
   <label class="checkbox">
      <input type="checkbox">
to
<div class="checkbox">
   <label>
      <input type="checkbox">
```
In the cases I am looking at the checkboxes have no text, like is show in the example on the getbootstrap site ("Checkboxes and radios without label text")

But what I noticed in looking at the heights in Chrome, the label takes a height of 20px (follows the min-height), but the div takes 25px.  I added the rule below and then the div is equal to the label in height.  Not sure if this is a bug or this effect was desired.
```css
.checkbox > label {
   display: block;
}
 ```
Thanks

**Comment by mdo** [comment]
`block` level `<label>`s are undesirable as all the white-space in that block—the negative space to the right of a short label, for example—become clickable. Putting checkboxes within a button group is also not supported.

**Comment by jfoegen** [comment]
When I look at it on your site, this is where I see the issue, whether or not the checkbox is in a button group.  Should the div really be taller than the label?  Again I was using it without any label text.

Thanks for all your work.

**Comment by mdo** [comment]
Can't help you without a live example. Try getting your code to run in something like <http://jsbin.com> to show us what you're seeing.

**Comment by jfoegen** [comment]
On the page, getbootstrap.com/css, go down to where the page discussed checkboxes without label text (id=”blankcheckbox”).

If you look at the checkbox example below in a browser debugger, the input is 13px high, the label is 20px high (due to the min-height), but the div with the checkbox class is 25px high, but why is the div taking up extra space?

So to get around the space problem, I added the block on the label, but like you said that has other side effects.  It is probably I don’t understand the difference between inline-block vs block in this case, but I just wanted to understand what is going on and if it is expected.  It does it in IE and Chrome.  The extra height was causing me some layout issues, so that is why I even found it and figured their may be other people with the same issue.

Thanks.

**Comment by jfoegen** [comment]
Let me know if you need a better or isolated example than the getbootstrap.com/css page

Thanks.
