### ISSUE TITLE
tooltip/popover 'destroy' needs event

### ISSUE THREAD

**Issue by dondi** [twbs/bootstrap#15607]
The tooltip/popover 'destroy' method is implicitly async because it calls `hide` first, and so a sequence like `$(selector).popover('destroy').popover({ ... })` does not reliably work.

I suggest that, like 'show' and 'hide', 'destroy' be given events 'destroy.bs.popover' and 'destroyed.bs.popover', so that a caller can know for sure that a 'destroy' is finished and can do whatever they need to do to the elements which depends on the tooltip/popover being cleared out.

**Comment by SaymV** [comment]
Seconded, Chain All the things!

**Comment by addremove** [comment]
Agreed, chaining would be very useful.

**Comment by pavel-lebedinsky** [comment]
+1.  Killed some hours while working with tooltips.

**Comment by mdo** [comment]
Is this a bug or a feature @cvrebert? If the latter, shall we punt to v4?

**Comment by fat** [comment]
I think the real problem here is that "destroy" was conflated with "hide", making it async… which is probably not the best.

At any rate, we are going to revisit teardown methods in v4, thanks for the input!

**Comment by seyfer** [comment]
@fat was it fixed in bootstrap v3.4.0? seems like not...

**Comment by kostetskyroma** [comment]
@seyfer did you find some workaround?
