### ISSUE TITLE
Position of X-UA-Compatible <meta> tag should be mentioned in the "Browser and device support" doc

### ISSUE THREAD

**Issue by cweinreben** [twbs/bootstrap#15601]
Recently I had some issues with the IE compatibility mode. The X-UA-Compatible meta tag was present in the head section of my page. Nevertheless, in IE 8 the compatibility mode button was still visible in the browser status bar.
The solution was to include the meta tag as the first entry of the head section.

**Comment by cvrebert** [comment]
Well, really the `charset` meta tag needs to come first if you're using all 3 tags used in our examples.

**Comment by cvrebert** [comment]
Maybe we could add a comment to the templates?:
```html
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>
```

**Comment by cweinreben** [comment]
Sounds good. I can test this with a WinXP 32 bit IE8 system.

**Comment by cweinreben** [comment]
Hi Chris,
I have tested the IE8 behavior. The compatibility mode pops in when a link tag comes before the X-UA-Compatible tag. So the comment you suggested should be enough.
Thanks

**Comment by vlakoff** [comment]
To clarify out and hopefully save some time to other people:

* meta `charset` has to be the very first tag, *ever*.
* meta `X-UA-Compatible` has to come before `link` tags, according to above statement by cweinreben. So, 2nd position is a fine place.
* meta `viewport` doesn't seem to cause trouble (refs https://github.com/twbs/bootstrap/pull/15658#issuecomment-72626810). So, 3rd position to keep it close to the others.
