### ISSUE TITLE
v3.3.2 NuGet package?

### ISSUE THREAD

**Issue by enashnash** [twbs/bootstrap#15612]
checking css:

.glyphicon-tree-deciduous:before {
  content: "\e200";
}

is present, whereas

.glyphicon-cd:before {
  content: "\e201";
}

and onwards, is not.

**Comment by enashnash** [comment]
okay just found the commit, upgrading the icons to v1.9
https://github.com/twbs/bootstrap/commit/bcb90ef3a0affa6540d141733a073593011af064

when can we expect the 3.3.2 release to be available via nuget?

**Comment by cvrebert** [comment]
[The NuGet package](https://www.nuget.org/packages/bootstrap/) is a third-party package controlled by the Outercurve Foundation, not by the Bootstrap Team. You can contact Outercurve via the "Contact Owners" link on https://www.nuget.org/packages/bootstrap/ . Thanks!
