### ISSUE TITLE
Popovers: Incorrect offset/position when shown outside viewport

### ISSUE THREAD

**Issue by kafoso** [twbs/bootstrap#15616]
The "popovers" elements appear at incorrect positions when shown while the triggering element (e.g. a `<button>`) is outside the current viewport.

**Example:**
- http://jsfiddle.net/y1z7gc1t/4/
 - The buttons appear in the bottom-right corner.
 - The popovers anchored `left` and `right` appear at the top-right corner.
 - The popovers anchored `top` and `bottom` appear at the bottom-left corner.
 - The popover arrows (`.arrow`) appear with the buttons.

**Reproduction:**
- Add elements (e.g. buttons), which appear outside the current viewport (e.g. a `padding-top` and `padding-left` of `2000px`, as in the jsfiddle example).
- Setup and trigger a `show` on said elements.
- The popovers in incorrect positions, both vertically (`top` and `bottom`) and horizontally (`left`and `right`).

**Notice:**
- The popovers will also appear in incorrect positions if the triggering element is very close to the edges of the current viewport.
- The popover's arrows appear close by the triggering elements. This is emphasized in the jsfiddle example by a red background on the `.arrow` elements.

- - -

I see this issue mentioned many places, but it has not yet been correctly addressed or fixed.

**Comment by fat** [comment]
Thanks for reporting - this is a known issue. We plan on replacing the positioning engine for tooltips/popovers in v4.

thanks!
