### ISSUE TITLE
.media-body element not spanning full width

### ISSUE THREAD

**Issue by draganbabic** [twbs/bootstrap#15615]
There's a problem with the `.media-body` element that won't span the full width of it's container if it doesn't contain enough content to push it so far. 

Here's a demo. 

http://jsbin.com/xaxerewuba/4/edit?html,output 

I ran into this issue because I need an element floated to the right within `.media-body` and noticed it won't go all the way to the right. 

I tried adding `display: table;` to the `.media` element had some unwanted side-effects. 

Video: https://bakara.s3.amazonaws.com/screenshots/sprawsm-screenshot-2015-01-20-vkbae_0_edited.mp4

**Comment by twbs-lmvtfy** [comment]
Hi @draganbabic!

You appear to have posted a live example (http://jsbin.com/xaxerewuba/4/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 17, column 5: [W010](https://github.com/twbs/bootlint/wiki/W010): Using `.pull-left` or `.pull-right` as part of the media object component is deprecated as of Bootstrap v3.3.0. Use `.media-left` or `.media-right` instead.
* line 33, column 5: [W010](https://github.com/twbs/bootlint/wiki/W010): Using `.pull-left` or `.pull-right` as part of the media object component is deprecated as of Bootstrap v3.3.0. Use `.media-left` or `.media-right` instead.
* line 49, column 5: [W010](https://github.com/twbs/bootlint/wiki/W010): Using `.pull-left` or `.pull-right` as part of the media object component is deprecated as of Bootstrap v3.3.0. Use `.media-left` or `.media-right` instead.
* line 50, column 5: [W010](https://github.com/twbs/bootlint/wiki/W010): Using `.pull-left` or `.pull-right` as part of the media object component is deprecated as of Bootstrap v3.3.0. Use `.media-left` or `.media-right` instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@draganbabic Please upgrade to Bootstrap v3.3.2.

**Comment by draganbabic** [comment]
Awesome, thanks @cvrebert
