### ISSUE TITLE
There are both .glyphicon-euro and .glyphicon-eur in the doc

### ISSUE THREAD

**Issue by bastienmoulia** [twbs/bootstrap#15617]
One is `glyphicon-euro`, and the other `glyphicon-eur`.
Also the number of glyphicon is 258 instead of 260 (2 are removed).

**Comment by cvrebert** [comment]
Yes, we added `-eur` for uniformity in #14867. `-euro` remains for backward compatibility.
Given that we're never going to remove `-euro`, it's not really a problem.

**Comment by juthilo** [comment]
IMO, both classes being in the docs is just thorough, not repetitive. And the number 260 is easier to comprehend at first glance.

**Comment by bastienmoulia** [comment]
In that case, for #14867, `glyphicon-ruble` must also be `glyphicon-rub`, and `glyphicon-yen` must be `glyphicon-jpy`.
It's interesting to have it in the less, but in the documentation a phrase to inform the user of the backward compatibility is enough. No need to duplicate the glyph because that can trouble the user which will use one syntax or the other for the same things.
