### ISSUE TITLE
[I'm not sure if this is a bug] .panel-heading custom colours

### ISSUE THREAD

**Issue by zudomc** [twbs/bootstrap#15626]
I don't know if this is a bug or not, but it occurs in both IE and Chrome and I can't find a way of fixing it.

When attempting to recolour a .panel-heading, there are little parts that don't change (see below). As I say, this looks like a bug but it could be just me.

![Bug](https://cloud.githubusercontent.com/assets/4703499/5837575/3b9cbad6-a178-11e4-854c-ba57bae5e64e.png)

Fiddle: http://jsfiddle.net/o6zdhzb4/

**Comment by juthilo** [comment]
Please provide a live code example of the problem, e.g. in a JS Bin. We can't do much with screenshots and I'm not able to reproduce just by changing `.panel-heading`'s main colors.

**Comment by zudomc** [comment]
@juthilo done.

**Comment by cvrebert** [comment]
Was that generated using [`.panel-heading-styles`](https://github.com/twbs/bootstrap/blob/1ce502dc4de0accf27a6c37c21d26f4739d09241/less/theme.less#L251) and [`.panel-variant`](https://github.com/twbs/bootstrap/blob/1ce502dc4de0accf27a6c37c21d26f4739d09241/less/mixins/panels.less#L3)? That's the pattern you should be following.

**Comment by mdo** [comment]
Not a bug on our end—it's a shortfall of CSS and browser. The background color of the `.panel` is bleeding through the rounded corners. You can override this with different `border-radius` and some `overflow`, but that can lead to other problems as well.
