### ISSUE TITLE
box-sizing support for Firefox <= 28 and Android <= 2.3

### ISSUE THREAD

**Issue by julianxhokaxhiu** [twbs/bootstrap#15625]
Hi,

I was trying my fresh new website on Firefox OS 1.3 ( aka Firefox 28 engine ) and I was astonished to see that it wasn't working as expected out of the box.

Now the question that pops in my mind is:
- why are you not using `-moz-box-sizing`? This breaks compatibility with Firefox <= 28
- why are you not using `-webkit-box-sizing`? This breaks compatibility with Android <= 2.3

Thanks in advice,
Julian

**Comment by juthilo** [comment]
We do use those vendor prefixed property versions, [in the compiled CSS, here](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L1060-1064) and [in our Less source, here](https://github.com/twbs/bootstrap/blob/master/less/mixins/vendor-prefixes.less#L73-78).

Can you share an example that demonstrates this problem? Might also be a browser bug. Please note that we only unofficially support the "Android Stock Browser" and, if at all, Firefox OS.

**Comment by julianxhokaxhiu** [comment]
Honestly I'm using (Bootstrap SASS)[https://github.com/twbs/bootstrap-sass ] from bower and compiling it through a custom grunt stack, but based on pure SASS from Ruby (no Compass).

May this be a problem? Or maybe that repo has something missing?

**Comment by cvrebert** [comment]
Is your stack missing Autoprefixer? As mentioned in our docs, its usage is required: http://getbootstrap.com/getting-started/#download-autoprefixer

**Comment by julianxhokaxhiu** [comment]
Yes I'm having it but I wasn't using the Firefox rule :) I added it like today. So this is the way to go, officially documented :D

Thanks for the clarifications! Was just curious to know about this side effect :)

**Comment by adam-beck** [comment]
@juthilo I am seeing the mixin in the less file you posted, however, whenever I compile my custom less file using that mixing the vendor prefixes are omitted. I understand that autoprefixer is required but I'm more or less curious why this isn't working?
