### ISSUE TITLE
Popover is not positioned correctly when viewport property is used

### ISSUE THREAD

**Issue by amiklosi** [twbs/bootstrap#15627]
You can see the issue in this fiddle: http://jsfiddle.net/699rsu57/

The fix is actually quite easy for this: 
In tooltip.js getViewportAdjustedDelta function the line

} else if (rightEdgeOffset > viewportDimensions.width) { // right overflow

should read

} else if (rightEdgeOffset > viewportDimensions.right) { // right overflow

**Comment by klakshman318** [comment]
copy below html text to html file

<div>
    <div class="para">
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed <span class="back">CLICK ME</span> eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
</div>




@import url('http://getbootstrap.com/dist/css/bootstrap.css');
.back{
 position:relative;   
}
}
.para {
    background-color: #999;
    width: 300px;
    position:relative;
    margin-left: 300px;
}

**Comment by klakshman318** [comment]
![screen](https://cloud.githubusercontent.com/assets/6956024/5840837/61150fb6-a1be-11e4-8573-212b0e8f64b1.jpg)

**Comment by fat** [comment]
in v4 we're going to rewrite the position engine/use a 3rd party one.

meanwhile - i'm happy to review a pr if you or someone else wants to make this change
