### ISSUE TITLE
Glyphicon height offset issue

### ISSUE THREAD

**Issue by neesonqk** [twbs/bootstrap#15636]
Tested chrome 40 (zoom 125%) has the issue, IE 11 doesn't have.

Put three same inputs with glyphicon, the first one works fine, the last two have offset issue, they are using the same code,

![error](https://cloud.githubusercontent.com/assets/7279067/5853739/87e3befa-a261-11e4-8f4c-c3e0d34b582c.PNG)

```html
<div class="form-group has-success">
                    <div class="input-group">
                        <span class="input-group-addon">@</span>
                        <input type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group has-success">
                    <div class="input-group">
                        <span class="input-group-addon">@</span>
                        <input type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group has-success">
                    <div class="input-group">
                        <span class="input-group-addon">@</span>
                        <input type="text" class="form-control">
                    </div>
                </div>
```
Obviously, bootstrap website demo examples have the same issue in some particular conditions

has
![website2](https://cloud.githubusercontent.com/assets/7279067/5853824/3e9a5f0a-a262-11e4-8a6c-aab17ddd53f4.PNG)

doesn't have
![website](https://cloud.githubusercontent.com/assets/7279067/5853830/498e9ca0-a262-11e4-80e2-4b286f556dfb.PNG)

**Comment by juthilo** [comment]
X-Ref: https://github.com/twbs/bootstrap/issues/15497
Also, this general note in the docs: http://getbootstrap.com/getting-started/#support-browser-zooming

**Comment by mdo** [comment]
Yeah, there likely won't be any changes to this in v3 per @juthilo's comment.
