### ISSUE TITLE
Different line-height in .form-control and .btn

### ISSUE THREAD

**Issue by blatan** [twbs/bootstrap#15631]
Hello.
You defined the height of .form-control class:
`height: $input-height-base;`
but in .btn you didn't defined the height. It causes a problem.
It's from bootstrap-sass, but it's the same on getbootstrap.com as well.

What happened in my case?
I defined `$font-size-base: 16px`, thus the height of the input has been set to 34px, but the height of the button has beend set to computed value: 36px;

The button is higher than the input.

When I changed `$font-size-base` to the default value everything is ok.

What is the solution of the issue?

1. Set 
```
.btn {
	height: $input-height-base;
}
```
2. Or set:
```
.form-control {
	height: auto;
}
```
3. Or delete the definition of the height from .form-control.

**Comment by mdo** [comment]
We won't be setting the `height` on buttons. For v3.x, honestly there's not too much I feel we can do to fully support all this. v4 will be much more flexible in the sizing of things (at least I hope). If you need to set the height, do so on your end as an override. Sorry for the pain there—form controls are rough.
