### ISSUE TITLE
Incorrect glyphicon displayed inside button

### ISSUE THREAD

**Issue by onebree** [twbs/bootstrap#15644]
- **Ruby 1.9.3., Rails 4.2.0**
-  **GEMS:  bootstrap_form (2.2.0), bootstrap-sass (3.3.1.0)**
- **Firefox ESR 31.3.0**

I am editing the view of a page, and replacing a text link with a button link. I figured out how to correctly do so; however, the glyphicon generated does not match what I chose in the view.
```haml
%a{class: "btn btn-warning", role: "button", href: edit_ip_path(ip)}
  %span.glyphicon.glyphicon-pencil
```
Instead, some envelope (or whatever) appears. Interestingly enough, even the browser's dev panel shows I entered `glyphicon-pencil`
![screenshot from 2015-01-22 16 53 40](https://cloud.githubusercontent.com/assets/9038433/5865433/43217668-a257-11e4-8104-792a30934060.png)

To make sure the icon was not a weird-shaped pencil, I tested `glyphicon-star`:
![screenshot from 2015-01-22 16 55 54](https://cloud.githubusercontent.com/assets/9038433/5865463/8d0b438a-a257-11e4-90da-39d871233f80.png)

Thank you for any and all help. As needed, I will submit any code you guys need.

**Comment by cvrebert** [comment]
Are you using bootstrap-sass v3.3.3 ?

**Comment by onebree** [comment]
@cvrebert I just updated my original comment. No, I am using v. 3.3.1.0 -- is this issue resolved in the newer release?

**Comment by cvrebert** [comment]
There was a Glyphicon-related bug in 3.3.2 that was fixed in 3.3.3, so guess that's not your issue.
Please re-file this issue in the correct repo: https://github.com/twbs/bootstrap-sass

**Comment by onebree** [comment]
I submitted an issue there. Thank you for pointing me in the right direction. For future reference, when should I submit an issue to bootstrap-sass, vs bootstrap itself?

**Comment by cvrebert** [comment]
If you can reproduce the issue with "regular" Less-based Bootstrap, file it here. Otherwise, file it with bootstrap-sass.

**Comment by cvrebert** [comment]
X-Ref: https://github.com/twbs/bootstrap-sass/issues/834
