### ISSUE TITLE
tooltip in navbar doesn't work

### ISSUE THREAD

**Issue by kwladyka** [twbs/bootstrap#15643]
Tooltip doesn't appear when is in navbar.

JS
```
$(document).ready(function(){
	$("[data-toggle='tooltip']").tooltip();
});
```
HTML
```
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-menu">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" ui-sref="home"><img src="img/logo.png"></a>
		    </div>

			<p class="navbar-text collapse navbar-collapse">dobrze opisane oferty nieruchomości</p>

			<div class="collapse navbar-collapse navbar-right" id="navbar-collapse-menu" ui-view="menu">

				<div class="nav navbar-nav">
					<!-- <a ui-sref="login" class="btn btn-default navbar-btn">Zaloguj się</a> -->
					<!-- <a ng-click="toogleFeedback();" ><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;&nbsp;Feedack</a> -->
					<a class="btn btn-default navbar-btn" data-toggle="tooltip" data-placement="bottom" title="Feedback &amp; Bugs"><i class="glyphicon glyphicon-bullhorn"></i></a>
					<a ui-sref="add-offer" class="btn btn-primary navbar-btn">Dodaj ofertę</a>
				</div>
			</div>
		</div>
	</nav>
```

The line
```<a class="btn btn-default navbar-btn" data-toggle="tooltip" data-placement="bottom" title="Feedback &amp; Bugs"><i class="glyphicon glyphicon-bullhorn"></i></a>```

works when is in body.

**Comment by cvrebert** [comment]
The navbar component has some very specific markup structure requirements, and yours looks a bit wonky (e.g. `navbar-nav` should be on a `<ul>` rather than a `<div>`).
Tooltips seem to work fine with correct navbar markup: http://jsbin.com/kulape/1/edit
Fully debugging the errors in your navbar's structure for you is outside the scope of this issue tracker. Use the examples in the docs (http://getbootstrap.com/components/#navbar) as your guide for what's valid, and/or ask on StackOverflow. Thanks!

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/kulape/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kwladyka** [comment]
I found it's because ```ui-view="menu"````

AngularJS do something magic ( i don't have any idea what ) what disturb tooltip.

**Comment by cvrebert** [comment]
When using Angular, you should generally use an Angular reimplementation of Bootstrap's JavaScript, such as http://angular-ui.github.io/bootstrap/ , rather than Bootstrap's jQuery plugins.
