### ISSUE TITLE
Suggestion for Breadcrumb

### ISSUE THREAD

**Issue by mewsoft** [twbs/bootstrap#15642]
Just withing to be something like this:

![breadcrumbs-bootstrap](https://cloud.githubusercontent.com/assets/7512085/5861330/faa3edfc-a270-11e4-9527-dbfc67c7003e.jpg)

http://metroui.org.ua/buttons.html#_breadcrumbs

**Comment by mdo** [comment]
We'll keep it as-is with the simpler styles. The above screenshot is definitely something that should be done with an add-on or overrides of your own.
