### ISSUE TITLE
Tabs as navigation across pages

### ISSUE THREAD

**Issue by birdwing** [twbs/bootstrap#15641]
There are a lot of server side languages such as PHP which allow you to include one file into multiple pages.

This works great for navigation! However if you are using Tabs (with Pill styling) the Tab.js file prevents the default link action. This works great if the "Tab" is on the page that the Tab-Panel is also on, but if the "Tabs" are in a navigation bar that gets included on multiple pages this is not always the case.

It would be nice if the links default action was only prevented if the Tab-Panel exists on the page. So if it doesn't exist it works like a normal link and takes you to the page the Tab-Panel does exist on.

Of course it would still be up to the designer to then display the proper Tab-Panel, but this can be easily accomplished on the back end as well when the page is loading.

**Comment by cvrebert** [comment]
If you omit the `data-toggle="tab"` then the links should work normally as our jQuery plugin won't be activated.

**Comment by birdwing** [comment]
correct, but then they do not work if they are included on the page which has the tab-panels.

I suppose you could right some serverside code and set a variable before the included content that would toggle whether or not to include the data-toggle portion.

**Comment by cvrebert** [comment]
Those tab-panels would be empty dummies though, right?

**Comment by birdwing** [comment]
Sorry let me try and explain a little better.
Lets say I have a small website that lists my Favorite Books, and my Favorite Movies.

I have one page (books.php) which holds all the information for my Favorite Books. This information is displayed using tabs and tab-panels.

I have another page (movies.php) which holds all the information for my Favorite Movies. This information is also displayed using tabs and tab-panels.

I then make the decision to move the "tabs" to a sidebar and display them as Pills.
I create two more files to hold these sidebars. (booksNav.php) and (moviesNav.php).
I include both of those Nav files into the sidebar of both of the other files.

When I am on the (books.php) page clicking on a pill included from the (booksNav.php) file should just switch the tab-panels. But clicking on a pill included from the (moviesNav.php) does nothing. But If I am on the (movies.php) page and click on something from (moviesNav.php) it updates the tab panels and clicking on something from (books.php) does nothing.

My suggestion is that If the Tab-Panel doesn't exist on the page, that the tab/pill act like a normal link. So that it would be easier to use Tabs/pills with Included files.

it would still be up to the designer to pass information in the URL to tell the page what tab to open when it loads.

So with my suggestion:
If I am on the books page and a click something from (booksNav.php) it just switches the tab-panel, but If I click on something from (moviesNav.php) it follows the URL acting like a regular link.

I would then be able to set up a tab like this (in the moviesNav.php page):
```html
<li role="presentation" id="LOTRTab"><a href="movies.php#LOTR" aria-controls="LOTR" role="tab" data-toggle="pill">Lord of the Rings</a></li>
```
This tab would work on both pages. On the (movies.php) page it would just change the tab-panels to display the appropriate content (I've tested this it already works as is).
On the (books.php) page it would take the user to (movies.php#LOTR) acting like a normal link.

Then on both pages all I would need to do is something like this:
```javascript
if(hash = window.location.hash) {
    /* loop to remove the active class from all tabs and tab-panels*/
    $(hash + "Tab").addClass('active');
    $(hash).addClass('active');
}
```

Now I can properly use tabs/pills in template files to be included on multiple pages.

**Comment by birdwing** [comment]
Its also worth noting that checking to see if the tab-panel exists before preventing the links default action would not break the functionality of the tabs at all.

If the Designer does not put in a full url and just the hash then even if it acts like a standard link it will do nothing because that ID does not exists on the page.

**Comment by fat** [comment]
as you mentioned before this can already be achieved with what seems to be a trivial amount of html logic (simply don't put data-toggle="pill" on the tabs that have real urls).

Also, from a ux perspective, it's pretty bad practice for some of your tabs to provide resolvable urls and others not to.

My advice would to either go all in or not, just my 2cents.
