### ISSUE TITLE
tooltip/popover data-animation option doesn't work

### ISSUE THREAD

**Issue by powange** [twbs/bootstrap#15654]
In setting popover, the option data-animation doesn't work.

**Comment by cvrebert** [comment]
Unable to reproduce: http://jsbin.com/citom/2/edit
Please post a JS Bin demonstrating the problem.

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/citom/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Closing due to lack of response to my request.
