### ISSUE TITLE
Provides a "col-all-1..12" class

### ISSUE THREAD

**Issue by joao-gsneto** [twbs/bootstrap#15655]
Instead the use of:

div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"

Provides a class to use with:

div class="col-all-3" that set 3 to all screen sizes!

Thanks.

**Comment by mdo** [comment]
You can just use `.col-xs-3`. It'll apply to every viewport.

**Comment by cvrebert** [comment]
Additional docs: https://github.com/twbs/bootlint/wiki/E029
