### ISSUE TITLE
anchor tag data not accessible when clicking on glyphicons inside the anchor tag

### ISSUE THREAD

**Issue by artitw** [twbs/bootstrap#15666]
Below is a reproduction and code
http://jsfiddle.net/sua0yp4y/2/
```
<h1 id="output1">OUTPUT1</h1>
<h1 id="output2">OUTPUT2</h1>
<a class="withIcon" href="#" data-taskid="1123" data-userid="5813"><span class="glyphicon glyphicon-time"></span></a>

<h1 id="output3">OUTPUT3</h1>
<h1 id="output4">OUTPUT4</h1>
<a class="withoutIcon" href="#" data-taskid="1123" data-userid="5813">without icon</a>
```
```
$('body').on('click','a.withIcon',function(e){
	e.preventDefault();
    $("h1#output1").text($(e.target).data('userid'));
    $("h1#output2").text($(e.target).data('taskid'));
});

$('body').on('click','a.withoutIcon',function(e){
	e.preventDefault();
    $("h1#output3").text($(e.target).data('userid'));
    $("h1#output4").text($(e.target).data('taskid'));
});
```

**Comment by twbs-lmvtfy** [comment]
Hi @artitw!

You appear to have posted a live example (http://fiddle.jshell.net/sua0yp4y/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 45, column 97: An element with ```` role=menuitem ```` must be contained in, or owned by, an element with ```` role=menu ```` or ```` role=menubar ````.
* line 49, column 100: An element with ```` role=menuitem ```` must be contained in, or owned by, an element with ```` role=menu ```` or ```` role=menubar ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by artitw** [comment]
Thanks, I have revised the example code.

**Comment by patrickhlauke** [comment]
This seems to be an issue with how jQuery's ``on`` method handles (or doesn't, in this case) event bubbling. The same effect can be seen if you added a ``<span>`` inside the "without icon" link, even without adding Bootstrap into the mix. Therefore, I'd suggest asking on StackOverflow or similar about a possible workaround.
