### ISSUE TITLE
Navbar: width of parent-entity <a> retains natural width of scaled down child-img

### ISSUE THREAD

**Issue by olafguesswhapp** [twbs/bootstrap#15664]
Instead of displaying the brand in the navbar as text I included the img of the brand-logo which I scaled down for responsive reasons with "max-width 50%". the parent of the img is a hyperlink tag <a>. the issue: the width of <a> remains displaying the original width of 100% of the img (being 350px instead of 50% of 350px). I have not been able to find a solution and kindly ask for your help.
```html
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
    <a class="navbar-brand" href="#" style="background-color: black;">
        <img src="http://placehold.it/350x150" style="max-width: 50%;">
    </a>
</div>
```

**Comment by cvrebert** [comment]
Please direct how-to questions and general HTML/CSS questions to StackOverflow (or other similar forums). Thanks!
