### ISSUE TITLE
Adding a box behind the text

### ISSUE THREAD

**Issue by Reusistic** [twbs/bootstrap#15667]
Greetings!

This may be a relatively noob-ish question, but please bear with me, as I am kind of new to Bootstrap. This may or may not even have too much to do with Bootstrap, but yeah.

So, I am a new freelance website developer, and I'm currently working on my third project. This time I get to work together with a graphics artist, who created a background image for me to use for the site. I added the background image and it fits quite well with the header he also created, although here comes the problem.

The text is put on top of the background image itself, so it's very hard to read what the text says. I know for a fact that it's possible to add a box/container behind the text, as I had that for my previous project. Although I am not quite sure how to add that from scratch. I tried to use some of the code from my previous project and implement it in the new one, but it didn't really help.

Anyone who can help me here? I'd love to have readable text.

**Comment by cvrebert** [comment]
This issue tracker is only for bugs and feature requests for Bootstrap itself. Please direct how-to and troubleshooting questions to StackOverflow instead. Thanks!
