### ISSUE TITLE
Bootstrap displays double scrollbar on modals

### ISSUE THREAD

**Issue by morgan-linux** [twbs/bootstrap#15669]
I have a problem with last version of Bootstrap.
This is a recurring problem in Bootstrap for years, with many solutions and (un)official fixes but nothing works on my side. I suspect the problem to be different in a lot of cases.

I have a scrollbar on the overlay, and the body's scrollbar is still visible. So I have two scrollbars on my page, that's hideous and the body scrolls when I reach the end of the modal.

On the demo page of Bootstrap, on .modal-open, the following style is applied :
```
.modal-open {
overflow: hidden;
}
```

On my page, this CSS rule has no effect. Why?

Also, Bootstrap also shifts the content on modals that are not highest than the visible screen. So my content is "glitching" uselessly.

**Comment by vanesyan** [comment]
Maybe you apply `overflow(-x, y): hidden` to `html` element, so it can make this effect, problem like so we can see on `medium.com` when fire modal.

**Comment by morgan-linux** [comment]
Oh! Thanks a lot, that's true. I completely forgotten this old hack into my html{}
Sorry for the inconvenience.
