### ISSUE TITLE
Table breaks inside collapsible panel

### ISSUE THREAD

**Issue by rasca** [twbs/bootstrap#15672]
When using a table as a panel content, it breaks when collapsing.

Check out this example, just click in the panel title to show the broken content http://jsfiddle.net/pyvqv9f2/1/

Tested in Chromium 39 and Firefox 34

**Comment by twbs-lmvtfy** [comment]
Hi @rasca!

You appear to have posted a live example (http://fiddle.jshell.net/pyvqv9f2/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 15, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0
* line 16, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rasca** [comment]
Updated example: http://jsfiddle.net/pyvqv9f2/2/

**Comment by cvrebert** [comment]
This is approximately the `<table>` equivalent of #12593.

**Comment by rasca** [comment]
Yeah, it seems like the same issue, adding:
```css
table.collapse.in {
    display: table;
}
```
fixes the issue.

The animation doesn't work though, but that may be worthwhile opening a different issue.

**Comment by mdo** [comment]
Not currently possible as we can't set the `height` on a `<table>` itself. We could try switching to using `max-height` mind you, but that'd be inconsistent with our other collapsing components.
