### ISSUE TITLE
better for popover extend.

### ISSUE THREAD

**Issue by icai** [twbs/bootstrap#15676]
https://github.com/twbs/bootstrap/blob/master/js/tooltip.js#L267
change to 
    var isVertical          = /^(top|bottom)/.test(placement)

may be better.

**Comment by cvrebert** [comment]
Why?

**Comment by kkirsche** [comment]
I'm not very familiar with tooltip.js so I could be wrong about this, but I think @icai's logic is that you don't want to change match value that isn't exactly "top" or "bottom". I believe the existing regex would match attributes such as `margin-top` as they include the word we are checking for since we are not anchoring it. If we wanted to be more specific though I would probably say it should be `/^(top|bottom)$/.test(placement)` though so that we anchor it to exactly "top" or exactly "bottom".

I could be wrong though :)

**Comment by cvrebert** [comment]
There are several places in the Tooltip plugin that assume `placement` (after removing `auto`) must be one of `left`, `right`, `bottom`, or `top`, and not any other value. Changing the plugin from having a closed-world assumption (that we know all possible legal `placement` values) to an open-world assumption is nontrivial.
If you're extending the plugin to add such a significant feature as additional placements, you're going to need to override or modify a few methods. Simply tweaking the regexes in the vanilla plugin itself (like is being proposed) won't be sufficient.

**Comment by icai** [comment]
I want to extend the popover placement (right-bottom, right-top ......), 

    $.fn.popover.Constructor.prototype.getCalculatedOffset = function (placement, pos, actualWidth, actualHeight) {
        return placement == 'bottom' ? { top: pos.top + pos.height,   left: pos.left + pos.width / 2 - actualWidth / 2  } :
               placement == 'top'    ? { top: pos.top - actualHeight, left: pos.left + pos.width / 2 - actualWidth / 2  } :
               placement == 'left'   ? { top: pos.top + pos.height / 2 - actualHeight / 2, left: pos.left - actualWidth } :
               placement == 'right' ? { top: pos.top + pos.height / 2 - actualHeight / 2, left: pos.left + pos.width   } :
               placement == 'bottom-left' ? {top: pos.top + pos.height, left: pos.left + pos.width / 2 - (actualWidth * 0.10)} :
               placement == 'top-left' ? {top: pos.top - actualHeight,  left: pos.left + pos.width / 2 - (actualWidth * 0.10)} :
               placement == 'bottom-right' ? {top: pos.top + pos.height, left: pos.left + pos.width / 2 - (actualWidth * 0.90)} :
               placement == 'top-right' ? {top: pos.top - actualHeight, left: pos.left + pos.width / 2 - (actualWidth * 0.90)} :
               placement == 'right-top' ? {top: pos.top + pos.height / 2 - (actualHeight * 0.10), left: pos.left + pos.width} : 
               placement == 'left-top' ? {top: pos.top + pos.height / 2 - (actualHeight * 0.10), left: pos.left - actualWidth} :
               placement == 'right-bottom' ? {top: pos.top + pos.height / 2 - (actualHeight * 0.90), left: pos.left + pos.width} :
               /* placement == 'left-bottom' */ {top: pos.top + pos.height / 2 - (actualHeight * 0.90), left: pos.left - actualWidth}
    }

but the `$.fn.popover.Constructor.prototype.applyPlacement = function(offset, placement){` method is too long. I must copy this again, but just change the `/top|bottom/.test(placement)`  to  `^(top|bottom)$/.test(placement)` 

do you have a better idea for me to do this?  @cvrebert @kkirsche  thanks
