### ISSUE TITLE
.caret is smaller in Firefox than other browsers

### ISSUE THREAD

**Issue by vsn4ik** [twbs/bootstrap#15682]
Before and after: http://jsbin.com/daguhewoka/2/edit?html,css,output.

For fix change `solid` to `dashed` in https://github.com/twbs/bootstrap/blob/master/less/dropdowns.less#L13.

I believe that it is necessary to add a comment: `// dashed: fix caret size for Mozilla Firefox`.

**Comment by twbs-lmvtfy** [comment]
Hi @vsn4ik!

You appear to have posted a live example (http://jsbin.com/daguhewoka/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by vsn4ik** [comment]
Fix link: http://jsbin.com/gubuzezayi/2/edit?html,css,output.

**Comment by mdo** [comment]
I recall trying this, and bailing on it, at some point.

**Comment by cvrebert** [comment]
Fixed by #15697.
