### ISSUE TITLE
Readonly input should not have a not-allowed cursor

### ISSUE THREAD

**Issue by andre-d** [twbs/bootstrap#15683]
I am sure this has been brought up before, but is there a design reason why read-only fields have a not-allowed cursor?  Semantically the "not-allowed" cursor often indicates "stay away" or "do not touch".  However, read only input fields are often intended for interaction: selection, copy, etc.  Although the "not-allowed" cursor makes sense for a disabled state input, I do not feel it is proper for a readonly field.

For example: Github is using a readonly field for the "clone url" box, is this sort of usage discouraged in bootstrap?

**Comment by cvrebert** [comment]
This was fixed by #15703.
