### ISSUE TITLE
LESS files, jspm, and package.json

### ISSUE THREAD

**Issue by nitrog7** [twbs/bootstrap#15685]
When installing from npm (using jspm) the LESS files do not seem to be including like they are in the bower.json. Can the LESS files be added to the package.json as well? Thanks!

**Comment by cvrebert** [comment]
Added where? There's no official field for them, and the unofficial `less` field is already there: https://github.com/twbs/bootstrap/blob/50a3e579ae9fce0fb285cc5b21c76ce76f085022/package.json#L20
I can't find any docs on using Less/Sass with jspm. Are you sure it's possible? Pointers to any relevant docs/discussions would be appreciated.

**Comment by cvrebert** [comment]
Closing for now due to lack of response.

**Comment by nitrog7** [comment]
Yes, close it. Was trying to identify where the problem was but it looks like it is in NPM. Thanks!
