### ISSUE TITLE
[v2.3.*] Fix infinite focus loop in modal

### ISSUE THREAD

**Issue by petrgrishin** [twbs/bootstrap#15690]
Fix infinite focus loop in modal https://github.com/petrgrishin/bootstrap/commits/v2.3.3

Can you create a branch for support v2.3.*?

**Comment by DsXack** [comment]
:+1:

**Comment by elfelrandcor** [comment]
:+1:

**Comment by cvrebert** [comment]
Nope, sorry. We stopped supporting v2.x.x after v3.0.0 was released, which was a long while ago.
