### ISSUE TITLE
Add .list-group-condensed

### ISSUE THREAD

**Issue by bradlis7** [twbs/bootstrap#15692]
Tables have a condensed version, it would also be nice for list-groups, as they have a similar appearance, and flow better for areas, such as sidebars, where you may not want to take up a lot of space.

    .list-group-condensed .list-group-item {
        padding: @table-condensed-cell-padding;
    }

**Comment by mdo** [comment]
Thanks, but I don't think we need this right now.

**Comment by rage-shadowman** [comment]
What is the workaround then?

**Comment by akaustav** [comment]
I am also looking for an answer to the "officially supported" workaround.

**Comment by ohfang** [comment]
I need this too!

**Comment by mdo** [comment]
Change the `padding` as you need. Not really a workaround—either override those values, change the variable and recompile, etc.
