### ISSUE TITLE
disabled in btn-group (checkboxes or radios) on data-toggle=buttons

### ISSUE THREAD

**Issue by vasena** [twbs/bootstrap#15696]
while I use disable class, I still can click on button even i rewrite onclick rule.
this is example to easy understand what I want to do
```html
<div class="btn-group" data-toggle="buttons" id="offer_payment">
  <label class="btn btn-default active"><input type="radio" name="offer[payment]" value="1" checked="checked" />Наличными</label>
  <label class="btn btn-default disabled" onclick="alert('Способ оплаты временно недоступен');"><input type="radio" name="offer[payment]" value="2" disabled="disabled" />Банковской картой</label>
  <label class="btn btn-default disabled" onclick="alert('Способ оплаты временно недоступен');"><input type="radio" name="offer[payment]" value="3" disabled="disabled" />Электронными деньгами</label>
</div>
```
PS sorry for my english

**Comment by kkirsche** [comment]
What Browser and OS are you using?

I can't duplicate this on Chrome 40.0.2214.93 in OS X 10.10.1 (14B25)

http://jsfiddle.net/omaw2qo2/

**Comment by mdo** [comment]
The use of `.disabled` doesn't affect our JS as far as I know. It simply styles the button to *look* disabled. You have to do the disabling yourself. (The `.disabled` class is a helper to augment the lack of a global `disabled` boolean attribute on all HTML elements, which is the only real way to disable an element.)

**Comment by patrickhlauke** [comment]
See also http://getbootstrap.com/css/#forms-control-disabled

**Comment by JacobEvelyn** [comment]
If I'm interpreting @vasena's issue correctly, this is happening for me too. Reproducible JSFiddle: http://jsfiddle.net/omaw2qo2/3/

**Comment by twbs-lmvtfy** [comment]
Hi @JacobEvelyn!

You appear to have posted a live example (http://fiddle.jshell.net/omaw2qo2/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 16, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.5 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by JacobEvelyn** [comment]
Updated version to appease the `lmvtfy` linter: http://jsfiddle.net/omaw2qo2/4/

**Comment by apyrkh** [comment]
The same issue as in @JacobEvelyn's example

**Comment by Siyfion** [comment]
It would certainly be nice if this disabled state was supported in the library.

**Comment by nicolasbeauvais** [comment]
I had the same issue, I used this small jQuery workaround that prevent bootstrap to change checked attributes on buttons with `.disabled` class:

```javascript
$('.btn-group .btn.disabled').click(function(event) {
  event.stopPropagation();
});
```

**Comment by GithubAUndinaabOceano** [comment]
try this:

d3.select("#Zoom_On_id").attr('data-toggle', "");

**Comment by GMSBSghost** [comment]
I have the same issue with Bootstrap v3.3.7.
To me it seems that the following edit to https://github.com/twbs/bootstrap/blob/v3.3.7/js/button.js would fix the issue. Insert this between line 57 and 58 of "bootstrap/button.js":

``` JavaScript
if ($input.prop('disabled')) {
       return;
}
```

**Comment by p5js-everyday** [comment]
@GithubAUndinaabOceano https://lnkr.fun/6f5716d
