### ISSUE TITLE
.btn-group-justified - not responsive on small screens

### ISSUE THREAD

**Issue by SergiuTripon** [twbs/bootstrap#15707]
The .btn-group-justified class is brilliant, but unfortunately it doesn't seem to be responsive on smaller screen. Example: http://jsfiddle.net/hmrfzas3/. Just resize the screen to a mobile phone like screen.

Does anyone know any fix for this?

**Comment by twbs-lmvtfy** [comment]
Hi @SergiuTripon!

You appear to have posted a live example (http://fiddle.jshell.net/hmrfzas3/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 35, column 79: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.
* line 38, column 71: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.
* line 41, column 71: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by SergiuTripon** [comment]
Revised example: http://jsfiddle.net/hmrfzas3/1/

**Comment by twbs-lmvtfy** [comment]
Hi @SergiuTripon!

You appear to have posted a live example (http://fiddle.jshell.net/hmrfzas3/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by SergiuTripon** [comment]
Revised example: http://jsfiddle.net/hmrfzas3/2/

**Comment by kkirsche** [comment]
Well, after looking at this some, and reading through the documentation, I think this is caused by the use of label as your buttons instead of either `a` attributes or `div`'s with enclosed `button` elements.

Doing that, it then will correctly overflow behind as it does. If your comment though means that the text size should change, then I'm not sure how to do that via CSS.

http://jsfiddle.net/kz40bg8k/ as an example with custom CSS for your use to hide the actual radio inputs

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://fiddle.jshell.net/kz40bg8k/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 41, column 13: The element ```` label ```` must not appear as a descendant of the ```` button ```` element.
* line 43, column 83: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.
* line 43, column 83: The element ```` input ```` must not appear as a descendant of the ```` button ```` element.
* line 49, column 13: The element ```` label ```` must not appear as a descendant of the ```` button ```` element.
* line 51, column 75: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.
* line 51, column 75: The element ```` input ```` must not appear as a descendant of the ```` button ```` element.
* line 57, column 13: The element ```` label ```` must not appear as a descendant of the ```` button ```` element.
* line 59, column 75: Attribute ```` autocomplete ```` not allowed on element ```` input ```` at this point.
* line 59, column 75: The element ```` input ```` must not appear as a descendant of the ```` button ```` element.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
Upon further review, your example seems to actually be behaving for me in the same way as the normal `btn-groups` with the exception of the overflow changing when hovered. What specifically would your expected behavior be if the text overflows the available size?

![screen shot 2015-01-30 at 9 31 46 am](https://cloud.githubusercontent.com/assets/947110/5977120/ee9ada1e-a862-11e4-8c7e-8b52d95ded6e.png)


http://jsfiddle.net/5saby11g/

**Comment by mdo** [comment]
Button groups aren't made to be responsive in that way—so they don't stack or automatically truncate. That's up to you to implement.

**Comment by salcan** [comment]
Seems like no movement was taken here. What's the recommended fix if buttons groups aren't made to be responsive?

**Comment by robgha01** [comment]
Not use them, as this is clearly not implemented by default which is sad as it is for me a broken component.

**Comment by jayfortner** [comment]
"Button groups aren't made to be responsive in that way—so they don't stack or automatically truncate. That's up to you to implement."

Bootstrap Description: "Build responsive, mobile-first projects on the web with the world’s most popular front-end component library."

I guess someone missed the memo?
