### ISSUE TITLE
Small issue with overlapping

### ISSUE THREAD

**Issue by jamespavett** [twbs/bootstrap#15704]
I'm helping a friend with a website and need some advice. We asked here before, and were told to update all the necessary jQuery files on the server, done that, but still broken.

Website: 3six-d.co.uk

If you go to the portfolio, you will see all the pictures are out of line, not the rows, but the columns. I'm using this to set the spacing:

<div class="col-md-4">
  <a class="fancybox-test" data-fancybox-group="thumb" href="images/portfolio-03.png"><img src="images/portfolio-preview-03.png" alt="" /></a>
</div>
Just to be clear I have upgraded from Bootstrap 2 to 3. But I have followed the instructions and upgraded all the syntax's. (I hope anyway) But still no luck, they just won't line up as they used to (Gaps between the columns and pictures of equal space).

I have done abit of research on this myself, and all that I can find is that they must all by in the container div, which they are.

This is driving me crazy, so I would love some help! I know there is fancybox involved, but I'm certain the issue is regarding Bootstrap, as the issue did not occue until the upgrade (Though now not even reverting fixes it).

Thanks

**Comment by kkirsche** [comment]
Image is broken.

And on the gallery page for me they are all in a straight line across the row.

**Comment by kkirsche** [comment]
Updating to OS X 10.10.2 fixed the little vertical issue to:

![screen shot 2015-01-29 at 5 35 35 pm](https://cloud.githubusercontent.com/assets/947110/5967657/4fd868cc-a7dd-11e4-8d61-9aa792896eb5.png)

**Comment by jamespavett** [comment]
Haha thanks! But I think I figured it out by myself :P and you just happened to update at the same time, thanks anyway!

**Comment by cvrebert** [comment]
In the future, please direct these sorts of general user help questions to StackOverflow (or similar) instead of the issue tracker. Thanks!
