### ISSUE TITLE
navbar-fixed-top issue between 3.2.0 and 3.3.x

### ISSUE THREAD

**Issue by whardier** [twbs/bootstrap#15702]
Tested in Chrome Stable.

I'm able to induce the navbar under the class navbar-fixed-top to move and regain it's anchor to the pixel top 0 when CSS transformations are queued/active by scrolling up and down rapidly using the scroll wheel.  This is a changed behavior in 3.3.0.  See below.  Simply scroll around rapidly using the scroll wheel in Linux or Windows to see the effect.  In 3.2.0 the navbar stays quite happily in place.  It's almost like Affix is being used now for navbar-fixed-top.

http://jsbin.com/belilikimo/2 (3.2.0)

http://jsbin.com/belilikimo/3 (3.3.2 and 3.3.0)

**Comment by twbs-lmvtfy** [comment]
Hi @whardier!

You appear to have posted a live example (http://jsbin.com/belilikimo/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 209, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by whardier** [comment]
...

**Comment by kkirsche** [comment]
I'm not able to replicate this in Chrome on Mac OS X 10.10.1 unless I'm misunderstanding your instructions.

**Comment by whardier** [comment]
See: http://youtu.be/Edo375wveso .. only when the scroll wheel is used is there a problem.  Been trying to dig in to see what the difference is but can't make heads or tails of what would be causing this issue.

**Comment by kkirsche** [comment]
Hm, that's interesting. I can see what you mean in the video. Thanks for sharing that.

**Comment by cvrebert** [comment]
Does removing your
```css
html {
  overflow: -moz-scrollbars-vertical; 
  overflow-y: scroll;
}
```
have any effect on the issue?

**Comment by whardier** [comment]
No

**Comment by whardier** [comment]
Removing the carousel resolves this issue however. :)  I haven't tried putting mundane content in place yet to see if that brings it back up

**Comment by whardier** [comment]
Oops. accidentally closed.

**Comment by belowservices** [comment]
I think this is also the problem on iOS. On 3.3.1, when using affix for a navbar to the top, after it attaches it flickers. When I connect it to Safari, the 'affix.bs.affix' and 'affix-top.bs.affix', events occur continuously, making the affixed item appear to flicker, while still scrolling. After it stops scrolling, the events stop and it is affixed properly. On 3.2.0 it works as intended and the exact same code works properly.

**Comment by mdo** [comment]
On iOS, the problem is Safari doesn't calculate the position of a fixed element until after the scrolling is done. That includes the momentum scrolling effect. Given this is unique to a specific hardware problem, I'm assuming this is a bug with Chrome or Windows or both. Nothing is showing up as something glaring to fix here after leaning into it a bit.
