### ISSUE TITLE
tooltip/popover destroy docs don't explain the delegation case

### ISSUE THREAD

**Issue by technotronic12** [twbs/bootstrap#15701]
Destroy does not work. Disable does.
You can look at this fiddle: http://jsfiddle.net/ecw3rk1s/3/

**Comment by cvrebert** [comment]
Since you're using delegation (i.e. the `selector` option), I believe there's only one actual tooltip instance (on the `body`). Thus, trying to destroy nonexistent tooltip instances on the trigger elements themselves has no effect.
Compare the non-delegated version: http://jsfiddle.net/zsb9h3g5/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/zsb9h3g5/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 45, column 104: Element ```` link ```` is missing required attribute ```` property ````.
* line 46, column 6: An ```` body ```` start tag seen but an element of the same type was already open.
* line 54, column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by technotronic12** [comment]
Thank you for your answer. I learned something new!

**Comment by kkirsche** [comment]
To document this, the documents currently say, "Hides and destroys an element's tooltip." followed by the code example `$('#element').tooltip('destroy')`. Do you believe it would be clear to instead have:

### .tooltip('destroy')
Hides and destroys an element's tooltip. `Destroy` should not be used when delegating to a target element using the [`selector` option](http://getbootstrap.com/javascript/#popovers-options). When calling `destroy`, it will attempt to remove the nonexistent tooltip instance from the trigger element.
```javascript
$('#element').tooltip('destroy')
```

Thoughts?

**Comment by cvrebert** [comment]
How about:
> Hides and destroys an element's tooltip. Tooltips that use delegation (which are created using [the `selector` option](http://getbootstrap.com/javascript/#tooltips-options)) cannot be individually destroyed on descendant trigger elements.

?

**Comment by kkirsche** [comment]
I think that works well.

**Comment by cvrebert** [comment]
Fixed by #15742.
