### ISSUE TITLE
Boostrap Responsive affix

### ISSUE THREAD

**Issue by michal222** [twbs/bootstrap#15711]
I need to sidebar box affix fix top, but problem with responsive. Thanks for advice or example.

<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
<div data-spy="affix" data-offset-top="60" data-offset-bottom="200">
<div class="sidebar">
 
</div>	       
</div>
<div class="sidebar-content">
 
</div>	 

</div>

**Comment by cvrebert** [comment]
Please direct how-to questions to StackOverflow. Thanks.
