### ISSUE TITLE
Add a variable for .form-group's margin-bottom

### ISSUE THREAD

**Issue by mryellow** [twbs/bootstrap#15719]
#3737

> @mdo The forms can be customized easily enough to reduce this when folks need it.

This statement is inaccurate, ~~form control~~ `.form-group` margin is not exposed in the LESS.

```
.form-group {
     margin-bottom: 15px
}
```

**Comment by cvrebert** [comment]
@mryellow The CSS you refer to no longer exists in Bootstrap v3. We don't set `margin-bottom: 15px` on `.form-control` anywhere.

**Comment by mryellow** [comment]
It's in the current master and 3.3.2

https://github.com/twbs/bootstrap/blob/85a6595a716fa6549383356e75c2091bfdfee585/less/forms.less#L200

https://github.com/twbs/bootstrap/blob/v3.3.2/less/forms.less#L200

**Comment by cvrebert** [comment]
Your original post says `.form-control`, not `.form-group`.

**Comment by mryellow** [comment]
Ahh too right, thanks. I had mistakenly worked around it by overloading `form-control` instead of `form-group`.

**Comment by kkirsche** [comment]
@cvrebert I can easily add a variable for this to variables [LESS file](https://github.com/twbs/bootstrap/blob/master/less/variables.less#L174-L219), will it also require being exposed in the customizer or is it automatically loaded?

**Comment by cvrebert** [comment]
@kkirsche That's done automatically via [the customizer-related Jade Grunt tasks](https://github.com/twbs/bootstrap/blob/33d8fde67cf9db663cc85b3990944109c5dcbe47/Gruntfile.js#L313).

**Comment by cvrebert** [comment]
Fixed by #15728.
