### ISSUE TITLE
 Liquid Exception: cannot load such file -- rouge in components.html

### ISSUE THREAD

**Issue by JetQin** [twbs/bootstrap#15715]
Warning: Command failed:   Liquid Exception: cannot load such file -- rouge in components.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rouge (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/tags/highlight.rb:73:in `render_rouge'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/tags/highlight.rb:43:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.rb:106:in `block in render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.rb:93:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.rb:93:in `render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.rb:82:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/template.rb:124:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/template.rb:132:in `render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/tags/include.rb:111:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.5.5/lib/liquid/context.rb:105:in `stack'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/tags/include.rb:109:in `render'

**Comment by JetQin** [comment]
can anyone meet this problem, i can add  <b>highlighter:      false</b> in _config.yml compile it successfully, but i want the othe way ,did any one have any idea?

**Comment by patrickhlauke** [comment]
``gem install rouge`` ?

**Comment by JetQin** [comment]
<pre>
pc:bootstrap jet$ sudo gem install rouge
Successfully installed rouge-1.7.7
Parsing documentation for rouge-1.7.7
Done installing documentation for rouge after 2 seconds
1 gem installed
pc:bootstrap jet$ 
pc:bootstrap jet$ jekyll serve
Configuration file: /Users/jet/nodejs/bootblog/bootstrap/_config.yml
            Source: docs
       Destination: _gh_pages
      Generating... 
  Liquid Exception: cannot load such file -- rouge in components.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rouge (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
</pre>

here is my command window hint,i already installed rouge, but it also has mistake,did i install wrong version? is it the version unmatch?

**Comment by cvrebert** [comment]
`ls -l $(which gem) $(which jekyll) $(which rougify)`

**Comment by JetQin** [comment]
thanks @cvrebert , 
$ ls -l $(which gem) $(which jekyll) $(which rougify)
-r-xr-xr-x  1 root  wheel  596  9 10 05:45 /usr/bin/gem
-rwxr-xr-x  1 root  wheel  508  2  2 11:29 /usr/bin/jekyll
-rwxr-xr-x  1 root  wheel  506  2  2 11:32 /usr/bin/rougify
$ jekyll serve
Configuration file:/bootstrap/_config.yml
            Source: docs
       Destination: _gh_pages
      Generating... 
                    done.
 Auto-regeneration: enabled for 'docs'
Configuration file: /bootstrap/_config.yml
    Server address: http://0.0.0.0:9001/
  Server running... press ctrl-c to stop. 
it works,thank you very much

**Comment by darielnoel** [comment]
+!
