### ISSUE TITLE
Add example of how to use grid system within a modal

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15712]
X-Ref: http://stackoverflow.com/questions/28243521/use-grid-row-in-modal

**Comment by kkirsche** [comment]
Is it best practice to nest a container or what is actually the recommended way? I can put together some documentation though if I know what the actual "recommended" way to work with the grid within a modal is.

**Comment by cvrebert** [comment]
CC: Answerman @mdo

**Comment by mdo** [comment]
Fluid containers can be nested anywhere basically—their `width` is in percentages, not pixels.
