### ISSUE TITLE
autocomplete weird scroll issue

### ISSUE THREAD

**Issue by cs1193** [twbs/bootstrap#15722]
I am having a jquery ui autocomplete inside bootstrap modal. 

The issue I am facing is:

 - the scroll down arrow in ui auto suggestion list does not properly scroll the content in IE.
 - When down arrow is pressed, instead of scrolling down it focusses on first element always, whereas in chrome it works fine

- [jsfiddle code][1]

This happens only when jquery ui autocomplete feature is inside bootstrap modal. Outside, it works fine. 

Any help to fix this issue would be of great help.

  [1]: http://jsfiddle.net/datachand/53Lryjc3/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cs1193!

You appear to have posted a live example (http://fiddle.jshell.net/91cvetb1/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 136, column 1: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-header` must be a child of `.modal-content`
* line 136, column 1: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-body` must be a child of `.modal-content`
* line 136, column 1: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-footer` must be a child of `.modal-content`
* line 148, column 21: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 149, column 21: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 22, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 2.3.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
I would recommend asking about this in [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap) as Bootstrap can't help you with issues involving third-party libraries such as jQuery UI.

**Comment by cvrebert** [comment]
What @kkirsche said.
