### ISSUE TITLE
Animations are choppy on mobile browsers

### ISSUE THREAD

**Issue by addremove** [twbs/bootstrap#15723]
Bootstrap animations on mobile browsers lack fluid motion. E.g. the accordion demo [here](http://getbootstrap.com/javascript/) is jerky (or choppy). I've tried Firefox & Chrome on Nexus 5, Safari & Chrome on iPad Air 2. Both devices have good specs when it comes to MHz/RAM. 

I'm wondering if this is a limitation of mobile devices. Is there some small tweak that can alleviate it ?

Some related discussion:
- [Proper way to optimize CSS 3 animations for iOS/Mobile Safari?](http://stackoverflow.com/q/6481894/)
- [Why is jQuery UI accordion open/close animation so choppy?](http://stackoverflow.com/q/15501060/)
- [jQuery Jerky slideUp and slideDown With Twitter Bootstrap Well](http://blog.markstarkman.com/blog/2013/07/25/jquery-jerky-slideup-and-slidedown-with-twitter-bootstrap-well/)
- [Two things that cause jQuery jerky animations
](http://jaredheinrichs.com/two-things-that-cause-jquery-jerky-animations.html)

**Comment by cvrebert** [comment]
In some cases, such as the Carousel, we use (typically hardware-accelerated) 3D transforms when supported by the browser, but it's not without some drawbacks (e.g. #15506).

We also briefly tried applying the translateZ hack to force hardware acceleration, but we encountered too many browser bugs and usability issues, and had to revert it; see #13649.

**Comment by mdo** [comment]
Yeah, there's not much else we can do other than what @cvrebert mentioned.

**Comment by addremove** [comment]
Perhaps an option to disable animations on mobile (Any chance of revisiting [#5764](https://github.com/twbs/bootstrap/issues/5764)?

**Comment by cvrebert** [comment]
@mdo ^^^ ?

**Comment by mdo** [comment]
I don't think we'd provide that globally, at least in v3. Perhaps in v4, but it's not at the top of the list right now there either.
