### ISSUE TITLE
Popovers parse escaped HTML code (3.3.2)

### ISSUE THREAD

**Issue by IlanF** [twbs/bootstrap#15733]
In one of my projects I had to show a pre-formatted code snippet in a popover. I found that any escaped HTML code (with `htmlspecialchars()` in PHP for example) in the popover content is parsed if you have the html attribute enabled.

Not sure if it is needed in this case, but I tested it with the latest Chrome, Firefox and IE on Windows 7 machine.

Steps to reproduce:
1. add button to page with popover data attributes
2. in content attribute add escaped HTML: `This &lt;strong&gt;should not be bold&lt;/strong&gt`
Expected results: popover should display the HTML tags

[Reduced case test](http://codepen.io/ilanf/full/pvWdoR/)

**Comment by twbs-lmvtfy** [comment]
Hi @IlanF!

You appear to have posted a live example (http://codepen.io/ilanf/pen/pvWdoR.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 10, column 265: The string following ```` & ```` was interpreted as a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
This, as far as I can see at least, is being caused by https://github.com/twbs/bootstrap/blob/master/js/popover.js#L50

Still looking to identify what the fix is

**Comment by kkirsche** [comment]
OK, so after looking into this more this is what I've "figured" out:

The `getContent` method picks up your input and translates it to:
```html
<pre>This <strong>should not be bold</strong></pre><strong>And this too not supposed to be bold</strong>
```

Then when the HTML is appended, it will fire up the HTML parser. My linter throws complaints that `<` `>` and `/` are not allowed within the append, but I admit I'm not extremely familiar with this.

If the append method receives the string correctly, this isn't an issue, it's just getting the string as formatted HTML

**Comment by kkirsche** [comment]
I'm not sure of an easy way to fix this because this string parsing is occurring before Bootstrap even comes into play. You can see in the image below that the browser already parsed the content into HTML. I think it would be possible to change the content of the string we receive so that all content within a `<pre></pre>` tag are escaped and can be displayed, but other than that I'm not sure there is much that can be done.

Thoughts from the Bootstrap admins/collaborators? 

![screen shot 2015-02-03 at 9 52 06 am](https://cloud.githubusercontent.com/assets/947110/6022384/5ad90c1c-ab8a-11e4-864c-ee7b45b57674.png)

**Comment by cvrebert** [comment]
This isn't a bug, it's just how escaping works when writing a string of HTML within HTML. It's been brought up before. The need to doubly escape literal metacharacters is definitely ugly, but so is putting HTML in an attribute value in the first place. To avoid this, one option is to pass the `content` option via JavaScript.
