### ISSUE TITLE
Tooltip on disabled elements and btn-group

### ISSUE THREAD

**Issue by Adysone** [twbs/bootstrap#15737]
Hi, I saw so many issues with that, but the only way to do it is to wrap the disabled element with a ``<div>`` (or a ``<span>``, it can work).

BUT!

I would like to put it on a btn wrapped by a btn-group and wrap my disabled element by a span breaks the CSS...

Within a ``<div>``
```html
<div class="btn-group">
	<a href="#href" class="btn btn-default" data-toggle="tooltip" title="The tooltip title">
		<i class="fa fa-edit"></i>
	</a>
	<div data-toggle="tooltip" title="The tooltip title">
		<a href="#href_disabled" class="btn btn-default disabled">
			<i class="fa fa-remove"></i>
		</a>
	</div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/6309463/6022620/6ec089c4-abbe-11e4-8cc3-d2ef2615c6c8.png)

Within a ``<span>``
```html
<div class="btn-group">
	<a href="#href" class="btn btn-default" data-toggle="tooltip" title="The tooltip title">
		<i class="fa fa-edit"></i>
	</a>
	<span data-toggle="tooltip" title="The tooltip title">
		<a href="#href_disabled" class="btn btn-default disabled">
			<i class="fa fa-remove"></i>
		</a>
	</span>
</div>
```
![image](https://cloud.githubusercontent.com/assets/6309463/6022636/880b5c1a-abbe-11e4-9b2d-0078fda07b7d.png)

Without a wrapper, but tooltip doesn't show up
```html
<a href="##" class="btn btn-default disabled" data-toggle="tooltip" title="Impossible de supprimer cette variété car elle contient des données"><i class="fa fa-remove"></i></a>
```
![image](https://cloud.githubusercontent.com/assets/6309463/6022636/880b5c1a-abbe-11e4-9b2d-0078fda07b7d.png)

**Comment by kkirsche** [comment]
http://jsfiddle.net/5jexwyj2/

Working on the PR next

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://fiddle.jshell.net/5jexwyj2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work
* line 53, column 5: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to 'body'. Found tooltips/popovers that might lack this setting.
* line 56, column 5: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to 'body'. Found tooltips/popovers that might lack this setting.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
We won't be providing any overrides in Bootstrap for this kind of thing, at least for v3.x. It's a bit too much to account for—`<div>`s, `<span>`s, etc would all need it. For now, you'll need to provide the CSS overrides for this.
