### ISSUE TITLE
Desktop becomes unresponsive over remote desktop when showing bootstrap animated progress bar

### ISSUE THREAD

**Issue by jalbertSyncroTech** [twbs/bootstrap#15743]
This seems to be a Chrome related issue, but I'm cross reporting the bug here in case Bootstrap would like to provide a work around.
https://code.google.com/p/chromium/issues/detail?id=454916

UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

Steps to reproduce the problem:
1. Connect to another PC using the windows remote desktop connect client
2. In Chrome go to http://getbootstrap.com/components/#progress-animated and press "Toggle animation"
3. Try to interact with the page (eg. select some text)

What is the expected behavior?
The interactions should be as responsive as when the progress bar isn't animated.

What went wrong?
With the progress bar animations turned on, all page interactions take several seconds to register, and the performance gets worse as time goes on.

Did this work before? No 

Chrome version: 40.0.2214.94  Channel: stable
OS Version: 6.1 (Windows 7, Windows Server 2008 R2)
Flash Version: Shockwave Flash 16.0 r0

This bug seems to be related to this issue, but the option to deactivate gpu compositing is no longer in about:flags
https://productforums.google.com/forum/#!topic/chrome/PGDcZguzqG0

The command line options --disable-gpu and --disable-gpu-compositing still work, but that's only a temporary solution.

Firefox and IE don't seem to be affected.

**Comment by cvrebert** [comment]
The only workaround we might offer here is some option to disable all Bootstrap animations; you can follow https://github.com/twbs/bootstrap/issues/15723#issuecomment-72590179 and/or #5764 if you'd be interested in such a feature.

**Comment by jalbertSyncroTech** [comment]
Thanks, that doesn't help in my case (I'd typically only use remote desktop when debugging a field issue, but that's the precisely when I'd need to disable the animations), but I respect the position you're taking.
