### ISSUE TITLE
woff2 in v3.3.2

### ISSUE THREAD

**Issue by skinnybrit51** [twbs/bootstrap#15758]
After downloading version 3.3.2 of bootstrap I noticed that if you using latest chrome or ff browser woff2 fonts are used.  This is causing a problem for our application stack.  The s3 bucket where our deployed client code lives is pushed from a travis build.  The travis build is unable to determine the MIME type for woff2.  [Ruby MIME Types](https://raw.githubusercontent.com/halostatue/mime-types/master/data/mime-types.json)

Is there any real need to include `woff2` as at the moment it is still in [draft](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face)?

**Comment by cvrebert** [comment]
Sounds more like a bug in your MIME type library, no?

**Comment by skinnybrit51** [comment]
I partially agree with that.  My counter argument would be that other library's might not want to support draft functionality.

**Comment by kkirsche** [comment]
The correct mime type for WOFF 2.0 files is hard to determine but from what I've seen:

Google uses `font/woff2`

W3C recommends `application/font-woff2`

NGINX: WOFF2 mime type
```
types {
    application/font-woff2  woff2;
}
```

APACHE: WOFF2 mime type
```
AddType  application/font-woff2  .woff2
```

**Comment by mansam** [comment]
The correct mime type for WOFF 2.0 is hard to determine because no proposal has been accepted by IANA yet as far as I know.

**Comment by cvrebert** [comment]
@mdo Any thoughts here?

**Comment by cvrebert** [comment]
> @kkirsche Google uses `font/woff2`

Where? Example?

**Comment by coliff** [comment]
@cvrebert Info re: 'Google uses font/woff2' and other interesting stuff on this Gist here:
https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

**Comment by twbs-lmvtfy** [comment]
Hi @coliff!

You appear to have posted a live example (https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 40, column 64: Non-space characters found without seeing a doctype first. Expected ```` <!DOCTYPE html> ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Sadly, that Gist doesn't actually give an example of where Google uses it. Given when that Gist was created, it's entirely possible that that portion of it is outdated.

**Comment by coliff** [comment]
Ok, go to http://www.google.com/fonts/ and view the Network Inspector in Google Chrome and you'll see type: font/woff2. Google use that type for all Google-hosted fonts.

I use WOFF2 fonts on my IIS 7 server but the type shows there as: application/font-woff2

**Comment by cvrebert** [comment]
Hmm, indeed. Let's see if they'll fix that: https://twitter.com/cvrebert/status/570155277648924672

**Comment by kkirsche** [comment]
Thanks for linking to that @coliff as that's where I was going

**Comment by cvrebert** [comment]
All my research says to use `application/font-woff2` and that that's going to be the final registered MIME type:
* http://dev.w3.org/webfonts/WOFF2/spec/#IMT
* http://lists.w3.org/Archives/Public/public-webfonts-wg/2014Jun/0025.html
* https://code.google.com/p/chromium/issues/detail?id=391289
* https://github.com/h5bp/server-configs-apache/issues/32

`application/font-woff2` works fine in Chrome (indeed, "[Chrome itself doesn't require any particular mimetype.](https://code.google.com/p/chromium/issues/detail?id=248712#c10)"), and [Blink is currently the only rendering engine](http://caniuse.com/#feat=woff2) where WOFF2 is supported without having to toggle any feature flags.

---

So IMHO, there's no serious doubt about the *de facto* or *de jure* correct MIME type here. And Bootstrap generally tends not to care about such server-side considerations anyway.

So I think that just leaves the matter of "Should we include support for a font format whose standard isn't yet finalized"? I'm personally in favor of simply deferring to our upstream (Glyphicons) and trusting their judgment; they've apparently chosen to include WOFF2.
Just to give some other data points: [Font Awesome](https://github.com/FortAwesome/Font-Awesome/blob/c79474df99e572e230a7e16f06a6a4605c00b18f/css/font-awesome.css#L10), Google Fonts, and [MediaWiki](http://www.gossamer-threads.com/lists/wiki/mediawiki-cvs/530314) use/support WOFF2.

---

CC: @twbs/team so we can make a final up-or-down decision here.

**Comment by mdo** [comment]
I'm fine leaving the WOFF2 in there if it's not causing any harm and makes us a bit more future-friendly.

**Comment by XhmikosR** [comment]
It is still a little bit early for woff2 but being that we just follow upstream, I'm OK with including it too. MIME types isn't something we need to care IMO.

**Comment by cvrebert** [comment]
Closing this then.
