### ISSUE TITLE
Modal windows don't resize correctly between 1100px and 1200px

### ISSUE THREAD

**Issue by webgurus** [twbs/bootstrap#15761]
Hello Bootstrappers,

I recently encountered an issue regarding the modal window. It doesn't auto-resize correctly between 1100 and 1200 pixels resolution. It should be constrained but it jumps to the 1200+ size automatically.

I used Bootstrap 3.3.1.

Any help would be much appreciated, or if anyone else has this same problem please do get in touch so we can get to the root of this issue.

Thanks,
Marton

**Comment by cvrebert** [comment]
* Please upgrade to v3.3.2
* Please post a JS Bin demonstrating the problem.

**Comment by kkirsche** [comment]
I don't have a big enough screen to duplicate it in JSBin but here's a JSBin at each version with an example modal:

http://jsbin.com/jezemekazo/1/edit?html,output — 3.3.2
http://jsbin.com/vexurucezo/1/edit?html,output — 3.3.1

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://jsbin.com/vexurucezo/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 5, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1
* line 6, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://jsbin.com/jezemekazo/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
With those minor Bootlint errors fixed: http://jsbin.com/secizo/2/edit

**Comment by cvrebert** [comment]
@webgurus I'm not seeing any obvious weirdness in OS X Chrome at those viewport sizes. Could you please clarify exactly what incorrect behavior you're observing?
Also, what OS and browser are you using?

**Comment by mdo** [comment]
Modals don't resize automatically—you must specify their size. Without more information, I'm closing.
