### ISSUE TITLE
Idea: implementing .make-*-column-max() mixins for "mobile-only" columns. 

### ISSUE THREAD

**Issue by maniqui** [twbs/bootstrap#15764]
The __goal__: to have the ability of making mobile-first & mobile-only (?) columns, and easily and transparently "undo" them on larger breakpoints.

As you all know, _currently_, Bootstrap lets you make columns starting from the smallest breakpoint you would like those columns to be rendered. For example, if you want a 2-column layout (each column taking up to 50% of the viewport) on every breakpoint, you would use `.make-xs-column(6)`. That mixing would then compile the code necessary for a 2-column layout for the smallest breakpoint and up to the largest one. Similarly, if you want those columns to be rendered only starting from a larger breakpoint, you would then use `.make-sm-column(6)`, `.make-md-column(6)` or `.make-lg-column(6)`, depending at which breakpoint would you like the columns to begin to exist.
Wow, very responsive, such mobile, so first.

But what if you would like to achieve the exact opposite. That is, __to create columns for smaller breakpoints _only___, without the need to "undo" the (applied) styles on larger breakpoints.

__Enter `.make-*-column-max()` and `.make-*-row-max()` mixins.__

The trick is simple, and mobile-first-compatible too: to rely on `@media (max-width: @screen-*-max) { ... }`.

I've done a _really_ quick & dirty test on my local copy, and so far, __it seems to work properly__.
On `/less/mixins/grid.less`, we would then add a few mixins like the followings:

```

// Rows
.make-xs-row-max(@gutter: @grid-gutter-width) {
  @media (max-width: @screen-xs-max) {
    margin-left:  (@gutter / -2);
    margin-right: (@gutter / -2);
    .clearfix; // Note: clearfix used as mixin because we can't extend from within a media query.
  }
}

.make-sm-row-max(@gutter: @grid-gutter-width) {
  @media (max-width: @screen-sm-max) {
    margin-left:  (@gutter / -2);
    margin-right: (@gutter / -2);
    .clearfix; // Note: clearfix used as mixin because we can't extend from within a media query.
  }
}

// ... and so on for larger breakpoints...

// Columns
.make-xs-column-max(@columns; @gutter: @grid-gutter-width) {
  @media (max-width: @grid-float-breakpoint-max) {
    position: relative;
    float: left;
    width: percentage((@columns / @grid-columns));
    min-height: 1px;
    padding-left:  (@gutter / 2);
    padding-right: (@gutter / 2);
  }

.make-sm-column-max(@columns; @gutter: @grid-gutter-width) {
  @media (max-width: @screen-sm-max) {
    position: relative;
    min-height: 1px;
    padding-left:  (@gutter / 2);
    padding-right: (@gutter / 2);  
    float: left;
    width: percentage((@columns / @grid-columns));
  }
}

// ... and so on for large breakpoints...
```

(as you can see, there is some repeated code -properties, mainly- that could probable be abstracted away with some other mixin, but that's another story)

The *main benefit* I see is the ability to easily create rows & columns for narrower viewports and "revert back" to full-width on larger viewports, if needed, while avoiding the need of "undoing" styles (that is, already applied properties).

Thanks for the feedback.

**Comment by kkirsche** [comment]
I'm not sure I fully understand. 

What does this add that would not be possible with doing `.col-xs-6 .col-sm6` To create a two column layout on smaller devices, then add the `.col-md-*` for "normal" size devices?

**Comment by maniqui** [comment]
This would bring mobile-first/mobile-only (read it as: "columns on smaller breakpoints") without the need to "reset" them back on larger breakpoints. 
Benefits? 

* less & leaner code, as you would be able to set columns for small breakpoints, without the need to reset them back (which is usually done, well, adding more code)
* smaller footprint on the compiled CSS (for the same very reason: less code needs to be compiled)

In the end, the goal of having these mixins is to allow a bit more control & versatility over the grid across the different breakpoints, without jumping hoops.
I'll try to prepare a PR during the next week.. 
Keep the feedback coming.:)

**Comment by mdo** [comment]
We won't be adding this to v3 at all—no new features given v4. v4's grid is mostly locked in for the alpha, too, so I don't think we'll be adding anything like this to the core either. Maybe make an add-on instead?

Thanks though!
