### ISSUE TITLE
Don't remove the LESS variables reference if browser don't support customizer

### ISSUE THREAD

**Issue by luishdez** [twbs/bootstrap#15763]
I don't use the customizer but I use LESS variables a lot, and the customizer section has the references for all the variables organized. But if you access with a browser that don't support the customizer, the page removes all the info, so I found my self re-opning in Chrome because I'm on Safari.

I think that references should be kept visible ( disabled ) but visible as a reference.

I'll make a PR if looks ok

**Comment by mdo** [comment]
The `variables.less` file is the only reference that makes sense. Duplicating, or even generating another version of, the customizer's variables wouldn't serve too much of a point. Thanks, but we'll pass for now.

**Comment by luishdez** [comment]
Well I was talking only about don't hide this … 

![dont-hide](https://cloud.githubusercontent.com/assets/38347/6089861/ff3e1e8c-ae69-11e4-8e1f-0716e7402211.png)

Not duplicating anything. Because if you use bootstrap as a bower component you have to go to and find the source to have a reference. Imho is most handy the web. I bet i'm not the only one I use that page as a reference

Anyway thanks :)
