### ISSUE TITLE
npm ERR! 404 'bootstrap-rtl' is not in the npm registry.

### ISSUE THREAD

**Issue by obadasemary** [twbs/bootstrap#15767]
when npm install

obada@obada:~/WebstormProjects/Fahras$ npm install 
npm http GET https://registry.npmjs.org/bootstrap-rtl
npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/angular
npm http GET https://registry.npmjs.org/angular-bootstrap
npm http GET https://registry.npmjs.org/angular-upload
npm http GET https://registry.npmjs.org/angular-route
npm http 304 https://registry.npmjs.org/bootstrap
npm http 304 https://registry.npmjs.org/angular
npm http 304 https://registry.npmjs.org/angular-upload
npm http 304 https://registry.npmjs.org/angular-route
npm http 304 https://registry.npmjs.org/angular-bootstrap
npm http 404 https://registry.npmjs.org/bootstrap-rtl
npm ERR! 404 'bootstrap-rtl' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/obada/WebstormProjects/Fahras
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/obada/WebstormProjects/Fahras/npm-debug.log
npm ERR! not ok code 0

**Comment by patrickhlauke** [comment]
I'm afraid bootstrap-rtl is not an official part of Bootstrap. Please file a bug with (presumably) https://github.com/morteza/bootstrap-rtl ?

**Comment by obadasemary** [comment]
but my project use bootstrap-rtl

what work now
