### ISSUE TITLE
Need Clearer Affix plugin documentation

### ISSUE THREAD

**Issue by impressivewebs** [twbs/bootstrap#15766]
Two things to improve the documentation for Affix:

1. What does this plugin do exactly? I understand there is a detailed description, and a live demo, but that doesn't really summarize it succinctly or clearly. Does the plugin just add classes? Does it track scrolling? I think it would be helpful to just add a brief sentence, explaining what it does, along with the statement about the live demo. The live demo is great, but it doesn't really help much because it's ScrollSpy that's doing a lot of that work, not just Affix. It might also help to state here exactly what ScrollSpy is doing and how Affix works with it.

2. In the detailed description it says: "You must provide the styles for these classes yourself (independent of this plugin) to handle the actual positions."  But then, a couple of lines later, it says "Scrolling past the element you want affixed should trigger the actual affixing. This is where .affix replaces .affix-top and sets position: fixed; (provided by Bootstrap's CSS)".

It took me a few minutes to understand those two statements, The first one seems to be saying that the developer has to add positioning, but then it says "position: fixed" is added by the class. Seemed contradictory at first. So as I understand it, Affix adds "position: fixed", but the developer needs to add the actual numeric offsets. Can you clarify this a little more, maybe specifying that the developer needs to supply the "top" values and whatnot?

Sorry if these are two different issues. I can open another one if necessary.

**Comment by kkirsche** [comment]
What do you all think of the following for the succinct definition:

The affix plugin allows you to easily create a fixed positioned element. The subnavigation on the right is a live demo of the affix plugin.

**Comment by kkirsche** [comment]
For the second part:

You must provide the styles, except for `position: fixed;`, for these classes yourself (independent of this plugin) to handle the actual positions.

**Comment by infacq** [comment]
at least show an example on how the webpage uses the affix plugin. Don't minify the `js` please

**Comment by cvrebert** [comment]
The docs already have a section showing how to use the Affix JS. The JS for the docs itself is minified for performance reasons. Any other concerns should go in a new issue.
