### ISSUE TITLE
Documentation for sticky/absolute footer

### ISSUE THREAD

**Issue by denisz1** [twbs/bootstrap#15760]
There is official documentation for a ["sticky" / "fixed to bottom" footer](http://getbootstrap.com/components/#navbar-fixed-bottom), which always sticks to the bottom of the screen.

But what about a regular/static footer which shows at the bottom as usual, EXCEPT when the content is short, in which case it is sticky? Well, there's an [example here](http://getbootstrap.com/examples/sticky-footer-navbar).

But it's not [included in the official docs](http://getbootstrap.com/components/#navbar). It makes sense to have it there, as it's a far more common footer use case than the sticky one which is already documented.

Would have saved me a ton of time if I found it in the official docs! :)

**Comment by denisz1** [comment]
Ideally, there could also be a class something like `navbar-fixed-bottom`, which contains all the appropriate styling, and you'd just declare that class as you can currently do for `navbar-fixed-bottom`.

**Comment by cvrebert** [comment]
It is referenced in the docs along with the rest of the examples: http://getbootstrap.com/getting-started/#examples-custom
Cross-referencing component-centric examples in the docs for the respective components might be worth considering though.

**Comment by mdo** [comment]
We won't be doing anything more for footers and the like in v3. Anything for the example will be just as they are until v4 ships.
