### ISSUE TITLE
Jumbotron heading color not changing with text-color classes

### ISSUE THREAD

**Issue by moinakbarali** [twbs/bootstrap#15768]
Jumbotron Heading ``h1`` does not pick color of ``text-danger`` because its color is inherit.
 
``<div class="jumbotron">``
          ``<h1 class="text-danger">Coffee ceramic cup</h1>``
          ``<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's.</p>``
          ``<p><a class="btn btn-danger btn-lg" href="#" role="button">but now</a></p>``
     `` </div>``

**Comment by malikfaizanhaider** [comment]
use !important

**Comment by kkirsche** [comment]
@mdo Would you like me to submit a PR for text-* variants on the `h1` in the Jumobotron?

Also JSBin to demonstrate the issue for everyone:
http://jsbin.com/yavuniqexa/1/edit?html,css,output

**Comment by cvrebert** [comment]
We've rejected some stuff like this previously, instead referring folks to the general workaround/solution explained in the "Dealing with specificity" callout on http://getbootstrap.com/css/#helper-classes-colors

**Comment by mdo** [comment]
Yeah, I'm still going to defer to @cvrebert's comment here. Nothing we can do except add more bloat to the project at this point by adding more specific code.
