### ISSUE TITLE
Convert Bootstrap css style into plain html 

### ISSUE THREAD

**Issue by haimeili** [twbs/bootstrap#15776]
Does anybody meet this requirement: I use Bootstrap css to build a html page. And I want to send this html content by email. I can use "$('#myelement').html();" to get its detailed content. But it is without css style. How can I convert Bootstrap css style to plain html, like `<div style="......">` ?

Really appericate your any idea.

**Comment by cvrebert** [comment]
Please direct general HTML/CSS questions to StackOverflow or other such forums. Thanks!

**Comment by haimeili** [comment]
thanks
