### ISSUE TITLE
Remove margin-top and margin-bottom from headers (h1, h2, h...)

### ISSUE THREAD

**Issue by raphaelcuba** [twbs/bootstrap#15775]
Why headers (h1, h2, h...) have margin-top and margin-bottom?
A suggestion is remove this configuration or add this configuration on variables.less.

**Comment by kkirsche** [comment]
What is the argument for why headers should not have margin-top and bottom? 

I would agree with variables as I can see users wanting to customize the margins but I feel having a margin makes sense as headers are designed to be standout elements at the beginning of a section of content, which benefits from having whitespace to break things up.

**Comment by raphaelcuba** [comment]
I agree that make sense a margins, but today is difficult to override this values, because depends on other values without duplicate code.

```
h1, .h1,
h2, .h2,
h3, .h3 {
  margin-top: $line-height-computed;
  margin-bottom: ($line-height-computed / 2);

  small,
  .small {
    font-size: 65%;
  }
}
h4, .h4,
h5, .h5,
h6, .h6 {
  margin-top: ($line-height-computed / 2);
  margin-bottom: ($line-height-computed / 2);

  small,
  .small {
    font-size: 75%;
  }
}
```

A suggestion:
```
// _variables.less
$header-margin-top: 10px;
$header-margin-bottom: 15px;

// _type.less
h1, .h1,
h2, .h2,
h3, .h3 {
  margin-top: $header-margin-top;
  margin-bottom: $header-margin-bottom;

  small,
  .small {
    font-size: 65%;
  }
}
// codes...
```

Is my second project using bootstrap and looking the same issue.
What you think about it?

**Comment by kkirsche** [comment]
Just from previous pull requests I can say pretty confidently that I don't think they would like hard coded pixel values for that. But I think it might be possible to do:

```
// _variables.less
$header-margin-top: $line-height-computed;
$header-margin-bottom: ($line-height-computed / 2);
```

This should still allow them to be overrided in a customizer or with a hardcoded value, but maintains the existing results. If the admins like it I can put in a pull request with the changes

**Comment by mdo** [comment]
We won't—we can't because of versioning—be doing this in v3. v4 will have slightly better margins on headings though—no top margins there.
