### ISSUE TITLE
How to motivate a border-top of an element with class="table"?

### ISSUE THREAD

**Issue by AndersBillLinden** [twbs/bootstrap#15771]
It seems like doksofts ckeditor plugin for bootstrap adds the class "table" to tables.

In the ckeditor css, there is some code that adds a top border to elements of that class:

.table>thead>tr>th,
.table>tbody>tr>th,
.table>tfoot>tr>th,
.table>thead>tr>td,
.table>tbody>tr>td,
.table>tfoot>tr>td
{
	padding: 8px;
	line-height: 1.42857143;
	vertical-align: top;
	border-top: 1px solid #ddd;
}

What is motivating this border-top? Wouldn´t it be easier for sites that wants to have such a top border to _include_ that instead of every other site to _exclude_ it?

Did doksoft do it right when they added the table class to tables?

**Comment by patrickhlauke** [comment]
Firstly, regarding the class of ``.table`` - yes, as per the documentation http://getbootstrap.com/css/#tables tables should be given an explicit class of ``.table`` to be given the bootstrap look and feel.

Secondly: the look and feel of bootstrap includes the use of top border. If you (or any other site) don't like it...don't add the class of ``.table``, or override it. Unless I'm missing your question here...

**Comment by AndersBillLinden** [comment]
Thanks for the quick reply! Seems like I have to add yet another !important css rule to all sites. No worries!

**Comment by AndersBillLinden** [comment]
@patrickhlauke I did not mean to hurt anyones feelings when I asked how to "motivate" something. It is just that I appreciate the core functionality of bootstrap of dividing a page in columns, rearranging columns when the browser width changes without appreciating all of the look-and-feel decisions. It would be great if the css was divided into core and look-and-feel. Thats all. Plus that I was seriously surprised of a top border this day.

**Comment by patrickhlauke** [comment]
sorry, i probably misread the tone of your original question (and i probably hadn't had enough coffee in me this morning).

> It would be great if the css was divided into core and look-and-feel

Ah, now I see what you mean. I think there will be a lot of cases where it's not easy to make a clear split between these two (to many, some of the basic styling parts that define the look itself are considered core as well, as they normalise the appearance of certain structures across browsers, for instance). I'll pass this suggestion on, though :)

**Comment by AndersBillLinden** [comment]
:+1:
