### ISSUE TITLE
Glyphicons missing quotes in SASS in 3.3.2

### ISSUE THREAD

**Issue by Hykalos** [twbs/bootstrap#15780]
Most of the glyphicons are missing the quotes, surrounding the content.
e.g. from asset/stylesheets/bootstrap/_glyphicons.scss line 34-40

// Individual icons
.glyphicon-asterisk               { &:before { content: "\2a"; } }
.glyphicon-plus                   { &:before { content: "\2b"; } }
.glyphicon-euro,
.glyphicon-eur                    { &:before { content: \20ac; } }
.glyphicon-minus                  { &:before { content: \2212; } }
.glyphicon-cloud                  { &:before { content: \2601; } }

Should be:
// Individual icons
.glyphicon-asterisk               { &:before { content: "\2a"; } }
.glyphicon-plus                   { &:before { content: "\2b"; } }
.glyphicon-euro,
.glyphicon-eur                    { &:before { content: "\20ac"; } }
.glyphicon-minus                  { &:before { content: "\2212"; } }
.glyphicon-cloud                  { &:before { content: "\2601"; } }

Every icon after this example has no quotes.

**Comment by sejr** [comment]
This issue is better suited for the [bootstrap-sass](https://github.com/twbs/bootstrap-sass) repository. The [master branch](https://github.com/sejr/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_glyphicons.scss) does not appear to have this issue.

**Comment by Hykalos** [comment]
It might have been fixed since the last release then. The version that is downloadable from the web page (http://getbootstrap.com/getting-started/) has this issue, I just checked.

**Comment by cvrebert** [comment]
Sass-specific bugs should be reported to the Sass project repo (https://github.com/twbs/bootstrap-sass), rather than here.
