### ISSUE TITLE
Custom Module Breakpoint Issue

### ISSUE THREAD

**Issue by jmamuzich** [twbs/bootstrap#15785]
Hello 

I am using the Purity III template, corporate layout with 8 custom modules on the homepage. When in certain mobile views, the last two seem to break in the wrong spot. I have tried the clearfixes and they don't seem to be working. Any help with this is greatly appreciated.

thanks

**Comment by cvrebert** [comment]
This issue tracker is only for bugs in Bootstrap itself.
For general help using Bootstrap, please ask on StackOverflow instead.
For help with third-party templates, please contact the template's vendor.
Thanks!
