### ISSUE TITLE
Modal window hangs when the button is clicked many times

### ISSUE THREAD

**Issue by tsys** [twbs/bootstrap#15781]
Hello!

There is an occasional bug in modal windows. If the user clicks fast and often on the button to open a modal window, it may hang. I attached a picture of it. This modal window cannot be closed.

There isn't any error messages in Chrome Console (see screenshot).

Also the same bug was reproduced with IE10.

Google Chrome version is 40.0.2214.93 m.

![modal_bug_1](https://cloud.githubusercontent.com/assets/10942426/6129055/786a6d44-b14c-11e4-8fa1-ea5572e77e91.PNG)

![modal_bug_2](https://cloud.githubusercontent.com/assets/10942426/6129239/cd2e093e-b14d-11e4-98ef-98c1c8d8710b.PNG)

**Comment by NYPD** [comment]
Strange issue. Same thing happens to me on chrome Version 38.0.2125.101 m on Windows 7 if i spam click the modal open button.

**Comment by kkirsche** [comment]
I wasn't able to on Chrome 40.0.2214.111 on mac OS X 10.10.2

**Comment by cvrebert** [comment]
I can produce a possibly related issue where the page can accumulate multiple `modal-backdrop`s. A backdrop is visible and the modal is visible, but the modal cannot be dismissed via either the backdrop or the close button. Using Chrome 40 on OS X Yosemite.

**Comment by sgoblin** [comment]
Reproduced on Firefox 35.0.1 Lubuntu.
![selection_011](https://cloud.githubusercontent.com/assets/4413176/6141072/5775768e-b155-11e4-82b8-a8ae305f57ce.png)

**Comment by cvrebert** [comment]
Is anyone still able to reproduce this with v3.3.4?

**Comment by sgoblin** [comment]
I was not in Firefox 36.0.1 Lubuntu.

**Comment by hnrch02** [comment]
Closing per https://github.com/twbs/bootstrap/pull/15859#issuecomment-85480711.
