### ISSUE TITLE
Look and feel to have table outer border plus row border only

### ISSUE THREAD

**Issue by stanleyxu2005** [twbs/bootstrap#15789]
Use `<table class="table table-bordered">` will create a fully bordered table. But I want to have a table with outer border and a border between rows. It should not have border between columns. I asked in SO http://stackoverflow.com/questions/28439436/partially-bordered-table-of-bootstrap-3, it seems BS3 does not support that.

**Comment by kkirsche** [comment]
@mdo / @cvrebert should this issue be closed if the PR was closed?
