### ISSUE TITLE
Bootstrap icons in sass file not working !!

### ISSUE THREAD

**Issue by adarshmahe** [twbs/bootstrap#15794]
The issue is beacuse there need to be double colon(" ") or single colon(' ') on each icon code. Currently only first two icons have double colons.  

stylesheets\bootstrap\_glyphicons.scss

**Comment by patrickhlauke** [comment]
duplicate of #15780

**Comment by adarshmahe** [comment]
@patrickhlauke ok thanks :) ...  didn't see that...
