### ISSUE TITLE
Suggestion for conditional loading based on media query

### ISSUE THREAD

**Issue by mewsoft** [twbs/bootstrap#15797]
Since bootstrap is going to power most of the internet websites even very large sites besides twitter using it like stackoverflow, I think this project will get larger and larger with time and must have the ability to extend without worrying about the css/js main file size.

Based on this my suggestion is, can all common css code shared among all screen sizes be collected in a one main bootstrap file say named bootstrap.css, then for each media query has its own file named by its size say bootstrap-xs.css, bootstrap-sm.css etc and only loaded based on the current detected screen size because there will be immediate request for many larger screen sizes and even we asked for one for the 480px and less, for example:

```
<link rel="stylesheet"  media="screen and (max-width: 768px)"   href="bootstrap-xs.css">
```
or 

```
@media screen and (max-width: 768px) {
    @import(bootstrap-xs.css);
}

@media screen and (min-width: 1024px) {
    @import(bootstrap-.md-css);
}

```

I understand this will lead to one more server call but really do not know which of the two use cases will be better and decision should be based on your research.

Please forgive my ignorance and do not be aggressive in your replies as I am a Perl developer not a designer.

**Comment by patrickhlauke** [comment]
Considering that minified bootstrap.min.css is currently only around 23KB, and that browsers (even on mobile, at least last time I looked into this) still load all stylesheets regardless of specific media query size indications (see for instance https://www.igvita.com/2012/06/14/debunking-responsive-css-performance-myths/), this may not not be advantageous

**Comment by kkirsche** [comment]
Great read @patrickhlauke thanks for sharing.

**Comment by lavendertech** [comment]
@mewsoft this idea may still be helpful for some 3-parties who make complicate JavaScript components. For bootstrap, considering it is only 23KB, it may not benefit much.

"Given that an average site today serves 37kB of CSS, which is less than 5% of the 1066kB total, chances are you will find much larger gains elsewhere. Optimizing images, which account for over 60%+ of the size is a good start." - from the nice article @patrickhlauke . For the entire web industry, image/media optimization has a much higher priority.

**Comment by cvrebert** [comment]
This seems like something that would be easy enough to do yourself with a third-party CSS postprocessing tool.
Also, this has the potential to cause CSS specificity problems.

**Comment by mdo** [comment]
We won't be splitting things up across files by media query. I don't believe it buys folks much help in extending things or making it any easier to build on top of Bootstrap. All this ends up being an implementation detail, and one that can be somewhat addressed with a post-processor.
