### ISSUE TITLE
btn-group should have overflow: hidden added to it

### ISSUE THREAD

**Issue by KageJittai** [twbs/bootstrap#15799]
btn-group makes btn children floating, floating elements have 0 height, meaning the parent "btn-group" ends up having 0 height.

By adding overflow: hidden, it does some magic that makes btn-group respect the height of the floating children.

**Comment by zacechola** [comment]
You should include a live demo explaining it, please.

**Comment by KageJittai** [comment]
http://jsfiddle.net/jmuea8r4/

**Comment by twbs-lmvtfy** [comment]
Hi @KageJittai!

You appear to have posted a live example (http://fiddle.jshell.net/jmuea8r4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 41, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 42, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 43, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 56, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 57, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 58, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by KageJittai** [comment]
http://jsfiddle.net/jmuea8r4/1/   Fixed the errors, though they didn't really make a difference >.>

**Comment by lavendertech** [comment]
Just a friendly note: the bottom example in KageJittai's demo is actually for "with overflow hidden", not "without...". His demo uses `<hr />` lines to tell the difference - the color of the lines added by this tag may look very light on some screens like mine and I almost didn't notice them at the beginning.

**Comment by kkirsche** [comment]
https://jsfiddle.net/83t2c88d/ with the verbiage fixed per @lavendertech's note

**Comment by mdo** [comment]
Adding `overflow: hidden` would prevent folks from placing tooltips on those buttons and cut off any `box-shadow`s and `outline`s. There's no need for it since, by default, button groups are `inline-block`. This negates any issues of the `float`s not being cleared out of the box.

If you're going to be changing the `display` to `block`, it seems fair game you'd need to account for any additional changes required to make that work.

See https://jsfiddle.net/83t2c88d/1/.
