### ISSUE TITLE
"cursor: not-allowed;" doesn't appear on disabled buttons.

### ISSUE THREAD

**Issue by toddlevy** [twbs/bootstrap#15806]
Not sure if bug or expected behavior...

Each of the following should have the "not-allowed" cursor on mouseover, but none do...

    <button class="btn btn-default" type="submit" disabled="disabled">Button</button>

    <a href="#" class="btn btn-default" disabled="disabled">Button</a>

Relevant CSS is here...

    .btn.disabled, .btn[disabled], fieldset[disabled] .btn {
      pointer-events: none;
      cursor: not-allowed;
      filter: alpha(opacity=65);
      -webkit-box-shadow: none;
      box-shadow: none;
      opacity: .65;
    }

If you remove the "pointer-events: none;" it works as expected.

Tested on XP in...
Chrome Version 40.0.2214.111 m 
Firefox Version 35.0.1

**Comment by mdo** [comment]
This is expected—there should be no cursor on disabled buttons in browsers that allow `pointer-events`.
