### ISSUE TITLE
Problem in manually hiding modal and main scrollbar not showing after modal closed..

### ISSUE THREAD

**Issue by oroalej** [twbs/bootstrap#15808]
I'm having a problem where when I hide the modal manually and I'm currently scrolled my page down. the main scroll-bar were not showing.

**Comment by kkirsche** [comment]
Does this occur on the docs or could you post a jsbin with the example

**Comment by oroalej** [comment]
[Here](http://jsbin.com/jexenedazo/3/edit)

**Comment by twbs-lmvtfy** [comment]
Hi @oroalej!

You appear to have posted a live example (http://jsbin.com/jexenedazo/3/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 11, column 9: ```` style ```` element between ```` head ```` and ```` body ````.
* line 11, column 9: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
http://jsbin.com/hecuruzaho/1/

Should fix that error

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://jsbin.com/hecuruzaho/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 12, column 7: Element ```` style ```` is missing required attribute ```` scoped ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
After fixing that last trivial validation error: http://jsbin.com/poxugo/3/edit

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/poxugo/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Should validate now: http://jsbin.com/poxugo/4/edit

**Comment by cvrebert** [comment]
You're not calling the method properly.
Instead of `$('#myModal').hide('hide');` it should be `$('#myModal').modal('hide');`

**Comment by oroalej** [comment]
Someone edited my work and changed it to hide('hide') and he also delete his comment here.lol.
