### ISSUE TITLE
Is Bootstrap overusing li's?

### ISSUE THREAD

**Issue by dt1973** [twbs/bootstrap#15816]
Is Bootstrap overusing li's?

- http://css-tricks.com/wrapup-of-navigation-in-lists/
- http://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/

In reality anything that can be considered "a group or a collection of items" can also be considered a list. A list of HTML tags, a list of page sections, a list of articles, a list of paragraphs within those articles.

The examples at http://w3.org/TR/html401/struct/lists.html#h-10.1 clearly shows `li` is meant for typographical bulleted / numbered lists.

Hoping to get some feedback on this so we could put an end to this malpractice.

**Comment by kkirsche** [comment]
I think it's reasonable to use li elements for the navigation thoughts?

**Comment by mdo** [comment]
We're stuck with things as they are in v3 because of versioning. v4 will have much simpler markup.

**Comment by patrickhlauke** [comment]
The pattern of using lists for navigation is well-established, and it offers advantages for users of assistive technologies - for instance, screen readers will announce the total number of list items and the current item ("list with 10 items", "1 of 10", "2 of 10" etc). This provides context to SR users which can be very helpful (something that a sighted user gets at a glance). So no, I believe it is definitely not an overuse of ``<ul>``.
