### ISSUE TITLE
Modal backdrop disappears after a jQuery hide() and show()

### ISSUE THREAD

**Issue by phatdoggi** [twbs/bootstrap#15815]
Using media query detection on 'print', the div with all the modal markup is hidden with jQuery.hide(). When the user leaves the print dialog, the content is then shown with jQuery.show(). The modal is visible and functional, but the tinted backdrop is gone. Browser used: chrome 40.0.2214.111 on Ubuntu 14.10

Modal markup is copied straight from the [example in the docs](http://getbootstrap.com/javascript/#modals-examples), only thing edited was the content text and a button.

Before hiding:
![backdrop](https://cloud.githubusercontent.com/assets/6709262/6204787/0c90fe8a-b50c-11e4-85eb-6a85caec2c2e.png)

After showing:
![no backdrop](https://cloud.githubusercontent.com/assets/6709262/6204789/0f933ad0-b50c-11e4-857c-f771843dc9cd.png)

**Comment by cvrebert** [comment]
Please ask on StackOverflow or other such forums for help with debugging your own custom JavaScript. Thanks.
