### ISSUE TITLE
bootstrap.min.css not updated when it’s generated from a config.json

### ISSUE THREAD

**Issue by Pellitero** [twbs/bootstrap#15818]
Hello developers,
I’m having problems with the generated minified bootstrap.min.css. I have my personal config.json for my web site, when I’ve updated from (http://getbootstrap.com/customize/) and save it again, the bootstrap.css file is updated ok, but the bootstrap.min.css does not. I have try in various occasions but the result it’s the same. On the other hand if I start a new json configuration the bootstrap.min.css file saved its well. What’s the problem? Could anyone help me?
Thanks in advantage……

**Comment by kkirsche** [comment]
What is incorrect with the resulting `bootstrap.min.css`? What version is the `config.json` from?

**Comment by Pellitero** [comment]
Hello and thank for the quick answer,
I’m using Bootstrap v3.3.2, and I load in the bootstrap site my json configuration file created 2 days ego. The problem  is that the new zip generated after make some modifications in http://getbootstrap.com/customize/  have:
1.	The bootstrap.css updated ok with my new changes.
2.	The bootstrap.min.css not updated, with my old .json configuration.

**Comment by cvrebert** [comment]
1. You are loading the config using the file picker at the top of the customizer, correct?
2. Please post your config.json file.
3. Please give examples of some of the changes that you are making that aren't being reflected in the minified CSS.

**Comment by Pellitero** [comment]
I had this problem about 2 weeks ago, but I have made some test during the morning and right now its working fine and the bootstrap.min.css file its updated correctly........thanks for the help

**Comment by Pellitero** [comment]
I had this problem about 2 weeks ago, but I have made some test during the morning and right now its working fine and the bootstrap.min.css file its updated correctly........

**Comment by Pellitero** [comment]
thanks for the help
