### ISSUE TITLE
modal-open class

### ISSUE THREAD

**Issue by moridianmess** [twbs/bootstrap#15817]
When one modal dialog is closed after another modal is opened, the modal-open class is not on the body.

Example: http://jsfiddle.net/f7x2e6tb/2/

I believe the onClose event of modal should do something like the following after hiding the chosen modal dialog:

var noOpenModals = $( 'body' ).find( '.modal:visible' ).length;
if( noOpenModals == 0 ){
  $( 'body' ).removeClass( 'modal-open' );
}else{
  if( !$( 'body' ).hasClass( 'modal-open' ) ) {
    $( 'body' ).addClass( 'modal-open' );
  }
}

**Comment by cvrebert** [comment]
> ## [Overlapping modals not supported](http://getbootstrap.com/javascript/#modals)
> Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.

**Comment by moridianmess** [comment]
That is totally unacceptable. There are 2 separate plugins involved here, I cannot force one to be closed before the other plugin opens it's modal dialog without modifying plugins. It isn't really good practice to modify plugins when considering updating them to their latest versions at a later date. jQuery dialogs support one dialog opening before another closing. The fact that you suggest a hack, doesn't really bode well for developers expectations of your solution. If you google search this issue, there are loads of posts with stupid hacks to fix this. Why is adding 4 lines of extra code to fix the body class issue not an acceptable solution to you guys?

**Comment by patrickhlauke** [comment]
Properly implementing multiple modals (including making them accessible, correctly handling focus hand-off from one to the other, etc) is not simply a matter of naively adding/removing that class. For this reason, rather than rolling out a half-baked implementation, Bootstrap decided not to support multiple concurrent modals.
