### ISSUE TITLE
Suggestion for plugins.getbootstrap.com portal like plugins.jquery.com

### ISSUE THREAD

**Issue by mewsoft** [twbs/bootstrap#15823]
I am suggesting creating a sub domain dedicated for third parties plugins called for example  plugins.getbootstrap.com similar to plugins.jquery.com where developers can have accounts and add plugins and demo pages since github until now does not allow running scripts on  the repositories pages. This will encourage jquery plugins and other developers to port their work to bootstrap and also will make it easy when searching for bootstrap plugins.

**Comment by cvrebert** [comment]
There is [the Resources page of the Expo](http://expo.getbootstrap.com/resources/), but it's fairly barebones and not emphasized/linked-to enough. I agree that a better plugin directory would be wonderful.

**Comment by kkirsche** [comment]
Would an update / upgrade to the Expo be something TWBS would be interested in or would something new / standalone be where the interest would be?

**Comment by patrickhlauke** [comment]
My concern would be maintenance and curation - keeping the list up-to-date, actually deciding which plugin should be included (which would give it some form of "official" endorsement), etc. As much as I'd like such a resource, I think it'd be quite intensive at our end... /cc @mdo

**Comment by kkirsche** [comment]
It's interesting though and I think worth mentioning that [plugins.jquery.com](plugins.jquery.com) is also in read-only mode and that they are recommending people just use NPM, using "jquery-plugin" as the keyword in the `package.json`. Potentially the solution is to simply offer a standardized keyword recommendation for use with services like NPM.

**Comment by mdo** [comment]
I'm for having a keyword recommendation, but that's about it. Adding additional overhead on our part isn't going to go over well (historically it hasn't since this is all very much a side gig for us). The resources page can continue to be updated and more widely linked to (perhaps from our docs and blog?).
