### ISSUE TITLE
nav-tabs-justified usage

### ISSUE THREAD

**Issue by WinnieK** [twbs/bootstrap#15824]
Hi.
Just want to clarify one thing. Navs.less contains styles for .nav-tabs-justified, but i can't find any example on BS website and docs. Is there any specific difference between .nav-justified and .nav-tabs-justified or it's still in the code from previous BS versions?

Thanks

**Comment by kkirsche** [comment]
http://getbootstrap.com/components/#nav-justified

**Comment by patrickhlauke** [comment]
So, in answer to your query, it seems that at some point we did indeed have ``.nav-tabs-justified`` as an actual style, but now it's used mainly as a mix-in internally for less - applying ``.nav-tabs-justified`` doesn't seem to have any discernible effect. /cc @mdo

**Comment by mdo** [comment]
Yeah, just a mixin for now. I forgot at what point that changed exactly.
