### ISSUE TITLE
Fix for one modal closing after another has been opened

### ISSUE THREAD

**Issue by moridianmess** [twbs/bootstrap#15827]
I know you said that you were not looking to support this at this time, but I know a lot of people have posted on stackoverflow regarding this issue. In my scenario I am using modal to hold a progress list of executed ajax with the ability to cancel each one. I am also using modal for "more details" on notifications. The data is gathered via ajax, therefore the processing modal is shown, and this closes once the entire ajax success function is called. The success function, in this case, opens the notification. So, the last issue I raised was regarding the modal-open class, and as patrickhlauke pointed out it is not just the class. This time I have taken the whole hideModal function and worked a test solution to solve this issue:

Modal.prototype.hideModal = function () {
    var that = this;
    this.$element.hide();
    this.backdrop(function () {
	var noOpenModals = $( 'body' ).find( '.modal:visible' ).length;
	if( noOpenModals == 0 ) {
		that.$body.removeClass('modal-open');
		that.resetAdjustments();
		that.resetScrollbar();
		that.$element.trigger('hidden.bs.modal')
	}
    });
  }

I'm not entirely sure if this would cause any other issues as a knock on effect, as I may have overlooked something, but I thought I'd post the fix. That way you can do with it as you fancy and other users can see how to overcome it if they want to.

Thanks.

**Comment by kkirsche** [comment]
The way I would personally attack the problem personally would be to use an accordion or collapsable panel(s) inside the first modal. 

This allows for the progress of multiple functions to be displayed in the main title of each collapsible panel. Using a button for more details, or the completion of one of the functions could then reveal one or multiple panels with details without the concerns related to requiring additional modals.

**Comment by cvrebert** [comment]
Closing per #15817.
