### ISSUE TITLE
initialism class should use text-capitalize()

### ISSUE THREAD

**Issue by gideoncresswell** [twbs/bootstrap#15825]
Currently `.initalism` in **type.less** looks like this -

```
.initialism {
  font-size: 90%;
  text-transform: uppercase;
}
```

but it should take advantage of `.text-capitalize` defined above so it should be

```
.initialism {
  font-size: 90%;
  .text-capitalize();
}
```

in my opinion 😄

**Comment by kkirsche** [comment]
I think you mean `.text-uppercase()` in the second example not Capitalize :+1:

**Comment by gideoncresswell** [comment]
My bad. Thanks.
