### ISSUE TITLE
backdrop on modal resize

### ISSUE THREAD

**Issue by vasena** [twbs/bootstrap#15833]
I load content into modal, so the size of modal changes, but not the size of backdrop, so when I scroll down I see the end of backdrop and can access underlayer. In previous version there were no error

**Comment by kkirsche** [comment]
Seems related to: #15106 and #15418

**Comment by DaSchTour** [comment]
also related to: #15136 and #15314 I guess there are even a lot more related topics to the broken modal backdrop

**Comment by cvrebert** [comment]
Closing as a duplicate of other open issues.
