### ISSUE TITLE
.form-control has display:block which disables caps lock indicator on password fields on webkit browsers

### ISSUE THREAD

**Issue by DannyJJK** [twbs/bootstrap#15832]
I noticed that the caps lock indicator wasn't displaying on bootstrap fields with the .form-control property. After disabling styles one by one I found out it was display:block causing the problem. This is a UX issue as many people enter passwords incorrectly by having caps lock enabled so it's essential to have the indicator there

**Comment by kkirsche** [comment]
I would personally consider that more of a browser bug than a Bootstrap bug. Potentially there would be a way to fix it via `display: inline-block` but I'm not sure

**Comment by kkirsche** [comment]
Yep, not sure of the other repercussions but `display: inline-block` addresses this and allows it to still be shown.

http://jsbin.com/belipunane/1/edit?html,css,output

**Comment by cvrebert** [comment]
Confirmed via http://jsbin.com/tulexi/2/edit on OS X Yosemite in Safari 8.0.3 and Chrome 40.

**Comment by cvrebert** [comment]
Filed Chrome bug: https://code.google.com/p/chromium/issues/detail?id=460200

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=141804

**Comment by cvrebert** [comment]
Filed Apple Radar problem: http://openradar.appspot.com/19892433

**Comment by cvrebert** [comment]
@mdo `display: inline-block` isn't an option, correct? Shall we close this as a non-critical browser-side bug?

**Comment by mdo** [comment]
Yeah, let's close it. `block` is definitely preferred here.

**Comment by cvrebert** [comment]
For folks bothered by this bug, we recommend starring or CC-ing yourself on the upstream browser bugs linked above, to show the browser vendors that you care about this bug.

**Comment by cvrebert** [comment]
This has been fixed in WebKit Nightly as of r186963: http://wkbug.com/141804
