### ISSUE TITLE
Bootstrap 3 button and input text filed not working in android device

### ISSUE THREAD

**Issue by dac777** [twbs/bootstrap#15834]
When I click the submit button in a android deivce doesn't work. Moreover I can see that the url changes like this:

normal_url.example to -----> this normal_url.example#

Like if I had pressed a link button or <a href='#'>

The input text is only working the first one... the other twho doesn't work in atouch device like android. Simply are not clickable.

Although if I try click in a desktop browser, the button is working normally and the input too.

This is the form: (see the form in stackoverflow non answered question)

https://stackoverflow.com/questions/28567191/bootstrap-3-button-not-working-in-android-device 

I've also tried removing my custom js and juqery code to see that there are no incompatibilities. I don't understand why is not working.

Thanks in advance

**Comment by patrickhlauke** [comment]
Please post an actual live example URL of where this issue happens, and more details about which version of Android and which browser. (incidentally, your ``for`` attributes in the code you posted on stackoverflow are wrong, as they need to point to the ``id`` of the form control they relate to)

**Comment by dac777** [comment]
Sorry I can't provide actually a live example url because I'm working in localhost and I access to the app with my android device like this: 192.168.1.x/myapp/where_the_form_is.

Did you mean "form attributes" ?  

The form attributes in the example have been changed. I have put some id values examples, but not the real.
I thougth I had something wrong in the structure. Not in the attribute values. I will check last time and if I can't get a solutuion I will remove all bootstrap clases for that particular form
