### ISSUE TITLE
Main Nav Parent Button Not Working With Dropdowns

### ISSUE THREAD

**Issue by wdejesus** [twbs/bootstrap#15838]
Hello everyone. In my nav, when a button has a dropdown the main button does not work. It works without the dropdown. Can someone help me out. The direct link is http://roseninn.wsoa.biz/

Thank you!

Will

**Comment by kkirsche** [comment]
I do not believe you can trigger a dropdown or trigger the button. In bootstrap the button triggers opening the dropdown. 

Personal support requests on how this could be changed should be directed to StackOverflow with the Twitter-bootstrap-3 tag.
