### ISSUE TITLE
.panel-collapse with .list-group-item.active adds border radius

### ISSUE THREAD

**Issue by zacechola** [twbs/bootstrap#15830]
jsbin: http://jsbin.com/wumoyi/1/edit?html,output

`.list-group-item:first-child` and `.list-group-item:last-child` removes the borders, but they're added back in by `..panel>.panel-collapse>.list-group:last-child .list-group-item:last-child` and it's first-child companion.

This doesn't seem to happen in a normal panel with a list group.

The reason isn't jumping out at me right now. :anguished:

**Comment by twbs-lmvtfy** [comment]
Hi @zacechola!

You appear to have posted a live example (http://jsbin.com/wumoyi/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by zacechola** [comment]
Damn it, robot. http://jsbin.com/wumoyi/2/edit?html,output

**Comment by mdo** [comment]
Fix demo-ed in https://jsbin.com/qomede/1/edit and in pull request form at #16175.

**Comment by twbs-lmvtfy** [comment]
Hi @mdo!

You appear to have posted a live example (https://jsbin.com/qomede/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 5, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
