### ISSUE TITLE
Resizing window breaks Affix positioning

### ISSUE THREAD

**Issue by gustavohban** [twbs/bootstrap#15845]
You can check this right on the Bootstrap website.

How to reproduce:

1 - Navigate to http://getbootstrap.com/css/
2 - Scroll down the page until you see the table of contents get affixed
3 - Resize your window to a size < 768px to hide the table of contents
4 - Scroll up the page until you reach the header
5 - Resize your window to normal size to see the table of contents still hold the .affix class and get wrong position

1
![issue-affix-1](https://cloud.githubusercontent.com/assets/6200550/6274709/15e22d02-b83f-11e4-892c-833abab2cb40.jpg)

2
![issue-affix-2](https://cloud.githubusercontent.com/assets/6200550/6274711/15e61b4c-b83f-11e4-9a07-18bec3bb85fb.jpg)

3
![issue-affix-3](https://cloud.githubusercontent.com/assets/6200550/6274707/15e0bc6a-b83f-11e4-932c-de983a3d5db4.jpg)

4
![issue-affix-4](https://cloud.githubusercontent.com/assets/6200550/6274710/15e30010-b83f-11e4-9c23-7ed38a944eca.jpg)

5
![issue-affix-5](https://cloud.githubusercontent.com/assets/6200550/6274708/15e21bb4-b83f-11e4-8738-5b032694cb02.jpg)

I dont know what is the best way to solve this problem but binding on window resize and forcing affix plugin to checkPosition solved to me.

var Affix = function (element, options) {
...
$( window ).resize( $.proxy(this.checkPosition, this));
...

**Comment by cvrebert** [comment]
Basically, anything (including media queries) that can hide/show the affixed element without notifying the affix plugin is problematic.

**Comment by fat** [comment]
I'm not too concerned about affix breaking on window resize, but if you we're feeling inspired and wanted to open a pr – i'd be happy to get that into v3.

**Comment by 1eddy87** [comment]
@fat - has this issue been resolved?

**Comment by cvrebert** [comment]
The bug hasn't been fixed, but is closed with the resolution "fat isn't interested in writing a patch for this, but Core Team would consider reviewing other folks' patches".

**Comment by 1eddy87** [comment]
I was able to work around the issue with the following:
 offset: {
        top: function () {
              return code to work out the correct value
        }
}

**Comment by alexandar87** [comment]
Thanks @1eddy87 that helped me also!
