### ISSUE TITLE
Old glyphicons in 3.3.2 working, new glyphicons are not loaded

### ISSUE THREAD

**Issue by netsetter** [twbs/bootstrap#15844]
Having a strange issue.

Trying to use glyphicon-picture or glyphicon-console and getting the square icon like when the icon-font isn't loaded.

However, all glyphicons I used before < 3.3.2 are still loaded correctly.

I tripple-checked everything, css- js- font- files, taken from the bootstrap website and now using the files from here.

Renamed the files to be sure it's not a browser cache issue, tried other browsers, added woff2 mime type to apache, but whatever I've tried, still the same problem that the old glyphicons are loaded correctly, and the new glyphicons aren't loaded at all.

Any ideas?

**Comment by netsetter** [comment]
Update:

including the new icons with <i class=""> working, with <span class=""> aren't working.

**Comment by kkirsche** [comment]
Could you post a JSBin demonstrating the problem?

**Comment by kkirsche** [comment]
Can't replicate it:
http://jsbin.com/wiyuxexapi/1/edit?html,output

**Comment by cvrebert** [comment]
This sounds like an environment/deployment problem. Questions about that sort of problem should be directed to StackOverflow instead. Thanks!
And remember to include what OS and browser(s) you're using in your SO post.
