### ISSUE TITLE
Modal  not working with bootsrap.min.js version3.3.2

### ISSUE THREAD

**Issue by manikandanAC** [twbs/bootstrap#15843]
When including the .min.js the modal is totally blacked out (opaque). But works like a charm when including the bootstrap.js?

Same issue when doing a customized download as well.

Any suggestions / workaround here is appreciated..

**Comment by kkirsche** [comment]
Could you post a JSBin and a photo demonstrating the problem

**Comment by kkirsche** [comment]
I can't seem to replicate this with a demo modal:
http://jsbin.com/wiyuxexapi/1/

**Comment by cvrebert** [comment]
Unable to reproduce. Please direct deployment troubleshooting questions to StackOverflow. Thanks.

**Comment by manikandanAC** [comment]
If i am using bootsrap.min.js version3.3.2 i am getting the output like
this.
please give any suggestions for this.

**Comment by cvrebert** [comment]
I suggest you re-ask your question on [StackOverflow](http://stackoverflow.com) (using the `twitter-bootstrap-3` tag) instead of here, since your problem is in all likelihood due to a mistake with your deployment as opposed to a bug in Bootstrap itself. Thanks!
