### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by georGEO1989** [twbs/bootstrap#15841]
Can we integrate flexbox into the grid system? I know there are issues with using flexbox with older IE browsers but are there polyfills that would work with it?

**Comment by kkirsche** [comment]
I think flexbox is cool but I'm pretty sure it wouldn't be added to V3 though as they aren't currently adding new features to V3. @mdo would probably make the call in V4 though. Thanks for the suggestion! :+1:

**Comment by kkirsche** [comment]
Compatability may a concern though with IE9 which will still be supported in V4 though — http://caniuse.com/#search=flexbox

IE9 doesn't support it, IE10 does with vendor prefixes. From [here](http://html5please.com/#flexbox) though it says, "There are presently no robust polyfills for the current spec, however you can mix old and new flexbox for maximum browser support."

**Comment by georGEO1989** [comment]
It would be awesome. I've been learning a lot about it and it's the easiest way to code layouts.

**Comment by mdo** [comment]
Can't in v3, probably can't in v4. Both for browser compatibility.

**Comment by RobertinoValue** [comment]
@georGEO1989 You might want to scan [this page](http://ink.sapo.pt/ui-elements/) for ```flexbox```.
And prise the flexbox grid out of their framework.
It works remarkably well.
I'm using their *full* framework on 2 projects. So I don't know how much time and effort would be involved. Didn't do any research.
And on top of that, it's a SCSS and JavaScript combo solution, so some translation from SCSS to Less would be involved.

**Comment by cvrebert** [comment]
X-Ref: #7332

**Comment by RobertinoValue** [comment]
From Roger Capriotti, Director, Internet Explorer:
> After January 12, 2016, only the most recent version of Internet Explorer available for a supported operating system will receive technical support and security updates. For example, customers using Internet Explorer 8, Internet Explorer 9, or Internet Explorer 10 on Windows 7 SP1 should migrate to Internet Explorer 11 **to continue receiving security updates and technical support**.

![ie-technical-support-and-security-updates-from-20160112___2015-02-19_23-39-37](https://cloud.githubusercontent.com/assets/2570736/6277845/736865ce-b892-11e4-8728-1375c180107e.png)
Source: [Stay up-to-date with Internet Explorer](http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx)

(About IE9 in the table above: We all know that Vista was skipped by the majority of corporations and consumers. And that not many people use Windows Server 2008 to surf the web.)
So in 10 months from now IE8, IE9 and IE10 are End-Of-Life.
You would encourage continued usage of browser versions unsupported by their maker, and therefore insecure.

I know what's worse of these 2 options:
- A website looking totally broken and being unusable in an ancient and insecure browser
- A website looking good and being usable in an ancient and insecure browser

Visitors with these unsupported browsers, *could* even point the finger at Bootstrap as the cause of these insecurities.
