### ISSUE TITLE
Carousel 

### ISSUE THREAD

**Issue by Walaa-Zahran** [twbs/bootstrap#15855]
please
 i need really a clear explanation about this carousel template
and the code of css and javascript
Sincerely ;

**Comment by patrickhlauke** [comment]
Sorry, but if you need an actual code-level explanation for the carousel component beyond http://getbootstrap.com/javascript/#carousel, you should direct your question to alternative places such as StackOverflow.

**Comment by Walaa-Zahran** [comment]
why you make it so hard !?

On Fri, Feb 20, 2015 at 6:02 PM, Patrick H. Lauke <notifications@github.com>
wrote:

> Closed #15855 <https://github.com/twbs/bootstrap/issues/15855>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/15855#event-239210032>.
>



-- 
Name : Walaa Mohamed Ali Mohamed Zahran
Mobile Number :01095114557-01095152424
Work:Student in Computers and informatics College,Suez Canal University
Section : 3
