### ISSUE TITLE
Stop Carousel if there is only 1 item

### ISSUE THREAD

**Issue by slackero** [twbs/bootstrap#15863]
It can happen that you have a single carousel item only (script generated Carousel).

Carousel should then:
- stop sliding
- add `active` class
- remove `.carousel-inidcator`
- remove `.carousel-control`

This would also solve the problem that Carousel returns an offsetWidth error message if the `active` class is missing too.

My simple solution is this:
```javascript
  $(window).on('load', function () {
    $('[data-ride="carousel"]').each(function () {
      var $carousel = $(this);
      var $items = $carousel.find('.item');
      if($items.length > 1) {
        Plugin.call($carousel, $carousel.data());
      } else {
        $items.addClass('active');
        $('.carousel-indicators,.carousel-control', $carousel).remove();
      }
    });
  });
```

**Comment by cvrebert** [comment]
* Sounds like you might as well not generate a Carousel at all in that case, and just output the `<img>` by itself.
* I think it's easy enough to have your script include the `.active` when it generates the Carousel in the first place.
* The other stuff sounds like overkill, and causes an edge case when a carousel initially has only 1 slide but then later has more added to it.

**Comment by slackero** [comment]
I know the pros and cons — but script should not fail when active is missing, in general that's all. In my opinion it's more overkill to start the Carousel when there is single item found only. But I haven't found an option to request the amount of items inside the Carousel fn.

**Comment by mdo** [comment]
I'm with @cvrebert—if you've got one image, there's no need for a carousel.

**Comment by StevenBlack** [comment]
It's not that simple.

A common performance tweak is load the page with a single carousel element then, once the page is fully loaded, get and append subsequent carousel elements (which could be `<div>`s with text, or images, or some combination.

@slackero does say this is a script generated carousel.

So if carousel elements come via request, potentially a zero-sized response, then I think @slackero's suggestion has merit, but with a `carousel-control` class `.hide()`, not `remove()`.

**Comment by cvrebert** [comment]
Having a few controls that are momentarily not strictly necessary doesn't seem like that big a of deal, imho.
