### ISSUE TITLE
Boot strap issue..

### ISSUE THREAD

**Issue by warunasanjayanew** [twbs/bootstrap#15869]
where to put these ==> @navber-height @navbar-padding-vertical .Please can show that to me in example?
Those parameters are mentioned here.  
http://stackoverflow.com/questions/19890700/change-navbar-height-in-bootstrap3
I am using bootstrap 3.0.0

**Comment by mdo** [comment]
Closing as super out of date and not something we can help with here (odd we somehow overlooked this). Searching Google for how to use Less would be your best bet :).

**Comment by cvrebert** [comment]
See https://github.com/twbs/bootstrap/blob/master/README.md#community for other community forums you could ask for help with this at.
