### ISSUE TITLE
Modal memory leak

### ISSUE THREAD

**Issue by toddbranch** [twbs/bootstrap#15868]
![leak](https://cloud.githubusercontent.com/assets/1130792/6323040/642510b8-badf-11e4-9843-b5c3cf56440b.jpg)

This is from repeatedly opening and closing the modal via Launch Demo Modal on http://getbootstrap.com/javascript/#modals.  DOM node count is continually growing.  Unsure if issue, or a misunderstanding on my part.

Thanks for all your work!

**Comment by cvrebert** [comment]
Did you force a GC run? That brings the node count back to normal for me, which would seem to indicate that it's not a true memory leak:
![gc](https://cloud.githubusercontent.com/assets/419884/6324114/1c3f27b0-baea-11e4-836b-5fc4749bf29a.png)

**Comment by toddbranch** [comment]
You're right.  I guess I was under the impression that the GC events in my screenshot were targeting everything.
