### ISSUE TITLE
Issues with Haltbox.com

### ISSUE THREAD

**Issue by kramerska** [twbs/bootstrap#15865]
I've noticed they use bootstrap and have no EULA or references to the development as per software agreements.

https://www.facebook.com/Haltbox.Startup?pnref=story

https://www.haltbox.com/

I posted to their website questioning why.

**Comment by kkirsche** [comment]
Thanks for passing this on!

**Comment by mdo** [comment]
Likely an issue with our Sass port which didn't have a license after compiling for awhile. Not a huge deal though, they'll get it back whenever they update.
