### ISSUE TITLE
Masthead Documentation

### ISSUE THREAD

**Issue by nfarrar** [twbs/bootstrap#15879]
I've seen a lot of a examples that use a "masthead" however I'm having trouble finding documentation on what a masthead is, when it should be used, and what it does.

Is this in the documentation somewhere and I'm just missing it?

**Comment by kkirsche** [comment]
There is no masthead component in bootstrap though components such as jumbotron could probably be used as mastheads. 

Mastheads are a concept that predates the creation of web pages. Essentially, a masthead is a graphic image that is often found at the top of a printed or electronic page. The masthead may include a number of different elements that are designed to catch the eye and provide the page with a degree of visual appeal. Most designers for mastheads also attempt to create a final design that will be easy for viewers to remember and easily associate with the publication.

When the overall design of the masthead is effective, visitors to the website are much more likely to continue scanning the web page and hopefully finding additional elements that attract attention. Many online retail businesses understand that a properly designed masthead can cause someone browsing the Internet to stop long enough to develop interest in the site and begin browsing through the items offered for sale. For this reason, many online stores will spend a great deal of time and energy in creating a masthead that will come to be familiar and welcoming to the buying public.

The amount of space that the masthead employs on the web page will vary from one application to another. Some web site owners find that a masthead that utilizes up to one third of the front page is effective. Others may choose to create a masthead that takes up the majority of the front page, and is only augmented with a hot button to allow the visitor to proceed to the next page. Still others choose to go with a relatively small and simple masthead and save most of the room for the display of items for sale or promotional announcements. As with print media, the use of the masthead in online applications covers a lot of ground, and is often determined by the marketing strategies employed by the business involved.

**Comment by patrickhlauke** [comment]
As this is not directly related to Bootstrap itself, I'd suggest taking this question to somewhere like StackOverflow :)

**Comment by nfarrar** [comment]
Thank you for the answer @kkirsche. :) 

@patrickhlauke I apologize, I didn't realize that it was unrelated when I asked (there are so many examples that use a .masthead - it's even used in the official examples). I thought perhaps that it was in the documentation but I didn't know where to look to find it, or that it was an undocumented/deprecated/experimental feature.
