### ISSUE TITLE
Why not use the new semantic elements from HTML5?

### ISSUE THREAD

**Issue by lusabo** [twbs/bootstrap#15870]
It would be interesting to update the bootstrap to use the new sectioning elements (header, footer, section, article, aside and nav)?

**Comment by patrickhlauke** [comment]
assuming you mean the bootstrap *examples* ? (as bootstrap itself does not come with any actual prescribed/ready-made HTML)

**Comment by kkirsche** [comment]
I think the docs page (which uses `<header>`, `<main>` for example) does a pretty good job.

I do believe that there could be better use of `<section>` throughout the actual docs pages to group each section within the CSS, Components and Javascript page but I'm not sure if there is a reason that this is currently not done.

**Comment by mdo** [comment]
Use any elements you like. We use a few here and there, but they're not required. Nothing changes for the components though—they're just as customizable and functional.
