### ISSUE TITLE
Add html { overflow-y: scroll; }

### ISSUE THREAD

**Issue by corysimmons** [twbs/bootstrap#15883]
This prevents the layout from "bouncing" about 20px when users go from a page with little content (doesn't have a scrollbar) to a page that has lots of content (has a scrollbar).

**Comment by mdo** [comment]
This has been brought up before and we won't be doing it. It's not necessary in any capacity and personally I feel its a bad practice.

**Comment by corysimmons** [comment]
@mdo No problem. Out of curiosity do you have a blog post or a link to a comment somewhere that describes why you think it's a bad practice?

**Comment by mdo** [comment]
Nope nothing to link to. Aesthetically it's unnecesaary, on many mobile devices and OS X you don't see them half the time, etc.

**Comment by corysimmons** [comment]
Fair enough. Thanks for taking the time to reply.
