### ISSUE TITLE
Modal window close event does not remove body class

### ISSUE THREAD

**Issue by FastEddie8888** [twbs/bootstrap#15880]
When a modal window is initialized, the body has a new class of "modal-open", which is FAD, but on the event close, the class is not removed from the body as a result. Since the modal-open class contains overflow:hidden, this is breaking the website as scroll bars are now removed and no longer able to scroll to the bottom of the page.

Thanks, Eddie

**Comment by FastEddie8888** [comment]
![image](https://cloud.githubusercontent.com/assets/6530213/6340338/41c3cb56-bb73-11e4-9fa4-a15ba3a5cab7.png)
result of markup after modal is closed.

**Comment by hnrch02** [comment]
- Which version of Bootstrap are you using?
- Which browser are you seeing this in?

And also please post a live example demonstrating the problem, since I'm unable to reproduce this on getbootstrap.com.

**Comment by cvrebert** [comment]
Closing due to lack of response from OP to hnrch02's questions.
