### ISSUE TITLE
rules for a and .btn-link

### ISSUE THREAD

**Issue by Bartmax** [twbs/bootstrap#15892]
```
<form>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="">link</a></li>
        <li><button type="submit" class="btn btn-link">button</button></li>
    </ul>
</form>
```

in this simple example code, the link and the button will look really different. I think it will be great to change all styles targeting `anchor` also targeting `.btn-link`. What do you think ?

**Comment by kkirsche** [comment]
[JSBin of the above code](http://jsbin.com/nepulexuyo/1/edit?html,output)

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://jsbin.com/nepulexuyo/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Bartmax** [comment]
adding `navbar-btn` fixes position issue, only thing left is the color and :hover

**Comment by mdo** [comment]
Given how the components are structured today, this isn't really practical with how much overriding you'd have to do to support both. Punting for now.

**Comment by Bartmax** [comment]
I think that using `.navbar-btn` and create a new `.navbar-btn-link` will be a good addition then.

Use case is mainly for log out link scenarios on navbar. Since the recommended way to do log out is via POST, it would be good to avoid having a logout page or using javascript to submit a form.

I can create a PR if you think that will be good @mdo

**Comment by Bartmax** [comment]
nevermind, wrapping in a form-group looks like it solves the problem.

**Comment by mdo** [comment]
I'm fine punting on it for now—no new additions to v3.

**Comment by rapilabs** [comment]
It's also worth pointing out that although `.navbar-btn` will fix the positioning, the btn-link will not have the same height as a regular link and will become apparent when the outline appears on focus.  Developers may simply just set the height as desired.

I'm also using a button to submit a simple form which will POST to a logout url.
