### ISSUE TITLE
Bootstrap v3.3.2 -> Firefox -> Refresh -> Carousel -> Images not shown

### ISSUE THREAD

**Issue by Peter4711** [twbs/bootstrap#15899]
Carousel images are not shown anymore when you refresh (F5) the page. 
You have to delete the Firefox history and then one time it is okay.
If you use Firebug you can display the images if you disable the "display:block" property. After a refresh the problem exists again of course.

This seems to be the rule:
.carousel-inner>.item>a>img,.carousel-inner>.item>img,.img-responsive,.thumbnail a>img,.thumbnail>img{display:block;max-width:100%;height:auto}

I discovered in this moment: it seems to be connect to the carousel auto display previous next images, because when the interval is over the images appear again (with jQuery 2.0, jQuery 2.1.3 NOT).

Also important: You habe to use local files, no problem with files from external servers.

Environment:
Firefox 35.0 -> PROBLEM!
Linux 3.11.10-25-desktop
openSUSE 13.1 (Bottle) (i586)
KDE 4.11.5

Google Chrome Version 40.0.2214.115 -> NO PROBLEM!

**Comment by Peter4711** [comment]
I discovered in this moment: it seems to be connect to the auto display previous next images, because when the interval is over the images appear again.
jQuery: 2.0 and 2.1.3

**Comment by kkirsche** [comment]
Would you be able to post a JSBin which we could test the issue with?

**Comment by Peter4711** [comment]
http://jsbin.com/micebi/1/

I'm sorry, but it seems to be imposible to save a file at JSbin or I don't understand this tool (1st time work wihth).

Important: use local image files

**Comment by twbs-lmvtfy** [comment]
Hi @Peter4711!

You appear to have posted a live example (http://jsbin.com/micebi/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 94, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 41, column 23: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Peter4711** [comment]
Ok. done.

**Comment by kkirsche** [comment]
For me in Firefox 35.0.1 and 36.0 on Mac OS X 10.10 I don't experience the issue you mentioned

**Comment by cvrebert** [comment]
The updated version: http://jsbin.com/micebi/2

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/micebi/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
> Important: use local image files

So, the problem doesn't occur for you when using the lorempixel version?

**Comment by Peter4711** [comment]
Exactly.

**Comment by cvrebert** [comment]
I don't think this is worth our time then. `file://` isn't used in production and this probably only affects Linux.
More power to you if you want to file a Firefox bug about this yourself though.

**Comment by Peter4711** [comment]
You are probably right. Thank you for your time.
