### ISSUE TITLE
Carousel Indicators 'active' status not supporting multiple carousels

### ISSUE THREAD

**Issue by permanyer** [twbs/bootstrap#15901]
Hello,
When having more than one twbs carousel components in a page, the 'active' status of the .carousel-indicators does not change.

This is due to the selector in the bootstrap.js `this.$indicators = this.$element.find('.carousel-indicators')`

A workaround would be to select the indicators via the data-target attribute of its children.
Currently I am doing it manually:
```
$(document).ready(function() {
    $('.carousel').on('slid.bs.carousel', function () {
		var carousel_id = $(this).attr('id');
		var indicators = $('li[data-target="#'+carousel_id+'"]').closest('.carousel-indicators');
	        indicators.find('li.active').removeClass('active');
	        var idx = $(this).find('.item.active').index();
	        indicators.find('li[data-slide-to="'+ idx+'"]').addClass('active');
    });
});
```

**Comment by kkirsche** [comment]
Could you post a JSBin of this issue?

**Comment by hnrch02** [comment]
I mean we have multiple carousels on our documentation page at http://getbootstrap.com/javascript/#carousel and it works just fine there for me. Are you sure that your carousels aren't sharing one ID?

**Comment by permanyer** [comment]
Mines are nested. I have a carousel of carousels.

**Comment by hnrch02** [comment]
I see, we don't support nested carousels though, see http://getbootstrap.com/javascript/#carousel:

> A slideshow component for cycling through elements, like a carousel. **Nested carousels are not supported.**

You'll either need to continue using your current workaround or use a different library that provides supported for nested carousels.

**Comment by permanyer** [comment]
OK, I had not noticed nested carousels were not supported. Using a different library for one of them, now. Thanks
