### ISSUE TITLE
What happened to the "Customizing Bootstrap" section of the Getting Started docs?

### ISSUE THREAD

**Issue by heyallan** [twbs/bootstrap#15918]
This section has been deleted: http://bootstrapdocs.com/v3.1.1/docs/getting-started/#customizing

What's the convention now?
I'd like to reference a “good practice” recommendation.

**Comment by hnrch02** [comment]
I guess some parts of it can now be found at http://getbootstrap.com/css/#less. /cc @mdo

**Comment by heyallan** [comment]
Sort of. But that is more how to “use” it, than how to “customize” it.
It clearly addresses: “those looking to use the source…”

I see a blended idea there.

Earlier version was clearer offering recommendations on how to stack customizations above the source and how to keep them separate. Valuable recommendation if you ask me.

I'm interested in having an official “good practice recommendation” that I can point to.

**Comment by cvrebert** [comment]
Looks like it was axed by 2a43e7e78a59c70e217383c12c9ef0482cabb163 without an explicit reason.

**Comment by mdo** [comment]
I'm not super happy with the content I created for that, so I nuked it when we broke apart the docs' content.

**Comment by XhmikosR** [comment]
@mdo: better than nothing, though :P

**Comment by mdo** [comment]
In this case, I'd prefer not to have that content in the docs. It's dependent on an external example for one and isn't all that great for what we could do.
