### ISSUE TITLE
Bootstrap 3.3.2 :Glyphicons work in chrome and andriod, don't work in IE and firefox

### ISSUE THREAD

**Issue by adam139** [twbs/bootstrap#15917]
Bootstrap 3.3.2 :Glyphicons work in chrome and andriod, don't work in IE and firefox

**Comment by cvrebert** [comment]
This is in all likelihood a problem with your website's configuration/environment, and we can't offer assistance with those sorts of problems here. Please ask on StackOverflow instead. Thanks!
