### ISSUE TITLE
Encourage use of icons with form validation states for the sake of colorblind users?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15928]
Refs #14744. Perhaps we should add a note to the form field validation state docs warning about their accessibility to colorblind users, and recommending the additional use of the indicator icons for the sake of such users? What do you think @patrickhlauke?

**Comment by kkirsche** [comment]
I'm very much for this.

Normal:
![screen shot 2015-02-25 at 7 50 10 pm](https://cloud.githubusercontent.com/assets/947110/6384216/976655d2-bd27-11e4-95b7-14da0a84f320.png)

Protanopia / Dueteranopia (Red / Green Color Blindness):
![screen shot 2015-02-25 at 7 51 15 pm](https://cloud.githubusercontent.com/assets/947110/6384228/c00ff088-bd27-11e4-8804-357890e347e1.png)

**Comment by patrickhlauke** [comment]
Commented on #15929 but in principle, even inputs/checkboxes/etc with an explicit bit of text (e.g. a bit of text saying "error"/"invalid"/etc or something as part of the label) would be nominally accessible to colorblind users (i.e. icons are not the only way to help this user group). In principle, I'm all for expanding the note, as per #15929, as long as we don't give the impression that *only* icons are the way to go.

**Comment by cvrebert** [comment]
> even inputs/checkboxes/etc with an explicit bit of text (e.g. a bit of text saying "error"/"invalid"/etc or something as part of the label) would be nominally accessible to colorblind users

Ah, true. However, none of the existing examples clearly do that.
Also I think a lot of folks prefer to put that text in the [help text](http://getbootstrap.com/css/#forms-help-text) ([a la formvalidation.io](http://formvalidation.io/getting-started/#example)) rather than the `<label>`.

**Comment by patrickhlauke** [comment]
the help text approach is also valid for colorblind users, mind (and because of the ``aria-describedby`` for AT users too). but yes, i think #15929 is on the right track, just needs a tiny bit of tweaking of the wording
