### ISSUE TITLE
Tooltips create a newline

### ISSUE THREAD

**Issue by Phieo** [twbs/bootstrap#15920]
When I use tooltip in my project, the title was not in a single line.
![bug](https://cloud.githubusercontent.com/assets/10499704/6372166/03b9108e-bd3d-11e4-8c4e-05954cb0fa1d.png)
My html code is 
```<a href="#list/all" class="iconfont note-btn nav-btn" data-toggle="tooltip" data-placement="right" data-original-title="so what?"></a>```

My js code is <code>$('[data-toggle="tooltip"]').tooltip();</code>

Was there anything wrong with what I did?

**Comment by kkirsche** [comment]
I'm pretty sure this is expected behavior, not something that went wrong.

**Comment by Phieo** [comment]
@kkirsche but the examples in http://getbootstrap.com/javascript/ are in single line

**Comment by kkirsche** [comment]
@Phieo I believe it tries to keep the size of the element it is called on. Because in the example it is wide, the tooltip has more room. In your example it is just the icon so it wraps to try to keep the same size.

**Comment by Phieo** [comment]
@kkirsche I think it is relevant to the data-original-title, if there is no space in it, everything is ok! 
![bug2](https://cloud.githubusercontent.com/assets/10499704/6372539/e5f38a04-bd3f-11e4-97a3-01508e5efb93.png)

**Comment by kkirsche** [comment]
Right, because a single word can't easily be broken. Any two line with a single icon should break at the space.

**Comment by Phieo** [comment]
@kkirsche thx, I've solved the problem by add the option container: body, you are right.

**Comment by kkirsche** [comment]
Anytime. Happy to help :+1:
