### ISSUE TITLE
popover.js accessibility issue on generated html template

### ISSUE THREAD

**Issue by maia-n** [twbs/bootstrap#15924]
When Popover default template is used within a page, document structure is somewhat odd :
`<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>`
It would be better to leave h level parametrized, or use a different way to style it like an h3.
Many thanks

**Comment by kkirsche** [comment]
When you say popover box code where do you see the H1? If you could link to where you are seeing this or provide a JSBin of the problem that would be appreciated.

**Comment by maia-n** [comment]
Comment updated, the h1 was somewhere else.  As for the hierarchy, this is the reference.
bootstrap.js, line 1582 

  Popover.DEFAULTS = $.extend({}, $.fn.tooltip.Constructor.DEFAULTS, {
    placement: 'right',
    trigger: 'click',
    content: '',
    template: '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'
  })
Maybe the use of h3 in the default template should not be necessary, and using a div will also work. That said, bottom of the backlog then.

**Comment by kkirsche** [comment]
I'm not 100% sure I follow the issue.

In this code, what specifically is the issue?

```javascript
Popover.DEFAULTS = $.extend({}, $.fn.tooltip.Constructor.DEFAULTS, {
    placement: 'right',
    trigger: 'click',
    content: '',
    template: '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'
  })
```

Would I be correct that you feel the `<h3>` is not semantically correct and should instead be a styled `<span>`, `<div>` or similar element?

**Comment by maia-n** [comment]
That's correct. Thanks!

**Comment by cvrebert** [comment]
@maia-n For future reference, you need to either enclose HTML in backticks or use fenced code block when posting HTML in GitHub comments.

**Comment by maia-n** [comment]
Thanks again, and my apologies for not being aware of working guidelines. Next time I will use them.

**Comment by fat** [comment]
hm i'm struggling to see how the h3 is invalid – @patrickhlauke i'm going to close this issue, unless you have some strong feeling that a title shouldn't be a heading element?
