### ISSUE TITLE
[feature] Semantic markup throughout the project

### ISSUE THREAD

**Issue by shehi** [twbs/bootstrap#15939]
I frequently write markup and CSS for my web projects, and the thing that I mostly adore in doing so is semantic data model. In short, I hate excessive usage of ```<div>``` tags, endlessly nested for the sake of creating the desired view (which isn't actually data-layer's job, but that of presentation layer's to be honest). I love Bootstrap as it helps all of us to create responsive, well-designed web UI at a glimpse in a very professional manner. Nevertheless, I hate seeing lack of support for semantic markup - I just checked Mark Otto's Code Guide, and even there, he states his support for the usage of least amount of markup. 

To give a specific example, I will talk about ```Tabs``` feature: semantically [it could easily be coded](http://stackoverflow.com/questions/10913087/box-with-tabbed-navigation-using-semantic-markup-structure) with ```<dl>``` tag, ```<dt>```'s being the tab's nav-bar component, ```<dl>```'s being tab-content. Instead we have two unrelated package of tags, ```<ul>``` for tab nav-bar and bunch of ```<div>```'s for tab-content. My question is: **WHY?** Why do we sacrifice data-layer for the sake of presentation one?

I'd love to see Bootstrap gradually move towards this semantic markup practice. This project already made many lazy devs and designers create clean code; taking this one step further would only improve the current state of front-end development - we all know good markup doesn't only enable easy code management, but also helps to right interaction layer (javascript and alike) in much more efficient way.

**Comment by kkirsche** [comment]
While this isn't going to change for V3 (as it's near end of life), it's something I believe @mdo has said will be addressed in part in V4, but a collab / admin would need to confirm or deny that.

**Comment by shehi** [comment]
That would be extremely awesome @kkirsche . Right now, I am refactoring admin UI for my open source package, where I intend to minimize markup and increase code quality. I stumbled upon ```Tabs``` and can't get TWBS's selector rules inherited in my SCSS files. It's hardcoded like ```.nav > li > a```. Now I am stuck :)

**Comment by patrickhlauke** [comment]
Going with your specific example, using a definition list for a tabbed interface is inappropriate, at best. Far from being "semantic", this misuses markup constructs.

**Comment by shehi** [comment]
I tend to disagree @patrickhlauke . But I guess it depends from what point of view you approach to the semantics of the practice. To me, tab-names are descriptive metas for their respective content, thus ```<dl>``` tag is suited for that role the most.

**Comment by kkirsche** [comment]
I would agree with what @patrickhlauke said but to expand on this:

In HTML 4, <dl> was considered a “definition list”, containing groups of terms and their definitions. The terms and definitions were a many-to-many relationship: one or more terms to one or more definitions. The element was often misunderstood and therefore misused or not used at all in favour of more widely used and (perhaps) less semantic markup.

To address these issues, <dl>’s definition has been refined in HTML5 as a description list. From the spec:

The dl element represents an association list consisting of zero or more name-value groups (a description list). Each group must consist of one or more names (dt elements) followed by one or more values (dd elements). Within a single dl element, there should not be more than one dt element for each name.

Source for that stuff: http://html5doctor.com/the-dl-element/

But V4 will have much simpler markup in general per @mdo here https://github.com/twbs/bootstrap/issues/15816#issuecomment-74465523

**Comment by shehi** [comment]
Yea, and according the same specs, all other tags were created for much (generally) simpler purposes as well, including lists and headings etc.

**Comment by mdo** [comment]
How exactly is using a `<dl>` "semantic" for tabs?

> The HTML <dl> Element (or HTML Description List Element) encloses a list of pairs of terms and descriptions. Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).

That's what [the MDN says about the `<dl>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl).

> But I guess it depends from what point of view you approach to the semantics of the practice.

There's not really any point of view when it comes to semantic HTML. You can follow the spec-ed usages, or not. There are elements that are designed for particular uses. Browsers and screenreaders apply meaning to those uses. Mis-using those elements can be bad.

That `<dl>` example involves removing elements from the normal flow of the DOM—meaning they're using `position: absolute;`. This is less efficient for browsers to render and far more difficult to manipulate aesthetically and structurally.

Yes, at times our markup is a bit more verbose than necessary, but at the time we made these things, those were the best options for our level of browser support and community-requested customization. v4 will be far more flexible on the required DOM (e.g., use a `<ul>` for tabbed nav or use a `<nav>` with just `<a>`s).

**Comment by shehi** [comment]
Not to create flame, but just to provide a food for thought: How would you wish your tabbed content to look like if you disabled CSS? From document perspective. I code my markup as if I am writing some Word processor document, with absolute minimum of markup. Then I put it aside and create styles for it, almost never touching that markup again. If I disabled CSS from my web, seeing tabbed interface as definition-lists would be more meaningful to me. I don't know you guys, but seeing unrelated unordered-lists and then tons of other content doesn't really look right to me. Both from document point of view, and that of crawler's. Again, I just wonder what you guys think about such issues, I am not writing to question your tastes or create a heat here.

**Comment by kkirsche** [comment]
For me personally I look at it from a spec viewpoint. I find that things like `data-rel`, `role="tablist"`, and other accessibility techniques are able to be used to communicate the relationships of content better than markup which was designed for other purposes

**Comment by patrickhlauke** [comment]
Feel free to continue this discussion on more general web-standards-oriented mailing list or forums. Cheers.

**Comment by mdo** [comment]
> Not to create flame, but just to provide a food for thought: How would you wish your tabbed content to look like if you disabled CSS? From document perspective. I code my markup as if I am writing some Word processor document, with absolute minimum of markup. Then I put it aside and create styles for it, almost never touching that markup again. If I disabled CSS from my web, seeing tabbed interface as definition-lists would be more meaningful to me.

That's one way to write your HTML and CSS, but it's not the only way. Working with dozens to hundreds of others on a single code base means doing things in tandem. That includes writing HTML and CSS that dovetails together elegantly and efficiently.

Disabled CSS (or even JS) isn't a major concern for us—it's not something that happens in browsers by default. Disabling those is a conscious decision users make. Proper and meaningful document structure is important, yes, but—going back to one of the original points here—this doesn't simply boil down to one's use of `<ul>`s or `<dl>`s.

We write our HTML and CSS to work together. Working on one in a vacuum feels like that wrong approach to me, but doing things differently is a-okay with me. That doesn't mean one of ways sacrifices quality in any shape or form. That just means we approach building systems of components from separate view points with perhaps separate concerns.

I care more about building efficient and elegant components. Bootstrap is about building durable components for anyone to customize and use for any number of things. That's where my focus lies.

> I don't know you guys, but seeing unrelated unordered-lists and then tons of other content doesn't really look right to me. Both from document point of view, and that of crawler's.

No one sees them that way unless someone's CDN is down or a URL is broken. Folk's don't want to see un-styled pages—anything that's even somewhat un-styled is frowned upon. Search bots and crawlers care even less about this stuff provided they can scan the document (and that happens no matter the HTML you use for your tabs).

> I understand the difficulties in CSS creation when you go this way, but hey, what is easy in our line of work anyway? I personally don't like sacrificing quality for someone's unwillingness to learn their craft better.
>
> Again, I just wonder what you guys think about such issues, I am not writing to question your tastes or create a heat here. Anyway, I apologize in advance, if I offended somehow.

None of this was personal in any way until that comment right there. I don't mind having these kind of discussions. I usually enjoy them, I like being questioned and I like questioning things. But seeing something like this makes me think you're not interested in hearing other ideas and that it is in fact personal.

I've used `<dl>`s for components other than definitions—there are so many nav ideas you can use them for. Insinuating that I or my team are lazy or unwilling to learn our craft is a big fuck you, and that's not very productive (or nice). You might not have meant that, but it reads pretty clearly there.

---

No matter what, there are always multiple options for HTML and CSS. That's what makes it so frustrating to some and awesome to others at the same time. I love the freedom these languages provide and the constraints I can create to build compelling experiences for others. I still maintain, and the spec agrees, that `<dl>`s *shouldn't* be used that way, but that doesn't mean they can't. Hell, some of my projects staunchly [ignore spec recommendations](http://mdo.github.io/mdoml).

At the end of it though, we're all just here to build cool shit with cool people. Keep that in mind and be open to people not agreeing with your take (friendly reminder for me and my team, too) and everything will be just dandy.

<3
