### ISSUE TITLE
Unit tests: Implement assert.expect in each unit test

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap#15953]
And require every future unit test to also do so.

See https://github.com/twbs/bootstrap/pull/15593/files#r25565051 as to why.

/cc @cvrebert

**Comment by cvrebert** [comment]
SGTM.

**Comment by kkirsche** [comment]
I'll have a PR for this shortly

**Comment by hnrch02** [comment]
As a side note, we should probably have a "What should a unit test look like?" section in #15952 that concisely explains the styling rules a test should follow.
