### ISSUE TITLE
Bootstrap 3 modal leaves blank space on mobile browsers

### ISSUE THREAD

**Issue by vishnuc** [twbs/bootstrap#15957]
I am using latest bootstrap 3.3.2 , So Everything works fine .But when opening modal in mobile browsers , there is menu bar at the bottom as shown in images attached.When scrolled it hides the bar and leaves empty space at the bottom.How can I redraw the modal and backdrop to full height when menubar or addressbar is hidden.

full details with screenshots here http://stackoverflow.com/questions/28791777/bootstrap-3-modal-leaves-blank-space-on-mobile-browsers

**Comment by hnrch02** [comment]
Presumably you are running into #15136 which will be fixed by #15881 in v3.3.4. You could try to mitigate this in the meantime by calling `$('#myModal').data('bs.modal').handleUpdate()` which will basically redraw the modal's backdrop.
