### ISSUE TITLE
Customize Bootstrap - Only modal

### ISSUE THREAD

**Issue by Donny5300** [twbs/bootstrap#15966]
The z-index is a issue because the backdrop is falling over the modal instead of before it.

**Comment by kkirsche** [comment]
Can you post a photo, what browser you are on and what operating system you use?

**Comment by cvrebert** [comment]
Please post a JS Bin demonstrating the problem. Also, what does this have to do with customization?

**Comment by cvrebert** [comment]
Closing due to lack of response to our questions.
