### ISSUE TITLE
Popover is not shown if content is 0 (numeric)

### ISSUE THREAD

**Issue by ashmind** [twbs/bootstrap#15969]
We use popover to show some counts/stats, so it is not surprising we just put a number in there.
However 0 doesn't show up -- probably because it's falsy.

Example:
http://jsfiddle.net/fL5s3hmp/5/ (press Test-0 to see the problem).

**Comment by twbs-lmvtfy** [comment]
Hi @ashmind!

You appear to have posted a live example (http://fiddle.jshell.net/fL5s3hmp/5/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 48, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 49, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ashmind** [comment]
Updated example as per @twbs-lmvtfy: http://jsfiddle.net/fL5s3hmp/6/.

**Comment by cvrebert** [comment]
Per our docs, `content` should be a string or function that returns a string. Not a number.

**Comment by ashmind** [comment]
That's fair -- the problem is all other numbers work well, so it is not immediately obvious this is not supported.

**Comment by cvrebert** [comment]
I agree it would be more user-friendly if we did more typechecking of argument values.

**Comment by kkirsche** [comment]
@cvrebert what would the expectation be with more type checking? A simple `console` warning or throw an error stating that type `Integer` for example was found when expecting type `String` or `Function`?

**Comment by cvrebert** [comment]
@kkirsche Throw an Error.

**Comment by fat** [comment]
closing - v4 we will be addressing the option type checking
