### ISSUE TITLE
Non-responsive example doesn't handle form-inline

### ISSUE THREAD

**Issue by simonbrent** [twbs/bootstrap#15977]
See: http://jsbin.com/hakunigina/1/edit?html,output

When you shrink the html panel to below 768px, the text input gets large (100% of the parent width)

**Comment by twbs-lmvtfy** [comment]
Hi @simonbrent!

You appear to have posted a live example (http://jsbin.com/hakunigina/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
@simonbrent Bootstrap 3 does not include a "non-responsive stylesheet" like Bootstrap 2 had. Please follow http://getbootstrap.com/getting-started/#disable-responsive for disabling responsiveness in Bootstrap 3.

**Comment by simonbrent** [comment]
@twbs-lmvtfy I have now updated the example - http://jsbin.com/yeviqupogo/1/edit?html,output (note, different URL), and the problem persists

@kkirsche http://getbootstrap.com/getting-started/#disable-responsive is what I am following in my example
