### ISSUE TITLE
Short modal above long modal takes away scrollbar on close

### ISSUE THREAD

**Issue by joakim-m** [twbs/bootstrap#15979]
If I have a long modal that requires a scrollbar. Then on top of that open a short modal that doesn't require a scrollbar. When I close the short one, the scrollbar disappears and makes it impossible to scroll the remaining long one.

Also if a modal content is expanded dynamically, the backdrop is not, so it creates an area that is not covered by backdrop.

**Comment by kkirsche** [comment]
Bootstrap 3 doesn't support multiple modals. http://getbootstrap.com/javascript/#callout-stacked-modals

Secondly, for the modal backdrop please refer to this (not yet published to website): https://github.com/twbs/bootstrap/blob/master/docs/_includes/js/modal.html#L397-L398

**Comment by cvrebert** [comment]
What @kkirsche said.
