### ISSUE TITLE
Strange behavior of a class="alert" in a <div class="col-md-3-offset>" depending on the browser window witdth

### ISSUE THREAD

**Issue by caBBAlainB** [twbs/bootstrap#15971]
I'm facing a strange behavior of class='alert' container depending on the browser window's width.

The html code is this one:

	<div class="col-md-offset-3">
	    <div class="form-group select">
	        <label class=" control-label" for="siteopeningdatechoices">Opening periods :</label>
	        <select class="form-control" name="siteopeningdatechoices" id="siteopeningdatechoices">
	            <option value="0" selected="selected">Undefined periods</option>
	            <option value="1">Defined periods</option>
	        </select>
	    </div>
	    <div id="openingdateslist">
        </div>
	    <div class="hidden" id="siteopeningdates_size">0</div>
	    <div id="helpTime" class="alert alert-info" role="alert"> <em>This is an help to input hours.</em>
	     </div>
	</div>

As you can see, if there is enough space, I want my div with an offset of 3.

I have an empty `<div id="openingdateslist"></div>`, where a javascript inserts additional html code.
So, I would have my additional html code and below, the `<div id="helpTime"...`.

And here is the problem; If bootstrap doesn't have enough space and give up col-md-offset-3, everything works fine but if it adds the offset, I visually have the inserted code inside the blue div!!!

You can test it in the fiddle below by moving the vertical separator left and right to see the result.

http://jsfiddle.net/suunt549/6/

According to my tests, the problem appears in both Firefox and Chrome.

Is there anything wrong in my code?

**Comment by twbs-lmvtfy** [comment]
Hi @caBBAlainB!

You appear to have posted a live example (http://fiddle.jshell.net/suunt549/4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by caBBAlainB** [comment]
jsfiddle update to 3.3.2. same result.

**Comment by cvrebert** [comment]
Your col-md-offset-3 should be the child of a `<div class="row">`

**Comment by cvrebert** [comment]
Please make a version of your example that involves no JavaScript.

**Comment by caBBAlainB** [comment]
Thanks cvrebert, <div class="row"> is the trick but not around col-md-offset-3, in my original code it is already, it's necessary around the code added by javascript.

http://jsfiddle.net/suunt549/9/

**Comment by cvrebert** [comment]
@caBBAlainB I can't seem to reproduce, or perhaps I'm not understanding your description. Can you post a screenshot showing the problem?

**Comment by cvrebert** [comment]
X-Ref: http://stackoverflow.com/questions/28781471/strange-behavior-of-a-class-alert-in-a-div-class-col-md-3-offset-depending

**Comment by cvrebert** [comment]
JS-free version of the example: http://jsfiddle.net/1ggbdL8x/5/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/1ggbdL8x/5/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 70, column 184: Attribute ```` placeholder ```` not allowed on element ```` input ```` at this point.
* line 74, column 186: Attribute ```` placeholder ```` not allowed on element ```` input ```` at this point.
* line 80, column 184: Attribute ```` placeholder ```` not allowed on element ```` input ```` at this point.
* line 85, column 186: Attribute ```` placeholder ```` not allowed on element ```` input ```` at this point.
* line 78, column 102: The ```` for ```` attribute of the ```` label ```` element must refer to a form control.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
After fixing your one bad `for` and removing the apparently-invalid `placeholder=""`s: http://jsfiddle.net/1ggbdL8x/7/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/1ggbdL8x/7/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 40, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 51, column 25: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 54, column 395: [E036](https://github.com/twbs/bootlint/wiki/E036): Having multiple `.btn`s inside of a single `.input-group-btn` is not supported
* line 54, column 267: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 54, column 395: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Closing until an updated example with no Bootlint problems is posted.

**Comment by caBBAlainB** [comment]
Hi cvrebert,
the fiddle http://jsfiddle.net/suunt549/9/ is working because I surrounded the code inserted lines 51-131 by a <div class="row">

which was not the case here: http://jsfiddle.net/suunt549/6/

but to get the problem, you have to move the vertical divider on the left to let bootstrap to add the 3 empty columns on left.
