### ISSUE TITLE
Pagination link right border is cut off on hover

### ISSUE THREAD

**Issue by sqal** [twbs/bootstrap#15976]
Due the negative -1px left margin applied on href link/span, right border is cut off when we hover over an element. Seems like there needs to be added z-index.

Issue example: http://jsfiddle.net/46s0ys7t/

**Comment by oktalk** [comment]
+1

This would be an easy fix too. In the `pagination.less` file, elements with the `.active` class already get a `z-index` bump. The same thing just needs to be applied to the hover and focus states.
