### ISSUE TITLE
Multiple bootstrap dialog scrolling issue.

### ISSUE THREAD

**Issue by hpatelpspl** [twbs/bootstrap#15992]
The scenario is. I have my main page where i already have scrolling. Where i am opening one bootstrap dialogue which is also bigger and the scroll is showing and scrolling the dialogue. In this big dialogue i have opened one more dialogue which is smaller one which remove the scroll. after i close this small dialogue the scroll is coming back on the back but it is not scrolling the dialogue. The scroll is working for the main page.

So how to handle this situation?

Thank you in Advance.

Hrushikesh

**Comment by cvrebert** [comment]
Assuming you mean multiple modal dialogs, Bootstrap explicitly does not support having multiple modals open at once: http://getbootstrap.com/javascript/#callout-stacked-modals

**Comment by hpatelpspl** [comment]
As per that i have written custom code as below:
 $("#btnAddPerson").click(function (e) {
        e.preventDefault();
        var href = '@Url.Action("AddPerson", "Common")';
        $('#addPersonDialogWindow').html("");
        $('#addPersonDialogWindow').load(href);
        $('#addPersonDialogWindow').modal({ show: true });
    });
$('#addOrgDialogWindow').on('hidden.bs.modal', function (e) {
        e.stopPropagation();

    });

**Comment by cvrebert** [comment]
We are unable to assist with the writing or debugging of such custom code on this issue tracker. Please direct your question to StackOverflow (or similar) instead. Thanks!

**Comment by NYPD** [comment]
Something I am curious about, it seems like half the issues opened up are related to multiple modals on a page. With so many issues has there been any thought, perhaps in v4, to support multiple modals or is this not supported for a design reason?

**Comment by kkirsche** [comment]
It's my understanding that the main reason these aren't supported is that they can not be made accessible in a clear manner for screen readers and other assistive technologies.

**Comment by cvrebert** [comment]
Due to implementation difficulty (chiefly CSS and event handling), it's not currently under consideration for v4. mdo also cited bad UX in one of the issues where the feature was canonically rejected, although that was quite a while ago.

**Comment by DenisAlliswell** [comment]
For those who are still facing this issue/limitation.

Workaround 1:
```
$('.modal').on('hidden.bs.modal', (e) => {
    $('body').addClass('modal-open');
});
```

If this not helping, here's workaround 2:
```
$('.modal').on("hidden.bs.modal", function (e) {
    if($('.modal:visible').length)
    {
        $('.modal-backdrop').first().css('z-index', parseInt($('.modal:visible').last().css('z-index')) - 10);
        $('body').addClass('modal-open');
    }
}).on("show.bs.modal", function (e) {
    if($('.modal:visible').length)
    {
        $('.modal-backdrop.in').first().css('z-index', parseInt($('.modal:visible').last().css('z-index')) + 10);
        $(this).css('z-index', parseInt($('.modal-backdrop.in').first().css('z-index')) + 10);
    }
});
```

Credits to [this blog](https://vijayasankarn.wordpress.com/2017/02/24/quick-fix-scrolling-and-focus-when-multiple-bootstrap-modals-are-open/)
