### ISSUE TITLE
Pseudo-class :hover styles should also be enabled with the class selector .hover

### ISSUE THREAD

**Issue by jamesrom** [twbs/bootstrap#15991]
It's not uncommon to have to enable the hover state of an element, even if the element isn't actually being hovered. For example, highlighting multiple related table rows, showing a link/button that will be pressed when a user performs an action, or the need to activate hover states if you have custom mouse/keyboard input.

Adding `.hover` to any selectors that implement `:hover` will allow elements to manually activated with js.

The current workaround involves copying the style and manually implementing `.hover`.

It would be a nice, relatively simple feature that will resolve this common anti-pattern.

Note: Psuedo-classes `:active` and `:focus` have `.active` and `.focus` respectively already for buttons. So you can style a button as being active or focused even if they aren't, so I believe it makes sense to style a button as being hovered too.

**Comment by kkirsche** [comment]
If admins feel this is worthwhile I would be able to put together a PR for this

**Comment by jamesrom** [comment]
Looks good @kkirsche. Thanks!

**Comment by kkirsche** [comment]
My pleasure :smiley:

**Comment by StevenBlack** [comment]
:+1: but documentation tho?

**Comment by mdo** [comment]
`.focus` is used for our JS button behaviors and `.active` is used for our dropdowns. Currently we make no use of `.hover` and I'm not too keen on adding a bunch of duplicate selectors to our CSS on the chance folks might use them.

Moreover, we're not adding features to v3 anymore, if we indeed classify this as one.

**Comment by mdo** [comment]
Punting per my last comment.
