### ISSUE TITLE
Multiple modal problem

### ISSUE THREAD

**Issue by Epexa** [twbs/bootstrap#15995]
If the modal window is open, and there scrollbar, after the closure of the second modal disappears scrollbar.

Before open and close second modal:
![Image of Yaktocat](http://i58.tinypic.com/28jwaj9.jpg)
After open and close second modal:
![Image of Yaktocat](http://i57.tinypic.com/16kb78m.jpg)

[Example CodePen](http://codepen.io/pen/myjGVq)

My fix:
```javascript
var openModalsCount = 0;
$('.modal').on('shown.bs.modal', function() {
	openModalsCount++;
}).on('hidden.bs.modal', function() {
	openModalsCount--;
	if (openModalsCount > 0) $('body').addClass('modal-open');
});
```

**Comment by kkirsche** [comment]
Bootstrap explicitly does not support having multiple modals open at once: http://getbootstrap.com/javascript/#callout-stacked-modals

<blockquote>
<h4>Overlapping modals not supported</h4>
    <p>Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.</p>
</blockquote>

See: #15992, #15979, etc. which bring up this and other issues related to multiple modals.

**Comment by cvrebert** [comment]
What @kkirsche said.

**Comment by Daiverspb** [comment]
$('.modal').on('hidden.bs.modal',function(){
		if($('.modal').is('.in')){
			$('body').addClass('modal-open');
			$(window).resize();
		}
	});

**Comment by Epexa** [comment]
@Daiverspb thank U! Your example is better!

And what's the problem with the developers do support multiple windows...

**Comment by cvrebert** [comment]
@Epexa That might appear to work okay under casual inspection, but if you were to rigorously test it, particularly with regard to edge cases and proper accessibility support, we believe you'd find several bugs. Also, [we have a hard enough time as it is just making single modals work completely properly](https://github.com/twbs/bootstrap/issues?q=is%3Aopen+modal+is%3Aissue), so we do not wish to take on the additional maintenance burden of a "multiple modals" feature at this time.
