### ISSUE TITLE
Some widths of text in default navbar brand line wrap in safari.

### ISSUE THREAD

**Issue by stoz** [twbs/bootstrap#15998]
Placing the exact string of text shown in the example in the navbar-brand element causes the text to wrap to the next line in Safari 8.0.3 and 7.1.3.

Example http://www.bootply.com/vnpi3VQcE8

Edit: Updated example to use Bootstrap 3.3.2.

**Comment by twbs-lmvtfy** [comment]
Hi @stoz!

You appear to have posted a live example (http://s.bootply.com/render/ptZiGH1h3b), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1
* line 50, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Workaround: Use a non-breaking space:
`<a class="navbar-brand">Chelesa&nbsp;EBALE</a>`

**Comment by jh3y** [comment]
Another solution so a user doesn't have to include `&nbsp;` is to add `white-space: nowrap` to the `navbar-brand` class. That might be easier for consumption.

I'd be happy to put that in a change and submit a PR if it was deemed necessary.

@jh3y

**Comment by mdo** [comment]
Sounds like a rather strange browser bug, perhaps something to deal with pixel rounding? Odd that it only happens with that exact string. Just about anything else seems to work fine.

**Comment by cvrebert** [comment]
@mdo So, are we calling this a "you should use `&nbsp;` (or similar)" user error, or a Safari bug, or what?

**Comment by mdo** [comment]
Seems like a Safari bug to me honestly. There's no reason for that stuff to wrap.

**Comment by cvrebert** [comment]
Reported WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=144990

**Comment by cvrebert** [comment]
Filed Safari Radar: http://openradar.appspot.com/20950962

**Comment by cvrebert** [comment]
This has been fixed in WebKit Nightly as of r186963: http://wkbug.com/144990
