### ISSUE TITLE
Affix Bottom fired is wrong

### ISSUE THREAD

**Issue by redocs** [twbs/bootstrap#16002]
I have a problem with the Affix Bottom:

in this project: http://ricasoli.it/brolioescape/tour/percorsi-enogastronomici-tour-gran-cru-brolio/ i can't use the Affix Bottom because it's fired a pixel bottom the Affix Top ever... if i write 100 or 20 of affix bottom it's start when affix top start, why ?

**Comment by cvrebert** [comment]
Sorry, but we don't debug full production webpages. We'd need a reduced testcase (via [JS Bin](http://jsbin.com) or similar) to be able to help you.
Note that [there are several open Affix bugs](https://github.com/twbs/bootstrap/issues?q=is%3Aissue+is%3Aopen+affix); possibly one of them is about the problem you're experiencing?
If this isn't a duplicate bug and you post a *simple* JS Bin testcase, then we'll be happy to reopen this issue.
