### ISSUE TITLE
Tooltip's "hover focus" combination behaves strangely

### ISSUE THREAD

**Issue by redbmk** [twbs/bootstrap#16008]
I can create a workaround for this easily enough, but it seems like odd default behavior so I thought it should be filed as a bug. I would expect that if "hover focus" is used that the tooltip would be showing any time I am focused or hovered.

If I move the mouse over an input, it will display the tooltip. Clicking on it will focus, and it remains showing. Now if I move the mouse out then I am still focused, but the tooltip disappears. Similarly, if I hit tab to move the focus to another input without moving the mouse then I am still hovering over the first, but the tooltip disappears in this case as well.

https://jsfiddle.net/wkxanbfh/

**Comment by hnrch02** [comment]
PRs welcome.

**Comment by redbmk** [comment]
Here you go :smiley: 

This ended up moving the changes from aac0e16452301a4735a668dc228b6b084b2d63d0 around a bit and using a slightly different method to figure out if the tooltip was already showing, but the tests still pass and I'm not able to recreate the flicker with my code changes. I was working with some older code when I did my testing and had noticed the flicker as well. Might need a bit of tweaking if the new method re-introduces some flicker, but like I said I wasn't able to recreate it.

@sgonyea, does this break any of your changes as far as you can tell?

**Comment by redbmk** [comment]
@hnrch02 ,

Any chance this will get merged at some point? What kind of vetting is required first?

**Comment by kkirsche** [comment]
@redbmk my initial guess would be its waiting for fat (Jacob I believe) to review as he is head JS dev. I'm just guessing Though

**Comment by redbmk** [comment]
@kkirsche OK, thanks for the update. Just didn't want it to fall through the cracks.

**Comment by fat** [comment]
closing in favor of the related pr
