### ISSUE TITLE
border between differently colored buttons in .btn-group changes color on hover

### ISSUE THREAD

**Issue by icai** [twbs/bootstrap#16000]
Different color button in `btn-group` border flash, when hover.

![Uploading Video_button-group-issue.gif . . .]()

**Comment by cvrebert** [comment]
* Please post a JS Fiddle demonstrating the problem
* What OS and browser are you using?
* Your screencast failed to upload

**Comment by icai** [comment]
<li class="btn-group btn-group-sm">
		<a class="btn btn-white" title=""><span class="icon-drag-sm"></span><span class="interator">1</span></a>
		<a class="btn btn-danger" ><i class="fa fa-times"></i></a>
	</li>

@cvrebert window pc.

**Comment by cvrebert** [comment]
@icai What **version** of Windows? And **which browser?**

**Comment by cvrebert** [comment]
`btn-white` is not part of Bootstrap. We'll either need to see the code for it or need a modified example that doesn't involve it.

**Comment by icai** [comment]
@cvrebert  you can use `btn-default` to replace `btn-white`.

**Comment by cvrebert** [comment]
@icai Okay. Please answer my questions from https://github.com/twbs/bootstrap/issues/16000#issuecomment-77511971 too.

**Comment by icai** [comment]
@cvrebert window 7 and chrome the new one dev. 
-----
I thank the problem is that,I use A(sucess), B(danger) button to example. when hover A(first button) z-index equal 2 that layer make highter, some the border show in top,lead to B button border is hidden. if A and B button is the same type button, that clearly not a problem.

**Comment by cvrebert** [comment]
Okay, I finally understand what you're referring to:
![border-shot](https://cloud.githubusercontent.com/assets/419884/6540813/d065836c-c466-11e4-9066-f65388ea3058.gif)
(Note gray vertical bar that appears when hovering over the left button.)

I feel like this has been reported before, but my search-fu is failing me.
The "fix" that occurs to me would be to force all buttons in button groups to use the same border color (a gray perhaps?). But maybe @mdo has something better or has a reason why that's a bad idea.

**Comment by mdo** [comment]
Yeah, you'll need to override those things on your end if you're mixing and matching button variations in a button group. There's no easy way to account for that on our end.
