### ISSUE TITLE
Text Colors

### ISSUE THREAD

**Issue by azizcelikeri** [twbs/bootstrap#16013]
Hi,

When I customizing bootstrap using website(http://getbootstrap.com/customize), I relaized that text color classes(text-primary, text-info, text-danger,text-warning,text-success) stays default. It will be better if it changes according to my selected color in web customizer.

**Comment by cvrebert** [comment]
We'll need your `config.json` or your customizer URL (`http://getbootstrap.com/customize/?id=XXXX`)

**Comment by cvrebert** [comment]
Are you aware that `.text-success` uses `@state-success-text` rather than `@brand-success`? (And similarly for the other variants besides `primary`.)

**Comment by getsetbro** [comment]
There is not one for PRIMARY or MUTED.

**Comment by cvrebert** [comment]
Closing due to lack of response from OP.
