### ISSUE TITLE
Navbar change!

### ISSUE THREAD

**Issue by smhenriques** [twbs/bootstrap#16010]
Hi guys!
I am new to bootstrap. So problably this is a stupid question but here it goes... :)

I am using the Carousel template to make my thing. And I what that the navbar change when i scroll down.
When the caroussel is on the screen it stays with the navbar detached from the top, and when i scrolldown, it changes to 'navbar-fixed-top'.

Can any one help me??? :rotating_light:

**Comment by cvrebert** [comment]
As stated in our docs, please [direct how-to questions to StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3). This issue tracker is for bugs and feature requests only. Thanks!
