### ISSUE TITLE
Feature Request: Never-Leaving-Divs

### ISSUE THREAD

**Issue by penne12** [twbs/bootstrap#16019]
I have a request for a feature that might be cool: never-leaving-divs. This is for a div that can be at any point of the page, but it will never scroll off the top of the page.

**Comment by kkirsche** [comment]
Like a sticky header or the affix javascript component?

I don't think we could truly implement this as a stand alone component though as everyone would need a different location based on their page's design. With that said I personally feel that the affix JavaScript module does a good job of helping with that problem.

I appreciate the suggestion though and look forward to hearing what the admins have to say.

**Comment by nextgenthemes** [comment]
@kkirsche  what is the difference between his "never leaving div" and using affix correctly on a div? I say none.

What "suggestion" do you appreciate? And what do you want to hear from Admins? I want to hear "closed, use affix" Standalone component???

@penne12 Did you ever use affix? Tried to do what you want with it? Because all you need is a bit JS on the `offset:` to make it happen automatically on scroll out.

**Comment by cvrebert** [comment]
Thanks for the suggestion, but we'll pass for now. <3
Affix should cover most/all of your needs anyway.

**Comment by nextgenthemes** [comment]
@penne12 Is this http://jsbin.com/qinevavagu/1/edit?html,css,js,output what you mean?

**Comment by twbs-lmvtfy** [comment]
Hi @nextgenthemes!

You appear to have posted a live example (http://jsbin.com/qinevavagu/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by penne12** [comment]
Yes, @nextgenthemes, thanks anyways, @cvrebert
