### ISSUE TITLE
Where is v4 being developed?

### ISSUE THREAD

**Issue by alberto** [twbs/bootstrap#16029]
I can't find a branch/repo or any ongoing discussion on what will be included there. Is there such a place?

**Comment by kkirsche** [comment]
It has not been made public yet.

**Comment by mdo** [comment]
Privately in another repo for now. Once we alpha, we'll have a branch.

**Comment by cvrebert** [comment]
http://blog.getbootstrap.com/2014/10/29/bootstrap-3-3-0-released/ gives some of our plans. Other than that, it's up in the air.
As @kkirsche said, the code itself is currently private.
If you have a specific suggestion for v4, feel free to open an issue (after searching for duplicates first).

**Comment by alberto** [comment]
Thanks. @cvrebert I had already seen that post, and found it promising how it addresses some of my pain points with bootstrap. I'll create issues for the remaining ones. Since more than "a couple weeks" went by, I thought there would be something up somewhere by now and I wanted to have a peek beforehand to avoid creating unnecessary noise.

**Comment by cvrebert** [comment]
Yeah, the estimate in that blog post was very overoptimistic.

**Comment by mdo** [comment]
> very overoptimistic

My bad :grin:.
