### ISSUE TITLE
Dropdown Navbar Parent Tab displays "expand child menu" when clicked

### ISSUE THREAD

**Issue by markmadedesign** [twbs/bootstrap#16026]
Instead of displaying the normal tab label like it should. Can anyone explain why this would be occurring? Example website below:

www.bethpagecamp.com/ ("Groups" tab)

Hopefully others have experienced this before so this issue doesn't fall under "personal requests" and will get some attention / feedback.

**Comment by patrickhlauke** [comment]
If it's not related to how the core Bootstrap component works/doesn't work, and is specific to how you implemented it on your site (and btw, that link doesn't have any tabs or anything else, so nuking it), then it *is* a personal request, which I'd suggest you take to some place like StackOverflow.

**Comment by markmadedesign** [comment]
Ok. Sorry I provided the wrong link by accident. Meant this - www.bethpagecamp.com/home/

I tried StackOverflow and no one has responded to my request. I figured it might relate to the core framework since it's showing "expand child menu" as the tab and I figured that might be a default action when something else isn't working. Sorry for any inconvenience.

Thanks,
Mark


MarkMadeDesign.com
--------------------------------------------
markmadedesign@gmail.com

**Comment by patrickhlauke** [comment]
your problem is not related to Bootstrap core, but to whatever it is you're doing in http://www.bethpagecamp.com/wp-content/themes/bethpage2015/js/functions.js?ver=20141212

**Comment by markmadedesign** [comment]
Much appreciation for that last response because that led me to the problem and disabling the top piece of code starting with...

$( '.dropdown-toggle' ).click( function( e ) {

...has resolved the issue. I also just read an article about why Bootstrap shouldn't be used w/ Wordpress theme development. Good to know. Sorry again for disrupting the forum.

Thanks,
Mark

http://www.bethpagecamp.com/home/


MarkMadeDesign.com
--------------------------------------------
markmadedesign@gmail.com
