### ISSUE TITLE
bootstrap-theme.css overrides well component border-color

### ISSUE THREAD

**Issue by oshsama** [twbs/bootstrap#16025]
The bug is that the <code>border-color</code> of a component well is not honoured and after generating is overridden by <code>bootstrap-theme.css</code> to mixin of the background instead of chosen <code>@well-border</code>.
The issue seems to be in the <code>theme.less</code> file (second line of <code>.well</code> properties):
<pre>.well {
  #gradient > .vertical(@start-color: darken(@well-bg, 5%); @end-color: @well-bg);
  border-color: darken(@well-bg, 10%); // <- where does that come from?
  @shadow: inset 0 1px 3px rgba(0,0,0,.05), 0 1px 0 rgba(255,255,255,.1);
  .box-shadow(@shadow);
}</pre>
This overrides the chosen colour which is defined in <code>bootstrap.css</code> as desired.

To reproduce:
1. Go to http://getbootstrap.com/customize/#wells and change just the colours of the well components (e.g. background - yellow, border - red)
2. Compile and download
3. Use it in your code, like:
<pre>&lt;!DOCTYPE html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;WELL not working too well&lt;/title&gt;
        &lt;meta charset="UTF-8"&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
        &lt;link rel="stylesheet" href="css/bootstrap.min.css"&gt;
        &lt;link rel="stylesheet" href="css/bootstrap-theme.min.css"&gt;
        &lt;script src="js/bootstrap.min.js"&gt;&lt;/script&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;div class="container"&gt;
            &lt;div class="well well-sm"&gt;
                in a small well
            &lt;/div&gt;
            &lt;div class="well"&gt;
                in a regular well
            &lt;/di&gt;
            &lt;div class="well well-lg"&gt;
                in a large well
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/body&gt;
&lt;/html&gt;</pre>
Removing <code>boostrap-theme.css</code> obviously fixes that, but that's beyond the point.

**Comment by oktalk** [comment]
That is intentional. The purpose of that `theme.less` file is to illustrate how you can easily override the default components.

**Comment by jcvaldes** [comment]
![plane](https://user-images.githubusercontent.com/2944428/33134871-9f43e6e4-cf7f-11e7-864f-3031e3511cb9.jpg)
