### ISSUE TITLE
Missing Glyphicons?

### ISSUE THREAD

**Issue by DerekFoulk** [twbs/bootstrap#16031]
I have been having issues with glyphicons lately. Namely the '.glyphicon-triangle-X'. There are others that don't work as expected. I will note that I am running Linux Mint (not windows) so there maybe some reason my OS has issues with them (I don't know). Regardless, when I use the aforementioned glyphicons, I see a circle/dot with a '3' or a '2' in the center (instead of the triangle(s)).

**I use the following to create glyphicons:**
```
<span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
```

***Another note:*** The bootstrap files used in my site were obtained via the GitHub repo. Built as instructed (unmodified).

**Comment by cvrebert** [comment]
* What browser and version?
* What version of Bootstrap?
* Please post a JS Fiddle of your example.
* Please note that Bootstrap only unofficially supports non-Android Linux.

**Comment by DerekFoulk** [comment]
Of course, sorry, I was in a hurry to get off.

**Browser** Chrome 41.0.2272.76-1
**Bootstrap** v3.3.2
I'll make a jsFiddle in the am when I get back to my machine...
**OS** Linux Mint 17.1

**Comment by cvrebert** [comment]
JS Fiddle: http://jsfiddle.net/74jhk5a5/

**Comment by cvrebert** [comment]
I am unable to reproduce the issue with Chrome v40, v41.0.2272.35, or v42.0.2311.22 on Linux via Sauce Labs using my JS Fiddle.
Either there is some error with how you setup Bootstrap's files on your server, or there is some bug specific to your Linux distro/packages.
Consult StackOverflow (or similar) for help with the former; we are unable to provide help with server environment troubleshooting on this issue tracker.
If it's the latter, please file a bug with your Linux vendor and/or [the Chromium project](http://crbug.com/new).
Thanks!

**Comment by DerekFoulk** [comment]
I will build Bootstrap again and see if the problem is still there. I will also check this on a Windows OS with various browsers. If I can't replicate in Windows, then there is a chance that there is an issue with the ttf-mscorefonts package (or something like that)... However, not your issue if that is the case :) 
Thanks Chris!

**Comment by DerekFoulk** [comment]
The problem was with the /Fonts directory provided by Initializr (Bootstrap version). It is missing the 'glyphicons-halflings-regular.woff2' file. I rebuilt bootstrap and replaced everything (/css, /js, /fonts) with the new files, and it fixed this issue...

**Comment by cvrebert** [comment]
@DerekFoulk Cool, could you please [file an Initializr bug](https://github.com/verekia/initializr/issues)? Thanks!

**Comment by DerekFoulk** [comment]
Will do! Thanks again Chris...

**Comment by DerekFoulk** [comment]
Reference [Initializr Issue #92](https://github.com/verekia/initializr/issues/92)
