### ISSUE TITLE
Screen sizes are outdated for mobile

### ISSUE THREAD

**Issue by elwayman02** [twbs/bootstrap#16032]
Currently the mobile-first design variables are set up at a max of 768px for mobile and 992px for tablet.  However, modern smartphones such as the iPhone 6 or HTC One m8 actually render at a pixel resolution of over 1080px.  That means that if you are relying on Bootstrap's features (such as navbar collapse) to convert to mobile appropriately, it will instead look like the desktop version on these phones.

**Comment by cvrebert** [comment]
Erm, per http://viewportsizes.com/?filter=iphone , the iPhone 6 Plus's viewport is 414x736 in CSS px, not 1000px. Also, I don't know where you're getting 400px from; the extra-small (phone) breakpoint covers anything < 768px.

**Comment by kkirsche** [comment]
I believe some of this will be fixed with Bootstrap V4 when released but I could be wrong.

**Comment by elwayman02** [comment]
@cvrebert those are device pixels, not CSS pixels.  The phones actually cram CSS pixels into the device pixels at a more than 2:1 ratio, primarily so as to be able to better display wide websites where the developers did not consider mobile in their design.

**Comment by cvrebert** [comment]
@kkirsche You are correct that any adjustment of the grid system's breakpoint ranges would have to wait until Bootstrap v4, due to backward compatibility constraints.

When will [`@media (pointer: coarse)`](http://dev.w3.org/csswg/mediaqueries-4/#pointer) finally become a thing...

**Comment by elwayman02** [comment]
Alright.  I'm using the SASS version of bootstrap, so the workaround was fairly simple:

https://github.com/elwayman02/jordan-hawker/blob/master/app/styles/bootstrap-variables.scss

I'm not sure if it's that easy for the CSS/LESS version, because I'm taking advantage of the !default feature in SASS.  You'd have to override a lot of other variables to make the LESS version work, I think.

**Comment by cvrebert** [comment]
No, you just have to adjust them in variables.less instead of in a separate file.

**Comment by elwayman02** [comment]
That would require actually forking and deviating from the project.  That's not really a sustainable solution for a production application (as I found out after inheriting maintenance of a BS2 fork a few months ago).

**Comment by patrickhlauke** [comment]
I will add here that the number of physical pixels in these devices is irrelevant, as you will always deal with just CSS pixels - that's the whole cornerstone of responsive web design: you tell the browser to use ``width=device-width``, and that normalises the display regardless of pixel density and number of physical pixels.

If you somehow try to force mobiles/tablets to match CSS pixels to actual physical pixels, you're going to have a bad time being responsive, and you'll end up with text/content that is far too small for anything but the smallest old screens (pre-retina iPhone etc). Unless you were planning to also bump up font sizes etc in your media queries for large screens...at which point, you're chasing your own tail.

**Comment by patrickhlauke** [comment]
>  Samsung Galaxy S6 will have a CSS width of 1440px,

no it won't. it has 2560x1440 physical pixels, 577ppi actual screen density...but once you load a webpage, I can guarantee you that it will not be 1440px wide. Without any viewport meta element, it's likely going to fall somewhere along the 800-980px width, and once you set ``width=device-width`` meta it will likely settle for a width somewhere around, i'd expect, 320-500px. again, this is the whole basis of using RWD and telling devices to choose their "ideal viewport" (a term coined by PPK, see http://www.quirksmode.org/mobile/metaviewport/)

**Comment by elwayman02** [comment]
In practice it isn't working as you've described.  Given the proper meta tag and a modern device, the media queries in bootstrap will not trigger appropriately for mobile. I have tested this today and had to apply the workaround to get the proper behavior.

**Comment by patrickhlauke** [comment]
please provide a test link to show that.
FWIW, here's a site i maintain, using bootstrap, on a nexus 5 which runs at 1080x1920 physical pixels, which with ``width=device-width`` actually has a viewport of 360x640.
![screenshot_2015-01-20-10-32-33](https://cloud.githubusercontent.com/assets/895831/6572078/f17ae59a-c706-11e4-85fe-469627af7274.png)

**Comment by elwayman02** [comment]
My website, www.jordanhawker.com, had this issue. The workaround is deployed at the moment, but I can roll it back sometime tomorrow to show you.  I tested on an HTC One m8, btw. 

The code for this site is public on my github as well, so you can see it for yourself.  I'll update here when I've deployed the rollback.

**Comment by patrickhlauke** [comment]
I'll hazard a guess that you're missing the viewport meta on your actual page that then embeds your heroku page as a frame...

**Comment by elwayman02** [comment]
Actually, @patrickhlauke I just rolled it back.  If the media queries and CSS pixels are working as you said, you would see a horizontal navbar on a mobile device.  On desktop, you have a vertical navbar on the left side of the page.

**Comment by elwayman02** [comment]
Hmm, that might be it. Thanks for the tip. I will investigate.

**Comment by patrickhlauke** [comment]
it is that. add the meta viewport to the page with the frameset.
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
  <head>
    <title>Jordan Hawker</title>
    <META name="keywords" content="developer, jordan, hawker, dance, dancer, dj">    <meta HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
  </head>
  
  <frameset>
    <frame marginwidth=0 marginheight=0 frameborder=0 name="TOPFRAME" src="https://jordan-hawker.herokuapp.com/" noresize>
  </frameset>
</html>
```

![jordan](https://cloud.githubusercontent.com/assets/895831/6572448/44edfd22-c70a-11e4-952d-e9c7d58b4056.png)

**Comment by nrogers64** [comment]
@elwayman02 According to http://www.canbike.org/CSSpixels/ , the Samsung Galaxy S6 has a resolution (in CSS pixels) of 360x640.

**Comment by elwayman02** [comment]
@patrickhlauke had it right.

**Comment by cvrebert** [comment]
Reviewing the grid breakpoint sizes is already on the list of action items for Bootstrap v4.
