### ISSUE TITLE
glyphicons font notworking after compile sass file with codekit 

### ISSUE THREAD

**Issue by soroushm** [twbs/bootstrap#16035]
glyphicons font notworking after compile sass file with codekit i`m resarch and find but with flyphicons sass file !!!

in glyphicons.scss missing "" after and prefix of content style 

i'm create a patch and uploaded this link please fixed it
http://up.soroush.co/issue/glyphicons_scss.patch

**Comment by patrickhlauke** [comment]
This is related to Bootstrap for Sass, not Bootstrap itself. Please file this issue over there https://github.com/twbs/bootstrap-sass

**Comment by cvrebert** [comment]
@soroushm You presumably need to upgrade to bootstrap-sass v3.3.3; see https://github.com/twbs/bootstrap-sass/commit/daeb43dcc7b0ab06328acaca0549ee68c039aaa6
