### ISSUE TITLE
In all browsers, responsive table overflows when dropdown from last row of table is triggered

### ISSUE THREAD

**Issue by micahknox** [twbs/bootstrap#16038]
It appears the changes to the "table-responsive" class creates an automatic overflow for all media sizes in version 3.3.2. I like to use dropdowns inside of table rows to hold actions that can be performed against a row of data. In the case where a dropdown is triggered near the end of the table, the table overflows and the dropdown cannot be seen unless you scroll down. This is more of a usability issue than a bug but I thought it was work reporting. Here's the JSBin showing the behavior: http://jsbin.com/kufofujoja/2/.

![screen shot 2015-03-10 at 9 25 07 am](https://cloud.githubusercontent.com/assets/6165412/6576773/64654d52-c707-11e4-8b49-f18dd177b44e.png)

**Comment by cvrebert** [comment]
Confirmed in OS X Chrome.

**Comment by kushalpandya** [comment]
Only workaround for the issue is to have `dropup` class applied to the last row's dropdown.

**Comment by Blucezhang** [comment]
the bootstrap is a good tools,I always used it,

发自我的 iPhone

**Comment by micahknox** [comment]
@kushalpandya Not a bad idea although the height of the dropdown plays into. If there are many options in the dropdown for the last few rows of the table, you would need to add `dropup` to the dropdown of several rows.

**Comment by jh3y** [comment]
A solution to this could be to have something similar to how tooltips work and have an option to attach the dropdown to the body therefore being able to use absolute positioning and not have to worry about the overflow property of parent containers?

I'm looking for issues so I can get into contributing so I'd be happy to work on this if a solution is agreed.

@jh3y

**Comment by micahknox** [comment]
@jh3y That solution works for me. Thanks!

**Comment by jh3y** [comment]
I'm happy to start working on this if it could be an accepted solution for a PR.

@jh3y

**Comment by mdo** [comment]
We likely won't be accepting something like that in v3—no new features are being added at this time.

I'd like to revisit the dropdown positioning for v4 to do just that though, but we'll see how and if that can happen in the release. No idea yet on that particular feature.

**Comment by jh3y** [comment]
Ah right ok, thanks @mdo.

I'm looking to get involved contributing to the project in some way, so if there's an opportunity to add this in v4, I'd be happy to get involved.

@jh3y

**Comment by fabiannydegger** [comment]
If your dropdown isn't very big add:
**style="padding-bottom : 75px;"**
to the table
You lose some space and it doesn't look great, but it works.
