### ISSUE TITLE
cant overrite button-variant mixin without change bootstrap sass file

### ISSUE THREAD

**Issue by soroushm** [twbs/bootstrap#16034]
HI

i'm needs change somethings  in this mixin i'm try to overwrite in other sass file but not working
please give me a solution without change bootstrap file

this is my structure 
//Bootstrap
@import "bootstrap/_bootstrap";

// my mixin
@import "mixins/_buttons";

**Comment by cvrebert** [comment]
Personal support/how-to questions are outside the scope of this issue tracker, which is for bug reports and feature requests only.
Try asking on one of these forums (or similar) instead:
* http://stackoverflow.com/questions/tagged/twitter-bootstrap-3
* http://stackoverflow.com/questions/tagged/sass
* https://groups.google.com/forum/#!forum/sass-lang

Thanks!
