### ISSUE TITLE
Less hooks

### ISSUE THREAD

**Issue by zslabs** [twbs/bootstrap#16041]
I'd like to propose the use of Less hooks in Bootstrap. [Here's an example](http://codepen.io/zslabs/pen/RNebLq). This is done throughout the [UIkit framework](https://github.com/uikit/uikit). It means when you need to hook into Bootstrap selectors to either add or override functionality, you don't have extra selectors hanging around.

What this means is a smarter, more extendable system that ends up being smaller than if you were to do it the old fashioned way. I'd be happy to start an initiative to get this into the core, as it would be quite an effort with the number of selectors. We could start in smaller pockets if necessary.

I encourage you to play around with the Codepen I linked to so see how the final output looks. Thanks!

**Comment by cvrebert** [comment]
We're kinda trying to avoid major changes to v3 at this point, given that v4 is already in development and keeping the branches synced is tedious. Also, how would this play out for [bootstrap-sass](https://github.com/twbs/bootstrap-sass)'s autoconversion?

**Comment by zslabs** [comment]
Hey @cvrebert I'd honestly have to defer to [UIkit's gulp task](https://github.com/uikit/uikit/blob/master/gulpfile.js#L269-L342) that handles the SASS conversion as I don't personally use SASS, but will dig in and see what I find.

**Comment by zslabs** [comment]
It looks like they split them off into their own mixin file https://github.com/uikit/bower-uikit/tree/master/scss and you'd interact with them before you load in the framework.

**Comment by mdo** [comment]
That's one way to do it, yeah, but it's a huge abstraction and deviation from how things current work (as @cvrebert mentioned). Regarding the Gulp task, while we have our own Gruntfile, it's possible to compile Bootstrap with other tools and flows. I'd rather not have something that specific as a requirement for anyone to compile our code on their own.

I see the benefit, but I think the overhead would be too great for us right now. I would love to simplify compiled styles for folks, but not in this manner.
