### ISSUE TITLE
How to use popover javascript plugin for remote data

### ISSUE THREAD

**Issue by xiaohan2013** [twbs/bootstrap#16048]
$("#receipts-image").delegate(".approval-advice","click",function(e){
        e.stopPropagation();
        // var rid = $.trim($($(e.target).parentsUntil("#receipts-image")[4]).attr("data-receipt"));
        var rid = click_rid = e.target.id.substring(8);

        $(this).popover({
            content:rid,
            html:true,
            container:this
        });
}

if I code like this , don't know why popover appear after trigger click event twice at the time of page initialization

**Comment by cvrebert** [comment]
Please direct how-to questions to StackOverflow (or other similar forums) instead of the bug tracker. Thanks!
