### ISSUE TITLE
Affix - data-offset-bottom break affix when scrolled to the bottom

### ISSUE THREAD

**Issue by stefek99** [twbs/bootstrap#16045]
Fiddle: http://jsfiddle.net/stefek99/0o15homy/

Demo: http://youtu.be/4XAKdwazxFo (less than a minute)

I've noticed couple of existing Affix issues, not sure if mine is a duplicate.

**Comment by bsbak** [comment]
http://jsfiddle.net/0o15homy/1/ - here without bug, enjoy.

**Comment by zacechola** [comment]
You have a `data-offset-bottom` attribute set.

From the documentation:

>If a bottom offset is defined, scrolling past it should replace `.affix` with `.affix-bottom`. Since offsets are optional, setting one requires you to set the appropriate CSS. In this case, add `position: absolute;` when necessary. The plugin uses the data attribute or JavaScript option to determine where to position the element from there.

That said, the docs could clarify this a bit better if `data-offset-bottom` is going to be set in the example code.

**Comment by stefek99** [comment]
HMMM...

I was hoping that:
* if I scroll down and pass certain threshold the sidebar is fixed
* if sidebar is larger than screen size it will be fixed to the bottom 

(I'll try to figure it out)

**Comment by fat** [comment]
Yeah this plugin is a bit confusing – i really effed up on the api for this plugin, that's my bad.

Expect a better solution for v4

**Comment by mdo** [comment]
Punt on this until then @fat?

**Comment by fat** [comment]
yep

**Comment by BeInventive** [comment]
I made a work around
```
$("[data-offset-top]").on("affixed.bs.affix",function () {
  $(this).removeAttr("style");
});
```
http://jsfiddle.net/983vjtn8/2/
