### ISSUE TITLE
Fix: Scrollbar fix on modal('hide');

### ISSUE THREAD

**Issue by jsonjuri** [twbs/bootstrap#16040]
I found a bug when hide the modal with modal('hide') the modal-open will not be removed from the body this will not bring back the scrollbar, fix is 
After: Event("hide.bs.modal"),
i add: this.$body.removeClass("modal-open"),
I fixed it in the .min file, so need also fix in normal file :+1:

I think somewhere in Modal.prototype.hide = function (e) {}

**Comment by cvrebert** [comment]
What version of Bootstrap are you using?
What OS and browser are you using?
Can you post a JS Fiddle of the bug and describe how to reproduce it?

**Comment by cvrebert** [comment]
@jsonjuri Our JS already does what you're suggesting:
https://github.com/twbs/bootstrap/blob/ba1345f144283d579b07cd40b5ae5a5b84d2b2e7/js/modal.js#L174
https://github.com/twbs/bootstrap/blob/ba1345f144283d579b07cd40b5ae5a5b84d2b2e7/js/modal.js#L137

**Comment by cvrebert** [comment]
Closing due to lack of response.

**Comment by russplaysguitar** [comment]
Possibly related: https://github.com/twbs/bootstrap/issues/16469
