### ISSUE TITLE
btn border cut off in chrome

### ISSUE THREAD

**Issue by danfitz36** [twbs/bootstrap#16053]
when btns are text-aligned or floated right, position:relative and overflow:hidden are causing the button border to get cut off slightly. if i remove either property, the border shows again.

**Comment by kkirsche** [comment]
Can you post your OS, browser and JSBin example of the problem?

**Comment by danfitz36** [comment]
I found the issue and it was with an integration with google material ripple.

**Comment by cvrebert** [comment]
@kkirsche Nice work triaging there, tiger :smile_cat:
