### ISSUE TITLE
speedup tab switch on iOS

### ISSUE THREAD

**Issue by dongyuwei** [twbs/bootstrap#16055]
in bootstrap/js/tab.js 

please change the code
```
$(document)
    .on('click.bs.tab.data-api', '[data-toggle="tab"]', clickHandler)
    .on('click.bs.tab.data-api', '[data-toggle="pill"]', clickHandler)
```
to 

```
$(document)
    .on('touchstart.bs.tab.data-api click.bs.tab.data-api', '[data-toggle="tab"]', clickHandler)
    .on('click.bs.tab.data-api', '[data-toggle="pill"]', clickHandler)
```

**Comment by patrickhlauke** [comment]
While this probably works great on iOS (which magically suppresses ``click`` if a touch interaction resulted in a change of layout - see figure 6.4 on https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html), on other OSs this will result in the handler firing twice (once for ``touchstart``, once 300ms later for the ``click`` mouse compatibility event). In the specific case of tabs, this may not be a problem, but I'd be careful with creeping this approach into the core code.
/cc @mdo @cvrebert ?

**Comment by cvrebert** [comment]
Per http://developer.telerik.com/featured/300-ms-click-delay-ios-8/ , this only makes a difference on iOS, and in iOS 8+ this only affects "fast" taps. And anyway I'd feel better about recommending a more complete solution like FastClick rather than this ad-hoc approach.

**Comment by patrickhlauke** [comment]
Ah, indeed, the viewport ``meta`` on mobile will already take care of speeding things up on Android/Chrome, Android/Firefox and WinPhone8.1/IE http://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay

So yes, this optimisation is effectively only targetting iOS (and probably still double-fired the handler on other platforms). Agree that this should be taken care of by a more holistic, but separate, solution.

**Comment by cvrebert** [comment]
Okay, closing as WontFix then.
