### ISSUE TITLE
bootstrap.min.css (bootstrap-3.3.2-dist)

### ISSUE THREAD

**Issue by odillepa** [twbs/bootstrap#16059]
Hi,

In bootstrap.min.css (bootstrap-3.3.2-dist) i see this:
.navbar-brand>img{display:block}

But must be:
.navbar-brand:img{display:block}

Right?

Regards!

**Comment by kkirsche** [comment]
I don't believe that's correct. It would be `> img` because the image tag goes inside of nav bar brand. Image isn't a pseudo class or state of CSS in this case

**Comment by cvrebert** [comment]
`:img` is indeed absurd. Presumably you meant `img.navbar-brand`, but per http://getbootstrap.com/components/#navbar-brand-image , the `<img>` should be within the `<a class="navbar-brand">`, as opposed to being `<img class="navbar-brand">`.
