### ISSUE TITLE
.badge within .btn-primary within .panel-default>.panel-heading using wrong style

### ISSUE THREAD

**Issue by colincameron** [twbs/bootstrap#16057]
I have a button inside a panel heading, and the button has a badge on it. The badge is being styled based on being inside the panel heading rather than based on being inside the button, i.e. this rule:

    .panel-default>.panel-heading .badge{color:#f5f5f5;background-color:#333}

is taking precedence over this rule:

    .btn-primary .badge{color:#337ab7;background-color:#fff}

This is causing my badge to look like this:

![screenshot 2015-03-13 12 32 53](https://cloud.githubusercontent.com/assets/1846118/6638369/1f9bae78-c97d-11e4-8313-17204ec37d44.png)

[Code example here.](http://jsbin.com/pubuvixuko/1/edit?html,output)

Of course, I can add the correct colour styling manually to the span to solve my immediate problem, but I would suggest that the styles for badges within button types are moved to later in the CSS file than the styles for badges within panel headers.

**Comment by twbs-lmvtfy** [comment]
Hi @colincameron!

You appear to have posted a live example (http://jsbin.com/pubuvixuko/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 25, column 11: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by colincameron** [comment]
Code sample updated in JS Bin to include button type.

**Comment by zacechola** [comment]
This is related to discussions in issue #13686 and PR #13687.

**Comment by mdo** [comment]
We can't really scope these styles any better. If we scope them with a `>` selector to make things more specific and prevent this inheritance, we screw up folks' implementations where they have even a single wrapping element around those badges.

Not sure we can address this in v3, so punting for now. Holler if anyone has any ideas though, save for overriding things one more time just for buttons.
