### ISSUE TITLE
event.stopPropagation does not work for a modal('show')

### ISSUE THREAD

**Issue by anthony-o** [twbs/bootstrap#16056]
Here is my fiddle : https://jsfiddle.net/3drpkwpk/14/

```html
<div>
    <div>
        <ul>
            <li>
                Just a test <button type="button" id="firstBtn">One</button>
                <button type="button" id="secondBtn">alert One</button>
                <div class="modal fade comment_One" tabindex="-1" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                Test One
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
```

```js
$('li').click(function() {
    alert('li');
});

$('#firstBtn').click(function(event) {
    event.stopPropagation();
    $('.comment_One').modal('show');
});

$('#secondBtn').click(function(event) {
    alert('secondBtn');
    event.stopPropagation();
});
```

If I click on the `li`, I have the alert "li", if I click on the second button, I have only the alert "secondBtn" but if I click on the first one, then, my modal shows, and when it disappears, the alert "li" is called !

Detected on http://stackoverflow.com/q/28896427/535203 and removed angular.

**Comment by twbs-lmvtfy** [comment]
Hi @anthony-o!

You appear to have posted a live example (https://fiddle.jshell.net/3drpkwpk/13/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 40, column 29: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 40, column 63: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1
* line 27, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by anthony-o** [comment]
Fixed all the issues, and still have the bug: https://jsfiddle.net/3drpkwpk/14/

**Comment by cvrebert** [comment]
The stopPropagation works fine and prevents the click event from the button as expected. What you're seeing is a separate click event entirely. (I would suggest you try logging the targets of the events next time.)
For example, click on the modal body itself after the modal is shown and note that "li" is alerted because you've put the modal as a descendant of the `<li>`. You're just seeing the same thing with the modal backdrop.
However, #15881 will move the backdrop element to be a child of the `<body>` in Bootstrap v3.3.4.

Note that we don't recommend cramming a modal under an `<li>` like this in the first place:
> ## Modal markup placement
> Always try to place a modal's HTML code in a top-level position in your document to avoid other components affecting the modal's appearance and/or functionality.

**Comment by anthony-o** [comment]
You're right, I didn't realized that, if I move the modal it's ok: https://jsfiddle.net/3drpkwpk/15/
