### ISSUE TITLE
 How to deal with uneven ordering of thumbnail and its caption in bootstrap?

### ISSUE THREAD

**Issue by evivz** [twbs/bootstrap#16061]
Demo: http://www.bootply.com/muMpOGTA6i I am trying to arrange products and their title (caption) in fluid way but due to uneven sizing of the title it gets ordered unevenly. How should I deal with it?
It turns more worse when opened in mobile size.

Thanks in advance.

**Comment by twbs-lmvtfy** [comment]
Hi @evivz!

You appear to have posted a live example (http://s.bootply.com/render/muMpOGTA6i%255B1), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 223, column 11: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 39, column 26: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Removing the extraneous "[1]" from your URL: http://www.bootply.com/muMpOGTA6i

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://s.bootply.com/render/muMpOGTA6i), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 223, column 11: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 39, column 26: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
You need to add clearfix divs as shown in http://getbootstrap.com/css/#grid-responsive-resets
Please direct how-to questions to StackOverflow in the future. Thanks!
