### ISSUE TITLE
inline forms don't wrap nicely

### ISSUE THREAD

**Issue by fplanque** [twbs/bootstrap#16064]
When you have multiple `form-group`s in an `inline-form` and they wrap on multiple lines, the inputs will touch each other (vertically).

Also I find the horizontal spacing between `form-group`s insufficient.

I'd like to propose the following CSS to fix this:

      .form-inline {
         margin: -5px -10px;
      }
      .form-inline .form-group {
         margin: 5px 10px;
      }

**Comment by mdo** [comment]
Inline forms aren't really meant for wrapping—they're meant for single lines of inputs. You'll need to space them out accordingly.

**Comment by fplanque** [comment]
Here's a use case on a set of filters. I do believe it's a valid use of a single line of inputs... which may run out of space:

![filter_bar](https://cloud.githubusercontent.com/assets/1156771/6654118/b00a2c0e-caaf-11e4-806c-ed2628787893.png)

which wraps to:

![wrapped](https://cloud.githubusercontent.com/assets/1156771/6654121/f1fe5342-caaf-11e4-8d28-22b71cc66172.png)

Without the fixes you would have gotten:

![meh](https://cloud.githubusercontent.com/assets/1156771/6654125/25bb7bce-cab0-11e4-9d2f-fc910aa65b68.png)

I thought that tiny little bit of CSS was improving the `inline-form` at a very cheap cost ;)

(but I won't be offended if you really don't like it ;)

**Comment by bradlis7** [comment]
+1
