### ISSUE TITLE
Add option to control Modal fade animation via JS

### ISSUE THREAD

**Issue by jvanasco** [twbs/bootstrap#16068]
I'd like to suggest this functionality to override fades in javascript:

    $('#modal').show({'fade': false});

Why?

It is currently painful to debug/troubleshoot a modal w/fade which is triggered by javascript. This is because `modal.show()` merely triggers the fade.  placing a `debugger;` line in the JS will show a screen without the modal.  so the `fade` needs to be removed on the modal's html.  Debugging might not be possible in a `shown`, because that event happens in a different scope.

This isn't terribly difficult to deal with, but adds a complicated step and one has to edit multiple things/files for testing.  It might not be easy to do (or a smart thing to do) depending on the development team or application -- the javascript could be managed separately from the html.

**Comment by kkirsche** [comment]
I don't think there would be any major api changes like that made to V3 as V4 is in development.

**Comment by cvrebert** [comment]
It's admittedly not documented, but since your only use case is debugging, I don't see much advantage over the existing `$.support.transition = false;` approach for disabling animations/transitions.

**Comment by jvanasco** [comment]
That totally handles it.  I can't think of any uses other than debugging.  Maybe this tip could go in the docs?

**Comment by cvrebert** [comment]
Cool, closing in favor of #16069 then.
