### ISSUE TITLE
bg-primary against list-group-item

### ISSUE THREAD

**Issue by humbertocruz** [twbs/bootstrap#16062]
Hello,

I'm trying to change the background of a list-group-item adding the class bg-primary to the LI element, but it's not working cause the list-group-item declaration is done after the bg-primary. Changing the order of then all is working nicely.

thanks
Humberto

**Comment by oktalk** [comment]
The docs state that sometimes this class will be overwritten, and so you may need to wrap the element in a container of sorts. You can read more about it here: http://getbootstrap.com/css/#dealing-with-specificity.

You should be using the classes: .list-group-item-success, .list-group-item-info, etc. to change the background of individual list group items.

The `.bg-primary` is an odd class on it's own. It assumes that the `@brand-primary` will always be contrasted to `#FFF` well enough to be readable on screen. That should probably change.

**Comment by mdo** [comment]
Yeah, this is a problem with our placement of the our utility classes in our compiled CSS. They *should* be after everything, but we can't fix that without potentially breaking folks' CSS. Not much we can do, but if you like, you can move those classes yourself without much problem I imagine.
