### ISSUE TITLE
Clicking into text input field within dropdown closes the dropdown

### ISSUE THREAD

**Issue by manudwarf** [twbs/bootstrap#16072]
Hi,

Please follow this JSfiddle for a live example: https://jsfiddle.net/znbtb8cp/1/

**Steps to reproduce:**
1. Click on the dropdown button
2. Click on the input field

**Expected behaviour:**
The field should be focused.

**Actual behaviour:**
The dropdown closes.

The project we are working on encountered this issue, and we have a workaround, but we are ready to provide a patch and a pull request with a better/long term solution if nobody has done it yet.

**Comment by twbs-lmvtfy** [comment]
Hi @manudwarf!

You appear to have posted a live example (https://fiddle.jshell.net/znbtb8cp/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 33, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by zacechola** [comment]
:+1:

I've run into this one in projects before. I swear this has come up in the issues before, though, but my searches are failing so maybe I'm thinking about work use of Bootstrap. 

¯\\\_(ツ)\_/¯
