### ISSUE TITLE
TypeError: this.$dialog is undefined

### ISSUE THREAD

**Issue by iyoba** [twbs/bootstrap#16076]
Hi,
Before this issue I use v3.3.2 it work perfect,
after update to v3.3.4 I found this error

TypeError: this.$dialog is undefined
this.$dialog.on('mousedown.dismiss.bs.modal', function () {
bootstrap.js (line 972, col 4)

TypeError: this.$dialog is undefined
this.$dialog.off('mousedown.dismiss.bs.modal')
bootstrap.js (line 1035, col 4)

I use Yii2 framework with this widget https://github.com/kartik-v/yii2-editable

**Comment by cvrebert** [comment]
Sorry, but we can't help you with problems involving third-party widgets. Try filing a bug at https://github.com/kartik-v/yii2-editable/issues instead.
