### ISSUE TITLE
helper classes should go at end of file for greater specificity

### ISSUE THREAD

**Issue by robertvasile** [twbs/bootstrap#16087]
let's say we need a custom popover-title, with a dangerous aspect :)

**expected:** add "bg-danger text-danger" to the "popover-title" h3 in a custom popover template

:-1: **result:** because of the helper definitions position in the .css file, the *bg-danger* helper class does not rewrite the default ones

:+1: **solution:** compile ALL the helper classes at the end of the style files

**Comment by zacechola** [comment]
Bin confirming: http://jsbin.com/wonivu/1/edit?html,js,output

**Comment by mdo** [comment]
I'm in agreement, but we can't really make that change yet in v3 I think. It'd present problems for folks who don't have the right files included right now. We'd have to move all those helpers from one file to another, and that'd potentially break folks' setups.
