### ISSUE TITLE
Bootstrap class="collapsed"

### ISSUE THREAD

**Issue by fpizarro54** [twbs/bootstrap#16096]
Is the class="collapsed" a typo?  I can't find the css for that class

**Comment by patrickhlauke** [comment]
Interesting - I'm not sure of the history behind it, but it seems that most of Bootstrap's example dropdown toggles have this class. Indeed you're right that none of the CSS currently targets that class. It seems that collapse.js does set/unset the class, but no styling applies to that. Maybe @mdo or @cvrebert know more?

**Comment by mdo** [comment]
We don't actually use it, but it gets applied I believe so folks can trigger off that.

**Comment by patrickhlauke** [comment]
As a side note @mdo, it seems currently ``.collapsed`` is not triggered for the main getbootstrap.com navigation button, nor for the navbar examples...will investigate why.
