### ISSUE TITLE
Dropdown menus not working in the navbar examples 

### ISSUE THREAD

**Issue by kkegans** [twbs/bootstrap#16091]
When using BS 3.3.4 with any of the NAVBAR examples the menu drop-downs when in a browser window of <792px do not seem to be working. Is this a problem, or am I doing something wrong?
![2015-03-17_11-36-19](https://cloud.githubusercontent.com/assets/11524544/6692299/f00b832a-cc99-11e4-8991-31667f6eea52.png)

**Comment by patrickhlauke** [comment]
That doesn't look like the default theme. Is it http://getbootstrap.com/examples/navbar-static-top/ ior have you added/modified things? In the latter case, you'll need to ask for advice about your specific modifications/additions on a forum like StackOverflow.

**Comment by cvrebert** [comment]
Also, you didn't state which OS and browser you're using.

**Comment by cvrebert** [comment]
None of the stock navbar examples use an inverse (dark) navbar like in the screenshot, so this doesn't appear to be a bug in Bootstrap itself. Closing until we get evidence to the contrary.
(I also checked IE8 on a hunch based on the lack of rounded corners, but our static top navbar example works fine there too.)
