### ISSUE TITLE
Arrow Keydown event triggers click event for all [role="menu]

### ISSUE THREAD

**Issue by chamelea** [twbs/bootstrap#16090]
I am writing my own aria menu object and handling the document click event differently than the document arrow keydown event. I was surprised when dropdown.js actually triggered a click event when I used the down arrow.

See:
https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L158
https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L72

**Comment by chamelea** [comment]
Sorry... hit enter before providing description...

I am writing my own aria menu object and handling the document click event differently than the document arrow keydown event.  I was surprised when dropdown.js actually triggered a click event when I used the down arrow.

**Comment by chamelea** [comment]
https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L158 && https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L72

**Comment by patrickhlauke** [comment]
It fires click in an attempt to keep the code DRY, as opening the menu hangs off the ``click`` event. So I'd say it's by design. If you're writing a custom object, you may have to override the behavior yourself (which I'm guessing you'd have to do anyway, if implementing your own handler?)

**Comment by chamelea** [comment]
Yeah - that's exactly how I'm working around it.  I wanted to call it out in case there was a way to better scope to just bootstrap dropdowns.  Thanks for the fast reply!

**Comment by patrickhlauke** [comment]
oh, now i see what you mean (re scoping to just bootstrap). that's actually an interesting idea (though it would probably require a lot of extra work to do that same kind of scoping explicitly for all components). @fat ?

**Comment by cvrebert** [comment]
The `[role="menu"]` event handler was added way back in https://github.com/twbs/bootstrap/commit/9889948f5851f5ce19668073b1f88eb4b6082ea6#diff-8a0a7067ead1e0530699852517369ddaR149 without much explanation.
Perhaps we could just use `.dropdown-menu` as the selector instead?

**Comment by patrickhlauke** [comment]
i think that would make sense (also in light of parallel discussions in https://github.com/twbs/bootstrap/pull/16179 about possibly removing some of the ``role="menu"`` instances to avoid authors tripping AT up unknowingly when they go beyond the normal menu pattern)
