### ISSUE TITLE
Bootstrap Template Scrolling nav

### ISSUE THREAD

**Issue by Jehizkia** [twbs/bootstrap#16095]
While I was working with this template I noticed when you re-sized the height of your brower window the elements on the page starts overlapping each other. 
solution: 
1.go into the file "scrolling-nav.css" 
2. go to line 34 or search for the class "intro-section"
3. remove the "height property" or make it an comment to disable it
After you've done this the problem should be fixed :)

**Comment by cvrebert** [comment]
There is no such example/template in Bootstrap.

**Comment by cvrebert** [comment]
You are presumably referring to this third-party template:
https://github.com/IronSummitMedia/startbootstrap-scrolling-nav

**Comment by Jehizkia** [comment]
yes, I'm sorry I didn't know it was a third-party template
