### ISSUE TITLE
Remove border radius settings from .btn-group-vertical > .btn 

### ISSUE THREAD

**Issue by fizex** [twbs/bootstrap#16106]
Remove border radius settings from .btn-group-vertical they are affecting border radius when using .btn-lg class.

.btn-group-vertical > .btn {
  &:not(:first-child):not(:last-child) {
    border-radius: 0;
  }
  &:first-child:not(:last-child) {
    //border-top-right-radius: @border-radius-base;
    .border-bottom-radius(0);
  }
  &:last-child:not(:first-child) {
    //border-bottom-left-radius: @border-radius-base;
    .border-top-radius(0);
  }
}

**Comment by cvrebert** [comment]
Please post an example that demonstrates the problem.

**Comment by mdo** [comment]
Closing until we have a test case.
