### ISSUE TITLE
.dropdown-toggle focus outline shouldn't be removed?

### ISSUE THREAD

**Issue by peterblazejewicz** [twbs/bootstrap#16103]
Hi team,

Is this fixture for Dropdown component still required or desired?
https://github.com/twbs/bootstrap/blob/master/less/dropdowns.less#L24-L27
The commit introducing this fixture:
https://github.com/twbs/bootstrap/commit/8bb7def26cac4d3166fbf2cc98f16c4151794676#diff-6972cbb37f0ec48771217d4915ea7e6fR2380

With this fixture that's hard to recognise navigation element focused:

![navbar](https://cloud.githubusercontent.com/assets/14539/6714509/edde2c92-cd98-11e4-97a2-5a779e8d7264.gif)

Thanks!

**Comment by cvrebert** [comment]
"Fixture"?

**Comment by cvrebert** [comment]
CC: @patrickhlauke @mdo

**Comment by patrickhlauke** [comment]
Sort of related #14939

In short, unless I'm mistaken, without explicitly suppressing the outline, it will "stick" for mouse users once they open/close dropdowns, and there's no clean solution to work around the problem without using JavaScript on top of it...

**Comment by peterblazejewicz** [comment]
@cvrebert 
Sorry - I didn't want to sound rude or impolite - I'm just wondering what was the reason of this specific solution and if it is still valid to use. 

@patrickhlauke 
excellent thread - thanks! I've not searched enough in closed tickets.

**Comment by cvrebert** [comment]
@peterblazejewicz It wasn't rude but instead unclear. I think you wanted just "fix". "Fixture" isn't quite the right word.

**Comment by peterblazejewicz** [comment]
@cvrebert Noted! Thanks!
