### ISSUE TITLE
Modal Switching Bug Effecting Scrolling

### ISSUE THREAD

**Issue by bigware** [twbs/bootstrap#16104]
Fiddle: https://jsfiddle.net/bigware/f3ta3xc4/

This fiddle highlights a bug when switching from one modal to another modal. When on a modal, the class "modal-open" gets added to the body. This allows scrolling to work on the modal, rather then the entire page. When switching from one modal to another modal, the class goes away, but does not come back. Due to this, scrolling does not work.

You can test this out by go to https://jsfiddle.net/bigware/f3ta3xc4/ and clicking the "Open Modal 1" button. Scroll to the bottom, and click "Switch to Modal 2". Modal 1 will close, and Modal 2 will open. But, try scrolling now, it will scroll the entire page, and leave the modal in the front.

This was not a bug  in version 3.2.0, but when I switched to 3.3.4 this bug crept in. I tested version 3.3.2 and found the bug in there also.

**Comment by cvrebert** [comment]
Your code is broken because the `hide` and `show` methods are async, but you code acts like they're synchronous. Please re-read the modal JS docs. Thanks!

**Comment by bigware** [comment]
I'm sorry, I didn't realize that. It doesn't mention that in the docs. All it mentions is about closing one before opening another, which is what I thought my code was doing.

**Comment by cvrebert** [comment]
It's perhaps not crystal clear, but this is what the docs are referring to when they say (in bold):
> Returns to the caller before the modal has actually been shown (i.e. before the shown.bs.modal event occurs).

(And similar for the other methods)

**Comment by tikotzky** [comment]
if you want to show a modal only once another modal is hidden, you can monitor the hidden event on the first modal and only open the second once the first is hidden.

for example:
```javascript
$('#switch_to_modal2').click(function () {
    $('#modal1').modal('hide').one('hidden.bs.modal', function(){
        $('#modal2').modal('show');
    });;
});
```

I updated your fiddle with a working copy here: https://jsfiddle.net/8pb7r51p/

**Comment by cvrebert** [comment]
@tikotzky The `.one` should come before the `.modal('hide')`, but yes, using the events like that is the proper way to deal with the async-ness.
