### ISSUE TITLE
.center-block doesn't set `width: 100%` ?

### ISSUE THREAD

**Issue by mrbacay** [twbs/bootstrap#16111]
Shouldn't the center-block utility class have a definition of width: 100% ?

**Comment by cvrebert** [comment]
Why should it?

* AIUI, its existing `display: block` basically already has that effect.
* In most cases, the element `.center-block` is being used on should have an explicit width set by the user; for example, see http://www.w3resource.com/twitter-bootstrap/center-a-div.php

**Comment by mrbacay** [comment]
If the element it is assigned also has a property of <code>position: fixed</code> it doesn't follow the width of the parent—even if it's a block element, or am I wrong to assume that this utility class can be used with those types of elements?

**Comment by cvrebert** [comment]
Well, if you have two objects of the same dimensions at exactly the same location, then by definition they are already centered within each other (this being an edge-case where the centering is trivial).
So in normal non-fixed-position cases, I'm not sure why one would (need to) use `.center-block` on a `width: 100%` element in the first place, although I am admittedly not a CSS expert.

Let me put it another way: In your case, if you remove `.center-block` and just put `width: 100%`, what problem do you encounter?

**Comment by mdo** [comment]
That utility is for centering an element within another element. It knows nothing of what the parent is, so if you've got some `position: fixed` parent, you'll need to account for width there as well.
