### ISSUE TITLE
Column size not rendering properly for hidden tabs.

### ISSUE THREAD

**Issue by berkinthomas** [twbs/bootstrap#16112]
Column presents in the active tabs renders properly. The second tab which columns are hidden by default does not render properly.

 For ex;
* col-md-4  in first tab takes 430px by default
* col-md-4 in second tab takes 100px or below by default

**Comment by cvrebert** [comment]
We'll need a JS Bin that demonstrate the problem in order to be able to help you.
Please also state the OS, browser, and viewport width that you are using.

**Comment by berkinthomas** [comment]
Thanks for your response. 

OS  : Windows 8.1 
Browser  : Chrome 
viewport width : 1366px
application : pentaho cde 5.3

**Comment by cvrebert** [comment]
And the [JS Bin](http://jsbin.com/) example please?

**Comment by berkinthomas** [comment]
http://jsbin.com/wonesiruwu/1/

**Comment by twbs-lmvtfy** [comment]
Hi @berkinthomas!

You appear to have posted a live example (http://jsbin.com/wonesiruwu/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 19, column 100: Element ```` link ```` is missing required attribute ```` property ````.
* line 22, column 106: Element ```` link ```` is missing required attribute ```` property ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
After moving the `<link>`s into the `<head>` where they belong: http://jsbin.com/fibufo/1/edit

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/fibufo/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 32, column 7: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 35, column 9: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by berkinthomas** [comment]
sorry, i did not understand what you are saying...

**Comment by berkinthomas** [comment]
please read the alert box, where the width of each div shown.

**Comment by cvrebert** [comment]
A. You're not using columns correctly; see https://github.com/twbs/bootlint/wiki/E014
B. Why do you care about the width of a hidden element in the first place? Its width is correct when it's shown, yes?

**Comment by berkinthomas** [comment]
B.  then, is it possible to refresh this tab while I am clicking,

**Comment by cvrebert** [comment]
Define "refresh". There are events you can listen for and then reinitialize some third-party widget in the tab in your event handler, if that's what you mean. See http://getbootstrap.com/javascript/#tabs-events

**Comment by berkinthomas** [comment]
Thanks. It's working fine..
