### ISSUE TITLE
HTML input checkbox with class .form-control width problem

### ISSUE THREAD

**Issue by weitzhandler** [twbs/bootstrap#16123]
Hi,

When generating a checkbox field with MVC Razor, as follows:

    @Html.EditorFor(model => model.IsHappy)

It inserts the class `form-control` to the generated input element, which is in this case a checkbox.  
What happens is, the element becomes huge to take up free space:

![](http://i.imgur.com/rc4AjyH.png)

I found it that what's causing this issue is the `width=100%` setting of `.form-control`, and when I add the following underneath the `.form-control` classes in the *bootstrap.css* file, issue is solved.

**Comment by cvrebert** [comment]
`.form-control` is only meant for use on `<textarea>`s, `<select>`s, and textual `<input>`s.
Use the `.checkbox` class for checkboxes (see the docs for details on usage).

**Comment by weitzhandler** [comment]
I guess this is something the ASP.NET MVC Razor engine team missed out.

Thanks and sorry for bothering!

**Comment by aspaiva** [comment]
I did not understand what is the solution and how to implement it. Please, explain like I have 6yo because I am not a CSS expert. Thanks.

**Comment by wolfy1339** [comment]
The solution was to just to not use `.form-control` class for checkboxes
