### ISSUE TITLE
Popover with trigger:"manual focus" always pops up automatically when button is clicked

### ISSUE THREAD

**Issue by joakim-m** [twbs/bootstrap#16122]
It doesn't wait for `.popover('show')`

**Comment by cvrebert** [comment]
Yes, that's exactly what `focus` is supposed to do. Admittedly, it's not clear to me whether it's sensical to combine `manual` with any other triggers like you're doing here.

**Comment by joakim-m** [comment]
I want to have a popover that shows only manually, but hides when a user clicks outside.

**Comment by cvrebert** [comment]
You'll have to use `manual` and handle all the showing/hiding entirely on your own then.

**Comment by cvrebert** [comment]
Keeping this open as, at the least, a documentation issue. And possibly we should make `trigger` combos involving `manual` throw an error.

**Comment by cvrebert** [comment]
@hnrch02 @XhmikosR Do you guys agree that combining `manual` with other triggers is nonsensical? Or am I missing something?

**Comment by fat** [comment]
I agree, doesn't make a lot of sense – something to add to our option checker in v4 for sure

**Comment by mdo** [comment]
Should this be closed then?

**Comment by rumman0786** [comment]
@ghost 

> I want to have a popover that shows only manually, but hides when a user clicks outside.

Were you able to implement what you wanted? I need something similar. Any snippets?
