### ISSUE TITLE
add an "input-group-xs" class

### ISSUE THREAD

**Issue by zzxjoanw** [twbs/bootstrap#16126]
This shows an xs-sized window with input fields and input-group-addons. The first input box has .input-group.xs applied. Any text entered in the second or third boxes doesn't show up.

![input-group-xs example](https://cloud.githubusercontent.com/assets/193442/6769731/0bc4ea62-d09f-11e4-8f78-11195bfeb227.png)

CSS for mobile-friendly input:
.input-group-xs > .input-group-addon {
  height: 30px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
}

.input-group-xs .input-group-addon {
  border-right: 1px solid #ccc;
}

.input-group-xs > .input-group-addon {
	border-top-left-radius:3px;
	border-top-right-radius:3px;
	border-bottom:none;
}

.input-group-xs > input[type="text"] {
	border-top-left-radius:0;
	border-top-right-radius:0;
	border-bottom-left-radius:3px;
	border-bottom-right-radius:3px;
	height: 30px;
  	padding: 5px 10px;
}

**Comment by mdo** [comment]
We're no longer adding new features to v3, sorry.
