### ISSUE TITLE
Add .panel-inverse to match .navbar-inverse for panel titles

### ISSUE THREAD

**Issue by CriseX** [twbs/bootstrap#16128]
This seems given, I was fiddling with the navbar earlier and realized unless all my panels are "headless" there is no way I can use navbar-inverse and panel-default without the two clashing.

Customising either color manually is hardly difficult but that is not the point here ultimately. Just a trivial request

**Comment by mdo** [comment]
We won't be adding any new features to v3, sorry.

**Comment by CriseX** [comment]
And world beyond version 3 does not exist and/or cannot be talked about? What your policy about adding features is currently should not prevent discussion about future additions. I also did not imply that this request was specific to a particular version or milestone.

Did I miss a memo somewhere about feature requests in general not being welcome?

**Comment by mdo** [comment]
Nah, I don't mean to be cryptic or unwelcoming. I'm just trying to keep ourselves focused on the larger project here. Anything that can't be done in v3—for lack of time, interest, versioning, etc—is happening in v4. And v4 isn't out yet, so rather then leaving things lingering, I'm closing them out.
