### ISSUE TITLE
Modal greyed out after updating to Meteor's twbs:bootstrap-3.3.4

### ISSUE THREAD

**Issue by onsombal** [twbs/bootstrap#16125]
I just updated to Meteor-1.0.4.2 from Meteor-1.0.4.1 and twbs:bootstrap automatically updated from 3.3.2 to 3.3.4.

My modal is now greyed out with the rest of the screen. I went back to Meteor-1.0.4.1 and my modal is still greyed out. I do not know how to go back to twbs:bootstrap-3.3.2. I can only assume that twbs:bootstrap-3.3.4 is the cause of my modal now being greyed out.

I installed the package -- mizzao:bootstrap-3 -- and my modal works as it should; not greyed out.

Also, can you reply with instructions for downgrading to twbs:bootstrap-3.3.2 ?

Thanks... Jim

**Comment by cvrebert** [comment]
My speculation would be that you're somehow mixing CSS and JS from different Bootstrap versions. Does Meteor have some sort of "clean" task or some kind of build cache that you might need to purge?

Anyway, we're unable to provide assistance with Meteor-specific problems (nobody on Core Team uses Meteor) unless there's some specific bug in our packaging that can be pointed out.
However, let's CC @splendido & @dandv, who added the Atmosphere integration, to see if they can offer you any advice.

**Comment by splendido** [comment]
Hello there.

I've just created a new test project using twbs:bootstrap@3.3.4 and pasting the code for [modal test](http://getbootstrap.com/javascript/#live-demo): it worked flawlessly ;-)

@onsombal could you please point us to a reproduction of your problem?

FYI to set a contraint on a package version you can do `meteor add org:package@x.y.z`, so in your case it should be

```shell
meteor add twbs:bootstrap@3.3.2
```

**Comment by onsombal** [comment]
Below is my code; it's pretty basic. The modal produced by this code worked fine with twbs:bootstrap@3.3.2. It works fine with mizzao:bootstrap-3, version 3.3.1_1.  The modal is greyed out using twbs:bootstrap@3.3.4


            <div class="row">
                <div class="col-sm-3" aria-labelledby="To Do">
                    <ul class="list-group listbox">
                        <li class="list-group-item"><strong>To Do</strong><span><a href="#" data-toggle="modal" data-target="#myModal" id="usertodo" value="userTodo" class="glyphicon glyphicon-plus-sign pull-right" aria-hidden="true"></a></span></li>   
            
                        <li class="list-group-item uTodo" id="mylist">
                    <ul class="list-group" name="userTodo" id="todo"></ul>
                        </li>
                    </ul>
                </div>



    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">                  
                    {{> cardSubmit}}  
            </div>
        </div> 
    </div>       
</section>

**Comment by onsombal** [comment]
Hello Luca,

I tried " meteor add twbs:bootstrap@3.3.2 ", but the installer still installs twbs:bootstrap@3.3.4. I'm running Meteor-1.0.4.2.

The modal is still greyed out. I put my code for this modal at https://github.com/twbs/bootstrap/issues/16125

Below are the packages I have installed. I replaced twbs:bootstrap@3.3.4 with mizzao:bootstrap-3, which appears to be using an earlier release of Bootstrap 3.  Again, twbs:bootstrap@3.3.2 worked well when I had it installed. I made no changes in my modal code.

accounts-password                1.1.0  Password support for accounts
audit-argument-checks            1.0.3  Try to detect inadequate input saniti...
harrison:papa-parse              1.0.10  A powerful, in-browser CSV parser fo...
ian:accounts-ui-bootstrap-3      1.2.36  Bootstrap-styled accounts-ui with mu...
iron:router                      1.0.7  Routing specifically designed for Meteor
jquery                           1.11.3_2  Manipulate the DOM using CSS selec...
less                             1.0.13  The dynamic stylesheet language
meteor-platform                  1.2.2  Include a standard set of Meteor pack...
meteorhacks:search-source        1.2.0  Reactive Data Source for Search
mizzao:bootstrap-3               3.3.1_1  HTML, CSS, and JS framework for dev...
sacha:spin                       2.0.4  Simple spinner package for Meteor
tsega:bootstrap3-datetimepicker  4.7.14_3  Bootstrap 3 DateTime picker from @...
underscore                       1.0.3  Collection of small helpers: _.map, _...

I also created another modal test to test twbs:bootstrap@3.3.4 -- code below

<template name="cardmodalTest">

    <div class="container">
        <div class="row text-center">
            <h3>The Basic Modal</h3>
            <a href="#" data-toggle="modal" data-target="#basicModal">Click to open Modal</a> 
        </div>



    <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    <div class="form-group">
                        <label>Name</label>
                        <input class="form-control required" placeholder="Your name" data-placement="top" data-trigger="manual" data-content="Must be at least 3 characters long, and must only contain letters." type="text">
                    </div>                              
                </div>
                <div class="modal-body">                

    <form class="form-inline"> 
    <div class="form-group">
      <label class="control-label" for="cardType">Card Type</label>
      <div class="controls">
          <input name="cardType" id="cardType" type="text" value="" placeholder="Card Type" class="form-control"/>
      </div>
    </div>   
    <div class="form-group">
      <label class="control-label" for="taskDueDate">Task Due Date</label>
      <div class="controls">
          <input name="taskDueDate" id="taskDueDate" type="text" value="" placeholder="Task Due Date" class="form-control"/>
      </div>
    </div>                      
                </div> 
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
      </div>
    </div> 
    </div>
</template>

I'm not sure what's causing twbs:bootstrap@3.3.4 to not work for me. I just know I made no code changes from when I was using twbs:bootstrap@3.3.2 -- and now that I'm using mizzao:bootstrap-3. The common link between these last two packages is they both use earlier versions than Bootstrap 3.3.4.

Regards... Jim

**Comment by splendido** [comment]
Have you tried to test the very same modals on a bare HTML page loading Bootstrap from the CDN?

That would be interesting to confirm whether it is a problem with Bootstrap itself or with the Meteor wrapper...

**Comment by OminStyle** [comment]
I'm experiencing the same issue as I updated to Meteor 1.0.5 from Meteor 1.0.3.2. Removing twbs:bootstrap package and loading Bootstrap 3.3.2 fixes the issue. However I get the same problem with 3.3.4.

**Comment by splendido** [comment]
Hey!
I've just tested the modal code pasted before and I have no problem with it!
...the only thing I've added is a missing `</form>` tag.

See [this repo](https://github.com/splendido/test-bootstrap-3.3.4)
Let me know if it works also for you!
