### ISSUE TITLE
Modals Overlapped by Tooltips/Popovers

### ISSUE THREAD

**Issue by zomp** [twbs/bootstrap#16127]
Modals are overlapped by tooltips/popovers which should be displayed behind them. See http://jsbin.com/bimipobiso/1/edit?html,output

Originally it worked fine but #13217 wrongly changed z-index values of tooltips/popovers to solve a side case of st else, which broke the primary use case of modals. (#13217 wanted to solve a situation, when a tooltip/popover is used inside a modal, but its container is set to be body. In that situation a tooltip/popover is taken out of the modal and placed to a different container. Unfortunately I do not know how to solve that issue properly, but this does not seem to be a valid solution.)

Thank you. Jan

**Comment by mdo** [comment]
Your example doesn't appear to work. Can you double check it?

**Comment by nextgenthemes** [comment]
Works for me, Ubuntu 14.10 Firefox 38.0a2. Confirming popover overlapping modal.

**Comment by mdo** [comment]
The z-indexes are set up in such a way that popovers within a modal work correctly. Any changes to this would undo that. My suggestion would be you close the popover when triggering the modal. Seems like the easiest fix without rejiggering z-indexes for everyone.

**Comment by zomp** [comment]
@nextgenthemes, thank you for the confirmation.

@mdo, thank you for the response. I am sorry, this must be a misunderstanding, it is not right: 1) Popovers within a modal does not work correctly. 2) And #13217 rejiggered z-indexes for everyone and I just want to correct it back.  3) Moreover popovers outside modals does not work correctly now.

1) `container: 'body'` is a hack and make popovers broken – if you use it, a lot of other things are affected, e.g. a popover defined inside a modal is not scrolled altogether with the modal and if you close the modal, the popover is still displayed: http://jsbin.com/bomanidafa/1/edit?html,output
Regular popovers within a modal would work correctly even without #13217. The only ones who would not work are those, who are defined inside and placed outside of the modal by the hack (`container: 'body'`). I do not question the hack, but it is just a hack, so it should not be made more important than a regular usage of something else (modals).

2) #13217 fixes only popovers defined within a modal moved outside by `container: '...'`. All the regular popovers within a modal would work even if #13217 would be reverted – there are placed within the modal, so they would be above the modal even though their z-index would be smaller.

3) All the popovers outside modals do not work as they should. Because there is a higher probability of a popover outside a modal than a popover inside a modal which is set to `container: 'body'`, I dare to question the current behaviour and propose to make up a better solution than #13217.

Maybe, the `container: '...'` processing could be somehow improved to adjust z-indexes, enable scrolling, hide what should be hidden in a proper time... but it is a different story.

Thank you. Bootstrap is one of my the most favourite projects.

**Comment by zomp** [comment]
I am still able to reproduce the issue on v4.0.0-alpha.5:
http://jsbin.com/yaxifejafi/edit?html,output

Tested in Firefox and Chromium under Linux and in IE and Edge under Windows.

![overlap](https://cloud.githubusercontent.com/assets/1536432/19552073/862610b6-96ae-11e6-8e0f-f709f6ca8413.png)

**Comment by mdo** [comment]
@zomp Your jsbin link doesn't work for me—no Bootstrap CSS or JS seems to be getting applied.

**Comment by zomp** [comment]
@mdo that seems to be correct – there is no need for custom JS and CSS – the issue lies in Bootstrap itself. (You just need to click the buttons and make your viewport narrower to see the overlap order.)

**Comment by nextgenthemes** [comment]
he said nothing about custom css, he said
> no Bootstrap CSS or JS seems to be getting applied

Works for me (still) in Firefox and I can still confirm it overlapping

**Comment by zomp** [comment]
@nextgenthemes, I see. I am far from being a native speaker. I thought @mdo considered [jsbin](http://jsbin.com/yaxifejafi/edit?html,output) invalid, because there is no content in CSS and JS tabs (so I replied that was correct and intentional).

How could we reopen the issue?

**Comment by nextgenthemes** [comment]
"We" can do nothing, he can reopen but looks like he does not even tried to get the JS bin working.

**Comment by MunkhdelgerMorhous** [comment]
This maybe old but Increase number of z-index of stacks it should fix for my case
