### ISSUE TITLE
AnchorJS should not be active in live examples

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#16129]
For example, it's currently active on the example panel titles in http://getbootstrap.com/components/#panels-alternatives
CC: @XhmikosR

**Comment by XhmikosR** [comment]
Unfortunately, there doesn't seem to exist any way currently to skip specific selectors. Maybe we could submit a patch upstream?

**Comment by XhmikosR** [comment]
Also, we really need https://github.com/twbs/bootstrap/tree/bump-anchorjs. It has an important change like avoiding duplicate IDs which we all know are invalid.

**Comment by Johann-S** [comment]
I submitted a PR to add unwanted selectors on ``anchorjs``
https://github.com/bryanbraun/anchorjs/pull/33

**Comment by fat** [comment]
@cvrebert couldn't we just add this to our docs css in the short term: 

```css
.bs-example .anchorjs-link {
  display: none !Important;
}
```
