### ISSUE TITLE
.img-thumbnail inside .media-left renders differently in Chrome than in Firefox

### ISSUE THREAD

**Issue by gws** [twbs/bootstrap#16120]
When applying `.img-responsive` or `.img-thumbnail` (possibly others) to a `.media-object` inside `.media-left`, the media object gets "crushed" horizontally by the `.media-body` even with an explicit width (and height) set, but just in Chrome - the expected rendering occurs in Firefox. I haven't tested extensively with other browsers.

Firefox: 36.0.1
Chrome: 41.0.2272.76

I've got a minimal example of the behavior:

http://jsbin.com/lunohawexo/2

In the example, the first `div.media` exhibits the problem in Chrome, and the second `div.media` does not. Both appear as I expect in Firefox.

At this point I'm not sure if I'm doing something wrong, if this is an issue with Bootstrap's CSS, or a browser bug. I'm hoping somebody more knowledgeable can point me in the right direction.

Thanks!

**Comment by twbs-lmvtfy** [comment]
Hi @gws!

You appear to have posted a live example (http://jsbin.com/nicehopoje/5/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by gws** [comment]
Updated the link in the original post to appease the bot: http://jsbin.com/lunohawexo/2

**Comment by cvrebert** [comment]
Desktop Safari 8.0.4 matches Chrome's rendering.
IE9-11 match Firefox's rendering.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by thomasphorton** [comment]
Chrome doesn't like max-width in table-cell.

Working on something along the lines of
```
.img-thumbnail {
  &.media-object {
    max-width: none;
  }
}
```

in scaffolding.less
