### ISSUE TITLE
Problem with vertical nav

### ISSUE THREAD

**Issue by J3FF3** [twbs/bootstrap#16121]
Code: http://pastebin.com/FGnd0zYv

Hello. Steps to view the problem:
1. Open page into wide screen (screenshot 1)
2. Change window size to middle (2)
3. Change window size to small and click on navbar icon to show menu (3)
4. Click to hide (4)
5. Change window size to bigger (5)
6. Change window size to large (6)

How can fix this problem?

1. 
![1](https://cloud.githubusercontent.com/assets/913873/6765985/48c010e2-cffd-11e4-846c-3bb75e509996.png)

2. 
![2](https://cloud.githubusercontent.com/assets/913873/6765987/4dcbab5a-cffd-11e4-91bf-24edab5a786b.png)

3. 
![3](https://cloud.githubusercontent.com/assets/913873/6765989/55267dd0-cffd-11e4-9603-a4b8d683aec5.png)

4. 
![4](https://cloud.githubusercontent.com/assets/913873/6765991/59c2a77e-cffd-11e4-8841-e353a945c2d0.png)

5. 
![5](https://cloud.githubusercontent.com/assets/913873/6765992/5e4fb534-cffd-11e4-81f5-d0f6385109c6.png)

6. 
![6](https://cloud.githubusercontent.com/assets/913873/6765993/62e09f14-cffd-11e4-9843-3cda87317319.png)

**Comment by patrickhlauke** [comment]
For questions about your specific use of Bootstrap (rather than issues relating to Bootstrap itself), please refer to forums like StackOverflow.
