### ISSUE TITLE
Problem with navbar collapse. Its not displaying on  768px view

### ISSUE THREAD

**Issue by lijingsamuel** [twbs/bootstrap#16133]
When the menu has many items it breaks in Ipad and other tablets becuase it doesnt get collapsed like it automatically collapsed on mobile. Anyone can help me please..
![navbar](https://cloud.githubusercontent.com/assets/6416377/6780218/35e52dda-d189-11e4-8c5a-094067c3d2bf.jpg)

**Comment by kkirsche** [comment]
Have you tried this on an iPad or just in (what appears to be) Firefox responsive viewer? I believe the Firefox viewer has a few known issues

**Comment by lijingsamuel** [comment]
yes. I have the same issue in apple ipad portrait view.

**Comment by cvrebert** [comment]
Per [the docs](http://getbootstrap.com/components/#changing-the-collapsed-mobile-navbar-breakpoint) (emphasis added):
> The navbar collapses into its vertical mobile view when the viewport is **narrower than** `@grid-float-breakpoint`, and expands into its horizontal non-mobile view when the viewport is at least `@grid-float-breakpoint` in width. Adjust this variable in the Less source to control when the navbar collapses/expands. The default value is `768px` (the smallest "small" or "tablet" screen).

So this is expected behavior. It will collapse at 767px by default.
As for how to deal with your navbar content overflowing on to 2 lines like in your screenshot, see http://getbootstrap.com/components/#callout-navbar-overflow

**Comment by lijingsamuel** [comment]
yes i got the solution ..
i just over-righted the boostrap css for  768px view 

/* see the below style */
@media (max-width: 900px) {
  .navbar-header {
    float: none;
  }
 .navbar-toggle {
    display: block!important;
}
.collapse{
	display:none!important;
	}
.navbar-collapse {
  padding-right: 15px;
  padding-left: 15px;
  overflow-x: visible;
  -webkit-overflow-scrolling: touch;
  border-top: 1px solid transparent;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .1);
          box-shadow: inset 0 1px 0 rgba(255, 255, 255, .1);
}
  .navbar-form .form-group {
    display: inline-block!important;
    margin-bottom: 0;
    vertical-align: middle;
}	
}

@media (min-width: 900px) {
  .navbar-collapse {
    width: auto;
    border-top: 0;
    -webkit-box-shadow: none;
            box-shadow: none;
  }
  .navbar-collapse.collapse {
    display: block !important;
    height: auto !important;
    padding-bottom: 0;
    overflow: visible !important;
    visibility: visible !important;
  }
  .navbar-fixed-top .navbar-collapse,
  .navbar-static-top .navbar-collapse,
  .navbar-fixed-bottom .navbar-collapse {
    padding-right: 0;
    padding-left: 0;
  }


}
@media (max-width: 990px) {
    .navbar-header {
        float: none;
    }
    .navbar-toggle {
        display: block;
    }
    .navbar-collapse {
        border-top: 1px solid transparent;
        box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
    }
    .navbar-collapse.collapse {
        display: none!important;
    }
    .navbar-nav {
        float: none!important;
        margin: 7.5px -15px;
    }
    .navbar-nav>li {
        float: none;
    }
    .navbar-nav>li>a {
        padding-top: 10px;
        padding-bottom: 10px;
    }
	.collapse.in {
  display: block!important;
  visibility: visible!important;
}
.navbar-left {
    float: none !important;
}
.navbar-nav .open .dropdown-menu {
    background-color: transparent;
    border: 0 none;
    box-shadow: none;
    float: none;
    margin-top: 0;
    position: static;
    width: auto;
}
}
