### ISSUE TITLE
Add Glyphicon Globe with other side of Globe

### ISSUE THREAD

**Issue by yultyyev** [twbs/bootstrap#16139]
It will be nice if there will be one more Globe glyphicon with more usual for Europian/Asia users side (Eurasia/Africa/Australia)

**Comment by cvrebert** [comment]
The [Glyphicons](http://glyphicons.com) are an external project that we just package/bundle.
Please direct icon suggestions to the Glyphicons' author. Thanks!

See also https://github.com/FortAwesome/Font-Awesome/issues/281

**Comment by cvrebert** [comment]
Actually, this is already part of the full for-pay Glyphicons (as `glyphicons-globe-af`), but Bootstrap only includes the "Halflings" set of Glyphicons.
