### ISSUE TITLE
How to restrict tab opens in second row, if more tab opens? 

### ISSUE THREAD

**Issue by ganthi** [twbs/bootstrap#16138]
I've include removable tab in bootstrap.

In my design, if i open more tabs, it show in the second line.

![untitled1](https://cloud.githubusercontent.com/assets/8499105/6795657/e88e40c2-d209-11e4-9b5e-82f463c7b5df.png)

How can i show all the tabs in same line and to set navigation. Is it possible?

Thanks

**Comment by mdo** [comment]
Fewer tabs or shorter labels are your best bet.

**Comment by xyres** [comment]
Maybe try stacked tabs?

**Comment by ganthi** [comment]
@xyres : stacked tabs is not suitable for my requirement. Bcoz i will open more than 10 tabs at the same time.
