### ISSUE TITLE
Size of first table row is inconsistent between browsers.

### ISSUE THREAD

**Issue by ripdog** [twbs/bootstrap#16149]
Testcase: http://jsfiddle.net/x5kefrd4/1/

On Blink and Webkit-based, the th element has a 2px bottom border. On Gecko and Trident, the `th` has a 1px bottom border and the first row has a 1px top border.

This means that the first row is 38px on Gecko and Trident and 37px elsewhere - the latter is correct.

There's more to this bug than meets the eye. Firefox's box model display shows the `th` elements as having 1px of bottom border, but when clicked, it expands to 2px. I'm hoping for some expert eyes on this problem and advice before I file a bug with Mozilla.

**Comment by twbs-lmvtfy** [comment]
Hi @ripdog!

You appear to have posted a live example (http://fiddle.jshell.net/x5kefrd4/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Just check in the latest Safari, Firefox, and Chrome on Mac—everything is `37px` for me. Even if there are discrepancies, I don't think it's important enough to worry about right now. Let us know if you find anything else out though—I could easily be overlooking something.

**Comment by patrickhlauke** [comment]
@mdo, I can see the discrepancy in Firefox/Win.

![capture2](https://cloud.githubusercontent.com/assets/895831/6843142/c5b5dd82-d397-11e4-9ae6-7c853bc28b42.PNG)

**Comment by ripdog** [comment]
@mdo JSFiddle is broken right now, so a codepen: http://codepen.io/anon/pen/jEdJgq

Changed the JS to display the height of first and second rows. In chrome, output is  37px 37px, firefox 38px 37px.

Another screenshot: http://i.imgur.com/TukZbOd.png

**Comment by twbs-lmvtfy** [comment]
Hi @ripdog!

You appear to have posted a live example (http://codepen.io/anon/pen/jEdJgq.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 100: Element ```` link ```` is missing required attribute ```` property ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
@patrickhlauke You're comparing the `thead`'s row vs the `tbody`'s row, no? I'd expect some cross-browser variation there with the `font-weight` and larger border.

**Comment by patrickhlauke** [comment]
@mdo yup, but i'm just confirming the OPs original statement :)

**Comment by mdo** [comment]
Ah, if that's what the OP meant, then I don't consider this a bug at all. Sounds about right to me.

**Comment by ripdog** [comment]
@mdo @patrickhlauke I'm sorry, I didn't mean to give that impression. The problem is the first table row, not the header. As you can see in my screenshot, it has a different height in different browsers. The header is only involved in that it appears to be a possible cause for the discrepancy.
