### ISSUE TITLE
false breakpoints on all mediaqueries

### ISSUE THREAD

**Issue by Shyim** [twbs/bootstrap#16141]
hey guys,

i've uploaded an image of the sourcecode where you can see the windowsize and what is visible!
the bugfeature is only on our project! js.fiddle and older projects work fine.
chrome show our project with no bugs too.

i have no idea where the fucking problem can be found. I've deleted the whole sourcecode except the bootstrap and the 2 divs 

![bug](https://cloud.githubusercontent.com/assets/6224096/6800981/f8df16ee-d223-11e4-938e-dd19b207e5a5.png)

**Comment by patrickhlauke** [comment]
Can't reproduce this, I'm afraid (tested your exact code on Win and Mac - both retina and non-retina MacBook - with Firefox). The fact it only happens on your test leads me to believe there's something not quite right with your setup...perhaps, some custom zoom setting in Firefox?
I'd suggest testing this on another machine or different browser, just to narrow down where the problem may be - but it does not appear to be an issue with core Bootstrap itself.
