### ISSUE TITLE
.alert-dismissible as default target for Dismissible alerts

### ISSUE THREAD

**Issue by matysik** [twbs/bootstrap#16150]
The [Bootstrap docs](http://getbootstrap.com/javascript/#alerts) indicated that "When using a .close button, it must be the first child of the **.alert-dismissible** ...".

But actually, the real target selector for the event is **.alert**.

It seems to me more logical to change the selector in the file **alert.js** at line number *39* to: `$parent = $this.closest('.alert-dismissible')`

Thus the **.alert** class unbinds from JavaScript and allows you to use dismissible alerts without must-have styles from the class **.alert**. Use only class **.alert-dismissible**, as described in the documentation.

**Comment by hnrch02** [comment]
That'd be something for v4 since all `.alert-dismissible` does is adjust the positioning and color of the `.close` button slightly so some people just leave it out. I'll make a note.
