### ISSUE TITLE
My Code Not working

### ISSUE THREAD

**Issue by SUMAN-PATI** [twbs/bootstrap#16153]
<!DOCTYPE html>
<html>
<meta charset="UTF-8"/>
<head>
<meta charset="UTF-8"/>
<title>Scrolling Effect</title>
<script type="text/javascript" src="jquery-1.11.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="normalize.css">
<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="css/bootstrap-theme.css">
<script type="text/javascript" src="bootstrap.js"></script>

<style type="text/css">
*{
	margin: 0px;
	padding: 0px;
}
body{
	font-family: Raleway,Arial;
}
.content,.content2{
	height: 800px;
	background-color: #e0e0e0;
}
.about{
	max-width: 600px;
	margin: 0 auto;
	padding: 100px 0;
	transform-style:preserve-3d;
	transform:perspective(800px);
}
.about h2{
	color: #FF4136;
	text-transform: uppercase;
	font-size: 50px;
	font-weight: 400;
}
.about p{
	color: #0074D9;
}
.about h2,.about p{
	transition:all 0.8s ease;
}
.about.hidden h2{
	color: #0074D9;
	opacity: 0;
	transform:translate3d(0,0,200px) rotateY(-40deg);
}
.about.hidden p{
	opacity: 0;
	color: #FF4136;
	transform:translate3d(0,0,400px) rotateY(40deg);
}
</style>
<body>

<div >

		<div class="row">
			
			<div class="col-md-6">
				<div class="inner-content" style="background-color:#2ECC40;">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</div>	
			</div>
			
			<div class="col-md-6">
				<div class="inner-content" style="background-color:#85144b;">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</div>	
			</div>
		</div>

		<div class="row">
			
			<div class="col-md-6">
				<div class="inner-content" style="background-color:#0074D9;">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</div>	
			</div>
			
			<div class="col-md-6">
				<div class="inner-content" style="background-color:#FF851B;">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</div>	
			</div>
		</div>

		<div class="row">
			
			<div class="col-md-6">
				<div class="inner-content" style="background-color:#FFDC00;" >
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</div>	
			</div>
			
			<div class="col-md-6">
				<div class="inner-content" style="background-color:#DDDDDD;" >
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</div>	
			</div>
		</div>
	</div>

	
	<div class="content">

	</div>
	<div class="content2">

	</div>
	</div>
	<div class="about hidden">
		<h2>This is the Heading</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
	<div class="content"></div>
	<div class="toggler">Hello</div>
	<button class="good">Hello</button>

<script type="text/javascript">
(function(){
	var aboutEl = $('div.about'),
		content2 = $('div.content2'),
		aboutElOffset=(aboutEl.offset().top)-content2.height()/2;
		documentEl=$(document);
	documentEl.on('scroll',function(){
	if(documentEl.scrollTop()>aboutElOffset && aboutEl.hasClass('hidden'))
		aboutEl.removeClass('hidden');

	});
})();
</script>
</body>
</html>

My script doesn't work the way it should be when I inlucde the bootstrap.css or bootstrap-theme.css or any of bootstrap file.
Try this Code once and then comment the bootstrap files included on the top of the page and you will the problem .

Thank You in Advance,
Suman

**Comment by patrickhlauke** [comment]
For specific questions about your implementation, rather than Bootstrap itself, please refer to places like StackOverflow. Thanks.
