### ISSUE TITLE
.list-group-striped ?

### ISSUE THREAD

**Issue by rubenscd** [twbs/bootstrap#16161]
future could implement a ".list-group-striped" like is on the tables.

**Comment by mdo** [comment]
We've no plans to do that ourselves—v3 will be seeing no new features. The code for doing that in tables could be easily adapted though.

**Comment by AndrewKralovec** [comment]
Can be done like this
tbody tr:nth-child(odd) {
   background-color: #ccc;
}

**Comment by joeysino** [comment]
Any chance of getting this in Bootstrap 4? :)

Thanks for your suggestion Andrew.  We did try something along those lines but unfortunately the selector was more specific than the `.list-item:active` selector, so it broke active highlights.  :(

**Comment by julmot** [comment]
I'm also interested for this in Bootstrap 4

**Comment by fab5741** [comment]
Yeah it should be cool guys :)

**Comment by ryabenko-pro** [comment]
Me too
