### ISSUE TITLE
labels within breadcrumbs is whitespace sensitive

### ISSUE THREAD

**Issue by jvanasco** [twbs/bootstrap#16163]
This is more of a docs warning than a bug.  I thought a callout might be a good idea.

When using labels in breadcrumbs, whitespace rules may cause a linebreak and odd formatting (see picture)

Code written in this style will create that output

    <li> 
        <a class="label label-info" href="/path/to">
            <i class="fa fa-twitter-square"></i>
            &nbsp;
            B
        </a>
    </li>

It took me a while to pinpoint this.

Here's an example with the bad form, and alternate forms that work.  I'm rusty on CSS/HTML rules, so I don't know what official combination breaks

   http://www.bootply.com/aI1qOPmlKV

probably related to https://github.com/twbs/bootstrap/issues/3652

![screen shot 2015-03-26 at 6 56 37 pm](https://cloud.githubusercontent.com/assets/204779/6858960/218d2122-d3ea-11e4-89ad-6bc57d82a146.png)

**Comment by twbs-lmvtfy** [comment]
Hi @jvanasco!

You appear to have posted a live example (http://s.bootply.com/render/aI1qOPmlKV), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 110, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Yeah, anything that's `inline-block` will be white-space sensitive. No way around that, and not particular worth mentioning as it affects a lot of things, in and out of Bootstrap.
