### ISSUE TITLE
Bootstrap 3 Carousel not reacting to default keyboard events

### ISSUE THREAD

**Issue by readerpal** [twbs/bootstrap#16164]
Based on docs, 
http://getbootstrap.com/javascript/#carousel

``` keyboard 	boolean 	true ```

When I try the  demo (which is using default setting)

http://getbootstrap.com/examples/carousel/

Note: (Mac 10.9.5, Safari 7.1.3, Firefox 36.0.1)

**Safari,**
Never seems to respond to keyboard events.

**FireFox**
Works sometimes, but when it does work if I click on the bottom of screen, it will ignore future keyboard events.

I've tried using:
```
    $(document).ready(function(){

     $("#myCarousel").carousel({

         interval : false,

         pause: true,

         keyboard: true

     });
    });
```

and that doesn't seem to help either.

Any suggestions? - Thanks, 
R

**Comment by cvrebert** [comment]
Using OS X 10.10.2
I am unable to reproduce with Safari 8.0.4 or with Firefox 36.0.4.

> Never seems to respond to keyboard events.

Presumably you didn't focus the carousel before you started pressing the keys.
Having the carousel listen to keypresses on the `<body>` itself would be problematic, as the user's intent is unclear and it could very easily conflict with other widgets/scripts on the page.

> but when it does work if I click on the bottom of screen, it will ignore future keyboard events.

Yes, that's how it's supposed to work. The carousel only receives keyboard events when the carousel itself (or an element within it) is focused. Clicking away like that removes the focus.
