### ISSUE TITLE
Navbar dropdown problem on Android Chrome

### ISSUE THREAD

**Issue by paulbf87** [twbs/bootstrap#16173]
Works perfect on laptop chrome and iexplorer. Works perfect on android I explorer and apple safari. Not working on android chrome. Standard responsive code used

<
![img_20150328_123625_1551](https://cloud.githubusercontent.com/assets/11598246/6881114/7c8cd210-d549-11e4-9597-a6632824f177.jpg)
 meta name = " viewport " content = "width = device -width , initial - scale=1.0 " >

Can anyone help..

**Comment by cvrebert** [comment]
* Please post your webpage's code as a [JS Bin](http://jsbin.com/).
* What version of Android?
* What version of Chrome?

**Comment by paulbf87** [comment]
Js...http://jsbin.com/zonulo/1/edit?html,output

Android 4.3.0
Chrome 41.0.227.92

**Comment by twbs-lmvtfy** [comment]
Hi @paulbf87!

You appear to have posted a live example (http://jsbin.com/zonulo/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 69, column 79: Bad value ```` http:youtube.com ```` for attribute ```` href ```` on element ```` a ````: Expected a slash ("/").
* line 78, column 9: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 59, column 26: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by paulbf87** [comment]
Js bin http://jsbin.com/hanoxu/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @paulbf87!

You appear to have posted a live example (http://jsbin.com/hanoxu/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 70, column 81: Bad value ```` //http:youtube.com ```` for attribute ```` href ```` on element ```` a ````: Illegal character in port.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by paulbf87** [comment]
Js bin   http://jsbin.com/hanoxu/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @paulbf87!

You appear to have posted a live example (http://jsbin.com/hanoxu/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 26, column 4: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by paulbf87** [comment]
Js bin   http://jsbin.com/poteve/1/edit?html,output

Android 4.3.0
Chrome 41.0.2272.96

**Comment by twbs-lmvtfy** [comment]
Hi @paulbf87!

You appear to have posted a live example (http://jsbin.com/poteve/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 5, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 6, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by paulbf87** [comment]
Js bin...http://jsbin.com/xuqito/1/edit?html,output
Android 4.3.0
Chrome 41.0.2272.96

**Comment by twbs-lmvtfy** [comment]
Hi @paulbf87!

You appear to have posted a live example (http://jsbin.com/xuqito/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 73, column 81: Bad value ```` //http:youtube.com ```` for attribute ```` href ```` on element ```` a ````: Illegal character in port.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by paulbf87** [comment]
Js bin.....http://jsbin.com/xuqito/1/edit?html,output
Android 4.3.0
Chrome 41.0.2272.96

**Comment by mdo** [comment]
Your nabber markup is not accurate—you're missing the `.navbar-header`. https://jsbin.com/kezena/1/edit
