### ISSUE TITLE
Missing carets in bootstrap v3.3.4 in IE8

### ISSUE THREAD

**Issue by someatoms** [twbs/bootstrap#16172]
Bootstrap v3.3.4 made carets go missing in IE8. Here is a [JSFiddle](https://jsfiddle.net/DTcHh/5998/) and here [screenshots](http://www.browserstack.com/screenshots/40d8e690eb74383adaa28a951cbba4817b804b3c) for IE8-IE10 (only IE8 is missing the caret). Reverting #15697 makes IE8 happily show carets again however. 

In my projects I add a `.legacy-ie` class to the html element if <=IE9 so for me this can easily be fixed by adding this `.legacy-ie .caret { border-top: @caret-width-base solid;  }`. However, I suppose bootstrap 3 supports IE8 and this should be fixed officially?

**Comment by twbs-lmvtfy** [comment]
Hi @someatoms!

You appear to have posted a live example (https://fiddle.jshell.net/DTcHh/5998/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 38, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by someatoms** [comment]
Revised example with button type: https://jsfiddle.net/DTcHh/5999/

**Comment by cvrebert** [comment]
Perhaps we should add something like `border-top: @caret-width-base solid\9;` to hack this for IE8.
