### ISSUE TITLE
Cannot vertically scroll page when scroll gesture is within .responsive-table

### ISSUE THREAD

**Issue by atragan** [twbs/bootstrap#16184]
Hi,

i have a responsive table with 100 rows and when i am in the mobile view there is no way to scroll the table vertically. Is there anything that i am doing wrong or this is something that Bootstrap doesn't support?

**Comment by mdo** [comment]
Bootstrap doesn't support vertical scrolling in tables on mobile, but you can add that with a `max-height` and some `overflow-y: scroll`.

**Comment by atragan** [comment]
the problem that i have is if a user wants to scroll the viewport up or down and tries to do that when he has clicked inside the table, then the scrolling doesn't work (nothing happens). If the user tries to scroll the viewport and he has clicked anywhere else apart from the table, then the viewport is scrolled.

You can see the attachment if it helps.

Andreas
[screenshot](https://cloud.githubusercontent.com/assets/1902714/6915525/63d2632e-d79d-11e4-8534-3970fe7ecb2e.png)

**Comment by russplaysguitar** [comment]
I had a similar problem with `table-responsive` preventing vertical scrolling of a parent div with `overflow: auto`. Resolved it by adding `-webkit-overflow-scrolling: touch;` to the parent div. In case anyone else has this issue.

**Comment by cvrebert** [comment]
Looks like this bug report was misinterpreted due to some unclear phrasing in the description. Reopening.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by nawlbergs** [comment]
For anyone who ends up here looking for temporary fixes/hacks:
http://stackoverflow.com/questions/21706505/bootstrap-responsive-table-not-scrolling-vertically-on-ios-devices/26885539#26885539

-webkit-overflow-scrolling: touch;  // apparently this can resolve the issue by adding it to the parent dom element that is causing the bug.

**Comment by Nenrikido** [comment]
I just had this issue and an other fix is to remove the potential `height:100%` from the element you want to scroll on (and of course containing an `overflow:scroll` rule) and to add a fixed or responsive height such as `height:100vh`.
This worked perfectly for me
