### ISSUE TITLE
problem with navbar collapse when navbar itself is *not* on small screen

### ISSUE THREAD

**Issue by edson-** [twbs/bootstrap#16189]
See issue here: http://stackoverflow.com/questions/28472815/bootstrap-navbar-collapse-not-closing-on-click/29370053#29370053

My temporary solution works (edson-), but would like to see something in bootstrap permanently that can handle this.

**Comment by patrickhlauke** [comment]
I'm afraid having a collapsed navbar on anything other than small screens is not officially supported by Bootstrap, so we won't be able to assist you in fixing your specific implementation.

**Comment by edson-** [comment]
I may not have been clear, I don't want to collapse the navbar on larger screens.  I rather don't want the 'blinking' issue when the navbar is (uncollapsed) on larger screens.

**Comment by patrickhlauke** [comment]
Please restate your exact problem, ideally providing a link to a live example or jsfiddle that illustrates the issue.

**Comment by edson-** [comment]
See: http://jsfiddle.net/mikeedson/v2gosj5s/9/

Desired Functionality: When Navbar is collapsed and menu is open, then when the user makes a selection, all menus will close.

To Repeat:
1. Shrink the width of the Result pane until the Navbar collapses
2. Open the menu
3. Select a Choice
4. See menus close

This works as intended.

The Issue:  When Navbar is not collapsed, then when the user makes a selection, the items in the Navbar disappear and redraw.

To Repeat 1:
1. Extend the width of the Result pane until the navbar is *not* collapsed
2. Select Choice A
4. Watch the Navbar choices disappear then redraw

To Repeat 2:
1. Extend the width of the Result pane until the Navbar is *not* collapsed
2. Select the Dropdown
3. Select a Choice F
4. Select Choice G (may or may not be necessary)
5. Watch the entire Navbar expand and then redraw

**Comment by twbs-lmvtfy** [comment]
Hi @edson-!

You appear to have posted a live example (http://fiddle.jshell.net/mikeedson/v2gosj5s/9/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 46, column 69: Bad value ```` banner ```` for attribute ```` role ```` on element ```` nav ````.
* line 56, column 43: Element ```` img ```` is missing required attribute ```` src ````.
* line 72, column 114: Attribute ```` {{bind-attr ```` not allowed on element ```` li ```` at this point.
* line 73, column 114: Attribute ```` {{bind-attr ```` not allowed on element ```` li ```` at this point.
* line 74, column 114: Attribute ```` {{bind-attr ```` not allowed on element ```` li ```` at this point.
* line 75, column 114: Attribute ```` {{bind-attr ```` not allowed on element ```` li ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Ah, yeah, we don't support that behavior in Bootstrap I'm afraid. If you want to modify the navbar to collapse on click of those menu items, you'll need to do a bit more work than adding just the data attributes I'm afraid.

We've no intention of updating v3's navbar to account for this either. It'd be a decent amount of work and we're limiting the changes to v3 to continue focused development of v4.

**Comment by edson-** [comment]
Thanks for letting me know.  Will this be part of  v4?
