### ISSUE TITLE
focus ring of image map within modal gets displayed in wrong place in Chrome

### ISSUE THREAD

**Issue by adityashankert** [twbs/bootstrap#16180]
if i click on image map then the border should be surrounding the image map area but if the image map is on modal the border is getting displayed at different place.

http://jsbin.com/meyejikife/1/edit?html,output -- image map on modal
http://jsbin.com/xekupejite/2/edit?html,output -- image map on normal page

browser - chrome
os - centos

**Comment by twbs-lmvtfy** [comment]
Hi @adityashankert!

You appear to have posted a live example (http://jsbin.com/henuyoliyi/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 29, column 97: Element ```` area ```` is missing required attribute ```` alt ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @adityashankert!

You appear to have posted a live example (http://jsbin.com/wofecilodo/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 15, column 97: Element ```` area ```` is missing required attribute ```` alt ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
* Please upgrade to Bootstrap v3.3.4
* Please state which browser(s) and OS(es) you've experienced the problem on.

**Comment by adityashankert** [comment]
@cvrebert added all the required details and upgraded bootstrap

**Comment by cvrebert** [comment]
Reposting to force revalidation: http://jsbin.com/meyejikife/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/meyejikife/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@adityashankert To clarify, when you say "border", are you referring to the `:focus` styling, specifically the difference between the locations of the circles in
![good-regular](https://cloud.githubusercontent.com/assets/419884/7041376/ae3f1e2a-dd8d-11e4-9df5-899627ab7ae5.png)
versus
![bad-modal](https://cloud.githubusercontent.com/assets/419884/7041382/b9e74de2-dd8d-11e4-8e83-1daabbfbdabc.png)
?

**Comment by adityashankert** [comment]
@cvrebert  yes exactly

**Comment by cvrebert** [comment]
This would appear to be a bug in WebKit/Blink.
Safari 8.0.4 also suffers from this bug.

**Comment by cvrebert** [comment]
Tweaked the fiddle to get rid of the lint: http://jsbin.com/hofuni/2/edit

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=143527

**Comment by cvrebert** [comment]
Filed Chrome bug: https://code.google.com/p/chromium/issues/detail?id=475128

**Comment by adityashankert** [comment]
great man you guys rock !!

**Comment by bhanuprakash-rb** [comment]
good work guys.. thanks a lot

**Comment by cvrebert** [comment]
Fixed in WebKit: http://trac.webkit.org/changeset/199247
