### ISSUE TITLE
label gets misaligned in navbar

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#16182]
http://www.bootply.com/QK8xizMUE1

When using a `<span class="label label-default">Label</span>` in a navbar it gets misaligned.

**Comment by twbs-lmvtfy** [comment]
Hi @vanillajonathan!

You appear to have posted a live example (http://s.bootply.com/render/QK8xizMUE1), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 66, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by vanillajonathan** [comment]
With 3.3.4 (sorry Bootply had outdated Bootstrap references).
http://jsbin.com/rasezoqeba/1/

**Comment by twbs-lmvtfy** [comment]
Hi @vanillajonathan!

You appear to have posted a live example (http://jsbin.com/rasezoqeba/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by vanillajonathan** [comment]
Updated to comply with Bootlint.
http://jsbin.com/vusajiwawe/1/

**Comment by vanillajonathan** [comment]
Seems this was solved by wrapping the label in `<p class="navbar-text">`. Sorry.
