### ISSUE TITLE
should remove height:auto from .img-responsive

### ISSUE THREAD

**Issue by argb** [twbs/bootstrap#16196]
in bootstrap there is a mixin 

```
// Responsive image
//
// Keep images from scaling beyond the width of their parents.
.img-responsive(@display: block) {
  display: @display;
  max-width: 100%; // Part 1: Set a maximum relative to the parent
  height: auto; // Part 2: Scale the height according to the width, otherwise you get stretching
}
```

note that the last statement-> `height:auto` ,This is really bad idea,I need to set a fixed size image attribute like `<img width="300px" height="200px".../>`,but you know it don't work, so i want to override the mixin to this:

```
.img-responsive(@display: block) {
  display: @display;
  max-width: 100%; // Part 1: Set a maximum relative to the parent
}
```

you know it don't work too,so bad...
bootstrap shouldn't set the style,and less should let me override it,both are wrong!
most time we don't need the height:auto,cause I need fixed size in `<img>` tag,this performance better for browser too,problem is there no way to disable it in css ,if i set a new number value,it's not what I want.

**Comment by zacechola** [comment]
There is a comment right on the `height: auto` portion explaining why it is there. We need it to scale responsive images, otherwise we get images that will have an incorrect aspect ratio.

If you need your images to not be responsive, simply omit the `.img-responsive` class from your markup.

**Comment by mdo** [comment]
Yeah, we need that in there I'm afraid.

**Comment by ntung** [comment]
I often scale my images keep ratios and then using img-responsive without height.
