### ISSUE TITLE
(3.3.4) If a modal is open on page load and then closed, the entire page blinks black.

### ISSUE THREAD

**Issue by joakim-m** [twbs/bootstrap#16191]
Had to go back to 3.3.2.

**Comment by cvrebert** [comment]
We cannot help unless you post a JS Bin that demonstrates the problem.

**Comment by lpaluszk** [comment]
I'm not sure if this is related, but it seems that backdrop is no longer rendered inside the .modal div.

I stumbled on this while investigating another issue where modal started leaving the backdrop behind after being removed while transitioning from page to page in my ember app.

See this JSBin:
http://emberjs.jsbin.com/hiqame/2

Flick between page 1 and 2 before you click any of the buttons and then use the browser's back button. You will notice that the backdrop stays after the modal is removed. 

Editing this JSBin to use Boostrap 3.3.2 fixes it.

Should I open another issue or is this related?

**Comment by cvrebert** [comment]
@lpaluszk We indeed changed where the backdrop is in the DOM. We can't provide help with examples involving third-party libraries such as Ember though.

**Comment by lpaluszk** [comment]
No problem. Is it by design and is it going to stay going forward? I'll just adapt, no problem, it just seems like a breaking change.

**Comment by cvrebert** [comment]
It's an intentional change. We've been treating the backdrop location as an implementation detail thus far.

@joakim-m Have a JS Bin example of your problem handy?

**Comment by cvrebert** [comment]
Closing for now due to lack of response from @joakim-m.
