### ISSUE TITLE
IE8 html5shiv, respondjs and Starting template order

### ISSUE THREAD

**Issue by julianxhokaxhiu** [twbs/bootstrap#16195]
Hi,

today I was working on a project with Bootstrap where I had to fix some issues that I had on IE8 that I thought they were already been covered.

The issues were mostly related to HTML5 tags used here and there and to media queries that were not really working.

What I've found strangly is that somehow the order of the scripts you've put on the starting template is not really working well for IE8 while this other one is perfectly working: HTML5 tags are parsed correctly, and media queries are working too.

Can you please explain me why? Also based on plugins logic it seems that this order is more correct than yours. 

Thank you in advice for any tip given :)

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    // We load this becuase html5shiv needs it
    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

    // Then we load jQuery this way to make sure we load jQuery 2.x on modern browsers, but jQuery 1.x for IE8 and lower
    <!--[if (!IE)|(gt IE 8)]><!-->
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <!--<![endif]-->
    <!--[if lt IE 9]>
      <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

      // We load HTML5 Shiv before any CSS have been applied because we have to make sure that HTML5 tags are really parsed and "valid" for IE8 to be styled
      <script src="//oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <![endif]-->

    // CSS Styles here
    <link ...>

    // We load respond js here AFTER the CSS, so it can really parse media queries
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Other scripts here -->
  </body>
</html>
```

**Comment by cvrebert** [comment]
getbootstrap.com and our examples work fine in IE8 as far as we can tell.
For help troubleshooting your particular site, try asking on StackOverflow.
Also, html5shiv doesn't need modernizr.
