### ISSUE TITLE
transition.js : why wait for document ready before testing transitionEnd() ?

### ISSUE THREAD

**Issue by fadomire** [twbs/bootstrap#16199]
I'm surely missing something obvious, but i don't see why we should wait for document ready before testing for transitionEnd support

```javascript
  $(function () {
    $.support.transition = transitionEnd()
  })
```

Here is the transitionEnd() function

```javascript
  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }
```

**Comment by cvrebert** [comment]
Does the `git blame` for the file (possibly via GitHub's Blame view) turn up anything that might explain it?

**Comment by fadomire** [comment]
i did git blame and it did not gave me any explanation

also i went back to version 2.0 and this document ready wrapper was already there even if code inside differ of course

**Comment by Johann-S** [comment]
I think it's because we have to wait for document ready to use the ``$`` of JQuery

**Comment by peterblazejewicz** [comment]
@fadomire 
I think that while implementation solution is similar to Modernizr:
https://github.com/twbs/bootstrap/commit/30b3f47e31487b9f7db6a42ed633597c3f5e764c#diff-b3500ed8c2c9ff753e3220ca808f9b72L27
, so it technically can be used without jQuery, it's internal to custom transition events and dedicated plugin, used only one time during plugin initialisation to set custom browser features detection status:
https://github.com/twbs/bootstrap/blob/master/js/transition.js
http://api.jquery.com/jquery.support/
Thanks!

**Comment by fadomire** [comment]
@Johann-S you don't need to wait for document ready to use $

@peterblazejewicz not sure i get your point. Is it, according to you, required to wait for document ready in the case of the transition plugin initialisation ?

PS : i asked this question because in the version of bootstrap i use, it caused an issue where $.support.transition.end was used in collapse.js before document ready was fired, which cause an error

This problem does not occurs in the current version

**Comment by fat** [comment]
yep, no reason to wait. i'll make sure to get this changed for v4 – meanwhile, if you really want this changed in v3, feel free to open a pr – seems pretty harmless
