### ISSUE TITLE
inclusion of sprites 

### ISSUE THREAD

**Issue by ryanstua** [twbs/bootstrap#16192]
I have added sprites to my website to reduce the HTTP requests.

Before I did this the site worked perfectly on mobile devices in terms of the width didn't needed scrolling to see the nav button and modals i have linked.

You now have to scroll to see the navbutton and I am not sure how to resolve this. 

Has anyone come across this before?

**Comment by patrickhlauke** [comment]
Unfortunately we can't help you with specific implementation questions. Please refer to StackOverflow or similar forums.
