### ISSUE TITLE
translate3d(0,0,0) and fixed position child elements

### ISSUE THREAD

**Issue by djcowan** [twbs/bootstrap#16209]
There appears to be an issue where children of an element set to `transform3d(0,0,0)` - don't position correctly when set to `position: fixed`.
`.navbar-fixed-top {
  transform: translate3d(0,0,0);
 position: static;
}`
`.navbar-fixed-top .navbar-header {
  position: fixed;
}`

Setting `transform: none` appears to correct the behaviour.
....
Mac Os 10.10.2 -> Chrome - Version 41.0.2272.104 (64-bit)

**Comment by cvrebert** [comment]
Are you not using Bootstrap v3.3.4?
X-Ref: #14667

**Comment by djcowan** [comment]
Thank you > CND loaded bootstrap >  my apologies for raising a known issue.

**Comment by cvrebert** [comment]
"CND" ?

**Comment by mdo** [comment]
Probably a typo, CDN :).

**Comment by jawedkhan** [comment]
best
