### ISSUE TITLE
".close" class conflicting

### ISSUE THREAD

**Issue by pensierinmusica** [twbs/bootstrap#16206]
Hi,

In a recent website project with Bootstrap I was having some conflicts with the `.close` CSS class.

Since it's a pretty common class name to be used in many different contexts, wouldn't it be better to use something more specific in Bootstrap (e.g. `.close-icon`)?

It looks like I'm not the only one having this issue: https://github.com/ccampbell/rainbow/issues/101

**Comment by mdo** [comment]
Can't make any changes for that in v3 for backward compatibility, but maybe in v4.
