### ISSUE TITLE
Affix doesn't update in iOS UIWebview

### ISSUE THREAD

**Issue by mhemesath** [twbs/bootstrap#16202]
In UIWebview scroll events aren't fired. This has the effect of making affix look buggy as its position isnd't updated until after scroll is done.  To mitigate the effects of this, we could add a touchmove event listener to update the affix position when the user is scrolling via moving their finger.

```js
    this.$target = $(this.options.target)
      .on('scroll.bs.affix.data-api', $.proxy(this.checkPosition, this))
      .on('touchmove.bs.affix.data-api', $.proxy(this.checkPosition, this))
      .on('click.bs.affix.data-api',  $.proxy(this.checkPositionWithEventLoop, this))

```

**Comment by cvrebert** [comment]
What version of iOS are you using?

**Comment by mhemesath** [comment]
iOS 8.2

**Comment by cvrebert** [comment]
Does http://stackoverflow.com/a/10880812 not work?

**Comment by mhemesath** [comment]
That doesn't solve the issue.  The view can scroll, it just doesn't fire any scroll events while it is going. This causes the affix to not "stick" until after scroll ends.

**Comment by cvrebert** [comment]
Does WKWebView suffer from the same problem?

**Comment by mhemesath** [comment]
No, I haven't tested it but from what I've read the WKWebview is similar to the native Safari in iOS 8.X and will throw scroll events while scrolling. This is only a a problem for UIWebview in iOS.

**Comment by cvrebert** [comment]
Okay, have you tried https://poschel.wordpress.com/2013/08/29/uiwebview-javascript-scroll-events-in-ios-7/ ?

**Comment by cvrebert** [comment]
@mhemesath Have you gotten a chance to try the other workaround I linked to above?

**Comment by mhemesath** [comment]
Sorry, that didn't seem to work either.   We are getting scroll events, just not until after scroll is over. I can try to throw together a test page that should be reproducible with Chrome on iOS (which uses webview I think).

**Comment by cvrebert** [comment]
Can you post what the UIWebview uses as its user agent string?

**Comment by mhemesath** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_10_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12D508

**Comment by cvrebert** [comment]
So, my research didn't turn up any way to differentiate between UIWebView vs. WKWebView via JS.
UIWebView can be distinguished from Safari by looking for the "Version/" token in the user agent, which is present in Safari but absent in both types of webview.

@fat What are your thoughts here, given the possible performance penalty of a touch event handler?

**Comment by fat** [comment]
I'm inclined not to add this directly into the plugin. Mobile scroll stuff has always been kinda jank and I'm a bit worried about potential sideeffects of adding the touchmove for all cases.

Also, i feel better about passing on this because it seems like there are a couple of straightforward ways to get this behavior in your app – you could subclass Affix pretty simply or just write a quick little script to pipe touchevents through for your specific target/instance.

**Comment by cvrebert** [comment]
Added a note about this to MDN: https://developer.mozilla.org/en-US/docs/Web/Events/scroll#iOS_UIWebView

**Comment by Shasharoman** [comment]
try use touchstart event on element and do nothing, but scroll events aren't fired when fingers leave the screen.

**Comment by cvrebert** [comment]
Affix is no longer officially supported; see https://v4-alpha.getbootstrap.com/migration/#components
