### ISSUE TITLE
Tooltip cuts spaces between buttons in WebKit-based browsers

### ISSUE THREAD

**Issue by fend25** [twbs/bootstrap#16200]
Tooltip cuts spaces between buttons if there is `<ul>` tag in the div with tooltipped button.
Bug is reproduced in Chrome 41, Safari 8 (on mac and android, most likely in windows too).
Bug is not reproduced in Firefox 36, IE 11. Both mac and windows.
All browsers are stable and up-to-date.
Example:
http://jsfiddle.net/oq3cajed/2/      UPD: fixed lmvtfy's warnings
How to reproduce:
Move the mouse over buttons in the first row, press button "click me", and move mouse again. And over the second row of buttons.
Buttons will stick to the left when the `<ul>` is shown and get back when it is hidden or absent.
Used latest jquery and bs.

**Comment by twbs-lmvtfy** [comment]
Hi @fend25!

You appear to have posted a live example (http://fiddle.jshell.net/oq3cajed/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 36, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 37, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 38, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 45, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 46, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 47, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by zacechola** [comment]
This is a good example of when you'd want to use the `container` option due to where in the DOM the tooltip is added in your example code.

http://getbootstrap.com/javascript/#tooltips-options

Passing `{container: 'body'}` in as a tooltip option will solve the issue in your fiddle.

**Comment by fend25** [comment]
@zacechola 
Thank you very much, that worked.
