### ISSUE TITLE
Bootstrap 3 Tabs - Can't place links or lists inside tab content box

### ISSUE THREAD

**Issue by AmedeoD** [twbs/bootstrap#16214]
Tabs - Can't place links or lists inside tab content box, after initial link or list item, all other links/lists fall outside tab content box.

  
![screenshot_3](https://cloud.githubusercontent.com/assets/11775889/6971108/2717b6da-d948-11e4-86f5-609ffcde6a7a.png)

                                <div class="tab-content mb30">
                                    <div class="tab-pane active" id="home5">
                                        <h4 class="nomargin">Home title goes here...</h4>
                                        <div class="col-md-3">
                                        <ul>
                <li>Lorem ipsum dolor sit amet</li>
                <li>Consectetur adipiscing elit
                  <ul>
                    <li>Phasellus iaculis neque</li>
                    <li>Purus sodales ultricies</li>
                  </ul>
                </li>
                <li>Integer molestie lorem at massa</li>
              </ul>
                                            
                                      </div>
                                      <div class="col-md-9">Home right content goes here</div>
                                    </div>
                                  
                                    <div class="tab-pane" id="profile5">
                                        <h4 class="nomargin">Profile title goes here...</h4>
                                        <p>Profile content goes here</p>
                                    </div>
                                  
                                    <div class="tab-pane" id="about5">
                                        <h4 class="nomargin">About title goes here...</h4>
                                        <p>About content goes here</p>
                                    </div>
                                  
                                    <div class="tab-pane" id="contact5">
                                        <h4 class="nomargin">Contact title goes here...</h4>
                                        <p>Contact content goes here</p>
                                    </div>
                                </div>

**Comment by zacechola** [comment]
Please post a live [reduced text case](http://css-tricks.com/6263-reduced-test-cases/). [Here's a template you can use](http://jsbin.com/lefey/1/edit?html,output).

**Comment by mdo** [comment]
Your markup isn't valid for Bootstrap's grid system—you need a `.row` around those columns. Otherwise the `float`s are not cleared.
