### ISSUE TITLE
bug when tooltip template has text (e.g. new line character) in between <div>s

### ISSUE THREAD

**Issue by stelovsky** [twbs/bootstrap#16219]
When there is text in tooltip 'template' option (e.g. new line character), a bug is reported in jQuery. Tracing the bug leads to Tooltip.prototype.applyPlacement where on line 1500 $tip.offset(offset) is called and $tip contains 'text' nodes (which don't have offset, or at least ownerDocument.defaultView.getComputedStyle( elem, null ) doesn't want 'elem' to be 'text' when 'ownerDocument' is #document):

![image](https://cloud.githubusercontent.com/assets/1028809/6979427/a93cd1b8-d9e3-11e4-90c4-79ac137122a2.png)

$tip: jQuery.fn.init[7]
0: div#tooltip981716.tooltip.fade.bottom.in
1: text
2: div#tooltip981716.tooltip-arrow.fade.bottom.in
3: text
4: div#tooltip981716.tooltip-inner.fade.bottom.in
5: text
6: div#tooltip981716.fade.bottom.in
length: 7
....

This is the error message:

![image](https://cloud.githubusercontent.com/assets/1028809/6979650/f12d9b12-d9e6-11e4-8567-4371fe917e7d.png)

And this is the state:
![image](https://cloud.githubusercontent.com/assets/1028809/6979684/81ca4ae4-d9e7-11e4-9a1b-8fd548fed168.png)

The best would be to skip the text elements or at least the documentation of Tooltip should state that not even eonls are allowed in between the `<div>`s

**Comment by cvrebert** [comment]
Could you post a JS Bin that demonstrates the problem?

**Comment by stelovsky** [comment]
Hi Chis,

sure I can, but it's a part of a bigger project so pairing it down will
take some time, and I have urgent time commitments - so sometimes after Tu
should be more feasible...

Jan



Dr. Jan Stelovsky, Founder and CTO

www.parwinr.com, jan AT parwinr.com, +1-808-673-0035
2903 Bunker Hill Ln #150, Santa Clara, CA 95054


This electronic message transmission contains information from the Company
parWinr, Inc. that may be proprietary, confidential and/or privileged. The
information is intended only for the use of the individual(s) or entity
named above. If you are not the intended recipient, be aware that any
disclosure, copying or distribution or use of the contents of this
information is prohibited. If you have received this electronic
transmission in error, please notify the sender immediately by replying to
the address listed in the "From:" field.

**Comment by cvrebert** [comment]
Presumably your `template` consists of more than 1 top-level element, which isn't valid (hence the likewise invalid repetition of the same autogenerated ID). Example: http://jsfiddle.net/7a2eutbt/3/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/7a2eutbt/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 38, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
