### ISSUE TITLE
Iframe in Chrome, after add padding-left & padding-right, The content can't respond to media quiries

### ISSUE THREAD

**Issue by blade254353074** [twbs/bootstrap#16227]
Iframe in Chrome, after add padding-left & padding-right, The content can't respond to media quiries

<iframe src="http://getbootstrap.com/css/#grid-example-basic" style="width: 100%;height: 500px;padding: 0 15px;" frameborder="0"></iframe>

**Comment by blade254353074** [comment]
![qq 20150404120737](https://cloud.githubusercontent.com/assets/9346008/6991381/61a3c22c-dac3-11e4-9e21-97113b814168.png)

**Comment by mdo** [comment]
We'll need a reproducible JS Bin example if you wish us to try to debug this. I've not seen any problems with using our media queries in iframes to-date though.

**Comment by cvrebert** [comment]
Closing this until/unless the requested JS Bin gets posted.
