### ISSUE TITLE
How to add two top fixed navigation bar?

### ISSUE THREAD

**Issue by svyasaraj** [twbs/bootstrap#16221]
If we add two top fixed class navigation code, its meshing in same place, and if I give padding to make them visible independently, in responsive view not showing properly.

Please tell me some solution, how to fix it?

**Comment by patrickhlauke** [comment]
Having two fixed top navigation bars is not supported by Bootstrap. You will need to hack your own solution for it. Please refer to places like StackOverflow for a possible solution.
