### ISSUE TITLE
Icons showing as Boxes or Upside down U

### ISSUE THREAD

**Issue by willshattuck** [twbs/bootstrap#16228]
Hi, I don't actively use Bootstrap, but I've noticed an issue that may be related to Bootstrap.  

I'm using Google Chrome v.41 (current as of 2015/04/03) and I am noticing more sites (including github.com) have some icons that don't show up.  They appear as a box or an upside down U. 

http://imgur.com/EoaeNJn

The link above shows what I am currently seeing on github and on other sites.  The boxes (when I Inspect Element) all seem to possibly be related to glyph icons or something UTF-8 in Bootstrap that isn't rendering correctly on my version of Google Chrome.

Is there something I can do within my system or browser so I can see the icons that aren't showing up?  Sometimes I can see the icons if I switch to Firefox, but that doesn't always work.

Thanks,
Will

**Comment by mdo** [comment]
No idea I'm afraid. If it's happening to GitHub's and Bootstrap's icons though, it's not likely a bug in our code. There's no overlap on that front. Could just be a bug in Chrome.
