### ISSUE TITLE
Font in code blocks does not distinguish { and ( clearly

### ISSUE THREAD

**Issue by nouyang-curoverse** [twbs/bootstrap#16225]
font in code blocks on http://getbootstrap.com/ does not distinguish { and ( clearly, can cause anguish for newcomers to javascript. Please remove the `Courier New` font fallback option. Just `monospace` works well.

_In Detail_

I was following the the example at http://getbootstrap.com/javascript/#carousel, and my brain removed the "extra parenthesis" I think, similar to how you don't notice I doubled "the" in this sentence unless I point it out.

This is a screenshot of the bootstrap website "code" block font currently on my computer:
![js-bootstrap-font](https://cloud.githubusercontent.com/assets/8737224/6989290/d6810434-da27-11e4-8750-f66478053021.png)

Please remove the `courier new`  font fallback option. Just `monospace` works well.

     code, kbd, pre, samp {
       font-family: monospace;
     }

Results in the much-better 

![js-bootstrap-font-better](https://cloud.githubusercontent.com/assets/8737224/6989328/3c902412-da28-11e4-8ead-51536edfc817.png)

**Comment by cvrebert** [comment]
What OS and browser are you using?

**Comment by mdo** [comment]
Without any more information, I don't see a strong enough reason to remove a rather common font from the stack, especially having been there since the open sourcing of Bootstrap. I'm always open to improving things, but with good reason. Please update us with anything new, though!

**Comment by nouyang-curoverse** [comment]
@cvrebert  I am using Firefox / google chrome / chromium, Ubuntu 14.04. 
![bootstrapwebsite-fontissue](https://cloud.githubusercontent.com/assets/8737224/7482791/fb3722c0-f347-11e4-9636-3d131cdbd85d.png)

@mdo updated with requested information, thanks. Apologies as I was not getting github notifications.

**Comment by cvrebert** [comment]
Seems okay as-is to me, but I'm not a typographer or visual designer.
@mdo WDYT?

**Comment by mdo** [comment]
Yeah, I'm still not convinced this is a large enough issue to warrant a font stack change (which has been unchanged for nearly three years).
