### ISSUE TITLE
Fix for modal close on mobile

### ISSUE THREAD

**Issue by cavanm** [twbs/bootstrap#16236]
On narrow screens (not just mobile) a modal's floated "close" button can be covered by following content and therefore become unclickable. Adding `position: relative; z-index:100;` as shown below solves that issue.

`<button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="position: relative; z-index: 100">&times;</button>`

I would like to recommend that these properties be added to the `close` class so that others will not have this issue.

I ran into this issue when using a modal that had the following structure.
```
...
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <div class="row">
        <div class="col-md-3">
            <div>
                <img src="image.png" width="135" height="135">
            </div>
        </div>
        <div class="col-md-3">Other Content</div>
        ... More columns here...
    </div>
</div>
...
```

**Comment by cvrebert** [comment]
Please post a full JS Bin example that demonstrates the problem.

**Comment by cavanm** [comment]
I can't make a modal work on JS Bin at all and I am in crunch mode so don't have time to work it out. If anyone else has had this problem they can create the JS Bin example and post the link here.

**Comment by mdo** [comment]
I'm curious why you have a row and column in the header around a single image. The grid is probably interfering with things there.

**Comment by cavanm** [comment]
There are actually several other columns after the image that I need but I omitted them in the example above because it is the first column that ends up overlaying the close button when the screen width is reduced. The grid is certainly interfering with things. That is why I suggested the fix to bring the close button forward.

**Comment by mdo** [comment]
I think for the time being we'll close this as a won't fix.

- It's definitely the grid, paired with the `float`ed `.close` that's causing the problem.
- Using the grid in the modal header feels like overkill, but it's hard to tell from that example.
- Adding `position: relative;` sounds fine to me, but adding any `z-index` sounds like it'd lead to further problems with layering.
- We don't currently `z-index` anything *within* the modal. I don't think we need to try to anticipate and address those use cases ourselves either.
