### ISSUE TITLE
Links in labels

### ISSUE THREAD

**Issue by gable44** [twbs/bootstrap#16231]
Hello!

` <span class="label label-info">Some text <a href="#">a link</a> some text</span> `

In this case the link is almost unseen because of the color of the "info label"

**Comment by mdo** [comment]
Labels aren't designed to handle anything more complicated than text and icons within them. You'll need to account for these kind of variations on your own, though I wouldn't recommend nesting links within such a small element. Labels—and badges—are about as small and focused of a component as you can get in Bootstrap and other UI systems.
