### ISSUE TITLE
Contenteditable div cursor outside of div

### ISSUE THREAD

**Issue by TheColorRed** [twbs/bootstrap#16237]
When making a `contenteditable` `div`, the cursor is placed on the inside of the div. 

* When you type something, then delete what was typed, the cursor displays on the outside of the div. 
* After deleting then clicking out of the div then clicking back on the div again, the cursor is outside of the div.

This image shows the cursor outside of the div:

![Div][1]

JSFiddle demonstration: http://jsfiddle.net/y3ms3f7a/4/

Here is an example:

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-control" contenteditable="true" id="tags">
                    <div contenteditable="false" class="tag">one <a href="" class="glyphicon glyphicon-remove"></a></div>
                    <div contenteditable="false" class="tag">two <a href="" class="glyphicon glyphicon-remove"></a></div>
                </div>
            </div>
        </div>
    </div>

Here is the extra css attached to it:

    .tag{
        background-color: #01b6ef;
        color: #012935;
        display: inline-block;
        padding: 1px 5px;
        margin-right: 3px;
    }

    .tag a{
        color: #ffffff;
        margin-left: 5px;
        font-size: 12px;
    }
    .tag a:hover{
        color: #ffffff;
    }

  [1]: http://i.stack.imgur.com/u61BM.png

**Comment by cvrebert** [comment]
What OS and browser are you using?

**Comment by cvrebert** [comment]
Trying to force revalidation:
http://jsfiddle.net/y3ms3f7a/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/y3ms3f7a/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 53, column 3: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by TheColorRed** [comment]
I am using Chrome 41.x on Ubuntu, someone also tried on Windows 8.1 with Chrome 41.x also and same thing.

**Comment by TheColorRed** [comment]
http://jsfiddle.net/y3ms3f7a/3/

**Comment by twbs-lmvtfy** [comment]
Hi @TheColorRed!

You appear to have posted a live example (http://fiddle.jshell.net/y3ms3f7a/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 53, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by TheColorRed** [comment]
http://jsfiddle.net/y3ms3f7a/4/

**Comment by cvrebert** [comment]
Putting `.form-control` on a `div` isn't valid.

**Comment by cvrebert** [comment]
X-Ref: https://github.com/twbs/bootlint/pull/263

**Comment by TheColorRed** [comment]
This should be valid, or there should be something that formats a div in a similar way as an input field since divs can be editable and act as a formattable form element.

**Comment by TheColorRed** [comment]
@cvrebert 

I found that I can solve the issue using an `input-group` within the `form-control` and it seems to work:

    <div class="form-group">
        <label for="tags" class="col-sm-2 control-label">Tags</label>
        <div class="col-sm-10">
            <div class="form-control" contenteditable="true" id="tags">
                <div class="input-group">
                    {foreach item=row from=$tags}
                        <span contenteditable="false" class="tag"><span class="text">{$row.tag}</span> <a href="" class="glyphicon glyphicon-remove"></a></span>
                        {/foreach}
                </div>
            </div>
        </div>
    </div>

**Comment by cvrebert** [comment]
X-Ref: #15486. `contenteditable` styles are off the table until Bootstrap v4.
For now, the closest thing we have is `.form-control-static`.

**Comment by TheColorRed** [comment]
Okay, sounds good. Thanks for the input!

**Comment by mattmcardle** [comment]
Has anyone found a valid fix for this issue? I am having the same occur when I have button groups inline in a contenteditable div and using the (invalid) `.form-control` `.input-group` fix suggested by @TheColorRed is not working for me
