### ISSUE TITLE
fixed width in containers gives horizontal scroll on page

### ISSUE THREAD

**Issue by happy2deepak** [twbs/bootstrap#16235]
.container {widths} at viewport width of 1000px and 780px adds a horizontal scrollbar in the page.

**Comment by peterblazejewicz** [comment]
@happy2deepak can you make example for review using JSBin.com or similar service? Here you can find BS template:
http://jsbin.com/lefey/1/edit?html,output

**Comment by mdo** [comment]
If you're referring to the docs, we addressed this in #16208. We'll re-open if you provide a JS Bin demo or other reproducible example.

**Comment by happy2deepak** [comment]
Hi there, I checked it again in other browsers. 
I just found that, it happens if a website is long enough to get a vertical scroll, then due to the width of that vertical **Scrollbar**, width of **.container** leads to horizontal scroll on the page.
I found it on Chrome and Firefox browser. (I don't know, if its really a issue or not, but reporting it as I encountered)

attaching the screenshots taken for http://getbootstrap.com/css/ page.
Screenshots were taken, When i resized my browser to 
992px to 1001px wide
Also occurs at 768px to 781px wide

![chrome](https://cloud.githubusercontent.com/assets/1978524/6998065/d5736278-dbf1-11e4-8694-9daeedfd294d.PNG)
![firefox](https://cloud.githubusercontent.com/assets/1978524/6998066/d579082c-dbf1-11e4-986f-fbd5211369d9.PNG)

**Comment by cvrebert** [comment]
@happy2deepak Please re-test; we deployed the fix in #16208 to getbootstrap.com (via e9c6ae1098f0aa1d3bced285a6690e22b030b80a) a couple days after you conducted your previous test.

**Comment by happy2deepak** [comment]
@cvrebert yes, its fixed.

**Comment by cvrebert** [comment]
Great!
