### ISSUE TITLE
[3.3.4] just only the first tab working with javascript, why?

### ISSUE THREAD

**Issue by fatihmert** [twbs/bootstrap#16241]
Hello guys,

I created message system with tabs. So there is following;
![twitter-bootstrap-3-message-system](http://i.stack.imgur.com/QOgAF.png)

I am just sending to **Mustafa** member', I can't send to **Alican** member'. This page's design before left side (so tab-title) get php listing to messages titles (with MySQL DISTINCT). Then so the same code getting messages.

**In the fact, first tab working. 2nd, 3rd , .. , Nrd tabs doesn't work with javascript action**

*All this page's code I linked paste.bin: http://pastebin.com/ekqf7dL9*

The Yellow button, (so it is "submit button") jquery posting with ajax my request to php file. There is its code;

```php
<button m_isim="<?php echo $_SESSION['uyeIsim'];?>" m_atan="<?php echo $_SESSION['uyeId'];?>" m_alan="<?php echo $msjGelenUye['mesaj_alan_id'];?>" class="btn btn-warning btn-sm" id="btn-chat">Gönder</button>
```

*Information about the variable*

```php
$_SESSION['uyeIsim'] -> user name
$msjGelenUye['mesaj_alan_id'] -> user reciever
m_atan -> transmitter
```

jQuery post code following;

```js
$("#btn-chat").click(function(event){
    var msjGonderenData = {
        "mesaj_atan_id" : $(this).attr('m_atan'), //user transmitter
        "mesaj_alan_id" : $(this).attr('m_alan'), //user receiver
        "mesaj"         : $("#btn-chat-input").val() //message content
    };

    var msjAtanIsim = $(this).attr('m_isim'); //transmitter name

    //alert(msjGonderenData['mesaj']);  //just control, This is "Mustafa" working but "Alican" doesn't work

    $.ajax({
        type        :"POST",
        url         :"inc/request/msjGonder.post.php",
        data        :msjGonderenData,
        success     :function(cvp){
            if(cvp != "1"){
                $(".postCevap").html(cvp);
            }else{
                //add current message list sent message
                $("ul#"+msjGonderenData['mesaj_alan_id']+".chat").append("<li class=\"right clearfix\"><span class=\"chat-img pull-right\"><img src=\"http://placehold.it/50/FA6F57/fff&text="+msjAtanIsim+"\" alt=\"\" /></span><div class=\"chat-body clearfix\"><div class=\"header\"><small class=\"text-muted\"><span class=\"glyphicon glyphicon-time\"></span>&nbsp;Şimdi</small><strong class=\"pull-right primary-font\">"+msjAtanIsim+"</strong></div><p>"+msjGonderenData['mesaj']+"</p></div></li>");
            }
        }
    });
});
```

**You must read This line (starting `//alert(msjGonderenData['mesaj']);`) note.**

How do solve this ? Thank you for interest.
Best regards..

**Comment by cvrebert** [comment]
Please post your example as a [JS Bin](http://jsbin.com)

**Comment by cvrebert** [comment]
Also, it needs to be a [reduced test case](https://css-tricks.com/reduced-test-cases/). That pastebin is much too complicated.

**Comment by mdo** [comment]
We'll need that reduced test case as @cvrebert mentioned, but at first glance this sounds like it might be a problem of nesting tabs (which we don't support). Closing until we hear more.
