### ISSUE TITLE
Fixed element with Carousel caused glitching effect in Chrome on Mac

### ISSUE THREAD

**Issue by ryanjamesross** [twbs/bootstrap#16242]
Whenever the a carousel is running and there is a fixed header the header tends to bounce around sporadically during scrolling motion when viewed in latest version of Chome on a Mac.  Have tested this on several machines with both Maverick and Yosemite and it happens on all, however have had problems replicating the issue on Browserstack and on PCs.

From some testing I believe the glitch may be related to the backface-visibility property on the carousel items, but I can not reliably correct the issue.  

Just to describe how the glitch appears, it looks similar to bugs I have seen on elements that have improper transitions set up.  The header will look as if it stutters off the edge of the window sometimes going off screen and sometimes creating a gap between the header and window.  Again this mostly occurs when the user is scrolling as the carousel is animating.

**Comment by cvrebert** [comment]
Please post a JS Bin that demonstrates the problem.

**Comment by ryanjamesross** [comment]
just copied it over to JS Bin and the issue doesn't appear. Should I still post?

**Comment by ryanjamesross** [comment]
http://jsbin.com/xahebojiki
Just in case you still need it.

**Comment by twbs-lmvtfy** [comment]
Hi @ryanjamesross!

You appear to have posted a live example (http://jsbin.com/xahebojiki/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 5, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 6, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
We really provide much help without a simplified example (JS Bin / jsFiddle / Plunker / live webpage / whatever) that reproduces the problem.

**Comment by ryanjamesross** [comment]
The site it is happening on that I pulled that from is moenio.com, if you are somehow able to see the issue you will notice that deleting the carousel element fixes everything

**Comment by cvrebert** [comment]
Even after forcing the carousel to cycle, I haven't noticed any glitch on http://moenio.com
Maybe @mdo will have better luck?

**Comment by ryanjamesross** [comment]
Well knowing its hard to replicate is making me feel a bit better since it
has been bothering me on the past few sites I've been working on.  I can
only replicate it on Macs using chrome, seems to occur on every model we
have in the office. Also tried on several browsers on iOS devices and
does't seem to happen.  Not sure if a screen capture would help but I can
work on that if it would.  (side not please don't judge the messiness of
the site, still a ways to go).



*Ryan Donahue*

Phone: 954.974.6640  |  Fax:  954.974.6621
jamesrossadvertising.com <http://www.jamesrossadvertising.com/>

James Ross Advertising & Interactive
1180 SW 36th Ave | Suite 101
Pompano Beach | Florida 33069

**Comment by ryanjamesross** [comment]
And sorry I did not have the carousel active, I had forgotten about it, but
the glitch happens for me even without it active.  The sliding of the
carousel usually just makes it more noticeable. And deleting the entire
carousel element removes the issue. I will continue debugging this and see
if I can give any further details.

*Ryan Donahue*

Phone: 954.974.6640  |  Fax:  954.974.6621
jamesrossadvertising.com <http://www.jamesrossadvertising.com/>

James Ross Advertising & Interactive
1180 SW 36th Ave | Suite 101
Pompano Beach | Florida 33069

**Comment by ryanjamesross** [comment]
Just wanted to give an update on this, someone over at sitepoint found a solution by adding.

.navbar-fixed-top {
-webkit-backface-visibility:hidden;
}

They also referenced this as to what was causing it. 
http://www.sitepoint.com/fix-chrome-animation-flash-bug/

**Comment by cvrebert** [comment]
@ryanjamesross And that fixes this issue for you?

**Comment by ryanjamesross** [comment]
Yes this solves the issue completely.  The guy who was helping me out reported he could also see the glitch on a PC so it is not just limited to Macs, but it does seem to be limited to just Chrome.

**Comment by dongepulango** [comment]
I also have this issue, but the `-webkit-backface-visibility:hidden;` fixed t.

**Comment by mdo** [comment]
Not seeing any flickering here. Without a functional and reproducible test case, I'm punting on this. Please feel free to update with an example that shows the bug and proposed fix and we get address it.

**Comment by timtimosh** [comment]
https://jsfiddle.net/kf4nnnu8/
here is an example. just try to scroll and the navbar will change the position in 1 pixel to the top or to the bottom.. ubuntu 16.04, google chrome v. 53
 -webkit-backface-visibility:hidden; fixed the problem for me to.

**Comment by midzer** [comment]
Just fixed a site with same issue for Chromium 60 under Debian Stretch, too https://github.com/midzer/eisolzried/commit/dfdecec118b23909863f6b53e3a9993275f83e5a

**Comment by DawidMmM** [comment]
Got exactly the same problem and i use the newset version of bootstrap but -webkit-backface-visibility:hidden; fixed the problem
