### ISSUE TITLE
Nested nav-tabs and aria-expanded

### ISSUE THREAD

**Issue by jannestad** [twbs/bootstrap#16249]
If you nest one nav-tabs inside of another (inside tab-pane), it seems that aria-expanded="true" is set on all the li elements of the child nav-tabs when you switch tabs. This affects version 3.3.4.

    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#categories" data-toggle="tab">Hovedmeny</a>
      </li>
      <li>
        <a href="#alphabet" data-toggle="tab">A til Å</a>
      </li>
    </ul>

    <div id="megamenu" class="tab-content">
       <div class="tab-pane active fade in" id="categories">
         ....
       </div>

       <div class="tab-pane fade" id="alphabet">
        <ul class="nav nav-tabs">
          <li class="active">
            <a href="#a" data-toggle="tab">A</a>
          </li>
          <li>
            <a href="#b" data-toggle="tab">B</a>
          </li>
          <li>
            <a href="#c" data-toggle="tab">C</a>
          </li>
          
       </ul>
       
     </div>
   </div>

In the above, switching to the tab #alphabet will set aria-expanded="true" not only on on the a element that reference to #alphabet, but also on all the a elements for the tabs (#a, #b etc.) nested inside of the active tab-pane.

The proper behaviour would be for the status of the parent nav-tabs to not affect the child nav-tabs.

**Comment by zacechola** [comment]
I don't think nested tabs are supported in that way, but your HTML confirms this behavior nonetheless: http://jsbin.com/lolaji/1/

**Comment by cvrebert** [comment]
This is due to `Tab.prototype.activate` being used for toggling both the tab links and the tab panes without differentiating between them.

**Comment by mdo** [comment]
Nested tabs are indeed not supported.

**Comment by hjnilsson** [comment]
If nested tabs are not supported, it ought to be mentioned in the documentation for the tab component.

**Comment by fat** [comment]
Yep, could be clear about that… if we change our mind for whatever reason, fixing the aria thing is also super trivial
