### ISSUE TITLE
Bootstrap Horizontal Form Wrapper Issue.

### ISSUE THREAD

**Issue by Jo5h** [twbs/bootstrap#16250]
The form-group for the horizontal form is breaking the row class, when inside of a fieldset This causes some responsive issues with the layout. The first being on that on large screens there is no bottom-margin on the div. The second being that if a label spans over two lines it will readjust layout at certain widths to have the label for the next row at the right of the form-group prior. Adding the row class via row class to the div fixes both these issues.

First form-group also has the row class, while the rest are just relying on the form-group to have them treated as rows.

![screenshot from 2015-04-07 08 20 28](https://cloud.githubusercontent.com/assets/4196382/7023830/42ffc8c6-dd06-11e4-8ee7-61e161ba7574.png)

Example of more layout issues related to this.

![screenshot from 2015-04-07 08 26 41](https://cloud.githubusercontent.com/assets/4196382/7023852/7d2f39f0-dd06-11e4-81ed-d874dd2b5312.png)

**Comment by zacechola** [comment]
Please post a reduced test case. We provide a [JS Bin template](http://jsbin.com/lefey/1/edit?html,output) to get you started.

**Comment by Jo5h** [comment]
http://jsbin.com/dahologeno

**Comment by twbs-lmvtfy** [comment]
Hi @Jo5h!

You appear to have posted a live example (http://jsbin.com/dahologeno/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 49, column 9: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 21, column 84: Unclosed element ```` form ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Jo5h** [comment]
http://jsbin.com/dahologeno

**Comment by twbs-lmvtfy** [comment]
Hi @Jo5h!

You appear to have posted a live example (http://jsbin.com/dahologeno/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 24, column 9: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Jo5h** [comment]
http://jsbin.com/dahologeno

**Comment by zacechola** [comment]
You have a typo in your `.form-horizontal` class name. See your code with the correction: http://jsbin.com/yolino/1/edit?html,output

:smile_cat:

**Comment by Jo5h** [comment]
Oh the shame :(
