### ISSUE TITLE
Hide the Copy buttons in docs when Flash is not available

### ISSUE THREAD

**Issue by tarebyte** [twbs/bootstrap#16269]
Hi There,

I'm opening up an issue before making a pull request to see if this was something that people might want.
I would like to hide the the copy button for the code snippets when the browser doesn't support flash.

Here is a before and after:
![screen shot 2015-04-09 at 20 17 25](https://cloud.githubusercontent.com/assets/564113/7079698/80621bba-def5-11e4-89db-141042d3e0b2.png)

![screen shot 2015-04-09 at 20 16 16](https://cloud.githubusercontent.com/assets/564113/7079684/587cf746-def5-11e4-891a-0fc7cba73d9c.png)

I don't think it takes away from the design at all, and it would be really useful for people like me who use Firefox and don't have flash installed.

Thanks!

**Comment by cvrebert** [comment]
Sounds perfectly reasonable.

**Comment by patrickhlauke** [comment]
LGTM. maybe a nice addition would be to explore the possibility of using the clipboard API http://www.w3.org/TR/clipboard-apis/ where supported, and ditch the flash thing altogether?

**Comment by tarebyte** [comment]
@patrickhlauke, @JamesMGreene had some thoughts on it in zeroclipboard/zeroclipboard#171.

From what I've read it doesn't sound like it's super feasible right now for a lot of browsers (http://caniuse.com/#feat=clipboard).

**Comment by JamesMGreene** [comment]
Sadly correct: the HTML Clipboard API is still basically unimplemented in all browsers, minus a few that support only its "paste" event.

Believe me... when it's available in ANY browser, ZeroClipboard will be utilizing it as the first-class approach ASAP and demoting our Flash bits to second-class (fallback).

**Comment by cvrebert** [comment]
@tarebyte Anyway, we'd welcome a pull request.

**Comment by JamesMGreene** [comment]
You guys may be interested in my comment on https://github.com/zeroclipboard/zeroclipboard/issues/552. Feedback is always welcomed.

**Comment by tarebyte** [comment]
@cvrebert this may seem like a silly question, but how are you minifying your JS for the docs?

**Comment by cvrebert** [comment]
@tarebyte Via an UglifyJS Grunt task: https://github.com/twbs/bootstrap/blob/4127b250db461e47639983e2ad177963316386e1/Gruntfile.js#L145

**Comment by tarebyte** [comment]
@cvrebert awesome thanks! I was look at the `gh-pages` branch and skipped right through the README. I'll get started on the PR.
