### ISSUE TITLE
Reliable way to detect bootstrap.js version

### ISSUE THREAD

**Issue by gtaborga** [twbs/bootstrap#16264]
I was searching through the source code and saw that there is no reliable way to detect the version of Bootstrap that is loaded on the page. Other popular libraries provide this functionality in some way right out of the box.

Example:
jQuery.fn.jquery
ko.version

I have run across a use case where I need to be able to do the following:

We need to be able to render fragments of HTML into an existing page. To prevent bloating the page and loading the same assets twice without actually knowing anything about the consuming page, I want to from the child fragment HTML detect if these libraries are loaded on the parent page and detect their exact version number for compatibility reasons. Only if a version that isn't compatible is loaded would I then load the required asset. 

With jQuery and Knockout which are two of the libraries that may already be loaded on my parent page this is trivial but with Bootstrap it is not. The two most popular techniques for detecting the Bootstrap version are:

1. To attempt to detect whether its Bootstrap 2 by checking if the typeahead plugin exists. This is not reliable at all and can give a false positive if any jQuery plugin named typeahead is loaded.
var bsVersion = ( typeof $.fn.typeahead !== 'undefined' ? '2.3.2' : '3.0.x' );

2. To explicitly load the CSS file as text and parse the comment at the top for the version number. This assumes that we want to detect the version from a known asset. This does not provide the means for detecting the version that may be loaded on the page already (which may be different from the one that you have access to).
$.get("dist/css/bootstrap.min.css", function (data) {
  var version = data.match(/v[.\d]+[.\d]/);
  alert(version);
});

I propose that Bootstrap adds something like:

jQuery.fn.bootstrap 

which much like jQuery.fn.jquery returns the version number of the library that is loaded. 

I'm not sure what the reason behind putting the version on every plugin explicitly such as Alert.VERSION = '3.3.4' is but it doesn't seem to provide the information without actually creating an instance of that plugin. EDIT: Didn't realize you didn't have to create an instance but in my comment below I expressed that it will only tell you that SOME plugin is loaded named Alert with a VERSION number, not that Bootstrap loaded it.

I apologize if this has been brought up before as I couldn't find an existing issue. If there are other alternatives that already exist to solve this problem please let me know.

**Comment by cvrebert** [comment]
> I'm not sure what the reason behind putting the version on every plugin explicitly such as Alert.VERSION = '3.3.4' is but it doesn't seem to provide the information without actually creating an instance of that plugin.

You don't need to create any instances. See http://getbootstrap.com/javascript/#js-version-nums

**Comment by gtaborga** [comment]
This still doesn't solve the problem as I pointed out in my post. I would appreciate a little more discussion before closing the issue. Depending on a jquery plugin by name doesn't tell me bootstrap is loaded it tells me SOME plugin by the name of Alert exists. This could be from any library.

**Comment by gtaborga** [comment]
Below is a dirty solution I just came up with which will look for a script tag that references bootstrap.js, attempts to retrieve it from the same location just to parse the comment. It does not feel robust to me but may provide a temporary workaround. I have a feeling this would be very brittle.

var getBootstrapVersion = function () {
  var deferred = $.Deferred();

  var scripts = document.getElementsByTagName('script'),
      foundBootstrap = false;

  for (var i = 0; i < scripts.length; i++) {
    var src = scripts[i].getAttribute('src');
    if (src.indexOf('bootstrap') > 0) {
      foundBootstrap = true;

      $.get(src).done(function(response) {
        var matches = response.match(/(?!v)([.\d]+[.\d])/);
        if (matches && matches.length > 0) {
          version = matches[0];
          deferred.resolve(version);
        }
      });

      break;
    }
  }

  if (!foundBootstrap) {
    return deferred.resolve(undefined);
  }
};

getBootstrapVersion().done(function(version) {
  alert(version);
});

**Comment by cvrebert** [comment]
X-Ref: #12394

**Comment by gtaborga** [comment]
Thank you for continuing this and not leaving it closed. I really appreciate it.

**Comment by cvrebert** [comment]
One complication here is that Bootstrap's JavaScript isn't monolithic. Users are free to load [the individual plugin files](https://github.com/twbs/bootstrap/tree/master/js) rather than `bootstrap[.min].js`, and they can potentially load different versions of different plugins (although that's not particularly encouraged).

**Comment by gtaborga** [comment]
I can see how that can complicate things. I hadn't considered that use case. It would certainly break the proposed $.fn.bootstrap as it is. Perhaps simply adding a property to each of the plugins like:

$.fn.Alert.constructor.BOOTSTRAP would provide me a way to detect from all plugins loaded that Alert is both a specific VERSION and that it comes from BOOTSTRAP and not some arbitrary other library with a VERSION property?

**Comment by gtaborga** [comment]
Is loading individual plugin files a particularly popular option that people have used? In my experience teams have opted to consume the whole library and usually the same version. This certainly makes any simple solution very challenging to implement.

**Comment by gtaborga** [comment]
What if the $.fn.bootstrap version number is only added when the `bootstrap[.min].js` file is loaded in its entirety. If users choose to load them individually they need to rely on the plugin version. This would allow consumers of the full JS file to have a more robust option.

**Comment by cvrebert** [comment]
> Is loading individual plugin files a particularly popular option that people have used?

Kinda hard to say, but it's been a fully supported option since pretty much forever, and it makes it very easy to strip off unnecessary parts of Bootstrap when someone doesn't need the whole thing. I find it very unlikely that we'd stop supporting it in the foreseeable future.

**Comment by zacechola** [comment]
>Is loading individual plugin files a particularly popular option that people have used?

fwiw, I custom build Bootstrap at work. Some parts are used, some are not. Depends on the specific needs of the projects. I do, however, stay on the same version.

Futhermore, [making Bootstrap even *more* modular is sometimes brought up](https://twitter.com/stubbornella/status/582602716410552320).

**Comment by gtaborga** [comment]
> EDITED for clarity. What if the proposed $.fn.bootstrap version number is appended only to the fully built bootstrap[.min].js file? If users choose to use the individual plugin files they will have the $.Alert.constructor.VERSION to depend on. This will continue to provide the flexibility of modularity but provide a more robust solution for detecting the version of the full library that may be loaded on the page. Is this an option?

No reply to this question yet so just trying to keep this thread active.

**Comment by gtaborga** [comment]
It looks like there is not as much of an interest in this feature by others. The above workaround would suffice for our use case if we decide to use it. I'm going to close the issue. If anyone feels compelled to raise this again I'd be interested in seeing what the result is.

**Comment by amin007** [comment]
how i can display version of bootstrap in html5?

**Comment by cvrebert** [comment]
https://getbootstrap.com/docs/4.3/getting-started/javascript/#version-numbers
