### ISSUE TITLE
modal, tooltip, popovers - oh my

### ISSUE THREAD

**Issue by lsintampa** [twbs/bootstrap#16267]
Been running V 3.1.0 for over a year - 

Recently upgraded to 3.3.4 and all popovers, tooltips, modal dialogs have stopped working.

Running Jquery 1.10.2

Simply reverting back to 3.1.0 solves all issues.

code like this:  

$(function () { 
	$('.post-exception').popover({ trigger: "hover" });
});	

throws an error (undefined) if the class "post-exception" does not exist on the page

Other issues similar to:

<button type="button" class="btn" data-toggle="modal" data-target="#searchSchDiv" ....

will not open the dialog at all - no error thrown, just doesn't open

same code works with 3.1.0

NOTE: the popover script above and the button code are obtained via $ajax calls to the server, where the content returned is placed on the calling page... 

Example the loaded page is say "mypage.html"

It holds a div area with id="mycontent"

It also holds the modal div id="searchSchDiv"

We call $ajax to get content - part of that content is the modal button - the content is then placed in the mycontent div

The whole application uses ajax calls - basically content is loaded as needed and most content contains jquery code and it's always worked until 3.3,4  (again popover, modal, and tooltips)

OH, one more thing, dropdowns stopped also and the only way to get them to work was to include the dropdown.js as well as bootstrap.js

Maybe a clue there?  In other words dropdowns didn't work either with 3.3.4 unless I also included dropdown.js

**Comment by cvrebert** [comment]
We cannot help you without a simplified Plunker or JS Bin that demonstrates the problem(s).

**Comment by lsintampa** [comment]
OK - my bad - had a corrupt bootstrap file...
