### ISSUE TITLE
`.btn-toolbar .btn-group {float: left}` prevents btn left of btn-group

### ISSUE THREAD

**Issue by bolinfest** [twbs/bootstrap#16276]
Consider the following markup:

```
<div class="btn-toolbar">
 <button class="btn">Left button</button>
 <div class="btn-group">
   <button class="btn">LB</button>
   <button class="btn">RB</button>
 </div>
 <button class="btn">Right button</button>
</div>
```

One would expect "Left button" to appear left of the button group, but the reverse is true because of the `.btn-toolbar .btn-group {float: left}` in `button-groups.less`. See http://www.bootply.com/slYNLprbgV to reproduce.

**Comment by twbs-lmvtfy** [comment]
Hi @bolinfest!

You appear to have posted a live example (http://s.bootply.com/render/LIia2vI4OL), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 40, column 2: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 42, column 4: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 43, column 4: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 45, column 2: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 51, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bolinfest** [comment]
Changed issue description to reference http://www.bootply.com/slYNLprbgV to try to fix lint errors.

**Comment by twbs-lmvtfy** [comment]
Hi @bolinfest!

You appear to have posted a live example (http://s.bootply.com/render/slYNLprbgV), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 51, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bolinfest** [comment]
Version 3.3.4 does not appear to be an option. 3.3.2 appears to be the latest version that I can test in bootply.com.

**Comment by cvrebert** [comment]
@bolinfest Then please use JS Bin instead.

**Comment by bolinfest** [comment]
OK, but this a pretty trivial example and is due to a style that looks to
be untouched since 2012, so I don't expect it will make a difference.

**Comment by cvrebert** [comment]
Confirmed, and with suggested fix: http://jsbin.com/vayuvu/4/edit
