### ISSUE TITLE
navbar.less references deprecated @screen-xs-min

### ISSUE THREAD

**Issue by dfoverdx** [twbs/bootstrap#16278]
As of version 3.3.4, navbar.less:95 references `@screen-xs-min` which was deprecated in version 3.2.0.

    .navbar-fixed-top,
    .navbar-fixed-bottom {
      .navbar-collapse {
        max-height: @navbar-collapse-max-height;

        @media (max-device-width: @screen-xs-min) and (orientation: landscape) {
          max-height: 200px;
        }
      }
    }

**Comment by cvrebert** [comment]
Thanks for the concern, but there's no action to be taken here for Bootstrap v3.
There's no non-deprecated replacement for `@screen-xs-min`, the snippet of code you're referencing is a flawed hack anyway, and we're no longer making any significant changes to the navbar in Bootstrap v3, in favor of focusing our efforts on overhauling the navbar component in Bootstrap v4 to properly fix several significant issues with the navbar, including the one that this snippet of code was attempting to fix.
