### ISSUE TITLE
Separate btn-border-radius variables

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap#16271]
I found myself in a position recently where I needed to alter the `border-radius` of buttons for them to be more “pill”-like, but when I inspected the [buttons.less](https://github.com/twbs/bootstrap/blob/master/less/buttons.less#L20), it appears as though buttons’ border-radius values are based on the `@border-radius-` variables.

It would be good if there were separate variables for specifying the border-radius of buttons. They could inherit from the `@border-radius` variables by default, but there’s a level of abstraction if folks like me do need to deviate away from the global `@border-radius` values. Something like this:

```less
@btn-border-radius-base: @border-radius-base;
@btn-border-radius-large: @border-radius-large;
@btn-border-radius-small: @border-radius-small;
```

I’m happy to create a Pull Request for this feature if it’s deemed something that’s worthy of inclusion.

**Comment by mdo** [comment]
I honestly hate all the variable abstractions, but I get it. If you go a PR, we'll accept it though.
