### ISSUE TITLE
filename isn't vertically centered in Chrome's file input

### ISSUE THREAD

**Issue by jvanasco** [twbs/bootstrap#16272]
The text on file inputs is not centered on Chrome. 

This looks to be an issue with Chrome, as it is centered on Safari and FireFox.  The baseline for the text is shifted up a few pixels.

I don't know if this is fixable cross-browser in a good way.

setting line-height to 0 seems to help a bit

     input[type="file"] {
       display: block;
    +  line-height: 0;
     }

Chrome default

![fileinput-default](https://cloud.githubusercontent.com/assets/204779/7094568/7600dcd8-df90-11e4-81e1-9d569e4c1229.png)

Recentered

![fileinput-better](https://cloud.githubusercontent.com/assets/204779/7094570/78bfd384-df90-11e4-9999-9d6932a233ed.png)

**Comment by arxene** [comment]
How do you reproduce this issue? I used the file input example from http://getbootstrap.com/css/#forms-example and used the master branch. The text to the right of the file input looks centered to me. Why is the file input button rounded in the screenshots?

**Comment by jvanasco** [comment]
Sorry, I should have been more clear:

The above screenshots are of http://getbootstrap.com/css/#forms using the latest Chrome on Mac OSX

**Comment by cvrebert** [comment]
We supposedly set `display: block` in order to "Set the height of file controls to match text inputs", but FWICT the heights don't seem to match.
Random observation: Setting `display: flex` fixes the alignment in Chrome (ditto with `-webkit-flex` in Safari), although the height still doesn't match.
CC: @mdo

**Comment by mdo** [comment]
There's no good way to center this across all browsers—the file input is super inconsistent. Punting as a won't fix.
