### ISSUE TITLE
v2.3.2 docs should link to corresponding page of v3 docs instead of to v3 docs homepage

### ISSUE THREAD

**Issue by Padmahas** [twbs/bootstrap#16277]
In this link "http://getbootstrap.com/2.3.2/javascript.html", in the modal section, under live demo subsection, this code can be found.

a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
 

div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

Where the code for modal calls the "hide" class which hides the O/P of the later part of the code. This took me about an hour to find where the problem is. 

Please modify the code by removing "hide" class.

And I found the code in this link more helpful (border for the modal and other css are applied) "http://getbootstrap.com/javascript/#live-demo",  and which I think it was written by same author, but I don't know why the code was not updated here.

Thank you.

**Comment by taspeotis** [comment]
> Using bootstrap 3, code for modal has to be changed ... In this link "http://getbootstrap.com/2.3.2/javascript.html"

Is the problem simply that you are looking at the Bootstrap 2 documentation?

**Comment by Padmahas** [comment]
Don't know exactly, Since the meaning and the function of hide class should do same job, I thought of notifying. Even though they have given warning in the starting of the page, the link they have provided will not redirect to another documentation of the most recent bootstrap. Instead it wil simply redirect to bootstrap  homepage (Where no seperate link to documentation section is not found) and people who doesn't know to which section of documentation does "modal" belongs to cannot figure out that they have to search inside "javascript" link.

It would be wise if the old documentation page provide link to new (new bootstrap) documentation page.

**Comment by cvrebert** [comment]
As mentioned in the "Additional notes" section of [the v2 to v3 migration guide](http://getbootstrap.com/migration/), the `.hide` class shouldn't be used on modals in v3.
Bootstrap v3 is not backward-compatible with Bootstrap v2, so v2's docs shouldn't be consulted when using v3.
