### ISSUE TITLE
Badges not vertically aligned in headers

### ISSUE THREAD

**Issue by bbodenmiller** [twbs/bootstrap#16270]
[Badges](http://getbootstrap.com/components/#badges) appear to have issues in headers. I think badges should be vertically aligned in headers.

Fiddle: https://jsfiddle.net/nwpmmhx1/3/

Current alignment:
![image](https://cloud.githubusercontent.com/assets/1192780/7084309/c848f9fa-df20-11e4-9c24-6f20d6fa12d7.png)

Better alignment:
![image](https://cloud.githubusercontent.com/assets/1192780/7084312/d229da98-df20-11e4-93c1-b2361eb2f291.png)

**Comment by twbs-lmvtfy** [comment]
Hi @bbodenmiller!

You appear to have posted a live example (https://fiddle.jshell.net/nwpmmhx1/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bbodenmiller** [comment]
Updated fiddle: https://jsfiddle.net/nwpmmhx1/4/

No change.
