### ISSUE TITLE
Help with bootstrap bug on my page

### ISSUE THREAD

**Issue by Kucharskov** [twbs/bootstrap#16274]
Hi!
I use bootstrap in my script here: http://folderlist.kucharskov.pl/beta/
That's simple "filemanager" but when file have too long name like first the table looks terrible.
I try many changes but nothing works. The white-space and other CSS tricks too.
Could you help me fix that?
Regards!
Your user ;)

**Comment by fchiumeo** [comment]
try with real word :)

**Comment by Kucharskov** [comment]
Thanks. Very usefull... I renamed that file to looks like file downloaded from internet. Check again. I wanna protect my script from that.

Any trick with white-space, text-overflow or normal overflow?? Maybe bootstrap class?
