### ISSUE TITLE
Grid gutter issue with uneven pixel values

### ISSUE THREAD

**Issue by 7R5N** [twbs/bootstrap#16281]
I have a layout with a 1px grid gutter; the columns are colored boxes. 

Bootstrap’s grid translates this in -0.5px margins along with 0.5px paddings. That seems to work, actually (and I have tested it in some browsers), because the bowsers seem to generally decide if they tilt the columns to the left or to the right, to finally feature one full pixel gap. 

But this feels overall accidentally, and I’m worried that that this might break on day, at least when it comes to sub pixel rendering … 

So I’m asking myself if it wouldn’t be a good idea to enhance the grid mixin with a logic for uneven values, that produces regardeless just full pixel values; in my case 1px left, 0px right, for example. 

Alternatively maybe optional variables for left-/right-gutter-part would be fine. 

Thanks a lot, 
7R5N

**Comment by mdo** [comment]
We should round up to the nearest pixel values, though come v4 it'd be nice to not dividing values for their true purposes. The latter there will be a fix I can make for our v4, but the former could be done in v3 if someone wanted to take a stab at it.
