### ISSUE TITLE
bootstrap rtl 3.3.4 doesn't work

### ISSUE THREAD

**Issue by essivision** [twbs/bootstrap#16283]
When I import bootstrap rtl 3.2.0 my style direction changed and any thing work in RTL ,but when I import bootstrap rtl 3.3.4 my style direction doesn't changed and show me LTR mode. what should I do?

**Comment by patrickhlauke** [comment]
Please direct your question at the Bootstrap RTL project https://github.com/morteza/bootstrap-rtl as core Bootstrap does not officially support RTL
