### ISSUE TITLE
.form-control-feedback misplaced by 25 px

### ISSUE THREAD

**Issue by spruce** [twbs/bootstrap#16285]
Hello,
I use in one of my projects bootstrap version (`"bootstrap": "~3.2.0"`) and wanted to upgrade to the new version (`"bootstrap": "~3.3.4"`). But the form-control-feedback icons are replaced by 25 px. In the versions before was a css selector which removed that (`form-horizontal .has-feedback .form-control-feedback {
  top: 0;
  right: 15px;
}`)

Am I doing anything wrong?

Included is an example how I use it.

```
<form id="ember756" class="ember-view form-horizontal" role="form">
  <div id="ember778" class="ember-view form-group has-feedback has-error">
    <label id="ember826" class="ember-view control-label col-sm-2">Full Name</label>
    <div class="col-sm-10">
      <input id="ember971" class="ember-view ember-text-field form-control" placeholder="Enter a name..."></div>
      <span class="form-control-feedback"><i class="fa fa-times"></i></span>
      <span id="ember960" class="ember-view help-block col-sm-offset-2 col-sm-10">is too short (minimum is 5 characters)</span>
    </div>
  </div>
</form>
```

**Comment by cvrebert** [comment]
Please post a JS Fiddle or JS Bin of your example.

**Comment by spruce** [comment]
Hey,
I forgot to do that here it is:
http://jsbin.com/layumotipu/2/edit?html,output
Strangly there is no icon showing (I forgot to include sth. but thats not the matter) so I added a simple x which is misplaced like the original glyphicon.

**Comment by twbs-lmvtfy** [comment]
Hi @spruce!

You appear to have posted a live example (http://jsbin.com/layumotipu/2/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 21, column 11 thru line 21, column 16: End tag ```` div ```` seen, but there were open elements.
* line 13, column 9 thru line 13, column 75: Unclosed element ```` form ````.
* line 22, column 9 thru line 22, column 15: Stray end tag ```` form ````.
* line 24, column 1 thru line 24, column 6: Stray end tag ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by spruce** [comment]
Nice bot :+1: 
New version: http://jsbin.com/layumotipu/3/edit

**Comment by twbs-lmvtfy** [comment]
Hi @spruce!

You appear to have posted a live example (http://jsbin.com/layumotipu/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 15, column 13: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 19, column 25: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 6, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 7, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by spruce** [comment]
Next iteration:
http://jsbin.com/layumotipu/4/edit

**Comment by twbs-lmvtfy** [comment]
Hi @spruce!

You appear to have posted a live example (http://jsbin.com/layumotipu/4/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by spruce** [comment]
Hopefully now it works:
http://jsbin.com/layumotipu/5/edit

**Comment by cvrebert** [comment]
Bootstrap doesn't integrate with Font Awesome; we include Glyphicons instead. See http://getbootstrap.com/components/
Please change your example to use Glyphicons instead of Font Awesome.

**Comment by spruce** [comment]
Now it magically works...
updated version: http://jsbin.com/wujujo/2/edit

**Comment by cvrebert** [comment]
Closing this then, since we can't help with third-party stuff such as Font Awesome.
