### ISSUE TITLE
How to get 'collapse' targeted div outside the scrolbar?

### ISSUE THREAD

**Issue by himmatdb** [twbs/bootstrap#16296]
I'm using 'bootstrap datatable'. In table there is edit button, on click edit button showing 'colapse' div which is displaying inside scrollbar. I want to show colapse div outside the table scrollbar. How to do this?
![collapse-actual](https://cloud.githubusercontent.com/assets/5779901/7158832/5a9e76bc-e39b-11e4-9905-b917cfeca280.jpg)
![collapse-issue](https://cloud.githubusercontent.com/assets/5779901/7158838/656cbe0a-e39b-11e4-84a9-80a96f060469.jpg)

**Comment by cvrebert** [comment]
This is a documented limitation of responsive tables; see http://getbootstrap.com/css/#callout-tables-responsive-overflow
Please direct how-to questions to StackOverflow. Thanks!
