### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Anenth** [twbs/bootstrap#16294]
I want to use [Sourcegraph](https://sourcegraph.com) for bootstrap code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/twbs/bootstrap. (It should only take 30 seconds.)

Thank you!

**Comment by cvrebert** [comment]
> **CSS is not supported**. Sourcegraph's advanced code search, browsing, and usage examples are only available for supported languages. If the language was detected incorrectly, or to use only basic repository operations, you can proceed anyway.

And it looks like they don't support HTML either, so it'd really only be for our JavaScript.

**Comment by Anenth** [comment]
True. Hoping they will have support css and html soon

**Comment by mdo** [comment]
We won't be doing this I think. I've seen this a few times and it feels like nothing more than a GitHub clone that copies over repos from here to there. Previously I've seen all our code on there, so I'm curious what "enabling" it would even do. Maybe that's changed?

Either way, punting for now. Maybe if they support our required languages I can take a second look.

**Comment by Anenth** [comment]
Cool

Anenth Vishnu
Front End Engineer
Bang The Table
