### ISSUE TITLE
Recent update to .hidden utility class causes regression when mixed with .visible-* classes

### ISSUE THREAD

**Issue by julianlam** [twbs/bootstrap#16292]
Re: this commit: https://github.com/twbs/bootstrap/commit/7dd72d83fab7394dee7326c0a6214374ec796ff6 and [this twitter conversation](https://twitter.com/jitendravyas/status/562940090553733121)

It *does* seem vestigial, although in *our* use case, we use the `hidden` class in conjunction with `visible-lg` and `visible-md`. `hidden` is used to hide the element (of course), while the latter 2 classes are used to ensure that *if shown* (that is, `hidden` class is removed), it is shown for `>=tablet` devices only

Removing `visibility: hidden` from `.hidden` means that the `display: block !important;` in the `visible-*` classes override the `display: none !important;` in `hidden` completely, which is a regression from expected behaviour, as although the actual placement of the element in the DOM has not changed, it used to be invisible, but now it is not.

I am not adverse to changing the way we handle showing/hiding of the element in question, so if i am "doing it wrong", please let me know.

Relevant usage code:

    <ul class="nav navbar-nav navbar-right pagination-block hidden visible-lg visible-md"> ... </ul>

**Comment by cvrebert** [comment]
Two options to consider:
```html
<div class="hidden">
  <ul class="nav navbar-nav navbar-right pagination-block visible-lg visible-md">
</div>
```

```js
$('#your-navbar').hide(); // or the moral equivalent in your JS library of choice
```

Note that `.hidden` will be gone in Bootstrap v4, due to its conflict with `jQuery.hide()/show()`.

**Comment by julianlam** [comment]
Thanks for the update @cvrebert. We'll look into alternative ways of toggling visibility for this item. A whole bunch of our code uses `.toggleClass('hidden', someBool);`, so in anticipation of this deprecation, we may have to reconsider some of our practices. Consider us warned in advance. :smile:

**Comment by cvrebert** [comment]
@mdo Should we close this?
