### ISSUE TITLE
Horizontal scrollbar appears on adding carousel code

### ISSUE THREAD

**Issue by ChapDaddy65** [twbs/bootstrap#16290]
After reviewing this problem in browserstack, I created a CodePen and found that the code containing the carousel is adding either some spacing or padding somewhere that is creating a horizontal scrollbar when using the carousel inside a `.container` & `.row`. I have been unsuccessful in my attempts to locate where the math is not adding up correctly to 100% of the screen's width.

here's my CodePen that isolates the Carousel :: [http://codepen.io/ChapDaddy65/pen/WbVOaM](http://codepen.io/ChapDaddy65/pen/WbVOaM)

**Comment by twbs-lmvtfy** [comment]
Hi @ChapDaddy65!

You appear to have posted a live example (http://codepen.io/ChapDaddy65/pen/WbVOaM.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 10, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 11, column 5: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
See ^^^. Try Bootlinting your code in the future.
