### ISSUE TITLE
ScrollSpy provide destroy method?

### ISSUE THREAD

**Issue by icai** [twbs/bootstrap#16293]
I think ScrollSpy  should provide `destroy` method to clear the event `scroll.bs.scrollspy` and element data.

**Comment by cvrebert** [comment]
X-Ref: #15607

**Comment by fat** [comment]
totally agree.

I think in v4 we should standardize a teardown method for all plugins :+1:

**Comment by fat** [comment]
But not for v3

**Comment by rulatir** [comment]
@fat, it is almost 2018 and v4 stable is not out yet. In retrospect it would seem that your careless "but not for v3" denied the feature to users for 3 years.

**Comment by rulatir** [comment]
... and it would seem that the feature is not in v4 alpha either:
https://v4-alpha.getbootstrap.com/components/scrollspy/#methods
