### ISSUE TITLE
Escape button behaving funny when Nested multiple modals are used

### ISSUE THREAD

**Issue by zuxfer** [twbs/bootstrap#16303]
http://www.bootply.com/86973

Open multiple modals and try to click escape.

Expected feature is to have the top most modal discarded on every press.

**Comment by twbs-lmvtfy** [comment]
Hi @zuxfer!

You appear to have posted a live example (http://s.bootply.com/render/86973), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0
* line 91, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Per our documentation, stacked modals are explicitly not supported by Bootstrap.
