### ISSUE TITLE
Can't see tooltip as mentioned on doc

### ISSUE THREAD

**Issue by ezequias** [twbs/bootstrap#16300]
Hi everyone 

I am having trouble to see tooltip working properly and I decided to put it on jsfiddler

Please see at: https://jsfiddle.net/erprvn54/1/

Sincerely
Ezequias

**Comment by twbs-lmvtfy** [comment]
Hi @ezequias!

You appear to have posted a live example (https://fiddle.jshell.net/erprvn54/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 40, column 3 thru line 40, column 130: Attribute ```` rel ```` not allowed on element ```` button ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ezequias** [comment]
I updated to the same as Bootstrap recommend. What's wrong?

See the link again: https://jsfiddle.net/erprvn54/2/

**Comment by twbs-lmvtfy** [comment]
Hi @ezequias!

You appear to have posted a live example (https://fiddle.jshell.net/erprvn54/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Also `[rel="tooltip"]` doesn't match any of the elements in your example.

**Comment by ezequias** [comment]
@cvrebert please check the second link i provided. The problem persists.

**Comment by cvrebert** [comment]
@ezequias Please see https://github.com/twbs/bootstrap/issues/16300#issuecomment-93602908

**Comment by ezequias** [comment]
Dear @cvrebert I changed the code now using the same example Bootstrap website suggest and I still don't have the result as espected, please see: https://jsfiddle.net/erprvn54/2/

Sincerely
Ezequias

**Comment by twbs-lmvtfy** [comment]
Hi @ezequias!

You appear to have posted a live example (https://fiddle.jshell.net/erprvn54/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Dear @ezequias As the bots have told you twice now, **your example is missing jQuery**, which is required for Bootstrap's tooltips.
Also, this bug tracker is not meant to be used for personal support questions like this. Kindly respect our policy (https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker) and use StackOverflow instead for such questions. Thanks.
