### ISSUE TITLE
will bootstrap unsupport ie8or9 when next big version update?

### ISSUE THREAD

**Issue by hiwjcn** [twbs/bootstrap#16310]
will bootstrap unsupport ie8or9 when next big version update?

**Comment by licensecart** [comment]
nope :) 4 is dropping ie8 not sure about 9.

**Comment by mdo** [comment]
Plan is to drop IE8. IE9 will still be supported.

**Comment by acshef** [comment]
@mdo, after V4 ships, will there be any documentation outlining why support for those browsers is being dropped? (More than just *"for the sake of modernization"*, I'm hoping there'll be an explanation of the Bootstrap features that are no longer compatible). Perhaps something on the blog?

**Comment by mdo** [comment]
We'll talk a bit about that, but it won't be anything big or new to folks. IE8 requires polyfills, some hacks, and holds us back from using some more modern and flexible CSS. Unsure about the JS.

v3 will continue to be supported for bugs though for awhile after v4 is out.

**Comment by cvrebert** [comment]
Also, Microsoft itself will stop supporting IE8 in about 7 more months; see https://support.microsoft.com/en-us/gp/microsoft-internet-explorer
