### ISSUE TITLE
responsive menu issue with https only

### ISSUE THREAD

**Issue by msptrooper31** [twbs/bootstrap#16315]
I recently created a responsive css menu using bootstrap and it works like it should when the page is http: but when the site goes to a https: the sub menu gets messed up. See attached. Any ideas how to fix this?
![screen shot 2015-04-18 at 10 18 59 pm](https://cloud.githubusercontent.com/assets/12014592/7218156/de7bb154-e619-11e4-8e11-658953fb79e1.png)
![screen shot 2015-04-18 at 10 19 09 pm](https://cloud.githubusercontent.com/assets/12014592/7218157/e7551b26-e619-11e4-95a7-643c89d281f0.png)

**Comment by patrickhlauke** [comment]
Please direct your implementation-specific support requests to StackOverflow - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
