### ISSUE TITLE
Double-сlicking on the container selects all texts

### ISSUE THREAD

**Issue by studio-marweb** [twbs/bootstrap#16326]
Please, see video: http://screencast.com/t/xaiXeHyl6

**Comment by patrickhlauke** [comment]
Cannot reproduce on Win8.1 with Chrome, Firefox, IE11. What OS/browser are you experiencing this?

**Comment by studio-marweb** [comment]
I used Win7/Firefox. Btw, in chrome this problem does not appear.

**Comment by patrickhlauke** [comment]
Tested with Win7/Firefox, and it seems this is Firefox's own strange text selection behavior - double (and sometimes triple) clicking on a container selects, depending on the underlying structure, all content. It also behaves this way on several other non-Bootstrap sites I tested, so closing as not a Bootstrap issue
