### ISSUE TITLE
When working with Jquery Ajax with async to false, Modal only shows when the request complete

### ISSUE THREAD

**Issue by deepakdhanwani** [twbs/bootstrap#16321]
I am using bootstrap 3.3.2 version. I have a form where I have frequent jquery ajax calls and I am trying to show or hide the bootstrap modal dialog box for "Loading" purpose. These all ajax call are set to async false because I need some order in the execution. What I noted is the the bootstrap modal only show when the server completed its request while I have set the modal to show in beforeSend part of Jquery. 

I doubt the bootstrap show is an async request because when I am working with other thing like showing a loading image, then its working fine. I am attaching my code here as well. Please advise me some solution for this.

$("#loadingPleaseWaitDialogForRules").modal('show');
    var options = {
      	
	  target: '#output',
	  type: 'POST',
	  url: ruleEngineRequestUrl,
	  dataType: 'text',
	  async: false,
	  success: function(resp) {
	    if (action == 'Hide') {
	      returnValue = stringToBoolean(resp);
	    } else {
	      returnValue = resp;
	    }
	  },
	  beforeSend : function() {
		  
		  //$("#imgAjaxLoaderRuleEngineGif").show();
		  
		  
		  
	  },
	  complete : function() {
		  //$("#showAddRowRequestImage").hide();
		  setTimeout(function() {
		      $('#loadingPleaseWaitDialogForRules').modal('hide');
		    }, 500);
	  },
	  error: function(xhr, status, error) {
	    alert(error);
	  }
    };

    
    $("#formToSubmit").ajaxSubmit(options);

Thanks and Regards
Deepak Dhanwani

**Comment by cvrebert** [comment]
For help with using Bootstrap in individual scenarios, rather than bugs or feature requests for Bootstrap itself, please ask on StackOverflow (or similar) instead. Thanks!

**Comment by cvrebert** [comment]
Showing or hiding a Bootstrap modal is asynchronous in that a CSS animation is involved.
