### ISSUE TITLE
muliple navbar-right elements and their order

### ISSUE THREAD

**Issue by My1** [twbs/bootstrap#16327]
right now I am playing around with some navbar styles and I noticed that when I put navbar-right elements (signed-in text and sign out button) I noticed that the order is reversed (which seems legit for CSS float reasons), but when you turn to mobile view, you have then in the right order (which is in fact legit as well) but it isnt expected bahavior of a page when elements suddenly switch order.

**Comment by patrickhlauke** [comment]
I don't think the idea with `.navbar-right` is to have multiple containers with that class (at least in the docs, there's no such example, which admittedly leaves this as an implied assumption). The solution would be to have an overarching container like a `<div class="navbar-right">` and have individual elements, like the signed-in text and sign out button, as inline elements inside it...

**Comment by My1** [comment]
I already tried solutions with a span and a p a div was not tried up to now and I see 2 problems. it isnt right and the margins are broken.

This is my code as it is now. any wrappers around it break everything. I guess that the CSS might use the direct descendant operator > for navbar-text and navbar-btn being directly descending after navbar-nav or something similar that will immediately break the layout.
it uses a FontAwesome icon, but I checked that isnt the point of the discussion.
```HTML
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.php">admin</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="users.php">Users</a></li>
            <li><a href="#">Presentations</a></li>
            <li><a href="#">Config</a></li>
          </ul>
            <p class="navbar-text navbar-right">Eingeloggt als <a href="#" class="navbar-link"><strong>My1</strong></a></p>
            <p class="navbar-btn navbar-right"><button class="btn btn-primary"><i class="fa fa-arrow-circle-left"></i>&emsp;Back to Main</button></p>
        </div>
      </div>
    </nav>
```

**Comment by mdo** [comment]
Yeah, probably no good way to fix this in v3. An option is wrapping things to be floated in a parent element and manually ordering things within that.

**Comment by My1** [comment]
well I got it to work, remove the p around the button and make the text p a span, then a navbar-right span around and it works, even with an a.btn which I think is awesome, okay in mobile layout you get both on one line unless they dont fit, but better than you get them on different lines or similar even on desktop layout.

**Comment by mdo** [comment]
Yeah, the navbar is a little finicky like that. Hopefully things will be better in v4 :).

**Comment by My1** [comment]
but the good thing is that .btn a elements work this way (also you can make them work inside a p if you dont need them wrapped extra (nice little addition for the docs; i use them I can say that).
