### ISSUE TITLE
popover on option does not work

### ISSUE THREAD

**Issue by deanmalmgren** [twbs/bootstrap#16322]
The use case here is that I have a `<select>` element in a form with several `<option>` elements. These options are named as well as possible, but some additional information would be very helpful for end users. 

Although I have been advised that [it is not possible to accomplish this](http://stackoverflow.com/a/29769667/564709), I am having a hard time believing that. [This jsfiddle demonstrates the issue](http://jsfiddle.net/vxro95u9/). To reproduce,

1. click on the select element
2. hover over the options
3. observe that there is no popover

I am using Chrome 42 on OSX 10.10.2

**Comment by twbs-lmvtfy** [comment]
Hi @deanmalmgren!

You appear to have posted a live example (http://fiddle.jshell.net/vxro95u9/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 46, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 49, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 46, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by deanmalmgren** [comment]
Thanks @twbs-lmvtfy! You're swell. [Here's a simplified example](http://jsbin.com/wiwoxe/1/edit?html,js,output) that will better articulate the problem.

**Comment by patrickhlauke** [comment]
As already advised in that StackOverflow thread, no...this is not possible, in any browser, as they themselves take care of the interaction/rendering of the `<select>` when it's opened.

**Comment by deanmalmgren** [comment]
Drat. Thanks for confirming.
