### ISSUE TITLE
Modal backdrop does not disappear, when modal-dialog being removed in HTML

### ISSUE THREAD

**Issue by SilverFire** [twbs/bootstrap#16320]
**Use case:** I use modal for actions' confirmation. 
The modal block is placed inside of a [Pjax](https://github.com/defunkt/jquery-pjax) wrapper.
There OK button triggers a Pjax request, which (in case of success) replaces overall Pjax block with the new content.
When the modal block is being removed, the backdrop stays alive, because it is placed in the end of the body.

**Expected behavior:** the backdrop will be removed automatically, when the modal wrapper disappears.

**Steps to reproduce:**

* Open [Modal Live Demo](http://getbootstrap.com/javascript/#live-demo), click the *"Launch demo modal"* button

* Open the development console and remove corresponding modal wrapper. Just execute:

~~~js
$('#myModal').remove()
~~~

* Meditate on the stuck backdrop :wink: 

Guys, is it possible to fix this?

**Comment by cvrebert** [comment]
X-Ref: #15632

**Comment by cvrebert** [comment]
I think you should be able to simply and easily address the problem yourself by using a callback on one of the events that pjax provides. Your callback would do something like `$('.modal.in').modal('hide')` or `$('.modal-backdrop').remove()`

As mentioned in the issue that I referenced, the only way to do something about this at the Bootstrap level would be to use something like Mutation Observers, but there are some concerns with that approach.

**Comment by cvrebert** [comment]
Punting anything involving `MutationObserver` to consideration for Bootstrap v4.

**Comment by remartins** [comment]
$('.modal-backdrop').remove()
$(document.body).removeClass("modal-open");
