### ISSUE TITLE
Multiple panels problem on a single page

### ISSUE THREAD

**Issue by cloudservice-hong** [twbs/bootstrap#16329]
So I'm building a single page that has multiple panels, one after another as the user scrolls down. Inside the panels there are content such as list, dropdown menus and buttons.

The issue is, on my 5th panel down the page, the panel loses its margin on both left and right and stretches across the full width of the browser. This is the case as I keep adding more panels from 5th onwards but have absolutely no problem from panels 1 to 4.

I thought it might be an error with the content inside the panels but I've copied the exact code from the first panel and placed it as the 5th and the problem is there, so I don't believe it is related to my code.

If I just create multiple panels on the page with no content inside the panels, there is no issue. The issue seems to effect when there are multiple panels on one page with content inside the panels.

**Comment by cvrebert** [comment]
We cannot help unless you post a JS Bin that demonstrates the problem.
Also, on which browser(s) and OS(es) does the problem occur?

**Comment by mdo** [comment]
Closing until we hear more.
