### ISSUE TITLE
mobile menu in FireFox

### ISSUE THREAD

**Issue by neverdar** [twbs/bootstrap#16323]
There may be a better fix than this, but I was having issue with the collapse menu not rendering correctly in FireFox - the menu would open, but it overlapped the toggle and all of the text was hidden. 

After some fiddling, I found the best solution was to make a slight change in the css:

```
.collapse.in {
    display: inline-block !important;
}
```
I've been noticing that I've been needing to add `!important` to my own .css far more than I would like in order to override Bootstrap's default properties, but that's an issue for another day.

Everything has been working alright since, with no negative effects on my other browsers (so far)

Not sure if anyone else is having this issue, but if you are, this was a simple fix that took WAY too long to track down.

**Comment by mdo** [comment]
Double check your markup—the `.navbar-brand`, `.navbar-header`, and `.navbar-collapse` are all required. As is a `.container` or `.container-fluid`. There should be no problems with the navbar toggling as it's been largely unchanged for awhile now.
