### ISSUE TITLE
Add Meteor package config option to allow serving files from CDN

### ISSUE THREAD

**Issue by yauh** [twbs/bootstrap#16336]
I'd love to see an option to configure bootstrap so it would use a CDN instead of local files when building for production. That way the versions would stay the same, but advantages of CDN could be used.

**Comment by cvrebert** [comment]
I'm not clear on what you mean. Which local files are you referring to?

**Comment by yauh** [comment]
The package contents from the `dist` folder and `twbs:bootstrap.js` in the packages folder are the local files. These are currently copied to each client upon first URL request. I think this could be improved to allow to bypass including package files in the actual build result and using CDN links in the templates instead.
Basically it would be nice to add bootstrap via package but not add any actual files to the build output, but simply a reference to a (possibly configurable) CDN URL.

**Comment by cvrebert** [comment]
@yauh Are you referring to something Meteor-related by chance?

**Comment by yauh** [comment]
Oh my, yes of course. Sorry, I did not realize this was not the meteor package repo but the actual and official twbs repo...

**Comment by cvrebert** [comment]
CC: @splendido @dandv since they're in charge of our meteor packaging and thus might be able to actually understand your suggestion

**Comment by splendido** [comment]
At the moment, to my best knowledge, there's no way for a Meteor package to have different behaviours at development and production time.

The only solution I can see is to take off the `twbs:bootstrap` package and add links to the CDN just before deploying the eapp

**Comment by yauh** [comment]
I haven't tried it myself yet, but I thought perhaps using [compileStep](https://github.com/meteor/meteor/wiki/CompileStep-API-for-Build-Plugin-Source-Handlers) we could achieve something like that. Use a configuration option for a new `TwbsBootstrap` object the package exports and the build step checks whether it is configured for CDN or 'regular' use.

Anyway, I haven't given it much time, and it certainly isn't a pressing issue. In the long run, however, it would be nice to achieve CDN functionality via the package so there is a unified way to add official bootstrap. Possibly the same technique could be used across most 3rd party libs that are added to Meteor.

**Comment by splendido** [comment]
I've never used build plugin, so I cannot add anything to your suggestion, but I can appreciate that it would be something nice to have in case it is feasible.

**Comment by jesseflorig** [comment]
@yauh  :+1:

**Comment by seanfrasure** [comment]
There are already CDN's if that's what you are referring to...
http://bootstrapcdn.com

**Comment by jesseflorig** [comment]
@seanfrasure - The point is to allow a package `config` to determine whether or not to use a local repo for, lets say, development, and then publish your application to production and have it point to a CDN. Its not about having a CDN available, its about having your application smartly choose between the two.

**Comment by cvrebert** [comment]
Closing this since this suggestion isn't directly actionable by the Core Team (because none of us have Meteor experience) and our two Meteor packaging friends haven't had much advice to offer either; but feel free to continue the discussion here and send a pull request at some point if anyone figures out an implementation of this.
