### ISSUE TITLE
Can i manage image aspect ratio.

### ISSUE THREAD

**Issue by webtuts4u** [twbs/bootstrap#16331]
Hello

Recently i am working on a project which need to manage image aspect ration.
After lots of the searching, i am decide to enter here. Currently i am using "img-responsive" with images.

Its to hard to manage image aspect ratio, when design PSD are 1920px or higher / lesser.

Thanks and Regards
Pankaj Sood

**Comment by patrickhlauke** [comment]
Please direct your specific implementation questions to StackOverflow. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
