### ISSUE TITLE
.help-block is not vertically aligned with label in horizontal form

### ISSUE THREAD

**Issue by jaakritso** [twbs/bootstrap#16337]
.help-block can be used in two ways. Next to form control and under the form control.

If used next to form control, then the vertical alignment is off (-2px).

For example check this out: http://plnkr.co/edit/VA2lXxo3V05iG3Yh6LD1?p=preview

This could be fixed with extra condition (I already added it to the plunker style.css):
```
// If the help-block is direct descendant of form-group align with control-label and form-control
.form-horizontal .form-group > .help-block {
  margin-top: 7px;
  margin-bottom: 8px;
}

```
Related to issue #14721

**Comment by cvrebert** [comment]
> `.help-block` can be used in two ways. Next to form control

I don't think we show or mention such "next to" usage anywhere in the docs, so I'd argue such usage isn't currently officially supported, although it might be a reasonable thing to add.

**Comment by jaakritso** [comment]
Yes you're right. Also you don't show or mention anything how is the correct way to use **help block** in the **horizontal form**.

But yes, as it's basically one-liner addition, then I think it won't hurt to fix it for the users who use help block differently from how it was actually meant to be used.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Doing this would also imply we'd need to vertically center help text with larger and small form controls, too. That makes this a bit more CSS than just the changes mentioned above, but still not a huge deal. The thing is the help text is designed for a new line and all our inputs are block level.

For now, I'm going to punt on this and call it a won't fix.
