### ISSUE TITLE
Mulitple Modals open on one page - removes modal-body class when the first one is closed

### ISSUE THREAD

**Issue by ripzay** [twbs/bootstrap#16330]
Hi all

We have bunch of modal windows which subsequently also pop up their own modal windows for certain functions.

This all works fine, but when one of the child modal windows is closed, it removes the modal-open class from the body tag, which causes the scroll prevention to stop working, and prevents scrolling of the modal.

This is demonstrated in the following fiddle: https://jsfiddle.net/jg6Lkvwe/

- Trigger the Parent Modal
- Scrolling works as expected
- Trigger the Child Modal
- Scrolling works as expected
- Dismiss the Child Modal (click the backdrop)
- Scrolling is broken

We have 'bodged' this by adding a handler to the modal hidden event which checks for other open modals and re-adds the modal-open class to the body.

```js
if ($('.modal.fade.in').length > 0) {
    $('body').addClass('modal-open');
}
```

I realise that this isn't a 'correct' fix, and perhaps the modals were never intended to be used this way.

Cheers

**Comment by cvrebert** [comment]
As mentioned in our docs, having multiple modals open at the same time is explicitly not supported by Bootstrap.
