### ISSUE TITLE
Add slackin badge

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#16348]
https://github.com/rauchg/slackin

**Comment by djch** [comment]
Slackin looks awesome. Does this mean there's going to be a public slack for Bootstrap nerds?

**Comment by seanfrasure** [comment]
Looks nice

**Comment by Insanitariume** [comment]
:+1:

**Comment by cuttingedgehobbies** [comment]
:+1:

**Comment by zacechola** [comment]
@djch [getboostrap.slack.com](https://getbootstrap.slack.com/)

**Comment by mdo** [comment]
Done!
