### ISSUE TITLE
Affix creates a huge margin at the top

### ISSUE THREAD

**Issue by JulijanasJezov** [twbs/bootstrap#16340]
Affix creates additional margin at the top while scrolling fast to the top. It leaves the elements in the right places when inspecting but displays them with the margin at the top, everything becomes unclickable.

![image](https://cloud.githubusercontent.com/assets/6087250/7295600/792c5062-e9af-11e4-8f72-dacf48b69b40.png)

**Comment by cvrebert** [comment]
What OS and browser are you using?

**Comment by JulijanasJezov** [comment]
Win 8.1, Chrome

**Comment by cvrebert** [comment]
The Stable version of Chrome? (as opposed to Canary, Beta, or Dev)

**Comment by JulijanasJezov** [comment]
Yes

**Comment by eddielee6** [comment]
We're also having an issue with this in Chrome v42

**Comment by fat** [comment]
wow that's unfortunate :/

**Comment by fat** [comment]
Maybe someone with windows can help debug a bit for us?

**Comment by juthilo** [comment]
> scrolling fast to the top

@JulijanasJezov Could you elaborate, please? I haven't been able to reproduce so far using my mouse or various keyboard shortcuts.

**Comment by JulijanasJezov** [comment]
I can reproduce it 1 in about 10 times on bootstrap website. You have to be on the page where the affix element is used, scroll down until the affix element sticks to the top and then 1 fast scroll to the top with the mouse wheel.

**Comment by moinakbarali** [comment]
Same issue when you leave page open and navigate tabs for about 10-15 minutes and then open bootstrap tab scroll to top fast.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
