### ISSUE TITLE
Height of plain <input type="week"> doesn't match height of other temporal <input>s in Chrome

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#16346]
As a side-effect of https://github.com/twbs/bootstrap/blob/6ba595f3fffee275922c377a7cc1bc46fc5e58c1/less/forms.less#L179 , the height of a plain `<input type="week">` without any Bootstrap classes doesn't match the height of other plain temporal `<input>`s.
Tested on OS X Chrome using http://jsfiddle.net/5Lh045wd/1/

**Comment by cvrebert** [comment]
I'm thinking we should add `.form-control` to these selectors?
We never make plain temporal `<input>`s be `display: block` in the first place.

**Comment by seanfrasure** [comment]
Or instead of using '''display: block' ''

**Comment by seanfrasure** [comment]
Instead of using 'display: block' maybe you could just adjust the padding with 'padding: #px'.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Sounds fine by me.

**Comment by mdo** [comment]
In fact I've got that temporal stuff commented out in v4 so far. Haven't tested it much yet though, but I wasn't sure if we needed it if we're going class-only for more of our styles.

**Comment by mdo** [comment]
We do need it in v4 still I think. Fuck that bug, ugh.
