### ISSUE TITLE
feature request for 4.x/5.x -- `.form-horizontal` implementations to be consistent with other form types

### ISSUE THREAD

**Issue by jvanasco** [twbs/bootstrap#16349]
I know this is a big ask, hence the future versions.

The current horizontal implementation requires a col-xx-yy class declaration on the form label and the input must be nested into a div with a column size declaration.  

This is inconsistent with the other classes.

It would be great if the html structuring could be more similar / identical; maybe have an option where the column sizes are defaults or pulled from js.

This request is born from the fact that transitioning an existing "basic" to "horizontal" form is a lot more tedious than it should be (as would transitioning back if this doesn't work out and version control doesn't exist)

**Comment by mdo** [comment]
v4 will lean further into grid classes to accomplish the horizontal layout, without the need for a parent `.form-horizontal` class.
