### ISSUE TITLE
Iphone 6 - Menu Toggle Issue

### ISSUE THREAD

**Issue by shoaibaslam007** [twbs/bootstrap#16355]
Bootstrap menu is not working in iphone6. Even getbootstrap.com it's own menu is not working.
Please help on the same.

**Comment by kukac7** [comment]
ios simulator iphone 6 ios 8.3 - working :+1:

**Comment by shoaibaslam007** [comment]
apps.eadaapps.com/tejkohlifoundation plz check this link, It's working on simulator but not in device having ios 8.3.

**Comment by patrickhlauke** [comment]
We will need a reduced test case, just showing the erroneous behavior without any additional page elements/scripts that may interfere. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Testing the link you gave on iPhone5 did not exhibit any anomalous behavior. I'm hard pressed to think why it wouldn't also work on iPhone6

**Comment by shoaibaslam007** [comment]
Resolved ...Thanks for the help Its device's issues somehow its blocking the js.
