### ISSUE TITLE
Feature Request: Grid System with (real) margins gutter

### ISSUE THREAD

**Issue by 7R5N** [twbs/bootstrap#16358]
I **love** bootstrap, especially it’s grid system: I love its flexibility, that you can nest it, and particularly that you can apply it via mixins to your custom HTML-Structure. 

But it even could go better: 
A grid system with *margins* as grid-gutter — that would be awesome! 

Because then we could use the paddings for inner spacing (what they were actaully made for) **along with** grid gutters, *without* having to nest another DIV for the actual paddings. 

There are grid systems in the wild, which can do, e.g Burbon Neat: 
- The cols have a right margin (in percentage; that’s arithmetics)
- The last-in-a-row is specially marked, to get *no* margin-right
- But it looks to me that this must be applied by someone(?); that is imho not yet fully developed

Maybe the bootstrap grid-system could be refined into this direction:
- Half of the gutter width on columns left and right, but as *margins*, calculated in percentage
- Container with half gutter width as minus margin (as is)
- No further need to lift a finger … 
- That’s it, right …!? I didn’t took the time yet to try it …

Maybe you already had this idea, perhaps it’s already in the pipe for v4 — so thank you for reading, anyway …  ;-)

Thnx
7R5N

**Comment by mdo** [comment]
We used to do margins. Padding is easier because it's part of the overall `width` with our `box-sizing` reset. This way, there's no weird calculations to do for figuring out dimensions minus the gutters.
