### ISSUE TITLE
Click Events Running Twice

### ISSUE THREAD

**Issue by codebeginer** [twbs/bootstrap#16353]
Suppose we have loaded the modal content with ajax. The loaded content has some jquery code in itself which includes some click events. The click events in the modal will run once when opened first time, but when we re-open the modal then the same events runs twice.

**Comment by cvrebert** [comment]
As this isn't a bug report or feature request, and isn't particularly Bootstrap-specific, it's not suitable for this issue tracker. Try asking on StackOverflow (or similar) instead.
