### ISSUE TITLE
PostCSS port

### ISSUE THREAD

**Issue by corysimmons** [twbs/bootstrap#16366]
@mdo Want to keep this issue open to bat around ideas for a port to PostCSS?

I'd be interested in helping *a lot* with this port just to get more people using PostCSS instead of preprocessors for libraries.

**Comment by mdo** [comment]
Sure.

**Comment by corysimmons** [comment]
What do you imagine some real world syntax looking like? For example, a button?

**Comment by corysimmons** [comment]
Like are you looking to tie functions into CSS or are you just looking to rewrite the LESS (soon to be SCSS) mixin library to PostCSS?

Example of tying functions into CSS:

```css
.my-cool-button {
  twbs-btn: primary large;
}
```

**Comment by mdo** [comment]
That kind of stuff is far too crazy for Bootstrap I think. Just getting things on the CSS4 syntax (variables for example) and what not is what I'd expect.

**Comment by corysimmons** [comment]
No problem. I agree.

I think we should rewrite the mixin library in PostCSS at least so we can remove all dependencies on *any* preprocessor.

**Comment by corysimmons** [comment]
As an example of the power of rewriting the mixins with PostCSS, you could do things like make it so when you dropped `avatar.svg` into an `icons/` folder, it would automatically create an `.icon-avatar` class and assign certain values to it: https://github.com/postcss/postcss-mixins#function-mixin

Or make the grid system incredibly flexible by accepting fractions so we could generate the CSS like so:

```css
@mixin grid 1-12;
```

Want to up it to 24 columns?

```css
@mixin grid 1-24;
```

**Comment by corysimmons** [comment]
Closing this before I scare everyone away from PostCSS bouncing crazy ideas around.

Excited to see what you guys do with it.

**Comment by SpencerCarstens** [comment]
@corysimmons - Sorry for the necro post - you seem like a guy to ask this though.

How do you think it would be best to approach future proofing a new codebase that uses Bootstrap-LESS, to be a "semi" painless transition to Bootstrap-PostCSS?

What I was thinking was making a custom Bootstrap build as usual. Apply all the desired variable overrides and then export .css via whatever PP. 

Then take over from there with PostCSS. There would have to be a file used to keep track "shared" variables...

Doesn't seem THAT painful...

**Comment by corysimmons** [comment]
I'd just convert the LESS mixins/functions to PostCSS as I went. Really that's all PostCSS would be replacing.
