### ISSUE TITLE
navbar toggle button and collapse accordion issue on Android Browser

### ISSUE THREAD

**Issue by porque09** [twbs/bootstrap#16364]
I use bootstrap 3.3.4 and I have issue with toggel button and accordion doesn't collapse in android navigator although it work fine in desktop with chrome, firefox, opera and safari.
this is my code: http://pastebin.com/wjhfEzeE

**Comment by cvrebert** [comment]
(Please note that we don't officially support the Android Browser, owing to how buggy and inconsistent it is.)
What version of Android? What version of the browser?

**Comment by porque09** [comment]
I use android 2.3.6 and the browser version is 2.3.6

**Comment by cvrebert** [comment]
Your site has some [Bootlint](https://github.com/twbs/bootlint) errors; you should fix those.

Given that this issue is regarding an unsupported browser, it's unlikely that the team will investigate this issue any further. But if you do find a reasonable fix, we'd be happy to consider merging it.

**Comment by porque09** [comment]
ok thank you very much for your assistance
