### ISSUE TITLE
modal plugin can't reopen if closed not from close button

### ISSUE THREAD

**Issue by youneschaoui** [twbs/bootstrap#16363]
When a user Opens Modal plugin he has 3 choices of how to close it : 
1- X Icon
2- Close button
3- Press anywhere outside the modal plugin window
If he goes with the third one, the modal can't be opened again.

Try it yourself http://www.w3schools.com/bootstrap/bootstrap_modal.asp

**Comment by cvrebert** [comment]
Looks like some bug specific to that page.
http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_modal&stacked=h and http://getbootstrap.com/javascript/#modals work fine.

**Comment by cvrebert** [comment]
* They are loading multiple copies of Bootstrap's JavaScript, which is a recipe for fail.
  * These copies are from different versions of Bootstrap; double fail.
* The latest version of Bootstrap they are loading is v3.3.1, which is somewhat outdated.
* The page has several [Bootlint](https://github.com/twbs/bootlint) errors, mostly regarding grid system usage.

In conclusion, I would advise not using w3schools.
