### ISSUE TITLE
Cannot disable stateful button

### ISSUE THREAD

**Issue by patrickyan** [twbs/bootstrap#16362]
I need to disable a button after it loads something. Unfortunately, Bootstrap is killing the disabled attribute and class no matter how I add it. See http://codepen.io/anon/pen/Wvbeeg

**Comment by twbs-lmvtfy** [comment]
Hi @patrickyan!

You appear to have posted a live example (http://codepen.io/anon/pen/Wvbeeg.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 8, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickyan** [comment]
@twbs-lmvtfy added type="button"

**Comment by cvrebert** [comment]
@patrickyan You are using Bootstrap v3.1.1. Please upgrade to v3.3.4.

**Comment by patrickyan** [comment]
@cvrebert I updated the code pen to the latest bootstrap, and it still doesn't work.

**Comment by cvrebert** [comment]
The `reset` method is asynchronous. This ought to be documented better.

**Comment by patrickyan** [comment]
But there isn't any kind of callback, or is there? How can I call code after the button is done doing it's thing?

**Comment by cvrebert** [comment]
There isn't. The single-stateful-button part of the button.js isn't very good/useful, TBH. I don't recommend using it. We might be removing it in v4. (We'll definitely be retaining the checkboxes/radios part of it though.)

**Comment by fat** [comment]
+1 to what @cvrebert mentioned. We'll be removing this from v4.

In the meantime, if you're dead set on using the state methods in v3, update your code to push the disabling code to the event loop like this:

```js
…
      if ($btn.is('#mybutton')) {
        // push to event loop to wait for reset to complete
        setTimeout(function () {
          console.log('disabling button');
          $btn.prop('disabled', true);

          $btn.attr('disabled', 'disabled');

          $btn.addClass('disabled');
        }, 0)
      }
...
```

**Comment by cssguru** [comment]
I just ran into this myself.   It appears that data-loading-text has undocumented behavior attached to it.  See my bin... http://jsbin.com/wafasi/3/edit.  If you use data-load-text instead and manage the enabled/disabled state yourself it is much more reliable.

**Comment by twbs-lmvtfy** [comment]
Hi @cssguru!

You appear to have posted a live example (http://jsbin.com/wafasi/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
