### ISSUE TITLE
Chrome. Table cell width is wrong using an input-group feature

### ISSUE THREAD

**Issue by TriAnMan** [twbs/bootstrap#16372]
Not a Bootstrap bug, but maybe it should be added to http://getbootstrap.com/browser-bugs/
See: https://code.google.com/p/chromium/issues/detail?id=427994

**Comment by thomasphorton** [comment]
I made a PR for a table-cell issue recently, is this related? There might be more to this.

https://github.com/twbs/bootstrap/pull/16350

**Comment by TriAnMan** [comment]
@thomasphorton
Have tried to apply `max-width: none;` for each element in my example and have no result.

**Comment by cvrebert** [comment]
This probably comes down to vagueness/implementation-definedness in the CSS 2.1 table layout spec, but that's arguably a deficiency in the spec, and pointing out bugs due to related implementation differences might encourage the development of more precise specs.
@mdo Any objection to adding this to the Wall?

**Comment by thomasphorton** [comment]
:+1:

**Comment by mdo** [comment]
Sounds like a prime candidate for the Wall.

**Comment by cvrebert** [comment]
OS X Safari 8.0.5 suffers from the same bug.

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=144696

**Comment by cvrebert** [comment]
Filed Safari bug: http://openradar.appspot.com/20839572

**Comment by davidsgrogan** [comment]
FYI, This should be fixed in chrome 53. See https://crbug.com/427994 (Table cell width is wrong using a twitter bootstrap input-group feature)

**Comment by cvrebert** [comment]
@davidsgrogan Great! :smile: :heart: Will do!
