### ISSUE TITLE
Horizontal-form layout breaks when label is too long

### ISSUE THREAD

**Issue by RiccardoDalFiume** [twbs/bootstrap#16375]
Don't know how to fix, just reporting.

http://plnkr.co/edit/zRqA9CkrmP8A1rlYjviY?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @RiccardoDalFiume!

You appear to have posted a live example (http://run.plnkr.co/plunks/zRqA9CkrmP8A1rlYjviY/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 5, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 6, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by RiccardoDalFiume** [comment]
http://plnkr.co/edit/zRqA9CkrmP8A1rlYjviY?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @RiccardoDalFiume!

You appear to have posted a live example (http://run.plnkr.co/plunks/zRqA9CkrmP8A1rlYjviY/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 5, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 6, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by RiccardoDalFiume** [comment]
http://plnkr.co/edit/zRqA9CkrmP8A1rlYjviY?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @RiccardoDalFiume!

You appear to have posted a live example (http://run.plnkr.co/plunks/zRqA9CkrmP8A1rlYjviY/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 8, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2
* line 9, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by RiccardoDalFiume** [comment]
http://plnkr.co/edit/zRqA9CkrmP8A1rlYjviY?p=preview

**Comment by mdo** [comment]
No worries about the errors there, I run into them all the time :D.

Your only real options are to use a different column class for the label column—thereby making it wider—or using CSS text truncation (check the docs section on utilities).
