### ISSUE TITLE
In Windows Safari <select> and <input> are not always the same height

### ISSUE THREAD

**Issue by chentaol** [twbs/bootstrap#16377]
In safari under high input select and not always the same, such as high default and select the default input is not the same, input of sm and select high is not the same.
![20150427173509](https://cloud.githubusercontent.com/assets/4080883/7345434/0ae2ebba-ed07-11e4-9f66-a530983d87e6.jpg)
![20150427173645](https://cloud.githubusercontent.com/assets/4080883/7345436/0c045876-ed07-11e4-858a-4802317f8bab.jpg)

**Comment by cvrebert** [comment]
We do not support Windows Safari; see http://getbootstrap.com/getting-started/#support

**Comment by acirinelli** [comment]
I found the same issue in Chrome. Fixed my own copy by adding:
`select.form-control {
    padding: .5em .75em;
}`
