### ISSUE TITLE
Dropdown-menu with dropdown-submenu

### ISSUE THREAD

**Issue by rpristopan** [twbs/bootstrap#16387]
Hi guys,

In older versions (e.g 2.x.x) you could add sub-menus to a dropdown, but in version 3.x.x this feature is missing.

![dropdown-with-submenu](https://cloud.githubusercontent.com/assets/5400982/7369927/c673dce2-edbe-11e4-9e71-069962cfbc6f.png)

**Comment by cvrebert** [comment]
This feature was purposefully removed by @mdo as he feels that submenus aren't great UX, particularly on mobile.

**Comment by acthp** [comment]
What's the alternative?

**Comment by cvrebert** [comment]
I believe there wasn't any one-size-fits-all suggestion beyond reworking your information architecture to not require nested menus.
You can also ask him yourself via Slack: https://github.com/twbs/bootstrap/blob/master/README.md#community

**Comment by akostadinov** [comment]
The only issue with multi-level menus I see when browsing the other issues is that hover is not possible on mobile. IMO this can be simply resolved by also expanding on click, not only hover. Best of both worlds IMO. Single-level menus are IMO crap for navigation. I hate when i have to click multiple times to reach some part of the web site.
