### ISSUE TITLE
Can't click drop-down links over carousel

### ISSUE THREAD

**Issue by d3inc** [twbs/bootstrap#16388]
Hi. I have a navbar that sits above a bootstrap carousel. When I click on a drop-down link, the drop-down menu appears, as normal. However, when I over over the links, the hover states don't activate, and nothing happens when I click on the links. Sometimes, it will work! It seems to work randomly during the transition of the carousel. Any tips?

**Comment by cvrebert** [comment]
Could you post a JS Fiddle demonstrating the problem?
What browser and OS are you using?

**Comment by d3inc** [comment]
Thanks for the reply. Here is the JSFiddle: 

https://jsfiddle.net/y5mgcfL8/embedded/result/

**Comment by twbs-lmvtfy** [comment]
Hi @d3inc!

You appear to have posted a live example (https://fiddle.jshell.net/y5mgcfL8/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 1023, column 29 thru line 1023, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 1028, column 29 thru line 1028, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 1033, column 29 thru line 1033, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 1038, column 29 thru line 1038, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 867, column 10 thru line 867, column 155: The ```` aria-controls ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by d3inc** [comment]
Here is the JSFiddle: https://jsfiddle.net/y5mgcfL8/embedded/result/
It seems to be working there, which is strange. I'm using Google Chrome. 
Here it is uploaded on Amazon S3: https://s3-us-west-2.amazonaws.com/nebc/index.html
Sometimes the links work in the drop down for 'About' and sometimes they don't. It's very strange.

**Comment by twbs-lmvtfy** [comment]
Hi @d3inc!

You appear to have posted a live example (https://fiddle.jshell.net/y5mgcfL8/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 1023, column 29 thru line 1023, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 1028, column 29 thru line 1028, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 1033, column 29 thru line 1033, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 1038, column 29 thru line 1038, column 77: The element ```` button ```` must not appear as a descendant of the ```` a ```` element.
* line 867, column 10 thru line 867, column 155: The ```` aria-controls ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by d3inc** [comment]
I'm trying to upload the JSFiddle but it keeps complaining about how a button element must not appear inside of an a element. I've uploaded it to Amazon S3: https://s3-us-west-2.amazonaws.com/nebc/index.html

I'm using Google Chrome.

**Comment by patrickhlauke** [comment]
For what it's worth, @twbs-lmvtfy is right...you can't have a `<button>` element wrapped inside an `<a>` (in your "Services we offer" section).

Your problem, in any case, is one of `z-index` on your `.carousel-control`.

Additionally, please refer to https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker and post personal support requests on StackOverflow, rather than here.
