### ISSUE TITLE
Modal ignores options

### ISSUE THREAD

**Issue by KarelCemus** [twbs/bootstrap#16391]
I want to open Modal from the javascript through

    $('#myModal').modal({
     backdrop: 'static',
     keyboard: false
    });

But it completely ignores my options. I looked into the source code and it seems to me that options received through javascript are really almost completely ignored. The are used only for the `options.show`, see [code](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L298). The actual value of `options` in the `show` method contains only default options.

I believe this is unintended behavior.

**Comment by fat** [comment]
modal doesn't ignore options, see here: https://github.com/twbs/bootstrap/blob/master/js/modal.js#L296

If you believe i'm wrong, please provide a link to them not working, or better a unit test. thanks!

**Comment by KarelCemus** [comment]
That's correct but when I debugged it, the data were set thus if (!data) were false. I try to reproduce and let you know

**Comment by KarelCemus** [comment]
Ok, I figured it out. Once is the modal initialized it caches the options and they cannot be overwritten.  That's what I wanted to do. I wanted to open the modal always with a different configuration.
