### ISSUE TITLE
Little blank space and scroll-x activation

### ISSUE THREAD

**Issue by DaGLiMiOuX** [twbs/bootstrap#16390]
Hi there.

I was working into a full responsive webpage for a client using bootstrap and I found something... strange using <b>.container</b> class behavior.

I had the following code:
```html
<div class="banner">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-8 text-center">
				<span>Some text</span>
			</div>
			<div class="col-sm-12 col-md-4 text-center">
				<span><a href="#">Some text <i class="fa fa-chevron-right"></i></a></span>
			</div>
		</div>
	</div>
</div>
```
After adding this, I got a blank space at the right side between <b>768px</b> and <b>770px</b> width window resolution and activates the horizontal scrollbar (scroll-x) to travel through web page as if it has more content on the right side. I fixed it modifing this line:
```css
width: 100%;
```
Into my <b>bootstrap.min.css</b> at:
```css
@media(min-width: 768px) {
    .container {
        width: 100%;
    }
}
```
By default it has <b>750px</b> width and I don't know if it is a bug or something.

I've checked if it was a conflict with my own css removing my styles for that block on the webpage or if I used a wrong class tag to check if was something related with paddings/margins and It was still showing a blank space.

Hope we can find the truth.

Regards,
DaGLiMiOuX

**Comment by cvrebert** [comment]
Please post a [JS Bin](http://jsbin.com) version of your example.
Also, which browser and OS are you using?

**Comment by thomasphorton** [comment]
Not seeing anything on OS X Chrome

http://codepen.io/tho/pen/JdoxeE

**Comment by twbs-lmvtfy** [comment]
Hi @thomasphorton!

You appear to have posted a live example (http://codepen.io/tho/pen/JdoxeE.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru line 8, column 6: Stray start tag ```` html ````.
* line 9, column 1 thru line 9, column 6: Stray start tag ```` head ````.
* line 11, column 1 thru line 11, column 112: Element ```` link ```` is missing required attribute ```` property ````.
* line 13, column 3 thru line 13, column 24: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 13, column 3 thru line 13, column 24: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 14, column 3 thru line 14, column 9: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 15, column 1 thru line 15, column 7: Stray end tag ```` head ````.
* line 16, column 1 thru line 16, column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 31, column 1 thru line 31, column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by thomasphorton** [comment]
ugh oh well. not sure how to format codepen right for this.

**Comment by cvrebert** [comment]
You're missing the DOCTYPE declaration.

**Comment by thomasphorton** [comment]
gah, codepen threw an error and told me to leave it out. I'll play around with it.

**Comment by mdo** [comment]
The `.container` has a fixed `width`. If you place it within another element that has `padding`, and that `padding` constrains the content to be less than the applied width on the `.container`, you will see horizontal scrolling problems.

Perhaps we should add a `max-width: 100%` to our containers then? It'd help out for these instances.

(Btw, this is the same as our jumbotron padding problem in #16374.)

**Comment by DaGLiMiOuX** [comment]
Already fixed. According to bootstrap documentation:

> Bootstrap requires a containing element to wrap site contents and house our grid system. You may choose one of two containers to use in your projects. Note that, due to padding and more, **neither** container is nestable.

I had a ```.container``` inside a ```.container-fluid ``` and that caused the problem. I will take it in count for my future projects =P

Thanks to all for your help.

**Comment by mdo** [comment]
Closing out then.
