### ISSUE TITLE
img-responsive class issue on IE11

### ISSUE THREAD

**Issue by xingle** [twbs/bootstrap#16399]
There is a mini css bug for class 'img-responsive' on IE11.
I inspected element on IE11 and it says:

width: 100% \9;

and it cause the problem. images are not responsive on IE11.

**Comment by cvrebert** [comment]
What problem does it cause?
The `\9` is a CSS browser hack and is expected to cause a parse error and be ignored in old IE.

**Comment by cvrebert** [comment]
See also http://getbootstrap.com/getting-started/#support-validators

**Comment by xingle** [comment]
Images are not responsive on IE11 with 'img-responsive'.

width: 100% \9;

seems like above line is ignored because of \9 on IE11.

**Comment by cvrebert** [comment]
What version of Bootstrap are you using?

**Comment by cvrebert** [comment]
AFAICT, no such line exists in the current version of Bootstrap's CSS. You must be using an outdated version.

**Comment by Sarahabogabir1** [comment]
Having the same issue. Using:
` .image-responsive{
  width:100%;
 }
`
Seems to fix it
