### ISSUE TITLE
Error detected in .modal('toggle')

### ISSUE THREAD

**Issue by snmdoc** [twbs/bootstrap#16393]
Hello!,

I'm trying to hide a modal through when a ajax jQuery action is completed by a button. The perceived problem is that when the user clicks simultaneous quickly tries to hide the modal several times and causes an error.

Greetings

**Comment by neilhem** [comment]
I guess problem just in your custom code not in bootstrap's modal.js plugin, but at least give us a link to your site/jsfiddle/codepen we will try to help you.

**Comment by cvrebert** [comment]
Until you're more certain that the problem isn't due to a bug in your own code, please take your question to StackOverflow (or similar). Thanks!
