### ISSUE TITLE
Can't download customized version via Google Chrome

### ISSUE THREAD

**Issue by vajahath** [twbs/bootstrap#16397]
http://getbootstrap.com/customize/
Can't compile and download
![image](https://cloud.githubusercontent.com/assets/12165822/7396042/9f6ee35a-eebb-11e4-81d8-5d537b1264d2.png)

The button is disabled.!

**Comment by wolfy1339** [comment]
Did you spoof your user agent?
I can't reproduce on Chrome 42 Windows

**Comment by cvrebert** [comment]
Unable to reproduce on Windows Chrome. Try disabling your Chrome extensions.
