### ISSUE TITLE
Tooltip does not work in meteor

### ISSUE THREAD

**Issue by xois** [twbs/bootstrap#16407]
@dandv 
Here is my sample code:
https://github.com/xois/meteortooltip

header.html
```html
<li><a data-toggle="tooltip" title="test title" href="#">test</a></li>
```
header.js
```js
Template.header.rendered = function() {
  $('[data-toggle="tooltip"]').tooltip({palacement: 'bottom'});
}; 
```

packages
```
meteor-platform
twbs:bootstrap
iron:router
```

**Comment by Quy** [comment]
Typo in `palacement`.

**Comment by cvrebert** [comment]
CC: @splendido

**Comment by dandv** [comment]
This works after fixing the typo:

![image](https://cloud.githubusercontent.com/assets/33569/7442724/9abf9a80-f0d1-11e4-9351-d219d92e425f.png)

**Comment by splendido** [comment]
Confirmed!

I also suggest to use the following to initialize it:

```javascript
Template.header.onRendered(function() {
  this.$('[data-toggle="tooltip"]').tooltip({placement: 'bottom'});
});
```

please note the new `onRendered` method and `this.$` in place of simply `$` which has better performances limiting the search to the template's content.

**Comment by hms37** [comment]
what could posssibly be the issue with the code you mentioned as my tooltip stays throughout the canvas when i clicked on the element and it does not go 

Template.RTableStatusMessage.onRendered(function() {
    const instance = this;
    instance.tooltipEl = instance.$('[data-toggle="tooltip"]').tooltip({
        title: 'Getting last heartbeat time...',
        placement: 'left',

        template: `<div data-res-id-${instance.data._id} class="tooltip" role="tooltip">
        <div class="tooltip-arrow"></div>
        <div class="tooltip-inner"></div>
        </div>`

    });
    function updateTip(event) {
        const target = $(event.currentTarget);
        const resourceId = target.data('resourceGetLastHeartbeatTime');
        Meteor.call('resource.getLastHeartbeatTime', resourceId, function(err, res) {
            if (res) {
                const tooltipText = moment(res).calendar();
                // necessary to permenantly change the tips in the html and the data attr
                instance.tooltipEl.attr('data-original-title', tooltipText);
                $('[data-res-id-' + resourceId + ']').find('.tooltip-inner').html(tooltipText);
            }
        });
    }
    instance.throttledUpdateTip = _.throttle(updateTip, HEARTBEAT_WAIT / 1000);
});
