### ISSUE TITLE
Collapse emulateTransitionEnd parameter should be configurable via options

### ISSUE THREAD

**Issue by elisechant** [twbs/bootstrap#16418]
We should be able to easily configure the value of emulateTransitionEnd speed via options, like: ````data-emulate-speed="200"````

````
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-emulate-speed="200" data-target="#navbar-collapse-search">Search</button>
````

**Comment by cvrebert** [comment]
@elisechant I don't get what the use case is for using a value different from the transition duration in the CSS.

**Comment by fat** [comment]
I dont think we want to add this as a data attribute - customization of this value is already possible in css

**Comment by elisechant** [comment]
what is the purpose of the method in that case?

**Comment by fat** [comment]
http://blog.alexmaccaw.com/css-transitions

**Comment by fat** [comment]
alex explains it at the end of the article

**Comment by cvrebert** [comment]
See also https://code.google.com/p/chromium/issues/detail?id=437860
