### ISSUE TITLE
better naming for enable Right-To-Left support

### ISSUE THREAD

**Issue by oriSomething** [twbs/bootstrap#16419]
i guess it would be more relevant in BS4, but still, i think we can have better naming so it will be easier to have support when needed to RTL to multi languages site:
`.pull-left` -> `.pull-start`
`.pull-right` -> `.pull-end`

same with texts:
`.text-left` -> `.text-start`
`.text-right` -> `.text-end`

so if there is `.text-left` in addition, it will always be aligned to left and won't have unexpected behavior.
the reason is when you make RTL support, many times you'll have to support multi languages with both LTR and RTL directions on the same page. so this naming convension, can make it much easier and more clearer for the developer

**Comment by Natshah** [comment]
This is a very good idea . I do like it.

And the start and end can work for Horizontal and Vertical too.

I do have this repository about Bootstrap Pull 3.x-1.1.1
https://github.com/Natshah/bootstrap-pull

I had a hint at this issue https://github.com/twbs/bootstrap/issues/13690
Punting to v4 

Thanks.

**Comment by cvrebert** [comment]
Noted for consideration for Bootstrap v4.

**Comment by oriSomething** [comment]
@cvrebert by the way, i use this kind of code for building `RTL` and `LTR` versions:
```scss
.text-start {
  @if $is-rtl {
    text-align: right;
  } @else {
    text-align: left;
  }
}
```
