### ISSUE TITLE
Tooltip positioned incorrectly (bootstrap 3.3.4)

### ISSUE THREAD

**Issue by alexanderlobanov** [twbs/bootstrap#16410]
![screen shot 2015-05-02 at 23 03 18](https://cloud.githubusercontent.com/assets/10610951/7442576/9f6200fc-f11f-11e4-9de1-3e50008d0e1f.png)

If browser width > 1515px and height 720px, tooltip-innner positioned incorrectly (in some cases).

**Comment by cvrebert** [comment]
@alexanderlobanov We cannot help you without a [JS Bin](http://jsbin.com) example that demonstrates the problem. We can't debug screenshots.

**Comment by alexanderlobanov** [comment]
We removed viewport option and bug disappeared.
```
$(<selector>).tooltip({
	trigger: 'click',
	//viewport: {selector: ownerSelector + ' .all-tooltips', padding: 0},
	placement: 'auto',
	html: true,
	title: '<span class="titleKeyWords">' + keyword.keyword + '</span><span class="textKeyWords"> ' + keyword.text + '</span>'
});
```
