### ISSUE TITLE
Windows phone - tried the fixes still won't work

### ISSUE THREAD

**Issue by emruscoe** [twbs/bootstrap#16415]
Hi Very, new to this coding malarkey and really struggling with the windows phone fix. have chaged my css and added the javascript to my header but no dice... any ideas? The navbar is just coming up as a list on hyperlinks at the moment rather than the snazzy dropdown

**Comment by cvrebert** [comment]
Please ask troubleshooting questions on [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3) rather than this bug tracker. Thanks!
