### ISSUE TITLE
Navbar dropdown-toggle does not get blue border when focused.

### ISSUE THREAD

**Issue by stefanseeger** [twbs/bootstrap#16412]
Hi, 
1. go to the example page for the navbar: http://getbootstrap.com/examples/navbar/
2. Use the Tabulator-key to iterate through the navbar links.

You will now see that the Home, About and Contact links get a blue border.
![Contact example](https://cloud.githubusercontent.com/assets/11074488/7445053/a4939e54-f1a2-11e4-81da-2ae4042677e3.png)

Unfortunately, the dropdown-toggle will not get the blue border when focused (no screenshot because, nothing to see)

This problem is related to

    .dropdown-toggle:focus {
     outline: 0;
    }
when disabling this line it works as expected for me.

Another way is to remove the class dropdown-toggle from the <a> tag
    
    // Remove
    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
    // Replace
    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false">
Then, the link has a border when focused.
![image](https://cloud.githubusercontent.com/assets/11074488/7445098/fc814290-f1a4-11e4-8f5d-ee99660fb6ee.png)
 **But**, when I refocus the dropdown while it is open, the focus border is not there again. Which is a bit confusing.
![image](https://cloud.githubusercontent.com/assets/11074488/7445108/3304b9b4-f1a5-11e4-9109-6ac29954fd4b.png)

I do not know which is the better solution/workaround.

Maybe some one of you guys can have a look.

Thanks
Stefan

**Comment by patrickhlauke** [comment]
This is a known issue (see for instance #16103) which unfortunately does not have a clean solution. We're hoping to revisit this in version 4, but for now I'm afraid we won't be able to address that (without breaking backwards compat in some way, or adding extra JavaScript logic to set/unset the focus styling based on the user's last interaction - mouse or keyboard).
