### ISSUE TITLE
bootstrap not remember user and pass on IOS: Iphone, iPad

### ISSUE THREAD

**Issue by nhachothue** [twbs/bootstrap#16423]
bootstrap not remember user and pass on IOS: Iphone, iPad. Help me!

**Comment by patrickhlauke** [comment]
Nothing to do with Bootstrap itself, I'm afraid. I suggest you ask on StackOverflow for specific advice on what it is you're trying to develop. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
