### ISSUE TITLE
print css background color transparent important

### ISSUE THREAD

**Issue by iqmeta** [twbs/bootstrap#16420]
there is a css directive with transparent background color set to important with media print.

if you have a lot of divs with dynamic background color on your page, 
and you want that color to be printed, you have no change of get rid of
the css property in general. 

you can only remove it from bootstrap.css or set for each div especially the exact color again -
but only static in css, not with jquery because of the media print directive. 

See also http://stackoverflow.com/a/20534590
or https://github.com/h5bp/html5-boilerplate/issues/1643

is there any way of overwriting instead of make changes to source bootstrap css?

**Comment by iqmeta** [comment]
okay, solved it with a hacky workaround....
```javascript
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CssTest</title>
    <link href="/libs/dev/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <script src="/libs/dev/common.js"></script>
</head>
<body>
    <button>Test Change / Add Dynamic</button><br />
    <br />
    <div id="test1" style="background-color: red; display: block; width: 500px; height: 100px">
        HELLO
    </div>
    <div id="test2" style="background-color: green; display: block; width: 500px; height: 100px">
        HELLO
    </div>
    <div id="test3" style="background-color: orange; display: block; width: 500px; height: 100px">
        HELLO
    </div>

    <script>
        var app = {};
        app.updatePrintCSS = function (items) {
            $("[data-role='printAdded']").remove();
            $(items).each(function (i, e) {
                var data = "@@media print{#" + $(e).attr("id") + "{ background-color: " + $(e).css("background-color") + " !important; }}";
                $("<style data-role='printAdded'></style>").appendTo("head").html(data);
            });
        }
        $(function () {
            app.updatePrintCSS($("div"));
            $("button").on("click", function (e) {
                $("#test3").css("background-color", "#FF69B4 !important");
                $("body").append($('<div id="test4" style="background-color: blue; display: block; width: 500px; height: 100px" >HELLO</div>'));
                app.updatePrintCSS($('div'));
            });
        });
    </script>
</body>
</html>
```

**Comment by cvrebert** [comment]
FWIW, the CSS snippet in question is gone in Bootstrap v4; it was deemed to be overly opinionated.
We probably can't remove it in Bootstrap v3 due to backward compatibility constraints.

**Comment by AckerApple** [comment]
I'm so so so so so so glad to hear this print important override was removed in 4. I'm gonna stop trying to fiddle with it in 3 and just start moving to 4... Worst class definition I've come across

**Comment by webprogrammierer** [comment]
Isn't there any way to override this or remove this in/from Bootstrap 3?
