### ISSUE TITLE
Undocumented Stateful Button Behavior

### ISSUE THREAD

**Issue by cssguru** [twbs/bootstrap#16429]
It appears as though data-loading-text has some built in behavior that is not documented. Bug or feature?  See my bin here for an example...

http://jsbin.com/wafasi/3/

As you will see data-loading-text kills my disabled state, but data-load-text does not.

**Comment by twbs-lmvtfy** [comment]
Hi @cssguru!

You appear to have posted a live example (http://jsbin.com/wafasi/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Questionable feature; see https://github.com/twbs/bootstrap/blob/d9a7cb2a09b889e324273739d2ec46eb8e2be75b/js/button.js#L42 and the parts of the code using `isLoading`.
However, the Stateful Button itself has now been deprecated anyway (#16430), so trying to document this isn't a huge priority.

**Comment by fat** [comment]
yep agreed - closing for now, don't think we want to encourage people to use w more documentation
