### ISSUE TITLE
Support for nested input groups

### ISSUE THREAD

**Issue by johnnyshields** [twbs/bootstrap#16425]
It would be nice if it were possible to have nested input-groups like this:

![image](https://cloud.githubusercontent.com/assets/27655/7474021/c914f95c-f379-11e4-9271-6bb8f95217e8.png)

**Comment by cvrebert** [comment]
* What's your concrete use case that requires this?
* Do you really want/need nesting, or just multiple add-ons per side?

**Comment by johnnyshields** [comment]
I use Ember JS has a concept of "components" which are coupled to HTML tags.

Here's one example where I have a "InternationalPhoneInput" component inside another component which provides the ability to tag and delete the phone number.

![image](https://cloud.githubusercontent.com/assets/27655/7479127/8dfdeaec-f39a-11e4-8dff-71d122da0076.png)

**Comment by mdo** [comment]
Passing on this—we explicitly don't support multiple add-ons per side. This is just another take on that.

**Comment by supergibbs** [comment]
@mdo I don't think the nested input-groups are needed but multiple buttons on a side is useful. 

I use this http://output.jsbin.com/tiqanu/1/ as part of my ReCaptcha and it works fine. BootLint calls it an error but there is a CSS rule that seems to be specifically for it:
`.input-group-btn > .btn + .btn { margin-left: -1px; }`

There are also rules for `.input-group-btn > .btn-group` which maybe was the plan but isn't mentioned in the docs and doesn't work (see my jsbin)

What am I missing?

**Comment by cvrebert** [comment]
@supergibbs The code you're referring to is for http://getbootstrap.com/components/#input-groups-buttons-segmented

**Comment by supergibbs** [comment]
Of course, duh. Sorry. 

Still seems like multiple buttons work and yet the [docs explicitly say](http://getbootstrap.com/components/#input-groups-basic) it's not supported.

**Comment by cvrebert** [comment]
Hmm, interesting. I think we had non-button add-ons in mind when adding that note.
Example: http://jsbin.com/mujone/3/edit

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/mujone/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 48, column 7: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* line 51, column 7: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* line 36, column 13: [E036](https://github.com/twbs/bootlint/wiki/E036): Having multiple `.btn`s inside of a single `.input-group-btn` is not supported
* line 37, column 13: [E036](https://github.com/twbs/bootlint/wiki/E036): Having multiple `.btn`s inside of a single `.input-group-btn` is not supported
* line 38, column 13: [E036](https://github.com/twbs/bootlint/wiki/E036): Having multiple `.btn`s inside of a single `.input-group-btn` is not supported

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
