### ISSUE TITLE
.has-error etc directly on .form-control

### ISSUE THREAD

**Issue by johnnyshields** [twbs/bootstrap#16421]
This may be a dupe of #14735 and others but wanted to re-raise in light of upcoming BS4 work.

It would be nice to be able to specify the class `has-error` directly on a `form-control` element.

**Comment by cvrebert** [comment]
Duplicate, and indeed already on the v4 docket from #14735.

**Comment by johnnyshields** [comment]
OK, where is the issue on v4 to track this? #14735 looks closed.

**Comment by cvrebert** [comment]
We close v4-related issues and add them to a private to-do list.

**Comment by johnnyshields** [comment]
Cool, thanks.
