### ISSUE TITLE
Modal-over-modal: scroll not working

### ISSUE THREAD

**Issue by nickich** [twbs/bootstrap#16428]
When I create a large modal dialog the scroll works fine. If I create a second modal over the first one, the scroll on the first one doesn't work anymore, even if the second one is closed.

I put a sample app here: 
https://www.dropbox.com/s/oq6er6kzy4xlo41/modaltest.7z?dl=0

**Comment by cvrebert** [comment]
As stated in our documentation, "stacked" modals are explicitly not supported.
