### ISSUE TITLE
Way to change glow and shadows via less variables

### ISSUE THREAD

**Issue by AdamPietrasiak** [twbs/bootstrap#16424]
Is there any way to modify inputs glow and elements like popup shadow via editing less variables?

And connected to that question  - I think as Bootstrap is 'framework' - if you get any UI kit from your designer that have elements that bootstrap have - it should be possible to achieve such look only by editing less variables.

**Comment by cvrebert** [comment]
The blue box-shadow of focused inputs is deliberately not customizable, per @mdo in #517.

**Comment by AdamPietrasiak** [comment]
And why is that? It's obvious that in many cases its not desired. And what about other things like shadows of some elements?

**Comment by mdo** [comment]
Currently not everything has a variable. I think we've got too many variables as it is, so adding more isn't really near the top of our list of todos. The notion that everything should be customized via variables isn't one we share—doing so would be a bit over the top.
