### ISSUE TITLE
Delete and copy paste not working inside popover

### ISSUE THREAD

**Issue by atulloona4** [twbs/bootstrap#16439]
i have a modal(bootstrap) in my application,modal(bootstrap) have a button,on click of button a new popover(bootstrap) open up, on my popup i have a normal html. 

<input  type="text" />
![image](https://cloud.githubusercontent.com/assets/1391976/7515338/c5641eda-f4e3-11e4-8d96-b365ea797b86.png)

Problems is with delete keyboard key and copy paste both are not working, please suggest how this can be fixed i am using v 3.2.0

**Comment by cvrebert** [comment]
1. Please upgrade to v3.3.4.
2. We cannot help you without a [JS Bin](http://jsbin.com) (or similar) live example that demonstrates the problem.

**Comment by rafiqbeepee9094** [comment]
i have a modal(bootstrap) in my application,modal(bootstrap) have a button,on click of button a new popover(bootstrap) open up, on my popup i have a normal html.




Problems is with delete keyboard key and copy paste both are not working, please suggest how this can be fixed i am using v 3.2.0

**Comment by cvrebert** [comment]
Closing due to lack of reply from @atulloona4.

@rafiqbeepee9094 Please see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
