### ISSUE TITLE
There's a bug onto navbar-brand>img

### ISSUE THREAD

**Issue by dnviti** [twbs/bootstrap#16438]
navbar img  is missing the css attribute height:100%

i've corrected on mine and now works.

the line is: 

.navbar-brand > img {
  display: block;
}

That should be:

.navbar-brand > img {
  display: block;
  height:100%;
}

Without height:100% the image is splatted onto the whole screen withour any boundary.

**Comment by patrickhlauke** [comment]
This depends entirely on the size of the image you're using. It appears that, in your particular case, you're adding an image that is essentially larger than what you want to have in the navbar. It would not be appropriate to set this height as a general rule, as it will not universally apply to all users/implementations.

**Comment by bryanwillis** [comment]
Patrick I think it would be a challenge to find a site where the logo was intentionally larger than the navbar. Additionally, I think it's fair to say that the current <a href="http://getbootstrap.com/components/#navbar-brand-image">implementation<a> isn't very "universal" as is. Unless the image height is set to <em>EXACTLY</em> `20px` it will be off center and additionally overflow beyond the navbar if it is too large unless additional changes are made.The demo on the page is using an image that is the designed to be the same height and width, but many if not most sites want to use images of varying sizes and dimensions with in the navbar. 

But if people don't agree that 100% is most often desired, what about using `max-height: 100%;` instead... basically like the reverse version of `.img-responsive`? 

There are literally hundreds of questions on stackoverflow <a href="<a href="http://stackoverflow.com/questions/18474564/bootstrap-3-navbar-with-logo"> like this one </a> on how to get navbar brand images to play nicely with the navbar. This should suggest that the current example in the docs needs to be expanded upon or something like this should be implemented by default.
