### ISSUE TITLE
Menu on hover instead of on click

### ISSUE THREAD

**Issue by rajthilak04** [twbs/bootstrap#16435]
Hi i need menu to on hover instead of on click at the same time need to be clickable functionality in responsive view (small and extra smal screen)

**Comment by thatzacdavis** [comment]
You can easily accomplish this with a bit of javascript.

**Comment by patrickhlauke** [comment]
Please use StackOverflow for personal implementation questions. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
