### ISSUE TITLE
Thoughts on contextual modals?

### ISSUE THREAD

**Issue by mtscout6** [twbs/bootstrap#16431]
I have a pull request react-bootstrap/react-bootstrap#403 which is a request to support contextual modals like `primary`, `danger`, `warning`, `info`, and `default`. That pull request proposed applying `bg-*` and `text-*` classes to the modal-header div. The problem is that the rounded corners are not respected via this approach. Any thoughts on supporting such a feature?

**Comment by mdo** [comment]
We'll pass on implementing those.

**Comment by ambischof** [comment]
Is there any chance bootstrap will ever support contextual modals?

**Comment by mdo** [comment]
Probably not :).

**Comment by mdo** [comment]
Feel free to extend them yourself though and share on GitHub :D.
