### ISSUE TITLE
Tab component is leaking memory

### ISSUE THREAD

**Issue by afinne** [twbs/bootstrap#16434]
For our project, we had to implement the following in the tab component, since it was leaking memory:

    Tab.prototype.destroy = function () {
      this.element = null;
    }

We manually call on this when transitioning away from a page with a Tab.

**Comment by zacechola** [comment]
I'd like to know more about your data showing a memory leak. Forcing a garbage collection in Chrome clears the heap, so I can't reproduce. Would you post a reduced test case we can look at?

![screenshot 2015-05-06 10 49 45](https://cloud.githubusercontent.com/assets/498418/7497080/e94984d6-f3dd-11e4-8521-e06e8544aded.png)

**Comment by afinne** [comment]
Let me give some more background to the issue we are seeing. Our application uses Ember.js, and when transitioning away from a page with a Tab, the page becomes a detached DOM tree, that cannot be garbage collected since the Tab control still holds a reference to the element. Below I'll first show the graph without using the ```destroy``` function I posted above, and then when using it.
![image](https://cloud.githubusercontent.com/assets/7114687/7510092/51731d2e-f4a1-11e4-9786-00b649f6716a.png)
As you can see, the number of nodes does not drop all the way back when garbage collecting. The next image is the same scenario, but with ```destroy``` when exiting.
![image](https://cloud.githubusercontent.com/assets/7114687/7510170/f76b3fcc-f4a1-11e4-8c03-085e7abd2f99.png)
Here, the number of nodes go all the way back down. Since DOM nodes use native memory, and not directly affect the heap, we don't see leaking in the memory graph, but the overall memory usage for the browser process grows.

**Comment by afinne** [comment]
There's now a jsbin at http://jsbin.com/zonuva/8/edit illustrating the issue with the tab control. I include a patched version of bootstrap (the "real" is commented out), and the call to destroy is also commented out. When going back and forth between the main page, and the tabs as in this gif: 
![bootstrap-tabcontrol](https://cloud.githubusercontent.com/assets/7114687/7908224/40144aea-084b-11e5-8eae-962b86a21ffc.gif)
The resulting graph looks like this:
![image](https://cloud.githubusercontent.com/assets/7114687/7908231/5e07d846-084b-11e5-97b9-6e5ead124625.png)
In this case I went twice back and forth, as you can see, the number of nodes grows with every visit. 
If I add back the call to destroy, and do the same navigation, this is the result: 
![image](https://cloud.githubusercontent.com/assets/7114687/7908268/ea24fd40-084b-11e5-9307-1232bb75756a.png)

There are still nodes retained, but there are more that get garbage collected.

**Comment by twbs-lmvtfy** [comment]
Hi @afinne!

You appear to have posted a live example (http://jsbin.com/zonuva/8/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by afinne** [comment]
Update at: http://jsbin.com/zonuva/9/edit

**Comment by fat** [comment]
thanks @afinne that's awesome. We've actually gone ahead and added "teardown" methods in all of our plugins in v4 which do precisely this.

thanks!

**Comment by animafact** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

animafact@naver.com 님께 보내신 메일 <Re: [bootstrap] Tab component is leaking memory (#16434)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by w3hacker** [comment]
+1
