### ISSUE TITLE
\9 three times

### ISSUE THREAD

**Issue by Franck78** [twbs/bootstrap#16440]
Why devs don't look at logs sometimes....

There are three \9 strings.

in css, version 3.3.4

lines 2517, 2646, 6238
eg
input[type="radio"]
input[...
carousel-indicators li

or just use our favorite ctrl-f ;-)

**Comment by patrickhlauke** [comment]
Was there an issue you wanted to report, or... ?

**Comment by patrickhlauke** [comment]
And just in case your issue was an oblique "I think these are typos" reference...see the original less files - for instance, forms.less (note the comment about why `\9` is there)

```
// Position radios and checkboxes better
input[type="radio"],
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9; // IE8-9
  line-height: normal;
}
```

**Comment by Franck78** [comment]
when the css interpretor says it encounters a syntax error and discard the style declaration, well it is a syntax error...
what do you want more ? 
"margin-top: 1px \9;" this is a syntax error, just nonsense.
And line 6238 is a duplicate of 6239.

**Comment by patrickhlauke** [comment]
It's a CSS hack to work around a problem in IE8-9.
