### ISSUE TITLE
grids in IE8 always stack when using non-customized Bootstrap

### ISSUE THREAD

**Issue by cesterline** [twbs/bootstrap#16448]
As of today if you were to download Bootstrap via the 'Download Bootstrap' link on the homepage of http://getbootstrap.com/ your grids in IE8 would stack(fail).  Whereas, if you were to goto http://getbootstrap.com/customize/ and choose the 'Compile and Download' version with all defaults accepted Bootstrap grids, as advertised, work flawlessly in IE8.  Initial issue noticed when testing https://github.com/cesterline/ic-2015 then later verified against Bootstrap provided examples found at http://getbootstrap.com/getting-started/.

**Comment by cvrebert** [comment]
Are you absolutely sure it's due to the CSS and not due to a problem with setting up Respond.js? There are several Respond.js gotchas to be aware of: http://getbootstrap.com/getting-started/#support-ie8-respondjs

**Comment by cesterline** [comment]
Good question: meta content is set to IE=Edge, I'm not using cross-domain CSS, nor am I referencing CSS via @import or calling the page via file://.  In either event, the only thing which changed, in my build, which produced a positive result (grids in IE8 performing as advertised) was making use of the version of bootstrap.css which was generated as a result of the Bootstrap customization script(accepting all defaults).

This issue is easily tested.  DL both versions of v.3.3.4 from the download link here (http://getbootstrap.com/) and here (http://getbootstrap.com/customize/).  Then point unique instances of any of the templates found here (http://getbootstrap.com/getting-started/) which make use of grids.  I believe you will find your results produce stacked(broken) grids in the version of bootstrap.css which is DL'd from the homepage and properly presented grids in the version DL'd from the Customization page.

**Comment by cvrebert** [comment]
Sorry, but I can't reproduce your issue.
Test page: http://run.plnkr.co/plunks/d0TzLqvRfaNB2cKTVNvX/
Screenshot: 
![proof](https://cloud.githubusercontent.com/assets/419884/7544468/2dc69b4e-f582-11e4-877b-d4e6fd431d35.png)

**Comment by cesterline** [comment]
It looks as if my original assumption was incorrect.  I may have missed a step.

Within your test, use <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> in place of the local reference.

My current tests involve a number of freshly downloaded, Bootstrap provided, templates which all point to the hosted(bootstrapcdn) version of bootstrap.css.  All of which, via IE8 running on Win7, cause grids to improperly stack.  If, however, I re-point the same templates towards a freshly downloaded, local, copy of bootstrap.min.css the grids work as advertised.

**Comment by cvrebert** [comment]
So you're running into the "Respond.js and cross-domain CSS" gotcha, which is among those I specifically asked you to check for earlier.

**Comment by cesterline** [comment]
Gotcha.  My original tests regarded the two paths to downloading a local distribution of the Bootstrap framework.  In which case the cross-domain issues which affect the behavior of Respond.js would not have been a factor.  However, in my latest tests, it seems I was remiss of your original concern.  In either case, I appreciate your time and attention.
