### ISSUE TITLE
v3.3.4: Affix plugin has problems handling items with offsetTop = 0

### ISSUE THREAD

**Issue by rafalp** [twbs/bootstrap#16449]
# Background

I have custom navbar in my app. Depending on configuration this navbar is either located at top of page, or its below user set header.

# Issue

If there's element taking height above affixed one, everything works, however if affix element is at top of page, click events will switch it between affix/affix-top.

This is because if affix isn't affixed and its `offsetTop` is 0, following line in getState will change it to 'top':

    if (offsetTop != null && scrollTop <= offsetTop) return 'top'

 Next click event will trigger getState again, this time changing state back off:

    if (offsetTop != null && this.affixed == 'top') return scrollTop < offsetTop ? 'top' : false

# Temporary fix

I have managed to fix this issue, by changing offsetTop to 1 if navbar has no element obove it (and making existing logic work).

# Proposed fix

because offsetTop == 0 is edge case, `getState` may check for it via running following check before all other checks:

    if (offsetTop === 0) return scrollTop === 0 ? 'top' : false

**Comment by davidgraca** [comment]
Thanks for the fix it really helped! :+1:

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
