### ISSUE TITLE
ScrollSpy works only on the body tag?

### ISSUE THREAD

**Issue by shadowii** [twbs/bootstrap#16441]
I've got an example here: http://jsfiddle.net/03sv47av/

As is, scrollspy will set up, but will not react to scrolling. But if you cut all the attributes from the first div and paste them to the body tag and re-run the example, scrollspy works perfectly.  

You'll need to inspect the nav elements with your browser dev tools. When it works, the active classes will be dynamically applied as you scroll. 

I've reread the docs about a zillion times now, and I can't seem to pinpoint where I'm going wrong.

**Comment by twbs-lmvtfy** [comment]
Hi @shadowii!

You appear to have posted a live example (http://fiddle.jshell.net/03sv47av/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 38, column 3 thru line 38, column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 327, column 1 thru line 327, column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by shadowii** [comment]
Maybe I'm blind, but I don't see where the validator is seeing extra body tags, ignoring the presence of iframes.

**Comment by cvrebert** [comment]
JS Fiddle already adds a `<body>` tag for you, so you don't need to include one in the HTML pane of the fiddle. Fiddle without the extra `<body>` tag: http://jsfiddle.net/03sv47av/2/

**Comment by shadowii** [comment]
I see, sorry about that. Fiddle warned me that it would already place an html tag, but was silent when I tried adding a body tag. I'll update the link with yours, thanks.

**Comment by cvrebert** [comment]
You can scrollspy on elements other than `<body>`. There's an example of doing this in the docs, and it works: http://getbootstrap.com/javascript/#scrollspy-examples
Here's another one using pills instead of a navbar: http://jsfiddle.net/6normhda/
For personal troubleshooting help, please use StackOverflow; see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by shadowii** [comment]
Eh, I think the documentation needs to be updated then. As currently written, it seems to imply "natural" divs will work if you follow the steps given. In the examples you've given, a height and overflow need to be specified. If you remove them, or set height to 100%, ScrollSpy stops working as per my example.

E.g.: Remove height and overflow. Make browser window smaller to allow for scrolling.

http://jsfiddle.net/6normhda/1/

**Comment by josemariap** [comment]
sdf

**Comment by elinake** [comment]
You should also add that scrollspy needs to be added to div that wraps only the sections and not the nav, unlike the body which wraps both sections and nav.
