### ISSUE TITLE
Include license to bootstrap.less

### ISSUE THREAD

**Issue by andrenarchy** [twbs/bootstrap#16447]
The MIT license header currently only is added to `dist/css/bootstrap.css`. If `less/bootstrap.less` is directly used (with the less compiler), no license statement ends up in the generated file. I propose to also add the MIT license header to `less/bootstrap.less`.

**Comment by cvrebert** [comment]
:+1:

**Comment by kkirsche** [comment]
Pull request submitted for this.

**Comment by andrenarchy** [comment]
Thx!
