### ISSUE TITLE
Tooltips not getting removed from dom when multiple containers exist

### ISSUE THREAD

**Issue by begizi** [twbs/bootstrap#16443]
Tooltips have the unexpected behavior of duplicating the tooltip dom in all of the matched `containers`, but only removing from the last matched container on the page.

Issue only occurs when the `container` option is specified as a selector that matches multiple dom elements.

Fiddle https://jsfiddle.net/begizi/L23rmymj/2/
Browser Chrome Version 42.0.2311.135 (64-bit)
Mac OSX 10.10.3

**Comment by cvrebert** [comment]
> Issue only occurs when the `container` option is specified as a selector that matches multiple dom elements.

I would be inclined to deem that to be a bug in the caller's code. Would be nice if we threw a clear error in such cases though.
@fat Another thing to add to the options validity checking in v4?

**Comment by fat** [comment]
yeah, we could be smarter about using query's equivalent of "querySelector" vs "queryselectorall" – but ultimately i think the best recommendation for now is it's better to recommend people provide unique container selectors

**Comment by animafact** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

animafact@naver.com 님께 보내신 메일 <Re: [bootstrap] Tooltips not getting removed from dom when multiple containers exist (#16443)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
