### ISSUE TITLE
panel + invisible list-group + panel-footer

### ISSUE THREAD

**Issue by Jarogniew** [twbs/bootstrap#16446]
Hidden list-group (display:none) within panel with panel-footer removes border-top from footer. Simple example:

```html
<div class="panel panel-default">
<div class="panel-body">Lorem Ipsum</div>
<ul class="list-group" style="display:none;"></ul>
<div class="panel-footer">Lorem Ipsum</div>
</div>
```

**Comment by cvrebert** [comment]
I doubt that this is fixable. It's simply not possible to style things in CSS based on the displayedness of elements.
CC: @mdo

**Comment by mdo** [comment]
Yeah not something we can account for reliably. You'll need to handle that I think. Open to suggestions though if you've got some ideas.
