### ISSUE TITLE
.dropdownmenu > .disabled > a should have pointer-events: none?

### ISSUE THREAD

**Issue by dankahle** [twbs/bootstrap#16456]
pointer-events: none works nicely for:

.btn.disabled, 
.btn[disabled], 
fieldset[disabled] .btn  { }

Was wondering why ".dropdownmenu > .disabled > a" only changed color and didn't defeat the pointer-events? Is this an over-sight?

**Comment by dankahle** [comment]
Looks like the "cursor: not-allowed" doesn't work if you do "pointer-events: none", i.e. the cursor won't change, I suppose that was the limiting factor. I'm running into that right now with the tabs, i.e. they're changing even though I've set li.disabled. If I add the pointer-events:none, then the tab doesn't change, but the cursor stops changing to not-allowed. I assume that's what you guys are trying to avoid. If so, just disregard this issue.

**Comment by sebcl** [comment]
How about puting the cursor attribute to the container and the pointer-events on the actual a?

**Comment by dankahle** [comment]
That works, just move the "cursor: not-allowed" up to the <li> tag. We'd
have to enumerate all the places this is affects. Dropdown menus, tabs,
anywhere we have an li.disabled > a. This still affords them to tab over
and click on them by hitting the enter key. All associated examples should
use "tabindex=-1" on the anchors then, like the dropdown menu does, i.e.
component>>nave>>tabs and javascript>>tab sections don't.

I wonder what the implication of tabindex=-1 is for accessibility, i.e. how
do blind people click if you take the keyboard option away from them? If we
need to have these navs be tabbable (tabindex can't be -1), then it's all a
moot point, we'll still have to use javascript to shut it down.

**Comment by dankahle** [comment]
The li with cursor: not-allowed and <a> with pointer-events:none trick doesn't work on pagination for some reason. Not sure why, just that it doesn't.

**Comment by dankahle** [comment]
It has something to do with .pagination > li is display:inline, i.e. when display: inline-block, it works.

**Comment by dankahle** [comment]
To make it work for pagination (the first example in the examples), need something like the following. For some reason the float:left was placed on the <li> <a> instead of the <li>. 

.pagination > li {
  display: inline-block;
  float:left;
}

.pagination > li.disabled
{
  &:hover {
    cursor: not-allowed;
  }
  > a {
    pointer-events: none;
  }
}

**Comment by kkirsche** [comment]
Could you post a JSBin of your problem please @dankahle?

**Comment by dankahle** [comment]
http://jsbin.com/baripo/4/edit?html,output

when you click on the "disabled" anchor, you will go to that location. Jsbin won't let you, and it locks up in a weird way. Outside of jsbin, you'll go to the href in that anchor tag, the cursor: not-allowed not stopping you. pointer-events: none would, but then the cursor doesn't show up. If you move the cursor:not-allowed up to the <li>, then all works again. But this problem is all over the place, say in pagination, and it isn't so easily fixed there as I explain above. I'm willing to let it all go, as it seems quite the undertaking. The links can still be enabled via keyboard as well, so would have to put tabindex=-1 on all of them, but not sure that's acceptable for accessibility reasons.

**Comment by twbs-lmvtfy** [comment]
Hi @dankahle!

You appear to have posted a live example (http://jsbin.com/baripo/4/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 19, column 1 thru line 19, column 70: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dankahle** [comment]
fixed

**Comment by twbs-lmvtfy** [comment]
Hi @dankahle!

You appear to have posted a live example (http://jsbin.com/baripo/4/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dankahle** [comment]
fixed

**Comment by dankahle** [comment]
Add listgroups to the list. The anchors in listgroups don't have ecompassing <li>s so that trick won't work. I'd say let's just drop this one, it's too big, and in reality, pointer-events:none is probably not well enough supported anyway. All the examples would have to use <a tabindex="-1"> as well as otherwise it wouldn't make sense to shut down mouse but not keyboard. Seems too big an undertaking, but something to consider down the road. I'd label this more a feature. Still... what got me started on this? Buttons. Buttons "do" use pointer-events:none as stated in my first comment (above). That's what got me going, as it was working swimmingly on buttons, why not on dropdown buttons/pagination/listgroups/etc? Still seems a big undertaking.

**Comment by mdo** [comment]
Whenever you use a class to do something to a link, you'll most likely need JS to prevent clicks on that element. `pointer-events` can help, but it's browser support is rather limited. Account for it in JS instead.

**Comment by kkirsche** [comment]
Noted. Thank you for the heads up
