### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by hooman-pro** [twbs/bootstrap#16454]
when i was in getbootstap.com or any site use bootstap with my laptop, i saw desktop version, but when i zoom my browser,i saw tablet and next mobile version.
it is not better to only break point deepend on browser or divice width??

**Comment by patrickhlauke** [comment]
this is how responsive design works. when zooming, browsers actually change their css pixel width, so the relevant media queries kick in.

**Comment by hooman-pro** [comment]
thanks for your answer.
