### ISSUE TITLE
add "back to top" button to docs

### ISSUE THREAD

**Issue by sevdimali** [twbs/bootstrap#16453]
I think we have to add "back to top" button to http://getbootstrap.com/ site.

**Comment by zacechola** [comment]
There is a link on the right hand side.

**Comment by patrickhlauke** [comment]
@zacechola which, admittedly, disappears in browser widths below 993px though...

**Comment by cvrebert** [comment]
Well, on mobile you can just tap above the address bar to return to the top.

**Comment by sevdimali** [comment]
will we replace text with image or change text color, font size... then it is easy to see. Now it is hard to see this little text.

**Comment by mdo** [comment]
It's not the best, but hitting the home button or Cmd+Up (on Mac) and what not are all options, too. Not something super important for us to solve I think, though I do admit we could use higher contrast on those links. That's a separate issue though, so closing this out.
