### ISSUE TITLE
Can't download/modify bootstrap template

### ISSUE THREAD

**Issue by MarkBond91** [twbs/bootstrap#16461]
Hello my name is Mark and I am very new to bootstrap. I want to download and experiment with one of the bootstrap templates on the http://getbootstrap.com/getting-started/ page but I can only seem to view a live demo on a web browser and can't actual download and modify it. It says that you are able to do just that in a statement where the template is located and I'm just assuming I'm just not understanding what I have to do. So if someone could help this noob out so I can start messing around with bootstrap I would appreciate it.
Thank-you

**Comment by StevenBlack** [comment]
If you download Bootstrap source, you can find these examples in `docs/examples/` folder.

**Comment by jorgefelico** [comment]
Hi Mark,
The way that StevenBlack described it works, but you can also right click on the thumbnail of the example you wish to use and hit "Save Link As..." This will allow you to make a copy of that same exact example on your computer, from which you can then make your changes.
![show](https://cloud.githubusercontent.com/assets/4616355/7596492/0c1afe3a-f8bc-11e4-87c8-116698045b38.jpg)

**Comment by cvrebert** [comment]
Please ask newbie questions on [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3) instead of this issue tracker. Thanks!

**Comment by mdo** [comment]
It's a valid concern though, and one we'll address in v4 hopefully with more isolated and downloadable example files. Unsure how best to approach that yet, but until then you'll want to download the entire Bootstrap project and pull those files from there.
