### ISSUE TITLE
IE8 clearfix issue in jumbotron and panel

### ISSUE THREAD

**Issue by shiznit013** [twbs/bootstrap#16468]
In IE8, if you use a jumbotron or panel with columns inside, the clearfix does not grow the jumbotron or panel to vertically wrap the floated columns.

![logon](https://cloud.githubusercontent.com/assets/2589695/7616389/fa94a24a-f971-11e4-8827-29c96bde85bf.png)

```html
<div class="container">
    <div class="jumbotron">        
        <div class="row">
            <div class="col-sm-8">
                <h1>Sign In</h1>
                <form>
                    <div class="form-group">
                        <label for="userName">User Name</label>
                        <input id="userName" type="text" class="form-control" placeholder="Enter username" />
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input id="password" type="text" class="form-control" placeholder="Enter password" />
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" /> Remeber Me
                        </label>
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                </form>                
            </div>
            <div class="col-sm-4">
                <img src="http://placehold.it/200x300" class="center-block" />
            </div>
        </div>
    </div>
</div>
```

**Comment by mdo** [comment]
Works for me at https://jsbin.com/hukaqis/1/.

**Comment by twbs-lmvtfy** [comment]
Hi @mdo!

You appear to have posted a live example (https://jsbin.com/hukaqis/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by shiznit013** [comment]
When I run your example in IE8, I do see a different output, but it looks like the 2nd column is wrapped below. I thought it might be a responsiveness issue, but including respond.js didn't seem to fix it.

![image](https://cloud.githubusercontent.com/assets/2589695/7616903/e9850306-f975-11e4-9db1-99798cbdeccf.png)

**Comment by mdo** [comment]
Make sure it gets included in the right place—order matters for that JS.

**Comment by shiznit013** [comment]
I'm including it after the stylesheet.

**Comment by cvrebert** [comment]
Are you using CDNs for any of the scripts or CSS? Try not using CDNs; see http://getbootstrap.com/getting-started/#respond-js-x-domain

**Comment by shiznit013** [comment]
We don't use CDNs in our project, all scripts are local. I just grabbed the example from the Bootstrap Getting started section for this jsbin.

**Comment by shiznit013** [comment]
I think I'm following you... there's no way to make the example work in jsbin?

**Comment by cvrebert** [comment]
Here's a Plunk that ought to work: http://plnkr.co/edit/EE9FvG?p=info

**Comment by cvrebert** [comment]
Yup, works fine in IE8:
![0002screenshot](https://cloud.githubusercontent.com/assets/419884/7618554/a03668b0-f967-11e4-9572-13e25bb9cf43.png)

**Comment by shiznit013** [comment]
Thank you, you've helped me rule out Bootstrap. We import Bootstrap into our own LESS file, modify some things and compile it.  One of our selectors was using `:not(.clazz)`, which IE8 doesn't support.  Inside that selector we use `.make-row();` which extends `.clearfix`.  This ended up invalidating the entire `.clearfix` selector.
