### ISSUE TITLE
Pagination-sm forget @line-height-small

### ISSUE THREAD

**Issue by Jacquelin** [twbs/bootstrap#16460]
Hello

The height of pagination elements is not consistent with btn-sm (29px for pagination, 30px for btn, see attach image).

pagination-sm forget '@line-height-small' !

buttons.less:133
```
.button-size(@padding-small-vertical; @padding-small-horizontal; @font-size-small; @line-height-small; @border-radius-small);
```

pagination.less:87
```
.pagination-size(@padding-small-vertical; @padding-small-horizontal; @font-size-small; @border-radius-small);
```
![btn-sm](https://cloud.githubusercontent.com/assets/4801131/7591872/7d3898de-f8d0-11e4-8852-5563148ebb00.png)
![pagination-sm](https://cloud.githubusercontent.com/assets/4801131/7591871/7d37c440-f8d0-11e4-814d-6468dee8b84a.png)

**Comment by kkirsche** [comment]
Pull request submitted. Thanks for the fix @Jacquelin :smiley:

**Comment by Jacquelin** [comment]
Thanks to you :)

**Comment by Jacquelin** [comment]
Hi @kkirsche 

Your pull was reject because of error while build. I forget this : 
You need to update .pagination-size function in mixins/pagination.less
```
.pagination-size(@padding-vertical; @padding-horizontal; @font-size; @border-radius) {
```
to 
```
.pagination-size(@padding-vertical; @padding-horizontal; @font-size; @line-height; @border-radius) {
```

and add line-height property on span 
```
    > span {
      padding: @padding-vertical @padding-horizontal;
      font-size: @font-size;
    }
```
to
```
    > span {
      padding: @padding-vertical @padding-horizontal;
      font-size: @font-size;
      line-height: @line-height;
    }
```

Sorry I can't make the pull request myself ...

**Comment by kkirsche** [comment]
@Jacquelin thanks, and no worries. One other thing is the pagination line height has to be included as well for `.pagination-lg` for consistency. When I put it together I just wasn't thinking and didn't pull / test local first. That should be all fixed now. Sorry about that.
