### ISSUE TITLE
Getting weird customizer output

### ISSUE THREAD

**Issue by Industrial** [twbs/bootstrap#16465]
Hi.

I've edited some vars at http://getbootstrap.com/customize/?id=292f34f3447b27068df8 and what is exported contains things like `margin-bottom: 192px;`. It (the 192px) seems to have nothing to do with the values that I customized. What's wrong?

**Comment by mdo** [comment]
Have you customized the line-height variable?

**Comment by Industrial** [comment]
Ah, yes. That was the problem. It was set at 16, so that's fixed now. Thanks!
