### ISSUE TITLE
Rails and Tab pages resizing my output

### ISSUE THREAD

**Issue by Maverick494** [twbs/bootstrap#16467]
I am using chartkick to generate some graphs.  When I pair it with tabs the second two tabs resize the chartkick graphs and make them unusable.

```
<div>
  <ul class="nav nav-tabs responsive" id="myTab">
        <li id="10" class="active"><a data-toggle="tab" href="#I">Need By Monthly Breakout</a></li>
        <li id="11"><a data-toggle="tab" href="#J">Model Quantities Breakout</a></li>
        <li id="12"><a data-toggle="tab" href="#K">Monthly Quantities Breakout</a></li>
  </ul>
</div>
<div class="tab-content responsive">
  <div class="tab-pane fade in active" id="I">
    <%= render partial: 'orderschart_a' %>
  </div>  
  <div class="tab-pane fade in" id="J">
    <%= render partial: 'orderschart_b' %>
  </div>
  <div class="tab-pane fade in" id="K">
    <%= render partial: 'orderschart_c' %>
  </div>
</div>
```
![normal chartkick](https://cloud.githubusercontent.com/assets/12422275/7616180/66c069ce-f957-11e4-98e1-031d392b0e0b.PNG)

This is the output of the first tab and it looks normal.
![chartkick issue](https://cloud.githubusercontent.com/assets/12422275/7616195/912273d8-f957-11e4-8217-6f31ccb53bcb.PNG)

This is the output of the second tab, you can see it has condensed the graph for some reason.

![chartkick issue 2](https://cloud.githubusercontent.com/assets/12422275/7616188/768ec0c6-f957-11e4-8633-997ed31218af.PNG)

This is the output of the third tab, you can see it has condensed the graph for some reason.

As you can see this is very inconvenient when trying to do dashboards, but I can't see to figure out how to fix it.  I have tested the second and third graphs independent of the tabs page and they work fine when not part of the tabs.

Any help??

**Comment by patrickhlauke** [comment]
Sorry, but the issue tracker is not for personal support request. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
