### ISSUE TITLE
Include documentation callout classes in official build

### ISSUE THREAD

**Issue by stephenkalnoske** [twbs/bootstrap#16466]
The callout classes (bs-callout) used in the getbootstrap documentation are really attractive and would be useful to have. While it's not hard to find sources that have recreated them, it would be good to have it officially a part of Boostrap.

**Comment by mdo** [comment]
Those are just for our docs and we won't be sharing them in the framework itself.

**Comment by cvrebert** [comment]
Duplicate of #9938.
