### ISSUE TITLE
New kind of variables for printing in css only what you need

### ISSUE THREAD

**Issue by LoicGoyet** [twbs/bootstrap#16478]
I do an issue before making a pr in order to know what you think about it and being sure to not working on a bad idea.

So !
The idea is to enjoy an customized bootstrap as we all can build on http://getbootstrap.com/customize/, but without using the doc's tool. The goal is to be more usefull for guys using bower. Could be usefull also when you're in core coding and your customized version is missing a component.

Into the code, the idea is to create of less/sass variables for each common css/components/javascript component, that I call triggers. Thoses triggers are booleans and on true it css print the wanted components, with "Guarded Namespaces" less feature & @if less directive.

Result  Scalable customized front-end developpers friendly !

Let me know what you think of it and I'll make it if you like it

**Comment by mdo** [comment]
Thanks for asking first :). We can't do it for v3 right now, but we're talking about something like that perhaps for v4. It's a big change to how things are built though, thus waiting for v4.
