### ISSUE TITLE
License of code files in the docs, esp. "ie10-viewport-bug-workaround.js"

### ISSUE THREAD

**Issue by lxg** [twbs/bootstrap#16470]
I understand that the docs are licensed under CC-BY 3.0. However, this is unfortunate for the code portions of the docs.

Especially the file [ie10-viewport-bug-workaround.js](https://github.com/twbs/bootstrap/blob/master/docs/assets/js/ie10-viewport-bug-workaround.js) should IMHO be relicensed to MIT, as it is useful/necessary to handle the edge case of IE 10 on Win 8.

The code snippet in the file is also embedded in the docs without any licence statement. Of course, as it is part of the docs there, it would be subject to the CC-BY license, too. But, extending this logic, you would force all example code snippets to adapt the CC license, which would be absurd.

So, maybe it would make sense to put the example code from the docs under the MIT license.

Disclaimer: IANAL.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Woof, that's a doozy. Maybe @caniszczyk can weigh in. I'd love to simplify to one license.

However, relicensing the docs would be a pretty big undertaking I think. We'd need contact every contributor and ask their permission like we do with the move to MIT in v3. And we had @juthilo's help for that, too :).

**Comment by cvrebert** [comment]
In the particular case of `ie10-viewport-bug-workaround.js`, it should be feasible since only me and @XhmikosR have touched that code.

**Comment by lxg** [comment]
@mdo: I think that, for now, would be sufficient to relicense `ie10-viewport-bug-workaround.js`.

In the long run, I don't think that the entire documentation has to be relicensed, only certain code parts … code snippets and [example templates](http://getbootstrap.com/getting-started/#examples). If these are used as starting points by developers, the resulting code will be subject to CC-BY. Or will it? For non-lawyers such as myself it's difficult to understand the implications of reusing CC-BY'd code, especially of merging it with other code.

**Comment by XhmikosR** [comment]
Fine by me too.

I'd prefer one license for myself but for docs it make sense to use CC...

**Comment by mdo** [comment]
Cool, let's get that file at least changed then, and we can address the other parts.

All the code snippets are largely part of what Bootstrap provides in it's MIT-licensed code—our HTML, CSS, and JS. Based on that, perhaps we could just add a FAQ or two to the license page clarifying this?
