### ISSUE TITLE
Open panel on load with URL

### ISSUE THREAD

**Issue by trosenthaltaconic** [twbs/bootstrap#16476]
Is there a way to get a panel (accordion) to open on page load with a specific URL? Similar to a anchor URL, I'd like to have a URL that opens a specific accordion. Anyway to do this?

This is the page http://www.taconic.com/find-your-model/neuroscience-portfolio.

**Comment by swjawa** [comment]
Yes, I think you can do this in JQuery for exemple by getting url and adding the class "in" to your chosen "<div class="panel-collapse collapse" id="yourId">"
("yourId" is "collapseOne", "collapseTwo" etc... in your case)

**Comment by patrickhlauke** [comment]
Please direct support requests of this kind to StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
