### ISSUE TITLE
collapsible navbar doesn't work on iPhone 6 iOS 8.3 Safari

### ISSUE THREAD

**Issue by lili21** [twbs/bootstrap#16497]
http://jsbin.com/jeletuxufe/1/edit

no error message.don't know why.

**Comment by twbs-lmvtfy** [comment]
Hi @lili21!

You appear to have posted a live example (http://jsbin.com/jeletuxufe/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* line 14, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`
* line 7, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.1.1
* line 9, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.1.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by lili21** [comment]
http://jsbin.com/muwaguxoju/1/edit?html,output

already fixed the problems.

still not working.

**Comment by kkirsche** [comment]
What behavior are you experiencing? On my iPhone 5S with iOS 8.3 the navbar collapsed and expanded as expected.

**Comment by kkirsche** [comment]
Using the iOS Simulator in iPhone 6 iOS 8.3 mode (not as great as a real iPhone 6 of course) I wasn't able to duplicate the error.

**Comment by cvrebert** [comment]
Ditto with all of what @kkirsche said. Closing as not reproducible.

**Comment by lili21** [comment]
@kkirsche
Could you visit  [http://whereyogi.com/?c=TOP50](http://whereyogi.com/?c=TOP50) by iOS Simulator?
and you could read the source code from safari.
I really don't know what's the problem.

**Comment by cvrebert** [comment]
@lili21 Your navbar has no `navbar-toggle` button (see [the examples](http://getbootstrap.com/components/#navbar)) and suffers from several other problems reported by [Bootlint](https://github.com/twbs/bootlint#in-the-browser)

**Comment by patrickhlauke** [comment]
And as this is a problem specific to how you're using Bootstrap, rather than a problem with Bootstrap itself, please direct further requests for support in this matter to StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by Hirbod** [comment]
I have the same problem. On the simulator and some other iOS 8.3 (iphone 6) everything is working fine, but not on my iPhone 6. Could this be jailbreak-related? Yesterday everything worked well..

**Comment by patrickhlauke** [comment]
Hirbod...as mentioned above, this is not a Bootstrap problem. Refer to StackOverflow or similar.
