### ISSUE TITLE
Less Sourcemaps Path (sourceMapRootpath)

### ISSUE THREAD

**Issue by Findus23** [twbs/bootstrap#16495]
*Disclaimer: This is the first time I am using Less and Grunt, so there may be an mistake in my reasoning.*

I wanted to use the CSS Sourcemaps in Chromium 42.0. I copied all files from the repository. Then I downloaded the Theme Template to the root folder and changed the paths to the local paths:
```html
<!-- Bootstrap core CSS -->
<link href="dist/css/bootstrap.css" rel="stylesheet">
<!-- Bootstrap theme -->
<link href="dist/css/bootstrap-theme.css" rel="stylesheet">
...
<script src="dist/js/bootstrap.js"></script>
```
But Chromium wasn't able to detect the less files. In my opinion this is because the paths in the *bootstrap-theme.css.map* point to */dist/css/less/theme.less*, which of course isn't there.
```json
{"version":3,"sources":["bootstrap-theme.css","less/theme.less","less/mixins/vendor-prefixes.less", ...
```
I fixed this by adding *sourceMapRootpath* to the Gruntfile.js

```js
      compileTheme: {
        options: {
          strictMath: true,
          sourceMap: true,
          outputSourceFiles: true,
          sourceMapURL: '<%= pkg.name %>-theme.css.map',
          sourceMapFilename: 'dist/css/<%= pkg.name %>-theme.css.map',
          sourceMapRootpath: '../../'
        },
        src: 'less/theme.less',
        dest: 'dist/css/<%= pkg.name %>-theme.css'
      }
```
As a result the sourcemaps point to */less/theme.less* and everything works.
```json
{"version":3,"sources":["../../less/theme.less","bootstrap-theme.css","../../less/mixins/vendor-prefixes.less",...
```
Now my question is: Is this an mistake in the original Gruntfile.js (I don't think so) or am I doing it wrong?

**Comment by cvrebert** [comment]
> Chromium wasn't able to detect the less files.

How did you determine this?

Since we're using `outputSourceFiles: true`, the presence (much less the location) of the Less files should be irrelevant.

**Comment by Findus23** [comment]
>How did you determine this?

When I switch back to the original file, Chromium just shows the css-line
![bildschirmfoto vom 2015-05-16 21 14 07](https://cloud.githubusercontent.com/assets/6266037/7667658/bb137816-fc10-11e4-83e0-97e860a0a22e.png)
The .map-file loads ...
![bildschirmfoto vom 2015-05-16 21 13 32](https://cloud.githubusercontent.com/assets/6266037/7667659/bb17fd3c-fc10-11e4-8c2e-ca13d867ea55.png)
... and the network is maped. 
![bildschirmfoto vom 2015-05-16 21 12 01](https://cloud.githubusercontent.com/assets/6266037/7667660/bb1e72ac-fc10-11e4-9f4c-58e93c44a52f.png)

Even stranger Firefox (aurora 40.0a2) shows the css-line for a fraction of a second, but then switches to *null*.
![bildschirmfoto vom 2015-05-16 21 19 29](https://cloud.githubusercontent.com/assets/6266037/7667671/430e0646-fc11-11e4-805f-009d963caf90.png)

Iceweasel 31.6.0 simply ignores the .map-file.

**Comment by cvrebert** [comment]
Plunk: http://plnkr.co/edit/tenTu3PdeVmJKBNbDzMO?p=preview

Works fine for me in Chrome 42.0.2311.152:
![plunk](https://cloud.githubusercontent.com/assets/419884/7669152/b04c6788-fc17-11e4-8e23-5461a493b6ab.png)
![plunk2](https://cloud.githubusercontent.com/assets/419884/7669158/f986c3f8-fc17-11e4-9349-614b89d5dd17.png)

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://run.plnkr.co/plunks/tenTu3PdeVmJKBNbDzMO/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 10, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Findus23** [comment]
Sorry, but I get a 408 error on your page:
```json
{
  "statusCode": 408,
  "error": "Request Time-out"
}
```
But I think I have found my mistake: I have mapped the *bootstrap-theme.css* to my local *bootstrap-theme.css*. But when I map the less-files (generated by the .map) with my local less files everything works.
