### ISSUE TITLE
Modal shows behind modal-bakdrop layer on 3.3.4

### ISSUE THREAD

**Issue by abaciocco** [twbs/bootstrap#16491]
Tested this behavoir on Firefox 31.7.0 and Chrome 42.0.2311.152 m

when click modal link Modal on show appear behind modal-bakdrop so i can't use it.

<span id="com_act_1" data-id="1" class="com-act btn btn-success btn-sm" title="Agregar contenido asociado" data-toggle="modal" data-target="#modal-con"><i class="fa fa-tasks fa-fw"></i></span>

<div class="modal fade" id="modal-con" tabindex="-7" role="dialog" aria-labelledby="Modal Contenidos" aria-hidden="true">
![modal](https://cloud.githubusercontent.com/assets/5117610/7654293/6d9af15a-faf2-11e4-87dc-dab679f7a746.jpg)

**Comment by kkirsche** [comment]
@abaciocco Could you please post a simplified JSBin demonstrating your problem as well the version of bootstrap which you are using?

**Comment by abaciocco** [comment]
Dear Kevin:
  I set uop a JSBIN and it work, so it means another library is messing up my work. thank you so much for your fast answer and attention.

best regards!

http://jsbin.com/gecaxa/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @abaciocco!

You appear to have posted a live example (http://jsbin.com/gecaxa/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 17, column 1 thru line 17, column 121: The ```` aria-labelledby ```` attribute must point to an element in the same document.
* line 17, column 1 thru line 17, column 121: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
You are mixing different versions of Bootstrap's CSS and JS, which is not advisable nor guaranteed to work properly.

**Comment by abaciocco** [comment]
My mistake! bad copy-paste! i'm am updating my code from 3.3.2 to 3.3.4, and this behavoir appear using full 3.3.4, but not using 3.3.2. thank for your answer!
