### ISSUE TITLE
Modal scrollbar handling problem when implementing stacked modals

### ISSUE THREAD

**Issue by cervengoc** [twbs/bootstrap#16502]
Stacked modals can be easily implemented with a few lines of custom code for z-indexes and so (as mentioned in the docs).

However, there is a usability issue in the core code. Consider the following:

1. Body is overflowing vertically.
2. A first modal is shown, so scrollbar disappears, and some padding is applied to the body.
3. A second modal is shown, and paddig is applied again, for no reason.

This could be easily fixed if there was a piece of code and maybe a global helper variable to check if a modal is already open or something like that.

**Comment by cervengoc** [comment]
A proposed solution would be to add a counter to body which indicates how many times the scroll padding was added. There is probably a nicer way but this came out of my head right now, and thought I would share it (I don't have GIT set up to create pull requests).

```
Modal.prototype.setScrollbar = function () {
    var counter = this.$body.data('bs.bodyScrollPaddingApplied')
    if (this.bodyIsOverflowing && !counter) {
      var bodyPad = parseInt((this.$body.css('padding-right') || 0), 10)
      this.originalBodyPad = document.body.style.paddingRight || ''
      this.$body.css('padding-right', bodyPad + this.scrollbarWidth)
    }
    this.$body.data('bs.bodyScrollPaddingApplied', (counter || 0) + 1)
  }

  Modal.prototype.resetScrollbar = function () {
    var counter = this.$body.data('bs.bodyScrollPaddingApplied')
    if (counter === 1)
      this.$body.css('padding-right', this.originalBodyPad)
    if (counter)
      this.$body.data('bs.bodyScrollPaddingApplied', counter - 1)
  }
```

**Comment by kkirsche** [comment]
Stacked modals, if I understand it correctly to mean multiple modals open simultaneously, are not supported in V3 and as V4 is nearing alpha I don't forsee any changes to the modal implementation like this in V3. 

<blockquote><h3>Overlapping modals not supported</h3>
<p>Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.</p></blockquote>

Thanks for the suggestion though

**Comment by cervengoc** [comment]
It was completely clear that it's not supported. In the docs there are those few words which state that it "requires custom code". I wrote that custom code as precisely as I could using show, shown eventhandlers and manipulating z-indexes, etc. I just wanted to point out that there exists this limitation in the core code, which prevents implementing multiple open modals even with custom code.

I know I could set back the padding in the shown event, but that's quite an ugly hack which I wanted to avoid. 

Anyway it seems to be possible to override this two methods from outside of bootstrap via $.fn.modal.Constructor.protorype, because in bootstrap.js the internal Modal type is assigned to it (correct me if I'm wrong).

**Comment by kkirsche** [comment]
Ah, sorry. I misunderstood the original post :smiley: Thanks for clarifying that :+1:

**Comment by cvrebert** [comment]
Yeah, you may need to override parts of the existing Modal JS when implementing stacking; reassigning methods on the prototype like you mentioned is one viable way to do that.
We won't be making any changes to the vanilla Bootstrap v3 Modal JS related to stacking; override methods as necessary yourself.
