### ISSUE TITLE
Tooltip should convert linebreaks to html linebreaks

### ISSUE THREAD

**Issue by kaystrobach** [twbs/bootstrap#16509]
* linebreaks should convert ```\n``` to ```<br>``` in the tooltip bubble
* see http://stackoverflow.com/questions/358874/how-can-i-use-a-carriage-return-in-a-html-tooltip

**Comment by kkirsche** [comment]
My concern is: would such a fundamental change this late into V3 cause issues for people who have already deployed solutions? I'm concerned that this might be more than a minor rev change and instead may need to go into V4. Core team will have to say though for sure one way or the other.

**Comment by ZDroid** [comment]
@kkirsche :+1:

**Comment by mdo** [comment]
Punting on new features to v3. We can revisit when the v4 alpha comes out.
