### ISSUE TITLE
Modal scrollbar handling issues in latest code

### ISSUE THREAD

**Issue by cervengoc** [twbs/bootstrap#16501]
In a pull request from @hnrch02 I noticed that body overflowing is checked using the widths instead of the heights, which seems to be wrong. When I've tested in Chrome, the scrollbars were never hidden because I had vertical overflowing (as expected in most cases).

The commit was this: https://github.com/twbs/bootstrap/commit/16479e9051614696df3d21acd9d482018da17045

**Comment by kkirsche** [comment]
@cervengoc could you post a JSBin which demonstrates this issue?

Also if this is a dynamic height modal (where height changes after loading), please refer to:
<blockquote>
<h4><code>.modal('handleUpdate')</code></h4>

<p>Re-adjusts the modal's positioning to counter a scrollbar in case one should appear, which would make the modal jump to the left.</p>

<p>Only needed when the height of the modal changes while it is open.</p>

Copy
$('#myModal').modal('handleUpdate')
</blockquote>

**Comment by cervengoc** [comment]
@kkirsche I'll put together a fiddle when I have time. Until then please check the source code. If it is an issue at all, it seems to be quite visible by a quick code review.

**Comment by cvrebert** [comment]
CC: @hnrch02

**Comment by cervengoc** [comment]
@hnrch02 Any news on this? Could you please give a short explanation about wether this is an issue or not, and why? I'm still using my function override to "fix" this on my side.

**Comment by hnrch02** [comment]
@cervengoc Could you explain where this is an issue for you with a fiddle? This was changed because of #15353. It's checking the width to detected a possible scrollbar since just checking the height was not sufficient in IE10/11.

**Comment by cervengoc** [comment]
@hnrch02 Ah I see now, it seems like I misunderstood the code that time, or maybe it was a different version than the current (3.3.6), don't have time to check it now. Thank you for the clarification, I'm closing this.
