### ISSUE TITLE
Popover arrow shadow

### ISSUE THREAD

**Issue by mbrevda** [twbs/bootstrap#16507]
Popovers have a nice dropshadow to them, but their arrow doesn't. Would there be any way to add a shadow to the arrow, too?

![screen shot 2015-05-19 at 8 09 06 am](https://cloud.githubusercontent.com/assets/293004/7695863/8cb14292-fdfe-11e4-86fb-77a637c66a9b.png)

Thanks!

**Comment by mdo** [comment]
Not really doable the way it's marked up right now and given how `box-shadow`s work.

**Comment by mbrevda** [comment]
I guess the suggestion here is to change the markup? Perhaps using a rotated div would work?

**Comment by mdo** [comment]
Can't change the markup or approach really—it'd likely break backward compatibility.

**Comment by mbrevda** [comment]
:+1: , reluctantly. I hope there is some way to address this in the future. Thanks!

**Comment by roberkules** [comment]
now that v4 is here, any chance it will be supported in the future?
(from playing around with the .arrow (before/after) styles I'm not getting my hopes up.)
