### ISSUE TITLE
How to IE6 compatibility for bootstrap3

### ISSUE THREAD

**Issue by priyusinha** [twbs/bootstrap#16511]

**Comment by patrickhlauke** [comment]
Bootstrap 3 does not support IE6. You'll either need to use an older version of Bootstrap, or unfortunately you'll have to put in the work yourself to ensure it works in IE6.

**Comment by nextgenthemes** [comment]
Oh common its 2015 - IE 6 are you fucking kidding? Its irresponsible to use it or to participate in anything that encourages further use of this disaster of a browser, you should do the exact opposite, encourage people to use a modern browser! BS 4.0 thankfully even drop IE 8.

**Comment by mdo** [comment]
@nextgenthemes Take it easy—this person asked a simple question and deserves an answer that doesn't involving raging at them :).
