### ISSUE TITLE
H1 tag not responsive for max-width: 768px

### ISSUE THREAD

**Issue by aicm** [twbs/bootstrap#16510]
Hello there guys. On my iPhone 6 Plus, if I use an h1 tag in portrait mode, and it's too long of a title, the h1 will bleed outside of its div container and mess up the overall appearance - using jumbotron theme. H1 tag is not responsive. It somehow escaped QA :sweat_smile:

**Comment by kkirsche** [comment]
Hey @aicm thanks for the report. Could you post a quick JSBin demonstrating the problem? Makes it easier for us to check that kinda stuff :smiley:

**Comment by kkirsche** [comment]
JSBin: http://jsbin.com/dawogaxizo/1/

Unable to duplicate via the iOS Simulator for the iPhone 6 Plus.

![screen shot 2015-05-19 at 9 22 48 pm](https://cloud.githubusercontent.com/assets/947110/7717308/39d1b380-fe6d-11e4-9dbe-a49030a720fd.png)

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://jsbin.com/dawogaxizo/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 10, column 1 thru line 10, column 32: Attribute ```` cz-shortcut-listen ```` not allowed on element ```` body ```` at this point.
* line 43, column 7 thru line 43, column 12: Stray end tag ```` div ````.
* line 50, column 5 thru line 50, column 10: Stray end tag ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
Updated JSBin cleaning up leftover tags from copying off the example source code: http://jsbin.com/zixuxefolo/1/

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (http://jsbin.com/zixuxefolo/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kkirsche** [comment]
http://jsbin.com/nulanuzupa/1/ Updated again...

Latest screen shot
![screen shot 2015-05-19 at 9 27 03 pm](https://cloud.githubusercontent.com/assets/947110/7717344/d1519324-fe6d-11e4-99bf-661636585957.png)

**Comment by StevenBlack** [comment]
@kkirsche confirming in both Safari and Chrome on an actual iPhone 6 Plus, I see what you see.

**Comment by kkirsche** [comment]
Thanks for looking on a device @StevenBlack. Simulator is good but not a replacement for the actual hardware. :+1:

**Comment by mdo** [comment]
If a particular string of text is too large or too long, that's up to you to account for I imagine. We don't have a responsive type scale in Bootstrap 3.

**Comment by aicm** [comment]
Wow you guys are fast. My apology, I didn't do a good job reporting this. @mdo has a point, however. It's precisely when the string is too long that the h1 tag pokes outside of its containers. And bootstrap is probably not the one that needs to account for user's content.

Here's my FF on OS X which basically shows the same way it does on my iPhone when I resize the viewport: ![screen shot 2015-05-20 at 12 32 02 pm](https://cloud.githubusercontent.com/assets/527855/7731127/47b33cec-feec-11e4-91f9-61a848dbeb29.png)

**Comment by kukac7** [comment]
@aicm 
```css
h1 { word-wrap: break-word; }
```

**Comment by aicm** [comment]
@kukac7 genius. Thank you!

**Comment by juthilo** [comment]
Closing per @mdo's comment and ff., i.e.: this problem should be addressed on an individual basis, not on the Bootstrap level.
