### ISSUE TITLE
CSS: .panel overflow should be hidden

### ISSUE THREAD

**Issue by hoofstephan** [twbs/bootstrap#16512]
Hi,

A .panel has rounded corners (border-radius: 4px;) and it's CSS overflow is visible (default). Because of this, it's contents is shown outside of the .panel's corners. (because 4px border-radius is relative small, this issue is not seen at first glance. Increase the radius will reveal it)

This issue can be resolverd by CSS:

.panel {
    overflow: hidden;
    ...
}

**Comment by kkirsche** [comment]
What browser and os are you on?

**Comment by hoofstephan** [comment]
W8 / Chrome







Kevin Kirsche <notifications@github.com> , 20-5-2015 14:02:

What browser and os are you on?

**Comment by mdo** [comment]
Yeah that'd crop everything within it—can't do that I'm afraid. Also that'd probably fuck up some folks' stuff given it's a rather large change to make now (so close to v4).
