### ISSUE TITLE
lack of Chinese sns icon

### ISSUE THREAD

**Issue by boss420** [twbs/bootstrap#16518]
Hi,
I'm using the Bootstrap to build my webiste,it's cool and fast.
However,I found I cannot find the Chinese sns icon,Could you please add some?
For example, Wechat from tencent,Weibo from Sina.
Thanks very much.

**Comment by juthilo** [comment]
Bootstrap doesn't feature icons for any kind of social network right now. Glyphicpns will be removed completely in v4, instead letting users choose their own icon font independently.

FontAwesome might have what you're looking for: http://fontawesome.io/icons/

**Comment by patrickhlauke** [comment]
Confirming that FontAwesome does have icons for Wechat and Weibo, so I'd suggest going down that route and integrating FA.

**Comment by boss420** [comment]
Thanks very much.I've found it.

Regards,
Jan

可用于iOS的myMail发送


2015年5月21日 星期四 +080016:32 发件人 Julian Thilo  <notifications@github.com>:
