### ISSUE TITLE
touch device (e.g. iOS) dropdown backdrop is removed incorrectly

### ISSUE THREAD

**Issue by gwynjudd** [twbs/bootstrap#16516]
This issue can be seen in this fiddle (http://jsfiddle.net/rfyt2fr3/1/) on an iOS touch device (probably other touch devices as well):

1. click on the dropdown to show it
2. verify using the web inspector that the dropdown backdrop has been added
3. click anywhere in the page
4. note that the dropdown backdrop is removed, but the dropdown didn't close due to the js event handler

On touch devices, the bootstrap plugin adds a dropdown:

https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L69

```javascript
      if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
        // if mobile we use a backdrop because click events don't delegate
        $(document.createElement('div'))
          .addClass('dropdown-backdrop')
          .insertAfter($(this))
          .on('click', clearMenus)
      }
```

It's evident that this backdrop is meant to compensate for the known issue of click events not ~~propagating~~delegating, otherwise the `clearMenus` doesn't run when you click anywhere:

https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L158

```javascript
  $(document)
    .on('click.bs.dropdown.data-api', clearMenus)
```

The code that removes the backdrop does so, even if the `hide.bs.dropdown` event handler prevented the close.

https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L37

```javascript
  function clearMenus(e) {
    if (e && e.which === 3) return
    $(backdrop).remove()
```

**Comment by gwynjudd** [comment]
I think the backdrop should be removed in clearMenus after the `hide.bs.dropdown` event has completed. It should only be removed from the parent element (this is a different issue I guess, but it helps with nested dropdowns):

```javascript
  function clearMenus(e) {
  	if (e && e.which === 3) return
    $(toggle).each(function () {
...
      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $parent.find(backdrop).remove()

      $this.attr('aria-expanded', 'false')
      $parent.removeClass('open').trigger('hidden.bs.dropdown', relatedTarget)
    })
  }
```

**Comment by cvrebert** [comment]
If we apply one of the workarounds from https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile , it's possible that the backdrop might become unnecessary.

**Comment by kkirsche** [comment]
@cvrebert does twbs have a preference which workaround is implemented?

**Comment by cvrebert** [comment]
There hasn't been sufficient discussion around it yet to form a preference.

**Comment by holtkamp** [comment]
I encountered this issue with the ```dropdown-backdrop``` element sometimes NOT being removed properly on iOS devices when using quite a few dropdown elements on a single page. Way to reproduce:

- open dropdown-menu by clicking button with a ```data-toggle="dropdown"``` attribute
- select a list item from the dropdown-menu
 - note we use ```<li><a href="javascript:void(null);">item X</a></li>``` elements
- see the dropdown-menu close automatically

After about 5 to 10 times repeating these steps, it made the browser tab in both physical and simulated iOS devices freeze, emitting lots of messages in the system log:

```
Nov 30 17:56:45 Mennos-MacBook-Pro assertiond[6895]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
Nov 30 17:57:15 --- last message repeated 45 times ---
Nov 30 17:57:15 Mennos-MacBook-Pro assertiond[6895]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
Nov 30 17:57:45 --- last message repeated 89 times ---
Nov 30 17:57:45 Mennos-MacBook-Pro assertiond[6895]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
Nov 30 17:57:45 Mennos-MacBook-Pro assertiond[6895]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
Nov 30 17:58:15 --- last message repeated 22 times ---
```

Forcing the backdrop to be removed after a dropdown-menu is opened resolved these freezes. 

```javascript
$('.dropdown-toggle').click(function (event) {
    event.preventDefault();
    setTimeout($.proxy(function () {
        if ('ontouchstart' in document.documentElement) {
            $(this).siblings('.dropdown-backdrop').off().remove();
        }
    }, this), 0);
});
```

I am aware that this way we do not follow [the best iOS practices of having a dropdown-menu close "when clicking elsewhere on a page"](http://getbootstrap.com/javascript/#dropdowns-usage), but this is better than a crashing browser tab.

Suggestions for a more elegant approach are welcome. Just reporting this to make this issue better findable and hopefully some day have Bootstrap itself incorporate a way to improve stability on iOS devices.

**Comment by holtkamp** [comment]
Just wondering whether this issue is on the radar for version 4?

**Comment by cvrebert** [comment]
@holtkamp Your problem is fairly different from this issue. Please open a new issue.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
