### ISSUE TITLE
Dropdown-menu - position absolute

### ISSUE THREAD

**Issue by tmmorimoto** [twbs/bootstrap#16514]
Hi everybody,

I`d like to report a problem with the class="dropdown-menu" (line 3277-bootstrap.min.css)

When we are using extra small devices (less than 768px), the position absolute make difficult to users select options because it doesn`t scroll properly. I used position: relative for this.

.dropdown-menu{
position: absolute; 
}  

Thanks!

**Comment by mdo** [comment]
Have an example of what you're referring to? There shouldn't be any problems with these dropdowns—these styles haven't changed in quite awhile.

**Comment by LondonZone** [comment]
Can you post a snippet or screenshot of the problem?

**Comment by mdo** [comment]
Closing until we hear more.

**Comment by tmmorimoto** [comment]
Hi!

Sorry for the time I did`t answer your question.

It just happens when we are using extra small devices (less than 768px):

Less than 768px:

![screen shot 2015-06-03 at 3 03 04 pm](https://cloud.githubusercontent.com/assets/6499905/7967730/50d66b20-0a02-11e5-80dc-2d73b4f41387.png)

More than 768px:

![screen shot 2015-06-03 at 3 12 28 pm](https://cloud.githubusercontent.com/assets/6499905/7967818/0f140b9c-0a03-11e5-8b87-6cead7a3ede9.png)


Thank you very much! :)

**Comment by mdo** [comment]
I can't speak to that exact example I'm afraid. Any chance you could make a jsbin?
