### ISSUE TITLE
Border around <select> caret in IE

### ISSUE THREAD

**Issue by WonSong** [twbs/bootstrap#16527]
Only happens in IE.

![image](https://cloud.githubusercontent.com/assets/5981331/7788949/2924762c-0204-11e5-877d-372dd93d69b1.png)

**Comment by WonSong** [comment]
Messed up rebasing. closed the old pull request... will request a new one

**Comment by cvrebert** [comment]
@WonSong What *version(s)* of IE and Windows?
I personally wouldn't call this a bug, but rather just a normal variation in native widget appearance, which necessarily differs by platform.

**Comment by WonSong** [comment]
@cvrebert  I use Windows 8.1 and IE11.
Should I just close this then?

**Comment by cvrebert** [comment]
We should wait for @mdo to weigh in.

**Comment by WonSong** [comment]
@cvrebert @mdo 

Sure. I created a pull request anyway in case... please discard if you feel it's not needed.
JFYI, I worked as a contractor at Microsoft and this issue came up as a bug for my projects though I am sure it does not matter :)

![image](https://cloud.githubusercontent.com/assets/5981331/7788960/977f83dc-0204-11e5-9ce4-aa32e1902311.png)

**Comment by WonSong** [comment]
How IE11 select box looks without ```form-control``` class:

![image](https://cloud.githubusercontent.com/assets/5981331/7789498/56beb3dc-0217-11e5-9614-82e9d561b74d.png)

**Comment by mdo** [comment]
What versions of IE does this affect?

**Comment by WonSong** [comment]
![image](https://cloud.githubusercontent.com/assets/5981331/7789761/fca3fef6-0221-11e5-955b-094ac1279224.png)

According to Visual Studio's intellisense, -ms-expand is enabled for IE 10 and above.

**Comment by cvrebert** [comment]
IE8-11 have boxes around their `<select>` menu triangles/arrows by default.

Win 7 IE8:
![win7-ie8](https://cloud.githubusercontent.com/assets/419884/7789766/3b3b3ac6-0222-11e5-997c-33175ef066ee.png)

Win 7 IE9:
![win7-ie9](https://cloud.githubusercontent.com/assets/419884/7789767/4afb3ec0-0222-11e5-9b11-c00505637c1c.png)

Win 8 IE10 looks the same as the screenshot in https://github.com/twbs/bootstrap/issues/16527#issuecomment-105055058

I can confirm that the proposed "fix" is only effective in IE10+.

**Comment by cvrebert** [comment]
For comparison, Firefox has similar boxes in its `<select>`s in Win XP thru Win 8.1.

Win 8/8.1 Firefox:
![win81-win8-ff](https://cloud.githubusercontent.com/assets/419884/7789806/9e59cb26-0223-11e5-9c38-39a70e63e0b8.png)

Win XP/7 Firefox:
![win7-ff](https://cloud.githubusercontent.com/assets/419884/7789807/acd294a8-0223-11e5-8e69-65004cce6dee.png)

**Comment by cvrebert** [comment]
In fairness, based on my extremely limited testing, it appears that pull-down menus in native Win 8 apps have no boxes around their carets.

**Comment by mdo** [comment]
Closing as #16529 was merged. Thanks!
