### ISSUE TITLE
2px border in input group.

### ISSUE THREAD

**Issue by inferusvv** [twbs/bootstrap#16521]
Just look this code: http://jsfiddle.net/8fhoc4bL/

If I put input group addon and it is not last or first, 2px border becomes between input and this addon.

**Comment by twbs-lmvtfy** [comment]
Hi @inferusvv!

You appear to have posted a live example (http://fiddle.jshell.net/8fhoc4bL/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 44, column 25: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Closing as invalid since, as the bot says, we don't support that.
