### ISSUE TITLE
Dropdown not aligning when text-center is applied for div

### ISSUE THREAD

**Issue by senthilsivanath** [twbs/bootstrap#16520]
When text-center class is used along with dropdown component, alignment is not centered for context menu
![without text-center](https://cloud.githubusercontent.com/assets/1016068/7749106/46edd91e-ffe8-11e4-86ea-dbe75f5ff302.png)

While disabling text-center alignment property it works fine, but it loses container alignment
![with text-center bug](https://cloud.githubusercontent.com/assets/1016068/7749103/43381262-ffe8-11e4-833f-1eb57ddc28fe.png)

**Comment by cvrebert** [comment]
What if you use [`.center-block`](http://getbootstrap.com/css/#helper-classes-center) instead?

**Comment by senthilsivanath** [comment]
using .center-block is not aligning the drop down. Drop down goes to left alignment.

**Comment by zacechola** [comment]
@senthilsivanath Would you post a live demo of this behavior? 

I'm unable to reproduce it here: http://jsbin.com/duwidu/1/edit?html,output

**Comment by mdo** [comment]
Dropdowns are positioned absolutely based on the parent element—whatever closest parent has `position: relative`. If you're realigning things, you'll need to account for that somehow.
