### ISSUE TITLE
radio-button + tooltip bug

### ISSUE THREAD

**Issue by NMFES** [twbs/bootstrap#16522]
```javascript
<div class="btn-group" data-toggle="buttons">
        <label class="btn btn-default btn-lg active" data-toggle="tooltip" data-placement="top" title="Отобразить плиткой">
            <input type="radio" name="options" id="option1" autocomplete="off" checked="checked"> <span class="fa fa-th-large"></span> 
        </label>
        <label class="btn btn-default btn-lg" data-toggle="tooltip" data-placement="top" title="Отобразить списком">
            <input type="radio" name="options" id="option2" autocomplete="off"> <span class="fa fa-th-list"></span>
        </label>
    </div>

....

$(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
});
```

1. Normal state. Mouse is out of buttons.
![1](https://cloud.githubusercontent.com/assets/12520993/7767837/608a065e-007e-11e5-913c-3d48f04f9304.png)

2. Mouse hover on left button. Appears 1 pixel space between two buttons.
![2](https://cloud.githubusercontent.com/assets/12520993/7767836/6089e6a6-007e-11e5-8638-b10671320565.png)

3. Mouse hover on right button. There are no rounding on right border of right button.
![3](https://cloud.githubusercontent.com/assets/12520993/7767835/60875b34-007e-11e5-991a-0ea4c3c985ac.png)

Bootstrap v3.3.2
Latest chrome and mozilla browsers.
Ubuntu 14.

**Comment by patrickhlauke** [comment]
Interesting...confirmed http://jsfiddle.net/zor1rz6f/

**Comment by twbs-lmvtfy** [comment]
Hi @patrickhlauke!

You appear to have posted a live example (http://fiddle.jshell.net/zor1rz6f/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 34, column 9: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to 'body'. Found tooltips/popovers that might lack this setting.
* line 37, column 9: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to 'body'. Found tooltips/popovers that might lack this setting.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
But, as @twbs-lmvtfy rightly pointed out, tooltips in button groups need the extra option for `container:'body'` ... adding this fixes it http://jsfiddle.net/zor1rz6f/1/

**Comment by twbs-lmvtfy** [comment]
Hi @patrickhlauke!

You appear to have posted a live example (http://fiddle.jshell.net/zor1rz6f/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 34, column 9: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to 'body'. Found tooltips/popovers that might lack this setting.
* line 37, column 9: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to 'body'. Found tooltips/popovers that might lack this setting.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
