### ISSUE TITLE
Bootstrap Drupal: changing link of currently active page

### ISSUE THREAD

**Issue by arebacollins** [twbs/bootstrap#16531]
Apologies as I couldn't find where to ask this on the drupal theme page. I am using bootstrap 3 to do this site. dev.infonet-biovision.org , and I somehow cant get to change the font colour and weight of the links to the currently active pages. 
A quick pointing to the right direction will really help. 
Regards, 
Collins.

**Comment by juthilo** [comment]
Please refer to StackOverflow for how-to questions like this. Thanks!
