### ISSUE TITLE
input-groups.less uses @border-radius instead of @input-border-radius

### ISSUE THREAD

**Issue by mrmv** [twbs/bootstrap#16537]
input-groups.less uses @border-radius instead of @input-border-radius

Maybe this is intentional, but I expected it to use @input-border-radius

**Comment by supergibbs** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/16492

**Comment by mrmv** [comment]
Awesome, thanx !

**Comment by mdo** [comment]
Closing since we merged #16492.
