### ISSUE TITLE
Customize page does not support Safari

### ISSUE THREAD

**Issue by moubry** [twbs/bootstrap#16538]
http://getbootstrap.com/customize/

The Customize page on Bootstrap's website does not support the latest version of Safari. A message appears that says:

> Looks like your current browser doesn't support the Bootstrap Customizer. Please take a second to upgrade to a more modern browser (other than Safari).

What's going on here? A bug in the feature detection? Or is this really the intent?

**Comment by mdo** [comment]
Really is the intent. Safari is incapable of downloading the generate zip file with a filename and extension I believe, so rather than giving folks that, we ask they use Chrome or Firefox.

**Comment by moubry** [comment]
I'm probably missing something—not very familiar with what Bootstrap is doing here... but this project looks like it provides Safari support (somehow): https://stuk.github.io/jszip/

**Comment by mdo** [comment]
Maybe something for @fat or @cvrebert to consider? They've worked the most on the customizer.

**Comment by cvrebert** [comment]
It's not a JSZip problem, it's a FileSaver.js problem: https://github.com/eligrey/FileSaver.js/issues/12

**Comment by kkirsche** [comment]
I don't think he meant it was an issue with JSZip @cvrebert but rather that using JSZip instead of Filesaver would resolve the issue entirely.

**Comment by cvrebert** [comment]
@kkirsche JSZip doesn't itself provide any file saving feature, FWICT. [JSZip's own official example](https://stuk.github.io/jszip/) uses FileSaver.js for the file saving functionality.
The Bootstrap v3 customizer uses JSZip to generate the binary ZIP data and then FileSaver.js to allow the user to save that data to a file on disk, just like in JSZip's own example code.

**Comment by cvrebert** [comment]
Duplicate of #14832.

**Comment by codyrobbins** [comment]
As discussed in #14832, the customize page includes documentation—namely, the Less/Sass variable names. Clicking the link in the [main documentation that talks about variables](http://getbootstrap.com/css/#less-variables) frustratingly shows you the documentation you are looking for, but only until the Javascript kicks in and shows the unsupported browser message.

Either the documentation on variables should be moved to a separate page that isn’t intentionally disabled for Safari users, or the FileSaver.js shortcoming should be worked around to allow Safari users to manually download the file so the page can be re-enabled.

**Comment by codyrobbins** [comment]
The complete absurdity of this issue not being fixed for years notwithstanding, if you’re using Safari you can find the variable documentation directly in the Bootstrap source here:

https://github.com/twbs/bootstrap/blob/v3-dev/less/variables.less

The customizer page on the Bootstrap website auto-generates its documentation by parsing this file.
