### ISSUE TITLE
Docs: hovering over list group item heading shows anchor icon

### ISSUE THREAD

**Issue by dchest** [twbs/bootstrap#16539]
http://getbootstrap.com/components/#list-group-custom-content

![hover](https://cloud.githubusercontent.com/assets/52677/7832607/9d63fafe-0460-11e5-894f-eb3c7e2b191d.gif)

**Comment by kkirsche** [comment]
I believe this is caused by AnchorJS's rule `anchors.add('.bs-docs-section > h1, .bs-docs-section > h2, .bs-docs-section > h3, .bs-docs-section > h4, .bs-docs-section > h5')` from https://github.com/twbs/bootstrap/blob/master/docs/assets/js/src/application.js#L182

**Comment by mdo** [comment]
Is this problem actually in master, or just live on the docs which doesn't have the latest JS? I don't think we need that `remove` @kkirsche since I had change that line to the `.bs-docs-section > *` stuff awhile back to fix this bug elsewhere.

**Comment by kkirsche** [comment]
@mdo live in the docs but I can't confirm on master yet. When I get home @mdo I'll install Rogue so I can fully build the docs. I'll verify it for you there and be able to tell you with certainty if it exists in master currently or if the `remove` would still be necessary. Sorry for the inconvenience on that!

**Comment by dchest** [comment]
Can't reproduce this in master, sorry for the noise.

**Comment by mdo** [comment]
All good, thanks @dchest.
