### ISSUE TITLE
Meteor package without Glyphicons

### ISSUE THREAD

**Issue by dandv** [twbs/bootstrap#16530]
Hey @splendido,

[twbs:bootstrap-noglyph](https://atmospherejs.com/twbs/bootstrap-noglyph) is behind two minor versions. In my previous approach, I had a script that published both the regular package and the noglyph one. Since you moved `package.js` to this repo, can you please take a look at bringing `noglyph` up to date too?

**Comment by splendido** [comment]
Ok!
I'll use the new approach we're testing to autopublish it when we get the trigger from the main `twbs/boostrap` repo...

I'll let you know when it's ready

**Comment by splendido** [comment]
Done!
See [twbs:bootstrap-noglyph](https://atmospherejs.com/twbs/bootstrap-noglyph) on atmosphere, now wrapped from [twbs-bootstrap-noglyph](https://github.com/MeteorPackaging/twbs-bootstrap-noglyph).

I hope to integrate the automated publish for these new repos soon.

**Comment by mdo** [comment]
Closing then.
