### ISSUE TITLE
bootstrap ScrollSpy not jump to div when click on dropdown menu item

### ISSUE THREAD

**Issue by athimannil** [twbs/bootstrap#16535]
Dropdown menu click ScrollSpy doesn't working
Demo: http://codepen.io/anon/pen/vOyZGq

![screen shot 2015-05-26 at 5 55 10 pm](https://cloud.githubusercontent.com/assets/4364227/7813607/04f9b24e-03da-11e5-827e-dbf516ba7435.png)

**Comment by twbs-lmvtfy** [comment]
Hi @athimannil!

You appear to have posted a live example (http://codepen.io/anon/pen/vOyZGq.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru line 8, column 71: Start tag ```` body ```` seen but an element of the same type was already open.
* line 8, column 1 thru line 8, column 71: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Also, you seem to be missing the required `body { position: relative; }` style that's documented as being required for ScrollSpy.

**Comment by athimannil** [comment]
@cvrebert  Thank you very much for your reply. The answer from Stackoverflow seems to me better http://stackoverflow.com/questions/30458578/bootstrap-scrollspy-not-jump-to-div-when-click-on-dropdown-menu-item

**Comment by cvrebert** [comment]
Closing as not a Bootstrap bug, per the answer in that SO thread.
