### ISSUE TITLE
Comments lose mark-down formatting with wide content

### ISSUE THREAD

**Issue by ukessays-me** [twbs/bootstrap#16548]
If long text such as a full URL is entered into any comments box and exceeds the width of the visible pane the comments box automatically adds in horizontal scroll functionality. In these scrollable sections of the comment it is not possible to view  mark-down formatting and URLs become unclickable.

**Comment by kkirsche** [comment]
@ukessays-me would you be able to post a JSBin / JSFiddle showing an example of this issue?

**Comment by cvrebert** [comment]
This doesn't sound directly Bootstrap-related. Bootstrap has nothing to do with markdown rendering.
Willing to reopen this if an example demonstrating otherwise is posted though.
