### ISSUE TITLE
Issue with responsiveness - using row, container and grid 

### ISSUE THREAD

**Issue by TASimpson** [twbs/bootstrap#16549]
When changing size of container and items within it seem to change as they should for the most part. However, when expanding my window, the container size will jump from 944px X 240px to 463.5px x 289px within just a couple of pixels difference in the explorer window. 

This happens in IE and chrome. 

![image](https://cloud.githubusercontent.com/assets/11613404/7845958/0db5e4ec-0480-11e5-81d6-2a563bb764d7.png)

![image](https://cloud.githubusercontent.com/assets/11613404/7845972/1e8d02c8-0480-11e5-8373-a539309338e7.png)

I have pasted the code as well, I haven't done anything "crazy" to the code: 

![image](https://cloud.githubusercontent.com/assets/11613404/7846025/85d2447a-0480-11e5-9ad1-56f0f82140e2.png)

**Comment by mdo** [comment]
Don't include containers within rows. That'll probably fix most of your problems.

**Comment by TASimpson** [comment]
I removed all rows and containers following the initinal "container-fluid", I only kept the grids, and I still have that overlapping effect.

**Comment by mdo** [comment]
Ah, yeah. Add `.img-responsive` or manually adjust the image's width. That'll naturally break out of any parent like that otherwise.

**Comment by mdo** [comment]
And you need the nested `.row`s, just not the nested `.container-fluid`s.

**Comment by cvrebert** [comment]
Try using [Bootlint](https://github.com/twbs/bootlint). It can detect many grid system usage mistakes.

**Comment by TASimpson** [comment]
Hey mdo! So I did all you suggested...and it's still an issue of when I get to that point in the window my text overlap AND the image using 'img-responsive' gets thumbnail size...which looked awful :( 

Oh and cvrebert, I used Bootlint but it didn't find any grid usage mistakes. But great app, thanks for introducing it to me. Will use going forward!
