### ISSUE TITLE
Input Group Addons make rounded

### ISSUE THREAD

**Issue by anonprophet** [twbs/bootstrap#16540]
```
      <div class="form-group">
        <div class="input-group">
          <input type="text" name="username" value="" class="form-control input-lg" placeholder="Username" />
          <div class="input-group-addon"><b>LES</b></div>
          
          <input type="hidden" name="rand" value="LES" />
        </div>
      </div>
```
![rounded](https://cloud.githubusercontent.com/assets/8217350/7832683/156cbd4a-048b-11e5-9c07-3a16d7761f94.jpg)

**Comment by kkirsche** [comment]
@anonprophet It's because of your hidden input. The `input-group-addon` should be the last child. Change your markup to this and it'll fix it:

```html
<div class="form-group">
    <div class="input-group">
        <input type="text" name="username" value="" class="form-control input-lg" placeholder="Username" />
        <input type="hidden" name="rand" value="LES" />
        <div class="input-group-addon"><b>LES</b></div>
    </div>
</div>
```

See: https://jsfiddle.net/k3h1ewq0/

**Comment by twbs-lmvtfy** [comment]
Hi @kkirsche!

You appear to have posted a live example (https://fiddle.jshell.net/k3h1ewq0/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 41, column 9: [E009](https://github.com/twbs/bootlint/wiki/E009): Button and input sizing within `.input-group`s can cause issues. Instead, use input group sizing classes `.input-group-lg` or `.input-group-sm`
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
@patrickhlauke Why the close here?

**Comment by patrickhlauke** [comment]
i thought #16542 was a good candidate for a solution. fair enough though if we want to reopen @mdo

**Comment by mdo** [comment]
Oh, yeah, I like to leave the issues open until the PRs are closed :). Easier that way if someone happens to the proposed fix.

**Comment by mdo** [comment]
Closing per #16542.
