### ISSUE TITLE
small and small, .small

### ISSUE THREAD

**Issue by Relequestual** [twbs/bootstrap#16547]
I notice that a small element first sets the font-size of 80%, but is then superseeded later to be a font-size of 85%

declaration of small
https://github.com/twbs/bootstrap/blob/049e86f47e90b35eeaf97d6b735f2fd3d62c0d1c/dist/css/bootstrap.css#L71-L73

declration of small, .small
https://github.com/twbs/bootstrap/blob/049e86f47e90b35eeaf97d6b735f2fd3d62c0d1c/dist/css/bootstrap.css#L1305-L1308

Seems a bit redundant. Should the small part of the second declration be removed, or is the intension for the second declaration to be correct, and therefore the first should be removed?

**Comment by mdo** [comment]
We can consolidate that stuff in v4, but for now we'll leave it as-is to avoid any backward incompatibility or unexpected changes.

**Comment by Relequestual** [comment]
@mdo Sure. In which case, wouldn't you want to add it to a 4.0 milestone or such? Otherwise, won't it simply get lost / forgotten about?

**Comment by mdo** [comment]
We're tracking a lot of stuff in a separate list.

**Comment by mdo** [comment]
Also, looking at this again, this is a won't fix. That first `small` is coming from Normalize.

**Comment by Relequestual** [comment]
Fair enough! =]
