### ISSUE TITLE
A lot of dropdowns in page will decrease performance

### ISSUE THREAD

**Issue by nikshulipa** [twbs/bootstrap#16553]
I've noticed that inside of  dropdown.js plugin, we have this code

```javascript
// APPLY TO STANDARD DROPDOWN ELEMENTS
// ===================================

$(document)
    .on('click.bs.dropdown.data-api', clearMenus)
```
so on each click on page it will execute function `clearMenus`
and inside of it, we have loop through all of dropdowns:

```javascript
$(toggle).each(function () {
```
where `toggle = '[data-toggle=dropdown]'`

My proposal is:
iterate only over open dropdowns
```javascript
$('.open ' + toggle).each(function () {
```
Also, in this case we will probably no need to checking below
```javascript
if (!$parent.hasClass('open')) return
```

Correct me if I wrong so I can create a pull-request for this

**Comment by fat** [comment]
the performance of this is basically negligible, don't think it's worth the optimization. thanks tho!

**Comment by animafact** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

animafact@naver.com 님께 보내신 메일 <Re: [bootstrap] A lot of dropdowns in page will decrease performance (#16553)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
