### ISSUE TITLE
Forums select arrow background show in Mozila but hide in Chrom 

### ISSUE THREAD

**Issue by kashinaat** [twbs/bootstrap#16551]
http://softoniktech.co.uk/dev/tca_wp/?page_id=8
plz chek this link

**Comment by coliff** [comment]
You're using an old version of Bootstrap:
http://softoniktech.co.uk/dev/tca_wp/wp-content/themes/tca/js/bootstrap/css/bootstrap.min.css
- please update to latest version (3.3.4).

This isn't a place to report problems with your own website. If you want to report a specific issue with the Bootstrap framework then please open a http://jsfiddle.net with a clear example.

**Comment by cvrebert** [comment]
Yes, this issue tracker isn't for personal support requests. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker and https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by kashinaat** [comment]
ok thanks i remove my question
