### ISSUE TITLE
How to show bootstrap affix position:fix with in .container for the .nav-tabs ?

### ISSUE THREAD

**Issue by athimannil** [twbs/bootstrap#16556]
bootstrap affix works fine but unfortunately the sticky tab does not show with in the `.container` it display as full width. Is there any option to show `nav-tabs` with in the container as central aligned ?

Demo: http://codepen.io/anon/pen/vOyZGq

**Comment by twbs-lmvtfy** [comment]
Hi @athimannil!

You appear to have posted a live example (http://codepen.io/anon/pen/vOyZGq.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru line 8, column 45: Start tag ```` body ```` seen but an element of the same type was already open.
* line 8, column 1 thru line 8, column 45: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
For how-to questions like this, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/twitter-bootstrap-3) (or similar) instead of the issue tracker. Thanks!
