### ISSUE TITLE
4.0 request - responsive spacing

### ISSUE THREAD

**Issue by morrow95** [twbs/bootstrap#16550]
I often find myself applying a spacing margin on my col-x divs so when in collapsed view there is some 'space' for visual appearance.  This is easy enough to do and is more appearance orientated than anything, but I think if done properly this could be useful as a new css feature set.

For example, I find myself doing something like this a lot where mb-30 would be a 30px bottom margin... the row is nothing special so I have no need to apply an id to it or use any other custom css... I just want to apply some spacing between the next container for visual appearance  : 
```
<div class="row">
    <div class="col-md-4 mb-30">
    <div class="col-md-4 mb-30">
    <div class="col-md-4 mb-30">
```
If the spacing was put on the row only then when viewed on xs and sm there would be no spacing between the 'now full width' stacked divs.

My proposal would go something like : 
```
<div class="row space-sm">
    <div class="col-md-4">
    <div class="col-md-4">
    <div class="col-md-4">
```
Where space-sm would be a margin applied to all immediate col-x-x children of the row.  There would be small, large, xlarge spacing values.  Incorporated in sass/less you could easily change these spacing values to whatever you wanted.  You could even take this a step further and have col-md-space-sm where it would only apply to col-md-x classes.  So in total you would have 3 spacing values for 4 breakpoints (xs, sm, md, lg) for a total of 12 extra classes.

Just thought I would throw it out there... maybe I am the only one who does this.

**Comment by joshuakelly** [comment]
Could you not use something like the vh/vw measurements to get what you need?

**Comment by morrow95** [comment]
How would that apply here?  I am simply talking about spacing between containers for visual appearance.  Maybe I didn't do a good job explaining what I am talking about.

**Comment by mdo** [comment]
More utilities are planned for v4, but likely not for the grid. That'd require a bit more work because of the way our grid is built. Could still use them, but it's need more work to do right.

**Comment by morrow95** [comment]
Right on... thanks for taking a look mdo.  Just thought I would throw it out there.
