### ISSUE TITLE
Bower has older version than GitHub master

### ISSUE THREAD

**Issue by IvanFarkas** [twbs/bootstrap#16555]
bower install twbs/bootstrap is getting an old version.

bower install twbs/bootstrap -> bootstrap/less/normalize.less has normalize.css v3.0.2
GitHub master -> bootstrap/less/normalize.less has normalize.css v3.0.3

There are other differences as well.
Is it possible to keep GitHub and bower in sync?

**Comment by zacechola** [comment]
This could be a lot of things, but my gut says check your bower configuration in your project that you're not locked to a 3.0.x tag.

Secondly, that's the correct version of normalize.css that bootstrap uses.

**Comment by mdo** [comment]
Yeah, that's the version of a dependency of ours, not Bootstrap itself. And `master` reflects the latest dev changes, not the last published release. Our releases handle that.
