### ISSUE TITLE
Multiple tabs conflict between themselves

### ISSUE THREAD

**Issue by ertong** [twbs/bootstrap#16554]
1. Take example from tabs docs.
2. Copy the code twice.
3. The second tabs change the state of the first tabs, which is not expected.

We can change ids for the second tabs, but it is not a good solution. 
Widgets should not rely on global ids.

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

<div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">Home</div>
        <div role="tabpanel" class="tab-pane" id="profile">Profile</div>
        <div role="tabpanel" class="tab-pane" id="messages">Messages</div>
        <div role="tabpanel" class="tab-pane" id="settings">Settings</div>
    </div>

</div>


<div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">Home</div>
        <div role="tabpanel" class="tab-pane" id="profile">Profile</div>
        <div role="tabpanel" class="tab-pane" id="messages">Messages</div>
        <div role="tabpanel" class="tab-pane" id="settings">Settings</div>
    </div>

</div>
```

**Comment by patrickhlauke** [comment]
> Widgets should not rely on global ids

Yes, in this case they should, as the links logically point to the unique panel that they control. FWIW having multiple elements with same `id` in the same document is also invalid HTML

**Comment by ertong** [comment]
Well, you can be right that having multiple elements with the same id is invalid. I agree with that.
But this fact does not change anything.

What if I use tabs, for example, in some popup block? And what if I need to open two almost equal popups? 

From your point of view I need to assign different ids for tabs in different popups. But it is a mess (it will lead to generating a lot of random ids).

From my point of view it it is logical to make a search for tabs only within tabpanel div. But currently, I do not see a way to do it without changing bootstrap code.

**Comment by patrickhlauke** [comment]
AFAIK, opening multiple popups (to take your example) is also not supported in Bootstrap. So this is still a no from me. @mdo ?

**Comment by mdo** [comment]
You'll need individual IDs for this kind of stuff. We're using browser-provided tools here for easier toggling—find the associated element by ID and show it. Anything more or different is something you'll have to account for outside Bootstrap.

**Comment by cvrebert** [comment]
Duplicate of #15505.
