### ISSUE TITLE
.dl-horizontal depends on @grid-float-breakpoint

### ISSUE THREAD

**Issue by dbkaplun** [twbs/bootstrap#16562]
The problem with `@grid-float-breakpoint` is that it's completely unrelated to `<dl>`s. It's used to determine whether a navbar's items should display as block.

**Comment by kkirsche** [comment]
Thanks for reporting this @dbkaplun, I'm not sure where you are seeing that though and was wondering if you could share which file or file(s) you see this in? Thanks!

**Comment by dbkaplun** [comment]
Sure, I'm almost done with a PR, will update the issue in a sec.

**Comment by dbkaplun** [comment]
See PR #16563

**Comment by mdo** [comment]
Closing since #16563 was merged. Thanks!
