### ISSUE TITLE
Browser crashed on iphone due to Carousel

### ISSUE THREAD

**Issue by mmhyamin** [twbs/bootstrap#16572]
I used two carousel in an one page website. Due to Carousel transition (.carousel-inner>.item) safari and chrome both browser on iphone is crashing.

**Comment by kkirsche** [comment]
Could you post a JSBin of the isolated problem so that we can ensure this is specific to Bootstrap and not the implementation you had?

**Comment by mmhyamin** [comment]
Here is [JSBin Link](http://jsbin.com/tenowo/1/edit?html,css,output). Try to change the slide using carousel indicators.

**Comment by twbs-lmvtfy** [comment]
Hi @mmhyamin!

You appear to have posted a live example (http://jsbin.com/tenowo/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 10, column 2 thru line 10, column 81: Element ```` link ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````, ```` rel ````.
* line 172, column 2 thru line 172, column 11: End tag ```` section ```` seen, but there were open elements.
* line 66, column 6 thru line 66, column 28: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mmhyamin** [comment]
w3 validation fixed. Here is the [Link](http://jsbin.com/tenowo/2/edit?html,css,output)

**Comment by twbs-lmvtfy** [comment]
Hi @mmhyamin!

You appear to have posted a live example (http://jsbin.com/tenowo/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 18, column 11: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 68, column 11: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mmhyamin** [comment]
Fixed. Here is the [Link](http://jsbin.com/tenowo/3/edit?html,output)

**Comment by twbs-lmvtfy** [comment]
Hi @mmhyamin!

You appear to have posted a live example (http://jsbin.com/tenowo/3/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Works on my iPhone 6 running latest iOS.

**Comment by kkirsche** [comment]
Worked for me as expected on an iPhone 5S with latest iOS

**Comment by mdo** [comment]
Closing until we hear more then.
