### ISSUE TITLE
button dropdowns doesn't display properly in responsive table

### ISSUE THREAD

**Issue by HenryYan2012** [twbs/bootstrap#16570]
I have a responsive table with button dropdowns inside in the last column. If you click the button dropdown the dropdown doesn't display properly .

This might releated with the fix of #13202

Tested on Chrome and Firefox for Mac with the latest versions.

http://output.jsbin.com/yifobikayi/1/

Image:
![button dropdown with responsive table](https://cloud.githubusercontent.com/assets/3112947/7928416/208e2f38-0922-11e5-832c-a5256a130ce1.png)

**Comment by mdo** [comment]
This is a dupe a couple times over I believe, but I don't have the numbers handy. It's not related to any fix—this just isn't possible. The `overflow` properties on the table's wrapper are required for the responsive-ness.
