### ISSUE TITLE
Generate js sourcemaps

### ISSUE THREAD

**Issue by xt0rted** [twbs/bootstrap#16583]
Is there any reason why the js files don't have sourcemaps like the css files do? Both the [concat](https://github.com/gruntjs/grunt-contrib-concat#sourcemap) and [uglify](https://github.com/gruntjs/grunt-contrib-uglify#sourcemap) tasks support this when you set `sourceMap` to `true`.

**Comment by kkirsche** [comment]
Good question. While I am not aware of a reason, when I get home / if the core team is interested I should be able to put together a PR to fix / add that.

**Comment by xt0rted** [comment]
The minified css files don't have sourcemaps either. This can be enabled with [cssmin](https://github.com/gruntjs/grunt-contrib-cssmin#sourcemap) the same way.

**Comment by mdo** [comment]
Punting on this since I believe we don't really do anything crazy to our JS. No matter what format you're running—individual, compiled, or minified+compiled—you'll get JS that runs in browser. Thanks though!
