### ISSUE TITLE
When modal is open users can access non-modal content via screen reader

### ISSUE THREAD

**Issue by propercursive** [twbs/bootstrap#16584]
Page contents other than the open modal are not `aria-hidden` so users can access non-modal content via a screen reader. Currently, users are prevented from tabbing out of the modal, but the underlying page content is navigable via the virtual cursor.

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by patrickhlauke** [comment]
One of the main stumbling blocks I can see here for a quick fix is that currently the underlying page itself is not wrapped in a unique container (which could then simply be given an `aria-hidden="true"`), with the modal outside of that container...so I don't think it's something we can easily enforce for v3. Punting for now, but adding this to potential features for v4. /cc @fat @mdo

**Comment by patrickfox** [comment]
@patrickhlauke Agreed that a common container to hold all non-modal page contents is ideal. I recommend an update that doesn't _require_ a unique container, but if there is one, it is `aria-hidden`. The way that we have done this is to have the developer designate the main page container using a data attribute(e.g. `data-isolate`).  (Also, it would be fairly easy to output a log message to remind the developer to do this if `data-isolate` isn't found). I don't think would be overly difficult to explain or implement, and it doesn't break if devs don't have things set up 100% correct. We can submit a PR if you'd like.

**Comment by patrickhlauke** [comment]
> Also, it would be fairly easy to output a log message to remind the developer to do this if data-isolate isn't found

I don't believe any of our JS fires off console log messages at the moment, and devs simply upgrading to the latest files may not even notice the change and we'd have log messages being generated in the wild...so not quite sure this would fly.

As said, I've added this to our internal v4 wishlist (which also includes plans to have more things like aria attributes etc being injected automagically, to avoid devs accidentally leaving crucial things out/cargo-culting the wrong attributes and structures) though.

**Comment by patrickfox** [comment]
Sounds good. Re: console messages - this could be part of a debug mode, possibly - not sure if BS has something like that.
