### ISSUE TITLE
Inline radio buttons are not aligned properly when they wrap

### ISSUE THREAD

**Issue by srinivasry** [twbs/bootstrap#16582]
Inline radio buttons are not aligned properly when the browser is minimized.
![inline-radio](https://cloud.githubusercontent.com/assets/11550150/7983865/2fa7ace4-0ae2-11e5-8533-c0a78e16d043.png)

Fixed the issue by modifying/overriding the bootstrap CSS . Find the modified CSS below.

.radio-inline+.radio-inline {
    margin-left: 0px;
    margin-right: 25px;
}

.radio-inline {
    margin-right: 25px;
    padding-left: 0px;
}

**Comment by kkirsche** [comment]
Hello @srinivasry would you be able to post a JSBin demonstrating the problem as well as share what Operating System and Browser (with versions) you are using? This will help others to confirm this issue.

**Comment by mdo** [comment]
Those shouldn't be inline then—those labels are far too long for a single line. Stick to the normal stacked ones instead.
