### ISSUE TITLE
Manually created tooltip cannot be destroyed in lot using the usual way

### ISSUE THREAD

**Issue by DemarsM** [twbs/bootstrap#16593]
Manually created tooltip cannot be destroyed in lot using the usual: `$('[data-toggle="tooltip"]').tooltip('destroy');`

http://jsfiddle.net/e6247y9c/18/

Maybe that would be nice to update the doc with the correct way to do it?

**Comment by twbs-lmvtfy** [comment]
Hi @DemarsM!

You appear to have posted a live example (http://fiddle.jshell.net/e6247y9c/18/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by acshef** [comment]
In your fiddle, you are attempting to use the jQuery selector for all elements where the data attribute `data-toggle` is `tooltip.` The checkbox in your DOM does not have this, so of course the selector does not return any elements. See the change I made to the checkbox in http://jsfiddle.net/e6247y9c/19/

**Comment by twbs-lmvtfy** [comment]
Hi @acshef!

You appear to have posted a live example (http://fiddle.jshell.net/e6247y9c/19/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by DemarsM** [comment]
I know, but when you create tooltips dynamically you dont put manually data-toggle="tooltip" attribute inside the element

**Comment by acshef** [comment]
You are right. But Bootstrap does not add the `data-` attributes if they're not present, so that's not the right way to select "elements that have had tooltips added to them dynamically." And I don't know the best way to do that. A simple method would be `$().tooltip({...}).addClass("has-tooltip")` and then you can access those elements with $(".has-tooltip")... but that's only one way. I'm sure there are more, and I'm sure some are better.

**Comment by cvrebert** [comment]
What @acshef said. Your code is based on incorrect assumptions.

**Comment by DemarsM** [comment]
@crevette ok so useless comment
