### ISSUE TITLE
Avoid creating temporary <div> in Modal.prototype.measureScrollbar

### ISSUE THREAD

**Issue by Samlv9** [twbs/bootstrap#16595]
```javascript
  Modal.prototype.measureScrollbar = function () { // thx walsh
    var scrollDiv = document.createElement('div')
    scrollDiv.className = 'modal-scrollbar-measure'
    this.$body.append(scrollDiv)
    var scrollbarWidth = scrollDiv.offsetWidth - scrollDiv.clientWidth
    this.$body[0].removeChild(scrollDiv)
    return scrollbarWidth
  }
```

为什么不用这种方式呢？个人感觉为了获取 scrollbar 的宽度创建一个 div 不是一个好的做法啊~~~
原谅我的弱智@
```javascript
  Modal.prototype.measureScrollbar = function () { // thx walsh
    var width = this.$body[0].clientWidth;
    this.$body.css("overflow", "hidden");
    var padWidth = this.$body[0].clientWidth - width;
    this.$body.css("overflow", "auto");
    return padWidth;
  }
```

**Comment by kkirsche** [comment]
@Samlv9 are you able to re-write this in English?

I have done a google translation of the text but this is often error prone and leads to miscommunications.
"Why not this way? Personal feeling to get scrollbar width to create a div is not a good practice ah ~~~
Forgive me mentally!"

**Comment by Samlv9** [comment]
@kkirsche sorry ~~~ my english is too  toooooo toooooooo bad!
i mean that if we what get the scrollbar's width,  we does not need to 'document.createElement("div")'
then get the div width,  how about set the container's overflow to 'hidden' ?  for example:

```css
.hide-scrollbar {
    overflow: hidden !important;
}
```

1,  get the body current width;
2,  give body the 'hide-scrollbar' class; if body no scrollbar, we can get the whole width of body;
3,  use body without scrollbar's width minus body with scrollbar's;
4, we have body scrollbar.width now~

**Comment by cvrebert** [comment]
The existing code is based on http://davidwalsh.name/detect-scrollbar-width

* I think messing with the body's overflow has the potential to cause flickering.
* Your proposed code is slightly too simple in that it doesn't account for the possibility of `<body style="overflow: XXX">`

**Comment by Samlv9** [comment]
@cvrebert thanks~~~ that's an great idea!



Sorry for my english teacher~~
Ps:
above my code just an example to show how i get the body scrollbar's width.
i can fixed it with 'addClass'  like this:


```css
.hide-scrollbar {
    overflow: hidden !important;
}
```
```javascript
Modal.prototype.measureScrollbar = function () { // thx walsh
    var oldWidth = this.$body[0].clientWidth;
    this.$body.addClass("hide-scrollbar");
    var padWidth = this.$body[0].clientWidth - oldWidth;
    this.$body.removeClass("hide-scrollbar");
    /// it will return 0 or 17 in my chrome, return 0 because the body have no scrollbar;
    return padWidth ;
  }
```

+：when `modal` will be open, body's padding right is `padWidth` + body default paddingRight;

**Comment by Samlv9** [comment]
I have to what your mean now~~~ thanks a lot~~

**Comment by Samlv9** [comment]
I have to what your mean now~~~ thanks a lot~~

**Comment by cervengoc** [comment]
I don't think there is anyithing wrong with the temporary DIV solution, it shouldn't cause too much performance overhead. However, creating it all the time is kind of a waste IMHO, could be nice to cache it into some utility variable. What do you think?

**Comment by cvrebert** [comment]
> scrollbar width is needed in more places

Hmm? I'm pretty sure Modal is our only widget that cares about the width of the scrollbar.

**Comment by cervengoc** [comment]
@cvrebert Yes, you're right, sorry. somehow I remembered incorrectly that the collapsing navbar is also preventing body scroll. However, caching would be still a good idea IMHO.

**Comment by cvrebert** [comment]
@cervengoc Feel free to send a pull request for that.

**Comment by cvrebert** [comment]
@Samlv9 I'm still reasonably sure that your code will lead to flickering. If the scrollbar is visible, simply forcibly removing the scrollbar (like in your code) may make the viewport wider (by the width of the scrollbar), causing a reflow/rerender of the page; and then the reverse happens when the `hide-scrollbar` class is removed.

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 7:42 AM, "Chris Rebert" <notifications@github.com> wrote:
>>
>> scrollbar width is needed in more places
>
> Hmm? I'm pretty sure Modal is our only widget that cares about the width
of the scrollbar.

**Comment by clarkdemvher** [comment]
On Jun 16, 2015 11:28 PM, "cervengoc" <notifications@github.com> wrote:
>
> I don't think there is anyithing wrong with the temporary DIV solution,
it shouldn't cause too much performance overhead. However, creating it all
the time is kind of a waste IMHO, could be nice to cache it into some
utility variable. What do you think?
