### ISSUE TITLE
textarea shrinked despite setting rows inside a form-horizontal > form-group form-group-lg

### ISSUE THREAD

**Issue by aldoluciano** [twbs/bootstrap#16590]
#13989 resurrected.

**Comment by mdo** [comment]
No longer an issue in `master` and in our next release, v3.3.5.

**Comment by aldoluciano** [comment]
sorry about my poor search skills.

**Comment by mdo** [comment]
Don't think it was a search problem :). We redid a bunch of that code a few times over in the last couple releases to try to fix some other problems. Finally got it all right for our next one.
