### ISSUE TITLE
like col mediaqueries, make text align mediaqueries to show correct alignment

### ISSUE THREAD

**Issue by vdeapps** [twbs/bootstrap#16601]
Hi.

I use in my interface labels with 'text-right' class to align right label and control to left.
When I resize my window to XS size, my align text label is set to right but for this screen size I want to align to left.

Can you add, like col-xs, col.sm, ... a class like:
text-right-xs, text-right-sm, ....
text-center-xs, text-center-sm, ...
... 

And my code will be: <label class="text-left-xs text-right-sm">TEST</label>

So when I resize my screen the good align will be selected.

Thanks.

**Comment by mdo** [comment]
There have been requests for this already—we won't be doing it. At least not in v3.

**Comment by cvrebert** [comment]
Duplicate of #11292.
