### ISSUE TITLE
Cannot get forms in modal dialogs to SUBMIT

### ISSUE THREAD

**Issue by unpocoloco** [twbs/bootstrap#16609]
I'm trying to use Bootstrap large modals as form containers. When you click the Add New Degree Code or click on the edit (pencil) icon, the modal is shown and, in the case of editing, the fields are populated with the correct values from that degree's line. All that works perfectly, but the form won't submit. 

Here is my event handler for the SUBMIT button:

```javascript
$( '#DEGREE_FORM' ).submit( function() {
	$( '#DEGREE_ENTRY' ).modal( 'hide' );	
	return submitEventHandler();
	});
```
The submitEventHandler() function is tested and debugged code used elsewhere in the site — outside of modals — to ensure that all required fields have values before allowing a form submission.

When I click the SUBMIT button, the modal does not dismiss and the form does not submit. Is this a bug in your code or mine? If mine, have you any suggested remedies?

![modal screenshot](https://cloud.githubusercontent.com/assets/4976640/8066536/00c7995c-0e9d-11e5-9253-7e520f2e4acc.png)

**Comment by patrickhlauke** [comment]
As per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker I'd suggest posting this personal support request to StackOverflow or similar.
