### ISSUE TITLE
Basic Code Blocks with Toggles

### ISSUE THREAD

**Issue by ViccAlexander** [twbs/bootstrap#16602]
It would be awesome to see support for basic code blocks with toggles. This would be incredibly useful when needing to display a code sample in multiple programming languages (Which happens quite often).

Here's a visual example (from Parse) of what I mean:

![Code Block With Toggles (Image from parse.com)](https://cloud.githubusercontent.com/assets/1724674/8031577/55f8f836-0d84-11e5-801f-fab19b5a07f7.png)

**Comment by kkirsche** [comment]
New features aren't something which would be coming to V3 to allow the core team to focus on V4 development as it gets prepared for it's beta. Potentially something for V4 though :smiley: Core team would have to say for sure though if it was a feature they planned to add.

**Comment by mdo** [comment]
Hey there,

To help keep us focused on the next major release, v4, we’re no longer adding new features to v3. Features we know we want to tackle in v4—or a subsequent release—will be added to our internal tracking list. That list will be shared with our first alpha. Until then, hold tight!

Thanks!

**Comment by mdo** [comment]
Moreover, this doesn't seem like something we need to solve and is probably specific to whatever code snippet tooling you're using.
