### ISSUE TITLE
Modal hidden event

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#16604]
Not sure what I'm doing wrong here, have managed to turn my issue into a simple example of what is going wrong at:

http://www.bootply.com/BzXT9pgtO7

Basically I'm trying to get it so that when a modal closes the hidden.bs.modal event sends the focus back to an input box on the page. I'm sure I've had this working before but cannot work out where I have gone wrong.

If I tell the hidden event to instead just put a value into the input box it shows up, I just can't get it to focus, I'm thinking it's a timing issue but then that's why I'm using the 'hidden' event as opposed to the 'hide' event.

**Comment by twbs-lmvtfy** [comment]
Hi @ray73864!

You appear to have posted a live example (http://s.bootply.com/render/BzXT9pgtO7), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 71, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ray73864** [comment]
Revised example using Bootstrap 3.3.4 same issue:

http://www.bootply.com/c7GmgLZx5H

**Comment by kkirsche** [comment]
Wrapping it in a `setTimeout` with a time of 1 fixes it.

```js
setTimeout(function() {
    $("#txtInput").focus();
  }, 1);
```

See: http://www.bootply.com/hsCP97LMhZ

**Comment by ray73864** [comment]
Hrmm, kind of wanted to avoid using a setTimeout, but if that is the only way then so be it.

**Comment by kkirsche** [comment]
Understandable. I'm not sure it's the only way, but it seems to work to fix the issue even if you set a 0ms delay. For that reason you shouldn't actually slow down the application in any noticeable manner because you aren't actually delaying it.

**Comment by cvrebert** [comment]
For accessibility reasons, after hiding a modal, we refocus the button that was used to trigger the showing of the modal (see https://github.com/twbs/bootstrap/blob/6e8df2ba581accbbd267ce649d2fb24a7440ccef/js/modal.js#L331 ).
I will make a note that we should try to better accommodate cases like yours in Bootstrap v4. For v3, short of modifying `modal.js`, I think only somewhat-hacky solutions are available.

**Comment by witheej** [comment]
The `setTimeout` workaround unfortunately does not solve the problem of IE throwing an error when it tries to refocus on an SVG that was clicked to trigger the modal (I'm using IE 11). 

See: https://github.com/davidtheclark/focus-trap-react/issues/18
