### ISSUE TITLE
multiple modal opening bug

### ISSUE THREAD

**Issue by linxixuan** [twbs/bootstrap#16619]
Sometimes we may open multiple modals in one page. When a modal hide, another modal can't fixed to screen. I think this bug maybe caused by this：
```
 When a modal hide, bootstrap will remove class `modal-open` of body.
```
We should fix this by counting opening modal number. If the number is equal to zero we should remove class `modal-open` of body.

Now I use code like below to handle this bug:
```javascript

 $('.modal').on('hidden.bs.modal', function () {
     if ($('.modal').hasClass('in')) {
          $('body').addClass('modal-open');
    }
 });
```

**Comment by patrickhlauke** [comment]
Multiple modals are explicitly not supported in Bootstrap, I'm afraid.
http://getbootstrap.com/javascript/#modals
