### ISSUE TITLE
inside the column creates a row

### ISSUE THREAD

**Issue by manojb05** [twbs/bootstrap#16612]
Hi, 

I am created a 4 col "col-sm-2, col-sm-2, col-sm-2, col-sm-6".
How can i create a 3 rows inside the "col-sm-6". 
Code is given below  

<div class="row">
    <div class="col-sm-2" style="background-color:lavender;">.col-sm-2</div>
    <div class="col-sm-2" style="background-color:lavenderblush;">.col-sm-2</div>
    <div class="col-sm-2" style="background-color:lavender;">.col-sm-2</div>
 	<div class="col-sm-6" style="background-color:lavender;">.col-sm-6</div>
  </div>

**Comment by cvrebert** [comment]
Closing for the same reason as https://github.com/twbs/bootstrap/issues/16611#issuecomment-110604607
