### ISSUE TITLE
Inside column make a 3 Rows

### ISSUE THREAD

**Issue by manojb05** [twbs/bootstrap#16611]
Hi,

my basic layout rows & column structure is given below

<div class="row">
    <div class="col-sm-2" style="background-color:lavender;">.col-sm-2</div>
    <div class="col-sm-2" style="background-color:lavenderblush;">.col-sm-2</div>
    <div class="col-sm-2" style="background-color:lavender;">.col-sm-2</div>
 <div class="col-sm-6" style="background-color:lavender;">.col-sm-6</div>
  </div>

How can i make "col-sm-6".... 3ROWS please help for the same

**Comment by cvrebert** [comment]
This issue tracker is for bugs and feature requests only. Please direct how-to questions to StackOverflow (or similar) instead. Thanks!
