### ISSUE TITLE
'a {' should not have color if it is not link 

### ISSUE THREAD

**Issue by ChameleonRed** [twbs/bootstrap#16615]
`<a>Something</a>` should not have color since it is not link
`<a href="something">Something</a>` should have color @link-color

Please add style for a:link not a since it is different - user see underline and color but can not click in such empty links - it wrong assumption that <a> must always point something.

Replace this code  `bootstrap/less/scaffolding.less`:
```
// Links

a {
  color: @link-color;
  text-decoration: none;

  &:hover,
  &:focus {
    color: @link-hover-color;
    text-decoration: @link-hover-decoration;
  }

  &:focus {
    .tab-focus();
  }
}
```
With:
```
// Links

a {
  color: inherit;
  text-decoration: none;
  
  &:link {
    color: @link-color;
    text-decoration: none;
  }
  &:hover,
  &:focus {
    color: @link-hover-color;
    text-decoration: @link-hover-decoration;
  }

  &:focus {
    .tab-focus();
  }
}
```

My code is not tested - not learned .less but I think it will lead you to solution :)

**Comment by ChameleonRed** [comment]
I found better solution:

http://www.w3schools.com/tags/tag_a.asp

```
a:link, a:visited {
    color: (internal value);
    text-decoration: underline;
    cursor: auto;
}

a:link:active, a:visited:active {
    color: (internal value);
} 
```

Maybe code should replaced with `a` -> `a:link`:
```
// Links

a:link {
  color: @link-color;
  text-decoration: none;

  &:hover,
  &:focus {
    color: @link-hover-color;
    text-decoration: @link-hover-decoration;
  }

  &:focus {
    .tab-focus();
  }
}
```

**Comment by ChameleonRed** [comment]
Valid code - tested is:
a:link {
  color: #2b6598;
  text-decoration: none;
}
a:link:hover,
a:link:focus {
  color: #1a3d5c;
  text-decoration: underline;
}
a:linl:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}

**Comment by mdo** [comment]
We're not going to change this—doing so would require updating every instance of a link to override that `:link` state. For example: https://jsbin.com/yopeji/1/.

**Comment by twbs-lmvtfy** [comment]
Hi @mdo!

You appear to have posted a live example (https://jsbin.com/yopeji/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
@mdo 

> doing so would require updating every instance of a link to override that `:link` state

not quite sure I follow here. If the change was (I believe more accurately)

```
a {
  color: @link-color;
  text-decoration: none;

  &:link {
    color: @link-color;

    &:hover,
    &:focus {
      color: @link-hover-color;
      text-decoration: @link-hover-decoration;
    }

    &:focus {
      .tab-focus();
    }
  }
}
```

what would the negative impact be?

**Comment by kkirsche** [comment]
Wouldn't that still cause the original issue of non-link anchor tags being colored?

I think the first color would be inherit though I could have misunderstood you Patrick.

I also don't follow mdo's comment

**Comment by patrickhlauke** [comment]
duh, my mistake, a copy/pasta error in my code. amended...

**Comment by ChameleonRed** [comment]
@patrickhlauke I looks that you solution is valid - see this is my code patching bootstrap because @mdo lack of response - BTW see that `:visited` should be also supported not skipped. Your solution looks good whatever I do not understand .less syntax so only imagine how it works.

```
/* fix bootstrap problems */
a {
  color: inherit;
  text-decoration: none;
}
a:hover,
a:focus {
  color: inherit;
  text-decoration: none;
}
a:focus {
  outline: none;
}

a:link, a:visited {
  color: #2b6598;
  text-decoration: none;
}
a:link:hover,
a:link:focus {
  color: #1a3d5c;
  text-decoration: underline;
}
a:link:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
```
See that FireFox has problem with `:visited`!
All shows that link should be blue but is black:
https://www.dropbox.com/s/ygiasz5iau1wqcu/Zrzut%20ekranu%202015-06-10%2021.15.38.png?dl=0
https://www.dropbox.com/s/jg55odfkgo12fu4/Zrzut%20ekranu%202015-06-10%2021.16.30.png?dl=0

I was reported bug - not only bootstrap has bug :)
https://bugzilla.mozilla.org/show_bug.cgi?id=1173505

**Comment by ChameleonRed** [comment]
@patrickhlauke @kkirsche @mdo Maybe code should such if `a:focus, a:hover` should be reseted - I am not tested only `:visited` ...

```
a {
  text-decoration: none;

  &:hover,
  &:focus {
    color: inherit;
    text-decoration: none;
  }

	a:link {
	  color: @link-color;
	  text-decoration: none;
	
	  &:hover,
	  &:focus {
	    color: @link-hover-color;
	    text-decoration: @link-hover-decoration;
	  }
	  
	  &:visited {
	  	color: @link-color;
	  }
	
	  &:focus {
	    .tab-focus();
	  }
	}
} 
```

**Comment by patrickhlauke** [comment]
adding `:visited` ...

```
a {
  color: inherit;
  text-decoration: none;

  &:link,
  &:visited {
    color: @link-color;

    &:hover,
    &:focus {
      color: @link-hover-color;
      text-decoration: @link-hover-decoration;
    }

    &:focus {
      .tab-focus();
    }
  }
}
```

now, whether we add this to version 3, or hold off until version 4, will be something for @mdo to decide.

**Comment by ChameleonRed** [comment]
I prefer to use it in version 3 to avoid monkey patching @patrickhlauke @mdo :)

Thank @patrickhlauke for `:visited` suggestion I try it against FF.

**Comment by ChameleonRed** [comment]
This works in firefox and correct Firefox bug! - next monkey patching - magic!
https://bugzilla.mozilla.org/show_bug.cgi?id=1173505 @patrickhlauke  @kkirsche @mdo

Thank @patrickhlauke for great help!

```
/* fix bootstrap problems */
a {
  color: inherit;
  text-decoration: none;
}
a:hover,
a:focus {
  color: inherit;
  text-decoration: none;
}
a:focus {
  outline: none;
}

a:link, a:visited {
  color: #2b6598;
  text-decoration: none;
}
a:link:hover,
a:link:focus {
  color: #1a3d5c;
  text-decoration: underline;
}
a:link:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
a:visited:hover,
a:visited:focus {
  color: #1a3d5c;
  text-decoration: underline;
}
a:visited:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
```

**Comment by ChameleonRed** [comment]
It looks also that there is bug in Chrome and different bug in FF (still bug but not in render) - console report blue from `:link` and shows computed blue value but should be black - looks that every programmer has problem with power of  WEB LINKS :)

https://bugzilla.mozilla.org/show_bug.cgi?id=1173505

**Comment by mdo** [comment]
I should have clarified more in both threads—the use of `:link` is **more specific** than a single class. From a design system approach, that's unacceptable.

Changing our approach to styling links from `a` to `a:link, a:visited` means a single class can no longer override the `a { }` selector. Most of our components would actually be okay in v3—e.g., `.nav > li > a` is more specific than `a:link` and `a:visited`. However, anything that's just a class—which is the case in v4—would be broken.

See an updated example at https://jsbin.com/yopeji/2/ of what I mean.

Lastly, you can accomplish this without rewriting Bootstrap's base styles by using the `:not` pseudo class. See https://jsbin.com/kofadu/1/ for an example.

**Comment by twbs-lmvtfy** [comment]
Hi @mdo!

You appear to have posted a live example (https://jsbin.com/yopeji/2/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @mdo!

You appear to have posted a live example (https://jsbin.com/kofadu/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
@mdo ... sorry to drag this on, but in that case: good to try and add a `:not` based patch?

**Comment by mdo** [comment]
I'm not against it, but I don't think we'll tackle it as part of v3. It'd be a new feature and a slight behavioral change for anyone not expecting this. Possibly for v4, but I don't think the use case is all that wide spread.

**Comment by patrickhlauke** [comment]
:+1: for v4 (though arguably, if the use case is small, the behavioral change would go mostly unnoticed)
