### ISSUE TITLE
Tooltip causing buttons to jump

### ISSUE THREAD

**Issue by tchoulihan** [twbs/bootstrap#16624]
Using tooltip, I noticed my buttons kept moving slightly on the screen.
` $('[data-toggle="tooltip"]').tooltip();`

Looking up on stackoverflow, I found the fix was this:
`$('[data-toggle="tooltip"]').tooltip({container: 'body'});`

Tooltip should probably default to that setting, to avoid problems for other people in the future.

From: http://stackoverflow.com/questions/14364079/bootstrap-tooltip-causing-buttons-to-jump

**Comment by mdo** [comment]
There's more history to that change and why it defaults to the immediate parent over the body. Suffice to say, we won't be changing that in v3 (backward compatibility) and likely won't for v4.
