### ISSUE TITLE
tooltip popup misaligned 

### ISSUE THREAD

**Issue by keithbmcd** [twbs/bootstrap#16626]
Hi,

We have a question about how to fix misaligned tooltip popup

test url - http://www.southernature.com.au/product/bilberry-vision-defence-12000

1. go to Product Certifications
2. expand the browser
3. hover Vegan Friendly
4. you will see the popup is moved to left

Thanks for your time. Hope that we can fix it

Cheers

Keith

**Comment by patrickhlauke** [comment]
As per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker you should post personal support requests to StackOverflow or similar. FWIW though, I can't reproduce any problem in Chrome, Firefox nor IE11 in Win.

**Comment by cvrebert** [comment]
Possible duplicate of #12799.
