### ISSUE TITLE
Modal box getting hide in Chrome browser

### ISSUE THREAD

**Issue by venkatesh-r** [twbs/bootstrap#16627]
Modal box getting hide in chrome browser, But its working in mozilla and IE.

**Comment by patrickhlauke** [comment]
You'll need to file an example, ideally a reduced test case showing the problem in isolation. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker - but generally, modals work just fine in Chrome, so it's likely an issue with your specific implementation.

**Comment by venkatesh-r** [comment]
![issue](https://cloud.githubusercontent.com/assets/8782150/8125635/f5f0e28a-1104-11e5-9a15-e6f862f30396.png)

Please check this screenshot for reference.

**Comment by patrickhlauke** [comment]
Suggest you post your request for support on StackOverflow. As a general piece of advice: posting a screenshot isn't helpful...people need to actually see your code.
