### ISSUE TITLE
What invokes Bootstrap overrides.css?

### ISSUE THREAD

**Issue by vinceroni** [twbs/bootstrap#16629]
I have a purchased theme [theme1] that I've cloned, to which Bootstrap is set as the base theme.
I've done the standard rebranding procedure of renaming all of the files and functions to match the new theme name [theme2].
It's mostly working, except that /themes/bootstrap/css/overrides.css is loading in theme2, and its causing a few issues.

Overrides.css doesn't load in the original theme1, and everything is fine.

It doesn't seem to matter if CDN is on or off.

What invokes Bootstrap overrides.css?

Any thoughts?

**Comment by patrickhlauke** [comment]
There is no "overrides.css" in Bootstrap, so I suggest you contact whoever you purchased your theme from (as this project also doesn't sell you themes).
