### ISSUE TITLE
Doesn't work well for half screens

### ISSUE THREAD

**Issue by tautology0** [twbs/bootstrap#16621]
I mostly use a web browser taking up half the screen of my 1980x1080 resolution, as 1980 tends to be too large to be comfortable, but this messes up on a lot of websites which use bootstrap as it gets forced into the small or even the mobile interface.

As the size (990px) is just shy of the boundary between the small and medium column factor, this results in pages where 25% of the screen horizontal space is taken up with white space and potentially causes content to flow in an ugly fashion etc.

This seems very wasteful for what must be a common use case (i.e. use a standard 24" or 27" monitor or gaming laptop and drag the web browser in the right/left margins for it to take up half the screen).

So, can we have a reduction in size of the lower boundary of the medium column sizes by about 10 pixels (to 982px), or some exception made for this use case?

**Comment by mdo** [comment]
Afraid not—we can't change that stuff at this point for v3. Versioning and backward compatibility wouldn't allow for that. You can customize those values and more though if you're dealing with a custom site and not just our docs.

**Comment by tautology0** [comment]
I think you've misinterpreted my request: I'm asking as a user of sites that use the library not as a developer (I prefer to roll my own CSS when I do web design). I have not option to alter the pixel sizes.

Rather than just closing it; can we have it noted as an issue and aim for a possible fix in later versions of the library?

This is still a usability issue: it really mankifies a lot of websites with bad flows and moving around of content over a two pixel difference.
