### ISSUE TITLE
Bootstrap 3 Pagination sm renders default

### ISSUE THREAD

**Issue by Hozey** [twbs/bootstrap#16639]
Applying pagination pagination-sm  in Bootstrap 3.3.4 renders the default size. There is nothing in the custom css file to override bootstrap pagination. What's wrong? Thanks for any help.

**Comment by kkirsche** [comment]
Could you post a JSBin or JSFiddle demonstrating the problem so we can assist you per the issue tracker guidelines?

**Comment by Hozey** [comment]
<ul class="pagination pagination-sm"> renders <ul class="pagination">

**Comment by kkirsche** [comment]
First, please wrap code in ```. Second, as originally requested please post a JSBin or JSFiddle demonstrating the problem, not code which we must setup ourselves.

**Comment by patrickhlauke** [comment]
As http://getbootstrap.com/components/#sizing shows that `.pagination-sm` does, in fact, work, this sound like you're doing something else in your page (i.e. it's not a Bootstrap bug, but likely a problem with how you use it). As such, I'd say its best to ask on StackOverflow or similar, as per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
