### ISSUE TITLE
Bad metrics of glyphicons font

### ISSUE THREAD

**Issue by puzrin** [twbs/bootstrap#16633]
I don't know is it intentional or not, but current glyphicons goes out of string bottom line, and that's a not expected way of font use. For example, icons looks shifted up, and not combine-able with another sources. How to check:

1. Open ttf or svg in fontdorge, then open any glyph and see horizontal rulers
2. Import svg to fontello, and see that result is shifted to top

Probably, icons should be shifted 240 down, OR descent should be set to 0.

__Quick hack for SVG:__

Replace

```
<font-face units-per-em="1200" ascent="960" descent="-240" />
```

with

```
<font-face units-per-em="1200" ascent="1200" descent="0" />
```

**Comment by kkirsche** [comment]
The [Glyphicons](http://glyphicons.com/) are an external project that we just package/bundle.
Please direct icon suggestions to the Glyphicons' author. Thanks!

**Comment by puzrin** [comment]
@kkirsche that's NOT icons suggestion. That's font format bug report. Icons are probably ok, but font metrics are bad.

**Comment by kkirsche** [comment]
We don't build them or anything so the statement still stands. All we do is package the fonts provided to us by their author. Your statement isn't something we could fix, that is a bug or suggestion for their author.

**Comment by puzrin** [comment]
@kkirsche , sorry, i've updated reply in the same time you posted your one.

Problem is that Glyphicons is not "normal" opensource project, and bootstrap is the last place where this problem can be reported/tracked. Glyphicon's website does not have tracker and provides vectors only for money with custom license.

I think it would be convenient for all to keep issue open here, until fixed.

**Comment by kkirsche** [comment]
Well, I'm not sure. V3 isn't the main focus due to V4 development and V4 removed Glyphicons entirely so I'm not sure the core team will want to keep this open as we can't fix it and it's a portion which will be gone in the next release.

**Comment by puzrin** [comment]
@kkirsche I didn't knew that v4 removed Glyphicons. If bootstrap will stop distributing font with bad metrics by compleete font removal, i see no reasons to keep this issue open.

Thanks for your explanations!
