### ISSUE TITLE
Docs falsely claim "not-allowed" cursor for labels inside fieldset.disabled

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#16630]
From http://getbootstrap.com/css/#checkboxes-and-radios:
> To have the <label> for the checkbox or radio also display a "not-allowed" cursor when the user hovers over the label, **add the .disabled class to** your .radio, .radio-inline, .checkbox, .checkbox-inline, or **&lt;fieldset>**

(bold highlighting by me)

Either the doc is wrong or the theme is missing something but adding the disabled class to an encompassing fieldset makes no difference.

Testcase with comparison to the other methods leading to the wanted result: http://jsbin.com/kacawu/3/edit?html,output (Bootlint and HTML validator passed).

**Comment by cvrebert** [comment]
In the `fieldset` case, it should be the `disabled` *attribute*, as opposed to the `disabled` *class*; see https://github.com/twbs/bootstrap/blob/5a8d0143b3fa9de883a5672d4a1f44d472657a8a/less/forms.less#L262

**Comment by Herst** [comment]
@cvrebert Yes, but there are caveats as mentioned at http://getbootstrap.com/css/#forms-disabled-fieldsets

**Comment by cvrebert** [comment]
To further clarify, the `disabled` class has never been meant to be used on `<fieldset>`s.

**Comment by Herst** [comment]
OK, I just thought it might be useful for cross-browser compatibility.

In any case if you plan on mentioning the disabled attribute on fieldsets in the checkbox section of the docs maybe link then to the fieldset-disabled section as well so that people who might not read the whole manual are aware of possible issues when using that approach.

**Comment by patrickhlauke** [comment]
So unless I'm missing something, this is a simple case of the docs needing a tweak, right? Rather than the CSS?

**Comment by cvrebert** [comment]
@patrickhlauke Correct.
