### ISSUE TITLE
Bootstrap 3.3.0 modal bug

### ISSUE THREAD

**Issue by crystal13282** [twbs/bootstrap#16637]
Hello,

I'm new on bootstrap and I found a modal bug: when I press the modal button, the background goes right of 15px about. My bootstrap template is 3.3.0 version.
I tried more possible solutions on GitHub but none of these works for me, so I open this topic. Probably I wrong anything!

Please, can you tell me what files I have to modify and what parameters I have to change?

Thank you in advance to all!
Gianfranco

**Comment by walutisme** [comment]
Before any contributor tell you, update your version to latest (3.3.4). JSbin maybe needed.

Sorry my bad english

**Comment by crystal13282** [comment]
Hello,

I also tried the upgrade to version 3.3.4 but doesn't work. Probably I wrong the upgrade procedures....
Can you tell me what files I have to substitute for the upgrade?

Thank you for your help!
Gianfranco

**Comment by cvrebert** [comment]
Please follow our issue tracker policies and bug reporting guidelines in the future:
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

How-to questions like "how to upgrade?" should be asked on [StackOverflow](stackoverflow.com/questions/tagged/twitter-bootstrap-3) instead on this issue tracker.
Bug reports should include a simplified, reproducible test case demonstrating the problem, preferably as a JS Bin or JS Fiddle.

Thanks, and good luck!
