### ISSUE TITLE
Modal toggled in other modal - can't scroll modal

### ISSUE THREAD

**Issue by Samuell95** [twbs/bootstrap#16631]
Hello,
i created modal and inside modal create button to open second modal + close first but problem is scrollbar doesn't work for second modal but work for page

How to fix it?

**Comment by patrickhlauke** [comment]
multiple modals are not supported in bootstrap. please refer to StackOverflow or similar for possible workarounds. https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by cvrebert** [comment]
> multiple modals are not supported in bootstrap.

Specifically, see http://getbootstrap.com/javascript/#callout-stacked-modals
