### ISSUE TITLE
Anchor tag stop working with list tag

### ISSUE THREAD

**Issue by sachin026** [twbs/bootstrap#16638]
As soon as the size of the window decreases to mobile view then the anchor tag with ist tag stops working

**Comment by cvrebert** [comment]
@sachin026 Bug reports require a reduced test case which demonstrates the problem; see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports for details.

**Comment by mdo** [comment]
This doesn't sound like a bug—more like an implementation problem. Closing for now and nuking the awaiting reply label.

**Comment by DevSachinGupta** [comment]
Thank you all
