### ISSUE TITLE
Bug with pagination in chrome

### ISSUE THREAD

**Issue by evilebottnawi** [twbs/bootstrap#16646]
![pagination-bug](https://cloud.githubusercontent.com/assets/4567934/8190567/fe66da22-146b-11e5-8c46-019b8a992245.png)
![pagination-bug1](https://cloud.githubusercontent.com/assets/4567934/8190568/fe692d7c-146b-11e5-9a67-f1a4082f5651.png)

**Comment by evilebottnawi** [comment]
problem with z-index in focus selector

**Comment by patrickhlauke** [comment]
suggest that an active and hovered/focused pagination link should get a treatment similar to https://github.com/twbs/bootstrap/pull/16154 ?

**Comment by mdo** [comment]
@patrickhlauke That's different—the problem here is definitely just `z-index`.

**Comment by patrickhlauke** [comment]
oh i understand, but wondering if, as part of fixing it, we can consider this as well?

**Comment by mdo** [comment]
Maybe? The buttons make a lot more sense because when they're active they can still be toggled. Active states here don't get toggled ever really—one link is generally always going to be active.

**Comment by patrickhlauke** [comment]
Perhaps overthinking it...will see once a fix for the original issue lands (thinking mainly keyboard users here, who will end up focusing on an active pagination link and wouldn't get the "focused AND active" visual indication). not a big concern though.
