### ISSUE TITLE
Modals and dropdowns not appearing on Windows phone [OS 8.1]

### ISSUE THREAD

**Issue by KPlanche** [twbs/bootstrap#16640]
I'm creating a website which uses modals and dropdown menus as necessary parts of the layout. My company is in the process of onboarding more users to our service and many of those users are using Windows devices (i.e. Nokia Lumia, HTC, etc) with Windows 8.1 OS and Internet Explorer as their mobile browser.

However, the modals and dropdowns provided by Bootstrap 3 do not work on these devices. The buttons these elements are connected to are still visible and clickable but nothing happens when clicked. The modals and dropdowns do not appear (the screen does not change at all). The code I have (basic modals and dropdowns with only css styling added) works on all other browsers and major mobile devices.

Also seeing this issue in the Bootstrap docs with modals and dropdowns when viewed on a Windows phone.

I've done my testing on a Nokia Lumia 635 using "Windows Phone 8.1" software (OS version 8.10.12397.895).

Example of project and issue can be found here: http://secondpop.com/kristine/web-app/menu2.html
- Restaurant menu items are connected to a modal
- Dropdowns are part of the top nav

**Comment by patrickhlauke** [comment]
I unfortunately don't have a WinPhone 8.1 device handy (upgraded mine to Win 10 for Phones preview recently), but I don't recall experiencing any problems relating to dropdowns, at least. Just to be safe, can you double-check that your code has no issues by running it against Bootlint? https://github.com/twbs/bootlint#in-the-browser

**Comment by patrickhlauke** [comment]
ah, just seen this bit

> Also seeing this issue in the Bootstrap docs with modals and dropdowns when viewed on a Windows phone.

ok, if even the docs are affected, there's something fishy going on with WinPhone 8.1/IE...

**Comment by KPlanche** [comment]
I didn't know about Bootlint. Very cool! I ran it on the example page and it found some issues. Will fix those and get back to you to see if this might help. @fat or @mdo , do you think this will be fixed soon in future version pushes?

**Comment by patrickhlauke** [comment]
first we'll need to actually verify the problem. but in principle, if it's a bug, we'll aim to fix it...

**Comment by patrickhlauke** [comment]
FWIW can't reproduce on a freshly flashed Nokia Lumia 520 with Windows Phone 8.1 and IE11 (neither on the Bootstrap docs, nor on http://secondpop.com/kristine/web-app/menu2.html).

![wp_ss_20150615_0007](https://cloud.githubusercontent.com/assets/895831/8170300/bc4040e4-13a7-11e5-908e-d0cbfcafc14d.png)
![wp_ss_20150615_0008](https://cloud.githubusercontent.com/assets/895831/8170302/bc4134d6-13a7-11e5-858f-0b43bca5e197.png)
![wp_ss_20150615_0009](https://cloud.githubusercontent.com/assets/895831/8170299/bc4017ea-13a7-11e5-9035-58a12a7bac53.png)
![wp_ss_20150615_0010](https://cloud.githubusercontent.com/assets/895831/8170301/bc40d77a-13a7-11e5-829e-0668b2dcbfc9.png)
![wp_ss_20150615_0011](https://cloud.githubusercontent.com/assets/895831/8170298/bc3f472a-13a7-11e5-92f7-153ee767ebe8.png)

**Comment by KPlanche** [comment]
Very, very strange.... In theory, should be working on mine as well (still not). Could it be the phone model causing issues since our IE settings are basically the same? 
![img_4319](https://cloud.githubusercontent.com/assets/8492572/8170992/9bef2212-1382-11e5-9190-369530fcc0e1.JPG)

**Comment by KPlanche** [comment]
@patrickhlauke I did a factory reset on the phone and now the drop downs and modals are working perfectly! Could it have been a cache issue causing this? Thanks for your help!

**Comment by patrickhlauke** [comment]
weird, but glad it sorted itself out :)
