### ISSUE TITLE
Problem with static modal backdrop height

### ISSUE THREAD

**Issue by idleberg** [twbs/bootstrap#16642]
I'm using JavaScript to inject content into modal. I have noticed that when the content extends the height of the browser window and I scroll down, the backdrop will end at the edge of the portion that's initially visible.

![screen shot 2015-06-15 at 21 21 39](https://cloud.githubusercontent.com/assets/1504938/8168744/629318c0-13a5-11e5-98bc-5b210bedb4cd.png)

The `modal-backdrop` is set to a static height, which matched the initial document height.

I'm not sure if this can even be considered a bug, since this is clearly caused by my content injection and works fine with static modals. Anyway, I thought I'd share this behaviour.

This is a quick fix…

    .modal-backdrop.in {
      position: fixed;
    }

…but on the downside, one can only scroll when down when the cursor is positioned over the modal

**Comment by kkirsche** [comment]
This if I remember needs `handleUpdate` to be done to update the height though I could be wrong. 

I thought this was fixed though unless that commit was reverted. cc: @hnrch02

**Comment by cvrebert** [comment]
What version of Bootstrap are you using?

**Comment by idleberg** [comment]
@cvrebert 3.3.4

@kkirsche Thanks, that was helpful. I guess this can be marked a duplicate then (#15483)

**Comment by idleberg** [comment]
Ah, I'm sorry but I was certain I had the latest version running. 3.3.4 works fine!
