### ISSUE TITLE
getbootstrap.com is returning a 404

### ISSUE THREAD

**Issue by ally** [twbs/bootstrap#16645]

**Comment by thegrtman** [comment]
+1

**Comment by Getz85** [comment]
Indeed.
If you need to access the documentation,  you can check: https://bootstrapdocs.com/v3.2.0/docs/ or offline doc: https://github.com/AAlakkad/Bootstrap-3-Offline-Docs

**Comment by kkirsche** [comment]
Confirmed.

**Comment by kkirsche** [comment]
Mdo is currently deploying an update (per slack)

**Comment by frewsxcv** [comment]
https://twitter.com/getbootstrap/status/610851216478703617

**Comment by frewsxcv** [comment]
It's back up now. This can probably be closed.
