### ISSUE TITLE
getbootstrap.com deployed missing asset

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#16647]
Check console to see this (ignore the other 6 in my console they are from a stupid extension that needs to be removed):
http://getbootstrap.com/assets/js/vendor/holder.min.js Failed to load resource: the server responded with a status of 404 (Not Found) 

![screen shot 2015-06-16 at 3 37 53 pm](https://cloud.githubusercontent.com/assets/947110/8192663/b25ce23a-143d-11e5-9cf3-fc068ccd7ba4.png)

**Comment by mdo** [comment]
Ah, yes, we didn't run our Gruntfile correctly in our haste to figure out why the site was down earlier. On it.

**Comment by mdo** [comment]
All fixed now. Thanks!

**Comment by kkirsche** [comment]
Anytime. :)

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 4:01 AM, "Mark Otto" <notifications@github.com> wrote:
>
> Ah, yes, we didn't run our Gruntfile correctly in our haste to figure out
why the site was down earlier. On it.
