### ISSUE TITLE
How to make bootstrap models open when I website page load (automatically)

### ISSUE THREAD

**Issue by manojb05** [twbs/bootstrap#16643]
I'm trying to launch a Bootstrap modal on page load without firing a HTML button or using jQuery.

**Comment by FabianKoestring** [comment]
I would say: "No way without js"!

**Comment by patrickhlauke** [comment]
As per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker please post these sorts of personal support requests to StackOverflow or similar
