### ISSUE TITLE
Bower.json main file is not complete 

### ISSUE THREAD

**Issue by charlesmudy** [twbs/bootstrap#16650]
On "version": "3.3.4", the main setup is like this:

````````````````
  "main": [
    "less/bootstrap.less",
    "dist/css/bootstrap.css",
    "dist/js/bootstrap.js",
    "dist/fonts/glyphicons-halflings-regular.eot",
    "dist/fonts/glyphicons-halflings-regular.svg",
    "dist/fonts/glyphicons-halflings-regular.ttf",
    "dist/fonts/glyphicons-halflings-regular.woff",
    "dist/fonts/glyphicons-halflings-regular.woff2"
  ],
````````````````

But with the new update "version": "3.3.5", this is what we have:

````````````````
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
````````````````

Any reason why? because it affects the way I load the files using gulp (main-bower-files). I mean after adding the first main to my root bower.json, everything is fine. Just wondering why

**Comment by kkirsche** [comment]
@charlesmudy this is due to bower updating the spec for main. The issue referenced in 3.3.5's release notes:
twbs/bootstrap/16359

**Comment by kkirsche** [comment]
Probably worth just including some of the issue linked to:

See bower/bower.json-spec#43

If you have a complaint about this, my recommendation (and it sounds like the core team's as well) is to take it up with the Bower folks, not us as we didn't decide this:
https://github.com/bower/bower.json-spec/issues
Or consider using a different package manager.

**Comment by cvrebert** [comment]
What @kkirsche said. There is no bug in Bootstrap here.

**Comment by charlesmudy** [comment]
Thanks guys for the clarification :)
