### ISSUE TITLE
labels sometimes not showing on mobile

### ISSUE THREAD

**Issue by hkericb** [twbs/bootstrap#16656]
Everything goes well on desktop browsers but the labels sometimes disappear from page. However, when I add custom inline CSS style "display: initial" to the label tag, the labels show up again with no problem.

Page Fragment:
&lt;div class="panel panel-success"&gt;
  &lt;div class="panel-heading"&gt;
    Order: #1
    &lt;span class="label label-danger"&gt;Pending&lt;/span&gt;
  &lt;/div&gt;
  &lt;div class="panel-body"&gt;
    Content
  &lt;/div&gt;
&lt;/div&gt;

Tested Devices & OS:
Apple iPhone 5s (iOS 8.1.2) - Pass
LG G3 (Android 4.4.2) - Pass
Sony Xperia Z3 dual (Android 4.4.4) - Pass
Sony Xperia Z1 (Android 5.0.2) - Pass
Sony Xperia TX (Android 4.3) - FAIL

P.S. the page is loaded from an in-app webview container.

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 5:57 PM, "hkericb" <notifications@github.com> wrote:
>
> Everything goes well on desktop browsers but the labels sometimes
disappear from page. However, when I add custom inline CSS style "display:
initial" to the label tag, the labels show up again with no problem.

**Comment by cvrebert** [comment]
We don't officially support the Android Browser/WebView.

@hkericb So to clarify, you're only seeing a problem on Android 4.3?

**Comment by mdo** [comment]
I can't think of anything that'd be causing this. Should work fine as demo-ed in https://jsbin.com/xojoku. Closing since it's not a browser we explicitly support and there's no specific example.
