### ISSUE TITLE
Grunt wiredep not updating bower:CSS section

### ISSUE THREAD

**Issue by mlakmal** [twbs/bootstrap#16652]
I have setup my angular app with bootstrap installed through bower install command.has part of grunt wiredep command index.html gets updated with bootstrap.CSS and bootstrap.is path from bower_components folder... After I recently updated bower bootstrap get to 3.3.5. Bower CSS wiredep doesn't pick the bootstrap.CSS path into index.html anymore...

**Comment by cvrebert** [comment]
Sorry, but we can't help you with (grunt-)wiredep stuff.
However, my guess is that you need to update your config to account for #16359.

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 12:02 PM, "mlakmal" <notifications@github.com> wrote:
>
> I have setup my angular app with bootstrap installed through bower
install command.has part of grunt wiredep command index.html gets updated
with bootstrap.CSS and bootstrap.is path from bower_components folder...
After I recently updated bower bootstrap get to 3.3.5. Bower CSS wiredep
doesn't pick the bootstrap.CSS path into index.html anymore...

**Comment by mdo** [comment]
Likely due to the changes to the `main` property in Bower. See #16650.

**Comment by mlakmal** [comment]
Thanks guys for the quick info. i wasn't aware of this change in bower ...

**Comment by mdo** [comment]
More discussion happening in #16663.
