### ISSUE TITLE
@line-height-computed variable

### ISSUE THREAD

**Issue by trollwinner** [twbs/bootstrap#16655]
Hello. I have a question about "@line-height-computed" variable. There are a lot of properties wich have value like 
"(@line-height-computed / 2)" 
or 
"(@line-height-computed * 2)"
in bootstrap. Is there any sense to add variables like 
"@space-base: @line-height-computed; 
@space-large: (@line-height-computed * 2); 
@space-small: (@line-height-computed / 2);" 
and use them anywhere?

**Comment by walutisme** [comment]
Maybe yes. Afaik, on less source its on 20px after computed. Cmiiw

**Comment by kkirsche** [comment]
@walutisme I think the core team is opposed to adding more variables if at all possible, though I'll let them say for sure. If they are interested, I can put together the PR for using variables instead of computations

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 7:30 PM, "Kevin Kirsche" <notifications@github.com> wrote:
>
> @walutisme I think the core team is opposed to adding more variables if
at all possible, though I'll let them say for sure. If they are interested,
I can put together the PR for using variables instead of computations

**Comment by clarkdemvher** [comment]
On Jun 17, 2015 4:42 PM, "trollwinner" <notifications@github.com> wrote:
>
> Hello. I have a question about "@line-height-computed" variable. There
are a lot of properties wich have value like

**Comment by patrickhlauke** [comment]
@clarkdemvher not sure what's going on, but you seem to have some autoresponder active that fires replies back to github notifications which then get posted as comments. can i suggest you check your email settings or whatever, as we're getting lots of noise from you here...

**Comment by walutisme** [comment]
@kkirsche I think computation is okay, it's needed maybe. Take a look at this

```less
//** Unit-less `line-height` for use in components like buttons.
@line-height-base:        1.428571429; // 20/14
//** Computed "line-height" (`font-size` * `line-height`) for use with `margin`, `padding`, etc.
@line-height-computed:    floor((@font-size-base * @line-height-base)); // ~20px
```

**Comment by kkirsche** [comment]
Sorry I guess I wasn't clear -- I wasn't meaning used fixed values but rather set computed values for variables instead of using inline computations as shown in the original comment.

**Comment by cvrebert** [comment]
> I think the core team is opposed to adding more variables if at all possible

mdo has shown opposition in some cases. I don't know about Core Team as a whole though.

**Comment by kkirsche** [comment]
Fair, I don't mean to put words in others mouths. Edited for clarity — sorry about that

**Comment by trollwinner** [comment]
What i trying to say: in design I like to use three kinds of spaces: large (between sections for example), base (between articles) and small (after anything else). Also I usually use the same spaces as padding of coloured blocks with text. It's easier to change three variables than find and change each of them if it needed, am I right? I think it's important ability like changing variables such as "@padding-{base/large/small}-{horizontal/vertical}"

**Comment by walutisme** [comment]
Playing with your own variable would be better. Maybe. Easy to maintain and remember it names

**Comment by trollwinner** [comment]
Yes, it's true. Apparently it's difficult question. It's monster wishing to perfect code, that lives in my head.

**Comment by mdo** [comment]
This kind of stuff is coming in v4, but not v3.
