### ISSUE TITLE
Padding, margin, general classes to introduce

### ISSUE THREAD

**Issue by choros7** [twbs/bootstrap#16667]
Hi
Why not to introduce classes for padding, margin etc to bootstrap? e.g .p-l-30 {
paddin-left: 30px } then class for mobile with media query max like p-l-30-sm {
{padding-left: 30px;} etc... does it make sense?

**Comment by monoblaine** [comment]
For the sake of maintainability, a class name should be [semantic](https://css-tricks.com/semantic-class-names). It should mean something by itself. `.p-l-30` however, has no meaning. If you really feel that you should name it this way, it's probably a sign of [code smell](https://en.wikipedia.org/?title=Code_smell).

**Comment by patrickhlauke** [comment]
I think this would move too far towards "atomic/OOCSS", and would require a fairly major refactoring of all CSS in Bootstrap. Certainly not going to happen in v3, and not quite sure - philosophically at least, but @mdo would know more - if it's something we'd consider for v4.

Personally, I'm not a fan anyway...

**Comment by choros7** [comment]
Please no offence, I'm just beginner developer. My work friend used these classes in that way so I thought its fine and useful. I do not see any problem to add right name for each class. Btw bootstrap has some classes like that e.g pull-right, pull-left, col-xs-12 etc and nobody complain. Thanks for reply

**Comment by walutisme** [comment]
I think set for margin/padding related to playing with some mixin/placeholder/etc library. Bootstrap is CSS framework, even there's some mixin included. So everything is okay.

**Comment by mdo** [comment]
Not happening until v4.
