### ISSUE TITLE
button add class 'disabled' in v3.3.5 not work? 

### ISSUE THREAD

**Issue by Arthas1850** [twbs/bootstrap#16666]
**_v3.3.4_** 

    .btn.disabled, .btn[disabled], fieldset[disabled] .btn {
      pointer-events: none;
      cursor: not-allowed;
      filter: alpha(opacity=65);
      -webkit-box-shadow: none;
      box-shadow: none;
      opacity: .65;
    }

**but in v3.3.5 hasn't**  
    
    pointer-events: none;

**this is why?**

**Comment by walutisme** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

disabled
This Boolean attribute indicates that the user cannot interact with the button. If this attribute is not specified, the button inherits its setting from the containing element, for example <fieldset>; if there is no containing element with the disabled attribute set, then the button is enabled.

**Comment by Arthas1850** [comment]
thanks,I just looked at the 3.3.5 version of the upgrade information, found the relevant explanation, found a lot of wrong in the projects

**Comment by cvrebert** [comment]
See #16092.
