### ISSUE TITLE
French translation of getbootstrap is broken/unstyled

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#16669]
http://www.oneskyapp.com/fr/docs/bootstrap/

/cc @vincentchan

**Comment by cvrebert** [comment]
Looks like it's been fixed.
https://mobile.twitter.com/VincentChan/status/613513937305276416

**Comment by xiaosong88** [comment]
what is?

**Comment by cvrebert** [comment]
@xiaosong88 http://www.oneskyapp.com/fr/docs/bootstrap/ (a French translation of our docs) now works again.
