### ISSUE TITLE
INR symbol missing in CSS

### ISSUE THREAD

**Issue by raghothams** [twbs/bootstrap#16660]
I was having a look at the [issue - 15617](https://github.com/twbs/bootstrap/issues/15617) and realized that the ISO 4217 currency code for INR (Indian Rupee) is missing in the styles.
It would be awesome to add the currency code (₹)

**Comment by kkirsche** [comment]
The [Glyphicons](http://glyphicons.com/) are an external project that we just package/bundle.
I'd recommend directing icon suggestions to the Glyphicons' author. Thanks!
