### ISSUE TITLE
What would be the mixin contrary to hide-text? [unhide-text]

### ISSUE THREAD

**Issue by AdsonCicilioti** [twbs/bootstrap#16664]
When I use the span tag with glyphincons within labels or buttons, in many cases I want to hide the text with the mixin hide-text. But it also hides the icon, because it the same as text and to be a child element ..
Knowing that want to apply a kind of "unhide-text" in the span tag to restore the visibility of it.

Someone uses some class or technique for this?

**Comment by patrickhlauke** [comment]
I'd say the most robust way of achieving what I think you're trying to do is something like this:
```
<button ...><span class="glyphicon ..." aria-hidden="true"></span><span class="sr-only"> the hidden text</span></button>
```

**Comment by AdsonCicilioti** [comment]
Yeah. My intention is only to show the icon. This works, but the amount of span tags in html will increase as a class of reversion to hide-text would be ideal. I will try here.

Thanks!

**Comment by patrickhlauke** [comment]
as the `:before` pseudo element (which contains the actual glyph as generated content) still inherits the styles applied to its `<span class="glyphicon ...">`, I don't think there's a clean way to both hide the span's content AND to have its icon show - at least to my knowledge. also the same problem applies if you were trying to apply a hiding class to the `<button>` itself and then trying to somehow unhide just the `<span class="glyphicon ...">`.

**Comment by AdsonCicilioti** [comment]
Truth! If I finish, I decided not to use the hide-text to this case because it really has no way to reverse the icon visibility. So how am working on SASS, I created a specific class for these cases in my project:

```
.ico-only {
   text-indent: -9999px;
   span.pficon {
     text-indent: 0px;
     float: left;
   }
}
```

Mesmo assim obrigado @patrickhlauke !

**Comment by patrickhlauke** [comment]
:+1:
