### ISSUE TITLE
IE11 shows some kinda of emboss in panel-primary

### ISSUE THREAD

**Issue by Khrysller** [twbs/bootstrap#16671]
Windows 8, IE 11:

![panel](https://cloud.githubusercontent.com/assets/5774516/8244737/e5d37318-15fa-11e5-8d63-fc60201172b4.PNG)

In Chrome it is flat. Shouldn't be flat in IE 11 too?

**Comment by mdo** [comment]
That's not any CSS bug, it's a rendering issue I believe. Looks like the background is bleeding through for some reason. Are you zoomed in or out at all?

**Comment by Khrysller** [comment]
No zoom. I tried with different zoom, to see the results. All the same. Just tested in a IE9 on Windows 7 and the result is the same as Chrome, flat, without the "emboss".

**Comment by coliff** [comment]
I've just been looking into this issue on IE11 on Windows 8.1. It is a bit jarring once you notice it.

Using the F12 DOM Explorer devtool and then turning off both 'border-top-left-radius:3px' and 'border-top-right-radius:3px' from .panel-heading fixes the issue and all the example panel headings looks great with no 1 pixel white inner border.

**Comment by cvrebert** [comment]
Confirmed in Win 8.1 IE 11.0.9600.17801 on Sauce Labs.

**Comment by cvrebert** [comment]
The bug does not repro in Win 8 IE10 on Sauce Labs.

**Comment by cvrebert** [comment]
> Looks like the background is bleeding through for some reason.

Confirmed that this is what's happening. Changing the background-color of the `.panel` changes the color of the bleed line.

**Comment by cvrebert** [comment]
Filed Internet Explorer bug: https://connect.microsoft.com/IE/feedback/details/1463734/border-radius-causes-line-of-bleed-through-of-background-color-from-containing-element

**Comment by jonathansampson** [comment]
Confirming on behalf of the IE team that we see the issue in both Internet Explorer and Microsoft Edge. As @coliff stated above, turning off the border-radius values on `.panel-heading` resolves the issue. I'm assuming that this is related to sub-pixel precision as slowly increasing the width of the window causes the 1px gap to manifest itself every-other-pixel.

**Comment by cvrebert** [comment]
@jonathansampson Thanks! IE Team's responsiveness is greatly appreciated.
