### ISSUE TITLE
Escape key not working on a modal

### ISSUE THREAD

**Issue by prahladyeri** [twbs/bootstrap#16677]
I've implemented Twitter-Bootstrap in my open source Project [Visual Alchemist](https://github.com/prahladyeri/valchemist). TwBs its an awesome framework, thanks a lot! However, the escape key works in all my dialogs, except the last one which contains a `pre` tag. This dialog is shown on the **Generate Models** button. Here is the HTML partial for it:

  	 <div id="resultsDialog" class="modal fade">
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h4 class="modal-title">Copy below code and run to generate models<span id="databaseName"></span></h4>
		  </div>
		  <div id="theCode" class="modal-body form-inline">
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  </div>
		</div>
	  </div>
	</div>

	<script type="text/javascript">
	//$("#fieldName").focus();
	//document.getElementById("fieldName").focus();
	//console.log("Focussed");
	</script>

**Comment by kkirsche** [comment]
This sounds like a personal support request not a big with bootstrap. Per the contributing.md file, the issue tracker is for bootstrap bugs only. 

If this is not the case, please post a stripped down bootstrap only implementation on JSBin which demonstrates the bug for us to assist. Cheers!

**Comment by mdo** [comment]
If you can put together an isolated example on JS Bin that reproduces this, we can take a more detailed look.

**Comment by cvrebert** [comment]
Also, please state which browser(s) and OS(es) you're experiencing the problem in.

**Comment by prahladyeri** [comment]
Hi @mdo et al., 
Thanks for your response, really appreciate it. To replicate this issue, I've created two jsFiddles:

[fiddle-1 (problem - Escape key doesn't work)](http://jsfiddle.net/07xcfunn/)
[fiddle-2 (runs okay)](http://jsfiddle.net/x4Lqk6xq/)

The first one is a simple modal where I display some python code inside the `<div>` block during run-time. There is no code in that fiddle-1, yet the escape-key isn't working.

In the second scenario, I'm showing an add-fields dialog so user can add fields to the models. Here, the dialog is working properly. Perhaps, I'm doing something in a wrong manner but unable to put my finger on it. Is that so that we need a focused `<input>` box in order for escape key to work?

Also, my browser is Chrome 41.0 on Windows 7, but I've also tested this on Firefox 33 and its failing there too.

Thanks,
Prahlad

**Comment by twbs-lmvtfy** [comment]
Hi @prahladyeri!

You appear to have posted a live example (http://fiddle.jshell.net/07xcfunn/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @prahladyeri!

You appear to have posted a live example (http://fiddle.jshell.net/x4Lqk6xq/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 39, column 46 thru line 39, column 53: Stray end tag ```` input ````.
* line 47, column 9 thru line 47, column 126: Bad value ```` true ```` for attribute ```` autofocus ```` on element ```` input ````.
* line 47, column 127 thru line 47, column 134: Stray end tag ```` input ````.
* line 48, column 9 thru line 48, column 227: Attribute ```` type ```` not allowed on element ```` select ```` at this point.
* line 55, column 122 thru line 55, column 129: Stray end tag ```` input ````.
* line 56, column 119 thru line 56, column 126: Stray end tag ```` input ````.
* line 57, column 94 thru line 57, column 101: Stray end tag ```` input ````.
* line 58, column 91 thru line 58, column 98: Stray end tag ```` input ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@prahladyeri Please fix the validation errors in your fiddles. Note that `</input>` is nonsense because inputs are [empty elements](https://developer.mozilla.org/en-US/docs/Glossary/empty_element).

**Comment by prahladyeri** [comment]
@cvrebert Please ignore the second fiddle with `<input>` tags because that popup is working fine. Its the first fiddle that's problematic. The only issue with that was an older bootstrap version. But now I've updated it to latest 3.3.4, but the issue is still replicable:

http://fiddle.jshell.net/07xcfunn/2/

**Comment by kkirsche** [comment]
Bootlint is wrong and I think just needs the latest code of it deployed — latest is actually 3.3.5 now. I'll give it a shot when I get home and see if I have the issue on OS X

**Comment by prahladyeri** [comment]
@kkirsche When I compared again with the canonical example, I found that my main dialog block (`div.modal`) lacked this attribute:

    tabindex="-1"

I found that once I added that attribute, the escape key started working in the fiddle as well as my original code! Are we always supposed to add this attribute? If so, I'm sorry this may not be a bug, but a configuration mistake?

**Comment by kkirsche** [comment]
I would guess it's necessary as tab index is extremely important for managing the keyboard and accessibility. 

Great article on tab index in general:
http://www.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/

**Comment by kkirsche** [comment]
It sounds as though that would be why. To quote the article:

"When `tabindex` is set to a negative integer like -1, it becomes programmatically focusable but it isn’t included in the tab order. In other words, it can’t be reached by someone using the tab key to navigate through content, but it can be focused on with scripting."

**Comment by prahladyeri** [comment]
I just found the source of my troubles. Whilst implementing this modal dialog, I unfortunately looked up this [W3Schools](http://www.w3schools.com/bootstrap/bootstrap_modal.asp) example instead of the canonical bootstrap one. And guess what - they conveniently forgot to add `tabindex` in that example!

**Comment by cvrebert** [comment]
Yet another good example of why to not use w3schools :smile:

**Comment by cvrebert** [comment]
> Bootlint is wrong and I think just needs the latest code of it deployed — latest is actually 3.3.5 now.

@kkirsche It could indeed use an update, but it's not wrong per se, just imprecise. Note the phrasing:

> Latest version is **at least** 3.3.4 ;

(And it's imprecise because making it precise would either involve fortune telling or an unreliable network request.)

**Comment by kkirsche** [comment]
Fair point. Skimming it, the output reads as latest is 3.3.4 but you are right it does actually clarify at least
