### ISSUE TITLE
Bower.json file missing css in 'main' block

### ISSUE THREAD

**Issue by tonypatton** [twbs/bootstrap#16676]
The 'main' block of the bower.json file used to contain the main css file, but that was been removed with a recent version. This causes build tools like grunt wiredep to not add the css file automatically (which it should). Was this removed intentionally?

**Comment by kkirsche** [comment]
@tonypatton:

See #16663

Bower has changed their spec and we will be following their spec which no longer allows compiled resources in main and uses one entry point of sources. 

Issues should be brought to bower.
