### ISSUE TITLE
Selectors issue in Bootstrap v3.3.5  with Jquery 1.11.3

### ISSUE THREAD

**Issue by tvvignesh** [twbs/bootstrap#16675]
When Bootstrap v3.3.5 JS is combined with Jquery 1.11.3 Jquery selectors dont work.

**Comment by Johann-S** [comment]
Please can you provide a JSBin of your code ?

**Comment by tvvignesh** [comment]
I just resolved the issue. I was using JQuery with Jquery UI and Bootstrap. So, I had method $( document ).tooltip({......}); to provide styles to my tooltip. But when it was used, there was conflict with bootstrap. So, i removed it.
