### ISSUE TITLE
Why the hell (IE11 issue)

### ISSUE THREAD

**Issue by asoggetti81** [twbs/bootstrap#16685]
Hi,

I'm working on a project for which I would like to have the maximum width size set to 1560px (i'm working with the latest bootstrap version):
I do not know if I'm doing write anyway I made something like this:

@media (min-width: 1576px) {
#page{width:1560px; padding-right:145px; padding-left:145px;}
div.bx-wrapper{background:#EEE; min-height:548px;}
}

but IE11 and Safari do not work with it:

it's all ok in Chrome Opera and Firefox.

Why???

**Comment by patrickhlauke** [comment]
For general support questions - rather than to report issues with Bootstrap itself - please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by asoggetti81** [comment]
Oh, sorry ok i'll do that way...

Thanks

**Comment by patrickhlauke** [comment]
:+1:
