### ISSUE TITLE
border radius on vertical button groups being incorrectly set on left and right

### ISSUE THREAD

**Issue by sdwarwick** [twbs/bootstrap#16683]
not sure why this has not been seen before..  for vertical button groups, I found that changing the button border radius only changed the top-right and bottom left, not the top-left and bottom right.  found that the following two lines fixed this.   

.btn-group-vertical > .btn {
  &:not(:first-child):not(:last-child) {
    border-radius: 0;
  }
  &:first-child:not(:last-child) {
    border-top-right-radius:  @btn-border-radius-base;
	border-top-left-radius:  @btn-border-radius-base;  //fixes this problem
    .border-bottom-radius(0);
  }
  &:last-child:not(:first-child) {
    border-bottom-left-radius:  @btn-border-radius-base;
	border-bottom-right-radius:  @btn-border-radius-base;  //fixes this problem
    .border-top-radius(0);
  }
}

**Comment by mdo** [comment]
Have a demo that shows the before and after here? Curious how much of a problem this is.

**Comment by sdwarwick** [comment]
after looking at this further,  it appears that the error is actually in including the  btn-border-radius references at all.    All 4 corners of border radius are already set, and the need is to clear them on the top and bottom only 

variables.less: 

 @border-radius-small:       10px;

corrected button-groups.less: 


.btn-group-vertical > .btn {
  &:not(:first-child):not(:last-child) {
    border-radius: 0;
  }
  &:first-child:not(:last-child) {
   // border-top-right-radius: @btn-border-radius-base;  // remove this
    .border-bottom-radius(0);
  }
  &:last-child:not(:first-child) {
   // border-bottom-left-radius: @btn-border-radius-base;  // remove this
    .border-top-radius(0);
  }
}

![image](https://cloud.githubusercontent.com/assets/7736675/8306974/05cb12a6-198a-11e5-8e8c-dd2c088943a5.png)

**Comment by kkirsche** [comment]
@sdwarwick can you post a JSBin demonstrating the resulting CSS?

**Comment by sdwarwick** [comment]
@mdo -  according to gitk, these were added by you on 08/13/2013  in a merge called "derp"   
f15f259876d77004fadf5b5937af5ab6b5eabb8e

prior to that,  the radius came from other settings.
