### ISSUE TITLE
Checkbox inputs leave a large shadow in the background on mobile displays

### ISSUE THREAD

**Issue by prahladyeri** [twbs/bootstrap#16681]
I don't know whether this is an intended feature or just a side-effect of bootstrap, but I've been trying to implement bootstrap in one of my projects and couldn't help notice this bug. Here is the jsbin:

http://jsbin.com/moqufeyiza/edit?html,js,console,output

As you can see in the small window, if you check the `primary` or `unique` boxes, there is a huge shadow in the background which is almost the size of a fully-fledged text-box. But if you see it in proper width (~960px display), the shadow is there, but just small enough to hold the checkbox. Is there any way to remove this huge shadow on mobile displays?

**Comment by mdo** [comment]
Don't apply input or button classes to checkboxes and radios. That appears to be your problem.
