### ISSUE TITLE
responsive embed for <svg>

### ISSUE THREAD

**Issue by rubenscd** [twbs/bootstrap#16686]
it is possible to encapsulate the SVG with "embed-responsive" for responsives SVGs
or daydreaming !?

**Comment by kkirsche** [comment]
@rubenscd you'd have a few options for responsive SVG though I don't think `.embed-responsive` would be the best one for it. Personally, I would recommend using the SVG `viewbox` attribute depending on your IE needs. Essentially you need to

1. Set a viewBox attribute.
2. Set at least one of height or width on the `<img>`.
3. Don't put it inside a table layout if you care about supporting Internet Explorer.

[This article by CSS-Tricks](https://css-tricks.com/scale-svg/) does a good job in my opinion of explaining the pros and cons associated with the different options.

**Comment by mdo** [comment]
Yeah I haven't looked much into it myself, but I believe this needs to happen at the SVG level, not just with CSS. Regardless, it's a new feature that we won't be addressing in v3 and likely won't get to ourselves in the first few releases for v4.
