### ISSUE TITLE
Fix for progress bars with small percentages

### ISSUE THREAD

**Issue by hrj** [twbs/bootstrap#16680]
## Problem
If we set a `min-width` to the progress bar as recommended in the docs, it doesn't allow the progress bar to monotonically increase. The alternative mentioned in past issues is to add a text-shadow, but simply adding the shadow doesn't work, because part of the text is hidden.

## Solution
Here's how I do it:

#### Markup
```
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width:1%">
    <span class="progress-bar-text">1%</span>
  </div>
</div>
```

#### CSS
```
.progress-bar .progress-bar-text {
  position: absolute;
  text-shadow: 0px 0px 4px #444;
}
```

## Explanation
The `position:absolute` forces the entire text to be visible, thus allowing it to be styled freely. Adding a shadow now works fine.

This could perhaps be added to the docs as a suggestion.

**Comment by kkirsche** [comment]
Could you post a JSBin demonstrating current and the proposed behavior?

**Comment by cvrebert** [comment]
Perhaps in v4 we should just put the caption centered below the progress bar (rather than inside it), thus sidestepping the problem entirely.

**Comment by mdo** [comment]
FWIW, in v4 we're likely moving to the `<progress>` element, which doesn't have support in nearly any browsers for text labels (nor animation).

**Comment by mdo** [comment]
That said, we're not going to tweak the behavior of this in v3. We've gone back and forth on this previously.

**Comment by hrj** [comment]
@kkirsche Here's the [jsBin](http://output.jsbin.com/fonoyirocu/1) showing the three different solutions.

**Comment by Vzor-** [comment]
Part of the issue here is that the intended functionality it to label the colored area of the progress bar. This behavior is not in line with progress bars in general. The entire bar is an element and the label should be centered. I think this issue should be revisited and fixed.

**Comment by Iftimasum1** [comment]
#16680
