### ISSUE TITLE
Not Displaying Letters like ššęą

### ISSUE THREAD

**Issue by mariukaas28** [twbs/bootstrap#16696]
help?what happens when typing ė...
![help](https://cloud.githubusercontent.com/assets/13029843/8325133/abd8ff5c-1a5f-11e5-8f8f-ff35ccd53c2a.jpg)

**Comment by patrickhlauke** [comment]
This is not a Bootstrap issue. Most likely something to do with whatever backend system you're using?

**Comment by patrickhlauke** [comment]
Suggest asking on StackOverflow or similar (providing a bit more information about what your setup is) https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
