### ISSUE TITLE
Deploy an official NuGet package

### ISSUE THREAD

**Issue by supergibbs** [twbs/bootstrap#16692]
I know this has been brought up many times but Bootstrap can currently be installed via a GitHub download/clone, CDN, Bower, npm, Composer and Meteor. Adding NuGet would be a helpful addition.

The best [NuGet Bootstrap Package](https://www.nuget.org/packages/bootstrap) is managed by [Outercurve Foundation](http://www.outercurve.org/). Unfortunately their package has had [issues in the past](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=nuget) and is often out of date (still on v3.3.4 currently).

@mdo suggested I open an issue to see how much interest there is. If this is something the core team would consider, I believe it could be fully automated with the addition of a couple files. I'd be happy to take on setting it up.

**Comment by mdo** [comment]
Yeah, if there's enough support out there, we can consider adding it to our release process—if it's not too much of a nuisance that is. Having someone own it is helpful, but a streamlined process that keeps things up to date for folks is always advantageous.

**Comment by sandeepmovva** [comment]
+1

**Comment by aaronhudon** [comment]
1++

**Comment by berwyn** [comment]
+1

**Comment by CalvinAllen** [comment]
+1 (I would also add a similar request for the sass port)

**Comment by jsheely** [comment]
+1 Surprised this is not already a thing.

**Comment by mdo** [comment]
None of us on the core team are really on Windows machines, so it hasn't come up for us. Previously someone else was managing it. If we add this, we'll likely want to snag that package name from those folks. Anyone want to try to spearhead this for us?

**Comment by supergibbs** [comment]
No prob, I'll shoot them a message. I was looking into https://www.myget.org/ too. Seems like an easy way to publish not only NuGet but npm and bower too. @mdo made it sound like a pretty manual process.

**Comment by chakrabar** [comment]
VS 2015 is using bower, so it should be already ready for that. But not all professional developers are going to jump to VS 2015 immediately. So, NuGet will be really helpful.
And ideally, the process should not be complex or manual!

**Comment by vtforester** [comment]
+1

How would you set up the folder structure for the package? Or would you keep the same structure that Outercurve uses?

**Comment by ahsteele** [comment]
+1
Having an official NuGet package would be a big win.

**Comment by jraq** [comment]
+1

Nuget would be awesome. @chakrabar the VS 2015 vnext web application project will be using bower, but every other web application project will still use nuget in VS 2015. I agree that not everyone will be jumping to upgrade their projects or visual studio immediately.

**Comment by gichamba** [comment]
+10 here

**Comment by ericberens** [comment]
+1

**Comment by druzza** [comment]
+1

**Comment by devdelimited** [comment]
+less #pleasepleasepleasepleasepleaseplease

**Comment by chakrabar** [comment]
@jraq agreed. An official NuGet will still be awesome for non-vNext web projects on VS 2015.
I wonder what would be the percentage of developers using vNext projects in next 6 months, more than 20% ?

**Comment by BramVercaigne** [comment]
+1

**Comment by jraq** [comment]
@chakrabar I don't know what the percentage would be, but I believe since the vs 2015 is already in release candidate it will be released before vnext. I follow the community standups that @shanselman does for vnext and it sounds like they are planning to release vs 2015 before vnext, but I'm not 100% sure. I know this is probably a stretch and I'm not sure if they will see these github comments, but it would be cool if @shanselman or @DamianEdwards could comment. I see them the most in the standups

**Comment by jerone** [comment]
:+1:

**Comment by turchenkoalex** [comment]
+1

**Comment by jenscski** [comment]
+1

**Comment by stigur** [comment]
Offical - would be much better :)

**Comment by cubitouch** [comment]
+1 :)

**Comment by MichaelPetrinolis** [comment]
+1

**Comment by Sycro** [comment]
+1

**Comment by heymega** [comment]
+1

**Comment by akrohn** [comment]
+1

**Comment by kylealanr** [comment]
+1

**Comment by scottaddie** [comment]
This would seem to go against Microsoft's recommendation when VS 2015 is released. Bower receives 1st class support in the IDE at that point, and Microsoft's own client-side assets will be delivered from Bower. We're seeing that already in VS 2015 RC with MVC and SignalR. Wouldn't it then make sense to keep consistent with this theme and use Bower for installing Bootstrap? I have yet to confirm it myself, but I'd also guess that the Bootstrap which is bundled in Microsoft's ASP.NET templates will also come from Bower.

Here's some reading related to what I've stated above: http://blogs.msdn.com/b/cdndevs/archive/2015/02/17/using-bower-with-visual-studio-2013.aspx.

**Comment by wags1999** [comment]
+1
Yes, eventually we should use Bower to get client-side assets... but in an enterprise environment like where I'm at, it takes a long time to change how people work.  We just got people using NuGet last year!  So I'd love to see the NuGet package be more up-to-date.

**Comment by scottaddie** [comment]
@wags1999 Good point. I can definitely relate to that.

**Comment by rheone** [comment]
+1 My team uses bootstrap within visual studio, being able to depend on a reliable NuGet package for it would be tremendously helpful.

**Comment by KimTranjan** [comment]
Yes, please. :)

**Comment by wags** [comment]
+1
I would definitely use this. There's something comforting about getting code right from an official source.

**Comment by mdo** [comment]
Right on.

I've sent them a message on the NuGet package site and also a quick note on Twitter. Let's see what happens over the next few days.

**Comment by supergibbs** [comment]
@scottaddie I love that Microsoft is embracing the open source community and trying to work with it instead of rolling their own and forcing people to use it. They started open sourcing on github instead of codeplex, better support for git instead of just TFS (or VSS, yuck) and now bower support so developers can take advantage of all that is out there already. That being said, there are lots of users of NuGet still and it's not going away. Some people might even prefer it. There almost 200K downloads of the latest (out of date) version via NuGet. Adding NuGet support only helps even if it's not the primary packaging system in the future.

PS- @mdo, I messaged OuterCurve too :)

**Comment by supergibbs** [comment]
@vtforester: Assuming OuterCurve is willing to transfer the package, it would make sense to keep the structure the same. Is there something you would change?

**Comment by vtforester** [comment]
@supergibbs No, I was just curious but keeping it the same makes sense.

**Comment by grprakash** [comment]
VS 2015 supports bower, it will take years for all the customers to upgrade to it. (One of my clients are still in 2010). It would be great to have a official nuget package

**Comment by Alex-Sokolov** [comment]
+1

**Comment by itomek** [comment]
+1

**Comment by NelsonReis** [comment]
+1

**Comment by gsferreira** [comment]
+1

**Comment by rmarinho** [comment]
+1

**Comment by shanselman** [comment]
Sorry, better to use Bower or npm, that's what they are for. NuGet is for
compiled .NET binaries.

On Wed, Jul 1, 2015 at 8:14 AM, Rui Marinho <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/16692#issuecomment-117711591>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by jraq** [comment]
@shanselman I built an asp.net 4.6 mvc project in vs 2015 rc and it uses nuget to pull down bootstrap 3.0 in the packages.config. In the last standup, I believe @DamianEdwards said vnext won't be in rc until November. If I'm wrong let me know. My company use nuget for bootstrap right now. When we update our projects to vnext this winter and start using bower it would be less stressful for me (and QA) that we are using the latest version of bootstrap.

p.s. I love this developers life

**Comment by grprakash** [comment]
@shanselman I second @jraq. I still have clients using VS 2010 and don't see them upgrading to VS 2015 anytime soon. Till most of the people upgrade, having a official nuget package would be great

**Comment by MoYu1991** [comment]
+1

**Comment by drmcclelland** [comment]
+1 - yes please!

**Comment by natalka01** [comment]
just another +1

**Comment by jimdavis1026** [comment]
A nuget package for Bootstrap would be used a lot. Consider this a vote for it. +1

**Comment by Eonasdan** [comment]
This is a little late the game here guys. Nuget is going to stop delivering front end packages like this to all new .Net 5+ projects (MVC 6, Webforms, etc). All .Net developers are going to have to use bower to add front-end packages in the future.

See this: https://github.com/NuGet/Home/issues/930

**Comment by supergibbs** [comment]
@Eonasdan yes this has been brought up but there will a long transition to the new system so there is no harm in supporting a nuget distro in the mean time. 

Not an automated process yet but currently up to date with v3.3.5:
https://www.nuget.org/packages/Bootstrap/
https://www.nuget.org/packages/Bootstrap.Less/

**Comment by sirkirby** [comment]
I'll plan to redirect https://www.nuget.org/packages/Twitter.Bootstrap.Less/ to Bootstrap.Less with the v3.3.5 update...Did the same thing when switching from Twitter.Bootstrap to Bootstrap when Outercurve took over the maintenance. Issue referenced above. thanks @supergibbs for the heads up.

**Comment by Untit1ed** [comment]
+1.
Outdated bootstrap packages was one of the reasons I switched to bower from NuGet. 
I agree it's a little too late now, but better late than never.

**Comment by taspeotis** [comment]
+1 although I've never had a problem with the Outercurve managed NuGet package.

**Comment by ichpuchtli** [comment]
+1

**Comment by tiesont** [comment]
@supergibbs Not sure if you're managing the package, but the 3.3.5 version does *not* include the Glyphicon font files. Is this intentional? I notice they're still referenced in the CSS file, so...

**Comment by supergibbs** [comment]
@tiesont I just checked and it seems fine to me. Make sure you are using the official packages; there are lots of others.

https://www.nuget.org/packages/bootstrap
https://www.nuget.org/packages/bootstrap.less

The font files are included in both. In the less package, you may have to change the font path in the `variables.less` file depending on your setup.

Let me know if it's still not working for you!

**Comment by tiesont** [comment]
@supergibbs True enough. Should have checked the .nupkg first.

For whatever reason, when I updated from the 3.3.4 version, the font files were not copying over. Using `Update-Package –reinstall bootstrap`, the fonts got copied in. Probably just something weird about this project. Thanks!

**Comment by cvrebert** [comment]
Fixed by #16710.
