### ISSUE TITLE
Broken images in Dashboard example

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#16699]
http://getbootstrap.com/examples/dashboard/

**Comment by kkirsche** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) for holder.js

**Comment by mdo** [comment]
Yeah, might have to fix some paths on that—or replace those images with something else. In the past I've done base64 encoded 1x1 solid GIFs that I then tweak with inline dimensions.

**Comment by kkirsche** [comment]
@mdo Is the `gh-pages` branch exactly what gets deployed? Just trying to identify what the actual production file paths look like so I can potentially submit a fix for you guys

**Comment by mdo** [comment]
Nah, you'll want to look at `master` and fix it there. `gh-pages` is just the generated Jekyll site.

**Comment by omegahm** [comment]
It seems that the `holder.min.js`-file isn't pushed to the gh-pages branch, however it is created in the `_gh_pages`-folder when I run

```bash
jekyll serve
```
