### ISSUE TITLE
data-toggle="buttons" problem in v3.3.5

### ISSUE THREAD

**Issue by kntmrkm** [twbs/bootstrap#16693]
I don't know I think this issue is specific for Rails.

But bootstrap version up have broken `button toggle's function`.

I have a code like below.

```
<div data-toggle="buttons">
      <div class="checkbox">
        <label class="btn btn-block btn-facebook " for="post_post_facebook">
          <input name="post[post_facebook]" type="hidden" value="0" />
          <input class="hidden" type="checkbox" value="1" name="post[post_facebook]" id="post_post_facebook" /> Share with Facebook</label>
      </div>
</div>
```
[![Gyazo](http://i.gyazo.com/e6692c1a3ff463b6f4237f690a8b79af.gif)](http://gyazo.com/e6692c1a3ff463b6f4237f690a8b79af)

The code works with version 3.3.4.1.

But, With 3.3.5. After click button. Toggle function does not works.

So, I have removed `<input name="post[post_facebook]" type="hidden" value="0" />` .

Then Toggle function works.

I think `data-toggle='buttons'` does not work with Rails form generator.

Is not?

（moved from https://github.com/twbs/bootstrap-sass/issues/923#issuecomment-114588190)

**Comment by cvrebert** [comment]
@kntmrkm What OS and browser are you using? Does http://getbootstrap.com/javascript/#buttons-checkbox-radio work for you?

**Comment by kntmrkm** [comment]
Yes. The page's script works well.

I'm using Chrome 43.0.2357.130 (64-bit), or Safari 8.0.6.
OS is OSX 10.10.3.

I have checked both browser. and, I realized this issue on iOS mobile safari.

**Comment by kntmrkm** [comment]
Sorry my English.
This problem happens on chrome safari on OSX.

**Comment by cvrebert** [comment]
@kntmrkm Are you sure the problem is not caused by some other script on your page?

**Comment by kntmrkm** [comment]
I confirmed by change just `bootstrap-sass` from '3.3.5' to '3.3.4.1'.

When version is '3.3.5' , problem happens (buttons does not work.)

**Comment by cvrebert** [comment]
@kntmrkm Could you make a [JS Fiddle](http://jsfiddle.net) that demonstrates the problem?
bootstrap-sass vs. Bootstrap shouldn't matter since this is a JavaScript problem.

**Comment by kntmrkm** [comment]
This fiddle works well with 3.3.4
http://jsfiddle.net/kntmrkm/39jtyruu/

This fiddle is problem with 3.3.5
https://jsfiddle.net/kntmrkm/xumxon1L/

**Comment by twbs-lmvtfy** [comment]
Hi @kntmrkm!

You appear to have posted a live example (http://fiddle.jshell.net/kntmrkm/39jtyruu/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 59, column 11 thru line 59, column 70: Any ```` input ```` descendant of a ```` label ```` element with a ```` for ```` attribute must have an ID value that matches that ```` for ```` attribute.
* line 60, column 11 thru line 60, column 111: The ```` label ```` element may contain at most one ```` input ````, ```` button ````, ```` select ````, ```` textarea ````, or ```` keygen ```` descendant.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @kntmrkm!

You appear to have posted a live example (https://fiddle.jshell.net/kntmrkm/xumxon1L/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 59, column 11 thru line 59, column 70: Any ```` input ```` descendant of a ```` label ```` element with a ```` for ```` attribute must have an ID value that matches that ```` for ```` attribute.
* line 60, column 11 thru line 60, column 111: The ```` label ```` element may contain at most one ```` input ````, ```` button ````, ```` select ````, ```` textarea ````, or ```` keygen ```` descendant.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by NogsMPLS** [comment]
updated fiddles based on bot's recommendations - 

3.3.4 fiddle: 
http://jsfiddle.net/39jtyruu/1/

3.3.5 fiddle:
https://jsfiddle.net/xumxon1L/1/

Can't reproduce defect with new fiddles. On Windows 7 tested with Chrome & Firefox.

Would recommend marking as resolved/closed.

**Comment by kntmrkm** [comment]
I didn't thought that bot's recommendations.
Sorry and Thanks.

This causes by form generator.

**Comment by EHLOVader** [comment]
I too had this problem with some custom checkbox buttons in a Laravel app. It uses Former and does the same force checkbox state trick Rails does.

I found an alternative fix for this changing the selector in `buttons.js` on line [57](https://github.com/twbs/bootstrap/blob/master/js/button.js#L57) to exclude `hidden` inputs.

```
      var $input = this.$element.find('input[type!=hidden]')
```

What do you think of this as a solution? I don't think I could think of any conflicts or reasons not to.

**Comment by cvrebert** [comment]
See #16727.

**Comment by EHLOVader** [comment]
Oh thank you. That is a better solution.

I had a hell of a time searching for duplicate issues.

**Comment by kntmrkm** [comment]
For Rails user.
This is my solution until 3.3.8.

```
ul.list-inline.btn-business-day.btn-group(data-toggle='buttons')
                li
                  = f.hidden_field :day_mon, value: false
                  label(class="btn btn-default #{'active' if f.object.day_mon}")
                    = check_box_tag 'region[setting_attributes][day_mon]', true, f.object.day_mon
                    = f.object.day_mon
                li
                  = f.hidden_field :day_tue, value: false
                  label(class="btn btn-default #{'active' if f.object.day_tue}")
                    = check_box_tag 'region[setting_attributes][day_tue]', true, f.object.day_tue
```

- http://stackoverflow.com/questions/11550941/why-does-the-check-box-form-helper-generate-two-checkboxes-one-hidden
- https://github.com/twbs/bootstrap/pull/16727
