### ISSUE TITLE
Tooltip on div enclosing a disabled button broken in 3.3.5

### ISSUE THREAD

**Issue by totycro** [twbs/bootstrap#16704]
In 3.3.1, this code produces a tooltip above the disabled button:

```
<div style="display: inline-block;" tooltip="tooltip">
    <button class="btn" ng-disabled="true">button</button>
</div>
```

In 3.3.5, the tooltip does not appear any more.

**Comment by cvrebert** [comment]
Please post a JS Fiddle (without using Angular) that demonstrates the problem.

**Comment by totycro** [comment]
Sorry, I currently don't have time to investigate this issue further. Using the title-attribute works even on disabled buttons, that's more or less good enough for me.

**Comment by cvrebert** [comment]
Closing this then.
