### ISSUE TITLE
New variable for margin-bottom

### ISSUE THREAD

**Issue by JoyceBabu** [twbs/bootstrap#16705]
When the font size and line height are very large, the bottom margin for `p`/`ul` elements are too small. 
For example, when the `font-size` is `17px` and line-height is `1.75em` (`~30px`), the calculated bottom margin is `15px`.

Is it possible to create a new variable for the bottom margin for `p`, `ul`, `ol`, `table`...?

**Comment by mdo** [comment]
We won't be adding any more variables to v3 I think. v3.3.5 turned out bigger than I liked and we have to stay focused on v4, which will see some improvements around this area.
