### ISSUE TITLE
Text align classes improvements

### ISSUE THREAD

**Issue by bertoost** [twbs/bootstrap#16706]
Text align classes should use !important or there should be extra classes for this purpose.

Also would be useful to have device specific alignment classes; like

```
.text-left-xs
.text-right-md
.text-center-lg
```

and all others etc. hehe

**Comment by kkirsche** [comment]
I don't think this is something which would be added in V3 as it is essentially feature frozen. The core team though will be able to consider this for V4 though.

**Comment by itomek** [comment]
I wouldn't want an !important declared in the framework unless its absolutely necessary as it can limit the flexibility of overwriting.

**Comment by mdo** [comment]
Been asked for before and we won't be doing it for v3. Maybe v4, but even there we don't have anything in the pre-alpha builds yet.
