### ISSUE TITLE
3 columns in sm/md/lg to carousel on xs?

### ISSUE THREAD

**Issue by phpMagpie** [twbs/bootstrap#16700]
How do you address situations where you need two differing sets of markup for the same content within a single page?  My use case is showing a 3 column 'features' type content section on sm/md/lg into a carousel on xs. 

The obvious way is to have two lots of markup on the page and hide/show the relevant content block depending on the screen size.  Here's a web page that does exactly that: http://gillroyalty.com (check the code for the Our Process section)

My concern is this creates duplicate content within the page.  Not sure how much impact this would have on the page's indexing, but it just seems wrong.  On the flip side, having JS reformat HTML markup as screens are resized also seems like a lot of hassle.  

I'm sure plenty of others have had the same decisions to make, just interested to see which way you decided to go?

**Comment by kkirsche** [comment]
Per contributing.md, personal support requests should be directed to StackOverflow, Slack, or IRC. The issue tracker is specifically for bootstrap bugs.

**Comment by phpMagpie** [comment]
Apologies, can I delete the issue?

**Comment by mdo** [comment]
Nah, don't sweat it :). We'll close it out.

I'd suggest you try to revisit to simplify things as much as possible. Separate content for the same page based on the device you use doesn't sound like the right approach. Seems to add more complexity than perhaps splitting that content across multiple pages, revisiting overall flows, etc.
