### ISSUE TITLE
clicking a file input no longer closes its parent dropdown in v3.3.5

### ISSUE THREAD

**Issue by archit** [twbs/bootstrap#16719]
In bootstrap v3.3.4 if I have a file input inside a `dropdown-menu`, when I clicked the file-input, it would close the `dropdown-menu`.

However in v3.3.5, the click on file-input doesn't close the `dropdown-menu`. 

P.S. I'm assuming bootstrap follows semver in version, because I had `"bootstrap": "~3.3.4"` in my `bower.json` and the behind the scenes patch upgrade was causing me this issue.

**Comment by kkirsche** [comment]
Can you post a JSBin demonstrating the described before and after behavior so we can assist in solving it?

**Comment by archit** [comment]
yes, setting one up as we speak :-)

**Comment by archit** [comment]
v3.3.4

http://jsbin.com/nocejawuki/1/edit?html,css,js

v3.3.5

http://jsbin.com/horuyuzaxi/edit?html,css,js

**Comment by archit** [comment]
looks like this change was intended; see https://github.com/twbs/bootstrap/pull/16073

**Comment by archit** [comment]
but they were intending to fix for other types of input files, forgot to add exception for `input type="file"`

**Comment by archit** [comment]
safe to submit a fix for this, by adding an exception for file inputs?

**Comment by cvrebert** [comment]
@archit Please give a justification for why file inputs should be treated differently here.

**Comment by archit** [comment]
@cvrebert 
I'm not a UI expert,so I'm unable to  may not be able to dig up an official Human Interface Guidlines. But I reckon it has something to do with blocking-modals (file browser, bootstrap modals) & non-blocking-modals (what I like to call menu's) being mutually exclusive on a screen. Also my experience in these situations...

1. Menus in Desktop programs.  I just tried `File > Open File` & `File` > `Save Page As` in Chrome on Mac OS X, and it closes the `File` menu, once the file browser pops open.
2. I'm able to replicate the same behavior using jQueryUI; see http://jsbin.com/zunapihonu/edit?html,css,js,output
3. Bootstrap itself closes drop down menus, if they trigger a modal.

**Comment by cvrebert** [comment]
> (2) I'm able to replicate the same behavior using jQueryUI

Well, we already don't fully agree with them. They seem to close dropdowns when you try to click into a text input within one (example: http://jsbin.com/xuyufu/1/edit?html,output ), whereas we leave the dropdown open per #16073.

> (3) Bootstrap itself closes drop down menus, if they trigger a modal.

That's not really modal-specific. If you click any link or button in a dropdown, regardless of whether it's modal related, the dropdown will close by default.

---

Another counterargument is that treating `<input>`s differently based on their `type` might be less intuitive. (It certainly would require a longer explanation in our docs.)

CC: @mdo for a design decision

**Comment by archit** [comment]
@cvrebert your counter argument is from the point of view of categorizing behaviors based on html tag type, in this case I would argue it doesn't make sense categorize a file browser in the same category as text input as HTML does. However I would argue to categorize based on user interaction & design elements, in which case a file browser is in the same category as a modal than a text[area] input.

**Comment by mdo** [comment]
Form elements should be treated consistently—we won't be changing this for everyone.

Imagine the workflow of opening a dropdown, clicking on the file input, picking your file, and then coming back to see the element you just interacted with is gone. That feels wrong in most cases, though I can imagine folks wanting to override that (which you totally can on your own as I understand it).
