### ISSUE TITLE
Event shown in modal.js

### ISSUE THREAD

**Issue by CHeinrich7** [twbs/bootstrap#16716]
I am missing the event "shown.bs.modal".
The Events "show", "hide", "hidden" are triggered everytime but "shown" only in specific cases.
ps: I do not know where to report that desire, so i may wrongly reportet that as issue yet.

**Comment by kkirsche** [comment]
Would you be able to post a JSBin demonstrating a case where `shown.bs.modal` is not being triggered?

**Comment by CHeinrich7** [comment]
I'm sorry. It works very well. I do not know why it was not fired in my case.
