### ISSUE TITLE
Input alignment in IE

### ISSUE THREAD

**Issue by borkosavic** [twbs/bootstrap#16717]
In all regular browsers, the radio button is right next to the text whie in IE it goes far to the left.

http://jsbin.com/fekinaxozu/edit?html,output

It seems that IE does not apply text-align to the input fields.

**Comment by kkirsche** [comment]
What version of Windows are you using (assuming Windows as you mention IE)? And when you say "regular browsers" which browsers are you referring to or have been tested?

**Comment by borkosavic** [comment]
@kkirsche I tried it in Windows 7 and 8 / IE 9, 10 & 11. 

It looks fine in Chrome, Firefox and Safari on both OSX and Windows 7 and 8

**Comment by cvrebert** [comment]
The markup in your example is invalid. See specifically:
* https://github.com/twbs/bootlint/wiki/E014
* https://github.com/twbs/bootlint/wiki/E018

If you have a lint-free example the demos the problem, I'll be happy to reopen this.
See https://github.com/twbs/bootlint for info on how to Bootlint your webpage.
