### ISSUE TITLE
Grunt serve or build removes the boostrap.css reference from index.html

### ISSUE THREAD

**Issue by mrtinkz** [twbs/bootstrap#16720]
When I do the grunt serve the bower removes the <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" /> from the index.html. Found out this is being caused by the 

 "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],

Not sure why the bootstrap.less is being referenced. It should be bootstrap.css ?

**Comment by cvrebert** [comment]
It's correct as-is. See #16359.
