### ISSUE TITLE
retaining the old value of a selected DropDown

### ISSUE THREAD

**Issue by sushiMish** [twbs/bootstrap#16729]
Hi,

On Onchange event I am comparing the drop down "X"  value to another dropdown "Y" value and if it same I want to retain the old value of dropdown.

Regards

**Comment by patrickhlauke** [comment]
for personal support requests, please use StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker (and incidentally, your question sounds like a basic HTML/JS question, not related to Bootstrap at all)
