### ISSUE TITLE
Problem with downloaded files

### ISSUE THREAD

**Issue by taylor009** [twbs/bootstrap#16728]
I downloads the files but them in my project file and i link them together. When I make my navbar non of appears correctly so i tried it with the CDN links and those worked. I was wounder what I did wrong?
here are pictures of my links:
![screenshot from 2015-06-29 15 51 47](https://cloud.githubusercontent.com/assets/13009418/8416989/79874bd2-1e77-11e5-86cb-fafe451ce1fb.png)
![screenshot from 2015-06-29 15 51 56](https://cloud.githubusercontent.com/assets/13009418/8416992/7dd3fc62-1e77-11e5-93de-320bd169bab7.png)

**Comment by taylor009** [comment]
This is how it looks like with the downloaded version instead of the CDN links
![screenshot from 2015-06-29 15 57 35](https://cloud.githubusercontent.com/assets/13009418/8417023/b58bd0da-1e77-11e5-94ae-eec71ec916db.png)

**Comment by kkirsche** [comment]
Personal support requests are best directed to StackOverflow, Slack or IRC as this is not an issue with Bootstrap but rather an issue with use of the files provided. The issue tracker is solely for issues with the framework itself. I've verified with downloaded 3.3.5 files that this is not a Bootstrap error issue.
