### ISSUE TITLE
Mention changelog on readme; possibly a changelog file that links to releases/milestones

### ISSUE THREAD

**Issue by jvanasco** [twbs/bootstrap#16739]
I understand that you're using the github releases/milestones for changelogs.  I'm not going to argue with that.

BUT it's hard to find and not very standard (or is now, and I'm just old and out of touch).  I'm looking for "changelog" or "changes",  and can't find them.  It would be great if the readme file had a "changelog" section that linked to the releases and mentioned this policy.  It would also be great if there was a changelog.txt file that linked directly to the given milestone (or history of releases?) because that is the first thing that many of us look for when noticing a potential upgrade.

**Comment by jvanasco** [comment]
awesome!

**Comment by cvrebert** [comment]
Closing since #16744 & #16745 have been merged.
