### ISSUE TITLE
Submit button not same height as anchor in Firefox on Windows

### ISSUE THREAD

**Issue by hsleisink** [twbs/bootstrap#16737]
Input fields of the type submit do not have the same height as anchors when given the class 'btn btn-default'. This is only the case for Firefox under Windows.

**Comment by hsleisink** [comment]
Hmm, never mind. It seems the issue was the older version of Firefox I was using. Sorry.

**Comment by cvrebert** [comment]
See http://getbootstrap.com/css/#callout-buttons-ff-height and https://bugzilla.mozilla.org/show_bug.cgi?id=697451
