### ISSUE TITLE
input group inside a table makes issue

### ISSUE THREAD

**Issue by Mahendran-Sakkarai** [twbs/bootstrap#16730]
When i use input-group inside table, the alignment of the table is gone.

Check the fiddle.
http://jsfiddle.net/mahendranmails/7acmu8ug/3/

I used bootstrap.min.css of Bootstrap v3.3.5.

In firefox it's working fine. But in chrome the alignment is not correctly set to the table.

**Comment by cvrebert** [comment]
Duplicate of #16372?

**Comment by cvrebert** [comment]
Yep, closing as a duplicate.
