### ISSUE TITLE
Not possible to change title for popover.

### ISSUE THREAD

**Issue by Envek** [twbs/bootstrap#16731]
Hello!

I have next code:
```html
<a href="/foo/like" title="4 users liked this" data-requires-captcha="true">
  <span class="glyphicon glyphicon-thumbs-up"></span>
  Like!
  <span class="badge">4</span>
</a>
```

```js
// In event handler
if ($(this).data().requiresCaptcha) {
  $(this).popover({title: 'Please confirm that you are human', placement: 'auto bottom'});
  return false;
} 
```

And when user clicks button with `data-requires-captcha` attribute set to true (I set it up for anonymous users), I intercept click, construct popover, and placing ReCaptcha into the popover body. But text from `title` attribute (obviously used for browsers' native link popover and I need it) is going to the Bootstrap popover title, and I see no way to replace it with my own (title specified in `popover` method call is ignored, as written in docs).

My thoughts:

 * Popover should not use standard `title` attribute, it should use something like `data-title` instead (with fallback to `title` if not present).
 * Popover should have some method to change title dynamically.

**Comment by cvrebert** [comment]
X-Ref: #18329

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
