### ISSUE TITLE
popover not getting closed when using focus option

### ISSUE THREAD

**Issue by adityashankert** [twbs/bootstrap#16749]
the following is the initialization  i am using for popover

```
 $(this).popover({
        placement : 'bottom',
        title : 'Appointment Actions',
        html : true,
        content :"test",
        trigger : 'focus'

    }).popover('show');
```
full code -> https://jsfiddle.net/kd7e2xpc/2/

when I click anywhere else on the screen the behavior should be the popover should close but it is not getting closed

**Comment by twbs-lmvtfy** [comment]
Hi @adityashankert!

You appear to have posted a live example (https://fiddle.jshell.net/kd7e2xpc/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 12, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0
* line 13, column 3: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by adityashankert** [comment]
updated fiddle -> https://jsfiddle.net/kd7e2xpc/4/

**Comment by cvrebert** [comment]
@adityashankert How do I get a popover to open in your example in the first place? I've tried clicking and double-clicking everything.

**Comment by cvrebert** [comment]
Possibly related to #16732.

**Comment by adityashankert** [comment]
@cvrebert click on the event

**Comment by kkirsche** [comment]
@adityashankert I'm not able to find any "blue event"s. 
![captura de pantalla 2015-07-02 a las 7 21 33 am](https://cloud.githubusercontent.com/assets/947110/8476014/04c7a308-208b-11e5-9d56-413afb08cbd6.png)

**Comment by adityashankert** [comment]
@kkirsche I am using chrome browser following is the output on my browser
![for bootstrap](https://cloud.githubusercontent.com/assets/3639617/8476441/01659662-20df-11e5-9f96-07df32ae8fc5.png)

**Comment by kkirsche** [comment]
@adityashankert also on chrome. This screenshot is from my work Mac so its an older Chrome but the previous ones were latest version on my personal Mac.

![screen shot 2015-07-02 at 8 02 58 am](https://cloud.githubusercontent.com/assets/947110/8476595/d9c3b0f6-2090-11e5-961b-173d6f55304b.png)

I would wager this is an issue in part with the code if it doesn't consistently generate the event.

**Comment by adityashankert** [comment]
@kkirsche I have tested on macbook chrome it is working use the following fiddle in that I have fixed the time also
https://jsfiddle.net/kd7e2xpc/5/

The event should be at 10 am

**Comment by cvrebert** [comment]
Your event `<div>` never becomes focused in the first place before or after showing the popover, so clicking on another element doesn't unfocus it either, hence the popover does not get hidden by virtue of `trigger: 'focus'`.

**Comment by adityashankert** [comment]
I am setting 'tabindex' to -1 which should get it to focus will this not work any alternatives you can suggest to make the div i'm clicking focusable?

**Comment by kkirsche** [comment]
@adityashankert to attempt to address the `tabindex` comment (emphasis mine), when `tabindex` is set to a negative integer like `-1`, it becomes __programmatically__ focusable but it isn’t included in the tab order. In other words, it can’t be reached by someone using the tab key to navigate through content, but it can be focused on with scripting. [Source](http://www.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/)

**Comment by cvrebert** [comment]
> I am setting 'tabindex' to -1 which should get it to focus will this not work any alternatives you can suggest to make the div i'm clicking focusable sorry I got off topic but help would be great ?

Sorry, but that sort of tangential personal support question is [off-topic for this issue tracker](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker). Try asking on [StackOverflow](stackoverflow.com/questions/tagged/twitter-bootstrap-3) (or similar; see other link) instead. Thanks!

**Comment by RaminPakzad** [comment]
just need to add click also:
 
trigger : 'focus click'
