### ISSUE TITLE
Convert Glyphicons to SVG

### ISSUE THREAD

**Issue by JulianNorton** [twbs/bootstrap#16742]
* https://speakerdeck.com/ninjanails/death-to-icon-fonts
* https://css-tricks.com/icon-fonts-vs-svg/

**It would increase accessibility**. Providing both formats is also an option.

**Comment by patrickhlauke** [comment]
https://twitter.com/patrick_h_lauke/status/616271575600492544 ;)

**Comment by JulianNorton** [comment]
I searched the issues before I commented too, awesome! Glad to hear it.
