### ISSUE TITLE
Is there way to display year followed by month on the top

### ISSUE THREAD

**Issue by supritashankar** [twbs/bootstrap#16743]
I want to display "2013 March" on top .. is there a way to do this for bootstrap datepicker? I went through the docs and did not find anything to do the same.
Thanks!

**Comment by patrickhlauke** [comment]
This has nothing to do with Bootstrap (particularly since there is no "bootstrap datepicker")

**Comment by cvrebert** [comment]
Presumably you want https://github.com/eternicode/bootstrap-datepicker/blob/master/CONTRIBUTING.md#support-requests , which is a completely separate project, its name notwithstanding.
