### ISSUE TITLE
.img-responsive and affix conflict

### ISSUE THREAD

**Issue by duguxu** [twbs/bootstrap#16751]
images with class "img-responsive" will become to normal size at the affixed state.

**Comment by cvrebert** [comment]
@duguxu We cannot help you without a JS Bin, JS Fiddle, or other such live example that demonstrates the problem. See also https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by duguxu** [comment]
sorry, I can't reproduce it on jsbin with the latest version.
