### ISSUE TITLE
Radios edge cut off being inside of .media (or another element with overflow-hidden) in Chrome on retina displays

### ISSUE THREAD

**Issue by DrShpongle** [twbs/bootstrap#16756]
http://jsbin.com/qosemu/edit?html,output
http://ow.ly/3y0vYM

It seems it is only webkit behavior.
As solution decreasing `margin-left` from `20` to `19` works.

**Comment by josephfusco** [comment]
There is an open issue to this with chromium. [Chromium #396726](https://code.google.com/p/chromium/issues/detail?id=396726)

Not sure if we want to implement a fix or not, but I think the solution from @DrShpongle should be fine as radio buttons are absolute positioned, and inline spacing of multiple inputs will not affected. Pull request submitted: [#16772](https://github.com/twbs/bootstrap/pull/16772)

**Comment by cvrebert** [comment]
Closing in favor of https://github.com/necolas/normalize.css/issues/462 per https://github.com/twbs/bootstrap/pull/16772#issuecomment-118931536
