### ISSUE TITLE
Offcanvas example on getbootstrap.com don't displaying correctly in chrome

### ISSUE THREAD

**Issue by christyharagan** [twbs/bootstrap#16750]
Hi all,

The off canvas example : [http://getbootstrap.com/examples/offcanvas/](http://getbootstrap.com/examples/offcanvas/) isn't displaying correctly in chrome.

Specifically the navbar isn't showing the project name or nav options. The project name does appear when the screen is resized to force the menu to go off-screen, but the nav options still don't appear.

It works in IE.

**Comment by MrGeneric** [comment]
The navbar displays correctly for me in both Chrome 43 and 45. What version are you using?

**Comment by christyharagan** [comment]
Version 43.0.2357.130 m



![offscreen-large](https://cloud.githubusercontent.com/assets/825421/8475632/7670b488-20b1-11e5-83b8-853dd6bc4e98.jpg)


![offscreen-small](https://cloud.githubusercontent.com/assets/825421/8475611/54c5d50c-20b1-11e5-82fd-3e85919d95f3.jpg)

**Comment by christyharagan** [comment]
Windows 8.1 on a desktop (i.e.: it's not a surface, just a standard computer)

**Comment by patrickhlauke** [comment]
Cannot reproduce/works fine for me on Win8.1/Chrome 43.0.2357.130 m

![capture](https://cloud.githubusercontent.com/assets/895831/8476401/d897dd56-20b8-11e5-9f99-b29bd1104059.PNG)
![capture2](https://cloud.githubusercontent.com/assets/895831/8476402/d89df7d6-20b8-11e5-9181-242e04f5e289.PNG)

**Comment by patrickhlauke** [comment]
Long shot, but perhaps one of your extensions (adblock etc) are somehow interfering?

**Comment by christyharagan** [comment]
I've disabled all plugins and extensions

The problem appears to be the "margin left" css property on the parent "container" div:


![margin-left](https://cloud.githubusercontent.com/assets/825421/8477854/4a876588-20c5-11e5-964f-7193bcfcc9e5.jpg)

As you can see from the screen shot it is computing the value to be 1903px (in fact upon inspection, it's setting the margin-right property to be the same value)

Manually setting the (margin-left) value to say 15px displays the content as expected.

Very strange.

**Comment by patrickhlauke** [comment]
Strange indeed...but I can't reproduce this in my setup...so not quite sure what's going on in your case.

**Comment by christyharagan** [comment]
Bizarre. Perhaps it's a Chrome bug. Will raise it with the Chrome guys and see what they say. Thanks anyway :)
