### ISSUE TITLE
Add variable for <label> margin-bottom

### ISSUE THREAD

**Issue by daniphp** [twbs/bootstrap#16758]
There should be a way to customize the label attributes like
margin-bottom: 5px;

Are there any workarounds for this?

**Comment by yuyokk** [comment]
@daniphp you can apply your own styles for labels. 

    <label class="label-custom"></label>

    .label-custom {
      // your styles go here
    }

**Comment by MoYu1991** [comment]
but sometimes we need margin-bottom:10px or margin-bottom:20px;so ,  There is no need to do  customize the label attributes。

**Comment by mdo** [comment]
Punting on this in v3. We'll have several changes around forms in v4 though.
