### ISSUE TITLE
Change request of bootstrap/docs/_data/translations.yml

### ISSUE THREAD

**Issue by meftunc** [twbs/bootstrap#16755]
We have translated the whole documentation into Turkish. We request you to add a link into "Translations" part of "Getting Started" page.
You can reach our web site: www.trbootstrap.com
Regards,
Meftun.

**Comment by cvrebert** [comment]
@meftunc What would be the correct translation for "Bootstrap in Turkish"? Google Translate says "Türkçe Bootstrap". We'll be using this as a title for the hyperlink to your website.

**Comment by meftunc** [comment]
Yes "Türkçe Bootstrap" is the correct translation.
