### ISSUE TITLE
Tooltip is not dismissed when clicking on a link which opens a new tab

### ISSUE THREAD

**Issue by Djayb6** [twbs/bootstrap#16752]
Hello !

I created a [jsfiddle](http://jsfiddle.net/51basamt/) for this issue. 

The tooltip appears normally when the link with target="_blank" gains focus. Then the user clicks on the link and is redirected to a new tab. However, when the user comes back to the initial tab, the tooltip is still appearing, and the user has to click on the tooltip to dismiss it.

Is it a normal behavior ? 

Thank you.

JB

**Comment by patrickhlauke** [comment]
Yes, as the focus (when you return to the original tab) is still on the link (and there's no clean and accessible way to override this behavior)
