### ISSUE TITLE
.modal-header min-height formula is wrong

### ISSUE THREAD

**Issue by inferusvv** [twbs/bootstrap#16769]
modals.less, line 82.

    min-height: (@modal-title-padding + @modal-title-line-height);

First of all it returns not rounded value. Secondary if we not set title, header seems broken. Cross becomes near bottom border. I don't know, what was idea of this min-height, but I fixed it with this code:

    min-height: round(@modal-title-padding * 2 + @font-size-h4 * @line-height-base);

**Comment by mdo** [comment]
Have a before/after example?

**Comment by inferusvv** [comment]
@mdo Nope, but you can do it yourself. Inspect modal title and remove it. You will see what is wrong
