### ISSUE TITLE
Color of buttons that are active and disabled

### ISSUE THREAD

**Issue by seyfert** [twbs/bootstrap#16767]
I am using a button group as a form input (using data-toggle="buttons").  After the user submits the form, the form is temporarily disabled while the data is being processed.  I would expect that while the buttons are disabled it would still be possible to identify which (if any) buttons are selected ('active').  However, the button-variant mixin overrides the color for all states when the button is disabled so every disabled button variant looks the same.

From a usability perspective the current behavior is not ideal because the user may be confused to think that their selections were lost when the form was disabled.

You can see an example of the issue here:
~~http://codepen.io/seyfert/pen/oXqgNN?editors=111~~
http://codepen.io/seyfert/pen/PqRwXR?editors=101

I think the appropriate fix would be to modify the "disabled" styling in button-variant mixin so only "hover" and "focus" states use the default color for disabled buttons.
 
See https://github.com/seyfert/bootstrap/commit/11f785060a94f978cd5bdfcbb4064db39143b09d

**Comment by twbs-lmvtfy** [comment]
Hi @seyfert!

You appear to have posted a live example (http://codepen.io/seyfert/pen/oXqgNN.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 15, column 1 thru line 15, column 94: Attribute ```` ng-app ```` not allowed on element ```` form ```` at this point.
* line 15, column 1 thru line 15, column 94: Attribute ```` ng-controller ```` not allowed on element ```` form ```` at this point.
* line 15, column 1 thru line 15, column 94: Attribute ```` ng-submit ```` not allowed on element ```` form ```` at this point.
* line 16, column 3 thru line 16, column 41: Attribute ```` ng-disabled ```` not allowed on element ```` fieldset ```` at this point.
* line 20, column 9 thru line 20, column 101: Attribute ```` ng-class ```` not allowed on element ```` label ```` at this point.
* line 21, column 11 thru line 21, column 99: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 24, column 9 thru line 24, column 101: Attribute ```` ng-class ```` not allowed on element ```` label ```` at this point.
* line 25, column 11 thru line 25, column 99: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 28, column 9 thru line 28, column 101: Attribute ```` ng-class ```` not allowed on element ```` label ```` at this point.
* line 29, column 11 thru line 29, column 99: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 38, column 9 thru line 38, column 101: Attribute ```` ng-class ```` not allowed on element ```` label ```` at this point.
* line 39, column 11 thru line 39, column 99: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 42, column 9 thru line 42, column 101: Attribute ```` ng-class ```` not allowed on element ```` label ```` at this point.
* line 43, column 11 thru line 43, column 99: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 46, column 9 thru line 46, column 101: Attribute ```` ng-class ```` not allowed on element ```` label ```` at this point.
* line 47, column 11 thru line 47, column 99: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 68, column 9 thru line 68, column 66: Attribute ```` type ```` not allowed on element ```` select ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by seyfert** [comment]
Fixed codepen:
http://codepen.io/seyfert/pen/oXqgNN?editors=101

**Comment by twbs-lmvtfy** [comment]
Hi @seyfert!

You appear to have posted a live example (http://codepen.io/seyfert/pen/oXqgNN.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 8, column 1: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 75, column 5: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by seyfert** [comment]
Fixed codepen: http://codepen.io/seyfert/pen/MwVYzd?editors=101

**Comment by twbs-lmvtfy** [comment]
Hi @seyfert!

You appear to have posted a live example (http://codepen.io/seyfert/pen/MwVYzd.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 76, column 7: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by seyfert** [comment]
One more try: http://codepen.io/seyfert/pen/PqRwXR?editors=101
