### ISSUE TITLE
Avoid reflow when glyphicon load

### ISSUE THREAD

**Issue by Krinkle** [twbs/bootstrap#16768]
Is there a way to make a glyphicon reserve its dimensions so that it doesn't bump the text over when it loads? This would improve perceived performance

**Comment by cvrebert** [comment]
Duplicate of #10022, which was [eventually reverted](https://github.com/twbs/bootstrap/pull/10022#issuecomment-118590542).

**Comment by mdo** [comment]
You can apply custom width/height if you need, but we won't be doing that.
