### ISSUE TITLE
Easier way to customise CSS (e.g. the colours) while still using the CDN css as a base

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#16771]
My website has
`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" >`
`<link rel="stylesheet" href="my.css" >`

But, Iike most people, I want to change the default colour scheme, 
i.e.1 or 2 'less' variables, e.g. @{brand-primary}. 

Option 1) Create my own customised-bootstrap.css files.

The problem is that changing less than 1% of the css means I can no longer use the CDN css file (which hopefully is already cached in the client's browser). This is a massive bandwidth hit for my website, as its quite a big file, way bigger than the web-page html. 

Option 2) Use my own css that overrides the default css...

step 1 - build the default css
step 2 - build the default css with my less @{brand-variable} changes
step 3 - err, diff the 2 files

My Suggestion)

As a simpler way, would it be possible to reorganise the CSS to make it "property" centric, rather than "selector" centric, i.e. 
- each list of selectors has just 1 property-value pair.
- each property-value pair appears just once. 

This means my 'over-ride' css is nice and simple. Probably just 1 or 2 (very long) lines for @{brand-primary} and @{brand-info} 

This means 
- I can still use the CDN css,
- my local css is something like:

`.btn-primary, .bg-primary, .another-selector-primary, ... { color: purple }`
`.btn-info, .bg-info, .another-selector-info, ...  { color: blue }`

The build process could even generate  a "customise-me.css" file, a css snippet which I can include in my site's css, with 1 line for each @{variable}, and I can take what I need.

There might be a better technical way of solving this problem (customising the bootstrap css while still using the CDN css as a base)

**Comment by mdo** [comment]
We won't be going that route. It's an interesting concept, but one that would likely output far more code than necessary and provide little benefit to the project at large.
