### ISSUE TITLE
Tooltips on disabled buttons not working

### ISSUE THREAD

**Issue by jiaweihli** [twbs/bootstrap#16778]
The documentation here: http://getbootstrap.com/javascript/#callout-tooltip-disabled
doesn't work in jsfiddle, as demonstrated here: http://jsfiddle.net/cSSUA/119/

**Comment by twbs-lmvtfy** [comment]
Hi @jiaweihli!

You appear to have posted a live example (http://fiddle.jshell.net/cSSUA/119/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 47, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jiaweihli** [comment]
Bumping jsfiddle link: http://jsfiddle.net/cSSUA/120/

**Comment by jiaweihli** [comment]
@cvrebert

**Comment by patrickhlauke** [comment]
This is, from what I can tell, standard behavior for `<button>` elements with the `disabled` attribute...browsers don't fire `mouseover` events nor allow for other things like context menu etc.

**Comment by jiaweihli** [comment]
This seems to have broken sometime between 3.0.2 (http://stackoverflow.com/a/19938049/759714) and 3.3.5.

**Comment by cvrebert** [comment]
This appears to be due to #16092.
(Which theoretically implies that the technique mentioned in the callout never worked in Opera <=18 or IE<=11 to begin with, per http://getbootstrap.com/css/#callout-buttons-disabled-anchor)

**Comment by patrickhlauke** [comment]
Confirming that re-adding `.btn-default[disabled] { pointer-events:none; }` fixes the behavior here

**Comment by mdo** [comment]
If there's a PR here to fix the broken examples, I'd love to see it proposed so we can merge it. Otherwise, since this is v3 and not mission critical, I'm closing it out.

(Basically I'm declaring defeat on most v3 issues, so expect a surge of issue closures <3.)
