### ISSUE TITLE
.modal-footer .btn + .btn { margin-left: 5px; }

### ISSUE THREAD

**Issue by efkan** [twbs/bootstrap#16770]
<u>Probably not </u>, though, I wanna ask could be there is a mistake? Because if I use a modal-footer class on a modal page, and with a form-inline class my second button on footer seems to be with 5px left indentation because of [the following codes][1].

    .modal-footer .btn + .btn  { 
       margin-bottom: 0px;
       margin-left: 5px;
    }

<b>with modal-footer class</b>
the light pink area 5px margin.
![image](https://cloud.githubusercontent.com/assets/6974198/8511281/0f946250-2318-11e5-952d-3e7901eb42e2.png)

<b>with panel-footer class</b>
![image](https://cloud.githubusercontent.com/assets/6974198/8511291/5ff71602-2318-11e5-8b82-c65d290351c1.png)

[1]:https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L6007

**Comment by cvrebert** [comment]
The code you're referring to ought to be counteracted by https://github.com/twbs/bootstrap/blob/0db18386a295a3fc6bf7bd48a047c0d8aa10a77e/less/modals.less#L120
Please post the actual HTML you're using.

**Comment by cvrebert** [comment]
X-Ref: #5018

**Comment by efkan** [comment]
Hello,

I've overwritten bootstrap.css already. Thanks. Just I want to report the issue.
I see your X-Ref page. It had been duplicated. Sorry...
