### ISSUE TITLE
missing web-bootstrap

### ISSUE THREAD

**Issue by yinonharush** [twbs/bootstrap#16774]
when i try to make a MEAN application
i do bower install

=================================================
the bower.json is this:
{
  "name": "mean",
  "dependencies": {
    "jquery": "latest",
    "angular": "latest",
    "angular-resource": "latest",
    "angular-cookies": "latest",
    "angular-mocks": "latest",
    "angular-route": "latest",
    "bootstrap": "latest",
    "angular-bootstrap": "latest",
    "angular-ui-router": "#master",
    "web-bootstrap": "./node_modules/meanio/resources/web-bootstrap.js"
  }
}

====================================================
error message:
bower  web-bootstrap#*                                                                                                             ENOTFOUND Package ./node_modules/meanio/resources/web-bootstrap.js not found

**Comment by patrickhlauke** [comment]
This has nothing to do with Bootstrap. https://github.com/linnovate/meanio
