### ISSUE TITLE
Jumbotron with outer container has no padding for narrow viewport

### ISSUE THREAD

**Issue by rlindner81** [twbs/bootstrap#16779]
This issue is explained in
https://github.com/twbs/bootstrap/pull/16477

In summary, a fix to unify the jumbotron behavior accross narrow and wide viewports, which corrected the inner container case, broke the same behavior for the outer container case.

See http://jsbin.com/jalohelene/edit?html,output

**Comment by mattblang** [comment]
+1

**Comment by kkirsche** [comment]
@rlindner81 not sure I understand the issue from the JSBin that you've provided

**Comment by rlindner81** [comment]
@kkirsche Did you read #16477 ? There is a lengthy discussion of the issue in there. In the JSBin you see that third (lowest) of the jumbotrons is missing any inner padding when it is rendered in a narrow viewport. That is the issue.

**Comment by kkirsche** [comment]
@rlindner81 I did. Sorry that I misunderstood the conversation...
