### ISSUE TITLE
Allow passing dynamic data to modals

### ISSUE THREAD

**Issue by Ben-Russell** [twbs/bootstrap#16787]
I often use modals for editing items in an application. If, for example, I display a list of items each with an edit button I don't like the idea of creating a separate modal div for each item. To allow using just one modal div I needed a way to dynamically set the fields in the modal window. I realized this was fairly trivial to add by assigning the data to the open button and then populating it to the modal div on `show.bs.modal`.

I have implemented this feature in the pull request below.

It triggers by adding the class `modal-dynamic` to any modal div, and then adding the class `input-dynamic` to any element in the modal. Then before `show.bs.modal` triggers (I figured before would be better, so a listener could interact post dynamic data), any element that has the `input-dynamic` class has it's `name` attribute checked against the open button for a `data-[name]` attribute. Then the `.val()` of the element is set to the value of the data attribute.

I have also added it to the visual and unit tests in the js folder.

Let me know if you have any questions, or need me to change something.

**Comment by patrickhlauke** [comment]
Personally, I think this a very specific solution to your very specific problem, and not something that is worth adding to a very general framework like Bootstrap itself.

Regardless of my own opinion though, we're currently on lockdown for any new features for v.3, to allow for some stablisation in order to concentrate on v.4. Once v.4 is out, we may revisit this request.

**Comment by cvrebert** [comment]
Also, you can easily implement yourself this in your user code using the technique outlined in http://getbootstrap.com/javascript/#modals-related-target
I agree with Patrick that we probably have no interest in adding such specific functionality directly to core Bootstrap.

**Comment by Ben-Russell** [comment]
Yes, this is how I implemented it originally. It seemed odd to me that it wasn't doable natively with data attributes like many of the other features. I understand if it's too specific to not add it though. I guess it's one of those things I come across a lot in the kinds of applications I build, but isn't so common elsewhere.
