### ISSUE TITLE
Rules that should be compiled in bootstrap-theme.css are not.

### ISSUE THREAD

**Issue by teomaragakis** [twbs/bootstrap#16783]
I created a particular workflow for working on WordPress themes (bear with me), which made me see a flaw in the way bootstrap-theme.css is compiled. The issue is that bootstrap assumes that the theme file is compiled with the same variables file as the main bootstrap file, which is not always the case.

Some quick examples are colors, navigation and typography. It seems more logical to me that if I compiled bootstrap-theme.css with a custom color palette, font sizes and families etc, the result should show these colors, even if bootstrap.css is compiled with different variables.

Please discuss.

**Comment by supergibbs** [comment]
The bootstrap-theme isn't for theming bootstrap entirely; it's for restoring the classic 2.0 look. It mostly adds gradients and shadows. 

If you want to customize the whole framework you need to compile the whole thing with your customized variables file.

**Comment by cvrebert** [comment]
What @supergibbs said. `bootstrap-theme` just adds gradients and shadows. Customizing other aspects of Bootstrap involves recompiling `bootstrap.less`/`bootstrap.css`.

> The issue is that bootstrap assumes that the theme file is compiled with the same variables file as the main bootstrap file, which is not always the case.

It is supposed to always be the case. Other usage is incorrect.
