### ISSUE TITLE
form-control-feedback doesn't sustain icon position

### ISSUE THREAD

**Issue by bradyclifford** [twbs/bootstrap#16789]
When an icon is placed inline with a text box using form-control-feedback, the icon does not follow the textbox when the label extends lines.
![capture](https://cloud.githubusercontent.com/assets/8923247/8583687/d6d6aa5a-258c-11e5-93fa-203bfd4d2609.PNG)

**Comment by cvrebert** [comment]
@bradyclifford Please post a [JS Fiddle](http://jsfiddle.net) that demonstrates the problem. We can't debug screenshots.

**Comment by mdo** [comment]
No good way to do that honestly, unless you wrap the input with another class.

**Comment by cvrebert** [comment]
@mdo So, do we close this as CantFix/WontFix then?

**Comment by mdo** [comment]
Yup. I have ideas on how to account for some of this in v4 which I haven't yet gotten around to implementing.
