### ISSUE TITLE
.popover() focus trigger not working on span.glyphicon

### ISSUE THREAD

**Issue by greenafrican** [twbs/bootstrap#16784]
Trying to set multiple triggers `{trigger: "click focus"}` on a popover but it isn't respecting the focus as I can't hide the popover by clicking anywhere else on the screen.

http://fiddle.jshell.net/gLke9bd2/3/

Simple `i` glyphicon:
```
<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
```

And `.popover(options)` declaration.
```
$(document).ready(function () {
	$("span").popover(
	        {'content': "Blah blah blah.",
	            'title': "Title",
	            'trigger': 'focus click',
	        	'placement': 'right'});
}); 
```

**Comment by twbs-lmvtfy** [comment]
Hi @greenafrican!

You appear to have posted a live example (https://fiddle.jshell.net/gLke9bd2/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 46, column 3: [E031](https://github.com/twbs/bootlint/wiki/E031): Glyphicon classes must only be used on elements that contain no text content and have no child elements.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by greenafrican** [comment]
Updated example - http://fiddle.jshell.net/gLke9bd2/3/

**Comment by cvrebert** [comment]
`<span>`s are not focusable in web browsers by default. You must add an appropriate [`tabindex` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to make it focusable.
Closing as not a Bootstrap bug.
