### ISSUE TITLE
Provide an option to not destroy the popover content's DOM when hiding the popover

### ISSUE THREAD

**Issue by DominikVogt** [twbs/bootstrap#16791]
Bootstrap v3.2
When I hide the popover with $(..).popover('hide'); the popover is removed from dom. When i reopen the popover with $(..).popover('show'); the changed content (eg. checked checkbox) is not shown, because the popover had been removed from dom.

asked allready on stackoverflow: http://stackoverflow.com/questions/31310958/bootstrap-popover-is-removed-from-dom-on-close

Any solution to this?

**Comment by cvrebert** [comment]
> Bootstrap v3.2

Bugs are only accepted against the latest version of Bootstrap (currently v3.3.5). In the future, please upgrade before filing a bug.

**Comment by DominikVogt** [comment]
I found a solution to this. Im not quite sure if the content is changed in ..data('bs.popover').options.content according to the changes made in the popovercontent. But for me it didnt, because I have checkboxes, which do not change in html dom.

So I changed the options.content on hide.bs.popover.

If it doesnt work for the newest version as well, this might be something to take into account

```
$(elem).on('hide.bs.popover', function (e) {
	var popover = $(this);
	var popoverContent = popover.data('bs.popover').$tip.find('.popover-content');
	var checkboxes = popoverContent.find("input[type=checkbox]");
	checkboxes.each(function(){ 
		var checkbox = $(this);
		var checked = checkbox.prop('checked');
		checkbox.attr('checked', checked);
	});
	popover.data('bs.popover').options.content = popoverContent.html();
});
```
Needs to be done for all elements.

**Comment by cvrebert** [comment]
Please include the value of `htmlOptions` in your original example.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
