### ISSUE TITLE
.pull-right drops down in IE

### ISSUE THREAD

**Issue by nmaya** [twbs/bootstrap#16798]
The pull-right element in nav menu item drops down in IE. Firefox and Chrome displays as inline.

http://jsfiddle.net/ud0aphcx/4/

**Comment by twbs-lmvtfy** [comment]
Hi @nmaya!

You appear to have posted a live example (http://fiddle.jshell.net/ud0aphcx/4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 47, column 13: [E039](https://github.com/twbs/bootlint/wiki/E039): `.navbar-left` and `.navbar-right` should not be used outside of navbars.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by nmaya** [comment]
This is a fixed example.

http://jsfiddle.net/ud0aphcx/7/

**Comment by twbs-lmvtfy** [comment]
Hi @nmaya!

You appear to have posted a live example (http://fiddle.jshell.net/ud0aphcx/7/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 34, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by nmaya** [comment]
Fixed again.

http://jsfiddle.net/ud0aphcx/9/

**Comment by cvrebert** [comment]
@nmaya What version(s) of IE?

**Comment by nmaya** [comment]
IE11.
And 10 and 9 emulation mode of IE11.

**Comment by cvrebert** [comment]
After adding missing JS, `.navbar-header`, and `.navbar-default: http://jsfiddle.net/cvrebert/d4esnrpy/

**Comment by nmaya** [comment]
Thank you for your advice. But still this issue occurs.
![16798-1](https://cloud.githubusercontent.com/assets/5668936/8609442/2ed1e0fe-26e0-11e5-804d-9e96dbf3940d.png)

**Comment by mdo** [comment]
Probably because your floated content is after the content you're floating around. Anything with a `float` should come first, before the sibling content. So place it before the regular link text and you should have no problem.
