### ISSUE TITLE
.media-right and .media-left positioning

### ISSUE THREAD

**Issue by knbcoder** [twbs/bootstrap#16795]
I've been working on removing some deprecated items from our bootstrap instance and ran into this issue, we are currently running with v3.3.4. When changing the View more link from .pull-right to .media-right it seems it loses the float that had previously been put on the .pull-right class. From the looks of it they are missing float declarations.

It doesn't quite have the styling but you can see the alignment on the last link element when you change from pull-right to media-right

Fiddle: http://jsfiddle.net/07w13nL8/10/

Screenshot: http://imgur.com/tuSJSYU

**Comment by twbs-lmvtfy** [comment]
Hi @knbcoder!

You appear to have posted a live example (http://fiddle.jshell.net/07w13nL8/9/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 45, column 25: [W010](https://github.com/twbs/bootlint/wiki/W010): Using `.pull-left` or `.pull-right` as part of the media object component is deprecated as of Bootstrap v3.3.0. Use `.media-left` or `.media-right` instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by knbcoder** [comment]
I've updated that fiddle. So to see the change you'll have to change it from media to pull to see the issue we're experiencing.

**Comment by mdo** [comment]
Simplifying your markup more (which may have fixed a bug, jsfiddle showed some red code) and removing the references to classes not included in Bootstrap shows no problem in the alignment using media classes: https://jsbin.com/xiluke/edit?html,output. Keep in mind the media alignment classes (e.g., `.media-right`) use table styles, not floats.
