### ISSUE TITLE
Lack of style for presenting error text in forms

### ISSUE THREAD

**Issue by ChameleonRed** [twbs/bootstrap#16805]
I was studied documentation "Forms" and not found any style for error text only decorations and icons.

http://getbootstrap.com/css/

Add some styles for warning, error text.

**Comment by patrickhlauke** [comment]
http://getbootstrap.com/css/#helper-classes ?

**Comment by cvrebert** [comment]
You'd use http://getbootstrap.com/css/#forms-control-validation and `.help-block`.
We probably ought to add `.help-block` to the examples in that section of the docs.
