### ISSUE TITLE
bootstrap.min.css mistyping

### ISSUE THREAD

**Issue by kgordont** [twbs/bootstrap#16803]
Found a few errors in the min file. 
If i remove the \9 it works fine.

input[type=radio]{margin:4px 0 0;margin-top:1px\9;

.radio-inline input[type=radio]{position:absolute;margin-top:4px\9;

.caret{display:inline-block;width:0;height:0;margin-left:2px;vertical-align:middle;border-top:4px dashed;border-top:4px solid\9;

.caret{content:"";border-top:0;border-bottom:4px dashed;border-bottom:4px solid\9

.carousel-indicators li{display:inline-block;width:10px;height:10px;margin:1px;text-indent:-999px;cursor:pointer;background-color:#000\9;

**Comment by kkirsche** [comment]
Could you post browser, OS, etc so we can verify that it doesn't work

**Comment by mdo** [comment]
The `\9` is an IE-specific hack.

**Comment by cvrebert** [comment]
See the third-to-last entry on https://css-tricks.com/snippets/css/browser-specific-hacks/

**Comment by kgordont** [comment]
Google Chrome, version 43.0.2357.134
