### ISSUE TITLE
Add required field style for forms.

### ISSUE THREAD

**Issue by ChameleonRed** [twbs/bootstrap#16806]
I was reading documentation "forms" and not found how to mark required fields.

http://getbootstrap.com/css/#forms

**Comment by cvrebert** [comment]
I'm no UX designer, but marking optional fields seems like it'd make more sense.

CC: @patrickhlauke for accessibility considerations

**Comment by kkirsche** [comment]
@cvrebert personally I think it would depend on the form. I think it's best to mark the one which is the least used. Normally this should be optional but that may not always be the case.

**Comment by patrickhlauke** [comment]
I'd shy away from defining anything in Bootstrap core, especially because some designers will want it one way, while others will want it another way...(and it's easy enough to add manually, rather than forced by the framework)

**Comment by patrickhlauke** [comment]
regarding accessibility considerations, having required fields not styled in any specific way is not directly an accessibility concern, as it would impact all users, not just those with potential disabilities (and in fact, assistive tech users would gain an "unfair" advantage, assuming proper `required` or `aria-required` attributes were used on those form controls, as their AT would announce this while non-AT users wouldn't get an explicit hint unless the designer/developer added it separately, either as part of the label text or through visual styling)

**Comment by mdo** [comment]
Not going to happen in v3 and currently no plans in v4's initial release.

**Comment by ChameleonRed** [comment]
Looks that world not care about accessibility and will not care.

**Comment by mdo** [comment]
@ChameleonRed Unsure what exactly you're saying, but we're not adding features to v3 and v4's initial feature set is locked down at this point. Adding anything else to v4.0.0 would push back the first alpha release. Thus, there's no plans for the current or next major release.

Also, forms should be 100% required. Only ask for what you need in a form, tell folks with clear messaging that you need it, and help folks get through it. Unnecessary form fields detract from a user's experience on your site and add to the burden folks have to get what they want.

**Comment by ChameleonRed** [comment]
@mdo You are doing many wrong assumptions so it directly lead you do sophism - wrong conclusion basing on correct thinking and wrong assumptions.

**Forms should be 100% required** that **totally wrong**.

No all forms is contact forms for customer, not all application is social media for mostly unskilled people which can not focus (distract very fast). Not all application is privacy harvesters which must be simple to get more privacy data from users and has multiple simple form to get all privacy data from user :)

Some forms is for experts, some need to have some optional fields. I will give you simple example - I am doing some expert application which have **project** each project has **name** and optional **description** and I can not mark it with bootstrap since it is not supported.

**name** and optional **description** is nothing special.

Please throw away wrong assumption that optional fields is not need since it is **wrong**.

**Comment by mdo** [comment]
True, I shouldn't have spoken in absolutes. In spirit, forms should be as focused as possible, but I realize that's not always necessary :).

**Comment by ChameleonRed** [comment]
@mdo I often have very wide view - much wider that often people/experts have - You have absolute right in specific case but I can often show wider view where there is other truth.

Clean design is not to use all truths where is need to use one truth - in you case required only is ok, in my case required only is ok with optional - always is true to limit fields to minimum.
