### ISSUE TITLE
Add .col-pr-* to handle columns in print layout

### ISSUE THREAD

**Issue by abusayeedomar** [twbs/bootstrap#16800]
Yes it will add some more classes. Peoples who use bootstrap for mobile first support can't use col-xs for print. They need it for to handle smaller devices. As we use col- classes a lot, it will be great to have something specific to print. There's some issues posted about it.

Here's the JSFiddle: https://jsfiddle.net/3aompwbp/3/embedded/result/ (print preview from browser)

Please tell me if there's anything else to add. If col-pr is not good name, can you suggest something better?

**Comment by twbs-lmvtfy** [comment]
Hi @abusayeedomar!

You appear to have posted a live example (https://fiddle.jshell.net/3aompwbp/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 45, column 3: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 48, column 1: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
We won't be doing that in v3. Maybe after the first v4 ship.

**Comment by davidjb** [comment]
+1, this would be useful for targetting print layouts.  Could this be re-opened for consideration in v4?

**Comment by mdo** [comment]
Going to punt on trying to do anything for print columns. We already have five tiers. Extending our grid system, however, in an external repo could be helpful for those in this thread though I suppose.

**Comment by TheSharpieOne** [comment]
just going to leave this here: https://gist.github.com/TheSharpieOne/27f338c93d5de166ed1e35f5fc753228
