### ISSUE TITLE
Bootstrap accordion and modal - event shown

### ISSUE THREAD

**Issue by joshlopes** [twbs/bootstrap#16815]
On Version: 3.3.4

I have this even listener for modals:

````
_wrapper.on('shown.bs.modal', function(e) {
    $('body').removeClass('modal-open');
});
````

The Event is being triggered when i click on accordion (example from the bootstrap page itself) any reason? i noticed that namespace for the modal is bs.modal and the namespace for the accordion is empty

**Comment by cvrebert** [comment]
@joshlopes We need a JS Bin or JS Fiddle example to be able to help you. And please upgrade to v3.3.5.

**Comment by joshlopes** [comment]
There most be some other plugin that i s changing the behaviour - i couldnt replicate the issue on JS Fiddle. Sorry.

**Comment by cvrebert** [comment]
Thanks! In the future, please try constructing a JS Fiddle before filing an issue, per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports
