### ISSUE TITLE
Modal not displaying correctly

### ISSUE THREAD

**Issue by marccollin** [twbs/bootstrap#16817]
hi

i try to display a basic modal.

In a page with  many tab, when i click on a button, i do an ajax call. If there is no result, i would like to display a modal.

I created a basic demo and get same result here: https://jsfiddle.net/djvxy5mh/

It's like modal is translucid

Picture of the result
![image](https://cloud.githubusercontent.com/assets/4097381/8649622/10c1e2a6-293a-11e5-8f67-b605faeec07e.png)

     <div class="container-fluid">
	<div role="tabpanel">

		<div class="row">
			<div class="span12">
				<nav role="navigation" class="navbar navbar-default navbar-right">

					<form class="navbar-form" role="search">
						<div class="checkbox">
							<label>
								<input type="checkbox" id="inactiveLodger"> Locataire inactif
							</label>
						</div>
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Rechercher" name="srch-term" id="srch-term">
							<div class="input-group-btn">
								<button id="lodgerSearch" type="button"  class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
							</div>
						</div>
					</form>

				</nav>

				<div class="modal fade" id="modalEmptyResult">
					<div class="modal-header">
						<a class="close" data-dismiss="modal">×</a>
						<h3>Résultat de recherche</h3>
					</div>
					<div class="modal-body">
						<p>Aucun résultat ne correspondant à votre requête</p>
					</div>
					<div class="modal-footer">
						<a href="#" class="btn">Fermer</a>
					</div>
				</div>

			</div>
		</div>
		...
	</div>
   </div>

        $('#lodgerSearch').on('click', function (e) {

            var inactiveLodger = $('#inactiveLodger').is(':checked');

            debugger;

            var searchParam = $('#srch-term').val();
            var url = "http://localhost:8080/lodgers/search";
            if (searchParam != "") {
                url = url + "?searchTerm=" + searchParam;
            }

            if (inactiveLodger == true) {
                url = url + "?inactiveLodger=true";
            }

            jQuery.ajax({
                type: "GET",
                url: url,
                success: function (data, status, jqXHR) {
                    debugger;
                    if (data.length == 0) {
                        $("#lodgerSearchResult").empty();
                        $('#modalEmptyResult').modal('show');
                    } else {
                        $("#lodgerSearchResult").empty().append(template(data));
                    }

                },
                error: function (jqXHR, status) {
                    // error handler
                    alert("error " + jqXHR + " -  " + status);
                }
            });
            // e.preventDefault();
        });

**Comment by twbs-lmvtfy** [comment]
Hi @marccollin!

You appear to have posted a live example (https://fiddle.jshell.net/d2tk7xmb/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 49, column 3: [E039](https://github.com/twbs/bootlint/wiki/E039): `.navbar-left` and `.navbar-right` should not be used outside of navbars.
* line 49, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by marccollin** [comment]
https://jsfiddle.net/uhaqg4sz/

**Comment by twbs-lmvtfy** [comment]
Hi @marccollin!

You appear to have posted a live example (https://fiddle.jshell.net/uhaqg4sz/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 49, column 3: [E039](https://github.com/twbs/bootlint/wiki/E039): `.navbar-left` and `.navbar-right` should not be used outside of navbars.
* line 49, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by marccollin** [comment]
With the last release of jquery is not working but that work fine with jquery 1.9.1.

**Comment by zacechola** [comment]
Bootstrap 3 depends on 1.9.1, not the 2.x branch. Though, some cursory looking over your code, looks like you might have a mix of Bootstrap 2 and Bootstrap 3, as well as the issues Bootlint caught.

**Comment by marccollin** [comment]
is there some tool to detect boostrap 2 code?

**Comment by zacechola** [comment]
Yeah. Bootlint caught it, at least for the outdated use of Bootstrap 3. 

I'm mainly making a note of the `.span12` from your pasted in code here on github, I guess, which have been replaced with `.col-*12` in BS3. I don't see it used in the fiddle.

**Comment by cvrebert** [comment]
* Bootstrap v2 is no longer supported 
* Please direct personal support requests to StackOverflow (or similar such forums) rather than this bug tracker
* I'm reasonably sure Bootstrap v3 does support jQuery v2, albeit with a corresponding decrease in support for older browser versions

Thanks!
