### ISSUE TITLE
Hover Effects on Laptops with Touchscreens

### ISSUE THREAD

**Issue by lighthousedesign** [twbs/bootstrap#16819]
I noticed that the hover effects have problems when you are on a laptop with touchscreen or something like a Microsoft Surface. The mouse over works, but when you try to use the touch screen it does not work. Any suggestions to make touch screen function like a tablet even when you have a mouse attached?

**Comment by kkirsche** [comment]
Does this occur in the docs or do you have a JSBin which can be used for testing this behavior?

**Comment by patrickhlauke** [comment]
Can you give specific examples of which constructs/components you have in mind? In general, getting hover/mouseover type things to work on touch is challenging, and in many cases the best approach is to avoid it and to stick with things that get activated explicitly with a `click` or similar.

See also http://patrickhlauke.github.io/getting-touchy-presentation/ (though it's rather lengthy, and needs a few updates) and http://patrickhlauke.github.io/touch/

**Comment by cvrebert** [comment]
This seems to be more of a how-to question, which is out of scope for the bug tracker.

**Comment by patrickhlauke** [comment]
Holding out to see if there's a specific example of a current standard Bootstrap pattern/component which clearly breaks on touchscreens. @lighthousedesign  ?

**Comment by mdo** [comment]
PUNTING.
