### ISSUE TITLE
Safari position:fixed not compatible with push/pull columns

### ISSUE THREAD

**Issue by enbo** [twbs/bootstrap#16814]
Objects with `position: fixed` do not get pulled or pushed like they should be when `col-xs-push-6` or any other pull/push classes are used when viewing in iOS 8.4 Safari. This is not an issue in Explorer, Chrome, Opera, or Firefox to my knowledge.

You can see that the paragraph with "affix" is not pushed to the right like it should be in the example below. Depending on the viewport, the paragraph may be covered by the background color of the left column, since it comes later in the HTML.

http://jsbin.com/kuzenonexe/1/edit?html,css,output
~~http://jsbin.com/dakenacazi/1/edit?html,css,output~~

HTML:
```
<div class="container-fluid">
    <div class="row">
        <div id="pushed-col" class="col-xs-push-3 col-xs-9">
            <p>
                This is a paragraph.
            </p>
            <p class="affix">
                This is a paragraph with "affix". In a desktop browser, you can scroll to verify that its position is fixed.
            </p>
            <div class="extended-col">
            </div>
        </div>
        <div id="pulled-col" class="col-xs-pull-9 col-xs-3">
            <p>
            This is a paragraph from a column lower in the document.
            </p>
            <div class="extended-col">
            </div>
        </div>
    </div>
</div>
```

CSS:
```
#pulled-col {
  background-color: #ee9999;
}
#pushed-col {
  background-color: #99eeee;
}
.extended-col {
  display: block;
  content: "";
  height: 100vh;
}
```

**Comment by cvrebert** [comment]
Your `.col-*`s need to be children of a `.row`, which in turn needs to be a descendant of a `.container` or `.container-fluid`. Dunno whether that affects your issue though.

**Comment by enbo** [comment]
Thanks, cvrebert. It doesn't fix the issue, but I've corrected the HTML.

**Comment by cvrebert** [comment]
I'm not sure what CSS dictates is supposed to happen if you just set `position: fixed` without any `left`/`right`/`top`/`bottom` like that (perhaps @mdo can enlighten me), but I can confirm that both iOS 8.4 Safari and OS X Safari 8.0.7 behave differently from IE11, Firefox, and Chrome on http://output.jsbin.com/yuxebo/2

Safari screenshot:
<img width="924" alt="safari desktop" src="https://cloud.githubusercontent.com/assets/419884/8667703/e339143e-29b7-11e5-8517-2895b67893e5.png">

Chrome screenshot for comparison:
<img width="926" alt="chrome" src="https://cloud.githubusercontent.com/assets/419884/8667724/2933f256-29b8-11e5-9440-652879e4c315.png">

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=147284

**Comment by cvrebert** [comment]
Filed Apple Safari Radar problem: http://openradar.appspot.com/21993128

**Comment by cvrebert** [comment]
There is now a test for this in the W3C CSS WG test suite: https://github.com/w3c/csswg-test/pull/813

**Comment by enbo** [comment]
Hm, I don't think it's actually been fixed yet. I looked at your test (https://bug-147284-attachments.webkit.org/attachment.cgi?id=268137) and it fails on Safari Version 9.1.1 (11601.6.17).

Thanks for passing this bug to the WebKit team!

**Comment by cvrebert** [comment]
@enbo It's fixed in the current [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/). So the fix should be shipped in the next stable Safari release.
Protip: Test using the current [WebKit Nightly](https://webkit.org/nightly/) in the future, rather than stable Safari.

**Comment by enbo** [comment]
Ah, I see.
Thanks for the tip! I'm still very new to bug reporting/testing.

**Comment by jonathanmelville** [comment]
Does anyone know if there is a known workaround to this problem?

I have tried all of the usual Safari hacks (transform: translateX(0) to no avail. Would love to know if anyone has been able to fine a reliable workaround to this problem.

Can confirm this has been fixed in the latest tech preview but that doesn't really help for now.

**Comment by cvrebert** [comment]
Set a non-`auto` value for the `left` or `right` property if possible.
