### ISSUE TITLE
Prepended text height bug

### ISSUE THREAD

**Issue by Chrysanthos** [twbs/bootstrap#16810]
I am using Prepended text for showing a euro sign before the textbox. Also i am using JQuery Validation Plugin ([link to the plugin](http://bassistance.de/jquery-plugins/jquery-plugin-validation/))

When the error message appears under the field the sign of the euro covers 2 lines (the textbox and the error line)

![after](https://cloud.githubusercontent.com/assets/7782312/8637543/760fbdf4-289f-11e5-9a3e-7b1ecbb8f41f.png)

The code
````
<div class="col-md-5">
			<div class="input-group">
			  <span class="input-group-addon">€</span>
			  <input id="worth" name="worth" class="form-control error" placeholder="" type="text" required=""><label for="worth" generated="true" class="error">error message</label>
			</div>
			
</div>
````

**Comment by josephfusco** [comment]
Can you post a working example please with [jsbin](https://jsbin.com/)?

**Comment by cvrebert** [comment]
Putting a `<label>` within an `.input-group` like that is invalid. File a bug against the plugin.

**Comment by phpdev-expert** [comment]
errorPlacement: function ( error, element ) {

            if(element.parent().hasClass('input-group')){
              error.insertAfter( element.parent() );
            }else{
              	error.insertAfter( element );
            }

	},

Use this

**Comment by fajarsapwebdev19** [comment]
thank you very much
