### ISSUE TITLE
all the scrollbar disappear when close the modal dialog or bootstrap dialog

### ISSUE THREAD

**Issue by wstrong** [twbs/bootstrap#16827]
I call the bootstrap modal dialog and the scrollbar could work well, when I call another modal dialog based on the current opened modal dialog, the scrollbar could work well. But when I close the second modal dialog which removes all the scrollbar containing it's parent modal dialog's.
Does anyone know what's wrong with the modal dialog? 

For my understanding, it's caused by close or hide event. But I have no idea how to update it. I think it's a bug of the Bootstrap modal. By the way, I use bootstrap 3.3.4.

I meet the same issue when I call bootstrap confirm  dialog based on a modal dialog, when the confirm dialog close, all the scrollbars have been removed.

The following code show the style I define for the modal dialog.
//The first modal dialog
    .two-column-modal .modal-dialog {
        width: 750px;
        overflow-y: initial !important
    }
//The second modal dialog 
    .modal-dialog-selector {
        width: auto;
        overflow-y: auto;
    }

**Comment by cvrebert** [comment]
As stated in our documentation, Bootstrap explicitly does not support having multiple modal dialogs open at the same time. Thanks!
