### ISSUE TITLE
Downloading "examples" from GetBootstrap.com

### ISSUE THREAD

**Issue by Outlines** [twbs/bootstrap#16823]
Hi,

Will you be adding the ability to actually download the examples from GetBootstrap.com?

Currently there are no buttons or "download" links.

Thanks

**Comment by kkirsche** [comment]
@Outlines while no explicit plans have been made as far as I am aware. You can download them from the repo in `/docs/examples/<desired-example>`

**Comment by cvrebert** [comment]
They are likewise included in the "Source code" download linked on http://getbootstrap.com/getting-started/#download

**Comment by cvrebert** [comment]
@mdo Do you think any action is warranted here?

**Comment by kkirsche** [comment]
@cvrebert I think it may be helpful to specifically call out examples as included not just docs. While I understand the connection, I wouldn't have assumed they were included there.

**Comment by mdo** [comment]
The problem as it stands right now is that the examples aren't 100% standalone—they need local copies of our compiled CSS, JS, etc. Right now they get that from the parent `docs` and `dist` files. If there's a way to inline those referenced CSS and JS files, we could add a Grunt task to ZIP everything up. Unsure how to do that first part myself though.

**Comment by cvrebert** [comment]
Perhaps we could just add to [the examples section of the docs](http://getbootstrap.com/getting-started/#examples) an explanatory sentence and a link, e.g.:
> The code for these examples can be found in the `/docs/examples/` directory of [Bootstrap's source code download.](https://github.com/twbs/bootstrap/archive/v3.3.5.zip)

**Comment by mdo** [comment]
Added a note to the docs per @cvrebert's recommendation.
