### ISSUE TITLE
Allow Showing Original Title for Popover

### ISSUE THREAD

**Issue by AlexeyKosov** [twbs/bootstrap#16822]
Example: http://getbootstrap.com/javascript/#live-demo-1
After initializing Popover plugin on the button, original "title" attribute becomes empty.
But how can I keep it as is if I want the button to show original (browser) tooltip?

**Comment by patrickhlauke** [comment]
You'll have to add extra code for this. I don't think it's a feature we'll be introducing in Bootstrap. I suggest asking on StackOverflow - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
