### ISSUE TITLE
Add more styled buttons

### ISSUE THREAD

**Issue by mateenrehan** [twbs/bootstrap#16833]
Bootstrap only supports 6 types of coloured buttons. We can add other colour buttons like Black for cancel and Brown for Help or so on. It would give developers more options.

**Comment by cvrebert** [comment]
It's pretty easy to add more colors yourself using [the `.button-variant` mixin](https://github.com/twbs/bootstrap/blob/66543ed112e9344d59eba343e3a45200e3ebd839/less/mixins/buttons.less#L6) we provide. It's what we use to [generate the built-in `.btn-*` classes](https://github.com/twbs/bootstrap/blob/66543ed112e9344d59eba343e3a45200e3ebd839/less/buttons.less#L63) (no extra tricks up our sleeves).

**Comment by dongepulango** [comment]
It would be cool if we could have no `border-radius` buttons and half circle corners buttons (like a hotdog) in default by adding just a class.

**Comment by cvrebert** [comment]
> It would be cool if we could have [square-cornered] buttons

In Bootstrap v4, there will be a new variable to enable/disable `border-radius` globally.

**Comment by dongepulango** [comment]
Awesome! Can't wait, when can we expect v4? I think @mdo tweeted it like a year ago. Keep up the good work guys.

**Comment by kkirsche** [comment]
@dongepulango sometime in August.

**Comment by mdo** [comment]
Closing per previous comments.
