### ISSUE TITLE
Gulp-jshint raises warnings. 

### ISSUE THREAD

**Issue by Tjoosten** [twbs/bootstrap#16837]
A time ago i was hinting the js files with gulp. and i get several warnings back. 

https://gist.github.com/Tjoosten/5094d32f190e3dfc4f2f <- cli report 

is this a bug or can this be fixed?

**Comment by kkirsche** [comment]
This is a style preference by the lead JS developer of bootstrap, @fat and will not be changed.

**Comment by cvrebert** [comment]
Duplicate of #3057.
