### ISSUE TITLE
Panel heading border is cut off

### ISSUE THREAD

**Issue by mking** [twbs/bootstrap#16847]
Because the panel heading sets a background color, this background color overflows the panel border radius, causing the panel heading border to appear thinned out at the bottom left and right corners.

The fix is to set border radius on the element that sets the background color (`.panel-heading`) when the panel is collapsed.

[Minimal JSFiddle demonstrating the issue](http://jsfiddle.net/kgg8wj9o)
* I tried fixing the issue, but my fix only works in the collapsed state.
* My guess is that a pure CSS fix requires a collapsed class on the panel heading element (or a parent).

Occurs in the following browsers:
* Mac OS X Chrome 43.0.2357.134
* Mac OS X Firefox 39.0
* Mac OS X Safari 8.0.7

**Comment by Khrysller** [comment]
I think I have faced this situation here #13941

**Comment by mdo** [comment]
Your issue sounds slightly different @Khrysller. I also don't recall seeing this behavior previously, wonder if something changed.

**Comment by jared-christensen** [comment]
Over flow hidden on the panel seems to solve the problem.
https://jsfiddle.net/jaredly2/kgg8wj9o/1/

**Comment by mdo** [comment]
Closing as a won't fix since we'd need to add additional classes here to make it really work. There's no way the parent element knows it's in a collapsed state right now.
