### ISSUE TITLE
Bootstrap media object is messing

### ISSUE THREAD

**Issue by ezekel** [twbs/bootstrap#16849]
Can I ask some help, I am using media object ,the problem is that if the content in media body is large it will not align properply. I am loading the media object dynamically. 
here is my code.

```php
    for(var i=0;i<data.length;i++){
                    mymdedia+=
                        '<div class="media col-sm-3">'+
                          '<div class="media-left">'+
                             '<a href="#">'+
                                '<img src=".....">'+
                              '</a>'+
                          '</div>'+
                             '<div class="media-body">'+
                                 '<h4 class="media-heading">'John Doe'</h4>'+
                                 '<p>Live: '+data[i].address+'</p>'+
                           
                              '</div>'+
                        '</div>';
            }
    $('#mycontainer').append(mymdedia);
```

here is my index

```html
     <div class="someclass">
                      <div class="row" id="mycontainer">

                      </div>
                </div>
```

This is image result it's messing

![ask](https://cloud.githubusercontent.com/assets/6830057/8764525/2db69a9a-2e13-11e5-9a8d-a64979b257e7.jpg)

Thank you in advance.

**Comment by neilhem** [comment]
Because of bootstrap's grid based on floated columns they are not aligned properly. Solution: add rows after each forth media element.
```html
<div class="row">
  <div class="media col-sm-3">
    ...
  </div>
  <div class="media col-sm-3">
    ...
  </div>
  <div class="media col-sm-3">
    ...
  </div>
  <div class="media col-sm-3">
    ...
  </div>
</div>

**Comment by ezekel** [comment]
@neilhem can you please show me how can I apply that in my for loop.

Thank you in advance

**Comment by patrickhlauke** [comment]
Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker please direct your personal support queries to StackOverflow or similar.

**Comment by cvrebert** [comment]
> Solution: add rows after each fourth media element.

Or add `clearfix` divs as demonstrated in http://getbootstrap.com/css/#grid-responsive-resets

**Comment by ezekel** [comment]
@neilhem, I Fixed it now following your suggestion. Thank you so much

**Comment by ezekel** [comment]
@cvrebert ,

Thank you for the reply where should I put the clearfix class in the fourth row ?
