### ISSUE TITLE
input-group-btn with badge in button has incorrect height in Firefox

### ISSUE THREAD

**Issue by AdamSelene** [twbs/bootstrap#16859]
When using a badge as button label in a input-group-btn, the height of the button is incorrect (34.3667px instead of 34px on FF 39) and can even mess with its siblings alignment.
Forcing the height of the button to 34px fixed it.
For instance, using the following snippet (from the 'segmented buttons' example, simply changing the label of the first button to use a badge) :
```
<div class="input-group">
    <div class="input-group-btn">
        <button class="btn btn-default" type="button">
            <span class="badge">1</span>
        </button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>
    <input class="form-control" aria-label="Text input with segmented button dropdown" type="text">
</div>
```

![capture](https://cloud.githubusercontent.com/assets/79495/8824895/6a13367e-307a-11e5-8987-c34c72f4a4ff.PNG)

**Comment by kkirsche** [comment]
@AdamSelene can you post a JSBin or JSFiddle demonstrating the issue? We can't debug images and don't prefer to debug static code.

**Comment by AdamSelene** [comment]
Sure, my bad:
https://jsbin.com/tisehi/3/edit?html,output

**Comment by mdo** [comment]
Closing as a won't fix—likely a problem with the font rendering or pixel rounding. Given our stance on v3 (vs v4), it's not mission critical and not much worth out time hunting down more Firefox edge cases. Sorry for the inconvenience <3.
