### ISSUE TITLE
Absolute Center (Vertical & Horizontal) “Responsive” it does not work

### ISSUE THREAD

**Issue by unehub** [twbs/bootstrap#16856]
Hello,

I'm use Bootstrap 3.3.5 and demo **30-lazy-load-images**, The problem is that the container can not have a fixed height(px), it must be "100% or auto" for it to be compatible with the responsive design. 

Check this demo http://jsfiddle.net/9s75kkxp/3/

    .swiper-container {
        width: 100%;
        height: 500px; // Only work if star height eg 500px, but need this container responsive 100% or auto.
    }

![captura de pantalla 2015-07-21 a las 2 57 00 p m](https://cloud.githubusercontent.com/assets/12479371/8811092/08965690-2fb9-11e5-9d5b-88df75ee95eb.png)

If set height: 100% or auto, .swiper-container height not initialize "0". How can we solve this? the image must be centered like the lazy load

**Comment by twbs-lmvtfy** [comment]
Hi @unehub!

You appear to have posted a live example (http://fiddle.jshell.net/9s75kkxp/3/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 99, column 23 thru line 99, column 99: Element ```` img ```` is missing required attribute ```` src ````.
* line 104, column 23 thru line 104, column 99: Element ```` img ```` is missing required attribute ```` src ````.
* line 108, column 23 thru line 108, column 99: Element ```` img ```` is missing required attribute ```` src ````.
* line 112, column 23 thru line 112, column 99: Element ```` img ```` is missing required attribute ```` src ````.
* line 116, column 23 thru line 116, column 99: Element ```` img ```` is missing required attribute ```` src ````.
* line 120, column 23 thru line 120, column 99: Element ```` img ```` is missing required attribute ```` src ````.
* line 80, column 11 thru line 80, column 154: The ```` aria-controls ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
> I'm use Bootstrap 3.3.5 and demo **30-lazy-load-images**

Bootstrap does not include such a demo.
