### ISSUE TITLE
Disabled div on click event not blocked

### ISSUE THREAD

**Issue by dan77l** [twbs/bootstrap#16855]
With a disabled div, \<div disabled="disabled"\>, in bootstrap 3.3.5 the div is styled as disabled but the click event fires:
https://jsfiddle.net/gjm38whe/1/

With bootstrap 3.1.1 the on click event was blocked:
https://jsfiddle.net/gjm38whe/

In both examples above, click the Toggle button to disable the Click button.

**Comment by twbs-lmvtfy** [comment]
Hi @dan77l!

You appear to have posted a live example (https://fiddle.jshell.net/gjm38whe/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.1.1
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.1.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dan77l** [comment]
@twbs-lmvtfy My inclusion of the Bootstrap 3.1.1 example was intentional to show that it used to work and now doesn't.

**Comment by cvrebert** [comment]
The `<div>` HTML element does not support the `disabled` attribute. Attempting to use the `disabled` attribute on a `<div>` results in invalid HTML (it will fail to [validate](https://validator.w3.org/nu/)). Bootstrap does not attempt to support invalid HTML.

Additionally, the `.btn-*` classes are only intended for use on `<a>`s, `<button>`s, and `<input>`s, not `<div>s`.

So, you're on your own here. Good luck!

**Comment by patrickhlauke** [comment]
To expand on this, I believe (though not dug through the JS for 3.1.1) that the reason it used to work was that the old JS was naively checking for the `disabled` attribute, while in more recent versions it goes through more rigorous checks to ensure it only acts on the intended elements as well.

**Comment by cvrebert** [comment]
I'm pretty sure it's because of our `pointer-events: none` tweak (#16092).

**Comment by patrickhlauke** [comment]
ah, that rings a bell. right you are.

**Comment by dan77l** [comment]
I changed my code to use `<button type="button"></button>`. Everything is working now, and valid! Thanks!!
