### ISSUE TITLE
Accordion title overlaps with chevron on small viewports

### ISSUE THREAD

**Issue by davidcafu412** [twbs/bootstrap#16853]
Dear Sifus / Masters of Bootstrap,

I'm having issues of the accordion panel title clashing with the chevron indicator when the panel title is really long. This occurs when viewed in mobile view and desktop view (when browser is sized at a c-certain size). I need help to solve this problem. I have attached a screenshot of the issue below
 ------------------------------------------------------------------------------------------------------------------------------

![capture](https://cloud.githubusercontent.com/assets/13431949/8796465/92e92166-2fc7-11e5-843d-3f07e5600b38.PNG)

 ------------------------------------------------------------------------------------------------------------------------------

here is my source code, in case you need it:

https://gist.github.com/davidcafu412/215e8128858220128531#file-code-html

 ------------------------------------------------------------------------------------------------------------------------------

Thank you all in advance. :+1:

**Comment by cvrebert** [comment]
@davidcafu412 Could you please repost the example as a JS Bin or JS Fiddle?

**Comment by cvrebert** [comment]
Note that the [vanilla Bootstrap accordion](http://getbootstrap.com/javascript/#collapse-example-accordion) does not use any chevrons.

**Comment by davidcafu412** [comment]
http://jsfiddle.net/davidcafu412/a61fqof0/1/

**Comment by cvrebert** [comment]
Try moving the glyphicon to *before* the `<a class="accordion-toggle">` instead of after it.

**Comment by davidcafu412** [comment]
it worked!!! thanks alot.

damm...such a simple solution to a simple problem, yet it drove nuts.

**Comment by cvrebert** [comment]
You're welcome. For future how-to questions, please try asking on [StackOverflow / IRC / Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community) first instead.
