### ISSUE TITLE
.carousel-indicators do not work

### ISSUE THREAD

**Issue by mrbacay** [twbs/bootstrap#16869]
`.carousel-indicators` do not navigate to slides as expected when I add classes to each `li` item. Is that not allowed?

**Comment by cvrebert** [comment]
We cannot help you without a concrete example that demonstrates the problem.

**Comment by mrbacay** [comment]
An indicator is marked up like so:
`            <li id="innovation" class="indicator" data-target="#first-fold" data-slide-to="1">
              <h4 class="text-uppercase">Innovation</h4>
              <h4>Our own technology&#8212;light years ahead!</h4>
            </li>
`
with the following style:
`  .carousel-indicators {
    width: 480px;
    height: 480px;
    text-align: initial;
    margin-bottom: initial;
    position: relative;
    left: initial;
    display: flex;
    flex-flow: wrap;
    .indicator {
      flex: 0 0 50%;
      height: 50%;
      text-indent: initial;
      padding: 24px 18px;
      margin: 0;
      border: initial;
      border-radius: 30px;
      position: relative;
      z-index: 1;
  }
}
`

**Comment by cvrebert** [comment]
@mrbacay Please use JS Bin or JS Fiddle for your example. Thanks.

**Comment by mrbacay** [comment]
Not sure why it's not rendering as how it renders on my local machine, but here it is: https://output.jsbin.com/hifufozina

**Comment by cvrebert** [comment]
> Not sure why it's not rendering as how it renders on my local machine

You posted Less/Sass into JS Bin's CSS field. That doesn't work; it needs to be CSS.

**Comment by mrbacay** [comment]
Somehow the indicators seem to be sliding the carousel on the JS Bin after I converted the Sass code to CSS. This really confuses me.

Thanks for putting that it's supposed to be CSS code there into my attention, by the way.

**Comment by mrbacay** [comment]
I get it now. There's a psuedo-element over the indicators on my local machine. I fixed it by adding `pointer-events: none;` to that element.

Thanks for my question!
