### ISSUE TITLE
Fixed navbar jumps around on iOS Chrome

### ISSUE THREAD

**Issue by andycorm** [twbs/bootstrap#16864]
Fixed elements at the top of the screen on the iOS version of Chrome tend to jump around once the keyboard is out. This issue is not specific to Bootstrap, but will affect all websites using the Bootstrap fixed navigation. I'd fix this for my website specifically, but all the solutions I can find look pretty hacky. Any chance we could get a bootstrap bundled patch for this in the next release? I've brought it up to the Chromium team, but they dismissed it as an iOS quirk. (Which it probably is, but I figure that doesn't mean it isn't worth looking at since Apple has yet to have fixed it in the last two years.)

You can find more information at the links below:
https://code.google.com/p/chromium/issues/detail?id=441592 (Crystal clear example of what the issue is)
https://code.google.com/p/chromium/issues/detail?id=298936 (Another user with the same issue that had Google respond directly)

**Comment by mdo** [comment]
Definitely an iOS thing—opening that keyboard fubars anything that's `position: fixed`. We mention some of this in http://getbootstrap.com/getting-started/#support-fixed-position-keyboards.
