### ISSUE TITLE
_glyphicons.scss issue

### ISSUE THREAD

**Issue by thirdtiu** [twbs/bootstrap#16861]
i'm having problems with `line 10` of _glyphicons.scss

```css
@at-root {
    @font-face {...}
}
```
glyphicons doesn't load
when removing `@at-root`, it works fine

**Comment by patrickhlauke** [comment]
define "problems". running the build tasks per http://getbootstrap.com/getting-started/#grunt doesn't throw any errors for me...

**Comment by kkirsche** [comment]
Also, I'd recommend opening this in Bootstrap-Sass repo

**Comment by patrickhlauke** [comment]
doh! @kkirsche is right, of course. https://github.com/twbs/bootstrap-sass

**Comment by cvrebert** [comment]
Note that bootstrap-sass currently requires sass>=3.3
See https://github.com/twbs/bootstrap-sass/issues/920
