### ISSUE TITLE
Inline form wraps when multiple input-group adds up to 12 column

### ISSUE THREAD

**Issue by cycotron69** [twbs/bootstrap#16866]
I'm using grid style classes to size my input-group within an inline form.  However, in cases where the total # of columns for the input-groups adds up to 12 columns, the last input-group will wrap. See [jsfiddle](https://jsfiddle.net/Cycotron69/wqs1950j/1/) example.

This is typical behavior with inline-blocks when the parent (such as <body>) element have a font-size > 0 where non-zero width white space is introduced between elements.

I'm currently getting around this by setting the font-size for the <form> element to 0.  However, that would require explicitly setting font-sizes for all child elements of <form>.  This could be tedious in large forms with many embedded text blocks.  I would be great to have a more elegant solution here.

**Comment by twbs-lmvtfy** [comment]
Hi @cycotron69!

You appear to have posted a live example (https://fiddle.jshell.net/Cycotron69/wqs1950j/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 39, column 17: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`
* line 43, column 17: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`
* line 47, column 17: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`
* line 39, column 17: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 43, column 17: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 47, column 17: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cycotron69** [comment]
Looks like that was it.

**Comment by kkirsche** [comment]
@cycotron69 Glad you got it "resolved". :+1:
