### ISSUE TITLE
Selectively include bootstrap modules with version 3.1.1.0

### ISSUE THREAD

**Issue by patrickbjohnson** [twbs/bootstrap#16875]
Is there a way to selectively include bootstrap `scss` / `js` modules in version `3.1.1.0`. 

Based on the documentation it seems like the only way to include all bootstrap files is simply adding `@import 'bootstrap';` to the main `application.scss` file. 

We are in a position where we do not need all components. 

Wish we could upgrade but running an app in rails 3.2.

**Comment by cvrebert** [comment]
Sorry, but how-to questions about old versions are outside the scope of this bug tracker.
Please direct such questions to StackOverflow, IRC, or Slack instead: https://github.com/twbs/bootstrap/blob/master/README.md#community
Thanks!

**Comment by patrickbjohnson** [comment]
It's actually been resolved via https://github.com/twbs/bootstrap-sass#configuration

**Comment by cvrebert** [comment]
Glad to hear that :smile:
