### ISSUE TITLE
Tooltip/Popover focus+click trigger not working as expected.

### ISSUE THREAD

**Issue by adityatj** [twbs/bootstrap#16870]
I've been meddling with popover for quite some time using a combination of focus and click trigger. Looks like the popover behavior is unpredictable. Please observe the following fiddle.

http://jsfiddle.net/adityatj/wcxxss8u/1/

**Comment by ernestopye** [comment]
:+1:

**Comment by dahoste** [comment]
Yup.  On 3.3.1 that combo ('focus click') mostly worked.  If you showed the popover with a direct click, then dismissed via a focus change (clicking on something else) and then tried to reshow with another direct click, the popover would show and then immediately dismiss itself again (implying that BS didn't entirely tell itself that the focus-based dismiss actually hid the popover, so the next click-based show got confused about the actual state of the popover).

Anyway, on 3.3.6 (as evidenced by the jsfiddle of the OP), it's considerably *WORSE* than before.  The combo seems to produce a popover that is downright dysfunctional.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
