### ISSUE TITLE
Modal not working sometimes on click event

### ISSUE THREAD

**Issue by lenerey** [twbs/bootstrap#16873]
I am new here and wanted to bring a problem I'm having in developing an application.
I put the code here to explain what happens :

ASPX
```html
<label class="col-md-2 control-label col-xs-12">Producto</label>                                        
<div class="col-md-3 col-xs-10">                                            
	<asp:TextBox runat="server" ID="_newProducto" CssClass="form-control" autocomplete="off" onkeypress="return CheckProductoN(event);"></asp:TextBox>
	<asp:UpdatePanel ID="UpdatePanel3" runat="server" >
		<ContentTemplate>
			<asp:Panel ID="busquedaProducto" runat="server" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="busquedaProducto" aria-hidden="true">
				
			</asp:Panel>     
		</ContentTemplate>
		<Triggers>
			<asp:AsyncPostBackTrigger ControlID="buMPDesripcion" EventName="Click" />
			<asp:AsyncPostBackTrigger ControlID="buMPCodigoAlterno" EventName="Click" />
		</Triggers> 
	</asp:UpdatePanel> 
</div>
<div class="col-md-1 col-xs-2">
	<asp:LinkButton runat="server" ID="buMPDesripcion" data-toggle="busquedaProducto" CssClass="btn blue" Text="Mostrar" OnClick="_buConfirmarProducto_Click"><i class="fa fa-search"></i></asp:LinkButton>
</div>

<script>

jQuery(document).ready(function () {
$('#buMPDesripcion').click(function () {
            var descripcionCantidad = document.getElementById("_newProducto").value;
            if (descripcionCantidad.length <= 4) {
                alert("Debe introducir como minimo 5 caracteres a la hora de buscar el producto");
            }
            else {
                setTimeout(function () { $('#busquedaProducto').modal('show') }, 400)
            }
        });
});

function CheckProductoN(e) {
        if ((e.keyCode && e.keyCode == 13) || (e.which && e.which == 13)) {
            var obj = document.getElementById("buMPDesripcion");
            if (obj) {
                obj.click();
            }
        }
    }
	
</script>
```
I build the modal code from the server and so far I have no problems where the problems start is the time to show .
It is that sometimes when I click the asp: LinkButton in the first sometimes I open the black background and I do not get modal and already for the second time if I get good data showing no problems.
But when I'm in the text box and enter me I should show modal and not what you do, just do it when I leave the crowded and sometimes enter when they closed me loose .
Yes please can you help me with this I would appreciate it .
Excuse my English .
Thanks in advance.

**Comment by lenerey** [comment]
excuse the code is not show , how should I put it to show it

**Comment by kkirsche** [comment]
Personal support requests should be directed to StackOverflow or the Slack / IRC chat platforms. 

For bugs with the framework, please post a JSBin or JSFiddle including the code to demonstrate the issue. In the future, code on GitHub should be wrapped with backticks (`) for inline code or 3 backticks for code blocks.

**Comment by cvrebert** [comment]
See https://github.com/twbs/bootstrap#community for more info on the community support forums mentioned.
Closing since we can't provide assistance with problems related to backend frameworks, such as ASP.
