### ISSUE TITLE
Please set default gutter to 10px between columns.

### ISSUE THREAD

**Issue by shiralizadeh** [twbs/bootstrap#16882]
Please set default gutter to 10px between columns in next version of bootstrap, our team thinks it's wrong to be 30px...

**Comment by MehdiDehghani** [comment]
I think in your team, you have at least 1 girl, am I right?

**Comment by shiralizadeh** [comment]
دهنت سرویس از کجا فهمیدی؟
Services mouth how did you know?

**Comment by mdo** [comment]
You can customize this if you like, but we'll probably be sticking to the v3 values for it.
