### ISSUE TITLE
Customizer not clear that Collapse requires Component animations

### ISSUE THREAD

**Issue by dagobert** [twbs/bootstrap#16893]
I have customized the bootstrap download to include "panel" and "collapsible". The resulting CSS file is missing at least two rules to make collapsible work:

.collapse {
    display: none;
}
.collapse.in {
    display: block;
}

Here is my customization link:
https://gist.github.com/94dfe9871cc382dfa3f9

**Comment by kkirsche** [comment]
@dagobert I'd first mention that per the documentation, collapse requires the transition JS which means you also need the Component animations (for JS) LESS attribute checked.

http://getbootstrap.com/javascript/#collapse

Here is a corrected `config.json` file.
https://gist.github.com/kkirsche/5016ef3796c7897d5f11
