### ISSUE TITLE
form-control class not works with input[type="file"]

### ISSUE THREAD

**Issue by ChameleonRed** [twbs/bootstrap#16899]
Using form-control on file input renders not need frame.

**Comment by Herst** [comment]
Formatting file controls needs specials tricks, like drawing something below a hugely scalled file input that has been made transparent (but still clickable).

**Comment by cvrebert** [comment]
`.form-control` should indeed not be used on file inputs. This is why our docs don't include file inputs in the list of form controls that `.form-control` can be used on.
