### ISSUE TITLE
I think I might find a BUG

### ISSUE THREAD

**Issue by maokelong** [twbs/bootstrap#16891]
For example, part of my HTML document goes like this

< div class="col-md-2">
https://www.test.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=nsdfgdfgdfg&rsv_pq=8a2e28240001cc27&rsv_t=51d8pdXJrJqseV5GWZmXyynpYSrH5IQIljMo%2F68WstEL%2BWvSR26N0mYD3fc&rsv_enter=0&oq=sdfgdfg&inputT=281&rsv_sug4=419
< /div>

I supposed all of my URL string was wrapped in the outer DIV, however, I just receive the wrong feedback.

You try, and you will get what I mean.

------

Pardon me for my English is not very good , but I am working on it .

![pic](https://cloud.githubusercontent.com/assets/12730912/8894179/6d532dcc-33df-11e5-9793-117307f2ba18.png)

**Comment by omegahm** [comment]
This is happening because of the natural word breaks in your browser. It sees the `-` and thinks it can break the word there.

If you do not want this, you can add `word-break: break-all;` to the style.

Take a look at this JSFiddle for an example: https://jsfiddle.net/a6o6pef1/1/

**Comment by twbs-lmvtfy** [comment]
Hi @omegahm!

You appear to have posted a live example (https://fiddle.jshell.net/a6o6pef1/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 50, column 32: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 36: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 45: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 54: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 69: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 93: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 163: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 175: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 186: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 50, column 197: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
This is not something that we'll be forcing/adding in Bootstrap core. You'll need to take care of non-breaking content that's too wide yourself, I'm afraid.

**Comment by maokelong** [comment]
Thanks !

**Comment by TimoSolo** [comment]
couldn't you add wrap to <code> tags? would be useful.
