### ISSUE TITLE
Calendar and scheduler components

### ISSUE THREAD

**Issue by Leon-O** [twbs/bootstrap#16907]
I want to know if there are plans to create a calendar and/or scheduler components like http://fullcalendar.io/ and http://fullcalendar.io/scheduler/?

**Comment by cvrebert** [comment]
Negative, due to the level of complexity and our team's limited manpower.
But there are a few third-party Bootstrap-based widgets for this, such as https://github.com/eternicode/bootstrap-datepicker

See also https://github.com/twbs/bootstrap/issues/445#issuecomment-13169107

**Comment by Leon-O** [comment]
Thanks for your fast response, but I don't speak about a "date-picker", I'm talking about a "calendar of events" component.
![20150729-4](https://cloud.githubusercontent.com/assets/4379316/8970461/ce82857c-3617-11e5-96dc-aa54287f688a.PNG)
![20150729-7](https://cloud.githubusercontent.com/assets/4379316/8970539/3bbfd220-3618-11e5-9805-eb208950722e.PNG)

But, I understood that all of you are to busy.

**Comment by cvrebert** [comment]
Yeah, no plans for that either.
