### ISSUE TITLE
input-group is too long when used in form-horizontal

### ISSUE THREAD

**Issue by chrisbloom7** [twbs/bootstrap#16905]
When using a horizontal form, input groups end up being longer than their sibling fields. I've created https://jsfiddle.net/z0L72nn1/1/ to demonstrate on the latest 3.3.5 bootstrap. 

* * *

![bootstrap-input-group-form-horizontal](https://cloud.githubusercontent.com/assets/21250/8964612/932e1f54-35f4-11e5-9298-6e2cad3890b7.png)

**Comment by twbs-lmvtfy** [comment]
Hi @chrisbloom7!

You appear to have posted a live example (https://fiddle.jshell.net/z0L72nn1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 46, column 5: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by chrisbloom7** [comment]
Revised - Switched to Bootstrap 3.3.4 to avoid bootlint errors. Removed wrapping `.container`

https://jsfiddle.net/z0L72nn1/2/

**Comment by twbs-lmvtfy** [comment]
Hi @chrisbloom7!

You appear to have posted a live example (https://fiddle.jshell.net/z0L72nn1/2/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 45, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 56, column 9: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`
* line 68, column 9: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by chrisbloom7** [comment]
> .input-group and .col-*-* cannot be used directly on the same element

Oh, well, you should update your docs. Also, how can W012 and E003 both be true? It's what http://getbootstrap.com/examples/grid/ uses...

**Comment by kkirsche** [comment]
@chrisbloom7 not sure I follow you. [W012](https://github.com/twbs/bootlint/wiki/W012) is `.container or .container-fluid should be the first child inside of a .navbar` and [E003](https://github.com/twbs/bootlint/wiki/E003) is `Found one or more .rows that were not children of a grid column or descendants of a .container or .container-fluid`.

Both of those are followed in the example page. Individual examples of components are not representations of how they should be deployed in production (e.g. you shouldn't copy and paste the examples/grid page as your entire page and expect that to be correct). For fully accurate examples in context use the provided examples found here: http://getbootstrap.com/getting-started/#examples

**Comment by cvrebert** [comment]
>> .input-group and .col-- cannot be used directly on the same element

> Oh, well, you should update your docs.

Guess what, we don't need to, because they *already explicitly* mention this: http://getbootstrap.com/components/#callout-inputgroup-dont-mix
Try reading more carefully in the future :smile:

**Comment by chrisbloom7** [comment]
@cvrebert, ah, thank you for pointing that out. I've got 3 bootstrap tabs open and I feel like I scoured them pretty thoroughly, as well as googled for the solution. Seems like I wasn't thorough enough. Consider me corrected.

@kkirsche The grid page _is_ from the examples section, so i'm not sure what I should be using for reference if not that. The entire grid page is wrapped with a `.container`, and E003 says a `.row` must be in a `.container`, but W012 says `.container` is only valid as the first child inside of a `.navbar`. How can both be true? Additionally, http://getbootstrap.com/css/#grid-intro says "Rows must be placed within a .container (fixed-width) or .container-fluid". The linter seems to contradict this.

Secondarily, I first got a W013 error even though I was using 3.3.5, which is the latest according to http://getbootstrap.com/getting-started/#download, but the linter complained and I ended up having to downgrade to 3.3.4 in my example.

**Comment by cvrebert** [comment]
> but W012 says .container is only valid as the first child inside of a .navbar

You have that a little backwards. The only valid first child of `.navbar` is a container. But containers have uses other than in navbars.
Perhaps we ought to rephrase W012 to clarify this.

**Comment by cvrebert** [comment]
> Secondarily, I first got a W013 error even though I was using 3.3.5, which is the latest according to http://getbootstrap.com/getting-started/#download, but the linter complained and I ended up having to downgrade to 3.3.4 in my example.

Did you edit the GitHub issue description after you posted it? Your description currently mentions https://jsfiddle.net/z0L72nn1/1/ , but @twbs-lmvtfy's comment mentions  (https://fiddle.jshell.net/z0L72nn1/ . Note the lack of the trailing `/1`.

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/z0L72nn1/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 56, column 11: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`
* line 68, column 11: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/z0L72nn1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 46, column 5: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by chrisbloom7** [comment]
> Did you edit the GitHub issue description after you posted it? Your description currently mentions https://jsfiddle.net/z0L72nn1/1/ , but @twbs-lmvtfy's comment mentions (https://fiddle.jshell.net/z0L72nn1/ . Note the lack of the trailing /1.

I'm a dolt. An angry, angry dolt. Yes, I originally submitted it with https://fiddle.jshell.net/z0L72nn1/, then realized it was showing some old code that I forked so I updated the jsfiddle and edited the issue to use the new link. It was only afterward that the @twbs-lmvtfy comment appeared, so I thought it was for the updated code.

Yes, I think rephrasing W012 is a good idea. Apologies to @kkirsche as well. This was all a tired-eyes user error, pebcak, RTFM, etc.

![May god have mercy on my soul](http://s2.quickmeme.com/img/db/db0629a737a0aa046b8e3c804481c554f69a1a07014dc48c4e74516dd838fae4.jpg)

**Comment by twbs-lmvtfy** [comment]
Hi @chrisbloom7!

You appear to have posted a live example (https://fiddle.jshell.net/z0L72nn1/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 56, column 11: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`
* line 68, column 11: [E012](https://github.com/twbs/bootlint/wiki/E012): `.input-group` and `.col-*-*` cannot be used directly on the same element. Instead, nest the `.input-group` within the `.col-*-*`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @chrisbloom7!

You appear to have posted a live example (https://fiddle.jshell.net/z0L72nn1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 46, column 5: [W012](https://github.com/twbs/bootlint/wiki/W012): `.container` or `.container-fluid` should be the first child inside of a `.navbar`
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
