### ISSUE TITLE
Using grid inside modal misalignment

### ISSUE THREAD

**Issue by julzmon** [twbs/bootstrap#16902]
When using the recommended .container-fluid grid inside modal creates misalignment with modal-title.
The title and modal-body aren't aligned. Is this by design or a bug?

http://getbootstrap.com/javascript/#modals-grid-system

![screen shot 2015-07-28 at 12 51 26 pm](https://cloud.githubusercontent.com/assets/46877/8937707/3cb76d00-3528-11e5-9b8f-ab3f584d4a73.jpg)

**Comment by robertvasile** [comment]
using .container-fluid there or any other container makes no sense, since modals have their own behaviour; just don't use the .container-fluid, place the rows directly in modal-body

**Comment by cvrebert** [comment]
CC: @mdo
