### ISSUE TITLE
Feature request: Option to have the navbar slide out from a side on mobile devices

### ISSUE THREAD

**Issue by rohithpr** [twbs/bootstrap#16906]
Many native applications designed for mobile devices have menus that slide out from a side. Bootstrap navbar's slide out from the top. It would be really cool if we have the option to get something that slides out from a side.

While this could be done by using CSS and some hidden-xs (etc.) classes, having the option within bootstrap itself would make life simpler.

**Comment by cvrebert** [comment]
There's the Off-canvas navigation example: http://getbootstrap.com/examples/offcanvas/

**Comment by cvrebert** [comment]
Duplicate of #9481.

**Comment by rohithpr** [comment]
@cvrebert - The example that you've provided does not turn the navbar that's on top into a side menu. That still slides out from the top.
What I had in mind when I opened this issue was something like [this](http://gdgbangalore.in/).

**Comment by cvrebert** [comment]
Right, I didn't say it was exactly the same. It's pretty similar though.

**Comment by rohithpr** [comment]
So there's no chance that you'll provide this option? :(

**Comment by cvrebert** [comment]
Not for v3. It's a *possibility* for v4, but no promises.

**Comment by rohithpr** [comment]
@cvrebert - Now that v4 is being readied, I'd like to bring your attention to this. Any chance of this becoming a feature on v4? :)

**Comment by cvrebert** [comment]
This falls under the

> Navbar
> * Add drawer variation? twbs/bootstrap#9481

bullet point on #17021.
So really there hasn't been any change since my previous comment.

**Comment by slidenerd** [comment]
Even that example doesnt quite cover it, what we need is that the content stays in place but the sliding menu appears on top
