### ISSUE TITLE
Have a problem with ocmposer bower asset update

### ISSUE THREAD

**Issue by kLkA** [twbs/bootstrap#16900]
Hi, im trying to use composer update depending on your  repository

Adding VCS repository bower-asset/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap/contents/bower.json?ref=master
Downloading https://api.github.com/repos/twbs/bootstrap/commits/master
Downloading https://api.github.com/repos/twbs/bootstrap/tags?per_page=100
Downloading https://api.github.com/repos/twbs/bootstrap/git/refs/heads?per_page=100

  [UnexpectedValueException]
  Could not parse version constraint <=2.*: Invalid version string "2.*"
It happens on 2 different computers but not happen on remote, can you help me with that?

**Comment by lynicidn** [comment]
duplicate https://github.com/twbs/bootstrap/commit/9b1a213cf758e1b60e20c59a721a63e13da098f7

**Comment by cvrebert** [comment]
See https://github.com/francoispluchino/composer-asset-plugin/issues/129
