### ISSUE TITLE
docs for target/relatedTarget of Tab events are somewhat unclear

### ISSUE THREAD

**Issue by mrbacay** [twbs/bootstrap#16910]
Not sure if I understood the documentation correctly. Did I not?

`jQuery('#list-features').on('shown.bs.tab', function(e) { console.log(e.relatedTarget); })`

**Comment by cvrebert** [comment]
It is working as intended. Visually speaking, the anchor is the part that looks like a tab.
However, I agree that the docs' phrasing is somewhat ambiguous and could stand to be clarified.

**Comment by mrbacay** [comment]
Thanks for clarifying it

**Comment by mdo** [comment]
Punting as a won't fix unless someone has a specific suggestion in a PR to share. <3
