### ISSUE TITLE
Add vertical space between buttons when pushed onto another line

### ISSUE THREAD

**Issue by MichaelRushton** [twbs/bootstrap#16912]
At the moment if a list of buttons is pushed onto another line the buttons crash into each other as shown here:

![screen shot 2015-07-30 at 10 01 10](https://cloud.githubusercontent.com/assets/681130/8979484/fa77f330-36a1-11e5-8e42-be1e20970c12.png)

It would be nice if some vertical space was added like so:

![screen shot 2015-07-30 at 10 01 14](https://cloud.githubusercontent.com/assets/681130/8979491/06565a20-36a2-11e5-8e20-690811c6f4f1.png)

As a simple suggestion, perhaps wrapping the buttons in a `<div class="btn-grid">` and use the following CSS:

    .btn-grid
    {
        margin: -2px 0;
    }
    
    .btn-grid > .btn
    {
        margin: 2px 0;
    }

An example fiddle is here: https://jsfiddle.net/90y4hvmv/

**Comment by twbs-lmvtfy** [comment]
Hi @MichaelRushton!

You appear to have posted a live example (https://fiddle.jshell.net/90y4hvmv/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 50, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 51, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 52, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 53, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 54, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 55, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 61, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 62, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 63, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 64, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 65, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 66, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by MichaelRushton** [comment]
Updated fiddle: https://jsfiddle.net/90y4hvmv/1/

**Comment by mdo** [comment]
I don't think this is something we need to solve—seems like a rather specific set of styles depending on the content and context. Thanks though.
