### ISSUE TITLE
Scroll preservation when viewing documentation

### ISSUE THREAD

**Issue by olegberman** [twbs/bootstrap#16924]
1. Go to http://getbootstrap.com/css/
2. Scroll down to **Grid options** with your browser window at **~750px**.
3. Now shrink the page down to a mobile version **~350px**.

You can see how the scroll position is lost, you've had your focus on the **Grid options** paragraph and now it's gone. This is a normal workflow when a person is reading docs (or something else) and then wants to put let's say his/her browser window side by side with their code editor window. Right after resizing the window the media query fires and colons go on top of each other - the height of the entire document increases, whereas the scroll stays at the same position as it was before. That makes you lose the place where you were reading and sometimes it's very hard to find where you were before (the more responsiveness - the harder it is).

This can be solved by adding a class `scroll-preserve`; javascript will look for such elements and if they are inside current viewport it will after resize scroll to the same place as it was before resize. There also could be other better solutions but this one sounds as the most efficient. 

Anybody else noticed this inconvenience? Any thoughts on it?

**Comment by kkirsche** [comment]
@olegberman Personally I don't find this as a problem but rather something that affects most responsive designed sites I have ever used ranging from major sites such as CNN to small homegrown sites. With that said, I'm not necessarily opposed to fixing it with a JS-based solution as long as the total code size wasn't anything substantial.

**Comment by mdo** [comment]
Reload the page with that `#` in the URL and you'll be alright. That's not a solution, but this isn't a huge priority for us and not something we want to implement and maintain moving forward. Perhaps worth noting this has been asked before, but I can't recall an issue # or anything.
