### ISSUE TITLE
How make Custom Layout Form?

### ISSUE THREAD

**Issue by yosacyber** [twbs/bootstrap#16929]
![capture](https://cloud.githubusercontent.com/assets/3403508/9043455/be6295d4-3a3f-11e5-968c-d60458d37c22.png)

How to make custom layout form?

**Comment by patrickhlauke** [comment]
Please use StackOverflow or similar for personal support requests. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
