### ISSUE TITLE
alert.js does not dismiss alert when clicking the button

### ISSUE THREAD

**Issue by nholiphant** [twbs/bootstrap#16928]
Works
alert.js prior to 3.3.0 contains the line --> $parent = $this.hasClass('alert') ? $this : $this.parent()

Doesn't work
alert.js 3.3.x contains the line --> $parent = $this.closest('.alert')

**Comment by kkirsche** [comment]
@enbuscadetesoro per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by nholiphant** [comment]
Turns out the issue is with @extend through bootstrap-sass not picking up parents, siblings or children properly. It's not a bug in bootstrap. Thanks
