### ISSUE TITLE
Tooltip/popover viewport padding not working when right aligned

### ISSUE THREAD

**Issue by ctigelaar** [twbs/bootstrap#16936]
I stumbled upon this issue on the current project I'm working on. When using a tooltip or popover aligned to the right of the screen, the viewport padding option is not working. Left aligned tooltips/popovers do respect the value of this option. I haven't tested other viewport selectors, I used the default `body` selector. Tested in Chrome 44 on OSX.

I know in v4 another positioning library will be used and this probably is a won't fix, but I thought it was worth noting.

See: https://jsfiddle.net/ctigelaar/kgghxsjs/3/

**Comment by ctigelaar** [comment]
Just found out the problem only occurs when using multiline content for the tooltip/popover. Single line tooltips/popovers do respect the viewport padding value.

**Comment by cvrebert** [comment]
Punting as WontFix per https://github.com/twbs/bootstrap/issues/15590#issuecomment-113321235
Patches would be welcomed, but Core Team doesn't have the time/bandwidth to write a patch ourselves.
