### ISSUE TITLE
Cards with Tabs

### ISSUE THREAD

**Issue by 0wczar** [twbs/bootstrap#16934]
I wonder why no combination for Bootstrap - **"Panel with Tabs"**.
Even the simplest. It is very often used a combination of applications, for example: "GitHub".

Is it possible?
![bootstrap-panels-with-tabs](https://cloud.githubusercontent.com/assets/2330394/9056423/35a79484-3a93-11e5-9eba-091ad1a57a57.png)

**Comment by abitdodgy** [comment]
This would be very useful in v4, but since panels are gone, it would have to apply to cards.

**Comment by hnrch02** [comment]
Tagging as a feature request for v4. cc @mdo

**Comment by 0wczar** [comment]
I've seen Cards in Bootstrap 4. Great stuff.
I have another proposal for **"Panel / Card with List Group"**

But I think that Tab (not active) should be colored blue (as a link)
What do you think?

![zrzut ekranu 2015-08-23 15 01 09](https://cloud.githubusercontent.com/assets/2330394/9428278/d2a803fe-49a7-11e5-8fc6-ae928d6c1df7.png)

**Comment by matt-hernandez** [comment]
@0wczar Did you actually make code to provide us with these screenshots, or are these mock-ups?

I'm eager to try my hand at coding a feature for v4 soon. But if you've already got code, then this one is yours.

**Comment by mdo** [comment]
Basics of this added in 955e0405.
