### ISSUE TITLE
Using grid system inside a .well

### ISSUE THREAD

**Issue by mrbscott** [twbs/bootstrap#16933]
When using the grid layout inside a `.well` the grid goes past the `.well` if the contents of a column exceed it's size.

Here is a Fiddle of the issue: https://jsfiddle.net/crxv61zt/2/

It would be fantastic if grids can be confined within a `.well`.

**Comment by kkirsche** [comment]
X-Ref: #1446

**Comment by mdo** [comment]
Use a fluid container: https://jsfiddle.net/crxv61zt/4/. Nothing will be changed for this in v3, so closing as a won't fix for now.
