### ISSUE TITLE
UI Unit Tests via CSS: Automatically show errors in code

### ISSUE THREAD

**Issue by aleemb** [twbs/bootstrap#16939]
The basic premise is based on the article [UI Unit Tests via CSS: Automatically catch errors in your code, in production](https://medium.com/@aleemb/ui-unit-tests-via-css-automatically-catch-errors-in-your-code-in-production-6f75826ec170).

It would be useful to include and work upon a `tests.css` stylesheet that is included in development environments and automatically catches and reports errors via the UI.

**Comment by kkirsche** [comment]
@aleemb isn't that basically just Bootlint?

**Comment by mdo** [comment]
Neat idea, but not something we'll put in v3 and maybe not even v4 given our Bootlint bot as @kkirsche mentions. We'll keep it in mind though!

**Comment by aleemb** [comment]
@kkirsche wasn't aware of Bootlint, makes sense and fits the bill. I suppose this is a different approach to tackle the same problem with the benefit that it can run on a dynamic and growing dataset, runs in the client's context and requires no further tooling after initial setup except updating the CSS.

**Comment by ndixita** [comment]
xamdo93qwerty
