### ISSUE TITLE
img-responsive and Firefox 39.0

### ISSUE THREAD

**Issue by PELock** [twbs/bootstrap#16940]
Firefox cannot handle properly .img-responsive class for the thumbnails, it ignores the default max-width property and stretches out the image within the .thumbnail container if the image is wider than the container itself. Default settings for the .img-responsive class:
```
.img-responsive(@display: block) {
  display: @display;
  max-width: 100%; // Part 1: Set a maximum relative to the parent
  height: auto; // Part 2: Scale the height according to the width, otherwise you get stretching
}
```
This class is inherited by .thumbnail class for all the images:
```
.thumbnail {
  ...
  > img,
  a > img {
    &:extend(.img-responsive);
    ...
}
```
I'm using sample code from http://getbootstrap.com/components/#thumbnails to display the thumbnails.

I've tried to set "width: 100%" to the .img-responsive and it works fine, until I've figured it out all the images not within the .thumbnail class container are stretched out.

The solution that works for Firefox for Windows and Android is to add "width: 100%" to the:
```
.thumbnail {
  ...
  > img,
  a > img {
    &:extend(.img-responsive);
    width: 100%;
    ...
}
```

**Comment by kkirsche** [comment]
@PELock can you post a JSBin demonstrating the problem and state what operating system you are using. I don't see any issues on Firefox 39 at the section you mentioned.

<img width="1098" alt="screen shot 2015-08-05 at 11 23 17 am" src="https://cloud.githubusercontent.com/assets/947110/9089682/69fa4944-3b64-11e5-9aba-0c5b68759101.png">

**Comment by lookfirst** [comment]
Odd, I just ran into this. A large image in the grid wasn't resized until I added width: 100%. 

Firefox 42.0a2 (2015-08-24) developer edition.

**Comment by cvrebert** [comment]
@lookfirst Screenshot?

**Comment by lookfirst** [comment]
@cvrebert 

FF with width: 100%: http://take.ms/eBtka
FF without width 100%: http://take.ms/dxiQ6 (broken)

Chrome (without width 100%): http://take.ms/clkL7

**Comment by lookfirst** [comment]
BS 3.3.5

**Comment by cvrebert** [comment]
@lookfirst We need a JS Bin or other simplified live example of the problem in order to be able to investigate further.
