### ISSUE TITLE
Tooltip examples with html content

### ISSUE THREAD

**Issue by miksh7** [twbs/bootstrap#16941]
It would be nice to have simple example(s) showing how to:
- define an inline html content for a tooltip
- use a function to define html content for a tooltip

**Comment by cvrebert** [comment]
Retargetting at v4 since v3 is in maintenance mode.

**Comment by mdo** [comment]
No specific plans to do this for tooltips—if you need custom HTML, I suggest using the popover instead <3.

**Comment by mdo** [comment]
Wait, misread that. We could add some examples for that since we already support it. My bad!

**Comment by mdo** [comment]
This was added with #16941—coming in Alpha 5.
