### ISSUE TITLE
Modal unscrollable after input focus in iOS safari

### ISSUE THREAD

**Issue by mduveborg** [twbs/bootstrap#16944]
How to reproduce: 
- Open a modal that's higher than the window height
- Focus an input field
- Press "done" in the iOS keyboard

You can no longer scroll to the bottom of the modal :(

jsbin: 
https://jsbin.com/hagiyojufu
( https://jsbin.com/hagiyojufu/1/edit?html,css,js,output )

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <[bootstrap] Modal unscrollable after input focus in iOS safari (#16944)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kkirsche** [comment]
@heralder99 I believe you have an auto-responder set up like has happened in the past. If you could please shut it off that would be greatly appreciated!

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [bootstrap] Modal unscrollable after input focus in iOS safari (#16944)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by zacechola** [comment]
This is very much related to #14839, I believe.

**Comment by cvrebert** [comment]
Closing as probable duplicate.
