### ISSUE TITLE
Tooltipe

### ISSUE THREAD

**Issue by andrey59** [twbs/bootstrap#16948]
<a href="#" data-toggle="tooltip" title="Some tooltip text!">Hover over me</a>

<div class="tooltip top" role="tooltip">
  <div class="tooltip-arrow"></div>
  <div class="tooltip-inner">
    Some tooltip text!
  </div>
</div>
Your example not work. Show title="Some tooltip text!" in <a , why then <div class="tooltip top".

**Comment by mdo** [comment]
Please re-consult our docs—tooltips work just fine. If you have a bug report, please submit a demonstrable bug report with something like JS Bin.

**Comment by andrey59** [comment]
Sorry, I was wrong. All work fine.

2015-08-07 12:32 GMT+05:00 Mark Otto <notifications@github.com>:

> Please re-consult our docs—tooltips work just fine. If you have a bug
> report, please submit a demonstrable bug report with something like JS Bin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/16948#issuecomment-128622002>.
>



-- 
С уважением, Журихин Андрей
