### ISSUE TITLE
ie10-viewport-bug-workaround.js missing in bower package.

### ISSUE THREAD

**Issue by websafe** [twbs/bootstrap#16943]
`ie10-viewport-bug-workaround.js` used in examples is not embedded in the bower package of `bootstrap`. This makes building combined/minimized/compressed javascript libraries with Grunt harder. Would be great to have it there.

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <[bootstrap] ie10-viewport-bug-workaround.js missing in bower package. (#16943)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kkirsche** [comment]
@websafe I believe that is due to it being a CC3 license since it is in the docs not the MIT license of the core. I may be mistaken as I think there was discussion of changing that. @cvrebert or someone other than me (not on a cell phone) could probably double check that one way or the other.

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [bootstrap] ie10-viewport-bug-workaround.js missing in bower package. (#16943)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by websafe** [comment]
@kkirsche OK, I think I've found a solution :-) There is a dedicated bower package containing this file https://github.com/Haixing-Hu/bootstrap3-ie10-viewport-bug-workaround so I'll use it.

**Comment by cvrebert** [comment]
@kkirsche We already relicensed it; see https://github.com/twbs/bootstrap/commit/c111c291be426c5e91ceb1b8fe506d0df9818a2d

**Comment by websafe** [comment]
@cvrebert So can I assume it will be available in the bower package of `bootstrap` and https://github.com/Haixing-Hu/bootstrap3-ie10-viewport-bug-workaround won't be needed anymore?

**Comment by cvrebert** [comment]
No. Like the other user-agent string sniffing browser hacks, we don't consider it part of Bootstrap proper. See also http://getbootstrap.com/getting-started/#support-ie10-width
