### ISSUE TITLE
Collapse Plugin: [data-toggle="collapse"] isn't respecting initial state for setting 'collapsed'

### ISSUE THREAD

**Issue by hurgleburgler** [twbs/bootstrap#16951]
I'm hitting an issue with Bootstrap 3's Collapse plugin, where I have added a caret to the [data-toggle="collapse"] element, and change the direction of the caret depending on the class .collapsed

Here is a jsfiddle showing the problem here: http://jsfiddle.net/Wc4xt/2743/
The caret for the second panel should be pointing down, and the caret for the first panel should be pointing to the right.

When the default accordion panel to be open isn't the first panel, on initial page render, Bootstrap is putting 'collapsed' on all [data-toggle="collapse"] elements except for the first one.  It seems like it might be making the assumption that the default panel to open is always the first.

**Comment by cvrebert** [comment]
> on initial page render, Bootstrap is putting 'collapsed'

Bootstrap doesn't perform any Collapse DOM adjustments at page load or Collapse plugin initialization time.
