### ISSUE TITLE
Unwanted gap while using panel heading with smaller sizes.

### ISSUE THREAD

**Issue by mbsmt** [twbs/bootstrap#16952]
Hi. It seems that there is a bug or something like that on bootstrap panel.
When I use panels with a smaller size (for example col-md-6), a new left and right margin comes with panel (body and heading).

This is a simple implementation of what I said:
http://codepen.io/mbsmt/pen/eNXmoY

**Comment by twbs-lmvtfy** [comment]
Hi @mbsmt!

You appear to have posted a live example (http://codepen.io/mbsmt/pen/eNXmoY.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 3: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mbsmt** [comment]
![capture](https://cloud.githubusercontent.com/assets/8167221/9144898/7a5ca87e-3d65-11e5-81a2-42f24a3e9fa7.JPG)

**Comment by cvrebert** [comment]
Don't put the `.col-md-6` directly on the `.panel` in this case: http://codepen.io/anon/pen/WvmvRq

**Comment by mbsmt** [comment]
Thank you cvrebert.
