### ISSUE TITLE
Dropdown menu enhancements

### ISSUE THREAD

**Issue by Hemanth089** [twbs/bootstrap#16953]
Hi the following page has some drop down enhancement which are very nice. It would be nice if you adopt this enhancements in bootstrap 

http://behigh.github.io/bootstrap_dropdowns_enhancement/index.html

**Comment by kkirsche** [comment]
Hey @Hemanth089 — thanks for sharing! V3 is currently frozen though in preparation for V4 public beta later this month. May be something that could be incorporated into V4 though.

**Comment by cvrebert** [comment]
A lot of the features are related to using Dropdowns as [Select2](https://select2.github.io)/[Selectize](http://brianreavis.github.io/selectize.js/)-like widgets. Due to the complexity, I think it's unlikely that the team would want to implement+maintain such features.

**Comment by patrickhlauke** [comment]
Indeed, as they also prove more challenging to convey accessibly...

**Comment by cvrebert** [comment]
The other major enhancement is submenus, which were deliberately removed in Bootstrap 3. You can argue the wisdom of that, but I don't think @mdo is inclined to revisit that decision any time soon.
