### ISSUE TITLE
Safari: active <li> doesn't have proper CSS

### ISSUE THREAD

**Issue by Buzz2Buzz** [twbs/bootstrap#16963]
Hi, 

Active li tag hasn't got proper CSS on Safari version 5.1.7. Text has the same color even if active.
I don't know for other versions.
Tested on Chrome, Firefox and IE (11) and it works.
Test it here: 
http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_case_navbar7

Something I missed ? Thanks !

**Comment by kkirsche** [comment]
@Buzz2Buzz what OS. Please be aware we only support the latest version of software and at least on OS X that is Safari 8.0.7. Safari on Windows is not supported:

http://getbootstrap.com/getting-started/#support-browsers

**Comment by Buzz2Buzz** [comment]
I tried on Windows, now I understand lol sorry.
But on my colleague Mac with OS X and Safari 8.0.7, it doesn't work too ...

**Comment by kkirsche** [comment]
Seems to work for me in Safari 8.0.7:

http://jsbin.com/nopuheresu/edit?html,output

![screen shot 2015-08-10 at 9 45 03 am](https://cloud.githubusercontent.com/assets/947110/9172895/83c2f748-3f44-11e5-92b6-6b84608d52b6.png)

**Comment by Buzz2Buzz** [comment]
Click on Page 1, 2 or 3 ? Text keeps white color ?

**Comment by kkirsche** [comment]
Unless you have implemented a way to change the active link, we do not do that for you. That is 100% up to the implementer to include how they move the `.active` class between items in the navbar.

**Comment by Buzz2Buzz** [comment]
I'm ok with that. 
But just try to click on a page link with Safari and then Chrome. There's a difference, where does it come from ?

**Comment by kkirsche** [comment]
@Buzz2Buzz it sticks for a minute because when clicked it gains `:focus` but doesn't have anywhere to go so it doesn't lose `:focus` on the new page load as it would in a normal situation. I don't see any other changes though

**Comment by Buzz2Buzz** [comment]
Nothing to do with page reloading, it's just about active li selected CSS. Maybe I don't understand something ...

**Comment by kkirsche** [comment]
I'm not sure I follow. When you click one of the page's, the item is `:focus`ed. This uses the same styles as `.active` but is not active. This is why a second click then removes the color from the link because it is in the focused state. The active class never moves.

Focus State: https://developer.mozilla.org/en-US/docs/Web/CSS/%3Afocus

**Comment by Buzz2Buzz** [comment]
Ok, I'll try to work on that and if something's wrong I'll show up here again, thanks for your replies !
