### ISSUE TITLE
open twitter bootstrap modal window (Custom HTML Forms ) from iframe into the parent window?

### ISSUE THREAD

**Issue by ghosh-arindam** [twbs/bootstrap#16969]
I have a parent page with an iframe, and inside this iframe are some html forms that should open a modal window in the parent window,when called from parent page. The thing is I dont have access to put code into the parent window. I just have access to this iframe. Is there a way this could be done with jquery and bootstrap with such limitations?

I have posted in stackoverflow: http://stackoverflow.com/q/31941987/4561922

**Comment by patrickhlauke** [comment]
As per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker, Stackoverflow is your best bet for these sorts of questions.
