### ISSUE TITLE
Trying to understand a behavior...

### ISSUE THREAD

**Issue by GearTheWorld** [twbs/bootstrap#16962]
Hi,

Can someone explain why the content of my html is resized bigger just before resizing normally and that the top position changes ?

For instance with an image I added the class "img-responsive" which works pretty well but why the behavior we see here ?  Everything is position absolute maybe that's why but I need to understand.

![bootstrapexample](https://cloud.githubusercontent.com/assets/8614008/9170467/237b305c-3f31-11e5-8463-962f4b47cb29.gif)

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by GearTheWorld** [comment]
So you really thing it's a bug ?  Maybe best is to know first if it's a bug or something I do wrong by asking me questions !  I also don't understand why it is closed so early ?

**Comment by cvrebert** [comment]
This does seem like it was closed prematurely.

@GearTheWorld We do need a JS Bin though, in order to be able to evaluate whether or not it's a bug in Bootstrap. Please create one and post it at your earliest convenience. Thanks!

**Comment by cvrebert** [comment]
@GearTheWorld Please also tell us what browser you're using.

**Comment by GearTheWorld** [comment]
Ok sorry I misunderstood the close thing.  Ok I'll do the repro and do it the right way. working on it...

**Comment by GearTheWorld** [comment]
Hmm I'm not sure anymore. Isn't respond.js that does this resizing thing or it's really bootstrap ? If it's respond, who should I contact then ?

**Comment by kkirsche** [comment]
@GearTheWorld HTML5 shim and Respond.js are for IE8 support of HTML5 elements and media queries

**Comment by cvrebert** [comment]
> If it's respond, who should I contact then ?

https://github.com/scottjehl/Respond/issues

**Comment by GearTheWorld** [comment]
I'm completely lost.  That's why I needed help to understand.  What exactly does this resizing thing specially when I have nothing configured in any tag for classes to do that thing.  The only thing I have is an image that have class = "img-responsive" everything else has no class but it looks like it adapts the content automatically.  Just referencing bootstrap and respond and having everything position absolute and as you can see in the gif, things start to resize itself smaller as I reduce the size of the browser.  I really don't know what does this resizing job ?

It would help to know what does this job in order to send repro or whatever needed to the right people

**Comment by kkirsche** [comment]
Essentially, media queries cause it. This is a decent guide to responsive website design which may be helpful to understand: http://blog.teamtreehouse.com/beginners-guide-to-responsive-web-design

**Comment by GearTheWorld** [comment]
That's a good start.  I'll try my best to understand this whole thing regardless of the issue I have which I don't know what and where to look at to know why it's doing what it does ;)

Thank you !
