### ISSUE TITLE
.navbar-default (& .navbar-nav?) should be covered more explicitly in the docs

### ISSUE THREAD

**Issue by skibulk** [twbs/bootstrap#16961]
The following classes are used in the latest bootstrap CSS, but not explained in the documentation: .navbar-nav & .nav-divider

It makes me wonder if there are more undocumented / orphaned classes...

**Comment by kkirsche** [comment]
Undocumented, probably. There area number of classes / mixins which aren't meant for external / public API use but are for internal use. Also remember V4 is coming out shortly so I wouldn't expect the V3 public API to be expanded

**Comment by skibulk** [comment]
Shouldn't private classes be on a separate stylesheet from the core bootstrap css? Will these classes be documented in v4?

Likewise, the effects of .navbar-default are not explained. It seems to me that .navbar should have all the default styles? Is navbar-default the opposite of navbar-inverse?

**Comment by kkirsche** [comment]
I doubt that every class will be documented and it doesn't make sense to make internal component classes a separate spreadsheet. It just adds complexity for no reason. Default is light color and inverse is dark coloring.

**Comment by kkirsche** [comment]
Navbar holds the common styles for all navbars of any colors.

**Comment by cvrebert** [comment]
> Is navbar-default the opposite of navbar-inverse?

Yes.

> The following classes are used in the latest bootstrap CSS, but not explained in the documentation: [...] .nav-divider

`.nav-divider` is extremely deprecated, hence why it's not documented:
https://github.com/twbs/bootstrap/blob/3487898a6af8c1d5b12f7b040d30e71b19e34923/less/navs.less#L56

**Comment by skibulk** [comment]
Thanks to both of you. Navbar-Nav is even used in the BS Example code. What does that do?

**Comment by cvrebert** [comment]
As shown in the examples, it's used for the list of links in the navbar.

**Comment by mdo** [comment]
Punting on any changes here—I think the existing docs are getting the job done.
