### ISSUE TITLE
Jumbotron : Padding fail

### ISSUE THREAD

**Issue by NEQII** [twbs/bootstrap#16972]
A'm I the only one, who got trouble with the class (jumbotron). It has no padding when i resize the screen to "XS (Extra Small)".

They wrote the padding into the class: .jumbotron
But they have to do it directly into the .jumbotron like this: 

.container .jumbotron, .container-fluid .jumbotron
{
       padding: 20px;
};

**Comment by kkirsche** [comment]
Duplicate of #16779
