### ISSUE TITLE
Switch to JS Bin vanity URL for reduced testcase template in docs

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#16977]
i.e. http://bootstrap.jsbin.com
As soon as https://twitter.com/mdo/status/631642152561324032 gets resolved, that is.

**Comment by kkirsche** [comment]
Nice. Good to know about this :+1:

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by mdo** [comment]
Closing this out as I don't think this is doable at all. We can link to the output, but I haven't seen anything done to allow us to link to the editor itself. We already have the link in the docs, and it's being used well enough, so punting on anything more here.
