### ISSUE TITLE
.label without .label-* is invisible

### ISSUE THREAD

**Issue by aDarkling** [twbs/bootstrap#16976]
Thanks for this excellent framework!

One problem though. Form labels started showing up as white text on white background on a 3rd-party web app. The issue is that the labels have the class "label", not "label-default/warning/whatever".

bootstrap.css defines "color" only in .label & then specifies only the background in .label-default, so if .label-default isn't called, only the font color is changed!

Although its more verbose, the best way to fix this is to define @label-color & @label-link-hover-color in each of the .label-xxxx sections and to define @text-color & @link-color in .label so that doesn't remain a problem if there's any older subordinate bootstrap.css CDN files involved.

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by mdo** [comment]
Need a JS Bin example to understand what you're seeing.

`.label` isn't for `<label>`s. It's another component entirely and does require a modifier class at all times—e.g., `.label.label-default`.

**Comment by cvrebert** [comment]
> bootstrap.css defines "color" only in `.label` & then specifies only the background in `.label-default`, so if `.label-default` isn't called, only the font color is changed!

Yes, having a base class (`.btn`, `.label`) which is required to be used in combination with a "variant" class (`.btn-*`, `.label-*` ; typically color-related) is a common design pattern in Bootstrap's components. It is invalid to use just the base class by itself, hence your problem.
I don't think it's worth trying to accommodate invalid code or unported Bootstrap v2 code like you're suggesting; down that route lies many complications and eventual madness.

> so that doesn't remain a problem if there's any older subordinate bootstrap.css CDN files involved.

Bootstrap v2 and v3 are incompatible with each other, so I expect such a site to encounter a lot of breakage, some of it much worse than just `.label`s having incorrect colors. We advise against trying to mix Bootstrap v2 with Bootstrap v3 in the first place.

**Comment by aDarkling** [comment]
Ok, JsBin snippet at http://jsbin.com/waneyo

I understand that its just a base class that designed to be paired with a modifier class, but if the base class has a name commonly used in existing 3rd party-generated markup we should try to not have it "disappear" output.  Especially when that possibility can be easily avoided.

In this particular instance the HTML wasn't written or intended for Bootstrap.   It was only because it was included in page output of a site that was using Bootstrap that the issue became apparent.  Or not apparent, actually.  The last thing that you'd think of checking for is that someone wrote a CSS class that turns something into white on white.  On purpose!

I did a pull request that fixes it.  #16982

**Comment by mdo** [comment]
Punting per https://github.com/twbs/bootstrap/pull/16982#issuecomment-130973743.
