### ISSUE TITLE
@carousel-control-font-size is ignored on larger screens

### ISSUE THREAD

**Issue by pehlert** [twbs/bootstrap#16973]
Apparently the @carousel-control-font-size setting is ignored on larger screens by hard-coding it to 30px here: https://github.com/twbs/bootstrap/blob/master/less/carousel.less#L243

Can someone point out whether this has been a deliberate decision and if so, what the reason behind it was? Otherwise I'll submit a pull request later which fixes this issue.

Cheers,

Pascal

**Comment by pehlert** [comment]
@kkirsche Brilliant, thanks. Not sure, but I think the margins should also be adjusted dynamically to ```@carousel-control-font-size * 1.5 / 2```. This may also make sense for the "non-media-queried" styles.

**Comment by kkirsche** [comment]
That was something which I had certainly considered, though I had thought through it as `@carousel-control-font-size * -0.75`. I wanted to get feedback from the core team first though as it starts to seem abusive of the variable which is already being used in such a way that it doesn't really fit the name so it could have unexpected consequences.

I believe mdo is in favor of avoiding adding more variables, so I wanted to wait and better understand their feeling(s) on (ab)using the variable for things like margins

**Comment by pehlert** [comment]
Totally agree, let's wait for the core team to get back on this!

**Comment by mdo** [comment]
Wait, what exactly is the problem? Is the issue that some property or value is being ignored, or is the issue that we've got set `30px` values here?

**Comment by kkirsche** [comment]
@mdo that there are hard coded values instead of using proportional values when customized with the variables.

**Comment by mdo** [comment]
Gotcha. Are there values to update anywhere else? Could be helpful to see a JS Bin with the changes to see if we need anything else tweaked.

**Comment by pehlert** [comment]
@mdo The size of the carousel control arrows (which are glyphicons) should be controllable through the ```@carousel-control-font-size``` variable. That works fine on screens smaller than ```@screen-sm-min```, but is broken on all other devices where for some reason the hard-coded value of ```30px``` is used.

**Comment by kkirsche** [comment]
@mdo my PR calculates to the same values. It just uses the variables so if changed they adjust accordingly.
