### ISSUE TITLE
On Esc, toggle bootstrap dialog

### ISSUE THREAD

**Issue by laxmikantG** [twbs/bootstrap#16979]
Generally, on Esc any dialog disappears. But we want the functionality to launch the bootstrap dialog on Esc and close it on next Esc . So this is my code:

           1.$(document).on("keyup", function(e){
           2.  if(e.which == 27 && id == "#esc"){
           3.      if(!$(dialogid).is(":visible")){
           4.          $(dialogid).modal({'show':true, 'keyboard':false});         
           5.        }else{
           6.          $(dialogid).modal('hide');
           7.      }
           8.  }
           9.});

It works fine until I press the Esc key slowly. But sometimes if user keeps pressing Esc key faster multiple times (3-5 times in a second), then the dialog disappears permanently. The control reaches to line no 4. i.e.

           $(dialogid).modal({'show':true, 'keyboard':false});         

but this line doesn't launch the popup. 
1. JSFiddle https://jsfiddle.net/Guruprasad_Rao/g535g20n/
Also I tried this solution without success:

              $(document).on("keyup", function(e){
                 if(e.which == 27){
                    if(!$('#myModal').is(":visible")){
                        setTimeout(function(){
                          $('#myModal').modal('show');         
                        },100);
                      }else{
                          setTimeout(function(){
                              $('#myModal').modal('hide');
                          },100);
                    }
                }
              });

 - What could be the reason?
 - How can I fix it.

**Comment by cvrebert** [comment]
Per our [our contribution guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker), how-to questions like this should be directed to StackOverflow instead of this bug tracker. Thanks!
Also, I would recommend listening for the show/hide events that the modal fires instead of merely checking `.is(':visible')`.
