### ISSUE TITLE
Resizing smaller makes content bigger than it is prior to resize

### ISSUE THREAD

**Issue by GearTheWorld** [twbs/bootstrap#16971]
I have a very simple content for which I'm using bootstrap.css.  It is used to have responsive design like resizing for smaller size.  When Resizing to a small size, the code starts to resize the content but just before it starts doing it it makes everything bigger then it was originally.  You can see it here in this GIF image

How do I send a repro by the way because I have zipped the little project to test it.  The only thing I can offer in this Issue tracker when writing this is an image.

![resizeissue](https://cloud.githubusercontent.com/assets/8614008/9203385/e16dea8e-4024-11e5-9e17-be788a3396a9.gif)

This media queries seems to work only in Internet Explorer 11 but seems not working in other browsers

**Comment by GearTheWorld** [comment]
Repro Project VS 2013 : https://onedrive.live.com/redir?resid=B1312569CC884E6!3076&authkey=!AOfXSZ27nnjSK-o&ithint=file%2czip

**Comment by kkirsche** [comment]
We require a JSBin or JSFiddle. We do not open zips, tars, other archives or personal projects for security reasons. Please post a JSBin of an isolated example.

**Comment by GearTheWorld** [comment]
Ah sorry, it's my first time,  I'll do a JSBin once at home.  I'll get the trick  :)

**Comment by GearTheWorld** [comment]
On JSBin it's not acting like the project and yet everything is there the same visual, css and reference to bootstrap

http://jsbin.com/dubomujapo/1/edit?html,css,output

When I resize the image is responsive but not the table but it is in my project and it's the same html content any idea ?

**Comment by kkirsche** [comment]
@GearTheWorld sounds to me like you may have some CSS which is causing that. Only thing I can think of if you aren't using the `.table-responsive` class on the `table`.

**Comment by GearTheWorld** [comment]
Everything you see in JSbin is what I have nothing else.  Now the question is how it uses media-queries on my MVC app and not on JSbin however it has the same things.  HTML, CSS and REFERENCES

I'm lost...

**Comment by patrickhlauke** [comment]
I suggest asking on StackOverflow at this point. It seems to be a problem specific to your use of Bootstrap, rather than with Bootstrap itself. I'd say though: check you don't have any further JS or CSS in your actual project that may be causing this change in styling.
