### ISSUE TITLE
Can't scroll <input type=text> on iPhone

### ISSUE THREAD

**Issue by hbridge** [twbs/bootstrap#16988]
If you enter text that exceeds the width of an `<input type=text>` field, then try to long press and scroll back, it doesn't scroll.  Reproable on the ~~components~~ CSS page. Originally filed this under React-Bootstrap, but affects the live Bootstrap.js components page as well.  

Screenshot attached.
![no scroll](https://cloud.githubusercontent.com/assets/77620/9280885/5d0fdbf4-428f-11e5-9105-59a1bcb72fbc.png)

**Comment by cvrebert** [comment]
This does not appear to be Bootstrap-specific. I encounter the same problem on http://output.jsbin.com/mixixuqipe/1 , where Bootstrap has been disabled, on my iPhone 5S running iOS 8.4.
Jesus that's a gnarly bug.

**Comment by cvrebert** [comment]
JS Fiddle (also affected), just to ensure that JS Bin 3D stuff wasn't the cause: http://jsfiddle.net/xuho9ccy/show/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/xuho9ccy/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 39, column 1: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@twbs/team Can someone else please test this on their iDevice to double-check?

**Comment by hbridge** [comment]
Whoa you're right.  I just tested google.com on an iPhone 5s with iOS 8.4 so it's not on you guys!

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=148061

**Comment by cvrebert** [comment]
Filed Apple Safari Radar: http://openradar.appspot.com/22299624

**Comment by pwbs** [comment]
Still not fixed in iOS 10.0. :(

**Comment by cvrebert** [comment]
Indeed. Nothing we can do about it on our end though. The ball is in Apple's court.
