### ISSUE TITLE
How to solve the problem of uneven thumbnail?

### ISSUE THREAD

**Issue by afuno** [twbs/bootstrap#16987]
Why do not they are row from left to right?
<img width="889" alt="2015-08-14 21 10 36" src="https://cloud.githubusercontent.com/assets/2853419/9280743/0bf7a4a6-42c9-11e5-9ca0-09da3e4bcbdc.png">

In the code that's right. Inside the &lt;div class="row"&gt;&lt;/ div&gt; there are several &lt;div class="col-xs-12 col-sm-6 col-md-6 col-lg-4"&gt; &lt;!-- here the custom content --> &lt;/ div&gt;.

**Comment by mdo** [comment]
That's not how floats work I'm afraid. You'll need to put each row of thumbnails in it's own clearfix, add a `clear` on the last element in each row, or set some fixed heights.

**Comment by afuno** [comment]
So, make beautiful tiles of various sizes with Bootstrap will not turn?

**Comment by afuno** [comment]
I do not have a fixed number to a string.

**Comment by afuno** [comment]
I do not have a fixed number to a string. For example, xs - this is one tile; sm - two; lg - three tiles. Can not add clearfix...

**Comment by patrickhlauke** [comment]
I'd suggest asking any follow-up questions on how to do this on StackOverflow, as per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
