### ISSUE TITLE
1 pixel margin under footer

### ISSUE THREAD

**Issue by nijs9** [twbs/bootstrap#16984]
I use the latest version of Bootstrap. There is one small issue: when I open the Bootstrap website in Internet Explorer, there is a 1 pixel margin under the footer. It's not the case on all the pages: some pages have this problem.  When I set the line-height of the body tag to 1 instead of 1.42857143, the problem is solved, but that's not a good solution. The problem occurs only in IE.

**Comment by cvrebert** [comment]
What version of IE?

> It's not the case on all the pages: some pages have this problem.

Which pages?

> there is a 1 pixel margin under the footer.

Can you post a screenshot to clarify the margin that you're referring to?

**Comment by nijs9** [comment]
The problem occurs in IE 11 and Edge. See screenshot below. The border is visible on some pages.

![bootstrap](https://cloud.githubusercontent.com/assets/10425157/9288467/9aad374a-4348-11e5-9ad9-4130d6a08366.png)

**Comment by cvrebert** [comment]
@nijs9 To clarify, did you mean http://getbootstrap.com when you said "the Bootstrap website" ?

**Comment by nijs9** [comment]
@cvrebert no, it's on my own website. I tried to setup another website from scratch with bootstrap, I don't change anything to the default bootstrap css. See this image: there is a small, 1pixel margin under the footer... It has something to do with the line-height in the body-element. I tried to give anothert height to the footer, but this thing wil not dissapear. In Chrome in Firefox there is no problem.

![naamloos-14](https://cloud.githubusercontent.com/assets/10425157/9306661/f6bd67fa-44f9-11e5-997f-2b43f2f9407b.jpg)

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem.  This shouldn't include third party resources so we can ensure this is a bug with browser's / bootstrap not an issue with the implementation of third party libraries or CSS. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by nijs9** [comment]
Please see to this website who is also in the bootstrap expo:

http://calhoun.ca/

There is also a white line under the footer, not in Chrome and Firefox, only in IE.

**Comment by kingmotley** [comment]
It appears that website is using the following tag: <link href="//cloud.webtype.com/css/e866cb1e-6627-4eba-83a2-82253617ce7c.css" rel="stylesheet" type="text/css"> which includes a style of body::after which is causing it.

**Comment by kingmotley** [comment]
It is the font file from webtype that is the cause on http://calhoun.ca

**Comment by nijs9** [comment]
Thanks, but I don't use WebType... I just use Google Fonts. Your solution doesn't work for me, but I want to thank you for your try.

**Comment by patrickhlauke** [comment]
For future reference...if you actually provided a link to your site where you're having your problem, it'd be a lot easier for people to try and help. But again, fundamentally this is not a problem with Bootstrap, but a problem with something else that's happening on the site, unrelated to Bootstrap. So, per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports you should use StackOverflow
