### ISSUE TITLE
bootstrap classes

### ISSUE THREAD

**Issue by SCORPIO12** [twbs/bootstrap#16991]
hi 

i install bootstrap and now learning is in progress . i want to ask that when we write any CSS class i.e. container or any such as i watched video he used css classes without write any css so how he knew that this css class is mentioned in bootstrap.css
"class="navbar navbar-default" now how we know this class is mentioned in bootstrap.css?
![untitled](https://cloud.githubusercontent.com/assets/13807459/9288042/f6c638c0-434c-11e5-9d6b-ae7f7e8e6ca3.png)

also there is many other classes
![untitledsd](https://cloud.githubusercontent.com/assets/13807459/9288043/f6c86ece-434c-11e5-94ad-a4c977643007.png)

so how we know that we write these or other css classes?

any help

**Comment by patrickhlauke** [comment]
read the documentation http://getbootstrap.com/css/ / http://getbootstrap.com/components/ / http://getbootstrap.com/javascript/

**Comment by webpax** [comment]
I'm sorry but the police Know about the telepathy crap and you guys
violating my life with it. He is a totally complete stranger and so are
you. I want people to know that this is a federal crime to bother people
incessently and get away with it. I am having a hard time getting and
keeping to my work and have the w2's to show it ok, and the actual
evidence. My PC was just hacked last night as well and I was forced under
friendly interrogation to answer to them. I know its the FBIs toys they are
playing with to catch criminals and they dont have a  right to play around
with it for fun.. sake,

On Sat, Aug 15, 2015 at 1:55 AM, SCORPIO12 <notifications@github.com> wrote:

> hi
>
> i install bootstrap and now learning is in progress . i want to ask that
> when we write any CSS class i.e. container or any such as i watched video
> he used css classes without write any css so how he knew that this css
> class is mentioned in bootstrap.css
> "class="navbar navbar-default" now how we know this class is mentioned in
> bootstrap.css?
> http://i.imgur.com/0ZBgATI.png
>
> also there is many other classes
> link .. http://i.imgur.com/rc48eXZ.png
>
> so how we know that we write these or other css classes?
>
> any help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/16991>.
>



-- 
Sincerely,

Amy Mondragon
