### ISSUE TITLE
main pointing to less file..

### ISSUE THREAD

**Issue by bialikover** [twbs/bootstrap#16992]
I know that everybody is using less but...
shouldn't be the main bower.json file pointing to the dist/css instead less folder?
https://github.com/twbs/bootstrap/blob/master/bower.json#L18

``` json
"main": [
    "less/bootstrap.less", 
    "dist/js/bootstrap.js"
  ],
```

I discover this because I'm using wiredep to inject my css and js files, and the css in dist is not being injected.

Any thoughts?

**Comment by kkirsche** [comment]
We didn't forget; it's deliberate.
Duplicate of #16663.
