### ISSUE TITLE
Tab-bar menu vs Hamburger

### ISSUE THREAD

**Issue by wyaeld** [twbs/bootstrap#16990]
There seems to be a lot of very valid points made by UX designers around the hamburger responsive menu actually not being effective for users, due to lack of connection with what they think they are looking for.

examples:
https://medium.com/design-philosophies/apple-and-hamburgers-a17e4099fada
https://medium.com/daily-ui-ux-inspirations/state-of-the-hamburger-buttons-fc49797af27a

and many apps are moving well away from it.  Apple has never liked it much from what I've read.
https://medium.com/mobile-growth/who-moved-my-hamburger-d237860bc589

The 2 most common alternatives seem to be static 'tab-bars', and left side flyouts.

I'm just interested in the core teams thoughts on this, and what options seem like things you're happy to support in TWBS.  I feel like the hamburger has its place, but that having a small curated collection of techniques for nav might be an improvement.  Technically the tab-bar can be done with just grid-style, and a bit of custom css, at least to get something workable.  Flyouts are a little trickier.

**Comment by taspeotis** [comment]
> Apple has never liked it much

Meanwhile, in the real world:

![image](https://cloud.githubusercontent.com/assets/1189399/9293110/de4c5f76-4460-11e5-806b-e4abd2f4bc55.png)

**Comment by num-lock** [comment]
That's not a hamburger. It's clearly a sandwich.

**Comment by kkirsche** [comment]
At least in my opinion, I think a framework such as bootstrap while recommending the best UI it can is limited by the possible use cases of the end user. We don't know how many items will be in any menu and I would argue that a tab bar such as recommended may not be possible for all end use cases though it is better UX (in my opinion at least).

I personally feel that a good solution would be to offer a styled select dropdown of the menu instead as that would provide the same functionality of the hamburger menu while still offering better controls to most mobile devices for easier navigation of the menu. 

Just my 2¢ though. Curious about @mdo's opinion on this.

**Comment by mdo** [comment]
We won't be making any changes for this in v3, but have some small nav changes coming to v4 that might help with a few things.

**Comment by dentarg** [comment]
Here's another well-written text about the hamburger menu: http://deep.design/the-hamburger-menu/

**Comment by wyaeld** [comment]
@dentarg that's actually the one I read, and then couldn't find again, thanks.
