### ISSUE TITLE
autoheight

### ISSUE THREAD

**Issue by soyebamd** [twbs/bootstrap#16993]
auto height or height in % not working

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by mdo** [comment]
You'll have to be more specific than that—we've no idea what you're referring to.
