### ISSUE TITLE
space issue in right side in SmartAdmin theme v1.5.2

### ISSUE THREAD

**Issue by Bvaghasiya** [twbs/bootstrap#17004]
in smart admin theme if we open any grid after that open any modal form and after that open any inside modal form then its append space in right side..if we open again and again this modal form then right side space will be increased.
this is because of bootstrap.min.js
in previous version of bootstrap there is 
c.prototype.resetScrollbar = function () { this.$body.css("padding-right", "")
but now in SmartAdmin - v1.5.2 - 2015-04-23 bootstrap.min.js
c.prototype.resetScrollbar = function () { this.$body.css("padding-right", this.originalBodyPad)
so is there any issue with originalBodypad ??

**Comment by cvrebert** [comment]
Bootstrap does not include any such theme. We cannot help you with it. Please contact the SmartAdmin theme's actual vendor for support. Good luck.
