### ISSUE TITLE
issue in scrollbar when open modal form

### ISSUE THREAD

**Issue by Bvaghasiya** [twbs/bootstrap#17005]
hello,
when we open one modal form which is add class "modal-open" in body element so that scroll in modal-form is maintained now i open another modal-form inside one modal-form then if modal form content is quite long then there is no lost content of scrollbar..in previous version its add  "modal-open " in each and every modal form but now in new version inside modal-form scroll bar not working for that.
what can i do for that??

**Comment by kkirsche** [comment]
<blockquote>
<h4>Multiple open modals not supported</h4>
<p>Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.</p>
</blockquote>

**Comment by Bvaghasiya** [comment]
hello
yes we have that custom functionality.that's why i am telling you that if
one another modal form is open over the one modal then scroll bar is not
working for that. but in previous version of the bootstrap its working fine.
thanks for the same.

**Comment by cvrebert** [comment]
Closing as "works as documented" per the documentation that @kkirsche quoted.
We are unfortunately unable to assist you on this bug tracker with the implementation/debugging of such custom modal code/functionality. For help with such things, ask on StackOverflow or one of the other community forums listed on https://github.com/twbs/bootstrap/blob/master/README.md#community
Good luck!

**Comment by Bvaghasiya** [comment]
hello,
thanks for the same.but i want to just inform you that it is working fine
in previous version of bootstrap but in new version its messed up.
Thanks

**Comment by kkirsche** [comment]
We understand. I believe that you're probably  hitting  one of the bug fixes that we implemented to address issues with the scrollbar for the document behavior

**Comment by Bvaghasiya** [comment]
hello,
but its not like that we open two modal form at a time on the screen but in my case scenario like this
1)open first modal form say modal-1
2)in modal-1 there is another button which open modal form say modal-2
now once modal-2 is open then modal -1 automatically hide and it shows only modal-2
if we close modal-2 then modal -1 shows which is hide by me
in this scenario from boot-strap.min.js which is add "modal-open " class in modal-1 but its not adding "modal-open "class in modal-2 so there is no scroll bar for that modal
or if modal-2 content is very long we need to scroll vertically but there is no scroll available because of "modal-open "  class.
Thanks for the same

**Comment by ahmedali5530** [comment]
@Bvaghasiya you must see this [Bootstrap 3.3.5 multiple modals scroll bars bug #17674](Bootstrap 3.3.5 multiple modals scroll bars bug #17674 ) .
