### ISSUE TITLE
Flexible css cover images

### ISSUE THREAD

**Issue by praveenvc** [twbs/bootstrap#17009]
Why below mentioned default flexible CSS cover styles not available.
Ex:
http://nicolasgallagher.com/flexible-css-cover-images/

**Comment by kkirsche** [comment]
@praveenvc 1.) the support of it is: `Chrome, Firefox, Safari, Opera, IE 9+` where Bootstrap V3 supports IE8. 2.) it probably wasn't something which came up as a priority to the core team.

Currently though, it wouldn't be added to V3 as it is feature frozen in preparation for the V4 beta later this month.

**Comment by mdo** [comment]
You can probably use the the responsive embed styles we include in Bootstrap to achieve most of this—though you'll likely need a bit of tweaking on top of that. Won't be doing it in v3 though.
