### ISSUE TITLE
.col-offset-0 example addition to docs

### ISSUE THREAD

**Issue by nathanhleung** [twbs/bootstrap#17003]
I was having a bit of trouble making a responsive column layout where `-xs` devices would have an offset while `-sm` devices would not.  On a whim I decided to try adding a `.col-sm-offset-0` class and it worked, however I had to search for a while since `-offset-0` classes are undocumented.  I think it would be really helpful in the future if this was added to the documentation.  If you guys feel the same I can create a quick pull request on `gh-pages` with the addition.

Relevant code:
```html
<div class="row">
  <div class="col-xs-6 col-sm-4">
  </div>
  <div class="col-xs-6 col-sm-4">
  </div>
  <div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-0">
  </div>
</div>
```

**Comment by mdo** [comment]
Coming in #18251.
