### ISSUE TITLE
Border color for input group on focus highlighted unevenly on right

### ISSUE THREAD

**Issue by jplehmann** [twbs/bootstrap#17001]
I'm having the same problem which can be seen in BS documentation:
http://getbootstrap.com/components/#input-groups-buttons

Click on the right example "Search for...".  Notice how the blue border/outline on the right side is covered up.  The left example doesn't really have this problem.

![screen shot 2015-08-17 at 8 48 00 pm](https://cloud.githubusercontent.com/assets/460964/9320568/44b4222e-4521-11e5-8750-45e0cdd78d4a.png)

The blue comes from .form-control:focus { border-color, outline, webkit-box-shadow, box-shadow }  at least on my page.

My site is: http://www.morphmarket.com and you'll see the same issue on its search input and the middle button too.  I messed with Chrome inspector for a while, but this is beyond me -- and when I saw the docs had the same problem, I figured I could create an issue.   Thanks!

**Comment by kkirsche** [comment]
PR submitted @jplehmann — thanks for reporting this. @mdo build failed due to a travis issue it seems not the code change itself. JSBin of the fix is in the PR. Just a simple z-index change.

**Comment by mdo** [comment]
Fixed in #18253.
