### ISSUE TITLE
Bootstrap modal popup overlapping in asp.net mvc

### ISSUE THREAD

**Issue by shrikantjadhav49** [twbs/bootstrap#17015]
I have declare modal popup code before body tag close. I want to declare modal popup code in middle of the chtml page in asp.net mvc. When I'm specify in middle of the page modal popup is overlapping. So please help me. Before end of the body tag its working fine modal popup window. What should I need to do for that.

Please see the below problem area of screenshot.
![people](https://cloud.githubusercontent.com/assets/13793791/9349309/e89831fa-4661-11e5-8a72-1212c74eb19d.png)
-Above image is indicate, I have declare partial view in middle of the page.

![addpeople](https://cloud.githubusercontent.com/assets/13793791/9349312/f6716440-4661-11e5-9081-c50f64a61edc.png)
-Above image is indicate, I have declare partial view in middle of the page and it overlapping.

![master page](https://cloud.githubusercontent.com/assets/13793791/9349316/04a9bf80-4662-11e5-8ba3-c9118e863973.png)
-Above image is indicate, I have created and declare partial view before body tag is close which is commented and its working fine.

**Comment by cvrebert** [comment]
A. We are unable to provide assistance with problems involving backend or third-party frameworks such as ASP.
B. See http://getbootstrap.com/javascript/#callout-modal-markup-placement and https://github.com/twbs/bootlint/wiki/E022

For further assistance regarding this, try asking on StackOverflow or one of the other support forums listed in https://github.com/twbs/bootstrap/blob/master/README.md#community
Good luck!

**Comment by shrikantjadhav49** [comment]
#17015 thank you Chris Rebert. I will go through some other site.
