### ISSUE TITLE
Webseite getbootstrap.com is not opening because of too many redirects

### ISSUE THREAD

**Issue by mklarmann** [twbs/bootstrap#17016]

**Comment by MrGeneric** [comment]
It's up for me.

**Comment by mklarmann** [comment]
sorry - the error is not 404 but because of to many redirects

**Comment by MrGeneric** [comment]
Looks like it's not just you as someone else has opened a similar issue. :)

**Comment by vaughany** [comment]
It seems to have been fixed.

**Comment by mklarmann** [comment]
nope, not yet for me

**Comment by mklarmann** [comment]
but this seems to be a nameserver / jekyll related issue, so a fix can take some time to propagate through dns
