### ISSUE TITLE
When I visited getbootstrap constantly jump to http://getbootstrap.com/2.3.2/, you can not view the new document

### ISSUE THREAD

**Issue by tel8618217223380** [twbs/bootstrap#17018]
When I visited getbootstrap constantly jump to http://getbootstrap.com/2.3.2/, you can not view the new document

**Comment by alexmocanu** [comment]
Same here

Going to getbootstrap.com redirects to http://twitter.github.com/bootstrap/2.3.2/ and then enters a redirect loop

**Comment by hnrch02** [comment]
See https://github.com/twbs/bootstrap/issues/17019#issuecomment-132588368.
