### ISSUE TITLE
Missing btn-xs 

### ISSUE THREAD

**Issue by supergibbs** [twbs/bootstrap#17029]
Bootstrap V4 docs show an example of btn-xs but it doesn't seem to exist. Not sure if it should be removed or if btn-xs was meant to be...

http://v4-alpha.getbootstrap.com/components/buttons/#sizes

**Comment by thomas-mcdonald** [comment]
yeah, we meant to remove these

**Comment by thomas-mcdonald** [comment]
fixed in 323b9b1
