### ISSUE TITLE
Justified nav and sticky footer examples are broken

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap#17026]
See http://v4-alpha.getbootstrap.com/examples/justified-nav/ and http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/.

Source: https://news.ycombinator.com/item?id=10086756

**Comment by XhmikosR** [comment]
Ah, here it is! And I pinged @mdo this morning on Slack.

**Comment by mdo** [comment]
Footers are fixed, justified is a dupe of #17723.
