### ISSUE TITLE
V4 dev gem badge goes to non BS owned gem

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#17022]
https://rubygems.org/gems/bootstrap directs to a non V4 Bootstrap gem from an individual not on the core team.

**Comment by thomas-mcdonald** [comment]
removed for now

**Comment by cvrebert** [comment]
Refs e7b0d726dbe8ad7b442056846b52545e391ace18

**Comment by mdo** [comment]
Looks like the gem is owned by @glebm—can/should we restore the badge?

**Comment by cvrebert** [comment]
Yes. Restored in 27596f48f4c84f823a2b4cb6ff3e4fc55ced6344.
