### ISSUE TITLE
v4: Quick Start docs reference v3.3.5

### ISSUE THREAD

**Issue by zacechola** [twbs/bootstrap#17028]
http://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start

**Comment by mohitbhatia1994** [comment]
because they haven't launched their CDN yet.

**Comment by hnrch02** [comment]
We could use [cdn.rawgit.com](http://rawgit.com/) in the meantime: https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js

**Comment by zacechola** [comment]
I'll add it. Have the file open anyway. :)

**Comment by zacechola** [comment]
Should cdn.css_theme be removed?

**Comment by hnrch02** [comment]
Fixed by https://github.com/twbs/bootstrap/commit/67af7ca69a19b8bc506687dfa8f792ef601bb8d1.
