### ISSUE TITLE
navbar with dropdown, dropdown not working after modal closure

### ISSUE THREAD

**Issue by AlexDev4life** [twbs/bootstrap#17045]
Hi, I'm using bootstrap navbar with a navbar dropdown. Within the navbar, I have an option to change user password which makes a bootstrapDialog.load('view') function to load the cshtml view within the modal. Everything works fine until I close that modal popup and the dropdown doesn't work. Can you please tell me why is this doing it? I see no errors in the console and don't know what would the best approach. I'm still testing the app, if you come with some solutions, please help. 

Thanks

**Comment by cvrebert** [comment]
We are unable to provide assistance with problems involving backend or third-party frameworks such as ASP.

Per our policy (https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports ), bug reports must include a reduced test case that demonstrates the alleged problem. If you can create & post such a testcase (which must not involve ASP) for your problem, I will be happy to reopen this issue for further investigation. Thanks.
