### ISSUE TITLE
Remove .btn-group-xs docs

### ISSUE THREAD

**Issue by acshef** [twbs/bootstrap#17054]
![image](https://cloud.githubusercontent.com/assets/9013284/9367742/91841aa8-467c-11e5-8954-aedf472d8cc3.png)
Viewable at http://v4-alpha.getbootstrap.com/components/button-group/#sizing

EDIT: Seems there's no styling for `.btn-group-xs` or `.btn-xs`.

**Comment by cvrebert** [comment]
Much to my dismay, XS buttons have been removed in v4.

**Comment by thomas-mcdonald** [comment]
These will be removed when we redeploy the docs

**Comment by cvrebert** [comment]
Approximate duplicate of #17029.
