### ISSUE TITLE
v4 Docs - Components - Cards links to Flexbox section returns 404

### ISSUE THREAD

**Issue by Schmalzy** [twbs/bootstrap#17056]
In the Components/Cards documentation, two of the sections contain broken links to the flexbox documentation 

http://v4-alpha.getbootstrap.com/components/card/#groups
http://v4-alpha.getbootstrap.com/components/card/#decks

Broken link URL - http://v4-alpha.getbootstrap.com/layout/flexbox

**Comment by hnrch02** [comment]
Fixed by https://github.com/twbs/bootstrap/commit/66be25917a66a2cdb19a297a1ce7e5642357fc06.
