### ISSUE TITLE
Add link to jQuery in Quick Start section of v4 docs

### ISSUE THREAD

**Issue by zacechola** [twbs/bootstrap#17057]
[Currently](http://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start): 

```html
<script src=""></script>
```

**Comment by kkirsche** [comment]
Is `site.cdn.jquery` supposed to be a variable replacement or is that just a placeholder in the docs currently?

**Comment by zacechola** [comment]
@kkirsche Yeah looks like it's a placeholder without a value in _config.yml. Added in the PR.

@fat mentioned in the slack room that jq2 is fine. v3 docs point to the Google jQuery CDN for 1.11.x, so I guess I'll add it.

**Comment by hnrch02** [comment]
Fixed by #17132.
