### ISSUE TITLE
README: link broken and suggestion for "Quick start" section

### ISSUE THREAD

**Issue by proehlen** [twbs/bootstrap#17053]
The link to "Getting started page" doesn't work.

Also recommend adding this code snippet which is all you need after installing the package to have bootstrap running in your application:
```
<head>
  <title>My app</title>

  <!-- Boostrap viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  
</head>
```

**Comment by cvrebert** [comment]
That meta tag is already part of the starter template:
http://v4-alpha.getbootstrap.com/getting-started/introduction/#starter-template

**Comment by cvrebert** [comment]
Which link are you referring to?

**Comment by proehlen** [comment]
![image](https://cloud.githubusercontent.com/assets/8384068/9367919/93d53314-46ea-11e5-9c88-6f3ca8b84ac5.png)
The link is this:
```
http://getbootstrap.com/getting-started/
```
Which redirects me to:
```
http://twitter.github.com/bootstrap/2.3.2/
```
Which gives me this in Chrome:
```
This webpage has a redirect loop

ERR_TOO_MANY_REDIRECTS
```

Sorry, that might be a bootstrap site issue and not one for your package.

**Comment by cvrebert** [comment]
This is due to some lingering DNS stuff. Should be fine once the DNS changes finish propagating. Nothing more we can do about it.
