### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by mrfaizanhaider** [twbs/bootstrap#17060]
how to apply  any theme, just like google material on bootstrap

**Comment by mrfaizanhaider** [comment]
can we make a branch a name with material theme for bootstrap.

**Comment by cvrebert** [comment]
X-Ref: #14914

**Comment by hnrch02** [comment]
I really don't understand why people want an official Material Design theme for Bootstrap. Why not just use [Material Design Lite](https://github.com/google/material-design-lite) instead? Material Design differs quite a bit from Bootstrap in terms of components.
Besides, there are already unofficial Material Design themes out there in userland.

**Comment by mdo** [comment]
We won't be doing that here. That's an entirely different project that's not really appropriate for this repository.
