### ISSUE TITLE
v4: custom checkboxes/radios not displaying focus outline

### ISSUE THREAD

**Issue by cornedor** [twbs/bootstrap#17066]
There is no visual feedback when selecting a custom checkbox or radiobox when using the keyboard, so it is not clear when you can change it using the space bar.
![checkbox](https://cloud.githubusercontent.com/assets/570297/9369457/8034c886-46c9-11e5-8d74-8101332aebfe.jpg)
One of these is selected.

**Comment by cvrebert** [comment]
You're referring to the lack of a `:focus` state, right?

**Comment by cornedor** [comment]
Yes, after looking trough the code I did see that there was a focus state, but I haven't much time to look at it more.

**Comment by mdo** [comment]
Fixed in #17220.
