### ISSUE TITLE
v4 - Change components using specific bg styling classes bg-*

### ISSUE THREAD

**Issue by AbbyLynn** [twbs/bootstrap#17067]
Was curious about possibly moving components from using custom coloring solutions (label-_) to just using the global bg-_ options.

label-primary (etc)
card-danger (etc)
progress-warning (etc)

``` html
<span class="label bg-danger">DANGER</span>
```

**Comment by luisvt** [comment]
why not just use the direct class:
```html
<progress class="warning"></progress>
<progress class="warning striped active"></progress>
<card class="warning"></card>
...
```

**Comment by mdo** [comment]
Going to punt on doing this since many of our styles for component modifiers include hover states and more than just one property-value pair (which is what utilities offer). Maybe in v5 we can revisit this approach to support a stronger balance between utilities and components.

Thanks though!
