### ISSUE TITLE
v4 - Missing space between nav-item and navbar-form

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#17068]
If you dont pull the form right (like in docs), there is a space missing between them.
![img_2015 08 19_23h34m15s_002_](https://cloud.githubusercontent.com/assets/1368405/9369660/f466e508-46ca-11e5-84c0-3c06a60d1a83.png)

**Comment by TheZoker** [comment]
Label docs is wrong, because this is a css bug (I changed the code by removing the `pull-right` with console editor, to show the bug)

**Comment by kkirsche** [comment]
@TheZoker thanks for posting the bug report! do you mind posting a JSBin demonstrating this? It'll make it quicker for us to put the fix together and to showcase what was done and how so everyone agrees it's fully fixed :smiley: 

Thanks for understanding!

**Comment by TheZoker** [comment]
Here you go: https://jsbin.com/kiroze/edit?html,output
Second example with 2 menus (e.g. for multiple mobile collapse): https://jsbin.com/xohokuk/edit?html,output
And a `nav-text` is also missing: https://jsbin.com/zovami/edit?html,output

**Comment by mdo** [comment]
The issue in the opening comment is solvable with spacing utilities.
