### ISSUE TITLE
Extra Small Button (.btn-xs) styles missing

### ISSUE THREAD

**Issue by ckihneman** [twbs/bootstrap#17075]
Navigate to the button docs here: <http://v4-alpha.getbootstrap.com/components/buttons/>.

Scroll down to "Sizes", look at the portion on "Extra Small Buttons".

**Expected result:** buttons to be smaller.

**Current result:** `.btn-xs` receives no additional styles, leaving them looking like a default `.btn`.

**Fix suggestion:** In looking at the source code in `/scss/_buttons.scss`, there are no styles for `.btn-xs`. Looks like they need to be added :)

**Comment by hnrch02** [comment]
They were removed on purpose and the docs will be updated to reflect that shortly. See also #17029.

**Comment by ckihneman** [comment]
My bad, shoulda checked closed issues (I will next time). Thanks!
