### ISSUE TITLE
Integrate Github with Slack for v4-dev

### ISSUE THREAD

**Issue by cassler** [twbs/bootstrap#17076]
Anyone doing this needs access to the GitHub repo AND be an admin on Slack. Just hit this URL and click-click https://getbootstrap.slack.com/services/new/github.

**Comment by thomas-mcdonald** [comment]
GitHub/Slack is pretty noisy

**Comment by kkirsche** [comment]
is that a bad thing @thomas-mcdonald? Depending on the person or organization that isn't a bad thing.

**Comment by mdo** [comment]
FWIW, we can explore adding the integration to a separate room. I don't think we'd inundate #general with all that noise given the number of folks there.

**Comment by thomas-mcdonald** [comment]
@kkirsche we had it enabled in our internal room for a while - the activity on this project means it will probably drown out discussion

**Comment by kkirsche** [comment]
@thomas-mcdonald I wasn't in those so I can't say. I know the alpha brings up a ton of activity but before it wasn't enough In my opinion to be a problem. I don't know what you consider drowning out though

**Comment by cassler** [comment]
@thomas-mcdonald @mdo a #git channel has served my team well. Even with dozens upon dozens of commits to master every day, it's actually surprisingly _quiet_ in my experience - typically announcing groups of commits and actions periodically rather than each event individually.

**Comment by thomas-mcdonald** [comment]
@cassler sounds cool - I hadn't thought about putting it in another room

**Comment by mdo** [comment]
Added to the `#git` room.
