### ISSUE TITLE
v4 Dashboard Example menus off

### ISSUE THREAD

**Issue by anquinn** [twbs/bootstrap#17072]
The top navbar doesn't behave correctly, and the left side nav styles seem to be incorrect here:

http://v4-alpha.getbootstrap.com/examples/dashboard/

**Comment by kkirsche** [comment]
Example image:
<img width="1388" alt="screen shot 2015-08-19 at 5 48 41 pm" src="https://cloud.githubusercontent.com/assets/947110/9369921/8ec5e5e4-469a-11e5-8e11-ee8b0b1d4dbc.png">

**Comment by wolfy1339** [comment]
#17077 should help with that

**Comment by mdo** [comment]
Fixed by #17172.

**Comment by hnrch02** [comment]
@mdo I don't think this is fixed - comparing the v4 version with the v3 example shows quite a bit of difference in style: http://getbootstrap.com/examples/dashboard/

**Comment by mdo** [comment]
Yeah, this and almost all the other examples, need more love. We can tackle much of this later unless folks start to pick at it for us.
