### ISSUE TITLE
docs.min.css and docs.min.css.map incorrect - v4

### ISSUE THREAD

**Issue by jatinhariani** [twbs/bootstrap#17078]
Compiling docs.min.css by running 'grunt dist-css' gives a diff on the docs.min.css file and the docs.min.css.map file. For example, the following property seems different from the compiled source: ``background:-webkit-linear-gradient(315deg,#271b38,#563d7c,#7952b3);background:-o-linear-gradient(3135deg,#271b38,#563d7c,#7952b3);background:linear-gradient(135deg,#271b38,#563d7c,#7952b3) ``. ( Line 6, Column 901).
There are more diffs in other properties. A recompile should fix this.

**Comment by kkirsche** [comment]
@jatinhariani dist is only for distribution. This won't be updated until alpha 2 and will have a dif for any compile until that time. Then it will only be accurate until the next PR

**Comment by hnrch02** [comment]
Docs CSS is compiled slightly different with `grunt docs-css`. Compiling it with that command gives no diff.
