### ISSUE TITLE
Use structured data like Microformats for various content like physical addresses

### ISSUE THREAD

**Issue by asuh** [twbs/bootstrap#17087]
According to [the W3C's definition for the `<address>` element](http://www.w3.org/TR/html5/sections.html#the-address-element), "the address element must not be used to represent arbitrary addresses (e.g. postal addresses), unless those addresses are in fact the relevant contact information".

It would be responsible to provide a more relevant markup for physical addresses using Microformats 2. Currently, [the address section of Bootstrap Alpha](http://v4-alpha.getbootstrap.com/content/reboot/#address) defaults the address element for physical addresses. This is where the h-card and Microformats can shine! Considering that physical addresses will sometimes be appropriate for the address element, there could be a combination or parallel between Microformats 2 and the address element in how it's styled and displayed.

**Comment by patrickhlauke** [comment]
The bootstrap section there doesn't default anything. It shows the styling that is applied to misc elements such as `address` and `blockquote`. It does not provide any guidance on when to actually use `address`, so it would be thoroughly inappropriate to start putting microformats in there.

**Comment by asuh** [comment]
Wouldn't it make sense to not list a physical address there as the default example to be more responsible? The way it looks right now, considering most people who use it won't know any better, will just default to thinking "oh, that's for physical addresses at all times". Seems like there should be something to suggest otherwise.

**Comment by kkirsche** [comment]
But would using a different address really make them question that or would it just confuse them and they would ignore it? I would assume the later honestly (and sadly)

**Comment by patrickhlauke** [comment]
The page lists elements and shows the styling that's applied. So no, it would not make sense. We don't give any advice on every other element's dos and don't on that page either.

**Comment by asuh** [comment]
It seems like the responsible thing is to add more context and possibly another example as the default (leaving the current one below with a stipulation that it needs to be relevant to the actual page.

**Comment by mdo** [comment]
Dismissing the presence of microformats in v4 simply because we're talking about the wrong page seems a tad shortsighted. We can explore supporting microformats for things like addresses, but @patrickhlauke is right in that the Reboot page is the wrong place to present that information. That doesn't mean, however, that we can't do it all somewhere else.

Let's step back and see what documenting a Microformats address would look like—what code and docs are involved? What's the difference between that and the Reboot section on the HTML element?

**Comment by patrickhlauke** [comment]
Hmmm, I seem to have gotten confused by the request then. If it's not arguing over whether or not `<address>` is correctly used in that particular part of the docs, but rather that it would be nice to also double-up the same styles to also target other types of elements with relevant microformats classes, and to document this somewhere (else), then fair enough.

**Comment by asuh** [comment]
@patrickhlauke I apologize if what I said came across incorrectly. The address element is indeed on the correct page but I think more context should be given and an example that is more universal instead of defaulting to physical addresses every time. I am just as at fault for not knowing spec as anyone else so steering them in a more responsible direction with the address element up front would be a good way for them to be exposed to both this element and Microformats.

But sweet, I do think promoting Microformats on a project like Bootstrap can help bring more attention to the semantics and value the it can and should have. It's like the ugly stepchild that needs some lovin'. @tantek can correct any misinformation below since he's one of the creators.

The difference between `<address>` and Microformats is that the address element, while it can be used for physical addresses every time, is not the appropriate default every time when the physical address might not be directly related to the content of the page it might be on. Microformats could and should be this default.

[Microformats 2](http://microformats.org/wiki/microformats2) is the current iteration of Microformats and there are many docs available there.

A simple physical address similar to what's on the Reboot page could be marked up like the following:

``` html
<div class="h-card">
  <a class="p-name p-org u-url"
     href="http://twitter.com/" 
    >Twitter Inc.</a>
  <div class="h-adr adr">
    <div class="p-street-address street-address">1355 Market St, Suite 900</div>, 
    <span class="p-locality">San Francisco</span>
    <span class="p-region">CA</span>
    <span class="p-postal-code"> 94103</span>
    <span class="p-country-name">USA</span>
    <div>
      <abbr title="Phone">P:</abbr> <span class="p-tel">(123) 456-7890</span>
    </div>
  </div>
  <p>
    <strong>Full Name:</strong> <a class="u-email" href="mailto:first.last@example.com">first.last@example.com</a>
  </p>
</div><!-- /.h-card -->
```

**Comment by QWp6t** [comment]
:-1:

If some form of structured data is going to be documented, then it should of course be Microdata/schema.org. But that stuff is already well documented in other places, so if anything, link out to resources that are dedicated to it.

**Comment by cvrebert** [comment]
I agree that this seems to go beyond our purview due to it being tangential and the heavy markup involved. But mentioning hCard and linking to some outside docs for it does seem like a good idea.

**Comment by asuh** [comment]
If this is determined to be too opinionated, I agree with @cvrebert that a mention to either Microformats and/or Scheme.org is a good idea. I'm not sure what the best content inside of `<address>` is without there being some context. Leaving a physical address in there makes it look like that's the universal use case when the wild it's often not the right use case according to W3C spec.

A more appropriate example could be the following in respect to what's there.
``` html
<address>
  For more details, contact
  <a href="#">first.last@example.com</a>.
</address>
```

I'm not gung-ho about forcing anyone to choose between schema.org or microformats (having not really been exposed to schema.org before this) but I do think keeping things in context on such a universally used project like Bootstrap is a good idea. I've used Microformats in several projects out of respect and I like that it can give content more semantic meaning but it seems schema.org is of a similar nature so I understand if docs from one or both could equally be linked to.

**Comment by patrickhlauke** [comment]
> Leaving a physical address in there makes it look like that's the universal use case when the wild it's often not the right use case according to W3C spec

that's not correct. you seem to be misinterpreting the spec. it's not the fact that something's a physical address that's the problem. it's that `<address>` needs to refer to relevant information relating to the document/section it's in (who's responsible/who to contact about the page/section you're reading), rather than to be used to mark up other people's addresses (i.e. if I wanted to put Twitter HQ's address on MY website in an article about them, I wouldn't put that in `<address>`...on MY website, only contact details relating to ME should be marked as `<address>`)

**Comment by patrickhlauke** [comment]
i.e. it's just as wrong to use `<address>` to mark up someone else's email address, web address, twitter handle, etc...unless it's contact info for the page/section that it's in.

**Comment by asuh** [comment]
> it's that `<address>` needs to refer to relevant information relating to the document/section it's in

Yes, that's right. But by using a physical address as an example, and I base this on my own behavior, if I didn't know any better I would look at this example and think "Oh ok, this is how I mark up physical addresses, great". 

I know that physical address has its place in the address element, sure, but I'd wager that most instances around the internet of the physical address being in this element are incorrect as laid out by W3C. I'm sure there are many others like me who briefly look at elements like this and take no time to look at context and understand them.

> i.e. it's just as wrong to use <address> to mark up someone else's email address, web address, twitter handle, etc...unless it's contact info for the page/section that it's in.

Yes, absolutely, I agree. But leaving default physical address in this example, not saying how it's relevant, for this element gives a potentially misunderstood use for it since there's no context.

I think it'd be more responsible to use an example that is more likely than not correct in most cases. This is where I think a microformat or schema type markup would be very useful and appropriate in Bootstrap to give better more relevant examples for things like physical addresses.

**Comment by kkirsche** [comment]
<blockquote>
Yes, that's right. But by using a physical address as an example, and I base this on my own behavior, if I didn't know any better I would look at this example and think "Oh ok, this is how I mark up physical addresses, great".
</blockquote>

But wouldn't other addresses do the same thing? E.g. "Oh ok, this is how I should mark up electronic addresses" or whatever the address type in question is. The example itself I don't believe really is the thing that matters

**Comment by asuh** [comment]
> But wouldn't other addresses do the same thing?

It's a valid question but the anchor already exists and is widely used for electronic addresses so that context is widely known. Wrapping email anchors with address is enough of a different context to signify there's something that needs to be known before going down this route.

**Comment by patrickhlauke** [comment]
> not saying how it's relevant, for this element gives a potentially misunderstood use for it since there's no context.

http://v4-alpha.getbootstrap.com/content/reboot/#address already clearly states:

> `<address>`s are for presenting contact information for the nearest ancestor (or an entire body of work)

so, you're really not convincing me here that there's anything wrong with the actual example...

**Comment by asuh** [comment]
That sentence has decent wording but the word "ancestor" comes off ambiguous I think. W3C's wording is more explicit and makes more sense IMO.

Maybe I'm being naive to think that there are many others like me who don't spend as much time reading as we do looking and copying visual examples.

**Comment by mdo** [comment]
Seems like there's not much we can agree on here to change, so I'm going to punt on this. If anyone has specific edits to suggest though, please open PRs. <3
