### ISSUE TITLE
"Preprocessors" section of v4 homepage needs updating

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17088]
* Preprocessors => Preprocessor
* Remove `{less}` logo

Sayonara, Less.

**Comment by kkirsche** [comment]
I can remove it in photoshop but may have quality loss. Who has the original of https://github.com/twbs/bootstrap/blob/v4-dev/docs/assets/img/sass-less.png

**Comment by sgraewe** [comment]
Just use the sass svg: http://svgporn.com/logos/sass.svg

**Comment by Caneco** [comment]
This is my suggestion…

![less-sass](https://cloud.githubusercontent.com/assets/502041/9378733/a8209e54-471b-11e5-8cd5-0c15a2b6aa39.png)

**Comment by cvrebert** [comment]
Fixed by #17221.
