### ISSUE TITLE
IE rendering mode link in v4 documentation goes nowhere

### ISSUE THREAD

**Issue by tomprats** [twbs/bootstrap#17096]
Looks like the code responsible for the following error is [here](https://github.com/twbs/bootstrap/blame/v4-dev/docs/getting-started/introduction.md#L41) (note my awesome linking skills). But otherwise, great job, I'm excited to see how everything works. Here's what the current code displays (note the blank link):

Forcing Internet Explorer to use its latest rendering mode ([read more]())

**Comment by hnrch02** [comment]
Addressed by https://github.com/twbs/bootstrap/commit/3895bfa3883fe9b06f87902906f6146533769997.
