### ISSUE TITLE
Issue with _variables.scss

### ISSUE THREAD

**Issue by mistakenCynic** [twbs/bootstrap#17090]
Currently getting this issue when trying to compile the Sass files:

error dimensionsapart/scss/bootstrap.scss (Line 89 of dimensionsapart/scss/_variables.scss: Invalid CSS after " xs": expected ")", was ": 0,")
identical dimensionsapart/stylesheets/bootstrap.css 

This is what the section in question looks like:

$grid-breakpoints: (
  // Extra small screen / phone
  xs: 0,
  // Small screen / phone
  sm: 34em,
  // Medium screen / tablet
  md: 48em,
  // Large screen / desktop
  lg: 62em,
  // Extra large screen / wide desktop
  xl: 75em
) !default;

**Comment by cvrebert** [comment]
What Sass compiler/tool are you using?

**Comment by mistakenCynic** [comment]
I'm using Compass, and then Scout as a GUI.

**Comment by cvrebert** [comment]
I can't reproduce:
```
~/code/bootstrap $ compass version
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2015 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
~/code/bootstrap $ compass compile --sass-dir scss --css-dir dist scss/bootstrap.scss
    write dist/bootstrap.css
~/code/bootstrap $
```

Technically, we don't officially support compilation methods other than our Gruntfile. For further assistance with Compass, try asking on [StackOverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap-4). Good luck!

**Comment by aladin7** [comment]
mistakenCynic, did you find solution for your problem?
