### ISSUE TITLE
Link to Wall of browser bugs from Browsers and devices page is broken

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17107]
http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#desktop-browsers

**Comment by karlingen** [comment]
![screen shot 2015-08-20 at 11 18 09](https://cloud.githubusercontent.com/assets/2265452/9379948/276f3a7e-472d-11e5-8309-a591e0155719.png)
yup

**Comment by hnrch02** [comment]
Fixed by https://github.com/twbs/bootstrap/commit/a5bed79459ee65f70ac7558424c756935ffeb8ba.
