### ISSUE TITLE
escape key not work with modal,except i add tabindex="-1".

### ISSUE THREAD

**Issue by jcs12311** [twbs/bootstrap#17105]
use Bootstrap v3.3.5.
if not use tabindex="-1",
escape key not work,but enter is ok to close modal in chrome.
both escape and enter is not work in firefox.

**Comment by cvrebert** [comment]
Yes, you need to include the tabindex attribute. That's why all the modal examples in our docs use it.

**Comment by jcs12311** [comment]
if not use tabindex= "-1", modal can't get focus, so can't handle keydown event.
https://api.jquery.com/focus/
The focus event is sent to an element when it gains focus. This event is implicitly applicable to a limited set of elements, such as form elements (<input>, <select>, etc.) and links (<a href>). In recent browser versions, the event can be extended to include all element types by explicitly setting the element's tabindex property.

**Comment by cvrebert** [comment]
**You must use `tabindex= "-1"`.** It is not optional.

**Comment by cvrebert** [comment]
您必须包括 `tabindex="-1"` 。包括它是强制性的。这是不可选的。
（使用谷歌翻译翻译）
