### ISSUE TITLE
Cards aren't block-level but docs say they are

### ISSUE THREAD

**Issue by MatTheCat** [twbs/bootstrap#17103]
[In the doc](http://v4-alpha.getbootstrap.com/components/card/#sizing) it's stated

> Cards are block-level by default

But there is no `display` on `card` class so if I add it on a link it'll stay inline-level. Considering border and sizing I don't think a card should be inline-level so I suggest adding `display: block;` on `.card`.

**Comment by mdo** [comment]
Addressed in 9c52e03.

**Comment by MatTheCat** [comment]
The real problem wasn't the doc. A card is not made to be inline so #17158 make way more sense than 9c52e03d31be40322f59062551519a7d4e009bef.

**Comment by MatTheCat** [comment]
The real problem wasn't the doc. A card should not be inline so #17158 made way more sense than 9c52e03d31be40322f59062551519a7d4e009bef. Plus, you cannot use grid classes on cards because of their padding.
