### ISSUE TITLE
Documentation typo "flexbix"

### ISSUE THREAD

**Issue by gpaton** [twbs/bootstrap#17108]
Typo in this paragraph :
http://v4-alpha.getbootstrap.com/getting-started/flexbox/#why-flexbox

`flexbix` instead of `flexbox`

**Comment by cvrebert** [comment]
Already fixed, we just haven't redeployed the site yet.

**Comment by gpaton** [comment]
OK nice reactivity :)

**Comment by cvrebert** [comment]
And yet we're not [reactive](http://www.reactivemanifesto.org/) :stuck_out_tongue_closed_eyes:
