### ISSUE TITLE
Change "Not supported" to "N/A" for Safari on Windows

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#17104]
In [desktop browsers](http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#desktop-browsers), Safari is noted as "Not supported", but as its latest release is from 2011 (Safar 5.1), shouldn't that be changed to "N/A", a 4 year gap is more than enough to consider the browser unexisting on Windows. IE for Mac is also not noted as "Not supported".

**Comment by cvrebert** [comment]
You would be surprised. People have actually filed Bootstrap bug reports regarding Windows Safari, with no shame in several cases, presumably due to lack of knowledge.
I would prefer to keep the existing "Not supported" labelling to make it perfectly unambiguous that we don't support it.

**Comment by patrickhlauke** [comment]
/me fires up IE5.5/Mac to file some bugs ;)

**Comment by mdo** [comment]
Leaving as is for now.

**Comment by cvrebert** [comment]
Gratuitous examples:
#16377, https://github.com/twbs/bootstrap/issues/15349#issuecomment-66826810, #11189, https://github.com/twbs/bootstrap/issues/13117#issuecomment-38127534, #11028, https://github.com/twbs/bootstrap/issues/10829#issuecomment-69308318
