### ISSUE TITLE
active and hovered checkbox button background colors should not be the same

### ISSUE THREAD

**Issue by philgyford** [twbs/bootstrap#17101]
If a v4 checkbox button is 'active' then clicking it with the cursor to uncheck it provides no visual feedback. This is because the 'active' and 'hover' states have the same background colours. You have to move the cursor away from the button to verify it is now unchecked.

Here, the middle checkbox is not checked/active, although it looks like it is:

![checkboxes](https://cloud.githubusercontent.com/assets/66670/9378268/fe4fcc36-4717-11e5-9bd8-805903bc183b.png)

**Comment by patrickhlauke** [comment]
hmmm...i'm fairly sure i had a PR in v3 that addressed this exact problem. wonder if it got left out in the transition to v4...

ah, i'm thinking of this https://github.com/twbs/bootstrap/pull/16154

**Comment by cvrebert** [comment]
\*sigh* And this is why I said we should audit the recent v3 commits to ensure they had been ported and thus guard against such regressions...

**Comment by mdo** [comment]
> *sigh*

There were bond to be oversights on my part :).

**Comment by mdo** [comment]
Addressed in 1f153b6.

**Comment by patrickhlauke** [comment]
<3
