### ISSUE TITLE
v4 - Card missing white background or bg-default missing

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#17117]
Cards background are by default transparent. But I need it to be white (like formaly panel-default).

So we need `card-default` or `bg-default` to fix this.

**Comment by kkirsche** [comment]
Personally I've never felt default should be the name since that's not really accurate. Default is transparent. I would argue for a bg-white and bg-inverse of it as black

**Comment by TheZoker** [comment]
Would also be fine!

**Comment by mdo** [comment]
Fixed with #17120.
