### ISSUE TITLE
v4 - Touch gesture support for carousel

### ISSUE THREAD

**Issue by nodkz** [twbs/bootstrap#17118]
This is must be introduced in v3. 
If bootstrap goes adaptive and mobile friendly - carousel must support swipe on touch devices!
http://v4-alpha.getbootstrap.com/components/carousel/#example

**Comment by kkirsche** [comment]
I'm not sure I know what you mean by "this is must be introduced in v3" — v3 is essentially feature frozen so new features most likely won't be added to it as we are preparing for only critical bug fixes to it.

**Comment by surjithctly** [comment]
He meant, This feature should have been introduced in v3, But its already late :)

Now, The requested feature should add in v4 not v3 :P

**Comment by rustd** [comment]
+1 for this. This will be useful now that bootstrap-touch-carousel is not being maintained https://github.com/ixisio/bootstrap-touch-carousel

**Comment by fat** [comment]
yep agreed, it's not ~that~ hard to do… maybe for thanksgiving or xmas i'll write it if ya'll haven't already

**Comment by patrickhlauke** [comment]
would this include both touch events and pointer events (the latter for IE/Edge on Windows touchscreen laptops, where touch events are not enabled by default)? if so, it can start to get quite dense without any third-party library like hammer.js that papers over the differences in event models

**Comment by nodkz** [comment]
Nice vanilla slider https://github.com/gilbitron/Ideal-Image-Slider

I already migrated to React. But may be it would be helpful - reactive sliders for React are:
http://kenwheeler.github.io/nuka-carousel/
http://oliviertassinari.github.io/react-swipeable-views/

**Comment by GianlucaMaggio** [comment]
Did you plan it in next alpha? Or when will be available?

**Comment by Johann-S** [comment]
No date for this feature but it's planned for V4 (see : https://github.com/twbs/bootstrap/pull/17021) and we are open for PRs 😄

**Comment by zberno** [comment]
There is a lot of options, events and who know what strange feature needs for a project working on a touch/drag carousel.
Maybe it's not the right method but.. I'm here to suggest something like this:
http://idangero.us/swiper/

**Comment by marchy** [comment]
Any status update on this?
Would be great to know rough timeline (ie: even which quarter/season) as to plan accordingly.

Cheers!

**Comment by endcore** [comment]
+1

**Comment by kaungmyatlwin** [comment]
+1

**Comment by Nodws** [comment]
years later, we still need to hack the events in

**Comment by patrickhlauke** [comment]
PRs welcome...

**Comment by patrickhlauke** [comment]
@mdo any mileage in looking at including (or making a plugin/extension) something like hammer.js rather than coding up our own swipe detection? https://patrickhlauke.github.io/touch/hammer/swipe/

**Comment by odahcam** [comment]
Like Popper, Hammer.JS could be a good addition for Bootstrap. @angular/material2, for example, uses Hammer.JS for a lot of cool things that Bootstrap may want to have in the future.

Carousel example: https://codepen.io/odahcam/pen/WdZbev

**Comment by pretty** [comment]
+1

**Comment by husbas** [comment]
+1

**Comment by S8nsick66** [comment]
+1

**Comment by odahcam** [comment]
Please, stop with these +1 comments, this creates unnecessary notifications for **ALL** subscribed people. 

Please use the +1 thumbs-up  👍  in the issue itself instead. We all thank you! ❤️

**Comment by astralmaster** [comment]
Two and a half years later,  the 'mobile-first' framework has no swipe support.

**Comment by patrickhlauke** [comment]
which is surprising, considering the huge number of people that helped out here with pull requests...

**Comment by odahcam** [comment]
There's a lot of better carousels around there, people just prefer to usem them instead of recreating the wheel, that's because Bootstrap's carousel stills the same. To develop touch support by hand for just a carousel now would be the dumbest thing we could for to Bootstrap, a lot of work for just one component, but by using some touch events recognizer could give to us the possibility of a lot new implementations (e.g. slider-inputs), that's the same case than Popper.js, which gives to Bootstrap more advantages than just tooltip positioning.

**Comment by aka1922** [comment]
@odahcam this feature has been confirmed.

**Comment by odahcam** [comment]
@aka1922 I know that, I'm just answering @patrickhlauke comment, also I shared some ideas to get this carousel to work. I could not understand you point.

**Comment by pkerling** [comment]
Quick hammer.js solution that works with the bootstrap 4 carousel:

```
    $('.carousel').each(function () {
        var $carousel = $(this);
        var hammertime = new Hammer(this, {
            recognizers: [
                [Hammer.Swipe, { direction: Hammer.DIRECTION_HORIZONTAL }]
            ]
        });
        hammertime.on('swipeleft', function () {
            $carousel.carousel('next');
        });
        hammertime.on('swiperight', function () {
            $carousel.carousel('prev');
        });
    });
```

**Comment by S8nsick66** [comment]
IGNOREME: I am commenting here so I can easily find this issue again in the future, [since I can't do that by subscribing alone] (https://github.com/isaacs/github/issues/283).

**Comment by Johann-S** [comment]
There are a lot of people which need this feature, so it would be nice if some of you take a look at this PR #25776 which implement Swipe left and Swipe right for our Carousel thank you 😄

**Comment by mattheussgrott** [comment]
+1

**Comment by qhuydtvt** [comment]
I'm struggling with it too

**Comment by sadaktx** [comment]
@pkerling - I'm trying to use your hammerjs solution on my bootstrap v4 carousel. Where do you specify the carousel id (in my case - myCarousel)? It doesn't seem to work for me. I'm using it iniside an Angular 5+ component template that has a carousel which needs swipe functionality (I know once #25776 is resolved then it will be automatically available). But i need an interim solution and your seem to be helpful.
Thanks much!

**Comment by pkerling** [comment]
@sadaktx It enables touch on all HTML elements with class `carousel`, since that is what bootstrap requires for styling purposes anyway. If you have different needs, adjust the selector in the first line. I can't help you with Angular, sorry.

**Comment by abrambailey** [comment]
Really surprised v4 didn't address this. Will try hammer, but expect he won't let me touch this.

**Comment by abrambailey** [comment]
Hammer worked ok for me.

**Comment by SemanticMikeG** [comment]
I added this to get it working with JQuery:

(function ($) {

    var touchStartX = null;

    $('.carousel').each(function () {
        var $carousel = $(this);
        $(this).on('touchstart', function (event) {
            var e = event.originalEvent;
            if (e.touches.length == 1) {
                var touch = e.touches[0];
                touchStartX = touch.pageX;
            }
        }).on('touchmove', function (event) {
            var e = event.originalEvent;
            if (touchStartX != null) {
                var touchCurrentX = e.changedTouches[0].pageX;
                if ((touchCurrentX - touchStartX) > 60) {
                    touchStartX = null;
                    $carousel.carousel('prev');
                } else if ((touchStartX - touchCurrentX) > 60) {
                    touchStartX = null;
                    $carousel.carousel('next');
                }
            }
        }).on('touchend', function () {
            touchStartX = null;
        });
    });

})(jQuery);

**Comment by santyas** [comment]
@SemanticMikeG great job

**Comment by sadaktx** [comment]
I was able to get it work in Angular 5:
In ts file, implement the carousel swipe method based on @pkerling & in the template

ts file:
-------
import * as Hammer from 'hammerjs';
declare var $: any;

@ViewChild('myCarousel')
  private myCarousel: ElementRef;

public swipe(): void {
  let carousel = this.prodCarousel.nativeElement;
  let $carousel = $(carousel);
  let hammertime = new Hammer(carousel, {
      recognizers: [
          [Hammer.Swipe, { direction: Hammer.DIRECTION_HORIZONTAL }]
      ]
  });
  hammertime.on('swipeleft', function () {
    $carousel.carousel('next');
  });
  hammertime.on('swiperight', function () {
    $carousel.carousel('prev');
  });
}
----------------------
template file
-------------
<div id="myCarousel" #myCarousel (swipeleft)="swipe()" (swiperight)="swipe()" class="carousel slide">
                    
                    <div class="carousel-inner">
                        <div class="item carousel-item text-center" [attr.data-slide-number]="index" *ngFor="let image of product.attribute; let index=index;" [ngClass]="{'active': index === 0}">
                            <img [src]="imageURL + image.imageName" class="img-fluid" alt="{{product.name}}" title="{{product.name}}" />
                        </div>
                    </div>
                    <ul class="carousel-indicators mt-2" *ngIf="product.attribute.length > 1">
                            <li data-target="#myCarousel" [attr.data-slide-to]="index" *ngFor="let image of product.attribute; let index = index" [ngClass]="{'active':index===activeIndex}" (click)="scrollToBundle(index)">
                                <a id="carousel-selector-0" class="selected">
                                    <img [src]="imageURL + image.imageName" class="img-fluid" alt="{{product.name}}" title="{{product.name}}" />
                                </a>
                            </li>
                        </ul>
                </div>

**Comment by odahcam** [comment]
Just a tip to help on sharing ~fancy~ code. 😊

> From GitHub docs:

    GitHub also supports something called code fencing, which allows 
    for multiple lines without indentation:

    ```
    if (isAwesome){
      return true
    }
    ```

    And if you'd like to use syntax highlighting, include the language:

    ```javascript
    if (isAwesome){
      return true
    }
    ```

**Comment by abrambailey** [comment]
@odahcam It drives me crazy how few people bother to use proper syntax highlighting in github issues 😆

**Comment by zchking** [comment]
now still not add this feature?

**Comment by johanlantz** [comment]
I have used owlslider in the past and it worked great. Is @SemanticMikeG solution moot since it’s based on jquery?
Either way, have to agree it would be sweet to just have this as a native part of bootstrap if it makes sense to the creators. It seems as it’s not a technical boundary as several solutions has been proposed. Maybe philosophical?

**Comment by ki11ua** [comment]
A solution I use in both bootstrap 3 and 4, BUT with including touchswipe library: https://cdnjs.cloudflare.com/ajax/libs/jquery.touchswipe/1.6.18/jquery.touchSwipe.min.js

`
            if($('.carousel').length){
              $('.carousel').carousel({interval: 7000, pause: false });
              $(".carousel").swipe({
                swipe: function(event, direction, distance, duration, fingerCount, fingerData) {
                  if (direction == 'left') $(this).carousel('next');
                  if (direction == 'right') $(this).carousel('prev');
                },
                allowPageScroll:"vertical"
              });
            }
`

**Comment by vnt** [comment]
I hope the swipe is officially introduced as soon as possible. 
Mobile first

**Comment by sicaboy** [comment]
+!

**Comment by jonathanlal** [comment]
+1

**Comment by rae0724** [comment]
yeap , swipe is needed! especially for mobile/touch screen device.

**Comment by Johann-S** [comment]
Our PR is ready and you can test it here: https://deploy-preview-25776--twbs-bootstrap4.netlify.com/docs/4.1/components/carousel/

We'll wait a few couples of days and we'll merge my PR, so if you have any feedbacks do not hesitate 👍

**Comment by rae0724** [comment]
Nice it works well on my iphone!

**Comment by garysui** [comment]
It's a good start! Ideally, when touched, the carousel should "stick" to users finger during swiping. Currently it's only starting moving after swipe gesture is completed.

**Comment by redoper1** [comment]
Works nice on my S9+. I think that sticking to the users finger could be added later. It's more like nice to have than must have like the basic touch support.

**Comment by rae0724** [comment]
> Our PR is ready and you can test it here: https://deploy-preview-25776--twbs-bootstrap4.netlify.com/docs/4.1/components/carousel/
> 
> We'll wait a few couples of days and we'll merge my PR, so if you have any feedbacks do not hesitate 👍

hi there! how can we use it? i have check the current files, it's still not working
https://getbootstrap.com/docs/4.1/components/carousel/

**Comment by patrickhlauke** [comment]
coming in 4.2

**Comment by S8nsick66** [comment]
On my iPhone 6s with Chrome 71.0.3578.77

- The controls doesn't work until I have swiped one time
- The direction of my initial swipe sets the direction for both controls

**Comment by GreedyBytes** [comment]
> On my iPhone 6s with Chrome 71.0.3578.7. Same in latest Safari.
> 
> * The controls doesn't work until I have swiped one time
> * The direction of my initial swipe sets the direction for both controls

Thanks for this feature! I was waiting years that bootstrap would support touch swipe on it's own :) 

For me swiping works fine, but only if I use the control arrows or indicators first. 

After initial load touch swipe doesn't work. The direction of swipe works correctly for me.

I got this beheaviour on mobile (73.0.3683.20) and desktop Chrome (73.0.3683.86), without any configuration of the carousel.

**Comment by daffinm** [comment]
I see the same thing as you @GreedyBytes on Android/Chrome Beta 74.0.3729.112 and Dev 75.0.3770.16. Swiping is ignored until I use the previous or next controls for the first time.

**Comment by Johann-S** [comment]
Hi @GreedyBytes and @daffinm,

that's because you have to initialise your carrousel manually to enable that:

```js
$('#myCarousel').carousel()
```

**Comment by dersar00** [comment]
Is any way currently make it work?

**Comment by Johann-S** [comment]
@dersar00 it's already working, you can test it in our docs 👍

**Comment by alek777** [comment]
> Hi @GreedyBytes and @daffinm,
> 
> that's because you have to initialise your carrousel manually to enable that:
> 
> ```js
> $('#myCarousel').carousel()
> ```

I have tried this and i keep getting
```
(...).carousel is not a function
```
I have jQuery implemented, added interface and all that stuff.
If i remove the ```$('#myCarousel').carousel()```, the code works BUT i still have to manually click the right arrow in order for swipe to work.

**Comment by Catterine** [comment]
one year after the last comment .... i have still a problem with the touch-swiping function.
installed latest bootstrap 4.5, use the data-touch="true", initalised the function like it is said above. What is my failure? it is not possible to swipe, until the controls are used for the first time ...

**Comment by patrickhlauke** [comment]
Just for reference: tested on iPhone 7/iOS14 Safari/Chrome, and Android 10 Chrome 87/Firefox 83 - both the 4.5 and 5.0 docs page for carousel. found no issues, swiping worked without needing to have previously interacted with the carousel.
