### ISSUE TITLE
getbootstrap.com navbar splits across 2 lines on narrower screens

### ISSUE THREAD

**Issue by kewogc** [twbs/bootstrap#17110]
My issue in image
![rsz_1rsz_bootstrap](https://cloud.githubusercontent.com/assets/1654087/9379844/85491008-4745-11e5-9956-5818061ec90d.jpg)
Something wrong in navbar?

**Comment by cvrebert** [comment]
Looks like the new "Themes" button puts us over our width budget.
CC: @mdo

**Comment by kkirsche** [comment]
While maybe not the prettiest, a simple solution would be to change `.container` to `.container-fluid` which would address the issue.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
