### ISSUE TITLE
v4 - Card Column Sizing

### ISSUE THREAD

**Issue by AbbyLynn** [twbs/bootstrap#17111]
When putting column sizing on the `card` item itself, the header gets a little funky. But if you put the `col-*-*` as a div around it, there is no issues.

<img width="308" alt="screenshot 2015-08-20 05 19 03" src="https://cloud.githubusercontent.com/assets/487798/9380027/6b6a8288-46fb-11e5-9df0-600ecf0c5e6b.png">

(As in screenshot)
```html
<div class="card col-lg-3">
  <div class="card-header">
    Featured
  </div>
  <div class="card-block">
    <h4 class="card-title">Special title treatment</h4>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```

Works:
```html
<div class="col-lg-3">
  <div class="card">
    <div class="card-header">
      Featured
    </div>
    <div class="card-block">
      <h4 class="card-title">Special title treatment</h4>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
</div>
```

Most other items in bootstrap this can be done and is nice to cut down on excess lines. Would be great to make this happen as well.

**Comment by cvrebert** [comment]
> Most other items in bootstrap this can be done

There are already some other widgets where wrapper divs are required (https://github.com/twbs/bootlint/wiki/E012), so this isn't hugely persuasive IMHO, but if it indeed can't be avoided for cards, it definitely needs to be documented.

**Comment by AbbyLynn** [comment]
Well, technically according to the style guide for html/css code bootstrap follows it does make more sense to:

http://codeguide.co/#html-reducing-markup

**Comment by cvrebert** [comment]
Oh yes it's most certainly one of the goals, it's just not achievable 100% of the time. Just trying to set expectations in the event that it ends up not being possible. We'll give it the old college try though. :smile:

**Comment by AbbyLynn** [comment]
hehe Alrighty :P Just wanted to mention it cause you said it wasn't hugely persuasive but just kinda of figured that was a given, but then again i should never assume anymore given what i deal with everyday at my work..

**Comment by mdo** [comment]
Yeah for now a wrapper is required: http://v4-alpha.getbootstrap.com/components/card/#sizing.
