### ISSUE TITLE
Getbootstrap.com not working.

### ISSUE THREAD

**Issue by tareq-halaby** [twbs/bootstrap#17126]
Yesterday the http://getbootstrap.com was in a redirects loop & today it's redirecting to the old version http://getbootstrap.com/2.3.2

What's up?

**Comment by kkirsche** [comment]
![screen shot 2015-08-20 at 9 05 06 am](https://cloud.githubusercontent.com/assets/947110/9383912/92f46d7c-471a-11e5-9979-a40b704f09be.png)

I'm not experiencing this redirection

**Comment by alc** [comment]
@tareq-halaby I was having the same issues: yesterday a redirect, and today being sent to the old docs (Windows 7/Chrome Canary).  Clearing my browsing data and reloading the page fixed it for me.

**Comment by hnrch02** [comment]
We had some DNS issues yesterday, please clear your browser cache and try again. See also #17019.
