### ISSUE TITLE
v4 - Scrollspy: Example in navbar broken

### ISSUE THREAD

**Issue by bravedick** [twbs/bootstrap#17125]
![image](https://cloud.githubusercontent.com/assets/988471/9383370/2d5a0d50-4751-11e5-970d-235a07dcfc6b.png)

**Comment by hnrch02** [comment]
Fixed by #17156.

**Comment by kkirsche** [comment]
Hm. Thought the merge should have auto closed this

**Comment by hnrch02** [comment]
They are only auto-closed when the commit lands in the main branch - "master" in our case.

**Comment by kkirsche** [comment]
Ah ok. Sorry, I wasn't clear on that
