### ISSUE TITLE
v4 - btn-xs does not work

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#17121]
Simple not working:
![img_2015 08 20_13h59m37s_004_](https://cloud.githubusercontent.com/assets/1368405/9382749/bfed374a-4743-11e5-8d5e-12980f6a48be.png)

**Comment by kkirsche** [comment]
They were removed on purpose and the docs will be updated to reflect that shortly. See also #17029.

**Comment by TheZoker** [comment]
Thats bad, because they where really usefull

**Comment by kkirsche** [comment]
I don't necessarily disagree, I have used them pretty extensively in the past as well. Just passing on that it was intentional :smiley: :

**Comment by hnrch02** [comment]
Closing as per #17029.
