### ISSUE TITLE
v4 - Need example of vertical alignment. May be need component.

### ISSUE THREAD

**Issue by nodkz** [twbs/bootstrap#17122]
Bootstrap v4 add great features, which cover all my needs:
- .hidden-X-up .hidden-X-down
- no-margin and spacers
- great adaptive modal dialog

Except one:
- no vertical aligment in div (example or component)

**Comment by kkirsche** [comment]
@nodkz using flexbox would probably be your best option for that. Otherwise any implementation gets messy as you'd need either the height of the div or if it's unknown you get into some messy Y translation / absolute positioning

**Comment by hnrch02** [comment]
If you use the new flexbox grid, we have classes for vertical alignment now: https://github.com/twbs/bootstrap/blob/b591d232a6bf3f830daee4bf40f47e76f8ec66be/scss/_grid.scss#L71-L123. Just needs documenting, see #17119.

**Comment by joedajigalo** [comment]
@hnrch02 

Curious, why not set it up like so?

<pre><code>
// Alignment for every column in row
@each $bp in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($bp) {
    .row-#{$bp}-top    { align-self: flex-start; }
    .row-#{$bp}-center { align-self: center; }
    .row-#{$bp}-bottom { align-self: flex-end; }
  }
}

// Align per column
@each $bp in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($bp) {
    .col-#{$bp}-top    { align-self: flex-start; }
    .col-#{$bp}-center { align-self: center; }
    .col-#{$bp}-bottom { align-self: flex-end; }
  }
}
</code></pre>

I'm following the same code snippet as `_grid.scss` lines 8-14. If this is incorrect, I would like to know. 

Thanks.

**Comment by hnrch02** [comment]
@mdo wanted to keep the complexity to a minimum, IIRC. Might have changed now though.

**Comment by mdo** [comment]
I'm open to a PR on that stuff to reduce the repetition, so long as we feel it's approachable enough for folks.

**Comment by mdo** [comment]
Added flexbox utils in #19099.
