### ISSUE TITLE
touch events support

### ISSUE THREAD

**Issue by PopoApple** [twbs/bootstrap#17128]
can it have touch events support on mobile device?

**Comment by kkirsche** [comment]
Google translate: Supports touch events on a mobile device?

Not sure I understand the question. Bootstrap does support touch events on iOS, Android and I believe Windows Phone

**Comment by PopoApple** [comment]
i say the carousel，i think it may support swipe to change pages on mobile device

**Comment by kkirsche** [comment]
I believe this is a duplicate of #17118

**Comment by hnrch02** [comment]
Closing as a duplicate of #17118.
