### ISSUE TITLE
grid floating issue using images with different sizes

### ISSUE THREAD

**Issue by MetroMarv** [twbs/bootstrap#17127]
I'm using 4 4-column-boxes with an image. There is a strange floating behavior if all images have the same size (768x510px) except for the second (768x514px): 

![snapshot1](https://cloud.githubusercontent.com/assets/9006725/9383457/7b70c5a4-4749-11e5-8cc8-86ed03f3cea6.png)

If images have the same size or if the second one is small than the other images everything is fine. 

I used the following code:
```html
    <!DOCTYPE html>
    <html lang="de">
      <head>
	  <meta charset="utf-8">
	  <link rel="stylesheet" href="css/bootstrap.min.css">
	  <link rel="stylesheet" href="css/bootstrap-theme.min.css" />
      </head>
      <body>
	  <div class="container">
	    <div class="row">
		<div class="col-sm-4">
		  <img class="img-responsive" src="http://lorempixel.com/768/510/" alt="test">
		  768x510px
		</div>
		<div class="col-sm-4">
		  <img class="img-responsive" src="http://lorempixel.com/768/514/" alt="test">
		  768x514px
		</div>
		<div class="col-sm-4">
		  <img class="img-responsive" src="http://lorempixel.com/768/510/" alt="test">
		  768x510px
		</div>
		<div class="col-sm-4">
		  <img class="img-responsive" src="http://lorempixel.com/768/510/" alt="test">
		  768x510px
		</div>
	    </div>
	  </div>
	  <script src="js/jquery-1.11.2.min.js"></script>
	  <script src="js/bootstrap.min.js"></script>
      </body>
    </html>
```
jsBin: http://jsbin.com/cogevanile/edit?html,output

Tested Versions: 
- v3.3.5
- current master Branch

Tested Browsers:
- Firefox 40.0
- Opera 12.16
- Chromium 44.0.2403.89

**Comment by hnrch02** [comment]
This is how floats work. That's why you need a new `.row` element, well, for each new row of images.

**Comment by MetroMarv** [comment]
If I add a few more images it looks like that: 
![snapshot1](https://cloud.githubusercontent.com/assets/9006725/9385742/616900c2-4758-11e5-8119-7d94cf2eb270.png)
(second picture has a different size)

I thought that this is the right way: 
![snapshot2](https://cloud.githubusercontent.com/assets/9006725/9385757/73b1b814-4758-11e5-8992-c9f5b554166d.png)
(all images have the same size)

**Comment by hnrch02** [comment]
Yes, you're right, but using `float` for a grid system is technically a hack - we use it because support for things like flexbox was relatively bad (and it didn't even exist as a standard when float grids became popular). My point is, this is not a problem we can solve in the framework unless we use flexbox. You're gonna need to add new `.row` elements after every fourth picture if you want to avoid the behavior you are seeing.

**Comment by cvrebert** [comment]
Or you can add clearfix divs after every 4th image; see http://getbootstrap.com/css/#grid-responsive-resets
