### ISSUE TITLE
v4 - Button group caret is not horizontally alligned

### ISSUE THREAD

**Issue by cihadturhan** [twbs/bootstrap#17135]
I think the image below describes.

![image](https://cloud.githubusercontent.com/assets/3739536/9386570/c3a45b5e-4764-11e5-87d0-a961a44bbb16.png)

Thanks for making bootstrap better

**Comment by kkirsche** [comment]
This is caused by: `margin-left: .25rem;` with no corresponding right margin. PR submitted to fix this.

**Comment by cvrebert** [comment]
Fixed by #17137.
