### ISSUE TITLE
 v4 - Dropup caret is missing

### ISSUE THREAD

**Issue by zacechola** [twbs/bootstrap#17144]
http://v4-alpha.getbootstrap.com/components/button-dropdown/#dropup-variation

**Comment by kkirsche** [comment]
@zacechola not sure I follow:
![screen shot 2015-08-20 at 12 25 52 pm](https://cloud.githubusercontent.com/assets/947110/9389049/efd5178c-4736-11e5-863b-9a9696226f2a.png)

**Comment by hnrch02** [comment]
I think what @zacechola means is that in v3 the caret of the dropup is facing upwards and not downwards.

**Comment by zacechola** [comment]
Yep

**Comment by kkirsche** [comment]
Ah, ok. Sorry :smiley:

**Comment by mdo** [comment]
Fixed by #17147.

**Comment by FelixINX** [comment]
Dosen't seem to be fixed, my dropup, and even on Bootstrap website, is inverse.

**Comment by kkirsche** [comment]
@FelixINX the team has not pushed updated versions of the Bootstrap alpha publicly yet. This is fixed in the latest non-compiled source, not on the pre-compiled versions of the source code or website

**Comment by FelixINX** [comment]
@kkirsche ok thank you. Is there any estimated date?
