### ISSUE TITLE
.img-responsive class should be renamed .img-fluid

### ISSUE THREAD

**Issue by equinusocio** [twbs/bootstrap#17166]
The css class `img-responsive`make confusion. This class add only a fluid behavior. Responsive concept is more big and it include a lot of things.

**Comment by Romens** [comment]
+

**Comment by equinusocio** [comment]
:+1:

**Comment by kkirsche** [comment]
X-Ref what responsive images may reference instead for clarity:
http://davidwalsh.name/responsive-images

**Comment by hnrch02** [comment]
CC @mdo

**Comment by vaibhavpandeyvpz** [comment]
+1

**Comment by zalog** [comment]
:+1:

**Comment by hnrch02** [comment]
Addressed by #17168 / #17456.

**Comment by levanijincharadze** [comment]
`.img-fluid` still **_# not working_** for me!

**Comment by equinusocio** [comment]
@hnrch02 Should this be reopened?

**Comment by mdo** [comment]
Nope, the class is there.
