### ISSUE TITLE
v4 - Dropdown should adjust its placement to ensure it stays within viewport

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#17167]
With the new version, dropdown content does not reconize, when the element is out of view and does not change the align:
![img_2015 08 20_23h35m40s_003_](https://cloud.githubusercontent.com/assets/1368405/9396325/5ad99b18-4794-11e5-9e24-06623534e49e.png)

**Comment by cvrebert** [comment]
Pretty sure the old version didn't do that either.

**Comment by TheZoker** [comment]
Jup it did:
![img_2015 08 20_23h38m47s_004_](https://cloud.githubusercontent.com/assets/1368405/9396355/a616b32c-4794-11e5-8a0d-05c05510e621.png)

**Comment by hnrch02** [comment]
[`.dropdown-menu-right`](http://v4-alpha.getbootstrap.com/components/dropdowns/#alignment) is probably what you are looking for, this behavior hasn't changed from v3.

**Comment by TheZoker** [comment]
@hnrch02 Nope did not add that class to the dropdown

**Comment by hnrch02** [comment]
Can you post your v4 test as a JS Bin?

**Comment by kkirsche** [comment]
@hnrch02 seems to have to do with being in a navbar I believe

V3 JSBin:
http://jsbin.com/rolitoqewi/edit?html,output

**Comment by cvrebert** [comment]
Ah, we used to special-case dropdowns within `.navbar-right`, but that class is gone in v4.
I do think it would be better to make the feature not navbar-specific. Should be feasible now that we're using Tether (see e.g. http://github.hubspot.com/drop/docs/welcome/ ).

**Comment by hnrch02** [comment]
Well, `.navbar-right` was replaced by `.pull-right` (for now, as @mdo said in Slack).

**Comment by LucasKA** [comment]
A dropdown menu pulled right on a fluid navbar is probably one of the most common use cases. 

Perhaps the dropdown menu should default to aligning its right side to the left side of the dropdown element, and the opposite be the special case.

**Comment by fat** [comment]
yeah i'd rather us solve this particular use case in css since so easy/common - @mdo what are your thoughts?

we could move dropdown onto tether but makes dropdown plugin a bit more complicated

**Comment by cvrebert** [comment]
> we could move dropdown onto tether but makes dropdown plugin a bit more complicated

IMHO, I think it's worth doing that. Way more robust.

**Comment by fat** [comment]
yeah fair enough

**Comment by davidklebanoff** [comment]
The suggestion of a new placement library here: #19673 - seems to have better support for flipping than Tether.

**Comment by joviczarko** [comment]
Untill this is solved (after 1 year of talking about it, here is a quick solution)

ul.pull-right .dropdown-menu {
    right: 0;
    left: initial;
}

And just add .navbar in front of the selector if you do not need this project wide...

**Comment by 0wczar** [comment]
@joviczarko in **v4 alpha6** not working. Can you please add demo via JSBin?

**Comment by erslater** [comment]
This works in v4 alpha6: <div class="dropdown-menu" style="left:initial;right:0;" ...

**Comment by Johann-S** [comment]
Closed and fixed by #22444
