### ISSUE TITLE
scss-lint needs to be installed as part of Travis build

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17165]

**Comment by thomas-mcdonald** [comment]
@cvrebert I started making some progress in #17050, which also switches us onto the Travis container infrastructure (and allows for Travis caching to be enabled). Still a bunch of various dependency failures though.

**Comment by XhmikosR** [comment]
This seems obsolete, right?

**Comment by cvrebert** [comment]
Yes.
