### ISSUE TITLE
Force linebreaks after grid tier names in v4 grid docs?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17176]
Right now the linebreaking is inconsistent and looks kinda weird:
http://v4-alpha.getbootstrap.com/layout/grid/#grid-options
<img width="842" alt="th" src="https://cloud.githubusercontent.com/assets/419884/9399455/5ad6f99c-4769-11e5-8982-27dad92b87f6.png">

**Comment by mdo** [comment]
Closed by #17207.
