### ISSUE TITLE
v4 Split button dropdowns have no border between the 2 buttons

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17180]
i.e. between the main button and the caret menu button.
But the Default split button dropdown does have a border between them.
http://v4-alpha.getbootstrap.com/components/button-dropdown/#split-button-dropdowns

**Comment by kkirsche** [comment]
Hm, technically they do on the base `.btn` class, it's just not visible. Not sure the best way to address this

**Comment by mdo** [comment]
I'm fine leaving this as-is given our approach to buttons in v4 (no difference in background and border to start for easier customization).
