### ISSUE TITLE
Broken link to Transitions plugin in Collapse docs

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17193]
The "transitions plugin" link in http://v4-alpha.getbootstrap.com/components/collapse/#collapse is broken

**Comment by maxbeatty** [comment]
It looks like `transition.js` was [removed in May](https://github.com/twbs/bootstrap/commit/ca9c850ebbfc880dc5021b451ffc9fa12184ff87) and its functionality was moved to [`util.js`](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js). I found other references to it in [the modal visual test](https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/visual/modal.html#L152) and [getting started with JavaScript doc](https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/javascript.md#L104). Should all references be removed? Anything to add?

**Comment by cvrebert** [comment]
They should be updated to refer to util.js, which might itself need to be documented if it isn't already.
