### ISSUE TITLE
Curly quotes tool in v4 docs is overzealous

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17192]
Stuff like this (http://v4-alpha.getbootstrap.com/components/modal/#modalshow ) should use plain apostrophes.
Ditto in tables of contents: http://v4-alpha.getbootstrap.com/components/tooltips/#contents
CC: @mdo

**Comment by XhmikosR** [comment]
The only workaround I can think of is using plain `html` for the headers. I'm not aware of a kramdown  switch or something.

**Comment by cvrebert** [comment]
There's the `smart_quotes` option: http://kramdown.gettalong.org/options.html#option-smart-quotes

**Comment by XhmikosR** [comment]
I haven't used it myself so I'm not sure if it'll have any impact in other part of the docs. But we can give it a go.

**Comment by XhmikosR** [comment]
I had a quick look but I that config option seems to have a universal effect. Maybe I'm missing something, though.

**Comment by cvrebert** [comment]
If killing it everywhere is the only option, that's fine by me. Dunno how @mdo feels about it though.

**Comment by XhmikosR** [comment]
Oh, OK, I thought that wasn't even an option :P

**Comment by mdo** [comment]
I'd rather we use `<code>` there to highlight those are commands. Otherwise, we should rewrite those headings to be regular text like the rest of the page.

**Comment by XhmikosR** [comment]
Whatever you prefer. I could give it a go if we all agree on something.

**Comment by cvrebert** [comment]
Addressed by #17725.
