### ISSUE TITLE
Add option to use tag selectors instead of explicit classes

### ISSUE THREAD

**Issue by zaydanmc** [twbs/bootstrap#17198]
I wonder why Bootstrap comes without auto-skinning. As the name suggests, this feature will automatically skinning components that could be skinned.
I also request a feature, named Auto-skinning Prevention. As the name suggests, this feature will prevent Bootstrap automatic skinning using **data-native** tag.

Sorry for bad english, because I Indonesian people.

**Comment by cvrebert** [comment]
@zaydanmc I'm sorry, but it's not clear what you mean by "auto-skinning". Please explain in more detail what you mean.

**Comment by zaydanmc** [comment]
Example:
<button>Test</button> will be skinned
But, if **data-native** attribute is used is not skinned.
Example:
<button data-native="true">Test</button> will not skinned.

**Comment by cvrebert** [comment]
You can easily accomplish those sorts of things yourself using Bootstrap's classes as Sass/Less mixins, but I don't think there's much interest in offering something like that out of the box. It tends to cause nasty conflicts with other widgets/libraries, thus making it unsuitable for most projects, and even then you'd still need to use classes to set which kind of button you want (primary, secondary, success, warning, danger, etc.).

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by annamalai-saro** [comment]
@zaydanmc  @cvrebert  I think its not a good idea... it will become a mess and lots  of **:not**  selector .Performance is affected.

**Comment by mdo** [comment]
We won't be doing this.
