### ISSUE TITLE
Validation icons should be optional

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17197]
Refs http://v4-alpha.getbootstrap.com/components/forms/#validation
I suspect lots of folks will want to use their own icons instead, so I think we should make them optional. Put them behind an additional class perhaps?

**Comment by jjkester** [comment]
I think that a variable (for the background image) would be ideal for this. It would be easy enough to remove the icons, but it would also be easy to use any custom icon.

**Comment by mdo** [comment]
It's easier now to remove or customize the icons, so going to leave them for now.
