### ISSUE TITLE
Navbar alignment classes link is broken in v4 docs

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17191]
The "alignment classes" link in http://v4-alpha.getbootstrap.com/components/navbar/#basics is broken

**Comment by tabone** [comment]
+1

**Comment by hnrch02** [comment]
The question is, do these still exist? One point down `.pull-{left,right}` are mentioned to "quickly align sub-components".

**Comment by mdo** [comment]
This was fixed in #17389.
