### ISSUE TITLE
Add way to get back to docs from theme site

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#17209]
Having themes on the homepage is nice but clicking it accidentally and not having a clear way back other than a back button can be frustrating.

**Comment by zacechola** [comment]
![giphy](https://cloud.githubusercontent.com/assets/498418/9409793/719c14d6-47e2-11e5-99e3-de94426b2bc4.gif)

**Comment by hnrch02** [comment]
I guess it's a little confusing having three links which lead to other pages with different layouts (Themes, Expo, Blog) right next to links which lead to sites with the same layout.

**Comment by mdo** [comment]
We'll be unifying those pages soon. In the mean time, I'd like to leave them as-is to avoid flip flopping.

**Comment by mdo** [comment]
Closing as this isn't a docs-specific problem <3. Will open an issue on our other repo for the themes site.
