### ISSUE TITLE
Pills issue (no break)

### ISSUE THREAD

**Issue by rafu1987** [twbs/bootstrap#17202]
When using `nav-pills` there is no break in Bootstrap 4 Alpha :( (see image attached)
![bildschirmfoto 2015-08-21 um 11 03 26](https://cloud.githubusercontent.com/assets/2694825/9404998/5e50eff2-47f4-11e5-8923-5c41d729d062.jpg)

**Comment by kkirsche** [comment]
@rafu1987 Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports) can you include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/qusafa/edit?html,output) if that would be helpful.

Thanks for your understanding!

**Comment by hnrch02** [comment]
It seems that neither `.nav` nor `.nav-pills` add a clearfix. CC @mdo

**Comment by rafu1987** [comment]
Sorry, didn't know about the CONTRIBUTING.md :)

Here's the link:
http://bit.ly/1LoYhOA

**Comment by Dashed** [comment]
Can confirm. Pill tabs doesn't play well with cards. Had to wrap with `<div className="card-block m-b">`.

**Comment by Deilv** [comment]
As mentioned by mdo in #17202 this issue appears to be resolved, so maybe a closure is in order? :)
