### ISSUE TITLE
Card Group: Borders are not correctly un-rounded

### ISSUE THREAD

**Issue by thriqon** [twbs/bootstrap#17203]
![2015-08-21-110758_1920x1080_scrot](https://cloud.githubusercontent.com/assets/768913/9405127/51abdfae-47f5-11e5-8f10-b78290c74dba.png)

Card Groups are not correctly un-rounded in v4. If there is nobody working on it yet, I can take a stab at it.

**Comment by mdo** [comment]
Fixed with #17212.
