### ISSUE TITLE
Drupal 7 - Bootstrap - Library - Twitter Bootstrap library - Bootstrap plugin

### ISSUE THREAD

**Issue by AlNahari** [twbs/bootstrap#17239]
Bootstrap - Library	
You need to download the bootstrap js library from github. please read the documentation. Missing: bootstrap-affix, bootstrap-alert, bootstrap-button, bootstrap-carousel, bootstrap-dropdown, bootstrap-popover, bootstrap-scrollspy, bootstrap-tab, bootstrap-tooltip, bootstrap-typeahead, bootstrap-modal, bootstrap-collapse, bootstrap-transition
Error

**Comment by AlNahari** [comment]
Twitter Bootstrap	The Twitter Bootstrap library could not be found.
The Twitter Bootstrap library could not be found.

**Comment by AlNahari** [comment]
Bootstrap plugin Not installed
The version of the Bootstrap library could not be detected.

**Comment by cvrebert** [comment]
We don't provide assistance with integrating Bootstrap with backend frameworks such as Drupal.
Please use other forums to seek help for such problems. Drupal-related ones would have the best chance of success in this case.
