### ISSUE TITLE
v4 - btn-info used in button-dropdown but not on the main buttons page.

### ISSUE THREAD

**Issue by Qqwy** [twbs/bootstrap#17234]
The `btn-info` button style is missing from
http://v4-alpha.getbootstrap.com/components/buttons/#examples

but still used on:
http://v4-alpha.getbootstrap.com/components/button-dropdown/

Either `btn-info` should be removed at the *components/button-dropdown* page, or it should be added on the *components/buttons* page

**Comment by kkirsche** [comment]
PR submitted. Thanks!

**Comment by cvrebert** [comment]
Fixed by #17235.
