### ISSUE TITLE
v4 - <a class="btn-disabled"> does not have cursor: not-allowed

### ISSUE THREAD

**Issue by Qqwy** [twbs/bootstrap#17231]
There is a slight difference between `<button class="btn btn-primary btn-disabled">Go!</button>` and `<a class="btn btn-primary btn-disabled">Go!</a>` in that the second will not show the ` not-allowed` cursor. (compare http://v4-alpha.getbootstrap.com/components/buttons/#disabled-state)

I thought this was a missing thing in the new Bootstrap v4 styling, but I found out that actually the `pointer-events:none;` that is applied to the disabled anchor tags results in the cursor not changing to `not-allowed` at all.

Is there a way to still make it show?
Or at least, if there is not, I think it would be a good idea to note this difference on the documentation page.

**Comment by kkirsche** [comment]
PR submitted. Thanks!

**Comment by cvrebert** [comment]
> Is there a way to still make it show?

Not that I know of. That's just how `pointer-events:none` works.

**Comment by mdo** [comment]
Closing per the referenced PR in #17232—`pointer-events: none` means it doesn't have an impact.

**Comment by mdo** [comment]
Made some docs tweaks in b8ff763 to help explain this a bit better.
