### ISSUE TITLE
Enable something similar to foundation zurb`s $include-html-classes

### ISSUE THREAD

**Issue by conmute** [twbs/bootstrap#17247]
Core of some components done by mixins, and new option of not generating default css. Just like Foundation Zurb does.

**Comment by kkirsche** [comment]
I don't understand. Could you explain in more depth?

**Comment by mdo** [comment]
If you're referring to something specific, like the predefined grid classes, I might do that. Been noodling on a ton of grid improvements for Alpha 2.

**Comment by conmute** [comment]
For example, we have grid.
I want to have grid with custom classes. Not col-sm-4, but small-4. In this case i can use

```less
.small-4 {
.col(small, 4);
}
```

It is just for example.

I do include all bootstrap parts, but in variable i enable this option: 
```less
@include-css-classes: false;
```

So i can use mixins to generate custom grid, but no grid classes are generated from compiling bootstrap.

In case of carousell or other parts, maybe leave as is. But if this possilbe each part to do as mixin, then  it would be awasome!

For example:
```less
.menu {
.navbar(default);
}
.links {
.navbar-nav();
}
```

etc.

**Comment by mdo** [comment]
Toggle for the predefined grid classes coming in #17259.

**Comment by mdo** [comment]
If you mean placeholders, we won't be going that route for all our components btw.

**Comment by conmute** [comment]
If to be exact, placeholders in the mixins. Just like this: http://www.sitepoint.com/sass-mixin-placeholder/
If u are going after libsass now.

If this is possible to turn also for:
* buttons (what if i need one or two buttons styls only? And i can specify them?)
* labels (sometimes i do like to name class label, and also have bootstrap labels. Would be nice to have those in mixin so i can import them under other name)

The rest can be just movved to placeholder/mixin, so there will be an option to set a custom class name for wells, list-group, alerts etc, But for such complex like component as carousell, it is better to keep as is.

**Comment by mdo** [comment]
Placeholders are likely out for v4. Too late in the game to re-architect things right now I think.
