### ISSUE TITLE
Card and its variants: outline variants and the need for .card-inverse

### ISSUE THREAD

**Issue by petetnt** [twbs/bootstrap#17243]
I am a huge fan of the new Card-component. Like many other components, it also has [some variants](http://v4-alpha.getbootstrap.com/components/card/#background-variants). These apply for the background only, and require another class, `.card-inverse` for proper text colors.

My suggestions:

- Add the `.card-inverse` styles for the `.card-primary`, `.card-info`, `.card-danger`, `.card-warning` and `.card-success` classes as an mixin
- Add new classes `.card-primary-outline`, `.card-info-outline`, `.card-danger-outline`, `.card-warning-outline` and `.card-success-outline` which would style the borders only, otherwise maintaining the regular style similar to those on `.btn`'s for quick styling

![image](https://cloud.githubusercontent.com/assets/7641760/9428238/58067304-49ae-11e5-97e3-10b71fb3311f.png)

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Merged #18099.
