### ISSUE TITLE
Request - bring muted backgrounds back

### ISSUE THREAD

**Issue by lassombra** [twbs/bootstrap#17245]
In V3 there was a series of bg classes (bg-primary for example) that provided a muted version of the same theme color.

In V4 those were changed to directly use the theme color ($brand-primary etc).  Please at least also provide muted backgrounds for those who want to have a more subtle color change or want to be able to read a variety of text colors against these highly saturated backgrounds.

Ideally these would be another variable which is derived from the $brand variables for ex: $brand-primary-muted: lighten(desaturate($brand-primary, 10%), 10%) !default;

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by hkarakose** [comment]
Did you consider using `bg-light`?

**Comment by lassombra** [comment]
bg-light is just a light grey.  It isn't a lighter version of the major colors.

Now, to be fair, v3 didn't really have background colors typically, you had to really use alerts.

However if you say use bg-info text-info together, the text is 100% unreadable.  There really should be a background variant of info that is not unlike v3 alert backgrounds to be mixed with same hue text.

**Comment by mdo** [comment]
Sat on this for awhile, closing as a won't fix for v4 and v5.

**Comment by robrez** [comment]
I was looking for this ability as well,  I was thinking that the colors used for "alerts" would serve well as "muted backgrounds"...

![bootstrap-muted-colors](https://user-images.githubusercontent.com/1993389/64555500-16a84580-d303-11e9-9d2d-528c033f1e49.png)

Something like that may fit neatly w/ a note I found in some of the color theming docs:

> This will be expanded upon in subsequent minor releases to add additional shades, much like the grayscale palette we already include.

I gather there is some additional difficulty since some components use `lighten/darken` while others use `mix`

**Comment by septatrix** [comment]
> Sat on this for awhile, closing as a won't fix for v4 and v5.

I would like to point out that many sites are still using Bootstrap v3 which reached EOL last year and will probably want to upgrade directly to v5. In v3 many components used a muted background like [panels](https://getbootstrap.com/docs/3.4/components/#panels-alternatives) and [list groups](https://getbootstrap.com/docs/3.4/components/#list-group-contextual-classes). Not having these when upgrading will be an additional burden.
