### ISSUE TITLE
.btn-group-justified v4

### ISSUE THREAD

**Issue by jorgelolz** [twbs/bootstrap#17249]
with the removal of .btn-group-justified

how to make in v4?

**Comment by cvrebert** [comment]
How-to questions are outside the scope of the bug tracker. They are better suited to other forums such as StackOverflow or IRC; see https://github.com/twbs/bootstrap/blob/master/README.md#community

**Comment by woto** [comment]
https://stackoverflow.com/questions/34450586/justify-buttons-with-bootstrap-v4/34450587#34450587

**Comment by woto** [comment]
https://stackoverflow.com/questions/34450586/justify-buttons-with-bootstrap-v4/34450587#34450587
