### ISSUE TITLE
v4 Suggestion: Add fallbacks for when JavaScript is disabled

### ISSUE THREAD

**Issue by StudioJunkyard** [twbs/bootstrap#17256]
It's just a thought, rather than relying solely on Javascript/jQuery for a lot of the components, how about implementing as much as possible using CSS. Seeing as CSS can do a lot of functions that can make Javascript unneeded these days, for those people that don't use jQuery, it would at least still allow them to use Bootstrap. And maybe still have some Javascript functions to make things like tooltips do extra things that Javascript is needed for, but the components can still work in at least a rudimentary form if jQuery, or Javascript isn't used. Anyway, just food for thought.

**Comment by cvrebert** [comment]
Any specific/concrete suggestions related to this?

**Comment by StudioJunkyard** [comment]
Not as such, I was thinking that it would be nice to be able to have the majority of components that need or require Javascript to not have to rely on having Javascript at all. Might make for a nice fallback for those that purposely disable Javascript. We might be able to get some .onion sites working with BS that actually look nice without the use of Javascript, lol.

A thought I had for the tooltips though, is to have classes that force positioning. I noticed in your Blog post that you mentioned about have auto-positioning, which obviously wouldn't work if Javascript is disabled, unless of course there's a way to do auto-positioning with pure CSS, not that I've ever come across such a thing before, lol.

Also, feel free to check out some of the extra's I've added onto BS for my own purposes, if only for idea's.
http://studiojunkyard.github.io/LibreICONS/

**Comment by kkirsche** [comment]
@StudioJunkyard we no longer include any icon fonts with Bootstrap as of V3 so the LibreICONS wouldn't be applicable here

**Comment by StudioJunkyard** [comment]
Sorry, wrong link, I meant the CSS I added to Bootstrap here, http://studiojunkyard.github.io/LibreICONS/examples.html#custom

**Comment by cvrebert** [comment]
Understood. It basically comes down to what @fat & @mdo are willing to implement/support.

Current policy in this area for reference: http://getbootstrap.com/javascript/#js-disabled

**Comment by StudioJunkyard** [comment]
Cool, sorry, I seen "Owner" on your comments, and assumed you were one of them.

**Comment by cvrebert** [comment]
I am on the [Core Team](http://getbootstrap.com/about/#team), but they're the primary contributors.

**Comment by StudioJunkyard** [comment]
+1

**Comment by mdo** [comment]
Probably not going to happen. That's a bit of a shift in our approach to the framework and not something I'd like to see us take on right now.
