### ISSUE TITLE
Documentation options for customizing and slimming Bootstrap down

### ISSUE THREAD

**Issue by caraya** [twbs/bootstrap#17251]
Before I write the doc I'd like some feedback on the text below. 

New (and lazy) users of Bootstrap may or may not be aware of options to slim down Bootstrap and, as a result, load the entire library when they use a fraction of it.  We need to avoid the "kitchen sink approach"  that leads to bloated pages and slower load times. 

## Providing docs on available customizers

Is there a list of community customizers? Removing the official customizer web tool leaves a lot of people out in the cold as to how to customize it and some people may decide it's not worth the effort 

## Add an uncss option to the grunt build process or instructions for how to add it to an existing build process

[UNCSS](https://github.com/giakki/uncss) trims unused CSS selectors based on what is used in a given HTML document.  There are plugins for most build  systems and making note of it may help when people try to shrink the size of a Bootstrap install. 

Am I missing the documentation or would it be OK if I start writing it?

**Comment by mdo** [comment]
The best thing you can do is simply comment out the `@import`s you don't need. We can and should add some docs for that to the Options section under Getting Started.

**Comment by mdo** [comment]
I'll probably take a crack at that first before exploring anything else.

**Comment by caraya** [comment]
For people who are experienced with SASS and build processes I would agree that just removing imports is a good solution 

However that may not be the case for people who are new to SASS, new to frameworks or who download a compiled version of Bootstrap 4 without access to the SASS source, what's the recommended solution in that situation?

**Comment by mdo** [comment]
We'll want to address that, too. UnCSS might be helpful there as you mentioned—I've never used it personally. We can add something for that if you want to take a crack.

**Comment by caraya** [comment]
Let me see what I can come up with. I'll update the issue when I come up with something.

**Comment by mdo** [comment]
<3

**Comment by cvrebert** [comment]
> Is there a list of community customizers?

No, but such third-party customizers do exist and I suspect many of them will be updated for Bootstrap v4. Including a list of them in the v4 docs SGTM.

Regarding UnCSS, including some info for it in the docs sounds good, but I probably wouldn't go so far as to include a task for it in Bootstrap's Gruntfile.

**Comment by mdo** [comment]
> Regarding UnCSS, including some info for it in the docs sounds good, but I probably wouldn't go so far as to include a task for it in Bootstrap's Gruntfile.

Agreed.

**Comment by caraya** [comment]
I've finished a first pass on the Uncss instructions, Unfortunately I can't attach a non-image file so I've linked it from my working copy. 

https://github.com/caraya/docs/blob/master/uncss-and-bootstrap.md

let me know what you think

**Comment by mdo** [comment]
Going to punt on this for now, thanks though!
