### ISSUE TITLE
"jekyll" cannot load such file -- jekyll-redirect-from

### ISSUE THREAD

**Issue by unehub** [twbs/bootstrap#17254]
Hello, i'm try launch site docs but not work, I followed all the steps, but you receive the following error:

        Warning: Command failed: /bin/sh -c jekyll build --config _config.yml
        /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-redirect-from (LoadError)
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:26:in `each'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:26:in `require_gems'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/site.rb:79:in `setup'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/site.rb:41:in `initialize'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:29:in `new'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:29:in `process'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/bin/jekyll:20:in `<top (required)>'
        	from /usr/local/bin/jekyll:23:in `load'
        	from /usr/local/bin/jekyll:23:in `<main>'
         Use --force to continue.

        Aborted due to warnings.

**Comment by kkirsche** [comment]
X-Ref: #17253

**Comment by mdo** [comment]
Pull the latest and try again please <3.

**Comment by Eagerestwolf** [comment]
I had the same issue. For me installing bundler, and running `bundle install` seems to have fixed the issue. It would appear there are Jekyll plugins used in the documentation.
