### ISSUE TITLE
Add a Next and Previous Button on Documentation Footer

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#17260]
I wonder why Bootstrap doc team does not add a next & previous button on the documentation footer (above the site footer).
I think, if Bootstrap doc has a next & previous button on the footer, it helping user to navigate to next/previous documentation page.

Can you add a next & previous button on the documentation footer?

Sorry for bad english, because I'am Indonesian.

**Comment by mdo** [comment]
Been wanting this, yeah. Likely means some more frontmatter in our docs pages (since these aren't posts), but that shouldn't be too bad to cook up.

**Comment by Masterbite** [comment]
This would be a great feature on the docs! Please do add this feature!

**Comment by viktor-yakubiv** [comment]
Yeah! It would be nice. Something like (here is [Figures page](http://v4-alpha.getbootstrap.com/content/figures/)):
`< Tables`  `Content` `Components -->`

Or/And make contents at the right fixed to easy navigation.

**Comment by mdo** [comment]
Skipping this given the sticky sidebar in v4's docs.
