### ISSUE TITLE
Scrollbar within modal is placed incorrectly in OS X Chrome

### ISSUE THREAD

**Issue by yleo77** [twbs/bootstrap#17267]
### Steps to Reproduce

* *modal-body* has a fixed height or a max-height.
* the element named child in *modal-body* has a css property `height` that it's value is more than *modal-body*'s.
* child has a css property `position: relative`

### Appearance:

Scrollbar shift to wrong position.

### Browser & OS:

* Chrome v45 with MAC

(Both of Chrome with windows, Firefox, Safari and IE11 are OK, so as a  result , may be it's a browser bug, I think.)

### Resolve:

Add `overflow: hidden` to *modal-dialog* element

### Example: 

For details, checkout this fiddle:  http://jsfiddle.net/s1f42hvs/

**Comment by cvrebert** [comment]
> Scrollbar shift to wrong position.

@yleo77 Erm, you mean how your example has 2 different scrollbars, or...?

> *modal-body* has a fixed height or a max-height.

I wouldn't recommend messing with any of the `.modal-*` classes in such a way in the first place.

**Comment by yleo77** [comment]
@cvrebert No. I mean the modal-body's scrollbar， not the body's.

checkout this gif for details: 

![bug](https://cloud.githubusercontent.com/assets/334762/9457029/4950c79c-4b11-11e5-9a51-9113f22d50a1.gif)

expected:

![expected](https://cloud.githubusercontent.com/assets/334762/9457097/db58705e-4b11-11e5-9b68-1bc4062d20b6.gif)

thank you for your advise, I follow it, but this case is still here ...

**Comment by pigeonman99** [comment]
i was facing the same problem and stumbled upon this bug. i'm not using bootstrap so i think this is not a bootstrap bug. it's more like a chrome bug.

**Comment by cvrebert** [comment]
Yeah, the intended scrolling paradigm for Bootstrap modals is that the modal-dialog scrolls, rather than setting a fixed height and making an element within the modal scroll, like you're doing. So it's not strictly a vanilla-Bootstrap-related bug.
However, I do encourage you to file a Chrome bug on your own (via https://crbug.com/new ) and post a link to the bug here when you're done so folks can follow it. Good luck!
