### ISSUE TITLE
CSS only file input

### ISSUE THREAD

**Issue by andykirk** [twbs/bootstrap#17269]
In response the 'Heads up' note in http://v4-alpha.getbootstrap.com/components/forms/#file-browser

I've had quick go at rebuilding the input to allow it to show the filename of the chosen file:

https://jsfiddle.net/AndyKirk/zs4byLse/1/
https://gist.github.com/andykirk/b7c9e26dc83edd61cdfa

Working on Windows 7 IE9+, FF, Chrome, Opera.

It contains some CSS hacks and isn't widely tested yet but it shows it can done. I just wanted to see if it was of interest. Happy to do more work on it if it is.

Thanks.

**Comment by twbs-lmvtfy** [comment]
Hi @andykirk!

You appear to have posted a live example (https://gist.github.com/andykirk/b7c9e26dc83edd61cdfa), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by hnrch02** [comment]
CC @mdo

**Comment by mdo** [comment]
Finally coming around to take a look at this—for some reason Sass fails to minify the `@supports` bit for Firefox hacks.

**Comment by andykirk** [comment]
Thanks for the response. I did see a comment error in my previous code (extra */), so I've [updated the fiddle](https://jsfiddle.net/AndyKirk/zs4byLse/2/) and fixed the gist.

However, I can't reproduce anything to do with an `@supports` minification error. There was a [bug in libsass](https://github.com/sass/libsass/issues/261) but it seems to have been fixed.

I'm Using libsass 3.3.2. Also no problems minifying via [Sassmeister](http://www.sassmeister.com/).

**Comment by xzyfer** [comment]
Hi all, I'm from the LibSass team. Is this still an issue?

**Comment by mdo** [comment]
Looked at this one again tonight. Overall, I'm super impressed with the demo! It's pretty rad to be able to target those file upload buttons in Webkit and IE. However, this falls down in Firefox with the negative margin hack there. Change the font-size and it breaks quite easily. Thanks for the suggestion, but we'll have to pass for that last bit.

**Comment by andykirk** [comment]
@mdo Ok, thanks.

@xzyfer - sorry, I only just noticed your comment. I was never able to reproduce the problem so I guess there's no problem now.

Thanks,
