### ISSUE TITLE
Padding issue for input-group large size

### ISSUE THREAD

**Issue by abinthomas** [twbs/bootstrap#17268]
![padding-issue](https://cloud.githubusercontent.com/assets/9411539/9438587/a6fde1c6-4a7c-11e5-84cb-14353d4985d4.png)

The issue in v4-alpha

**Comment by zacechola** [comment]
Duplicate of #17035

**Comment by abinthomas** [comment]
Thank you @zacechola

**Comment by cvrebert** [comment]
Please search next time :smile:
