### ISSUE TITLE
.card-block p:last-of-type should be margin-bottom: 0

### ISSUE THREAD

**Issue by brwr** [twbs/bootstrap#17274]
Inside `.card-block`, the last `p` tag should be `margin-bottom: 0`. This is not currently the case.

**Comment by kkirsche** [comment]
@brwr Can you post a JSBin demonstrating this issue? I wasn't able to duplicate a situation where this would be a major issue though I may be thinking through this differently than what you mean.

**Comment by monoblaine** [comment]
I had a suggestion as to remove the bottom margin of the last immediate child of a `panel-body` (which could also be applied to a `card-block`):

~~~less
.panel-body {
  & > :last-child {
    margin-bottom: 0;
  }
}
~~~

But the bs guys don't agree with that (#10825), and apparently cannot even entertain the idea. (#16765)

**Comment by brwr** [comment]
@kkirsche Here is the requested JS bin: https://jsbin.com/mikinohopa/edit?html,output

This is not a major issue. Removing the `margin-bottom` from the last `p` tag is just a reasonable default.

I am actually in favor of @monoblaine's suggestion. It is unfortunate that it was shot down so quickly in both cases.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
I'd rather see folks use `.m-b-0` to nuke things as they need, or as they customize and extend the styles, override things as needed manually.
