### ISSUE TITLE
Tooltips: "Tether is not defined"

### ISSUE THREAD

**Issue by lgkonline** [twbs/bootstrap#17273]
Today I wanted to try the Bootstrap 4 alpha and when I want to use the tooltips plugin I get this error in my debugger console:

```
Uncaught ReferenceError: Tether is not defined
bootstrap.js:2967

show @ bootstrap.js:2967
_enter @ bootstrap.js:316
4n.extend.proxy.n.isFunction.e @ jquery-1.11.0.min.js:2
n.each.n.event.special.(anonymous function).handle @ jquery-1.11.0.min.js:3
n.event.dispatch @ jquery-1.11.0.min.js:3
n.event.add.r.handle @ jquery-1.11.0.min.js:3
```

**Comment by kkirsche** [comment]
@lgkonline did you load the tether javascript library? You'll notice in the docs we load this file to load the tether library https://github.com/twbs/bootstrap/blob/v4-dev/docs/assets/js/vendor/tether.min.js#L1

**Comment by zacechola** [comment]
Should x-ref with #17201 and cc @fat. There are options for handling dependencies _in general_ that need to be worked out.

**Comment by cvrebert** [comment]
We should probably throw a more explicit "Bootstrap tooltips require Tether (<hyperlink here>)" error/warning like we do for jQuery.

**Comment by lgkonline** [comment]
Ah, got it. Thanks guys. :)
So I need to include the Tether library.

I guess I can close issue here.

**Comment by cvrebert** [comment]
Reopening to track the "throw an explicit error" suggestion.

**Comment by sdaitzman** [comment]
Does this mean that Tether needs to be imported separately from the bootstrap js?

**Comment by digitaldesigndj** [comment]
I feel like tether should be included as a bower dependency of bootstrap 4. 

Thanks for all the great work everyone.

**Comment by Bing-Du** [comment]
You need to include the Tether library. but Tether library return value is function TetherClass,
however Bootstrap4.0 direct use Tether ,that Tether is not defined.

**Comment by cvrebert** [comment]
See #17325.
