### ISSUE TITLE
RTL (right-to-left language) support

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#17279]
hi!
i customize bootstrap3 and make it's direction dynamically by adding a $dir var in variables file then on each files check if $dir == 'rtl' then float:right else float left. why you don't add this feature to bootstrap 4?! it's make bootstrap more amazing ;-)

**Comment by kkirsche** [comment]
@m-ekramy am I correct in understanding that you would like better support of RTL text formats? Just want to make sure I fully understand your goals

**Comment by m-ekramy** [comment]
yes if it can be changed dynamically by changing a dir variable in the main variable file. it's mine code that wrote for bootstrap 3:
##### _variables.scss
``$Direction: 'rtl';``
and for example in my file if i have `` float:left;`` changed it to:
``
  @if ($Direction == 'rtl'){
    float: right;
  }@else{
    float: left;
  }
``

**Comment by cvrebert** [comment]
I agree with mdo's remark (https://github.com/twbs/bootstrap/pull/17280#issuecomment-134297270) that the approach being suggested is overly simplistic and incomplete. See also https://github.com/twitter/css-flip#supported-css-properties-a-z
X-Ref: #15509
I believe the current plan is to try adding RTL support as a new feature in a minor release post-v4.0.0, although given the Core Team's lack of RTL expertise, it's still a bit up in the air.

**Comment by gam-phon** [comment]
It is very strange that bootstrap did not support RTL until now. I was waiting this feature from version 2. In some project, I have to switch to foundation because they support RTL out of the box. Bootstrap is a very great project and I hope they will support RTL very soon. Thanks for making Bootstrap even greater than before.

**Comment by mdo** [comment]
@gam-phon There are addons for handling that in v3. We didn't have too much time to put into it ourselves, so we never got around to making it official.

**Comment by oriSomething** [comment]
i remind #16419 because with better naming it would be easier path toward r-t-l support

**Comment by asaf** [comment]
(Until it's official, at least this issue can be a reference for others)

Grid columns should be flipped in RTL, what would be the most appropriate way to do the flipping ?

**Comment by oriSomething** [comment]
@asaf 
i found that is still the best in the end to have two separate `CSS` files, one to RTL and another to LTR. but, of corse it should contains both styles of `.*-start` / .`*-end` classes with `.*-left` /  `.*-right`. because in end they both needed for multi-lang support.
by the way, the reason for two separate files is `specificity` hell if your using top elements styles

**Comment by asaf** [comment]
@oriSomething Thanks,
I don't see how it solves columns flipping, what I'm saying is, if you have a grid with 2 columns a:left/b:right, : in RTL, it should look like: b:right/a:left,

**Comment by weitzhandler** [comment]
Very demanding!

**Comment by weitzhandler** [comment]
Very demanding!
BTW, [this](https://github.com/morteza/bootstrap-rtl) repo (by @morteza) does that, but it's not convenient to deal with two libraries, and it will obviously be great if it's integrated in the main repo, I'm sure the OP of that lib would also vote for this.

**Comment by weitzhandler** [comment]
Very demanding!

BTW, [this](https://github.com/morteza/bootstrap-rtl) repo (by @morteza) does that, but it's not convenient to deal with two libraries, and it will obviously be great if it's integrated in the main repo, I'm sure the OP of that lib would also vote for this.

@m-ekramy Can I achieve https://github.com/twbs/bootstrap/issues/17279#issuecomment-134264780 with LESS?

**Comment by oriSomething** [comment]
@asaf what wasn't understood?

you have the absolute direction rules `a:left/b:right` and the page local direction `a:start/b:end` that will flipped when you user the (let's say) `bootstrap-rtl.css`

**Comment by mdo** [comment]
> I'm sure the OP of that lib would also vote for this.

That person was staunchly against it actually :laughing:.

**Comment by weitzhandler** [comment]
@mdo actually I just saw in his page that he does vote for it:

[![](http://i.imgur.com/45wpD1w.png)](https://github.com/morteza/bootstrap-rtl)

What made you think he's against it in first place anyway?

**Comment by taitems** [comment]
Hey all, does the lack of a milestone set against this issue mean "it will happen when it happens" or is this going to drop as part of 4.0? I'm just not overly familiar with feature planning in Bootstrap.

**Comment by evilaliv3** [comment]
we have this requirement also in the [GlobaLeaks[(https://github.com/globaleaks/GlobaLeaks) project;

Since a little we are using the [bootrap-rtl fork](https://github.com/bright/bootstrap-rtl) made by @bright wich approach is simplified and effective: https://github.com/bright/bootstrap-rtl/blob/master/README.md

**Comment by mdo** [comment]
Punting for v4.0.

**Comment by evilaliv3** [comment]
@mdo which is the open ticket that keeps track of this topic?

**Comment by cvrebert** [comment]
@evilaliv3 There isn't one, but don't worry, given the number of times folks have asked for RTL, we won't soon forget about it. But we're not going to delay v4.0.0 for this. RTL will probably land in a later minor release (e.g. v4.2.0).

**Comment by Mohsen7s** [comment]
Is this finally supported in newest release (v4.0.0-alpha.2)?

**Comment by cvrebert** [comment]
@Mohsen7s No. Please refer to my previous comment.

**Comment by Benosika** [comment]
Inserting RTL support for Bootstrap will be a best things and will solve so much headaches for so much users. Let me demonstrate that live: The Drupal community, which I am a proud member of, for about 5 years now, has always suffered from lack of RTL support; There are many hopes within that community that releasing RTL support for Bootstrap will help quite that problem as a huge number of Drupal themes are Bootstrap based and almost any premium theme I ever saw for Drupal is Bootstrap based. This will be a major leap forward, I am so waiting for this !

**Comment by jbokkers** [comment]
@cvrebert If/when you guys go for RTL, please do a proper implementation that supports bi-directional content on an individual page. Worked in Dubai for 3yrs and can't count the number of times when when AR and EN content needed to be mixed.

I've created a port myself that [supports twbs 3.3.6, sass and ltr/rtl/bidi](https://github.com/jbokkers/bootstrap-bidirectional) by means of mix-ins and avoiding to think in terms of left and right but pushing against the box-model and pulling at the box-model but there are cleaner and better ways to make just twbs bi-directional if we're just talking about twbs scope.

In any case, more than happy to chat, assist, help when you guys are in the mood and considering this.

**Comment by al1b** [comment]
Will Bootstrap 4 support RTL? OR when will it be?

I'm developing a web application that uses Bootstrap 3.x. I would like to use Bootstrap 4 but there is not any RTL version of it.

P.S: Right now Zurb Foundation supports RTL officially.

**Comment by cvrebert** [comment]
@al1b See #19555.
