### ISSUE TITLE
v4 - btn-group-xs still exists in docs

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#17281]
The `btn-group-xs` does still exists here:
http://v4-alpha.getbootstrap.com/components/button-group/#sizing

**Comment by zacechola** [comment]
Those were removed in 2965adfea0071e05c92ca07450f473ea62714403

**Comment by TheZoker** [comment]
@zacechola Yes I know, that they where removed, but there is still a entry in the docs, that should be removed.

**Comment by kkirsche** [comment]
@TheZoker the docs haven't been updated since the commit. We will not update the docs till alpha 2

**Comment by TheZoker** [comment]
Jup this issue is just for tracking

**Comment by kkirsche** [comment]
@TheZoker the issue tracker is for tracking unresolved issues. As this has been resolved in the codebase, the next deployment will cover this. There is nothing to track here.

**Comment by mdo** [comment]
FYI, docs are updated every now and then independently of specific alpha releases. I'll push an update today to get more docs changes out there.

**Comment by mdo** [comment]
Should probably point the download link to the master ZIP instead of a specific release ZIP.
