### ISSUE TITLE
Use higher precision when calculating breakpoint-max values

### ISSUE THREAD

**Issue by chrisnicotera** [twbs/bootstrap#17282]
Bootstrap is currently using `0.1` as the value for calculating `breakpoint-max`. This causes an issue when using the `hidden-*-down` classes.

For example (assume font-size: 16px):
md: 48em, // 48 * 16 = 768px
breakpoint-max(md, (xs: 0, sm: 34rem, md: 48rem)): 47.9 // 47.9 * 16 = 766.4

This leaves a ~2px window where elements with `hidden-md-down` will show up unexpectedly.

I'm proposing changing the precision value to 0.00001. I'm not sure that 5 places are needed (too much?), but since that seems to be the default precision for SASS, I went with that.

I opened pull request #17283 for this issue.

**Comment by mdo** [comment]
No longer relevant—we're back to pixels for media queries and containers.
