### ISSUE TITLE
v4 Alpha - scss/_progress.scss triple colon

### ISSUE THREAD

**Issue by Schmalzy** [twbs/bootstrap#17288]
The latest build of v4 Alpha fails to compile for me because of triple colons on a psuedo element in the following file.

scss/_progress.scss - line 34
`.progress[value]::-webkit-progress-value:::before {`

Looks like it was recently added on this commit. - https://github.com/twbs/bootstrap/commit/d51f0a4f816534e8c39ff58d8d4c562d2dd568fb

Is this on purpose, or is this a bug?

**Comment by kkirsche** [comment]
Crap. /me goes to yell at sublime text for not finding all my `:::before`'s when searched

**Comment by cvrebert** [comment]
Fixed by #17289.
