### ISSUE TITLE
btn-secondary-outline appears disabled

### ISSUE THREAD

**Issue by sconstantinides** [twbs/bootstrap#17286]
Sorry if it's been mentioned already, but the normal state of btn-secondary-outline looks disabled.

<img width="513" alt="screen shot 2015-08-24 at 12 26 44 pm" src="https://cloud.githubusercontent.com/assets/2643701/9449380/d6137062-4a67-11e5-9e79-1a87dfb7027c.png">

For reference: below are the current button text/border [contrast ratios](http://leaverou.github.io/contrast-ratio/):
- Primary: 4.6
- Secondary: 1.6
- Success: 2.5
- Warning: 1.9
- Danger: 4

**Comment by cvrebert** [comment]
CC: @patrickhlauke as this also touches on accessibility

**Comment by zacechola** [comment]
Those contrast ratios are against a _white_ background, but the button background is actually set to transparent in the mixin.

**Comment by patrickhlauke** [comment]
but then again, our very own examples in the docs are against white background...

not much that can be done here unless we make an assumption that most devs will use it against a light/white background, and darken those accordingly (which then makes them worse against any darker backgrounds) or we add a general note somewhere about devs needing to check their contrast ratios.

**Comment by kkirsche** [comment]
@patrickhlauke we could (though lot's of work) make unique colors for light or dark backgrounds and apply them via a mixin similar to http://thesassway.com/intermediate/dynamically-change-text-color-based-on-its-background-with-sass

**Comment by sconstantinides** [comment]
My thought would be to darken the secondary gray slightly to make its contrast more similar to the others.

Toggling light/dark colors may be more work than it's worth. And you would still have issues when someone chooses a background color similar to a button color.

**Comment by zacechola** [comment]
The buttons may not always be on the body as well, so using `$body-bg` might not be the most helpful. My vote would be to 1) Use `$gray-dark` instead of `$btn-secondary-border` to adjust the example contrast in the docs and 2) add an a11y callout.

**Comment by olvlvl** [comment]
Ironically the disabled button is more contrasted with `color: #373A3C` compared to `#CCC`.

**Comment by spdpiyush** [comment]
I Suggest The Darken The Secondary Button And Increase The Border - radius.

**Comment by mdo** [comment]
This is less of an issue with changes I made to the secondary button awhile back. More changes are coming to our grays in #21199, but there won't be any major changes to our overall styling for secondary buttons.
