### ISSUE TITLE
v4 - composer

### ISSUE THREAD

**Issue by andrewtch** [twbs/bootstrap#17290]
Hi, can you please push dev-v4-dev branch to composer so it's installable for early adopters? Thanks.

**Comment by cvrebert** [comment]
Any specifics on how we'd do that?

**Comment by kkirsche** [comment]
Most I can find at the moment is https://getcomposer.org/doc/05-repositories.md#packages

**Comment by cvrebert** [comment]
Manually sync'ed, and installed the GitHub service webhook, so it should be automatic going forward.

**Comment by andrewtch** [comment]
Yes, perfect )) Seems you really missed the webhook, thanks!
