### ISSUE TITLE
Docs -- Themes Marketing

### ISSUE THREAD

**Issue by sonyab** [twbs/bootstrap#17298]
Marketing Theme Documentation states:
 
    <link href="dist/toolkit.min.css" rel="stylesheet">

incorrect css file name / not part of the dist file

**Comment by cvrebert** [comment]
@sonyab I presume this is in reference to http://themes.getbootstrap.com/products/marketing ?

**Comment by sonyab** [comment]
http://bootstrap-themes.github.io/marketing/docs/# <http://bootstrap-themes.github.io/marketing/docs/#>

I recently purchased this theme and found what I believe is a typo in the documentation.



·.¸.·´¯`·.¸.·´¯`·.><(((º>

Sonya Boggs
+1 617.314.0895
sonya.bayarea@gmail.com <mailto:sonya.bayarea@gmail.com>
http://www.sonyaboggs.com <http://www.sonyaboggs.com/>

**Comment by cvrebert** [comment]
@mdo Where are we supposed to redirect folks who have feedback/questions about the themes?

**Comment by mdo** [comment]
Folks with bug reports or feature requests, and any other themes related support questions can email themes@getbootstrap.com :).
