### ISSUE TITLE
Tooltips no longer adjust their position to stay in the viewport

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap#17297]
v4: https://output.jsbin.com/zabazi/quiet
v3: https://output.jsbin.com/niketi/quiet

X-Ref: https://github.com/twbs/bootstrap/pull/17238#issuecomment-134399945

**Comment by fat** [comment]
@hnrch02  your js doesn't work in v4 :P

**Comment by fat** [comment]
fwiw, we definitely did drop the arrow placement stuff.

You can still do some tricky stuff with constraints…

something like this, won't allow the tip to leave the window… but it definitely wont be ~as~ nice with the arrow… but also i feel like we over engineered that tip / arrow before and as a result like almost all of the v3 issues were tooltip position related

```js
  $('.js-btn-overflow').tooltip({
    placement: "bottom",
    constraints: [
      {
        to: 'scrollParent',
        attachment: 'together',
        pin: true
      }
    ]
  })
```

**Comment by hnrch02** [comment]
> @hnrch02 your js doesn't work in v4 example :P

Fixed. Was caused by us now throwing an error when jQuery < v2 is used.

> something like this, won't allow the tip to leave the window… but it definitely wont be ~as~ nice with the arrow… but also i feel like we over engineered that tip / arrow before and as a result like almost all of the v3 issues were tooltip position related

100% agree. The question is do we decidedly drop this as the default? I feel like it's not used that often and one can solve this with constraints as you showed. Maybe this is more of a documentation issue?

ping @mdo @cvrebert

**Comment by mdo** [comment]
Yeah, I'm fine leaving this as a dropped feature for now.
