### ISSUE TITLE
Have custom events include the original event that caused them as a property

### ISSUE THREAD

**Issue by aureole82** [twbs/bootstrap#17306]
It's a common need but I'd like to demonstrate it a the tab extension:

Using a custom handler

    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        // all undefined: e.altKey, e.ctrlKey, e.shiftKey
    });

Here's the reason `bootstrap.js:2145`:

    var clickHandler = function (e) { // e.g. e.altKey == true, e.ctrlKey == false, e.shiftKey == true
        e.preventDefault()
        Plugin.call($(this), 'show')
    }

Do you mind to provide the orginal source event (here's the click event) as a property of the passed event inside my custom handler?

Thanks

**Comment by cvrebert** [comment]
Yes, this is planned. Quoting from #17021:

> * [ ] Have Bootstrap's custom events include the (e.g. click, keyboard) event that caused them as an `originalEvent` property: #15393

**Comment by aureole82** [comment]
Ok. I got it. It's a duplicate! Thanks for quick response.

**Comment by fat** [comment]
closing as dup
