### ISSUE TITLE
Reboot: why is @viewport manually vendor prefixed?

### ISSUE THREAD

**Issue by tomByrer** [twbs/bootstrap#17300]
I'm a little confused why Autoprefixer is a build requirement, but there are still [vendor-prefixes](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L49)?  Don't want to nit-pick, but not sure if an ancient version of Opera & other browsers need support...

**Comment by cvrebert** [comment]
In that particular case, I'm pretty sure it's future-proofing since so far only IE/Edge implements the relevant CSS standard: http://caniuse.com/#feat=css-deviceadaptation

**Comment by tomByrer** [comment]
IIRC Fx is dropping `-moz-` prefixes for new rules; they have a dev branch & use flags.
I can't find documentation for the `-webkit-` prefix, but possible since it is pre-blink addition.
Interesting footnote in [MDN's `@viewport`](https://developer.mozilla.org/en-US/docs/Web/CSS/%40viewport#Browser_compatibility) entry.

But I still think prefixe fixing belong in autoprefixer, & not main `.scss` code  :dancers:

**Comment by cvrebert** [comment]
> I can't find documentation for the `-webkit-` prefix

WebKit doesn't currently implement `@viewport` (see caniuse link).

**Comment by tomByrer** [comment]
Oh, thanks.

**Comment by mdo** [comment]
Dropped the unused and unsupported ones in de944e0.
