### ISSUE TITLE
Customizer Not Working

### ISSUE THREAD

**Issue by ewistrand** [twbs/bootstrap#17309]
I've tried several times to use the customizer and keep receiving the same error when compiling. 

Ruh roh! Problem parsing or compiling Less files.
Error: error evaluating function `red`: a.rgb is undefined
 // Customize the `:focus` state to imitate native WebKit styles.
 .form-control-focus();

Thanks in advance for your help!

**Comment by cvrebert** [comment]
The customizer can't work if you give it invalid input :smile: 
Most probably one of the variable values you set is invalid. Unfortunately, we don't have the manpower to personally help you track down which one it is. You can figure it out yourself by either looking at what variables are referenced (possibly indirectly) in the source code shown in the error message, or by only setting one more custom variable value at a time, retrying the download each time until it fails.
Or you can try asking community members on StackOverflow, IRC, or Slack: https://github.com/twbs/bootstrap/blob/master/README.md#community
Good luck!
