### ISSUE TITLE
tabs should support custom elements

### ISSUE THREAD

**Issue by jczerwinski** [twbs/bootstrap#17312]
Because [tab styles are defined as child -- and not descendant -- selectors](https://github.com/twbs/bootstrap/blob/master/less/navs.less#L78):
```css
.nav-tabs > li { ... }
```
Tabs that are injected via custom elements aren't styled correctly:
```html
<ul class="nav-tabs">
  <my-custom-tab-wrapper-element>
    <li>Hai Tab</li> <!-- injected template, not styled properly -->
  </my-custom-tab-wrapper-element>
</ul>
```
My thoughts on solutions, in order of preference:

1. Use a descendant selector: `.nav-tabs li {...}` - Is backwards compatible, and doesn't impose any additional requirements on custom elements. It doesn't seem likely to break anything -- is anyone nesting `<li>` within tabs?
2. Use a class to represent tabs: `.nav-tabs > .tab {...}` - Breaks existing tabs. Requires custom elements to express classes, which isn't great -- we might want to keep style rules within templates. But, doesn't risk issues with nested list items. I don't think it's really a big risk.

Thoughts?

**Comment by kkirsche** [comment]
@jczerwinski not sure I agree. To my knowledge, and I could be wrong, the only areas that really support components named in that way are third party frameworks such as Angular which offer other options for integrating components such as AngularStrap.

Is there a different method of creating custom components which I'm not aware of?

**Comment by jczerwinski** [comment]
@kkirsche I do happen to be running into this with Angular and UI-Bootstrap, but I don't think it's limited to this.

You're right that it's third-party libraries providing most of this functionality at the moment. Polymer and React would be other examples.

These frameworks also seem intended as a bridge to/wrapper around the [Custom Elements API](http://w3c.github.io/webcomponents/spec/custom/), which is natively supported in some of the more recent browser releases, so using frameworks to do this isn't strictly necessary.

I can see how this would be a slippery slope -- *many* other selectors could become less specific to accommodate similar use cases. In this case the risk seems pretty low, but maybe that's not true elsewhere. Button groups are another obvious example where this would happen: `<my-custom-button-wrapper>`... ad nauseum I'm sure.

Anyway, this isn't too important to me, so don't be afraid to reject. Could be I'm trying to use these things in a uniquely weird way. I get the feeling that this sort of thing will come up again, but I'm happy to wait and see. Keep it in mind, maybe some other requests fit the pattern.

**Comment by cvrebert** [comment]
This is fixed in upcoming Bootstrap v4, where the relevant selectors have already been changed to address both of your points: :smile: 
https://github.com/twbs/bootstrap/blob/210e2b8100e0a90e097cd98f1abd7c3bfdc72a8b/scss/_nav.scss#L49-L57

We aren't accepting significant changes into Bootstrap v3 anymore, since v4 is coming soon, so this is WontFix for v3.

**Comment by jczerwinski** [comment]
:+1:
