### ISSUE TITLE
Input Group - Sizing

### ISSUE THREAD

**Issue by cwolfenberger1** [twbs/bootstrap#17311]
As seen here - http://ibin.co/2DNMWhtcwFuN - the input group sizing is off on the largest size (using Chrome, Mozilla Firefox, and Internet Explorer 11 on Windows 7 64-bit).
Here's a link to the section - http://v4-alpha.getbootstrap.com/components/input-group/#sizing

**Comment by zacechola** [comment]
Yep. Dupe of #17035 which also has a fix in.

**Comment by cwolfenberger1** [comment]
Oh, I'm sorry! I did a quick search before posting this and didn't see that.

**Comment by TheSanto** [comment]
Awesome job guys.
