### ISSUE TITLE
v4 - No _custom.scss is provided

### ISSUE THREAD

**Issue by colin-marshall** [twbs/bootstrap#17322]
In the comments of `_variables.scss` there is this comment at the top:

```scss
// Copy settings from this file into the provided `_custom.scss` to override
```

I see no _custom.scss file provided in the v4-dev repo.

**Comment by kkirsche** [comment]
Duplicate of action item in #17021

item:
Consider implementing a _custom.sccss for easier, built-in variable overrides

**Comment by colin-marshall** [comment]
Ok thanks for pointing that out, my bad. Closing this issue.
