### ISSUE TITLE
collapse() calls toggle twice on initial call

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#17335]
When calling `.collapse('toggle');` on a collapsible the first time, it is toggled twice (i.e. shown and immediately hidden afterwards). However, one can see the issue only when having transitions disabled (as is the case in all our web tests), otherwise the first toggle is still in transition while the second one is triggered and the second one is therefore ignored.

The reason seems to be in the Collapse plugin:

    var data    = $this.data('bs.collapse')
    [...]
    if (!data) $this.data('bs.collapse', (data = new Collapse(this, options))) // toggle is called in Collapse ctor
    if (typeof option == 'string') data[option]() // toggles again

Possible fix: the ctor call to Collapse should overwrite the default toggle:true option to toggle:false.

**Comment by cvrebert** [comment]
It would be very helpful if you could post a JS Bin that demonstrates the problem.

**Comment by drauch** [comment]
http://jsbin.com/sayuquluva/edit?html,output

Depending on whether you execute the line `$.support.transition = false;` the state of the collapsible is either collapsed or expanded after the `.collapse('toggle')` call.

**Comment by cansozeri** [comment]
Same over here, I am creating dynamic collapse divs and after that function "show.bs.collapse" calls toggle twice, but if I reset Dom and refresh page it is working as expected ...

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by drauch** [comment]
Are you sure that the bug is no longer valid in v4?

**Comment by JeanCollas** [comment]
For future references:
I got the issue, actually the target did not have the `.collapse` class set. Adding it fixed the issue.

**Bad code:**

    <a href="#target" data-toggle="collapse">toggle</a>
    <div id="target">
        some content
    </div>

goes **after one click** to

    <a href="#target" data-toggle="collapse">toggle</a>
    <div id="target" class="collapse show">
        some content
    </div>

**Good code:**

    <a href="#target" data-toggle="collapse">toggle</a>
    <div id="target" class="collapse show">
        some content
    </div>
