### ISSUE TITLE
Internet Explorer 10 device width fix / Examples missing the css

### ISSUE THREAD

**Issue by mrmv** [twbs/bootstrap#17337]
[The docs state that:](http://getbootstrap.com/getting-started/#support-ie10-width)
 'As a heads up, we include this in all of Bootstrap's documentation and examples as a demonstration.'

I see the javascript (ie10-viewport-bug-workaround.js) is included in the examples, but the actuall css seems to be missing.

**Comment by cvrebert** [comment]
Are you referring to Bootstrap v3, or v4?

**Comment by mrmv** [comment]
V3

**Comment by cvrebert** [comment]
Thanks for reporting this.
