### ISSUE TITLE
Reeboot: iframes

### ISSUE THREAD

**Issue by viktor-yakubiv** [twbs/bootstrap#17345]
Add to bootstrap's reboot `iframe` styles refresh that clears borders.

Example from [team page](http://v4-alpha.getbootstrap.com/about/team/)
[![iframe example](http://ipic.su/img/img7/fs/kiss_1kb.1440608079.png)](http://v4-alpha.getbootstrap.com/about/team/)

**Comment by kkirsche** [comment]
@viktor-yakubiv That was fixed in #17190

**Comment by mdo** [comment]
Should we reset this for all iframes?

**Comment by viktor-yakubiv** [comment]
I think, yes. Iframes uses for including dynamic content, video from youtube, social buttons or maps and we always need to refresh default iframe borders.

**Comment by kkirsche** [comment]
I don't think so. `iframe` is generally used for inserting content from a third party and I believe it's that party's responsibility to provide the necessary code to ensure that their item displays as they expect. I believe YouTube is exception and items like ads, third party buttons (I.e. Facebook, Twitter, etc) are the main use.

**Comment by mdo** [comment]
Punting for now.
