### ISSUE TITLE
Update Holder.js

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#17354]
Notes:
1) Make sure the images show up when we use a percentage
~~2) See why there's a difference in the images' background-color (happens with current version too compared to v4-dev)~~

**Comment by XhmikosR** [comment]
@imsky: any ideas why v.2.8.2 fails when we use a percentage like `<img class="card-img-top" data-src="holder.js/100%x180/" alt="Card image cap">`?

**Comment by imsky** [comment]
i should have made it clearer in docs - because of various URI-encoding issues, percent signs have been replaced by `p`, so `100%x100%` is now `100px100p`. it's on my todo list to clarify this for 2.9.

**Comment by XhmikosR** [comment]
Ah, makes sense. I'll make the changes later but it might be worth
emphasizing it in docs.

**Comment by mdo** [comment]
Closing since #17373 was merged.
