### ISSUE TITLE
semantic grid system proposition, and separated responsive classes

### ISSUE THREAD

**Issue by tykayn** [twbs/bootstrap#17365]
how about using semantic class names aliases for the responsive grid system?
plus it would be great if the responsive part of the layout were in a separate class, so we would have less cases to specify in the css rendered.

(`.input-warning`, by combining `.input` and `.warning` for example, would lighten the DOM and the css output. an other example would be remplacing this:
`btn btn-xs btn-default-outline`
by this
`btn xs default outline`
)

so for the grid system:
added to the classical `.col-xs-6` we could use `.col-half` (6/12 = 1/2) and put `.xs` class separately.
same as `.col-xs-8` we could use `.col-four-sixth` (8/12 = 4/6)
 `.col-xs-8` we could use `.col-four-sixth` (8/12 = 4/6)
`.col-one-third` , `.col-three-fourth` , `.col-two-sixth` and so on for other proportions, but just until the sixths.

just suggesting

**Comment by zacechola** [comment]
:-1: That sort of chaining looks like it'll work in theory, but runs into practical issues when it comes to component scoping. @mdo did a talk on his class naming philosophy recently. It's worth a watch if you have a half hour: http://jqueryuk.com/2015/videos.php?s=mdo-ular-css

**Comment by abitdodgy** [comment]
@tykayn I don't see the benefit that `col-four-sixth` brings over `col-xs-8`. The grid system is known to be 12 columns, which is a standard in all popular CSS frameworks, and using numbers is more obvious, and shorter.

**Comment by cvrebert** [comment]
> an other example would be replacing this:
> `btn btn-xs btn-default-outline`
> by this
> `btn xs default outline`

Not gonna happen. The prefixing is an intentionally chosen naming scheme. See http://markdotto.com/2012/02/16/scope-css-classes-with-prefixes/ for the rationale.

> so for the grid system:
added to the classical .col-xs-6 we could use .col-half (6/12 = 1/2) and put .xs class separately.
same as .col-xs-8 we could use .col-four-sixth (8/12 = 4/6)

There is some talk of potentially tweaking the naming to allow multiple grids (e.g. 5-column, 12-column) to coexist better, but I don't believe the "spelled-out-numbers" style you're suggesting is currently on the table. It's also more annoying both to type out manually or to generate programmatically.
