### ISSUE TITLE
bootstrap gird system

### ISSUE THREAD

**Issue by SCORPIO12** [twbs/bootstrap#17363]
HI 

i try to create grid with the following code 

![dsf](https://cloud.githubusercontent.com/assets/13807459/9517144/1ad14f88-4cc7-11e5-81f3-3eac287b29e8.png)

butt when i run it it shows me like this
![untitled](https://cloud.githubusercontent.com/assets/13807459/9517033/3024b5c4-4cc6-11e5-8902-38a0a1ba57ce.png)
 .. 
where as i follow this bootstrap tutorial and it shows me like with same code ...
![untitledd](https://cloud.githubusercontent.com/assets/13807459/9517057/613d7ce0-4cc6-11e5-9798-30f12b06f981.png)

how to resolve this

**Comment by prisis** [comment]
The bootstrap css is missing ;), that why it dont work

**Comment by SCORPIO12** [comment]
oOps .. thanku prisis

**Comment by cvrebert** [comment]
Please direct future personal support requests to StackOverflow instead of this issue tracker. Thanks!
