### ISSUE TITLE
Proposal: Drop jQuery dependency.

### ISSUE THREAD

**Issue by omeid** [twbs/bootstrap#17378]
For upcoming version 4, with no support for even IE8, there is little inconsistencies in Javascript APIs used by Bootstrap Javascript components, so why not drop a dependency at the cost of little to no overhead? I am happy to contribute.

**Comment by mdo** [comment]
Not happening in v4, sorry. Already too far down the path with v4 to remove it now.

**Comment by omeid** [comment]
I don't see how this is too late, how Bootstrap implements any feature should never impact users anyways.

Besides, most of work has been already done at [bootstrap.native](https://github.com/thednp/bootstrap.native).

But maybe at least for `4.1`?

**Comment by mdo** [comment]
> I don't see how this is too late, how Bootstrap implements any feature should never impact users anyways.

We've spent over a year working on v4 :D. Completely rewriting the plugins for a minor version isn't practical or doable either.

**Comment by omeid** [comment]
Fair enough. :)

**Comment by cvrebert** [comment]
Duplicate of #15068.
