### ISSUE TITLE
ایران

### ISSUE THREAD

**Issue by ali-kazemi** [twbs/bootstrap#17377]
نصب زبان فارسی

**Comment by ali-kazemi** [comment]
نصب زبان فارسی در تنضیمات برنامه های کاربردی

**Comment by cvrebert** [comment]
Sorry, but we are unable to provide assistance in Farsi.

**Comment by ali-kazemi** [comment]
Alikazemiaalma@gmail.com
در تاریخ ۲۸ اوت ۲۰۱۵ ۹:۲۵، "Chris Rebert" <notifications@github.com> نوشت:
