### ISSUE TITLE
_card.scss: variables in head and not moved to _variables.scss

### ISSUE THREAD

**Issue by kscherling** [twbs/bootstrap#17372]
Looks like the variables never got removed from the `_card.scss` partial and into the global `_variables.scss` file.  Probably an oversight but keep having to post special instructions  for post bower install for team to fix card border issue #17210.

**Comment by petetnt** [comment]
#17069 fixed this

**Comment by kscherling** [comment]
Oh awesome.  Thanks!  Any idea when the next tick of alpha with these updates will propagate to bower?

**Comment by petetnt** [comment]
Unsure about that, but meanwhile you could try installing it straight from the `v4-dev´ instead via
```
bower install twbs/bootstrap#v4-dev --save
```
:ok_hand:

**Comment by kscherling** [comment]
Word.  Thanks again!
