### ISSUE TITLE
Dropdown menu inside scrollable div is cropped

### ISSUE THREAD

**Issue by dfsdfsdfs** [twbs/bootstrap#17383]
http://s14.postimg.org/3v5ecy0qp/testbutton.png

If the parent button is inside a div with scrollbar and near the visible bottom, then the menu shows cropped.

**Comment by cvrebert** [comment]
This is covered by the following bullet point in #17021:
> * Consider removing dropdown menus from normal document flow (perhaps with `container` option) to prevent a number of parent cropping issues (due to `overflow`)

**Comment by mdo** [comment]
I know this issue is tagged for v4, but this seems to be in reference to v3. Also, we've got an open bullet point on using the positioning library for dropdowns and just haven't gotten around to it yet. Closing for now given that.
