### ISSUE TITLE
Why no full screen modal?

### ISSUE THREAD

**Issue by dfsdfsdfs** [twbs/bootstrap#17381]
Bootstrap is mobile first, so how to make a large modal in desktop show as full screen modal in mobile to give it the feeling of a native app? I'm surprised this isn't an out of the box feature.

**Comment by dfsdfsdfs** [comment]
I know there's a modal-fullscreen class, but this will apply to both mobile and desktop. Can't have a mobile only class without hacking?

**Comment by cvrebert** [comment]
> I know there's a modal-fullscreen class

No, there's no such class in Bootstrap.

**Comment by Gupocca** [comment]
Perhaps you are thinking of @noreiller's [`.modal-fullscreen`](https://github.com/noreiller/bootstrap-modal-carousel/blob/master/src/less/modal-fullscreen.less)?

**Comment by dfsdfsdfs** [comment]
Yes, my bad. Sorry.

**Comment by mdo** [comment]
I'm unsure what you're asking for—you want a fullscreen modal on mobile with a constrained width on desktop? If so, I'm pretty sure that's how our modal sizes work today.

**Comment by mdo** [comment]
Closing out until we hear more.

**Comment by dfsdfsdfs** [comment]
I'm sure you understood me. There's no way to make a modal full screen unless you use a third party addon or your own solution, plus the current modal size on mobile must be something around 90% width and 50% height. In fact there's no difference between modal-lg and modal-sm on mobile.

**Comment by dfsdfsdfs** [comment]
I'm just saying full screen modal class for mobile would be interesting as there's no way you can insert the content of a modal-lg inside a half-height almost-full-width mobile modal, plus this tool would be useful for bootstrap to make web apps look like native mobile apps, in the sense that you don't need to scroll up or down nor left or right and your modal covers the entire screen, and that same modal can then be reused for desktop version as a floating non-fullscreen modal. Let me know if I haven't explained myself clearly.

**Comment by mdo** [comment]
I wouldn't be opposed to seeing something in a PR for this, but I've no plans to implement it myself. Earliest we could maybe look at this would be 4.1 or 4.2.
