### ISSUE TITLE
Mismatching element sizes in input-group-lg on site docs

### ISSUE THREAD

**Issue by filipesilva** [twbs/bootstrap#17386]
I am using chrome44, win10 desktop. Issue happened with varying screen sizes. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/4172079/9546729/06943af0-4d8d-11e5-9e9f-91b7eee66403.png)

**Comment by kkirsche** [comment]
Duplicate of #17035

**Comment by filipesilva** [comment]
Right you are, my bad!
