### ISSUE TITLE
accordion always pass value of first collapsed in window Modal - WHY ?? Don't undrestand

### ISSUE THREAD

**Issue by alfo77italy** [twbs/bootstrap#17382]
<!DOCTYPE html>
<html lang="en">
<head>   
    <title></title>	
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
	<link href="css/item_hover.css" rel="stylesheet">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="fonts/stylesheet.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">    
    <link rel="shortcut icon" href="images/ico/favicon.ico">    
</head>
<body>
   <div class="container">
     	<h1 class="text-center" style="background-color:#000">RUN</h1>
        <div class="row">
            <div id="list" class="col-xs-12 col-sm-12">                
                <div id="load"><img src="images/preloader-w8-cycle-black.gif" height="100px" width="100px"/></div>
            </div>                
        </div>            
   </div>
    
    <script src="js/jquery-1.11.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/jquery.isotope.min.js"></script>
    <script src="js/main.js"></script>
    <script src="js/wow.min.js"></script>

	<script type="text/javascript">		
	
	var xml;
	$(document).ready(function(){		
			
			$.ajax({
            type: "GET",
            url: "run.xml",
            dataType: "xml",
            success: xmlParser			
				});			
				
			function xmlParser(data) {
				xml = data;				
				$('#load').fadeOut();				
				$("#list").append('<div class="panel-group" id="accordion1"><div id="listAcc" class="panel panel-default"></div></div>');
				
				$(xml).find("Prodotti").each(function () {
					nome = $(this).attr("nome");
					var img = $(this).find("img").text();						
					var data = $(this).find("data").text();							
					
					$("#listAcc").append('<div class="modal fade" id="myModal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">MODULE</h4></div><div class="modal-body"><form class="form-inline" role="form"><div class="form-group"><label for="gara">RUN:</label><input type="text" class="form-control" id="gara" name="gara" placeholder="RUN" value="' + nome + '" readonly /><label for="data">DATA:</label><input type="text" class="form-control" id="data" placeholder="DATA" value="' + data + '" readonly /><div class="divider"><hr></div></div></form></div><div class="modal-footer"><button id="inviaPrenota" type="button" class="btn btn-success">Conferma</button><button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button></div></div></div></div><div class="panel-heading"><h3 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#'+ id +'">Circuito: <strong>'+ nome +'</strong> - Data: <strong>' + data + '</strong><i class="fa fa-angle-right pull-right"></i></a></h3></div><div id="'+ id +'" class="panel-collapse collapse"><div class="panel-body"><div class="col-xs-12 col-sm-6 col-md-6"><h4>Circuito: <input type="text" id="no1" name="no1" value="' + nome + '" readonly /></h4><img src="' + img + '" height="200px" width="200px" /><p><b>Data:</b> ' + data + '</p><br /><button id="prenota" type="button" class="btn btn-info" data-toggle="modal" data-target="#BtnPrenota">Prenota</button></div></div></div><br />'); 				
						$("#listAcc .panel-heading").mouseover(function(e) {            
							e.preventDefault;							
							$(this).addClass('active');										
						});
						
						$("#listAcc .panel-heading").mouseout(function(e) {            
							e.preventDefault;
							$(this).removeClass('active');		
						});	
						
						$("[data-target='#BtnPrenota']").on('click', function(e) {			
							e.preventDefault;
							$("#myModal").modal({show: true});							
						});
						
					});	
			};	
	});
	
	</script>
    
</body>
</html>

**Comment by cvrebert** [comment]
Please direct personal support questions to StackOverflow, IRC, or Slack, instead of this bug tracker. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
Thanks!
