### ISSUE TITLE
carousel issue

### ISSUE THREAD

**Issue by schel4ok** [twbs/bootstrap#17396]
I don't know if my issue is correct one, but if you check example here http://109.120.184.51/blog/carousel.html

You will see that slides rotate to the right continuously one after the other.
And when they rotates to the left there is no continuous carousel. Active slide dissappear completely and then left slide moving.
It is not beautiful. Is it possible to fix it?

**Comment by cvrebert** [comment]
As mentioned in https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker , please direct personal support requests to StackOverflow, IRC, or Slack instead of this bug tracker. Thanks!
