### ISSUE TITLE
Support tables in cards

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#17395]
With Bootstrap 3, I used to quiet often put tables in panels as shown in the v3 documentation (without the panel-body class). However, in the v4-replacement for panels - cards - doing so does not give the expected result. The table heading still has a line on top and at the bottom, there is a white margin between the table's end and card's end.

**Comment by mdo** [comment]
I really don't want to get into supporting tables in cards—it's such a shitshow and leads to so much extra CSS for such little gain. Take a look at the panels in v3 for an example of what I mean. So many edge cases, `>` selectors, etc.

For now, going to punt.

**Comment by heruan** [comment]
I'd love to have a seamless design for tables in cards. I know tables are too often misused and abused in cases where a list would suffice and I understand the downside of extra CSS—BUT in my opinion the gain isn't that little: appropriate tables are an important semantic element and cards are so practical in v4 I think the combination of them would be a great feature.

**Comment by sebastiaanluca** [comment]
Placing the table directly in the card div seems to produce an acceptable result. Though that's only my first impression.

```html
<div class="card">
    <!--<div class="card-block">-->
        
        <table class="table table-hover">
            ...
        </table>
    
    <!--</div>-->
</div>
```

**Comment by browner12** [comment]
i've been putting them in there, and simply adding `mb-0` to the table, and that works well enough.

**Comment by fulldecent** [comment]
In alpha 6, tables look OK in a card. To make it work I need to first remove the header row.

**Comment by thebobhudgins** [comment]
Just put .table inside .card
then put .mb-0 into .table
and put .border-0 into .card

```
<div class="card border-0">
    <!--<div class="card-block">-->
        
        <table class="table table-bordered mb-0">
            ...
        </table>
    
    <!--</div>-->
</div>
```

**Comment by stevenjamesfrank** [comment]
Can someone confirm that status of this (specifically, use of tables inside cards)?

I would term the status as "you can do it but it's not pretty or fully functioned". and I'm good with that, I just want to make sure I understand the state of affairs (v4-beta) and whether or not I should expect more.

Additionally, my plan is to use the grid (.row and .col) inside my cards for tabular data, is that the officially preferred way to do this?

**Comment by jlozoya** [comment]
In bootstrap 4.0.0-alpha.6 table-responsive was working fine, so I copy the css of table-responsive of that version then I put it in my project and update bootstrap to 4.0.0-beta
```
.app-table-responsive {
  display: block;
  width: 100%;
  overflow-x: auto;
  -ms-overflow-style: -ms-autohiding-scrollbar;
}

.app-table-responsive.table-bordered {
  border: 0;
}
<div class="app-table-responsive">
    <table class="table table-hover">
    ...
    </table>
</div>
```

**Comment by codigoestudio** [comment]
<div class="card-body" style="padding: 0;">
;)

**Comment by stevebauman** [comment]
There's a padding helper class you can use for this that's included in bootstrap named `p-0` (for `padding: none`).

If you apply it to the `card-body`, then it mirrors the functionality of Bootstrap 3 (at least in my experience):

```html
<div class='card'>
  <div class="card-body p-0"> <!-- Here -->
    <div class="table-responsive">
      <table class="table table-hover">
      ...
      </table>
    </div>
  </div>
</div>
```

**Comment by fulldecent** [comment]
The recommendation from @stevebauman did not work for me:

<img width="1707" alt="screen shot 2018-02-23 at 2 08 07 pm" src="https://user-images.githubusercontent.com/382183/36611918-0be1e69a-18a3-11e8-9bac-65ff87417153.png">

**Comment by kjdion84** [comment]
This following works.

HTML:

    <div class="card">
        <div class="card-header">Category</div>
        <div class="card-body p-0">
            <table class="table table-hover table-responsive mb-0">
                <tbody>
                <tr>
                    <td class="align-middle">Content</td>
                    <td class="align-middle">Content</td>
                    <td class="align-middle">Content</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

Optional CSS to remove top border from first `td`:

	.card-body .table tr:first-child td {
	    border-top: 0;
	}

**Comment by swrobel** [comment]
Here's an open PR for this feature: https://github.com/twbs/bootstrap/pull/25193

Out of curiosity, why do tables have `margin-bottom`? It seems like it's been in the source forever, so I guess that's how it's always been, and it can't be changed, yada yada, but it still makes me morbidly curious...

**Comment by philipnewcomer** [comment]
Until support is added natively in Bootstrap 4, I've published an NPM package containing CSS to properly render tables inside of cards: https://www.npmjs.com/package/bootstrap4-card-tables

**Comment by cbranje** [comment]
I don't understand the issue? I put tables in card all the time. Am I missing something?

**Comment by jlozoya** [comment]
@cbranje Was an issue about a specific problem with the responsive tables on a old version of bootstrap if I remember the 4 alpha version

**Comment by krisleech** [comment]
I need to add `p-0` to the `.card-body`:

```html
<div class="card">
  <div class="card-header">Not invoiced</div>
  <div class="card-body p-0">
    <table class="table">
```

**Comment by dangquochoi2007** [comment]
@krisleech 
Thanks . It's working

**Comment by othyn** [comment]
This style looks perfect to me:

```html
...
<div class="card">
    <div class="card-header border-0">
        My Card Header
    </div>
    <table class="table table-hover mb-0">
    ...
```

**Comment by florianlacreuse** [comment]
Guys, the tricky part is to make it look good with `.table-bordered` on the `table` while keeping the borders from the `card` itself. Need to deal with `rowspan` and `colspan` too.

**Comment by rebecca-xie-au** [comment]
> Guys, the tricky part is to make it look good with `.table-bordered` on the `table` while keeping the borders from the `card` itself. Need to deal with `rowspan` and `colspan` too.

that's true, rowspan or colspan will affect tr:first-child selector
