### ISSUE TITLE
Small border in final row in tables when placed in panel

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#17391]
Today, I noticed an issue where placing a table in a panel will cause in the first and last cell of the last row of that table, to appear a small white border on the right hand side and the bottom. Here's the test ase: http://jsbin.com/widodifozi/1/edit?html,output. I've tested this in Edge.

**Comment by cvrebert** [comment]
Same problem in Firefox. There's a bit of white in the lower-left and lower-right corners of the table when hovering over the indicated row.

**Comment by mdo** [comment]
Closing as a pixel rounding browser-specific problem, and a won't fix on our end.
