### ISSUE TITLE
v4 - Use right rem size for xl grid

### ISSUE THREAD

**Issue by iDuuck** [twbs/bootstrap#17390]
There is a fail in the grid configuration. 

`_variables.scss` says that `72.25rem` are `1140px`,but `71.25rem` are `1140px` when using a root size of `16px`.

But if [this issue](#17070) should be fixed, it's unnecessary, because it will be hardcoded.

**Comment by mdo** [comment]
Will be fixed when we revamp the media queries and what not in #17403.
