### ISSUE TITLE
v3.3.5 compilation from source > panel and pagination styles missing

### ISSUE THREAD

**Issue by senritsu** [twbs/bootstrap#17407]
Using the source .zip from the website, when compiling `bootstrap.less` with the included grunt task or with any other less compiler, neither `.panel` nor `.pagination` styles are included in the output `bootstrap.css`.

Running a diff on the generated `bootstrap.css` against the one included with the download (in the dist folder) shows that there are 4 differences, 2 from the sections that include `.panel` and `.pagination` as well as all variant styles, and 2 from the corresponding clearfixes.

Subsequent comparison of `panels.less` and `pagination.less` files with the respective `mixins/panels.less` and `mixins/pagination.less` revealed that they are the same, and apparently the correct `.less` files in the bootstrap source folder were erroneously overwritten with the mixin files.

**Comment by mdo** [comment]
The contents of the v3.3.5 download doesn't show those stylesheets—the regular `panels` and `pagination` files, and their mixins—to be the same. Are you sure these are pulled from our site and not being modified some other way?

**Comment by senritsu** [comment]
Yes, definitely downloaded from

http://getbootstrap.com/getting-started/

or to be more precise, using the source code link that points to

https://github.com/twbs/bootstrap/archive/v3.3.5.zip

First download was a few weeks ago, and i downloaded it again 2 days ago to diff the compiled `.css` files. 

Downloading it again now, i can indeed confirm the issue is apparently fixed. Maybe someone updated the .zip already?

**Comment by mdo** [comment]
> Downloading it again now, i can indeed confirm the issue is apparently fixed. Maybe someone updated the .zip already?

Definitely hasn't been touched—only way to do that is to delete and republish the entire release and Git tag. Either way though, happy it's resolved! <3
