### ISSUE TITLE
Confusing display headings

### ISSUE THREAD

**Issue by aleritty** [twbs/bootstrap#17412]
The way display headings are structured, IMHO is counterintuitive, because normal headings are "size descendant" (h1 -> bigger, h6 -> smaller).

With display headings you inverted this behaviour (display-1 -> smaller, display-4 -> bigger).

This can lead to confusion, maybe a good solution can be following "original" heading behaviour.

Also, maybe you can add a display-5 and display-6 class, just to keep consistent.

Just and advice, maybe this is made voluntarily.

**Comment by ChaseGiunta** [comment]
I can see how this could be counterintuitive. Another way to avoid confusion would be to use `display-sm` `display-md` `display-lg` `display-xlg` or something like that, instead.

**Comment by mdo** [comment]
I dig flipping it around.

**Comment by mdo** [comment]
Fixed in 29c3edd.
