### ISSUE TITLE
v4 radio and checkbox in Android v4.4.2 browser

### ISSUE THREAD

**Issue by KOSNOWMAN** [twbs/bootstrap#17416]
I'm trying to apply bootstrap v4 in my project.
but I can't touch the custom radio or checkbox in my mobile phone.
The example in v4 document-components-Forms-Custom Forms-Checkboxs and radios have also same problem.
My phone is a Samsung galaxy note2 .
What is the problem?

**Comment by cvrebert** [comment]
@KOSNOWMAN:
* What version of Android?
* Are you using Chrome or the Android Browser? What version?

**Comment by KOSNOWMAN** [comment]
My Android is v 4.4.2 and the model is a SHV-E250S using Korean.
I'm using a default brower, SBrowser(?) by Samsung not Chrome.

**Comment by cvrebert** [comment]
We don't support that particular platform; see http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#mobile-devices
CC: @mdo in case he wishes to still look into this

**Comment by KOSNOWMAN** [comment]
Hmm... First, thank you your fast answer.
I checked your link, supporting mobile device.
But I don't know exactly what version of browser I have.
My browser is a default program in Samsung mobile.
I think it is based on Chromium and there are many users in same situation especially in Korea.
