### ISSUE TITLE
camelCase for ids and hyphens for class names

### ISSUE THREAD

**Issue by dandv** [twbs/bootstrap#17417]
I've noticed in the [forms example](http://v4-alpha.getbootstrap.com/components/forms/) that ids use `camelCase`, while classes use `dash-names`.

Since the [consensus seems to be on using hyphens for both ids and class names](http://stackoverflow.com/questions/7560813/why-are-dashes-preferred-for-css-selectors-html-attributes), I was wondering if there are some Bootstrap-specific aspects that have led to this decision, and whether this is a guideline for Bootstrap projects.

**Comment by cvrebert** [comment]
I'm reasonably sure we do that so as to help avoid any confusion that those names are somehow part of Bootstrap itself.

**Comment by mdo** [comment]
We try to limit our IDs and make them stand out, thus the camelCase. Classes and everything else though should be dashes.
