### ISSUE TITLE
Docs v3 - missing semicolons in almost every js example script

### ISSUE THREAD

**Issue by 7rust** [twbs/bootstrap#17415]
The javascript section of the docs of V3 is missing semicolons in almost every jquery script, see: http://getbootstrap.com/javascript/#transitions

**Comment by MichaelRushton** [comment]
They're not required.

**Comment by mdo** [comment]
Yup, most of our JS doesn't use semicolons.

**Comment by cvrebert** [comment]
Approximate duplicate of #3057.
I personally don't like it either, but it's Jacob's house style and not currently open to reconsideration.
