### ISSUE TITLE
v4 On the fly compiling of Sass

### ISSUE THREAD

**Issue by mitcheal** [twbs/bootstrap#17424]
Are there any plans to have a js compiler option to render Sass files on the fly in BS4?  Having to rely on a local compiler seems to counter the speed and value of Sass.  When going across various hosting environments and coding in live test cases,  it would be nice to have the /option/ to render Sass without access to the command line.

**Comment by glebm** [comment]
You could use sass.js: https://github.com/medialize/sass.js/

**Comment by cvrebert** [comment]
Nope, we have no plans to bring back the Customizer. It's highly likely that some community members will create better third-party customization webapps themselves once there's a stable v4 release though.

**Comment by mitcheal** [comment]
I understand, as an intermediate front-end developer who is trying to figure out the best way to work Sass into my work flow, the process to leverage Sass seems over kill to get going.  You just want to edit a file and be done, without hassle of compiling.   And a lot of times a simple find and replace seems to still work wonders.   I get the need to write less code from the core framework point of view, but i'm wondering the styling barriers secondary developers are going to have.

**Comment by glebm** [comment]
@mitcheal If uncomfortable with the command line, try using something like http://koala-app.com/.
