### ISSUE TITLE
Request: Drop utility classes in favor of Atomic OOBEMITSCSS or CSS Modules

### ISSUE THREAD

**Issue by sbussard** [twbs/bootstrap#17421]
Firstly, great job on Bootstrap 4! 

It would be really super fantastic to see bootstrap also move beyond the use of utility classes to a solution that flexibly maps styles to markup. There are a couple solutions available for doing so 

https://css-tricks.com/atomic-oobemitscss/
https://github.com/css-modules/css-modules

**Comment by mdo** [comment]
We'll be sticking with what we have today for v4. Too late to change to anything else.
