### ISSUE TITLE
list-group has double border if last element on card (v4)

### ISSUE THREAD

**Issue by filipesilva** [twbs/bootstrap#17431]
~~I've added a box shadow to cards via the following css~~
~~.card {
  box-shadow: 0 0.125em lightgrey;
}~~

If my last element is a `list-group list-group-flush` then it looks like there's a second border.

![image](https://cloud.githubusercontent.com/assets/4172079/9621040/9f1b4d42-5119-11e5-8809-4cabe655d97b.png)

Whereas if the last element on a card is something else, like an empty `card-block`, it looks fine.

![image](https://cloud.githubusercontent.com/assets/4172079/9621053/be8a4426-5119-11e5-97a1-5cdadedc0f3c.png)

**Comment by cvrebert** [comment]
If this doesn't happen without your custom CSS, then it's a bug in your CSS, not in Bootstrap.
Support questions related to custom CSS don't belong on this issue tracker; see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by Gupocca** [comment]
It appears to occur independently of the `box-shadow` addition: https://jsfiddle.net/orheqwk0/1/

![border](https://cloud.githubusercontent.com/assets/567038/9621639/d6f85a02-50dd-11e5-889b-e9dbea284267.png)

**Comment by filipesilva** [comment]
You're absolutely right about the custom css bit. I'm sorry, I should have explained better - I mentioned it because that's when the issue became obvious to me. 

I should have taken the shadow off and added screenshots without it.

**Comment by mdo** [comment]
Fixed with a22d2fb.
