### ISSUE TITLE
Double border on left-aligned segmented buttons (v4)

### ISSUE THREAD

**Issue by filipesilva** [twbs/bootstrap#17438]
In the bootstrap 4 docs, components -> input groups page, segmented buttons section (http://v4-alpha.getbootstrap.com/components/input-group/#segmented-buttons ) the example looks like this on chrome:

![image](https://cloud.githubusercontent.com/assets/4172079/9628297/d2bd5260-5161-11e5-9478-b1136d5e2184.png)

![image](https://cloud.githubusercontent.com/assets/4172079/9628312/e1e11312-5161-11e5-8ca2-3341d2063d7c.png)

The left aligned segmented buttons appears to have a double border. Upon zooming in it seemed to disappear though.

**Comment by cvrebert** [comment]
v3 equivalent: #14237

**Comment by filipesilva** [comment]
Want me to close this one? The issue you referenced mentions this should be reviewed in v4.

**Comment by cvrebert** [comment]
This one can be the v4 review :smile:

**Comment by filipesilva** [comment]
:+1:

**Comment by cvrebert** [comment]
Relevant Chrome bug: https://code.google.com/p/chromium/issues/detail?id=534750

**Comment by cvrebert** [comment]
Seems to be fixed in Chrome Canary 47.0.2517.0 !

**Comment by cvrebert** [comment]
Seems to be broken again as of Chrome Canary 48.0.2530.0 :disappointed:
