### ISSUE TITLE
Add a navbar example that uses <div> instead of <ul>

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17439]
I hope we can agree that v3's requirement of using a `ul.navbar-nav` for nav links ended up being too restrictive and thus annoying. It complicates mixing other widgets (e.g. buttons, inputs) in with nav links, among other problems.
Everything ought to use classes now, but it'd be good to include an example without a `ul` so as to both prove things work without `ul`s and demonstrate the markup-independence to readers.
CC: @mdo

**Comment by mdo** [comment]
Tackled in e61eae4 I believe.

**Comment by cvrebert** [comment]
<3
