### ISSUE TITLE
Documentation references alert-error style which no longer exists

### ISSUE THREAD

**Issue by baus** [twbs/bootstrap#17444]
alert-error style is now alert-danger. Docs should be updated to reference alert-danger.

**Comment by kkirsche** [comment]
Where is this?

<img width="868" alt="screen shot 2015-09-02 at 10 40 35 am" src="https://cloud.githubusercontent.com/assets/947110/9639095/121951b4-515f-11e5-9dc0-19fe4fa363ff.png">

**Comment by baus** [comment]
My fault. I must have been looking at an old version of the documentation.
