### ISSUE TITLE
Compiled and minified CSS and JavaScript

### ISSUE THREAD

**Issue by henrywright** [twbs/bootstrap#17442]
Hey guys.

Any chance you can make the compiled and minified CSS and JavaScript available?

Ref: http://v4-alpha.getbootstrap.com/getting-started/download/

**Comment by kkirsche** [comment]
@henrywright these are available via Github:
https://github.com/twbs/bootstrap/tree/v4-dev/dist

**Comment by henrywright** [comment]
Great, thanks.

**Comment by mdo** [comment]
We'll hopefully have them linked in the docs for Alpha 2, fyi.
