### ISSUE TITLE
Rounded buttons

### ISSUE THREAD

**Issue by asnoba** [twbs/bootstrap#17458]
Hi,

Maybe a rounded button modifier class could be a nice addition to the existing button lineup in v4?

```
.btn-rounded {
  border-radius: 999em;
}
```

Of course they need a little more work if they should be available for button groups and dropdowns etc.

Here's a demo: http://codepen.io/asnoba/pen/XmJXKb

**Comment by cvrebert** [comment]
`rounded` could be confusing given the [`$enable-rounded`](http://v4-alpha.getbootstrap.com/getting-started/options/) variable, which does something a bit different. Perhaps `.btn-pill`? Just throwing it out there.

**Comment by zullkay** [comment]
Delete all css

**Comment by zullkay** [comment]
.Btn-pill

**Comment by mdo** [comment]
We won't be adding that to the core—seems like a perfect modifier or extension for folks to make on their own.

**Comment by asnoba** [comment]
Great, @cvrebert. I'll use `.btn-pill`instead of `btn-rounded`in my own projects. Fair enough, @mdo :)

**Comment by tarkhov** [comment]
Implemented here - https://tarkhov.github.io/postboot/#button-pill
