### ISSUE TITLE
v4 - Horizontal Alignment (justify-content) with FlexBox.

### ISSUE THREAD

**Issue by joedajigalo** [twbs/bootstrap#17463]
Possible to add a feature/classes for `justify-content`?

Ran into this when on smaller screens using flexbox - the columns would align to the left by default. Would be nice for on smaller screens, a class added to the row will determine the layout of the columns

Suggested addition: 
`justify-content: flex-start | flex-end | center | space-between | space-around`

Not sure of naming convention:
`.row-**-content-start         { justify-content: flex-start; }`
`.row-**-content-end          { justify-content: flex-end; }`
`.row-**-content-center      { justify-content: center; }`
`.row-**-content-between  { justify-content: flex-between; }`
`.row-**-content-around     { justify-content: flex-around; }`

**Caveat** - Although I did realize if you use `justify-content: center`, then there will be no need to add any offset classes since the columns will be centered automagically.

If this is approved and you can give me the naming convention you prefer - I can make a pull request.

Thanks.

**Comment by mdo** [comment]
Added this in #19099.
