### ISSUE TITLE
Flexbox for overall page layout

### ISSUE THREAD

**Issue by mmjaeger** [twbs/bootstrap#17464]
Hello
I stumbled over this article and I was wondering what you guys' stand is on this: https://jakearchibald.com/2014/dont-use-flexbox-for-page-layout/

Would it make sense to have some sort of parameter that would allow to enable flex overall but use a regular gird for the overall page layout - I guess there could be some sort of argument passed to the mixins that would allow to override $enable-flex?

**Comment by mdo** [comment]
That article is a bit out of date (over a year old) and talks more of grid layout over flex. Mixing the regular and flex-based grids sounds like a recipe for disaster (in debugging, differing browser support, extraneous CSS, etc). Pick one and use it throughout.
