### ISSUE TITLE
SSL error on https://www.bootstrapcdn.com/

### ISSUE THREAD

**Issue by hubdotcom** [twbs/bootstrap#17472]
![screenshot 2015-09-04 12 11 39](https://cloud.githubusercontent.com/assets/5274747/9681425/3108b178-52fe-11e5-97ab-f8d34edea933.png)

**Comment by MrGeneric** [comment]
I think the best bet would to tweet the guys listed as maintainers on that page.

**Comment by patrickhlauke** [comment]
Indeed. https://github.com/MaxCDN/bootstrap-cdn/

**Comment by hubdotcom** [comment]
Perhaps the reference to the bootstrapcdn.com should be without https?
http://getbootstrap.com/getting-started/#download 
```Just use these Bootstrap CDN links. ```

**Comment by patrickhlauke** [comment]
FWIW https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js etc do not give me any certificate warnings (note the maxcdn bit, rather than www)

**Comment by hubdotcom** [comment]
Thanks Patrick, the team is addressing now https://github.com/MaxCDN/bootstrap-cdn/issues/574

**Comment by patrickhlauke** [comment]
:+1:

**Comment by jdorfman** [comment]
This has been resolved: https://github.com/MaxCDN/bootstrap-cdn/issues/574

FTR: This only affected the marketing site, not the CDN.  Thanks
