### ISSUE TITLE
Use data: URLs instead of Holder.js for placeholder images

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17478]
Refs #17373.

**Comment by imsky** [comment]
i'm currently writing an alternative, text-only, SVG engine for Holder. the intent is to make CLI and programmatic use easier, so Holder could be leveraged here to embed the data URIs as the docs are built. it'd reduce potential confusion and keep the source images declarative.

let me know what you think

**Comment by cvrebert** [comment]
> Holder could be leveraged here to embed the data URIs as the docs are built.

@imsky Not sure what you mean by this.

**Comment by imsky** [comment]
Source doc:
```
<img src="holder.js/200x150">
```

Grunt builds the docs, with Holder, which transforms the above (at build time) into:
```html
<img src="data:image/svg+xml;charset=UTF-8,...">
```

**Comment by cvrebert** [comment]
Jekyll builds the docs at present. Good luck integrating with Ruby :-)

**Comment by imsky** [comment]
the data uri embedding stage can run after jekyll builds docs - as a grunt plugin, for example.

**Comment by adjohnson916** [comment]
@imsky I'd be interested in such a transform plugin.

**Comment by bardiharborow** [comment]
@cvrebert very happy to take this issue, but you aren't going to get the same effect you have currently (the dimension text changes when you resize the window, at least on album).

**Comment by mdo** [comment]
Closing as stale.
