### ISSUE TITLE
V4 - Responsive Cards

### ISSUE THREAD

**Issue by starise** [twbs/bootstrap#17486]
The new Bootstrap 4 [Cards](http://v4-alpha.getbootstrap.com/components/card) are nice, but regarding the variants, like Decks and Columns, i see that they're completely non-responsive at the moment. Am i wrong?

I think many users would use them in some kind of responsive layout.

**Comment by XhmikosR** [comment]
/CC @mdo I wanted to ping you about this yesterday too. One can see this by visiting the docs card page with a mobile phone.

**Comment by starise** [comment]
I'm trying to achieve the result in Decks being responsive. The main problem is that if you want equal heights, you have to apply 'card' styles on the flexbox item, then inside of it build the card. Applying the style to the box causes a collapse between elements due to the use of padding for spacing ([codepen](http://codepen.io/starise/pen/Gpgbyq)).

If you take a look at [my website](https://stari.co/scores), i achieved something like that using a flex container and boxes styled as cards themselves. Inside of the box there's the wrapper for the card. For spacing i had to play with margins instead of paddings as Boostrap does by default.

**Comment by mdo** [comment]
Work started in 0d0edeb.
