### ISSUE TITLE
Bootstrap 3.3.5, IOS 8.4.1 modal scrolls background when selecting input field

### ISSUE THREAD

**Issue by LotD86** [twbs/bootstrap#17497]
When i select a Form Field (Select and/or Textbox) In a Modal, the page in the Background scolls to top.
This also happens on the Bootstap example page:
http://getbootstrap.com/javascript/#modals-related-target

Works fine in Chrome, IE and Safari on Windows, and also in Safari on a Macbook.
The only troublemaker ist the iPhone and iPad Mini with IOS version 8.4.1.

All CSS hacks with modal-open didnt fix the problem.

**Comment by cvrebert** [comment]
It didn't use to do that...

**Comment by mdo** [comment]
Seems to be a browser bug.

**Comment by cvrebert** [comment]
Still reproduces in iOS 9.2.

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=153224

**Comment by cvrebert** [comment]
And added an entry to the Wall of Browser Bugs: http://getbootstrap.com/browser-bugs/

**Comment by chrisdemars** [comment]
This has been one of our issues at work. I looked in to it but just recently was approached again and dug deeper. This would be the bug.
