### ISSUE TITLE
.form-control-label padding-left breaks non-grid forms

### ISSUE THREAD

**Issue by MrOutput** [twbs/bootstrap#17498]
This is a `.form-control.form-control-lg` with `.form-control-label`

![screenshot from 2015-09-06 15-03-36](https://cloud.githubusercontent.com/assets/8491687/9706479/bad07874-54ab-11e5-96d2-96ca4b6eb621.png)

However, i have this issue with all labels regardless of control size

```css
.form-control {
    padding: 0.5em 0em;
}
```
^fixes this. Instead of `padding: 0.5em`

~~also card images need to have width of 100%~~

**Comment by cvrebert** [comment]
Please open a separate issue regarding the card thing.

**Comment by matt-hernandez** [comment]
In the docs, it seems like the use of `.form-control-label` only gets brought up if you are using form controls and labels with the `.col-*` and `.row` classes.

Eliminating the left and right padding would override the `.col-*` classes, so maybe it would be best to just specify top and bottom padding.

**Comment by cvrebert** [comment]
@mdo So, http://v4-alpha.getbootstrap.com/components/forms/#validation says to use `.form-control-label` to make labels pick up the form validation text color (regardless of the type of form),
but http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid basically implies `.form-control-label` should only be used for grid-based forms
(and indeed, the padding-left on `.form-control-label` screws up the alignment of the label text in http://v4-alpha.getbootstrap.com/components/forms/#validation ).
Which is it?

**Comment by mdo** [comment]
Coming in #19141.
