### ISSUE TITLE
v4 .form-inline doesn't work and documentation incorrect

### ISSUE THREAD

**Issue by badpk** [twbs/bootstrap#17507]
the v4 documentation for an inline form has the class .inline-form while the example below as .form-inline. also when using either class, my form is still display: block.

<img width="927" alt="screen shot 2015-09-07 at 9 24 46 am" src="https://cloud.githubusercontent.com/assets/2065666/9717755/39b34eae-5543-11e5-9e47-9b4773051900.png">

**Comment by rbrs** [comment]
Using `.form-inline` works fine for me. Maybe you could show your example when it does not work for you?

**Comment by mdo** [comment]
Looks like #17553 was merged to fix this.
