### ISSUE TITLE
Add Date & Time Picker Support

### ISSUE THREAD

**Issue by Shifrin** [twbs/bootstrap#17503]
Many developers & designers like me, try to use date and time pickers in their projects. Therefore, we always need to include separate JS and CSS for the pickers. So I am thinking if it is already attached as a component in Bootstrap like in UI-Kit it will be very useful for the developers & designers.

If it's already requested by someone please ignore this feature request.

**Comment by cvrebert** [comment]
Duplicate of #445.
Available third-party libraries for this include https://github.com/eternicode/bootstrap-datepicker

**Comment by rosieks** [comment]
Maybe it's worth mentioning about that date picker at official website?
