### ISSUE TITLE
The Great Firewall interferes with loading jQuery from Google's CDN for the docs

### ISSUE THREAD

**Issue by thanatos11** [twbs/bootstrap#17517]
Can you guys alocate the js, css resources to the local getBootstrap.com website, and avoid having to connect to google for the resources?

**Comment by cvrebert** [comment]
Define "secure network connection".
We added a local jQuery fallback in #16888; the docs site just hasn't been redeployed yet.

**Comment by thanatos11** [comment]
Maybe somewhere where the Great Firewall is in place. Anyway, thank you, I am waiting for the local jquery.js file on docs.

**Comment by cvrebert** [comment]
Closing as a duplicate then.
Politics... :rage:
