### ISSUE TITLE
v4-alpha btn-xs variables missing or documentation incorrect

### ISSUE THREAD

**Issue by miclip** [twbs/bootstrap#17516]
Documentation for v4 alpha lists `btn-group-xs` as an option yet `btn-group-xs`, class `btn-xs` and dependent variables do not exist. 

    .btn-xs {  // line-height: ensure proper height of button next to extra small input 
     @include button-size($btn-padding-y-xs, $btn-padding-x-xs, $font-size-xs, $line-height-xs, $btn-border-radius-xs);}

**Comment by kkirsche** [comment]
XS buttons have been removed in V4

**Comment by miclip** [comment]
Didn't realize that, just noticed it's also removed from doc src few days ago.

**Comment by cvrebert** [comment]
Duplicate of #17236.
