### ISSUE TITLE
Responsive Card-Groups (Keeping Equal Height)

### ISSUE THREAD

**Issue by Phillips126** [twbs/bootstrap#17528]
Would it be possible to take advantage of the grid css to make `.card-groups` responsive and keep the cards at equal heights?

An example of the code:
http://codepen.io/anon/pen/bVdvxR

    <div class="card-group">
        <div class="card col-sm-4 col-xs-12">
            <div class="card-block">
                <h4 class="card-title">Card 1</h4>
                <p class="card-text">Some content here...</p>
            </div>
        </div> 
        
    </div>

Adding the grid css to each card does make them responsive, but as you can see the cards are no longer at equal heights.
![screen shot 2015-09-08 at 12 06 54 pm](https://cloud.githubusercontent.com/assets/11968220/9740320/2815cffc-5622-11e5-972a-34f7b61416a5.png)

**Comment by lenamtl** [comment]
+1

**Comment by ato57** [comment]
+1

**Comment by gjsduarte** [comment]
+1

**Comment by samuelsiau** [comment]
+1

**Comment by jozydapozy** [comment]
+1

**Comment by samuelsiau** [comment]
+1

**Comment by DarioSalutt** [comment]
+1

**Comment by ManasN** [comment]
7 | +1 :)

**Comment by chetanism** [comment]
+1

**Comment by lindeberg** [comment]
+1

**Comment by Oxicode** [comment]
+1

**Comment by guylepage3** [comment]
+1

**Comment by mdo** [comment]
Flexbox will indeed be of help here. Nothing specific will change for the card groups at this time.
