### ISSUE TITLE
v4-alpha equal heights of card-block's

### ISSUE THREAD

**Issue by janusch** [twbs/bootstrap#17525]
Hey,
fantastic work on BS4. I am delighted to see and use a flexbox grid and the simplifications it brings. Also the switch to scss is very nice. 

While using the cards there was an issue getting equal heights for the card body, consulting in the chat we came forth with this possible solution:

http://codepen.io/anon/pen/xwGpOb

Hopefully it is in your interest to provide this functionality out of the bs4 box.

**Comment by cvrebert** [comment]
@janusch Duplicate of #17528?

**Comment by janusch** [comment]
@cvrebert Yes, we could say that. I am not sure if it's the exact same issue. The proposed solution in #17528 is an elegant fix, if it can be used to keep card sections to equal height.

Thanks for having a look at it.
