### ISSUE TITLE
scss build with flex FAILING

### ISSUE THREAD

**Issue by prijindal** [twbs/bootstrap#17527]
Building Scss after putting $enable-flex:true is failing
```
Error: ".col-xs-1" failed to @extend "%grid-column-float-xs".
       The selector "%grid-column-float-xs" was not found.
       Use "@extend %grid-column-float-xs !optional" if the extend should be abl
e to fail.
        on line 33 of site/static/client/bower_components/bootstrap/scss/mixins/
_grid-framework.scss
```

**Comment by prijindal** [comment]
Note: I am using the bower version

**Comment by cvrebert** [comment]
@prijindal Please retest against the latest commit in the [`v4-dev`](https://github.com/twbs/bootstrap/tree/v4-dev) branch.

**Comment by prijindal** [comment]
:thumbsup: working in the branch !!
but it is still not working when using the bower version

**Comment by cvrebert** [comment]
Closing as Fixed then.
