### ISSUE TITLE
Modal focus escapes when there is no focusable element after the modal HTML

### ISSUE THREAD

**Issue by wcopenhaver** [twbs/bootstrap#17529]
You can escape the enforced focus of the modal, by using the tab key, if there is not focusable element after the modal's HTML markup, such as;
```
<html>
...
            <button ... data-toggle="modal" data-target="#myModal">Open</button> ...
            <div class="modal fade" id="myModal" ... >...</div>
       </body>
</html>
```
If there is no focusable element in between the modal div and the close body tag, the focus will be lost by pressing the tab key.  See  http://codepen.io/anon/pen/vNORPG 

The workaround is to add a focusable element in between, such as; 

```
    <div class="modal fade" id="myModal" ... >...</div>
    <a href="#">...</a>
</body>
```

**Comment by twbs-lmvtfy** [comment]
Hi @wcopenhaver!

You appear to have posted a live example (http://codepen.io/anon/pen/vNORPG.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 10, column 3: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Successor: #17530.
