### ISSUE TITLE
cant install using bower?

### ISSUE THREAD

**Issue by Gillardo** [twbs/bootstrap#17538]
I have tried installing v4 via bower using the command

```bower install https://github.com/twbs/bootstrap/tree/v4-dev```

but this doesnt download anything but the bower file?

**Comment by cvrebert** [comment]
`bower install 'bootstrap#4.0.0-alpha'` works as expected.

**Comment by Gillardo** [comment]
Be helpful if the documentation was updated to say this pls

**Comment by cvrebert** [comment]
The docs do now say that: http://v4-alpha.getbootstrap.com/getting-started/download/#bower
