### ISSUE TITLE
Panel Title Does not Respect H1->H6

### ISSUE THREAD

**Issue by dscherertfm** [twbs/bootstrap#17533]
Putting a `.panel-title` on an `h1`...`h6` in the `.panel-heading` does nothing in latest Bootstrap, issue and workaround provided at http://stackoverflow.com/questions/32262542/bootstrap-3-panel-title-with-header-tag-h1-is-not-working.

**Comment by cvrebert** [comment]
This doesn't sound fixable without breaking backward compatibility.

**Comment by mdo** [comment]
Yeah, we're not going to be changing that. There are some older issues around this, too, FWIW. Basically our stance is most headings don't make sense in a panel heading—the spacing and relative sizing of elements would be a tad awkward.

**Comment by dscherertfm** [comment]
Then update the docs? They still reference support for this.

On 8 Sep 2015 7:16 pm, Mark Otto <notifications@github.com> wrote:

Yeah, we're not going to be changing that. There are some older issues around this, too, FWIW. Basically our stance is most headings don't make sense in a panel heading-the spacing and relative sizing of elements would be a tad awkward.

-
Reply to this email directly or view it on GitHub<https://github.com/twbs/bootstrap/issues/17533#issuecomment-138728273>.

CONFIDENTIALITY NOTICE: This electronic message contains information which may be legally confidential and/or privileged and does not in any case represent a firm TARGET FREIGHT MANAGEMENT bid or offer relating thereto which binds the sender without an additional express written confirmation to that effect. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error, and delete it. Thank you.

**Comment by cvrebert** [comment]
@dscherertfm Could you give a link to the problematic section?

**Comment by dscherertfm** [comment]
It's the one on panels http://getbootstrap.com/components/#panels

"Easily add a heading container to your panel with .panel-heading. You may also include any <h1>-<h6> with a.panel-title class to add a pre-styled heading."

On 8 Sep 2015 8:02 pm, Chris Rebert <notifications@github.com> wrote:

@dscherertfm<https://github.com/dscherertfm> Could you give a link to the problematic section?

-
Reply to this email directly or view it on GitHub<https://github.com/twbs/bootstrap/issues/17533#issuecomment-138734888>.

CONFIDENTIALITY NOTICE: This electronic message contains information which may be legally confidential and/or privileged and does not in any case represent a firm TARGET FREIGHT MANAGEMENT bid or offer relating thereto which binds the sender without an additional express written confirmation to that effect. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error, and delete it. Thank you.

**Comment by mdo** [comment]
Yeah, any heading will work—but we force the font-size. That's what that means.

**Comment by dscherertfm** [comment]
Well, I'm glad I've had you here to interpret the ambiguity for me, otherwise I'd still be here banging my head off my keyboard screaming at the screen and cursing the docs. Seems like a trivial change to the docs to clear up confusion about this as there are a few open issues on SO regarding this as well, with some hacky fixes to go with it.
