### ISSUE TITLE
 Modal focus escapes when there is no focusable element after the modal HTML

### ISSUE THREAD

**Issue by wcopenhaver** [twbs/bootstrap#17530]
You can escape the enforced focus of the modal, by using the tab key, if there is not focusable element after the modal's HTML markup, such as;

```
<html>
...
            <button ... data-toggle="modal" data-target="#myModal">Open</button> ...
            <div class="modal fade" id="myModal" ... >...</div>
       </body>
</html>
```

If there is no focusable element in between the modal div and the close body tag, the focus will be lost by pressing the tab key.  See  http://codepen.io/anon/pen/vNORPG 

The workaround is to add a focusable element in between, such as; 

```
    <div class="modal fade" id="myModal" ... >...</div>
    <a href="#">...</a>
</body>
```

**Comment by cvrebert** [comment]
([Demo JS Bin](http://output.jsbin.com/xeroli/1))

@wcopenhaver What browser and OS are you using? Adding the dummy `<a href="#">...</a>` doesn't seem to have any effect in Chrome or Firefox on OS X, AFAICT.

> the focus will be lost by pressing the tab key

I presume you really mean "focus will move to part of the browser chrome (e.g. the address bar)"? That wouldn't count as a bug anyway. Preventing keyboard users from accessing the address bar would be user-hostile behavior (plus I'm not sure it'd even be possible).

**Comment by wcopenhaver** [comment]
@cvrebert I'm using Windows 10 Chrome 44 and Firefox 40.  The JS Bin Demo seems to work, and it makes no difference with the dummy link because JS Bin still appends a link to the end of the document, the link is:
```
<a id="edit-with-js-bin" href="http://jsbin.com/xeroli/1/edit" style="top: -60px;">Edit in JS Bin <img src="http://static.jsbin.com/images/favicon.png" width="16" height="16"></a>
```
If you remove that link using the development tools, open the modal, and press tab multiple times you will experience the issue.  

I did mean that focus will move to the part of the browser (specifically the address bar), as you mention above.  And I do agree with you that you shouldn't try to prevent users from accessing the address bar.  I just found it confusing that an element that is not related to the modal, in this case the link, has such an adverse effect on the tabbing behavior of the modal.  I took me awhile to figure out what was going on.

**Comment by cvrebert** [comment]
Ah, I see. I'm just a pessimist these days.
Confirmed in Chrome.

**Comment by cvrebert** [comment]
Actually, I might not have jammed on the Tab key enough. Can't reproduce. Video proof:
![video](https://cloud.githubusercontent.com/assets/419884/9747606/80d0d414-5633-11e5-844c-de547e39dcf4.gif)
Keep in mind that the Tab key needs to be pressed like 3 or 4 times after the address bar to loop back around into the modal.

**Comment by wcopenhaver** [comment]
If you do not delete the link, the focus will stay captured by the modal as expected, and it will never go to the address bar.

**Comment by cvrebert** [comment]
I did delete the link. That's what I opened the dropdown menu in the inspector to do in the video. You can see it disappear from the DOM tree.

**Comment by cvrebert** [comment]
@XhmikosR Can you confirm I'm not taking crazy pills here?

**Comment by wcopenhaver** [comment]
If you leave the link the focus will never leave the modal, as expected and discussed in https://github.com/twbs/bootstrap/issues/3101.  

If you remove the link the focus will escape the modal and start going to the address bar.

**Comment by cvrebert** [comment]
> If you remove the link the focus will escape the modal and start going to the address bar.

Which, like we discussed, isn't a bug. So what change are you seeking exactly? An addition to the docs mentioning this edge case difference?

**Comment by wcopenhaver** [comment]
There are two different things happening here:

1. If you do not delete the link, the focus will never focus on the address bar and it will loop forever inside the modal.
1. If you do delete the link, the focus will escape the modal and go to the address bar, and other browser elements such as the Firefox search box

What is the correct behavior?

This bring me to my second comment:
> I just found it confusing that an element that is not related to the modal, in this case the link (the JS Bin link), has such an adverse effect on the tabbing behavior of the modal

**Comment by damionmounts** [comment]
Ran into this problem in 5.3.0 on Chrome in both Fedora and Windows.
- Sprinkling some `<button type="button">Dead</button>` before and after made it work fine.
- A Modal / an Offcanvas alone on the page causes the issue.

**Comment by cvrebert** [comment]
This issue is regarding v3. Given the elapsed time, v5 would be a separate issue.
