### ISSUE TITLE
Tooltip + modal

### ISSUE THREAD

**Issue by tglabicki** [twbs/bootstrap#17547]
Hi 

I build asp webform page (vb.net) 
My tooltips crashes when I open modal from code behind using below code

<pre>
Dim sb As New System.Text.StringBuilder()
            sb.Append('&ltscript type='text/javascript'&gt')
            sb.Append('$('#SetTime').modal('show');')
            sb.Append('&lt/script&gt')
            ScriptManager.RegisterClientScriptBlock(Me, Me.[GetType](), 'SetTimeModalScript', sb.ToString(), False)
</pre>

If I open the same modal form using button eg.
<pre>
"&ltbutton type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#SetTime"&gt"
</pre>
everything works fine.

To initialize tooltips I use 
<pre>
$(document).ready(function () {
            $('[data-tooltip="true"]').tooltip();
        });
</pre>
I try to find solution but I gave up after few hours.
I must use this code to open modal because I open it to display data for specific gridview row.

Thanks in advance for any help 
Thomas

**Comment by cvrebert** [comment]
Please direct personal support requests to StackOverflow, IRC, or Slack, instead of this bug tracker. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker which includes links to those other community forums.
Thanks!
