### ISSUE TITLE
Modal scroll issue in Chrome for Android

### ISSUE THREAD

**Issue by davide-quix** [twbs/bootstrap#17543]
When opening a modal o Android using Chrome, if the user  scrolls at some point the underground body starts scrolling ignoring the `overflow: hidden` rule.

Tested using Android 5.0 and Chrome 39

**Comment by sevdog** [comment]
Using Chrome 43 it seem to work properly.
The only issue is when the browser dockbar disappears, leaving the backdrop smaller than screen for a little time.

**Comment by cvrebert** [comment]
And the stable version of Android Chrome is currently v45.
@davide-quix Please upgrade your Chrome and re-test.
Please also take note of http://getbootstrap.com/getting-started/#overflow-and-scrolling , as I'm not sure whether you're describing that known issue or a different problem.

**Comment by davide-quix** [comment]
@cvrebert upgrading the browser and the webview component of my device the bug seems to be fixed.
I will recommend my users to keep everything up to date.

However i confirm the anomaly reported by @sevdog .

**Comment by cvrebert** [comment]
Feel free to open a separate bug about that anomaly (preferably with a video or screenshot).
Closing this bug as invalid.
