### ISSUE TITLE
.carousel-indicators li { }  Warning: Expected color but found '#\30 00\9 '

### ISSUE THREAD

**Issue by dlmiles** [twbs/bootstrap#17546]
Understand on the IE hack matter from https://github.com/twbs/bootstrap/issues/16803

But FireFox 40.0.3 reports CSS error as:

Warning: Expected color but found '#\30 00\9 '.  Error in parsing value for 'background-color'.  Declaration dropped.

Note the extra \3 in there and the 2 spaces.

My text editor reports the minified snippet as: cursor:pointer;background-color:#000\9;background-color:transparent

This is after minification (via grunt-contrib-cssmin ~0.13 and ) and such.  Can you confirm there isn't a control-code (that my text editor is not seeing) or that there isn't a bug in grunt-contrib-cssmin concerning this hack.

Is this handling exactly as expected ?  I notice there is the transparent setting directly after which should supersede anyway.

Some kind of original source comment would have been helpful to explain what is doing on and which browsers are expected to reject the line.  This way you only get a bug report when someone notices such a comment doesn't match their testing.

**Comment by cvrebert** [comment]
There is already a source code comment for this: https://github.com/twbs/bootstrap/blob/3487898a6af8c1d5b12f7b040d30e71b19e34923/less/carousel.less#L203

I can confirm that there aren't any control codes in Bootstrap v3.3.5's `bootstrap.min.css`, and that the code snippet displayed in Firefox's error message is inaccurate. There is no `\30` or extra spaces in the actual code. I shall file a bug against Firefox.

**Comment by cvrebert** [comment]
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1203346
