### ISSUE TITLE
form-group should use flex

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#17554]
Somtimes in form-horizontal labels takes more then one line.
Then label and input is at the top of field and I think it should be in the middle.
Here is (not mine) flex solution (with extra class - could be default with form-group)
http://stackoverflow.com/a/30153750/979911

Consider it in v4

**Comment by mdo** [comment]
> I think it should be in the middle.

We'll be leaving it at the top for now. Thanks though!
