### ISSUE TITLE
v4 css file doesn't contain navbar-header classes

### ISSUE THREAD

**Issue by puffster** [twbs/bootstrap#17559]
I'm an "high-end novice" so I hope this isn't a dumb question, but I just updated bootstrap to alpha-4 via Nuget, and there doesn't appear to be any functionality included in the .css file for navbar-header classes...am I missing something?

**Comment by plunger** [comment]
simply doesn't exist in the v4-dev branch. http://v4-alpha.getbootstrap.com/components/nav/

It'll be added to a build soon it seems. https://github.com/twbs/bootstrap/issues/17532

**Comment by mdo** [comment]
There is no more `.navbar-header` in v4. Navbars are still in need of a ton of work, so consider them incomplete in the alpha builds for the next bit.
