### ISSUE TITLE
v4 - Collapse JavaScript - not removing a temporary style.

### ISSUE THREAD

**Issue by IceReaper** [twbs/bootstrap#17555]
Hello,

when closing a collapse element, this line gets triggered:
this._element.style[dimension] = 0
causing the correct animation but which is not overwritten by
this._element.style[dimension] = ''
when the transition is completed.

After closing a collapse, there is a leftover height style, which might break layout and has to be removed when close transition is finished.

Should be added around line 232.

**Comment by cvrebert** [comment]
A JS Bin or JS Fiddle that demonstrates the problem would be greatly appreciated.

**Comment by IceReaper** [comment]
https://jsfiddle.net/nngk8x0t/

**Comment by twbs-lmvtfy** [comment]
Hi @IceReaper!

You appear to have posted a live example (https://fiddle.jshell.net/nngk8x0t/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 42, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 43, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
