### ISSUE TITLE
v4-alpha decimal rem number for borders breaks in chrome.

### ISSUE THREAD

**Issue by janusch** [twbs/bootstrap#17556]
Somehow, maybe by adjusting the base font size, I ended up with borders that have 0.625rem as thickness. This did not display any borders in chrome. Have not tested in other browsers. 

Wouldn't it be better to have borders pixel based, or to round rem's to something that displays in all browsers?

**Comment by minipai** [comment]
+1
When set "Zoom out" to 90% view, .0625rem cal as less then 1px, thus won't render border in Chrome.
Better just use 1px.

**Comment by mdo** [comment]
Addressed in 85f08df.

**Comment by rasmuswoelk** [comment]
How can we pull in this fix? Currently we pull in: "bootstrap": "4.0.0-alpha",
