### ISSUE TITLE
v4 .form-group lacks clearfix to work properly as grid row

### ISSUE THREAD

**Issue by marvin1023** [twbs/bootstrap#17560]
```html
<div class="form-group">
    <label class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <p class="form-control-static">email@example.com</p>
    </div>
</div>
```
`.col-sm-2` and `.col-sm-10` has float, but `.form-group` has no clearfix

**Comment by sdustinh** [comment]
I have this same problem. It doesn't seem to be broken on the docs so I assume it is because I have `$enable-flex: true`.

**Comment by mdo** [comment]
Per http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid, the `.row` class is required for now.
