### ISSUE TITLE
Proper color schemes and variations

### ISSUE THREAD

**Issue by gseregni** [twbs/bootstrap#17567]
IMHO every component should have its own color variations: primary/inverse/secondary/info/warning/success
To simplify the development of custom themes for every brand color a related text-color variable should defined. 
So i would expect to find something like this:

$brand-primary:             #0275d8 !default;
$brand-success:             #5cb85c !default;
$brand-info:                #5bc0de !default;
$brand-warning:             #f0ad4e !default;
$brand-danger:              #d9534f !default;

$brand-primary-text:             black !default;
$brand-success-text:             white !default;
$brand-info-text:                white !default;
$brand-warning-text:             white !default;
$brand-danger-text:              white !default; 

So to avoid to have dozens of text variables to override, like $btn-primary-color  $label-color $progress-bar-color etc .

Also border, active and similiar rules should be derived by the current color variation for default, instead of assigning fixed values.
  
--
Giulio
Pingendo

**Comment by cvrebert** [comment]
> Also border, active and similiar rules should be derived by the current color variation for default, instead of assigning fixed values.

We already do that FWICT, e.g. https://github.com/twbs/bootstrap/blob/b811f8cf9628dbcbfe994f71588c5a0c921a092d/scss/mixins/_buttons.scss#L7-L8
Do you have a specific example where we don't do that but believe we should?

**Comment by gseregni** [comment]
I know you already did that in the various scss files and it's fine. 
i'm speaking about the variables.scss ... take for example this
$btn-primary-color:              #fff !default;
why to "hardcode" a white foreground color ? 
IMHO , given that the bg color of primary button is $brand-primary, the foreground should be at least computed as the most "readable" between black and white. 
or better, you should define a variable for background and a variable for foreground for every color variation. 

Additionally, for coherence, I think that all the components should have all the color variations. Why i can change the color of a button and not the color of a breadcrumb , or a nav ? or why navbar has the inverse variation and buttons do not ?

Last but not least, defining bg and foreground color for every variation would make simpler to skin navigation bar. 
If final version will remain like now, if i have a navbar bg-primary that is white e.g., and i change the theme, making bg-primary black, i will need to change also the html switching from navbar-light to navbar-dark. It make over-complicated to change color palettes for tool like Pingendo.

Hope it helps, and thank you for your time.

--
Giulio 
Pingendo
 


IMHO or

**Comment by gseregni** [comment]
@mdo always on the same subject, why just btn has secondary variation ? imho the framework should normalize color variations across different components. it's counterintuitive to have navbars dark and light, just button with secondary, nav without colors... etc

**Comment by abibell** [comment]
I can see lot of uses for the color schemes. It can be very handy. Color is like painting you could apply to anything you need. Code would be much cleaner. No more btn-primary, panel-danger, alert-info and such just the words primary, danger and inverse.

We might have to pick the color variants for some components like alerts where they don't look good with primary color but a lighter version does the trick.

# What component combinations do we need to test this out and what we don't need to?
# Do we consider this as breaking change like card and tell everyone to replace *-schemename to schemename?
# I might have to need your help if I were to implement this foreground color as I feel there might be some hidden issue in future @gseregni

This would require some significant changes in source code, I am happy to do this in next two weeks if @mdo and other key collaborators agrees to this.

**Comment by cvrebert** [comment]
> No more btn-primary, panel-danger, alert-info and such just the words primary, danger and inverse.

The prefixes are there for good reason; see http://markdotto.com/2012/02/16/scope-css-classes-with-prefixes/

**Comment by gseregni** [comment]
@abibell @cvrebert i'm available too.

**Comment by mdo** [comment]
> IMHO every component should have its own color variations

That's an assumption I don't agree with. Not everything needs a variation, though I do agree naming needs rethinking and unifying across the board. Will add to a new tracking issue shortly.
