### ISSUE TITLE
Bootstrap example templates

### ISSUE THREAD

**Issue by hcgtv** [twbs/bootstrap#17562]
Hi,

What license do the example templates fall under on your website?

http://getbootstrap.com/getting-started/#examples

Thanks.

**Comment by cvrebert** [comment]
They are part of Bootstrap's documentation, which is licensed under CC BY 3.0 (https://github.com/twbs/bootstrap/blob/master/docs/LICENSE / https://creativecommons.org/licenses/by/3.0/).

**Comment by hcgtv** [comment]
Thank you sir.
