### ISSUE TITLE
:focus style of .carousel-control arrow button is too prominent

### ISSUE THREAD

**Issue by Baskerville42** [twbs/bootstrap#17571]
After I clicked on carousel-control buttons (left or right), focus state stayed. Look on right control on the screenshot.
![Screenshot](https://cloud.githubusercontent.com/assets/5596941/9817886/383ac142-58ae-11e5-92ea-c29ae2e13b22.png)

**Comment by rbrs** [comment]
I think it's by design - general buttons behavior is the same.

**Comment by Baskerville42** [comment]
But it looks wrong, in my project I must fix it.

**Comment by kkirsche** [comment]
While it may look wrong, technically nothing else has gained focus since that point. The only logical thing that could maybe take the focus would be the new image, otherwise just losing the focus could cause problems from an accessibility standpoint.

**Comment by mdo** [comment]
Punting on this one.
