### ISSUE TITLE
v4 js issue with popover.js file

### ISSUE THREAD

**Issue by SimonJ** [twbs/bootstrap#17574]
Hey,

I'm just trying v4 out but i keep getting this error `Uncaught TypeError: Cannot read property 'Default' of undefined` when i try to run the javascript files

![skaermbillede 2015-09-11 kl 19 06 22](https://cloud.githubusercontent.com/assets/183790/9821082/3c4f1652-58b8-11e5-8a20-b3f110b459ea.png)

any one have this problem?

**Comment by zacechola** [comment]
Can you recreate this on a jsbin or similar?

**Comment by SimonJ** [comment]
oh it was my own error, i dident used the right js files from the download folder
