### ISSUE TITLE
Inconsistent button/dropdown outline

### ISSUE THREAD

**Issue by acshef** [twbs/bootstrap#17573]
How come regular buttons don't remove the focus `outline`, but dropdown buttons do? The difference is jarring, especially when using split button dropdowns. (This affects v3 and v4.)
![image](https://cloud.githubusercontent.com/assets/9013284/9820501/94251ea4-5871-11e5-87f5-cb438a2364de.png)
![image](https://cloud.githubusercontent.com/assets/9013284/9820521/af7df158-5871-11e5-88bc-55f1ebecf16b.png)
I'm curious: what's the reason for this design?

**Comment by cvrebert** [comment]
Presumably @mdo thinks the focus outline on a dropdown menu button after a dropdown menu is closed either is confusing or looks bad.
See https://github.com/twbs/bootstrap/commit/8bb7def26cac4d3166fbf2cc98f16c4151794676#diff-69b9ec7c8eab7fe0e63a39c7bb88e003R24

**Comment by acshef** [comment]
That's a fair design preference, although it's still inconsistent :) Regular buttons retain the focus outline after being clicked. I see that on the dropdown toggle button element, the `aria-expanded` attribute changes depending on whether the dropdown is expanded or not. Since `[attribute=value]` is only a CSS Level 2 selector, would it be preferrable to conditionally hide the outline based on that?

**Comment by patrickhlauke** [comment]
> would it be preferrable to conditionally hide the focus outline based on that

could you propose a tweak/show an example of what you mean (a jsfiddle or similar would be great). this is definitely a thorny area that we'd like to address at some point...

**Comment by acshef** [comment]
http://jsfiddle.net/k8L0u7os/
I've drummed up some examples, but I'd have to better understand it from @mdo's standpoint. The comment says
>Prevent the focus on the dropdown toggle when closing dropdowns

Why is that wanted? When the dropdown is closed, the focus does technically go back to the dropdown button. So why mask it?

**Comment by patrickhlauke** [comment]
because designers usually don't like it, is probably the short answer

**Comment by mdo** [comment]
> because designers usually don't like it, is probably the short answer

There was feedback long ago that it was awkward to emphasize something that was recently closed—in this case our dropdown menus. I'd rather we be consistent though and really like the hidden when open example in that jsfiddle.
