### ISSUE TITLE
Block component from Mochi template should be part of Bootstrap

### ISSUE THREAD

**Issue by gseregni** [twbs/bootstrap#17579]
IMHO [a block component like the one in the Mochi template](http://bootstrap-themes.github.io/marketing/docs/#blocks) should be part of Bootstrap. Building site made of stacked blocks/section it's quite a de-facto standard nowadays. In Pingendo we implemented something similar. 
I would add also a .block-cover class that make the block full-height.

--
Giulio
Pingendo

**Comment by rbrs** [comment]
Well it's pretty much the same as [jumbotron](http://v4-alpha.getbootstrap.com/components/jumbotron/) is. Major difference is that text is centered, but `.text-center` fixes that. It's not worth to make as a separate component IMO.

**Comment by gseregni** [comment]
and what about a 100% height modifier ?

**Comment by mdo** [comment]
Won't be adding to the core. The jumbotron will be getting nuked I think anyway for a series of utilities, so theoretically we could do more utilities for full height maybe. Not for the initial launch though.

**Comment by gseregni** [comment]
@rbrs  It's not just a jumbtron. It incudes "logic" for block-foreground and block background
