### ISSUE TITLE
Modal width causes content getting cut off in small viewport sizes

### ISSUE THREAD

**Issue by supergibbs** [twbs/bootstrap#17581]
The normal modal width is set to 600px on anything bigger than a sm viewport (34em/544px) so when the viewport is 544px to 599px, the modal width causes horizontal scrolling.

javier reported this in Slack and made the following demo:

http://codepen.io/anon/pen/YyyRzR

**Comment by twbs-lmvtfy** [comment]
Hi @supergibbs!

You appear to have posted a live example (http://codepen.io/anon/pen/RWWMbv.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 39: Start tag ```` body ```` seen but an element of the same type was already open.
* line 8, column 1 thru column 39: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by supergibbs** [comment]
Updated http://codepen.io/anon/pen/YyyRzR

**Comment by twbs-lmvtfy** [comment]
Hi @supergibbs!

You appear to have posted a live example (http://codepen.io/anon/pen/YyyRzR.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 8, column 1: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-dialog` must be a child of `.modal`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by supergibbs** [comment]
Oops, probably should have verified his code first... anyway, I fixed it and used the css from the docs to make sure the modal is shown. Not sure if embedding a modal like this is a supported use case but issue is real, you can see it in the [live modal demo on the docs](http://v4-alpha.getbootstrap.com/components/modal/#live-demo). With the `.modal` wrapper it doesn't scroll but it still cuts off.

**Comment by cvrebert** [comment]
> Not sure if embedding a modal like this is a supported use case

Erm, you mean using it as a non-modal glorified panel/card? Doubtful.

**Comment by supergibbs** [comment]
Agreed but it happens as a real modal too. Sorry if that wasn't clear. Go to the docs and click the live modal demo button then make your viewport between 544px and 599px to see part of the modal cut off.

**Comment by jacargentina** [comment]
v4 alpha 2 was released without this fixed yet ??

**Comment by cvrebert** [comment]
@jacargentina That's just how things go with volunteer-based projects sometimes.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Fix coming in #19105.
