### ISSUE TITLE
V4.0.0-alpha tooltips js error hover

### ISSUE THREAD

**Issue by jimolina** [twbs/bootstrap#17588]
Hi

With this:

```
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
   Tooltip on top
</button>

$('[data-toggle="tooltip"]').tooltip();
```
Give me this error:

bootstrap.min.js (line 7, col 4687)
ReferenceError: Tether is not defined
	...rigger(this.constructor.Event.INSERTED),this._tether=new Tether({attachment:j,el...

OSX 10.10.5 | Firefox 40.0.3

**Comment by jimolina** [comment]
I saw the reference in the documentation:

"Tooltips rely on on the 3rd party library tether for positioning. You must include tether.min.js before bootstrap.js in order for tooltips to work!"

Sorry.

**Comment by cvrebert** [comment]
Duplicate of #17273.
