### ISSUE TITLE
lost on breakpoints

### ISSUE THREAD

**Issue by mmjaeger** [twbs/bootstrap#17585]
Hello
Hope somebody can help - How do I set a media breakpoint let's say from medium to large - do I nest the min mixing and max mixing or how do I do that.

the output I'm after is something like this: @media (min-width: 480px) and (max-width: 767px)

Thank you in advance for your help

**Comment by cvrebert** [comment]
How-to questions should be asked on StackOverflow or similar (see https://github.com/twbs/bootstrap/blob/master/README.md#community ), not on this bug tracker. Thanks!

**Comment by cvrebert** [comment]
However, see https://github.com/twbs/bootstrap/blob/87308ba2f6960ba7b5d630cd3aaf19b304df6b5c/scss/mixins/_breakpoints.scss#L70
