### ISSUE TITLE
Documentation: Varying modal content demo does not work

### ISSUE THREAD

**Issue by ZacharyDraper** [twbs/bootstrap#17584]
In the modal documentation under the 'Varying modal content based on trigger button,' the demo does not work as expected. When the user clicks one of the buttons such as 'Open modal for @mdo,' the modal opens but the modal label and content is not updated.

The desired functionality is that the label should be updated to read 'New message to @mdo' and the recipient input field should be populated with '@mdo.'

**Comment by jamez14** [comment]
Pending pull request (17607) for this [here](https://github.com/twbs/bootstrap/pull/17607)

**Comment by mdo** [comment]
Looks like this was addressed: https://github.com/twbs/bootstrap/pull/17607#issuecomment-186010879.
