### ISSUE TITLE
Would love to have control over the card border-radius variable(s)

### ISSUE THREAD

**Issue by martin-pettersson** [twbs/bootstrap#17597]
(I just assumed that they would either be located in the variable file or at least have a !default suffix if they where meant to be configurable)

**Comment by abibell** [comment]
The [_variables.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L187) file has few border radius variables. Are you talking about something else @martin-pettersson ?

```scss
$border-radius:          .25rem !default;
$border-radius-lg:       .3rem !default;
$border-radius-sm:       .2rem !default;
```

**Comment by martin-pettersson** [comment]
I see now it has been added in _variables.scss (see: ba6cf48 and 793db36)
Thanks!

**Comment by liquidvisual** [comment]
Currently the global border-radius variable has no effect on cards :/

**Comment by cvrebert** [comment]
@liquidvisual I've opened #17903 to fix that.
