### ISSUE TITLE
Document that @screen-*-min were replaced by $grid-breakpoints

### ISSUE THREAD

**Issue by garrettjohnson** [twbs/bootstrap#17593]
The new $screen-{xs,sm,md,lg,xl}-min variables don't exist. See http://v4-alpha.getbootstrap.com/migration/#responsive-utilities
![screenshot 2015-09-13 15 40 55](https://cloud.githubusercontent.com/assets/374209/9839406/1a731976-5a2e-11e5-914f-96b4eaffc2b6.png)

**Comment by glebm** [comment]
Need to document `map-get($grid-breakpoints, xs)` and the new `media-breakpoint-up/down/only` mixins.

**Comment by mdo** [comment]
Coming in #17593.

**Comment by cvrebert** [comment]
Reopening since @mdo didn't update the specific section of old busted advice mentioned in OP.

**Comment by mdo** [comment]
Removed those bits in 1ba370f. Less specific, but more concise and to the point.
