### ISSUE TITLE
Navbar right padding broken when using navbar-text, navbar-right and navbar-fixed-top

### ISSUE THREAD

**Issue by eszstuff** [twbs/bootstrap#17598]
Issue similiar to https://github.com/twbs/bootstrap/issues/11783 but occurs with classes "navbar-text navbar-right" and navbar-fixed-top. 

Example: http://jsbin.com/puhivomaca/edit?html,output

Tested with version 3.3.5.

**Comment by rifton007** [comment]
For me too, it is not fixed.

**Comment by cvrebert** [comment]
X-Ref: #18362

**Comment by cvrebert** [comment]
Duplicate of #16694, which is WontFix. The v3 navbar is admittedly kinda sucky, too much so to be feasibly fixable while maintaining backward-compatibility; we're hoping to do better with Bootstrap v4's navbar.
