### ISSUE TITLE
When a heading is used in .card-header, the margin bottom makes the layout uneven.

### ISSUE THREAD

**Issue by cfarquharson** [twbs/bootstrap#17609]
The card heading ` <div class="card-header">Featured</div>` allows a user to fake out a header style, but if you try to put put an actual heading in that div, the display is odd as there is default 8px margin on the bottom.  Can this be modified to match the effect that was previously available in panels? 

I even tried that `<div class="card-header"><h3 class="card-title">Special title treatment</h3></div> ` but that didn't fix it and instead created a 12px margin on the bottom.

http://v4-alpha.getbootstrap.com/components/card/#header-and-footer 
![card1](https://cloud.githubusercontent.com/assets/2319199/9892925/53a94d0a-5bc8-11e5-89f4-1d15fc3f4e04.jpg)

![card2](https://cloud.githubusercontent.com/assets/2319199/9892891/1321e0b2-5bc8-11e5-8329-b6e3717e780d.jpg)

**Comment by cvrebert** [comment]
`<h3 class="card-header">Featured</h3>` seems to look okay to me.

**Comment by cfarquharson** [comment]
@cvrebert ahh yes.  You might way to change the demo code to show a heading using that class instead of a div so it's more semantically correct.  I was assuming the code was similar to panels where you had to nest the heading in it's own heading div.  Thx for the quick reply!

**Comment by cvrebert** [comment]
Reopening as a docs bug to add an example of using an hN tag as a `.card-header`.

**Comment by mdo** [comment]
Resolved in #17626.
