### ISSUE TITLE
DOC: v4 button group doc exemplifies -xs that is no longer applicable

### ISSUE THREAD

**Issue by NicholasPGoodwin** [twbs/bootstrap#17606]
DOC
A minor yet misleading mistake in the component documentation:
http://v4-alpha.getbootstrap.com/components/button-group/#sizing
The "Extra small" modifier -xs is no longer supported, but it still appears in the illustration example, albeit incorrectly.

**Comment by cvrebert** [comment]
Already fixed, we just haven't redeployed the docs yet.

**Comment by NicholasPGoodwin** [comment]
Thanks for the prompt response!

**Comment by cvrebert** [comment]
Duplicate of #17029.
