### ISSUE TITLE
Throw explicit error when a nonexistent method is invoked

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17612]
Refs #17544.
`data[config] is not a function` sucks compared to `No method named "destroy"`

**Comment by Johann-S** [comment]
it would be nice for sure :+1: 

Is it something we can generalize for all the plugins ?

**Comment by cvrebert** [comment]
Yes, this is not intended to be tooltip-specific.

**Comment by cvrebert** [comment]
Fixed by #17616.
