### ISSUE TITLE
When to code a fix, and when to wait

### ISSUE THREAD

**Issue by matt-hernandez** [twbs/bootstrap#17627]
Hey everyone. I really want to get involved with contributing to an open source project. Since I'm a big fan of Bootstrap, I figured why not try to add some small fixes here and there.

I've been taking a good look at all the open and closed issues. It seems to me that one shouldn't start coding a fix for an issue until the "confirmed" label has been attached.

I'm not saying it's a hard and fast rule, just that it seems pretty common. Can anyone else weigh in on this?

**Comment by Johann-S** [comment]
Yes when it's a issue to be sure you can wait for the confirmed label but when you saw a feature label you can work on it too.
But feature can only be accepted for the V4

**Comment by mdo** [comment]
The `feature` label doesn't guarantee that we do the feature, just that it's a feature request. The `confirmed` one is definitely a good signal though. Asking in myself or another contributor in Slack or on the relevant issue thread can also be helpful.
