### ISSUE TITLE
Unnecessary padding-right added to modal

### ISSUE THREAD

**Issue by LaurentVB** [twbs/bootstrap#17622]
Hello,

When a modal is open, a padding-right is added even when it's not needed (Bootstrap 3.3.5 in latest firefox and latest chrome). The padding is added on the ```.modal``` element by javascript.
It is probably supposed to account for the scrollbar, but actually there is no scrollbar shown, somehow it is disabled when the modal is opened. When the modal overflows, then a scrollbar appears and the padding is appropriate.

See the bug in action on the following screenshot of http://getbootstrap.com/javascript/#modals-examples in chrome:

![screen shot 2015-09-16 at 18 45 51](https://cloud.githubusercontent.com/assets/2806149/9911602/31a90e12-5ca3-11e5-832c-bb27c3a7af03.png)

**Comment by cvrebert** [comment]
What's the `window.innerWidth` at which you're encountering this problem?

**Comment by petetnt** [comment]
The extra padding on the right comes from the missing scrollbar: when scrollbar is there, the padding is correct.

**Comment by cvrebert** [comment]
@LaurentVB Is your problem likewise related to resizing the window while the modal is open?

**Comment by LaurentVB** [comment]
I guess it could be...
I cannot reproduce right now, on my laptop without my second screen (?). I'll check again tomorrow at the office.

**Comment by cvrebert** [comment]
@petetnt
> (2) Delete text from the modal until scrollbar disappears

You must call `handleUpdate` after doing that: http://getbootstrap.com/javascript/#modalhandleupdate
(It's a limitation in Bootstrap v3's current implementation.)

**Comment by petetnt** [comment]
@cvrebert yeah I was just typing that I forgot that `handleUpdate` must be called when the height changes. I think that is what causes this bug, but `handleUpdate` should be called too when the browser resizes. Otherwise `this.scrollbarWidth` is wrong when the scrollbar disappears.

**Comment by LaurentVB** [comment]
Hello.
I can confirm reproduction on latest chrome, without resizing the window when modal is open.
window.innerHeight: 1057
window.innerWidth: 1548

See attached screenshot.
![screen shot 2015-09-17 at 10 06 57 2](https://cloud.githubusercontent.com/assets/2806149/9928121/20506abc-5d24-11e5-9f01-1ddd82cb5d4a.png)

**Comment by cvrebert** [comment]
I can't seem to reproduce that, albeit I don't currently have such an incredibly large monitor at my disposal. Does this still happen if you disable all your Chrome extensions?

If possible, try debugging the Modal JavaScript. The bug is presumably somewhere in the following section: https://github.com/twbs/bootstrap/blob/911312d61ee27eda034346dfe717d989cc92d1a4/js/modal.js#L241-L284

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by nitinelegant** [comment]
If nothing works. Then try this
1. Go to downloaded bootstrap file in your project.
2. Open bootstrap css file where you will find two file (i) bootstrap.css and (ii) bootstrap.min.css
3. Open both one by one and search modal-scrollbar-measure and comment that section in both file. 
4. It will defenitly work.

**Comment by satyaprasadkota** [comment]
Hello,
 The same issue was repeated on v5.2, please suggest to me, what changes I have to make.
![image](https://user-images.githubusercontent.com/32476604/212315052-c1c356f0-0ef3-4e33-95a5-cfea4b9bc473.png)

**Comment by cvrebert** [comment]
@satyaprasadkota Search for a relevant **open** bug or else file a new bug. Sane folks aren't monitoring closed, dead bugs from 2 major versions ago.
