### ISSUE TITLE
mobile navbar shown on desktop-width viewport

### ISSUE THREAD

**Issue by Gum-Joe** [twbs/bootstrap#17624]
When I installed bootstrap 4, it appeared to be that all my glyphs disappeared, the glyphs did not appear and all my buttons' fonts went below the button (although that's probably to do with the font)

Before:
![screenshot 18](https://cloud.githubusercontent.com/assets/12299307/9912645/98d4b5f8-5ca0-11e5-9ccf-104925f4b337.png)
![screenshot 19](https://cloud.githubusercontent.com/assets/12299307/9912646/98d5dcc6-5ca0-11e5-8962-e322cf04490d.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/12299307/9912647/98d71eba-5ca0-11e5-8651-04ac70822457.png)

After:
![screenshot 14](https://cloud.githubusercontent.com/assets/12299307/9912664/ae6cdc4c-5ca0-11e5-964a-f21b52ca5275.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/12299307/9912663/ae6c0ea2-5ca0-11e5-8b2a-f6205af625c3.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/12299307/9912665/ae7319ae-5ca0-11e5-8ac2-e9c34a628b27.png)

If you wish for my HTML, please comment

**Comment by cvrebert** [comment]
The Glyphicons integration has been removed in v4: http://v4-alpha.getbootstrap.com/migration/#components
You can either include them on your own, or use another icon set (e.g. Font Awesome).

Regarding the width problem, we'd need a JS Fiddle or JS Bin example to investigate.

**Comment by Gum-Joe** [comment]
What is a Jsbin

**Comment by cvrebert** [comment]
http://jsbin.com/
http://jsbin.com/help/getting-started

**Comment by cvrebert** [comment]
Closing due to lack of response.
