### ISSUE TITLE
Make a class to set item visibility based on size of window

### ISSUE THREAD

**Issue by parixitjani** [twbs/bootstrap#17629]
Hi Bootstrap,
No wonder! you are doing a great job.
I just want to suggest that 
How is it, If we toggle the visibility of any item(tag) based on size change, That might be useful a lot.

Thanks

**Comment by cvrebert** [comment]
That already exists:
* v3: http://getbootstrap.com/css/#responsive-utilities
* v4: http://v4-alpha.getbootstrap.com/layout/responsive-utilities/
