### ISSUE TITLE
Sass compliation failed. Icompatible units

### ISSUE THREAD

**Issue by icemancast** [twbs/bootstrap#17620]
Sass Compilation Failed: resources/assets/vendor/bootstrap/scss/_variables.scss
  286:36  Incompatible units: 'rem' and 'px'

Had the following fail. Used bower to install and using Laravel Elixir (gulp) to compile sass and always fails.

**Comment by cvrebert** [comment]
Unable to reproduce against current `v4-dev` branch.

**Comment by icemancast** [comment]
Human error :). Had another variables file that was using px as unit measure.... doh!
