### ISSUE TITLE
Remote Modal Keeps moving the layout towards left

### ISSUE THREAD

**Issue by devyaqoob** [twbs/bootstrap#17628]
Hi,

i just updated to bootstrap v3.3.5 but the fix does not working for me, its getting even weird. When modal window opens first time its loading fine no issues, but when clicks again, it disturbs the layout, and on each click the layout slightly moves towards left. after a number of clicks (modal open/close)  the top static navbar, footer, header are gone towards left.

How to fix this issue? please help?

found this JS on SO to reset the modal window, but it doesn't works for me either.

```javascript
$(document).ready(function(){

$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});

});
```

**Comment by cvrebert** [comment]
We'll need a reduced test case (e.g. JS Bin) as mentioned in https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by devyaqoob** [comment]
@cvrebert thanks for the response. While i was creating the JS Bin i found out the issue was on my end :( and its fixed now. Sorry to bother you ... How can i delete this thread?

**Comment by cvrebert** [comment]
The "Close issue" button. I'll do it for ya.

**Comment by devyaqoob** [comment]
Thanks.
