### ISSUE TITLE
Bootstrap version 4's nav bar thinks it is on a mobile device and all the buttons appear to have weird fonts 

### ISSUE THREAD

**Issue by Gum-Joe** [twbs/bootstrap#17623]
* White buttons appear grey (so
Writing...

**Comment by wolfy1339** [comment]
Please post a JSBin containing **only Bootstrap and your navbar code**

**Comment by Gum-Joe** [comment]
I 'm going to close this issue as I do not have time to describe it

**Comment by cvrebert** [comment]
Duplicate of #17624.
