### ISSUE TITLE
Demo page problem

### ISSUE THREAD

**Issue by Jegulsky** [twbs/bootstrap#17639]
Seems like you have a problem with you product page http://getbootstrap.com/components/#dropdowns
A lot of trash in console of my Chrome and not working dropdowns in your sample

**Comment by patrickhlauke** [comment]
Of the dropdown examples in the docs, only the "dropup" variant is meant to be interactive...all others are forced to be open to show what the menus look like.

As for Chrome console, apart from a warning about "SVG's SMIL animations" relating to html5player-new.js, I don't see any "trash" or other notices.

**Comment by Jegulsky** [comment]
In this case all works correct. Thanks for reply.
