### ISSUE TITLE
Migration docs don't mention .btn-group-justified removal

### ISSUE THREAD

**Issue by gseregni** [twbs/bootstrap#17631]
.btn-group-justified has been removed from docs and from scss. Is this intentional ?

**Comment by cvrebert** [comment]
Yes: 454cc55e313d29d886563b874abab33412f0d31d
We ought to add an entry to the v4 Migration docs.

**Comment by gseregni** [comment]
@cvrebert But what is the replacement for .btn-group-justified ?

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by gseregni** [comment]
@mdo why to remove .btn-group-justified ?

**Comment by Teranode** [comment]
seriously.... why?

**Comment by dangayle** [comment]
Yeah, why was it removed? Was it because it could only be used on <code>a</code> tags? I really liked that justified button scheme, and I used it all over one of my websites.

**Comment by Studio384** [comment]
Would be great if this is added back, I miss the btn-group-justified class. It was a great UI for navigation.

**Comment by bassjobsen** [comment]
See http://stackoverflow.com/questions/34450586/justify-buttons-with-bootstrap-v4/34450587 about how to add the ` .btn-group-justified` class back into Bootstrap 4

**Comment by cvrebert** [comment]
@mdo Could you please explain your rationale here regarding the removal?

**Comment by stefanspicer** [comment]
Maybe there is a better way to do this with flex?  Is that the replacement?

**Comment by cvrebert** [comment]
Shouldn't be, since Flexbox is disabled by default in Bootstrap 4.

**Comment by Studio384** [comment]
So is this going to be readded again, or will it be left out?

**Comment by cvrebert** [comment]
Only @mdo can answer that.

**Comment by zakjan** [comment]
Solution at http://stackoverflow.com/a/39119031/1823988 works for me. Can you include it?

**Comment by socheth** [comment]
You can use like this

class="btn-group btn-group-toggle nav nav-fill"
