### ISSUE TITLE
Nuke bootstrap-server

### ISSUE THREAD

**Issue by ZDroid** [twbs/bootstrap#17632]
Will [twbs/bootstrap-server](https://github.com/twbs/bootstrap-server) repository ever be dropped? I think there is no need to keep it anymore.

Sorry if issue is too meta, I don't know where else to post it.

**Comment by mdo** [comment]
Nah, going to leave it (until/if we ever figure out how to do archived repos at GitHub) for now. No harm and the description mentions the current state of the repo.
