### ISSUE TITLE
Inputs are not un-rounded on iOS in v4

### ISSUE THREAD

**Issue by davidglenn** [twbs/bootstrap#17630]
Setting `$enable-rounded: false` doesn't remove rounded borders from `input` fields on iOS in v4. (tested on iOS 8 & 9 on iPhone 6)

![bootstrap](https://cloud.githubusercontent.com/assets/6709642/9932062/9f6578f6-5d38-11e5-8e80-f14f9dc574f5.png)

iOS rounds borders by default.

mixin only rounds when $enabled-rounded == true

````
@mixin border-radius($radius: $border-radius) {
  @if $enable-rounded {
    border-radius: $radius;
  }
}
````

So I guess this should be normalized in `_reboot.scss`?

**Comment by mdo** [comment]
Fixed with #17701.
