### ISSUE TITLE
[V4] popover destroy

### ISSUE THREAD

**Issue by tsm91** [twbs/bootstrap#17647]
[popover destroy](http://v4-alpha.getbootstrap.com/components/popovers/#popoverdestroy) is not working.

`Uncaught TypeError: data[config] is not a function`

**Comment by Johann-S** [comment]
Use ``dispose`` instead of ``destroy`` 

fixed documentation by https://github.com/twbs/bootstrap/commit/62199b96dc8f2b56ca46df2762e328442ce29157

**Comment by tsm91** [comment]
thanks
