### ISSUE TITLE
Tooltips in Bootstrap 4 aren't destroyed when their associated elements are

### ISSUE THREAD

**Issue by sdaitzman** [twbs/bootstrap#17641]
In Bootstrap 3, a tooltip initialized using attributes will go away when the associated element is removed from the DOM. In Bootstrap 4, the tooltip remains in place and cannot be hidden (unless you manually address it).

Should this issue be raised with Tether rather than Bootstrap?

**Comment by cvrebert** [comment]
Could you post a simple JS Fiddle demonstrating the problem?

**Comment by matt-hernandez** [comment]
@cvrebert I think these Fiddles show the problem.
Here is a fiddle using the latest V4 Dev files. There is a button that has a tooltip on hover and the button will be removed from the DOM after three seconds. When the button is removed, the tooltip remains.

V4: https://jsfiddle.net/a_matt_appeared/f0ajqebL/

However, this also happens in Bootstrap 3. Here is another fiddle with the same setup, only using BS 3 files.

V3: https://jsfiddle.net/a_matt_appeared/oq57m4mv/

I'm not sure how often this will come up in actual installations.

**Comment by Johann-S** [comment]
I think you have to destroy manually Tooltips in the same time of the button.
http://v4-alpha.getbootstrap.com/components/tooltips/#tooltipdestroy

**Comment by sdaitzman** [comment]
@matt-hernandez, thanks for getting to this before me :+1: 

@Johann-S you're right... oddly enough, in my app on Bootstrap 3 the tooltips were going away automatically. I'll look into this more.

**Comment by fat** [comment]
yeah this has never been the case - you've always needed to manually kill tooltips if they are active on destroy
