### ISSUE TITLE
Recursive call by _reboot.scss

### ISSUE THREAD

**Issue by mazarini** [twbs/bootstrap#17649]
Hi,
I have timeout (or memory if increase exec time)  problem using symfony / assetic / sass / bootstrap for release 3.5.5 and 4.0.0-alpha.

After some search about 4.0.0-alpha, it seems to be cause from a comment in _reboot.scss in line 46 : 
// `.class-name { @import "bootstrap"; }`).

To solve this, I just suppress the '@' :
// `.class-name { import "bootstrap"; }`).

It's look as saas execute @import in comment.

**Comment by cvrebert** [comment]
I cannot reproduce this with either Ruby Sass or libsass, which are the only Sass compilers that we support. Presumably you're using some other buggy Sass compiler.

**Comment by mazarini** [comment]
You're right, bootstrap is not the responsible of my bug.
 I use Ruby Sass but the bug come from Assetic (kriswallsmith/assetic) and append before calling Ruby Sass.
