### ISSUE TITLE
Height mismatch in input-group (button + textarea)

### ISSUE THREAD

**Issue by iliasch** [twbs/bootstrap#17654]
While using a simple button+textarea input-group I noticed that there is a height mismatch between the two elements, which only exists when using the default size. Using input-group-sm or input-group-lg works properly. Sample: https://jsfiddle.net/iliasch/rb71ng1p/

Looking into bootstrap.css I noticed that height and line-height are specifically defined for input-group-sm and input-group-lg, but not for input-group (default), so the inherited 'auto' height is probably the cause of the problem. Is there a reason why you don't set a specific height for the default size?

**Comment by twbs-lmvtfy** [comment]
Hi @iliasch!

You appear to have posted a live example (https://fiddle.jshell.net/iliasch/rb71ng1p/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 41, column 3 thru column 67: Duplicate ID ```` sample-button ````.
* line 43, column 2 thru column 53: Duplicate ID ```` sample-textarea ````.
* line 48, column 3 thru column 67: Duplicate ID ```` sample-button ````.
* line 50, column 2 thru column 53: Duplicate ID ```` sample-textarea ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by iliasch** [comment]
Removed unnecessary ids which were causing the validation errors.
https://jsfiddle.net/iliasch/rb71ng1p/

**Comment by twbs-lmvtfy** [comment]
Hi @iliasch!

You appear to have posted a live example (https://fiddle.jshell.net/iliasch/rb71ng1p/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 41, column 3 thru column 67: Duplicate ID ```` sample-button ````.
* line 43, column 2 thru column 53: Duplicate ID ```` sample-textarea ````.
* line 48, column 3 thru column 67: Duplicate ID ```` sample-button ````.
* line 50, column 2 thru column 53: Duplicate ID ```` sample-textarea ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by iliasch** [comment]
http://jsfiddle.net/iliasch/rb71ng1p/1/

**Comment by twbs-lmvtfy** [comment]
Hi @iliasch!

You appear to have posted a live example (http://fiddle.jshell.net/iliasch/rb71ng1p/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 36, column 2: [E006](https://github.com/twbs/bootlint/wiki/E006): `.input-group` contains a `<textarea>`; only text-based `<input>`s are permitted in an `.input-group`
* line 43, column 2: [E006](https://github.com/twbs/bootlint/wiki/E006): `.input-group` contains a `<textarea>`; only text-based `<input>`s are permitted in an `.input-group`
* line 50, column 2: [E006](https://github.com/twbs/bootlint/wiki/E006): `.input-group` contains a `<textarea>`; only text-based `<input>`s are permitted in an `.input-group`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
