### ISSUE TITLE
Bootstrap v4 - panel migration

### ISSUE THREAD

**Issue by squadwuschel** [twbs/bootstrap#17658]
Hi, 

I've used a lot of panels from v3 in my WebProjects, are there some easy migration steps to migrate from panels to the new cards feature.

I've also used a html table very often instead of the Body element from panels, but I've seen no example on the documentation that you will support this feature

like: 

        <div class="panel panel-default">
          <div class="panel-heading">Panel heading without title</div>
           <table class="table">
                 Table Content Here!
            </table>
            <div class="panel-footer">
             Panel Footer
            </div>
        </div>

**Comment by zacechola** [comment]
This is probably a better question for the Slack room or IRC, but there's a [migration page for v4](http://v4-alpha.getbootstrap.com/migration/). 

Panels have been dropped in favor of cards.

@mdo has said a few times  to think of moving to v4 less as a migration and more as a rewrite, as structure will change a bit, [but not all the much given your example](http://v4-alpha.getbootstrap.com/components/card/#header-and-footer ).

**Comment by cvrebert** [comment]
Panels => Cards in general is covered by http://v4-alpha.getbootstrap.com/migration/#components
Tables in cards is covered by #17395.
If you have more specific questions, let us know.
