### ISSUE TITLE
position:absolute inside a container > jumbotron

### ISSUE THREAD

**Issue by My1** [twbs/bootstrap#17657]
I am not sure whether it's bootstrap or anything else, but it might be worth a shot...

I have the wird problem that when I attempt to absolutely position an element (like a a.btn to a corner via position:absolute;top:0;right:0;) it does not position it relative to the jumbotron (its conaining element), but rather in relation to the whole page, which seems rather weird.

tested both in chrome and firefox

and to quote w3schools for at least the top property, pretty much the same for left-right and bottom.:

"For absolutely positioned elements, the top property sets the top edge of an element to a unit above/below the top edge of its containing element."

**Comment by patrickhlauke** [comment]
absolute positioning is always relative to the nearest positioned ancestor https://developer.mozilla.org/en-US/docs/Web/CSS/position

this is not a Bootstrap issue, but a basic CSS one. long story short: add `position:relative` to your `.jumbotron`, which then defines it as a positioned ancestor and any absolute positioning of elements inside it will be in relation to its bounding box.

**Comment by My1** [comment]
so every position except static (which seems to be the default) counts as position ancestor, right?

unrelated to bootstrap, seems like w3schools needs some further explanation upon that. I (and probably a lot of others use it as help) and it doesnt say that the static doesnt count.


thanks, this helped really much.
Best Regards by My1

**Comment by mdo** [comment]
For what it's worth, I'd recommend using the Mozilla Developer Network over W3C schools any day of the week :).

**Comment by My1** [comment]
but well the MDN page for "top" isnt any better then w3schools:

"For absolutely positioned elements (those with position: absolute or position: fixed), it specifies the distance between the top margin edge of the element and the top edge of its containing block."

https://developer.mozilla.org/en-US/docs/Web/CSS/top

so unless you know the error lies in position (which I didnt) this page wouldnt have helped me.
