### ISSUE TITLE
Flexbox Grid not working in Safari 8

### ISSUE THREAD

**Issue by LucasKA** [twbs/bootstrap#17666]
Safari Version: 8.0.8 (10600.8.9)

Steps to replicate: 

- Create a grid that has a row and more than just a col-xs-12 (For instance, a bunch of cards with (col-*-6).
- View in Safari, and all the columns render as full with column 12

Everything renders on Chrome no problem, and if you switch the flex box variable to false, everything renders on Safari correctly again.

I'd submit a JSBin, but I don't know an easy way to set one up with the Variables file. Is there an official Bootstrap one I can clone?

**Comment by cvrebert** [comment]
> I'd submit a JSBin, but I don't know an easy way to set one up with the Variables file.

For now, just copy-paste the non-minified CSS into JSBin's CSS box. And specify the exact version of Bootstrap you're using (i.e. the first Alpha release, or latest `v4-dev` branch commit).

**Comment by LucasKA** [comment]
@cvrebert Here's a JSBin ( http://jsbin.com/naloja/edit?output ), but not sure how you would enable flexbox with the default css, so what I did was compile the latest v4-dev branch Sass with the ```$enable-flex: true;```

Open the JSBin in Chrome, all dandy, open it in Safari, all full widths

And cause I love y'all here's some screenies:

#### Flexbox enabled chrome ####
![screenshot 2015-09-21 16 07 44](https://cloud.githubusercontent.com/assets/1824267/10007559/18e07196-607b-11e5-93e8-473e0f53cbed.png)

#### Flexbox enabled safari ####

![screenshot 2015-09-21 16 07 56](https://cloud.githubusercontent.com/assets/1824267/10007569/31e1ff20-607b-11e5-83a9-661506f40122.png)

**Comment by cvrebert** [comment]
Yep, that's what I was suggesting. Perfect! Thanks.

**Comment by VictorArgote** [comment]
I have found issues when using flexbox on Safari, some time ago I decided to use Bourbon mixin library, so far, after using the Bourbon mixins I have not experienced any problems with flexboxes on major browsers including Safari.

You can check here:

http://bourbon.io/docs/#flexbox
https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_flex-box.scss

Maybe It can helps.

**Comment by cvrebert** [comment]
Autoprefixer ought to make Bourbon-style vendor prefix mixins unnecessary.

**Comment by LucasKA** [comment]
@VictorArgote Thanks for the workaround, but this is something that should supposedly be working in the core of Bootstrap v4, so I'm not using the flexbox grid just yet, I'm using the standard grid for now.

**Comment by cvrebert** [comment]
This has been fixed in Safari 9:
<img width="1167" alt="saf-9-fixed" src="https://cloud.githubusercontent.com/assets/419884/11581793/e33e38de-99fa-11e5-9fcc-c43a85569839.png">
@mdo Do we have any interest in trying to fix this for Safari 8?

**Comment by slavanga** [comment]
Flexbox was unprefixed in Safari 9. Prefixes are still required for Safari 8 and older.
The example is just missing the -webkit prefixes that are normally added via Autoprefixer.

**Comment by cvrebert** [comment]
@slavanga Indeed. Good catch!
@LucasKA As mentioned in our docs, you need to setup [Autoprefixer](https://github.com/postcss/autoprefixer) yourself if you aren't using our Gruntfile to build Bootstrap.
