### ISSUE TITLE
Fallback position for Tooltip

### ISSUE THREAD

**Issue by heaven** [twbs/bootstrap#17669]
It would be cool to be able to specify position like: "right, bottom", so if right makes tooltip to appear off the screen it should try the next available position. At the same time "right bottom" position could specify the alignment. So basically it should be possible to do: "top right, bottom left".

**Comment by cvrebert** [comment]
Refs #17297, #12328.

**Comment by FezVrasta** [comment]
This is something that would be possible with #19673

**Comment by Johann-S** [comment]
Closed and fixed by #22444
