### ISSUE TITLE
Add size variations for dropdowns in v4

### ISSUE THREAD

**Issue by Dashed** [twbs/bootstrap#17667]
Same spirit as https://github.com/twbs/bootstrap/issues/17610. 

I'll need to apply `font-size` to resize the dropdown component to their respective button component (especially when it's resized from the default).

If the elements are buttons, I can workaround by applying `btn-lg` or `btn-sm`.

**Comment by mdo** [comment]
Similarly, no plans for this for content within dropdowns.
