### ISSUE TITLE
Scrollspy not working at all as per documentation

### ISSUE THREAD

**Issue by rasmuswoelk** [twbs/bootstrap#17679]
I'm having difficulties getting the scrollspy working in bootstrap 4.0.0.

Here is an example: http://pastebin.com/LJqUi4jX

I am using the bootstrap libraries from bootstraps own documentation directly. Also their own jquery version. In the bottom you can see the out-commented version of bootstrap3. If you activate it the scrollspy works.

I pretty sure I have done the (simple) installation correctly but I might be wrong. Anyone else having this issue?

**Comment by cvrebert** [comment]
Could you please make your example into a [JS Bin](http://jsbin.com/)? Thanks!

**Comment by rasmuswoelk** [comment]
Could not get it to work in JSBin, but heres a jsfiddle:

With bootstrap 3 (working)
http://jsfiddle.net/y0vp7z61/

With bootstrap 4 (not working)
http://jsfiddle.net/y0vp7z61/1/

All code is exactly the same in the two fiddles, except for the included bootstrap library in the footer.

**Comment by twbs-lmvtfy** [comment]
Hi @rasmuswoelk!

You appear to have posted a live example (http://fiddle.jshell.net/y0vp7z61/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 3 thru column 17: Stray doctype.
* line 32, column 1 thru column 6: Stray start tag ```` html ````.
* line 33, column 1 thru column 6: Stray start tag ```` head ````.
* line 34, column 9 thru column 15: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 35, column 1 thru column 22: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 35, column 1 thru column 22: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 36, column 1 thru column 53: Attribute ```` http-equiv ```` not allowed on element ```` meta ```` at this point.
* line 36, column 1 thru column 53: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 37, column 1 thru column 109: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 37, column 1 thru column 109: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 38, column 1 thru column 90: Element ```` link ```` is missing required attribute ```` property ````.
* line 39, column 1 thru column 7: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 49, column 1 thru column 7: Stray end tag ```` head ````.
* line 53, column 1 thru column 92: Start tag ```` body ```` seen but an element of the same type was already open.
* line 53, column 1 thru column 92: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @rasmuswoelk!

You appear to have posted a live example (http://fiddle.jshell.net/y0vp7z61/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 3 thru column 17: Stray doctype.
* line 32, column 1 thru column 6: Stray start tag ```` html ````.
* line 33, column 1 thru column 6: Stray start tag ```` head ````.
* line 34, column 9 thru column 15: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 35, column 1 thru column 22: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 35, column 1 thru column 22: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 36, column 1 thru column 53: Attribute ```` http-equiv ```` not allowed on element ```` meta ```` at this point.
* line 36, column 1 thru column 53: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 37, column 1 thru column 109: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 37, column 1 thru column 109: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 38, column 1 thru column 90: Element ```` link ```` is missing required attribute ```` property ````.
* line 39, column 1 thru column 7: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 49, column 1 thru column 7: Stray end tag ```` head ````.
* line 53, column 1 thru column 92: Start tag ```` body ```` seen but an element of the same type was already open.
* line 53, column 1 thru column 92: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rasmuswoelk** [comment]
Could not get it to work in JSBin, but heres a jsfiddle:

With bootstrap 3 (working)
http://jsfiddle.net/d2q9ysq0/1/

With bootstrap 4 (not working)
http://jsfiddle.net/d2q9ysq0/

All code is exactly the same in the two fiddles, except for the included bootstrap library.

**Comment by twbs-lmvtfy** [comment]
Hi @rasmuswoelk!

You appear to have posted a live example (http://fiddle.jshell.net/d2q9ysq0/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 46, column 3 thru column 94: Start tag ```` body ```` seen but an element of the same type was already open.
* line 46, column 3 thru column 94: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @rasmuswoelk!

You appear to have posted a live example (http://fiddle.jshell.net/d2q9ysq0/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 46, column 3 thru column 94: Start tag ```` body ```` seen but an element of the same type was already open.
* line 46, column 3 thru column 94: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rasmuswoelk** [comment]
Could not get it to work in JSBin, but heres a jsfiddle:

With bootstrap 3 (working)
http://jsfiddle.net/d2q9ysq0/2/

With bootstrap 4 (not working)
http://jsfiddle.net/d2q9ysq0/3/

All code is exactly the same in the two fiddles, except for the included bootstrap library.

**Comment by rasmuswoelk** [comment]
Any clues yet?

**Comment by ci2014** [comment]
I have to confirm, that scroll-spy, as already proved by rasmuswoelk, does not work at all in Bootstrap v4.0.0 alpha. His example is correct as documented. I assume that there is a problem in the JavaScripts themselves.

By now, I switched back to the latest Bootstrap 3.x JS-File.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by SirCmpwn** [comment]
I retract my :+1:, it works fine. I had a different problem.

**Comment by ci2014** [comment]
Are there any news to this issue? @cvrebert @rasmuswoelk

**Comment by cvrebert** [comment]
Both the [visual test](https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/visual/scrollspy.html) and the live example in the docs work fine in current `v4-dev` (eea6690d0e47b25a02bb42e610fde7e5ecd247d7)...

**Comment by cvrebert** [comment]
Demo which works and agrees with the v4 docs' instructions AFAICT:
https://jsbin.com/muyodi/edit?html,output
Happy to reopen this if you can point out any specific discrepancy between it and the docs.

> All code is exactly the same in the two fiddles, except for the included bootstrap library.

Bootstrap v4 isn't backward-compatible with Bootstrap v3, so it's unlikely that correct code would be exactly the same between the two versions. Migrating to v4 will most likely require changes; for example, the markup for the Nav component changed in v4.

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/muyodi/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 79, column 3 thru column 6: No ```` p ```` element in scope but a ```` p ```` end tag seen.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by SirCmpwn** [comment]
Somewhat related: #18163

**Comment by cvrebert** [comment]
@tiesont You are describing #14187.
