### ISSUE TITLE
Dependancies errors

### ISSUE THREAD

**Issue by dr-zekot** [twbs/bootstrap#17681]
GRUNT

Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'chalk'

fix : npm install --save chalk

Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'maxmin'

fix: npm install --save maxmin

Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'uglify-js'

not fixed with npm install uglify-js

**Comment by mdo** [comment]
I can't imagine what you're running into unless you haven't walked through the entire development setup as outlined in our project readme. You'll need to install all dependencies before running Grunt. If you've done that and are still having problems, consider nuking your `node_modules` directory and re-running those steps.

**Comment by dr-zekot** [comment]
Thanks Mark,

The problem is with uglify.All other dependancies are ok, I ran the install steps but something is wrong. I will re-run the install.
