### ISSUE TITLE
Redefining '$font-size-root' value adversely affects '.container' widths

### ISSUE THREAD

**Issue by dfross** [twbs/bootstrap#17686]
I am setting a sites `$font-size-root` to 14px when I noticed that the resulting width of `.container` reduced in size. BS4 declares `$font-size-root` to 16px, which directly affects elements using `.container` because they're based on rem values. So if the value of `$font-size-root` changes, it also changes a `.container`'s widths. This seems undesirable. To eliminate this problem I think the values defined in the `$container-max-widths` variable should be in px units rather than rem units.

**Comment by cvrebert** [comment]
X-Ref: #17403

**Comment by mdo** [comment]
No longer relevant with #17403.
