### ISSUE TITLE
custom download not including all collapse classes in css

### ISSUE THREAD

**Issue by alex-petrea** [twbs/bootstrap#17696]
After I've downloaded a custom bootstrap file the responsive navbar wasn't working properly. On mobile it will always be collapsed even if I would press the button the event was triggering and the links would still be visible.

Please note that I haven't deleted any navbar or navs components from the custom file. Here's the link to the custom file http://getbootstrap.com/customize/?id=01351100fa3d773cd4c1

I've found those classes missing from my custom file

```
.collapse {
  display: none;
}
.collapse.in {
  display: block;
}
tr.collapse.in {
  display: table-row;
}
tbody.collapse.in {
  display: table-row-group;
}
.collapsing {
  position: relative;
  height: 0;
  overflow: hidden;
  -webkit-transition-timing-function: ease;
       -o-transition-timing-function: ease;
          transition-timing-function: ease;
  -webkit-transition-duration: .35s;
       -o-transition-duration: .35s;
          transition-duration: .35s;
  -webkit-transition-property: height, visibility;
       -o-transition-property: height, visibility;
          transition-property: height, visibility;
}
```

**Comment by cvrebert** [comment]
Most probably you need to also check the "Component animations (for JS)" and/or "Transitions (required for any kind of animation)" checkboxes.
The Customizer's dependency information is incomplete to say the least.

**Comment by alex-petrea** [comment]
@cvrebert works like a charm :+1: 
"Component animations (for JS)" did the trick

**Comment by cvrebert** [comment]
Since we are now focusing on Bootstrap v4, the Bootstrap Core Team is no longer investigating non-critical issues in the Bootstrap v3 Customizer.
However, patches to fix such issues would be welcomed and we would gladly merge such patches; we just won't be writing any ourselves due to time/manpower constraints.
Thank you for your understanding.
