### ISSUE TITLE
Issues with border thickness on retina displays

### ISSUE THREAD

**Issue by abstractic** [twbs/bootstrap#17690]
There's an issue with border thickness on a retina display, especially if the root font size is less than 16 pixels.

![bootstrap-4-border-issue](https://cloud.githubusercontent.com/assets/2080809/10065846/015ba1f2-62b6-11e5-9589-1be901724d1c.png)

The problem seems to be related to the way pixels are divided into REM units, i.e. the border width is set to the default value of .0625rem, so if you take following measurements you will get these results.

16 x 0.0625 = 1 pixel
15 x 0.0625  = 0.9375 pixel
14 x 0.0625  = 0.875 pixel

A quick fix could be to calculate the border width based on a custom font size, not a fixed value of 16 pixels, as that might not be the suitable size for all types of web projects. Then you will always get a result that are dividable with a full pixel.

1 rem / 16 px = 0.0625 rem
1 rem / 15 px = 0.06666666666667 rem
1 rem / 14 px = 0.07142857142857 rem

The border thickness could be calculated via simple function.

```shell
$border-width:              rem-unit($font-size-root);
```

```shell
@function rem-unit($size) {
    
    $rem:  1rem / ($size / 1px);
    
    @return $rem;
}
```

**Comment by neilhem** [comment]
Issue has already been opened & solved, see https://github.com/twbs/bootstrap/commit/85f08df3b0b3c9b8c0cf625475a4ec66a809d968
