### ISSUE TITLE
Integrate Parker into the build process

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17705]
i.e. https://github.com/katiefenn/parker
By diffing a PR's CSS stats against the previous stats, we can get a warning if something causes the number of entities to explode.

See also: mdo's jQuery SF talk where he mentions similar tooling and graphs at GitHub
https://speakerdeck.com/mdo/at-mdo-ular-css?slide=41
https://speakerdeck.com/mdo/at-mdo-ular-css?slide=42

**Comment by cvrebert** [comment]
Or perhaps whatever generates http://www.basscss.com/stats/

**Comment by bardiharborow** [comment]
[CSSStats](http://cssstats.com/) (from mdo's jQuery SF talk) is interesting. The report for Bootstrap is [here](http://cssstats.com/stats?link=https%3A%2F%2Fraw.githubusercontent.com%2Ftwbs%2Fbootstrap%2Fv4-dev%2Fdist%2Fcss%2Fbootstrap.min.css&name=Bootstrap).
