### ISSUE TITLE
Remove pointer-events:none from .disabled

### ISSUE THREAD

**Issue by my8bird** [twbs/bootstrap#17703]
This issue directly relates to #14104 where by adding the the styling class `.disabled` buttons stopping working altogether.  While on the surface this change makes sense and the reasoning on the pull is not bad I believe this change should be removed for the following reasons

 1. Handling the click for a disabled button allows the developer to give the user valuable insight into why the button is disabled.
 1. `pointer-events` is a directive which controls behavior and not styling.  Behavior should be handled by Javascript.

On the first point I think it is valuable to provide feedback when a user clicks a disabled button so that they know why it is disabled.  Think a password change form where the two fields do not match.  When they click submit[1] we can give them the exact reason the form is invalid.  Additionally, this user interaction matches the behavior the user sees if the server needs to do a second level of validation which fails because that happens after clicking the submit button.

The second point is perhaps a little, or a lot, dogmatic.  CSS should change only the way the page looks.  It makes things bigger, smaller, flashier, move etc.  In my opinion, and I feel like it is a prevailing view point, CSS should not change the behavior of an element.  `pointer-events` is a case where CSS does change behavior by making the button not handle clicks.  It would be better to tell BS users to ignore events in JS if that is the behavior they want since this is a trivial problem.  I have this CSS / JS split so ingrained in my head (as I suspect others do) that I spent load of time trying to figure out why my button was not clickable after upgrading bootstrap.

As far as a road forward I would propose that `.btn.disabled` should allow events since `.btn[disabled]` already exists and will block events.

[1] Users might notice the button looks disabled but they are still going to click it the best we can do with styling is give the hints at the correct path :smile:

PS: I do apologize for the long issue description.  I thought about making it much shorter but was concerned the nuances would be lost and thus my reasoning.

**Comment by cvrebert** [comment]
Is this regarding Bootstrap v3, or v4? I think we're loath to have much more churn on this in v3 (given #16092, #16778).

**Comment by cvrebert** [comment]
>  I think it is valuable to provide feedback when a user clicks a disabled button so that they know why it is disabled.

To be fair, there's a trick to work around that: http://getbootstrap.com/javascript/#callout-tooltip-disabled
It is hacky though.

> As far as a road forward I would propose that .btn.disabled should allow events since .btn[disabled] already exists and will block events.

It blocks them for `<button>`s, but not for `<a>`s. `<a>`s have no `[disabled]` attribute (why god, why?!).

But yeah, `pointer-events:none` leaves a lot to be desired; e.g. it doesn't prevent keyboard users from "clicking" on the element.

**Comment by my8bird** [comment]
I am using v3 and can workaround the issue for our usage so a fix aimed at v4 would be fine.  I made the issue because others could hit it in the future and I wanted to save them the trouble

**Comment by mdo** [comment]
Thoughts on changes to pointer events, @patrickhlauke?

**Comment by cvrebert** [comment]
(FWIW, I agree with the OP that we should remove it.)

**Comment by patrickhlauke** [comment]
though conceptually i agree, the main problem i can see is that [1] requires developers to actually code their stuff properly to handle the case where a `click` was fired, but that it was on a disabled control. though i guess that if we didn't even try to prevent it, it would be fairly obvious to them during testing that they need to handle this correctly (plus adding extra text in the documentation to that effect, i.e. "this only makes the control appear to be disabled, it'll still work...so make sure you change your code accordingly".

however, this would also mean that any of bootstrap's own code needs to make sure it's not being called on a disabled control either.

as for the separation of concerns of [2], that train left the station a long time ago IMO (see also `touch-action` which breaks that presentation vs behavior membrane)

**Comment by mdo** [comment]
We're sticking with it for now then <3.
