### ISSUE TITLE
form-control disabled input background override issue

### ISSUE THREAD

**Issue by cosecantt** [twbs/bootstrap#17700]
Currently bootstrap has following form control disabled style
```
    .form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {
        background-color: #eee;
        opacity: 1;
    }
```
This does not override the custom background style given to `.form-control`. In my opinion above code should contain extra background style as:

```
    .form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {
       background : none;
       background-color: #eee;
       opacity: 1;
    }
```
In that case any custom background style is overridden by `background:none`

**Comment by cvrebert** [comment]
> This does not override the custom background style given to `.form-control`

@cosecantt What custom background style are your referring to?

**Comment by cvrebert** [comment]
Also, are you using Bootstrap v3, or v4?

**Comment by cosecantt** [comment]
I am using version 3.3.5. Custom means original boostrap overridden styles
in my app.css. If I override .form-control giving additional background
style, it also affects form-control disabled style. Therefore form-control
disabled style should have extra style like background:none.

**Comment by cvrebert** [comment]
IMHO, seems like you should handle that in your own CSS since you're the one adding the style causing the problem in the first place.
CC: @mdo

**Comment by mdo** [comment]
Yup, @cvrebert is on point there.

**Comment by Streusel** [comment]
Just a question, but was something done about this in version 3.3.6?
I've found that disabled and readonly take precedence to items such as btn-danger which surprised me a bit..
3.3.5 Allowed me to set a readonly or disabled with btn-danger and have that style apply while still disabling the actual element.

**Comment by cvrebert** [comment]
@Streusel This bug was/is invalid since it was caused by custom CSS added by the user. Using only Bootstrap's built-in styles, no bug manifested. Sounds like your issue isn't related to this one.
