### ISSUE TITLE
Use Page Visibility API to avoid cycling carousels when the page isn't visible

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17706]
Resurrecting #15566 for v4.

**Comment by igor-im** [comment]
@cvrebert Are you guys supporting IE9? As per MDN Page Visibility works IE10+

**Comment by cvrebert** [comment]
This feature would be implemented in a progressive enhancement fashion.

**Comment by cvrebert** [comment]
This was fixed in #17710.
