### ISSUE TITLE
Rename .btn-*-outline to .btn-outline-*

### ISSUE THREAD

**Issue by pinin** [twbs/bootstrap#17719]
health men, just my opinion
I think the class names for button style outline in v4, it should be following

```
... class="btn btn-outline-primary" ...
... class="btn btn-outline-secondary" ...
... class="btn btn-outline-success" ...
... class="btn btn-outline-warning" ...
... class="btn btn-outline-danger" ...
```

instead of

```
... class="btn btn-primary-outline" ...
... class="btn btn-secondary-outline" ...
... class="btn btn-success-outline" ...
... class="btn btn-warning-outline" ...
... class="btn btn-danger-outline" ...
```

that is not only a clearer, but can be used for example, another modification as

```
[class^='btn-outline-'],
[class*=' btn-outline-'] { ... }
```

which is not possible now

**Comment by cvrebert** [comment]
> that is not only a clearer, but can be used for example, another modification as
> ```
> [class^='btn-outline-'],
> [class*=' btn-outline-'] { ... }
> ```

I believe we're trying to avoid those sorts of selectors for performance and extensibility reasons.

**Comment by mdo** [comment]
Changed in #18772.
