### ISSUE TITLE
nav-pills inside a card-block doesn't maintain the card-height.

### ISSUE THREAD

**Issue by JochemKuijpers** [twbs/bootstrap#17711]
(bootstrap v4)

When placing a `nav-pills` list of links inside a `card-block`, the card doesn't maintain the required height.

This problem does not occur with any of the other lists so I think it's unintended behaviour. 

[Example of nav-pills](http://jsbin.com/navevorofo/edit?html,output)

[Example of nav-tabs](http://jsbin.com/hupovovilu/edit?html,output)

[Example of base nav](http://jsbin.com/johoqemelu/edit?html,output)

As you can see, only `nav-pills` has unintended behaviour. In case anything happens to the hosted code examples, here's a screenshot and the core part of the code to re-create this issue.

	<div class="card">
		<div class="card-block">
			<ul class="nav nav-pills">
				<li class="nav-item">
					<a class="nav-link active" href="#">navlink 1</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">navlink 2</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">navlink 3</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">navlink 4</a>
				</li>
			</ul>
		</div>
	</div>

![](https://cloud.githubusercontent.com/assets/1162720/10120685/c40aff36-64c8-11e5-9d01-1cce8f851862.png)

**Comment by chrisbell08** [comment]
This has been fixed in the below pull request: https://github.com/twbs/bootstrap/commit/49379fd5f7fff0dbc88305c6a627f1f0351327ce
