### ISSUE TITLE
Task "sass:core" not found.

### ISSUE THREAD

**Issue by saturnast** [twbs/bootstrap#17721]
While i'm running the task use 'grunt dist', i got a warning that 'Warning: Task "sass:core" not found. Use --force to continue.', then the task aborted, Could anybody tell me why? Thank you.

The branch is v4-dev.

**Comment by mdo** [comment]
I imagine you don't have all the dependencies installed—double check you've got the latest with a fresh `npm install` and `bundle install` (I think we're on Bundler now).

**Comment by cvrebert** [comment]
See https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/build-tools.md#tooling-setup

**Comment by saturnast** [comment]
@mdo thank you very much. 

I have tried `npm install` and `bundle install`, but it still does not work, error massage is blow:

`Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found in /Users/saturn/Documents/github/bootstrap/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node. Try reinstalling `node-sass`?

Running "clean:dist" (clean) task
>> 1 path cleaned.
Warning: Task "sass:core" not found. Use --force to continue.

Aborted due to warnings.`

I tried `npm install node-sass`, but the error message comes again.

I think it may because my npm is not working right, i'll try google it first.

Thank you.

**Comment by saturnast** [comment]
@cvrebert Thank you. i try `grunt dist`.

**Comment by saturnast** [comment]
@mdo I remove the node_modules and run `npm install` again, and the error fixed, thanks.
