### ISSUE TITLE
Bootstrap 4 Template Overflow Issue

### ISSUE THREAD

**Issue by gncstudios** [twbs/bootstrap#17724]
Hello Bootstrap, I was browsing your templates and noticed a bug. It looks like width of the the image pulled the text content out of the container panel behind it.

This only happens if you resize the window to be the size of mobile and then drag it large again.

When the page first loads in desktop view, the image looks fine.

Browser Firefox 31.8.0
Windows 7 64-bit

![tempateoverflow](https://cloud.githubusercontent.com/assets/4097685/10145944/01b4e636-65db-11e5-97d4-5b579ccb6c11.png)

**Comment by cvrebert** [comment]
Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
* Please **do not** open issues regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`.

Thanks.
