### ISSUE TITLE
.hidden-*-up classes

### ISSUE THREAD

**Issue by ucitelot** [twbs/bootstrap#17731]
Those classes are more efective,
.hidden-*-up .hidden-*-down

so is there option to add them on bootstrap v3 ?

**Comment by cvrebert** [comment]
Bootstrap v3 is now in maintenance mode and is no longer accepting new features.
However, you can always copy the relevant code from v4, tweak it a bit, and put in it your local copy of Bootstrap. The general technique isn't intimately tied to v4, it can be made to work with v3.
