### ISSUE TITLE
Alpha Bootstrap 4 _carousel.scss missing webkit transition?

### ISSUE THREAD

**Issue by aicragellebasi** [twbs/bootstrap#17738]
Hi,
I am using sass and I had issues with the slider on devices. The transitions were not working. So doing some research I came across this thread https://github.com/twbs/bootstrap/issues/14973 and found my answer. The _carousel.scss was missing a few rules around lines 24 

Here is the original _carousel.scss:

```
   // WebKit CSS3 transforms for supported devices
    @media all and (transform-3d), (-webkit-transform-3d) {
      transition: transform .6s ease-in-out;
      backface-visibility: hidden;
      perspective: 1000px;

      &.next,
      &.active.right {
        left: 0;
        transform: translate3d(100%, 0, 0);
      }
      &.prev,
      &.active.left {
        left: 0;
        transform: translate3d(-100%, 0, 0);
      }
      &.next.left,
      &.prev.right,
      &.active {
        left: 0;
        transform: translate3d(0, 0, 0);
      }
    }
```

Here's how I edited it and the slider is now working:

```
// WebKit CSS3 transforms for supported devices
    @media all and (transform-3d), (-webkit-transform-3d) {

      -webkit-transition: -webkit-transform .6s ease-in-out;
        -o-transition:      -o-transform .6s ease-in-out;      
          transition: transform .6s ease-in-out;

      -webkit-backface-visibility: hidden;    
          backface-visibility: hidden;

      -webkit-perspective: 1000px;
          perspective: 1000px;

      &.next,
      &.active.right {
        left: 0;

        -webkit-transform: translate3d(100%, 0, 0);
          transform: translate3d(100%, 0, 0);
      }
      &.prev,
      &.active.left {
        left: 0;

        -webkit-transform: translate3d(-100%, 0, 0);
          transform: translate3d(-100%, 0, 0);
      }
      &.next.left,
      &.prev.right,
      &.active {
        left: 0;

        -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
      }
    }
  }
```
Hope this can help others and that the Bootstrap 4 developers will include it soon...

**Comment by cvrebert** [comment]
In v4, we rely on [Autoprefixer](https://github.com/postcss/autoprefixer) to add vendor prefixes, so no changes to `_carousel.scss` are necessary.
[The Download page](http://v4-alpha.getbootstrap.com/getting-started/download/) mentions that Autoprefixer is required, and our Gruntfile integrates Autoprefixer.

**Comment by aicragellebasi** [comment]
I see. Sorry I missed that part. Just recompiled using the Autoprefixer and it works like a charm. Forgive my ignorance... Thanks.

**Comment by Hamlet89** [comment]
It's possible use Autoprefixer without node.js? If yes so how can I do that?

**Comment by cvrebert** [comment]
Not to my knowledge.
Also, please refrain from necroposting in the future. Thanks.
