### ISSUE TITLE
unattached modal not removed from dom on hide.

### ISSUE THREAD

**Issue by tonywestonuk** [twbs/bootstrap#17732]
If a modal that is not already part of the DOM is shown, it is added to the DOM as part of the .model('show') method.   It is however not removed from the DOM afterwards. Just hidden.

var $dialog = $(Mustache.render(...))
$dialog.modal('show')

the $dialog is added to the DOM, and shown as required. There is no code to remove it from the DOM after the modal is no longer required.  The result of this is that repeated invokes of the above code will result in a memory leak, with the DOM littered with previous incarnations of modals that are no longer required.

a work around can be to add a listener to use a listener to remove the dialog from the DOM, Though I think if bootstrap added it to the DOM, then bootstrap should remove it from the dom afterwards.

  $dialog.on('hidden.bs.modal', function () {$(this).remove()})

For an example of this, check here.  Launch the modal, right click inspect element. Close the modal, reopen it.

http://jsfiddle.net/timbonicus/6rMtv/1/

**Comment by cvrebert** [comment]
We probably should throw an exception when trying to show a modal that's not part of the DOM and unambiguously make it the caller's responsibility to insert/remove transient modals from the DOM as necessary, but we likely can only make such a change in Bootstrap v4 due to backward compatibility constraints.

**Comment by tonywestonuk** [comment]
To be honest, when I would like to show a rendered popup. As a user of bootstrap, I would rather put:
			 popup = $(Mustache.render(template[0],data[0]));	
			 popup.modal('show');

than:
			 popup = $(Mustache.render(template[0],data[0]));	
			 $(document.body).append(popup);
			 popup.on('hidden.bs.modal', function () {$(this).remove()});
			 popup.modal('show');

the latter being a bit noisy...
 
Maybe a compromise.  If you do change the code to throw an exception, could you also add an additional parameter that will handle the adding and removing the modal from the dom, if set to true? 

popup.modal('show',true)   

Thanks.

**Comment by cvrebert** [comment]
> the latter being a bit noisy...

Yes, but auto-removing the modal from the DOM breaks modals whose markup is static (which is very common) or which are templated into the DOM, by making it impossible to show/hide them multiple times without regenerating their markup.

It's a teeny bit more code (OMG, 2 whole lines!) in your case, but the code is straightforward and easy to extract into a reusable function.

> could you also add an additional parameter that will handle the adding and removing the modal from the dom, if set to true?

Personally, I'd be somewhat against that, in keeping with the KISS principle. I'm betting folks would, as a follow-up to the proposed feature, say "But now I need a callback so I can un-register the removed modal from $SOME_JS_FRAMEWORK's system", so we'd have to fire a `remove.bs.modal` event to accommodate those folks, etc...
The cure seems worse than the disease, in terms of maintenance cost.

---

But these JS decisions are really up to @fat. I'm just dropping in my 2¢.

**Comment by tonywestonuk** [comment]
I'll add my 2¢ also!

Lines 79, to 81 of modal.js:

   if (!that.$element.parent().length) {
        that.$element.appendTo(that.$body) // don't move modals dom position
      }

If just the following is added, this should remove the element on hide, but only if it was actually added by bootstrap.

that.$element.on('hidden.bs.modal', that.$element.remove());

So, static, and templated modals should continue to work as before. 

But, hey, its your framework!... Im happy whatever you decide.!

Thanks.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by cvrebert** [comment]
Reopening since this also has the v4 label.

**Comment by mdo** [comment]
Reading through this, I think we'll punt on making any changes here and allow folks to clean these modals up themselves as they need to.
