### ISSUE TITLE
Full screen button don't work in bootstrap modal with html5 video

### ISSUE THREAD

**Issue by leetas** [twbs/bootstrap#17730]
Hello,
Here is my code example:
`<div class="modal fade bs-example-modal-lg" id="modal-video">`
`<div class="modal-dialog modal-lg">`
`<div class="modal-content">`
`<div class="modal-header">`
`<h4 class="modal-title text-center" id="video-modal-title">
</h4> `
`</div> <!-- .modal-header -->`
`<div class="modal-body">`
` <video src="http://v2v.cc/~j/theora_testsuite/320x240.ogg" controls>
                    Your browser does not support the <code>video</code> element.
                </video>`
`</div> <!-- modal-body -->`
`</div> <!-- .modal-content -->`
`</div> <!-- .modal-dialog -->`
`</div> <!-- #modal-delete.modal.fade -->`

When I push the 'fullscreen' button video appears briefly and disappears.

**Comment by leetas** [comment]
Problem solved. 
Modal transfer the upper div.

**Comment by cvrebert** [comment]
In the future, please ask troubleshooting questions on StackOverflow instead of this bug tracker. Thanks!
