### ISSUE TITLE
Consider switching to clipboard.js

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#17736]
It's IE9+ so we should be OK.

https://github.com/zenorocha/clipboard.js

**Comment by mdo** [comment]
Lack of Safari support kinda sucks.

**Comment by bhamodi** [comment]
Agreed @mdo.

**Comment by XhmikosR** [comment]
@mdo @cvrebert @hnrch02: do you know of any alternative solutions that doesn't use Flash?

**Comment by XhmikosR** [comment]
BTW @mdo from its docs

>Although copy/cut operations with execCommand aren't supported on Safari yet (including mobile), it gracefully degrades because Selection is supported.

**Comment by hnrch02** [comment]
> Lack of Safari support kinda sucks.

It falls back to a "Press CMD+C to copy" mode in Safari though and Flash isn't supported in Safari anyway (unless the user has installed it globally).

**Comment by hnrch02** [comment]
+ :100: on switching.

**Comment by patrickhlauke** [comment]
+1

**Comment by bhamodi** [comment]
Based on the safari workaround mentioned above, I'd also support removing Flash. :+1:

**Comment by zenorocha** [comment]
@mdo have you seen in action how it gracefully degrades on Safari? I think it's a pretty good trade-off when comparing to ZeroClipboard's 30kb minified JS + Flash

**Comment by XhmikosR** [comment]
Can you check the PR I made for this and suggest any improvements for the
JS part?

**Comment by zenorocha** [comment]
There's a lot of work to be done on that PR @XhmikosR. Can't really help at this moment because of all the attention that this clipboard.js is having. But I'll make sure to revisit this in a near future.

**Comment by zenorocha** [comment]
I've just updated the other PR and I'm pretty satisfied with the result.

Here's how it works on Chrome, Opera, Firefox, and Internet Explorer 9+:

![supported](https://cloud.githubusercontent.com/assets/398893/10467002/41da0480-71ac-11e5-8c7e-8287821d9a84.gif)

And here's how it works on Safari:

![not supported](https://cloud.githubusercontent.com/assets/398893/10467009/4d0a7218-71ac-11e5-8fbd-e8cadae87802.gif)

By accepting #17751 you'll be dropping dependency from Flash and saving 30kb on every request.

**Comment by XhmikosR** [comment]
Thanks a lot! I'll take care of it asap.
