### ISSUE TITLE
Request: Create a JS Style Guide

### ISSUE THREAD

**Issue by bhamodi** [twbs/bootstrap#17743]
I was planning on doing a big JavaScript refactor but I'm holding off because I'm not sure what style of JavaScript is followed in this repository.

I've seen different styles in different parts of the repository. For example, the JavaScript style used in the `grunt` directory is different from the style that I'm seeing in the `js/tests` directory.

I would be willing to help standardize the style and cleaning up all the JavaScript files. :+1:

**Comment by cvrebert** [comment]
There are ESLint and JSCS configurations in https://github.com/twbs/bootstrap/tree/v4-dev/js
In v4, the client-side JS uses ES6.
The Grunt tasks use ES5 for Node.js compatibility, and semicolons for sanity and because Jacob doesn't own them.

**Comment by bhamodi** [comment]
I haven't checked in for a long time. Are there any action items for this issue, or has this been resolved now?

**Comment by mdo** [comment]
Closing as stale—I don't think anyone has an intention to create this on the core team right now.
