### ISSUE TITLE
 Cannot set property 'bsTransitionEnd' of undefined

### ISSUE THREAD

**Issue by atul221282** [twbs/bootstrap#17744]
I get this error in Chrome-Version 45.0.2454.101 m and IE 11 on load

I am using Bootstrap v3.3.5 (http://getbootstrap.com) and JQuery jquery-2.1.4

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by atul221282** [comment]
I have created this fiddle https://jsfiddle.net/rf3tezqt/1/ . One more thing if u view the navbar on smaller screen u will find the toggle right button doesn't work

**Comment by twbs-lmvtfy** [comment]
Hi @atul221282!

You appear to have posted a live example (https://fiddle.jshell.net/rf3tezqt/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 36, column 5 thru column 11: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 38, column 1 thru column 7: Stray end tag ```` head ````.
* line 39, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 77, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 67, column 5 thru column 40: Unclosed element ```` div ````.
* line 79, column 1 thru column 7: Stray end tag ```` body ````.
* line 79, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
> Cannot set property 'bsTransitionEnd' of undefined

I'm unable to reproduce such an error with the given fiddle.

(Also, the "HTML" pane of JS Fiddle gets shoved into the `<body>` of the result, so it's not valid to have a `<head>` (or an outer `<body>`) tag in there.)

Odds are there is some error in your page rather than in Bootstrap itself. Try asking your question [on StackOverflow.](http://stackoverflow.com/questions/tagged/twitter-bootstrap-3) Thanks!

**Comment by ma3310** [comment]
meet same error with zeptojs library, once switch to jQuery 1.12.x, error disappears.

**Comment by cvrebert** [comment]
Zepto isn't supported, so that makes perfect sense.
