### ISSUE TITLE
#12683 in 3.2.0 causes regression for collapsed accordion bottom borders

### ISSUE THREAD

**Issue by gillius** [twbs/bootstrap#17740]
In Bootstrap 3.2.0, the fix for #12683 removed overflow: hidden from .panel when in .panel-group. This CSS was preventing panel-header's background from overflowing out of the collapsed according header. This is visible on http://getbootstrap.com/javascript/#collapse-example-accordion today, but it is hard to see because the default border radius is small:
![borders-default](https://cloud.githubusercontent.com/assets/1524332/10195944/44f34440-675e-11e5-9e18-b9e8760b2795.png)

When the border-radius is modified to be bigger (10px), it is a lot more noticeable:
![borders-big](https://cloud.githubusercontent.com/assets/1524332/10195945/44f51928-675e-11e5-9c61-50559adde4b9.png)

When setting overflow: hidden, the panel-header leak is fixed.

It is possible to fix the top border without overflow: hidden, by setting border-top-left/right-radius to equal the panel's border-radius. But there is no class change at panel-header or above to write CSS to fix the bottom radius only when collapsed (the collapsed class is put on the panel body, not the header or panel itself).

For my application, because I am using Angular, I could easily place a class on the panel when panel is collapsed that sets panel-header's border-bottom-left/right-radius to match panel's. However, since I'm not affected by #12683, I've reverted to 3.1.x style by just setting overflow: hidden, which works perfectly for us, but I wanted to file this issue since it exists in stock Bootstrap.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
