### ISSUE TITLE
Tooltip/Popover container option is not implemented

### ISSUE THREAD

**Issue by BenjinYap** [twbs/bootstrap#17755]
V4 documentation shows the container option exists but it is not actually implemented in the code.
http://v4-alpha.getbootstrap.com/components/tooltips/#options
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L28

Also found 2 unit tests which attempt to use the option even though it is not implemented.
https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/unit/tooltip.js#L331
https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/unit/tooltip.js#L661

**Comment by tim-peterson** [comment]
I'd like to contribute to this module, but can anyone summarize why just copy/pasting the v3 code wasn't done?

**Comment by amites** [comment]
issue seems to be 

https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L275

I'm gonna make a fork and see if I can time box a fix

**Comment by amites** [comment]
I'm out of time to hack on this -- it's not a simple issue given the Tether dependency

- changing the `appendTo` is ignored 
- moving when `appendTo` is triggered also ignored
- moving after creation gets real hacky and doesn't display correctly (this is where I stopped)

happy to share notes with anyone that picks up this ticket

**Comment by andyexeter** [comment]
Has there been any movement on this issue? Seems to have gone a bit quiet but the `container` option still isn't even in the source code for popover.js or tooltip.js in v4.0.0-alpha.4

**Comment by lekkerduidelijk** [comment]
@andyexeter I also bumped into this issue right now with the same findings as you. Too bad there is no fix available for this yet.

**Comment by andyexeter** [comment]
@lekkerduidelijk hopefully two people bumping the issue will create a bit of movement on it :)

@amites when you say "changing the `appendTo` is ignored" what do you mean? If you change the `appendTo` to `document.getElementById('my-id')` and not `document.body` it still uses the body as the container?

**Comment by andyexeter** [comment]
I wasn't experiencing the issue @amites was seeing with the `appendTo` being ignored. I've submitted a PR (#20725) but one of the tests is failing at the moment because it's passing an element to the the `container` option instead of a `string` or `boolean`. Just waiting on feedback before I either update the test, or update the docs/code to accept an element.

**Comment by andyexeter** [comment]
Hmm, looks like I spoke to soon. Setting the container to certain elements works fine, but with others it gets thrown back out to the body as soon as `this._tether` is set. Going to have a look through the Tether source code and see if I can find any clues there.

**Comment by andyexeter** [comment]
Ok, so I had a look through the Tether source code and read [this PR](https://github.com/HubSpot/tether/pull/98) and I know what's going on now.

Tether moves the popover/tooltip to the body if the `container`'s position property is not `static`. I guess there just needs to be a mention of this added to the docs for the option.

**Comment by mdo** [comment]
Closed with manual merge of #20725.

**Comment by iijak** [comment]
> Tether moves the popover/tooltip to the body if the `container`'s position property is not `static`.

@andyexeter is right.
But I found out that all parent nodes of the `container` must be `static` too.
If at least one of them is not `static` it will cause the popover/tooltip will be appended the `body` element.

**Comment by tournyguy** [comment]
I gave all divs a position of static and it still is not being contained correctly.
