### ISSUE TITLE
v4: hidden-xs-down mismatch with hidden-sm-up

### ISSUE THREAD

**Issue by wnr** [twbs/bootstrap#17757]
There's one pixel between xs-down and sm-up that makes the following case not working as expected:

```
<div class="hidden-xs-down hidden-sm-up">...</div>
```

Expected is that the div will never be visible.

If font size is 16px, the div will be visible at 543 px.
```
sm: 16*33.9 = 542.4 px
sm: 16*34 = 544 px
```

This same error occurs with ```hidden-sm-down hidden-md-up```, etc.

**Comment by cvrebert** [comment]
As of #17403, we now use pixels instead of ems, which should fix this problem.
Please re-test against current the `v4-dev` branch. Happy to reopen this if some variation of the problem still exists.
