### ISSUE TITLE
Add aria-label to Icons w/o Accompanying Text

### ISSUE THREAD

**Issue by loganfranken** [twbs/bootstrap#17752]
Hey there!

We've been exploring accessibility standards at the University of California, Santa Barbara Web Standards Guide (https://github.com/ucsb-wsg/ucsb-wsg.github.io/issues/31), specifically the use of **icon fonts with screen readers**.

In an **example with accompanying text**, like the following from the docs (http://getbootstrap.com/2.3.2/base-css.html#icons):

```html
<i class="icon-star"></i> Star
```

This isn't an issue as "Star" would get read by a screen reader, but the **following example (also from the docs) is problematic**:

```html
<a class="btn" href="#"><i class="icon-align-left"></i></a>
```

As a user with **a screen reader has no way to know this is a left alignment button**.

This is a pretty easy fix; you can just pop an `aria-label` on there:

```html
<a class="btn" href="#" aria-label="Left Align"><i class="icon-align-left"></i></a>
```

Any concerns with me submitting a pull request to include `aria-label` in the docs in cases where an icon is used *without* accompanying text? Should I also include a small bit of text explaining why this is the case or does the attribute explain itself?

**Comment by cvrebert** [comment]
The example you cite is from the Bootstrap v2 docs. Bootstrap v2 is no longer maintained at all.
Do you have any examples from the Bootstrap v3 or v4 docs?

**Comment by patrickhlauke** [comment]
That example is from the documentation for Bootstrap 2.3.2 ... so quite outdated and not maintained anymore. Documentation for the current version should not have any of those issues.

--
Patrick H. Lauke

**Comment by loganfranken** [comment]
You're totally right! I'm so sorry for the noise! Thank you so much for your work on this and for the quick reply!
