### ISSUE TITLE
Carousel with Drag and Swipe support

### ISSUE THREAD

**Issue by kirantheprince** [twbs/bootstrap#17750]
Carousel should be able to be dragged and swiped on the Touch devices. This seems to be a important and extremely serious issue right now with the carousel. It  is to be include in the next version atleast.

**Comment by starise** [comment]
Since you're talking about it, Carousel should be deprecated imho. There are much more powerful and flexible plugins out there with its purpose that it looks just a waste of space in the code to me.

**Comment by cvrebert** [comment]
This is already on the v4 roadmap (#17021):
> ## Carousel
> * Swipe support #8907 and #12881

**Comment by zacechola** [comment]
Also a dupe of #17118

**Comment by odahcam** [comment]
I agree with @starise, a carousel is a too big JavaScript feature to be written inside Bootstrap. (imho)
