### ISSUE TITLE
Tab plugin should use a class selector instead of a ul tag selector

### ISSUE THREAD

**Issue by Invis1ble** [twbs/bootstrap#17754]
Hello. I want to use `<ol>` instead of `<ul>`, but in the `Tab` plugin tag name is hardcoded.
https://github.com/twbs/bootstrap/blob/master/js/tab.js#L28
```js
var $ul      = $this.closest('ul:not(.dropdown-menu)')
```

**Comment by cvrebert** [comment]
>  I want to use `<ol>` instead of `<ul>`

Why?

**Comment by Invis1ble** [comment]
Because I have an ordered list.

**Comment by cvrebert** [comment]
> Because I have an ordered list.

And you have an ordered list because...?

**Comment by Invis1ble** [comment]
> And you have an ordered list because...?

Because it is a ordered dataset from database and it should be displayed as an orderd list of tabs. It is semantic, isn't it?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
