### ISSUE TITLE
[v4] Cards in card-columns will sometimes wrap

### ISSUE THREAD

**Issue by zfrenchee** [twbs/bootstrap#17762]
Not entirely sure why this is happening. Seems like this shouldn't be a problem because of display: inline-block, but it's causing some strange UI bugs for us. 

<img width="1317" alt="screen shot 2015-10-02 at 6 33 49 pm" src="https://cloud.githubusercontent.com/assets/2761597/10259674/d34b518e-6938-11e5-8350-5c1db833a831.png">

**Comment by cvrebert** [comment]
In what browser(s)?
And please post a JS Fiddle or JS Bin of your example. We can't really debug screenshots.

**Comment by cvrebert** [comment]
Also, is flexbox enabled or disabled?

**Comment by arashataei** [comment]
it is up to your content of each cols. it is responsive in each columns.

**Comment by zfrenchee** [comment]
Fixed this by adding display: inline-block to .card-block
