### ISSUE TITLE
Form validation styling applies to .help-block instead of .text-help

### ISSUE THREAD

**Issue by AntonCooper** [twbs/bootstrap#17768]
Documentation says that .text-help will have styling applied when parent element has .has-warning, .has-error, or .has-success. However this isn't happening. Looks like the styling is applied to V3s .help-block instead. Docs also say that 'No official help text classes exist in Bootstrap 4 (previously we had .help-block in v3),'

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by cvrebert** [comment]
@mdo Ping.

**Comment by mdo** [comment]
Fixed with #18089.
