### ISSUE TITLE
external css file

### ISSUE THREAD

**Issue by tangoone** [twbs/bootstrap#17764]
When I use a external css file for my custom styles I have the problem that the site is no longer "responsive". 

Can someone please tell me why, or how do I add custom styles to my site or is inline css the onlyway. ?

**Comment by arashataei** [comment]
you should add your code/s inside of bootstrap and by using main format of main class you wanna add a feature to it to work costumized to you site.

**Comment by cvrebert** [comment]
Closing as this sounds like a bug in your custom styles rather than in Bootstrap itself.
Try asking personal support questions like this on StackOverflow (or similar).
Thanks.
