### ISSUE TITLE
change col-md-x mode to col-md-x.y mode in Bootstrap

### ISSUE THREAD

**Issue by arashataei** [twbs/bootstrap#17767]
hi developers,
I suggest whay we cant set width of columns of a page in e.g. col-md-1.5    .
In this web development world we need all these setting for workspace and I need this oe for my work in my office .
pls, accept this and answer to me what is your answer about it?

**Comment by arashataei** [comment]
I mean width of <div> in mode width="1.5" . I need to have this style for my sites .

**Comment by arashataei** [comment]
I mean width of "<div>"

in mode <font color="red">width="1.5"</font> . I need to have this style for my sites

**Comment by cvrebert** [comment]
So, you're suggesting fractional column widths? If not, please explain what the `x.y` is supposed to mean/do.

**Comment by arashataei** [comment]
I meant width="x.y px" . It is like e.g. width="1.5 px" . I need this format for my carousal web site.

**Comment by arashataei** [comment]
and if you want me to help in this v4-bootstrap project to help, I can do it. If you want to add help me by documentations and I will add this feature to active this kind of width attribute in current width of bootstrap v 3.0.

**Comment by arashataei** [comment]
Now we have <code>col-md-x</code> and I wanna it to change in this mode : <code>col-md-x.y</code> .
In this mode I think all the developers are able to be responsive in setting page columns and it will help to create this kind of sink pages.

**Comment by neilhem** [comment]
Bloating bootstrap css with rarely used classes is not good idea.

**Comment by cvrebert** [comment]
Thanks, but don't think we'll implement this. It doesn't really jive with the paradigm of the rest of the grid system.

**Comment by arashataei** [comment]
Now, we cant set the width of columns our page style in bootstrap to for example 1.6 px or any scales in this format :  <code> <div class="col-md-1.5></dive></code>.  I suggest to use this code I gave u as example....  
. 
. 
. 
But, I will change what ever I want in bootstrap v3.0 and will upload it on a new repository on my account.  U will see what I mean after uploading changes. 
. 
. 
. 
As I say, now on current bootstrap we have : class="col-md-5" and I need all scales.  For example I need to have 3 columns in one row of my page with this scales : 1.5,  3.4 and 5.6.  How can set my page by these scales?  It is verysimple question I ask. 

Any way, ........  Arash Ataei,  software engineer at Ertebat co.

**Comment by cvrebert** [comment]
> `1.6 px` or any scales

What do you mean by `1.6px` here? A column less than 2 pixels wide is absurd, so I assume there's some miscommunication here.

**Comment by cvrebert** [comment]
Possible X-Ref: #17524

**Comment by arashataei** [comment]
Ok Igot it, it's not necessary now, But I will add a col-?-?.? into my
custom style close by bootstrap style and merge them togeter when ever I
need .

tnx, Arash Ataei

Libra
