### ISSUE TITLE
Error: ".col-xs-1" failed to @extend "%grid-column-float-xs".

### ISSUE THREAD

**Issue by ergov2015** [twbs/bootstrap#17779]
Error: ".col-xs-1" failed to @extend "%grid-column-float-xs".
       The selector "%grid-column-float-xs" was not found.
       Use "@extend %grid-column-float-xs !optional" if the extend should be able to fail.
        on line 33 of C:/wamp/www/bootstrap-4/scss/mixins/_grid-framework.scss
  Use --trace for backtrace.

**Comment by cvrebert** [comment]
Duplicate of #17046. Please search more next time.
