### ISSUE TITLE
Add Famous Social Networking site icons in Glyphicons

### ISSUE THREAD

**Issue by shanksdev** [twbs/bootstrap#17772]
While i was working on a project, just thought it would be great to have few famous icons for social networking sites such as Facebook, Google plus, Twitter etc. What say ?

**Comment by patrickhlauke** [comment]
As glyphicon support is being dropped in version 4, this is unlikely to happen I'm afraid. Additionally, in version 3 we rely on using the free glyphicon set, so any requests for additional glyphs should be directed to http://glyphicons.com/
