### ISSUE TITLE
Variables for components line-height seem to be erroneous

### ISSUE THREAD

**Issue by kitsguru** [twbs/bootstrap#17776]
in _variables.scss starting around line 180, it indicates that the values are bases on 14px text and line height of 1.428

Yet the defaults are 16px and 1.5 respecitively.

It would imply that the lg and sm line heights should be adjusted as the lg would be 1.3333 which is smaller than the default and sm 1.5 the same as the default.

````
// Components
//
// Define common padding and border radius sizes and more. Values based on 14px text and 1.428 line-height (~20px to start).

$line-height-lg:         (4 / 3) !default;
$line-height-sm:         1.5 !default;
````

**Comment by mdo** [comment]
Fixed in 60ad55b.
