### ISSUE TITLE
Link to "Narrow jumbotron" on v4 Examples docs 404s

### ISSUE THREAD

**Issue by peterbe** [twbs/bootstrap#17771]
From http://v4-alpha.getbootstrap.com/examples/ the link to 
http://v4-alpha.getbootstrap.com/examples/jumbotron-narrow/ causes a 404 not found.

**Comment by hebbet** [comment]
seems to be fixed an current v4 branch

**Comment by cvrebert** [comment]
Duplicate of #17174. Please search more next time. Thanks.
