### ISSUE TITLE
.has-error does not change .form-group label color

### ISSUE THREAD

**Issue by justdevelopers** [twbs/bootstrap#17777]
<table>
<thead>
<tr>
   <td><b>Bootstrap 3</b></td>
   <td><b>Bootstrap 4</b></td>
  </tr>
 </thead>
<tbody>
<tr>
<td>
<img width="1431" alt="screen shot 2015-10-05 at 4 25 20 am" src="https://cloud.githubusercontent.com/assets/12764577/10271518/8cb4e7e8-6b19-11e5-9574-0dbee801c0ce.png">
</td>
<td>
<img width="1413" alt="screen shot 2015-10-05 at 4 26 14 am" src="https://cloud.githubusercontent.com/assets/12764577/10271519/8fe15f1e-6b19-11e5-88fa-9d957bed981a.png">
</td>
</tr>
 </tbody>
</table>

**Comment by cvrebert** [comment]
Works fine in the docs: http://v4-alpha.getbootstrap.com/components/forms/#validation
Please post a JS Bin or JS Fiddle instead of a screenshot.

**Comment by justdevelopers** [comment]
i'm using 
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'

**Comment by cvrebert** [comment]
Need to see the exact HTML you're using. Please post a JS Bin or JS Fiddle using the CSS from https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css

**Comment by justdevelopers** [comment]
https://jsfiddle.net/vx7ufkzc/

**Comment by Johann-S** [comment]
It seems your Bootstrap CSS is different from the last V4 CSS.
With the correct one the problem doesn't occure

**Comment by justdevelopers** [comment]
<table>
<thead>
<tr>
   <td><b>Bootstrap master</b></td>
   <td><b>Bootstrap v4-dev</b></td>
  </tr>
 </thead>
<tbody>
<tr>
<td>
<img width="670" alt="screen_shot_2015-10-05_at_6_31_19_pm" src="https://cloud.githubusercontent.com/assets/12764577/10285305/ef8efbca-6b90-11e5-9a57-098fdb77e680.png">
</td>
<td>
<img width="668" alt="screen_shot_2015-10-05_at_6_31_49_pm" src="https://cloud.githubusercontent.com/assets/12764577/10285306/f40942f0-6b90-11e5-855e-3f1e020e61f6.png">
</td>
</tr>
 </tbody>
</table>

**Comment by cvrebert** [comment]
`.control-label` is gone in Bootstrap v4. Now it's named `.form-control-label`.
Filed a bug to note this change in the v4 migration docs: #17781
