### ISSUE TITLE
Glyphicons: Symbols have a little offset when trying to center it

### ISSUE THREAD

**Issue by Skaronator** [twbs/bootstrap#17780]
I've noticed that the glyphicons icons have a offset. You wouldn't notice it on original size but I want a bigger one and noticed the offset.

![image](https://cloud.githubusercontent.com/assets/2886913/10281344/224e14be-6b74-11e5-9171-dc300c062c18.png)

**CSS** - increase the size
```
<style>
	.custom-heart {
		font-size:1024px;
		color: #c9302c;
	}
</style>
```

**HTML**
```
	<body>
		<div class="mobile-fullwidth">
			<div class="container">
				<div class="jumbotron">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="text-center">
									<span class="glyphicon glyphicon-heart custom-heart" aria-hidden="true"></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>

```

**Comment by cvrebert** [comment]
Bootstrap just packages Glyphicons. We don't maintain the icon font itself ourselves.
Please report your issue upstream to http://glyphicons.com/
Thanks.

**Comment by jankovarik** [comment]
Actually it's an attribute caused by 12px basic grid as I already explained here: https://github.com/twbs/bootstrap/issues/15011#issuecomment-61652157 (try to zoom in attached screenshot and you'll understand once you recognize pixel grid ;]

**Comment by Skaronator** [comment]
Alright, thanks for the quick email response @jankovarik!
