### ISSUE TITLE
Auto Positioning in Tooltips not Working

### ISSUE THREAD

**Issue by krogis01** [twbs/bootstrap#17782]
We are pulling in the tooltips bootstrap component, and are having issues with the 'top/bottom/left/right auto' functionality. Currently, it will position the tooltip to the defined direction, but will not automatically re-position based on its location on the screen. We have the tooltip initialized in the JavaScript, and are defining the position with data-placement: "position" in the HTML; however, the auto is not being seen. We are on version 3.3.5.

HTML CODE:
`<button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="right auto" title="Tooltip on right">Tooltip on right</button>`

JAVASCRIPT CODE/INITIALIZATION:
`$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})`

**Comment by cvrebert** [comment]
Punting as WontFix per https://github.com/twbs/bootstrap/issues/15590#issuecomment-113321235
Patches would be welcomed, but Core Team doesn't have the time/bandwidth to write a patch ourselves.
