### ISSUE TITLE
aaahh bootstrap v3 carousel - removing text shadows!

### ISSUE THREAD

**Issue by mikeyinglis** [twbs/bootstrap#17787]
Please, before I have a little cry and even less sleep...

how do I remove the shadow from the text in the carousel caption?? what css element is controlling it??

I have set up custom css class, borrowed code from other places...nothing removes it!!

HELP!

**Comment by cvrebert** [comment]
Please ask how-to questions on StackOverflow, IRC, or Slack, rather than this bug tracker.
See https://github.com/twbs/bootstrap/blob/master/README.md#community for links.
Thanks!
