### ISSUE TITLE
Can we not show links in "print" media?

### ISSUE THREAD

**Issue by thdoan** [twbs/bootstrap#17788]
I propose that we git rid of this line in bootstrap.css:

```css
@media print {
  a[href]:after { content:" (" attr(href) ")" }
}
```

When appending the URL to all links on a printed page, it generally breaks the page layout and sometimes causes other unpredictable side effects. Also, most links are super long, so the value of showing them in the first place is questionable (the user always has the option to include the URL of the printed page in the header or footer). A [quick](https://processwire.com/talk/topic/9602-printing-page-in-browser-shows-urls-next-to-links/) [search](http://drupal.stackexchange.com/questions/59900/how-to-get-rid-of-added-urls-when-printing-a-bootstrap-themed-page) will reveal that many people are looking for ways to hide the link URLs.

**Comment by cvrebert** [comment]
It's gone in Bootstrap v4 (b9164b3690d63187e91fcef39cc81aa8c066806d).
We can't remove it in v3 due to backward compatibility.
