### ISSUE TITLE
input groups are broken when using flexbox 

### ISSUE THREAD

**Issue by itised** [twbs/bootstrap#17784]
If $enable-flex is set to true, input-group-addons shrink to their minimum size and content overflows out of them.

**Comment by cvrebert** [comment]
In which browser(s)?

**Comment by itised** [comment]
Safari 9.0 and Chrome 45, both on OS X 10.11. 

I also just checked Firefox 41, and it has the opposite problem. In Firefox, the addons are much wider than they should be. They are also shorter than the inputs they are attached to.

Again, this is only when $enable-flex is set to true. If $enable-flex is false, all 3 browsers behave as expected.

**Comment by DanCouper** [comment]
+1 on this, specifically FireFox. This is the behavior I'm getting at the minute (the green dashed lines are where the edges of the a grid columns are) -

In Firefox (42 and 44.0a2):
<img width="503" alt="screen shot 2015-12-16 at 12 11 34" src="https://cloud.githubusercontent.com/assets/573694/11840619/159fd078-a3ef-11e5-8128-e47dc9f79b4f.png">

In Chrome (47, correct behaviour):
<img width="463" alt="screen shot 2015-12-16 at 12 15 38" src="https://cloud.githubusercontent.com/assets/573694/11840626/280d5e1a-a3ef-11e5-9f83-23000e098f26.png">

As above, it's a flex issue; if I turn off flex it works universally.

**Comment by garlian** [comment]
+1

**Comment by mdo** [comment]
*Should* be fixed now that #17756 is merged. Holler if it's still broken though and we can re-open.

**Comment by wnr** [comment]
Seems to me that this issue is still around. I tried it with `exampleInputAmount` in the docs `components/forms/` locally with flex turned on @ commit `0416f761dddae04a1b4d3ce70afece518330ca4d`.

Applying `min-width: 0` seems to fix it indeed.

**Comment by reisub-de** [comment]
This bug is still there in v4.0.0-alpha.4

**Comment by tharunsaik** [comment]
you can simply add this default bootstrap grid CSS

`.input-group {
    border-collapse: separate;
    display: table;
}
.input-group .form-control, .input-group-addon, .input-group-btn {
    display: table-cell;
}`

**Comment by DanCouper** [comment]
@tharunsaik removing flex isn't a solution the described problem, using table display simply [re]introduces a new set of problems.

**Comment by mdo** [comment]
This is fixed y'all :).
