### ISSUE TITLE
.active class should be on <li> instead of <a> in .nav-tabs ?

### ISSUE THREAD

**Issue by sunilthecoder** [twbs/bootstrap#17799]
Sample code for Navs components show @ http://v4-alpha.getbootstrap.com/components/navs/ has the ACTIVE class in the `<a>` element, it should be in `<li>`.

**Comment by cvrebert** [comment]
>  it should be in `<li>`

Because...?

**Comment by sunilthecoder** [comment]
Because, as defined in bootstrap.css .active applies to <li>.  See code
below:

.nav-tabs > li.active > a,
.nav-tabs > li.active > a:hover,
.nav-tabs > li.active > a:focus {
  color: #555555;
  background-color: #ffffff;
  border: 1px solid #dddddd;
  border-bottom-color: transparent;
  cursor: default;
}


On Tue, Oct 6, 2015 at 1:52 PM, Chris Rebert <notifications@github.com>
wrote:

> it should be in <li>
>
> Because...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/17799#issuecomment-145943966>.
>



-- 
________________________________________________________
Sunil Mathews
phone: 517.914.8984

**Comment by cvrebert** [comment]
The CSS you're referring to is part of Bootstrap v3, not Bootstrap v4.

**Comment by sunilthecoder** [comment]
Interesting!  I learned something new, thank you.  Does this mean that when
I upgrade to v4 the code needs to be changed?

-Sunil

On Tue, Oct 6, 2015 at 5:51 PM, Chris Rebert <notifications@github.com>
wrote:

> The CSS you're referring to is part of Bootstrap v3, not Bootstrap v4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/17799#issuecomment-146011371>.
>



-- 
________________________________________________________
Sunil Mathews
phone: 517.914.8984

**Comment by cvrebert** [comment]
Yes! In accordance with [semantic versioning](http://semver.org), v4 is not backward-compatible with v3.

**Comment by gxclarke** [comment]
It is more useful on the <li> element because this provides a wider range of styling flexibility. I ran into this issue on an existing site already when converting to v4. As a workaround, I had to simplify the styling of the tabs, but it would be great if you retained the active class on the <li> element as in v3.

**Comment by cvrebert** [comment]
@gxclarke Feel free to open a new issue; this one is spent.
