### ISSUE TITLE
Modal transitions bugged by programmatic show/hide

### ISSUE THREAD

**Issue by SpikedKira** [twbs/bootstrap#17796]
http://getbootstrap.com/javascript/#modals

$('#myModal').modal('show');
$('#myModal').modal('hide');
$('#myModal').modal('show');
$('#myModal').modal('hide');

backdrop not correctly cleaned up due to new backdrop created each time show is called

**Comment by cvrebert** [comment]
[As noted in the documentation](http://getbootstrap.com/javascript/#modals-methods), those methods are asynchronous and return before the modal has actually been shown/hidden. So it doesn't make sense to call them directly one after another like that. You need to listen for the appropriate event (http://getbootstrap.com/javascript/#modals-events ) to fire, indicating that the showing/hiding has completed.
