### ISSUE TITLE
Bolded Inline Radio/Checkbox Labels

### ISSUE THREAD

**Issue by aabenoja** [twbs/bootstrap#17797]
Apologies in advance if there was already an issue reported for this. My issue searching did not turn up any relevant results. I'm currently working in chrome with `v3.3.5`.

I have a couple of cases where it would be desirable to use `.has-{validation state}.radio-inline`, rather than `.has-{validation state} .radio-inline` to mark individual inputs. However, when wrapping my label with my inline class the font weight gets bolded due to the `label` selector being more specific.

```html
<div class="radio-inline has-error">
  <label>
    <input type="radio" />
    Hi!
  </label>
</div>
<div class="radio-inline has-success">
  <label>
    <input type="radio" />
    Hello!
  </label>
</div>
```
![screen shot 2015-10-06 at 10 05 33 am](https://cloud.githubusercontent.com/assets/3229671/10314560/b9c5f188-6c12-11e5-8f67-f124c9e6fcf8.png)

While I could place the inline class back on the label and remove the wrapping div so that the inline styling works as expected, this prevents the `.has-{validation state}.radio-inline label` selector from allowing me to specifically style my input with the correct state.

**Edit**
For reference
https://github.com/twbs/bootstrap/blob/d53525cc3e24ef2e2d841468836c3d7712214f0a/dist/css/bootstrap.css#L2823-L2826

**Comment by mdo** [comment]
Sorry, but we won't be making any changes to the validation behavior in v3. Closing as a won't fix.
