### ISSUE TITLE
Modal shift+tab does not cycle

### ISSUE THREAD

**Issue by tdhooper** [twbs/bootstrap#17798]
Pressing `tab` on the **last** item in a modal will take your focus to the **first** item in the modal, but pressing `shift+tab` on the **first** item will not take you back to the **last** item.

**Comment by cvrebert** [comment]
What version of Bootstrap are you using?
What browser and OS are you using?

**Comment by tdhooper** [comment]
The version currently on http://getbootstrap.com/javascript/#modals (v3.3.5)
Chrome 45.0.2454.99 OS X

**Comment by schacko3** [comment]
our client has high 508 standards, so we also need the shift tab modal fix....thx

**Comment by cvrebert** [comment]
Confirmed on Firefox too, so this isn't browser-specific.

**Comment by SevenHong** [comment]
I am also having this problem on firefox and chrome on Fedora and Windows 7.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
