### ISSUE TITLE
card-columns in horizontal order

### ISSUE THREAD

**Issue by alexkerr** [twbs/bootstrap#17805]
Card columns in v4-alpha enforce a vertical order on cards. For many uses this would be unsuitable - for example anything that requires higher priority content to live above the fold. A technique to force horizontal ordering would be useful.

In addition, using the grid system to achieve this loses the benefits of the masonry-like columns - whereby cards can be varying heights and still fill empty vertical space.

**Comment by alexkerr** [comment]
Apologies - I didn't seem to be able to add correct label(s)

**Comment by torbjoernk** [comment]
+1 This would be an awesome feature!

**Comment by mariushop** [comment]
+1

**Comment by bigdrum** [comment]
+1. But for now, the document should at least point out explicitly that the current order is not horizontal. Stating "Masonry-like" without mentioning this difference is confusing.

**Comment by mdo** [comment]
You could accomplish this with some flexbox styles, but the exact columns implementation currently featured in the docs does not allow this reordering.
