### ISSUE TITLE
OS X Chrome/Safari native dropdowns for <select>s slightly horizontally misaligned

### ISSUE THREAD

**Issue by whelaro** [twbs/bootstrap#17801]
I'm noticing that on OSX for Safari and Chrome at the least, we're having issues with the options rendering in a way that doesn't appear to be linked to the container. Attaching example from css/supported controls from the getbootstrap.com site to show behavior. Works as expected (options are flush with the select parent) on Windows Chrome.

OSX Safari
<img width="884" alt="screen shot 2015-10-06 at 3 41 26 pm" src="https://cloud.githubusercontent.com/assets/2752676/10320352/05cede86-6c41-11e5-8bac-65ac8a9a7300.png">
OSX Chrome
<img width="882" alt="screen shot 2015-10-06 at 3 42 12 pm" src="https://cloud.githubusercontent.com/assets/2752676/10320353/05ceec64-6c41-11e5-9b7f-b6931bdc5a3b.png">

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=149871
@whelaro Please add yourself to the CC List of that bug.

We can't do anything about this on the Bootstrap side. The way the `<select>` native dropdown menu renders is up to the browsers themselves; we can't control it directly. Also, this isn't really Bootstrap-specific; the same thing happens with a completely vanilla unstyled `<select>`.
