### ISSUE TITLE
AMP'd HTML

### ISSUE THREAD

**Issue by codingideas** [twbs/bootstrap#17806]
Has anyone seen this: https://github.com/ampproject and what do you think the chances are to implement this in bootstrap?

Google even has a separate index to only search amp'd content: g.co/ampdemo

**Comment by Yoav1987** [comment]
I'm too interested about this. If Bootstrap is already responsive, what are the chances that AMP HTML runs smoothly with it?

**Comment by patrickhlauke** [comment]
From an admittedly cursory look over some of the AMP spec and discussion, the bottom line would be:

- can't use any custom JS (so any of the Bootstrap components and JavaScript plugins are out); the only way around this would be to define anything that needs JS behavior as an extended component, loaded via `<script async custom-element="..." src="..."></script>` syntax
- you can only use a subset of HTML and specific tags like `<html amp>` - as Bootstrap itself doesn't actually build the overall page/markup and it's left up to authors, there's not much Bootstrap would need to do here
- you can only add custom styles as an inline `<style>` - this is something that once again an author could/should be doing, not really something that Bootstrap should deal with

If anybody's in the mood to set up a separate "bootstrap-amp" project, great for them. But I personally don't think this is anything that should be done in core Bootstrap. /cc @mdo

**Comment by cvrebert** [comment]
Yeah, AMP is currently focused only on the websites of publications (e.g. newspapers, where the pages are relatively simple and not richly interactive), whereas Bootstrap is aimed at more general usage, including for sophisticated web apps.
Also, given that we support IE9 and that AMP uses Custom Elements, some potentially-hefty polyfill would be required, and I expect that'd be a tough sell.

**Comment by mdo** [comment]
Yup, not going to happen :grin:.

**Comment by Yoav1987** [comment]
AMP is now going live: http://searchengineland.com/live-google-launches-amp-results-in-mobile-search-results-243147

Still no plan for AMP Project & Bootstrap?

**Comment by cvrebert** [comment]
Nope :smile:

**Comment by patrickhlauke** [comment]
And again: if anybody plans to do a bootstrap-amp project, good on them. AMP does not allow for interaction JS, uses custom elements, and wants styles to be inlined. This does not strike me as a fit for what Bootstrap itself does/provides. Using "Bootstrap with AMP" would simply mean, unless I'm misunderstanding it, "having some basic CSS that can be inlined by authors" (either manually, or using some build tool). There's nothing else to "do" here from a bootstrap perspective.

**Comment by Yoav1987** [comment]
@patrickhlauke Got it.
