### ISSUE TITLE
bootstrap image vertically centered failure

### ISSUE THREAD

**Issue by tel8618217223380** [twbs/bootstrap#17807]
![image](https://cloud.githubusercontent.com/assets/12679783/10348067/8313fede-6d69-11e5-93a2-d704f830969e.png)
Write a program, the following code fragment, now there is a problem that is not vertically centered first picture on the left, hoping to give answers.

					<div class="container">
						<div class="row clearfix">
							<div class="col-lg-12 column">
								<div class="container-fluid">
									<div class="row clearfix">
										<div class="col-lg-2 column">
											<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
										</div>
										<div class="col-lg-10 column">
											<div class="container-fluid">
												<div class="row clearfix">
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
													<div class="col-lg-2 column">
														<img src="http://placehold.it/300x300" alt="" class="img-responsive img-thumbnail">
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

**Comment by cvrebert** [comment]
@tel8618217223380 Please make your example into a JS Fiddle or JS Bin. Thanks.

**Comment by tel8618217223380** [comment]
![image](https://cloud.githubusercontent.com/assets/12679783/10364240/45200702-6dec-11e5-8c17-71e6401eafa8.png)
Hello, please set the screen to be guaranteed so normal browsing, code has been shared, please help view.
https://jsfiddle.net/18217223380/1pejqewo/

Finally, I want to achieve so that left the first picture vertically centered, but I also set out how, please help me to tell me how we can properly make the first left pictures vertically centered

![image](https://cloud.githubusercontent.com/assets/12679783/10364289/aeb9fdb2-6dec-11e5-91b3-cd88f0e84767.png)

**Comment by tel8618217223380** [comment]
@cvrebert

**Comment by mdo** [comment]
That's something you'll need to address yourself—there's nothing in Bootstrap to do that for you, unless you perhaps make use of the `.media` component.
