### ISSUE TITLE
Bootstrap 3.3.5 Panel class is not available in v4-alpha?

### ISSUE THREAD

**Issue by msbg93** [twbs/bootstrap#17818]
why panel class is not available in bootstrap v4-alpha?

**Comment by simonewebdesign** [comment]
Panels, thumbnails and wells have been dropped in favour of cards, see: http://v4-alpha.getbootstrap.com/components/card/

**Comment by cvrebert** [comment]
See also http://v4-alpha.getbootstrap.com/migration/#components
