### ISSUE TITLE
Chrome bug makes rem sized borders vanish on zoom out

### ISSUE THREAD

**Issue by misterdai** [twbs/bootstrap#17812]
While checking Bootstrap V4, I noticed that the card borders vanish in Google Chrome when zoomed out by 1 increment or more.  Other browsers (Firefox, IE) behave themselves and the border stays visible.  Appears to be caused by a Chromium bug that's not going to be fixed until they've released their Slimming Paint code.

https://code.google.com/p/chromium/issues/detail?id=382483

As far as I can tell, this currently only affects cards in V4 as they use rem based borders.  I'm unsure on the approach V4 intends to take, but this probably should be taken into consideration if all borders will be sized in rem's eventually.

Here's an example of the normal zoom level and one step zoomed out on Chrome.

![bootstrap-v4-cards](https://cloud.githubusercontent.com/assets/209023/10364312/29b7c84a-6db2-11e5-9b9f-dc0e5936cd0f.png)

**Comment by cvrebert** [comment]
We don't support zooming; see http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#browser-zooming

**Comment by ivebeenlinuxed** [comment]
I don't think it's a zooming issue, it's a minimum font size issue. If you bring the root font size to ~<12px "rem" measurement becomes less than 1px.

**Comment by slavanga** [comment]
```$card-border-width``` should be changed to 1px like ```$border-width``` in https://github.com/twbs/bootstrap/commit/85f08df3b0b3c9b8c0cf625475a4ec66a809d968

**Comment by ivebeenlinuxed** [comment]
That should go a way to fix my related issue issue. Not sure on the original browser zooming bug.

Thanks @slavanga

**Comment by cvrebert** [comment]
Chrome has fixed [their bug](https://code.google.com/p/chromium/issues/detail?id=382483).

**Comment by mdo** [comment]
This isn't a Chrome bug, it's just a fact of the specific value we're using.

**Comment by mdo** [comment]
To elaborate, it makes sense that it'd disappear—the value becomes too low to render. I plan on replacing these with pixel values before v4 goes final.

**Comment by misterdai** [comment]
Happy for the issue to be closed in that case.  A switch to pixels would fix the current issue and Chromium have commit a fix to retain rendering at sub-pixel amounts.

**Comment by mdo** [comment]
No more rem borders so should be good here.

**Comment by cvrebert** [comment]
Not quite true:
```
bootstrap (v4-dev) $ ack rem scss/ | grep border | grep -v radius | grep -v spacing
scss/_type.scss:127:  border-left: .25rem solid $blockquote-border-color;
scss/_type.scss:146:  border-right: .25rem solid $blockquote-border-color;
scss/_variables.scss:462:$card-border-width:        .0625rem !default;
```

**Comment by mdo** [comment]
Fixing the card one now, but the blockquote ones can stay.

**Comment by mdo** [comment]
ac5be12
