### ISSUE TITLE
Suspicious code: unused property access

### ISSUE THREAD

**Issue by vagran** [twbs/bootstrap#17824]
https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L105

This place probably should be changed like this:
```diff
< this.$element[dimension](this.$element[dimension]())[0].offsetHeight
> this.$element[dimension](this.$element[dimension]())
```

Have a warning when compiling with Google Closure Compiler:
```
collapse.js:106: WARNING - Suspicious code. The result of the 'getprop' operator is not being used.
        this.$element[dimension](this.$element[dimension]())[0].offsetHeight
```

**Comment by cvrebert** [comment]
It might be there to force a relayout in buggy browsers, but that's just a guess.
@fat Do you know what's up with this code?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
