### ISSUE TITLE
when input larger when sr-only

### ISSUE THREAD

**Issue by yasinkocak** [twbs/bootstrap#17831]
When u use form-horizontal then the input is larger when the label has sr-only class.

**Comment by patrickhlauke** [comment]
Please provide a reduced test case showing this issue in something like http://jsfiddle.net/

**Comment by yasinkocak** [comment]
See at: http://jsfiddle.net/yasinkocak/33afd89p/

**Comment by twbs-lmvtfy** [comment]
Hi @yasinkocak!

You appear to have posted a live example (http://fiddle.jshell.net/yasinkocak/33afd89p/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 35, column 18 thru column 22: End tag ```` h2 ```` seen, but there were open elements.
* line 45, column 20 thru column 24: End tag ```` h2 ```` seen, but there were open elements.
* line 50, column 13 thru column 86: Duplicate ID ```` email ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
This has nothing to do with `.sr-only`. Those margins are basically down to whether or not a form is set to `.form-horizontal`, and are intended behavior as the form then behaves the same as `.row` (which also defines left/right margins of -15px). See http://getbootstrap.com/css/#forms-horizontal
