### ISSUE TITLE
Code style issue

### ISSUE THREAD

**Issue by inferusvv** [twbs/bootstrap#17873]
Sorry, maybe I am too much perfectionist, but...

![O_o](https://cloud.githubusercontent.com/assets/3227120/10403483/9373dd96-6ed4-11e5-9d84-5364e61593eb.jpg)

![WTF](https://cloud.githubusercontent.com/assets/3227120/10403544/1c9a66f8-6ed5-11e5-9c9f-32a8cdbb6047.jpg)

_vendor-prefixes.scss. Line 57.

**Comment by cvrebert** [comment]
The file in question no longer exists in the current `v4-dev` branch, because Autoprefixer.

**Comment by inferusvv** [comment]
@cvrebert v3 is not supported now?

**Comment by cvrebert** [comment]
Ah. Next time, mention that you're using bootstrap-sass.
