### ISSUE TITLE
Paid Dashboard Theme Is Broken

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#17872]
http://themes.getbootstrap.com/products/dashboard

<img width="705" alt="screen shot 2015-10-09 at 10 31 07 am" src="https://cloud.githubusercontent.com/assets/947110/10396519/e5fd91ba-6e70-11e5-8c98-2ab45e92eb0b.png">

**Comment by kkirsche** [comment]
This is due to an extension — sorry

**Comment by cvrebert** [comment]
FYI: Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker :
> Please **do not** open issues regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`

Thanks though.
