### ISSUE TITLE
Adding a stylization of the body cards

### ISSUE THREAD

**Issue by gitarno** [twbs/bootstrap#17874]
My proposal is to put a stylization the panel body respecting the same tone of context. for this you should add a Modified class "color" to paint the body panel.

file: less/mixins/panels.less
```
  & > .panel-body.color {
    background-color: lighten(@heading-bg-color,15%);
  }
```

**Comment by cvrebert** [comment]
We are no longer accepting new features into Bootstrap v3, so this would have to target Bootstrap v4.
And panels have been replaced by cards in Bootstrap v4 (http://v4-alpha.getbootstrap.com/components/card/ ) so this would have to target Cards instead.
Finally, "color" is a bad class name, it's way too generic. Do you have another naming proposal?

**Comment by cvrebert** [comment]
> respecting the same tone of context. 

I'm not clear on what you mean by this. Could you explain more?

**Comment by gitarno** [comment]
The proposal was to color the panel body (card), however this solution has already been shown in v4 in "background variants", thanks.

Regarding the nomenclature, really, ".color" is generic, but the properties that this rule are assigned are only valid if it was used with the class ".panel-body": ```.panel.body.color``` was more to simplify the names of classes as well as another proposal: ```.btn.warning``` , ``` .btn.alert```, etc we would have the class of the element and his modification. This creates a problem in Question performace or support, in practice?

**Comment by cvrebert** [comment]
> The proposal was to color the panel body (card), however this solution has already been shown in v4 in "background variants", thanks.

So, your feature request is now unnecessary? If yes, then can you close this issue?

---

We deliberately use e.g. `.btn-warning` instead of `.btn.warning`. See http://markdotto.com/2012/02/16/scope-css-classes-with-prefixes/ for the reasoning.

**Comment by gitarno** [comment]
Thanks!
