### ISSUE TITLE
404 themes.getbootstrap

### ISSUE THREAD

**Issue by HUGEwindow** [twbs/bootstrap#17871]
If you hit the startup link, you get a 404: http://themes.getbootstrap.com/products/marketing

**Comment by cvrebert** [comment]
Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker :
> Please **do not** open issues regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`

Thanks.
