### ISSUE TITLE
hidden-print don't work

### ISSUE THREAD

**Issue by churchill1869** [twbs/bootstrap#17876]
Hello,
Hidden-print class is not working (tested in ubuntu 14.04LTS / Firefox 41.0 / Chrome 39.0)
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
    <title>Print test</title>
  </head>
  <body>
    <div class="hidden-print">
        This text is not printed
    </div>
    <div class="visible-print-block">
        This text is only visible when printed
    </div>
    <!-- jQuery first, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>
  </body>
</html>
```

**Comment by msbg93** [comment]
please add these two also in <head>;
 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

**Comment by msbg93** [comment]
please put the jquery and bootstrap.js in <head>

**Comment by patrickhlauke** [comment]
@msbg93 that has nothing to do with the reported problem

**Comment by patrickhlauke** [comment]
the issue seems to be in https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css where for some reason the following rule appears:

```
@media print {
  .hidden-print .hidden-print {
    display: none !important;
  }
}
```

however, in the actual CSS - and if you use https://rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css - the correct media query is present

```
@media print {
  .hidden-print {
    display: none !important;
  }
}
```

not sure why the cdn version of rawgit.com somehow has the wrong CSS...so i'd suggest not using cdn.rawgit and instead making your own local copies of the css instead

**Comment by msbg93** [comment]
@patrickhlauke thanks for your kind information!

**Comment by churchill1869** [comment]
Perfect ! Thank you.
