### ISSUE TITLE
.list-group-item border in offcanvas example not visible in Chrome when page zoomed

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17885]
http://v4-alpha.getbootstrap.com/examples/offcanvas/

**Comment by cvrebert** [comment]
@bhutaninitin I can't reproduce this. What OS and version of Chrome are you using? Can you post a screenshot?

**Comment by bhutaninitin** [comment]
OS: Windows 10 
Google Chrome:	45.0.2454.101 (Official Build) m (32-bit)
![aadik-offcanvas-issue](https://cloud.githubusercontent.com/assets/10048052/10415138/96c0ae3a-7009-11e5-95b1-bb7014247c34.png)

**Comment by cvrebert** [comment]
Couldn't repro on Win 10 with Chrome 45; see screencast: https://saucelabs.com/jobs/623c661525bf49f4925d2618de355bea

**Comment by bhutaninitin** [comment]
Set zoom to 90% or less in chrome to reproduce this. The lines are visible at 100%.

Setting zoom to 90% or less works fine in Firefox/IE.

**Comment by cvrebert** [comment]
That would be an important detail worth noting.
Beware that we tend not to care about page zoom problems though: http://getbootstrap.com/getting-started/#support-browser-zooming
CC: @mdo

**Comment by bhutaninitin** [comment]
It seems to have come with the px to rem change. The issue was not visible with px.

**Comment by mdo** [comment]
No longer an issue—we're rocking 1px borders.
