### ISSUE TITLE
Vertically misaligned placeholder for date fields in Edge

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#17886]
In Microsoft Edge, when a form-control is applied to a field with the input type set to date, the pre-filled placeholder isn't vertically aligned, but instead in the bottom of the field.

http://jsbin.com/livelijafu/edit?html,output

**Comment by morvay** [comment]
How did you solve ?

**Comment by Studio384** [comment]
#17308 addresses the same issue. The problem here is that the line height is set to 34 pixels instead of the actually needed 1.5.

**Comment by Syone** [comment]
a possible fix on forms.less https://github.com/twbs/bootstrap/blob/master/less/forms.less

change line 192:
line-height: @line-height-base;

it may cause regression on iOS

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
