### ISSUE TITLE
Cover example: non-active nav-links of nav-masthead lack border-bottom on hover like in v3

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17887]
![image](https://cloud.githubusercontent.com/assets/10048052/10416091/048d02dc-7024-11e5-93ed-d3f6637491c0.png)

**Comment by cvrebert** [comment]
The hover styles were removed in 908f776c08bd5a1a04c7e6acdfdce693f943bcec without explanation.
@mdo Was this intentional or not?

**Comment by mdo** [comment]
Fixed in 8fa5fb2.
