### ISSUE TITLE
.page-header in Dashboard example should have border-bottom ?

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17883]
In the dashboard example, border-bottom is not visible for the page-header class.

**Comment by cvrebert** [comment]
It's not that the border is invisible; there's no `border-bottom` on it in the first place. I assume you really mean "Why doesn't it have a bottom border like the other heading?"

**Comment by bhutaninitin** [comment]
I would rather say: Why doesn't it have a padding-bottom? Currently it is too close to the row placeholders that follow.
