### ISSUE TITLE
Tabs doesnt update contents when programmatically selected

### ISSUE THREAD

**Issue by javexpress** [twbs/bootstrap#17894]
Here is the code:
```
<div id="iz">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">..jhhj.</div>
    <div role="tabpanel" class="tab-pane" id="profile">..jhbbnnb.</div>
    <div role="tabpanel" class="tab-pane" id="messages">..bnbn5456.</div>
    <div role="tabpanel" class="tab-pane" id="settings">..33333.</div>
  </div>

</div>
<button onclick="$('li:eq(2)', $('.nav-tabs')).tab('show')">Show It!</button>
```

**Comment by cvrebert** [comment]
As shown in the docs (http://getbootstrap.com/javascript/#tabs-usage ), you must call `show` on the `a` element, not the `li` element.
Fiddle: http://jsfiddle.net/cvrebert/ngco8wjo/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/cvrebert/ngco8wjo/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 58, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by javexpress** [comment]
Oh i see that was my mistake. Sorry. Thank you.
