### ISSUE TITLE
Installation - Initial build & running grunt - aborted due to warnings.

### ISSUE THREAD

**Issue by heliumdream** [twbs/bootstrap#17905]
Howdy folks of internetland, 

This borders on a bug and personal support...I'm posting reguardless, because even after following the documentation and scouring stackoverflow I'm stuck. 

Multiple clean installation attempts, plenty of restarts, still frustrated. Sorry if some of these are newb-ish questions. 

Following this very succinct guide:
http://v4-alpha.getbootstrap.com/getting-started/build-tools/#tooling-setup

There was a link to [Autoprefixer](https://github.com/postcss/autoprefixer)...after you download it, what do you do with it? 
I couldn't find any installation documentation, nor any mention of it in the tooling setup.  

aside from that,  I have completed the tooling setup.

alas, my first grunt command pukes at scsslint:

Running "scsslint:src" (scsslint) task
Running scss-lint on src
scss/_custom-forms.scss:133 [W] PropertySortOrder: Properties should be ordered
display, max-width, padding, padding-right, vertical-align, background, backgrou
nd-image, background-size, border, -moz-appearance, -webkit-appearance, appearan
ce
scss/_custom-forms.scss:134 [W] Indentation: Line should be indented with spaces
, not tabs
scss/_custom-forms.scss:148 [W] PropertySortOrder: Properties should be ordered
border-color, outline, box-shadow
scss/_dropdown.scss:56 [W] PropertySortOrder: Properties should be ordered displ
ay, width, padding, clear, font-weight, line-height, color, text-align, white-sp
ace, background, border
scss/_forms.scss:269 [W] PropertySortOrder: Properties should be ordered padding
-right, background-repeat, background-position, background-size
scss/_input-group.scss:100 [W] Shorthand: Shorthand form for property `padding`
should be written more concisely as `$input-padding-x-lg` instead of `$input-pad
ding-x-lg $input-padding-x-lg`
scss/_labels.scss:44 [W] PropertySortOrder: Properties should be ordered padding
-right, padding-left, border-radius
scss/_list-group.scss:51 [W] PropertySortOrder: Properties should be ordered wid
th, color, text-align
scss/_modal.scss:29 [W] PropertySortOrder: Properties should be ordered transiti
on, transform
scss/_navbar.scss:73 [W] PropertySortOrder: Properties should be ordered float,
padding-top, padding-bottom, margin-right, font-size
scss/_navbar.scss:93 [W] PropertySortOrder: Properties should be ordered float,
width, padding-top, padding-bottom, margin-right, margin-left, overflow
scss/_navbar.scss:98 [W] StringQuotes: Prefer double-quoted strings
scss/_type.scss:179 [W] PropertySortOrder: Properties should be ordered margin-b
ottom, line-height
scss/_utilities-spacing.scss:43 [W] PropertySortOrder: Properties should be orde
red padding-right, padding-left
Warning: Task "scsslint:src" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2015-10-13 01:37:01 UTC)
sass:core          229ms  ██ 3%
postcss:core       255ms  ██ 3%
autoprefixer:core  296ms  ██ 4%
csscomb:dist       823ms  █████ 10%
cssmin:core        463ms  ███ 6%
cssmin:docs         92ms  █ 1%
babel:dist          1.4s  ████████ 17%
uglify:core        771ms  ████ 9%
babel:umd           1.1s  ██████ 14%
scsslint:src        2.7s  ██████████████ 32%
Total 8.3s

**Comment by cvrebert** [comment]
> There was a link to Autoprefixer...after you download it, what do you do with it? 

If you're using our Gruntfile, you don't need to manually install Autoprefixer or use Autoprefixer directly; it's integrated into the relevant Grunt tasks (such as `dist`), and will get installed in step 3 of the "Tooling setup" instructions.

---

I cannot reproduce your scsslint error with the latest commit on [the `v4-dev` branch](https://github.com/twbs/bootstrap/tree/v4-dev), and no such error happens on Travis, so you'll need to go to StackOverflow (or IRC or Slack) if you want further help with that.

Note that `grunt dist` doesn't run the tests/linters, so you could run `grunt dist` instead of `grunt` to bypass the scsslint problem.

Good luck!
