### ISSUE TITLE
Margin and Padding Utility classes missing?

### ISSUE THREAD

**Issue by ShaunR** [twbs/bootstrap#17904]
Docs show them, but i'm not seeing them.  Have they now been implemented yet or is something broken?

**Comment by Wasserschlange** [comment]
Would it be possible to be more specific about what you are experiencing? Like which version of Bootstrap are you using, or your development setup. Can you describe your setup a little more, so the issue you are experiencing can be dissected more? 

I am using [Bootstrap's v4 Alpha cdns](http://www.bootstrapcdn.com/alpha/), and I am just doing a [quick start](http://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start) setup. I created a test html file with the margin and padding classes described in [Utility Classes](http://v4-alpha.getbootstrap.com/components/utilities/#utility-classes), and I found the classes to be available.

**Comment by ShaunR** [comment]
Sorry guys, this was an error on my part. I didn't checkout the right branch and was in the 3.3.5 tree.

Sorry again!
