### ISSUE TITLE
img-responsive seems to be missing from v4

### ISSUE THREAD

**Issue by shawnwildermuth** [twbs/bootstrap#17901]
The docs still mention it. Are you moving to img-fluid instead? If so, the docs need updating. This is for v4-dev branch

**Comment by davidjb** [comment]
Docs look okay:  https://github.com/twbs/bootstrap/blob/v4-dev/docs/content/images.md

The v4.0.0-alpha docs online are for that specific version; this was slightly confusing when I switched to following code directly from the v4-dev branch.

**Comment by kkirsche** [comment]
This is an artifact from One of the PRs where we changed from .img-responsive to fluid and will go away when beta 2 gets pushed out. Sorry for the confusion there, as it was launched as responsive not fluid, that changed though.

**Comment by cvrebert** [comment]
Closing per @kkirsche's comment. See #17166 / #17168 / #17456.

**Comment by ShaunR** [comment]
```.img-fluid``` is not working, i'm thinking it's because it's missing ```width: 100%``` also.  I'm trying to use it in the navbar...

**Comment by cvrebert** [comment]
@ShaunR No, it's not missing it. We don't use (and didn't use in v3 either) `width: 100%` because that will stretch the image if it's smaller than the available area. We use `max-width: 100%` instead.

**Comment by ShaunR** [comment]
I've got the image wrapped in a ```<a class="navbar-brand">``` which appears to be causing the problem.  Not sure if that classifies as a bug or not? My code below

```
<nav class="navbar">
  <a class="navbar-brand" href="#">
    <img src="logo.png" class="img-fluid">
  </a>
</nav>
```

**Comment by cvrebert** [comment]
@ShaunR This is veering off topic. Open a new issue with a JS Bin please.
