### ISSUE TITLE
btn-group and full width: 1px error

### ISSUE THREAD

**Issue by jcval** [twbs/bootstrap#17908]
The btn-group have a 1px error when a 100% width is apply.
(Chrome latest / Firefox latest / Win7)

![dp1](https://cloud.githubusercontent.com/assets/4648693/10455079/657a45a0-71b9-11e5-982b-584028037c74.png)
![dp2](https://cloud.githubusercontent.com/assets/4648693/10455080/657d3882-71b9-11e5-9fbb-fa03cc1ea503.png)

**Comment by cvrebert** [comment]
@jcval Please post a JS Bin or JS Fiddle demonstrating the problem. We can't debug screenshots.

**Comment by jcval** [comment]
@cvrebert : of course, you can see a demo here : http://goo.gl/VHXe1x

**Comment by 37371968ssr** [comment]
i want demo

**Comment by kukac7** [comment]
@jcval
````
#days-control a {
 margin: 0;
}
````

**Comment by jcval** [comment]
Thanks. So Bootstrap haven't a good way to make a full-width button group ?

**Comment by kukac7** [comment]
@jcval it has fallen behind:
````
#days-control a {
 margin: 0;
}
````

**Comment by jcval** [comment]
But if I remove width, the links does not take third of width...

**Comment by kukac7** [comment]
@jcval 
````
#days-control a {
    border-radius: 0;
    border-left: 0;
    border-right: 0;
    border-top: 0;
    margin: 0;
    padding: 10px 0 10px 0;
    width: 33.33333333%;
}
````

**Comment by jcval** [comment]
Correct. Thank you, @kukac7 

@cvrebert : ready to close.
