### ISSUE TITLE
Use display:inline-block instead of float

### ISSUE THREAD

**Issue by gthlopez** [twbs/bootstrap#17915]
This framework has been one of the best I have used , but I have a suggestion , you can use the property "display: inline-block " instead of "float: left | right and clear: both " that does exactly the same , " vertical-align : | middle | top bottom .... " only that the properties of vertical alignment is used , I 'd like to see in a later version . Thank you.

**Comment by kkirsche** [comment]
I'm not sure I follow how `display: inline-block;` can be equivalent to floating an object then clearing it. Would you be able to provide an example showing how floating an object is the same as setting `display: inline-block`?

**Comment by gthlopez** [comment]
I attach you the example.

**Comment by gthlopez** [comment]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Title of the document</title>
		<style>
			/* Main.css */
			html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}body{line-height:1}ol,ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:'';content:none}table{border-collapse:collapse;border-spacing:0}
			.col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12 {display: inline-block;}
			.col-md-12{width:100%}.col-md-11{width:91.66666667%}.col-md-10{width:83.33333333%}.col-md-9{width:75%}.col-md-8{width:66.66666667%}.col-md-7{width:58.33333333%}.col-md-6{width:50%}.col-md-5{width:41.66666667%}.col-md-4{width:33.33333333%}.col-md-3{width:25%}.col-md-2{width:16.66666667%}.col-md-1{width:8.33333333%}
			/*End main.css*/
			
			.row {
				font-size : 0px;
			}
			.row div {
				height : 250px;
				font-size : 12px;
			}
		</style>
	</head>
	<body>
		<div class="row">
			<div class="col-md-4" style="background-color:yellow;">
				<p>Div #1</p>
			</div>
			<div class="col-md-4" style="background-color:blue; vertical-align:middle;">
				<p>Div #2</p>
			</div>
			<div class="col-md-4" style="background-color:red;">
				<p>Div #3</p>
			</div>
			<div class="col-md-10" style="background-color:green;">
				<p>Div #5</p>
			</div>
		</div>
	</body>
</html>

**Comment by gthlopez** [comment]
![index2](https://cloud.githubusercontent.com/assets/12861278/10465862/c59c302c-71b6-11e5-840d-babfcf78875c.png)

Change extension .png to .html

**Comment by gthlopez** [comment]
Sorry , I can hardly attach the link. Here it goes: https://jsfiddle.net/prlopez/cqav24pw/

**Comment by twbs-lmvtfy** [comment]
Hi @gthlopez!

You appear to have posted a live example (https://fiddle.jshell.net/prlopez/cqav24pw/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 45, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Not a directional change we plan on taking. `inline-block` has it's own faults, and I believe they've been discussed across other issues here over the last few years.

**Comment by gthlopez** [comment]
I see , I wonder where you saw problems about using display:inline -block.

**Comment by dubcanada** [comment]
inline-block treats divs as text. So things like font size and letter spacing effect how far apart a display inline block is from one and another. Also things like different browsers and different OS's play an impact.

You can over come this by doing things like `font-size:0px;` and stuff like that. But this is more of a hack, then a solution.

Float is what you are suppose to use to put elements beside eachother, as states in the CSS documentation http://www.w3.org/TR/CSS2/visuren.html#float-position

Also order matters when you use inline-block. You can't put a div on the left of another div and float that first div right. You would need to reorder them in HTML. You also couldn't do things like offset without the use of margins, which would effect the flow and make things like fluid width almost impossible.

**Comment by cvrebert** [comment]
Closing per https://github.com/twbs/bootstrap/issues/17915#issuecomment-147832871

**Comment by stevendesu** [comment]
I know it's a year late, but I would like to point out one benefit to `inline-block` over `float` that has been causing me a bunch of headaches on a recent project.

I have a list of search results displayed as grid of cards. On a large screen I wish to display rows of 3, and on a small screen I wish to display rows of 2. However the height of the card may change.

Because the number of cards-per-row may change I can't do something cheesey like put `style="clear:left;"` on every third card, and because the height of the card may change it can sometimes cause cards to stack in strange ways like so: http://kimbryant.net/on-bootstraps-grid-using-display-inline-block-instead-of-floats/

`font-size:0px;` may seem like a "hack", but when it comes down to it with CSS the point is to make it look how you want, and if it looks good in all browsers then who cares if there's weird font-size stuff going on behind the scenes?

**Comment by mdo** [comment]
We've dropped nearly all our inline-block, table, and float styles for flexbox in v4. Should give you all the control you want :).

**Comment by stevendesu** [comment]
@mdo I was about to complain about how flexbox still isn't the silver bullet everyone has been clinging to for two years, but then I took a look at [Can I Use FlexBox](http://caniuse.com/#feat=flexbox) and it looks like - at long last - it finally is.

Guess my complaints are shot. Now I just need to know a convenient way to use Bootstrap 4's flexbox grid via NPM, if possible. I currently utilize Bootstrap like so:

```
npm install --save-dev bootstrap@4.0.0-alpha.5

// app.scss
@import '../node_modules/bootstrap/scss/bootstrap'
```

Which is delightfully simple but doesn't yield the flexibility to change SCSS variables. Is there a `bootstrap-flex` project or similar way to get what I want, or will I have to just download the whole Bootstrap source and include it in my repo?

**Comment by mdo** [comment]
> doesn't yield the flexibility to change SCSS variables

You can override Sass variables with `!default` on them by placing your overrides first in your Sass. For example...

```scss
// Your override
$body-bg: blue;

// Our variables file
$body-bg: #fff !default;

// Code
body { background-color: blue; }
```
