### ISSUE TITLE
Card-Deck class set card margin bottom to 0

### ISSUE THREAD

**Issue by gotoGosub** [twbs/bootstrap#17911]
It seems that the card-deck class has impact on margin bottom of card class. I can correctly see 0.75rem in browser page inspection, but margin is then rendered at 0px. Altering the margin bottom height to other values has no effect. The result on page is no margin is present between card-deck-wrapper -> card-deck -> card and subsequent elements.

**Comment by mdo** [comment]
By default the `.card-deck` nullifies a `.card`'s bottom margin because of the table styles. Doesn't happen with the flex approach I imagine. Probably just need to nuke the bottom margin entirely and use spacer utils instead.

**Comment by mdo** [comment]
Improvements coming in #19885.
