### ISSUE TITLE
Card borders are invisible with $font-size-root  less than 16px

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#17912]
Related to https://github.com/twbs/bootstrap/issues/17210 since `$card-border-width` is set to `0.625rem` which computes to `1px` only with `$font-size-root: 16px`.

**Comment by heruan** [comment]
Since this is still an issue, I wonder how much v4 is intended to work with a `$font-size-root` less than `16px`? Are there other elements such as borders which would disappear with a smaller root size? What will be the recommended minimum root size for v4?

**Comment by mdo** [comment]
Shouldn't be an issue anymore—borders are set to `1px` instead of using rems.
