### ISSUE TITLE
Navbar button gets pushed on second row because of form

### ISSUE THREAD

**Issue by Fatcrobe** [twbs/bootstrap#17913]
I have a navbar with a bunch of buttons, a hidden form and a float right dropdown. Sometimes when loading the page the button named "Dropdown" will be rendered on a 2nd row and refreshing the page will either fix or break the button. Sometimes it's the opposite, the button is on the first row and refreshing the page will break it.

JSBIN: https://jsbin.com/guruzocafo/1/edit?html,output

Even though it should have no impact, declaring bootstrap.css before bootstrap.js seems to fix the issue.

I'm using a customized bootstrap with `@grid-float-breakpoint` set to 1px (I don't think this is related to the problem) version 3.3.5
jQuery 2.1.4

Stackoverflow post
http://stackoverflow.com/questions/33107792/bootstrap-navbar-button-gets-pushed-on-second-row

**Comment by dkfiresky** [comment]
@Fatcrobe you're messed up with `.collapseMenu`. Why you override `margin-right` on your button?

**Comment by dkfiresky** [comment]
@Fatcrobe you're messed up with `.collapseMenu`. Why you overwrite `margin-right` on your button?

**Comment by Fatcrobe** [comment]
@dkfiresky Not sure I understand what you mean, I defined my own margin-right to get the proper position. I tried removing the margin-right on .collapseMenu and still have the issue.

**Comment by Fatcrobe** [comment]
Removed ````margin-right```` on  ````.collapseMenu```` because it's not related to the problem.

**Comment by Fatcrobe** [comment]
Also, the weird thing is that sometimes it renders properly but once I refresh the page a couple of times it breaks. The opposite can happen too.

**Comment by cvrebert** [comment]
@Fatcrobe Please make your example into a JS Fiddle or JS Bin.

**Comment by Murilirum** [comment]
Tried this on [CodePen] and I can't see any unexpected behavior.

[CodePen]: http://codepen.io/mur/pen/4451fb4b9c7348534363aaad0ce7a824

**Comment by twbs-lmvtfy** [comment]
Hi @Murilirum!

You appear to have posted a live example (http://codepen.io/mur/pen/4451fb4b9c7348534363aaad0ce7a824.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 24, column 13: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 25, column 13: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 26, column 13: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 27, column 13: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Murilirum** [comment]
Adjusted for linter compliance :+1:

**Comment by Fatcrobe** [comment]
That might sound really stupid but I just noticed my css is declared AFTER my javascript in my head. I just swapped them and the issue seems to be gone... anyone has an explanation?

**Comment by Murilirum** [comment]
I typically [put my javascript in the footer](http://stackoverflow.com/a/2105394) but offhand I can't think of why that would adjust anything other than maybe browser caching causing you to not see changes made to the CSS until you modified the layout of the DOM.

**Comment by Fatcrobe** [comment]
Something I forgot to say is that when I opened my page sometimes the button would be in the correct place (single row) and refreshing the page multiple times would break it (would get pushed to 2nd row). Sometimes it would be the opposite, button is on 2nd row and then refreshing the page would fix it.

**Comment by Murilirum** [comment]
> Something I forgot to say is that when I opened my page sometimes the button would be in the correct place (single row) and refreshing the page multiple times would break it (would get pushed to 2nd row). Sometimes it would be the opposite, button is on 2nd row and then refreshing the page would fix it.

What resolution was this at? RIght at the 559 breakpoint or something different?

**Comment by Fatcrobe** [comment]
Lower than 559

Right now I have my page opened and not able to reproduce the problem. Now with my page still opened I just moved the CSS to the footer and I hit refresh a couple of times and now the button is on the 2nd row.

Now if I increase the width of my window to higher than 559 the button dissapears and if I reduce my window width to lower than 559 the button re-appears but is on the 1st row (as you would expect)

**Comment by Murilirum** [comment]
> I just moved the CSS to the footer
Is there a particular reason for doing this? I'd recommend CSS be loaded in the header and just the jQuery / bootstrap library be handled in the footer. You'd want the styles to be available to the tags before they are loaded rather than vice-versa.

> I have my page opened and not able to reproduce the problem
I haven't seen any unexpected behaviour yet so I'm assuming this is then resolved - to some degree?

**Comment by Fatcrobe** [comment]
@Murilirum Try moving CSS files to the footer and see if you can reproduce.

**Comment by Fatcrobe** [comment]
@cvrebert How do I use those with a customized bootstrap?

**Comment by Murilirum** [comment]
@Fatcrobe No change was visible.

>How do I use those with a customized bootstrap?

You can import external stylesheets. I prefer CodePen out of habit for presenting examples, and you can provide a URL for a stylesheet and it will then be available.

**Comment by dkfiresky** [comment]
@Fatcrobe, @Murilirum position of \<link\> and \<script\> tags (in the \<head\> or in the \<body\>) does not affect on rendering, instead it affect on networking and time offset of when you will see rendered page.

**Comment by Fatcrobe** [comment]
I was able to reproduce the issue on JS Bin here's the link https://jsbin.com/siborogehe/1/edit?html,css,output

Make sure your output is wide enough so all the buttons fit on a single row then refresh the page multiple times (can take more than 10 refresh). The button named "Dropdown" will eventually be displayed on a second row by itself.

**Comment by dkfiresky** [comment]
@Fatcrobe you're missing `<div class="collapse navbar-collapse">`?

**Comment by Fatcrobe** [comment]
Further testing with jsbin and it seems quite random, I can't find a pattern to reproduce it easily plus jsbin is slow. It's much easier to reproduce with my files on disk.

**Comment by Fatcrobe** [comment]
@dkfiresky I removed it but I was able to reproduce it with and without the collapse div

**Comment by Fatcrobe** [comment]
@cvrebert Updated original post with JS Bin link.

**Comment by Fatcrobe** [comment]
@Murilirum Check out the JS Bin link in the original post it should be easy to reproduce the issue (should break after 2-3 page refresh)

**Comment by cvrebert** [comment]
@Fatcrobe Which web browser(s) are you experiencing this problem in?

**Comment by Fatcrobe** [comment]
@cvrebert I'm experiencing this problem with chrome and safari, haven't tested the other browsers.

**Comment by Fatcrobe** [comment]
Update: Since I moved the css files declaration to the top, I did not encounter the issue.

**Comment by Fatcrobe** [comment]
@patrickhlauke May I ask why is it considered closed? I mean, the solution I found doesn't make much sense and there should be an underlying issue.

**Comment by patrickhlauke** [comment]
unless i missed something, the reason for your bug was the fact that you were calling the stylesheet from the footer, rather than having a the `<link>` in your `<head>`, which can cause unexpected results  and interactions if scripts or other styles kick in before the linked stylesheet is loaded? it's not recommended practice to load your styles from anywhere other than the `<head>` (unless you're very explicitly doing stuff like conditional loading of certain styles after JS processing), so this looks like a bug with your approach, not with bootstrap?

**Comment by patrickhlauke** [comment]
but fair enough, if i've misunderstood this (admittedly, only been dipping in and out of this thread), i'm reopening it and leaving it up to @cvrebert ;)

**Comment by Fatcrobe** [comment]
@patrickhlauke You misunderstood, when I said footer I actually meant bottom of the ````<head>````.

**Comment by dkfiresky** [comment]
As I already mentioned:

> @Fatcrobe you're missing `<div class="collapse navbar-collapse">` after `.navbar-header`

This is the reason of why the row moved down. In case of wrapping all other content (all content that is in `.container-fluid`, except `.navbar-header`) into `.collapse.navbar-collapse` it returns to normal expected behavior. So I also agree with @patrickhlauke that it's rather @Fatcrobe implementation issue, not the bootstrap.

**Comment by Fatcrobe** [comment]
@dkfiresky As I already mentioned the issue occurs whether the buttons are in the ````.navbar-header```` or in the ````.collapse .navbar-collapse````

JSBin with buttons in ````.collapse .navbar-collapse````
https://jsbin.com/mepakucexu/1/edit?html,output

**Comment by dkfiresky** [comment]
[Navbar](http://getbootstrap.com/components/#navbar):

> ### Overflowing content
> Since Bootstrap doesn't know how much space the content in your navbar needs, you might run into issues with content wrapping into a second row. To resolve this, you can:
> 
> Reduce the amount or width of navbar items.
> Hide certain navbar items at certain screen sizes using responsive utility classes.
> Change the point at which your navbar switches between collapsed and horizontal mode. Customize the @grid-float-breakpoint variable or add your own media query.

**Comment by dkfiresky** [comment]
What is the problem to put script tags into end of the \<body\> and link tags into the \<head\>?

**Comment by cvrebert** [comment]
> What is the problem to put script tags into end of the <body> and link tags into the <head>?

@dkfiresky It should not be necessary to do that (it can affect loading speed, but should not impact correctness), and that's apparently not what Fatcrobe is doing (per https://github.com/twbs/bootstrap/issues/17913#issuecomment-148745527 ).

**Comment by cvrebert** [comment]
@dkfiresky The issue that the "Overflowing content" note refers to wouldn't explain inconsistency across page loads (without resizing the page).

**Comment by cvrebert** [comment]
@Fatcrobe Could you please point to which example the problem is most frequently reproducible with?

**Comment by Fatcrobe** [comment]
@cvrebert That would be https://jsbin.com/guruzocafo/1/edit?html,output

**Comment by dkfiresky** [comment]
> https://jsbin.com/guruzocafo/1/edit?html,output

Works fine for me without any issues. (Safari 9.0)

**Comment by cvrebert** [comment]
After much simplification of the testcase, I've been able to repro this in Chrome and Safari 9.0.

**Comment by cvrebert** [comment]
Testcase: https://gist.github.com/cvrebert/14f296e3629e177da6c2
(Reproduces when opened over `file://` ; haven't tried it over http)

**Comment by cvrebert** [comment]
Filed Chrome bug: https://code.google.com/p/chromium/issues/detail?id=544290

**Comment by Fatcrobe** [comment]
@cvrebert Thanks for the confirmation. Were you able to reproduce the bug when the css file was declared before your javasript file?

**Comment by cvrebert** [comment]
@Fatcrobe Didn't specifically test that.

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=150271

**Comment by Fatcrobe** [comment]
@cvrebert You might want to consider adding that the bug does not manifest when the css file is declared before the javascript file in the observations section of your bug report.

**Comment by cvrebert** [comment]
@Fatcrobe I welcome you to add such comments to the bugs yourself (assuming they also hold true for the reduced testcase). I am unable to spend more time on this myself.

**Comment by Fatcrobe** [comment]
@cvrebert Done. Thanks for the help.

**Comment by cvrebert** [comment]
Fixed in WebKit Nightly: http://trac.webkit.org/changeset/191610

**Comment by cvrebert** [comment]
Fixed in Chrome Canary: https://code.google.com/p/chromium/issues/detail?id=523282#c13
