### ISSUE TITLE
Styling for disabled checkboxes and radio buttons

### ISSUE THREAD

**Issue by markau** [twbs/bootstrap#17918]
I would like to submit a PR for this feature:

![demo](https://cloud.githubusercontent.com/assets/3004849/10472898/68a37224-726d-11e5-83e6-65317b7c9b7a.png)

Tested with:

Chrome 45.0.2454.101 m
Internet Explorer 11.0.23
Firefox 40.0.3

**Comment by kkirsche** [comment]
Make a or and post with a JSBin for us to review :)

**Comment by markau** [comment]
Thanks @kkirsche, I will ensure I do the the JSBin as well.

**Comment by markau** [comment]
I am still not exactly a Git expert, please let me know if I did something wrong with the PR.  Thank you!

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by markau** [comment]
I just realised that this isn't really complete without adding an example of usage into the documentation. Just give me a day or to 2 to take a look at that.

**Comment by patrickhlauke** [comment]
I do like the look of this...nice

**Comment by markau** [comment]
Thanks Patrick. The author of the custom forms should take the credit though, I just styled the disabled controls :blush:

**Comment by surjithctly** [comment]
@markau The disabled radio looks like its clickable bacause of the color and clickable looks like its disabled. Also fadeout the label text to make it perfect.

**Comment by markau** [comment]
Hey @surjithctly, you make a good point about the element state colors being the opposite of what is intuitive. Something like [this](https://jsbin.com/korurorovi/1/edit?html,css,output) looks much better. Thanks. Originally, the element was `#eee`, however I found this too light (i.e. insufficient contrast) to clearly show the checked+disabled state, so I have gone with a darker color, which means the enabled state also needs to be darker. [Here are the colors](https://color.adobe.com/create/color-wheel/?base=2&rule=Custom&selected=4&name=My%20Color%20Theme&mode=rgb&rgbvalues=0.9333333333333333,0.9333333333333333,0.9333333333333333,0.8196078431372549,0.8196078431372549,0.8196078431372549,0.8862745098039215,0.8862745098039215,0.8862745098039215,0,0,0,0,0,0&swatchOrder=0,1,2,3,4) I have used in this updated demo. I am interested in further suggestions people may have regarding the colors.

I like your suggestion of fading the label color of a disabled control, that would really make the state clear! However, I am not sure this is possible; the enabled/disabled control is a child of the label and, [AFAIK](http://stackoverflow.com/questions/2326499/apply-css-styles-to-an-element-depending-on-its-child-elements), it is not possible to style a parent based on the child's state.    i.e.:

    <label class="c-input c-checkbox">
        <input type="checkbox" checked="checked" disabled>
        <span class="c-indicator"></span>
        Can't toggle this (checked disabled)
    </label>

I am happy to be proven wrong! Perhaps there are new CSS selectors to help here.

Regarding your second point, I agree that this should also be applied to the default checkboxes/radios.  Thanks for bringing this to my attention; for some reason, I thought the defaults were still using the non-CSS elements - hence my attention on the custom forms. I will look at applying this to the defaults as well.

**Comment by markau** [comment]
Just to elaborate: the colour difference between enabled and disabled is subtle, perhaps too much so. As I said above, for reasons of contrast I had to make both states darker, and I sought to not stray too far from the original brightness.

**Comment by surjithctly** [comment]
@markau The easiest way to style disabled label is to wrap it in a <span> and write something like this in CSS.

```
input[type="radio"]:disabled ~ span {
  color:#e2e2e2;
}
```

So that it will look like : 

![image 2015-10-17 at 8 45 19 pm](https://cloud.githubusercontent.com/assets/1884712/10559532/2f7ac0b0-7510-11e5-9183-204aa2160709.png)

**Comment by markau** [comment]
Ahh yes, I see!  Here's an [updated demo](https://jsbin.com/fireleyopi/1/edit?html,css,output).  I have added a class selector to that label, to ensure no ambiguity, do you think that's useful? 

    <label class="c-input c-checkbox">
        <input type="checkbox" checked="checked" disabled>
        <span class="c-indicator"></span>
        <span class="c-indicator-label">Can't toggle this (checked disabled)</span>
    </label>

I'll commit the change.

Thanks.

**Comment by surjithctly** [comment]
Perfect. one more thing I think useful.

`cursor:not-allowed;`

for label and indicator. What do you think?

**Comment by markau** [comment]
Yes, that would be consistent with other form elements. Do you suggest that apply to just the checkbox/radio, or also the label (since it forms part of the hit box?)

**Comment by surjithctly** [comment]
Sure. it should be for both label and indicator. Same as in the default form.

**Comment by markau** [comment]
OK here's the [updated demo](https://jsbin.com/gifinodafa/1/edit?html,css,output). Thanks, Surjith.

It is a shame the `cursor:not-allowed;` is applied separately to the element and the label, and not the entire hitbox (e.g. there is a gap between the element and label where the normal cursor is shown). This is a consequence of not being able to style the parent control (the form-group div) based on the child's state. (Without non-trivial changes to the html.)

**Comment by surjithctly** [comment]
yeah.. there's no way now. otherwise we have to use JS. or else CSS4 should release before BS4 :)

**Comment by cvrebert** [comment]
Fixed by #18771.

**Comment by classicmike** [comment]
Hi @markau or @cvrebert or @patrickhlauke or @mdo,

Thanks for adding this featureI know this thread is quite old already but I had a question in regards to this issue.

How was the exporting of the svg images responsible for the custom checkboxes/radio buttons done? Back story to this is that my designer has created an svg of the checkbox she wants to export and replace as part of the ```$custom-checkbox-indicator-icon-checked``` hover upon exportation my checkboxes in a disabled checked state both look the same despite the fact I've used a background colour that has opacity in it (i.e. ```$custom-control-indicator-checked-disabled-bg: rgba(theme-color("primary"), .5);```).

Appreciate the help. 

Thanks.

**Comment by neojw1505** [comment]
trash
