### ISSUE TITLE
Invert selectors in input group

### ISSUE THREAD

**Issue by vicary** [twbs/bootstrap#17927]
I am using Chrome 45.0.2454.10.

This issue persists in v3 and v4, when an input group contains only one `<input type="text" class="form-control"/>` element, it would lost the 100% width and renders all four corners without radius.

Another problem about the selector is when I add more than one addon at the same side, only `:first-child` and `:last-child` removes the border of the opposite side.

See [this plunker](http://run.plnkr.co/plunks/Tud4LzDeDy8p3O6XetXk/) for a demo.

This issue can be fixed by,

0. Adding `width: 100%` to `.input-group`.
0. Flipping `:first-child` selectors to `:not(:last-child)` in `.form-control`, `.input-group-addon` and `.input-group-btn` under `.input-group`
0. Flipping `:last-child` selectors to `:not(:first-child)` in `.form-control`, `.input-group-addon` and `.input-group-btn` under `.input-group`

Not sure if this introduces other issues, any ideas?

**Comment by twbs-lmvtfy** [comment]
Hi @vicary!

You appear to have posted a live example (http://run.plnkr.co/plunks/Tud4LzDeDy8p3O6XetXk/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 21, column 9: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
> when an input group contains only one `<input type="text" class="form-control"/>` element

There is no point in using an `.input-group` in that case. There's nothing to group together.

> Another problem about the selector is when I add more than one addon at the same side

As noted by the bot, this is [explicitly documented as not being supported](http://getbootstrap.com/components/#input-groups-basic):
> **We do not support multiple add-ons (`.input-group-addon` or `.input-group-btn`) on a single side.**

**Comment by vicary** [comment]
My case is that multiple buttons and/or addons will be dynamically displayed based on the context of the textbox and other values of the same data model, one of the many possibilities is none of them are being shown.

Yes I am aware of the not supporting statement via the bot, but because these two features can be easily fixed, may I ask about the reason of the current approach? 

If there are more generic concerns to prevent my patch, I am happy to close this and do it with my own custom CSS.

**Comment by cvrebert** [comment]
Overall, I'm in favor of this. I am sympathetic to how the lack of generality is annoying at the templating layer. Since Bootstrap v4 drops IE8 support, that means we can now utilize `:not()` ([which requires IE9+](http://caniuse.com/#feat=css-sel3)) like you're suggesting.

**Comment by vicary** [comment]
Sounds good, should I make a PR?

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
If there's a better way, I'm in favor of it :D.

**Comment by vicary** [comment]
Should I include grunt generated files namely, `dist/`, `docs/assets/`, `docs/dist/` in the PR?

**Comment by cvrebert** [comment]
@vicary Negatory. They just cause merge conflicts.

**Comment by vicary** [comment]
@cvrebert Affirmative.

**Comment by cvrebert** [comment]
Fixed by #18500.
