### ISSUE TITLE
Lint all JS

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#17924]
Currently ESlint only lints `/js/*.js`; we should lint `/grunt` and `docs`.

**Comment by simonewebdesign** [comment]
No problem about the `grunt` folder, but `docs` seems to have many compiled files, as well as minified ones. I tried running the linter against `['js/src/*.js', 'grunt', 'docs']` and it took several minutes with a massive amount of errors:

```
>> 34671 code style errors found!
Warning: Task "jscs:core" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-10-14 11:00:17 UTC)
eslint:target         6.9s  ▇ 1%
jscs:core        11m 10.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
Total 11m 27.4s
```

Maybe we should restrict the linter to run just on some specific directories under `docs`?

**Comment by XhmikosR** [comment]
You got it wrong clearly. Docs JS src only.

**Comment by simonewebdesign** [comment]
Oh -- makes sense.

So if I understand correctly, the task is about copying the same configuration we have for `grunt jscs` into `grunt eslint`. So at the end we'll have the following commands available:

- `grunt eslint`
- `grunt eslint:grunt`
- `grunt eslint:core`
- `grunt eslint:test`
- `grunt eslint:assets`

Is this correct?
