### ISSUE TITLE
Add custom form control for  <input type="number">

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17923]

**Comment by cvrebert** [comment]
I'm pretty sure it's not styleable in any significant way other than treating it like a text input.
E.g. The increment and decrement buttons aren't styleable in most browsers, other than making them `display: none`, and adding replacement buttons requires adding actual `<button>` elements, and at that point it's basically a [custom form control](http://v4-alpha.getbootstrap.com/components/forms/#custom-forms), which is indeed something you can ask for, but it's more than merely "adding CSS styles".

**Comment by TroySK** [comment]
How about making them right aligned by default?

**Comment by bhutaninitin** [comment]
You are right, Chris. There aren't much styleable with CSS and a custom form control is a more appropriate request. How about a segmented button with input type=number and button elements controlling spin up and spin down for the number?

**Comment by cvrebert** [comment]
@TroySK That sounds fairly reasonable and would be really easy to implement. I encourage you to open a separate issue for your suggestion so that we don't lose track of it.

**Comment by TroySK** [comment]
@cvrebert Opened https://github.com/twbs/bootstrap/issues/17925. Please add appropriate labels.

**Comment by mdo** [comment]
Closing on this since I punted on the other PR as well.

**Comment by bhutaninitin** [comment]
Ahh! I am going to missing &lt;input type=number&gt; form controls. They are useful in scientific projects.
