### ISSUE TITLE
should have a CSS class which is styled like fill in the blanks

### ISSUE THREAD

**Issue by mrinal013** [twbs/bootstrap#17935]
Recently I use a class for form element which is .form-blanks and it simply has three lines code.
can we add this class?

![screenshot from 2015-10-15 18 20 48](https://cloud.githubusercontent.com/assets/11308328/10513475/97b69e04-7369-11e5-9183-68a5739519e8.png)

**Comment by cvrebert** [comment]
Closing per https://github.com/twbs/bootstrap/pull/17940#issuecomment-148446332
