### ISSUE TITLE
Consider integrating Drool to check for leaks in the JS

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#17932]
https://github.com/samccone/drool

**Comment by cvrebert** [comment]
See also https://github.com/tastejs/todomvc/pull/1464

**Comment by samccone** [comment]
@cvrebert let me know if you want a hand with this... :)

More than willing to do the initial spike here

**Comment by cvrebert** [comment]
@samccone Go for it. :grin: Implementing this by ourselves isn't on Core Team's radar at the moment, but if it's just reviewing a PR for it, I think we can handle that. Let me know if you have any questions about the setup of our build tools or unit tests.

**Comment by samccone** [comment]
awwww snap :+1:

**Comment by samccone** [comment]
@cvrebert is there a subset of components that you would recommend doing the initial leak tests against in v4?

**Comment by cvrebert** [comment]
Tooltips and popovers would probably be the best bang-for-your-buck place to start.

**Comment by mdo** [comment]
Closing as stale.
