### ISSUE TITLE
New xs and xl (extra large) classes for button sizes?

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17937]
Like clothes, buttons should also come in all sizes.

**Comment by cvrebert** [comment]
Although personally I wasn't in favor of it, we've already removed XS buttons in v4, so adding XXS is out of the question.
Also, there isn't currently an XL button size, so I presume you mean "add XL" rather than "add XXL".

**Comment by bhutaninitin** [comment]
By XXS, I meant buttons which have line-height exactly half of the normal size textbox. It may open possibilities of some creative form controls.

**Comment by cvrebert** [comment]
The old XS buttons in v3 were bigger than what you're suggesting, and they were axed by @mdo in v4 for being too small. So, yeah, a new XS/XXS is not likely to happen.

**Comment by bhutaninitin** [comment]
I won't miss XS buttons as I think they had an awkward size. Here is a rough (not neat, sorry) drawing for a possible use case for XXS:

![image](https://cloud.githubusercontent.com/assets/10048052/10533139/1edbdc90-73e3-11e5-8c48-b3cabd0df5dc.png)

**Comment by mdo** [comment]
Punting on this for now—don't think we need all those sizes.

**Comment by tarkhov** [comment]
@bhutaninitin Implemented here - https://tarkhov.github.io/postboot/#button-size
