### ISSUE TITLE
`selector` option must be specified when initializing exception will never be hit in tooltip.js

### ISSUE THREAD

**Issue by viktorlarsson** [twbs/bootstrap#17948]
In line [57-59](https://github.com/twbs/bootstrap/blob/master/js/tooltip.js#L57-L59) in tooltip.js, the following exception will never be thrown.

`if (this.$element[0] instanceof document.constructor && !this.options.selector) {
      throw new Error('`selector` option must be specified when initializing ' + this.type + ' on the window.document object!')
    }`

```
this.$element[0] == <span ...>
document.constructor == [Object HTMLDocument]
```
I think this would be a better solution perhaps?

`if (this.$element.is(window.document) && !this.options.selector) {
			throw new Error('`selector` option must be specified when initializing ' + this.type + ' on the window.document object!')
}`

My first bug report, so sorry if i'm missing something :)

**Comment by cvrebert** [comment]
It does get thrown in the appropriate scenario, otherwise the following unit test wouldn't pass:
https://github.com/twbs/bootstrap/blob/1db87efc2a809132756be052498922bfa8527cde/js/tests/unit/tooltip.js#L1258-L1263
And I just manually re-verified that it works correctly by running
```js
$(document).tooltip({ title: 'What am I on?' })
```
on getbootstrap.com and observing the expected error.

> `this.$element[0] == <span ...>`

That's not the problematic scenario.

**Comment by viktorlarsson** [comment]
Oh, right. If you initialise it like that. Didn't think of that.

There is an issue with IE7 and this method. It's because when Function.prototype.toString is called with a constructor, it can only discern the constructor as an object("[object Object]"), and thus rejects the argument and throws a "Function expected" error.

But since you dropped the support for IE7 it doesn't matter I guess. :)
