### ISSUE TITLE
HTML form <input type='number'> does not allow the letter 'e' as it should according to HTML spec

### ISSUE THREAD

**Issue by bfrager** [twbs/bootstrap#17943]
The Bootstrap form validation checker returns the warning "Please enter a number" if e is entered into an input field with type=number.

The <a href'http://www.w3.org/TR/html-markup/input.number.html">HTML spec</a> denotes that 'e' or 'E' is allowed in input fields with type=number as a mathematical symbol. From the spec:

A floating-point number consists of the following parts, in exactly the following order:

Optionally, the first character may be a "-" character.
One or more characters in the range "0—9".
Optionally, the following parts, in exactly the following order:
a "." character
one or more characters in the range "0—9"
Optionally, the following parts, in exactly the following order:
a "e" character or "E" character
optionally, a "-" character or "+" character 3.One or more characters in the range "0—9".

**Comment by cvrebert** [comment]
> The Bootstrap form validation checker

There's no such thing. You're either referring to a third-party library such as https://github.com/1000hz/bootstrap-validator or to the HTML5 form field validation built into the web browser itself. Neither of which is controlled by Bootstrap.
