### ISSUE TITLE
Add variable to disable responsiveness in v4

### ISSUE THREAD

**Issue by hitmands** [twbs/bootstrap#17962]
Hi, most of developers use an uncompiled version of bootstrap (ex, SCSS version for twbs/4).

Should you expose a *sass variable* that disables the responsivness feature when compiled?

`$useResponsive: false;`

there are many posts that help users to disable responsive but I think that this could be a simple, standard way.

**Comment by kkirsche** [comment]
I don't believe bootstrap 4 has been architected in such a way to allow this type of thing (disabling responsive design)

**Comment by hitmands** [comment]
I think you're right, but, i some projects, sometimes, we need to have a non-responsive design and in these cases we need to manually disable the responsive feature...

Exposing a simple variable could be a standard-way to do what sometimes we need (depends on the project that we are working)!

By the way, 
I vote for this feature!

**Comment by cvrebert** [comment]
Sorry, but we explicitly no longer support this. Per the v4 migration documentation:
> #### Misc
> * [Non-responsive usage of Bootstrap is no longer supported.](http://v4-alpha.getbootstrap.com/migration/#misc)

So, you're on your own. You may wish to consider using a different framework or re-evaluating the wisdom of non-responsive designs in this day and age. Good luck.
