### ISSUE TITLE
 justified-nav.css ( http://getbootstrap.com/examples/justified-nav/) not connecting

### ISSUE THREAD

**Issue by avkpol** [twbs/bootstrap#17963]
Hi,
I can not connect  justified-nav.css   to example page http://getbootstrap.com/examples/justified-nav/
 in my project. Path to file and Bootstrap version both checked. Even placing justified-nav.css in the same dir with base.html did nothing. Only adding file content into base.html itself works. BTW bootstrap. min.css not working as file as well, only as link to source. Any ideas?

**Comment by cvrebert** [comment]
Please use StackOverflow, IRC, or Slack for asking personal support questions such as this. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker for links.
