### ISSUE TITLE
Bootstrap3 navbar not working with bootstrap4 alpha

### ISSUE THREAD

**Issue by rkommine** [twbs/bootstrap#17961]
Hi,

I thought of using bootstrap 4 alpha. To check I have used the  below code for the navbar.

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

But this navbar is not working. It is working fine in bootstrap 3. Could you please help how I can make this nav bar work in bootstrap4

**Comment by cvrebert** [comment]
Per [our versioning policy](https://github.com/twbs/bootstrap/blob/master/README.md#versioning), in accordance with [SemVer](http://semver.org/), Bootstrap v4 is not backward-compatible with Bootstrap v3. So you shouldn't expect Bootstrap v3 HTML to always work in Bootstrap v4 without any modifications.

See http://v4-alpha.getbootstrap.com/components/navbar/ for the required navbar markup for Bootstrap v4.

Please note that v4 is not yet stable and that the v4 navbar component in particular is currently a work-in-progress.
