### ISSUE TITLE
v4 Modal transition (fade) violates CSP (script-src 'unsafe-inline')

### ISSUE THREAD

**Issue by Deilv** [twbs/bootstrap#17964]
Modals with the .fade class trigger an error on show, causing the modal to fail to show and scripts to stop working requiring a page reload. This wasn't a problem in v3 and seems to be caused by the reflow function trying to eval() and inject javascript in the page.

Using branch v4-dev in a Meteor app.

**Comment by iliasch** [comment]
This is the cause of the problem:
```javascript
reflow: function reflow(element) {
  new Function('bs', 'return bs')(element.offsetHeight);
},
```
I'm trying to figure an alternative way to access the proper global object, without using the function constructor, unless you want to classify this as WontFix as well.

**Comment by iliasch** [comment]
Commenting out the Function line seems to solve the modal/fade problem, but I wonder what exactly is this reflow function meant to do? What did I just break?

```javascript
    reflow: function reflow(element) {
      //new Function('bs', 'return bs')(element.offsetHeight);
    },
```

**Comment by cvrebert** [comment]
That strange coding style might be a remnant from earlier drafts of v4 which used the Google Closure compiler, presumably to prevent that function from being optimized away completely.
CC: @fat

**Comment by leeish** [comment]
The accordian also seem to violate the CSP for unsafe-eval. Anyone else seeing this?
