### ISSUE TITLE
Changing pictures (src) and resize needs a refresh to reposition all pictures nicely

### ISSUE THREAD

**Issue by Odvkram** [twbs/bootstrap#17976]
Hi,
I made a logo surrounded by pictures. With a timer, the pictures are changes by changing the src attribute. It works beautifully on all screensizes, however if the screensize is reduced, it needs a full browser refresh to allign the pictures again.
It can be observed here: http://www.iklaad.com 

Reproduce: use large or medium screensize and wait for 3 seconds or so, so that some pictures have changed, then resize to small or xs. You'll see the pictures not lined up but below each other. refresh solves it again. 

In JSbin, I reduced the code by taking out the surrounding fadeout/fadein jQuery statements. Now the problem seems to happen only very occasionally. Apperantly a glitch when user resizes at the same moment the src attrib is changed. That behaviour is here http://jsbin.com/lokizo

Is there a workaround for using jQueries fade out/in in combination with changing src attrib and resizing screen or would this concidered to be a limitation?
Cheers,
Mark

**Comment by twbs-lmvtfy** [comment]
Hi @Odvkram!

You appear to have posted a live example (http://jsbin.com/lokizo/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 15, column 4 thru column 232: Duplicate ID ```` lang_flag ````.
* line 54, column 2 thru column 7: Stray end tag ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
Please direct personal support requests to StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
