### ISSUE TITLE
v4: Compiled version not available yet? 

### ISSUE THREAD

**Issue by HallofFamer** [twbs/bootstrap#17975]
The bootstrap 4's official website does not have a compiled version for download yet, unlike for bootstrap 3 I can just download it and upload to my server for easy installation/integration.

http://v4-alpha.getbootstrap.com/getting-started/download/

So when do you plan to add it? And is there anyone who has compiled bootstrap 4, if so do you mind sharing? Thanks. 

Edit: Also there is no bootstrap-theme.css file in bootstrap 4, is the bootstrap theme removed or is it integrated into the bootstrap.css file?

**Comment by tshinnic** [comment]
"... if so do you mind sharing?"  
The linked [source download zip](https://github.com/twbs/bootstrap/archive/v4.0.0-alpha.zip) has both the `/dist/css/` and `/dist/js/` subdirectories containing built files.  You could extract the built files from that alpha release zip?  Less easy, but for an alpha I'm not surprised...

The [latest source zip](https://github.com/twbs/bootstrap/archive/v4-dev.zip) had its `/dist/` files [updated](https://github.com/twbs/bootstrap/tree/v4-dev/dist/css) 'recently' (6 days ago). (though that appears to be an irregularly performed update?)  So from that you could test recent changes.

**Comment by cvrebert** [comment]
> So when do you plan to add it?

When we release v4.0.0-alpha.2. There's not yet a specific date.

> Also there is no bootstrap-theme.css file in bootstrap 4, is the bootstrap theme removed or is it integrated into the bootstrap.css file?

It's been integrated into core Bootstrap. There are now variables to control things such as rounded corners and gradients that were part of the v3 theme.

**Comment by jvanasco** [comment]
I'd really love to see these updated as part of the nightly build process too.

I'd definitely be testing out 4.0 and looking for bugs if it were -- but having to switch to a "built it from scratch!" system is too much of a buy-in for me right now.

**Comment by IanLee1521** [comment]
Looks like Alpha 2 is out, but the compiled link on the [website](http://v4-alpha.getbootstrap.com/getting-started/download/) still shows `Coming Soon!`
