### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by chrisbell08** [twbs/bootstrap#17971]
This is how the responsive menu looks when it's toggled in the docs for V4.

<img width="387" alt="screen shot 2015-10-19 at 09 25 33" src="https://cloud.githubusercontent.com/assets/8242722/10572837/82b9037a-7643-11e5-9625-296b33a93cc7.png">

Is this the expected behaviour? Should the menu items not stack like in BS3?

**Comment by cvrebert** [comment]
Duplicate of #17250.
