### ISSUE TITLE
Prevent dropdown from closing

### ISSUE THREAD

**Issue by dominicarrojado** [twbs/bootstrap#17984]
Is this package responsible for closing a dropdown on click outside? How do I change it so that it will not close my dropdown?

**Comment by cvrebert** [comment]
You [`preventDefault()`](http://getbootstrap.com/javascript/#js-events) the [`hide.bs.dropdown` event](http://getbootstrap.com/javascript/#dropdowns-events).
Please direct future how-to questions to StackOverflow or similar. Thanks.
