### ISSUE TITLE
Scroll Issue in IE using page's zooming

### ISSUE THREAD

**Issue by dimamarksman** [twbs/bootstrap#17989]
Windows 8, IE11.
Bootstrap v3.3.5.

It can be reproduced on http://getbootstrap.com/javascript/#modals by click on the button:
![screenshot_1](https://cloud.githubusercontent.com/assets/3263744/10611093/3ad9bdd6-7753-11e5-81aa-75eea799c5d1.png)

and increasing page's zoom.

As result two vertical scrollbars:
![c7zzzw9](https://cloud.githubusercontent.com/assets/3263744/10611145/6eaeabda-7753-11e5-9564-e210f3aac8d6.png)

**Comment by Johann-S** [comment]
I'm not sure Bootstrap support page zooming, see 
http://getbootstrap.com/getting-started/#support-browser-zooming

**Comment by dimamarksman** [comment]
I see. Thank you for a quick response.

**Comment by cvrebert** [comment]
Yeah, gonna call this WontFix/CantFix.
