### ISSUE TITLE
gulp less compile

### ISSUE THREAD

**Issue by terminatorheart** [twbs/bootstrap#17987]
when i put bootstrap.min.css file in a folder which will be used by gulp-less task, then something wrong there.

Error: Unrecognised input. Possibly missing opening '{' in file /private/var/www/weishequ/static/less/common/bootstrap.min.css line no.

 so i check it again and again, at last, i found something:
`
.dropup .caret,.navbar-fixed-bottom .dropdown .caret{content:"";border-top:0;border-bottom:4px dashed;border-bottom:4px solid\9} 
`
as you can see, there has a '\9' behind solid property, if i remove it, then everything is fine, is it a bug?

more detail:
* bootstrap version:v 3.3.5 (v 3.0.3 get the same problem, but i have not read the code carefully)
* i find some code in dropdowns.less in line 189:
`border-bottom: @caret-width-base solid ~"\9"; // IE8`

need more info ? please @me

**Comment by cvrebert** [comment]
@terminatorheart 
The `\9` is an IE-specific [browser CSS hack](http://www.paulirish.com/2009/browser-specific-css-hacks/).
We cannot provide assistance with build tools other than the official Gruntfile that is provided with Bootstrap itself. So we can't help you with `gulp-less` here.
Also, running a minified CSS file such as `bootstrap.min.css` thru a Less compiler doesn't really make sense.

**Comment by terminatorheart** [comment]
@cvrebert you're right, i know it has no sense, i just run it and find the problem.may be i had bad habit as i wound put all third-part css file into less folder and process all( no matter it is a css or less file) into css folder, i have to do it that way because i wound clean the dist folder each time when i build project, and css folder just under the dist folder. anyway, thank you a lot
