### ISSUE TITLE
v4 Checkbox label font weight hard-coded

### ISSUE THREAD

**Issue by quasipickle** [twbs/bootstrap#17991]
`.checkbox label` has the weight set to "**normal**".  I believe it should be set to "**inherit**".

**Comment by bassjobsen** [comment]
@quasipickle why do you believe so? I don't think it should inherit from the parent? Or did you mean set to `initial` (which refers to the initial value `normal` )?

**Comment by quasipickle** [comment]
No, I meant `inherit`.  I think it should have `inherit` because if I have custom CSS that sets the font weight of `.checkbox`, I think it should be carried through to the label.

I have set the font-weight for my entire app to "300".  As it currently stands, I have to have a special rule for `.checkbox label`, because by default that will have a weight of "400".

`initial` would be just as bothersome to me, because I'd still have to override it with a special rule.

Regular labels don't have any special weight setting, just those wrapped inside `.checkbox` (and I'm assuming `.radio`)

**Comment by mdo** [comment]
No longer an issue I think—we're not specifying weights for our form labels.

**Comment by cvrebert** [comment]
@mdo Erm:
* https://github.com/twbs/bootstrap/blob/1132e0c11df54a1d1a92f771aa8632fe03e3c935/scss/_forms.scss#L187
* https://github.com/twbs/bootstrap/blob/1132e0c11df54a1d1a92f771aa8632fe03e3c935/scss/_forms.scss#L219

**Comment by mdo** [comment]
Fixed in #18760.
