### ISSUE TITLE
Explanation of !important on visible-*-* classes?

### ISSUE THREAD

**Issue by RKS213** [twbs/bootstrap#17993]
I was wondering the reasoning for adding !important to all the visible-*-* styles. I've never actually been able to use these classes due to this issue and they seem very useful.

Example: most of the time I need these I want visible-md-block but have some js show the element on a click for xs devices. The js won't override the !important however unless I write more code to account for this. I always end up using a custom class that does the same thing as the built-in visible-*-* classes and it seems redundant.

**Comment by cvrebert** [comment]
They're utility classes and thus use `!important` to avoid CSS specificity issues (i.e. getting accidentally trumped by other CSS and thus defeating their sole purpose). See http://davidtheclark.com/on-utility-classes/ and https://css-tricks.com/when-using-important-is-the-right-choice/

> Example: most of the time I need these I want visible-md-block but have some js show the element on a click for xs devices.

I suspect the recommendation would be to not use the `.visible-*` classes in such cases where you also want to manually toggle the visibility.
CC: @mdo

> The js won't override the !important however unless I write more code to account for this.

Doesn't seem like that much code:
```js
yourElement.style.setProperty("display", "block", "important");
```

**Comment by mdo** [comment]
Yeah I don't see anything changing here—if we want them to be useful, it has to happen this way for the most part. Unless we force everyone to only ever use single classes and no parents or chaining etc :D.
