### ISSUE TITLE
v4: label-pill doesn't adhere to $enable-rounded

### ISSUE THREAD

**Issue by davidjb** [twbs/bootstrap#18002]
See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_labels.scss#L46

This makes `.label-pill` inconsistent with `.nav-pills`; the latter uses `$enable-rounded` via the border-radius mixin and the former hard-codes its value. 

That said, if `.label-pill` adhered to this variable, there'd be no difference between standard `.label` and `.label-pill` if `$enabled-rounded` was disabled, thus making it redundant.

**Comment by mdo** [comment]
Fixed by #18011.
