### ISSUE TITLE
Icon with a wrong height on input groups button when doctype xhtml1.0

### ISSUE THREAD

**Issue by cyrilgandon** [twbs/bootstrap#18003]
Here is a plunkr that demonstrate the problem:

http://plnkr.co/edit/4bkLrD4jy3dDAs0Os77a?p=preview

![image](https://cloud.githubusercontent.com/assets/2806672/10632753/99172ef4-77e6-11e5-86ab-48ffb11f32b1.png)

If you change `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`

To `<!DOCTYPE html>`

The icon is sized properly.

Is there a workaround here?

**Comment by twbs-lmvtfy** [comment]
Hi @cyrilgandon!

You appear to have posted a live example (http://run.plnkr.co/plunks/4bkLrD4jy3dDAs0Os77a/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 1, column 1 thru column 121: Almost standards mode doctype. Expected ```` <!DOCTYPE html> ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cyrilgandon** [comment]
Beat by a bot, gg!
