### ISSUE TITLE
Tabs dont work properly in BS4 alpha

### ISSUE THREAD

**Issue by craft37** [twbs/bootstrap#18009]
Each tab possible to be shown only once cause active class not removing with clicking on other tabs.

Fixed with:
```
$('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
	$( "a" ).removeClass( "active" )
})
```

**Comment by cvrebert** [comment]
Already fixed in the [`v4-dev`](https://github.com/twbs/bootstrap/tree/v4-dev) branch. Please test against the latest commit in the branch prior to filing bugs against v4 in the future. Thanks!
