### ISSUE TITLE
add .text-normal, .text-bold, .text-italic classes

### ISSUE THREAD

**Issue by jparmar** [twbs/bootstrap#18001]
we have text formatting classes like text-muted, text-left etc.

like wise please  add classes like text-normal, text-bold, text-italic

I know there are alternatives for : 
text-bold : `<strong>`
text-italic : `<em>`

but if I have a already bold text and I want to remove the text formatting, then text-normal would be very helpfull.

**Comment by cvrebert** [comment]
The [`reset-text` mixin](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_reset-text.scss) is similar to `.text-normal`, though it's not currently exposed as a class.

**Comment by mdo** [comment]
Added in 0759d76.

**Comment by cvrebert** [comment]
Erm, rather, added in 26da610bd03e7efe9255b2b88f14449972f7d616

**Comment by nickmccurdy** [comment]
Were these removed? `text-bold` doesn't seem to do anything for me.

**Comment by Starsam80** [comment]
@nickmccurdy I think you are looking for the `.font-weight-bold` class

**Comment by cvrebert** [comment]
@Starsam80 is correct.
