### ISSUE TITLE
Vendor CSS prefixes

### ISSUE THREAD

**Issue by karlitoz007** [twbs/bootstrap#18019]
The project is missing vendor-specific prefixes for Firefox (-moz) in several parts of the CSS file. For example:

-moz-transitions in .img-thumbnail, .form-control, .fade, .thumbnail, .progress-bar, .carousel-inner, etc.

https://developer.mozilla.org/es/docs/Web/CSS/Transiciones_de_CSS

**Comment by cvrebert** [comment]
Our vendor prefixing is accomplished via [Autoprefixer](https://github.com/postcss/autoprefixer).
[Our Autoprefixer configuration](https://github.com/twbs/bootstrap/blob/18ad53fc5662e0739a32f86d8dcbfbf5bd5b260a/grunt/configBridge.json#L21-L30) is set according to [our browser support policy.](http://getbootstrap.com/getting-started/#support)
Most likely the "missing" prefixes you mention aren't required for the versions of Firefox which we support. Or (pretty unlikely) there is a bug in Autoprefixer.
Thank you for your concern.
