### ISSUE TITLE
Site very slow after opening and closing a modal - Chrome 46.0.2490.71 m

### ISSUE THREAD

**Issue by Tiega91** [twbs/bootstrap#18016]
Since the update my site is driving me crazy, after i open/close a modal every further interaction that requires JS is super slow.
The console show no errors and the timeline also seems normal....

I tried the same with Firefox and there is no issue, someone similar problems?

EDIT: I'm using v3.3.5

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by Tiega91** [comment]
So the last day i try to clean up some code and try to isolate the issue.

It seems like that there is a problem with the amount of DOM element. The site has ~19.000 DOM elements, i know its quite a lot, if i reduce it to below 10.000 its working okay. So you see with this big site a example is a bit tricky :(

So i thought it is a "repaint" problem and i added "backface-visibility: hidden;" to test if it change something, no success.

Then i noticed that if i just click somewhere on the page in a empty area its working fine till i open a modal again.

Some ideas in which direction i should search to isolate the problem better?

best regards

**Comment by cvrebert** [comment]
> Some ideas in which direction i should search to isolate the problem better?

Nothing specific really. Just keep trying to simplify it; see also https://www.webkit.org/quality/reduction.html

If you ever come up with a specific reduced testcase for the problem, feel free to open a new issue. But without a testcase, there's nothing we can do. Can't debug without anything concrete to go on.
