### ISSUE TITLE
different top margin in headings building from sources

### ISSUE THREAD

**Issue by ShadowManu** [twbs/bootstrap#18023]
According to the [Headings and Paragraphs section in alpha-docs](http://v4-alpha.getbootstrap.com/content/reboot/#headings-and-paragraphs), Reboot overrides Normalize top margin (at least). The files in dist goes according to this.

However, while locally building with `grunt dist` (using `bower` and `libsass`) and using the generated files, the Normalize rules have higher priority than the Reboot ones (leaving a top margin instead).

**Comment by cvrebert** [comment]
Unable to reproduce with the latest `v4-dev` branch (807fb8847aa8cbe54ad371fccdec93b2518c1558).
