### ISSUE TITLE
Adjustment for the input file does not overflow in Firefox 

### ISSUE THREAD

**Issue by teamcreed** [twbs/bootstrap#18025]
adjustment for the input file does not overflow in Firefox - adding cuotes in "file" and blank space after the colon and blank space after the colon.

![overflow_input_file_firefox](https://cloud.githubusercontent.com/assets/14580377/10698724/5fc87fcc-7967-11e5-8186-2d8611d36466.PNG)

**Comment by cvrebert** [comment]
`.form-control` is only meant to be used on `<input>`s that are text-based, which does not include `<input type="file">`.
See https://github.com/twbs/bootlint/wiki/E042
