### ISSUE TITLE
Clearfix weird behavior

### ISSUE THREAD

**Issue by BuKinoshita** [twbs/bootstrap#18021]
What's the purpose of `display: table` on the `clearfix mixin`, is it a bug?

I'm getting weird behavior because of the display table.

**With display:table**
![screenshot 2015-10-22 13 21 10](https://cloud.githubusercontent.com/assets/6929565/10672767/09ebc4d0-78c0-11e5-910e-427a985bf107.png)

**Without display:table**
![screenshot 2015-10-22 13 21 39](https://cloud.githubusercontent.com/assets/6929565/10672790/2fda830c-78c0-11e5-99eb-db32922ba046.png)

It's mess with height ...

**Comment by cvrebert** [comment]
No, it's not a bug.
See https://github.com/twbs/bootstrap/blob/18ad53fc5662e0739a32f86d8dcbfbf5bd5b260a/less/mixins/clearfix.less#L8-L11 and http://nicolasgallagher.com/micro-clearfix-hack/
