### ISSUE TITLE
.text-left redundant to .text-xs-left ?

### ISSUE THREAD

**Issue by marekkobida** [twbs/bootstrap#18037]
The repeating class
	
	.text-left {
	  text-align: left; }

	.text-right {
	  text-align: right; }

	.text-center {
	  text-align: center; }

	.text-xs-left {
	  text-align: left; }

	.text-xs-right {
	  text-align: right; }

	.text-xs-center {
	  text-align: center; }

**Comment by cvrebert** [comment]
Fixed by #18317.
