### ISSUE TITLE
Navbar - Collapse bug

### ISSUE THREAD

**Issue by marekkobida** [twbs/bootstrap#18035]
Why are things shown inline?

<img width="476" alt="snimka obrazovky 2015-10-23 o 22 34 25" src="https://cloud.githubusercontent.com/assets/12018118/10704311/505c13ae-79d6-11e5-9609-55985516ff5d.png">

**Comment by cvrebert** [comment]
Duplicate of #17250. Navbars are still a work-in-progress in Bootstrap v4.
