### ISSUE TITLE
Remove useless .col-*-offset-12 and .col-xs-offset-0 classes

### ISSUE THREAD

**Issue by marekkobida** [twbs/bootstrap#18036]
Your grid system has `.col-*-offset-*` from 0 to 12 but we need only from 1 to 11.

`.col-xs-offset-0` = useless
`.col-xs-1` + `.col-xs-offset-12` is = 13 = bug

This example is correct:

|       From      |        To        |    |
|:---------------:|:----------------:|:--:|
|     .col-*-1    |     .col-*-12    | 12 |
| .col-*-offset-1 | .col-*-offset-11 | 11 |

**Comment by cvrebert** [comment]
@marekkobida Please open separate issues for separate suggestions in the future.

**Comment by cvrebert** [comment]
> `.col-xs-1` + `.col-xs-offset-12` is = 13 = bug

Well, given [the grid'd column wrapping feature](http://getbootstrap.com/css/#grid-example-wrapping), having more than 12 columns isn't wrong *per se*, but `.col-xs-offset-12` indeed doesn't seem to work as one might expect.

**Comment by cvrebert** [comment]
X-Ref: #16463, #16480

**Comment by mdo** [comment]
Yeah, they're useless.

**Comment by cvrebert** [comment]
Opened #18473 to fix this.

**Comment by cvrebert** [comment]
Fixed by #18473.
