### ISSUE TITLE
Add touch-action:manipulation to future-proof avoidance of 300ms click delay?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18044]
In particular, the next iOS Safari feature release should (modulo secret Apple machinations) support it (see http://trac.webkit.org/changeset/191452), whereas it's uncertain whether WebKit will (ever) decide to remove the delay on all pages with mobile viewports (see https://bugs.webkit.org/show_bug.cgi?id=150469) like Chrome et al. already do.
Some background on the delay: http://developer.telerik.com/featured/300-ms-click-delay-ios-8/
CC: Touchy guy @patrickhlauke

**Comment by patrickhlauke** [comment]
Seems legit to me. Now the question is where to add it. One could brutally add it to just
```
html, body { touch-action: manipulation; }
```
and thus kill any double-tap-to-zoom throughout (similar to what happens with `width=device-width` in Chrome/Firefox/Edge - see http://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay)...or we could (should, probably) be more surgical and only apply it to clickable controls (buttons, tabs, accordion triggers, etc).

**Comment by cvrebert** [comment]
Opened #18051 to implement this.
CC: @mdo

**Comment by cvrebert** [comment]
Fixed by #18051.
