### ISSUE TITLE
Where's `.navbar-text` ?

### ISSUE THREAD

**Issue by dudewheresmycode** [twbs/bootstrap#18049]
Did you drop support for the `navbar-text` sub-component in `v4-beta`?

v3 Reference http://getbootstrap.com/components/#navbar-text

**Comment by cvrebert** [comment]
v4's navbar is currently an incomplete work-in-progress.

**Comment by tshinnic** [comment]
Looks like this (tested) would be a temporary replacement/workaround:
```
    .navbar-text {
      float: left;
      padding-top: .425rem;
      padding-bottom: .425rem;
      zzmargin-right: 1rem;
      zzmargin-left: 1rem;
    }
```
Works with the text modifiers like `.text-muted` and the position modifier `.pull-right`.

One nit with the current state of change is left/right margins between navbar items. `.nav-item`s assume nothing for the side margins, `.navbar-brand` does a right margin, etc.  You'll need to enable whichever margin seems right for your usage.

**Comment by mdo** [comment]
Coming in #19890.

**Comment by mdo** [comment]
Brought back in Alpha 5 with #19890.
