### ISSUE TITLE
bootstrap glyphicons are not displaying in  IE-9, IE-10 with document view = IE-7 standard 

### ISSUE THREAD

**Issue by RatanPaul** [twbs/bootstrap#18058]
Below is html code
```
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.css"/>
</head>
<body>
<span class="glyphicon glyphicon-search"></span>

<span class="glyphicon glyphicon-home"></span>
<span class="glyphicon glyphicon-file"></span>
<span class="glyphicon glyphicon-time"></span>
</body>
</html>
```
If we try to run this code in IE-9 or IE 10 and select document view = IE-7 standard 
then font don't render.

for selecting  document view press F12 and select document view = IE-7 standard

**Comment by kkirsche** [comment]
@RatanPaul is this for bootstrap 3 or 4? Glyph icons are removed from V4, if using this you will need to manually include your own icon font.

**Comment by RatanPaul** [comment]
@kkirsche This is /twitter-bootstrap/3.3.5/

**Comment by patrickhlauke** [comment]
As IE7 itself is not supported http://getbootstrap.com/getting-started/#support, forcing IE into IE7 standard rendering is also not supported, I'm afraid.

**Comment by patrickhlauke** [comment]
Ah, there's even an actual mention of compat modes here http://getbootstrap.com/getting-started/#support-ie-compatibility-modes
