### ISSUE TITLE
nav-bar does not work

### ISSUE THREAD

**Issue by varghesep** [twbs/bootstrap#18052]
I checked out the [dashboard example](http://v4-alpha.getbootstrap.com/examples/dashboard/) in IE 11 and Chrome. The nav-bar at the top is not behaving correctly. Please see the attached image which shows how it looks like on my machine.

How can make it work?

![menu](https://cloud.githubusercontent.com/assets/12233474/10715310/ef504e08-7adf-11e5-8688-9b0c05e0156c.PNG)

**Comment by cvrebert** [comment]
Duplicate of #17816.
