### ISSUE TITLE
v4 navbar with container inside results in extra padding

### ISSUE THREAD

**Issue by Nemo64** [twbs/bootstrap#18053]
I build a simple navbar like shown in the docs with the container inside: http://v4-alpha.getbootstrap.com/components/navbar/#containers

The problem is that in mobile layout, as soon as the container has the size of the page, the content inside the navbar does no longer align with the normal content of the page.

Here the example: http://jsbin.com/fisovineku/1/edit?html,output

a simple workaround is to remove the padding of the navbar but that would require another class on the navbar so it isn't a nice automatic solution.

**Comment by Deilv** [comment]
Why use a separate container?

**Comment by Deilv** [comment]
If you remove padding, then the collapse animation breaks. This is being worked on afaik.

**Comment by Nemo64** [comment]
You mean why i have one inside the navbar and one below?
The navbar has 100% width of the page but the content not.
Thats why there are 2 containers.

Basically it's the same what the bootstrap 3 documentation has for a navigation. There the navbar has no padding and that's why the container always fits... event though the side navigation is a little missplaced on mobile there.

**Comment by Deilv** [comment]
The navbar has no padding in v4 either. Perhaps a special navbar-container with smaller padding would solve your issue?

**Comment by Nemo64** [comment]
I don't think so. If the padding on the container is removed, the content
will be too wide in a layout > xs.

That would work however if the container inside the navbar would be smaller
in general.

Something like:
.navbar > .container {padding: 0; width: layout-container-width -
normal-padding * 2:}

Ilias <notifications@github.com> schrieb am So., 25. Okt. 2015, 15:55:

**Comment by Deilv** [comment]
I just tested it on my laptop and actually saw what you mean. As soon as the screen size becomes smaller than 576px, navbar > container maintains it's left padding while the other container doesn't and the two lines are no longer aligned. Looking into this...

**Comment by Deilv** [comment]
``` css
.navbar {
  padding: 0;
}
```
Seems to solve this. Still working on it...
