### ISSUE TITLE
sm container width is larger than minimum sm viewport width

### ISSUE THREAD

**Issue by Deilv** [twbs/bootstrap#18054]
The (sm) max-width of .container is larger than the (sm) breakpoint (576px > 544px). Wouldn't that let containers overflow the viewport?

scss/_variables.scss
```javascript
// Grid breakpoints
//
// Define the minimum and maximum dimensions at which your layout will change,
// adapting to different screen sizes, for use in media queries.

$grid-breakpoints: (
  // Extra small screen / phone
  xs: 0,
  // Small screen / phone
  sm: 544px,
  // Medium screen / tablet
  md: 768px,
  // Large screen / desktop
  lg: 992px,
  // Extra large screen / wide desktop
  xl: 1200px
) !default;


// Grid containers
//
// Define the maximum width of `.container` for different screen sizes.

$container-max-widths: (
  sm: 576px,
  md: 720px,
  lg: 940px,
  xl: 1140px
) !default;
```

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by glebm** [comment]
Has anyone been able to reproduce this? The container should fill the screen without overflowing, as max-width only restricts the default width of 100%.

**Comment by cvrebert** [comment]
At the least, it's weird from a consistency perspective. Only `sm` has a container max width larger than its minimum viewport width.

**Comment by glebm** [comment]
Perhaps this is because on viewports under that width there is no space for a gutter. It is typically a tablet in portrait orientation.

**Comment by Deilv** [comment]
Something along the lines of what @cvrebert said. I found that inconsistency accidentally while digging for another issue. It's easy to fix. In fact it would take longer to setup a jsbin than fix it. The actual question is what the number should be. @glebm was the last to change the number, so I guess he could shed some light on this.

**Comment by mdo** [comment]
Yeah, container should be narrower—or maybe the same? It's tougher for the super narrow devices like phones because in most cases you really don't want the container to be overly nested. You want just the gutters and nothing more in most cases.

**Comment by Deilv** [comment]
After some research on available device resolutions, I'd like to recommend we change the breakpoints and the respective max-widths to:

File: scss/_variables.css
```css
// Grid breakpoints
//
// Define the minimum and maximum dimensions at which your layout will change,
// adapting to different screen sizes, for use in media queries.

$grid-breakpoints: (
  // Extra small screen / phone
  xs: 0,
  // Small screen / phone
  sm: 540px,
  // Medium screen / tablet
  md: 768px,
  // Large screen / desktop
  lg: 900px,
  // Extra large screen / wide desktop
  xl: 1200px
) !default;

// Grid containers
//
// Define the maximum width of `.container` for different screen sizes.
$container-max-widths: (
  sm: 540px,
  md: 730px,
  lg: 855px,
  xl: 1140px
) !default;
```

Please note how I change 544 to 540 (which is considered qHD) and 992 to 900 (which is the breakpoint between older tablets and newer tablets/laptops).

If these numbers look ok to you, I can post a PR to close this issue.

Also, any particular reason why these settings also exist in scss/bootstrap-grid.css which then imports scss/_variables.css to overwrite the values?

**Comment by cvrebert** [comment]
> Please note how I change 544 to 540 (which is considered qHD)

I'm not certain how relevant that is, given that we're talking about CSS pixels rather than physical pixels. For example, the Samsung Galaxy S4 Mini has a qHD screen, but according to http://viewportsizes.com/?filter=galaxy%20s4%20mini its CSS device-width is either 360px or 640px (depending on orientation).

> and 992 to 900 (which is the breakpoint between older tablets and newer tablets/laptops).

Could you share the data that led you to this conclusion? It's hard to evaluate such a suggestion without seeing any evidence.

> Also, any particular reason why these settings also exist in scss/bootstrap-grid.css which then imports scss/_variables.css to overwrite the values?

Only @mdo can really answer that since he wrote those files. My guess would be that the variables in `bootstrap-grid.css` were copied into there for convenience and shouldn't be `!default`.

**Comment by Deilv** [comment]
I used data from [this page](http://spirelightmedia.com/resources/responsive-design-device-resolution-reference)

**Comment by hanakin** [comment]
you should also consider that all your container sizes should be evenly divisible by 12 and the columns should be divisible by the spacer size

I would suggest the following values

````
$grid-breakpoints: (
    // Extra small screen / phone
    xs: 0,
    // Small screen / phone
    sm: 544px,
    // Medium screen / tablet
    md: 800px,
    // Large screen / desktop
    lg: 992px,
    // Extra large screen / wide desktop
    xl: 1200px
) !default;

$container-max-widths: (
    sm: 576px,
    md: 768px,
    lg: 960px,
    xl: 1152px
) !default;

the gutter should also match the spacer size

so 32px instead of the current 30px

**Comment by mdo** [comment]
Hasn't been an issue since August apparently: eabed0edf84c61bb4095ce8f92f41e58552785b9.

**Comment by cvrebert** [comment]
@mdo Erm, the OP refers to code from that commit. I don't follow your logic.
