### ISSUE TITLE
jekyll serve not working - cannot load such file

### ISSUE THREAD

**Issue by janpetras** [twbs/bootstrap#18059]
Pause:bootstrap-4.0.0-alpha ian$ jekyll serve
Configuration file: /Users/ian/GitHub/bootstrap-4.0.0-alpha/_config.yml
/usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-redirect-from (LoadError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:26:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/site.rb:79:in `setup'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/site.rb:41:in `initialize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:29:in `new'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/commands/build.rb:29:in `process'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
Pause:bootstrap-4.0.0-alpha ian$

**Comment by patrickhlauke** [comment]
this would be an issue with jekyll / your current setup, not with bootstrap, i think
