### ISSUE TITLE
.collapse.in does not work on table rows (<tr>)

### ISSUE THREAD

**Issue by ivebeenlinuxed** [twbs/bootstrap#18060]
Branch: v4-dev (testing v4 Alpha 1)

It looks like 27df020 commented out [some stuff in scss/_animation.scss](https://github.com/twbs/bootstrap/blob/2332a3f536be75c4407557435c91cae359816625/scss/_animation.scss#L16-L17) which now stops collapse working on table rows.

I haven't used less/sass (not any time yet!), but it looks like line 16-17 need to be uncommented.

// tr&.in    { display: table-row; }
// tbody&.in { display: table-row-group; }

**Comment by cvrebert** [comment]
Perhaps we should consider reworking the animation scheme along the lines of the responsive utility classes, so that we only ever set `display:none`, and leave the normal `display` at its default, thus making it generic with respect to the element's non-hidden `display` value.

**Comment by arashataei** [comment]
Yeap

**Comment by ivebeenlinuxed** [comment]
If you really want a polish, the animation doesn't work on table rows either so the result it that the row displays, without animation, 1/2 second after clicking.

**Comment by mdo** [comment]
Fixed with #20768 with Alpha 5.
