### ISSUE TITLE
Tip: Bootstrap Template Another Way (BTAW)

### ISSUE THREAD

**Issue by pacav69** [twbs/bootstrap#18062]
Bootstrap Template Another Way
This setup is based on Modern Business template from Start Bootstrap using the following:

Grunt
Bower components
Assemble
handlebars
less
concat
uglify
fontawesome
With this configuration it provides a scaffold structure that can be simply combined to form a single web-page or a multi-page website.

https://github.com/pacav69/btaw/

**Comment by cvrebert** [comment]
This issue tracker is for reporting bugs or making feature requests.
Please post articles/announcements to other, more relevant community forums instead of here. Thanks!
