### ISSUE TITLE
Navbar collapse does not hide when clicked again

### ISSUE THREAD

**Issue by rogersbrad** [twbs/bootstrap#18064]
This may be similar to #12852 but in Windows 7, Chrome/IE, the VS2015 MVC app, the auto generated form with the navbar, when the display is manually sized to be small until the text hides and the button appears with the lines, click as expected it will display the items.  click again? it starts to close then stops and covers up other items on the display where it should close.

Searched for a fix or new version, did not find a solution.

**Comment by cvrebert** [comment]
Please post a JS Bin or JSFiddle that demonstrates the problem.

**Comment by rogersbrad** [comment]
http://jsbin.com/puzitivosa/edit?html,output 
I am trying to duplicate this on jsbin;  used the bootstrap CDN, but will also try by pasting the bootstrap.css from my system

its not showing the items as expected,  and here http://jsfiddle.net/cW9sA/43/  is someone's GOOD example that shows the correct operation.    So far have not found out why that one works and mine, which is fully default from the MVC scaffolding, doesnt

**Comment by twbs-lmvtfy** [comment]
Hi @rogersbrad!

You appear to have posted a live example (http://fiddle.jshell.net/cW9sA/43/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 81, column 1: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`
* line 20, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.5 ; saw what appears to be usage of Bootstrap 2.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @rogersbrad!

You appear to have posted a live example (http://jsbin.com/puzitivosa/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 9, column 1 thru column 232: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 9, column 1 thru column 232: Element ```` link ```` is missing required attribute ```` property ````.
* line 12, column 1 thru column 214: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 12, column 1 thru column 214: Element ```` link ```` is missing required attribute ```` property ````.
* line 15, column 1 thru column 214: Attribute ```` integrity ```` not allowed on element ```` script ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rogersbrad** [comment]
Am not sure if the code example just posted shows up or not?  Am new here and to posting with the fiddle or jsbin, but what i posted then caused 2 posts that showed several validation errors.  Dont know if its only on my screen or public, but I will work on this.
