### ISSUE TITLE
Bootstrap themes: Table's global checkbox doesn't work

### ISSUE THREAD

**Issue by DriftingSteps** [twbs/bootstrap#18075]
The link is - https://bootstrap-themes.github.io/dashboard/order-history/index.html

Screenshot - http://i.imgur.com/Syq64Ef.png

Clicking this is supposed to check all the checkboxes on the current page, but apparently it doesn't work. Or is it supposed to not work in the first place? Either way, I felt that this needed to be pointed out, seems like a design bug.

Regards.

**Comment by dkfiresky** [comment]
The issue occurred because of sorting functionality overwrite the checkbox click behaviour. Is there any way to disable sorting on the first column of the table?

**Comment by cvrebert** [comment]
Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker :
> Please **do not** open issues regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`

Thanks.
