### ISSUE TITLE
Buttons on mobile (iOS) get "stuck" in active state

### ISSUE THREAD

**Issue by ilyador** [twbs/bootstrap#18076]
It seems like quite a common issue but I could not find any discussion about it. Is it on purpose? From a Ui point of view it is confusing, unless a the button is specified as a toggle and meant to stay pressed.

**Comment by dkfiresky** [comment]
@ilyador The buttons might look pressed because of the `:focus` state.

**Comment by ilyador** [comment]
I found the official solution: http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#sticky-hoverfocus-on-mobile

**Comment by ilyador** [comment]
But I can't find where to set `$use-hover-media-query`

**Comment by ilyador** [comment]
Found it! It is `$enable-hover-media-query` (not `$use-...`)

You should update it

**Comment by kkirsche** [comment]
Thanks for finding that. Pull request with the fix submitted @ilyador

**Comment by mdo** [comment]
Fixed by #18077.
