### ISSUE TITLE
v4: navbar-form removed, but still in documentation

### ISSUE THREAD

**Issue by davidjb** [twbs/bootstrap#18087]
I've been testing v4 and noticed that the documentation and examples in the `v4-dev` branch (https://github.com/twbs/bootstrap/blob/v4-dev/docs/components/navbar.md) mention `.navbar-form`, but the class was removed in this commit:  https://github.com/twbs/bootstrap/commit/d6b6a20a0daaed70ec6f395dd813ea460b394e6c#diff-df1f74faf207a474f1d78c86393221c8L162

Is this documentation no longer needed / an entry needed for the Migration documentation?

**Comment by cvrebert** [comment]
@mdo Can you confirm whether `.navbar-form` is supposed to be defunct?

**Comment by mdo** [comment]
It's been removed. Fixed in 21b15d4.

**Comment by cvrebert** [comment]
It's also used several times in [the example pages](https://github.com/twbs/bootstrap/tree/master/docs/examples).

**Comment by cvrebert** [comment]
And this snippet of CSS is now presumably unnecessary:
https://github.com/twbs/bootstrap/blob/21b15d450dd013a8b96c3b8ae8176146f6df7ea9/scss/_forms.scss#L395-L400

**Comment by cvrebert** [comment]
Fixed the example pages in da87424a796a6c61866caaed1069360c822cdd4d

**Comment by mdo** [comment]
Haven't dug into those bits completely, but I updated the comment at least. See 30aad99.
