### ISSUE TITLE
Add Flexbox utility classes

### ISSUE THREAD

**Issue by karlhorky** [twbs/bootstrap#18088]
Would there be any interest in adding some utility classes for simple flexbox properties? The `row`s and `col`s are a good starting point, but they miss out on a bit of the *flexibility* of flexbox. :trollface: 

Some possibilities:

- `display: flex` without `flex-wrap` set
- ~~`flex-order`~~ `order`
- `flex-direction`
- `align-items`
- `align-self`

I'm putting something together for myself to use, and was wondering if a pull request would be welcome.

**Comment by mmjaeger** [comment]
+1

**Comment by ilyador** [comment]
+1

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by BlockWorld** [comment]
+1

**Comment by liquidvisual** [comment]
+1

**Comment by psc064** [comment]
Like https://github.com/trenthogan/flexbox-utility?

**Comment by karlhorky** [comment]
Yeah, something like that.

**Comment by DanCouper** [comment]
+1 on this. I'm retrofitting a big commercial site at the minute using BS4, and lack of flex utils has been a big pain point. (as an aside, the grid is often the opposite of what flexbox is good at [flex is implicit, not explicit; declarative, not imperative], it steamrollers a lot of what makes flex useful)

this is the file I'm using alongside BS at the minute - it's just a set of classes for most usecases: https://gist.github.com/DanCouper/98df51f393fb7604b7cd

The one's I'm using heavily: `.flex-1` all over the place,  `.order`, vertical alignment via `.align-center`

**Comment by karlhorky** [comment]
Addressed in #19099

**Comment by DrChills** [comment]
+1
