### ISSUE TITLE
.input-group-btn slightly too short in IE9-11

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18083]
Demo: http://jsfiddle.net/9waquk0b/
Works fine in Chrome, Safari, and Firefox, but not IE11.
Refs https://github.com/twbs/bootstrap/issues/17035#issuecomment-151643774
Screenshot:
![proof](https://cloud.githubusercontent.com/assets/419884/10773130/e66196ca-7cb6-11e5-9256-55f35702b2ff.png)

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/9waquk0b/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [XX0](https://github.com/twbs/bootlint/wiki/XX0): Your example is too large for Bootlint to process! Please simplify your example and make it smaller.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
MS Edge isn't affected.

**Comment by cvrebert** [comment]
In IE11, the `<input>`'s content height is 18.4px instead of 24px like in other browsers. Couldn't figure out why; guess I'm not pro enough; `font-size` and `line-height` are the same as Chrome.

Also, IE11 "rounds" the `<input>`'s `0.375rem` of top/bottom padding to `0.37rem`, thus making the computed vertical padding `5.92px` instead of `6px`.

And the `.input-group-addon`'s content height is 16px instead of 24px. I'm lost.

CC: @mdo

**Comment by NKCSS** [comment]
FYI: Also occurs on windows phone.

**Comment by tagliala** [comment]
It seems that the rounding up to the second decimal is presentational only

Layout:

![image](https://cloud.githubusercontent.com/assets/556268/11168633/edbddc68-8b97-11e5-896b-7e253f66786a.png)

--

Calculated:
![image](https://cloud.githubusercontent.com/assets/556268/11168639/2374c970-8b98-11e5-92b0-9ec23c13a8f4.png)

**Comment by tagliala** [comment]
Hi again,

I had some time to dig into this issue.

Apparently, `line-height` (still) doesn't work as expected for input tags

Minimal amount of css to reproduce this: https://jsfiddle.net/tagliala/fmkktn2p/

Hope it helps

**Comment by cvrebert** [comment]
Re-tested in a263e194194969fa0daf5fde938a330f6c77be81. Things have improved; the issue now is that `.input-group-btn`s are slightly too short in IE9-11:
<img width="866" alt="ie11" src="https://cloud.githubusercontent.com/assets/419884/12911801/bf342ab2-cec9-11e5-967e-d0a097677ee1.png">

Testcase: http://jsbin.com/biqube/edit?html,css,output
CC: @mdo

**Comment by mdo** [comment]
No longer an issue with the move to flexbox.
