### ISSUE TITLE
Use mixin to generate card color variations

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18096]
i found that in the current version the cards module has not got `card-variant()` mixins, just like the button module.
Compare:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L90
and
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L56
Of course i understand the card variant only set two properties, but on the other hand not having these mixins seems inconsequent and not futur proof?

**Comment by petetnt** [comment]
Using mixins would easily enable outline variants too like I suggested in #17243 :+1:

**Comment by mdo** [comment]
Merged #18099.
