### ISSUE TITLE
where can i check how regulary v4 is updated?

### ISSUE THREAD

**Issue by elgubenis** [twbs/bootstrap#18101]
where can i check how regulary v4 is updated?

**Comment by kkirsche** [comment]
Here (Github) — v4-dev branch

**Comment by cvrebert** [comment]
You can follow our progress in the [`v4-dev` branch](https://github.com/twbs/bootstrap/tree/v4-dev).
Future v4 release announcements will be released through the usual channels: [our blog](http://blog.getbootstrap.com/) and [out Twitter account](https://twitter.com/getbootstrap).
