### ISSUE TITLE
v4: light vs dark in navbars and cards

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18115]
I found that the navbar component uses the `navbar-light`, `navbar-dark` classes to create link colors. The output of this classes can be set with the `$navbar-light-` and `$navbar-dark-*` variables.
The card modules uses a `.card-inverse` to set a light font.
Should it be more consequent when the card module also got a `card-light` and `card-dark` class? Including some variable to set them?

Also the navbar use the contextual backgrounds classes, shouldn't the card modules use these classes too? Which requires having contextual border classes too.

**Comment by Wolfr** [comment]
It is preferable for me to use `inverse` as naming convention, because depending on the project, that might mean dark or light. If the project started out with mostly dark UI, inverse actually means light UI.
