### ISSUE TITLE
v4: suggestion to introduce a color contrast function

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18119]
for instance: http://compass-style.org/reference/compass/utilities/color/contrast/#function-contrast-color

Useful in among others `mixins/background-variants.scss`:

```
// Contextual backgrounds

// [converter] $parent hack
@mixin bg-variant($parent, $color) {
  #{$parent} {
    color: contrast-color($color,$gray-dark,$gray-lightest);
    background-color: $color;
  }
  a#{$parent} {
    @include hover-focus {
      background-color: darken($color, 10%);
    }
  }
}
```

See also: https://github.com/twbs/bootstrap/issues/18118

**Comment by cvrebert** [comment]
X-Ref: #3224

**Comment by mdo** [comment]
Yeah, could be nice to do something here as a utility function across the project.

**Comment by Superpencil** [comment]
I'd like to suggest an actual dark/light distinction with a single `body.inverse` class.
I'd go further and say an automatically generated color-palette would be impressive as well.
Perhaps copy https://github.com/simurai/duotone-light-syntax
And https://github.com/simurai/duotone-dark-syntax
