### ISSUE TITLE
Glyphicons font icon shows garbage character on firefox

### ISSUE THREAD

**Issue by quchunguang** [twbs/bootstrap#18114]
OS: ubuntu 15.10
BROWER: firefox 41.0.2

![2015-10-31-020753_1600x876_scrot](https://cloud.githubusercontent.com/assets/383218/10854338/04ca6b84-7f76-11e5-9db3-a6d5dd8c54cf.png)

```html
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
</button>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Star
</button>
```

Chrome works fine.

**Comment by kkirsche** [comment]
What version of bootstrap? Bootstrap 4 dropped glyph icons which is why you'd get nothing. Search the issues to find the previous threads :) (on mobile and GitHub makes search hard on mobile)

**Comment by cvrebert** [comment]
Unable to reproduce, so this is likely a problem related to your particular environment.
Please use StackOverflow (or similar) for troubleshooting questions. Thanks.

**Comment by quchunguang** [comment]
@kkirsche : The version is i just pulled from here yesterday (f5bb168).

@cvrebert : OK.
