### ISSUE TITLE
v4: hardcoded white values (#fff) in both _cards.scss and mixins/background_variants.scss

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18118]
suggested solution:

in `_variables.scss`:

```
$body-bg:                    #fff !default;
$body-color:                 $gray-dark !default;
$body-color-inverse:    $gray-lightest !default;
```

then in `_cards.scss`:

//
// Inverse text within a card for use with dark backgrounds
//

```
.card-inverse {
  .card-header,
  .card-footer {
    border-bottom: .075rem solid rgba($body-color-inverse,.2);
  }
  .card-header,
  .card-footer,
  .card-title,
  .card-blockquote {
    color: #fff;
  }
  .card-link,
  .card-text,
  .card-blockquote > footer {
    color: rgba($body-color-inverse,.65);
  }
  .card-link {
    @include hover-focus {
      color: $body-color-inverse;
    }
  }
}
```

and in `mixins/background-variants.scss`:

```
// Contextual backgrounds

// [converter] $parent hack
@mixin bg-variant($parent, $color) {
  #{$parent} {
    color:$body-color-inverse;
    background-color: $color;
  }
  a#{$parent} {
    @include hover-focus {
      background-color: darken($color, 10%);
    }
  }
}
```

**Comment by bassjobsen** [comment]
Also in _variables.scss white has been hard code many times:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L215
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L246
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L333
etc.

I think most declarations can be set to `$body-bg` after all, cause when changing `$body-bg` you possible want to keep other things, like dropdown background background,white. Label background should possible be transparent, and so on...
See also: https://github.com/twbs/bootstrap/pull/18172

There is possible a need for variables which set the lightest and darkest colors?

```
$color-lightest: #fff !default;
$color-darkest: #000 !default;

$body-bg: $color-lightest !default;
````
I also found https://github.com/twbs/bootstrap/blob/v4-palettes/scss/_variables.scss which still do not define a lightest (white) and darkest (black color).

Also the button font / background colors seems to be inconsequent for the lightes and darkest colors:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L246
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L250

When the lightest color for dark buttons is white the darkest color for light button should be black? Or alternatively the lightest color should be $gray-lightest?

**Comment by mdo** [comment]
I'm fine leaving these hardcoded for now. Not too keen on adding contrast functions at this point, or trying to pair multiple variables if I can avoid it. Thanks though!
