### ISSUE TITLE
Not able to expand and collpase angular-ui-tree with Bootstrap v4.0.0-alpha

### ISSUE THREAD

**Issue by abpati** [twbs/bootstrap#18126]
we are using Bootstrap v4.0.0-alpha in our project, for tree view I am using angular-ui-tree, it's expand and collpase is working with Bootstrap-v3.3.5 but when we change it to v4.0.0-alpha, tree stops  expanding and collapasing.

**Comment by cvrebert** [comment]
We are unable to provide assistance regarding third-party libraries such as angular-ui-tree. Please ask on one of the community forums listed in https://github.com/twbs/bootstrap#community instead.
