### ISSUE TITLE
miscalculation for popover - div.popover 

### ISSUE THREAD

**Issue by vikasna** [twbs/bootstrap#18121]
For pages which are very wide (>1600px), when the page is scrolled the left position of div.popover is not set properly. The popover arrow is placed properly under the element that is clicked, but the content itself is placed far from the arrow.

I am working around using the following code - (in the click handler of the button element; after calling the popover 'show' following lines are added)

if ($(document).scrollLeft()>0){
                                                        $('.arrow').css('left','');
                                                        $('.popover').css('left', parseInt($(this).position().left)-$('.popover').width()/2+5);
                                                    }

**Comment by cvrebert** [comment]
What version of Bootstrap are you using?

**Comment by vikasna** [comment]
I am using Bootstrap v3.3.5

**Comment by cvrebert** [comment]
Punting as WontFix per https://github.com/twbs/bootstrap/issues/15590#issuecomment-113321235
Patches would be welcomed, but the Bootstrap Core Team doesn't have the time/bandwidth to write such a patch ourselves.
