### ISSUE TITLE
Add responsive margin-bottom utility classes

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [twbs/bootstrap#18122]
A pluggable margin-bottom that is `20px` in `xs`, `30px` in `sm/md`, and `40px` in `lg`. 

This is something I find myself needing increasingly in diverse projects. Who knows if I need a margin on component XYZ? Shouldn't be built-in into the component, but optional, IMO.

I also keep anti-component-margin classes undoing the previous components margin (by negative `margin-top`), for example when an element with component-margin is visible only in certain screen sizes.

Dunno if it can be something to add as a responsive utility.

    @component-margin-xs: 20px;
    @component-margin-sm: 30px;
    @component-margin-md: 30px;
    @component-margin-lg: 40px;

    .component-margin {
      margin-bottom: @component-margin-xs;
  
      @media (min-width: @screen-sm-min) {
        margin-bottom: @component-margin-sm;
      }
      @media (min-width: @screen-md-min) {
        margin-bottom: @component-margin-md;
      }
      @media (min-width: @screen-lg-min) {
        margin-bottom: @component-margin-lg;
      }
    }

    .component-margin-xs {
      margin-bottom: @component-margin-xs;
  
      @media (min-width: @screen-sm-min) {
        margin-bottom: 0;
      }
    }

    .component-margin-sm {
      @media (min-width: @screen-sm-min) {
        margin-bottom: @component-margin-sm;
      }
      @media (min-width: @screen-md-min) {
        margin-bottom: 0;
      }
    }

    .component-margin-md {
      @media (min-width: @screen-md-min) {
        margin-bottom: @component-margin-md;
      }
      @media (min-width: @screen-md-min) {
        margin-bottom: 0;
      }
    }

    .component-margin-lg {
      @media (min-width: @screen-lg-min) {
        margin-bottom: @component-margin-lg;
      }
    }

**Comment by mdo** [comment]
Thanks, but we'll pass for now. Too many utility classes and if we do this one direction, folks will ask and expect all four directions.

**Comment by kfriend** [comment]
This is too bad. The new responsive helpers (e.g. text-xs-left, pull-md-right) are useful, but if it came down to it, I'd rather have responsive spacing helpers. They go well with the grid system. 

I will often build something out using the grid classes, then still end up having to target specific elements in CSS, only to adjust margins at specific widths.

Maybe in a future version? Let's hope!
