### ISSUE TITLE
Move Util variable to bootstrap namespace

### ISSUE THREAD

**Issue by JoyceBabu** [twbs/bootstrap#18136]
Bootstrap v4 has introduced a new `Util` variable in global namespace. Please rename it to a bootstrap specific name like `BootstrapUtil` or `Bootstrap.util`. It is a common variable name, and there is a high probability that such a variable already exists. For example, our app already include a `Util` collection with utility methods like `notify`, `highlight` etc.

**Comment by cvrebert** [comment]
Unless I'm missing something, it's not global; it's in the `util` ES6 module. And it doesn't seem to get exported as a global after transpilation to ES5 either, otherwise there'd be a `window.Util` on http://v4-alpha.getbootstrap.com/components/buttons/
So please explain what leads you to believe that it's global.

**Comment by JoyceBabu** [comment]
I tried to create my own custom build (without tooltip and popover plugins) by concatenating the `.js` files in `js/dist/` using `gulp-concat`. Do I need to include `util.js` in that case?

**Comment by cvrebert** [comment]
Following the Gruntfile's current approach (which I don't like, but that's a matter for another issue), the way to create such a custom build would be to concatenate the desired/required subset of the `js/src/` files and then run Babel over the result with the `modules: 'ignore'` option set.

**Comment by JoyceBabu** [comment]
When I use `{presets: ["es2015"], modules: "ignore"}` options, babel is not generating any output :-(

When I use `{presets: ["es2015"]}`, it is working fine. I am using Gulp not Grunt

**Comment by mdo** [comment]
Closing out since I don't see a specific action to do here. Holler if we need to reopen though.
