### ISSUE TITLE
Left edges of headings and .row>.form-control-label don't align

### ISSUE THREAD

**Issue by Gillardo** [twbs/bootstrap#18130]
I seem to be having a funny problem with form-group and row.  it says on the migration page, that you now need to add .row to .form-group in order to use grid layout.

Here is my html, which i believe is correct

```
<h4>Company Details</h4>
<div class="row form-group">
    <label class="form-control-label col-sm-3">Business/Region or Company</label>
    <div class="col-sm-9">
        <module-data-form-field form-field="field">
            <span> UL East/ North East&nbsp;</span>    
        </module-data-form-field>
    </div>
</div>
```

But on screen, you can see that it seems to be out of alignment with the parent heading

![example2](https://cloud.githubusercontent.com/assets/7406381/10884750/af98534e-8171-11e5-902e-6e718b1be2bf.PNG)

I have tried turning on the enable-flex option, but it seems to make no difference.  Is this a current bug?

**Comment by cvrebert** [comment]
What the heck is `module-data-form-field`?

**Comment by Gillardo** [comment]
Sorry copied and pasted from raw html. That is just an angular custom tag.
It is treated as a normal div.

**Comment by cvrebert** [comment]
This seems to be caused by the horizontal padding set by `.form-control-label`, which overrides the padding set by the grid column classes.
CC: @mdo

**Comment by Gillardo** [comment]
So it is a bug then. I didng know if it was a bug or i wax doing something
wrong.

Thanks

**Comment by heruan** [comment]
I confirm, here's simple fiddle: http://jsfiddle.net/heruan/4ejpdyos/
Sample code:
```html
<div class="container">
    <fieldset>
        <legend>Fieldset</legend>
        <div class="form-group row">
            <label class="form-control-label col-sm-2">Label</label>
            <div class="col-sm-10">
                <input class="form-control" type="text" />
            </div>
        </div>
        <div class="form-group row">
            <label class="form-control-label col-sm-2">Label</label>
            <div class="col-sm-10">
                <input class="form-control" type="text" />
            </div>
        </div>
    </fieldset>
    <p>Paragraph</p>
</div>
```
![screen shot 2015-11-05 at 14 44 00 2](https://cloud.githubusercontent.com/assets/851745/10969996/fe37b9b6-83cb-11e5-80fc-187e04284349.png)

**Comment by mdo** [comment]
Coming in #19141.
