### ISSUE TITLE
Responsive heading sizes

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [twbs/bootstrap#18137]
Okay, this one's seriously useful: Pleasant heading sizes in all devices (the H1 is a little too H1 on a mobile)

(10% smaller headings in each mode, except for `xs`, which is 20% smaller than `sm`)

    .responsive-headings(@tag-name){
      @selector: ~"@{tag-name}, .@{tag-name}";
      @size-variable: ~"font-size-@{tag-name}";
  
      @{selector} {
        font-size: @@size-variable * 0.6;
      }
  
      @media (min-width: @screen-sm-min) {
        @{selector} {
          font-size: @@size-variable * 0.8;
        }
      }
      @media (min-width: @screen-md-min) {
        @{selector} {
          font-size: @@size-variable * 0.9;
        }
      }
      @media (min-width: @screen-lg-min) {
        @{selector} {
          font-size: @@size-variable;
        }
      }
    }

    .responsive-headings(h1);
    .responsive-headings(h2);
    .responsive-headings(h3);
    .responsive-headings(h4);
    .responsive-headings(h5);
    .responsive-headings(h6);

**Comment by cvrebert** [comment]
X-Ref: #16523

**Comment by cvrebert** [comment]
@mdo Is this inadmissible per #17095?

**Comment by Skwai** [comment]
Would agree with this, headings can be very large on small devices, even if the root font-size is reduced.

A way to declare the factor by which headings are scaled up and down by screen size would be great.

**Comment by bjorn-ali-goransson** [comment]
I noticed the smaller headings get a bit too small, so here's a modified version...

    .responsive-headings(@tag-name, @multiplier){
      @selector: ~"@{tag-name}, .@{tag-name}";
      @size-variable: ~"font-size-@{tag-name}";
  
      @{selector} {
        font-size: @@size-variable * (1 - (0.4 * @multiplier));
      }
  
      @media (min-width: @screen-sm-min) {
        @{selector} {
          font-size: @@size-variable * (1 - (0.2 * @multiplier));
        }
      }
      @media (min-width: @screen-md-min) {
        @{selector} {
          font-size: @@size-variable * (1 - (0.1 * @multiplier));
        }
      }
      @media (min-width: @screen-lg-min) {
        @{selector} {
          font-size: @@size-variable;
        }
      }
    }

    .responsive-headings(h1, 1);
    .responsive-headings(h2, 1);
    .responsive-headings(h3, 1);
    .responsive-headings(h4, 0.7);
    .responsive-headings(h5, 0.6);
    .responsive-headings(h6, 0.5);

Now, the smallest headings get kinda undistinguishable, but that's the price you pay when using h6-h7 with default styles to start with.

**Comment by mdo** [comment]
Thanks, but we'll pass for now. We can tweak the type scale, but I'm inclined to leave it as-is with a simpler and easier to understand behavior across devices.

**Comment by jacargentina** [comment]
@mdo Some words to give this some importance.

The www.getbootstrap.com website describes bootstrap as:

### Bootstrap is the most popular HTML, CSS, and JS framework for *developing responsive, mobile first* projects on the web. ###

That very text, has `font-size: 30px` when on large device, but switching to a smaller display, you get `font-size: 24px`

So it seems bootstrap website is... hacking bootstrap "simpler and easier to understand" you pointed, to make it *useful on real use case!*

It seems *Eating your own dog food* slang is not applied here. Why?

Anyway, how many boostrap users/developers should point the importance of this to make it happen?

**Comment by jacargentina** [comment]
This is my custom solution to this, for v4 with sass. Hope helps someone!

````sass
@mixin responsive-headings($tag-name, $font-size, $multiplier) {
  $selector: "#{$tag-name}, .#{$tag-name}";

  #{$selector} {
    font-size: $font-size * (1 - (0.4 * $multiplier));
  }

  @include media-breakpoint-up(xs) {
    #{$selector} {
      font-size: $font-size * (1 - (0.2 * $multiplier));
    }
  }
  @include media-breakpoint-up(md) {
    #{$selector} {
      font-size: $font-size * (1 - (0.1 * $multiplier));
    }
  }
  @include media-breakpoint-up(lg) {
    #{$selector} {
      font-size: $font-size;
    }
  }
}

@include responsive-headings('h1', $font-size-h1, 1);
@include responsive-headings('h2', $font-size-h2, 1);
@include responsive-headings('h3', $font-size-h3, 1);
@include responsive-headings('h4', $font-size-h4, 0.7);
@include responsive-headings('h5', $font-size-h5, 0.6);
@include responsive-headings('h6', $font-size-h6, 0.5);
````

**Comment by mdo** [comment]
> That very text, has `font-size: 30px` when on large device, but switching to a smaller display, you get `font-size: 24px`
> 
> So it seems bootstrap website is... hacking bootstrap "simpler and easier to understand" you pointed, to make it *useful on real use case!*
> 
> It seems *Eating your own dog food* slang is not applied here. Why?

This isn't hacking Bootstrap—it's extending it's simple, default behavior. Not everyone needs a responsive scale like what you're proposing. I personally think it over-engineers a particular problem that's better solved with a holistic view of your product/app.

This is about eating our own dog food, too. We're building the entire docs site with Bootstrap itself. Most of the pain points y'all feel are ones we've run into as well (here in the docs and in our paid themes). Simpler approaches often have a more meaningful impact than more complex ones.
 
> Anyway, how many boostrap users/developers should point the importance of this to make it happen?

It's not always that simple :). Sheer numbers doesn't make something more likely to ship for us. Lots of folks wanted us to maintain multi-level dropdown menus, but we nixed them because they're shit to implement, not that accessible, and lead to carelessly designed components.

Hope that helps some! Thanks for following up and asking the questions—appreciate it :).

**Comment by jacargentina** [comment]
Why not go with an *optional* feature, disabled by default?
I've discovered on the v4 alpha there are some flags to enable/disable some features as described on http://v4-alpha.getbootstrap.com/getting-started/options/
Also i must say, there are some of those flags which dont do anything.
Why dont simply add a new `enable-responsive-headings: false !default`, which turns on/off my proposal?

**Comment by bjorn-ali-goransson** [comment]
But! @jacargentina , when columns collapse, often it is actually appropriate with *larger* headings than on a larger screen.

**Comment by mdo** [comment]
> Why not go with an optional feature, disabled by default?

Sorry, but we don't implement every feature request we receive. The options we've added in our Sass variables for largely for easier customization (aside from flex box, which is for folks building more future friendly sites). I get the use case, but I don't see the need.

**Comment by bjorn-ali-goransson** [comment]
Actually, the best way to do this IMO is by doing:

    h1 {
      font-size: 4.5vw;
    }

    h2 {
      font-size: 3.5vw;
    }
