### ISSUE TITLE
V4 docs for input size shows input-lg and input-sm in placeholder.

### ISSUE THREAD

**Issue by ShaunR** [twbs/bootstrap#18132]
http://v4-alpha.getbootstrap.com/components/forms/#control-sizing

Looks like version 4 now uses form-control-size for sizing inputs, the examples in the docs though use a place holder that still shows .input-lg and .input-sm.  They just need to be updated to the correct new classes.

**Comment by cvrebert** [comment]
Duplicate of #17670.
