### ISSUE TITLE
Very long words overflow cards

### ISSUE THREAD

**Issue by gotoGosub** [twbs/bootstrap#18142]
Hi, long text without breakable space is not correctly managed in card divs (see the snapshot)

![untitled](https://cloud.githubusercontent.com/assets/7568389/10911588/d24560e2-8245-11e5-9d64-1e5add58dc08.png)

**Comment by cvrebert** [comment]
Per #14162, since different folks will want to deal with unusually long words differently, I think this needs to be dealt with at the application level rather than at the Bootstrap level.
CC: @mdo

**Comment by mdo** [comment]
Yeah, you'll want to change up the text wrapping there manually. Whatever we do could mess with folks unnecessarily and lead to more trouble down the line.

**Comment by mdo** [comment]
(For context, I'm pretty sure we don't account for this anywhere else in Bootstrap.)
