### ISSUE TITLE
v4 feature request: browser support config

### ISSUE THREAD

**Issue by Havunen** [twbs/bootstrap#18143]
Hi,

We are using BS4 alpha currently in our web app and we have no plans supporting IE9 at all. Therefore I think it would be nice to have config file where we could specify minimum supported browser version. I have been following bootstrap development and noticed that every now and then there is hack made specifically for IE9. 

The idea would be to have config where you set the browser and minimum supported version and then in grunt compilation time it removes the code if its outside the browser requirements. There could be defaults of course what you guys want to support offically and then people who want to tweak it could increase the level. This way shipped code would not contain that much "bloat".

Thanks and good work with V4 :+1:

**Comment by Havunen** [comment]
I found that clean css component has this kind of config also. Similar feature could be inside bootstrap also?

https://github.com/jakubpawlowicz/clean-css#how-to-set-a-compatibility-mode

**Comment by cvrebert** [comment]
This pretty much depends on how @mdo would feel about adding an IE version variable and a bunch of associated `@if`s to the SCSS.

**Comment by mdo** [comment]
Eh, not really interesting in this right now. I'd be fine exploring it, but it's not on my agenda for anytime soon.
