### ISSUE TITLE
Bower Json problem with the css main file

### ISSUE THREAD

**Issue by Tibicenas** [twbs/bootstrap#18158]
To automate tasks we need to get by the bower json the main files, i mean the .js and the .css
but you have right now this in the bower.json : 
```json
"main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
```

please change to this:

```json
"main": [
    "less/bootstrap.less",
    "dist/css/bootstrap.css",
    "dist/js/bootstrap.js"
  ],
```

**Comment by Johann-S** [comment]
See this : https://github.com/twbs/bootstrap/issues/16663

**Comment by cvrebert** [comment]
Closing as duplicate. Please search more in the future. Thanks.
