### ISSUE TITLE
Multiple collapse group items (parent and children) - not working

### ISSUE THREAD

**Issue by dejwne** [twbs/bootstrap#18160]
When I want to create collapsing group item like is written in this example - http://v4-alpha.getbootstrap.com/components/collapse/#accordion-example but with that difference - to have much more multiple levels - it doesn't work. Everytime when I'm opening child level and their content, it is covered by parent on top level. When I tried to changed version of Bootstrap to 3.3.5, it worked.

For better explanation - here is example what is working in 3.3.5 and not in v4 alpha. Could you please fix it somehow? :) http://www.bootply.com/vlLkd53dZb

Edit: I'm using v4-alpha version

**Comment by twbs-lmvtfy** [comment]
Hi @dejwne!

You appear to have posted a live example (http://s.bootply.com/render/vlLkd53dZb), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 60, column 21: [E023](https://github.com/twbs/bootlint/wiki/E023): `.panel-body` must have a `.panel` or `.panel-collapse` parent
* line 61, column 25: [E026](https://github.com/twbs/bootlint/wiki/E026): `.panel-title` must have a `.panel-heading` parent
* line 10, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.5 ; saw what appears to be usage of Bootstrap 3.2.0
* line 128, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.5 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@dejwne Please fix the above problems in your example.
