### ISSUE TITLE
v4 - Change modal widths to rem units

### ISSUE THREAD

**Issue by Skwai** [twbs/bootstrap#18167]
As everything else is using `rem` units in v4. Perhaps change modal widths from px to rem:

```
$modal-lg:                    900px !default;
$modal-md:                    600px !default;
$modal-sm:                    300px !default;
```

Also, on that note many other elements still have px units such as `$alert-padding`

**Comment by cvrebert** [comment]
Actually, the grid doesn't use rem units anymore, and for similar reasons, I doubt we'd want to switch to then here.

**Comment by Skwai** [comment]
Well that's good news. Was going to post an issue about borders not showing when their widths were calculated as <1px when the root font-size is reduced but it appears that won't be an issue

**Comment by cvrebert** [comment]
Er, you already did post that issue, but anyway..
