### ISSUE TITLE
v4 - Add a fluid container class that grows to 'x' width

### ISSUE THREAD

**Issue by Skwai** [twbs/bootstrap#18168]
Would be great to have a container class that grows until it reaches full width.

`.container-fluid` can often be to large on big screens, whereas `.container` has a lot of whitespace on smaller screens

Something like this would be great:

```
.container-grow {
  @include max-container();
  max-width: map-get($container-max-widths, 'xl');
}
```

**Comment by cvrebert** [comment]
Why not just use the available variables to change the responsive widths of `.container` ?

**Comment by Skwai** [comment]
I guess that's a fair point. Would be nice to have out of the box though.

**Comment by kandros** [comment]
I personally think you should just set a class in your own code that extends `.container-fluid` and adds a max-width form a project variable

**Comment by mdo** [comment]
Yup, not making any changes to v4 for this. Thanks though!
