### ISSUE TITLE
question about refactoring to avoid child selectors 

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18162]
I understand about child selectors, but what about the `.active` class? see: https://github.com/bassjobsen/bootstrap/blob/patch-13/scss/_carousel.scss#L185

Maybe it is possible to consider the the `.active` class as a state, like `:hover` and so allow nesting? Or should i also have to create a `.carousel-indicators-item-active` class in the above?

Related: https://github.com/twbs/bootstrap/pull/18161

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
`.active` is fine to chain like that—we use it in our navs right now and I wouldn't imagine using more specific classes for that there.
