### ISSUE TITLE
form select  height is small on v4-dev

### ISSUE THREAD

**Issue by iBasit** [twbs/bootstrap#18169]
http://v4-alpha.getbootstrap.com/components/forms/

Please check form select drop down menu size is small compare to previous version and standard input box height.

![image](https://cloud.githubusercontent.com/assets/34341/10955521/5278e71e-834c-11e5-995f-134d5ef8dd6d.png)

**Comment by cvrebert** [comment]
Duplicate of #18117. No need to re-file this.
