### ISSUE TITLE
Cannot access Bootstrap v4 docs

### ISSUE THREAD

**Issue by priyanka-herur** [twbs/bootstrap#18173]
Trying to access the docs at http://v4-alpha.getbootstrap.com/  returns "Unknown Host".
![bootstrap_docs](https://cloud.githubusercontent.com/assets/3461882/10961328/94702c88-83b3-11e5-88f4-17beb189d276.png)

**Comment by Johann-S** [comment]
For me the documentation is available please use this : http://downforeveryoneorjustme.com

**Comment by priyanka-herur** [comment]
Thanks! It's up again.
