### ISSUE TITLE
v4 - Make .card class display: block

### ISSUE THREAD

**Issue by Skwai** [twbs/bootstrap#18170]
Cards using an anchor element are rendering as inline as the `display` property is inherited, eg.

```
<a class="card card-block" href="#">
  <h4 class="card-text">The parent is inline</h4>
  <p class="card-text">This is some text</p>
</a>
```

Adding `display: block;` to `.card` class would fix this.

**Comment by mdo** [comment]
Fixed in #18255.

**Comment by saeideh-mardan** [comment]
I have my card with position absolute so this thing does not work at all for mw :( what are other ways?

**Comment by Skwai** [comment]
`position: absolute` will override block positioning. You should give it an explicit width and height (or left/right/top/bottom). If you want to preserve its layout then use `position: relative`
