### ISSUE TITLE
Add utility class for user-select:none ?

### ISSUE THREAD

**Issue by adelivuk** [twbs/bootstrap#18176]
Is there a reason why the text selection isn't disabled on the `.checkbox label` element? It's kind of annoying when you're clicking fast on the element, see the image:

![screen shot 2015-11-05 at 13 56 04](https://cloud.githubusercontent.com/assets/6178877/10968911/0440c8cc-83c5-11e5-8f27-b1f095951be1.png)

Adding these styles fixes the issue:

```
.checkbox label{
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

<hr>

Or maybe creating, for example, a `.disable-user-select` class, like:

```
.disable-user-select{
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

```
<div class="checkbox">
    <label class="disable-user-select">
        <input type="checkbox"> Check me out
    </label>
</div>
```

<hr>

However, I've noticed that you using the `user-select` style on the `.btn` class. Should I add `.btn` class to the `.checkbox label` element? Is that the "bootstrap" way for dealing with it?

```
<div class="checkbox">
    <label class="btn">
        <input type="checkbox"> Check me out
    </label>
</div>
```

**Comment by wtser** [comment]
it looks not comfortable

**Comment by patrickhlauke** [comment]
As selectable label text is standard in browsers, I'd be in favor of actually leaving this as it currently is.

**Comment by adelivuk** [comment]
@patrickhlauke yes, I agree with you, however maybe adding an additional class for preventing `user-select` is a good thing, for situations like this one?

I've tested with using `.btn` on the `label` and it's `outline` styles just doesn't fit.

![screen shot 2015-11-05 at 15 10 41](https://cloud.githubusercontent.com/assets/6178877/10970515/6dd482ba-83cf-11e5-954c-5ffd47ed6ef9.png)

**Comment by mdo** [comment]
Disabling text on the checkbox won't happen, though I'm not against a utility class I suppose.

**Comment by mdo** [comment]
Punting on the utility class for now until we hear more folks asking for it.

**Comment by joeysino** [comment]
I would +1 on the utility class, as long as it is called [`.noselect`](http://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css). That's two requests in 13 months! ;)

**Comment by stanleyxu2005** [comment]
+1 for making label (checkbox) in a form not selectable

**Comment by 0reo27** [comment]
I'm with the utility class on this one.

**Comment by davidmarcbrown** [comment]
+1 I would have used the utility class once or twice last year

**Comment by vanillajonathan** [comment]
A `.user-select-none` utility class could be useful for portable web applications (PWA).
When the application runs on a device with touch input such as a phone or tablet.

Then it could be used together with [stretched links](https://github.com/twbs/bootstrap/pull/26184) over cards, or [list groups with links and buttons](https://getbootstrap.com/docs/4.2/components/list-group/#links-and-buttons).

**Comment by hgs-fredarters** [comment]
+1.  I use my own utility class for this all the time.  Would be nice if it was in the utilities.

**Comment by llemurya** [comment]
+1 It will be useful if this class will be in the repo.

**Comment by Salah2Eddin** [comment]
+1

**Comment by aeadedoyin** [comment]
+1

**Comment by mhrabiee** [comment]
+1

**Comment by exzizt** [comment]
+1

**Comment by sheff3rd** [comment]
+1

**Comment by adam-marshall** [comment]
+1

**Comment by backoon** [comment]
+1

**Comment by vanillajonathan** [comment]
Instead of just commenting "+1" you can react with thumbs up 👍  the original post in this issue.

GitHub allows you to sort issues after number of reactions:
https://github.com/twbs/bootstrap/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by danday74** [comment]
I think this shows enough interest to do something

**Comment by mdo** [comment]
I’ll take a crack at this for v5 shortly. With our new utility API, we can easily add these and allow others to customize. Be on the lookout for a PR.
