### ISSUE TITLE
!default flag should be removed

### ISSUE THREAD

**Issue by NickToye** [twbs/bootstrap#18175]
Maybe I have missed something here, but if I have !default applied to a bunch of variables in my Bootstrap variables.scss file, regardless of whether or not I have the variable in a custom.scss variables file it will not allow me to override it.

So while I can spend time removing this flag, it will get overridden if I upgrade Bootstrap.

**Comment by NickToye** [comment]
Ignore, seems it makes no difference.

**Comment by mattycraig** [comment]
Have you tired importing your custom.scss or declaring any variable before you import the bootstrap variables.scss file?

**Comment by NickToye** [comment]
Yeah I did and it works. But not sure why but it didn't make logical sense to me. 

If I add a variable after one variable of the same name it overrides it.
