### ISSUE TITLE
v4: should carousel captions be hidden by default for small viewports?

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18171]
See: https://github.com/twbs/bootstrap/blob/4d17a04a2766315299de7e6f5d0894bb9ed25228/scss/_carousel.scss#L199
Should i remove the comment or implement it?

**Comment by mdo** [comment]
Yeah, they should be hidden.

**Comment by mdo** [comment]
This can be optionally handled with display utilities. Example coming with #21298.
