### ISSUE TITLE
Add vertical tabs

### ISSUE THREAD

**Issue by teamcreed** [twbs/bootstrap#18179]
Hello

this is to propose a new feature, placing them in tabs to the left or right of the tab-content

![left_sidebar_menu](https://cloud.githubusercontent.com/assets/14580377/10975938/4688ade8-839e-11e5-89d0-09b113a41f94.PNG)
![right_sidebar_menu](https://cloud.githubusercontent.com/assets/14580377/10975939/468cd1b6-839e-11e5-9964-812f09a6f3b4.PNG)

**Comment by teamcreed** [comment]
In the file less/navs.less

.nav-tab-left{
  float: left;
  width: 10%;
  border:1px solid #ddd;
  margin-right: 1em;

  li:not(:first-child){
    border-top: 1px solid #ddd;
  }

}


.nav-tab-right{
 float: right;
 width: 10%;
 border:1px solid #ddd;
 margin-left: 1em;

 li:not(:first-child){
   border-top: 1px solid #ddd;
 }

}

**Comment by cvrebert** [comment]
@mdo deliberately removed this feature in Bootstrap v3 (see #8922) and to my knowledge his opinion hasn't changed since then.

@mdo Please reopen if you've changed your mind on this.

**Comment by raphaelvigee** [comment]
Here is my implementation of `nav-stacked` to tabs :

```
.nav-tabs.nav-stacked {
  border-bottom: none;
  border-right: $nav-tabs-border-width solid $nav-tabs-border-color;

  .nav-item {
    margin-bottom: 0;
    margin-right: -$nav-tabs-border-width;
  }

  .nav-link {
    border-radius: 0;
    padding: 1em;
    @include border-left-radius($nav-tabs-border-radius);

    @include hover-focus {
      border-color: $nav-tabs-link-hover-border-color transparent $nav-tabs-link-hover-border-color $nav-tabs-link-hover-border-color;
    }
  }

  .nav-link.active,
  .nav-item.open .nav-link {
    @include plain-hover-focus {
      border-color: $nav-tabs-active-link-hover-border-color;
      border-right-color: transparent;
    }
  }
}
```

I'm ready to make a PR if this is still wanted

**Comment by cvrebert** [comment]
I don't believe @mdo's opinion on this has changed.

**Comment by raphaelvigee** [comment]
Me neither, I dont really understand this decision, but anyway it can still be usefull for anyone trying to do it :)
