### ISSUE TITLE
Why are responsive images opt-in?

### ISSUE THREAD

**Issue by peiche** [twbs/bootstrap#18178]
It seems strange to me that Bootstrap, being responsive and mobile-first, requires an additional class for any image to behave responsively. The docs state that you must [manually disable responsiveness](http://getbootstrap.com/getting-started/#disable-responsive), but conversely, you must [add a class to images](http://getbootstrap.com/css/#images-responsive) to enable, not disable, responsive behavior.

Obviously your choices are your choices, and I'm not looking to reverse that. I would just like to know the reasoning behind this decision, and I'm unable to find a past issue that might address this.

**Comment by cvrebert** [comment]
See the comments and linked issues at the bottom of 09cdee2f03aaad5c5a767fbec2e3896ad3d1f980.

The summary is that it breaks a ton of unsuspecting third-party widgets (including Google Maps), which understandably don't anticipate the images within them being forcibly resized to other widths. This is why we rolled back Bootstrap v2's "images are responsive by default" approach in Bootstrap v3 in favor of an explicit `.img-responsive` class.
