### ISSUE TITLE
Add JS to set class on <body> based on viewport width

### ISSUE THREAD

**Issue by brunoguirado** [twbs/bootstrap#18183]
Hi, the below script, make more easy fine responsive adjusts, what do you think about implement  something like this by default?

```
jQuery(function($) {


    $.fn.isBreakPoint = function(device) {
        return $().getBreakPointClass() == 'device-' + device;
    };

    $.fn.setBreakPointClass = function() {
        var bodyClasses  = [];

        if ($('body').attr('class') != undefined) {
            bodyClasses = $('body').attr('class').split(' ');
        }

        var classBlackList = ['device-xs', 'device-sm', 'device-md', 'device-lg'];

        jQuery.grep(bodyClasses, function(bClass) {
            if (jQuery.inArray(bClass, classBlackList) != -1) {
                $('body').removeClass(bClass);
            }

        });

        $('body').addClass($().getBreakPointClass());
    };

    $.fn.getBreakPointClass = function() {
        var deviceClasses = $($('.device:visible')[0]).attr('class').split(' ');
        var classBlackList = ['device', 'visible-xs', 'visible-sm', 'visible-md', 'visible-lg'];

        var actualDeviceClasses = '';

        jQuery.grep(deviceClasses, function(el) {
            if (jQuery.inArray(el, classBlackList) == -1) actualDeviceClasses = el;
        });

        return actualDeviceClasses;
    };

    $(document).ready(function () {

        $(document).ready(function () {

            $('body').append('<div class="device device-xs visible-xs"></div>');
            $('body').append('<div class="device device-sm visible-sm"></div>');
            $('body').append('<div class="device device-md visible-md"></div>');
            $('body').append('<div class="device device-lg visible-lg"></div>');

            $().setBreakPointClass();

            $(window).resize(function () {
                $().setBreakPointClass();
            });
        });
    });
});
```

**Comment by cvrebert** [comment]
Can't say I really see the point of this. The proper way is to use media queries in your CSS instead. Bootstrap even already provides some Sass mixins to make writing them easier.
And there are already responsive `display` and `text-align` classes in Bootstrap, which cover some of the use-cases that this class toggling code might have.

**Comment by cvrebert** [comment]
@brunoguirado Care to give a rebuttal?

**Comment by brunoguirado** [comment]
for example, i have an image and I need change this image when screen is resized (xs, sm, md or lg), I think more easy if body target comes setted with device. Some times I don't know use this resource from bootstrap.

Today bootstrap have the Media queries for this, all right, but the code get dirty and with this class setted in the body, get more easy and css code, for divs for example, gets grouped and easy to read and fix/adjust.

**Comment by brunoguirado** [comment]
Example: <div class="img-x"></div> and <div class="img-y"></div>

...


/* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm-min) {
    div.img-x { background-image: url('path-to-image-x-sm.jpg'); }
    div.img-y { background-image: url('path-to-image-y-sm.jpg'); }
}

/* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md-min) {
    div.img-x { background-image: url('path-to-image-x-md.jpg'); }
    div.img-y { background-image: url('path-to-image-y-md.jpg'); }
}

/* Large devices (large desktops, 1200px and up) */
@media (min-width: @screen-lg-min) {
    div.img-x { background-image: url('path-to-image-x-lg.jpg'); }
    div.img-y { background-image: url('path-to-image-y-lg.jpg'); }
}
...

With my suggestion: 
...
body.device-sm div.img-x { background-image: url('path-to-image-x-sm.jpg'); }
body.device-md div.img-x { background-image: url('path-to-image-x-md.jpg'); }
body.device-lg div.img-x { background-image: url('path-to-image-x-lg.jpg'); }

body.device-sm div.img-y { background-image: url('path-to-image-y-sm.jpg'); }
body.device-md div.img-y { background-image: url('path-to-image-y-md.jpg'); }
body.device-lg div.img-y { background-image: url('path-to-image-y-lg.jpg'); }
...

**Comment by cvrebert** [comment]
CC: @mdo for opinion

**Comment by patrickhlauke** [comment]
FWIW my opinion: this approach creates a JavaScript dependency. And while it's true that it would make writing new styles less verbose, it basically advocates abandoning media queries for old-school JS similar to this from 2006 http://www.themaninblue.com/writing/perspective/2004/09/21/ ...

**Comment by oleersoy** [comment]
@brunoguirado to me it looks like you are looking for sizing utilities similar to:
https://github.com/suitcss/utils-size

See the responsive utilities section.  I believe SUIT generates these using `@custom-media` variables.  You could do it fairly easily using something like:
[postcss-custom-media](https://github.com/postcss/postcss-custom-media).  

You may need to use `postcss-each` as well to generate the responsive utitlies for each breakpoint.  I'm still figuring out the exact process.  Once you have the utilties, you would apply all of them to the image, and then the correct class is triggered by the media breakpoint.

**Comment by mdo** [comment]
Thanks, but we'll pass.

**Comment by plinus** [comment]
Might be helpful for Bootstrap 4 Beta 2
`jQuery(function($) {

		    $.fn.isBreakPoint = function(device) {
		        return $().getBreakPointClass() == 'device-' + device;
		    };

		    $.fn.setBreakPointClass = function() {
		        var bodyClasses  = [];

		        if ($('body').attr('class') != undefined) {
		            bodyClasses = $('body').attr('class').split(' ');
		        }

		        var classBlackList = ['device-xs', 'device-sm', 'device-md', 'device-lg', 'device-xl'];

		        jQuery.grep(bodyClasses, function(bClass) {
		            if (jQuery.inArray(bClass, classBlackList) != -1) {
		                $('body').removeClass(bClass);
		            }

		        });

		        $('body').addClass($().getBreakPointClass());
		        
		    };

		    $.fn.getBreakPointClass = function() {
		        var deviceClasses = $($('.device:visible')[0]).attr('class').split(' ');
		        var classBlackList = ['device', 'd-xs-none', 'd-xs-block', 'd-sm-none', 'd-sm-block', 'd-md-none', 'd-md-block', 'd-lg-none', 'd-lg-block', 'd-xl-none', 'd-xl-block'];

		        var actualDeviceClasses = '';

		        jQuery.grep(deviceClasses, function(el) {
		            if (jQuery.inArray(el, classBlackList) == -1) actualDeviceClasses = el;
		        });

		        return actualDeviceClasses;
		    };

		    $(document).ready(function () {

		        $(document).ready(function () {

		            $('body').append('<div class="device device-xs d-xs-block d-sm-none d-md-none d-lg-none d-xl-none"></div>');
		            $('body').append('<div class="device device-sm d-xs-none d-sm-block d-md-none d-lg-none d-xl-none"></div>');
		            $('body').append('<div class="device device-md d-xs-none d-sm-none d-md-block d-lg-none d-xl-none"></div>');
		            $('body').append('<div class="device device-lg d-xs-none d-sm-none d-md-none d-lg-block d-xl-none"></div>');
		            $('body').append('<div class="device device-xl d-xs-none d-sm-none d-md-none d-lg-none d-xl-block"></div>');

		            $().setBreakPointClass();

		            $(window).resize(function () {
		                $().setBreakPointClass();  
		            });
		        });
		    });
		});`
