### ISSUE TITLE
@viewport has currently-hypothetical vendor prefixes

### ISSUE THREAD

**Issue by oleersoy** [twbs/bootstrap#18188]
Version 4 unsupported / unknown `@viewport` extensions.  See https://github.com/postcss/autoprefixer/issues/552

**Comment by cvrebert** [comment]
Those are there for future-proofing per https://web.archive.org/web/20150429205336/http://timkadlec.com/2013/01/windows-phone-8-and-device-width/

**Comment by oleersoy** [comment]
You may want to consider adding a comment / todo tag to add vendor specific prefixes when they become available, or implement tooling support such as autoprefixer.  Having code that is actually unimplemented and undocumented by the corresponding browser vendors will most likely raise a few eyebrows down the road.

**Comment by mdo** [comment]
Fixed in f16ad22.
