### ISSUE TITLE
Buttons with Dropdowns : Height of dropdown & input don't match in the example in official docs

### ISSUE THREAD

**Issue by bitcity** [twbs/bootstrap#18194]
Using Chrome (Version 46.0.2490.80 (64-bit)) on Ubuntu (14.04). 

The height of dropdown & input don't match in the [example in docs](http://getbootstrap.com/components/#input-groups-buttons-dropdowns) (Bootstrap v3)

> Screenshot (misaligned at bottom edge, click image to enlarge) : 
![image](https://cloud.githubusercontent.com/assets/4221404/11014325/c0057822-8556-11e5-965c-d710fdf908f7.png)

> Dropdown height : 19.08
![image](https://cloud.githubusercontent.com/assets/4221404/11014340/834dae80-8557-11e5-80f0-0bcc874990af.png)

> Input height : 20.173
![image](https://cloud.githubusercontent.com/assets/4221404/11014343/904b88e6-8557-11e5-8389-6c74fdacebfd.png)

P.S. It's correctly aligned on Chrome + iPad, Chrome + Windows, Firefox + Ubuntu

**Comment by cvrebert** [comment]
Please confirm that the page zoom level is 100% (i.e. not zoomed). Page zooming isn't really supported, per http://getbootstrap.com/getting-started/#support-browser-zooming
If zooming isn't the problem, could you please re-test against the latest Bootstrap code in the `master` branch?

Note that Linux is only unofficially supported, per http://getbootstrap.com/getting-started/#support-browsers

**Comment by bitcity** [comment]
Sorry, my bad. It was indeed a zoom issue that I missed.
