### ISSUE TITLE
v4 - grid broken in FF28

### ISSUE THREAD

**Issue by monolux** [twbs/bootstrap#18195]
Check this URL with Firefox version 28.

http://v4-alpha.getbootstrap.com/examples/grid/

Grid is broken.

**Comment by krnlde** [comment]
How are you still able to use a Firefox, that old? It is evergreen and will be update once you open it.

**Comment by patrickhlauke** [comment]
"the latest versions of most desktop browsers are supported" http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/

so no, sadly no support for Firefox 28 (regardless of people who steadfastly refuse to upgrade because they don't like the new Australis theme ;) )

**Comment by monolux** [comment]
I use FF or all versions and themes, in a sandbox or a VM, latest without those, for testing, things like, you got that right, v4.
