### ISSUE TITLE
.form-control-static not vertically aligned with labels

### ISSUE THREAD

**Issue by ruslandzhumaev** [twbs/bootstrap#18190]
Guys, can you please take a look at http://v4-alpha.getbootstrap.com/components/forms/#static-controls
I think there is a padding issue with .form-control-static: http://i.imgur.com/yW3uD7s.png (Win7 / Chrome Browser)
And I did not find the open issue of that.

**Comment by cvrebert** [comment]
This appears to already be fixed in the head of the `v4-dev` branch.
