### ISSUE TITLE
Taking Sass customisation to the next level !

### ISSUE THREAD

**Issue by karan1276** [twbs/bootstrap#18192]
So for a project of mine i wanted bootstrap’s grid system only, i wanted the latest version so i decided to separate bootstraps v4 grid system my self, [Check it out here](https://github.com/Code-Lobster/Bootstrap-4-grid-system). While i was working at it i realised the amount of flexibility it provides is just amazing, i could change the breakpoints AND the number of columns, wow   man! that was amazing.

I also leaned about sass-script and the awesome things you can do with them.So i came-up with an cool idea:

bootstrap provides six basic classes: `primary, secondary, info, danger, warning, and success`. These classes are used in all components: Buttons, labels, alerts, etc. Instead of hard coding these classes why don’t we let the user create them.

To better explain things i created [this repository, check it out](https://github.com/Code-Lobster/Bootstrap-ultra-buttons-system). We can create a sass map of these properties and let the user change the map and css will be generated accordingly just like [Bootstrap ultra button system](https://github.com/Code-Lobster/Bootstrap-ultra-buttons-system).That way users can have exactly the classes they want.

This will have large impact on how people use bootstrap, i think this will encourage people to start editing bootstrap directly and not add extra css file on top of bootstrap to override it’s rules. Not only that it will promote use of css pre-compilers, this will also accelerate the growth of the css pre-compilers themselves (because we will be using lots of advanced features). Long story short it’s better for web in general :)

I understand implementing this will take lots of time (may be you will leave it for bootstrap 5) and you guys are very very busy. But hey, i am a student who is really into bootstrap and i have some time in my hand, vacations are coming and i was thinking for doing an internship anyways. I would be glad to become a volunteer, not only for this modification but bootstrap in general, i can try and fix most of those v4 issues. On demand i can send my resume as well :)

Thanks for reading,
Regards Karan

**Comment by karan1276** [comment]
@mdo since it looks like you wrote a lot of sass, what do you think about this?

**Comment by karan1276** [comment]
what do you think @cvrebert, is this a practical idea :sweat_smile: ?

**Comment by mmjaeger** [comment]
+1

**Comment by cvrebert** [comment]
It is feasible. I defer to @mdo as to whether it's desirable.

**Comment by mdo** [comment]
I mean, that'd be pretty chill, but unsure if we want to do it for v4 just yet. A lot of this kind of stuff just obscures what folks have readily available to them. Closing for now, but we could revisit in the future.

**Comment by karan1276** [comment]
Okay, if you need a hand in anything i will be glad to help :)
Thanks
