### ISSUE TITLE
Space between pager links requires whitespace in the HTML

### ISSUE THREAD

**Issue by AngeIII** [twbs/bootstrap#18199]
http://getbootstrap.com/components/#pagination-pager

Currenlty in your preview pagination have whitespace this is an issue when pagination is generated without spaces we have no margins. I expect that default functionality can be changed?
Related: https://github.com/esimakin/twbs-pagination/issues/57

**Comment by cvrebert** [comment]
I suspect logic similar to #16163 will apply here, except the pager parts are `display:inline` rather than `display:inline-block`.
/cc @mdo

**Comment by mdo** [comment]
Yeah, no plans on our end to change this up—too close to end of life for v3.

**Comment by cvrebert** [comment]
@mdo This also applies to v4. Can we agree on "Bootstrap may require spaces in HTML as a result of `inline(-block)`" as a general design principle?

**Comment by mdo** [comment]
Just dropped pager links in v4, so closing this out. See #18782.
