### ISSUE TITLE
Validator.js

### ISSUE THREAD

**Issue by aminsmartsense** [twbs/bootstrap#18198]
![untitled-1](https://cloud.githubusercontent.com/assets/15724804/11027523/2e8087a2-86dc-11e5-9ff2-6a945c58e978.png)

Please Check

**Comment by aminsmartsense** [comment]
Please check this issue and fix

Thanks

**Comment by patrickhlauke** [comment]
you're possibly after http://1000hz.github.io/bootstrap-validator/ - nothing to do with bootstrap core
