### ISSUE TITLE
v4 justified nav broken in Chrome 45.0.2454.101

### ISSUE THREAD

**Issue by monolux** [twbs/bootstrap#18196]
Anybody had a look at http://v4-alpha.getbootstrap.com/examples/justified-nav/ with Chrome 45.0.2454.101?

This version of Chrome is from Sept. 24th 2015, fingers crossed that is supported.
http://googlechromereleases.blogspot.com/2015/09/stable-channel-update_24.html

**Comment by cvrebert** [comment]
Duplicate of #17026. Please search more in the future.

**Comment by monolux** [comment]
Been searching all my life so far but in this case I will use the search to find duplicate bugs ;)

Thanks.
