### ISSUE TITLE
Bootstrap themes  

### ISSUE THREAD

**Issue by Jayman1305** [twbs/bootstrap#18200]
I stumbled across the bootstrap themes on http://themes.getbootstrap.com/. Given that they come form you direct, i was only to happy to purches them but they ore less not sass and it looks like there are for version 4 not 3. Am i correct?

**Comment by cvrebert** [comment]
> * [Please do not open issues](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker) regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`
