### ISSUE TITLE
Carousel does not cycle under v3.3.5

### ISSUE THREAD

**Issue by manjuiotlabs** [twbs/bootstrap#18204]
Hi,

I am facing almost the same issue as the one previously reported and fixed in #3528: carousel does not cycle. 

I tried all the plausible solutions discussed under #3528, but none worked. The following is my config code, and please let me know what is going wrong:

JAVA SCRIPT:
```html
<script type="text/javascript" src="/bower_components/jquery/jquery.js"></script>
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script type='text/javascript'>
    $(document).ready(function() {
         $('#ck-carousel').carousel({
             interval: 2000,
             cycle: true,
             pause: 'none'
         })
    });    
</script>
```
HTML:
```html
<div id="ck-carousel" class="carousel slide" data-ride="carousel" data-interval="2000">
// images go here
</div>
```

**Comment by cvrebert** [comment]
For troubleshooting questions, please use StackOverflow, IRC, Slack, or similar.
See https://github.com/twbs/bootstrap#community for links to these resources.
Thanks.
