### ISSUE TITLE
Navbar Collapse 

### ISSUE THREAD

**Issue by cassia23** [twbs/bootstrap#18203]
My navbar is not collapsing on tablet like it should. I've tried everything. I've even pulled the navbar example from getbootstrap.com and removed everything else from the page aside from the navbar and it's still not collapsing. I haven't done anything to it. and I'm using the minified BS 3.3.5 css and js. (issue on ipad) heeeeeeeeeeeeeeeeeeelp

**Comment by patrickhlauke** [comment]
of course, without a pointer to your actual code that's failing, there's little that we can do. sounds to me, though, that you're missing appropriate viewport meta.

i'd also suggest directing requests for help (i.e. not bug reports for Bootstrap itself) to StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
