### ISSUE TITLE
Make a dedicated bootstrap themes repo and/or forums

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#18206]
In my opinion, providing customers who purchase the team's themes with a standalone support forum that they get an account to and/or a public repository for issues would be very helpful to the support team, the community, and the customers. The public repository can provide users who review the themes and find bugs in the demos to clearly and simply report them, as well as provides a clear point for where users should go when they need support. Contributing.MD doesn't seem to be the right place for that information as the user isn't contributing, they are asking for support which is part of the product.

The biggest issue in my opinion with not having a dedicated site or history is that by not answering questions and directing users to email there is no historic base for users to see if others face similar problems and to work together and collaborate. The current posture of the team of using trying to stop users here does nothing in my opinion other than increase frustration of the user opening the issue and those of us that get notifications about issues here. Creating more tension and frustration between the users and core team seems counter-intuitive to me.

In addition to this, providing a standalone repository (with a readme, wiki and issues) would provide clearer direction in my opinion (if users find bootstrap-themes repo, I believe they would connect that it makes more sense to open the issue there instead of here). This would allow closed issues for paid users to be directed to the support forum or the team could do a registration that adds them to a standalone twbs-themes organization. Ultimately though, I feel as though the infrastructure to support bootstrap themes is lacking and has a negative impact on the issue tracker and Bootstrap community.

Ultimately, I think it's important to ensure that there is clear and consistent issue reporting for all users. I believe that simplifying how users can communicate with the team, and if possible providing support for paid themes via Github issues, will benefit not only the team, but the individuals requesting support as well as reduce noise for other members of the Bootstrap community.

If at any time here I've used "the team" incorrectly when it should be a sub-set of the team (e.g. mdo and fat only?), I apologize for the inaccuracy and ultimately am referencing the sub-set of the team.

Thanks for your time and assistance.

**Comment by cvrebert** [comment]
/to @mdo @fat @dhg, who are the ones offering the "official" themes (as noted in the "From industry leaders" section of http://themes.getbootstrap.com)

**Comment by mdo** [comment]
Punting on this—we have the email for official support threads and can't maintain something like that publicly (or even semi-publicly for customers).

**Comment by kkirsche** [comment]
Disappointing but understood.
