### ISSUE TITLE
Menu "smushing" list elements on Chrome and IE

### ISSUE THREAD

**Issue by cloudinspector** [twbs/bootstrap#18210]
Hello,

I am attempting to "fix" a website that was built by someone else.  They code used for the navbar appears to all be fine.  In Firefox, the menu looks great when it goes full width.  In Chrome and IE however, the list items all smush into each other, despite my adding a min-width to the "li", and adding padding to the actual "a" tag.  This only happens when you browse to one of the two other pages "login" or "privacy", and then back again.  Once jumbled up, a refresh straightens everything out but I can't figure out why it isn't working to begin with.

Any help would be super appreciated.  I'm just not a bootstrap expert.  Thanks!

Dan

You can see what I mean here...

http://adxcel.quillcm.com/new.html

**Comment by dtamm** [comment]
Getting a 403 here...

**Comment by cloudinspector** [comment]
http://adxcel.quillcm.com/new.html

**Comment by cloudinspector** [comment]
@dtamm 

Are you able to view the site now?  Not sure why the link wouldn't work, I can see it fine from any device without being logged in or anything like that...

**Comment by dtamm** [comment]
Nope, still a 403 Forbidden!

**Comment by cloudinspector** [comment]
Going to call the server owner right now...maybe they are allowing only my IP???

**Comment by cloudinspector** [comment]
Are you located outside the US?  Nobody else is having the issue, including the new outside clients.  Any ideas.

**Comment by dtamm** [comment]
I'm in germany, maybe thats a problem?

**Comment by patrickhlauke** [comment]
This issue tracker is really meant for bugs/feature requests for Bootstrap core. Personal help requests relating to specific implementations should be directed to StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
