### ISSUE TITLE
Border-width if base font-size 14px

### ISSUE THREAD

**Issue by rash2x** [twbs/bootstrap#18211]
If we have font-size 14px then border-width in controls not viewed.
Border-width = 0.0625rem
![](https://cloud.githubusercontent.com/assets/3594973/11069178/e1d9acde-87e5-11e5-9dbc-a2d92f25a96a.png)

It makes us dependent on the font size of 16 pixels

**Comment by cvrebert** [comment]
Duplicate of #18166.
