### ISSUE TITLE
Add CDN links to v4 alpha docs?

### ISSUE THREAD

**Issue by zudoo** [twbs/bootstrap#18219]
[index.html:40](https://github.com/twbs/bootstrap/blob/v4-dev/docs/index.html#L40) says the CDN is not yet available, yet it is. [BootstrapCDN](http://www.bootstrapcdn.com/alpha/) have a v4 section.

**Comment by mdo** [comment]
Fixed in fd0d7e28fe6dbbc5338cdc3d31290ec2cbb347aa.
