### ISSUE TITLE
Display classes use incorrect sizing.

### ISSUE THREAD

**Issue by ramaboo** [twbs/bootstrap#18213]
On: http://v4-alpha.getbootstrap.com/content/typography/

`<h1 class=display-4">` is visibly larger than `<h1 class="display-1">`

Yet in https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss display-1 is sized larger than display-4.

```
$display1-size:               6rem !default;
$display2-size:               5.5rem !default;
$display3-size:               4.5rem !default;
$display4-size:               3.5rem !default;
```

I am unsure if the docs are wrong or the code is wrong but they are conflicting!

**Comment by cvrebert** [comment]
The live docs are currently for the 1st v4 alpha release, whereas `v4-dev` is the active development branch where many subsequent commits have been made. Thus, they aren't synchronized.
In particular, the sizing scheme of the `display-N` classes was reversed in 29c3eddaeb323299cd37796d893ed475ac1a29bd, which happened after the 1st alpha release.
