### ISSUE TITLE
v4: Maybe the wrapper can be left out using card decks?

### ISSUE THREAD

**Issue by storafrid** [twbs/bootstrap#18218]
Hi, it seems like the card deck can be structured like this instead, saving one div wrapper:

``` html
<div class="card-deck-wrapper card-deck">
    <div class="card">
        ...
    </div>
</div>
```

In the docs there is a separate div for this. Maybe it can be left out? I might very well be overlooking a browser test or edge case here, sorry if I do! Just tested around a bit.

Here is a CodePen [before](http://codepen.io/anon/pen/wKQEpW) and [after](http://codepen.io/anon/pen/GpwXXp) the change.

**Comment by mdo** [comment]
I recall it being a browser thing, but will need to revisit to be sure.

**Comment by mdo** [comment]
Or maybe it was just a problem with a table having `width: 100%`, which would be problematic for the negative margins.

**Comment by mdo** [comment]
Done with the move to flexbox in #21403.
