### ISSUE TITLE
dist/js/bootstrap.min.js has comments in it

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18216]
Presumably there's a problem with the minifier.
Refs https://github.com/twbs/bootstrap/commit/1dc8583bc5622463218b75c19c986765dce8798d#commitcomment-14322130

**Comment by XhmikosR** [comment]
This seems to also happen with the previous grunt-contrib-uglify version but it's using `^` for uglify-js' version so it's still using the latest.

**Comment by XhmikosR** [comment]
Note that this should also affect v3 but I need to double check later.

**Comment by XhmikosR** [comment]
OK, I think I pinpointed the issue; it's due to https://github.com/gruntjs/grunt-contrib-uglify/pull/338

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/commit/5a26a1386828758dbe0f132c2d02a3d46b5e0705
