### ISSUE TITLE
Inherited color of link in text emphasis.

### ISSUE THREAD

**Issue by TMMC** [twbs/bootstrap#18222]
While you give to any element color emphasis (for example `.text-primary`) it should IMHO inherit the color and lightly change it + change it more on hover/focus. But does not. 
There is a mixin in text-emphasis.less for focused and hovered links and it does not work.
```
.text-emphasis-variant(@color) {
  color: @color;
  a&:hover,  // mistake: 'a&'
  a&:focus { // mistake: 'a&'
    color: darken(@color, 10%);
  }
}
```
My guess is it should be:

```
.text-emphasis-variant(@color) {
  color: @color;
  a {
    color: darken(@color, 10%); // let's say
      &:hover,  
      &:focus {
        color: darken(@color, 20%); // let's say
      }
  }
}
```

**Comment by cvrebert** [comment]
Same thing also applies to `.bg-variant`

**Comment by mdo** [comment]
This isn't for children elements that are links, it's for links with the emphasis class. Put another way, this:

```html
<a href="#" class="text-info"></a>
```

Not this:

```html
<span class="text-info">
  <a href="#">...</a>
</span>
```

**Comment by TMMC** [comment]
OK, I will not insist and I get the point, but wouldn't it be more logical to add inheritance in those cases (color and background emphasis) - example below seems kind of redundant:
```html
<p class="text-info">
  Some text in paragraph and <a href="#" class="text-info">a link</a>. Both sharing same class.
</p>
```
