### ISSUE TITLE
Exclude unnecessary combos of the build matrix

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18224]
Refs #17652.
Running Sauce tests twice is downright wasteful.
Doing the HTML validation twice is unnecessary.
IMHO, we only really case that the core build doesn't break. The other builds are only really used by Core Team.

**Comment by XhmikosR** [comment]
Makes sense. For node.js we should care about the core build only.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/commit/5a26a1386828758dbe0f132c2d02a3d46b5e0705

**Comment by XhmikosR** [comment]
Err, sorry accidentally closed this.

**Comment by cvrebert** [comment]
Fixed by #18229.

**Comment by XhmikosR** [comment]
:clap:
