### ISSUE TITLE
ul.nav-tabs border-bottom is visible on IE11+Edge

### ISSUE THREAD

**Issue by hansmaad** [twbs/bootstrap#18228]
http://getbootstrap.com/components/#nav-tabs

![image](https://cloud.githubusercontent.com/assets/3396747/11112103/fa96184a-890f-11e5-8f13-8c56dfa9f329.png)

![image](https://cloud.githubusercontent.com/assets/3396747/11112141/92163be6-8910-11e5-921a-35f1d2925337.png)

This has to be a known issue, because it's even visible on the doc site. But I can't find any report nor a workaround. Increasing the `margin-bottom` on `.nav-tabs > li`  to -2px removes the line but does not look good either.

**Comment by cvrebert** [comment]
Unable to reproduce in Windows 10:
![proof](https://cloud.githubusercontent.com/assets/419884/11112852/08ca2832-88cc-11e5-88f2-04ba2cce0b85.png)
@hansmaad What version of IE11 and Windows are you using?

**Comment by hansmaad** [comment]
IE 11.0.9600.18059 on Win7. I will check this on other machines too.

**Comment by cvrebert** [comment]
@hansmaad Please also verify that IE's Zoom level is set to 100%.

Sauce only has IE 11.0.9600.17728 on Win7, which doesn't repro this.
@twbs/team Anyone have a Win7 box/VM to test this?

**Comment by hansmaad** [comment]
Zoom is 100%. The thickness of the visible part of the border changes with different zoom settings.

**Comment by XhmikosR** [comment]
@cvrebert: sorry, I don't have IE 11 on my Windows 7 VM because it ignores conditionals and it pissed me off :P

**Comment by kkirsche** [comment]
@cvrebert can grab a VM from https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/ if no one has one

**Comment by mrmlnc** [comment]
Confirmed on Windows 10 Edge && IE
![image](https://cloud.githubusercontent.com/assets/7034281/11126890/4cced350-8982-11e5-9cb8-4f527d573caf.png)
![image](https://cloud.githubusercontent.com/assets/7034281/11126941/81d05c22-8982-11e5-9e0a-0fd95c5c16ac.png)

**Comment by petetnt** [comment]
I can see it on Windows 8 IE11 when zoomed to 200% (and after zooming back 100% too). I recently wrestled with similar problem with IE (on non-Bootstrap related product) and the root cause was IE's High DPI scaling functionality (https://msdn.microsoft.com/en-us/library/dn265030%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

**Comment by R1chardTM** [comment]
Confirmed with Windows 10 Edge v20 on a high DPI screen. Best visible on 200% zoom, but also visible on 175% zoom. Cannot reproduce in Chrome on a high DPI screen.

![image](https://cloud.githubusercontent.com/assets/7275740/11502682/909f251c-983c-11e5-81d6-255ca11426d3.png)

**Comment by cvrebert** [comment]
Confirmed in Edge on Windows 10.

**Comment by cvrebert** [comment]
Filed Edge/IE11 bug: https://connect.microsoft.com/IE/feedback/details/2263132/edge-ie11-subpixel-problem-with-transparent-borders

**Comment by cvrebert** [comment]
For whatever reason, this doesn't *seem* to affect v4 (http://v4-alpha.getbootstrap.com/components/navs/#tabs).

**Comment by cvrebert** [comment]
@mdo Any interest in trying to figure out a workaround?

**Comment by petetnt** [comment]
@cvrebert v4, IE11, Windows 8, non-HDPI display, 100% zoom, first load:

![image](https://cloud.githubusercontent.com/assets/7641760/12446086/c3958596-bf70-11e5-8131-1e220b737f6b.png)

:fire:

**Comment by cvrebert** [comment]
@petetnt Huh. Window size or monitor resolution seems to be a factor, since v3 only reproduced for me when I had Edge's window maximized. Yet v4 didn't under the same conditions. Weird!

**Comment by mdo** [comment]
Fix in #21429. IE11 and Edge just don't like `transparent` here with whatever's happening with page rendering. Specific hex value works great though.
