### ISSUE TITLE
Heading size does not scale linearly

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#18220]
This can make it difficult to grasp which weight/priority/order a heading have.

![image](https://cloud.githubusercontent.com/assets/10222521/11093132/a6739e72-8888-11e5-9502-efcc8129f407.png)

#### Linear plot
![image](https://cloud.githubusercontent.com/assets/10222521/11093159/c5644390-8888-11e5-8ec5-4dc42e4cb2cf.png)

#### Exponential plot
![image](https://cloud.githubusercontent.com/assets/10222521/11093147/b3b4de2a-8888-11e5-857c-b1a13d50d037.png)

**Comment by cvrebert** [comment]
These sorts of things tend to favor "whatever looks visually pleasing to @mdo" over following strict mathematical formulas.
@vanillajonathan Also, I assume you're referring to Bootstrap v4 here?

**Comment by patrickhlauke** [comment]
Also, type scales used in design are generally not linear http://type-scale.com/

**Comment by mdo** [comment]
> These sorts of things tend to favor "whatever looks visually pleasing to @mdo" over following strict mathematical formulas.

:grin: Yup!

> This can make it difficult to grasp which weight/priority/order a heading have.

Headings are prioritized for you by the HTML spec. The order and priority is always `h1`, `h2`, `h3`, `h4`, `h5`, `h6`.

**Comment by cvrebert** [comment]
> Headings are prioritized for you by the HTML spec.

@mdo I think he meant "visually, as an end-user" (i.e. the average joes browsing the web).

**Comment by vanillajonathan** [comment]
@cvrebert this applies for both v3 and b4 since they use the same header sizes.

@mdo as cvrebert said, I was referring to the experience of the end-user which may have difficulties distinguishing between their weight.
