### ISSUE TITLE
Inline checkbox and radio text vertically misaligned on Firefox

### ISSUE THREAD

**Issue by hackel** [twbs/bootstrap#18239]
As seen in the first image below from your own documentation (http://getbootstrap.com/css/#inline-checkboxes-and-radios), checkboxes and radios are not properly aligned with their labels.  I believe this is due to the 4px top margin applied here: https://github.com/twbs/bootstrap/blob/master/less/forms.less#L54  In the second image, I disabled this margin, and they are aligned properly.
![bootstrap-checkbox-alignment](https://cloud.githubusercontent.com/assets/583677/11140888/331e9ddc-89a5-11e5-8332-a08ff7f8d7cb.png)

I'm running Firefox 44, but have seen this issue on previous Firefox versions for quite some time.

Edit: Also, when toggling that margin off in Chrome, the checkboxes get misaligned in the opposite way.

**Comment by cvrebert** [comment]
@hackel Could you please re-test against the latest code in the `master` branch?

**Comment by hackel** [comment]
I am still seeing it on master.

**Comment by cvrebert** [comment]
As of Bootstrap v3.3.6 and Firefox 44.0a2 on OS X, the labels seem to be aligned reasonably well:
<img width="369" alt="checkbox" src="https://cloud.githubusercontent.com/assets/419884/11491282/564411ea-9795-11e5-9570-833426fc697b.png">

I'm happy to reopen this if you can point out a case where the alignment is still bad.

**Comment by cvrebert** [comment]
X-Ref: #15791, #13936

**Comment by hackel** [comment]
Ah, okay, I am seeing #15791.  I don't use any proprietary operating systems so I can't say how it performs on them, but it's definitely still present in v3.3.6 on GNU/Linux/Xorg-based operating systems.  Not seeing it on Firefox 43 on Android/Linux at least!
