### ISSUE TITLE
What's the \9 in the styles for checkboxes?

### ISSUE THREAD

**Issue by ichuchvaga** [twbs/bootstrap#18231]
filename - bootstrap.css, uncompressed, v3.3.5.

not critical, tiny misprint take place at line#2523
__________________

input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9;
  line-height: normal;
}

**Comment by mrmlnc** [comment]
This is not a typo - this hack for IE (IE6, IE7, IE8, IE9).

**Comment by ichuchvaga** [comment]
Oh, sorry for my IE 'knowledge'..

**Comment by cvrebert** [comment]
Please search existing issues more in the future before opening new issues. Thanks!
