### ISSUE TITLE
v4: name of the dropdown menu item class

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18248]
The drop down menu got a `.dropdown-item` class. As far as i understand this class should be applied on the `a` or `button` elements. On the other hand the navigation component applies the `-item` class on the `li` element and has a `nav-link` class for the `a` elements.

So possible rename the  `.dropdown-item` class to  `.dropdown-link`?

**Comment by cvrebert** [comment]
`-link` could be slightly confusing since `<button>`s aren't links.

**Comment by mdo** [comment]
The way I think about it is to treat `-item` as the immediate child of the `.parent` part of that selector. Same goes with navs—`.nav-item` is the first child if you require a wrapping element around the `.nav-link`, and isn't required for all implementations.

**Comment by bassjobsen** [comment]
@mdo possible i do understand you wrong. For the dropdown menus you will need now:

```
<ul class="dropdown-menu">
<li><a class="dropdown-item">item 1</a></li>
</ul>
```
So the `a` is not the immediate child of the `ul`, so i suggest to rename it. Instead of the above i expect in accordance with the navigation component:

```
<ul class="dropdown-menu">
<li  class="dropdown-item"><a class="dropdown-link">item 1</a></li>
</ul>
```
I agree with @cvrebert that it is confusing for buttons. Maybe create both `dropdown-link` and `dropdown-button`

**Comment by cvrebert** [comment]
@bassjobsen v4 dropdowns use `<div>` instead of `<ul>`: http://v4-alpha.getbootstrap.com/components/dropdowns/#example
(Or at least, `<ul>` isn't currently explicitly supported)

**Comment by bassjobsen** [comment]
@cvrebert thanks, i see now, so keep closed
