### ISSUE TITLE
Make label-pills truly pill shaped at all sizes (v4)

### ISSUE THREAD

**Issue by asnoba** [twbs/bootstrap#18241]
When making a larger `label-pill` the borders are not perfectly rounded. So instead of...
```
.label-pill {
   border-radius: 1rem;
}
```
...maybe this would be better:
```
.label-pill {
  border-radius: 999em;
}
```

**Comment by mdo** [comment]
Fixed in 36b33bd145af0ac212e7d6ce88cc9b7abc9f43fc.
