### ISSUE TITLE
The presentation video isn't available in France

### ISSUE THREAD

**Issue by fredericlefeurmou** [twbs/bootstrap#18242]
On [this page](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/), the youtube presentation video isn't available for France.

http://www.awesomescreenshot.com/image/750749/117cb04220c38c2c5216cce1ef9be777

**Comment by MrGeneric** [comment]
It's just a music video for the following song.

REO Speedwagon - Roll With The Changes
