### ISSUE TITLE
Improper alignment using input with add-on within card

### ISSUE THREAD

**Issue by willgeiger** [twbs/bootstrap#18243]
Inputs with an addon, placed within a card seem to get centered in it's parents container, and have unnecessary space around them. I tried just about everything, using utility classes to strip padding, margin, and set floats, but nothing works.

http://i.stack.imgur.com/a8A7Q.jpg
http://stackoverflow.com/questions/33679680/bootstrap-4-0-0-alpha-improper-alignment-using-input-with-add-on-within-card

**Comment by mdo** [comment]
This is a result of nested `display: table` styles. Unsure how best to reset that just yet.

**Comment by willgeiger** [comment]
Any movement on this? Or, any suggestions on how I can override the css to resolve it?

**Comment by mdo** [comment]
This was closed by our move to flexbox by default in #21389.
