### ISSUE TITLE
v4: question should media query mixin be nested or not?

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18259]
not nested: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_jumbotron.scss#L12
nested: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L11

related: https://github.com/twbs/bootstrap/pull/18258

**Comment by mdo** [comment]
Either works, but I think I prefer nested.
