### ISSUE TITLE
The modal does not scroll

### ISSUE THREAD

**Issue by panovek** [twbs/bootstrap#18262]
If my page does not have scrollbar before and i opening the long modal, which adding scrollbar on the page, then scroll the modal does not work.
In Chrome and Opera.

**Comment by kukac7** [comment]
@panovek [it works in the example?](http://getbootstrap.com/javascript/#modals)

**Comment by panovek** [comment]
example on [bootstrap site](http://getbootstrap.com/javascript/#modals) is working, because page already has a scrollbar.
Right now i cannot create clear example, sorry.

**Comment by panovek** [comment]
additional info:
 - mouse wheel scroll in the modal does not work. although the keys scroll - work.
 - after focusing some element inside the modal, mouse wheel scroll begining work.

**Comment by cvrebert** [comment]
Unable to reproduce with https://github.com/twbs/bootstrap/blob/master/js/tests/visual/modal.html , which covers the case of a page without a scrollbar with a long modal that requires a scrollbar. Scrolling the modal works fine for me in OS X Chrome.
Unless someone has a live example (e.g. JS Fiddle or JS Bin) that demonstrates the problem, there's not much we can do here. Happy to reopen if someone posts such an example though.
