### ISSUE TITLE
Documentation licensing

### ISSUE THREAD

**Issue by Hacktivista** [twbs/bootstrap#18269]
Since the documentation examples are intended to be used as copy-paste, and the code is already licensed, why using attribution license for examples and pieces of code instead of CC0?

**Comment by kkirsche** [comment]
I'd start by reviewing issues #16470 and #16487 — for the most part this has to do with the need to contact every single individual contributor who has ever touched the docs to change which is an extremely painful process for a project of this size as I understand it.

**Comment by mdo** [comment]
Closing out since there are no planned changes here.

The docs content itself is under a different license than the code, yes, but the code included there is still under that MIT license as far as I know. However, as I'm no lawyer, if someone has a more authoritative source, I'd happily revisit.

**Comment by dcousens** [comment]
@mdo to clarify,  are the [examples](https://getbootstrap.com/docs/4.1/examples/) are MIT licensed?

The README states "Code released under the MIT License.",  which seems to be a resounding **yes**... 
But then "Docs released under Creative Commons." ... hmph.

The examples are under `docs/`,  but they are *Code*... which is it?
