### ISSUE TITLE
Add boolean variables to enable/disable CSS components

### ISSUE THREAD

**Issue by asnoba** [twbs/bootstrap#18273]
Hi,

When developing with Bootstrap it would be nice if it was possible to turn on/off components in the variables.scss file to keep file sizes down.

Maybe something like this:
```
$components: (
  alert: true,
  breadcrumb: true,
  ...
) !default;
```
... and something like this in each component:
```
@if map-get($components, alert) == true {
  .alert {
    ...
  }
}
```

**Comment by mmjaeger** [comment]
+1

**Comment by cvrebert** [comment]
This was discussed internally in https://github.com/twbs/derpstrap/pull/127.
The suggestion there was for folks to write their own SCSS file that `@import`s only the specific Bootstrap components that they want (in other words, write your own https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss).

**Comment by asnoba** [comment]
@cvrebert – Yes, this is what I've been doing up until now, but when including UI components in different projects a variable overwrite would be better than having multiple files with `@import` in them.

**Comment by simonewebdesign** [comment]
@asnoba You can as well use [uncss](https://github.com/giakki/uncss) to remove the unused CSS at a later stage.

**Comment by asnoba** [comment]
Thanks for the tip @simonewebdesign :)

**Comment by mdo** [comment]
My main reason for it is that it seems to just be a re-implementation of existing CSS core functionality—you import files to use them. Adding variables to also do that seems over-engineered to me.
