### ISSUE TITLE
.hidden-print Fails

### ISSUE THREAD

**Issue by Merovex** [twbs/bootstrap#18276]
@media print {
  .hidden-print .hidden-print {
    display: none !important;
  }
}

The above is the code block in http://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css.

I'm assuming it should just be .hidden-print.

**Comment by patrickhlauke** [comment]
> The above is the code block in http://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css

I'm seeing 

```
@media print {
  .hidden-print {
    display: none !important;
  }
}
```

**Comment by Merovex** [comment]
![screenshot 2015-11-17 06 52 43](https://cloud.githubusercontent.com/assets/108851/11210707/ff1b8544-8cf7-11e5-88c4-cc2f0eab5a2d.png)

**Comment by Merovex** [comment]
[image: Inline image 2]

On Tue, Nov 17, 2015 at 6:51 AM, Patrick H. Lauke <notifications@github.com>
wrote:

> The above is the code block in
> http://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
>
> I'm seeing
>
> @media print {
>   .hidden-print {
>     display: none !important;
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/18276#issuecomment-157347122>.
>



-- 
Ambuletis Digne,
Ben Wilson

We complain because we forget.

**Comment by Merovex** [comment]
Bottom of the file.

And, it's still failing.

**Comment by patrickhlauke** [comment]
![capture](https://cloud.githubusercontent.com/assets/895831/11210751/352ecd2e-8d22-11e5-81a6-aa34c212f382.PNG)

don't know what to tell you other than "github's CDN may be borked or something". what does https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css look like at your end?

**Comment by patrickhlauke** [comment]
see also #17876

**Comment by Merovex** [comment]
I was just looking at that. It looks fine. Couldn't be a Chrome thing, not used to seeing something like this on the browser. But, your other ticket refers to Chrome.

Chrome Bug? Shows up in FF as well (just checked).

It'll work out by final, and I don't anticipate people printing the site in question. ;-)

**Comment by patrickhlauke** [comment]
my point is that it's not an issue with the browser, but an issue with something happening at CDN level - it's sending different text for some reason. you're obviously safer to grab your own clean copy of the CSS for now and not rely on CDNs

**Comment by Merovex** [comment]
Only other suggestion is to blow away that file on the CDN, then repopulate
it. But that might peeve a few people.

No worries here keeping it closed.

On Tue, Nov 17, 2015 at 7:06 AM, Patrick H. Lauke <notifications@github.com>
wrote:

> see also #17876 <https://github.com/twbs/bootstrap/issues/17876>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/18276#issuecomment-157350683>.
>



-- 
Ambuletis Digne,
Ben Wilson

We complain because we forget.
