### ISSUE TITLE
Dynamic generation of "navbar-toggleable"-classes

### ISSUE THREAD

**Issue by sergej2705** [twbs/bootstrap#18289]
I want to have 6 grid-breakpoints in twbs 4 and have defined:

    $grid-breakpoints: (
      xs: 0,
      ms: 30em,
      sm: 45em,
      md: 58em,
      lg: 65em,
      xl: 95em
    ) !default;

but now it generates:

    @media (min-width: 45em) {
      .navbar-toggleable-xs {
        display: block !important;
      }
    }
    @media (min-width: 58em) {
      .navbar-toggleable-sm {
        display: block !important;
      }
    }

So `.navbar-toggleable-xs` is used in `xs` and `ms`-size and there is no `.navbar-toggleable-ms`.

It would be better If `.navbar-toggleable-*` would be generated dynamiclly. Probably in all sizes, also `md`, `lg` and `xl`.

**Comment by mdo** [comment]
Going to punt on this for now given I still need to rewrite massive areas of the navbar.
