### ISSUE TITLE
data cache of $tip doesn't cleaned after "show" has been triggered

### ISSUE THREAD

**Issue by gabbersepp** [twbs/bootstrap#18282]
Show Tooltip and destroy it will lead to memory leaks.

StR:
1. Setup a tooltip on any element
2. Open profiler and take heap snapshot
3. Move mouse over the element
4. Call destroy method in console on this element
5. Take another heap snapshot
6. Have a look at those objects that are created between both snapshots

Result:
The tooltip stays in the jquery data cache.

Expected Result:
After calling destroy() there should nothing remain in memory.

Please have a look at the first picture. Snahsphot_1 was taken before triggering the tooltip. Snapshot_2 after calling destroy().
You can see that there are data in the cache left.

I tjhink it is because of following lines of code in the show() function:

``` javascript
                 $tip
                 .detach()
                 .css({ top: 0, left: 0, display: 'block' })
                 .addClass(placement)
                 .data('bs.' + this.type, this)
```

Then in the destroy() function the data of $tip gets not removed:

```
      that.$element.off('.' + that.type).removeData('bs.' + that.type)
      if (that.$tip) {
        that.$tip.detach()
      }
```

YOu see that the data is removed from the element but not from $tip.
Calling $(element).data("bs.tooltip").$tip.remove() in my own code (where 'element' is my html element where the tooltip was set on) will lead to the second picture. Again the same test scenario but you see that there is notjhing left in the cache.

![tooltip_in_cache](https://cloud.githubusercontent.com/assets/3234900/11264315/fb47d368-8e92-11e5-9538-eb654a720828.PNG)
![tooltip_not_in_cache](https://cloud.githubusercontent.com/assets/3234900/11264316/fb494bbc-8e92-11e5-9d0f-e7423f16f6c6.PNG)

Use following example for testing (remember to remove the $tip.remove() line before testing):

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

  </head>
  <body>
    <h1>Hello, world!</h1>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="js/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.js"></script>

    <script>
    $(window).load(function() {
            containerTemplate =
            '<div class="tooltip fixed" role="tooltip"><div class="tooltip-inner TOOLTIP-WIDTH"></div></div>';

        tooltipTemplateTitle = "<div class='tooltip-title'>TITLE</div>";
        tooltipTemplateDesc = "<div class='tooltip-description'>DESCRIPTION</div>";
                var defaults = {
                animation: true,
                html: true,
                title: 'blub',
                placement: 'auto',
                container: 'body',
                template: containerTemplate.replace("TOOLTIP-WIDTH", "small"),
                delay: { show: 100, hide: 100 } };

        $("h1").tooltip(defaults);

        window.dest = function() {
        $("h1").data("bs.tooltip").$tip.remove();
        $("h1").tooltip("destroy")
        };
    });
    </script>
  </body>
</html>
```

**Comment by cvrebert** [comment]
@gabbersepp Could you please make your example into a JSFiddle or JS Bin?

**Comment by gabbersepp** [comment]
@cvrebert 
Of course. Sorry. I forgot about this.

https://jsfiddle.net/srsrnrhs/1/

**Comment by crashnick16** [comment]
i am also experiencing this problem, is there any fix for this?

**Comment by mdo** [comment]
Closing as this is for v3 and we're not actively working on that version.
