### ISSUE TITLE
Add flexbox-enabled CSS to v4 /dist

### ISSUE THREAD

**Issue by MichaelRushton** [twbs/bootstrap#18292]
For those who don't want to download and compile the SCSS files it'll be useful to include something like bootstrap-flexbox.css in the dist folder.

**Comment by arechsteiner** [comment]
With Microsoft dropping support for IE10 and lower in two months ([source](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support)), I'd even argue to make flexbox the new default and additionally provide a bootstrap-**no**flexbox.css in the dist folder.

**Comment by mdo** [comment]
> For those who don't want to download and compile the SCSS files it'll be useful to include something like bootstrap-flexbox.css in the dist folder.

That could be interesting. I think I had these files being generated at some point, but hated the extra noise it added to all our diffs.

> I'd even argue to make flexbox the new default and additionally provide a bootstrap-noflexbox.css in the dist folder.

We won't be doing that.

**Comment by cvrebert** [comment]
Additionally, caniuse recently [downgraded its rating of IE11's flexbox support](https://github.com/Fyrd/caniuse/commit/825979d5a021dea7a0e6e5ab8d480fbbbda082b2#diff-1b8d821657901f8f24989e29fc993a7f) due to how buggy it is.

**Comment by arechsteiner** [comment]
>We won't be doing that.

@mdo: Could you elaborate why? I'm not trying to argue, but I'm curious what the reasoning is.

**Comment by cvrebert** [comment]
Bootstrap v4 currently aims to be compatible with IE9+ out of the box. (This ratchets the minimum IE version up one notch from v3, which supported IE8+.)

**Comment by GitMiester** [comment]
This would be so useful right now.  The build system can be a challenge and a barrier to using this awesome flexbox file.

**Comment by mdo** [comment]
Exploring this in #20682.
