### ISSUE TITLE
Release bv4

### ISSUE THREAD

**Issue by B-iggy** [twbs/bootstrap#18297]
Hey guys,
after Foundation launched his v6 yesterday I wonder when does bv4 comes out? Any vague idea?
Keep up. 
Thanks

**Comment by zacechola** [comment]
🔜

([The alpha is already out](http://v4-alpha.getbootstrap.com/).)

**Comment by B-iggy** [comment]
Alright. Regarding this list http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/ it's a very very late soon. I thought it would be a race between f6 and bs4 ;)
Till next year then.

**Comment by cvrebert** [comment]
http://blog.getbootstrap.com/2015/12/08/bootstrap-4-alpha-2/
