### ISSUE TITLE
sticky-footer example shows vertical scrollbar in v4 but in v3

### ISSUE THREAD

**Issue by ksmets** [twbs/bootstrap#18293]
How can we get rid of the vertical scrollbar in the sticky footer example?

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem.

Thanks for your understanding and cooperation!

**Comment by cvrebert** [comment]
Confirmed in Chrome with c960169807102d1f78b700fbadac44106ff06716.

**Comment by mdo** [comment]
Fixed with 3d45bd6.
