### ISSUE TITLE
dropdown-menu in table-responsive  were covered

### ISSUE THREAD

**Issue by chiaki-yu** [twbs/bootstrap#18307]
In \<div class="table-responsive"\>,
If there is a \<div class="dropdown"\>, 
then the \<ul class="dropdown-menu"\>  will be covered by \<div class="table-responsive"\>

**Comment by cvrebert** [comment]
Kindly read our fine documentation which explicitly covers this: http://getbootstrap.com/css/#callout-tables-responsive-overflow
