### ISSUE TITLE
If explicit target not specified, clicked tab should activate tabpanel of same ordinal position

### ISSUE THREAD

**Issue by tarranjones** [twbs/bootstrap#18301]
The following code would allow tabs to function without selectors providing they are wrapped either within a `[role=tabpanel]` or a `[role=tabcontainer]`. The default behaviour would pair the index `[role="tab"]` to `[role="tabpanel"]`. 
This allows for deep nesting tabs without specifying #ids or .classes. 
If a tab is required to perform something other than the default pairing then a selector can be specified.
If multiple matching targets are found then the selector is looked for within the context of the wrapper.

If at this point more that one matching targets are found then it selects the target which has the same  `[role="tabpanel"]` index as the `[role="tab"]` if it exists. 

Otherwise the $target does not change and the script continues as normal. 

The JavaScript is probably the best approach for best performance, I has many nested `if, else`'s which may look untidy but makes sure no unnecessary methods are called. 

I recommend looking/testing the demo

<p data-height="268" data-theme-id="0" data-slug-hash="avMKgM" data-default-tab="result" data-user="tarranjones" class='codepen'>See the Pen <a href='http://codepen.io/tarranjones/pen/avMKgM/'>Bootstrap tab.js (working nested tabs without using selectors)</a> by Tarran Jones (<a href='http://codepen.io/tarranjones'>@tarranjones</a>) on <a href='http://codepen.io'>CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

```
// changes
if ($target.length != 1) {
    var container = '[role="tabpanel"],[role="tabcontainer"]'
    var $context = $this.closest(container);
    if ($context.length) {
        if ($target.length > 1) {
            $target_idx = $context.find(selector).filter(':eq(' + $this.parent().index() + ')')
        } else {
            $target_idx = $context.find(container).filter(function(i, el) {
                var $closest = $(el).parent().closest(container, $context);
                return !$closest.length || $context.is($closest);
            }).eq($this.parent().index());
        }
        if ($target_idx.length) $target = $target_idx
    }
}
```

**Comment by twbs-lmvtfy** [comment]
Hi @dtjones!

You appear to have posted a live example (http://codepen.io/tarranjones/pen/avMKgM.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 43: Bad value ```` tabcontainer ```` for attribute ```` role ```` on element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dtjones** [comment]
unfortunately `tabcontainer` and `tabgroup` do not validate as html5 role values so have changed it to `group` http://www.w3.org/wiki/PF/XTech/HTML5/RoleAttribute

**Comment by dtjones** [comment]
The following code would allow tabs to function without selectors providing they are wrapped either within a `[role=tabpanel]` or a `[role=group]`. The default behaviour would pair the index `[role="tab"]` to `[role="tabpanel"]`. 
This allows for deep nesting tabs without specifying #ids or .classes. 
If a tab is required to perform something other than the default pairing then a selector can be specified.
If multiple matching targets are found then the selector is looked for within the context of the wrapper.

If at this point more that one matching targets are found then it selects the target which has the same  `[role="tabpanel"]` index as the `[role="tab"]` if it exists. 

Otherwise the $target does not change and the script continues as normal. 

The JavaScript is probably the best approach for best performance, I has many nested `if, else`'s which may look untidy but makes sure no unnecessary methods are called. 

I recommend looking/testing the demo

<p data-height="268" data-theme-id="0" data-slug-hash="avMKgM" data-default-tab="result" data-user="tarranjones" class='codepen'>See the Pen <a href='http://codepen.io/tarranjones/pen/avMKgM/'>Bootstrap tab.js (working nested tabs without using selectors)</a> by Tarran Jones (<a href='http://codepen.io/tarranjones'>@tarranjones</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>



	// changes
	if ($target.length != 1) {
		var container = '[role="tabpanel"],[role="group"]'
		var $context = $this.closest(container);
		if ($context.length) {
			if ($target.length > 1) {
				$target_idx = $context.find(selector).filter(':eq(' + $this.parent().index() + ')')
			} else {
				$target_idx = $context.find(container).filter(function(i, el) {
					var $closest = $(el).parent().closest(container, $context);
					return !$closest.length || $context.is($closest);
				}).eq($this.parent().index());
			}
			if ($target_idx.length) $target = $target_idx
		}
	}

**Comment by twbs-lmvtfy** [comment]
Hi @dtjones!

You appear to have posted a live example (http://codepen.io/tarranjones/pen/avMKgM.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 1709, column 1: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.5 ; saw what appears to be usage of Bootstrap 3.2.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dtjones** [comment]
@twbs-lmvtfy, i know your a bot but it would be brilliant if you gave me all the errors at once

**Comment by dtjones** [comment]
http://codepen.io/tarranjones/pen/avMKgM

**Comment by dtjones** [comment]
<p data-height="268" data-theme-id="0" data-slug-hash="avMKgM" data-default-tab="result" data-user="tarranjones" class='codepen'>See the Pen <a href='http://codepen.io/tarranjones/pen/avMKgM/'>Bootstrap tab.js (working nested tabs without using selectors)</a> by Tarran Jones (<a href='http://codepen.io/tarranjones'>@tarranjones</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by cvrebert** [comment]
> @twbs-lmvtfy, i know your a bot but it would be brilliant if you gave me all the errors at once

Suffice it to say that Bootlinting only known-valid HTML avoids false positives (which would be more annoying) and we lack funding for a fancier option which would require the bot to assess the severity of the HTML validity errors.

**Comment by cvrebert** [comment]
@patrickhlauke Would the lack of `aria-controls` attributes render the example inaccessible?

**Comment by patrickhlauke** [comment]
One issue created by not having `aria-controls` is that it breaks functionality in certain AT (e.g. JAWS) that let the user jump directly to whatever content/element the currently focused widget is controlling (e.g. in JAWS you can use JAWS KEY+ALT+M to jump directly to the relevant tab panel). I'd be more comfortable if - in case an proper `id`/`aria-controls` pairing is missing - one was generated dynamically via JS)

**Comment by mdo** [comment]
Punting on this and opting for explicit behavior instead.
