### ISSUE TITLE
v4 tooltip position doesn't work when link spans two lines

### ISSUE THREAD

**Issue by MichaelRushton** [twbs/bootstrap#18304]
As shown in the Bootstrap documentation. Note that I'm hovering over "whatever keytar":

![tooltip](https://cloud.githubusercontent.com/assets/681130/11309096/d488e3ca-8fb9-11e5-981e-b495eed2f2d4.png)

**Comment by kkirsche** [comment]
Would this be a bug for HubSpot/tether which is what we use for positioning in V4?

**Comment by cvrebert** [comment]
http://v4-alpha.getbootstrap.com/components/tooltips/#overview (emphasis mine) : 
> Things to know when using the tooltip plugin:
> [...]
> * **When triggered from hyperlinks that span multiple lines, tooltips will be centered.** Use `white-space: nowrap;` on your `<a>`s to avoid this behavior.

Suggestions for different behavior in this case should indeed be directed to https://github.com/HubSpot/tether/issues rather than here.
