### ISSUE TITLE
error when input name is 'nodeName'

### ISSUE THREAD

**Issue by leo108** [twbs/bootstrap#18318]
http://jsfiddle.net/tb9ooc8q/

There is only a text input named `nodeName` in a `form` tag, when click the input box, it triggers a error:
> Uncaught TypeError: elem.nodeName.toLowerCase is not a function

it only happens when the input's name is `nodeName`

**Comment by patrickhlauke** [comment]
that seems to be a problem with jQuery, rather than Bootstrap? /cc @fat

**Comment by leo108** [comment]
@patrickhlauke http://jsfiddle.net/8q3sL5s9/ without bootstrap it is OK

**Comment by patrickhlauke** [comment]
well, without Bootstrap there's no actual JavaScript code being executed, so jQuery is not called...

**Comment by patrickhlauke** [comment]
"Uncaught TypeError: elem.nodeName.toLowerCase is not a function" jquery-2.1.3.js:1626

**Comment by cvrebert** [comment]
Duplicate of https://github.com/jquery/jquery/issues/1721
