### ISSUE TITLE
Circular reference when assetic/sass compile

### ISSUE THREAD

**Issue by deguich** [twbs/bootstrap#18316]
Hi,

With this configuration : 
- Windows 8.1
- sass default ruby compiler
- symfony 2.7
- assetic lib

This comment in _reboot.scss line 47 causes a circular reference assetic compilation error :
// `.class-name { @import "bootstrap"; }`).

Assetic library probably ignore comment. Error occur only in browser mode.

"php app/console assetic:dump" command well produce the bootstrap.css

I post the same issue in assetic library git.

**Comment by cvrebert** [comment]
Closing in favor of https://github.com/kriswallsmith/assetic/issues/779
We don't officially support build tools other than the Gruntfile that we provide. So, sorry, can't help you with Assetic.
