### ISSUE TITLE
Margin left-right navbar-form with nav-link

### ISSUE THREAD

**Issue by unehub** [twbs/bootstrap#18312]
Hello, there is an issue that has never been solved on Bootstrap 3 and now in Bootstrap 4 is not the exception. When we use the pull-right form-search and then want to add a list of icons do not have margins.

    <header class="navbar navbar-light navbar-static-top bg-faded">
        <ul class="nav navbar-nav pull-right">
          <a class="nav-link active" href="">
            <span class="icon sm icon-cart"></span>
            <span class="label label-info">0</span>
          </a>
        </ul>
        <form role="search" class="form-inline navbar-form pull-right hidden-sm-down" style="">
          <div class="input-group">
            <input type="search" placeholder="Search product..." class="form-control" id="query">
            <div class="input-group-btn">
              <button type="submit" class="btn btn-info-outline">
                <span aria-hidden="true" class="icon icon-search"></span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </header>

![captura de pantalla 2015-11-22 a las 1 10 55 p m](https://cloud.githubusercontent.com/assets/14114839/11325392/7dbd448e-911a-11e5-951d-7da079777902.png)

     <form style="margin-right: 15px;">

![captura de pantalla 2015-11-22 a las 1 05 22 p m](https://cloud.githubusercontent.com/assets/14114839/11325397/a5ca3c48-911a-11e5-93d0-55d58539532a.png)

There must be a way to keep adding items maintaining margins.

**Comment by mdo** [comment]
This will be addressable in v4 with utility spacing classes.

**Comment by cvrebert** [comment]
i.e. http://v4-alpha.getbootstrap.com/components/utilities/#spacing
