### ISSUE TITLE
navbar fix to dissuade from the ul > li > a 

### ISSUE THREAD

**Issue by hwnder** [twbs/bootstrap#18310]
I've been playing around with the bootstrap v4 navbar to get the mobile/desktop responsiveness kinks out and to be able to avoid using unordered lists and list items when building the nav class.

[Codepen](http://codepen.io/hwnd/pen/vNbLyV) &mdash; [Page view](http://codepen.io/hwnd/full/vNbLyV/) (shrink the browser to verify the mobile nav)

----

##### HTML

    <header class="navbar navbar-light navbar-fixed-top" role="banner">
      <div class="container">
        <div class="clearfix">
          <button class="navbar-toggler pull-right hidden-sm-up" type="button" data-toggle="collapse" data-target="#build-nav">
            &#9776;
          </button>
          <a class="navbar-brand" href="/"><i class="fa fa-500px"></i></a>
        </div>
        <div class="collapse navbar-toggleable-xs" id="build-nav">
          <nav class="nav navbar-nav" role="navigation">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link" href="/">Blog</a>
          </nav>
        </div>
      </div>
    </header>

##### CSS

    .navbar-nav .nav-item { float: none }

    .navbar-nav .nav-item + .nav-item,
    .navbar-nav .nav-link + .nav-link { margin-left: 0 }

    @media (min-width: 34em) {
      .clearfix:after { display: none }  
  
      .navbar-nav .nav-item { float: left }
  
      .navbar-nav .nav-item + .nav-item,
      .navbar-nav .nav-link + .nav-link { margin-left: 1rem }
    }

If you have a better way of implementing this, please leave some feedback.

----

The other issue I came across is that when you change the font-size of the navbar, the `nav-link` elements shift up and if you're using a font-icon or svg for a logo the line-height is messed up.

And if you change the `navbar-brand` font-size it looks distorted and hideous.

You can see what I mean: http://codepen.io/hwnd/pen/BoEVog

Has anyone came across this, do I just need to manually change the line-height?

**Comment by mdo** [comment]
Added some stuff for non-list based navs in navbars in e61eae4.
