### ISSUE TITLE
Support - is this possible with boostrap ?

### ISSUE THREAD

**Issue by henrix343** [twbs/bootstrap#18315]
Hi I'm starting to make some interest in boostrap. Fast question to see it is worth the time to start :)

Is this - http://i65.tinypic.com/29eoy2a.png possible with boostrap grid system ? Thanks!

**Comment by wolfy1339** [comment]
This question would be better off on StackOverflow, since the issues aren't for personal help requests.
But, yes it could be possible

**Comment by cvrebert** [comment]
As noted, the bug tracker is not the right venue for personal help requests.
See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker for links to proper venues for such requests. Thanks.

**Comment by henrix343** [comment]
Ohhh, got it. Ok pls remove this topic.
