### ISSUE TITLE
Tooltip shares same tip after use of jQuery.clone(true)

### ISSUE THREAD

**Issue by nsarazin** [twbs/bootstrap#18326]
Hello,

When we want to clone an element which has a tooltip, the result depends on arguments crossed in parameters : 

If we use ".clone(true)", the tooltip doesn't work has expected on the cloned element.
If we use ".clone()", the tooltip works has expected on the cloned element.

See https://jsfiddle.net/t3z2vuw9/ for an example.

**Comment by twbs-lmvtfy** [comment]
Hi @nsarazin!

You appear to have posted a live example (https://fiddle.jshell.net/c8c2pcn4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 94, column 13: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 97, column 13: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by nsarazin** [comment]
Revised example : https://jsfiddle.net/t3z2vuw9/

**Comment by cvrebert** [comment]
This also applies to v4.

**Comment by cvrebert** [comment]
jQuery API docs: http://api.jquery.com/clone/

FWICT, jQuery (nor raw DOM) doesn't offer any callback or event which is activated when an element has been cloned, which makes fixing this nontrivial. I suppose we could add a circular reference to detect the cloning after the fact, but that's an invitation to a DOM node memory leak, and there might still be complications if you clone a tooltip when it's in certain states or while a transition is in progress.

@fat Do we care about supporting this?

**Comment by mdo** [comment]
I'll go ahead and say with the lack of activity around this one, we probably don't care. :grin: Please holler folks if there's more to do here.

**Comment by didix16** [comment]
Hi, I'm experimenting this issue. Are there any solution to workarround this bug? How can reassign a tooltip to a cloned node? Thanks
