### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by xc4patryk** [twbs/bootstrap#18322]
Hello dev,

Thank you for great css/js framework. Anyway. I TEST Bootstrap 4

When i wanted to do login panel with col-md-4 (e.g) and 100% width for panel class then i have bad scale. Left margin had +- 50px but right had +- 10px 

-- Result -- I think that mobile scale should be center.

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by xc4patryk** [comment]
Ok, i'm new - sorry !

http://screenshu.com/static/uploads/temporary/if/fj/3v/uuag7e.jpg
http://screenshu.com/static/uploads/temporary/ic/rj/vz/b1bs6y.jpg

**Comment by kkirsche** [comment]
Can you please provide a JSBin as requested not screenshots. Live code makes debugging possible while screenshots we can't really help.
