### ISSUE TITLE
Option to replace Glyphicons with Font Awesome

### ISSUE THREAD

**Issue by cristiammercado** [twbs/bootstrap#18321]
Hi,

We all know the icons from Glypicons set (Halflings) is very limited, and Font Awesome has a vast amount of icons to use in a free way.

Is it possible to add an option to download Bootstrap whit FA package, rather than Glyphicons?

**Comment by patrickhlauke** [comment]
Font icons will be completely removed in v4, leaving it up to developers to add their preferred icon solution.
