### ISSUE TITLE
Incorrect percentage width syntax for Holder.js placeholders

### ISSUE THREAD

**Issue by SteveGriffith** [twbs/bootstrap#18333]
In the documentation for the new [Cards](http://v4-alpha.getbootstrap.com/components/card/#image-caps), the sample for image-caps is using holder.js and a percentage for the width.
The code sample is using:
 data-src="holder.js/100%x180/" 

However, [percentages in holder.js are denoted with the letter p instead of a percentage sign.](https://github.com/imsky/holder/blob/master/README.md#fluid-placeholders)
The example should be:
 data-src="holder.js/100px180"

**Comment by SteveGriffith** [comment]
data-src="holder.js/100px180"

data-src="holder.js/100px180"

- these are the values from above which were filtered out.

**Comment by Deilv** [comment]
@cvrebert This seems already fixed in 1ba807f (https://github.com/twbs/bootstrap/commit/1ba807f15dc18e4762fa0d03df0ec746a69283be#diff-554b8e9cc1baf50f739a3e29deda2d86).

**Comment by cvrebert** [comment]
Indeed!
