### ISSUE TITLE
Calculation of m-*-md, m-*-lg, p-*-md and p-*-lg refers to wrong variable

### ISSUE THREAD

**Issue by sergej2705** [twbs/bootstrap#18339]
The calculation of `m-*-md`, `m-*-lg`, `p-*-md` and `p-*-lg` uses twice `$spacer-y` instead of `$spacer-x`:

    .m-a-md { margin:        ($spacer * 1.5) !important; }
    .m-t-md { margin-top:    ($spacer-y * 1.5) !important; }
    .m-r-md { margin-right:  ($spacer-y * 1.5) !important; }
    .m-b-md { margin-bottom: ($spacer-y * 1.5) !important; }
    .m-l-md { margin-left:   ($spacer-y * 1.5) !important; }
    .m-x-md { margin-right:  ($spacer-x * 1.5) !important; margin-left:   ($spacer-x * 1.5) !important; }
    .m-y-md { margin-top:    ($spacer-y * 1.5) !important; margin-bottom: ($spacer-y * 1.5) !important; }

The `m-*` and `p-*`-classes are calculated right.

And I would calculate `.m-a-md { margin: ($spacer * 1.5) !important; }` more like `.m-a-md { margin: ($spacer-y * 1.5) ($spacer-x * 1.5) !important; }` because it generates the more expected output.

**Comment by cvrebert** [comment]
I believe #18185 fixes the X/Y switcheroos you mention.

**Comment by sergej2705** [comment]
I think it should solve it ;-) thank you
