### ISSUE TITLE
Missing some codes in documentation for Dropdown function 

### ISSUE THREAD

**Issue by shimag** [twbs/bootstrap#18344]
In Javascript menu for Dropdown function, in order to be more Learnable for user ,it would better if add this two lines of code:  `<li>Action</li> <li>Another action</li>` ...
in this 
```html
<ul class="dropdown-menu" aria-labelledby="dLabel">
    ...
  </ul> 
```
to be like the example.

**Comment by Khrysller** [comment]
This is an overall situation with v3 docs. I agree the examples should be more real with the results.
+1

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
