### ISSUE TITLE
Feature Request: Affix enabled/disabled for each media breakpoint

### ISSUE THREAD

**Issue by krnlde** [twbs/bootstrap#18341]
We had the issue a lot of times where - for example the navbar - has to be sticky on `< @grid-float-breakpoint` but not on `>= @grid-float-breakpoint`. Currently the affix is lacking that feature and it is really complicated to destroy an affix instance (#5870, #13655).

I would love a consistent way to bind an affix to a specific media breakpoint.

Here are some suggestions to achieve that:

```
<div data-spy="affix" data-offset-top="60" data-offset-bottom="200" data-min-width="768" data-max-width="data-min-width="996">
  ...
</div>
```

Or as suggested for [srcset](https://ericportis.com/posts/2014/srcset-sizes/):

```
<div data-spy="affix" data-offset-top="60" data-offset-bottom="200" sizes="(min-width: 768px) and (max-width: 996px)">
  ...
</div>
```

**Comment by cvrebert** [comment]
The Affix plugin is gone in Bootstrap v4 (see http://v4-alpha.getbootstrap.com/migration/#components ), and we are no longer accepting new features into Bootstrap v3.
