### ISSUE TITLE
Mobile Scale - Grid

### ISSUE THREAD

**Issue by xc4patryk** [twbs/bootstrap#18349]
Hello dev,

I want to scale RIGHT panel first, but bootstrap scale MOBILE from LEFT

_______________________________________
Bootstrap grid scale (mobile):
1                 2                 3

I want:
3                 1                 2
_______________________________________

My Question: Bootstrap this enables or not ?

**Comment by cvrebert** [comment]
Please direct how-to questions to StackOverflow. Thanks.
