### ISSUE TITLE
Expandable card group/deck

### ISSUE THREAD

**Issue by bsrdjan** [twbs/bootstrap#18345]
Hi,
I have collections of 3 to 20 cards, grouped currently into one card group or deck.
On opening the view, 1 to 3 cards shall be visible and, if the users wants so (click on some element), expand the view to show all cards. Any example in that direction ?
Thanks,
srdjan

**Comment by mdo** [comment]
No examples currently planned for that, nor specific feature development. You could probably setup the collapse plugin to support something like that though.
