### ISSUE TITLE
SRI hashes in docs are outdated/wrong

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18353]
They weren't updated from their v3.3.5 values during the v3.3.6 release process.
(I've submitted a PR to add relevant steps to the internal "how to ship" document to prevent this from recurring in the future.)

**Comment by ztane** [comment]
+1

**Comment by mikexstudios** [comment]
Hey @cvrebert I submitted a simple PR (#18369) in case you needed a quick fix. Thanks.
