### ISSUE TITLE
Collapsible navbar-fixed-top gets clipped when uncollapsed

### ISSUE THREAD

**Issue by xc4patryk** [twbs/bootstrap#18358]
Hello,

Bootstrap v4 doesn't support navbar fixed with collapse:
https://output.jsbin.com/lecosohuxa

**Comment by twbs-lmvtfy** [comment]
Hi @xc4patryk!

You appear to have posted a live example (https://jsbin.com/wiyoyaweqe/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 11, column 30 thru column 34: End tag ```` br ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Forcing revalidation: https://output.jsbin.com/lecosohuxa

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/lecosohuxa/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 14, column 1: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
(That container rule isn't necessarily applicable to v4)

**Comment by Deilv** [comment]
Try to wrap the navbar and the collapsible inside a <div class="navbar-fixed-top"> </div>.
The collapsible element is positioned relative to its parent, but in the provided documentation it does not have a parent. The problem would be more obvious if you were using a navbar-fixed-bottom, because the collapsible element would make its appearance at the top! 

In this codepen you can see both fixed-top and fixed-bottom navbars working properly, just by moving the navbar-fixed-top and navbar-fixed-bottom to a wrapping container div:
http://codepen.io/anon/pen/gaVOYy

As for the issue itself, I believe it's a problem in the documentation. AFAIK there is no other way to position the collapsible element relative to the navbar without using a container.

@cvrebert is someone working actively on the navbars, or should we change the documentation and close this issue?

**Comment by twbs-lmvtfy** [comment]
Hi @Deilv!

You appear to have posted a live example (http://codepen.io/anon/pen/gaVOYy.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 6: Stray start tag ```` html ````.
* line 10, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 46, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Deilv** [comment]
twbs-lmvtfy scared the hell of out me! (codepen fixed - hopefully)

**Comment by cvrebert** [comment]
Navbars are on @mdo's todo list.

**Comment by xc4patryk** [comment]
@Deilv yea, its working , but site content It stands on the site and becomes invisible. I think, that collapse should move the contents to the bottom.

**Comment by Deilv** [comment]
@xc4patryk that does not make sense!

navbar-fixed-top makes you navigation bar float and stick to the top of the page. When you scroll down the rest of the content, your navigation will stay visible, but will hide whatever goes underneath. I can't even imagine how else it could be.

If you just want a full width navigation bar, then you don't need the navbar-fixed-top class. In that case your expanding navbar will push your content downwards, but will also scroll along with the rest of the content.

**Comment by xc4patryk** [comment]
I Understand. You added class fixed to collapse - It's wrong, however....
I can handle it, but I thought it was a aesthetic standard in bootstrap, so I reported it.

**Comment by mdo** [comment]
Can't load any of those JS Bin links, and our navbars need reworking, so closing out for now since I know the collapsing is fine with the right markup right now.

**Comment by cvrebert** [comment]
> Can't load any of those JS Bin links

JS Bin is currently down: http://status.jsbin.com/incidents/pdcc2s17d8wk
