### ISSUE TITLE
JSPM not pulling down css folder for 3.3.6 release

### ISSUE THREAD

**Issue by briannoyes** [twbs/bootstrap#18360]
Repro:
Create a new folder, switch to that folder
jspm install bootstrap

It pulls down the rest of the dist files and folders, but css folder is missing

**Comment by onlyplo** [comment]
This unfortunately effects v3.3.5 as well now.

**Comment by cpritchard** [comment]
Also chiming in that this has broken 3.3.5 took a while to figure out why an automated build server was puking on bootstrap files.

**Comment by kkirsche** [comment]
Is this due to changes to the bower file?

**Comment by cpritchard** [comment]
After raising this issue as a JSPM bug he was quite quick to push out a fix. This is now working on my local machine and an automated build server.

**Comment by briannoyes** [comment]
Yup, works fine for me as well. Thanks for the quick fix!
