### ISSUE TITLE
tab shown event not fired when tab is in a modal

### ISSUE THREAD

**Issue by dgobaud** [twbs/bootstrap#18364]
shown.bs.tab does not seem to be fired on tabs that are in a modal

**Comment by cvrebert** [comment]
@dgobaud Per [the bug report guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), please post a JS Bin or JSFiddle that demonstrates the problem.

**Comment by dgobaud** [comment]
https://jsfiddle.net/dgobaud/naLgkv04/2/

Click show, modal pops up, change to Settings tab then back to Map tab - no tab shown event even though


```$('a[data-toggle="tab"]').closest('[name="truckMap"]').on('shown.bs.tab',
      function() { alert("HI!"); }
    )```

**Comment by twbs-lmvtfy** [comment]
Hi @dgobaud!

You appear to have posted a live example (https://fiddle.jshell.net/dgobaud/naLgkv04/2/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 35, column 3 thru column 86: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dgobaud** [comment]
fixed https://jsfiddle.net/dgobaud/naLgkv04/3/

**Comment by twbs-lmvtfy** [comment]
Hi @dgobaud!

You appear to have posted a live example (https://fiddle.jshell.net/dgobaud/naLgkv04/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 39, column 3: [E046](https://github.com/twbs/bootlint/wiki/E046): `.modal` elements must have a `tabindex` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dgobaud** [comment]
https://jsfiddle.net/dgobaud/naLgkv04/4/ fixed

**Comment by webvitaly** [comment]
This @twbs-lmvtfy validator bot is pretty good :)

**Comment by cvrebert** [comment]
There is no element in your HTML with `name="truckMap"`.

**Comment by dgobaud** [comment]
Thanks! Turns out that was the problem in the fiddle but not my real problem. My problem was more subtle but its fixed now. Was delay loading HTML and injecting it into a div. Problem had something to do with loading all the css/javascript twice.
