### ISSUE TITLE
I want add language for bootstrap documentation

### ISSUE THREAD

**Issue by rameezsoomro** [twbs/bootstrap#18367]
Sorry this is not a issue because I don't have idea where can I ask how to contribute language in bootstrap documentation.

**Comment by cvrebert** [comment]
We don't host, organize, or assist with translations; we merely link to translations that others have done.
If you finish a translation and host it somewhere, feel free to then send a pull request to add it to https://github.com/twbs/bootstrap/blob/master/docs/_data/translations.yml which is what the translation list in our docs is generated from.

**Comment by rameezsoomro** [comment]
Bow can I contribute/translate the language?
>>Should I download the whole bootstrap project and then change language of each file?
OR
>>Language file defined in project and I can change the text from language file?
OR
Something else ?

**Comment by cvrebert** [comment]
> How can I contribute/translate the language?

It doesn't particularly matter to us, since we'd merely link to your translation's website. Other than adding the link, no git merge would take place. The actual translated text is never merged upstream.

> Should I download the whole bootstrap project and then change language of each file?

That's a perfectly fine method.

> OR
> Language file defined in project and I can change the text from language file?

I have no idea what you mean here.
