### ISSUE TITLE
[v4-alpha] Remove (ul) from dropdown-menu sass comment (_dropdown.scss: line 27)

### ISSUE THREAD

**Issue by beau-gosse** [twbs/bootstrap#18363]
For consistency sake, the comment on [line 27](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_dropdown.scss#L37) in `_dropdown.scss` should be updated to reflect the fact that `.dropdown-menu` now targets more than just the `<ul>` element. The comment line currently reads: `// The dropdown menu (ul)`. It Should have a more generic title like this `// The dropdown menu`. This works too: `// The dropdown menu (div)`.

**Comment by cvrebert** [comment]
Fixed in a23cf74340ef11ed7de81c2e105062b1e7f511e7. Thanks.

**Comment by beau-gosse** [comment]
@cvrebert  thanks for the quick follow-up.
