### ISSUE TITLE
Errors in Modal._setScrollbar()

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18373]
See https://github.com/twbs/bootstrap/issues/18366#issuecomment-160357727

**Comment by Deilv** [comment]
@cvrebert you can mark this as confirmed, there is indeed a bug in [Modal._setScrollbar](https://github.com/twbs/bootstrap/blob/a23cf74340ef11ed7de81c2e105062b1e7f511e7/js/src/modal.js#L420).

Line 430 should be:
```javascript
`${this._originalBodyPadding + this._scrollbarWidth}px`
```

Already tested this and the fix works as intended, however, the fixed navbar still scrolls to the left. I can only assume that the first part of the function was about to fix the navbar padding, but then something went wrong along the way. I'm still working on it.

**Comment by Deilv** [comment]
I believe I have a rather complete fix for both the body and fixed-navbar scrolling related to the modal. Please check this codepen to see if it works well for you (already tested on FF, Edge and IE11). PR coming soon.

**Comment by Deilv** [comment]
Made further changes to the code to address all possible scenarios I could think of. Now it supports pre-existing % based padding and also adjusts/restores all fixed content on the page.

You can check the updated version of the codepen posted above. I'll run some more tests to see all is ok before I send a pull request.
