### ISSUE TITLE
Respect $enable-rounded in mixins _border-radius.scss

### ISSUE THREAD

**Issue by MHobijnCgmNl** [twbs/bootstrap#18385]
The mixin border-radius (in _mixins.scss) checks $enable-rounded. But the mixins in _border-radius.scss do not. Please add the check, so setting $enable-rounded can block all roundings.

**Comment by cvrebert** [comment]
As of the current [v4-dev](https://github.com/twbs/bootstrap/tree/v4-dev) branch, unless I'm missing something, there is no such mixin in [`_mixins.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_mixins.scss) and all the mixins in [`_border-radius.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_border-radius.scss) respect `$enable-rounded`.
Given that v4 is currently in a phase of intensive development (hence why it's in Alpha), please check the bleeding-edge [v4-dev](https://github.com/twbs/bootstrap/tree/v4-dev) code before filing bugs in the future. Thanks!

**Comment by MHobijnCgmNl** [comment]
Dear Chris,
Sorry  for the trouble. I use the code downloaded from ‘git://github.com/twbs/bootstrap.git#v4.0.0-alpha’.
I expected that to be the newest.

I will check the real code next time I have an ‘issue’.

Met vriendelijke groet,
With kind regards


Mathijs Hobijn
Software Developer
[cid:image001.png@01CEFFCC.1267D910]
CompuGroup Medical Nederland B.V.
Hoogoorddreef 15
1101 BA  Amsterdam Zuidoost
The Netherlands

T  +31 (0) 88 387 63 32

mathijs.hobijn@cgm.com<mailto:mathijs.hobijn@cgm.com>
www.cgmnederland.nl<http://www.cgmnederland.nl/>

[cid:image008.png@01D0BFCD.D901A930]Before printing, think about the environment.

DISCLAIMER: This e-mail contains information which may be legally privileged. It is intended to be read by the addressee only. If this e-mail has been misdirected, please notify the author by replying to this e-mail. If you are not the intended recipient, you must not use, distribute, copy, print or rely on this e-mail and all copies should be deleted. This e-mail does not constitute a legally binding document.

Van: Chris Rebert [mailto:notifications@github.com]
Verzonden: maandag 30 november 2015 9:34
Aan: twbs/bootstrap
CC: Hobijn, Mathijs
Onderwerp: Re: [bootstrap] Respect $enable-rounded in mixins _border-radius.scss (#18385)


As of the current v4-dev<https://github.com/twbs/bootstrap/tree/v4-dev> branch, unless I'm missing something, there is no such mixin in _mixins.scss<https://github.com/twbs/bootstrap/blob/v4-dev/scss/_mixins.scss> and all the mixins in _border-radius.scss<https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_border-radius.scss> respect $enable-rounded.
Given that v4 is currently in a phase of intensive development (hence why it's in Alpha), please check the bleeding-edge v4-dev<https://github.com/twbs/bootstrap/tree/v4-dev> code before filing bugs in the future. Thanks!

**Comment by AndersSahlin** [comment]
I think this issue is still present, somewhat.

`.modal-content` has rounded borders even if they have been disabled with the setting. Probably because it uses `$border-radius-lg` instead of the mixin.

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L52
