### ISSUE TITLE
Collapse Problem with Responsive

### ISSUE THREAD

**Issue by xc4patryk** [twbs/bootstrap#18386]
Hello,

Whether Bootstrap allows hide class "in" when use mobile scale ? - I Want hide Collapse panel for mobile.

or Do I need to write my own solution?

**Comment by cvrebert** [comment]
There is currently no "collapse this Collapsible by default on smaller viewports" feature.

**Comment by mdo** [comment]
No plans to add additional specific collapsing features, so you'll need to write your own extension.
