### ISSUE TITLE
Does Bootstrap 4 uses the same grid classes as Bootstrap 3 ?

### ISSUE THREAD

**Issue by darol100** [twbs/bootstrap#18399]
Does Bootstrap 4 uses the same grid classes as Bootstrap 3 ?  Meaning that I should be able to change to B4 and my code still will be responsive if using B3.

**Comment by webvitaly** [comment]
Hi @darol100 

As far as I know Bootstrap3 uses: -xs- [768px] -sm- [992px] -md- [1200px] -lg-

And Bootstrap4 uses: -xs- [544px] -sm- [768px] -md- [992px] -lg- [1200px] -xl-
Or same but in ems: -xs- [34em] -sm- [48em] -md- [62em] -lg- [75em] -xl-

Note that Bootstrap4 adds new breakpoint -xl- and shift all other breakpoints by adding 544px screen size.

**Comment by darol100** [comment]
@webvitaly interesting.....

**Comment by cvrebert** [comment]
As of bleeding edge v4, the grid uses px instead of em.
