### ISSUE TITLE
Consider renaming .radio and .checkbox

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18390]
Perhaps to something like `.radio-block`, `.checkbox-block`?
Given Bootstrap's general CSS class naming scheme, the current names (`.radio`, `.checkbox`) could be misinterpreted as base classes for which the `.radio-inline`, `.checkbox-inline` would be modifier classes; but that's not how they work (`.radio.radio-inline` isn't currently a sensical combination).

**Comment by guylepage3** [comment]
+1 Makes sense.

**Comment by halfmage** [comment]
`.radio` is block by default; I think `.radio-block` would be unnecessary. But `.radio-inline` should have the same behavior like `.radio` except the display method (like you mentioned).

**Comment by mdo** [comment]
Coming in #19141.
