### ISSUE TITLE
<span> with visible-print is displayed as block, not inline (on print)

### ISSUE THREAD

**Issue by EquisTango** [twbs/bootstrap#18405]
When I use the following HTML:

<pre>
This is a text &lt;span class="visible-print"&gt;only for print&lt;/span&gt;
</pre>

The output for print is:

This is a text
only for print

The &lt;span&gt; is displayed as a block and not inline. Tested with version 3.3.6 with Firefox 42 on Linux.

**Comment by cvrebert** [comment]
As stated in the docs, `.visible-print` is deprecated. In your case, you want `.visible-print-inline` instead.
