### ISSUE TITLE
Not able to use 3 modal in a single page

### ISSUE THREAD

**Issue by soorajbala** [twbs/bootstrap#18403]
Third popup is not visible
<a href="#" class="btn btn-default pull-right" type="button"  data-toggle="modal" data-target=".bs-example-modal-sm">one</a>

 <a href="#" class="blue-bg" type="button"  data-toggle="modal" data-target=".bs-example-modal-lg">Two</a>
          <a href="#" class="blue-bg" data-toggle="modal" data-target="#squarespaceModal" class="btn btn-primary center-block">Three</a>

**Comment by MrGeneric** [comment]
Your links all point to this issue!

**Comment by soorajbala** [comment]
no i want one modal at a time :)

**Comment by patrickhlauke** [comment]
please create a reduced testcase in jsfiddle.net or similar, so we can actually see the problem.

**Comment by cvrebert** [comment]
Please use StackOverflow, IRC, or Slack for troubleshooting questions; see https://github.com/twbs/bootstrap/blob/master/README.md#community for links.
If you're alleging a bug, there are specific requirements for bug reports; see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by tsquinn** [comment]
What's the answer to this question? I'm having the same problem.
