### ISSUE TITLE
.form-inline with .input-group has wrong positioning when flexbox is enabled

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#18406]
sample code

```
<body>
  <form class="form-inline">
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1">@</span>
        <input type="text" class="form-control" placeholder="Username">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-btn">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
            Action
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
          </div>
        </div>
        <input type="text" class="form-control" aria-label="Text input with dropdown button">
      </div>
      <button type="submit" class="btn btn-primary">Send invitation</button>
    </div>
  </form>
</body>
```

screenshoot

![form-inline-input-group](https://cloud.githubusercontent.com/assets/6099236/11533508/647f6644-990a-11e5-84b4-982c564da4a4.png)

If flex is disabled everything looks correct.

**Comment by cvrebert** [comment]
Could you repost your example as a JS Bin or JSFiddle?

**Comment by wojtask9** [comment]
Sorry my mistake

In both cases bootstrap was build from 8a1685fdee8f01f041184948cf20dede54a2f4b3 (v4-dev branch)

http://jsfiddle.net/78LfL3gg/      ----> bug and flex enabled
http://jsfiddle.net/2032j74L/      ----> correct (without flex enabled)

**Comment by twbs-lmvtfy** [comment]
Hi @wojtask9!

You appear to have posted a live example (http://fiddle.jshell.net/78LfL3gg/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 60, column 3 thru column 17: Stray doctype.
* line 61, column 1 thru column 16: Stray start tag ```` html ````.
* line 62, column 3 thru column 8: Stray start tag ```` head ````.
* line 63, column 5 thru column 25: A ```` charset ```` attribute on a ```` meta ```` element found after the first 512 bytes.
* line 63, column 5 thru column 26: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 63, column 5 thru column 26: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 64, column 5 thru column 57: Attribute ```` http-equiv ```` not allowed on element ```` meta ```` at this point.
* line 64, column 5 thru column 57: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 65, column 5 thru column 90: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 65, column 5 thru column 90: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 67, column 5 thru column 11: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 68, column 3 thru column 9: Stray end tag ```` head ````.
* line 70, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 96, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @wojtask9!

You appear to have posted a live example (http://fiddle.jshell.net/2032j74L/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 58, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 84, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by wojtask9** [comment]
http://jsfiddle.net/2032j74L/1/  ----> correct (without flex enabled)
http://jsfiddle.net/78LfL3gg/1/  ----> bug (flex enabled)

**Comment by schalk-b** [comment]
I have just had the same issue.

The issue is in _forms.scss where there are a bunch of display: inline-block. I have added similar to the following in a few places which fixed the issue:

@if $enable-flex {
		display: flex;
	  } @else {
		display: inline-block;
	  }

**Comment by aeksco** [comment]
I'm seeing the same issue as well - adding ```display:table-cell``` to ```.input-group-addon``` solves for me:

```jade
form.form-inline
  .form-group
    .input-group
      input.form-control(type='text', placeholder='Amount')
      .input-group-addon( style='display:table-cell;' ) .00
```

That being said it would seem that using CSS tables with Flexbox enabled is missing the point.

**Comment by hokiecoder** [comment]
I believe the needed code changes are as such:

In [_forms.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L322), starting at line 322:
```scss
.input-group {
  display: inline-table;
  vertical-align: middle;
```

...change to:
```scss
.input-group {
  @if $enable-flex {
    align-items: stretch;
    display: flex;
  } @else {
    display: inline-table;
    vertical-align: middle;
  }
```

In [_input-group.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_input-group.scss#L40), starting at line 40:
```scss
.input-group-addon,
.input-group-btn,
.input-group .form-control {
  @if not $enable-flex {
    display: table-cell;
  }
```

...change to:
```scss
.input-group-addon,
.input-group-btn,
.input-group .form-control {
  @if $enable-flex {
    align-items: center;
    display: flex;
  } @else {
    display: table-cell;
  }
```

These changes, at least in my limited testing, allow the input groups in an inline form to fall inline as well as be vertically centered.

**Comment by jocooler** [comment]
I added these rules to by stylesheet and things seem to be largely resolved:

```
      .form-inline, .form-inline * {
        display: -webkit-box !important;
        display: -webkit-flex !important;
        display: -ms-flexbox !important;
        display:flex !important;
      }
      
      .form-inline .form-control, 
      .form-inline .input-group, 
      .form-inline .btn, 
      .form-inline .custom-select  {
        margin-right:5px;
        margin-bottom: 5px;
      }
      
      .form-inline .input-group * {
        margin-right:0 !important;
        margin-bottom:0 !important;
      }
```

**Comment by AJamal79** [comment]
use flex-nowrap with input-group
