### ISSUE TITLE
Is it possible to make modals simpler?

### ISSUE THREAD

**Issue by camohub** [twbs/bootstrap#18408]
Hello,
I am playing with modal dialogs and I wold like to know if is necessary to have block with role="document" there. Block has only few properties like margin, transform, position, width ... which could be placed to the "content" block. 
I would like to have only 2 necessary blocks  1. role="dialog" and 2. class="modal-content" instead of 3 blocks. Block role="document" could be removed. Couldn't be?

Is document block necessary there? May be I am wrong. May be because of back compatibility it wont be possible to change it. Thanks.

**Comment by kkirsche** [comment]
This is necessary for excess ability reasons which are outlined in version three of bootstraps documentation

**Comment by kkirsche** [comment]
Though potential he that is something worth reconsidering Per https://accessibility.oit.ncsu.edu/training/aria/modal-window/version-3/ cc: @patrickhlauke

**Comment by camohub** [comment]
There is it: 
8. Note, there used to be a role="document" which wrapped all of the contents of the modal window. This was only necessary because NVDA previously did not allow you to fully browse all of the contents of the modal window. NVDA now allows full browsing of the contents so this is not needed anymore.

**Comment by kkirsche** [comment]
Any progress on identifying if this is possible or not?

**Comment by mdo** [comment]
Punting on any changes to the modal here in lieu of any further information being provided.
