### ISSUE TITLE
Add JS to calculate arbitrary responsive embed aspect ratios

### ISSUE THREAD

**Issue by lifecom** [twbs/bootstrap#18404]
Why do we use the only 16by9 and 4by3?
It is possible to use a height (calculate padding-bottom for .embed-resposive with js), based on params  of the source (e.g. iframe height="xx") if params is specified?

**Comment by cvrebert** [comment]
> Why do we use the only 16by9 and 4by3?

Actually there's also [21by9 and 1by1 now](https://github.com/twbs/bootstrap/blob/78eafb8d068f5d4ec0f8560ee017a2c9c9e503a0/scss/_responsive-embed.scss#L25-L39).
Why these specific ratios? Well, 1by1 is square, and the others are common aspect ratios for video and photo content; see https://en.wikipedia.org/wiki/Aspect_ratio_(image)

> It is possible to use a height (calculate padding-bottom for .embed-resposive with js), based on params of the source (e.g. iframe height="xx") if params is specified?

What's your specific use case?

**Comment by lifecom** [comment]
> What's your specific use case?

E.g. codepen embed iframe ([example](http://frontender.info/centering-css-complete-guide/)).
It's not a video or image, but iframe.
Most embed-api for iframe contain width and height params (incl. youtube. vimeo, etc.)
With width all clear: we use 100%. But height may be excessive.
And we can use this value, if it specified, for calculate padding-bottom via js.

All the more so actually we can use only one aspect ratio (except some modifications).
For example, I use the wrap and add appropriate classes to the frame via js.

**Comment by lifecom** [comment]
Ie, using the width and height from iframe params (if it specified), we can calculate aspect ratio and set appropriate value for .embed-resposive padding-bottom.

This allows set the correct aspect ratio dynamically based on content, rather than a fixed aspect ratio.

**Comment by peiche** [comment]
Why not provide an option via preprocessor? I'm using this mixin in a Sass project:

````
@mixin aspect-ratio($width, $height) {
	padding-top: ($height / $width) * 100%;
}
````

It's called from within a class, like so:

````
.embed-responsive-3by4 {
	@include aspect-ratio(3, 4);
}
````

And the corresponding markup uses it just like Bootstrap's prebuilt ones:

````
<div class="embed-responsive embed-responsive-3by4">
  <iframe></iframe>
</div>
```

**Comment by lifecom** [comment]
> Why not provide an option via preprocessor?

The outcome of this solution (involving two values) will be again an **fixed** ratio.
My proposal is substitute $height and $width values from iframe params (for calculate real ratio) via js.

**Comment by mdo** [comment]
No plans to add any JS to tackle this in v4.
