### ISSUE TITLE
Accordion's "at most 1 open item" invariant gets violated after using JS API

### ISSUE THREAD

**Issue by skateman** [twbs/bootstrap#18418]
Hello!

When you try to collapse/expand accordions with JS, reopening the collapsed accordion by clicking causes expanding both accordions.

See http://getbootstrap.com/javascript/#collapse-example-accordion

![animated](https://cloud.githubusercontent.com/assets/649130/11565051/8ac7a01e-99dc-11e5-9732-048bf279e9db.gif)

Originally posted to: https://github.com/patternfly/patternfly/issues/162

**Comment by cvrebert** [comment]
Collapse's `toggle`, `show`, and `hide` methods are asynchronous. It's not valid to call them twice sequentially like that. You need to wait for the `hidden.bs.collapse` event before making subsequent calls.

**Comment by Johann-S** [comment]
This PR would be usefull https://github.com/twbs/bootstrap/pull/17823 :smile:

**Comment by cvrebert** [comment]
Indeed! I do intend to get around to that PR, I just have a lot of things on my TODO list.

**Comment by Johann-S** [comment]
Haha it's ok good luck for your TODO list :wink:

**Comment by skateman** [comment]
Same happens when I call it like this: 
```javascript
$("#collapseOne").one('hidden.bs.collapse', function () {
  $("#collapseTwo").collapse('show');
});
$("#collapseOne").collapse('hide');
```
But even if I wait between typing in the two collapse calls.

**Comment by cvrebert** [comment]
Perhaps this is related to #17335.

**Comment by cvrebert** [comment]
This also prompts the question of whether this can be fixed in v3 given that some folks might be relying on the "broken" behavior.

**Comment by Johann-S** [comment]
IMO we should add ``data-parent`` in the collapse element because we allow user to toggle collapse element without passing by the ``<a>`` which contain the ``data-parent`` attribut. 
That's why the collapse behavior is strange because they are no parent

**Comment by vanduynslagerp** [comment]
X-ref #18418
