### ISSUE TITLE
Media queries aren't precise enough with 0.1rem difference

### ISSUE THREAD

**Issue by sergej2705** [twbs/bootstrap#18414]
The media queries aren't precise enough with 0.1rem difference, e.g.:

we have the breakpoint `md: 48em`

    @media (max-width: 47.9em) {   // this is 766,4px => 766px
        ...
    }
    @media (min-width: 48em) {     // this is 768px
        ...
    }

Now if we have a viewport of `767px`-width this can lead to display-issues:

Example:

    <div class="hidden-sm-down">
        Content for bigger screens!
    </div>
    <div class="hidden-md-up">
         Content for smaller screens!
    </div>

On `767px`-width both `div`s show up, you can see it on https://jsfiddle.net/5ba6aton/ if you resize the output-window.

**Comment by cvrebert** [comment]
The bleeding-edge `v4-dev` code doesn't use `em`s in the media queries anymore. See #17403. Please search more next time! Thanks.
