### ISSUE TITLE
Не работает collapse accordion

### ISSUE THREAD

**Issue by andrey59** [twbs/bootstrap#18412]
На официальном сайте http://getbootstrap.com он работает , у вас прописан другой код. Поискал в интернете почему не работает. Оказалось что bootstrap-collapse.js и bootstrap-transition.js надо отдельно подключать , как у вас на сайте и подключёно. Для чего сделано так непонятно, только вводите народ в заблуждение

**Comment by cvrebert** [comment]
Google Translate: Извините, но мы не в состоянии оказывать помощь на русском языке. Ни один из нас не говорит по-русски.

Original English: Sorry, but we are unable to provide assistance in Russian. None of us speak Russian.

**Comment by andrey59** [comment]
So , who is made site  http://bootstrap-ru.com/ ? It is made in Russian language and collapse accordion not work, but code  with site  http://getbootstrap.com/  work fine.

**Comment by cvrebert** [comment]
According to the footer at the bottom of http://bootstrap-ru.com/ :
> Переведено [@VeliovGroup](https://twitter.com/VeliovGroup) в VeliovGroup.com
> Dmitriy A.: [@smart_egg](https://twitter.com/smart_egg) - О Авторе, ceo(AT)veliovgroup.com
> Translated in [@VeliovGroup](https://twitter.com/VeliovGroup), web: VeliovGroup.com
> By Dmitriy A.: [@smart_egg](https://twitter.com/smart_egg) - About author, ceo(AT)veliovgroup.com

**Comment by mrmlnc** [comment]
@andrey59 указанный вами сайт разработан энтузиастами. На этом сайте указана версия Bootstrap 2.3.2, которая уже устарела и больше не поддерживается.

**Comment by cvrebert** [comment]
To further clarify:
Neither Dmitriy nor VeliovGroup nor http://bootstrap-ru.com are officially affiliated with or endorsed by the Bootstrap project.
So http://bootstrap-ru.com/ is completely **unofficial**.
