### ISSUE TITLE
include a table sorter by default

### ISSUE THREAD

**Issue by daniel-baumann** [twbs/bootstrap#18419]
Hi,

it would be nice if bootstrap would include a table sorter by default.

It doesn't need to be as elaborate like https://mottie.github.io/tablesorter/, something simple out-of-the-box like e.g. http://joequery.github.io/Stupid-Table-Plugin/ would be just enough.

Regards,
Daniel

**Comment by cvrebert** [comment]
As mentioned in #13804, we're open to considering pull requests which add CSS that would be useful for table sorting libraries.
But as stated in https://github.com/twbs/bootstrap/issues/13804#issuecomment-47416525 , we're not particularly interested in adding JavaScript for such a potentially-complicated feature. Among other reasons, the Core Team currently lacks sufficient JavaScript manpower to take on the maintenance of another potentially-complicated jQuery plugin.
