### ISSUE TITLE
Button sizing with <strong> label and 14/15px root font size

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#18429]
When having a root font size of 14 or 15 pixels, when a `<strong>label</strong>` is used inside a button text, that button won't scale correctly. E.g.
```html
<div class="btn-group">
  <button type="button" class="btn btn-warning">Test of <strong>strong</strong> label</button>
  <button type="button" class="btn btn-warning dropdown-toggle"></button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Foo</a>
  </div>
</div>
```
Produces:
![screen shot 2015-12-04 at 13 10 08](https://cloud.githubusercontent.com/assets/851745/11589350/1f20fa34-9a88-11e5-8c6c-9528973a4bb2.png)

This is strange, since it happens only with 14 or 15 pixels root font size, when with 13 pixels it scales correctly again.

Fiddle: http://jsfiddle.net/heruan/qnarqu8p/

**Comment by kkirsche** [comment]
@heruan it's because of the weight of the strong text. Just putting `<strong>&nbsp;</strong` inside of your `.dropdown-toggle` fixes the scaling though I agree that's not the ideal solution by any means.

**Comment by heruan** [comment]
Thank you @kkirsche, I wonder why it doesn't happen with a root font size of 13 or 16 pixels. If the weight of strong text matters, I would expect the same behaviour with any font size.

**Comment by mdo** [comment]
This is an age old problem with the weights. I don't have a good answer or fix for you though :\. Could be related to our font stack but I feel like if that were the case universally we'd have more reported issues.

**Comment by mdo** [comment]
Punting on this. Latest native font stack might help a bit since this is a pretty big problem with Helvetica Neue in particular.
