### ISSUE TITLE
_input-group.scss & _button-group.scss still assume 1px borders

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18425]
Refs https://github.com/twbs/bootstrap/pull/18417#issuecomment-161856850
X-Ref: #18150
Though these files no longer hardcode any `border-width` property values, there are some hardcoded `-1px` margins which were meant to counteract the border widths.

**Comment by mdo** [comment]
Fixed by #18427.

**Comment by cvrebert** [comment]
No, still broken for input groups.

**Comment by cvrebert** [comment]
X-Ref: #18424

**Comment by mdo** [comment]
Ah, my bad. Tweaked some things in 49674a8. Unsure about making the variables the same just yet though, but that's probably what will need to happen.

**Comment by cvrebert** [comment]
Cool. #18424 covers the remaining variable issue.
