### ISSUE TITLE
Validation feedback icon is hidden while <input> in input group is focused

### ISSUE THREAD

**Issue by thekondrashov** [twbs/bootstrap#18449]
I'm not sure this is normal behavior or this is a bug, but in the official docs in chapter "[Validation states](http://getbootstrap.com/css/#forms-control-validation)" &rarr; "With optional icons" try to check any "Input group with success" example.
The problem:
- when `<input>` element get focus, feedback icon is hidden.
- when `<input>` element lost focus, feedback icon is shown again.
- in other examples (wthout input group) feedback icon is always visible regardless of focus

This affected only on bootstrap v3 (no impact on v4) only on [input groups](http://getbootstrap.com/components/#input-groups) (with an `.input-group-addon` or `.input-group-btn`) in latest Chrome, Firefox (other browsers not tested).
This can be important, for example if using a live validation as you type with javascript when `<input>` is constantly in focus. In this case, the feedback icon element is not able to indicate of validation state via icon.
See [/less/forms.less](https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/forms.less#L404):
```less
// Feedback icon (requires .glyphicon classes)
.form-control-feedback {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 2; // Ensure icon is above input groups
  ...
```
If you increase the z-index to 3, it will be fixed.
P.S.: There are no similar examples of input groups with feedback icons in the [v4 docs ](http://v4-alpha.getbootstrap.com/components/forms/#validation). I'm confused!

**Comment by vincentwinkel** [comment]
Thanks for this topic. I found the same issue on my project, with feedback icons but also with this plugin:
http://labs.abeautifulsite.net/jquery-minicolors/
which stops to work well after Bootstrap updating.
Thanks too for the z-index 3 temporary solution until v3.3.7, it works fine :)

**Comment by Lausselloic** [comment]
Hello,
Can be fixed properly into input-groups.less line 33 : 
&:focus {      
      &,
      + .form-control-feedback{
        z-index: 3;
      }
    }
Instead of : 
&:focus {
      z-index: 3;
    }

Loïc

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
