### ISSUE TITLE
Dropdown's arrow key handler runs global DOM query?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18454]
It seems rather odd that we're selecting all the dropdown items in the entire document in https://github.com/twbs/bootstrap/blob/2f176821c3c5439f83a5df4a176534d724e716b9/js/src/dropdown.js#L233
Surely we should be limiting the query to the descendants of the relevant dropdown menu? It seems rather unnecessarily wasteful otherwise.

**Comment by mdo** [comment]
Merged #19953, so closing.
