### ISSUE TITLE
img-responsive i missing

### ISSUE THREAD

**Issue by indymx** [twbs/bootstrap#18456]
just pulled all of the latest commits, img-responsive is now missing from v4-dev branch

**Comment by kkirsche** [comment]
X-Ref: #17168

**Comment by indymx** [comment]
That didn't turn up in my search on github, but I found it after opening
the image.scss file and poking around..

**Comment by indymx** [comment]
at certain break points I'm getting odd behavior, that I didn't see in v3
or even v4 with img-responsive.

   <div class="col-xs-12 col-sm-6 col-lg-4">
            <div class="card">
  <img class="card-img-top img-fluid" src="images/photos/bj1.jpg" alt=" ">
<div class="card-header black-text">The Race:</div>
<div class="card-block">
                    <p>A speedway "meeting" consists of four heats and a
main event. Each rider will ride in four heats, starting each one from a
different spot or "gate" on the starting line. The four riders with the
most points after four heats go on to the main event. All heats and mains
are four laps and the fast guys can run their four laps in less than 50
seconds.</p>
                </div>
            </div>
        </div>

[image: ScreenShot029.jpg]
