### ISSUE TITLE
Bootstrap release date

### ISSUE THREAD

**Issue by vaibhavshettar5** [twbs/bootstrap#18457]
i am excited to see bootstrap 4 from u guys.

**Comment by kkirsche** [comment]
Release date is to still TBD based on the release cycle described here: http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by vaibhavshettar5** [comment]
oh thanks

**Comment by cvrebert** [comment]
http://blog.getbootstrap.com/2015/12/08/bootstrap-4-alpha-2/
