### ISSUE TITLE
v4: Type

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#18470]
Meta tracking issue for some typography stuff.

- ~~#17969: Clearfix on dl-horizontal?~~
- [x] #18090: Nuke .dl-horizontal for a row and other classes?
- ~~#18429: font-weight and computed height in button groups?~~
- ~~#17580: Centering non-block elements (e.g. tables) with utils?~~

**Comment by bassjobsen** [comment]
https://github.com/twbs/bootstrap/pull/18669 should close this?

**Comment by mdo** [comment]
Closed all these with no major changes to any of them.

**Comment by cvrebert** [comment]
@mdo Erm, #17969 & #17580 are still open...
