### ISSUE TITLE
v4: Add a dropdown-menu-reverse class

### ISSUE THREAD

**Issue by iDev0urer** [twbs/bootstrap#18482]
It would be nice to have a class `dropdown-menu-reverse` that would reverse the X direction of a dropdown menu. 

![dropdown-reverse](https://cloud.githubusercontent.com/assets/4535422/11664748/a5e3269e-9da0-11e5-9ee9-cea359ac7cbc.png)

Doing this would be as simple as adding a class:
```
.dropdown-menu-reverse {
    left: initial;
    right: 0;
}
```

**Comment by cvrebert** [comment]
I feel like we have a class for this, but hard to check since I'm on a phone right now.

**Comment by cvrebert** [comment]
Yup: http://v4-alpha.getbootstrap.com/components/dropdowns/#alignment

**Comment by iDev0urer** [comment]
Would you look at that. Good job guys!
