### ISSUE TITLE
Add .h1 – .h6 example to docs

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18492]
Refs #18491, http://v4-alpha.getbootstrap.com/content/typography/#headings

**Comment by patrickhlauke** [comment]
related to this advice

> for when you want to match the font styling of a heading but still want your text to be displayed inline

though, I'm not particularly thrilled about the supposed rationale. If something's semantically a heading, it should always use `<h1>` through `<h6>`. If it's only about having it "displayed inline" then it should be a case of still using the correct heading element and adding a `display:inline` style, and not to just use an arbitrary element and slapping a `class="h1"` or similar on it.

maybe the wording just needs to be changed to something more like

> for when you want an arbitrary piece of text to match the font styling of a heading

**Comment by cvrebert** [comment]
Yeah, we could probably stand to tweak that.
The `<h3 class="h4">` use case (i.e. this is logically a level 3 heading in the outline tree, but the normal `<h3>` styling would be insufficiently/excessively prominent) isn't covered by the current rationale either.

> and adding a `display:inline` style

Perhaps that deserves a utility class?

**Comment by patrickhlauke** [comment]
i think (though I'm just going by my own practice, so take with a pinch of salt) that the "i want a heading, but have it shown inline" use case it pretty marginal/edge. also, personally not a fan of classes that only really set a single property, but that's just me.

**Comment by mdo** [comment]
Fixed in b479efb.

Dropped that whole inline business—no idea what that was about. This is just a set of utilities to apply an HTML element's default styles to any other element.
