### ISSUE TITLE
Add .large and .larger typography classes

### ISSUE THREAD

**Issue by ozgureffe** [twbs/bootstrap#18491]
Beside `.small`, it would be nice to have `.large` and `.larger` type classes for quick text emphasizing.

**Comment by cvrebert** [comment]
`.small` is a class-based analog for the `<small>` tag. There's no `<large>` tag (or similar) in HTML.
You could use http://v4-alpha.getbootstrap.com/content/typography/#lead or the `.h1` thru `.h6` classes (http://v4-alpha.getbootstrap.com/content/typography/#headings) instead to achieve something similar to `.large`.

**Comment by mdo** [comment]
Punting on it per @cvrebert's comment.
