### ISSUE TITLE
help-block class is removed

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#18505]
The `.help-block` class is removed.

There is no mention of it in the migration document.

**Comment by fchiumeo** [comment]
Not in migration page but [Help text](http://v4-alpha.getbootstrap.com/components/forms/#help-text)

**Comment by vanillajonathan** [comment]
Pull request sent.

https://github.com/twbs/bootstrap/pull/18509

**Comment by cvrebert** [comment]
Fixed by #18509.
