### ISSUE TITLE
v4 migration guide doesn't mention the removal of the .badge class

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#18506]
The `.badge` class is removed.

There is no mention of this in the migration document.

**Comment by wolfy1339** [comment]
New markup is <code>.label.label-pill.label-{color}</code>

**Comment by vanillajonathan** [comment]
Oh, that is not documented in the migration document.

**Comment by wolfy1339** [comment]
Feel free to make a PR to fix that

**Comment by cvrebert** [comment]
Fixed in ddba80595280740b043606464dc36006f059c28c.
