### ISSUE TITLE
Disabled .close button lacks cursor:not-allowed

### ISSUE THREAD

**Issue by aciccarello** [twbs/bootstrap#18508]
Is there a reason why the cursor style for a disabled close button is not disabled? This seems unintuitive to me and doesn't match the main button style.

See this plunker for a comparison: http://plnkr.co/edit/y870CMpxz8CmEdbpP0bu?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @aciccarello!

You appear to have posted a live example (http://run.plnkr.co/plunks/y870CMpxz8CmEdbpP0bu/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 32, column 7 thru column 12: End tag ```` div ```` seen, but there were open elements.
* line 30, column 64 thru column 69: Unclosed element ```` span ````.
* line 30, column 9 thru column 14: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by aciccarello** [comment]
@twbs-lmvtfy It should be better now :8ball:

**Comment by aciccarello** [comment]
The fix should be on the same plunker. http://plnkr.co/edit/y870CMpxz8CmEdbpP0bu?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @aciccarello!

You appear to have posted a live example (http://run.plnkr.co/plunks/y870CMpxz8CmEdbpP0bu/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by aciccarello** [comment]
I've added that too. http://plnkr.co/edit/y870CMpxz8CmEdbpP0bu?p=preview

**Comment by cvrebert** [comment]
Disabled close buttons aren't styled any differently from non-disabled ones for that matter.
Although perhaps just hiding the close button altogether when it's not applicable might be better UX?

**Comment by kkirsche** [comment]
That would be my thought @cvrebert as why show me a close button I can do nothing with? Just gets my hopes up that I can get rid of the element

**Comment by aciccarello** [comment]
Okay, I wasn't sure if this was by design or not.  If you don't see a problem feel free to close.

**Comment by cvrebert** [comment]
Leaving this open for @mdo to confirm/deny whether this is intentionally by design.

**Comment by mdo** [comment]
Going to leave it as-is, and I'd suggest simply not showing the dismiss icon when there is no possibility of dismissing.
