### ISSUE TITLE
Not all .container widths are divisible by 12

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#18510]
I've been working on a Photoshop starter template for Bootstrap 4 with column guides, and I've noticed  that not all column widths are divisible by twelve, which results in oddly sized column widths.

In alpha 2 this only affects "Large":

`940px - 360px (gutter) / 12 = 48.33333...px`

As a result, some columns are rendered with `48px` width and others with `49px` width. 

This makes working with graphic tools harder and more cumbersome. For example, Photoshop has a "Guide Layout" functionality that would work well *if* columns were evenly sized:

![2015-12-09 17_50_20-untitled-1 100 rgb_8](https://cloud.githubusercontent.com/assets/1199486/11691938/7db7a0d4-9e9d-11e5-9bdf-d65e60f73088.png)

Is there a good reason for this that I am unaware of? I initially assumed this was a trade-off related to using rem, but now that this was ditched, I don't quite understand why the containers are not made so they divide evenly.

PS: I've published my [Photoshop template here](http://hackerthemes.com/blog/bootstrap-4-psd-template/), if you want to take a look. It includes test renderings that I've made in Firefox in order to get the column widths exactly right.

**Comment by bassjobsen** [comment]
see also: http://benstewart.net/2014/06/bootstrap-grid-calculation-explained/ or set the width of your large container to 936px

**Comment by arechsteiner** [comment]
Thanks @bassjobsen. I've looked at the SCSS and I think I understand why it's done with %-values. However:

> or set the width of your large container to 936px 

My point is, why isn't this (or 948px) set by default? I'm convinced that 99% of Bootstrap end-users will not customize Bootstrap through recompilation of the SCSS source, so why not have sane defaults that do not result in half-pixels in the column width?
