### ISSUE TITLE
How to control the input-group-addon span class in bootstrap 3.3.6

### ISSUE THREAD

**Issue by spidy6792** [twbs/bootstrap#18516]
This is my Code written in bootstrap 3.3.6 : 
![untitled](https://cloud.githubusercontent.com/assets/6323685/11707232/7d20a848-9f27-11e5-9aa0-baa5d8896914.png)

output comes as : 
![untitled](https://cloud.githubusercontent.com/assets/6323685/11707183/cb7155b6-9f26-11e5-8e10-2d9bfcfc68ee.png)

Issue : How to change that input-group-addon span class styling so that it gets in perfect shape with the input-group class. Please help me out this.

**Comment by neilhem** [comment]
@spidy6792 what is the purpose of `<label for="sel1">Height:</label>` ?

**Comment by spidy6792** [comment]
@neilhem I want to add a label to the input field because my entire form is built on that. Please provide a solution for that and also tell me your alternative way to achieve what i intend to do.

**Comment by cvrebert** [comment]
Please ask how-to questions on StackOverflow or [other community help forums](https://github.com/twbs/bootstrap/blob/master/README.md#community). This issue tracker is for bug reports and feature requests only. Thanks!

**Comment by abedkanbar** [comment]
@rushabh-wadkar have you found the solution ?
