### ISSUE TITLE
in Smartphone and tablet opera mini browser not supporting Bootstrap

### ISSUE THREAD

**Issue by vaibhavshettar5** [twbs/bootstrap#18528]
i developed one site using` bootstrap but in opera mini its not working correctly. Especially collapsing navbar and carousel not working. So we are  expected fix it in upcoming bootstrap 4.

**Comment by kafeltz** [comment]
is this just a random comment?

**Comment by patrickhlauke** [comment]
As per http://getbootstrap.com/getting-started/#support Opera Mini is not supported, I'm afraid
