### ISSUE TITLE
tabs bug

### ISSUE THREAD

**Issue by maz1989** [twbs/bootstrap#18524]
When I zoom in/out on my browser in chrome at zoom 90% 
underline appear under the select tab as shown below:

![tabs_bug](https://cloud.githubusercontent.com/assets/16080780/11717889/d6001ffa-9f5b-11e5-86d9-007f4bf93a69.PNG)

**Comment by Johann-S** [comment]
See this link please : http://getbootstrap.com/getting-started/#support-browser-zooming
