### ISSUE TITLE
"npm install bootstrap@latest" now installs v4 alpha instead of 3.3.6

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#18520]
With npm, using 

`npm install bootstrap --save` causes `"bootstrap": "~4.0.0-alpha.2"` being installed and added as a dependency to package.json. 

In bower on the other hand, `bower install bootstrap --save` installs and saves the latest stable version (3.3.6), as expected.

**Comment by cvrebert** [comment]
Unable to reproduce.
```
dummy $ npm -v
3.3.12
dummy $ npm install bootstrap
/Users/chris/code/dummy
└── bootstrap@3.3.6 

dummy $
```

**Comment by danielweck** [comment]
I had the same problem (see https://github.com/twbs/bootstrap/issues/18539 )

`npm view bootstrap dist-tags` shows `{ latest: '4.0.0-alpha.2' }`
I'm pretty sure "latest" should reference the stable version `3.x` (Git `master` branch), not `4.x` which is a pre-release (branch `v4-dev`) Don't you think?

That's how other NPM libs do it, e.g. jQuery:
```
$ npm view jquery dist-tags

{ beta: '3.0.0-alpha1',
  latest: '2.1.4',
  old: '1.9.1',
  compat: '1.11.3' }
```

**Comment by danielweck** [comment]
See NPM documentation: https://docs.npmjs.com/cli/dist-tag
"latest" should be used for current `v3` version, "alpha" or "beta" for `v4`

**Comment by cvrebert** [comment]
Wow, the npm docs don't surface this too well. And googling for "npm prerelease" didn't seem to yield anything mentioning dist-tags either.

**Comment by cvrebert** [comment]
@danielweck Still confused why you were getting v4 though. The webpages I had found regarding prereleases claim that `npm install <packagename>` skips prereleases (such as our alphas). Did you use some different installation command?

**Comment by cvrebert** [comment]
The dist-tags should be sorted out now:
```
$ npm view bootstrap dist-tags
{ latest: '3.3.6', next: '4.0.0-alpha.2' }
```

**Comment by danielweck** [comment]
@cvrebert I am not sure about the original issue committer ( @arechsteiner ), but personally I was using `npm install bootstrap@latest` which explains why `v4` was pulled instead of `v3`. Thanks for fixing the `dist-tags` :)

**Comment by arechsteiner** [comment]
@danielweck: I have used `npm install bootstrap`, without the @latest.

@cvrebert: This works now, and `npm view dist-tags bootstrap` shows `{ latest: '3.3.6', next: '4.0.0-alpha.2' }`. 3.3.6 is installed as expected.

**Comment by cvrebert** [comment]
Proposed related improvements to npm's documentation.
* https://github.com/npm/npm/pull/10787
* https://github.com/npm/docs/issues/486
* https://github.com/npm/npm/pull/10788
* https://github.com/npm/npm/pull/10789
* https://github.com/npm/npm/pull/10790

**Comment by cvrebert** [comment]
And I've just sent a PR to update our internal npm release instructions accordingly, so this should be fully resolved now.
@danielweck Thank you for the `dist-tags` pointer.

**Comment by boennemann** [comment]
@cvrebert I did a full write-up on dist-tags recently: https://medium.com/greenkeeper-blog/one-simple-trick-for-javascript-package-maintainers-to-avoid-breaking-their-user-s-software-and-to-6edf06dc5617
Using this technique you might be able to avoid the confusion around prerelease versions altogether.
