### ISSUE TITLE
Button borders disappear when font root size is set to 14px (v4)

### ISSUE THREAD

**Issue by asnoba** [twbs/bootstrap#18522]
When setting ```$font-size-root``` to ```14px``` the button borders disappear.

![btn-border](https://cloud.githubusercontent.com/assets/361101/11716319/39a83924-9f49-11e5-87d3-d4f21243c878.png)

Maybe they should be set to a fixed pixel width of ```1px```?

**Comment by cvrebert** [comment]
Duplicate of #17812.
Please search more next time, and please also upgrade to v4.0.0-alpha.2 or the `v4-dev` branch.

**Comment by asnoba** [comment]
Ah yes – Sorry about that.
