### ISSUE TITLE
Versions 3.3.5 and 3.3.6 break less4j

### ISSUE THREAD

**Issue by rlogiacco** [twbs/bootstrap#18529]
The latest two releases do break less4j which report a `ERROR 28:1 missing EOF at '/' in stylesheet (which started at 10:1)`. The same error doesn't occur with version `3.3.4` which is the one I've chosen to use until the issue isn't resolved.

**Comment by patrickhlauke** [comment]
I'd suggest filing an issue with https://github.com/SomMeri/less4j as (from what I can see) Bootstrap's Less files compile just fine with other less tools in build chains, unless you can pinpoint more specifically which less file(s) pose a problem.

**Comment by cvrebert** [comment]
We do not support Less compilers other than the official Less.js.
