### ISSUE TITLE
contextual, striped, animated progressbar not working in IE and Edge

### ISSUE THREAD

**Issue by canfiax** [twbs/bootstrap#18527]
There is no styling on the progressbar in Edge on Windows 10

**Comment by patrickhlauke** [comment]
http://getbootstrap.com/components/#progress (and, if you were referring to v4 alpha, http://v4-alpha.getbootstrap.com/components/progress/) look just as they should in Edge/Win 10.

**Comment by patrickhlauke** [comment]
![capture2](https://cloud.githubusercontent.com/assets/895831/11728053/7787a92e-9f7f-11e5-9c2b-3c03cd399175.PNG)
![capture](https://cloud.githubusercontent.com/assets/895831/11728054/778bf48e-9f7f-11e5-978f-1099796e5e5c.PNG)

**Comment by canfiax** [comment]
V4 Alpha. They don't. They don't adopt correct colors. They are all blue

**Comment by patrickhlauke** [comment]
Fixed - https://github.com/twbs/bootstrap/commit/70247e36f64295c61e0f867606793da5a26eebeb
