### ISSUE TITLE
Scrollspy sliding animation problem at iphone 5s ios 9.1

### ISSUE THREAD

**Issue by ifsNet** [twbs/bootstrap#18534]
Hi,

The content slide animation is coming with delay at ios 9.1 iphone 5s on chrome mobile browser.
How to fix it please ?

http://getuikit.com/docs/scrollspy.html
http://erdemygz.com

Thank you

**Comment by cvrebert** [comment]
> http://erdemygz.com

That site is using Bootstrap v2, which stopped being supported a while ago.

> http://getuikit.com/docs/scrollspy.html

That's a completely different framework: https://github.com/uikit/uikit

**Comment by cvrebert** [comment]
Duplicate of https://github.com/uikit/uikit/issues/1665
