### ISSUE TITLE
Glyphicons "fonts" folder disappeared in Bootstrap v4+ NPM dist

### ISSUE THREAD

**Issue by danielweck** [twbs/bootstrap#18539]
The Glyphicons `fonts` folder is NPM-packaged in v3, but not v4:
https://github.com/twbs/bootstrap/tree/master/fonts

https://github.com/twbs/bootstrap/blob/master/package.json#L64
```json
  "files": [
    "dist",
    "fonts",
    "grunt",
    "js/*.js",
    "less/**/*.less",
    "Gruntfile.js",
    "LICENSE"
  ],
```

https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L72
```json
  "files": [
    "dist",
    "grunt/*.js",
    "grunt/*.json",
    "js/*.js",
    "scss/**/*.scss",
    "Gruntfile.js",
    "LICENSE"
  ],
```

Is that an error? If not, what is the suggested alternative now?

Also see: https://github.com/twbs/bootstrap/issues/18520

**Comment by cvrebert** [comment]
There is no fonts folder whatsoever in v4 because v4 doesn't include any fonts anymore. Glyphicons has been dropped. See http://v4-alpha.getbootstrap.com/migration/#components

**Comment by danielweck** [comment]
Thanks, that helps.

**Comment by luisSanchezCruz** [comment]
thanks !
