### ISSUE TITLE
Use variables for <progress> base colors

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18535]
The code currently hardcodes `#0074d9` and `#eee` in a few places.
E.g. https://github.com/twbs/bootstrap/blob/f0f3020db159dd602fd6bfa0274ff8562f81677b/scss/_progress.scss#L30-L38

**Comment by patrickhlauke** [comment]
...I was waiting for you to notice ;)

**Comment by cvrebert** [comment]
Fixed by #18622.
