### ISSUE TITLE
Bootstrap 4 suggestions: Alerts design and outline buttons class naming

### ISSUE THREAD

**Issue by dmxt** [twbs/bootstrap#18538]
Hi, I'm an experienced designer and front-end developer. I have few suggestions:

##### Suggestion 1: Alerts design
It will match Bootstrap 4 style to remove visible border from all [alerts](http://v4-alpha.getbootstrap.com/components/alerts/) and it will look more pleasant and distinctive from Bootstrap 3. 

##### Suggestion 2: Outline buttons class naming
I see that you added [outline buttons](http://v4-alpha.getbootstrap.com/components/buttons/), wouldn't it more simple if it was named as `btn-primary-o` instead of `btn-primary-outline`? [FontAwesome](https://fortawesome.github.io/Font-Awesome/cheatsheet/) also follow this naming style and I think it's straightforward and more simple. 

Does anyone else agree with me?

I apologize in advance if it was already suggested.

**Comment by cvrebert** [comment]
> wouldn't it more simple if it was named as `btn-primary-o` instead of `btn-primary-outline`?

I wouldn't call it simpler. It is certainly shorter.
IMHO, it seems like excessive abbreviation.

**Comment by dmxt** [comment]
@cvrebert I honestly don't feel its excessive abbreviation, like Fontawesome use it and I use this type of naming in my own projects myself, so that's why it makes sense to me. Someone else can weight in with their opinion.

**Comment by cvrebert** [comment]
Shortening down to a single letter is near where I'd start drawing the line, personally.
CC: @mdo since his opinion is the one that matters here.

@dmxt Also, just as a process note for the future: If you have multiple unrelated suggestions, opening a separate issue for each suggestion is preferred.

**Comment by dmxt** [comment]
@cvrebert Okay, I'll keep that in mind. Thanks. 

Alert suggestion is great though.

**Comment by pelhage** [comment]
@dmxt I agree with @cvrebert - `o` isn't very semantic either, and IMO brings some cognitive overhead as a result.

An alternative that's semantic yet slightly shorter than `outline` could be `ghost`. "[Ghost button](https://www.google.com/search?q=ghost+button&safe=off&biw=1440&bih=801&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjgw7nb8djJAhXGeCYKHSd2CTkQ_AUIBygC)" is the common term in the design world used to describe the effect that `outline` achieves. I'm good either way, just my 2 cents.

**Comment by dmxt** [comment]
@pelhage Okay, I understand everyone have different opinion. I'm just used with `o` as an outline due to FontAwesome and my custom CSS, so that's why it makes sense to me.

If I have to pick, I would stick with `outline` instead of lesser common term `ghost`. I haven't heard of this term until you mentioned it but that's just me.

**Comment by mdo** [comment]
Probably fine leaving it as `outline` honestly. I might move the appearance of that word in the overall class though (e.g., `.btn-outline-*` instead of `.btn-*-outline`).

**Comment by cvrebert** [comment]
@mdo Any response to the Alert suggestion? Not that I'm favor or anything.

**Comment by dmxt** [comment]
@mdo It's best to leave it as `.btn-*-outline` and like what cvrebert said, any response to the Alert suggestion?

**Comment by mdo** [comment]
Why is it best to not change it? And we'll probably leave the borders in for now.

**Comment by dmxt** [comment]
@mdo Bootstrap 4 removed borders from many elements like button, navbar, progress bar, etc so it would make sense if borders on alert get removed as well.

Alerts with border:
![Alerts with border](https://i.imgur.com/NrmT8zl.png)

Alerts without border:
![Alerts without border](https://i.imgur.com/CnxWoq6.png)

**Comment by cvrebert** [comment]
> Bootstrap 4 removed borders from many elements like buttons

Um, buttons still have borders in v4.

**Comment by mdo** [comment]
Borders are indeed still on our buttons, and the borders will stay on the alerts as well. They might seem superfluous, and in some instances they can be, but as a designer I see them adding just a tad bit of structure with clearer boundaries.

And I'm still likely going to change our outline buttons to `.btn-outline-*` since that creates a more query-able string (e.g., `[class^="btn-outline"] { ... }`). We don't encourage those selectors too much, but thy are super useful and powerful in some instances. Also, simple searchability of the code base goes up with that.

**Comment by dmxt** [comment]
@cvrebert, @mdo 

From design view, Bootstrap v4 buttons don't look like they have borders:
![Bootstrap v4 buttons](http://i.imgur.com/dB6xKQH.png)

Comparing to Bootstrap v3:
![Bootstrap v3 buttons](http://i.imgur.com/pcZI0C7.png)

Obviously, they have border in CSS, borders are set with same color as background color. It's clearly Bootstrap v4 style not to have visible border, and it could be applied to alerts. Alerts can have borders same color as background color leading to non-visible border. This is for sake of consistency, distinction between versions and style.

**Comment by cvrebert** [comment]
> Obviously, they have border in CSS, borders are set with same color as background color.

Not for the `:focus`/`:active`/`:hover` states.

**Comment by dmxt** [comment]
@cvrebert Do alerts have `:focus / :active / :hover` states? ;)

**Comment by cvrebert** [comment]
> This is for sake of [...] distinction between versions [...]

As far as I'm aware, there's no such explicit visual design goal, although @mdo can of course feel free to correct/enlighten me regarding this.

**Comment by dmxt** [comment]
@cvrebert It can happen on accident, but I noticed that on v4 have invisible borders on all, if not almost all, elements in comparison with v3. Buttons (idle state), navbar, progress bars, etc. So I suggested that it can be applied on alerts since it's only element that stood out and it looks like it's stuck in v3. With or without explicit visual design goal, this is for sake of consistency.
