### ISSUE TITLE
Consider adding accessibility guidance to Label/badge docs

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18544]
See http://www.slideshare.net/maxdesign/front-end-frameworks-are-they-accessible/32 et seq.

**Comment by patrickhlauke** [comment]
i'd contend that it's not purely screenreader users that may be confused by the random number, but all users to varying degrees. it also heavily depends on what the preceding text in the actual button/etc is. however, adding a suggestion boxout won't hurt anyone.
