### ISSUE TITLE
Consider combining "Dropdowns" and "Button dropdown" docs pages

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18545]
Given that dropdowns are used with buttons 80% of the time, separating them doesn't make a lot of sense, IMHO.
The current split also means that the "Dropdowns" page lacks any interactive examples; its only examples are currently static always-expanded dropdowns.

**Comment by patrickhlauke** [comment]
:+1:

**Comment by gseregni** [comment]
@cvrebert  When we should use button dropdown and when dropdown ? It's not clear...

**Comment by mdo** [comment]
Happening with #18807.
