### ISSUE TITLE
bootstra RTL.LESS BUG

### ISSUE THREAD

**Issue by gjorgji18** [twbs/bootstrap#18540]
When i install Package Twitter.Bootstrap.RTL.Less from Nuget and try compile a less file and say Errorr
In grid.less in 231 row has word left who i think is error
After i delete and save everything was good
Please watch this problem because next time when i go to update may cause new problem

**Comment by patrickhlauke** [comment]
I'd suggest contacting whoever managers that particular package (https://www.nuget.org/packages/Twitter.Bootstrap.RTL.Less/ ?), as it's nothing to do with bootstrap core.
