### ISSUE TITLE
How can add a new breakpoint that same as md?

### ISSUE THREAD

**Issue by aboutjquery** [twbs/bootstrap#18546]
Hello, i would like to add a new breakpoint call `break` at the end of the map, the breakpoint map will be.

$grid-breakpoints: (
  xs: 0,
  sm: 544px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  break: 768 // place this key after `xl`
) !default;

`break` is just same as `md`, i try edit this with sass, seem that `breakpoint-down` mixin not work correctly with above map.

Any way to make this map work with `breakpoint-down` mixin?

Thank you so much.

**Comment by cvrebert** [comment]
There is no way to alias a breakpoint to multiple names.

To add a new breakpoint with a *different* size, you must insert it into the correct position in the map, such that ascending numerical order is maintained. For example:
```scss
$grid-breakpoints: (
xs: 0,
sm: 544px,
smallish: 600px, // new breakpoint
md: 768px,
lg: 992px,
xl: 1200px
) !default;
```
