### ISSUE TITLE
Docs navbar doesn't render correctly on SM viewports

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18557]
See https://github.com/twbs/bootstrap/issues/18551#issuecomment-164134715

**Comment by patrickhlauke** [comment]
related: i'd actually suggest a change to the docs navbar in line with the actual pattern suggested in the docs themselves https://github.com/twbs/bootstrap/pull/18662

**Comment by mdo** [comment]
Resolved in #19890.
