### ISSUE TITLE
.hidden-XX-down how to show/hide elements in same time?

### ISSUE THREAD

**Issue by jek-fdrv** [twbs/bootstrap#18551]
With new rules .hidden-XX-down ONLY I cant show and hide in same time elemts.
I have:
```html
<button class="navbar-toggler pull-xs-right hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">&#9776;</button>
```
and
```html
<ul class="nav navbar-nav hidden-sm-down pull-xs-right">
    <li class="nav-item">
        <a class="nav-link" href="#">Link 1</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Link 2</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Link 3</a>
    </li>
</ul>
```
Here how it works 
stadia 1
![2015-12-12 10 49 08](https://cloud.githubusercontent.com/assets/4230282/11761121/3f12db8c-a0be-11e5-8283-a97d82b71860.png)
stadia 2
<img width="405" alt="monosnap 2015-12-12 10-53-17" src="https://cloud.githubusercontent.com/assets/4230282/11761128/98dedf80-a0be-11e5-90e7-85c574905748.png">
stadia 3
![2015-12-12 10 54 04](https://cloud.githubusercontent.com/assets/4230282/11761134/b7286f88-a0be-11e5-820a-32e740e2b3a1.png)

So there is a white space during  responsive resizing. White blame when any nav doesn't appear in 230 px.

**Comment by cvrebert** [comment]
@jek-fdrv Please make your example into a JS Bin or JS Fiddle.

**Comment by jek-fdrv** [comment]
Ok. 1 min plz.

**Comment by jek-fdrv** [comment]
Here https://jsbin.com/ravoninino/edit?html

**Comment by twbs-lmvtfy** [comment]
Hi @jek-fdrv!

You appear to have posted a live example (https://jsbin.com/ravoninino/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 36, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 12, column 3 thru column 23: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jek-fdrv** [comment]
Nice system! I like this validation from stupid mistakes... Sry. Here the new version.
https://jsbin.com/jihotoxise/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @jek-fdrv!

You appear to have posted a live example (https://jsbin.com/jihotoxise/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jek-fdrv** [comment]
Honestly on bootstrap original documentation page same thing
One
![2015-12-12 11 46 03](https://cloud.githubusercontent.com/assets/4230282/11761315/29294182-a0c6-11e5-9a61-05b3f31b85c4.png)
Two
![2015-12-12 11 46 11](https://cloud.githubusercontent.com/assets/4230282/11761317/3297452a-a0c6-11e5-83a2-730ccda84fdd.png)
Paa-aadaa
![2015-12-12 11 46 18](https://cloud.githubusercontent.com/assets/4230282/11761320/408d4274-a0c6-11e5-9bb5-e0353a6e7145.png)

**Comment by jek-fdrv** [comment]
Also why error system with html validation ask about `is missing X-UA-Compatible <meta>` if bootstrap  doesn't support 8 IE any more?
https://jsbin.com/zabaxozefe/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @jek-fdrv!

You appear to have posted a live example (https://jsbin.com/zabaxozefe/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 40, column 3 thru column 44: No space between attributes.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jek-fdrv** [comment]
https://jsbin.com/zabaxozefe/edit?html,output

**Comment by cvrebert** [comment]
> Also why error system with html validation ask about is missing X-UA-Compatible `<meta>` if bootstrap doesn't support IE8 any more?

The problem which that tag addresses is not specific to IE8.

**Comment by cvrebert** [comment]
The SM breakpoint covers the following range of viewport widths: 544px ≤ viewport_width < 768px
`.hidden-sm-up` hides elements when the viewport width is SM or wider, which is to say viewport_width ≥ 544px.
`.hidden-sm-down` hides elements when the viewport width is SM or narrower, which is to say viewport_width < 768px

Thus, if the viewport is within the SM breakpoint and two elements have `.hidden-sm-up` and `.hidden-sm-down`, neither of them will be visible.
So, the classes are working as intended.

You should use a different combination of responsive visibility classes such that both elements are never simultaneously invisible. I invite you to consult the chart on http://v4-alpha.getbootstrap.com/layout/responsive-utilities/ to better understand the effects of the classes.

**Comment by cvrebert** [comment]
> You should use a different combination of responsive visibility classes such that both elements are never simultaneously invisible.

For example, `.hidden-sm-down` and `.hidden-md-up`

**Comment by cvrebert** [comment]
Filed #18557 regarding the issue with the navbar on v4-alpha.getbootstrap.com
