### ISSUE TITLE
Responsive Utilities docs still think the grid is in em instead of px

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18556]
See the first table on http://v4-alpha.getbootstrap.com/layout/responsive-utilities/

**Comment by cvrebert** [comment]
Also, for this table, we should be quoting viewport width ranges rather than just minimum viewport widths.

**Comment by cvrebert** [comment]
Related: #18503

**Comment by bassjobsen** [comment]
should you expect a range at http://v4-alpha.getbootstrap.com/layout/grid/#grid-options too?
In both situation we should have?
Portrait phones (<544px)
Landscape phones (≥544px - <768px)
Tablets (≥768px - <992px)
Desktops (≥992px - <1200px)
	Extra large devices
Desktops (≥1200)
Or should i use ≥544px - &le;767px

**Comment by cvrebert** [comment]
> should you expect a range at http://v4-alpha.getbootstrap.com/layout/grid/#grid-options too?

I'm thinking "No", because the grid classes are open-ended and apply to "minimum width X and up" (until overridden by another grid class).

The reason I think http://v4-alpha.getbootstrap.com/layout/responsive-utilities/ should use ranges is because the table there is treating the breakpoints as disjoint and mutually exclusive for the purposes of the Visible/Hidden cells.

> Or should i use ≥544px - ≤767px

No, because that's inaccurate when considering fractional CSS pixels.

**Comment by cvrebert** [comment]
Fixed by #18560.
