### ISSUE TITLE
Migrate from uber/npm-shrinkwrap to regular `npm shrinkwrap`

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18559]
Fixes #19596.
The shrinkwrap output consistency issue has allegedly been fixed in npm@3: https://github.com/npm/npm/issues/10731

**Comment by XhmikosR** [comment]
Is this still valid @cvrebert?

**Comment by cvrebert** [comment]
Affirmative.

**Comment by XhmikosR** [comment]
Do you want me to make a test branch against v4-dev for this? I'm all for reducing the dependencies if we can.

**Comment by cvrebert** [comment]
Sure.

**Comment by XhmikosR** [comment]
You still don't want npm-shrinkwrap.json in root? It would make things simpler.

**Comment by cvrebert** [comment]
This is now more important since https://news.ycombinator.com/item?id=11340510 has made `npm-shrinkwrap` impossible to install, at least temporarily.
I'll try to take a look at this.

**Comment by XhmikosR** [comment]
If you don't need the dest change, the patch is ready :P

**Comment by cvrebert** [comment]
I'll make the dest change and try to avoid grunt-exec.

**Comment by XhmikosR** [comment]
:+1: Feel free to push to this branch.

Should we also backport this to master too?

**Comment by cvrebert** [comment]
If we're currently using uber/npm-shrinkwrap there too, then yes. I'll backport the patch once it's finalized.
