### ISSUE TITLE
Dropping Thumbnails

### ISSUE THREAD

**Issue by AlexandruDoda** [twbs/bootstrap#18553]
Hello,

Apparently, Bootstrap 4 will drop the '.thumbnail' class which was used to create, well, thumbnails :)
I totally agree with moving everything into the Card component (which is a lot more compact), but what happens if we only want to use the thumbnail class on its own without all the extra cards markup? 

In a "blog" example, when creating a blog page loop, a recent posts widget sidebar and a category widget, the 'thumbnail' class could be used to apply a default common markup to all of them. Is that class something we would have to create separately in this scenario? Wouldn't it be useful keeping it for that type of usage?

Please let me know if I am wrong or if there's a better approach towards it.

**Comment by cvrebert** [comment]
> what happens if we only want to use the thumbnail class on its own without all the extra cards markup?

I wouldn't say there's a lot of extra markup. It's

```html
<!--Old thumbnail code-->
<div class="thumbnail">
  <img src="...">
  <div class="caption">
    <h3>Title</h3>
    <p>Some text</p>
  </div>
</div>
```
vs.
```html
<!--New card code-->
<div class="card">
  <img class="card-img-top" src="...">
  <div class="card-block">
    <h4 class="card-title">Title</h4>
    <p class="card-text">Some text.</p>
  </div>
</div>
```

which is the same number of elements. There's 3 more classes (because we're avoiding element and child selectors like the plague in v4, to improve flexibility & extensibility), but that's not much of a burden IMHO.

Or perhaps you had a different case in mind?

> In a "blog" example, when creating a blog page loop, a recent posts widget sidebar and a category widget, the 'thumbnail' class could be used to apply a default common markup to all of them.

I'm not seeing why you couldn't/wouldn't apply the Card widget to them instead. Perhaps if you made a concrete example? You don't seem to be referring to the [official "Blog" example](http://getbootstrap.com/examples/blog/), which doesn't use thumbnails.

**Comment by AlexandruDoda** [comment]
I'm sorry, perhaps the blog example is not the best :D.
Here's an example of how I use it with my custom Wordpress theme framework in an e-commerce environment:

These images are all using the ".thumbnail" class as clicking them opens a lightbox and it is a good indicator for that functionality.
![Uploading Screen Shot 2015-12-13 at 20.24.17.png…]()

And here is the code:
![screen shot 2015-12-13 at 20 24 53](https://cloud.githubusercontent.com/assets/8274669/11769125/e5bf67ec-a1d7-11e5-9ab5-69ea571e0ded.png)

As you can see, the thumbnails do not need a caption or anything, only the ".thumbnail" class which is applied to those image links.

**Comment by mdo** [comment]
Ah, you mostly want `.img-thumbnail` then: http://v4-alpha.getbootstrap.com/content/images/#image-shapes.

**Comment by AlexandruDoda** [comment]
Well, not really, because the "img-thumbnail" does not have a hover state and those image links should have one as they open lightbox items on click.

**Comment by cvrebert** [comment]
Also, even if the answer here really is "Use cards", we don't seem to have a Card example with just an image without any header/footer/caption currently.

**Comment by AlexandruDoda** [comment]
In that scenario (which could be pretty common), it wouldn't make sense to have an extra wrapper around that item, would it :) ?

**Comment by cvrebert** [comment]
Hmm? There's no extra wrapper, unless I'm missing something.

```html
<div class="thumbnail"> <!-- or <a class="thumbnail"> -->
  <img src="...">
</div>

versus

<div class="card">
  <img class="card-img-top" src="..."> <!-- or maybe .card-img-middle; whatever. -->
</div>
```

In both cases, there's an element wrapping the `<img>`.

**Comment by AlexandruDoda** [comment]
Oh, all right, I see. Thanks for the clarification.
Is "-top" still necessary if it's just an image card though? 
Maybe "card-img" would be more straight forward or simply using the "card" class that applies default properties to the direct child image just like the ".thumbnail" class? Just popping in suggestions - please let me know if it's relevant or not.

**Comment by cvrebert** [comment]
> Is "-top" still necessary if it's just an image card though?

Some class will likely be required, but it might be a different one (I agree -top seems weird here). As I mentioned earlier, we need to add a "image-only card" example to the docs, to clarify the exact markup that ought to be required.

> simply using the "card" class that applies default properties to the direct child image 

We're trying hard to avoid CSS child selectors and CSS tag selectors in v4, since they hurt flexibility and extensibility. We're pushing for explicit classes instead.

**Comment by AlexandruDoda** [comment]
Awesome, thank you very much :) 
I am so eager to work with Bootstrap 4 on my projects.
Cheers!

**Comment by mdo** [comment]
Making a note for myself to revisit this—sounds like we need some more examples of using cards to replace the old thumbnails.

**Comment by mdo** [comment]
Coming back to this once again, I'm punting on any changes here.

**Comment by inyoka** [comment]
Using "card-img" without a wrapping card div seems to work.  Is there a reason this should be avoided?

```
      <div class="col-lg-4">
          <img class="card-img" src="http://i.imgur.com/qK42fUu.jpg" alt="">
      </div>
```
