### ISSUE TITLE
oneskyapp translation links don't work

### ISSUE THREAD

**Issue by thekondrashov** [twbs/bootstrap#18555]
Looks like oneskyapp translation links on v3 [Translations](http://getbootstrap.com/getting-started/#translations) page don't work. It's [French](http://www.oneskyapp.com/fr/docs/bootstrap/getting-started/), [Russian](http://www.oneskyapp.com/ru/docs/bootstrap/) and [Spanish](http://www.oneskyapp.com/es/docs/bootstrap/) translations.
Maybe I can get the source files of the translations of these languages in this case?

**Comment by cvrebert** [comment]
X-Ref: #16669

**Comment by kkirsche** [comment]
@thekondrashov this is a third party translation and the Bootstrap team only links to external pages, it does not have the source. They also appear to not host the documentations on [Github](https://github.com/onesky).

**Comment by cvrebert** [comment]
Tweeted to @vincentchan about the problem: https://twitter.com/cvrebert/status/675769655630270464

**Comment by thekondrashov** [comment]
Thank you very much for the answer. Then I'll try to find an alternative resource with translation.

**Comment by vincentchan** [comment]
@thekondrashov @cvrebert Sorry for the delay and inconvenience caused. The problem is solved now.

**Comment by cvrebert** [comment]
Thanks @vincentchan !

**Comment by thekondrashov** [comment]
Thank you very much @vincentchan!
