### ISSUE TITLE
_dropdown.scss references defunct .pull-right class

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18550]
Refs #18548

**Comment by mdo** [comment]
No longer a problem. Was a small code comment that had the old class, but just removed that in 64b88bd.

**Comment by cvrebert** [comment]
@mdo No, still busted:
https://github.com/twbs/bootstrap/blob/cb7b78087690e756e33b6f6abdb3548f73f8bb1b/scss/_dropdown.scss#L161

**Comment by mdo** [comment]
Damnit, probably time to call it if I'm missing that obvious of stuff 😆.

Fixed in 612d287.
