### ISSUE TITLE
Check for broken links & nonexistent fragments as part of docs build

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18568]

**Comment by aelisecarey** [comment]
Are there links for the Reboot, Grid Only, and Flexbox downloads?

**Comment by cvrebert** [comment]
@aelisecarey Currently there aren't any actual built files for those, just the skeleton of some Grunt+Sass infrastructure to build them.

**Comment by petetnt** [comment]
@cvrebert is there an existing issue to track custom builds in the docs?

**Comment by avradul** [comment]
@cvrebert Then you need to remove links.
Never publish broken links.

**Comment by RyanZim** [comment]
@avradul v4 is still in alpha; both the code and docs are a WIP and are far from complete.

**Comment by bardiharborow** [comment]
@cvrebert, I'm not sure about automating this, but I did a manual scan of the docs with the [W3C Link Checker](https://validator.w3.org/checklink) and have incorporated several broken links into #20557.

**Comment by mdo** [comment]
Seems https://github.com/ChrisWren/grunt-link-checker could help with the links.

**Comment by bardiharborow** [comment]
I'll look into it.

**Comment by vanduynslagerp** [comment]
The PR #21695 is a proposition for this issue. It uses [broken-link-checker](https://github.com/stevenvachon/broken-link-checker).

[This comment](https://github.com/twbs/bootstrap/issues/18568#issuecomment-255617699) mentioned [grunt-link-checker](https://github.com/ChrisWren/grunt-link-checker) but unfortunatly this produce errors for links that are valid.
Here is an example:
```
>> Resource not found linked from http://localhost:9001/getting-started/introduction/ to http://localhost:9001/getting-started/introduction/%7Burl%7D
>> Status code: 404
>> Resource not found linked from http://localhost:9001/getting-started/contents/ to http://localhost:9001/getting-started/contents/%7Burl%7D
>> Status code: 404
```

**Comment by XhmikosR** [comment]
@vanduynslagerp: I rebased your patch. It works OK but it's slow.

Would it be possible to switch to `simplecrawler` which supports concurrency and CC me? We can work on ignoring the false positives.

**Comment by vanduynslagerp** [comment]
@XhmikosR, using `simplecrawler` might be possible but it would require some more work to implement the rules to check (for example verifying that URL with a hash correspond to a anchor).

I don't think I will contribute to Bootstrap in the near future, but feel free to re-use/change/update any code in this PR (or any other PR :)).
I'll definitely let you know if I spend more on Bootstrap contributions though.

**Comment by XhmikosR** [comment]
I have a branch for this in https://github.com/twbs/bootstrap/tree/v4-dev-xmr-broken-link-checker

Works fast because we don't check for broken external links.

So, I'm not 100% satisfied with this solution. Also, I can't find a switch to make blc's output less verbose.

Other than that it works, see https://travis-ci.org/twbs/bootstrap/builds/306272185.

Ideally, I think we should hook something up using [simplecrawler](https://github.com/simplecrawler/simplecrawler), not sure if I'll ever get around to do it, so PRs are welcome.

@Johann-S: maybe we could work together on a simple script to get the job done with simplecrawler. Let me know what you think.
