### ISSUE TITLE
Tabs plugin adds .active class to wrong element of correct tab when switching

### ISSUE THREAD

**Issue by ditiem** [twbs/bootstrap#18566]
The "active" class is set in the &lt;li class="nav-item"&gt; rather than the &lt;a class="nav-link"&gt; when you click on the "tab". The tap-panels are hidden and shown accordingly without any problem.

![screen shot 2015-12-13 at 19 56 05](https://cloud.githubusercontent.com/assets/1786965/11768643/d90b0690-a1d3-11e5-86ab-2705924601e4.png)

**Comment by cvrebert** [comment]
@ditiem This is regarding Bootstrap v4, correct?

**Comment by ditiem** [comment]
@cvrebert Yes.
