### ISSUE TITLE
Consider renaming .form-control-label

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18573]
FWICT, it's currently only meant for grid-based forms (see #17498, #18571), but the class's name doesn't communicate this at all.
Perhaps add something like `grid` or `col` to the name? e.g. `.col-form-label`

**Comment by cvrebert** [comment]
CC: @mdo for feedback

**Comment by mdo** [comment]
Fixed in 0a4d315 with #19141.

**Comment by mdo** [comment]
Fixed in 0a4d315 with #19141.

**Comment by Herst** [comment]
There are still some remains of `.form-control-label` and the migration docs still mention it as well.
