### ISSUE TITLE
Bootstrap Mail

### ISSUE THREAD

**Issue by TonyValenti** [twbs/bootstrap#18572]
Good morning Bootstrap!
Congrats on the upcoming V4.0 release.  What great stuff!

According to Bootstrap's homepage:
"Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile first projects on the web."

Right now Bootstrap is a great library from frontend WEBSITE design, however, WEBSITES are only part of the projects on the web.  Have ya'll considered building a similar email template library?  It seems as if email templates are one of the next frontiers of the web.  Everybody has to do them and everybody hates having to do them because all of the extensive testing that has to take place to make sure things work with every client.  It would be great if I could build a "Boostrap Email" and just know that it will work on every client and have the tools that handle doing things like inlining styles and such.

Just an idea.

**Comment by kkirsche** [comment]
Sadly email usually requires online styles for maximum compatability and is extremely hack heavy. I'd argue a project like Bootstrap would look "ugly" and wouldn't work nearly as well as thought unless the team made tools to automate inlining styles. Also lots of need to test extensively with non free services usually like Litmus. Just my 2¢ though from ripping my hair out with them for a few years.

**Comment by mdo** [comment]
It's been asked, and the response is the same—we have no plans to build anything there yet :).
