### ISSUE TITLE
Label in form validation style has a padding left

### ISSUE THREAD

**Issue by adriansuter** [twbs/bootstrap#18571]
Version 4.0.0.alpha2: The form control labels on the examples at http://v4-alpha.getbootstrap.com/components/forms/#validation have a left padding. Isn't that wrong? The other examples do not have this padding. For example: http://v4-alpha.getbootstrap.com/components/forms/#form-groups

**Comment by cvrebert** [comment]
Confirmed. The labels here have the `.form-control-label` class even though they're not in a grid-based form.

**Comment by vsn4ik** [comment]
Duplicate #17498.
