### ISSUE TITLE
Fixed header

### ISSUE THREAD

**Issue by vespino** [twbs/bootstrap#18585]
I'm using the following classes to fix a header: navbar navbar-default navbar-fixed-top

This works perfectly on my PC:

![schermafbeelding 2015-12-16 om 12 20 21](https://cloud.githubusercontent.com/assets/6991325/11839657/c7857ebe-a3ef-11e5-99fd-ce97cea9a9a3.png)

But when checking it on iPhone or iPad, the header is only partially shown:

![img_3292](https://cloud.githubusercontent.com/assets/6991325/11839666/e1c32cb8-a3ef-11e5-9fae-b070d5d5e958.PNG)

I'm using Bootstrap v3.3.6. Has anybody had this problem and were you able to fix it?

**Comment by patrickhlauke** [comment]
Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker please use StackOverflow or similar for how-to/troubleshooting requests. Thanks.
