### ISSUE TITLE
Document removal of non-responsive .text-left/right/center classes

### ISSUE THREAD

**Issue by simonewebdesign** [twbs/bootstrap#18580]
The [migration page](http://v4-alpha.getbootstrap.com/migration/#typography) says the `.text-*` classes have been moved to _utilities.scss, but I can't find `.text-center` in there. Has it been removed?

**Comment by NandoTh** [comment]
I think now you need to use: ```.text-#{$breakpoint}-center```.

**Comment by simonewebdesign** [comment]
That's it. Thanks!

**Comment by cvrebert** [comment]
Yes, we need to add migration guidance for #18317.

**Comment by mdo** [comment]
Added in 856e21757431ca6c1bbe9e183708ec7174fa73a1 I believe.
