### ISSUE TITLE
Remove background-image:url(data:image/jpg;base64) in modal bootsrap

### ISSUE THREAD

**Issue by sidaurukfreddy** [twbs/bootstrap#18586]
Hello i have been developing upload images in modal bootsrap which has resize and crop images i got tutorial from <a href="http://scottcheng.github.io/cropit/">here </a> my question is how can i clear the modal from old images,

i use jquery but nothing happend
<pre>
success: function(data) {
$('#forminfo').trigger("reset"); //reset form 
$('#myModalinformation').find('form')[0].reset();
}
</pre>

**Comment by cvrebert** [comment]
Sorry, but we cannot assist you with problems involving third-party libraries such as Cropit.
Either ask the Cropit community/developers for help, or ask the Bootstrap community for help on StackOverflow or similar (see https://github.com/twbs/bootstrap/blob/master/README.md#community for links).

**Comment by sidaurukfreddy** [comment]
why you closed it @cvrebert ! still need discussion about it, i guess this is bootsrap issue so i posted in here lah already ask in stackoverflow here is "http://stackoverflow.com/questions/34310925/remove-or-clear-background-image-urlimage-png-after-success-submit-in-modal-b/34313272#34313272

**Comment by patrickhlauke** [comment]
> i guess this is bootsrap issue

nope sorry, it isn't. this is related specifically to your own specific code. nothing to do with core functionality provided by bootstrap.
