### ISSUE TITLE
Document recommended Autoprefixer `browsers` setting

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18584]
The docs mention that Autoprefixer is required, but don't cover what `browsers` setting is required for parity with precompiled Bootstrap.
To avoid having two copies which are liable to get out-of-sync, I propose moving the data out of `Gruntfile.js` and into a separate file. The docs can then simply say to consult the file and link to it.
X-Ref: https://github.com/twbs/bootstrap-sass/pull/995

**Comment by mdo** [comment]
Mention and link in docs added with a296975.
