### ISSUE TITLE
Drop Down Sub menu is not working in Iphone 6

### ISSUE THREAD

**Issue by jumboteam** [twbs/bootstrap#18587]
Drop Down Sub menu is not working in Iphone 6, by using below code.

<div class="collapse navbar-collapse" id="custom-collapse">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">The Company <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="about-us.html">About Us</a></li>
                                            <li><a href="vision.html">Vision</a></li>
                                            <li><a href="mission.html">Mission</a></li>
                                        </ul>
                            </li>
</ul>
</div>

**Comment by patrickhlauke** [comment]
Per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker please use StackOverflow or similar for how-to/troubleshooting requests. Thanks.
