### ISSUE TITLE
Responsive media object

### ISSUE THREAD

**Issue by AlexandruDoda** [twbs/bootstrap#18595]
Working with the "Media Object" has been extremely helpful in the past, but there are a couple of issues which I kept encountering, having to fix them with every project.

1 - The "media-left" part seems very close to the content. Perhaps increasing the default padding-right a bit would make things look more clean and readable?

2 - Responsiveness seems a bit tricky on mobile, especially when the media object is a bit wider than default. Perhaps a class that turns the "media object" into something more responsive would be good? Maybe a "media-responsive" class which would make the mobile version not use the table display model and moves the "media-left" above the "media-body"? For example, when using a larger media-object item like the following, the page layout will be really broken:

<img width="1440" alt="screen shot 2015-12-17 at 10 53 16" src="https://cloud.githubusercontent.com/assets/8274669/11867964/8916eb50-a4ac-11e5-9246-400dfa1219bf.png">

There are cases where we might have to use larger media-objects - like comment sections, an "about author" section on a blog post, etc.

**Comment by AntonTrollback** [comment]
3 - Add additional configuration variables for the [left/right paddings](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_media.scss#L64)

**Comment by tecdrop** [comment]
+1

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by arechsteiner** [comment]
May I piggyback on this as I've just encountered an issue with the media object as well:

3 - "media-right" does not seem to consistently work where "media-left" works in the examples in the documentation. If you take the [very first example](http://v4-alpha.getbootstrap.com/layout/media-object/#default-media) and replace media-left with media-right, it looks like this: 

![media-right in docs](https://cloud.githubusercontent.com/assets/1199486/14458908/05478c48-00b5-11e6-9d4c-14f036e7100d.png)

Same thing happens in the subsequent examples where a div is used as a wrapper. The only place media-right seems to work is inside the media-list.

**Comment by moshie** [comment]
+1 might I recommend implementing `media-sm` `media-md`

**Comment by mdo** [comment]
We won't be adding anything for this in v4 yet (at least the initial launch) and I'm unclear how much this would benefit others when you can use responsive media independent of the media classes. Put another way, there's nothing stopping you from using `max-width` and more with a bit of custom code to accomplish these things.

**Comment by devkinetic** [comment]
@mdo can I get a followup on this. Perhaps an example for:

> using max-width and more with a bit of custom code

I'm looking to have the media object break into two rows.
