### ISSUE TITLE
position issue

### ISSUE THREAD

**Issue by han1070** [twbs/bootstrap#18594]
hi guys ,can you help me with my position issue.

how can i put my logo and the rest navbar menu  in the same line?
how can i put the text upper the button "contact" right-align with the button?
how can i put the whole navbar a little upper?
![2015-12-17 3 39 34](https://cloud.githubusercontent.com/assets/16324262/11864051/78b1eee0-a4d4-11e5-8c92-423ec3eff11f.png)

**Comment by patrickhlauke** [comment]
Please use StackOverflow or similar for help/how-to requests. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
