### ISSUE TITLE
active element class is used differently in navbar and nav-tabs

### ISSUE THREAD

**Issue by ygatesoupe** [twbs/bootstrap#18599]
Hi,
I noticed .active class is not applied to the same element in navbar and nav-tabs. 
Using navbar, .active will be used within a .nav-item, whereas in nav-tabs, .active is be used within .nav-link element.

    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Another link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

    <nav class="navbar navbar-light bg-faded">
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
      </ul>
    </nav>

This is confusing if you plan to have common styling for navbar and nav-tabs.

**Comment by cvrebert** [comment]
You are referring to Bootstrap v4, correct?

**Comment by bassjobsen** [comment]
@ygatesoupe i think your are right. According the nav-tabs and carousel which has been refactored  to avoid child selectors, you should use:

    <nav class="navbar navbar-light bg-faded">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
       </ul>
    </nav>    

Notice that the above already works with the current code. Also see: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L183

The SCSS code compiles into CSS which applies the same styles for the `.navbar-light .navbar-nav .active > .nav-link` and `.navbar-light .navbar-nav .nav-link.active`

**Comment by mdo** [comment]
Docs clarification for being able to use both coming in #19890.

**Comment by bardiharborow** [comment]
@mdo, I just came across this on a project. I saw you've clarified the docs a little for this, but can we choose one canonical way of doing things, ensure that the examples for `.nav` and `.navbar` match?

The current state of things:

```html
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="#">.active on anchor tag</a>
  </li>
</ul>
```

```html
<ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">.active on parent tag</a>
    </li>
</ul>
```

**Comment by mdo** [comment]
@bardiharborow Sure.

I think putting the active class on the _active_ element is the most straightforward and logical. If an element is in a state, that state should be reflected on that element and not it's parent. We could go that route for the dropdown menus... but it'd mean selectors like `.nav-link-active ~ .dropdown-menu` or something similar. In that instance, I think it'd be best to do the parent as both elements get their states modified (i.e., an anchor is active/open and the menu is shown).

Make sense?

**Comment by appsparkler** [comment]
Also to add a `active` class to the `.nav-item` too, it can be done like so:

```javascript
$('[data-toggle=tab]').on('shown.bs.tab', function(evt) {
    $(evt.currentTarget).parent().addClass('active');
    $(evt.relatedTarget).parent().removeClass('active');
});
```

and in the `HTML` we will add `active` class to the `.nav-item` too:

```html
...
<li class="nav-item active">
   <a class="nav-link active" ...></a>
</li>
...
```

Good Luck...
