### ISSUE TITLE
.btn-default but no .btn-md ?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18592]
A philosophical question that occurred to me:
So, `.btn` itself doesn't have a default color, which is why `.btn-default` exists.
Given that `.btn` doesn't have a default color, why does it have a default size? Perhaps it should have no default size and there should be e.g. a `.btn-md` class that explicitly sets a "normal" size? Or if this difference is legitimate, what's the rationale behind it?
X-Ref: https://github.com/jquery/css-chassis/pull/138

**Comment by AlexandruDoda** [comment]
I think .btn is more related to the layout and  ".btn-default", ".btn-primary", ... are related to style. It's a great sepparation between layout and style, and ".btn-md" is somehow still layout-related. I think we should not bloat the DOM with extra classes because most of the time, if we want to edit the default button size, we could simply edit it with SASS. 

In conclusion, it is very likely that we use the default button size, far more likely than using the "btn-default" so I consider the current separation of layout / style is good.

**Comment by cvrebert** [comment]
I remind you that we already have `.btn-lg` and `.btn-sm` classes.

**Comment by AlexandruDoda** [comment]
Indeed, but it's most likely to use the default button size so having to specify it explicitly only adds more classes than necessary to the DOM. It makes sense to have layout-related properties by default while leaving style-related properties optional.

Even though it could make sense, I don't think we have to compromise the simplicity of Bootstrap where it's unnecessary. Again, it's far more likely to want to change the style of the button than its size, and forcing an extra class on a website that is only using the default size could mean just bloating the markup.

Please let me know if I am wrong :)

**Comment by AlexandruDoda** [comment]
And yes, the -lg and -sm classes are great, but not as likely to be used compared to -primary and -default (or the others).

**Comment by arechsteiner** [comment]
@cvrebert: Note that .btn-default was renamed to .btn-secondary: f399d21ef5e20bd736d5cf2946acb982378cd2f4

**Comment by SharkyKZ** [comment]
Default sizing is required to keep consistent look throughout framework. .btn-md would just add clutter, as would .form-control-md, .input-group-md, .modal-md, .pagination-md... All of which would be required in case .btn-md is added, to fully follow this naming convention.

The better question is here why .btn doesn't have a default color. .btn-secondary styles could be applied to .btn by default and .btn-secondary perhaps replaced by something useful like .btn-inverse from v2.

**Comment by cvrebert** [comment]
> The better question is here why `.btn` doesn't have a default color.

That was a deliberate change made in v3.

**Comment by Studio384** [comment]
Honnestly, adding `.btn-md` and requiring it for every normal buttons sounds to me like adding classes for the sake of adding classes. Don't do that.

**Comment by mdo** [comment]
My assumption there is that it's perfectly acceptable to have a default button size, but not necessarily a default button style. Specifying what style—or semantic/contextual variation—you need makes more sense than specifying an initial size as well.

I understand the argument, but I don't think we need to go that far with the class and minimal override approach we've taken elsewhere :).

(Holler here if that doesn't make sense though!)
