### ISSUE TITLE
<a> btn with .center-block becomes as wide as its container

### ISSUE THREAD

**Issue by davidjameslettice** [twbs/bootstrap#18596]
Hey,

I'm not sure if this is by design, or a v4 bug, or if I've overlooked something.

Essentially I'm creating a multi-page form, and I have the following code:
```<a class="btn btn-primary center-block" href="/signup/first_page" role="button">Previous</a>```
```<button type="submit" class="btn btn-primary center-block" id="next">Next</button>```

Obviously this is to create a Previous and Next button, with the Next button submitting, and the Previous acting as a link to the previous page.

The Next button works fine with the 'center-block' class, it centers the button and nothing more. However the Previous button spans the whole width of the page. I've tried putting them both within a center-block div but that didn't make any difference.

Any advice, or is this a bug?

**Comment by cvrebert** [comment]
It seems that `display: block` affects `<a>` and `<span>` elements differently than `<button>` elements.

Using a wrapper `<div>` with `.text-xs-center` seems to work fine as an alternative:
```html
<div class="text-xs-center">
  <a class="btn btn-primary" href="/signup/first_page">Previous</a>
</div>
```

**Comment by mdo** [comment]
You want text alignment as @cvrebert mentioned awhile back because our buttons are `inline-block`, not `block` level.
