### ISSUE TITLE
v4 Tooltips not initializing

### ISSUE THREAD

**Issue by alijaffar** [twbs/bootstrap#18598]
Using the data-toggle attribute, set to "tooltip" and with it initialized on DOM ready, tooltip fails to initialize.
Why?
`
data-toggle="tooltip" title="Test"
`
`
		$(function(){
			$('[data-toggle="tooltip"]').tooltip();
		});
`

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by alijaffar** [comment]
https://jsfiddle.net/6hs6ce0k/

Note: I'm using the v4-alpha CSS with the alpha-2 JS, but I used the same versions of v4-alpha and alpha-2 with the same exact problem.

**Comment by Johann-S** [comment]
To use Tooltips you have to include Tether : See http://v4-alpha.getbootstrap.com/components/tooltips/#overview

**Comment by cvrebert** [comment]
@alijaffar Read the JavaScript error console:
> Refused to execute script from 'https://github.com/twbs/bootstrap/raw/v4.0.0-alpha.2/dist/js/bootstrap.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

You can't hotlink scripts from GitHub.

**Comment by alijaffar** [comment]
Excellent, thanks for the info guys. I included tether.min.js before BS as the docs specify and it initialized.
