### ISSUE TITLE
Switching out bold descriptive value weights with numerical 700 values

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#18605]
What’s the reasoning for all the use of the `bold !default;`keyword value throughout `_variables.scss`/`variables.less`? 
```$label-font-weight:           bold !default;```

Shouldn’t this be a numerical weight value for consistency? like `weight: 700;`?

Maybe i’m nuts, but this would allow for easier overrides of an `h1` css selector's weight for example.

**Comment by guylepage3** [comment]
I'll create a pull request for this in a little bit.

**Comment by mdo** [comment]
What's the consistency issue?

**Comment by guylepage3** [comment]
having a descriptive value font-weight ie. "bold" as opposed to a numerical value ie. "700". By switching the weight value to be a numerical value from bold, it allows for an easier overwrite down the line. All browsers that bootstrap supports now recognize the numerical value 700.

**Comment by mdo** [comment]
Sorry, but I don't see much of an improvement to customization here from using numbers over keywords. Sure browsers support them, but that's irrelevant to the most common approaches to styling text—"make it bold", "italicize that", etc. Until you get into custom web fonts, the specific numerical values don't have a huge impact on folks using and customizing Bootstrap (and then that's a whole other problem).

Thanks though!
