### ISSUE TITLE
Floated button is vertically misaligned with .input-group in form if we use 14 px as default font size

### ISSUE THREAD

**Issue by jack-fdrv** [twbs/bootstrap#18607]
I recompile bootstrap css with default font size - 14 pixels

<img width="352" alt="321" src="https://cloud.githubusercontent.com/assets/4230282/11910872/9fb8f028-a60b-11e5-9fd8-d7c13c165259.png">

It's changed only html styles
<img width="352" alt="21" src="https://cloud.githubusercontent.com/assets/4230282/11910875/b628c05e-a60b-11e5-971f-6ecf37903542.png">

So I've emulated it in jsBin with overwritten html font size.
The problem that the button now has 1pix space at top. So it looks ugly and misaligned with left inputs and .input-group-addon.
<img width="245" alt="31" src="https://cloud.githubusercontent.com/assets/4230282/11910882/ecdf8c72-a60b-11e5-96a9-42e65cde1f1f.png">

jsBin https://jsbin.com/behimohuga/edit?html,css,output

**Comment by twbs-lmvtfy** [comment]
Hi @jack-fdrv!

You appear to have posted a live example (https://jsbin.com/behimohuga/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bassjobsen** [comment]
@jack-fdrv which browser give you this issue? Because of i can NOT confirm your issue for both FF and Chrome. For the form elements and the button the box model will look like that shown below:
![box](https://cloud.githubusercontent.com/assets/954055/11915000/e50e17ba-a693-11e5-9c61-026fc084be4c.png)
The above box-model seems right for me.

**Comment by jack-fdrv** [comment]
Chrome (last) 47.0.2526.106 (64-bit)

**Comment by jack-fdrv** [comment]
Hello?

**Comment by patrickhlauke** [comment]
There are 300 issues and 120 PRs currently on this project...so you may not immediately get an answer/resolution to your particular problem. No need to "ping" your issue...we'll get to it ;)

**Comment by jack-fdrv** [comment]
Sry, ok, I've thought you need any more help =)

**Comment by mdo** [comment]
This is due to the computed padding changes. That button has a computed height of `33.5px` and is sitting down 1px due to the rounding error.

**Comment by mdo** [comment]
Fix coming with improved math in #19121.

**Comment by mdo** [comment]
Merged #19121, so closing. Please be aware, however, that similar things can happen when you change the root font size. There's no guaranteed fix for this kind of stuff, especially across all browsers.
