### ISSUE TITLE
tether dependancy throws errors, even without opting-in to tooltips

### ISSUE THREAD

**Issue by lotap** [twbs/bootstrap#18603]
When my assets are precompiled, the tether dependency is added regardless of whether I opt-in to tooltips or not. (Running bootstrap via the gem on Rails 4.2.4 on Heroku.) This causes all of my js to fail unless I explicitly require tether. See https://github.com/twbs/bootstrap/issues/17273

This did not seem to be an issue on alpha-v1.

**Comment by cvrebert** [comment]
Please file an issue on https://github.com/twbs/bootstrap-rubygem/issues
Thanks.
