### ISSUE TITLE
hide class missing in alerts?

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#18601]
&lt;div class="alert hide alert-success" is not working in V4 alpha.2.

**Comment by fchiumeo** [comment]
Migration docs - [Responsive utilities](http://v4-alpha.getbootstrap.com/migration/#responsive-utilities)

**Comment by bhutaninitin** [comment]
Got it. Thanks.

**Comment by cvrebert** [comment]
@fchiumeo Nice work :smile:
