### ISSUE TITLE
v4 Tooltip/Popover auto-placement left/right, then top/bottom

### ISSUE THREAD

**Issue by quasipickle** [twbs/bootstrap#18604]
I think it would be advantageous if the "auto" positioning algorithm checked all 4 directions, rather than just 2.  Right now, if I set a popover's placement to "auto right" and the element is on the right side of the page, then the popover will be positioned to the left of the element.  However, if my element is 100% width, i.e. on both the left and right edges of the screen, the popover appears off screen.  If the algorithm were to notice that, then check the "top" and "bottom" position, it would ensure the popover was visible if at all possible.

I realize I can write my own positioning function - but I thought this could be baked in.

**Comment by mdo** [comment]
Is this a limitation of Tether? Curious if it's something we need to investigate or if we punt on it if it's not supported there.

**Comment by mdo** [comment]
Closing since our `auto` placement is no more. #19796
