### ISSUE TITLE
panel-title to card-title migration docs

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#18619]
According to the migration docs for Bootstrap 4, `.panel-title` has been replaced with `.card-title`, however I think that's misleading because both classes have a different usage case. `.panel-title` was ment to be used within a `.panel-heading` (which was replaced with `.card-header`), whereas `.card-title` is - according to the docs - supposed to be used within a `.card-block` (the `.panel-body` replacement). Using `.card-title` within a `.card-header` gives unexpected results. It isn't a replacement, just a new element what a similar name but a totally different usage case. As it stands now, `.panel-title` is replaced with `<h3 class="card-header">`.

**Comment by cvrebert** [comment]
Thanks! Fixed by #18624.
