### ISSUE TITLE
Conflicted class .hidden when include Modernizr 3.2 - [hidden] Attribute

### ISSUE THREAD

**Issue by claudchan** [twbs/bootstrap#18628]
There is a conflicted class .hidden when include Modernizr 3.2.

**Comment by cvrebert** [comment]
* We don't support third-party libraries such as Modernizr.
* We cannot remove `.hidden` in Bootstrap v3 because this would break backward-compatibility.
* The `.hidden` class is already being removed in Bootstrap v4: http://v4-alpha.getbootstrap.com/migration/#misc-notes-to-prioritize
