### ISSUE TITLE
create submenu in nav 

### ISSUE THREAD

**Issue by vahidalvandi** [twbs/bootstrap#18620]
why in bootsrap 4 can't create sub menu in nav ??

**Comment by kkirsche** [comment]
This has been talked about in the past (eg #424) and @mdo felt it was a bad design pattern. Personally, I agree with this sentiment. With that said, I'm sure a third party will create an extension for this once V4 is production ready.

**Comment by vahidalvandi** [comment]
very thanks

**Comment by vahidalvandi** [comment]
this not for bootstrap 4

**Comment by kkirsche** [comment]
I am aware of that @vahidalvandi. To my knowledge @mdo's stance hasn't changed:

It was closed in V4: #17408
Closed during V3: #16387

and in general is something that he has not wavered on.
