### ISSUE TITLE
Lint for unused SCSS variables

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18623]
See:
- http://blog.gospodarets.com/finding_unused_scss_variables/
- https://gist.github.com/badsyntax/6193491

v4 currently (as of d756e12f7837aff41f279e25f4b280aae5630d5c) has several unused variables:

```
$enable-gradients
$font-family-serif
$font-size-xs
$line-height-computed
$nav-link-hover-bg
$nav-pills-active-link-hover-bg
$nav-pills-active-link-hover-color
$nav-tabs-justified-active-link-border-color
$nav-tabs-justified-link-border-color
$navbar-dark-disabled-color
$navbar-light-disabled-color
$pre-bg
$pre-border-color
$progress-bar-bg
$progress-border-radius
```

Also, we'll need some sort of exemption system (e.g. magic comments) for variables which we don't use out of the box but are exposed for the benefit of downstream users (e.g. the many color palette vars in #18462).

**Comment by mdo** [comment]
Updated the list above to remove the pager variables (done in af1de03 btw).
