### ISSUE TITLE
Is there a way to do scrollTo in BS?

### ISSUE THREAD

**Issue by camohub** [twbs/bootstrap#18627]
Hi,
is there a way to do scrollTo little more automatic in Bootstrap? 
I mean something like this:
``` html
<button class="scrollTo" data-scrollto="target_id">scrollTo</button>
<div id="target_id">Target</div>

<script>
$( '.scrollTo' ).on('click', function() {
    var target_id = $(this).data( 'scrollto' );
    $('html,body').animate({ scrollTop: $( '#' + target_id ).offset().top });
});
</script>
```
but without that js part. Only with using **class="scrollTo"** and **data-scrollto="target_id"** attributes. It would be fine to have it. Also it could work with anchors and add #fragment to window.location. 
What do you think about it?

**Comment by cvrebert** [comment]
Thanks, but we'll pass for now.
