### ISSUE TITLE
Nested card-based accordions don't behave as expected

### ISSUE THREAD

**Issue by aimeos** [twbs/bootstrap#18632]
Accordions with nested cards don't open/close as expected: https://jsfiddle.net/6Laqymq0/

**Comment by cvrebert** [comment]
X-Ref: #18160

**Comment by cvrebert** [comment]
<img width="1004" alt="bogus" src="https://cloud.githubusercontent.com/assets/419884/11969659/fd8a784a-a8d9-11e5-8ea2-c6e4aa4d57e0.png">

**Comment by cvrebert** [comment]
/me kicks @twbs-lmvtfy back to life
https://jsfiddle.net/6Laqymq0/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/6Laqymq0/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 47, column 5 thru column 127: Attribute ```` href ```` not allowed on element ```` div ```` at this point.
* line 51, column 5 thru column 127: Attribute ```` href ```` not allowed on element ```` div ```` at this point.
* line 56, column 11 thru column 136: Attribute ```` href ```` not allowed on element ```` div ```` at this point.
* line 60, column 11 thru column 136: Attribute ```` href ```` not allowed on element ```` div ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@aimeos Please fix those.

**Comment by aimeos** [comment]
@cvrebert Makes no difference: https://fiddle.jshell.net/6Laqymq0/1/

**Comment by aimeos** [comment]
@cvrebert As an improvement, a "data-href" attribute should be used so we aren't forced to add an <a></a> tag only for the "href". It works well without the additional tag.

**Comment by cvrebert** [comment]
@aimeos The plugin already supports a `data-target` attribute for such cases.

**Comment by cvrebert** [comment]
I'm gonna say this is on-hold until we get Accordions working with Cards in the first place (#18375).
Once that's fixed, we'll recheck whether nested Card-based Accordions work properly.

**Comment by mdo** [comment]
Closing because I think #22251 addressed this? Please holler if not.
