### ISSUE TITLE
Reboot for forms causes ugly control rendering in Windows / Windows Mobile

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#18635]
A quirk on Windows and Windows Mobile: the very light styles provided by Reboot cause some unforeseen ugliness - current working hypothesis is that by mostly only setting `border-radius` most browsers (Firefox, IE11, Edge on Windows 10, and Edge on Windows 10 Mobile) flip from using some nice system-level provided form controls to having to make up their own control rendering, which then has unforeseen defaults that Reboot does not cancel out.

For comparison, here's a test http://codepen.io/patrickhlauke/pen/gPMqgd and two screenshots of the dramatic difference in rendering from just having `border-radius` present.

Here's Firefox
![untitled-1](https://cloud.githubusercontent.com/assets/895831/11969453/89a7ab72-a911-11e5-962d-62a80882e957.png)

And here's Edge on Win 10 Mobile

![wp_ss_20151223_0002](https://cloud.githubusercontent.com/assets/895831/11969457/99af955c-a911-11e5-8630-1a5229ab3bd7.png)

![wp_ss_20151223_0003](https://cloud.githubusercontent.com/assets/895831/11969456/99ad76fa-a911-11e5-9526-f2054800afcb.png)

Now, in practice, this isn't so much a problem as Bootstrap obviously defines extra things like `border` etc later on...but I wonder if Reboot itself should be extended to normalise their rendering? /cc @cvrebert @mdo

**Comment by patrickhlauke** [comment]
And related, this causes the same sort of unsightly form controls (in Edge/Win10Mob) for the notoriously difficult to style file input and for disabled checkboxes/radio buttons in form components http://v4-alpha.getbootstrap.com/components/forms/

![wp_ss_20151222_0008](https://cloud.githubusercontent.com/assets/895831/11969706/78cb2e7e-a915-11e5-9968-e10885c38716.png)

![wp_ss_20151222_0011](https://cloud.githubusercontent.com/assets/895831/11969722/9f76de1a-a915-11e5-86a8-254bdca04ae3.png)

**Comment by cvrebert** [comment]
Does adding `border-style: solid;` to the `border-radius` reset help things?

**Comment by patrickhlauke** [comment]
not fully, no. you then also have to set `border-width: 1px` and `border-color: inherit`. and that only fixes the most egregious problem with the broken-looking (most prominently in Edge/Win10Mob) borders. background color and some font choices still don't match exactly, but probably better than nothing.

**Comment by patrickhlauke** [comment]
then again, just going for the basics (maybe even adding a subtle `background: inherit` (though that seems to make it white/transparent in Firefox/Win10) may make this look slightly less crappy. will have to test a bit...

**Comment by mdo** [comment]
If we need to do `border: 1px solid`, let's do it. I don't have a newer Windows phone lying around to test though, so if anyone wants to pick that up and test, I'll happily merge.

**Comment by patrickhlauke** [comment]
Sorry, dropped the ball on this one. Will pick this up in a week or so once I'm not travelling. Wondering if, instead of adding some rule, we should instead remove some (if I can identify the minimum set of styles that work without kicking browsers into their own custom form widget rendering)

**Comment by patrickhlauke** [comment]
retesting everything on Firefox/Windows, Edge/Windows 10, Edge/Windows 10 Mobile, and it seems that at some point, reboot has changed sufficiently for the problem to disappear. http://v4-alpha.getbootstrap.com/content/reboot/#forms and http://v4-alpha.getbootstrap.com/components/forms/ all look fine (no heavy inset broken-looking border, no unsightly blue-ish background on disabled checkboxes/radio buttons/file type inputs). as such, i'm closing this...

**Comment by mdo** [comment]
May have been the switch from Normalize to all Reboot, too. Bunch of styles got redone as part of that.
