### ISSUE TITLE
Is there a visual, concise test page for Bootstrap 4?

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#18645]
I think I remember a test page for Bootstrap 2, where some of the core components were put on a single page in order to quickly assess whether they all look good. I can't find that page anymore though.

Is it still around and if not, how do Bootstrap developers test that their changes have not affected any of the components?

I'm thinking specifically in terms of rebuilding Bootstrap with a different set of variables in `_variables.scss` (or `_custom.scss`). Except for scrolling through the docs, I don't see how someone could quickly verify that everything works as it should.

If such a page or set of pages does not exist, would there be demand that I create them and submit a pull request?

**Comment by cvrebert** [comment]
> Is it still around

No.

> and if not, how do Bootstrap developers test that their changes have not affected any of the components?

As you mentioned, browsing through the docs is the current method.

> If such a page or set of pages does not exist, would there be demand that I create them and submit a pull request?

Unless it was done using Jekyll `include` macros or similar, I'd have maintainability concerns about such a page. It'd be duplicating a significant portion of the rest of our docs.

**Comment by arechsteiner** [comment]
Good point. How about something like this:

https://github.com/arechsteiner/bootstrap/commit/0467eb92fceba0377453b0f4dbe8f4b1c26a4fb3

I would group the snippets by chapter in which they appear in the documentation. This would allow to reuse them elsewhere with a single point of maintenance, allowing to create one or more test scenarios as described above.

Thoughts?

**Comment by mdo** [comment]
That kind of abstraction just makes for more complex docs construction. I see the use of a catch-all kitchen sink type page, but not in the extra partials for nearly every code snippet (of which there are hundreds).

**Comment by tinyearth** [comment]
@arechsteiner I think the closest you'll get here is in a separate repo: https://github.com/thomaspark/bootswatch

As of January 2017, there's a "4-alpha" directory in this project. The default theme page comes in handy for me: https://github.com/thomaspark/bootswatch/blob/gh-pages/4-alpha/default/index.html

**Comment by gavsiu** [comment]
@tinyearth I realized the 2nd link was missing a lot of stuff, so I ended up making my own.

I just combined the documentation and stripped out descriptions, codes, and duplicates. It ended up being a super long single page.

https://github.com/gavsiu/bootstrap-demo

**Comment by Olivia101** [comment]
@gavsiu It looks good but I'm intrigued to know what the advantages of using your demo page over the actual Bootstrap 4 documentation.

**Comment by gavsiu** [comment]
@Olivia101 I'm really only using it for Wordpress. I have a post with the code and I can apply my own styles. If you're not using Wordpress, I guess you could attach your stylesheet to the documentation.

**Comment by iatek** [comment]
This is what I use for Bootstrap 4: https://www.codeply.com/render/2yVCoASXof
