### ISSUE TITLE
.nav-tabs.nav-stacked do not render properly

### ISSUE THREAD

**Issue by ditiem** [twbs/bootstrap#18640]
They render like if they are horizontal tabs rather than "vertical tabs". I think you would need from another class like: nav-tabs-left or nav-tabs-right to determine if the tabs are on the left or right side of the tabpanel.

No idea how to add labels, but this is in v4

**Comment by bassjobsen** [comment]
i think you should use `.nav-stacked` only for pills; http://v4-alpha.getbootstrap.com/components/navs/#stacked-pills

**Comment by ditiem** [comment]
I do not know the original intention, but there are only 4 lines of CSS needed. I think it would make sense to have vertical tabs.

**Comment by kafeltz** [comment]
Is it possible to stack something in the sides? I need to relearn few concepts i think.

**Comment by cvrebert** [comment]
> I think it would make sense to have vertical tabs.

Bootstrap v3 deliberately removed all tab variations except for "horizontal, above the content". See #8922.
/fyi @mdo
