### ISSUE TITLE
Regex in Util.getSelectorFromElement is too restrictive

### ISSUE THREAD

**Issue by ditiem** [twbs/bootstrap#18641]
In this line (v4-alpha code)

tab.js: 90:       let selector  = Util.getSelectorFromElement(this._element)

decided which pane will be selected when clicking on the "tab". Inside the getSelectorFromElement, if not data-target is provided, the href attribute is inspected. In order to decide if the selector is valid, a regular expression is used.

I generated a "fake uuid" in my code and found out:

/^#[a-z]/i.test("#8828a412-2185-4d9c-9073-81272784c4a1")
returns false

/^#[a-z]/i.test("#e58329c1-e759-4661-9ae9-c33a12b8c0b6")
returns true

(the reason is that in the first selector the first character is a number rather than a letter.)

So sometimes the tab was selected and sometimes not!

An expression like /^#[a-z1-9]/i should work, but I suspect there will be more cases to take into consideration.

**Comment by ditiem** [comment]
Checked the w3 spec (I was suspecting about the _ character). See the source in http://www.w3.org/TR/CSS21/grammar.html

nmchar		[_a-z0-9-]|{nonascii}|{escape}
name		{nmchar}+
"#"{name}		{return HASH;}

So I think at least the expression mentioned in the previous comment should be:
/^#[_a-z0-9-]/i

Notice (I realized after I hit "Send comment") that we are only checking for the first character. I do not know if this was intended.

**Comment by ktmud** [comment]
There are a lot of weird cases for these IDs, and it is promised all will be fixed in v4?
https://github.com/twbs/bootstrap/pull/14789#issuecomment-60138926

**Comment by vanillajonathan** [comment]
I've also encountered this issue with the regular expression being too restrictive. It could not handle my numerical id, i.e. `#123`.

**Comment by joezcool02** [comment]
PR for this issue [Here](https://github.com/twbs/bootstrap/pull/22128)

**Comment by mdo** [comment]
Fixed by #21615.
