### ISSUE TITLE
File browser too wide on iOS/iPhone

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#18651]
Not sure if it's easily fixable, but on iOS 9.2 on my iPhone 5c the file browser http://v4-alpha.getbootstrap.com/components/forms/#file-browser is wider than the viewport.

![2015-12-23 14 00 11](https://cloud.githubusercontent.com/assets/895831/11979908/cdee6f82-a98e-11e5-9409-31632743d416.png)

**Comment by bassjobsen** [comment]
well the `.file input` selector got a `min-width` of `14rem` here: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L182

**Comment by SamHH** [comment]
Got this covered (seems an easy one), bear with me while I figure out PR.

**Comment by SamHH** [comment]
Here: https://github.com/twbs/bootstrap/pull/18716

**Comment by patrickhlauke** [comment]
:+1:

**Comment by patrickhlauke** [comment]
Closed by #18716
