### ISSUE TITLE
Empty progress bar tweaks are Firefox-only

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18658]
See https://github.com/twbs/bootstrap/blob/5cdb09231871e320c2c2210a3a03262bc78875fb/scss/_progress.scss#L49-L54
Presumably they ought to be applied to all browsers.
Or perhaps the tweaks are unnecessary.

**Comment by mdo** [comment]
Removing them entirely in d46c7ef as we no longer have them in v3 as of awhile ago.
