### ISSUE TITLE
Docs: responsive tables reflow needs some explanatory text

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#18683]
http://v4-alpha.getbootstrap.com/content/tables/#reflow

Needs some general introduction of what reflow actually does, as well as some strong-ish warning that this is only applicable to a certain type / arrangement of content (where the first "column" is actually the `<thead>`, and the other columns contain data...so effectively, a traditional table turned on its side). If devs blindly take this table and stuff their "regular" table content in there, it may lead to nonsensical structures.

**Comment by Pvanhesteren** [comment]
I have just submitted a PR to resolve this issue. Please have a look at #19408 and let me know what you think :smike:

**Comment by patrickhlauke** [comment]
:+1: thanks for picking this up and running with it...have to admit that i forgot about it...

**Comment by patrickhlauke** [comment]
Closed via #19408
