### ISSUE TITLE
documentation layout broken when compiling Bootstrap with Flexbox support

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18688]
On pages of the documentation the `.bd-content` columns is too wide due to the `div.highlight` takes full width and did not get `overflow-x: scroll`.
The page look like that shown in the figure shown beneath (on both FF and chrome):

![brokendocs](https://cloud.githubusercontent.com/assets/954055/12007668/a60677da-ac0e-11e5-9bbb-a025903c47e9.png)

According to http://stackoverflow.com/questions/12022288/how-to-keep-a-flex-item-from-overflowing-due-to-its-text fixing is possible with:

I found that the following code fixes the issue for both FF and Chrome:

    .bd-content {
       min-width: 0px;
     }

For other browsers the following code is possible needed:

    .bd-content {
      flex-shrink: 1;
      min-width: 0px;
    }

    .bd-sidebar {
      flex-grow: 1;
    }
    
Or even:

    .bd-content {
      flex-shrink: 1;
      flex-order: 1;
      min-width: 0px;
    }

    .bd-sidebar {
      flex-order: 2; 
      flex-grow: 1;
    }

**Comment by bassjobsen** [comment]
possible closes https://github.com/twbs/bootstrap/issues/18688, but should be test for other browser than FF and Chrome

**Comment by bassjobsen** [comment]
The `max-width` also solves this issue https://github.com/twbs/bootstrap/pull/17756

**Comment by mdo** [comment]
Fixed after merging #17756.
