### ISSUE TITLE
Problem with tabs plugin

### ISSUE THREAD

**Issue by AustinWinstanley** [twbs/bootstrap#18694]
Hide doesn't exist and 'Active' class isn't removed from previous links.

Previous working (now broken) code:

    $('.tab-link').mouseenter(function (e) {
        $(this).tab('show');
    });

    $('.tab-link').mouseleave(function (e) {
        $(this).tab('hide');
    });

Working Workaround code:

    $('.tab-link').mouseenter(function (e) {
        $('.tab-link').removeClass('active');
        $(this).tab('show');
    });

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by AustinWinstanley** [comment]
[Not Working (The old way in previous Bootstrap examples)](https://jsfiddle.net/9327y7f8/embedded/result/)

[Working](https://jsfiddle.net/55qgffmj/embedded/result/)

**Comment by Johann-S** [comment]
As it said on the error console tab doesn't have ``hide`` method see : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js

To hide a tab you just have to show an other one

**Comment by AustinWinstanley** [comment]
[Doesn't work to just show another. Doesn't do anything.](https://jsfiddle.net/3e648m6r/embedded/result/)

**Comment by cvrebert** [comment]
Works fine when implemented according to the docs:
https://jsfiddle.net/cvrebert/4L4ktLxy/

**Comment by nimmolo** [comment]
@cvrebert You're right, tabs do work fine when implemented exactly according to docs but i'm still trying to understand why nav classes are necessary to the markup. does tab.js need the Bootstrap nav classes? I can't see that it does when reading through the script.

It seems the Bootstrap nav classes were all @AustinWinstanley was missing, and when I add them, his jsfiddle works. Why do the nav classes make it work?

The question came up for me on a development site, I have tabs working **without** nav markup on two different pages, but on the third i'm running into the exact same behavior as his Dec. 26 jsfiddle. Without Bootstrap nav classes you can tab to Tab-2 but relatedTarget is not hidden. You can't go back to Tab-1 from Tab-2, and Tab-1 is not itself hidden when you go to Tab-2.

It does seem unexpected.

**Comment by cvrebert** [comment]
> Does tab.js need the Bootstrap nav classes?

Certainly that's the only usage which we officially support; you're on your own otherwise. We'll be relying on the nav classes more once #17754 gets fixed.
Probably the `.active` class is what's currently key here, but I'm not going to spend time tracing thru the code to verify that.

**Comment by nimmolo** [comment]
Thanks @cvrebert -
I am using an `<ol>` and tabs works once I apply @daleparkerwinston's patch for #17754
