### ISSUE TITLE
Add Alignment class changes to Migration docs

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#18701]
Issues:

1. The alignment classes changed from v3 to v4 but this change is not documented in the migration document.
2. Also the chapter was moved which makes it very hard to find. In v3-docs it was [a sub-chapter in "typography"](http://getbootstrap.com/css/#type-alignment), in v4 it is [hidden in "utilities"](http://v4-alpha.getbootstrap.com/components/utilities/#text-alignment).

This should be changed IMHO:
- extend [the migration file](http://v4-alpha.getbootstrap.com/migration/) to reflect the different syntax for the text-* helper
- btw, the same goes for the changes to the push/pull helper [which where documented before](https://github.com/twbs/bootstrap/commit/a8dc4812a49d8467e8642abb510b523a9a51cd48#diff-c2ec3a9f63de0b91b7bb532c0befc6cdR131) but this documentation was remove later apparently
- move the text-alignment back [in the typography section](http://v4-alpha.getbootstrap.com/content/typography/) of the documentation, where one would naturally search for it and where it has been above. In other word: Don't let the css-file-structure dictate a good information architecture in the docs (which I believe it does ATM).

**Comment by mdo** [comment]
No plans to reorganize things just yet. Going to wait and see how folks feel about the current structure more and react after hearing more feedback if it comes in. That said, I did add a cross reference to the type docs in 27ba4be to address some find-ability issues and also added some basic migration docs in 856e217.
