### ISSUE TITLE
Improve Migration Doc for .help-block and .form-group

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#18705]
I could not find those things in the migration doc but I think they should be added:

- ".help-block" the change is documented at http://v4-alpha.getbootstrap.com/components/forms/#help-text but should be documented here as well.

- Section Forms: I don't understand this sentence: ".form-group no longer mixins the .row class, so it’s now required for grid layouts.". What exactly is "mixins" and what exactly should I change in my form html?

**Comment by cvrebert** [comment]
> What exactly is "mixins"

See http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins
Using "mixes-in" might be clearer in that sentence.

> what exactly should I change in my form html?

`class="form-group"` should be changed to `class="form-group row"`

**Comment by mdo** [comment]
Migration docs improved in fea7feb.
