### ISSUE TITLE
container-fixed mixin does not apply clearfix without utilities.less

### ISSUE THREAD

**Issue by zgmnkv** [twbs/bootstrap#18718]
Hi guys,
I noticed a small issue:
I want to separate my own styles from bootstrap styles in resulting css, so I created 2 files:

libs.less:
```
@import "bootstrap/less/bootstrap";
```

styles.less:
```
@import "bootstrap/less/variables";
@import "bootstrap/less/mixins";

.my-container {
  .container-fixed();
  /* other styles */
}
```

But I noticed that in css `.my-container` class doesn't contain clearfix styles.
`.container-fixed` mixin includes `&:extend(.clearfix all);` style, so it uses `.clearfix` class from `utilities.less`, not `.clearfix()` mixin from `mixins/clearfix.less`, so I don't get clearfix styles because I don't import `utilities.less`.

Am I correct with my expectation that importing just mixins and variables will do what I want? Or is it just wrong way?
Thanks

**Comment by bassjobsen** [comment]
it only works when you explicit call the `clearfix` mixin:
    @import "bootstrap-master/less/variables";
    @import "bootstrap-master/less/mixins";

    .my-container {
      .container-fixed();
      .clearfix();
      /* other styles */
    }

The issue you describe will be fixed in BS4. BS4 uses Sass in stead of Less and enable you to use the following SCSS code:

    @import "bootstrap/scss/variables";
    @import "bootstrap/scss/mixins";

    .my-container {
        @include make-container();
    }

**Comment by zgmnkv** [comment]
Any chance this will be fixed in BS3? Maybe we can use `.clearfix()` instead of `&:extend(.clearfix all);` in `.container-fixed` mixin?

**Comment by bassjobsen** [comment]
see: https://github.com/twbs/bootstrap#contributing
>Bootstrap v3 is now closed off to new features. It has gone into maintenance mode so that we can focus our efforts on Bootstrap v4, the future of the framework. Pull requests which add new features (rather than fix bugs) should target Bootstrap v4 (the v4-dev git branch) instead.

**Comment by mdo** [comment]
I don't anticipate us making any changes here, so you'll probably have to work around the Less issue for the time being. Sorry <3.
