### ISSUE TITLE
Some letters are being cutoff in headers with overflow: hidden

### ISSUE THREAD

**Issue by lipis** [twbs/bootstrap#18714]
https://jsfiddle.net/t3n7x8fh/

<img width="596" alt="screen shot 2015-12-29 at 00 27 27" src="https://cloud.githubusercontent.com/assets/125676/12026509/fec308b0-adc2-11e5-8b31-c015dd5114d4.png">

**Comment by bassjobsen** [comment]
see also: http://stackoverflow.com/questions/10182336/text-cropping-when-using-overflow-hidden
try:

    h1, h2, h3, h4, h5, h6 {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis; 
      line-height: normal; 
    }

**Comment by lipis** [comment]
:dancer: :+1:

**Comment by mdo** [comment]
Alternatively try specifying `overflow-x: hidden` and that might help.

**Comment by cvrebert** [comment]
Please use StackOverflow rather than this issue tracker for such customization questions in the future. See https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md#using-the-issue-tracker . Thanks.

**Comment by lipis** [comment]
@mdo `overflow-x: hidden` is not working https://jsfiddle.net/gr81L1gx/

@cvrebert I think it's more of an _issue_ for an existing mixin.. https://github.com/twbs/bootstrap/blob/master/less/mixins/text-overflow.less and maybe the line height should be fixed in general as it _looks_ like it's smaller and maybe the problem is not visible without the overflow..

**Comment by patrickhlauke** [comment]
however, it's generally considered good practice for headings to reduce line height, as it's otherwise too excessive by default...
