### ISSUE TITLE
docs' SCSS code does not pass the linter

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18710]
docs/assets/scss/_ads.scss:11 [W] PropertySortOrder: Properties should be ordered width, height, padding, margin, overflow, font-family, font-size, line-height, color, text-align, background, border
docs/assets/scss/_ads.scss:52 [W] IdSelector: Avoid using id selectors
docs/assets/scss/_anchor.scss:13 [W] PropertySortOrder: Properties should be ordered opacity, -o-transition, -webkit-transition, transition
docs/assets/scss/_anchor.scss:13 [W] VendorPrefix: Avoid vendor prefixes.
docs/assets/scss/_anchor.scss:14 [W] Indentation: Line should be indented 2 spaces, but was indented 7 spaces
docs/assets/scss/_anchor.scss:14 [W] VendorPrefix: Avoid vendor prefixes.
docs/assets/scss/_anchor.scss:15 [W] Indentation: Line should be indented 2 spaces, but was indented 10 spaces
docs/assets/scss/_buttons.scss:14 [W] SpaceAfterPropertyColon: Colon after property should be followed by at least one space
docs/assets/scss/_component-examples.scss:26 [W] PropertySortOrder: Properties should be ordered min-width, max-width, margin-right, margin-left
docs/assets/scss/_component-examples.scss:70 [W] PropertySortOrder: Properties should be ordered padding, margin-right, margin-bottom, margin-left, border-width

and so on

**Comment by cvrebert** [comment]
Fixed by #18752.
