### ISSUE TITLE
Security Compliance Question

### ISSUE THREAD

**Issue by tschock** [twbs/bootstrap#18719]
We are currently looking at using Bootstrap for current and future sites that contain sensitive customer information (PCI, SOC, HIPAA, etc...).  In order for us to use this open source framework we need to establish maintenance plans that cover what needs to be done when security issues a rise (ex. What needs to happen if our security scans detect a vulnerability in the open source framework.).  

What are your recommendations for going about this?  How have you dealt with security concerns in the past?

**Comment by mdo** [comment]
> What are your recommendations for going about this? How have you dealt with security concerns in the past?

Honestly, no idea. We've not had to deal with it at all to date. Security issues—the only one I can think of is potential XSS vulnerabilities—are tackled like anything else with an open issue here.

**Comment by cvrebert** [comment]
Compare: http://emberjs.com/security/
(Keep in mind that Ember has corporate backing; Bootstrap currently doesn't.)

**Comment by mdo** [comment]
Closing out as stale. For any specific security questions, pinging members of the core team directly is the best course of action.
