### ISSUE TITLE
.has-error does not work for button group

### ISSUE THREAD

**Issue by bhantol** [twbs/bootstrap#18712]
The workaround is 

```
.has-error .btn-group > .btn {
  border-color: #883333;
}
```

**Comment by cvrebert** [comment]
@bhantol What's your use case for a button group having an error?
The only one I can come up with is [using a `.btn-group` as checkboxes/radios](http://getbootstrap.com/javascript/#buttons-checkbox-radio) and the user's (lack of) selected option(s) being invalid.

**Comment by mdo** [comment]
Changing the borders for buttons isn't likely going to happen, especially in v3 (no major changes like this are coming to the v3 version). Mixing border colors on colored buttons is just going to be confusing.

**Comment by bhantol** [comment]
So what is the alternative we have to indicate that radio buttons using button groups are invalid ?
