### ISSUE TITLE
bs-callout

### ISSUE THREAD

**Issue by AndreLGava** [twbs/bootstrap#18723]
Bootstrap uses bs-callout in its documentation, we coud have a class for this in native bootstrap as this
http://cpratt.co/twitter-bootstrap-callout-css-styles/ but on top, right and bottom too, yea?

**Comment by mdo** [comment]
Not going to be added to the core—that's docs only. This has also been asked previously, so few free to search for more context or prior replies if you'd like <3.

**Comment by cvrebert** [comment]
Duplicate of #9938. Please search more in the future.

**Comment by hugolpz** [comment]
As I saw it on the documentation, see it as usefull (the bootstrap team too apparently), I indeed expected it to be documented and in bootstrap.
