### ISSUE TITLE
process-steps component

### ISSUE THREAD

**Issue by AndreLGava** [twbs/bootstrap#18722]
we could have a new component of process like this? http://bootsnipp.com/snippets/featured/process-steps as simple for pages process and in a detailed page something like this?
http://bootsnipp.com/snippets/featured/content-in-bootstrap-tabs

**Comment by mdo** [comment]
We'll pass. I don't see it as something that's of huge value for us to build. Plus these things tend to be super different depending on the overall page design.

**Comment by cvrebert** [comment]
Duplicate of #1982.
