### ISSUE TITLE
btn-outline

### ISSUE THREAD

**Issue by AndreLGava** [twbs/bootstrap#18724]
Bootstrap uses this http://bootsnipp.com/snippets/featured/bootstrap-outline-buttons in the documentation, we could have this classes on core as alternatives to the standard buttons?

**Comment by mdo** [comment]
Coming in v4.

**Comment by AndreLGava** [comment]
Thank you mdo, I really love bootstrap, I want to use bootstrap 4 as soon as possible, thanks for solving my doubts

**Comment by cvrebert** [comment]
Gratuitous link: http://v4-alpha.getbootstrap.com/components/buttons/#outline-buttons
