### ISSUE TITLE
npm install bootstrap@4 not work

### ISSUE THREAD

**Issue by AndreaLombardo** [twbs/bootstrap#18728]
Hi guys, i'm tried to use 
```
npm install bootstrap@4
```
As mentioned in the quick start section:
https://github.com/twbs/bootstrap/tree/v4-dev#quick-start

But not worked for me.
Instead I've got the message:
```npm
npm ERR! No compatible version found: bootstrap@4
npm ERR! Valid install targets:
npm ERR! 4.0.0-alpha.2, 3.3.6, 3.3.5, 3.3.4, 3.3.2, 3.3.1, 3.3.0, 3.2.0, 3.1.1, 0.0.2, 0.0.1
```
It's case to update your Quick Start section or there is something wrong in my npm installation?
Thanks!

**Comment by wolfy1339** [comment]
Nothing is wrong with npm, it's the quick start section that is just in advance. When v4 will get released, you will be able t use that command

**Comment by AndreaLombardo** [comment]
Oh thanks!

**Comment by cvrebert** [comment]
Fixed in cd74e2db2ead7ce76186e0cd5e16bddfc886eedf. Thanks.

**Comment by ronnyandre** [comment]
`npm install bootstrap@4.0.0-alpha.2`
Didn't work here. Do I have wrong npm version or anything?

**Comment by cvrebert** [comment]
@ronnyandre Unable to reproduce:
```
~/code/scratch $ rm -r ~/.npm/bootstrap/
~/code/scratch $ npm install bootstrap@4.0.0-alpha.2
scratch@1.0.0 /Users/chris/code/scratch
└── bootstrap@4.0.0-alpha.2 

~/code/scratch $ ls node_modules/bootstrap/
CHANGELOG.md Gruntfile.js LICENSE      README.md    dist         grunt        package.json scss
 ~/code/scratch $ 
```
Try asking on StackOverflow or one of [the other community forums](https://github.com/twbs/bootstrap#community) for troubleshooting help.
