### ISSUE TITLE
iPad Pro Landscape rendering bug for dropdown menu in .navbar-fixed-top 

### ISSUE THREAD

**Issue by deadend5001** [twbs/bootstrap#18738]
I am struggling with the iPad Pro testing. The navbar (aka top menu) doesn't seem to want to cooperate and it seems related to only the iPad Pro...the iPad 2, 4 and Air 2 all work perfectly. I've also tried testing on an Kindle fire and that worked too. The screenshot attached is what happens to the menu when you tap it. 

Any advise is much appreciated on how to fix this.

NOTE: this seems to be only related to navbar-fixed-top. The navbar-static-top seems to work OK.

Here's the jsbin link to the source that I've tested is not working with the iPad Pro on Safari or Chrome: https://jsbin.com/dufozatiwi/1/edit?html

![img_5038](https://cloud.githubusercontent.com/assets/1420431/12069278/43032162-aff4-11e5-8b1a-4e97531b5857.JPG)

**Comment by kkirsche** [comment]
Can you post your example on a site like JSBin for us to 
Analyze / debug?

**Comment by deadend5001** [comment]
Just updated the top ticket with the info you asked for.

**Comment by cvrebert** [comment]
Reposting to trigger validator: https://jsbin.com/dufozatiwi/1/edit?html

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/dufozatiwi/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 13, column 1 thru column 49: Using the ```` meta ```` element to specify the document-wide default language is obsolete. Consider specifying the language on the root element instead.
* line 15, column 1 thru column 45: Bad value ```` pragma ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 16, column 1 thru column 52: Bad value ```` cache-control ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 17, column 1 thru column 39: Bad value ```` expires ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 21, column 1 thru column 208: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 30, column 1 thru column 190: Attribute ```` integrity ```` not allowed on element ```` script ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
(The `integrity` false positives are due to https://github.com/validator/validator/issues/151)
Tweaked example: https://jsbin.com/vajuqasibi/edit?html

**Comment by cvrebert** [comment]
@deadend5001 Were you pinch-zoomed-in at all when you took that screenshot? What version of iOS are you running?

**Comment by deadend5001** [comment]
@cvrebert I'm running the latest iOS 9.2

**Comment by deadend5001** [comment]
@cvrebert I just tried https://jsbin.com/vajuqasibi/edit?html and it still has the same behavior

**Comment by deadend5001** [comment]
@cvrebert 100% not using pinch-zoomed. Just loaded the page and tapped the menu.

**Comment by cvrebert** [comment]
@deadend5001 Are you able to reproduce this in the iPad Pro Simulator in Xcode?

**Comment by deadend5001** [comment]
@cvrebert just tested on the simulator as you stated using the iPad pro as the device and yes it's the same behavior.

**Comment by cvrebert** [comment]
@deadend5001 I couldn't seem to repro in the simulator. Could you give step-by-step instructions to reproduce the problem? Given #14603, I'm prepared to believe there is such a similar bug, but unless I can repro it, I can't report it upstream to WebKit.

**Comment by deadend5001** [comment]
Yes #14603 looks to be the exact same as this. If you look at their animated gif or whatever the visual is its the same steps I am doing. I open the simulator, I open safari, I type in url, it comes up. I click right most menu, I click menu to left of the one I click and keep going left clicking menus and it causes the image I showed you.

**Comment by deadend5001** [comment]
Strange they are saying its fixed with pull request https://github.com/twbs/bootstrap/pull/14667 but I am using bootstrap 3.3.6 and it's definitely there...

**Comment by cvrebert** [comment]
> Yes #14603 looks to be the exact same as this.

#14603 involved zooming; your bug doesn't.

**Comment by cvrebert** [comment]
I can't reproduce:
![ipadpro](https://cloud.githubusercontent.com/assets/419884/12070114/5e19ba12-b015-11e5-8472-99c3a8f96bdc.gif)

@twbs/team Anyone able to reproduce this on either the Simulator or a physical iPad Pro?

**Comment by deadend5001** [comment]
@cvrebert did you try landscape mode? It looks like you are using portrait.

**Comment by patrickhlauke** [comment]
confirming on simulator / ipad pro in landscape

![screen shot 2016-01-01 at 18 44 23](https://cloud.githubusercontent.com/assets/895831/12071821/e34e1f64-b0b7-11e5-9bd7-0b89d08011fc.png)

**Comment by cvrebert** [comment]
Confirmed for me too after switching to Landscape.

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=152637

**Comment by cvrebert** [comment]
Filed Apple Safari Radar: http://openradar.appspot.com/24030853

**Comment by cvrebert** [comment]
We've reported the bug upstream and listed it on our [Wall of Browser Bugs](http://getbootstrap.com/browser-bugs/). Given the nature of this bug, it's not feasible to work around it, so there's nothing more we can do here. The ball is in Apple's court now.

**Comment by deadend5001** [comment]
Thanks for the follow-up. Glad it's found but a little sad it's on apple's side because that means it could take a long time to get fixed...

**Comment by coliff** [comment]
FYI; This bug appears to be fixed as of iOS 12. Tested on iPad Pro 12.9" on Browserstack.

Can reproduce the issue on iOS 11.
![image](https://user-images.githubusercontent.com/1212885/60778228-10fe7a00-a171-11e9-88ea-43d3aa17f148.png)

Fixed in iOS 12:
![image](https://user-images.githubusercontent.com/1212885/60778196-ee6c6100-a170-11e9-925b-4476f5c30cf7.png)
