### ISSUE TITLE
Breadcrumbs :hover showing underline under separator when using <div> instead of list

### ISSUE THREAD

**Issue by TortleWortle** [twbs/bootstrap#18733]
Showing underline under a seperator
<img src="https://scrshot.eu/s/41a219e.png" />

**Comment by patrickhlauke** [comment]
In what browser/OS?

**Comment by bassjobsen** [comment]
possible related http://stackoverflow.com/questions/8820286/how-to-remove-only-underline-from-abefore

**Comment by TortleWortle** [comment]
@patrickhlauke, Mac os x 10.11.1, Google chrome Version 47.0.2526.106 (64-bit)

**Comment by bassjobsen** [comment]
chrome Version 46.0.2490.86 (64-bit) under Linux does not show the issue. @TortleWortle can you also add your HTML?

**Comment by patrickhlauke** [comment]
confirmed for the "hey look, no list markup" example from https://github.com/twbs/bootstrap/pull/18474 (which i'm admittedly not a big fan of)

**Comment by chicheng** [comment]
@cvrebert This issue was already closed by #18789 ?

**Comment by cvrebert** [comment]
Indeed.
