### ISSUE TITLE
Bootstrap button dropdowns windows 10 chrome/opera issue?

### ISSUE THREAD

**Issue by jmanden** [twbs/bootstrap#18730]
Take a look at: http://getbootstrap.com/components/#btn-dropdowns and try the dropdown buttons under win 10 chrome browser. I experience generel problems with bootstrap dropdown menus in windows 10 chrome/opera browser (no problem in win 7/8 with all browsers) - clicking a dropdown button renders other buttons inactive. Does anyone else experience the same problems? Anyone know why this button behaviour is present under win 10?

Best regards

**Comment by patrickhlauke** [comment]
can't reproduce on chrome nor opera in windows 10,  i'm afraid
