### ISSUE TITLE
`Bootstrap tooltips require Tether` error is logged to console when not using tooltips

### ISSUE THREAD

**Issue by KevinGrandon** [twbs/bootstrap#18732]
Version: 4.0.0-alpha.2

I am not using tooltips, but see the following error being logged to the console:
```
Uncaught Error: Bootstrap tooltips require Tether
```

I would expect that this should only be logged if I'm actually using tooltips.

**Comment by cvrebert** [comment]
We prefer to error out early rather than later if required dependencies are missing.
If you're not using Bootstrap tooltips and don't want to include Tether, then you'll need to exclude Bootstrap's `tooltip.js` (which may mean not using the default concatenated `bootstrap[.min].js` file).

**Comment by KevinGrandon** [comment]
@cvrebert Thanks for the info - do you know if there is a package of bootstrap without tooltip.js included on BootstrapCDN? If not it feels like that would be nice to add.

This feels like a developer paper-cut and a step backwards from previous bootstrap versions. Might be solvable with the right messaging though.

**Comment by kybishop** [comment]
+1 on KevinGrandon's comment

**Comment by cvrebert** [comment]
> do you know if there is a package of bootstrap without tooltip.js included on BootstrapCDN?

To my knowledge, there is not. You'd have to take that up with https://github.com/MaxCDN/bootstrap-cdn/issues

> This feels like a developer paper-cut and a step backwards from previous bootstrap versions.

We've already done the same thing with jQuery in Bootstrap v3 for ages. It's saved much debugging time and grief.

**Comment by synth** [comment]
Jquery is a foundational library; it makes sense to error out if a foundational required dependency is missing.

Is Tether considered to be a required dependency? Seems so from the error, or at least its a default/opt-out dependency. I vote for it to be an opt-in dependency. However, if the majority opinion is for it to be required/opt-out, then improvement in documentation would be welcome as tether is not mentioned on this repo's README nor the bootstrap Getting Started documentation.

**Comment by cvrebert** [comment]
> tether is not mentioned on this repo's README

To be fair, the README doesn't mention jQuery either.

> nor the bootstrap Getting Started documentation.

That's been fixed by #18666.

**Comment by synth** [comment]
again, jquery:foundational; tether:not-so-much

in any case: :+1:

**Comment by jgacuca567** [comment]
@cverbert, Tether, should be included in the (http://v4-alpha.getbootstrap.com/getting-started/introduction/) example page as well

**Comment by alvinchevolleaux** [comment]
Why is Tether not included in Bower dependencies if it throws an error on the default distribution?

**Comment by cvrebert** [comment]
@alvinchevolleaux It's been added to the dependencies; see #18575.

**Comment by alvinchevolleaux** [comment]
@cvrebert Thanks for the info, I didn't realise it was already flagged.

**Comment by sky-coding** [comment]
Why do we have a straight `if (window.Tether === undefined)` check when both libraries are commonjs/amd "compliant"? It's going to break for anyone using a module loader.

**Comment by mrbtec** [comment]
Solution
https://stackoverflow.com/questions/47431612/using-bootstrap-4-with-angular-4
