### ISSUE TITLE
add min-width to container

### ISSUE THREAD

**Issue by Nemo64** [twbs/bootstrap#18746]
The grid can currently be pushed to 1px width. This probably does not happen in the wild and can only be accomplished using dev tools, however it probably wouldn't hurt to define an absolute minimum size for the grid system so that it is impossible to get an untested broken layout because the viewport width was too small.

I suggest 320px min-width on the container as this is the width of the iphone <= 5. Also, according to [these stats](http://gs.statcounter.com/#all-resolution-ww-monthly-201412-201511), there is nothing smaller.

**Comment by cvrebert** [comment]
X-Ref: #10513, #13221

> [These docs](http://developer.android.com/guide/practices/screens_support.html) and [this SO entry](http://stackoverflow.com/questions/4519605/minimum-screen-resolution-for-android-devices) suggest that 240x320 physical px [as opposed to CSS px] is the de facto minimum Android screen size. (Although this neglects market share considerations, etc.)

**Comment by Nemo64** [comment]
There is even a [browser for android wear out there](https://play.google.com/store/apps/details?id=com.appfour.wearbrowser&hl=de). I don't know how relevant those smaller screen sizes are. My idea is: if a site isn't optimized for these screens they'll look broken. With a min-width in place there will have to scroll horizontally but the layout would probably be fine.

**Comment by patrickhlauke** [comment]
browser/OS/device manufacturers set their ideal viewport (what you get when doing `width=device-width`) to whatever they think gives them/their users the most comfortable experience. they also (generally) don't release a borwser/OS/device which would make a large portion of sites look immediately unusable and broken. with that in mind, i'd be against defining a minimum width - once below a certain size sure, drop to single column. beyond that, i'd leave it up to authors to weigh up themselves if they're happy for their designs to scale down to ever decreasing widths (provided that their stuff is fluid). if devs then DO want to make a mininum cut-off, they can add it in themselves.

**Comment by mdo** [comment]
Not going to be adding this—v3 managed without it for the last 2.5 years so should be fine :).

**Comment by pranav9196** [comment]
@mdo  I have been looking for a fix to this since the past two days and all I found is people saying that this is unrealistic and highly improbable layout usage, which is wrong, people can avoid this for sure but there should be a workaround to it.
