### ISSUE TITLE
Width of the popover is restricted to the width of the parent.(parent grid).

### ISSUE THREAD

**Issue by 1988vignesh** [twbs/bootstrap#18756]
Hi
I am using Bootstrap Version:  v3.3.4, I am calling bootstrap popover via angular custom popover.
When the target is inside the bootstrap grid structure the width of the popover is restricted to the width of the grid . Kindly help me to solve this issue. Please find the screen sort for my html structure

![bootstrap_issue](https://cloud.githubusercontent.com/assets/16542603/12093611/0306d7be-b32a-11e5-93de-364cc2b31229.png)

![image](https://cloud.githubusercontent.com/assets/16542603/12094068/91e47728-b32c-11e5-8ae0-7bcc4267f2ff.png)

**Comment by cvrebert** [comment]
* Please upgrade to Bootstrap v3.3.6
* Please post an example JS Bin or JS Fiddle that doesn't use Angular (we cannot provide help with third-party lobs such as Angular)
* Have you tried setting the `data-container="body"` option?

**Comment by 1988vignesh** [comment]
Thanks for your response it is working after replacing data-container='body'
