### ISSUE TITLE
Migrate away from Sauce Labs?

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18754]
Refs https://github.com/theintern/intern/issues/394

**Comment by mdo** [comment]
I'm down. Is this why our tests are failing for v4-dev currently? They pass locally for me.

**Comment by cvrebert** [comment]
Yes, the Sauce API seems to be experiencing issues.

**Comment by mdo** [comment]
Rough. Are there any other services we should consider if we're looking into another?

**Comment by cvrebert** [comment]
BrowserStack and TestingBot. Sounds like BrowserStack has improved a lot since when we first tried them.

**Comment by cvrebert** [comment]
Or we could setup our own tiny Selenium cluster (I'm not volunteering to be the one to do that though).

**Comment by cvrebert** [comment]
Also: https://www.browserstack.com/newsletter-chrome-on-ios

**Comment by XhmikosR** [comment]
If anyone notices any rate API limit errors, please keep the link to the build and CC me so that I pass it to Sauce Labs. We could at least ask for a plan with a bigger limit.

**Comment by Johann-S** [comment]
Closed thanks to: #27007
