### ISSUE TITLE
.input-group within navbar becomes too wide

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18751]
Resurrecting #9950, since [the alleged Chrome bug](https://code.google.com/p/chromium/issues/detail?id=309483) that was supposedly causing it turned out to be invalid; all the browsers turned out to behave the same as Chrome.

**Comment by SiteSplat** [comment]
I worked around this by applying a "btn-toolbar" to the parent element and then "form-group" to my last element and that fixed the issue under chrome.
https://gyazo.com/ed3e840d6cc73149164b9220588a3e67

**Comment by heruan** [comment]
I'm experiencing this when using a `input-group` inside a `btn-toolbar`: the `input` takes all the space and other toolbar elements wrap.

**Comment by mdo** [comment]
Should be fine according to the docs examples I have included in #19890.
