### ISSUE TITLE
Suggesting addition of _color.scss palette for better color control

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#18758]
I am suggesting the addition of an `_color.scss` file for better color control. Something like what is seen on Google Design.

In adding a color palette we would be control color in one location with a better overview of your projects colors.

Reference:
- https://www.google.com/design/spec/style/color.html#color-color-palette
- https://github.com/Dogfalo/materialize/blob/master/sass/components/_color.scss

**Comment by mdo** [comment]
#18462 :grin:.

**Comment by guylepage3** [comment]
didn't find that in my search. Thanks @mdo
