### ISSUE TITLE
data-toggle="modal" triggers modal overlay even if the id/modal is not present

### ISSUE THREAD

**Issue by sneila** [twbs/bootstrap#18764]
`<a href="#" data-toggle="modal" data-target="#MODAL" ... >Modal</a>`
the #MODAL id/element is not present in the dom, and it triggers a dark overlay.

Should check if modal/element exists and only then trigger the modal(), else ignore.

**Comment by cvrebert** [comment]
@sneila What version of Bootstrap are you using?

**Comment by sneila** [comment]
@cvrebert Indeed i was using 3.3.5. Upgraded to 3.3.6 and it does nothing now.
Yet, it is still not what i would like it to do, since it kills my href

i have:
<a href="path to actual page i'd like to load" data-toggle="modal" data-target="#MODAL" ..>Edit</a>
So if i have NO #MODAL on page, i would still like the href to trigger to load the page. Yet a preventDefault is probably no allowing it.
If #MODAL is present, the default functionality is expected.

What i am saying is that if toggle modal is on an <A> it should not steal the click event if the data-target is not present in the dom.

**Comment by patrickhlauke** [comment]
so why are you defining the trigger as being a modal trigger when there's no actual modal present?

**Comment by sneila** [comment]
well, it's fallback for when the modal is not loaded correctly in the dom, for whatever reasons, it should allow the page to actually load the page that is defined into the href.
(it's also intended for older mobile browsers that do not allow JS, in this case, i am aware there will be no preventDefault)

Think a lightbox (it's not the case here, just as an example) where it pops up a lightbox if JS is present, else it just points/loads the large image (in href).
I want to use the same view/template for both popup version as well as for "load page"

**Comment by mdo** [comment]
Closing since this is against v3 and we're not actively developing that. Did a quick check in v4 with a modal trigger and no modal; no issue.
