### ISSUE TITLE
Notes about the docs

### ISSUE THREAD

**Issue by qaisjp** [twbs/bootstrap#18767]
Sorry, I know multiple issues in threads are frowned upon but here are a few things that needed to be added to the docs

1. [x] dropdowns no longer require `li`
1. [x] `.navbar-header` no longer necessary, I think `.navbar-body` was also a thing (and is no longer necessary)
1. [x] `.card-danger`+`.card-inverse` isn't exactly the same as `.panel-danger`
1. [x] media objects in docs are moved from components to "layout"
1. [x] removal of badges aren't mentioned (`.badge` can be directly replaced by `.label .label-pill .label-default`)

**Comment by cvrebert** [comment]
> Removal of badges aren't mentioned

Already fixed in ddba80595280740b043606464dc36006f059c28c

**Comment by cvrebert** [comment]
> `.card-danger`+`.card-inverse` isn't exactly the same as `.panel-danger`

It's semantically the same, albeit visually different. Added guidance regarding more visually similar migration options in eb26e69a854ac05e3dbaef29153d2ed552c4e5ac.

**Comment by cvrebert** [comment]
> media objects in docs are moved from components to "layout"

Given that this has no impact on any code, personally I don't see the need to go into the minutiae of the reorganization of the docs.

**Comment by cvrebert** [comment]
>  I think `.navbar-body` was also a thing

Nope, it wasn't.

**Comment by cvrebert** [comment]
> `.navbar-header` no longer necessary

v4's navbars in general are still currently a work-in-progress. I added a general task to #18467 to add migration guidance though.

**Comment by cvrebert** [comment]
> dropdowns no longer require `li`

There've actually been several other additional changes to Dropdowns. Filed #18768 for this.

**Comment by cvrebert** [comment]
Core Team, if anyone disagrees regarding media objects, feel free to reopen this.

**Comment by qaisjp** [comment]
Thank you for handling this so quickly! If I have any more problems would you rather I reopen and edit my original post or create a brand new ticket?

**Comment by cvrebert** [comment]
I would rather you open a new ticket and please actually adhere to our "one issue per ticket" guideline.

**Comment by qaisjp** [comment]
Okay, sorry about that and thank you!
