### ISSUE TITLE
Allow disable buttons-checkbox-radio

### ISSUE THREAD

**Issue by yceruto** [twbs/bootstrap#18766]
Ref: http://getbootstrap.com/javascript/#buttons-checkbox-radio
```html
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Radio 1 (preselected)
  </label>
  <label class="btn btn-primary disabled">
    <input type="radio" name="options" id="option2" autocomplete="off" disabled> Radio 2
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Radio 3
  </label>
</div>
```
Option 2 is disabled but however I can select it. Live example: https://jsfiddle.net/yonelceruto/L2x9vb3o/

This is a bug?

**Comment by patrickhlauke** [comment]
that does indeed seem to be a bug.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by ryangriggs** [comment]
Just for future reference: it seems you can simulate a "disabled" state on the radio group with the following code:
`$("[radio-button-selector]").parent().on('click.disabled', function(e) { e.preventDefault(); e.stopPropagation(); });`

Then to re-enable, simply remove the event with the .off() function:
`$("[radio-button-selector]").parent().off('click.disabled');`

Hope this helps anyone else needing to do this.
