### ISSUE TITLE
Migrating from JqueryUI's Dialog to Modal

### ISSUE THREAD

**Issue by nielsnl68** [twbs/bootstrap#18773]
Hello all,
First i like to thank you for creating and maintaining the Bootstrap framework, i like it a lot.

In the past we just the JqueryUI;s Dialog a lot in our application but now we have switched over to bootstrap we want also to replace the dialog's to the modal layout. 
With the Dialog we used the option to set the buttons dynamically a lot based the content we are putting in the dialog (via an ajax call).

My question is, when i implement this into the modal widget, do you be interesting to include this into future version as well? My idea is to do let it work the same way as jQueryUI made it.

**Comment by cvrebert** [comment]
You can already accomplish such things by hooking into the events that the Modal plugin fires (or by handling the opening of the modal yourself, as opposed to using `data-toggle="modal"`); see http://getbootstrap.com/javascript/#modals-related-target
So I don't see much point in adding another feature of such limited applicability.
