### ISSUE TITLE
feature? enable application of dropdown css to a media query

### ISSUE THREAD

**Issue by ryanrain** [twbs/bootstrap#18776]
hi all, thanks for all your work!

i'm building a site with alpha.2 that will have a standard mobile menu on small screens and a dropdown on larger screens. the site will have the same markup for any screen size, so i need the .dropdown-menu etc. classes.

my issue is this: i'm needing to do some very messy resetting of the dropdown css for my mobile menu. it'd be much simpler if almost everything in _dropdown.scss could be tucked inside of a nice @include media-breakpoint-up($dropdown-min-width){} with a sensible default.

craziness?
thanks again!
-ryan

**Comment by mdo** [comment]
That'd be a bit of craziness, yeah :D. Sorry, but I don't think we'll be doing that at this point <3.
