### ISSUE TITLE
<input type="color" class="form-control"> as colorpicker is displayed badly

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18786]
When browsers such as Chrome and Firefox present a proper colorpicker UI for `<input type="color">`, if you use `.form-control` on the input, it's displayed kinda weirdly.

In Chrome, the padding scrunches the actual color swatch and makes it invisible:
<img width="789" alt="chrome" src="https://cloud.githubusercontent.com/assets/419884/12158529/9c036ebc-b48f-11e5-8932-64fde5a90870.png">

In Firefox, the height of the input doesn't match the height of `<input type="text" class="form-control">`:
<img width="483" alt="firefox" src="https://cloud.githubusercontent.com/assets/419884/12158594/16577122-b490-11e5-8b1a-d74ab993b843.png">

Safari doesn't support color inputs, so it shows a plain text input, which looks fine.
I haven't tested on IE/Edge.
CC: @mdo

**Comment by patrickhlauke** [comment]
Neither IE nor Edge currently support `type="color"`, so visually it's the same as for `type="text"`

**Comment by eliottrobson** [comment]
There's a couple of inconsistencies with heights on elements. I've managed to fix these with a few explicit height declarations which normalizes select and input heights. This also works for input type color too.

[http://www.bootply.com/NjBlSmhHNm](http://www.bootply.com/NjBlSmhHNm)

**Comment by twbs-lmvtfy** [comment]
Hi @eliottrobson!

You appear to have posted a live example (http://s.bootply.com/render/NjBlSmhHNm), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 61, column 5 thru column 95: Attribute ```` placeholder ```` is only allowed when the input type is ```` email ````, ```` number ````, ```` password ````, ```` search ````, ```` tel ````, ```` text ````, or ```` url ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by eliottrobson** [comment]
Revised: [http://www.bootply.com/NjBlSmhHNm](http://www.bootply.com/NjBlSmhHNm)

**Comment by vanillajonathan** [comment]
@patrickhlauke Edge nowadays (version 14) supports `type="color"`.

**Comment by mdo** [comment]
Agreed this needs addressing, but I don't think a fully custom (square) component like in the cross referenced PRs is the way to go. I think a modifier to accomplish something similar to that would be helpful though for the browsers that do support it.

**Comment by oktalk** [comment]
There's been a lot of back and fourth on this issue. I would suggest removing support for the `color` attribute. It's glaringly broken now, and has limited browser support. I could open a PR if desired.

You can do a bit with pseudo classes, but it's still funky. Here's a pen: https://codepen.io/oktalk/pen/BRJKYd

**Comment by gvangool** [comment]
I've resolved it in our local build by setting the same height as on `<select/>`

```scss
input[type=color].form-control {
    height: $input-height;
}
```

**Comment by rparundekar** [comment]
I fixed mine by using @gvangool's solution, but by setting the padding as 0px.

```
input[type=color].form-control {
    padding: 0px;
}
```

**Comment by MartijnCuppens** [comment]
Since #26820, a height is added to the `.form-control` which solves this problem.

**Comment by mariusa** [comment]
`height: auto` still results in the same bad display (1 thin line instead of rectangle), sometimes, with bootstrap 5, for `.form-control-color`. Screenshot (same as above)
![2021-11-30_14-34](https://user-images.githubusercontent.com/1283842/144048220-1a8b478a-0fea-4caf-8ae2-71c46bf67f1d.png)

**Comment by vanillajonathan** [comment]
https://getbootstrap.com/docs/5.1/forms/form-control/#color

**Comment by mariusa** [comment]
Exactly the same control *sometimes* shows like this. I've seen this on multiple user devices, can't figure out why:
![2021-11-30_14-59](https://user-images.githubusercontent.com/1283842/144051846-7ec62d63-453a-4f9e-9b30-fb0028915261.png)

**Comment by patrickhlauke** [comment]
well, it would be good to isolate a reduced test case (without any non-bootstrap styles in the way), and trying to pin down which browsers/operating systems/etc it happens on. "*sometimes*" is a bit too vague to try and trouble-shoot
