### ISSUE TITLE
.dropdown-toggle::after causes offset alignment in a container when used with .pull-*-right

### ISSUE THREAD

**Issue by kybishop** [twbs/bootstrap#18790]
As of alpha2, `.dropdown-toggle::after` contains `margin-right: .25rem`, which causes offset alignment if the dropdown is the last element of a container where `.pull-*right` is used on the dropdown.

Example within a navbar:
~~https://jsfiddle.net/6twft72d/~~
https://jsfiddle.net/6twft72d/12/

This is admittedly a bit nitpicky, but it looks the slightest bit off when compared to how it used to look in alpha 1.

**Comment by twbs-lmvtfy** [comment]
Hi @kybishop!

You appear to have posted a live example (https://fiddle.jshell.net/6twft72d/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 67, column 9 thru column 56: Attribute ```` disabled ```` not allowed on element ```` a ```` at this point.
* line 66, column 7 thru column 79: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@kybishop Add the JavaScript to your example please. (And fix the above errors too.)

**Comment by kybishop** [comment]
Javascript added and errors fixed https://jsfiddle.net/6twft72d/4/

**Comment by twbs-lmvtfy** [comment]
Hi @kybishop!

You appear to have posted a live example (https://fiddle.jshell.net/6twft72d/4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work
* line 62, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kybishop** [comment]
For real this time ;) https://jsfiddle.net/6twft72d/5/

**Comment by twbs-lmvtfy** [comment]
Hi @kybishop!

You appear to have posted a live example (https://fiddle.jshell.net/6twft72d/5/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 66, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
W012 doesn't apply to v4, so we can ignore that one.

**Comment by cvrebert** [comment]
jQuery needs to come before bootstrap.js. Read the JS console error message.

**Comment by kybishop** [comment]
That's what I get for trying to submit an issue on mobile. Fixed now https://jsfiddle.net/6twft72d/12/

**Comment by twbs-lmvtfy** [comment]
Hi @kybishop!

You appear to have posted a live example (https://fiddle.jshell.net/6twft72d/12/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 70, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
This is because of #17137. I need to undo that.

**Comment by mdo** [comment]
Fix coming in #18807.
