### ISSUE TITLE
Can't increase the size of glyphicon in bootstrap

### ISSUE THREAD

**Issue by RReji** [twbs/bootstrap#18791]
<span class="glyphicon glyphicon-arrow-left fa-5x"></span>

**Comment by patrickhlauke** [comment]
We'd need a bit more, like an actual test case, to see what your problem is. Fundamentally, glyphicons are simply icon fonts, so changing font size will do it...

**Comment by mdo** [comment]
As @patrickhlauke says, resizing icons is a matter of changing the `font-size`.
