### ISSUE TITLE
v3 dot caret declaration has syntax error

### ISSUE THREAD

**Issue by cigzigwon** [twbs/bootstrap#18798]
v3.3.6
line 3512: duplicate declaration for border-top and \9 is invalid, please remove the line

**Comment by cigzigwon** [comment]
More importantly, how does this happen when compiling the sass? Shouldn't have errored out?

**Comment by cigzigwon** [comment]
after lookign at line 14 in the dropdowns.less file I have concluded that the less parser is not picking up the additional chars but I've never seen this usage before ~"\9" must be "less than IE9" should the slash be there??

**Comment by cvrebert** [comment]
See http://getbootstrap.com/getting-started/#support-validators
`\9` is an intentional IE CSS hack.

**Comment by cigzigwon** [comment]
Found that out but since it was declared second it defaults to that line in Chrome and then you have now dropdown carets at all. It's not closed... I'm using Chrome Version 46.0.2490.71 (64-bit)

**Comment by cigzigwon** [comment]
Take that back. My current configuration of gulp is outdated and when it compiles to dist\ it only gets the IE hack.

**Comment by cigzigwon** [comment]
gulp-csso package .0.2.9 is deprecated so moving to 1.0.1 is the fix! Thanks for reminding me that IE8 is still a plague even tho my apps don't need to run on it ;)
