### ISSUE TITLE
What does the Preview Theme at the bottom of Aside @ getbootstrap.com do?

### ISSUE THREAD

**Issue by sandipchitale** [twbs/bootstrap#18794]
![previewtheme](https://cloud.githubusercontent.com/assets/3310939/12171693/cd7425ba-b500-11e5-8e2f-31816575bfae.png)

**Comment by wolfy1339** [comment]
It applies the gradients that were found by default in previous versions of Bootstrap

**Comment by mdo** [comment]
What @wolfy1339 said. It's only visible on some elements.

**Comment by cvrebert** [comment]
And you can apply the theme to your own site by including `bootstrap-theme.css`

**Comment by sandipchitale** [comment]
I see.

I understand you can customize the theme, download and apply the theme to my own site - but by that you probably mean my copy bootstrap documentation site - so that the Preview Theme will pick that up locally. But it probably does not make sense on the getbootstrap.com site. Unless, if the user could customize the theme on the customize page and only for their session preview their changes as applicable to the examples. Does that make sense?

IMO this will be a useful enhancement to the site.
