### ISSUE TITLE
Nav Pills Drop Down Links Not Working

### ISSUE THREAD

**Issue by jamieharrop** [twbs/bootstrap#18793]
Hello,

I'm using a drop down with nav pills. The drop down works on desktop but not on mobile. When I try to click the links in the drop down on mobile, the menu just closes and I'm not taken to the new page. 

You can see the issue at http://www.jamieharrop.com/Freelance/Customers/Dyad/theatre-productions/austens-women/ (click the "venue information" link).

I'm using Bootstrap 3.

Any help would be greatly appreciated.

Thanks!

Jamie

**Comment by mdo** [comment]
We'll need a reduced test case please (via JS Bin or JS Fiddle) to properly test.

**Comment by jamieharrop** [comment]
Hi Mark.

Sure. Here you go. http://jsfiddle.net/jamieharrop/ffzyfgps/3/

Thanks!

Jamie

**Comment by cvrebert** [comment]
As stated on http://getbootstrap.com/components/#navbar-default in bold red:
> **Justified navbar nav links are currently not supported.**

Likewise, it's not valid to combine `.nav-pills` with the normal navbar.
You're on your own as far as frankensteining such a widget together.
