### ISSUE TITLE
Borders on .table-bordered don't wrap around .table-responsive

### ISSUE THREAD

**Issue by petetnt** [twbs/bootstrap#18795]
In V4, When combining `.table-bordered` with `.table-responsive`, the borders of the table still fill the whole width instead of wrapping around the outer edge of the table.

``` html
<table class="table table-bordered table-responsive">
 /**/
</table>
```

JSBIN: http://jsbin.com/qikagupifo/edit?html,output

Also visible on docs:
![image](https://cloud.githubusercontent.com/assets/7641760/12172086/54f6e044-b557-11e5-966d-3df696a174aa.png)

**Comment by twbs-lmvtfy** [comment]
Hi @petetnt!

You appear to have posted a live example (http://jsbin.com/qikagupifo/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 10, column 3: [E027](https://github.com/twbs/bootlint/wiki/E027): `.table-responsive` is supposed to be used on the table's parent wrapper `<div>`, not on the table itself
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by petetnt** [comment]
Duh, saved by the `twbs-bot`: bordered is supposed to be on the wrapper.

**Comment by cvrebert** [comment]
Actually, that rule only applies to v3, not to v4.
Possibly related to #18612.

**Comment by petetnt** [comment]
Hmm so it seems! This occurs cross browser though (tested on Chrome47, IE11, newest FF) :mag:

**Comment by cvrebert** [comment]
Yes, we're currently waiting for mdo to clarify whether the v4 docs are wrong or whether there's some change to the CSS that he forgot to make.

**Comment by mdo** [comment]
The classes go on the `<table>`, no need for a wrapper anymore. Responsive tables will scroll horizontally if their contents expand past the available horizontal viewport space.
