### ISSUE TITLE
Checkbox/radio aligned too low

### ISSUE THREAD

**Issue by quasipickle** [twbs/bootstrap#18797]
The default checkbox/radio alignment seems to be with the bottom of it's associated label text.  To me, visually this makes the elements seem too low.  The inline variants appear to have the boxes aligned with the middle of the text, which looks better.

**Comment by mdo** [comment]
What version of Bootstrap? What browser (version and OS)? Screenshots?

**Comment by quasipickle** [comment]
Duh - right, sorry.

The v4 Alpha.  You can actually see this in the documentation on both Chrome and Firefox on OS X.

![checkboxes](https://cloud.githubusercontent.com/assets/1377105/12184232/4d9c3246-b551-11e5-9b24-25be41153e6c.png)

**Comment by quasipickle** [comment]
In practice the boxes seem to be aligned to the top:

![practice](https://cloud.githubusercontent.com/assets/1377105/12184405/4afca8bc-b552-11e5-8bbb-33fccca408b9.png)

so it looks to be a documentation/browser bug stemming from _forms.scss:193

**Comment by cvrebert** [comment]
X-Ref: #13936, #15791

**Comment by cvrebert** [comment]
Some findings:
* OS X Chrome checkbox dimensions: 28x28 (native px)
* OS X Chrome radio button dimensions: 32x32 (native px)

Currently, in bleeding-edge v4, the strikethrough line of the label text is 1 native px below the center of the checkbox/radio:
<img width="217" alt="chrome" src="https://cloud.githubusercontent.com/assets/419884/12185874/cd8fd7cc-b552-11e5-8fb1-9220daff3e1b.png">

(Strikethrough being one possible interpretation of the "vertical center" of text)

**Comment by cvrebert** [comment]
For Firefox:
* OS X Firefox checkbox dimensions: 24x24 (native px)
* OS X Firefox radio button dimensions: 28x28 (native px)

Similarly, the strikethrough line of the label text is currently 1 native px below the center of the checkbox/radio, though Firefox's strikethrough is lower than Chrome's (in a bad way):
<img width="202" alt="firefox" src="https://cloud.githubusercontent.com/assets/419884/12186223/7a09d15e-b555-11e5-8e63-88af221c27db.png">

(Guess I should find a different metric..)

**Comment by cvrebert** [comment]
For Safari:
* Safari radio button dimensions: 16x17 (native px)
* Safari checkbox dimensions: 14x15 (native px)

![safari](https://cloud.githubusercontent.com/assets/419884/12186579/14e10136-b559-11e5-8746-c4e79b4112d6.png)

**Comment by mdo** [comment]
Always bummed to find these problems, hah. Seeing it in Firefox, but not in Chrome. Going to close this as a won't fix since it's virtually impossible to get this 100% locked down across browsers. If y'all have any specific ideas for what we could try, I'm all for it though.
