### ISSUE TITLE
Definition list row extend?

### ISSUE THREAD

**Issue by cyberwombat** [twbs/bootstrap#18806]
In BS4, in the docs [example](http://v4-alpha.getbootstrap.com/content/typography/#horizontal-description) it shows columns being used. However these collapse when in a smaller div unless `row` is added to the `dl` element. Should this element inherit the `row` attributes or do the docs need to have the `row` class added?

**Comment by cvrebert** [comment]
That example is outdated as of #18669. But it still needs work; see #17969.
