### ISSUE TITLE
shown.bs.modal is not triggered

### ISSUE THREAD

**Issue by bambuk6** [twbs/bootstrap#18809]
shown.bs.modal is not triggered when modal is shown in v4-dev.

**Comment by kkirsche** [comment]
Per [Contributing.md](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md#bug-reports) please create a reduced test case and a live example. [This JS Bin](http://jsbin.com/qusafa/edit?html,output) is a helpful template.
