### ISSUE TITLE
Add a way to expose Bootstrap as only mixins/placeholders, no classes

### ISSUE THREAD

**Issue by felds** [twbs/bootstrap#18805]
In order to use bootstrap, all the code of a given module has to be present in the final CSS. In current versions, it generates a lot of collisions and the need to make up confusing names for my own classes.

## An example

If I want to use `.card` as a base for a class of my own (`@extend`ing it), the whole CSS for `.cards` would end up in the final CSS together with my implementation.

It also brings concerns regarding existing classes. eg: `.card` could be a semantically significant element in my page.

## An idea on how to solve it

Sass enables us to create silent classes, that are not expressed in the final CSS. This could be used (as an opt-in; just like the current flex-grid) to use Bootstrap as a mixin library.

Bootstrap:
```scss
// bootstrap/scss/_card.scss
%card {
  // all the declarations for .card elements (current code)
}
@if not($silent-classes) {
  .card { @extend %card }
}
```

Custom SCSS
```scss
@import "bootstrap/scss/card";

.projects {
  // class definition for the wrapper
  &__item { @extend %card }
}
```

This is not a perfect solution as it would still generate child elements with the original names (although this already happens when using mixins like `card-inverse`) and would force the user to `@extend` a lot of classes (like `.card-block` by doing a `.projects__item-content { @extend %card-block }`).

That said, as far as I can think, this would not change anything when using bootstrap as is, but it would give a lot more power for experienced developers who want to use Bootstrap together with their existing codebases.

What do you guys think about this?  
Any better ideas on how to achieve this?  
Would this change be welcome?

**Comment by felds** [comment]
@cvrebert thank you very much for rephrasing the ticket! it's much clearer now! :smile: 

Btw, any ideas on how to move forward with this?
I'm afraid it gets buried before it gets even looked at.

**Comment by mdo** [comment]
Not going to go this route, sorry. It'd be a pretty big departure from the current approach. Sorry!

**Comment by csscoderRU** [comment]
I re-wrote Bootstrap v4 grid system for my needs. Can it be useful to someone else [Bootstrap Silent Grid](https://github.com/csscoderRU/bootstrap-silent-grid)

**Comment by janwagner** [comment]
Too bad @mdo 😔

I love your approche @felds! Great idea!

My components now are looking  way. Unfortunately not with bootstrap anymore  😔
I just set silent-classes to true in every component.

```
@import "variables";
$silent-classes: true;
@import "atomic";

#header {
  @extend %display-flex;
  @extend %align-items-stretch;
  &__logo {}
  &__title {
    @extend %align-items-end;
    @extend %flex-1-0;
    &--headline {
      @include font(20px,20px);
    }
    &--subline {
      @include font(16px,16px);
    }
  }
  &__navigation {
    @extend %display-flex;
    @extend %align-items-end;
    ul {
      @extend %display-flex;
      @include listreset();
      li {
        span {
          @include font(14px,14px);
        }
      }
    }
  }
}
```

**Comment by felds** [comment]
@janwagner I'm glad it was useful to someone! <3
