### ISSUE TITLE
Use feature query for Firefox-specific <progress> styling

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18812]
Given [Firefox's relatively long-time support for feature queries](http://caniuse.com/#feat=css-featurequeries), we should be able to replace https://github.com/twbs/bootstrap/blob/48e62fdf34c6f2a0a5c559e9b5e8318b7d86e654/scss/_progress.scss#L64 with a less hacky feature query, e.g. `@supports (-moz-appearance:none) { ... }` ala http://browserhacks.com/#hack-8e9b5504d9fda44ec75169381b3c3157

**Comment by mdo** [comment]
No need for this; RIP `<progress>`. See #21473.
