### ISSUE TITLE
Migration docs don't mention .list-inline-item

### ISSUE THREAD

**Issue by planting** [twbs/bootstrap#18813]
Seems like the `.list-inline` class have been removed or stopped working in the latest alpha release. If it have been removed, is there a new utility class for horizontal lists that we can use?

**Comment by cvrebert** [comment]
It's still present and seems to be working fine: http://v4-alpha.getbootstrap.com/content/typography/#inline
Do you have an example where it's not working?

**Comment by planting** [comment]
Thanks @cvrebert, I had forgot to add `.list-inline-item` to my `<li>` tags. Don't think that was needed in Alpha1, but now it works! Thank you!

**Comment by cvrebert** [comment]
I'm going to call this a bug in the migration docs, since they don't currently mention the new `.list-inline-item` requirement.

**Comment by cvrebert** [comment]
Fixed by #20187.

**Comment by leecollings** [comment]
Just curious to know, why the need to add `list-inline-item` to every list item now?

Surely this could just be handled in CSS by using `.list-inline > li` as it was before in v3?

Seems a bit of a step backwards

**Comment by Johann-S** [comment]
@leecollings you should create a new issue about this subject and add a reference to this issue thank you 👍

**Comment by cvrebert** [comment]
@leecollings Child selectors interfere with genericity/extensibility. Folks don't want to or can't use ul/li in some cases for their "lists". And sometimes there are intermediate wrapper elements, so hardcoding the targeting of direct children would break such cases.
