### ISSUE TITLE
Don't use !important in spacing utilities

### ISSUE THREAD

**Issue by zeroxme** [twbs/bootstrap#18817]
I've built my own spacing utils with Scss and I've been using it for over a year. From what I see in spacing utils and what CSS experts recommend is not to use `!important` too much, so I would suggest to remove it and keep the code clean. Also, spacing utils classes can be used and extended within other classes like navs and etc..

**Comment by cvrebert** [comment]
`!important` is generally appropriate for utility classes; see https://css-tricks.com/when-using-important-is-the-right-choice/ and http://davidtheclark.com/on-utility-classes/

**Comment by zeroxme** [comment]
way to go :+1: Also you can check my approach for [Spass](https://github.com/zeroxme/spass)
Also I'll try to come up with something to make this module better

**Comment by mdo** [comment]
I think for what folks expect out of Bootstrap's utilities, we'll keep the `!important`, but my bigger concerns are around the media queries for responsive utilities and how they mix and match. I feel like we need a bit more experimentation with these before we finalize v4 honestly.

**Comment by cvrebert** [comment]
> I think for what folks expect out of Bootstrap's utilities, we'll keep the `!important`

Closing this then.
