### ISSUE TITLE
Part of the v4 Grid example page still talks about v3's grid

### ISSUE THREAD

**Issue by AdamPerkins** [twbs/bootstrap#18818]
Hello

- In the folder /docs/examples/ is a file *index.md*. Guess it should be a compiled html index page to the examples. 

- In examples/grid. There is still written about BS3 and 4 instead of 5 tiers.

Mixed: mobile and desktop
The Bootstrap 3 grid system has four tiers of classes: xs (phones), sm (tablets), md (desktops), and lg (larger desktops). You can use nearly any combination of these classes to create more dynamic and flexible layouts.

**Comment by cvrebert** [comment]
> In the folder /docs/examples/ is a file index.md. Guess it should be a compiled html index page to the examples.

No, it's the source code for http://v4-alpha.getbootstrap.com/examples/

**Comment by cvrebert** [comment]
> In examples/grid. There is still written about BS3 and 4 instead of 5 tiers.

Fixed in dedfffe5dbda53148c816e379f7ba93eb1ff36f6. Thanks!
