### ISSUE TITLE
v4 .btn.btn-default does not seem to affect <a/> elements

### ISSUE THREAD

**Issue by patchee500** [twbs/bootstrap#18827]
Giving an <a/> element class .btn-default doesn't seem to apply button styles.
Not sure if this is supposed to be working, however adding class .btn-info does function.

https://jsfiddle.net/96xLcqto/2/

**Comment by twbs-lmvtfy** [comment]
Hi @patchee500!

You appear to have posted a live example (https://fiddle.jshell.net/96xLcqto/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 58, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 66, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patchee500** [comment]
fixed example

**Comment by cvrebert** [comment]
Quoting from http://v4-alpha.getbootstrap.com/migration/#buttons
> ## Buttons
> * Renamed `.btn-default` to `.btn-secondary`.
