### ISSUE TITLE
multiple accordions collapse bug

### ISSUE THREAD

**Issue by leymannx** [twbs/bootstrap#18824]
Added two accordions both with all unique IDs. Page load fine. Each with one panel open. Now clicking a panel on one accordion to open leads to other accordion's panel to close. See example here: https://jsfiddle.net/leymannx/9x92umfk/

**Comment by cvrebert** [comment]
https://github.com/twbs/bootstrap/blob/64b9ad4d7f09c4d71612d9176bdda52d706ef2de/js/src/collapse.js#L124 is grabbing all active panels in the document instead of limiting itself to active panels within the parent/accordion.
