### ISSUE TITLE
Refactor embed-responsive to embrace images too

### ISSUE THREAD

**Issue by saviomd** [twbs/bootstrap#18833]
The `.embed-responsive` reserves document space to the element, avoiding layout recalculation.
But the `.img-responsive` (`.img-fluid` in v4) doesn't do that.
Dave Rupert expanded the responsive video solution to images to solve this (and gave it a background color, so you know the space will be filled with something):
http://daverupert.com/2015/12/intrinsic-placeholders-with-picture/

I think it would be nice to refactor `.embed-responsive` as `.media-responsive` (or media-fluid to follow the new image nomenclature) to embrace images too and include the following new classes:
- `.embed-responsive-1by1` for squared images like avatars (and videos too, instagram and vine videos are squared)
- `.embed-responsive-9by21`, `.embed-responsive-9by16`, `.embed-responsive-3by4` for portrait images

(I think img-fluid should still exist, there will be cases when the images dimension will not follow a pattern: a news site can have a squared image in a article, and a 16x9 in another article)

**Comment by cvrebert** [comment]
> `.embed-responsive-1by1`

Already exists: https://github.com/twbs/bootstrap/blob/6058dae624710e46b4efcd15aa94cfd7be18b674/scss/_responsive-embed.scss#L37

**Comment by saviomd** [comment]
Oops, my bad.. still messing with alpha 1, will update to alpha 2 to get the new stuff
But what do you think about renaming the module and adding classes for portrait elements? Do you think it's valid?

**Comment by mdo** [comment]
Going to punt on this for now, at least in renaming any classes in v4.
