### ISSUE TITLE
Stacked progress bars are missing in v4

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#18835]
So I noticed that the Bootstrap 4 has no documentation on stacked progressbars. Are they gone or is this simply missing? I hope the later, as stacked progressbars are quiet useful.

**Comment by mdo** [comment]
They are gone since the `<progress>` element basically didn't allow it. Given some of the other problems we've run into with that move, however, I'm thinking we should revert some of the progress bar changes. Maybe we can rebalance some things and make using the `<progress>` a seccondary option.

**Comment by cvrebert** [comment]
> Given some of the other problems we've run into with that move

Such as?

**Comment by ivebeenlinuxed** [comment]
I think loosing the stacked progress bar functionality would be shame. Could you leave in the div.progress bars so the functionality does not disappear....

**Comment by zhuangsirui** [comment]
stacked progress bar is needed! Please!

**Comment by magnusmanske** [comment]
+1 Need! Stacked! Bars!

**Comment by simran-ssk** [comment]
up vote +1 for stacked progress bars!

**Comment by cvrebert** [comment]
@magnusmanske @simran-ssk Per our contributing guidelines, please use [GitHub's reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of making "+1" comments. Thanks.

**Comment by Studio384** [comment]
Any news on this?

**Comment by Studio384** [comment]
Any update on what's going to happen to this rather useful feature? Will it be in 4.0? Will it be in 4.1?

**Comment by mdo** [comment]
Switched back to `div.progress` instead of `<progress>` in #21473, allowing progress components to have multiple bars.
