### ISSUE TITLE
Filename for svg glyphicons prevents Intellisense preview in Visual Studio

### ISSUE THREAD

**Issue by erikmartinessanches** [twbs/bootstrap#18834]
There appears to be a typo in bootstrap.css, end of line 267, which says: `#glyphicons_halflingsregular`, with implication that Visual Studio Enterprise 2015, doesn't display Bootstrap's glyphicon preview in its IntelliSense. Changing that section (using the less file I gather...) so that it reads `#glyphicons-halflings-regular` resolves the problem. But I'm not sure what other implications there may be. See the attached picture. 

This may be a related issue: #10952

The environment is: (VS2015 version 14.0.24720.00 Update 1; ASP.NET and Web Tools 2015 RC1 Update 1; using an ASP.NET MVC 5 project, Bootstrap package version 3.0.0)

![svgglyphsinvisualstudio2015]
(https://cloud.githubusercontent.com/assets/4912935/12223384/5d1398e0-b7d6-11e5-826f-aa969e15b486.jpg)

**Comment by cvrebert** [comment]
3.0.0 is ancient. Upgrade to 3.3.6 please.

**Comment by erikmartinessanches** [comment]
I did, it's still present.

**Comment by cvrebert** [comment]
The ID is correct as-is. See https://github.com/twbs/bootstrap/blame/master/fonts/glyphicons-halflings-regular.svg#L6
Sounds like Visual Studio has a bug.
