### ISSUE TITLE
Has the google style tabs with dropdown or button on it ?

### ISSUE THREAD

**Issue by aisuhua** [twbs/bootstrap#18840]
I see the document about the **Basic Google tabs**[http://todc.github.io/todc-bootstrap/components/#nav-tabs-google]. I use it in my project. If it can integration with dropdown or button. It will be so cool.

Thank you！

**Comment by cvrebert** [comment]
We have no relationship with the TODC Bootstrap project.
You should report your issue to https://github.com/todc/todc-bootstrap/issues instead.
Cheers!

**Comment by aisuhua** [comment]
@cvrebert Sorry, I make a mistake.
