### ISSUE TITLE
Non-interactive examples in Dropdowns docs are confusing

### ISSUE THREAD

**Issue by igll** [twbs/bootstrap#18841]
The examples of dropdown components (at http://v4-alpha.getbootstrap.com/components/dropdowns) are always expanded and can not be collapsed.

As the time of posting the example uses  Bootstrap v4.0.0-alpha.2 and Jquery 2.1.4

Confirmed using Internet Explorer 11.0.110240.16603, Firefox 43.0.4 and Chrome 47.0.2526.106 m

![dropdown always expanded](https://cloud.githubusercontent.com/assets/15997199/12230364/60c87a62-b850-11e5-9e20-f3983f01e524.png)

<h4>v4</h4> <h4>v4.0.0-alpha.2</h4> <h4>Dropdown</h4> <h4>Issue</h4>

**Comment by cvrebert** [comment]
Those examples are deliberately static. FWIW, I agree it would be less confusing to just make them dynamic.

**Comment by rosskevin** [comment]
:+1:  for dropping the added docs `.bd-example > .dropdown` styles and making them interactive.  While the static variation might be nice for development/styling, this deviates from other examples.

**Comment by rosskevin** [comment]
It looks like you can get the best of both worlds by:
  1. dropping the docs `.bd-example > .dropdown` styles
  2. sticking `open` on `.dropdown` the example html

This gives you an initial open view then upon click it is fully interactive.

**Comment by rosskevin** [comment]
Revising the above statement, it looks like `Menu headers` and below need those static docs styles to be displayed, so perhaps it's best to apply the existing docs styles a bit more narrowly to:
- Menu headers
- Menu dividers
- Disabled menu items

**Comment by mdo** [comment]
I've redone a lot of the dropdown docs in #18807, but I didn't change the display of most of these examples. I think they're okay as-is for nearly all of them right now. Will revisit at a later point though if I hear from more folks on it.
