### ISSUE TITLE
Explain .panel-collapse class in docs

### ISSUE THREAD

**Issue by aavmurphy** [twbs/bootstrap#18857]
It is in an "accordian" example, not a "collapse" example, which is how I missed it.

Maybe mention it in the 'collapse' section as well.

Thanks
Andrew

**Comment by Pvanhesteren** [comment]
@aavmurphy, I have just submitted #19474 to fix this. Please let me know what you think :smile:

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
