### ISSUE TITLE
Custom c-select and number control are too similar

### ISSUE THREAD

**Issue by aimeos** [twbs/bootstrap#18853]
The custom BS select and the standard browser controls for number fields are too similar. People will think both are the same, e.g.:

![select and number controls](https://aimeos.org/fileadmin/download/bs-controls.png)

Instead, the drop-down sign for the c-select should be a caret (down) only.

**Comment by mdo** [comment]
> Instead, the drop-down sign for the c-select should be a caret (down) only.

That can be changed with custom images. The number input, like most other inputs, will look lightly different in every browser. Not *super* concerned about the intersection here, but if folks feel strongly enough, I'd consider a PR for it.
