### ISSUE TITLE
Adding .dropdown-menu-right to left aligned element positions menu at right side of screen

### ISSUE THREAD

**Issue by rosskevin** [twbs/bootstrap#18852]
http://v4-alpha.getbootstrap.com/components/dropdowns/#button-elements

If you add `.dropdown-menu-right` to the live sample, the menu appears across the screen.

JSbin test case(updated): http://jsbin.com/yerepoh/edit?html,output

I'm expecting the menu to be right aligned on the `dropdown-toggle`.

**Comment by twbs-lmvtfy** [comment]
Hi @rosskevin!

You appear to have posted a live example (http://jsbin.com/qumuku/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 38, column 9 thru column 157: Duplicate ID ```` dropdownMenu2 ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rosskevin** [comment]
[Updated test case](http://jsbin.com/qumuku/edit?html,output)

**Comment by cvrebert** [comment]
Confirmed.
Also, http://v4-alpha.getbootstrap.com/components/dropdowns/#alignment really ought to be a live example to make this easier to test.

**Comment by mdo** [comment]
[Commented](https://github.com/twbs/bootstrap/pull/19610#issuecomment-202168163) on @chief10's PR in #19610. What's the use case for using the alignment class for the menu without right-aligning that button as well?

**Comment by rosskevin** [comment]
@mdo this was quite some time ago - so it is a bit fuzzy - it seems I have worked around it: 
https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/scss/_dropdown.scss#L34

The `stuff` menu here is a good example:
https://www.google.com/design/spec/components/menus.html#menus-usage

From my note it looks like I was shooting for the BMD default menu dropdowns to originate at the bottom right, regardless of on page page button placement.  This makes sense because we want the dropdown attached to the trigger, not disconnected.  Since they are encapsulated as one component under `div.dropdown`.

**Comment by rosskevin** [comment]
1.  I have updated the [test case](http://jsbin.com/yerepoh/edit?html,output), it now shows that a `dropdown` aligns different than a `btn-group`

1.  I may have also filed this issue for when a trigger is smaller than the menu, such as [this example](http://rosskevin.github.io/bootstrap-material-design/material-design/menus/#lower-right-side):

![menus_ _bootstrap_material_design](https://cloud.githubusercontent.com/assets/136564/14086440/be46e4b8-f4ea-11e5-9a57-2605f300bbd7.png)

**Comment by rosskevin** [comment]
I have tried a `btn-group` with a small trigger,, I can confirm that it works properly:

![menus_ _bootstrap_material_design](https://cloud.githubusercontent.com/assets/136564/14087852/a814d0ea-f4f1-11e5-85b4-c86530cc0f11.png)

**Comment by mdo** [comment]
I *think* this is good to go in `v4-dev`. At some point we added an example for this.
