### ISSUE TITLE
Carousel prevents input into form elements within slides

### ISSUE THREAD

**Issue by kulbakin** [twbs/bootstrap#18850]
Carousel should allow input for `input` or `textarea` within slides, there is no reason why it shouldn't.

Currently carousel keydown handler calls `e.preventDefault()` then checks for event source tag and does nothing if it is input or textarea. It would make more sense to prevent default after this check, not before.

**Comment by cvrebert** [comment]
X-Ref: #14991

**Comment by prosanelli** [comment]
:+1:

**Comment by KeithBohler** [comment]
👍
