### ISSUE TITLE
Link triggering a popover has its title attribute removed 

### ISSUE THREAD

**Issue by davidloubere** [twbs/bootstrap#18862]
I understand that a generated Bootstrap tooltip should have its `title` attribute removed because it substitutes to it.

However, regarding popovers which purpose can be much more different, IMHO, there's no point removing the `title` attribute which brings meaning/explanation to the trigger.
At least, an option should be available.

But perhaps am I missing something?

**Comment by cvrebert** [comment]
@patrickhlauke Any thoughts on this?

**Comment by patrickhlauke** [comment]
isn't `title` also displayed at the top of the popover, as popover title? that wouldn't really make it useful for adding meaning/explanation, i think. @davidloubere got an example in mind?

also, purely from a UX point of view, if `title` was left intact (either all the time, or cancelled out when popover is displayed and then reinstated when it's closed), you'd get some strange double functionality of native tooltip showing the `title` when hovering over the trigger with the mouse (or setting kbd focus on it in Edge), and then having the same text appear as part of the bootstrap popover when opened (and potentially still showing the native one, if you didn't cancel it while popover is open).

**Comment by davidloubere** [comment]
It is indeed. Nonetheless, regarding popovers that embeds interactive/dynamic content (such as links, forms etc.), my point is that when a popover has not yet been displayed, you can't always presume/infer what will happen when the trigger is clicked.
See my example attached (as seen on http://producthunt.com).
![popover-with-title-example](https://cloud.githubusercontent.com/assets/1379433/12319809/02e43114-baa5-11e5-9945-b61d5e5b8616.jpg)

**Comment by patrickhlauke** [comment]
At least looking at the bootstrap documentation (http://getbootstrap.com/javascript/#popovers and http://v4-alpha.getbootstrap.com/components/popovers/), I don't think that's an intended use of popovers.

In fact, this kind of use would likely cause other issues at the moment, such as focus/tab order ones, since the popover is added at the end of the HTML document itself, and focus is not programmatically moved to the popover/retained inside it/returned to the triggering element once closed.

**Comment by davidloubere** [comment]
Agree but I don't see much difference with tooltips TBH and I thought popovers were intended to achieve more complex tasks. Whatever.

Still, it would be great if the option to enable or not displaying the `ttile` argument was available. :)

Thx for your time.

**Comment by alecpl** [comment]
`trigger: 'click'` popovers should not remove `title` from the link. Also, I'd like to have a possibility to keep `title` on the link and not set title of the popover, e.g. with `title: ''` option.

**Comment by mdo** [comment]
Closing as stale. @twbs/js-review please reopen if you want to revisit this.
