### ISSUE TITLE
Grunt babel - List of JS

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#18861]
It's just a question, but why do you use this style of declaration for your array: 
https://github.com/twbs/bootstrap/blob/v4-dev/Gruntfile.js#L57-L77

Instead of something like this : 
```javascript
                files: [{
                    expand: true,
                    cwd: 'js/src/',
                    src: ['*.js'],
                    dest: 'js/dist/',
                    ext: '.js'
                }]
```
See : http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by mdo** [comment]
No idea honestly. @cvrebert any ideas?

**Comment by mdo** [comment]
Closing out as I'm pretty sure this is because `util` needs to come before everything else given some JS dependencies across those files.

**Comment by bardiharborow** [comment]
mdo is correct. `util.js` is a depended on by several of the other plugins and hence needs to be loaded first.
