### ISSUE TITLE
v4 Dashboard demo does not work with flexbox

### ISSUE THREAD

**Issue by Nikita240** [twbs/bootstrap#18867]
http://v4-alpha.getbootstrap.com/examples/dashboard/

The demo is built with flexbox turned off. It works because the width of the fixed sidebar is set as a percentage. However, flexbox does not work with `position: fixed`, so the sidebar does not size correctly.

**Comment by mdo** [comment]
We'll likely have some custom flexbox examples for v4's launch. Until then, the examples are as-is—no specific plans to do both flexbox and default versions of those.
