### ISSUE TITLE
Button plugin doesn't apply "checked"-attribute to checkbox/radio button

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#18866]
The button example as described in the documentation (http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons) doesn't apply the ```checked```-attribute to the actual checkbox and only applies ```active``` to the button.

**Comment by patrickhlauke** [comment]
Same problem also for the radio buttons that follow.

**Comment by patrickhlauke** [comment]
Actually, on further analysis no browser ever changes the `checked` attribute in the DOM (even on vanillla checkboxes/radio buttons), so just doing something like "inspect element" and looking at the DOM, or querying with `document.getElementById('option1').getAttribute('checked')` or similar, will not show any change. It's the `checked` *property* that changes, however ... (e.g. `document.getElementById('option1').checked`), and this works properly with the button plugin.
