### ISSUE TITLE
Preview of Customizations on getbootstrap.com

### ISSUE THREAD

**Issue by sandipchitale** [twbs/bootstrap#18870]
The user can customize bootstrap on Customize tab of getbootstrap.com website and download the less and css stuff for use in their own apps. But why not add a "Apply to this site" button so that the users can see how all the examples on other tabs are affected by the customization.

Of course this should apply to that user's session. And the customizations will have to be remembered for that session.

**Comment by cvrebert** [comment]
Given that:

* The customizer in general hasn't been particularly high on our priority list
* Superior third-party Bootstrap customizers already exist
* The customizer has currently been discontinued in Bootstrap v4

it's IMHO pretty unlikely that we'd implement this new feature.

CC: @hnrch02 @XhmikosR in case they disagree

**Comment by hnrch02** [comment]
@cvrebert Nope, I agree.

**Comment by XhmikosR** [comment]
Yeah, since it's dropped it doesn't make any sense.

**Comment by sandipchitale** [comment]
I see. I will close the issue then.
