### ISSUE TITLE
Flexbox navbar elements wrap onto new line instead of inline

### ISSUE THREAD

**Issue by rosskevin** [twbs/bootstrap#18875]
Meta list: #18467

[Test case](http://jsbin.com/jeyudiw/edit?html,css,output) 

It appears that there is not an implementation for nav items that responds to `$enable-flex: true;`.  This may not be in-scope, but wanted to mention it.

NOTE that it is not based on compiled css with `$enable-flex: true;` as that doesn't exist in `dist`.   Nonetheless, I see the same behavior in a flex enabled scenario.  Here's a screenshot of the same thing rendered with `$enable-flex: true;`:

![test_ _bootstrap_material_design](https://cloud.githubusercontent.com/assets/136564/12299311/c8b81bdc-b9db-11e5-93bb-cd9073e129f1.png)

**Comment by twbs-lmvtfy** [comment]
Hi @rosskevin!

You appear to have posted a live example (http://jsbin.com/jeyudiw/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 20, column 7: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`
* line 44, column 7: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rosskevin** [comment]
Bootlint failed on a sample copied from the v4 navbar docs :)

I updated the [test case](http://jsbin.com/jeyudiw/edit?html,css,output) with an inner container.

**Comment by acshef** [comment]
Ignore Bootlint in this case: https://github.com/twbs/bootstrap/issues/18790#issuecomment-169620411

**Comment by alwaysbrightblue** [comment]
Not sure if this is still an issue, but I think if you make the container class have `flex-direction: row`, it solves the issue.

https://gist.github.com/alwaysbrightblue/a66fed1fb9f7210fe803

**Comment by rosskevin** [comment]
This may be a good flex setup:

```scss
.navbar {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  flex-shrink: 0;
  align-items: center;
  align-self: stretch;

  > * {
    flex-shrink: 0;
  }
}
```

The problem I see with integrating this is the doc/examples with identical markup.  I'll take a shot at a navbar flexbox PR and see if I can get something working both ways.

**Comment by rosskevin** [comment]
PR #18976 flexbox enables the navbar

**Comment by jorge-sanz** [comment]
Is this issue solved because of #18976?

**Comment by rosskevin** [comment]
@jorge-sanz it is for me.  I'm using directly in bootstrap-material-design v4 (we are standardizing on flex-only)

**Comment by jorge-sanz** [comment]
Ok! Cool! I am a newbie contributor and I would like to start to code for Bootstrap! @rosskevin
