### ISSUE TITLE
Tooltip Position problem in Windows OS

### ISSUE THREAD

**Issue by Hazarapet** [twbs/bootstrap#18873]
I have a problem with Bootstrap Tooltip in Windows OS.The Position is wrong.It's working fine in Ubuntu, but I can't fix it for windows os. Tell me what's wrong with it.?
![rsz_12540391_880082492088876_1967723238_n](https://cloud.githubusercontent.com/assets/4758675/12295140/22a80a24-ba10-11e5-9306-aac115c7830f.jpg)

**Comment by patrickhlauke** [comment]
Please have a look at https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports - it's not possible for us to see if there is an actual bug in Bootstrap based only on a screenshot

**Comment by Hazarapet** [comment]
I've got a problem and would like to know how to fix it.your link didn't get me anything.

**Comment by patrickhlauke** [comment]
The link told you how to actually file bug reports (and not just put a small screenshot in here and ask people how to fix it...)
