### ISSUE TITLE
Center content in navbar

### ISSUE THREAD

**Issue by kevinwarren** [twbs/bootstrap#18876]
Howdy,

It would be great if we could have centered content in the navbar built into Bootstrap.

I find it useful to be able to slightly off-center content depending on the rest of the content in the navbar eg lots of content using .navbar-right... use .navbar-center-left to slightly move it to the left.

I use this to do it which works great:

.navbar-center {
	position: 	absolute;
	left: 		50%;
	-webkit-transform:	translateX(-50%);
	-moz-transform:	translateX(-50%);
	-ms-transform:		translateX(-50%);
	-o-transform:		translateX(-50%);
	transform:		translateX(-50%);
}

.navbar-center-left {
	position: 	absolute;
	left: 		40%;
	-webkit-transform:	translateX(-50%);
	-moz-transform:	translateX(-50%);
	-ms-transform:		translateX(-50%);
	-o-transform:		translateX(-50%);
	transform:		translateX(-50%);
}

.navbar-center-right {
	position: 	absolute;
	right: 		40%;
	-webkit-transform:	translateX(-50%);
	-moz-transform:	translateX(-50%);
	-ms-transform:		translateX(-50%);
	-o-transform:		translateX(-50%);
	transform:		translateX(-50%);
}

The 40% could easily be a variable for custom aligning per site.

Hope you like my idea. :-)

**Comment by mdo** [comment]
No planned changes here for v4.0 at this time, thanks though!
