### ISSUE TITLE
Selecting any text on the page prevents custom radios/checkboxes from being (un)checked in Chrome

### ISSUE THREAD

**Issue by Deklan** [twbs/bootstrap#18887]
![bootstrap-wtf](https://cloud.githubusercontent.com/assets/2732482/12315728/83250eec-ba65-11e5-9d8c-4ca46cc0f681.png)
In the photo above scenario (text or part of text of the first selected radio), if I click on the second radio - visual object (marked with red ball), it is not selected. Also applies to checkboxes ;)

**Comment by patrickhlauke** [comment]
in what os/browser? can't reproduce in Chrome, Firefox, IE11 nor Edge on Windows

**Comment by Deklan** [comment]
Selecting label text of custom radios/checkboxes (or any other text on the page) prevents (un)checking/ ;)
