### ISSUE TITLE
Update to jQuery 1.12.0 (Bootstrap v3)

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#18889]
Bootstrap v3 usually uses the latest available version of jQuery 1.x.

jQuery 1.12.0 is now available - can we update CDN links to use this:
REF: http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/pull/18904
