### ISSUE TITLE
Alert CSS shouldn't have hardcoded lengths

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18884]
See:
https://github.com/twbs/bootstrap/blob/5e9b365b2533d245bc992caaad2beca4bc3d701e/scss/_alert.scss#L17
https://github.com/twbs/bootstrap/blob/5e9b365b2533d245bc992caaad2beca4bc3d701e/scss/_alert.scss#L38-L44

**Comment by cvrebert** [comment]
@mdo Could you take a look? Not quite sure of the logic here.

**Comment by mdo** [comment]
Yup, I'll peep this soon.

**Comment by mdo** [comment]
Addressed in Alphas 4 & 5 I believe.
