### ISSUE TITLE
Decouple from <body> as only viewport for modals, backdrops, etc.

### ISSUE THREAD

**Issue by MrAndMrsK** [twbs/bootstrap#18898]
For administrative console-style apps, the ability to host sub-areas of the screen that can manage their own modals, overlays, etc would be useful.  If I want a window-manager-like controller that can bring up mutliple sub-areas, I want to be able to have modals and overlays that are local only to that area and which can further be overlain by outer such viewports' overlays.

I don't think there's anything in the CSS that would make this difficult.  The javascript has only a few references to `document.body` or `window`.  Conceptually though, addressing a modal or an overlay would need rethinking.  I assume there would be some new `.viewport` class (bad name?) and for backwards compatibility the default viewport would be the body, but that additional modals and scrolling effects would have additional options for being bound to other viewports.

**Comment by mdo** [comment]
Understand the use case, but going to punt on this for simplicity's sake.
