### ISSUE TITLE
progress-variant -mixin should allow overriding the other color (background) too

### ISSUE THREAD

**Issue by petetnt** [twbs/bootstrap#18896]
![image](https://cloud.githubusercontent.com/assets/7641760/12324821/27819524-bace-11e5-9c8d-7538e20cad68.png)

Lets call the green part (completed) the foreground and white part (incomplete) the background.

Currently we have `progress-variant` to change the foreground color of the progress bar:

```
@mixin progress-variant($color) {
  &[value]::-webkit-progress-value {
    background-color: $color;
  }

  &[value]::-moz-progress-bar {
    background-color: $color;
  }

  // IE10+, Microsoft Edge
  &[value]::-ms-fill {
    background-color: $color;
  }

  // IE9
  @media screen and (min-width:0\0) {
    .progress-bar {
      background-color: $color;
    }
  }
}
```

However, there's no easy way to style the background of the progress bar (default: `$progress-bg: #eee !default`), which kinda sucks when you want to change colors of the progress bars that happen to be on gray backgrounds but don't want to override all the progress bars. 

One option would be passing another value to the `progress-variant`

```
@mixin progress-variant($color, $background-color: $progress-bg)
```

Most likely this would mean that the all the progress bars should be / would be made with this mixin only, as the mixin would have to handle pretty much everything in `scss/_progress.scss` (sans the animations etc.).

(Sorry if there's some inconsistencies with the names of the elements, the progress bars are a pain in the ass in general :facepunch: )

**Comment by mdo** [comment]
Going to close this as a won't fix.

Generally speaking, we don't add properties that might get used in our CSS. Put another way, anything that's `inherit` or a "default" to the base component doesn't need to be set again on modifiers. Rather than have CSS that's largely unused by default, we prefer folks add to our own.

Hope that explains it, and thanks for the suggestion!

**Comment by petetnt** [comment]
Fair enough, thanks @mdo
