### ISSUE TITLE
Popover positioning issue with window resize and device orientation change

### ISSUE THREAD

**Issue by cloud9amit** [twbs/bootstrap#18893]
Hi,

I am  using bootstrap ui version 1.0.0 with bootstrap version 3.3.5 and I see popover positioning issue when 
1. window is being resized on browser 
2. opening popover on small screen devices
3. opening popup and changing the orientation of tablets/devices.

I have added a plunkr for the same. http://plnkr.co/edit/2p3JxVpTH2MACfvhy5Bu?p=preview

Please click on button "D" to reproduce the issue.
I see some of this is proposed in v4 but want to understand if there is any workaround at this moment.

**Comment by twbs-lmvtfy** [comment]
Hi @cloud9amit!

You appear to have posted a live example (http://run.plnkr.co/plunks/2p3JxVpTH2MACfvhy5Bu/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 1, column 16 thru line 2, column 33: Attribute ```` ng-app ```` not allowed on element ```` html ```` at this point.
* line 12, column 1 thru column 37: Attribute ```` ng-controller ```` not allowed on element ```` div ```` at this point.
* line 16, column 7 thru column 80: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 20, column 7 thru column 78: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 24, column 7 thru column 106: Attribute ```` ng-model ```` not allowed on element ```` input ```` at this point.
* line 25, column 7 thru column 171: Attribute ```` uib-popover ```` not allowed on element ```` button ```` at this point.
* line 25, column 7 thru column 171: Attribute ```` popover-title ```` not allowed on element ```` button ```` at this point.
* line 29, column 5 thru column 141: Attribute ```` uib-popover-template ```` not allowed on element ```` button ```` at this point.
* line 29, column 5 thru column 141: Attribute ```` popover-title ```` not allowed on element ```` button ```` at this point.
* line 42, column 7 thru column 112: Attribute ```` ng-model ```` not allowed on element ```` select ```` at this point.
* line 42, column 7 thru column 112: Attribute ```` ng-options ```` not allowed on element ```` select ```` at this point.
* line 44, column 5 thru column 137: Attribute ```` popover-placement ```` not allowed on element ```` button ```` at this point.
* line 44, column 5 thru column 137: Attribute ```` uib-popover ```` not allowed on element ```` button ```` at this point.
* line 49, column 7 thru column 122: Attribute ```` uib-popover ```` not allowed on element ```` button ```` at this point.
* line 49, column 7 thru column 122: Attribute ```` popover-trigger ```` not allowed on element ```` button ```` at this point.
* line 51, column 5 thru column 152: Attribute ```` uib-popover ```` not allowed on element ```` input ```` at this point.
* line 51, column 5 thru column 152: Attribute ```` popover-trigger ```` not allowed on element ```` input ```` at this point.
* line 55, column 5 thru column 108: Attribute ```` popover-animation ```` not allowed on element ```` button ```` at this point.
* line 55, column 5 thru column 108: Attribute ```` uib-popover ```` not allowed on element ```` button ```` at this point.
* line 56, column 5 thru column 107: Attribute ```` uib-popover ```` not allowed on element ```` button ```` at this point.
* line 56, column 5 thru column 107: Attribute ```` popover-title ```` not allowed on element ```` button ```` at this point.
* line 57, column 5 thru column 162: Attribute ```` uib-popover ```` not allowed on element ```` button ```` at this point.
* line 57, column 5 thru column 162: Attribute ```` popover-is-open ```` not allowed on element ```` button ```` at this point.
* line 57, column 5 thru column 162: Attribute ```` ng-click ```` not allowed on element ```` button ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cloud9amit** [comment]
Hi I have fixed those errors. Please review it now:

http://plnkr.co/edit/2p3JxVpTH2MACfvhy5Bu?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @cloud9amit!

You appear to have posted a live example (http://run.plnkr.co/plunks/2p3JxVpTH2MACfvhy5Bu/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 8, column 5: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.3.5

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cloud9amit** [comment]
Updated plunker : http://plnkr.co/edit/2p3JxVpTH2MACfvhy5Bu?p=preview

**Comment by cvrebert** [comment]
Angular UI Bootstrap doesn't use Bootstrap's JavaScript, and your issue doesn't appear to be CSS-related, so you should report this to the Angular UI Bootstrap project instead of us: https://github.com/angular-ui/bootstrap/issues
Thanks.
