### ISSUE TITLE
Update to jQuery 2.2.0 (Bootstrap v4)

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#18890]
Bootstrap v4 usually uses the latest available version of jQuery 2.x.

jQuery 2.2.0 is now available - can we update to use this:
REF: http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by cvrebert** [comment]
It's quite possible that the same apparent bug in jQuery 1.12.0 (https://github.com/twbs/bootstrap/pull/18904#issuecomment-171868812) also applies to jQuery 2.2.0.

**Comment by alberto** [comment]
I'll try to update it and see what happens.

**Comment by alberto** [comment]
Yup, same issue.

**Comment by cvrebert** [comment]
Superseded by #19296 due to the bug in jQuery 2.2.0 (& 1.12.0).
