### ISSUE TITLE
Custom forms - lack of color variables

### ISSUE THREAD

**Issue by atu-record** [twbs/bootstrap#18897]
I'd suggest to add variables to _custom-form.scss to make custom forms more maintainable

**Comment by mdo** [comment]
Done! See #18920.

**Comment by atu-record** [comment]
many thx!

Von: Mark Otto [mailto:notifications@github.com]
Gesendet: Montag, 18. Jänner 2016 02:58
An: twbs/bootstrap
Cc: Amar Tupo
Betreff: Re: [bootstrap] Custom forms - lack of color variables (#18897)


Done! See #18920<https://github.com/twbs/bootstrap/pull/18920>.
