### ISSUE TITLE
iPad keyboard should close upon tapping outside of an <input>

### ISSUE THREAD

**Issue by lakinmohapatra** [twbs/bootstrap#18895]
After applyinng bootstrap , i am unable to close/dismiss numpad of ipad while tapping screen outside of textbox. 

I think , bootstrap css is causing issue. Please fix it and let me know.

**Comment by cvrebert** [comment]
@lakinmohapatra Please post a JS Bin or JS Fiddle that demonstrates the problem and given step-by-step instructions for how to reproduce the problem. Also, what version of iOS and what modal of iPad are you using?

**Comment by lakinmohapatra** [comment]
Hi @cvrebert  ,

Please go to bootstrap official site and click on any textbox inside forms [documentation]. 

Once focus will be inside textbox , keypad of ipad [16GB] will open . Then after entering something inside textbox , if you will tap outside of it , keypad will not close. 

It generally happens with bootstrap powered form elements . In this case user need to manually close keypad and then tap outside.

I fixed it using following js code.
$(document).on('touchstart', function (event) {
			  if ((!$(event.target).is('input') && $('input').is(':focus')) ||
				  (!$(event.target).is('textarea') && $('textarea').is(':focus'))) {
				document.activeElement.blur();
			  }
}); 

Please let me know if you need anything else from me.
You can test it with any bootstrap powered input text boxes.  

Thanks,
Lakin
![image1](https://cloud.githubusercontent.com/assets/11457501/12347090/6d43ba1c-bb80-11e5-998a-aab4aae91e66.PNG)

**Comment by cvrebert** [comment]
> Please let me know if you need anything else from me.

@lakinmohapatra 
* What version of iOS are you running?
* What iPad model are you using? See https://en.wikipedia.org/wiki/IPad#Model_comparison for a list of possible models. Just saying that it's "16GB" doesn't help us.

**Comment by cvrebert** [comment]
@lakinmohapatra Also, are you using Bootstrap v3 or Bootstrap v4?

**Comment by lakinmohapatra** [comment]
@cvrebert  , 

Please find following details.

1. Bootstrap version - V3
2. IOS version - 9.2(13C75)
3. Model - MC705HN/A

Thanks,
Lakin

**Comment by patrickhlauke** [comment]
isn't this simply standard behavior of iOS? if you just have a page without bootstrap with form fields, does the keyboard close when you tap out of the field?

**Comment by cvrebert** [comment]
> Model - MC705HN/A

Thanks. That appears to translate to https://en.wikipedia.org/wiki/iPad_(3rd_generation)

**Comment by lakinmohapatra** [comment]
@patrickhlauke  , Check google & yahoo website for textfields , they have implemented something so that by tapping outside , numpad is dismissed. 

So as bootstrap is a popular framework , it should have this feature so that ipad users will not face that difficulty in future. It is required for better user experience. Webpage should not only be mobile responsive , but also it should be flexible for users to use in their mobiles/tablets/ipads etc.

$(document).on('touchstart', function (event) {
if ((!$(event.target).is('input') && $('input').is(':focus')) ||
(!$(event.target).is('textarea') && $('textarea').is(':focus'))) {
document.activeElement.blur();
}
});

I hope , Bootstrap team will fix that issue as soon as possible
Thanks,
Lakin

**Comment by cvrebert** [comment]
@lakinmohapatra What happens when you do the same "type in the input and then tap away" thing on https://jsfiddle.net/zc26zazn/2/show/ ?

**Comment by cvrebert** [comment]
> isn't this simply standard behavior of iOS?

Indeed, that's what my testing in the Simulator for iPad Air 2, iOS 9.2 seems to suggest. Tapping areas of the page without links, labels, or form controls while an input is focused doesn't seem to dismiss the keyboard.

**Comment by cvrebert** [comment]
> it should have this feature so that ipad users will not face that difficulty in future. It is required for better user experience.

Presumably Apple disagrees; otherwise, one would expect them to have made the behavior you're proposing be the default behavior.

At any rate, the JavaScript snippet you're suggesting seems too invasive/opinionated, IMHO. We generally don't attempt to override basic platform behaviors such as this.

**Comment by patrickhlauke** [comment]
Agree...i would punt on this (and messing with focus can cause accessibility issues, FWIW)

**Comment by cvrebert** [comment]
@mdo @XhmikosR @hnrch02 If any of y'all disagree, feel free to reopen.

**Comment by lakinmohapatra** [comment]
Hi @cvrebert  ,

I admire , its an default behaviour of apple. But the same thing is not happening in case of android.[numpad dismissing in case of android (working fine)]
But user  should use web app in the same way in all platforms.  There should be consistency in behaviour of webapp in all platforms.

Can i contribute  to  this repository for this fix ?

Please let me know your feedback.

Thanks,
Lakin

**Comment by patrickhlauke** [comment]
> There should be consistency in behaviour of webapp in all platforms

no, there needs to be consistency with standard platform conventions and behavior.

> Can i contribute to this repository for this fix ?

unless @mdo or other core project members agree this is a worthwhile addition, it will not be merged I'm afraid.

**Comment by lakinmohapatra** [comment]
@patrickhlauke ,

I respect your opinion. 

You can check google/yahoo's textbox . it has same behaviour in all platforms thats why users are much more comfortable with it. 

Please let me know if this fix will affect any other parts of web app.

Thanks,
Lakin
