### ISSUE TITLE
v4 discussion: flexbox goals

### ISSUE THREAD

**Issue by rosskevin** [twbs/bootstrap#18901]
With bootstrap-material-design we are opting for `$enable-flex: true`, though there are a variety of items in BS that aren't using the flex layout, so we have a pretty broad mixture at this point.

For example, flex based vertical alignment is quite simple and would work well for our `card-footer` as well as `btn`, in that we could simply set a desired height and get a vertical center alignment, without using padding for adjustment.  I realize I'm probably restating known advantages here.

My question is concerning the goals for `$enable-flex`, is it to:
1. enable flex everywhere _except_ where it makes things harder; or 
2. enable flex on some items where it makes things easier

Are we seeking to implement for example buttons and cards with flex and that is a bug?

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
If we can flex it, we should flex it :). I haven't had time myself to do every component yet, but I'm definitely in favor of it as much as possible.

**Comment by rosskevin** [comment]
Ok thanks,  I might pr some things then.
