### ISSUE TITLE
alert-success become alert-info ?? BS4 CSS

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#18909]
when i use and write an alert-success in my source code this become alert-info in generated code ???

`<div id="mess" class="alert alert-success" role="alert"></div> `MUST BE GREEN
this is change to 
`<div id="mess" class="alert alert-info" role="alert"></div>` IT IS BLUE

**Comment by patrickhlauke** [comment]
"generated" by what, exactly?

**Comment by jipexu** [comment]
safari ...

**Comment by jipexu** [comment]
in my dev inspector in safari .. (generated code) and the second line is what i get in my page: 
 a div stylized with info instead of success ...
so in one others word my class is change(switch?)  ... before rendering

**Comment by patrickhlauke** [comment]
Please provide a live example of where this is happening (for instance as a JSFiddle, JS Bin or similar). see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by jipexu** [comment]
i just making a jsfiddle now

**Comment by jipexu** [comment]
i make a fiddle [here]( https://jsfiddle.net/jipexu/s48tzabg/10/)
with :
https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js

but can not reproduce 

on my dev labo i use 4.0.0-alpha.2

What is the newest 4.0.0-alpha.2 or or from rawgit ??

**Comment by twbs-lmvtfy** [comment]
Hi @jipexu!

You appear to have posted a live example (https://fiddle.jshell.net/jipexu/s48tzabg/10/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 80, column 63 thru column 103: Start tag ```` span ```` seen in ```` table ````.
* line 80, column 63 thru column 103: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jipexu** [comment]
[here] (https://jsfiddle.net/jipexu/s48tzabg/20/)

**Comment by twbs-lmvtfy** [comment]
Hi @jipexu!

You appear to have posted a live example (https://fiddle.jshell.net/jipexu/s48tzabg/20/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 68, column 118 thru column 173: Duplicate ID ```` mess ````.
* line 68, column 118 thru column 173: Element ```` div ```` not allowed as child of element ```` h4 ```` in this context. (Suppressing further errors from this subtree.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jipexu** [comment]
[here] (https://jsfiddle.net/jipexu/s48tzabg/20/)

**Comment by twbs-lmvtfy** [comment]
Hi @jipexu!

You appear to have posted a live example (https://fiddle.jshell.net/jipexu/s48tzabg/20/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 68, column 118 thru column 173: Duplicate ID ```` mess ````.
* line 68, column 118 thru column 173: Element ```` div ```` not allowed as child of element ```` h4 ```` in this context. (Suppressing further errors from this subtree.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by jipexu** [comment]
[here] (https://jsfiddle.net/jipexu/s48tzabg/22/)

**Comment by patrickhlauke** [comment]
As the issue is not reproducing in the minimal test case (the alert is green, as it should be), I'd hazard a guess that the problem you're seeing lies with something else other than Bootstrap. Maybe try StackOverflow or similar? (see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker)

**Comment by jipexu** [comment]
ok thanks i will continue to test and to search why ..
