### ISSUE TITLE
google map did not work in tab

### ISSUE THREAD

**Issue by Neeraj-pant** [twbs/bootstrap#18911]
google map did not work in tabs if map is in 2nd or other tabs.
If we use map in active tab it started work.
or if we open firebug it works.
but not works in other tabs

**Comment by patrickhlauke** [comment]
Please provide a reduced test case showing the problem - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by Neeraj-pant** [comment]
https://jsfiddle.net/neeraj__pant/Lj9Lshtt/10/
open second tab, map isn't working there.

**Comment by twbs-lmvtfy** [comment]
Hi @Neeraj-pant!

You appear to have posted a live example (https://fiddle.jshell.net/neeraj__pant/Lj9Lshtt/10/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 17, column 3: [W005](https://github.com/twbs/bootlint/wiki/W005): Found what might be an outdated version of jQuery; Bootstrap requires jQuery v1.9.1 or higher

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Neeraj-pant** [comment]
![image](https://cloud.githubusercontent.com/assets/13445943/12363094/cfde0314-bbec-11e5-8ca3-217589edcadb.png)
i've updated the version of Jquery to 1.9.1 , even i've tried higher version it still not working..
i'm thinking it happening because the div is display:none at the time page load so mp is't working..

**Comment by patrickhlauke** [comment]
> i'm thinking it happening because the div is display:none at the time page load so map is't working

yes, that seems likely. suggest trying to initialize the map when the tab is first shown, rather than on page load. see http://getbootstrap.com/javascript/#tabs-events

**Comment by patrickhlauke** [comment]
Also, as this is not a Bootstrap problem per se, but rather an issue of Google Maps / your specific use of Bootstrap, I'm afraid I'll have to close this issue. However, I'd suggest - if the problem still persists - to check on StackOverflow, Slack or IRC (see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker)
