### ISSUE TITLE
Add off-canvas sidebar navigation widget

### ISSUE THREAD

**Issue by krvikash35** [twbs/bootstrap#18918]
need a vertical sidebar navigation, which is widely used in mobile app development.

**Comment by cvrebert** [comment]
Erm, you mean an off-canvas navigation like http://getbootstrap.com/examples/offcanvas/ ?

**Comment by krvikash35** [comment]
@cvrebert ...yes...I wish if releases as part of v4

**Comment by cvrebert** [comment]
Duplicate of #17502.

**Comment by saclychan** [comment]
I also liked that

2016-01-18 3:58 GMT+07:00 Vikash Kumar <notifications@github.com>:

> @cvrebert <https://github.com/cvrebert> ...yes...I wish if releases as
> part of v4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/18918#issuecomment-172379726>.
>



-- 
Ngô Cẩm Hà
