### ISSUE TITLE
 Large modal missing scrollbar after close a small modal up on it

### ISSUE THREAD

**Issue by unbug** [twbs/bootstrap#18924]
v4.0.0-alpha.2.
The large modal has scrollbar due to is too height,but if I open a small modal up on it,after the small one close,the large modal's scrollbar is missing.
![image](https://cloud.githubusercontent.com/assets/799578/12383347/fcb6f220-bddf-11e5-8b6e-a4a0e8a54818.png)

My solution for this issue is hide the large modal before show the small one,and show it back after the small one closed.
Is there a better options?

The
```
$('#myModal').data('bs.modal').handleUpdate()
//actually is 
$('#myModal').data('bs.modal')._handleUpdate()
```
does nothing in my case.

**Comment by cvrebert** [comment]
@unbug Please post a JS Bin or JS Fiddle that reproduces the problem.

**Comment by unbug** [comment]
@cvrebert Sorry for the delay,here is the [demo](https://jsbin.com/bahacos/edit?html,output)

**Comment by twbs-lmvtfy** [comment]
Hi @unbug!

You appear to have posted a live example (https://jsbin.com/bahacos/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 21, column 1 thru column 118: The ```` aria-labelledby ```` attribute must point to an element in the same document.
* line 455, column 1 thru column 118: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by unbug** [comment]
@cvrebert Ok,bot,I fixed the issue [demo](https://jsbin.com/bahacos/edit?html,output)

**Comment by twbs-lmvtfy** [comment]
Hi @unbug!

You appear to have posted a live example (https://jsbin.com/bahacos/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
See http://v4-alpha.getbootstrap.com/components/modal/#multiple-open-modals-not-supported
