### ISSUE TITLE
Problem with Forms-Groups 

### ISSUE THREAD

**Issue by ishaklive** [twbs/bootstrap#18923]
I have to use the clearfix class with every form-group class to in order to get the margin-bottom in the form-group.
 If I didn't use clearfix class, form-group height becomes 0

https://codepen.io/anon/pen/zrEVMe

Bootstrap V4 Alpha 2

**Comment by twbs-lmvtfy** [comment]
Hi @ishaklive!

You appear to have posted a live example (https://codepen.io/anon/pen/zrEVMe.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 6: Stray start tag ```` html ````.
* line 9, column 3 thru column 8: Stray start tag ```` head ````.
* line 10, column 3 thru column 294: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 10, column 3 thru column 294: Element ```` link ```` is missing required attribute ```` property ````.
* line 11, column 3 thru column 9: Stray end tag ```` head ````.
* line 12, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 115, column 3 thru column 9: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 114, column 5 thru column 9: Unclosed element ```` div ````.
* line 13, column 3 thru column 19: Unclosed element ```` div ````.
* line 117, column 1 thru column 7: Stray end tag ```` body ````.
* line 117, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ishaklive** [comment]
Hi,
I fixed the problems with code. 

https://codepen.io/anon/pen/zrEVMe

**Comment by twbs-lmvtfy** [comment]
Hi @ishaklive!

You appear to have posted a live example (https://codepen.io/anon/pen/zrEVMe.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 6: Stray start tag ```` html ````.
* line 10, column 1 thru column 6: Stray start tag ```` head ````.
* line 11, column 1 thru column 7: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 12, column 3 thru line 13, column 26: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 12, column 3 thru line 13, column 26: Element ```` link ```` is missing required attribute ```` property ````.
* line 14, column 1 thru column 7: Stray end tag ```` head ````.
* line 16, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 125, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ishaklive** [comment]
I fixed the Probelm. 
https://codepen.io/anon/pen/zrEVMe

**Comment by twbs-lmvtfy** [comment]
Hi @ishaklive!

You appear to have posted a live example (https://codepen.io/anon/pen/zrEVMe.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 9, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 116, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ishaklive** [comment]
fixed 
https://codepen.io/anon/pen/zrEVMe

**Comment by twbs-lmvtfy** [comment]
Hi @ishaklive!

You appear to have posted a live example (https://codepen.io/anon/pen/zrEVMe.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 8, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 96, column 15: [E017](https://github.com/twbs/bootlint/wiki/E017): Incorrect markup used with the `.checkbox` class. The correct markup structure is .checkbox>label>input[type="checkbox"]

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ishaklive** [comment]
Okay Fixed 
https://codepen.io/anon/pen/zrEVMe

**Comment by twbs-lmvtfy** [comment]
Hi @ishaklive!

You appear to have posted a live example (https://codepen.io/anon/pen/zrEVMe.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 1: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ishaklive** [comment]
Okay Fixed 
https://codepen.io/anon/pen/zrEVMe.html

**Comment by mdo** [comment]
I see the margin rendering just fine:

<img width="423" alt="screenshot 2016-01-17 18 58 30" src="https://cloud.githubusercontent.com/assets/98681/12382209/5bcfb4d4-bd4c-11e5-99ca-952c8b166a5b.png">

**Comment by ishaklive** [comment]
Are you sure. Did you check my code pen code. It happens only in large screens I used Bootstap v4 alpha 2. It work fine with md and sm screens

**Comment by ju1ius** [comment]
Hi,
That's the way bootstrap works.
You have to wrap columns in rows. Just add the `.row` class to your `.form-group`s.

```html
 <div class="form-group row">
    <label class="form-control-label col-lg-3" for="Title">Title</label>
    <div class="col-lg-9">
        <input class="form-control text-box single-line" id="Title" name="Title" type="text" value="" />
        <span class="field-validation-valid text-danger" data-valmsg-for="Title" data-valmsg-replace="true"></span>
    </div>
</div>
```

 :wink:

**Comment by mdo** [comment]
Yeah, I used your code, but I don't think I viewed at the larger screen resolutions since you didn't mention it was a responsive problem. And right now in v4 you need `.row` or `.clearfix`. Might revisit it still, but that's what we have for now.

**Comment by ishaklive** [comment]
OKay Thank you for quick replays   :+1:  :D
