### ISSUE TITLE
Add variable for breadcrumb link color

### ISSUE THREAD

**Issue by trollwinner** [twbs/bootstrap#18929]
Hello. Can you add some variable like "$breadcrumb-link-color" in v4, which affects on "a" tags, please? Designers are unstoppable and re-styling it allmost always, but now impossible to change it without changing "breadcrumb.scss" (or global only). Thank you.

**Comment by trollwinner** [comment]
@cvrebert, sorry for bad issue styling

**Comment by mdo** [comment]
Going to pass on this since by default breadcrumbs use an inherited link color. Adding the variable would mean adding a new placeholder color that's rather unnecessary until time of customization.
