### ISSUE TITLE
<progress>: Don't set display: block and margin-bottom to .progress

### ISSUE THREAD

**Issue by petetnt** [twbs/bootstrap#18939]
`normalize.scss` normalizes `<progress>` to `display: inline-block` and `vertical-align: baseline`

```
//
// 1. Correct `inline-block` display not defined in IE 8/9.
// 2. Normalize vertical alignment of `progress` in Chrome, Firefox, and Opera.
//

audio,
canvas,
progress,
video {
  display: inline-block; // 1
  vertical-align: baseline; // 2
}
```

`progress.scss` overrides the `display` value with `block` and prevents vertical alignment (with for example, `aling-items: center`) by adding an explicit `margin-bottom`

```
.progress {
  display: block;
  width: 100%;
  height: $spacer-y; // todo: make a new var for this
  margin-bottom: $spacer-y;
}
```

Unless I am missing something, neither of these seem necessary (but on the contrary make `<progress>` elements trickier to use)?

**Comment by mdo** [comment]
Going to leave this as-is for v4 for now. It doesn't affect all `<progress>` elements, just the ones we want to style the way we want them styled. Happy to revisit in the future though.
