### ISSUE TITLE
v4: Each .container size has 30px smaller width in comparison to BS3

### ISSUE THREAD

**Issue by darklow** [twbs/bootstrap#18937]
In bootstrap 3:
`@container-large-desktop:      (1140px + @grid-gutter-width);`
Which results **1170px** `.container` width and **1140px** width for actual content.

In bootstrap 4:
`$container-max-widths: (... xl: 1140px)`
`$grid-gutter-width:          1.875rem !default; // 30px`
Which results **1140px** `.container` width and **1110px** width for actual content.

Same goes to other containers sizes as well.
In bs3 gutter padding was added to width, in bs4 it is not, which decreases width for content.

Easy to spot difference by Getting started examples, inspect `.container` class.
BS3: http://getbootstrap.com/examples/starter-template/
BS4: http://v4-alpha.getbootstrap.com/examples/starter-template/

Is it planned behaviour to decrease `.container` size by `30px` in comparison to bs3?

**Comment by mdo** [comment]
Yes, it's intentional. The newer widths divide into whole pixel values as opposed to decimal values.
