### ISSUE TITLE
Button in card heading

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#18931]
I had the idea that when you put a button in the card heading, it wouldn't deform the heading as it does at this point, but instead it would take the height of of the heading so that it has a nicely integrated look as shown on the screenshot in the lower card. The "Normal card with button" is the current state of what would happen, with the lower being what happens with this change.

![integrated button](https://cloud.githubusercontent.com/assets/1693592/12398965/56db255a-be17-11e5-929f-1739c51ddf00.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now on this.
