### ISSUE TITLE
Tooltip shows at wrong place

### ISSUE THREAD

**Issue by foxbg** [twbs/bootstrap#18941]
If <a tag is used as button tooltip shows at wrong place (checked with FF, Opera and Edge)

An example
http://jsbin.com/cogaqeyipi/1/edit?html,output

Ordinary button works as expected.

**Comment by twbs-lmvtfy** [comment]
Hi @foxbg!

You appear to have posted a live example (http://jsbin.com/cogaqeyipi/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 25, column 25: [W008](https://github.com/twbs/bootlint/wiki/W008): Tooltips and popovers within button groups should have their `container` set to `'body'`. Found tooltips/popovers that might lack this setting.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by foxbg** [comment]
adding data-container="body" fixed the issue.
