### ISSUE TITLE
Top corners of singleton .list-group-item within a card aren't rounded

### ISSUE THREAD

**Issue by clurect** [twbs/bootstrap#18940]
A card that has a list in it will round the first li but if there is only one li (which can happen with dynamic data) the top is not rounded. I'll try to fix myself and submit a pull request
Here's an example I wrote up: http://codepen.io/clurect/pen/EPbpKE

**Comment by stephaniepurvis** [comment]
If you take off the "row" class on your "list-group-item", it seems to fix the problem. It looks like the row class is causing the list items to bust out of the card too. Do you need that row class for something specific?

**Comment by clurect** [comment]
Oh I was using a gird system, but I trimmed down my example to not have that, but left the row class in. In retrospect that may not be a good idea, but it might be a problem that could potentially use a fix.

**Comment by mdo** [comment]
Fixed with #19140.
