### ISSUE TITLE
[reboot] Consider use `margin-top` rather than `margin-bottom`

### ISSUE THREAD

**Issue by sodatea** [twbs/bootstrap#18958]
The comments in [_reboot.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L103) says

> By default, `<h1>`-`<h6>` all receive top and bottom margins. We nuke the top
> margin for easier control within type scales as it avoids margin collapsing.

This goal can also be achieved by using `margin-top` as long as it's consistent.

Besides, `margin-top` is much more intuitive and more useful for web layout.

For example: generally, an `h2` element is the title of the following paragraphs, so we may want to distinguish it from its preceding contents, that means, we need a margin between a whatever tag and `h2`. And most of the time, we want this margin's height to be consistent. This cannot be achieved by only using `margin-bottom`.

Actually, medium.com has already adopted this idea for their article layout (as far as I can see, there's no `margin-bottom` for any major block on [this page](https://medium.com/designing-medium/project-tnt-4b9b4ea97cda)).

**Comment by mdo** [comment]
> Besides, margin-top is much more intuitive and more useful for web layout.

I'd view that as more personal preference than anything else. When using typographic elements like headings in other instances, you might want *no* margin—top or bottom.

Thanks, but going to stick with `margin-bottom` for typography and ideally not setting any margin on other components whenever possible.
