### ISSUE TITLE
Missing Packagist versions

### ISSUE THREAD

**Issue by johnmadrak** [twbs/bootstrap#18950]
If you access the Packagist page (https://packagist.org/packages/twbs/bootstrap) you'll see that many of the versions are no longer present. 

When running composer with:
```
        "twbs/bootstrap": "3.0.0",
```

This error happens:
```
  Problem 1
    - The requested package twbs/bootstrap could not be found in any version, there may be a typo in the package name.
```

Which prevents composer from running successfully. 

It seems someone (with access) may need to manually update the Packagist information using the update button on their page.

**Comment by tmeliberty** [comment]
+1 there is only v4 dev versions

for v3 : you can temporarily specify the repository in your composer.json
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/twbs/bootstrap.git"
        }

**Comment by philipwhitt** [comment]
Same here. "twbs/bootstrap" : "3.3.6" was available just a few days ago, now it isn't...

**Comment by djalmaaraujo** [comment]
+1 same as @johnmadrak

**Comment by luiztiago** [comment]
+1 same here

**Comment by cvrebert** [comment]
Strange, we haven't changed anything on our end that would account for this.

**Comment by cvrebert** [comment]
Mashed the Update button on Packagist; all the v3 versions are on the Packagist page now.

**Comment by cvrebert** [comment]
Perhaps we were a victim of https://github.com/composer/packagist/issues/610

**Comment by johnmadrak** [comment]
@cvrebert Thanks for resolving this issue. Yes, it seems like that may have been the cause of this. Hopefully they'll come up with a solution to prevent this kind of issue in the future.
