### ISSUE TITLE
Tooltip bad position onto IE11 enterprise emulation mode IE8

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#18951]
Hello,

Seems to be an error into tooltip.js for position evaluation onto IE11 browser in IE8 document mode.
I've not seen this issue opened or fixed. 
I've put th sample code onto JSbin with the fix I've made: http://jsbin.com/hopelagiha/1/edit?html,output

Seems to be a reflow/redraw error of IE8 document mode, the first time the tooltip append in the dom getBoundingClientRect return a wrong left/right position. but the call to getBoundingClientRect invoke a reflow of the dom and the second call works well.

So i propose to add a call to getBoundingClientRect() when the first call return a null width Into the function "Tooltip.prototype.getPosition = function ($element) {" of tooltip.js :
 
.... Line 361 of tooltip.js
      if (elRect.width == null) {
        // Second call to getBoundingClientRect return the good width, only done if the first one failed
        elRect    = el.getBoundingClientRect()   
        // width and height are missing in IE8, so compute them manually; see https://github.com/twbs/bootstrap/issues/14093
        elRect = $.extend({}, elRect, { width: elRect.right - elRect.left, height: elRect.bottom - elRect.top })
...

**Comment by twbs-lmvtfy** [comment]
Hi @Lausselloic!

You appear to have posted a live example (http://jsbin.com/jacacoqema/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 42, column 7 thru column 309: Attribute ```` placeholder ```` not allowed on element ```` div ```` at this point.
* line 42, column 7 thru column 309: Attribute ```` width ```` not allowed on element ```` div ```` at this point.
* line 42, column 7 thru column 309: Attribute ```` tags ```` not allowed on element ```` div ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Lausselloic** [comment]
Fix HTML : http://jsbin.com/hopelagiha/1/edit bug reproduced

**Comment by twbs-lmvtfy** [comment]
Hi @Lausselloic!

You appear to have posted a live example (http://jsbin.com/hopelagiha/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 42, column 7: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` should only be used on `<input>`s, `<textarea>`s, and `<select>`s.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Lausselloic** [comment]
Fix HTML : http://jsbin.com/qaquhotiwi/1/edit bug reproduced

**Comment by cvrebert** [comment]
We don't support IE's emulation modes; see http://getbootstrap.com/getting-started/#support-ie-compatibility-modes
