### ISSUE TITLE
Box sizing not working for older Firefox versions.

### ISSUE THREAD

**Issue by codecrafting-net** [twbs/bootstrap#18977]
Since Firefox 29 does not require anymore the use of prefix -moz- for box-sizing property in css. I suggest to include in the code the `-moz-box-sizing` to avoid problems with older firefox versions.

**Comment by cvrebert** [comment]
Duplicate of #17237.
It's really not advisable to be running such old versions of Firefox...

**Comment by codecrafting-net** [comment]
I know that it's not advisable to use old versions of FIrefox, but that can happen and the 28 version is not that much old, I think that has no cost to add a -moz-box-sizing property. Many companies use old ESR versions and don't follow the update rhythm. I don' know, to me doesn't cost to add that. Sorry for the duplicated. My bad.
