### ISSUE TITLE
v4: General "label" for multi radio/checkbox

### ISSUE THREAD

**Issue by grizzm0** [twbs/bootstrap#18994]
Orphan "labels" next to multi-choice checkbox/radio are not aligned the same as form-control-label. Adding form-control-label also adds a padding-top which should not be there. See [docs example](http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid) or [screenshot](https://www.dropbox.com/s/gc1wr8j5raku073/Screenshot%202016-01-21%2014.33.18.png?dl=0).

The orphan label has class col-sm-2 with padding-left .9375rem while form-control-label has a padding-left of .75rem.

**Comment by patrickhlauke** [comment]
popping in the linked screenshot here

![screenshot 2016-01-21 14 33 18](https://cloud.githubusercontent.com/assets/895831/12481922/52f384da-c044-11e5-9b8c-1270dee99a15.png)

**Comment by Holt59** [comment]
There is already a pending pull-request for this: https://github.com/twbs/bootstrap/pull/18389

And another related issue: https://github.com/twbs/bootstrap/issues/17211

**Comment by patrickhlauke** [comment]
The label itself (which should actually be a `<legend>` in this case) is fixed here https://github.com/twbs/bootstrap/pull/19277 (but that fix exposes a problem with "naked" radio not having the same top padding, so more work needed on that in https://github.com/twbs/bootstrap/pull/19141)
