### ISSUE TITLE
.btn inside .form-group does not respect margin-bottom

### ISSUE THREAD

**Issue by victoriafrench** [twbs/bootstrap#18999]
`input`, `select` and such inside a `.form-group` are defined with a `margin-bottom` of 15px. But a `btn` has a `margin-bottom` of 0. There is no definition of `.form-group .btn` to override the margin to align the button with all other elements.

**Comment by cvrebert** [comment]
@victoriafrench Please post a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by victoriafrench** [comment]
http://stackoverflow.com/questions/34934156/bootstrap-input-button-not-aligning-with-other-fields

**Comment by victoriafrench** [comment]
user in post presented this [fiddle](https://jsfiddle.net/yzw8q28q/5/).

**Comment by twbs-lmvtfy** [comment]
Hi @victoriafrench!

You appear to have posted a live example (https://fiddle.jshell.net/yzw8q28q/5/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 60, column 5 thru column 129: Attribute ```` placeholder ```` not allowed on element ```` select ```` at this point.
* line 76, column 7 thru column 131: Duplicate ID ```` filter_discipline_id ````.
* line 76, column 7 thru column 131: Attribute ```` placeholder ```` not allowed on element ```` select ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by victoriafrench** [comment]
ignoring not my example

**Comment by cvrebert** [comment]
If you're posting it, then it's your example for our purposes.

**Comment by cvrebert** [comment]
After fixing the invalid HTML for you: https://jsfiddle.net/cvrebert/ebyak0jc/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/cvrebert/ebyak0jc/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 76, column 7: [E006](https://github.com/twbs/bootlint/wiki/E006): `.input-group` contains a `<select>`; this should be avoided as `<select>`s cannot be fully styled in WebKit browsers
* line 73, column 1: [E010](https://github.com/twbs/bootlint/wiki/E010): Input groups cannot contain multiple `.form-control`s
* line 67, column 5: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`
* line 83, column 7: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`
* line 73, column 1: [E044](https://github.com/twbs/bootlint/wiki/E044): `.input-group` must have a `.form-control` and either an `.input-group-addon` or an `.input-group-btn`.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@victoriafrench Could you please post a new, different example? The StackOverflow one has several unrelated errors and seems overly complicated given your original simple description.

**Comment by victoriafrench** [comment]
Closing issue. Just discovered that the css the person is using does not match the released version. It has been modified. Also verified in less files that classes that appear in the css do not exist in github.
