### ISSUE TITLE
is clearfix missing code?

### ISSUE THREAD

**Issue by Bartmax** [twbs/bootstrap#18996]
Why clearfix was changed on v4? 

original:
``` 
.clearfix:before,
.clearfix:after {
    content: " "; 
    display: table;
}

.clearfix:after {
    clear: both;
}
``` 

https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_clearfix.scss
right now is
```
@mixin clearfix() {
  &::after {
    content: "";
    display: table;
    clear: both;
  }
}
```

**Comment by mrmlnc** [comment]
Your first version (original) supports IE8. In Bootstrap 4 refused to support IE below 9 version. This version Clearfix does not support IE9. See ["Beat That ClearFix", a clearfix for modern browsers](http://stackoverflow.com/questions/211383/which-method-of-clearfix-is-best)

**Comment by mdo** [comment]
^^^ Yup, that :D.

**Comment by thierryk** [comment]
Thanks @mrmlnc for the plug but my latest recommendation is to use `display:block` instead of `display:table`; check [The very latest `clearfix` reloaded](http://www.cssmojo.com/the-very-latest-clearfix-reloaded/). 
I'll create an issue.
