### ISSUE TITLE
Unable to customize `.carousel-indicators` class because it's used for presentation and behavior

### ISSUE THREAD

**Issue by Bartmax** [twbs/bootstrap#18995]
the class `.carousel-indicators` have los of css styles attached for positioning.
if ones want to customize the appearance, you probably cant use the `.carousel-indicators` class.

for example, if you want to use grid classes like `.col-sm-offset-3`, it wont work because the margins will get all wrong.

removing `carousel-indicators` class so you can have your own 'custom-carousel-indicators' makes carousel indicators stop working because javascript use the class to access the items inside with no option to choose a selector on initialization. (or I didn't see it mentioned in the docs).

Some suggestions

1) use 2 classes, one for presentation and other for behavior

``` html
<ol class="col-sm-8 col-sm-offset-4 carousel-indicators carousel-indicators-default">
    <!-- li items -->
</ol>
```

2) allow initialization of component to specify a class for indicators.

``` html
<ol class="col-sm-8 col-sm-offset-4 custom-carousel-indicators">
    <!-- li items -->
</ol>
```

``` js
$('.carousel').carousel({indicators: '.custom-carousel-indicators'});

```

**Comment by mdo** [comment]
Going to close this as a won't fix actually; we have the same problem for all our selectors in our carousel JS and I don't foresee us adding additional classes or data attributes to address them all.
