### ISSUE TITLE
v4: Clarify custom stylesheet usage

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#18997]
It's not for writing new styles, it's for modifying variables. We should rename it to be something like `_variables-overrides.scss` or something. Also will need to update/add docs for this.

See #18993.

**Comment by sergej2705** [comment]
Sorry, but you misunderstood the issue behind https://github.com/twbs/bootstrap/issues/18993 the usage of the `_custom.scss` is very clear...

**Comment by lucasgladding** [comment]
FWIW, I agree about the renaming.  

For #18993, I think that's just a documentation issue, though nothing specific to Bootstrap. You can't reference variables that are not yet defined (i.e. $spacer).  In this case, you would just need to define $spacer before using it.
