### ISSUE TITLE
`bower install bootstrap` downloading jQuery@2.2.0

### ISSUE THREAD

**Issue by adam-beck** [twbs/bootstrap#19008]
When using the command `bower install --save bootstrap` I noticed that it is downloading `jquery@2.2.0`. From my understanding, the dependency on jquery `1.9.1 - 2` does not make sense to bower [source](https://github.com/npm/node-semver#ranges). Maybe the confusion is coming from npm which does allow for the `version1 - version2` syntax [source](https://docs.npmjs.com/files/package.json#dependencies). I'm not sure.

### Steps to reproduce

- From an empty directory `bower init`; (proceed through questions using defaults)
- `bower install --save bootstrap`
-  `cd bower_components/jquery/dist`
- Open `jquery.js`
- Notice that the version listed at the top is `2.2.0`

Am I correct in assuming the desired effect of `1.9.1 - 2` would include versions from `1.9.1` up to (and including) `2.0.0`.

> version1 - version2 Same as >=version1 <=version2
[from here](https://docs.npmjs.com/files/package.json#dependencies)

and
 
> If a partial version is provided as the first version in the inclusive range, then the missing pieces are replaced with zeroes.
1.2 - 2.3.4 := >=1.2.0 <=2.3.4
[from here](https://docs.npmjs.com/misc/semver)

Also note that the version of bootstrap is `~3.3.6` in the bower.json file

**Comment by cvrebert** [comment]
> From my understanding, the dependency on jquery `1.9.1 - 2` does not make sense to bower

It does make sense to Bower.
See https://github.com/bower/spec/blob/master/json.md#dependencies
Furthermore, Bower is implemented using `node-semver` (see https://github.com/bower/bower/blob/9d2681b0c4c02c7abd4a273b3188491840ed6341/package.json#L54 ), the same library that powers npm's version syntax.

> Am I correct in assuming the desired effect of `1.9.1 - 2` would include versions from `1.9.1` up to (and including) `2.0.0`.

It's canonically equivalent to `>=1.9.1 <3.0.0`
(jQuery 2's API is compatible with jQuery 1.9's, it just drops support for old versions of IE. Official blog posts about jQuery 3 indicate that it will include some backward-incompatible API changes.)

> If a partial version is provided as the first version in the inclusive range

The partial version is the **second** version in the inclusive range in our case.

**Comment by adam-beck** [comment]
Wow okay after searching through more of the documentation:

> If a partial version is provided as the second version in the inclusive range, then all versions that start with the supplied parts of the tuple are accepted, but nothing that would be greater than the provided tuple parts.

> 1.2.3 - 2.3 := >=1.2.3 <2.4.0
> 1.2.3 - 2 := >=1.2.3 <3.0.0

That's pretty confusing because they explicitly say:

> version1 - version2 Same as >=version1 <=version2

Followed by

> If a partial version is provided as the first version in the inclusive range, then the missing pieces are replaced with zeroes.

So in this case the partial version would be `2.x.x ==> 2.0.0`

`1.9.1 - 2.0.0`
Then becomes:
`>=1.91 <=2.0.0`


Thank you for clarifying that though. I had not seen this range syntax before.

**Comment by iyogeshjoshi** [comment]
It's doing the same thing with me, it's installing `v2.2.0` instead of `v1.9.1` though I don't have any problem with this, it's just `bootstrap` is not working with any other version other than `v1.9.1`. I'm using `bootstrap#3.3.6` it say it's compatible with all version `<3.x` I tried with many but it's only working with `v1.9.1`. I think this is a compatibility issue :confused:
