### ISSUE TITLE
Initial render of Accordion in Meteor behaves incorrectly

### ISSUE THREAD

**Issue by mroftalp** [twbs/bootstrap#19009]
3 panels. When clicking on the 2nd panel and with just a bit of a second to also click the 3rd panel both of them will open. Same as this one: https://github.com/twbs/bootstrap/issues/2941 although I'm using Meteor.js and using a package twbs:bootstrap.

**Comment by cvrebert** [comment]
@mroftalp Have you tried duplicating the problem without Meteor? Are you using Bootstrap v3.3.6?

**Comment by mroftalp** [comment]
It says the package version is 3.3.5*

**Comment by cvrebert** [comment]
3.3.6 is available (see https://atmospherejs.com/twbs/bootstrap), so please upgrade.

**Comment by mroftalp** [comment]
I just upgraded. Still happens. It only happens on the first render of the template. Then it never happens after that.

**Comment by mroftalp** [comment]
Thanks for the rename. That makes more sense.

**Comment by cvrebert** [comment]
Core Team doesn't use Meteor, so CCing @splendido & @dandv

**Comment by cvrebert** [comment]
@mroftalp Posting a complete minimal demo of the problem would be helpful. Also, does the problem occur in all browsers?

**Comment by mroftalp** [comment]
I'm using chrome. Also able to duplicated the error in safari. So quite sure also would happen in other browser.

**Comment by mroftalp** [comment]
"complete minimal demo of the problem" what do you mean? Screenshot?

**Comment by cvrebert** [comment]
@mroftalp Code. Can't debug a screenshot.

**Comment by cvrebert** [comment]
> I'm using chrome. Also able to duplicated the error in safari.

Those are both WebKit/Blink-based browsers, so that doesn't say a whole lot. Could you try Firefox, IE, or Edge?

**Comment by mroftalp** [comment]
```
<div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    <h4 class="panel-title">
                        <a>
                            Panel 1
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" style="height: auto;">
                    <div class="table-container">
                        <table class="table">
                            <tbody>
                                <!-- my content -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                    <h4 class="panel-title">
                        <a>
                            Panel 2
                        </a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" style="height: 0;">
                    <div class="table-container">
                        <table class="table">
                            <tbody>
                                <!-- my content -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                    <h4 class="panel-title">
                        <a>
                            Panel 3
                        </a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" style="height: 0;">
                    <div class="table-container">
                        <table class="table">
                            <tbody>
                                <!-- my content -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
```

Pretty much from bootstrap example.

**Comment by mroftalp** [comment]
Also happens in Firefox.

**Comment by splendido** [comment]
@mroftalp are you initializing you accordion with the [collapse plugin](http://getbootstrap.com/javascript/#collapse-usage)?

If you're using Blaze, you should have it into a stand-alone template and put the initialization into the `onRendered` hook:

HTML
```html
<template name="myAccordion">
  <div class="panel-group" id="accordion">
    <!--
    ... ... ...
    -->
  </div>
</template>
```

JS
```javascript
Template.myAccordion.onRendered(function() {
  // Initialize collapse plugin from bootstrap
  this.$('.collapse').collapse();
});
```

Lets have a look at the documentation for [onRendered](https://docs.meteor.com/#/full/template_onRendered) hook.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
