### ISSUE TITLE
Not working in Meteor in production mode

### ISSUE THREAD

**Issue by mazing** [twbs/bootstrap#19020]
When using `twbs:bootstrap@=4.0.0-alpha2`, it works locally, but my page is blank when used in production mode (`meteor --production`) or deployed (`meteor deploy _.meteor.com`).

**Comment by Lidofernandez** [comment]
I'm having some related issue because It works locally but in production It give a message of "Oops, looks like there's no route on the client or the server for url: someurl.com". The issue is solved once I removed the package and add the old one.

**Comment by cvrebert** [comment]
CC: @dandv @splendido

**Comment by mdo** [comment]
Closing as stale. I'm assuming we're good to go here now since we haven't heard anything in nine months.
