### ISSUE TITLE
Dropdowns in navbars

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19027]
Currently there is no documentation for dropdown in navbar, however, there is this example http://www.quackit.com/html/html_editors/scratchpad/?example=/bootstrap/bootstrap_4/tutorial/bootstrap_4_navbars_dropdown_menus

It works good and same way I have rewritten old bs3 code for bs4 but now dropdown is in front of navbar and overlaps at top. I need to render dropdown behind navbar and z-index is not working and I can't figure out why. dropdown already have z-index 2 and nav - z-index 3.

However, looking on old bs3 example https://getbootstrap.com/examples/navbar/ navbar have no top/bottom padding and it is easier to position dropdown. In old examples there is also `.navbar-nav > li > .dropdown-menu` nested selector which removes top right/left border-radius etc. I could agree that this option probably would not fit bs4 class structure but navbar is a component and it can have it's own dropdowns.

How do you plan to structure dropdown in navbar and what about navbar padding?

Also I haven't found any examples how to make old bs3 responsive navbar with hamburger like in the same example https://getbootstrap.com/examples/navbar/ Is it currently possible?

**Comment by cvrebert** [comment]
v4's navbars overall are still a work-in-progress. See #18467.

> Also I haven't found any examples how to make old bs3 responsive navbar with hamburger

There is http://v4-alpha.getbootstrap.com/components/navbar/#collapsible-content , although making the items stack like in v3 hasn't been implemented yet; see #17250.
