### ISSUE TITLE
[v4, new feature] create "up" set of classes in grid system

### ISSUE THREAD

**Issue by bkCDL** [twbs/bootstrap#19023]
I like the new "up" feature for responsive classes in v4. It's great!

Would it be possible to have a parallel "up" set of classes for the grid system? This would allow me to specify one setting for x-small devices and just one class for small, medium, large inclusively.

So instead of this
`<div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">`
I could do this?
`<div class="col-xs-6 col-sm-up-3">`

Bryan

**Comment by cvrebert** [comment]
v3's and v4's grid `.col-*` classes already work like "up" classes; they aren't "only" classes.
See also https://github.com/twbs/bootlint/wiki/E029
