### ISSUE TITLE
Dropdown: Toggling behavior on keydown is inconsistent and does not focus on first item

### ISSUE THREAD

**Issue by aminimalanimal** [twbs/bootstrap#19034]
**Related to [#14646: Escape key should only close Dropdown](https://github.com/twbs/bootstrap/issues/14646), which was closed in [this commit](https://github.com/twbs/bootstrap/pull/14722)**.
### Current behavior

Currently, when a user is focused on a `button` with `data-toggle="dropdown"`, the associated dropdown can be opened and closed by pressing <kbd>enter</kbd>, but pressing <kbd>space</kbd> will either open the dropdown or (if already open) focus on the first item.
### Expected behavior

According to the [W3's guide on using ARIA menus](https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus#Example_Keyboard_Behavior), both <kbd>enter</kbd> and <kbd>space</kbd> should open and close the dropdown. When opening, the first item should automatically be focused.

**Note**: This guide also states that <kbd>up</kbd> and <kbd>down</kbd> should open the menu. I disagree with this as it will negatively impact browsing modes in both NVDA and VoiceOver (when QuickNav is enabled).

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by patrickhlauke** [comment]
sorry for late reply. note that bootstrap's dropdowns are not strictly ARIA menus anymore - note the removal of the various `role="menu"` and `role="menuitem"` that was carried out some time ago (can't find the commit off-hand, but happy to dig it up if necessary). reason for that change was that ARIA menus have fairly rigid rules about what is and isn't allowed (`menuitem`, `menuitemcheckbox`, `menuitemradio`, sub-menus, ...), but that bootstrap's dropdowns are commonly used for other things that go beyond this particular pattern, and having the `role="menu"` with such non-conformant items actually resulted in confusing and unusable behavior in AT. in effect, bootstrap's dropdowns are now simply generic disclosure widgets. for that reason, the recommended interactions outlined for ARIA menus don't strictly apply here. having said all that, it may well be worth revisiting some of the keyboard interactions in v4 to ensure they're consistent/predictable

**Comment by vanduynslagerp** [comment]
For information in the current code on v4-dev the keyboard interaction to navigation the menu still requires either `role="menu"` or `role="listbox"`.
See [dropdown.js#L271](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L271) and [dropdown.js#L272](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L272) 
Although `role="menu"` or `role="listbox"` are required only for navigation and not to open the menu with keyboard when  `data-toggle="dropdown"` is focused.

Is it the intended behavior ? Or should `role="menu"` or `role="listbox"` be replaced by `.dropdown-menu` ?
Let me know, I can make a PR.

**Comment by Johann-S** [comment]
@patrickhlauke what's the decision about this issue ? 
Should we open menu on `enter`, `space` and `up`/`down` ? + Add a focus on the first item ? 

#21535 removed reliance on roles but the behavior isn't the good one described by @aminimalanimal

**Comment by patrickhlauke** [comment]
with the `role="menu"` and `role="menuitem"` gone, the cursor behavior is not necessary. however, if the menu trigger is something like a link, but with `role="button"`, it should also trigger on `space` (like real buttons do).

**Comment by mdo** [comment]
Let me know what y'all would like to do here. For now I've de-prioritized this and removed it from the Beta 1 project.

**Comment by patrickhlauke** [comment]
This can be closed, as we now removed the ARIA menu stuff, and the keyboard behavior has been normalised (both `enter` and `space` behave the same)
