### ISSUE TITLE
Bootstrap popover title option do not override the html element title

### ISSUE THREAD

**Issue by belov91** [twbs/bootstrap#19039]
I'm initializing Bootstrap's popovers like this:

http://stackoverflow.com/questions/35032922/bootstrap-popover-title-option-do-not-override-the-html-element-title/35033149?noredirect=1#comment57792150_35033149

The problem is that the title that I set in jQuery do not override the button title attribute.

Any ideas?

**Comment by patrickhlauke** [comment]
As per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker please ask these sorts of support questions (rather than bug reports on Bootstrap itself) on StackOverflow or similar. Thanks.

**Comment by cvrebert** [comment]
Duplicate of #18329.
