### ISSUE TITLE
Vertical alignment in .input-group-addon broken in flexbox mode

### ISSUE THREAD

**Issue by atu-record** [twbs/bootstrap#19044]
Hi,

![image](https://cloud.githubusercontent.com/assets/16321313/12640351/bb85ec12-c5a9-11e5-90fb-9b593db70bdf.png)

In flexbox mode the linehight should inherit the body value to be properly shown.

**Comment by cvrebert** [comment]
@atu-record What browser are you using? Are you using Bootstrap v4.0.0-alpha.2, or the bleeding-edge `v4-dev` branch?

**Comment by atu-record** [comment]
chrome, alpha.2

**Comment by atu-record** [comment]
sorry my bad, seems to be fixed in ```v4-dev```
