### ISSUE TITLE
Recommended way to add margin-top in main container?

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19046]
Right now there is no default or recommended way for adding margin-top for main content inside .container.

Example markup with card as main wrapper now looks like
```
... nav ...
<main class="container">
  <div class="card card-block">
     ... content ...
  </div>
</main>
.. footer ...
```

.card have margin-bottom but first card in main container does not have margin-top.

Another your example http://v4-alpha.getbootstrap.com/examples/dashboard/ in which you manually added .main padding 20px.

I have some options on adding top margin for main container:

A. Something like:
```
.container > .card:first-of-type {
  margin-top: $card-spacer-y;
 }
```

B. Using new utility class for margin like `card card-block m-t-1`

C. Adding new class `.container-main` or just `.main` and add top padding probably with new variable.

D. Adding .card-block to container like `container card-block`

What are your thoughts or recommendations on how to do it better?

**Comment by mdo** [comment]
This is a layout and project specific question, so there nothing for us to really document on our end for that. Any of those options works and just depends on your overall approach :).
