### ISSUE TITLE
Feature request: Multilevel dropdowns

### ISSUE THREAD

**Issue by GKMelbo** [twbs/bootstrap#19059]
One of the things I really missed in Bootstrap 3 was the ability to add multilevel dropdowns. It would be really nice not having to look for extensions to allow this, as it makes it even harder to convert to WordPress. I'm still pretty new to coding, so it might just be me...

**Comment by MrGeneric** [comment]
This has been requested in the past. You can read some of the previous responses here:

https://github.com/twbs/bootstrap/issues/424
https://github.com/twbs/bootstrap/issues/160

**Comment by GKMelbo** [comment]
Oh, Sorry!
