### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'"

### ISSUE THREAD

**Issue by willyelm** [twbs/bootstrap#19062]
Getting Error: Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'"

When using the server header: 

Header set Content-Security-Policy: "default-src 'self' 'unsafe-inline'"

https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js#L121

**Comment by cvrebert** [comment]
Duplicate of #17964.
