### ISSUE TITLE
Other table modifier classes don't work in combination with .table-inverse

### ISSUE THREAD

**Issue by wayneashleyberry** [twbs/bootstrap#19064]
The various modifier classes for tables, `table-striped`, `table-hover` etc. don't work on inverse tables.

https://jsfiddle.net/toorL6y0/

**Comment by mishra-ankit** [comment]
Even without `.table-inverse` : `.table-hover` doesn't seem to be working!!
Am I missing something here ?

https://jsfiddle.net/cryostat/toorL6y0/2/
http://getbootstrap.com/css/#tables-hover-rows
http://v4-alpha.getbootstrap.com/content/tables/#hoverable-rows

Seems like the actual color and hover color are same. As a result on hovering, no difference in the row background color is observed.
```css
.table-hover>tbody>tr:hover {
    background-color: #f5f5f5
}
```

**Comment by wayneashleyberry** [comment]
@mishra-ankit `.table-hover` is working fine for me on non inverse tables... which browser are you using?

**Comment by mishra-ankit** [comment]
Sounds really strange to me as well, either some display issue on my machine or I'm losing my color perception. Will try on another machine and get back here.
(Currently using : _Chrome 39.0.2171.95 m on Windows 7_)

**Comment by mishra-ankit** [comment]
@wayneashleyberry  Checked on another device, results same as you reported.
Its still a mystery for me. Removing previous comments to avoid confusion.

**Comment by mdo** [comment]
Done in d74a897.
