### ISSUE TITLE
<progress> bar rounding cut off when max != 100

### ISSUE THREAD

**Issue by bschaeffer** [twbs/bootstrap#19065]
When a `<progress>` element's `max` attributes is over **100**, the rounding is cutoff.

For me, this issue popped up when I was displaying progress bars in a `table.table` element, but occurs outside of it as well. Here's an example:

http://www.bootply.com/X7zC8gJyLG

![Example Image](https://api.monosnap.com/rpc/file/download?id=MLICaEjnz0SMBka8OclgxkPhVQbvph)

Though most examples of `progress` elements on the web use a max value of **100**, I could find no documentation that **100** is the max allowed value.

**Comment by twbs-lmvtfy** [comment]
Hi @bschaeffer!

You appear to have posted a live example (http://s.bootply.com/render/X7zC8gJyLG), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 43, column 16 thru line 44, column 26: ```` th ```` start tag in table body.
* line 52, column 17 thru column 55: Element ```` div ```` not allowed as child of element ```` progress ```` in this context. (Suppressing further errors from this subtree.)
* line 64, column 17 thru column 55: Element ```` div ```` not allowed as child of element ```` progress ```` in this context. (Suppressing further errors from this subtree.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bschaeffer** [comment]
Revised example: http://www.bootply.com/X7zC8gJyLG

**PS:**
* Error 1: [Tables > Basic Example](http://v4-alpha.getbootstrap.com/content/tables/#basic-example)
* Error 2 & 3: [Progress Bar > IE](http://v4-alpha.getbootstrap.com/components/progress/#ie9-support)

**Comment by twbs-lmvtfy** [comment]
Hi @bschaeffer!

You appear to have posted a live example (http://s.bootply.com/render/X7zC8gJyLG), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 43, column 16 thru line 44, column 26: ```` th ```` start tag in table body.
* line 52, column 17 thru column 55: Element ```` div ```` not allowed as child of element ```` progress ```` in this context. (Suppressing further errors from this subtree.)
* line 64, column 17 thru column 55: Element ```` div ```` not allowed as child of element ```` progress ```` in this context. (Suppressing further errors from this subtree.)

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bschaeffer** [comment]
Ugh: http://www.bootply.com/E0twbUEAoy

**Comment by twbs-lmvtfy** [comment]
Hi @bschaeffer!

You appear to have posted a live example (http://s.bootply.com/render/E0twbUEAoy), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 40, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 67, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 73, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by bschaeffer** [comment]
This is stupid

**Comment by wolfy1339** [comment]
Fixed up example: http://www.bootply.com/HgDioZygC1

**Comment by cvrebert** [comment]
Looks like the current code assumed that `value` was always a percentage and didn't account for `max`:
https://github.com/twbs/bootstrap/blob/6384789f952c297356a94aded5900d199d09ae87/scss/_progress.scss#L46-L52

Perhaps we should just always apply the `border-radius` regardless of the fill level?

**Comment by eliottrobson** [comment]
I think always applying it would be the best option. #18835 discusses the potential to stacking and the main discussion is, are we planning on bringing stacking progress bars back? If we are then the progress element itself becomes irrelevant because it's non supporting.

Personally, I think that stacked progress bars add a layer of confusion and are not necessary. They are rarely used as "progress" bars when done in this way from what I've seen. It might be worth considering implementing a different component but to be honest, I haven't seen them used enough for it to be worth it.

**Comment by cvrebert** [comment]
> are we planning on bringing stacking progress bars back?

Probably. But that doesn't imply dropping support for `<progress>` for non-stacked bars.

**Comment by patrickhlauke** [comment]
...just to point out that providing a sensible, live-updating and screenreader friendly way of providing stacked bars is...non-trivial ;)

**Comment by cvrebert** [comment]
"Include a screenreader-only `<table>` with the same data, sprinkle with ARIA attributes, and pray to the dark god Cthua11yhu?" 😜

**Comment by patrickhlauke** [comment]
heh, indeed. in seriousness, if it's only a stack of 3-4 different bars, it possibly best to make it a visually hidden live region that reads the whole thing as one short sentence ("foo: 10%; bar: 23%; baz: 92.4%") but once you have more separate elements, it starts getting really tricky...
