### ISSUE TITLE
sourcemap references and CDNs result in 403 responses

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#19063]
wondering if - at least for CDN versions - there's a way of suppressing sourcemap references to files which aren't available (and result in 403 responses, which get silently absorbed by Chrome/Firefox/Safari dev tools but are - correctly? - exposed by Edge's dev tools) - see http://stackoverflow.com/questions/35142485/why-is-bootstrap-trying-to-load-less-files-in-edge/35151109

/cc @mdo @cvrebert

**Comment by patrickhlauke** [comment]
xref https://github.com/MaxCDN/bootstrap-cdn/issues/629

**Comment by cvrebert** [comment]
I think there's a config option somewhere to stuff copies of the source files into the sourcemap itself so it doesn't reference any external files. We could try that.

**Comment by jdorfman** [comment]
@patrickhlauke @cvrebert any updates?

**Comment by patrickhlauke** [comment]
@jdorfman, i think @cvrebert is your man on this one, as I have zero clue about grunt, sourcemaps, etc

**Comment by cvrebert** [comment]
I'm currently in transit. Will have a go at this in a couple hours when I reach my destination though.

**Comment by jdorfman** [comment]
@cvrebert let me know if @jmervine can be of any assistance. Thanks

**Comment by cvrebert** [comment]
Fixed in v3 via #20258.
A v4 fix is still on our TODO.

**Comment by mdo** [comment]
Was this ever addressed for v4?

**Comment by mdo** [comment]
Gah, tried to straight move it over and in my rush missed all the Grunt errors :grin:. Will revisit for v4.

**Comment by Delagen** [comment]
I think package.json section should include js.map files
```
 "files": [
    ".babelrc",
    ".eslintignore",
    "Gruntfile.js",
    "dist",
    "build",
    "js/.eslintrc.json",
    "js/**/*.js",
    "js/**/*.js.map", //source-map
    "scss/.scss-lint.yml",
    "scss/**/*.scss",
    "LICENSE"
  ],
```

**Comment by XhmikosR** [comment]
I believe I have enabled all the related switches without knowing about this issue some time ago (see #23255), and source files are embedded in map files.

@Delagen: you are welcome to make a new issue or a PR.
