### ISSUE TITLE
Escape doesn't close dropdown in Chrome

### ISSUE THREAD

**Issue by jeznag** [twbs/bootstrap#19071]
![escape doesn t close in chrome](https://cloud.githubusercontent.com/assets/1034890/12774551/1e9d895a-ca9a-11e5-9e7e-eae5945e6503.gif)

If you open a dropdown from http://getbootstrap.com/components/#btn-dropdowns and press escape, it doesn't close it in Chrome. You have to press it twice.

It works fine in Firefox.

Am running Chrome 48.0.2564.97

**Comment by mishra-ankit** [comment]
Working fine for me (Chrome  39.0.2171.95 m/ Windows).
Could you share what Chrome version you are using ?

**Comment by cvrebert** [comment]
@jeznag What OS are you running?

**Comment by jeznag** [comment]
OSX 10.10.5

**Comment by cvrebert** [comment]
@jeznag I can't reproduce on OS X 10.11.3, Chrome 48.0.2564.97. Perhaps I'm not getting something in your screencast. Could you give step-by-step instructions to reproduce the problem?

**Comment by jeznag** [comment]
Was an extension messing with it. Sorry for the time wastage  :(
