### ISSUE TITLE
Is there a way to make the mouse focus on the first modal when I close a modal that was inside another modal? 

### ISSUE THREAD

**Issue by InnocentMonareng** [twbs/bootstrap#19073]
After creating a button inside a modal that will pop another modal and close the latter modal, the mouse now focuses on the main page in-which you find the button to open the first modal. However this first modal is still visible on the screen, you just cannot scroll the modal up and down using the mouse scroll wheel or up and down keys on the keyboard (if you try to that you can see the main page in the background scrolling up and down). The buttons that pops the last modal inside this modal still works though. In order to scroll up and down again on the first modal, you need to close the modal and then open the modal again. 

Is there a way to make the mouse or keyboard focus on the first modal when I close the latter modal?

**Comment by patrickhlauke** [comment]
I'm afraid Bootstrap does not officially support multiple simultaneous modals. I'd suggest asking on StackOverflow or similar for a possible solution. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by cvrebert** [comment]
See also http://getbootstrap.com/javascript/#callout-stacked-modals
