### ISSUE TITLE
Disabled button (e.g. delete) is always triggered

### ISSUE THREAD

**Issue by nckarmelk** [twbs/bootstrap#19074]
Disabled button (e.g. delete) is always triggered. 

Button:

<btn class="btn btn-sm btn-danger pull-right" id="btnDelete" title="Delete Item"><i class="fa fa-trash-o fa-lg"></i></btn>

The button looks disabled (also an icon appears) but the javascript function at onClick is still executed:

$('#btnDelete').click(function () {
            confirmDelete();
        });

Disable with:

$("#btnDelete").attr('disabled', 'disabled');

Works fine in Bootstrap 3.3.4, not in 3.3.6

Tested (and not working) in:
- IE11
- Chrome
- Firefox

**Comment by nckarmelk** [comment]
Button tag:

<btn class="btn btn-sm btn-danger pull-right" id="btnDelete" title="Delete Item"><i class="fa fa-trash-o fa-lg"></i></btn>

**Comment by nckarmelk** [comment]
Button Tag:
`<btn class="btn btn-sm btn-danger pull-right" id="btnDeleteCatalog" title="Delete Sub-Catalog"><i class="fa fa-trash-o fa-lg"></i></btn>`

**Comment by nckarmelk** [comment]
Button tag:
`<btn class="btn btn-sm btn-danger pull-right" id="btnDelete" title="Delete Item"><i class="fa fa-trash-o fa-lg"></i></btn>`

**Comment by patrickhlauke** [comment]
assuming you're using `<button>` and not `<btn>` as an element? otherwise, I'd start looking at that...

**Comment by patrickhlauke** [comment]
anyway, can't seem to reproduce (and my guess is you used `<btn>` instead of `<button>` ?) https://jsfiddle.net/tv7fcm2a/

**Comment by twbs-lmvtfy** [comment]
Hi @patrickhlauke!

You appear to have posted a live example (https://fiddle.jshell.net/tv7fcm2a/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 71, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
Ah, forgetful me... tweaked https://jsfiddle.net/tv7fcm2a/1/
