### ISSUE TITLE
Create mixin 'opacity' for compatibility reasons

### ISSUE THREAD

**Issue by mep253** [twbs/bootstrap#19080]
Migrating from Bootstrap 3 fails on missing mixin 'opacity'. 
Instead of the missing one:
// Opacity
  236: @mixin opacity($opacity) {
  237:   opacity: $opacity;
  238    // IE8 filter
  239:   $opacity-ie: ($opacity * 100);
  240:   filter: unquote("alpha(opacity=#{$opacity-ie})");
  241  }

you could add something simple like this, only for compatibility reasons:
@mixin opacity($opacity) {
     opacity: $opacity;
 }

**Comment by mdo** [comment]
Dump the mixin, it's unnecessary in v4. No reason to migrate and keep it around :).
