### ISSUE TITLE
addition of upper and lower case text variables

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#19081]
I would like to propose adding additional `_variables.scss` to be baked into b4. I have been finding these two variables quite handy.
```
$text-uppercase:    uppercase !default;
$text-lowercase:    lowercase !default;
```

I'm sure there could be more but definitely cuts down on time.

**Comment by mdo** [comment]
How does this cut down on time?

**Comment by guylepage3** [comment]
How I approach the `_variables.scss` file is a design checklist. What do I want to add (modify) to make this particular project unique. Adding the uppercase and lowercase variables to the the `_variables.scss` file would help inspire a designer to utilize casing for in their designs.

Bootstrap may be a framework, but let's not forget the beauty of it is that any designer can take it, modify it and build something unique with it. The more unique projects become, the more bootstrap becomes solidified as the default front-end framework for projects.

I also feel that it is a frictionless way to add uppercase to my mixins, for example.

**Comment by cvrebert** [comment]
Having `$text-uppercase` potentially not be `uppercase` seems confusing to me. Variables like `${component}-text-transform` would seem clearer.

But I note that the only uses of `uppercase` and `lowercase` in Bootstrap itself are in `.initialism` and the casing utility classes `.text-lowercase` & `.text-uppercase`.

**Comment by guylepage3** [comment]
Yeah. I suppose they can be called:
```
$text-transform-upper:    uppercase !default;
$text-transform-lower:    lowercase !default;
```

**Comment by guylepage3** [comment]
Let me know if you'd like me to do a pull-request.

**Comment by patrickhlauke** [comment]
i really don't understand what this tries to accomplish. a designer would still have to - if they decided to use this - write specific styles like `text-transform: $text-transform-upper` or whatever in their specific stylesheets/additions...at which point, they're quicker just writing `text-transform: uppercase` ... or am i missing something here?

**Comment by guylepage3** [comment]
sorry it should be;
```
$text-casing:    uppercase !default;
```
This would allow you to apply uppercase or lowercase to multiple items throughout the site and make one simple change in `_variables.scss`

**Comment by AustinPaquette** [comment]
I don't think that would be all that useful to have in the bootstrap core though, I mean... what kind of odds are we talking about that you'd have to do a mass switch from uppercase to lowercase (or any of the others for that matter) enough times to warrant a variable for it.

I don't find this being overly useful - or very applicable - to anything other than the odd niche projects (in which case adding this is not overly inconvenient anyhow) but I'm more than willing to be proven wrong on that.

**Comment by guylepage3** [comment]
Uppercase and lowercase are core elements in typography.

Also, upper and lower casing is a big part in quite a few brands. So to discard this by saying, "...what kind of odds are we talking about that you'd have to do a mass switch from uppercase to lowercase..." is not a great argument.

Here are a couple super quick examples;
*Uber* - http://driveubernyc.com/#driving-with-uber
*InVision* - http://www.invisionapp.com/
*Hotel Tonight* - https://www.hoteltonight.com/

That was a couple quick searches. I feel this is extremely useful on a regular basis.

**Comment by patrickhlauke** [comment]
but unless you specify separate variables for every single type of element/content block (e.g. `$text-casing-h1`, `$text-casing-h2`, etc) how are you expecting to implement this single variable in practice?

**Comment by patrickhlauke** [comment]
and what does having it as variable do that having a few lines of custom CSS like `h1, h2, h3 { text-transform: uppercase; }` doesn't ? i still don't see any advantage here to abstract it into variables...

**Comment by guylepage3** [comment]
You would need to do that and that would be customized on a per project basis. Or we could do all the hard work for the user by having a default `_headings.scss` mixin that would allow the user to change `$text-casing` and it would be imported into the mixin. That would be a huge help for the user.

One thing bootstrap tends to neglect is actual core design fundamentals. This addition could be a great first step in a slightly more `design` oriented bootstrap framework. v4 is already a heck of a lot more thought out that it's predecessor. I feel that this could add to it.

**Comment by patrickhlauke** [comment]
so which is it? do you propose a single `$text-casing` variable, and then having it as one big master switch to change...what?...all headings at the same time to either upper or lowercase?

or a whole series of different `$text-casing-xxxxxx` variables for all sorts of things (headings? labels? buttons? other)

**Comment by guylepage3** [comment]
Well for our particular situation we're using uppercase in our branding for labels and buttons and we use lowercase on our headings. other users, like a little company called Uber, use uppercase heavily throughout their "drivers" brand. http://driveubernyc.com/#driving-with-uber

I have designed a brand in the past utilizing uppercase for almost everything. and similarly done this with lowercase.

My vote is to have `$text-casing` be applied to headings, labels, buttons, base-font, etc. and let the user turn it off and on.

Having said all that, I will leave that final decision up to you. i can do a pull request if you like.

**Comment by patrickhlauke** [comment]
(FWIW i suggest leaving the condescending sarcasm like "a little company called Uber" etc out of this discussion)

feel free to submit a pull request...as it seems we're just talking across purposes here about how you'd envisage this (single variable or a whole slew of variables)

**Comment by AustinPaquette** [comment]
> My vote is to have $text-casing be applied to headings, labels, buttons, base-font, etc. and let the user turn it off and on.

Okay, that's fair, let's remember this.

> for our particular situation we're using uppercase in our branding for labels and buttons and we use lowercase on our headings.

Let's assume `$text-casing = lowercase !default`

So now you'd have to go through and explicitly change the variable... but conditionally. Or overwrite it and not use it in half of the cases, specifically labels and buttons.

> use uppercase heavily throughout their "drivers" brand. http://driveubernyc.com/#driving-with-uber

I don't see how such a variable would have helped them here. 

> I have designed a brand in the past utilizing uppercase for almost everything. and similarly done this with lowercase.

What makes it too much of a hassle to define this in the body (god forbid), the specific elements, or dedicated classes for that matter?

**Comment by guylepage3** [comment]
@patrickhlauke, I'm in a great mood. :smile: Not being condescending at all. just who i am. will keep it in mind though. :smile: 

I'll get to a pull request tonight. This would definitely be helpful. Thx.

**Comment by mdo** [comment]
Thanks, but we won't be adding anything for this. I don't see this saving folks time and I don't want us adding variables and properties throughout to state a default that's usually not overridden. If you want to change the casing, you'll have to make it an additional style for now.

**Comment by guylepage3** [comment]
Ok. Will add this as a custom feature for our projects. (hat tip)

**Comment by 29** [comment]
I'm a little late to this discussion, but...

While I can see the merits of having this on the side, it does seem more like a per-project thing, and not very necessary to the overall goal of bootstrap.
