### ISSUE TITLE
File input inside inline form

### ISSUE THREAD

**Issue by PowerGamer1** [twbs/bootstrap#19082]
Currently, when trying to use `<input type="file>` inside inline form it gets ~~an extra border due to "form-control" class. If the "form-control" class is removed the input is rendered without a border (as it is supposed to be) but~~ misaligned (due to the fact that the style "form-control" is responsible for input alignment in the horizontal form):

Incorrectly misaligned:
```HTML
<form class="form-inline">
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
  </div>
  <div class="form-group">
    <label for="exampleInput">File</label>
    <input type="file" id="exampleInput">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
```
P.S. This is for Bootstrap v3.

**Comment by cvrebert** [comment]
Using `.form-control` on file inputs is invalid (see https://github.com/twbs/bootlint/wiki/E042#form-control-cannot-be-used-on-non-textual-inputs-such-as-those-whose-type-is-file-checkbox-radio-range-button ), but your point about misalignment of file inputs in inline forms is well-taken.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
