### ISSUE TITLE
Extra padding tags to use whenever needed.

### ISSUE THREAD

**Issue by Lutir** [twbs/bootstrap#19083]
I would like to propose the addition of extra tags, like-

'.space-medium','.space-small','.space-large' in the css

<p>Many times while developing a website,we require some additional padding to be given between different div's,sections,etc. Instead of adding padding to them we can make divs with the following class name in order to get required spacing.</p>

<h5>For eg:</h5>
.space-small{
 height:10px;
}
.space-medium{
height:20px;
}
.space-large{
height:40px;
}

**Comment by mdo** [comment]
Margin and padding utilities are coming in v4.

**Comment by cvrebert** [comment]
http://v4-alpha.getbootstrap.com/components/utilities/#spacing
