### ISSUE TITLE
_custom-forms.scss name change suggestion

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#19085]
we are creating our own custom styles for our project. one of the things our team has had a discussion about was the naming of the `_custom-forms.scss` file. this is a very confusing name for a bootstrap core .scss file. we understand that it is an extension to forms for customization.

I feel this should be a more specific name for this forms doc as the word `custom` would be nice to reserve for users who are building projects with bootstrap.

we are calling our "custom" files;

```
_custom-styles.scss
_custom-variables.scss
_custom-mixins.scss
```

You can see how `_custom-forms.scss` could get lost in the mix with our file names.

We could replace the `_custom` naming convention on our end with the project name but that would be bad practice for forking projects on our end.

Perhaps a name change for `_custom-forms.scss` to one of the following would work;

```
_more-forms.scss
_additional-forms.scss
_behavioral-forms.scss
```

**Comment by cvrebert** [comment]
"nonnative-forms" perhaps?

**Comment by guylepage3** [comment]
`_nonnative-forms.scss` works for me.. 

Some others could be;
`_auxiliary-forms.scss`
`_other-forms.scss`

**Comment by IamManchanda** [comment]
you are a living dictionary perhaps @guylepage3 ... lollzzz

**Comment by IamManchanda** [comment]
wont  be a bad idea if 
`_custom.scss` can be changed to `_overrides.scss` also

**Comment by guylepage3** [comment]
@cvrebert @mdo where are we with this issue? would be nice to have this defined for our projects as there seems to be a couple of processes on how to override scss in b4. I've had a couple conversations in the slack channel and seems as though the most popular method is to override on a component basis which means `_custom-forms.scss` could get very confusing.

Let's try and resolve this one.

Also, I am unable to do a `pull-request`. Is there a reason for that?

**Comment by cvrebert** [comment]
We're waiting for @mdo to review this issue and make a decision. He's a very busy man. :smile: 

> Also, I am unable to do a pull-request.

That shouldn't be the case.

> Is there a reason for that?

No.

**Comment by guylepage3** [comment]
He def is. Don't know how he does it. Must have cloned himself. ;)

>That shouldn't be the case.

Hmm.. I'll look into this more tonight. Thanks for the reply, good sir. (hat tip)

**Comment by mdo** [comment]
Debated this for awhile and going to leave it as-is for now. I couldn't come up with anything I liked better that got at the heart of what these components are about (which is *custom* forms built on *native* form elements).

**Comment by guylepage3** [comment]
>I couldn't come up with anything I liked better that got at the heart of what these components are about (which is custom forms built on native form elements).

I know they are custom forms but users will have their own customizations as well. The word `custom` should be reserved for the user as it's the most logical word for them, which I feel is more important.
