### ISSUE TITLE
Remove label tag wrap around radio and checkbox in forms

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#19095]
I am wanting to target `<label>` tags quickly. The current v4-dev applies an unnecessary `<label>` wrapper around `<input>`s on inline form radio and checkbox elements. 

Seen below:
```
<div class="form-group row">
    <label class="col-sm-2">Radios</label>
    <div class="col-sm-10">
      <div class="radio">
        <label>
          <input type="radio" name="gridRadios" id="gridRadios1" value="option1" checked="">
          Option one is this and that—be sure to include why it's great
        </label>
      </div>
      <div class="radio">
        <label>
          <input type="radio" name="gridRadios" id="gridRadios2" value="option2">
          Option two can be something else and selecting it will deselect option one
        </label>
      </div>
      <div class="radio disabled">
        <label>
          <input type="radio" name="gridRadios" id="gridRadios3" value="option3" disabled="">
          Option three is disabled
        </label>
      </div>
    </div>
  </div>
```

This is very problematic and odd. they should not be there as the dev will not be able to target `<label>`s.

I am requesting the removal of the excessive `<label>` wrapping around `<input>`s on inline form radio and checkbox elements.

**Comment by mdo** [comment]
> I am wanting to target `<label>` tags quickly.

What do you mean by target?

> The current v4-dev applies an unnecessary `<label>` wrapper around `<input>`s on inline form radio and checkbox elements. 

This is not unnecessary nor excessive. The surrounding `<label>` gives a large clickarea for toggling the input. The `<label>` is not made to be block-level to avoid accidental clicks from the white-space around the label and input. As such, the wrapping `<div class="radio">` is required for proper stacking.

**Comment by patrickhlauke** [comment]
also, radio buttons and checkboxes (and, well, all types of form control) need a `<label>` (or alternative form of naming, such as `aria-label` attribute) for accessibility. labels can either be separate, which then requires a `for`/`id` relationship, or they can be "implicit", where the `<label>` wraps around the relevant form control...as is the case in our documented example.

**Comment by mdo** [comment]
Going to close this out given my comment and @patrickhlauke's, but please feel free to holler if there's something specific around the targeting that you're having a problem with. A class might be coming that way soon anyway, so maybe that could help.

**Comment by guylepage3** [comment]
@mdo @patrickhlauke, actually if you look at your example, there are not just 1 but 2 sets of `<label>`'s for the radio and checkbox elements. So I disagree that the set that wraps the radio and checkbox elements is necessary.

**Comment by patrickhlauke** [comment]
there are two sets of labels, but the first one should actually be a `<legend>` - and will be once i resolve https://github.com/twbs/bootstrap/pull/17266

there is a difference between an overarching legend and a unique label for each radio/checkbox. so no, the wrapping `<label>` is not redundant.

**Comment by guylepage3** [comment]
Ah. Gotcha. @patrickhlauke does that mean that we are going to go be adjusting the form layout to include `<fieldset>`? and follow the form syntax recommended by W3schools?

```
<form>
  <fieldset>
    <legend>Personalia:</legend>
    Name: <input type="text" size="30"><br>
    Email: <input type="text" size="30"><br>
    Date of birth: <input type="text" size="10">
  </fieldset>
</form>
```
http://www.w3schools.com/tags/tag_legend.asp

**Comment by patrickhlauke** [comment]
> follow the form syntax recommended by W3schools?

no, because the code quality of W3schools is generally poor, as in this case.

**Comment by patrickhlauke** [comment]
Maybe have a look at far more respectable sources of markup to make your point? e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

**Comment by guylepage3** [comment]
Thanks @patrickhlauke. I did notice though that they did not wrap the input with a label in their example.

```
<form action="test.php" method="post">
  <fieldset>
    <legend>Title</legend>
    <input type="radio" id="radio"> <label for="radio">Click me</label>
  </fieldset>
</form>
```

Also, we have no way to target just the `<label>` according to the documentation. See image..
<img width="704" alt="screenshot 2016-02-08 11 46 18" src="https://cloud.githubusercontent.com/assets/1711854/12892338/a5dd0e50-ce59-11e5-8f33-d310b1d0b0f9.png">

**Comment by patrickhlauke** [comment]
>  I did notice in your resource that they did not wrap the `<input>` tag with a label in their example

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

long story short: it's a valid way of doing labelling, so no we're not going to remove it.

however, if your request is not "remove the `<label>` wrapper" but rather "also allow for a checkbox/radio button to have a separate `<label for="...">` and maintain the same styling", then yes, that's something that we could look into /cc @mdo

**Comment by guylepage3** [comment]
thanks @patrickhlauke, that could definitely work to add the `<label for="...">` 

<img width="717" alt="screenshot 2016-02-08 15 37 56" src="https://cloud.githubusercontent.com/assets/1711854/12898375/5ca26336-ce7a-11e5-8562-0b6ddc1d4461.png">

method as well. 

a bit redundant but understandable if others have been doing it the other way for some time.
