### ISSUE TITLE
Rename .label class to .tag

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#19094]
there is a naming conflict between bootstrap's class name `.label` and the html tag `<label>`. it is generally good practice to not name your classes after html tags for easy and clear recognition.

i'd like to propose that we change the bootstrap `.label` to something like `.tag`.

**Comment by cvrebert** [comment]
+1

**Comment by shea256** [comment]
+1

**Comment by eliottrobson** [comment]
+1

**Comment by mdo** [comment]
Merged #19157.
