### ISSUE TITLE
Bootstrap thesis to save time and reduce the number of issues created

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#19090]
@mdo, I thought about issue https://github.com/twbs/bootstrap/issues/19081 last night and realized that the creation of issues could be greatly reduced if there was a short 2-3 paragraph thesis written by yourself on how you envision bootstrap. an always evolving thesis. something you can iterate on.

i am fully aware of https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker documentation but there is no real 'thesis' for bootstrap contributors to follow.

We started a developer community and created a rough outline for the community to follow and it has reduced the amount of time required to maintain the community. 

This would be a nice thing to have so that bootstrappers such as myself and others do not waste your time.

**Comment by mdo** [comment]
Closing as stale.
