### ISSUE TITLE
Difficulty to read table by column with NVDA when caption have class .sr-only

### ISSUE THREAD

**Issue by patriciamarchand** [twbs/bootstrap#19092]
Hello, 
I have an issue with NVDA, table and caption with class .sr-only. In the first table i'm not able to navigate with screen reader between cells column.

2. Open NVDA with Chrome or Firefox.
3. Go to [http://jsbin.com/ralipipuhe/edit?html,css,output](http://jsbin.com/ralipipuhe/edit?html,css,output). On that page, there are two basic examples of  table with header. The first one have a table caption only for screen reader so i add the class .sr-only. The second table have a caption visible.
3. Navigate with screen reader between cells column, hold down Ctrl + Alt and use the arrow keys to move from header cell to cell.
4.  In the first table i'm not able to navigate with screen reader between cells column, in the second table i dont have the problem.

Thanks

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by csilva2810** [comment]
@patriciamarchand 
How are you?
Did you try to use the "aria-label" attribute?
I think this is not a problem with "sr-only" class.
I have used your example adding the "aria-label" and it worked normally.

**Comment by patrickhlauke** [comment]
this appears to be a bug/inconsistency in NVDA - it somehow thinks the hidden caption is some form of second row (announces that the table has 5 rows, when in fact it has only 4, and when using reading keys it reads the caption after the row of headers) that it then can't navigate past. there seem to be some open bugs in https://github.com/nvaccess/nvda/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+table+caption at least for the wrong row count, at least

the same test case with JAWS 17 works absolutely fine, which again leads me to the conclusion it's NVDA messing up here. maybe worth posting a bug report on https://github.com/nvaccess/nvda/issues ?

**Comment by patriciamarchand** [comment]
I tried to put position:static instead of position:absolute on .sr-only and it seems to resolve the issue. What do you think? [http://jsbin.com/ducoqosoki/edit?html,css](http://jsbin.com/ducoqosoki/edit?html,css)

.sr-only{
  position:static;
  height:0;
}

**Comment by patrickhlauke** [comment]
it works in this very specific case as a workaround, but can cause other problems - see for instance the effect this change would have on the skip link at the start of getbootstrap.com

> ![capture2](https://cloud.githubusercontent.com/assets/895831/12858852/6a020b6c-cc4a-11e5-898b-ab2ec3436ea2.PNG)

**Comment by patrickhlauke** [comment]
fundamentally, it's something that NVDA need to fix at their end. changing to `position:static` is a potential workaround, but it depends on the exact situation so can't be used as a generic fix, i'd say :(

**Comment by patriciamarchand** [comment]
I understand thanks for the quick replies :)

**Comment by vimalans** [comment]
In the other thread posted by patrickhlauke, someone mentioned that FF exposes the additional row and hence NVDA announces incorrect row count. Anyone aware of bug reported to Mozilla or NVDA?
