### ISSUE TITLE
.card-outline-* classes no longer work

### ISSUE THREAD

**Issue by Starsam80** [twbs/bootstrap#19097]
[JSBin example](http://jsbin.com/cupegocuce/edit?html,css,output)
I'm pretty sure that the reason why it broke is with the recent change to cards

**Comment by twbs-lmvtfy** [comment]
Hi @Starsam80!

You appear to have posted a live example (http://jsbin.com/cupegocuce/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Starsam80** [comment]
whoops, even though this shouldn't be related to javascript. [revised example](http://jsbin.com/cupegocuce/edit?html,css,output)

**Comment by Starsam80** [comment]
I was able to fix it by adding `border: 1px solid`. [new example, with and without fix](http://jsbin.com/sesefosexe/edit?html,css,output)

**Comment by cvrebert** [comment]
Confirmed. We're setting a `border-color` but not any `border-width`.

**Comment by cvrebert** [comment]
Bisection showed that 955e0405ea04e8bce3fa8395cd5e1c4030c4947a was what broke this.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by Starsam80** [comment]
Any update on this? I reverted 955e0405ea04e8bce3fa8395cd5e1c4030c4947a for now on my branch, but it gets rid of header navs. I could do a pull request, but I have no idea if header navs are here to stay.

**Comment by cvrebert** [comment]
@Starsam80 If there was an update, you'd see it here.

@mdo Ping.

**Comment by indymx** [comment]
in mixins/_cards.scss I added

// Card variants

@mixin card-variant($background, $border) {
  background-color: $background;
  border-color: $border;
  border-style: $card-border-style;
  border-width: $card-border-width;
}

@mixin card-outline-variant($color) {
  background-color: transparent;
  border-color: $color;
  border-style: $card-border-style;
  border-width: $card-border-width;
}


added 

$card-border-style:         solid !default;

to _variables.scss also.

and it works as expected.

**Comment by cvrebert** [comment]
@mdo Ping.

**Comment by mdo** [comment]
Change coming in #19861.
