### ISSUE TITLE
Make print-media optional

### ISSUE THREAD

**Issue by JD-Robbs** [twbs/bootstrap#19101]
For v4, it would be nice to be able to set `$print-media = false` or something similar.

That would enable us to simply `@import` bootstrap.scss, rather than having to import everything (by copying the contents of bootstrap.scss) and remove the print-styles partial.

**Comment by mdo** [comment]
Yeah, I could see us doing this one actually since I don't think most folks thinking about print styles for their sites these days anyway.

**Comment by JD-Robbs** [comment]
Fantastic, cheers - would play nicely with all the other optional functionality and variable-goodness.

**Comment by cvrebert** [comment]
Implemented in #19106.

**Comment by JD-Robbs** [comment]
Thanks! :+1:
