### ISSUE TITLE
problem with show navbar-toggle in tablet

### ISSUE THREAD

**Issue by MohammadeMBi** [twbs/bootstrap#19100]
hi,

when i open website in tablet , navbar-toggle not working and normal menu has show , because in tablet , menu display Unordered .

i want show navbar-toggle in tablet such as mobile phone

screenshots :
http://www.uplooder.net/img/image/17/8228b8a137134f21b6b3b4f46f038e37/ss1.png
http://www.uplooder.net/img/image/58/e1d57c327e029704a9ea0531abd43687/ss2.png

can help me to resolved the problem ?

**Comment by cvrebert** [comment]
Please use StackOverflow or similar for personal support questions like this.
See https://github.com/twbs/bootstrap/blob/master/README.md#community for links to such forums.
Thanks.
