### ISSUE TITLE
Warn if $container-max-widths implies a non-integer px column width

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#19113]

**Comment by saqibnaveed** [comment]
Hello. I am a junior develop, I want to contribute to this issue. Kindly guide me :)

**Comment by ysds** [comment]
The `%` have been fixed in #26689.

I don't know if other units of (`rem`, `em`, `ex` ...) should also be considered, but at now we can close this IMO.

**Comment by ysds** [comment]
> non-integer px 

oh, I was misunderstood, but this issue can not be reproduced now.
