### ISSUE TITLE
Grid column with overflowing content behaves differently when Flexbox is enabled

### ISSUE THREAD

**Issue by ilpasqui** [twbs/bootstrap#19123]
Different behavior of columns in flexbox/floats grid columns,
if the content of the column is larger than the column, we have two different behaviors:

No flex:  the column overflows
[http://jsbin.com/jalubuxome/1/edit](http://jsbin.com/jalubuxome/1/edit)

Flexbox: the column enlarge itself (breaking the row)
[http://jsbin.com/majutogofe/edit](http://jsbin.com/majutogofe/edit)

is it meant to be like this ?

**Comment by cvrebert** [comment]
> if the content of the column is larger than the column

I would tempted to say that that in and of itself is a bug in the user's code.

**Comment by mdo** [comment]
I see no difference in Safari at the largest viewport. Regardless of that, if you're content is extending past the containers, you'll want to fix that as it's arguably a bug as @cvrebert mentioned.

<img width="1288" alt="screen shot 2016-02-08 at 10 20 03 pm" src="https://cloud.githubusercontent.com/assets/98681/12909069/1fe8e630-ceb2-11e5-8561-869777044a8b.png">
<img width="1292" alt="screen shot 2016-02-08 at 10 19 58 pm" src="https://cloud.githubusercontent.com/assets/98681/12909070/1feae372-ceb2-11e5-8abf-7d950761211a.png">

**Comment by ilpasqui** [comment]
It's clearly not a bug, it's just a difference in behavior between flex/floats not really documented 
Setting  a `min-width`  to the columns in flex changes the overflow behavior to the floats version (at least in Chrome 48 and FF 43 ),

[http://jsbin.com/nayihodowu/edit?html,css,js,output](http://jsbin.com/nayihodowu/edit?html,css,js,output)

**Comment by performatric** [comment]
Thanks @ilpasqui 

`[class^="col-"]{
    min-width:1px;
}`

works for me, with `$enable-flex: true;`

**Comment by at0g** [comment]
I'm seeing this too in FF and IE.
The columns work as expected for me provided:
- There is a min-width value, even `min-width: 0` (FF)
- There is a max-width equal to columns flex-basis (IE)

eg.
```
@mixin make-col-span($size, $columns: $grid-columns) {
	@if $enable-flex {
		flex: 0 0 percentage($size / $columns);
		max-width: percentage($size / $columns);
	} @else {
		width: percentage($size / $columns);
	}
}
```

**Comment by cvrebert** [comment]
@mdo So, should we close as NotABug, or...?

**Comment by vagyriag** [comment]
saw the comment in the fix 
```
// Add a `max-width` to ensure content within each column does not blow out
// the width of the column. Applies to IE10+ and Firefox. Chrome and Safari
// do not appear to require this.
max-width: percentage($size / $columns);
```

I'm using Chrome V49.0.2623.110 in Windows 10 and it **requires** the fix for me to work as expected.

**Comment by davewasmer** [comment]
@cvrebert #19770 might be related here, which doesn't seem like a user bug. `white-space: nowrap` causes flex columns to overflow their width, and code blocks with lines longer than the containing column width certainly seems like a valid use case.

**Comment by kvlsrg** [comment]
Here [example](http://codepen.io/kvlsrg/pen/pbPEym) of this bug (tag `pre` inside the column) & fix with `max-width` property. Seems, that it also need to add `max-width: 100%;` as default for all columns with breakpoints.

**Comment by mdo** [comment]
Revisited and still see no issue in the opening comment's links. Closing out for now.
