### ISSUE TITLE
Include Flexbox-enabled version of Bootstrap on Flexbox Grid docs page

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#19127]
i.e. `/layout/flexbox-grid/`
Viewing it with Flexbox disabled makes for a very confusing experience.

**Comment by mdo** [comment]
Yeah, been debating doing something there.

**Comment by cvrebert** [comment]
We just need to faff about with the build system a bit.

**Comment by mdo** [comment]
Did this in Alpha 3.
