### ISSUE TITLE
Shunt excess tabs that don't fit in available horizontal space into a dropdown menu

### ISSUE THREAD

**Issue by andrewtch** [twbs/bootstrap#19124]
Subj; achievable only by javascript plugin.

Example for 2.0: http://www.eyecon.ro/bootstrap-tabdrop/#

If this behavior is acceptable, I can make a PR.

**Comment by cvrebert** [comment]
X-Ref: #9048 (alternate suggestion for this situation)

**Comment by mdo** [comment]
We'll pass for now. My suggestion would be to revisit whatever design assumptions got you to that place and find a way to have fewer tabs. Or at the very least add a horizontal scroller of some kind if you in fact need all those.

**Comment by andrewtch** [comment]
This is not true for systems where tabs are user defined and vertical space is limited, though. Afar from that, horizontal scrollers suck )
