### ISSUE TITLE
.input-group with .form-control-sm & .btn-sm renders incorrectly vs. .input-group-sm

### ISSUE THREAD

**Issue by redayoub** [twbs/bootstrap#19133]
Hi,

The input and the button inside a an input group didn't have the same height when adding form-control-sm class for input and btn-sm for button:

``` html
<form class="form-inline">
    <div class="input-group">
        <input type="text" class="form-control form-control-sm" placeholder="Search">
        <span class="input-group-btn">
            <button class="btn btn-secondary btn-sm" type="button">
                Go!!
            </button>
        </span>
    </div>
</form>
```

This could be fixed by setting the line-height of the .btn-sm to 1.6.

**Comment by cvrebert** [comment]
If you are using Bootstrap v3, see https://github.com/twbs/bootlint/wiki/E009
What version of Bootstrap are you using?

**Comment by redayoub** [comment]
No, I'm using v4 alpha.

**Comment by cvrebert** [comment]
@redayoub What OS and browser are you using?

**Comment by mdo** [comment]
And are you using the latest `v4-dev`?

**Comment by redayoub** [comment]
@cvrebert I'm using Ubuntu and Chrome.
@mdo I've this on my bower file: "bootstrap": "v4.0.0-alpha.2"

**Comment by mdo** [comment]
If you could, please change it to the latest commit from the branch and try again :). I pushed some changes that aren't attached to a release yet.

**Comment by redayoub** [comment]
@mdo It's fixed, thanks.
