### ISSUE TITLE
Bootstrap tooltip issue:

### ISSUE THREAD

**Issue by umesh-naik** [twbs/bootstrap#19130]
Here is the code::
`setInterval(function() {
    $("#someId").html("<a class='toolbar-Details'>'+someTime+'</a>");
}, 1000)`

//data attribute is set on the same id that is given above.
`$('[data-refresh]').hover(function() {
    $(this).tooltip({'placement': 'bottom'}).attr('data-original-title',      myDateTime).tooltip('fixTitle').tooltip('show');
});`

There are few doubts here:
1. `aria-describedby` and `getUID` are appending in all the browsers but they are updating every second only in the Mozilla Firefox but not in Chrome or IE. Why is that?
2. Because of the above problem, tooltip is fluctuating every second which is not desired. The same code is perfectly working in other browsers.
3. Since both are updating every single second, I removed those two attributes. And what I wanted to know is, which gets called first? aria-describedby or getUID? which is updating what? From `tooltip.js` I have seen that this happens::
`$tip.attr('id', tipId)
 this.$element.attr('aria-describedby', tipId)`

but when we look into html, it is opposite. Please explain.

**Comment by cvrebert** [comment]
Please make your example into a JS Bin or JS Fiddle.

**Comment by umesh-naik** [comment]
https://jsfiddle.net/hm98oc0s/1/

Check the above link in Mozilla Firefox only.

**Comment by twbs-lmvtfy** [comment]
Hi @umesh-naik!

You appear to have posted a live example (https://fiddle.jshell.net/hm98oc0s/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 31, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0
* line 35, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@umesh-naik 
(1) Update your Bootstrap to v3.3.6
(2) `fixTitle` and `data-original-title` aren't part of the public API; can't help you with them. Instead, [destroy](http://getbootstrap.com/javascript/#tooltipdestroy) the old tooltip and create a new tooltip instance.

**Comment by umesh-naik** [comment]
https://jsfiddle.net/hm98oc0s/1/

this is the updated fiddle.

**Comment by twbs-lmvtfy** [comment]
Hi @umesh-naik!

You appear to have posted a live example (https://fiddle.jshell.net/hm98oc0s/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 31, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0
* line 35, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by umesh-naik** [comment]
I have found that when you use `<a>` tag in `html()` method, this happens. Instead, if we use `text()` method, there will be no issue. Check the fiddle example::

https://fiddle.jshell.net/hm98oc0s/4/

**Comment by cvrebert** [comment]
@umesh-naik Please remove the usage of moment.js from your example since it's not relevant to the main problem and you haven't included it properly anyway. Just use plain `Date` objects instead.

**Comment by cvrebert** [comment]
@umesh-naik Also, don't use the edge version of jQuery; use jQuery v2. And please check the JS console and ensure there are no errors before posting the next revision of your example.

**Comment by umesh-naik** [comment]
Check this example::

https://jsfiddle.net/hm98oc0s/7/

I have removed moment.js. Check in mozilla.

**Comment by cvrebert** [comment]
@umesh-naik Please fix the issues I noted in https://github.com/twbs/bootstrap/issues/19130#issuecomment-181753098

**Comment by umesh-naik** [comment]
Okay, I have fixed those two issues. Now check this fiddle.

https://jsfiddle.net/hm98oc0s/10/

**Comment by cvrebert** [comment]
As mentioned previously, you need to [destroy](http://getbootstrap.com/javascript/#tooltipdestroy) the old tooltip.

**Comment by umesh-naik** [comment]
Okay that worked. Thanks. But why is this only with Mozilla Firefox?

**Comment by cvrebert** [comment]
> Okay that worked. Thanks.

Closing this then.

> But why is this only with Mozilla Firefox?

\*shrugs*
