### ISSUE TITLE
2 modals work but not more

### ISSUE THREAD

**Issue by tsquinn** [twbs/bootstrap#19131]
I know this is a rehash of issue #18403 but I didn't see a solution. I've been able to get as many as 4 working but not more and then only when in a specific order. Each of them will work when I reduce their total number to one or two. I've even tried c/p a working modal and changing only the linked button and it still doesn't work if more than 2.

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by tsquinn** [comment]
I'm not sure how to post it in JS Fiddle. How about if I send you a link to
the website?

On Mon, Feb 8, 2016 at 4:47 PM, Chris Rebert <notifications@github.com>
wrote:

> Please post a JS Bin or JS Fiddle that demonstrates the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/19131#issuecomment-181566247>.
>



-- 

Tim Quinn
Owner/CEO
Total Realty Solutions, LLC
614-407-TRS7 (8877)
YourTRS@gmail.com
www.YourTotalRealtySolution.com <http://www.yourtotalrealtysolution.com/>

**Comment by tsquinn** [comment]
Here's the temporary website: http://www.yourtotalrealtysolution.com/agents/bootstrap/Bootstrap_layout/template.html
The first two buttons work.

**Comment by patrickhlauke** [comment]
the first two work because the `<div>` elements they refer to actually exist in markup

```
<div id="propertyModal" ...> ... </div>
<div id="communityModal" ...> ... </div>
```

the other ones refer to `<div>`s that aren't actually there in your markup...

**Comment by tsquinn** [comment]
All the referenced <div>s are there. I c/p the entire working code to make the new modals then change the reference tags to match the buttons.

**Comment by tsquinn** [comment]
Why is this case closed? It's not closed. All the <div>s are there in the
markup. I've checked it a hundred times. I've c/p the working code and
changed only the reference name to match the button name and it still won't
open more than 2.

The code is there.

On Mon, Feb 8, 2016 at 5:44 PM, Patrick H. Lauke <notifications@github.com>
wrote:

> the first two work because the <div> elements they refer to actually
> exist in markup
>
> <div id="propertyModal" ...> ... </div>
> <div id="communityModal" ...> ... </div>
>
> the other ones refer to <div>s that aren't actually there in your
> markup...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/19131#issuecomment-181601283>.
>



-- 

Tim Quinn
Owner/CEO
Total Realty Solutions, LLC
614-407-TRS7 (8877)
YourTRS@gmail.com
www.YourTotalRealtySolution.com <http://www.yourtotalrealtysolution.com/>

**Comment by tsquinn** [comment]
I found the problem. It was not that the referenced tags were missing as
you suggested. There was one missing div tag at the bottom.

Thanks for your help.

On Mon, Feb 8, 2016 at 5:59 PM, Tim Quinn <yourtrs@gmail.com> wrote:

> Why is this case closed? It's not closed. All the <div>s are there in the
> markup. I've checked it a hundred times. I've c/p the working code and
> changed only the reference name to match the button name and it still won't
> open more than 2.
>
> The code is there.
>
> On Mon, Feb 8, 2016 at 5:44 PM, Patrick H. Lauke <notifications@github.com
> > wrote:
>
>> the first two work because the <div> elements they refer to actually
>> exist in markup
>>
>> <div id="propertyModal" ...> ... </div>
>> <div id="communityModal" ...> ... </div>
>>
>> the other ones refer to <div>s that aren't actually there in your
>> markup...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/twbs/bootstrap/issues/19131#issuecomment-181601283>.
>>
>
>
>
> --
>
> Tim Quinn
> Owner/CEO
> Total Realty Solutions, LLC
> 614-407-TRS7 (8877)
> YourTRS@gmail.com
> www.YourTotalRealtySolution.com <http://www.yourtotalrealtysolution.com/>
>



-- 

Tim Quinn
Owner/CEO
Total Realty Solutions, LLC
614-407-TRS7 (8877)
YourTRS@gmail.com
www.YourTotalRealtySolution.com <http://www.yourtotalrealtysolution.com/>

**Comment by cvrebert** [comment]
> There was one missing div tag at the bottom.

You should really check for that sort of thing yourself (e.g. via http://validator.w3.org/nu/) prior to filing an issue.

**Comment by tsquinn** [comment]
Right you are. Thanks for your help.

On Mon, Feb 8, 2016 at 6:32 PM, Chris Rebert <notifications@github.com>
wrote:

> There was one missing div tag at the bottom.
>
> You should really check for that sort of thing yourself (e.g. via
> http://validator.w3.org/nu/) prior to filing an issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/19131#issuecomment-181621075>.
>



-- 

Tim Quinn
Owner/CEO
Total Realty Solutions, LLC
614-407-TRS7 (8877)
YourTRS@gmail.com
www.YourTotalRealtySolution.com <http://www.yourtotalrealtysolution.com/>
