### ISSUE TITLE
make-col mixin is missing a $gutter parameter?

### ISSUE THREAD

**Issue by julien-gargot** [twbs/bootstrap#19147]
#19099

> #17512, #17514: Overhauls the grid mixins to merge make-col and make-col-span into a single make-col mixin, thereby ensuring mixins and predefined classes utilize the same float/flex behaviors.

Problem is, now, you have to override row-padding for working with contextual gutter widths.
If you can use `make-container($gutter)` and `make-row($gutter)`, it could makes sense to have a `$gutter` parameter in `make-col($size, $columns)` too. What do you think?

**Comment by cvrebert** [comment]
Fixed by #19257. Thanks!
