### ISSUE TITLE
Modal don't scroll when closing top modal

### ISSUE THREAD

**Issue by malcomxcia** [twbs/bootstrap#19149]
Hey there ! ! !

I have 2 Modals

Modal 1 including an Contact form
Modal 2 opens when Contact Form has an Validate Error

after closing the Modal 2 the contact form is no more scrolling

Does anyone have a solution ?

**Comment by patrickhlauke** [comment]
i'm afraid multiple/stacked modals are not supported in bootstrap http://getbootstrap.com/javascript/#modals

i'd suggest checking on StackOverflow or similar for a potential workaround/additional code. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
