### ISSUE TITLE
make-grid-columns mixin doesn't use its $gutter parameter

### ISSUE THREAD

**Issue by julien-gargot** [twbs/bootstrap#19148]
#19099

It seems that in the `make-grid-columns($columns: $grid-columns, $gutter: $grid-gutter-width, $breakpoints: $grid-breakpoints)` mixin in `scss/mixins/_grid-framework.scss`, the `$gutter` parameter is not used. The variable `$grid-gutter-width` is used to set the padding (lines 18, 19). Is this should not be `$gutter`?

**Comment by mdo** [comment]
Done! 4043510

**Comment by mdo** [comment]
<3
