### ISSUE TITLE
Labels of custom checkboxes and radios lack pointer cursor

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#19142]
Custom checkbox and radio labels lost the `pointer` cursor, is it a bug or by design?

**Comment by cvrebert** [comment]
The `cursor: pointer` was removed in 11df78ec742cae7340e80468f3d7492e26724185 (of #18771) without explanation.
CC: @mdo

**Comment by mdo** [comment]
I don't recall if I did this on purpose. Thinking about it, I may have—I don't think labels have a non-`default` cursor by default. But I think I like having it.

**Comment by cvrebert** [comment]
Indeed, the UA stylesheets for both Chrome and Firefox set `label { cursor: default; }`

**Comment by mdo** [comment]
Restored in 63a269d since our `.radio` and `.checkbox` has the custom cursor.
