### ISSUE TITLE
suggestion regarding <a> tags with .disabled state

### ISSUE THREAD

**Issue by patchee500** [twbs/bootstrap#19154]
According to the docs I am supposed to add class .disabled to an `<a>` element if I want it to look and act like an actual `<button>` with `disabled` attribute. This is working almost perfect.
The only problem I have, is that because of the `pointer-events: none` rule, the cursor will not have the same look it has on disabled buttons (`cursor: not-allowed;`). IMO they should look the same.

This topic was already mentioned here: #16088

So what about adding a little hack like the following: https://jsfiddle.net/ekswzwgz/6/

~~Also, while we are at it, disabled `<button>` and `<a>` tags should not change their `background-color` and `border-color` while they are in `:active` state. They can be forced into active state in some browsers by trying to drag the element.~~ (moved to #19189)

**Comment by cvrebert** [comment]
@patchee500 Could you please open a separate issue regarding the `:active` problem?

**Comment by cvrebert** [comment]
> So what about adding a little hack like the following: https://jsfiddle.net/ekswzwgz/6/

Not sure whether it's worth that much CSS just for a `cursor`.

**Comment by patchee500** [comment]
> Could you please open a separate issue regarding the :active problem?

yessir: #19189

> Not sure whether it's worth that much CSS just for a cursor.

Fully understand your point there, as it is a little hacky but I still think this should be fixed.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
