### ISSUE TITLE
.form-control-label overrides horizontal padding set by .col-*

### ISSUE THREAD

**Issue by Thomas--S** [twbs/bootstrap#19150]
Hello! I have noticed a little problem with Bootstrap 4 alpha-2: When I use the code from http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid, the labels are about 3 pixels too left. This is because of the .form-control-label, that overrides the horizontal padding (originally set by .col-*)
I have made a jsfiddle to show the problem: https://jsfiddle.net/Thomas_S/cvs4tvyp/

**Comment by Thomas--S** [comment]
I think #19141 will fix this problem.

**Comment by mdo** [comment]
Sounds like a dupe of #17498.
