### ISSUE TITLE
Card headers and footers maintain border radius inside a card group

### ISSUE THREAD

**Issue by wesm87** [twbs/bootstrap#19159]
Example:

<img width="308" alt="screenshot 2016-02-11 15 17 25" src="https://cloud.githubusercontent.com/assets/1192513/12989252/a0e552ce-d0d2-11e5-9a2c-96e97b8c7f14.png">

**Comment by wesm87** [comment]
This seems to fix the issues:

```
.card-group {
	.card {
		.card-header,
		.card-footer {
			border-radius: 0;
		}

		&:first-child {
			.card-header {
				border-top-left-radius: $border-radius;
			}

			.card-footer {
				border-bottom-left-radius: $border-radius;
			}
		}

		&:last-child {
			.card-header {
				border-top-right-radius: $border-radius;
			}

			.card-footer {
				border-bottom-right-radius: $border-radius;
			}
		}
	}
}
```

**Comment by cvrebert** [comment]
@wesm87 What exact version of Bootstrap are you using?

**Comment by mdo** [comment]
Currently not an issue in the latest `v4-dev`.

**Comment by onokazu** [comment]
I still do see the issue with card-group in v4 beta. Try zooming into the footer section of the 2nd card-group example on the documentation site. https://getbootstrap.com/docs/4.0/components/card/#card-groups
