### ISSUE TITLE
Offset does not work anymore

### ISSUE THREAD

**Issue by iBasit** [twbs/bootstrap#19161]
I'm assuming following commit broke the offset https://github.com/twbs/bootstrap/commit/5a9538d4c789ab25be71db1e6f190b8ad80e6858#diff-c5c8721c93f4a635309debe19c7196f4

Because it is not compiling anymore.

offset-sm-2 it is changed to this... :/

Is it part of new change or is it a mistake?

**Comment by iBasit** [comment]
offset-sm-2 it is changed to this... :/

**Comment by cvrebert** [comment]
@iBasit Are you just referring to the change in the names of the classes "breaking" code that used the old names, or are you claiming that the newly-renamed classes don't function correctly?

**Comment by ciro207** [comment]
I've noticed this change this morning.
Just use the new classes (`.offset-**-#`) and everything return to work

**Comment by cvrebert** [comment]
Refer to #19099 and https://github.com/twbs/bootstrap/pull/19099/files#diff-c2ec3a9f63de0b91b7bb532c0befc6cdR30 for info on the intentional naming scheme change.
