### ISSUE TITLE
How to use the dropdown sub menu? 

### ISSUE THREAD

**Issue by KOSNOWMAN** [twbs/bootstrap#19163]
In v3 bootstrap It was easy to make dropdown submenu, 
but in v4 I don't know how to do it.

for example, I want to make dropdown sub menu.
when I click the Dropdown2 menu, I want to see popup the dorpdown sub menu like one, two, three 
.. Is it possible?

+div class="dropdown open">
 +button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown
  +/button>
  +div class="dropdown-menu" aria-labelledby="dropdownMenu1">
    +a class="dropdown-item" href="#">Action+/a>
    +a class="dropdown-item" href="#">Another action+/a>
    +a class="dropdown-item" href="#">Something else here+/a>
    +a class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown2
   +/a>
  +/div>

  +div class="dropdown-menu" aria-labelledby="dropdownMenu2">
	+a class="dropdown-item" href="#">one+/a>
	+a class="dropdown-item" href="#">two+/a>
	+a class="dropdown-item" href="#">three+/a>
  +/div>

</div>

**Comment by patrickhlauke** [comment]
dropdowns with submenus are not supported in bootstrap. please ask these sorts of "how to" questions on stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by KOSNOWMAN** [comment]
Thank you for your reply.
