### ISSUE TITLE
I do not get an invitation for the slack community 

### ISSUE THREAD

**Issue by cristian-sima** [twbs/bootstrap#19164]
Hi I tried for many times, but without any response.

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Just tried myself and got an email immediately. Have you checked your spam folder?

**Comment by cristian-sima** [comment]
Yes. Nothing :(

**Comment by cristian-sima** [comment]
I got it now. Thanks guys
