### ISSUE TITLE
disabled <button> and <a> tags styling should not be affected by :active state

### ISSUE THREAD

**Issue by patchee500** [twbs/bootstrap#19189]
Generally it is quite hard to force the `:active` state on a `<button>` that has the `disabled` attribute or an `<a>` with class `disabled`. If you however manage to do so (e.g. in dev tools) the buttons appearance will change. It will look like the button is being clicked.
You can also achieve this behavior in Firefox by trying to drag a `<button>` with `disabled` attribute.
Here's a fiddle: https://jsfiddle.net/ekswzwgz/7/

**Comment by mdo** [comment]
Merged #21439 to address this.
