### ISSUE TITLE
v4: Dropdown arrow and popover arrow not show

### ISSUE THREAD

**Issue by HadesD** [twbs/bootstrap#19181]
![issue](https://cloud.githubusercontent.com/assets/11664992/13019751/875f772e-d214-11e5-8be6-f13c519ce345.png)
```html
<li class="nav-item">
					<a class="nav-link" href="http://sinigami.dev/tools" data-toggle="tooltip" data-placement="left" title="" data-original-title="Trang công cụ"><i class="material-icons"></i></a>
				</li>
```

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem.
Also, please state which browser you're using.

**Comment by HadesD** [comment]
I 've fixed it, it not enough tether document so it can't show all of the element.
how can i remove the tether but the site still working perfectly?

**Comment by cvrebert** [comment]
> I've fixed it, it not enough tether document so it can't show all of the element.

Sorry, but I don't understand what you mean here.
Was the problem in your code, or in Tether.js, or in Bootstrap?

> how can i remove the tether but the site still working perfectly?

That shouldn't be possible.

**Comment by ffejwright** [comment]
I would love to know the fix for this
