### ISSUE TITLE
stability in grid system in future v4 

### ISSUE THREAD

**Issue by nyn05** [twbs/bootstrap#19193]
I want to use Bootstrap v4 instead of Bootstrap v3 because of improved grid system in v4.
But I need to be sure that grid system in this version will not change class names such col-sm-* or col-xs-* in future versions.
Is it possible that class names used in this grid system such as xl , lg , md , sm , xs change in future or some classes add into this grid system in current version(alpha-version)?
**Is this grid system stable ?**

@mdo

**Comment by saviomd** [comment]
No.
It will change in alpha3: https://github.com/twbs/bootstrap/pull/19099

**Comment by cvrebert** [comment]
Bootstrap v4 is currently in alpha, hence we make no stability guarantees at this time.

**Comment by nyn05** [comment]
I really appreciate your help
