### ISSUE TITLE
Outlined buttons have the same appearance on :active and :focus states

### ISSUE THREAD

**Issue by TiGR** [twbs/bootstrap#19199]
Slightly modified example from the docs:

```html
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary-outline">
    <input type="checkbox" checked="" autocomplete="off"> Checkbox 1
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off"> Checkbox 2
  </label>
</div>
```

Once you clicked the button you can't say what is its state actually until you move your mouse pointer away (or on mobile devices - tap outside of the buttons area). So, if user have tapped some checkbox he can't really say what state is it in.

Compare this behavior with not outilined buttons.

**Comment by patrickhlauke** [comment]
I'm assuming you mean in v4 ?

**Comment by TiGR** [comment]
Yep, there are no outlined buttons in v3

**Comment by patrickhlauke** [comment]
btw note that in your example code `btn-primary-outline` should be `btn-outline-primary`

**Comment by TiGR** [comment]
My code was based on docs, it seems that outline buttons docs need to be updated.

**Comment by patrickhlauke** [comment]
actually, ignore me...i seem to have gotten myself mighty confused while hacking away with devtools. you and the documentation are right...

**Comment by patrickhlauke** [comment]
need to stop looking at the out-of-sync v4-alpha site, as it seems the naming was swapped at some point. i'll make a note to check/update the docs if needed.

**Comment by patrickhlauke** [comment]
just to confirm that the docs in the latest version here are up-to-date. it's just http://v4-alpha.getbootstrap.com that is quite a few commits behind.

**Comment by TiGR** [comment]
@patrickhlauke I've checked the actual docs. See pull request.
