### ISSUE TITLE
Download link - 404

### ISSUE THREAD

**Issue by vitherain** [twbs/bootstrap#19191]
http://liferay.github.io/alloy-bootstrap/ - Download button does not work - 404 error.

**Comment by hebbet** [comment]
you are in the wrong repo. 
please contact https://github.com/liferay/alloy-bootstrap

**Comment by vitherain** [comment]
Go here : http://liferay.github.io/alloy-bootstrap/index.html

And click Download -> 404.

**Comment by patrickhlauke** [comment]
@vitherain ... to be clear: that's nothing to do with bootstrap. go and report the issue here https://github.com/liferay/alloy-bootstrap
