### ISSUE TITLE
submitting form in modal

### ISSUE THREAD

**Issue by sonkengmaldini15** [twbs/bootstrap#19203]
Hi wonder how i can redirect a page with errors displayed in 
Modal when a form is submitting
Thanks

**Comment by patrickhlauke** [comment]
please direct these sorts of personal requests for help (rather than issues relating to bootstrap itself) to StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
