### ISSUE TITLE
Dropdown in Breadcrumb

### ISSUE THREAD

**Issue by sahilbabbar** [twbs/bootstrap#19200]
We can have an advanced breadcrumb, which will have a dropdown for navigating to a specific position in case of nested pages.

For example:
`Home / Dashboard v / Profile`

Here, 'Dashboard' leads to different pages and profile is one of them. So, if the user wants to directly navigate to some other page from Profile page, then, it can do so by clicking on the dropdown on Dashboard link and selecting the desired page; instead of first going back to Dashboard and then selecting the desired page.

**Comment by cvrebert** [comment]
This kinda works in v4; the only major problem is that the dropdown's height causes the text of the other non-dropdown crumbs to become vertically misaligned.

**Comment by mdo** [comment]
Won't be adding to the default v4, but sounds ripe for custom CSS or open source add-on.

**Comment by sahilbabbar** [comment]
[Just a thought] Won't it be nice, if developers don't have to reach out to add-ons if most modern things are included by default in the framework. Because, in enterprise production systems it takes a lot of process and debate before going out of the framework and opt for any add-on.

**Comment by cvrebert** [comment]
If we added every quasi-reasonable feature that was ever requested, the framework would become very complex, much harder to maintain, and would justifiably be considered bloated by [potential] users. Therefore, each potential addition must be carefully considered.

**Comment by cvrebert** [comment]
In fairness, and to aid any future re-evaluation of this feature request, there have been 2 prior issues related to such a feature: #559, #6115
