### ISSUE TITLE
.nav-inline .nav-item has extra space when there are spaces in the HTML source

### ISSUE THREAD

**Issue by atu-record** [twbs/bootstrap#19223]
Just came across this general issue when working with dispay: inline-block; and nav elements
http://stackoverflow.com/questions/9664321/strange-margin-on-displayinline-block-elements

so i'd suggest to add something like this to _nav.scss

```sass
    .nav-inline {
        font-size: 0;
    }
```

**Comment by cvrebert** [comment]
We've generally opted not to try to "fix" this aspect of inline-block in other places.

**Comment by mdo** [comment]
Yup, not changing anything here for basic inline nav.
