### ISSUE TITLE
Add width:100% utility class

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19221]
Is there a helper to set a width: 100%? I'm currently making an autocomplete input and using .dropdown-menu as base style, however, I can't find a class to make dropdown full width.

~~Also some bs4 elements are set to display: none by default and I can't find helper to make element visible while there is helper to make element invisible. What are bs4 recommendations on how to do it?~~

**Comment by cvrebert** [comment]
+1. This would also be a potential fix for #19202.

> Also some bs4 elements are set to display: none by default

Please open a separate issue for that, and in the future please don't combine multiple unrelated issues into a single issue.

**Comment by cvrebert** [comment]
Fixed by #19234.
