### ISSUE TITLE
problem with bootstrap 4

### ISSUE THREAD

**Issue by GCNews** [twbs/bootstrap#19266]
i have a problem with the new bootstrap 4.0.0 alpha 2.. i downloaded the file, i opened it and i found interesting the browser page (for test) called "tab". It is more cool! i copied the code with notepad++ in my website,but it doesn't work like first! when i click a text (in the editor is &lt;a href="#home1"&gt;Home&lt;/a&gt;) , automatically i am teleported to a page called undefined.. so it doesn't exist.. if you don't understand , try to download and see the page tab on the bootstrap 4.0.0 alpha 2! please help me! i am doing a big update on my website! 
http://www.gcnews.altervista.org

**Comment by hebbet** [comment]
bootstrap v4 is currently in development and not yet suitable for usage in production.

**Comment by GCNews** [comment]
i am using it! it works in his original file! but in my website it doesn't work.. @hebbet

**Comment by patrickhlauke** [comment]
for personal support requests, please use stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
