### ISSUE TITLE
4.0.0-alpha.2 Alignment Class doesn't work

### ISSUE THREAD

**Issue by cheungtitus** [twbs/bootstrap#19265]
Per the documentation ...
[http://getbootstrap.com/css/#type-alignment](url)

If I use 4.0.0-alpha.2 CSS, it doesn't work.
[https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css](url)
https://jsfiddle.net/jj01hb7d/2/

However, when I swap in to use the current 3.3.6 CSS it works!
[https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css](url)
https://jsfiddle.net/o9699a3x/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cheungtitus!

You appear to have posted a live example (https://fiddle.jshell.net/o9699a3x/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 66, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 76, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @cheungtitus!

You appear to have posted a live example (https://fiddle.jshell.net/jj01hb7d/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 66, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 76, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by MrGeneric** [comment]
Check out the v4 docs, it looks like those classes have been changed.

http://v4-alpha.getbootstrap.com/components/utilities/#text-alignment

**Comment by patrickhlauke** [comment]
indeed. don't look at v3 documentation when using v4. additionally, the v4-alpha.getbootstrap site isn't always as up-to-date as the actual repo, so if you really want to be on the cutting edge, suggest building a local version of the documentation straight from the repository as well

**Comment by cheungtitus** [comment]
Thanks.
