### ISSUE TITLE
Add iOS Firefox to compatibility chart

### ISSUE THREAD

**Issue by Mortiferr** [twbs/bootstrap#19269]
According to [this](https://saucelabs.com/u/bootstrap) Bootstrap is _Firefox 44_ compatible on iOS. I believe this should be updated.

![screenshot from 2016-02-18 22 40 38](https://cloud.githubusercontent.com/assets/13282318/13166743/b6d1aaa6-d690-11e5-83c5-8a9d1806c853.png)

**Comment by cvrebert** [comment]
The apple logo in "44 (apple logo)" under the Firefox column in the Sauce Labs UI refers to Mac OS X, not iOS. That's what the "iPhone" column is for.

**Comment by patrickhlauke** [comment]
See https://github.com/twbs/bootstrap/pull/18614

**Comment by cvrebert** [comment]
Fixed by #19273.
