### ISSUE TITLE
Issue and Pull Request Templates 

### ISSUE THREAD

**Issue by herpdederp** [twbs/bootstrap#19260]
Would help with organization and getting all the relevant info. Requires adding files issue_template.md and pull_request_template.md

**Comment by mdo** [comment]
Yup, I've started some stuff on this last week since I knew it was coming down the pike :).

**Comment by cvrebert** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates
X-Ref: https://github.com/dear-github/dear-github/issues/125

**Comment by mdo** [comment]
We added the issue template, so closing.
