### ISSUE TITLE
Migration docs don't mention grid class renames from #19099

### ISSUE THREAD

**Issue by marvinmarnold** [twbs/bootstrap#19267]
In v4, adding col-X-offset-Y no longer has any effect. This appears to have broken in 7114e94d6668ad2b7b91b67d2b3d75a9258b1c2a. Not sure what the underlying cause is.

**Comment by cvrebert** [comment]
Some of the grid class names were changed in #19099, including those of column offsets.

**Comment by mdo** [comment]
Done in 1993fe5.
