### ISSUE TITLE
CDN v3.3.6 cross-origin request blocked 

### ISSUE THREAD

**Issue by BernardA** [twbs/bootstrap#19276]
Hello
Getting console error with my php script that used to work fine.
When I change back to v3.3.5, still using CDN, it works fine.

Pls. advise

Bernard
![screen shot 2016-02-19 at 11 57 22](https://cloud.githubusercontent.com/assets/9449665/13175097/f8b7fe74-d6ff-11e5-8079-d73c49079c38.png)

**Comment by cvrebert** [comment]
CDN-related issues should be filed at https://github.com/MaxCDN/bootstrap-cdn/issues
