### ISSUE TITLE
Part of Popover is outside boundaries of viewport

### ISSUE THREAD

**Issue by martinfojtik** [twbs/bootstrap#19279]
![bootstrap-1](https://cloud.githubusercontent.com/assets/7465851/13197312/120e7efc-d7eb-11e5-970e-eeb7fb559c7e.jpg)

it should look like this:

![bootstrap-2](https://cloud.githubusercontent.com/assets/7465851/13197313/1e1287a2-d7eb-11e5-86fc-628c428f1ae5.jpg)

**Comment by hebbet** [comment]
looks like your browser zoom is not at 100%.

**Comment by fojtCz** [comment]
yes, it's true, but problem occurs even if zoom is 100%

**Comment by kybishop** [comment]
This also occurs with tooltips. I'd wager the problem is related.

![screen shot 2016-02-21 at 2 25 18 pm](https://cloud.githubusercontent.com/assets/679465/13201780/a0921af0-d8a7-11e5-81c1-192d80f1e062.png)

**Comment by jipexu** [comment]
Hi
Sorry but i have also this tooltip problem? is it fixed or not or is there a way to avoid this ?
Thanks

**Comment by omnibrain** [comment]
Any chance this fix will be in alpha 6?

**Comment by Joyrex** [comment]
Still an issue in α6 - did this get introduced with the switch to Tether? v3 did not have this issue...

**Comment by jipexu** [comment]
yes same behavior even in alpha doc ...

**Comment by Joyrex** [comment]
Wasn't the auto value v3 had (that is dropped in v4) is what prevented tooltips and popovers from leaving the viewport?

**Comment by alecpl** [comment]
Can be fixed with `constraints: [{to: 'window', attachment: 'together', pin: true}]`, but the arrow is in wrong position. Please, do something with popover, this widget is really important but so broken in v4.

**Comment by mscu** [comment]
same issue here, please fix :)

**Comment by Johann-S** [comment]
Closed by #22444
