### ISSUE TITLE
Add variables for pager

### ISSUE THREAD

**Issue by trollwinner** [twbs/bootstrap#19274]
Hi again. One more question: why we can change some things as "pagination-hover-color" or "pagination-disabled-bg" by variables, and can't do this for pager. Are these variables unnecessary?

**Comment by wolfy1339** [comment]
I believe they removed the pager component

**Comment by patrickhlauke** [comment]
Correct - assuming we're talking about v4, the pager component has been removed https://github.com/twbs/bootstrap/pull/18782
