### ISSUE TITLE
Font size change when I use google translate

### ISSUE THREAD

**Issue by technotrixcy** [twbs/bootstrap#19278]
Hi. I'm using a Google Translate Tool in my website,. my problem is , when I use google translate the font size will be change when you click the languages. how can fix it?

Thank you,

**Comment by patrickhlauke** [comment]
Please use StackOverflow or similar for this sort of request. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
