### ISSUE TITLE
Popovers & tooltips should close when their containing modal closes

### ISSUE THREAD

**Issue by lenberman** [twbs/bootstrap#19270]
The 'Live Demo' section of http://v4-alpha.getbootstrap.com/components/modal/#live-demo contains a button which opens a Popover.  If the popover is opened and the containing modal is then closed, the popover remains open.  I don't think this is the correct behavior.

**Comment by cvrebert** [comment]
Also, clicking that `<a>` causes the page to scroll to the top, which also shouldn't happen.
