### ISSUE TITLE
Justified Button Groups and Single Button Dropdowns off the screen

### ISSUE THREAD

**Issue by hannahorange** [twbs/bootstrap#19285]
In small browser widths and mobile devices, the dropdown in the Justified Button Groups and Single Button Dropdowns is off the screen and we are also seeing this in our own style guide docs.
![image](https://cloud.githubusercontent.com/assets/12280024/13224590/e5675ec2-d94e-11e5-8dbc-18ea40a85471.png)

**Comment by cvrebert** [comment]
Per http://getbootstrap.com/components/#dropdowns-alignment , emphasis added:

> ### May require additional positioning
> Dropdowns are automatically positioned via CSS within the normal flow of the document. This means dropdowns may [...] appear out of bounds of the viewport. Address these issues on your own as they arise.

**Comment by cvrebert** [comment]
This might get fixed in Bootstrap 4 though; see #17167
