### ISSUE TITLE
Docs navbar stacks vertically & expands when resizing window

### ISSUE THREAD

**Issue by ahmetislam25** [twbs/bootstrap#19280]
There is a little bug in the menu on the homepage.

![menu](https://cloud.githubusercontent.com/assets/9280397/13201900/52cf1594-d88d-11e5-9629-8461c7f1d441.gif)

**Comment by hebbet** [comment]
please test if that also happens when you are running the docs locally (from branch v4-dev)

**Comment by mrmohtas** [comment]
I can't see the bug locally or on production. There is however a wrapping issue for the `md` viewport width.
<img width="860" alt="bootstrap_ _the_world_s_most_popular_mobile-first_and_responsive_front-end_framework_" src="https://cloud.githubusercontent.com/assets/44009/13218240/0f96e300-d960-11e5-9aaf-03602bf6e704.png">

**Comment by mdo** [comment]
This behavior in v4 has since been fixed.
