### ISSUE TITLE
Bootstrap with Symfony3

### ISSUE THREAD

**Issue by yolosaucisson** [twbs/bootstrap#19284]
Hi,

Sorry for my english, i'm French.
So yesterday, i installed Bootstrap v3.3.6 with Composer and now i have it in my Symfony3 project. But i have a problem. 
How to use it in my twig files ? I tried all paths as possible but no one works... So if you have ideas. Tell me.

Thanks,

**Comment by patrickhlauke** [comment]
Sorry, but for how-to / personal support requests (rather than issues relating to Bootstrap directly), please consult StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
