### ISSUE TITLE
Use CSS attribute prefix/suffix selectors

### ISSUE THREAD

**Issue by brycesnyder** [twbs/bootstrap#19297]
Currently on elements that are desired to be a button with added effects, they need to have the classes that pertain to the default styles.

i.e.

`<a class="btn btn-default"></a>`

Why not use prefix/suffix selectors to cut back on the markup and having to continually specify those previous styles?

```
[class^="btn"],
[class*=" btn"]
```

and use 

`<a class="btn-default"></a>`

Support: 
http://caniuse.com/#feat=css-sel3

Example:
http://codepen.io/brycesnyder/pen/qbepXm

**Comment by fchiumeo** [comment]
because performance reasons (see [http://codeguide.co/#css-selectors](http://codeguide.co/#css-selectors)

**Comment by cvrebert** [comment]
X-Ref: #18012

**Comment by brycesnyder** [comment]
@cvrebert @fchiumeo are there any resources that show the performance hit by chance? Genuinely interested to see.

**Comment by XhmikosR** [comment]
I believe this was right some years ago. Nowadays it shouldn't make much of a difference.

Having said that, CC @mdo for the final choice.

**Comment by mdo** [comment]
We use them in a few places in our docs, but I don't see us changing this across the entire project.
