### ISSUE TITLE
Checkbox / Radio missing form field when checking already checked radio

### ISSUE THREAD

**Issue by snovak7** [twbs/bootstrap#19301]
From example http://getbootstrap.com/javascript/#buttons-checkbox-radio

I have a form with this, and I have only 1 button, and it is already active, when I press on it again, nothing happens, and this is ok, but when I submit form, the value is missing for that radio button as it is unselected. Tested versions 3.0.0 & 3.3.6

**Comment by patrickhlauke** [comment]
Can you provide a reduced test case showing the issue, in something like JSFiddle?

**Comment by snovak7** [comment]
https://jsfiddle.net/0bzdb5ub/

You need to check the value with post fields on server side though

**Comment by twbs-lmvtfy** [comment]
Hi @snovak7!

You appear to have posted a live example (https://fiddle.jshell.net/0bzdb5ub/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 33, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0
* line 37, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
Just from your fiddle there, i see that your radio input is missing an actual `value="..."`, which - depending on browser - usually results in that form field not actually being submitted.

Are you sure the issue is relating to Bootstrap? If you remove bootstrap CSS and JS, do you still see the same problems?

**Comment by snovak7** [comment]
Sorry my bad, I have value inserted:

`<input autocomplete="off" checked="checked" id="SelectedProduct" name="SelectedProduct" type="radio" value="1">`

**Comment by snovak7** [comment]
Hello, seems like it works now, I don't know why, probably cache issue after Bootstrap 3.0.0 upgrade.
