### ISSUE TITLE
.pager class to be added to v4-dev

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#19307]
I have noticed that there is a `.pager` class name in the v4-alpha docs but there is no `.pager` class in `v4-dev`. Please add these styles into the next shipping version.

http://v4-alpha.getbootstrap.com/components/pagination/#pager

**Comment by fchiumeo** [comment]
see this pull #18782

**Comment by cvrebert** [comment]
Please note that the docs reflect the most recent alpha release version, v4.0.0-alpha.2, NOT the bleeding-edge `v4-dev` branch which is a moving target.
