### ISSUE TITLE
Add variable or class to control .row's margin-top & margin-bottom

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19303]
Currently grid .row class has only
```
  margin-left:  ($gutter / -2);
  margin-right: ($gutter / -2);
```
Which adds spacing between columns, but no spacer between rows.

I have many cards and displaying N cards per row. Right now cards are stacked to each other at top/bottom with 0 spacer and because of that I have to manually add to .row class top/bottom spacing.

Adding a new config variable could allow easily add margin-top/bottom to ($gutter / 2) or a new .row-* class could be added.

**Comment by ResentedHook** [comment]
@mdo - I'm sure you're already on it, but this seems proximally germane to #11601 (Vertical Rhythm).

**Comment by mdo** [comment]
We won't be adding any predefined margin or padding to the top/bottom of rows. If you need space between rows, use the utility classes we've added in v4 or write custom styles.
