### ISSUE TITLE
<ul> menu error to take full height on mobile

### ISSUE THREAD

**Issue by Tibicenas** [twbs/bootstrap#19306]
Hi
I'm trying to make that menu expanded take full height on mobile.
Play with vh units but looks ugly, and also trying 100%.

There is a specific bootstrap class to achieve this ?
any idea would be appreciated 
Thanks in advance.

**Comment by cvrebert** [comment]
> There is a specific bootstrap class to achieve this ?

No.

Please ask how-to questions such as this on StackOverflow or other such forums; see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
Thanks.
