### ISSUE TITLE
v4-alpha-2: font-size of <legend> larger than other form control labels.

### ISSUE THREAD

**Issue by fisharebest** [twbs/bootstrap#19302]
For [accessibility](https://www.w3.org/WAI/GL/WCAG20/tests/test168.html), groups of radio buttons need to be contained within `<fieldset>` and `<legend>`.  e.g.

```
<fieldset class="form-group row">
	<legend class="col-md-3 form-control-label">
		Sex
	</legend>
	<div class="col-md-9">
		<div class="radio-inline">
			<label><input type="radio" name="size" value="M"> Male</label>
			<label><input type="radio" name="size" value="F"> Female</label>
		</div>
	</div>
</fieldset>
```

The `<legend>` has styling `font-size: 1.5rem`, whereas other form-control-labels default to `font-size: 1rem`.  Is this difference intentional?

**Comment by patrickhlauke** [comment]
Will be fixed once https://github.com/twbs/bootstrap/pull/19277 lands. There are situations where you DO want a legend to appear larger, like a small heading (basically, in situations where you're not displaying it as a multi-column form like in your example).
