### ISSUE TITLE
Add utility class which adds ellipsis if text overflows

### ISSUE THREAD

**Issue by adrien-be** [twbs/bootstrap#19314]
As explained in the below StackOverflow question, one might often want to add an ellipsis to some text if it overflows.

http://stackoverflow.com/questions/802175/truncating-long-strings-with-css-feasible-yet/22811590#22811590

I created a pull request for this feature https://github.com/twbs/bootstrap/pull/19313

It's my first time contributing to Bootstrap so forgive me if I'm doing anything incorrectly.

**Comment by niutech** [comment]
There is already such a mixin: text-overflow() in v3 and [text-truncate()](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_text-truncate.scss) in v4. However, it should be available as a class: .text-truncate.

**Comment by niutech** [comment]
There is already such a mixin: text-overflow() in v3 and [text-truncate()](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_text-truncate.scss) in v4. However, it should be available as a class: .text-truncate.

**Comment by mdo** [comment]
Gotcha coming in #22961
