### ISSUE TITLE
Tooltip on disabled <a> btn not working

### ISSUE THREAD

**Issue by torbjoernk** [twbs/bootstrap#19322]
Having a tooltip via data attributes on a button-link is not working when the link is "disabled" via class `disabled` and `aria-disabled="true"`.

Example:
```html
<a href="http://www.example.com"
   class="btn btn-link disabled"
   aria-disabled="true"
   role="button"
   title="A tooltip not shown"
   data-toggle="tooltip">
    some text
</a>
<script type="text/javascript">
    $('[data-toggle="tooltip"]').tooltip()
</script>
```

It works fine when the class `disabled` and `aria-disabled="true"` is omitted.

**Comment by cvrebert** [comment]
Quoting from http://v4-alpha.getbootstrap.com/components/tooltips/#overview 
> Tooltips for `.disabled` or `disabled` elements must be triggered on a wrapper element.

So this isn't a bug per se.
That said, this is almost certainly due to `pointer-events: none` (see #17703), which I still think we should trash.

**Comment by torbjoernk** [comment]
Thanks for the RTFM, @cvrebert :wink: Sorry for the noise.
