### ISSUE TITLE
Customizer is using old incorrect version number in comment header

### ISSUE THREAD

**Issue by jrtitus** [twbs/bootstrap#19320]
Downloading Bootstrap from the big download button on [Bootstrap's main page](http://getbootstrap.com/) downloads version 3.3.6.

Downloading Bootstrap from the [Customize section](http://getbootstrap.com/customize/) of the web site (without making any changes) downloads version 3.3.5.

**Comment by jrtitus** [comment]
I did a diff against the two downloaded versions:

- "Customized" version shows header stating it is Bootstrap 3.3.5, with a copyright date 2011-2016, but contains all content of 3.3.6 minus the sourcemap comment at the bottom of the files.
- Main version shows header stating it is Bootstrap 3.3.6, but copyright date still says 2011-2015.

(Customized download version on the left, Main download version on the right)

**bootstrap.js**
![image](https://cloud.githubusercontent.com/assets/1756049/13329673/4ebb66a4-dbc3-11e5-81ac-b54c11e1a117.png)

**bootstrap.css**
![image](https://cloud.githubusercontent.com/assets/1756049/13329724/94ea5770-dbc3-11e5-9209-0b9b5970bc3b.png)

**bootstrap-theme.css**
![image](https://cloud.githubusercontent.com/assets/1756049/13329779/cd7b1926-dbc3-11e5-81f5-49ff4cb5beac.png)
...
![image](https://cloud.githubusercontent.com/assets/1756049/13329797/e71dd6fc-dbc3-11e5-83fa-df6f79b93d48.png)

(also notice spacing as well as decimal number differences between two versions of this file)

So, I guess it looks like the actual library content is technically equivalent, but the headers and formatting of the files in each download is different.

**Comment by XhmikosR** [comment]
Sourcemaps is normal I believe. The version is fixed in latest master.

Feel free to close or investigate more @cvrebert

**Comment by XhmikosR** [comment]
@cvrebert: how about a full rebuild of the master docs?

**Comment by jrtitus** [comment]
Looks like this is fixed in 3.3.7. Thanks, guys.
