### ISSUE TITLE
Possible contradiction with grids & cards in documentation.

### ISSUE THREAD

**Issue by morganfeeney** [twbs/bootstrap#19323]
I was reading this: http://v4-alpha.getbootstrap.com/layout/grid/ and specifically this point under the **How it works** section: _Content should be placed within columns, and only columns may be immediate children of rows_. 

I then looked at this example: http://v4-alpha.getbootstrap.com/examples/album/

It doesn't follow the convention described in your documentation as the immediate children of row in this case are cards.

Does the documentation need updating or is the example incorrect?

**Comment by alberto** [comment]
That example works because custom css was added to `.card`s to make it work like `.col`s. I'm not sure if the intention of the example was precisely to show this technique. Otherwise it's not a very good example. Aslo, it doesn't work with variable height cards.

**Comment by morganfeeney** [comment]
I understand that the example is demonstrating the use of cards. However the documentation states that the
Immediate children of rows should be columns. Should there be an update to explain that the same can be achieved with other classes that share the same value as col classes? Or should that example have some col classes added to it?

**Comment by mdo** [comment]
They're styled *as* columns, but are not using the predefined column classes. This isn't any different than using the mixins and variables to build your own grid styles.

**Comment by morganfeeney** [comment]
So why not add what you just said to that part of the doc?

**Comment by mdo** [comment]
Because that's already covered by the docs on custom grid builds. There's guidance for using he Sass mixins and more in there.
