### ISSUE TITLE
Syntax error in forms.less

### ISSUE THREAD

**Issue by j055** [twbs/bootstrap#19324]
Hi 

In the forms.less file, line 159, an ampersand is incorrectly appended to ```textarea```

```
  textarea& {
    height: auto;
  }
```

**Comment by patrickhlauke** [comment]
Good catch, thank you

**Comment by patrickhlauke** [comment]
Oh, actually...scrap that. Re-running the current version, it's intentional, and is compiled to
```
textarea.form-control {
  height: auto;
}
```
which is what's meant here.

**Comment by patrickhlauke** [comment]
If you're compiling it locally and getting the incorrect output you posted, check that your toolchain is up-to-date and that you haven't somehow altered the less files.

**Comment by j055** [comment]
Ah, I see, Looks like the compiler tool is ok. 

I wanted to use the ```.form-control``` class like a mixin so I could apply the styling to all form controls by default, i.e.

```
select,
textarea,
input[type="text"],
input[type="password"],
input[type="datetime"],
input[type="datetime-local"],
input[type="date"],
input[type="month"],
input[type="time"],
input[type="week"],
input[type="number"],
input[type="email"],
input[type="url"],
input[type="search"],
input[type="tel"],
input[type="color"] {
    .form-control();
}
```

Seemed like a good idea at the time but the results are not good. Is there another way to do this?

Thanks
Andrew

**Comment by j055** [comment]
Or perhaps the compiler tool isn't ok?

**Comment by j055** [comment]
To be clear this:

```

select,
textarea,
input[type="text"],
input[type="password"],
input[type="datetime"],
input[type="datetime-local"],
input[type="date"],
input[type="month"],
input[type="time"],
input[type="week"],
input[type="number"],
input[type="email"],
input[type="url"],
input[type="search"],
input[type="tel"],
input[type="color"] {
   .form-control();
}

.form-control {
    textarea& {
        height: auto;
    }
}
```

compiles to:

```
textareaselect,
textareatextarea,
textareainput[type="text"],
textareainput[type="password"],
textareainput[type="datetime"],
textareainput[type="datetime-local"],
textareainput[type="date"],
textareainput[type="month"],
textareainput[type="time"],
textareainput[type="week"],
textareainput[type="number"],
textareainput[type="email"],
textareainput[type="url"],
textareainput[type="search"],
textareainput[type="tel"],
textareainput[type="color"] {
  height: auto;
}
textarea.form-control {
  height: auto;
}
```

**Comment by patrickhlauke** [comment]
As this is not relating to Bootstrap, but a question about using Less, please ask in a forum or mailing list specifically for Less.

**Comment by j055** [comment]
OK, but just one last suggestion.

If you move this outside of the ```.form-control``` in the .less file

```
textarea.form-control {
  height: auto;
}
```

Anyone who wants to apply ```.form-control``` as a mixin to their inputs and selects shouldn't have any problems. It does work at the moment but you get this extra muck in the output.

I did try another less compiler and got the same result by the way.

Thanks
Andrew
