### ISSUE TITLE
images center-block doesn't work

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#19339]
Just opening this to investigate it later

![screen shot 2016-02-28 at 03 54 28](https://cloud.githubusercontent.com/assets/349621/13376889/6db9e540-ddcf-11e5-8a40-4a07b21b6600.png)

Firefox 45b10 x64, Windows 7 x64

/CC @cvrebert @mdo

**Comment by alberto** [comment]
`.center-block` was replaced by `.m-x-auto`. The latter doesn't set `display:block` while the former did, so they are not really equivalent.

**Comment by cvrebert** [comment]
If we add the `display` utilities requested in #19254, we could just tack the `display:block` utility class onto that example.

**Comment by RyanZim** [comment]
a0a157db9339b129738face06ef72c10fbe3fbf3 should have fixed this.

**Comment by cvrebert** [comment]
@RyanZim Indeed! But there was one lingering erratum that's now been fixed by 835676b99a0dd15d5e3dd0bc925e686807c24972.
