### ISSUE TITLE
No .page-header in v4?

### ISSUE THREAD

**Issue by juan-orca** [twbs/bootstrap#19338]
Hi,

I am searching for the [page-header CSS component](http://getbootstrap.com/components/#page-header) in v4-alpha. It looks like it was not ported over from v3. Can someone else confirm?

**Comment by cvrebert** [comment]
It's indeed gone. Per http://v4-alpha.getbootstrap.com/migration/#typography :
> * Dropped the `.page-header` class entirely.

**Comment by Saucy** [comment]
@cvrebert May I ask why .page-header class is removed?

**Comment by cvrebert** [comment]
@Saucy It was removed in bf085b1a02238611d4962717a02f71def0fa8ba0 without much explanation. I've filed #19439 to ask @mdo to add his rationale to the docs.

**Comment by Saucy** [comment]
@cvrebert Awesome, I'll subscribe to that issue and keep a look out on why it was remove. Thanks!
