### ISSUE TITLE
No list item image

### ISSUE THREAD

**Issue by DarkhejMaster** [twbs/bootstrap#19334]
When you create a list with ul and li using no classes, the first list item does not get any image, dot or anything similar if you want to have your own list item image.

`<ul>
  <li>Home</li>
  <li>Products</li>
  <li>About Us</li>
  <li>Contact</li>
</ul>`

EDIT: The first list item is going on the right side of the page.

**Comment by hebbet** [comment]
provide an jsfiddle or similar, and the version of bootstrap you are using.

**Comment by DarkhejMaster** [comment]
Can't get the js fiddle (https://jsfiddle.net/9cyyvb5p/) to miss the list item image.
I am using bootstrap v 3.3.6

**Comment by twbs-lmvtfy** [comment]
Hi @DarkhejMaster!

You appear to have posted a live example (https://fiddle.jshell.net/9cyyvb5p/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 54, column 3 thru column 17: Stray doctype.
* line 55, column 1 thru column 16: Stray start tag ```` html ````.
* line 57, column 3 thru column 8: Stray start tag ```` head ````.
* line 58, column 5 thru column 26: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 58, column 5 thru column 26: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 59, column 5 thru column 212: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 59, column 5 thru column 212: Element ```` link ```` is missing required attribute ```` property ````.
* line 60, column 5 thru column 11: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 63, column 3 thru column 9: Stray end tag ```` head ````.
* line 65, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 66, column 3 thru column 9: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 87, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
> Can't get the js fiddle to miss the list item image.

That tends to indicate that the problem is related to your specific setup, rather than being a bug in Bootstrap itself.
Try asking on StackOverflow or similar for help; see https://github.com/twbs/bootstrap/blob/master/README.md#community for links. Good luck.
