### ISSUE TITLE
.navbar-brand with non-anchor element isn't vertically centered

### ISSUE THREAD

**Issue by petetnt** [twbs/bootstrap#19349]
This issue is one issue that can be fixed in two different ways that somewhat make it seem like it's two different issues :cat: 

If we look at the `.navbar-brand` on the [docs](http://v4-alpha.getbootstrap.com/components/navbar/#brand) you'll see this pretty vague statement:

> The .navbar-brand can be applied to most elements, but an anchor works best

The `working best` part shows up immediately in the examples below because the `h1.navbar-brand` element is not vertically aligned:

![image](https://cloud.githubusercontent.com/assets/7641760/13390952/5322157a-deda-11e5-8513-72f32f3b7ac0.png)

There are two ways to solve this:

1. Always reset and setup the margins paddings etc. for the `.navbar-brand`-elements or

2. Make a mention about the users needing to change the CSS if other elements that `a` are being used, sort of like how the v3 version mentions [overriding CSS when using images](http://getbootstrap.com/components/#navbar-brand-image)

**Comment by mdo** [comment]
This was addressed in c8bd62b214add34ab133cb11241d528ef3402ef0.
