### ISSUE TITLE
Button with label component

### ISSUE THREAD

**Issue by JThompson1123** [twbs/bootstrap#19342]
Hi, could we see some new components in Bootstrap? Such as full-width modals that can be solid or transparent, buttons with labels etc.

I like the Semantic UI components and wish they were in Bootstrap.

**Comment by cvrebert** [comment]
> Such as full-width modals

See https://github.com/twbs/bootstrap/issues/17381#issuecomment-138038976

**Comment by cvrebert** [comment]
> [buttons with labels](http://semantic-ui.com/elements/button.html#labeled)

Hmm, so basically an [input group](http://v4-alpha.getbootstrap.com/components/input-group/) with no text input and that isn't block-level.
Or a generalization of #18759 to buttons other than "X" buttons.

> etc.

Feel free to open new issues regarding other specific widgets, after searching through closed issues for duplicates and being mindful of not opening too many feature requests all at once.

**Comment by JThompson1123** [comment]
Example: https://gyazo.com/bd279be73b2c8064a659ee79c980726e
Example: Youtube Subscribe button

**Comment by mdo** [comment]
Seems like stuff we've already implemented, only slightly customized. Punting as a won't fix/implement.
