### ISSUE TITLE
Add a Sidebar component

### ISSUE THREAD

**Issue by JThompson1123** [twbs/bootstrap#19345]
Many Frameworks have Sidebars available out of the box.

What about a customisable sidebar? It seems to be the only thing i have an issue with is creating my own sidebar.

Great for people building admin panels, one less thing to create / worry about.

allow, items, sub-menus, headers etc.

**Comment by ZakariaRidouh** [comment]
This is actually a really good idea, @mdo any plans about this?

**Comment by yasinkocak** [comment]
:+1:

**Comment by cvrebert** [comment]
@JThompson1123 To clarify, do you mean a vanilla sidebar, or an off-canvas sidebar (#17502)?

**Comment by JThompson1123** [comment]
@cvrebert Sorry, i've been busy. What exactly do you mean by vanilla or off-canvas?

My example would be like a sidebar in an admin panel, you click a button in the navbar and it slides in etc. It has sub-menus etc.

**Comment by cvrebert** [comment]
> it slides in etc.

Okay, so off-canvas then. A "vanilla"/normal/static sidebar would always be visible.

**Comment by cvrebert** [comment]
Duplicate of #17502.
