### ISSUE TITLE
Enhanced Footer

### ISSUE THREAD

**Issue by MatanSilver** [twbs/bootstrap#19356]
Hello,
I am currently using the navbar-fixed-bottom class to create a sticky footer for my site. However it wastes a lot of space for sites where the content is longer than the size of the window. Would it be possible to make a footer class where the footer stays at the bottom of the windows when the content is small, but then follows the end of the content if the content is large (as opposed to always staying visible at the bottom of the window no matter what)? Thanks.

**Comment by NYPD** [comment]
Do you mean something like this? http://getbootstrap.com/examples/sticky-footer/

You might also have better luck asking on stackoverflow for questions like this.

**Comment by MatanSilver** [comment]
Yes I saw that, but with that (navbar-fixed-bottom), if the content was longer than the window, the footer would still be visible at the bottom of the window, instead of following the bottom of the content. I will ask around some forums for other solutions, but I think that a comprehensive set of footer classes should have what I am describing above (take github for example, on this page, the footer appears at the bottom of the content, and only sticks to the bottom of the window if the content is less than the window size). It would save a lot of space, especially when considering limited screen real estate in mobile pages. I appreciate the link though!

**Comment by MatanSilver** [comment]
<img width="1432" alt="screen shot 2016-02-29 at 4 04 32 pm" src="https://cloud.githubusercontent.com/assets/4491337/13408900/2e3a4006-defe-11e5-9d57-6890dd3d9bea.png">
Notice how the footer is not at the bottom of the page, but at the bottom of the window.

**Comment by NYPD** [comment]
I understand, but in that example the footer gets pushed down if the content is longer than the window.
![pic 1](https://cloud.githubusercontent.com/assets/6412879/13409814/9ae4588c-df02-11e5-867d-d5d7051690ef.PNG)

and

![pic 2](https://cloud.githubusercontent.com/assets/6412879/13409820/9fc176aa-df02-11e5-91fd-4de1664a6188.PNG)

Having enhanced footer classes might be neat, but it depends on knowing what the height of the footer is before hand and offsetting that in the css. (In the getbootstrap link the body has a margin-bottom of 60px)

**Comment by MatanSilver** [comment]
Oh I see. Interesting, I must be doing something wrong because mine doesn't get pushed down. I will double check my html. Thanks!
