### ISSUE TITLE
.center-block class isn't responsive

### ISSUE THREAD

**Issue by andyrichardson** [twbs/bootstrap#19357]
There is a lack of ability to center element based on screen size.
This is inconsistent with the general class syntax of bootstrap 4, see below:

**Text Center Evolution**
`<p class = "text-center"> Bootstrap 3 </p>`
`<p class = "text-*-center"> Bootstrap 4 </p>`

**Block Center Evolution**
`<img class = "center-block"/>    //Bootstrap 3`

`<img class = "center-block"/> // Bootstrap 4 (current)`

`<img class = "center-*-block"/> // Bootstrap 4 (fix)`

**Conclusion**
Create "center-*-block" classes

**Comment by saviomd** [comment]
I think .center-block should reset float too, so it could be used with columns and be less verbose.
ie.
```
<div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4"></div>
```
would become
```
<div class="col-xs-8 col-md-6 col-lg-4 center-xs-block"></div>
```

**Comment by RyanZim** [comment]
`.center-block` was removed in #19102 in favor of `.m-x-auto`. If it's going to stay that way, we should have a `.display-block` or `.display-*-block` class as recommended in  #19343.

**Comment by cvrebert** [comment]
`.display-*-block` was rejected in #18410.
Closing this since, as noted, `.center-block` no longer exists.
