### ISSUE TITLE
Add responsive left or right navigation

### ISSUE THREAD

**Issue by anggadarkprince** [twbs/bootstrap#19350]
I think will be great if bootstrap gives choice how navigation getting responsive on mobile with slide-direction and some framework offer tooltips like a tour pointing element of website by sequence to help user understand web app feature or functionality of something..

**Comment by cvrebert** [comment]
A "tour" feature has been rejected; see #12788.

**Comment by cvrebert** [comment]
> will be great if bootstrap gives choice how navigation getting responsive on mobile with slide-direction

@anggadarkprince Are you referring to off-canvas navigation sidebars such as http://codepen.io/scottb/full/javhr/ ?

**Comment by anggadarkprince** [comment]
Oh I didn't know if tour feature exist kind as bootstrap plug-ins,, 

Yes,  off - canvas navigation,  and we could determine to use both left and right either, because it gives the same experience with mobile app with touch event obviously..

**Comment by cvrebert** [comment]
Duplicate of #17502 then.
