### ISSUE TITLE
Add tooltip border color variable

### ISSUE THREAD

**Issue by yasinkocak** [twbs/bootstrap#19360]
Possible to set only border color for tooltip

See: http://jsfiddle.net/2htZe/1852/

**Comment by twbs-lmvtfy** [comment]
Hi @yasinkocak!

You appear to have posted a live example (http://fiddle.jshell.net/2htZe/1852/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 35, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 2.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@yasinkocak Please describe your request in greater detail.

**Comment by yasinkocak** [comment]
@cvrebert on http://jsfiddle.net/2htZe/1852/ u can see the tooltip have border color blue with white background.

If you can make it possible to set variables where u fill in border color and the background of the tooltip.

Now u can set only background color with the same border-color

**Comment by twbs-lmvtfy** [comment]
Hi @yasinkocak!

You appear to have posted a live example (http://fiddle.jshell.net/2htZe/1852/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 35, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 2.3.2

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Going to punt on adding a border here, thanks though!
