### ISSUE TITLE
Add .form-row class to make horizontal & vertical spacing between inputs the same in grid forms

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19369]
Let say I have a form:

- name
- day, month, year (3 inputs in 1 row)
- form-group3 input
- ...

And want to style row with 3 inputs so each input would save form-group spacing.

I've added new class `.form-row` and there is sass:
```sass
.form-row [class^="col-"] {
  padding-top: 0;
  padding-bottom: 0;
}

.form-row [class^="col-"]:not(:last-of-type) {
  padding-right: $form-group-margin-bottom / 2;
}

.form-row [class^="col-"]:not(:first-of-type) {
  padding-left: $form-group-margin-bottom / 2;
}
```

and HTML:
```html
    <div class="form-group">
        <input type="text" class="form-control">
    </div>

    <div class="row form-row">
        <div class="col-xs-3">
            <div class="form-group">
                <input type="text" class="form-control">
            </div>
        </div>
        <div class="col-xs-3">
            <div class="form-group">
                <input type="text" class="form-control">
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <input type="text" class="form-control">
            </div>
        </div>
    </div>
```

And now form looks amazing and all inputs have same spacing between each other from all sides.

I also would add the example on how to make inline inputs (not inline-form) into tutorial http://v4-alpha.getbootstrap.com/components/forms

**Comment by cvrebert** [comment]
I'm not sure whether using the grid in such a scenario would be advisable. Personally I'd go for something more like http://jsbin.com/tufebam/edit?html,css,output

----

> `.form-row [class^="col-"] { padding-top: 0; padding-bottom: 0; }`

This seems unnecessary. Columns don't have any default vertical padding to begin with, so there's no need to explicitly zero the vertical padding.

**Comment by Mevrael** [comment]
> I'm not sure whether using the grid in such a scenario would be advisable. Personally I'd go for something more like http://jsbin.com/tufebam/edit?html,css,output

Added one input and your case not working http://jsbin.com/gekodi/1/edit?html,css,output All 3 inputs should be same width as input on first row. Also form itself is responsive and when I resizing window all input widths also should change, you are hardcoding width.

I attached an image to show my use case.
![inline-input-bs4-example](https://cloud.githubusercontent.com/assets/7879528/13488306/0fd70158-e129-11e5-8028-45b41c593465.jpg)


I also don't like using grid .col for this but since there is no simple classes to build content columns and helpers with .inline-block was rejected I haven't found another option.

> This seems unnecessary. Columns don't have any default vertical padding to begin with, so there's no need to explicitly zero the vertical padding.

Forgot about this, well for me it is unaccaptable to have 0 spacing between rows and cells and since this #19303 was rejected I will leave it as is. I also changed margin to padding because margins for .col was not working as expected:

```scss
[class^='col-'] {
  padding-top: $grid-gutter-width / 2;
  padding-bottom: $grid-gutter-width / 2;
}
```

**Comment by twbs-lmvtfy** [comment]
Hi @Mevrael!

You appear to have posted a live example (http://jsbin.com/gekodi/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 14, column 7: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
> All 3 inputs should be same width as input on first row.

Ah, I was not aware of that constraint.

> Also form itself is responsive and when I resizing window all input widths also should change

I guess I glommed onto the specific "date fields" example too much. (I don't quite see the point of very-unnecessarily-wide date fields on large screens (makes it harder to read IMO), but there are of course many other cases where proportional field widths are sensible.)

So basically it seems like you want to be able to tweak the grid gutter width in grid-based forms. Not sure it's worth it, but now I see where you're coming from.

CC: @mdo

**Comment by Mevrael** [comment]
> (I don't quite see the point of very-unnecessarily-wide date fields on large screens (makes it harder to read IMO)

That's why I added xxl breakpoint and increasing margins/paddings and font sizes for each breakpoint. Form in current example is also in container which will never let form be too wide. And yes, there are many use cases.

**Comment by mdo** [comment]
Hopefully we'll get custom gutters per breakpoint, but until then you can use the grid, utilities, and other form helpers to get you pretty close to this I think. Closing out as I don't plan to make any major changes here for v4.
