### ISSUE TITLE
Add new vars: $input-bg-focus and $input-color-focus

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19364]
Now there are only 2 variables to style focused input:

$input-border-focus
$input-box-shadow-focus

However, there are additional 2 variables to style input and there is no way to change those styles when element is focused:

$input-bg:
$input-color:

Adding 2 new variables $input-bg-focus and $input-color-focus would fix this.

**Comment by mdo** [comment]
Merged #19370.
