### ISSUE TITLE
What is correct name for col offset classes?

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19368]
In docs http://v4-alpha.getbootstrap.com/layout/grid/#example-offsetting-columns classes for offsetting columns are named `.col-bp-offset-x` while the real class names in v4-dev currently are in format `.offset-bp-x`

**Comment by SharkyKZ** [comment]
.offset-bp-x is the new naming format, see https://github.com/twbs/bootstrap/pull/19099

**Comment by patrickhlauke** [comment]
if you're using the latest v4-dev, then please consult the documentation that comes with it. http://v4-alpha.getbootstrap.com is only accurate to the last proper alpha release (v4.0.0-alpha.2)
