### ISSUE TITLE
Bootstrap 4 roadmap?

### ISSUE THREAD

**Issue by tormit** [twbs/bootstrap#19362]
Any ideas when Bootstrap 4 would become stable or beta?

I'm in dilemma whether to use B4 for upcoming project or stay with B3. I like B4 more, because it's Sass based and easier to incorporate with Laravel's Elixir. Just want to know if B4 going to change a lot in future?

**Comment by petetnt** [comment]
Check out PR #17021 which list the features meant to land in V4

**Comment by patrickhlauke** [comment]
As for "when is it going to be in stable/beta", the answer unfortunately is "when it's ready". No specific timescales are set for this, at the moment.

**Comment by webraj1** [comment]
I am starting the application from scratch today, I am the owner of the business. It will take 6 months of development efforts & looking for bootstrap 4 , I hope by the the time it will get stable, So I am okay to make few iterations when it comes to beta or stable release but do not want major trouble, Can anyone suggest me if I can start with bootstrap 4 for production today?

**Comment by cbwiedel** [comment]
Alpha 6 is shipped, what comes next is the first Beta. They say no major changes _should_ be added, only efficiencies. Take that how you'd like, I'm in the same boat and am itches to use it.

**Comment by moehoward** [comment]
They knew the answer back in 1956.
https://www.youtube.com/watch?v=CcWbZUgymkw

**Comment by atilkan** [comment]
Bootstrap 4 is basically Foundation 6 which released years ago.

**Comment by bardiharborow** [comment]
Duplicate of #22576, #23027, #23054 and #23120. Please go read all those issues, and feel free to ask any remaining questions you have.
