### ISSUE TITLE
Alternative row hover colour for a specific table row

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#19375]
I have a class called 'table-green-hover' which when set on a table makes it so that the hover colour is LightGreen instead of the usual bootstrap colour

`.table-green-hover > tbody > tr:hover > td,
.table-green-hover > tbody > tr:hover > th {
  background-color: LightGreen;
}`

However for 2 specific rows in my table (with a class of 'logout-hover') I want those to be a completely different colour, I thought of doing it as

`.logout-hover > tr:hover > td {
  background-color: LightBlue;
}`

Though it doesn't seem to be doing anything at all, when I hover over those 2 specific rows they still show with the LightGreen.

**Comment by cvrebert** [comment]
Please use StackOverflow, IRC, or Slack for personal how-to questions such as this. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker for links.
Thanks.
