### ISSUE TITLE
Feature request: .col-*-down-offset-N classes

### ISSUE THREAD

**Issue by smsteel** [twbs/bootstrap#19377]
You've done new responsive classes which can work in both direction: hide only on large or hide only on small. It would be logical to extend this functionality on other things.

It would be useful to make column offset only for small device:
```html
<div class="row">
    <div class="col-xs-2">.col-xs-2</div>
    <div class="col-md-4 col-sm-8 col-xs-8">.col-md-4 .col-sm-8 .col-xs-8</div>
    <div class="col-md-1 col-sm-2 col-xs-2">.col-md-1 col-sm-2 col-xs-2</div>
    <div class="col-md-5 col-sm-10 col-xs-10 col-sm-down-offset-2 col-xs-down-offset-2"></div>
</div>
```
So the last column will be with offset only on extra small and small devices.

**Comment by cvrebert** [comment]
Seems like your example has some redundancy. For the relevant column, did you mean:
```html
<div class="col-xs-10 col-md-5 col-sm-down-offset-2"></div>
```
?

**Comment by cvrebert** [comment]
I note that the same result can already be accomplished with existing classes, albeit using 1 more class:
```html
<div class="col-xs-10 col-md-5 col-xs-offset-2 col-md-offset-0"></div>
```

**Comment by mdo** [comment]
No plans to add these classes at this time. Thanks though!.
