### ISSUE TITLE
.nav-inline class ignored when .navbar-nav class is used

### ISSUE THREAD

**Issue by andyrichardson** [twbs/bootstrap#19373]
_.nav-link_ elements become block elements when using  the _.navbar-nav_ class.

```html
<nav class="navbar">
    <div class="nav nav-inline navbar-nav">
        <a class="nav-link" href="#">Test</a>
        <a class="nav-link" href="#">Test 2</a>
    </div>
</nav>
```

Removal of the _.navbar-nav_ class fixes this issue although that should not be necessary. 

I can confirm this is a new issue for bootstrap 4 which was not present in bootstrap 3.

**Comment by cvrebert** [comment]
X-Ref: #18467

**Comment by mdo** [comment]
The navs should use one modifier in this instance—it's either the `navbar-nav` or an `nav-inline`, not both.
