### ISSUE TITLE
Add text-align: left to .form-control

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19379]
.form-control does not have text-align and because of that text-align might be inherited from parent element. Inputs should have text-align: left by default.

.form-control used as a div contenteditable=true

```html
    <div class="form-group">
        <div contenteditable="true" class="form-control"></div>
        <input type="hidden">
    </div>
```

**Comment by cvrebert** [comment]
What about RTL text/pages?

**Comment by Mevrael** [comment]
In RTL you will need in any case add styles like direction:RTL, text-align: right and is a good idea for .form-control-right

**Comment by cvrebert** [comment]
X-Ref: #17925

**Comment by Mevrael** [comment]
The only one input[type="number"] should have right align if rest is aligned to left. From design and UX point of all elements must have same structure and proportions. It is the same as making selects also align to right only because they have arrow button there. I agree that helper here would be better choice because it is only for one specific decorative case.

**Comment by mdo** [comment]
Going to punt on this—I'd rather leave it inherited as it's the browser default.
