### ISSUE TITLE
Collapse without transitions doesn't work on nested triggers.

### ISSUE THREAD

**Issue by apokryfos** [twbs/bootstrap#19386]
Having i.e. a trigger like: 
`<h4 class="panel-title" data-parent="#accordion" data-toggle="collapse" data-target="#panel1">Trigger for the first panel <a class="glyphicon glyphicon-plus-sign" data-parent="#accordion" data-toggle="collapse" data-target="#panel1"></a></h4>` 
works on all browsers when the h4 is clicked but only works on browsers with transitions supported if the anchor glyph is clicked. I think this is because the event propagates from the anchor to the h4 and causes the panel to hide as soon as it's shown by triggering the click on the h4. 

My workaround was to create an anchor in the panel title e.g:
`<h4 class="panel-title"><a  data-parent="#accordion" data-toggle="collapse" data-target="#panel1">Trigger for the first panel</a><a class="glyphicon glyphicon-plus-sign" data-parent="#accordion" data-toggle="collapse" data-target="#panel1"></a></h4>` 
however this is not ideal since I want the entire panel title to trigger the panel collapse/expand.

**Comment by cvrebert** [comment]
@apokryfos Would you be so kind as to make a JS Bin or JS Fiddle that demonstrates the problem?

**Comment by apokryfos** [comment]
See http://jsfiddle.net/wq428aLz/ 
The (+) glyph works on Chrome but in IE 9 it closes other open panels but doesn't open the current one. 
Clicking on the panel title (anywhere in the grey area) works for both.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
