### ISSUE TITLE
Add placeholder support to <select>

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19380]
What it does?
1. if select.form-control has a placeholder attribute
2. adds a new first option with value="" and content from palceholder attribute
3. if there are no any option with "selected" attribute then also make first option selected
4. now select has a "placeholder" same color as .form-control::placeholder
5. Enjoy, welcome to 2016 and say good bye to "stackoverflow: how to add placeholder for select"

sass:
```sass
select.form-control[placeholder] option:first-child {
  color: $input-color-placeholder;
}

select.form-control[placeholder] option:not(first-child) {
  color: $input-color;
}

.placeholder {
  color: $input-color-placeholder;
}
```

and JS for side effects:
```es6

document.addEventListener('DOMContentLoaded', () => {
    document.getElementsByTagName('select').forEach((select) => {
        let placeholder = select.getAttribute('placeholder');
        if (placeholder !== null) {

            let selected = false;
            for (let k = 0; k < select.options.length; k++) {
                if (select.options[k].hasAttribute('selected')) {
                    selected = true;
                    break;
                }
            }

            let option = document.createElement('option');
            option.setAttribute('value', '');
            option.textContent = placeholder;
            select.insertBefore(option, select.firstChild);

            if (!selected) {
                select.selectedIndex = 0;
            }

            if (select.selectedIndex === 0) {
                select.classList.add('placeholder');
            } else {
                select.classList.remove('placeholder');
            }
            select.addEventListener('change', () => {
                if (select.selectedIndex === 0) {
                    select.classList.add('placeholder');
                } else {
                    select.classList.remove('placeholder');
                }
            });
        }
    });
});
```

If you will upvote this I'll make an ES5 version without my .forEach() added to many oldschool prototypes.

**Comment by cvrebert** [comment]
This JS is too brittle; it doesn't handle `<select>s` added to the DOM after the initial page load.

**Comment by Mevrael** [comment]
Well, in that case all the code block inside forEach can be an object and called via:
select = document.createElement('select');
...
BsSelect.init(select);

**Comment by patrickhlauke** [comment]
I admit that I'm not a fan of silently extending native elements this way. Particularly thinking about developers looking at code like `<select placeholder="..." ...>` in a bootstrapped site and assuming that this is standard behavior of `<select>`, copy-pasting it into their own (non-bootstrapped) projects, and then getting very confused about why it doesn't work. So, in the first instance, I'd rather see `data-placeholder` being used, as that more clearly signals that it's a non-standard attribute.
More generally, this still feels like something that would perhaps best be left to a 3rd party plugin, rather than as part of BS core, though my feelings aren't all that strong about that.

**Comment by patrickhlauke** [comment]
Further to brittleness of JS, does the code also handle situations where a `<select>` would be dynamically updated (for instance as a result of another control being changed/activated in the form)? e.g. a whole new set of `<option>`s being injected, and the `data-placeholder` attribute being modified dynamically?

**Comment by cvrebert** [comment]
Sounds like HTML already provides for a placeholder `<option>` for `<select>`s: https://html.spec.whatwg.org/multipage/#placeholder-label-option
Albeit, good luck styling it at present. However, once CSS Selectors Level 4 becomes a thing, seems like you could do:
```css
.placeholder:checked /* are there really any browsers that allow styling <option>s? */
select:has(.placeholder:checked) {
  color: $input-color-placeholder;
}
```

**Comment by patrickhlauke** [comment]
@cvrebert my reading of that (slightly inpenetrable) wording is: if there `<select>` has a `required` attribute, and the first `<option>` in the list of options is empty `<option></option>`, then treat it as the placeholder and fail constraint validation (i.e. the user is required to select something other than that first empty `<option></option>`). this does not, to my understanding, say anything about specifying a non-empty `<option>` as being the placeholder, nor does it define any other way of giving the `<select>` a placeholder

**Comment by patrickhlauke** [comment]
oh, actually, strike that. reading further, it's the `value` that needs to be empty. 
```
<select name="unittype" required>
 <option value=""> This would be the placeholder due to empty value </option>
 <option value="1"> ... </option>
 ...
</select>
```
So, it may be a case of using this instead then...

**Comment by Mevrael** [comment]
> .placeholder:checked
This is only for options, not <select>; `.placehodler` class is needed only for <select> itself. When you set color on option, only dropdown item color is changed, not <select> selected item (dropdown closed).

You need to add `.palceholder` on <select> when 1st item is selected. CSS4 parent selectors is still far away from being a standard.

And yes, basic styles, like color, are allowed in any browser.

HTML, does not provide placeholder for option or select. It allows native `required` attribute to work with option with empty value.

**Comment by Mevrael** [comment]
@patrickhlauke 
> Further to brittleness of JS, does the code also handle situations where a <select> would be dynamically updated (for instance as a result of another control being changed/activated in the form)? e.g. a whole new set of <option>s being injected, and the data-placeholder attribute being modified dynamically?

Any code is not a magic and will not cover all cases. If it is required to modify select with JS and as a result it will break placeholder, then you have to update it with provided BsSelect.init() or smth. The init() method can be extended to cover more cases.

Software engineers have to know and understand what they are doing not copy-pasting.

**Comment by mdo** [comment]
Not going to be adding custom JS to encourage/imply browser support for the `placeholder` attribute on `<select>`s, nor anything else that augments the first `<option>`.
