### ISSUE TITLE
.card-footer not aligned to bottom of card in .card-group

### ISSUE THREAD

**Issue by ketangoyani** [twbs/bootstrap#19381]
![bootstrape jpg](https://cloud.githubusercontent.com/assets/11384794/13493482/5f891a70-e164-11e5-978f-a14ef1d192d4.png)
what i want is 
![solved](https://cloud.githubusercontent.com/assets/11384794/13493517/8707ca10-e164-11e5-84c5-6e407dd120bd.png)

**Comment by MatthewRayfield** [comment]
Can't seem to reproduce this issue.

Looks like it's working here: https://jsfiddle.net/555Lq4k1/

Is this different than what you're doing @ketangoyani ?

**Comment by casselc** [comment]
Using .card-title seems to cause this issue in subsequent cards: https://jsfiddle.net/kn3b86mn/

**Comment by eproxus** [comment]
Also occurs inside a `.card-deck`: https://jsfiddle.net/mtcL9fwf/6/

**Comment by Sebsebzen** [comment]
I'm having the same problem. It's a bit annoying.

**Comment by rwaltenberg** [comment]
Would not a flexbox solve this?

**Comment by brjadams** [comment]
I'm also experiencing this. @rwaltenberg 's example doesn't work with .card-deck

**Comment by pgaby28** [comment]
for card-deck just replace card-block by card-body https://jsfiddle.net/mtcL9fwf/6/
