### ISSUE TITLE
Quick switch of fading modals breaks modal behavior

### ISSUE THREAD

**Issue by birjolaxew** [twbs/bootstrap#19385]
If you quickly `.modal("hide")` one fading modal, then `.modal("show")` another, a few things happen:

- The class `modal-open` isn't applied to `<body>`
- No padding (to account for the lack of scrollbar) is applied to `<body>` until the second modal is hidden, at which point it is added permanently.

There might be more side-effects.

It seems that you have to wait roughly .35 seconds between hiding one modal, and showing another, if you wish to avoid these effects. Example code below:

```javascript
var foo = $("<div class='modal fade'><h1>Modal 1</h1></div>");
var bar = $("<div class='modal fade'><h1>Modal 2</h1></div>");

foo.modal();
// body: .modal-open, 15px padding
// modal: foo is shown

foo.modal("hide");
bar.modal();
// body: no class, no padding
// modal: bar is shown

bar.modal("hide");
// body: no class, 15px padding
// modal: none
```

**Comment by cvrebert** [comment]
Modal's show/hide methods are asynchronous. Therefore, code such as:
```js
foo.modal("hide");
bar.modal("show");
```
is invalid. You need to wait for the showing/hiding to actually complete (by listening for the `shown`/`hidden` events; see http://getbootstrap.com/javascript/#modals-events ) before calling the show or hide methods again.
