### ISSUE TITLE
project not working properly

### ISSUE THREAD

**Issue by harshakantha94** [twbs/bootstrap#19392]
#bootstrap feedback icons not showing to my script
#data not inserted to the database
[ci2.zip](https://github.com/twbs/bootstrap/files/157796/ci2.zip)

**Comment by patrickhlauke** [comment]
Please use StackOverflow or similar for support/how-to questions https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
