### ISSUE TITLE
Buttons in .modal-footer not clickable in Windows Firefox when the modal is very long

### ISSUE THREAD

**Issue by roelgit** [twbs/bootstrap#19390]
Using Firefox (latest, v44.0.2), it is not possible to click on the default modal buttons (down bellow) when the modal contains a lot of content, see an example: http://jsbin.com/tewizumipi/edit?html,output

In Google Chrome (latest, v49.0.2623.75 m) and Internet Explorer 11, there is no problem (the buttons are clickable) so i guess this is probably a browser (Firefox) bug? _Tested under Windows 7 and 8.1._

Thanks!

**Comment by cvrebert** [comment]
Clone of the Bin under a registered account so it's not subject to limitations on full-screen preview time:
http://output.jsbin.com/rogixax/1

**Comment by cvrebert** [comment]
Confirmed in Firefox 44 + Win 8.1 on Sauce Labs.

**Comment by cvrebert** [comment]
After some rough bisection, it looks like this became broken in Firefox 33.

**Comment by cvrebert** [comment]
> Tested under Windows 7 and 8.1.

Also affects Windows 10.

**Comment by cvrebert** [comment]
Doesn't reproduce on OS X.

**Comment by cvrebert** [comment]
Filed Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1253468

**Comment by cvrebert** [comment]
Added to the Wall of Browser Bugs: #19393
It's in Mozilla's hands now.

**Comment by cvrebert** [comment]
This is fixed in upcoming Firefox 45: https://bugzilla.mozilla.org/show_bug.cgi?id=1217012
