### ISSUE TITLE
Bootstrap collapse accordion

### ISSUE THREAD

**Issue by CaredduMattia** [twbs/bootstrap#19397]
I'm having a problem with accordion.
In accordance with documentation example ( http://getbootstrap.com/javascript/#collapse-example-accordion ) this is my code : 
```
<div class="container">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a role="button"  data-toggle="collapse" data-parent="#accordion"  href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Failed Backups
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                       
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Weeks Backup
                        </a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                    <div class="panel-body">
                        
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Months Backup
                        </a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                    <div class="panel-body">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

```
This works right and I can open and close accordion right. But if I add something to `<div class="panel-body">` for example : 
```
<form class="form-inline" role="form">
                            <label for="sel1">Months Ago</label>
                            <select class="form-control" id="sel1">
                                <option selected="selected">1</option>
                                <option>2</option>
                                <option>3</option>
                            </select>
                            <button type="button" class="btn btn-default" id="updatemonthsbutton">Update</button>
                        </form><br>
                        <div class="monthsBackupCollapse"></div>

```
Accordion works wrong. I can't close it by cliking on. It just close if I click on others accordion.

**Comment by cvrebert** [comment]
@CaredduMattia Please make a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by CaredduMattia** [comment]
From here i can't open or close any accordion. https://jsfiddle.net/cb5wy5z3/

**Comment by twbs-lmvtfy** [comment]
Hi @CaredduMattia!

You appear to have posted a live example (https://fiddle.jshell.net/cb5wy5z3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Having added jQuery as noted: https://fiddle.jshell.net/cb5wy5z3/1/

**Comment by cvrebert** [comment]
@CaredduMattia https://fiddle.jshell.net/cb5wy5z3/1/ works fine for me. Does that fiddle work on your browser?

**Comment by CaredduMattia** [comment]
https://fiddle.jshell.net/cb5wy5z3/1/ works right, but the same doesn't work on my project. The only thing that change si that i include other js library but I can't get any js error in console.

**Comment by cvrebert** [comment]
Then this is presumably not a bug in Bootstrap, but rather in those other JS libraries or in your webpage's code.
We are unable to provide personal support or give help regarding third-party libraries. Please ask for help on StackOverflow or similar; see https://github.com/twbs/bootstrap/blob/master/README.md#community
Good luck!
