### ISSUE TITLE
Update popover content

### ISSUE THREAD

**Issue by vtur** [twbs/bootstrap#19396]
Hi, I create popover via js, and for updating content i using .popover('destroy') and after   .popover('show') with new content. In one of my project it worked, but in my new project  .popover('destroy') worked later than .popover('show') and destroying all (old and new) popovers. Please, help me) And sorry for my  English.

**Comment by cvrebert** [comment]
Please ask personal support questions on StackOverflow or similar rather than this issue tracker.
See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker for links.
Thanks.
