### ISSUE TITLE
Style native <select> arrow by adding new wrapper class .form-group-select

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19399]
Each browser is making his own arrow for `<select>` and Firefox's one is the most ugly. It adds grey block behind arrow which does not have border radius when input has.

I would recommend adding same triangle to all selects as used in .dropdown.

However, ::after selector does not work on select tag, it should be wrapped within another class, let say `.form-group-select` and markup will be:

```html
<div class="form-group-select">
   <select ...>
</div>
```

This approach will add custom arrow only when select is wrapped aroung new class and if developers want keep using native UI they still can do it.

First, hide native arrows:
```sass
// remove browser dropdown arrow and use custom class to add dropdown arrow
.form-group-select select {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
.form-group-select select::-ms-expand {
  display: none;
}
```

And now add custom arrow, something like:
```sass
.form-group-select::after {
  content: "";
  border-top: 0.3em solid #999;
  border-right: 0.3em solid transparent;
  border-left: 0.3em solid transparent;
  position: absolute;
  top: 35%;
  right: 20px;
}
```

**Comment by wolfy1339** [comment]
There's [this](http://v4-alpha.getbootstrap.com/components/forms/#select-menu) in the docs already that looks to do exactyl what you are describing.

**Comment by Mevrael** [comment]
@wolfy1339  Looks like, yes. I will check it. Does custom form styles requires anything except importing custom-forms.scss? Is it using any js?

**Comment by cvrebert** [comment]
@Mevrael Currently none of the custom form controls use JS.

**Comment by mdo** [comment]
Closing as we have our custom select in place already.
