### ISSUE TITLE
Navbar Collapse Triggering Multiple Animations in iOS

### ISSUE THREAD

**Issue by LittleCoding** [twbs/bootstrap#19405]
### Problem/Motivation

In browsers on the iOS platform multiple open/close (height) animations can be triggered by the opening the mobile navbar (burger icon) due to JS swopping of the .collapse / .collapsing classes. This is limited to the mobile WebKit rendering engine and does not effect the desktop.

### Proposed resolution

Use a vender specific css attribute and important flag to limit animation to only during the presence of the .collapsing class.
`.navbar-collapse.collapse { -webkit-transition: height 0.0s !important; }`
With this we get to avoid making changes to both the JS and CSS.

**Comment by mdo** [comment]
I wasn't able to produce this, and given the age and limited reporting from others, I'm going to close it out. Please feel free to comment here again with a JS Bin including a reduced test case from the latest `v4-dev` code though and I can revisit.
