### ISSUE TITLE
quickly slide thru intervening slides when skipping ahead to a specific slide

### ISSUE THREAD

**Issue by rrhussain** [twbs/bootstrap#19401]
Hi,
I love bootstrap carousel it has many many good options. My problem is with this carousel is it does move only one slide at one time. let me explain to you what i mean.

if user is on first slide and he wants to go lets say number five slide. Carousel will move only one slide and reach on its clicking destination. What I want carousel should scroll all between slides from 1 to 5. This way user will notify i came here to pass four slides.

I hope it makes sense to you.

I will really really appreciate your help it someone tweak the code.

many thanks

**Comment by mdo** [comment]
No plans to implement this—closing out.
