### ISSUE TITLE
Development of a real-time style sheet implications view

### ISSUE THREAD

**Issue by Pvanhesteren** [twbs/bootstrap#19419]
To allow developers to configure and style the framework more easily to their needs, developers should be allowed to upload their project source code when editing the Bootstrap style sheets. For example, the changes to the Bootstrap style sheets can be done on the left of the screen, whereas the right side would show a preview of the resulting implications to his project by the changes, similar to https://jsfiddle.net/.

Please let me know what you think about this possible improvement.

**Comment by hebbet** [comment]
[bootsnipp](http://bootsnipp.com/) does exactly what you want. 

the bootstrap community is very big and i don't think we need an "official" solution for everything.

**Comment by Pvanhesteren** [comment]
@hebbet, thanks for your reply! This is however not exactly what I had in mind. While bootsnipp is an excellent tool for debugging your own web applications using Bootstrap, it does not really easily allow for easy Bootstrap customization (e.g. altering Bootstrap styles as can be done on the [customize](https://getbootstrap.com/customize/) page) while receiving immediate feedback.

I would love to hear your (and others') thoughts on this!

**Comment by mdo** [comment]
We won't be building this ourselves for the foreseeable future. Thanks for the suggestion, though!
