### ISSUE TITLE
Bootstrap 4 - flexbox

### ISSUE THREAD

**Issue by mmjaeger** [twbs/bootstrap#19417]
Hello

If I set a container as a row using flex box, shouldn't its elements spread across and split the available space without have to give each column a size?

`<div class="row">
<div>column 1</div>
<div>column 2</div>
<div>column 3</div>
<div>column 4</div>
</div>`

if we had something like:

`.row > * { flex: 1 0 auto}`, this should work automagically.

**Comment by cvrebert** [comment]
Already implemented in https://github.com/twbs/bootstrap/pull/19099/files#diff-72dff98341bd060bfffede845cccc29eR32
