### ISSUE TITLE
At specific viewport widths, no breakpoints apply

### ISSUE THREAD

**Issue by twmobius** [twbs/bootstrap#19412]
I am not entirely sure if this is a bug but here goes.

From what I've seen so far v4 works great (I actually last week pushed it into production) but I've noticed that there are some gaps in between the responsive layout where neither the larger nor the directly smaller media applies.

For instance if window width is 1199px we are inbetween xl and lg. Same for 991 we are between lg and md, and so on. 

I am guessing this is because of 
`@return if($next, breakpoint-min($next, $breakpoints) - 0.1, null);` 

Is this expected or an actual issue?

**Comment by cvrebert** [comment]
@twmobius What exact version of Bootstrap are you using? v4.0.0-alpha.2?
Is your browser's page zoom level set to 100% ?

**Comment by cvrebert** [comment]
X-Ref: #17403, #19197

**Comment by twmobius** [comment]
I am on v4.0.0-apha and the browser zoom level is at 100%

**Comment by cvrebert** [comment]
@twmobius Please upgrade to the 2nd alpha (`4.0.0-alpha.2`). You're likely encountering the issue that was fixed by #17403.

**Comment by twmobius** [comment]
@cvrebert Yes you are right. `4.0.0-alpha.2` resolves the issue. Thank you very much!
