### ISSUE TITLE
Building docs with Jekyll doesn't use latest built /dist/ assets

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19429]
1. runned `grunt`
2. got new dist/css/bootstrap.css
3. build docs and serve localhost server via `jekyll serve`
4. when viewing docs on localhost
5. I'm getting diffirent bootstrap.css version from what I have builded with grunt

**Comment by cvrebert** [comment]
You need to run `grunt docs` before Step 3.

**Comment by Mevrael** [comment]
I see, it works now.

Maybe add notes about grunt to section "Running documentation locally" in README.md?

**Comment by mdo** [comment]
Fixed in d8a9a06.
