### ISSUE TITLE
Docs don't mention labels are replaced by tags

### ISSUE THREAD

**Issue by e-oz** [twbs/bootstrap#19421]
Please add info about tags to documentation (and remove part about labels)

**Comment by patrickhlauke** [comment]
already done for alpha.3 https://github.com/twbs/bootstrap/blob/v4-dev/docs/migration.md https://github.com/twbs/bootstrap/blob/v4-dev/docs/components/tag.md - the docs at http://v4-alpha.getbootstrap.com/ reference alpha 2
