### ISSUE TITLE
How to put title and background colour for column in bootstrap

### ISSUE THREAD

**Issue by adhasyuhada** [twbs/bootstrap#19425]
Hi Everyone, anybody help me, how to create this one image below from bootstrap 
![20160306200722](https://cloud.githubusercontent.com/assets/11660402/13562235/cd8c7d3a-e468-11e5-9fa7-c858048043ac.jpg)

**Comment by cvrebert** [comment]
This issue tracker is for bug reports and feature requests. Please use StackOverflow, IRC, or Slack for how-to questions such as this. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
