### ISSUE TITLE
Justified nav example header bug

### ISSUE THREAD

**Issue by adelivuk** [twbs/bootstrap#19428]
Seems to break:

![screen shot 2016-03-07 at 10 46 06](https://cloud.githubusercontent.com/assets/6178877/13565677/db3c6902-e451-11e5-97b8-fa9fd7e73f1f.png)

Tested in Chrome v48.0.2564.116 (64-bit) and v49.0.2623.75 (64-bit), FF v42.0 and v44.0.2

**Comment by cvrebert** [comment]
@adelivuk What version of Bootstrap?

**Comment by adelivuk** [comment]
@cvrebert i'm looking at [v4-alpha.getbootstrap.com/examples/justified-nav/](http://v4-alpha.getbootstrap.com/examples/justified-nav/).

**Comment by cvrebert** [comment]
Duplicate of #17723. Please search more in the future.

**Comment by adelivuk** [comment]
@cvrebert sorry, my bad - searched but with a low quality query.
