### ISSUE TITLE
Tooltip - jQuery data caching issue

### ISSUE THREAD

**Issue by eek** [twbs/bootstrap#19436]
I have a issues with the Bootstrap tooltip, more exactly with their reliance on .data() which caches data attributes.

I'm using tooltips with templates (to add a custom class to the tooltip), the element that create the tooltip is usually changed by a 3rd party script. The problem is that the 3rd party script is not using jQuery's data function, so unfortunately the `.data` function saves the old template in memory and it doesn't know that it changed. If I `destroy` a tooltip and create it again, it will be created with the old template instead of the new.

My solution would have been a workaround, to call the `.removeData()` function from jQuery that will only remove data from jQuery's internal `.data()` cache, and any corresponding data- attributes on the element will not be removed. A later call to `data()` will therefore re-retrieve the value from the data- attribute. 

The problem with this is the fact that on the next tooltip creation, the tooltip will no longer have a template attached to it :|

I have attached a JS Bin Demo: 

http://jsbin.com/suxoyohiyo/1/edit?html,js,output

You guys can uncomment the `.removeData()` line to see the other problem.

My current work-around is to re-add the data value of the template `element.data( 'template', element.attr('data-template') );` 😭

**Comment by Johann-S** [comment]
Hi @eek , why don't try to create again the tooltip via the constructor after destroyed it like this : 
```javascript
$('a').tooltip({
  template : '<div class='tooltip warn' role='tooltip'><div class='tooltip-arrow'></div><div class='tooltip-inner'></div></div>'
})
.attr('title', 'This is a warning')
```
Is it possible for you to update your JSBin to the current alpha ?

**Comment by NirvashPrime** [comment]
I see this hasn't been updated in over a year, is this still an issue?

**Comment by Johann-S** [comment]
We don't know @NirvashPrime the author do not answer and I answered with a workaround, so if you face this issue do not hesitate 👍

**Comment by Johann-S** [comment]
Thanks @eek but is there anything we can do in Bootstrap ?
