### ISSUE TITLE
.form-inline used as mixin in navbar component

### ISSUE THREAD

**Issue by andreiduca** [twbs/bootstrap#19430]
I tried to recompile a custom distribution without the forms components (commented out `@import "forms.less";` and `@import "input-groups.less";` from the main bootstrap less file) and a fatal error occurred due to `.form-inline`class  being used in the `navbar.less` component.

**Bug:**
Class `.form-inline` defined in `less/forms.less` is used in `less/navbar.less` as a mixin. Trying to compile the `bootstrap.less` without the forms components (`forms.less` and `input-groups.less`) triggers a fatal error.

**Steps to reproduce:**
1. Download and npm install the twitter bootstrap master branch.
2. Comment out `forms.less` and `input-groups.less` from the main `bootstrap.less` file.
3. `grunt less` should fail with the following error:

```
>> NameError: .form-inline is undefined in less/navbar.less on line 296, column 3:
>> 295   // Mixin behavior for optimum display
>> 296   .form-inline();
```

**Resolution proposal:**
Consider moving the code from the `.form-inline` class declaration into a mixin in the appropriate file: `less/mixing/forms.less`.
This should break this existing dependency and allow to compile a custom distribution without the forms components (mentioned above).

**Comment by mdo** [comment]
Closing per #19432.
