### ISSUE TITLE
Fix triangle position for dropdown button when the button has extra width

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19444]
Imagine a dropdown button to look like a select, it have a border and some width.

Right now select icon (triangle) is styled with `.dropdown-toggle::after ` and it adds triangle right after the text but not positioning it to block's right border.

When dropdown button (.dropdown-toggle) have a width set, triangle is not aligned to button's right corner like shown in image below:

![bs4_dropdown_toggle](https://cloud.githubusercontent.com/assets/7879528/13604091/cd395736-e549-11e5-8849-e4793931925c.png)

**Comment by mdo** [comment]
If you're customizing the width, you'll have to add more styles to change the text, too. That caret is generated via CSS as an inline-block element. You'll need to move it accordingly for that.

**Comment by Mevrael** [comment]
@mdo @cvrebert 

We now have `.w-100` class. What about changing some styles of dropdown-toggle with w-100 to align triangle icon to the right side when dropdown is full width?
