### ISSUE TITLE
Remove .center-block class from the docs

### ISSUE THREAD

**Issue by RyanZim** [twbs/bootstrap#19443]
`.center-block` was removed in #19102, but the [docs](http://v4-alpha.getbootstrap.com/components/utilities/#center-content) still mention it.

Also this should be added to the [Migration Guide](http://v4-alpha.getbootstrap.com/migration/#utilities).

**Comment by RyanZim** [comment]
It seems that this was updated in [v4-dev docs/](https://github.com/twbs/bootstrap/tree/v4-dev/docs) on GitHub but hasn't been compiled to the gh-pages branch.

**Comment by XhmikosR** [comment]
@cvrebert: shouldn't we close this? I mean, gh-pages is from master so this is expected.

**Comment by cvrebert** [comment]
@XhmikosR There are still references to it in the docs:
```
bootstrap (v4-dev) $ ack center-block docs/
docs/assets/scss/_component-examples.scss
302:  .center-block:not(img) {

docs/content/images.md
63:  <img data-src="holder.js/200x200" class="img-rounded center-block" alt="A generic square placeholder image with rounded corners">
67:<img src="..." class="img-rounded center-block" alt="...">

docs/examples/carousel/index.html
132:          <img class="featurette-image img-fluid center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
144:          <img class="featurette-image img-fluid center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
156:          <img class="featurette-image img-fluid center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">

docs/index.html
90:    <img class="img-fluid center-block" src="{{ site.baseurl }}/assets/img/bs-themes.png" alt="Bootstrap Themes" width="1024" height="388">
```

**Comment by XhmikosR** [comment]
Ah, that's why https://github.com/twbs/bootstrap/issues/19339 happens.

I'll try to have a look later

**Comment by XhmikosR** [comment]
So, how do you want to proceed @cvrebert? `m-x-auto` doesn't set `display: block`. Should I add a custom class now?

**Comment by RyanZim** [comment]
#19343 is a feature request for `.display-block`, `.display-inline`, and `display-inline-block`. Why not include all of them while we're at it?

**Comment by cvrebert** [comment]
@XhmikosR I favor @RyanZim's suggestion.

**Comment by XhmikosR** [comment]
All right, I'll leave it to someone else for the time being.

**Comment by RyanZim** [comment]
Closing due to a0a157db9339b129738face06ef72c10fbe3fbf3.

**Comment by cvrebert** [comment]
<3
