### ISSUE TITLE
text-emphasis-variant mixin links don't darken

### ISSUE THREAD

**Issue by chaosmaster99** [twbs/bootstrap#19446]
#18109 added !important to the text emphasis colors, which is good, but the lack of the same on the hover-focus state prevents the links from changing colors. Not sure if this has been addressed in another branch, but the current v4-dev branch doesn't include anything for it.

It's occurring on the alpha docs site as well:
http://v4-alpha.getbootstrap.com/components/utilities/#contextual-colors-and-backgrounds

I would suggest adding !important to the hover-focus color as well. Unless, of course, there is a reason I'm not aware of for not including it.

**Comment by mdo** [comment]
This was fixed awhile back with #20626.
