### ISSUE TITLE
Flexbox helper classes (and docs)

### ISSUE THREAD

**Issue by DrChills** [twbs/bootstrap#19458]
Are there any current plans to implement helper classes for flexbox i.e.

`.flex-start {align-items: flex-start}`

or even something like:

```
.row-start {
//current row styles
align-items: flex-start
}
```

Seems like there is only flexbox grids in (really awesome by the way) but no (boostrap) way of manipulating flexbox. Doesn't seem completely in-keeping with the bootstrap ethos!

Thanks!

**Comment by cvrebert** [comment]
Duplicate of #18088.
