### ISSUE TITLE
.table-hover on table with nested tables also adds hover style to nested tables 

### ISSUE THREAD

**Issue by Kuzmin** [twbs/bootstrap#19456]
So, I found myself in a situation where I have some nested tables. Feels like I'm back in the 90s again. The code is something like this;

```
<table class="table table-hover">
  <tbody>
    <tr>
      <td>
        <table class="table">
          <tr>...</tr>
          <tr>...</tr>
          <tr>...</tr>
        </table>
      </td>
    </tr>
  </tbody>
</table>
```

And this adds the hover styles to the nested tables. I felt like this might not be the intended behaviour, so I thought I'd file a bug!

**Comment by cvrebert** [comment]
@Kuzmin What version of Bootstrap?

**Comment by Kuzmin** [comment]
It's the Bootstrap Alpha!

Sorry about that, I thought you only had `.table-hover` in Bootstrap 4 :)

**Comment by cvrebert** [comment]
This is intended behavior (though I don't like it either); see the 1st bullet point of http://v4-alpha.getbootstrap.com/migration/#tables

> [...] meaning nested tables will now automatically inherit styles from their parents

**Comment by Kuzmin** [comment]
I see, oh well. Thanks @cvrebert for the prompt responses!

**Comment by websiteduck** [comment]
I ran into this problem using a datepicker in a striped table and thought it was a bug as well.  I'll probably end up adding the > selectors into my _tables.scss.
