### ISSUE TITLE
Link in form-control-feedback can't be clicked in 3.3.5

### ISSUE THREAD

**Issue by YueZhaoDreams** [twbs/bootstrap#19465]
I was using links in form-control-feedback span to perform a save or cancel since 3.1.1. I'm trying to upgrading to 3.3.5, but the behavior for the form-control-feedback changed.

Please refer to the jsfiddle: 
3.1.1-Work https://jsfiddle.net/yuezhao1989/jm7z8gaw/1/
3.3.5-Not work https://jsfiddle.net/yuezhao1989/zL470g8y/1/

I checked, there is a z-index:2 added in 3.3.5. I tried to override it by setting to a higher number, but it doesn't work. Do you have any thoughts to make it work again? 

Thanks!

**Comment by twbs-lmvtfy** [comment]
Hi @YueZhaoDreams!

You appear to have posted a live example (https://fiddle.jshell.net/yuezhao1989/zL470g8y/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 71, column 59 thru line 73, column 35: Start tag ```` a ```` seen but an element of the same type was already open.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @YueZhaoDreams!

You appear to have posted a live example (https://fiddle.jshell.net/yuezhao1989/jm7z8gaw/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 71, column 59 thru line 73, column 35: Start tag ```` a ```` seen but an element of the same type was already open.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
For how-to/personal support questions, please StackOverflow or similar https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

for what it's worth, your input is overlapping the "Cancel" link, which means it's swalling click events.
