### ISSUE TITLE
Split _variables.scss into multiple files by component

### ISSUE THREAD

**Issue by fntneves** [twbs/bootstrap#19478]
Hello everyone,

It would be nice to add default values in each .sass component rather than put everything only in _variables.sass. It would encourage reuse of specific Bootstrap components without the need to add all variables or to define all of them.

I also believe it would simplify the custom Bootstrap build generator.

Obviously, it may not be possible for all components that depend on each other. But it may be discussed.

**Comment by sqal** [comment]
But you can use BS components like so:
```
@import "your_custom_variables";  // override boostrap variables
@import "bootstrap/variables";
@import "bootstrap/dropdown"
```
etc.;

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by fntneves** [comment]
@sqal Yes, I can use them like that.

However, I need to find all variables that are related to each component in huge file `variables` and also other variables which each component's variables depend on.

@sqal @mdo I think that this approach would be great and improve modularity, since every component's variables will be placed in each component's file. "bootstrap/variables", however, still exist to provide current bootstrap's styles.

Thank you.

**Comment by cvrebert** [comment]
Approximate duplicate of #18233
