### ISSUE TITLE
Dropdown not showing after modal injection

### ISSUE THREAD

**Issue by GerardStark** [twbs/bootstrap#19479]
i have an issue where my dropdown menu, witch is in my nav, doesnt show after using and closing a modal, beein either with the close button or clickin in the faded area, it just wont show again, im using links, and the content is showing in the modal via remote injection. pls help

**Comment by RyanZim** [comment]
Please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/) and list your OS and browser so the team can help you quicker. You may want to read about filing a bug the [Contributing Guidlines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by GerardStark** [comment]
i fixed the problem just recently, i was calling the bootstrap.js twice and the modal was closing instantly and that crashed my dropdown. sorry for bothering, awesome framework

**Comment by cvrebert** [comment]
@RyanZim Thanks. <3
