### ISSUE TITLE
Add an example for large documents like user manuals, guides, books, etc.

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#19471]

**Comment by cvrebert** [comment]
I'm not sure how the length of the document would especially affect the usage of Bootstrap, beyond using a table of contents widget.
@bhutaninitin Could you elaborate on what aspects of such an example you envision being distinctive?

**Comment by mdo** [comment]
I'd argue that's our docs, and there's not much to be gained from doing a generic example like that. Going to pass for now, thanks though!
