### ISSUE TITLE
Column Dividers

### ISSUE THREAD

**Issue by robmoggach** [twbs/bootstrap#19480]
I'd like to see column dividers with media breakpoints something like the following:

    $divider-height: 100%;

    @mixin make-column-dividers($breakpoints: $grid-breakpoints) {
        // Common properties for all breakpoints
        %col-divider {
            position: absolute;
            content: " ";
            top: (100% - $divider-height)/2;
            height: $divider-height;
            width: $hr-border-width;
            background-color: $hr-border-color;
        }
        @each $breakpoint in map-keys($breakpoints) {
            .col-#{$breakpoint}-divider-right:before {
                @include media-breakpoint-up($breakpoint) {
                    @extend %col-divider;
                    right: 0;
                }
            }
            .col-#{$breakpoint}-divider-left:before {
                @include media-breakpoint-up($breakpoint) {
                    @extend %col-divider;
                    left: 0;
                }
            }
        }
    }

https://gist.github.com/robmoggach/316f3f2b66c26173c076

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by aflanagan** [comment]
@mdo I'm trying to talk my team out of creating a bunch of helper classes that can add borders to everything, though the use case they all keep coming up with is grid columns. I've looked around to see if there is a canonical approach to this, but I haven't found anything. Any suggestions?
