### ISSUE TITLE
.label :hover background should be a variable

### ISSUE THREAD

**Issue by robmoggach** [twbs/bootstrap#19481]
The label `:hover` attribute needs a little more flexiblity. Currently it's hard coded to `darken($color,10%)` as below:

    @mixin label-variant($color) {
      background-color: $color;
    
      &[href] {
        @include hover-focus {
          background-color: darken($color, 10%);
        }
      }
    }

How about some new variables:

    $label-default-bg-hover:            $gray-light !default;
    $label-primary-bg-hover:            $brand-primary !default;
    $label-success-bg-hover:            $brand-success !default;
    $label-info-bg-hover:               $brand-info !default;
    $label-warning-bg-hover:            $brand-warning !default;
    $label-danger-bg-hover:             $brand-danger !default;

and then a tweaked mixin:

    @mixin label-variant($color-bg, $color-bg-hover) {
      background-color: $color-bg;
    
      &[href] {
        @include hover-focus {
          background-color: $color-bg-hover;
        }
      }
    }

**Comment by michael-hamilton** [comment]
I think the way it currently exists helps lend to consistency across Bootstrap.  The hover states for `.button` are generated in a similar way, by darkening `$color`.

**Comment by roura356a** [comment]
We could set a global percentage for that scenarios. But I'm with michael-hamilton, is all about consistency.

**Comment by mdo** [comment]
Going to punt on adding a variable for that value for now. We do this in a number of spots and I'm unsure where I draw the line yet on variable-ifying them.
