### ISSUE TITLE
Docs refer to make-col-span mixin that no longer exists

### ISSUE THREAD

**Issue by marvin1023** [twbs/bootstrap#19538]
in [grid example usage](http://v4-alpha.getbootstrap.com/layout/grid/#example-usage), the code as follow:
![image](https://cloud.githubusercontent.com/assets/1264591/13743525/34d27fda-ea1d-11e5-92cc-cffb66fa83a9.png)

but in `_grid.scss` only defined the `@mixin make-col` and must has `$size` arg
![image](https://cloud.githubusercontent.com/assets/1264591/13743467/e2f80888-ea1c-11e5-864c-e9c1271b7319.png)

**Comment by leandroruel** [comment]
oh =(

that's true! i see it too

**Comment by mdo** [comment]
Updated the docs to go with the changes coming in #20349—see that PR for more consistent docs for this bit.
