### ISSUE TITLE
Dropdowns carets don't show in simpler navbars on iOS

### ISSUE THREAD

**Issue by ivanhalen** [twbs/bootstrap#19531]
On iOS 9.2.1 (tried on iPhone 5 and 6s), both Safari and Chrome, navbar dropdowns carets appear only in some circumstances
I.E. they appear in a complex menu (first example in http://getbootstrap.com/components/#navbar) but not in a simpler menu (first example in http://getbootstrap.com/javascript/#dropdowns): not sure why, it seems a very strange behavior
Carets still don't appear after opening/closing dropdowns

# Safari, simple menu (carets don't show)
![no-safari](https://cloud.githubusercontent.com/assets/835377/13728937/4f6fa20a-e928-11e5-9cfa-3e8760b2bd19.PNG)

# Safari, complex menu (carets show)
![yes-safari](https://cloud.githubusercontent.com/assets/835377/13728958/85e6ceee-e928-11e5-9b7e-81bb43e4f6bd.PNG)

# Chrome, simple menu (carets don't show)
![no-chrome](https://cloud.githubusercontent.com/assets/835377/13728941/67c4201a-e928-11e5-8dbf-1cf283efd2c1.PNG)

# Chrome, complex menu (carets show)
![yes-chrome](https://cloud.githubusercontent.com/assets/835377/13728960/8ea10c8e-e928-11e5-9286-9674fe092b75.PNG)

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
