### ISSUE TITLE
Enhancement/Feature Request: align-right and align-center generic classes

### ISSUE THREAD

**Issue by edmackowiak** [twbs/bootstrap#19535]
It would be really nice if bootstrap included a generic class to align the contents of a div to the right (a center-align class would be nice as well). I couldn't find a way to do this that worked correctly inside of a column div on Bootstrap 4.0.0.alpha3

Example:

```
.align-right
{
  text-align: right;
}

<div class="align-right">
  Right-Aligned Text
</div>
```

**Comment by fchiumeo** [comment]
It's exist
[Responsive floats](http://v4-alpha.getbootstrap.com/components/utilities/#responsive-floats) 
or
[Text alignment](http://v4-alpha.getbootstrap.com/components/utilities/#text-alignment)

**Comment by cvrebert** [comment]
Closing per @fchiumeo
