### ISSUE TITLE
Add templating methods for Modals

### ISSUE THREAD

**Issue by duvdevani** [twbs/bootstrap#19547]
Is it possible to extend the `$.modal` plugin to add addional helper methods for setting titles and body/contents of a specific modal within it's scope, lets say like this:

```
$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this).getModalInstance();
  // or
  var modal = $.getModalInstance(this);
  // or
  var modal = $(this); // I belive additional methods can be added within this scope of this or any event of the modal component, or maybe prototype-ed...
  
  modal.title('New message to ' + recipient);
  modal.body().find('input').val(recipient);
  // or
  modal.body('Contents of the modal\'s body...');
})
```

In this example, the `title()` and `body()` methods would return the DOM/jQuery object of related elements if no arguments are supplied and in that way we'd avoid finding/typing `.modal-title`' and `.modal-body` classes and might be helpful.

Or via `data-` attributes, or with options object, like, lets say:

```
{
   title: 'Some modal title.',
   body: 'Some awesome body.'
}
```

And those could be catched with methods I've mentioned above.

Same can be applied to the `.modal-footer` as well...

**Comment by cvrebert** [comment]
I think you'd be better served by just using a proper templating library.

**Comment by rafalp** [comment]
TBH this doesn't even look like something that would need view library at all. One can easily implement such feature writing custom jquery function:

    function modalFromAjax(url) {
        $.get(url).success(function(r) {
            $('#modal .modal-header h2').text(r.responseJson.title);
            $('#modal .modal-body').html(r.responseJson.body);
            $('#modal').modal('show')
        });
    }

As for doing it in Bootstrap, I believe any implementation done here would eventually work against existing view libraries/frameworks flow, as sooner or later there'll will be somebody trying to shove React/Ember/Angular into Bootstrap's function and seeking support/api expansion on Bootstrap's part.

**Comment by cvrebert** [comment]
Yeah, we appreciate the suggestion, but we'll pass for now.
