### ISSUE TITLE
Unexpected shadow on top border of text <input> in .input-group

### ISSUE THREAD

**Issue by dotku** [twbs/bootstrap#19542]
It is fine with PC browser, but when it come with iOS safari, there is unexpected shadow on the board.
Any one knows why?

Demo URL: http://cnbayarea.com/yp/

on iOS safari

![image](https://cloud.githubusercontent.com/assets/1519232/13768115/7ef2d45e-ea2f-11e5-8431-30e9364ff918.png)

PC emulator

![image](https://cloud.githubusercontent.com/assets/1519232/13768137/a39fcf46-ea2f-11e5-9913-d566716bf3fd.png)

**Comment by cvrebert** [comment]
@dotku Please make a simplified JS Bin or JS Fiddle that demonstrates the problem.
Also, what version of iOS?

**Comment by ahtee** [comment]
https://jsfiddle.net/4kq9yztg/ 
I see the heavy shadow on the first input field on iOS 9.2

**Comment by twbs-lmvtfy** [comment]
Hi @ahtee!

You appear to have posted a live example (https://fiddle.jshell.net/4kq9yztg/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 60, column 1 thru column 47: Bad value ````  ```` for attribute ```` action ```` on element ```` form ````: Must be non-empty.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
With minor adjustments: https://fiddle.jshell.net/ufdk0cqx/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/ufdk0cqx/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 93, column 9: [E014](https://github.com/twbs/bootlint/wiki/E014): Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s
* line 65, column 11: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* line 73, column 11: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* line 81, column 11: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* line 89, column 11: [E015](https://github.com/twbs/bootlint/wiki/E015): Having multiple add-ons on a single side of an input group is not supported
* line 66, column 11: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`
* line 74, column 11: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`
* line 82, column 11: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`
* line 94, column 11: [E042](https://github.com/twbs/bootlint/wiki/E042): `.form-control` cannot be used on non-textual `<input>`s, such as those whose `type` is: `file`, `checkbox`, `radio`, `range`, `button`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Several of the `input`s are missing `type` attributes, which are required per http://getbootstrap.com/css/#callout-input-needs-type

**Comment by cvrebert** [comment]
After fixing the Bootlint errors: https://fiddle.jshell.net/fmf1y31c/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/fmf1y31c/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 80, column 1: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And fixing that last error: https://fiddle.jshell.net/fmf1y31c/1/

**Comment by cvrebert** [comment]
Unable to reproduce in iOS 9.3 after fixing the errors detected by [Bootlint](https://github.com/twbs/bootlint).
