### ISSUE TITLE
Errant link in v4 docs sidebar

### ISSUE THREAD

**Issue by michael-hamilton** [twbs/bootstrap#19540]
On the  v4 site, in the sidebar under the About section of the sidebar, there is an item titled Accessibility - The item links [here](http://v4-alpha.getbootstrap.com/about/accessibility).
I took a look at the docs in the v4-dev branch and it doesn't look like the Accessibility page exists under About any longer.  Just bringing this up as an issue since this is a broken link on the live site, although seems to be removed from the repository.

<img width="1552" alt="about_accessibility_link" src="https://cloud.githubusercontent.com/assets/9778027/13756629/262f39e4-e9f7-11e5-8fe1-1cbcd1e6e8db.png">

**Comment by cvrebert** [comment]
This was fixed in #18819.
The live site will be updated when the next alpha release ships.
