### ISSUE TITLE
Hiding middle breakpoints with hidden-XX-down and hidden-XX-up

### ISSUE THREAD

**Issue by aburchette** [twbs/bootstrap#19559]
There is a need to show an element at the smallest and largest breakpoints, while hiding the middle three breakpoints. I've searched for a solution and do not see one currently using the utility classes. How would this be done in v4 without my own media queries?

Example:
* XS - visible
* SM - hidden
* MD - hidden
* LG - hidden
* XL - visible

**Comment by michael-hamilton** [comment]
Try applying the classes `.hidden-sm-up` and `.hidden-lg-down` to the element that you want to show at both the smallest and largest break points.

`.hidden-sm-up` will show only on xs devices and `.hidden-lg-down` will only show on xl devices, by combining the two, you will show on xs and xl but not sm, md, or lg

**Comment by fabiospampinato** [comment]
@michael-hamilton I guess @aburchette was looking for a javascript-free solution, if one has to use js for that he/she might as well just use a media query.

@aburchette There's no way of doing that. As stated in the v4 docs:

> These classes don’t attempt to accommodate less common cases where an element’s visibility can’t be expressed as a single contiguous range of viewport breakpoint sizes; you will instead need to use custom CSS in such cases.

**Comment by michael-hamilton** [comment]
That is a javascript free solution.  Using the available classes in v4, there is a solution to his scenarios.
As the v4 docs state 

> You can combine one `.hidden-*-up` class with one `.hidden-*-down class` to show an element only on a given interval of screen sizes.

@aburchette wants to only show something on extra small devices and on extra large devices, but nothing in between.  By combining the class that shows only on _xs_ with the one that shows only on _xl_, you achieve the desired effect.  The markup might look something like this:
    
    <div class="hidden-sm-up hidden-lg-down">
      ...
    </div>

**Comment by cvrebert** [comment]
@fabiospampinato is correct here. As noted in the docs, the `.hidden-*` classes don't support cases where the Visible range consists of multiple disjoint ranges. Combining multiple `.hidden-*` classes can only *decrease* the number of breakpoints where the element is visible. This is one reason why they're phrased as `.hidden-*` and not as `.show-*`.
As noted in the docs that @fabiospampinato quoted, cases like OP's will require custom CSS. (Or you might consider adjusting your design to avoid such a relatively odd pattern in the first place.)
