### ISSUE TITLE
bootstrap model scroll not working in iPhone for PDF

### ISSUE THREAD

**Issue by devshaw** [twbs/bootstrap#19557]
I am using bootstrap model for PDF view. I am using with ifreame and it's working fine in desktop version. But it's not showing scroll in in iPhone. 

How i can fix this?

**Comment by patrickhlauke** [comment]
For how-to/support questions, please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
