### ISSUE TITLE
tabs with .nav-justified have gap in border (and possible solution)

### ISSUE THREAD

**Issue by ChristopherBrix** [twbs/bootstrap#19558]
I noticed that tabs that use `.nav-justified` have a very small gap in their bottom-border (reproducable with the [official example](http://getbootstrap.com/components/#nav-justified)).

This was already reported in #9978, but closed because it shouldn't be visible without zooming. However, I noticed it on two different browsers without zooming, so it's definitely visible.

A pull request (#15145) addressing this was closed, because it'd create a subtle shifting of content.  
I found a different solution (using a `:before`-pseudo element), but this introduces a new minor bug: The bottom border overlays the outline of a focused tab (marked red).

However, since there's already another bug present (the outline doesn't fit the curved background, marked green) I wonder what's more important to the community.

![image](https://cloud.githubusercontent.com/assets/5114411/13818336/c69b1bb0-eb95-11e5-9c1f-0c160b2dfbe5.png)

This is my change to the `navs.less` file (inside `.nav-tabs-justified`): I added
```
// Add the border to the :before pseudo element to avoid a tiny grap
// between the tabs
> li > a {
  border: none !important;
}
> li > a:before {
  content: " ";
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  border-bottom: 1px solid @nav-tabs-justified-link-border-color;
}
> .active > a {
  &:before {
    border-radius: @border-radius-base @border-radius-base 0 0;
    border: 1px solid @nav-tabs-justified-link-border-color;
    border-bottom-width: 0;
  }
}
```

I'll happily provide this change as a pull request if there's any interest, or work on fixing the two bugs with the outline if I get any hint how to do so.

**Comment by ChristopherBrix** [comment]
No one has any opinion on this? Should I go ahead and create a pull request to get feedback?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by sekharz518** [comment]
I their any solution available for this problem in new versions. Well I tried to get space between borders but it is challenging in length depends on the span. If the text is more in span the tab borders is not of equal height.
