### ISSUE TITLE
Navbar not collapsed by default

### ISSUE THREAD

**Issue by stickon1** [twbs/bootstrap#19569]
Hi, I am pretty new to web coding so thank you very much for help. My issue is that when site is displayed on small screens, the menu is by default expanded and it takes two clicks to collapse it back. I wanted the site on mobile devices to behave so at the beginning  the menu is collapsed.
Thank you for your help.
See code below for details.

	<div class="row h_menu">
		<nav class="navbar navbar-default navbar-left" role="navigation">
		    
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div>
		    
		    <div class="nav" id="bs-example-navbar-collapse-1">
		      <ul class="active">
		        <li class="active"><a href="index.html">O ordinaci</a></li>
		        <li class="tutorials">
				<a class="tutorials" href="#">Léka&#345i</a>
				<ul>
					<li><a href="klein.html">MUDr. Tibor Klein</a></li>
		        		<li><a href="svobodova.html">MUDr. Irena Svobodová</a></li>
					<li><a href="kubus.html">MUDr. Petr Kubuš</a></li>
		       			<li><a href="tomek.html">MUDr. Viktor Tomek</a></li>
				</ul>
		        <li class="contact"><a href="galerie.html">Galerie</a></li>
		        <li class="contact"><a href="contact.html">Kontakty</a></li>
		      </ul>
		    </div>
		    
		</nav>
	</div>

**Comment by kubacode** [comment]
There are a number of issues with this code, but changing:
```
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="nav" id="bs-example-navbar-collapse-1">
```
To:

```
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="nav navbar-collapse collapse" id="bs-example-navbar-collapse-1">
```

Will correct the expanding issue you are having.

**Comment by stickon1** [comment]
Thank you worked great, I guess I have to keep practicing :) you are my savior :)

**Comment by patrickhlauke** [comment]
Also, for future reference: help/how-to questions should be sent to StackOverflow or similar - this issue tracker is only here for bugs/problems with Bootstrap itself. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
