### ISSUE TITLE
Customizable inverse bg color

### ISSUE THREAD

**Issue by henwen** [twbs/bootstrap#19563]
Currently, we can give a component an inverse background color using the `.bg-inverse` class. However, `.bg-inverse` is hard set to use `background-color: $gray-dark`. 

Non-gray dark bg's are pretty common, so It'd be great to have a `$background-color-inverse` sass var in _variables.scss that could be referenced directly, and by utility classes like `bg-inverse`.  

Let's give dark colors some love! :rainbow:

**Comment by mdo** [comment]
Done in 64e7230.
