### ISSUE TITLE
Dynamic toggle not working

### ISSUE THREAD

**Issue by avitrakumar** [twbs/bootstrap#19560]
I am trying to append menu from javascript to div(sidebar-content), appending is successful but when ever I try to click (data-toggle) on the menu item its not calling the java script function.
The same code is working(data-toggle) when I directly included the code in div with out appending from JS .Please advice where its getting wrong.

Thanks in advance

<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>

**Comment by patrickhlauke** [comment]
without a minimal test case (using JSFiddle or similar) and further information (what version of Bootstrap you're using, what browser the problem appears in, etc) there's little that can be done...

**Comment by avitrakumar** [comment]
I am trying to append menu from javascript to div(sidebar-content), appending is successful but when ever I try to click (data-toggle) on the menu item its not calling the java script function.
The same code is working(data-toggle) when I directly included the code in div with out appending from JS .Please advice where its getting wrong.

Thanks in advance


<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>

**Comment by avitrakumar** [comment]
<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>

**Comment by avitrakumar** [comment]
`I am trying to append menu from javascript to div(sidebar-content), appending is successful but when ever I try to click (data-toggle) on the menu item its not calling the java script function.
The same code is working(data-toggle) when I directly included the code in div with out appending from JS .Please advice where its getting wrong.

Thanks in advance


<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>`

**Comment by avitrakumar** [comment]
<

<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>

>

**Comment by avitrakumar** [comment]
`I am trying to append menu from javascript to div(sidebar-content), appending is successful but when ever I try to click (data-toggle) on the menu item its not calling the java script function.
The same code is working(data-toggle) when I directly included the code in div with out appending from JS .Please advice where its getting wrong.

Thanks in advance


<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>`

**Comment by avitrakumar** [comment]
`<html>

<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>
</html>`

**Comment by avitrakumar** [comment]
`I am trying to append menu from javascript to div(sidebar-content), appending is successful but when ever I try to click (data-toggle) on the menu item its not calling the java script function.
The same code is working(data-toggle) when I directly included the code in div with out appending from JS .Please advice where its getting wrong.

Thanks in advance


<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>
`

**Comment by avitrakumar** [comment]
added code

`
<div class="sidebar-content">

</div>

<script>
 var menu1=' <div class="side-content"><ul class="nav-main json-menu">';
	         	  menu1=menu1+'<li style="background:#ffc20a;margin-top:-14px; margin-left:-10px"><a class="h5 text-white" href="index.html"><img src="responsive/assets/img/logo.png"/></a></li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="si si-home"></i><span class="sidebar-mini-hide">HOME</span></a> </li>';
	         	  menu1=menu1+'<li> <a class="nav-submenu" data-toggle="nav-submenu" href="#"><i class="fa fa-search-plus"></i><span class="sidebar-mini-hide">PARTS & SEARCH</span></a>';
	         	  menu1=menu1+'<ul><li><a href="#">Basic Search</a> </li><li><a href="#">Mutiple Parts Upload</a></li></ul></li>  </ul></div>';
	         	   alert(menu1);
                
	               $('.sidebar-content').append(menu1);

jQuery('[data-toggle="nav-submenu"]').on('click', function(e){
        	alert(1);
  
});
</script>`

**Comment by patrickhlauke** [comment]
for help/how-to questions (rather than reports about bugs in Bootstrap itself), please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
