### ISSUE TITLE
Tables buggy in Firefox (Missing Borders)

### ISSUE THREAD

**Issue by ibot3** [twbs/bootstrap#19573]
Table borders are randomly missing in firefox. 

http://prntscr.com/ahb6el

http://prntscr.com/ahb6s9

Please fix it or tell me how to fix.

**Comment by cvrebert** [comment]
@ibot3 We can't debug screenshots. Please post a JS Fiddle or JS Bin that demonstrates the problem.

**Comment by ibot3** [comment]
Sorry, seems to be a problem related to c9.io it's working on my webserver and JSFiddle.
