### ISSUE TITLE
Bootstrap accordion weird jumping in safari

### ISSUE THREAD

**Issue by harishajdarevic** [twbs/bootstrap#19576]
I have made bootstrap accordion for my website. Everything works perfect except in Safari.

I'm trying to figure out what's wrong.

If you are running Safari you can see the problem [here](https://weltenbruecken.com/)

**Comment by cvrebert** [comment]
@harishajdarevic Please make a simplified JS Bin or JS Fiddle that demonstrates the problem.

**Comment by harishajdarevic** [comment]
@cvrebert Hi, ok here is simplified https://jsfiddle.net/Hajdarevic89/L8jd6f27/

But on that fiddle it has a little bit different jumping behavior. On the webpage is much worst on Safari. 

So, it would be good if you can also take a look on webpage also.

Thanks

**Comment by twbs-lmvtfy** [comment]
Hi @harishajdarevic!

You appear to have posted a live example (https://fiddle.jshell.net/Hajdarevic89/L8jd6f27/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 89, column 3 thru column 143: Duplicate ID ```` accordion ````.
* line 125, column 4 thru column 9: End tag ```` div ```` seen, but there were open elements.
* line 89, column 3 thru column 143: Unclosed element ```` article ````.
* line 126, column 3 thru column 12: Stray end tag ```` article ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@harishajdarevic Please fix the errors identified by @twbs-lmvtfy.

**Comment by harishajdarevic** [comment]
Fixed! 

https://fiddle.jshell.net/L8jd6f27/2/

**Comment by twbs-lmvtfy** [comment]
Hi @harishajdarevic!

You appear to have posted a live example (https://fiddle.jshell.net/L8jd6f27/2/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 129, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 71, column 3 thru column 73: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by licatajustin** [comment]
@harishajdarevic, this happens when the selector, `<div class="collapse">` has padding on it. In your case, the class `.panel-body` is adding `15px` of padding to the collapse selector. Just nest the `.panel-body` class within `<div class="collapse">` selector like so:

```html
<div id="collapse1" class="collapse">
  <div class="panel-body">
    <div class="panel-inner main">
      <p class="uk-article-lead">...</p>
    </div>
  </div>
</div>
````

[Here](https://fiddle.jshell.net/L8jd6f27/4/) is an updated fiddle.

**Comment by twbs-lmvtfy** [comment]
Hi @licatajustin!

You appear to have posted a live example (https://fiddle.jshell.net/L8jd6f27/4/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 134, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 71, column 3 thru column 73: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@harishajdarevic Your fiddle is using very old Bootstrap v3.0.0. Your website is using very old Bootstrap v3.0.1.
Please upgrade to current Bootstrap v3.3.6.
If the problem persists after upgrading, let me know and I'll reopen the issue.
