### ISSUE TITLE
Nested Rows/Cols Require encompassing widths

### ISSUE THREAD

**Issue by defsdoor** [twbs/bootstrap#19587]
It's it intentional that it is necessary to specify fully encompassing column widths on nested rows ?

For example
```
<div class="row">
  <div class="col-sm-6">
    Hello 1
    <div class="row">
      <div class="col-sm-6">
        Hello 2
      </div>
  </div>
  <div class="col-sm-6">
    Hello 3
  </div>
</div>
```

The second hello begins off the left of the page when the browser width is smaller than sm.
It can be dragged back by specifying col-xs-12 additionally.

**Comment by defsdoor** [comment]
Sorry - this is v4

**Comment by cvrebert** [comment]
@defsdoor Are you using the Flexbox grid or the default `float`-based grid?

**Comment by defsdoor** [comment]
This with with 

$enable-flex: false;

Just tried it with $enable-flex: true and it exhibits the same results

**Comment by cvrebert** [comment]
@defsdoor By "fully encompassing column widths", you mean explicit `col-xs-*` classes, right?

**Comment by defsdoor** [comment]
yes  - class="col-sm-6 col-xs-12" works when smaller than sm

just class="col-sm-6" on a nested row/col is 15px off to the left

**Comment by defsdoor** [comment]
Seems to be because the second row also offsets -15px, thereby taking the content off the page.

```
<div class="row">
  <div class="col-sm-6">
    hello
    <div class="row">
      <div class="col-sm-6">
        hello
        <div class="row">
          <div class="col-sm-6"> hello </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

Results in - 
![screenshot from 2016-03-23 09-33-28](https://cloud.githubusercontent.com/assets/57616/13981184/6b74270a-f0da-11e5-9b0a-daf62d4770a9.png)
![screenshot from 2016-03-23 09-33-45](https://cloud.githubusercontent.com/assets/57616/13981193/758a63c6-f0da-11e5-8e7f-a072cf6b0dbe.png)

greater than sm and less than sm respectively

**Comment by defsdoor** [comment]
does there need to be an ever constant padding-left: 15px on all col-* regardless of media size matching ?

**Comment by defsdoor** [comment]
I notice that bootstrap 3 has permanent padding for all col-* defined.

Is this needed also ?

```
.col-xs-1,.col-xs-2,.col-xs-3,.col-xs-4,.col-xs-5,.col-xs-6,.col-xs-7,.col-xs-8,.col-xs-9,.col-xs-10,.col-xs-11,.col-xs-12,.col-sm-1,.col-sm-2,.col-sm-3,.col-sm-4,.col-sm-5,.col-sm-6,.col-sm-7,.col-sm-8,.col-sm-9,.col-sm-10,.col-sm-11,.col-sm-12,.col-md-1,.col-md-2,.col-md-3,.col-md-4,.col-md-5,.col-md-6,.col-md-7,.col-md-8,.col-md-9,.col-md-10,.col-md-11,.col-md-12,.col-lg-1,.col-lg-2,.col-lg-3,.col-lg-4,.col-lg-5,.col-lg-6,.col-lg-7,.col-lg-8,.col-lg-9,.col-lg-10,.col-lg-11,.col-lg-12,.col-xl-1,.col-xl-2,.col-xl-3,.col-xl-4,.col-xl-5,.col-xl-6,.col-xl-7,.col-xl-8,.col-xl-9,.col-xl-10,.col-xl-11,.col-xl-12 {
	position:relative;
	min-height:1px;
	padding-left:0.9375rem;
	padding-right:0.9375rem
}
```

**Comment by mdo** [comment]
You're missing a `</div>` to close your nested row. That'll fix your rendering issues.
