### ISSUE TITLE
Popover's methods

### ISSUE THREAD

**Issue by cristiancota** [twbs/bootstrap#19588]
When you use the manual methods from the docs http://v4-alpha.getbootstrap.com/components/popovers/#methods they have unexpected behavior, i.e. if you have a button that show a popover and use the hide method via js, when you try to show your popover again when you click the button, the first click doesn't work, until the second

**EDIT**

Here is the example: https://jsfiddle.net/mdcew1bd/7/

**Comment by hebbet** [comment]
please provide an example as noted in [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by cvrebert** [comment]
Duplicate of #16732.
