### ISSUE TITLE
Build error:  No compatible version found: read-json@0.1.0

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#19597]
I'm trying to build Bootstrap 4 from source (v4-dev) on Ubuntu. I've installed the latest node / npm versions:

    npm -v
    3.8.2

    node -v
    v5.9.0

    git clone git@github.com:twbs/bootstrap.git
    cd bootstrap
    git checkout v4-dev
    npm install

This ends up going wrong with the following error (full npm-debug.log attached). I used to be able to build Bootstrap 4, but not anymore it seems. 

    npm ERR! No compatible version found: read-json@0.1.0
    npm ERR! Valid install targets:
    npm ERR! 1.0.3, 1.0.2, 1.0.1

[npm-debug.log.zip](https://github.com/twbs/bootstrap/files/186332/npm-debug.log.zip)

I believe that the problem is caused by the dev dependency npm-shrinkwrap, as I get the same error when trying to install it independently

    npm install npm-shrinkwrap

See issue https://github.com/uber/npm-shrinkwrap/issues/103 in their repository.

**Comment by bmatusiak** [comment]
https://github.com/twbs/bootstrap/issues/19596, Dupe

**Comment by arechsteiner** [comment]
Hm, I could swear I checked the issues before posting. Then again, it took me more than 15 minutes to post, because I started drilling down the packages and try find the exact root of the issue, which I mentioned in my last line.

**Comment by bmatusiak** [comment]
i hear ya... i just wanted to link the issues together

**Comment by bmatusiak** [comment]
https://github.com/twbs/bootstrap/issues/19596#issuecomment-200503219

here is a temp fix that i used
