### ISSUE TITLE
input-group-btn add on gets wrong height for icon, correct height if text value instead.

### ISSUE THREAD

**Issue by areim3r** [twbs/bootstrap#19598]
Im trying to add an input with multiple add ons as shown [here](http://getbootstrap.com/components/#input-groups-buttons-multiple). The issue is when I try to use an icon, even just copying the code directly from the docs, the icon is always has the wrong height / padding unless there is some kind of text value inside. To demonstrate, here is the code from the docs I'm using and a screenshot for what gets rendered (className because react):

![wrong-height-code](https://cloud.githubusercontent.com/assets/8661521/13993268/065c0f74-f0f6-11e5-8057-6fb5725af488.png)

![wrong-height](https://cloud.githubusercontent.com/assets/8661521/13993263/ff12ba60-f0f5-11e5-9885-be4f40b04016.png)

and for comparison, here is what happens when I add an &nbsp; inside the button with the icon:

![right-height-code](https://cloud.githubusercontent.com/assets/8661521/13993286/1c8b1060-f0f6-11e5-93ae-1ab2bd27cd41.png)

![correct-height](https://cloud.githubusercontent.com/assets/8661521/13993293/1f92a566-f0f6-11e5-8c00-9cee20bf8b78.png)

I don't think anything else is affecting the elements because looking in the console, the only styles I see being applied to any of the related elements are bootstrap css and normalize css. Also, this seems to happen when I use any icon whether its glyphicon or font awesome.

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle that demonstrates the problem and doesn't involve React.
Also, what OS and browser are you using?

**Comment by areim3r** [comment]
I could not replicate via JSFiddle, it works as expected there. However, I still get the same result even after making an MVP html file that only sources Bootstrap and Font-Awesome. The full contents of the MVP file are as follows: 

![mvp-code](https://cloud.githubusercontent.com/assets/8661521/14119011/2acf7b84-f5ba-11e5-9496-f0bdc451502d.png)

and in my browser this is what it renders:

- chrome
![chrome](https://cloud.githubusercontent.com/assets/8661521/14119095/8b29645e-f5ba-11e5-9093-03f71e51f7a1.png)

- firefox
![firefox](https://cloud.githubusercontent.com/assets/8661521/14119098/913cb1e8-f5ba-11e5-84d2-6f86065e3343.png)

- safari
![safari](https://cloud.githubusercontent.com/assets/8661521/14119104/98acd930-f5ba-11e5-824b-7de44e3a522e.png)

Note that this happens whether I use glyphicon or fontawesome, either way the top and bottom margin are always misaligned unless I add some kind of text value such as &nbsp; on either side of the icon element.

Im running OSX 10.11.3

Also worth noting is that the Bootstrap documentation renders fine in my browsers, and I've used bootstrap in a number of projects before with no issue, so I'm a bit confused where the disconnect is here.

**Comment by cvrebert** [comment]
Please post your MVP HTML file as text instead of a screenshot of text.

**Comment by areim3r** [comment]
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>
    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <input type="search" class="form-control" placeholder="" aria-controls="DataTables_Table_0">
          <span class="input-group-btn"><button class="btn btn-default" type="button"><span class="glyphicon glyphicon-ok"></span></button></span>
        </div>
      </div>
    </div>
  </body>
</html>
```

**Comment by cvrebert** [comment]
JS Bin of the MVP: http://jsbin.com/hopale/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/hopale/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
The Bin renders correctly for me in Safari, Firefox, and Chrome on OS X El Capitan.
Closing as not reproducible.

**Comment by guillaumevincent** [comment]
your are missing the `<!DOCTYPE html>`

here the JS BIN with the bug : 

http://jsbin.com/riledimule/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @guillaumevincent!

You appear to have posted a live example (http://jsbin.com/riledimule/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 1, column 1 thru column 6: Start tag seen without seeing a doctype first. Expected ```` <!DOCTYPE html> ````.
* line 25, column 3 thru column 9: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 9, column 5 thru column 27: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
