### ISSUE TITLE
Flexbox grid column with content that's too wide causes the column to line-wrap

### ISSUE THREAD

**Issue by lsapan** [twbs/bootstrap#19590]
I apologize if this is a duplicate, I looked through a ton of issues and (very) surprisingly didn't see any describing these behaviors.

I've been using Bootstrap v4 alpha 2 for awhile now and I keep running into these two issues:

~~1) Using a class like .col-md-4 doesn't switch to full-width on `xs` and `sm` size devices. To compensate, I've been setting classes like this: `col-xs-12 col-md-4`. Not a super huge deal, but strange. Is this intentional moving forward?~~

2) Here's the bigger issue. If the content within the column is too wide to fit, the column moves down onto the next line. I really _really_ need it to stay on the same line. Again, is this intentional moving forward? If so, is there a way to force the row to not allow this?

Thanks for all the hard work on v4 by the way! Other than this it's awesome.

**Comment by cvrebert** [comment]
@lsapan Are you using the Flexbox grid or the default `float`-based grid?

**Comment by lsapan** [comment]
@cvrebert Yes, my apologies that's the first time I've seen that documentation. Well that certainly explains the first issue, but it doesn't mention anything about the overflowing issue.

**Comment by cvrebert** [comment]
@lsapan 
(a) Which browser are you using?
(b) Do you have a JS Bin or JS Fiddle demo of (2) handy?

> 2) Here's the bigger issue. If the content within the column is too wide to fit [...]

Currently, provisionally, we're deeming that to be a bug in the content itself; see https://github.com/twbs/bootstrap/issues/19123#issuecomment-181317487

**Comment by lsapan** [comment]
@cvrebert thanks for the replies. I've been playing around with the two modes and it seems like the same situation as #19123.

That said, in my content example, it was based on one of the words a user typed being too long, forcing the width of the content to be too wide. I would recommend at the very least adding a note of this behavior to the flexbox documentation. It's a pretty important consideration. Sure, having text overflow a column is not beautiful, but sometimes it looks better than the alternative.

Unfortunately, this means falling back to the float based grid for me. :disappointed_relieved:
