### ISSUE TITLE
Open a modal window in a modal window body jumps to the left

### ISSUE THREAD

**Issue by drtvader** [twbs/bootstrap#19608]
Hello! Why when opening modal in modal, there is a shift of all the site of the body? What could be the reason? 
I use this code, but it only works for the first modal
Thanks!
```
$(document).ready(function(){
    $(window).load(function(){
        var oldSSB = $.fn.modal.Constructor.prototype.setScrollbar;
        $.fn.modal.Constructor.prototype.setScrollbar = function () 
        {
            oldSSB.apply(this);
            if(this.bodyIsOverflowing && this.scrollbarWidth) 
            {
                $('.minimized-header,.b-filter--floating').css('padding-right', this.scrollbarWidth);
            }       
        }

        var oldRSB = $.fn.modal.Constructor.prototype.resetScrollbar;
        $.fn.modal.Constructor.prototype.resetScrollbar = function () 
        {
            oldRSB.apply(this);
            $('.minimized-header,.b-filter--floating').css('padding-right', '');
        }
    });
});
```

**Comment by patrickhlauke** [comment]
Nested/multiple modals are not officially supported in Bootstrap, I'm afraid. I'd suggest asking for specific help/support in how to get this working on StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by cvrebert** [comment]
> Nested/multiple modals are not officially supported in Bootstrap

which is noted in the docs at http://getbootstrap.com/javascript/#callout-stacked-modals
