### ISSUE TITLE
Update normalize.css to 4.0.0

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#19613]
Not sure what's the case with v4. I haven't followed the changes closely regarding reboot.

**Comment by hebbet** [comment]
for v4 #19575

**Comment by cvrebert** [comment]
Bumping the major implies that this broke backward compatibility, so perhaps we shouldn't pursue this for v3.

**Comment by XhmikosR** [comment]
I haven't checked all the changes so after I do I will let you know.

**Comment by XhmikosR** [comment]
@cvrebert: I've made #19620. The changes are affecting us in a breaking way, at least regarding the `table` styling which we can just add to our styles.
