### ISSUE TITLE
<input> border sometimes overlaps button border in .input-group

### ISSUE THREAD

**Issue by kleverigheid** [twbs/bootstrap#19624]
The result depends on the value of the buttons. It is very noticeable when using `btn-*-outline`.

<img width="633" alt="screenshot 2016-03-26 00 33 12" src="https://cloud.githubusercontent.com/assets/10009551/14055494/327b1bb2-f2eb-11e5-9461-469be50dd008.png">

JSFiddle – https://jsfiddle.net/kleverigheid/3onsbgad/.

**Comment by twbs-lmvtfy** [comment]
Hi @kleverigheid!

You appear to have posted a live example (https://fiddle.jshell.net/kleverigheid/3onsbgad/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 69, column 7: [E033](https://github.com/twbs/bootlint/wiki/E033): `.alert` with dismiss button must have class `.alert-dismissible`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Unable to reproduce in OS X Chrome with the current code in the bleeding-edge `v4-dev` branch.
