### ISSUE TITLE
Clearfix Reset Not Working Properly in Bootstrap 4.0.0 Alpha

### ISSUE THREAD

**Issue by VishalSubramanyam** [twbs/bootstrap#19622]
I was trying the grid examples given on Bootstrap page when I found that the clearfix reset pulled my grid into an "xs" setting even when the browser window was resized to "lg". Below are a few screenshots with the clearfix set and browser maximized to full width and height showing the difference between Bootstrap 3 and Bootstrap 4:
Bootstrap 3:
![bstrap-bug-03](https://cloud.githubusercontent.com/assets/9930597/14049119/1b009ee2-f2d9-11e5-8d8b-58ac0eea430f.png)
Bootstrap 4.0.0 alpha:
![bstrap-bug-04](https://cloud.githubusercontent.com/assets/9930597/14049132/386da678-f2d9-11e5-96a3-aeb67f1e49e1.png)

**Comment by RyanZim** [comment]
Could you post a JSBin/JSFiddle of this?
Also, what browser and OS are you using?

**Comment by VishalSubramanyam** [comment]
Here is the JSFiddle with Bootstrap 4 attached:
https://jsfiddle.net/vishal_subramanyam/cspveff6/

I am using Chrome on Windows 10.

**Comment by twbs-lmvtfy** [comment]
Hi @VishalSubramanyam!

You appear to have posted a live example (https://fiddle.jshell.net/vishal_subramanyam/cspveff6/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 54, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by VishalSubramanyam** [comment]
This is my JSFiddle with Bootstrap 4 attached:
https://jsfiddle.net/vishal_subramanyam/cspveff6/

I am running Chrome on Windows 10.

**Comment by twbs-lmvtfy** [comment]
Hi @VishalSubramanyam!

You appear to have posted a live example (https://fiddle.jshell.net/vishal_subramanyam/cspveff6/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 54, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by VishalSubramanyam** [comment]
This is my JSFiddle with Bootstrap 4 attached:
https://jsbin.com/pehacaresa/edit?html,output
I am using Chrome on Windows 10.

**Comment by twbs-lmvtfy** [comment]
Hi @VishalSubramanyam!

You appear to have posted a live example (https://jsbin.com/pehacaresa/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 11, column 1: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by VishalSubramanyam** [comment]
This is the JSBin with Bootstrap:
https://jsbin.com/pehacaresa/1/edit?html,output

I am running Chrome on Windows 10

**Comment by twbs-lmvtfy** [comment]
Hi @VishalSubramanyam!

You appear to have posted a live example (https://jsbin.com/pehacaresa/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 11, column 1: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by VishalSubramanyam** [comment]
This is my JSBin after revision with Bootstrap 4:
https://jsbin.com/jajirudepu/1/edit?html,output

I am using Chrome on Windows 10

**Comment by RyanZim** [comment]
`.visible-xs` was removed in v4. See http://v4-alpha.getbootstrap.com/migration/#responsive-utilities. You should use a `.hidden-*-up` and/or `.hidden-*-down` class instead. These classes hide the element at the given breakpoint and all sizes "up" (larger) or "down" (smaller).

**Note: v4 adds an new breakpoint.** Therefore, you should use **one breakpoint larger** than you would in v3 for all grid sizing.

**Comment by cvrebert** [comment]
Closing per @RyanZim. Let me know if there's something I'm overlooking.
