### ISSUE TITLE
Active tab in .nav-tabs sometimes still shows bottom border on Firefox in Linux & OS X

### ISSUE THREAD

**Issue by adriaanzon** [twbs/bootstrap#19626]
When I use badges within .nav-tabs, list items with an .active class still have a visible bottom border. This problem only occurs to me when using Firefox on Linux, with Bootstrap 3.3.5 and 3.3.6. Chrome displays it just fine.

Here is a JSBin, and a screenshot of how it looks on my end.

http://jsbin.com/qekubi/1/edit?html,css,output

![2016-03-26-182455_760x185_scrot](https://cloud.githubusercontent.com/assets/4326420/14061445/7d654162-f380-11e5-800c-ac5eb749da8a.png)

I fixed it by reducing the padding-top and padding-bottom of the badge by 1px.

**Comment by twbs-lmvtfy** [comment]
Hi @adriaanzon!

You appear to have posted a live example (http://jsbin.com/mokizeyalu/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by adriaanzon** [comment]
JSBin with the meta tag http://jsbin.com/yifubeludu/1/edit?html,output

**Comment by cvrebert** [comment]
Confirmed in OS X Firefox 47. Doesn't repro in Safari or Chrome.

**Comment by cvrebert** [comment]
Also reproduces in OS X Firefox 45.0.
Doesn't repro in Win10 Firefox 45.0.

**Comment by cvrebert** [comment]
Still reproduces in bleeding-edge v3 `master` branch.

**Comment by cvrebert** [comment]
Visually similar but doesn't seem causally related: #18228

**Comment by cvrebert** [comment]
Filed Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1259972
