### ISSUE TITLE
Dismiss button in alert is not centered vertically on OS X Chrome+Safari

### ISSUE THREAD

**Issue by kleverigheid** [twbs/bootstrap#19621]
Tested in Safari and Chrome.

<img width="636" alt="screenshot 2016-03-25 16 01 43" src="https://cloud.githubusercontent.com/assets/10009551/14045434/eaab8e5e-f2a2-11e5-9ad0-131ea35920dc.png">

```
<div class="alert alert-success" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  Feedback successfully sent. We will response you as soon as possible.
</div>
```

**Comment by hebbet** [comment]
what version of bootstrap do you use?

can you provide a jsfiddle or similar?

**Comment by kleverigheid** [comment]
4.0.0.alpha.2

**Comment by jacob-on-github** [comment]
It is working correctly for me in your fiddle. Using Chrome. 
![capture](https://cloud.githubusercontent.com/assets/11466782/14049880/11217502-f286-11e5-8959-c2e3d92da170.PNG)

**Comment by kleverigheid** [comment]
![screenshot 2016-03-25 19 42 49](https://cloud.githubusercontent.com/assets/10009551/14050051/e9fbf22c-f2c1-11e5-8671-ea1020fb04df.png)
<img width="252" alt="screenshot 2016-03-25 19 43 27" src="https://cloud.githubusercontent.com/assets/10009551/14050052/eb64b112-f2c1-11e5-8583-c6d541e54999.png">

Also tried use Chrome and I think that the problem is related to OS X.

**Comment by RyanZim** [comment]
Works fine for me in Firefox, Chrome, and Safari on Windows.

**Comment by cvrebert** [comment]
As stated in the docs, dismissible alerts **must** use the `.alert-dismissible` class.

**Comment by cvrebert** [comment]
Unable to reproduce in either browser on OS X with the correct markup.
Docs:
* http://v4-alpha.getbootstrap.com/components/alerts/#dismissing
* https://github.com/twbs/bootlint/wiki/E033

**Comment by mikedensem** [comment]
I am currently out of the office and due back Wed. 30th.
I will be collecting emails and responding when I can.

For urgent issues please leave a message on 021 895 393

Mike
