### ISSUE TITLE
.table-bordered with grid columns and differing cell/column heights gives incorrect borders

### ISSUE THREAD

**Issue by timb07** [twbs/bootstrap#19625]
A table with .table-bordered and columns sized with .col-md-\* results in incorrect cell borders, particularly when cell contents are of different heights. See [this example](http://www.bootply.com/k5CfpiegA2), which shows a table without column sizing, one with sizing displaying the problem, and one with the problem fixed.

Applying "float: inherit" to the td elements fixes the issue.

(This assumes that using grids to size table columns (as described [here](http://donnapeplinskie.com/using-tables-with-bootstrap-grids/) is in fact a supported feature of Bootstrap 4.)

**Comment by cvrebert** [comment]
JS Bin with bleeding-edge v4: http://jsbin.com/vuyivutuja/edit?html,output

**Comment by cvrebert** [comment]
This would seem to require automatic equal-height columns, which aren't a feature of the non-Flexbox grid. So I would lean towards "not supported".
CC: @mdo to confirm/deny

**Comment by mdo** [comment]
Yup, not supported.
