### ISSUE TITLE
iOS doesn't show :active or :hover state for <a> btns

### ISSUE THREAD

**Issue by djmtype** [twbs/bootstrap#19623]
I noticed after updating from Bootstrap v3.2.x to v3.3.6, pressing on a button with an `href` no longer shows :active or :hover state for a split second, giving the user some visual cue that the button has been pressed. Furthermore, I'm seeing the button's :focus state when navigating back to the previous page – which can totally be confusing to the user. 

By example, visit the the [http://getbootstrap.com](http://getbootstrap.com) page from iOS Safari or Chrome on iOS and press the _Download Boostrap_ button. [https://cloudup.com/iBoqJWG-UHw](https://cloudup.com/iBoqJWG-UHw)

Also, pressing on an element with a tooltip, the tooltip doesn't always disappear when tapping out of focus. Sometimes it can take up to 10 taps before the tooltip disappears. Unfortunately, the amount of taps varies before the tooltip disappears. On my site where only one tooltip was present, the tooltip never disappeared when out of focus. I recorded a similar action on Bootstrap's own site. [https://cloudup.com/iZHYpS_Tynh](https://cloudup.com/iZHYpS_Tynh)

Is this the norm?

Although, my demos are recorded on the iOS simulator, the same action occurs on the real device.

**Comment by cvrebert** [comment]
See #16028 regarding the tooltip issue.

**Comment by cvrebert** [comment]
Regarding the :focus thing, see http://getbootstrap.com/getting-started/#support-sticky-hover-mobile

**Comment by cvrebert** [comment]
> I noticed after updating from Bootstrap v3.2.x to v3.3.6, pressing on a button with an href no longer shows :active or :hover state for a split second

Would you be able to do some more testing to determine in exactly which Bootstrap version the behavior change occurred?
Also, what version of iOS are you using?

**Comment by djmtype** [comment]
@cvrebert I can't seem to repeat the behavior I had experienced on older builds of iOS Safari and Chrome. I thought Bootstrap v3.2.x handled button and link states differently than v3.3.6. After further testing, I realized this isn't the case. 

What use to happen: when a button (with href) or link was pressed, the `:hover` state appeared for a brief moment. Could it be he latest iOS Safari no longer has that 300ms lag which inadvertently showed this state? Honestly, I can't tell and haven't added any script like fastclick.js to my project. In any case, it doesn't appear to be a Bootstrap-specific cause.

**Comment by djmtype** [comment]
BTW, if I add in fastclick.js, on touch devices, the `:active` state is shown if applicable, (otherwise, `:hover` is shown). This is the desired effect I was hoping for – some visual cue that an action is taking place.

**Comment by cvrebert** [comment]
> Could it be the latest iOS Safari no longer has that 300ms lag which inadvertently showed this state?

Yes: https://webkit.org/blog/5610/more-responsive-tapping-on-ios/

**Comment by DerZyklop** [comment]
@cvrebert the link you posted about the ':focus thing' is outdated. I assume you meant this: https://getbootstrap.com/docs/4.4/getting-started/browsers-devices/#sticky-hoverfocus-on-ios

Bootstrap 5 has this issue, too, but the Bootstrap 5 docs do not mention it.
