### ISSUE TITLE
Add class for center-aligned blockquotes

### ISSUE THREAD

**Issue by surjithctly** [twbs/bootstrap#19637]
If you see majority of websites, The quotes / testimonials are center aligned. So its good to make a center-aligned blockquote. 

``` html
<blockquote class="blockquote blockquote-center">
  <p class="m-b-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
  <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
</blockquote>
```

Optional: Add an Image Avatar at top in the Docs using existing classes?

PS: Is that search button on the documentation actually works? I did a search for "blockquote" but returned no result found :(

~Surjith

**Comment by RyanZim** [comment]
What styling did you have in mind for `.blockquote-center`?

The search box in the v4-alpha docs only searches the page names, not their contents.

**Comment by surjithctly** [comment]
Something like this:
![testimonials](https://cloud.githubusercontent.com/assets/1884712/14114839/58b86a7e-f5f6-11e5-85ed-ed08b9965dfe.png)

It adds `text-align: center`, and removes the grey bar.

**Comment by jonahallibone** [comment]
https://github.com/twbs/bootstrap/pull/19819

**Comment by mdo** [comment]
This was made possible with #22949.
