### ISSUE TITLE
<audio> width not responsive

### ISSUE THREAD

**Issue by kongebra** [twbs/bootstrap#19634]
Title says its all. There is nothing doing anything with the audio-width.

My own fix is:
`audio {
    width: 100%;
}`

**Comment by cvrebert** [comment]
Sorry, but the title doesn't say enough. Please post a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by cvrebert** [comment]
Ah, presumably you mean `<audio controls>`.

**Comment by kongebra** [comment]
https://jsfiddle.net/juhe9xpj/1/

**Comment by twbs-lmvtfy** [comment]
Hi @kongebra!

You appear to have posted a live example (https://fiddle.jshell.net/juhe9xpj/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 60, column 3: [E027](https://github.com/twbs/bootlint/wiki/E027): `.table-responsive` is supposed to be used on the table's parent wrapper `<div>`, not on the table itself

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by kongebra** [comment]
https://jsfiddle.net/juhe9xpj/2/

**Comment by RyanZim** [comment]
You nearly always want `<audio controls>` to be 100% width, however, there might be a few cases this would be undesirable. For example, when using it at the end of a line of text:
```
<p>Listen: <audio controls src="somefile.mp3"></p>
```
`width: 100%;` would cause it to wrap to a new line.

I suggest we set `audio { max-width: 100%; }` and use `.w-100` (pending in PR #19234) for the `width: 100%;` behavior. This would allow the `audio` element to render as usual in most cases, but would keep the element from running off the screen or overlapping other content.

**Comment by cvrebert** [comment]
Probably it should be entirely opt-in, to avoid conflicts with other libraries (similar to how `<input>`s aren't `width:100%;` by default and you need to use `.form-control` explicitly).
Since it doesn't seem like a "better" `<audio>` requires any further styling beyond tweaking its width, I agree that `.w-100` seems sufficient. Adding something like `.audio` doesn't seem necessary.

**Comment by RyanZim** [comment]
@cvrebert I agree that an `.audio` class is unnecessary, however, I still think setting the `<audio>` element to `max-width: 100%;` would be beneficial. I can't think of any cases where this would cause a conflict.

If you decide against setting a default for `<audio>` in favor of an opt-in, we should have a `.mw-100` utility to set `max-width: 100%;`. (Perhaps add it to PR #19234)

**Comment by patrickhlauke** [comment]
@RyanZim 
> You nearly always want `<audio controls>` to be 100% width

evidence for this?

@cvrebert 
> Probably it should be entirely opt-in

agree, would be far too opinionated otherwise.

Once you start getting into the situation of wanting to make it as wide as possible, without breaking onto a new line, you really get into very specific styling which I'm not quite sure is a good candidate for generalising into a utility class, IMO

**Comment by RyanZim** [comment]
@patrickhlauke 
I edited my comment above.

I don't want it:

> as wide as possible, without breaking onto a new line

`max-width: 100%` would allow `<audio>` to behave as normal except when its containing element is too narrow, thereby preventing overlapping content. I can't think of any cases where this would cause a conflict. (Correct me if I'm wrong.)

However, I repeat:

> If you decide against setting a default for `<audio>` in favor of an opt-in, we should have a `.mw-100` utility to set `max-width: 100%;`. (Perhaps add it to PR #19234)

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
New utils coming in #21221 to help.

**Comment by Haixiang6123** [comment]
> @cvrebert I agree that an `.audio` class is unnecessary, however, I still think setting the `<audio>` element to `max-width: 100%;` would be beneficial. I can't think of any cases where this would cause a conflict.
> 
> If you decide against setting a default for `<audio>` in favor of an opt-in, we should have a `.mw-100` utility to set `max-width: 100%;`. (Perhaps add it to PR #19234)

`max-width: 100%` works for me!! God, you save my day!

For those who wants to make `<video/>` auto width, you can try put the `<video/>` into `<div/>`

```html
<div>
  <video ... />
</div>
```
