### ISSUE TITLE
angularjs/bootstrap

### ISSUE THREAD

**Issue by Victor-Zxk** [twbs/bootstrap#19648]
when a page refresh, bootstrap based on angularjs not work very well.

**Comment by RyanZim** [comment]
@Victor-Zxk: Please provide a [Reduced Test Case](https://css-tricks.com/reduced-test-cases/) as a JSFiddle/JSBin and list your browser and OS. You may want to read about filing a bug in the [Contributing Guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by cvrebert** [comment]
I presume you're referring to either https://github.com/angular-ui/bootstrap or https://github.com/mgcrea/angular-strap
We have no involvement with either of those third-party packages and cannot help you with them. Please report problems with those projects to their respective issue trackers, not to this issue tracker.

**Comment by Victor-Zxk** [comment]
Thank you very much!
