### ISSUE TITLE
Justified nav is not working on chrome !

### ISSUE THREAD

**Issue by beingsagir** [twbs/bootstrap#19645]
Here is the output of a theme sample on Chrome!

Example name : Justified nav

![onchrome](https://cloud.githubusercontent.com/assets/1620769/14170487/b33428f2-f74b-11e5-926a-41c30f37d79f.png)

**Comment by RyanZim** [comment]
If you are referring to a theme at http://themes.getbootstrap.com, please do not report it here. See: [CONTRIBUTING.md#using-the-issue-tracker](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker).

**Comment by cvrebert** [comment]
Duplicate of #17723. Please search more next time.

**Comment by kutec** [comment]
Not only Chrome in all browsers it's not working!
