### ISSUE TITLE
W3C CSS Validator

### ISSUE THREAD

**Issue by vipulsolanki** [twbs/bootstrap#19649]
Hello,

We have try to validator the Bootstrap css in w3c and it's show error 41 and warnings, ca you please let us know how to resold the error and warning?

**Comment by RyanZim** [comment]
Bootstrap uses a number of browser-specific hacks. These hacks will not pass validation. They are necessary to ensure compatibility with older browsers. The code should work as intended on all supported browsers. Just ignore the errors and warnings.

**Comment by patrickhlauke** [comment]
See http://getbootstrap.com/getting-started/#support-validators

**Comment by anchev** [comment]
@RyanZim however non-valid CSS cannot be minified correctly by Cloudflare as it won't minify CSS that contains errors.

**Comment by patrickhlauke** [comment]
you can have CSS hacks that ensure things work to an extent in all browsers, or you can have cloudflare-minified CSS. you can't have both.

**Comment by anchev** [comment]
I received an invitation for a new private beta of Cloudflare's auto-minification which seems to minify the CSS. So obviously you will be able to have both. Good news.
