### ISSUE TITLE
Exclude bootstrap parts and components while compiling bootstrap less

### ISSUE THREAD

**Issue by hassandad** [twbs/bootstrap#19644]
I am using bootstrap less in my project. I am not using every thing provided by bootstrap in my project that's why i want to exclude components while compiling bootstrap less like bootstrap provides this facility in its "Customize" page. How could i exclude bootstrap sections exactly like in bootstrap customize page?

**Comment by cvrebert** [comment]
1. Copy `less/bootstrap.less`
2. Delete the `@import`s of the components you don't want
3. Compile the resulting `.less` file with [Less](http://lesscss.org/)
4. Run [Autoprefixer](https://github.com/postcss/autoprefixer) on the resulting CSS file

(If you're okay with modifying Bootstrap's files, then just apply step 2 directly to `bootstrap.less` and then run [`grunt dist`](http://getbootstrap.com/getting-started/#grunt))
