### ISSUE TITLE
Boostrap RTL Support

### ISSUE THREAD

**Issue by caseydev** [twbs/bootstrap#19643]
Hey guys. Its really powerful framework ever. I have one request for you. Are you going to add RTL support on bootstrap 4 or not?

**Comment by cvrebert** [comment]
Duplicate of #19555. Please search next time!

**Comment by caseydev** [comment]
Okay
thanks

**Comment by parsmizban** [comment]
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
