### ISSUE TITLE
v4 - Padding & Margin based on screen size

### ISSUE THREAD

**Issue by iBasit** [twbs/bootstrap#19657]
Sometimes we need different margin size based on different screen size.

Ex:
`m-y-3` is good for desktop, but `m-y-1` is best for mobile for same div area. 

Just like we have `text-xs-center` and `text-sm-left`

I think we should have similar for padding and margins.

```
p-xs-y-3
m-xs-y-3
m-sm-y-3
```

This will make it true responsive support for margin and padding.

**Comment by guylepage3** [comment]
I believe this has been discussed and was dealt with here. https://github.com/twbs/bootstrap/issues/18490

**Comment by cvrebert** [comment]
@guylepage3 No need to CC us. ☺

Yup, closing as duplicate.

**Comment by guylepage3** [comment]
Gotcha.
