### ISSUE TITLE
If there any way to specify use pixel rather then rem?

### ISSUE THREAD

**Issue by jack-fdrv** [twbs/bootstrap#19653]
I want to be able to select in scss variables use pixel then rem. For example some generator like DocRaptor doesnt understand rems.

**Comment by cvrebert** [comment]
You can manually override the default values of the variables and set the variables equal to pixel values (possibly using your own rem->px Sass utility function).

> For example some generator like DocRaptor doesnt understand rems.

I would consider that a bug in DocRaptor.

I'm not sure it'd be worth the extra complication to add built-in support for px conversion just for the benefit of DocRaptor, particularly considering that Bootstrap isn't optimized for print usage in the first place.
CC: @mdo

**Comment by jack-fdrv** [comment]
> can manually override

I tried, and it is not so simple =) 30+ times change and calculate the variable....

I dont think it is a bug in PDF generator, bc it simple parses html like any other string.

But like you wish.

**Comment by mdo** [comment]
Yup, doesn't seem like there's much we can do here.
