### ISSUE TITLE
Embed images into a card

### ISSUE THREAD

**Issue by TheBotox** [twbs/bootstrap#19658]
Hello, I've just migrated form bootstrap 3 and now I'm using the all new Bootstrap's 4 cards. I don't know how to embed images into them.

**Comment by patrickhlauke** [comment]
http://v4-alpha.getbootstrap.com/components/card/

for how-to questions, please refer to StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
