### ISSUE TITLE
documentation on .nav-divider

### ISSUE THREAD

**Issue by ShaunR** [twbs/bootstrap#19652]
I found a class called ```.nav-divider``` however I was unable to find any documentation on this? I'm assuming this is used in nav dropdown menu's however the current docs look to just use ```.divider```

**Comment by cvrebert** [comment]
It's utterly deprecated and therefore deliberately undocumented.
See https://github.com/twbs/bootstrap/blob/7cbd9a181a970b306f1963a612c5cd45aef60f8c/less/navs.less#L54-L58
