### ISSUE TITLE
possible to initialize the framework and all of its plugins?

### ISSUE THREAD

**Issue by r3wt** [twbs/bootstrap#19651]
I've been searching high and low for information on this subject and `zero.zilch.nada`. bootstrap is already loaded before the view is rendered so the html bindings for bootstraps plugins aren't applied.
```js
$.jqMVC.bind('bootstrap',function(){
      //apply bootstrap bindings to view...
});
```

**Comment by patrickhlauke** [comment]
For how-to questions, please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by r3wt** [comment]
or you could have answered it here you fucking twat

**Comment by patrickhlauke** [comment]
nice attitude there. certainly makes me want to help you further in future.
