### ISSUE TITLE
Interval not able to be set on per carousel basis

### ISSUE THREAD

**Issue by alexluecke** [twbs/bootstrap#19666]
When setting up the carousel, you can disable the interval as follows:

    $('.carousel').carousel({ interval: false });

However, the following does not work:

    $('#custom-slideshow-container.carousel').carousel({ interval: false });

It would be better to set interval on a per-carousel per-page basis.

Tested on:
jQuery version: 2.1.4
Bootstrap version: 3.3.6

**Comment by cvrebert** [comment]
Please post a JS Bin or JS Fiddle demonstrating the problem.

**Comment by alexluecke** [comment]
I will update later. For now, I found a fix: if you name your carousel with a custom class it seems to work (i.e. `my-carousel` instead of `carousel`).

**Comment by alexluecke** [comment]
Can't recreate bug outside of my environment. I will Call this a false alarm.
