### ISSUE TITLE
Simple input group has mismatched heights in Chrome

### ISSUE THREAD

**Issue by cageygee3** [twbs/bootstrap#19662]
This can be repro'd in two of the basic examples in the Bootstrap docs:

http://getbootstrap.com/components/#input-groups

In Chrome, the spans containing the text (@, $, and .00) are slightly taller than the inputs right next to them, causing a very noticeable glitch in the bottom border. This is not an issue in IE, Edge, or Firefox. (I'm running Windows 10 64-bit.)

Zoomed in:

![screenshot](https://cloud.githubusercontent.com/assets/10719780/14221092/4aa30c30-f819-11e5-94ae-9bed007b92bd.PNG)

**Comment by cvrebert** [comment]
Unable to reproduce in Win10 Chrome on Sauce Labs:
![chrome](https://cloud.githubusercontent.com/assets/419884/14224500/b9fbf4c2-f853-11e5-90a4-7a89cdcd3c10.png)

The CSS box model heights in DevTools also seem to match.
Are you using non-pinch browser page zoom perhaps? We don't really support that; see http://getbootstrap.com/getting-started/#support-browser-zooming

**Comment by cageygee3** [comment]
Ah yes, that might be it. I have a global page zoom of 125% set in my browser. Feel free to close this out if it's not applicable.
