### ISSUE TITLE
.alert-link styling in alerts should be the default instead of opt-in

### ISSUE THREAD

**Issue by lkula** [twbs/bootstrap#19663]
The alert link class should be available from the parent. If you're dynamically loading API responses from somewhere and they include links, this class isn't available without using javascript to add it later.

**Comment by cvrebert** [comment]
Using JavaScript or templating to add the class later seems like a perfectly fine option. It's a fairly minor inconvenience.

In general, Bootstrap styles are opt-in via explicit classes, so as to not interfere with third-party widgets/libraries. Your suggestion would run rather counter to this.
CC: @mdo

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
