### ISSUE TITLE
Add RTL support to latest 3.3.6 by means of rtlcss

### ISSUE THREAD

**Issue by evilaliv3** [twbs/bootstrap#19668]
As the version 3 for boostrap is coming to its latest release, it would be interesting to add an offiial RTL support atop of it.

This could be done that easily and a patch for that is already implemented and is now been polished by @MohammadYounes in https://github.com/MohammadYounes/RTL-bootstrap/commit/3be91ac69ddd92a47e1e53bcebe2b80b3d04b30e#diff-f3e99e0bb007ace7a370f0492b9cb5ab

it would be great if bootstrap could offer off the shelf the following additional files:
- boostrap-rtl-inline.css
- bootstra-rtl-inline.js

those files could then be used by the users that want to go for that and any app would be able to be in RTL by simply using the HTML dir attribute: https://www.w3.org/International/questions/qa-html-dir

**Comment by cvrebert** [comment]
Sorry, but as explained in https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#feature-requests , new features are no longer being accepted into Bootstrap v3.

**Comment by parsmizban** [comment]
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
