### ISSUE TITLE
cannot download the customized files in v2.

### ISSUE THREAD

**Issue by chenyuncai** [twbs/bootstrap#19675]
Hi, I want to customize and download but failed in v2.3.2. When I clicked the download btn, just wait few seconds and did nothingIt works well in v3.

**Comment by jgacuca567** [comment]
@chenyuncai `Bootstrap V 2.3.2` is no longer supported, use current version from [Bootstrap 3.3.6](http://getbootstrap.com/getting-started/#download)

**Comment by hebbet** [comment]
the customizer for v2 is no longer available. so you are using an unoffical version

**Comment by patrickhlauke** [comment]
indeed http://getbootstrap.com/2.3.2/customize.html

**Comment by chenyuncai** [comment]
OK, Thank you guys for your helping.
