### ISSUE TITLE
Alternative tooltip positioning library

### ISSUE THREAD

**Issue by FezVrasta** [twbs/bootstrap#19673]
I've built my career around Bootstrap, developing and maintaining [Bootstrap Material Design](https://github.com/fezvrasta/bootstrap-material-design). Recently I've started working with BS v4, particularly with the new tooltips and popovers powered by Tether.js.

I rapidly got frustrated by them for several reasons...

That inspired me to create [Popper.js](http://fezvrasta.github.io/popper.js/), a library to manage tooltips, popovers, dropdowns and so on.

It's the result of several years of experience with complex web interfaces which heavily use "poppers" for UX purpose and it spots a long list of features including:
- half the size of Tether.js (just ~3.5KB);
- No CSS dependencies;
- No dependencies required;
- Supports automatic detection of the tooltip size (included its arrow) to correctly position the tooltip near its reference element, without need to specify offsets manually;
- It's fully tested by Karma + Jasmine;
- When you scroll, you don't notice any lag in the popper movement;
- You can append your tooltip element on any element in the page, not just the `body`;
- Popper.js, has automatic support for tooltip element creation. You can define its content, the markup of its arrow and everything you'd expect;
- It supports a plugin system you can use to customize the behavior of the library;
- Particular "flip" behaviors are supported, for example if there's not enough space on the left, you can ask the popper to be placed on the bottom of the reference element;
- The whole code is fully documented using JSDoc;
- Licensed under MIT;
- **update**:
- Written in ES6;
- Includes a side library almost identical to the tooltip.js library of Bootstrap;
- Active community with responsive maintainers;
- Performance optimizations such as 60fps throttling and passive events support;
- Absolutely clear code base, easy to modify and patch;
- `auto` placement option is in WIP in the v1 release;

I’d love for you to check out my library and integrate it with Bootstrap V4.

Here the link to the demo page:
http://fezvrasta.github.io/popper.js/

and of the GitHub repo:
https://github.com/FezVrasta/popper.js

Would you be open to a PR?
Please reach out to me with feedback our questions about Popper.js!

**Update**:

The library has been rewritten in ES6 and its API improved (also, more features has been added), we are finalizing it.
Right now we are writing a side-library with an API very similar to the one used by Bootstrap tooltips, once it will be ready we'll release the new version.
This is being done because our plan is to first replace Tether.js with Popper.js in Bootstrap Material Design v4 to prove the quality of the library and the ease of integration of it.

Popper.js has been successfully adopted by Atlassian and by Le Roy Merlin and both are really happy with it.

**Comment by FezVrasta** [comment]
@cvrebert any chance to get a feedback about this issue?

Thanks!

**Comment by FezVrasta** [comment]
@patrickhlauke or @cvrebert Still waiting for feedback please.

**Comment by mdo** [comment]
Thoughts @fat?

**Comment by FezVrasta** [comment]
@mdo and @fat I have added some updated informations to the first post, maybe they can be useful to let you decide.

**Comment by krisdigital** [comment]
I think the most requested feature for Popovers is 'auto' positioning like in BS3. As a responsive framework popovers are useless otherwise.
I just checked and one can get the expected behavior with tether using the constraints

```js
constraints     : [{to: 'window', pin: ['left', 'right']}],
```
The only thing left to do is adjusting the scss and setting the arrow position.

As mentioned in another thread there are also more positioning options in Tether, no reason to not support them.

**Comment by FezVrasta** [comment]
@krisdigital the way you implemented `auto` is a very simple method, it will flip only when there's not enough space.

The feature we are going to merge in Popper.js instead calculates the available space on the 4 sides and decides the one with more space available.

**Comment by krisdigital** [comment]
@FezVrasta The example does not flip anything, it just prevents the tooltip from moving left or right outside the window. The flipping behavior you described is also something supported by tether, it is some option called attachment:together if I remember correctly.. But it is something I did not need.

**Comment by FezVrasta** [comment]
@krisdigital I'm pretty sure Tether doesn't check for the best placement but it just allows to flip from `bottom` to `top` and from `left` to `right` (and vice-versa).

**Comment by FezVrasta** [comment]
@mdo we just finished to write a side-library based on Popper.js that mimics the behaviour of the Bootstrap tooltip.js script.

https://github.com/FezVrasta/popper.js/tree/v1-dev#tooltipjs

I think this could come in handy if you decide to switch to Popper.js since you will just have to use the existing library and wrap it with jQuery (to add multi-element support)

**Comment by mdo** [comment]
I think we're going to end up passing on this for now. I don't want to leave you hanging, but it seems unlikely that we'll be switching at this point. I'm happy to continue the conversation for subsequent v4 releases though as folks start to use this more!

**Comment by FezVrasta** [comment]
would you be open to a PR for this?

**Comment by FezVrasta** [comment]
I know the issue is closed, but seems relevant to add a link to [Tippy.js](https://atomiks.github.io/tippyjs/).

It's a library for tooltips and pop-overs based on Popper.js, I think it's a good way to show you what you could achieve using my library inside Bootstrap.

**Comment by FezVrasta** [comment]
Related: https://github.com/twbs/bootstrap/pull/22444

**Comment by 719media** [comment]
I've closed 19692 in preference of this issue/pull, since it seems to be the one that will end up landing. I haven't built the pull request branch to check, but one thing that would be nice is if something like <form><dropdown /></form> will still work (i.e. when the dropdown gets absolutely positioned and attached to the <body> when it opens, the <dropdown /> gets "put back" on close, such that the <inputs> will be included in the <form> submit).
