### ISSUE TITLE
Add pointer-events:none to Tooltips (and probably popovers)

### ISSUE THREAD

**Issue by sintro** [twbs/bootstrap#19679]
The reason why it is matters to do something like pointer-events: none for tooltips and popovers is: when you have many objects with tooltips and they are located close to each other, when you are moving mouse from one object to another you have a chance to "hit" the tooltip while it is disappearing (with fade animation). In this case the new tooltip will not be shown for sure, even if you will drag a mouse over the new object.

**Comment by cvrebert** [comment]
`pointer-events` doesn't work in IE<11, sadly.
Also, popovers often contain buttons or links, which `pointer-events: none` would render unclickable.

**Comment by sintro** [comment]
Exactly. I have faced this problem previously, and solved it using about 15 lines of ugly javascript. Don't think that it is worth to find them for anyone. But this problem is definitely has nice cross-browser fix.

**Comment by sintro** [comment]
For some reason there are no description in my first post, I will edit it and also post it here:
The reason why it is matters to do something like pointer-events: none for tooltips and popovers is: when you have many objects with tooltips and they are located close to each other, when you are moving mouse from one object to another you have a chance to "hit" the tooltip while it is disappearing (with fade animation). In this case the new tooltip will not be shown for sure, even if you will drag a mouse over the new object.

**Comment by cvrebert** [comment]
So, since `pointer-events: none` doesn't seem like a workable approach, what's the alternative that you're suggesting?

**Comment by sintro** [comment]
Just checked, it was ``pointer-events: none`` exactly, or disabled animations. So I really don`t know how to fix it now.

**Comment by mdo** [comment]
Punting as a won't fix here—not a clear bug for us to fix. Only thing I could recommend is caution at implementing some of these components in such close proximity to one another. Perhaps another solution could be better? <3

**Comment by sintro** [comment]
I think you are right. Looks like now there are no fine solution for this problem. The best one for tooltips without interactive elements it to user `poiner-events: none`, to make more cross-browser fix one need to write huge crutch in JS, I assume. There are no sence in doing it in core this way for sure.

**Comment by abdulrazakshaikh** [comment]
**you can use like this below**

<style type="text/css">
[disabled]{pointer-events: none}
.tooltip-disabled{pointer-events: none}
</style>


<button type="button" class="btn btn-secondary tooltip-disabled" disabled="disabled" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button>
