### ISSUE TITLE
.form-control-label padding causes horizontal misalignment with other grid text

### ISSUE THREAD

**Issue by davidpauljunior** [twbs/bootstrap#19678]
The documentation for forms under the 'Using the grid' section suggests using the following code:

```
<div class="form-group row">
<label for="inputEmail3" class="col-sm-2 form-control-label">Email</label>
```

The horizontal padding on the `form-control-label` is less than the negative margin on the row, so labels don't line up correctly with the grid.

**Comment by cvrebert** [comment]
Example: http://jsbin.com/bezamecena/edit?html,output

**Comment by cvrebert** [comment]
X-Ref: #18130

**Comment by mdo** [comment]
Closing as a dupe of #18130 I believe.
