### ISSUE TITLE
Dropdowns using Tether?

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#19682]
Tether js for dropdowns?

I like the improvements Tether provides for tooltips/popovers in bootstrap v4. Is there a reason it was not implemented for dropdowns?

This would help with having dropdowns flow outside of overflows, as well as positioning.

Example:
https://jsfiddle.net/719media/0f8vc7td/

The idea here is that I should not have to write custom event handlers to capture the dropdowns and introduce tether.

**Comment by twbs-lmvtfy** [comment]
Hi @719media!

You appear to have posted a live example (https://fiddle.jshell.net/719media/0f8vc7td/3/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 79, column 3 thru column 127: Element ```` link ```` is missing required attribute ```` property ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by 719media** [comment]
Try this?

https://jsfiddle.net/719media/0f8vc7td/

**Comment by cvrebert** [comment]
Overlaps with #17167.

**Comment by cvrebert** [comment]
> Is there a reason it was not implemented for dropdowns?

No deliberate reason. Patches welcomed.
Dropdowns in Bootstrap v3 didn't dynamically position themselves like Tooltips/Popovers do, so there wasn't any relevant Dropdown positioning JS to rewrite when we migrated to Tether in v4-dev.

**Comment by 719media** [comment]
Please see 19692

**Comment by davidklebanoff** [comment]
Another option is #19673.

**Comment by 719media** [comment]
closing this in preference of pull request #22444
