### ISSUE TITLE
Naming concerns regarding .btn-secondary

### ISSUE THREAD

**Issue by robertzajda** [twbs/bootstrap#19688]
Hi

As I see in 4 alpha **btn-default** is renamed to **btn-secondary**.
Is it good way? It closes posibility of adding more colors to bootstrap.

In some of my projects there are variables:
$brand-primary $brand-secondary $brand-tertiary

In my opinion keywords primary, secondary, tertiary should be reserverd for colors.

What do you think?

Robert

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by mdo** [comment]
Apologies for the clashing with your keywords, but `secondary` implies a much clearer hierarchy and purpose than `default`—we'll be sticking with it for the time being.
