### ISSUE TITLE
Emphasize that .list-inline also requires .list-inline-item

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#19690]
V4 Alpha 2 coming from bootstrapcdn.com:

https://jsfiddle.net/7hd6qmtr/

A list set as inline still shows stacked vertically however it does remove the bullets.

**Comment by cvrebert** [comment]
Your example is missing the requisite `.list-inline-item` class on the items. See http://v4-alpha.getbootstrap.com/content/typography/#inline

**Comment by bellwood** [comment]
Thank you very much =)

Perhaps the documentation for lists could link/allude to this?

I had looked through the docs rather thoroughly (or so I thought) and obviously missed this.

Again, thank you =)

**Comment by cvrebert** [comment]
Yeah, I suppose we could try to highlight the requirement more.

**Comment by mdo** [comment]
Fixed in 2cc7567.
