### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by dtagdev1** [twbs/bootstrap#19694]
please see:
![screenshot from 2016-04-09 09 27 37](https://cloud.githubusercontent.com/assets/7581868/14401262/742067e8-fe35-11e5-8254-1b9fd3df277d.png)

I tried to overcome popup scrollbar . Help me. thank all!

**Comment by cvrebert** [comment]
Personal support requests don't belong on this issue tracker. Use StackOverflow, IRC, Slack, or similar instead. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
