### ISSUE TITLE
V4: Responsive Classes - Actions for one breakpoint

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#19695]
One thing I'm struggling with (but loving at the same time) on V4 is the new responsive classes.

For instance, I want to hide a piece of text wrapped in a span when the viewport is medium.

Based on the docs:

> You can combine one `.hidden-*-up` class with one `.hidden-*-down` class to show an element only on a given interval of screen sizes.

So given the grid:

http://v4-alpha.getbootstrap.com/layout/responsive-utilities/

I should be able to do:

```
<span class="hidden-md-down hidden-md-up">Content</span>
```

... as the summation of those two leads to the medium column being hidden.

Alas this does not work, the content in the span is ALWAYS hidden.

Any pointers?

Thank you =)

**Comment by cvrebert** [comment]
As mentioned in those docs:

> These classes don’t attempt to accommodate less common cases where an element’s visibility can’t be expressed as a single contiguous range of viewport breakpoint sizes; you will instead need to use custom CSS in such cases.

You want your example `<span>` to be visible on XS-SM and LG-XL. That's two disjoint ranges, not a single contiguous range, and thus not supported.
Perhaps the docs need further clarification.

**Comment by cvrebert** [comment]
I'm also somewhat curious what your concrete use case is.

**Comment by bellwood** [comment]
Sure...

I have a 3 column grid to display to highlight 3 products

One of the products has a heading:

Amazing Widget

At the medium view port this heading wraps and the additional line break causes visual discontinuity with the other two columns.

So, I tried wrapping "Amazing" in a span with a responsive class to hide it just at the medium view where this is happening. In this case Amazing is a non-critical descriptive and being invisible at this breakpoint does no "harm".

Thanks =)

**Comment by RyanZim** [comment]
@cvrebert I realize we're trying to get away from `visible-*` classes since they add a lot of bloat to the library (due to needing `block`, `inline`, and `inline-block` options for each). Perhaps we could come to a compromise by adding explicit `hidden-*` classes that hide the element **only** at the given breakpoint. That would allow for code like this:
```
<span class="hidden-xs hidden-sm hidden-lg hidden-xl">Content</span>
```
for the above edge cases. This would require the addition of 5 classes vs. 17 classes for `visible-*-*`.

I would personally rather write the above row of classes instead of writing custom css for the media queries. (I remember doing that for `pull-*-left` in v3 - **_ouch_**)

**Comment by cvrebert** [comment]
@bellwood And how is your design intended to behave on SM and LG screens?

**Comment by cvrebert** [comment]
@RyanZim Don't you mean `<span class="hidden-md">Content</span>` ?

**Comment by bellwood** [comment]
@cvrebert At the smaller breakpoints all the headings are wrapped so its visually consistent

I would love to have the hidden-* functionality back...

**Comment by RyanZim** [comment]
@cvrebert Yes, sorry.

**Comment by cvrebert** [comment]
That seems brittle. If the product names weren't hardcoded (e.g. pulled from a database), you'd need a different approach.

@mdo Your thoughts on adding `.hidden-{breakpoint}-only` classes?

**Comment by bellwood** [comment]
@cvrebert No contest however in this case its a static site...

I suppose I could see if responsive typography would work but for ease of use adding back the hidden-** classes would be great

**Comment by bellwood** [comment]
Also an option would be to have the header in the page twice and set breakpoints on each accordingly but violating DRY to accomplish this seems senseless.

Thanks to everyone for their considerations =)

**Comment by mdo** [comment]
No plans to add these classes at this point—sticking with the up and down variants.

**Comment by bellwood** [comment]
Mark,

Any possibility for future implementation or are "we" basically saying no?

Trying to determine how best to address my implementation - thanks =)

**Comment by mdo** [comment]
Basically saying no :grin:

**Comment by bellwood** [comment]
"A" for honesty - thanks Mark =)
