### ISSUE TITLE
Dropdown doesn't close properly on iOS

### ISSUE THREAD

**Issue by stephenbe** [twbs/bootstrap#19691]
Hello,

I have noticed a bug when trying to close a dropdown, if you tap on the red div, it won't actually close the dropdown (viewport > 767)

http://output.jsbin.com/waziduquhe/1
http://jsbin.com/waziduquhe/1/edit?html,output

I tested on Ipad mini with IOS 9.3.1

Thank you,

Steve

**Comment by twbs-lmvtfy** [comment]
Hi @stephenbe!

You appear to have posted a live example (http://jsbin.com/luwiyataru/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 54, column 7 thru column 58: Bad value ```` search ```` for attribute ```` role ```` on element ```` form ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by stephenbe** [comment]
Fixed : 

http://output.jsbin.com/waziduquhe/1
http://jsbin.com/waziduquhe/1/edit?html,output

**Comment by cvrebert** [comment]
Known issue, see http://getbootstrap.com/getting-started/#navbar-dropdowns

**Comment by stephenbe** [comment]
Alright thank you!
