### ISSUE TITLE
No styling for labels (using SCSS)

### ISSUE THREAD

**Issue by mstnorris** [twbs/bootstrap#19697]
I'm using Laravel, Laravel-Elixir (gulp) and compiling the SCSS source and there isn't any styling when using `.label.label-*`.

The compiled minified alpha-2 hosted on BootstrapCDN is fine however.

I've also stripped all my customisations and still no label styling.

Lastly, I tried with a completely new install of Laravel, pulled in the alpha-2 scss from npm and still no styling.

![No styling](http://i.imgur.com/IvGDfoP.png)

```html
<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-sm-6 col-xs-12">
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="label label-success label-pill pull-xs-right">14</span>
                    Cras justo odio
                </li>
                <li class="list-group-item">
                    <span class="label label-info label-pill pull-xs-right">2</span>
                    Dapibus ac facilisis in
                </li>
                <li class="list-group-item">
                    <span class="label label-success label-pill pull-xs-right">1</span>
                    Morbi leo risus
                </li>
            </ul>
        </div>
    </div>
</div>
```

**Comment by wolfy1339** [comment]
The label component was renamed to pill

**Comment by mstnorris** [comment]
Can you point to the source where that is? I've tried as you suggested and it doesn't change anything.

As mentioned above, when using the minified version from the CDN, it works just fine.

**Comment by wolfy1339** [comment]
Sorry, my mistake. Its named tag https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tags.scss

**Comment by mstnorris** [comment]
Thank you
