### ISSUE TITLE
V4: bd-navbar missing from bootstrap.min.css (it's in docs.min.css)

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#19699]
In working with v4-alpha2: 

```
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css
```

...and with responsive navigation I found myself needing to include:

```
http://v4-alpha.getbootstrap.com/assets/css/docs.min.css
```

...in order to make use of "bd-navbar" which then properly renders/styles the responsive navs.

I'm sure part of this has todo with the laundry list involving navigation however figured it was worth mentioning.

The only way I got responsive navs working was to copy the view-source from the v4 docs page and then trim it back to my needs and then stumbled on needing the bd-navbar bits from docs.min.css for even that to work properly.

Adding this to my custom.css allows functionality without the need to include docs.min.css:

```
.bd-navbar {
    font-size: 87.5%
}

.bd-navbar .navbar-nav .nav-link {
    color: #8e869d
}

.bd-navbar .navbar-nav .nav-link.active,
.bd-navbar .navbar-nav .nav-link:focus,
.bd-navbar .navbar-nav .nav-link:hover {
    color: #373a3c;
    background-color: transparent
}

.bd-navbar .navbar-nav .nav-link.active {
    color: #000
}

.bd-navbar .dropdown-menu {
    font-size: inherit
}
@media (max-width:767px) {
    .bd-navbar .nav-link {
        float: none
    }
    .bd-navbar .nav-link+.nav-link {
        margin-left: 0
    }
}
```

Thank you =)

**Comment by hebbet** [comment]
i think it is intentionally missing from bootstrap.css. 
it is for docs only. 

please note: bootstrap v4 is still an alpha and things might break during it. so updating to a later version might be difficult. i would recommend using 3.x for now.

**Comment by bellwood** [comment]
I know but we gotta use it to find issues :)

**Comment by RyanZim** [comment]
@bellwood: Responsive navs are not implemented yet for v4. See #18467 &  #17250. @hebbet is probably right; the docs still need responsive navs whether bootstrap v4 has them yet or not.

**Comment by cvrebert** [comment]
What @hebbet and @RyanZim said.
