### ISSUE TITLE
Feature request - Right To Left layout

### ISSUE THREAD

**Issue by ppp999** [twbs/bootstrap#19703]
Please consider to make a RTL version of Bootstrap. 

I know that there are some RTL forks, but it doesn't support well, and they not update for each version of Bootstrap.

Hope you will make that.

**Comment by hebbet** [comment]
see [19545#comment](https://github.com/twbs/bootstrap/issues/19545#issuecomment-196990781)

**Comment by ppp999** [comment]
Thanks

**Comment by cvrebert** [comment]
Nope.

**Comment by cvrebert** [comment]
Duplicate of #19555.

**Comment by parsmizban** [comment]
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
