### ISSUE TITLE
Boostrap Modal disappears automatically when used with Navigation Wizard

### ISSUE THREAD

**Issue by jpavanaryan** [twbs/bootstrap#19700]
Hello Folks,
I have an issue with Bootstrap Modal. I am using Bootstrap3.x for Modal and BootstrapWizard for custom navigation wizard. So both the libraries are necessary. When I click on Modal it disappears automatically. Can anyone help me on this?

**Comment by RyanZim** [comment]
Please provide a [Reduced Test Case](https://css-tricks.com/reduced-test-cases/) and list your browser and OS.

**Comment by cvrebert** [comment]
We are unable to provide assistance with third-party libraries such as BootstrapWizard.
Please ask on a BootstrapWizard-related venue or a Bootstrap community forum (e.g. StackOverflow, IRC, Slack; see https://github.com/twbs/bootstrap/blob/master/README.md#community ) instead.
Thank you for your understanding, and good luck.
