### ISSUE TITLE
[v4] Any options to make two column layout with left fixed width?

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19716]
Are there any ways in BS4 right now to make a grid (let say two columns) with left column fixed width? If no, how would you recommend to do it using BS4 grid framework?

**Comment by RyanZim** [comment]
Not that I know of.

Not sure why you would want this, as BS4 [removed support for non-responsive use](http://v4-alpha.getbootstrap.com/migration/#misc). Concrete use case?

**Comment by Mevrael** [comment]
* User menu / user card with photo/name/statistics left -> profile details, edit profile form, whatever else right
* Any item (main col) with small column of statistics at the right/left
* Left menu, admin panel
* Documentation

**Comment by RyanZim** [comment]
I would personally make the small column responsive as well, but supposing that you really had to make it fixed-width, how would you recommend this to be implemented?

FWIW, some of the above use cases might be implemented better using a drawer. See #17502, #9481, &  #9397.

**Comment by cvrebert** [comment]
Different folks would want different fixed widths, so it doesn't seem generic enough to include something for this in Bootstrap itself.
And I doubt you'd actually want it to be fixed-width on mobile.
CC: @mdo

**Comment by mdo** [comment]
Yeah, not going to happen in the core—that's something that belongs in the customization layer.
