### ISSUE TITLE
Double border line

### ISSUE THREAD

**Issue by jamalsoueidan** [twbs/bootstrap#19715]
Hello everyone,

I don't know if this is a bug in line-group:

![screen shot 2016-04-11 at 1 42 22 pm](https://cloud.githubusercontent.com/assets/115714/14425907/364275ee-ffeb-11e5-9b7a-c6d6ee6ed4b9.png)

The double border line is incorrect on some line-group-item:

```
.list-group-item {
    position: relative;
    display: block;
    padding: .75rem 1.25rem;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid #ddd;
}
```

I did not change anything on the original bootstrap code.

```
<div class="list-group">
    <city-item class="list-group-item">
    amager
  </city-item><city-item class="list-group-item">
    berlin
  </city-item><city-item class="list-group-item">
    esbjerg
  </city-item><city-item class="list-group-item">
    fredericia
  </city-item><city-item class="list-group-item">
    frederiksberg
  
etc..
</div>
```

**Comment by patrickhlauke** [comment]
you'll need to provide a live reduced test case (for instance using https://jsfiddle.net/), and indicate which browser and OS you're seeing the problem in. also, check that your zoom level in the browser is set to 100% (as bootstrap does not currently support browser zoom levels other than default). i'm assuming this refers to bootstrap 3 as well, yes?

**Comment by jamalsoueidan** [comment]
Damn it was NOT 100% zoom...
