### ISSUE TITLE
label inside .input-group-addon breaks height of addon [v4-dev]

### ISSUE THREAD

**Issue by vinorodrigues** [twbs/bootstrap#19711]
Nesting a label tag inside a .input-group-addon now breaks the height of the add-on.

```html
<div class="input-group">
  <span class="input-group-addon"><label for="go">X</label></span>
  <input name="go" class="form-control" type="text">
</div>
```

*This seems to come from _reboot.scss:291*

A possible fix is this override

```css
.input-group label {
  margin: 0;
}
```

See this [jsfiddle](http://jsfiddle.net/cvrebert/7hs4qpcf/5/) for sample.

**Comment by cvrebert** [comment]
Just get rid of the wrapper `<span>`: http://jsfiddle.net/cvrebert/02hocdbh/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/cvrebert/02hocdbh/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 6597, column 5 thru column 46: The ```` for ```` attribute of the ```` label ```` element must refer to a non-hidden form control.
* line 6602, column 5 thru column 47: The ```` for ```` attribute of the ```` label ```` element must refer to a non-hidden form control.
* line 6610, column 5 thru column 46: The ```` for ```` attribute of the ```` label ```` element must refer to a non-hidden form control.
* line 6615, column 5 thru column 47: The ```` for ```` attribute of the ```` label ```` element must refer to a non-hidden form control.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
