### ISSUE TITLE
W3C CSS Grids

### ISSUE THREAD

**Issue by LaurentGoderre** [twbs/bootstrap#19729]
Hey,

I was just introduce to this W3C document for implementing grids natively in CSS and was a bit surprised that there doesn't seem to be anyone from this community as a collaborator for this document.

https://www.w3.org/TR/css-grid-1/

I know that this might compete somewhat with this project, but if it's going to be a recommendation, I would prefer that it gets input from a community that has been doing grids for years.

**Comment by mdo** [comment]
Not really something that competes with our project—if the spec improves something like this, we'll likely end up implementing and extending it in the future. For now though, not much for us to do. There's been plenty of community input on it I think :).

**Comment by mikhey** [comment]
I realize this has been closed, but I recently came across this article on MDN:

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids#Native_CSS_Grids_with_Grid_Layout

And I realize that mainly Chrome (through flags) and Firefox 50+ are supporting this (https://www.w3.org/TR/css3-grid-layout/), however, it's something to keep an eye on IMO.

**Comment by RehanSaeed** [comment]
It's not live in Firefox and Chrome https://css-tricks.com/getting-started-css-grid/ without a feature flag.
