### ISSUE TITLE
Is the modal("hide") only useful to visible modals?

### ISSUE THREAD

**Issue by taotaocoule** [twbs/bootstrap#19720]
I have a problem about the modal plugin. When I use the modal("hide") function to an invisible modal, it's useless. So I want to know is the modal("hide") function only useful to visible modals.

**Comment by cvrebert** [comment]
What precisely do you mean by "invisible"?

**Comment by taotaocoule** [comment]
I have to hide the modal use jquery.hide() function (for some reasons I can't use the modal('hide') directly) in my page. But if I do this, the hidden modal will mask my page. So I hope to use the modal('hide') to close this modal after the modal is hidden, but it seem to be useless.

**Comment by cvrebert** [comment]
Please post a JS Bin, JSFiddle, CodePen, or similar that demonstrates the problem.

**Comment by taotaocoule** [comment]
I have found it that I set the modal "display:block", so it always mask other elements.
But I also find that the modal's z-index is always 1040, if z-index could be -1 when it is not displayed on the page, I think it will be better.
Thanks!

**Comment by cvrebert** [comment]
@taotaocoule Please post a JS Bin, JSFiddle, CodePen, or similar that demonstrates the problem so we can properly analyze it.
