### ISSUE TITLE
Scrollspy broken when using non-list-based navbar markup

### ISSUE THREAD

**Issue by secondstreetmedia** [twbs/bootstrap#19736]
According to the documentation (http://v4-alpha.getbootstrap.com/components/navbar/), navbar implementation can be simplified from:

```
<nav class="navbar navbar-light bg-faded">
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
</nav>
```

 to: 

```
<nav class="navbar navbar-light bg-faded">
  <div class="nav navbar-nav">
    <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
    <a class="nav-item nav-link" href="#">Features</a>
    <a class="nav-item nav-link" href="#">Pricing</a>
    <a class="nav-item nav-link" href="#">About</a>
  </div>
</nav>
```

However, unless I'm missing something, which is entirely possible, doing so appears to break Scrollspy, as the menu items no longer highlight.

Using the initial navbar implementation:
https://jsbin.com/dekakunuha/edit?html,css,js,output

Using the simplified implementation:
https://jsbin.com/viyexurala/edit?html,css,js,output

Thanks,
Tim

**Comment by twbs-lmvtfy** [comment]
Hi @secondstreetmedia!

You appear to have posted a live example (https://fiddle.jshell.net/cckbke6q/5/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 120, column 3 thru column 72: Start tag ```` body ```` seen but an element of the same type was already open.
* line 120, column 3 thru column 72: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @secondstreetmedia!

You appear to have posted a live example (https://fiddle.jshell.net/0uk84srk/5/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 120, column 3 thru column 72: Start tag ```` body ```` seen but an element of the same type was already open.
* line 120, column 3 thru column 72: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
@secondstreetmedia Try [JS Bin](http://jsbin.com/) instead of JSFiddle.

**Comment by secondstreetmedia** [comment]
@cvrebert  Edited initial post, replacing JSFiddle links with JS Bin links.

**Comment by cvrebert** [comment]
Reposting to trigger validator: https://jsbin.com/viyexurala/edit?html,css,js,output

**Comment by Manuellama** [comment]
I noticed this too in https://jsbin.com/dekakunuha/edit?html,css,js,output link:

If there is not enough content height in the page to make the target considered as active,when you choose the last item, this will not allow the content to reach the top of the page, and you will never get the white font to mark it as target, because it is not an active target. The last item will not be marked as active if there is no extra space to place the last item content in the top.

I added extra content after the last item so you can see it here.
https://jsbin.com/qapizoligo/edit?html,css,output

**Comment by vanduynslagerp** [comment]
X-ref #21807
