### ISSUE TITLE
.list-group-item links style has changed or lost

### ISSUE THREAD

**Issue by gslender** [twbs/bootstrap#19732]
Not sure if the intended outcome in the latest dev build was intending to strip the non-active hover style and introduce an active-link on the text ??

As per https://jsfiddle.net/3aegkL4h/

**Comment by cvrebert** [comment]
@gslender That JSFiddle doesn't use `.list-group-item`. Wrong fiddle?

**Comment by gslender** [comment]
(sound of a massive DOH! heard across the land)..... This fiddle is now correct (and saved) !!

https://jsfiddle.net/3aegkL4h/1/

**Comment by ItsJonQ** [comment]
It looks like the `<a>` styles of `.list-group-item` were removed :o.

Looking at the history, it might have been caused by this update?
https://github.com/twbs/bootstrap/commit/cbda7e3862306a2ec3bced93f250be9378b99c99#diff-cd8ec88dc7823a5c78f7111e37a78adbL48

**Comment by mdo** [comment]
Those styles were remapped to another class. I've made a note in the migration docs for it: 15874b7.

**Comment by gslender** [comment]
Maybe update the docs too !!

http://v4-alpha.getbootstrap.com/components/list-group/#linked-items

**Comment by mdo** [comment]
Hosted docs will be updated when we release the next alpha version. Docs are up to date in the branch.
