### ISSUE TITLE
Link-style custom file control

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#19740]
It would be really nice to have a custom file control which would style like a link, as the one GitHub uses for attaching files to issues.

![screen shot 2016-04-15 at 13 03 13](https://cloud.githubusercontent.com/assets/851745/14559678/c118c28c-030a-11e6-8813-fee4c9c61ce7.png)

What do you think?

**Comment by patrickhlauke** [comment]
To clarify, github's own implementation is a combination of an actual `<input type="file"...>` that is visually hidden, and a separate `<button...>` with custom javascript that then triggers the actual file input itself

**Comment by patrickhlauke** [comment]
also, github's file chooser does not provide a built-in indication of which file was selected (as it integrates it in the big comment/text field itself), so some additional way of indicating the chosen file for upload would need to be devised

**Comment by RyanZim** [comment]
Foundation uses a fairly simple solution: http://foundation.zurb.com/sites/docs/forms.html#file-upload-button. However, it does not display the name of the file that was selected (it's pure CSS, no JS).

Osvaldas Valutis wrote an article about a similar method that has a few more features: http://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

I tend to favor an adaptation of the 2nd method.

**Comment by heruan** [comment]
Thank you @patrickhlauke for your response. I understand GitHub's implementation uses JavaScript, but in my opinion Bootstrap's implementation could be done with an hidden `<input type="file">` inside a customized `<label>`—as on `.custom-file` in v4.

**Comment by heruan** [comment]
@RyanZim I tried the Foundation's method and it works, now it's just a matter of styling a `<label>` as a link.
```html
<input id="files" type="file" multiple class="sr-only">
Attach files by dragging &amp; dropping, <label for="files" class="m-b-0">selecting them</label>, or pasting from the clipboard.
````

**Comment by patrickhlauke** [comment]
@heuan sure i wasn't being dismissive, just adding some info/context for when we look at this more closely :)

**Comment by RyanZim** [comment]
**A side note:**
Maybe I'm wrong, but wrapping the input in a `<label>` seems a bit un-semanatic. Are there any drawbacks of the `for` attribute that I'm unaware of?

Osvaldas Valutis has an example that pretty well duplicates what `.custom-file` does: http://tympanus.net/Tutorials/CustomFileInputs/#file-7. It also doesn't rely on `::before` and `::after` nearly as much. Would this implementation be something that could be considered for `.custom-file`?

**Comment by patrickhlauke** [comment]
wrapping an input inside its own `<label>` is perfectly legit semantically, and something that's been used for a long time. there's no particular drawback to `for`, it's just a different way of marking up the same thing (commonly referred to as implicit labelling, see for instance https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly)

**Comment by RyanZim** [comment]
OK, just wondered.

**Comment by heruan** [comment]
I've achieved this with `for` and `id`.
```html
<span>Attach files by dragging and dropping,</span>
<label for="attachmentsInputElement" class="link">selecting them</label>,
<span>or pasting from the clipboard.</span>
<input id="attachmentsInputElement" type="file" multiple class="sr-only">
```
Thank you all for the suggestions!
