### ISSUE TITLE
Reboot.scss overwrote some of my css

### ISSUE THREAD

**Issue by tiagoovieira** [twbs/bootstrap#19746]
I was taken by surprise by some changes happened to the css of my app, I'm importing v4 via CDN, and apparently reboot.scss broke some of my CSS. Some of my link tags had some styling or the default blue link color but this line imported from reboot.scss
```
a:not([href]) {
  color: inherit;
  text-decoration: none;
}
```
changed the styling (my app is in angular, so I don't use href and use ng-click instead, for e.g) 

Is there a way to ignore reboot.scss?

**Comment by hebbet** [comment]
> Is there a way to ignore reboot.scss?

build bootstrap from source and don't include it via CDN.

**Comment by patrickhlauke** [comment]
Fundamentally, an `<a...>` without an `href` is a non-focusable placeholder/named anchor. for controls, you should use either proper `<a href="#" role="button">` or, even better, `<button>` elements.

But if for whatever reason you *are* set on using named anchors, at least ensure that they're keyboard focusable and expose their role as button controls `<a tabindex="0" role="button">` and override the reboot styles with your own `a:not([href]) { ... }` styles

**Comment by ramitmathur27m** [comment]
> Fundamentally, an `<a...>` without an `href` is a non-focusable placeholder/named anchor. for controls, you should use either proper `<a href="#" role="button">` or, even better, `<button>` elements.
> 
> But if for whatever reason you _are_ set on using named anchors, at least ensure that they're keyboard focusable and expose their role as button controls `<a tabindex="0" role="button">` and override the reboot styles with your own `a:not([href]) { ... }` styles

Thanks It worked for me too!

**Comment by scottw-finao** [comment]
re: "build bootstrap from source and don't include it via CDN."

Um ok, how???  I see a LOT of people complaining about a tag customizations being squashed by this _reboot thing - why isn't there a version of bootstrap available that avoids this annoying behavior and/or specific instructions somewhere on how to remove it?
I'm getting it on a standard hover that, short of putting a contextual rule for every single use of an a tag to tell it 'turn off the damn underline whenever I use an a inside a div with an li and a ul' that it won't go away.  (e.g. a:hover { text-decoration: none; } doesn't work)

**Comment by RubyRabelle** [comment]
Also totally annoyed by reboot.   We don't compile our code and "downloading from source" is still giving me references to reboot.scss  

Make it stop!!

**Comment by austingriff** [comment]
Agreed... annoyed by reboot.. this is an ISSUE.... not sure why this "Closed". Its overwriting my background colors to everything. I upgraded from Bootstrap 3 --> 4 on an existing website and this problem is insanely annoying.

<img width="409" alt="Screen Shot 2019-07-02 at 6 20 48 PM" src="https://user-images.githubusercontent.com/13683746/60552984-bc817780-9cf6-11e9-9a6c-86daec18bd99.png">
<img width="752" alt="Screen Shot 2019-07-02 at 6 22 02 PM" src="https://user-images.githubusercontent.com/13683746/60552985-bc817780-9cf6-11e9-9c13-53d9bc8f671f.png">

**Comment by austingriff** [comment]
Agreed... annoyed by reboot.. this is an ISSUE.... not sure why this "Closed". Its overwriting my background colors to everything. I upgraded from Bootstrap 3 --> 4 on an existing website and this problem is insanely annoying.

<img width="1414" alt="Screen Shot 2019-07-02 at 6 20 23 PM" src="https://user-images.githubusercontent.com/13683746/60553257-0dde3680-9cf8-11e9-82ca-e4a887dd41a6.png">
<img width="752" alt="Screen Shot 2019-07-02 at 6 22 02 PM" src="https://user-images.githubusercontent.com/13683746/60553258-0e76cd00-9cf8-11e9-8c99-9fe5a0c2ef4d.png">

**Comment by whisperV** [comment]
Same issue, reboot's default styling for the body element is creating problems. 

The only solution I found was to build from the source as was already suggested.

**Comment by whisperV** [comment]
Same issue on my end. Reboot's default styling is showing up when I don't expect it to. 

Building from the source is the only solution I've found so far

**Comment by BrutalCSkakan** [comment]
Hello. this is a big issue, could it be fixed soon?

**Comment by kai452** [comment]
Hi everybody, 
a Happy New Year !

Had same Problem with 
<a.... 
in my html

After I wrote a basic
a {
 ....
}
in addition to things like
.nav a{
...
}
 into my css, the problem was gone.

Hope, it will solve the problem for Your,
Kai

**Comment by kingalione** [comment]
Why is this issue closed? I have same problems here. _reroot.scss is constantly overwriting my styles.

**Comment by GeanCarloV** [comment]
I have the same problem, try all the previous solutions but it does not allow me to put my own styles, even if I put it important!

**Comment by kevin-poulet** [comment]
hi guys, I'm also facing this issue, a workaround working for me is to add ::ng-deep :
::ng-deep a { ... }
hope it can help some people, and there'll be a true solution one day

**Comment by patrickhlauke** [comment]
the true solution is: don't misuse `<a>` elements for actual actionable controls. if they're acting as links, they need to have an `href` attribute. if they're used to act as buttons, they should really be output as `<button>`, not an anchor element.

**Comment by kevin-poulet** [comment]
@patrickhlauke actually I think it has nothing to do with the href. I got the issue in an angular project using bootstrap where my anchor's css was ignored, and when inspecting the dom, the style applied came from reboot.
however the ng-deep workaround works for angular project, not sure it was OP's context

**Comment by codementation** [comment]
Normally I wouldn't comment on an issue closed for this long, but this ranks high on search engines and just wanted to leave a simpe solution for anyone else that stumbles on this.  For React or or any SCSS @import use case simply place your custom overrides **below** the @include and the subsequent stylesheets will "cascade" as desired -  effectively overriding _reboot.scss:

e.g.:
```
// index.scss

// Import bootstrap, anything before this gets overridden by _reboot
@import '../node_modules/bootstrap/scss/bootstrap'; 
// Overrides go here
a {}
```

**Comment by psarco** [comment]
For those who have the problem with the **_reboot.scss** the solution that I find was **_edit_** the **bootstrap.min.css.map** if you only have to delete the **"../../scss/_reboot.scss",**, on your file preventing the site load the bootstrap reboot, obviously you have to add your own reboot.

**Comment by Abhishek-K-Mckinsey** [comment]
> Normally I wouldn't comment on an issue closed for this long, but this ranks high on search engines and just wanted to leave a simpe solution for anyone else that stumbles on this. For React or or any SCSS @import use case simply place your custom overrides **below** the @import and the subsequent stylesheets will "cascade" as desired - effectively overriding _reboot.scss:
> 
> e.g.:
> 
> ```
> // index.scss
> 
> // Import bootstrap, anything before this gets overridden by _reboot
> @import '../node_modules/bootstrap/scss/bootstrap'; 
> // Overrides go here
> a {}
> ```

This worked for me. Thanks @codementation

**Comment by vaporpin** [comment]
> Normally I wouldn't comment on an issue closed for this long, but this ranks high on search engines and just wanted to leave a simpe solution for anyone else that stumbles on this. For React or or any SCSS @import use case simply place your custom overrides **below** the @import and the subsequent stylesheets will "cascade" as desired - effectively overriding _reboot.scss:
> 
> e.g.:
> 
> ```
> // index.scss
> 
> // Import bootstrap, anything before this gets overridden by _reboot
> @import '../node_modules/bootstrap/scss/bootstrap'; 
> // Overrides go here
> a {}
> ```

I have a new app importing a library which I have built using bootstrap and it messed up my new app's style. 
When I import the library in one of the components, reboot.scss got activated straightaway and affect the <a> tags on my sidebars in the new app. Where should I place my new app's style at to override bootstrap's reboot.scss styles? Thank you.

**Comment by Sufyanzaki** [comment]
just place index.css after the bootstrap.min.css, this fixed my problem   
import 'bootstrap/dist/css/bootstrap.min.css';
import './index.css';

**Comment by CartagoGit** [comment]
> re: "build bootstrap from source and don't include it via CDN."
> 
> Um ok, how??? I see a LOT of people complaining about a tag customizations being squashed by this _reboot thing - why isn't there a version of bootstrap available that avoids this annoying behavior and/or specific instructions somewhere on how to remove it? I'm getting it on a standard hover that, short of putting a contextual rule for every single use of an a tag to tell it 'turn off the damn underline whenever I use an a inside a div with an li and a ul' that it won't go away. (e.g. a:hover { text-decoration: none; } doesn't work)

In your angular.json just put the project styles after the bootstrap styles, then your styles will override the __reboot.css styles.

```
"build": {
     ...
        "styles": [
          "node_modules/bootstrap/dist/css/bootstrap.min.css",
          "src/styles.css"
        ],
        "scripts": []
      },
```

**Comment by FaresMenzli** [comment]
maybe it is not the best solution but also the inline style is working

**Comment by daustany** [comment]
I have removed import bootstrap section on my react project, then add by link directly in my head before my other main css.

**Comment by Muk74dir** [comment]
what a terrible day

**Comment by IfDougelseSa** [comment]
> ###
> **[CartagoGit](/CartagoGit) ** commented [Sep 28, 2022](#issuecomment-1261071547) •

It worked here.
