### ISSUE TITLE
Closing an open collapsed navbar on clicking outside of the navbar element

### ISSUE THREAD

**Issue by alexrois** [twbs/bootstrap#19768]
Actual for bootstrap 3.3.6.

Example: http://getbootstrap.com/examples/navbar-fixed-top/

Open this example on mobile (or in desktop with resized browser window to width less than 768px) and try to collapse menu by clicking outside of dropdown. In this case nothing happens. So you can collapse menu only by clicking on button with bars (navbar-toggle button).

At the same time if you will test "Dropdown" in my example (with full sized browser window) you can see that clicking outside of dropdown works fine. It happens because we have `.dropdown-backdrop` class for `data-toggle="dropdown"` (see http://getbootstrap.com/javascript/#dropdowns-usage). But we do not have the same behavior for `data-toggle="collapse"` (http://getbootstrap.com/javascript/#collapse).

Any suggestions?

**Comment by alexrois** [comment]
Is here somebody who can solve this issue?

**Comment by JulienItard** [comment]
+1

**Comment by iamrohan** [comment]
+1

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
