### ISSUE TITLE
v4-dev: the docs and source of v4 is out of date

### ISSUE THREAD

**Issue by jmpews** [twbs/bootstrap#19760]
http://v4-alpha.getbootstrap.com/components/navbar/

in the docs,the outline style of button is below.
```
btn-success-outline
```
but the last source of github is
```
btn-outline-success
```

**Comment by cvrebert** [comment]
As noted in the website itself, http://v4-alpha.getbootstrap.com reflects Bootstrap v4.0.0-alpha.2, not the `v4-dev` git branch.
The hosted docs always reflect a particular tagged release, not a moving target such as a git branch.
If you need docs for `v4-dev`, build+view the docs locally as described in http://v4-alpha.getbootstrap.com/getting-started/build-tools/#local-documentation
