### ISSUE TITLE
Request to change .btn-outline-primary/info/warning/* to just .btn-outline

### ISSUE THREAD

**Issue by grvsooryen** [twbs/bootstrap#19764]
Hello,

I thought about button outline and realised that toggling .btn-outline is better that switching .btn-outline-danger to .btn-danger while changing the parent background. my suggestion is to use .btn-outline like below for v4.

.btn-primary.btn-outline {
  ...
}
.btn-danger.btn-outline {
  ...
}
...

**Comment by cvrebert** [comment]
This suggestion runs counter to our class naming scheme; see http://codeguide.co/#css-selectors and http://markdotto.com/2012/02/16/scope-css-classes-with-prefixes/
And it would require more overrides in our CSS, which we usually try to avoid.
CC: @mdo

**Comment by mdo** [comment]
Yup, sticking with separate classes for now.

**Comment by grvsooryen** [comment]
Sounds Reasonable.

Thank you
