### ISSUE TITLE
Cross-browser compatibility (OS X Safari)

### ISSUE THREAD

**Issue by progcode** [twbs/bootstrap#19763]
The default bootstrap select & input form elements are broken in Safari (8/9 OSX Yosemite / El Capitan). 

**Screenshots:**

Safari 8/9 (OSX Yosemite / El Capitan:)
![safari_select](https://cloud.githubusercontent.com/assets/5430762/14632066/df32702e-0616-11e6-8ab9-73e61dfa042b.png)
![safari_select2](https://cloud.githubusercontent.com/assets/5430762/14632068/df69ed6a-0616-11e6-933e-959cc228abeb.png)

Windows10 Chrome:
![windows_select](https://cloud.githubusercontent.com/assets/5430762/14632073/e961eebc-0616-11e6-8f72-2ae320ae154b.png)
![windows_select2](https://cloud.githubusercontent.com/assets/5430762/14632074/e988cf32-0616-11e6-8672-bd763780211e.png)

Please support  pure-css cross-browser compatiblity!

**Comment by blakestoddard** [comment]
I do recall reading something about Safari (and iOS iirc) forcing their own browser-side styling, which is what you're seeing. You also didn't say which version of Bootstrap you are referring to, however the v4-alpha has different styling of selects, so I'm assuming you're talking about 3.x.x.

**Comment by progcode** [comment]
Boostrap 3.3.6, but this not work any other versions, too

**Comment by cvrebert** [comment]
@progcode I don't see what breakage you're referring to. Please describe the breakage in words.

**Comment by patrickhlauke** [comment]
@cvrebert i suspect the "breakage" is "it doesn't look the same". which is to be expected, as we don't fake non-native selects, but just rely on the platform's own select implementation ... so I think this is not a bug, so a won't-fix

**Comment by cvrebert** [comment]
Yeah, platform-native form controls are a feature, not a bug.
If you want absolute uniformity rather than nativeness, use http://v4-alpha.getbootstrap.com/components/forms/#custom-forms or http://wtfforms.com or similar.
If we've misunderstood you somehow, we'll be happy to reopen this.
