### ISSUE TITLE
http://v4-alpha.getbootstrap.com/about/accessibility returns 404

### ISSUE THREAD

**Issue by vantienhoven** [twbs/bootstrap#19761]
Hi Guys,

Not sure if this is correct , but the following link returns a 404: 

http://v4-alpha.getbootstrap.com/about/accessibility

Thank you, Sacha

**Comment by RyanZim** [comment]
Duplicate of #19540; Please close this.

**Comment by patrickhlauke** [comment]
indeed. and fixed already in https://github.com/twbs/bootstrap/pull/18819
