### ISSUE TITLE
.form-control-{sm,lg} height sizing classes don't work on <select>s

### ISSUE THREAD

**Issue by delakanda** [twbs/bootstrap#19771]
i am trying to apply the class form-control-sm to make my select element smaller. it doesnt seem to work.
i tried form-control-lg too and there is no visual change.

**Comment by cvrebert** [comment]
@delakanda 
What browser and OS are you using?
Please post a JS Bin that demonstrates the problem.

**Comment by delakanda** [comment]
@cvrebert 
I am using google chrome Version 50.0.2661.75 (64-bit) on ubuntu 15.10

here is the JS bin link:
https://jsbin.com/vacadozega/edit?html,output

It however seems that the form-control-sm class only seems to affect the text inside the 'select' eleme nt and not the size of the element itself

**Comment by twbs-lmvtfy** [comment]
Hi @delakanda!

You appear to have posted a live example (https://jsbin.com/vacadozega/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 12, column 7 thru column 26: The ```` name ```` attribute on the ```` option ```` element is obsolete. Use the ```` id ```` attribute instead.
* line 13, column 7 thru column 31: The ```` name ```` attribute on the ```` option ```` element is obsolete. Use the ```` id ```` attribute instead.
* line 14, column 7 thru column 32: The ```` name ```` attribute on the ```` option ```` element is obsolete. Use the ```` id ```` attribute instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Reposting to trigger revalidation: https://jsbin.com/walamozoxa/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/walamozoxa/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Okay, that particular warning should be safe to ignore.

**Comment by cvrebert** [comment]
Possible cause: https://github.com/twbs/bootstrap/issues/17194#issuecomment-187660696

**Comment by mdo** [comment]
Tacked onto #19141.
