### ISSUE TITLE
Flex with white-space for text-overflow

### ISSUE THREAD

**Issue by stafast** [twbs/bootstrap#19770]
If a inner container is using white-space: nowrap for text-overflow, this container is break out.
I found this solution: [Link](http://stackoverflow.com/questions/34934586/white-space-nowrap-and-flexbox-did-not-work-in-chrome)

I just add to _grid-framework.scss line 8:
@if $enable-flex {
 min-width: 0px;
}

**Comment by ItsJonQ** [comment]
I've experienced weirdness with flexbox and CSS text truncation. Not just with Bootstrap, but in general.

The solution you found is one I use myself, but there's a gotcha to it.

If you enable flexbox with Bootstrap `v4`, and you apply your fix, the following will work:

```
<div class="col-1">
  <div class="text-truncate">This works</div>
</div>
```

However, this does not (with flex):
```
<div class="col-1 text-truncate">
  This doesn't work
</div>
```

Again, I think the fix you suggested is valid :).
But the user would have to be mindful of where to add CSS truncating, whether it's via `.text-truncate` or with some other method.

Maybe it can be clarified/outlined in the docs?

Hope this helps!

**Comment by mdo** [comment]
Closing since this sounds like it's not exactly a Bootstrap bug.
