### ISSUE TITLE
Ul LI list-inline do not work 

### ISSUE THREAD

**Issue by Ere00** [twbs/bootstrap#19776]
This works in 3.3.6 (tested) version but not in Alpha 4

In Alpha 4 it removes styles but do not arrange them to horizontal 

Tested list: 

 ```
 <ul class="list-inline">
    <li>LINKKI</li>
    <li>LINKKI</li>
    <li>LINKKI</li>
    <li>LINKKI</li>
    <li>LINKKI</li>
    <li>LINKKI</li>
  </ul>
```

**Comment by patrickhlauke** [comment]
There is currently no inline list construct for v4 http://v4-alpha.getbootstrap.com/content/reboot/#lists (compare to v3 http://getbootstrap.com/css/#inline)

**Comment by Ere00** [comment]
There is, [http://v4-alpha.getbootstrap.com/content/typography/#inline]
and I did not use it right. It works now (haz dumz)
I works now !

**Comment by sagive** [comment]
i dont understand why did they added that foolish class to LI items. WHY!?! Overmark example of the year.
