### ISSUE TITLE
anchor text misaligned in .form-horizontal>.form-group

### ISSUE THREAD

**Issue by user414** [twbs/bootstrap#19777]
Exactly the same as here

https://github.com/twbs/bootstrap/issues/8150

but if you use an anchor instead of just a p element. Adding static-form-control does not do anything on an anchor tag.

**Comment by RyanZim** [comment]
I assume you're using v3.

The reason for your problem is that `<a>` is an inline element, while `<p>` is a block element. The docs specifically state:

> use the `.form-control-static` class on a `<p>`.

If you want your plain text linked, you would do:
```
<p class="form-control-static"><a href="http://example.com/">email@example.com</a></p>
```

If this fixes your problem, please close this.

**Comment by user414** [comment]
@RyanZim Thanks, that was so obvious I never thought of it. May I suggest changing and/or adding the example in the doc here

https://getbootstrap.com/css/#forms-controls-static

to have an anchor with mailto, since it is already an email in the example I feel perhaps that would be a better example then the current one. Thanks again.

**Comment by RyanZim** [comment]
CC: @cvrebert for decision regarding adding an example to the docs.

**Comment by cvrebert** [comment]
Eh, I don't think folks normally hyperlink login email addresses in login/confirmation screens such as the example in question.
