### ISSUE TITLE
.card-img-top and .card-img-bottom missing when $enable-rounded is false

### ISSUE THREAD

**Issue by hongymagic** [twbs/bootstrap#19782]
**Problem**

When you compile bootstrap v4 with `$enable-rounded` set to false, the `.card-img-*` classes are completely omitted.

These [two top-level declarations](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L198) print nothing when `border-radius` function is called with `$enable-rounded` is set to false.

Same is also true for `.card-deck-wrapper` and `$enable-flex = true`. I personally think `.card-deck-wrapper` being omitted conditionally is a bug too.

---

I found this issue while `@including 'bootstrap.scss'` and `@extending` existing classes i.e., above.

**Comment by cvrebert** [comment]
Unless it results in incorrect rendering, the `.card-img-*` case doesn't sound like a bug.
@hongymagic Does the result still render correctly visually?

---

> I personally think `.card-deck-wrapper` being omitted conditionally is a bug too.

Nope. It's unnecessary when Flexbox is enabled:

> [ProTip! If you enable flexbox mode, you can remove the `.card-deck-wrapper`.](http://v4-alpha.getbootstrap.com/components/card/#decks)

**Comment by hongymagic** [comment]
> Does the result still render correctly visually?

Yes, visually correct.

I'm assuming then, the usage notes for SASS is to _not_ assume existence of classes that are turned on/off by custom variables even though they may not seem obvious. Assuming, that's the case, happy for this to be closed.

Thanks!
