### ISSUE TITLE
v4: .dropdown-header has margin-bottom

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#19784]
Bootstrap 2.3.2 and 3 nav headers (and now dropdown-header) kept tight to the items listed below them:

http://getbootstrap.com/2.3.2/components.html#nav-lists

http://getbootstrap.com/components/#dropdowns-headers

...just 3px of padding top and bottom, no margin

v4 however keeps the 8px or .5 Rem margin added by the H6 plus the 3px of padding top and bottom and as a result its distanced away from the sub-items:

http://v4-alpha.getbootstrap.com/components/dropdowns/#menu-headers

If this purely a function of using H6 for the header (ergo, I should be using another element) or an item that needs to be addressed in the styles?

Thank you =)

**Comment by cvrebert** [comment]
`.nav-header` was killed after v2. Going to assume you meant `.dropdown-header`

**Comment by bellwood** [comment]
@cvrebert: that is correct, thank you for the correct =)

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by ItsJonQ** [comment]
Hi hi :)

Is it safe to add `margin-bottom: 0;`  to act as a "reset" to `.dropdown-header`?
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_dropdown.scss#L142

It should work with other heading sizes as well, if the user chooses to not use `<h6>`.

**Comment by bellwood** [comment]
@ItsJonQ a suitable work around for the time being would be to add the class **m-b-0** to the dropdown-header to reset the margin

**Comment by ItsJonQ** [comment]
@bellwood adding that definitely works as a work around :)

But if a specific class for `.dropdown-header` exists, then the styling (color, sizing, margin) should be consistent.

I can't really imagine a use-case where you'd want extra padding on the bottom of it (if you were to favour heading tags)

I think the default should be `margin: 0`, and if you wanted to add extra margin, you can add one of the margin utility classes.

I hope that thinking makes sense 💃

**Comment by bellwood** [comment]
@ItsJonQ agreed and thats why its a confirmed bug and will be addressed
