### ISSUE TITLE
Collapse plugin not finding trigger when targeting a class or multiple ids

### ISSUE THREAD

**Issue by Xabis** [twbs/bootstrap#19780]
Potential fix: PR  #19779

When a collapse panel is targeting either a class or a comma separated list of ids, the trigger's class and aria attributes are not updated.

Use case 1, "class":
```html
<ul>
   <li>item</li>
   <li>item</li>
   <li>item</li>
   <li class="mylist collapse">item</li>
   <li class="mylist collapse">item</li>
   <li class="mylist collapse">item</li>
</ul>
<button type="button" data-toggle="collapse" data-target=".mylist">show/hide</button>
```

Use case 2, "multliple ids":
```html
<ul id="mylist1">
   <li>item</li>
   <li>item</li>
   <li>item</li>
</ul>
<ul id="mylist2">
   <li>item</li>
   <li>item</li>
   <li>item</li>
</ul>
<button type="button" data-toggle="collapse" data-target="#mylist1,#mylist2">show/hide all</button>
```

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
