### ISSUE TITLE
import bootstrap Error: Incompatible units: 'px' and 'em'  when compiling bootstrap.scss

### ISSUE THREAD

**Issue by allencoded** [twbs/bootstrap#19785]
Using Gulp-Sass and trying to compile the bootstrap 4 sass, but running into an error.

```
Error: Incompatible units: 'px' and 'em'.
        on line 38 of node_modules/bootstrap/scss/mixins/_breakpoints.scss
>>   @return if($next, breakpoint-min($next, $breakpoints) - 1px, null);

```
Gulp:
```
gulp.task('sass:compile', () =>
  gulp.src([paths.sass])
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', function (e) {
      reportError(e);
      this.emit('end');
    }))
    .pipe(autoprefixer({
      browsers: ['last 2 versions'],
      cascade: false,
    }))
    .pipe(sourcemaps.write('./maps'))
    .pipe(gulp.dest(`${paths.webroot}/css`))
);
```

I have the latest gulp-sass installed:
```
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
```

My Sass is just doing a simple import:
`@import "../node_modules/bootstrap/scss/bootstrap.scss";`

**Comment by cvrebert** [comment]
Unable to reproduce with current [`v4-dev`](https://github.com/twbs/bootstrap/tree/v4-dev).
For personal support requests, please use StackOverflow, IRC, or Slack; see https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community for links.

**Comment by allencoded** [comment]
I am on alpha 2 not v4-dev branch.

**Comment by cvrebert** [comment]
`v4-dev` is newer than alpha 2.
