### ISSUE TITLE
Active nav tab acquires border-bottom when beneath two tables

### ISSUE THREAD

**Issue by robertandrews** [twbs/bootstrap#19794]
Here is a weird Bootstrap 4 problem that occurs only on Chrome Version 50.0.2661.86 (64-bit), not iOS Safari or Mac OS X Safari...

I am trying to show a tabbed nav (class="nav nav-tabs") beneath a table, with a vertical space.

When I use "`<p>&nbsp;</p>`" as the spacer, the tabs render correctly. But this is too much space. I prefer to use "`<br />`".

However, when I use "`<br />`", the first, "Active" tab acquires a horizontal line on its bottom edge. That's wrong.

It looks like this:

http://i.imgur.com/DTInKY2.png

Here is the code. Although I don't see the problem in the JSFiddle, it's fine there, just on my site itself (not very helpful?)...

https://jsfiddle.net/iamrobertandrews/ndkmw1te/

The problem is evident in Chrome, but not on Safari in either iOS or Mac OS X.

I hope the problem is not my markup.

I can't explain the issue any further.

**Comment by twbs-lmvtfy** [comment]
Hi @robertandrews!

You appear to have posted a live example (https://fiddle.jshell.net/iamrobertandrews/ndkmw1te/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 55, column 1 thru column 15: Stray doctype.
* line 56, column 1 thru column 19: Stray start tag ```` html ````.
* line 57, column 1 thru column 6: Stray start tag ```` head ````.
* line 58, column 3 thru column 24: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 58, column 3 thru column 24: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 59, column 3 thru column 70: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 59, column 3 thru column 70: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 60, column 3 thru column 52: Element ```` link ```` is missing required attribute ```` property ````.
* line 61, column 3 thru column 69: Element ```` link ```` is missing required attribute ```` property ````.
* line 64, column 3 thru column 218: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 64, column 3 thru column 218: Element ```` link ```` is missing required attribute ```` property ````.
* line 65, column 3 thru column 73: Element ```` link ```` is missing required attribute ```` property ````.
* line 66, column 3 thru column 108: Element ```` link ```` is missing required attribute ```` property ````.
* line 68, column 3 thru column 9: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 69, column 1 thru column 124: Element ```` link ```` is missing required attribute ```` property ````.
* line 70, column 1 thru column 142: Element ```` link ```` is missing required attribute ```` property ````.
* line 71, column 1 thru column 164: Element ```` link ```` is missing required attribute ```` property ````.
* line 76, column 3 thru column 25: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 90, column 1 thru column 162: Element ```` link ```` is missing required attribute ```` property ````.
* line 91, column 1 thru column 77: Bad value ```` https://api.w.org/ ```` for attribute ```` rel ```` on element ```` link ````: The string ```` https://api.w.org/ ```` is not a registered keyword.
* line 91, column 1 thru column 77: Element ```` link ```` is missing required attribute ```` property ````.
* line 92, column 1 thru column 111: Element ```` link ```` is missing required attribute ```` property ````.
* line 93, column 1 thru column 124: Element ```` link ```` is missing required attribute ```` property ````.
* line 94, column 1 thru column 49: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 94, column 1 thru column 49: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 96, column 3 thru column 25: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 97, column 3 thru column 88: Start tag ```` body ```` seen but an element of the same type was already open.
* line 97, column 3 thru column 88: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by robertandrews** [comment]
All of the above validation errors have now been corrected.

**Comment by RyanZim** [comment]
@robertandrews: I stripped your example down to just the basics: https://jsfiddle.net/co0oqtm4/1/. Could you copying the code into an html file and see if you can reproduce it locally? (I don't have OS X)

**Comment by robertandrews** [comment]
@RyanZim Thanks.
1. As your fragment only pertained to the tabs themselves, when I deploy only that (with header code), there is no rendering problem - no lower line shows.
2. When I add back in the two tables above the tabs (attempting to reproduce the error), the bottom border is still absent, as it should be. Here is that code - https://jsfiddle.net/iamrobertandrews/ry7xr1ow/ So maybe there is something amiss in my code... ie. the media-object part, the sidebar... ?

**Comment by twbs-lmvtfy** [comment]
Hi @robertandrews!

You appear to have posted a live example (https://fiddle.jshell.net/iamrobertandrews/ry7xr1ow/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 54, column 3 thru column 17: Stray doctype.
* line 55, column 1 thru column 19: Stray start tag ```` html ````.
* line 56, column 1 thru column 6: Stray start tag ```` head ````.
* line 57, column 3 thru column 24: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 57, column 3 thru column 24: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 58, column 3 thru column 70: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 58, column 3 thru column 70: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 59, column 3 thru column 52: Element ```` link ```` is missing required attribute ```` property ````.
* line 60, column 3 thru column 69: Element ```` link ```` is missing required attribute ```` property ````.
* line 63, column 3 thru column 218: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 63, column 3 thru column 218: Element ```` link ```` is missing required attribute ```` property ````.
* line 64, column 3 thru column 73: Element ```` link ```` is missing required attribute ```` property ````.
* line 65, column 3 thru column 108: Element ```` link ```` is missing required attribute ```` property ````.
* line 67, column 3 thru column 9: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 68, column 1 thru column 124: Element ```` link ```` is missing required attribute ```` property ````.
* line 69, column 1 thru column 142: Element ```` link ```` is missing required attribute ```` property ````.
* line 70, column 1 thru column 164: Element ```` link ```` is missing required attribute ```` property ````.
* line 75, column 3 thru column 25: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 89, column 1 thru column 162: Element ```` link ```` is missing required attribute ```` property ````.
* line 90, column 1 thru column 77: Bad value ```` https://api.w.org/ ```` for attribute ```` rel ```` on element ```` link ````: The string ```` https://api.w.org/ ```` is not a registered keyword.
* line 90, column 1 thru column 77: Element ```` link ```` is missing required attribute ```` property ````.
* line 91, column 1 thru column 111: Element ```` link ```` is missing required attribute ```` property ````.
* line 92, column 1 thru column 124: Element ```` link ```` is missing required attribute ```` property ````.
* line 93, column 1 thru column 49: Attribute ```` name ```` not allowed on element ```` meta ```` at this point.
* line 93, column 1 thru column 49: Element ```` meta ```` is missing one or more of the following attributes: ```` itemprop ````, ```` property ````.
* line 95, column 3 thru column 25: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 96, column 3 thru column 78: Start tag ```` body ```` seen but an element of the same type was already open.
* line 96, column 3 thru column 78: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by RyanZim** [comment]
@robertandrews 
> So maybe there is something amiss in my full code

That's what I suspect.

BTW, JSFiddle doesn't require the `<head>` or `<body>` tags; use "External Resources" (in the sidebar) to include bootstrap.

**Comment by robertandrews** [comment]
Any pointers on how I can get a hand de-bugging my code before, assuming it is not a Bootstrap 4 bug, this issue is closed?
Thanks.

**Comment by RyanZim** [comment]
@robertandrews have you tried [bootlint](https://github.com/twbs/bootlint)? Of course, you should try https://html5.validator.nu/ as well.

**Comment by mdo** [comment]
This is likely a browser rendering issue mixed with some of our older code. When components render on a half or fraction of a pixel, they can sometimes get messed up. This was worse when we were using `rem`s as our border units, too.

If this is still an issue with the latest from the `v4-dev` branch, please give us a holler.
