### ISSUE TITLE
xs-offset isn't working how it suppose to work

### ISSUE THREAD

**Issue by kaminaze** [twbs/bootstrap#19798]
The xs-offset will ignore the media screen all will add offset to the element no matter the size of the browser.
But this isn't how it suppose to work:
[grid::options](http://getbootstrap.com/css/#grid-options)

**Comment by RyanZim** [comment]
`.col-*-offset-*` classes offset the column at the given breakpoint and larger. For example, `.col-offset-sm-*` will offset the column when the viewport is 768px or larger.

The docs say:

> You can also override offsets from lower grid tiers with `.col-*-offset-0` classes.

For example, if you want the column to be offset only at the `xs` breakpoint, you would do something like:
```
<div class="col-xs-4 col-xs-offset-2 col-sm-offset-0"></div>
```
See it live: https://jsfiddle.net/264sty8y/

**Comment by kaminaze** [comment]
That makes sense.I asked because I couldn't find it on the documentation and I assumed it will only stay when the viewport is lower or equal to xs.

**Comment by RyanZim** [comment]
Docs are at: http://getbootstrap.com/css/#responsive-utilities-classes. Please close this issue. Thanks.
