### ISSUE TITLE
Modal dialog with close link

### ISSUE THREAD

**Issue by Dimigergo** [twbs/bootstrap#19799]
I have a modal dialog with a Google sign in link. I would like to close the dialog, when the user clink the link.

The button is the following link:
`
<a id="lnkGoogleLoginAdd" href="#" class="btn btn-block btn-social btn-google">
    <span class="fa fa-google"></span>
    <div data-i18n="accounts.add_modal.lnk_google_login"></div>
</a>
`

I have tried the following steps:
1. data-dismiss="modal" parameter, but it is not worked for me.
2. $('#addAccountModal').modal('hide'); in the click event. It hides the dialog, but the body remains disabled.
3. After close the dialog I have tried: $("#mainBody").removeClass("modal-open"); but it took no effect.

Thank you very much.

**Comment by RyanZim** [comment]
`data-dismiss` works for me: http://jsbin.com/luhofexiha/edit?html,output

A side note: where does the `<a>` element link to?

**Comment by Dimigergo** [comment]
Ok, sorry that is my mistake.

I have used a click event handler, which reloads the container page ($(".custom-container").load("<whatever page>")), and there was the problem.

My workaround solution is that I use the same code, but not in the click event, but the 'hidden.bs.modal' event.

Thanks!

**Comment by RyanZim** [comment]
@Dimigergo No problem. Please close this issue.
