### ISSUE TITLE
Docs: "auto" is not a valid tooltip placement option

### ISSUE THREAD

**Issue by Tiendq** [twbs/bootstrap#19796]
Currently Bootstrap only allow 4 values for placement option: top, bottom, left, right. "auto left" as explained in the document is an incorrect value and will cause error "Tether Error: You must provide an attachment".

http://v4-alpha.getbootstrap.com/components/tooltips/

**Comment by eriksendc** [comment]
Why is auto not a valid option? It would be very helpful to have it. I the meantime, the online bootstrap 4 docs are still wrong.

**Comment by karlschwaier** [comment]
Placement auto has been removed from the tooltip docs, but it is still mentioned in the popover docs.
http://v4-alpha.getbootstrap.com/components/popovers/#options

**Comment by str** [comment]
It's been a year since this issue. Was issue "auto" not suported? Or was it that the documentation is wrong? I feel many of us want he "auto" placement to be a valid flag, instead of fixing the documentation.
