### ISSUE TITLE
Tooltip size recalculated by browser

### ISSUE THREAD

**Issue by mpec** [twbs/bootstrap#19797]
There is an issue (probably related somewhat to our internal css in the project) that the tooltip after all the position calculations are done changes it's width and then renders incorrectly. Unfortunately I can't reproduce it easily without our source code. Do you still take pull requests for v3? I'm not sure if the fix is pull request material (I'm forcing min-width if it's not set already). The change in size happens when we call 'applyPlacement' method.

**Comment by cvrebert** [comment]
> Do you still take pull requests for v3?

In general, we still accept bugfix pull requests for it, but we've mostly given up on v3 tooltip positioning bugs; see https://github.com/twbs/bootstrap/issues/15590#issuecomment-113321235
