### ISSUE TITLE
embed-responsive4by3 not working in a modal in 3.3

### ISSUE THREAD

**Issue by eccebozo** [twbs/bootstrap#19801]
We just upgraded bootstrap in our application, and I've found that an object tag inside a modal in which we're displaying a PDF is not sized correctly.  As we didn't make any changes except for the upgrade, I swapped out the old version and found that 3.0 had .embed-responsive-4by3.embed-responsive{ padding-bottom:75%;}, while 3.3 has just .embed-responsive-4by3{ padding-bottom:75%;}.

What I'm guessing is happening is that with the dual class selection, the old one was a more specific selector and therefore was taking precedence.  With the new one, the .modal-body selector seems to have precedence, and so I'm only getting a bottom padding of 15px.

My tag:
`<div class="modal-body embed-responsive embed-responsive-4by3"><object class="embed-responsive-item" id="pdfObject" data="/myapp/method/id" type="application/pdf">Unable to display the document</object></div>`

Is this a bug, or am I supposed to be structuring something differently?  For now, I'll throw in a workaround.  Thanks

**Comment by RyanZim** [comment]
I would structure it:
```
<div class="modal-body">
  <div class="embed-responsive embed-responsive-4by3">
     <object class="embed-responsive-item">Unable to display the document</object>
  </div>
</div>
```
You can rarely combine `.embed-resposive` with other classes.

**Comment by eccebozo** [comment]
Yep, suggested restructuring works.  Thanks!
