### ISSUE TITLE
Minified file throwing "ParseError: Unrecognised input"

### ISSUE THREAD

**Issue by ericmmartin** [twbs/bootstrap#19802]
With 3.3.6, I get a `ParseError: Unrecognised input.` error during my build process. I am concatenating all 3rd party libs into a single file. The error is thrown when that concatenated file is being parsed. **This is not an issue with 3.3.2.**

The issue appears to be related to the minified dropup code from dropdowns.less:
```
.dropup,
.navbar-fixed-bottom .dropdown {
  // Reverse the caret
  .caret {
    border-top: 0;
    border-bottom: @caret-width-base dashed;
    border-bottom: @caret-width-base solid ~"\9"; // IE8
    content: "";
  }
  // Different positioning for bottom up menu
  .dropdown-menu {
    top: auto;
    bottom: 100%;
    margin-bottom: 2px;
  }
}
```

Turns into this in dist/boostrap.css (not sure why the order changes)
```
.dropup .caret,
.navbar-fixed-bottom .dropdown .caret {
  content: "";
  border-top: 0;
  border-bottom: 4px dashed;
  border-bottom: 4px solid \9;
}
```

Which turns into:
`.dropup .caret,.navbar-fixed-bottom .dropdown .caret{content:"";border-top:0;border-bottom:4px dashed;border-bottom:4px solid\9}`

If I insert a semi-colon after the \9 in the minified file, the problem goes away. I'm not sure why the order changes, but the \9} seems to be causing an issue.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
