### ISSUE TITLE
Confusion: jquery v1.11.3 is recommended in starter-template, but jquery v2.2.3 is installed with bootstrap via bower by default?

### ISSUE THREAD

**Issue by wbin666** [twbs/bootstrap#19808]
Hi,
I use bower to get the bootstrap v3.3.6 installed with jquery v2.2.3.  But I found the jquery v1.11.3 is recommended in the starter-template/index.html file.  
should I update the starter-template to use jquery v2.2.3?   or should I downgrade the jquery to v1.11.3 via bower.   Which is better? and why?

Thanks for your help.

**Comment by wolfy1339** [comment]
They are both compatible versions with Bootstrap. jQuery 1.x is compatible with IE 6/7/8 while the lather is not
