### ISSUE TITLE
Clicking scrollbar in <select multiple> with overflowed options will select nearby <option> in Chrome

### ISSUE THREAD

**Issue by wengjs** [twbs/bootstrap#19810]
I use chrome v50.0.2661.87 m.

While option text overflowed, user could select option every single clicking on scrollbar.

Does anyone could reproduce this issue?

Here is the sample code:
https://jsfiddle.net/umt87ojo/1/

And finally I found if:
```
select > option {
  overflow-x:hidden;
}
```

and problem solved!!!!

**Comment by RyanZim** [comment]
Clarification: This only happens with `<select class="form-control" multiple>`.

Confirmed in Chrome; all other browsers seem to work fine (I didn't check Opera).

Here is a JSFiddle demonstrating the suggested change: https://jsfiddle.net/a3rkua5p/. I tested this in all browsers (except Opera) and didn't notice any adverse effects. The change does not affect `<select>` without the `multiple` attribute.

:+1: for implementing this. Perhaps we should also report this to Chrome as this is inconsistent with other browsers.

**Comment by RyanZim** [comment]
On second thought, perhaps this is within the scope of [normalize.css](https://github.com/necolas/normalize.css).

CC: @necolas @jonathantneal

**Comment by cvrebert** [comment]
Confirmed in OS X Chrome. Doesn't happen with in a fiddle with only Normalize.css loaded, so something in Bootstrap must be triggering this. Definitely seems like Chrome itself has a bug though.
@RyanZim Did you test in Chrome on Windows or Linux by any chance?

**Comment by slavanga** [comment]
Confirmed in the latest Chrome on Windows.
The effect seems to be triggered by the border-radius from the .form-control class.

**Comment by cvrebert** [comment]
Confirmed that removing the `border-radius` restores sane behavior.
I'll file a Chrome bug tomorrow.

**Comment by RyanZim** [comment]
@cvrebert I did my cross-browser testing on Windows. I'll try to do some testing in Linux later today.

**Comment by RyanZim** [comment]
On Linux (Lubuntu), I cannot reproduce with chrome 48.0.2564.116. My Linux box is 32-bit so I can't test with later releases of Chrome. :disappointed:

**Comment by cvrebert** [comment]
Going to assume this is cross-platform since both Windows and OS X are affected.

**Comment by cvrebert** [comment]
Known Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=597642

**Comment by Herst** [comment]
> Known Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=597642

Has been "WontFix"ed because it apparently cannot be reproduced anymore.
