### ISSUE TITLE
Modal events not working

### ISSUE THREAD

**Issue by sirEgghead** [twbs/bootstrap#19818]
I'm having trouble getting the content of my modal window to change.  I eliminated all the variables for testing.  I have attached my HTML file.  Line 220 is the button that summons my modal window.  The modal shows.  Line 243 begins my modal editor script block.

I went ahead and attached my jquery.js, bootstrap.js and bootstrap.css files since I host them locally.  Should be standard though, I would think.
[modal.zip](https://norandomzipfiles.github.com/twbs/bootstrap/files/241275/modal.zip)

And a screenshot of my modal:
![image](https://cloud.githubusercontent.com/assets/6648625/14898444/baaf2ffe-0d54-11e6-88a3-1be14ba398c7.png)

Thanks!  :)

**Comment by sirEgghead** [comment]
I just figured out that if I put my modal edit as the last thing before my </body> tag, it works fine.  So I've gotten it fixed, but I'd still like to know why.  :)

**Comment by patrickhlauke** [comment]
if you suspect this is a bug in Bootstrap, please provide a live minimal test case using something like jsfiddle.

if, however, this is more of a support/how to question, then please direct it at Stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by RyanZim** [comment]
Simple: your js on line 243 uses jquery, so it needs to be loaded after jquery. jquery is not loaded until line 264 in your example.

Please close this.

BTW, next time use a JSBin instead of a file upload. Thanks!
