### ISSUE TITLE
https://themes.getbootstrap.com/products/dashboard and AdBlockPlus

### ISSUE THREAD

**Issue by fulldecent** [twbs/bootstrap#19816]
FYI. Loading this page 

 > https://themes.getbootstrap.com/products/dashboard

fails in Mac / Chrome with ABP installed.

**Comment by RyanZim** [comment]
> Please **do not** open issues regarding the official themes offered on <http://themes.getbootstrap.com/>.
  Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`.

https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Thanks.

**Comment by fulldecent** [comment]
Thank you, sorry. I have sent the message to that email.
