### ISSUE TITLE
71 commits in 2016 – is dev slowing down?

### ISSUE THREAD

**Issue by bjornte** [twbs/bootstrap#19815]
I depend on Bootstrap for all my front end projects (and am a great fan!) and would like to start using [flexbox](http://v4-alpha.getbootstrap.com/getting-started/flexbox/), which is v4 only. However alpha 2 is too buggy for my current `form`-heavy project. So I'm wondering when we can hope to expect alpha 3. The [Graphs tab](https://github.com/twbs/bootstrap/graphs/contributors?from=2016-01-01&to=2016-04-28&type=c) shows 71 commits so far this year, mostly by @cvrebert and none by @fat or @mdo. Is this a bad sign?

I understand that Bootstrap is probably a volunteer project for all involved so I don't mean to complain, rather the opposite, it's a fantastic tool with great support & documentation, I really love it.

[Related thread](https://www.reddit.com/r/bootstrap/comments/4emn07/anyone_have_an_idea_of_when_bootstrap_4_is_being/) on Reddit.

**Comment by afuno** [comment]
@mdo was a vacation, apparently :)
April 26, he made two commit. After a long period of time.

**Comment by rafalp** [comment]
Please don't judge development pace by commits number. Bootstrap dev happens on PR's that are squashed before the merge, so stats are very mistaking here.

**Comment by patrickhlauke** [comment]
And there are separate private repos for some of the more fundamental reengineering work, which won't even show up in the stats :)

I'd suggest, however, that this is not the right place to discuss this. May I suggest Slack or similar? See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by bjornte** [comment]
Thanks @rafalp. I'm quite new to GitHub so that might be the case. Looking at the aforementioned graph, however, the trend suggests a slowdown, so a confirmation from the main committers would be nice.

And thanks @patrickhlauke for the link!

<sub>(Having said that, @mdo is now "Director of Design at GitHub" [according to](https://twitter.com/mdo?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) his Twitter profile. With that background, @mdo, is it possible for GitHub to give newbies like me better insight into "offline" work? I'm assuming @rafalp means pull requests when he writes PR, and that related work happens on a local computer or similar – but since you have a desktop client, perhaps some trend-like analysis might be done even for local work? Or perhaps a "progress calculator", e.g. "based on historic rates for this project, the X open issues and Y commit frequency suggests the next milestone will be met in Z days" – kind of like what you have in [JIRA](https://www.atlassian.com/software/jira).)</sub>

**Comment by rafalp** [comment]
@bjornte

> means pull requests when he writes PR, and that related work happens on a local computer or similar

As Patrick said, related work happens on private forks of main repo, and those are just that - private forks that we, little ones, have no access to.

If you are looking for way to spot changes in bootstrap, you may look at recently merged pull requests:

https://github.com/twbs/bootstrap/issues?q=milestone%3Av4.0.0-alpha.3+sort%3Aupdated-desc+is%3Aclosed

Or look at activities listed on Pulse page (it also notes that @mdo is in fact active in project):
https://github.com/twbs/bootstrap/pulse/monthly

**Comment by patrickhlauke** [comment]
(also note that "Graph" only shows activity on `master` branch, while v4 is on `v4-dev`)

**Comment by bjornte** [comment]
Again thanks for updates. The takeaway, it seems, is that for programmers not active on GitHub, the graph template leads to false negatives. I think this is the case because my current client's core developers dismissed Pattern Lab because [their graph](https://github.com/pattern-lab/patternlab-php/graphs/contributors) makes it look stale. Neither my client nor I understood what the graph template doesn't show. Would be nice with a heads up on the template.

**Comment by patrickhlauke** [comment]
> Would be nice with a heads up on the template.

you'll need to ask github for that, not us... ;)

**Comment by bellwood** [comment]
Correct, pulse operates on the default branch of a project as indicated here:

https://help.github.com/articles/about-pulse/
