### ISSUE TITLE
Affix doesn't recheck position on touchmove

### ISSUE THREAD

**Issue by pixiebox** [twbs/bootstrap#19811]
affix.js works on tablets but only when scroll ends.
Please add touchmove `.on('touchmove.bs.affix.data-api', $.proxy(this.checkPosition, this))` around line 20

**Comment by pixiebox** [comment]
It happends on one of the latest apple tablet, I've tried it with Chrome and Safari. And it might be a bug on their side but I guess a touchmove isn't that bad to add as a fallback for scroll.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
