### ISSUE TITLE
Update textbox based on populated list of bootstrap typeahead

### ISSUE THREAD

**Issue by VikashKumarRP** [twbs/bootstrap#19821]
I am running one application where i used bootstrap typeahead, which is using ajax call to get data and  auto populate to user. when user select any item in populate list using down arrow key then based on that textbox value should change based on the selected text. I have one link where you can see user select any item in list based on that textbox value is changing. [This is the link](http://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=typeahead-with-local-dataset).

in this example local data is used to populate.
Need the same functionality with mine also.

**Comment by patrickhlauke** [comment]
Note that typeahead is not a component of bootstrap 3 anymore http://getbootstrap.com/javascript/

For how-to/support questions, please use StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by patrickhlauke** [comment]
(or if you're using bootstrap-3-typeahed, please visit the relevant repo https://github.com/bassjobsen/Bootstrap-3-Typeahead)
