### ISSUE TITLE
Dropdowns on Getbootsrap.com/components not working

### ISSUE THREAD

**Issue by IOIIOOIO** [twbs/bootstrap#19820]
Hi I'm not sure where else to leave this, but I noticed your dropdown demo isn't working here:

http://getbootstrap.com/components/

I'm browsing with Chrome Version 49.0.2623.112 m

**Comment by patrickhlauke** [comment]
can't reproduce, they work fine for me (Version 50.0.2661.94 m (64-bit))

**Comment by RyanZim** [comment]
@patrickhlauke At http://getbootstrap.com/components/#dropdowns-example, the first example is already expanded when the page loads and clicking on the dropdown button has no effect. I'm not sure if this is intended behavior or not.

Windows 7 & Firefox 46.0

**Comment by patrickhlauke** [comment]
oh THAT? yes that's intended

**Comment by RyanZim** [comment]
OK, wasn't sure.
