### ISSUE TITLE
Modal form not showing in firefox

### ISSUE THREAD

**Issue by rocketman343** [twbs/bootstrap#19823]
Good evening, 

I'm writing a page where the login form shows up in a mode window. In Edge and Chrome all works very well but when I use Firefox and I test the site on my local machine, if I load the page using: 
" localhost/path_of_the_page" 
the page is showed but the modal form doesn't pop up, instead, if I load the page writing the whole path of the page it works.
Ex: "file///C:/path"
This obviously reflect in hosting problems, once the site is hosted, the login modal form doesn't pop up in Firefox. 
Unfortunately I don't know how to fix this issue, so I'm asking if someone knows a little more about this problem. 
I'm attaching the code of the modal form I used. 
[modal_form.txt](https://github.com/twbs/bootstrap/files/242964/modal_form.txt)

Thank you in advance!!!

**Comment by patrickhlauke** [comment]
For how-to questions, please ask on StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

(but for what it's worth, this sounds like a cross-origin problem with Firefox when running on localhost)

**Comment by rocketman343** [comment]
Excuse me for the mistake I've done publishing here, but then thank you, it was a css problem and now I solved my compatibility problems with Firefox.
