### ISSUE TITLE
Positioning of card-header-tabs with other floats

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#19822]
Tabs in card headers are really cool in v4 and while testing them extensively I've found that if another float is placed inside the card header (for example a pulled-right button), the tab list no longer lies onto the header bottom margin.

```html
<div class="card text-xs-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs pull-xs-left">
      <!-- items -->
    </ul>
    <button class="btn btn-primary pull-xs-right" type="button">Do something cool</button>
  </div>
  <div class="card-block">
    <!-- content -->
  </div>
</div>
```
![screen shot 2016-04-29 at 17 43 58](https://cloud.githubusercontent.com/assets/851745/14921513/ede0b7c4-0e32-11e6-9eda-0a6bee6f971b.png)

**Comment by RyanZim** [comment]
@heruan Apparently you didn't test this one extensively enough :grinning: 

It has nothing to do with floats, the issue is that the button is bigger than header. Adding `.btn-sm` fixes this. See a live example: https://jsfiddle.net/0xdwv2wk/.

**Comment by cvrebert** [comment]
@heruan Does @RyanZim's comment adequately address this for you?

**Comment by heruan** [comment]
It doesn't, since in my opinion card header tabs should be aligned with the bottom border regardless of the header height. They could be very useful also in rich card headers!

**Comment by RyanZim** [comment]
@heruan I agree that would be nice, but I'm not sure how you would do it.

**Comment by heruan** [comment]
It may be naïve, but I'd make the header relatively positioned and then adjust the tabs margin/position relative to it, in a way that it would stay on the header bottom edge regardless of the header's content.

**Comment by RyanZim** [comment]
@cvrebert What do you think? (Also remove `awaiting reply` label)

**Comment by cvrebert** [comment]
I'll leave this for mdo to look at.

**Comment by RyanZim** [comment]
@mdo

**Comment by mdo** [comment]
> It may be naïve, but I'd make the header relatively positioned and then adjust the tabs margin/position relative to it, in a way that it would stay on the header bottom edge regardless of the header's content.

That'd present other problems for us, namely that the `relative`/`absolute` combo you're referring to takes those tabs out of the normal flow of the document. They'd overlay other content, collapse the parent, etc. Best option I can safely give without fudging things on our end is to use negative margin on the button there, or potentially use a smaller button.

**Comment by RyanZim** [comment]
@heruan thoughts?

**Comment by heruan** [comment]
I'll use a smaller button, as @mdo suggested. Feel free to close this, unless you think there may be other means to achieve this and keep this issue as reference.

**Comment by RyanZim** [comment]
@cvrebert Ping?
