### ISSUE TITLE
Table content with multiple class

### ISSUE THREAD

**Issue by allen-infante** [twbs/bootstrap#19830]
If I have a tr["warning"] work with td[class=danger] but doesn't work with td[class=success] 

`<table class="table table-condensed">
<tr class="warning">
  <td>1</td>
  <td class="danger">2</td>
  <td>3</td>
</tr>
<tr>
  <td>4</td>
  <td>5</td>
  <td>6</td>
</tr>
</table>`

https://jsfiddle.net/3wkqy9xL/

Any advice?

**Comment by wolfy1339** [comment]
Please don't use the issue tracker for how-to questions.
Also, shohldn't you use tr.warning and td.danger and td.success anx not tr["warning"] or td[class=danger] or td[class=success]

**Comment by RyanZim** [comment]
The Contributing Guidelines say:
> Please **do not** use the issue tracker for personal support requests. Stack
  Overflow ([`twitter-bootstrap-3`](https://stackoverflow.com/questions/tagged/twitter-bootstrap-3) tag), [Slack](https://bootstrap-slack.herokuapp.com/) or [IRC](README.md#community) are better places to get help.

Please close this. Thanks!
