### ISSUE TITLE
Cross origin error 

### ISSUE THREAD

**Issue by vamsi0391** [twbs/bootstrap#19838]
Hi, how to avoid the cross origin error, I implemented this plugin in my Angular Project, It is getting error in Chrome browser while in safari it is working fine. Please suggest me any solution, Thanks.

**Comment by RyanZim** [comment]
> Please **do not** use the issue tracker for personal support requests. Stack
  Overflow ([`twitter-bootstrap-3`](https://stackoverflow.com/questions/tagged/twitter-bootstrap-3) tag), [Slack](https://bootstrap-slack.herokuapp.com/) or [IRC](README.md#community) are better places to get help.

https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

If you're referring to angular-ui/bootstrap, that is a 3rd party plugin that we cannot provide support for.

Please close this issue. Thanks!
