### ISSUE TITLE
Designing percentage based layouts using bootstrap

### ISSUE THREAD

**Issue by Matso89** [twbs/bootstrap#19835]
Bootstrap recommends using 12 columns grid for designing layout. it means every column has about 8.33% width of the parent row. this means width of elements in our layout must be multiple of the width of one column (8.3% of the parent row).

for example, I want to design the below layout for lg screens, How can I do that using bootstrap:

<img src="http://i.stack.imgur.com/roS4d.png">

**Comment by RyanZim** [comment]
> * Please **do not** use the issue tracker for personal support requests. Stack
  Overflow ([`twitter-bootstrap-3`](https://stackoverflow.com/questions/tagged/twitter-bootstrap-3) tag), [Slack](https://bootstrap-slack.herokuapp.com/) or [IRC](README.md#community) are better places to get help.

https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Please close this. Thanks!

**Comment by cvrebert** [comment]
The grid isn't intended to cover all conceivable layouts.
As noted by @RyanZim, how-to questions like this belong on other forums.
