### ISSUE TITLE
unexpected column behavior with flexbox enabled

### ISSUE THREAD

**Issue by iyel** [twbs/bootstrap#19831]
Not sure if it is a feature or a bug (i've built latest code from v4)
Example http://plnkr.co/edit/lOWg1FHZxWnDq2R5zQW5?p=preview (bootlint is freaking out because it doen't know ```col-xl-*```)

On screen size smaller than defined for column, column won't fill 100% of space
<img width="589" alt="screen shot 2016-05-01 at 11 28 42" src="https://cloud.githubusercontent.com/assets/929834/14940869/0772cf70-0f90-11e6-9e63-a9e037ffcaee.png">

By simply adding ```width: 100%``` for all columns, changes behaviour to classic

```css
[class^=col-] {
    width: 100%;
} 
```
<img width="592" alt="screen shot 2016-05-01 at 11 31 18" src="https://cloud.githubusercontent.com/assets/929834/14940875/3f614f24-0f90-11e6-97f0-3d973011ea02.png">

**Comment by twbs-lmvtfy** [comment]
Hi @iyel!

You appear to have posted a live example (http://run.plnkr.co/plunks/lOWg1FHZxWnDq2R5zQW5/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 157, column 5: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 158, column 5: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by iyel** [comment]
@twbs-lmvtfy updated example
http://plnkr.co/edit/lOWg1FHZxWnDq2R5zQW5?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @iyel!

You appear to have posted a live example (http://run.plnkr.co/plunks/lOWg1FHZxWnDq2R5zQW5/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 168, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 169, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by iyel** [comment]
@twbs-lmvtfy seems you have bug
http://plnkr.co/edit/lOWg1FHZxWnDq2R5zQW5?p=preview

**Comment by twbs-lmvtfy** [comment]
Hi @iyel!

You appear to have posted a live example (http://run.plnkr.co/plunks/lOWg1FHZxWnDq2R5zQW5/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 168, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 169, column 9: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
I believe this was addressed in Alpha 5.
