### ISSUE TITLE
Update Glyphicons version

### ISSUE THREAD

**Issue by LilyJ** [twbs/bootstrap#19836]
Bootstrap doesn't seem to have the glyphicon star-half `content: "\E507"`. Is this an oversight?

**Comment by SharkyKZ** [comment]
This is a new glyph added in 1.9.2. Glyphicons haven't been updated in Bootstrap for a while. What's the consensus on this?

**Comment by RyanZim** [comment]
Not sure. v4 removes glyphicons altogether and v3 is closed to new features, so I'm not sure.

FWIW, https://fortawesome.github.io/Font-Awesome/ is a good alternative and is recommended for v4.

**Comment by Ruffio** [comment]
Not that I'm using Glyphicons, but one could argue that it is an exitsting feature that needs to be updated to current version.

**Comment by RyanZim** [comment]
@Ruffio Yeah, like I said, not sure. Perhaps @patrickhlauke or @cvrebert would know if there was a decision about this.

**Comment by PowerGamer1** [comment]
Related: https://github.com/twbs/bootstrap/issues/19846

**Comment by luzfcb** [comment]
hello, where is documented that `glyphicons` is removed from `Bootstrap v4`?

http://v4-alpha.getbootstrap.com/extend/icon-fonts/ 

c/c @cvrebert @mdo

**Comment by patrickhlauke** [comment]
http://v4-alpha.getbootstrap.com/migration/#components

**Comment by luzfcb** [comment]
@patrickhlauke thanks. it would be good to reinforce this information and add a note about it in

http://v4-alpha.getbootstrap.com/extend/icon-fonts/

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
