### ISSUE TITLE
Two different bootstrap accordion trigger each other

### ISSUE THREAD

**Issue by bertanyaman** [twbs/bootstrap#19833]
As you can on the example bootlint is fine and all IDs unique but two diffrent collapsable accordion triggers each other. Still looking for solution.

Live example : http://codepen.io/bertanyaman/pen/NNOLyG

**Comment by Johann-S** [comment]
Duplicate of : https://github.com/twbs/bootstrap/issues/18824

the fix is waiting for a review see : https://github.com/twbs/bootstrap/pull/18847
