### ISSUE TITLE
.modal-backdrop is not reveal properly

### ISSUE THREAD

**Issue by shangoyanyi** [twbs/bootstrap#19844]
I upgrade bootstrap from 3.3.5 to 3.3.6 and my project hits in a modal issue that .modal-backdrop is not reveal properly. I try to find out what's going on and found that .modal-backdrop element is already append to the tail of <body></body> but the style is weird. The position of .model-backdrop is "absolute"  without "width" and "height" attribute. which makes .modal-backdrop a 0x0 element and looks like it's not working. I downgrade to 3.3.5 and everything work fine again. hope this can be fixed quickly, thanks.

**Comment by RyanZim** [comment]
Please provide a [Reduced Test Case](https://css-tricks.com/reduced-test-cases/) and list your browser and OS. You may want to read about filing a bug in the [Contributing Guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by shangoyanyi** [comment]
Hi Ryan, I think I made a mistake. I try to re-produce this situation and I found that my web server cached the old version .css file and it's not work well with the new .js file. Since I restart my web server and force reload my web page again, everything goes fine again! Thanks for your time.

**Comment by RyanZim** [comment]
@shangoyanyi OK, great! Could you please close this?
