### ISSUE TITLE
Dropdown sub-menus  

### ISSUE THREAD

**Issue by saboorazizi** [twbs/bootstrap#19845]
Hello, 
Could you please add submenus in version 4 and update the examples. I think sub-menus are very important and every need that. I searched for that in this repository but couldn't find that. If you have already add that please give me update links.

I have found something for Bootstrap 3.3.6 from "Vasily" in here: https://vsn4ik.github.io/bootstrap-submenu/

Thanks from your great CSS.

**Comment by bellwood** [comment]
Please see: #19814 

There's a ton of work to be done still hence Alpha status

**Comment by cvrebert** [comment]
Duplicate of #14944. Please search more in the future. Thanks.
