### ISSUE TITLE
.card-primary, .card-header, and .card-inverse don't work well together

### ISSUE THREAD

**Issue by RyanZim** [twbs/bootstrap#19841]
The docs say:

> ### Background variants
Cards include their own variant classes for quickly changing the background-color and border-color of a card. **Darker colors require the use of .card-inverse.**

Using a background variant does not affect `.card-header`, however, `.card-inverse` does. This results in unreadable text. The same goes to `.card-footer`. See JSFiddle: https://jsfiddle.net/uxcuem8t/2/. (There is text in the header & footer)

I'm not sure what should be changed here, but something should be done.

**Comment by mdo** [comment]
Improvements coming in #19885.
