### ISSUE TITLE
Click on disabled tab still shows corresponding pane

### ISSUE THREAD

**Issue by Paladinium** [twbs/bootstrap#19849]
Using the tab JavaScript plugin with alpha v2, a disabled tab switches the tab content when being clicked. This bug can be seen in the documentation:
- Go to http://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior
- Add class 'disabled' to the 'Profile' tab (e.g. using Firebug)
- Notice that the 'Profile' tab correctly appears to be visually disabled, also when hovering over the tab
- Click on the 'Profile' tab
- The tab's content is switched

Expected: no tab switch happens when clicking on disabled tabs.

The JavaScript needs to take the 'disabled' CSS class (maybe also the 'disabled' attribute) on nav-link into account.

**Comment by RyanZim** [comment]
Confirmed on the latest v4-dev branch. JSFiddle: https://jsfiddle.net/55rb3th9/.

**Comment by cvrebert** [comment]
X-Ref: #19031
