### ISSUE TITLE
Popover dismiss on next click failing on iOS

### ISSUE THREAD

**Issue by jholt1** [twbs/bootstrap#19848]
Your example does not work on ios http://getbootstrap.com/javascript/#dismiss-on-next-click

I have seen that there was a discussion about it before (https://github.com/twbs/bootstrap/issues/15935#issuecomment-76694397), however it seems to be not resolved

**Comment by jeffmcnabb** [comment]
Was just looking in to this issue as well. Have been unable to get this working in Mobile Safari, and then realized even the GetBootstrap demo was failing as well.

**Comment by jeffmcnabb** [comment]
@jholt1 I would suggest changing the name of this to something like "Popover dismiss on next click failing on iOS", the current title seems too generic.

**Comment by RyanZim** [comment]
Possible duplicate of #16028.

**Comment by cvrebert** [comment]
@RyanZim Indeed. Closing as duplicate.
