### ISSUE TITLE
how to give gutter space between two div 

### ISSUE THREAD

**Issue by raman15071991** [twbs/bootstrap#19856]
always we have to give padding from left and right which is affecting the responsiveness and for avoiding this we have to write the media queries but is there any way to achieve it by default like "row"

**Comment by RyanZim** [comment]
I'm not sure what you're asking. If you don't want padding between the columns, you could write a custom class that sets `padding: 0` and add it to all `.col-*-*`s. (I assume you're using v4)

If this answers your question, please close this.

**Comment by cvrebert** [comment]
> If this answers your question,

Or if it doesn't, please describe your problem in greater detail.

**Comment by mdo** [comment]
Sounds like this is dealing with generating custom layouts—yeah, you'll always need that horizontal padding.

**Comment by raman15071991** [comment]
thank you i got it problem solved i used a custom class in which i have given the padding left and right for horizontal space thank you all for your response
