### ISSUE TITLE
Internet Explorer 9 and 10

### ISSUE THREAD

**Issue by JamesGeiger** [twbs/bootstrap#19859]
Microsoft ended support for IE 9 and 10 as per https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

Why does Bootstrap 4 still support 9 and 10?

**Comment by patrickhlauke** [comment]
9 and 10 are supported, with caveats https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/browsers-devices.md#internet-explorer-9--10 at this point. this is not to say that once v4 hits final, this support will remain. but more fundamentally: is support for 9 and 10 causing any particular problems/limitations in your view?

**Comment by JamesGeiger** [comment]
@patrickhlauke No - not really. But if we are going to be using v4 for years supporting them doesn't make sense, especially since MS axed support for them

P.S. Should I be using v4 for production yet?

**Comment by mdo** [comment]
Not for prod yet, and we'll be supporting them for v4.

**Comment by JamesGeiger** [comment]
@mdo Ok - I just don't understand why you would support browsers that were EOL'd by MS. Oh well.

**Comment by AustinPaquette** [comment]
@JamesGeiger because it's not about EOL, it's about Marketshare.

**Comment by mdo** [comment]
Just because they are unsupported doesn't mean they're not actively being used by customers.

**Comment by JamesGeiger** [comment]
@mdo Ok, I don't agree, but that is fair.

**Comment by coliff** [comment]
@JamesGeiger IE9 is still supported for Vista SP2 customers, IE10 is still supported for Windows Server 2012 customers.

REF: https://support.microsoft.com/en-us/lifecycle?wa=wsignin1.0#gp/Microsoft-Internet-Explorer

**Comment by cvrebert** [comment]
Duplicate of #19607.
