### ISSUE TITLE
Unable to scroll modal after typing in a text field within it on iOS

### ISSUE THREAD

**Issue by gunehub** [twbs/bootstrap#19853]
Checking the version of Bootstrap branch v4-dev, I have noticed that I have a form in a modal and when I try to pull the scroll bar down when I close the keyboard does not work, does not let up or down modal. Only it works on mobile devices.

**Comment by RyanZim** [comment]
I'm not sure what you're describing. Could you provide a JSFiddle perhaps?

**Comment by unehub** [comment]
Check this only with mobile devices OS X: https://jsfiddle.net/4d0q8zz9/2/

Open keyboard and last close,  does not let up or down modal.

**Comment by twbs-lmvtfy** [comment]
Hi @unehub!

You appear to have posted a live example (https://fiddle.jshell.net/4d0q8zz9/2/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 89, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 93, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 97, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 101, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 105, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 109, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 113, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 117, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 121, column 15 thru column 74: Duplicate ID ```` recipient-name ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by RyanZim** [comment]
@unehub You can safely ignore @twbs-lmvtfy.

**Comment by cvrebert** [comment]
@unehub I'm still not clear on what you mean.
Which specific OS(es) and browser(s) are you experiencing the problem on?
Please give *step-by-step instructions* for reproducing the problem.

**Comment by unehub** [comment]
Please check the next GIF:

![]
(http://i.giphy.com/26vUJA5vRVLQqyTMQ.gif)

If I try to edit a field, then I can not get to the end of the modal.

**Comment by RyanZim** [comment]
If I understand correctly, @unehub is saying that after you use the keyboard, you cannot scroll the modal (background page scrolls instead).

**Comment by unehub** [comment]
That's right @RyanZima and @cvrebert , once I try to use the "keyboard" will not let me move the modal down.

**Comment by singhashu** [comment]
@gunehub Its web bouncing 
To prevent over scrolling of web page you can use:

html {
    overflow: hidden;
    height: 100%;
}

body {
    height: 100%;
    overflow: auto;
}
And yes its bug in Modal Scrollbar

**Comment by cvrebert** [comment]
I am unable to reproduce the problem using either https://jsfiddle.net/4d0q8zz9/2/show/ or http://output.jsbin.com/yenuqah/quiet on iOS 9.3.5 on iPhone 5S.

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/4d0q8zz9/2/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 89, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 93, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 97, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 101, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 105, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 109, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 113, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 117, column 15 thru column 74: Duplicate ID ```` recipient-name ````.
* line 121, column 15 thru column 74: Duplicate ID ```` recipient-name ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
