### ISSUE TITLE
Make Modal.enforceFocus easier to override/exempt

### ISSUE THREAD

**Issue by zenorocha** [twbs/bootstrap#19850]
For many years, dozens of third-party libraries have been facing the same issue with Bootstrap's modal. The answer so far has been "override enforceFocus" #16050 #12216 #11686 #10610 #8537 #7371 #6996 #5114

That led to many apps adding this line to their code:

```
$.fn.modal.Constructor.prototype.enforceFocus = function() {};
```

Once they upgrade to Bootstrap 4, this line will no longer work. They will need to figure out that it changed to:

``` js
$.fn.modal.Constructor.prototype._enforceFocus = function() {};
```

Instead of asking people to monkey patch their projects, shouldn't this functionality be revisited and fixed? Maybe starting from #12142?

**Comment by whodabudda** [comment]
Oy!!  Days of trolling through code and finally stumbled on this!  Thank you so much for the post.  What a difference a character makes. It would be nice if 3rd party vendors kept the old interface and aliased it to the new, at least for a few releases as deprecated.  I was ready to toss out bootstrap modals altogether.

**Comment by Johann-S** [comment]
With `focus` option to `false`, `enforceFocus` isn't called see : http://v4-alpha.getbootstrap.com/components/modal/#options

**Comment by bhernandezflorido** [comment]
Thanks, brother. That's right, you saved me. @zenorocha
