### ISSUE TITLE
.tab-pane has no border or padding

### ISSUE THREAD

**Issue by alvipeo** [twbs/bootstrap#19857]
So, when using tabs active tab pane should have a border and padding to look like .. normal.

Here's what seems like right to me:

```
.tab-pane.active {
    border: 1px solid $nav-tabs-border-color;
    border-top: none;
    padding: $grid-gutter-width / 2;
}
```

**Comment by cvrebert** [comment]
Seems like a matter of taste to me. I can't seem to recall or find any other requests/complaints for such styling.
You can always use a [card](http://v4-alpha.getbootstrap.com/components/card/) in the tab pane or around the entire tabs widget to achieve a similar result.
CC: @mdo

**Comment by alvipeo** [comment]
I mean isn't this better:

![With border]
(http://inus.azureedge.net/pub/tab-panes.png)

than this? 

![Without border]
(http://inus.azureedge.net/pub/tab-panes-no-border.png)

Especially when the tab contains tab.

**Comment by alvipeo** [comment]
Is this possible with cards?

**Comment by cvrebert** [comment]
Almost, if you add `.card.card-block` to `.tab-content`, but the border still requires extra tweaking.

**Comment by cvrebert** [comment]
> Especially when the tab contains text (or at least starts with text).

Yeah, I agree at least some padding would be nice in that case, but implementing that properly could be fiddly.

**Comment by alvipeo** [comment]
Doing it with cards seems like tuning css with javascript :)

**Comment by RyanZim** [comment]
If this is added, it should be entirely opt-in.

Perhaps we could could add a class that would be placed on `.tab-content` and use a selector like `.tab-pane-outline .active` for the styling.

**Comment by alvipeo** [comment]
ok, opt-in is fine. It just should be there in some way.

**Comment by mdo** [comment]
Closing as a won't fix. There are easy padding utilities now that can accomplish all the spacing, and borders are a preference that don't need to be set initially IMO.

**Comment by willianmzc** [comment]
### 

> [`_****_`](

- 

- [ ] @ #1. url

)
