### ISSUE TITLE
collapse (accordion) does not work properly with parent

### ISSUE THREAD

**Issue by diaksid** [twbs/bootstrap#19866]
js/src/collapse.js/collapse.js str. 124:

`actives = $.makeArray($(Selector.ACTIVES))`

should be changed to

`actives = $.makeArray($(Selector.ACTIVES, this._parent));`

**Comment by Johann-S** [comment]
Exactly this PR : https://github.com/twbs/bootstrap/pull/18847 will fix it

**Comment by RyanZim** [comment]
Duplicate of https://github.com/twbs/bootstrap/issues/18824. Please close this. Thanks!
