### ISSUE TITLE
CSS sourcemap "sources" path is incorrect

### ISSUE THREAD

**Issue by TimKraemer** [twbs/bootstrap#19860]
Hi,

I'm not a web-developer so I might be missing something, but I think the "sources"-paths in all `css.map` files are wrong.
I fetched bootstrap via bower:
`bower install bootstrap`
wich results in a folder-structure like this:
```
bower_components
-> bootstrap
    -> dist
        -> css
            -> bootstrap.css.map
    -> less
       -> normalize.less
...
```

However `bootstrap.css.map` looks for `less/normalize.less` in its relative child-folder:
```
{
  "version":3,
  "sources":
      [ "bootstrap.css", "less/normalize.less", ... ]
...
}
```

Shouldn't this be `"../../less/normalize.less"` (which works in my setup)?

**Comment by cvrebert** [comment]
Fixing #19063 will also fix this.

**Comment by wolfy1339** [comment]
You can add a `sourceRoot` option in the sourcemap to fix this

**Comment by TimKraemer** [comment]
thanks @wolfy1339 - that worked for me (at least until the next update :smiley:)

**Comment by cvrebert** [comment]
Looks like we ought to set `sourceMapBasepath: 'dist/css/'`

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
