### ISSUE TITLE
Collapse doesn't work when in a Modal

### ISSUE THREAD

**Issue by uwbadger1** [twbs/bootstrap#19876]
The class and aria-expanded attributes of the data-toggle="collapse" element are updated correctly. 
- class="btn btn-primary collapsed" aria-expanded="false"
- class="btn btn-primary" aria-expanded="true"

The class="collapse" element is not updated.  It should be adding/removing the .in class to this element.

This is working when it's not within a modal.

**Comment by RyanZim** [comment]
Please provide a [Reduced Test Case](https://css-tricks.com/reduced-test-cases/) (JSFiddle, etc.) and list your browser and OS. Thanks!
