### ISSUE TITLE
Bootstrap solution for buttons with icons

### ISSUE THREAD

**Issue by AlexanderDowerk** [twbs/bootstrap#19873]
A common scenario for buttons is to contain either text, icons or icons with text.
In the case of a button containing an icon with text, the icon obviously needs some margin to get some spacing to the text. If the button just contains an icon, the icon doesn't need any margin. 
Of course it's easy to write custom classes for this scenario, but it would be great to have a native bootstrap solution that doesn't require any additional markup or classes. 

![buttonwithicon](https://cloud.githubusercontent.com/assets/10029073/15140031/7caecba8-1699-11e6-9a65-ed1e49ba15a6.png)

**Comment by RyanZim** [comment]
@AlexanderDowerk I always use a space, like this:
```
<buttton class="btn btn-primary"><i class="icon-name"></i> Text</button>
```
If we would add such a feature it would have to be for v4.

**Comment by AlexanderDowerk** [comment]
Actually I meant to suggest this feature for v4, sorry.

**Comment by mdo** [comment]
We don't have icons in v4 anymore, so going to punt on making any changes here.
