### ISSUE TITLE
How to customized? No easy way to ask questions

### ISSUE THREAD

**Issue by pgorbas** [twbs/bootstrap#19870]
There is a page, [http://www.getbootstrap.sk/customize/index.html](url), but after you finish and compile and download the completed zip file - NOWHERE is anything giving even a clue as what to do with the darn files.  ( I just installed the standard package though bower ).

SO what am I supposed to do with the downloaded customize files?

Nowhere to be found on the website is there a support email, web form or forum to ask questions.

**Comment by RyanZim** [comment]
The proper places to ask questions are listed in the README: https://github.com/twbs/bootstrap#community.

StackOverflow.com is another good place to get help.

The issue tracker doesn't handle support requests, but FWIW, here is the basic template for your html: http://getbootstrap.com/getting-started/#template.

Please close this. Thanks!

**Comment by pgorbas** [comment]
I see from that that it is all twitter based and I generally avoid twitter. Boo twiter!

**Comment by wolfy1339** [comment]
Follow the same instructions as noted in the docs for the original package

**Comment by Starsam80** [comment]
> twitter based

Well, it _is_ Twitter Bootstrap. However, Bootstrap is used in many different sites, so it's not just twitter anymore.

**Comment by cvrebert** [comment]
http://getbootstrap.com/getting-started/#whats-included explains what the files are, and http://getbootstrap.com/getting-started/#template gives an example of basic usage.
If you need basic general web development information on how to use CSS and JS, please consult general beginner web developer resources; teaching folks such things is beyond the scope of the Bootstrap project.
