### ISSUE TITLE
@include 'part'

### ISSUE THREAD

**Issue by chwebo** [twbs/bootstrap#19875]
Installing Bootstrap to a website means a lot of data that has to be transferred. If you use all of the great features this is not a big problem, but if you only use some features as the grid system you may do not want to transfer the complete bootstrap installation.

So it would be awesome if a developer could include (by sass) only the features to his stylesheet that he really needs. This has several advantages. First, you only need one .css file which is great for SEO, secondly you do not transfer unused styles to the user and furthermore it would be much more easy to style the website as you don't have to overwrite the bootstrap defaults on elements you don't want to have the bootstrap styles.

Hoping, that this feature will be included in the fourth version of bootstrap.
Thanks a lot in advance.

**Comment by mdo** [comment]
I don't see us making any changes to how you can accomplish this now. Manually edit the import stack in https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss to include what you wish (keeping in mind dependencies), and recompile as part of your app.
