### ISSUE TITLE
Remote Modals in IE9 do not trigger shown.bs.modal the first time they are clicked.

### ISSUE THREAD

**Issue by Jaded-Design** [twbs/bootstrap#19884]
IE9 ONLY: 

When clicking a modal link the modal does open on the first click. However, the content that is to be loaded using .load() does not render as it fires off of the shown.bs.modal event, which is not firing. 

If I close the modal and click the modal link again then the modal will open and render the content correctly.

**Comment by cvrebert** [comment]
@Jaded-Design Where is the testcase which I explicitly requested?

**Comment by Jaded-Design** [comment]
No need to be rude... Some of us have jobs and aren't able to spend a bunch of time setting up examples... It's a pretty straightforward problem... 

Anyway, I've figured out the issue. 

If you nest your shown.bs.model event inside of your click event it will not fire. You need to put the shown.bs.model event in it's own script and doc ready function. 

So instead of nesting the shown.bs.modal event like this: 
'''$(function (){
   $(element).on('click', function () {
       $(element.).on('shown.bs.modal', function(){
       //do something
})
})
})```

You break it out into it's own script.
