### ISSUE TITLE
Caret not displayed in recent versions of v3

### ISSUE THREAD

**Issue by bjarnef** [twbs/bootstrap#19880]
It seems the `.caret` isn't working anymore in recent versions of v3. I use bower to get bootstrap files `"bootstrap": "~3.3.4"` and bundling with gulp, but there seems to be this change since v. 3.3.4
https://fossies.org/diffs/bootstrap/3.3.4_vs_3.3.5/less/dropdowns.less-diff.html

I affects several browsers:
* Chrome Version 50.0.2661.94
* Microsoft Edge 25.10586.0.0
* Firefox 45.0.2
* Chrome for Android v. 50.0.2661.89
* Firefox for Android v. 46.0.1

probably other browsers as well.

in v. 3.3.4 it worked in e.g. Chrome:
![image](https://cloud.githubusercontent.com/assets/2919859/15172785/675607a2-1758-11e6-813c-2ee4d655a1d8.png)

now it has been changed to this in v. 3.3.5 / 3.3.6:
![image](https://cloud.githubusercontent.com/assets/2919859/15172811/858f3c66-1758-11e6-8790-4eb7e01e680c.png)

it works if I add `border-top:dashed` or `border-top:solid` for `.caret`

I know `\9` is a special hack for IE (where it also is working in IE11 but now in Edge), but browsers like Chrome ignore it so it won't display anything.

Why not something like this if IE needs to override the border property with another value?
```
.caret {
    border-top: 4px solid;
    border-top: 4px solid\9;
}
```
http://stackoverflow.com/a/8004962

However it seems to work fine when just having this (not sure about it has issues in older versions of IE):

```
.caret {
    border-top: 4px solid;
}
```

**Comment by bjarnef** [comment]
Okay, it actually seems it is an issue in the gulp plugin that compiles the bootstrap less:
https://github.com/plus3network/gulp-less/issues/165
https://github.com/css/csso/issues/230
https://github.com/css/csso/issues/231

**Comment by patrickhlauke** [comment]
So not an issue with Bootstrap, but with the gulp plugin.

**Comment by anasqadrei** [comment]
I don't know who's problem is it but caret is still not displayed!
