### ISSUE TITLE
closing modal causes layout issues on the page

### ISSUE THREAD

**Issue by pallymore** [twbs/bootstrap#19882]
Hello,

I'm using Boostrap 3.3.6 and recently ran into a puzzling issue with the modal component.

Here's a jsfiddle to recreate this: http://jsfiddle.net/14qjajoh/ 
Browsers tested: latest Chrome & Firefox. 

So I have a box container, which has two boxes, the 2nd one contains actions, and only shows up when the box container is hovered. 
When I close the modal, the boxes are moved to the top...for no reason?
Clicking on the box itself fixes the layout though...

Is there anything wrong with my code? 

Thanks! 
P

===== more info

this only happens when the modal is invoked by clicking the button. 
if it is displayed with javascript
```javascript
// in console. 
$('#modal').modal();
```
then layout won't be affected after closing the modal (by using the Close buttons)

**Comment by mdo** [comment]
Perhaps the button is snagging focus and jumping you back to it?

**Comment by pallymore** [comment]
Interesting. Same issue occurs when I focus on the button with JS `$('a').focus();` 
still not sure why it's making `box-1` to move up though.

**Comment by pallymore** [comment]
Hmm It seems it's a browser behavior, not a bootstrap issue. 
I will try to figure it out. 

Thanks for your help!

**Comment by pallymore** [comment]
checked previous pull requests.
It seems bootstrap is partially responsible - it tries to focus on the triggering element when the modal is closed as long as the modal `.is(':visible')` - since that jQuery considers anything that takes up space in the document is visible, it will focus on the button no matter if it's `visibility: hidden` or `opacity: 0` or being hidden by `overflow: hidden;` 

original pull request
https://github.com/twbs/bootstrap/pull/13627

I think the pull request makes sense for accessibility reasons, but I think it's better if it checks if the element is actually in port of view, instead of checking if it is taking up space in the document. Thoughts? 

I updated CSS to fix this issue:
http://jsfiddle.net/14qjajoh/3/

**Comment by cvrebert** [comment]
Sounds like a uncommon enough case that I'm not sure it's worth handling.

CC: @patrickhlauke

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
