### ISSUE TITLE
Dropdown Menu for Nav bar

### ISSUE THREAD

**Issue by chiraggmodi** [twbs/bootstrap#19881]
Hi
It been create if in Bootstrap 4 dropdown on hover will be added natively. And we you could add mega menu too that would be awesome. Just Wanted this feature as most site use dowpdown on hover not on click.

**Comment by mdo** [comment]
No native or mega dropdowns will be coming to Bootstrap. Thanks for the suggestion though!

**Comment by cvrebert** [comment]
Duplicate of #2965.
