### ISSUE TITLE
width scrolling problem with .card-deck

### ISSUE THREAD

**Issue by rubenscd** [twbs/bootstrap#19883]
I have a problem with the card-deck, he is breaking the width of the size of the body / html, creating horizontal scrolling, following image and test html

![card-deck-size-problem](https://cloud.githubusercontent.com/assets/40513/15190558/e19b6f92-1786-11e6-8d5c-ee17a8d82ecc.PNG)

`
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>test nivo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css">
  </head>
  <body>
  <div class="container-fluid">
    <div class="card-deck-wrapper">
      <div class="card-deck">
        <div class="card">
          <div class="card-block">
            Card 1
          </div>
        </div>
        <div class="card">
          <div class="card-block">
            Card 2
          </div>
        </div>
        <div class="card">
          <div class="card-block">
            Card 3
          </div>
        </div>
        <div class="card">
          <div class="card-block">
            Card 4
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
  </body>
</html>
`

**Comment by RyanZim** [comment]
Please use a JSFiddle next time. I created one using your code (https://jsfiddle.net/Lhuq3frk/) and am unable to reproduce in Firefox 46.0.1 on Windows 7. What browser & OS are you using?

**Comment by rubenscd** [comment]
@RyanZim Windows 10 - Google Chrome 50.0.2661.94 m (64-bit) - and Mozilla Firefox 46.0.1 also

**Comment by RyanZim** [comment]
@rubenscd Is that tested with the JSFiddle or with your own code?

**Comment by rubenscd** [comment]
@ryanzim both

**Comment by RyanZim** [comment]
OK, still can't reproduce. Any insight @cvrebert?

**Comment by mdo** [comment]
This is a mismatch of grid and card deck values in our CSS. Need to rework those to match the grid for something like this.

**Comment by mathmatrix828** [comment]
+1 on this issue. Ran into it when creating dynamic content via PHP, adding in a row causes all kinds of formatting problems as well

**Comment by ve3** [comment]
I have the same problem with Firefox 47 on Windows 10.
