### ISSUE TITLE
[proposed v4 docs bug] btn outline docs are wrong

### ISSUE THREAD

**Issue by flexzuu** [twbs/bootstrap#19899]
[Docs](http://v4-alpha.getbootstrap.com/components/buttons/#outline-buttons): 
```html
<button type="button" class="btn btn-primary-outline">Primary</button>
<button type="button" class="btn btn-secondary-outline">Secondary</button>
<button type="button" class="btn btn-success-outline">Success</button>
<button type="button" class="btn btn-info-outline">Info</button>
<button type="button" class="btn btn-warning-outline">Warning</button>
<button type="button" class="btn btn-danger-outline">Danger</button>
```

Working ones for the via cdn distributed version [v4-dev](https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css)
```html
<button type="button" class="btn btn-outline-primary">Primary</button>
<button type="button" class="btn btn-outline-secondary">Secondary</button>
<button type="button" class="btn btn-outline-success">Success</button>
<button type="button" class="btn btn-outline-info">Info</button>
<button type="button" class="btn btn-outline-warning">Warning</button>
<button type="button" class="btn btn-outline-danger">Danger</button>
```
[JSBin example](http://jsbin.com/turobipuye/edit?html,output)
I don't know if the docs or the cdn version is right.

**Comment by twbs-lmvtfy** [comment]
Hi @flexzuu!

You appear to have posted a live example (http://jsbin.com/jopeluzuho/embed/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by flexzuu** [comment]
Fixed bug in example: [JSBin example](http://jsbin.com/turobipuye/edit?html,output)

**Comment by patrickhlauke** [comment]
http://v4-alpha.getbootstrap.com is for v4.0.0-alpha.2 while v4-dev has now moved ahead with changes since then. if using v4-dev, refer to the documentation that comes with the branch itself https://github.com/twbs/bootstrap/tree/v4-dev
