### ISSUE TITLE
min-height:100% prevents children divs from inheriting height:100%

### ISSUE THREAD

**Issue by plaudev** [twbs/bootstrap#19891]
With html & body both defined with height:100%, .container {min-height:100%} prevents children of .container from inheriting height of body.

[Try this jsfiddle](https://jsfiddle.net/rockhammer/1a6vo20p/).

If you change .container {min-height:100%} to .container {height:100%} then children will inherit height:100%.

**Comment by twbs-lmvtfy** [comment]
Hi @pchlau!

You appear to have posted a live example (https://fiddle.jshell.net/rockhammer/1a6vo20p/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 184, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 247, column 11: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 170, column 3: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by pchlau** [comment]
Fyi, the code is fixed as noted. Thanks

**Comment by cvrebert** [comment]
Reposting to trigger revalidation: https://jsfiddle.net/rockhammer/1a6vo20p/

**Comment by mdo** [comment]
I don't think this is a Bootstrap bug so much as HTML behavior. Closing out, but happy to revisit if someone provides a bit more information <3.
