### ISSUE TITLE
Typeahead

### ISSUE THREAD

**Issue by billias13** [twbs/bootstrap#19895]
I don't know if this is the correct place for posting questions, but is there any typeahead script working with the version 4 of bootstrap?

**Comment by patrickhlauke** [comment]
sorry, per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker no it's not the right place ;)

(however, a quick google brings up https://github.com/bassjobsen/Bootstrap-3-Typeahead which I believe is quite solid)

**Comment by billias13** [comment]
I found this, which works perfectly (for at least a few browsers) : 
https://github.com/bassjobsen/typeahead.js-bootstrap4-css/blob/master/typeaheadjs.css
