### ISSUE TITLE
Accessibility question about role in tabs and accordions

### ISSUE THREAD

**Issue by patriciamarchand** [twbs/bootstrap#19898]
Hello, 
I have question about accessibity roles tags in collapsible element like accordion and tabs. I don’t understand why they have the same role (**tablist, tab and tabpanel**).  
Aren't the accordion and tab two different components visually? Or they use the same roles because the two components are similar in functionality (when you click on a panel heading or a tab you display a hidden content).

### On W3C the definition of tablist :
> A list of tab elements, which are references to tabpanel elements. 
Source : [https://www.w3.org/TR/wai-aria/roles#tablist](https://www.w3.org/TR/wai-aria/roles#tablist) 

### On W3C the definition of tab :
> A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user.
Source : [https://www.w3.org/TR/wai-aria/roles#tab](https://www.w3.org/TR/wai-aria/roles#tab)

### Bootstrap markup for ACCORDION
 &lt;div class="panel-group" id="accordion" **role="tablist"** aria-multiselectable="true" ...
 &lt;div class="panel-heading" **role="tab"** id="headingOne"...
 &lt;div id="collapseOne" class="panel-collapse collapse in" **role="tabpanel"** aria-labelledby="headingOne"...

```
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
```

### Bootstrap markup for TAB
 &lt;ul class="nav nav-tabs" **role="tablist"** 
&lt;li role="presentation"><a href="#profile" aria-controls="profile" **role="tab"** data-toggle="tab"...
&lt;div **role="tabpanel"** class="tab-pane active" id="home"...
```
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">...</div>
    <div role="tabpanel" class="tab-pane" id="profile">...</div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">...</div>
  </div>
```

**Comment by patrickhlauke** [comment]
refer to https://www.w3.org/TR/wai-aria-practices/#accordion

**Comment by patriciamarchand** [comment]
ok I understand. Thanks

**Comment by Hibrix-net** [comment]
> 
> 
> refer to https://www.w3.org/TR/wai-aria-practices/#accordion

Hi,

they removed those tab related accessibity roles from Boostrap 4, because they were referring to deprecated W3C specs.

Now is much simpler: https://getbootstrap.com/docs/4.0/components/collapse/

Cheers,
