### ISSUE TITLE
ESLint rules need to be updated

### ISSUE THREAD

**Issue by sijad** [twbs/bootstrap#19908]
v4 [.eslintrc](https://github.com/twbs/bootstrap/blob/v4-dev/js/.eslintrc) rules should be updated

* Rule 'no-empty-label' was removed and replaced by: no-labels (no-empty-label)
* Rule 'space-after-keywords' was removed and replaced by: keyword-spacing (space-after-keywords)
* Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing (space-return-throw-case)

**Comment by cvrebert** [comment]
Bootstrap's current grunt-eslint: ^17.1.0
Corresponding ESLint (for grunt-eslint 17.3.2): ^1.5.1

Latest grunt-eslint: 18.1.0
Corresponding ESLint: ^2.0.0
Latest ESLint: v2.11.1

**Comment by cvrebert** [comment]
The rules you specifically mentioned have now been updated via #19998.

**Comment by cvrebert** [comment]
As of #20000, there's 9 more versions to go, to get to current ESLint v2.11.1.

**Comment by cvrebert** [comment]
And with #20068, we're fully up-to-date.
