### ISSUE TITLE
Navigation bar nesting issues

### ISSUE THREAD

**Issue by AbhilashKuvalkar** [twbs/bootstrap#19900]
Hi,

I tried to implement navigation bar with multiple nesting of items, but didn't came up with the solution.

Check the below link for example: [Example](http://vizagtechie.blogspot.in/2012/06/dynamic-multi-level-jquery-menu-for.html)

When, I implemented the css the nesting would happen overlapping the current menu or below it. It should be displayed to the right next to it.

**Comment by mdo** [comment]
No idea what you're referring to in your example—please reproduce it with a JS Bin link. [Read the contributing guidelines for more info](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker).

**Comment by rafalp** [comment]
Looking at example posted I'm taking it @AbhilashKuvalkar is trying to do dropdown with dropdown in navbar.

**Comment by AbhilashKuvalkar** [comment]
Please check the code below:

`<nav class="navbar navbar-default">
    <div class="container-fluid">
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a>
                </li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret" /></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Create User</a>
                        </li>
                        <li>
                            <a href="#">Create Group</a>
                        </li>
                        <li>
                            <a href="#">Create Account</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Accounting <span class="caret" /></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Manage Account</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">GL Accounts <span class="caret" /></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">Salary Accounts</a>
                                </li>
                                <li>
                                    <a href="#">Savings Accounts</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>`

The second nesting menu is not getting opened also.
i.e 'GL Accounts' menu is not getting displayed, which contains 'Salary Accounts' & 'Saving Accounts'.

Please check it.

**Comment by mdo** [comment]
Sorry, but nested dropdown menus aren't supported in Bootstrap as of v3.0.0.
