### ISSUE TITLE
Access generated SASS variables

### ISSUE THREAD

**Issue by OleVik** [twbs/bootstrap#19903]
Is there a way of accessing the variables Bootstrap sets in compilation? I import the v4 scss, and need to use the width of for example `col-sm-8` and `offset-sm-2` in my custom scss-file, but can't find any reference for how to use these variables in SASS itself - rather than as HTML-classes.

**Comment by mdo** [comment]
As long as you're importing the Sass files into another Sass file, you should be able to reference those variables. I suppose an example in our docs would be helpful here. I'll tag it and see if I can find some time to dive into it.

In the mean time, you might want to peep the Slack channel or StackOverflow (see readme).

**Comment by OleVik** [comment]
So they are accessible as `$col-sm-8` for example?

**Comment by mdo** [comment]
Ah, you're talking about classes, not variables. That's not possible currently and is a limitation of Sass (you cannot create variables dynamically).
