### ISSUE TITLE
v4 small input group addon not even with input

### ISSUE THREAD

**Issue by ryanzec** [twbs/bootstrap#19907]
![screen shot 2016-05-15 at 10 31 12 am](https://cloud.githubusercontent.com/assets/444206/15274757/89a46d48-1a88-11e6-9d23-ddeb7928f97d.png)

I saw a bug about this issue for all input sizes that has been closed however with v4 / alpha 2, I am still seeing this slight issue with only the small input group size (normal / large look fine).

**Comment by mdo** [comment]
Are you using the latest CSS from `v4-dev`?

**Comment by ryanzec** [comment]
I am using the tagged release of alpha 2

**Comment by mdo** [comment]
Update to the latest from `v4-dev` and you should be good to go. We're closing in on another tagged release, but there are ~1,000 commits to `v4-dev` since alpha 2 was released (that's both awesome and shitty, sorry!).
