### ISSUE TITLE
Center container vertically.

### ISSUE THREAD

**Issue by leebaird** [twbs/bootstrap#19905]
Need a simple method to center a container vertically.

**Comment by rafalp** [comment]
Pick one fitting your usecase http://howtocenterincss.com/ ;)

**Comment by seshaljain** [comment]
Using flexbox, it becomes quite easy:
Check out my example on [Codepen](http://codepen.io/seshaljain/pen/eZoPbB)

**Comment by leebaird** [comment]
Thanks seshaljain, that solved my issue.
