### ISSUE TITLE
Bootstrap 4 - modal stacking?

### ISSUE THREAD

**Issue by EugenMayer** [twbs/bootstrap#19914]
I am using Bootstrap 2 right now, with several, reused / custom made solutions for modal stacking. 
I am aware there is http://jschr.github.io/bootstrap-modal/ for Bootstrap 3.

But what about Bootstrap 4? Are there any internal efforts / external efforts to get this going? At least for me, thats a / the deal breaker.

Thanks

**Comment by patrickhlauke** [comment]
sorry, currently there are no plans to implement modal stacking in v4.

**Comment by EugenMayer** [comment]
before you instantly close this, it can be useful to have a guide for all people searching for this - this does not mean it needs to be an internal project. A lot of people do search for this kind of solution, and they will look into the issue queue. 

You might want to consider keeping this issue open

**Comment by cvrebert** [comment]
To my knowledge, we're not ideologically opposed to the feature, it's just difficult to implement properly, there are acceptable (admittedly not ideal) alternatives, and the team has limited resources which might be more impactfully spent on other things.
If someone wrote an awesome patch that implemented it properly, was well-tested, and handled all the edge cases, we'd seriously consider merging it.

**Comment by rafalp** [comment]
If your need modal stacking for your SPA, you have bigger problems than not having that feature in Bootstrap.

**Comment by shyamal890** [comment]
@rafalp Ok, so what would be an alternative to the following flow:
Open userlist modal - click on delete button - confirmation modal opens up

**Comment by rafalp** [comment]
The fact that you put list of users into modal and made them hard deletable from it already sounds like classic "we really wanted to have that thing on this page but had no idea where so we shoved them into modal". The good approach would be to have that list on the page and then open modal to ask user for confirmation.

Other alternatives are `window.confirm`, swapping modal's content for new one that lists only selected items (that one gives you chance to provide extra info on what may be lost together with deleted items), or if you want users to have quick reach to multiple complext sets of same information, use tabs.

**Comment by shyamal890** [comment]
Almost all SPA applications out their have this flow. Moreover, to pick one example checkout Google Contacts pic below. Are you saying GOOGLE's designers who designed Material which is now most prevalent framework after bootstrap don't know UI/UX?!!

![i](https://user-images.githubusercontent.com/6606965/39081705-b04e3c28-4563-11e8-934d-d8a0f1656784.JPG)

**Comment by EugenMayer** [comment]
@shyamal890 i would not bother them too much here, i do not have any hopes of changes.

The big issue here is, what are you actually designing, a SPA / Enteprise application or some website or simple web application. for the latter, avoiding stacked modals is easy and does not cut a lof from user UX , very different for bigger web applications with different contexts and sub-contexts.

When well designed, there is are good reasons to use stack MODALS and the anti-pardigm against that was never "anti stacked modals" it was anti "stacked dialogs" which are total different things. But people seem to got that wrong.

Here, Google decided to use stacked modals out of the typical treasons:
 - the user should be aware of the context of his action seeing it blurred in the background - getting reminded "where he is doing and typical CRUD action". The more complex a system is, the more this "compass" is needed for the user to feel save it its actions
 - more important is, that the user stays in the context after finishing the operation, that means lets assume "User administration". You go to the page listing the users (administration), click on details, a modal dialog opens showing you the details of the users. It offers you a delete button. Now when you click on delete a modal stacks with the confirmation. You will see in the background, confirming yourself, what you are operating on. Clicking yes/ no closes the modal stack and you are back to your initial context, the user-administration.

If you would not stack, but replace the initial details dialog, the user would see the list of users ( all ) in the background and loses his context and "safe compass".

There are more reasons to use stacked modals ( other then using stacked non-modals ). 

Having a good flow / framework to use those stacked modals is fundamental to such a UX/UI framework and getting it done using a plugin is, since bootstap2, rather a full blown hack then anything near to integrated in well done.

But there is no sense in complaining or waiting for anything to happen here. Eventhough @cvrebert states there is no idiologic reason behind that not getting offered, i doubt that is the real motivation.

There is a good chance, using b2/b3 implementations, refactoring them and making them first class citizens, that those already battle proven implementations become well integrated and not an issue at all. But i suppose the motivation to integrate those is low, since there are ideologic reasons.
