### ISSUE TITLE
v4: justified button groups

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#19918]
Doesn't appear to be working properly:

https://jsfiddle.net/7sqnran9/2/

Expected result is buttons stretch at equal sizes to span the entire width of its parent as per:
http://getbootstrap.com/components/#btn-groups-justified

Not sure if WIP or missing/broken

**Comment by mdo** [comment]
Dupe of #17631.

**Comment by dejurin** [comment]
```
<div class="btn-group d-flex" role="group">
   <a href="" class="btn btn-secondary w-100">Previous</a>
   <a href="" class="btn btn-secondary w-100">Next</a>
</div>
```
https://getbootstrap.com/docs/4.0/migration/#button-group

**Comment by Ohidur** [comment]
Thank you very much @dejurin
