### ISSUE TITLE
Use ::after instead of div.modal-backdrop for modal backdrop

### ISSUE THREAD

**Issue by pgrmCreate** [twbs/bootstrap#19916]
When we use modal component : We can found a DIV with the class **_modal-backdrop_**.

Why don't change architecture of component or use **::after** tag for respect the HTML semantic ?

**Comment by shakegioh** [comment]
It's not possible to use `:after` since `.modal-backdrop` has a click handler on it.

Pseudo-elements are not part of the DOM, so you can't bind any events directly to them, you can only bind to their parent elements.

**Comment by kkirsche** [comment]
Since pseudo-elements cannot have an event bound to them, would it make sense to close this issue? While I agree `::after` is semantically preferred, I'm not sure that there would be a clean and concise way to bind the click event to the backdrop to trigger closing it.

**Comment by RyanZim** [comment]
This might be too hacky, but... http://stackoverflow.com/a/23243996.

**Comment by mdo** [comment]
Closing since there are no planned changes here.
