### ISSUE TITLE
.form-horizontal .form-group.form-group-sm .form-control-static (horizontal padding)

### ISSUE THREAD

**Issue by bkdotcom** [twbs/bootstrap#19917]
https://github.com/twbs/bootstrap/blob/master/less/forms.less#L351

horizontal padding is being added to static controls  (form-group-sm & form-group-lg)

attached is a screen shot of the [documentation example](http://getbootstrap.com/css/#forms-controls-static) after adding `form-group-sm` to the `form-group`

form-group-sm
![screen shot 2016-05-16 at 11 14 44 am](https://cloud.githubusercontent.com/assets/2137404/15295720/7250adf8-1b57-11e6-99cb-046306e59b0c.png)

vs regular
![screen shot 2016-05-16 at 11 14 13 am](https://cloud.githubusercontent.com/assets/2137404/15295729/7a502880-1b57-11e6-848b-9b473f31f83e.png)

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
