### ISSUE TITLE
Change in column offset naming convention should be reflected in docs

### ISSUE THREAD

**Issue by diroru** [twbs/bootstrap#19910]
Hello,
i have the distinct impression that `col-{size}-offset-{n}` is now `offset-{size}-{n}`. If that is a long term change, it would be nice if this was reflected in the docs.
Keep up the excellent work & cheers!

**Comment by mdo** [comment]
It's in the branch, `v4-dev`, but we only push to our hosted docs upon release. Soon!

**Comment by diroru** [comment]
Thanks for the info! I had the impression that http://v4-alpha.getbootstrap.com/ reflects the current status of the v4 API. A disclaimer of sorts saying there might be API differences would be nice :) Cheers
