### ISSUE TITLE
Switching between text inputs within Modal flickers on iOS

### ISSUE THREAD

**Issue by eozelius** [twbs/bootstrap#19927]
I have a bootstrap modal that contains a form with text and email fields.  Moving between inputs by clicking, or using ios keyboard tab, causes a 'jumping' effect.  The entire modal seems to re-render or slide down, animate again, and then the correct field is focused.  The issue seems to be related to height of modal, often the first 3-4 input fields work fine, and then the fields closer to the bottom will have this issue.

Steps to recreate
1. http://output.jsbin.com/pusayir
2. launch modal
3. focus/click field 7
4. focus/click field 6
5. focus/click field 5

System info: 
Apple ipad2, v9.3.1
Chrome: 50.0.2661.95
Bootstrap: v3.3.6

**Comment by twbs-lmvtfy** [comment]
Hi @eozelius!

You appear to have posted a live example (http://jsbin.com/pusayir/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 72, column 17 thru column 24: The ```` center ```` element is obsolete. Use CSS instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by eozelius** [comment]
`<center>`s removed from my code.  Thanks @twbs-lmvtfy

**Comment by cvrebert** [comment]
@eozelius Does this happen in Safari, Chrome, or both? (on iOS)

**Comment by cvrebert** [comment]
Possible X-Ref: #17324

**Comment by eozelius** [comment]
Hello @cvrebert, this issue happens on both safari and chrome

**Comment by cvrebert** [comment]
Ok, I can see what you're referring to on my iPhone.
Very unlikely we can do anything about it on our end, but we can file a WebKit bug about it.

**Comment by mantrax314** [comment]
@cvrebert Please file this WebKit bug

**Comment by cvrebert** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=158276

**Comment by ImranBug** [comment]
@cvrebert Thanks for the info a lot, I have wasted a day or more trying to find a work around to this. I can finally show the URL of [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=158276#c1) & tell client we cant do much here :) cheers.

**Comment by ImranBug** [comment]
@cvrebert Hi again, I ended up using a work around which might help for people who end up in this thread. 
I am simply hiding entire layout then showing popup as a normal div (without fixed or absolute position). This gives a feel of popup & seems like the most closest acceptable solution to this bug.

[Click here](https://jsbin.com/laciseputi/3) for the demo and [here for editor](https://jsbin.com/laciseputi/3/edit?html,css,js,output).
Further details are [here](http://stackoverflow.com/questions/38681809/input-field-inside-popup-is-jumping-when-focused)

**Comment by Marshevskyy** [comment]
I've run into same issue today. fixed it by moving width/height from "%" to "vh", "vw" for .modal dialog.

**Comment by ryancwalsh** [comment]
@Marshevskyy I'm encouraged by your comment. However, changing all modal-related width and height values from % to `vh` didn't seem to change the behavior for me. I'm using Bootstrap 3 and [Featherlight](https://github.com/noelboss/featherlight) (and the flicker seems to happen even if I remove Bootstrap entirely). If you'd be willing to share more specifically how you solved the problem, I'd appreciate it! Are you using http://getbootstrap.com/javascript/#modals? Where/what did you edit? Thanks!!

**Comment by jaythakur** [comment]
I am having same flickring issue on ipad. can you tell any one how can i resolve?

**Comment by cvrebert** [comment]
This is believed to have been fixed in iOS 10.3.1:
https://bugs.webkit.org/show_bug.cgi?id=158276#c4

**Comment by jaythakur** [comment]
Hi 

but this solution not working for me.
https://bugs.webkit.org/show_bug.cgi?id=158276#c4

**Comment by cvrebert** [comment]
What version of iOS are you using?
Link to your affected webpage?

**Comment by jaythakur** [comment]
I am using 10.2.1

**Comment by jaythakur** [comment]
when i click on any textbox, the whole popup goes up and down.

**Comment by cvrebert** [comment]
No good known workaround aside from "update your iOS".
