### ISSUE TITLE
How to make a listview with LayoutTemplate,ItemTemplate responsive using bootstrap

### ISSUE THREAD

**Issue by nasreekar** [twbs/bootstrap#19929]
I have a List<T> which is to be displayed on the webpage. Im using a listview with layout template to show the values. How can I make the listview responsive using bootstrap.

my listview code:

```
<asp:listview id="ListView1" runat="server">
                <LayoutTemplate>
                    <table id="t" class="table table-striped">
                        <thead>
                            <th>
                                Title
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Address
                            </th>
                            <th>
                                Phone Number
                            </th>
                            <th></th>
                            <th></th>
                       </thead>
                        <tr id="itemPlaceholder" runat="server"></tr>
                    </table>
                </LayoutTemplate>
                <ItemTemplate>
                    <tr runat="server">
                        <td><%# Eval("title") %></td>
                        <td><%# Eval("Name") %></td>
                        <td><%# Eval("Address") %></td>
                        <td><%# Eval("PhoneNumber") %></td>
                        <td><asp:Button ID="btnView" runat="server" Text="View" class="btn btn-info"/></td>
                        <td><asp:Button ID="btnDownload" runat="server" Text="Download" class="btn btn-info"/></td>
                    </tr>
                </ItemTemplate>
            </asp:listview> 
```
I tried using the container before the `asp:listview` tag but it didnt help in responsiveness. And when the address is long, the table is going beyond the limits of `class:container`.

I want to show something like below.(where view and download are buttons)

![lkstview](https://cloud.githubusercontent.com/assets/13792317/15346436/bf23b2e4-1cea-11e6-976e-e7eb59f9b118.png)

**Comment by patrickhlauke** [comment]
for how-to questions, please refer to StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by nasreekar** [comment]
@patrickhlauke  Sorry Patrik. I tried in SO, but no one responded. So thought will post it here .. But after posting only I realised that this is not the right place. When I tried to delete the post, I couldnt find any delete option. So I had to leave it without removing the post..
