### ISSUE TITLE
Fat split dropup in v4

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#19930]
Suddenly the split dropup got fat:
![screen shot 2016-05-18 at 10 01 29](https://cloud.githubusercontent.com/assets/851745/15351442/9c06572c-1cdf-11e6-8bb8-0f0a569b48c7.png)

**Comment by heruan** [comment]
Seems it needs an additional `dropdown-toggle-split` now: the docs need to be updated.

**Comment by rafalp** [comment]
Per @mdo:

> Hosted docs will be updated when we release the next alpha version. Docs are up to date in the branch.

**Comment by RyanZim** [comment]
@heruan Please close this as per @rafalp. (I've gotten mixed up on that myself!)

Here are the docs: https://github.com/twbs/bootstrap/blob/v4-dev/docs/components/dropdowns.md#split-button-dropdowns.

**Comment by heruan** [comment]
I was referring to the docs in the `v4-dev` branch: the split dropup code is missing `dropdown-toggle-split` class.

**Comment by RyanZim** [comment]
Oops, I didn't notice you were referring to split drop**_up_**s. This does need fixing.

**Comment by mdo** [comment]
Fixed by #20553.
