### ISSUE TITLE
Feature: Disable button after click to avoid users to send the form twice (or more)

### ISSUE THREAD

**Issue by fruvalcaba** [twbs/bootstrap#19939]
Something really common while making Webdevelopment is when a user clicks a button, it never gets clicked once, its always twice or multiple times, which sometimes makes the form element to send the same amount of times which of course creates bugs and duplicated items. 

We always have to input Javascript code on each button to avoid this behavior, which of course is very annoying. It could be great if there is a class, option or label were we can disable the button after the first click. 

We usually do this using jQuery 

`onClick="$('button').prop('disabled', true);"`

But it would be a great improvement in user experience to have a simple label, class, option, etc, which automatically does the job. 

Best regards, 

- Flavio

**Comment by cvrebert** [comment]
It's so trivial and there are so many slight variations on it that I question the value of adding it.
It's also similar to http://getbootstrap.com/javascript/#buttons-stateful , which we've already removed in v4.

**Comment by patrickhlauke** [comment]
agree with @cvrebert - and i can also see a risk in naive devs adding these classes inappropriately, e.g. having the submit button disabled but the form has validation errors so isn't submitting...which results in an inoperable form. especially as this is such a simple thing to actually do by hand yourself, i would say it's not necessarily something i think needs to be in bootstrap core, IMO

**Comment by rafalp** [comment]
I'm strongly opposed, but not on basis of "easyness of implementation" but (ha!) developer friendlyness.

Every time your frontend fromework's js does something with inputs/forms/buttons state, there is JavaScript developer out there who starts thinking about strangling somebody for messing with his state-dom bindings, be it Angular, React or other flavor of the week.

There's so many technology-specific ways to disable button after click, its impossible to do one that'll wont break workflow for whole lot of others.

**Comment by cvrebert** [comment]
Going to close this then, unless someone on Core Team unexpectedly wants to argue in favor of it.
