### ISSUE TITLE
Checkbox and radio input markup unsuitable for advanced styling

### ISSUE THREAD

**Issue by mindplay-dk** [twbs/bootstrap#19931]
With a radio or checkbox input nested inside a label, the CSS `+` selector is unusable - which means you can't do advanced styling with pure CSS and no JS.

Arguably, what you have presently, is simpler, in terms of markup:

```html
<div class="checkbox">
  <label>
    <input type="checkbox" value="">
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
```

It's simpler because you don't need an `id` attribute on the `input` and a `for` attribute on the `label`.

In another sense however, using simpler markup for checkboxes and radio buttons actually *adds* complexity, because it deviates from the way you have to mark up most other inputs - only checkbox and radio inputs are nested inside a label in this way, so it's inconsistent with other markup.

The issue I'm highlighting here though, is the inability to apply advanced styling to these inputs. The following markup offers more flexibility:

```html
<div class="checkbox">
  <input id="option-one" type="checkbox" value="">
  <label for="option-one">
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
```

The current markup doesn't allow CSS selectors such as `input[type="checkbox"]:checked + label`, which would enable us to create advanced CSS effects dependent on the radio/checkbox state - such as what's done here:

https://github.com/flatlogic/awesome-bootstrap-checkbox

There are oodles of "fancy checkbox" CSS libraries and examples out there - if you google something like "bootstrap pure CSS fancy checkbox", you will find that basically every single example out there requires you to deviate from standard bootstrap markup.

It's problematic that bootstrap is designed for markup that isn't useful for the majority of CSS examples out there.

It's also problematic that your recommended/standard HTML pattern for radios and checkboxes deviates from other inputs in this way.

For one, designing a (server side) form rendering helper is tricky, because for radio buttons and checkboxes, we'd like to support bootstrap markup out of the box - but we need options or additional classes or templates that allow developers to switch to alternative markup that actually works for styling.

Would you please consider changing it for Bootstrap 4?

**Comment by mdo** [comment]
We're not making this change for regular checkboxes and radios, but it's now possible with our custom forms. This isn't up to date on our hosted docs, but here's how it looks in `v4-dev`:

<img width="870" alt="screen shot 2016-05-18 at 10 31 55 am" src="https://cloud.githubusercontent.com/assets/98681/15368661/dc6a1ce6-1ce3-11e6-8c2e-fc27a1d2c001.png">

**Comment by mindplay-dk** [comment]
This seems more like a work-around than a solution.

Other than avoiding the `id` and `for` attributes (which is inconsistent with required markup for other types of inputs) what's the advantage of your markup over the markup that most other CSS frameworks and tutorial resources tend to favor?

Is it worth the extra complexity and mental overhead of adding another concept?

Or are you playing avoidance in favor of backwards compatibility?

**Comment by mdo** [comment]
> This seems more like a work-around than a solution.

Call it what you like, the important bits are intuitive functionality (for end users and you as a developer working with Bootstrap). Feedback like this is good, so thanks for continuing to question it.

> what's the advantage of your markup over the markup that most other CSS frameworks and tutorial resources tend to favor?

I don't claim any advantage over others. Your original question was about changing checkbox/radio markup in v4, and I responded with an update on what's been done so far. Custom form elements are the only ones to have received an update to accomplish what you've asked.

Looking at it again, it's kinda lame that we don't offer the same functionality for the default ones. Let me take another look.

> Or are you playing avoidance in favor of backwards compatibility?

Nah man, I throw shit out on a moment's notice in major version bumps :D.

**Comment by mindplay-dk** [comment]
> Feedback like this is good, so thanks for continuing to question it.

Yeah, I'm a persistent nag, sorry ;-)

> I don't claim any advantage over others

If there's no advantage to your approach over the more common approach, which has an advantage in terms of styling, that ought to weigh in favor of a change.

> the important bits are intuitive functionality

That's why I keep arguing consistency - I would find it more intuitive if the tag structure and attributes were consistent with that of other inputs.

Either way, I appreciate your thinking about it :-)

**Comment by janniconl** [comment]
+1 for a `input + label {}` solution/option!

(and make this possible with "BS4 markup": https://codepen.io/CreativeJuiz/pen/BiHzp)

**Comment by mdo** [comment]
I've overhauled the checkbox and radio markup in Alpha 3, but I didn't end up making a change for this to those controls. I'm a big fan of the simplicity of the wrapping label implementation, and you can get most of the customization you need out of it. Everything else can be addressed with custom markup and styles on your end as needed.

(I might also remove that extra wrapper in the custom ones soon, too actually).

**Comment by janniconl** [comment]
Thats a pity

I don't really agree with your "you can get most of the customization you need out of it". AFAIK now there is no way you can style the radio's or checkboxes itself with a CSS-only solution, since you can not use `input:checked + label`. Also mentioned above. So the only thing we can now customize is basically the font. 

Radio's and checkboxes are styled very differently natively in browsers, which is one of the main reasons a lot of people would want to customize them via CSS.

Now we need to write our own HTML or use a JavaScript solution.

Your work is appreciated though :)
