### ISSUE TITLE
Dropdown.prototype.keydown prevents focus and swallows some keystrokes in contenteditable elements

### ISSUE THREAD

**Issue by bo01ean** [twbs/bootstrap#19949]
The click event will fall through and close dropdowns that contain contenteditables.
The space character will fall through and be cancelled in contenteditable elements in dropdowns.

Issue:
http://codepen.io/anon/pen/oxraRw

PR:
https://github.com/twbs/bootstrap/pull/19950

**Comment by bo01ean** [comment]
This has been addressed in a PR, and the build is passing. Not sure what to do next :)

**Comment by vanduynslagerp** [comment]
X-ref #21802

**Comment by XhmikosR** [comment]
This should have been fixed by #24557.
