### ISSUE TITLE
Why only provide option to be completely flex or no flex at all?

### ISSUE THREAD

**Issue by cyphix333** [twbs/bootstrap#19942]
I heard Bootstrap 4 was going to be including support for utilizing flexbox out of the box with the framework and was excited; but not just starting to use the alpha version available I have noticed that using flex is a "use it for everything" or not at all and personally I find that rather annoying.

Why not just add additional classes which use flex rather than floats and then we can pick and choose on what elements we want to use flex on and what ones we prefer to use floats on?

Unfortunately because of thi9s I won't be enabling flex in bootstrap and will continue to applying it manually like I was doing in V3. :(

**Comment by mdo** [comment]
There are utilities being added for `flex` display options, but yes, we're going all or nothing due to the browser support (IE10 and up support flexbox, but not IE9). Even IE10 has some funky bugs with it's implementation, so promoting it further would be signing more folks up for headaches.

Big takeaway from this issue to me is more flex utilities. I'll see what we can do about that.

**Comment by cvrebert** [comment]
Yeah, basically the only reason not to use Flexbox is browser compatibility. Floats are hacky/janky; not sure when/why you'd ever prefer them for reasons not related to compatibility.
So we've had no particular reason to make the Flexbox toggle be component-wise.

**Comment by mdo** [comment]
Creating a new issue to explore what this could look like—see #19945. I'll follow up on that when I can. Unsure if it'll make it into the first v4 release.

**Comment by cyphix333** [comment]
Thanks for the explanation and your consideration at expanding on the implementation via utilities.

I guess the main reason I don't want a full on flex on _everything_ is because of the chance of browser issues and extended debugging; I have worked with flex quite a bit in the past and whilst it's obviously a very powerful tool, it does present the chance of more browser issues even if they claim to have full support.

I guess I just get worried that putting basically a whole site into "flex mode" drastically increases the chance that there will be _some_ clients out there somewhere that has some weird display issue caused by flex; whereas if you only use it when you really need to then the chances get drastically reduced.
