### ISSUE TITLE
Explore adding additional flex utilities

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#19945]
As alluded to in #19942, right now v4 is flex or no flex. Could be rad to allow more opt-in use of flex with additional utilities and examples without enabling flex completely.

**Comment by danimalweb** [comment]
I'd like to see an option to disable flex for a set of divs. 

I have a case where I'm trying to implement a 3rd party carousel and with flex: true in BS I've got all sorts of issues. With flex: false its all good.

I could rewrite the 3rd party SCSS to support flex, however with an option to disable just for the nested container / row / cols would have been an easy win.

**Comment by mdo** [comment]
Punting on the outside utilities for now.
