### ISSUE TITLE
Catching all clicks instead of just left-clicks and their keyboard nav. equivalents considered harmful

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#19957]
At http://getbootstrap.com/javascript/#tabs-usage and http://v4-alpha.getbootstrap.com/components/navs/#via-javascript
IMHO, the following:

``` js
$('#myTab a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
```

should be:

``` js
$('#myTab a').click(function (e) {
  if (e.button === 0) {
    e.preventDefault()
    $(this).tab('show')
  }
})
```

.

This way e.g. middle-clicks still work. And since a keyboard navigation "click" (focus + enter) is also `button === 0` this should pose no problem from an accessibility perspective.

Am I missing something?

**Comment by patrickhlauke** [comment]
You don't want to middle-click an in-page tab to open in a new window/tab, as the logic is not in place to then open that page AND switch to that tab on page load.

**Comment by Herst** [comment]
Ah well, so I did indeed miss something! I missed that the logic for this isn't part of Bootstrap, it's on my site though (I am parsing `window.location.hash` on page load. On a site note, I am also doing `window.history.pushState()` for the tab clicks if available).

You could add a note for this case but if you don't want to bloat up your documentation with stuff having to do with stuff people _might_ do outside of Bootstrap then I totally get it. It was just something I came across in my project and thought might be worth noting.

**Comment by bardiharborow** [comment]
As this is part of the suggested code instead of the framework itself and implements the principle of least astonishment, I am closing this without prejudice as stale. If anyone feels strongly, please reopen.
