### ISSUE TITLE
Tapping on checked checkbox button on Android leaves the button dark until you tap elsewhere

### ISSUE THREAD

**Issue by mylogin** [twbs/bootstrap#19968]
Visual state of buttons changes only when pressed again (outside of the buttons area).
Example: http://getbootstrap.com/javascript/#buttons-checkbox-radio

**Comment by IAmAnubhavSaini** [comment]
Reproducible steps:
In mobile these are the following states:
1. Initial state: no checkbox is selected.
2. Click a checkbox. A dark color appears.
3. Click anywhere else. Earlier checkbox now has a lighter color.
4. Click on the same checkbox again. Dark colored.
5. Click anywhere else. Original color (step 1) appears.

<img width="410" alt="screen shot 2016-05-25 at 10 48 41 pm" src="https://cloud.githubusercontent.com/assets/1573771/15549654/34d56bfa-22cb-11e6-8a15-443c9d810f97.png">
<img width="415" alt="screen shot 2016-05-25 at 10 48 53 pm" src="https://cloud.githubusercontent.com/assets/1573771/15549653/34d009b2-22cb-11e6-91b4-1b27f2b59297.png">
<img width="408" alt="screen shot 2016-05-25 at 10 48 59 pm" src="https://cloud.githubusercontent.com/assets/1573771/15549655/3507a318-22cb-11e6-93de-f5c588e03706.png">
<img width="408" alt="screen shot 2016-05-25 at 10 49 15 pm" src="https://cloud.githubusercontent.com/assets/1573771/15549650/34696fea-22cb-11e6-9fca-b971b942cb27.png">
<img width="405" alt="screen shot 2016-05-25 at 10 49 09 pm" src="https://cloud.githubusercontent.com/assets/1573771/15549652/34cfd816-22cb-11e6-967c-6f7d4e5b0cbc.png">

**Comment by cvrebert** [comment]
@mylogin @IAmAnubhavSaini Which OS are you using? (iOS, Android, WinPhone)

**Comment by mylogin** [comment]
such behavior at least in Android,  Windows Google Chrome (Developer Tools -> device emulator)

**Comment by cvrebert** [comment]
Probably an instance of http://getbootstrap.com/getting-started/#support-sticky-hover-mobile
Not sure how much we can do here.

**Comment by patrickhlauke** [comment]
the only solution would be to implement something like https://github.com/ten1seven/what-input and NOT having focus/hover styles as a result of a touch interaction (something that we're considering for v4)

**Comment by cvrebert** [comment]
Right, or use something like https://github.com/twbs/mq4-hover-shim (currently planned to be an opt-in option for v4).
Closing this as CantFix for v3. Other existing issues track the plans for v4.

**Comment by patrickhlauke** [comment]
> Right, or use something like https://github.com/twbs/mq4-hover-shim (currently planned to be an opt-in option for v4).

However that will likely have problems on multi-input devices if the primary input is the mouse/trackpad, but the user still uses touchscreen (i.e. this https://dev.opera.com/articles/media-features/)

**Comment by cvrebert** [comment]
@patrickhlauke Fair point. Seems like switching to `@media not (any-hover: none)` would address that. Do you see any obvious problem with such an approach?

**Comment by patrickhlauke** [comment]
conceptually that would work. note that at the time of my article for dev.opera, `not (any-hover: none)` and similar didn't actually work in some browsers (can't remember off-hand which ones). instead, I suggested using `not all and (any-hover: none)`.

**Comment by cvrebert** [comment]
@patrickhlauke Were there other use-cases for adding what-input? If there are, then we might as well discuss adding it as an (optional?) dependency and scrapping/overhauling mq4-hover-shim accordingly. If not, then I'll just update mq4-hover-shim to use the `not all and (any-hover: none)` approach.

**Comment by cvrebert** [comment]
Ah, right, #19708 was where you'd brought it up before. Wasn't having luck finding it via GitHub search for whatever reason.

**Comment by patrickhlauke** [comment]
the advantage of using something like what-input over `any-hover` etc is that it's directly related to the input type the user is using right now, while `any-*` only takes a hint from "potential" inputs. currently, for most phone/tablet scenarios, you're probably fine with just the `any-hover` approach, as it's very rare for users to have external keyboard/mouse paired with their device. but for the (increasingly common?) two-in-one / touchscreen laptop scenario, you will always end up with a potential non-hover-capable input in there, making any MQ acrobatics pointless
