### ISSUE TITLE
<button> vs. <a> inconsistency with .btn.btn-primary.center-block

### ISSUE THREAD

**Issue by ThomasBerends** [twbs/bootstrap#19962]
Example: https://jsfiddle.net/z190gj32/2/

When using the button stylings together with `center-block` in a `a` tag, they are inconsistent with using it in a `button` tag. I discovered this issue in the latest alpha. When using `btn btn-primary center-block` in a `a` tag, the a gets stretched horizontally as seen in the jsfiddle.

If you replace the `a` tag by a `div` you get the same results.

**Comment by twbs-lmvtfy** [comment]
Hi @ThomasBerends!

You appear to have posted a live example (https://fiddle.jshell.net/z190gj32/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 63, column 50 thru column 53: Stray end tag ```` a ````.
* line 64, column 1 thru column 6: End tag ```` div ```` seen, but there were open elements.
* line 63, column 1 thru column 45: Unclosed element ```` button ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ThomasBerends** [comment]
Thanks bot!

Here is the revised example: https://jsfiddle.net/z190gj32/1/

**Comment by twbs-lmvtfy** [comment]
Hi @ThomasBerends!

You appear to have posted a live example (https://fiddle.jshell.net/z190gj32/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 63, column 1: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by ThomasBerends** [comment]
Oops. Okay. Here you go: https://jsfiddle.net/z190gj32/2/

**Comment by RyanZim** [comment]
FYI, `.center-block` was removed in #19102.

**Comment by mdo** [comment]
Near as I can tell, this is just HTML behavior. See https://jsbin.com/wofuyag.

The utilities have changed as @RyanZim alluded to, so this might also be moot since Alpha 5 and the other recent changes in `v4-dev`. I'd suggest using the width utilities in conjunction with the new `.mx-auto` for center aligning block level content as needed.
