### ISSUE TITLE
Support multiple targets for tabs

### ISSUE THREAD

**Issue by ukipme-jr** [twbs/bootstrap#19964]
Bootstrap 3 supports multiple targets for tab controls - http://stackoverflow.com/questions/19719653/control-multiple-tab-contents-with-one-nav-tabs 

Bootstrap 4 does not support this, yet, but it is a useful feature. I have added a basic workaround for time being:

file: /js/src/tab.js

line: 116
`
 target = $(selector)[0]
`
to 
`
target = $(selector)
`

line: 138
`
this._activate(target, target.parentNode, complete)
`
to
`
for (i=0; i<target.length; i++) {
    this._activate(target[i], target[i].parentNode, complete);
}
`

**Comment by realconspiracy** [comment]
This workaround does not appear to work in v4alpha3. Can anyone else confirm?

**Comment by nimmolo** [comment]
Maybe this can be done at the same time as [collapse module support for multi-target](https://github.com/twbs/bootstrap/pull/21692)?

**Comment by nimmolo** [comment]
@mdo Maybe this can be done similarly to [#21692 Collapse module supports multi-target](https://github.com/twbs/bootstrap/pull/21692)

**Comment by DanielRHarris** [comment]
Any update on this?

**Comment by patrickhlauke** [comment]
note that this pattern would be quite difficult to make accessible, as there's no equivalent mapping for this sort of thing in regular tab panel constructs...

**Comment by VJ22** [comment]
Is this still open? I can not find any working example and after migrating from 3.x to 4.x , multiple targets for tabs wont work.

**Comment by darylknight** [comment]
+1, just came across a need for this in BS 4 updating an old site.
_rrvw_

**Comment by headkit** [comment]
+1 - this one is important!

**Comment by mkswebdev** [comment]
I need this for a form where some fields are multilingual. I switch the language using tabs.

**Comment by amsimoes** [comment]
Any update on this? Anyone know if it is possible in Bootstrap5?

**Comment by sowinski** [comment]
Any update on this? :)

**Comment by patrickhlauke** [comment]
Are there any actual live examples of the sort of thing people are wanting to do with this? The common format for what a tabbed interface doesn't seem to gel with having multiple things change. maybe we're talking across purposes about what sort of widget/interface authors are trying to achieve? (still maintain that bastardising a regular tabbed interface structure to open more than one panel will not be easy to make sensibly conveyable to assistive technologies).

**Comment by metadaddy** [comment]
@patrickhlauke A common example is code samples on a page, where tabs switch between the programming language on display. You don't want to have to switch from the default to the version you want to see on each set of tabs.

For example: https://developers.google.com/drive/api/v3/folder

**Comment by patrickhlauke** [comment]
i'll admit that to me, that feels a bit niche and perhaps better solved by a tiny bit of custom code (implement each code sample block as a normal tab widget, then hang code off any change to active tab, iterate over any other tab widgets, and switch them accordingly) rather than baking it into the tab component logic directly

**Comment by mirekkukla** [comment]
When I switch tabs, it's often nice to be able to change some user-facing text that says something about the actively selected tab (but lives outside of the tab content). Here's an example:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/903370/192645625-ca559591-a74f-4def-90f4-8b560d524305.png">

While of course it's possible to use some custom code to get the text section "mirror" tab visibility, it'd be nice to be able to do this in via data attributes. The fact that this isn't possible is especially confusion given that collapse component _does_ support [multiple target](https://getbootstrap.com/docs/5.0/components/collapse/#multiple-targets).
