### ISSUE TITLE
Card Reveal functionality in Bootstrap 4

### ISSUE THREAD

**Issue by mohankumargupta** [twbs/bootstrap#19975]
Feature Request

http://materializecss.com/cards.html#reveal

**Comment by praveenpuglia** [comment]
I like the idea of card reveal but I feel it doesnt really fit into bootstrap because this looks like a very material design specific behaviour. Obviously you could implement your own way of doing this with the existing card component in v4. I might be wrong. 

@mdo can say the best about it.

**Comment by mdo** [comment]
For now, I recommend using Animate.css with some custom JS—or something similar—to add this functionality to your projects.
