### ISSUE TITLE
Why has bootstrap 4 made the container sizes smaller?

### ISSUE THREAD

**Issue by cyphix333** [twbs/bootstrap#19979]
I have noticed since working with Bootstrap 4 that the container sizes are now 30px smaller than they were in Bootstrap 3 - for example, the large size in Bootstrap 3 was 1170px and in Bootstrap 4 the respective size is now 1140px.

What happened here?

**Comment by RyanZim** [comment]
Bootstrap 4 adds an extra grid tier. http://v4-alpha.getbootstrap.com/migration/#grid-system You should use 1 breakpoint larger than you would in v3 to achieve the same effect (eg. `lg` -> `xl`). See http://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints.

Please close this. Thanks!

**Comment by cyphix333** [comment]
I'm aware of the added grid tier, but that's not what I was asking. I was asking about the _container size_; this is not the same as the size of the different breakpoints.

**Comment by RyanZim** [comment]
OK, sorry.

I can't find the discussion, but I think the goal may have been to make all the container widths evenly divisible by 12 (simplifies the maths).

- 1170 / 12 = 97.5
- 1140 / 12 = 95

**Comment by cyphix333** [comment]
Hmm fair enough; just found it a little weird they decided to cut off 30px of screen space, something I find a little annoying.

**Comment by VladShcherbin** [comment]
What about `940`, 940 / 12 = 78.333

**Comment by RyanZim** [comment]
> What about `940`

@VladShcherbin Where did you get that number?

**Comment by VladShcherbin** [comment]
@RyanZim [here](http://v4-alpha.getbootstrap.com/layout/grid/#grid-options), `Large` breakpoint

**Comment by RyanZim** [comment]
Oops; didn't see that.

It would probably be best to open a new issue for this.

**Comment by johanneskrtek** [comment]
@RyanZim @cyphix333 I noticed default container widths getting smaller with each Bootstrap iteration too:

Bootstrap 2: 1170px*
Bootstrap 3: 1140px*
Boostrap 4: 1110px*

* Effective space inside respective container sizes

Out of curiosity (and because displays tend to get rather larger), why not choose `1200px` as default `xl` size?

It is evenly divisible and leads to a clean grid column width of `70px` (based on the default grid gutter).
