### ISSUE TITLE
Collapse-navbar-at-sm-screen

### ISSUE THREAD

**Issue by InnocentMonareng** [twbs/bootstrap#19987]
How can I collapse navbar at sm screen and have it behave and styled like the default navbar collapse in the xs screen? Adding the code below in the CSS file help collapse the navbar however the dropdown menus do not behave the same as in the xs screen and the search box is not separated by separators and does not occupy the entire width of the screen. What is the default codes that bootstrap use to collapse the navbar at xs screen? 

/* collapse menu at sm screen */
@media (min-width: 768px) and (max-width: 991px) {
    .navbar-header {
        float: none;
    }
    .navbar-toggle {
        display: block;
    }
    .navbar-collapse {
        border-top: 1px solid transparent;
        box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
    }
    .navbar-collapse.collapse {
        display: none!important;
    }
    .navbar-nav {
        float: none!important;
        margin: 7.5px -15px;
    }
    .navbar-nav>li {
        float: none;
    }
    .navbar-nav>li>a {
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .navbar-text {
        float: none;
        margin: 15px 0;
    }
    /* since 3.1.0 */
    .navbar-collapse.collapse.in { 
        display: block!important;
    }
    .collapsing {
        overflow: hidden!important;
    }
}

**Comment by cvrebert** [comment]
Please use StackOverflow, IRC, or Slack for how-to questions. See https://github.com/twbs/bootstrap/blob/master/README.md#community for links to those fora.
Thanks.
