### ISSUE TITLE
display:table in .clearfix rule may create unwanted gaps between blocks

### ISSUE THREAD

**Issue by thierryk** [twbs/bootstrap#19983]
The clearfix rule has changed to reflect the [latest new clearfix so far](http://cssmojo.com/latest_new_clearfix_so_far/index.html) but as [this more recent article](http://www.cssmojo.com/the-very-latest-clearfix-reloaded/) explains, `display:table` may create unwanted gaps between blocks.

So my suggestion is to replace the existing [_clearfix.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_clearfix.scss):

```
@mixin clearfix() {
  &::after {
    content: "";
    display: table;
    clear: both;
  }
}
```

 with:

```
@mixin clearfix() {
  &::after {
    content: "";
    display: block;
    clear: both;
  }
}
```

**Comment by cvrebert** [comment]
CC: @mdo for review

**Comment by thierryk** [comment]
It may be worth editing the [documention](https://github.com/twbs/bootstrap/blob/v4-dev/docs/utilities/clearfix.md) too as it says:

> Easily clear floats by adding .clearfix to the parent element. Utilizes the micro clearfix as popularized by Nicolas Gallagher. Can also be used as a mixin.

since the new rule does not have much to do with the "micro clearfix" anymore.
