### ISSUE TITLE
Stop using nonstandard MouseEvent.which property

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#19991]
Refs https://github.com/twbs/bootstrap/blob/301dc70e1b04fdb70ac8e83a6906b6b27d7d2235/js/src/dropdown.js#L155
Refs https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which

**Comment by patrickhlauke** [comment]
Closed by https://github.com/twbs/bootstrap/pull/19992 I assume?

**Comment by cvrebert** [comment]
Negatory.

**Comment by cvrebert** [comment]
(All #19992 did was extract a relevant constant. We ought to change the code to use `MouseEvent.button` or `MouseEvent.buttons` instead.)

**Comment by patrickhlauke** [comment]
Ah, sorry 'bout that.

**Comment by hnrch02** [comment]
`which` is normalized by jQuery though: https://api.jquery.com/event.which/

**Comment by Johann-S** [comment]
I think we can close this issue thanks to @hnrch02 answer

**Comment by tkrotoff** [comment]
Now that Bootstrap is not based on jQuery anymore, this issue should be reopened and fixed. MDN clearly states that *"This attribute is deprecated; you should use KeyboardEvent.key instead"*
