### ISSUE TITLE
Consider enabling more new ESLint rules

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#19999]
Refs http://eslint.org/blog/2016/02/eslint-v2.0.0-released#new-rules
Refs http://eslint.org/docs/rules/object-property-newline

**Comment by cvrebert** [comment]
CC: @XhmikosR @hnrch02 @juthilo

**Comment by XhmikosR** [comment]
No new warning with the new rules so far?

**Comment by cvrebert** [comment]
Here's a specific proposal: #20076
