### ISSUE TITLE
When do you plan to release Bootstrap 4?

### ISSUE THREAD

**Issue by 1st** [twbs/bootstrap#20008]
Hi. When do you plan to release new version of Bootstrap 4? It seems that you published news about v4 in August 2015, and soon it will be a year after announcement. Do you have any schedule for release? Thanks.

**Comment by patrickhlauke** [comment]
Sorry, no schedule at the moment.

**Comment by cvrebert** [comment]
Approximate duplicate of #19403.
Also, we published some news in December: http://blog.getbootstrap.com/2015/12/08/bootstrap-4-alpha-2/
