### ISSUE TITLE
Docs rb plugin linenos option malforms output

### ISSUE THREAD

**Issue by davebowker** [twbs/bootstrap#20005]
Hey,

I'm playing around with Jekyll a bit and I'm using your `highlight_alt.rb` code in the docs folder to render an example. I've found that if you add the option `linenos` on the tag it doesn't close the `</code></pre>` properly. 

Simple to test, use your plugin to render some code and add `linenos` option.

I tried to fix it on my install but I'm not so hot with regex.

Cheers,
Dave

**Comment by cvrebert** [comment]
Since we don't currently use the `linenos` option ourselves, it seems unlikely that the team would spend time to fix this. Patches would be welcomed, but for now I've taken the easy way out and just disabled the `linenos` option.
