### ISSUE TITLE
Add .d-flex utility class for `display:flex`

### ISSUE THREAD

**Issue by atu-record** [twbs/bootstrap#20004]
I'd suggest to add display:flex to utilities 
this will be need a lot i guess.

**Comment by cvrebert** [comment]
Do you mean "add one class that just sets `display:flex`", or something else?

**Comment by atu-record** [comment]
exactly - same as the ```.d-block``` in _display.scss
a ```.d-flex``` would be helpfull so we can use the flex aligment classes (_flex.scss) easier outside the grid when flex is enabled.

**Comment by atu-record** [comment]
playing around with flex - i'd realised it would also be helpfull to have responsive display classes
something like 
```
.d-flex-xs
.d-flex-sm
.d-flex-lg
.d-flex-xl
```

**Comment by cvrebert** [comment]
I expect that would probably get rejected, per #18410.

**Comment by mdo** [comment]
Adding *a* flex utility is something we can do I think, but definitely conditional to flexbox mode and what not.

**Comment by mdo** [comment]
This was added in #20934.
