### ISSUE TITLE
v4: Responsive tables not clearly documented

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#20003]
In the migrating guide there is this one line:

> Responsive tables no longer require a wrapping element. Instead, just put the .table-responsive right on the `<table>`.

But on the docs the example is still like in v3.
http://v4-alpha.getbootstrap.com/content/tables/#responsive-tables

Also the "not-wrapping" version does not really work:
![img_2016 05 31_12h02m33s_001_](https://cloud.githubusercontent.com/assets/1368405/15670798/9bd174ce-2727-11e6-95f6-3c7e8f15824f.png)

There is always empty space in the table

**Comment by mdo** [comment]
This was addressed with #21208, which fixed #18612.
