### ISSUE TITLE
need for replicating active button state programmatically?

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#20006]
Looking at http://v4-alpha.getbootstrap.com/components/buttons/#active-state makes me wonder what use cases would require somebody to programmatically show/fake an active state. Any pointers @mdo @cvrebert ? (thinking this part could well be optimized away/removed, simply relying on just `:active` for buttons, or perhaps using an attribute selector hanging off of `aria-pressed=true` instead)

**Comment by patrickhlauke** [comment]
the same thinking (using `aria-pressed=true`) would also apply to the toggle state http://v4-alpha.getbootstrap.com/components/buttons/#toggle-states - this would avoid the need for specific `.active` styles on the button

**Comment by patrickhlauke** [comment]
this is related to some initial exploration of also abandoning the `.active` class for radio/checkbox button groups as per https://github.com/twbs/bootstrap/issues/18874 (which would rely solely on the `:checked` state of the contained `<input>`) - in short, depending on the above answers, the whole lot can be majorly simplified (and the radio/checkbox case would work even without the button plugin altogether, as no JS will be needed anymore)

**Comment by rafalp** [comment]
Personally, I stick to disabling buttons for duration of action, vide `disabled={this.state.isLoading}`, but perhaps keeping button pressed after user clicks it until completion of action may be better UX?

**Comment by patrickhlauke** [comment]
ping @mdo @cvrebert

**Comment by patrickhlauke** [comment]
@mdo @cvrebert any thoughts on this? (sorry, dropped the ball on this and https://github.com/twbs/bootstrap/issues/18874 but hoping to get some momentum going again in coming months)

**Comment by mdo** [comment]
Showing an active state is for anchor based buttons, for whatever reason folks want it. While we can push folks to use `<button>`s, there are instances where people don't want them. We support this kinda stuff for dropdowns and the like.

**Comment by mdo** [comment]
Closing given last reply, but holler at me if we need to do anything else here.
