### ISSUE TITLE
modal: stack overlay option

### ISSUE THREAD

**Issue by leandroruel** [twbs/bootstrap#20014]
would be great if, bootstrap comes with the option of stack modals together with the background overlay, some people are trying to do it with some hacks, like this [StackOverflow Post](http://stackoverflow.com/questions/19305821/multiple-modals-overlay)

example:
```js
$('#myModal').modal('stack');
```

**Comment by rafalp** [comment]
Seems like dupe of #19914

**Comment by patrickhlauke** [comment]
Indeed.

**Comment by leandroruel** [comment]
oh sorry for that
