### ISSUE TITLE
error in your online docs - "Media"

### ISSUE THREAD

**Issue by davealan** [twbs/bootstrap#20010]
Hello,

I may have noticed an error in your online docs on this page

http://getbootstrap.com/components/#media

Under "Media"

Please see the screen shots below.

Thanks.

Dave

![unnamed1](https://cloud.githubusercontent.com/assets/19678661/15696853/26b27d3e-277a-11e6-9dde-493f041dcf9a.jpg)

![unnamed 2](https://cloud.githubusercontent.com/assets/19678661/15696864/38925560-277a-11e6-8fb7-3d7dd6f148b5.jpg)

**Comment by cvrebert** [comment]
The example could stand to be further clarified, but it seems correct as-is.
`.media-middle` forms a duo with `.media-bottom`, both of which control the vertical alignment of the media (in the example's case, the images) relative to the media object as a whole.
They're orthogonal to `.media-left` and `.media-right`, which control horizontal alignment.

Also, none of the documentation's examples use `.media-body` together with another `.media-*` class on the same element, so this doesn't seem to be a one-off error.
