### ISSUE TITLE
:hover pseudo-class still applies in Safari after moving the pointer away over a tooltip

### ISSUE THREAD

**Issue by RopoMen** [twbs/bootstrap#20012]
Hi,

I noticed that when using Safari and hovering over a tooltip in to another element hover state does not disappear from previous element. I made simple [JSFiddle](https://jsfiddle.net/RopoMen/x1zzL5jq/embedded/#Result) from the issue. I also checked [Wall of browser bugs](http://getbootstrap.com/browser-bugs/) and webkit bug list, but I didn't find any similar issue.

I know that this is most likely Safari bug, but I post this over here, because someone may encounter this when using Bootstrap.

This video shows how to reproduce the issue [safari_hover_issue.mp4](https://www.dropbox.com/s/q5lhbfyjzn2zd1p/safari_hover_issue.mp4?dl=0)

Machine: OSX El Capitan 10.11.5 (15F34)
Safari: Version 9.1.1 (11601.6.17)

**Comment by cvrebert** [comment]
Confirmed. Seems to be a bug in Safari's `:hover` pseudo-class implementation. `:hover` shouldn't simultaneously apply to multiple unrelated elements like that.

**Comment by cvrebert** [comment]
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=158340

**Comment by cvrebert** [comment]
Fixed in WebKit Nightly: http://trac.webkit.org/changeset/202324
