### ISSUE TITLE
Pagination .page-item doesn't visually contain the .page-link links

### ISSUE THREAD

**Issue by praveenpuglia** [twbs/bootstrap#20029]
I am not sure if this is all good but as I was fixing a bug on my website, I came to realized that the `<li class="page-item">` in `.pagination` doesn't show to be containing the inner `.page-link` anchors. This is due to the fact that each `.page-link` is floated within `.page-item` **li**. 

I have couple of questions regarding this.( could be silly )
1. Is this a good thing? Shouldn't the parent show to be containing the floated children?
2. Is the float really need to be on the anchors? Couldn't it just be on the `.page-item` **li** ?
3. If at all it's necessary, could we float the **li** too so it shows to be containing the inner anchor? In that case, I can definitely send a PR.
4. Is there already something coming up in alpha 3 addressing it?

**Example Instance :** 
http://v4-alpha.getbootstrap.com/components/pagination/#default-pagination

**Comment by cvrebert** [comment]
CC: @mdo
