### ISSUE TITLE
aria-haspopout on dropdown button but not on button launches the modal

### ISSUE THREAD

**Issue by patriciamarchand** [twbs/bootstrap#20032]
I would like to know why does the dropdown button has an aria-haspopout="true" (http://getbootstrap.com/components/#btn-dropdowns), but not on the button that launches the modal (http://getbootstrap.com/javascript/#live-demo). 

Would it be a good idea to add it?

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by patrickhlauke** [comment]
because as per https://www.w3.org/TR/wai-aria/states_and_properties#aria-haspopup a modal (in the very general sense used most commonly) is not a "popup context menu or sub-level menu"
