### ISSUE TITLE
shown.bs.modal not being fired with "fade"

### ISSUE THREAD

**Issue by rzeh4n** [twbs/bootstrap#20030]
Bootstrap v3.3.6
Same probem as in  #11793. Issue was locked but i found an example and a solution.
It only happens in combination with class fade. See more and simple fix here: http://stackoverflow.com/a/37610417/1053761

**Comment by cvrebert** [comment]
@rzeh4n What OSes and browsers do you encounter the problem in?
Please post a JS Bin or JS Fiddle version of your example.

**Comment by rzeh4n** [comment]
Ubuntu 14.04 64b, Firefox 46, Chrome 51 and Chromium 50. Behaves alway same - shown.bs.modal not being fired when modal also has class <i>fad</i>.
Here it is:
http://jsbin.com/gigoqezano/1/edit?html,console,output

**Comment by twbs-lmvtfy** [comment]
Hi @rzeh4n!

You appear to have posted a live example (http://jsbin.com/gigoqezano/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 20, column 7: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 23, column 7: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s
* line 27, column 3: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-content` must be a child of `.modal-dialog`
* line 36, column 3: [E032](https://github.com/twbs/bootlint/wiki/E032): `.modal-content` must be a child of `.modal-dialog`
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* line 31, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 40, column 9: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by rzeh4n** [comment]
After fixing bootling issues the problem disappeared:
http://jsbin.com/hakakuzave/edit?html,console,output

**Comment by cvrebert** [comment]
Great!
Please take note of our bug reporting guidelines before opening issues in the future:
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports
Thanks.
