### ISSUE TITLE
.media-left / .media-right don't move/float the element to that side of the media object

### ISSUE THREAD

**Issue by amkgo** [twbs/bootstrap#20035]
The example code at http://v4-alpha.getbootstrap.com/layout/media-object/ shows:
```
<div class="media">
  <a class="media-left" href="#">
    <img class="media-object" src="..." alt="Generic placeholder image">
  </a>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
  </div>
</div>
```

The image stays left when changing the class from `.media-left` to `media-right`. The `media-right` example after actually change the DOM order to place the image onto right side.

Can we just remove the `media-left` and `media-right` class and replace them with one `media-header` class? Then the image will show out anywhere according to the DOM order.

Andrew

**Comment by cvrebert** [comment]
> Can we just remove the media-left and media-right class and replace them with one media-header class?

Doubtful. They have different padding: https://github.com/twbs/bootstrap/blob/9c8eb788ac7f79bcbc3b92d39e1408dd4c30ea83/scss/_media.scss#L63-L69

**Comment by amkgo** [comment]
Then is it possible to let the image shows on the left when `media-left` is used, and to the right when `media-right` is used. This will match the meaning of `left` and `right`. Even better, if `media-center` is used, show the image between two `media-content` blocks.

**Comment by mdo** [comment]
Closing as there are no planned changes here.
