### ISSUE TITLE
reset <button> styles by default

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#20082]
`<button>` is a best tag for clickable control elements which are not links (well, just buttons) from semantics and accessibility point of view and it default browser styling is ugly and nobody uses it.

Each time you have a close button, button in custom select or anything else you have to add a custom reset class or use `.btn-link` and add a bit less reset styles anyway. I propose reseting button default styles on `<button>` tag.

**Comment by cvrebert** [comment]
@Mevrael Which specific CSS properties do you propose resetting? We can't really move **all** the `.btn` styles into `<button>` because it would break many third-party widgets.
Compatibility with third-party CSS is why Bootstrap's styles are generally opt-in instead of opt-out.

**Comment by Mevrael** [comment]
@cvrebert I believe it can be a discussion for community but I see at least `border`, `background`, `padding` and may be padding can be > 0 to make a bigger clickable area of all basic buttons for better UX.

**Comment by cvrebert** [comment]
I'm still pretty wary about this, but, CC: @mdo @patrickhlauke

**Comment by mdo** [comment]
Not going to reset the element outright. Definitely will be an opt-in approach like the vast majority of our custom components.
