### ISSUE TITLE
Error: Incompatible units (_popover.scss)

### ISSUE THREAD

**Issue by Tiendq** [twbs/bootstrap#20085]
Got this error when running `grunt dist`

```
Running "sass:core" (sass) task
>> Error: Incompatible units: '/px' and 'px'.
>>         on line 114 of scss/_popover.scss
>> >>   @include border-radius(($border-radius-lg - $offset-border-width) ($border-r
>>    --------------------------^
```

**Comment by cvrebert** [comment]
This doesn't happen with the default Sass variable values.
You've apparently set some of the variables to incorrect values.
Note especially the presumably-erroneous slash in '/px'.
