### ISSUE TITLE
question(docs): may I reuse BS docs for ng2-bootstrap?

### ISSUE THREAD

**Issue by valorkin** [twbs/bootstrap#20080]
Good day
You are doing are great work! (but I am sure you already knew it :) )

I am writing https://github.com/valor-software/ng2-bootstrap
it is just a port of bootstrap + some components
main reason: allow server side rendering
(direct DOM manipulation blocks this, at least for now)

**Question is**: may I reuse your documentation?
Right now I am adding links like `Base specifications: bootstrap 3 or bootstrap 4`
But as a developer having to jump from one doc to another to get things done
is not really convenient, so I would love to add more details, samples and explanations
from mother docs.

I know that it is under MIT licence, but still,
I have a filling that I should ask a permission :)

Thanks in advance

//cc @cvrebert

**Comment by cvrebert** [comment]
> I know that it is under MIT licence

Actually, the docs are under CC-BY-3.0, not MIT.
See https://github.com/twbs/bootstrap/blob/master/docs/LICENSE

> Question is: may I reuse your documentation?

Yes, so long as you comply with the terms of the license, which basically boil down to just giving Bootstrap proper attribution/credit.

Good luck with your project!
