### ISSUE TITLE
Relicense the documentation using CC-BY 4.0

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#20095]
The documentation for Bootstrap is licensed under CC-BY 3.0, since there is a new version, CC-BY 4.0, consider moving to the new updated license.

**Comment by cvrebert** [comment]
Doesn't seem feasible. CC-BY doesn't have an "or any later version" option like the GPL usually does. So we'd have to get permission from all the existing non-trivial contributors to the documentation, which is a huge PITA.

**Comment by cvrebert** [comment]
@twbs/team Any other opinions?

**Comment by atulmishra-one** [comment]
8o

**Comment by XhmikosR** [comment]
I'm not sure what the differences are. Is it just a replacement for 3.0?

**Comment by vanillajonathan** [comment]
https://creativecommons.org/version4/

**Comment by Calinou** [comment]
> CC-BY doesn't have an "or any later version"

AFAIK, such a clause is included by default in the license.

**Comment by cvrebert** [comment]
@Calinou Then please quote the relevant passage. Having skimmed the legalese and having tried searching for the term "version", I didn't find anything.

**Comment by cvrebert** [comment]
From https://wiki.creativecommons.org/wiki/4.0_upgrade_guidelines#Upgrading_from_prior_versions_to_4.0

> Existing content:
> Who owns the rights?
> * [...]
> * If the contributors, **then need permission to relicense**. Without permission (via terms of use or otherwise), then that content remains under prior version.

**Comment by Calinou** [comment]
The [CC BY-SA 3.0 legal code][https://creativecommons.org/licenses/by-sa/3.0/legalcode) does say that:

> You may Distribute or Publicly Perform an Adaptation only under the terms of: (i) this License; **(ii) a later version of this License with the same License Elements as this License**; (iii) a Creative Commons jurisdiction license (either this or a later license version) that contains the same License Elements as this License (e.g., Attribution-ShareAlike 3.0 US)); (iv) a Creative Commons Compatible License. If you license the Adaptation under one of the licenses mentioned in (iv), you must comply with the terms of that license. If you license the Adaptation under the terms of any of the licenses mentioned in (i), (ii) or (iii) (the "Applicable License"), you must comply with the terms of the Applicable License generally and the following provisions: (I) You must include a copy of, or the URI for, the Applicable License with every copy of each Adaptation You Distribute or Publicly Perform; (II) You may not offer or impose any terms on the Adaptation that restrict the terms of the Applicable License or the ability of the recipient of the Adaptation to exercise the rights granted to that recipient under the terms of the Applicable License; (III) You must keep intact all notices that refer to the Applicable License and to the disclaimer of warranties with every copy of the Work as included in the Adaptation You Distribute or Publicly Perform; (IV) when You Distribute or Publicly Perform the Adaptation, You may not impose any effective technological measures on the Adaptation that restrict the ability of a recipient of the Adaptation from You to exercise the rights granted to that recipient under the terms of the Applicable License. This Section 4(b) applies to the Adaptation as incorporated in a Collection, but this does not require the Collection apart from the Adaptation itself to be made subject to the terms of the Applicable License.

(emphasis mine)

**Comment by IdleCoyote** [comment]
Indeed, Calinou. The ability to upgrade is built into the license (you're making modified versions every time someone makes a change.) And CC-BY is compatible with BY-SA. Creative Commons has a nice compatibility chart here: https://wiki.creativecommons.org/wiki/Wiki/cc_license_compatibility so upgrades to BY-SA are easy. But even if you decide not to go that direction, there's always the possibility for do it as mix-content: https://wiki.creativecommons.org/wiki/4.0_upgrade_guidelines#Dealing_with_mixed-version_.28e.g..2C_4.0_and_prior_versions.29_content but this seems perhaps more complicated? One single license (BY-SA) that doesn't have this version problem seems simpler.

**Comment by cvrebert** [comment]
I don't think the ShareAlike license is suitable. We don't want folks who copy-paste example code from the docs to have to license their websites under Creative Commons.

**Comment by XhmikosR** [comment]
So, what are we going to do with this? Is there any compelling reason to
switch to v4?

**Comment by mdo** [comment]
Punting on it for now; not worth the shift in focus from getting literally any kind of release for v4 out :laughing:.
