### ISSUE TITLE
New jQuery version breaks bootstrap

### ISSUE THREAD

**Issue by AmitMY** [twbs/bootstrap#20108]
jQuery released version 3.0.0 stable, no beta, official version.
Bootstrap throws this:
`Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

Can you release a new version for bootstrap (3, not 4) that supports version 3?

**Comment by cvrebert** [comment]
Duplicate of #16834. Please search more in the future. Thanks.
