### ISSUE TITLE
Can't use .input-group subclasses (input-group-xs, input-group-sm etc.) as a mixin in less

### ISSUE THREAD

**Issue by CompadreP** [twbs/bootstrap#20107]
Compiler says they are undefined.
But if I'm adding it through jquery
`$(elem).addClass('input-group-sm')` it works well.

I think it would be better to fix it, because in my case it is the easiest and quite clean way to add necesarry styling to element and it can be useful for others/

**Comment by tomlutzenberger** [comment]
How about code examples?
No one in here will be able to fix anything as long as they don't know what your code looks like.

**Comment by mdo** [comment]
We're not adding any new features or changing anything substantial in v3 at this point. Sorry, only critical bug fixes and docs improvements.
