### ISSUE TITLE
Modal dialog too wide on a viewport with a width between 544px and 600px

### ISSUE THREAD

**Issue by dennify** [twbs/bootstrap#20105]
The modal dialog is too wide on a viewport with a width between 544px and 600px. this causes on current master because of _modal.scss:130

```
@include media-breakpoint-up(sm) {
  // Automatically set modal's width for larger viewports
  .modal-dialog {
    width: $modal-md;
    margin: 30px auto;
  }
  [...]
}
```

The media breakpoint sm is defined to 34em in _variables.scss:91 which is exactly 544px, but the modal width is defined with $modal-md which is 600px (_variables.scss:505)

The output css is (dist/css/bootstrap.css:5176):
```
@media (min-width: 34em) {
  .modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
  [...]
}
```

You can see the problem that the viewport is 544px width, but the modal is 600px width.

Look at the following codepen: https://codepen.io/anon/pen/pbgaVJ
Open your inspector tools and set the iframe (viewport) to width:544px;
`document.querySelector('.result-iframe').style.width = '544px'`

![image](https://cloud.githubusercontent.com/assets/6861243/15960060/496540d8-2efe-11e6-8f22-3eb2c8277e37.png)

**Comment by twbs-lmvtfy** [comment]
Hi @dennify!

You appear to have posted a live example (https://codepen.io/anon/pen/pbgaVJ.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 8, column 1: [E046](https://github.com/twbs/bootlint/wiki/E046): `.modal` elements must have a `tabindex` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dennify** [comment]
Sorry see thisis  a duplicate. I'am not searching closed issues because this error still exists on master

**Comment by cvrebert** [comment]
`master` is Bootstrap v3. For Bootstrap v4, you want `v4-dev`.
