### ISSUE TITLE
Why are padding values precomputed in variables.less?

### ISSUE THREAD

**Issue by olalonde** [twbs/bootstrap#20119]
https://github.com/twbs/bootstrap/blob/master/less/variables.less#L88

```less
//## Define common padding and border radius sizes and more. Values based on 14px text and 1.428 line-height (~20px to start).

@padding-base-vertical:     6px;
@padding-base-horizontal:   12px;

@padding-large-vertical:    10px;
@padding-large-horizontal:  16px;

@padding-small-vertical:    5px;
@padding-small-horizontal:  10px;

@padding-xs-vertical:       1px;
@padding-xs-horizontal:     5px;
```

Why are those values "hardcoded" and how are they computed? It would be more useful if they were derived from the base font size / line height at compile time. I've been trying to change the `$font-size-base` variable but it breaks some things like navbar paddings.

**Comment by mdo** [comment]
I made them up, there's nothing to compute them from.

**Comment by olalonde** [comment]
Ah ok, `Values based on 14px text and 1.428 line-height (~20px to start)` made me think they were somehow based on the base font size / line height.
