### ISSUE TITLE
flex-shrink / flex shorthand in _grid-framework.scss

### ISSUE THREAD

**Issue by marekkobida** [twbs/bootstrap#20114]
_grid-framework.scss

I. Why

```
.col-#{$breakpoint} {
  position: relative;
  flex-basis: 0;
  flex-grow: 1;
  max-width: 100%;
  min-height: 1px;
  padding-right: ($gutter / 2);
  padding-left:  ($gutter / 2);
}
```

instead of

```
.col-#{$breakpoint} {
  position: relative;
  flex: 1 0 0;
  max-width: 100%;
  min-height: 1px;
  padding-right: ($gutter / 2);
  padding-left:  ($gutter / 2);
}
```

II. `max-width: 100%;` really help in IE?

**Comment by cvrebert** [comment]
II. Do you have some reason to disbelieve it?

**Comment by robfrawley** [comment]
@cvrebert I think he was referring to the use of the longer `flex-*` statements instead of `flex: 1 0 0` but I prefer avoiding the shorthand when it isn't 100% clean: I don't think the long-hand `flex-basis` and `flex-grow` should be changed.

**Comment by cvrebert** [comment]
@robfrawley My remark was regarding "`max-width: 100%;` really help in IE?", not their Flexbox question.

**Comment by cvrebert** [comment]
CC: @mdo for a style decision on (I).

**Comment by mdo** [comment]
First bit no longer applicable with #20349.
