### ISSUE TITLE
Explain why rows must be placed within a container

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [twbs/bootstrap#20120]
> Rows must be placed within a .container (fixed-width) or .container-fluid (full-width) for proper alignment and padding.

Why is this? This isn't explained and I haven't found this case to be true.

If I'm not wrong, let's remove the text, and if I am, please explain further.

**Comment by cvrebert** [comment]
They are required so as to counteract the -15px margin on rows. See http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works

**Comment by bjorn-ali-goransson** [comment]
The -15px `.row` margins are for compensating the start and end margins of the `.col`s. So the result is 0.

If I'd have a paragraph somewhere, it would be at x=0. When putting it inside a container-fluid, it would be 15px off (right?), if that's what I'd wanted. (But wanting 15px padding isn't the same as wanting columns... Then, we wouldn't even be needing the `.row`, I guess.)

If I then would decide that the paragraph would be inside a grid system, I'd wrap with .row and .col-sm-x, and the paragraph would still be at x=0.

It seems I don't get it?

**Comment by mdo** [comment]
Some of these details are covered in our grid intro docs: http://getbootstrap.com/css/#grid.

- Content doesn't need to be within a grid column to be lined up down the page.
- Containers have horizontal padding to prevent content from butting right up to the edge of the viewport.
- Rows counteract the left padding of the first column and right padding of the last column to ensure text is completely aligned down the page.

**Comment by bjorn-ali-goransson** [comment]
Hi @mdo,

1 Yes, I get that I don't need a grid to have a full column. (I think that's what you mean)
2 Yes, this is the dual purpose of _containers_. Restricting width (in case its' not fluid) and providing padding for the main content.
3. Yes, this is the purpose of _rows_.

But all this doesn't answer the first question. It's like assuming I always want 15px padding. Who said I want 15px padding on my content? All right-columns don't have rounded borders you know (let's imagine something resembling the metro-style UI elements), so they may touch the sides of the page quite nicely.

(there's also the question of why the navbar has a default border that I need to override to get rid of, a whole nother question but also touches my opinion that TWBS sometimes makes a little too large assumption of how the UI should look)

It's (unless I'm misunderstanding) like saying: "**For the grid to work**, it's required you need a container class, (because we know you want 15px padding on all your content) --- and without a 15px padding the grid doesn't work (because then you won't have 15px content and your grid won't work)"

How about this example:

```

<div class="container">
  <div class="row">
    <div class="col-sm-6">


      <h2>Some content</h2>

      <div class="row">
        <div class="col-sm-6">
          <p>Some content in the first subcolumn ...</p>
        </div>
        <div class="col-sm-6">
          <p>Some content in the second subcolumn ...</p>
        </div>
      </div>
      
      <p>... and here's your CTA: <a class="btn btn-primary" href="/buy">Hello</a>


    </div>
    <!-- lets imagine there's another column here -->
  </div>
</div>

```

I'm not making any guarantees of the merchantibility of that code - but for the "sub grid" to work, it shouldn't require a container-fluid class, should it? (Unless I want 15px padding, of course ... which has really nothing to do with the actual **grid** being functional)

**Comment by bjorn-ali-goransson** [comment]
In addition, @cvrebert , I think the helloerik.com article is very misleading when stating "Never use a row outside a container, it won’t work."

Stop the madness?

The requirement paragraph (in the docs) should IMO be refactored into explaining the following:

1) When adding a .container, you are not only centering the content (and restricting its width), but you're also adding horizontal padding (15px by default) in order for the inner content to never directly touch the window edges. If you want the padding without centering, use .container-fluid.

2) The former also applies to grids. While grids (that is, a hierarchy of rows and columns) add padding between each non-collapsed column, they do not automatically add padding to the outermost sides of the grid. To achieve this padding, wrap the grid in a .container or .container-fluid element.

**Comment by Clovenhoof** [comment]
I've tackled this problem by using custom container elements instead, since the default containers don't really take up this issue that you just might want to have the content spanning full out without the 15 px margin.

The original containers work all well as long as you don't have mixed content that should hit the edges (common with images, or navigation/footers for instance). I do think this is a fair design decision, but unfortunately a lot of graphic designers want to provoke it.

I think it's a valid solution to use your own custom container setups as long as you know what the implications are. Wrapping the container in a graphical container (background, etc, etc) is also a better solution than applying custom css directly to the bootstrap classes, since that tends to give issues with the media queries.

**Comment by bjorn-ali-goransson** [comment]
@Clovenhoof Jean, I get where you're coming from, thanks for the input ...

This is really more about "**let's not say that containers are strictly required for grids when they're actually not**" than finding a workaround, though.

**Comment by bjorn-ali-goransson** [comment]
(Not saying that grids may never benefit from parent containers, though.) @mdo ?

**Comment by vikaskyadav** [comment]
For proper alignment of divs and it provides a way to deal with the default margin of 15px as stated in above answers.

**Comment by bjorn-ali-goransson** [comment]
So what exactly is this proper alignment of divs that the container class
makes possible?

onsdag 6 juli 2016 skrev Vikas Kumar Yadav <notifications@github.com>:

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by bjorn-ali-goransson** [comment]
For the record, yesterday I found out why .container-fluid is required.

# If you don't have a .container-fluid, there will be a -15px push of the right-most column out of the screen on the right side, causing a horizontal scrollbar to appear on the body/window.

See this ticket for more info: https://github.com/twbs/bootstrap/issues/10711
