### ISSUE TITLE
.bg-inverse's text color and background-color are the same, making text unreadable

### ISSUE THREAD

**Issue by jeradrutnam** [twbs/bootstrap#20128]
I have fix this. It's available in the PR: https://github.com/twbs/bootstrap/pull/20130.

Please review the fix, https://github.com/jeradrutnam/bootstrap/commit/f5f98ec2452a63485236ef7ef0cada790b62be25

**Comment by cvrebert** [comment]
Please try to keep to one issue fix per PR in the future.

**Comment by jeradrutnam** [comment]
Hi Chris, Noted. I'll revert the commit and add to a new PR. :)

**Comment by jeradrutnam** [comment]
Hi Chris, I Updated the PR. :)

**Comment by mdo** [comment]
PR was merged into Alpha 4, so closing out.
