### ISSUE TITLE
border-color of .list-group inside .card doesn't match .card's border-color

### ISSUE THREAD

**Issue by eproxus** [twbs/bootstrap#20129]
In the Bootstrap 4 example where a list group is included in a card (https://v4-alpha.getbootstrap.com/components/card/#content-types) the border color of the card is `#E5E5E5` but the border color of the list items is `#DDDDDD` which makes them stand out from the card.

Operating system: OS X 10.11.5
Browser: Chrome 51.0.2704.84 (64-bit)

**Comment by cvrebert** [comment]
You must have great eyesight to notice such a subtle difference 😄

**Comment by eproxus** [comment]
Thank you! :smile:
