### ISSUE TITLE
Add color support for SVG-Icons in Navbar

### ISSUE THREAD

**Issue by Skaronator** [twbs/bootstrap#20124]
Would be nice to have a native SVG Icons color-support for the nav-bar. It would just required the `fill` command parallel to the `color` command. 

Here is how I made it for my site on Bootstrap v3:
```
.navbar-inverse {
	.navbar-nav {
		> li > a {
			fill: #9d9d9d;

			&:hover,
			&:focus {
				fill: #fff;
			}
		}
		> .active > a {
			&,
			&:hover,
			&:focus {
				fill: #fff;
			}
		}
		> .disabled > a {
			&,
			&:hover,
			&:focus {
				fill: #444;
			}
		}
	}
}
```

default (the SVG is actually black) | with fill command
![image](https://cloud.githubusercontent.com/assets/2886913/16101731/fa1cf074-3368-11e6-8cd5-8c8789a70dac.png)
default (the SVG is actually black) | with fill command
![image](https://cloud.githubusercontent.com/assets/2886913/16101733/fc900d28-3368-11e6-9556-8dccfc399839.png)

[talking about this part in the v4 source code](https://github.com/twbs/bootstrap/blob/ac1ea8c26ccb4b65d14bf207974854ca993ea4e5/scss/_navbar.scss#L166-L232)

**Comment by cvrebert** [comment]
Since we no longer include any icons in v4 (modulo the form validation icons, which aren't freestanding), I'm skeptical about this. We don't want to potentially interfere with third-party SVGs/icons. Might as well leave icon stuff to the icon experts, IMHO.

**Comment by mdo** [comment]
Use `fill: currentColor` and you won't need to specify any particular colors again other than the parent link's `color`.

**Comment by Skaronator** [comment]
Oh didn't know about `fill: currentColor`. Works fine and no longer need to link the colors! Thanks @mdo
