### ISSUE TITLE
SOLUTION  with js-> FORM FILE -> FILENAME INJECTION

### ISSUE THREAD

**Issue by ixms** [twbs/bootstrap#20132]
An idea how to do this:

> Heads up! The custom file input is currently unable to update the Choose file… text with the filename. 
> Without JavaScript, this might not be possible to change, but I’m open to ideas.
http://v4-alpha.getbootstrap.com/components/forms/     //bottom of the page

Tell me what you're thinking in comments below, that's how I've fixed it for my self for now :)

HTML CODE:
```
<div class='col-xs-4'>
      <label class="file col-xs-12">
              <input type="file" name='file' id="file">
              <span class="file-custom"></span>
      </label>
</div>
```

SCRIPT CODE:
```
$('.file input:file').change(function (){
	var fileName = $(this).val();
	$('.file span').replaceWith('<span class="file-custom_2" style="position:absolute;right:0;top:0;text-align:right;display: block;padding: .375rem .75rem;font-size: 1rem;line-height: 1.5;color: #55595c;">'+fileName+'</span>')
	$('.file').css({'background-color': '#fff','background-image': 'none','border': '1px solid #ccc','border-radius':'.25rem','overflow':'hidden'});
});
```

Hope you'll notice this, cuz it may be helpful for ya =)

**Comment by cvrebert** [comment]
I think you may have misunderstood the remark in the docs.
It's reasonably clear how the "show the actual chosen filename" feature could be properly implemented in JS. The challenge posed in the comment is whether a pure-CSS solution is possible. (It most likely isn't.)
We appreciate your enthusiasm though.
