### ISSUE TITLE
Request: ADD typehead or auto complete input boxes with ajax json support

### ISSUE THREAD

**Issue by Davidthecoolsmartguy** [twbs/bootstrap#20138]
Request: ADD typehead or auto complete input boxes with ajax json support

**Comment by cvrebert** [comment]
We had a buggy typeahead widget in Bootstrap v2, and removed it in Bootstrap v3. We lack the time+manpower to maintain (a quality implementation of) such a complex widget ourselves.
We recommend independent projects such as http://selectize.github.io/selectize.js/ or https://github.com/twitter/typeahead.js instead.
X-Ref: #7805
Please search existing issues more thoroughly in the future. Thanks!
