### ISSUE TITLE
Slack invite app is down

### ISSUE THREAD

**Issue by olalonde** [twbs/bootstrap#20131]
http://bootstrap-slack.herokuapp.com/ returns `An error occurred in the application and your page could not be served. Please try again in a few moments.`

Just a heads up

**Comment by mdo** [comment]
Restarted dynos, back up. Sorry, and thanks!

**Comment by C-Lodder** [comment]
It's still down

**Comment by mdo** [comment]
Updated the app and redeployed. Let's see if that helps.

**Comment by mdo** [comment]
Annnnnnd down again.

**Comment by olalonde** [comment]
Yep, still down 😭

**Comment by mdo** [comment]
Back up again I think. Let's see how this one goes—switched to a fork of the Slackin project that apparently doesn't have the Heroku deploy issue I'm running into.

**Comment by mdo** [comment]
Appears to be alright, still up after 6+ hours. Closing out.
