### ISSUE TITLE
[stupid question] what is the reason custom.scss being before variables.scss ?

### ISSUE THREAD

**Issue by Izopi4a** [twbs/bootstrap#20134]
https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss#L9

in bs4 you can easily change bs variables which is very nice, but whatever you set bootstrap will automatically with override it. 

I think it should be :

```
@import "variables";
@import "custom";
@import "mixins";
```

pard me if i am wrong i suck at scss

**Comment by cvrebert** [comment]
We use `!default` on our variable declarations, so they shouldn't override your customized values AFAIK.

**Comment by Izopi4a** [comment]
ahaaa got the idea.... sorry for the stupid question, and thx.
