### ISSUE TITLE
textarea autoresize class

### ISSUE THREAD

**Issue by MINORITYmaN** [twbs/bootstrap#20135]
hi,
i know there is a plenty of jQuery plugins for:
`$('textarea').autoResize();`
but having an intergrated `.auto-resize` class for the bootstrap.js would be a overload?

cheers, Stefano

**Comment by robfrawley** [comment]
I don't think adding an additional JS *dependency* on Bootstrap is a great idea. With that said though, most auto resize plugins are relatively small and could be forked and added to the bootstrap JS: https://github.com/jackmoore/autosize/blob/master/src/autosize.js

I don't have much of an opinion on whether the feature itself is added: I just object to the idea of adding another external JS dependency for developers to worry about.

**Comment by mdo** [comment]
No plans to integrate something like this in Bootstrap 4. Thanks for the suggestion though!
