### ISSUE TITLE
Edge of <select> dropdown menu cut off in Firefox 47

### ISSUE THREAD

**Issue by end-user** [twbs/bootstrap#20147]
In FF 47.0, it looks like the select drop-down's options box border isn't right.  Can anyone confirm this?

[screenshot](http://i.imgur.com/uV5NTYC.png?1)

**Comment by patrickhlauke** [comment]
confirmed. seems to vary depending on window width (in some widths it shows, others it doesn't). rounding error perhaps

**Comment by cvrebert** [comment]
Perhaps related to https://bugzilla.mozilla.org/show_bug.cgi?id=545685 ?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
