### ISSUE TITLE
Why does horizontal form have padding-left?

### ISSUE THREAD

**Issue by tfarina** [twbs/bootstrap#20153]
This is the most annoying thing in bootstrap. Why does it not align with the left side? 

If we have the following:
```html
<h3>Foo </h3>
<form class="form-horizontal">
 <div class="form-group ">
  <label class="col-sm-2 control-label">Title</label>
   <div class="col-sm-5">
     <input type="text" name="title" class="form-control" />
    </div>
  </div>
</form>
```

I want the "T" of "Title" to align with the "F" from "Foo". I'm very surprised this is not the default behavior.

**Comment by mdo** [comment]
The labels are right-aligned by designed. Override if you need to with `text-align: left;`.
