### ISSUE TITLE
how can I split the page in two?

### ISSUE THREAD

**Issue by tfarina** [twbs/bootstrap#20154]
This does not work:

col-sm-3 col-md-2 sidebar
col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main

**Comment by tfarina** [comment]
Well, it does, but it makes pretty hard to control the margins/paddings between the columns. And I can't get to set it up the way I want.

**Comment by patrickhlauke** [comment]
For "how-to" type questions, please refer to StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
