### ISSUE TITLE
Make active tab behaviour independent of html structure

### ISSUE THREAD

**Issue by alberto** [twbs/bootstrap#20156]
In v4, the active tab selector is defined as:

```
ACTIVE_CHILD: '> .nav-item > .active, > .active',
```

The first selector forces us to use the `nav-item` class for the tab, which I would like to avoid in my case. 

The second selector, which applies to the tab, not the link, doesn't seem to work correctly (see https://github.com/twbs/bootstrap/issues/18566)

Is the descendant selector really needed?

**Comment by sereneramesh** [comment]
hi

**Comment by srvance** [comment]
I'm running into problems with this, as well, but perhaps in the opposite direction. In most cases, putting `active` on the item with `nav-item` works, but in some cases like tabs, it needs to be on the `nav-link`. On the surface, it appears inconsistent, but I may not be seeing the pattern. Understanding this is important for ember-bootstrap, where we're re-implementing the JS behaviors in an Ember-y way.
