### ISSUE TITLE
form-group for input, select and button

### ISSUE THREAD

**Issue by cristian-sima** [twbs/bootstrap#20158]
This is a very nice feature to have

**Comment by cvrebert** [comment]
I'm sorry, but a single terse sentence isn't enough detail to go on. Please provide more info, as [our issue template advised you to](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md).

Please describe the requested feature **in detail**, and include a diagram or mockup if possible.

**Comment by cristian-sima** [comment]
It seems it works :D Thanks
