### ISSUE TITLE
the error of Chinese translation about Modal

### ISSUE THREAD

**Issue by faryang-sh** [twbs/bootstrap#20162]
the chinese transition about Modal，the JavaScript components，have a error.the error is:"along with"  translated into "或者",which means or.this error maybe make users doubt. 
the website is http://www.bootcss.com/ ,which is famous chinese website about usage of bootstrap

![image](https://cloud.githubusercontent.com/assets/14032423/16301655/15b9a4c4-3979-11e6-963f-c92d529209a5.png)

**Comment by patrickhlauke** [comment]
we don't maintain any of the translation sites. I'd suggest trying to get in touch with that site's maintainers directly.
