### ISSUE TITLE
card-columns card over-flow content is not visible

### ISSUE THREAD

**Issue by raghuam** [twbs/bootstrap#20161]
v4-alpha .card-columns .card (over-flow content is not visible) i want show more details content in position absolute element inside card, but its visible out side the card? 
![screenshot-over-flow-content-not-visible](https://cloud.githubusercontent.com/assets/12889300/16301725/8ef1ae28-3964-11e6-8e68-1b88ac8dbf02.jpg)

**Comment by cvrebert** [comment]
Please post a JS Bin or other live example that demonstrates the problem.
We can't debug screenshots.

**Comment by raghuam** [comment]
Hi,

here is the basic bootstrap cards, JS Bin link http://jsbin.com/kuxiqojadu/1/edit?html,css,output

**Comment by twbs-lmvtfy** [comment]
Hi @raghuam!

You appear to have posted a live example (http://jsbin.com/kuxiqojadu/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by raghuam** [comment]
Hi,

here is the basic bootstrap cards, JS Bin link http://jsbin.com/navinekore/1/edit?html,css,output

**Comment by cvrebert** [comment]
@raghuam What browser and OS are you using?
In OS X Chrome, the red boxes aren't below the cards, they just exceed the width of the card and their text gets cut off. If I remove the `width: 600px;` style from your example, the red boxes get displayed in a reasonable way (fit to the bounds of the card; text line-wraps properly).

**Comment by raghuam** [comment]
@cvrebert Im checking in windows 8 chrome and Mozilla Firefox.
the red box position absolute i want to show bigger than card size, when we have position absolute that can be overlap with parent relative container ? but in this cards its showing only inside the card, i want t show content bigger than card size, please check and let me know how i can fix this issue....

**Comment by cvrebert** [comment]
Reduced testcase: http://jsbin.com/yovihuf/1/edit?html,css,output
Chrome, Safari, and Edge 13 all clip the `position:absolute` child at the middle of the column gap.
Firefox doesn't clip it, but draws the 2nd and 3rd columns on top of it (with regard to the z-axis).

**Comment by raghuam** [comment]
Is there any fix can be done ?

**Comment by cvrebert** [comment]
Filed Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1282363

**Comment by cvrebert** [comment]
> Is there any fix can be done ?

Assuming you mean "Then how do I make my `position:absolute` element get displayed wider than the boundaries of its column?", it's unclear whether it's possible to accomplish that using CSS3 Multi-column Layout.

Unfortunately, we don't really answer "how-to" questions on this issue tracker. For further assistance with this, try asking the community on StackOverflow, IRC, or Slack. See https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community for links.
Good luck.

**Comment by raghuam** [comment]
@cvrebert its bug with cards columns? position:absolute element get displayed wider than the boundaries of its card.

**Comment by cvrebert** [comment]
The bug lies in the web browser(s), as opposed to Bootstrap. `.card-columns` is implemented using [CSS Multi-column Layout Module Level 1](https://drafts.csswg.org/css-multicol/). Specifically:
```css
@media (min-width: 544px) {
  .card-columns {
    -moz-column-count: 3;
    column-count: 3;
    -moz-column-gap: 1.25rem;
    column-gap: 1.25rem;
  }
}
```

All major browsers except Firefox currently clip your `.absolute-content` to the boundaries of the column it's within. It's not clear to me whether Firefox or Chrome/Safari/Edge is correct according to the standard here.

**Comment by cvrebert** [comment]
Added to the [Wall of Browser Bugs](http://getbootstrap.com/browser-bugs) in #20183.
