### ISSUE TITLE
Navbar displays as expanded in landscape on Android Chrome

### ISSUE THREAD

**Issue by Xmashine** [twbs/bootstrap#20164]
### Bootstrap Rendering error on Mobile Chrome
Site: http://v4-alpha.getbootstrap.com

These screenshots are on getbootstrap.com, stable relase and the bug isn't present

![screenshot_20160623-190839](https://cloud.githubusercontent.com/assets/18101935/16312817/c085ceb2-3976-11e6-99ff-bc4e06b17185.png)
![screenshot_20160623-191259](https://cloud.githubusercontent.com/assets/18101935/16312818/c0865f6c-3976-11e6-81f5-43cc26350f7d.png)

Also, on alpha site the `navigation bar` will be automatically expanded

![screenshot_20160623-190826](https://cloud.githubusercontent.com/assets/18101935/16312816/c0841dc4-3976-11e6-83dc-148164fbb0e9.png)

**Comment by cvrebert** [comment]
Covered by #19280.
