### ISSUE TITLE
fieldset's min-width:0 causes the cordova android app to overflow screen width

### ISSUE THREAD

**Issue by Atralbus** [twbs/bootstrap#20170]
Hi, I have an angularjs app that i use cordova for android and ios devices. Normally the table is responsive and horizontally scrollable within the screen's innerWidth. But there is a problem only occurs in some android devices(in the browser and ios it's not happening). 
Scrollable table overflows screen's width.

When I remove fieldset's "min-width: 0" style the problem doesn't occur.

[stackoverflow link](http://stackoverflow.com/questions/38019013/css-style-min-width0-causes-the-cordova-android-app-to-overflow-screen-width)

Some part of the code available at the stackoverflow link. If needed I can share the detailed code snippet.

**Comment by cvrebert** [comment]
What version of Android and what version of the Android WebView?

**Comment by Atralbus** [comment]
Android version: 4.3
And I guess Android webview version: 534/30 (http://jimbergman.net/webkit-version-in-android-version/)

Native browser's user agent: "Mozilla/5.0 (Linux; U; Android 4.3; en-us; GT-I9300 Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30".

**Comment by cvrebert** [comment]
Unfortunately, we don't officially support the Android Browser/WebView [in Bootstrap v3](http://getbootstrap.com/getting-started/#support-browsers).
And [in Bootstrap v4](http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#mobile-devices), we require Android v5.0+, so your older Android version isn't supported there either.
For further assistance, you can try the `twitter-bootstrap-3` tag on StackOverflow, or try asking on IRC or Slack. See https://github.com/twbs/bootstrap#community for links.
Good luck!
