### ISSUE TITLE
Content in a new row is not aligned

### ISSUE THREAD

**Issue by dams666** [twbs/bootstrap#20177]
Hi
I'm trying to display images, but the result is not as expected
the fifth picture should appear on the bottom left, and be aligned with the content above.

The HTML file is attached to this message

thank you in advance for your help

[Unaligned.zip](https://github.com/twbs/bootstrap/files/333562/Unaligned.zip)

**Comment by patrickhlauke** [comment]
for how-to/troubleshooting questions, please use stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
