### ISSUE TITLE
Fix jQuery Migrate 3 warnings

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20181]
[**EDIT:** Upon fixing human error in following the instructions, no warnings are issued.]

Refs #19433.

**Comment by TheBuzzer67** [comment]
Not supposed to be uncompatible?

**Comment by cvrebert** [comment]
> jquery-migrate-3.0.0.js:62 JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort

Apparent false positive. jQuery 2.2.4 still uses unique internally in one place:
https://github.com/jquery/jquery/blob/2.2-stable/src/traversing/findFilter.js#L76
@dmethvin FYI.

**Comment by cvrebert** [comment]
Erm, my bad, nevermind about `unique`.

**Comment by cvrebert** [comment]
> Not supposed to be uncompatible?

Well, there could be deprecated-but-still-present APIs, but fortunately we don't seem top be using any of them.
