### ISSUE TITLE
Popover problem when upgrading from 3.3.0 to 3.3.6 

### ISSUE THREAD

**Issue by zhaojinhui** [twbs/bootstrap#20186]
I call the popover function this way:

```js
$('body').popover({
    selector: '.js-popover',
    html: true,
    title: 'test',
    content: function () {
        someinfo
    }
})
```

in the old version 3.3.0 it could work fine, but in the 3.3.6 it can't. 
I check the bootstrap.js and compare the code:

```js
function Plugin(option) {
    console.log(option);
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.popover')
      var options = typeof option == 'object' && option
      var selector = options && options.selector

      if (!data && /destroy|hide/.test(option)) return
      // 3.3.6 can't work well
      //if (!data) $this.data('bs.popover', (data = new Popover(this, options)))
      
      // 3.3.0 could work well
      if (selector) {
        if (!data) $this.data('bs.popover', (data = {}))
        if (!data[selector]) data[selector] = new Popover(this, options)
      } else {
        if (!data) $this.data('bs.popover', (data = new Popover(this, options)))
      }
      //////////////
      
      if (typeof option == 'string') data[option]()
    })
  }
```
 the Popover function seems need to pass to a data[selector] elements instead of data. Wondering if I use it the right way or this is a bug? Thanks.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
