### ISSUE TITLE
Popover can't show number as content

### ISSUE THREAD

**Issue by Kirill89** [twbs/bootstrap#20193]
If `data-content` attribute specified as number (like `data-content="123456"`), will be an error.

Error text: `Uncaught Error: TOOLTIP: Option "content" provided type "number" but expected type "(string|function)".`.

[Demo on jsfiddle.](https://jsfiddle.net/1bq7dzps/2/)

OS and Browser: **Mac OS X, Chrome 51.0.2704.106 (64-bit).**

**Comment by design8383** [comment]
There are, in if it is the number should be taken to operate. Add space in the back, if you want to use to "123456".

**Comment by Kirill89** [comment]
@design8383 your solution works well, but looks like a workaround.

I think it's a bug because `data-content` attribute can't be anything except string.

**Comment by design8383** [comment]
@Kirill89  Your 're right. This bug is not a solution. A simple tip that can only be used.

**Comment by mdo** [comment]
Could also be related to #18641?

**Comment by vanduynslagerp** [comment]
I don't think it's related to #18641.
#20210 seems to be the appropriate fix as the problem come from an explicit restriction on the format of the `data-content` here https://github.com/twbs/bootstrap/pull/20210/files#diff-e9010e9ff0ddb6c88e5442067e24aa1fL37
