### ISSUE TITLE
Make `npm run shrinkwrap` work on Windows too

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#20192]
Maybe things will be OK with July's Windows 10 update, but until then on Windows `mv` doesn't exist.

`cp` and `rm` doesn't exist either so I can't think of a native workaround.

So I can only think of these solutions:

1. `npm shrinkwrap` accepts a path; I doubt this is reported or if so, it will change
2. save npm-shrinkwrap.json in root
3. try to find a grunt or a shell-js solution

/CC @cvrebert

**Comment by cvrebert** [comment]
I guess you could give https://github.com/shelljs/shx a shot. I think they had yet to publish a release the last time we discussed this; looks like they have now.

> 1. npm shrinkwrap accepts a path; I doubt this is reported or if so, it will change

Heck, if it merely supported stdout, we could simply use stream redirection. It's a real shame it doesn't support this.

**Comment by XhmikosR** [comment]
I do have a workaround; I'm using MSYS. But since everything is truly cross-platform, I just feel we need to make this work out of the box.

How would you feel about a shell-js solution? Or saving npm-shrinkwrap.json in root? I know the downsides but I still believe we should have it in root. This will make things more controllable IMO.

**Comment by cvrebert** [comment]
> I just feel we need to make this work out of the box.

Why? Nobody uses `npm run shrinkwrap` besides us Core Team members.

> How would you feel about a shell-js solution?

I'd be fine with it. Like I said, shx should probably do the trick.

> Or saving npm-shrinkwrap.json in root?

Still opposed to that.

**Comment by XhmikosR** [comment]
All right, I'll check out shx and make a PR.

**Comment by XhmikosR** [comment]
Ported to v3 too.
