### ISSUE TITLE
other Button focus issue after modal dialogue close with bootstrap

### ISSUE THREAD

**Issue by shivanitatineni** [twbs/bootstrap#20207]
Button focus issue:bootstrap
hi I have 2 buttons in main page.upon clicking one button modal dialogue opens,and I close it using data-dismiss option for close button in modal dialogue.
Here is the problem.
upon closing the modal window focus should shift to next button in main page.
before I had java script code
formname.buttonname.focus();
this is not working....any help is appreciated...

Thanks
Shivani

**Comment by cvrebert** [comment]
Please follow the "When reporting a bug" instructions in https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md

**Comment by shivanitatineni** [comment]
Hi,

i have a testcase 
save the file as html and run it

[sample.txt](https://github.com/twbs/bootstrap/files/340341/sample.txt)



Thanks
Shivani

**Comment by RyanZim** [comment]
@shivanitatineni **Read the instructions.**

> When reporting a bug, include:
...
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

_Do **not** use GitHub's file upload feature._

**Comment by cvrebert** [comment]
@RyanZim You are correct of course, and I really appreciate all your help with triage, but please be a little gentler with your phrasing going forward; "Read the instructions" in bold was overkill.
We definitely prefer JS Bin etc., but an example's completeness and level of reduction are way more important than its format.

**Comment by RyanZim** [comment]
@cvrebert You're right, my apologies to @shivanitatineni.

**Comment by shivanitatineni** [comment]
I. Called. Focus. Method
But. No. Use

**Comment by shivanitatineni** [comment]
Thank. You. So. Much


Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: Ryan Zimmerman <notifications@github.com> Date: 7/1/16  7:48 PM  (GMT-05:00) To: twbs/bootstrap <bootstrap@noreply.github.com> Cc: shivanitatineni <shivanitatineni@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [twbs/bootstrap] other Button focus issue after modal dialogue
  close with bootstrap (#20207) 
I hope I'm understanding what you're trying to do (correct me if I'm wrong). If you are trying to make the second button focused when the modal is closed, you have to call focus() after the modal has been closed since clicking the close button focuses that instead.

Here is a JSBin that should do that: https://jsbin.com/hixemuhata/1/edit?html,output (I removed the <form> element to make JSBin happy.)

Let me know if I misunderstood your question.

**Comment by shivanitatineni** [comment]
RyanZim,

I have a question.
if I need to do button focus in parent page rather than in modal dialog code can I do it?
because in my application I call modal dialog from multiple pages  hope you understand the problem..
if not please update we can talk
Thanks
Shivani

**Comment by RyanZim** [comment]
@shivanitatineni I'm not sure what you're asking.

**Comment by mdo** [comment]
Closing as stale.
