### ISSUE TITLE
Flexbox grid columns not full width at small viewport sizes

### ISSUE THREAD

**Issue by kiwi1342** [twbs/bootstrap#20206]
Hi,

I noticed that using the flex grid, columns at small sizes don't fill the full width.

See: http://codepen.io/anon/pen/vKxQVx

set the grid to use flexbox and resize the window to small size. Notice how the columns don't fill the width. Shouldn't  the columns have `flex-grow: 1;` ?

thanks

**Comment by cvrebert** [comment]
May I ask why you didn't include your OS and browser versions [as requested in the issue template](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md)?

**Comment by kiwi1342** [comment]
Sorry, I forgot :(

OS: mac OS X (latest version)
browser: Chrome

**Comment by mdo** [comment]
This should be fixed by #20349.
