### ISSUE TITLE
Add a rating component?

### ISSUE THREAD

**Issue by jeradrutnam** [twbs/bootstrap#20204]
If $subject is not there, What if we include it to bootstrap v4 ?

![rating component](https://cloud.githubusercontent.com/assets/7569427/16444025/85801110-3df9-11e6-888f-7f9ef437da17.png)

I already have a component  that I developed sometime back: https://rawgit.com/jeradrutnam/css-rating/master/example.html

I would happy to contribute it with some enhancements.

**Comment by cvrebert** [comment]
X-Ref: #7135

**Comment by design8383** [comment]
Not good example of the Accessibility. Focus is good from a possible element. Use input elements. Will be an improved ui

**Comment by jeradrutnam** [comment]
@design8383: Can you be more specific? Thanks.

**Comment by patrickhlauke** [comment]
@jeradrutnam try using your component with the keyboard (not mouse)...

**Comment by patrickhlauke** [comment]
so in general: the idea of adding a rating component may be a good one (personally, i think it's a bit too specific, rather something i'd see as a third party extension/plugin), but it needs to be fully accessible to warrant inclusion. This includes being keyboard accessible and working correctly with assistive technologies (e.g. screenreaders).

**Comment by jeradrutnam** [comment]
@patrickhlauke +1, yes that something I have to add. which is not there at the moment. As I mentioned need to do some enhancements before adding.

**Comment by jeradrutnam** [comment]
I updated example [1] with keyboard shortcuts as requested.

Note: Code is not efficient. Its only for demo purpose. And currently it works only on full star rating. Not for half stars. Which I will update asap.

[1] - https://rawgit.com/jeradrutnam/css-rating/master/example.html

**Comment by design8383** [comment]
@jeradrutnam 
patrickhlauke said. The same opinion . The markup to be accessible from the keyboard to use the semantic. If you like to be accessible with the keyboard arrows. Rated options should be selected for each . Must add the label text for the selected target with .

**Comment by jeradrutnam** [comment]
@design8383: Thanks for the suggestion. I have updated the example. As I told previously, this is not the final contribution code. This is only for demoing purpose. Please find the updated [example](https://rawgit.com/jeradrutnam/css-rating/master/example.html) which I added the arrow key events.

**Comment by design8383** [comment]
Be tab to access the keyboard. Then Be moved by the arrows. Points can be selected for each . Increase access to keyboard users. Provided , correct information to the screen reader users

demo: http://codepen.io/design8383/full/mypyvW/

**Comment by jeradrutnam** [comment]
Yes, it's already there. But it doesn't select the first rate star on focus. But which is also can easily implement.

**Comment by AucT** [comment]
this can be easily done with jquery.
I vote-down

**Comment by jeradrutnam** [comment]
@AucT 

There are many things we can do easily using jQuery. But what's your point of down voting to not to add this component?

Cheers!

**Comment by AucT** [comment]
bootstrap rating icon is all I need. As far as I remember it is easily done with few css lines. 
That's why I think it's not needed.

**Comment by mdo** [comment]
Not going to add this, thanks though.
