### ISSUE TITLE
Progress Bar animation not working

### ISSUE THREAD

**Issue by mtrstudio** [twbs/bootstrap#20200]
Hi I am using Chrome on windows 10,
It seems the progress bar does not animate itself on v4-bootstrap documentation page (http://v4-alpha.getbootstrap.com/components/progress/)

But it works fine on bootstrap3 page (http://getbootstrap.com/components/#progress).

Is this a bug?

**Comment by cvrebert** [comment]
Duplicate of #17148. Please search more in the future. Thanks.
