### ISSUE TITLE
24 columns grid doesn't calculate columns width correctly

### ISSUE THREAD

**Issue by enrimr** [twbs/bootstrap#20213]
If you select 24 columns in custom.scss, when you use a col-sm-5 together with col-sm-19, the total width is bigger than 100%

**Comment by wolfy1339** [comment]
Bootstrap only supports 12 columns.
The issue tracker is not a place to post How-to or personal questions. Thanks

**Comment by tomlutzenberger** [comment]
That's exactly why there's a variable for the amount of columns. To configure it.
So @enrimr 's question is legit.

**Comment by enrimr** [comment]
I was going on checking my issue, and the problem is when you mix a two cols where one of them includes a min-width attribute. So I'm going to close the issue because the problem is not the grid system. Thanks both of you!
