### ISSUE TITLE
bootstrap support Angular2 release candidate

### ISSUE THREAD

**Issue by sharmilemurugaraj** [twbs/bootstrap#20212]
Does Bootstrap supports Angular 2 release candidate?

**Comment by rafalp** [comment]
Supporting JS frameworks is outside Bootstrap's project scope. This is frontend framework that provides you with html and css foundations for your project as well as few basic JS components like dropdowns/modals that are purely representational (ergo control elements styles/visibility).

You should instead ask at Angular 2 communities about known issues in writing views/components using Bootstrap's markup.
