### ISSUE TITLE
card-columns, can't get media-query to work. Wrong column count.

### ISSUE THREAD

**Issue by thechile** [twbs/bootstrap#20226]
I have a simple bootstrap card example here that used 14 cards http://www.bootply.com/1ERCHtYa8k. I used a media query to adjust the column count from the usual fixed count of 3 to more or less columns based on screen size.

For some reason at the large break point where I've specified 6 columns, it always shows 5. The other breakpoints work OK and i'm not sure why it's doing this or how to fix.

I've noticed as well that as i vary the card count, at large the number of columns changes in weird ways. For example here is the same bootply but with only 7 cards http://www.bootply.com/7yubrPSKgQ#.  When sized to large will only show 4 columns. Don't understand why.

I'm using latest Chrome on Windows 10 machine.

Any info/help appreciated. Thanks.

**Comment by twbs-lmvtfy** [comment]
Hi @thechile!

You appear to have posted a live example (http://s.bootply.com/render/1ERCHtYa8k), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 5, column 9 thru column 30: A document must not include both a ```` meta ```` element with an ```` http-equiv ```` attribute whose value is ```` content-type ````, and a ```` meta ```` element with a ```` charset ```` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @thechile!

You appear to have posted a live example (http://s.bootply.com/render/7yubrPSKgQ), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 5, column 9 thru column 30: A document must not include both a ```` meta ```` element with an ```` http-equiv ```` attribute whose value is ```` content-type ````, and a ```` meta ```` element with a ```` charset ```` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by thechile** [comment]
the HTML5 validation is bootply auto-generated code. Not the bootstrap code example i gave. I can't **fix these errors**.

**Comment by cvrebert** [comment]
I've let Bootply know about their bug: https://twitter.com/cvrebert/status/750506021328592896
In the meantime, please use one of the other live example sites (JS Bin, JS Fiddle, CodePen).

**Comment by thechile** [comment]
Thanks @cvrebert. 

Having looked into this issue some more i don't think it's a bootstrap problem.. more a CSS thing that can't be fixed. Please see [here](http://stackoverflow.com/questions/38194574/bootstrap-4-with-card-columns-cant-get-media-query-to-work/38206775#38206775) for some more info. It automatically fills the column space as it deems best and occasionally you will have full columns empty when using the masonry layout. 

To increase your chances of this not happening, use variable height cards. Which I've tried and works but on occasion i still got empty columns so isn't full proof.

**Comment by cvrebert** [comment]
Closing this then.

**Comment by iatek** [comment]
Thanks for the heads up @cvrebert. I'm not sure why it came through as invalid the META tags seems to be correct: https://html5.validator.nu/?doc=http%3A%2F%2Fs.bootply.com%2Frender%2F7yubrPSKgQ

**Comment by cvrebert** [comment]
@iatek I guess they're running different versions. Compare with https://validator.w3.org/nu/?doc=http%3A%2F%2Fs.bootply.com%2Frender%2F7yubrPSKgQ

**Comment by cvrebert** [comment]
https://github.com/validator/validator/issues/239#issuecomment-190849280 suggests that checker.html5.org should be the most up-to-date, and it reports the error in question:
https://checker.html5.org/?doc=http%3A%2F%2Fs.bootply.com%2Frender%2F7yubrPSKgQ
