### ISSUE TITLE
is it possible modal to act like popup window?

### ISSUE THREAD

**Issue by linejine** [twbs/bootstrap#20227]
i want to use both modal and modal's backdrop page.
in bootstrap, $('#modalID').modal({backdrop : true}) is just showing backdrop, not working backdrop event. for example, click, focus, etc.
i want backdrop page to activate when showing modal.
is it possible?

**Comment by cvrebert** [comment]
Please ask how-to or troubleshooting questions on StackOverflow, Slack, or IRC.
See https://github.com/twbs/bootstrap/blob/master/README.md#community for links to those forums.
Thanks.
