### ISSUE TITLE
Add .col and .row-* classes to support flex-direction: column.

### ISSUE THREAD

**Issue by Kyopaxa** [twbs/bootstrap#20233]
I saw there is no support for flex-direction, not being set anywhere so it uses the default value of "row".

I suggest to add _.col_ and _.row-*_ classes to support _flex-direction: column_. Those classes would be the same as current _.row_ and _.col-*_ classes, except that _.col_ class would use flex-direction: column.

So Bootstrap 4 could have (using xs and 12 for this example):

```
<div class="row"> <!-- uses flex-direction: row -->
  <div class="col-xs-12"></div>
</div>

<div class="col"> <!-- uses flex-direction: column -->
  <div class="row-xs-12"></div>
</div>

<div class="row"> <!-- nesting -->
  <div class="col-xs-6 col">
    <div class="row-xs-6"></div>
    <div class="row-xs-6"></div>
  </div>
  <div class="col-xs-6 col">
    <div class="row-xs-6"></div>
    <div class="row-xs-6"></div>
  </div>
</div>
```

Of course, there should be some study about what do "xs", "md" and "lg" mean in the context of "column" layout. Media queries with screen height I suppose?

Cheers.

**Comment by Mathdrquinn** [comment]
Being addressed in a [new PR](https://github.com/twbs/bootstrap/pull/20272).  I was looking for these same classes.  I hope this helps.

**Comment by cvrebert** [comment]
Seems potentially confusing.
CC: @mdo

**Comment by mdo** [comment]
Tons of flex utils were added in #21407, so you can add `.flex-column` to any flex container and change the flex items accordingly.
