### ISSUE TITLE
Popover lying outside of viewport

### ISSUE THREAD

**Issue by juavenel** [twbs/bootstrap#20231]
How to have a bootstrap popover always contained in the screen? Below a popover that lying outside of the screen ?

![screencapture-quirktools-com-screenfly-1467665231029](https://cloud.githubusercontent.com/assets/20143484/16581393/8f2391c4-42a9-11e6-9dd7-075eb2ff5923.png)

**Comment by cvrebert** [comment]
Please follow the instructions for "When reporting a bug" in https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md

**Comment by juavenel** [comment]
add this to solve the problem:

    constraints: [ { to: 'scrollParent', pin: true } ]

**Comment by Superpencil** [comment]
```js
$('[data-toggle="popover"]').popover({ constraints: [ { to: 'scrollParent', pin: true } ] })
```
