### ISSUE TITLE
Hamburger icon (U+2630 TRIGRAM FOR HEAVEN) is always black on Samsung Galaxy S Android devices

### ISSUE THREAD

**Issue by juampi** [twbs/bootstrap#20234]
OS: Android 6.0.1 SM-G920F Build/MMB29K
Browser: Chrome 51.0.2704.81

The Bootstrap 4 navbar hamburger icon is always black, even when using other background colors such as bg-inverse or bg-primary.

The bug can be reproduced by accessing this bin:
https://output.jsbin.com/hiyeti/3

**EDIT**:
I just realized this behavior is present even without Bootstrap:
https://output.jsbin.com/wovuba/1

Probably an Android/Chrome issue then, though not sure if anything should be done about this on Bootstrap's side.

**EDIT 2**:
Here's a screenshot:
![whatsapp-image-20160706](https://cloud.githubusercontent.com/assets/748094/16642821/e97b3ca8-43e4-11e6-84e8-42933c661225.jpeg)

**Comment by cvrebert** [comment]
Unfortunately I don't have an Android 6 device handy, but testing in Android 5.1 via Sauce Labs shows that it does use the correct color there (but seems to lack the glyph in question).

I highly recommend that you open a Chrome bug about this via https://crbug.com/new

**Comment by anantoghosh** [comment]
Works fine for me.
![screenshot_20160706-153854- 1](https://cloud.githubusercontent.com/assets/12339068/16614790/bf542e98-4390-11e6-9898-8b61917aa11b.png)
![screenshot_20160706-154129](https://cloud.githubusercontent.com/assets/12339068/16614791/bf569b92-4390-11e6-879c-14a5ebd304b3.png)
![screenshot_20160706-153938- 1](https://cloud.githubusercontent.com/assets/12339068/16614789/bf53de16-4390-11e6-9f27-38f5ebb13021.png)

**Comment by patrickhlauke** [comment]
both jsbin examples (with and without bootstrap) WFM in Chrome 51 / Android 6.0.1 on Nexus 5, including loading the correct glyph. don't think it's a bootstrap issue per se.

**Comment by juampi** [comment]
I asked a friend with the same phone (Samsung Galaxy S6) and the icon is black for him as well.

![whatsapp-image-20160706](https://cloud.githubusercontent.com/assets/748094/16639688/4cf4b8e4-43c8-11e6-8b4b-ced3e306ee98.jpeg)

Seems to be an issue with that phone then.

**Comment by Starsam80** [comment]
![image](https://cloud.githubusercontent.com/assets/4411333/16642665/7993929c-43ca-11e6-8375-61d76f4250ac.png)
![image](https://cloud.githubusercontent.com/assets/4411333/16642681/96b4848a-43ca-11e6-98ff-c95b7e3302e8.png)
I can't reproduce.

**Comment by tomlutzenberger** [comment]
I actually **can** reproduce on Galaxy S5.
If needed, I can do some USB-Debugging.

![screenshot_2016-07-07-09-29-21-1](https://cloud.githubusercontent.com/assets/5536910/16645860/31b49a9a-4427-11e6-988b-1ac3020e6fea.png)
![screenshot_2016-07-07-09-32-02-1](https://cloud.githubusercontent.com/assets/5536910/16645861/31b57028-4427-11e6-8ee9-b0f8cae4612a.png)

**Comment by acshef** [comment]
I also have black bars (like @tomlutzenberger) with a Galaxy S5 on Kit-Kat 4.4.2, Chrome 51.0.2704.81

**Comment by TheBuzzer67** [comment]
It seems to be a Chrome V51 issue, have the same problem with S7 on 6.0.1 SM-G930W8 and Chrome 51.0.2704.81

**Comment by cvrebert** [comment]
@juampi @TheBuzzer67 @acshef @tomlutzenberger 
Please re-test using the Dev version of Android Chrome: https://play.google.com/store/apps/details?id=com.chrome.dev

**Comment by patrickhlauke** [comment]
So a Chrome/Samsung issue then? (I have 51.0.2704.81 on Android 6.0.1 and don't see it)

**Comment by tomlutzenberger** [comment]
I can't reproduce on `Chrome 51.0.2704.103 m` under Win 7.

**Comment by cvrebert** [comment]
@tomlutzenberger Yes, we've established that this is Android-specific (and potentially Samsung-specific).

**Comment by cvrebert** [comment]
@patrickhlauke Also, the glyph not rendering on Android 5.1 is a (separate) problem, since we currently claim support for Android v5.0+.

**Comment by juampi** [comment]
Still shows black on Chrome Dev 53.0.2782.9 and Android 6.0.1 SM-G920F Build/MMB29K.

**Comment by tomlutzenberger** [comment]
@cvrebert Same result as @juampi

**Comment by acshef** [comment]
Still black with Chrome Dev 53.0.2782.9 on Android 4.4.2 Galaxy S5. And for what it's worth, I also tried disabling the pre-installed [Chrome Samsung Support Library](https://play.google.com/store/apps/details?id=com.chrome.deviceextras.samsung) (although honestly _nobody_ knows for sure what that does).

**Comment by Starsam80** [comment]
It might be a font issue. Since I can't test anything, somebody should try switching fonts and see if that helps. It might not, but it's worth a try.

**Comment by cvrebert** [comment]
Yeah, that sheen on the ☰ character is weird. Maybe Samsung has some unusual default font that uses emoji-ish rendering where the color is baked-in.

@tomlutzenberger Since you offered, could you please USB debug and inspect to see what font it's using? The panel is at the bottom of the "Computed" tab of the "Elements" inspector:
<img width="378" alt="example" src="https://cloud.githubusercontent.com/assets/419884/16667941/ac70f492-4443-11e6-94df-c4d656ebb91d.png">

**Comment by cvrebert** [comment]
Just to summarize the data y'all have contributed so far, the bug has been observed on:
* Devices
  * Samsung Galaxy S7
  * Samsung Galaxy S6
  * Samsung Galaxy S5
* Chrome
  * 53.0.2782.9 (dev)
  * 51.0.2704.81 (stable)
* Android
  * 6.0.1; SM-G930W8
  * 6.0.1; SM-G920F Build/MMB29K
  * 6.0.1; SM-G900F Build/MMB29M
  * 4.4.2

**Comment by acshef** [comment]
Screenshot from the GMail app with @cvrebert's reply to this issue. Our culprit makes an appearance again! Definitely smells of "emoji-ish rendering where the color is baked-in"

![scr](https://cloud.githubusercontent.com/assets/9013284/16668346/ce0d7ad0-444d-11e6-8479-1702481bf128.png)

**Comment by tomlutzenberger** [comment]
@cvrebert Aye, I'm on it! <:grin: 

But it takes *a year* to download that Windows Driver from the Samsung website.
On Linux it just works...

**Comment by tomlutzenberger** [comment]
Even though @juampi did good on picking a unicode character it seems, that the wrong font for rendering is picked. After trying with some other "hamburger character" it rendered ─ to my surprise ─ White!

The font is "[Noto Color Emoji](https://www.google.com/get/noto/#noto-emoji-qaae-color)" (It makes those ugly default emoticons).
On androidcentraI.com [i came across something interesting](http://forums.androidcentral.com/general-help-how/241050-solved-android-4-1-ios-how-emoji-works-android-ios.html#post2524302).
> "Normal system emoji on Android is black and white because TTF doesn't support colour it has to be done by the app [...]"

Maybe this is why black color is kind of "forced"?!

![image](https://cloud.githubusercontent.com/assets/5536910/16680691/c3d010b6-44f0-11e6-9a2a-599c3be1d0e8.png)

**Comment by tomlutzenberger** [comment]
**Correction:** He sure picked a unicode character, but maybe the wrong one.
I googled and found **[this](https://coderwall.com/p/jsb-vw/hamburger-icon-with-unicode)**.

> "Use ≡ (x2261) instead as it has better support (96%)
http://unicode.johnholtripley.co.uk/2261/"

Now if you compare, you'll see that he's right:
* **Old:** http://unicode.johnholtripley.co.uk/2630/
* **New:** http://unicode.johnholtripley.co.uk/2261/

I changed it and.... works!

![image](https://cloud.githubusercontent.com/assets/5536910/16681376/9adf78aa-44f4-11e6-8001-58de230e9c6b.png)

**Comment by cvrebert** [comment]
@mdo Perhaps we could just go with the word "Menu" instead of a hamburger icon? The CJK trigram and mathematical equivalence operator don't make sense semantically and can't be good for accessibility. And it avoids these 2 Android compatibility problems. (And criticism about hamburger menu icons generally.)

**Comment by patrickhlauke** [comment]
the accessibility issue (for screen reader users) is taken care of by using a proper `aria-label` on the `<button>` (as per our documentation). I'm actually about to send a PR to do the above...

**Comment by patrickhlauke** [comment]
and although there's often talk about how much better having an actual word like "Menu" is compared to hamburger icons...many devs will want it, and I do think that users are (getting) familiar with this convention.

**Comment by tomlutzenberger** [comment]
@patrickhlauke But due to the removement of the glyphicons in v4, I don't see why any kind of a menu icon is needed. If a developer wants an icon instead of the word "Menu", he/she should include some icon font line Fontawesome.

**Comment by patrickhlauke** [comment]
we also use "X" glyphs for dismissible alerts etc...so it's not the only situation where a subtle icon is in play...

**Comment by patrickhlauke** [comment]
an alternative (but slightly more involved) solution would be to switch to using SVG icons, of course...

**Comment by tomlutzenberger** [comment]
But this would mean more could to maintain.
I would stick to unicode characters (for now).

**Comment by cvrebert** [comment]
@patrickhlauke Good points. I have no objection to your improved U+2261 approach, or an SVG approach.

**Comment by acshef** [comment]
Unicode has support for forcing the text variant of an emoji, using _variation selectors_. http://www.unicode.org/emoji/charts/emoji-variants.html

For this case, we'd use &#x2730;&#xFE0E;

Unfortunately, from what I've found only iOS supports this.

**Comment by cvrebert** [comment]
Strangely, I can't seem to find U+2630 TRIGRAM FOR HEAVEN in the vanilla Noto Color Emoji font. Maybe Samsung added some glyphs without changing the font's name? Or maybe I'm not searching correctly.

**Comment by tomlutzenberger** [comment]
What? 😕
Any chances that there's some kind of a "fallback character"?

**Comment by Starsam80** [comment]
When it renders correctly on my phone, it uses the font "Noto Sans Symbols".

**Comment by Drakenhart** [comment]
A note: Gmail for their mobile mail app, uses three bullets in a vertical line to represent menus in some instances. Added point for consideration.

The Icon debate is a hot one to be sure, but icons (if they are well understood see:save icon) improves scan-ability, and fits better into a 44px square area then a word does. There are work arounds in CSS that don't even bring in the img ( or the "i" ) tag into use, so accessibility is partly covered. However, stand alone icons isn't a great idea either because not all images make the same sense and in a growing global reality.... may even be offensive to some folks from other cultures. ^.^

Wether it is a button or a link, if we use their native functions, it works for accessibility. If it's coded. Semantically. The visual is just icing on the cake.

Maybe, having a "sr-only" option for icons/images, with the associated words, allowing designers to expose that or not as they choose, may be a better way to go?

**Comment by yesiateyoursheep** [comment]
Why exactly did you dump the ol' reliable method of using 3 `<span class="icon-bar">`s anyway?
The hamburger menu icon doesn't render at all on my Vodafone 890N KitKat 4.4.4 device (this has always been the case, chrome version is irrelevant). It does still have a clickable area though. For now, I'm using the old icon-bar system to work around it as the inconsistencies that come with relying on  each device's emoji font to render the symbol isn't ideal.

**Comment by patrickhlauke** [comment]
> Why exactly did you dump the ol' reliable method 

as v4 targets android 5.0+, it was time to move on to some more modern technologies (using `<span>`s, or applying border/shadow tricks, feels like a very old-school hack compared to using proper SVG or proper fonts/characters, IMO)

**Comment by yesiateyoursheep** [comment]
I'm not a fan of it personally, using some SVG magic would help, but using a font results in it rendering differently on a bunch of devices unless you're prepared to download a font. Either of these options would just add to precious loading time, meanwhile all the code required to make the 3 `<span>`s trick can fit in roughly 200 bytes and can also be animated bar by bar (you can make a hamburger to x button transition, for example). If it ain't broke, don't fix it.

**Comment by tomlutzenberger** [comment]
@yesiateyoursheep So you suggest to furthermore keep a method...
1. That display's an Icon made of empty HTML? (needs to included by the Dev itself **each time used** while SVG can be applied by CSS class)
2. With less technical capabilities and potential? (SVG can be animated, too)
3. That supports old technology one more major version? (If Dev's want to support older Devices/Browser they should stick to `v3.3.6`)

> If it ain't broke, don't fix it.

No offense, but IMHO in this context, it's like saying "Even if there are better and more modern ways to do it, don't change it anyway.

**Comment by yesiateyoursheep** [comment]
@tomlutzenberger I do like the class support and animation with SVG, but I don't like how this is default, that's a pretty harsh price to pay for a critical part of the UI not rendering on some devices.
To me, the time it takes to copy and paste the code to make a hamburger menu out of `span`s is well worth the backwards compatibility, I can understand wanting to use newer technologies, but I don't think it's worth it yet. Just look at the Android Version distribution;
![screenshot-developer android com 2016-07-11 12-41-57](https://cloud.githubusercontent.com/assets/7791524/16717175/ee4063de-4764-11e6-9548-0dce37d23fe9.png)
You're aiming for support for 45.5% of Android devices. Android app developers usually have support for at least 4.0.
Using an SVG should have very high compatibility rates. I hope. But I'll be sticking with `span`s for another few years as is. It doesn't have enough positives to weigh out the potential negatives. Plus I just really like tinkering with CSS animations.
More than anything else, I was just arguing against using UTF symbols, it just seems like you're pushing to use new technologies for the sake of using new technologies.

**Comment by tomlutzenberger** [comment]
Partially, I agree.
But I am not sure if it is the Bootstrap teams intention to support old devices and technologies. That's what v3 is for. Version 4 should be new, modern and clean.

It's **your** responsibility as Developer, to make sure that **your** audience is capable to access the information of your website or your product they want and need. Don't shove this off to BS.
If they're using old devices back from 2000-something, don't use v4.

**Comment by Drakenhart** [comment]
Is there a way for developers/designers to change out the hamburger for something else? (like three vertically stacked dots, or wording)?

**Comment by tomlutzenberger** [comment]
You can use whatever you want.
The solution provided by Bootstrap is just a recommendation, mostly used in the examples.
What icon etc. you are using at least is your own decision.

**Comment by cvrebert** [comment]
> Is there a way for developers/designers to change out the hamburger for something else?

If we go the SVG route, there will be a Sass variable you can use to swap out the inline SVG with your own SVG image.

**Comment by cvrebert** [comment]
> Did a little research; Android 4.3 and below have partial or no support for SVGs,

Under the assumption that the Android Browser data on http://caniuse.com/#feat=svg also applies to Chrome when used with those Android versions, Android 3+ should support SVG (modulo masking, which shouldn't matter in our case).
And we're talking about an extremely trivial SVG here for the hamburger.

**Comment by Touficbatache** [comment]
The triple bar / hamburger icon can be replaced with ≡ in the HTML code!

**Comment by cvrebert** [comment]
@Touficbatache Doesn't look quite right to mdo. See https://github.com/twbs/bootstrap/pull/20260#issuecomment-231471027
We're probably going with the SVG route: #20329

**Comment by bardiharborow** [comment]
I get this on `Mac OS X 10.11.5 Chrome 53.0.2785.70` with `v4.0.0-alpha.3`. The issue is not present with `v4.0.0-alpha.2.`
