### ISSUE TITLE
bower ECONFLICT Unable to find suitable version for jquery

### ISSUE THREAD

**Issue by vineeshc9** [twbs/bootstrap#20230]
$ bower install bootstrap
bower bootstrap#*               cached https://github.com/twbs/bootstrap.git#3.3              .6
bower bootstrap#*             validate 3.3.6 against https://github.com/twbs/boo              tstrap.git#*
bower jquery#1.9.1 - 2          cached https://github.com/jquery/jquery-dist.git#2.2.4
bower jquery#1.9.1 - 2        validate 2.2.4 against https://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower                        ECONFLICT Unable to find suitable version for jquery

How Can i Solve this

**Comment by cvrebert** [comment]
Unable to reproduce:
```
dummy $ npm install bower
/Users/chris/code/dummy
└── bower@1.7.9 
dummy $ ./node_modules/.bin/bower install bootstrap
bower bootstrap#*           not-cached https://github.com/twbs/bootstrap.git#*
bower bootstrap#*              resolve https://github.com/twbs/bootstrap.git#*
bower bootstrap#*             checkout v3.3.6
bower bootstrap#*             progress Receiving objects:  64% (264/411), 3.23 MiB | 782.00 KiB/s
bower bootstrap#*             resolved https://github.com/twbs/bootstrap.git#3.3.6
bower jquery#1.9.1 - 2      not-cached https://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower jquery#1.9.1 - 2         resolve https://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower jquery#1.9.1 - 2        checkout 2.2.4
bower jquery#1.9.1 - 2        resolved https://github.com/jquery/jquery-dist.git#2.2.4
bower bootstrap#^3.3.6         install bootstrap#3.3.6
bower jquery#1.9.1 - 2         install jquery#2.2.4

bootstrap#3.3.6 bower_components/bootstrap
└── jquery#2.2.4

jquery#2.2.4 bower_components/jquery
```

For help with personal troubleshooting, please ask on one of the community forums listed on https://github.com/twbs/bootstrap/blob/master/README.md#community

**Comment by sonnysavage** [comment]
I had an issue like this due to running MinTTY on Windows 10. This article explains why, and gives two different solutions: https://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/
