### ISSUE TITLE
Spelling Error: 'alert-dismissable'

### ISSUE THREAD

**Issue by meyersbs** [twbs/bootstrap#20249]
This should be 'alert-dismiss**i**ble.' In the grand scheme of things, this really doesn't matter, but I thought I would bring it up.

**Comment by mendeza** [comment]
Spelling counts; it _does_ matter.

**Comment by meyersbs** [comment]
Sorry, it IS spelled correctly in the codebase.

**Comment by meyersbs** [comment]
Actually, it appears to be spelled both ways.

**Comment by patrickhlauke** [comment]
it would help if you said *where* in the codebase

**Comment by patrickhlauke** [comment]
noting that it's in the .less file and commented as being something left over from version 3.2.0

https://github.com/twbs/bootstrap/search?utf8=%E2%9C%93&q=alert-dismissable
