### ISSUE TITLE
Request for W-9 or W-8BEN

### ISSUE THREAD

**Issue by advent-com** [twbs/bootstrap#20254]
In order to purchase any software from your site, your company must be set up on our system.  At this time we would like to purchase Inspinia.  Would you kindly provide me with your W-9 (or W-8 Ben if outside of the US) so that we can order and pay for our software.  

Please send to it-purchasing@advent.com

Thank you.

**Comment by shayne2013** [comment]
嗨

**Comment by patrickhlauke** [comment]
assuming this is about bootstrap themes, see http://themes.getbootstrap.com/pages/faq

if it's not about themes...bootstrap itself is open source, so you don't need to purchase anything from us...

**Comment by patrickhlauke** [comment]
> we would like to purchase Inspinia

aeh...looking at this, I think you're definitely in the wrong place. nothing to do with either bootstrap nor bootstrap themes. suggest you contact whoever you're trying to buy that theme from https://www.google.co.uk/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=inspinia&oq=inspinia&aqs=chrome..69i57j0l5.1288j0j1
