### ISSUE TITLE
Text Input of type='time' doesn't properly size

### ISSUE THREAD

**Issue by AlpriElse** [twbs/bootstrap#20257]
### Text input of type='time' doesn't properly size

```
<input type="time" placeholder="time" class="form-control"/>
```

Expected input field to be of same vertical height as other textual inputs but given field with excess vertical height.

![screen shot 2016-07-07 at 19 13 04](https://cloud.githubusercontent.com/assets/7798116/16673985/ee1914ee-4478-11e6-8255-eefea216a123.png)

Mac OS X 10.11.5, Google Chrome v51.0.2704.84

Reproduced [here](http://jsbin.com/hejanosexe/edit?html,output) which is a snippet taken from my current project.

**Comment by cvrebert** [comment]
Duplicate of #17308. See also #18842.
