### ISSUE TITLE
Popover input text in modal window

### ISSUE THREAD

**Issue by Dimigergo** [twbs/bootstrap#20252]
Hello!

When I use a opover with input (text) field, everything works fine, but the input field is disabled. It is only for input type text, number ect. but button, checkbox, file input works fine.

Any workaround for this?
Thanks.

**Comment by cvrebert** [comment]
May I ask why you didn't provide the information requested by [the new issue template](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md)?

**Comment by Dimigergo** [comment]
Sorry, I have made az emample:
[](https://jsbin.com/guzipefoxi/edit?html,js,output)

Chrome, Firefox make the error with Windows 8.1

Thanks.

**Comment by cvrebert** [comment]
Unfortunately, we're unable to provide assistance with third-party libraries such as jquery.webui-popover.
Try asking on one of the community help forums (StackOverflow, IRC, Slack) instead: https://github.com/twbs/bootstrap/blob/master/README.md#community
Or try asking the webui-popover folks for help: https://github.com/sandywalker/webui-popover/issues

**Comment by Dimigergo** [comment]
Ok, I have made it with bootstrap popover, and the result is the same.

[Link](https://jsbin.com/magacurefi/edit?html,js,output)

**Comment by cvrebert** [comment]
Due to how modals' focus management works, you cannot use `container: 'body'` in this case. The `<input>` element must be a descendant of the modal in order for it to be able to obtain focus.
Remove the `container: 'body'` option and your example works fine.

**Comment by ricardoperroni** [comment]
Hi everyone, 
Add container: 'divmodal' and works very well!!
