### ISSUE TITLE
Will the class ‘form-control-feedback’  make the events such as ‘onclick’ not fire？

### ISSUE THREAD

**Issue by ychaos** [twbs/bootstrap#20268]
```
<form id= "form">
<span id="needfire" class=“form-control-feedback”>something</span>
</form>
<script>
$('#form').on('click','#needfire',function(){
alert('fire');
});
</script>
```

This  will not work,but remove the class "form-control-feedback",it will fire immediately!

**Comment by cvrebert** [comment]
Please make your example into a JS Bin or JS Fiddle.
In which browser(s) have you observed the problem?

**Comment by ychaos** [comment]
Chrome 51.0.2704.103 m

**Comment by cvrebert** [comment]
Okay, then we just need you to post a [JS Bin](http://jsbin.com) demo of the problem.

**Comment by cvrebert** [comment]
Understood. (Sorry, I sent my prior comment while you were amending your reply.)

**Comment by mdo** [comment]
I don't believe this is anything on our end, but I'll happily be proven wrong. Please leave a comment if you find something on our end is for sure causing this. As it stands now, no behavioral things should be changing with our styling of those inputs.
