### ISSUE TITLE
multiple navbar conflict 

### ISSUE THREAD

**Issue by hasanmisbah** [twbs/bootstrap#20263]
I've added two navigation in my site one for all and one for mobile only
the problem is when clicked second menu icon that shows first menu. I tried it using desktop visibility it was work but on the same mode using on mobile isn't work. it shows first menu.

**Comment by cvrebert** [comment]
May I ask why you didn't provide the information requested by [the issue template](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md)?

**Comment by hasanmisbah** [comment]
`<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap-dropdownhover.min.css">
	<link rel="stylesheet" type="text/css" href="css/animate.min.css">
	<link rel="stylesheet" type="text/css" href="css/Font-awesome.css.min.css">`

`<div class="conatiner-fluid nav-bg">
		<div class="container">
			<div class="row">
				<nav class="navbar">
					<div class="container-fluid">
						
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>

						
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav" data-hover="dropdown" data-animations="fadeInDown fadeInRight fadeInUp fadeInLeft">
								<li class="active"><a href="#">মূলপাতা<span class="sr-only">(current)</span></a></li>
								<li><a href="#">আমাদের সম্পর্কে</a></li>
								<li><a href="#">সদস্য পাতা</a></li>
								<li><a href="#">বৈশিষ্ঠ্য সমুহ</a></li>
								<li><a href="#">সম্পাদনা পরিষদ</a></li>
								<li><a href="#">যোগাযোগ</a></li>
								<li class="dropdown" data-hover="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">অন্যান্য <span class="caret"></span></a>
									<ul class="dropdown-menu dropdownhover-bottom">
										<li><a href="#">Action</a></li>
										<li><a href="#">Another action</a></li>
										<li><a href="#">Something else here</a></li>
										<li role="separator" class="divider"></li>
										<li><a href="#">Separated link</a></li>
										<li role="separator" class="divider"></li>
										<li class="dropdown" data-hover="dropdown">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
											<ul class="dropdown-menu dropdownhover-right">
												<li><a href="#">Action</a></li>
												<li><a href="#">Another action</a></li>
												<li><a href="#">Something else here</a></li>
												<li role="separator" class="divider"></li>
												<li><a href="#">Separated link</a></li>
												<li role="separator" class="divider"></li>
												<li><a href="#">One more separated link</a></li>
											</ul>
										</li>
										<li><a href="#">One more separated link</a></li>
									</ul>
								</li>
							</ul>
							<form class="navbar-form navbar-right" role="search">
								<div class="form-group">
									<input type="text" class="form-control" placeholder="Search">
								</div>
								<button type="submit" class="btn btn-default">Submit</button>
							</form>
						</div>
						
					</div>
					
				</nav>
			</div>
		</div>
	</div>`
`<div class="conatiner-fluid nav-bg">
		<div class="container">
			<div class="row">
				<nav class="navbar">
					<div class="container-fluid">
						
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>

						
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav" data-hover="dropdown" data-animations="fadeInDown fadeInRight fadeInUp fadeInLeft">
								<li class="active"><a href="#">মূলপাতা<span class="sr-only">(current)</span></a></li>
								<li><a href="#">আমাদের সম্পর্কে</a></li>
								<li><a href="#">সদস্য পাতা</a></li>
								<li><a href="#">বৈশিষ্ঠ্য সমুহ</a></li>
								<li><a href="#">সম্পাদনা পরিষদ</a></li>
								<li><a href="#">যোগাযোগ</a></li>
								<li class="dropdown" data-hover="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">অন্যান্য <span class="caret"></span></a>
									<ul class="dropdown-menu dropdownhover-bottom">
										<li><a href="#">Action</a></li>
										<li><a href="#">Another action</a></li>
										<li><a href="#">Something else here</a></li>
										<li role="separator" class="divider"></li>
										<li><a href="#">Separated link</a></li>
										<li role="separator" class="divider"></li>
										<li class="dropdown" data-hover="dropdown">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
											<ul class="dropdown-menu dropdownhover-right">
												<li><a href="#">Action</a></li>
												<li><a href="#">Another action</a></li>
												<li><a href="#">Something else here</a></li>
												<li role="separator" class="divider"></li>
												<li><a href="#">Separated link</a></li>
												<li role="separator" class="divider"></li>
												<li><a href="#">One more separated link</a></li>
											</ul>
										</li>
										<li><a href="#">One more separated link</a></li>
									</ul>
								</li>
							</ul>
							<form class="navbar-form navbar-right" role="search">
								<div class="form-group">
									<input type="text" class="form-control" placeholder="Search">
								</div>
								<button type="submit" class="btn btn-default">Submit</button>
							</form>
						</div>
						
					</div>
					
				</nav>
			</div>
		</div>
	</div>`

`	<script src="js/jquery.min.js" type="text/javascript"></script>
	<script src="js/bootstrap.min.js" type="text/javascript"></script>
	<script src="js/bootstrap-dropdownhover.min.js" type="text/javascript"></script>
	<script src="js/script.js" type="text/javascript"></script>`

**Comment by cvrebert** [comment]
Your HTML is invalid. You have two elements with id="bs-example-navbar-collapse-1".
Use the [HTML validator](https://checker.html5.org/) beforehand next time.
