### ISSUE TITLE
Method selectPage in bootstraptable has bug when executed the current page element is not actived

### ISSUE THREAD

**Issue by rgqancy** [twbs/bootstrap#20274]
```
                                <button class="btn btn-default" type="button"
                                    id="btnTableSelectPageNumber">
                                    <span class="glyphicon glyphicon-repeat"></span>
                                    <span>Goto</span>
                                </button>
                                &nbsp;&nbsp;&nbsp;
                                <input id="SelectPageNumber" type="text" placeholder="please input the page number">                                        
```

SearchDesignPatent.btnTableSelectPageNumber().click(function() {
    var selectPageNumber = $('#SelectPageNumber').val();
    if(window.console){
        console.log(selectPageNumber);
    }
    SearchDesignPatent.tableSearchDesignPatent().bootstrapTable('selectPage',selectPageNumber);
    $('.page-number').each(function(){
        if(window.console){
            console.log($(this).text());
        }
        if($(this).text() == selectPageNumber){
            $(this).attr("class","page-number active");
        }
    });
});

the above sample code can fix the bug.

**Comment by mdo** [comment]
No idea what this was in regards to—I don't recall ever seeing this issue originally. Closing out now. Please feel free to open a new issue if a bug still exists, but please include a fully reduced test case.

**Comment by Johann-S** [comment]
you should open an issue in bootstrapTable repository 👍
