### ISSUE TITLE
Update Forms Documentation For Validation Styles

### ISSUE THREAD

**Issue by hokiecoder** [twbs/bootstrap#20273]
The [Validation section](http://v4-alpha.getbootstrap.com/components/forms/#validation) of the V4 docs mentions that child elements with `.form-control-label`, `.form-control`, and `.text-help` will automatically be styled based on the validation styles of their parent. However, it doesn't seem the `.text-help` class exists anymore. Looking through **_forms.scss** it appears the appropriate class is `.form-control-feedback`.

**Comment by cvrebert** [comment]
Already fixed in the `v4-dev` branch.
