### ISSUE TITLE
Customizer uses jqXHR success() & error() methods which are gone in jQuery 3

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20279]
Refs https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax
Refs #16834.
Or we could simply ensure the Customizer keeps using jQuery 2.
I personally have no interest in writing a patch for this.
CC: @XhmikosR @hnrch02

**Comment by XhmikosR** [comment]
But the customizer only exists in v3, where we need old browsers support, so we'll never use 3.x.

**Comment by cvrebert** [comment]
Excellent point.

**Comment by XhmikosR** [comment]
I can have a look though, just for consistency.
