### ISSUE TITLE
Unit test for tooltip on SVG element fails in Chrome+Safari under jQuery 3

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20280]
Specifically, https://github.com/twbs/bootstrap/blob/1956146787d686f5771ae51f7b96f3a3ad62ce09/js/tests/unit/tooltip.js#L1042 fails.

Refs #16834.

**Comment by cvrebert** [comment]
It seems like jQuery 3 gives incorrect results for the `.offset()` of an SVG element:
http://jsbin.com/papobuk/1/edit?html,js,console,output

**Comment by cvrebert** [comment]
Looks like they're aware of this and deemed it WontFix 😢:
https://github.com/jquery/jquery/issues/3137

**Comment by drewskig** [comment]
This should do a jQuery version check, as it now breaks tooltip placement for previous supported jQuery versions.

**Comment by cvrebert** [comment]
@drewskig Presumably you want #20381.

**Comment by drewskig** [comment]
Whoops, that's correct (just went to the issue noted in the code).
