### ISSUE TITLE
Popover will rapidly flicker on and off when used on an <a> element

### ISSUE THREAD

**Issue by JustASquid** [twbs/bootstrap#20289]
We've been having issues with some of our popovers for a while, so I've decided to put together a minimal repro.

[Jsfiddle](https://jsfiddle.net/JustASquid/v73hkd95/)

If you move your cursor over the <a> element, occasionally you will notice the popover flicker. If you move it slowly in from the right side, and stop it right on the edge, you can actually create a situation where the popover will be endlessly flickering.

If you set animation to true, the flickering means that half the time the popover will have given up and disappeared when the cursor is on the element.

OS: Windows 10
Browser: Chrome

**Comment by Lewiscowles1986** [comment]
Had this since Bootstrap 2.3.2. As I understand it there is no way around this as it's a browser implementation detail, but maybe a debounce could help to mitigate?

**Comment by Lewiscowles1986** [comment]
Also you could use manual, wrap the element and trigger on parent mouseleave
```html
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <a id="anchor" href="#" data-popover-title="A popover title" data-popover-content="Some popover text">?</a>
    </div>
  </div>
</div>
```

```js
$("a[data-popover-title]").each( function(e,elem) {
	var _this = this;
  $(this).popover({
    title: $(this).data('popover-title'),
    content: $(this).data('popover-content'),
    trigger: "manual",
    animation: false
  }).on("mouseenter", function () {
    $(_this).popover("show");
  }).parent().on("mouseleave", function() {
    $(_this).popover("hide");
  })
});
```

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by iftimiedaniel** [comment]
> We've been having issues with some of our popovers for a while, so I've decided to put together a minimal repro.
> 
> [Jsfiddle](https://jsfiddle.net/JustASquid/v73hkd95/)
> 
> If you move your cursor over the element, occasionally you will notice the popover flicker. If you move it slowly in from the right side, and stop it right on the edge, you can actually create a situation where the popover will be endlessly flickering.
> 
> If you set animation to true, the flickering means that half the time the popover will have given up and disappeared when the cursor is on the element.
> 
> OS: Windows 10
> Browser: Chrome



> We've been having issues with some of our popovers for a while, so I've decided to put together a minimal repro.
> 
> [Jsfiddle](https://jsfiddle.net/JustASquid/v73hkd95/)
> 
> If you move your cursor over the element, occasionally you will notice the popover flicker. If you move it slowly in from the right side, and stop it right on the edge, you can actually create a situation where the popover will be endlessly flickering.
> 
> If you set animation to true, the flickering means that half the time the popover will have given up and disappeared when the cursor is on the element.
> 
> OS: Windows 10
> Browser: Chrome

You can add 
`.popover{
pointer-events:none;
}`
This way you popover will appear but the cursor will pass through it.
Here is the edited fiddle : https://jsfiddle.net/naf1mubz/

**Comment by Hamdan85** [comment]
This also brakes several behaviours... for example if you are using buttons on popover, they wont work.
