### ISSUE TITLE
Wrong border-radius variable for .input-group-addon

### ISSUE THREAD

**Issue by fsasvari** [twbs/bootstrap#20291]
Problem with dev-v4 In "**_input-group.scss**". There is wrong border-radius included in **.input-group-addon** class.

It must be corrected for:

- $border-radius => $input-border-radius
- $border-radius-sm => $input-border-radius-sm
- $border-radius-lg => $input-border-radius-lg

Problem is when I change settings for **$input-border-radius** to _.1rem_ instead of default _.25rem_, input control form is OK, but **.input-group-addon** is still _.25rem_ so it's not proportional in view.

**Comment by mdo** [comment]
Addressed in #20387. Thanks!
