### ISSUE TITLE
Rename print utility classes

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20296]
Suggest renaming print utility classes as follows:

visible-print-block --> print-visible-block
visible-print-inline --> print-visible-inline
visible-print-inline-block --> print-visible-inline-block
hidden-print --> print-hidden

This would prevent them showing in intellisense with hidden-xs-up, etc.

**Comment by tomlutzenberger** [comment]
As you can see [in the Docs](http://getbootstrap.com/css/#responsive-utilities), your suggestions runs against the naming scheme.
By migrating to a newer Version all these classes need to be renamed.

**Comment by cvrebert** [comment]
@bpierson I tend to agree with Tom. Do you have a counterargument?

**Comment by bpierson** [comment]
No, Tom's argument makes sense. I was thinking too narrowly in terms of grid visibility, but in the broader terms of media queries the current naming convention makes more sense. Thanks.
