### ISSUE TITLE
Can't set a variable value into bootstrap popover

### ISSUE THREAD

**Issue by RReji** [twbs/bootstrap#20292]
('button').popover({
    title: 'John',
    content: 'Loading...'
});

    
var popover = $('button').data('popover');

setTimeout(function() {
var dt6 = new Date(stays[page-1].sty_DateCreated) ;
    dt6.setDate(dt6.getDate() - 1) ;
    $('button').attr('data-content',dt6);
    var popover = $('button').data('popover');
    popover.setContent();
    popover.$tip.addClass(popover.options.placement);
},500);

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
