### ISSUE TITLE
btn-group-vertical gaps with toggle buttons

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20298]
btn-group-vertical leaves gaps when used with label-style toggle buttons. On the left is standard vertical group, followed by checkbox and radio versions:

![btn-group-vertical_1](https://cloud.githubusercontent.com/assets/6351149/16822284/92fa4cdc-4918-11e6-9bae-4b7d323d313f.png)

```
<div class="btn-group-vertical" data-toggle="buttons" role="group">
    <label class="btn-secondary btn">
        <input type="checkbox" /> One
    </label>
    <label class="btn-secondary btn">
        <input type="checkbox" /> Two
    </label>
    <label class="btn-secondary btn">
        <input type="checkbox" /> Three
    </label>
</div>
```

**Comment by wolfy1339** [comment]
I don't think that class is designed to be used with label

**Comment by bpierson** [comment]
Possibly. Switching from `label` to something non-semantic like `span` seems to fix the problem. The docs use `label` for toggle buttons. The following works:
```
<div class="btn-group-vertical" data-toggle="buttons">
    <span class="btn-secondary btn">
        <input type="checkbox" /> One
    </span>
    <span class="btn-secondary btn">
        <input type="checkbox" /> Two
    </span>
    <span class="btn-secondary btn">
        <input type="checkbox" /> Three
    </span>
</div>
```

**Comment by cvrebert** [comment]
Did you test against v4.0.0-alpha.2, or against the v4-dev branch?

**Comment by bpierson** [comment]
It's the dev branch. I learned that lesson on the first issue that I opened. =c)
