### ISSUE TITLE
Some (Clock, Stopwatch, Alarm) Glyphicons Not Showing In Chrome, Safari, Firefox

### ISSUE THREAD

**Issue by artforlife** [twbs/bootstrap#20306]
I have a simple Angular code that iterates through a list of items and populates a page with them. Below each item it includes a few buttons with glyphicon styles. Here it is:
```
` <li ng-repeat='activity in activities | orderBy: activity.totalTime' class="list-group-item" ng-controller="TimerCtrl">
    		<a href="/#/activity/{{activity._id}}" class="btn btn-warning btn-block badge" ng-style="{'background-color' : activity.color, 'color' : activity.colorTitle, 'border-color' : activity.colorBorder}" ng-class="{'pulsation' : pulse , 'nonpulsation' : !pulse}" ng-init="pulse = false">
            	{{activity.title}}
            	
               	<span class="badge" ng-style="{'background-color' : activity.colorSupport, 'color' : activity.colorFont}">Current: {{counter | secondsToHHmmss }}</span>
            	<span class="badge" ng-style="{'background-color' : activity.colorSupport, 'color' : activity.colorFont}">Total: {{activity.totalTime | secondsToHHmmss }}</span>
            	
        	</a>
        	
        	<div class="btn-toolbar btn-toolbar-justified" ng-controller="toggleCtrl" ng-style="{'padding-top' : '30px', 'padding-left' : '10px'}">
	        		   
	        	     	<a ng-click="toggle =!toggle; $parent.pulse = !$parent.pulse; toggleTimer()" ng-class="{'glyphicon glyphicon-pause' : toggle , 'glyphicon glyphicon-play-circle' : !toggle}" ng-style="{'cursor': 'pointer'}"></a>
	        	     	<a href="/#/add-activity/{{activity._id}}" class="glyphicon glyphicon-plus-sign" ></a>
	        	     	
	        	     	<a colorpicker="hex" href="" ng-controller="ColorCode" ng-model="hexPicker" ng-init="hexPicker = activity.color" class="glyphicon glyphicons glyphicon-tint"></a> 
	        	     	<a href="/#/add-activity/{{activity._id}}" class="glyphicon glyphicon-clock"></a>
	        	     	
					 	<a href="/#/activity/delete/{{activity._id}}" class="glyphicon glyphicon-trash"></a> ` 
```

I omitted the bottom part of the ng-repeat for brevity. All of the icons except for glyphicon-clock show up. I have also tried glyphicon-stopwatch and glyphicon-alarm. They do not show. 

In the past, I have discovered that some other (database-related) icons would also not display here. Is this a bug or am I doing something wrong?

**Comment by patrickhlauke** [comment]
bootstrap only contains a subset of glyphicons http://getbootstrap.com/components/#glyphicons-glyphs

**Comment by wolfy1339** [comment]
If I may add, Bootstrap's version of Glyphicons is outdated. So, that may be why it is not included.
Follow patrickhlauke's advice and check the docs for all the glyphs included

**Comment by artforlife** [comment]
What is the reason why not all of them are included?

**Comment by patrickhlauke** [comment]
as it says on the documentation:

> Includes over 250 glyphs in font format from the Glyphicon Halflings set. Glyphicons Halflings are normally not available for free, but their creator has made them available for Bootstrap free of cost. As a thank you, we only ask that you include a link back to Glyphicons whenever possible.

so note it's the HALFLINGS set (not the full set) that is included (and halflings doesn't have the stopwatch icon either). i seem to remember that the set has been expanded by the author since its inclusion here in bootstrap, and it may be that the author hasn't provided us with the latest copy (@mdo or @cvrebert may know more).

as v4 drops glyphicons, i don't think there's going to be any major effort to update to latest halflings in v3 though.
