### ISSUE TITLE
Native position:sticky CSS not working in divs nested in grid columns 

### ISSUE THREAD

**Issue by marcanuy** [twbs/bootstrap#20307]
This is the screencast of the `position:sticky` applied to the whole sidebar column, and then applying the same `sticky` class to a `div` inside the column (that does not work):

![stickyy2](https://cloud.githubusercontent.com/assets/954673/16876996/9746d6f6-4a7c-11e6-8a7f-7a7012f4e5ac.gif)

Full details: http://stackoverflow.com/q/38382043/1165509
Codepen: https://codepen.io/marcanuy/pen/YWYZEp

Tested it Ubuntu 16.04 LTS with:

- Firefox 47.0 with css.sticky.enabled=“true” under about:config
- Chrome 50.0.2661.94 (64-bit) with experimental Web Platform features enabled in chrome://flags

Using Bootstrap 4 alpha:

- https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css
- https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
- https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js

**Comment by cvrebert** [comment]
The `.col-xs-4` isn't as tall as the `.col-xs-8`, so there's basically no space for the Menu to "float" within when the stickiness kicks in.
Make the `.col-xs-4` taller and things work fine: https://codepen.io/anon/pen/OXzoNJ
If you enable the Flexbox version of our grid system (via `$enable-flex: true;`), you get automatic equal-height columns for free, which comes in handy in your case.

**Comment by marcanuy** [comment]
I had missed that one. It did the trick, thanks!
