### ISSUE TITLE
Docs production JS is broken

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#20302]
So after https://github.com/twbs/bootstrap/commit/d4805c2c3dcae527ca3948bc93373e2d56068633 we are getting `TypeError`s when running the production docs.

https://github.com/bryanbraun/anchorjs/commit/6140a5285122fdc96ad9df49301bfd00f37d0576#commitcomment-18242789

v4 isn't affected (yet) since #20288 isn't merged yet.

/CC @cvrebert

**Comment by cvrebert** [comment]
Or we could just use a CDN instead of vendoring it.

**Comment by XhmikosR** [comment]
Well, the idea is to reduce the number of files.

Anyway, still waiting for a reply but if I don't get one until I'm back I'm gonna revert the update.

**Comment by XhmikosR** [comment]
I reverted it for now.
