### ISSUE TITLE
.embed-responsive video has 0 height when Flexbox is enabled

### ISSUE THREAD

**Issue by GuerrillaCoder** [twbs/bootstrap#20327]
I am using this code to embed a video:
```
<div class="container">
  <div class="row">
    <div class="embed-responsive embed-responsive-16by9">
      <video class="embed-responsive-item" controls>
            <source src="https://0.s3.envato.com/h264-video-previews/75d04469-5a0a-44c0-81af-d206845de439/854411.mp4">
            Your browser does not support the video tag.
        </video>
    </div>
  </div>
</div>
```
With the standard out of the box v4 alpha 2 it works fine.  With the flexbox support enabled it seems like the video has 0 height although the row height is correct.  I tried to override the height but was unable to do so, it is fixed at 0 height so the video is not visible.

Any ideas why it's doing this with flexbox?  I have attached the css/js I am using

[bs.zip](https://github.com/twbs/bootstrap/files/371798/bs.zip)

**Comment by cvrebert** [comment]
In which browser(s) have you observed the problem?

**Comment by Lewiscowles1986** [comment]
I've copied the code and made a codepen http://codepen.io/Lewiscowles1986/pen/BzYEZj
looks like I am getting the 0 height bug in chrome, firefox or opera on xenial 64-bit using the attached build

**Opera** 38.0.2220.41
**Chrome** 51.0.2704.106 (64-bit)
**Firefox** 47.0 (Firefox for ubuntu)

**Comment by twbs-lmvtfy** [comment]
Hi @Lewiscowles1986!

You appear to have posted a live example (http://codepen.io/Lewiscowles1986/pen/BzYEZj.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 11, column 5: [E013](https://github.com/twbs/bootlint/wiki/E013): Only columns (`.col-*-*`) may be children of `.row`s

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Lewiscowles1986** [comment]
Bug squished... you need to have a col defined. I supplemented the example with `col-xs-12`, seems to restore video height in all browsers

**Comment by cvrebert** [comment]
Closing this then.
:heart: Bootlint
