### ISSUE TITLE
Consider using cssnano instead of cssmin

### ISSUE THREAD

**Issue by Olivia101** [twbs/bootstrap#20324]
I suggest using cssnano (https://www.npmjs.com/package/cssnano) to minify the CSS code as it does a much better job.

Add cssnano to grunt/postcss.js
use: [
    'postcss-flexbugs-fixes',
    'autoprefixer',
    'cssnano'
  ]

cssnano: {
    safe: true,
    sourcemap: false
  }

Also, add "cssnano": "^3.7.3" to package.json

**Comment by cvrebert** [comment]
For reference: http://goalsmashers.github.io/css-minification-benchmark/

**Comment by mdo** [comment]
Looks like we switch to clean-css at some point, so closing out. https://github.com/jakubpawlowicz/clean-css
