### ISSUE TITLE
Consider adding word-wrap:break-word to Reboot

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20323]
Refs https://github.com/twbs/bootstrap/pull/18927#issuecomment-233224020
Has anyone ever actually wanted the Web's default "text runs outside of the box and often creates a scrollbar" behavior?

**Comment by eddyerburgh** [comment]
Agreed, should be default. I'll create a PR if others agree

**Comment by neatonk** [comment]
Just noting that if `word-wrap: break-word` is applied globally (e.g. to the `body` tag) then it needs to be overridden locally for something like `overflow: hidden; text-overflow: ellipsis` to work as expected.

**Comment by mdo** [comment]
Closing as stale.

**Comment by leafac** [comment]
Hi all,

I started a pull request to bring new life into this issue: https://github.com/twbs/bootstrap/pull/33954

Please let me know what you think.
