### ISSUE TITLE
Babel - "path must be a string" when compiling v4 from npm module

### ISSUE THREAD

**Issue by GuerrillaCoder** [twbs/bootstrap#20322]
I am trying to compile from the V4 alpha 2 NPM module.

~~My first issue was that grunt complained that `sauce_browser.yaml` and the `bs-sass-compile` directory was missing so I added them from the stand alone download.~~

I ran grunt again and majority of tasks seem to complete but when it gets to babel it gives this error:

```
Running "babel:dev" (babel) task
Warning: Path must be a string. Received undefined Use --force to continue.

Aborted due to warnings.
```

I am unfamiliar with grunt and not sure what to do to fix.  Anyone know what the issue is here?

**Comment by cvrebert** [comment]
> My first issue was that grunt complained that sauce_browser.yaml and the bs-sass-compile directory was missing

That part has been fixed via #19328.

**Comment by cubanpete** [comment]
I have the same problem with

> Warning: Path must be a string. Received undefined Use --force to continue.

Did you find solution to the problem?

Thanks
Kasper

**Comment by norgeous** [comment]
I has the same error. [Apparently](https://github.com/babel/grunt-babel/issues/56#issuecomment-154431982), it's an ambiguous way of saying 'a file was not found'

when installing from npm with
```
npm install bootstrap@4.0.0-alpha.3
cd node_modules/bootstrap
npm install
grunt dist
```
the node repo only includes the scss files and **not the js source**, hence the grunt task fails when it gets to the js section... the css files are produced properly, but the js files are both 1kb.

I installed the github version with:
```
npm install https://github.com/twbs/bootstrap/tarball/v4-dev
```
to get the 'full' repo, and then the `grunt dist` command went through perfectly.

now I can use _bootstrap4 flexbox edition_!

**Comment by cubanpete** [comment]
Awesome norgeous, thanks a million, I'll try that tonight.

**Comment by pr0jectile** [comment]
Hi @cubanpete did you try this? What were your findings? @norgeous are you using `npm install https://github.com/twbs/bootstrap/tarball/v4-dev` after `cd node_modules\bootstrap`?

**Comment by norgeous** [comment]
Hi @pr0jectile, sorry that my comment was not clear enough...
try this order:
```
npm install https://github.com/twbs/bootstrap/tarball/v4-dev
cd node_modules/bootstrap
npm install
grunt dist
```
you can make changes to `node_modules/bootstrap/scss/_variables.scss` before running the `grunt dist` command

**Comment by bardiharborow** [comment]
Is there anything further that needs to be done here?
