### ISSUE TITLE
v4: Dark version for Stacked pill on `.bg-primary`

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#20348]
The stacked pills don't react to color changes in their background and don't have an inverse or dark version.
http://v4-alpha.getbootstrap.com/components/navs/#pills
This is probably similar to #18115.

- when the wrapper of `nav nav-pills nav-stacked` has `bg-primary`, shouldn't the pill be inverted?
- should there be a `nav-inverse` or a `nav-dark` add on class?

Right now, it looks like this
<img width="526" alt="bildschirmfoto 2016-07-23 um 06 43 25" src="https://cloud.githubusercontent.com/assets/111561/17075846/fc4bc85c-50a0-11e6-92fb-91df161e3682.png">

**Comment by mdo** [comment]
Pills and anything else within `.bg-*` classes will not automatically change. We can't accurately predict the structure or style of the content around these things, so that's up to you. I'd recommend extending the nav classes or overriding them for things like this.
