### ISSUE TITLE
Upgrade font stack for non-Apple visitors

### ISSUE THREAD

**Issue by JoeArizona** [twbs/bootstrap#20346]
The current sans-serif font stack favors Mac and iOS device owners, then drops everyone else into generic/Arial.

> @font-family-sans-serif:  "Helvetica Neue", Helvetica, Arial, sans-serif;

Most site visitors for most sites do not use Apple devices, so this is a strange cultural bias that seeped into the code.

Issue #13823 talks about issues with Windows, but what really struck me from that 2014 thread was that Bootstrap was using _Arial_ for Windows. I confirmed that this is still the case, as seen in the snippet above.

Windows has many fonts, and Arial is a poor choice here. Note also that Arial is the sans fallback, so listing Arial in the font stack is pointless – the generic sans-serif fallback is sufficient.

#### Suggested upgrades for non-Apple site visitors:

**Windows:** Calibri

**Android:** there are hardly any fonts on Android, and the fallback will be Roboto or Droid Sans, which are fine

**Linux:** Liberation Sans and/or Linux Biolinium (the former should be on most distros, and the latter comes with LibreOffice). Liberation Sans might be the sans fallback – if so, it would be as redundant as Arial and could be excluded.

**Useful source for pre-installed fonts on Windows, Mac, and Ubuntu:** http://www.apaddedcell.com/web-fonts

**Comment by wolfy1339** [comment]
This was fixed by #19098 in v4, it might be a little late to fix this in v3 though.

**Comment by cvrebert** [comment]
Yeah, this is probably off the table for v3 at this point.
Feel free to make suggestions regarding v4 though.

**Comment by JoeArizona** [comment]
Is this for UI elements only, e.g. buttons, or does it enfold headings and body content? The Smashing article by the Medium guy is very problematic, but in any case it's singularly obsessed with fonts that are called "system fonts" somewhere, whether by the browser or in OS docs. These are fonts used in native UI elements, not meant for textual content, body, etc. (Sitka Text is the new Microsoft font for content, since Win 8.1, but it's a serif.)

If that "system font" stack is slated for content in v4, it should probably be updated with body fonts. For UI elements, that system stack will be a nice upgrade over Arial, so I'm glad it's already done.

**Comment by mdo** [comment]
System font stack is for everything in v4—headings, body, UI, etc. That stack needs work for sure—I ran into a few problems with what's in v4 when adding it to GitHub's stack. No changes coming to the font stack for v3, though.
