### ISSUE TITLE
Bug Report: Boostrap SASS Installation. 

### ISSUE THREAD

**Issue by jgacuca567** [twbs/bootstrap#20340]
After Installing `bootstrap-sass` using `npm`, this is the error that I get below. Looks like the issue was never resolved according to issue #18368. 

<img width="1137" alt="screen shot 2016-07-21 at 10 39 30 am" src="https://cloud.githubusercontent.com/assets/4000076/17027053/60ae870c-4f30-11e6-96ab-42ed490da9c2.png">

@cvrebert is it the file that has a problem or what could be the problem?

**Comment by patrickhlauke** [comment]
this should probably be filed under the bootstrap-sass repo? https://github.com/twbs/bootstrap-sass

**Comment by jgacuca567** [comment]
@patrickhlauke , Have Filed the Issue under `bootstrap-sass`

**Comment by cvrebert** [comment]
Successor: https://github.com/twbs/bootstrap-sass/issues/1057
