### ISSUE TITLE
v4: Expand documentation for "Available variables"

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#20347]
I am wondering what the variables that are documented at http://v4-alpha.getbootstrap.com/getting-started/options/ do.

There are a few things that could be improved for the documentation:
- [ ] The `$spacer` is no longer specified in this part of the code but still documented there
- [ ] "various components" should be more specific on this page, like a linked list of componets that shows the examples for each of the component
- [x] Also, are there component-specific variables as well that I could use to cherry pick "this component with rounded border, that without"?
- [ ] And on each component-documentation page, there should be an example of both settings with link to the global variables documentation page
- [ ] maybe add a link to from the source to the doc? Like so:

```
// Options
//
// Quickly modify global styling by enabling or disabling optional features.
// See http://v4-alpha.getbootstrap.com/getting-started/options/
```

**Comment by cvrebert** [comment]
> Also, are there component-specific variables as well that I could use to cherry pick "this component with rounded border, that without"?

Not currently. Feel free to file a separate issue to request such a feature.

**Comment by cvrebert** [comment]
>  And on each component-documentation page, there should be an example of both settings with link to the global variables documentation page

Not sure what you mean by "both settings" here. Is this point in reference to the previous rounded corners point?

**Comment by mdo** [comment]
Going to punt on this task list. We do need to clean up the spacer stuff though before we hit the first beta so that's clearer.
