### ISSUE TITLE
nav links pipe line dividers 

### ISSUE THREAD

**Issue by mojtabakaviani** [twbs/bootstrap#20355]
Add `nav-inline-pipe` class for separate nav links with pipe lines.

**Comment by cvrebert** [comment]
@mojtabakaviani Erm, you mean like a vertical version of the `.divider` shown in http://getbootstrap.com/components/#btn-dropdowns-single ?

Also, please add more details. Per [the issue template](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md):
> When suggesting a feature, include:
>
> * As much detail as possible for what we should add and why it's important to Bootstrap

**Comment by mdo** [comment]
I think I know what he's getting at, and the answer is no thanks—that's a perfect example of what folks should do to extend Bootstrap themselves.
