### ISSUE TITLE
Top of modal within iframe isn't in view when modal is shown on iOS

### ISSUE THREAD

**Issue by psukmak** [twbs/bootstrap#20352]
os:  IOS 9.3.3
Browser: Chrome , Safari, Firefox
Mobile : iphone 5, 6
Bootstrap :  v4.0.0-alpha.2

On first image, I have form put into iframe.
On second imag,I have change location button that put into middle of the form above. when click will show modal. 
![13615388_1209496925747718_8387065026170878775_n](https://cloud.githubusercontent.com/assets/20636845/17097183/d1af6d6e-5286-11e6-9db0-a5470720892d.jpg)   ...............................          ![13754280_1209498572414220_7091115259155697470_n](https://cloud.githubusercontent.com/assets/20636845/17097186/d5195956-5286-11e6-80d3-7e4a8f30bcff.jpg)

On nexus 5 android version 6.0.1
- When click change location button, it shows perfect. Header of modal show first.
- Form behide of modal cannot scroll  
  ![android1](https://cloud.githubusercontent.com/assets/20636845/17097402/d5112cd0-5287-11e6-98dc-5683303627db.png)

On Iphone 5 
- When click change location button, it will show not right. Header of modal not show first. It relates to height of the iframe.
-  Form behide of modal can scroll
-  When show modal it will be put modal-open class into body in the iframe and modal-open class is overflow: hidden; but this css not working on iphone
  
  ![13775828_1209496902414387_616818270966338745_n](https://cloud.githubusercontent.com/assets/20636845/17097412/e07472b2-5287-11e6-8f2e-8ec1553567fb.jpg)

**Comment by cvrebert** [comment]
> On nexus 5 android version 6.0.1

Please open a separate issue for that. Much appreciated.

**Comment by cvrebert** [comment]
Also, we cannot debug screenshots. Please make a reduced test case using JS Bin (or similar).

**Comment by psukmak** [comment]
On nexus 5 everything OK. I just show right case.

**Comment by psukmak** [comment]
about on iPhone, I upload example code to my server

http://appsoftplus.com/index-test.html

**Comment by chaiyot** [comment]
There are 2 issues for iframe in Safari's iPhone from that example.
1. Modal doesn't show at the correct position (center of the page) if we put the button down at some level in the iframe (if we put the button at the beginning of iframe it's still works).
2. Contents inside iframe has been stop displayed for long contents (Cannot scroll down) on iPhone.

**Comment by chaiyot** [comment]
We've manually fix modal show incorrect position in iframe on iPhone by calling focus event again using javascript.It's works.

**Comment by majianxiong** [comment]
@psukmak Did you solve?

**Comment by majianxiong** [comment]
@chaiyot Did you solve？

**Comment by psukmak** [comment]
@majianxiong No, I did not.  I waiting  update from bootstrap 
but you can  ues manually fix:
$('#myModal').on('shown.bs.modal', function (e) {
    // focus somewhere in modal
});

$('#myModal').on('hidden.bs.modal', function (e) {
    // focus somewhere in body
});

**Comment by majianxiong** [comment]
![image](https://cloud.githubusercontent.com/assets/887531/17921882/b58cf170-6a0e-11e6-9536-183619688fcc.png)
![image](https://cloud.githubusercontent.com/assets/887531/17921891/c6ec5d8e-6a0e-11e6-96b8-d350b12d50c7.png)
But not in the middle

**Comment by majianxiong** [comment]
@psukmak  $(document).scrollTop() is zero

**Comment by majianxiong** [comment]
Relevant solutions：

- https://medium.com/@dvoytenko/amp-ios-scrolling-and-position-fixed-b854a5a0d451#.dfo4munsj

- https://zafiel.wingall.com/archives/8198
There is no validated.

**Comment by majianxiong** [comment]
problem is resolved

**Comment by cvrebert** [comment]
> about on iPhone, I upload example code to my server
> http://appsoftplus.com/index-test.html

Copied to Plunker for durability: https://plnkr.co/edit/jYMgPUsBwAuTCCze3KWe?p=preview

**Comment by cvrebert** [comment]
Updated the Plunk: https://plnkr.co/edit/jYMgPUsBwAuTCCze3KWe?p=preview

**Comment by cvrebert** [comment]
> * Form behind of modal can scroll
> * When show modal it will be put modal-open class into body in the iframe and modal-open class is overflow: hidden; but this css not working on iphone

This portion seems to be referring to https://bugs.webkit.org/show_bug.cgi?id=153852 , which we've already reported to WebKit.

**Comment by cvrebert** [comment]
> When click change location button, it will show not right. Header of modal not show first. It relates to height of the iframe.
> [...]
> Modal doesn't show at the correct position (center of the page) if we put the button down at some level in the iframe (if we put the button at the beginning of iframe it's still works).

I can confirm that the user sees the middle of the modal in iOS Safari and the top of the modal in Android Chrome, when the modal within the iframe is initially shown.
Will need to do some more testing to determine who's deviating from the standards and how.

**Comment by jeremyjcpaul** [comment]
I've also been having problems with this issue. See this JS Fiddle https://jsfiddle.net/tmfq0rnm/4/. It works perfectly everywhere except on iOS due to the iframe issue. On iOS tapping "Click here" will cause the iframe to jump to the bottom rather than to where the modal is displayed. Do we know what the status is of this issue? Is there a good fix for it in the meantime? Looking at the previous comments it seems like all the "fixes" may brake other things which I need to avoid.

**Comment by cristianocordeiro07** [comment]
I fixed this issue with the following solution:

$('#formViewIframe').load(function () {	            	
		resizeIframeForm();
}

function resizeIframeForm() {
		
	if( (navigator.userAgent.match(/iPhone/i)) || (navigator.userAgent.match(/iPod/i))) {
		// block scroll for mobile;
		// causes underlying page to jump to top;
		// prevents scrolling on all screens
		$('body.modal-open').css('overflow', 'hidden');
		$('body.modal-open').css('position', 'fixed');
	} 
}

**Comment by mdo** [comment]
This is super stale, and I'm not seeing a clear issue anymore with a live demo. I updated the last Fiddle link to the latest version of v4.x and things look okay to me I think? https://jsfiddle.net/deghcsuv/

Closing out.
