### ISSUE TITLE
.table-sm is a potentially confusing name

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20350]
Small nit-pick issue, but the v3 `.table-condensed` was renamed to `.table-sm` in v4. This seems like an unnecessary and potentially confusing name change, as it has nothing to do with floats, alignment, or viewport size. I think the old `.table-condensed` was perfectly descriptive.

**Comment by cvrebert** [comment]
We use the `-sm` and `-lg` naming convention unrelated to viewport size in several other widgets (btns, modals, input-groups, pagination) besides tables at this point.
If we were to switch schemes, the new scheme ought to be similarly generic across widgets, IMHO.

**Comment by mdo** [comment]
Leaving it for now, but noted for future iterations. Thanks!
