### ISSUE TITLE
Consider alternative method of styling toggle buttons (don't use data-toggle="buttons" for styling) 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [twbs/bootstrap#20359]
I'm part of the [angular-ui/bootstrap](http://angular-ui.github.io/bootstrap) team working on native Angular directives using Bootstrap markup. 

As part of the effort to migrate to Angular 2 and Bootstrap 4 we've started the ng-bootstrap project here: https://ng-bootstrap.github.io 

So far the progress is very smooth and I couldn't be more grateful for all the splendid job that you are doing here on Bootstrap 4. 

There is just one glitch that we've encounter so far: when using button groups (ex. [check-box](http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons) ) we need to add `data-toggle="buttons"` to get proper styling on inputs. While I totally see how it works perfectly with provided jQuery plugins, it is not very intuitive for people not using jQuery but rather using a framework like Angular or React.

Would you consider another method of styling toggle buttons, for example using a dedicated CSS class (eg. `.toggle-buttons`)?

**Comment by cvrebert** [comment]
We're trying to axe the buttons.js JavaScript entirely in v4 and replace it with a pure-CSS `+ :checked`-based approach. See #18874.
I believe that should adequately address your concern?

**Comment by pkozlowski-opensource** [comment]
@cvrebert yes,  #18874 would solve my problem _and_ will make the whole integration on our side trivial :+1: 

Going to close this one and keep an eye on #18874 

Thnx for the quick answer and all the awesome work you guys are doing here!
