### ISSUE TITLE
Trailing &

### ISSUE THREAD

**Issue by BlueUrbanSky** [twbs/bootstrap#20351]
Feature: Allow the Bootstrap LESS to be included using conditional LESS/SASS in a project.

Hi we use bootstrap 3 as a isolated include using an id to give it high specificity over our old core css. We wrap the include in a #bootstrap this works well in keeping the 2 sets of rules separate for the most part but a problem occurs with the use of training & 

The use of this structure:
`.btn & {
    position: relative;
    top: -1px;
  }`
will transpile to:
`.btn #bootstrap .badge {
    position: relative;
    top: -1px;
  }`

There seems to be 28 uses of this in the SASS(which is converted from the LESS source). I understand that I have a use case that is not typical but it seems like only a small loss in grouping. I have no problem doing the work myself and submitting a pull request If that is acceptable?

**Comment by cvrebert** [comment]
I'm reasonably sure this has come up before, with the answer being No.
@mdo Can you confirm?

**Comment by mdo** [comment]
Can confirm, not going this route.

**Comment by BlueUrbanSky** [comment]
ok thanks
