### ISSUE TITLE
Support of base text direction for Bootstrap v4 JS widgets 

### ISSUE THREAD

**Issue by ashensis** [twbs/bootstrap#20378]
The must to have requirement to any program product from the Arabic/Hebrew customer's perspective is support for base text direction. For detailed explanation of what base text direction term means please see, for instance, pages 5-9 of the following reference document. 

​https://docs.google.com/document/d/1dDrSwimrQbpbXybhMYDEiJXLeeqvelnY4cc8HeCP1Nk/edit?usp=sharing 

Every platform (like MS Office or Open Office) or web based (like CKEditor, IBM Docs) text editor as well as large variety of program products and platforms (like dojo) allows the possibility to specify the base text direction that impacts the display of Arabic/Hebrew text. 
The current proposal is to introduce the base text direction into Bootstrap JS widgets. Possible candidates for support are  Popover and Tooltip (these widgets create their HTML markup dynamically). 

How to specify 'base text direction' for bootstrap widgets
Bootstrap widgets would provide BTD basing on 'textdir' option been passed to widget constructor.
Alternatively BTD may be specified decoratively as 'data-textdir' attribute of corresponding html element.

Allowed values are: "ltr" (left-to-right), "rtl" (right-to-left) and 
"contectual" (meaning that either 'ltr' or 'rtl' value is used depending on 
the first strong(Arabic/Hebrew or English) character of string been displayed.  

Note: The bootstrapBidi.js script file (containing added functionality) might be loaded, by side of primary bootstrap script
(either bootstrap.js or bootstrap.min.js) in order to enable 'base text direction support

**Comment by mdo** [comment]
If we did this, it'd be part of a holistic RTL approach, something we don't have the ability to undertake at this point. Passing on this until then.

**Comment by tomerm** [comment]
@mdo and @cvrebert based on _"For now, please wait until we ship a stable v4.0.0 release. At that point, we'd gladly welcome a pull request that implements a primarily-conversion-tool-based approach to RTL."_ from #19555 , it looks like PRs associated with basic Bidi / RTL support are welcomed after shipment of first stable v4.0.0. Proper layout and display of bidirectional text (Arabic / Hebrew / Farsi etc.) discussed in this ticket is inseparable from GUI mirroring described in  #19555 . We would appreciate if you can allow us to submit a PR (once stable v4.0.0 releases) illustrating the functionality described in this ticket.

Many thanks in advance. 

PS.   @ashensis who created this ticket is part of my development team called Bidi Development Lab. We join efforts with Arabic Competence and Globalization Center (opened #19555 ) in addressing Bidi (Arabic / Hebrew ) requirements in variety of technologies.

**Comment by cvrebert** [comment]
> it looks like PRs associated with basic Bidi / RTL support are welcomed after shipment of first stable v4.0.0.

That is correct.
