### ISSUE TITLE
Do not work navbar-static-top with determine style body

### ISSUE THREAD

**Issue by vvp24** [twbs/bootstrap#20374]
Do not work navbar-static-top menu with style:

html, body {
  overflow-x: hidden; /* Prevent scroll on narrow devices */
}

This style use in menu offcanvas

Problem discussion here: http://stackoverflow.com/questions/20962524/bootstrap-3-0-affix-doesnt-work-when-body-has-overflow-xhidden

**Comment by mdo** [comment]
Closing as a won't fix to v3.
