### ISSUE TITLE
v4 Docs incorrect

### ISSUE THREAD

**Issue by th3fallen** [twbs/bootstrap#20377]
On your v4 docs you still have labels listed http://v4-alpha.getbootstrap.com/components/label/ while they have been updated to be tags, the docs dir appears correct but may not have been deployed.

I couldnt find another issue for this if there is please close me.

**Comment by patrickhlauke** [comment]
the docs are currently still for v4.0.0-alpha.2 http://v4-alpha.getbootstrap.com/

**Comment by th3fallen** [comment]
Ah you're right im installing via npm with `git+https://github.com/twbs/bootstrap.git#v4-dev` that explains it. Thanks
