### ISSUE TITLE
.caret in collapsed .navbar-fixed-bottom should point down

### ISSUE THREAD

**Issue by PowerGamer1** [twbs/bootstrap#20376]
Bootstrap v3.3.6.
When Navbar with .navbar-fixed-bottom class has a Nav with Dropdown and Navbar is collapsed (browser window size is less than 768px) the caret (.caret class) in Nav items that open Dropdown should point down since the Dropdown menu opens under the Nav item clicked not above it.

**Comment by Hopper262** [comment]
This same issue also happens with .dropup menus inside a non-fixed navbar. As a workaround, I'm using the following CSS:

    @media (max-width: 767px) {
      .navbar-collapse .dropup .caret,
      .navbar-fixed-bottom .navbar-collapse .dropdown .caret {
        border-top: 4px dashed;
        border-bottom: 0;
      }
    }

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
