### ISSUE TITLE
Fork Normalize

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#20388]
Reading through #20384, and looking at the history of Normalize, I think it might be time to explore forking the project and combining it with our own Reboot. There are a few styles in Reboot that override Normalize anyway, so at some point I'd like to take a deeper look at this.

**Comment by tomlutzenberger** [comment]
So this means that normalize.css will no longer just be included as kind of a "component" but actually merged with the current code base?

**Comment by kkirsche** [comment]
Would you want to keep a proper fork of it in a separate repo or would you prefer to incorporate it inline within this repo? My thought would be a full fork in a separate repo which you then incorporate in, this would allow you to pull in any upstream changes easier (as I see it) while maintaining the overrides.

**Comment by mdo** [comment]
Going to punt on this for v4. Not toooooo stoked for keeping up with this just yet seeing how much Normalize is already doing for us.
