### ISSUE TITLE
<select multiple> overflows

### ISSUE THREAD

**Issue by danieldecsi** [twbs/bootstrap#20384]
Operating system and version: Ubuntu 14.04
Browser and version: Chrome 52.0.2743.82

Options overflow on multiple selects if there are at least 5 options.
http://codepen.io/anon/pen/GqGdbw
https://s3.amazonaws.com/upload.screenshot.co/33f65bef97

If am not mistaken it is caused by the overflow: visible; declaration set by normalize.css on selects. Possible solution is to upgrade it to the latest version, the declaration was removed in this commit: https://github.com/necolas/normalize.css/commit/e4a7827199b61e1cdcabe807044b3a2384bba924.

**Comment by pixelbandito** [comment]
So, is the solution here to fork normalize, or to upgrade it to the latest version?

I'd be happy to try the upgrade, if that's the consensus ...

**Comment by adamreed90** [comment]
I have switched the:

`select { overflow: visible; }` to `select { overflow: hidden; }` and the issue was corrected.

**Comment by FezVrasta** [comment]
`select` should have `overflow: auto`, not `scroll`

**Comment by bardiharborow** [comment]
@adamreed90, just removing `select` from the rule seems to work for me. Is there a particular reason you need the second rule?
