### ISSUE TITLE
Flexbox Vertical and Horizontal alignment not working on examples

### ISSUE THREAD

**Issue by Turqueso** [twbs/bootstrap#20382]
as you can see on the docs
http://v4-alpha.getbootstrap.com/layout/flexbox-grid/#vertical-alignment  
http://v4-alpha.getbootstrap.com/layout/flexbox-grid/#horizontal-alignment

Seems there isn't any `justify-content` or `align-items`

**Comment by mdo** [comment]
This is likely because my compilation of the flex grid doesn't include the flex utilities.

**Comment by mdo** [comment]
This was fixed in #20417.

**Comment by AlessandroVecchi** [comment]
it doesn't work yet...

**Comment by mdo** [comment]
@AlessandroVecchi The fix for this hasn't been deployed to the docs yet. It will be with the next alpha release.
