### ISSUE TITLE
Navbar items wrong position when in state "collapse in", with any navbar-toggleable-*

### ISSUE THREAD

**Issue by os1r1s110** [twbs/bootstrap#20392]
When using the new navbar component, there is a little problem with the alignment of the list items which appear right aside the navbar-brand when viewing the collapsed menu. 

I don't really know how to explain it clearly so here is an image which shows what I mean exactly. Maybe it's not a bug and if so, just tell me and I'll abide to your decision :P. IMO, the Home link should stand on it's own line. If we put a bigger navbar-brand, the problem gets even clearer as multiple items will be right beside the logo/brand image and others will flow under normally. 

![navbar_before_clear](https://cloud.githubusercontent.com/assets/1885400/17217530/a8ba9efa-54b2-11e6-9bd8-b729794901b4.jpg)

To reproduce, simply go the bootstrap 4 navbar documentation. The last example, the responsive one, will show this "bug" when window is resized enough to display the hamburger icon.

Then simply expand the navbar and it should be right there. 

Reproduced on Edge 25.10586.0.0 and Chrome 52.0.2743.82 on Windows 10. Not tested on other browsers.

I found a possible fix to this problem by adding a clear when the navbar is in "collapse" mode and viewed. 

https://gist.github.com/os1r1s110/7379c3ba0a0472a7c8b3da977864d041

![navbar_after_clear](https://cloud.githubusercontent.com/assets/1885400/17217533/aca0e45c-54b2-11e6-89af-8fd73dd242cc.jpg)

**Comment by os1r1s110** [comment]
Don't know why my gist doesn't work... I'll try something else.

**Comment by cvrebert** [comment]
Please use JS Bin or CodePen for sharing demos/test cases.

**Comment by os1r1s110** [comment]
@cvrebert All right I will try to do that in the future. But I have one question, how do I make corrections using codepen? I found how to load the newest bootstrap version (alpha 3) but not the v4-dev branch in it so I don't really know how it can be used to show bugs/solutions. Do I simply put the new scss and assume it will overwrite?

**Comment by mdo** [comment]
Resolved in #19890.

**Comment by Adonisjs-ace** [comment]
don’t overlook this https://crashing86.github.io/GurPTsKhuTLonSvncr2wAXCauo18LPHoz1R9ux3h9aN/ answer
