### ISSUE TITLE
Consider adding an "attached PR" label for issue tickets.

### ISSUE THREAD

**Issue by judetucker** [twbs/bootstrap#20399]
This works great for the Rails contributor community to easily sort through their issues to see what issues actually need work vs. which ones have work waiting to be merged.

Example: https://github.com/rails/rails/issues?q=is%3Aopen+is%3Aissue+label%3A%22attached+PR%22

Just a thought. Feel free to close.

**Comment by mdo** [comment]
As I remember to, I'll start adding this.
