### ISSUE TITLE
data-toggle collapse broken on href for alpha 3

### ISSUE THREAD

**Issue by joncoop** [twbs/bootstrap#20396]
The button with data-target still works, but the a href does not. It worked in alpha 2. Also, it does work on doc page, just not on my test site. Are docs/examples all using latest build?

If I use a button to open collapsed item, then href will correctly scroll to target. However, href scrolls to top of page if item is in collapsed state when link is clicked.

Copied code directly from here: http://v4-alpha.getbootstrap.com/components/collapse/#example

**Comment by judetucker** [comment]
I am unable to confirm this as an issue. It works as intended both locally for me as well as here: http://codepen.io/anon/pen/akjEpO

I would say check your code to see if you have an extra `href="#" ` in there somewhere that may be making your page push to the top.

**Comment by joncoop** [comment]
I found the problem. It was on my end. There is a conflict with some smooth scroll JS that I also had. As soon as I disable smooth scroll, everything worked fine. Here's the problematic code:

```
/* Smooth scroll to selected anchor
 * https://css-tricks.com/snippets/jquery/smooth-scrolling/
 */
$(function() {
  $('a[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});
```
