### ISSUE TITLE
Stacked and inlined checkboxes/radios markup

### ISSUE THREAD

**Issue by NicoLB** [twbs/bootstrap#20403]
I’d like to question the different markup used for stacked and inlined checkboxes (or radios) and ask if there is any reason behind it.

**Stacked**

```
<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input"> Stacked
  </label>
</div>
```

**Inlined**

```
<label class="form-check-inline”>
  <input class="form-check-input”> Inlined
</label>
```

Why not use a more consistent markup instead?

**Stacked**

```
<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input"> Stacked
  </label>
</div>
```

**Inlined**

```
<div class="form-check-inline">
  <label class="form-check-label">
    <input class="form-check-input"> Stacked
  </label>
</div>
```

On the .scss side we'd have something like that.

```
.form-check {
  display: block;
}
.form-check-inline {
  display: inline-block;
}
[class^=form-check] {
  // Shared by both Stacked and Inlined
}

.form-check-label {
  // Shared by both Stacked and Inlined
}

.form-check-input {
  // Shared by both Stacked and Inlined
}
```

This would avoid some CSS duplication we have right now between `.form-check-label` and `.form-check-inline`, and simply makes more sense in my opinion.

**Comment by caepenna** [comment]
Hmm, I totally agree a more consistent markup would be better.

It's worth pointing out that by doing so we'd be having one extra <div> container for the form-check-input where we had none. This might be a problem for some but its worth if the goal is standardizing the markup for check/radio inputs.

On your solution even the scss gets more elegant, I really like, kudos 😁

**Comment by notmessenger** [comment]
I also have some questions.

The chart at the bottom of the http://v4-alpha.getbootstrap.com/components/forms/#form-controls section lists these classes as being applicable to radio and checkbox controls:

* `.radio`
* `.radio-inline`
* `.checkbox`
* `.checkbox-inline`

The only such example though I see of these classes being used is in this code example within the same section:

```
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
```

The use of these classes seems to be contradicted (maybe?) in http://v4-alpha.getbootstrap.com/components/forms/#inline which uses a different set of classes for the inline or non-inline display of these controls.

Which classes should be used and when and how (in what combinations, etc)?

**Comment by mdo** [comment]
No more difference as of #20995.
