### ISSUE TITLE
Modal containing a table inside a fieldset extends past modal width (Firefox)

### ISSUE THREAD

**Issue by jarstelfox** [twbs/bootstrap#20400]
Env:
Windows 10 (Version	10.0.10586 Build 10586)
Firefox (47.0.1)

Test Case:
https://jsbin.com/verujaqezo/edit?html,output

Expected Results:
Responsive table is contained within modal.

Actual Results:
Responsive table extends past the modal's width.

Note:
Chrome and Edge are confirmed working with this test case.

**Comment by cvrebert** [comment]
Have you tried the CSS given in the "Firefox and fieldsets" box on http://getbootstrap.com/css/ ?

**Comment by jarstelfox** [comment]
@cvrebert Thank you for the quick reply. I missed this while looking at the docs. My apologies.
The css provided fixes the issue. Working example https://jsbin.com/yojewivise/edit?html,css,output
