### ISSUE TITLE
Adding <meter> tag support

### ISSUE THREAD

**Issue by aduh95** [twbs/bootstrap#20412]
Greetings,

As Bootstrap v4 replaces the old `.progress` `<div>` with a real `<progress>` element, we should consider adding [`<meter>`](https://html.spec.whatwg.org/multipage/forms.html#the-meter-element) support to better match the HTML semantics of each element.

I would also suggest that `<progress>` tag should be stripped by default, or even animated since it aims to represent the completion progress of a task (quoting [WHATWG spec](https://html.spec.whatwg.org/multipage/forms.html#the-progress-element)).

**Comment by cvrebert** [comment]
> I would also suggest that  `<progress>`  tag should be stripped by default, or even animated

Different folks always want different aesthetics. Plain-by-default with a single class each to opt into striping and animation makes it easy to keep everyone happy. Using 2 more classes isn't a heavy burden.

**Comment by mdo** [comment]
Closing as a won't fix given the `.progress` and lack of IE10 or IE11 support.

**Comment by xi** [comment]
Could this be reconsidered for v5?

**Comment by mdo** [comment]
I suppose so! How would meter differ from progress overall? Anything meaningful in it's display or rendering?

**Comment by xi** [comment]
As @aduh95 already explained:

> stripped by default, or even animated since it aims to represent the completion progress of a task

But @cvrebert already argued that it would be better to stick with plain styling by default and allow users to add additional striping and animation classes. I tend to agree with that.

**Comment by mdo** [comment]
Yeah, that still holds true IMO. Animating by default can be a performance hit for sure.

**Comment by xi** [comment]
I just realized that `<progress>` itself hasn't been supported since #21473. @mdo Do the reasons for removing `<progress>` sill apply or has something changed? I guess those reasons are likely to also affect `<meter>`.

**Comment by mdo** [comment]
Yeah still applies as far as I know. Closing out, but if someone finds a solution, I'll happily revisit :).
