### ISSUE TITLE
Use @padding-xs-horizontal on components

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#20429]
Change Request.

In the CSS, use @padding-xs-horizontal on components, e.g. alerts, tabs, panels

Why? I have an alert-component / panel-components inside a tab-component.
On a smartphone (portrait), the combined padding of both components is a good chunk of the available screen width.
On 'xs' screens only, it would be good to reduce horizontal padding.
There's already a variable - @padding-xs-horizontal - it just isn't used yet

i.e. something like:
.alert { padding: @alert-padding;}
@media screen and width < 768 { .alert { padding:@padding-xs-horizontal; } }

Apologies if this has already been suggested before ... I did search for it...

Andrew

,

**Comment by mdo** [comment]
No plans to add responsive variations to those kind of components for everyone. I'd rather let folks customize that on their own for each use case.
