### ISSUE TITLE
Tooltip always stays after click <a> (target="_blank") tag

### ISSUE THREAD

**Issue by dreamerblue** [twbs/bootstrap#20422]
This issue begins at v3.3.5. v3.3.4 works well.
For example, there's a html tag like this: `<a href="http://getbootstrap.com" target="_blank" data-toggle="tooltip" data-placement="right" title="bootstrap">bootstrap</a>`
If I click it, then close new page and return to the source page, tooltip will always stay, and it won't disappear even though I move mouse.

**Comment by cvrebert** [comment]
As requested in the [issue template](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md), please state which OS and browser you have observed the problem on.

**Comment by dreamerblue** [comment]
@cvrebert 
OS: OS X El Capitan
Safari: Both 3.3.5+ and 3.3.4 works well.
Chrome 51.0.2704.103: 3.3.5+ Tooltip won't disappear. 3.3.4 works well.

OS: Ubuntu 16.04
Firefox 47.0:  3.3.5+ Tooltip won't disappear. 3.3.4 is same.
Chrome 50.0.2661.94: 3.3.5+ Tooltip won't disappear. 3.3.4 works well.

OS: Windows 7
Chrome: 45.0.2454.101: 3.3.5+ Tooltip won't disappear. 3.3.4 is same.

**Comment by mevsme** [comment]
This affects me too in v4-alpha in Chrome 51, Ubuntu 15.04

**Comment by t47io** [comment]
Same here, only for SVG:

Chrome 52.0.2743.116, Mac OSX 10.11.6;
Bootstrap 3.3.7

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
