### ISSUE TITLE
Normalize forces '.dropdown .bg-inverse' to have a button appearance

### ISSUE THREAD

**Issue by Splinti** [twbs/bootstrap#20421]
Only applies for V4 alpha 3
As the title says,  the _normalize.css "forces" a dropdown-toggle "button" to have the appearence of a button, thus making it not appear as bg-inverse, but as a normal button. I needed to  reset `-webkit-appearance`  from `button` to `none` to fix the issue.

**Comment by cvrebert** [comment]
Please post a JS Bin or other example that demonstrates the problem.

**Comment by Splinti** [comment]
https://jsbin.com/borugimaqe/edit?html,output

This is  the JS bin you asked for.

**Comment by mdo** [comment]
You're markup is incorrect—you cannot set an anchor to have `type="button"`. Please revisit the dropdown documentation for how to use our JS and with what markup.
