### ISSUE TITLE
Popover title: .close needs margin

### ISSUE THREAD

**Issue by levu42** [twbs/bootstrap#20423]
Bootstrap v4, alpha3: If I add an `<button class="close">` to a popover heading, the close icon looks weird. Adding `margin: -0.2rem 0.1rem 0 1rem` to the close icon fixes this. [See live example.](http://codepen.io/anon/pen/pbkOZq)

**Comment by mdo** [comment]
We don't include the dismiss button in the default popover, so this is a customization on your part that will require additional CSS from you.
