### ISSUE TITLE
Support headings when using navs in .card-header

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#20420]
Currently, you have to choose between either a title or a nav inside a ```.card-header```. I think it would be nice if Bootstrap supports adding both a title and a nav in the same ```.card-header``` as shown here:

![knipsel](https://cloud.githubusercontent.com/assets/1693592/17272850/e6a79768-56a1-11e6-9b00-fefbbc449dd0.PNG)

**Comment by judetucker** [comment]
Hi @Studio384,

If I understand it correctly, the feature you are requesting can already be achieved right out of the box with v4. Check this pen out. http://codepen.io/anon/pen/QEBxpW

Let me know if this resolves this issue or if there is additional functionality that cannot be achieved.

**Comment by mdo** [comment]
Yup, can already be done :).
