### ISSUE TITLE
Modal displays behind its own gray background when it's a child of a position:fixed element

### ISSUE THREAD

**Issue by dk8996** [twbs/bootstrap#20433]
Bug with modal that wasn't happening in version 3.3.1.  Here is a [jsfiddle](http://jsfiddle.net/cdahju1r/).  Looks like if the modal is in a div with fixed position then the modal will be behind the gray background -- again this didn't happen in 3.3.1.  

[Version 3.3.1 jsfiddle](http://jsfiddle.net/ru1d6k1q/)

[Version 3.3.5 jsfiddle](http://jsfiddle.net/cdahju1r/)

[Version 3.3.6 jsfoddle](http://jsfiddle.net/wqv6dapu/)

**Comment by twbs-lmvtfy** [comment]
Hi @dk8996!

You appear to have posted a live example (http://fiddle.jshell.net/cdahju1r/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 33, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.3.5
* line 37, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.3.5

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @dk8996!

You appear to have posted a live example (http://fiddle.jshell.net/ru1d6k1q/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 33, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.3.1
* line 37, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Easy workaround: Set `z-index: 1050;` on `.my-module`.
My guess would be that your `position:fixed` creates a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), thus disrupting the Z-ordering somehow.

AFAIK, there's nothing we can do on our end without actually moving the `.modal` in the DOM, which would probably break various JS frameworks that want to own the DOM, so it's not really an option.

Generally speaking, your predicament falls under the warning in http://getbootstrap.com/javascript/#callout-modal-markup-placement . But specifically mentioning `position:fixed` (and IIRC, tables) in that warning as being problematic would be reasonable.

**Comment by dk8996** [comment]
@cvrebert Just strange that it worked in 3.3.1 without issues but then stopped working.

**Comment by mdo** [comment]
Made a brief docs mention in 1562a2d, but otherwise closing as a won't/can't fix.
