### ISSUE TITLE
V3.3.6 Modal displaying behind its own gray background.

### ISSUE THREAD

**Issue by dk8996** [twbs/bootstrap#20432]
Bug with modal that wasn't happening in version 3.3.1.  Here is a [jsfiddle](http://jsfiddle.net/cdahju1r/).  Looks like if the modal is in a div with fixed position then the modal will be behind the gray background -- again this didn't happen in 3.3.1.  

[Version 3.3.1 jsfiddle](http://jsfiddle.net/ru1d6k1q/)

[Version 3.3.5 jsfiddle](http://jsfiddle.net/cdahju1r/)

[Version 3.3.6 jsfoddle](http://jsfiddle.net/wqv6dapu/)

**Comment by twbs-lmvtfy** [comment]
Hi @dk8996!

You appear to have posted a live example (http://fiddle.jshell.net/uL8Lanfe/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 83, column 1: [E046](https://github.com/twbs/bootlint/wiki/E046): `.modal` elements must have a `tabindex` attribute.
* line 83, column 1: [E048](https://github.com/twbs/bootlint/wiki/E048): `.modal` must have a `role="dialog"` attribute.
* line 84, column 3: [E049](https://github.com/twbs/bootlint/wiki/E049): `.modal-dialog` must have a `role="document"` attribute.
* line 33, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0
* line 37, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Successor: #20433
