### ISSUE TITLE
Vertically separating col-* elements when they wrap

### ISSUE THREAD

**Issue by cervengoc** [twbs/bootstrap#20437]
In my current project in almost every situation when I use `col-*` `div`s which wrap into more lines I need a top margin so they don't stick together vertically.

I found that adding a `margin-top` to `col`s and adding an appropriate negative `margin-top` to the parent `row` will nicely solve this issue in a global way. (Some pseudo-code example below.)

```
.col-xs-* {
  margin-top: 15px;
}

.row {
  margin-top: -15px;
}
```

But I wonder why this is not applied by default, so I became suspicious about the possible drawbacks of these modifications. Also, I wonder why `padding` is applied to left and right of the cols instead of margin.  Could anyone explain what the current implementation's purpose is?

**Comment by cvrebert** [comment]
http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works is a decent explanation of how the non-flexbox grid works.

**Comment by cervengoc** [comment]
Thank you @cvrebert for pointing to this article, it was actually good to read, but I was aware of the system. My question targets a case which is not mentioned there. The case when there are more columns than a row could hold, so they wrap to more lines. In this case I (and I guess everybody else) need a vertical space between the lines of columns, and this is not implemented in bootstrap.

My example wanted to show a possible implementation for this vertical spacing. I was actually asking why this is not implemented, if there is a reason for it. Sorry if I wasn't clear enough.

**Comment by mdo** [comment]
Generally speaking, the grid rows should only have 12 columns, but if you do have more, we have options to support that (e.g., they'll wrap). However, we don't plan or include anything to encourage that behavior, hence the lack of this functionality for you. I'd recommend implementing your own solution as I have no plans to build this into Bootstrap itself.

**Comment by cervengoc** [comment]
@mdo thank you for the answer, however, there is something I don't understand in your points. Let's say we have a very simple case where we want to make use of responsiveness, so we want 4 columns on desktop and 2 on mobile. A simplified layout could be something like this.

```
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-3"> ... </div>
    <div class="col-xs-6 col-md-3"> ... </div>
    <div class="col-xs-6 col-md-3"> ... </div>
    <div class="col-xs-6 col-md-3"> ... </div>
  </div>
</div>
 ```

Here on mobile we have 4 columns, 2 in each visual row, so they wrap into 2 visual rows, and my problem is already visible.

What I want to say is that as I see it's not a rare situation, and it's not related to having more than 12 columns in a `.row`.

**Comment by cvrebert** [comment]
> and it's not related to having more than 12 columns in a `.row`.

It is related to that. You have four `.col-xs-6`es in a `.row`.
4*6 = 24
24 > 12

**Comment by cervengoc** [comment]
@cvrebert thanks for the clarification, indeed it is. Somehow I was thinking of 12 like 12 `div` elements.
