### ISSUE TITLE
What are the dependencies between Bootstrap's CSS, JavaScript and components?

### ISSUE THREAD

**Issue by hezjing** [twbs/bootstrap#20430]
Hi

Can we use Bootstrap CSS and the components without the JavaScript? It would be helpful if you can describe this in the documentation.

We need to use Bootstrap CSS in React application.

**Comment by wolfy1339** [comment]
On what version of Bootstrap?
Only certain components require the JavaScript, ex: navbar

**Comment by cvrebert** [comment]
> Can we use Bootstrap CSS and the components without the JavaScript?

Yes, you'll just lose any interactive features that out JavaScript added (e.g. opening+closing Modals and Collapses).

> We need to use Bootstrap CSS in React application.

Consider using something like https://github.com/react-bootstrap/react-bootstrap

**Comment by hezjing** [comment]
[react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) supports Bootstrap 3, but we want to try Bootstrap 4.0.0-alpha.3

**Comment by hezjing** [comment]
Instead of `npm install bootstrap` that will download the CSS and the components, would it be better if we can download them separately? For example,
`npm install bootstrap-css`
`npm install bootstrap-js`

**Comment by mdo** [comment]
We don't ship things separately at the moment (and we honestly have no plans to change that yet). Closing out since the question was answered and I don't see an immediate change to make to the docs that would universally clarify this.
