### ISSUE TITLE
Contextual list-group-item-* with child <a> element

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20443]
The themed `list-group-item-x` (-success, etc) right now required a contained `a` element to repeat the `list-group-item-x` class. This seems excessive. Shouldn't the css be declared as:

`list-group-item-success a` {

}

rather than:

`a.list-group-item-success` {

}

**Comment by cvrebert** [comment]
What version of Bootstrap are you referring to?

**Comment by bpierson** [comment]
V4 dev version from about a week ago.

**Comment by cvrebert** [comment]
Could you post an example?

It's declared as `a.list-group-item-success` because `<a>`s without any enclosing item parents are valid: http://v4-alpha.getbootstrap.com/components/list-group/#contextual-classes

**Comment by bpierson** [comment]
Sure, here's a sample. The first one, inside the `card` renders as expected because I added the class to the `a` element. The second just shows a standard blue link:

```
<div class="card">
    <div class="card-block"></div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-success"><a class="list-group-item-success" href="#">Cras justo odio</a></li>
        <li class="list-group-item">Dapibus ac facilisis in</li>
        <li class="list-group-item">Vestibulum at eros</li>
    </ul>
</div>

<ul class="list-group list-group-flush">
    <li class="list-group-item list-group-item-success"><a href="#">Cras justo odio</a></li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
</ul>
```
![contextual-list-item-link](https://cloud.githubusercontent.com/assets/6351149/17352606/17231b2e-58f5-11e6-941a-8b761089c728.png)

**Comment by bpierson** [comment]
I see what you're getting at. Moving people away from the `ul` to the `div` so that there is less markup. I think that makes sense. Sometimes when there is a better way to do something, it's good to push your users to the better way, and make the old way more painful. :)

**Comment by caepenna** [comment]
@bpierson IMO what you are saying makes a lot of sense and it seems like something to be improved in Bootstrap.

To me, it doesn't makes much sense (semantically) to name both a tag and its child with the same class, like this example:
```html
 <li class="list-group-item list-group-item-success"><a class="list-group-item-success" href="#">Cras justo odio</a></li>
```

I understand what @cvrebert said, that the <a> tag could be used without any enclosing item parent, but a nice way this could work would be just using the selector `.list-group-item-success` on Bootstrap (instead of `a.list-group-item-successs`), it would still work for <a> tags :)

**Comment by mdo** [comment]
No planned changes here to the list group states and links. If you want links within a list group item, or the list group item as a link, both are supported today.
