### ISSUE TITLE
Latest Release breaks Select Lists

### ISSUE THREAD

**Issue by adamreed90** [twbs/bootstrap#20440]
As you can see on the Offical Examples, options are no longer staying inside of the select list.

http://v4-alpha.getbootstrap.com/components/forms/#form-controls

http://puu.sh/qnaWl/1aac9954b3.png

http://puu.sh/qnaWv/c1e8ee27d2.png

**Comment by judetucker** [comment]
Thanks for pointing this out. This issue is a duplicate issue of #20384 

Next time make sure to search open issues.

**Comment by cvrebert** [comment]
@judetucker Thanks!
