### ISSUE TITLE
Slack badge on the README.md is broken.

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#20456]
The slack badge on the README.md is broken. The relevant upstream issue is rauchg/slackin#24. The slackin instance may need to be updated.

**Comment by mbrig-co** [comment]
![twbs](https://cloud.githubusercontent.com/assets/11582342/17391580/796cdf44-5a2c-11e6-9e5d-6aa86a739786.png)

But not for me!

**Comment by mdo** [comment]
Ah, yeah, I imagine this came up—given it's such an old bug—because I had to use a fork of Slackin to fix some Heroku deploy issues. Unsure if those issues have been resolved, but I can look into that soon.

**Comment by bardiharborow** [comment]
I'm not sure if you redeployed slackin, but it's fixed now. The alignment is still off, but I've fixed that in #20562.
