### ISSUE TITLE
dropdown-menu in navbar isn't full-width and obscures elements on mobile

### ISSUE THREAD

**Issue by os1r1s110** [twbs/bootstrap#20455]
When navigating mobile website, if we use a dropdown-menu in our navbar, then when expanding it, it hides other navbar items and doesn't expand to take full widht of the menu)

Here is an image in which this issue is apparent:

![navbar overflow content hidden](https://cloud.githubusercontent.com/assets/1885400/17382827/e2c2fc30-59a0-11e6-976b-58754918bb4a.jpg)

Here is a ply showing the same snippet but with a little modification to the css: http://codeply.com/go/4JLsdMHESx 

In this, I modified the dropdown-menu behavior when used inside a navbar that is collapsed and in sight. I know nesting should be avoided but I thought we wouldn't want to change dropdown-menu behavior if not used in this particular scenario... maybe there is a better alternative and if it is the case, I'm totally open to suggestions. 

`.collapse.in .dropdown-menu {
    position:relative;
    width:100%;
}`

Here is the result in case you don't want to open the ply: 
![fixed dropdown menu in navbar](https://cloud.githubusercontent.com/assets/1885400/17383059/faf505c2-59a1-11e6-9c81-c7d5e265d9d5.jpg)

Maybe we could make the dropdown-menu take the full page-width instead of respecting the padding but that's more of a design decision and I'll let you decide what would be better.

Operating system: Windows 10
Browsers: Chrome 52.0.2743.82, Edge 25.10586.0.0

**Comment by mevsme** [comment]
Drop down menus is navbar don't have any explanation and examples in documentation. Positioning works wrong, and puts pop-up menus at {left: 0px;} for all drop down buttons. Responsible features doesn't work too. 

Other navbar issues #20392 #20374

**Comment by mevsme** [comment]
Now I have this in Chrome
![alt](https://pp.vk.me/c604724/v604724332/4792/wxGNOBiFit8.jpg)
Because of this:
![alt](https://pp.vk.me/c604724/v604724332/479a/Uzzp_THyOyM.jpg)

**Comment by mdo** [comment]
Resolved in #19890.
