### ISSUE TITLE
Bootstrap 3.3.7 not published to Atmospherejs

### ISSUE THREAD

**Issue by frco9** [twbs/bootstrap#20450]
I can't update my bootstrap meteor package. It seems the last release (3.3.7) was not published to AtmosphereJS ?

**Comment by cvrebert** [comment]
Approximate duplicate of #20389. Same underlying cause.

**Comment by frco9** [comment]
Ok thanks ! 
Maybe the package.js should be removed from source, so that it would be more explicit that bootstrap is not anymore published on AtmosphereJS.
