### ISSUE TITLE
Invalid US-ASCII character "\xE2" in v4Alpha3.0

### ISSUE THREAD

**Issue by bijoyanupam** [twbs/bootstrap#20469]
In the recent release of v4.alpha3, I did face "Invalid US-ASCII character "\xE2"" issue. I think replacing '—' => '-' in scss/_tables.scss file would resolve the issue. Couldn't check all the files, but a check for such characters would be good. Please ignore, if we have already resolved in v4.Alpha3.1

**Comment by mdo** [comment]
Fixed in 935e0cc.
