### ISSUE TITLE
Hound warnings on JS test files

### ISSUE THREAD

**Issue by maxbeatty** [twbs/bootstrap#20466]
[I've opened a few PRs](https://github.com/twbs/bootstrap/pulls/maxbeatty) and each gets lots of comments from @houndci-bot because the [JS unit test files](https://github.com/twbs/bootstrap/tree/0416f761dddae04a1b4d3ce70afece518330ca4d/js/tests/unit) do not conform to [the ESLint settings](https://github.com/twbs/bootstrap/blob/0416f761dddae04a1b4d3ce70afece518330ca4d/js/.eslintrc.json). Here are few ways I've considered addressing this:
1. Ignore the test files similar to #20446. This is the least amount of work and will get other PRs passing and more likely to merge.
2. Fix the eslint issues in the test files, add a grunt task or npm script (#20332) to transpile the test files, and update the references in [`index.html`](https://github.com/twbs/bootstrap/blob/0416f761dddae04a1b4d3ce70afece518330ca4d/js/tests/index.html#L149-L159). This is obviously more work but would be more of a long term benefit.

I'm open to other ways to please @houndbot-ci when changing JS test files and willing to put in the work 😅

**Comment by bardiharborow** [comment]
@maxbeatty just an update on this. Once #21005 merges, Travis will lint tests correctly. Hound is still mad because of houndci/hound#889, but that's more annoying than show-stopping for now.

**Comment by mdo** [comment]
Closing out given latest comment from @bardiharborow. Holler if this needs to be re-opened to track anything else not already covered in another issue or PR <3.
