### ISSUE TITLE
v4.0.0-alpha.3.1 Release Date / NuGet Update

### ISSUE THREAD

**Issue by adamreed90** [twbs/bootstrap#20470]
I was wondering if you had an expected date for the push of release v4.0.0-alpha.3.1, and if you would be pushing this update to NuGet. The current release is not on NuGet.

**Comment by cvrebert** [comment]
The current release is on NuGet: https://www.nuget.org/packages/bootstrap/4.0.0-alpha3

**Comment by cvrebert** [comment]
> I was wondering if you had an expected date for the push of release v4.0.0-alpha.3.1

"Pretty soon"

**Comment by bardiharborow** [comment]
At the moment, it looks like [6 to 8 weeks](https://meta.stackexchange.com/a/19514).

**Comment by mdo** [comment]
Closing out as we'll be shipping it soon.
