### ISSUE TITLE
Tooltip won't show up on Labels

### ISSUE THREAD

**Issue by JacobGunther12** [twbs/bootstrap#20478]
Operating System: Coding on Windows, viewing on Macintosh (macOS Sierra)
Browser: Google Chrome (Latest)
Potential fixes: Unknown

I created a Label and tried to apply a Tooltip to it but it doesn't like to show up, here's my code:
`<span data-toggle="tooltip" data-placement="top" title="Tooltip on top" class="label label-default">Universal</span>`
This is in a table, path: .table > tbody > tr > th.
The Label element will show up but it seems like the Tooltip isn't even getting recognized at all. I made it so when I hover over the "tr" element, it shows the pointer cursor but I wouldn't think this would be a problem. I don't know of any solutions or fixes at the time. Thanks, Jacob.

**Comment by cvrebert** [comment]
What version of Bootstrap?

**Comment by judetucker** [comment]
I was unable to verify this as an issue. I suspect you are not properly initializing the JS. 

Here is an example use case: https://codepen.io/judetucker/pen/JKmggd 

This is based on v4-alpha.3. Not sure what version you are on. Hope this helps.

**Comment by JacobGunther12** [comment]
@cvrebert The lastest

**Comment by JacobGunther12** [comment]
@judetucker I am on the lastest, not 4 but 3.3.7 or something.
