### ISSUE TITLE
Custom.scss (custom variables)

### ISSUE THREAD

**Issue by masaanli** [twbs/bootstrap#20481]
**There is an custom.scss added where u can place the variables but then customized. But the problem here is, that this is a strange approach right, because normally you will use a reference to a node_modules file.

What i mean is, the custom.scss file is inside a node_modules, node_modules aren't checked in in Source Control / Repository.**

Is there any other way to, suggested way to work with your own variables file which isnt in the node_modules for example...

Future, is there a Gitter or Slack channel for Questions?

Bootstrap:
**4.0 Alpha 3**

**Comment by cvrebert** [comment]
See https://github.com/twbs/bootstrap/blob/master/README.md#community for links to IRC, Slack, etc.

**Comment by AMIT1122** [comment]
thanks

**Comment by mdo** [comment]
Closing out.

For folks who copy the Sass files verbatim out of our project, it works. For those who use dependency managers, it's less helpful.
