### ISSUE TITLE
V4 popover: Uncaught TypeError: f is not a function

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20488]
I think I've got everything in place: Tether before bootstrap.js, etc. Here is the element, not trying to do anything fancy...

```<button class="btn btn-secondary" data-content="This is the text of the popover." data-title="Hello World" data-toggle="popover" data-container="body" data-placement="right" title="Hello World">Click Me</button>```

I've tried with and without `data-title`, `data-container`, etc. Result is always the same.

**Comment by bpierson** [comment]
Looks like I had some JS that was out of order. Closing.

**Comment by bpierson** [comment]
The problem is with the bundling and minification of MVC. Feel free to close if this is not the place for this.

**Comment by cvrebert** [comment]
We are unable to provide assistance with backend frameworks, such as ASP MVC.
You can take such questions to StackOverflow, IRC, or Slack. See our README for links.
