### ISSUE TITLE
Cannot use other units than 'px' for $alert-padding variable

### ISSUE THREAD

**Issue by webmasterlv** [twbs/bootstrap#20485]
In v4 alpha3:

If trying to override $alert-padding with something like
`$alert-padding: 1rem`
The Sass compilation fails with
_Error: Incompatible units: 'px' and 'rem'._

Because in _alert.scss there's this
`padding-right: ($alert-padding + 20px);`

**Comment by bartekbart** [comment]
<img width="1440" alt="screen shot 2016-08-09 at 10 48 48 am" src="https://cloud.githubusercontent.com/assets/9088003/17511113/e8ba0338-5e21-11e6-9595-7b37bb20bd65.png">



THIS IS ONLY DEMO ONLY

**Comment by tschallacka** [comment]
$alert-padding: 2em;
    .foo {
       padding-right: calc( #{$alert-padding} + 20px  );
     } 

might be a nice solution.

**Comment by lucasgladding** [comment]
Is there a reason this can't be done the same as the close button on modals? Removing the styling for .alert-dismissible and offsetting the top margin gives the same appearance for single lines.
```
.alert .close {
margin-top: -2px;
}
```
For multiple lines, text could appear below the button, which is the only reason I can think of for the alternative approach.

**Comment by mdo** [comment]
Addressed with #20625.

**Comment by bartekbart** [comment]
![log3](https://cloud.githubusercontent.com/assets/9088003/18716834/7784d656-801e-11e6-91a5-ad38699e0af
