### ISSUE TITLE
import "bootstrap" is not working

### ISSUE THREAD

**Issue by kamalpatel125** [twbs/bootstrap#20491]
Hi,

import "bootstrap" is not working and i think because in "package.json" - "main": "./dist/js/npm" but there is no npm folder exist..

For now can use "import 'bootstrap/dist/js/bootstrap';"  but it's nice to have "import 'bootstrap;" So could you fix this please ? 

Thanks, 

Kamal Patel.

**Comment by pkozlowski-opensource** [comment]
Duplicate of #20383

**Comment by cvrebert** [comment]
Please search more for existing issues in the future. Thanks.
