### ISSUE TITLE
Bootstrap4的中文版文档何时能出

### ISSUE THREAD

**Issue by iamwelk** [twbs/bootstrap#20490]
1. 中文版文档何时能出？
2. 感觉有些例子不够详细，是否能再细化一下？

**Comment by patrickhlauke** [comment]
we don't maintain the translated versions of the documentation...we just link to them from our end. i'd suggest trying to get in touch with whoever is maintaining the chinese version of the docs (should ideally be identified somewhere there, perhaps in the footer?)

**Comment by iamwelk** [comment]
Thank you~ 
You can read Chinese!!! That's amazing!

**Comment by patrickhlauke** [comment]
> You can read Chinese!!! That's amazing!

well, in fairness, google translate does ;)
