### ISSUE TITLE
Flexbug 9 can affect the grid system when flexbox is enabled

### ISSUE THREAD

**Issue by DerekFoulk** [twbs/bootstrap#20498]
Hi guys,

The issue I have discovered is that the grid layout gets screwed up when `fieldset.row` is used instead of `div.row` when flexbox is enabled.

See the examples found here: http://v4-alpha.getbootstrap.com/components/forms/

If you scroll down to the 'Using the Grid' section, you will notice the following example:

    <div class="container">
      <form>
        ...
        <fieldset class="form-group row">
          <legend class="col-form-legend col-sm-2">Radios</legend>
          <div class="col-sm-10">
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
                Option one is this and that&mdash;be sure to include why it's great
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
                Option two can be something else and selecting it will deselect option one
              </label>
            </div>
            <div class="form-check disabled">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios3" value="option3" disabled>
                Option three is disabled
              </label>
            </div>
          </div>
        </fieldset>
        ...
      </form>
    </div>

I modified the example to suit our form:

    <div class="container">
        <form>
            ...
            <fieldset class="row">
                <div class="form-group col-xs-12 col-lg-6 col-xl-4">
                    <label for="FirstName">First name:</label>
                    <input class="form-control" id="FirstName" name="FirstName" type="text">
                </div>
                <div class="form-group col-xs-12 col-lg-6 col-xl-4">
                    <label for="LastName">Last name:</label>
                    <input class="form-control" id="LastName" name="LastName" type="text">
                </div>
            </fieldset>
            ...
        </form>
    </div>

The above markup works just fine- until you enable flexbox in Bootstrap. If you change the `.row` element to `<div class="row">`, then the markup works fine with or without flexbox enabled.

I haven't yet discovered why using `fieldset.row` with flexbox causes the grid to breakdown, but I will post here as soon as I determine the cause.

- Operating system and version (Windows 10)
- Browser and version (Chrome 52.0.2743.82 m)
- JS Bin: http://jsbin.com/naqapizepa/edit?html,output

**Comment by cvrebert** [comment]
This is a bug in the browsers themselves which we cannot work around.
See https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers
It's supposed to be fixed (for fieldset) in Chrome 54 and Firefox 46, but Edge and Safari are still buggy.
It's probably worth mentioning Flexbug 9 somewhere in our docs.

**Comment by DerekFoulk** [comment]
Hi Chris,

Thank you for the quick response! So, has it been determined that there is no way to make these elements work as grid rows with flexbox enabled? Or is there some CSS that can be applied to the `<fieldset>` element to make it play nice with our grid?

**Comment by cvrebert** [comment]
Yes, as I said, this is a bug in the browsers themselves which we cannot work around.

**Comment by DerekFoulk** [comment]
Good deal. Thank you Chris!
