### ISSUE TITLE
Combining pills and collapse/accordion

### ISSUE THREAD

**Issue by slacto** [twbs/bootstrap#20492]
Since pills are not very responsive, a combination of pills and accordion/collapse is often useful (where pills are used on desktop an up and accordion/collapse are used on mobile). Unfortunately they share the same class ‘in’ which creates some unwanted behavior when resizing (selecting a new tab will remove ‘in’ from other tab panes and hereby unintendedly collapsing them when resizing). Please consider using unique class names for each JavaScript plugin to make combinations easier.

**Comment by cvrebert** [comment]
> where pills are used on desktop an up and accordion/collapse are used on mobile

We've had requests for such a widget in the past, but they've been rejected by @mdo.

Short of properly adding such a widget, trying to accommodate (in upstream) "frankensteining" widgets together like you're talking about doesn't seem feasible, IMHO.

> Please consider using unique class names for each JavaScript plugin to make combinations easier.

Actually we've had requests for the exact opposite policy, for different reasons: #19344

**Comment by mdo** [comment]
No plans to add this feature in v4. Thanks though!
