### ISSUE TITLE
White title and text when expecting black

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#20496]
When creating an row with bg-inverse and then inside it we create a regular card component the title changes to white even if the card default behavior is white bg with black text.

DEMO : http://codepen.io/igcorreia/pen/KrbgNm

Boostrap: v4-alpha

Browser: Chrome 54

```
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 sidebar bg-info p-t-1 p-l-1">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-block">
            <h3 class="card-title">Special title treatment</h3>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 main p-t-1 p-l-1">
      123
    </div>
    <div class="col-md-3 options bg-inverse p-t-1 p-l-1">
      123
    </div>
  </div>
</div>
```

**Comment by RyanZim** [comment]
@Igcorreia Your problem has nothing to do with `bg-inverse`. The `bg-info` class is causing the problem. Here is a simplified pen demonstrating the problem: http://codepen.io/anon/pen/KrbaaK.

Something should be fixed with the card component to make sure `color` is set to the default value (that can be changed with `.card-inverse`).

**Comment by RyanZim** [comment]
BTW, if https://github.com/twbs/bootstrap/pull/19847 gets merged, that could be a workaround.

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/issues/20496#issuecomment-238946972.

**Comment by RyanZim** [comment]
@mdo I still think we should consider having `.card` set `color`. This is sort of unexpected behavior IMHO.
