### ISSUE TITLE
position:fixed focused button flickers on Edge+IE when scrolling

### ISSUE THREAD

**Issue by os1r1s110** [twbs/bootstrap#20507]
Okay so I looked through past issues and I did find quite a few issues on affix plugin and scrolling glitches but none seems to fit this case, so if I'm wrong thanks for pointing the solution to me.

The issue is only happening on IE and Edge. When clicking on a button, it correctly activates the said button when when action is done, focus remains on the button and if we scroll on a page with these browsers, the button then starts flickering/jumping. 

You can see it with this little ply by opening with IE/Edge and simply clicking the button and scrolling afterwards.

http://codeply.com/go/i7UQ86nqLr

Operating system: Windows 10
Browsers: Chrome 52.0.2743.82, Edge 25.10586.0.0 and IE 11.545.10586.0

**Comment by os1r1s110** [comment]
Tried the "backface-visibility: hidden" trick but it didn't work.

**Comment by os1r1s110** [comment]
Quick observation, if I use the same button but I put it in a <div> instead of a <button> tag, the problem goes away, so the issue really is related to the use of <button> tag in IE / Edge... 

Maybe it's not related to Bootstrap I'll try to dig deeper to see if it's a combination of styles from btn or btn-* along with <button> from user agent.

**Comment by cvrebert** [comment]
Filed MS Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8770398/

**Comment by Tix1981** [comment]
I solved this trough css:

a:focus {outline:none}

**Comment by cvrebert** [comment]
@Tix1981 That's not a good fix. See http://www.outlinenone.com
