### ISSUE TITLE
CSS of v4.0.0-alpha.3 has validation errors

### ISSUE THREAD

**Issue by igll** [twbs/bootstrap#20516]
Hi! 
Congrats for building a great alpha.3! A lot of invested work with good feature

CSS code of V4.0.0-alpha.3 (at least the examples') has some apparently easy-to-solve validation errors.

These kind of errors could generate eventually difficult-to-debug side effects.

You can see them here: [https://jigsaw.w3.org/css-validator/validator?uri=http://v4-alpha.getbootstrap.com/examples/jumbotron/&profile=css3&usermedium=all&warning=2&vextwarning=&lang=en]

**Comment by cvrebert** [comment]
See http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#validators

**Comment by igll** [comment]
Thank you!
