### ISSUE TITLE
IE10 viewport hack - JSHint complains about 3 missing semicolon

### ISSUE THREAD

**Issue by AvexMedia** [twbs/bootstrap#20512]
JSHint complains about 3 missing semicolon in the the IE10 viewport hack:

```
if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
  var msViewportStyle = document.createElement('style')
  msViewportStyle.appendChild(
    document.createTextNode(
      '@-ms-viewport{width:auto!important}'
    )
  )
  document.querySelector('head').appendChild(msViewportStyle)
} 
```

Should this warning be ignored or the 3 semicolon be added?

**Comment by cvrebert** [comment]
Bootstrap's current house style is to not use semicolons in client-side JavaScript.
Feel free to add semicolons when copying the code, but we're not going to modify the snippet in our documentation.
