### ISSUE TITLE
Add Sass unit tests

### ISSUE THREAD

**Issue by airandfingers** [twbs/bootstrap#20521]
Sass unit tests via [True](http://oddbird.net/true) are useful for validating Sass functions and mixins, while linting tools like [scss-lint](https://github.com/brigade/scss-lint) enforce style guidelines.

**Comment by cvrebert** [comment]
> while linting tools like scss-lint enforce style guidelines.

We already have that 😄 : 
https://github.com/twbs/bootstrap/blob/3a0fed1590c8abc166bb8ed2c3853396dbe3801d/Gruntfile.js#L152

**Comment by airandfingers** [comment]
Whoops, my mistake! Thanks for the correction.

**Comment by xzyfer** [comment]
👋  Hi I'm the Node Sass and LibSass. We would love this.

As part of our release process we manually verify that the HEAD of this repo compiles correctly to prevent regressions. A automated test suite would make our lives easier and lower the risk of serious regressions.

**Comment by mdo** [comment]
Closing as stale. If someone on the team, or a contributor, wants to revive this and stub out a starter PR, I'd be happy to review though!
