### ISSUE TITLE
Fixed-top Navbar contents shift to right if body min-height css rule is removed

### ISSUE THREAD

**Issue by samantp** [twbs/bootstrap#20532]
Hi,

In the example given in the Bootstrap 3.3.7 download for the fixed-top navbar at: http://getbootstrap.com/examples/navbar-fixed-top/ , noticed that if the "min-height: 2000px" in the navbar-fixed-top.css is removed, the entire navbar contents shift a few pixels to the right.

Same issue is noticed if the 2000px is reduced to a lower value like 100px or so, as long as this number is well below the height of the screen in pixels.

Noticed on both Chrome (Version 52.0.2743.116, 64-bit) and Firefox (48.0) on Ubuntu 16. Uploaded the screenshots with the original, and then with the min-height removed.

**Comment by mdo** [comment]
Fixed content will shift if there is a scrollbar present—no way around it I'm afraid unless you want to calculate scrollbar widths and offset it somehow (or hide the scrollbar).
