### ISSUE TITLE
CII best practices badge for bootstrap

### ISSUE THREAD

**Issue by david-a-wheeler** [twbs/bootstrap#20531]
I'd like to convince Bootstrap to get a “best practices” badge from the Linux Foundation Core Infrastructure Initiative (CII).  I’m the technical lead of the badging project.  Someone from the bootstrap project simply needs to go here and click on “Get Your Badge Now!”:
>  https://bestpractices.coreinfrastructure.org/

It’s basically a web form, and it shouldn’t take more than hour.  We can help you (if you’d like) once you get started.  I’d be happy to answer questions, too.  Projects with the badge include Node.js, the Linux kernel, curl, and OWASP ZAP.

Why should you add it? Why is it important to Bootstrap?  Here are two reasons that come to mind:
* Presuming that you already meet the criteria for a badge, this will help potential users know that you are following best practices and as a result are more likely to produce higher-quality secure software.
* If you don't meet one, I'm sure Bootstrap would want to know about that, so it can then decide what (if anything) it wants to do about that.

For example, here is Node.js's badge:
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/29/badge)](https://bestpractices.coreinfrastructure.org/projects/29) 

Thanks!

**Comment by cvrebert** [comment]
X-Ref: https://github.com/d3/d3/issues/2943

**Comment by david-a-wheeler** [comment]
X-Ref: https://github.com/nodejs/node/commit/fea3ba4f4b19044cac75b90d356c39637f7d7b02

**Comment by mdo** [comment]
Thanks, but passing for now.
