### ISSUE TITLE
Issue with .btn-group in td.text-nowrap

### ISSUE THREAD

**Issue by cervengoc** [twbs/bootstrap#20530]
Please check this demo to reproduce the issue: http://www.bootply.com/wWM2a9R8Mt#

The unexpected horizontal overflow seems to be caused by the `float: left` of the buttons in the `btn-group`. For me it was unexpected that `btn-group` contains floating elements. ~~If floating is really needed, it would be good to include the `clearfix` in `btn-group`s.~~ It seems like adding the `clearfix` class to `btn-group` doesn't solve the issue in itself.

How could I solve this table cell layout issue?

Is there any way to avoid floats in `btn-gruop`s in future versions? I mean for example `input-group`s are implemented without floats, so `btn-group`s might have an alternative implmentation too.

**Comment by twbs-lmvtfy** [comment]
Hi @cervengoc!

You appear to have posted a live example (http://s.bootply.com/render/wWM2a9R8Mt), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 5, column 9 thru column 30: A document must not include both a ```` meta ```` element with an ```` http-equiv ```` attribute whose value is ```` content-type ````, and a ```` meta ```` element with a ```` charset ```` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
This will be fixed by #21394 with the move to flexbox based button groups. https://jsbin.com/zekera/edit?css,output
