### ISSUE TITLE
Form validation labels not coloring

### ISSUE THREAD

**Issue by hiddewie** [twbs/bootstrap#20535]
### Required behaviour:

The labels of a form element with a validation class, like `has-danger`, are highlighted in the validation colour, like red.

### Observed behaviour:

There is no colour change. It seems `.has-danger .col-form-label` has no associated styles.

Screenshot: 
![2](https://cloud.githubusercontent.com/assets/1073881/17731301/fd0cdabc-646c-11e6-9352-335d425cadf2.PNG)

### Details:

BS 4: Alpha 3
OS: Windows 10, x64 (10.0.10586 Build 10586)
Browser: Chrome 52.0.2743.116 m, Firefox 48.0, Microsoft Edge 25.10586.0.0

CodePen: http://codepen.io/anon/pen/XKGVaR

**Comment by twbs-lmvtfy** [comment]
Hi @hiddewie!

You appear to have posted a live example (http://codepen.io/anon/pen/XKGVaR.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 6: Stray start tag ```` html ````.
* line 10, column 1 thru column 6: Stray start tag ```` head ````.
* line 11, column 3 thru column 26: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 11, column 3 thru column 26: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 11, column 3 thru column 26: A document must not include more than one ```` meta ```` element with a ```` charset ```` attribute.
* line 12, column 3 thru column 9: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 15, column 3 thru column 9: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 20, column 1 thru column 7: Stray end tag ```` head ````.
* line 22, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 41, column 109 thru column 117: Element ```` option ```` without attribute ```` label ```` must not be empty.
* line 92, column 139 thru column 147: Element ```` option ```` without attribute ```` label ```` must not be empty.
* line 95, column 34 thru column 42: Element ```` option ```` without attribute ```` label ```` must not be empty.
* line 127, column 112 thru column 120: Element ```` option ```` without attribute ```` label ```` must not be empty.
* line 143, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Apply `.form-control-label` to the label and you'll be set. I missed this in our docs, but it's coming in #20872.

**Comment by hiddewie** [comment]
Thank you!
