### ISSUE TITLE
V4 documentation still mention pull-right and pull-left classes

### ISSUE THREAD

**Issue by arnaudruffin** [twbs/bootstrap#20538]
The current v4 documentation on v4-dev branch states that 

> Two similar non-responsive mixins (pull-left and pull-right) are also available.

(see https://github.com/twbs/bootstrap/blob/v4-dev/docs/components/utilities.md) for instance)

I understand that the absence of `pull-right` and `pull-left` classes in V4 is intentional (see #20286 for instance). 

So maybe the documentation should be fixed?

**Comment by cvrebert** [comment]
> Two similar non-responsive ***mixins*** (pull-left and pull-right) are also available.

Sass mixins != CSS classes.
The classes were removed. The mixins weren't.

I suppose we could rephrase that sentence to "Sass mixins" to help emphasize the distinction.

**Comment by arnaudruffin** [comment]
Ok, my bad 😄 ! Thanks for the clarification

**Comment by mdo** [comment]
Fixed in c2b8012.
