### ISSUE TITLE
Flexbox without Sass

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#20536]
From: http://v4-alpha.getbootstrap.com/getting-started/flexbox/

> Alternatively, if you don’t need the source Sass files, you may swap the default Bootstrap compiled CSS with the compiled flexbox variation. Head to the download page for more information.

Where can i find the compiled CSS? I can't see any information in the download page.
Thanks

**Comment by troydildine** [comment]
The best way to download pre-compiled CSS is to visit [this page](http://v4-alpha.getbootstrap.com/getting-started/download/). There is an option on this page to download the source code in ZIP format. This zip file contains pre-compiled CSS and JavaScript in the 'dist' folder.

**Comment by yasinkocak** [comment]
Compiled CSS is in "dist" folder

**Comment by AlessandroVecchi** [comment]
CSS in the dist folder doesn't contain any "flex" class

**Comment by cyberwombat** [comment]
Here https://gist.github.com/cyberwombat/70a4edc624c84b0a6d25ac793b852213

**Comment by stanleyxu2005** [comment]
@cyberwombat Thanks. This is the thing we want to get without downloading and mastering the SASS compiler stuff.

**Comment by bardiharborow** [comment]
It would be extremely helpful if Bootstrap would provide a `bootstrap.flex.min.css` download, if only so it would be pushed to CDNJS. I'll write a PR if there is a chance of it being included.

**Comment by bardiharborow** [comment]
Duplicate of #18292.

**Comment by mdo** [comment]
Closing as dupe.
