### ISSUE TITLE
Centered block

### ISSUE THREAD

**Issue by leonardo1024** [twbs/bootstrap#20546]
I think, it would be good to add in .center-block class float: none; style

For ex:
.center-block {
    display: block;
    margin-right: auto;
    margin-left: auto;
**float:none;**
}

becouse when I want to show smaller centered box like
`<div class="col-sm-4 center-block">
I'm small centered box
</div>`
it will not be centered without float:none

**Comment by Drakenhart** [comment]
Why not use _margin: auto 0;_  instead of declaring two margins?

**Comment by mdo** [comment]
If you're centering grid columns, use the `.offset-*` modifiers instead. For centering all other content, use the margin utils on a a block level element that's not part of the grid.
