### ISSUE TITLE
Seems the sr-only-focusable class does not appear to be working

### ISSUE THREAD

**Issue by DavidMacDonald** [twbs/bootstrap#20547]
See issue #13457 it introduced the sr-only-focusable class but it doesn't appear to be working.

See the link on this test page.
http://davidmacd.com/testmenu.html
The link should be invisible until it receives focus.

**Comment by patrickhlauke** [comment]
Please read the relevant documentation http://getbootstrap.com/css/#helper-classes-screen-readers

> Combine `.sr-only` with `.sr-only-focusable` [...]

so you need both classnames in there
