### ISSUE TITLE
Text ribbons break if line-span > 1 and text = centered

### ISSUE THREAD

**Issue by loadsfaster** [twbs/bootstrap#20554]
If the text in a text ribbons is text-centred and the text is long enough that it breaks into more than one line then the text ribbons break badly. It's not much of a problem on larger screens but it only take ~3 longish words to cause a line-break on small screens.

**Comment by mdo** [comment]
We don't have ribbons in Bootstrap—if this is about an official Bootstrap Theme, please email `themes@getbootstrap.com` for support.

**Comment by loadsfaster** [comment]
Thanks @mdo. I emailed GB support over two months ago but there was no reply. @fat just followed up via Twitter though so thanks.
