### ISSUE TITLE
shown.bs.collapsible event is not working after an Ajax call

### ISSUE THREAD

**Issue by MounicaChette** [twbs/bootstrap#20558]
I am doing an AJAX call in jquery to dynamically generate html and binding it to my accordian. Before the ajax call, the shown.bs.collapsible event is triggered. But after ajax call, this event is not being trigger. Please help me.

**Comment by cvrebert** [comment]
Please post a JS Bin or other live example which demonstrates the problem, per the [issue template](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md).

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team
