### ISSUE TITLE
Collapse on tr results on tr losing width

### ISSUE THREAD

**Issue by roybrener** [twbs/bootstrap#20566]
Before opening an issue:

Using **bootstrap 4-alpha 3**
*Example*: [https://github.com/roybrener/tableCollapseBug](url) 

I've created a simple table with 2 rows. The 2nd row is hidden using `class="collapse"`. After clicking the first row
The second row is being showed but then losses It's width- the FIrst column of row 1 takes much 
more space and pushes the rest of the columns and the second row gets the width of only the first column.

When removing the "class=collapse" then the row cover the full colSpan

Bootstrap 3 (3.3.7) Works as expected

tested on windows 10- Chrome 53, IE 11.545 and edge, All showing the same behavior

**Comment by mxviteri** [comment]
The tr and trbody tags were commented out within the .collapse class. Additionally, when uncommented, they generated incorrect css when compiled. Restructed. Compared generated css with css from 3.3.7
