### ISSUE TITLE
Webkit issue : cannot load glyphicons, does not render corner radius, drop shadow, RGBA

### ISSUE THREAD

**Issue by goldesigner** [twbs/bootstrap#20561]
To reproduce the issue, install Linux 3.14.60 and Webkit-r61967. 

We pulled in a custom bootstrap build earlier last week – we’re having issues with compatibility. Border-radius/-webkit-border-radius, box-shadow/-webkit-box-shadow styles won’t load, as well as some various opacity strategies. It also looks like trying to pull in glyphicons is failing as well. 

Can you please verify if this version of Webkit has compatibility issues with Bootstrap?

**Comment by cvrebert** [comment]
I assume you are using Bootstrap v3.3.7?

**Comment by mdo** [comment]
This seems like a v3 thing given the Glyphicons mention, and likely not one for us to address given how broad the problems are. Please do holler though if it's something on our end and we can re-open this issue <3.

**Comment by goldesigner** [comment]
@cvrebert, sorry for not responding. Was offline for a bit. It was a custom Bootstrap build v3.3.7.
@mdo, I concur. It's an industrial automation interface, so we just reverted to simpler styling.
