### ISSUE TITLE
The state 'loading' can't reset after the first time successed.

### ISSUE THREAD

**Issue by vrbvillor** [twbs/bootstrap#20564]
https://jsfiddle.net/zLxn6uo3/

```html
<button id="fat-btn" class="btn btn-primary" data-loading-text="Loading..." 
   	type="button"> Click to load.
</button>
```
```javascript
	$(function() { 
		$(".btn").click(function(){
			$(this).button('loading').delay(1000).queue(function() {
				$(this).button('reset');
			});        
		});
	});  
```

The first click can reset to primary state.  But the second time, it won't reset, staying at the 'loading' state.

**Comment by bardiharborow** [comment]
When you [.queue](https://api.jquery.com/queue/) a function with jQuery, you need to ensure that it calls it's callback once it has completed. If you don't call the callback, your function will not be run the second time around because jQuery still thinks it is waiting for the first to complete.

```javascript
$(function() {
    $(".btn").click(function() {
        $(this).button('loading').delay(1000).queue(function(next) {
            $(this).button('reset');
            next();
         });
    });
});  
```

**Comment by patrickhlauke** [comment]
working example of what @bardiharborow said https://jsfiddle.net/zLxn6uo3/13/ ... closing, as not a BS issue as such

**Comment by vrbvillor** [comment]
Thanks a lot. I've got it .
