### ISSUE TITLE
Bootstrap 4 alpha 3 for meteor : how to set flexbox enabled ?  

### ISSUE THREAD

**Issue by philohelp** [twbs/bootstrap#20579]
I installed the package and I can see that flexbox is not enabled by default. How could I set it within the meteor package ? Thanks for your help.

**Comment by cvrebert** [comment]
You would compile the Sass with `$enable-flex` set to `true`.
For advice on how to do that in Meteor, please ask on a Meteor-specific forum.
Thanks.
