### ISSUE TITLE
Docs are contradictory as to which classes should be used and when and how (in what combinations, etc) for stacked and inlined checkboxes/radios markup

### ISSUE THREAD

**Issue by notmessenger** [twbs/bootstrap#20578]
I asked this question in https://github.com/twbs/bootstrap/issues/20403#issuecomment-241100345 but am making it its own issue for more visibility.

The chart at the bottom of the http://v4-alpha.getbootstrap.com/components/forms/#form-controls section lists these classes as being applicable to radio and checkbox controls:

* `.radio`
* `.radio-inline`
* `.checkbox`
* `.checkbox-inline`

The only such example though I see of these classes being used is in this code example within the same section:

```
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
```

The use of these classes seems to be contradicted (maybe?) in http://v4-alpha.getbootstrap.com/components/forms/#inline which uses a different set of classes for the inline or non-inline display of these controls.

Which classes should be used and when and how (in what combinations, etc)?

**Comment by mdo** [comment]
Fixed by #20629.
