### ISSUE TITLE
.tab('show') event leaves the content of the default tab visible

### ISSUE THREAD

**Issue by markau** [twbs/bootstrap#20575]
[Js Bin example](http://jsbin.com/hayunaxehe/edit?html,js,output)

The content of the Home tab should be hidden on page load, with only the content of the Profile tab visible.

Clicking through the tabs ensures the expected result.

**Comment by patrickhlauke** [comment]
to activate a tab you need to target the link/tab itself, not the related tab panel. see http://getbootstrap.com/javascript/#tabs-usage

**Comment by markau** [comment]
Ahh yes, that works perfectly. Thanks Patrick.
