### ISSUE TITLE
Travis builds are failing.

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#20589]
Travis builds are failing with: `Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
section: 'ffi'`.

The [last change](https://github.com/twbs/bootstrap/commit/0339272f55c5a9b27b4a18599ef9f96e451481c8) to `GEMFILE.lock` was on July 7.

**Comment by bardiharborow** [comment]
I'm not sure what is going on, but it's very intermittent so I'm closing until I'm sure there is a problem.

**Comment by bardiharborow** [comment]
This is definitely still happening.

**Comment by n054** [comment]
@bardiharborow running this through Travis-ci locally, this pull request performed out on line#301: your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES.
 Line#302: section: 'ffi'
