### ISSUE TITLE
consider adding .form-control-condensed

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20581]
In addition to `form-control-sm` and `form-control-lg`, it would be nice to have an `form-control-condensed` which could be used alone or in combination with small and large, to cut down on top and bottom padding.

**Comment by cvrebert** [comment]
Alternatively, perhaps just use the .p-* utility classes.

**Comment by mdo** [comment]
Puntin—utilities or custom styles are great for this use case.
