### ISSUE TITLE
Layout of Labels for Checkboxes Changes When They Contain Other Tags

### ISSUE THREAD

**Issue by ikellenberger** [twbs/bootstrap#20594]
Regular layout:
`<label class="form-check-inline"><input class="form-check-input" type="checkbox" id="inputCriteria1" name="checkCriteria1" value="yes"> Yes, I want!</label>`

Checkboxes get positioned too far to the left and too high when label contains other tags:
`<label class="form-check-inline"><input class="form-check-input" type="checkbox" id="inputCriteria2" name="checkCriteria2" value="yes"> Yes, it's me: <a href="mailto:john@doe.com">john@doe.com</a></label>` 
or
`<label class="form-check-inline"><input class="form-check-input" type="checkbox" id="inputCriteria3" name="checkCriteria2" value="yes"> Yes, I <em>really</em> want it!</label>`

Same behaviour for Microsoft Edge, Internet Explorer 11, Mozilla Firefox 47 or Google Chrome 52.

See [JSFiddle](https://jsfiddle.net/noeldi/wdo30w6v/). 
The last example in the fiddle is more or less directly copied from [Bootstrap Documentation](http://v4-alpha.getbootstrap.com/components/forms/#inline).

**Comment by ikellenberger** [comment]
This might be somewhat related to #20271.

**Comment by mdo** [comment]
This appears resolved in latest v4-dev.
