### ISSUE TITLE
v3.3.7 fonts couldn't be decoded

### ISSUE THREAD

**Issue by dankuer** [twbs/bootstrap#20595]
## Hi there!
When i use bootstrap.css(**v3.3.7**),i found that the fonts couldn't be decoded.(via chrome,IE).That is to say ,when i use class in span (like below):
```html
<span class="glyphicon glyphicon-chevron-right"></span>
```
I found nothing (and there suppose to be an icon just as i wish ),and the console of chrome just show as follow:"fail to decoded downloaded font".
To fix that ,i download bootstrap(**v3.3.5**) ,and find problem solved.
So ,pls check out if the fonts in **v3.3.7** have some problems?
Best regards

**Comment by cvrebert** [comment]
Unable to reproduce. Perhaps your web server is configured incorrectly?
For further assistance, please try StackOverflow, IRC, or Slack:
https://github.com/twbs/bootstrap/blob/master/README.md#community
