### ISSUE TITLE
Bootstrap type.less file over rides custom CSS

### ISSUE THREAD

**Issue by DavidMacDonald** [twbs/bootstrap#20598]
I hope version 4 SASS typography CSS file doesn't over ride custom CSS implemented by author.

**Comment by bardiharborow** [comment]
Your question is somewhat unclear. Cascading Style Sheets, by definition, override CSS included earlier in the document. To ensure that your custom CSS is not overridden you need to move Bootstrap before your custom CSS.

**Comment by cvrebert** [comment]
Yeah, this is the nature of CSS. There's no notion of precedence other than selector specificity.
If you don't like [`_type.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_type.scss), then your options are to modify it, delete it, or override its styles in your own CSS.

**Comment by cvrebert** [comment]
Selector specificity also matters, not just ordering.

**Comment by andre-koch** [comment]
@cvrebert could you be more specific please. what do you mean?

**Comment by lakshmankotipalli** [comment]
I changed my code to the below in angular.json

```
"styles": [
              "./node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles/main.scss"
            ]
```

And this works, I am able to override bootstrap styles with main.scss now.
