### ISSUE TITLE
modal displaying under backdrop on iPhone

### ISSUE THREAD

**Issue by dracula92107** [twbs/bootstrap#20592]
Hi,

I have a problem with modal on Iphone. I use Bootstrap v3.2.0
On Iphone, when I open a modal, it display under back-drop. I researched in many topic but no working.
This problem only occur on Iphone, isn't occur on PC or Android devices.

Please help.
Sorry if I post a duplicate issue.

**Comment by cvrebert** [comment]
Please upgrade to Bootstrap v3.3.7.
Also, you will need to post a JS Bin or other live example that demonstrates the problem, per the [issue tempate.](https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md)

**Comment by dracula92107** [comment]
Hi @cvrebert 
I'm sorry, maybe my mistake. Although I haven't found the cause yet, but it's seem only occur on my project. Please remove this issue.
I'm so sorry for this inconvenient.
Thanks.

**Comment by dracula92107** [comment]
![image](https://cloud.githubusercontent.com/assets/9784920/18081845/677af344-6ec6-11e6-846e-7b5b79bc9914.png)

**Comment by dracula92107** [comment]
Hi @cvrebert,

I just found the root cause of my issue.
I use: `-webkit-overflow-scrolling: touch` in my code.
Is this similar to #17695 ?

**Comment by cvrebert** [comment]
Quite possible. (Though I haven't heard of webkit-overflow-scrolling affecting backdrop placement before, but clearly it's a bug-prone property.)
