### ISSUE TITLE
Alternate media-queries for selected col's (row)

### ISSUE THREAD

**Issue by lifecom** [twbs/bootstrap#20599]
Now columns width calculated depend of window size (**lg, md, sm**) - media query breakpoints.
I propose to add option for column width, dependent of size any html-element (no only window size).

I think way to this - via js: specify name of html-element (by default - window size).

It's will be like **universal** media queries.

For example:
```
<div class="row">
    <div class="one-div col-md-6 row">
        <div class="row" data-media-query-element="onediv"> // now child col's width calculate dependent of onedive size
            <div class="col-md-6"></div> // 50%, then min-width of one-div (no window width) is: 992px
            <div class="col-md-6"></div>
        </div>
    <div class="sec-dev col-md-6"></div>
</div>
```
But I do not know whether it is possible to implement, because media queries - it is a css-function...

**Comment by cvrebert** [comment]
Sounds like you want Element Queries: https://www.sitepoint.com/beyond-media-queries-time-get-elemental/
Something that complex and general is outside of Bootstrap's scope.
As linked in that article, there are some existing libraries you can use which try to implement it.
