### ISSUE TITLE
.dropdown inside .input-group-addon

### ISSUE THREAD

**Issue by tomlutzenberger** [twbs/bootstrap#20606]
I would like to request official support for `.dropdown` inside of `.input-group-addon`.
Compared with a `select` (#20527) we would have the advantage that the content can be styled as needed. 
Browser support looks pretty good. Yet, I tested on 3 OS' / 11 Browsers; more to come.

I implemented this in a prototype yesterday, so I can open a PR (but not sure where to put the documentation). It looked like this:

![dropdown-in-input-addon](https://cloud.githubusercontent.com/assets/5536910/18161806/d5c78c04-7033-11e6-8c9d-7e774519f76e.png)

**Comment by cvrebert** [comment]
Don't we already support that?:
http://v4-alpha.getbootstrap.com/components/input-group/#buttons-with-dropdowns

**Comment by tomlutzenberger** [comment]
Oh.... Seems like I overlooked that.
In that case you can close the issue.
