### ISSUE TITLE
Docs are contradictory for radio/checkbox classes

### ISSUE THREAD

**Issue by TheSharpieOne** [twbs/bootstrap#20608]
Slightly different from #20578 which is specific to inline and stacking, this ticket hopes to address the `.form-check` vs `.radio` and `.checkbox` classes.

The [checkboxes and radios example](http://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios) uses the `.form-check` class exclusively while the [validation example](http://v4-alpha.getbootstrap.com/components/forms/#validation) uses `.radio` and `.checkbox` exclusively.
It is also worth noting that the validation styles for the label depend on the use of `.radio` and `.checkbox`

EDIT: Also affects disabled styles. The docs show both ways. Using `.radio`, as shown in the [form controls](http://v4-alpha.getbootstrap.com/components/forms/#form-controls) example, does not make the label gray when disabled. Using `.form-check` does make the label gray when it is disabled` as seen in the [using the grid](http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid) example

`.radio.disabled label`
![radio-disabled](https://cloud.githubusercontent.com/assets/664714/18180161/9d55bda8-7053-11e6-9845-4fbeb6eb1f36.gif)
`.form-check.disabled .form-check-label`
![form-check-disabled](https://cloud.githubusercontent.com/assets/664714/18180166/a0ad6f96-7053-11e6-89c6-c7bbdae1d950.gif)

**Comment by mdo** [comment]
Fixed by #20629.
