### ISSUE TITLE
Cloning and inserting a card looses toggle capability

### ISSUE THREAD

**Issue by aimeos** [twbs/bootstrap#20601]
OS: Ubuntu, Browser: Firefox 48

Copying a card looses toggle capability:
https://jsbin.com/geyenovizo/edit?html,js,output

**Comment by mdo** [comment]
Your JS Bin doesn't show me much, but I'm guessing that if you're duplicating a card, you'll need to update the `data-target` and `id`. If that's not the case, please comment and we can revisit.
