### ISSUE TITLE
Opening a modal from another modal and modal-open

### ISSUE THREAD

**Issue by AdamSGit** [twbs/bootstrap#20607]
When you open a modal from a link in another modal, it close the first modal to switch to the new one, but the body lose his "modal-open" class in the process.

**Comment by patrickhlauke** [comment]
Multiple modals are currently not supported.

**Comment by AdamSGit** [comment]
Yes I know, it's not the point. The issue is about the body class modal-open.

**Comment by cvrebert** [comment]
Duplicate of # 17956.

**Comment by Fusty** [comment]
Anyone looking to solve this, it's stupidly easy.  Not sure why they're not implementing something similar to this.  I think I'll submit a pull request for this if I can.

`//Watch for closing modals
$('.modal').on('hidden.bs.modal', function () {
    //If there are any visible
    if($(".modal:visible").length > 0) {
        //Slap the class on it (wait a moment for things to settle)
        setTimeout(function() {
            $('body').addClass('modal-open');
        },200)
    }
});`

**Comment by Metalchocobo** [comment]
@Fusty it's no a good solution. In my web app i keep permanently a padding on right of body after close the second modal.

**Comment by Metalchocobo** [comment]
@Fusty it's no a coplete solution. In my web app i keep permanently a padding on right of body after close the second modal.

**Comment by john-kamau01** [comment]
Try putting the second modal outside the first modal.

**Comment by fahmisabar** [comment]
@Fusty Thankyou very much!!

**Comment by k-suresh** [comment]
A detailed blog with an example: http://wp.me/p3Osmq-uf

**Comment by Adria-indico** [comment]
This worked for me:
Open your second modal programmatically through a click event. That is, remove _data-bs-toggle="modal" and  data-bs-target="#yourModal"_ and do instead:

buttonClick{
    **$(#yourModal).modal('show')**
}
