### ISSUE TITLE
Ability to select container for modals

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#20616]
It's a feature request.

When using layout libraries ([golden layout](https://www.golden-layout.com) for example) it is necessary to be able to select the container (the tab) so the backdrop doesn't fill the whole window and the modal can target the right tab!

**Comment by cvrebert** [comment]
So you're effectively asking for modals which are only modal to one area of the screen?

**Comment by natcohen** [comment]
Exactly!

**Comment by mdo** [comment]
Going to punt on this as something we'll tackle. Modal's are window-only, not a subset of that.
