### ISSUE TITLE
Background color in card variant header/footer

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#20614]
Headers and footers in card variants are practically indistinguishable from the card body since the background color is the same, where in the standard card a slightly darker background gives them their own visual semantic.

![screen shot 2016-09-02 at 10 47 34](https://cloud.githubusercontent.com/assets/851745/18198095/05c8b302-70fb-11e6-98cd-6db86aeb5da9.png)

Is this intended? In my opinion headers and footers in variants should follow the default visual behavior.

**Comment by Oxicode** [comment]
+1

**Comment by mdo** [comment]
Punted on the fix, so I'll punt on this for now, too. See #20649.
