### ISSUE TITLE
富文本框

### ISSUE THREAD

**Issue by helibin** [twbs/bootstrap#20611]
bootstrap 真的好用，但目前还没有集成富文本框，如果能加入就更好了

**Comment by tomlutzenberger** [comment]
Rich text editors should be implemented by yourself. There are a lot of libraries for this, for example
https://www.tinymce.com/

富文本编辑器应该自己来实现。有很多的库对于这一点，例如
https://www.tinymce.com/

**Comment by helibin** [comment]
嗯嗯，谢谢啊，我也用了个其它的，就是希望bootstrap能更强大，这样我们只用bootstrap+jq就行了，暂时没有也没关系，如果以后有集成的可能就太棒啦。                             原始邮件                             发件人: Tom Lutzenberger<notifications@github.com>收件人: twbs/bootstrap<bootstrap@noreply.github.com>抄送: helibin<helibin@139.com>; Author<author@noreply.github.com>发送时间: 2016年9月2日(周五) 15:52主题: Re: [twbs/bootstrap] 富文本框 (#20611)Rich text editors should be implemented by yourself. There are a lot of libraries for this, for example
https://www.tinymce.com/

富文本编辑器应该自己来实现。有很多的库对于这一点，例如
https://www.tinymce.com/

**Comment by tomlutzenberger** [comment]
别客气 :smiley:

**Comment by danggang** [comment]
呵呵






在 2016-09-02 16:22:16，"Tom Lutzenberger" <notifications@github.com> 写道：


别客气 😃

**Comment by cvrebert** [comment]
See also: http://summernote.org

Definitely not adding such widgets to core Bootstrap.
