### ISSUE TITLE
Incorrect scrollbar measuring in Windows Firefox 48 with 40% and less browser scale

### ISSUE THREAD

**Issue by metalass** [twbs/bootstrap#20621]
Hi, folks!

There is some problem with Bootstrap scrollbar measuring function when it try to measure scrollbar in big screens (or in desktop with negative scale, 40% for instanse) in **Windows Firefox 48.0.2**. It shows 0 pixels insead of 17 pixels.
There is an example: http://codepen.io/webvictor86/pen/bwGyoK
And screenshot: http://joxi.ru/MAjpMNyuv5ewvm (first number is measureScroll from original Bootstrap).
And it is easy to be fixed also. just replace:
.modal-scrollbar-measure { ... height: 50px; ... }
to that one:
.modal-scrollbar-measure { ... height: 99999px; ... }

I think that there are some other cases when the bug repeat (not only with browser scaling because bug was detected by my client that uses Mac, but not uses scaling, I guess).

**Comment by christianpv** [comment]
@mdo FYI The example has a reference to bootstrap 3.3.6. I believe this should be close.

**Comment by metalass** [comment]
Yeah, good point. But I've checked this one in bootstrap 3.3.7 also. In codepen.io default bootstrap version is 3.3.6, well here is an example in jsfiddle:
http://joxi.ru/VrwMQLBuKn4N42
https://jsfiddle.net/webvictor86/zmpeshcw/1/
The same problem unfortunately (

**Comment by woaixiaobanban** [comment]
I believe this should be close

**Comment by metalass** [comment]
But why?
This problem is easy to be fixed. And I believe it's not only about Firefox scaling, there are some other cases.
Bootstrap scrollbar measuring is a workaround and sometimes it's not precise, but just by changing one number it can become better.
U are upset me (

**Comment by mdo** [comment]
Work in v3 has stopped as we progress on v4. Closing out.
