### ISSUE TITLE
Consider using ES6 arrow functions instead of $.proxy()

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20633]
Refs #17673.

**Comment by alamgird** [comment]
@cvrebert is this an open issue? If so i'd like to work on it. Can i get this assigned?

**Comment by wyaeld** [comment]
Slighly related, but should bootstrap be using a styleguide or standards, enforced by eslint etc https://github.com/airbnb/javascript seems to be the most popular, but I can't judge its overall appropriateness for the project.
