### ISSUE TITLE
How to import JS module - alpha 4

### ISSUE THREAD

**Issue by danimalweb** [twbs/bootstrap#20634]
Great news on the alpha 4 release.

I was under the impression I would be able to selectively import any of the JS modules.

``import Carousel from 'bootstrap';``

When doing this I get the complete JS file for all modules (all Bootstrap JS)

Am I missing something? Thanks!

**Comment by cvrebert** [comment]
You're not missing anything. We just don't have our ES6 modularization story properly implemented yet.
#19017 tracks Bootstrap 4's JS modularization.
