### ISSUE TITLE
Date, Time, Datetime-local and Month inputs : incorrect line-height on Edge

### ISSUE THREAD

**Issue by Seb33300** [twbs/bootstrap#20645]
On Microsoft Edge browser, Date, Time, Datetime-local and Month inputs types contents are not displayed properly (with an incorrect line-height so the text is not vertically centered).

Demo here: http://www.bootply.com/ynEsXe67Hg

On Edge line-height is overridden by: (since it should not)
https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L2608
```
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  input[type="date"].form-control,
  input[type="time"].form-control,
  input[type="datetime-local"].form-control,
  input[type="month"].form-control {
    line-height: 34px;
  }
  input[type="date"].input-sm,
  input[type="time"].input-sm,
  input[type="datetime-local"].input-sm,
  input[type="month"].input-sm,
  .input-group-sm input[type="date"],
  .input-group-sm input[type="time"],
  .input-group-sm input[type="datetime-local"],
  .input-group-sm input[type="month"] {
    line-height: 30px;
  }
  input[type="date"].input-lg,
  input[type="time"].input-lg,
  input[type="datetime-local"].input-lg,
  input[type="month"].input-lg,
  .input-group-lg input[type="date"],
  .input-group-lg input[type="time"],
  .input-group-lg input[type="datetime-local"],
  .input-group-lg input[type="month"] {
    line-height: 46px;
  }
}
```

**Comment by twbs-lmvtfy** [comment]
Hi @Seb33300!

You appear to have posted a live example (http://s.bootply.com/render/ynEsXe67Hg), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 5, column 9 thru column 30: A document must not include both a ```` meta ```` element with an ```` http-equiv ```` attribute whose value is ```` content-type ````, and a ```` meta ```` element with a ```` charset ```` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by FelixRilling** [comment]
This issue seems to only exists in Bootstrap v3.3.x, for which support was dropped. In v4.0.0beta4 this issue doesnt exist.

**Comment by nsteenbeek** [comment]
This problem (in the current version v3.3.7!) also happens on iOS and Android.
