### ISSUE TITLE
Form control feedback in SVG background

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#20644]
Form control feedback currently needs a message block be rendered inside the form group, it works well but having a block element to show the feedback may push other elements down with a noticeable impact on the form layout.

Why not having the form control background SVG containing the text of an attribute? For example:

```html
<div class="form-group has-warning">
  <label class="col-form-label">Input with warning</label>
  <input type="text" class="form-control form-control-warning"
      aria-label="Shucks, check the formatting of that and try again">
</div>
```
![screen shot 2016-09-06 at 15 59 15](https://cloud.githubusercontent.com/assets/851745/18276885/dbec77b2-744c-11e6-99e4-0d4b588c6ebf.png)

I don't know if the `background-image` data URL may contain dynamic parts to have attribute content on the SVG, but maybe there are other means to achieve this I'm not aware of.

**Comment by mdo** [comment]
> Why not having the form control background SVG containing the text of an attribute? 

Good idea, but it doesn't seem like it'd scale to most implementations :). Thanks though!
