### ISSUE TITLE
V4 alpha 4 card-columns cuts off cards on top and bottom

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20654]
With the release of V4 alpha 4, **card-columns** class truncates the top of the middle and right cards when the cards are of varying heights. The same behavior occurs on the bottom edge, although it appears to be the third column that is shown completely, with 1 and 2 being cut off.

![card_cols_cutoff](https://cloud.githubusercontent.com/assets/6351149/18291787/575d5b6a-7447-11e6-81e6-ebf084e2abd7.png)

**Comment by kevdotbadger** [comment]
Browser? Also, are you using CSS columns?

**Comment by kennethn** [comment]
I'm seeing the same behavior, and also seeing it on the [Bootstrap documentation site](http://v4-alpha.getbootstrap.com/components/card/#columns). I'm on Mac OS X Chrome beta channel (currently 53.0.2785.80 beta (64-bit)).

![screen shot 2016-09-06 at 5 32 28 pm](https://cloud.githubusercontent.com/assets/5931405/18295647/fde51dfa-7457-11e6-8306-aa111d10a01f.png)

**Comment by bpierson** [comment]
I tested in IE 11, Firefox, Chrome on Windows 7. All the same. I'm just using the bootstrap.js and bootstrap.css from the **dist** folder, so whatever the default settings are.

**Comment by mdo** [comment]
Likely something to do with the `display: block` change we introduced in Alpha 4.

**Comment by dpmontero** [comment]
![captura de pantalla de 2016-09-07 07 58 19](https://cloud.githubusercontent.com/assets/16160165/18301386/3089557c-74d1-11e6-80d9-e0ab185727a1.png)

Captured in official documentation

**Comment by dpmontero** [comment]
I have tried! Fixed!!

Thanks!
