### ISSUE TITLE
Incompatible Units rem/px

### ISSUE THREAD

**Issue by allencoded** [twbs/bootstrap#20650]
We are using 4.0.0-alpha.4. So once I compile the source sass I run into this Error:
```
Error in plugin 'sass'
Message:
    node_modules/bootstrap/scss/_popover.scss
Error: Incompatible units: 'rem/px' and 'rem'.
        on line 114 of node_modules/bootstrap/scss/_popover.scss
>>   @include border-radius(($border-radius-lg - $offset-border-width) ($border-r
   --------------------------^
```

Looks like it has to do with `$offset-border-width` on line 114 in _popover.scss:
`@include border-radius(($border-radius-lg - $offset-border-width) ($border-radius-lg - $offset-border-width) 0 0);`

I went and looked at the older alpha v2 we were running and seen this:
`@include border-radius(($border-radius-lg - 1) ($border-radius-lg - 1) 0 0);`

I then went and changed our v4 line to match v2 and it seems to work. 
So something changed in the BS4 source code that has to do with `$offset-border-width` that is causing a break in the sass compiler. Currently using gulp sass as our compiler.

**Comment by cvrebert** [comment]
Unable to reproduce with current v4-dev.
That error normally means you've customized Bootstrap's variables, and one of your custom values uses incompatible units. So it's a bug in your particular choice of values rather than in Bootstrap.

**Comment by httpete** [comment]
I fixed this by removing my $base-font-size which was set to px.
