### ISSUE TITLE
Native font stack does not match documentation

### ISSUE THREAD

**Issue by jfinkels** [twbs/bootstrap#20655]
The documentation for version 4.0.0-alpha4 states that the "Ubuntu" font family is part of the default native font stack (http://v4-alpha.getbootstrap.com/content/reboot/#native-font-stack). I tested the "Hello, world!" example from the *Getting Started* page by viewing the file with Firefox version 48.0 on Ubuntu 16.04, but the computed font-family for `body` seems to be

    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    Roboto,
    "Helvetica Neue",Arial,sans-serif

The documentation suggests that this should be

    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    "Roboto",
    "Oxygen",
    "Ubuntu",
    "Cantarell",
    "Fira Sans",
    "Droid Sans",
    "Helvetica Neue", Arial, sans-serif !default;

Specifically, the documentation includes the following families that the actual code does not have:

    "Oxygen",
    "Ubuntu",
    "Cantarell",
    "Fira Sans",
    "Droid Sans",

Maybe this is a documentation/code mismatch?

**Comment by jfinkels** [comment]
Thanks for updating the documentation. This means Reboot will not attempt to provide native fonts for Linux systems?

**Comment by mdo** [comment]
> Thanks for updating the documentation. This means Reboot will not attempt to provide native fonts for (non-Android) Linux systems?

Basically, yes :(. The rendering—even with Roboto in there—is super inconsistent. We did it at GitHub and it was a shit show more or less based on whatever distro or settings each user had. We're still getting feedback on that actually. Hopefully we can deliver something better in the future, but at the very least, most distros seem able to swap from Helvetica to decent sans-serif options.
