### ISSUE TITLE
Clearer mentions of util.js

### ISSUE THREAD

**Issue by sodevious** [twbs/bootstrap#20660]
I realize a simialr issue has been made and closed: https://github.com/twbs/bootstrap/issues/17193

However, the `collapse.js` [plugin](http://v4-alpha.getbootstrap.com/components/collapse/) page should mention that `util.js` is a dependency. 

Additionally, the reference to `transitions.js` on the Introduction page should be changed to the appropriate `util.js` reference: http://v4-alpha.getbootstrap.com/getting-started/introduction/

**Comment by vanduynslagerp** [comment]
Changed the reference to `transition.js` to `util.js` in #21743 (although the PR covert primarily something else)

**Comment by bastienmoulia** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/javascript.md#util

Seems good to me.
