### ISSUE TITLE
Can't find a changelog that documents breaking changes

### ISSUE THREAD

**Issue by antpaw** [twbs/bootstrap#20675]
I've just updated form alpha.2 to alpha.4 and noticed that .breadcrumb stopped working because it now requires a .breadcrumb-item on each `<li>`. Is there a history where I can see all the breaking changes and new features?

**Comment by patrickhlauke** [comment]
you may be able to glean most of the information by looking at the various ship lists https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22ship%20list%22  (but nothing as involved as, say, the migration guide from 3 to 4 http://v4-alpha.getbootstrap.com/migration/)
