### ISSUE TITLE
Form-control line-height and browser zoom

### ISSUE THREAD

**Issue by plouveau** [twbs/bootstrap#20676]
Hi,
I'm using Bootstrap V4 alpha 4.

I've noticed that when you write a letter with a tail like p, q, g, the letter's tail was cutting for each text input with a zoom > 100%

Bootstrap defines the actual line-height by 1.5.
But if you remove that, the browser's default line-height (24px) renders fine and doesn't cut each letter.

**Comment by cvrebert** [comment]
What browser and OS are you using?

**Comment by plouveau** [comment]
I'm using Chrome v53 on Windows 10.

**Comment by mdo** [comment]
Not seeing too much changing on zoom for Chrome Mac at least, so closing out for now until we have a clearer example or more reports.
