### ISSUE TITLE
Bootstrap and Internet Explorer 8 Carusel

### ISSUE THREAD

**Issue by ArtesanoDigital** [twbs/bootstrap#20679]
Hello, I'm in trouble, I'm updating an intranet that is used in Internet Explorer 8, does not the carousel, and the probe-carousel.min.js- -ie-bootstrap script does not work ...! help.

**Comment by ArtesanoDigital** [comment]
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/ie-bootstrap-carousel.min.js"></script>

**Comment by cvrebert** [comment]
For troubleshooting assistance, please use our community forums (StackOverflow, IRC, Slack); see https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community for links to them.
