### ISSUE TITLE
[Firefox] Prefixed Page Visibility API has been removed

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#20674]
https://www.fxsitecompat.com/en-CA/docs/2016/prefixed-page-visibility-api-has-been-removed/

**Comment by cvrebert** [comment]
This might be relevant to the Carousel JS.

**Comment by Johann-S** [comment]
We don't use a prefixed version of Visibility API, see : https://github.com/twbs/bootstrap/pull/17710
