### ISSUE TITLE
"marketing pages" link on Bootstrap Themes main page goes to application template

### ISSUE THREAD

**Issue by Avrong** [twbs/bootstrap#20689]
![image](https://cloud.githubusercontent.com/assets/6342851/18396814/1e72b726-76ce-11e6-9fef-95bd0ff0ba36.png)
![image](https://cloud.githubusercontent.com/assets/6342851/18396870/65ab42e8-76ce-11e6-9ff5-832d8b591c63.png)

**Comment by cvrebert** [comment]
Closing per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker 

> * Please do not open issues regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to `themes AT getbootstrap DOT com`.
