### ISSUE TITLE
bootstrap affix does not behave in Safari same as in other browsers

### ISSUE THREAD

**Issue by athimannil** [twbs/bootstrap#20686]
The `nav` sticky at the top of the page without scrolling. 

It happens only in Safari browser. 

**Demo** https://jsbin.com/waqezepijo

**Comment by twbs-lmvtfy** [comment]
Hi @athimannil!

You appear to have posted a live example (http://codepen.io/athimannil/pen/kkraVP.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 10, column 1 thru column 23: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 33, column 1 thru column 7: Stray end tag ```` head ````.
* line 34, column 1 thru column 45: Start tag ```` body ```` seen but an element of the same type was already open.
* line 34, column 1 thru column 45: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by athimannil** [comment]
Thank you very much for the comment 
@twbs-lmvtfy Just updated the demo link 👍

**Comment by cvrebert** [comment]
The Affix plugin has been removed in Bootstrap v4.
Bootstrap v3 is no longer supported, per #20631.
See https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community for links to community help forums.

**Comment by athimannil** [comment]
It is a bug in mac safari reported 4 years ago.
Yet, they did not fix https://trac.webkit.org/changeset/139669
