### ISSUE TITLE
In grid docs, clarify that container widths are maximums rather than exact widths

### ISSUE THREAD

**Issue by Kamikadze4GAME** [twbs/bootstrap#20688]
Link: http://v4-alpha.getbootstrap.com/layout/grid/#grid-options
"Small ≥544px" and "Container width 576px"
I think that "Container width 512px"

**Comment by tomlutzenberger** [comment]
Nope, it's correct.
See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L141

**Comment by cvrebert** [comment]
We should change that row title to clarify that those are **maximum** container widths.

**Comment by jmahc** [comment]
I do have a question regarding `.container`

Why are these not isolated to specific screen sizes?  Instead, we see CSS overwrites...am I missing something here?

In my mind, the less overwrites, the better.  Therefore, utilizing Bootstrap v4 should incorporate the following:


// For each breakpoint, define the maximum width of the container in a media query
@mixin make-container-max-widths($max-widths: $container-max-widths, $breakpoints: $grid-breakpoints) {
  @each $breakpoint, $container-max-width in $max-widths {
    // @include media-breakpoint-up($breakpoint, $breakpoints) {
    //   max-width: $container-max-width;
    // }
    // jmahc's thoughts....???? (aka it's me)
    // Maybe this will prevent overwrites...?
    @include media-breakpoint-only($breakpoint, $breakpoints) {
      max-width: $container-max-width;
    }
  }
}

**Comment by Kamikadze4GAME** [comment]
![image](https://cloud.githubusercontent.com/assets/10538480/18502962/11105244-7a63-11e6-9e46-3aa32fdc10b7.png)
Look:
Extra Large (≥1200px and container width 1140px): 1200 - 1140 = 60
Large (≥992px and container width 940px): 992 - 940 = 52
Medium (≥ 768px and container width 720px): 768 - 720 = 48
Small (≥ 544px and container width 576px): 544 - 576 = -22 (Why <0?)

**Comment by spdpiyush** [comment]
No, It's Correct Which Is Mentioned Above.
But You Have Also Access To Change Width According To Your Choice.
