### ISSUE TITLE
v4: p inside an .alert break the layout with their default margin

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#20693]
<img width="605" alt="bildschirmfoto 2016-09-10 um 16 49 00" src="https://cloud.githubusercontent.com/assets/111561/18411386/a8c5c9f6-7776-11e6-8717-b04cffb3b77b.png">

Since all P tags have a default margin bottom, the .alert elements look bad whenever there is a P inside.

Workaround:
```sass
.alert
  ol:last-child,
  ul:last-child,
  p:last-child
    margin-bottom: 0px
```

**Comment by mdo** [comment]
To avoid bloated styles on our end, I removed the overrides for that like we had in v3. Use the margin utilities to override these kinda things in v4. :)
