### ISSUE TITLE
Preventing overwrites for `.container`

### ISSUE THREAD

**Issue by jmahc** [twbs/bootstrap#20691]
OK - so call me clueless, but why does bootstrap utilize overwrites for container sizes?

Case in point, this mixin for containers:

```
// For each breakpoint, define the maximum width of the container in a media query
@mixin make-container-max-widths($max-widths: $container-max-widths, $breakpoints: $grid-breakpoints) {
  @each $breakpoint, $container-max-width in $max-widths {
    // @include media-breakpoint-up($breakpoint, $breakpoints) {
    //   max-width: $container-max-width;
    // }
    // Instead of a breakpoint up (which eventually gets overwritten as the screen size grows...
    // .... .... .... Why doesn't Bootstrap utilize "isolated" breakpoints for stuff like this?

    // Maybe I'm a noob but this makes sense to me.
    @include media-breakpoint-only($breakpoint, $breakpoints) {
      max-width: $container-max-width;
    }
  }
}
```

**Comment by jmahc** [comment]
In hindsight, my comments within the code are not as clear as I would like them to be.

If you are using a container with a max-width at a certain viewport size, would you not want it to be isolated to that "breakpoint criteria".

For example: 

```@media screen and (min-width: x) and (max-width: y)```

You would only want that container size applied within those 'boundaries' versus being overwritten (just bad practice).

Thoughts?

**Comment by mdo** [comment]
Both are valid approaches I suppose, but the current implementation is easily communicated and extends to similar methods used across the project. We set properties and values from the smaller viewports and modify them as those viewports grow in size. Not always the cleanest, but it is the easiest in my experience.

Hope that helps explain it a bit!

**Comment by jmahc** [comment]
Makes sense to me - was just curious about the thought process behind this decision, which you've answered.

Thanks!
