### ISSUE TITLE
Tooltip position wrong when there is horizontal scrolloffset v3.3.7

### ISSUE THREAD

**Issue by Maxrunner** [twbs/bootstrap#20704]
It seems that if we have the window page smaller enough that there is an horizontal scroll bar, the position of the tooltip when we mouse over the text,  will be wrongly affected, as we can see in the picture:

![image](https://cloud.githubusercontent.com/assets/313850/18433586/58dbbb4c-78e0-11e6-94da-5f81be2b509e.png)
![image](https://cloud.githubusercontent.com/assets/313850/18433654/d55d9064-78e0-11e6-9b8f-62889f0b02fa.png)

The problem seems to be the applyPlacement method:

` Tooltip.prototype.applyPlacement = function (offset, placement) {
    var $tip   = this.tip()
    var width  = $tip[0].offsetWidth
    var height = $tip[0].offsetHeight

    // manually read margins because getBoundingClientRect includes difference
    var marginTop = parseInt($tip.css('margin-top'), 10)
    var marginLeft = parseInt($tip.css('margin-left'), 10)

    // we must check for NaN for ie 8/9
    if (isNaN(marginTop))  marginTop  = 0
    if (isNaN(marginLeft)) marginLeft = 0

    offset.top  += marginTop
    offset.left += marginLeft

    // $.fn.offset doesn't round pixel values
    // so we use setOffset directly with our own function B-0
    $.offset.setOffset($tip[0], $.extend({
      using: function (props) {
        $tip.css({
          top: Math.round(props.top),
          left: Math.round(props.left)
        })
      }
    }, offset), 0)

    $tip.addClass('in')

    // check to see if placing tip in new offset caused the tip to resize itself
    var actualWidth  = $tip[0].offsetWidth
    var actualHeight = $tip[0].offsetHeight

    if (placement == 'top' && actualHeight != height) {
      offset.top = offset.top + height - actualHeight
    }

    var delta = this.getViewportAdjustedDelta(placement, offset, actualWidth, actualHeight)

    if (delta.left) offset.left += delta.left
    else offset.top += delta.top

    var isVertical          = /top|bottom/.test(placement)
    var arrowDelta          = isVertical ? delta.left * 2 - width + actualWidth : delta.top * 2 - height + actualHeight
    var arrowOffsetPosition = isVertical ? 'offsetWidth' : 'offsetHeight'

    $tip.offset(offset)
    this.replaceArrow(arrowDelta, $tip[0][arrowOffsetPosition], isVertical)  }  `

This is probably related to elements with specific width values too and regarding the possible solution 
It seems if i comment the last two lines of the method it fixes the position.

Here's the example i've created with bootstrap 3.3.7 version:
[boostrap -3.3.7 example tooltip.zip](https://github.com/twbs/bootstrap/files/467145/boostrap.-3.3.7.example.tooltip.zip)

**Comment by cvrebert** [comment]
Bootstrap v3 is unfortunately no longer officially supported.
See https://github.com/twbs/bootstrap/blob/v4-dev/README.md#community for links to our community support forums.

**Comment by Maxrunner** [comment]
Hi! Isn't the v3.3.7 the latest final release?

**Comment by cvrebert** [comment]
See #20631.

**Comment by anon1970** [comment]
I too am suffering from this bug, and its siblings, in v3.3.7.
Given that v3 is now in "critical fixes only" mode, is there any wisdom on a workaround - CSS, or JS or both?

**Comment by Maxrunner** [comment]
Yes,
My solution was, go to the method  **Tooltip.prototype.applyPlacement** in bootstrap.js, and either comment the last two lines or create a condition to only use them in case there is no left scrolloffset:

if($( document, window ).scrollLeft()===0){
		$tip.offset(offset)
		this.replaceArrow(arrowDelta, $tip[0][arrowOffsetPosition], arrowPosition)
	}

**Comment by cvrebert** [comment]
Probable duplicate of #15590.
