### ISSUE TITLE
Recommended install method for meteor

### ISSUE THREAD

**Issue by nmaro** [twbs/bootstrap#20714]
Since meteor allows to import npm packages directly, which way is recommended? meteor install or npm install?

**Comment by christianbundy** [comment]
https://atmospherejs.com/twbs/bootstrap

**Comment by cvrebert** [comment]
npm is now recommended. See #20389.

**Comment by nmaro** [comment]
Maybe reopen this until this is reflected in the Quick Start section of the Readme?

**Comment by nmaro** [comment]
If someone lands here: here is a showcase of npm bootstrap integration with meteor: https://github.com/juliancwirko/meteor-bootstrap-npm-test

**Comment by pilarArr** [comment]
The atmosphere package is now in 3.3.6, I guessed from other closed issues that it has been discontinued. Installing it gives a restriction on jQuery version but installing the npm package for 3.3.7 does not load the glyphicon fonts, I have to manually copy them to a public folder. This is in meteor. @nmaro  Any ideas on how to work with 3.3.7 in meteor?
