### ISSUE TITLE
Add lint check that all variables are !default

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#20717]
Refs #20716

**Comment by arthur801031** [comment]
@cvrebert  May I work on this? I'm a first time contributor to bootstrap.

**Comment by arthur801031** [comment]
@cvrebert  @mdo I've added a lint function to check if all the variables in _variables.scss are !default. Please check. Thank you very much!

**Comment by ryzokuken** [comment]
This one hasn't been responded to for a long time. Can I try to resolve this?

**Comment by Johann-S** [comment]
every openned issues are available for folks 👍

**Comment by freezy-sk** [comment]
I've created rule for stylelint-scss https://github.com/kristerkari/stylelint-scss/issues/198
Once it will be accepted, I will create PR with new linting setting
