### ISSUE TITLE
[docs] btn-outline-primary should be btn-primary-outline

### ISSUE THREAD

**Issue by pierre-b** [twbs/bootstrap#20727]
Hi guys, like the subject says: ```btn-outline-primary``` should be ```btn-primary-outline``` in the docs.
Hope this could save some time to others :)

**Comment by tomlutzenberger** [comment]
The naming logic depends on how you group the elements.
Are they grouped by type or by color?
Type: `btn-[type-group]-[specifier]` = `btn-outline-primary`
Color: `btn-[color-group]-[specifier]` = `btn-primary-outline`

So I think it's correct that way. But I see your point.
There are classes in Bootstrap that look/feel wrong when you read their names.

**Comment by cvrebert** [comment]
@pierre-b Please clarify whether you're claiming that the docs don't match the actual CSS or whether you're asking for the classes to be renamed.

**Comment by pierre-b** [comment]
yes the docs don't match the actual CSS

**Comment by jipexu** [comment]
Hi
before the class was  : btn-xxx-outline
now in alpha 4 is : btn-outline-xxx

**Comment by mdo** [comment]
The name is correct in `v4-dev` and Alpha 4.
