### ISSUE TITLE
Best Projects workflow for y'all?

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#20721]
Hey everyone!

We just launched [Projects on GitHub](https://github.com/universe-2016)—and code review, new profiles, Integrations, GraphQL API, and more :D—and I'd love to know how the Bootstrap community would like us to use the feature here. We haven't been the best at communicating larger changes or what we're actively focused on, and I'd love to give folks better information so they can contribute more easily.

- What kind of columns would you like to see?
- What's missing from our current milestones setup?
- Do our [ship lists](https://github.com/twbs/bootstrap/issues/20630) work well enough for y'all?
- Any new labels we should look into (e.g., `has-pull-request`)?

Holler with any and all feedback. I started putting together [one for our next v4 release, Alpha 5](https://github.com/twbs/bootstrap/projects/1), but wanted to pause that until more folks had the opportunity to help direct it's usage :).

<3

**Comment by wolfy1339** [comment]
The label `has-pull-request` is a really good idea

**Comment by judetucker** [comment]
Love the `has-pull-request` or `attached-pr` labels. It works great for the Rails contributor community. They make great use of this label.

X-ref #20399

**Comment by tomlutzenberger** [comment]
**Columns in Projects:**
- Backlog
- Help wanted/Approved
- Priority/Important/Bug
- Pending PR
- Test/Review
- Good-to-merge
- Done/Merged (Milestone/Release)

**Ship list:**
- It would be nice to have kind of an "optical indicator" that show the progress on the current release/milestone. This could encourage people.
- It would also be nice to see how (estimated) complex (no-brainer to unsolvable) an issue is. Could be solved with labels.

**Comment by wolfy1339** [comment]
Add state of PRs via labels or labels within the title
Ex: If a PR is WIP, mark it with a WIP label.
Use the RFC label to request comments
Use the RDY label to let other people know that the PR is ready to merge

**Comment by bardiharborow** [comment]
The high issues/spare-time ratio of this project means that a lot of issues and PRs to go without any core team response for months, so any mechanism to prioritise and organize work is very welcome. The issue that remains is that there is no mechanism for the community to help triage issues/PRs. There are a lot of, at least from my point of view, "easy-merge" PRs that have stalled, and short of pinging the core team (which I'm very reticent to do given your high workload), there is no way for me to ask for the to be prioritised.

**Comment by mdo** [comment]
Going with the hybrid of things suggested here and elsewhere. I'll look into the label for things that have a PR attached (usually I just get those merged if they're ready to go in our view).

Thanks y'all!
