### ISSUE TITLE
V4: Remove left and right border of list-group-item inside Card

### ISSUE THREAD

**Issue by webdevron** [twbs/bootstrap#20720]
All `.card` and `.list-group-item` has a default border. When using `.list-group-item` inside a `.card` both border a showing and displaying as a single border of 2px which looks ugly.

![bs](https://cloud.githubusercontent.com/assets/8216116/18531030/09182ac4-7af6-11e6-8738-590bbec908d9.png)

**Comment by Starsam80** [comment]
Duplicate of #20395

**Comment by cvrebert** [comment]
Please search more in the future.
