### ISSUE TITLE
.card-columns break card layout in v4

### ISSUE THREAD

**Issue by s123121** [twbs/bootstrap#20736]
In Bootstrap 4 Alpha 4, `card-columns` split `card` in half and then display `card` in two column. See picture:
<img width="752" alt="screen shot 2016-09-17 at 6 00 54 pm" src="https://cloud.githubusercontent.com/assets/3921357/18607188/c01e8e78-7d00-11e6-9042-2d8de6673988.png">
Also, the jsbin example:
https://jsbin.com/robemogiba/edit?html,output

The problem doesn't exist in Bootstrap 4 Alpha 3

P/s: I am using OSX Yosemite with Chrome version 52.0.2743.116 (64-bit)

**Comment by rafalp** [comment]
Dupe for #20654

**Comment by mdo** [comment]
Yeah, closing as a duplicate.
