### ISSUE TITLE
custom-checkbox broken when not using label next to checkbox

### ISSUE THREAD

**Issue by Gillardo** [twbs/bootstrap#20730]
When reporting a bug, include:

- Operating system and version (Windows)
- Browser and version (Chrome 52.0.2743.116 m (64-bit))

![image](https://cloud.githubusercontent.com/assets/7406381/18583338/ee136fb0-7c01-11e6-8e2b-e60c862cfed0.png)

Code to reproduce, as you can see i am using a form, so no need to have a description 
```
    <div class="row form-group">
        <label class="col-sm-2 col-form-label">Legend</label>
        <div class="col-sm-10 col-md-7">
            <label class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" />
                <span class="custom-control-indicator"></span>
            </label>
            <div class="text-muted">
                Display legend
            </div>
        </div>
    </div>
```

I have also tried adding a blank ```custom-control-description``` class to the html, so it looks like this, and again, still same line up issue

```
    <div class="row form-group">
        <label class="col-sm-2 col-form-label">Legend</label>
        <div class="col-sm-10 col-md-7">
            <label class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" />
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description"></span>
            </label>
            <div class="text-muted">
                Display legend
            </div>
        </div>
    </div>
```

If however, i use `custom-control-description` and ever in a single character, it lines up fine, as you can see here

![image](https://cloud.githubusercontent.com/assets/7406381/18583320/d8697e2a-7c01-11e6-8c95-38141873709a.png)

**Comment by tomlutzenberger** [comment]
Could be post it as a JSbin example?

**Comment by Gillardo** [comment]
jsbin supplied with latest bootstrap css https://jsbin.com/kujilitawu/edit?html,css,output

**Comment by tomlutzenberger** [comment]
Why is the text outside of the label? That's what it's for.
This solves it for me:
`<span class="custom-control-description text-muted">Display legend</span>`

**Comment by Gillardo** [comment]
the text "Display Legend" is just the help text, the "label" is the "Legend" text

**Comment by tomlutzenberger** [comment]
In this case your markup is basically wrong.

**Comment by Gillardo** [comment]
How can my markup be wrong?  I would like Legend to appear next to the checkbox, and my help text (which says Display Legend) to appear under it...

This `<span class="custom-control-description text-muted">Display legend</span>` does not solve the issue, as you can see in the jsbin, the label appears next to it still

**Comment by tomlutzenberger** [comment]
As long as this is not a bug, I'd recommend to ask such questions on sites like [stackoverflow](http://stackoverflow.com/) or similar.

**Comment by stone1113** [comment]
wow吼厉害
