### ISSUE TITLE
Carousel indicators vertical alignment is broken

### ISSUE THREAD

**Issue by salparadise** [twbs/bootstrap#20738]
Since indicators margins (`1px` - default, `0` - active) are hardcoded, setting i.e. the same value of `$carousel-indicator-size` and `$carousel-indicator-active-size` breaks their vertical alignment.

<img width="90" alt="zrzut ekranu 2016-09-17 o 16 45 57" src="https://cloud.githubusercontent.com/assets/4439778/18609016/df647cec-7cf7-11e6-9495-667b2ee5e1d3.png">

**Comment by mdo** [comment]
No longer an issue since the redesigned carousel in #21298.
