### ISSUE TITLE
Missing clearfix on docs for responsive navbar

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#20749]
Per <https://v4-alpha.getbootstrap.com/components/navbar/> and the screenshot below:

<img width="527" alt="screen shot 2016-09-20 at 7 13 41 am" src="https://cloud.githubusercontent.com/assets/523141/18668170/f50460f6-7f01-11e6-87e3-2ad6a33a344e.png">

We need to add `<div class="clearfix hidden-sm-up"></div>` below the `navbar-brand` anchor tag.  This fixes the weird line break issue between the navbar items and the navbar brand.

**Comment by craigstroman** [comment]
I would be interested in fixing this.

**Comment by niftylettuce** [comment]
Send over your pull request @craigmichaelmartin 👍

**Comment by craigstroman** [comment]
Pull request created.

**Comment by mdo** [comment]
Resolved in #19890.
