### ISSUE TITLE
Nested collapsible elements with shown and hidden events

### ISSUE THREAD

**Issue by makshh** [twbs/bootstrap#20747]
I'm using Bootstrap collapse (Bootstrap 3.3.7) to create 3rd menu level.

I'm adding panel-active class to the parent to change more to less in CSS.

The problem is that when I'm opening Item 2.1, panel-active class is added to the href="#test3" div (which is good) AND href="#test2" div (which is bad). It seems like Bootstrap shown.bs.collapse and hidden.bs.collapse events are firing twice when I'm opening/hiding nested Item 2.1.

To reproduce the problem try to show/hide Item 2.1 (panel-active class is added/removed to/from both divs (with href="#test2" and href="#test3").

**[CODEPEN](http://codepen.io/makshh/pen/ozzqZV)**

**Comment by cvrebert** [comment]
Unfortunately, Bootstrap 3 is no longer officially supported.
Please use the community forums linked in the README (e.g. StackOverflow) for assistance. Thanks.
