### ISSUE TITLE
Use a variable for the default font-weights

### ISSUE THREAD

**Issue by sbaechler** [twbs/bootstrap#20741]
Right now Bootstrap uses the hardcoded font weights `bold` and `normal`.

Websites might use different weights such as `medium` or `thin` or use `light` as default weight instead of `normal`.

If Bootstrap used settings variables for `$font-weight-normal` and `$font-weight-bold` the user could easily override the default values or use numerical weights.

This would also help #18605. 

Those two lines could be added to the _variables.scss:

    $font-weight-normal: normal;
    $font-weight-bold: bold;

All occurrences of `font-weight: normal;` would be replaced by `font-weight: $font-weight-normal`. The same applied for `font-weight: bold;`.

Foundation uses a [similar approach](https://github.com/zurb/foundation-sites/blob/master/scss/settings/_settings.scss#L69-L70).

I could create a pull-request for this.

**Comment by cvrebert** [comment]
X-Ref: #16170
