### ISSUE TITLE
404 error in Utility classes

### ISSUE THREAD

**Issue by QuentinGibson** [twbs/bootstrap#20743]
There's a link in the Utility classes page under CSS display that leads to a 404 error

browser: Chrome

page: http://v4-alpha.getbootstrap.com/components/utilities/#text-alignment

link: http://v4-alpha.getbootstrap.com/components/layout/responsive-utilities/

Edit: I just figured out what it should link too
http://v4-alpha.getbootstrap.com/layout/responsive-utilities/

**Comment by bardiharborow** [comment]
Fixed in #20557.
