### ISSUE TITLE
iOS 10 Safari navbar disappears after opening a <select> menu

### ISSUE THREAD

**Issue by gomski** [twbs/bootstrap#20759]
go to:
https://bootswatch.com/cerulean/
scroll to form and select the select element.
The navbar will disappear as long as the iOS Safari input helper is open and reappears when closing.
The same happens to ALL fixed elements on the page, they disappear\get relative positioned.

I have an SPA app which modifies the page contents when selecting an option and all elements stay hidden after closing after choosing a select option. The nav ans sidebar are seem to loose their fixed postition and stay at relative positions. Furtermore the postition of the select input helper is misplaced after opening the select element a second time. Turning the device repositions the select helper to the correct position.

Apple bug report has been filed. #28407863 
generic bootstrap site before select
![generic bootstrap site before select](https://cloud.githubusercontent.com/assets/3985767/18720266/668b9ab2-802b-11e6-8f11-12c5b52ad12e.png)

generic bootstrap site after select
![generic bootstrap site after select](https://cloud.githubusercontent.com/assets/3985767/18720269/704f3d4c-802b-11e6-8255-56fc3012b480.png)

web brf normal view before selecting select element
![web brf normal view before selecting select element](https://cloud.githubusercontent.com/assets/3985767/18720245/49e6d1a6-802b-11e6-8ed9-b14b872c6d60.png)

web brf nav sidebar scroll to top and all other fixed elements disappeared after selecting select element
![web brf nav sidebar scroll to top and all other fixed elements disappeared after selecting select element](https://cloud.githubusercontent.com/assets/3985767/18720253/57380e1a-802b-11e6-82e0-d1d2756c14fa.PNG)

web brf after closing select
![web brf after closing select](https://cloud.githubusercontent.com/assets/3985767/18720261/5e10c0ba-802b-11e6-947b-f22fe35df3df.png)

web brf misplaced select helper
![web brf misplaced select helper](https://cloud.githubusercontent.com/assets/3985767/18720284/7fe779c2-802b-11e6-9aef-e31df913d0eb.png)

web brf after screen rotation select helper realigns
![web brf after screen rotation select helper realigns](https://cloud.githubusercontent.com/assets/3985767/18720279/79ef4c48-802b-11e6-9419-bb0ef4140486.png)

**Comment by cvrebert** [comment]
> Apple bug report has been filed. #28407863 

I would encourage you to repost your report to https://openradar.appspot.com
I would also encourage you to file a WebKit bug: https://bugs.webkit.org

**Comment by cvrebert** [comment]
However, since this concerns Bootstrap 3, which is no longer supported per #20631, I will close this.
Please let us know if the bug also occurs with Bootstrap 4, in which case I'll be happy to reopen this for further action.

**Comment by gomski** [comment]
Thanks,
bugs filed... 

for BS4 demo see
http://www.codeply.com/go/GjrVfpcyEv
scroll down to select and watch the navbar disappear

**Comment by cvrebert** [comment]
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=162362

**Comment by cvrebert** [comment]
@gomski Looks like you're using an iPad. What exact model of iPad is it?

**Comment by gomski** [comment]
its an iPad Air A1475

**Comment by vhanahrni** [comment]
Hi, I noticed this too and created stack [post](http://stackoverflow.com/questions/39967817/ios-10-safari-select-issue) yesterday.

**Comment by mdo** [comment]
Do we just need to document the bug here @cvrebert or can this be closed out as something outside our control?

**Comment by cvrebert** [comment]
@mdo Just need to add it to the Wall.

**Comment by sbaechler** [comment]
It looks like the Safari bug has been fixed in iOS 10.3.1.
