### ISSUE TITLE
Split button dropdowns grow wider when expanded on Android Chrome

### ISSUE THREAD

**Issue by josheby** [twbs/bootstrap#20758]
On Chrome on Android, when clicking the dropdown button on the split button the spacing shifts on the right side and extra padding or margin is added.  See screenshots.  

I didn't see any other issue that appreaed related so I am opening a new issue.  Let me know if I can provide any further information.

![screenshot_20160921-104035](https://cloud.githubusercontent.com/assets/12487096/18715698/3597a3c6-7fe8-11e6-90c5-a5a54dd5b060.png)

![screenshot_20160921-104039](https://cloud.githubusercontent.com/assets/12487096/18715700/3601bb8a-7fe8-11e6-89a9-24e7a8919828.png)

Browser Version:
Chome 53.0.2785.124

Operation System:
Android 6.0.1; Nexus 6 Build MOB31E

**Comment by tstackhouse** [comment]
This also occurs in Desktop Chrome.

I looked into it in more detail, and it appears that the main culprit is that the `.dropdown-backdrop` <div> is being prepended to the DOM before the split button, thus breaking style rules for split dropdown buttons:

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_button-group.scss#L28-L33

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_button-group.scss#L95-L102

I'm sure there are other effects of this, but that seems to be the main culprit.

**Comment by mdo** [comment]
This has been fixed in v4-dev. See demo at https://output.jsbin.com/piwakik/.
