### ISSUE TITLE
Artifacts in scrollable modal on Edge (Windows 10)

### ISSUE THREAD

**Issue by amozes** [twbs/bootstrap#20755]
Using Edge 25.10586.0.0 (and possibly IE 9+) on Windows 10, artifacts appear on a modal with enough content to require scrolling.
As the user scrolls, transparent 1px lines bleed through to the background on the boundaries of the scroll.  These artifacts move as you continue to scroll (depending on where you stop and start).  Resizing the browser window will also create them sporadically.
You can see this on Bootstrap 3 and 4 on the live modal demo.

![capture](https://cloud.githubusercontent.com/assets/5177408/18696906/80b3f0fc-7f71-11e6-9fe0-71084b471e46.png)

**Comment by patrickhlauke** [comment]
Can confirm. Refs https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9011176/
