### ISSUE TITLE
Moving to Bootstrap 4 means no more free compiler?

### ISSUE THREAD

**Issue by raknjak** [twbs/bootstrap#20753]
This is going to affect many users so yeah, is there a free compiler for SASS?
edit: please do not mention koala, it has been abandoned.

**Comment by bsssshhhhhhh** [comment]
There's a bunch of (free!) ways to transpile sass. [sass-lang.com](http://sass-lang.com/libsass) has a list of libsass wrappers for different languages. Pick whichever you prefer.

**Comment by raknjak** [comment]
Thanks for your reply. Going to love having to maintain this where before we poor and lazy developers (or is that just me?) could just click a button and get on with life. Node wrapper looks interesting enough though.
