### ISSUE TITLE
Icon in input-group button makes button smaller than input

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#20750]
When adding an icon into an input group button, the button height is smaller than the input. I don't know if I'm doing something wrong but here is how to reproduce it (using [fontawesome](http://fontawesome.io/))

    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">
          <i class="fa fa-calendar"></i>
        </button>
      </span>
      <input type="text" class="form-control" placeholder="Date">
    </div>

**Comment by Rosenny08** [comment]
Hello natcohen. I tried your code and both of then have the same height. Or maybe I don't understand very well your question.
![untitled](https://cloud.githubusercontent.com/assets/21026681/18687191/29c19388-7f3c-11e6-9b6f-99200fc5b2b3.png)

**Comment by natcohen** [comment]
Weird...this is what I'm getting:

![input-group](https://cloud.githubusercontent.com/assets/7813574/18688210/9771f1d8-7f83-11e6-8820-647ec8b1670b.png)

Are you sure you're using `input-group-btn` and not `input-group-addon`?

**Comment by cvrebert** [comment]
We are unable to provide assistance with third-party libraries such as FontAwesome. Sorry.
Try StackOverflow or the other forums in the Community section of the README instead. Good luck!
