### ISSUE TITLE
.img-fluid Should not apply display:block by default

### ISSUE THREAD

**Issue by arctic-ice-cool** [twbs/bootstrap#20767]
The `.img-fluid` class applies `display: block;` styling by default. This is a completely different & additional behaviour to what `.img-fluid` is meant to do.

Shouldn't `.img-block` be a seperate class?

**Comment by mdo** [comment]
Agreed that `display: block` is unnecessary for the `max-width` and `height: auto` to have an affect—see https://jsbin.com/tefukez/. I'll remove that in Alpha 5.

However, I won't be adding `img-block`—there are other display utils for that.
