### ISSUE TITLE
v4 Avoid common shorthand IE flex bugs 

### ISSUE THREAD

**Issue by philmayfield** [twbs/bootstrap#20760]
As noted in this document: [https://github.com/philipwalton/flexbugs](https://github.com/philipwalton/flexbugs)

Specifically [#4](https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored) and [#6](https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed).

`_card.scss` uses `flex: 1 0 0;` short hand.  Suggest changing to `flex: 1 0 0%;`

`_input-group.scss` and `_media.scss` use `flex: 1;` short hand.  Suggest changing to `flex: 1 1 0%;`

`mixins/_grid-framework.scss` uses `flex-basis: 0;` short hand.  Suggest changing to `flex-basis: 0%;`

**Comment by razh** [comment]
This is handled with `postcss-flexbugs-fixes`: https://github.com/luisrudge/postcss-flexbugs-fixes

https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/grunt/postcss.js#L3

For example: https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/dist/css/bootstrap-flex.css#L914

**Comment by philmayfield** [comment]
Ah, got it thanks!  I'm using a custom build process with gulp, and never saw that part.  I will look for the same solution.  Closing the issue.
