### ISSUE TITLE
Bootstrap Problem with Pagination

### ISSUE THREAD

**Issue by Gabo46** [twbs/bootstrap#20761]
Version: 3.3.7 (newest)
CMS: Wordpress

Hello guys, I have followed your tutorial of how to set up a bootsrap pagination and wrote a wordpress function to add classes and html tags. But there is a problem. Even though the pagination breaks after every item. So f.e. page 2 is one line under page 1 etc.
URL: https://www.weeabow.de 
I don't get what I did wrong

**Comment by gomski** [comment]
remove
a {
	/*! clear:both; */
}
from style.css

**Comment by gomski** [comment]
I just see that you have changed to navigations markup...
It is not very useful to post bug reports when fiddling around with the code.
Thanks for wasting my time!

**Comment by Gabo46** [comment]
However it was just a test for pagination if the articles for my client get too much, the pagination will be needed. Thanks for help, I changed some things too and working fine.

**Comment by cvrebert** [comment]
Bootstrap 3 is no longer officially supported. Please use the community forums linked in the README, e.g. StackOverflow, for further assistance. Thanks.

**Comment by gomski** [comment]
Thanks,
bugs filed...

for BS4 demo see
http://www.codeply.com/go/GjrVfpcyEv
scroll down to select and watch the navbar disappear

Gordon Suchomski
Senior Manager EFB & Flight Documentation
IT-Systementwicklung - Luftfahrtsysteme

Air Berlin PLC & Co. Luftverkehrs KG
Saatwinkler Damm 42-43
13627 Berlin

airberlin group

Tel: +49 (0)30 3434 4017
Fax: +49 (0)30 3434 4449
gsuchomski@airberlin.com<mailto:gsuchomski@airberlin.com>
http://www.airberlin.com

Von: Chris Rebert [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. September 2016 00:52
An: twbs/bootstrap
Cc: Suchomski, Gordon; Comment
Betreff: Re: [twbs/bootstrap] Bootstrap Problem with Pagination (#20761)


Bootstrap 3 is no longer officially supported. Please use the community forums linked in the README, e.g. StackOverflow, for further assistance. Thanks.
