### ISSUE TITLE
meteor add twbs:bootstrap@=4.0.0-alpha.4 does not work

### ISSUE THREAD

**Issue by rahulserver** [twbs/bootstrap#20771]
In the README.md the instructions for meteor say that we need to execute command 
`meteor add twbs:bootstrap@=4.0.0-alpha.4`
This gives error that no such package exists.

As per `meteor show --show-all twbs:bootstrap` the latest version is 4.0.0-alpha.2

So README.md needs to show proper version for meteor installation.

**Comment by cvrebert** [comment]
Duplicate of #20389.
