### ISSUE TITLE
More flexbox utility classes

### ISSUE THREAD

**Issue by intellix** [twbs/bootstrap#20776]
So I'm using BS4 with flex enabled and I'm typically copy/pasting angular material utility classes into my project to make use of those for building the whole layout and doing flex magic like vertical and horizontal alignment: `layout-fill, layout-row, layout-column, layout-space-between-center` etc. Is there any plan to include a range of flex utility classes in BS4?

Minimal pen: http://codepen.io/intellix/pen/ALLJqK
Angular material layout documentation: https://material.angularjs.org/latest/layout/container
Layout code: https://github.com/angular/material/blob/master/src/core/style/layout.scss

**Comment by yshterev** [comment]
+1
Polymer's `iron-flexbox` classes also good - [Plunker demo](http://plnkr.co/edit/xIARqr?p=preview)

**Comment by twbs-lmvtfy** [comment]
Hi @yshterev!

You appear to have posted a live example (http://run.plnkr.co/plunks/xIARqr/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Hella utils added in #21407.
