### ISSUE TITLE
Creating a "Resources" page to feature books & videos

### ISSUE THREAD

**Issue by packtpartner** [twbs/bootstrap#20772]
Hi, 

As Bootstrap is been gaining popularity in Web development and has empowered millions of websites, Packt is proud to publish books on Bootstrap.

This year Packt has published 4 titles on Bootstrap. 3 books and a video
**Books:**
[Bootstrap Site Blueprints Volume](https://www.packtpub.com/web-development/bootstrap-site-blueprints-volume-ii)
[Bootstrap Site Blueprints](https://www.packtpub.com/web-development/bootstrap-site-blueprints)
[Learning Bootstrap 4 - Second Edition](https://www.packtpub.com/web-development/learning-bootstrap-4-second-edition)

**Video:**
[Building a Responsive Application with Bootstrap [Video]](https://www.packtpub.com/web-development/building-responsive-applications-bootstrap-video)

We would appreciate if you could create a Resources page to feature such content. I think it would really help the Bootstrap community and budding developers.

Let me know what you think.

Many thanks

**Comment by cvrebert** [comment]
The Bootstrap Expo already has a Resources page: http://expo.getbootstrap.com/resources/
Feel free to file an issue in the Expo's repository: https://github.com/twbs/bootstrap-expo

**Comment by packtpartner** [comment]
Thanks @cvrebert alot
