### ISSUE TITLE
Card header and footer color not fully filling in header/footer area of card

### ISSUE THREAD

**Issue by Chris-Rios** [twbs/bootstrap#20789]
When working with bootstrap cards, I noticed that the background color of a card header does not completely fill the header area of the the card. For example if you look at the top-left and right corners, the color is not fully filled in, there is an uncolored area between the border of the card and the header color. I've also noticed this behavior for the footer as well, on the bottom-right and bottom-left. Please see https://output.jsbin.com/qekodo for an example, and zoomed in screenshot I've attached below. I am running windows 10, chrome version 53.0.2785.116.

![image](https://cloud.githubusercontent.com/assets/6753611/18762032/426936bc-80d5-11e6-9bbe-bb3b9740cf0d.png)

This seems to be influenced by the value of the border radius, top-left and top-right for header and bottom-left and bottom-right for the footer. These values look like they are too large e.g border radius is .25rem for me, but should be somewhere closer to .2rem.  Let me know if this makes sense or if more clarification is needed.

**Comment by rafalp** [comment]
Isn't this bug with chrome math?

https://bugs.chromium.org/p/chromium/issues/detail?id=491574

**Comment by Chris-Rios** [comment]
I see the same problem in firefox as well, version 49.0.1

**Comment by mdo** [comment]
We likely need to employ some `calc` in there to round it properly. Basically you need to subtract the width of the `border` of the parent (`1px` in this case) from the inner element's `border-radius` (`.25rem` I think).

So, `border-radius: calc(.25rem - 1px);`.

**Comment by Chris-Rios** [comment]
After looking at the v4-dev code a bit, I noticed that this will be fixed with alpha 5. #20667 and  #20672 resolved this issue.
