### ISSUE TITLE
Remove card-block class on cards?

### ISSUE THREAD

**Issue by gilronc** [twbs/bootstrap#20786]
I'm constantly using utility classes(p-a-1, p-a-2, p-a-3) on cards instead of the `card-block` class.  I'm wondering if it might be better to just remove `card-block` and promote the use of the Spacing utility classes.

Eg:  I might have different cards that lists intro information for Employees, News Stories, Events, etc...Most of the different card types have different padding requirements instead of the default 1.25rem that is provided by the card-block class.

This is a prototype of what i'm doing:
```
<div class="container">
  <div class="row">
    
    <div class="col-lg-3">
      <div class="card card-person">
        <div class="p-a-2">
          <img src="http://www.unsplash.it/450/450" class="img-fluid img-circle" />
        </div>
        <div class="p-a-1 card-block text-xs-center">
          <h2 class="h5">John Doe</h2>
          <p>Solid Waste Management and Environment Supervisor</p>
        </div>
      </div>
      
    </div><!--End Row-->
</div><!--End Container-->
```
If this makes sense, i can create a PR with all the necessary changes to the docs and the code.

**Comment by oystersauce8** [comment]
is this issue related to bootstrap?

**Comment by maniarasu** [comment]
your class not effected in bootstrap

**Comment by gilronc** [comment]
@oystersauce8  , yes this is related to the `card-block` class on the boostrap 4 cards component
```
<div class="card">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title">Card title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```

**Comment by mdo** [comment]
> I'm constantly using utility classes(p-a-1, p-a-2, p-a-3) on cards instead of the card-block class. I'm wondering if it might be better to just remove card-block and promote the use of the Spacing utility classes.

`.card-block` clears floats and adds component-specific padding. You can definitely override it, but for structural integrity of the component in isolation of utilities, we'll be keeping it. Utilities are generally for one-offs, modifiers, overrides, or quick-fixes. I don't like building components that depend on them though :).

**Comment by gilronc** [comment]
Sounds Good :)
