### ISSUE TITLE
Any news about btn-responsive like these one?

### ISSUE THREAD

**Issue by mrkongo** [twbs/bootstrap#20783]
Any news about `btn-responsive` like this one?

http://stackoverflow.com/a/19937581/4412054

I wrote an example of what I think:

http://plnkr.co/edit/UobgFbNdwOAOU8JmtssW?p=preview

**Comment by mdo** [comment]
No plans for v4 launch at this point.

**Comment by carmelone** [comment]
But why you close? Can it stay open for the future?
