### ISSUE TITLE
Bottom margin with radio button group

### ISSUE THREAD

**Issue by andreasschiestl** [twbs/bootstrap#20784]
Hi!

I noticed that there is a button margin with radio button groups, but not with normal button groups.

![bildschirmfoto 2016-09-25 um 21 45 54](https://cloud.githubusercontent.com/assets/8170218/18817799/39926792-836a-11e6-876e-e3ef1f823f57.png)

![bildschirmfoto 2016-09-25 um 21 46 32](https://cloud.githubusercontent.com/assets/8170218/18817848/59234d32-836b-11e6-9bb2-d98f1d306f1b.png)

code used for this example
```
<div class="btn-group btn-group-sm" role="group">
    <button type="button" class="btn btn-secondary">Left</button>
    <button type="button" class="btn btn-secondary">Middle</button>
    <button type="button" class="btn btn-secondary">Right</button>
</div>

<div class="btn-group btn-group-sm" data-toggle="buttons">
    <label class="btn btn-secondary">
        <input type="radio" name="options" id="option1" autocomplete="off"> Radio 1
    </label>
    <label class="btn btn-secondary">
        <input type="radio" name="options" id="option2" autocomplete="off"> Radio 2
    </label>
    <label class="btn btn-secondary">
        <input type="radio" name="options" id="option3" autocomplete="off"> Radio 3
    </label>
</div>
```

The bottom margin is created by the label tag.

**Comment by cvrebert** [comment]
Please make a CodePen, JS Bin, or other live example that demonstrates the bug.

**Comment by andreasschiestl** [comment]
Here is a JS Bin example :) https://jsbin.com/yicopuz/2/edit?html,output
