### ISSUE TITLE
Bootstrap 4 navbar toggle icon does not display correctly in Android.

### ISSUE THREAD

**Issue by ve3** [twbs/bootstrap#20787]
Here is the screenshot.
![screenshot_2016-09-26-16-54-28](https://cloud.githubusercontent.com/assets/1568262/18830343/7f21f4ee-840a-11e6-9673-b76ca490c56a.png)

In the red mark. It should be hamburger icon but in Android (Chrome), it is not.

My HTML

```
<nav class="navbar navbar-light bg-faded">
    <div class="container">
        <a class="navbar-brand" href="./">Template</a>
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#bs4-navbar-collapse" aria-controls="bs4-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
            &#9776;
        </button>
        <div class="clearfix hidden-sm-up"></div>

        <div class="collapse navbar-toggleable-xs" id="bs4-navbar-collapse">
            <ul class="nav navbar-nav">
                ...
            </ul>
        </div>
    </div>
</nav>
<!--end navbar header--> 
```

Is there a way to make it display the same icon cross platform? (without any additional css like FontAwesome)

**Comment by patrickhlauke** [comment]
Fix is in next alpha (tl;dr: uses SVG rather than unicode character) https://github.com/twbs/bootstrap/pull/20329
