### ISSUE TITLE
Suggestion: Setting equal height for grid columns in a row

### ISSUE THREAD

**Issue by shellysaju** [twbs/bootstrap#20798]
Currently its showing in different height 
Example:
![bugb](https://cloud.githubusercontent.com/assets/13540432/18880168/a42da252-84f4-11e6-85ae-35d07dc7938a.jpg)

By adding css we can adjust it, but it will be nice to add a bootsrap class and maintain the grid columns height equal and also maintaining button in same vertical line it will be good.

![bugg_bootstrap2](https://cloud.githubusercontent.com/assets/13540432/18880509/b43a7386-84f5-11e6-93d3-bac863c5fd7a.jpg)

![bugg_bootstrap](https://cloud.githubusercontent.com/assets/13540432/18880129/7e59ec34-84f4-11e6-9dd8-e7aa0f3bc267.jpg)

Hope you make the adjustment and update in coming version.

Thanks and regards
Shelly

**Comment by cvrebert** [comment]
I believe Card Decks already implements what you seek?:
http://v4-alpha.getbootstrap.com/components/card/#decks

**Comment by p-h-i-l** [comment]
I think the problem is, that card decks, hold an infinite amount of cards in one row, if one wants multiple rows of cards of equal hight columns, he would have to add many decks which works, but isn't intuitive...

Or is it possible to clear the floats after X cards with a clearfix? That might work?

**Comment by shellysaju** [comment]
The card looks good(http://v4-alpha.getbootstrap.com/components/card/#decks), but is it possible to maintain button on same alignment.

**Comment by cvrebert** [comment]
> but is it possible to maintain button on same alignment?

If you put the buttons within a Card Footer, probably.

Otherwise, no, not at the framework level. CSS doesn't let you express constraint-based layouts like that. You could set min-height on the image and the paragraph in custom CSS, but such an approach won't handle dynamic content.

**Comment by shellysaju** [comment]
@cvrebert 

> If you put the buttons within a Card Footer, probably.

It sounds promising.

If it work for dynamic content, then it will be cool.

**Comment by mdo** [comment]
Switching to the flexbox grid—or using table styles—will help you achieve this. Outside that, there are no plan for equal height columns on the default grid.

**Comment by mredem96** [comment]
I implement this in my  e-commerce website you can see it https://ushop.uz/
