### ISSUE TITLE
Include `from` and `to` indexes in Carousel `slide.bs.carousel` and `slid.bs.carousel` event

### ISSUE THREAD

**Issue by MrCsabaToth** [twbs/bootstrap#20792]
AFAIK it's not included.

**Comment by Johann-S** [comment]
It's a feature request. Any thoughts about this request @bardiharborow ?

**Comment by bardiharborow** [comment]
I don't see why this couldn't be implemented, and it makes sense.

**Comment by Johann-S** [comment]
Yes I have the same opinion.
(Feature label is missing 😄 )
