### ISSUE TITLE
Docs for disabled inline radio/checkboxes

### ISSUE THREAD

**Issue by TheSharpieOne** [twbs/bootstrap#20799]
Similar to #20608, this ticket aims to address the "inline" radio/checkbox which use `form-check-inline`. It was not explicitly pointed out in the previous issue, which is my fault. Rather than reopen it, I am making this new ticket.
The disabled styles between the `form-check` and `form-check-inline` are inconsistent as can be seen in the image below.

![form-check-v-form-check-inline](https://cloud.githubusercontent.com/assets/664714/18887827/d9772d24-84c3-11e6-9853-11229cbe94cd.gif)

The docs do not clearly indicate how to mark a `form-check-inline` as disabled. See this pin for the code used in the image: http://codepen.io/TheSharpieOne/pen/LRLErr?editors=1000

Relevant code: https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/scss/_forms.scss#L241-L243

**Comment by cvrebert** [comment]
It would seem that either `.form-check-inline` is missing the `color: $text-muted;` of its `.disabled .form-check-label` counterpart, or that the markup scheme needs tweaking.
