### ISSUE TITLE
bootrap carousel (keyboard: false) and modal pop up do not mix well 

### ISSUE THREAD

**Issue by ugenegrg** [twbs/bootstrap#20793]
All right, using data attribue or via js, it works, which is prevent keyboard leftarrow-prev/right-arrow-next , but there is an strange issue in my case.
I have disabled the key reaction in carousel which is working fine, but i have a popup in the lets's say 5th slide, and used the bootstrap modal for popup. Now the problem is when bootstrap modal is showing, the keyboard false does not prevent the carousel from sliding? Any help is appreciated. Also tried the solutions to prevent action using event listener and others as below.

`window.addEventListener("keydown", function(e) { // space and arrow keys if([32, 37, 38, 39, 40].indexOf(e.keyCode) > -1) { e.preventDefault(); } }, false);`

By the way my pop modal is outside of the the carousel. It is just triggered from one of the carousel slide.

**Comment by mdo** [comment]
This would be fixed by #20907 or #19058 I think.

**Comment by mdo** [comment]
Closing as referenced PRs were merged.
