### ISSUE TITLE
Pagination Pull-xs-left pull-xs-right classes not working Version 4.0 alpha 4

### ISSUE THREAD

**Issue by CShehan** [twbs/bootstrap#20791]

**Comment by cvrebert** [comment]
Please post a live example (e.g. CodePen, JS Fiddle, etc.) that demonstrates the problem.

**Comment by mdo** [comment]
Closing as we haven't heard anything back.

**Comment by stanuku** [comment]
This is still an issue. pull-xs-right not working

**Comment by cvrebert** [comment]
@stanuku Then please file a new issue based on the template: https://github.com/twbs/bootstrap/blob/v4-dev/ISSUE_TEMPLATE.md

**Comment by cvrebert** [comment]
Also keep in mind that #21238 recently renamed the pull classes.
