### ISSUE TITLE
Non-floating columns in grid system

### ISSUE THREAD

**Issue by Miqueliu** [twbs/bootstrap#20807]
I'm rewriting this issue because @cvrebert ignored [my response](https://github.com/twbs/bootstrap/issues/20757#issuecomment-248851540) (and he did not reopen it):

> If we are in a media query and it is not applying a proper class on a column, by default the full width is reached (like a virtual `col-*-12` class). However, the problem is that **it is not floating** as it should be.

> Considering a portion of the [said particular example](http://getbootstrap.com/css/#grid-example-basic):

> ```html
<div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">.col-md-4</div>
</div>
```

> On a extra small (phones) or small (tablets) devices, children `div`s **have no `float: left`**.

In case of possible doubts:

> ```html
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <div class="col-lg-12">
        <h2>Title 1</h2>
      </div>
      <div class="col-lg-12">
        <h2>Title 2</h2>
      </div>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="row">
      <div class="col-md-12">
        <h2>Title 1</h2>
      </div>
      <div class="col-md-12">
        <h2>Title 2</h2>
      </div>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="row">
      <div class="col-sm-12">
        <h2>Title 1</h2>
      </div>
      <div class="col-sm-12">
        <h2>Title 2</h2>
      </div>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="row">
      <div class="col-xs-12">
        <h2>Title 1</h2>
      </div>
      <div class="col-xs-12">
        <h2>Title 2</h2>
      </div>
    </div>
  </div>
</div>
```

Analyze the height variations.

**Comment by mdo** [comment]
This is intended behavior—there are no floats on grid columns outside their media queries. The margin collapsing is an unintentional side effect, but one that can be combatted in certain situations with v4's utilities.

**Comment by Miqueliu** [comment]
Which utilities?

**Comment by Miqueliu** [comment]
Look [this JSFiddle](https://jsfiddle.net/nsr6vzqk/). In small devices (for example) the only difference between `col-*` columns is the `float: left;` CSS declaration. Why?

**Comment by Miqueliu** [comment]
Because of flex-styled columns in BS4, this issue is particularly for 3rd version. You can appreciate differences between [V3](https://jsfiddle.net/568etd8r/) and [V4 (Beta)](https://jsfiddle.net/a7e3svn1/). Pay attention to content margins.
