### ISSUE TITLE
v4 Navbar tooltip / Tether not working

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#20805]
~~Per https://github.com/twbs/bootstrap/issues/20630 and https://github.com/twbs/bootstrap/issues/20218~~ if you have a fixed navbar and add a tooltip inside of it (on top of a button) it does not work.  I'm using the default `$(function() { $('[data-toggle="tooltip"]').tooltip(); });` usage.

```html
<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  <button class="navbar-toggler bg-inverse pull-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
    <i class="fa fa-bars"></i>
  </button>
  <a class="navbar-brand" href="/">{{config.appName}} <span class="tag tag-success">{{ version }}</span></a>
  <div class="clearfix hidden-lg-up"></div>
  <div class="collapse navbar-toggleable-md" id="navbar-header">
    <ul class="nav navbar-nav">
      <li class="nav-item"><a role="button" data-toggle="tooltip" title="Early-bird discount available" class="btn btn-outline-danger" href="#"><i class="fa fa-book"></i> Book <span class="tag tag-danger text-uppercase">Pre-order</span></a></li>
    </div>
  </div>
</div>
```

It's not working due to the CSS z-index.  Not sure if I need to specify a `data-container` or something else?

**Comment by mdo** [comment]
Have a live example?

**Comment by niftylettuce** [comment]
@mdo Yeah I forgot to do `data-placement="bottom"`, and since it's a navbar I just wasn't seeing it since it went over top of page view.  <https://jsfiddle.net/grL5k5sd/> works fine.

**Comment by twbs-lmvtfy** [comment]
Hi @niftylettuce!

You appear to have posted a live example (https://fiddle.jshell.net/grL5k5sd/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 71, column 3 thru column 164: The ```` aria-controls ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
