### ISSUE TITLE
Linux Centos 5 web server

### ISSUE THREAD

**Issue by Dougjan** [twbs/bootstrap#20806]
Hello
Can anybody tell me if slider "revolution-slider" works with a web server using Linux Centos 5 and Apache? If the slider does work please can I get some help on what must be done on the webserver. The slider works great on my windows 7 PC.
Kind regards
Doug

**Comment by cvrebert** [comment]
Please use the community forums linked in the README (e.g. StackOverflow) for non-bug, non-feature request questions such as this. Thanks.
