### ISSUE TITLE
Avoid the empty div with "Optional: clear cols if their content doesn't match in height" @ v4-alpha

### ISSUE THREAD

**Issue by semmais** [twbs/bootstrap#20804]
Instead using a empty div in markup [like](http://v4-alpha.getbootstrap.com/layout/grid/#example-mobile-tablet-desktop):
```
<!-- Optional: clear the XS cols if their content doesn't match in height -->
<div class="clearfix hidden-sm-up"></div>
```

I suggest something like:
`<div class="row clear-sm-2 clear-md-3 clear-xl-5">`

With some implementation like
```
$max-clear-cols: 5;
@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
  	@for $i from 2 through $max-clear-cols {
  		.clear-#{$breakpoint}-#{$i} >*:nth-child(n) { clear:none; }
    	.clear-#{$breakpoint}-#{$i} >*:nth-child(#{$i}n+#{$i+1}) { clear:both; }
  	}
  }
}
```

**Comment by mdo** [comment]
You don't need to add an extra clearfix for a row that has uneven heights—the row takes care of that. The only times you need a separate element is when you have more than 12 columns in a row (e.g., you're putting two row's worth of content into a single row) or need to tweak wrapping behavior within the same row at different breakpoints. This adds too many new classes to address an already solved problem.

Thanks though!
