### ISSUE TITLE
Is there any React-Bootstrap version that the Bootstrap team officially endorse? 

### ISSUE THREAD

**Issue by wzup** [twbs/bootstrap#20817]
There are:
https://github.com/react-bootstrap/react-bootstrap
https://github.com/reactstrap/reactstrap

I didn't immerse too deep into them yet, at first would like to know if the official Bootstrap team aware about those projects, do they somehow support or recommend any of them? What do the Bootstrap team recommend as a React-Bootstrap framework, if there's any?

**Comment by rafalp** [comment]
Hey, I'm using Bootstrap with React frequently in my projects, and I've never did this using "react-bootstrap" or similiar package. Could you please explain what issues those solve?

**Comment by waywaaard** [comment]
@rafalp: Well the use no jQuery.

**Comment by mdo** [comment]
No recommendations from us I'm afraid :).
