### ISSUE TITLE
Toogle

### ISSUE THREAD

**Issue by spdpiyush** [twbs/bootstrap#20815]
Toggle Not Working Properly , How To Solve It.

**Comment by pkozlowski-opensource** [comment]
> Toggle Not Working Properly , How To Solve It.

You could start by providing an adequate bug report: https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md#bug-reports

**Comment by mdo** [comment]
Closing until we hear back with a more specific question.
