### ISSUE TITLE
Some text/letters are clipped when using .custom-select

### ISSUE THREAD

**Issue by niteraven78** [twbs/bootstrap#20810]
See the screenshot below- particularly the lowercase g. It seems to be caused by -webkit-appearance: none;

![custom-select](https://cloud.githubusercontent.com/assets/21128070/18938285/bf05c59c-85c5-11e6-9978-bf209dda8ffe.PNG)

Windows 10/Chrome latest version

**Comment by sa7bi** [comment]
same here :( 
To solve it, I had to add a custom `height`

**Comment by dumb** [comment]
Can confirm this also happens in the latest OSX Chrome (v53.0.2785.143), but not in the latest Safari or Firefox.

Throwing `.custom-select { height: 2.5rem; }` into the stylesheet works as a band-aid for the normal size (thanks sa7bi), but form-control-sm is still cut off & might need some padding adjustment.

**Comment by gregpettit** [comment]
I still see this in Beta 2. Possible regression? Per the original discussion thread, setting custom heights fixes the issue, whether smaller (line-height: 1) or larger (line-height: 1.3). For whatever reason it's 1.25 that seems to cause the scenario along with Segoe UI (the default for Windows, I believe?).
