### ISSUE TITLE
Select option ugly on Firefox and Safari on mac

### ISSUE THREAD

**Issue by TheBuzzer67** [twbs/bootstrap#20820]
Hi!

Just developping my new web site with the v4-alpha.4 and Select option doesn't look like in opera and Google Chrome!?

Watch the code is simple in the test! The Chrome look is better for Bootstrap

[http://www.zzyb.biz/TestSelectOption.html](url)

Firefox-49.0-Mac 10.12:
![firefox-49 0-mac 10 12](https://cloud.githubusercontent.com/assets/4350789/19016200/5ae9a09c-87e1-11e6-8498-be24e96c01c2.png)

Opera-40.0.2308.75-Chrome-Version 49.0.2623.110 (64-bit)-Mac OS X 10.12.0 64-bit:
![opera-40 0 2308 75-chrome-version 49 0 2623 110 64-bit -mac os x 10 12 0 64-bit](https://cloud.githubusercontent.com/assets/4350789/19016199/5ae5aa96-87e1-11e6-9464-c28d01866790.png)

Safari-Version 10.0 (12602.1.50.0.10)-Mac 10.12:
![safari-version 10 0 12602 1 50 0 10 -mac 10 12](https://cloud.githubusercontent.com/assets/4350789/19016201/5aeb3092-87e1-11e6-8489-ba008d94a534.png)

**Comment by mdo** [comment]
There is little we can do for this, sorry. Firefox doesn't style select items very well. Your best bet is to use the custom select element in v4.
