### ISSUE TITLE
Button on ms edge don't keep it css position

### ISSUE THREAD

**Issue by maw2be** [twbs/bootstrap#20822]
I spot some problem with MS edge and bootstrap 3.3.7
Buttons have setup static position by css. on all browser it's works only   on edge I have problems.
looks on [this link](http://stackoverflow.com/questions/39807077/bootstrap-and-ms-edge-bug)
I try this on pure code and get the same error. How to fix it? Is this possible to fix on edge?

**Comment by patrickhlauke** [comment]
> I try this on pure code and get the same error.

so this points to the fact it's an Edge bug, rather than a Bootstrap bug? in that case, this is the wrong place to ask. Suggest going to StackOverflow or similar
