### ISSUE TITLE
collapse uses display:none vs display:block, shouldn't it be using visibility:visible/hidden/collapse

### ISSUE THREAD

**Issue by iwhp** [twbs/bootstrap#20838]
I have an issue with a `<table>` which should be set to `width:100%`.
When I use the `collapse `component, the `width:100%` is lost during collapsing.
I would assume that setting `display:table` would be a solution, but since collapse uses display for showing and hiding I cannot use `display:table`.
Shouldn't Bootstrap use `visibility` anyway.

**Comment by cvrebert** [comment]
Approximate duplicate of #18060.
