### ISSUE TITLE
Responsive utility "xs" not working

### ISSUE THREAD

**Issue by isaacg11** [twbs/bootstrap#20831]
The responsive grid class "xs" is not working on mobile, furthermore it seems that Bootstrap is preventing the viewport to be loaded in and adjusted to mobile screens.

**Comment by bardiharborow** [comment]
Please provide [a reduced test case](https://css-tricks.com/reduced-test-cases/).

**Comment by mdo** [comment]
Pretty sure it works 😁 but in case it's not, please do holler here and we can reopen this! <3
