### ISSUE TITLE
bootstrap 3.3.7 examples - downloaded the bootstrap repository - navbar link broken: File not found

### ISSUE THREAD

**Issue by KerryRuddock** [twbs/bootstrap#20839]
I downloaded and installed the bootstrap 3.3.7 repository to my windows 7 pc. 

Using windows explorer, I select from examples folder,  this navbar html file to run locally:

**bootstrap3.3.7/docs/examples/navbar/index.html**

My Chrome browser displays the navbar example,  The example contains a button link:
 _View navbar docs >>_ 

When I click on the above button, I get a broken link with the message FILE NOT FOUND
The navbar index.html contains this markup for the broken link:
`<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs »</a>`

I installed everything I needed to install grunt and run 'grunt docs' as I thought I might have missed
this step to run the examples locally.  Am I doing something wrong or is there a bug within the
**bootstrap3.3.7/docs/examples/navbar/index.html** ?

**Comment by zacechola** [comment]
Bootstrap 3 is no longer maintained. You can read more about the reasoning from Mark's post at #20631. That said, someone in [Slack or IRC](https://github.com/twbs/bootstrap#community) may be able to help you out.

**Comment by KerryRuddock** [comment]
That is too bad considering bootstrap 4 is still in its alpha version and not beta.  Topic now closed.
