### ISSUE TITLE
Some widgets use hardcoded breakpoint names for their media queries

### ISSUE THREAD

**Issue by judowalker** [twbs/bootstrap#20833]
This issue is similar to https://github.com/twbs/bootstrap/issues/20548, however in my case I want to change the breakpoint names as follows:
```scss
$grid-breakpoints: (
  xxs: 0,
  xs: 544px,
  sm: 768px,
  md: 992px,
  lg: 1200px
);
```
This seems to work as far as generating the columns. However, some of the Bootstrap scss files call the `media-breakpoint-*` mixin with a breakpoint name that no longer matches my breakpoint names. For example, `_carousel.scss` calls `@include media-breakpoint-up(sm)` which results in 768px in my case instead of 544px. I would have to manually change it to `@include media-breakpoint-up(xs)` for it to be correct with my breakpoint names.

Since the number of breakpoints are the same, perhaps some type of mapping can be used to map the mixin argument to the grid-breakpoint (e.g. `@include media-breakpoint-up(sm)` maps to xs: 544px in `$grid-breakpoints`).

**Comment by cvrebert** [comment]
> Since the number of breakpoints are the same

But we can't rely on that in the general case.
No good, general solution comes to mind.

CC: @mdo

**Comment by mdo** [comment]
Yeah I've struggled to think of a way to do this right... I don't know that there is one that scales well without adding too many complications to the source code. I'm open to more suggestions on how to make it work, but otherwise I think it might be outside our scope unfortunately.

**Comment by judowalker** [comment]
Could it work by passing an index instead of the hardcoded name like `media-breakpoint-up(1)` which refers to the second breakpoint in `$grid-breakpoints`?

**Comment by judowalker** [comment]
@mdo @cvrebert I think I have a decent solution. The `_variables.scss` can include variables for the breakpoint names, something like:
```scss
$grid-breakpoint-xs: xs !default;
$grid-breakpoint-sm: sm !default;
$grid-breakpoint-md: md !default;
$grid-breakpoint-lg: lg !default;
$grid-breakpoint-xl: xl !default;
```
Then you can use the variable instead of the hard-coded name: `media-breakpoint-up($grid-breakpoint-sm)`.
This would allow the developer to overwrite the breakpoint names:
```scss
$grid-breakpoint-xs: xxs;
$grid-breakpoint-sm: xs;
$grid-breakpoint-md: sm;
$grid-breakpoint-lg: md;
$grid-breakpoint-xl: lg;
```

**Comment by judowalker** [comment]
@mdo @cvrebert could you take a look at my proposed solution?
https://github.com/twbs/bootstrap/issues/20833#issuecomment-251891823

It scales well and doesn't add any complications.

**Comment by Andrew-Dyachenko** [comment]
The same problemm:
![2017-08-24 15-51-04](https://user-images.githubusercontent.com/10127643/29667206-2dfa73cc-88e4-11e7-9630-8ddd30667928.png)
The code below working with **bootstrap 4.0.0-alpha.6**, but not working with **bootstrap 4.0.0-beta**
![2017-08-24 15-59-08](https://user-images.githubusercontent.com/10127643/29667474-349c1dec-88e5-11e7-9617-7ea700d585c2.png)
The solution below not working with **bootstrap 4.0.0-beta**
![2017-08-24 16-00-11](https://user-images.githubusercontent.com/10127643/29667530-6aac69f0-88e5-11e7-9eac-97530a914534.png)
