### ISSUE TITLE
[BUG] card-img-top

### ISSUE THREAD

**Issue by SoaringRadio** [twbs/bootstrap#20848]
I believe this is in all browsers.
I'm using 4.0.0-alpha.4 via cdn
--------------
When I use an image with the class "card-img-top" the image does not stay within the card.
This is because it doesn't have a defined width.
The"card-img-top" class needs to have a width of 100%.
--------------
Example of buggy code: https://jsfiddle.net/1v3dLj05/5/
Example of fixed code:   https://jsfiddle.net/1v3dLj05/4/

**Comment by twbs-lmvtfy** [comment]
Hi @SoaringRadio!

You appear to have posted a live example (https://fiddle.jshell.net/1v3dLj05/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 7 thru column 54: No space between attributes.
* line 31, column 7 thru column 64: Quote ```` " ```` in attribute name. Probable cause: Matching quote missing somewhere earlier.
* line 31, column 7 thru column 150: Bad value ```` <link rel= ```` for attribute ```` src ```` on element ```` script ````: Illegal character in path segment: ```` < ```` is not allowed.
* line 31, column 7 thru column 150: Attribute ```` stylesheet" ```` not allowed on element ```` script ```` at this point.
* line 31, column 7 thru column 150: Attribute ```` href ```` not allowed on element ```` script ```` at this point.
* line 31, column 153 thru column 161: The text content of element ```` script ```` was not in the required format: Expected space, tab, newline, or slash but found ```` " ```` instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @SoaringRadio!

You appear to have posted a live example (https://fiddle.jshell.net/ye1ba5wj/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 7 thru column 54: No space between attributes.
* line 31, column 7 thru column 64: Quote ```` " ```` in attribute name. Probable cause: Matching quote missing somewhere earlier.
* line 31, column 7 thru column 150: Bad value ```` <link rel= ```` for attribute ```` src ```` on element ```` script ````: Illegal character in path segment: ```` < ```` is not allowed.
* line 31, column 7 thru column 150: Attribute ```` stylesheet" ```` not allowed on element ```` script ```` at this point.
* line 31, column 7 thru column 150: Attribute ```` href ```` not allowed on element ```` script ```` at this point.
* line 31, column 153 thru column 161: The text content of element ```` script ```` was not in the required format: Expected space, tab, newline, or slash but found ```` " ```` instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by melonista** [comment]
Thanks for this.... I spent way too much time trying to figure this out...
