### ISSUE TITLE
v3 Accordion effect breaks when using toggle methods

### ISSUE THREAD

**Issue by QuantumHive** [twbs/bootstrap#20841]
I'm using the [Bootstrap 3 Collapse Accordion Example][1].  
I've noticed that when using the javascript `.collapse()` methods, the *accordion* effect seems to be acting unexpected.
See this [simple jsfiddle example][2].

Here I'm using `$('#collapseOne').collapse('toggle');`. Why? Because to demonstrate the following behavior:

- Initially because of this piece of JavaScript, **panel 1** gets expanded.
- Clicking on **panel 2** gives us the accordion effect as one would expect.
- Clicking back on **panel 1** gives an *unexpected behavior* in that both panels now are expanded.

Now if you **remove** the javascript and execute the following steps:

- Click on **panel 1** to expand
- Click on **panel 2** to get the *accordion effect*.
- Clicking on **panel 1** again, still gives us the *accordion effect*.

The *observation* here is that when using the `.collapse('toggle')` method, the *accordion effect* seems to be broken?

Would one expect this to break or might this be a bug?

  [1]: http://getbootstrap.com/javascript/#collapse-example-accordion
  [2]: https://jsfiddle.net/x7j58rj1/21/

**Comment by cvrebert** [comment]
Closing per #20631. v3 is no longer supported.
