### ISSUE TITLE
Docs refer to "compiled flexbox variation" of CSS on download page that doesn't yet exist

### ISSUE THREAD

**Issue by CharlesWiltgen** [twbs/bootstrap#20844]
[Getting Started > Flexbox](http://v4-alpha.getbootstrap.com/getting-started/flexbox/) notes that: "Alternatively, if you don’t need the source Sass files, you may swap the default Bootstrap compiled CSS with the compiled flexbox variation. Head to the download page for more information."

Currently, neither the [download page](http://v4-alpha.getbootstrap.com/getting-started/download/) or the Bootstrap CDN info on the front page link to the compiled flexbox variation.

This would be handy to have, assuming that the flexbox variation of the Bootstrap CSS is in as good shape as the non-flexbox variation.

**Comment by cvrebert** [comment]
X-Ref: #18568

**Comment by wolfy1339** [comment]
This issue is fixed already by mdo in v4-dev

**Comment by mdo** [comment]
"Custom builds" are in the `dist` folder now, as well as the ZIP we attach to our releases. Docs update to fix the copy coming in #20878.
