### ISSUE TITLE
[Firefox] Touch event support has been re-enabled on Windows desktop

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#20847]
https://www.fxsitecompat.com/en-CA/docs/2016/touch-event-support-has-been-re-enabled-on-windows-desktop/

**Comment by mdo** [comment]
Unsure if we should be doing anything for this on our end?

**Comment by patrickhlauke** [comment]
i don't think so, but i'll double-check if any of our components misbehave

**Comment by patrickhlauke** [comment]
Two areas where this (as well as a recent change in Chrome, where touch events are exposed on touch-enabled desktop machines, like Surface 3) affects us.

- `dropdown.js` behavior to add a backdrop on touch to work around an iOS event bubbling/delegation hack (reworked in #22426)
- `carousel.js` does not add the mouse listeners to pause the carousel when the user is over it when touch is present (which means on touch-enabled laptops/desktops, or if user has mouse paired with a touch device like Android phone, the carousel never pauses even on `mouseover` - working on a fix for that just now)
