### ISSUE TITLE
font-size-sm and small-font-size in v4

### ISSUE THREAD

**Issue by bradly** [twbs/bootstrap#20859]
In v4 there are two variables that are named similar and act similar but are different– font-size-sm and small-font-size.

```scss
$small-font-size: 80% !default;
```
```scss
$font-size-sm:   .875rem !default;
```

This was causing some confusion on my team when someone removed `font-size: $font-size-sm` from an element's css in favor of a `.small` class in the html. So couple questions:

1. Is this a bug or as designed?
2. If it is as designed, is there a desire to change something to make it less confusing. 

One change that would allow .small to continue to change things relevant to it's parent but keep text the same as font-size-sm when the parent has a normal height would be to change small-font-size to .875%? Not sure, though.

Anyways, thanks again for all the work on BS4. We've been using it in prod since Jan. and really appreciate all the effort that's gone into making it great.

**Comment by mdo** [comment]
We should consolidate. I think I added the `$font-size-sm` after already having the `$small-font-size`, which is generally for the `<small>` element.

**Comment by mdo** [comment]
Reopening based on https://github.com/twbs/bootstrap/pull/20867#issuecomment-252744421

**Comment by mdo** [comment]
Reverted the PR that changed this in #20918.
