### ISSUE TITLE
Text and image in `.navbar-brand` issue

### ISSUE THREAD

**Issue by chesedo** [twbs/bootstrap#20856]
When setting text and an image in the `.navbar-brand` component, the text gets pushed below the image - breaking the navbar - since the image is set to `display: block` in the Sass code. Cases where this would happen is when you want to display the brand name next to its minimal logo.

**Recreate**: Add an image and text to the `navbar-brand` component of a navbar.
**Expected behavior**: That the text be next to the image.
**Current behavior**: The text gets pushed below the image

[Example pen code](http://codepen.io/chesedo/pen/xEYXGV)

**Comment by twbs-lmvtfy** [comment]
Hi @chesedo!

You appear to have posted a live example (http://codepen.io/chesedo/pen/xEYXGV.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 18, column 5: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Improvements made in #19890.
