### ISSUE TITLE
Ability to overwrite the default mixins

### ISSUE THREAD

**Issue by FDiskas** [twbs/bootstrap#20857]
It's imposible to change the mixins. For example - if I want to make the button to be lighter on hover (not darker) its imposible. Because https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss#L42 its hardcoded "darken"
If you separate the mixins and settings from main bootstrap.scss it should be possible to pass customized mixins. The sass will use the last defined mixin. So this will solve a problem.

```
@import 'bootstrap_settings';
@import 'my_mixins/buttons';
@import 'bootstrap';
```

For more details of the problem please check: http://stackoverflow.com/a/12761579/175404

**Comment by mdo** [comment]
We won't be switching up the import order, but this is totally possible for you to do by modifying the `bootstrap.scss` imports to suite your needs.

**Comment by FDiskas** [comment]
Ok, but why hardcoded `darken()`

**Comment by mdo** [comment]
There's another issue for tracking that. See #21037.
