### ISSUE TITLE
Add vertical-align utilities

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#20866]
For example, `.v-align-middle` and what not.

**Comment by craigstroman** [comment]
Is this something that's being worked on or that needs to be worked on?

**Comment by mdo** [comment]
Slated for v4.1, not currently done or in progress on my end.

**Comment by craigstroman** [comment]
I would be interested in taking this up if it hasn't been assigned to anyone yet.

**Comment by stuyam** [comment]
I made this a little while ago with flexbox. It isn't perfect but may give more inspiration: http://stuyam.github.io/align.css

I love the idea of these utilities, maybe it would resemble the margin and padding helpers. Like ```.align-y-center``` or ```.align-x-right``` and you could combine them for something like ```.align-y-center.align-x-right```.

And just like the margin and padding helpers you could do ```.align-a-center``` to align in the x and y direction both to the center.
