### ISSUE TITLE
[Firefox] Prefixed CSS3 multi-column properties will be removed & unprefixed

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#20879]
https://www.fxsitecompat.com/en-CA/docs/2016/prefixed-css3-multi-column-properties-will-be-removed/

**Comment by mdo** [comment]
I think this will get updated on our end whenever we update our Autoprefixer settings. Otherwise there's nothing to change on our end since we don't write prefixes anymore.
