### ISSUE TITLE
Starter template misses sha384 prefix in integrity attributes

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#20888]
Documentation bug @ https://v4-alpha.getbootstrap.com/getting-started/introduction/#starter-template

Chrome fails to verify the integrity of the Bootstrap files from the starter template. Both are missing the `sha384-` prefix. Use values from home page https://v4-alpha.getbootstrap.com/ instead.

**Comment by bardiharborow** [comment]
This was supposed to have been fixed in #20694. Not sure what went wrong there.

**Comment by mdo** [comment]
We'll get this addressed when Alpha 5 ships since it's solved in `v4-dev`.
