### ISSUE TITLE
Why event.preventDefault() in tab

### ISSUE THREAD

**Issue by sarbbottam** [twbs/bootstrap#20883]
>Before opening an issue:

>- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)

Did not find any related exting issue, please excuse me if I have recreted a duplicate issue, it is completely unintentional.

>- [Validate](https://validator.w3.org/nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems

Not applicable

>- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs

It is highly reduced and to the point.

>- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Referred 

>When asking general "how to" questions:

>- Please do not open an issue here
>- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

Not an "how to" issue but "why" issue.

>When reporting a bug, include:

>- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)

Mac OS X (issue not related to OS)

>- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

Chrome latest (issue not related to Browser)

>- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

Why `event.preventDefault()` at [v4-dev/js/src/tab.js](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js#L256)

I have been checking out https://yarnpkg.com/en/docs/install, and found an interesting implementation of `tab/panel`, digging further I found it to be bootstrap-v4 tab.

Here are my thoughts:
* no `role="tabpanel", `role="tab", `role="tablist"` have been used
* no `aria-controls`
* no `aria-selected`
* no support for `left/right/up/down arrow keys`
* use of internal link
* behavior almost similar† to jump links
* visually looking like tab
* full keyboard support (as the behavior is similar to jump link)
* great with screen reader (Safari/VoiceOver)
* nice use of `aria-expanded`

IMHO which is great, less is more, simplicity wins. By far this is the best implementation I have seen. You have presented `tab` by not creating [tab](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel)

**One concern though.**

†There is no way, I could share a specific tab link w/ anyone due to `event.preventDefault()` at [v4-dev/js/src/tab.js](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js#L256).

The `#hash` never gets added to the `URL`.

However if I remove/comment out the `event.preventDefault()` at [v4-dev/js/src/tab.js](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js#L256), it works as desired, even aligning the corresponding container to the top of the view port.

So I am wondering what has been the reason behind `event.preventDefault()` at [v4-dev/js/src/tab.js](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js#L256).

I could not find any breaking behavior, could you please validate and remove it, if there is no specific reason behind it?

>When suggesting a feature, include:

>- As much detail as possible for what we should add and why it's important to Bootstrap
>- Relevant links to prior art, screenshots, or live demos whenever possible

Please refer the screencast at https://www.youtube.com/watch?v=2g2pH-JbljE

Thanks!

**Comment by cvrebert** [comment]
> There is no way, I could share a specific tab link w/ anyone [...]
> The #hash never gets added to the URL

Setting aside the preventDefault aspect of the issue, we don't attempt to implement such link-able tabs because it's not feasible to do so at the generic framework level with sufficient robustness. A tab might be nested inside other tabs, collapsibles, or even third-party or custom widgets, which would have to be opened in order for the tab to become visible. A tab might be generated by JS based on AJAX data and thus not exist at initial-page-load time. Your page might use a JS framework which wants to control URL routing itself. Etc...

**Comment by sarbbottam** [comment]
>it's not feasible to do so at the generic framework level with sufficient robustness. ...

@cvrebert very through reasoning, I could not have listed it any better.

My: 💵 0.02. 
Since with JS (bootstrap.js) the tabs behave as jump links, it might have been better to retain the same functionality. However as mentioned by you there could be multiple scenario, where this might not be desired.

Could the `event.preventDefault()` no be executed if an user prefers, i.e. then can opt out? May be wrap it in a condition or something like that? Is that possible?

**Comment by sarbbottam** [comment]
>Could the `event.preventDefault()` be executed on user's preference? May be wrap it in a condition or something like that? Is that possible?

Please feel free to close the issue, if it seems irrational w/ the project's scope. Thanks!

**Comment by mdo** [comment]
Closing out since we won't be making any changes here <3.
