### ISSUE TITLE
pull-sm-right

### ISSUE THREAD

**Issue by LeahPike** [twbs/bootstrap#20885]
**Version: 4.0.0-alpha.4**

I had used **pull-sm-right** but it doesn't seem to exist in the latest build?

**Comment by bardiharborow** [comment]
It works for me. Please provide a test case so we can try to help you.

**Comment by LeahPike** [comment]
If I use the following the text is displayed on the right of the container.

```
<div class="container">
    <div class="pull-right">Float right on all viewport sizes</div><br>
</div>
```

If I use the following no matter the size of the view port, the text is never on the right of the container.
```
<div class="container">
    <div class="pull-sm-right">Float right on viewports sized SM (small) or wider</div><br>
    <div class="pull-md-right">Float right on viewports sized MD (medium) or wider</div><br>
    <div class="pull-lg-right">Float right on viewports sized LG (large) or wider</div><br>
    <div class="pull-xl-right">Float right on viewports sized XL (extra-large) or wider</div><br>
</div>
```

**Comment by bardiharborow** [comment]
It works correctly in [this JS Bin](http://jsbin.com/cuvifozasu/edit?html,output). Please ensure you are actually using the version of Bootstrap you think you are, because `.pull-right` is a v3 class and if it works then you would appear to be using v3.

**Comment by LeahPike** [comment]
Strange, the package.json inside node_modules/boostrap is saying version "4.0.0-alpha.4".

Code like the following works perfectly though 😕 

```
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      One of three columns
    </div>
    <div class="col-sm-4">
      One of three columns
    </div>
    <div class="col-sm-4">
      One of three columns
    </div>
  </div>
</div>
```

**Comment by LeahPike** [comment]
Just did a search and saw the following:, seems it has been removed.

![image](https://cloud.githubusercontent.com/assets/6124100/19313916/1519ade8-9090-11e6-8fde-ce64460d7060.png)

**Comment by patrickhlauke** [comment]
closing, as the various `pull-XX-right` work correctly in 4.0.0-alpha4 as per http://jsbin.com/cuvifozasu/edit?html,output

and yes, `pull-right` was removed, so it should NOT work anymore in that version of bootstrap.
