### ISSUE TITLE
Slight improvement to offcanvas example

### ISSUE THREAD

**Issue by niteraven78** [twbs/bootstrap#20899]
To account for negative margins on rows a change to margins on active oncanvas row needs to be made. This will fix the offcanvas column/sidebar margin when it comes into view.

.row-offcanvas-left.active {
    left: 50%;
    margin-left: 0;
    margin-right: -30px;
}

.row-offcanvas-right.active {
    right: 50%;
    margin-left: -30px;
    margin-right: 0;
}

**Comment by mdo** [comment]
I believe this was fixed in a recent PR with a bunch of flexbox updates.
