### ISSUE TITLE
THEME in v4

### ISSUE THREAD

**Issue by Favorskij** [twbs/bootstrap#20894]
![mobile](https://cloud.githubusercontent.com/assets/3519169/19349700/2d19e00a-91a0-11e6-9dbd-2d9f12c0db85.png)
![css](https://cloud.githubusercontent.com/assets/3519169/19349687/11241776-91a0-11e6-946d-8f91fd17d096.png)
Before opening an issue: THEME in v4

Windows, Mac OS X, Android, iOS, Win10 Mobile
Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser

**Comment by Favorskij** [comment]
Before opening an issue:Mobile version of the CSS

When asking general "how to" questions:
HTML5
Laravel
Apache 2.4
php.5.6
Windows, Mac OS X, Android, iOS, Win10 Mobile
Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser
![mobile](https://cloud.githubusercontent.com/assets/3519169/19349614/aa126858-919f-11e6-8bfc-219d4a5dfb5b.png)

**Comment by mdo** [comment]
Unclear what you're asking for here, but theming in v4 is much improved from v3.
