### ISSUE TITLE
$form-icon-success / $form-icon-warning / $form-icon-danger: break Magento 1.9.2  CSS Merge

### ISSUE THREAD

**Issue by KickinAss** [twbs/bootstrap#20896]
I know that is a very specific bug, but I used Alpha 2 (or 3?) in my last projects and never happened.

The problem is that a " or '  don't close a string, and so the rest of style is messy (css selectors take as string and so on).
At first http:// (the magento marge translate all path in absolute form) non properly inside in url(""), the  // open a comment, and so the right part of the css line is lost.

I rewrite this variabile as empty and everthing go fine.

I attach the css for debugging.

Nice work, I love Bootstrap 4, and can't go back! 

[ae3006ea4530c692609dd427f25c3117.zip](https://github.com/twbs/bootstrap/files/527660/ae3006ea4530c692609dd427f25c3117.zip)

**Comment by mdo** [comment]
Sounds like a bug on Magento's side I'm afraid. Please open an issue with them so your CSS can compile as intended.
