### ISSUE TITLE
Add background cover functionality in v4

### ISSUE THREAD

**Issue by fur866** [twbs/bootstrap#20893]
**Background**
There should be a cover photo functionality (and possibly other forms of media i.e videos etc but mainly pictures) in bootstrap. This is very easy to do by setting `background-size: cover` on body tag. However, the problem with that is on smaller screens you won't get an exact cover page (there would be some white space in that).  Trying to do that in a div and having a same cover for all screen sizes can require a bit of css. The attached two images demonstrate this problem: 

[Image 1 - full browser screen works fine](https://postimg.org/image/kmmcx83qf/)
[Image 2 - browser shrinked both horizontally and vertically and there is some white space at the end of it](https://postimg.org/image/509ulfyjx/)

**What I propose?**
There should be a `.cover` class that would handle that i.e the developer should just say `<div class="cover"></div> <!-- with a background image linked to this div with css"` or even `img class="cover" src="..." />` and it should give the user an image that is scaled to the screen size (which is responsive as well).

**Comment by mdo** [comment]
I don't think we'll be trying to tackle that for everyone by building it into Bootstrap. Having implemented similar things in other projects myself, each time it was rather custom to what else was going on in the page.
