### ISSUE TITLE
Responsive utility classes overlapping near breakpoint

### ISSUE THREAD

**Issue by bobrinch** [twbs/bootstrap#20902]
It seems to me, that the responsive utility classes overlap at the breakpoints. If for example I have:

```
<div class="hidden-lg-down">
   This is XL
</div>
```

```
<div class="hidden-md-down hidden-xl-up">
   This is LG
</div>
```

Then, when making the browser the exact width of the breakpoint between xl and lg, I see both texts "This is XL" and "This is LG".

Same for LG-MD, MD-XS.

I am using Google Chrome latest version on Windows 7.

**Comment by mdo** [comment]
Have no problems using this with the latest code in `v4-dev`. Make sure you're up to date with the latest code there and if you're still hitting this problem, please share a JS Bin link demoing the issue.

**Comment by bobrinch** [comment]
Please have a look at this JS Bin:

https://jsbin.com/sabedowija/edit?html,console,output

If you make the Output window exactly 1199 pixels in width, you will see:
