### ISSUE TITLE
No Gruntfile.js in Sass Bootstrap 3.3.7 Download

### ISSUE THREAD

**Issue by rubyframework** [twbs/bootstrap#20904]
I downloaded the Sass version of Bootstrap 3.3.7 at 1:45pm PST and there was no Gruntfile included in the download. I then repeated 5-7 times in different browsers, and still no Gruntfile included. 

Not sure if this is a bug, or if I'm just missing the obvious, but this is the first time I have run into this problem.

**Comment by mdo** [comment]
Please open in the `bootstrap-sass` repo for that. No guarantees that we'll change this given v3.3.7 isn't being worked on anymore.
