### ISSUE TITLE
card-columns should be responsive

### ISSUE THREAD

**Issue by rocifier** [twbs/bootstrap#20905]
Can card-columns have responsive variants? I can't set the number of columns on different device widths without doing custom media queries.

**Comment by mdo** [comment]
Maybe in the future, but not for v4.0.

**Comment by mdo** [comment]
Closing as dupe of #20321.

**Comment by shivampaw** [comment]
I think this needs to be done as a priority. It defeats the point of cards and it ruins the responsiveness.

**Comment by rocifier** [comment]
FYI this isn't a dupe of #20321 - that feature request is about card-deck this one is about card-columns. Anyway, I just question the usefulness of releasing 3 hard-coded columns in final production v4 - I mean, why 3? and for all devices?

**Comment by ayoubkhan558** [comment]
Try This 
https://codepen.io/migli/pen/OQVRMw
