### ISSUE TITLE
card-columns breaking because of position: relative

### ISSUE THREAD

**Issue by rocifier** [twbs/bootstrap#20906]
My cards, when used inside of card-columns, only fill two of the three columns unless I change the card class to have position: static. Unfortunately this is a full website so I don't have a simple example right now.

Recommended: set default card position attribute to static.

**Comment by mdo** [comment]
Can't help without a reduced test case.

**Comment by rocifier** [comment]
I reduced my site down to the minimum possible html and css to break the card columns. Seems it's actually quite a complex issue. It only breaks when I have a combination of: a wrapper div with overflow: hidden, a (fullscreen) menu with z-index: -1 (part of the hidden menu state), and the default card position: relative.

Using bootstrap v4 dev:
http://codepen.io/rocifier/pen/LRrooA

**Comment by mdo** [comment]
Oh, if you want your cards to only be organized into two columns, you need to modify the CSS that controls that. As it stands now, card columns use CSS to organize them automatically into three columns. Customize that and you'll be alright.

**Comment by rocifier** [comment]
After some research I think the issue here was that I shouldn't have been using a negative z-index
