### ISSUE TITLE
Multiple accordions with different data-parent collapse each other

### ISSUE THREAD

**Issue by martijn-basesoft** [twbs/bootstrap#20923]
In bootstrap 4 alpha 4, wIth two different accordions on one page having different data-parent's, I would expect them to collapse indepdent of each other. However, the first accordion collapse panels in the second and visa versa. 

See demo at http://codepen.io/anon/pen/JRaZyd

This example is based on the original documention at http://v4-alpha.getbootstrap.com/components/collapse/#accordion-example

**Comment by twbs-lmvtfy** [comment]
Hi @martijn-basesoft!

You appear to have posted a live example (http://codepen.io/anon/pen/JRaZyd.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 62, column 5 thru column 58: Duplicate ID ```` headingOne ````.
* line 75, column 5 thru column 58: Duplicate ID ```` headingTwo ````.
* line 88, column 5 thru column 60: Duplicate ID ```` headingThree ````.
* line 69, column 5 thru column 108: The ```` aria-labelledby ```` attribute must point to an element in the same document.
* line 82, column 5 thru column 105: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by martijn-basesoft** [comment]
Updated demo: http://codepen.io/anon/pen/JRaZyd

**Comment by mdo** [comment]
Can you try with the latest from `v4-dev`? We merged some changes recently to the collapse plugin.

**Comment by Johann-S** [comment]
Duplicate : https://github.com/twbs/bootstrap/issues/18824

**Comment by mdo** [comment]
Closing as duplicate then! Thanks @Johann-S.
