### ISSUE TITLE
SASS Compile error with Gulp

### ISSUE THREAD

**Issue by ryanbuiltthat** [twbs/bootstrap#20924]
I enabled the `flex` variable in the `_variables.scss` before first compiling after installation using Bower. But I get an error about incompatible units. Here's the error:

```
bower_components\bootstrap\scss\_variables.scss
[Error: Incompatible units: 'rem' and 'px'.
        on line 343 of bower_components/bootstrap/scss/_variables.scss
>> $input-height:                   (($font-size-root * $line-height-base) + ($in
   -----------------------------------^
```

I tried to change it to $font-size-root which is a pixel definition and still run into this error.

**Comment by wolfy1339** [comment]
What version or commit are you using?

**Comment by mdo** [comment]
Make sure you have the latest code from `v4-dev` and you should be fine. That line is now:

```scss
$input-height:                   (($font-size-base * $line-height-base) + ($input-padding-y * 2)) !default;
```

**Comment by ryanbuiltthat** [comment]
I just pulled it from bower an hour before I posted this. That line is failing the only way I could make the build finish was hard coding in values.

**Comment by mdo** [comment]
Hmm, the latest code in v4-dev though doesn't match your quoted code in the opening comment. Are you pulling in the latest *release* or the latest commit?

**Comment by rrapstine** [comment]
I know this is closed, but using `npm i bootstrap@4.0.0-alpha.5` still gives this error. If there is a more current way to install via npm I haven't found it posted anywhere.

**Comment by datashaman** [comment]
I've hit the same error when trying to switch Laravel's version to v4. Read here if you are in the same boat.

https://laracasts.com/discuss/channels/laravel/bootstrap-4-alpha-w-laravel-51-also-asking-tips/replies/193627

**Comment by ngankt2** [comment]
In /node_modules/bootstrap/scss/_variables.scss
change $font-size-base: 14px;  to $font-size-base:1rem;
it worked

**Comment by crantron** [comment]
@ngankt2 changing something within node_modules is never a solution. You'd have to override it within your projects theme.
