### ISSUE TITLE
Input addon incorrect vertical alignment with flex enabled

### ISSUE THREAD

**Issue by KyleNeedham** [twbs/bootstrap#20927]
When `enable-flex` is set to true there is no `input-addon` vertical alignment.

```
bootstrap: ^4.0.0-alpha.4
OS: Ubuntu 16.0.4 LTS
Browsers:
    Chrome 54.0.2840.59 (Official Build) (64-bit)
    Firefox 49.0
```

Example with flex enabled
---

`enable-flex: true`
![image](https://cloud.githubusercontent.com/assets/4059001/19477315/6ff0034e-9535-11e6-904d-db78ee4b121c.png)
Reduced test case: https://jsbin.com/fimigirefu/edit?html,output
*I had to embed the built CSS into this bin, since I couldn't find a CDN with flex enabled. It was built using the 4.0.0-alpha.4 bootstrap release and no other sass included.*

Example without flex enabled
---

`enable-flex: false`
![image](https://cloud.githubusercontent.com/assets/4059001/19477268/3c9d4eca-9535-11e6-8d54-3ca2598148dd.png)
Reduced test case: https://jsbin.com/yoyagecifo/edit?html,output

**Comment by tomlutzenberger** [comment]
Could you provide a reduced test case so that other people can test and confirm if it's a bug?

**Comment by KyleNeedham** [comment]
@tomlutzenberger I have added links for each test case.

**Comment by tomlutzenberger** [comment]
The first link is missing the CSS.

**Comment by KyleNeedham** [comment]
@tomlutzenberger https://jsbin.com/fimigirefu/edit?html,css,output Here's a link with the CSS tab clicked

**Comment by tomlutzenberger** [comment]
It seems to behave different with included CSS and a CSS file.
Delete the CSS in the tab and include the file to make it work.

**Comment by KyleNeedham** [comment]
@tomlutzenberger 

CSS in the tab is bootstrap compiled with `enable-flex: true`.
CSS from the CDN is compiled with the default `enable-flex: false`.

Hence the title and original comment explaining that.

**Comment by tomlutzenberger** [comment]
Aaah, I see...
I tried the following:
* wrapped a `span` around the £ sign
* assigned `align-self: center;` and `display: flex;` to `.input-group-addon`

That way it's vertically centered.
But I'm not sure if this is the correct way to do it.
