### ISSUE TITLE
Tooltips not triggering manually

### ISSUE THREAD

**Issue by robertmylne** [twbs/bootstrap#20920]
When I trigger a tooltip via click in the method below. It shows the tooltip, but not because the on click event is triggering it but because the on hover is. Tested on Chrome 53.

```
<div data-toggle="tooltip" data-placement="top" title="" trigger="manual" class="wishlist" data-original-title="Tooltip on top">
    <i class="material-icons">favorite</i>
</div>
```

```
wishlist() {
    $('.wishlist').tooltip('show')
}
```

I can get it the tooltip to only trigger on click and not hover using the below. So I am not sure if this is a bug, feature or I am reading the docs wrong

```
<div data-toggle="tooltip" data-placement="top" title="" class="wishlist" data-original-title="Tooltip on top">
    <i class="material-icons">favorite</i>
</div>
```

```
$('[data-toggle="tooltip"]').tooltip({
    trigger : 'manual'
})

wishlist() {
    $('.wishlist').tooltip('show')
}
```

**Comment by abvalentine** [comment]
You should use `data-trigger="manual"` instead of `trigger="manual"` in `div` tag attributes.

**Comment by mdo** [comment]
Sounds like this was resolved, so closing.
