### ISSUE TITLE
[chrome] [alpha4] card-columns unstable behaviour

### ISSUE THREAD

**Issue by dritir** [twbs/bootstrap#20928]
I am working with rails `gem 'bootstrap', '4.0.0.alpha3.1'` after updating to `gem 'bootstrap', '4.0.0.alpha4'` card-columns became unstable.

A static page would break a card in the middle (img from text like in the Pen below) and start do blink between the correct card position versus this broken one.

I'm using chrome lastest build.

BS4-alpha3.1 Pen:
(http://codepen.io/dritir/pen/gwBxgK)

BS4-alpha4 Pen:
(http://codepen.io/dritir/pen/QKkrGP)

**Comment by mdo** [comment]
Breaking vertically across columns was addressed in #20654. As an aside, there's another bug though in Chrome as reported in #20925.

**Comment by scottgrayson** [comment]
I can confirm that I have the same issue with card-columns in chrome. Works in device mode and firefox
