### ISSUE TITLE
[Chrome] Cards inside .card-columns stack differently

### ISSUE THREAD

**Issue by glebez** [twbs/bootstrap#20925]
In case when there's a few cards inside card-columns container they get distributed differently in Chrome, comparing to FF and Safari.

For example, with 2 cards, in Chrome they stay in the same column and are placed one under another. In FF and Safari they are distributed among 2 columns and displayed side by side.

Adding 3rd card leads to this: In chrome there are 2 cards in the 1st column and 1 in the 2nd. In other browsers there is 1 card in each of 3 columns.

Here is the [reduced test case for 2 cards](http://codepen.io/glebez/pen/QKVokJ).
Here is the [reduced test case for 3 cards](http://codepen.io/glebez/pen/qarzwa).

I'm using BS4 alpha 3, running Mac Os 10.11.6, Chrome 53.0.2785.116 (64-bit), Firefox 49.0.1 and Safari 9.1.2 (11601.7.7).

**Comment by mdo** [comment]
Can you try with the latest from `v4-dev`? I imagine it's something to do with `inline-block` on those elements, but I don't recall seeing this issue before in Chrome.

**Comment by glebez** [comment]
Same behaviour with the v4-dev css: http://codepen.io/glebez/pen/pExPdP

**Comment by scottgrayson** [comment]
This customization worked for me
```
.card-columns .card {
    display: block;
}
```

**Comment by glebez** [comment]
@scottgrayson, be aware that using this workaround causes the card to break in multiple columns. This was addressed in this ticket: https://github.com/twbs/bootstrap/issues/20654

**Comment by jeronimok** [comment]
Hi @glebez  
Did you get any solution to this problem?

**Comment by trackleft** [comment]
https://github.com/twbs/bootstrap/pull/22378

**Comment by DLongoni** [comment]
Hello, I see that @trackleft solution has been closed. I am still experiencing the same problem, though. Have you found a solution?

**Comment by ilromolo** [comment]
Hello, same for me. Using bootstrap-4.0.0-alpha-6, if .card are less than three, cards stack differently in Chrome and Opera.

I modified the last part of _card.scss:

````
//
// Columns
//

@include media-breakpoint-up(sm) {
    .card-columns {
        column-count: $card-columns-count;
        column-gap: $card-columns-gap;

        .card {
            -webkit-column-break-inside: avoid;
            //display: inline-block; // Don't let them vertically span multiple columns
            width: 100%; // Don't let their width change
            margin-bottom: $card-columns-margin;
            
        }
    }
}

@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .card-columns {
        .card {
            display: inline-block; // Don't let them vertically span multiple columns 
        }
    }
}

@supports (-ms-ime-align:auto) {
    .card-columns {
        .card {
            display: inline-block; // Don't let them vertically span multiple columns 
        }
    }
}
````

In this way works fine on Firefox, Opera, Edge and IExplorer 11, but still have problem with Chrome: the margin bottom of the last .card in the most long column is reported on the top of next column:

![screen](https://user-images.githubusercontent.com/16102131/29974073-0b7eec98-8f32-11e7-962c-6e13b8d53841.png)

**Comment by Kronuz** [comment]
@ilromolo my first impression was it was due the border, but this margin thing doesn't seem to happen here. does your card have `box-sizing: border-box;`? Can you produce a live example somewhere please?

**Comment by fran-worley** [comment]
I've got this issue in bootstrap4.beta1. Less than 3 cards and they sit in one row in chrome.

Turns out it is todo with how chrome handles line breaks: 
https://drafts.csswg.org/css-break/#widows-orphans

Simply set `orphans: 1; windows:1;` on your `card-columns` and chrome will wrap as expected.

**Comment by Kronuz** [comment]
This is interesting. @fran-worley, do you mean your solution with vanilla bootstrap 4 beta or the one using `-webkit-column-break-inside: avoid`?

**Comment by Kronuz** [comment]
I can confirm adding `orphans: 1; widows:1;` to `.card-columns` fixes the issue here. (Over vanilla bootstrap v4.0.0-beta)

**Comment by ashkitten** [comment]
Will this fix make it into beta 2?

**Comment by mikebeaudin87** [comment]
In Beta 2, I had to add !important

orphans: 1 !important; 
widows:1 !important;

**Comment by WebDragon** [comment]
can confirm, even in Bootstrap 4.0-final release, it is still necessary to add @mikebeaudin87 's orphans/widows trick  for the webkit version in the current releases of 
chrome (google-chrome-stable-65.0.3325.181-1.x86_64),
vivaldi (vivaldi-stable-1.14.1077.60-1.x86_64),
opera (opera-stable-52.0.2871.30-0.x86_64)
that are  available for Fedora Linux

**Comment by mariusa** [comment]
This still doesn't work on screens/viewports at 570px or smaller. Cards overlap, even with @mikebeaudin87 's solution 

example: https://booxia.com/book/20000-leagues-under-the-sea/m9u96ctuz2c

![screenshot from 2018-09-05 12-46-54](https://user-images.githubusercontent.com/1283842/45085738-17176a80-b10a-11e8-9bf3-04643ff7dfe9.png)

**Comment by LuiguiDVen** [comment]
me sucede lo mismo que comenta @mariusa con la versión de bootstrap 4.1.3 y chrome, 

![image](https://user-images.githubusercontent.com/44814160/48081374-46a82900-e1c6-11e8-84b9-486996950304.png)

esa imagen es de chrome..
