### ISSUE TITLE
Fonts not loading with npm install 

### ISSUE THREAD

**Issue by AlmogRnD** [twbs/bootstrap#20935]
I'm working on a meteor app, latest version using React for the client side I installed the package via npm and did the proper imports as required. 

Everything is fine expect the fonts, I get the following error. And when I installed the npm package and just used the meteor atmosphere package it's fine  

Failed to decode downloaded font: http://localhost:3000/lineups/fonts/glyphicons-halflings-regular.woff

select-business:1 OTS parsing error: invalid version tag

**Comment by bardiharborow** [comment]
Please read [the contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md) and provide an adequate amount of information for us to follow up. However note that Bootstrap v3 is now no longer supported. A simple google search turned up [this](https://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts) which may assist you.

**Comment by AlmogRnD** [comment]
@bardiharborow I did a search on stackoverflow, none of the issues that I found are related to what I reported. For example what you sent me is for webpack but I'm using the meter build tool. I also looked at the guidelines before reporting the bug not sure what else you need.

**Comment by cvrebert** [comment]
Closing since v3 is no longer supported.
See https://github.com/twbs/bootstrap/blob/v3-dev/README.md#community for community help forums.

**Comment by AlmogRnD** [comment]
@cvrebert I don't understand the current bootstrap version is v3.3.7 which is what I'm using. bootstrap 4 is not out yet, so why are you not supporting version 3?

**Comment by cvrebert** [comment]
Please refer to #20631

**Comment by liop** [comment]
@AlmogRnD same problem resolve by use `meteor add twbs:bootstrap `
