### ISSUE TITLE
Inline checkbox and radio -> unecessarily different markup

### ISSUE THREAD

**Issue by bkdotcom** [twbs/bootstrap#20936]
**default stacked (and without label) markup:**

``` html
<div class="form-check disabled">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" value="pick me" disabled>
    Giant Meteor
  </label>
</div>
```

**inline markup:**

``` html
<label class="form-check-inline disabled">
  <input class="form-check-input" type="checkbox" value="pick me" disabled> I'm not grey - fixed in a5
</label>
```

**Proposed markup for inline:**
keep wrapper <div>; label's class is same as stacked; disabled class would go on the wrapper (consistent with stacked)

``` html
<div class="form-check form-check-inline disabled">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" value="pick me" disabled>
    Same is good
  </label>
</div>
```
- The only difference is the class attribute for the outer wrapper.
- We're not removing the div + changing the label's class
- adding the `disabled` class is consistent
- procedural / dynamic / templating easier..   don't need a separate template for inline,, just a different class attribute on the wrapper

It makes no difference to me whether inline is accomplished by adding the class `form-check-inline` or replacing `form-check` with `form-check-inline`  (seems like maintaining css  - would be easier by adding `form-check-inline`)

Different markup leads to issues like #20799  (fix pending for a5)
(currently need separate selectors for inline `.disabled`)

(this annoyance exists in Bootstrap 3 as well - lets get it right in 4!)  🤓

**Comment by mdo** [comment]
Originally thinking was if I could keep markup and styling simpler, I should try to do so. Totally get that this leads to more complications though, so happy to take a look at the associated PR more.

**Comment by Shyam1319** [comment]
<form>
			<div class="form-group">
				<label for="firstName">First Name</label>
				<input type="text" id="firstName" class="form-control">
			</div>
			<div class="form-group">
				<label for="lastName">Last Name</label>
				<input type="text" id="lastName" class="form-control">
			</div>
			<div class="form-group">
				<label for="myFile">Upload</label>
				<input type="file" id="myFile" class="form-control-file">
			</div>
			<div class="form-group">
				<legend>Please Select</legend>
				<div class='form-check-inline'>
				  <label for="radio1">Yes</label>
				  <input type="radio" id="radio1" class="form-control-input" value='Yes' name="radios">
				</div>
				<div class='form-check-inline'>
				  <label for="radio2">No</label>
				  <input type="radio" id="radio2" class="form-control-input" value='Yes' name="radios">
				</div>
				
			</div>
		</form>
form-check-inline is not working
