### ISSUE TITLE
[v4] Unify card and alert padding

### ISSUE THREAD

**Issue by KKSzymanowski** [twbs/bootstrap#20931]
Currently `.alert` padding is defined as `15px` and `.card-header` padding as `0.75rem 1.25rem`.
Because of this, the text isn't aligned vertically:
![przechwytywanie1](https://cloud.githubusercontent.com/assets/13980973/19496303/2bcc072e-9587-11e6-87a1-fa628d98aed4.PNG)

I don't know if this is intentional or not, but for me it doesn't look that good.
[Here ]( https://jsbin.com/hedurinawi/edit?html,css,output) is a live example with two possible fixes.

Is this something I should configure on my end or should I make a pull request to include it in the core?

**Comment by mdo** [comment]
See #20933.

**Comment by KKSzymanowski** [comment]
Thanks.
