### ISSUE TITLE
Tooltip has no style

### ISSUE THREAD

**Issue by timmyrs** [twbs/bootstrap#20942]
I have the luck that sometimes I see *this*:
![right](https://cloud.githubusercontent.com/assets/11009697/19518766/201cce4a-9609-11e6-9383-b560a2d2d776.png)
but most of the time, I see *this* instead:
![wrong](https://cloud.githubusercontent.com/assets/11009697/19518778/3311a76e-9609-11e6-9e09-e12d658afd71.png)
So, I went and looked for this issue online, but I found nothing.
It might be an issue with my code, so I created a [minimal test case](https://playground.netdex.co/test/bootstrapbug) that **also** works only sometimes.
If the tooltip does work for you, reload until it doesn't.
So, please fix or tell me if I did something wrong.

**Comment by bardiharborow** [comment]
Your test case isn't even valid HTML and loads Bootstrap v3 not v4.

**Comment by timmyrs** [comment]
@bardiharborow Bootstrap v4 is in beta (from my point of view, so I obviously use v3) and I fixed these 3 little bugs and it still doesn't work.

**Comment by bardiharborow** [comment]
Your test case now works perfectly for me. Please read [the contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md) and provide information about your enviroment (browser version, OS, etc.) so we can follow up. Note that [support for v4 has mostly ceased](https://github.com/twbs/bootstrap/issues/20631).

**Comment by timmyrs** [comment]
@bardiharborow Have you reloaded until it doesn't work?
I wrote that it works **sometimes**, reading is a valuable skill, man.

**Comment by timmyrs** [comment]
Well thanks to a bit of digging I found out that the issue was with jQuery UI.
http://stackoverflow.com/questions/13731400/jqueryui-tooltips-are-competing-with-twitter-bootstrap
