### ISSUE TITLE
"Inner" containers in alpha5 suddenly are much wider than before

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#20949]
- Operating system and version: Win 10
- Browser and version: Chrome 53

I use two Bootstrap containers on my page, both are inside (different) flex-item divs. In alpha4, the containers maintained the same width as their parent (Bootstrap set the container's max-width only). I've tried to upgrade to alpha5 today, but now the containers are pushing the width of their parents by having a fixed width set.

Is this on purpose or a bug? Is it no longer recommended to use the container class somewhere in the page? Why the change to setting the width explicitly?

**Comment by drauch** [comment]
Just found https://github.com/twbs/bootstrap/pull/20865, still, this seems like a bug to me. Now whenever you want to use a container you are immediately using at least n pixels :(

**Comment by drauch** [comment]
Plunker v4: https://plnkr.co/edit/bOscs8UMioYZOoHnfCxh?p=preview
div#col2 is not broader than expected, works just fine.

Plunker with v5: https://plnkr.co/edit/cfZKLrQJrscQP7muwXgO?p=preview
div#col2's width is much broader than expected, layout ruined due to inner Bootstrap container => cannot use Bootstrap container anymore => :((

**Comment by hebbet** [comment]
see also https://blog.getbootstrap.com/2016/10/19/bootstrap-4-alpha-5/#grid-updates

**Comment by mdo** [comment]
> Now whenever you want to use a container you are immediately using at least n pixels of width :(

That's the whole point of the container though—it centers related content in the page at a fixed width. Previously, flexbox containers wouldn't grow to their full available width. That's why that grid PR fixes #20681.

Remove the container and add the grid gutter padding to the custom parent you're using and you should be good to go. See a quick fork of your demo in https://jsbin.com/cinewo.

**Comment by drauch** [comment]
Oh, nice, didn't know you could use the grid now without an outer container. Thanks!
