### ISSUE TITLE
Can Bootstrap-4 support markdown?

### ISSUE THREAD

**Issue by chuoke** [twbs/bootstrap#20946]
I like Bootstrap,and i hope it be more powerful.

Markdown is popular and fashion more and more. There are many applications use Markdown,especially the world of developer and writer.

Can Bootstrap-4 support or parse markdown ?

**Comment by bardiharborow** [comment]
This is nonsensical. Markdown is a text markup language and has nothing to do with a CSS library. If you want to parse and format markdown client-side, you can look at any of [the numerous options](https://www.google.com/search?q=markdown+javascript).

**Comment by patrickhlauke** [comment]
Indeed, Bootstrap does not do processing etc of things like Markdown into HTML. It's an HTML/CSS/JS framework.

**Comment by chuoke** [comment]
OK， thanks，anyway，i will find one.
