### ISSUE TITLE
question or bug? on scroll

### ISSUE THREAD

**Issue by publicocean0** [twbs/bootstrap#20944]
I m developping a chat minipopup in the bottom part of window and in side it there are many tools. When i click on a tool icon it will open a popup with arrow(popover) for not covering editor line.When resize window, being inside a fixed area it have to remain in fixed position like the parent divs of this area. 
i tried to use property container='body' but on scroll popover dont remain in the fixed position as the parent area of target.
I tried to use container=main_popup(the div with fixed position). scroll works correctly but now width of popover can't be bigger that the with of main_popup. I tried also to change z-index but dont work.

**Comment by mdo** [comment]
We can't help you with potential bugs unless there's a reduced test case you can link us to :).

**Comment by publicocean0** [comment]
can i create a pull request for emproving it on resize (container body fixed position) , custom shift offset and better perfomance in replacing ? I need this requirements also for my gui.

**Comment by mdo** [comment]
I'm still unsure what exactly you're referring to, but it sounds like a mix of popovers and more. I don't think we'd accept the kind of changes you're looking to make for your specific use case, but if you can articulate that in a demo of some kind, we can revisit.

**Comment by publicocean0** [comment]
considering new version (4) is completey different for popover and it use external dependecy (i dont agree with using external dependecy sincerely... in addition i tried it in my old code built with version 3 (just replacing js e css references)but dont works.... i didnt go inside for seeing the reason ... but it seams a version non very stable ). For all this reasons i decided to create my plugin.
