### ISSUE TITLE
Error building SASS file when extending .pull-xs-right alpha5

### ISSUE THREAD

**Issue by jlai403** [twbs/bootstrap#20953]
After updating to the latest alpha release, my SASS builds are failing with the following error:

`
Module build failed: 
		@extend .pull-xs-right;
 ^
`

I've reverted back to v4.0.0-alpha.4 for now and it's working again.

**Comment by mdo** [comment]
It's `.float-xs-right` now. Apologies for not making a mention of that in the blog post.
