### ISSUE TITLE
Not an issue - a minor improvement

### ISSUE THREAD

**Issue by HJPepper** [twbs/bootstrap#20959]
Please could you add a 'back to top' button sometime.

When you scroll so far down the page/click to a section further down the page, and need to go back to the top you have to scroll all the way up. Could there just be a button which appears when you're scrolling distance down a page that takes you back to the top?

Many thanks

**Comment by zacechola** [comment]
Are you requesting this for the v4 documentation?

**Comment by cvrebert** [comment]
Are you aware of the Ctrl+UpArrow keyboard shortcut?

**Comment by mdo** [comment]
Might have some nav changes coming that'll help with this, but I don't see us adding that back to v4's docs again :). Try what @cvrebert mentioned with the keyboard shortcut :).

**Comment by mahassan** [comment]
Just a icon would help, Sometimes you busy reading and don't want to play with keyboard.
