### ISSUE TITLE
Reopen #16127

### ISSUE THREAD

**Issue by zomp** [twbs/bootstrap#20955]
Could you reopen issue #16127 (Modals Overlapped by Tooltips/Popovers) and close this one, please? Unfortunately I have no rights to do so.

**Comment by bardiharborow** [comment]
Closed issues can still be commented upon and still generate notifications. Creating an issue to get another reopened is unnecessary. Please close this and go explain on #16127 why it should be reopened.

**Comment by mdo** [comment]
Closing this that issue.
