### ISSUE TITLE
Popover wrong sass variable

### ISSUE THREAD

**Issue by peacepostman** [twbs/bootstrap#20958]
Hello,

In last Bootstrap alpha 5 release (v4.0.0-alpha.5) there is an error in popover.scss

Line 89 value is : 
`border-bottom-color: $popover-title-bg;`
and should be
`border-bottom-color: $popover-arrow-color;`

Keep up the good work :)

**Comment by zacechola** [comment]
I don't believe that is an error. When the arrow is at the top of the popover, its color should be the same as the title-bg, not white, as in the other positions.

**Comment by mdo** [comment]
Yup, there are two arrows doing the popover effects that we have in place. I believe these are working as intended.

**Comment by peacepostman** [comment]
@zacechola @mdo Oh my bad I didn't think it this way. Nevertheless my usecase was without a popover title and in this very exemple the gray arrow is a bit weird :/

I don't thin we can add a specific style according to the fact that arrows are now in pseudo element.

**Comment by zacechola** [comment]
@mdo Might have an opinion on that case as far as the framework goes, but the simplest thing to do would be to override the CSS yourself, @peacepostman.
