### ISSUE TITLE
Provide a SASS / CSS file for flex grid only

### ISSUE THREAD

**Issue by ova2** [twbs/bootstrap#20950]
For a regular grid, we have this file https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap-grid.scss The result CSS only contains grid speicific styles. We need the same for a flexbox based grid. There are many users that only want to use the flexbox based grid in there projects with Angular or React components.

**Comment by mdo** [comment]
Do you need the compiled CSS bundle, or do you need a flexbox enabled Sass file? If the latter, that's easily done with the current grid.

**Comment by ova2** [comment]
I need a Sass file, but not a flexbox enabled Sass file which includes everything. I need a Sass file which ONLY include flexbox layout grid. The goal: use this Sass file with Webpack in Angular based app (or any other web apps). It should be possible to only use the flexbox layout without Bootstrap's typography, components, etc. etc.

**Comment by ve3** [comment]
In the Bootstrap 4 alpha 5, there are many files in the package. bootstrap-flex.css, bootstrap-grid.css, bootstrap-reboot.css, bootstrap.css
Which files do I have to use and what are these files for? I have to use all of them in the html > link element? Please describe more in the document.

**Comment by ova2** [comment]
- **bootstrap-reboot.css** - Normalize styles + some extended styles to reset common CSS settings for better cross-browser experience.
- **bootstrap.css** - All CSS from Bootstrap, inkl. reqular grid layout
- **bootstrap-flex.css** - All CSS from Bootstrap, but with flexbox based grid layout
- **bootstrap-grid.css** - Only CSS for reqular grid layout

What I'm missing now, is **bootstrap-flex-grid.css** - Only CSS for flexbox based grid layout. This is the topic of this issue.

**Comment by ve3** [comment]
thank you @ova2

**Comment by mdo** [comment]
You can declare the variable that enables flexbox with the current grid file. Add `$enable-flex: true;` within or before the grid Sass file and you *should* be good to go.

**Comment by ova2** [comment]
@mdo Do you mean, I can install boostrap with npm and then create my own Sass file with this content?

$enable-flex: true;
@import "~bootstrap-sass/.../bootstrap-grid

Webpack should create then a flexbox based layout when it loads this file by the sass-loader. I will give it a try. Thanks for the tip.

**Comment by mdo** [comment]
Yup! That works :).
