### ISSUE TITLE
figure img-fluid doesn't work in IE and Firefox

### ISSUE THREAD

**Issue by jvanderkroon** [twbs/bootstrap#20970]
http://v4-alpha.getbootstrap.com/content/figures/

The diplay:inline-block on the .figure creates a bug in IE11 and Firefox lt 49.0.2
The image doesn't listen to the max-width: 100% and get's bigger than the available space.

see the demo http://codepen.io/jvanderkroon/pen/PGXKWJ

**Comment by jdpunk1** [comment]
img-responsive from bootstrap 3.3.7 seems to improve it in ie9, it may be possible to import just that portion of 3.3.7 to a custom bootstrap config? http://codepen.io/jd_1/pen/amPyrk

**Comment by jvanderkroon** [comment]
@xcartmods LT (lower than) i don't know the exact version because my firefox did an auto update.

@jdpunk1 Bootstrap 3 don't use inline-block on the .figure but this is needed in version 4 for the caption alignment.

I did a quick fix by adding max-width: 100% tot the .figure.

**Comment by jdpunk1** [comment]
Got sidetracked by the weekend! cool, glad it worked out..

**Comment by mdo** [comment]
Closing without any changes here for now. Happy to revisit if needed though.

**Comment by Findus23** [comment]
Is there a reason why this issue is closed? I just stumbled over this issue while testing my page in IE11. (I am using the latest version on git)

**Comment by johnaau** [comment]
Just came across this issue in V4.1.1. Even the figure demos in the documentation don't respect img-fluid in Internet Explorer 11. @jvanderkroon 's fix does solve the problem but would be nice if this was fixed in BS.
![capture](https://user-images.githubusercontent.com/6590573/41069666-492c01c6-6a32-11e8-8a95-d03070d7c67a.JPG)
