### ISSUE TITLE
<select> element height differs from other form inputs when using custom line height

### ISSUE THREAD

**Issue by maimairel** [twbs/bootstrap#20977]
When compiling Bootstrap with line-height other than the default value, the select element's height slightly differs from other elements and buttons.

select element with default line height:
![default line height](https://cloud.githubusercontent.com/assets/2133064/19626131/5b25d3a8-9954-11e6-9b80-7a33e1fb5337.png)

select element with 1.75 line height:
![1.75 line height](https://cloud.githubusercontent.com/assets/2133064/19626130/5b23cab8-9954-11e6-893d-3706f405f6a6.png)

Thanks!

**Comment by maimairel** [comment]
When compiling Bootstrap with line-height other than the default value, the <select> element's height slightly differs from other elements and buttons (see screenshot).

1.5 line height (Bootstrap's default):
![Button with default line height](https://cloud.githubusercontent.com/assets/2133064/19626131/5b25d3a8-9954-11e6-9b80-7a33e1fb5337.png)

1.75 line height:
![Button at 1.75 line height](https://cloud.githubusercontent.com/assets/2133064/19626130/5b23cab8-9954-11e6-893d-3706f405f6a6.png)

**Comment by maimairel** [comment]
Can't insert an image with markdown:

Button with default line height:
https://cloud.githubusercontent.com/assets/2133064/19626131/5b25d3a8-9954-11e6-9b80-7a33e1fb5337.png

Button with 1.75 line height:
https://cloud.githubusercontent.com/assets/2133064/19626130/5b23cab8-9954-11e6-893d-3706f405f6a6.png

**Comment by maimairel** [comment]
Can't insert an image with markdown:

<select> with default line height:
https://cloud.githubusercontent.com/assets/2133064/19626131/5b25d3a8-9954-11e6-9b80-7a33e1fb5337.png

<select> with 1.75 line height:
https://cloud.githubusercontent.com/assets/2133064/19626130/5b23cab8-9954-11e6-893d-3706f405f6a6.png

**Comment by jesusmtzarvizu** [comment]
Just to confirm that I understand it , So the select element's height is the only element that change when you change the default value of line -height on you CSS Document???

**Comment by maimairel** [comment]
@jesusmtzarvizu Yes, the select element height's differs, because it is hardcoded in Bootstrap. 
``
select.form-control:not([size]):not([multiple]) {
  height: calc(2.75rem - 2px);
}
```
