### ISSUE TITLE
[BUG] - Accessibility using menu(dropdown) and select  + keyboard - IE

### ISSUE THREAD

**Issue by Taobaoliveira** [twbs/bootstrap#20972]
Operating system and version:  **Win10**
Browser and version: **IE 11**

You cannot change select options using the keyboard. Options are not displayed.
https://jsfiddle.net/DTcHh/26402/

**Comment by patrickhlauke** [comment]
The problem here is that you have a `role="menu"` on those dropdowns, but these are not menus - ARIA menus can only contain menu items, checkbox menu items, radio button menu items and submenus. https://www.w3.org/TR/wai-aria/roles#menu

Remove the `role="menu"` and it should work correctly.

**Comment by patrickhlauke** [comment]
https://jsfiddle.net/m9662zyw/1/

**Comment by Taobaoliveira** [comment]
Thx but,
 
- It works correctly in Bootstrap 3.0.0
- The error occurs in higher versions  (3.3.5) and (3.3.7)- https://jsfiddle.net/3nwz4d2b/1/

**Comment by patrickhlauke** [comment]
> It works correctly in Bootstrap 3.0.0

but it's still invalid to have anything other than menu items, checkbox menu items, radio button menu items or submenus inside a `role="menu"` construct. if this worked in the past, that was a bug in past version of Bootstrap

> The error occurs in higher versions (3.3.5) and (3.3.7)- https://jsfiddle.net/3nwz4d2b/1/

Tested that in IE, and I can't reproduce a problem. Is that URL causing you problems?

**Comment by Taobaoliveira** [comment]
After removing `role="menu"` works correctly in version 3.0.0.

In version 3.3.5 does not work.

Open the link for Internet Explorer (IE11 -10) and try to change the select options using keyboard.
https://jsfiddle.net/3nwz4d2b/1/

Thx

**Comment by patrickhlauke** [comment]
Ah yes, it does seem that those `<select>`s can't be changed with up/down arrows. Digging further, it seems though that dropdown components in v3 are intended/designed to be used just for link/menus

>Toggleable, contextual menu for displaying lists of links.

http://getbootstrap.com/components/#dropdowns

this limitation has been partially removed in V4 

> Historically dropdown menu contents had to be links, but that’s no longer the case with v4. Now you can optionally use <button> elements in your dropdowns instead of just <a>s.

http://v4-alpha.getbootstrap.com/components/dropdowns/#menu-items

but fundamentally, they're still not designed to contain arbitrary content, such as a fully-fledged form. so the current behavior is arguably "as designed". @mdo any further thoughts on this?

**Comment by vanduynslagerp** [comment]
Please see #19864 that fix this issue in V4 for the dropdowns.
You might also be interested in #19978 that deal with keyboard navigation in dropdown as well.
