### ISSUE TITLE
navbar-text on navbar-dark and bg-inverse is invisible

### ISSUE THREAD

**Issue by Bartmax** [twbs/bootstrap#20975]
`nav-link` change colors based on theme but `navbar-text` doesn't.

also I find `nav-link` and `navbar-text` not consistent. shouldn't be `nav-link` and `nav-text` ?

full example:
```html
<nav class="navbar navbar-dark bg-inverse navbar-full">
    <span class="navbar-text">gdsafdsa</span> <!-- invisible because color = bg-color -->
</nav>
```

**Comment by SamArmand** [comment]
@Bartmax do you have a workaround for the navbar-text issue?

**Comment by Bartmax** [comment]
@SamArmand apply a color to `navbar-text` you can use `text-muted`, `text-white` or a custom one.
