### ISSUE TITLE
Printing : New CSS Class to set base font size

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#20988]
Screen fonts sizes are much too big for printing - e.g. an H1 on an A4 page (portrait) only has about 4 words per line. 

Its the same for normal text, printing a page (A4, portrait)  gives about 10 words/line, but standard printing is about 20 words/line.

It would be better to reduce font sizes for printing, or at least have it as an option.

```
<body class="print-sm">
<body class="print-xs">
```

(Reason, my website is walks, so people print the pages to take with them. People who need glasses prefer big print so they can read without them. 20-20 people like small print to save paper)

In Bootstrap 3, there is no easy solution, as all sizes are in px. 

With the switch to rem units, this should be possible to fix/implement.

**Comment by saturdaywalkers** [comment]
Well, this is very embarrassing. Turns out the 'too big font sizes' is a phantomjs issue. (phantomjs renders webpages, including js, for testing, or saving to pdf).

The "new class to set base font for printing" request is still valid, some people need (very) large print

**Comment by mdo** [comment]
Closing as stale and not something I want to prioritize. Feels like this can easily be an extension/add-on to the core styles.
