### ISSUE TITLE
Input Group drop-down menu minimum width too wide

### ISSUE THREAD

**Issue by davidtgq** [twbs/bootstrap#20981]
The minimum width of the drop-down menu is too wide:

![capture](https://cloud.githubusercontent.com/assets/14155110/19630093/5f4f273e-9951-11e6-8afe-81018988947e.png)

This is on V4 alpha 5

        <div class="form-group row">
          <label class="col-xs-2 col-form-label">Area</label>
          <div class="col-xs-10">
            <div class="input-group">
              <input type="number" class="form-control" value="42" id="example-number-input">
              <div class="input-group-btn">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                  Conversion
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item" href="#">m<sup>2</sup> to ft<sup>2</sup></a>
                </div>
              </div>
            </div>
          </div>
        </div>

The minimum width of the drop-down menu should be the width of the button toggling the drop-down menu. This is what it would look like:

![capture1](https://cloud.githubusercontent.com/assets/14155110/19630094/5f4fd1a2-9951-11e6-98f7-c2ae6a841616.PNG)

**Comment by jdpunk1** [comment]
HI, I'm trying to replicate this, do you have it on jsfiddle or codepen pls?

**Comment by davidtgq** [comment]
@jdpunk1 Sure, here you go: http://codepen.io/anon/pen/ozVbXR

**Comment by mdo** [comment]
The default minimum width is a recommendation on our part. If that doesn't work for you, you should override it as needed.

**Comment by davidtgq** [comment]
@mdo I'm ok with this being a wontfix, but please at least explain it to me. Do you genuinely recommend the layout in the first picture over the layout in the second picture? Why?

**Comment by jdpunk1** [comment]
.dropdown-menu{min-width:100% !important}
allows it to inherit..
