### ISSUE TITLE
.row margin-right ineffective

### ISSUE THREAD

**Issue by shivampaw** [twbs/bootstrap#20997]
up vote
1
down vote
favorite
I am using Bootstrap 4 Alpha 5 and I have the following HTML:

```
<div class="home-content">
    <div class="container">
        <div class="row flex-items-xs-middle">
            <div class="col-md-7">
                <h1 class="site-title text-xs-center text-md-left">
                    <span class="name">I'm Shivam Paw</span>
                    <span class="title">I create beautiful and bespoke websites to fit your needs</span>
                </h1>
            </div>
            <div class="col-md-5">
                <img src="https://www.shivampaw.com/wp-content/uploads/2016/10/shivampaw.png" class="float-md-right img-fluid logo-me mx-auto" alt="Shivam Paw">
            </div>
        </div>
    </div>
</div>
```
However, if you see the image below then you will see that the content is misaligned to the left.

https://i.stack.imgur.com/1y69Q.png

http://i.imgur.com/gIS0h4n.png

With margins removed: http://i.imgur.com/oeyguoo.png

I looked at the .row CSS which has margin for left and right of -15px. Removing those margins fixed it but I don't think that's how it should be?

I posted on StackOverflow but nobody knew what was wrong: http://stackoverflow.com/questions/40228705/bootstrap-row-not-aliging?noredirect=1#comment67722210_40228705

Seems like a bug.

**Comment by mdo** [comment]
Can you post a live, reduced test case please? Hard to go off one bit of the code snippet and your screenshots :).

**Comment by shivampaw** [comment]
https://www.shivampaw.com

**Comment by shivampaw** [comment]
@mdo ^ thanks

**Comment by mdo** [comment]
Sorry, that's not a reduced test case :). Please strip it all down to just Bootstrap's HTML and CSS in a JSBin or JS Fiddle.

**Comment by mdo** [comment]
Closing until we hear more in reply to my previous comment. <3

**Comment by shivampaw** [comment]
I fixed it.

The problem was I had a 

*{
    max-width: 100%;
}

In my css
