### ISSUE TITLE
[Firefox] SHA-1 certificates issued by public CA will no longer be accepted (Affecting)

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#20990]
https://www.fxsitecompat.com/en-CA/docs/2016/sha-1-certificates-issued-by-public-ca-will-no-longer-be-accepted/

**Comment by mdo** [comment]
Maybe need to look into Cloudflare for this given they handle our https bits?

**Comment by bardiharborow** [comment]
@mdo, Cloudflare has been [on top of this](https://blog.cloudflare.com/sha-1-deprecation-no-browser-left-behind/) for quite a while now. Cloudflare is using a special technique to serve SHA1 certificates only to legacy browsers, which means that new versions of Firefox are not being served SHA1 certificates anyway. This is safe to close.

**Comment by mdo** [comment]
Dope!
