### ISSUE TITLE
Sass flexbox Mixin for a better compatibility

### ISSUE THREAD

**Issue by ansiloc** [twbs/bootstrap#21009]
Hello !

Can you reformulate all flex declaration with a sass flexbox mixin than include prefixes.

I had this one on my project and the gain is huge if i compare to the few occurences of flex terms in bootstrap 4 code :
https://github.com/mastastealth/sass-flex-mixin

IOS 8, than have only 2 years and witch is installed on first iPhone 6 genaration need prefixes.
IE11 need some to.
And there is more active clients than need some (Older iOS, Samsung Browsers, etc...).

A small modification to gain 2 years back compatibility on various devices, this is not a bad proposal ?

Thank you in advance.

Nicolas

**Comment by wolfy1339** [comment]
Bootstrap uses Autoprefixer to do that automatically during the build process. That just adds extra un-needed vendor prefixes for browsers that aren't supported by Bootstrap.
See https://github.com/twbs/bootstrap/blob/v4-dev/grunt/postcss.js#L12-L40 for all the versions of supported browsers.

**Comment by mdo** [comment]
Yup, sticking with Autoprefixer on our end for this.
