### ISSUE TITLE
[Firefox] New WoSign and StartCom certificates will no longer be accepted (Affecting)

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#21006]
https://www.fxsitecompat.com/en-CA/docs/2016/new-wosign-and-startcom-certificates-will-no-longer-be-accepted/

**Comment by mdo** [comment]
Closing this out since it sounds like it doesn't affect us @cvrebert. (Going to peep the rest of these, too, and close out what I think doesn't apply fwiw.)
