### ISSUE TITLE
[Firefox] Missing form input validation icons

### ISSUE THREAD

**Issue by thomey** [twbs/bootstrap#21001]
OS: macOS Sierra
Browser: Firefox 49.0.2

The validation icons doesn't work. Try http://v4-alpha.getbootstrap.com/components/forms/#validation

<img width="1051" alt="bs4" src="https://cloud.githubusercontent.com/assets/812358/19681743/f243e250-9aaa-11e6-8446-e90cee17a755.png">

**Comment by Lausselloic** [comment]
Yes, it's fixed by https://github.com/twbs/bootstrap/pull/20962
# need to be escaped into svg. Impact all svg used into _variables
