### ISSUE TITLE
table-inverse : need a variable for hover, accent, active state

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#21002]
https://github.com/twbs/bootstrap/commit/d74a897f55ff01258b81e05c94a8126a819b8601#diff-82ee1ffb694a87db828fe22dcd868aed

Following the fix, table-hover, table-stripped combined with table-inverse works, but for accessibility reason, could we have a dedicated background value for those states?

For example : 
Actual value for table 
$table-bg-accent:     $table-bg-hover:      $table-bg-active:  
Can be completed with : $table-inverse-bg-accent:     $table-inverse-bg-hover:      $table-inverse-bg-active:

**Comment by mdo** [comment]
Was addressed with #22217.
