### ISSUE TITLE
[Firefox] use strict can no longer be used in function with non-simple parameters

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#21008]
https://www.fxsitecompat.com/en-CA/docs/2016/use-strict-can-no-longer-be-used-in-function-with-non-simple-parameters/

**Comment by mdo** [comment]
I think we're safe here given this line from the site:

> Since Google Chrome and Microsoft Edge have already made the change, the compatibility impact should be minimum.

We can re-open if need be @cvrebert.
