### ISSUE TITLE
Alpha5 Blogpost - pull-*-* becomes float-*-*

### ISSUE THREAD

**Issue by elieteyssedou** [twbs/bootstrap#21014]
Hi,

I updated from alpha 4 to alpha 5 this morning and for an obscure reason I figured out that `pull-xs-right` - for example - doesn't work anymore.

Then, I checked the [changelog](https://blog.getbootstrap.com/2016/10/19/bootstrap-4-alpha-5/) and nothing was written about it.

Finally I found the answer in the following PR: #19890, `pull-*-*` becomes `float-*-*`.

I think **that would be helpful to have this information at least the blog post**.
To go further, in the documentation `float-*-*` is mentioned in the [navbar component section](http://v4-alpha.getbootstrap.com/components/navbar/). What about create an `Align` section - in utilities - in the documentation ? Or putting it in the `Sizing and positioning` section?

Thank you,

Elie

**Comment by saviomd** [comment]
It's here: http://v4-alpha.getbootstrap.com/utilities/responsive-helpers/
But I think that it should be in a better place in the docs (probably a new section: utilities -> floats)

**Comment by elieteyssedou** [comment]
I didn't see it in the doc, thanks. But yes in a floats section it would be great.

**Comment by niftylettuce** [comment]
great idea

**Comment by mdo** [comment]
I plan to revisit the docs organization in Alpha 6 to address that. The blog post has since been updated to include mention of the change, too.
