### ISSUE TITLE
popover 'Auto left' / 'Auto right' placement bug latest Chrome (Version 54.0.2840.71 (64-bit))

### ISSUE THREAD

**Issue by ezkialrage** [twbs/bootstrap#21018]
Running the latest Chrome, when using 'auto left' or 'auto right' with the popover placement attribute, the popover arrow is initially misaligned. For clarity, if you select 'auto left' and the popover gets adjusted right for lack of room on the left, then the arrow is misaligned, otherwise it looks fine on the left.   Any event that changes a css property will somehow fix the issue on the page for the opened popover e.g. expanding the browser past a MQ breakpoint or manually adjusting any css element of the popover arrow in the devtools, but when you close and reopen the popover the issue will re-present itself.  

I have noticed that this issue is not present on machines with older chromes v.53 and under. This issue is not present in FF or Safari.  You can duplicate this issue with the angular bootstrap popover plunker link by adding  'auto' to the popover-placement attribute, and select left for the button. 

https://plnkr.co/edit/cld8q7rtEa6O9zSGuGlW?p=preview

Again, this only affects the repositioned 'auto left' and 'auto right' placement in the latest version of chrome. 

![screen shot 2016-10-26 at 11 30 37 am](https://cloud.githubusercontent.com/assets/6233135/19735082/ae7bf8ee-9b6f-11e6-96e2-5e65595013de.png)

![screen shot 2016-10-26 at 11 04 58 am](https://cloud.githubusercontent.com/assets/6233135/19735059/95f6ed24-9b6f-11e6-9994-3007dfbfbe57.png)

**Comment by abyx** [comment]
:+1: I am also seeing this with `auto bottom` and `auto top`

**Comment by mdo** [comment]
Closing as a won't fix given v3's state (we're not actively developing it while working on v4).
