### ISSUE TITLE
Input-group within card-deck

### ISSUE THREAD

**Issue by 121052** [twbs/bootstrap#21010]
In Chrome I get a bug when adding input group under a card-deck. The spacing between buttons and input are off. The reason seem to be the `border-spacing: 1.25rem 0;` under .card-deck.
Changing the `border-collapse: separate;` to `border-collapse: collapse;` under .input-group seems to fix the problem. However, it also affects the spacing between each card.

**Comment by benwa** [comment]
I just got this too and made a pen to demo: http://codepen.io/_benwa/pen/ozVAgo?editors=1000#0

It does work correctly with flexmode

**Comment by mdo** [comment]
Likely the `display: table` styles interfering with one another. It's the risk we run of building the card deck the way we have... 🤔

**Comment by owre** [comment]
Same thing happens when input-group is used inside a table. [demo](http://codepen.io/anon/pen/vXwBRx)

**Comment by mdo** [comment]
Won't be an issue anymore with #21389—we're going all in on flexbox, thereby removing the table-based styles like the ones powering input groups.
