### ISSUE TITLE
v4 alpha 5 - navbar toggler inconsistencies

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#21012]
It seems that `.navbar-toggler` only gets a `background-image` applied if it is in a `.navbar-dark` or `.navbar-light` for example.  This doesn't seem right - it should always get a background-image, and there should be a class to turn this off.  Otherwise we can't use FontAwesome icon easily with `<i class="fa fa-bars"></i>`.

**Comment by niftylettuce** [comment]
<img width="741" alt="screen shot 2016-10-26 at 1 06 26 am" src="https://cloud.githubusercontent.com/assets/523141/19714002/a2642826-9b18-11e6-9155-5e5e24ca0615.png">

**Comment by mdo** [comment]
I'm going to leave this as-is, save for one thing.

- The toggler, like all our other styles in the navbar, requires a theme class to be set. There shouldn't be any navbars without a light or dark modifier. No changes here.

- If you need to use custom icons, that'll be possible again without having to modify a Sass variable. I've moved the toggle back to an additional element, `.navbar-toggler-icon`, for easier modification. Use it as-is, or drop it for your own.

That's coming in #21390.
