### ISSUE TITLE
v4 alpha 5 - spacing documentation inaccurate

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#21011]
https://v4-alpha.getbootstrap.com/utilities/spacing/

<img width="854" alt="screen shot 2016-10-26 at 12 17 14 am" src="https://cloud.githubusercontent.com/assets/523141/19713150/9f685fa4-9b11-11e6-92c3-0972006e3546.png">

> `a - for classes that set a margin or padding on all 4 sides of the element`

is deprecated

as it is now

`p-0` instead of `pa-0` and `m-0` instead of `m-a-0`

**Comment by Starsam80** [comment]
Already fixed in `v4-dev`: https://github.com/twbs/bootstrap/pull/20966/commits/8e888796a64ba89b69fb1af7b8e295d050b17ca1

**Comment by niftylettuce** [comment]
cool thx @Starsam80
