### ISSUE TITLE
mode move up

### ISSUE THREAD

**Issue by desireluqilai** [twbs/bootstrap#21025]
hi,all:
   When i show a mode of a child page(this page is realized by load(url) of jquery),the parent divs will move up 1px each time,and the button for call a function to show mode has ‘data-toggle="modal"’.If you know the reason for this phenomenon,please tell me,thanks!

**Comment by patrickhlauke** [comment]
for help/how-to, please use stackoverflow. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
