### ISSUE TITLE
Support <script defer>

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#21029]
```
<script defer src="jquery.js">
<script defer src="bootstrap.js">
<script defer src="my-stuff.js">
```

Either support, or recommend using defer.

This should make pages faster to load, as the js is fetched async, not serially, then executed in order at the end.

"defer" is safe to use in IE 10+ (see https://github.com/h5bp/lazyweb-requests/issues/42 and caniuse)

Correct usage  seems to be "defer", **not** "async defer".

I use it happily with Bootstrap 3. NB: It may cause issues with js and  'document ready' times, e.g. some ajax-created tabs that used data-toggle tags now have to be .show()'ed instead.

**Comment by bardiharborow** [comment]
Bootstrap still has support for IE <= 9, so we can't recommend this to everyone. We may be able to add a section somewhere about this, but I'm more inclined to leave it for now.

**Comment by mdo** [comment]
Punting as a won't fix for now.

**Comment by saturdaywalkers** [comment]
Fair enough as you want to get v4 out the door.

But maybe consider a few new tests for the js, especially the auto init'ed bits that can fire on jquery ready like tabs. At least 4.1 the suggestion.

**Comment by ryansobol** [comment]
Could you please re-evaluate this decision now that Bootstrap 4 has dropped support for IE 9?

http://caniuse.com/#feat=script-defer

**Comment by aavmurphy** [comment]
@mdo - reconsider `<script defer>` ? maybe for 4.1

**Comment by aavmurphy** [comment]
@mdo  reconsider <script defer> for v5
