### ISSUE TITLE
Unwanted style "height: 0px" in navbar-toggleable-{} after hide

### ISSUE THREAD

**Issue by m5seppal** [twbs/bootstrap#21030]
Hi,

I'm trying to make navbar using flexbox. It's working now otherwise but when I toggle open and close once, then javascript adds extra style "height: 0px" to navbar-toggleable-{} element. It stays on place when I resize window and makes flexbox to think that center of the element is at top of element, which mixes up the layout. If I manually remove this, then everything works. Following picture shows the problem:

![picture4](https://cloud.githubusercontent.com/assets/22469162/19782310/f5fb0daa-9c95-11e6-984d-b61cba7e049f.png)

I did some debugging and found that if I add .removeAttr('style') to complete, then everything seems to work.

      let complete = () => {
        this.setTransitioning(false)
        $(this._element)
          .removeClass(ClassName.COLLAPSING)
          .addClass(ClassName.COLLAPSE)
          .removeAttr('style') // seems to fix the problem
          .trigger(Event.HIDDEN)
      }

Is this bug in javascript? I don't see any need to leave that "height: 0px" to element, since if it's closed, then display = none. And if it's open, height shouldn't be a zero anyway.

What is right way to fix that?

**Comment by mdo** [comment]
Update to Alpha 5 and/or the latest `v4-dev` code. I believe we fixed this with the handful of JS updates we made in our last release.

**Comment by m5seppal** [comment]
Yes update to Alpha 5 fixed the problem. I already thought that I'm using it but I was still using Alpha 4 in one project.
