### ISSUE TITLE
line-height is not specified for page-links

### ISSUE THREAD

**Issue by stefan-staynov** [twbs/bootstrap#21039]
I've noticed that the `pagination` component is slightly bigger than `button`'s and `form-control`'s. `form-control`'s and `button`'s have their `line-height` set to 1.25. This is not the case for `page-link`'s. When I place a `button` or a `form-control` next to a `pagination` components, they look out of place. It makes sense to me to apply `line-height: 1.25` to `page-link` as well and make all components the same height.

Here is an example of what I'm talking about: [http://codepen.io/anon/pen/ALkJyw](http://codepen.io/anon/pen/ALkJyw)

Bootstrap v4 alpha5

**Comment by syhc** [comment]
This solution will only solve regular and `lg` sized `form-control `and `pagination`.

In this example, you will notice that the button is slightly smaller: [http://codepen.io/anon/pen/dONpgZ?](http://codepen.io/anon/pen/dONpgZ?)

For `sm`, the `pagination padding-y-sm: .275rem !default;` differs from `btn-paddding-y-sm: .25rem !default;`,

**Comment by stefan-staynov** [comment]
Thanks for the info, I haven't noticed this. I will update the line-height for all pagination sizes.

**Comment by mdo** [comment]
Merged #21052 so closing. Thanks!
