### ISSUE TITLE
Consider using html 5.1 <details> for show hide with fallback.

### ISSUE THREAD

**Issue by DavidMacDonald** [twbs/bootstrap#21038]
Support for `<details>` is improving, perhaps implement it with a fallback.

**Comment by patrickhlauke** [comment]
we'd need to explore if `<details>` offers the same flexibility in structure/styling as current custom methods, but in principle sure, all for it

**Comment by mdo** [comment]
Premature closing from mobile, sorry.

I don't think we'll end up doing this given the accordion, more flexible markup, multiple triggers, and styling options of what we have today.
