### ISSUE TITLE
Better hover/active customization in button mixin

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21037]
See #19414.

Ideally we could do better than a specific darken/lighten value.

**Comment by sqal** [comment]
> Ideally we could do better than a specific darken/lighten value.

If I may throw an idea out here. Perhaps we can use sass maps to define buttons styles:

```
$buttons: (
  primary: (
    color: $white,
    background-color: $brand-primary,
    hover-color: $white,
    hover-background-color: darken($brand-primary, 20%)
  ),
  outline-primary: ()  
  ...
)
```

Wouldn't it be more flexible? Because sometimes apart from the usual color change, I would also like to add other button types or remove those I don't need at all in my project. What you think? :)

**Comment by mdo** [comment]
Dupe of #19353.
