### ISSUE TITLE
Input group in navbar not working with flexgrid

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#21045]
Trying to put an input group in navbar with flexbox grid gives the following: https://plnkr.co/edit/tAvMQX3uR9UIEspLEYpO?p=preview

While the default grid gives: https://plnkr.co/edit/E2dNnfGGdfBCGyMVrX8S?p=preview

**Comment by mdo** [comment]
This looks good to go in `v4-dev` with the latest input group fixes we've made there. https://jsbin.com/vegofav/edit?html,css,output
