### ISSUE TITLE
Suggested change in Documenation

### ISSUE THREAD

**Issue by buttflattery** [twbs/bootstrap#21043]
Please update the command 

`composer require twbs/bootstrap to`

`composer require "twbs/bootstrap:*"`

as the your command gives 

>  [InvalidArgumentException]
>   Could not find package twbs\bootstrap at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by mdo** [comment]
I'm assuming this is for v4?

**Comment by bardiharborow** [comment]
This is for v3. The v4 command is `composer require twbs/bootstrap:4.0.0-alpha.5`.

**Comment by mdo** [comment]
Ah, closing out then. Thanks @bardiharborow <3.
