### ISSUE TITLE
.col-xs has width: 100%

### ISSUE THREAD

**Issue by sbaechler** [twbs/bootstrap#21040]
This was added in Alpha.5 and changes the flexbox behavior. The columns are now always stacked.

If this change was on purpose then the docs for flexbox grid should be updated. But I think this is a bug.

**Comment by mdo** [comment]
Works for me with the latest from `v4-dev`. See https://jsbin.com/jireka/edit?html,css,output.

**Comment by sbaechler** [comment]
My columns had `flex: 0 0 auto`. So strictly speaking they were not on the grid anymore and I guess I should not have used row and col.
