### ISSUE TITLE
Custom checkboxes don't work without indicator

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#21048]
Custom checkboxes don't work without an indicator:

https://plnkr.co/edit/ZiJJbkXhCGwcLHpqsDr9?p=preview

**Comment by bardiharborow** [comment]
Your issue here is that custom checkboxes are broken in cases where the `.custom-control-description` label has no content.

**Comment by natcohen** [comment]
Yes but there should be a way to create a custom checkbox without text...

**Comment by mdo** [comment]
Works fine for me I think. What's broken?

https://jsbin.com/jejefuh/edit?html,css,output

**Comment by natcohen** [comment]
@mdo Did you check my plunker? I don't see what's different but yours works...

**Comment by bardiharborow** [comment]
@mdo the crucial bit that I missed, is that this only happens with flexbox enabled.

**Comment by natcohen** [comment]
> @mdo the crucial bit that I missed, is that this only happens with flexbox enabled.

@bardiharborow Well... when using default (and not flexbox), I'm getting the same issue:
https://plnkr.co/edit/gPVBndoMC3rejmhxkJYx?p=preview

**Comment by mdo** [comment]
Could've been #20730? I'm using the latest CSS in my demo.

**Comment by natcohen** [comment]
@mdo Maybe... Can you please check that it works with flexbox (I don't know how to get the latest version...) so I can close this issue?

**Comment by mdo** [comment]
I've updated my demo at https://jsbin.com/jejefuh/edit?html,css,output to be flexbox and it does work with the latest from `v4-dev`. Closing out.

> I don't know how to get the latest version...

You can clone the project and switch to the `v4-dev` branch. Everything in the `dist` subdirectory should be the latest (or very close to it). Alternatively, you can download the compiled assets from [our releases page](https://github.com/twbs/bootstrap/releases).
