### ISSUE TITLE
ScrollSpy clears active nav-item on Safari when rubber-band scrolling past the top of page

### ISSUE THREAD

**Issue by RobRuana** [twbs/bootstrap#21055]
ScrollSpy clears active nav-item on Safari when rubber-band scrolling past the top of page. If the first ScrollSpy target is at the very top of the page, the active nav-item that links to it will be cleared when the rubber-band effect pulls the page past the top.

![scrollspysafaribug](https://cloud.githubusercontent.com/assets/2592431/19869168/6c6df8ce-9f68-11e6-969b-d7a19acc81e2.gif)

[JS Bin test case](http://jsbin.com/jukihe/edit?html,output)

Issue is a regression introduced by: https://github.com/twbs/bootstrap/commit/e8af21cc9db7941de217113cef5c7d1640dd86d5

Issue has been reproduced on:
- macOS Sierra 10.12.1, Safari 10.0.1
- iOS 10.1, Mobile Safari

**Comment by malikfaizanhaider** [comment]
Same here !
