### ISSUE TITLE
Update grid classes to omit `xs` abbreviation

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21059]
Following up on #20926 and #20934, we need to update our grid classes to omit the `-xs` part from those classes.

**Comment by leetskills** [comment]
How would this affect people like me who create their own breakpoints (e.g. `xxs`)?

**Comment by mdo** [comment]
@leetskills Whatever is the first breakpoint won't have an abbreviation in the class name. So if you have `xxs` in addition to `xs`, `sm`, `md`, `lg`, and `xl`, only the `xxs` classes would be without that in their classes.

**Comment by ETNOL** [comment]
I have the grid framework updated. This will also require updating all instances of the col-xs-* classes used from the documentation, correct? Or should some backward-compatibility be considered?

**Comment by mdo** [comment]
> This will also require updating all instances of the col-xs-* classes used from the documentation, correct? Or should some backward-compatibility be considered?

Yes, it'd require that. No need for backward compatibility—we're still in alpha.

**Comment by mdo** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/21086.
