### ISSUE TITLE
q tag for Bootstrap?

### ISSUE THREAD

**Issue by greg-raven** [twbs/bootstrap#21054]
Have you ever considered adding a q tag CSS definition in Bootstrap? Here's the one I've been using:

// HT: Disgruntled Goat
// http://stackoverflow.com/users/37947/disgruntledgoat
q:before { content: "\201c"; }
q:after { content: "\201d"; }
q q:before { content: "\2018"; }
q q:after { content: "\2019"; }

**Comment by mdo** [comment]
Most browsers handle the quotes automatically: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q. As such, we won't be adding anything else to tackle that.
