### ISSUE TITLE
<br> after closing 'Alert'

### ISSUE THREAD

**Issue by MircoSchlatter** [twbs/bootstrap#21066]
Hey there, 

I throw out my `alert` above the `navbar`. When the Alerts are closed there is a `<br>` left which lets ugly space up there. On page reload everything is back to normal. (The code is in the picture below.)

Is this technically wanted, because it should not be used above the navbar?
Tested on newest version of Chrome &  Safari  (Bootstrapversion: 4.0.0-alpha.5 )

Kind Regards 
Mirco

<img width="240" alt="bildschirmfoto 2016-11-01 um 20 43 48" src="https://cloud.githubusercontent.com/assets/20202518/19904770/593fb8b6-a074-11e6-9a85-8ea6717b3118.png">

**Comment by mdo** [comment]
We don't add `<br>`s anywhere, so that's not coming from us. There is the clearfix from the `.row` there with the `::after`, but that's unrelated to the `.alert` as well.

**Comment by MircoSchlatter** [comment]
Sorry, my bad! That came from my own class :(...
