### ISSUE TITLE
About classes that respond to breakpoints

### ISSUE THREAD

**Issue by saviomd** [twbs/bootstrap#21061]
@mdo, with the omition of 'xs' in floats, margins, paddings, etc (which I think is a great idea as I said https://github.com/twbs/bootstrap/pull/20934#issuecomment-254705147), the names got a little weird IMO:
```
.float-left
.float-sm-left
.float-md-left
.float-lg-left
.float-xl-left
```

I would suggest to go with:
```
.float-left
.float-left-sm
.float-left-md
.float-left-lg
.float-left-xl
```
I think that it's a lot more readable, easier to understand and go to the same direction as BEM (block/original class `.float-left`, modified class `.float-left--sm`) that I know you don't like but it makes easier to see if the class is a brand new one or one that extends/changes a previous one.

It will be a hell of a work to change everything again (and a biggier change from v3) but the outcome would be better (again, IMO)

What do you think?

**Comment by mdo** [comment]
Having the breakpoint in the middle of the class name is a purposeful decision that matches our grid system (e.g., `float-sm-left` and `col-sm-8`). Putting it in the middle allows for easier searching/grepping IMO. I don't see a huge benefit to switching it out right now, but I'm open to reconsidering for the future.

**Comment by saviomd** [comment]
> Having the breakpoint in the middle of the class name is a purposeful decision that matches our grid system (e.g., float-sm-left and col-sm-8).

My idea was to change everything (including the grid) to the end, to keep the consistency

> Putting it in the middle allows for easier searching/grepping IMO. I don't see a huge benefit to switching it out right now, but I'm open to reconsidering for the future.

Ok, understood, thanks for the feedback!
