### ISSUE TITLE
All custom form background not found in firefox

### ISSUE THREAD

**Issue by Thibault34** [twbs/bootstrap#21071]
Hello,

http://v4-alpha.getbootstrap.com/components/forms/#custom-forms

Background not work in firefox, can you help me please ?

**Comment by Lausselloic** [comment]
Hello,

Yes, this bug had been fixed by @patrickhlauke see https://github.com/twbs/bootstrap/pull/20962

Need to get back this patch to your version or wait for the alpha.6 release
