### ISSUE TITLE
Multiple accordions collapse each other

### ISSUE THREAD

**Issue by dmbaughman** [twbs/bootstrap#21074]
When multiple accordion-type collapse groups are on a page, expanding a new item in one group collapses the open item in the other accordion.

The example below shows two collapse groups with unique IDs on the parents and unique IDs on each section.  Clicking on a collapsed section on either group will close the open section on the opposite group.

http://codepen.io/dmbaughman/pen/xRKrwN

Version, OS, Browser details:

* Bootstrap v4.0.0-alpha.5 (via maxcdn.bootstrapcdn.com)
* MacOS Sierra 10.12.1
* Replicated behavior on:
  * Chrome 54.0.2840.71
  * Firefox 48.0.2
  * Safari 10.0.1

**Comment by bkdotcom** [comment]
you reuse the ids `headingOne`, `headingTwo`, & `headingThree`

**Comment by dmbaughman** [comment]
@bkdotcom Thanks for catching that, I fixed those duplicates.  The bug still persists as described.

**Comment by Johann-S** [comment]
Will be fixe in the next release, see : https://github.com/twbs/bootstrap/pull/18847

**Comment by dmbaughman** [comment]
@Johann-S thanks, I figured this had already been discovered but couldn't find the existing issue.

**Comment by Johann-S** [comment]
You're welcome @dmbaughman 😉
