### ISSUE TITLE
Provide a link to _variables.scss on website.

### ISSUE THREAD

**Issue by jcoyne** [twbs/bootstrap#21072]
On this page http://v4-alpha.getbootstrap.com/getting-started/options/ it says to find _variables.scss, but that isn't easy to find.  Can there be a link to it?

**Comment by patrickhlauke** [comment]
Not really, since to customize it, you'd need to find it on your own local copy. Linking to _variables.scss in the GitHub repo would be fairly pointless?

**Comment by jcoyne** [comment]
@patrickhlauke the text on the website says:
> You can find and customize these variables for key global options in our _variables.scss file.

**Comment by patrickhlauke** [comment]
yes...but as you do that to your local version (note the "Override a variable’s value and recompile with the included Gruntfile as needed." which of course means doing it locally), there's no point linking to the scss file in the bootstrap repo. or what kind of link did you envisage here?

**Comment by jcoyne** [comment]
I really have a documentation problem. I don't know which variables I could set.  In bootstrap 3, I could look  at this page to see: http://getbootstrap.com/customize/#less-variables

Here's my example scss file:
```scss
$border-radius: 0;
@import 'bootstrap';
```

I'm using the  Ruby on Rails asset pipeline with bootstrap installed as a gem. So, although I could find, `_variables.scss` on my system, most users won't have to if there was good documentation.

**Comment by wolfy1339** [comment]
Bootstrap v4 is still in Alpha, and the documentation is far from complete. And I believe that this was proposed somewhere else too (having a list if variables you can change)

**Comment by patrickhlauke** [comment]
so it's not really about providing a link to the scss file, but rather about providing documentation/listing of all the available variables?

**Comment by jcoyne** [comment]
@patrickhlauke that would be another acceptable way to fix this issue

 @wolfy1339 I'm aware this is alpha, that's why I'm testing now. If you can find a duplicate ticket, feel free to close this.

**Comment by mdo** [comment]
As @patrickhlauke mentioned, would a link to the file hosted on GitHub.com suffice? It'd be https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss.

Practically speaking, those docs are for compiling with Sass locally, meaning you'd have a familiarity with the Sass file structure, how to compile, overriding `!default` variables, etc. Perhaps additional documentation is required for that, too?

**Comment by jcoyne** [comment]
@mdo I think that having a link to the github file is the perfect solution for now.  I think there are plenty of other good resources for how to use SASS on the web and I don't think we need to document that.
