### ISSUE TITLE
Can't find bootstrap-theme.css for version ^4.0.0-alpha.4

### ISSUE THREAD

**Issue by pankajparkar** [twbs/bootstrap#21078]
I had bootstrap 3.3.7 version. Now I'm looking to migrate it to bootstrap v4.

I have included bootstrap.min.css with [bootstrap-theme.min.css](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css), but while migrating it to v4 I don't find from where I can get `bootstrap-theme.min.css` for latest v4 release.

**Comment by patrickhlauke** [comment]
Separate theme has been removed from v4

> Replaced the separate optional theme with configurable options via SCSS variables

http://v4-alpha.getbootstrap.com/migration/#global-changes

**Comment by pankajparkar** [comment]
@patrickhlauke I went through that migration guide. 

Still don't understand "from where I can get"/"how can I apply" `bootstrap-theme` to my application?

**Comment by wolfy1339** [comment]
@pankajparkar you have to recompile the SCSS source with `$enable-gradients: true;`

**Comment by patrickhlauke** [comment]
http://v4-alpha.getbootstrap.com/getting-started/options/

**Comment by pankajparkar** [comment]
@wolfy1339 I put `$enable-gradients: true;` in `_varaible.scss` & compiled `scss` to `bootstrap.css` but didn't get exact `bootstrap-theme.css` look and feel. Am I missing something silly? I want to get exact `bootstrap-theme.css` which was there in bootstrap 3.3.7 version.

**Comment by wolfy1339** [comment]
Maybe add `$enable-shadows: True;` too? Other than this variable there's no other one there to enable v3-like options. I would try posting this on StackOverflow, and link your question back here. It would help other users who want the same thing

**Comment by pankajparkar** [comment]
@wolfy1339 Thanks for response. You suggestion got work for me. After applying your suggestions my navbar css wasn't getting applied. Thereafter an hour time googling found that, navbar has been fully re-written in `v4`, so I completely missed that part.

I end up re-writting `navbar` by referring new [Navbar API](http://v4-alpha.getbootstrap.com/components/navbar/#nav).

No need to add question in SO I guess.

@wolfy1339 small question, Is it OK if I start using v4 alpha version for production app?

**Comment by patrickhlauke** [comment]
> Is it OK if I start using v4 alpha version for production app

alpha means alpha...there can still be drastic changes to the markup, styling and JS behavior. if you decide to use it in production, you need to be aware that things can and will change (so if you pull a newer version of v4 later on, it may require you to go back to your production app to adapt that to any changes that happened in the meantime).

**Comment by pankajparkar** [comment]
@patrickhlauke Can I get roadmap link of BS v4 next releases & upcoming things?

**Comment by wolfy1339** [comment]
#20631

**Comment by wolfy1339** [comment]
For reference here's my SO question and answer: http://stackoverflow.com/q/40428410/3411410
