### ISSUE TITLE
More Beauty card-footer on card-outline

### ISSUE THREAD

**Issue by SuperWangCC** [twbs/bootstrap#21070]
# More Beauty card-footer (suggestion)
### When the card set to outline-color*. the card footer become ugly.
so we can add card-outline-color support for the card-footer.
![_001](https://cloud.githubusercontent.com/assets/8223268/19926336/f70ea498-a12e-11e6-87af-32ff82157383.png)

**Comment by rafalp** [comment]
Header and footer styles are basic for purpose of custom theming.

**Comment by guylepage3** [comment]
I'm with @rafalp. I definitely do not want more styling added to bootstrap. Simplicity is something I would like to begin pushing for.

**Comment by mdo** [comment]
We won't be making changes to support theming of the inner components. One thing I might do is make those background-colors `rgba` so they can blend easier with parent backgrounds, but that's about it.

**Comment by javis2** [comment]
I agree with @SuperWangCC that it would have been nice to have the header and footer take on the same colour scheme as the outline class applied.

However, adding "bg-*** text-white" to the card-header or card-footer produces a good result.

For example:

    <div class="card" card-outline-success>
        <div class="card-header bg-sucess text-white">Header</div>
        <div class="card-block">
            Content
        </div>
    </div>`

![capture](https://cloud.githubusercontent.com/assets/24308857/21375881/d44033c4-c784-11e6-96ed-307870801856.JPG)
