### ISSUE TITLE
Don't expose class names such as "hidden"

### ISSUE THREAD

**Issue by ibc** [twbs/bootstrap#21084]
Bootstrap should just expose namespaced or prefixed class names. The fact that it declares a global CSS class named "hidden" produces conflicts when CSS styles other than just Bootstrap is used in any website.

This becomes even more problematic when a 3rd party widget is inserted into a website made with Bootstrap. The widget may define it's own "hidden" class but just for elements within a specific namespace or CSS selector, something such as:

```css
.3rdPartyWidget .hidden {
  // something here
}
```

Unfortunately Bootstrap exposes a global `hidden` class that includes `display: none !important` and much more stuff like that.

Bootstrap shouldn't be "God" but a component within a website or web application.

**Comment by mdo** [comment]
This was changed in v4; we no longer have straight `.hidden` classes anymore with our work on v4.

**Comment by ibc** [comment]
Nice to know. Thanks a lot.
