### ISSUE TITLE
Button toggle functionality is broken

### ISSUE THREAD

**Issue by troarie** [twbs/bootstrap#21087]
The data-toggle functionality no longer works for buttons that have no additional semantic - a button with a type attribute = "button". Please refer to the spec:  https://www.w3.org/TR/html-markup/button.button.html.

This holds for a single button or a group of buttons. So for example, consider this markup: 

\<ul class="btn-group" data-toggle="buttons">
     \<li>
           \<button class="btn btn-default" type="button" </button>
           \<button class="btn btn-default" type="button" </button>
      \</li>
\</ul>

With the simple example above, it is expected that when you click either of the buttons, it would  toggle the active state of the clicked button. This functionality worked well in all versions up to v3.3.4 and seems to be broken in 3.3.7.

**Comment by patrickhlauke** [comment]
This seems to be working fine https://jsfiddle.net/11o6oxcg/1/

I think the issue you're seeing is rather related to the fact that there is no `btn-default` anymore in v4 (which then in turns means that a button with `class="btn btn-default active"` looks no different visually from `class="btn btn-default"` - see http://v4-alpha.getbootstrap.com/migration/#buttons

**Comment by troarie** [comment]
I might have not clearly indicated this in my issue description - the issue was created against v3 not v4. So this is basically a "maintenance" request for the v3-dev code branch. The underlying problem is that the button data toggle function (https://github.com/twbs/bootstrap/blob/v3-dev/js/button.js#L52) does not apply or remove the active class to the button elements. Please note this functionality does work properly in v3.3.4, so something must have been broken in between these versions. This is a bug that breaks our application.

Our current solution (until the next v3.3.x version is released) is to detach the button data api altogether and plug in a custom version that does the toggling correctly. A solution would be to add a check if the underlying element is a button and if so apply the toggle action: 

```javascript
Button.prototype.toggle = function () {
    var changed = true
    var $parent = this.$element.closest('[data-toggle="buttons"]')

    if ($parent.length) {
      var $input = this.$element.find('input')
      if ($input.prop('type') == 'radio') {
        if ($input.prop('checked')) changed = false
        $parent.find('.active').removeClass('active')
        this.$element.addClass('active')
      } else if ($input.prop('type') == 'checkbox') {
        if (($input.prop('checked')) !== this.$element.hasClass('active')) changed = false
        this.$element.toggleClass('active')
      } else if (this.$element.prop('type') == "button")
        this.$element.toggleClass('active') 

      $input.prop('checked', this.$element.hasClass('active'))
      if (changed) $input.trigger('change')
    } else {
      this.$element.attr('aria-pressed', !this.$element.hasClass('active'))
      this.$element.toggleClass('active')
    }
