### ISSUE TITLE
collapse toggle clears checkbox selection

### ISSUE THREAD

**Issue by sebastienros** [twbs/bootstrap#21082]
When applying a `data-toggle="collapse"` using a checkbox, the target is correctly shown/hidden but the checkbox tick is cleared.

Example:
http://codepen.io/anon/pen/KNKMQR

Expected:
When clicking on the label or the checkbox, the target opens up and the checkbox is ticked.

Actual:
The target appears but the checkbox is not ticked.

**Comment by mdo** [comment]
Same as #21079.
