### ISSUE TITLE
Modal title padding named wrong

### ISSUE THREAD

**Issue by chmieludaniel** [twbs/bootstrap#21080]
Version: v4.0.0-alpha.5

In source variables we can find `$modal-title-padding`. As the name indicates it should be applied to `.modal-title`, but in fact it's applied to: `.modal-header`.

Either change variable name to `$modal-header-padding`, or apply this value to `.modal-title`

Source:
_variables.scss on line 690
```
$modal-title-padding:         15px !default;
```

_modal.scss on line 77
```
.modal-header {
  padding: $modal-title-padding;
  border-bottom: $modal-header-border-width solid $modal-header-border-color;
  @include clearfix;
}
```

**Comment by mdo** [comment]
#21118 was merged, so this is fixed.
