### ISSUE TITLE
.nav-link has padding when navbar is collapsed

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#21081]
Button elements with the `.btn-link` class have a left padding when the navbar is collapsed.

This can partially be traced to the `padding` property for the `.btn` class in [_buttons.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L17).

![image](https://cloud.githubusercontent.com/assets/10222521/19973692/38ae6a7a-a1e6-11e6-9a7b-5794a4101b28.png)

# Example
```html
<nav class="container navbar navbar-dark bg-inverse">
  <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
  <div class="collapse navbar-toggleable-md" id="navbarResponsive">
    <ul class="nav navbar-nav">
      <li class="nav-item"><a class="nav-link" href="#foo">Foo</a></li>
    </ul>
    <form method="post" id="logoutForm" class="form-inline float-lg-right" action="/Account/LogOff">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" title="Manage" href="/Admin">Hi Alice!</a>
        </li>
        <li class="nav-item">
          <button type="submit" class="btn btn-link navbar-btn nav-link">Log off</button>
        </li>
      </ul>
    <input name="__RequestVerificationToken" type="hidden" value="..." /></form>
  </div>
</nav>
```

The "Log off" `button` which has the `.btn`, `.btn-link` and `.nav-link` classes have padding to the left which makes it not align vertically with the navbar link(s) above.

**Comment by mdo** [comment]
That's because you're mixing button classes with the nav bar classes. Remove the `.btn` and `.btn-link` for more accurate styling, though we may need to reset the `background` and `border` for `<button>` elements.

**Comment by vanillajonathan** [comment]
![image](https://cloud.githubusercontent.com/assets/10222521/20179319/df6fca38-a755-11e6-8daf-0255356f8eb1.png)

This is after removing `.btn` and `.btn-link`. Now the button element has `.navbar-btn` and `.nav-link`.

**Comment by mdo** [comment]
Going to punt on doing this because it gets messy pretty quickly. You can place buttons anywhere else in the navbar, but styling them as links requires overriding the properties I listed above and reseting a few other things. Might revisit in the future, and I'm open to PRs if folks want to take a stab anyway.
