### ISSUE TITLE
Printing documentation broken

### ISSUE THREAD

**Issue by youradds** [twbs/bootstrap#21083]
The printing of documentation pages (http://v4-alpha.getbootstrap.com/layout/grid/ for example) is broken. I tried printing it on paper, and it cuts the page off. I then tried it with a PDF printing, and same issue (see attached). It seems to negative margin the pages, so they get cut right down the middle, so are unusable.

[grid.pdf](https://github.com/twbs/bootstrap/files/571072/grid.pdf)

**Comment by patrickhlauke** [comment]
As there are also issues in IE11 relating to printing, closing this issue in favor of https://github.com/twbs/bootstrap/issues/21092
