### ISSUE TITLE
Printing broken in IE11 and Firefox

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#21092]
Using the v4 alpha documentation as a case in point, when printing in IE11 only the very first page is printed (instead of 17 or so pages, only 1 page is printed), while printing in Firefox results in all pages after the first one being offset to the left and cut off.

> ![v4-print-firefox](https://cloud.githubusercontent.com/assets/895831/20036775/786b6c88-a409-11e6-8135-12c499520aec.PNG)

xref: https://github.com/twbs/bootstrap/issues/21083 and https://github.com/twbs/bootstrap/issues/20814#issuecomment-251591737

**Comment by patrickhlauke** [comment]
Printing works correctly in Chrome, Safari and Edge though

**Comment by slavanga** [comment]
The ```*::first-letter``` selector in _print.scss is causing the problem in IE11:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_print.scss#L16

I could not reproduce this issue in Firefox v49.0.2 on Windows.

Related: https://github.com/h5bp/html5-boilerplate/pull/1799

**Comment by patrickhlauke** [comment]
@slavanga the first-letter issue was causing a crash. even after fixing, it in alpha 5, printing itself isn't working correctly in IE. see https://github.com/twbs/bootstrap/issues/20814#issuecomment-250981577

**Comment by patrickhlauke** [comment]
Zeroing in on the issue at least in Firefox, it appears related to flexbox and the sidebar in the docs. As soon as the sidebar isn't there anymore in the printed version (pages 2 and onwards), the main content is moved off-paper by the same width as the sidebar would have taken up in the printout. This may be a bug with Firefox...

**Comment by patrickhlauke** [comment]
As for IE11, initial trial and error suggests that removing
```
*,
  *::before,
  *::after,
  *::first-letter,
  p::first-line,
  div::first-line,
  blockquote::first-line,
  li::first-line {
    text-shadow: none !important;
    -webkit-box-shadow: none !important;
            box-shadow: none !important;
  }
```
from the bootstrap.css print styles also makes IE see/print the entirety of the page, rather than just the first page - likely a css parsing bug in IE?

**Comment by patrickhlauke** [comment]
ah, apologies @slavanga ... i got confused with the issue i solved regarding `::first-line`. it does indeed seem specifically about `*::first-letter` in IE. scoping this the same way it was scoped for `::first-line` fixes at least the IE issue.

**Comment by patrickhlauke** [comment]
The issue in Firefox appears to be a bug with how floated elements are handled across different pages - filed https://bugzilla.mozilla.org/show_bug.cgi?id=1315994

**Comment by cvrebert** [comment]
Firefox bug added to the Wall in f2bc3bec7cce34752ce27ade582dee6d3e060432.
