### ISSUE TITLE
Invisible border of input-group in inverse navbar

### ISSUE THREAD

**Issue by fredgate** [twbs/bootstrap#21098]
When in a **inverse** navbar I add a input-group containing a input and an add-on, the border of the input is badly rendered while the border of the add-on is ok. If the navbar is not inverse, all is fine.
Here is a jsfiddle showing the problem : [https://jsfiddle.net/mw7ts10m/](https://jsfiddle.net/mw7ts10m/)

![temp](https://cloud.githubusercontent.com/assets/3648269/20081388/93de9548-a54f-11e6-932c-a94b6547da2a.png)
The problem is with version alpha 5 (tested on firefox and IE11).

With the alpha 2 version, the borders was well rendered, as showed in this jsfiddle : [https://jsfiddle.net/mw7ts10m/2/](https://jsfiddle.net/mw7ts10m/2/)
It seems broken since alpha 3.

**Comment by abvalentine** [comment]
The reason is move to a translucent border color in commit c3e4cbdfb0eaff43db4de6b4df045f364e5500d2
This commit also affects `.custom-select` and `.input-group-addon`.

**Comment by abvalentine** [comment]
The commit was a fix for #19136. Maybe we should make semi-transparent a border of add-on.

**Comment by fredgate** [comment]
Here is the previous rendering with version aplha 2 :

![issue](https://cloud.githubusercontent.com/assets/3648269/20466875/97b867a8-af7b-11e6-958e-99043e2b8154.png)

**Comment by fredgate** [comment]
I tried to add `background-clip: padding-box;` to input-group-addon.
At first glance, it was not too bad, although the separator between the addon and the input is not very pretty. But there is another problem. When the input receives the focus, the blue border that it gains produces the inverse effect : the input seems higher than the addon.

Here is a screenshot showing the problem :

![issue](https://cloud.githubusercontent.com/assets/3648269/20466950/d8015ae4-af7c-11e6-94f7-fbb1f0e5ae98.png)

**Comment by tillkruss** [comment]
Seeing the same issue.

<img width="357" alt="screen shot 2017-01-01 at 2 18 39 pm" src="https://cloud.githubusercontent.com/assets/665029/21583243/4349c3a6-d02d-11e6-889d-c639710b64e6.png">
<img width="343" alt="screen shot 2017-01-01 at 2 18 57 pm" src="https://cloud.githubusercontent.com/assets/665029/21583244/434a9f42-d02d-11e6-8853-94c97075892c.png">
