### ISSUE TITLE
transition mixin does't work

### ISSUE THREAD

**Issue by mehranrasulian** [twbs/bootstrap#21091]
It doesn't work when I include it within my styles.
Also [within btn class](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L18), bootstrap is using transition while [I don't see any transition for buttons](https://jsbin.com/tetoyoruqo/edit?html,output).

I'm even not sure about `box-shaddow` mixin which is in [_mixin.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_mixins.scss)

**Comment by mdo** [comment]
The mixin includes logic to only render the `box-shadow` or `transition` when those are enabled by the [global options in our Sass](http://v4-alpha.getbootstrap.com/getting-started/options/). You need to set those variables, or not use the mixins.
