### ISSUE TITLE
Navbar problem

### ISSUE THREAD

**Issue by Epexa** [twbs/bootstrap#21105]
Hello!

I have a problem with the menu. If you make your browser window **smaller than 991 and more than 768** pixels, the menu is in **two lines**!

You can see it at the [official navbar example](http://getbootstrap.com/examples/navbar/)!

Browsers: Chrome latest, Safari latest, and i think others browsers also.

_This issue will happen such as a MacBook 11 inch._

Screenshots:
# **769px**
![navbar template for bootstrap](https://cloud.githubusercontent.com/assets/2198826/20112861/ff4e500c-a5fe-11e6-9602-79ff5acbf012.png)
# **990px**
![navbar template for bootstrap2](https://cloud.githubusercontent.com/assets/2198826/20112840/f25fc646-a5fe-11e6-9ce1-6a2e7a6a7252.png)
# **992px**
![navbar template for bootstrap3](https://cloud.githubusercontent.com/assets/2198826/20112847/f5e6285a-a5fe-11e6-8cf4-db558678e231.png)

**Comment by mdo** [comment]
The only solution here is fewer items in your navbar :).

**Comment by Epexa** [comment]
Bootstrap v4 also!

[Official navbar example](https://v4-alpha.getbootstrap.com/examples/navbar/)!

![navbar template for bootstrap](https://cloud.githubusercontent.com/assets/2198826/20119939/a62d55aa-a61b-11e6-87d6-9d9f6e970960.png)
