### ISSUE TITLE
navbar-right class overshoots container by 15 pixels

### ISSUE THREAD

**Issue by celare** [twbs/bootstrap#21101]
The navbar-right class has margin-right -15px presumably to reclaim the 15px padding of the container BUT it is floated right so this doesn't work and causes it to stick out the side of the container by 15px. You can see it clearly in the Bootstrap doc page for the Navbar Fixed Top (http://getbootstrap.com/examples/navbar-fixed-top/) using any modern browser. Can you confirm the best way to correct this problem? I'm currently just overriding with .navbar-right{margin-right:0px} to fix it but didn't know if maybe the doc page was wrong and maybe needed correcting by adding a different container around .navbar-right?

**Comment by celare** [comment]
Here are screenshots of it broken and fixed.

![fixed](https://cloud.githubusercontent.com/assets/2094130/20103370/a44ac376-a5c1-11e6-9ef4-229b6ee65ce9.png)
![broken](https://cloud.githubusercontent.com/assets/2094130/20103375/ad413514-a5c1-11e6-881e-e61d63e66d9c.png)

**Comment by mdo** [comment]
We're no longer actively working on v3, so this is a won't fix. No planned changes here.
