### ISSUE TITLE
Custom radio & checkbox doesn't work without custom-control-description

### ISSUE THREAD

**Issue by miguelmich** [twbs/bootstrap#21103]
When using custom radio and checkbox control without `custom-control-description` content the control stops firing the check attribute, you can see an example [here](https://jsbin.com/kalegubuna/edit?html,output)

Tested on latest Chrome & Firefox

I don't know if it's the intended behavior but I didn't find any information in the docs.

**Comment by miguelmich** [comment]
Currently I'm fixing it by applying a `min-height` to the `custom-control` but I guess is not the optimal solution

**Comment by mdo** [comment]
Duplicate of #20730, and already fixed in `v4-dev` branch.
