### ISSUE TITLE
Keep a class option without grid prefix (-xs, -sm, -md, -lg)

### ISSUE THREAD

**Issue by guizoxxv** [twbs/bootstrap#21106]
I tried Bootstrap 4 today and missed the option of using `float-right` instead of `float-xs-right`. Adding the option to specify the break point is a nice feature but I think that the option of using a class without those prefixes should be kept. I think it is more intuitive for those who are using `float-right` (or any other class with this new sintax) for any size.

Maybe another solution would be something like using only `float-right`, `float-sm-right`, `float-md-right` and `float-lg-right`.

**Comment by browner12** [comment]
i believe that final is what is in the works right now for the next alpha

**Comment by mdo** [comment]
Yeah, this is coming in `v4-dev`. Nearly everything but the grid classes have this done already.
