### ISSUE TITLE
Adding a tag (badge) in a button makes it taller

### ISSUE THREAD

**Issue by BrokenCrust** [twbs/bootstrap#21102]
If you add a tag (badge) to the text of a button then the button is slightly taller.  This is most noticeable in a button group but it is also taller when used in a standalone button.  

This issue was first reported against v3 and closed as won't fix, but it still happens in v4.0.0-alpha.5 in Firefox on Windows and Android.

[JSbin](https://jsbin.com/mazocayoma)

```
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary">Left</button>
  <button type="button" class="btn btn-secondary">Middle <span class="tag tag-primary">0</span></button>
  <button type="button" class="btn btn-secondary">Right</button>
</div>
```

**Comment by bardiharborow** [comment]
Confirmed on Chrome 55 and Firefox 51. `.tag { display: inline; }` fixes the height but breaks the padding.

**Comment by nested** [comment]
is this issue fixed ?
I tried to reproduce this issue and got that in  **bootstrap/scss/mixins/_border-radius.scss:19**
may be we can change to bottom instead of baseline. as @bardiharborow suggested.

**Comment by bardiharborow** [comment]
The current `vertical-align` was added by #8852 and seems quite purposeful. Testing indicates that changing `vertical-align` would cause alignment to go out of wack for things like headings. I'm having better luck with reverting 2ade44a. Need review by someone who gets CSS more. @mdo?

**Comment by PurvaA** [comment]
@BrokenCrust 
 
I fixed this issue and also tested in all the Browsers. To fix this I have written Javascript code. 

Please check my code in http://jsbin.com/xehaka/4/edit?html,js,output

Please let me know in case of any further concerns

**Comment by bardiharborow** [comment]
@PurvaA, we'll need a CSS-only solution to this.

**Comment by PurvaA** [comment]
@bardiharborow 

I removed Javascript code from my JSBin & used CSS Hack to fix this issue.

Please check Browser specific hack which I added http://jsbin.com/penaxehoro/edit?html,css,output & let me know in case of any further concerns/ queries/ suggestions

**Comment by vanduynslagerp** [comment]
The issue seems to be fixed in Alpha6: [JSBin](https://jsbin.com/xosetibise/1/edit?html,output)

**Comment by BrokenCrust** [comment]
Yes, this appears to be fixed (or no longer an issue anyway) in alpha-6, so I'm closing the issue.
