### ISSUE TITLE
Class .custom-controls-stacked should clear floats

### ISSUE THREAD

**Issue by PawelMysior** [twbs/bootstrap#21119]
Hi,

According to http://v4-alpha.getbootstrap.com/components/forms/#stacked you can wrap your custom checkboxes or radios in a `.custom-controls-stacked` parent to make them appear on separate lines instead of inline.

The `.custom-control` are floated when put inside that parent and thus do not add to the height of the parent element. I believe that the `.custom-controls-stacked` class should include the  `clearfix()` mixin to solve that issue.

Here is the relevant part of the source code: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L119-L128

**Comment by mdo** [comment]
I believe this was resolved when we fixed #20730.
