### ISSUE TITLE
Replace hardcoded breakpoints in Card, Carousel, Forms, Jumbotron, Modal, and Navbar

### ISSUE THREAD

**Issue by ArrayKnight** [twbs/bootstrap#21115]
The below hardcoded references don't allow all breakpoints to be replaced. One of the desired changes that my team would like to make is to replace all $grid-breakpoints to extend and rename.

Card: (sm)
- [Line 210](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L210)
- [Line 227](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L227)
- [Line 253](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L253)
- [Line 358](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L318)

Carousel: (sm)
- [Line 224](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_carousel.scss#L224)

Forms: (sm)
- [Line 311](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L311)

Jumbotron: (sm)
- [Line 7](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_jumbotron.scss#L7)

Modal: (sm, lg)
- [Line 118](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L118)
- [Line 132](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L132)

Navbar: (xs, sm, md, lg)
- [Line 11](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L11)
- [Line 40](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L40)
- [Line 287](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L287)
- [Line 293](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L293)
- [Line 300](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L300)
- [Line 306](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L306)
- [Line 313](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L313)
- [Line 319](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L319)

But if you replace [$grid-breakpoints](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L186) with something like:

`
$grid-breakpoints: (
  ms: 0,
  ml: 576px,
  ts: 768px,
  tl: 992px,
  ds: 1200px,
  dm: 1400px,
  dl: 1700px
);
`

Compilation errors are thrown for all of the above SCSS files. If these were replaced with variables that a developer could reassign to new breakpoints, or if there were some other logic in play that determined which breakpoints to use, we'd have more control/flexibility with breakpoints.

**Comment by ArrayKnight** [comment]
Maybe something like:
`$grid-breakpoints-internal: (`
`  xs: map-get($grid-breakpoints, xs),`
`  sm: map-get($grid-breakpoints, sm),`
`  md: map-get($grid-breakpoints, md),`
`  lg: map-get($grid-breakpoints, lg),`
`  xl: map-get($grid-breakpoints, xl)`
`) !default;`

Could be added and then internal references could be:

`@include media-breakpoint-up(map-get($grid-breakpoints-internal(sm)))`

Then if developers override `$grid-breakpoints` they can also reassign the internal set so no styling is lost. This seems fairly manual....

Another option would be to create a mixin that iterates over `$grid-breakpoints` looking for a dimension and returning the next larger breakpoint.
`@mixin breakpoint-greater-then($size, $breakpoints: $grid-breakpoints) {...}`

`$card-breakpoint-sm: 544px;`

`@include breakpoint-greater-than($card-breakpoint-sm) {...}`

**Comment by mdo** [comment]
I totally get the use case for this, but I'm not interested in going this route. I think our docs need updating to explain what to do when you change this variable instead of adding another layer of abstraction. Thanks though!
