### ISSUE TITLE
Advertised CDN link results in ERR_CERTIFICATE_TRANSPARENCY_REQUIRED in Chromium

### ISSUE THREAD

**Issue by bronger** [twbs/bootstrap#21129]
On http://getbootstrap.com/getting-started/, CDN links to bootstrap are mentioned, e.g. <https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css>.  But this link results in a “NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED” error in Chromium 53.0.2785.143.  I think this is because Google recently made their code more picky about certs.  The link should be replaced, or the provider should be urged to update the certificate.

**Comment by Starsam80** [comment]
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css works [perfectly fine for me in Chrome 56.0.2918.0](https://cloud.githubusercontent.com/assets/4411333/20255393/690f5cc2-a9f9-11e6-901f-ac703e56bf81.png). After some very quick research, it looks like its a bug in Chrome 53: https://sslmate.com/blog/post/ct_redaction_in_chrome_53 https://bugs.chromium.org/p/chromium/issues/detail?id=664177

**Comment by bronger** [comment]
Oh, in this case – I'm sorry for the noise.
