### ISSUE TITLE
Clarify when .mx-auto can be used

### ISSUE THREAD

**Issue by dinophile** [twbs/bootstrap#21123]
.mx-auto adds the `margin-left:auto` and `margin-right:auto` attributes but the browser will not center the elements that it is set on.  I don't have any other element surround the button I'm trying to center other than the body tag. The body tag has no classes applied to it either. 

Tested it on various elements such as the following (all of course nested within a div with the class `.container`):
`<p class="mx-auto">Hello?</p>`  and
`<button type="button" class="btn btn-lg mx-auto">Hello?</button>`

The following also fails to center (bootstrap.min.css is alpha 5, downloaded November 13 2016):
```
<!DOCTYPE html>
  <html lang="en">
     <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <title>Document</title>
     <link rel="stylesheet" href="css/bootstrap.min.css">
   </head>
   <body>
     <div class="container">
       <button type="button" class="btn btn-primary btn-lg mx-auto">HELP!</button>
     </div>
   </body>
  </html>
```

Browser does not position elements as expected with auto left and right margins. Inspecting the elements shows that the values are in fact set to auto on the margins. But there is no visual effect in the browsers at any screen size. (Chrome stable and Chromium stable both used)

The only way I could center my component was to give the `.container` div the  class of `text-xs-center`.

Ran all examples through validators and lint. Example included in JSBin link below. Cannot find duplicate issue, nor example on any search. 

- Operating system and version: Ubuntu 16.04 LTS (64-bit)
- Browsers and version:
 Chromium Version 53.0.2785.143 Built on Ubuntu  
 Chrome Version 54.0.2840.100 (64-bit)
- Reduced Test Case: http://jsbin.com/gefiladofu/edit?html,output

**Comment by hultberg** [comment]
You stylesheet in the jsbin example is using 3.3.6, and the `mx-auto` class is new in v4. Also, for `mx-auto` to work, one must use it on a node with width specified.

**Comment by dinophile** [comment]
Oh weird, I set the link tag to point to the alpha version using the CDN just to double check. And in my own file I'm using the newest version as well (v4 for sure, just verified!). 

Forgive me for asking a stupid question but...node with width specified? As in the parent div? What if I use it on a `<p>` within a div with a column width set? Ie `col-md-6` etc? 

Also when I use just plain margin-left and margin-right both set to auto in any of my other projects it sets the margins relative to the parent div whether I'm just using `<body>` or a specified parent with width set. So I'm not sure why I need to specify the width of the 

Apologies if I'm asking a stupid question! Not an expert by any means!

**Comment by hultberg** [comment]
"node with width specified" refers to the element having a width css-property defined, like:
```html
<p style="width:100px;" class="mx-auto">Im in center of the page.</p>
```

**Comment by dinophile** [comment]
Ah I see! Did not realize that!

 Could that be added to the docs then? It makes it seem like you can use the class on elements willy nilly! :)

**Comment by mateddy** [comment]
A side note, it seems that I could not apply mx-auto on canvas (with or without css-width defined).  My workaround is to wrap the canvas in a div and then apply mx-auto to the div.  Is this intended?

**Comment by bolohori** [comment]
Horizontal centering
Additionally, Bootstrap also includes an .mx-auto class for horizontally centering fixed-width block level content—that is, content that has display: block and a width set—by setting the horizontal margins to auto.

```
<div class="mx-auto" style="width: 200px;">
  Centered element
</div>
```
