### ISSUE TITLE
.input-group and .input-group-addon is not flex

### ISSUE THREAD

**Issue by Cranavvo** [twbs/bootstrap#21131]
Hello,

You have forgotten to change the display property of the input groups to flex. Because of this, odd little stylings of this utility occurs, for e.g. within tables:

![22a336cbc85842c0b04288404f8b3d0c 1](https://cloud.githubusercontent.com/assets/1441054/20274802/da6f8c68-aa8d-11e6-8b8d-b46ee8553cc5.png)

I found that using `display: flex;` on both classes and removing `width: 1%`; from `.input-group-addon, and .input-group-btn` fixes this issue.

@mdo

**Comment by ArunHub** [comment]
@Cranavvo if you use bootstrap-flex.css then it will be alright . In common bootstrap.css they used float layout so only .input-group-addon, and .input-group-btn have width:1%;

**Comment by Cranavvo** [comment]
@ArunHub I think a fix should be done in the CSS not including flex for these classes.

**Comment by mdo** [comment]
This should be fixed already in `v4-dev`.
