### ISSUE TITLE
Add responsive helpers to margins and paddings.

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#21134]
Everything is Boostrap 4 has the -sm -lg helpers expect the margins and paddings.
I am talking about this ones:
http://v4-alpha.getbootstrap.com/utilities/spacing/

I need this:
`<div class="menu mt-sm-3 mt-md-2"></div>`

Is really unfortunate that I need a custom css only to fix the margins and paddings.

**Comment by hultberg** [comment]
This is an upcoming feature in alpha 6, merged in #20926

**Comment by mdo** [comment]
Yup, already implemented in `v4-dev` branch.
