### ISSUE TITLE
col-form-label isn't same height with form-control / form-control-static in grid

### ISSUE THREAD

**Issue by kuz30** [twbs/bootstrap#21135]
Windows 10: Chrome 54, FF 49, IE 11, MS Edge.
Bootstrap 4 alpha 5.

Grid forms has different heights for labels and controls.
For example, [static controls from documentation](http://v4-alpha.getbootstrap.com/components/forms/#static-controls) colored here: [http://jsbin.com/moduvayane/edit?html,css,output](http://jsbin.com/moduvayane/edit?html,css,output)

**Comment by jesusmtzarvizu** [comment]
You can fix this problem by adding the attribute "float:left" on both, labels and controls, as you can see on the picture below: 

![issue](https://cloud.githubusercontent.com/assets/22154923/20368773/b19be814-ac12-11e6-8a3e-d5e1e3fd6f0d.png)

As you can see on the original web page the labels and controls have the attribute "float:left" as you can see on the image below, I put a circle on the left side as you can see:

![issue1](https://cloud.githubusercontent.com/assets/22154923/20368958/b20d69ac-ac13-11e6-81bb-bf3b4cf88b0c.png)

For some reason the CSS don't have this attribute when you are trying to use it

**Comment by kuz30** [comment]
The problem is in height, not in width. So floating doesn't fix the issue.
I guess label and form-control should have equal heights, 1px-broken line of text between label and text in contol looks so unnatural.

Label e-mail has: Padding top .5rem + Font-size 1rem * Line-height 1.5 + Padding bottom .5rem = 2.5rem.
Form-control-static has: Border-top 1px + Padding top .5rem + Font-size 1rem * Line-height 1.25 + Padding bottom .5rem + Border-bottom 1px.

There we have a gap in text line because of this difference. 2.5rem != 2,25rem + 2px.
May be same line-height + 1px border for label columns could be a solution?

**Comment by jesusmtzarvizu** [comment]
Oh Now I understand

**Comment by mdo** [comment]
Two potential fixes (one of which is coming in a general fix PR):

- Set a `height` on inputs. I've avoided doing this for awhile in v4 to keep things as flexible as possible.
- Use `calc()` to subtract those 2px from the label height.

Going with the latter route.
