### ISSUE TITLE
Error in Babel:dev task on grunt dist v4

### ISSUE THREAD

**Issue by thejimbirch** [twbs/bootstrap#21139]
Has anyone run into this?  Just downloaded the v4 release, npm installed, and grunt dist and got this error:

```
Running "babel:dev" (babel) task
Warning: /Users/Jim/Sites/energy/www/sites/all/themes/energy/bootstrap/node_modules/babel-plugin-transform-es2015-modules-strip/lib/index.js:4
      ModuleDeclaration(path) {
                       ^
Unexpected token ( Use --force to continue.

Aborted due to warnings.
```

**Comment by bardiharborow** [comment]
It looks like babel-plugin-transform-es2015-modules-strip is not ES5 compatible, and you are running an older version that does not have ES6 support. Opened bardiharborow/babel-plugin-transform-es2015-modules-strip#1 to track. In the meantime, upgrading node will fix this for you.

**Comment by bardiharborow** [comment]
Fix coming in babel-plugin-transform-es2015-modules-strip v0.1.1, shipping in a few hours.

**Comment by thejimbirch** [comment]
Upgrading node solved my problem, thanks @bardiharborow
