### ISSUE TITLE
Tooltip wouldn't Appear After AJAX Call

### ISSUE THREAD

**Issue by imbagila** [twbs/bootstrap#21142]
First of all, I'm sorry for my bad English.
For quickly I'm using datatables to show the data, but using AJAX processing. On the table, I also put the button element to put the tooltip attribute. So this element is loaded after AJAX call
```
<button class="btn btn-warning btn-xs" data-toggle="tooltip" data-placement="bottom" title="Edit Data">
Edit
</button>
```
But the tooltip is wouldn't appearing. After that, I try to put the element by not using AJAX call, and it's works fine. So this is kind of a bug or am I just wrong to write the code ?
Note : I've already put the javascript code to activated the tooltip :
```
$("[data-toggle=tooltip]").tooltip({"animation" : false});
```

**Comment by bardiharborow** [comment]
Please read [the contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md) and provide a reduced test case so we can follow up.

**Comment by fleepcom** [comment]
Not a Bootstrap problem but an AJAX loading one.

The solution is to to have the JS function load with the AJAX Results Template which then gets injected back in. So just grab the function and wrap it in a <script></script> and place it at the end of your results template and then it will load. The AJAX search will then work with the Datatables. Have a look at how i implemented by looking at the source at : https://canyonmag.net/database/

**Comment by imbagila** [comment]
@bardiharborow I'm sorry, I should not to post here. And thanks @fleepcom , now is solved.
