### ISSUE TITLE
Bootstrap site doesn't work

### ISSUE THREAD

**Issue by emfluenceindia** [twbs/bootstrap#21144]
http://getbootstrap.com/ is not loading.

![untitled](https://cloud.githubusercontent.com/assets/11072678/20337255/fe58c4d2-abf5-11e6-86e6-647f36588703.png)

**Comment by Starsam80** [comment]
It works for me using Chrome 56. Does the link https://getbootstrap.com work? If so, it might be a http -> https redirect error

**Comment by bardiharborow** [comment]
Please check your internet connection, including any intermediate proxies. If you continue to have problems, please post the output from [cloudflare.com/cdn-cgi/trace](https://www.cloudflare.com/cdn-cgi/trace).

**Comment by emfluenceindia** [comment]
I am having the same issue even on Chrome and IE. Here is the output from https://www.cloudflare.com/cdn-cgi/trace

`fl=59f3
h=www.cloudflare.com
ip=103.24.189.227
ts=1479286550.247
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
colo=MAA
spdy=h2
http=h2
loc=IN`

Thank you!

**Comment by mdo** [comment]
Looks like we're good to go, site seems completely accessible on my end.
