### ISSUE TITLE
Disabling a button while popover is displayed prevents the popover from hiding

### ISSUE THREAD

**Issue by dmbuchta** [twbs/bootstrap#21158]
If you have a button with a popover, and you disable the button while the popover is displayed, the popover will never be dismissed (until you re-enable the button and hover over it again).

```
<button type="button" data-content="Click here to disable" data-toggle="popover" class="btn btn-labeled btn-primary" title="My Example" data-placement="top">
    <i class="fa fa-plus"></i>
</button>

<script>
    $("button").click(function() {
        $(this).addClass("disabled").attr("disabled", "disabled");
    });
</script>
```

**Comment by cvrebert** [comment]
This would require using something like Mutation Observers, and we've historically shied away from that.

**Comment by toby-howell** [comment]
As described in #21232, listening for the `mousemove` event from the document may be a suitable alternative to the `mouseleave` event for disabled buttons.

**Comment by dmbuchta** [comment]
Closing since it sounds like this won't be fixed and a workaround is provided.
