### ISSUE TITLE
Table content alignment inconsistent across site

### ISSUE THREAD

**Issue by VirenMohindra** [twbs/bootstrap#21151]
The content seems to be getting pushed around for no apparent reason.

Technical = 
- Mac OS X 10.11.6
- Occurs Across all browsers
- Hacky fix - `$('html > head').append( $('<style>tbody > tr:nth-child(1) > td:nth-child(2) { width:100%; }</style>') )
`

Live Demo
- https://trumptracker.github.io/
- Scroll to the third section on the first page, this inconsistency is across almost all the pages.

Screenshots
![screen shot 2016-11-16 at 10 15 23 am](https://cloud.githubusercontent.com/assets/10460518/20352549/a3f3be1c-abe5-11e6-8284-648e1ee6432f.jpg)
![screen shot 2016-11-16 at 10 15 32 am](https://cloud.githubusercontent.com/assets/10460518/20352550/a3f43310-abe5-11e6-9585-123e60a5668a.jpg)

**Comment by bkdotcom** [comment]
everything appears full width (as expected) for me.

**Comment by VirenMohindra** [comment]
We have implemented the hack as a temporary fix until we get a more robust solution. That is why I included the screenshots.

What do you think might be the issue?

**Comment by tjdavenport** [comment]
Are you trying to ensure all comment links are aligned vertically?

You have each policy in its own table. If you combined all policies into a single table, then the columns would be of equal width.

**Comment by jesusmtzarvizu** [comment]
I saw your webpage on Chrome and Firefox with Ubuntu and everything is working perfectly, did you fix it? if so, you could close this issue.

**Comment by jesusmtzarvizu** [comment]
it Would be great to see the code that causes that on your web

**Comment by VirenMohindra** [comment]
Open source here - https://github.com/TrumpTracker/trumptracker.github.io

**Comment by jesusmtzarvizu** [comment]
On the readme file there is a To Do list and the first feature says: "Spanish Version" that is a spanish version of the readme, a spanish version of the documentation or spanish version of the content on the web? (I am sorry I comment this here but I don't have you email)

**Comment by VirenMohindra** [comment]
Content displayed on the web through `_data/data.yaml`.
Currently looking for fluent Spanish developers to translate Trump's policies.

**Comment by jesusmtzarvizu** [comment]
I am a fluent Spanish Dev

**Comment by VirenMohindra** [comment]
would love your contribution!

**Comment by jesusmtzarvizu** [comment]
Yes, tomorrow I will translate it !!

**Comment by mdo** [comment]
There's nothing we can do for you on our end with this; it's how multiple tables with variable width content get laid out by browsers. That top table has a single line of content, so it's not spanning the full width whereas the second table includes multi-line content.

Your hacks get you close, but still not exact. Your best bet is to try to make it all one table, but that's not always an ideal solution either.
