### ISSUE TITLE
Broken link (404) under content/typography on v4-alpha docs

### ISSUE THREAD

**Issue by duncanmmacleod** [twbs/bootstrap#21156]
On the [content/typography](http://v4-alpha.getbootstrap.com/content/typography/) page of the v4-alpha docs, the link in the lead '_textual utility classes_' is broken, at least I get a 404 Page not found error when trying to get to http://v4-alpha.getbootstrap.com/utilities/.

**Comment by patrickhlauke** [comment]
Good spot. This has been fixed already via https://github.com/twbs/bootstrap/commit/d6cc0e017dcb205f417b4f74ffd8ec5762b44bf2 - will be reflected in the next alpha
