### ISSUE TITLE
Feature Request - a way to determine navbar height 

### ISSUE THREAD

**Issue by jhechtf** [twbs/bootstrap#21154]
I noticed that there is not a way in the v4 alpha to easily change the height of the navbars like there is in bootstrap 3, there are also some hard-coded styles on the navbar which may be good to have a variable  for customization reasons. 

Example: 
`.navbar-text {
  display: inline-block;
  padding-top:    .425rem;
  padding-bottom: .425rem;
}`

**Comment by mdo** [comment]
Yes, the height will likely stay this way in v4. Fixed dimensions are fragile for customization and variable contents. More variables and improvements to the navbar are still planned for the release.
