### ISSUE TITLE
.badge class name conflicting with original .badge class name

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#21150]
So there seems to be some confusion between `.label`, `.tag`, `.badge`

Back in issue https://github.com/twbs/bootstrap/issues/19094, we determined that there was a conflict between the class name `.label` and the html tag `<label>`. As a result, we changed `.label` to `.tag` in issue https://github.com/twbs/bootstrap/pull/19157. `.tag` was then determined to conflict with Wordpress. See issue https://github.com/twbs/bootstrap/issues/20542. `.tag` was then proposed to be changed to `.badge` https://github.com/twbs/bootstrap/pull/21020.

**New Issue:**
`.badge` is already a class name within **Bootstrap** and will conflict with the current `.badge` class name. See http://getbootstrap.com/components/#badges.

**Proposal:**
Reconsider the merge "**Renamed .tag back to .badge, like v3, to avoid conflicts with common WordPress styles.**" in the [v4 Alpha 6 ship list](https://github.com/twbs/bootstrap/issues/20939) and change the new `.badge`, originally `.label`–`.tag`, to one of the following options:
* `.stamp`
* `.signet`

**Comment by wolfy1339** [comment]
v3 and v4 are incompatible... They can basically take any class they want and completely change them without any consequences as this is a major release.

**Comment by guylepage3** [comment]
So `.badge` is deprecated from v4 then?

**Comment by guylepage3** [comment]
Nevermind. please close this issue.

class names have add on `-pill` that resolves this issue and should be renamed to `.badge`. Sorry about that.
