### ISSUE TITLE
Inconsistent behavior after using collapse('show') on Accordion

### ISSUE THREAD

**Issue by davidtgq** [twbs/bootstrap#21168]
http://codepen.io/anon/pen/zoNyvO?editors=1010#0

To reproduce the problem:

1. Open `Item #2`. It automatically collapses `Item #1`.
2. Open `Item #1` again. `Item #2` does not automatically collapse.

The above steps can be also reproduced substituting `Item 3` in lieu of `Item 2` to demonstrate the same problem where `Item 3` stays open.

The problem does not exhibit when:

 - using `.in` instead of `collapse('show')`

 - `collapse('show')` is removed such that the page loads with all items collapsed

**Comment by bardiharborow** [comment]
Confirmed in Chrome 55 and Firefox 51.0a2.

**Comment by bardiharborow** [comment]
After debugging with DevTools, it appears that `this._parent` equals `null` in [js/src/collapse.js#L123](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L123) if is run before interaction, whereas it refers to the `div#accordion` otherwise.

**Comment by Johann-S** [comment]
I found the same things as @bardiharborow and I'm not sure if we should add a search of a possible ``parent`` if no one provided

**Comment by vanduynslagerp** [comment]
The problem is due to unclear documentation. The `data-parent` has to be set on the collapsible area and not on the trigger. No need to modify the JS code.

Doc fixed here: #21726

**Comment by davidtgq** [comment]
Thanks. Here is the fixed code pen: http://codepen.io/anon/pen/YNGNqv?editors=1010#0
