### ISSUE TITLE
2nd Modal does not scroll on mobile devices

### ISSUE THREAD

**Issue by bttb** [twbs/bootstrap#21163]
The users of my site can add reviews, but only if they are logged in.

When someone clicks the button "Write a Review", a Login-Dialog appears first. The login button is hidden behind the keyboard (on my android), but I can scroll it.

As soon as the login is successful, the modal is hidden and another modal opens. This is not scrollable.

If the user is already logged in, the login modal does not appear. In this case the review-modal is scrollable.

I open the 2nd modal after the first is closed with a $timeout in AngularJS.

**Comment by bttb** [comment]
And I think the problem is: The .modal-open class is there on the <body>-element for the first dialog, but for the 2nd it is removed. Maybe because of fading?

**Comment by bttb** [comment]
If anybody else has this problem: This is my workaround:

                $element.on('shown.bs.modal', function () {
                    // Bootstrap-Fix to support scrolling
                    $('body').addClass('modal-open');
                });

**Comment by cvrebert** [comment]
Please post a CodePen, JS Bin, JS Fiddle, or other live example that demonstrates the problem.
We are unable to provide assistance with third-party libraries such as AngularJS, so please ensure that the example doesn't use Angular.
Also, "mobile devices" is too vague. Please state which OS and browser you're using (including version numbers).

**Comment by bardiharborow** [comment]
@bttb, what happens if you trigger the second modal on `hidden.bs.modal` rather than using a timeout. Bootstrap really doesn't support having two modals operating at the same time, and if your timeout is too short you might be creating the second modal just as the first is stripping `.modal-open` off `<body>`.

**Comment by mdo** [comment]
Closing out given we never heard back. Please update with a new comment here if any of the advice above didn't help and you're still running into the same problem.

<3

**Comment by lulalala** [comment]
https://fiddle.jshell.net/o2tvspvz/1/

Here is the jsfiddle for this situation.
In the first modal everything is fine.
Click the submit button would close the first and bring up the second modal.
In this second modal, scrolling affects the background page, not the modal itself.

There is probably a race condition for between the fade-out of 1st modal and fade-in of 2nd modal.
If I remove the fade class of both modal, it works correctly.
