### ISSUE TITLE
Docs: specify .card-inverse usage

### ISSUE THREAD

**Issue by maxxyme** [twbs/bootstrap#21164]
Please specify in the Card documentation: (starting from) http://v4-alpha.getbootstrap.com/components/card/#image-overlays
that ``.card-inverse`` only works for the following classes (as stated in ``bootstrap-flex.css``):
``.card-header``
``.card-footer``
``.card-title``
``.card-blockquote``
``.card-link``
``.card-text``
``.card-subtitle``
``.blockquote-footer``

**Comment by mdo** [comment]
You say it only applies for that list of classes, but what classes does it *not* apply to that would warrant such an explicit list in the docs?

**Comment by maxxyme** [comment]
It does not apply to regular HTML elements (i.e. without any bs classes).
