### ISSUE TITLE
REGARDING BADGES

### ISSUE THREAD

**Issue by ARKKYN** [twbs/bootstrap#21166]
please implement badges that are compatible for having in top right corner

**Comment by bardiharborow** [comment]
Please read [the contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md) and provide an adequate amount of information for us to follow up. I'm assuming your are referring to [these badges](https://v4-alpha.getbootstrap.com/components/tag/). The top right corner of what?

**Comment by mdo** [comment]
We don't provide any styling for this because it's completely dependent on your implementation. Build this styling yourself as you need.
