### ISSUE TITLE
Opera: pull with nested grid fails with bootstrap-flex (4.0.0-alpha.5)

### ISSUE THREAD

**Issue by jozydapozy** [twbs/bootstrap#21175]
I'm using a flexbox grid and notice some strange behaviours in Opera (content shifting to the left) and not in other browsers.

When I use the exact same code without flexbox, everything works okay. When using flexbox, the results seems wrong in Opera:

This works in Chrome, Firefox & Opera: http://codepen.io/anon/pen/YpZvwe
This works in Chrome, Firefox, but fails in Opera: http://codepen.io/anon/pen/pNeKbo

**Comment by cvrebert** [comment]
What version of Opera?

**Comment by jozydapozy** [comment]
The latest: Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12.388 Version/12.18

**Comment by cvrebert** [comment]
Sorry, but per our browser support policy (https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/ ), we only support the latest version of Opera, [which is currently Opera 41](http://www.opera.com/blogs/desktop/2016/10/86-percent-faster-opera-41-for-computers/).

**Comment by jozydapozy** [comment]
My Opera said there where no updates available. That turned out not to be the case! Works as expected in Opera 41!

**Comment by cvrebert** [comment]
Welcome to the modern web world! 😄

**Comment by jozydapozy** [comment]
haha thanks ;) I use Chrome ;) Was just testing on Opera..

**Comment by patrickhlauke** [comment]
(for reference, the last Opera version with Presto is from approx May 2013, when they switched to using Chromium/Blink)

**Comment by jozydapozy** [comment]
Yes, i feel stupid already!
