### ISSUE TITLE
hide.bs.modal called on smalot/bootstrap-datetimepicker hide

### ISSUE THREAD

**Issue by poolerMF** [twbs/bootstrap#21174]
hello

when datetimepicker hide function is called, modal hide function is triggered too ..

is this problem in bootstrap modal or it's problem of smalot/bootstrap-datetimepicker? https://www.malot.fr/bootstrap-datetimepicker/

example:
https://jsfiddle.net/0egyfdjg/

**Comment by cvrebert** [comment]
Unfortunately we are unable to provide assistance with third-party libraries such as smalot/bootstrap-datetimepicker.
Perhaps try asking on https://github.com/smalot/bootstrap-datetimepicker/issues or on one of the Bootstrap community forums (e.g. StackOverflow; see https://github.com/twbs/bootstrap/blob/v3-dev/README.md#community for links).
