### ISSUE TITLE
Scrollspy + jQuery 3.1.1 refresh bug?

### ISSUE THREAD

**Issue by gpakosz** [twbs/bootstrap#21172]
Hello,

I've noticed the following weird combination when having:
  - a fixed top primary nav bar
  - a static top secondary nav bar
  - a breadcrumbs trail
  - an affixed with scrollspy enabled TOC

When I run Bootstrap `v3.3.7` along with jQuery `v2.2.4`, everything works as expected: scrolling down to "Title 1" highlights the TOC and nav bars remain functional. [See corresponding pen][ok].

When I run Bootstrap `v3.3.7` along with jQuery `v3.1.1`, when scrollspy makes TOC's "Title 1" anchor active, **active classes from the top nav bars disappear**. [See corresponding pen][ko].

So far I found a workaround that could help analyze the problem further: stop doing
```
$(window).on('load', function() {
  $('body').scrollspy('refresh')
});
```
[See corresponding pen][workaround].

I unfortunately don't remember why I needed this in the first place as I obviously don't add or suppress elements from the DOM dynamically. Still it seems weird to me switching from jQuery `v2.2.4` to `v3.1.1` exhibits this behavior. What do you think?

[ok]: http://codepen.io/anon/pen/PbpmBr
[ko]: http://codepen.io/anon/pen/jVBmKW
[workaround]: http://codepen.io/anon/pen/JbWNaL

**Comment by cc13ny** [comment]
Sorry for asking an unimportant problem. What is TOC short for?

**Comment by gpakosz** [comment]
I think I have a lead in understanding what's going on. However since I'm totally unfamiliar with jQuery and I'm not a seasoned Javascript dev at all, please tell me whether you agree or not...

I believe I'm facing https://github.com/jquery/jquery/issues/3194#issuecomment-228556922

When using `v2.2.4`, `ready` fires before `load` and `ScrollSpy.selector` gets assigned `".toc .nav li > a"`.

However, when using jQuery `v3.3.1`, `load` fires first and `ScrollSpy.selector` gets assigned its default `".nav li > la"` value.

All in all, I believe I don't really need
```
$(window).on('load', function() {
  $('body').scrollspy('refresh')
});
```
Can you confirm the last point please?

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
