### ISSUE TITLE
Input boxes are copy-and-pasted, but look different

### ISSUE THREAD

**Issue by ErikB26** [twbs/bootstrap#21186]
I want to make two input boxes, one with a placeholder "Username" and one with "Password". I want both boxes to be exact the same, so I just copy and pasted them, and only changed the class. But, they still look different (see screen). What am I doing wrong? Or do I need to add more things in CSS?

![form](https://cloud.githubusercontent.com/assets/23705771/20573374/b7519a5e-b1af-11e6-9b54-0aa572b97308.png)

![irritated](https://cloud.githubusercontent.com/assets/23705771/20573335/91310576-b1af-11e6-8aa9-fa5cfcf42f5b.png)

**Comment by tomlutzenberger** [comment]
In the second input, you set the wrong class. It must be `form-control` to be rendered correctly.

**Comment by ErikB26** [comment]
Ah of course! Thanks!
