### ISSUE TITLE
Proposing change spelling of 'gray' to international 'grey'

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#21188]
Proposing the change of all instances of the spelling `gray` to the international spelling `grey`.

Main reason for the proposal is that there are more people in the world spelling grey with `ey` than `ay`. Other large tech corporations such as Google are utilizing the international spelling for obvious, greater adoption. 
- See https://material.google.com/style/color.html#color-color-palette

Other companies that are non-universal, such as Apple, use both `gray` and `grey` depending upon the country they are in.

Having said this, it seems as though the United States corporations are quite aware of the `ey` spelling and where the rest of the world is not.

I'd definitely like to see bootstrap take a step in the more universal direction with it's naming and make the switch to `grey` over the `ay` spelling.

**Comment by mdo** [comment]
Thanks, but we'll leave it as-is for now.
