### ISSUE TITLE
tooltip position breaks with horizontal scroll website and absolute positioned elements

### ISSUE THREAD

**Issue by butlerps** [twbs/bootstrap#21184]
I'm having an issue with the positioning of tooltips on a horizontal scrolling website (lets say body width:4500px) where elements have absolute positioning.  It only seems to happen when the tooltip is set to top or bottom. I have created a reduced test case on bootply that demonstrates the problem
[http://www.bootply.com/x1xfg7Z19J#](http://www.bootply.com/x1xfg7Z19J#)
Note: I've been able to get the tooltips (when on the far right side of the display) in the correct location by adding position:relative to the body class.  They still display incorrectly when not on the far right of the screen (a picture paints a thousand words, take a look at the bootply to see what I mean). Note: setting 'container' to 'body' does not fix the problem
Bootstrap v3.3.5, jQuery 2.1.3, seen on firefox/safari(mac)

**Comment by mdo** [comment]
Closing as a won't fix since it's v3.
