### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by pixxet** [twbs/bootstrap#21180]
please give this fork a look,

https://github.com/pixxet/Bootstrap-4-RTL-Support

Its a 100% RTL support without only flipping the directions. all you need is to define `$rtl: true;` to make bootstrap support RTL.

directions are named to $direction_1 and $direction_2 and defined base on the value of $rtl.

default `$rtl: false;`

hope this helps someone, and it would be great if twbs would adapt this solution.

**Comment by mdo** [comment]
Thanks for the heads up. We'll keep an eye on it as we consider RTL options in future versions.

**Comment by BobbyBabes** [comment]
Thanks pixxet.
I do not need to support RTL (at the moment) but now and then I am looking at how to add it anyway.
I was going to go for this Sass solution : http://matanich.com/2013/09/06/rtl-css-with-sass (Github repo is linked at the bottom of the blog post.)
But I will also look at how that repo that you linked implemented it.

**Comment by parsmizban** [comment]
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
