### ISSUE TITLE
Changing $grid-gutter-widths responsively does not affect .container

### ISSUE THREAD

**Issue by iantbarker** [twbs/bootstrap#21181]
I changed the $grid-gutter-widths variable so that sm, md, lg, xl are 60px but xs is 30px. The columns and rows change respectively, but the .container changes to padding-left: 30px and padding-right: 30px on xs-xl.

I would think the expected behavior would be for the .container on xs to change to padding-left/padding-right: 15px;

This is what I changed:

```
$grid-gutter-width-base:     60px;
$grid-gutter-widths: (
  xs: 30px,
  sm: $grid-gutter-width-base,
  md: $grid-gutter-width-base,
  lg: $grid-gutter-width-base,
  xl: $grid-gutter-width-base
);
```

**Comment by mdo** [comment]
This works for me locally with the latest changes from `v4-dev`.
