### ISSUE TITLE
v4 Docs Pages Missing ToC

### ISSUE THREAD

**Issue by davebowker** [twbs/bootstrap#21195]
Confirmed only for the /components folder at this time, but affects:

badges
breadcrumbs
jumbotron
tag

Missing:
```
## Contents

* Will be replaced with the ToC, excluding the "Contents" header
{:toc}

**Comment by mdo** [comment]
On some of these pages, the content is super short, so I've avoided adding a table of contents. I'll audit these pages and a few more today and see if there's any worth revisiting though. Thanks!
