### ISSUE TITLE
stacked progress bar flickering

### ISSUE THREAD

**Issue by sb10** [twbs/bootstrap#21198]
I have a flickering progress bar problem.

Demo: https://jsfiddle.net/qthgs5od/ or https://jsbin.com/yecezijasi/1/edit?html,output

Watch it for long enough (expand out the output window to make it big, and wait until complete is in the 3 digit range at least), and you should note that the green bar on the right flickers. This is seemingly because it's animation causes it to get too big when the middle dark blue bar appears and disappears.

I have tried everything I can think of to ensure that at no point in time do the total of the stacked bars exceed 100. If I stop using the progress-bar class and use my own that results in a similar look, but with no animation, then then there is zero flickering and the bars are stable, always totalling 100.

OS: Mac OS X 10.12.1
Browser: Chrome 55 or Safari 10.0.1
Bootstrap: 3.3.7

**Comment by mdo** [comment]
Closing as we're not actively working on v3.
