### ISSUE TITLE
v4.0.0-alpha.5: input placeholder color is not changeable.

### ISSUE THREAD

**Issue by weilinzung** [twbs/bootstrap#21197]
TRY with this, but the placeholder text color is not changing, stay with the gray. Bootstrap 3 doesn't have this issue. thanks!!

> 
> input::-webkit-input-placeholder {
>    color: red !important;
> }
> input::-moz-placeholder {
>  color: red !important;
> }
> input:-moz-placeholder {   /* Older versions of Firefox */
>  color: red !important;
> }
> input:-ms-input-placeholder {
>    color: red !important;
> }

**Comment by mdo** [comment]
I'm able to override it fine with latest from `v4-dev` branch: https://jsbin.com/layavul/edit?html,css,output.

**Comment by weilinzung** [comment]
ok. thanks! 
Not sure why there is also an opacity on it too, so I just add the `opacity: 1 !important`, it works now.

**Comment by mahdibavi** [comment]
Thank you, that was so helpful

**Comment by kashmiry** [comment]
If your using SASS you can override it by setting a value to $input-placeholder-color

**Comment by jrfornes** [comment]
If you are not fan of forcing things with `!important` just do

```
.form-control::-webkit-input-placeholder { /* Chrome/Opera/Safari */
  color: #C0C0C0;
}
```

This worked for me.
