### ISSUE TITLE
.btn-outline- caption text colors

### ISSUE THREAD

**Issue by viktor-yakubiv** [twbs/bootstrap#21210]
For `.btn-primary` (and others) was made an option to set color of caption text on `_variables.scss`

But for all `.btn-outline-*` caption text in active state is white, even if black is better to look. It would be good feature add similar option for `.btn-outline-` or use colors from `$btn-*-color` in `button-outline-variant` mixin, or use sass functions for checking color [lightness](http://sass-lang.com/documentation/Sass/Script/Functions.html#lightness-instance_method).

**Comment by mdo** [comment]
Outline buttons are specifically designed to share the same color for `color` and `border-color`. No planned changes here for making that any different.

**Comment by viktor-yakubiv** [comment]
Yeah, in normal state. But in *hover* and *active* states buttons change its background, and on different backgrounds we have only white text. That's I mean.
