### ISSUE TITLE
v4 Alpha 5, no breakpoint near docs specified `~ 480px`, `sm` too large for iPhone 5 landscape

### ISSUE THREAD

**Issue by AdmiralPotato** [twbs/bootstrap#21219]
Part of this issue is a possibly a documentation discrepancy; reading through the V4 migration guide, there are three references to a measurement of `~ 480px`, but in v4 Alpha 5, we jump from `xs: 0` all the way to the current value of ` sm: 576px`. This value is quite far from being able to target a number of phones in landscape mode, notably the iPhone 5, with a landscape viewport size of `568px` - [reference](http://viewportsizes.com/?filter=iphone%205) - which can no longer be reached with the default preset.

These are the places in the migration guide where I'm seeing the reference to `~ 480px`:
* [Global Changes](https://v4-alpha.getbootstrap.com/migration/#global-changes)
* [Grid System](https://v4-alpha.getbootstrap.com/migration/#grid-system)
* [Grid System](https://v4-alpha.getbootstrap.com/migration/#grid-system-1) - this section title is listed a second time in the same page, but with different content. Is this intentional, or just overlooked after a reorganization?

Is there a reason that the `sm` breakpoint was moved up so high? Is there a motion to abandon the landscape breakpoint for smaller/older smartphones, or was this scooted up a a bit too far on accident?

**Comment by holger1411** [comment]
Could it be a bug?
` sm: 567px,`
would make sense,
not 
` sm: 576px,`

**Comment by AdmiralPotato** [comment]
The problem is that `sm: 567px` doesn't make compatibility sense either though. There are so many devices  (at a glance, looking like up to 20% - [reference](https://deviceatlas.com/blog/viewport-size-statistics-2016)) with a landscape width between `480px` and `560px`, with a very popular size being `533px`. It doesn't make any sense to me to exclude all of them just because a single popular device has a width of exactly `568px`. I suppose that this is a question for @mdo for some history on this issue.

Somewhere between here: https://github.com/twbs/bootstrap/commit/0d27e12d1f2773fb672513fbd025ac3f07e47660
and here: https://github.com/twbs/bootstrap/commit/a90f6c709306d2bc1411639b1061aed01950239a?diff=split#diff-d8ee409a461718bfb6240710c8c73382R84
something was lost in translation between `rem`s and pixel viewport widths.

At one point, there was a motion to use `rem`s to measure the viewport in media queries. This was a nice idea, but it turned out that media query `rem` values didn't scale with the `font-size` applied to the `html` tag. It seems that the value `@media (max-width: 34rem) { ... }` was chosen because `34rem` * `html{ font-size: 14px; }` = `476px` as a viewport width - `14px` being Bootstrap 3's default font size.

The approach of using `rem`s has since been abandoned, but it seems that a later a decision for the pixel resolution of the `sm` breakpoint should be defined by was Bootstrap 4's `16px` default font size. I even see where the `34rem` * `html{ font-size: 16px; }` = `544px` as a viewport width comes from, but the problem is that the browser was never able to make that multiplication. Many viewports are still between `476px` and `533px`.

Again, I would like to ask - Is there a reason that the `sm` breakpoint was moved up so high? Is there a motion to abandon the landscape breakpoint for smaller/older smartphones? Or was this simply lost in translation between `px` -> `rem` -> `px`? I would like to propose that the `sm` breakpoint be moved back to `476px` to cover all of the use cases that it previously met - the landscape viewport that it used to target.

**Comment by mdo** [comment]
The current values are intentional, not specific to a particular device, not lost in any translation, and not likely to change again. The small breakpoint was never about specifically targeting the landscape orientation of any particular device. It's simply meant to be a reasonable width at which you might want to re-arrange content with another grid tier.

Regarding your mention of `476px` as the old breakpoint, we never had that value for the `sm` breakpoint. We've been rocking a base font-size of 16px in v4 for the last two years of development.

Coupled with the first default tier, `xs` at `0px` and above, you should have plenty of control for targeting smaller devices like phones, be it in portrait or landscape.
