### ISSUE TITLE
Why does rendering a button with React.js cause the margins to break?

### ISSUE THREAD

**Issue by ryancole** [twbs/bootstrap#21225]
I've got a React.js application in which I also use bootstrap (alpha 5). I've noticed an issue with spacing between `<button class="btn">` elements for the past few versions. I just figured it was something with my own CSS interfering. I finally got to looking into it and narrowed it down to the following jsfiddle example. The issue has been reproduced with minimal code ...

https://jsfiddle.net/hmq560Lu/

Also, here's an example of it on my application ...

http://jsbin.com/fiziyiquha/1/edit?html,output

For some reason, rendering two simple buttons via react causes them to have no visual space between them.

When rendering them normally, via HTML, they look as expected.

Any ideas?

**Comment by bardiharborow** [comment]
If you go into DevTools and hit `Edit as HTML`, you'll notice that the HTML is very slightly different between the two.

With React:

```
<div id="app"><div data-reactroot=""><button class="btn">Foo</button><button class="btn">Bar</button></div></div>
```

Without React:

```
<div>
  <button class="btn">Foo</button>
  <button class="btn">Bar</button>
</div>
```

The React example generates markup that is all on one line and has no whitespace between the `<button>`s. [Whitespace between inline block elements is actually rendered](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) in HTML.

**Comment by ryancole** [comment]
Ah, I see. Thanks! Will close.
