### ISSUE TITLE
Consider using Babili instead of UglifyJS.

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#21229]
Tracking issue to investigate a possible switch. [Babili](https://github.com/babel/babili) is a minifier based on the Babel toolchain. We already use Babel to transpile from ES6 to ES5, so switching would reduce dependency weight. Babili, being based on the Babel pipeline, has a significantly nicer architecture than Uglify, though it is still in beta and does present some risk. We may wish to sit this one out for a while. At the very least, by looking at this, I'll have some feedback to go back to the Babili team with.

Todo:

- [x] Ensure all tests pass on `bootstrap.min.js` after being minified with Babel.
- [ ] Compare byte for byte with uglified version to ensure nothing funky is going on.
- [x] Evaluate raw and gziped sizes for `bootstrap.min.js` compared with UglifyJS.
- [ ] If Babili does not minify as well as Uglify does, identify areas where Babel needs to improve in.

Benchmark:
```
minifier            | output raw | raw win | gzip output | gzip win | parse time (ms) | minify time (ms)
babel-minify        | 57.4KB     | 53%     | 14.62KB     | 36%      | 2.48            | 1802.26         
terser              | 55.45KB    | 55%     | 14.11KB     | 38%      | 2.20            | 734.08          
uglify              | 54.06KB    | 56%     | 14.08KB     | 38%      | 2.29            | 658.73          
closure-compiler    | 53.83KB    | 56%     | 13.09KB     | 42%      | 2.90            | 1846.95         
closure-compiler-js | 56.58KB    | 54%     | 13.87KB     | 39%      | 2.15            | 4653.47         
```
Last Updated: 24 January 2019

Command: `node scripts/benchmark.js ../bootstrap/dist/js/bootstrap.js`

**Comment by hzoo** [comment]
>  If Babili does not minify as well as Uglify does, identify areas where Babel needs to improve in.

👍  would be super appreciated!

**Comment by XhmikosR** [comment]
The thing with this is that the docs are not ES6+, at least not yet. So we'd still need uglify for the docs.

From the tests above closure-compiler seems the best though. We'll need to revisit at some point later.

**Comment by mdo** [comment]
@XhmikosR Should we close this out if we're moving off Uglify?

**Comment by XhmikosR** [comment]
@mdo I'd like to keep this open as an alternative until we make the switch.

**Comment by bardiharborow** [comment]
The Babili project has stagnated recently and will not be a viable alternative in the short term.
