### ISSUE TITLE
Disabled button's tooltip displays on Firefox

### ISSUE THREAD

**Issue by toby-howell** [twbs/bootstrap#21233]
Disabled buttons don't normally fire the `mouseenter` event, but they do in Firefox. As a result, the tooltips of disabled buttons (`<button disabled>`) are displayed when the mouse enters the button.

If this is the desired behaviour, this is broken for other browsers. If not, a fix for Firefox could be to check whether the button is disabled before showing the tooltip. This may also affect other elements such as `<input>`.

- **Operating system:** Windows 10 Pro x64
- **Browser:** Firefox 50.0
- **Test case and workaround:** [https://jsbin.com/qigazerate](https://jsbin.com/qigazerate/edit?js,output)

The fix in Bootstrap's JavaScript would skip the processing of the `mouseenter` event, rather than `show.bs.tooltip`, as was used in the above workaround.

This issue was encountered with Bootstrap v4.0.0-alpha.5.

**Comment by cvrebert** [comment]
https://www.fxsitecompat.com/en-CA/docs/2016/disabled-form-controls-now-trigger-mouseover-and-similar-mouse-events/

**Comment by PurvaA** [comment]
@toby-howell 

This issue can be fixed using custom code using jQuery

Please check my solution here - https://jsbin.com/guzikakuba/edit?html,css,js,output
I have tested in Mozilla, Chrome & Opera, IE11. In all these browsers it showing the desired behaviour.

I am attaching screen shot.

![notooltip_mozilla](https://cloud.githubusercontent.com/assets/15212429/20749686/59675c84-b719-11e6-8b2a-ed74505bed08.jpg)

Please let me know in case of any further concerns.

**Comment by alecpl** [comment]
This is still an issue. It could be fixed by adding `pointer-events: none` to disabled button style. However, this also "disables" `cursor` style so might not be a solution for everyone.

**Comment by mdo** [comment]
This will be addressed in v5. Up to @MartijnCuppens and rest of @twbs/css-review if we backport something to v4. See #29296 for more details.
