### ISSUE TITLE
No Gutter from Container up to col

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#21239]
Please consider adding:

.no-gutter.row,
.no-gutter.container,
.no-gutter.container-fluid{
  margin-left: 0;
  margin-right: 0;
  padding-left: 0;
  padding-right: 0;
}

.no-gutter>[class^="col-"]{
  padding-left: 0;
  padding-right: 0;
}

**Comment by mdo** [comment]
Dupe of #19107 and added in #21211.
