### ISSUE TITLE
Why figure-caption?

### ISSUE THREAD

**Issue by garretwilson** [twbs/bootstrap#21248]
I'm desperately looking for a base stylesheet to use for reports. I just want things to look good with HTML5. This seems an impossible task: no one likes HTML5. No, seriously. Take Bootstrap 4.0.0-alpha.5. I want a figure caption. Here's how HTML5 wants me to do it:

```html
<figure><img ... />
  <figcaption>This is my caption</figcaption>
</figure>
```

But Bootstrap wants me to do this:

```html
<figure><img ... />
  <figcaption class="figure-caption">This is my caption</figcaption>
</figure>
```

For the life of me I can't understand why. Look at the HTML5 `<figcaption>` tag. _It means "figure caption"._ Why oh why do I have to put a `"figure-caption"` class on it? Why do I have to repeat myself?

HTML5 has a load of semantic tags. Bootstrap doesn't like semantic tags. Bootstrap would be happy if I just used `<div>` throughout my code and put a special Bootstrap class (each of which looks suspiciously like the HTML5 tag name I could have used).

What is so sinful about tag names?  Why does Bootstrap make me repeat the tag name in a class?

If someone could suggest a CSS framework that _follows HTML5 tag name semantics_ and doesn't make me repeat myself on every tag, I would greatly appreciate it. Or maybe there is an option in Bootstrap that says, "when I tell you the tag, take my word for it and use that for styling"...

**Comment by mdo** [comment]
We take a class based approach to many of our global styles whenever possible. This helps ensure we don't blow up projects as soon as folks import Bootstrap. We only restyle a handful of global elements and settings: http://v4-alpha.getbootstrap.com/content/reboot/.
