### ISSUE TITLE
cross browser compatibility

### ISSUE THREAD

**Issue by MuhammadGoharKhan** [twbs/bootstrap#21247]
<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default">Left</button>
  <button type="button" class="btn btn-default">Middle</button>
  <button type="button" class="btn btn-default">Right</button>
</div>

In google chrome button have blue outline and box shadow but in Internet explorer no out line and button animate while clicking on it can we fix this issue in bootstrap we need same behavior of button in all browser [visit here](http://getbootstrap.com/components/#btn-groups)

**Comment by bardiharborow** [comment]
Please read [the contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md) and provide an adequate amount of information for us to follow up, including the version of Internet Explorer and the operating system you are experiencing this on. However, note that [support for v3 has mostly ceased](https://github.com/twbs/bootstrap/issues/20631). Please identify whether this issue effects v4.

**Comment by mdo** [comment]
Your version of IE likely doesn't support those styles that Chrome does. Plus, @bardiharborow's comment—v3 isn't being actively developed right now.
