### ISSUE TITLE
Consider adding responsive height

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#21240]
Sometimes we need to add images as background like so:

`<div style="background-image:..."></div>`

That way the element is empty and it will not display on the browser.
My idea is to add responsive height heplers, similar to the mt-1 and pt-1.

Something like this:

`h-xs-100 h-sm-200 h-md-300`

Height: 100px - in mobile
Height: 200px - in tablet
Height: 300px - in desktop

This will allow us to play with card that have background image instead of the image tag.

**Comment by mdo** [comment]
Going to pass on this; not seeing the value in us creating those classes for you when in all likelihood those styles will be one-off or project dependent.
