### ISSUE TITLE
Bootstrap doc. docsNavbarContent bug.

### ISSUE THREAD

**Issue by axfsociety** [twbs/bootstrap#21252]
click "Content" like this https://postimg.org/image/l46jg8tv7/ two menu opened. why ?

**Comment by bardiharborow** [comment]
Ouch. Sounds like we're [Doing It Wrong](https://xkcd.com/1700/)™ somewhere. I'll look into a fix.

**Comment by axfsociety** [comment]
and here -> http://v4-alpha.getbootstrap.com/layout/responsive-utilities/ for screenshot this -> https://postimg.org/image/sc283hzkv/

**Comment by bardiharborow** [comment]
The issue is [docs/_includes/nav-docs.html#L31](https://github.com/twbs/bootstrap/blob/v4-dev/docs/_includes/nav-docs.html#L31). `{% if page.url contains slug %}` matches slugs that are substrings of other slugs.
