### ISSUE TITLE
Tether should be linked/listed as a requirement from the doc home page

### ISSUE THREAD

**Issue by Eonasdan** [twbs/bootstrap#21250]
Tether is not listed as a requirement on the home page of the BS4 docs. Simply including the two references listed will result in a error about missing Tether

![image](https://cloud.githubusercontent.com/assets/1006516/20736609/97ad7400-b675-11e6-8296-b4a5b88d7221.png)

**Comment by Johann-S** [comment]
The documentation home page talk about Bootstrap CDN, if you want to see Bootstrap requirement go to this link : http://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start and you'll see Tether as required
