### ISSUE TITLE
Mixin button-outline-variant takes 1 argument but 2 were passed

### ISSUE THREAD

**Issue by afuno** [twbs/bootstrap#21257]
This part: https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss#L61-L106

When I'm trying to create a button with a different hover-color:

```
.btn-outline-blue {
	@include button-outline-variant(#dbe4ed, #000000);
}
```

I get:

> Mixin button-outline-variant takes 1 argument but 2 were passed.

**Comment by aRestless** [comment]
Do you have the alpha5 tag checked out? The introduction of the second argument happened not so long ago and can only be found in the dev branch (that you also linked).

Just check if your local version of mixins/_buttons.scss has that second parameter defined.

**Comment by mdo** [comment]
Make sure you're using the latest from` v4-dev`, which does change from time to time. Shouldn't be an issue anymore.
