### ISSUE TITLE
Icon input status not show in firefox

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#21258]
http://joxi.ru/12MQPzlfyogM2J

**Comment by bkdotcom** [comment]
markup?

can you recreate on one of these sites?
https://plnkr.co/
https://jsfiddle.net/
https://codepen.io/
https://jsbin.com/?

**Comment by rorc** [comment]
Here my markup:
```html
<div class="has-success">
    <input placeholder="Дата принятия" class="form-control form-control-success" type="text">
</div>
```
I have latest firefox. In chrome with same markup all is ok http://joxi.ru/MAjMLEZcN3kO2e

**Comment by rorc** [comment]
Here my markup:
```html
<div class="has-success">
    <input placeholder="Дата принятия" class="form-control form-control-success" type="text">
</div>
<div class="has-danger">
    <input placeholder="Дата принятия" class="form-control form-control-danger" type="text">
</div>
```
I have latest firefox. In chrome with same markup all is ok http://joxi.ru/MAjMLEZcN3kO2e

**Comment by patrickhlauke** [comment]
as @bkdotcom already said, this bug was addressed and the fix will make it into the next alpha release.

**Comment by rorc** [comment]
Ok thanks :)
