### ISSUE TITLE
Outine buttons using an anchor tag have their text color overridden

### ISSUE THREAD

**Issue by KyleMay** [twbs/bootstrap#21251]
I tried to override the text color from white on an outline button by overriding the SASS variable, however it's being overwritten by another rule.

Using this HTML and overriding like so:
```
<a class="btn btn-outline-primary">Button</a>
$btn-primary-color: #000;
```
It's being overridden by `color: inherit` on `a:not([href]):not([tabindex])`

Seems to have been caused by 64251a1 as this is not present in alpha 4 (I believe).

**Comment by KyleMay** [comment]
Never mind, works when adding a `href`

**Comment by 0xb4dc0d3** [comment]
same problem, thanks !

**Comment by rsshilli** [comment]
I don't want an href on my link (it's controlled by React).  How do I fix / override this?

**Comment by team-massive** [comment]
Same problem as @rsshilli

**Comment by tonytontian** [comment]
> I don't want an href on my link (it's controlled by React). How do I fix / override this?

You can use flowing code in your css
```
a:not([href]):not([tabindex]){
    color:red;
}
```
