### ISSUE TITLE
Remove flash from the bootstrap website

### ISSUE THREAD

**Issue by BartWillems** [twbs/bootstrap#21255]
Currently the website uses flash to copy code blocks to the clipboard. 
It is 2016 however and flash has no place in this time or space.

It is possible to copy text to clipboard using [javascript](https://clipboardjs.com/) so why doesn't bootstrap use this?

**Comment by hultberg** [comment]
On v4 docs, clipboardjs is used for click-to-copy. On v3, flash is used (current getbootstrap.com). As v3 has mostly ceased (#20631), I doubt this will be changed.

**Comment by cvrebert** [comment]
What @hultberg said.
