### ISSUE TITLE
Docs utilities 404

### ISSUE THREAD

**Issue by JacobLett** [twbs/bootstrap#21265]
http://v4-alpha.getbootstrap.com/utilities/

I see other categories are redirecting but this one is causing a 404.

**Comment by giulianovelli** [comment]
The category titles link directly send to the first section of each category, the correct “Utilities” link is:

http://v4-alpha.getbootstrap.com/utilities/borders/

**Comment by JacobLett** [comment]
I see now thank you. In my opinion it would be clearer to toggle and show the secondary items and not auto click to the first sub category. Or having a summary page with an index to each individual sub category.

**Comment by bardiharborow** [comment]
@JacobLett, you are correct though that the category page should redirect.
