### ISSUE TITLE
Checkmark in checked custom checkbox and radio doesn't display in Firefox

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#21279]
http://joxi.ru/p27LNavcJ4gdA7
Without checkmark and bullet inside.

**Comment by cvrebert** [comment]
@rorc What OS are you using? What version of Firefox?

**Comment by rorc** [comment]
@cvrebert Windows 10, latest firefox 50.0.2

**Comment by tomlutzenberger** [comment]
Can confirm on Win10 with FF50 and FF51

**Comment by rorc** [comment]
This bug by svg like this https://github.com/twbs/bootstrap/issues/21258

**Comment by patrickhlauke** [comment]
that should also be fixed by https://github.com/twbs/bootstrap/pull/20962 - have you actually tried the latest version from the repo?

**Comment by Mevrael** [comment]
Have same issue with alpha5. Latest dev works.

**Comment by patrickhlauke** [comment]
>  Latest dev works.

i.e. "latest version from the repo" which includes the fix from #20962
