### ISSUE TITLE
[FEATURE] Responsive margin and padding spacing

### ISSUE THREAD

**Issue by iamandrewluca** [twbs/bootstrap#21275]
Hello folks!
As I see, now Bootstrap v4 offers a new way for spacing
http://v4-alpha.getbootstrap.com/utilities/spacing/

I think would be nice to have also this classes for `margin` and `padding` also related to screen size

The classes are named using the format: `{property}{sides}-{size}-{screen}`
For *property*, *sides*, *size*, check the link above.
Where *screen* is one of:
* `xs` - for Extra small devices and up
* `sm` - for Small devices and up
* `md` - for Medium devices and up
* `lg` - for Large devices and up
* `xl` - for Extra large devices and up

ex:
```
<div class="mt-2-xs"></div>
<div class="mt-1-xs mt-0-md"></div>
<div class="pa-3-lg"></div>
<div class="pb-2-lg"></div>
<div class="ma-3-xs ma-2-sm ma-1-md ma-0-lg"></div>
```

Thanks!

**Comment by Starsam80** [comment]
This is already in `v4-dev` but with a slightly different format: `{property}{sides}-{breakpoint}-{size}`. For example:
- `.pl-3`: `padding-left: 1rem` on all screen sizes
- `.pl-sm-3`: `padding-left: 1rem` only on `sm` screens and bigger

For more information, you can checkout the `v4-dev` branch and build the docs yourself, or wait until the next release. See also #20926

**Comment by iamandrewluca** [comment]
@Starsam80 oh yeah :smiley: Thanks!
