### ISSUE TITLE
Colors style for dropdown

### ISSUE THREAD

**Issue by sulian** [twbs/bootstrap#21277]
Hello

It is possible that options in button dropdown and split button dropdown have colos like this example provided by GLPI : 

![bootstrap-4-improvements](https://cloud.githubusercontent.com/assets/2016950/20831745/d14fa4ea-b886-11e6-85e9-da103389e617.jpg)
 
Colors are the same like buttons : primary, success, ...

**Comment by mdo** [comment]
There's a previous issue asking for this somewhere, but we're not going to be adding anything else here for our dropdowns. You'll need to take that on your own.
