### ISSUE TITLE
Fix style select

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#21276]
For best view `select` field need disable vertical padding from class `.form-control`
http://joxi.ru/12MQPzlfyE6j2J to http://joxi.ru/DmBEb8qHKD1xrP

**Comment by tomlutzenberger** [comment]
Please post a reduced testcase. Images are not helpful.

**Comment by rorc** [comment]
Ok :)
https://jsfiddle.net/x88sx118/

**Comment by tomlutzenberger** [comment]
You're right, it looks like this is an issue.

I took a look into the docs and added high letters:
http://v4-alpha.getbootstrap.com/components/forms/#control-sizing

![form-select](https://cloud.githubusercontent.com/assets/5536910/20832913/39254a9c-b88d-11e6-915b-89fd3400569e.png)

**They get cut.** (Tested in Chrome, FF, Edge, IE)
Removing the top-/bottom-padding also affects the other form-controls. This needs to be discussed.

//cc @mdo

**Comment by rorc** [comment]
Thanks :)
But if use `select.form-control { padding-top: 0, padding-bottom: 0 }` ?

**Comment by tomlutzenberger** [comment]
Using `select.form-control` would mean to overqualify an element.  It's an undesirable practice and linters don't like it.
A suitable solution for all form-controls needs to be found.

Of course you can overwrite it like this in your project 😉

**Comment by mdo** [comment]
Can you retest with the latest code from `v4-dev`? We just made a change to the selects that's not published to our docs yet (fixed #20977 with #21171).

**Comment by tomlutzenberger** [comment]
Done, LGTM (http://codepen.io/tomlutzenberger/pen/ZBrEaZ?editors=1100#0)

But... It's not pixel-perfect.
The `.form-control-lg` has a height of `50.6563px`, while the `.btn-lg` has `51px`.
Not sure how it works out if one adjust the root font-size.

**Comment by sbaechler** [comment]
I noticed that the padding is also depending on the font that is used. Some have odd spacings. 
The 'Neue Haas' example looks good if the top and bottom padding are 0.

This is how it looks with the Helvetica font (with #21171 applied):

![helvetica](https://cloud.githubusercontent.com/assets/288516/21100076/5407fd90-c072-11e6-957f-25032cc42c37.png)

This is Neue Haas:

![haas](https://cloud.githubusercontent.com/assets/288516/21100080/5c67437e-c072-11e6-9af7-bf748b521ea1.png)

The only thing that changed was `font-family`.

**Comment by mdo** [comment]
> I noticed that the padding is also depending on the font that is used.

Yeah, there's not much we can do about that though sadly. We'll do our best, but it's tough :). I made some other changes to the select sizing recently as well, so I think we're good here now.
