### ISSUE TITLE
nav-justified doesn't work at any IE versions and description of feature is wrong

### ISSUE THREAD

**Issue by alexey-kuznetsov** [twbs/bootstrap#21274]
Hi! I have recently noticed, that ".nav-justified" class doesn't work in any IE versions. In IE all menu items are rendered with the same width instead of the same indents. And also I've noticed, that in description of this class is written the following:

> Easily make tabs or pills equal widths of their parent at screens wider than 768px with .nav-justified. On smaller screens, the nav links are stacked.

But it's definitely wrong, because normal behaviour of nav-justified is rendering menu items with equal indents, but not equal widths

**Comment by mdo** [comment]
I'm unsure if this was targeted for v3 or v4, but it sounds v3. Justified nav options are coming back in v4 with flexbox being our layout method of choice though, too.
