### ISSUE TITLE
tooltip.js treats `data-title="0"` as no content

### ISSUE THREAD

**Issue by bayashi** [twbs/bootstrap#21273]
tooltip.js treats `data-title="0"` as no content. So tooltip does not work. But I expect to show "0" tooltip.

    <span data-toggle="tooltip" title="" data-title="0">0</span>
	<script>
	$(document).ready(function() {
	    $('[data-toggle=tooltip]').tooltip({trigger: 'hover'});
	});
	</script>

I think it had been caused by below line
https://github.com/twbs/bootstrap/blob/535fec93cf8892d1a83f6bb8cb97adc589af2b39/js/src/tooltip.js#L369

    isWithContent() {
      return Boolean(this.getTitle())
    }

Thank you.

**Comment by Johann-S** [comment]
You have to use the ``title`` attribute not ``data-title`` see the documentation : http://v4-alpha.getbootstrap.com/components/tooltips/#options

Plus my CodePen : http://codepen.io/Johann-S/pen/qqpJxv

**Comment by bayashi** [comment]
I know I should use `title` attribute.
However, I feel weird about string `0` does not work in `data-title` attribute for tooltip.
Is it correct that `titile` attribute and `data-title` attribute are not same behavior?

**Comment by Johann-S** [comment]
It seems ``data-title`` doesn't work because it's ``data-original-title`` which is used in tooltip.js

https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L413

So, we have to update the documentation or change this in tooltip.js

**Comment by bayashi** [comment]
I understand.
Basically, `data-title` should not be used for tooltip.
I have to use `title` or `data-original-title`. I'll do so.

Thank you so much.
