### ISSUE TITLE
How to split a row into multiple rows when using Flexbox grid?

### ISSUE THREAD

**Issue by cyrildc** [twbs/bootstrap#21287]
When enabling flex to create an auto-layout column, the colum reset with the use of .clearfix doen't work.
```
<div class="row">
<div class="col">1 </div>
<div class="col">2</div>
<div class="clearfix"></div>
<div class="col">3</div>
<div class="col">4</div>    
</div>
```

We get:
![Image of Flex clearfix](http://i.imgur.com/qFXaKmU.png)
instead of the expected result:
![Image of Flex clearfix](http://i.imgur.com/1vxnqz0.png)

**Comment by cvrebert** [comment]
The concept of clearfixing only makes sense with a float-based grid, not the flexbox-based grid.
So I'll interpret this as a request for a way to split a row into multiple rows when using Flexbox.

**Comment by mdo** [comment]
Insert a `.w-100` where you used to do the clearfix.

```html
<div class="row">
  <div class="col">Column</div>
  <div class="col">Column</div>
  <div class="w-100"></div>
  <div class="col">Column</div>
  <div class="col">Column</div>
</div>
```
