### ISSUE TITLE
Travis failing on bad version of Java

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21281]
Example build failure: https://travis-ci.org/twbs/bootstrap/jobs/180783524.

```
Running "htmllint:src" (htmllint) task
Fatal error: Command failed: java -version
/bin/sh: 1: java: not found
```

Can hopefully look myself this weekend, but if anyone else has a quick fix, PRs are welcome!

**Comment by bardiharborow** [comment]
X-Ref: travis-ci/travis-ci#6928. Seems to be fixed by #21108, but I'm not sure how exactly.

**Comment by bardiharborow** [comment]
I'm guessing this will be fixed within the next 24 hours, based on progress over on Travis' end.

**Comment by mdo** [comment]
Thanks @bardiharborow! Merged your PR today for that fix.
