### ISSUE TITLE
Incorrect .dropdown-menu li:hover background color when .bg-inverse is used

### ISSUE THREAD

**Issue by shine-on** [twbs/bootstrap#21290]
Bootstrap 4 alpha 5.

Extra css should be applied to .dropdown-menu li:hover elements to have correct background color when .bg-inverse is used

http://www.bootply.com/9tRoFXx8Jz

```
.bg-inverse .dropdown-menu li:hover {background-color:#373a3c!important;}

<nav class="navbar navbar-full navbar-dark bg-inverse">
<ul class="nav navbar-nav">
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">dropdown</a>
<ul class="dropdown-menu bg-inverse">
<li class="dropdown-item"><a class="nav-link" href="#">.nav-link</a></li>
</ul>
</li>
</ul>
</nav>
```

**Comment by mdo** [comment]
That's not how we expect our `.bg-*` utilities, or any other utilities, to work. Utilities are specific to a set of elements they affect and usually are not inherited, nor freely modify the children elements. You'll need to further modify this yourself.
