### ISSUE TITLE
Documentation Example - Nested form-inlines

### ISSUE THREAD

**Issue by imcodingideas** [twbs/bootstrap#21291]
Hello,

As a jr developer I relay heavily on your documentation for code examples. I would like to ask if you could create some examples on how to create forms like this where you have grouped form-groups inline.

![omvid](https://cloud.githubusercontent.com/assets/5374985/20866342/b555705e-b9e8-11e6-9e08-4ab4e16cc2da.png)

Thanks for your consideration.

**Comment by mdo** [comment]
Cannot help you without a JS Bin to reproduce the problem.

**Comment by imcodingideas** [comment]
Sure. So this is how I would create a form with several 'inline-form' http://codepen.io/imcodingideas/full/jVZjRe/ but I don't ever really know if I'm doing it the 'bootstrap way' as bootstraps documentation really teaches us how to use it the way its intended and I think some 'checkout' form or 'registration' form example would benefit a lot of people.

**Comment by cvrebert** [comment]
@imcodingideas Your example doesn't use `.form-inline` anywhere...

But generally speaking, to accomplish complex form layouts, using the grid system is The Right Way to do it.

**Comment by imcodingideas** [comment]
I know it doesn't use .form-inline because it doesn't get padding/margin right. I'm not this great front end developer so like I said in my proposal that maybe an example registration form or checkout form would be beneficial for some developers.

**Comment by IamManchanda** [comment]
@imcodingideas - You are looking for an example ( codepen ), so here you go 
--> http://codepen.io/IamManchanda/pen/KNBgmo

But even i will also say that grid system is the right way to achieve form layouts.

**Comment by mdo** [comment]
I agree with others here that your best best is using the grid system. There's not much we'll do here to document this differently than our existing grid and form docs.
