### ISSUE TITLE
<A> Buttons are not styled correctly in a dropdown-menu

### ISSUE THREAD

**Issue by bowyer99** [twbs/bootstrap#21301]
The issue is that `<a>` tags marked with the class btn (and btn-danger etc) are not styled correctly when in a dropdown-menu. 

<Buttons> and <input> are styled consistently but the <a> is overridden by the following css in the bootstrap.css:

```
.dropdown-menu > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.42857143;
  color: #333;
  white-space: nowrap;
}
.dropdown-menu > li > a:hover,
.dropdown-menu > li > a:focus {
  color: #262626;
  text-decoration: none;
  background-color: #f5f5f5;
}
.dropdown-menu > .active > a,
.dropdown-menu > .active > a:hover,
.dropdown-menu > .active > a:focus {
  color: #fff;
  text-decoration: none;
  background-color: #337ab7;
  outline: 0;
}
.dropdown-menu > .disabled > a,
.dropdown-menu > .disabled > a:hover,
.dropdown-menu > .disabled > a:focus {
  color: #777;
}
.dropdown-menu > .disabled > a:hover,
.dropdown-menu > .disabled > a:focus {
  text-decoration: none;
  cursor: not-allowed;
  background-color: transparent;
  background-image: none;
  filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
}
```

I have created a JSfiddle with a working example at https://jsfiddle.net/unjg9mjs/3/

Initial quick fix is to remove the above code. But what I think is required is to add the css for btn and the btn-danger etc as an override eg 
```
.dropdown-menu > li > a .btn
{
...
}
.dropdown-menu > li > a .btn-danger
{
...
}
.dropdown-menu > li > a .btn-danger:hover
{
...
}
```

**Comment by v8xm** [comment]
This problem also exists in bootstrap3.

**Comment by mdo** [comment]
Buttons within dropdown items aren't supported; dropdown-items in themselves are singular click targets. If you want buttons or other content in there, don't try to nest them in the list items and anchors. Also note that the mentioned markup is from v3 and this has changed in v4.
