### ISSUE TITLE
Using col* css tags inside the elements other than div

### ISSUE THREAD

**Issue by cullsin** [twbs/bootstrap#21308]
Hi, 

Although it's not a bug, I would like to know whether It's Good design or bad design to use col* tags other than Div.
If so, what's the difference between the actual Div vs Element layout. 
If not, How do I stop that one may or may not be include that Css class in the element which is not a div.

For example, 
I can use "col-md-12" inside "li". Is that allowed ? 

Thanks,
Raja K

**Comment by mdo** [comment]
You can use most of our classes on just about any elements, though we encourage semantically neutral (`<div>`) elements or more purposeful elements like `<section>`, `<article>`, etc. Any of those works well. When you're mixing with other types of elements like list items, headings,  buttons, links, list items, and the like, you might run into unforeseen design issues or bugs.
