### ISSUE TITLE
[Bug] Tooltip in Button

### ISSUE THREAD

**Issue by turbopixel** [twbs/bootstrap#21302]
In our project code, we have a button group with fontawesome icons and bootstrap tooltip in <a>-links. The button jump to the right on hover a button.

**Example** https://jsfiddle.net/nok3s/qkedaxtg/3/

## Test case
**Operating system** 
* Linux Ubuntu 16.04.1 LTS
* Mac OS X

**Browser**
* Google Chrome (Version 53.0.2785.89 (64-bit))
* Firefox for Ubuntu (Version 48)
* Mac Safarie
* Mac Chrome

**Bootstrap Version**
* 3.3.7

**jQuery Version**
* 1.12.1
* 2.2.4

**Comment by Johann-S** [comment]
You have to use the ``container`` option like this : 
```javascript
$('[data-toggle="tooltip"]').tooltip({ container : 'body' });
