### ISSUE TITLE
Make $card-deck-margin default to $grid-gutter-width-base / 2

### ISSUE THREAD

**Issue by aRestless** [twbs/bootstrap#21300]
Cards are a cool concept, but with default values card-decks are somewhat incompatible to mix-and-match with elements designed with the grid system, see https://jsbin.com/butapaqucu/edit?html,css,output, which results in a layout with irregular (i.e. bad) spacing.

Setting `$card-deck-margin` to `$grid-gutter-width-base / 2` by default would result in the same spacing for all these elements, regardless of origin.

**Comment by mdo** [comment]
Closing as dupe of #19883, which will be fixed shortly.
