### ISSUE TITLE
Documentation $enable-flex Needs Improvement 

### ISSUE THREAD

**Issue by imcodingideas** [twbs/bootstrap#21304]
The documentation is confusing for newcomers looking to _get started_ with **sass** and **flexbox**. Currently the [documentation](http://v4-alpha.getbootstrap.com/getting-started/flexbox/) says: 

- Open the __variables.scss_ file and find the _$enable-flex_ variable.
- Change it from _false_ to _true_.
- Recompile, and done!

This is where it gets confusing: Most of us are using task managers like gulp or grunt, and dependency manages like bower. In my case I'm _@import "bootstrap";_ in my style.scss file. This leaves to questions which I think the documentation needs improvement: 

To properly override this variable do I need go into bower_compoonents/bootstrap/scss/ __variables.scss_ and change it there or do I need to create that file in: /public/assets/sass/ _variables.scss with 1 variable $enable-flex: true

I wouldn't mind updating documentation if I knew this answer myself.

**Comment by razh** [comment]
The documentation should suggest modifying [`_custom.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom.scss) instead. The [Getting Started > Options](http://v4-alpha.getbootstrap.com/getting-started/options/) section was updated, but not flexbox.

You can also create your own `_custom.scss` file and `@import` it before you `@import bootstrap;`.

**Comment by Starsam80** [comment]
If flex is the only thing you need enabled, you could always try `@import "bootstrap-flex"`, but I can't guarantee that will work.

**Comment by imcodingideas** [comment]
razh, that worked. :) I created a _custom.scss and @import before. Worked perfectly. :)

**Comment by mdo** [comment]
We're, uh, removing the option entirely. 😆 Won't be an issue anymore with #21389—we're going all in on flexbox.
