### ISSUE TITLE
The .m-* and .mb-* classes are not documented

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#21313]
The classes `.m-*`, and `.mb-*` classes are not in the documentation.

**Comment by afuno** [comment]
http://v4-alpha.getbootstrap.com/utilities/spacing/

**Comment by vanillajonathan** [comment]
Oh, thanks. I missed that. My bad.

Perhaps it would be easier to use, understand and memorize Bootstrap and it would be more intuitive if it used the class names fully spelled out instead of short cryptic letters.

I.e. `.margin-top-3` instead of `.mt-3`.

**Comment by afuno** [comment]
I like the current solution. A minimalistic and not conspicuous (in the code). Why this (`mb-1`) should be obvious?

**Comment by mdo** [comment]
Closing since these are indeed documented. Once you use them a few times, the format starts to make more sense and feel natural :).
