### ISSUE TITLE
Disable/Enable affix 

### ISSUE THREAD

**Issue by rajamuthur** [twbs/bootstrap#21316]
I can able to destroy affix by using
[Working Fine]
$(window).off('.affix');
$([selector]).removeData('affix').removeClass('affix affix-top affix-bottom');

But, unable to enable affix for same element
[Not working]
$(window).on('.affix');
$([selector]).affix({
offset: {
top: function () {
return $([selector]).position().top;
}
}
});

Is there any specific way to destroy/disable affix for specific element ?
Thanks in advance.

**Comment by cvrebert** [comment]
Bootstrap v3 is no longer officially supported.
See https://github.com/twbs/bootstrap/blob/v3-dev/README.md#community for community forums which might be able to give you advice.

**Comment by saury** [comment]
I used to do the refresh job just write the code below. And that works properly.  I've not test but you can try not adding `$(window).on('.affix');` in your case.
```
// destroy
$(window).off('.affix');
$([selector]).removeClass('affix affix-top affix-bottom').removeData();

// init again
$([selector]).affix(...);
```

**Comment by rajamuthur** [comment]
Thanks for reply,
I tired. but not working :(
Able to destroy but unable to init again
