### ISSUE TITLE
.navbar-brand does not scale with font-size

### ISSUE THREAD

**Issue by mateddy** [twbs/bootstrap#21319]
Using the code from: http://v4-alpha.getbootstrap.com/components/navbar/ (v4.0.0-alpha.5)

If the style "body{ font-size: 200%; }" is applied, the rest nav-item does scale, however navbar-brand does not.

**Comment by mdo** [comment]
This is because `.navbar-brand`, like nearly all our type, is using rem units. Rem units scale from the root element, which is `<html>` and not `<body>`. To do this right, you'll want to set `html { font-size: 200%; }`.
