### ISSUE TITLE
Feature Request: Floating Labels

### ISSUE THREAD

**Issue by imcodingideas** [twbs/bootstrap#21312]
I want to add a feature request! I would like to see floating labels be incorporated into bootstrap 4. Please take a look at this dribble shot: https://dribbble.com/shots/1254439--GIF-Float-Label-Form-Interaction which shows this in action as well as some pros for it:

> User keeps context
> The main advantage of this pattern is that the user keeps the field’s context after they’ve focused and entered a value. This provides for a more accessible, less frustrating experience.
> 
> Clean and scannable by default
> This pattern allows for a clean inline label experience by default, and only becomes a little more cluttered once the user has filled things out.
> 
> Elegant
> It needs to be said: this pattern is sexy. You usually can’t say that about forms. It looks good and the animations are a nice subtle touch.
> 

Google uses floating labels in their material design: https://material.google.com/components/text-fields.html#text-fields-floating-labels and designers love them: https://dribbble.com/search?q=floating+label 

Here is a live example http://mrlopez.me/bootstrap-floating-labels/ someone else did with bootstrap.

**Comment by IamManchanda** [comment]
+1

**Comment by Herst** [comment]
@IamManchanda Interesting, but I don't think differentiating between the label and placeholder text is a good idea.

**Comment by IamManchanda** [comment]
Why not .... label and placeholder are two different species

for eg.
```
Label: Name 
Placeholder: Enter Name here 
```

But yeah if you dont want it no issue just safely remove placeholder's 
like this here --> http://jsfiddle.net/pLzqy9mn/

**Comment by leovafme** [comment]
Alternative with pure css

http://jsfiddle.net/g094quoc/

**Comment by patrickhlauke** [comment]
i wouldn't mind a (CSS only) solution for this, though it will need to be made clear that the construct will likely require a very specific set/order of markup, and that the component needs enough top padding to allow for the label to then float up when field is focused or contains actual value.

**Comment by aardrian** [comment]
I have one I have been playing with on and off for a while now, but it does not work properly in Edge (labels start floated) nor IE (placeholder is shown too soon): https://codepen.io/aardrian/pen/MeeZrQ

I am working on a simplified block of code for a blog post (removes the radio/checkbox, gets rid of validation experiments, etc), but it won't be ready for a bit owing to Reasons.

The key approach, IMO, is to create good, valid, accessible mark-up first, and only then fold in the styles (and possibly) script to achieve what you want.

**Comment by archatas** [comment]
The [floating-labels example](https://getbootstrap.com/docs/4.0/examples/floating-labels/) works very nicely - I appreciate for how smothly the placeholder turns into a label placed above the field. But it would be even better, if the label was listed before the input field in the markup. It would add value for semantics and accessibility.

I tried to exchange the fields and hack the CSS to create an example, but I guess there are better CSS masters here than me.

**Comment by patrickhlauke** [comment]
as CSS doesn't have any way to "go back" to style a preceding element, unfortunately we're stuck with this order.

**Comment by Ruffio** [comment]
I was thinking of using the floating label on my website, but it appears to have been changed :-(

4.0 (https://getbootstrap.com/docs/4.0/examples/floating-labels/):
![image](https://user-images.githubusercontent.com/1877612/43541385-9dcea2a6-95ca-11e8-8d1a-8aba81fa8535.png)

4.1 (https://getbootstrap.com/docs/4.1/examples/floating-labels/):
![image](https://user-images.githubusercontent.com/1877612/43541409-aed3056a-95ca-11e8-9281-8265d71e1533.png)

Actually I think that the changes happened when 4.1.3 was released and a fixed height of 38px was introduced as it goes from 50px (calculated) to 38px (set):
![image](https://user-images.githubusercontent.com/1877612/43541755-72be4e44-95cb-11e8-95f2-24f0577d2a24.png)

![image](https://user-images.githubusercontent.com/1877612/43541835-aa1aedde-95cb-11e8-8196-af6b2b2ad80c.png)

**Comment by mdo** [comment]
Ah, this is the `height` stuff I did. Can you open a new issue for this @Ruffio?

**Comment by micka-fdz** [comment]
Hello, any news about this feature request? Maybe an implementation in v5?

**Comment by imcodingideas** [comment]
Check this out: 

https://getbootstrap.com/docs/4.4/examples/floating-labels/

**Comment by StayCoolDK** [comment]
I agree that this would be a nice feature for v5 - what would be the issue in making https://getbootstrap.com/docs/4.4/examples/floating-labels/ a part of v5? Seems to have decent support.

**Comment by mdo** [comment]
I should be able to pull in https://getbootstrap.com/docs/4.4/examples/floating-labels/ and make it a legit component of Bootstrap now that we've dropped IE11. However, the classic Edge doesn't support this exactly. It doesn't break anything, but only the new MS Edge built on Chromium works as intended.

**Comment by mdo** [comment]
See #30449, which is also adding support for `<select>`s.

**Comment by micka-fdz** [comment]
Good news! Is it possible to add support for `<textarea>` and `.form-file` elements?

**Comment by tkrotoff** [comment]
I've implemented floating labels for Bootstrap 4 here: https://github.com/tkrotoff/bootstrap-floating-label

![demo](https://user-images.githubusercontent.com/643434/77843350-92cd8200-719c-11ea-98ce-1da9852d4ab4.gif)
