### ISSUE TITLE
Add btn-outline-*-inverse for dark backgrounds

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21311]
`btn-outline-*` is a great option but adding inverse classes ( `btn-outline-*-inverse`  ) will help buttons on dark backgrounds to be presented better

for eg. 

```
btn-outline-primary-inverse {
    color: #fff;
    background-image: none;
    background-color: transparent;
    border-color: #fff;
}
.btn-outline-primary-inverse:hover {
    color: #fff;
    background-color: #0275d8;
    border-color: #0275d8;
}
.btn-outline-primary-inverse:focus, .btn-outline-primary-inverse.focus {
    color: #fff;
    background-color: #0275d8;
    border-color: #0275d8;
}
```

Adding some screenshots for the demo purposes 

![screenshot from 2016-12-07 11-28-42](https://cloud.githubusercontent.com/assets/4970624/20956675/6657a7d4-bc71-11e6-8cf5-a71dd1818bb1.png)

![screenshot from 2016-12-07 11-29-02](https://cloud.githubusercontent.com/assets/4970624/20956684/79d047bc-bc71-11e6-8b85-6539a1a14be5.png)

**Comment by IamManchanda** [comment]
@cvrebert @mdo guys i think this should be looked up ! Please look into it ?

**Comment by cvrebert** [comment]
@IamManchanda Hello! Bootstrap is an all-volunteer project, so unless otherwise stated, please don't assume any particular timeline for responding to issues/suggestions. But we will get around to considering your suggestion eventually. Thank you for taking the time to propose this suggestion.

**Comment by IamManchanda** [comment]
@mdo Still love you guys but passing on this and closing!
