### ISSUE TITLE
Smooth scroll on iOS

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#21329]
I have some troubles having a smooth scroll in touch screen devices for a form. Something is wrong but I can't figure out what: not sure if it's a bug. 

Here is my index (pug and Angular 2):

    doctype html
      html
       head
        base(href="/")

        title MyApp

        meta(charset='utf-8')
        meta(name='viewport', content='width=device-width, initial-scale=1, shrink-to-fit=no')
        meta(http-equiv='x-ua-compatible', content='ie=edge')

        link(rel='icon', href='images/favicon.ico')
        link(rel='stylesheet', type='text/css', href='stylesheets/bootstrap-flex-4.alpha5.min.css')
        script(type='text/javascript' src='javascripts/bootstrap-4.alpha5.min.js')
        body
            my-app(style='height:100%')
                #loader

(Please note that I have removed angular code for better clarity)

My app code:

    div#main.container-fluid(style='width:100%; height:100%;')
       #content.row.flex-items-xs-center(style='min-height:100%;')
         .col-xs-12.col-sm-10.col-md-8.col-lg-6
             router-outlet

and my form:

    div.survey
      div.row(style='margin-bottom:30px;')
        h3.col-xs-12.col-sm-12.col-md-12 Hello

    form([formGroup]='form', novalidate='', (ngSubmit)='postSurvey(form.value, form.valid)')
        div(style='margin-bottom:80px')
            div.row.question-row(*ngFor='let item of survey.pages[page].questions; let idx=index', [formGroupName]='idx')
                // INFO
                div.col-xs-12.col-sm-12.col-md-12
                    label.question {{ (item.id | findItem:questions).question[lang]}}
                // NUMBER
                div.col-xs-12.col-sm-12.col-md-12
                    .form-group
                        label.form-control-label.question {{ (item.id | findItem:questions).question[lang] }}
                            span.required
                        input.form-control(number, name='answer', type='number', placeholder='Reponse', formControlName='answer')

                // TEXTAREA
                div.col-xs-12.col-sm-12.col-md-12
                    .form-group
                        label.form-control-label.question {{ (item.id | findItem:questions).question[lang] }}
                            span.required
                        textarea.form-control(autosize, name='answer', placeholder='Reponse', formControlName='answer')

I have an example [here](http://hartena.azurewebsites.net/survey/291T9z/q5aZaMS) so you can easily try with a touch device (I've tried on my iPhone using Safari ios 10)

**Comment by cvrebert** [comment]
Unfortunately, we are unable to provide assistance with issues potentially related to third-party libraries such as Angular.
If you can make an example which doesn't use Angular, then we might be able to take a look.

**Comment by natcohen** [comment]
I discovered I applied a `width:100%` on the `html` tag and the `body` which made the view sticky
