### ISSUE TITLE
[Firefox] Non-standard Array/String generics have been deprecated

### ISSUE THREAD

**Issue by twbs-notify** [twbs/bootstrap#21324]
https://www.fxsitecompat.com/en-CA/docs/2016/non-standard-array-string-generics-have-been-deprecated/

**Comment by cvrebert** [comment]
It's unlikely that we use any of these.

**Comment by bardiharborow** [comment]
We don't, as far as I can see.

**Comment by Johann-S** [comment]
I didn't checked all the projet but we use some of them for exemple : 

- Array.push in : scrollspy.js  (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/scrollspy.js#L148-L149)
- Array.join in : scrollspy.js (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/scrollspy.js#L253)
- Array.filter in : scrollspy.js (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/scrollspy.js#L145)
- Array.forEach in : tooltip.js and scrollspy.js
- String.split in : tooltip.js and scrollspy.js

**Comment by cvrebert** [comment]
Only static methods were deprecated. The standard, non-static methods aren't affected. Read the original link for details.
