### ISSUE TITLE
[Chrome] bootstrap.js as a chrome extension content script

### ISSUE THREAD

**Issue by dgbrokaw** [twbs/bootstrap#21339]
Mac OS X El Capitan 10.11.6
Chrome Version 54.0.2840.98 (64-bit)

In the context of chrome extensions, if the bootstrap javascript is executed as a content script on a page that already uses bootstrap javascript, these plugins will no longer work.

To reproduce:

1. Download this repo: https://github.com/dgbrokaw/bootstrap-extension.
2. Load the repo folder as an unpacked extension in chrome: chrome://extensions/.
3. Open the page http://getbootstrap.com/javascript/#dropdowns.
4. Click on the dropdown buttons.  They will not open.

**Comment by patrickhlauke** [comment]
This seems like you're using bootstrap for what it's not intended, and noting that this then conflicts on sites that use it as intended? I would think the onus is on you there to debug what you're doing at your end in the extension?

**Comment by tomlutzenberger** [comment]
Before executing, you could check if there's already an identical named function.

```javascript
  if ($.fn.bootstrapFunction) {
    // bootstrap.js already included on the site
  } else {
    // execute
  }
```
