### ISSUE TITLE
Footer goes to the top

### ISSUE THREAD

**Issue by soljohnston777** [twbs/bootstrap#21344]
When you do 360x640, the footers go to the top of the screen unless you do a lot of css customizations.  I would love to see this fixed in bootstrap 4.

**Comment by patrickhlauke** [comment]
They shouldn't, and I've not encountered any situations where that would be the case. Sounds more likely that whatever markup you're using, or CSS modifications/additions you may have made, are the cause (unless you can provide an minimal test case)

**Comment by soljohnston777** [comment]
I am using a wrapper and I think this is why it is an issue.

**Comment by patrickhlauke** [comment]
In that case, please use stackoverflow or similar for help. see https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md#using-the-issue-tracker
