### ISSUE TITLE
Issue with Bootstrap 4 Flexbox Layout and Intervening Tags Between .row and .col-*

### ISSUE THREAD

**Issue by agatlin** [twbs/bootstrap#21358]
HTML frameworks (e.g. Angular 2) often generate their own custom tags which get injected into the HTML. Depending on how components are structured, that HTML can sometimes be injected in between the elements which define `.row` and `.col-*` settings. This actually works fine in the old-style bootstrap grid system. However, with the new Flexbox grid system in Bootstrap4, it causes the columns to stack rather than to display as expected.

It appears that any tag injected between a `.row` and `.col-` definition will cause this adverse column stacking behavior.

Following is a sample snippet which demonstrates the issue. 

```
<!doctype html>
<html lang="en">

<head>
    <title>Bootstrap 4 Container Test</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="bootstrap-flex.css">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="uh-oh-i-am-an-intervening-tag">
                <div class="col-xs">
                    <h1>Way Back When</h1>
                    <p>Theming with pure CSS in the old days was very challenging.</p>
                </div>
                <div class="col-xs">
                    <h1>Recently</h1>
                    <p>Bootstrap 1-3 made things a bit easier.</p>
                </div>
                <div class="col-xs">
                    <h1>Moving Forward</h1>
                    <p>Bootstrap 4 finally makes theming enjoyable.</p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
```

Note: This was tested using `bootstrap@4.0.0-alpha.5`.

**Comment by cvrebert** [comment]
Given how CSS works, it's difficult, and often infeasible in the general case, to be robust to inserting arbitrary elements at arbitrary places in the DOM. So there might be no way around this besides tweaking your Angular code.

**Comment by agatlin** [comment]
Well, Bootstrap 3 works fine, and Bootstrap 4 (non Flexbox version) works fine too. I am relatively hopeful that there is a workable solution here. This is particularly important given that Angular 2 is a major SPA framework and will only grow in popularity now that it is out of beta. I am sure a very high number of Angular developers would prefer to use Bootstrap. If this issue cannot be resolved, it might discourage them. I should point out that Angular is not the only framework that inserts its own tags or even div tags at odd places. Failure to fix this issue could have implications with a variety of frameworks.

**Comment by mdo** [comment]
There are likely no issues with the default grid systems because they are all block level and use floats. With flexbox, you'll need to appropriately set the `display` or `flex` on those in-between elements. This has to be done on your end selectively, otherwise we risk restyling far too many things for folks.
