### ISSUE TITLE
Requirejs asynchronous loading of bootstrap does not fire window load event

### ISSUE THREAD

**Issue by dvpandianwipro** [twbs/bootstrap#21350]
When i load bootstrap asynchronously using requirejs windows load event fires before adding the below load event.  
if i change below callback function to $(document).ready(...) then it works fine
Is there any other way without changing the bootstrap code i can handle this?

```javascript
 // AFFIX DATA-API
  // ==============

  $(window).on('load', function () {
    $('[data-spy="affix"]').each(function () {
      var $spy = $(this)
      var data = $spy.data()

      data.offset = data.offset || {}

      if (data.offsetBottom != null) data.offset.bottom = data.offsetBottom
      if (data.offsetTop    != null) data.offset.top    = data.offsetTop

      Plugin.call($spy, data)
    })
  })

```

Modified code 

```javascript
  // AFFIX DATA-API
  // ==============

  $(document).ready( function () {
    $('[data-spy="affix"]').each(function () {
      var $spy = $(this)
      var data = $spy.data()

      data.offset = data.offset || {}

      if (data.offsetBottom != null) data.offset.bottom = data.offsetBottom
      if (data.offsetTop    != null) data.offset.top    = data.offsetTop

      Plugin.call($spy, data)
    })
  })


```

**Comment by Johann-S** [comment]
I'm not sure it's a Bootstrap problem here, you can look in requirejs issue like this one : https://github.com/requirejs/requirejs/issues/875 and more precisely : https://github.com/requirejs/requirejs/issues/875#issuecomment-24788009

**Comment by hnrch02** [comment]
v4 claims to have UMD support, so this is a Bootstrap problem. Simplest solution I can think of is to look at the [`document.readyState`](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) and then deciding whether to listen for the load event or not.

**Comment by hnrch02** [comment]
(Please note that the examples you sent are from the Affix plugin which no longer exists in v4. The Scrollspy and Carousel plugins still use load event listeners in v4 though.)

**Comment by XhmikosR** [comment]
@Johann-S: is this still valid?

**Comment by Johann-S** [comment]
Currently on a lot of our plugins we immediately set listeners (for event delegation, or to immediately create an instance of the plugin needed).

But our plugins are UMD and there is a workaround to fix that, it's to instanciate the plugin you need manually.

So we can close this.
