### ISSUE TITLE
Rename .font-weight-bold to logical state name (.font-weight-strong)

### ISSUE THREAD

**Issue by klaslundberg** [twbs/bootstrap#21355]
The variable names introduced in #18433 and [968282e](https://github.com/twbs/bootstrap/commit/968282e587cc9c9f520d57df51ab38ef04f4c3ec) for strong text are based on the physical state name **bold** instead of the logical state name **strong**. This leads to confusion when you want to change/override these styles with custom styling. 

Let's say you want to change the `.font-weight-bold` style to `font-weight: 500; // Medium`  and then use `font-weight: bold;` in styles somewhere else, then the names gets confusing.

The names should be changed to match the `<strong>` element used in html.
Discussions about strong vs bold can be read at [MDN - &lt;strong&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong).

Similar renaming might also be applicable for `.font-italic`, but thats more open for discussion, since it has another meaning. More to read at [MDN - &lt;em&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em)

So I propose renaming to the following:
`.font-weight-strong    { font-weight: bold; }`

**Comment by mdo** [comment]
I'm not super concerned about the naming of these utilities. If there's enough feedback around it into v4 once it's stable I can add aliases. Until then, no planned changes. Thanks though!
