### ISSUE TITLE
Media component bug in Chrome 55 (easy fix)

### ISSUE THREAD

**Issue by stevendesu** [twbs/bootstrap#21359]
Issue
=====

A strange race condition in Chrome for Windows causes `<div class="media">` components to display incorrectly **sometimes**

Details
=======

Having a `display: table-cell` element whose immediate parent is not a `display: table-row` or `display: table` is invalid according to the W3C table spec:

https://www.w3.org/TR/CSS2/tables.html#table-display

**However**: According to the W3C spec, when an element is misparented an anonymous element should be generated around it with the proper display type. Therefore there should be no issue. And this is, in fact, the case in Internet Explorer and Firefox (did not test Safari or Opera)

A bug or race condition in Chrome causes it to improperly generate these anonymous elements when the page takes too long to render (many DOM elements on the page). The net effect looks like so:

![broken](https://cloud.githubusercontent.com/assets/1384974/21289936/b4b3acda-c477-11e6-8306-ad54ea7fb310.jpg)

Repro
=====

 - **Operating system:** Windows 10
 - **Browser:** Chrome 55

In order to create this effect I had a page with **many** elements above the media item:

 - A responsive navbar
 - A carousel
 - A collapsible form with multiple form-groups and inputs
 - Images, text, etc

At the bottom of the page I had a card with a media inside of it:

```html
<div class="row">
    <div class="col-sm-6"><!-- Repeated element -->
        <div class="card mx-auto">
            <img class="card-img-top w-100" src="...">
            <div class="card-block px-0 py-0">
                <div class="media">
                    <a class="media-left pr-0" href="...">
                        <img class="media-object" src="...">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading>...</h4>
                        <div class="pl-1">
                            <p class="small my-0">...</p><!-- Repeated element -->
                        </div>
                </div>
                <a href="..." class="btn">...</a>
            </div>
        </div>
    </div>
</div>
```

Fix
===

By setting `display: table` on `.media` it generates properly every time:

```scss
.media {
    display: table;
}
```

Fixed:

![fixed](https://cloud.githubusercontent.com/assets/1384974/21289977/aab3cc1e-c478-11e6-90b0-aae520087a80.jpg)

**Comment by cvrebert** [comment]
@stevendesu Please post the URL of your example webpage or a link to a CodePen/JSBin/etc. example that demonstrates the problem, so that we can file a Chrome bug.

**Comment by stevendesu** [comment]
https://jsbin.com/ruhoqocumo/1/edit?html,output

**Comment by mdo** [comment]
Won't be an issue anymore with #21389—we're going all in on flexbox.
