### ISSUE TITLE
How do I enable the gradient buttons in BS4 as BS3 has using its theme.css?

### ISSUE THREAD

**Issue by gfdesign** [twbs/bootstrap#21367]
Dear community
I want to be able to give to buttons the same gradients as BS3 has, using its bootstrap-theme.min.css
<img src="http://i.imgur.com/jNwZ6ce.jpg" alt="">
I've enabled _$enable-gradients_ to **true** in my compilation but I don't see any effect on them.
<img src="http://i.imgur.com/74V36Zu.jpg" alt="">
What am I doing wrong?
Regards

**Comment by wolfy1339** [comment]
Can I see your ` _variables.scss`

**Comment by gfdesign** [comment]
It's the same of the repository.
I am setting up the variables from my own SASS file (styles.scss) like this:

`
$enable-flex:               true;
$enable-rounded:            true;
$enable-shadows:            true;
$enable-gradients:          true;
$enable-transitions:        true;
@import "Bootstrap4/bootstrap";
`
I know this set up works fine because I can see when I change the rest of variables, they compile as expected, except as I mentioned $enable-gradients as value true :/

**Comment by wolfy1339** [comment]
I can't find anywhere in the code that $enable-gradients is used. It's just a dummy variable defined

**Comment by gfdesign** [comment]
That's why BS4 is still in alpha state? :P

**Comment by mdo** [comment]
I'm guessing I nuked this some time ago and never restored it. I'll have to swing back around to it, likely in v4.1.

**Comment by gfdesign** [comment]
Thanks for replying. 
My respect and admiration for your work.

**Comment by Rustin** [comment]
Ran into this today. I'm sorry for a potential dumb question, but is using the gradients possible before you've had a chance to get $enable-gradients: back in there?

**Comment by LarryAzevedo** [comment]
@mdo `$enable-shadows` and `$enable-gradients` need to be revisited as they do not give the result I believe most people are expecting.  For example, here is a _before and after_ of the shadows setting:
![screen-shot-2017-09-04-at-3 12 57-pm](https://user-images.githubusercontent.com/2222751/30037584-5bf109a4-918a-11e7-89a8-07b38bba9359.png)

Consider changing line 339 of variables.scss from `$btn-box-shadow: inset 0 1px 0 rgba($white,.15), 0 1px 1px rgba($black,.075)` to something like `$btn-box-shadow: 0 2px 2px rgba($black,.2)`.

Also, what do people think about shadows being applied to cards and nav pills when `$enable-shadows` is set to true?
