### ISSUE TITLE
v4 examples, empty navbars.

### ISSUE THREAD

**Issue by gpakosz** [twbs/bootstrap#21364]
Despite #17532 being [marked as resolved and closed](https://github.com/twbs/bootstrap/issues/17532#issuecomment-254742079), visiting https://v4-alpha.getbootstrap.com/examples/navbar-top-fixed/ gives a navbar containing nothing but the toggler:

```
    <div class="pos-f-t">
      <div class="collapse" id="navbar-header">
        <div class="container-fluid bg-inverse p-1">
          <h3>Collapsed content</h3>
          <p>Toggleable via the navbar brand.</p>
        </div>
      </div>
      <div class="navbar navbar-light bg-faded navbar-static-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation"></button>
      </div>
    </div>
```

The parent documentation page features a [screenshot of a navbar containing many different items](https://v4-alpha.getbootstrap.com/examples/screenshots/navbar-fixed.jpg) but here is what I get:
![image](https://cloud.githubusercontent.com/assets/553208/21314967/2666b8d0-c5fa-11e6-856f-8c66710d5a1f.png)

**Comment by petetnt** [comment]
The collapsed content is the same color as the background too: 

![image](https://cloud.githubusercontent.com/assets/7641760/21315251/e846aac4-c603-11e6-880f-79d9682b49cc.png)

**Comment by bardiharborow** [comment]
It appears I forgot to push my examples PR that fixes this. I'll push that in the morning.

**Comment by gpakosz** [comment]
Any idea when website is updated?

**Comment by bardiharborow** [comment]
@gpakosz the website is only updated when there is a release.
