### ISSUE TITLE
Aligning collapsible button to the right makes the list messy

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#21361]
Trying to make the collapsible button of the navbar aligned to the right and keeping the brand to the left makes the list messy like in this example (tested on latest chrome):

https://plnkr.co/edit/gHA1Ea7JhYX2eWSyOgWp?p=preview

As you can see the "home" stays on the top and the rest moves to the left only when it's fully collapsed...

**Comment by jipexu** [comment]
you can fix with this 
  ```
<div class="clearfix">
      <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler hidden-lg-up float-xs-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
  </div>
```

**Comment by natcohen** [comment]
When you do that, you get two lines when the button is not active.
Try to make your window big with this example: https://plnkr.co/edit/wAclPZLjJTDKHppVUMCX?p=preview

**Comment by jipexu** [comment]
https://plnkr.co/edit/uMwX3uvE7ZmRfUIWDNKE
