### ISSUE TITLE
Grid : Document choice of negative margin on the container vs resetting first-child and last-child left/right margin

### ISSUE THREAD

**Issue by gkatsanos** [twbs/bootstrap#21365]
I attempted recently to "extend" the Bootstrap grid with the following:

```
.row-no-gutter {
    margin: 0;
}

.row-no-gutter>* {
    padding: 0;
}

.row-small-gutter {
    margin-left: -$grid-gutter-small;
    margin-right: -$grid-gutter-small;
}

.row-small-gutter>* {
    padding-left: $grid-gutter-small;
    padding-right: $grid-gutter-small;
}

.row-large-gutter {
    margin-left: -$grid-gutter-large;
    margin-right: -$grid-gutter-large;
}

.row-large-gutter>* {
    padding-left: $grid-gutter-large;
    padding-right: $grid-gutter-large;
}

```

Things generally "worked" , until I resized down to mobile and noticed the `.container-fluid` was still applying the (default) grid padding of `15px`, resulting in Horizontal scrollbars.

By the look of things, we can't have different gutter widths with the current Grid implementation?

Provided the above's correct, is there a documented discussion somewhere over the decision of the "negative margins" on the container versus something like resetting the left margin of the first child and the right-margin of the last child? (I am pretty sure that also has side-effects but I'd like to skip the part of researching this on my own when I can safely imagine this has already been widely researched by the community)

Many thanks and cheers!

*update* after some more research, it is the problem of mobile is remedied by min-width media-querying `.row-large-gutter` (still my question stands and that's not a bullet-proof solution)

```
@include bp-medium {
    .row-large-gutter {
        margin-left: -$grid-gutter-large;
        margin-right: -$grid-gutter-large;
    }

    .row-large-gutter>* {
        padding-left: $grid-gutter-large;
        padding-right: $grid-gutter-large;
    }
}
```

**Comment by cvrebert** [comment]
The CSS specificity increase in the `:first-child`/`:last-child` case was probably one factor in deciding against it.

**Comment by stevendesu** [comment]
I could be mistaken, but when I noticed the negative margins on columns I was under the assumption they did it to make columns more optional. Now if you put content directly into a row without a column it will have a padding, but if you use columns the columns applies the padding while still stretching to fill the space for the purpose of full-width backgrounds and the like.

I thought it was an awkward but neat hack

Consider the following:

```html
<div class="row">
    <h1>Title</h1>
    <div class="col-md-6">
        <p>...</p>
    </div>
    <div class="col-md-6">
        <p>...</p>
    </div>
</div>
```

This would have exploded in Bootstrap 3, but now works as expected

**Comment by gkatsanos** [comment]
@stevendesu let me clarify that my question is regarding Bootstrap 3.x and not 4.x . (saying this because from your post it seems its implied that this is a 4.x behavior)

@all : I guess the question could have been how do we add options for variable Grid Gutter sizes (like UiKit does) but this could be flagged as support/SO question; I would rather hear the opinion of the maintainers.

**Comment by cvrebert** [comment]
Unfortunately, we no longer support Bootstrap v3. But you might find the following article helpful:
http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works
Or you could try StackOverflow. The design decision most likely been explained in some old issue on this tracker; just a matter of someone tracking it down for you.

**Comment by gkatsanos** [comment]
@cvrebert that ticket closing is a little bit premature, the discussion was ongoing. 
Does Bootstrap v4 support multiple grid gutter widths?

**Comment by gkatsanos** [comment]
@cvrebert also, thanks for the link, I've been using Bootstrap since 3 years, I know quite well how the grid works.

**Comment by mdo** [comment]
> By the look of things, we can't have different gutter widths with the current Grid implementation?

Answering that question @gkatsanos, no you cannot have different gutter widths in v3. We don't provide that out of the box, but you could further customize things and add it yourself.

**Comment by gkatsanos** [comment]
@mdo Thanks Mark, that's what I did as you can see above. But what about v4? Is it an option there? I was just looking at the documentation and the options looked more or less the same as v3. 
Which channel do I use to ask for that feature?

**Comment by gkatsanos** [comment]
(just to clarify I realized that blindly using one framework even if that's the most popular sometimes isn't the best idea if it's not built to satisfy your most common use cases)
