### ISSUE TITLE
<figure> seems to cause <img> to be resized incorrectly in IE11

### ISSUE THREAD

**Issue by micwic** [twbs/bootstrap#21360]
I just created www.toboggan.me by using Bootstrap4 Alpha5. This site with just on page is public and accessible.
I have seen a difference (a bug) in the rendering in IE11.576.14393.0 (W10).
I know other IE11 version are also affected. Don't currently know much more.
The error is located in a figure tag that allow to render a copyright mention in the first image after the home background image. Just click the chevron down to see the difference.

In IE11 the height is set to the height of the image instead the resized height depending on the row height. MS Edge doesn't have this problem.
[exportToHTML.zip](https://github.com/twbs/bootstrap/files/659357/exportToHTML.zip)

**Comment by micwic** [comment]
I just created www.toboggan.me by using Bootstrap4 Alpha5. This site with just on page is public and accessible.
I have seen a difference (a bug) in the rendering in IE11.576.14393.0 (W10).
I know other IE11 version are also affected. Don't currently know much more.
The error is located in a figure tag that allow to render a copyright mention in the first image after the home background image. Just click the chevron down to see the difference.

In IE11 the height is set to the height of the image instead the resized height depending on the row height. MS Edge doesn't have this problem.
[exportToHTML.zip](https://github.com/twbs/bootstrap/files/659357/exportToHTML.zip)

**Comment by mdo** [comment]
Sorry, but I'll need way more reduced than your live site or the exported files in that zip to be able to help you out at all. Please create a reduced test case with the bare minimum HTML and CSS in something like JS Bin.

**Comment by mdo** [comment]
Closing given lack of reply. Please comment with an updated example and we can revisit.
