### ISSUE TITLE
Popover/Tooltip placement logs tether error

### ISSUE THREAD

**Issue by chapterjason** [twbs/bootstrap#21362]
I tried the `auto` placement like described in the documentation

> When "auto" is specified, it will dynamically reorient the popover. For example, if placement is "auto left", the popover will display to the left when possible, otherwise it will display right.

After nothing happens I saw an error in the console.

> Error: Tether Error: You must provide an attachment

On a bit debugging I found out that `attachment` is `undefined` in the `tooltip.js` what extends the `popover.js` cause the AttachmentMap does not provide any `auto left`

https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L282

**Comment by Johann-S** [comment]
A codepen to show the issue : http://codepen.io/Johann-S/pen/NbojYb
