### ISSUE TITLE
Any way to listen to bootstrap dropdown to mousedown event instead of click/mouseup?

### ISSUE THREAD

**Issue by maxlibin** [twbs/bootstrap#21369]
Any way to listen to bootstrap dropdown to mousedown event instead of click/mouseup?

**Comment by cvrebert** [comment]
Because...?

**Comment by patrickhlauke** [comment]
This would make dropdowns unusable for keyboard users, so not really an advisable move?

**Comment by maxlibin** [comment]
someone did this on older version: https://github.com/adobe/brackets/pull/5430/commits/57b8d39addd39e29c42bb6bdd835e6521ab15d7c

It would be nice when mouse down and dropdown-menu will be shown, example gmail dropdown behaviour.
<img width="443" alt="screen shot 2016-12-20 at 5 58 57 pm" src="https://cloud.githubusercontent.com/assets/1277038/21346159/14b9adb0-c6de-11e6-844b-84e4c3ff4f16.png">

**Comment by hnrch02** [comment]
> This would make dropdowns unusable for keyboard users, so not really an advisable move?

I'm gonna go ahead and close this for this reason.

BTW, you can remove the click event listeners that we set by [turning off the data API](https://v4-alpha.getbootstrap.com/getting-started/javascript/#data-attributes) for your dropdowns and manually manage dropdown toggles with `$().dropdown('toggle')` if you need this.

**Comment by julianlam** [comment]
> I'm gonna go ahead and close this for this reason.

I know this issue is closed, but... **does it**? I'd bet it works in gmail (not tested), and the existing click handler is *kept*, because otherwise mobile wouldn't work as there's no concept of mousedown. It's strict a nice-to-have desktop-only feature to allow you to open the menu on mousedown, and then mouseup to select the item you want. Saves you a click.

**Comment by patrickhlauke** [comment]
dropdowns in bootstrap can contain more than just menu items. i'm guessing it would require a bit of work to then work out how to make everything inside the opened menu react sensibly to mouseup too.

and yes the triggering can be done on mousedown AND click (and dedupe it, presumably, so it doesn't open on down and close as soon as it's released again and sends click), but there's a lot of scripting involved for little gain. no plan to do this in core bootstrap at this stage.
