### ISSUE TITLE
Jumping issue on affix.js while scrolling back

### ISSUE THREAD

**Issue by rahmangfx** [twbs/bootstrap#21372]
Sticky block is jumping up while scrolling back, I have specific layout as showed below fiddle.

```
<div class="container-fluid" style="padding:0">
      <div id="nav">Navigation</div>
      <div id="banner">Banner</div>
      <div class="container-inner pad-20">
        <div class="row" style="margin:0">
          <div id="rightContent" class="col-xs-12 col-lg-9 col-lg-push-3 left-20">
              right content
          </div>
          <div id="leftContent" class="col-xs-12 col-lg-3 col-lg-pull-9 right-20">
            <div id="sticky" data-width data-spy="affix" data-offset-bottom="350">
              Sticky part
            </div>

          </div>
        </div>
      </div>
      <div id="footer">Footer</div>
    </div>
```
http://jsfiddle.net/y82rb9cn/19/ 

Result is here: http://jsfiddle.net/y82rb9cn/19/embedded/#Result 

I have used bootstrap v3.3.7. How can i avoid this jumping? Anyone please help me.

**Comment by cvrebert** [comment]
Bootstrap v3 is no longer supported.
Please see https://github.com/twbs/bootstrap/blob/v3-dev/README.md#community for links to community support forums.

**Comment by rahmangfx** [comment]
Thanks for your reply. Would you mean that this is defect in v3 bootstrap and there is no support available on this version?

**Comment by cvrebert** [comment]
Yes
