### ISSUE TITLE
Partial _custom.scss is not in file .gitignore

### ISSUE THREAD

**Issue by BobbyBabes** [twbs/bootstrap#21377]
Is there a special reason why the partial ``_custom.scss`` was not added to ``.gitignore`` ?
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom.scss
https://github.com/twbs/bootstrap/blob/v4-dev/.gitignore

**Comment by mdo** [comment]
It's imported into the main Sass file, so without it there to start you'd have compilation errors. https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss

**Comment by BobbyBabes** [comment]
Now if you make changes to ``_custom.scss``. There is a conflict.
``.gitignore`` doesn't remove files.

**Comment by mdo** [comment]
> But now if I make changes to `_custom.scss` there is a conflict with the next git pull

This is only if we make changes to the file on the same lines that you've changed.

**Comment by BobbyBabes** [comment]
Thanks for coming back on this.
That sounds like removing the comment from ``_custom.scss`` (I replaced it with my own) also could cause the conflict.

Later today I will reset the file to original.
And copy+paste back my customised variables after the comment. To see what happens.

**Comment by bardiharborow** [comment]
@BobbyBabes, if `_custom.scss` isn't working for you, you can create your own SCSS file in your project and use `@import "bootstrap";`

**Comment by BobbyBabes** [comment]
@bardiharborow That's what I was already doing (second paragraph in my opening comment).
@mdo is right though. Making a new clone and modifying ``scss/_custom.scss`` works flawlessly with git pull.
Although I still get the conflict error (my local changes would be overwritten by git pull) in the first test clone of Bootstrap that I had made. Checking out the original ``scss/_custom.scss`` file is the only way (I know of) to get rid of the error.
