### ISSUE TITLE
Drop IE9 support for v4 beta?

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21387]
I'm close to pushing out a new v4 alpha, ideally our last alpha before the beta, and I found myself thinking about our IE support. Given how long v4 is taking—we've been in alpha for over a year—I'm way more comfortable suggesting we drop IE9 and go all in on flexbox. Here's why:

- It'd simplify our codebase (new features, maintenance, etc), given we're supporting two versions of many components right now.
- It'd remove a good amount of "duplicate" code from our CSS.
- It'd resolve some annoying bugs (e.g., broken table-styled button groups in tables).

Thoughts?

**Comment by coomberc** [comment]
fuck it, why not

**Comment by SpencerSharkey** [comment]
yes

**Comment by tomlutzenberger** [comment]
Totally into it. That's the only way to let old technology die.
If you choose to do it, would there be an additional alpha version or would you go right into beta with those changes?

**Comment by MehediH** [comment]
Yes please! I personally don't find supporting IE9 a necessity anymore, and users should just fucking upgrade their PCs at this point.

so yes, fuck it and drop ie9

**Comment by jasonmorehead** [comment]
Go for it.

**Comment by tillkruss** [comment]
Perfectly fine.

**Comment by felipesiqueira8** [comment]
Please drop ie9 !

**Comment by rafalp** [comment]
Using BS for JS apps in latest and greatest I am fine with IE < 11 going down the drain :]

**Comment by reinink** [comment]
I say go for it, especially with the lack of flexbox support in IE9. 👍

**Comment by psmyrdek** [comment]
Yup!

**Comment by bobbybouwmann** [comment]
Use bootstrap v3 if you need IE9 support right? We need flexbox support in 2017!

**Comment by robcresswell** [comment]
Yep, drop it. No good reason to support IE 9 nowadays.

**Comment by ctepeo** [comment]
BS4 without IE9 support? 0 fucks given. Let's be progressive!

**Comment by matiaspunx** [comment]
Drop it!

**Comment by cba85** [comment]
Yup ! New frameworks for new browsers, old frameworks for old browsers 😈

**Comment by arnireynir** [comment]
Drop it!

**Comment by adelivuk** [comment]
> I'm way more comfortable suggesting we drop IE9 and go all in on flexbox.

IE9 is a 5 years old browsers so yea - drop it. And if someone needs IE9 support, he can use bootstrap v3.

Also, love flexbox and it's features, especially that it supports RTL and it's nice vertical alignment. Maybe one day can we also drop `float`.

**Comment by jguadagno** [comment]
I would say, drop support for it.  Worse comes to worse, you or the community could make a "hotfix" for it.

**Comment by jminuscula** [comment]
Drop it, no worries. Organizations stuck with IE9 are probably stuck using old websites too!

**Comment by Starsam80** [comment]
I recommend using the GitHub reaction feature instead of spamming the comments

**Comment by mogusbi** [comment]
Microsoft no longer supports IE9 so why should any one else?

**Comment by peterfox** [comment]
:thumbsup: go for it

**Comment by michalstrzelecki** [comment]
Yes, drop it.

**Comment by andre-dw** [comment]
Drop

**Comment by skyrpex** [comment]
drop it

**Comment by sarcanon** [comment]
Kill it. Kill it dead.

**Comment by CarlQLange** [comment]
Running a large government website, and even here only about 1% of sessions are IE9, dropping over time. 

<img width="1012" alt="screen shot 2016-12-21 at 17 48 05" src="https://cloud.githubusercontent.com/assets/859820/21399948/b8c48264-c7a5-11e6-9af5-6b87f39d210f.png">

Might as well go for it, huh. Maybe a minor compatibility pass on some vital components.

**Comment by lstables** [comment]
IE sucks balls, don't support it! Simples!

**Comment by mdo** [comment]
Holy crap, okay fine, I'll drop it. 😆 

Locking this thread to avoid further notification overload to everyone watching the project here. Thanks for weighing in everyone, super appreciative of the feedback! If you want to discuss further, please hit me up on Twitter or open an issue for specific issues.

<3

**Comment by mdo** [comment]
Opened the pull request for this in https://github.com/twbs/bootstrap/pull/21389. Thanks everyone!
