### ISSUE TITLE
Can v3 icons be reused in v4 from a license point of view?

### ISSUE THREAD

**Issue by phax** [twbs/bootstrap#21383]
Bootstrap v3 contain the Glyphicons.
Does the license allow to reuse them in V4 or is it required to switch to the commercial license or another font pack?

Thanks!

**Comment by fchiumeo** [comment]
see this [link](http://v4-alpha.getbootstrap.com/migration/#components)

**Comment by phax** [comment]
Thanks, I know this link.
But I need clarification whether I can reuse the old ones (by extracting them from v3) or whether there are license issues when doing so.

**Comment by mdo** [comment]
Shouldn't be an issue, but please do not _redistribute_ them anywhere. Beyond that, there are significantly larger and better solutions out there than what we were providing in v3. By no means is that a reflection of the icon quality, but there are tons of icon options out there now that give you fonts, SVGs, sizing, etc :).

**Comment by phax** [comment]
You may want to add https://github.com/google/material-design-icons/ to the list at http://v4-alpha.getbootstrap.com/migration/#components
