### ISSUE TITLE
Unexpected CSS token warning in Safari

### ISSUE THREAD

**Issue by dominicgermain** [twbs/bootstrap#21386]
Using most recent version of Bootstrap

Getting lots of warnings in Safari

Just as a hint, font-awesome was suffering of that same issue until recently... They did exactly what I'm suggesting...

All lines starting with "filter:progid" should be rewritten with quotes :

```
filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1);
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1);
```

example :

```
filter: "progid:DXImageTransform.Microsoft.gradient(enabled = false);"
filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1);"
filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1);"
```
based on that : usablica/intro.js#537

**Comment by mdo** [comment]
I'm assuming this is from v3, so closing out as a won't fix. We're no longer actively developing v3 while work continues on v4.
