### ISSUE TITLE
Popover doesn't appear on hover sometimes

### ISSUE THREAD

**Issue by dimka665** [twbs/bootstrap#21385]
Popover doesn't appear on hover sometimes.
http://jsfiddle.net/0oyj0emd/2/

If we draw mouse slowly from right side then popover doesn't appear sometimes.
It works good if we cancel this CSS rule: `#container {text-align: center}`

Windows 10, Chrome 55, Bootstrap 3.3.7

**Comment by wolfy1339** [comment]
V3 is currently not supported anymore. Can you replicate against v4

**Comment by DavisMiculis** [comment]
Cannot replicate this using Windows 10, Chrome 55

**Comment by mdo** [comment]
We're no longer actively developing v3, so closing as a won't fix.
