### ISSUE TITLE
Scroll Anchoring affects .collapse elements.

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#21384]
We need to look at how [Scroll Anchoring](https://www.chromestatus.com/feature/5700102471548928) is going to affect us, specifically on `.collapse` elements that collapse upwards. In Chrome 56, if you are one pixel off the top of the page when you activate the toggle, the scroll position is locked and you can not see the expanded `.collapse` without scrolling up.

Example: https://v4-alpha.getbootstrap.com/examples/album/

**Comment by hnrch02** [comment]
Maybe a JS solution would help here? I'd imagine applying `overflow-anchor: none` to the `documentElement` while we're toggling a collapsable could work.

Are there any other examples as bad as this one? Because if not maybe we just need to think about changing the example.

**Comment by MartijnCuppens** [comment]
Imo, the current behaviour looks ok. Trying to change the scroll position introduces new issues:
- what if the expanded element doesn't fit on the screen?
  - We scroll to the top of the expanded element? in this case the focused button is out of the viewport.
  - What do we do when the element is collapsing/expanding, should we scroll the page while doing this? What if the user scrolls when doing this?
