### ISSUE TITLE
Add search bar button in Doc.

### ISSUE THREAD

**Issue by jsroyal** [twbs/bootstrap#21382]
- Operating system and version (Ubuntu 15.04)
- Browser and version (Chrome)

When suggesting a feature, include:

-Why it's important to Bootstrap?
  I need to only particular class details eg. form-control etc.

![image](https://cloud.githubusercontent.com/assets/10773353/21384463/b3b1d99e-c790-11e6-8fe0-5d18b820743d.png)

**Comment by bardiharborow** [comment]
Support for v3 has ceased. v4 has a search bar and improvements to it are being discussed over at #21125.
