### ISSUE TITLE
Npm install does not pulls all files when theme is added as dependency

### ISSUE THREAD

**Issue by aatifhussain** [twbs/bootstrap#21381]
Hi, We have forked bootstrap theme and we have added this theme in a **React Project** as a dependency. When to run _npm install_ in the react project it does not pull all the theme css files, always skips a few files

**Comment by lovezhuliang** [comment]
**Discuss**

**Comment by mdo** [comment]
Unsure what Bootstrap theme you're talking about—if it's the official ones from themes.getbootstrap.com, please contact our support team via email. There's no theme in Bootstrap itself, so closing out.
