### ISSUE TITLE
Is intentional to have the main .sccs instead of the main .css in the main files section in the bower.json?

### ISSUE THREAD

**Issue by dvmuccillo** [twbs/bootstrap#21380]
Hello!
Is intentional to have the "scss/bootstrap.scss" instead of the "dist/css/bootstrap.css" (or the .min) in the "main" option in bower.json?
If it is not, although small, is a correction welcome?

Edit: in the v4 version!

**Comment by mdo** [comment]
It is intentional, yes. Bower's packaging specs look for source files, not compiled assets. If you need the compiled assets, pull it in with another method.

**Comment by dvmuccillo** [comment]
Ok, thsnk you!
