### ISSUE TITLE
Waiting is painful！

### ISSUE THREAD

**Issue by newyhj** [twbs/bootstrap#21396]
从alpha1到alpha6.已经超过一年了，非常希望尽快发布正式版本。备受煎熬。。

**Comment by IamManchanda** [comment]
i don't understand Chinese but i can understand your feeling but hey 

" **There is a sweet fruit at the destination of every journey.** " 
" **सब्र का फल मीठा होता हे**  "

**Comment by bardiharborow** [comment]
Bootstrap is a volunteer-run project, and as such we can't provide timelines as to when v4 will be completed. You can help by jumping in and helping out.
