### ISSUE TITLE
Responsive Utilities page opens both Layout and Utilities in docs

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#21408]
When going to the [Responsive Utilities](http://v4-alpha.getbootstrap.com/layout/responsive-utilities/)-page both the Layout and Utilities categories in the navigation are opened.

Sorry if this was already reported, didn't see it in the tracker yet.

**Comment by Starsam80** [comment]
Fixed by #21288.
Also see #21252

**Comment by Studio384** [comment]
Ha, my apologies.

**Comment by Starsam80** [comment]
Haha, don't worry, I've pointed way too many duplicates or stuff that were already fixed in the past that people seem to have missed: #21310, #20482, #20680, #20720, #21011, https://github.com/twbs/bootstrap/issues/18001#issuecomment-263782177, #21275, #21289.
