### ISSUE TITLE
getbootstrap.com mixed content

### ISSUE THREAD

**Issue by OmgImAlexis** [twbs/bootstrap#21411]
Carbonads is currently setup to use http for all requests instead of https meaning there's a mixed content warning shown on getbootstrap.com

I've already checked and they serve the https version of all the files currently being served over http.

**Comment by bardiharborow** [comment]
This is already fixed in v4 (4a63dc6). @mdo, do we care about this enough to backport to v4?

**Comment by mdo** [comment]
Hmm, I thought I updated the hosted docs to the new ads code. 🤔 

For stuff like this, I think I'm okay to update the docs. I'd hate to have folks feel it's not usable for some reason because of console warnings like this.

**Comment by bardiharborow** [comment]
@mdo, you did update the hosted docs, but the v4 ones, not v3.

**Comment by hnrch02** [comment]
@mdo You porting back 4a63dc6 or should we do the easy fix for v3 and just update the script URL to be HTTPS?

**Comment by mdo** [comment]
Punting on this.
