### ISSUE TITLE
Dropping IE9 support or other older browsers

### ISSUE THREAD

**Issue by pattonwebz** [twbs/bootstrap#21416]
Recent days have shown that maintainers and some developers are in favour of dropping IE9 (and maybe even IE10). Can we please reopen that discussion? I don't think that this decision can be explored fully in the space of 24-48 hours, especially when it's the week before Xmas and many people are not around to weigh in with their opinion.

This issue and PR are both under 48 hours old and both are locked without allowing everyone who is following V4 development the time and opportunity to say what they think.

https://github.com/twbs/bootstrap/issues/21387
https://github.com/twbs/bootstrap/pull/21389

If anyone has an opinion to share, or any data to support their decision, please share so that the decision to drop support can be explored fully to reach the best outcome for developers and end-users.

Thanks in advance for any input you have :)

**Comment by browner12** [comment]
i don't think there's any real interest in dropping support for IE10. The only reason IE9 was targeted was because of flexbox support.  And I think the decision has been made already. A lot of the excess IE9 code has been removed, and we're going all in on flexbox. Basically the answer is if you need support for <=IE9, use BS3.

**Comment by pattonwebz** [comment]
@browner12 yeah it appears that the decision has been made and already a PR is ready that drops most of the support (with the rest forthcoming in the next few days). Personally I also want IE9 to stop being used but people do continue to use it. Stats vary greatly among different user groups and geographical location and the current window of discussion between maintainers and developers hasn't been open long enough to get a proper overview of that situation.

**Comment by myorangeca** [comment]
@browner12  I second your opinion. We closed it too quick and it was not discussed in detail. It looks as if we are skipping the work just to push the release. :\

**Comment by mdo** [comment]
I was unaware my PR to make this change was locked, apologies for that and thanks for opening a new issue to continue discussion.

While the decision was made _publicly_ in a day or two, I've spent the last several weeks (months?) exploring and debating the move to drop IE9 alongside the IE8 drop. I was already convinced of the change before asking on Twitter or opening that PR, but I figured asking couldn't hurt. I think I saw maybe a handful of negative reactions.

At this point, however, I'm sticking with IE10+. I'm incredibly excited to be building a leaner and more forward-thinking v4 with this change (if the number of PRs didn't already show that :P). Bootstrap 3 is now the go-to version for folks who require IE9 (or IE8) support.

Please continue bringing up potential issues, though. I'll happily take inventory of bugs, grievances, and the like so that after v4 is finalized, I can swing back to v3 and make some quality updates there, too.

**Comment by browner12** [comment]
sorry, to be clear, I am **for** this change.

**Comment by pattonwebz** [comment]
Hey, @mdo, appreciate you coming by and giving some insights into your thoughts on the move. I realize that prior to public discussion A LOT of different thoughts about this move would have been considered internally. Also I'm happy to hear just how excited you are about the move: a happy dev is a productive dev in my opinion :) Hoping that'll be a huge boost for the momentum towards launch.

My thoughts that even a small percentages of users still on old browsers amounts to a significant figure is the main concern for me with the move - especially since at this point IE10+ is the way it's going. Perhaps you could answer a question or 2 that might help ease my concern? 

Since the current stance is that anyone requiring IE9 support should make use of v3, what is the stance on continued support for it following the v4 launch? I'm relieved to hear you'll circle back round and make some updates to v3 in the future based on any issues that users bring up. Do you think that some of those updates could possibly be backports of new ideas brought from v4, or is it that v3 will be in somewhat of a feature freeze?

**Comment by mdo** [comment]
> Since the current stance is that anyone requiring IE9 support should make use of v3, what is the stance on continued support for it following the v4 launch? You say that you'll circle back round and make some updates to v3 if people continue to bring up issues etc. Do you think that some of those updates could possibly be backports of new ideas brought from v4, or is it that v3 will be in somewhat of a feature freeze?

Not looking to add major features back to v3. There's little that I would add there that's supported in all those browsers (IE8+ being the main one). Docs updates, bug fixes, and the like would be included there. Not on any regular schedule, but as important bits arise and we have time to fix them, I'll try to patch them.

**Comment by bardiharborow** [comment]
It appears no one has mentioned the possibility of adding support for IE9 back with a polyfill. I have not tried this approach out yet, but [flexibility.js](https://github.com/jonathantneal/flexibility) looks promising. More information about possible polyfills is available on the [Modernizr wiki](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills).

**Comment by tkrotoff** [comment]
> At this point, however, I'm sticking with IE10+

IE10 stats for oct-nov 2016:
- 3% according to [NetMarketShare](https://cloud.githubusercontent.com/assets/643434/21471531/5722dd76-cab6-11e6-8584-54adb782f73c.png)
- 0.53% according to [StatCounter](http://gs.statcounter.com/#desktop-browser_version_partially_combined-ww-monthly-201610-201611-bar)
- 0.46% according to [Wikimedia stats](https://cloud.githubusercontent.com/assets/643434/21471530/546f7594-cab6-11e6-8a8a-8098b098cdfb.png)

So always less than IE8 (=> 6.64% NMS, 0.85% SC, 0.59% W)

By the time v4 is final, it will be even lower. Also v4 lifetime will probably be ~4 years (v3 was released in 2013-08), will IE10 still be relevant in 2018-2020?
=> I believe this is a total waste of time supporting IE10 (even if it requires a small amount of work)

**Comment by alextarkhov** [comment]
IE10 and jQuery must be dropped in v4.

**Comment by Herst** [comment]
It might also be worth noting that IE10 is not supported by Microsoft anymore on any supported OS other than Windows Server 2012 (no R2) and Windows Embedded 8 Standard, i.e. no desktop OS, see: https://support.microsoft.com/help/17454 (1. Point)

The same will apply to Vista after the 11 April 2017 as all support for this OS will end.

(No idea about Windows Phone though.)

**Comment by alextarkhov** [comment]
IE10 and jQuery must be dropped in v4.

**Comment by Starsam80** [comment]
@alextarkhov I don't know if it was intentional, but don't delete your comment and post the same thing again. It causes unnecessary noise for people who use email notifications.

![image](https://cloud.githubusercontent.com/assets/4411333/21472820/7dd60312-caa7-11e6-8f0d-d4c7161d35e2.png)

**Comment by mdo** [comment]
We're not dropping IE10, and we're not dropping jQuery at this time (that's also not what this thread is about). Supporting IE10 hasn't been an issue for us at all whereas IE9 was the lone browser holding us back from flexbox, which solves a tonnnnn of issues for us.

**Comment by Studio384** [comment]
@mdo Can we expect the list of supported browsers to stay the same throughout the whole Bootstrap 4.x-cycle?

**Comment by mdo** [comment]
Yes, as dropping browsers means a breaking change.

**Comment by IamManchanda** [comment]
@bardiharborow but flexibility is not a active community to rely on i guess 
+ version 2 is not working of the same

**Comment by mdo** [comment]
Closing this out now. Please keep the feedback coming in (it'll help inform our next release) if y'all have any to share. <3

**Comment by tkrotoff** [comment]
IE10 stats for june 2017:
- StatCounter: [0.18% (desktop + mobile)](https://user-images.githubusercontent.com/643434/27758541-e46f8f0a-5e16-11e7-8272-74d3f2b5b308.png) and [0.42% (desktop only)](http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201706-201706-bar)
- NetMarketShare: [0.79% (desktop only)](https://user-images.githubusercontent.com/643434/27760641-b6e23a66-5e4c-11e7-910f-1d0dd93b7500.png)
