### ISSUE TITLE
Compiling SCSS via command line

### ISSUE THREAD

**Issue by bartoszhernas** [twbs/bootstrap#21417]
Hi,

for my build process I am using `django-compressor`, which let me define compilers for different extensions.

I am trying to compile bootstrap v4 scss'es via:

    /usr/lib/node_modules/node-sass/bin/node-sass {infile} {outfile} && \
    /usr/lib/node_modules/postcss-cli/bin/postcss --use autoprefixer \
    --autoprefixer.browsers "Android 2.3,Android >= 4,Chrome >= 20,Firefox >= 24,Explorer >= 8,iOS >= 6,Opera >= 12,Safari >= 6" {outfile} -o {outfile}

But when I am using these styles, then whole page looks different than using ones from CDN.

Any ideas what am I missing?

**Comment by wolfy1339** [comment]
What version/revision are you compiling?

**Comment by bartoszhernas** [comment]
The latest one

**Comment by bardiharborow** [comment]
We use `node-sass --output-style expanded --source-map --precision 6 scss/bootstrap.scss dist/css/bootstrap.css` to compile our SCSS. You'll need to provide more information as to what "looks different", preferably screenshots and a copy of the CSS being generated.

**Comment by bartoszhernas** [comment]
Ok, so trying to compile v4 beta5:

```  
{% compress css %}
    <link rel="stylesheet" type="text/scss" href="{% static 'bower_components/bootstrap/scss/bootstrap-flex.scss' %}">
{% endcompress %}
```


It goes through this command:

```
  COMPRESS_PRECOMPILERS = (
      ('text/scss',
       '/usr/lib/node_modules/node-sass/bin/node-sass --output-style expanded --precision 6 {infile} {outfile}'),
  )
```


Tools are installed via Docker:

```
RUN npm install -g node-sass bower postcss-cli autoprefixer
```

The resulting CSS:
[a2d50978e671.css.zip](https://github.com/twbs/bootstrap/files/672910/a2d50978e671.css.zip)


The website when including bootstrap css via CDN:
![screencapture-127-0-0-1-8078-en-1482751619009](https://cloud.githubusercontent.com/assets/1025587/21481319/ba438346-cb66-11e6-9cdf-659c5f907a9a.png)

Exactly same website after removing Bootstrap css CDN:
![screencapture-127-0-0-1-8078-en-1482751654079](https://cloud.githubusercontent.com/assets/1025587/21481328/c6ccbca4-cb66-11e6-8ca3-edd0c9fe7fc3.png)

**Comment by bartoszhernas** [comment]
I see that my compiler cannot compile inline-svg's properly:

```

.has-danger .form-control-danger {
    background-image: url('data:image/svg+xml;charset=utf8,%3Csvg xmlns=' http://www.w3.org/2000/svg ' fill=' #d9534f ' viewBox=' -2 -2 7 7 '%3E%3Cpath stroke=' %23d9534f ' d=' M0 0l3 3m0-3L0 3 '/%3E%3Ccircle r=' .5 '/%3E%3Ccircle cx=' 3 ' r=' .5 '/%3E%3Ccircle cy=' 3 ' r=' .5 '/%3E%3Ccircle cx=' 3 ' cy=' 3 ' r=' .5 '/%3E%3C/svg%3E')
}
```

**Comment by patrickhlauke** [comment]
just to check, you absolutely sure you using the latest version of the files from the repo? those `#` should be encoded to `%23`, and it should be double quotes for `url("...")`

**Comment by bartoszhernas** [comment]
I am sure, just got latest bower package and it looks fine in .scss from bootstrap:

```
$form-icon-danger: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='#{$form-icon-danger-color}' viewBox='-2 -2 7 7'%3E%3Cpath stroke='%23d9534f' d='M0 0l3 3m0-3L0 3'/%3E%3Ccircle r='.5'/%3E%3Ccircle cx='3' r='.5'/%3E%3Ccircle cy='3' r='.5'/%3E%3Ccircle cx='3' cy='3' r='.5'/%3E%3C/svg%3E") !default;
```

I think I have old libsass installed, trying to use the newest one.

**Comment by bartoszhernas** [comment]
I fixed the issue in the end. The problem was django-compressor filter, that was destroying inline-svg's ( I guess v3 bootstrap did not use this?)

Thanks a lot!

```
#### COMPRESS ####
COMPRESS_CSS_FILTERS = [
    # 'compressor.filters.css_default.CssAbsoluteFilter', <- That is the problem
    'compressor.filters.cssmin.CSSMinFilter'
]
```

**Comment by patrickhlauke** [comment]
> I am sure, just got latest bower package

clearly that's not the latest code, as it doesn't include this https://github.com/twbs/bootstrap/pull/20962/files#diff-d8ee409a461718bfb6240710c8c73382R463
