### ISSUE TITLE
Responsive variation for no-gutters 

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21428]
( https://github.com/twbs/bootstrap/pull/21211 ) I feel that there should be a responsive variations for the same ? 

Example 

- .no-gutters
- .no-gutters-sm-up

**Special note:** I have never used such variation ~~and wont be surprised if this suggestion doesn't proceed ahead~~ but i found the similar thing in zurb so i want to know whether bootstrap should have these responsive variations or not

Source : http://foundation.zurb.com/sites/docs/grid.html#collapse-uncollapse-rows

**Comment by IamManchanda** [comment]
@mdo Still love you guys but passing on this and closing!

**Comment by surjithctly** [comment]
I just got a use case for this. 

I wanted to use no-gutters for mobile to save space (you know) but keep the space intact on larger screen.

So, Is it possible to keep this open? or Is it available now?

**Comment by vjmunhoz** [comment]
I have the same issue as @surjithctly , and I don't think this use case is unusual at all
