### ISSUE TITLE
Flip effect on hover for Bootstrap buttons

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21427]
Not a fan of duplicacy so, here below is my issue/suggestion 
https://github.com/zurb/foundation-sites/issues/9553 

Codepen for reference --> http://codepen.io/IamManchanda/pen/Pbvmxg

**Comment by mdo** [comment]
No plans for adding animations like this to buttons at this time. Definitely something that's more specialized I think. Might expand on our transitions and animations we have currently, but it's not a high enough priority for me now to commit to or anything.

**Comment by IamManchanda** [comment]
no issue @mdo
