### ISSUE TITLE
Docs: Grid examples are not updated as per flexbox

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21431]
Path --> **{{ site.baseurl }}/examples/grid/**

The above page only contains the basic grid functionality and it doesn't show the flexibility of flexbox grid system in the examples as displayed in **{{ site.baseurl }}/layout/grid/**
for eg : Auto-layout columns, Flexbox Alignment, Flex ordering

Yes flexbox is an advanced functionality instead of basic but i feel that flexbox grid system deserves an example page whether its the same one or new one created  !

**Comment by mdo** [comment]
I think these are adequately covered in the docs right now. I want to move away from having so many examples that are just repurposed docs snippets. Thanks for the suggestion though!
