### ISSUE TITLE
Docs: Coding Bug within docs

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21445]
Path --> /layout/grid/#how-it-works

Here is the bug 

![docs-bug](https://cloud.githubusercontent.com/assets/4970624/21505654/5856de24-cc8f-11e6-90ca-b1523b361188.png)

As per i see it , its doesn;t have to do anything with the framework but instead **docs.min.css** file with below styling
 
```
.bd-example-row-intro .container {
    padding: 1px; 
    border: 1px solid rgba(217,83,79,.5);
}

.bd-example-row-intro .row {
    padding: 1px;
    border: 1px solid rgba(2,117,216,.5);
}

```
If `padding: 1px;` is commented out, it will be back to the normal `15px` padding to left and right and will resolve the issue respectively

**Comment by IamManchanda** [comment]
@mdo Best Option would be to remove  the `bd-example-row-intro` class from the parent div of the container div . as removing it is just simply resolving the issue completely including those unneccesary border outlines.

**Comment by Starsam80** [comment]
I think this is intentional. If you actually take a look at the docs it mentions those outlines:
```markdown
- Containers (outlined in blue above) provide a means to center your site's contents. Use `.container` for fixed width or `.container-fluid` for full width.
- Rows (outlined in red above) are horizontal groups of columns that ensure your columns are lined up properly. We use the negative margin method on `.row` to ensure all your content is aligned properly down the left side.
```
I assume the `padding: 1px` is just to make it stand out a little bit more

**Comment by mdo** [comment]
Ah, yeah, I meant to come back to this. The borders aren't doing what I wanted them to to show how things overlap and make use of the negative margin. Going to remove it outright instead of fiddling with it for now. Thanks for reporting!
