### ISSUE TITLE
Docs: Dropdown's not toggling

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21454]
Path --> /components/dropdowns/#single-button-dropdowns

The Dropdowns with default button ( btn-secondary ) ones are not toggling ( closing )
Rest buttons are working fine for toggle functionality

![dropdown-show](https://cloud.githubusercontent.com/assets/4970624/21528625/e799d792-cd59-11e6-826e-07558aab6107.png)

**Comment by mdo** [comment]
This is intentional. I'll revisit and perhaps clarify in the docs copy or update the example.
