### ISSUE TITLE
Icon input status not show internet explorer 

### ISSUE THREAD

**Issue by guilhermepatriarca** [twbs/bootstrap#21452]
In internet explorer dont show status and give error **XML5602**
![boostrap 4](https://cloud.githubusercontent.com/assets/14976020/21525886/0a208ed8-cd18-11e6-9630-0df5a31a47d7.jpg)

**Comment by mdo** [comment]
We cannot help without a live example via JS Bin. Screenshots don't show us what the code is that's powering those components :). Please provide a reduced test case example and we can look into it.

**Comment by patrickhlauke** [comment]
Fixed already by https://github.com/twbs/bootstrap/pull/20962

**Comment by guilhermepatriarca** [comment]
Ty for the help i appreciate it.
