### ISSUE TITLE
Add component-specified variables

### ISSUE THREAD

**Issue by ftiasch** [twbs/bootstrap#21455]
For example, $navbar-height, as it's commonly written for fixed-top navbar:
`body { padding-top: $navbar-height + $spacer-y; }`

As `$navbar-height` actually equals to `$navbar-brand-height + 2 * ($navbar-padding-y + $navbar-brand-padding)` (plus $navbar-brand-height: $line-height-base * $font-size-lg, $navbar-brand-padding: .25rem), having such kind of variables can offer greate convenience.

**Comment by bardiharborow** [comment]
I think this might be indicative of a the bigger issue of how difficult it is to pad the body when a `.navbar-fixed-top` is present. Is there a way we could make this easier?

**Comment by mdo** [comment]
I'm avoiding setting height and width wherever possible, so having these variables isn't super helpful I think. They're just computed shorthands that won't ever get used by us in the core. I understand their use case, but don't see huge value in there for us.

> Is there a way we could make this easier?

Not really. Only thing you could do is a sibling selector if you wanted to add `margin-top` to something after a fixed navbar. And even then, that only works for one of our navbars. Anything with fixed comes with added work.

**Comment by mdo** [comment]
Closing out since I don't have any specific plans to add the example variable or others from this issue.
