### ISSUE TITLE
chrome autocomplete hide background image of has-success, has-warning, has-danger

### ISSUE THREAD

**Issue by Korigoth** [twbs/bootstrap#21463]
Using Chrome, if the user autocomplete an input with chrome feature the background become yellow and hide the background image from this css -> .has-success .form-control-success

How can we make the image appear over the autofill background-color ?

tried this hack but it still hide the background-image:
input:-webkit-autofill, textarea:-webkit-autofill, select:-webkit-autofill {
  -webkit-box-shadow: 0 0 0px 1000px white inset !important;
}

**Comment by mdo** [comment]
Please provide a JS Bin demo of the bug.

**Comment by Korigoth** [comment]
should be easy to check with this simple demo

https://jsbin.com/haxemuzile/edit?html,css,output  (on chrome)

**Comment by patrickhlauke** [comment]
it's default browser behavior (show custom autocomplete background instead of any author-defined background) that i don't think can (or should) be overridden. only solution would be to explicitly suppress the behavior with `autocomplete="off"` on the input, or to reengineer the validation image/background to in bootstrap to not be on the form control itself, but on a separate wrapper

**Comment by bkdotcom** [comment]
[Relevant Stackoverflow](http://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete)

**Comment by mdo** [comment]
Closing as a won't fix given @patrickhlauke's comment.

**Comment by Korigoth** [comment]
@bkdotcom  this doesn't fix the problem it hide the yellow background but it still hide the image from bootstrap4. 

Putting autocomplete to off is bad for a lot of situation where we want the autocomplete for UX.
So we cannot use the bootstrap 4 feature...

So there is useless CSS in bootstrap4 ... i though it would be better suited for cross-broswer, it seem's not,


Mobile first equal cross-browser in thoughts because the different device uses Safari, Chrome, Bing, ect ...
Bootstrap4 doesn't come with Mobile-First as they say.... google chrome is the most used broswer still in our days... and you fail at showing new feature that will not work for LOT of dev out there.

**Comment by xtrem14** [comment]
This work for me:

@-webkit-keyframes autofill-valid {
    to {
        /* Background image copied from: node_modules/bootstrap/dist/css/bootstrap.css selector: .was-validated .form-control:valid, .form-control.is-valid */
        background-image: ($form-feedback-icon-valid);
    }
}

@-webkit-keyframes autofill-invalid {
    to {
        /* Background image copied from: node_modules/bootstrap/dist/css/bootstrap.css selector: .was-validated .form-control:invalid, .form-control.is-invalid */
        background-image: ($form-feedback-icon-invalid);
    }
}

input.is-valid:-webkit-autofill {
    -webkit-animation-name: autofill-valid;
    -webkit-animation-fill-mode: both;
}

input.is-invalid:-webkit-autofill {
    -webkit-animation-name: autofill-invalid;
    -webkit-animation-fill-mode: both;
}

**Comment by fritzfr** [comment]
This webkit autofill animation trick doesn't seem to work anymore (April 2022, Chrome v100).
