### ISSUE TITLE
BS4 Alpha 5 Omissions

### ISSUE THREAD

**Issue by srvance** [twbs/bootstrap#21472]
I'm in the process of porting [ember-bootstrap](https://github.com/kaliber5/ember-bootstrap) to be [BS4-friendly](https://github.com/kaliber5/ember-bootstrap/pull/181). We would like to have it mutually compatible so we don't force everyone to move. In most cases, we've been able to successfully do that. There are two omissions that we would like to have filled in or documented in the migration doc.

1. The `icon-bar` style has been removed. It's easy to re-create, but I'm sure lots of people have used it.
1. Tabs have been removed. Comments in other issues seem to indicate that Navs with tab style should be used, which is a useful building block but doesn't address the pane switching. The migration guide refers to panels, but that's not what the tab panes are called, so I don't know if this is related or not.

**Comment by mdo** [comment]
The latest in `v4-dev` varies a decent amount from Alpha 5.

- There's a new icon for the `.navbar-toggler`, and an icon class within, `.navbar-toggler-icon`. See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L93-L134.
- Tabs have not been removed, nor their tabbable panes. See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_nav.scss#L108-L119.

**Comment by srvance** [comment]
How about stacked progress bars?

**Comment by mdo** [comment]
> How about stacked progress bars?

Progress bars will see a rewrite that will revert them to basically their v3 implementations. The `<progress>` element, which we use in v4-dev, is far too limiting (no animations, no stacking, no labels within). Expect a PR for that today.

> Is there any good way to version test which version you're in?

As in which version of v4? Alpha 5 is the latest published version, but v4-dev has no versioning other than the commits :). We're super close to the final alpha release though, then onto the betas.

**Comment by srvance** [comment]
Good to hear about progress bars. I was banging my head over them.

No, as in which version of bootstrap at compile or runtime. For example, I'd like to conditionally include my `icon-bar` replacement or conditionalize the use of `icon-bar` styled elements versus using `navbar-toggler-icon`.

I know I'm coming at this from a niche angle, that of a bootstrap addon or wrapper striving for compatibility with both versions, so I appreciate your patience.

**Comment by mdo** [comment]
You could scrap the code comment at the top of the compiled CSS file (or source `bootstrap.scss`)? It's always there unless you remove all `/* */` style comments at compilation.

**Comment by srvance** [comment]
Any chance of adding a variable that could be tested from v4 forward?

**Comment by mdo** [comment]
Progress rewrite landed in `v4-dev` with #21473.

No plans on a variable for the version in our Sass though I'm afraid. I try not to add variables that aren't immediately used by us somewhere.

**Comment by srvance** [comment]
Thanks on progress. Any idea when a new alpha release will be cut with it? Bower 1.8.0 has a bug that won't let me reference `v4-dev` directly and for various reasons downgrading is a rough option right now.

What do you think of having some sort of version or feature test mechanism available that would let dependent packages work more seamlessly across different bootstrap versions?

**Comment by mdo** [comment]
New alpha hopefully very soon.

> What do you think of having some sort of version or feature test mechanism available that would let dependent packages work more seamlessly across different bootstrap versions?

Sounds too good to be true 😜. What'd you have in mind?

**Comment by srvance** [comment]
The simplest would be to embed the major version in a SASS variable (e.g., `$bootstrap_version=4`) that could be used for compile-time conditionals. At least for the use cases I'm thinking, that would be sufficient. Put it in it's own `_version.scss` committing to a format and a build tool could easily test for the file's existence and parse it for external-to-SCSS decisions.

I don't have a use case for full-blown semver or more granular feature flags, so let's not go there gratuitously.

The two things I would consider using it for right now are conditionally defining an `icon-bar` class for BS4+ and globally adding `row` back into `form-group` for specific applications.

How does that sound?

**Comment by mdo** [comment]
Had a think about this and I don't see us moving forward with anything else beyond what we have today in the banner at the top of the import stack. That's present in all our build files and can theoretically be processed as needed.
