### ISSUE TITLE
getbootstrap.com: npm install instructions get mangled by CloudFlare

### ISSUE THREAD

**Issue by anowlcalledjosh** [twbs/bootstrap#21477]
If a visitor to the [Getting Started][] page has JavaScript disabled, the instructions for installing Bootstrap with npm are converted from `npm install bootstrap@3` to `npm install [email protected]`, with a link to https://getbootstrap.com/cdn-cgi/l/email-protection. Is it possible to disable this protection? I can't find any email addresses on the site that need protecting, so it seems more than a little pointless.

[Getting Started]: https://getbootstrap.com/getting-started/

**Comment by bardiharborow** [comment]
Ping @mdo for Cloudflare access. You'll need to turn Email Address Obfuscation off on [this page](https://www.cloudflare.com/a/content-protection/getbootstrap.com).

**Comment by mdo** [comment]
Just fixed it in Cloudflare. I imagine it might take a bit to propagate out and what not.
