### ISSUE TITLE
Tooltip is "Sticky" when clicking on nav-links

### ISSUE THREAD

**Issue by dmbuchta** [twbs/bootstrap#21486]
Clicking on a .nav-item with a tooltip causes the tooltip to continue to be displayed even after the mouseout event. The tooltip will only be dismissed when clicking elsewhere on the page.

    <li class="nav-item dropdown" data-toggle="tooltip" title="Notifications" data-placement="left">
        <a class="nav-link" href="#" data-toggle="dropdown">
            <i class="fa fa-bell-o" aria-hidden="true"></i>
        </a>
    </li>

**Comment by mdo** [comment]
Can you create a JS Bin example to demo the bug?

**Comment by dmbuchta** [comment]
I've never made a jsbin before, so I don't know if I'm doing something wrong but there seems to be a different error with tether in the provided example. 

You can however, see the bug I'm referring to the first time only. I have to refresh the page each time to reproduce it. That does **not** happen in my actual project. Hopefully that will make sense when you view it.

Here it is: https://jsbin.com/suyafed/edit?html,js,output

**Comment by mdo** [comment]
Feel like there's some funky stuff going on with JS Bin right now. This works fine locally with the docs tests. Looking at your code, you also have two `data-toggle`s on parent-child elements. That's likely the source of your problem in your code.

**Comment by hnrch02** [comment]
[This bin](https://jsbin.com/cazawa/edit?html,js,output) uses Tether 1.3.3. That removes the odd quirk you were describing.

Regarding your report: This is intended behavior. See [the `trigger` option for tooltips](https://v4-alpha.getbootstrap.com/components/tooltips/#options). Clicking on a link will give it focus, thus making the tooltip sticky. You can use `data-target="hover"` to remove the tooltip on mouse out, see [this bin](https://jsbin.com/bapapu/edit?html,output).

**Comment by dmbuchta** [comment]
Thanks for the help guys, explicitly setting the data-trigger attribute to 'hover' did the trick. My issue was occurring because of the focus event. That's my fault for not reading the docs better.

@hnrch02 can you edit your comment to `data-trigger` instead of `data-toggle`?
