### ISSUE TITLE
Javascript: Smooth Page Scrolling - Add a "smooth-scroll" class 

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21498]
This could be super useful for things like navbars
http://codepen.io/IamManchanda/pen/VPZMba

**Simple** "smooth-scroll" class on anchor tags 

Here is the simple javascript ( jquery ) code

```
$('a.smooth-scroll[href*="#"]:not([href="#"])').click(function() {
  if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
    var target = $(this.hash);
    target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
    if (target.length) {
      $('html, body').animate({
        scrollTop: target.offset().top
      }, 1000);
      return false;
    }
  }
}); 
```

Source: CSS Tricks 

**Update** : I am not looking for any plugin, only **simple** basic smooth scroll for basic landing page functionality specifically for navbars and **simple** anchor tags which will help to scroll the page smoothly.

**Comment by hnrch02** [comment]
I believe we have discussed this in the past and have settled on recommending other plugins for this. CC @mdo @cvrebert

**Comment by IamManchanda** [comment]
@hnrch02 oh i see, is there any issue with the code ?
I am asking this because why would you need a plugin if you can do a thing in a 10 liner code

**Comment by hnrch02** [comment]
I assumed you were suggesting that we add a plugin à la ScrollSpy or Tooltip for this functionality. Then we would need to write a lot more than 10 lines of code, since it would need extensive unit testing too 😄

**Comment by IamManchanda** [comment]
nah nah only basic smooth scroll ... basic landing page functionality specifically for navbars

For example: https://blackrockdigital.github.io/startbootstrap-scrolling-nav/

**Comment by mdo** [comment]
Passing on this.

**Comment by IamManchanda** [comment]
Any specific Reasons @mdo.. Simple code ... No plugins

**Comment by mdo** [comment]
I'm not a huge fan of hijacking or modifying scrolling, don't feel it's a useful application of our time, doesn't help solve any glaring issues with the framework, etc. I'd sooner see us *remove* or simplify things than add more to the core.

Just because we _can_ add something, doesn't mean we _should_.

**Comment by patrickhlauke** [comment]
Generally (depending on technique) messing with scrolling can also negatively impact things like hardware acceleration.

This is certainly something that would be more of a fit as a plugin/extension/addon, rather than core bootstrap.

**Comment by IamManchanda** [comment]
Ohk no issue @mdo sir @patrickhlauke sir

**Comment by IamManchanda** [comment]
But I have to say with most systems and mobile's being new and updated these days, I don't see  " that " much hardware acceleration issues 
@patrickhlauke

**Comment by IamManchanda** [comment]
@mdo @patrickhlauke it hurts me to say but the bootstrap team has ignored my **relevant** ideas

Relevant because this same feature, today morning i was able to integrate(merge) in an another framework succesfully and quite happily and sorry but bootstrap lacks behind when it comes to latest web .... specially javascript! 
Sorry for being a bit sour ....  didn't meant to!
