### ISSUE TITLE
Basic HTML includes with simple javascript library for bootstrap 4 

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21493]
For static sites, Surely the best use case for **html includes** is static site generators like jekyll or hugo.
I am not denying that but many static websites ( specially bootstrap ones ) dont want to use these static site generators simply because its complicated at first and thus use this type of below crutch

`document.write("<h1 class=\"task\">Task for the day<\/h1>");`

This type of code is meant for testing only and isn't for production but still websites use this type of codes because its easy to get started with. Infact there are many [html to js convertors](https://www.google.co.in/search?q=html+to+js+converter) for the same use case.

As per my best of knowledge and experience, this doc_write is mostly and widely used in navbars, sidebar, and footers of website which is surely not great!!

So i wanna purpose this simple below thing for `**bootstrap.js**`
http://www.w3schools.com/w3css/w3data_includes.asp

Demo => http://www.w3schools.com/w3css/tryit.asp?filename=tryw3data_html_include_2

Yup, maybe bootstrap is not meant for this type of stuff but what's better than saving the developer's and designer's day ??

**Comment by RamanCool** [comment]
+1 , Even i face this thing daily. Would be nice if this ads to bootstrap. Less Hacky then document write.

**Comment by hnrch02** [comment]
I don't think we need this in Bootstrap. Besides HTML imports and web components seem like a much safer bet for this. If I even understand the problem correctly? Could you describe a use case?

**Comment by IamManchanda** [comment]
Here is the use case, 

My Company where i work has 1000's of pages in their website, 
And we are using static html pages and dynamic java pages in between, its frankly imposible for us to use a static site generator
But our Navbar and footer remains the same throught the website ,

so we use JS File for both with doc_write statements in there. so that we dont have to make it repetitive

As we are using bootstrap, and if there is this **feature** in bootstrap, we dont need to use doc_write again, we can easily include the header.html and footer.html with a simple line of code. 

Yes i admit this is not the best use case but not every site uses things like angular, react, jekyll etc and feel that this will be the best case for the old school static pages.

Rest on you guys to decide @hnrch02

**Comment by hnrch02** [comment]
I see. That seems to be a solution to a very specific problem though with not many other possible applications. Besides this should probably be handled server-side with your templating engine not on the client.

So I'm fairly confident in saying that we're not going to add this, considering A) the required amount of work we would have to put in and the arguably small benefit it would provide to the vast majority of Bootstrap users and B) the better first party solutions provided by browsers with HTML imports and web components.

**Comment by IamManchanda** [comment]
no issue @hnrch02
