### ISSUE TITLE
CSS Drop Caps - Add a "dropcaps" class 

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21495]
Kinda basic but should be added to bootstrap core 
Demo => http://codepen.io/IamManchanda/pen/bgbraw

Here's the **SCSS** I used for the above example

```
.dropcaps:first-of-type:first-letter {
  height: 0.7em;
  margin: 0.07em 0 -0.05em 0;
  padding: 0 0.03em 0 0;
  font-size: 5em;
  line-height: 0.85em;
  float: left;
}
```
That tiny negative margin is for the next line (4th line in this case) to start from scratch after dropcap has finished its variable height!

**Comment by cquanu** [comment]
Neat!

**Comment by IamManchanda** [comment]
thanks @cquanu .... Yup neat like your [theme](https://github.com/cquanu/github-dark)

**Comment by mdo** [comment]
Thanks, but we'll pass on this for now. <3

**Comment by IamManchanda** [comment]
What happened @mdo .... I thought this would have been nice feature to add ? 
Simple dropcaps .... Not much code to add ?

**Comment by mdo** [comment]
I don't see this being a hugely request feature, and despite it's initial impressions of not much code to add, it's still something we've added to the project. Everything added dilutes the rest in some way and I'll continue to be rather particular in what we add here to keep things lean enough.
