### ISSUE TITLE
Feature Request: CSS3 Transitions, Animated Input Form on focus

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21497]
Dear , @mdo & team <3

Just wanna know are you accepting css transition's ticket requests ?
The reason i am asking this as IE9 is not supported for CSS3 Transitions and if i propose any CSS3 Transitions , will that proceed ahead to the bootstrap core ? 

**Update**: Oh sorry i got a bit confused with IE9 & IE10,,,, IE9 is already out #flexbox .... and CSS3 Transitions is supported in IE 10 ... 

So, here's my feature request as asked later in the comment 

Animated Input Form on focus
http://codepen.io/IamManchanda/pen/XpraGx

**Comment by hnrch02** [comment]
We have transitions in Bootstrap despite them not being supported in IE9. We also mention this [in our docs](https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#internet-explorer-9--10).

What type of transitions are we talking about here? Do you want to modify current ones or introduce new transitions? I'm slightly confused.

**Comment by IamManchanda** [comment]
some feature requests

For example, 
**Animated Input Form on focus** 
http://codepen.io/IamManchanda/pen/XpraGx

**Comment by hnrch02** [comment]
I see. Deferring to @mdo.

**Comment by IamManchanda** [comment]
No issue. Let mark decide on that, he will do whats best for the framework, 
For the time being i have updated my question and title ...

**Comment by mdo** [comment]
Yup, we'll pass on that.

@hnrch02 Welcome back! Missed you around these parts. 😻
