### ISSUE TITLE
Docs: Providing docs for opening a new modal and closing the current one 

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21499]
{{ **Bootstrap 4: Docs** }} , Path => /components/modal/ 
 
Please add documentation on opening an another modal and closing the current one when a link is clicked as its done without any extra code efforts, via 

`  <a href="#modal-2" data-toggle="modal" data-dismiss="modal">Next ></a>`

JS Fiddle: http://jsbin.com/hujipi/edit?html,output 

This is happening as i am calling both data toggle and data dismiss at the same time, so i felt it should be in the documentation too. As always, rest on you guys to decide :smile_cat:

**Comment by IamManchanda** [comment]
Awaiting reply @mdo

**Comment by molfar** [comment]
Such solution has a bug with modal-open body class. But it would be nice it working)

**Comment by IamManchanda** [comment]
Still love you guys but passing on this and closing!
