### ISSUE TITLE
Add Chips to Bootstrap 4

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21492]
Here's what i am referring to http://www.w3schools.com/howto/howto_css_contact_chips.asp

**Comment by mdo** [comment]
Thanks, but we'll pass on this for now. <3

**Comment by IamManchanda** [comment]
@mdo will hope that you come soon to this ! 
A Bit unhappy coz this would have been nice feature and currently used in other frameworks like materialize !!

**Comment by quintonn** [comment]
Chips can be created using badges: https://getbootstrap.com/docs/4.0/components/badge/
