### ISSUE TITLE
Jumbotron example not in sync with github source

### ISSUE THREAD

**Issue by aguibert** [twbs/bootstrap#21506]
After browsing the [Bootstrap download page](http://getbootstrap.com/getting-started/#download) I found the [jumbotron example](http://getbootstrap.com/examples/jumbotron/) and wanted to import it into my local application.

I went to [the github repository location for this example](https://github.com/twbs/bootstrap/tree/v4-dev/docs/examples/jumbotron) location and imported the `index.html` and `jumbotron.css` into my sample application.  However, what I imported did not look anything like the jumbotron example on the download page.

After some confusion, I downloaded [the entire bootstrap repo zip](https://github.com/twbs/bootstrap/archive/v3.3.7.zip) from the download page and found the correct html source for the "jumbotron" example in this zip.  It appears that at some point the nav-bar for [the carousel example](http://getbootstrap.com/examples/carousel/) got mixed up with the nav-bar in the jumbotron example.

Please update the github source so it is in sync with what is presented in the getbootstrap.com examples and the repo download linked on that site.

**Comment by wolfy1339** [comment]
You probably downloaded a copy from the v4 source. For the v3 source check out the master or v3-dev branches

**Comment by aguibert** [comment]
ah, thanks.  I hadn't realized what was in this repo was still under dev.

I'll close out this issue.
