### ISSUE TITLE
navbar-brand link add new line when the logo text contain space or long name in v4

### ISSUE THREAD

**Issue by pixieaka** [twbs/bootstrap#21504]

**Comment by imcodingideas** [comment]
@pixieaka can you please create a https://codepen.io with an example?

**Comment by mdo** [comment]
The issue template, autofilled in every new issue created, includes instructions for how to file a bug report. See https://github.com/twbs/bootstrap/blob/v4-dev/ISSUE_TEMPLATE.md and provide a reduced test case, details on Bootstrap version, and any relevant browser/OS details.

**Comment by pixieaka** [comment]
sorry the error from me
