### ISSUE TITLE
progress bar animation doesn't work with dev branch

### ISSUE THREAD

**Issue by robbisy** [twbs/bootstrap#21503]
The progress bar animation [jsfiddle](https://jsfiddle.net/audLoLb0/1/) didn't work anymore with the dev branch, there isn't animation anymore.

**Comment by mdo** [comment]
We only animate the striped gradient; if you need another animation (say for the width or something else), you'll need to write custom CSS for that.

**Comment by Johann-S** [comment]
Your JSBin show that you use Bootstrap 3.3.5 and the last release of Bootstrap 3 is 3.3.7 + we're no longer actively developing v3
