### ISSUE TITLE
Changing bs dropdown trigger to hover for desktop and click for mobile conflicts?

### ISSUE THREAD

**Issue by KhayyamNosrati** [twbs/bootstrap#21507]

**Comment by patrickhlauke** [comment]
And how would a keyboard user activate the dropdown on desktop?

**Comment by KhayyamNosrati** [comment]
Excuse me for that.. this was an issue I had in my project, and was searching to find a solution.. thank you for notifying me patrichlauke :-)

 I corrected the issue title!

**Comment by mdo** [comment]
I imagine if you used the JS API vs `data` API, you could write some JS to accomplish this (swap the trigger in JS, update the attributes with JS, use different triggers shown by media query, etc). Beyond that, doesn't sound like there's much for us to do here. Please correct me if I'm wrong, but otherwise closing out.

**Comment by KhayyamNosrati** [comment]
Obviously that would be they way! but if you look around in online markets themes or personal websites, those which are built on bootstrap didn't use bs collapse menu for mobile. They used other plugins or created a custom ones... Beyond that, its been asked alot on online programming communities by web designers...

Here is what happens when I have swapped the trigger...(while it slides to open) , have a look
![www](https://cloud.githubusercontent.com/assets/20792731/21597567/8f1a2be0-d172-11e6-9793-7d46d3833bbd.png)

 And here is when it slides to close
![www](https://cloud.githubusercontent.com/assets/20792731/21597580/c236f8b4-d172-11e6-9c87-26ae1d6c604e.png)

But thank you for you friendly reply
Have Good Day :-)

**Comment by KhayyamNosrati** [comment]
Obviously that would be they way! but if you look around in online markets themes or personal websites, those which are built on bootstrap didn't use bs collapse menu for mobile. They used other plugins or created a custom ones... Beyond that, its been asked alot on online programming communities by web designers...

Here is what happens when I have swapped the trigger...(while it slides to open) , have a look
![bbb](https://cloud.githubusercontent.com/assets/20792731/21597619/5ab8ebd8-d173-11e6-9131-47911c2b5990.png)


And here is when it slides to close
![bbb](https://cloud.githubusercontent.com/assets/20792731/21597614/4c9b838a-d173-11e6-8d57-7845855c3c0e.png)


But thank you for you friendly reply
Have Good Day :-)

**Comment by KhayyamNosrati** [comment]
Obviously that would be they way! but if you look around in online markets themes or personal websites, those which are built on bootstrap didn't use bs collapse menu for mobile. They used other plugins or created a custom ones... Beyond that, its been asked alot on online programming communities by web designers...

Here is what happens when I have swapped the trigger...(while it slides to open) , have a look
![www](https://cloud.githubusercontent.com/assets/20792731/21597628/7b8181f4-d173-11e6-9a16-b0c101f41fdb.png)


And here is when it slides to close
![bbb](https://cloud.githubusercontent.com/assets/20792731/21597629/81900408-d173-11e6-97c3-b751c383d4e0.png)


But thank you for you friendly reply
Have Good Day :-)

**Comment by KhayyamNosrati** [comment]
Obviously that would be they way! but if you look around in online markets
themes or personal websites, those which are built on bootstrap didn't use
bs collapse menu for mobile. They used other plugins or created a custom
ones... Beyond that, its been asked alot on online programming communities
by web designers...

Here is what happens when I have swapped the trigger...(while it slides to
open) , have a look
[image: www]
<https://cloud.githubusercontent.com/assets/20792731/21597567/8f1a2be0-d172-11e6-9793-7d46d3833bbd.png>

And here is when it slides to close
[image: Inline image 1]

But thank you for you friendly reply
Have Good Day :-)
