### ISSUE TITLE
ios safarie drowpdown bug js css

### ISSUE THREAD

**Issue by darkiron** [twbs/bootstrap#21518]
in 3.3.7 dropdown doesn't work. use double tap only !

**Comment by DavisMiculis** [comment]
Are you using MacBook trackpad to tap on dropdown?

**Comment by hnrch02** [comment]
It works just fine for me in the v3 docs on iOS 10.2. Make sure no other JavaScript is interfering and the markup you use is correct. If the issue persists, feel free to reopen with additional details on your iOS version and a reduced test-case on JS Bin.
