### ISSUE TITLE
Add .dropdown-menu-center?

### ISSUE THREAD

**Issue by 0wczar** [twbs/bootstrap#21510]
I wonder, why has no connection `btn-block` with `dropdown`. 
I wanted such a solution several times used **as a substitute for select**.

So I would **have three options** for the dropdown:
![btn-block-with-dropdown](https://cloud.githubusercontent.com/assets/2330394/21587068/73646b9e-d0d8-11e6-8425-99bdcfadc128.png)

**Comment by mdo** [comment]
Dropdown menus can be right aligned with the existing modifier class. We could add another for a middle/center alignment, but unsure how that plays into Popper.

/cc @johann-s for ideas.

**Comment by Johann-S** [comment]
By default Dropdown are left align and if you want a right align you can add this class `.dropdown-menu-right` to your Dropdown menu.
About to have a center position yes we can add this feature, Popper allow this placement too

**Comment by drolean** [comment]
the class .dropdown-menu-right dont exist

**Comment by Johann-S** [comment]
Present here : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L58 and here : https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L163

**Comment by drolean** [comment]
`.navbar-expand-sm .navbar-nav .dropdown-menu-right` on my css only exist inside in `.navbar` class

**Comment by Johann-S** [comment]
Yes but you can add this class (`.dropdown-menu-right`) to your dropdown menu and align it to the right 👍

**Comment by mdo** [comment]
Closing for consolidated issue: #22962.

**Comment by drolean** [comment]
dropdown-menu-right or left work only inside a navbar?
