### ISSUE TITLE
List groups - heading and text on same line in custom content example

### ISSUE THREAD

**Issue by Quy** [twbs/bootstrap#21516]
At a certain point and higher, the heading and text are displayed on the same line.
![listgroup](https://cloud.githubusercontent.com/assets/368084/21597935/b13307ee-d107-11e6-9807-a164ce0a7af4.jpg)

**Comment by isank** [comment]
1. Issue comes up on resolution 980x1280 and above.
2. Problem seems to be related to `padding-right` value of `.list-group-item`

**Comment by isank** [comment]
1. Changing the property `display: flex` to `display: block` for `.list-group-item` solves this on v4.

**Comment by mdo** [comment]
Unfortunately the only way to handle this, and other flexbox layout options, is to customize even further with utility classes. Otherwise we cannot vertically center and space things like badges. Docs update for this coming in #21526.
