### ISSUE TITLE
bootstrap v3.3.5 DOM with [data-toggle='collapse'] cannot be toggled with class 'collapsed' properly [chrome 55.0.2883.87 ]

### ISSUE THREAD

**Issue by zhou9197** [twbs/bootstrap#21528]
- As is shown in https://jsfiddle.net/zhou9197/vs7x127p/
1. when set one data-target to button1, class `collapsed` **CAN BE** toggled to button1
2. when set two data-targets to button2, class `collapsed` **CAN NOT BE** toggled to button2

- Is there any methods or workaround to fix it?

**Comment by mdo** [comment]
Closing because v3. Moreover, I don't believe we support, in v3 or v4, multiple targets from the same toggle.
