### ISSUE TITLE
Broke Tabs with tables

### ISSUE THREAD

**Issue by imcodingideas** [twbs/bootstrap#21527]
When I put div tab-content inside of a table, the tabs no longer work. I reproduced it from my application to a codepen.

- Browser and version Chrome: 55.0.2883.95
- Test case: http://codepen.io/imcodingideas/pen/oBNMqw?editors=1000

The issue is between line 26-> 58

**Comment by neilhem** [comment]
Hi, do not put div inside table, put table inside tab content

**Comment by imcodingideas** [comment]
So for my layout that's how it needs to happen. On top I have the tabs and the tr's are the tabbed content.

![screen shot 2017-01-03 at 9 53 52 pm](https://cloud.githubusercontent.com/assets/5374985/21632044/540b7c42-d1ff-11e6-8557-1e8d3aef10b8.png)

**Comment by neilhem** [comment]
You can't put div inside `table` tag, so you should change your layout
