### ISSUE TITLE
Doc: Incorrect breakpoint?

### ISSUE THREAD

**Issue by discoveryjames** [twbs/bootstrap#21522]
Since the breakpoint was changed on the grid system, should these values not be updated?

https://v4-alpha.getbootstrap.com/layout/overview/

**Comment by Starsam80** [comment]
They are already updated in `v4-dev`: #21204

**Comment by discoveryjames** [comment]
Ah, sorry my bad.

**Comment by mdo** [comment]
Docs only get redeployed when there's a release :).
