### ISSUE TITLE
.col-xs-n missing now?

### ISSUE THREAD

**Issue by phawley** [twbs/bootstrap#21532]
Hello,

I am compiling the bootstrap-grid.scss from the v4-dev branch for a project, and noticed that there are no rule-sets generated for .col-xs-n. My hunch is that since it is mobile first CSS (AISB), the **xs** is superfluous in favor of simply saying .col-n and then overriding that at an _actual_ breakpoint (e.g. .col-lg-).

I was not able to find any info stating such, but did find the issue from mid 2016 in which you were trying to clean (and DRY out) the .col-__-n classes, so perhaps this is a relic or product of that effort.

Thanks!

**Comment by fchiumeo** [comment]
> #21059, #21086, #21222: Remove -xs from the extra small grid class names (but keep the sm, md, lg, and xl for the others). 

(from #20939)

**Comment by phawley** [comment]
Perfect, thanks!
