### ISSUE TITLE
Chrome in flex mode col-* affect table column width wrong

### ISSUE THREAD

**Issue by andyyou** [twbs/bootstrap#21547]
Is this a `Not recommended` way or a bug I am not quite sure but case description as follow:

In bootstrap 3, I usually use `col-{size}-*` to adjust width of table column let's say I want some column always get more widely. Like [Example](https://jsbin.com/qezelukipe/edit?html,output) & [Codepen](http://codepen.io/andyyou/pen/xgbLNz)

In bootstrap 4 alpha.5 that `enable flex` ability case, when I do the same thing.  [Flexbox example](https://jsbin.com/vecenugida/edit?html,output)

* Firefox v50.1 is work fine and same behavior.

![](http://i.imgur.com/RPXIMXg.png)

* But Chrome v55.0.2883.95

![](http://i.imgur.com/jNjW2dV.png)

For this case I just modify `col-{size}-*`'s css property that `max-width` to `width` can work quite fine, But I am not sure this is a good way to do or cause other problem. 

![](http://i.imgur.com/4pXVD5p.png)

**Comment by mdo** [comment]
You'll need to do further modification if you wish to use these (now) flex styles with tables. I don't advise that overall though as it adds a ton of overrides to undo the table styles. I'd would recommend creating new styles as needed for specifying column widths in tables.

**Comment by stanleyxu2005** [comment]
I met [the same problem](https://stackoverflow.com/questions/39131128/how-to-specify-responsive-column-width-for-table-in-bootstrap-v4). So table with responsive column width is no longer supported in Bootstrap 4?

**Comment by SrAxi** [comment]
Has this issue been addressed? Or we still have to override BS's classes with our own in order to set columns width? Thanks! :D
