### ISSUE TITLE
Can I use Bootstrap v4 Carousel as a module with browserify/webpack?

### ISSUE THREAD

**Issue by gkatsanos** [twbs/bootstrap#21548]
I'm reading at the Installation readme:

> You can manually load Bootstrap’s jQuery plugins individually by loading the /js/*.js files under the package’s top-level directory.

I don't really get that part. I tried several combinations, amongst which:

`import carousel from 'bootstrap/js/src/carousel.js'`

but nothing really works. 

Can I use the Bootstrap v4 Carousel without having the rest of the Bootstrap modules with browserify/webpack? - or do I have to manually add it in my codebase?

(and if I can't, how do I build it - the customizer is gone -) cc @fat

**Comment by petetnt** [comment]
I have proposed an idea in #19017, which would allow for proper module usage of any Bootstrap components.

**Comment by gkatsanos** [comment]
@petetnt I hope a solution will be found.

**Comment by Johann-S** [comment]
We have in our documentation an how to use Bootstrap with Webpack which explain that see : https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/webpack.md
