### ISSUE TITLE
Docs : Dead Link - Slack 

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21549]
Path => /getting-started/best-practices/ 

Ask in Slack redirects to https://bootstrap-slack.herokuapp.com/ which is a dead link

**Comment by Starsam80** [comment]
https://bootstrap-slack.herokuapp.com/ is working perfectly fine for me: 
![image](https://cloud.githubusercontent.com/assets/4411333/21696365/fd2d0f56-d34a-11e6-9328-c31252447b1b.png)

**Comment by mdo** [comment]
Works for me.

**Comment by IamManchanda** [comment]
Now works for me too .... So maybe it was a one off ..... Site issues etc
