### ISSUE TITLE
Docs: Dead Link within sidenav

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21550]
Utilities => Sizing and Positioning redirects to 
this path` /utilities/sizing-and-positioning/`

which is a dead link

**Comment by Starsam80** [comment]
Are you using the latest `v4-dev`? I don't see that link:
![image](https://cloud.githubusercontent.com/assets/4411333/21696507/9b360414-d34b-11e6-8384-28d6878042dd.png)
The `alpha.5` still has a working link too: https://v4-alpha.getbootstrap.com/utilities/sizing-and-positioning/

**Comment by mdo** [comment]
Yeah, I nuked that in `v4-dev`. Split those two pages up. Nav and everything should be up to date.
