### ISSUE TITLE
Documentation on show.bs.tab event 

### ISSUE THREAD

**Issue by didiergm** [twbs/bootstrap#21557]
The documentation should include that returning false from that event effectively cancels the action and that the current tab is not changed.

**Comment by Johann-S** [comment]
It seems more a jQuery behavior than Bootstrap, see : http://api.jquery.com/on/#event-handler

> Returning false from an event handler will automatically call event.stopPropagation() and event.preventDefault().

**Comment by bardiharborow** [comment]
It's a browser behavior as far as I can recall, but we may still wish to document it clearer.

**Comment by Johann-S** [comment]
But it's the same behaviour for all Bootstrap's plugins ⁣​

**Comment by didiergm** [comment]
@Johann-s unless it escaped me, this is documented nowhere in BS, making it clear would save a bit of time to many developpers, for the sake of a one liner I believe it is worth it.
