### ISSUE TITLE
If a container-fluid follows a container, in a small screen columns of first overlay columns of the second

### ISSUE THREAD

**Issue by realtebo** [twbs/bootstrap#21553]
See this plnker:  http://run.plnkr.co/plunks/voFU7jJk5aW08zOhLYbQ/ [Link updated]

```
    <div class="container conBorder">
        <div class="row">
            <div class="col-md-6 conBorder">Column 1</div>
            <div class="col-md-6 conBorder">Column 2</div>
        </div>
    </div>

    <div class="container-fluid conBorder">
        <div class="row">
            <div class="col-md-6 conBorder">Column 1</div>
            <div class="col-md-6 conBorder">Column 2</div>
        </div>
    </div>
```

With this code, if you shrink the window, you'll see that "Column  2" of first div will stay on top of the second div.

**note**: even if I have the fluid as first and the normal as second, the problem happens anyway.

**Comment by mdo** [comment]
Your link doesn't work for me, can you double check it?

**Comment by realtebo** [comment]
Sorry: I recreated the plnkr: http://run.plnkr.co/plunks/voFU7jJk5aW08zOhLYbQ/

**Comment by realtebo** [comment]
I discovered just now that the problem is related to my custom css class `conBorder`, styled as:

```
    <style>
        .conBorder {
            border: 1px solid #888888;    
            height: 200px;
        }  
    </style>
```

Removing `height : 200px;` definition, all works, but I think it's a issue anyway

**Comment by mdo** [comment]
Since this was an issue with custom styles, closing out as a won't fix.
