### ISSUE TITLE
Nav tabs are not working anymore on the boostrap site or my site.

### ISSUE THREAD

**Issue by ayordy67** [twbs/bootstrap#21555]
I am using bootstrap nav tabs on my dev site. Today they stopped working. Click on a tab and nothing happens. I went to the bootstrap site and the same thing. None of the examples worked.
I am not using the cdn to load the bootstrap files on my site either. Tried on Edge latest and Chrome latest.

**Comment by bardiharborow** [comment]
Tabs work correctly for me in [v3](https://getbootstrap.com/javascript/#tabs), [v4](https://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior), and on `v4-dev`. Please ensure you have Javascript enabled. I'm going to close this until I hear more. If you continute to have problems, please read [the contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/CONTRIBUTING.md) and provide a reduced test case, and details about the browser you are expreiencing this on ("chrome latest" is not detailed enough, as Chrome has stable, beta and dev channels).
