### ISSUE TITLE
Bootstrap modal closes when dragging on the backdrop into the modal

### ISSUE THREAD

**Issue by CodeDeFury** [twbs/bootstrap#21563]
Thanks for the great work guys ! Just a small issue to report here.

Steps to reproduce the problem:
1. Go to http://v4-alpha.getbootstrap.com/components/modal/#live-demo
2. Click on the Launch Demo Modal button
3. Mousedown on the backdrop and mousemove into the modal and release the mouse
4. The modal is closed

In my opinion, the expected behavior is the modal should stays open. 😄 

OS Version: OS X 10.12.2
Chrome version: 55.0.2883.95

Also happens on IE 11 and Edge, but not Firefox and Safari.

**Comment by judetucker** [comment]
I think this behavior is expected. Clicking on the modal backdrop should close the modal and is very common behavior across frameworks.

**Comment by Johann-S** [comment]
If you want to change this behavior just change the `backdrop` option see : http://v4-alpha.getbootstrap.com/components/modal/#options

Closed because this behavior is expected
