### ISSUE TITLE
mouse cursor on active item of tabs and pills 

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#21560]
When I mouse over the active item of tabs and pills, I noticed that the mouse cursor is different. 

Tabs: cursor: pointer
Pills: cursor: default

I would like to know why are cursors different between pills and tabs. Thanks.

you can see the behavior: http://v4-alpha.getbootstrap.com/components/navs/#tabs

**Comment by bardiharborow** [comment]
Confirmed. Relevant code is [scss/_nav.scss#L83](https://github.com/twbs/bootstrap/blob/a9d899b1154cdb382ec291dcd29ac50e995e6484/scss/_nav.scss#L83).
