### ISSUE TITLE
Tooltip, popover, modal JS error in hosted docs

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21570]
```
TypeError: e(".tooltip-demo").tooltip is not a function. (In 'e(".tooltip-demo").tooltip({selector:'[data-toggle="tooltip"]',container:"body"})', 'e(".tooltip-demo").tooltip' is undefined)
```

Not present in development...

**Comment by Starsam80** [comment]
Looks like we aren't importing all of the JS needed. Can you try rebuilding the docs on a clean checkout from git? Here is what the currently hosted docs have for scripts: 
![image](https://cloud.githubusercontent.com/assets/4411333/21728597/45039b74-d404-11e6-8856-609199b14e4c.png)
And this is my locally built one:
![image](https://cloud.githubusercontent.com/assets/4411333/21728578/2df0cd44-d404-11e6-8c0f-0b5fd1e1ea10.png)

**Comment by mdo** [comment]
All the JS is in that `docs.min.js` bundle. For now I'm going to push a change to the docs to not use that version until I can figure out what's up with the concatenated and minified bundle.

**Comment by vanduynslagerp** [comment]
Surprisingly enough everything works fine for me here: https://v4-alpha.getbootstrap.com/components/popovers/

**Comment by mdo** [comment]
I pushed up an update to use the non-minified JS right after my earlier comment. It works now, but I still need to look into why the minimized didn't.

**Comment by bardiharborow** [comment]
I'm betting #21414 caused this.
