### ISSUE TITLE
Supporting other types of Navbar's

### ISSUE THREAD

**Issue by medj** [twbs/bootstrap#21576]
It's somewhat of an "issue" to me that the Navbar doesn't support slide in effects for extra small screens. When I click the nav toggler button, instead of it expanding downward, I would like to see a full height menu slide from the left to the right, perhaps taking up 80% of the screen. I use this effect in all of my projects and constantly have to code this in on top of Bootstrap, but I thought it would be neat if this were baked into it instead.
Example: http://bootsnipp.com/snippets/featured/navbar-lateral-slide-menu

Would be cool if there was support to slide in from all directions, the height and width of the slide in, etc.

**Comment by mdo** [comment]
Dupe of #17496.
