### ISSUE TITLE
Alerts (components) : show class not found

### ISSUE THREAD

**Issue by jluisgarcia** [twbs/bootstrap#21582]
I am testing the documentation sample from:

https://v4-alpha.getbootstrap.com/components/alerts/#dismissing
and it does not work.

Also,  my editor cannot find .show class, which is used in the example.

**Comment by mdo** [comment]
There's no specific CSS for the `.show` class on `.alert`s. And the example works for me.

**Comment by Johann-S** [comment]
The example works for me too.
``.show`` is used here : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/alert.js#L111
But it seems a bit useless, I only found one occurence in alert.js
