### ISSUE TITLE
Inputs and buttons use base sans-serif font, not native font stack

### ISSUE THREAD

**Issue by bgentry** [twbs/bootstrap#21588]
Repro: check out the [forms documentation page](http://v4-alpha.getbootstrap.com/components/forms/) for v4 alpha. Inspect one of the input elements. Observe that it is using a base `sans-serif`, *not* the native font stack:

<img width="1051" alt="screen shot 2017-01-06 at 5 10 53 pm" src="https://cloud.githubusercontent.com/assets/114033/21737937/37d2df8a-d433-11e6-9b3a-7aee2e98bdae.png">

Presumably these should get the same base font as all the other elements on the page? I'm guessing there are probably also some other styles that are not being applied to inputs or maybe other elements too.

Cheers :beers:

#### Environment

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
  - macOS
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
  - Chrome Version 55.0.2883.95 (64-bit)

**Comment by bgentry** [comment]
As mentioned in #21629, the underlying cause of this seems to be https://github.com/necolas/normalize.css/issues/642

**Comment by ccbetts** [comment]
This is the rule (specifically line 257) that appears to be causing the problem...

           // _normalize.scss
    
    252    button,
    253    input,
    254    optgroup,
    255    select,
    256    textarea {
    257      font-family: sans-serif; // 1
    258      font-size: 100%; // 1
    259      line-height: 1.15; // 1
    260      margin: 0; // 2
    261    }

Perhaps the `font_family` ought to be overridden within **_reboot.scss**?
