### ISSUE TITLE
Alpha 6 ignoring _custom.scss

### ISSUE THREAD

**Issue by bluesurfer** [twbs/bootstrap#21583]
I am trying to customize Bootstrap by editing `_custom.scss` like this:
```
$blue: red !default
```
But, when compiling with `grunt dist-css`, the new version seem to ignore `_custom.scss` - nothing changes. On the other hand editing directly `_variables.scss` works. Am I missing something new or is this an actual bug?

**Comment by maimairel** [comment]
This is caused by #21442 I also have the same issue

**Comment by mdo** [comment]
Drop the `!default`. https://jsbin.com/ficofo/edit?html,css,output

**Comment by maimairel** [comment]
@mdo Yes, I don't have the `!default` on the custom values. What I don't understand is while `$grid-breakpoints` and `$container-max-widths` do work the other custom values are ignored.

**Comment by szastupov** [comment]
I can confirm the issue, here is my _custom.scss:

```
$brand-primary:             #f0941c;
$brand-inverse:             #0f6be3;
$brand-danger:              #e15325;
$body-color:                #505455;
```

and all those variables are ignored.

The reasons is that values from _variables.scss are used in mixins *before* including _custom.scss.

Here is your modified example to demo the behaviour: https://jsbin.com/qutoniseci/edit?html,css,output
