### ISSUE TITLE
Revisit stacked and inline form layout options

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21581]
Folks often want to mix the standard form group and inline form options in the same form. I'll build some example layouts out and see what we can do to help.

**Comment by dmxt** [comment]
Based on https://news.ycombinator.com/item?id=13339739

**Comment by Olivia101** [comment]
This looks like a great example [http://forms.viewflow.io/demo/bank/](url) referenced in the Hacker News article above

**Comment by srvance** [comment]
While I like the ability to control the spacing for inline forms, the defaults are distinctly lacking. When you revisit this, can you make inline layout have sensible, aesthetic defaults that can be overridden when desired?

**Comment by mdo** [comment]
I've been playing around with ideas and have been struggling to find anything more helpful and flexible than the grid system provided by Bootstrap. I still haven't gotten to the default spacing and alignment options in the inline forms, but that's a straightforward enough fix I think.

Thoughts from folks on something like this for the sizing of multiple inputs per row though? https://jsbin.com/zaloye/edit?html,output
