### ISSUE TITLE
[Design] Inverse navbar search bar

### ISSUE THREAD

**Issue by dmxt** [twbs/bootstrap#21586]
_This change suggestion is purely for developers or site maker who don't write CSS much and don't change the Bootstrap style on their site, we'd like to make it look as good as possible when we come across the "default bootstrap site"._

I think the search field would look much better if it's dark gray background instead of white on inverse navbar. Not as strict HEX, but as low opacity white via SASS/SCSS, just in case background CSS is changed to dark gray instead of black. Perhaps we could make it outline, like one with outline button. 

Beside making it look better, would we run into any issues?

---

Inverse navbar (black background) navbar image for reference:
![image](https://cloud.githubusercontent.com/assets/3248782/21737545/d9af9a28-d447-11e6-8856-1f4bbe3a4d0c.png)
Image source: http://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

**Comment by LarryAzevedo** [comment]
@dmxt You can do it by just adding a few classes.  Let's take the dark navbar example found on https://getbootstrap.com/docs/4.0/components/navbar/#color-schemes.  You would just add `bg-dark text-white border-secondary` to the input.  @mdo Perhaps we could use that solution on that page?
`<input class="form-control mr-sm-2 bg-dark text-white border-secondary" type="text" placeholder="Search" aria-label="Search">`

Hope that helps.

**Comment by ronanharris09** [comment]
what about using a class that will reverse the foreground color into background and vice versa ? We can keep the contrast between the two color consistent.

**Comment by dmxt** [comment]
@LarryAzevedo My main suggestion was intended for the default theme for the form in the inverse navbar. Obviously, I can do it myself with CSS if not implemented.

**Comment by mdo** [comment]
I think I'm going to say we won't implementing this one. If we add it for one input type, we have to add it for all inputs—and that's a lot of form styles to override.
