### ISSUE TITLE
Pause on the Carousel dont work in Google Chrome

### ISSUE THREAD

**Issue by 1letter** [twbs/bootstrap#21599]
OS: Windows 10
Browser: Google Chrome Version 55.0.2883.87m

Problem: Pause on the Carousel dont work

The Chrome Browser on my **Desktop** don't stop the Slide when i hover the Mouse over the Carousel. The [check](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L232) of `!('ontouchstart' in document.documentElement)` evaluate to `True ` and the Mouseenter and Mouseleave Event is not registered. I think another check is needed.

**Comment by patrickhlauke** [comment]
yes, checking for `ontouchstart` is bound to give false positives (or rather, it doesn't test what some authors expect) and will only get more muddy in the near future https://bugs.chromium.org/p/chromium/issues/detail?id=392584

also, this doesn't seem to take into account scenarios where there are BOTH a mouse and a touchscreen. in short, this code (and any other instances of conditionals depending on `ontouchstart` being present, e.g. in https://github.com/twbs/bootstrap/blob/65ffb1c3b6e94440812a2e228cb8e8be512652ec/js/src/dropdown.js#L98) will need to be rethought. /cc @mdo

**Comment by Johann-S** [comment]
For me pause (on hover) Carousel work, see this CodePen (BS 4 Alpha 6) : http://codepen.io/Johann-S/pen/oBedMZ
But we should follow what @patrickhlauke said

**Comment by xsalto-camille** [comment]
+1 not working with Chrome workaround found at #1048 
```javascript
$('.carousel').hover(function () { 
  $(this).carousel('pause') 
}, function () { 
  $(this).carousel('cycle') 
})
```

**Comment by Johann-S** [comment]
I checked once again my CodePen and everything is working

This is my version of Chrome : 56.0.2924.87 (64-bit)

**Comment by xsalto-camille** [comment]
My version is 56.0.2924.87 (64-bit) too !

I work on Windows 10 with an hybrid PC (Lenovo Yoga) connected to an external screen...

**Comment by KevinHotaling** [comment]
+1 noworky on Window 10, Chrome 56.0.2924.87, touchscreen Samsung ATIV.  Fixed with xsalto-camille's jQuery workaround. Thanks.

**Comment by gijsbotje** [comment]
so is this a touch issues or also a mouse hover issue?
i'm on a macbook pro with macos 10.12.5 and chrome 59.0.3071.115 and the mouse hover seems to work, in the inspector the touch>hold kind of hover is also working

**Comment by patrickhlauke** [comment]
Should all be fixed by https://github.com/twbs/bootstrap/pull/22442
