### ISSUE TITLE
Modal has stopped working

### ISSUE THREAD

**Issue by karolisgrinkevicius** [twbs/bootstrap#21596]
Modal window has stopped working in new alpha release. Seems the issue is because of opacity problems with .fade .in classes. But not entirely sure. 
http://plnkr.co/edit/?p=preview
https://github.com/ng-bootstrap/ng-bootstrap/issues/1191 

- Mac OS X
- Chrome
- angular 2.2.1
- bootstrap 4.0.0-alpha.6
- ng-bootstrap 1.0.0-alpha.16

**Comment by Quy** [comment]
`.in` has  been renamed to `.show`.

From the Alpha 6 ship list:
```
Renamed some .active, all .in, and all .open classes for our JavaScript powered components for more consistent naming. For example, instead it's now .collapse.show instead of .collapse.in and .show > .dropdown-menu instead of .open > .dropdown-menu to better communicate the visibility of elements.
```

**Comment by karolisgrinkevicius** [comment]
@Quy thanks!
