### ISSUE TITLE
$font-family-sans-serif and $font-family-base are ignored?

### ISSUE THREAD

**Issue by gthomas-appfolio** [twbs/bootstrap#21595]
When customizing alpha.6 via _custom.scss, if I set values for `$font-family-sans-serif` and `$font-family-base`:

    $font-family-base: sans-serif !default;
    $font-family-sans-serif: sans-serif !default;

this is set for `html`, but seems to be ignored for `body`, `.popover`, and `.tooltip`, in the built css.  Instead the font-family for these is the default `$font-family-sans-serif` from _variables.scss:

    font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;

This used to work in previous alphas.  Anything I'm missing above?

**Comment by Jas-n** [comment]
Same here, looks like it's related to the moving of the @import "custom"; line in scss/bootstrap.scss (Commit: https://github.com/twbs/bootstrap/commit/44825032370e37f7cec410356e4a1b1cd9999307).

I tried changing it back and the custom variables work again.

**Comment by gthomas-appfolio** [comment]
Ah thanks for noticing, I'll temporarily use this as workaround

**Comment by mdo** [comment]
Closing since #21603 was merged.
