### ISSUE TITLE
[v4 css feature] Giving more attention to footers

### ISSUE THREAD

**Issue by sejr** [twbs/bootstrap#21601]
**Footers** are commonly used for more elaborate navigation, copyright information, maps, and more. An example of an awesome footer is available on the [**official Google Developers website**](https://developers.google.com/):

![](http://i.imgur.com/YY7KJsS.png)

Considering the substantial amount of pages on this site, the footer navigation is super helpful for users who have not previously visited. It is also a refreshing alternative to the `navbar` we see all over the web now (and typically associate with Bootstrap).

That said, I think we should consider giving the `<footer>` element a little attention, especially with the V4 release coming up. Some key ideas:

1. `footer.footer-bottom`, which would push the footer element and its content to the bottom of the page. Currently, the only bottom-positioned element is a `.navbar` with the `.fixed-bottom` class. However, this utilizes fixed positioning and isn't really ideal (especially with large footer navs such as the one on the Google Developer website). Example usage `<footer class="footer-bottom">Copyright 2017 Bootstrap</footer>`
2. `footer ul.footer-nav`, or even more abstractly, something like `.nav-vertical` which could display navigation elements like an non-styled list with a little extra padding. The headers (`li.nav-vertical-header`) could have a heavier font.

I may expand on this later, but I'd be interested in seeing what others think.

**Comment by mdo** [comment]
I don't think this is something we need to solve for. These things are often one-offs and quite easily created with few custom styles and utilities. Thanks for the suggestion though!
