### ISSUE TITLE
V4 Alpha 6: Popover errors when using `hover` trigger

### ISSUE THREAD

**Issue by JD-Robbs** [twbs/bootstrap#21600]
When "quickly" hovering over a list of Popovers (trigger = `hover`), the introduction of the `isAnimating` check is causing quite a few errors.

Here's a reproduction: https://jsfiddle.net/kzhszdpa/

Simply hover quickly (i.e. move the cursor fast) from the topmost button down and then up again and check the console output.

- Operating system and version: Windows 10
- Browser and version: Chrome v55

Similar issues appear with regards to Modal and when interactions are "too fast" (for lack of a better description) - albeit I have not found a way to re-produce this in a simple fiddle.

**Edit**: see #21607 for an issue that may be related.

**Comment by ghiscoding** [comment]
As described in [issue #21607](https://github.com/twbs/bootstrap/issues/21607), my comments were the following:

> I can reproduce it on the [Tooltip Doc](https://v4-alpha.getbootstrap.com/components/tooltips/) page. It takes a few hover over to get the errors to show up in the console, I usually can see them appearing after 15-20 times of doing hover over the Toolips. I can reproduce in both Chrome and Firefox.
> 
> Created a JSFiddle account and tried [forking](https://jsfiddle.net/Lnckrj3y/6/) with unminified `bootstrap.js` code to know which line throws the error and this is what came up (as a reminder, this is after 15-20 times of doing hover over):
> ```javascript
> Uncaught Error: Tooltip is transitioning
>     at Tooltip.show (bootstrap.js:2946)
>     at Tooltip._enter (bootstrap.js:3187)
>     at HTMLButtonElement.<anonymous> (bootstrap.js:3134)
>     at HTMLButtonElement.handle (jquery-3.1.1.min.js:3)
>     at HTMLButtonElement.dispatch (jquery-3.1.1.min.js:3)
>     at HTMLButtonElement.q.handle (jquery-3.1.1.min.js:3)
> ```
> Try the [JSFiddle](https://jsfiddle.net/Lnckrj3y/6/), hope it works for you

@Johann-S replied to this error with the following

> It's due to this PR : #17823
> 
> My PR #21613 wont fix what you report

**Comment by vanduynslagerp** [comment]
Ref #21727

**Comment by Johann-S** [comment]
Closed due to the merge of : https://github.com/twbs/bootstrap/pull/21743
