### ISSUE TITLE
Alpha 6 Navbar Align Right example

### ISSUE THREAD

**Issue by mrjlynch** [twbs/bootstrap#21602]
Alpha 6 navbar is now using flexbox:

> Navbars are built with flexbox! Instead of floats, you’ll need flexbox and margin utilities.

The [navbar documentation](https://v4-alpha.getbootstrap.com/components/navbar/) and examples provided [here](https://v4-alpha.getbootstrap.com/examples/navbars/) are good, however they do not provide an example for a navbar aligned right. 

The only way I have been able to achieve this to date is as follows: 

```html
<div class="mr-auto"></div>
<ul class="navbar-nav">
  ...
</ul>
```

Perhaps we should create an example?

**Comment by mdo** [comment]
Not sure we need a separate demo for this; you want `justify-content: flex-end;`, or `.justify-content-end`. See https://jsbin.com/kemawa/edit?output. Open to revisiting if more folks struggle with this though.

**Comment by smutek** [comment]
> Open to revisiting if more folks struggle with this though.

@mdo, your example worked great until I wrapped the contents of `nav` in a `.container`, now below 575px the toggle and the nav items center and overlap. 


Documentation with examples wouldn't hurt.

**Comment by asadsahi** [comment]
@mdo how do we put some nav items in your example to the left? It looks like you are wrapping in one div to make it flex. Does that mean we have to have two flex divs for each nav group to appear on right and left. Trying to get the right markup. Examples on the webiste with right-left nav items don't work anymore.

**Comment by asadsahi** [comment]
Finally what worked for me https://jsbin.com/wibosoz/1/edit?html,output:

**Comment by KerryRuddock** [comment]
The 4.0.6 navbar documentation for aligning right is horribly misleading and shows using justify-content-end class in the <ul> but this does not work.  justify-content-end is to be placed on the parent wrapper div.

incorrect:
`<ul class="nav justify-content-end">`

correct: 
```
<div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
  <ul class="navbar-nav">
```
