### ISSUE TITLE
v4: <a> & <button> .dropdown-item have different font families

### ISSUE THREAD

**Issue by puzrin** [twbs/bootstrap#21614]
If you use `<a class="dropdown-item">` and `<button class="dropdown-item">` in the same menu, it's well seen that text dencity is different. Dev tools shows that items have different font faces.

**Comment by mdo** [comment]
Dupe of #21588.

**Comment by puzrin** [comment]
Is it possible, that user configures different font for buttons? Does it worth to override it in .dropdown-item for safety?
