### ISSUE TITLE
SyntaxError: missing = in const declaration

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#21618]
In latest firefox in file util.js.

**Comment by calandraz** [comment]
Do you perhaps have a screen shot of this missing =?

**Comment by rorc** [comment]
This error on 57 line in util.js

`for (const name in TransitionEndEvent) {`

**Comment by vanduynslagerp** [comment]
`for (const name in TransitionEndEvent)` is a valid es6 for-in loop : http://exploringjs.com/es6/ch_variables.html#_for-of-loop-and-for-in-loop

I'm not sure what you mean by "In latest firefox in file util.js."

Your website should import the compiled and minified version: https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.min.js and not the individual js source files.
This is the file you should "see in Firefox" (I imagine you mean in the Firefox dev tools?)

**Comment by calandraz** [comment]
@vanduynslagerp thanks for getting to this...I was just now looking over the files he specified and couldn't see what he was talking about.

**Comment by rorc** [comment]
@vanduynslagerp Yes, valid, but not for firefox :(
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const
Scroll down to header Firefox-specific notes.

**Comment by vanduynslagerp** [comment]
> @vanduynslagerp Yes, valid, but not for firefox :(
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const
Scroll down to header Firefox-specific notes.

Again:
> Your website should import the transpiled version: https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.min.js and not the individual js source files.

Bootstrap v4 is writing in es6 (that is not supported natively by every browser) and it is compiled in es5 (compatible with every browser).

**You have to use the transpiled version: https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.min.js.**
**Or if you want to include the plugins individualy, you should include the transpiled versions that you can find here: https://github.com/twbs/bootstrap/tree/v4-dev/js/dist**

Firefox will never see this file https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js

Firefox should see either https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.min.js or https://github.com/twbs/bootstrap/blob/v4-dev/js/dist/util.js if you decide to include the modules individually.
You can notice that those 2 files are transpiled in es5 and do not contains the keyword `const`.

You can find more details here: https://v4-alpha.getbootstrap.com/getting-started/javascript/

**Comment by rorc** [comment]
@vanduynslagerp Ok, ty 😄
