### ISSUE TITLE
Navbars with a Container in it does not work proper at xs-grid (<576px) v4

### ISSUE THREAD

**Issue by josmaissan** [twbs/bootstrap#21612]
`.navbars` with `.container` in it does not work proper at xs-grid (<576px) 
(also your own side http://v4-alpha.getbootstrap.com/ 
and de second exampel at http://v4-alpha.getbootstrap.com/examples/navbars/)

- Operating system Windows, Mac OS X
- Browser and version Most desctop versions

**Comment by svenluijten** [comment]
Possible duplicate of #21605.

**Comment by josmaissan** [comment]
@svenluijten Your right!

**Comment by josmaissan** [comment]
@svenluijten Your right!

**Comment by yxbh** [comment]
I don't think this is a duplicate because although it may be related the OP in #21605 is describing a different issue. He's since [clarified](https://github.com/twbs/bootstrap/issues/21605#issuecomment-271182852) what he's trying to resolve.

**Comment by josmaissan** [comment]
@yxbh Your right. 
This one should be reopend

**Comment by svenluijten** [comment]
You're right, it's a duplicate of #21590 then 😉

**Comment by josmaissan** [comment]
@svenluijten Think now your right
this one of @sejr described same problem!
Reclose this one.
