### ISSUE TITLE
Turn on Common Ligatures and Kerning

### ISSUE THREAD

**Issue by RehanSaeed** [twbs/bootstrap#21623]
Feature request to turn on Common Ligatures and Kerning where open type fonts support the feature. [This](http://thenewcode.com/547/Make-Your-Web-Pages-More-Legible-With-Ligatures-and-Kerning-Pairs) article describes both features in more detail.

```
body {
    font-kerning: normal;
    font-variant-ligatures: common-ligatures;
}
```

Am willing to submit a PR if suggestion is welcomed.

**Comment by bardiharborow** [comment]
Browsers already do a fairly good job of this. The defaults for these two properties are:

- [`font-kerning: auto;`](https://developer.mozilla.org/en/docs/Web/CSS/font-kerning) which defers to the browser regarding whether to use kerning. When the font size is small, font kerning may look strange and browsers will disable it.
-  [`font-variant-ligatures: normal;`](https://developer.mozilla.org/en/docs/Web/CSS/font-variant-ligatures) which activates `common-ligatures` and `contextual` already.

**Comment by RehanSaeed** [comment]
@bardiharborow Very intersting. A lot of blog posts will lead you to believe the opposite. Is that true of all browsers or just Firefox as indicated by your links?

**Comment by mdo** [comment]
@RehanSaeed Read through those MDN docs and you'll see the Browser Compatibility tables—looks like there's decent enough support.
