### ISSUE TITLE
<a> button :focus styles not overridden correctly.

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#21625]
On any desktop browser, do the following:

1. Go to http://v4-alpha.getbootstrap.com/components/popovers/#dismiss-on-next-click
2. Click on the red _Dismissible popover_ button to bring up the popover.
3. Finally, move your cursor off of the button.

The text of the button changes to blue; which in my opinion, looks and feels a little weird.

**Comment by vanduynslagerp** [comment]
ref #21539
