### ISSUE TITLE
Bootstrap image spacing problem

### ISSUE THREAD

**Issue by soniapello** [twbs/bootstrap#21632]
I use bootstrap v4 alpha 6 and I trying to have images with opacity and font awesome icon on them. It works great until I resize it on medium screen. At that point I get some spacing between my images
<img width="467" alt="stack" src="https://cloud.githubusercontent.com/assets/20027271/21792813/adc1473e-d6ec-11e6-8537-16692efd9e6c.png">
Here is a codepen [link](http://codepen.io/anon/pen/jybdBW)
The only I find out to solve this is to add width:100% to img-fluid
So I wonder why not add it by default in bootstrap ?

**Comment by mdo** [comment]
`.img-fluid` ensures images don't break out of their parent, not that they are sized *upward* to their parent element. That's not the behavior we're after, but there is also an issue open at #20830 to explore adding some class for this down the line.
