### ISSUE TITLE
4.6 cols break when row within row

### ISSUE THREAD

**Issue by mike192020** [twbs/bootstrap#21631]
So I have noticed that when using the flex box col version (ie class="col") that if you put a columns in a row that is in another row it completely breaks the even spacing.

example: http://codepen.io/itisnot_me/pen/ygYwoj (shows cols within one row and double row)

when using the normal route ie: col-xs-3 and the cols are in a row that is in a row it seems to work fine and doesnt care.

--------------------------
On a side note if you dont put class="col" within there own class="row" they dont even try to work. not sure if this a bug also. previous versions didnt seem to care about rows

**Comment by mdo** [comment]
For nesting, rows don't go within rows, they go within columns. Example: http://codepen.io/anon/pen/VPvNgy

**Comment by mike192020** [comment]
When this comes to public use its going to break alot of sites. Especially the now forced rows. I see that alot of people do not use rows and alot of templates have double rows. The transition to flex box, while awesome, lacks old code support.
