### ISSUE TITLE
Navbar left/right sections

### ISSUE THREAD

**Issue by Alfaspider** [twbs/bootstrap#21649]
After upgrading from alpha 4 to alpha 6. Right aligned navbar items don't work anymome. Docs don't cover this scenario except for navbar text.

**Comment by Alfaspider** [comment]
Figured it out. You need two nav elements in navbar, left is mr-auto aligned and the second one without. Example:
http://www.codeply.com/go/P0G393rzfm

**Comment by Olivia101** [comment]
@Alfaspider have a look at this [https://github.com/twbs/bootstrap/issues/21602](url)
