### ISSUE TITLE
Card images distorted

### ISSUE THREAD

**Issue by membla** [twbs/bootstrap#21650]
Seems like the Flexbox card implementation in alpha6 has produced some unwanted effects for card images – distortion occurs regardless if using .img-fluid for the .card-img-top or not. I know it has been discussed before but if the default behaviour of .card-img-top means distortion of the image I'd say .img-fluid should be applied to card images by default.

(OS X 10.12.1 Chrome 55.0.2883.95)

http://codepen.io/membla/pen/WRrvqG

**Comment by mdo** [comment]
Fix coming in #22288
