### ISSUE TITLE
Buttons and input elements not inheriting $font-family-base

### ISSUE THREAD

**Issue by dohayon** [twbs/bootstrap#21652]
It seems like normalize is overriding the body with font-family: sans-serif, instead of reboot's setting of $font-family-base

**Comment by vanduynslagerp** [comment]
I think it's a duplicate of #21595

**Comment by maimairel** [comment]
`_reboot.scss`

``// Normalize includes `font: inherit;`, so `font-family`. `font-size`, etc are
// properly inherited. However, `line-height` isn't inherited there.``

But normalize doesn't inherit the font anymore.

**Comment by mdo** [comment]
Dupe of #21588.
