### ISSUE TITLE
<input type="date"> inside .input-group renders incorrectly in Chrome.

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#21651]
Bootstrap 4 alpha6 on Chrome 55 on Windows.
Renders properly in Firefox and Edge.

## Test case
https://jsbin.com/pomicuyiza/1/edit?html,output

## Screenshot
![image](https://cloud.githubusercontent.com/assets/10222521/21811257/572f3bac-d74f-11e6-8974-5be22ae46120.png)

**Comment by bardiharborow** [comment]
Please check your testcase. It doesn't contain an input group or a submit button as per the screenshot, which leads me to believe you've posted the wrong code. Per [this](http://stackoverflow.com/q/21263515/1414639) StackOverflow question, support for `<input type="datetime">` has been removed from most browsers, so the element renders the same as any other textbox (confirmed in Chrome 56). `<input type="datetime-local">`, however, is supported by Chrome and displays correctly.

**Comment by vanillajonathan** [comment]
Sorry, that test case somehow got wrong. To clarify I am referring to type `date`, not `datetime` or `datetime-local`.

## Test case
https://jsbin.com/pomicuyiza/1/edit?html,output

**Comment by bardiharborow** [comment]
Yep, okay. Confirmed on Chrome 56.

**Comment by jasonswearingen** [comment]
The issue also exists with ```datetime-local```

please see this testcase: https://jsbin.com/kihosoviyu/1/edit?html,output
running chrome on windows.

**Comment by sudhirj** [comment]
Fix is to change `.input-group .form-control` to `flex-direction: row;`. It's currently `column`, which I think makes the elements _inside_ the date text box layout vertically.

**Comment by sudhirj** [comment]
Actually, will be fixed when #21716 lands.
