### ISSUE TITLE
Reboot does not assign "font-size: 16px;" to html in alpha 6

### ISSUE THREAD

**Issue by DonaldShaw** [twbs/bootstrap#21667]
Reboot does not assign "font-size: 16px;" to html in alpha 6 was fine in alpha 5

Windows 10 and MacOS
Chrome and Safari

I performed a search for all cases of ' html' in bootstrap.css. No assignments to font-size found

I investigated because many headings and anchor tags had suspiciously large font size.

**Comment by rafalp** [comment]
Take a look there: https://github.com/twbs/bootstrap/pull/21524

**Comment by DonaldShaw** [comment]
Hi Rafal,

Thanks for the info that the font-size declaration is now do-it-yourself


I should point out however, that the V4 docs still read 

A base font-size: 16px is declared on the <html> and font-size: 1rem on the <body> for easy responsive type-scaling via media queries.

Donald

**Comment by rafalp** [comment]
Then this looks like bug in docs ;)

**Comment by vanduynslagerp** [comment]
Ref #21567

**Comment by bardiharborow** [comment]
Closing out per previous comments. You shouldn't have too many problems though, as 16px is normally the browser default. Check that you haven't changed your default text size or enabled zoom.
