### ISSUE TITLE
<fieldset> does not obey grid

### ISSUE THREAD

**Issue by fisharebest** [twbs/bootstrap#21666]
See https://v4-alpha.getbootstrap.com/components/forms/#using-the-grid

The `<fieldset>` and `<legend>` contains grid markup that should align the radio buttons with the text inputs and checkbox.

However, the contents of `<fieldset class="form-group row">`, (`<legend class="col-form-legend col-sm-2">` and `<div class="col-sm-10">`), are stacked vertically rather than horizontally.

![screen shot 2017-01-11 at 20 04 13](https://cloud.githubusercontent.com/assets/2306088/21864448/c261e9ca-d839-11e6-9fde-8e3ac9a10b8f.png)

**Comment by nthorpe** [comment]
We're also having trouble with this. Flexbox doesn't work on fieldsets in Chrome
https://bugs.chromium.org/p/chromium/issues/detail?id=375693

**Comment by cvrebert** [comment]
This is Flexbug 9: https://github.com/philipwalton/flexbugs/blob/master/README.md#9-some-html-elements-cant-be-flex-containers
We can't really do anything about this. It's perhaps worth mentioning in the docs though.

**Comment by mdo** [comment]
Oof, definitely worth mentioning in the docs. We'll likely use the workaround for that bug (wrapping the contents of the `<fieldset>` in a `<div>`.

**Comment by fisharebest** [comment]
> (wrapping the contents of the `<fieldset>` in a `<div>`

This breaks HTML validation, as `<legend>` needs to be the first child of a `<fieldset>`.
https://developer.mozilla.org/en/docs/Web/HTML/Element/legend

But if this is the best workaround we have, then we have little choice.

**Comment by mdo** [comment]
Addressing this in #22271.

**Comment by bircha** [comment]
I also discovered this issue today. Example http://codepen.io/anon/pen/NpoqPm only seems to work in Firefox and IE11. Edge, Chrome, iOS Safari does not layout the fields properly into two columns.

**Comment by chrisbenseler** [comment]
I'm facing the same problem now. Any news about this issue?

**Comment by fisharebest** [comment]
As described in the 4.0 [documentation](https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form), you need to wrap the `<legend>` in a `<div>`.

Yes, it's invalid HTML. But it seems to work in all browsers.

**Comment by cweiske** [comment]
The invalid HTML issue is in #24938.
