### ISSUE TITLE
Fixed navbar not working on mobile

### ISSUE THREAD

**Issue by rolandoldengarm** [twbs/bootstrap#21675]
The fixed navbar, in [this example](https://v4-alpha.getbootstrap.com/examples/navbar-top-fixed/), is working fine on desktop. However, when I open Chrome Dev Tools and switch to mobile, it's no longer fixed when scrolling.

**Comment by sleewoo** [comment]
however it works well on real devices.
also works on xcode's iPhone simulator.

**Comment by jbruni** [comment]
I tried to reproduce, but I couldn't. Using Ubuntu Chrome 55.0.2883.87 (64-bit), opened DevTools, switched to mobile, and it just works. The navbar remains fixed.

**Comment by mdo** [comment]
Indeed, it is fixed appropriately for me. If there's something else going on, please do update the issue here and we can revisit.
