### ISSUE TITLE
Scrollspy on bodytag not working on wordpress site

### ISSUE THREAD

**Issue by peecore** [twbs/bootstrap#21686]
I'm having troubles putting to work scrollspy in one page of my site:
https://www.agenciaboutique.cl/work/supremevision/nosotros

I did everything like bootstrap docs says and more. Tried calling the target with js aswell but nothing works. Also thought that js file wasn't working but if I add scrollspy to another element inside the code with height it works. But I need it to work on the body tag.
Could you help me?

**Comment by patrickhlauke** [comment]
For help/support of this kind, please use StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
