### ISSUE TITLE
Sass variable in _custom.scss strange behavior

### ISSUE THREAD

**Issue by henk23** [twbs/bootstrap#21688]
I'm currently on v4.0.0-alpha.6.
When I put this line into my `_custom.scss`:
```scss
// _custom.scss
$font-family-sans-serif: MyFont, sans-serif;
```

running grunt does **not** update the font in the resulting dist/css. This **does** work though:
```scss
// _custom.scss
$font-family-sans-serif: Oswald, sans-serif;
$font-family-base: $font-family-sans-serif;
```
Not sure if this is a bootstrap issue or if it is standard sass behavior. But I'm _pretty sure_ it worked in alpha.3 without adding `$font-family-base`.

**Comment by Quy** [comment]
Probably related to this issue #21603 .

**Comment by henk23** [comment]
Absoluteley. Thanks.
