### ISSUE TITLE
Bootstrap 4.0.0, Strange operation of the responsiveness. Is it a bug?

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#21689]
I'm using Bootstrap 4.0.0-alpha.6.

I'm using the code in above plunker:

https://plnkr.co/edit/Awoof7KfACHXlPpQYNLo

and everything works in the small preview window.

**If I enlarge** the `col-6` columns are like `col-3`. For enlarge the screen click the small blue icon at top right of the page.

See the screenshot:

![col-6noresponsiveness](https://cloud.githubusercontent.com/assets/21275217/21908465/280d36be-d914-11e6-8e08-fc65b3bd0942.jpg)

- Browser and version (Chrome 55)

**Comment by sickboy** [comment]
You have children inside `display: flex` elements which do not have flex: 1 set,
the selectors in question are: `.somethingRandomlyEveryTime > .container-fluid > .row`
In the example you can just as well drop the `.d-flex` from all three.

**Comment by johnunclesam** [comment]
Yes, but if I remove `d-flex` selector from `.main, somethingRandomlyEveryTime` and `container-fluid` the scrollbars disappear... I need them scrollable.

**Comment by sickboy** [comment]
@johnunclesam then adding `flex: 1` to the other 3 should do the trick.

**Comment by johnunclesam** [comment]
Yes. It works. But there is something in Bootstrap 4 for `style: flex: 1;"`?

**Comment by sickboy** [comment]
@johnunclesam so far I just found the class `media-body`

**Comment by johnunclesam** [comment]
Yes, `.media-body` but I can't use it if tomorrow it will do anything else than `flex: 1`, maybe something related to medai objects.

Can you explain bettere your words: however you require a row for each level`... I don't understand what you mean.

**Comment by mdo** [comment]
I don't see this as a bug in Bootstrap so much as an incomplete flexbox implementation. Closing out unless there's something specific to the grid we need to fix.
