### ISSUE TITLE
Carousel slider bouncing on the lefthand side when it slides

### ISSUE THREAD

**Issue by optimido** [twbs/bootstrap#21685]
This is what I am getting using Edge (on the left hand side towards the end of the move) - https://www.screencast.com/t/vhNWdirw - is this a bug?

**Comment by dlis** [comment]
I can confirm this bug in the following browsers on MacOS:
- Google Chrome 55,
- Safari 10.

**Comment by optimido** [comment]
Is there anything happening with this or have I missed a solution somewhere else? Thanks
