### ISSUE TITLE
[css] [v4] .text-xs-center no longer available

### ISSUE THREAD

**Issue by julmot** [twbs/bootstrap#21698]
I'm only able to extend `@extend .text-center;`, not `@extend .text-xs-center;`. According to the "Migrating" guide, it should be possible

> Added responsive variations to our text alignment classes .text-{sm,md,lg,xl}-{left,center,right}.

**Comment by sqal** [comment]
It was removed in alpha 6 - https://github.com/twbs/bootstrap/pull/21217

**Comment by julmot** [comment]
@sqal Thanks for this information. What were the reasons?

**Comment by Quy** [comment]
From the Alpha 6 announcement:

> First, we’ve dropped the -xs infix from our lowest (extra small) breakpoint. xs isn’t a responsive breakpoint quite like sm, md, lg, and xl because it doesn’t start applying styles at a min-width and up. It simply applies to everything as there’s no bounding @media query.
