### ISSUE TITLE
Navbar 'md' triggers at 992 instead of 768

### ISSUE THREAD

**Issue by schmitgreg** [twbs/bootstrap#21691]
I noticed that while all of the other responsive classes define medium (md) as 768 px viewport, the navbar collapses the menu at 992 px. `navbar-toggleable-md` is the problematic class, although there could be others.

**Comment by vanduynslagerp** [comment]
Fixed with #21719
`navbar-toggleable-md` will now break at 768px

**Comment by vanduynslagerp** [comment]
You might want to keep the issue open until the PR is merged, for tracking purpose. Just in case the PR doesn't get merged...
