### ISSUE TITLE
JS/Carousel - "Carousel is sliding"

### ISSUE THREAD

**Issue by nlemoine** [twbs/bootstrap#21704]
### Steps to reproduce

- Open: https://v4-alpha.getbootstrap.com/components/carousel/
- Open browser console
- Click quickly on "next" or "prev" arrow multiple times
- You will get some errors as shown above:
![capture d ecran 2017-01-13 a 14 53 53](https://cloud.githubusercontent.com/assets/2526939/21932288/25d5e756-d9a0-11e6-970f-ac1fb393c2a0.png)

### Issue source

I can't understand why you're throwing an error when `next`/`prev` methods are called which is likely to happen when navigating a carousel. As long as events don't get queued, I think that shouldn't happen.
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L124

**Comment by Johann-S** [comment]
Due to this PR : #17823
This PR was made to notice user that the plugin you use is in transition to avoid some behaviors like, I show my plugin and hide it at the same time without listenning to the event

**Comment by nlemoine** [comment]
Salut ;)
Sorry, I didn't still understand why an error is needed if the component is transitioning.

**Comment by Johann-S** [comment]
Salut :smile: 
That PR : #17823 was created to fix this issue https://github.com/twbs/bootstrap/issues/17800 maybe it can help you

**Comment by nlemoine** [comment]
I understand some actions must not be fired while something is executing.

I just don't get why an error has to be thrown to the console instead of simply returning to stop execution.

**Comment by Johann-S** [comment]
I think because we have to notice user why their actions have been canceled.
But yes we have a lots of issues related to this and currently I'm looking for a better solution

**Comment by nlemoine** [comment]
>  we have to notice user why their actions have been canceled.

You mean developer? No standard user opens a browser console ;)

IMHO (I'm only speaking for the carousel component here), noticing user/developer when he's clicking too hard on the next/prev buttons is pointless. It's a common standard behaviour to avoid stacking events when the component is doing something. No one expects that multiple actions will be recorded and queued for later execution (i.e. I quickly click five times on the next control, the carousel won't slide five times).

I'll close the issue and look forward to a better transitions handling.

**Comment by vanduynslagerp** [comment]
Ref #21727
