### ISSUE TITLE
4.0.0-alpha.6: Navbar should have style of .navbar-toggleable-xl by default

### ISSUE THREAD

**Issue by spongessuck** [twbs/bootstrap#21706]
My navbar is compact and shouldn't be toggleable. I've had to set the class to `.navbar-toggleable-xl` to make this work, which is counter-intuitive.

I don't understand why a `navbar-toggleable-*` is required when `.navbar-toggleable-xl` makes it never toggle. Navbars should have the style currently given to `navbar-toggleable-xl` by default.

**Comment by vanduynslagerp** [comment]
Fixed with #21719
Using `navbar-toggleable` will allow to never collapse.
In addition, omitting `navbar-toggleable-*` on the navbar will make always collapsed.
