### ISSUE TITLE
4.0.0.alpha6: .navbar-text should have the same vertical padding as .nav-link

### ISSUE THREAD

**Issue by john-999** [twbs/bootstrap#21705]
Vertical padding (top and bottom):
- .navbar-text shows 0.425rem
- .nav-link shows 0.5rem

This means that 2 juxtaposed elements having these classes will not be vertically aligned.

Solution: Change .navbar-text to have 0.5rem of top- and bottom-padding.

**Comment by bardiharborow** [comment]
The relevant code is [scss/_variables.scss#L633](https://github.com/twbs/bootstrap/blob/b47c252ee13c536205105dcb16029021118f989c/scss/_variables.scss#L633) and [scss/_navbar.scss#L69-L70](https://github.com/twbs/bootstrap/blob/b47c252ee13c536205105dcb16029021118f989c/scss/_navbar.scss#L69-L70).

**Comment by vanduynslagerp** [comment]
Should be fixed by #21705

**Comment by iatek** [comment]
+1
