### ISSUE TITLE
"col-xs-*" aliases for "col-*" classes for compatibility

### ISSUE THREAD

**Issue by dmiko** [twbs/bootstrap#21701]
How about to add aliases "col-xs-*" for "col-*" classes as far you've dropped -xs?
This will be extremely helpful for migrating from B3 to B4 and from B4alpha5 to B4.
Grid subsystem is the only component which is used by everyone Bootstrap users. In many cases migration from B3 to B4 was almost painless, till this moment (xs dropped).

I suggest:
- Keep col-xs-* and col-* together in B4
- Announce removing col-xs-* in B5... or never
- Let ability to build B4 from SASS without -xs- support (for those who needs size optimization).

For better effect this will be fine to make changes to B4alpha6 immidiately (just suggestion and my vision). For example one of my website became broken (yes, i am dumb and use dinamyc alpha version from CDN, but... is seemed to be rather stable for a long time, I think I am not alone in this).

**Comment by hultberg** [comment]
When there is a new major version I think it's reasonable that migration do not need to be painless. Having aliases too keep backward compatibility just clogges the project.

**Comment by browner12** [comment]
for a breaking change, this is about as painless as they come. find and replace `-xs-` with `-`.

**Comment by dmiko** [comment]
@browner12 you forget about content saved into DB. Yes, we can have tons on responsible content on the website, Bootstrap is not only for templates.
Also there are Bootstrap-related tools which now need to be changed too.

**Comment by Starsam80** [comment]
I just want to remind everybody that bootstrap 4 is currently in alpha, meaning breaking changes are going to happen all the time. Until bootstrap 4 gets released, I don't think we should need to worry about backward compatibility.

**Comment by IamManchanda** [comment]
We are using this much and more code [currently](https://gist.github.com/IamManchanda/c2f6444f956fc489d44a773a73ef87af) for `col-`

and i dont think this is a good idea to duplicate that!

**Comment by mdo** [comment]
No plans to keep the `-xs` around in v4. No point in doing so given we explicitly make major versions all about breaking backward compatibility to advance the project.
