### ISSUE TITLE
Cannot override CSS padding for select.form-control

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#21712]
```
        .form-control {
            padding: 0.2rem 0.5rem;
        }
        
        select.form-control {
            padding: 0.2rem 0.4rem;
        }
```

Using Alpha 6.

These style override settings have no effect on the **select** element. I believe you are using JS to set the select height - which I think is a design flaw.

For example, I think there is too much padding on the **.form-control** class. Others may think it's just right. I should be able to easily override it, but if bootstrap JS is just going to bash the style settings, it will remain confusing and frustrating.

**Comment by bpierson** [comment]
Looks like it's a calc() in CSS rather than in javascript. So what's the best approach to override? I tried **!important** with no success.

**Comment by bpierson** [comment]
Ok, this seems to work (select is still 1px taller on IE, but so are the default settings, so that's probably an IE thing):

```
        .form-control {
            padding: 0.2rem 0.5rem;
        }

        select.form-control:not([size]):not([multiple]) {
            height: 1.75rem;
        }
```

**Comment by Nitin304** [comment]
Hi @bpierson, did you got a solution for this?
