### ISSUE TITLE
Semantic Row mixin Missing Horizontal gutter Padding

### ISSUE THREAD

**Issue by Timoti** [twbs/bootstrap#21718]
@include make-row() doesn't include horizontal padding , so semantic grids are failing to match their non-semantic equivalents.  

![image](https://cloud.githubusercontent.com/assets/99953/21951977/5ad2b2a6-da75-11e6-800b-52edfed54c61.png)

Currently this appears to be provide for the non semantic version in _grid_framework.scss by  the %grid-column extend

I hope I'm not missing something here but this is making semantic grids impractical and I'm forced to use an alternative

Just BT - In general it seems the semantic side of things could use a lot more love - particularly with documentation.

Thanks 

Chrome Canary Version 57.0.2979.0  - MacOS 10.11.6

**Comment by bardiharborow** [comment]
The relevant code is [scss/mixins/_grid.scss#L40-L51](https://github.com/twbs/bootstrap/blob/b47c252ee13c536205105dcb16029021118f989c/scss/mixins/_grid.scss#L40-L51).

**Comment by mdo** [comment]
Our grid classes use the semantic mixins, so they're essentially getting the same code. Are you using the correct markup?

**Comment by mdo** [comment]
Never heard back on this, but closing out. The rows don't get padding at all, not in the mixins or the classes. Without a live example, can't help you. I am updating the semantic grid docs though; PR coming for that.
