### ISSUE TITLE
How to keep modal-open class on body as long as the one of the more modal window is open

### ISSUE THREAD

**Issue by mijatovic85** [twbs/bootstrap#21710]
Hello, I have one small issue with modal windows, and I need your help. So, I have two modal windows on same page, `<div class="modal book-modal modal-fullscreen fade" id="book-modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="book-modal" aria-hidden="true">` and `<div class="modal modal-fullscreen fade" id="nav-modal" tabindex="-1" role="dialog" aria-labelledby="navbar-modal" aria-hidden="true">`

I know that multiple open modals not supported, but I don't have problem with that, because without any problems opening and closing any of them, together or separately, but I have just another problem. 

When I open first and second together, both of them gets additional class `in` , and then when I click on `data-dismiss="modal"`, this causes the closing one of them correctly, but the problem is at this point that the from body disappears class `modal-open` although the second model is still open. 

Please can you help me how to fix this issue?

**Comment by IamManchanda** [comment]
Can you share the codepen or js fiddle ?

**Comment by patrickhlauke** [comment]
Bootstrap does not support multiple modal dialogs open at the same time, as you noted. Therefore, I'd suggest asking your question on StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by mijatovic85** [comment]
http://mile.x3.rs/apartment/

1. Resize browser window < 991px
2. Open collapsed burger menu 
3. On the bottom of nav-modal click book now button 
4. Close book-now modal

Then, you will noticed that vertical scroll bar is appear, that is because class="modal-open from body disappear
