### ISSUE TITLE
No slide animation of Carousel v6

### ISSUE THREAD

**Issue by ChristophKnopf** [twbs/bootstrap#21713]
Hello,

1. go to http://v4-alpha.getbootstrap.com/components/carousel/ and copy any example code you like
2. test on alpha-v6 release and slide animation is gone
3. works like charm in alpha-v5

- Operating system and version Windows 10
- Browser and version Chrome, Firefox both newest version

PS: you are awesome!

**Comment by vanduynslagerp** [comment]
The version of Bootstrap deployed on http://v4-alpha.getbootstrap.com/components/carousel/ is the alpha-v6 and the slide animations works for me on both Chrome and Firefox (Mac).

Do you have a JSBin that shows the problem ?

**Comment by ChristophKnopf** [comment]
No, couldn't get it to run there, so I sent you a link via mail.

**Comment by vanduynslagerp** [comment]
In the email you sent me you are using the css of alpha 6 and the JS of alpha 5.

I'd suggest asking for this sort of support/advice on StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by ChristophKnopf** [comment]
I really don't know why but I accidentally had v5 productive, changed that to v6 and everything is running normal. I will stop to cod after midnight yet.
Sorry for wasting your time :(
Please close
