### ISSUE TITLE
Forms are not styled

### ISSUE THREAD

**Issue by schmitgreg** [twbs/bootstrap#21725]
In many frameworks, you render forms from a view. For example, in Django you often write something like: `{{ login_form.as_p }}` and it injects the relevant fields into the template from your view.

I noticed that when using Bootstrap, you have to specify classes like "form-control" for each text input, to get the necessary basic style. Why wouldn't you apply some class to the form and then have the CSS style the form in a sensible way? It makes everything very repetitive. This is also true for buttons.

Doesn't this make everything crazily repetitive for people writing websites?

P.S. My current hacky workaround is to modify the form itself injecting the class, however this is a gross mixing of content and presentation. That is why I think Bootstrap would be smarter to have a class that styles the contents in a sensible way, instead of having a handful of classes that you apply to each and every mother-loving input.

**Comment by mdo** [comment]
This is how we've built our forms for years now, and it's unlikely to change. You'll have to add classes to the inputs, buttons, tables, modals, navs, etc as you need them.

**Comment by schmitgreg** [comment]
Ah, 'we've always done it that way.' That is an avowal of a bad conscience.

**Comment by rafalp** [comment]
@schmitgreg it's not. If anything, its your task as developer to know your tools and how to make them work together.

Django 1.11 will (finally!) ship with template-based form rendering, allowing you to setup bootstrap templates. Thats weeks away from landing.

In meantime you may use alternative form rendering approach, either using ready solution like crispyforms or floppyforms (both support Bootstrap 3 form markup out of the box), or by devising custom rendering strategy. Bulk of work can be achieved via custom templates mixed filters for introspecting otherwhise hidden attributes from form fields (like widget's type and backend specified props).

**Comment by patrickhlauke** [comment]
The whole philosophy of Bootstrap is that you opt into things. It sets a few basic normalisations/styles, and everything else requires you as the author to opt into them with relevant classes. This allows you to easily mix and match your own custom styles if you don't want to opt into specific ones for certain cases.

**Comment by schmitgreg** [comment]
After I left that I started thinking about the consequences of having Bootstrap put in more active styles to all general form elements (not just clearing silly browser defaults, but really putting in active styles), and I see how this paradigm would end up requiring me to use things like "remove-bootstrap-annoying-default" classes for certain scenarios, which could be just as annoying. So I think I am convinced of this philosophy of opt-in.
