### ISSUE TITLE
bower problems solved

### ISSUE THREAD

**Issue by publicocean0** [twbs/bootstrap#21738]
hi i saw there are a lot of issues about new version of bower json with less files. 
I solved problems with bower using 

https://github.com/publicocean0/bindep

bye

**Comment by mdo** [comment]
There are no planned changes to v3's Bower setup.

**Comment by publicocean0** [comment]
really it is not necessary no changes inside bower.json. I m using your v3 bower.json inside a project with other tens of bower components :) 
Anyway it was just a suggetion. 
bye
