### ISSUE TITLE
Button dropdown links don't work on mobile (android, iOS)

### ISSUE THREAD

**Issue by MartinProkop** [twbs/bootstrap#21732]
Hello,

I have same issue which is mentioned here: https://github.com/twbs/bootstrap/issues/4550

My bootstrap version is 3.1.1. I have tried about 10 ways, how to fix it, which are mentioned in ticket, but anything did not worked. 

It appears only on menu elements which has class "menu-item-has-children"

Could you help me, please?

Instance of bootstrap where issue occures is here: http://sandbox.pakultura.cz/

Thank you very much

**Comment by coliff** [comment]
This is not the place to post problems about using Bootstrap. You should certainly update to the latest version of Bootstrap (v3.3.7)... and if problem persists post about it on Stackoverflow or ask in the Slack channel.

**Comment by mdo** [comment]
If this is a problem on the latest version of v3 (v3.3.7), we can tag it appropriately and perhaps tackle it when we swing back around to a v3 update after shipping v4. If this happens in v4, please provide a reduced test case using something like JS Bin.
