### ISSUE TITLE
Carousel slide animation blurry on completion [osx/chrome]

### ISSUE THREAD

**Issue by henwen** [twbs/bootstrap#21749]
This is new behavior on Alpha 6 –

On completion of the slide animation, the carousel content is blurry for ~200ms, then clarifies and shifts slightly. It's fairly innocuous in the gif below but becomes more serious with HD images or more text content. Visit the [carousel docs](http://v4-alpha.getbootstrap.com/components/carousel/) for a clearer example.

![cheapinsidiousbream](https://cloud.githubusercontent.com/assets/1422112/21998226/2941e010-dbf9-11e6-8979-bbc917c55321.gif)

The blurring aspect of this issue is only present on Chrome (only tested OSX) as far I know. The issue seems related to whatever's causing #21750 and  #21751.

**Comment by mdo** [comment]
There's not much we can do here—this is just using standard CSS to move the items. It looks pretty solid on my end across all browsers. Hardware acceleration is likely playing a role here.
