### ISSUE TITLE
card card-warning (et al) formatting on list-group

### ISSUE THREAD

**Issue by Gemione** [twbs/bootstrap#21748]
Card formatting is for embedded list-group is not constant. This may not be a bug but it doesn't look great.

```
<div class="card text-center card-inverse card-danger">			
 <div class="card-block">
  <h4 class="card-title">Top Sites This Month</h4>
  <ul class="list-group list-group-flush" style="list-style-type: none;">
    <li class="list-group-item">Something - 57.6%</li>
    <li class="list-group-item">Something Else - 57.1%</li>
    <li class="list-group-item">Another - 56.8%</li>
    <li class="list-group-item">Last One? - 56.2%</li>
    <li class="list-group-item">Nope - 55.9%</li>			  	
  </ul>
 </div>
</div>
```
Result (highlighted text to show)
![card list](https://cloud.githubusercontent.com/assets/25158907/21996384/fd80fb6a-dbf7-11e6-9edd-28c0e3eaace4.png)

**Comment by mdo** [comment]
I don't think there's anything to change here. You can choose to not use flush list groups, or place the list group outside the `.card-block`.
