### ISSUE TITLE
Utilities 'ml-auto' and 'mr-auto' cause navbar components to overflow the navbar

### ISSUE THREAD

**Issue by raymondelooff** [twbs/bootstrap#21745]
In IE10, the 'ml-auto' and 'mr-auto' utilities cause the navbar components to overflow the navbar. As far as I tested this only happens in IE10. This is probably due to a IE10 browser bug.

![schermafbeelding 2017-01-16 om 15 49 09](https://cloud.githubusercontent.com/assets/9716806/21987490/1b367dd6-dc04-11e6-896d-96fada933a35.png)

Strange enough the first toggler example works fine.
![schermafbeelding 2017-01-16 om 16 00 39](https://cloud.githubusercontent.com/assets/9716806/21987736/f8284f6c-dc04-11e6-8df5-53b870045da9.png)

OS: Windows 7 (VM)
Browser: IE10

You can see the bug when visiting the navbar documentation with IE10: https://v4-alpha.getbootstrap.com/components/navbar/.

**Comment by chrismbarr** [comment]
Same thing happening for me in IE11 with a `modal-footer`

![image](https://cloud.githubusercontent.com/assets/463685/23582180/88b91694-00f2-11e7-8075-cf1ebe1c59e6.png)


Relevant HTML:
```html
<div class="modal-footer">
        <button class="btn btn-sm btn-outline-danger mr-auto align-self-end" type="button" ng-click="$ctrl.confirmDelete()">
        <span class="fa fa-trash"></span>
        Delete this test
    </button>
    <button class="btn btn-secondary" type="button" ng-click="$ctrl.dismissModal()">
        Close
    </button>
    <button class="btn btn-success" type="button" ng-click="$ctrl.save()">
        <span class="fa fa-check"></span>
        Save Changes
    </button>
</div>
```

**Comment by MisterY** [comment]
Not sure if this is the same thing, but adding a right-aligned item in the navbar, by using mr- or ml-auto throws the right item off the screen.

![image](https://cloud.githubusercontent.com/assets/462445/23709595/45f03c86-041a-11e7-9481-3e19f3f55797.png)

**Comment by mdo** [comment]
Judging by some of the descriptions here and at https://github.com/philipwalton/flexbugs, this is a flex bug only in IE 10. I haven't found the exact fix yet, but I feel like this is a fixable issue.

**Comment by raymondelooff** [comment]
I think I have found the cause of the issue. The '.navbar-collapse' element had a width of 100%, [declared on this line](https://github.com/twbs/bootstrap/blob/65ffb1c3b6e94440812a2e228cb8e8be512652ec/scss/_navbar.scss#L163) (at the moment of writing, this line is now gone). When the collapse element is placed next to an item with 'display: inline-block', in most cases the navbar brand, IE10 doesn't take that element into account when calculating the width of the collapse element.

The following screenshot shows the outlines of the '.navbar-collapse' element. The navbar brand is placed next to the collapse element.

![image](https://cloud.githubusercontent.com/assets/9716806/24326282/70030b2c-11ab-11e7-891e-d37d47aa5ba6.png)

After I replaced 'width: 100%' with 'flex: 1 1 auto', the width was calculated correctly in IE10 and other browsers.

![image](https://cloud.githubusercontent.com/assets/9716806/24326287/7c452b68-11ab-11e7-913e-a17515c62a13.png)

It appears that this issue has nothing to do with the margin utilities. As the navbar examples from the docs are not working due to the recent navbar changes and the fact that the line that caused this issue is now gone, I can't reproduce the issue on the latest development version. I can check whether this issue still exists when the examples are fixed 😀

**Comment by mdo** [comment]
Should be fine in v4-dev.

**Comment by mheptinstall** [comment]
Latest v4-dev still has issue with `mr-auto` in a `modal-footer` in IE11 https://jsfiddle.net/8mt7qk7u/3/

**Comment by mdo** [comment]
@mheptinstall There's only so much we can do. See the link under this section of the docs: http://getbootstrap.com/docs/4.0/utilities/flex/#auto-margins.
