### ISSUE TITLE
Flexbox Grid Doesn't Add Margin top and bottom

### ISSUE THREAD

**Issue by imcodingideas** [twbs/bootstrap#21742]
- MacOS Sierra 10.12.2
- Chrome 55.0.2883.95
- Demo: http://joseph-m-chambers.herokuapp.com

In the projects I have a grid of cards. However, the spacing is completely off in the cards. No  padding-top or padding-bottom

**Comment by Skipvanthof** [comment]
Having the same problem with card-decks, cards within card-columns have:
margin-bottom: $card-columns-margin; 
But cards within card-decks don't have this margin.

**Comment by mdo** [comment]
We've removed most of the margins like this in favor of explicit margin utilities or custom styles.

**Comment by imcodingideas** [comment]
@mdo can you create documentation to show card-columns examples?
