### ISSUE TITLE
Spacing utility classes missing in Alpha 6

### ISSUE THREAD

**Issue by chanaka1** [twbs/bootstrap#21754]
The classes are named using the format **{property}{sides}-{size}** for xs and **{property}{sides}-{breakpoint}-{size}** for sm, md, lg, and xl.

None of **Spacing utility classes** are working and does not seems to be in the package too. 

Did we change it or remove it?

**Comment by hultberg** [comment]
In v4, they are not removed: https://v4-alpha.getbootstrap.com/utilities/spacing/

In v3, there are no spacing utilities.

**Comment by bardiharborow** [comment]
I can't see any problems here. Do holler if you are sure there is something wrong here. <3
