### ISSUE TITLE
Semantic modal with dialog element

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#21758]
The HTML living standard defines the `dialog` element.

As of January 2017 it is only supported by Chrome so far, but it seems to be scheduled for inclusion in Firefox as support can be enabled by a flag in Firefox 53.

Does or could Bootstrap support modals using the `dialog` element?

**Comment by IamManchanda** [comment]
You can use any html5 elements like 
[Picture tag](https://github.com/twbs/bootstrap/issues/21376), video tag, dialog tag in bootstrap....

There is no need for bootstrap to support it!!

**Comment by bardiharborow** [comment]
> Does or could Bootstrap support modals using the dialog element?

I don't imagine that the `<dialog>` element *isn't* supported. It's more a matter of if we want to start using it in the documentation examples. Relevant [MDN listing](https://developer.mozilla.org/en/docs/Web/HTML/Element/dialog).

**Comment by Starsam80** [comment]
I don't think this would be added anytime soon, because of browser compatibility.
Ref #20175, which added it to the [most wanted features page](https://v4-alpha.getbootstrap.com/browser-bugs/#most-wanted-features)

**Comment by bardiharborow** [comment]
@Starsam80 ah thanks, didn't catch that. Closing this as a WontFix [pending Edge support](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/dialogelementformodals/).

**Comment by vanillajonathan** [comment]
Would it make sense to update the documentation to use `dialog` instead of `div` ?

**Comment by rafalp** [comment]
<img width="615" alt="zrzut ekranu 2017-01-18 o 12 49 38" src="https://cloud.githubusercontent.com/assets/750553/22062960/a3f26fc6-dd7c-11e6-90a3-ff9f3d5eaffb.png">

There's still some way to go before one may think about using `dialog` element, unless you want to polyfill it.

**Comment by vanillajonathan** [comment]
Yeah, but Bootstrap already implements its own modals using JavaScript, so if it used the existing `dialog` element, it would still trigger and work with browsers that do not yet support the `dialog` element. The question is if it would collide browsers that currently support the `dialog` element.

Using `dialog` instead of `div` already today would have the benefit that later versions of Bootstrap, i.e. 4.1 or 4.2 could clean up or remove the modal code when browsers have caught up with support for the `dialog` element.

**Comment by Phantomphyre** [comment]
<[https://github.com/PheonxFyre/curl-www.git]>

**Comment by RehanSaeed** [comment]
Edge now has `dialog` [under consideration](https://caniuse.com/#search=dialog). You can use the [dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill) to add support today.

Should this be reopened?

**Comment by AdamInstem** [comment]
As of today, we're seeing [93% rated coverage](https://caniuse.com/?search=modal), with all browsers supported.

It would be really great to see this semantic element supported.
It should be possible to realise some nice simplification of the current div-based modal markup.

**Comment by vanillajonathan** [comment]
This issue is also in issue #37000 which has also been closed because of issue #33804. This is schedule for Bootstrap 6.
