### ISSUE TITLE
Where did .tag go in alpha.6?

### ISSUE THREAD

**Issue by ellisio** [twbs/bootstrap#21753]
With the release of `alpha.6` it appears `.badge` was reintroduced and `.tag` was removed. The documentation still says `.tag` should be used; yet it does not exist.

https://v4-alpha.getbootstrap.com/migration/#labels-badges-and-tags

Possible merge error?

**Comment by Starsam80** [comment]
This was already fixed: #21565

**Comment by ellisio** [comment]
Figured it was either doc error (docs always seem to lag the release), or merge as that has happened before with alpha.4.

Cheers!
