### ISSUE TITLE
4.0.0-alpha.6: .container in .navbar not fluid when XS

### ISSUE THREAD

**Issue by spongessuck** [twbs/bootstrap#21752]
A .container should act the same as .container-fluid on XS screens, but the .container in a .navbar isn't getting its width set to 100% as it should. This causes the .navbar contents to clump together in the center of the navbar.

https://plnkr.co/edit/1bSkz3IhFFtNCweFCsP7?p=preview

**Comment by vanduynslagerp** [comment]
I think it's a duplicate of #21605 and #21590

**Comment by spongessuck** [comment]
I think #21605 more so, thanks. Closed.
