### ISSUE TITLE
Carousel slide animation shifts up ~1px on completion [osx/firefox]

### ISSUE THREAD

**Issue by henwen** [twbs/bootstrap#21750]
This is new behavior on Alpha 6 –

On completion of the slide animation, the carousel-item content shifts upward by ~1px..

![neatfrequenthare](https://cloud.githubusercontent.com/assets/1422112/21998430/60832326-dbfa-11e6-85a1-8ff03c52374b.gif)

This behavior is only on Firefox (OSX) as far I know and is likely related to #21749 and #21751.

**Comment by mdo** [comment]
This seems to be the result of pixel rounding. Various tests on my end showed this only happening at certain browser widths; resizing by a pixel or so fixed it. Closing as a won't fix given we cannot control that.
