### ISSUE TITLE
uncaught "type error ajax is not a function" error after switching to the three new starter template scripts.  

### ISSUE THREAD

**Issue by jkstermitz** [twbs/bootstrap#21766]
I made the switch from alpha 5 to alpha 6 simply by swapping out the prior three starter template scripts, and putting the new ones in ( jquery-3.1.1.slim.min.js, tether 1.4.0 and of course alpha 6 via the cdn ).  I got the scripts from this page:  https://v4-alpha.getbootstrap.com/getting-started/introduction/

Incidentally (I hope), the prior jquery came from googleapis.com and was version 3.1.1.

I did not make any other changes anywhere else...simply put in the three new scripts in place of old.  Now my ajax function generates Type error:  

Uncaught TypeError: $.ajax is not a function
    at HTMLAnchorElement.<anonymous> (?page=home:230)
    at HTMLAnchorElement.dispatch (jquery-3.1.1.slim.min.js:3)
    at HTMLAnchorElement.q.handle (jquery-3.1.1.slim.min.js:3)

I can "fix" this simply by swapping out the new scripts in place of the originals.

**Comment by zoiii** [comment]
Use https://code.jquery.com/jquery-3.1.1.min.js instead, not sure what is the dependency of BS to "slim" :)

**Comment by jkstermitz** [comment]
Yes, I did switch back to that and it works fine with alpha 6 bootstrap scripts for js.  Thanks.

**Comment by bardiharborow** [comment]
Bootstrap only requires the [slim build](https://stackoverflow.com/questions/35424053/what-are-the-differences-between-normal-and-slim-package-of-jquery) of jQuery. If you need to use features such as `$.ajax`, which are not included in the slim build, you should use the full build instead.

**Comment by trantoan960** [comment]
:)) Thanks

**Comment by david95thinkcode** [comment]
@bardiharborow  Thanks  !
