### ISSUE TITLE
hidden class added by Modernizr causes blank page when combined with bootstrap

### ISSUE THREAD

**Issue by tschallacka** [twbs/bootstrap#21762]
Relevant: https://github.com/Modernizr/Modernizr/issues/2147

Reproduce:
 make html page with bootstrap
 add Modernizr.js compiled with the following modernizr-config.json

```
{
  "minify": true,
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/dom/hidden",
  ]
}
```

suggested solution:

make https://github.com/twbs/bootstrap/blob/96d8553becfdf219c40e046e1202d4f2a2723010/scss/mixins/_visibility.scss#L4

`html .hidden `  instead of just `.hidden`

**Comment by ryanseddon** [comment]
For reference: https://github.com/Modernizr/Modernizr/issues/2147#issuecomment-274682514

**Comment by tschallacka** [comment]
yea, but that requires to rewrite other libraries that use default modernizr classes too.

**Comment by mdo** [comment]
This won't be a problem anymore with #22113.
