### ISSUE TITLE
'label label-default' on ie not have the same height on chrome

### ISSUE THREAD

**Issue by shihao316558512** [twbs/bootstrap#21763]
I looked for a lot, but no one raised the question.

**Comment by bardiharborow** [comment]
I do not have access to a IE instance to test. Is the issue present on https://v4-alpha.getbootstrap.com/components/badge/#example? This is what I get in Chrome 56:

![screenshot](https://cloud.githubusercontent.com/assets/1073681/22050352/4aab23b0-dd8e-11e6-9968-cc55b66e7596.png)

**Comment by shihao316558512** [comment]
sorry,i said bootstrap v3 
the height of label on ie  is smaller than chrome .
how to do with it


https://getbootstrap.com/components/#labels

**Comment by geneparcellano** [comment]
@shihao316558512 I tried this out on IE Edge, 10, and 9, and height and width for me is the same. What version of IE are you using? Please check to make sure no other styles are being inherited from parent elements.

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
