### ISSUE TITLE
Document .text-gray-dark class

### ISSUE THREAD

**Issue by Quy** [twbs/bootstrap#21761]
Ref #19847

**Comment by vanduynslagerp** [comment]
Actually I wonder is `text-gray-dark` shouldn't be removed ?

The reason for adding it what to overwrite the default `color: #fff` on classes `bg-*` : #19842
But in alpha-6 the classes `bg-*` do not define a default `color` attribute anymore. The `bg-*` are now meant to be used with `text-*`.
So gray-dark is now the default color on an element with `bg-*`.

**Comment by Quy** [comment]
@vanduynslagerp  Maybe not per this use case #21803.
