### ISSUE TITLE
Text-center class not included in v4-alpha.5 generated CSS

### ISSUE THREAD

**Issue by shaekuronen** [twbs/bootstrap#21776]
In the docs https://v4-alpha.getbootstrap.com/utilities/typography/#text-alignment the text-center class is listed. However, when I search bower_components/dist/css/bootstrap.css, not finding text-center, only text-xs-center. 

Has the text-center class been removed in v4?

**Comment by Quy** [comment]
No. From the Alpha 6 announcement:
> First, we’ve dropped the -xs infix from our lowest (extra small) breakpoint. xs isn’t a responsive breakpoint quite like sm, md, lg, and xl because it doesn’t start applying styles at a min-width and up. It simply applies to everything as there’s no bounding @media query.

**Comment by bardiharborow** [comment]
v4-alpha.5 is not the latest version. v4-alpha.6 is. You'll need to update Bootstrap.
