### ISSUE TITLE
Theme Dashboard Alpha Update

### ISSUE THREAD

**Issue by samirotiv** [twbs/bootstrap#21779]
Hi,

I have written an email to the Bootstrap team for support, but have gotten no answer, so I'm writing here.

When is the update to 4.0.0-alpha6 going to be released for the Dashboard theme?

Also, is it possible for me to just replace the contents of the Bootstrap folder in the SASS code to update it?

Best regards,
Samir.

**Comment by Quy** [comment]
Here is a reply that may answer your questions:
https://github.com/twbs/bootstrap/issues/21564#issuecomment-273562770

**Comment by mdo** [comment]
Yup, Themes support team is still getting caught up on things. You should be able to redownload the theme a few times over provided you have your original email.

**Comment by varghesep** [comment]
@mdo There is a lot of people like me who can't download the theme due to the original email has been lost. I don't think you have any plan to provide support to such customers.
