### ISSUE TITLE
First-letter prints incorrectly in Chrome

### ISSUE THREAD

**Issue by zam6ak** [twbs/bootstrap#21771]
When using [display headings](https://v4-alpha.getbootstrap.com/content/typography/#display-headings) and trying to print (Ctrl+P) the first letter of the heading breaks layout.
Tested on Chrome v55

 
Here is sample HTML code
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Print Test</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js">
</head>

<body>

    <div class="container-fluid">
        
        <div class="row">
            <div class="col">
                <h1 class="display-4">This heading fails to print</h1>
                <p class="lead">This heading fails to print correctly.</p>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h1 class="display-1">Display 1</h1>
                <h1 class="display-2">Display 2</h1>
                <h1 class="display-3">Display 3</h1>
                <h1 class="display-4">Display 4</h1>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h1 id="h1-heading">h1 heading</h1>
                <p>Curabitur blandit tempus porttitor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

                <h2 id="h2-heading">h2 heading</h2>
                <p>Curabitur blandit tempus porttitor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

                <h3 id="h3-heading">h3 heading</h3>
                <p>Curabitur blandit tempus porttitor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

                <h4 id="h4-heading">h4 heading</h4>
                <p>Curabitur blandit tempus porttitor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

                <h5 id="h5-heading">h5 heading</h5>
                <p>Curabitur blandit tempus porttitor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

                <h6 id="h6-heading">h6 heading</h6>
                <p>Curabitur blandit tempus porttitor. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
            </div>
        </div>

    </div>

</body>

</html>
```

**Comment by zam6ak** [comment]
Here is how browser renders the page vs what the print preview looks like.
Please note that changing from "Save as PDF" to actual printer has no effect....

![image](https://cloud.githubusercontent.com/assets/838582/22069349/241fee1a-dd66-11e6-8596-0be2d8c7b4b7.png)


![image](https://cloud.githubusercontent.com/assets/838582/22069395/497d40f4-dd66-11e6-94cd-6f047db399a8.png)

**Comment by perttumyry** [comment]
As a temporary solution before this is fixed, this seemed to give proper print results for h1.

```
h1::first-letter {
    margin-top: 0;
}
```

**Comment by nataniel** [comment]
It's not display headings, it's every Hx.

This is all fine:
```
<h1>Test</h1>
<h2>Test</h2>
<h3>Test</h3>
<h4>Test</h4>
```

All of those display with first letter problem:
```
<div class="row">
    <div class="col-6">
        <h1>Test</h1>
    </div>
    <div class="col-6">
        <h2>Test</h2>
    </div>
    <div class="col-6">
        <h3>Test</h3>
    </div>
    <div class="col-6">
        <h4>Test</h4>
    </div>
</div>
```

Tested with v4.0.0-alpha.6

**Comment by tylercubell** [comment]
Disabling [text-shadow and box-shadow](https://github.com/twbs/bootstrap/blob/2ea7e388e7d180d8251e01d0905a694a779d16d0/scss/_print.scss#L29) while [emulating CSS print media](http://stackoverflow.com/questions/9540990/using-chromes-element-inspector-in-print-preview-mode/) in Chrome seems to fix the problem.

**Comment by patrickhlauke** [comment]
from #22308 @bschlosser

> This doesn't seem to be font related. I tried with `sans-serif`, `serif`, and `Arial` on macOS and they all exhibit the same up and down shift.
>
>You can make the issue appear using the Dev Tools
> 1. **(Three dot menu)->More Tools->Rendering** set **Emulate CSS Media** to **print**
> 2. Inspect the `h2` element for "Easy to get Started"
> 3. In the **Styles** pane, disable and reenable the `font-size` property on the `h2` class
>
> You should then see the problem.
> 
> To temporarily "fix it", scroll down in the **Styles** pane and find the
> `@media print
> *, ::after, ::before, blockquote::first-letter, blockquote::first-line, div::first-letter, div::first-line, li::first-letter, li::first-line, p::first-letter, p::first-line` selector and disable all of the text and box shadow properties, it looks correct, both on screen and printed.
>
>More specifically it looks like the `div::first-letter` selector in combination with the text and box shadow properties are the key.

**Comment by patrickhlauke** [comment]
Issue can also be observed in code blocks in the docs (where the opening "<" is too high up). Possibly related, some lines get cut off between pages when printing.

![capture](https://cloud.githubusercontent.com/assets/895831/25171840/08c06000-24e7-11e7-932e-1c069e11afbf.PNG)

**Comment by patrickhlauke** [comment]
Possibly also related https://github.com/twbs/bootstrap/issues/22425

**Comment by tylercubell** [comment]
I think this is a Chrome bug. After playing around for a while, this seemed to do the trick:

```html
<style>
*::first-letter {
  color: initial;
}
</style>
```

**Comment by shusain** [comment]
Seems to be okay in 4.0.0 alpha 5 but seeing a similar issue with alpha 6

**Comment by vassyz** [comment]
Also in inputs:
<img width="242" alt="screen shot 2017-05-04 at 16 58 19" src="https://cloud.githubusercontent.com/assets/1636476/25712971/ff2a28e0-30ea-11e7-950a-13bc9990d6c3.png">

**Comment by Wardrop** [comment]
I see this also in the latest Alpha.

**Comment by nicrider** [comment]
I see this as well in alpha 6. Overriding the `::first-letter` in the header like this seemed to work around the issue:
```html
<style media="print">
::first-letter{
  margin: 0px;
  padding: 0px;
  vertical-align: inherit;
}
</style>
```

**Comment by ao95** [comment]
Same with element strong, trying to fix it but no luck so far.

**Comment by grantzau** [comment]
Same problem for first letter of `<sup>` element when printing or viewing with print styles in Chrome.

As proposed by @perttumyry but for all elements, not only h1, this works for me as a temporary fix:

```css
@media print {
    *,
    *::before,
    *::after,
    p::first-letter,
    div::first-letter,
    blockquote::first-letter,
    li::first-letter,
    p::first-line,
    div::first-line,
    blockquote::first-line,
    li::first-line {
      margin-top: 0;
    }
}

**Comment by grantzau** [comment]
Same problem for me for text within `<sup>` element. I cannot fix it by overwriting CSS with any of the suggested solutions. 

It seems that the problem occurs already when the `text-shadow` and `box-shadow` properties are set in the first place (by the bootstrap print stylesheet). So, no matter what I set them to, the problem persists.

The only way I can fix it is by removing the CSS by setting `$enable-print-styles: false;` (or I could edit `_print.scss` and remove the `text-shadow` and `box-shadow` declarations).

**Comment by nafg** [comment]
Can someone explain why/how this happens?

**Comment by patrickhlauke** [comment]
Short explanation: it's a Chrome bug. I actually found the issue in the Chrome bug tracker, but as I commented on it the issue was moved/locked...in any case, it was https://bugs.chromium.org/p/chromium/issues/detail?id=739800 (if anybody else has more joy seeing it with their credentials)

**Comment by nafg** [comment]
@patrickhlauke FWIW I can view the bug without signing in. Thanks for the link. :)

**Comment by patrickhlauke** [comment]
@nafg yes the bug was reopened to the public after a friend at Google queried it being restricted https://bugs.chromium.org/p/chromium/issues/detail?id=739800#c6
