### ISSUE TITLE
Feature Request: Plain text in Dropdowns

### ISSUE THREAD

**Issue by CTMiner** [twbs/bootstrap#21772]
A nice ability would be to add plain text in a dropdown menu instead of only `<a>` and `<button>` elements. Currently this can be more or less done with `a.disabled`, but being able to use a `<p>` or `<span>` element would be nice, and would also remove having the disabled cursor. Behavior could be like `.navbar-text` is to a navbar.

Example usage, short username on navbar and full username on menu to save valuable navbar space:
![capture](https://cloud.githubusercontent.com/assets/2054816/22070679/dc7fde58-dd6a-11e6-92bb-3af2301a3eb7.PNG)

**Comment by Quy** [comment]
It can be done with Menu Headers.
https://v4-alpha.getbootstrap.com/components/dropdowns/#menu-headers

**Comment by scienceguru1** [comment]
Would be nice not not need a header. I personally find the headers annoying to the eye for something as short as this. Also, in the context of this menu "User" or "Profile" would be a more appropriate header.

**Comment by Quy** [comment]
You can use the `.dropdown-header` on any tags and override the font size in your custom css.

**Comment by guylepage3** [comment]
I feel this is something that can be added in on the developer's end and just adds extra added weight to the project. imo
