### ISSUE TITLE
Navbar dropdown issue

### ISSUE THREAD

**Issue by mattonit** [twbs/bootstrap#21778]
When I use the dropdown menu in navbar it will look great on large screens, but on mobile devices, the navbar becomes higher when I open the dropdown. It's because you use position:static for .dropdown-menu on screens smaller than 992px. It's simply to resolve by changing position: static to position: absolute;

**Comment by mdo** [comment]
Have a demo of this? And any details on browser/device/etc?

**Comment by guylepage3** [comment]
I have seen this happen in the past. there is a 2px-4px repositioning.

**Comment by mattonit** [comment]
Blue background color is just to show what I mean. Is it intended effect?

![bs navbar](https://cloud.githubusercontent.com/assets/4998725/22975126/c31d8678-f385-11e6-8c22-52b34dffd3c4.png)
![bs navbar dropdown](https://cloud.githubusercontent.com/assets/4998725/22975125/c3195e7c-f385-11e6-8987-94573cd8408c.png)

**Comment by mdo** [comment]
This is intended behavior. It's the same thing we did in v3.
