### ISSUE TITLE
Scrollbar bug on Windows 10 with IE 11, HiDPI Monitor

### ISSUE THREAD

**Issue by strebl** [twbs/bootstrap#21780]
Hi guys

I encountered a bug on Windows 10 with Internet Explorer 11 and Bootstrap v4.0.0-alpha.6.
The scrollbar is visible and hidden randomly if I resize the window.
Let me start with two GIFs which demonstrate the issue on a page without any elements except the html structure and body:
![bootstrap_v4_scrollbar_bug_my_app](https://cloud.githubusercontent.com/assets/6151204/22108718/c6a4e9bc-de54-11e6-83c0-456e6bea0375.gif)
As you can see, on some sizes the scrollbars are visible and on other sizes they are hidden.

The second GIF demonstrates the problem on https://v4-alpha.getbootstrap.com itself:
![bootstrap_v4_scrollbar_bug_getbootstrap_com_v4](https://cloud.githubusercontent.com/assets/6151204/22108792/17a9d660-de55-11e6-911d-639e07a01d45.gif)
Same problem. The only difference there is that the scrollable distance is shorter. That's because the vertical scrollbar is needed. If I remove elements until it fits vertically, the scrollable distance is the same comparing to GIF 1.

## Workaround
If I change the viewport width to auto, everything behaves as expected.
```css
@-ms-viewport {
  width: auto;
}
```

## Tests
I tested this on two computers with HiDPI displays:

 Type | Windows Version | Resolution | Scaling | Issue
------|---------------------|-------------|---------|------
Desktop|Windows 10 Pro Insider Preview 1607 Build 15007 |3840x2160|200%|Yes
Tablet - Microsoft Surface|Windows 10 Pro 1511 Build 10586 |2736x1824|200%|Yes

...and on two computers without HiDPI displays:

 Type | Windows Version | Resolution | Scaling | Issue
------|---------------------|-------------|---------|------
Desktop|Windows 10 Pro 1607 Build 14393|1920x1200|100%|No
Notebook|Windows 10 Pro 1607 Build 14393 |1920x1080|100%|No

As you can see, it happens only with HiDPI displays.

**To clarify, I don't have that issue with Edge, only with IE!**

I hope I provided enough details!

**Comment by strebl** [comment]
Further findings:
Changing the scaling to 175% or 100% on my HiDPI compiter"fixes" the issue too.
I can't bump the scaling to 200% on my low DPI devices, therefore I can't test if the issue occurs on low DPI devices @ 200% scaling.

Just tell me if you need more details.

**Comment by patrickhlauke** [comment]
MS don't accept any more bug reports for IE, so we'd have to work around it. Just wondering if adding the proposed (harmless-looking)
```
@-ms-viewport {
  width: auto;
}
```
will trigger funky behavior like https://github.com/twbs/bootstrap/issues/18543 again though. Worth investigating...
