### ISSUE TITLE
Allow negative push/pull/offset

### ISSUE THREAD

**Issue by davebowker** [twbs/bootstrap#21786]
Creating off page navigation and off page panels has required me to use negative positioning. 

Looks like these mixins spit out classes (only?) to enable me to use `@extend .push-md-2` for example. 

```
@mixin make-col-offset($size, $columns: $grid-columns) {
  margin-left: percentage($size / $columns);
}

@mixin make-col-push($size, $columns: $grid-columns) {
  left: if($size > 0, percentage($size / $columns), auto);
}

@mixin make-col-pull($size, $columns: $grid-columns) {
  right: if($size > 0, percentage($size / $columns), auto);
}
```
I can use `@include make-col-push(2)` directly, but I'd like to specify here `@include make-col-push(sm, 2)` but that doesn't work. [Feature request for that]

Continuing on, I want to be able to use negative positioning, so in the same vein use `@include make-col-push(sm, -2)` (minus symbol), but the mixin looks at only calculating the position if it's greater than 0, otherwise making it default to 'auto'.

Now, I am able to do this using the `make-col-offset` mixin and multiplying by a negative `grid-columns` number gives me the abilty to minus things by 12/17/Whatever/48/etc columns. Mucho useful. For example:

```
.off-canvas {
  @include make-col-offset(-3);
}
```
Outputs:
```
.off-canvas {
  margin-left: -25%;
}
```

Now, the only drawback to this again is when designing for responsive views that have different column widths at different viewport sizes, so going back to that $size parameter. It would be great to be able to do the following:
```
.off-canvas {
  @include make-col-offset(sm, -3);
  @include make-col-offset(md, -4);
  @include make-col-offset(lg, -5);
}
```

Right now, I'm doing the following as a workaround:
```
    @include media-breakpoint-up(xs) {
      &.secondary {
        @include make-col-offset(-8);
      }
    }
    @include media-breakpoint-up(sm) {
      &.secondary {
        @include make-col-offset(-4);
      }
    }
    @include media-breakpoint-up(md) {
      &.secondary {
        @include make-col-offset(-3);
      }
    }
```

Thoughts welcomed,
D

**Comment by guylepage3** [comment]
I don't fully understand why this cannot be done aside from the framework itself. Personally seems as though this adds unnecessary bloat. IMO.

**Comment by davebowker** [comment]
Well, apart from the size modifier offset works fine. And for push/pull, the $size > 0 prevents negative values otherwise that too would also work fine, again without the size modifier request.

I'm not saying I can't do it outside of the framework, but the code is pretty much already there apart from a tweak or two.

**Comment by mdo** [comment]
I've dropped offset, push, and pull in v4, so closing as a won't fix.

**Comment by permpkin** [comment]
Just gonna leave "this" here for others, found this fix on the google. forces container-fluid to be full width if it's within a container

.container .container-fluid {
   margin-left: calc(50% - 50vw);
   margin-right: calc(50% - 50vw);
}
