### ISSUE TITLE
Why 'Button' don't have 'cursor: pointer;' ?

### ISSUE THREAD

**Issue by firstziiz** [twbs/bootstrap#21795]
In bootstrap 4.0.0-alpha6.

I wondering why 'Button' doesn't have 'cursor: pointer;'. I think it should have.

I'm just wondering.

Thank you for replying me. 🙏🏻

**Comment by vanduynslagerp** [comment]
X-ref #21479

**Comment by firstziiz** [comment]
@vanduynslagerp -0- thank you so much !
