### ISSUE TITLE
Adopt SUIT CSS naming conventions

### ISSUE THREAD

**Issue by meleyal** [twbs/bootstrap#21794]
When working on large/shared code-bases this can really help define a strict naming scheme and enforce encapsulation through [linting](https://github.com/postcss/postcss-bem-linter).

See: https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md

**Comment by bardiharborow** [comment]
I'm sure that this is suitable for some codebases, but we likely will not be adopting this. Even if we were, it's too late in the v4 release cycle to be making such a huge breaking change for the relatively limited benefit.

**Comment by bardiharborow** [comment]
I'm sure that this is suitable for some codebases, but we likely will not be adopting this. Even if we were, it's too late in the v4 release cycle to be making such a huge breaking change for the relatively limited benefit.
