### ISSUE TITLE
Error jQuery must be included before Bootstrap's JavaScript

### ISSUE THREAD

**Issue by alexey2baranov** [twbs/bootstrap#21790]
I'am very new in Bootstrap. So my step by step
1. install bottstrap as written hire https://v4-alpha.getbootstrap.com/getting-started/download/#npm
2. install jquery by `npm i jquery`
3. write a code 
```javascript
import $ from 'jquery'
require('bootstrap')
```
4. run it on webpack-dev-server ` npm run dev `
5. And finally get error

> Uncaught Error: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
>     at eval (eval at <anonymous> (app.js:690), <anonymous>:8:9)
>     at Object.<anonymous> (app.js:690)
>     at __webpack_require__ (app.js:556)
>     at fn (app.js:87)
>     at eval (eval at <anonymous> (app.js:684), <anonymous>:17:1)
>     at Object.<anonymous> (app.js:684)
>     at __webpack_require__ (app.js:556)
>     at fn (app.js:87)
>     at Object.<anonymous> (app.js:587)
>     at __webpack_require__ (app.js:556)

'

**Comment by CyrilWork** [comment]
I think bootstrap uses the `<script>` tag pattern for modules . Put your own javascript at the end script as in the example here https://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start in another tag. use the global variables

**Comment by alexey2baranov** [comment]
hmmmm... old scool scripting in 2017 year? doesn't bootstrap 4 support commonjs or es6 importing?

i suppose if  my some module use jquery it will be included in webpack boundle and another version of jquery will be at the end of body tag just for bootstrap works. so i will get double included jquery library on page. I think it thould be another way for including bootstrap into webpacked projects

**Comment by IamManchanda** [comment]
I agree with @alexey2baranov

**Comment by DavidStrada** [comment]
@alexey2baranov Bootstrap in most of it's plug-ins relay on having $/jQuery available globally so that's why you get that message, what you could try is making jQuery available globally and avoid this message, I know it's a dirty hack but until they start including their dependencies I'm afraid is your only option.

e.g.

`import $ from "jquery"`
`window.jQuery = $`
...

**Comment by DavidStrada** [comment]
Also given that you're using webpack as a work around you could try this.
``` js
new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery",
    "window.jQuery": "jquery"
})
```

[Wepack Docs](https://webpack.github.io/docs/shimming-modules.html)

**Comment by christianirack** [comment]
Testing with this 

import jquery from 'jquery'
window.jQuery = jquery
require('bootstrap')

**Comment by alexey2baranov** [comment]
Do same with Teather and it will work

7 мая 2017 г. 1:07 PM пользователь "Christian Irack" <
notifications@github.com> написал:

**Comment by Johann-S** [comment]
Now we have a doc on how to use Bootstrap with Webpack : https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/webpack.md

**Comment by rolele** [comment]
@Johann-S The doc is not rendered well. I see all the `{% highlight js %} ` commands.

**Comment by wolfy1339** [comment]
@rolele that's not the compiled docs. That's the source.

**Comment by anarerdene** [comment]
Also demo links not working.

**Comment by peterbarraud** [comment]
Hey does anyone else get this error:
`Uncaught Error: Bootstrap dropdown require Popper.js`
So I do
`require('popper');`
And get this error:
`Cannot find module 'rijs.resdir' from 'C:\Users\barraud\Documents\tech\browserify-prototyping\rapo-browserify-part-2-external-css\node_modules\popper\dist'`

**Comment by Johann-S** [comment]
Popper.js should be available in the Window scope so you should do : 
`window.Popper = require('popper')`

**Comment by peterbarraud** [comment]
Thanks for the super quick response but it still gives the same error. The includes in my file are as such:
```
const $ = require('jquery');
window.jQuery = $;
window.Popper = require('popper')
require('bootstrap');

```

**Comment by Johann-S** [comment]
be sure to use the last release of Popper.js (1.12.5) not the one required by the beta 1 (1.11.0)

**Comment by peterbarraud** [comment]
When I run `npm -v popper` it shows `4.2.0`. What is that supposed to mean?

**Comment by Johann-S** [comment]
Because the package name is `popper.js` 😉

**Comment by peterbarraud** [comment]
Thanks much @Johann-S . It now works perfect :)
