### ISSUE TITLE
pagination should be `display: inline-flex` 

### ISSUE THREAD

**Issue by gthomas-appfolio** [twbs/bootstrap#21797]
In older versions and alpha releases, the pagination component was `display: inline-block`, and allowed you to left/center/right align inside columns.

    <div class="row">
      <div class="col-sm-4">...</div>
      <div class="col-sm-8 text-right">
        <ul class="pagination">
          ...
        </ul>
      </div>
    </div>

With the change to flex box, pagination is now `display: flex` : https://github.com/twbs/bootstrap/blob/v4-dev/scss/_pagination.scss#L2

and I'm unable to align it.

Changing to `display: inline-flex` seems to behave correctly, see example here:

https://jsfiddle.net/3xeadpde/

**Comment by vanduynslagerp** [comment]
This because Bootstrap switched to flexbox in alpha 6.
You can the (flex utilities)(https://v4-alpha.getbootstrap.com/utilities/flexbox/#justify-content) to align content.

Here your example with `justify-content-end` on the `pagination` element.
https://jsfiddle.net/3xeadpde/1/

`text-right` will work only for text.

**Comment by gthomas-appfolio** [comment]
Thanks, flex is not a problem, it's that pagination used to be inline, and now it's a block basically.  `text-*` works for inline components (buttons, etc) and like pagination used to be.  
The issue with `justify-content-end` is you have to specify that on the component instead of the column.

**Comment by gthomas-appfolio** [comment]
Looks like there is a `d-inline-flex` utility that I can add to the pagination usages, I'll try that and close for now, thanks.
