### ISSUE TITLE
list-group-item's with badges break at narrow widths

### ISSUE THREAD

**Issue by philgyford** [twbs/bootstrap#21792]
In v4-alpha-6, `badge`s in `list-group-item`s fall below the item's text at narrow widths and/or if the the text is fairly long.

e.g., using this code from the docs, but with some extra text added to the first item:

```
<ul class="list-group">
  <li class="list-group-item justify-content-between">
    Cras justo odio cras justo odio cras justo odio
    <span class="badge badge-default badge-pill">14</span>
  </li>
  <li class="list-group-item justify-content-between">
    Dapibus ac facilisis in
    <span class="badge badge-default badge-pill">2</span>
  </li>
  <li class="list-group-item justify-content-between">
    Morbi leo risus
    <span class="badge badge-default badge-pill">1</span>
  </li>
</ul>
```

It looks like this at a narrow width:

![screen shot 2017-01-20 at 17 23 30](https://cloud.githubusercontent.com/assets/66670/22158767/c8eae910-df35-11e6-8ab2-860c381c2058.png)

Wouldn't it be better for the badge to stick to the right-hand edge of the `list-group-item` in such cases?

(Safari 10.0.2, MacOS 10.12.2.)

**Comment by Quy** [comment]
Adding `.flex-nowrap` to `<li class="list-group-item flex-nowrap justify-content-between">` appears to fix the issue. If this is an ideal solution, I will do a pull request.

**Comment by mdo** [comment]
Since this is solved with a utility class, closing out.
