### ISSUE TITLE
Flex positioning of items with different widths

### ISSUE THREAD

**Issue by bluesurfer** [twbs/bootstrap#21808]
Consider this code from the [docs](https://v4-alpha.getbootstrap.com/utilities/flexbox/#justify-content):
```
<div class="d-flex justify-content-between bd-highlight mb-3">
      <div class="p-2 bd-highlight">Flex item</div>
      <div class="p-2 bd-highlight">Flex item</div>
      <div class="p-2 bd-highlight">Longer Longer Flex item</div>
</div>
```
I would like to always keep the second item centered even if the third (or the first) item is wider. 
I'm trying to make a `navbar` with this layout but I can't find a way to keep the central item centered regardless of the others.

**Comment by mdo** [comment]
Regrettably, that's just not possible with flexbox alone. The only way to accomplish that is forcing equal width on the first and last elements, or using absolute positioning. [Here's a demo of using absolute position and flex styles.](https://jsbin.com/gejexeq/edit?html,css,output) Please bear in mind, however, that this isn't bulletproof and might cause other issues.
