### ISSUE TITLE
An input is in focus after the click on an empty space.

### ISSUE THREAD

**Issue by p-chaikouski** [twbs/bootstrap#21818]
Bootstrap v3.3.7.
Bug reproduced in the case when input.form-control use inside .row.
When clicking on an empty space on left and bottom from an input, the focus passes to input. (Please, see test cases link for more information)

- Operating system and version: Windows
- Browser and version: Chrome
- Reduced test cases and potential fixes: [CodePen](http://codepen.io/anon/pen/dNWEQE)

**Comment by bardiharborow** [comment]
Note that [support for v3 has mostly ceased](https://github.com/twbs/bootstrap/issues/20631). Please let us know if this issue affects v4.

**Comment by p-chaikouski** [comment]
No, this issue not affects v4. 
In the v4 do not need to use a clearfix, through the use of flexbox for layout.

**Comment by mdo** [comment]
Closing given v3's development status.
