### ISSUE TITLE
possibility of using bootstrap 4 CSS + bootstrap 3 JS

### ISSUE THREAD

**Issue by ibtrey** [twbs/bootstrap#21817]
Not so much an issue, more of a general question I think is worth asking. Currently it seems the JS in Bootstrap 4 kills a few things, (modals, popups etc. seem to be worse hit).

The changes in Bootstrap 4 seem to mean having to edit a lot of code, and in a large code base that task is mammoth. What would be the pros / cons of using Bootstrap 4 purely for css?

**Comment by patrickhlauke** [comment]
Bootstrap 4 is still in alpha. As such, it's not deemed to be fit for production environment / usage yet by the team. If you're planning to now use it before it's ready, AND use it in a way that's not intended (by trying to use BS 3 JS on top of it), then i'm afraid you'll have to ask that question on StackOverflow or similar, as it's beyond the scope of what we can help with here. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
