### ISSUE TITLE
Wrong documentation for order utility

### ISSUE THREAD

**Issue by hultberg** [twbs/bootstrap#21810]
Hello,

I noticed while reading about the flexbox order utility that the docs state there are several responsive utility classes, like: `.order-first`, `.order-last` and so on. However, the actual classes are named `.flex-first` and `.flex-last`. The doc in question: https://v4-alpha.getbootstrap.com/utilities/flexbox/#order

Opened a PR correcting the docs: #21811 

I'm not sure if this is an issue with the docs, in case `.order-*` was ment to be the actual classes or that the docs are in fact wrong. 😄

**Comment by Quy** [comment]
Duplicate of #21739

**Comment by hultberg** [comment]
@Quy Damit, I was not able to find any duplicate, thanks for the info! Closing in favour for #21739
