### ISSUE TITLE
Grunt with the latest autoprefixer

### ISSUE THREAD

**Issue by bangzek** [twbs/bootstrap#21819]
autoprefixer just releases version 6.7 with support for `flex-flow: row`.

So if you build with fresh npm install there will be additions:
```
+  -webkit-box-orient: horizontal;
+  -webkit-box-direction: normal;
```
for every `flex-flow: row`

Currently the `dist/` in the repo built with the previous version of autoprefixer.

**Comment by bardiharborow** [comment]
@mdo run `npm update` locally and then you can close this. <3
