### ISSUE TITLE
What's wrong with the cursor the buttons?

### ISSUE THREAD

**Issue by afuno** [twbs/bootstrap#21823]
Why does not change the cursor when I point the arrow on the button?
http://v4-alpha.getbootstrap.com/components/buttons/#examples

Must be this: { cursor: pointer }
But instead, I have: { cursor: default }

**Comment by browner12** [comment]
if you do a quick search in the issues for 'button cursor' you'll find this issue: https://github.com/twbs/bootstrap/issues/21479

with the discussion about this.
