### ISSUE TITLE
Fail on the last Build

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#21827]
Fail on ``saucelabs-qunit:all`` see :
https://travis-ci.org/twbs/bootstrap/jobs/194740775

/CC : @mdo (Because the build failed on your commit sorry ^^) @bardiharborow

**Comment by mdo** [comment]
Ah, that's just Travis/Sauce being dumb. Happens a *ton* on PRs before I merge. I'll restart the job and it should pass shortly. Thanks for the heads up!
