### ISSUE TITLE
Rename .bg-faded to .bg-light?

### ISSUE THREAD

**Issue by Quy** [twbs/bootstrap#21822]
When I see `*-inverse`, I think of its counterpart as `*-light` (ie. `navbar-inverse` and `navbar-light`). It might be too late, but would it make sense to rename `.bg-faded` to `.bg-light` for consistency sake?

**Comment by vishai12345** [comment]
no

**Comment by dongepulango** [comment]
Should be `*-dark` and `*-light`

**Comment by mdo** [comment]
This was done in #22836
