### ISSUE TITLE
.badge-pill with $enable-rounded:false is broken

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#21839]
My understanding for flag $enable-rounded is that we want to reduce css size (if we don't want rounded buttons, etc).
But .badge-pill is special case and border-radius should be added unconditionally (not using @include border-radius but plain border-radius).

**Comment by mdo** [comment]
I don't think this should be unconditional and live outside the variable; it should respect it like the rest. Thanks though!

**Comment by coliff** [comment]
I agree that `.badge-pill` should always have a border-radius. Hope this could be re-considered for v5.

But for anyone looking for a solution to this without adding/changing any additional CSS, you can add the class `.rounded-pill` to your badge which adds `border-radius: 50rem!important;`

**Comment by ffoodd** [comment]
@coliff it's very easy in both v4 and v5 to work around `$enable-rounded`: simply duplicate your value in `@include border-radius()`.

This mixin has a second optional argument called `$fallback-border-radius` which applies `border-radius` when  `$enable-rounded` is `false`.
