### ISSUE TITLE
Tabs navigation with <button> instead of <a>

### ISSUE THREAD

**Issue by stephenbe** [twbs/bootstrap#21833]
I noticed in bootstrap 3 and 4 that `<a>` tags are used for the top navigation. 
http://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior

On the  WAI-ARIA Authoring Practices they don't mention that you need to use the `<button>`, but in the one example they list, it does use the `<button>`.

https://www.w3.org/TR/wai-aria-practices/#tabpanel
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs.html

Any reason why you use `<a>` instead of the `<button>` ?

**Comment by patrickhlauke** [comment]
as they're given a `role="tab"` which overrides their link-/button-like nature, it's functionally irrelevant which elements are used. you could even use `<span>` elements, as long as they had the correct `role` and behavior...
