### ISSUE TITLE
bs 4 alpha-6: navbar-inverse-toggler-bg and navbar-light-toggler-bc cause browser to stop interpreting css

### ISSUE THREAD

**Issue by abidibo** [twbs/bootstrap#21838]
Bootstrap 4 alpha-6. Ubuntu 16.04 LTS.

I import bootstrap scss inside my entry point styles.scss this way:

    // Core variables and mixins
    @import 'variables'; // overwrite bs vars
    @import '../vendor/bootstrap/scss/bootstrap';

    @import 'main';
    @import 'navbar';`

I use it in a django project using django-pipeline as assets manager. Everything compiles as expected, using sass compiler. The problem is with the generated css.

In firefox 50.1.0 comparing the css file generated and the css file interpreted (seen through firebug in the css tab) I can see these things:

Generated css:

    .navbar-light .navbar-toggler {
      border-color: rgba(0, 0, 0, 0.1); }
    .navbar-light .navbar-toggler-icon {
      background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5")' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E"); }
    .navbar-light .navbar-text {
    // etc....

while in the interpreted css copied from firebug I see that the css gets truncated:

    .navbar-light .navbar-toggler {
        border-color: rgba(0, 0, 0, 0.1);
    }
    .navbar-light .navbar-toggler-icon {
    }

So the `.navbar-light .navbar-toggler-icon` brokes in some way the css interpretation.

In Chromium Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit), in the developer toolbar I can see the css source, not truncated, but the result is the same.

__Which is the result?__

The result is that all css rules below that point are ignored.

The problem is caused by these 2 rules in bootstrap/_variables.scss:

    $navbar-light-toggler-bg: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='#{$navbar-light-color}' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E"), "#", "%23") !default;

    $navbar-light-toggler-bg: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='#{$navbar-light-color}' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E"), "#", "%23") !default;

I solved it overwriting the two variables definitions in my variables.scss this way:

    $navbar-inverse-toggler-bg: MYCUSTOMRULE;
    $navbar-light-toggler-bg: MYCUSTOMRULE;`

Now the rules below are correctly interpreted.

**Comment by gertsteyn** [comment]
This is a symptom of the issue I described in #21879

**Comment by gertsteyn** [comment]
You'll notice the `rgba(0, 0, 0, 0.5)` gets changed to `rgba(0, 0, 0, 0.5")` by the preprocessor - note the misplaced apostrophe.

I suspect this is because the brackets need to be encoded...

**Comment by mdo** [comment]
This sounds like an error on the Django side; this compiles fine on our end.
