### ISSUE TITLE
Visual difference between disabled and active btn-secondary is very low

### ISSUE THREAD

**Issue by denormative** [twbs/bootstrap#21834]
I've just been working with a lot of "secondary" buttons and have noticed that there's actually very little contrast between the active and disabled variants. It's not as noticeable when done side-by-side, but I've found myself having to mouse over buttons to confirm they're disabled rather then visually checking.

https://jsbin.com/hidamelina/edit?html,output

Firefox on linux (centos7) seems to be better due to thicker default font choice in comparison to chrome.

![chrome-secondary](https://cloud.githubusercontent.com/assets/3412429/22272774/90841968-e2df-11e6-91fb-7c61f533bca5.png)

![firefox-secondary](https://cloud.githubusercontent.com/assets/3412429/22272778/98b5f1e2-e2df-11e6-9c9f-d2ec93d86bf4.png)

Not sure what could be done to increase the contrast. Making the disabled font even lighter would help, but that would probably decrease readability. Alternatively perhaps making the inner-border of the active btn-secondary thicker would improve the contrast

**Comment by janaagaard75** [comment]
I think the issue is that the secondary button is an outline button by default. Making it a filled button like the others solves the issue. The design that I am thinking of is apparently already included in the source, as a button without any modifier, i.e. simply `class="btn"`.

http://embed.plnkr.co/lRsSbcAvhEhkmi4TGgTw/

**Comment by janaagaard75** [comment]
Is it possible to get an official comment on this? I wouldn't mind making a pull request to change this, but would, of course, like to know up front, if there is a chance that this would get accepted.

**Comment by mdo** [comment]
No planned changes here for now; we have the same styles applied to all our buttons. I know it's not perfect, but we'll want to revisit them all together and limit the one-off styles.

**Comment by janaagaard75** [comment]
>  I know it's not perfect, but we'll want to revisit them all together and limit the one-off styles.

Will gladly help when to get to that. :)
