### ISSUE TITLE
Why Jumbotron padding bigger on the vertical?

### ISSUE THREAD

**Issue by bangzek** [twbs/bootstrap#21837]
In the v3 the vertical padding is smaller than horizontal, but combined with _margin-top_ on `h1` gives a rather squared spacing on the top left margin.

But currently on v4 the vertical padding is twice the size of horizontal padding and no _margin-top_ on `h1` result in heavier vertical spacing rather than squared.

**Comment by mdo** [comment]
Just a change in how we wanted to space those elements. We removed most top margins from our headings and tried to simplify these rules so there is one way to space vs multiple elements building on one another.

**Comment by bangzek** [comment]
If the intention just to change the how and not change the perceived appearance, the vertical padding should be the same with the horizontal padding.
