### ISSUE TITLE
`background-clip` css property inconsistent in input groups.

### ISSUE THREAD

**Issue by Nikita240** [twbs/bootstrap#21849]
Looking at the example input-group in the [navbar docs](https://v4-alpha.getbootstrap.com/components/navbar/#forms):

![image](https://cloud.githubusercontent.com/assets/6479817/22324851/436e45be-e360-11e6-949d-4df0576ade68.png)

We can see the `input.form-control` gets assigned `background-clip: padding-box;`. This is intended behavior as of https://github.com/twbs/bootstrap/commit/c3e4cbdfb0eaff43db4de6b4df045f364e5500d2.

![image](https://cloud.githubusercontent.com/assets/6479817/22324912/83bc23a2-e360-11e6-9dfd-ba8bfa18fe74.png)

However, the `span.input-group-addon`, still has the default `background-clip: border-box;`.

![image](https://cloud.githubusercontent.com/assets/6479817/22324928/99f1287a-e360-11e6-94b2-09dcb7c6d9e7.png)

This may go unnoticed, but it causes unintended behaviour when you change the background color. Here is what the before mentioned example looks like when you change it from `<nav class="navbar navbar-light bg-faded">` to `<nav class="navbar navbar-inverse bg-inverse">`

![image](https://cloud.githubusercontent.com/assets/6479817/22325005/0d05c6a4-e361-11e6-9ea8-b05a2d9c6acc.png)

Recommended solutions:

Either revert https://github.com/twbs/bootstrap/commit/c3e4cbdfb0eaff43db4de6b4df045f364e5500d2, or change `input-group-addon` to `background-clip: padding-box;`.

**Comment by mdo** [comment]
Basically the same as #21098, so closing as a dupe. Definitely need an answer for this so I'll be aiming to address it in Beta 1.

**Comment by Nikita240** [comment]
@mdo my bad for not spotting the dupe.
