### ISSUE TITLE
glyphicon glyphicon-request

### ISSUE THREAD

**Issue by AlaskanDesigns** [twbs/bootstrap#21844]
glyphicon glyphicon-canine, glyphicon glyphicon-cat, glyphicon glyphicon-rabbit, glyphicon glyphicon-goat/sheep, glyphicon glyphicon-bird, glyphicon glyphicon-fish, glyphicon glyphicon-snake...

I really only need a dog, but there's so much potential in silhouettes!
<hr />
When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by bkdotcom** [comment]
Not gonna happen

a) v3 development is no more.
b) https://v4-alpha.getbootstrap.com/migration/#components

> Dropped the Glyphicons icon font. If you need icons, some options are:
the upstream version of [Glyphicons](https://glyphicons.com/)
> * [Octicons](https://octicons.github.com/)
> * [Font Awesome](http://fontawesome.io/)

**Comment by mdo** [comment]
Yup, we're not working on v3 actively right now and Glyphicons is an external project that we shipped with Bootstrap. You can find the site and creator and make more requests there if you need.

**Comment by httpete** [comment]
It's a smart move to not include glyphicons in BS4. These are separate concerns.
