### ISSUE TITLE
.btn-outline-secondary defaults to reboot color on :focus

### ISSUE THREAD

**Issue by psorensen** [twbs/bootstrap#21843]
There is no explicit color set for the active state of a the btn-outline-secondary focus state. It uses the color set by reboot.

![screen shot 2017-01-25 at 9 22 06 am](https://cloud.githubusercontent.com/assets/6152801/22301707/cf620c8e-e2e0-11e6-84b2-35d7a26b9f5e.png)

**Comment by mdo** [comment]
Pretty sure this was addressed with #21633.
