### ISSUE TITLE
Modal unexpected behaviour - class modal-open removed and padding-right issue

### ISSUE THREAD

**Issue by revolutionart** [twbs/bootstrap#21840]
Hi, Ive noticed a problem with launching modals, If you launch a modal from within a modal the class .modal-open is removed from the body and if you dismiss the modals padding-right 17px; isn't removed from the body, wich causes your layout to shift to the left. Workaround is a little bit of CSS. However i believe this is unexpected behaviour. It worked fine in bootstrap 3.

I have reproduced the bugs and commented it aswell:
http://codepen.io/revolutionart/pen/YNxjgw

**Comment by Johann-S** [comment]
Related to this PR : https://github.com/twbs/bootstrap/pull/18441

**Comment by revolutionart** [comment]
Ah, i see i haven't been search well enough. Glad it is being fixed. I guess this one can be closed 👍 
Great work everyone!
