### ISSUE TITLE
Why need "nav-item" class for every menu item

### ISSUE THREAD

**Issue by leonardo1024** [twbs/bootstrap#21847]
Hi, I think that using  "nav-item"  for each menu item makes code too long. Everybody prefer clean code isn't it?

**Comment by vanduynslagerp** [comment]
See PR #21807

**Comment by mdo** [comment]
That PR doesn't answer the question or provide any backstory.

In short, we're taking the class-based approach to all our selectors to limit their scope and provide a more flexible environment for building sites/apps without added headaches of CSS inheritance. In v3 we used children selectors that restricted your markup structure. With v4 and our emphasis on classes, you can basically use whatever markup you want.
