### ISSUE TITLE
carousel slide class not found

### ISSUE THREAD

**Issue by jluisgarcia** [twbs/bootstrap#21841]
Checking this example in the Docs:
http://v4-alpha.getbootstrap.com/components/carousel/#with-indicators
You can see "slide" class at the very top of the code block.

However this class is NOT found in the provided CSS file, here:
http://v4-alpha.getbootstrap.com/getting-started/download/#bootstrap-css-and-js
Thanks.

**Comment by josmaissan** [comment]
@jluisgarcia It's at least in the recent javascript file (bootstrap.js)
`var action = typeof config === 'string' ? config : _config.slide;`

**Comment by jluisgarcia** [comment]
thanks, i didnt know it was just for JS functionality, not styling.
case closed.
