### ISSUE TITLE
Navbar logo and items get displayed in new lines.

### ISSUE THREAD

**Issue by rahulsharma20** [twbs/bootstrap#21858]
I just moved to bootstrap 4 and I am having a problem with the navbar.
All the items in navbar come in a new line

Here's my html :-

        <div class="container-fluid">
          <nav class="navbar navbar-light bg-faded">
            <a class="navbar-brand pull-xs-left" href="#">Logo</a>
            <ul class="nav navbar-nav pull-xs-right">
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 3</a>
                </li>
            </ul>
          </nav>
        </div>

The logo and items are getting broken into new lines.
Is there something wrong with my html or it an actual issue I'm not sure.

I have also attached a screenshot with the inspector so you can check better.

![screen shot 2017-01-27 at 5 18 02 pm](https://cloud.githubusercontent.com/assets/25361829/22369997/14f5cd96-e4b5-11e6-90ba-9c019223d37a.png)

I have no css written at my end just the bootstrap.min.css is all thats included.

Here's the bootstrap version :-

        /*!
         * Bootstrap v4.0.0-alpha.6 (https://getbootstrap.com)
         * Copyright 2011-2017 The Bootstrap Authors
         * Copyright 2011-2017 Twitter, Inc.
         * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
         *//*! normalize.css v5.0.0 | MIT License | github.com/necolas/normalize.css */

**Comment by mdo** [comment]
The HTML and CSS for the navbar in v4 is much different than that of v3's. Be sure to update to the latest HTML alongside the latest CSS.
