### ISSUE TITLE
[Issue Template] Simplify template

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#21852]
Currently our ``Issue template`` is a list of best practices before posting an issue, but it doesn't help mainteners to find quickly the kind of issue.

It would be convinient to have something like this : 

| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| Question ? | yes/no
| Bootstrap version  | x.y.z

For me this list (https://github.com/twbs/bootstrap/blob/v4-dev/ISSUE_TEMPLATE.md) should be included in the Contributing section

I open a discussion here, to share ideas and to have differents feedbacks

**Comment by mdo** [comment]
I'm in favor of a simpler template. A more succinct bulleted list of what we need answers to seems like a step in the right direction.

**Comment by Johann-S** [comment]
First of all we need to know what information are needed.

IMO we should know : 
- Bootstrap version
- What kind of issue (Bug report, Feature request, question)

I'm in favor of a table because it's easy to complete and visually speaking it's better than a list (that's my opinion 😄 )

**Comment by mdo** [comment]
Working with tables in Markdown is terrible though :). Regardless of format, we need:

- Bootstrap version
- For bugs, OS/browser version
- For bugs, reduced test case via jsbin

We can easily deduce what's a bug, feature, or question by the scope of the issue. Don't need anything in the issue body for that I think.

**Comment by mdo** [comment]
Punting on this for now :D.
