### ISSUE TITLE
Tooltip on svg misplacement after scrolling the page

### ISSUE THREAD

**Issue by pm-Egor-Genning** [twbs/bootstrap#21855]
Issue happens because:
The Element.getBoundingClientRect() method returns the size of an element and its position relative to the **viewport**.

Need to extend tooltip position with:

```
 Tooltip.prototype.getPosition = function ($element) {
    $element   = $element || this.$element

    var el     = $element[0]
    var isBody = el.tagName == 'BODY'
   
    var elRect    = el.getBoundingClientRect();
    elRect = $.extend({}, elRect, {
        top: elRect.top + window.pageYOffset, 
        left: elRect.left + window.pageXOffset
   });
... e.t.c
```

**Comment by sjd78** [comment]
This is the same as issue #20381 (Positioning error on SVG tooltips/popovers when scrolled, then clicked) that was caused by PR #20313 for issue #20280 (Unit test for tooltip on SVG element fails in Chrome+Safari under jQuery 3).
