### ISSUE TITLE
The ml-auto and mr-auto utility classes are not documented

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#21853]
The `.ml-auto` and `.mr-auto` utility classes are not documented.

Looking at the source code I figured out this set the margin-left to auto and margin-right to auto respectively.

**Comment by josmaissan** [comment]
I had found them here http://v4-alpha.getbootstrap.com/utilities/flexbox/#auto-margins

**Comment by vanillajonathan** [comment]
Yes, but they are only in the code, nowhere are they described in the documentation.

**Comment by mdo** [comment]
Given @josmaissan's comment, they are in fact in the documentation. These utilities are only useful for flexbox layouts, so that's only where they appear.

**Comment by vanillajonathan** [comment]
Yes, they are in the documentation but the class names are only referenced in the example.

**Comment by danger89** [comment]
So they are actually not documented.. It's like writing code, and saying .. it's documented. It's just not explained.

**Comment by cjke** [comment]
Hmm, that isn't really documentation. I double took and though perhaps `mr-auto` was Elliot's bootstrap cousin - alas, it was not. 

Google results for "bootstrap mr-auto" return the navbar page, the flexbox page and this issue thread. 

Can PR if you guys are open to it - but you already have a stack in your backlog

**Comment by vanillajonathan** [comment]
Yes, that page explains it.
Maybe it could be linked from the http://v4-alpha.getbootstrap.com/utilities/flexbox/#auto-margins page?

**Comment by danger89** [comment]
Yea indirectly. Guessing "with margin-right: auto or margin-left: auto" is equal to the mr-auto in the example. But this explanation can maybe improved a bit.

**Comment by MeganGong** [comment]
Hey, look this: https://v4-alpha.getbootstrap.com/utilities/spacing/
m - for classes that set margin
r - for classes that set margin-right or padding-right

so, I think your guess is right

**Comment by josmaissan** [comment]
@MeganGong That is already a year ago and v4 has already shipped, now I would point to: https://getbootstrap.com/docs/4.0/utilities/flex/#auto-margins and https://getbootstrap.com/docs/4.0/utilities/spacing/ 
🤓
