### ISSUE TITLE
we can add prefix for container

### ISSUE THREAD

**Issue by pixieaka** [twbs/bootstrap#21869]
we can add prefix for container like

container-lg , container-md, container-xl

when screen get small the container will be fluid container. it just idea 👍 

because sometimes we need the margins  just for big screen .

**Comment by nextgenthemes** [comment]
If I understand correctly then I am against this because this #22008

**Comment by mdo** [comment]
Punting on this for now.

**Comment by pixieaka** [comment]
Any update on this ?? ,, All the best.
