### ISSUE TITLE
dropdown on navbar doesn't show the full text

### ISSUE THREAD

**Issue by markoverflow** [twbs/bootstrap#21863]
the dropdown doesn't completely show it's text when it was in the right side of the navbar

![nav](https://cloud.githubusercontent.com/assets/23117722/22394075/7b26cec6-e550-11e6-8cb5-9563f0debcae.png)

http://codepen.io/anon/pen/wgPryR

**Comment by smertnik77** [comment]
<a class="dropdown-item" href="#">Something else<br>here</a>

**Comment by markoverflow** [comment]
@smertnik77  i notice that the problem is not really the long text, the problem is that the margin doesn't consider the width of the drop down container. when i add another nav item after dropdown, it shows the whole container.

**Comment by mdo** [comment]
Change the alignment of the menu with `.dropdown-menu-right`. https://v4-alpha.getbootstrap.com/components/dropdowns/#menu-alignment
