### ISSUE TITLE
Modal handleUpdate is protected

### ISSUE THREAD

**Issue by ashleydw** [twbs/bootstrap#21868]
From the docs:

> If the height of a modal changes while it is open, you should call $('#myModal').data('bs.modal').handleUpdate() to readjust the modal’s position in case a scrollbar appears.

In the source the method is protected:

https://github.com/twbs/bootstrap/blob/045888fa3887f5e65658499da11c8ad737222759/js/dist/modal.js#L394

**Comment by Johann-S** [comment]
You can call call ``_handleUpdate`` by the following lines : 

```javascript
$('#myModal').modal('_handleUpdate')
// or
$('#myModal').data('bs.modal')._handleUpdate()
```

We should update the documentation
