### ISSUE TITLE
Breakpoints in each docs example

### ISSUE THREAD

**Issue by reardestani** [twbs/bootstrap#21864]
Is it possible to add breakpoints as buttons in docs example sections (http://take.ms/ec3USu) so we can easily resize each example section easily to see how each example work in different breakpoints.

Currently we have to manually resize the browser to see how each example work in different devices.

**Comment by mdo** [comment]
Not currently, and no plans to do this. Chrome's developer tools handle this quite well, and other browsers have similar options. Not something I see us addressing.
