### ISSUE TITLE
navbar-light-toggler-bg contains invalid URL

### ISSUE THREAD

**Issue by gertsteyn** [twbs/bootstrap#21879]
in scss/_variables.scss line 626:

`$navbar-light-toggler-bg: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='#{$navbar-light-color}' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E"), "#", "%23") !default;`

The `{$navbar-light-color}` sections results in ( ) being put into the URL unencoded, as far as I know this is invalid and actually results in an error in the preprocessor I use (django-compressor)

Am I correct in my assumption that this is invalid?

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/issues/21838#issuecomment-277488207.

**Comment by mrobit** [comment]
Not to beat a dead horse, but I was experiencing this issue with using the roots/sage theme and I was intermittently experiencing similar issues when compiling via webpack. What "fixed" it for me (and I don't know if this will come up again or not) was replacing the single quotes within the encoded SVG with an escaped double quote, i.e.

```
$navbar-light-toggler-bg: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox=\"0 0 32 32\" xmlns=\"http://www.w3.org/2000/svg\"%3E%3Cpath stroke=\"#{$navbar-light-color}\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-miterlimit=\"10\" d=\"M4 8h24M4 16h24M4 24h24\"/%3E%3C/svg%3E"), "#", "%23") !default;
```

Just in case someone comes along this issue via Google and finds this, figured I'd post it here.

**Comment by RTC1** [comment]
Running yarn upgrade fixed this for me.

**Comment by MichalSchwarz** [comment]
I have the same problem now, but don't know why. Double quoting both variables works fine `stroke=\"#{$navbar-light-color}\"` . It started from beta.3, beta.2 is working. There is only changes in whitespaces. I'm using "webpack": "^3.10.0" and "sass-loader": "^6.0.6"
