### ISSUE TITLE
Container's margin on Navbar for mobile devices centers both items.

### ISSUE THREAD

**Issue by CameronCT** [twbs/bootstrap#21870]
When you put a container in your `nav` it does what it's supposed to do. However, if you use it on any mobile devices the `.navbar-brand` and the `.navbar-toggler` gets centered. And this is because Mobile devices are still trying to use `margin-left: auto` and `margin-right: auto`

How to fix this? Very simple, all you do is reset the `margin-left` and `margin-right` for the `.navbar-toggleable` that has it enabled . Which in this case is `991px`, but should be applied from XS to MD devices.

```css
@media (max-width: 991px)
	.navbar-toggleable-md > .container
	    padding-right: 0
	    padding-left: 0
	    margin-left: 0
	    margin-right: 0
```

**Comment by melmsie** [comment]
+1

**Comment by browner12** [comment]
this is already fixed in another commit

https://github.com/twbs/bootstrap/commit/9cf235508d8ae881304877e0c4da3258c69de867

**Comment by CameronCT** [comment]
Didn't notice, thanks for letting me know!
