### ISSUE TITLE
tab-pane fade in active regression in Bootstrap 4 alpha 6.

### ISSUE THREAD

**Issue by mcc007** [twbs/bootstrap#21876]
The following pen works as expected.

https://codepen.io/jek/pen/BoWNRy

When loaded the first page shows the '...' when loaded. It is using the the following 

https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js

The following pen does not work

https://codepen.io/simonfarrow/pen/ygpObr

The only difference is this one uses
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js

Thank you in advance

**Comment by Quy** [comment]
Per [Alpha 6 ship list](https://github.com/twbs/bootstrap/issues/20939), `.in` has been renamed to `.show`:
> Renamed some .active, all .in, and all .open classes for our JavaScript powered components for more consistent naming. For example, instead it's now .collapse.show instead of .collapse.in and .show > .dropdown-menu instead of .open > .dropdown-menu to better communicate the visibility of elements.

**Comment by mcc007** [comment]
Thanks for the prompt reply  - I have closed the ticket as this the fix
