### ISSUE TITLE
Issue with the 'media-right' class

### ISSUE THREAD

**Issue by varghesep** [twbs/bootstrap#21873]
I observed this UI behavior when I was using the [Application Theme](http://themes.getbootstrap.com/products/application). This happens in all browsers.

The following is my HTML fragment. I expected the content inside the div element with the **media-right** style should be in single line. Right it now it wraps to multiple lines (_See the last picture_). I think the issue is that the **media-body** is 10000px.

I'm not sure is this a bug or should I use only **media-body** to align the test to the right?

![image](https://cloud.githubusercontent.com/assets/12233474/22404952/b5b6b91a-e600-11e6-9391-7435ec22689c.png)

```
<div class="card">
    <div class="card-header">
        <div class="container">
            <form class="form-inline">
...            </form>
        </div>
    </div>
    <div class="card-block">
        <div class="media-list media-list-users list-group">
            <a href="#" class="list-group-item">
                <div class="media">
                    <span class="media-left">
                        <img class="img-circle media-object" src="assets/img/avatar-fat.jpg">
                    </span>
                    <div class="media-body">
                        <strong>Jacob Thornton</strong>
                        <div class="media-body-secondary">
                            The quick brown fox jumps over the lazy dog
                        </div>
                    </div>
                    <div class="media-right">The quick brown fox jumps over the lazy dog</div>
                </div>
            </a>
        </div>
    </div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/12233474/22404889/b027dc0a-e5ff-11e6-85b0-8be6083dae0b.png)

**Comment by mdo** [comment]
This isn't the place to report bugs for the Bootstrap themes. Please use the support email for that.
