### ISSUE TITLE
nav-justified not working within navbar

### ISSUE THREAD

**Issue by robinchrist** [twbs/bootstrap#21874]
Hello,
It seems like nav-justified and nav-fill are not working together with navbar.
Example: https://jsfiddle.net/wq16antm/
Tested with Chrome 56.0.2924.76 on Ubuntu 16.04

The Bootstrap justified-nav example (http://v4-alpha.getbootstrap.com/examples/justified-nav/) seems to be pretty broken as it is permanently collapsed (shouldn't the whole toggle-stuff disappear when the screen is big enough?).
I just want justified pills within a fixed-top navbar collapsing at medium level...

**Comment by JasonAllenCorns** [comment]
@bardiharborow - I have been able to reproduce this, as well.

if you change from the ul/li schema for navs, and instead just use anchor tags like `<a href="#someBookmark" class="nav-item nav-link">IMPORTANT STUFF</a>`, the justification and fill classes work within navbar.  **BUT** if you do make this switch, then ScrollSpy doesn't work. 

I'm looking for related bugs for both of these issues, now, before I open one.

**Comment by mdo** [comment]
Fix for the justified navbar example is coming in #22230. It'll make use of the `.nav-justified` modifier, but also require `.w-100` because of the flex sizing.

**Comment by zfrenchee** [comment]
The need for `.w-100` to get this to work should be in the docs, no? I just ran into this.

**Comment by hebert-nr** [comment]
Agreed with zfrenchee.  Also noticing when using the w-100, once page is collapsed, the ul/li in the navbar still list horizontally instead of adjusting to vertical list
