### ISSUE TITLE
card-group should accept multirow

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#21878]
I want to use card-group with multirow.
I want for example 20 cards that are displayed in ex 5 rows (4 items per row) on lg and 10 rows (2 items per row) on md.
First and last item in a row should have rounded borders.
Is it possible? Will it be possible?

**Comment by adamjgomez** [comment]
I would like this functionality also.

**Comment by clindelof** [comment]
I could really use this functionality

**Comment by mdo** [comment]
With utilities and a bit of custom CSS, this is definitely possible. I won't be adding anything to the project core for this though at this time.
