### ISSUE TITLE
Firefox bug: Figures break grid

### ISSUE THREAD

**Issue by alienlebarge** [twbs/bootstrap#21886]
## Description

When using [Figures](http://v4-alpha.getbootstrap.com/content/figures/) in a grid, it doesn't fit the width of the container.

Here's a [Pen](http://codepen.io/alienlebarge/pen/apqvbm) to reproduce the bug

## Environment
- **Browser version**: [All firefox version](https://www.browserstack.com/screenshots/9fc68838c44e2e5f5b8a4b1a0f5085e231c923ad) [(.zip of screenshots)](http://d.pr/f/cnpB)
- **Bootstrap version**: 4.0.0-alpha.6

## Cause
The problem is caused by [the following code](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_images.scss#L32):
```css
.figure {
  // Ensures the caption's text aligns with the image.
  display: inline-block;
}
```

## Additional Info

```html
  <div class="row">
    
    <article class="col-md-6">
      <figure class="figure">
        <img src="..." class="figure-img img-fluid rounded" alt="...">
        <figcaption class="figure-caption">...</figcaption>
      </figure>
      <p>...</p>
    </article><!-- /.col-md-6 -->
    
    <article class="col-md-6">
      <figure class="figure">
        <img src="..." class="figure-img img-fluid rounded" alt="...">
        <figcaption class="figure-caption">...</figcaption>
      </figure>
      <p>...</p>
    </article><!-- /.col-md-6 -->

  </div><!-- /.row -->
```

![Firefox 45](https://cloud.githubusercontent.com/assets/611234/22461617/3fd54198-e7aa-11e6-8b91-a29229e4eed9.png)
![Chrome 55](https://cloud.githubusercontent.com/assets/611234/22461619/42099432-e7aa-11e6-81a9-d2f5e838b96d.png)

**Comment by alienlebarge** [comment]
I'll make a PR asap.

**Comment by mdo** [comment]
This renders fine for me in latest Firefox on Mac (v52).

<img width="1551" alt="screen shot 2017-03-19 at 7 12 12 pm" src="https://cloud.githubusercontent.com/assets/98681/24087114/fe4bed14-0cd7-11e7-885c-da2c76b52039.png">

**Comment by alienlebarge** [comment]
@mdo You are right, the problem is in Firefox 45 and older.
The latest one are ok

**Comment by rafalp** [comment]
45 is previous LTS ("ESR") for FF that Mozilla timetable says will be supported until June 13 this year. Thats something to keep on mind if you have users on it to support (eg. corporate) but then, you shouldn't be using BS4 in the first place if thats the case.

**Comment by mdo** [comment]
Closing as a won't fix.
