### ISSUE TITLE
Suggestion Responsive Helpers - Sizing

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#21887]
The sizing helpers are great, I have suggested them in the past and I am so glad you added them.
They need only one tweak, add responsiveness to them:
 * h-100 h-sm-75 h-md-50 w-100 w-sm-75 w-md-50

`<div class="h-100 h-sm-75 h-md-50 w-100 w-sm-75 w-md-50">Example</div>`

**Comment by mdo** [comment]
Thanks, but we'll pass for now. I don't see a huge value in this for our project.
