### ISSUE TITLE
Clarity in Flexbox Documentation

### ISSUE THREAD

**Issue by samirotiv** [twbs/bootstrap#21883]
I hope this is the right place to report an issue in the documentation. I am almost driving myself crazy trying to search for what "p-2" does.

I'm not a CSS developer. but I'm somewhat familiar with Bootstrap 3, and I'm going through the flexbox page in Bootstrap docs, and the class "p-2" has been applied all over. [https://v4-alpha.getbootstrap.com/utilities/flexbox/](https://v4-alpha.getbootstrap.com/utilities/flexbox/)

A Google search unfortunately won't help me find this.

Can somebody enlighten me, and can somebody add what it means to the documentation page? It would be ideal if every class in the documentation code was a clickable link that took the user to the relevant page.

I deeply apologize for annoying the contributors of this repo with this seemingly trivial problem, and advertising my ignorance and lack of expertise in Bootstrap.

Thanks a lot,
Samir.

**Comment by vanduynslagerp** [comment]
`p-2` is a custom Bootstrap class that is part of the spacing utilities. See [docs](https://v4-alpha.getbootstrap.com/utilities/spacing/). It sets a padding of `.5rem`.

For help/support of this kind, you should use StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by mdo** [comment]
> A Google search unfortunately won't help me find this.

As mentioned, it's one of our padding utilities. Next time, search the project's CSS instead of Googling for it :). No snark intended, but if it's a class that appears in our code snippets, there's a near 100% chance it's in our code.
