### ISSUE TITLE
data-toggle on two actions

### ISSUE THREAD

**Issue by kosmom** [twbs/bootstrap#21896]
For default is impossible set data-toggle for tooltips (on hover) and data-toggle for modal/popover/tab/dropdown (on click) events on one DOM element
To separate events "on hover" and "on click" i offer change default "data-toggle" attribute on "data-toggle-hover" and "data-toggle-click"
It will be obviously

**Comment by Joyrex** [comment]
Agreed - it was possible with 2.x and 3.x to have elements that have a popover/tooltip as well as having a click event to trigger a modal. I used `rel="tooltip"` or `rel="popover"`, and then `data-toggle` for modals.

**Comment by YodaDaCoda** [comment]
I think a better solution is to change the selector in Bootstrap's `dropdown.js`

from
`[data-toggle="dropdown"]`
to 
`[data-toggle~="dropdown"]`

See ref: [MDN: Attribute Selectors](https://developer.mozilla.org/en/docs/Web/CSS/Attribute_selectors)

**Comment by mdo** [comment]
Closing as stale and as a won't fix.
