### ISSUE TITLE
input-group addons and form-control-feedback

### ISSUE THREAD

**Issue by artnova-david** [twbs/bootstrap#21897]
Hi,
When using **.form-control-feedback** in an **.input-group**, the feedback control is not rendered on the next line like other form fields which are not marked with the input-group class (see image). Is this normal behavior?

![input-group](https://cloud.githubusercontent.com/assets/21141231/22552149/fef3816c-e957-11e6-90a6-a89fc29b6435.jpg)

I use: 
- Bootstrap: v4.0.0-alpha.6
- OS: Windows 10
- Browser:  Chrome 55.0.2883.87

Thanks.

**Comment by TheSharpieOne** [comment]
Posting an example html markup (or even a link to codepen, jsfiddle, plunker, or more) demonstrating this issue helps.
Here is an example of the markup I am using, based on the documentation, which do not have the issue.
http://codepen.io/TheSharpieOne/pen/YNaoxx?editors=1000
![image](https://cloud.githubusercontent.com/assets/664714/22561118/f14b6b1e-e944-11e6-866a-81b747e113f6.png)

Does you markup look like mine?

**Comment by artnova-david** [comment]
@TheSharpieOne 
Indeed, my markup was different from yours in that you added an extra div just below `<div class="col-sm-10">` where i added the input-group class to this div. But in the [documentation ](https://v4-alpha.getbootstrap.com/components/forms/#validation) where i copied the code this is not the case .

Thanks for your help
Kind regards

**Comment by TheSharpieOne** [comment]
Glad to help.

Also, That is the same documentation I used. I copied that and replaced the `<input ... />` with the snippet from the [input group documentation](https://v4-alpha.getbootstrap.com/components/input-group/#basic-example)
