### ISSUE TITLE
CSS classes from own SCSS files will be overwritten.

### ISSUE THREAD

**Issue by henningn** [twbs/bootstrap#21898]
I try to to build Bootstrap 4 according to this description: https://v4-alpha.getbootstrap.com/getting-started/build-tools/#tooling-setup

I've found the _custom.scss where variables can be overwritten.
But it seems that the _custom.scss is the wrong place for an import of '_myOwn.scss' because it's one of the first SCSS files called by 'bootstrap.scss'.

So if "_myOwn.scss" contain the lines
```css
.btn {
	// great stuff
}
```
it will be overwritten by the .btn class from '_buttons.scss'.

Is there a propper way to import your own SCSS files?
If not, I suggest a '_customImports.scss' called last by 'bootstrap.scss'.

**Comment by bkdotcom** [comment]
if `.btn {}` is defined more than once, the last one defined is the one used.
if you're overriding **rules**, create a separate _myOwnRules.css and include it last.

**Comment by mdo** [comment]
Yup, what @bkdotcom said.
