### ISSUE TITLE
[hidden] attribute doesn't have any effect with display utility classes

### ISSUE THREAD

**Issue by sqal** [twbs/bootstrap#21907]
So this thing happens when I have element with `d-flex` class and hidden attribute added to the same element:

![img1](http://image.prntscr.com/image/bcbff9094b5344a09233d16d1bd54d00.png)

I can't hide the element because flexbox utility classes are placed after reboot.scss. Shouldn't this attribtue have higher priority than all these other `d-xxx` classes? As a workaround I added this selector once again at the end of my css, but I think it also should be fixed in Bootstrap.

**Comment by mdo** [comment]
`.d-sm-flex` is scoped to a media query, so it's going to override your `[hidden]` attribute. This would also happen with `.d-none`; just a matter of how you use these classes.
