### ISSUE TITLE
Customizing Bootstrap with Webpack/Browserify 

### ISSUE THREAD

**Issue by bluesurfer** [twbs/bootstrap#21900]
I have installed Bootstrap with `npm` and I would like to customize some of the variables in `_variables.scss`. I can't find a good way to integrate it with Webpack or Browserify.

**Comment by patrickhlauke** [comment]
I'd suggest asking on StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
