### ISSUE TITLE
Forms in navbar placed outside navbar-collapse break

### ISSUE THREAD

**Issue by ChaseGiunta** [twbs/bootstrap#21902]
https://jsbin.com/dovifatoco/edit?html,output

![image](https://cloud.githubusercontent.com/assets/1377169/22573139/26661b5a-e96d-11e6-8e13-bfc314bc6b4f.png)

Tested in Chrome & Safari on Mac. 

`width: 100%` placed on `.navbar-toggleable-* .navbar-collapse` seems to be the culprit.

**Comment by SingingLioness** [comment]
There is no issue with either `.navbar-toggleable-*` nor `.navbar-collapse`. The code uses `.navbar-toggleable-md` which implies that for screen width > 572px, your styling is valid. As you lower the screen width <572px navbar components are placed one below the other. You might want to use the `.navbar-toggleable-sm` attribute instead. Mobile-first approach.

**Comment by ChaseGiunta** [comment]
@SingingLioness give the jsbin I provided a try with _any_ `navbar-toggleable-*` . That's why I specifically used an asterisk.

 Form elements in the navbar, regardless of sizing, should be in inlined side-by-side, not stacked.

**Comment by mdo** [comment]
Inline form behavior is a separate issue than the navbar. With this issue in particular, the contents of a navbar kinda have to be within the `.navbar-collapse` for the intended behaviors on our end. We can't really get around that. If you change the markup, you'll likely need to change the CSS, too.
