### ISSUE TITLE
glyphicon-chevron-up and glyphicon-chevron-down strange spacing

### ISSUE THREAD

**Issue by aclarembeau** [twbs/bootstrap#21912]
Hello, 

When using the two glyph icons chevron-up and down, there is a strange space to the right of the symbol. This gap isn't present in the other symbols. 

Here's an example: 
http://www.w3schools.com/code/tryit.asp?filename=FCEJ1653WF9G

We can see the right space with the two first images, but not with the last one. 

Does someone know if this is a feature and if yes, how to solve it? 
Thank you in advance

![glyphicon](https://cloud.githubusercontent.com/assets/10834626/22617186/b70164ec-eabe-11e6-926e-44b3d4a4df86.png)

**Comment by wolfy1339** [comment]
Unfortunately, Bootstrap v3 is not supported anymore.

**Comment by mdo** [comment]
Yup, and Glyphicon specific problems should be reported to the Glyphicons project, not us. We just package it with Bootstrap with their blessing as an awesome bonus. Closing given v3's status.
