### ISSUE TITLE
[Alpha 6] Set table column width in th

### ISSUE THREAD

**Issue by sarotnem** [twbs/bootstrap#21913]
Hello. When trying to set a class with column width in th elements it doesn't work properly as you can see below: 

http://www.codeply.com/go/GNB0rUnQF1

This snippet worked perfectly in Bootstrap 3:

http://www.codeply.com/go/GUjXa8hRgG

A temporary workaround for this is to set the `<tr class="row">` but then again you have to set the same classes in td which is not very practical.

http://www.codeply.com/go/fgSa15wAWg

**Comment by briancray** [comment]
For now I put this in my css

```
@for $i from 1 through $grid-columns {
    .table .col-#{$i} {
        width: percentage($i / $grid-columns);
    }   
}
```

it doesn't have the responsive part but at least you can do `class="col-4"` etc

**Comment by mdo** [comment]
Punting on this for now and leaving as a won't fix.

**Comment by oliverasistemas** [comment]
@sarotnem  I am having the same problem. Won't fix means this is not going to be fixed?

**Comment by mdo** [comment]
Small heads up here, we no longer use `flex-basis` on our grid classes. It's back to just `width` now, so this should work!
