### ISSUE TITLE
Right aligned button group in fixed navbar missing margin problem

### ISSUE THREAD

**Issue by kallevaravas** [twbs/bootstrap#21915]
Hello, I don't do this often, so I hope it helps.

# Problem
When navbar is set to be fixed, by adding the `navbar-fixed-top` class to it. Then button group, when only aligned to right (`navbar-right`) and being the upmost right sided element -- navbar's containers limits or button-group margins get ignored.

![bootstrap_buttongroup_margin_ignored](https://cloud.githubusercontent.com/assets/6654943/22622173/34ed876e-eb3c-11e6-90e3-2011de5b5fb6.png)

[Live example](https://jsfiddle.net/732tLkww/)
```
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="btn-group navbar-right">
                <button type="button" class="btn btn-danger navbar-btn btn-primary"><span class="glyphicon glyphicon-user"></span> Sign Up</button>
                <button type="button" class="btn navbar-btn"><span class="glyphicon glyphicon-log-in"></span> Login</button>
            </div>
        </div>
    </div>
</nav>
```
_Issue will disapear, if `navbar-fixed-top` is removed from **nav**._

# Dirty fix
Adding `.btn-group.navbar-right {margin: 0;}` as [custom css](https://jsfiddle.net/732tLkww/2/) OR adding `style="margin: 0;"` as inline-css to **btn-group** [container](https://jsfiddle.net/732tLkww/1/). 

![bootstrap_buttongroup_margin_ignored_fixed](https://cloud.githubusercontent.com/assets/6654943/22622227/8cdd92d8-eb3d-11e6-8838-8fcccb002581.png)

**Comment by Connum** [comment]
Hi, you added the label "v4", but your example uses 3.3.7?

**Comment by kallevaravas** [comment]
Yeah, this is not a **v4** bug! The `navbar-right` acts completely differently in v4 and no fix is needed.

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
