### ISSUE TITLE
Custom select border radius has default browser value when $enable-rounded is set to false

### ISSUE THREAD

**Issue by salparadise** [twbs/bootstrap#21922]
I'm using Bootstrap v4.0.0-alpha.6 on OS X 10.2.2.

Setting `$enable-rounded` to `false` instead of zeroing the value of border radius it allows to use browser default. However it works as expected when `$enable-rounded` is set to `true` and `$custom-select-border-radius` is set to `0`.

**Comment by mdo** [comment]
Torn on this one since every browser is different in it's styling of `<select>`. Windows users don't have any rounded corners I believe, and Mac browsers don't always pick up. Maybe fine to do an if/else for the custom select, and leave the default select untouched?

**Comment by salparadise** [comment]
In my opinion, as long as it's "custom" select it should provide consistent styling across browsers and left default select untouched.
