### ISSUE TITLE
add negative margin spacing

### ISSUE THREAD

**Issue by hamad-almamari** [twbs/bootstrap#21924]
https://github.com/hamad-almamari/bootstrap/pull/1/commits/b19ee58caf91c8b832e21b115689d8dc8f946f3f

Hello what about add negative margin spacing, I thing it is very usefull.

**Comment by josmaissan** [comment]
I would appreciate especially `margin: -15px;`-versions to eliminate the spacing of the .container

**Comment by mdo** [comment]
I get it, I've wanted these from time to time as well, but I'm going to pass on this. It's a matter of too many classes more than anything else. This can easily be an add-on or custom CSS though. Thanks for the suggestion!

**Comment by tamtakoe** [comment]
@mdo I add +1 for negative margin. There are a lot of examples when we need it. Popular one:
https://plnkr.co/edit/p1eZ50ncru36N3FaXzsk?p=preview
