### ISSUE TITLE
Feature Request: Http2 and multiple files 

### ISSUE THREAD

**Issue by kitsguru** [twbs/bootstrap#21928]
With HTTP2 coming on strong does it make sense to split bootstrap into several files?

Grid traditional
Grid Flex
Components, one for each
Color - skin
Gradients
Utilities
Etc.

Having several color skins would be nice and this approach would accomplish two objectives. 
1. Meeting HTTP2 best practices of several small files. 
2. Skins

**Comment by bardiharborow** [comment]
We're not at the point where this makes sense, for a few reasons:

- HTTP/2 is not really adopted sufficiently yet (73.51%), and we can't justify such a large slowdown for the other 26.49%.
- Even with HTTP/2, one file is still slightly faster. The main reason why you should split things into smaller files in HTTP/2 is that if you change one of them, then the whole cache isn't invalidated and only the changed file needs to be re-downloaded. With Bootstrap, this isn't much of a problem as updates are made quite slowly, and by the time we make a new release, we'll probably have touched most files anyway.
- One large attraction of Bootstrap is it's plug and play nature, especially for web designers who don't want to get too bogged down in the detail. Having multiple CSS files to include adds a level of complexity that will deter a chunk of our users. Those who want such complexity are probably already using build processes and tweaking our SASS variables. These people could modify their build processes fairly easily to generate multiple files if that meets their requirements.

At this point we are not in a position to do this. When v5 comes around, things could look very different, but for now I'm closing this as a WontFix.
