### ISSUE TITLE
Time input spin button and calendar picker indicator forced downwards when joined with input-group-addon

### ISSUE THREAD

**Issue by Aidurber** [twbs/bootstrap#21932]
**System details**
- OS: Windows 10 Pro; Version: 1607; OS Build: 14393.693
- Browser: Chrome; Version 55.0.2883.87
- Bootstrap version: v4.0.0-alpha.6

Time input formatting is off when joining two inputs with an input-group-addon in v4.0.0-alpha.6. 
The following are being forced down: 
```
input::-webkit-inner-spin-button{}

input::-webkit-calendar-picker-indicator{}
```

**Code**
```html
<div class="form-group">
    <label>Between: </label>
    <div class="input-group">
        <input type="time" name="starttime" class="form-control">
        <div class="input-group-addon">
            <label>and </label>
        </div>
        <input type="time" name="endtime" class="form-control">
    </div>
</div>
```
**Demos**
- [v4.0.0-alpha.6](http://www.bootply.com/KlVoWbQyzG)
- [v3.3.7](http://www.bootply.com/2RThCYj2l6)

**Comment by bardiharborow** [comment]
Is this at all related to #21651?

**Comment by Aidurber** [comment]
Looks that way, my apologies, I did a search but my terms must have been poor. Closing in favour of #21651
