### ISSUE TITLE
Unexpected CSS token warning ':' in Safari

### ISSUE THREAD

**Issue by Deminem** [twbs/bootstrap#21933]
Unexpected CSS token **:** in the Safari browser while rendering the page. 

> [Warning] Unexpected CSS token: : (bootstrap.css, line 3572)

There's another [issue](https://github.com/twbs/bootstrap/issues/21386) which shows the same warning due to some other reason and marked as **closed** because of migration from V3 to V4 JS engine.

**Bootstrap version:** 3.3.7
**Browser:** Safari 10.0.1
**Error:**  [Warning] Unexpected CSS token: : (bootstrap.css, line 3572)

**Comment by patrickhlauke** [comment]
> while rendering the page.

which page?

**Comment by mdo** [comment]
Sounds like it's a v3 thing, so closing out given that and the lack of details.
