### ISSUE TITLE
Utility for the flex-grow property

### ISSUE THREAD

**Issue by tompazourek** [twbs/bootstrap#21944]
I think there could be an utility class like `f-grow-1` that would correspond to CSS rule `flex-grow: 1`. (possibly also `f-grow-2`, `f-grow-3`, etc.)

I've been really enjoying working with the Bootstrap 4 [flexbox utility classes](https://v4-alpha.getbootstrap.com/utilities/flexbox/), but I feel this one is still missing and could be very useful for a lot of people to do stuff like this:

https://stackoverflow.com/questions/29467660/flexbox-row-how-to-stretch-children-to-fill-cross-axis

If it's a stupid idea, please let me know why.

**Comment by iatek** [comment]
IMO this would be very useful and I've already encountered several use cases for it.

**Comment by iatek** [comment]
I keep finding more use cases for a flex grow utility..

- [Sticky footer](http://www.codeply.com/go/wECEBeWpLO)
- [Horizontal centering of navbar elements (flexbox children)](http://www.codeply.com/go/4XNoJE4T3j)

**Comment by manju-reddys** [comment]
[May be something like](https://plnkr.co/users/manju-reddys)

**Comment by toyeca** [comment]
I would  also appreciate this functionality. Bootstrap lets you flex-grow: 1 in horizontal layout using col class, but this functionality is not present for vertical layouts.

**Comment by uclaitsscott** [comment]
In my projects, I've added a fill class flex: 1 to cover this since I utilize some fixed width columns and rows inside.

**Comment by SuperPat45** [comment]
I need also a flex-grow-0 utility for columns that should grow on mobile but not in desktop resolutions like:
```
<div class="row">
<div class="col-12 col-md"><input /></div>
<div class="col f-grow-md-0"><span>+</span></div>
<div class="col-12 col-md"><input /></div>
</div>
```

**Comment by rbrtmrtn** [comment]
I would definitely use this! :D

**Comment by cupofjoakim** [comment]
+1. We're currently setting and using our own utility for this, but should definitely be part of default utility classes.

**Comment by AaronLayton** [comment]
100% back this

**Comment by AndyCJ** [comment]
We have a layout where `flex-grow-0` and `flex-grow-1` would be handy.

**Comment by ThinkWired** [comment]
+1

I just created my own help class to do just this.
