### ISSUE TITLE
Dropdown in table responsive

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#21948]
Is there a way to create in bootstrap 4 dropdown links or buttons menu in table responsive, like this:

https://jsfiddle.net/xp5zsjau/10/

I use bootstrap in eCommerce administration and now i must use four inline buttons instead of menu. I saw a similar issue for bootstrap 3, but not for bootstrap 4.

**Comment by hugmanrique** [comment]
For questions, please use Stackoverflow or any other dev place. This place is only for issues regarding the main bootstrap issues, not the implementation of them.
