### ISSUE TITLE
Incorrect working collapse() method?

### ISSUE THREAD

**Issue by Shurikkan** [twbs/bootstrap#21949]
I'm trying hide all active accordion panels and then show panel by ID.
Then, when I click on adjacent accordion panels - all panels are showing. 

Here is example of code:
https://jsfiddle.net/u9kzt32w/5/
Сlick on the various panells and you will be able to see the problem.

P.S.: Sorry for my bad english :)

**Comment by Johann-S** [comment]
Support for v3 has mostly ceased. Please let us know if this issue affects v4.
See : https://github.com/twbs/bootstrap/issues/20631

**Comment by Shurikkan** [comment]
Unfortunately, this is Bootstrap 3...

**Comment by Shurikkan** [comment]
BS3 support is ceased because BS4 stable version is already appeared?

**Comment by Johann-S** [comment]
No because the team and folks wants to focus on the development of V4

**Comment by Shurikkan** [comment]
I try this in Bootstrap 4 (alpha):
https://jsfiddle.net/u9kzt32w/6/
and the result has not changed.

Code write in accordance with the official documentation on the website:
https://v4-alpha.getbootstrap.com/components/collapse/

Previous code version (on BS3):
https://getbootstrap.com/javascript/#collapse

**Comment by Johann-S** [comment]
Related to : #18418

**Comment by Shurikkan** [comment]
Thank's for help! :)

Working example is:
https://jsfiddle.net/u9kzt32w/9/

Maby insert information in documentation?
I think it's a pretty useful thing!
