### ISSUE TITLE
Increasing card height after use select.

### ISSUE THREAD

**Issue by Crustquake** [twbs/bootstrap#21946]
Dear all,

I have small issue with IE11, bootstrap@4.0.0-alpha.6 and card>form-group>select.
When I use (inside card) form-group with select, after click on select element my card increase height a little bit (more select elements -> more increase) and this size don't return back after.

![cardheightincreasing](https://cloud.githubusercontent.com/assets/19504248/22757914/b60b5e6a-ee5d-11e6-8dda-c72e20d961f9.gif)

In Chrome everything is OK, but IE is problem.
The reason is display:flex for card element and margin for elements inside (for example margin-bot in form-group or margin in label etc).
When I set all margins 0 - I have no this problem. And setting display:block for card resolve issue too.

[JSFIDDLE](https://jsfiddle.net/t7f4dpfn/)
[JS Bin](https://output.jsbin.com/kedutafile)

**Comment by mdo** [comment]
I've no idea what causes this and I cannot find a fix for it. Regrettable, closing as a can't fix. If anyone has a solution other than refactoring all these components away from margin (not feasible), I'm open to revisiting!
