### ISSUE TITLE
[Question] How does bootstrap manage to change the outline color on button and how does button get their margin between eachover ?

### ISSUE THREAD

**Issue by kopax** [twbs/bootstrap#21952]
I am trying to understand how does the render does the outline on click and margin on buttons without any css.

## Outline 

I am looking on this page [components/progress](https://v4-alpha.getbootstrap.com/components/progress/)

The button "Toggle animation" when got click got a class "active" when active.

There is on chrome another effect on the `outline` property. It's very hard to debug as it goes away as soon as we click out and settings a state `:hover`, `:active`, `:focus` didn't work.

According to http://www.w3schools.com/cssref/pr_outline-color.asp , it can be changed using `outline-color` css property.

I've looked on the code and the only file I've found using this is in [.scss-lint.yml](https://github.com/twbs/bootstrap/blob/v4-dev/scss/.scss-lint.yml#L336)

How did you do ?

## Buttons margin

I am looking at this page [components/buttons/#examples](https://v4-alpha.getbootstrap.com/components/buttons/#examples)

I can see that Buttons are spaced with a margin between them, but it doesn't belong to any element.

How did you do ? 

Thanks in advance,

**Comment by mdo** [comment]
You're seeing the custom focus state. It's made using `box-shadow` in CSS. The space between buttons in that example is what's referred to as an HTML space—it's rendered by the browser because our buttons have `display: inline-block`.
