### ISSUE TITLE
Dropdown menu inside modal

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#21959]
Bootstrap 4 alpha 6. Dropdown menu with checkbox input behaves differently inside modal (Impossible to check checkbox in Firefox, difficult in Chrome, etc.)

See
https://jsfiddle.net/32nupfrc/6/

Perhaps related to issue #21941

**Comment by mdo** [comment]
Retagging this as a JS issue. /cc @bardiharborow @johann-s

**Comment by md5** [comment]
I tested against `v4-dev` and `popper.js` and this seems to be fixed.
