### ISSUE TITLE
Navbar's Layout messes up when wrapped in divs!

### ISSUE THREAD

**Issue by henryspike** [twbs/bootstrap#21968]
Whenever I wrap the brand <a> tag and the .navbar-nav section in another div, the layout messes up. The nav-links start to stack up on the next line.

Moreover, there is no way I can centralize nav-items on the navbar. There is no flexbox utility to justify content at center when it comes to navbar. For example if you use justify-content-center on the <ul> nav-item list, it centers is according to the left space after the brand. And when you try to use the flexbox utilities in a div wrapping both <a> and .navbar-nav section, as mentioned earlier, the layout messes up.

**Comment by mdo** [comment]
If you're customizing the markup, you likely have to customize the CSS or make use of additional utilities. Without a live demo showing what you're running into, we can't help at all.

**Comment by henryspike** [comment]
Well, here you go, have a look at this bootply: http://www.bootply.com/KfCX35W9vS You can totally see the 'justify-content-between' class in the nav tag yet the image, links and social links arent aligning themselves.

Now if I wrap the navbar-brand and the navbar-item in a separate div, this happens: http://www.bootply.com/LIhwSuGYcD

So it looks like the flexbox utilities don't kind of work for the navbar. Thanks
