### ISSUE TITLE
Auto wrap with col does not work in Safari

### ISSUE THREAD

**Issue by iFlash** [twbs/bootstrap#21967]
This code will not auto wrap in Safari 10.0.3  (OSX 10.12).

Basically using class="col" in order to auto wrap columns will not work. The columns are displayed outside page margins.

Chrome and FF behave as expected.

```
<div class="container-fluid">
    <div class="row">
        <div class="col"><small>Some text here</small></div>
        <div class="col"><small>Some text here</small></div>
        <div class="col"><small>Some text here</small></div>
        .... add more columns until they should wrap
        <div class="col"><small>Some text here</small></div>
        <div class="col"><small>Some text here</small></div>
    </div>
</div>
```

**Comment by iFlash** [comment]
couldnt get the tags to show. sorry.

**Comment by iFlash** [comment]
See http://stackoverflow.com/questions/42174385/safari-and-bootstrap-4-automatic-grid-breaks for example.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin and report back with specific browser and OS details.

**Comment by iFlash** [comment]
I made an example available. I don't have the time to mouth feed you to make you product bug free. Sorry.

**Comment by mukadr** [comment]
Created [JSBin](https://jsbin.com/yuhubuziru/edit?html,output)

Reproduced this issue on the following browsers:

iOS 7, Safari 7
iOS 8, Safari 8
iOS 7 & 8, Chrome 47

**Comment by mdo** [comment]
Turns out this is [flexbug 11](https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items), where Safari doesn't wrap flex items properly. As I understand it, Safari uses different calculations for determining how to wrap flex items. The only workaround is using `flex-basis` to size the columns :\. In this case, you'd need to add:

```css
.col {
  flex: 1 0 50%; // where 50% is the intended size of the items
}
```

This is the same problem #21620 faces as well. Digging into even more, a `border: 1px solid transparent` on the `.col` will also fix this. Will work on a docs update to suggest these in context.

**Comment by dxh9845** [comment]
I got this as well. Site: danherzig.com. Happened on iOS browsers. Don't have an iPhone but got these screenshots. Fixed by reverting to prior columns (col-sm-12 and col-md-6). So the official fix was adding an invisible border?

**Comment by pimisi** [comment]
In my case I overrode the class .row:before, row:after, and set display: inline-block; That did the trick and did not affect Chrome and Firefox

**Comment by gigadie** [comment]
@pimisi suggestion wasn't working for me, but it worked changing it to `display: block;`

**Comment by mansouryaacoubi** [comment]
Here's the solution:
https://github.com/twbs/bootstrap/issues/9282#issuecomment-413421690

Worked like a charm!
