### ISSUE TITLE
justify-content-between doesn't work in card-header

### ISSUE THREAD

**Issue by piehei** [twbs/bootstrap#21963]
Hello

I think I've found a bug. justify-content-between in card-header does not work as I expect it should.

![bootstrap-v4a6-justify-bug](https://cloud.githubusercontent.com/assets/8404555/22852648/fb72200a-f048-11e6-850f-a5b203e91381.png)

You can find a JSFiddle here: https://jsfiddle.net/piehei/ztt3ya8q/3/

And this is the code:
```
Works (li):
<ul class="list-group">
  <li class="list-group-item justify-content-between">
    some text
    <span class="badge badge-default badge-pill">12</span>
  </li>
</ul>

Doesn't work (card-header):
<div class="card">
  <div class="card-header justify-content-between">
    moi <span class="badge badge-default badge-pill">12</span>
  </div>
</div>

Works:
<div class="card">
  <div class="card-header">
    <div class="d-flex justify-content-between">
      some text
      <span class="badge badge-default badge-pill">12</span>
    </div>
  </div>
</div>
```
Please note the usage of d-flex and an additional div in the works example.

I tested this on Chrome 56.0.2924.87 and Firefox 51.0.1 on Ubuntu 16.10.

**Comment by lactozily** [comment]
`display` of `.card-header` is not flex.
so `justify-content` will not work.

**Comment by piehei** [comment]
Should it be flex? Meaning, is this a bug or a feature?

**Comment by TheSharpieOne** [comment]
There is the `.d-flex` utility for these kind of things. You can add it directly to the `.card-header`, not need for an extra `div`.

**Comment by mdo** [comment]
Yup, you'll need to add `.d-flex` to properly use most of the flexbox utilities. We don't change the default `display` values whenever possible to minimize potential conflicting styles or bugs.

**Comment by mdo** [comment]
Please see the flexbox utilities docs page, specifically the first section for more info: https://v4-alpha.getbootstrap.com/utilities/flexbox/#enable-flex-behaviors
