### ISSUE TITLE
Rename responsive utilities to visibility utilities

### ISSUE THREAD

**Issue by JacobLett** [twbs/bootstrap#21965]
I think the naming is a little confusing and could be clearer on their purpose by renaming it to be more literal on what they do. Someone could be searching the docs thinking, "how do I hide this div on mobile? Ahh visibility utilities."

**Comment by bkdotcom** [comment]
another alternative name:
breakpoint utilities?

**Comment by mdo** [comment]
Got a doozy of a PR for you at #22113 to address this and some other things I've been noodling on around these utilities :). Reviews and general feedback would be awesome!
