### ISSUE TITLE
Tooltip not appends to given element

### ISSUE THREAD

**Issue by Liad91** [twbs/bootstrap#21962]
Bootstrap 4 alpha 6.
I'm trying to append tooltip to element by using the container option, but it's not working.
[JSFiddle](https://jsfiddle.net/Liad91/Lab4wsvu)

**Comment by echubs** [comment]
Same issue here. From what I see, tooltip [gets added](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L286) to the container first, but then tether moves it back to the body [here](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L292). I found that tether scans container and all its parent nodes up to the body, if it finds an element with a **non-static position** - it moves a tooltip ([see here](https://github.com/HubSpot/tether/blob/master/src/js/tether.js#L768)). In reality tooltip always ends up in the body, cause grid classes like .col-12 use relative position.

**Comment by Liad91** [comment]
I found that tether have `bodyElement` option which can be used to specify which element the tether's should attach themselves to. The problem is that tether currently makes the assumption that all of its calculations must be relative to the body, So even if we will use this option the container element will have to be same size and position respect to the body.
Maybe [Popper.js](https://github.com/FezVrasta/popper.js) is more suitable than Tether.js?

**Comment by Liad91** [comment]
#22444

**Comment by Johann-S** [comment]
Will be fixed by https://github.com/twbs/bootstrap/pull/22444

**Comment by Johann-S** [comment]
Closed and fixed by #22444
