### ISSUE TITLE
`.nav-link` under `.navbar-bar` doesn't get left/right padding unless some `.navbar-toggleable-*` is specified

### ISSUE THREAD

**Issue by almeidap** [twbs/bootstrap#21979]
IMO, `.nav-link` under `.navbar-bar` shouldn't require a parent `.navbar-toggleable-*` to receive left & right padding.

Currently, `.nav-link` padding is reset [here](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.6/scss/_navbar.scss#L56) and re-applied again [here ](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.6/scss/_navbar.scss#L147) with the `.navbar-toggleable-*` classes.

Unless there is some technical issue, I don't see the point of resetting the padding under `.navbar-bar`. A `.nav-link` should always have some space around, should it be under a `.navbar-toggleable-*` or not.

For your information, we will not use the `.navbar-toggleable-*` as we have a quite more complex toggleable navigation bar (with sliding sub-menus under small viewports).

**Comment by mdo** [comment]
Sticking with the current solution for now. We can adjust if need be during the beta.
