### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by trueibi7** [twbs/bootstrap#21978]
Dear Bootstrap team,

This is Chami Lim from KIA Austria Gmbh.
First of all, I really thank you for your the greatest open source.
Gloriously our project team wants to use it therefore, I would like to make sure of the license.

I have some questions as below:
1. Our project team choice the Bluemoon and we tried to buy a license as Bluemoon using our company account.
(https://wrapbootstrap.com/theme/blue-moon-admin-theme-1-2-WB0375140)
However, I don't know how to buy it using the business account.
Honestly, I tried to buy it using my private account but our company wants to manage the business account for the license.
I would like to know how to but the license using our business account.(Unfortunately, our company doesn't have PayPal account)

2. If our company couldn't buy the license using our company account, then Can we buy it using our private account? (if it is valid for our company's project)

3. We will develop homepage for the website and for the tablet version.
The Bluemoon license should choose options (Single/Multiple/Extended).
Which option should I buy?

If you have any question, don't hesitate to contact me.
I am looking forward to your reply.
Thank you for your assistance and time in advance.

**Comment by patrickhlauke** [comment]
This has nothing to do with the Bootstrap project itself. You'll need to contact https://wrapbootstrap.com
