### ISSUE TITLE
Closing 2nd modal removes "modal-open" class from body.

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#21983]
As in topic - Open first modal, then second and then close second modal - "modal-open" class is removed from body and therefore scrollbar is wrong.

Edit: it concerns v4

**Comment by Johann-S** [comment]
Specified by the documentation : 

> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

See : http://v4-alpha.getbootstrap.com/components/modal/#how-it-works

**Comment by piernik** [comment]
ok thanks - I have to do it myself - it's only adding a class...

**Comment by Johann-S** [comment]
If I answered your question, you should close your issue thank you 👍
