### ISSUE TITLE
.navbar-toggler not aligned same as .navbar-collapse if .navbar-brand causes whole navbar element to expand beyond "default" height

### ISSUE THREAD

**Issue by johnsenpeder** [twbs/bootstrap#21984]
Not sure if this is intended or not but when .navbar-brand element causes the whole navbar element to expand beyond it's "default" height, the elements in the .navbar-collapse element are vertically center aligned but the .navbar-toggler is not.

![links vertically aligned](http://i.imgur.com/sSqbjsh.png)
![navbar toggler absolute positioned top right corner](http://i.imgur.com/K3mOSss.png)

Screengrabs taken from official docs (editing the font-size of the .navbar-brand element in inspection tools)

**Comment by henryspike** [comment]
+1, I have the same issue as well and the alignment utils just don't seem to work. The only temporary fix that I worked out was to use custom css adding a little margin-top but once again it defeats the whole purpose of responsiveness through a framework if you have to use custom margins/spacing.

**Comment by inorishizuka** [comment]
[http://i.imgur.com/yj3A6UG.png](url)

same here

**Comment by mdo** [comment]
Should be fixed by updated navbar toggler behaviors in #22230.
