### ISSUE TITLE
FlexBox utilities not working with 'nav' tag

### ISSUE THREAD

**Issue by henryspike** [twbs/bootstrap#21982]
Please take a look at this Bootply here: http://www.bootply.com/KfCX35W9vS You can totally see the 'justify-content-between' class in the nav tag yet the image, links and social links arent aligning themselves

Now if I wrap the navbar-brand and the navbar-item in a separate div, this happens: http://www.bootply.com/LIhwSuGYcD

So it looks like the flexbox utilities don't kind of work for the navbar. Thanks

**Comment by iatek** [comment]
It's happening because the `navbar-collapse` width is 100%. If you change the width to auto it works: http://www.bootply.com/zhUH3FCODG

I think a better solution is to not use the flexbox utilities, and instead use the alignment utils as explained in the docs.

```
 <nav class="navbar navbar-toggleable-md bg-custom">
   <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
     <span class="navbar-toggler-icon"></span>
   </button>
   <a href="/" class="navbar-brand"><img src="http://imgur.com/4UhrQPD" alt="logo" class="nav-logo"></a>
   <div class="navbar-collapse collapse" id="collapsingNavbar">
     <ul class="navbar-nav ml-auto">
       <li class="nav-item active">
         <a class="nav-link" href="#">Link <span class="sr-only">Home</span></a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="#">Link</a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="#" data-toggle="collapse">Link</a>
       </li>
     </ul>
     <ul class="nav navbar-nav flex-row">
       <li class="nav-item"><a class="nav-link pr-3" href="">Facebook</a></li>
       <li class="nav-item"><a class="nav-link" href="">Twitter</a></li>
     </ul>
   </div>
</nav>
```

**Comment by henryspike** [comment]
Well the bootstrap docs say:

> Navbars and their contents are built with flexbox, providing easy alignment options via utility classes.

But clearly it is misleading then. 

Moreover, the second fix you mentioned does not provide you with full layout control. I mean you can not center some links, push others to right and keep the logo on left. So its the centering that would be the issue with the normal spacing classes.

And again it does not answer the wicker behavior of navbar when navbar-brand and navbar-nav is wrapped in a separate div.

**Comment by iatek** [comment]
Yeah, I should've said [auto-margins](http://v4-alpha.getbootstrap.com/utilities/flexbox/#auto-margins) instead of "alignment utils". IMO, auto margins are one of the best ways to align with flexbox.

[navbar left, center. right works nicely ](http://www.bootply.com/QQ4KvIEfQe) with just auto-margins and no add'tl flexbox utils. The center is still relative to the container, but that'd happen with flexbox alignment too.

**Comment by henryspike** [comment]
Is there any harm in making the collapse span auto width so the flexbox can be used? 
Moreover, please do answer this part if you can, I would really appreciate it

> And again it does not answer the wicked behavior of navbar when navbar-brand and navbar-nav is wrapped in a separate div.

And in the end, thanks again for helping out

**Comment by mdo** [comment]
> Well the bootstrap docs say:
> 
> > Navbars and their contents are built with flexbox, providing easy alignment options via utility classes.
> But clearly it is misleading then.

While being built with flexbox, not everything is `display: flex`.

---

Closing as a won't fix as there's not much we can do here.
