### ISSUE TITLE
[Alpha 6] Upgrade from 4.0.0-alpha.4 to 4.0.0-alpha.6 leads to problem with _animation.scss

### ISSUE THREAD

**Issue by mircowidmer** [twbs/bootstrap#21986]
I upgraded the following npm modules in my Angular project:

- @ng-bootstrap/ng-bootstrap from 1.0.0-alpha.8 to **1.0.0-alpha.20**
- bootstrap from 4.0.0-alpha.4 to **4.0.0-alpha.6**
- boostrap-loader from 2.0.0-beta.12 to **2.0.0-beta.20**

I then encountered the following problem upon loading my application (Angular 2.3.1)

> Module build failed: 
undefined
^
      File to import not found or unreadable: ../bootstrap/scss/_animation
Parent style sheet: stdin
      in /node_modules/bootstrap-loader/no-op.js (line 16, column 1)
Error: 
undefined
^
      File to import not found or unreadable: ../bootstrap/scss/_animation
Parent style sheet: stdin
      in /node_modules/bootstrap-loader/no-op.js (line 16, column 1)
    at options.error (/node_modules/node-sass/lib/index.js:292:26)

> OS: Mac OS X El Capitan
Browser: Chrome 56

My suspicion is, that the following commit (https://github.com/twbs/bootstrap/pull/21370/commits/2ae314554cbeaba718252015b276665222b29be0?diff=split) somehow breaks my setup, but I don't know where I can change this incorrect import. Cleaning of all npm modules and hard reload everything did not help unfortunately.

Any help is much appreciated.

**Comment by bardiharborow** [comment]
I'm not familiar with bootstrap-loader, but a quick search indicates that it relies on hard coded paths of SCSS files. You'll need to raise a bug with them.

**Comment by tc-imba** [comment]
In Release 4.0.0-alpha.6, you can find
+ Renamed _animation.scss to _transitions.scss for clarity.

So you can rename `animation` to `transitions` in .bootstraprc/Components
