### ISSUE TITLE
feature: spacer semantics

### ISSUE THREAD

**Issue by alindber** [twbs/bootstrap#21989]
I'm really happy Bootstrap is adding spacer utilities! Awesome stuff!
https://v4-alpha.getbootstrap.com/utilities/spacing/

One suggestion I had was to change the semantics in a way that developers can understand the baseline of the spacing.

For example, `[m/p]-3` seems to be the baseline spacer size in the variables: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L157

Which strikes me as odd/confusing.  It's easy to understand `m-3` has more margin than `m-2`, but to know `m-2` is half the default spacer size...not as intuitive.

What are your thoughts on something more along the lines of `+/-` semantics?

Example proposal:
```
// margin
m--, m-, m, m+, m++

// padding
p--, p-, p, p+, p++
```

This way, it strikes me as a simple and somewhat intuitive way to see a baseline spacing selector and understand if I'm using a fraction or multiplier of it.

The disadvantage I see in this semantic is it wouldn't be as simple in customizing the `spacers` Sass map. Or it simply just adds more `+`'s or `-`'s ... like `m+++, m++++` - definitely not a fan of that.

Thoughts?

**Comment by mllrjb** [comment]
I could see the case for more `+`, (e.g. `font-awesome` has / had a semantic like `fa-6x`). I don't see a great reason for ever-decreasing margins / padding though (`m------- = m0`?).

**Comment by alindber** [comment]
also, I'd be happy to open a PR! just wanted to hear peoples thoughts

**Comment by mdo** [comment]
No plans on changes to the syntax here. The format we use is one that's used in other projects and is relatively straightforward to understand with the help of our docs and a bit of practice. I don't think the `+`s and `-`s do any better of a job at articulating how much the jump in margin/padding is, the total available steps, etc.

Thanks though!
