### ISSUE TITLE
navbar without collapse for all screen sizes

### ISSUE THREAD

**Issue by ablbol** [twbs/bootstrap#21992]
Hi,
I was wondering if there is a way to not collapse the navbar for all screen sizes in which case the navbar will be always be horizontal for all screen sizes.
Thanks

**Comment by iatek** [comment]
The navbar is responsive by default, so you need to use `navbar-toggleable-xl` to prevent it from stacking vertically. However, there is an open issue as the wether this should be the default:
#21706

**Comment by ablbol** [comment]
Thanks for your help.
navbar-toggleable-xl does work.
Thanks
