### ISSUE TITLE
CSS CDN with Alpha 6

### ISSUE THREAD

**Issue by Windy01** [twbs/bootstrap#21996]
I'm using Win 10 with Chrome browser version 56 and using Bootstrap 4 Alpha 6
I have a Carousel working with a number of images and left and right chevrons.
This works fine with Alpha 5 but when I use the CSS CDN for Alpha 6, the images do not resize when changing browser width.
I set up a simple test page with no css files apart from the CDN. The images resize correctly when using the Alpha 5 CDN, but when I change it to the Alpha 6 CDN, the images don't resize
I used the "Slides Only" code from https://v4-alpha.getbootstrap.com/components/carousel/ to test

**Comment by mdbootstrap** [comment]
any demo of this?

**Comment by mattonit** [comment]
any demo of this?

**Comment by Windy01** [comment]
Have commented out CDN alpha 5. Run this code (change src for images) and change browser width. This shouldn't work. Comment out alpha 6 and un-comment alpha  5 and this should work
`
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    
    
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    
    <link rel="stylesheet" href="css\myStyle.css">      
    
</head>
<body>
    
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="images/Home/H01.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="images/Home/H02.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="images/Home/H03.jpg" alt="Third slide">
    </div>
  </div>
</div>

    
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</body>
</html>
`

**Comment by Windy01** [comment]
I accidently closed

**Comment by wolfy1339** [comment]
Alpha 6 went to all flexbox. Please make sure your styles are also using them and that the HTML is also changed to reflect the changes in the HTML structure of some components

**Comment by Windy01** [comment]
Here's my test code:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Bootstrap 101 Template</title>

    
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

      
    
  </head>
  <body>

      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="images/Home/H01.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="images/Home/H02.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="images/Home/H03.jpg" alt="Third slide">
            </div>
          </div>
      </div>
          
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="myjs/myScript.js"></script>
  </body>
</html>

**Comment by josmaissan** [comment]
Think this is the same as #21611

**Comment by Windy01** [comment]
josmaissan

Your link was the answer to my problem

Many thanks :-)
