### ISSUE TITLE
Horizontal checkbox label inconsistency

### ISSUE THREAD

**Issue by srvance** [twbs/bootstrap#21998]
The documentation in [BS3 for horizontal layout](http://getbootstrap.com/css/#forms-horizontal) omits a `control-label` class from the checkbox. This seems an odd inconsistency. Is this intentional? Adding `control-label` doesn't seem to harm anything, but I can't be sure I'm looking at all the right things. This seems to have been remedied in BS4.

This has led to some additional complexity in implementing `ember-bootstrap`. I would love to simplify it if possible.

**Comment by bkdotcom** [comment]
checkbox labels don't use the `control-label` class (horizontal or otherwise)

**Comment by srvance** [comment]
They don't need `control-label` or shouldn't have it? It looks like it would add some extra padding.

In contrast, BS4 shows `form-control-label` in on checkbox labels.

**Comment by mdo** [comment]
It's been awhile since I've peep the v3 code, but the `.control-label` is only used on labels for inputs in the grid layout like that. We need to add extra styles to those labels so they line up correctly, whereas the checkbox below is fine on it's own.

**Comment by mdo** [comment]
And more specifically, no you don't need `.control-label` on `.checkbox`s there. In v4, we encourage the class usage in far more layouts, though the `.form-check` has it's own styles as well there.

**Comment by srvance** [comment]
Thanks for the info. I've been looking at both side-by-side quite a bit.
