### ISSUE TITLE
Add uncolored .btn example to docs.

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#21995]
Just notice that we have a new or another color for buttons:

`<button class="btn">link</button>`

This button is like midtone grey. This one should be shown in the examples:

https://v4-alpha.getbootstrap.com/components/buttons/

**Comment by Studio384** [comment]
That's not supposed to be used if I remember correctly. That is just the basic ```.btn```-style that is used as a "reset style" (that's not the right word) for the other ```.btn-*```-classes.

**Comment by Igcorreia** [comment]
@Studio384 it is a style do. :)

**Comment by Studio384** [comment]
It's not, it's like saying that ```.btn-primary``` on itself is a correct style as well.

**Comment by mdo** [comment]
`.btn` by itself is incomplete—it's what we call the base class. Base classes require modifier classes to apply additional styles on top of the shared ones in the base class. As such, there's nothing else to document here at this time.
