### ISSUE TITLE
v4 Alpha 6 Docs for Modal

### ISSUE THREAD

**Issue by genericlady** [twbs/bootstrap#21999]
[Modal Examples](https://v4-alpha.getbootstrap.com/components/modal/#examples) #Live Demo has an example where the `data-target` attribute is not referencing the same id that is in the `div.modal` element.

```html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>
```

Proposed change `target="#exampleModal"` to `target="#myModal"`
```html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>
```

Conversely, it's reasonable to be more instructional with the naming of this hook. Why not use `#nameYourOwnID`? Unfortunately, as it is now it will break if you don't change the id.

**Comment by patrickhlauke** [comment]
already fixed by https://github.com/twbs/bootstrap/pull/21671
