### ISSUE TITLE
4K and 5K Support

### ISSUE THREAD

**Issue by BenMorganIO** [twbs/bootstrap#22000]
Hey there,

I'm opening this issue to generate discussion and thought about the use of 4K and 5K monitors. I myself have recently sold my retina thunderbolt display, went over to BestBuy, and picked up a 4K monitor. I've scaled it down to a retina display, but as the future gets ever so much closer to the present, 4K and 5K becomes more and more widely used by designers, engineers, health professionals, video editors, and so on...

To help start building projects and websites that allow for 4K resolution, I've placed one of my projects in a 4K environment. As expected, everything's ~2x smaller.

I think we should expand our grid system for 4k and/or 5k displays. I know there's been one issue on the discussion of px to rem located at https://github.com/twbs/bootstrap/issues/19943 and @AsoStrife opened a PR to ask for a 4K implementation at https://github.com/twbs/bootstrap/pull/17661.

Although 4K isn't a resolution currently being used by general users, it's got a major upstream of users from professional industries.

As @patrickhlauke pointed out in https://github.com/twbs/bootstrap/issues/19943#issuecomment-224439306 that `px` is defined via CSS and not by hardware. In which case, this may be an issue with the current version of CSS not taking into account the greater pixel density of ultra high resolutions.

Questions for discussion:

- Would 4K support be a quick win?
- Is it worth the implementors' and users' time to expand and use a larger grid system?

**Comment by myorangeca** [comment]
Are you able to share a screenshot of this? I am finding it hard to picture.

**Comment by BenMorganIO** [comment]
@myorangeca what you can do is select a Bootstrap example page, create a custom emulated device for 3840x2160 and then view the result:

<img width="1280" alt="screen shot 2017-02-15 at 4 27 00 pm" src="https://cloud.githubusercontent.com/assets/3117356/22996118/9e5aedb0-f39b-11e6-9358-4278318b2330.png">

**Comment by patrickhlauke** [comment]
That assumes that people on a 4K monitor are running their desktop at the native monitor resolution (3940x2160) ... which some users certainly might, though others may run it at 2dppx device pixel ratio (effective 1920x1080 pixels).

Also, it assumes that users that run at the native resolution will run their web browser maximised ... again, some users may, but it more likely they'll be running it as a smaller window.

In principle, catering for 4K (by widening the layout a bit more) is certainly doable...but challenging, since you'll end up with lots of very long lines of small text even if we stick with the 12 column grid.

**Comment by nextgenthemes** [comment]
Are you aware that you can just add additional breakpoints to the variable and compile BS with 100 different breakpoints for 4k 5k 10k whatever screens sizes you like?

I personally don't get the point at all as I argue in #22008.

**Comment by BenMorganIO** [comment]
@nextgenthemes standardization and convention set by a very popular framework.

@patrickhlauke 

I doubt many of the 4K users use native resolution. I myself don't. However, I would like to start using the native resolution.

I tend to place my web browser as a smaller. Not because I want to, but as a workaround for so much negative space; that being in native resolution.

Yep, I thought it would be challenging as well.

It looks like adding an expanded grid system would be pretty straight-forward, but the font sizes could be a cause for concern. We could scale up the base font-size as the screen gets larger.

```css
body {
  font-size: $base-font-size;
  line-height: $base-line-height;

  @media #{$mq-medium} {
    font-size: $base-font-size*1.2;
    line-height: $base-line-height*1.2;
  }

  @media #{$mq-large} {
    font-size: $base-font-size*1.3;
  }

  @media #{$mq-xlarge} {
    font-size: $base-font-size*1.4;
  }

  @media #{$mq-xxlarge} {
    font-size: $base-font-size*1.6;
  }
}
```

From [CSS Tricks](https://css-tricks.com/optimizing-large-scale-displays/).

I found that article quite helpful in researching more of this issue.

**Comment by patrickhlauke** [comment]
> We could scale up the base font-size as the screen gets larger.

that's an opinionated take, though. it will make the webpage text font size larger than, say, the actual OS text or the browser's own UI, at that point, and it's not necessarily what the user intends/wants (if they did want things to be larger, while ALSO running at native resolution and maximized, would they simply use the zoom feature?)

it's difficult to find an answer that will be equally valid for all users and authors here

**Comment by BenMorganIO** [comment]
I agree on the difficulty to find an answer. I have a feeling many users wouldn't want to be using the zoom feature on a large number of web pages. If there's an opt-in for 4k support, then we know the user is making an intention to use it and then highlight that 4k support is naïvely making text 2x bigger or the other routes that Bootstrap could take.

**Comment by patrickhlauke** [comment]
Also worth noting that currently you'd be hard pressed to find many (any?) prominent sites that take advantage of a 4K native 1dppx resolution maximised. So users that do run that particular setup with that particular browser size would either be used to it like that (in terms of the text size etc), or they'd already be doing something generally to counter it (e.g. having a general page zoom setting in their browser set to 150%/200%, or something at OS level to change text size, etc). The danger of Bootstrap doing its own resizing here would be that potentially this overshoots whatever general settings the user has already applied. In short, I personally think that (with exception of perhaps considering what happens to the 12 column grid at such large sizes), we shouldn't be making assumptions and touching other things like font size.

**Comment by BenMorganIO** [comment]
@patrickhlauke you're right. We'd have to make a lot of assumptions as to how current users are mitigating the negative space. To summarize and to list the methods that users may use to troubleshoot:

- They may decrease the zoom to ~2x.
- They may resize the window.
- They may scale the resolution down to what they were originally used to or to a size that is "comfortably big".

We've identified that we can definitely upgrade the grid system for larger resolutions. However, what we need to know is what users would like from websites that may rescale themselves for the higher resolutions. As a user, I would like them to alter the font size, yet I'm only just one of many users fo the internet.

What we could do to get data and responses on the matter is add some breakpoints to the famous Bootstrap grid system. This would serve three purposes:

1. It would allow us to have (albeit some) support for ultra high resolutions.
2. It would give a gentle nudge to web designers to test the waters fo ultra high-resolution web design. In that sense, they may use it on their real-world projects and obtain user data.
3. It would allow people to call Bootstrap 4, Bootstrap version 4K; the pun is amazing.

Would people use the higher grid system or would it become a cool-but-not-so-often-used feature?

**Comment by mdo** [comment]
No planned changes for this ahead of v4. I'm open to future iterations exploring larger (and higher) resolutions, but not for v4's initial release.

**Comment by bupy7** [comment]
How many columns do you recommend for 4k displays?

**Comment by BenMorganIO** [comment]
@bupy7 The system that Bootstrap uses is 12 and 4k is 4x the screens with the horizontal pixel count doubled. Since columns are spanning horizontal, I would recommend 2 x 12 columns = 24 columns.

**Comment by bupy7** [comment]
@BenMorganIO Yep, I did it already =)

**Comment by BenMorganIO** [comment]
Sweet

**Comment by xpectmore** [comment]
Someone try  something cool here
https://github.com/BenWhitehead/bootstrap-big-grid

**Comment by HybridSolutions** [comment]
2026 and still no upgrade for bigger screens. Container breakpoints are obsolete and require tweak for bigger sizes. Does not make sense that on a 2k+ screen the xxl container element max-width is 1320px.  Breakpoints should be updated. Technology evolves so what was LG, XL or XXL is not anymore. Appliances had a letter rating that was also updated. There's no problem with that.
