### ISSUE TITLE
Empty navbar collapses

### ISSUE THREAD

**Issue by SirAiedail** [twbs/bootstrap#22003]
While in v3 the navbar has a `min-height`, in v4 an emtpy navbar will collapse and will only keep the height of it's padding (16px in default configuration).

JS Bin:
[v4/master](https://jsbin.com/kafugedemi/edit?html,output)
[v3.3.7](https://jsbin.com/gujimevoyo/edit?html,output)

**Comment by nextgenthemes** [comment]
Well whats the point on having a empty navbar?

You can just add a navbar element and make it invisibility with the `.invisible` class.

**Comment by SirAiedail** [comment]
The point in that is that I use a layout like [this](https://material.io/guidelines/material-design/environment.html) where both the sidebar and the content have a navbar. So even if the content's navbar has no children, visually it's not empty, as it merges with the sidebar to a full header.

If this is considered an edge case and the change is intentional, I don't mind closing the issue, as it is easy to fix in my code.

**Comment by nextgenthemes** [comment]
I think its was just removed to get rid of bloat or let the content + padding dictate the height rather then forcing it. Again I would just use a invisible brand or something.
