### ISSUE TITLE
Select uses wrong border variable for height calculation

### ISSUE THREAD

**Issue by andrewbelcher** [twbs/bootstrap#22011]
To get `select`s matching the size of text inputs, a calculation is done which includes the width of the border. However, it uses `$border-width instead` of `$input-btn-border-width`, which means if the two don't match, your `select`s have the wrong height.

This and the fix can be seen in the demonstration at http://codepen.io/andrewbelcher/pen/rjbwox.

I've got a PR to fix it - #21994. Apologies if I shouldn't have also opened an issue - wondered whether issues were the better place for reporting.

**Comment by lekkerduidelijk** [comment]
I've found the same to be so for the `$custom-select-border-width` and addressed it with a PR #22068.
