### ISSUE TITLE
Bootstrap 3.3.4 in Angular 2

### ISSUE THREAD

**Issue by prksean** [twbs/bootstrap#22016]
We are trying to start a project using Angular 2 and since Bootstrap 3.3.4 is the highest version that my company has approved, we cannot use Bootstrap 4. When I tried to use 3.3.4 Bootstrap navbar in Angular 2 application, it did not seem to work as supposed to. For example, the navbar dropdown would not pop up even when I click the menu. Is Bootstrap 3.3.4 ok to use along with Angular 2 or do I have to use Bootstrap 4?

Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://validator.w3.org/nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by GuskiS** [comment]
Are you trying to use bootstrap as standalone with Angular2 or are you using one of the already made implementations of bootstrap for Angular2, such as, https://github.com/valor-software/ng2-bootstrap ?

**Comment by patrickhlauke** [comment]
> When asking general "how to" questions:
>
> - Please do not open an issue here
> - Instead, ask for help on [StackOverflow, IRC, or Slack] (https://github.com/twbs/bootstrap/blob/master/README.md#community)

**Comment by mjasplin** [comment]
We are using Angular 1.6, and we also just ran into issues when upgrading from 3.3.7 to 3.4.0.  It seems to have issues with the #/linkName in the href field.  Reverted back to 3.3.7 and it is working fine. 
<ul class="dropdown-menu">
<li><a href="#/amount" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Amount Type</a>                                 	
</li>
</ul>

Error appearing in console: 
bundle.js:16915 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.Sizzle.error (bundle.js:16915)
    at Sizzle.tokenize (bundle.js:17572)
    at Sizzle.select (bundle.js:17993)
    at Function.Sizzle [as find] (bundle.js:16316)
    at jQuery.fn.init.find (bundle.js:18239)
    at getParent (bundle.js:101210)
    at HTMLAnchorElement.<anonymous> (bundle.js:101220)
    at Function.each (bundle.js:15812)
    at jQuery.fn.init.each (bundle.js:15584)
    at clearMenus (bundle.js:101218)
