### ISSUE TITLE
Text in button (.btn) is displaced a bit down when using ProximaNova SemiBold in Firefox

### ISSUE THREAD

**Issue by jnystromdesign** [twbs/bootstrap#22019]
The buttons text are displaced when using the font ProximaNova SemiBold from TypKit. Below are screenshoots from the bug version and the desired. Using Bold or Normal versions of the font cancels the weird behavior. 

**Buggy version**
![btn-buggy](https://cloud.githubusercontent.com/assets/141703/23056959/2f6560f8-f4ee-11e6-8e94-f1c6d3401220.png)

**Desired version**
![btn-desired](https://cloud.githubusercontent.com/assets/141703/23056960/2f6634ec-f4ee-11e6-8805-f6915ca6c12e.png)

**Comment by bardiharborow** [comment]
I'm not sure this is a Bootstrap issue...

**Comment by jnystromdesign** [comment]
Me neither, but I thought the issue at least would be possible to google now. Perhaps it's something to bring up to the Adobe community.

**Comment by bardiharborow** [comment]
Closing as not a Bootstrap bug until I hear more.
