### ISSUE TITLE
flex-column-reverse with ipad-Safari problems

### ISSUE THREAD

**Issue by creativesousa** [twbs/bootstrap#22023]
- Operating system and version (IPAD)
- Browser and version (Safari)

Hello. i'm having problems with flex-md-column-reverse

I have two columns
```
<div class="row flex-lg-row flex-md-column-reverse">
    <div class="col-md-12 col-lg-9 mb-lg-0 mb-md-4"></div>
    <div class="col-md-12 col-lg-3"></div>
</div>
```

On ipad vertical i want to columns change places
It works on Windows , Chrome. 
But on ipad it hide the content
only showing a little bit of the secound Columns.

**Comment by mdo** [comment]
Closing until we hear more.

**Comment by SiteGefuehl** [comment]
I have the same issue on Safari 10.0.2 and iOS 10.

**Comment by noblesilence** [comment]
```
.flex-md-column-reverse > * {
    flex: 1;
}
```

The above code solved the issue for me.
