### ISSUE TITLE
custom input checkbox with attribut for 

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#22026]
Hi
I use often the attribut for to the labels and when it is used with custom input (checkbox) it's no possible to have the control on checkbox (can not checked or unchecked...)

here is a small example 
https://jsfiddle.net/jipexu/21qryLcr/

Thanks

**Comment by bkdotcom** [comment]
2 things:
1)  for attribute isn't necessary when the label wraps the input (as it does here)
2) your inputs don't have `id` attribute.  you've told your labels that they're associated with 'nono' and 'notwork', which don't exist on the page..  add `id="nono"`, and `id="notwork"` and it will work  (but again, the "for" isn't necessary for labels that wrap the input)

**Comment by jipexu** [comment]
Thank you for your explanations !
