### ISSUE TITLE
Popover tether on window resize

### ISSUE THREAD

**Issue by silverbackdan** [twbs/bootstrap#22022]
I'm not sure whether this is a Bootstrap bug or Tether. I've created a small JS Bin to demonstrate that when I have aligned a button to the right, popover to the left and then resize the window with the popover open, the popover no longer aligns properly. Instead it will go off to the left of the screen.

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
MacOS Sierra 10.12.3
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Chrome  56.0.2924.87 (64-bit)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)
https://jsbin.com/cubacik/1/edit?output

I think it has something to do with the percentage width calculation because if you set a `min-width` when the container reaches that width, it aligns correctly again.

**Comment by Johann-S** [comment]
Closed and fixed by #22444
