### ISSUE TITLE
v4 migration docs: label renamed to tag renamed to badge

### ISSUE THREAD

**Issue by orymate** [twbs/bootstrap#22037]
Commit d9fa3fd7971b5331b6582b46b568048458bb5544 re-renamed .label from .tag to .badge. The migration docs mentions the first rename only.

**Comment by mdo** [comment]
The migration docs need only reflect the final state of the migration from v3 to v4, not for individual changes in each alpha release. Apologies for any confusion, but it's simply too many changes otherwise :).

**Comment by orymate** [comment]
@mdo The migration doc mentions the transitional name (.tag) only, not the final one (.badge).

**Comment by mdo** [comment]
You're seeing the hosted docs, but this is already fixed in `v4-dev` for our next release :).
