### ISSUE TITLE
Centered nav not quite right

### ISSUE THREAD

**Issue by leeaston** [twbs/bootstrap#22046]
When on [this page](https://v4-alpha.getbootstrap.com/examples/navbars/) the word (Container) and the icon overlap when the width is reduced. See below:

![yhwx6b5tblqdj6saaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/83708/23171116/e6f2bc50-f851-11e6-9155-565ffbffee9f.png)

**Comment by josmaissan** [comment]
If you think it's like these #21590 it's already fixed in these #21722 ...

**Comment by leeaston** [comment]
Thank you very much for your help josmaissan.
