### ISSUE TITLE
data-toggle=collapse with a checkbox to trigger the toggle

### ISSUE THREAD

**Issue by jcwchriswalker** [twbs/bootstrap#22049]
Using this fiddle as the testcase:

[http://jsfiddle.net/jcwchriswalker/e8wwhqcx/](http://jsfiddle.net/jcwchriswalker/e8wwhqcx/)

Note that by checking on/off the checkbox will hide and show the element targeted by the data-target. However the checkbox will not show checked/unchecked state. I looked through the documentation concerning what elements support the data-toggle attribute but could not find any definitive list. It seems that the checkbox's event handler set a preventDefault() keeping the checkbox from setting on/off but showing/hiding the data-target.

**Comment by Johann-S** [comment]
Yes that's due to this line : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L366
Same as : https://github.com/twbs/bootstrap/issues/21079
