### ISSUE TITLE
col-*-offset-* does not work

### ISSUE THREAD

**Issue by williamcaruso** [twbs/bootstrap#22052]
Simply, adding the offset classes do not work as they did in Bootstrap 3

**Comment by josmaissan** [comment]
Are you sure?
`col-*-offset-*` is now `offset-*-*` or
`col-md-offset-4` in Bootstrap 3 is 
`offset-lg-4` in Bootstrap 4 alpha 6
I think!

**Comment by browner12** [comment]
they have been renamed. please ensure you are using the correct classes.

http://v4-alpha.getbootstrap.com/layout/grid/#offsetting-columns

they no longer have the `col` prefix
