### ISSUE TITLE
Font in buttons and input fields is wrong

### ISSUE THREAD

**Issue by athyuttamre** [twbs/bootstrap#22051]
**Operating system and version:** macOS Sierra 10.12.3
**Browser and version:** Chrome 56
**Reduced test case:** http://jsbin.com/zajexemese/edit?html,output

On macOS, the button and input should use the San Francisco typeface. Instead, they use `sans-serif` from `_normalize.scss`. Perhaps `_reboot.scss` should also override these font settings?

**Screenshot**

<img width="800" alt="screenshot 2017-02-22 02 24 49" src="https://cloud.githubusercontent.com/assets/1485350/23201137/240b8fe6-f8a6-11e6-8326-af533ded294a.png">

**Comment by wolfy1339** [comment]
This should be fixed now that they have gotten rid of Normalize

**Comment by athyuttamre** [comment]
Oh interesting; could you point me to a commit where they remove it, please?

**Comment by athyuttamre** [comment]
Never mind, found it! https://github.com/twbs/bootstrap/pull/21741

**Comment by mdo** [comment]
Closing as already fixed.
