### ISSUE TITLE
input-group:    input-group-addon and input label is inconsistent  in horizontal direction, when the browser zoom

### ISSUE THREAD

**Issue by lu-yuan** [twbs/bootstrap#22055]
Test version: BS3.3.7
Browser: chrome, firefox, ie
Test image: attach file
![bug](https://cloud.githubusercontent.com/assets/24749117/23242128/25161cd2-f9b2-11e6-84a2-997e35c2c7c1.jpg)

We have used BS3.3.7 , because BS4 is not supported ie8.

**Comment by djaddo** [comment]
Deleting/changing the .form-control height size will fix the issue. 
Take a look here: https://content.screencast.com/users/djaddo/folders/Jing/media/997700fa-b5dc-48bb-9035-6f23e6ffa060/00001987.png

Cheers

**Comment by mdo** [comment]
_Closing as a won't fix given v3's state._

---

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

Sorry for the inconvenience, and thanks for the suggestion, but we'll be passing on this change.

<3
