### ISSUE TITLE
Cards in a .card-group/.card-deck should accept a spacing class for when they become vertical

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#22053]
Right now, adding .mt-sm-3 to a .card within a .card-group or .card-deck has no effect. When they become vertical, it's more user friendly on the eyes when some space exists between them. Can this be added in?

For example, adding a .mt-sm-3 to a .card within a .card-group could be honored when the grid causes them to become stacked/vertical.

**Comment by iatek** [comment]
Would you use .mt-3 since they stack vertically on the smallest (576px) breakpoint?

**Comment by mrlife** [comment]
@iatek You're quite right. This is not actually an issue.
