### ISSUE TITLE
Dropdown inside navbar-toggleable-xl expands entire navbar when open

### ISSUE THREAD

**Issue by iatek** [twbs/bootstrap#22058]
This is related to #21778 

When using a dropdown inside a `navbar-toggleable-xl` navbar, the entire navbar expands when the dropdown is open.

```
<nav class="navbar navbar-toggleable-xl">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCustom">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a href="" class="navbar-brand">Brand</a>
    <div class="navbar-collapse collapse" id="navbarCustom">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
```
Demo: http://www.codeply.com/go/cd92P7PAgE

Workaround is to override the responsive `postition: static` set on the dropdown-menu:

```
.navbar-toggleable-xl .navbar-nav .dropdown-menu {
  position: absolute;
}
```

**Comment by josmaissan** [comment]
I don't understand who wants to use a "navbar-toggleable-xl" navbar...
If I'm right it's always collapsed... 😕

**Comment by iatek** [comment]
Currently the `navbar-toggleable-xl` is a **non-collapsing** navbar, that doesn't collapse vertically. There is an open issue about this #21706 and making it the default state.

Currently the "always collapsed" navbar is the default, meaning if you don't specify  `navbar-toggleable-*` you get a vertical navbar.

**Comment by mdo** [comment]
This is intended behavior; it's the same thing we did for v3.

**Comment by iatek** [comment]
@mdo, it's not the same behavior as 3.x. In 3.x, when the navbar is **horizontal**, the dropdown doesn't effect the navbar's height. In 4.x it does..

3.x.
![3.x](http://i.imgur.com/tu6X490.png)

4.x
![4.x](http://i.imgur.com/emqeT9C.png)
