### ISSUE TITLE
Control-label + text-left

### ISSUE THREAD

**Issue by onzinsky** [twbs/bootstrap#22067]
Hi. I was trying to use both control-label and text-left to achieve something like this:
<img width="341" alt="screen shot 2017-02-25 at 11 47 46" src="https://cloud.githubusercontent.com/assets/4222074/23330530/41646d0e-fb50-11e6-8619-67a40580c06c.png">

I realised it's impossible to use both control-label and text-left, because text-left is before (in the code), so the text-align will always get overridden.

Is there a reason for not putting the text-left (which is really more specific) after control-label? 

Doing this would offer the possibility of using both. Shouldn't that be done?

**Comment by mdo** [comment]
We should move the `.text-` utilities to come later in the import stack so this is possible. We're also likely missing out on some `!important`s there to help out with overrides and specificity.

**Comment by mdo** [comment]
Wait, actually that is the case, and in the layout above the labels *are* left aligned. This is also the case in the docs examples and our codebase. The `.text-` utils should be applicable if you need to adjust any of this though.

Am I misunderstanding what you're after?

**Comment by onzinsky** [comment]
Hi Mark! In the picture I posted, I "forced" the labels to align left. But as far as I can see, it's not possible to do something like that by doing:

```
<div class="form-group **text-left**"> 
    <label for="inputEmail3" class="col-sm-2 control-label **text-left**">Email</label> 
    <div class="col-sm-10"> 
        <input type="email" class="form-control" id="inputEmail3" placeholder="Email"> 
    </div> 
</div>
```

Neither `.text-left` in the example work as desired (I know you wouldn't put both).

If `.text-whatever` were after the `.form-horizontal .control-label`, this would work! Maybe you guys don't want them to be after for some reason, but if that's not the case, it would be cool to move it or add the `!important` as you said.

(Sorry for late response)

**Comment by mdo** [comment]
These are already left aligned though: http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid. Plus, those text classes have `!important` on them and do already come after the forms CSS in the import order.

**Comment by onzinsky** [comment]
You're right. I have to apologise since I was talking about v3. I'm sorry, I hadn't read the CONTRIBUTING in quite a while! 
Thanks for replying either way!

**Comment by mdo** [comment]
Got it, thanks for the back and forth! :)

**Comment by mdo** [comment]
For those following along, closing given v3's status.

---

_Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements._

_Sorry for the inconvenience, and thanks for the suggestion, but we'll be passing on this change._

_<3_
