### ISSUE TITLE
Badges in v4?

### ISSUE THREAD

**Issue by leeaston** [twbs/bootstrap#22064]
Are [badges in v3](http://getbootstrap.com/components/#badges) no longer available in v4. I've had a [good luck in v4 documentation](https://v4-alpha.getbootstrap.com/components/badge/) and found no mention.

**Comment by caiquecastro** [comment]
Are you sure?

**Comment by leeaston** [comment]
I've had a good luck in v4 documentation and found no mention.

**Comment by fchiumeo** [comment]
it [this](https://v4-alpha.getbootstrap.com/migration/#labels-badges-and-tags) ?

**Comment by patrickhlauke** [comment]
indeed, as @fchiumeo said

> Dropped the `.badge` component as it was nearly identical to labels/tags. Use the `.tag-pill` modifier together with the label component instead for that rounded look.

**Comment by leeaston** [comment]
.tag and .tag-pill do not seem to be in the .css file.

**Comment by fchiumeo** [comment]
#20939

> 

- #20542, #21020, #21122: Rename .tag to .badge to avoid conflicts w/ WordPress.
