### ISSUE TITLE
v4 custom-select does not support "multiple"

### ISSUE THREAD

**Issue by jsmad** [twbs/bootstrap#22065]
The current bootstrap v4 beta 6 comes with a new custom-select class, but it appears broken when the "multiple" attribute is also defined.

For example:
```<select multiple class="form-control" id="exampleSelect2">```

changes into
```<select multiple class="custom-select" id="exampleSelect2">```

Maybe the documentation could mention that multiple is not supported, or if it is not too much work, to implement custom-select a bit better for displaying on a multiple select.

Thank you.

**Comment by C-Lodder** [comment]
PR: https://github.com/twbs/bootstrap/pull/23055
