### ISSUE TITLE
no visual feedback for buttons with mouse click and on touch devices

### ISSUE THREAD

**Issue by NothingWeAre** [twbs/bootstrap#22069]
Is it by design that since v4-alpha6 there is no visual feedback when button is pressed ?

Example: when button **focused and hovered**,clicks(after first focus) do not produce any visual feedback. On touch devices, after first press, button stay in :hover:active state and any further presses do not produce any visual feedback.

Tested on latest chrome/firefox, windows and android.

**Comment by mdo** [comment]
Yes, this is by design. We've limited our defaults to allow better and easier overrides.
