### ISSUE TITLE
Accessibility - custom improvement - allow badge text color customisation

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#22062]
As it's possible to custom badge background color for default, danger, and all others. There may be also a variable for text color in each case. By this way, the user can ensure that the contrast ratio between font color and background is all time okay with WCAG requirements.

You can see a proposition here : 
https://github.com/Lausselloic/bootstrap/commit/ec75282e85c378216c5ccb300ef910aa93130acc

**Comment by WoutMag** [comment]
I have the same request for badge class to have variants like -default, -info and -danger.

**Comment by 719media** [comment]
I think this would be better served by just doing something in the mixin like

```
@if (lightness($colorCode) > 80) {
  color: $gray-dark;
}
```

**Comment by mabar** [comment]
Maybe someone will found inspiration [here](https://github.com/oddbird/accoutrement-color/blob/master/sass/_contrast.scss)
With these functions can be contrast colors calculation fully automatized.
