### ISSUE TITLE
xl breakpoints differ on 12" and 27"

### ISSUE THREAD

**Issue by chrismccorrister** [twbs/bootstrap#22074]
I'm using bootstrap 4 Alpha 6 on 12", 15" and 27" macs (all newer retina screens). The problem I'm having is that the COL-LG-* and COL-XL-* are triggering the same for all those variations of screen sizes. Maybe this is how it's programmed, but it would be nice to see the breakpoints for XL and LG triggered differently on my 12" and 27". 

For example, I have an image library that I've developed, and on a 27" I'd like to use col-xl-2 to display 6 across, and then on my 12" and 15", I'd like to use col-lg-3 to display 4 across, but the xl is triggered on my 12" exactly the same as the 27". This means I have to either choose 6 across for all screen sizes or 4 across.

It would be nice to see the XL triggered for larger screens 17" and greater and LG used on smaller desktops 12" and greater.

**Comment by mdo** [comment]
We don't target our CSS based on the physical dimensions of your devices—it's based on the pixel dimensions of your browser's or device's viewport. They are triggering the same thing because of both devices match the specifications of our media queries. Unfortunately, the behavior you're after isn't possible in Bootstrap at this time.

**Comment by chrismccorrister** [comment]
Thanks for the response. I kind of figured that was the answer…but doesn’t it make sense to have different break points for such massively different screen sizes?

**Comment by mdo** [comment]
Maybe! I've worked in codebases with more and less breakpoints. All depends on the needs of the site/application and the expected users' hardware. In v4 you can add additional breakpoints as needed if your use case requires it.
