### ISSUE TITLE
Dashboard example: There is no way to display the sidebar in mobile layout

### ISSUE THREAD

**Issue by Skaronator** [twbs/bootstrap#22072]
When you open the Dashboard example (https://v4-alpha.getbootstrap.com/examples/dashboard/) and reduce the browser size to mobile layout then it will hide the sidebar completely.

On code base it is correct but it doesn't make any sense to me. (How do you want to click on the shiny Analytics buttons if the sidebar is completely hidden?)

I found some examples how this could be handled better:
 * https://colorlib.com/polygon/gentelella/index.html
 * https://almsaeedstudio.com/themes/AdminLTE/index2.html (probably the best way for boostrap)
 * http://themedesigner.in/demo/matrix-admin/index.html (click on "Dashboard", 3rd row from top)

**Comment by mdo** [comment]
There's an offcanvas example that highlights the potential behavior you're after. For now I'll leave the dashboard example as-is.
