### ISSUE TITLE
Remove 'hover' from nav-tabs-active-link-hover-color et al

### ISSUE THREAD

**Issue by janaagaard75** [twbs/bootstrap#22073]
I seems to me that `hover` should be removed from these three variables, since the styles are applied to the tab, regardless of it being hovered or not. The has to has be active.

Current, v4-alpha.6, names:

    $nav-tabs-active-link-hover-color
    $nav-tabs-active-link-hover-bg
    $nav-tabs-active-link-hover-border-color

Proposed corrected names:

    $nav-tabs-active-link-color
    $nav-tabs-active-link-bg
    $nav-tabs-active-link-border-color

**Comment by gettinToasty** [comment]
If no one else is working on this I can do it real quick.

**Comment by mdo** [comment]
Fixed by #22087.
