### ISSUE TITLE
[Feature] Burger Menu on Desktop

### ISSUE THREAD

**Issue by iTsFILIPOficial** [twbs/bootstrap#22077]
The burger menu is becoming more popular and just used by default on many website, it would be good if we can have a class that will take all of our nav elements and just display the burger, either on the left of on the right. 

Some website with that burger style:
http://demos.creative-tim.com/rubik-agency
https://ewebdesign.com/
http://brianhoffdesign.com/#/

**Comment by idleberg** [comment]
What you're asking for is basically a hamburger-class for a standard dropdown button.

**Comment by iTsFILIPOficial** [comment]
Yeah just like on the mobile but now for the desktop.

**Comment by idleberg** [comment]
Have you tried using `<button class="navbar-toggler"…>`?

**Comment by idleberg** [comment]
It should be possible with available classes, e.g. `navbar-toggler` and `navbar-toggler-icon`

**Comment by IamManchanda** [comment]
+1

**Comment by hebbet** [comment]
probably an idea for 4.1+

**Comment by iatek** [comment]
This seems easy enough to implement already using Collapse...

http://www.codeply.com/go/jKDAY0SPBm

**Comment by mdo** [comment]
This is actually doable with v4-dev.
