### ISSUE TITLE
Orientation specific columns 

### ISSUE THREAD

**Issue by mika76** [twbs/bootstrap#22085]
It would be great is bootstrap 4 (although an enhancement for 3 would be most welcome 😄 ) would have grid columns which respond to orientation as well.

Something like 

```html
<div class="col-md-por-hidden col-md-lan-6">...</div>
```

I find that landscape mode on an iphone 6 plus or samsung s7 (largish phones) or tables have enough real estate to show separate columns which you might want to hide in portrait mode.

**Comment by bkdotcom** [comment]
https://v4-alpha.getbootstrap.com/layout/responsive-utilities/

seems like you could/should drop the col prefix.  this could be a general utility.

`hidden-md-po`

**Comment by mika76** [comment]
By adding it to the co- classes you could manipulate different layouts for landscape Vs portrait much more than just hiding or showing. Offsets, reordering and push pull with orientation could be very powerful.

**Comment by mdo** [comment]
No plans to add such classes to v4, but thanks for the suggestion!
