### ISSUE TITLE
Card group width issue in IE

### ISSUE THREAD

**Issue by arnaudriegert** [twbs/bootstrap#22089]
Consider a card group with two cards, where the width of the first card is set to a given value, say 10rem.

    <div class="card-group">
        <div class="card" style="width: 10rem;"></div>
        <div class="card"></div>
    </div>

In IE10, the second card won't expand to take all the available width.

I think the bug comes from [this line](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L217). Setting `.card-group .card { flex: 1 0 0px; }` (instead of `1 0 0`) seems to work for me (IE doesn't like a unitless `flex-basis`).

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by mdo** [comment]
Closing due to lack of response.
