### ISSUE TITLE
change .table css selector

### ISSUE THREAD

**Issue by newyhj** [twbs/bootstrap#22084]
bootstrap alpha6 source code:
.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgba(0, 0, 0, 0.05);
}
.table-hover tbody tr:hover {
  background-color: rgba(0, 0, 0, 0.075);
}
  .table-bordered th,
  .table-bordered td {
    border: 1px solid #ddd !important;
  }
-----------------------------------------------------------
html:
&lt;table class="tabe table-striped table-hover"&gt;
   &lt;tbody&gt;
   &lt;tr&gt;
      &lt;td&gt;main row&lt;/td&gt;
  &lt;/tr&gt;
  &lt;tr&gt;
    &lt;td&gt;
             &lt;table class="table"&gt;
                    &lt;tr>&lt;td>content 1&lt;/td&gt;&lt;/tr&gt;
                   &lt;tr>&lt;/td>content2&lt;/td&gt;&lt;/tr&gt;
             &lt;table&gt;
    </td>
   </tbody>
</table>

issues:
I don't want to change the style of the nested table，In fact it has changed,The style of the each table should be controlled by its own（sorry,my english so bad）

suggest change:
.table-striped>tbody>tr:nth-of-type(odd) {
  background-color: rgba(0, 0, 0, 0.05);
}
.table-hover>tbody>tr:hover {
  background-color: rgba(0, 0, 0, 0.075);
}
 .table-bordered>thead>th,
 .table-bordered>thead>td,
.table-bordered>tbody>th,
.table-bordered>tbody>td,
.table-bordered>tfoot>th,
.table-bordered>tfoot>td,
  .table-bordered td {
    border: 1px solid #ddd !important;
  }

**Comment by mdo** [comment]
We've purposefully moved away from the very specific nesting and `>` selectors in v4 to simplify our CSS and to more easily allow customization. We won't be changing that back in v4.

**Comment by devoto13** [comment]
@mdo This makes it impossible to use `.trable-striped` and other table classes with nested tables. Because it leaks onto nested table as well. See this [fiddle](https://jsfiddle.net/fe498x0u/2/) for example. Nested table is not supposed to be stripped and header of nested table is supposed to be white.

Are nested tables a not supported use case? Because I don't see how it can work without using `>` selectors.
