### ISSUE TITLE
Toggleable navbar defaults to a collapsed state

### ISSUE THREAD

**Issue by scottjehl** [twbs/bootstrap#22083]
I was implementing a navbar toggler and noticed that [the docs example](https://v4-alpha.getbootstrap.com/components/navbar/#toggler) recommends including the `collapse` class alongside `navbar-collapsed` in the source markup. This seems to ensure that the toggleable content is hidden from the start, and if Bootstrap's javascript files fail to load and/or execute, that content will still be hidden and unreachable to the user.

![image](https://cloud.githubusercontent.com/assets/214783/23383739/82f1affc-fd0d-11e6-95e9-ecdcbf071834.png)

I noticed that if I remove the `collapse` class from the starting markup, the class will still be applied by JS when the viewport size is small, and that is great! There's still a relatively minor issue of having a `<button>` that does nothing in that case (since it requires JS to function), but at least the content is all readable. Omitting the `collapse` class from the start seems to be a more resilient approach to recommend in the docs, if possible, but I admit there may be reasons this is not possible that I'm unaware of. 

As a sidenote, I understand that collapsing the content late (e.g. after JS finishes loading) is not desirable or acceptable for a smooth, fast page render. There are probably other ways, but we typically work around this situation by applying a top-level "enhanced" class immediately from a script in the head of the page, and keying many components' "collapsed" states off of that class (e.g. `.enhanced .collapse { display: none; }`), knowing that the class may later be removed if the required scripts fail to load in a given amount of time. ([article on that "optimistic" approach here](https://www.filamentgroup.com/lab/enhancing-optimistically.html))

Thanks for considering the feedback!

**Comment by mdo** [comment]
#22230 is redoing a ton, but the collapsed by default behavior isn't changing. Adding `.navbar-expand`, however, will allow this behavior.
