### ISSUE TITLE
button is displayed small in size if it has icon

### ISSUE THREAD

**Issue by SauravShaw** [twbs/bootstrap#22086]
I am trying to create a button group with some of the buttons containing text and some of them containing icon. The buttons containing icon are rendered smaller than the rest of the buttons having text

**Comment by acshef** [comment]
When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

**Comment by SauravShaw** [comment]
Operating System: Mac, Windows 7
Browser: In each of the browsers latest version I have checked this.
It's happening while running the application using AWS

**Comment by josmaissan** [comment]
Would be great if you can add a [JS Bin](https://jsbin.com/) and/or screen print. 😉

**Comment by SauravShaw** [comment]
![pasted image at 2017_02_28 09_46 am](https://cloud.githubusercontent.com/assets/26093576/23533463/efc1c500-ffd7-11e6-9cd5-bc5ef86dc570.png)

**Comment by mdo** [comment]
We need a live demo of the problem as mentioned above, not a screenshot.

**Comment by mdo** [comment]
Closing since we haven't heard back. With v4's alpha 6 release, button groups use flexbox and shouldn't have sizing issues like this.
