### ISSUE TITLE
No content for flex order responsive variations

### ISSUE THREAD

**Issue by goldboat90** [twbs/bootstrap#22080]
I read up on the Order property for flex in documentation for bootstrap 4. I understand you have flex-first and flex-last. In addition you mentioned there are responsive variations for order. However, when I add those classes to my element (e.g. "order-md-first") nothing happens at all, nor is there any content for that class.

I have flex initiated on the parent element as well. Do order classes only work when you explicitly set order in your CSS, or am I missing something?

**Comment by iatek** [comment]
Are you referring to the fact that the docs say "order-*", but the actual classes are still "flex-*"? If so there is already an issue for that.. #21739

**Comment by mdo** [comment]
Ah yeah, sorry about that. Latest fixes for CSS and docs are in `v4-dev` branch.

**Comment by gerardreches** [comment]
Damn, I was using `order-last` instead of `flex-last` too. That's confusing in the docs 😕

**Comment by mdo** [comment]
Those are still there if you're using Alpha 6. Don't use `v4-dev` if you want to use the docs that have always been, and will continue to be, updated with each release. If you're working out of a dev branch, things will break, and they'll be out of date with what's on our official site.
