### ISSUE TITLE
Modal example not working

### ISSUE THREAD

**Issue by ajithkanatt** [twbs/bootstrap#22094]
In the page http://v4-alpha.getbootstrap.com/components/modal/, the modal example under "Tooltips and popovers" is not closing if I mouse-over through the tooltip links. I tried in Chrome over a mac.

**Comment by dydemin** [comment]
The same in Opera for Windows and Android.

**Comment by patrickhlauke** [comment]
already fixed - please search the current repo before filing :) https://github.com/twbs/bootstrap/pull/21671

**Comment by ajithkanatt** [comment]
Have you tested it?

**Comment by patrickhlauke** [comment]
Have you? To be clear, http://v4-alpha.getbootstrap.com/ is v4.0.0-alpha.6 while the repo here is more up-to-date than that...
