### ISSUE TITLE
suggestion: turn btn-group into btn-group-vertical according to col width

### ISSUE THREAD

**Issue by FoxInCloud** [twbs/bootstrap#22097]
The following screenshots show the situation: .btn-group-vertical is OK on large display, KO on smaller display; .btn-group is OK on small display, KO on larger display.

There may be a CSS way to make .btn-group display differently whether it's in a large or small col-

<img width="1930" alt="capture d ecran 2017-03-02 11 15 17" src="https://cloud.githubusercontent.com/assets/8310516/23503059/4de9777a-ff3a-11e6-87a7-6bcac0c4a844.png">
<img width="1930" alt="capture d ecran 2017-03-02 11 15 25" src="https://cloud.githubusercontent.com/assets/8310516/23503056/4de6b486-ff3a-11e6-877b-e8428e163598.png">
<img width="1930" alt="capture d ecran 2017-03-02 11 15 46" src="https://cloud.githubusercontent.com/assets/8310516/23503058/4de7e978-ff3a-11e6-9a90-2f42b574d644.png">
<img width="1930" alt="capture d ecran 2017-03-02 11 17 56" src="https://cloud.githubusercontent.com/assets/8310516/23503057/4de77dd0-ff3a-11e6-9cd2-926bccd3f613.png">

**Comment by mdo** [comment]
The CSS language lacks the ability at this time to have styles that react to the size of the parent element. We can only target based on the viewport itself. There are some JS polyfills that can help out here though if you're keen on this behavior.
