### ISSUE TITLE
Suggestion: Form validation: Icons should be displayed with a generic class (v4-alpha)

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#22096]
To display an icon in an `input` element, you have to add `.has-success` to the parent element and `.form-control-success` to the `input` element like so.

```html
<div class="form-group row has-success">
      <label for="inputHorizontalSuccess" class="col-sm-2 col-form-label">Email</label>
      <div class="col-sm-10">
        <input type="email" class="form-control form-control-success" id="inputHorizontalSuccess" placeholder="name@example.com">
        <div class="form-control-feedback">Success! You've done it.</div>
        <small class="form-text text-muted">Example help text that remains unchanged.</small>
      </div>
    </div>
```
Source: https://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios

It would be great if the icon could be displayed with a generic class that displays an icon according to the parent `.has-*` class.

That would be an advantage to template languages where I would not have to check the validation status a second time on the input element, but only once on the parent element.

**Comment by tmentink** [comment]
I agree that this would be a nice improvement. I talked about this and some other form validation tweaks in issue #22192. I just updated my pull request #22344 so hopefully this will get added soon.

**Comment by mdo** [comment]
Revisiting validation states in #22762, and revisiting icons in #22762.
