### ISSUE TITLE
Add Slider and toggle components

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#22090]
I was wondering since bootstrap has been built with "mobile first" in mind, why there is no slider and toggle (which are key components in the mobile world)!

Shouldn't be new features to add to the new v4?

**Comment by HarelM** [comment]
Should be one of the top priorities, it's so basic.

**Comment by saad749** [comment]
+1 its an essential component for a lot of websites

**Comment by shyamal890** [comment]
Angular Material too has these components. Its a basic need in mobile.

**Comment by HarelM** [comment]
I migrated to material for several reasons: slider, RTL and pagination support out of the box, I don't understand how this is not implemented already in bootstrap, especially the RTL - this is a requirement as old as bootstrap...

**Comment by shyamal890** [comment]
@HarelM The only problem I have with material is that it is too style heavy. I guess we would need more designers to make sure that custom elements gel well with material elements.

**Comment by natcohen** [comment]
@HarelM Don't forget that nobody at bootstrap is paid for this project (AFAIK) while material is backed by Google... so yeah, it's a must have but be patient!

**Comment by HarelM** [comment]
True, I can't argue about it, although I don't think it's a matter of payment but priorities - bootstrap 4 has a lot of code changes but still doesn't have RTL and slider - which means it's not highly prioritized, it's not like this project doesn't have contributors and maintainers...

**Comment by cinqlair** [comment]
Totally agree, I clearly miss sliders and toggle components. 
If I had the skills, I would do it !

**Comment by natcohen** [comment]
@mdo Any chance this can be implemented in the next release?

**Comment by gijsbotje** [comment]
slider has allready been added, the switch is still in progress i guess. although i couldn't find it on any project board

**Comment by guledali** [comment]
Exactly slider has already being added. The toggle-switch, seems that they are reviewing it. 
Man I really hope it becomes part of this release.

**Comment by mdo** [comment]
Custom switch was added for v4.2 (launching soon), and the custom range was added in v4.1. Closing out!

**Comment by septatrix** [comment]
Is the "Feature Idea" project still used? If so this issue should be removed from there to keep it clean and up to date
