### ISSUE TITLE
Add utility class for overflow property

### ISSUE THREAD

**Issue by dkrutsko** [twbs/bootstrap#22091]
Apologies if this was already brought up but I didn't find any mention of it. I've come across use cases where you might want to make a div `overflow: hidden` for improved design. I would like to propose a new class (or set of classes) relating to controlling the overflow CSS property. Perhaps something like `.overflow-{visible|hidden|scroll|auto}`. These classes do not have to be responsive.

**Comment by prateekgoel** [comment]
I would like to take this up.

**Comment by mdo** [comment]
Closing per comment in #23085.
