### ISSUE TITLE
Standardize header, footer, and content language

### ISSUE THREAD

**Issue by vmike245** [twbs/bootstrap#22092]
Currently there is not a standard with how bootstrap refers to the header, footer, and content of an element. There are at least 4 items which fall into this category:

- Tooltips
  - Content: `tooltip-inner`
- Modals
  - Header: `modal-header`
  - Content: `modal-body`
  - Footer: `modal-footer`
- Card
  - Header: `card-header`
  - Content: `card-block`
  - Footer: `card-footer`
- Popover
  - Header: `popover-title`
  - Content: `popover-content`

For the most part the header and footer format is the same, but the content section seems to be on a per component basis. I would suggest standardizing the language around these sections to improve discoverability. If a user who has used cards before tries to use a modal, the first things they will try is `modal-header`, `modal-block`, `modal-footer` since that is what they used for card. Currently only 2 out of 3 of those will work. I think everyone would agree that a discoverable API is a very important part of a successful service and drastically improves ease of use.

**Comment by bkdotcom** [comment]
I vote for "body"  (which is semantically similar to table markup:  <thead>,<tbody>,& <tfoot>)

**Comment by Oxicode** [comment]
+1 body

**Comment by mdo** [comment]
Two PRs coming in #22828 and #22829 to update popover and card classes to match the modals. No changes to the tooltips given that's an odd one.
