### ISSUE TITLE
NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED

### ISSUE THREAD

**Issue by treyko** [twbs/bootstrap#22099]
I use 

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

for connect bootstrap. 

It is ok on Chrome 56.0.2924.87 , but on Chrominum Portable 56.0.2896.3 I have error on get all resources .

(index):42 GET https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css net::ERR_INSECURE_RESPONSE
(index):42 GET https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css net::ERR_INSECURE_RESPONSE
(index):45 GET https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js net::ERR_INSECURE_RESPONSE

**Comment by mdo** [comment]
You'll want to reach out to the MaxCDN folks directly regarding that. /cc @jdorfman

**Comment by jdorfman** [comment]
Thanks @mdo. @treyko Please open an issue here: https://github.com/MaxCDN/bootstrap-cdn/issues/new

Include your OS as well. (e.g. `Ubuntu 16.04.2 LTS`)

**Comment by treyko** [comment]
Thanks guys . Most likely - a build error "Chromium", which is "crooked" works with the certificate store.
