### ISSUE TITLE
(v4-alpha) List Groups with custom content are broken in IE10

### ISSUE THREAD

**Issue by drskullster** [twbs/bootstrap#22100]
On IE10 / Win8, List Group custom item text is broken. Instead of wrapping normally, it extends its width on one line.

This is due to the property `flex-flow: row wrap;` on `.list-group-item` elements. As I understand, this is kind of a hack to force vertical display without adding an extra class. I don't know how we could resolve this on IE10 though.

![image](https://cloud.githubusercontent.com/assets/1693766/23517737/7ec4041e-ff71-11e6-852b-356cf16f109a.png)

No problem on IE11 / Win10 (tested with Browserstack).

**Comment by mchirkin** [comment]
Same issue on IE11 / Win7

![image](https://cloud.githubusercontent.com/assets/11601605/23894097/e2844aa6-08b1-11e7-963b-1da8640d08e0.png)

Adding `.list-group-item > * {  max-width: 100%;  }` seems to fix the problem

![image](https://cloud.githubusercontent.com/assets/11601605/23894307/a52e94c6-08b2-11e7-8ca4-9d971300e728.png)

**Comment by mdo** [comment]
This will be nullified by fixing #21584, which will remove `display: flex` from the default `.list-group-item`.

**Comment by Superpencil** [comment]
```.list-group-item {
  display: initial
}```

for now

(also effected by length of content being too short instead of too long and collapsing the flexbox row)
