### ISSUE TITLE
(v4) customize input height not working for IE 9 to 11

### ISSUE THREAD

**Issue by changLiuUNSW** [twbs/bootstrap#22105]
Just notice that the height for inputs  is commented out:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L11
```
  // // Make inputs at least the height of their button counterpart (base line-height + padding + border)
  // height: $input-height;
```
I want to customize my input height to ```48 px```:
I do the following change: 
```
$input-line-height : 30px;
$input-padding-y: 8px:
$input-btn-border-width: 1px; 
base line-height + padding + border = 48 px
```
It works perfectly for Chrome + Firefox+ IE edge, but it does not work for IE 9-11. 

Plunker:
https://plnkr.co/edit/kJdhvFyAZmDVkeTATkiW?p=preview

Just open above link in Chrome and IE 11. You will find the difference.

Is there any workaround for this?

**Comment by wolfy1339** [comment]
IE 9 isn't supported. Have you tested on IE 11?

**Comment by changLiuUNSW** [comment]
@wolfy1339  IE 11 not working

**Comment by mdo** [comment]
`line-height` doesn't really have an affect on the computed height of `<input>`s in IE. The only way to do it right is to set a fixed `height` and apply a mix of `line-height` and `padding` alongside that. Alternatively, you can try your best to not care about slight inconsistencies across browsers.

I'll either be removing that commented out code, or redoing the input sizing a bit here soon.
