### ISSUE TITLE
[feature] Should Jumbotrons be merged with Cards since they are similar in style?

### ISSUE THREAD

**Issue by JacobLett** [twbs/bootstrap#22107]
I noticed jumbotrons use a lot of utilities to build the inner content. The major difference I saw between the .jumbotron and .card classes are inner padding, a border, and a darker gray background.

Here is a demo showing how they are similar and how you can build a jumbotron with a card class http://codepen.io/JacobLett/pen/oZxyYJ

Why would you use the jumbotron class over the card class if they essentially have the same result?

**Comment by mdo** [comment]
Heh, I have to admit I didn't anticipate someone using a card as a jumbotron. In general the jumbotron is used for a one-off large hero area at the top of the page, whereas cards are designed to be repeated  (horizontally, vertically, in a grid, etc). and operate at various levels of information density.

Honestly the bulk of the jumbotron could be removed for utilities in general, but for now I'm going to keep it around and will keep this in mind for future versions. Thanks!
