### ISSUE TITLE
_reboot overwrites $btn-primary-color var

### ISSUE THREAD

**Issue by nicmare** [twbs/bootstrap#22110]
found another reboot overwrite issue. i can not set any color for $btn-primary-color var. it will be overwritten by reboot with color: inherit
![screenshot 2017-03-03 18 00 15](https://cloud.githubusercontent.com/assets/898582/23560597/53819d0a-003b-11e7-8aa8-a75d526786b7.png)

**Comment by mdo** [comment]
This one's tough, but if you have a button without an `href` we assume different behaviors (as does the browser). For example, `href`-less links have no cursor change on hover in most browsers. If you need a button that doesn't function as a link, please use a `<button>` element.

**Comment by mdo** [comment]
Adding to that, the selector you're seeing is intentional. See the comment in our Reboot file:

```
// And undo these styles for placeholder links/named anchors (without href)
// which have not been made explicitly keyboard-focusable (without tabindex).
// It would be more straightforward to just use a[href] in previous block, but that
// causes specificity issues in many other styles that are too complex to fix.
// See https://github.com/twbs/bootstrap/issues/19402
```

**Comment by nicmare** [comment]
hey @mdo you are absolutely right. i just add href attribute and its fine for me. sorry for the issue
