### ISSUE TITLE
Modal is not closing in bootstrap 4 documentation

### ISSUE THREAD

**Issue by the94air** [twbs/bootstrap#22118]
Chrome: Version 56.0.2924.87
OS: Windows 7
[This](http://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers) modal can't be closed by any how. I tried the close buttons or clicking out of the modal. any other modal is working Great.

**Comment by Skaronator** [comment]
I tried to reproduce it but its very random. Most of the time it just works fine. 


I had to open/close it multiple times and also refresh the whole page (F5) and retry again to reproduce it.

**Comment by rafalp** [comment]
Its not really random. Here's how you reproduce:

1. Open modal
2. Hover over tooltipped link within modal
3. Modal will refuse to close because tooltip didn't flag as transitioned out

**Comment by mdo** [comment]
Closing as dupe.
