### ISSUE TITLE
Select and Multi Select Padding

### ISSUE THREAD

**Issue by gavsiu** [twbs/bootstrap#22112]
Is there a reason `select` padding isn't styled to match the `input` visually? I understand `.form-control` applies a universal padding, but even in the Bootstrap 4 doc page, the `options` don't align with other input text.

I kinda hacked a fix in `_forms.scss` and seems to work on the latest Firefox/Chrome and IE11.

    select.form-control {
        padding: $input-padding-y $input-padding-y;

      &:not([size]):not([multiple]) {
        $select-border-width: ($border-width * 2);
        height: calc(#{$input-height} + #{$select-border-width});

        padding: 0 0 0 $input-padding-y;
      }
    ...

`Select` padding issue can be seen [here](http://v4-alpha.getbootstrap.com/components/forms/#form-controls)

**Comment by gavsiu** [comment]
`.custom-select` also has the same extra padding. However, it only affects the latest Firefox. Changing the left padding fixes it for Firefox, but screws it up for IE 11 and Chrome.

[link](http://v4-alpha.getbootstrap.com/components/forms/#inline-forms)

**Comment by mdo** [comment]
`<select>`s in general are difficult to consistently style across browsers unless you go the fully custom route like `.custom-select` does. We can't force `padding` in macOS browsers without screwing up the rendering for most Windows browsers.
