### ISSUE TITLE
col-auto removes gutters

### ISSUE THREAD

**Issue by goldboat90** [twbs/bootstrap#22111]
Perhaps it is intentional, but when you add col-auto, or col-{breakpoint}-auto for that matter, it automatically removes the element's gutters. 

In my case, the first column has col-auto. It indeed fits to its content, but since there are no gutters defined for col-auto, it fits the outer edge of the row parent. As a result, it kind throws off the general flow and style of the row/column formatting. 

I feel it would be beneficial to keep gutters intact regardless of whether or not a column is given a specified column length or set to auto. For the time being I have manually added in padding. 

I couldn't find any other issues for this matter, and documentation makes no mention of it either. In the examples, they use col-12 on top of col-md-auto, so the element conveniently gets the padding from the col-12 class.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin and report back with specific browser and OS details.

**Comment by goldboat90** [comment]
Example: https://jsbin.com/borusisaxi/edit?html,output

Using Chrome, Version 56.0.2924.87 (64-bit) running on Windows 10 64-bit OS

**Comment by tvervest** [comment]
I'm experiencing the same problem on the latest `v4-dev` branch. I've applied the same fix as @goldboat90, but I'd agree that the expected behaviour would be that the gutters would remain intact.
