### ISSUE TITLE
Not able to select Nav Tabs using space bar 

### ISSUE THREAD

**Issue by iamkumaranca** [twbs/bootstrap#22127]
When tabbing through, I was not able to select the tab using space bar but works fine with Enter.

OS: Windows 7 Professional
Browser: Chrome 54.0.2840.71 and IE 11.0.9600.18537

[Test Case](https://jsfiddle.net/tsathianathan/heyfshLy/)

**Comment by mdo** [comment]
Why would you expect to select these with space bar?

**Comment by tsathianathan** [comment]
It is mostly for users using screen readers and keyboard. Some users prefer to select with space bar instead of enter key.

**Comment by stephenbe** [comment]
I would add to this, that with jaws the screen reader actually says that the tab can be open using space regardless if that functionality is there or not.

Further more,  W3C recommends this here : 

> When focus is on a tab in a tablist with either horizontal or vertical orientation:
Space or Enter: Activates the tab if it was not activated automatically on focus.

Source 
https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-15

**Comment by gameboyzone** [comment]
@iamkumaranca 

Were you able to find a solution or apply a fix which works only on the tabs for selection and doesn't scroll the page down?

**Comment by patrickhlauke** [comment]
very late response, but...finally getting around to having a proper look at tabs - will end up going for the aria practices 1.1 "tabs with automatic activation" - see https://github.com/twbs/bootstrap/issues/28918
