### ISSUE TITLE
card can't contain col-* elements

### ISSUE THREAD

**Issue by krtschmr** [twbs/bootstrap#22129]
```
.card
  .card-block
    .col left
    .col right

```

is not working. instead of having 2 cols next each other, they are under each other.
in alpha5 it was working, as we used `display: block` and not `flex`for cards. (maybe that's wrong, but that's how i see it)

in docs i don't see, that this is on purpose and i can't figure why we shouldn't be able to make cols in a card.

so we basically can't use cards as a container for wrapping the body-content. is that right?

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin and report back.

You can put columns in cards, but as always is the case with grid classes, you need a wrapping `.row`.

**Comment by iatek** [comment]
@krtschmr _ I think the `.col` need to be contained within a `.row`.

```
<div class="card">
        <div class="card-block">
            <div class="row">
                <div class="col">
                     ..
                </div>
                <div class="col">
                     ..
                </div>
            </div>
        </div>
</div>
```

And then the `.col` will [work as expected](http://www.codeply.com/go/FWlCG1cUdM). However, I'm still not sure if the grid is meant to be used within the card.

**Comment by krtschmr** [comment]
yes right, misconception of myself, forgetting about the row. why 
shouldnt it be used within a card? if a row is in a card, so then is a grid


Am 07.03.2017 um 19:12 schrieb Carol Skelly:
>
> And then the |.col| will work as expected 
> <http://www.codeply.com/go/FWlCG1cUdM>.*However, I'm still not sure if 
> the grid is meant to be used within the card.*
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by mdo** [comment]
The grid docs explain how these pieces work together: http://v4-alpha.getbootstrap.com/layout/grid/#how-it-works. The row needs to be the immediate parent of any set of columns.
