### ISSUE TITLE
Iconav not clickable when using with container-fluid

### ISSUE THREAD

**Issue by mamatopian** [twbs/bootstrap#22132]
```
<div class="with-iconav">
         <div class="iconav">...</div>
         <div class="container-fluid">...</div>
</div>
```

`container-fluid` is covering `iconav` so menuitems are not clickable. You can experience the issue here https://themes.getbootstrap.com/products/dashboard   (just switch `container` to `container-fluid`)

**Comment by mdo** [comment]
Please email our Themes support team for bug reports with the official themes.
