### ISSUE TITLE
Grid column (float) collapse prevention broken when zooming out in Safari

### ISSUE THREAD

**Issue by hvdmeulen** [twbs/bootstrap#22131]
The code to prevent columns from collapsing when they have no content breaks in Safari (on MacOS) when zoomed out. Zooming in is no problem.

Code seems to be in the grid mixins file:
```min-height: 1px; // Prevent collapsing```

Cause: 1px zoomed out becomes less then 1px (0.9px for example) and Safari decides to ignore the floating column.

Possible fix is using 1vh or just make it a bit bigger. Even 2px seems to be fine with all zoom levels.

- Operating system: macOS 10.12.2
- Browser and version: Safari 10.0.2 (12602.3.12.0.1)
- Reduced test case: https://jsbin.com/nazegucobu/2/edit?html,output (and then zoom out)

**Comment by joezcool02** [comment]
I can confirm that this is an issue and also the 2px change resolves this. 1vh is a bit much in my opinion.

**Comment by mdo** [comment]
Just noticed this is for v3.3.6, so closing given the following saved reply. Worth noting this isn't an issue in v4 given our flexbox implementation. https://jsbin.com/xenayok/edit?output

---

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
