### ISSUE TITLE
Expand the spacing utility to allow for responsive breakpoints like "pl-lg-3"

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#22134]
I don't know if this has been discussed yet, I could not find any issue except for #21943 which suggests the same thing for sizing helpers.

I would consider adding responsive capabilities to the [spacing utilities](http://v4-alpha.getbootstrap.com/utilities/spacing/) as well. This is the issue I run into the most when using Bootstrap 4. I try to use one of the spacing utilities, say `pl-3` but then I end up removing it again because the padding actually hurts on other view port sizes.

Here's an example from my current project:

![spacing-1](https://cloud.githubusercontent.com/assets/1199486/23703622/2952364c-0401-11e7-8758-9535871c9f97.png)
![spacing-2](https://cloud.githubusercontent.com/assets/1199486/23703624/2c7810e4-0401-11e7-86c9-1a12ba59408f.png)

As you see, the spacing tools end up being inappropriate for this case, because I only need the spacing on certain screen sizes. This happens in many other cases, possibly even in most cases when spacing utilities would come in handy.

I'm not sure if this is a feasible feature to implement. I could imagine code bloat and more complex code as a potential showstopper. Nonetheless I thought it would be good to at least consider this.

Examples:

`pl-1`, `pl-sm-1`, `pl-md-1`, `pl-lg-1`
`mx-3`, `mx-sm-3`, `mx-md-3`
`m-51`, `m-lg-5`

**Comment by iatek** [comment]
I think this has already been implemented and merged...

https://github.com/twbs/bootstrap/pull/20926

**Comment by arechsteiner** [comment]
Oh wow, yeah that's exactly it, and it's even implemented and usable with the current alpha. I just never thought to actually try that, since it is [not yet documented](http://v4-alpha.getbootstrap.com/utilities/spacing/). Thanks a lot, today my life got a little bit easier.
