### ISSUE TITLE
A problem about “.glyphicon” in bootstrap.css file

### ISSUE THREAD

**Issue by Koppel-Zhou** [twbs/bootstrap#22130]
Problem code in bootstrap.css:
```
.glyphicon {
  position: relative;
  top: 1px;
  display: inline-block;
  font-family: 'Glyphicons Halflings';
  font-style: normal;
  font-weight: normal;
  line-height: 1;

  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

When I use bootstrap create a search bar,like this:
```
<div class="input-group">
        <input type="text" class="form-control input-lg"><span class="input-group-addon btn btn-default glyphicon glyphicon-search"></span>
</div>
```
I find the search button shorter than the search input 1px is because of the “.glyphicon” have "top:1px".
I am a Junior from Chinese,I find have some people have same problem in stackoverflow.

**Comment by acshef** [comment]
If you want an icon in a button in an input addon, you can look at the documentation for input groups: https://getbootstrap.com/components/#input-groups

![image](https://cloud.githubusercontent.com/assets/9013284/23662608/5ff1110e-030d-11e7-89a1-ed91c1adbb9f.png)


```
<div class="input-group">
  <div class="input-group-btn">
    <button type="button" class="btn btn-default">
      <span class="glyphicon glyphicon-bold"></span>
    </button>
  </div>
  <input type="text" class="form-control">
</div>
```

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

Sorry for the inconvenience, and thanks for the suggestion, but we'll be passing on this change.

<3
