### ISSUE TITLE
Introduce card-columns-count as class

### ISSUE THREAD

**Issue by punkkeks** [twbs/bootstrap#22136]
I'd like to specify the number of columns which a .card-columns class has by using a class, e.g.
card-columns-{2,3,4}.

This would give the user the opportunity to specify the layout even further. The css would be something like this for the correspoding classes.

    .card-columns-2 {
        -webkit-column-count: 2;
        -moz-column-count: 2;
        column-count: 2;
    }

Maybe even with the sm, md, lg, xl prefix: card-columns-{sm,md,lg,xl}-{2,3,4}, so you could resolve the issue, that card decks for example aren't responsive currently, but this would lead to responsiveness. I'm currently using the sm prefix for my project to distinct between one and two columns. Works like a charm :)

**Comment by mdo** [comment]
For that level of control, I imagine the grid is what you want. I don't think we'll implement this much control over card column layout at this time. Thanks though!
