### ISSUE TITLE
[Docs] Provide Asynchronous Loader Instructions

### ISSUE THREAD

**Issue by jhabdas** [twbs/bootstrap#22139]
Improve PageSpeed scores and user experience using asynchronous loading.

Currently Bootstrap requires jQuery, and in version 4 it requires both jQuery and Tether. These scripts, and the CSS block the page render. Rather than blocking, Bootstrap should provide a mechanism to load assets asynchronously.

Loading dependencies asynchronously can be accomplished using the following library: https://www.npmjs.com/package/fetch-inject

Here's what the loader might look like:

```js
fetchInject([
  'https://cdn.jsdelivr.net/jquery/3.1.1/jquery.slim.min.js',
  'https://cdn.jsdelivr.net/tether/1.4.0/tether.min.js'
  'https://cdn.jsdelivr.net/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'
]).then(() => {
  fetchInject([
    'https://cdn.jsdelivr.net/bootstrap/4.0.0/js/bootstrap.min.js'
  ])
})
```

Please let me know your thoughts.

**Comment by Johann-S** [comment]
For me this problematic is for the developer who use Bootstrap not for the core of Bootstrap but yes it's a best practice 👍

**Comment by jhabdas** [comment]
Working on creating a Grunt plug-in now and will sub a pull against `v4-dev`.

**Comment by jhabdas** [comment]
Disregard comment about creating a Grunt plug-in. It's outside the scope of this project.

**Comment by jhabdas** [comment]
Starting with `v1.6`, Fetch Inject can now download bootstrap and all its dependencies in parallel. Here's the updated syntax:

```js
fetchInject([
  'https://npmcdn.com/bootstrap@4.0.0-alpha.5/dist/js/bootstrap.min.js'
], fetchInject([
  'https://cdn.jsdelivr.net/jquery/3.1.1/jquery.slim.min.js',
  'https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js'
])
```

https://github.com/jhabdas/fetch-inject

**Comment by jhabdas** [comment]
HN discussion regarding this approach: https://news.ycombinator.com/item?id=14380191

**Comment by mdo** [comment]
Closing given lack of interest here. Happy to re-open if the need arises.

**Comment by jhabdas** [comment]
@mdo pretty sure most people don't understand it—that's cool though the issue is here and the stargazers on the repo get it.
