### ISSUE TITLE
Reboot suggestion: iOS Safari button and input reset

### ISSUE THREAD

**Issue by mesqueeb** [twbs/bootstrap#22148]
Dear Community,

I suggest Bootstrap reboot to include some css resets for buttons and inputs on **iOS Safari**.
I am using bootstrap reboot, but iOS Safari still adds 1em padding right and left from buttons and also border radius to inputs.

**Comment by mdo** [comment]
I think we'll pass on this for now. I'm not looking to reset every property and value, even the platform-specific ones and want to take our time for changes here. Thanks though!
