### ISSUE TITLE
Tabs lost css after update to alpha 6

### ISSUE THREAD

**Issue by Wandang** [twbs/bootstrap#22141]
When reporting a bug, include:

- Operating system and version (Windows 7)
- Browser and version (Chrome 56.0.2924.87 (64-bit))
- I am using Angular2 if that is important

Switching from bootstrap 4 alpha 5 to alpha 6 removed/deapplied tab css.

Even though my tab elements are build like this:
```
<ul role="tablist" class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" [class.active]="tab.active"
    </a>
  </li>
</ul>
```

I suddenly lost the css that includes padding as you can see in this screenshot. So the tabs are ugly and small. I looked into your docs and it seems that I am using the right classes.
![padding](https://cloud.githubusercontent.com/assets/2470212/23752858/51266900-04d7-11e7-9428-28757ae4973d.PNG)

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin.

**Comment by Wandang** [comment]
I cannot reproduce it with plain html/js
