### ISSUE TITLE
Affix not working when <html> is not scrollable

### ISSUE THREAD

**Issue by DumboJet** [twbs/bootstrap#22142]
In my web page I have this CSS:

```
html {
    overflow: hidden;
}
body {
    overflow: auto; // Body has scrollbar
}
```

Apparently it makes the affix functionality break.
One reason seems to be that the events are registered on the window:

```
    this.$window = $(window)
      .on('scroll.bs.affix.data-api', $.proxy(this.checkPosition, this))
      .on('click.bs.affix.data-api',  $.proxy(this.checkPositionWithEventLoop, this))
```

Is there any way to make this work when only the body is scrollable?
(Or more general, when a custom element is scrollable)
I am not sure what are the best practices here, but having the `<html>` element scroll seems a bit weird to me.

(I use Bootstrap v3.1.1)

**Comment by Johann-S** [comment]
Support for v3 has mostly ceased. (See https://github.com/twbs/bootstrap/issues/20631)
Please let us know if this issue affects v4.

**Comment by DumboJet** [comment]
Hm...
I don't have v.4 in any project. :(
I will see what I can do...

**Comment by mdo** [comment]
*Closing given v3 status.*

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

Sorry for the inconvenience, and thanks for the suggestion, but we'll be passing on this change.

<3

**Comment by Akeri** [comment]
For anyone still dealing with this.
Use 'target' option to specify the scrollable container

```javascript
$('#scrollable').affix({
  target: 'body'
});
```

Refer to: https://getbootstrap.com/docs/3.4/javascript/#affix-options
