### ISSUE TITLE
btn-groups in input-groups in form-groups with sizing not being sized correctly

### ISSUE THREAD

**Issue by bolemeus** [twbs/bootstrap#22152]
It appears that not all elements inside a form-group with sizing options are sized correctly. (If you use form-group form-group-sm for example). In my case I have an input group inside the form-group with a btn-group inside.

I have the following code. See the following [codepen](http://codepen.io/bolemeus/pen/Nppymm)

```html
<div class="row">
  <div class="col-lg-6">
    <div class="form-group form-group-sm">
      <div class="input-group">
        <input type="text" class="form-control" />
        <span class="input-group-btn">
      <button class="btn btn-default" type="button">Go!</button>
    </span>
      </div>
    </div>
  </div>
</div>
```

Using bootstrap 3.3.7 in chrome 56.0.2924.87, but I dont think thats the issue here.
Now it does work when you add input-group-sm to the input-group, but this seems counter intuitive.
in fact it does size correctly when using bootstrap v4

**Comment by mdo** [comment]
You can remove `.form-group-sm` and that'll fix it.

---

_Beyond that, v3 isn't being actively developed, so closing as a won't fix._

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

Sorry for the inconvenience, and thanks for the suggestion, but we'll be passing on this change.

<3
