### ISSUE TITLE
Wrong spacer var in scss/variables.scss

### ISSUE THREAD

**Issue by git-no** [twbs/bootstrap#22158]
Dear Twitter, many thanks for Bootstrap.
FYI: it seems their is a small issue about variable $spacer in the latest code in Bootstrap 4.0.0 beta in variables.scss.

Actual:
```
$spacers: (
  0: 0,
  1: ($spacer * .25),
  2: ($spacer * .5),
  3: $spacer,
  4: ($spacer * 1.5),
  5: ($spacer * 3)
) !default;
```

Seems line `3: $spacer` is misspelled. Better would be `3:($spacer * 1),`

Whole section of code should be:

```
$spacers: (
  0: 0,
  1: ($spacer * .25),
  2: ($spacer * .5),
  3: ($spacer * 1),
  4: ($spacer * 1.5),
  5: ($spacer * 3)
) !default;
```
shouldn't be?

**Comment by Surfoo** [comment]
$spacer * 1 = $spacer

no? lolz

**Comment by git-no** [comment]
Sure. Sorry.
