### ISSUE TITLE
(v4) unable to override popover text color

### ISSUE THREAD

**Issue by changLiuUNSW** [twbs/bootstrap#22153]
I change ```$popover-bg``` to ```black``` and also want to change text color to ```white```, but I cannot find variable for popover text color. 

I suggest we should expose a variable for popover text like ```$popover-color```

**Comment by praveenpuglia** [comment]
I would suggest adding two variables with the following defaults.
```scss
$popover-title-color   : $headings-color;
$popover-content-color : $body-color;
```

I can send a PR if adding it is finalized.

**Comment by praveenpuglia** [comment]
I sent the PR anyway. If the ability to change color doesn't need to be present, please ignore it.
