### ISSUE TITLE
Popover and Tooltip docs don't mention disable() or enable()

### ISSUE THREAD

**Issue by airandfingers** [twbs/bootstrap#22162]
I have a popover that I need to enable or disable depending on user actions. I checked the docs at http://getbootstrap.com/javascript/#popovers-methods, and only saw the initialize/destroy methods, so I wrote my code creating and destroying the popover each time.

I ran into some problems with this approach, so I dug into your code a bit, and I found that Popover extends the Tooltip class, which has a number of methods that aren't documented on the page above, including `disable` and `enable` that perfectly suit my use case.

These functions already work, using the same `.popover('disable')` syntax as the other methods, so why aren't they documented for either [Popovers](http://getbootstrap.com/javascript/#popovers-methods) or [Tooltips](http://getbootstrap.com/javascript/#tooltips-methods)?

**Comment by mdo** [comment]
Unsure honestly, but we're not working on v3 right now, so labeling this and closing for now.

---

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

Sorry for the inconvenience, and thanks for the suggestion, but we'll be passing on this change.

<3

**Comment by airandfingers** [comment]
As far as I can tell, the [Tooltip](https://v4-alpha.getbootstrap.com/components/tooltips/#methods) and [Popover](https://v4-alpha.getbootstrap.com/components/popovers/#methods) docs and [code](https://github.com/twbs/bootstrap/blob/v4-dev/js/dist/tooltip.js#L143) are unchanged in this respect.

Shouldn't the v4 docs reference disable and enable?

**Comment by Johann-S** [comment]
``enable`` and ``disable`` are public methods in V4 (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L176-L182) so we can update the documentation IMO

**Comment by mdo** [comment]
Can we get a separate issue (or PR!) for the v4 docs update on this?
