### ISSUE TITLE
(v4) white-space should be normal when using btn-link

### ISSUE THREAD

**Issue by changLiuUNSW** [twbs/bootstrap#22163]
When button with ```btn-link``` has a long text, the text will continue growing outside the screen. 

To keep consistent with behavior of link ```<a>```, we should add following style:
```
white-space: normal;
text-align: left;
```

https://plnkr.co/edit/cE7gYzwIu32ykHIvTGoe?p=preview

**Comment by oktalk** [comment]
I would also kill the left and right padding.

**Comment by mdo** [comment]
This defeats the purpose of the `.btn-link`. Take that away and it's just a regular link, so if you need that I'd suggest removing the class entirely.
