### ISSUE TITLE
Placeholder text is overlapped.

### ISSUE THREAD

**Issue by nuttikung** [twbs/bootstrap#22169]
I'm not sure is it **bootstrap or angular 2** issue becuase I use both.

The issue is about input when I try to put place holder for Chrome is not a problem but for safari after angular 2 put the data it's still placeholer and text is overlapped.

see the screenshot as below : 
This screenshot from my Safari
<img width="629" alt="problem_placeholder" src="https://cloud.githubusercontent.com/assets/8456620/23831317/33ff6e4a-0751-11e7-959d-ea81240bc2b6.png">

and this from Chrome
<img width="612" alt="chrome_screenshot" src="https://cloud.githubusercontent.com/assets/8456620/23831331/70c06b18-0751-11e7-826b-e2204087635f.png">

or any suggestion?

If you need more information, please let me know.
Thanks,
Phudit.C

**Comment by patrickhlauke** [comment]
That's an Angular (or something else you're running in addition?) issue, as Bootstrap doesn't do any weird trickery of putting positioned text over existing form controls. Suggest asking on StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
