### ISSUE TITLE
Any reason as to why img-rounded radius is set to 0?

### ISSUE THREAD

**Issue by DualPixel** [twbs/bootstrap#22161]
I've been using Bootstrap for quite some time (Almost years now) and i never got to use **img-rounded** just because i always had a separated CSS Stylesheet for avatars and stuff. 

But today i was going to use it and realized that by default **img-rounded** has gotten its border set to **border-radius: 0**

![border](https://cloud.githubusercontent.com/assets/5727180/23815953/e07b6b9a-05c8-11e7-9604-06194b0a3d4d.png)

**Comment by razh** [comment]
This is for Bootstrap 3. `.img-rounded` continues to have a `border-radius` value: https://github.com/twbs/bootstrap/blob/v3-dev/less/scaffolding.less#L86

Please make sure that someone has not edited your copy of that file, or has changed the value of `@border-radius-large`/`$border-radius-large` if you're using Less/Sass.

**Comment by mdo** [comment]
Closing give above comment.
