### ISSUE TITLE
checkboxes slightly unaligned from v3 to v4

### ISSUE THREAD

**Issue by nippur72** [twbs/bootstrap#22170]
I noticed that in v4 the boxes from checkboxes and radios are vertically unaligned by a small amount, see the screenshot attached:

![checkboxes](https://cloud.githubusercontent.com/assets/2598443/23833382/e706135c-0744-11e7-9c99-a4669274a9bd.png)

The screenshot was taken with Chrome at 800% opening the example pages for v3 and v4.

**Comment by mdo** [comment]
They'll look slightly off given the font changes across all browsers in v4. No real way of getting them 100% lined up I'm afraid. Open to specific suggestions if there's something that looks better to you across Mac and Windows.

**Comment by nippur72** [comment]
I'm not a CSS expert and I am new to bootstrap, but in my project I'm using the following hack to make checkboxes look aligned:
```css
.form-check-input:only-child {
   position: relative;
   top: 0.07rem;   
}
```
they look good in Chrome, Firefox, Edge and IE (all them on Windows).
