### ISSUE TITLE
[BS4] Clarification for .col-form-label vs .form-control-label

### ISSUE THREAD

**Issue by shuriu** [twbs/bootstrap#22173]
Currently [the docs (Using the grid)](https://v4-alpha.getbootstrap.com/components/forms/#using-the-grid) specify using `.col-form-label`, but the [validation examples](https://v4-alpha.getbootstrap.com/components/forms/#examples) contain `.form-control-label` classes for labels.

From my testing and looking at the source it seems that `.col-form-label` handles both alignment and validation colors.

Whatever the intention for the label classes may be for stable releases, to me this seems a thing that can be clarified better in the docs, and I'd be happy to contribute.

**Comment by mdo** [comment]
Should be clarified given #22395 was just merged—validation styles have been overhauled.
