### ISSUE TITLE
Issue with outline on <a> tag.

### ISSUE THREAD

**Issue by souravbadami** [twbs/bootstrap#22172]
![screenshot from 2017-03-13 14 45 06](https://cloud.githubusercontent.com/assets/11073943/23845645/e5163c2c-07fb-11e7-9c38-9e5306589fa9.png)

It'll be better if there's no outline by default instead of specifying it.
**Browser:** Mozilla Firefox 51.0.1

**Comment by patrickhlauke** [comment]
You seem to be filing an issue about github's UI, rather than bootstrap?

**Comment by souravbadami** [comment]
@patrickhlauke -- Ah, I have experienced this issue before using the framework on my project. I just saw it on github too and so filed the issue.

**Comment by hultberg** [comment]
@souravbadami If this is an issue with bootstrap, it will help if you reference to the project itself and not github. :smile:

**Comment by souravbadami** [comment]
@hultberg -- Here: http://mycleanindia.herokuapp.com/app. Source: http://github.com/mycleanindia/mycleanindia/.
