### ISSUE TITLE
mr_left iPhone

### ISSUE THREAD

**Issue by Godminders** [twbs/bootstrap#22171]
`

        @* -- Logo -- *@

        <nav class="navbar navbar-inverse bg-inverse hidden-sm-up">

            <a class="navbar-brand ml-auto mr-auto" href="#">

                <img src="~/assets/images/godminders-logo.png" width="202" height="50" alt="">

            </a>

        </nav>

`
The above code works fine for centering the logo on Desktop.  It also centers it fine in Chrome DevTools when simulating a mobile.

On the iPhone itself though, the Logo moves flush left.   Also if I remove the mr-auto, as expected in Desktop the logo shifts flush right.  However on the actual iPhone it remains flush left.

**Comment by Godminders** [comment]
mx-auto does not work either.  Brand logo remains flush left on iPhone regardless.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin and report back with specific browser and OS details.

**Comment by mdo** [comment]
Closing due to lack of response. Might be similar to #21745 though, too.
