### ISSUE TITLE
The List-group does not recognize text alignment

### ISSUE THREAD

**Issue by marcoarib** [twbs/bootstrap#22179]
I'm trying to align the items from a List-group with "text-center", but it does not recognize the rule.

Here is the test: https://jsfiddle.net/marcoarib/0t9htcoa/3/

**Comment by mchirkin** [comment]
Try to use "justify-content-center" instead of "text-center"
https://jsfiddle.net/mchirkin/efjjvxzr/1/

**Comment by marcoarib** [comment]
> Try to use "justify-content-center" instead of "text-center"
https://jsfiddle.net/mchirkin/efjjvxzr/1/

Thanks, but put a class in every list item can't be a good solution. This a list and I think it should to recognize the alignment used on the parent element.

**Comment by mchirkin** [comment]
"list-group-item" has `display: flex` so `text-align: center` does not work
You can wrap text in "list-group-item" in div with 100% width
https://jsfiddle.net/0t9htcoa/5/

**Comment by marcoarib** [comment]
Changing the "**display**" propertie to "**block**" on "**.list-group-item**" seems to be a good workaround to use "**text-center**" on the "**.list-group**" element:
https://jsfiddle.net/marcoarib/0t9htcoa/6/

**Comment by mdo** [comment]
Closing as this isn't a bug. Flex items require different properties and values to achieve certain styles.
