### ISSUE TITLE
Img-fluid resize in IE11

### ISSUE THREAD

**Issue by NightFlash82** [twbs/bootstrap#22187]
Bootstrap 4 alpha-6

When resizing a image with img-fluid on in a div the div keeps the size of the div but the image is resized.
Yet again works in FF and Chrome and not in IE.

Left is IE 11 and the surrounding div is huge, cause that's the img real size, on Chrome to the right the div is smaller and resized to match the img-fluid image. I'm using this in a collapsable menu.

![bs4-error1](https://cloud.githubusercontent.com/assets/7119894/23893556/35e130f0-089f-11e7-84e5-a3aacb19b33c.jpg)

**Comment by mdo** [comment]
I believe this is one of the many flexbox bugs we're facing. Try `.w-100` instead.

**Comment by go-rost** [comment]
use `overflow: hidden` for external container

**Comment by miestr** [comment]
The issue still appears in v4.1.1 and IE 11. Both solutions `.w-100` and `overflow:hidden` do not help.

**Comment by tschortsch** [comment]
For me setting `flex-shrink-0` on the outer flex container helped.

**Comment by MickL** [comment]
Same problem. Why is this closed?
