### ISSUE TITLE
4.0 alpha not rendering tabs using w3schools sample

### ISSUE THREAD

**Issue by TLKG** [twbs/bootstrap#22180]
see this [plunker](http://plnkr.co/edit/DfZ6R9FGnH96GrcsBeDv).

based on w3schools, the last sample on the [bottom](https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp).

**Comment by jipexu** [comment]
you must use show instead of in

class="tab-pane fade show active"

**Comment by rafalp** [comment]
W3Schools is not the origin of truth for Bootstrap's markup. Official bootstrap's docs are.

**Comment by mdo** [comment]
Closing per comments above.
