### ISSUE TITLE
.btn width different on <a> and <button> or <input>

### ISSUE THREAD

**Issue by EikiProg** [twbs/bootstrap#22181]
Hi, I'm on Windows 10 and verified this on lastes FF, Chrome and EDGE
Here some exemple: [https://jsfiddle.net/Lw8m1w53/](https://jsfiddle.net/Lw8m1w53/)

As you can see `button` and `input` render the same but the `a` in the middle is less large and the font-size seem more small and/or the baseline is not he same.

At start I was thinking that it was FF behavious but after verifying in Chrome and Edge that seem to not be the case.

I checked to the extend of my capacity but in the end not finding anything to help.

That show the same in [https://v4-alpha.getbootstrap.com/components/buttons/#button-tags](https://v4-alpha.getbootstrap.com/components/buttons/#button-tags) if you replace the "Link" text by "Button" in `a`

**Comment by mchirkin** [comment]
It seems that `a` has different `font-family` than `button` and `input`
Setting the same font-family to ".btn" can fix the problem
`.btn { font-family: sans-serif; }` 
https://jsfiddle.net/Lw8m1w53/1/

**Comment by mdo** [comment]
Font family was fixed in `v4-dev`.
