### ISSUE TITLE
Do You have any updates for rotate(or flip) glyphicon ? 

### ISSUE THREAD

**Issue by baladkb** [twbs/bootstrap#22184]
Hi @mdo, I'm using bootstrap it's use full for me and do You have any updates for rotate(or flip) glyphicon ?

**Comment by patrickhlauke** [comment]
Glyphicons are not part of v4 anymore, and v3 is now purely in maintenance mode...so unfortunately there won't be any more changes/fixes around glyphicons here I'm afraid.

**Comment by baladkb** [comment]
@patrickhlauke  Ok.
