### ISSUE TITLE
[BS4] Carousel not working well in IE11.

### ISSUE THREAD

**Issue by pappabj0rn** [twbs/bootstrap#22198]
I'm seeing several issues with the carousel in IE11.
* Transitions don't really work
* Indicators are a bit of to the right
* During transition, captions from both current and next slide are showing

Tested on Win 7, 8.1 and 10 with IE11.

Issues are live on https://v4-alpha.getbootstrap.com/components/carousel/#with-captions

![2017-03-15_20-51-03](https://cloud.githubusercontent.com/assets/637452/23970944/1ac8096e-09cc-11e7-8ded-b3b1fef293b2.gif)

**Comment by seberik** [comment]
The transition seems not work due to the feature media-query `if-supports-3d-transforms`.

**Comment by quicoto** [comment]
@mdo should this changes be already live in https://v4-alpha.getbootstrap.com/components/carousel/#with-captions ? 

I just tested the page on a Win10 IE11 and I still don't see the transitions. Also indicators are a bit to the right site (not centred).

I have also tried downloading the v4-dev branch to test it locally. Same issue.

**Comment by Johann-S** [comment]
This changes will be available on our next release @quicoto

**Comment by quicoto** [comment]
Thank you @Johann-S 

No ETA at the moment?

**Comment by Johann-S** [comment]
No but you can follow the progress here : https://github.com/twbs/bootstrap/milestone/41

**Comment by romaricdrigon** [comment]
Anyone found out how to center carousel indicators?

**Comment by romaricdrigon** [comment]
It seems again it is a unsupported `max-width` issue.
Following code solved my issue, in case someone else drops here:
```css
.carousel-indicators li {
    width: 30px;
}
```

I'm not sure about the side effects though.

**Comment by dana6** [comment]
This issue is still happening. Any fix yet?

**Comment by josejohnandrew** [comment]
Hi!

I made a simple sass fallback for IE to use fadeout effect instead of slide.
Just add **carousel-fade** class to your carousel container, and IE will use fadeout instead of slide. I hope this helps someone

`@media all and (-ms-high-contrast:none), (-ms-high-contrast:active) {
  
  .carousel-fade {
    .carousel-item {
      display: block;
      position: absolute;
      opacity: 0;
      transition: opacity .75s ease-in-out;

      &.active {
        opacity: 1;
      }
    }
  }
 
}`

**Comment by martindohko** [comment]
<meta http-equiv="X-UA-Compatible" content="IE=11" />

**Comment by martindohko** [comment]
You can try to specify the compatibility mode in the document header with:

<meta http-equiv="X-UA-Compatible" content="IE=11" />

**Comment by martindohko** [comment]
You can try to specify the compatibility mode in the document header with:
`<meta http-equiv="X-UA-Compatible" content="IE=11" />`
