### ISSUE TITLE
open dropdown menu in navbar results in changed viewport width

### ISSUE THREAD

**Issue by christianmalek** [twbs/bootstrap#22195]
If I position a dropdown menu on the right side in the navbar and open it, it changes the viewport width.

Here is a fiddle: http://jsfiddle.net/4r7059hk/5/

edit: Seems like not everybody has this problem with the fiddle. Because of that here is a picture showing the rendering in my browser:
![image](https://cloud.githubusercontent.com/assets/2873986/23950253/a2f650da-098a-11e7-9486-3043ec43d66b.png)

I use Bootstrap version `4.0.0-alpha.6`.

**Comment by patrickhlauke** [comment]
You'll need to add the `dropdown-menu-right` class - see http://v4-alpha.getbootstrap.com/components/dropdowns/#menu-alignment

**Comment by patrickhlauke** [comment]
http://jsfiddle.net/euu8b4y5/

**Comment by christianmalek** [comment]
@patrickhlauke Thanks! I just looked in the navbar section.
