### ISSUE TITLE
Cover not working with bootstrap-theme.min.css

### ISSUE THREAD

**Issue by typical-h** [twbs/bootstrap#22201]
Cover is not working with bootstrap-theme.min.css I am using Chrome, with Windows.

**Comment by patrickhlauke** [comment]
as per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker please provide a reduced test case showing the problem.

**Comment by mdo** [comment]
Also, theme file is for v3, which we're not actively working on right now. Tagging and closing.
