### ISSUE TITLE
format <blockquote> without `class="blockquote"`

### ISSUE THREAD

**Issue by xenoterracide** [twbs/bootstrap#22203]
downstream bug https://github.com/alanorth/hugo-theme-bootstrap4-blog/issues/50

using v4.alpha6

I think that like bootstrap 3, that just having

```
<blockquote>
   <p>foo</p>
</blockquote>
```

should be a valid blockquote, I can see wanting or needing the class for more advanced things, but semantically rendered html from sources like markdown should work without adding the class, imho.

**Comment by mdo** [comment]
We're sticking with the class name to limit scope of our styles.
