### ISSUE TITLE
v4: Dropdown toggle not working after hiding

### ISSUE THREAD

**Issue by mroftalp** [twbs/bootstrap#22208]
I've used `$().dropdown('toggle')` to hide the dropdown but after that the dropdown won't show anymore.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin and report back with specific browser and OS details.

**Comment by mroftalp** [comment]
@mdo Hi man! Can you check out this link https://jsbin.com/ranapahihi/edit?html,css,js,console,output

**Comment by praveenpuglia** [comment]
I cannot say for sure if the behaviour is intended but here's a run down of what's happening.

- I think the current dropdown toggle function expects that only the button inside `.dropdown` to trigger it. So...
- When you execute the toggle() function using the __Hide Dropdown__ button, that button's reference gets passed to toggle function as if it was the button inside `.dropdown`.
- To be specific, [this](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L91) is where things get messed up. The `var parent = Dropdown._getParentFromElement(this);` gets the `div.p-4.show` as the parent and not the `.dropdown`.
- After you have clicked the button, the `div.p-4` gets a class `show` and then on it just returns false assuming the dropdown is already shown.

**Comment by vanduynslagerp** [comment]
The `$().dropdown('toggle')` has to be called on the dropdown trigger. See https://v4-alpha.getbootstrap.com/components/dropdowns/#via-javascript

It works If you change your js function for:
```js
function hideDropdown() {
  $('#dropdownMenuButton').dropdown('toggle');
}
```
See https://jsbin.com/civimovoxa/edit?html,js,output

**Comment by mdo** [comment]
Closing per latest comment's fix. Lemme know if we need to revisit.
