### ISSUE TITLE
Appearance of the badge

### ISSUE THREAD

**Issue by claudioalmeiida** [twbs/bootstrap#22205]
I think it would be interesting to change the appearance of the badge, since it can be mistaken for a button because it looks the same. Here is my suggestion of appearance:

![image](https://cloud.githubusercontent.com/assets/942899/24024242/2e05cec8-0a88-11e7-88b8-16543a73bd43.png)

`
.badge-default {
    border-left: 4px solid #636c72;
    color: #636c72;
    background-color: #d6d6d6;
}
.badge-primary {
    border-left: 4px solid #0275d8;
    color: #0275d8;
    background-color: #b3d0ea;
}
.badge-success {
    border-left: 4px solid #5cb85c;
    color: #5cb85c;
    background-color: #dff0d8;
}
.badge-info {
    border-left: 4px solid #5bc0de;
    color: #5bc0de;
    background-color: #d9edf7;
}
.badge-warning {
    border-left: 4px solid #f0ad4e;
    color: #f0ad4e;
    background-color: #fcf8e3;
}
.badge-danger {
    border-left: 4px solid #d9534f;
    color: #d9534f;
    background-color: #f2dede;
}
`

**Comment by rahulteja16** [comment]
Hi,
I want to pick this up and submit a PR if any one has not yet picked it up.
Please let me know. Thanks.

**Comment by mdo** [comment]
Thanks, but I'm happy with how they look now.
