### ISSUE TITLE
Card order not working on XS devices; .card-deck is not a flex

### ISSUE THREAD

**Issue by vliegelientje** [twbs/bootstrap#22206]
Rearranging cards does not work on mobile devices as expected. 
Setting an "order" has no effect because .card-deck on XS devices is a "display: block" instead of a "display: flex".

I would suggest to use flexbox even on XS devices so ordering of the cards in CSS is possible:

```
.card-deck {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-flow: row wrap;
    -ms-flex-flow: row wrap;
    flex-flow: row wrap;
}
```

**Comment by iatek** [comment]
A workaround is to use the flexbox utils..

`<div class="card-deck d-flex flex-column flex-sm-row">..</div>`

[Demo ](http://www.codeply.com/go/7e5zO42ePR)

**Comment by mdo** [comment]
#22860
