### ISSUE TITLE
navbar all most imposible to style

### ISSUE THREAD

**Issue by Global-Open-Source** [twbs/bootstrap#22215]
Bootstrap use !important way to much, this make it incurable hard to style. And should be fixed. I can offer my help to make this, (found many bugs and preferments problem in the code) Anyways so should bootstrap update the grid witch a more custom-able navbar

**Comment by mdo** [comment]
Can't help you much with such a vague issue. We use `!important` on our utilities only; everything else is styled with classes wherever possible. 

> found many bugs and preferments problem in the code

Please do list them or open new issues and we can resolve them.

> Anyways so should bootstrap update the grid witch a more custom-able navbar

Grid isn't attached to the navbar, not sure what you're looking for here.
