### ISSUE TITLE
Only xl is for desktop

### ISSUE THREAD

**Issue by Global-Open-Source** [twbs/bootstrap#22214]
I the documentation you say that lg is desktop and xl is for large desktop.

I have a macbook pro 15" Rentia and a iMac 27" Full HD, and there is no diffrent between lg and xl

**Comment by mdo** [comment]
It's not based on the physical size of your screen, but the available pixels in your browser's viewport. Furthermore, we use those names and sizes as rough benchmarks for screen sizes and don't always apply additional styles across each. We largely leave that up to you.

If there's a specific bug you're seeing, please do open a new issue with an example.

**Comment by Global-Open-Source** [comment]
Yes, but this also mean that bootstrap doesn't support High Revulsion screen. 
with other words: `min-device-pixel-ratio` and `min-resolution`

**Comment by patrickhlauke** [comment]
the pixel density may be different, but the actual number of CSS pixels between a retina and non-retina are the same, and that's what counts. if you wish to make your designs smaller (to fit more stuff in?) for high density displays, then that's something we're not planning to implement as it's not very user-friendly.
