### ISSUE TITLE
Incorrect cursor in case of input in legend of disabled fieldset

### ISSUE THREAD

**Issue by MarkoNV** [twbs/bootstrap#22226]
By spec, the disabled attribute, when specified, causes all the form control descendants of the fieldset element, excluding those that are descendants of the fieldset element's first legend element child, if any, to be disabled.

https://html.spec.whatwg.org/multipage/forms.html#the-fieldset-element

HTML:
```
<fieldset disabled="disabled">
<legend><div class="checkbox"><label><input type="checkbox"> Not disabled</label></div></legend>
<div class="checkbox"><label><input type="checkbox"> Disabled</label></div>
</fieldset>
```

Expected behaviour: Disabled label should has not-allowed cursor, but Not disabled shouldn't.
Observed behaiour: Not disabled label also has not-allowed cursor.
Bootstrap version: v3.3.7

CSS causing error:
```
.checkbox.disabled label, 
.radio.disabled label, 
fieldset[disabled] .checkbox label, 
fieldset[disabled] .radio label {
    cursor: not-allowed;
}
```

Suggested solution:
```
.checkbox.disabled label, 
.radio.disabled label, 
fieldset[disabled] > .checkbox label,
fieldset[disabled] > .radio label,
fieldset[disabled] > :not(legend) .checkbox label,
fieldset[disabled] > :not(legend) .radio label {
    cursor: not-allowed;
}
```

Notice: it's possible that there are other selectors affected with same problem.

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
