### ISSUE TITLE
Pointer disabled button

### ISSUE THREAD

**Issue by Thibault34** [twbs/bootstrap#22222]
Hello,

When button link is disabled, curors "cursor: not-allowed;" not found.

https://v4-alpha.getbootstrap.com/components/buttons/#disabled-state

**Comment by mdo** [comment]
This is another problem with the `pointer-events: none` property. We apply that to anchor based buttons, but not the `<button>` elements. Any element with that doesn't get `cursor` changes.

/cc @patrickhlauke

**Comment by patrickhlauke** [comment]
On the road, so can't dig into the code...but I'm slowly wondering if we should drop the `pointer-events:none` and live with the fact that if authors use anchor-based buttons, they're going to have a bad time / it's the wrong way to do it...

**Comment by mdo** [comment]
I'm fine with that I think. We've run into that issue in a few place without buttons too though, so will want to take inventory of all that before moving forward.

Holler when you're back and ready to dig in!

**Comment by patrickhlauke** [comment]
@mdo actually related to this...i've been pondering, along the same lines as the decision to remove `cursor` things relating to buttons and faked buttons, if there's any chance to remove the actual `cursor: not-allowed` instances? browsers don't normally use the "not-allowed" cursor in these circumstances, so it makes BS a bit opinionated here. (and, at least on Windows, the "not-allowed" cursor looks rather fugly with its red colour compared to other regular mouse pointers)

> ![capture](https://cloud.githubusercontent.com/assets/895831/24841663/1f9bbd46-1d81-11e7-9e96-54502b731edf.PNG)

**Comment by runderworld** [comment]
years late to the party on this one, but i think a better solution would have been to default the 3.x-era `$cursor-disabled` variable to null/empty, and then users can reenable as needed.  I totally agreed with the reasoning behind removing the `not-allowed` styling as the *default*, but just suggesting this kind of strategy in the future.
