### ISSUE TITLE
$btn-focus-box-shadow variable does not trickle down to button variants

### ISSUE THREAD

**Issue by sernstberger** [twbs/bootstrap#22225]
In v4, we now have:
`$btn-focus-box-shadow:           0 0 0 2px rgba($brand-primary, .25) !default;`

If I change it to:
`$btn-focus-box-shadow:           0 10px 25px rgba($black, .15) !default;`

Doesn't work. :/ This is overridden by individually by each button variant. Take this for example:
<img width="300" alt="screen shot 2017-03-20 at 12 50 37 pm" src="https://cloud.githubusercontent.com/assets/7228039/24111288/5ae7f98e-0d6c-11e7-9225-fd30e5f3fd6e.png">

There's 2 solutions that would make sense to me:
1. individual button styles shouldn't override this
2. there should be separate variables for focus-box-shadow on each button variant (for example: $btn-info-focus-box-shadow)

Thank you!

**Comment by bwalendz** [comment]
Pull request submitted for this https://github.com/twbs/bootstrap/pull/22354

**Comment by geocode64** [comment]
Another attempt at fixing this issue: #22752

**Comment by mdo** [comment]
This is intentional. Each button variant is meant to have a matching focus style.
