### ISSUE TITLE
Link not working in Bootstrap 4 card view

### ISSUE THREAD

**Issue by ayush554** [twbs/bootstrap#22220]
http://jsfiddle.net/n4kcccyh

check the above js fiddle link
the link inside the card view is not working i am using bootstrap 4 please provide the solution

**Comment by iatek** [comment]
There are various problems with the code structure. The link is not working specifically because you have `z-index: -1` on the container.

**Comment by mdo** [comment]
Closing since this isn't a bug in Bootstrap.
