### ISSUE TITLE
Height for form-control-static inside form-group-sm is fixxed, which causes multiline form-control-static fields to overlap

### ISSUE THREAD

**Issue by bolemeus** [twbs/bootstrap#22240]
When using a form-control-static field inside of form-group-sm (I think other sizes as well) the height of the field becomes fixxed. This causes overflow to overlap with the next lines.

I couldn't find a duplicate issue, but I did find this one (https://github.com/twbs/bootstrap/issues/15536) where it seems to have been introduced.

[Codepen here](http://codepen.io/bolemeus/pen/rydgEW)

I'm using the latest bootstrap version 3.3.7

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
