### ISSUE TITLE
Navbar justify-content-end dropdown not staying in container-fluid

### ISSUE THREAD

**Issue by parityhero** [twbs/bootstrap#22243]
JSBin: http://jsbin.com/wijelawuso/edit?output

Click on "Matt" in the top right and notice the body horizontal overflow turns to scroll.

Fixed by adding the following css :
    .container-fluid .navbar-nav.justify-content-end .dropdown-menu {
      right: 0;
      left: auto;
    }

OS: Windows 7 Pro
Browser: Chrome 57 (latest stable)

**Comment by mdo** [comment]
This is easily addressed with `.dropdown-menu-right`. See http://v4-alpha.getbootstrap.com/components/dropdowns/#menu-alignment.
