### ISSUE TITLE
4.0.alpha.6: Navbar Text inconsistency

### ISSUE THREAD

**Issue by Skaronator** [twbs/bootstrap#22248]
I've noticed that the navbar-brand is closer to the left side of the navbar than the link on the right side.

Thats because the `.navbar-brand` doesn't have [margin on the left side](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L42). While the `.nav-link` has [padding all the way around](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L155-L158).

![image](https://cloud.githubusercontent.com/assets/2886913/24235356/31837518-0f9d-11e7-9e8a-11f7a996213a.png)

____

Also noticed different `line-height` on `.nav-brand` vs `.nav-link` but I assume this has been made to match the different font-size at some point.

![image](https://cloud.githubusercontent.com/assets/2886913/24235195/70855f20-0f9c-11e7-99e8-d08ddc9c42f5.png)

**Comment by Skaronator** [comment]
Maybe something like this to avoid padding on the very left and very right element:
```
.nav-link:not(:first-child) {
	padding-left: .5rem;
}
.nav-link:not(:last-child) {
	padding-right: .5rem;
}
```

And add some more margin-right to the ´.nav-brand´ to equalize the missing padding.

**Comment by mdo** [comment]
This is intentional, though we could decrease that `.navbar-brand`. I'll think on it while working on navbar stuff in #22230.
