### ISSUE TITLE
Form controls docs

### ISSUE THREAD

**Issue by matsaman** [twbs/bootstrap#22244]
> https://v4-alpha.getbootstrap.com/components/forms/#form-controls
> Remember, since Bootstrap utilizes the HTML5 doctype, all inputs must have a type attribute.

I don't know whether bootstrap requires this, but HTML5 certainly does not:
http://w3.org/tr/html5/forms.html#attr-input-type

**Comment by JayteeNZ** [comment]
I don't see what your point is here?

Regardless whether it's required or not, you still need a type to determine the input. I've never seen anyone leave the type blank (which defaults to a text box).

**Comment by bkdotcom** [comment]
> I don't see what your point is here?

His point is "the HTML5 doctype requires all inputs to have a type attribute" is patently false.

> I've never seen anyone leave the type blank

anecdotal

> (which defaults to a text box)

exactly, `type` is NOT required

**Comment by mdo** [comment]
This was added to our docs long ago after situations like https://github.com/twbs/bootstrap/issues/170, https://github.com/twbs/bootstrap/issues/246, and https://github.com/twbs/bootstrap/issues/4089.

**Comment by bkdotcom** [comment]
Since bootstrap no longer uses the `input[type="text"]` selector, I don't *think* this still applies?
