### ISSUE TITLE
list-group overflow-y list-group-flush bug?

### ISSUE THREAD

**Issue by mcleangm** [twbs/bootstrap#22242]
Here is a test where scrolling ul does not seem to work... think it worked in alpha5
http://codepen.io/anon/pen/PpRKyJ

**Comment by satyajit11** [comment]
@mcleangm use overflow-y: scroll; instead of auto

[codepen](http://codepen.io/satyajit11/pen/KWBmaR)

**Comment by mcleangm** [comment]
overflow-y: scroll does not work in my code pen the top-border is clipped off
also I do want scroll bars to show when list grows past height

**Comment by mdo** [comment]
This doesn't sound like a Bootstrap bug—I'm seeing the second example scroll just fine. Showing scrollbars isn't fully up to you; that's an OS setting (for example, macOS can disable them until scrolling is attempted).
