### ISSUE TITLE
Uncaught Error: Collapse is Transitioning 

### ISSUE THREAD

**Issue by Rishabhk94** [twbs/bootstrap#22256]
Hi, 
I am using a CDN link for bootstrap v4-alpha , and on every click of accordian/collpase I get the following error on my console, what could be a possible fix for this? I am using the sample code used in the bootstrap docs, with a few tweaks.
![untitled](https://cloud.githubusercontent.com/assets/25672349/24284686/86a7607c-1092-11e7-84ca-c7fc9e2c15d5.png)

**Comment by Johann-S** [comment]
Related to https://github.com/twbs/bootstrap/pull/21743
