### ISSUE TITLE
Flex grid problem for form element fieldset and legend 

### ISSUE THREAD

**Issue by krishnanandsaha** [twbs/bootstrap#22255]
The flex grid system is not working on google chrome and firefox for form element fieldset and legend.

We are using Bootstrap 4 Alpha-6. We have tested on chrome version  56.0.2924.87 and firefox version 52.0.1 .

Sample link is : https://jsfiddle.net/krishnanandsaha/9Lfqj3nn/15/

What is wrong with my code?

**Comment by PlippiePlop** [comment]
Why do you need fieldset. change it to a div like the other group rows.

**Comment by patrickhlauke** [comment]
> Why do you need fieldset.

because it's the structurally correct element to use when you also want to provide an overarching `<legend>`. so yes, @krishnanandsaha's markup is correct, and it's likely a shortcoming of the BS CSS

**Comment by PlippiePlop** [comment]
Problem with this element, also <button> and <fieldset> is it has bug in flexbox on all mayor browers.

**Comment by mdo** [comment]
[This is flexbug 9](https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers)—some elements cannot be flex containers. The only solution is to put another element directly within the `<fieldset>` it appears. Closing as a can't fix.
