### ISSUE TITLE
v4: dropdown menu text with .navbar-inverse.bg-inverse

### ISSUE THREAD

**Issue by hypeJunction** [twbs/bootstrap#22259]
I have a dropdown down menu in an inversed navbar and the text of the dropdown menu comes up white/transparent.

```.navbar-inverse .navbar-nav .nav-link``` this should probably be less greedy.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbinc.om) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by hypeJunction** [comment]
http://codepen.io/hypeJunction/pen/KWBwdg

**Comment by oktalk** [comment]
You've improperly formatted your dropdown. In your example you need to remove the class '.nav-link' and replace it with the class `.dropdown-item`.

These questions are better suited for Stackoverflow.

**Comment by hypeJunction** [comment]
I abandoned the project. Too much time investment to rewrite an entire interface. Thanks for getting back to me though
