### ISSUE TITLE
Where can I see browser support of bootstrap ?

### ISSUE THREAD

**Issue by Chuyue0** [twbs/bootstrap#22258]
Where can I see browser support of bootstrap ?

**Comment by kanecko** [comment]
https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/

**Comment by Johann-S** [comment]
More precisely @kanecko : https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#supported-browsers

But thank you for your answer 👍

**Comment by bkdotcom** [comment]
It would be greatly helpful if the documentation could be a bit more specific.

> Bootstrap supports the latest, stable releases of all major browsers and platforms

as of when?

When a new version comes out, does official support of the older version end?

Does Bootstrap officially support Firefox v51? (current version is 52)
etc

Specifically, I'm needing to know if Bootstrap 4 supports Safari 9. (I'm assuming no)
The documentation support grid says Safari on iOS is supported, but omits any version information.

**Comment by Chuyue0** [comment]
Thank you for your answers!  I'll take a detailed look at the browser support. @kanecko @Johann-S @bkdotcom
