### ISSUE TITLE
v3-feature: Extend the responsive utilities visible-<size>- to include table-cell display

### ISSUE THREAD

**Issue by carlos-mora** [twbs/bootstrap#22250]
A visible-*-table-cell class is required in when table-cell is the display value. As an example,
this class is useful to hide input addons on small devices, where the span is shown as display:table-cell:
```
css:
@media (min-width: 1200px) {
  .visible-lg-table-cell {
      display: table-cell !important;
  }
}
@media (max-width: 1199px) {
  .visible-lg-table-cell {
      display: none !important;
  }
}

html:
<div class="col-sm-2">
      <div class="input-group date" data-provide="datepicker" data-date-language="es">
              <span class="input-group-addon visible-lg-table-cell"><i class="fa fa-calendar"></i></span>
              <input class="form-control" name="dob" type="text">
      </div>
</div>
```

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
