### ISSUE TITLE
input-group on grid breaks on Chrome

### ISSUE THREAD

**Issue by gtnasser** [twbs/bootstrap#22269]
Using .form-group and .input-group input gives me weird behavior only in Chrome, IE and Edge looks fine.

It's a bootstrap bug or chrome bug? Or I'm making any mistake?

You can check it on https://jsfiddle.net/gtnasser/szd376py/5/

I'm using 56.0.2924.87 on a 64bit Win10 OS.

![untitled](https://cloud.githubusercontent.com/assets/13912188/24324653/2e04c45a-1169-11e7-8354-211e285fe089.png)

**Comment by satyajit11** [comment]
@gtnasser which chrome version u r using its working for me

**Comment by mdo** [comment]
_CSS included in the example is for v3._

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
