### ISSUE TITLE
Row inside navbar

### ISSUE THREAD

**Issue by AlexTeixeira** [twbs/bootstrap#22262]
Hello,

When I try to put a div with class row inside a navbar, the row do not take the full width.
But if I remove the div with the row, the col works correclty

**Code sample :** 

```
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="row">
            <div class="col-2">
                <h1>Col1</h1>
            </div>
            <div class="col-8 text-center">
                <h1>Col2</h1>
            </div>
            <div class="col-2 text-right">
                <h6>Col3</h6>
            </div>
        </div>
    </div>
</nav>
```

[Codeply link](http://www.codeply.com/go/5O2YXQoLCN)

**EDIT :** 

It do not work if the nav is toggleable

**Comment by mdo** [comment]
Navbar containers are `flex`, so any immediate children element of that becomes a flex child. Flex items behave differently than standard components. Unfortunately, the navbar markup is a bit limited in how flexible it is given the component's complexities, so when you deviate from the default markup, you'll run into stuff like this.

**Comment by AlexTeixeira** [comment]
Hello, 

After investigating, I found  the solution deleting `navbar-toggleable-md`.
For mobile approach I can't toggle the navbar, so I will adapt design.

Thanks for the explanation.

**Comment by jeremylynch** [comment]
@mdo is there any workaround for this? Thanks

**Comment by TheRedstoneTaco** [comment]
@jeremylynch IT WORKED THANKS SO MUCH JESUS IS LORD

**Comment by shomonrobie** [comment]
flex-grow: 1 to the .row element - did the trick! Thanks!
