### ISSUE TITLE
Implement bodyElement in Tooltips and Popover

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#22261]
Tether added ``bodyElement`` option in **1.4.0** (see https://github.com/HubSpot/tether/pull/204) and it would be better to use ``bodyElement`` instead of trying to do the same thing with ``container`` option 
in Tooltip (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L284-L288) which doesn't work because Tether previous version only add element to the ``<body>``

It would be usefull for #22249

**Comment by melbee** [comment]
.

**Comment by guv3n** [comment]
I guess this is related to the problem I'm facing right now : I can't make a popover to be appended to a specific DOM element. It's always added to the body.

When I comment the Tether code (and only that part of the code) in the Tooltip.prototype.show function, the tooltip is obviously not well positioned but is appended to the DOM element I ask.

Any idea for a workaround ? ;)

**Comment by Johann-S** [comment]
Closed and fixed by #22444
