### ISSUE TITLE
Collapsing Submenus

### ISSUE THREAD

**Issue by Moon-ika** [twbs/bootstrap#22278]
Hello,
I've migrated to Bootstrap 4 Alpha 6 release and code below is not working anymore:

http://www.codeply.com/go/qxIBsp83TN

Item 1 and Item 3 have submenus and should collapse when the other is active.
Any idea? Thanks for help

**Comment by Johann-S** [comment]
Hi @Moon-ika,

I tried what you said but when I opened Item 1 and after I open Item 3, Item 1 collapse. So everything is ok for me.

Maybe I misunderstood something ?

**Comment by jipexu** [comment]
Yo
but it's write with classes who are not in BS4 now .. for example
`        <div class="col-md-3 col-xs-1 p-l-0 p-r-0 collapse in" id="sidebar">`
col-xs-1, in, p-r ...  are no more available in BS4  ...

**Comment by iatek** [comment]
@Moon-ika - there have been many changes from alpha 2 to alpha 6. You need to update the code accordingly: http://www.codeply.com/go/8ESO56VMns

**Comment by Moon-ika** [comment]
@iatek thanks for posting the code on codeply. The menus are not toggling tho - when I open menu Item1 and then switch to menu Item3, the menu Item1 doesn't collapse.

**Comment by iatek** [comment]
Because the accordion behavior now depends on `.card` instead of `.panel`: http://www.codeply.com/go/8ESO56VMns

**Comment by FBlade** [comment]
Works fine for me in http://www.codeply.com/go/qxIBsp83TN or http://www.codeply.com/go/8ESO56VMns.

**Comment by mdo** [comment]
Closing per comments about updating to later release.
