### ISSUE TITLE
v4: AMD support missing

### ISSUE THREAD

**Issue by rposener** [twbs/bootstrap#22277]
Tether and jquery support AMD loading.  Can this please be added to the v4 release.  I looked and there were quite a few others looking for the same, and as v4 is nearing beta, can't we get this?

**Comment by mdo** [comment]
If memory serves, and I don't fully understand the UMD/AMD stuff, but I think we stripped it all out in https://github.com/twbs/bootstrap/pull/20072 in favor of ES6.
