### ISSUE TITLE
v4: Buttons gives no feedback when clicked.

### ISSUE THREAD

**Issue by yedderson** [twbs/bootstrap#22281]
From the examples on Bootstrap 4 page https://v4-alpha.getbootstrap.com/components/buttons/#examples there seems to be a couple of issues :

- The cursor is not changing to a finger when hovering the buttons

 - Clicking the buttons gives no feedback. (they only change to active state)

Tried with Firefox 42 and Chromium 56 on Ubuntu 16.04.

**Comment by mdo** [comment]
> The cursor is not changing to a finger when hovering the buttons

This was removed to respect the spec, but the feedback has been rather mixed. I'm still debating if we'll restore it though. macOS for example does no cursor change for buttons. You'll want to search for the relevant issues and PRs where we discussed this change.

> Clicking the buttons gives no feedback. (they only change to active state)

The active state is the feedback you're looking for. Additional styles are available when customizing Bootstrap.
