### ISSUE TITLE
Select value not v-centered when in input-group

### ISSUE THREAD

**Issue by Mioleris** [twbs/bootstrap#22283]
Select value is not vertically centered when using ```<select>``` inside ```.input-group```

Only in safari
V4-Alpha6
https://jsfiddle.net/0zdm5p4u/

**Comment by oktalk** [comment]
The Bootstrap input group is only for inputs. Are you proposing a new feature to be extended to `select` tags? 

From the docs:
> Easily extend form controls by adding text, buttons, or button groups on either side of textual <input>s.

**Comment by oktalk** [comment]
I forgot to mention: if you want to just vertically center the text of a `select` tag in an input-group you could add the class `.custom-select`, and it will look better.

Example:
https://jsfiddle.net/0zdm5p4u/1/

**Comment by Mioleris** [comment]
I thought that is normal to have ```<select>``` in ```.input-group```
I think it could be a new feature :)
And yes I also found ```.custom-select``` class. Thank you. Issue should be closed or proposed as new feature.

**Comment by mdo** [comment]
Closing per comments.
