### ISSUE TITLE
Navs JavaScript example doesn't need role tabpanel

### ISSUE THREAD

**Issue by thbt** [twbs/bootstrap#22284]
The [JavaScript behavior example of navs](https://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior), the example container has the attribute `role="tabpanel"`. It doesn't make sense to put this role on the whole container since it is already on the `tab-pane` elements.

**Comment by Johann-S** [comment]
As it said here : https://www.w3.org/TR/wai-aria/roles#tablist

> tablist elements are typically placed near, usually preceding, a series of tabpanel elements.

Maybe I'm wrong but it seems correct to me.

/CC @patrickhlauke

**Comment by pkozlowski-opensource** [comment]
@Johann-S the key of the quote you are linking would be:

> usually **preceding**, a series of tabpanel elements

In the linked example there is a `tabpanel` role _above_ tablist (incorrect, IMO) and then `tabpanel` role on individual panels (this one is right, IMO).

**Comment by patrickhlauke** [comment]
@thbt / @pkozlowski-opensource are right. this seems to be an oversight/misunderstanding carried over from v3 docs.

(note there are more fundamental problems with tabs in BS, but this is a first quick fix of a blatant error in docs/markup)
