### ISSUE TITLE
Split variables.scss up?

### ISSUE THREAD

**Issue by enkafan** [twbs/bootstrap#22293]
I think this somewhat was discussed in #21409 and #21603. Kind of a chicken and egg situation right now with `custom.scss`. If I want to override a property it needs to come first, but if I want to use a standard variable then `custom.scss` then obviously you can't use it in that situation. Common scenarios that get tricky are something like if I wanted to change the following settings

``` scss
$font-family-base: $font-family-serif;
$headings-font-family: $font-family-sans-serif;
$brand-primary: $green;
$navbar-padding-y: ($spacer * .75);
$navbar-border-radius: $border-radius-lg;
$kbd-bg: $gray-lightest;
```

The "fix" for me in these scenarios is to also "override" the variables I'm using with the default value at the top of my script. Granted in the example above I'd probably be using a custom green and font anyways, but the fact that the order has been flipped a couple of times due to confusion shows that people are going to be trying to do things like above. 

I think a good solution, albeit something that has the potential to break a few people, would be to split the values with absolute values into their own file like `_base-variables.scss` and leaving the rest as `_variables.scss`. Then `bootstrap.scss` would become

```
// Core variables and mixins
 @import "base-variables";
 @import "mixins";
 @import "custom";
 @import "variables";
```

example of how this would be split would be the colors.

`_base-variables.scss`

``` scss
// Start with assigning color names to specific hex values.
$white:  #fff !default;
$black:  #000 !default;
$red:    #d9534f !default;
$orange: #f0ad4e !default;
$yellow: #ffd500 !default;
$green:  #5cb85c !default;
$blue:   #0275d8 !default;
$teal:   #5bc0de !default;
$pink:   #ff5b77 !default;
$purple: #613d7c !default;

// Create grayscale
$gray-dark:                 #292b2c !default;
$gray:                      #464a4c !default;
$gray-light:                #636c72 !default;
$gray-lighter:              #eceeef !default;
$gray-lightest:             #f7f7f9 !default;
```

`_variables.scss`

``` scss
// Reassign color vars to semantic color scheme
$brand-primary:             $blue !default;
$brand-success:             $green !default;
$brand-info:                $teal !default;
$brand-warning:             $orange !default;
$brand-danger:              $red !default;
$brand-inverse:             $gray-dark !default;
```

With that in place my `_custom.scss` would be free to use the semantic colors that are defined when overriding the styles of the branding (or navbar, etc) and I'd still be free to change the colors themselves if I was so inclined.

**Comment by mdo** [comment]
No changes are coming to the variables file in v4—I've worked in situations where we split out the files and this adds a ton of overhead. I already loathe the mixins files :grin:. With `!default` variables, you can override any point in the Sass file, before or after. https://jsbin.com/xexedip/

**Comment by wolfhoundjesse** [comment]
@mdo Your jsbin works beautifully, but I can't put anything in any order to override color variables with node_sass. If I understand correctly, tossing a `$blue: green;` into _custom.scss should make all of my primaries green, since they are set to $brand-primary and $brand-primary is set to $blue. Is that right?

**Comment by emilyjbro** [comment]
I've run into this same issue @wolfhoundjesse - changing the color $blue in your example does not then change $brand-primary and anything else that is connected to that color. Is this a bug or something I'm missing?

**Comment by iamandrewluca** [comment]
@mdo Any chance this will be done in `v5` ?

> "With !default variables, you can override any point in the Sass file, before or after."

As I see the problem is that variables depdend on other variables in same file.  
In my opinion I think that spliting variables by domain will solve the problem.  

```sass
@import "base-functions";
@import "base-variables";       // hard coded variables
@import "variables";            // variables dependent of base-variables 
@import "base-mixins";          // dependent only on above imports

// ...
@import "grid-functions";       // dependent only on top 4 imports
@import "grid-variables";       // may depend on base-variables
@import "grid-mixins";          // dependent only on top 4 imports
@import "grid";                 // uses only 3 above

@import "buttons-functions";    // dependent only on top 4 imports
@import "buttons-variables";    // may depend on base-variables
@import "buttons-mixins";       // dependent only on top 4 imports
@import "buttons";              // uses only 3 above

// ...
```

Everything that someone depdens on, should be splited in another file.  
This way someone could easy extend bootstrap. And do imports in any desired order.  
And maybe grouping each module in his own folder with mixins, functions, variables,  
And depdendent only on parent folder mixins, functions, variables.
