### ISSUE TITLE
Error on modal close

### ISSUE THREAD

**Issue by claudioalmeiida** [twbs/bootstrap#22295]
I have a bug here since alpha 6, and until the last "Grunt" I saw that it has not been solved yet, I looked at the issues but I did not find anyone talking about it. I made a video to prove it better.

When I open a modal and close it, normal, but when I open and move the mouse on an item that has tooltip, when I close it, it shows the error in the console.

https://youtu.be/YmmFNOEdMQE

**Comment by Johann-S** [comment]
Same as : https://github.com/twbs/bootstrap/issues/21607
