### ISSUE TITLE
modal background issue only in ios devices

### ISSUE THREAD

**Issue by Nuno1123** [twbs/bootstrap#22299]
I tried to find this issue already but didn't seem to find any, not sure if I'm doing anything wrong.

Desktop version of one of my modals (android devices display like this with different width obviously):

![screenshot from 2017-03-29 11-13-51](https://cloud.githubusercontent.com/assets/16775774/24450436/c613b0a6-1472-11e7-960d-7941bcbd4a24.png)
![screenshot from 2017-03-29 11-14-08](https://cloud.githubusercontent.com/assets/16775774/24450437/c6fc8f88-1472-11e7-9074-50499c69b5dd.png)

IOS version of one of my modals:

![17671003_1420092781346387_1664912782_n](https://cloud.githubusercontent.com/assets/16775774/24450518/1b6618c8-1473-11e7-854f-609955ea1f6d.jpg)
![17670954_1420092758013056_1739959193_n](https://cloud.githubusercontent.com/assets/16775774/24450522/1ec36912-1473-11e7-9877-73b9752083c4.jpg)
![17619073_1420092741346391_245324117_n](https://cloud.githubusercontent.com/assets/16775774/24450523/1fc838ce-1473-11e7-8a4a-1336ed9927d1.jpg)

The background becomes black for no reason (I can think of) if the modal height is bigger than device's. It displays the viewable part correctly when you open it, but the modal part that is not viewable on open, once you scroll down, background is black. Text is there, though.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Closing due to no follow-up with a demo of a reduced test case.
