### ISSUE TITLE
v4: Carousel animation bouncing on Microsoft Edge

### ISSUE THREAD

**Issue by marcelo2605** [twbs/bootstrap#22291]
I'm having this issue with Bootstrap carousel on Microsoft Edge:

![ice_video_20170328-091959](https://cloud.githubusercontent.com/assets/2372927/24406708/2e9d6222-139f-11e7-8e3f-b982635c9070.gif)

This gif is from official documentation page.

OS: Windows 10
Browser: Microsoft Edge 38.14393.0.0

**Comment by Johann-S** [comment]
Same as : #21751

**Comment by mdo** [comment]
Also a dupe of #21685.
