### ISSUE TITLE
collapse.js does not work anymore

### ISSUE THREAD

**Issue by git-marijus** [twbs/bootstrap#22296]
Since commit 24924c23b24c1b196c42166ebe9a17d31f0ee720 `<a data-toggle="collapse" href="#collapseExample">Some text</a>` reloads the page. `event.preventDefault()` is not being called anymore.

**Comment by mdo** [comment]
Do you have a demo that reproduces this?

/cc @Johann-S

**Comment by Johann-S** [comment]
Yes that's true I'll fix that now thank you @git-marijus 

My bad sorry 😢

**Comment by git-marijus** [comment]
The code below works well in alpha6 and does not work in current git.
The logic in https://github.com/twbs/bootstrap/commit/24924c23b24c1b196c42166ebe9a17d31f0ee720#diff-6ef28a975ef633bb3b3318b9917df9e5R366 is obviously wrong. It only calls `event.preventDefault()` on inputs and textareas instead of the other way around.
```
<a data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Link with href
</a>
<div class="collapse" id="collapseExample">
  <div class="card card-block">
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
  </div>
</div>
```

**Comment by Johann-S** [comment]
That's true, that's what happened when you are in a hurry

**Comment by git-marijus** [comment]
No big deal ;)

**Comment by vanduynslagerp** [comment]
As the `if` logic was wrong, shouldn't the unit have failed ?
