### ISSUE TITLE
Inconsistency Between Tooltip's Margins

### ISSUE THREAD

**Issue by IdanCo** [twbs/bootstrap#22300]
Following issue #21146 and PR #22276, tooltips still exhibit inconsistencies with the margins.

The issue manifests itself in two ways:

1. Initial state lacks margins:
![tooltips-margin](https://cloud.githubusercontent.com/assets/10364499/24447346/4b21aedc-1479-11e7-9b13-1a4cc2586658.png)

2. When the browser re-renders the tooltips, the margins changes. open [this bin](http://jsbin.com/gopevakala/edit?html,output) and try scrolling down and then back up. notice how the margins of the **top** and **bottom** tooltips changes.

**Comment by Johann-S** [comment]
Confirmed for me.

If you want to work on this issue @IdanCo do not hesitate 👍

**Comment by mdo** [comment]
No longer an issue in v4-dev.
