### ISSUE TITLE
Question about margins in Bootstrap 4

### ISSUE THREAD

**Issue by nikolas** [twbs/bootstrap#22304]
The following is from the bootstrap 4 docs here: https://v4-alpha.getbootstrap.com/content/reboot/

> Avoid margin-top. Vertical margins can collapse, yielding unexpected results. More importantly though, a single direction of margin is a simpler mental model.

The second sentence here isn't clear to me. Wouldn't defining a `margin-top` be a margin in a single direction? (up?)

**Comment by mdo** [comment]
The idea is we try to only apply bottom margin, no top margin, and we try to do so uniformly. All it means is that doing one direction, top or bottom, is easier.
