### ISSUE TITLE
Modal window doesn't close when tooltip used inside it. (Bootstrap 4 - alfa 6)

### ISSUE THREAD

**Issue by dmitry-git** [twbs/bootstrap#22314]
Testing on Chrome (v56.0) and Firefox (v52.0).

Example in bootstrap docs:
https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers

Actions:
1. Open link
2. Click "Launch demo modal" button
3. Hover mouse on link to open tooltip (inside modal window)
4. Click close button in modal window. Window does not close and in console we see error: 
"Error: Tooltip is transitioning"

**Comment by Johann-S** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/21743
