### ISSUE TITLE
typography   description-list-alignment

### ISSUE THREAD

**Issue by sh977218** [twbs/bootstrap#22319]
When using the example from here:
https://v4-alpha.getbootstrap.com/content/typography/#description-list-alignment
the code shows from there is:

```html
<dl class="row">
     <dt class="col-sm-3">Description lists</dt>
     <dd class="col-sm-9">A description list is perfect for defining terms.</dd>
     <dt class="col-sm-3">Euismod</dt>
     <dd class="col-sm-9">Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.
    </dd>
    <dd class="col-sm-9 offset-sm-3">Donec id elit non mi porta gravida at eget metus.</dd>
```

If the value of dd is empty, the alignment will be off.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by sh977218** [comment]
This is no longer bug since I couldn't reproduce. It might be the style.css I wrote overwriting the default style.
