### ISSUE TITLE
move .dropdown-toggle (caret) to mixin

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#22318]
Currently .dropdown-toggle is hard to customize.
If it will be mixin then people can override this mixin and create own caret (.dropdown-toggle::after) (for example using font-awesome).

This is only my idea to improve bootstrap :)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by wojtask9** [comment]
Maybe I wasn't clear. 
This isn't a issue, problem or bug with bootstrap. It's just about moving dropdown-toggler::after to mixin.

My thinking:

move 
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_dropdown.scss#L9
and
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_dropdown.scss#L24

to some mixins

@mixin dropdown-caret() {
  &::after {
    display: inline-block;
    width: 0;
    height: 0;
    margin-left: $caret-width;
    vertical-align: middle;
    content: "";
    border-top: $caret-width solid;
    border-right: $caret-width solid transparent;
    border-left: $caret-width solid transparent;
  }
}

@mixin dropup-caret() {
  &::after {
    border-top: 0;
    border-bottom: $caret-width solid;
  }
}

and then replace referenced lines with

.dropdown-toggle {
  // Generate the caret automatically
  @include dropdown-caret();
}

and 

.dropup {
  .dropdown-toggle {
    @include dropup-caret()
  }
}

Then in my project I'm able to override mixin (create another one and include after bootstrap mixin) and generate my custom style for dropdown-toggler caret (for example using font-awesome glyph instead of current bootstrap based on border triangle)

**Comment by mdo** [comment]
I'll pass on this one for now—not an immediate gain for the project itself and I'm unsure just how much this would change customization of the class.
