### ISSUE TITLE
Button do not have cursor:pointer ? Why?

### ISSUE THREAD

**Issue by sahilweb6** [twbs/bootstrap#22313]
I am making an app and after checking the buttons I saw there is no cusror:pointer on the buttons . Why have you removed or you forget to add this? Is there any specific reason for this? Because if there will be no cursor the user will be confused about its functions. 

Note : **I can add custom css but I want to know the reason**

**Comment by patrickhlauke** [comment]
the decision was made mainly in light of this https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b
