### ISSUE TITLE
Typo in samplecode in https://v4-alpha.getbootstrap.com/components/modal/#live-demo

### ISSUE THREAD

**Issue by Aweather** [twbs/bootstrap#22310]
https://v4-alpha.getbootstrap.com/components/modal/#live-demo

Copying and pasting the sample code does not work. The id of the modal is not set to the data-target id. 

Suggestion: replacing myModal with exampleModal will solve the issue.

**Comment by Johann-S** [comment]
Already fixed here : https://github.com/twbs/bootstrap/pull/21671
