### ISSUE TITLE
Tooltip on dropdown are still shown when dropdown is clicked

### ISSUE THREAD

**Issue by gsouf** [twbs/bootstrap#22312]
In the following fiddle I show an exemple of a dropdown with a tooltip on the title.

When the dropdown is clicked the tooltip is still visible and hides the top of the dropdown (admiting the tooltip is set to show on bottom). I had to manually hide the tooltip when the dropdown is clicked. See:

https://jsfiddle.net/3kxprueq/

I think it sould be natively managed by bootstrap.

**Comment by MattRoop** [comment]
Is it necessary that the anchor gets a title? W3 says that the title attribute is optional. Just to add, from my experience with digital accessibility, I can say that screen readers typically will read the value of the anchor text so that the user knows what they are clicking on. Just a thought. :)

**Comment by gsouf** [comment]
In my case tooltip is a must, because I use a menu with an icon only,
though the icon is meaningful enough, it's better for the user experience
to have the tooltip explaining more about the icon.

I didn't think about screen readers because in my case I'm not concerned by
them, but screen reader could have a sr-only alternative with the same
content as the title.

2017-03-31 15:06 GMT+02:00 Matt <notifications@github.com>:

**Comment by sofiakhatoon** [comment]
This seems to be an issue only when direction of tooltip is "bottom". But if you test it with "top" facing tooltip it is working correctly.

**Comment by gsouf** [comment]
Indeed, but try to use a dropup with a top tooltip now : https://jsfiddle.net/3kxprueq/3/

;)

**Comment by dominikfiala** [comment]
Not sure if its the problem but Tooltip stays displayed after you click the element (default option).

Try `trigger: 'hover'` option. It displays the Tooltip on hover only.

See https://jsfiddle.net/3kxprueq/4/

**Comment by mdo** [comment]
Given the age of this issue, and the specific situation (including where OP mentions designing around some common conventions of supporting screen readers), closing as a won't fix. The linked demo has a solution that can be executed should someone want to have a tooltip and dropdown on the same element.
