### ISSUE TITLE
Can't change the width of modal on bootstrap4 alpha6

### ISSUE THREAD

**Issue by dickcarlee** [twbs/bootstrap#22322]
`<div id="show" class="modal" >`
        `<div class="modal-dialog col-xl-12" style="width: 1000px">`
            `<div class="modal-content">`
               ` <div class="modal-header" style="padding: 2px">`
               ` </div>`
                `<div class="modal-body" style="padding: 1px">`
         `       </div>`
               ` <div class="modal-footer" style="padding: 2px">`
                    `<a class="btn col-xl-12" data-dismiss="modal" >close</a>`
               ` </div>`
            `</div>`
      `  </div>`
    `</div>`
To change the width of modal, this code works on bootstrap3, but on bootstrap4 the modal dialog size can't be change in any way, I've tried `modal-lg` , `width=99%`; 
it is a bug or need to do something new in bs4?

**Comment by mdo** [comment]
Change `max-width` on `.modal-dialog` as we do for the modal size variants.

**Comment by dickcarlee** [comment]
I've tried `<div class="modal-dialog" style="width: 2000px">`, but the width still haven't been changed.
