### ISSUE TITLE
btn-group using <a> tag as btn fail to popover

### ISSUE THREAD

**Issue by maxime4000** [twbs/bootstrap#22325]
# Info
- Operating system : Windows 7
- Browser and version (Chrome 56.0.2924.87, IE 11)
- Bootstrap Version 3.3.7 and 3.0.2 (on JSFiddle)

# Bug 
Popover can't be attach to a tag a with bootstrap btn without having display problem.
[Page example](https://jsfiddle.net/9qforbbp/1/)

**Comment by oktalk** [comment]
I'd refer you to this issue as this is a possible dup:
https://github.com/twbs/bootstrap/issues/5865

The docs talk about using popovers on button groups here:
https://getbootstrap.com/javascript/#popovers

**Comment by maxime4000** [comment]
It's maybe almost the same, but I don't thinks it's duplicate from the one you refer me because I don't use the button tag due to some limitation and because my display wasn't working right with button. 

That been said, in my work, I was using this before switching to "a" tag 
```
<div class="btn-group btn-group-justified">
  <div class="btn-group">
    <button type="button" class="btn btn-xs   Popover_Class   ">
    ...
    </button>
  </div>
  <div class="btn-group">...</div>
  ...
</div>
```

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
