### ISSUE TITLE
Navbar in-line bug?

### ISSUE THREAD

**Issue by bennierex** [twbs/bootstrap#22329]
I'm having issues with the navbar component (BS v4.0.0-alpha.6). If I follow the documentation, the navbar items are not displayed in-line: [jsbin](http://jsbin.com/denububero/2/edit?html,output)

I was able to reproduce this on Safari 10.0.3 and Chrome 57.0.2987.98 (on macOS 10.12.3).

Is this an error in the docs or bug in the css?

Edit:
Appearantly, if I put a div (without any classes) around the navbar contents, it displays the items inline.

```
<nav class="navbar fixed-top navbar-light bg-faded">
    <div class="">
      <a class="navbar-brand" href="#">Brand</a>
      <span class="navbar-text">inline text attempt</span>
      <span class="navbar-text">another</span>
    </div>
  </nav>
```

Edit2:
Although that doesn't fix ul's and inline forms

**Comment by mdo** [comment]
Navbar markup requires the use of the collapse to function and display properly. Adjust your markup accordingly and it'll be fixed. Also note that `v4-dev` has some further navbar improvements.
