### ISSUE TITLE
Different behavior of flexbox with (overflow-y) scroll on Safari, Firefox and Edge VS Chrome

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#22339]
In this page on plunker (https://plnkr.co/edit/gMbgxvUqHNDsQVe4P7ny?p=preview) there is a weird problem.

On Chrome on Windows and Android (Canary also) everything works good. I can scroll the two areas (on the left and on the right) and the top and bottom div of the page are on the top and on the bottom of my device screen. I see them anytime (see the picture below).

[![Example of scroll on Chrome on Windows, Good][1]][1]

On iPad or iPhone, iOS, with Safari or Chrome, this is not what I get. And also on Firefox 47.0.1 on Windows.

The page is long and there is just one scroll on the right, like if there is no flexbox on the page, this code is just ignored:

    .bigone {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }
    
    .main {
        flex: 1 1 0;
        display: flex;
    }
    .container-fluid {
      display: flex;
    }
    .col-6 {
      overflow-y: auto;
    }

**Quirk example:**

[![Firefox 47.0.1 on Windows][2]][2]

You can see on the iPad or iPhone just by a click on this button:

[![Click for plunker fullscreen][3]][3]

**Why this behaviour?**
Safari and Firefox bug or Chrome's one?
Why on Chrome everything good on Windows and Android?
And if in the new Safari in the future this will work good, how to do with the older devices with older iOS and firefox?

I will appreciate any answer. Thanks.

  [1]: https://i.stack.imgur.com/Jrb5O.png
  [2]: https://i.stack.imgur.com/7Gd51.png
  [3]: https://i.stack.imgur.com/VSxcw.png

**Comment by dholbert** [comment]
I don't know precisely why yet, but the discrepancy goes away if you:
 (1) add `min-height:0` to the `.main` element
 (2) reset `flex-wrap` to its initial value (`nowrap`) on the `.row` element.

Demo with those changes: https://plnkr.co/edit/ANrNNl4yFvcg2NEe8PQF?p=preview

**Comment by johnunclesam** [comment]
It works, but just in Firefox on Windows, not in Safari on iOS.

**Comment by johnunclesam** [comment]
Can I ask you if the problem is of Chrome or of Safari? I mean, is Chrome following the specifications and other browsers not? Is this true? We have to use workaround for scroll div with flexbox in Bootstrap 4 in Safari? It's possible?

**Comment by dholbert** [comment]
Sorry, I don't know enough about the internals of Chrome & Safari to know which one is wrong on my amended plnkr. My guess would be that Safari's wrong, though, because latest Chrome/Firefox/Edge all agree.

**Comment by johnunclesam** [comment]
Yeah, and this is a big problem. Because every browser on iOS is Safari engined!

**Comment by mdo** [comment]
I don't believe this isn't a Bootstrap bug, but rather a problem with flexbox and custom CSS. Reduce your code down if you can determine it to be a bug on our end, otherwise it looks like you'll need some additional CSS to clean this up.

**Comment by johnunclesam** [comment]
What I can reduce? People better than me here and on stackoverflow doesn't know what to reduce in jsfiddles.

**Comment by nicolasxu-bg** [comment]
`min-height:0` fixed my issue!
