### ISSUE TITLE
v4 - bg-inverse doesn't change borders on form elements

### ISSUE THREAD

**Issue by brunolm** [twbs/bootstrap#22331]
`bg-inverse` doesn't change form element borders, this makes `input-group-addon` look weird. I think one of the other should be changed.

Reduced test case: https://jsfiddle.net/e3yvym9r/1/

Windows 10 Pro
Chrome 57.0.2987.133 (Official Build) (64-bit)

**Comment by mdo** [comment]
Background utilities are for `background` alone; we won't be adding anything to modify `border` or any other property.
