### ISSUE TITLE
Modal dialog sticks, getting "Error: Modal is transitioning" in console. Most likely problem with the "fade" class.

### ISSUE THREAD

**Issue by mopsyd** [twbs/bootstrap#22334]
This error happens after the modal opens and closes about two or three times. I have a form wizard I have put together, which fires an ajax event when each form section completes, then opens a modal dialog with the results. Seems to happen primarily often when using the previous button to go back to a form section that has already been completed. Navigating to the next form section does not seem to cause the issue.

No other bootstrap components are used inside the modal presently.

*Note: Removing the "fade" class from the modal in the template prevents the issue. I suspect the way that class is handled is the root of the problem.*

This is the function I am using for modal control:

```
FormController.prototype.modal = function (status, title, content) {
        jQuery('#modal-dialogue').removeClass('success').removeClass('error').removeClass('warning').removeClass('info').removeClass('primary').removeClass('default').addClass(status);
        jQuery('#modal-dialogue h4.modal-title').html(title);
        jQuery('#modal-dialogue div.modal-body').html(content);
        jQuery('#modal-dialogue').modal();
    };
```
Markup for the modal element on the page is:

```
<div class="modal show success" style="display: block;" id="modal-dialogue" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
```

Modal content population is a normal h4 element in the title, and a ul list of associated data in the body. li elements in the body only have font awesome icons and a standard p tag populated with static text, with no event bindings. All content is received from the ajax call from the server and compiled fully before the modal is opened, so there isn't really any chance that this is due to a hanging ajax call, or the modal would never be called at all.

**Comment by mopsyd** [comment]
I saw some similar bug reported here:
https://github.com/twbs/bootstrap/issues/21607

That one was thought to originate due to a conflict with tooltips. This example is having the same issue without any other components being used.

**Comment by mopsyd** [comment]
Can also confirm that in all test cases, modal has been completely closed from any prior usage before the error occurs.

**Comment by Johann-S** [comment]
Close due to the merged of : https://github.com/twbs/bootstrap/pull/21743

**Comment by Jinet** [comment]
Worked with removing `fade` from parent div class. 
Final Modal code : 
```
<div class="modal loadingModal" id="applemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"  aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6">
                        <img src="ico/4.svg">
                    </div>
                </div>
              </div>
          </div>
    </div>
```


```
$.ajax({
        type: "GET",
        url: "/Timeline",
        data: {
            'dateTime': selected
        },
        async: true,
        beforeSend: function () {
              $('#applemodal').modal({
                  backdrop: 'static',
                  keyboard: false
              });
        },
        success: function(data) {
            $('#applemodal').modal('toggle');
       }
});
```
