### ISSUE TITLE
.card Conflict with wordpress

### ISSUE THREAD

**Issue by gregoryderner** [twbs/bootstrap#22346]
http://prntscr.com/es8plq

There is a conflict with WP v4.7.3 and BootStrap v4 in the .card class.

**Comment by unbolt** [comment]
It doesn't show up in the WordPress Generated Class list here: 

https://codex.wordpress.org/CSS

So is it from a theme? Plugin? Something else? Either way I don't think it's an issue that Bootstrap needs to solve.

**Comment by gregoryderner** [comment]
It's a plugin. It's in a clean wordpress in the admin area.

**Comment by mdo** [comment]
Closing as a won't fix.
