### ISSUE TITLE
Bootstrap v4.0.0-alpha.6: Navbar with more than one dropdown: unexpected behaviour

### ISSUE THREAD

**Issue by iamleighm** [twbs/bootstrap#22347]
When you add more than one dropdown menu to the navbar, and the navbar is in mobile view: if you Have a look here and take these steps: 
https://jsfiddle.net/leighm/ftg0fvz5/

1. Click on dropdown 1: should open as normal
2. Click on dropdown 2: it doesn't open, but dropdown 1 closes, so you have to click dropdown 2 a second time to open
3. Repeat steps for dropdown 3: the same should happen

Then reverses the steps:
1. With dropdown 3 open, click on dropdown 2: dropdown 2 opens and dropdown 3 closes. This would be the expected behaviour for me.

This is happening for me on Mac OS Sierra. Version 10.12.3 and it happens on Firefox (52.0.1) and Chrome (57.0.2987.133). It behaves normally on Safari.

**Comment by spllogics** [comment]
Running in to the same issue here as well.

**Comment by marcoarib** [comment]
Same issue here on Windows 10 (Firefox 53 and Chrome 57).

**Comment by xDestinatioNx** [comment]
@iamleighm I updated your fiddle and now it's working fine for me [https://jsfiddle.net/ftg0fvz5/3/](https://jsfiddle.net/ftg0fvz5/3/)

**Comment by iamleighm** [comment]
Thanks @xDestinatioNx Just looking at the code it appears that all you've done is removed the href. Is that correct? I think this should be explained in by Bootstrap in the documentation or more likely it should work with the href in the tag. I'd still consider this a bug?

**Comment by marcoarib** [comment]
I'm not sure, but the <a> element without the "href" attribute may cause problems with HTML validation and the tabbing order.

**Comment by marcoarib** [comment]
I'm not sure, but the element without the "href" attribute may cause problems with HTML validation and the tabbing order?

**Comment by mdo** [comment]
This works for me. https://codepen.io/emdeoh/pen/rGzYZv
