### ISSUE TITLE
Incorect checkbox position when using .form-check and grid

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#22348]
I'm generally new to Bootstrap and I'm testing Bootstrap 4. I see an issue in checkbox input positioning in forms with use of grid.

https://jsfiddle.net/wnov88px/2/

Current result:
1. Firefox the checkbox is right after the label
2. In Chrome it's at the end of the row.

Expected result:
I'd expect the checkbox to be aligned to the left of the text input, i.e. the label should take 33.33% of the row width.

ps. I used table element instead of div. When using div the checkbox drops below the label which might be another issue.

**Comment by alecpl** [comment]
Looks that `display:block` in `.form-check` overrides `display:flex` of `.row`.

**Comment by oktalk** [comment]
You shouldn't use tables for layout. Also, try to stick more closely to the [examples](https://v4-alpha.getbootstrap.com/components/forms/#using-the-grid).

You're correct in your assessment that `.form-check` overrides the flex display -- this is intended behavior. Your usage of the class, in your example, is incorrect.

**Comment by alecpl** [comment]
I'm migrating existing system to Bootstrap, so I prefer to not change the form generation code too much, to not break old themes for this system. Generally it looks good, only this one small issue.

I don't see in examples how to have a checkbox with label on the left, properly aligned, even with divs.

**Comment by mdo** [comment]
Don't use tables for this; the markup is a required part of the component.
