### ISSUE TITLE
Pushed and pulled columns are breaking out of the container when exceeding 12  grid-columns

### ISSUE THREAD

**Issue by bluesnotred** [twbs/bootstrap#22349]
**Tested on:**
Mac OS X using Safari 10.0.3 and Chrome  57.0.2987.133

**Description:**
Columns are breaking out of the container on pushing and pulling. This only happens when the total of grid-columns exceed 12. 

**JSbin example:**
http://jsbin.com/saxaran/1/edit?html,output

**Comment by oktalk** [comment]
I'm not sure the column amounts should exceed 12. Per the docs:
> Column classes indicate the number of columns you’d like to use out of the possible 12 per row. So, if you want three equal-width columns, you can use .col-sm-4.

Also, your example was lacking some styles, I've edited it a bit: 
http://jsbin.com/keneqor/edit?html,output

**Comment by bluesnotred** [comment]
@oktalk the docs say:

> **Column wrapping**
> If more than 12 columns are placed within a single row, each group of extra columns will, as one unit, wrap onto a new line

https://v4-alpha.getbootstrap.com/layout/grid/#column-wrapping

**Comment by iatek** [comment]
This is the same push/pull behavior as 3.x, and it doesn't matter if the columns exceed 12. I think this is the intended behavior.

**Comment by bluesnotred** [comment]
Maybe it's intended behaviour, but somehow it goes against the new-line wrapping when exceeding 12 columns,. For me it wasn't expected behaviour ;-)

@iatek Thank you for your example. I already tried to use flexbox ordering, but didn't know it was possible to use multiple flex-firsts. Great!

**Comment by mdo** [comment]
Yup, this is how these classes should behave—see https://github.com/twbs/bootstrap/issues/22349#issuecomment-291538117. Rows have `flex-wrap: wrap;` but if you're not pushing _and_ pulling together (or go too far), that screws up the rendering.
