### ISSUE TITLE
Font color utilities

### ISSUE THREAD

**Issue by NicoLB** [twbs/bootstrap#22350]
I find the way we name text-color variants inconsistent. On one hand we have `.text-muted` and on the other hand `.text-white` and `.text-gray-dark`. I think we can all agree the latter is bad practice.

I suggested we:
- rename `.text-white` to `.text-inverse`
- rename `.text-gray-dark` to `.text-default`
- introduce `.text-accent`

We'd end up with something like that:

**_variables.scss**
```
$text-muted:    $gray-light !default;
$text-accent:   $black !default;
$text-inverse:  $white !default;
```

**utilities/_text.scss**
```
@include text-emphasis-variant('.text-default', $body-color);
@include text-emphasis-variant('.text-muted', $text-muted);
@include text-emphasis-variant('.text-accent', $text-accent);
@include text-emphasis-variant('.text-inverse', $text-inverse);
```

**Comment by Borkason** [comment]
> On one hand we have .text-muted and on the other hand .text-white and .text-gray-dark. I think we can all agree the latter is bad practice.

Why?

From my point of view it makes sense to separate classes that describe a style belonging to the overall theme and classes are not linked to the theme.

> rename .text-white to .text-inverse

For example.

If the overall theme is dark, `.text-default` would be light `.text-inverse` would be dark. But `.text-white` would still be white and `.text-dark-gray` would be dark grey, regardless of the theme.

In that light `.-text-white` to `.text-inverse` would be contradicting.

**Comment by NicoLB** [comment]
Thanks for the feedback.
I should probably have started by saying I wasn't super happy with the naming I came up with either.

To provide a simple example, my default `$body-color` is set to `$gray-dark` instead of `$gray`. The utility `.text-dray-dark` is now useless to me unless I do something like `.text-gray-dark { color: $black; }` which doesn't make much sense.
It's bad practice because the name of class is linked to the name of the variable / color. That's why we have `.text-muted`, `.text-danger`, etc. and not `.text-gray-light`, `.text-red`, etc.

It's also inconsistent with the naming of other utilities:
```
.text-muted
.text-primary
.text-success
.text-info
.text-warning
.text-danger
.text-white
.text-gray-dark
```
Don't they feel out of place?

About your argument for theming, I see your point, very what you write is what you see. But let's say your site is white on black, then `.text-white` could become useless?

Note: I used `.text-inverse` because of the existent `.bg-inverse`.

**Comment by Superpencil** [comment]
`.text-white` has thrown me off especially since there is no `.text-black` and I'm dealing with a dark site.

Since there is `.text-muted`, I'd say whatever high-contrast option we have should adjust to white or black backgrounds and be called `.text-intense` (the opposite of muted according to a dictionary)

**Comment by wereveal** [comment]
I personally get frustrated with names that convey different/vague meanings to different people, especially when it comes to color. e.g., text-info doesn't really convey a color at all, just a purpose. It could be blue, green, or purple. Having to learn what color .text-info has seems wrong or it gets overridden by the person that wants .text-info to be something other than originally defined. 

Some may use .text-danger to get red text when the text (or context) itself has nothing to do with danger, they just wanted red text. On the other hand, with .text-white you expect the text to be white even if it is never used in someone's work. There are probably many classes defined by bootstrap that probably never see use where others find them indispensable. 

I always get a chuckle out of the whole btn btn-primary thing. I have a client whose primary buttons are always .btn-success and secondary buttons are .btn-info. To keep my client's lesser informed people from making mistakes in the cms, I had to create .btn-{color} classes so they knew which ones were which by color. After all, the only difference between btn-primary and btn-success is the color.

**Comment by mdo** [comment]
@wereveal Completely agree on the nomenclature. I think we'll move to colors only; the abstraction to _semantic_ names largely feels unnecessary and doesn't provide us with much. I _think_ I'd rather provide an array of colors that we can iterate over to generate our buttons, utilities, etc.

Lemme noodle on that.

**Comment by mdo** [comment]
For now though, the suggestion from the OP here isn't going to happen—closing out.

**Comment by Superpencil** [comment]
@mdo @wereveal switching to actual colors for the names will put me out of a job. Finally I can focus on my putting skill.

How about going with the full array here http://clrs.cc while you're at it? Since Bootstrap is the standard, have standard colors?
