### ISSUE TITLE
Update NuGet publish specs for version 4 with Tether dependency

### ISSUE THREAD

**Issue by peterblazejewicz** [twbs/bootstrap#22359]
As far as I understand with version 4.* the `Tether` is additional dependency for BS JavaScript plugins. 
It looks that NuGet publish specs should reflect this change:
https://github.com/twbs/bootstrap/blob/v4-dev/nuget/bootstrap.nuspec#L18-L20
https://github.com/twbs/bootstrap/blob/v4-dev/nuget/bootstrap.sass.nuspec#L18-L20

If that information about dependency is expected, I'd be glad to make a PR (we are using v.4 bits at work already).

Thanks!

**Comment by peterblazejewicz** [comment]
Little more info:

The Tether is available on nuget.org, but only in 1.1.1 version:
https://www.nuget.org/packages/HubSpot.Tether/
That is the version marked as the `latest` release on the Github:
https://github.com/HubSpot/tether/releases/latest
The current version - referenced in `package.json`, seems to be never submitted to nuget.org.

HotSpot/Tether#251

**Comment by mdo** [comment]
@Johann-S Do we need to update this given the move to Popper?

**Comment by Johann-S** [comment]
It seems Popper.js isn't in nuget.org
@FezVrasta any project to publish Popper.js in nuget ?

**Comment by FezVrasta** [comment]
I never used Nugget, may you open an issue on the popper repo?

**Comment by peterblazejewicz** [comment]
I think you folks from BS should do not be bothered with NuGet. As I understand the `popper.js` is both registered and updated both as Bower and NPM package (thx to @FezVrasta)
I personally avoid using NuGet for non C#/.NET deps and at my current company we are not using NuGet for this at all too. The folks using VS + .NET have a problematic or somehow convoluted ways of managing client side dependencies in my opinion (I'm using NPM for this).
Let me /cc to people from relevant tech stack for input
@mlorbetske @scottaddie

**Comment by mlorbetske** [comment]
cc @madskristensen

**Comment by scottaddie** [comment]
I agree 100% with what @peterblazejewicz stated above. As a .NET/Visual Studio developer, I use npm to acquire and install client-side libraries & frameworks. Bower is another, less popular, option.

The problem I've had with NuGet in the past is that these types of assets are dumped into **Content** and **Scripts** folders (when using the Web Application project type). I have no control over this, as the decision is left to the library author. In the new CPS project system, NuGet doesn't support delivery of content files at all. At the time of writing, NuGet redirects to Bower instead. Read the 1st paragraph of the following doc for Microsoft's position:

https://docs.microsoft.com/en-us/aspnet/core/client-side/bower

**Comment by mdo** [comment]
So Bower it is? We drop Nuget support?

**Comment by Johann-S** [comment]
Currently Bower recommend to use `npm` or `yarn` for package manager see : https://github.com/bower/bower/issues/2298 and `README.md` so IMO we shouldn't rely a lot on Bower. And @FezVrasta added Popper.js to NuGet

**Comment by FezVrasta** [comment]
Why not just npm?

**Comment by Johann-S** [comment]
I think it's just a question of being available in all package manager and we are (Bootstrap) available in NuGet since v4 Alpha2

**Comment by FezVrasta** [comment]
I get it, but if NuGet itself says that people should use Bower, and Bower says people should use npm...

**Comment by peterblazejewicz** [comment]
> but if NuGet itself says that people should use Bower, and Bower says people should use npm...

Let me put a little context why the NuGet is here and why there are all those tools mentioned. 
Couple years ago when Microsoft introduced new version of its flagship web framework: ASP.NET MVC 5, they literally **dropped** its own custom styles and markup in project templates shipped with Visual Studio IDE and instead introduced templates based on Bootstrap 3.
See here:
https://www.hanselman.com/blog/VisualStudio2013RCForWebDevelopersOneASPNETBrowserLinkAndOurDirection.aspx
> Notice that Bootstrap is the default template now. We'll have Bootstrap 3.0 for the final release.

With this move (in my opinion) Microsoft changed dev experience for developers. And for many years from that release, thousands of C#/.NET developers still use Bootstrap as default web framework whenever doing first steps with Visual Studio or just starting web development.
This was one of many similar steps taken by Microsoft (again, in my opinion) to improve overall developer experience with MS tooling (in short).
The main problem still not clearly solved in Visual Studio (as mentioned before) is how client dependencies should be managed. The NuGet package manager (and repository) was not created for client side code and web developers have their own beloved tools. The new Asp.Net Core 1.0 (new version of .Net web framework) and supporting tools tried to solve that problem with adding support for Bower or NPM package manager as 'first-time citizen'  within ASP .NET projects:
https://www.mikesdotnetting.com/article/283/asp-net-5-managing-client-side-dependencies-with-npm-bower-and-gulp
https://docs.microsoft.com/en-us/aspnet/core/client-side/bower

But this applies only to new version of framework and there are thousands of developers that are stick with older version of framework for now and many years ahead. So the community should somehow figure a friendly way to provide Bootstrap 4 to all developers that are using Microsoft tools. And yes, this could be all of those: NuGet (to help ASP.NET MVC5 folks), Bower or Yarn/NPM.

/CC @shanselman @danroth27
Can we somehow help BS folks with this?

**Comment by FezVrasta** [comment]
I forgot to update the status of this issue, eheh..

Popper.js is available on Nuget starting from version 1.9.9.

I created an utility ([`nuget-publish`](https://www.npmjs.com/package/nuget-publish)) to help to publish npm packges to NuGet. Maybe Bootstrap could benefit from it as well?

I think this issue can be closed now.

**Comment by supergibbs** [comment]
A little more context... It was decided a while back to continue supported NuGet because there was a demand. Probably will be dropped for v5.0.0 but plenty of developers still use the Visual Studio setup mentioned above. Since all the alpha's have been published to NuGet and are getting significant downloads, it shouldn't be dropped now. I am happy to keep it updated.

Should I add Popper as a dependency?

**Comment by peterblazejewicz** [comment]
@supergibbs Jesse,

> Should I add popper.js as a dependency?

Yes, the same reason you have mentioned: people are used to get NuGet package with all the deps. So I think there should be explicit dependency added here:
https://github.com/twbs/bootstrap/blob/v4-dev/nuget/bootstrap.nuspec#L19

Thanks for taking your time on this!

**Comment by supergibbs** [comment]
Yes, I created the PR already

**Comment by supergibbs** [comment]
This has been done, please close! (also NuGet has been updated)

**Comment by mdo** [comment]
Thanks @supergibbs!
