### ISSUE TITLE
.btn class in Navbar behaving differently for button- and a-element

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#22351]
`.btn` class in Navbar is behaving slightly different for `button`- and `a`-element. This happens only when there is another nav item on the left. If there is none, the buttons align perfectly. I have not tested other cases.

![button](https://cloud.githubusercontent.com/assets/2971735/24699416/30b7ed92-19f4-11e7-98cd-3ded387480b6.png)

```
<nav class="navbar navbar-toggleable sticky-top navbar-inverse" style="background-color: #00b1e6;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
            <!-- If you remove this nav item, size and alignment of both buttons match. -->
            <li class="nav-item ">
                <a class="nav-link" href="#">Nav-Item</a>
            </li>
          
            <li class="nav-item">
              <!-- use the margin to push the a-button to the button-button.
                   Makes it easier to compare sizes and alignment. -->
                <a class="btn btn-primary" href="#" style="margin-left:0px">a-element</a>
            </li>
          
        </ul>

        <form class="form-inline" action="#">
            <button class="btn btn-primary" type="submit">button-element</button>
        </form>
    </div>
</nav>
```

https://jsbin.com/zexutexiri/edit?html,output

Windows 10 Pro x64
Firefox 52.0.2

**Comment by peterblazejewicz** [comment]
The `.nav-link` could have  `line-height` set to:
```css
line-height: 1.25;
```
in order to better align text. Now it inherits global settings:
https://github.com/twbs/bootstrap/blob/ea6390d513039a18903901e5e6b4603166fc46db/scss/_reboot.scss#L53
https://github.com/twbs/bootstrap/blob/ea6390d513039a18903901e5e6b4603166fc46db/scss/_variables.scss#L257

**Comment by mdo** [comment]
Sounds like this is the font-family issue. Please check with the latest from `v4-dev` and retry.
