### ISSUE TITLE
bootstrap 4 -> fail load 74 .scss files !

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [twbs/bootstrap#22356]
hi.
i recently used bootstrap v4.
when i started `Hello, world!` project. browser(mozilla firefox) send many request and all failed!
i test this problem in [v4-alpha.getbootstrap.com](https://v4-alpha.getbootstrap.com/)

![image](https://cloud.githubusercontent.com/assets/6462878/24722566/6eeb263c-1a59-11e7-8ea0-2ba7bfb18a5a.png)

is this bug?

**Comment by mdo** [comment]
Doesn't look like a bug to me—looks like Firefox is showing you the source Sass files, likely via the Sass maps feature.
