### ISSUE TITLE
Modal "esc" key closes fullscreen browser

### ISSUE THREAD

**Issue by callumstrubi** [twbs/bootstrap#22362]
Pressing the "esc" key to close a modal will close the browser in macOS from fullscreen using the default browser action

Tested on:
macOS Sierra, Safari Version 10.1

Simple JSBin:
https://jsbin.com/buciferovu/edit?html,css,output

Proposed fix:
preventDefault(); added to modal close action when triggered from keypress

**Comment by patrickhlauke** [comment]
sounds fair enough to me. targetting this for v4, as v3 is only in maintenance mode

**Comment by bkdotcom** [comment]
Modal Feature Request:  Keyboard Arrow Key's changing modal button focus should be core functionality.    In addition, when a modal opens, it should  `.find("[autofocus]").focus()`

**Comment by patrickhlauke** [comment]
> Keyboard Arrow Key's changing modal button focus should be core functionality. 

modals are used for more than just OK/CANCEL type dialogs, so this would likely not work in our more generalised model, i think

**Comment by callumstrubi** [comment]
To specifically support @patrickhlauke here, we use the modal for our search implementation, any bootstrap focus intervention would kill that functionality.
A suggestion to get your focus to work though:
$("#modal").on('shown.bs.modal', function(){
      $(this).find('[autofocus]').focus();
});
This is how we focus on the search input when the search menu is initialised.
<img width="1440" alt="screen shot 2017-04-06 at 15 53 02" src="https://cloud.githubusercontent.com/assets/5045779/24760788/8e519096-1ae1-11e7-974e-e93700a9fd72.png">

**Comment by bkdotcom** [comment]
>any bootstrap focus intervention would kill that functionality.

sorry to derail...
how so?  If you don't want something autofocused don't add the autofocus attribute.  If you do want something autofocused, add the autofocus attribute.   Autofocus on an input element inside a modal currently doesn't have any effect (unless implementor is listening for on show/shown and setting the focus).  I don't see any potential breakage or undesired behavior.

**Comment by patrickhlauke** [comment]
i think @callumstrubi was referring to focus intervention in the context of the left/right cursor key to set focus to OK/CANCEL type buttons. agree with you that the autofocus thing is likely fine since it's up to the author to either add any autofocus attributes or not

**Comment by bkdotcom** [comment]
final comment regarding keyboard arrows and buttons:
perhaps enabled via a data-attr on the modal?
`<div class="modal" data-keyboard-btn="true"></div>`

**Comment by patrickhlauke** [comment]
@bkdotcom mind splitting out your additional requests into two new separate issues, so we can keep this on-topic regarding the "ESC" key handling?

**Comment by asztal** [comment]
FYI, there is also another (perhaps unintended, but beneficial) consequence of this - the ESC key also stops any ongoing network requests in some browers (Chrome). As a result, if closing the modal via the ESC key triggers a network request, that request would be cancelled in bootstrap 3 but succeed in bootstrap 4.
