### ISSUE TITLE
Bro add some features please 

### ISSUE THREAD

**Issue by HARoonMIND** [twbs/bootstrap#22361]
Before opening an issue:

- in masonry grid please add pagination ,
- add timeline 
- add slider for custom html 
- add horizontal view scroll  for section 
- sidebar navigation ui 
- Handy utilities z-index div which always top level 
- add div dim background image property 
- hover div text ,

**Comment by mdo** [comment]
Nah, bro. We'll do new features in v4 when I'm done breaking everything that's already there.

---

- Pagination on your masonry grid isn't up to us—use the pagination component and hook it up as you and your setup requires.
- What's a timeline?
- As in the range component? Maybe. We have an issue for that.
- Like `overflow-x: auto`?
- Also a PR for that somewhere I think.
- That's a new one, maybe!
- Eh, probably better served by an animation/transition lib, or your own styles.
- No idea what this would be honestly, but see previous bullet?
