### ISSUE TITLE
 badge in paragraph

### ISSUE THREAD

**Issue by nam-co** [twbs/bootstrap#22360]
Hi, I noticed that badge inside a `<p>` doesn't render well, when the you change the p font-size

Example:
p {
	font-size: 14px;
}

Thanks

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by nam-co** [comment]
Hi Johann, thanks, it's a mac, using safari and chrome (latest versions) and here is the sample: https://jsfiddle.net/maksuco/u4jdatj5/
thanks

**Comment by nam-co** [comment]
Johann I also notice it doesn't do the same with a <li>, but it doesn't align with theoretical center, but I guess this is normal, is there a way to fix it with an additional class?
https://jsfiddle.net/maksuco/u4jdatj5/3/
thanks

**Comment by oktalk** [comment]
@nam-co What do you mean by "... doesn't render well ..?"

Your issue, vague as it is, seems a bit too subjectively stated. The examples you've provided are correct implementations of the badge class.

**Comment by nam-co** [comment]
Hi @oktalk the vertical alignment is at the top of the text as you can see in the picture, shouldn't it be vertical align middle? so they look better.

![screen shot 2017-04-11 at 10 30 11 am](https://cloud.githubusercontent.com/assets/3951529/24917504/0d10149c-1ea3-11e7-994f-9d6da27d1d13.png)

**Comment by oktalk** [comment]
Thank you for the clarification. Does this look better?
https://jsfiddle.net/hs5jusLs/2/

I've added `vertical-align: text-bottom;` to the `.badge` class.

**Comment by nam-co** [comment]
It does, should it be included on the v4 code?
What do you think of the problem first posted in the issue

Thanks

**Comment by mdo** [comment]
Going to punt as a won't fix for now. Vertical alignment is slightly off between all browsers; basically impossible to solve for everyone.
