### ISSUE TITLE
Modal with Tooltips and popovers don't not close

### ISSUE THREAD

**Issue by raesromero** [twbs/bootstrap#22382]
If popover or tooltips button is clicked. the modal can't close.

<a href="https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers">Tooltips and popovers</a>

**Comment by pkozlowski-opensource** [comment]
Most probably duplicate of #22314, which should be fixed in the `v4-dev` branch but not released yet

**Comment by Johann-S** [comment]
Fixed by #21743
