### ISSUE TITLE
Documentation & Modal - not same ID in live demo

### ISSUE THREAD

**Issue by vertisan** [twbs/bootstrap#22381]
For Bootstrap 4 in documentation we have **[Live Demo](https://v4-alpha.getbootstrap.com/components/modal/#live-demo)** with different ID.
Button:
```
data-target="#exampleModal"
```
Modal box:
```
<div class="modal fade" id="myModal"  
```

This may be embarrassing for new users, so I'm asking for a correction :)

**Comment by patrickhlauke** [comment]
already fixed https://github.com/twbs/bootstrap/pull/21671
