### ISSUE TITLE
v4: .btn classes on an "a" tag looks differently than on "button" tag

### ISSUE THREAD

**Issue by igodorogea** [twbs/bootstrap#22384]
Anchor buttons(`a.btn`) differ from normal buttons(`button.btn`) because of font family.

E.g. the difference is easy to notice on large buttons(`.btn-lg`)
![buttons](https://cloud.githubusercontent.com/assets/4079076/24830957/9fb4e7b2-1c98-11e7-8533-9228deb383c1.jpg)

**Comment by mdo** [comment]
This was fixed awhile back in v4-dev branch.
