### ISSUE TITLE
list-inline & col-offset not working

### ISSUE THREAD

**Issue by geminiX** [twbs/bootstrap#22399]
I am a newbie to GitHub and programming in general, so I apologize for any errors in the following report. I am creating a page on CodePen and the list-inline and column offset classes are not working properly in v4.0.0 alpha 6, however if i switch to Bootstrap 3.3.7 it is working as expected. Links to Bootstrap CSS files I am using: 

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css

My CodePen project:
https://codepen.io/geminix/pen/PpMNzz

**Comment by mdo** [comment]
v4 has different HTML, CSS, and JS, so you might need to change a few things around. Take a look at the v4 docs at http://v4-alpha.getbootstrap.com. The grid classes have changed for offsets (now `.offset-*`), for example.
