### ISSUE TITLE
Space distributed uneven when using fraction of rem's

### ISSUE THREAD

**Issue by valorize** [twbs/bootstrap#22409]
When I use rem's instead of even pixels I run into the problem that a fraction of rem's might result in 1.75 pixels. When this 1.75 pixels are used as margin for multiple boxes next to each other one box might be separated by 3 px and one by 4 pixels. Is this problem already noted?

**Comment by valorize** [comment]
I added a mixin. Is this the way to go?

```
$font-size-base-pixel: 14px;

html {
	font-size: $font-size-base-pixel;
}

/// Remove the unit of a length
/// @param {Number} $number - Number to remove unit from
/// @return {Number} - Unitless number
/// @see https://css-tricks.com/snippets/sass/strip-unit-function/
@function strip-unit($number) {
	@if type-of($number) == 'number' and not unitless($number) {
		@return $number / ($number * 0 + 1);
	}

	@return $number;
}

@mixin rem-margin($tb, $lr) {
	margin: round($font-size-base-pixel * strip-unit($tb)) round($font-size-base-pixel * strip-unit($lr));
}

.mydivs {
	@include rem-margin(0, $card-spacer-x/4);
}
```

**Comment by mdo** [comment]
Not really a way around this when using relative units. Closing as a won't fix.

**Comment by valorize** [comment]
@mdo Don't you think it would be valuable to have a note on this issue and add an appropriate mixin for this issue?
