### ISSUE TITLE
Will badge-default be the final class name for V4?

### ISSUE THREAD

**Issue by pat270** [twbs/bootstrap#22404]
Just wanted to make sure that you guys will be sticking to `badge-default` for V4 before I commit to using that component. I don't think it quite fits the V4 naming pattern but doesn't matter to me either way. Thanks!

`btn-default` was renamed to `btn-secondary`
`navbar-default` was renamed to `navbar navbar-light bg-faded`
I also see a `card-outline-secondary`.

**Comment by mdo** [comment]
Nothing's locked in until our first beta. Hoping that's coming soon though—we're getting close.
