### ISSUE TITLE
Problem with Modal popup. Background slide left.

### ISSUE THREAD

**Issue by jackryu** [twbs/bootstrap#22408]
If My modal popup open my complete background slide left.

please help.

/*!
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under the MIT license
 */

![img](https://cloud.githubusercontent.com/assets/6933841/24917208/099e5894-1efa-11e7-9f0c-8c0c1f14de43.JPG)

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
