### ISSUE TITLE
Fire modal event after appending to the DOM but before the transition begins

### ISSUE THREAD

**Issue by ElMassimo** [twbs/bootstrap#22410]
Similar to #16124, but for modals.

Because `shown.bs.modal` is triggered after the transition ends, any transformation to the HTML in the modal happens after the modal has been displayed. This creates a jarring visual effect, if say, you want to add something like [selectize.js](http://selectize.github.io/selectize.js/) to a form in the modal.

Having an event that is triggered after the modal has been inserted in the DOM but before the transition begins would provide a hook that can be used to apply any transformation or event bindings, making it also useful for data binding or templating libraries as well.

Example implementation in [modal.js](https://github.com/twbs/bootstrap/blob/v3-dev/js/modal.js#L95-L97):
```js
       that.enforceFocus()
  
 +      that.$element.trigger($.Event('inserted.bs.modal', { relatedTarget: _relatedTarget }))
 +
        var e = $.Event('shown.bs.modal', { relatedTarget: _relatedTarget })
```

**Comment by Johann-S** [comment]
I think you can use `show.bs.modal` event which is trigger before `shown.bs.modal`

**Comment by ElMassimo** [comment]
`show.bs.modal` is fired before the modal is appended to the DOM, and there are several operations that can't be performed until that time.

**Comment by Johann-S** [comment]
In our examples modals are always in the DOM. We add `.show` to display modals that's all

**Comment by ElMassimo** [comment]
Have in mind that [that's not always the case](https://github.com/twbs/bootstrap/blob/v3-dev/js/modal.js#L79-L81).

Also, resizing, padding, and scrollbars are applied after `show` is fired, so if there's any calculation that needs to consider the modal's dimensions, it need to happen after the layout.

The point remains, having this event would be very useful in different circumstances.
