### ISSUE TITLE
鼠标经过dom 获取id 请求数据 通过popover显示出来 如果接口返回速度慢 会出现很多提示窗不消失 请问怎么解决

### ISSUE THREAD

**Issue by gitkingchen** [twbs/bootstrap#22417]
<div data-popover="toggle" data-id="1">title1</div>
    <div data-popover="toggle" data-id="2">title2</div>
    <div data-popover="toggle" data-id="3">title3</div>

    $('*[data-popover]').hover(function() {
            var e = $(this);
            $.ajax({
                url: url,
                type: 'get',
                dataType:'json',
                data: {
                    id: e.data('id')
                },
                beforeSend: function () {},
                success: function (json) {
                            e.attr('data-content',json.content).popover({
                                trigger:"hover",
                                animation:false
                            }).popover('show');
                }  
            });
        }
    },function(){
        var e = $(this);
        e.popover('hide');
    });

**Comment by patrickhlauke** [comment]
for how-to questions, please use StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
