### ISSUE TITLE
Scrollspy data-offset="" is not working

### ISSUE THREAD

**Issue by SamThilmany** [twbs/bootstrap#22411]
I'm using scrollspy for a sidebar navigation on a long post and as my top navigation is fixed, I need to set an offset to the anchors, so that the navigation acts like it should.

I tested it using `data-offset=""` on the `body` element, but unfortunately my input was ignored. The new menu item is highlighted at the default offset of 10...

Any ideas? Is it my fault or is this a known bug?

---

I also tested it on the v4 Documentation. On the given example I added `data-offset="50"` to the body and guess what, It didn't work either.

**Comment by CyrilWork** [comment]
my guess would be to not style body, but something else inside

**Comment by SamThilmany** [comment]
The documentation says that you should add these `data-*`attributes to the body. 
I also tested it with the attributes being on a div inside the body. in fact it was the parent of both elements, the navigation and the text. That didn't work either.

And as said, my test-case, where I added the `data-offset="50"` via the developer tools in Chrome to the example given in the v4 Documentation failed too. So it really seems to be a bug of Bootstrap.

**Comment by tiesont** [comment]
Just to eliminate the obvious: did you add a "position: relative" to the body?

**Comment by SamThilmany** [comment]
Yes of course!

**Comment by Johann-S** [comment]
`data-offset=""` isn't a valid value for this option see : http://v4-alpha.getbootstrap.com/components/scrollspy/#options + it throw an error : `Error: SCROLLSPY: Option "offset" provided type "string" but expected type "number".`

Scrollspy is initialised on `load` event so you cannot test `data-offset` via developer tools.
Everything is fine see this Codepen : https://codepen.io/Johann-S/pen/LyjXPO

**Comment by mast3rd3mon** [comment]
@Johann-S `data-offset=""` is a valid option? even look at the link you posted
