### ISSUE TITLE
document that dropdown-backdrop is shown for touch devices

### ISSUE THREAD

**Issue by SimonHeimberg** [twbs/bootstrap#22416]
Please update the documentation to report that the dropdown-backdrop is used on devices with **touch** support (and not only on **mobile** devices).
* on http://getbootstrap.com/javascript/#dropdowns-usage
* in the souce in [dropdown.js](https://github.com/twbs/bootstrap/blob/f2f805128508e82f0adc6e57b421dfb46d65a434/js/src/dropdown.js#L115)

And maybe there should be some discussion when the backdrop is necessary. For all touch devices or only some? Or only when the pointing device with touch support is used? Some toughts on [mozilla hack](https://hacks.mozilla.org/2013/04/detecting-touch-its-the-why-not-the-how/).

Background: Firefox reports touch support on my computer since 52.0 (indicated in note [2] on [touchstart](https://developer.mozilla.org/en-US/docs/Web/Events/touchstart)). (There is a touchpad and a trackpoint.) Because of a bug in my dropdown code, the backdrop was in front of the dropdown. Finding out why it happens on my computer and not on similar ones took much time. The documentation mentioning that the backdrop is enabled on touch support would have saved time.
Similar situation have happended in the past for others ([SO](http://stackoverflow.com/questions/30925699/hide-bootstraps-dropdown-backdrop-css-only), [SO](https://stackoverflow.com/questions/35612895/links-and-ng-clicks-in-bootstrap-dropdown-not-working-on-chrome-48-for-windows-8)).
Of course I will fix the z-order of the dropdown now. (I do not want to hide the backdrop, to support closing menu on real mobile devices.)

browser: firefox 52.0.2
os: windows 10, 64bit

**Comment by patrickhlauke** [comment]
v3 is really just in maintenance mode, but i've made this PR against v4 https://github.com/twbs/bootstrap/pull/22422

**Comment by patrickhlauke** [comment]
related, i may have found a way to completely avoid this backdrop altogether in v4 https://github.com/twbs/bootstrap/pull/22426
