### ISSUE TITLE
BS4 dropdown caret conflicts with ::after

### ISSUE THREAD

**Issue by 0dp** [twbs/bootstrap#22412]
Hi there,

Porting from BS 3.x to 4.0.0-alpha.6 I noticed this issue:

If I have a hover effect on a navbar link using

```
.effect a:hover::before,
.effect a:hover::after
```
it will conflict with

**_dropdown.scss**
```
.dropdown-toggle {
  // Generate the caret automatically
  &::after {
    display: inline-block;
    width: 0;
    height: 0;
    margin-left: $caret-width;
    vertical-align: middle;
    content: "";
    border-top: $caret-width solid;
    border-right: $caret-width solid transparent;
    border-left: $caret-width solid transparent;
  }

```

Reproduction here:
http://codepen.io/0dp/pen/rmBrba

Using the bs3.x style caret seems to work better in this scenario

```
<span class="caret"></span>
```

**Comment by mdo** [comment]
Going to stick with the generated content method via `::after`.

**Comment by 0dp** [comment]
Could it be considered to make best practice example to work around this scenario (ref. http://codepen.io/0dp/pen/rmBrba) for the documentation?

**Comment by acshef** [comment]
@mdo, would an option flag be out of the question?

```scss
.dropdown-toggle {
  @if $enable-pseudo-caret {
    // Generate the caret automatically
    &::after {
      ...
    }
  }

  ...
}

**Comment by 0dp** [comment]
IMO something along those lines would be helpful.

if $enable-pseudo-caret is false use the old style
else $enable-pseudo-caret is true use new style.

Since $enable-pseudo-caret default is true no extra markup would be needed.
In the docs it would simply describe the scenario, that if you want to use custom styles on .dropdown-toggle ::before ::after ie. for hover effects then set $enable-pseudo-caret variable and add `<span class="caret"></span>` to navbar markup

**Comment by mdo** [comment]
We won't be adding any CSS to flip between these two implementation options.

**Comment by 0dp** [comment]
@mdo and what would you propose for a solution for above mentioned scenario?
