### ISSUE TITLE
Input group with hidden addon

### ISSUE THREAD

**Issue by gertsteyn** [twbs/bootstrap#22418]
We often use input groups with multiple addons and then hide/show some of the addons based on the state of a previous select etc.

1) If an input group addon is made hidden (display: none) it visually looks like the right margin of the addon is still visible, I can't figure out how this happens, but ideally hidden addons should not have borders.

2) If the last addon is made hidden (display: none) the right border radius of the last visible addon stays at 0 instead of 4px. I.e. the input group now ends with square corners instead of rounded.

I'm not a CSS guru at all, but is it not possible to make the applicable :last and :first selectors look at visible instead of all addons?

**Comment by patrickhlauke** [comment]
could you provide a reduced test case (jsbin, jsfiddle or similar) as per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker ?

**Comment by oktalk** [comment]
The Bootstrap input group doesn't do this out of the box. Your issue would be requesting a new feature.

**Comment by gertsteyn** [comment]
I wouldn't really call hiding an element a new feature :-) Have a look at:
https://jsfiddle.net/wkzo2cyo/7/

**Comment by danijelGombac** [comment]
I think this two parts of code are responsible for the border radius 0 instead of 4px. Because .form-control is not first child and not last child. 

```
.input-group .form-control:not(:last-child),
.input-group-addon:not(:last-child),
.input-group-btn:not(:last-child) > .btn,
.input-group-btn:not(:last-child) > .btn-group > .btn,
.input-group-btn:not(:last-child) > .dropdown-toggle,
.input-group-btn:not(:first-child) > .btn:not(:last-child):not(.dropdown-toggle),
.input-group-btn:not(:first-child) > .btn-group:not(:last-child) > .btn {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
```

```
.input-group .form-control:not(:first-child),
.input-group-addon:not(:first-child),
.input-group-btn:not(:first-child) > .btn,
.input-group-btn:not(:first-child) > .btn-group > .btn,
.input-group-btn:not(:first-child) > .dropdown-toggle,
.input-group-btn:not(:last-child) > .btn:not(:first-child),
.input-group-btn:not(:last-child) > .btn-group:not(:first-child) > .btn {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
```

**Comment by danijelGombac** [comment]
The same problem is if you have hidden input after or before .form-control in .input-group.

**Comment by oktalk** [comment]
@gertsteyn If that's all you wanted to do, here you go:
https://codepen.io/oktalk/pen/rmNWQK

Bootstrap only supplies you with a base of common design patterns. The issue you've raised is not (IMHO) a "common" design pattern. If we all come together and agree that this should be added in to BS4, then I'm down for that. However, the amount of work is sizable enough to call this a new feature.

Best to document this issue as well as possible, and add the appropriate tags for future work.

**Comment by gertsteyn** [comment]
I thought the solution might be trivial to add, if it is not, please proceed as you see fit.

**Comment by bkdotcom** [comment]
agree that this would add extra unneeded complexity to bootstrap's core.

@gertsteyn a hack/fix for your need would be to toggle some classes on the input.  toggle something like `border-left-round` when showing/hiding the left add-on  and `border-right-round` when showing/hiding the right add-on.

```
.input-group .border-left-round {
   border-top-left-radius: .25rem;
   border-bottom-left-radius: .25rem;
}
```

potentially needs additional specificity 

or, @oktalk's  similar solution / via adding classes to the .input-group container

**Comment by mdo** [comment]
Not something we can accommodate I'm afraid. Despite hiding the element, our CSS selectors still know the element is in the DOM. We can't _not_ target it. The only solution is removing it from the DOM instead of hiding it.
