### ISSUE TITLE
$grid-breakpoint-{size} variables for (orientation: portrait) type queries

### ISSUE THREAD

**Issue by nimmolo** [twbs/bootstrap#22424]
It would be good to still have these for `orientation` media queries. 
If you guys think it's a good idea, i'll make a PR.

```
@media (min-width: $grid-breakpoint-sm) and (orientation: landscape), (min-width: $grid-breakpoint-lg) {
  rules: here;
}
```

I don't believe you can generate a group of similarly named variables recursively in SASS from the $grid-breakpoints map, but this function accomplishes the same thing:

```
@function breakpoint($size) {
  @if map-has-key($grid-breakpoints, $size) {
    @return map-get($grid-breakpoints, $size);
  }

  @warn "Unknown `#{$size}` in $grid-breakpoints.";
  @return null;
}
```

then: 

`  @media (min-width: breakpoint(sm)) and (orientation: landscape), (min-width: breakpoint(lg)) {`

**Comment by nimmolo** [comment]
A function could accomplish the same thing:

```
@function breakpoint($size) {
  @if map-has-key($grid-breakpoints, $size) {
    @return map-get($grid-breakpoints, $size);
  }

  @warn "Unknown `#{$size}` in $grid-breakpoints.";
  @return null;
}
```

**Comment by mdo** [comment]
No plans to add orientation mixins at this time, thanks though!

**Comment by Misiu** [comment]
@mdo anything changed? I think this would be useful.
