### ISSUE TITLE
input/input-group with clear function: not found, but have a bug about input with optional icons

### ISSUE THREAD

**Issue by lu-yuan** [twbs/bootstrap#22428]
Test version: BS3.3.7
Browser: chrome
Test image: attach file
Make some changes, please see attach file.

![Uploading image.png…]()
http://pan.baidu.com/s/1eSmU84y

**Comment by mdo** [comment]
This issue isn't super clear what you're problem is, but beyond that, we're not actively developing v3 right now. See message below.

---

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
