### ISSUE TITLE
grunt generating lots of new .css.map files for examples

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#22427]
not sure if this is specific to my setup on Windows, but: it seems that by default running `grunt` now generates map files for all the various css files in the examples. as these aren't in the current repo, they're all flagged all the time as new untracked files. any way to either disable this in explicitly in the grunt script, or alternatively to add the map files to the repo so they're at least only showing up as modified, rather than untracked?

> ![capture](https://cloud.githubusercontent.com/assets/895831/24979148/0ff41da6-1fcb-11e7-9d0b-6d0ce02a71a3.PNG)

**Comment by bardiharborow** [comment]
I think #22045 may have fixed this?

**Comment by patrickhlauke** [comment]
Closed by https://github.com/twbs/bootstrap/pull/22477
