### ISSUE TITLE
Print in Chrome cuts off pages, depending on viewport size

### ISSUE THREAD

**Issue by thadboyd** [twbs/bootstrap#22425]
Example page: https://v4-alpha.getbootstrap.com/
Browser: Chrome (v54, Windows)

When the window is narrowed to xs, and I print, the whole homepage prints (6 printed pages).

However, if I print the homepage when my browser window is sized at sm or above, the homepage gets cut off in the middle of the Riot and Newsweek screenshots (5 printed pages).  The bottoms of those images, the text and button underneath, and the page footer do not appear in the print preview or on the printout.  (The issue also occurs if I print using the system dialog.)

The issue also exists in Bootstrap v3; you can see the same thing happen on https://getbootstrap.com/.

**Comment by TobiasKrais** [comment]
+1 Same issue here. Firefox prints page correctly, but print preview has same error.

**Comment by patrickhlauke** [comment]
I believe this issue is resolved in the latest code (looking at https://twbs.github.io/staging/)

**Comment by TobiasKrais** [comment]
Not solved in Alpha 6.

**Comment by patrickhlauke** [comment]
> Not solved in Alpha 6

and as i said, in the latest code in the repo (which is newer than the alpha 6 release http://v4-alpha.getbootstrap.com/) it seems the cut-off issue (at least the one described in the issue starter, taking the bootstrap site's homepage as example) isn't present anymore.

**Comment by TobiasKrais** [comment]
Hi Patrick,
sorry for disturbing again. Where can I download nightly builds to be able to test it?
Thanks for your hard work for this great project!
Greetings,
Tobias

**Comment by patrickhlauke** [comment]
Right here from github, but you'll have to build it/compile it yourself I'm afraid.

**Comment by TobiasKrais** [comment]
Verified in 4beta -> fixed. Thanks a lot! Bootstrap 4 will be great!
