### ISSUE TITLE
Make sure that svg icon colors are set when color is set.

### ISSUE THREAD

**Issue by dietergeerts** [twbs/bootstrap#22430]
I think this is more of a feature request, to be able to style svg icons.

What I have now:

I have a class `svg-icon`, for icons that are inside text and buttons, and that will scale according to the text size etc..... This is really great to use icons inside text. The only problem is the color of these icons. Now I need to copy/paste the bootstrap scss, and change color to my svg-icon-color mixin, so that svg icons have the same color.

What I want to see:

The addition of an `svg-icon` class, and everywhere color is used, svg icons should get that color too.

**Comment by patrickhlauke** [comment]
so really what you're asking for is a new `.svg-icon` class, and all the scss necessary to also set the color explicitly for all the different contexts in which you may be adding an `.svg-icon` to? this seems like a fairly large undertaking for something we currently don't use/have in bootstrap, not sure if it's a generic enough use case. @mdo?

**Comment by acshef** [comment]
Or use the CSS value [`currentColor`](http://caniuse.com/#feat=currentcolor).

Here's a random example from CodePen that show it being used on an SVG's `fill` and `stroke` properties: https://codepen.io/yoksel/pen/xiLen/

**Comment by patrickhlauke** [comment]
`currentColor` won't work if (as i suspect) the SVG is being added as a CSS background, because in those situations the SVG lives in a new context (rather than being in the context of where it is within the HTML), so `currentColor` is meaningless there

**Comment by patrickhlauke** [comment]
randomly, something i looked at a while ago in the context of bootstrap's hamburger menu https://jsbin.com/toyoqopequ/edit?html,css,output

**Comment by patrickhlauke** [comment]
but of course yes, if @dietergeerts is adding actual inline `<svg>`, then adding one global `.svg-icon { stroke:currentColor; }` will make the SVG (provided it's using strokes, otherwise set the fill color instead) automatically take whatever the context's foreground color is. didn't mean to sound dismissive there @acshef, it was a good addition to the thread here :)

**Comment by mdo** [comment]
This doesn't seem like something we should be handling across the entire project. We'll defer to the icon sets for how they wish to be colored/styled as opposed to making up our own generic classes. Thanks though!

**Comment by dietergeerts** [comment]
@mdo it's not about adding new classes, but making sure that .text-success etc... can be used with svg's. But like quoted, I could use currentColor if we only support IE11 and up, but that's not the case at the moment.

**Comment by mdo** [comment]
`currentColor` is available in IE9+ if I recall correctly.

Apply `currentColor` to your SVGs as needed, and text utilities work apply to them. For example, here's how we do it at GitHub [with our Octicons](https://github.com/primer/octicons/blob/master/lib/octicons.css):

```
.octicon {
  fill: currentColor;
}
```
