### ISSUE TITLE
Bootstrap Grid Cols Don't Wrap in Safari 8 and Below

### ISSUE THREAD

**Issue by hamiltonbrooke** [twbs/bootstrap#22435]
In Safari 8 and below, my columns don't automatically wrap like they do on other browsers.

They instead break outside of the container boundaries and all stay on one line instead of wrapping onto a new line.

Screenshot attached and here is a live link to the page:

https://www.babbelegal.com/people/

![img_0475](https://cloud.githubusercontent.com/assets/14992849/24997817/ef815006-202f-11e7-8560-2b3414672613.PNG)

**Comment by mathurvishal** [comment]
Don't user safari 8.

**Comment by oktalk** [comment]
@matheusazzi Your response is a bit crass.

@hamiltonbrooke The honest answer is:
> Bootstrap supports the latest, stable releases of all major browsers and platforms. On Windows, we support Internet Explorer 10-11 / Microsoft Edge.
https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#supported-browsers

Bootstrap is a forward thinking CSS framework. If you want to support legacy browsers please use Bootstrap v3 for that: https://github.com/twbs/bootstrap

**Comment by matheusazzi** [comment]
@oktalk I think you mentioned the wrong person.

**Comment by oktalk** [comment]
Ha. @matheusazzi my mistake. Carry on.

**Comment by mdo** [comment]
Closing given it's outside our supported browser ranges.
