### ISSUE TITLE
Wrong Color in Popover Arrow

### ISSUE THREAD

**Issue by IdanCo** [twbs/bootstrap#22432]
When popover direction is set to **bottom**, the arrow has the wrong color:

![image](https://cloud.githubusercontent.com/assets/10364499/24996862/27296536-203d-11e7-9949-76e59c6da489.png)

Couldn't find any related PRs, i'll push one soon...

**Comment by Johann-S** [comment]
Closed by : #22433

**Comment by IdanCo** [comment]
@Johann-S , the plot thickens -

After further research, I'm assuming the reason for the mixup with the color variable was intended to handle cases where the popover has a title:
![image](https://cloud.githubusercontent.com/assets/10364499/25005856/3b7a709a-2063-11e7-8ae6-372122c8efc1.png)

The problem was that it affected all bottom-popovers, even those without a title.

This conflict can be solved by using the already existing [title::before](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_popover.scss#L93) element to "cover" the existing arrow with the right color. I'll do a PR with this solution and let you decide what's best.

**Comment by Johann-S** [comment]
Oh nice catch I didn't know that. Yeah sure create your PR but this time I'll CC @mdo because I don't know all the use case
