### ISSUE TITLE
Error on copied minified bootstrap into a new web project add === for ==

### ISSUE THREAD

**Issue by rosser2121** [twbs/bootstrap#22438]
Hi Bootstrap devs-

When copying and pasting the 

Into a new Web Project we get this error when compiling in chrome.

You should be able to replicate by building a new web project.  Kindly let me know.

/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under the MIT license
 */
// From sources tab in inspector

if("undefined"==typeof jQuery)throw new Error("Bootstrap's JavaScript requires jQuery");+function(a)

We think if you turn == to === it might fix the problem.
Hopefully this doesn't slow down any web development projects on the internet.

Ta ta

Development Environment
MAC os Sierra = 10.12.4
Chrome = Version 57.0.2987.1
![screen shot 2017-04-13 at 2 40 15 pm](https://cloud.githubusercontent.com/assets/24345029/25019303/24ac1f5e-2058-11e7-8e33-acdec73ecfb4.png)
![screen shot 2017-04-13 at 2 40 15 pm](https://cloud.githubusercontent.com/assets/24345029/25019327/34501f8c-2058-11e7-9e8a-475076371e1f.png)

33 (64-bit)

The below sandbox doesn't show the error clear
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

**Comment by acshef** [comment]
The error explicitly states that **Bootstrap's JavaScript requires jQuery**.

I can't be certain of your setup, but from your screenshot it looks like you don't have jQuery. Are you including jQuery, and are you sure it's loading before Bootstrap's JavaScript?

**Comment by mdo** [comment]
Closing per above comment.
