### ISSUE TITLE
No disable state for buttons (checkbox) group

### ISSUE THREAD

**Issue by 776166** [twbs/bootstrap#22431]
- Mac OS X, Chrome (57.0.2987.133 (64-bit))

https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons
Can not make buttons disabled.

**Comment by oktalk** [comment]
You can add the `disabled` state to the label in this case and to the input as well. I've created a pen showing the checkbox radio buttons with a disabled state:
https://codepen.io/oktalk/pen/YVzmMv

**Comment by 776166** [comment]
Well. I think, that I found the problem: jquery loaded before bootstrap.js. :-\

**Comment by 776166** [comment]
If load jquery before bootstrap.js checkboxes are not working (http://codepen.io/776166/pen/QvwaMY).
If load bootstrap before jquery bootstrap not work.

**Comment by rajarju** [comment]
I dont think there is any JS involved here.
You can try to block the click event on the label from reaching the checkbox by adding
`pointer-events: none;` when the button/label has a disabled class.

But this will remove the cursor style from the element.

**Comment by 776166** [comment]
I think it is a bug and this should work out of the box. :)

**Comment by mdo** [comment]
What's the problem here exactly? Buttons have disabled states.

**Comment by patrickhlauke** [comment]
Looking at http://codepen.io/776166/pen/QvwaMY it seems that the `active` class is set/unset on the `<label>` despite the related checkbox being `disabled` and despite the label itself having `.disabled` class.

@mdo the whole "button-like checkboxes" thing is, without doubt, one of the most problematic of the patterns we currently have in BS4. wondering if we should try to work towards a cleaner solution here using just CSS and rely purely on the browser's own handling without adding any classes. I could swear I had filed an issue or PR with a potential working solution ages ago, but can't seem to locate it. I'll go on a hunt...

**Comment by mdo** [comment]
@patrickhlauke Probably something with inputs as siblings of labels?

**Comment by 776166** [comment]
@mdo The problem is: even input is disabled, i can change its state by click. On official bootstrap 4 site i see this bug.

**Comment by patrickhlauke** [comment]
very late, but: this should now be fixed by https://github.com/twbs/bootstrap/pull/28834
