### ISSUE TITLE
To mutch out styles in dist css

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#22434]
the  .container and  .container-fluid class have always the same paddings for media breakpoints!
https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L632-L665
https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L695-L729

the same on .row with the margins
https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L731-L769

the same .col's with paddings
https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L782-L841

what is the trick, can you explain!

jonny

**Comment by joneff** [comment]
The padding (or gutters) on each responsive breakpoint can be customized, see https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L209-L217. By default they have the same value, hence the duplication of styles.

**Comment by patrickhlauke** [comment]
yup, what @joneff said. they may be same by default, but splitting them out allows authors to more easily tweak the stuff based on their own particular needs
