### ISSUE TITLE
Use :focus-ring (and its polyfill) to gracefully handle dropdown triggers etc

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#22447]
Meta-issue to explore the use of `:focus-ring` https://github.com/WICG/focus-ring for situations that currently aren't all that great (with things keeping a visible focused style after being clicked with the mouse), including:
- dropdown triggers
- buttons and their related variants
- carousel controls

Would be great to get this added before V4 final, by which time there should be good support in latest browser versions (and to add polyfill for older versions)

**Comment by FezVrasta** [comment]
In my company we make use if `what-input` and a custom PostCSS plugin that adds a `:focus-mouse` pseudo selector. Doing so we simply do:

```
.class:focus-mouse { outline: none }
```

It also adds a `:focus-keyboard` useful to add focus style to custom elements.

I think it's a better approach compared to the proposed standard. And doesn't add classes to the elements, because only `html` gets alerted.

**Comment by patrickhlauke** [comment]
the advantage of going with a proposed standard (which is already implemented in firefox anyway, as that's where the proposal took initial inspiration) is that unlike `what-input`'s take, it will be natively adopted by browsers, obviating the need for a polyfill in future altogether. but yes, `what-input` (which i've contributed to in the past) was considered some time ago as well, but it seems to go beyond our immediate needs

**Comment by FezVrasta** [comment]
I see, I really hope they will change the proposed standard because it doesn't make any sense to me at the moment 😥

**Comment by patrickhlauke** [comment]
the standard solves one very specific but common problem: when clicking/interacting with certain controls (`<button>` etc) with a mouse or even touch, browsers currently use heuristics (specific to each browser) to decide whether or not to show the default focus outline; for keyboard users, the focus outline is essential to indicate where they currently are within the page; but for mouse/touch users it's usually seen as visually redundant and ugly.

traditionally, designers have simply added `outline: none` or similar to suppress the outline (which used to show all the time for focused items, before browsers implemented heuristics) altogether. this caused problems for keyboard users and is a bad idea.

adding explicit `:focus` styles, while good for keyboard users, also results in browser heuristics being completely bypassed. it explicitly says that when an element receives focus (regardless how it received focus - by mouse, touch, keyboard) it should have those particular styles.

`:focus-ring` basically allows you to say "apply these styles, but only in situations where the browser would normally show its default outline", i.e. only in the same situations in which browser heuristics would also determine that the default outline should be shown. this way you can provide very specific styles that generally only apply to keyboard users, and are not shown for mouse/touch interactions. which gives you exactly what you want in most cases - e.g. in the case of Bootstrap's dropdowns, clicking on the control to open a dropdown with a mouse you wouldn't want a visible outline/focus style on the dropdown trigger...but for a keyboard user, you do want to provide a visible "this item currently has focus" style.

**Comment by FezVrasta** [comment]
Yes I understand, but what people need is a `:focus` that matches when you don't want to show the outline, so that you can remove it with `:focus-something { focus: 0 }`.

With the current proposal instead you'll be forced to do `:not(:focus-ring) { focus: 0; }` which doesn't make any sense.

**Comment by patrickhlauke** [comment]
```
:focus { outline: 0; }
:focus-ring { /* go crazy with whatever visual indicator you wanna give for kbd users */ }
```

**Comment by FezVrasta** [comment]
Yes but I think it's better to leave the default focus style and simply disable it when interacting with mouse, because the focus ring should be consistent across websites to don't confuse the users. By the way this isn't the right place to discuss about this.

**Comment by rafalp** [comment]
How will polyfill fly with JS view libraries? Will I have to run extra logic whenever I render button for polyfill to do its magic?

**Comment by patrickhlauke** [comment]
Closing this out for now. Will revisit once native support for `focus-visible` (yes, they renamed it...) is a bit more mature
