### ISSUE TITLE
Problem with a nested container

### ISSUE THREAD

**Issue by zhivulinal** [twbs/bootstrap#22446]
When I put the .container inside the .container-fluid, then the nested container is poorly displayed in the mobile version. Fixed this by adding width: 100%
`.container {`
`    @media(max-width: @screen-sm-max) {`
`        width: 100%;`
`    }`
`}`

`<div class="container-fluid bg-theme">`
`  <div class="row">`
`    <div class="container">`
`      <div class="row">`
`        <div class="col-12">call</div>`
`      </div>`
`    </div>`
`  </div>`
`</div>`

**Comment by oktalk** [comment]
I could be wrong, but I'm fairly certain you should never nest a `.container` inside of a `.container`. And, you definitely should never nest a `.container` inside of a `.row`.

Nothing specifically talks about this issue in the docs (not that I could find). Bootstrap v3, however does mention this issue:
https://getbootstrap.com/css/#overview-container

> Bootstrap requires a containing element to wrap site contents and house our grid system. You may choose one of two containers to use in your projects. Note that, due to padding and more, neither container is nestable.

**Comment by mdo** [comment]
Containers are fixed width. There's no need to nest them, but if you find a reason for it, use two fluid containers instead of a fixed width one.
