### ISSUE TITLE
Dropdown fails to trigger action when inside a modal on iPAD, latest Alpha

### ISSUE THREAD

**Issue by javismiles** [twbs/bootstrap#22452]
- This issue happens on iPAD IoS,  (issue does not happen on Android or Desktop).
- I Create a general dropdown, exact same one of your documentation.
- It all works perfect, except when I insert it within a Modal.
- When it exists within a modal that opens, clicking on the dropdown rows closes them but fails to trigger the action present at the href=""
- As I say, the issue is triggered by  the Dropdown existing within a Modal. (outside of a Modal all works ok).
- This issue is happening in the latest Alpha 6, it is not happening in a previous Alpha version, it has broken in the latest Alpha.

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>

**Comment by javismiles** [comment]
The same action works with the previous alpha version and fails with the latest one, on iPAD. It seems to have broken in this latest alpha version.

**Comment by patrickhlauke** [comment]
please provide an isolated test case on jsbin, jsfiddle or similar

**Comment by javismiles** [comment]
Yes, this issue is now confirmed with the following isolated test case, it uses the latest Bootstrap Alpha, and It ran on an iPad device with the latest IoS, test case here:
https://codepen.io/javismiles/pen/bWdrRM

It fails on iPad, it works on Android, Laptop, etc

all best

**Comment by javismiles** [comment]
Im looking at the bs code, i cannot debug on ipad because i dont have an ioS laptop/desktop but this part of the code:
`if (event && (event.type === 'click' && /input|textarea/i.test(event.target.tagName) || event.type === 'focusin') && $.contains(parent, event.target)) {`

is being triggered on android and desktop but not on ipad, maybe that's related to the issue

**Comment by javismiles** [comment]
i have been  testing further, 
on laptop and android, event.type is triggered with types focusin and click,
on  ipad only focusin events are triggered, no click event is triggered, also the events on android and laptop are triggered over the A tagname, on ipad over DIV

**Comment by javismiles** [comment]
ok so i found a way to bypass the issue, just  to demonstrate which  part is stopping it.
If i change this
`  if (event && (event.type === 'click' && /input|textarea/i.test(event.target.tagName) || event.type === 'focusin') && $.contains(parent, event.target)) {`

to this

` if (event && (event.type === 'click' && /input|textarea/i.test(event.target.tagName) || event.type === 'focusin')) {`

therefore getting rid of this:
`&& $.contains(parent, event.target)`

then it works on iPAD!

so that part is somehow stopping  the triggering of the action on iPAD, this part
`&& $.contains(parent, event.target)`

**Comment by javismiles** [comment]
confirmed that getting rid of `&& $.contains(parent, event.target)` and leaving:
`if (event && (event.type === 'click' && /input|textarea/i.test(event.target.tagName) || event.type === 'focusin')) {			
          continue;
        }`

fixes the problem on iPAD. Now, of course i know that what i eliminated is there  for a reason and cannot be eliminated, I hope you guys can fix this in the right way, I'm trying to help because having the dropdown within the modal is key for the cart of my app and it won't work on iPad till this is fixed (i guess same thing may happen on other IoS devices), best wishes

**Comment by pratikthecook** [comment]
I have the same issue when rendering a dropdown inside a modal. Our Component Library is built on Angular using Bootstrap 4 Link to the issue : [Amexio Bootstrap 4 DropDown issue](https://github.com/meta-magic/amexio.github.io/issues/8)

**Comment by mdo** [comment]
Testing this with the latest v4 CSS and JS (v4.5.3) and on my iPad Pro running iOS 14, I don't see anything broken. The modal opens, the dropdown opens, and tapping the dropdown items updates the modal title. https://codepen.io/emdeoh/pen/ZEpjNRZ 

Closing out.
