### ISSUE TITLE
v4 sass import sequence wrong in bootstrap.scss?

### ISSUE THREAD

**Issue by stonecooler** [twbs/bootstrap#22458]
If I change/override in case of theming / branding the value of the variable $blue
to another blue / my branding blue in my "_custom.scss" (as described in the [documentation](https://v4-alpha.getbootstrap.com/getting-started/options/)) I had also override all variables in "_custom.scss" which are using $blue. Okay this is only $brand-primary, but $brand-primary itself is used in many variables definitions as well (16 times). This is not useful.

Another example: If I change/override $spacer I had also override/copy $spacer-x, $spacer-y and $spacers
into "_custom.scss" as well into "_custom.scss"

Every variable (overridden in "_custom.scss") from "_variables.scss" which is also used in "_variables.scss" in other variable definition makes it neccessary to override the "other"-variables in "_custom.scss" also.

Moving the import "custom" above the import "variables" in "bootstrap.scss" fixed it for me.
But is this a valid way, or do I forgot something or missed something out.
And is the change of the import sequence more usefull for developers in the future?

Thank you.

**Comment by mdo** [comment]
The order is correct. There's some history around this in the issues as this has been brought up and changed back and forth a couple times. We use `!default` flags in all our vars, so if you update them before or after the variables file, they get updated. However, this precludes you from using those vars in the custom.scss file. If that file doesn't work for y'all, definitely try a different approach—it can't solve every problem unfortunately.
