### ISSUE TITLE
Graceful degradation for navbar is broken (flexbox)

### ISSUE THREAD

**Issue by sintro** [twbs/bootstrap#22456]
If you want to make typical navbar with collapsable links (for mobile view), the default code of bootstrap will never works fine in situation where there is no flexbox support in browser.
You can easily repeat the problem in this example page:
https://v4-alpha.getbootstrap.com/examples/starter-template/
Open web-inspector, go to "#navbarsExampleDefault" element, disable all "flex" options, so it will be rendered as block element. Look at links - they all dissapeared. 
The problem is in class "collapse" this item must have by default for correct behaviour of collapsing feature. If it has it (it must), when the item has "block" class, all the links are hidden, because the "display: none" is attached to it with "collapse" class.
But it obviously have to has more precise settings, based on @media queries, so the "collapse" class will be active only for "mobile" view.
There are also some other css problems, which causes different rendering for browsers without flexbox support, but they are not so critical (but still worth fixing if you really need graceful degradation for flexbox in bootstrap 4)

**Comment by nimmolo** [comment]
@sintro   

Bootstrap 4 will not support browsers without flexbox at all, see [here](https://github.com/twbs/bootstrap/pull/21389). 

If you need graceful breakdown for flex you should use v3.

**Comment by bardiharborow** [comment]
Closing per previous comment.
