### ISSUE TITLE
Too few cards to fill number of .card-columns slightly before break point (leaves blank column)

### ISSUE THREAD

**Issue by NotAnAmbiTurner** [twbs/bootstrap#22451]
I wrote a detailed question on StackOverflow, to try to make sure this wasn't a "me doing it wrong" thing. I hope it's okay that I post a link here instead of re-typing: [http://stackoverflow.com/questions/43271316/bootstrap-4-card-masonry-style-columns-column-numbers-at-breakpoints-blank](http://stackoverflow.com/questions/43271316/bootstrap-4-card-masonry-style-columns-column-numbers-at-breakpoints-blank).

The basic issue is shown in the below screengrabs from Chrome DevTools Version 57.0.2987.133.

The error doesn't appear to be occurring anymore (though it was happening sporadically before as well), and may have been fixed by the addition of:
```
    -webkit-column-count: #;
    -moz-column-count: #;
```
to the CSS where the .column-court was altered.

![bhastings_masonry_1599](https://cloud.githubusercontent.com/assets/6279988/25069570/fa8b4900-2239-11e7-8b5c-81c3d96d8c47.png)
![bhastings_masonry_1621](https://cloud.githubusercontent.com/assets/6279988/25069569/fa8946e6-2239-11e7-9d48-6d777df89d24.png)
![bhastings_masonry_1620](https://cloud.githubusercontent.com/assets/6279988/25069571/fa8ceb34-2239-11e7-9078-a0fde87fca49.png)
![bhastings_masonry_1600](https://cloud.githubusercontent.com/assets/6279988/25069572/fa8cf4b2-2239-11e7-9c26-3634b6dcbb0e.png)

**Comment by mdo** [comment]
Not seeing any issue on our end now. Guessing this was somehow resolved?

**Comment by travhall** [comment]
I'm seeing this issue … 

<img width="640" alt="screen shot 2018-02-09 at 8 00 02 am" src="https://user-images.githubusercontent.com/3809845/36033816-48377f86-0d6f-11e8-9664-511e22449cb4.png">

… the upper portion is displaying 8 cards w/in card-columns, the lower displays 9

**Comment by midzer** [comment]
`.card-columns` are sometimes lil bit buggy. I've experienced same for an image gallery.

@travhall Check out https://github.com/twbs/bootstrap/issues/20321. I hope it lands in a future bootstrap version.

**Comment by travhall** [comment]
agreed, thanks @midzer, I'll give this a look over!

**Comment by warniiiz** [comment]
`.card-columns` is not working properly with `.card` of the same height. For the second example (with 9 cards), I would tweak the margin of either the first or the last card in order they display smoothly in all the available columns. Customizing the bootstrap CSS like this (considering the default margin-bottom of `.card` is `0.75rem`):

```
.card-columns .card:first-child {
  margin-bottom: 0.74rem;
}
```
