### ISSUE TITLE
navbar fixed-top overlays main page

### ISSUE THREAD

**Issue by derek-v4** [twbs/bootstrap#22459]
Bootstrap V4 Alpha6
Using fixed-top on navbar, when collapsed the menu expands covering the main content screen instead of pushing the content down.
The situation can be seen in the bootstrap examples @
https://v4-alpha.getbootstrap.com/examples/navbar-top-fixed/#

**Comment by mdo** [comment]
Instead of using fixed, use the static/default navbar then. Both are valid options.
