### ISSUE TITLE
Card shadow doesn't play well with cards-column

### ISSUE THREAD

**Issue by f-ricci** [twbs/bootstrap#22450]
Hi,

The project I'm working on has shadows enabled and I'm experiencing a problem, when using the card-columns, that the card's shadow is cut.

I've tried to reproduce the issue in a pen:
https://codepen.io/facricci/pen/ybNVVY

This works perfect on firefox but doesn't on opera, chrome and safari.

I just wanted to let you know about this issue although this issue is related to browsers vendors.

**Comment by mdo** [comment]
That's not something we can help with unfortunately. That's just how the browsers have implemented card columns. You can try http://stackoverflow.com/questions/7785374/how-to-prevent-column-break-within-an-element for some help in determining when to break across the columns though.

**Comment by f-ricci** [comment]
@mdo thanks for the feedback.

**Comment by trandaison** [comment]
@f-ricci How did you solve the issue?

**Comment by trandaison** [comment]
Adding `transform: translateZ(0)` to the column item will solve the problem. 
Tested on Chrome.
