### ISSUE TITLE
Cards in card-columns changes places.

### ISSUE THREAD

**Issue by Velociapcior** [twbs/bootstrap#22465]
Hello,

I am working with bootstraps' v4 cards and cards column. In my my project, cards have collapsible element and many cards can be added to card-columns container. Whenever collapsible element changes its state, different cards change their position, even card, which was clicked, can go to another column. Is there any option to make cards stay in their initial place, or to animate transition of cards, so it would be less confusing

**Comment by leandroruel** [comment]
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by mdo** [comment]
This is the browser repainting the content across your columns as the column content changes. Nothing we can do about that I'm afraid. If you need more control of the columns, you likely need to use the grid system instead.
