### ISSUE TITLE
The col-{breakpoint}-auto class is picking up the lesser width device max-width 

### ISSUE THREAD

**Issue by kannanwisen** [twbs/bootstrap#22463]
Hi,

Kindly prefer to the below url for easy understanding

https://jsbin.com/qajobibovi

```
<div id="d1" class="row">
  <div class="col-md-4 col-lg-2">Col 1</div>
  <div class="col-md-4 col-lg-auto">
    Col 2 Some Text.  Some Text.  Some Text.  Some Text.  Some Text.  
    Some Text.  Some Text.  Some Text.  Some Text. 
  </div>
  <div class="col-md-4 col-lg-2">Col 3</div>
</div>
```

In lg device, the col-lg-auto is picking up the col-md-4 max-width. that is 33.33%.

But I think, it suppose to be 66.67%. since col-lg-2 max width is 16.66%

Any thoughts?

**Comment by sameer-dudeja** [comment]
I think that is why because you are using col-md-4 also in that.
Instead just use 
`<div class ="col-lg-auto">some text some text.....</div>` 
it will be 66% this time

**Comment by mdo** [comment]
You're using the wrong class: https://jsbin.com/napohed/edit?html,css,output. `-auto` means size the column to the column's _content_.
