### ISSUE TITLE
Bootstrap v4 - Navbar with Container responsive issue in the example 

### ISSUE THREAD

**Issue by Cobra86** [twbs/bootstrap#22469]
Hi,
Sorry, if this issue is exists, I already searched and I couldn't find any.
In this example: https://v4-alpha.getbootstrap.com/examples/navbars/#
the container Navbar doesn't look right in mobile view. 
![image](https://cloud.githubusercontent.com/assets/7024154/25170496/a6acb80e-24e2-11e7-9790-b5d1d8f44f5c.png)

Thanks,

**Comment by rafalp** [comment]
Looks like dupe of #21590

**Comment by mdo** [comment]
Yup, already fixed in `v4-dev`.
