### ISSUE TITLE
custom-control margin and padding

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#22460]
Currently, .custom-control uses a sass variable $custom-control-gutter which is default 1.5rem;

It seems the reason for this additional "0.5" is for creating space between the input (.custom-control-indicator) and any label text (.custom-control-description).

However, when desiring to use a standalone input without a label (perhaps for use in a table where the label is in a <thead> element in a column, as an example), this additional padding makes things space poorly. There are actually two reasons for this: the margin applied to the .custom-control, and the padding applied to the .custom-control.

The margin comes about because of https://github.com/twbs/bootstrap/pull/21295
Now, this isn't too bad to "overcome" by just using m-0 class on the .custom-control.

However, the padding just doesn't make sense to me why it's that way to begin with. Since the "custom-control-description" class is already documented, why not apply the padding to this element instead? There is no reason to create space around the input for purposes of a description unless there is, indeed, actually a description! (right?). So I think that the proper sass for this should be:

```
.custom-control {
  1rem;
  .custom-control-description {
    0.5rem;
  }
}
```

See the following fiddle for an easy to see representation: https://jsfiddle.net/g9uqgbb5/6/

Thoughts?

**Comment by 719media** [comment]
One more possibility here is to also utilize the fact that .custom-control is using flexbox to position the indicator using align-items instead of using absolute positioning. I'm not sure if there is some accessibility reason that absolute positioning may be utilized? If not, then the following css is even better:

Current sass
```
.custom-control {
  padding-left: $custom-control-gutter;
}
.custom-control-indicator {
  position: absolute;
  top: (($line-height-base - $custom-control-indicator-size) / 2);
  left: 0;
}
```

Proposed sass
```
.custom-control {
  /* no padding defined */
  align-items: center;
}
.custom-control-indicator {
  /* no absolute position or top/left defined */
}
```

As an added benefit, this also allows for easier "multiple sizes" of the custom-control (like a -lg) if desired.
See https://jsfiddle.net/s7khLqct/2/ for a demo

**Comment by mdo** [comment]
We'll be leaving this as-is.

> However, the padding just doesn't make sense to me why it's that way to begin with.

We add padding to the left of the parent, then use negative margin to position the custom checkbox/radio over that padding. This ensures proper text alignment if your checkbox has multiple lines of content.
