### ISSUE TITLE
`fade` tag prevents rendering of `modal` when there is no JQuery/JS

### ISSUE THREAD

**Issue by trajano** [twbs/bootstrap#22478]
I am trying to render a modal without using JQuery or JS.  I got it working for the most part with http://jsfiddle.net/trajano/dz1waeq1/1/ where I set 
```
.modal {
    display:block;
}
```
using the code from https://v4-alpha.getbootstrap.com/components/modal/#modal-components

What I found was `fade` prevents it from rendering but without it the backdrop does not "fade"

**Comment by patrickhlauke** [comment]
as this seems to be a question broadly about "how can I use Bootstrap in a way that it's not intended, i.e. without jQuery/JS", I'd recommend consultin StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
