### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#22476]
Due to the merged of https://github.com/twbs/bootstrap/pull/22045

~they are few errors, on Travis see :~
~- https://travis-ci.org/twbs/bootstrap/jobs/223876338#L312~
~- https://travis-ci.org/twbs/bootstrap/jobs/223876309#L303~

And on my computer (Win10) `js-compile-bundle` don't work because it failed here : 
`shx sed 's/^(import|export).*//'`

I changed this part of this task into to make it works : 

`shx sed \"s/^(import|export).*//\"`

/CC @bardiharborow

**Comment by bardiharborow** [comment]
Regarding Travis, the main branch is passing. Your branch may need to be rebased though. Thanks for testing on Windows, I haven't really done that yet. I'll get that issue patched tonight.

**Comment by Johann-S** [comment]
But my branch is up to date @bardiharborow , so I don't understand how my branch can generate this build issue

**Comment by bardiharborow** [comment]
@Johann-S, I just re-shrinkwrapped your branch, and it's all green now.

**Comment by Johann-S** [comment]
Yes I saw it thank you 👍 but I don't understand why I didn't have the good shrinkwrap... I rebased my branch this morning

**Comment by bardiharborow** [comment]
@Johann-S, you'd overridden the shrinkwrap to include popper.js, and rebasing didn't pick up some last minute changes that I made to my PR before merging it.

**Comment by bardiharborow** [comment]
Fixed in #22477.

**Comment by Johann-S** [comment]
It seems they are build issues with this error : `sh: 1: grunt: not found`
https://travis-ci.org/twbs/bootstrap/builds/225503458

It's strange because sometimes this error doesn't happen like here : https://travis-ci.org/twbs/bootstrap/jobs/225375395

/CC @bardiharborow
