### ISSUE TITLE
modal with inputfields - line bug with Edge browser and 150% zoom

### ISSUE THREAD

**Issue by twofourjack** [twbs/bootstrap#22489]
Hello, 

**Requirements to reproduce this bug:** 
- Microsoft Edge Browser 38.14393.10660 (Maybe all versions of Edge)
- Windows 10
- On Windows there is a option for "Customize diplay setting" where you can change the size of text, apps and other elements. There are zoom precentages (100%, 125%, 150%) -> Change it to 150 %
![windows10 display-monitor settings](https://cloud.githubusercontent.com/assets/27823744/25267003/8e98c2de-2673-11e7-8705-c12f8d09d67e.png)
- big display/monitor (resolution 1920x1080)

1. Go to http://getbootstrap.com/javascript/ to section 
"Varying modal content based on trigger button" and klick on button Open modal for @getbootstrap

2. Now you see this:
![modal bootstrap](https://cloud.githubusercontent.com/assets/27823744/25267066/c4efe632-2673-11e7-9ac8-3ea88ebccbc8.png)

3. If you klick into fields on modal or hovering with mouse on the 2 buttons and the cross to close the modal, there are display some lines. The positions of the lines are different, but the lines will every time shown: 
![screenshot bug](https://cloud.githubusercontent.com/assets/27823744/25267227/3ed8d5e4-2674-11e7-8c7d-bc0370fd8faf.png)

btw: I am project manager for a website agency and we made a website for our customer. This website is available on https://www.bestlance.de/. On the frontpage on top of the right you can login (icon with arrow and door). If you click on this login button there opens a bootstrap modal. Here we have same problem which a wrote above:
![bestlance modalbug](https://cloud.githubusercontent.com/assets/27823744/25267408/efdf6f06-2674-11e7-891d-4e00711305a9.png)

I search very well on internet and github bootstrap issues but I found nothing about this problem. Our developers have still yet no solution for this problem. Our problem is that our customer want to fix this apperance bug, it is for him high prior and we try to debug this issue already some days and no solution. 

Have you some advice to fix this problem?

- Bug is only shown with the requirements which a mention above. 
- On Firefox, Chrome there is no bug. No matter which zoom I have setting in Windows 10. 
- If the zoom is setting to 100% (or 125%) there is no problem. Even under Microsoft Edge it works.

Thank you for all. 
I hope so much to get an answer with a solution - that would be awesome. 

best regards, 
Jack

**Comment by FezVrasta** [comment]
Looks like a specific rendering bug of Edge... You should report it to [Microsoft Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/)

**Comment by twofourjack** [comment]
ok thanks for your information and your time. 
I find same issue in Microsoft Ege issue tracker: 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4540401/

Maybe you can close this ticket, because it seems that it is a Edge bug.

**Comment by Johann-S** [comment]
Moreover BS do not support Browser zooming see : http://getbootstrap.com/getting-started/#support-browser-zooming

**Comment by patrickhlauke** [comment]
also note there are a few edge bugs relating to visual artifacts/lines on http://v4-alpha.getbootstrap.com/browser-bugs/

**Comment by dleger** [comment]
I have exactly the same issue (Bootstrap 4.0) with **edge** and **Internet Explorer 11**.

I have 2x15" retina screens (UHD 3940*2160 ). One is my laptop UHD screen, the other is a Cintiq pro 16. I use 250% zoom factor with windows 10.

If I use a FHD resolution (1920x1080) at 125%, the problem disappears immediately. So this is DEFINITIVELY a rendering bug from Microsoft. :/

**Comment by TheCommunistCow** [comment]
FYI for anyone who couldn't find a quick fix for this.

It seems to be fixed by setting:
.modal-content {
    background-clip: border-box;
}

This causes the border to be fairly ugly, so you might want to also do
.modal-content {
    background-clip: border-box;
    border: none;
}

**Comment by dleger** [comment]
Well, this is then a workaround. I will test it, thanks. But The fix should be provided by Microsoft in their browsers. This is clearly a Microsoft bug.

**Comment by sanjayaketan** [comment]
I also face same issue. Is there any way to fix?

**Comment by alabastida** [comment]
We are still facing the same issue son Edge and IE with Bootstrap 3.3

**Comment by dilipkumaarvr** [comment]
still, we also facing the issues on IE browser. If anyone knows the solution please share the link with an example file. Thanks in advance

**Comment by sanjayaketan** [comment]
I have added below class in my CSS file and now working fine for me.
Please try this.

**.modal-content {
background-clip: border-box;
border: none !important;
}**

**Comment by dilipkumaarvr** [comment]
> I have added below class in my CSS file and now working fine for me.
> Please try this.
> 
> **.modal-content { background-clip: border-box; border: none !important; }**
Thanks Sanjayaketan. for now its working fine.

**Comment by xenogew** [comment]
@sanjayaketan @dilipkumaarvr thanks, you guys save my life
