### ISSUE TITLE
Modal flickers when input get focus on iOS

### ISSUE THREAD

**Issue by 4muzar** [twbs/bootstrap#22491]
Bootstrap 4
iOS 10.2
Chrome 57, Safari 
iPhone 5

This bug is similar to #17324, but consistently reproduces on iOS at every browser.
You can reproduce it on official bootstrap 4 docs page: https://v4-alpha.getbootstrap.com/components/modal/#varying-modal-content

![modal_ios_medium](https://cloud.githubusercontent.com/assets/3948879/25282330/d5f95e64-26b8-11e7-9165-7d0e98f5e283.gif)

Possible fix: set modal `position: fixed`, but in this case window scroll up to start of page when modal shown.

**Comment by andrey-lizunov** [comment]
Confirm. Have same issue on my website.
Maybe any one know some fix? I don't find it yet.

**Comment by jhack32** [comment]
@andrey-lizunov Try adding position: fixed to body.modal-open.

body.modal-open {
  position: fixed;
}

**Comment by ysds** [comment]
Closing this since we can't do anything.
