### ISSUE TITLE
Hidden class mediaqueries not working anymore

### ISSUE THREAD

**Issue by rickerd** [twbs/bootstrap#22492]
Since i updated BS4-dev the classes hidden-*-down are not working anymore..
Is there something updated? I can't seem to find it in the generated css as well.

It still works with commit 65ffb1c

**Comment by pat270** [comment]
Looks like they got removed at https://github.com/twbs/bootstrap/commit/4778190d78faab6d19486292e2e73cc418c663f3

**Comment by mdo** [comment]
Yes, these were removed for our display utilities.

**Comment by rickerd** [comment]
Why and what else to use? Are they coming back?
I cant hide certain elements when i'm downscaling from screen/device.

**Comment by pkozlowski-opensource** [comment]
@rickerd check https://github.com/twbs/bootstrap/pull/22113#issue-211802976

**Comment by rickerd** [comment]
Okay thanks.

**Comment by rickerd** [comment]
Just checkin, but if i want an element to be hidden on every screensize except mobile should i use;
`<div class="d-sm-none d-md-none d-lg-none"></div>`

Before i could use one class so my element was hidden on all screen sizes except sm or md.
I thought it was pretty powerfull @mdo

**Comment by mdo** [comment]
All our responsive classes like this build on one another—part of the whole mobile first appeal. If you use `.d-none` to always hide something, it applies to all viewports from xs to xl and beyond. If you want the smallest xs tier visible and the rest hidden, use `.d-sm-none`—it'll automatically hide on md and lg and xl.

**Comment by stefan505** [comment]
@mdo, I struggle to understand why the hidden-* classes got removed. I was a responsive ninja with it! I know that for some it was confusing and you had your dedup reasons, but for me it made perfect sense and the docs where clear. 

Also, docs 404 in beta: https://getbootstrap.com/docs/4.0/layout/responsive-utilities/

**Comment by Luc45** [comment]
Yes, and they are still on the docs:
https://getbootstrap.com/docs/3.3/css/#responsive-utilities
