### ISSUE TITLE
navbar with container layout breaks at smallest breakpoint

### ISSUE THREAD

**Issue by tanichols** [twbs/bootstrap#22498]
Reproduce the issue:

1. Visit the navbar example page here: https://v4-alpha.getbootstrap.com/examples/navbars/
2. Shrink the page, and watch the 2nd example (container)
3. After shrinking the page to past the smallest breakpoint, observe the overlap of the navbar-brand element and the toggle element. 

I'm not familiar with bootstrap enough to know where this fix needs to be applied, but should be a simple fix of pulling the brand left and the toggle right at the smallest breakpoint if nested in a container.

**Comment by Devtronic** [comment]
Verified in Google Chrome 57.0.2987.133 (64-bit) macOS 
![image](https://cloud.githubusercontent.com/assets/2362734/25311216/d6a1ad10-27fa-11e7-975b-bd529d20708e.png)

**Comment by FelixRilling** [comment]
I compiled and tested this with the current code of the repo, the navbar in question is fine on the smallest breakpoint there:

![image](https://cloud.githubusercontent.com/assets/3207763/25316639/3bbce37a-286b-11e7-8de6-17ae829a9ab6.png)

**Comment by rafalp** [comment]
Please use search before reporting the issues, this comes up a lot: #21590

**Comment by mdo** [comment]
Closing per @rafalp's comment. And yes, please search next time :).
