### ISSUE TITLE
Tooltip not show style

### ISSUE THREAD

**Issue by limjoonae** [twbs/bootstrap#22505]
Hello, i have problem about tooltip. It's not show style follow the example
![image](https://cloud.githubusercontent.com/assets/3191903/25324473/3ddbe59a-28f0-11e7-93a3-51656f6b08b0.png)

This is my html code
<input type="text" class="form-control" data-toggle="tooltip" data-placement="top" title="Tooltip on top"/>

When i find _**data-toggle="tooltip"**_  in boostrap.min.js. It's not found. Is it possible to be a reason?

Pls help me
Thank.

**Comment by patrickhlauke** [comment]
for help/how-to questions, please use stackoverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
