### ISSUE TITLE
Website/docs v3 & v4 redirects

### ISSUE THREAD

**Issue by tomByrer** [twbs/bootstrap#22502]
I'm already seeing v4 in the wild both in template stores & GitHub repos for components.  & I imagine when v4 is finally released, v3 will be in use for years afterwards.  Could there be a permanent redirect from say `https://getbootstrap.com/3/` to where ever the final v3 route will end up being please?  (Same for v2 & v4.)  Will help reduce confusion, especially during the 6-12 months of transition.

**Comment by mdo** [comment]
We'll have a new url for the v3 docs, yes. It'll probably be something like `getbootstrap.com/v3/` and that'll house the latest version of v3 at all times. We already host previous versions at `getbootstrap.com/v{major}.{minor}.{patch}/`.

**Comment by tomByrer** [comment]
Great, thanks @mdo !
I'm hoping sooner than later; I'm already cringing at adding link rot to other repos...
