### ISSUE TITLE
Unexpected behavior in navbar if navbar-brand is removed. 

### ISSUE THREAD

**Issue by tanichols** [twbs/bootstrap#22508]
When using a navbar and removing the navbar-brand element, the navbar resizes inappropriately at medium and lower breakpoints. 

This does not appear to affect centered navs, regardless of container placement. 

**System**
```
OS:      macOS 10.10.5
Browser: Chrome 58
```

**Steps to reproduce error**
- add a navbar to test page
- test breakpoints with navbar-brand element in-place
- remove navbar-brand element
- test breakpoints with navbar-brand element removed

**Screenshots of issue**
5 navs with navbar-brand, before md-breakpoint:

<img width="1005" alt="screen shot 2017-04-24 at 8 34 31 am" src="https://cloud.githubusercontent.com/assets/5770965/25345106/f6542ff6-28c8-11e7-9d9b-033afae9f5f5.png">

5 navs with navbar-brand, after md-breakpoint:

<img width="964" alt="screen shot 2017-04-24 at 8 28 07 am" src="https://cloud.githubusercontent.com/assets/5770965/25345136/121f574c-28c9-11e7-90cf-afd3c6bc02db.png">

5 navs without navbar-brand, before md-breakpoint:

<img width="1114" alt="screen shot 2017-04-24 at 8 30 32 am" src="https://cloud.githubusercontent.com/assets/5770965/25344922/6a4d0b4a-28c8-11e7-8346-617b0e1f6a96.png">

5 navs without navbar-brand, after md-breakpoint:

<img width="962" alt="screen shot 2017-04-24 at 8 29 10 am" src="https://cloud.githubusercontent.com/assets/5770965/25345151/20cbbda8-28c9-11e7-98e6-a228e1859433.png">

**Comment by JayteeNZ** [comment]
I believe this issue was fixed via this PR [#22230](https://github.com/twbs/bootstrap/pull/22230)

This will likely be available in the first Beta however you can download the master branch.

**Comment by JayteeNZ** [comment]
No worries. I actually create a npm package with the latest dev version. I'm actually not sure if it's allowed, but you can pull it here: 

[Latest version (2 weeks ago)](https://www.npmjs.com/package/bootstrap-v4-master)

**Comment by tanichols** [comment]
Using the jsfiddle by @mdo here: (https://jsbin.com/rikevuj/1/edit?output) I confirmed that this is corrected by removing the brand from the various navbars and testing.
