### ISSUE TITLE
相对当前元素定位目标元素

### ISSUE THREAD

**Issue by xp44mm** [twbs/bootstrap#22501]
When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
在BOOTSTRAP中许多操作元素和被操作元素相对固定，比如：collapse，操作collapse内容的按钮和被操作的collapse元素往往就是按钮的下一个兄弟元素。而现在，定位被操作元素往往使用jQuery Selector字符串。主要使用绝对定位，常常是用id选择器。这就常常要求手工编写id选择器。
另外，一些选项，如collapse.parent只允许设置selector字符串，而不允许设置为element，实际上，我查看了源代码，使用的是$(options._parent)，jquery的参数可不是仅限于字符串。
相对当前元素定位目标元素，是一个很符合逻辑、并且易于实现的技术。盼望能够尽快加上。

- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by patrickhlauke** [comment]
from what I can gather with google translate, this sounds like a request for help with a specific implementation/use of bootstrap. i'd suggest trying stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by xp44mm** [comment]
_getParent() {
      const parent   = $(this._config.parent)[0]
      const selector =
        `[data-toggle="collapse"][data-parent="${this._config.parent}"]`

      $(parent).find(selector).each((i, element) => {
        this._addAriaAndCollapsedClass(
          Collapse._getTargetFromElement(element),
          [element]
        )
      })

      return parent
    }
the code of [data-parent="${this._config.parent}"] restrict the type of this._config.parent to string, but it is element or string is better than only string.

**Comment by patrickhlauke** [comment]
as `data-parent` would be an attribute coming from the HTML markup, it can't really be an element though

**Comment by xp44mm** [comment]
you are right, it is the problem. i look at some code, which is applied bs. there is a resolution that use guid() at target element, it is a little overweight.my resolution just need change
$(parent).find(selector)
as
$(parent).children(`[data-toggle="collapse"]`)
