### ISSUE TITLE
[Suggestion] Add CSS to documentation #docs #suggestion

### ISSUE THREAD

**Issue by mesqueeb** [twbs/bootstrap#22514]
I believe it would be extremely useful if every component in the documents shows on the right side or through a link the actual CSS that's being applied.

**Comment by oktalk** [comment]
@mesqueeb Could you add some clarification to your statement? I agree that the docs are a bit cumbersome, but it's unclear as to what your issue and solution is.

**Comment by mdo** [comment]
Wants all the links in the sidebar always expanded. Perhaps. I'm working on some new docs designs for the beta and stuff, but not 100% settled yet.

**Comment by patrickhlauke** [comment]
The way I understood this request was to have a link/control next to each live example of a component that shows the exact CSS that applies to it (so it would show all the classes and rules that give the component its appearance). Which I think would be a bit overkill and not that useful...
