### ISSUE TITLE
card-columns with cards same heights. card-deck will not work

### ISSUE THREAD

**Issue by Sun3** [twbs/bootstrap#22512]
Is there a way to have card-columns have the cards with same heights? Like card-deck does but I need the cards stacked vertically for when on a small device the will collapse to one row ordered correctly.

Medium to Desktop Devices
----------------------------
```
card1    card4     card7
card2    card5     card8
card3    card6     card9
```

Small Devices
--------------
```
card1
card2
card3
card4
card5
card6
card7
card8
```

 
Thanks.

**Comment by mdo** [comment]
You'll want to use the grid for this instead of a card deck or group. Or, do some `flex-wrap` on the card deck if you can. Should be a handful of options out there.
