### ISSUE TITLE
Bootstrap 4 "container" looks smaller on Firefox compared to Chrome

### ISSUE THREAD

**Issue by Rajan** [twbs/bootstrap#22515]
I'm on the latest version of Chrome (57.0.2987.133 (64-bit)) and Firefox (Version 53.0) on Macbook with Sierra (10.12.3 (16D32)). The size of "container" element seems much smaller on Firefox than on Chrome and my site looks odd on Firefox because of the same. 

I tried using container-fluid and container-fixed but it makes it look too broad. Ideally, Bootstrap should offer same experience for the same code on both Firefox and Chrome.

**Comment by Rajan** [comment]
Attaching screenshots for both Chrome and Firefox.
<img width="1440" alt="screen shot 2017-04-25 at 6 46 21 am" src="https://cloud.githubusercontent.com/assets/60307/25364887/15876bb2-2983-11e7-9e6a-ae34503db350.png">

<img width="1440" alt="screen shot 2017-04-25 at 6 46 21 am" src="https://cloud.githubusercontent.com/assets/60307/25364895/231f1d1a-2983-11e7-8b24-21373d241215.png">

**Comment by Rajan** [comment]
I also checked out Bootstrap starter template and things do look smallish on Firefox.
https://v4-alpha.getbootstrap.com/examples/starter-template/

**Comment by JayteeNZ** [comment]
I can see a class of `.container` that has a max-width of 60rem. Based on the display of the fonts etc, it looks like the default font size in Firefox is smaller than Chrome, hence possibly reflecting on the container since it uses rem

**Comment by Rajan** [comment]
I changed the font-size and it looks good but most people won't do the same. There must be a way to handle this differently like a multiplier for font-size if the browser is Firefox.

**Comment by oktalk** [comment]
@Rajan I wasn't able to reproduce your example when using the Bootstrap examples: https://v4-alpha.getbootstrap.com/examples/navbars/

It looks like your CSS file `theme.min.css` is causing the issue.

**Comment by Rajan** [comment]
@oktalk the issue goes away when one increases font-size in Firefox. You may not be able to reproduce the issue if you're no longer using default font-size on Firefox which is smaller than default font-size in Chrome. Kindly reset the font-size in Firefox and you might be able to reproduce.

**Comment by patrickhlauke** [comment]
cannot reproduce with default settings (which is what most users would see). could it be that you had your firefox set to a custom font size at first?

<img width="1280" alt="screen shot 2017-04-25 at 18 40 48" src="https://cloud.githubusercontent.com/assets/895831/25399306/ef093344-29e6-11e7-851e-a4fc15e37bcf.png">

**Comment by Rajan** [comment]
Highly unlikely as default font-size is 16px and I did increase to fix the issues but most users will not increase their font sizes and we will end up killing Firefox in the process as most sites would be adopted to Bootstrap 4 in a year or so. Kindly check the default font size which comes at 16px.
https://superuser.com/questions/974268/firefox-restore-all-default-font-settings

**Comment by patrickhlauke** [comment]
My font size *is* set to default/16px. And the above is how it's rendered. This is a completely fresh install with a clean profile, with no modifications to settings nor about:config.

**Comment by Rajan** [comment]
@patrickhlauke Let me try to understand what is the default font-size on chrome. I was using large font-size on chrome. That could be a reason why It might've been looking different on two browsers instead of medium (which might be 16px on chrome). Thanks for all your help and time. Closing this.
