### ISSUE TITLE
Link inside page doesn't go to the same location if accessed directly

### ISSUE THREAD

**Issue by gravsten** [twbs/bootstrap#22524]
Operating system: Windows 8.1
Browser: Chrome 57, Firefox 52, IE 11

Test case:
1. Open the following URL: http://bootstrap4.guide/
2. Click on the menu item "Breakpoints"
3. In a different browser window/tab, open the following URL: http://bootstrap4.guide/#three

The page at step 2. shows all the contents of `#three` (correctly taking into account the menu height).
The page at step 3. sees the top of the contents of `#three` hidden behind the menu.

In another example (https://pilierpublic.com/fr/help#install), the first question pointed to by this URL is hidden behind the menu.

As a result, one cannot give (e.g. by email) a URL with anchor inside a page unless this points to an element with enough padding so that it not be hidden behind the menu.

**Comment by patrickhlauke** [comment]
Those examples/templates are not official Bootstrap ones, so nothing to do with us. Suggest finding out who maintains them and contacting them.
