### ISSUE TITLE
Carousel does not upscale images on very large screens

### ISSUE THREAD

**Issue by ralfEdmund** [twbs/bootstrap#22521]
The Carousel does not the images if the screen size exceeds the images size as available on the recent iMacs. 

The images I've used have a maximum size of 4000 by 3000 pixels. The carousel is part of section covering the whole width of the browser viewport. 

If the browser is switched to full screen mode, the carousels display arearesizes accordingly while the images are to stretched to cover the whole area. Therefore parts of the background are visible.

**Comment by mdo** [comment]
Explicitly set the width as `100%` or use `.w-100` and you should be okay. We won't be adding this behavior by default though, not now at least.
