### ISSUE TITLE
Search style does not work when bootstrap is loaded. Any alternatives to simulate?

### ISSUE THREAD

**Issue by wyattbiker** [twbs/bootstrap#22525]
```<input type="search">``` does not style with an X under bootstrap v3.3.7 or prior. Looking for alternative solutions but removing bootstrap is not an option. Thanks

**Comment by patrickhlauke** [comment]
bootstrap 3.x is in maintenance mode while we focus on 4.x. for how-to questions, I'd suggest StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
