### ISSUE TITLE
Buttons resized responsively in Bootstrap 4

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#22520]
It would be amazing to have buttons resized responsively in our Bootstrap 4 websites.

Something like this:

http://stackoverflow.com/a/19937581/4412054

I do not think it's possible today, right? Why? Is it a desired choice?

**Comment by mdo** [comment]
Buttons are sized in `rem`s, so things will automatically scale based on the root font-size. Should provide enough flexibility. No plans for anything else.
