### ISSUE TITLE
Official Bootstrap example "Fixed Navbar" sees anchor hidden behind menu

### ISSUE THREAD

**Issue by gravsten** [twbs/bootstrap#22531]
Operating system: Windows 8.1
Browser: Chrome 57, Firefox 52, IE 11

Test case:
1. - Open the following URL: https://pilierpublic.com/tmp/
2. - Click on the menu item "Home"
3. - Alternatively, open directly the URL: https://pilierpublic.com/tmp/#block2
4. - See that in either case the top of the contents of `#block2` is hidden behind the menu

A workaround is to link to an element with sufficient padding-top (i.e. at least the height of the navbar), which isn't satisfactory for many use cases.

**Comment by modusinternet** [comment]
Correct title, Bootstrap not Boostrap.

**Comment by hd719** [comment]
Hello can I work on this?

**Comment by mdo** [comment]
Yeah, this has always been the case with `position: fixed` and now `sticky` as well. Only way around it is CSS hacks or custom JS, none of which we'll be getting ourselves into as they both kinda suck.

**Comment by sebastiangaertner** [comment]
So no satisfying solution for this?
