### ISSUE TITLE
Sizes for form-horizontal's .control-label on min-width < 768px does not work as expected for .control-label but work for .form-control (visible with with .col-xs-*)

### ISSUE THREAD

**Issue by radek-anuszewski** [twbs/bootstrap#22537]
Hi! I found that on small devices (min-width < 768 px) sizes for `.form-horizontal` does not change `.control-label` font-size. To reproduce this behavior, [check this JSBin](https://jsbin.com/zofenaxeni/edit?html,css,output). It is not striking in [your documentation about sizes](http://getbootstrap.com/css/#forms-control-sizes), because on small devices it become 100% width with `col-sm-* classes`. but in JSBin which I provided it may confuse people a little bit. Fragment of Bootstrap's code:

```
@media (min-width: 768px) 
.form-horizontal .form-group-lg .control-label {
    padding-top: 11px;
    font-size: 18px;
}
```
I think it intentionally behaves in this way, but it can be confusing when using `col-xs-*` different than `col-xs-12` for `.form-horizontal` layout. Changing it may cause breaking change problems, but maybe it needs clarification in documentation?

Thank you in advice for taking the time to my issue.
Greetings,
Radek.

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
