### ISSUE TITLE
Let's avoid from jQuery dependency

### ISSUE THREAD

**Issue by greybax** [twbs/bootstrap#22540]
Guys, now is 2017 year! And bootstrap still has [dependency on jquery](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L70). I'm sure that we can avoid this dependency and do not load jquery. So f.e the latest version of jquery on today is:

* v3.2.1 - [jquery.min.js](https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js) is 84.6KB. 

And I wouldn't to install in my project extra data which will affect on  page load of my app.

Let's think about it. If you agree with that I'd like to help with it. Thanks Guys!

**Comment by Johann-S** [comment]
Thank you for your feedbacks we will think about it for the next major release (V5) of Bootstrap 👍

**Comment by greybax** [comment]
seems this day will not happened.... 😞

**Comment by Johann-S** [comment]
It's a huge change plus V4 beta will be released soon so we cannot put all the efforts to rewrite Bootstrap entirely because we have to stabilise V4

**Comment by greybax** [comment]
it's ok, but I thought you will not close the task..

**Comment by Johann-S** [comment]
It's a duplicate of #22194 but we will thought about that on our next major release for sure 👍
