### ISSUE TITLE
[feature-request] btn-group with two responsive variations

### ISSUE THREAD

**Issue by robgha01** [twbs/bootstrap#22545]
We need a way to make .btn in a .btn-group's behave better what i suggest is adding a new css class addable at the .btn-group level where we can chose ether "wrap" or "ellipse" that may be named ex:
".btn-group-wrap" ".btn-group-ellipse" or anything else that describe them better.

We can then have the following css rules for each of them

**Wrap**
```
white-space: pre-wrap;
overflow: hidden;
```
![boot](https://cloud.githubusercontent.com/assets/362726/25555992/67d8b5aa-2cf4-11e7-816e-353ddc34bd53.PNG)

**Ellipse**
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```
![boot2](https://cloud.githubusercontent.com/assets/362726/25556004/bfd131f6-2cf4-11e7-98d3-9f102978c694.PNG)

**Comment by mdo** [comment]
No plans to add this to the button group—there is an issue open for a truncate mixin, though! We'll tackle that in a minor bump sometime after v4 launches.

**Comment by robgha01** [comment]
@mdo No plans... a truncate mixin would not behave if you want to show all of the content closing it just to say that it is not a part of the plan is unprofessional as this is clearly someting trivial to implament and someting that we all can have good use for. i just cant get my finger around your statement...

**Comment by mdo** [comment]
Just to be clear, it's definitely not unprofessional to say no to things :). I don't add everything that is asked of me to Bootstrap. A truncate mixin and class, if added at a later date, would help you out for one of these requests, and the other can be done via custom styles.
