### ISSUE TITLE
[v4-alpha] Can't find documentation about .mr-*

### ISSUE THREAD

**Issue by ahmetb** [twbs/bootstrap#22553]
I'm looking for a page that explains the `.mr-*` class in  https://v4-alpha.getbootstrap.com/, so far no luck.

https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fv4-alpha.getbootstrap.com%2F+%22mr-auto%22&oq=site%3Ahttps%3A%2F%2Fv4-alpha.getbootstrap.com%2F+%22mr-auto%22&aqs=chrome..69i57j69i58.2942j0j4&sourceid=chrome&ie=UTF-8#q=site:https://v4-alpha.getbootstrap.com/+%22mr%22

**Comment by rafalp** [comment]
https://v4-alpha.getbootstrap.com/utilities/spacing/
