### ISSUE TITLE
Collapse - collapses automatically after opening, ( bootstrap.min.js)

### ISSUE THREAD

**Issue by noaud** [twbs/bootstrap#22569]
When clicking on a collapsed item, the item opens but is visible for < 1 second before collapsing automatically. Seems to be a problem with the .min.js version where

`<div class="collapse active" id="xxx"` 
instead of:
`<div class="collapse in" id="xxx"`

Does work:
https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js 
Does not work:
https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.min.js 

Using example from https://v4-alpha.getbootstrap.com/components/collapse/:

Html from browser running in develop mode (boostrap.js), which is OK:

```
<p>
  <a aria-controls="collapseExample" aria-expanded="true" class="btn btn-primary" data-toggle="collapse" href="#collapseExample">
    Link with href
  </a>
  <button aria-controls="collapseExample" aria-expanded="true" class="btn btn-primary" data-target="#collapseExample" data-toggle="collapse" type="button">
    Button with data-target
  </button>
</p>
<div class="collapse in" id="collapseExample" aria-expanded="true">
  <div class="card card-block">
    Anim pariatur cliche reprehenderit... 
  </div>
</div>
``` 
Html from browser running the bostrap.min.js version, which is auto collapsing: 
```
...
<div class="collapse active" id="collapseExample" aria-expanded="true">
  <div class="card card-block">
    Anim pariatur cliche reprehenderit...
  </div>
</div>
```

Tested in browsers:
- Chrome Version 57.0.2987.133 (64-bit)
- Firefox Version 52.0.2

Os: Mac OS X

**Comment by patrickhlauke** [comment]
I think in general you shouldn't rely on the `/dist/` versions in the branch to contain all the fixes etc done in the branch, since they're not consistently rebuilt (to my knowledge anyway) when PRs/changes get merged. Safest always to grab the latest state of the branch and build your own.

**Comment by Johann-S** [comment]
Totally agree with @patrickhlauke and you should add a CodePen or JSBin to demonstrate your issue thank you

**Comment by Swapnil2127** [comment]
Thank you, I am also facing the same issue, then I got this and it is resolved.
Thanks a lot
