### ISSUE TITLE
row class not having margin-bottom or margin-top which cause the adjacent row to stick?

### ISSUE THREAD

**Issue by sahilweb6** [twbs/bootstrap#22567]
I am using bootstrap 4 and when I am using 2 rows they just stick together without any space. I can write custom css here or use helper utility class to fix this. But why you have dropped the margin between rows in v4? or is there anything I am missing?
here is my example code -https://jsfiddle.net/aq3o7j46/

**Comment by oktalk** [comment]
Rows have never had a bottom margin. Your components typically have the bottom spacing instead.

**Comment by mdo** [comment]
Yup, rows have never had vertical margins.
