### ISSUE TITLE
Dropdown-item  link vs dropdown item button styling different

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#22560]
In V4 alpha 6, dropdown-items that are `<a href="#">` are styled differently (bolded) than dropdown-items that are `<button>` elements. (at least in webkit/chrome)

When a drop down consists only of one type (`a` or `button`) the styling is OK, but if you mix `a` and `button` in the same dropdown the result is different styles (bold, not bold):

See examples on:
http://v4-alpha.getbootstrap.com/components/dropdowns/

example with `a` (links) only:
![image](https://cloud.githubusercontent.com/assets/2781561/25646392/5528271e-2f8e-11e7-8b6d-b340e4f4fa5f.png)

example with `button`s only:
![image](https://cloud.githubusercontent.com/assets/2781561/25646412/7544a752-2f8e-11e7-96fc-463ae882f9d5.png)

Example with both `a` links and `button`s:
![image](https://cloud.githubusercontent.com/assets/2781561/25646437/c333a33c-2f8e-11e7-8cb5-4186d018255d.png)
 
I believe it has to do with the inheritance from the body font-family on `a.dropdown-item` vs. `button.dropdown-item`

**Comment by mdo** [comment]
Yes, this is solved in the `v4-dev` branch. Was a result of Normalize.css changing how they apply text styles to various elements. Next release will resolve it.
