### ISSUE TITLE
Change jQuery slim to full version on Get Started docs

### ISSUE THREAD

**Issue by JacobLett** [twbs/bootstrap#22568]
https://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start

I think a lot of beginners will grab the code snippet and later on add some jQuery scripts that don't work because they have the slim version. This could cause some frustration on not knowing why. Maybe have an HTML comment that states a slim version can be used to decrease the footprint if no custom scripts are being used.

**Comment by mdo** [comment]
There is copy in the docs right above the code snippets for their includes that mentions a full build of jQuery is supported. We only require the slim version, but the full one works great, at a minimum. Perhaps we can make that clearer, but we're sticking with the slim build as the default.
