### ISSUE TITLE
Tooltips arrow breakaway

### ISSUE THREAD

**Issue by huang-x-h** [twbs/bootstrap#22572]
Hi

Browser：**Chrome 56.0.2924.87 / IE 10.0.9200.16384 / Firefox 53.0**

View http://getbootstrap.com/javascript/#tooltips, the tooltips arrow breakaway

![f4 0 t k7 6g7waby 2 3mf](https://cloud.githubusercontent.com/assets/381860/25737013/03169f34-31a8-11e7-8d44-9acc7030a48a.png)

But Chrome 57 / IE 11 it's ok.

**Comment by Johann-S** [comment]
Tested on Win10 Firefox 53 not able to reproduced your issue.
FYI we don't support browser zooming see : http://getbootstrap.com/getting-started/#support-browser-zooming

**Comment by huang-x-h** [comment]
We do not zoom the browser, it's default 100%, and we test on Win7 and Win8.1

**Comment by oktalk** [comment]
I can't duplicate this either. Tested in all mentioned browsers and OS's.

**Comment by jipexu** [comment]
the given example is BS 3 ??

..."View http://getbootstrap.com/javascript/#tooltips, the tooltips arrow breakaway" ...

it's labelled V4 ?

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by huang-x-h** [comment]
Sorry for reply late

We test v4 version also have the same problem

https://v4-alpha.getbootstrap.com/components/tooltips/

```
OS: Windows8  6.2.9200 N/A Build 9200
Browser: Chrome 56.0.2924.87
```

**Comment by jipexu** [comment]
seems to happens only with your config ?
OS: Windows8  6.2.9200 N/A Build 9200
Browser: Chrome 56.0.2924.87

i have not this on 
Chrome Version 58.0.3029.96 (64-bit)
Safari
FF
macOS sierra 10.12.4

**Comment by huang-x-h** [comment]
@jipexu chrome 58 we test it's ok, but not on chrome 56, and also on `IE10 / FF54`

**Comment by dillix** [comment]
I also have this issue with tooltips on Chrome 56 (mac) & ElectronJS (build on Chromium 56)

**Comment by jipexu** [comment]
so seems chrome 56 "bug" on both mac/win ?

**Comment by dillix** [comment]
@jipexu, yes I tested on 56 win & 56 mac. Both versions have it.

**Comment by Johann-S** [comment]
With this PR : #22681 arrow positionning will be managed by Popper.js

**Comment by feng-xiao** [comment]
@Johann-S , have the arrow issue fixed for Chrome 58? See the screenshot below, I have this issue only on Chrome (58). it's working for IE 11, Edge (latest), and Firefox 

![image](https://cloud.githubusercontent.com/assets/3407775/26634380/799be4b6-45e4-11e7-935c-3aa9f6a16944.png)

**Comment by Johann-S** [comment]
Where can I reproduce this @feng-xiao ?

**Comment by feng-xiao** [comment]
@Johann-S [https://codepen.io/anon/pen/rwNepE](https://codepen.io/anon/pen/rwNepE)

**Comment by feng-xiao** [comment]
@Johann-S After I updated bootstrap css and js got from the latest dist from v4dev branch, it works on Chrome at 100% zoom, it doesn't work well for zoom mode 

Codepen: [https://codepen.io/anon/pen/ZyEWRN](https://codepen.io/anon/pen/ZyEWRN)

Edge: 
![image](https://cloud.githubusercontent.com/assets/3407775/26743174/e0ab53d2-47ae-11e7-9111-da6544bef736.png)

Chrome 58:
![image](https://cloud.githubusercontent.com/assets/3407775/26743226/177c4560-47af-11e7-8be0-5c0e31adf3ce.png)

IE 11
![image](https://cloud.githubusercontent.com/assets/3407775/26743277/334fe7f6-47af-11e7-9791-41825d12d59e.png)

**Comment by Johann-S** [comment]
FYI Bootstrap don't support browser zooming.
So this issue will stay closed. Thank you for your feedbacks @feng-xiao 👍
