### ISSUE TITLE
Nav Tabs example not working in documentation

### ISSUE THREAD

**Issue by nosoycesaros** [twbs/bootstrap#22578]
When you navigate to https://v4-alpha.getbootstrap.com/components/navs/#tabs the example for tabs is not changing between tabs when clicked, and this doesn't report any errors in the console.

When downloaded a local copy of Bootstrap and test the nav tabs, it didn't work either.

- OS: Mac OS X 10.10
- Browser: Chrome 57, Safari 8

**Comment by jipexu** [comment]
no error in the console is right as all the tab link are # .. perhaps probably planned like this just to show the code ?....?

**Comment by patrickhlauke** [comment]
exactly. it's just illustrating the look of tabs, it's not an actual working set of tab panels.
