### ISSUE TITLE
Stray tooltip is appearing on top of body when the containing element is removed

### ISSUE THREAD

**Issue by Sahas** [twbs/bootstrap#22585]
This issue produced in Mac Chrome(58.0.3) &Firefox.

As the image shows, this stray tooltip is appearing on top of viewport.
![screen shot 2017-05-09 at 12 24 21 am](https://cloud.githubusercontent.com/assets/1641300/25820156/f4c43cfe-344d-11e7-90e7-6567b64a9531.png)

I have a link which shows this tooltip. This happens when I click the link. The behaviour of the link is it removes the row at current position and moves to some other position. 

In dev tools, I observed the following changes made to the page (I didn't add these elements in the HTML).
![screen shot 2017-05-09 at 12 27 27 am](https://cloud.githubusercontent.com/assets/1641300/25820436/da10c688-344e-11e7-97e7-1f1b596fdee1.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Sahas** [comment]
Able to partially reproduce this. 

https://codepen.io/sahas/pen/pPpdYv

Steps:
1. Hover over heart icon to get the tooltip 2. Click the heart to remove it 

The tooltip for the removed element doesn't disappear. It still remains on the page.

**Comment by Sahas** [comment]
Closing issue as I found this is an issue with jquery

**Comment by Sahas** [comment]
I find there is an issue with tether. Reopening the issue.

**Comment by Johann-S** [comment]
I'll close this as a WontFix since we can't reasonably detect when the original element is removed from the DOM. Please consider the state of tooltips/popover before just flat out removing elements.

Related to : #21490
