### ISSUE TITLE
How can component popover support not html tag

### ISSUE THREAD

**Issue by hudalong** [twbs/bootstrap#22586]
In my project, I used the velocity template and bootstrap framework for my admin management system, the code just like this:
![image](https://cloud.githubusercontent.com/assets/9346269/25833885/ff5d3a2c-34a6-11e7-846c-d253306419b1.png)
In this picture, when I changed the script tag to div , the popover component works, so I wander if the popover component can support not html tag!

**Comment by anovsiradj** [comment]
it's because javascript cannot execute/scan html-code inside script-tag.
you need to initialize them by yourself, eg: `$(selector).popover();` after handlebar.js (?) parse complete.

**Comment by Johann-S** [comment]
Closed thanks to the comment of @anovsiradj
