### ISSUE TITLE
Bower Install Bootstrap 4 missing dist js file

### ISSUE THREAD

**Issue by alaksandarjesus** [twbs/bootstrap#22587]
Installing bootstrap v4 with bower the js file in dist folder is missing. Attaching the snapshot.

![bower bootstra4](https://cloud.githubusercontent.com/assets/4712552/25836822/97100d9a-34a7-11e7-9657-402a8498a66f.PNG)

**Comment by mdo** [comment]
Bower doesn't include dist files—only source.
