### ISSUE TITLE
Card-subtitle causes jitter on collapse

### ISSUE THREAD

**Issue by RobertDiebels** [twbs/bootstrap#22596]
**Problem**
The `card-subtitle` class combined with `collapse` functionality is shows a slight jitter when collapsing the collapsible area.

**Cause**
There is a `margin-top: 0.375rem;` on the `card-subtitle` class which is causing the jitter.

**Solution**
When I removed the `margin-top` there was no jitter and everything on my end kept functioning.

**Test-case**
Reproduced test cases and solution: [here](http://www.bootply.com/Gr0e2jUqNY)

**Versioning**
- Bootstrap: 4.0.0-alpha.6
- Operating system and version: Windows 10
- Browser and version: Chrome 57.0.2987.133

**Comment by mdo** [comment]
Collapse must be used on containers—the element cannot have padding or margin without causing you issues in how the height is calculated. No way around this on our end I'm afraid. Put the collapse on the parent instead of the subtitle.

**Comment by RobertDiebels** [comment]
@mdo That's fine and thanks for answering. Just to be clear for potential future readers I solved the problem by adding a `mt-0` to the element I tried to collapse.

I do have one request. The documentation wasn't very specific on what the requirements for elements were. If I may request a change in the documentation to clarify which requirements an element should fulfill that would be great.
