### ISSUE TITLE
Tabs should work without required ul and li Nav classes

### ISSUE THREAD

**Issue by mmplisskin** [twbs/bootstrap#22597]
This Works: 
```        
<ul class="" role="tablist">
  <li class="nav-item ">
    <a class="nav-link active" data-toggle="tab" href="#home">Home</a>
    <a class="nav-link" data-toggle="tab" href="#profile">Profile</a>
  </li>
</ul>

        <div class="tab-content">
            <div class="tab-pane active" id="home" role="tabpanel">H..</div>
            <div class="tab-pane" id="profile" role="tabpanel">P..</div>
          </div>
```
This Markup does not open tab
Click profile -> Click home -> Click profile and tab panel does not open
```  
<ul class="" role="tablist">
    <li class="">
      <a class=" active" data-toggle="tab" href="#home" role="tab">Home</a>
      <a class="" data-toggle="tab" href="#profile">Profile</a>
    </li>
</ul>

Tab content same as above

```

I think it would be really great if nav-item and nav-link classes were not required as they are semantic to a nav and Tabs have many other use cases.  Interested in thoughts on this.

edit: version 4.0.0.alpha6

**Comment by Johann-S** [comment]
Hi @mmplisskin,

Can you specify the release of Bootstrap you use ? please

**Comment by mmplisskin** [comment]
4.0.0.alpha6

**Comment by esr360** [comment]
Not sure I personally agree - tabs should work on any HTML elements and shouldn't be bound to `<ul>` and `<li>` elements specifically. To me it makes sense to provide any style/functionality through classes and ID's, regardless of the HTML tags used.

**Comment by mmplisskin** [comment]
Sorry if it is confusing what I was suggesting but please reread.

**Comment by MalithHatananchchige** [comment]
Same issue, I'm using bootstrap alpha 6 and tabs need li but even if you have something like

```
                      <li class="nav-item">
                        <a class="btn btn-default btn-cons btn-rounded btn-notification-style m-b-10" href="#" data-target="#simpleAlert" role="tab" data-toggle="tab" data-type="position-simple">Simple Alert</a>
                      </li>
```

Tabs will stop working. Which is strange because in bootstrap v3 everything worked out just fine.

**Comment by Johann-S** [comment]
Tabs aren't bound to `ul` and `li` markups they are other examples in our docs see : https://getbootstrap.com/docs/4.0/components/navs/

for example : 
```html
<nav class="nav">
  <a class="nav-link active" href="#">Active</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link disabled" href="#">Disabled</a>
</nav>
````

The only requirement we have it's the parent should have one of this classes : `.nav` or `.list-group` and the links will have an `.active` class added when they are active that's all

Bootstrap is a CSS/JS Framework so we provide usefull classes and markups 👍 

I hope I helped you, if you have a more precisely issue do not hesitate to open one 👍

**Comment by mmplisskin** [comment]
@Johann-S This is not really what I was getting at, I will try to rephrase: 

Is it possible to isolate tab behavior from nav stylings, it would make sense to me that anything could behave as a tab by adding the required role and data attributes?

**Comment by mattez** [comment]
@Johann-S wrote:
> The only requirement we have it's the parent should have one of this classes : .nav or .list-group ..

IMHO its not mentioned in documentation. Or it is not clear from documentation. See: https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior

I expected something different then `class` `nav` is used in javascript to identify tabs parts, for e.g. `data-` atribute. If you want to make javascript depending on `class` I think it is a good habit to add some prefix to that `class` to mark that javascript is depending on it and one should not remove it. Something like `.js--nav`.
