### ISSUE TITLE
docs: have a "jump to top" icon

### ISSUE THREAD

**Issue by ScotsScripts** [twbs/bootstrap#22604]
I've been using the docs a lot lately and for most part think they work well except for all the manual scrolling back to the top. I'd like to request  a "jump to top" icon to help save time in this activity.

**Comment by edanbarak** [comment]
@Johann-S I was thinking of taking on this issue, but I noticed the docs have a "Back to top" button in the sidebar when scrolling down. Does this solve the issue or should I improve it by changing it to an icon or have it floating?

**Comment by Johann-S** [comment]
I don't see any "back to top" link on our `v4` documentation, see for example : http://v4-alpha.getbootstrap.com/components/alerts/

**Comment by mdo** [comment]
Closing out, no plans for this. I have some design updates in mind for the docs to help.
