### ISSUE TITLE
Tooltip Image has opacity

### ISSUE THREAD

**Issue by congomonster** [twbs/bootstrap#22609]
Hi,

i use the tooltip with an image. But the image is transparent. I can't change that.
`<td class="profile-picture-table" data-toggle="tooltip" data-placement="top" data-html="true" title="' . get_avatar( $userdata->id, 128 ) . '">' . get_avatar( $userdata->id, 32 ) . '</td>`
<img width="595" alt="transparent" src="https://cloud.githubusercontent.com/assets/15074474/26002943/896573c4-3731-11e7-8a5d-488c157f91d7.png">

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by congomonster** [comment]
That's pretty bad for me. I have created codepen but it doesn't work...
https://codepen.io/anon/pen/ybjJJK?editors=1010

**Comment by congomonster** [comment]
Ok solved it. I'm feeling dumb right now. Just placed some css code:
`.tooltip {
    opacity: 1 !important;
}`

**Comment by Johann-S** [comment]
That's something happen don't worry 😉 so I can close this issue 👍
