### ISSUE TITLE
v4: Rounded corner missing when .input-group has label

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#22608]
The css for the rounded corners of .input-group input is build in a way that breaks once you add a label-tag to the form.

Example:
```
<div class="form-group form-group-email input-group">
<label>E-Mail</label>
<input type="text" id="" name="" value="" label="Email" placeholder="E-Mail" class="form-control">
<div class="input-group-addon"><i class="fa fa-question-circle" aria-hidden="true"></i></div></div>
```

Screenshot: Input has no rounded corners

<img width="991" alt="bildschirmfoto 2017-05-12 um 15 49 52" src="https://cloud.githubusercontent.com/assets/111561/26001046/67411c72-372b-11e7-810f-5ac343d9d944.png">

Screenshot: But once I remove the label-tag, the input has rounded corners again

<img width="990" alt="bildschirmfoto 2017-05-12 um 15 50 06" src="https://cloud.githubusercontent.com/assets/111561/26001047/6743227e-372b-11e7-8feb-b3151213e86b.png">

Screenshot: The CSS that "removes" the rounded corners with the problematic first/last-child-declarations.

<img width="800" alt="bildschirmfoto 2017-05-12 um 15 50 27" src="https://cloud.githubusercontent.com/assets/111561/26001048/67425826-372b-11e7-842c-f556323da921.png">

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by pat270** [comment]
I would say try putting the label outside the input-group, see http://v4-alpha.getbootstrap.com/components/input-group/#basic-example. It doesn't look like labels inside input-groups are supported.

```
<div class="form-group form-group-email">
    <label>E-Mail</label>
    <div class="input-group">
        <input type="text" id="" name="" value="" label="Email" placeholder="E-Mail" class="form-control">
        <div class="input-group-addon">
            <i class="fa fa-question-circle" aria-hidden="true"></i>
        </div>
    </div>
</div>
```

**Comment by mdo** [comment]
The only way around this is putting the labels outside the input group. Added a quick docs mention in ea2d6adfc.
