### ISSUE TITLE
Display class, Btn small

### ISSUE THREAD

**Issue by tobioye88** [twbs/bootstrap#22618]
The new display class is awesome but doesn't wrap or scale well in small screens.

The btn-sm class need a padding top of .30rem to look properly padded. it apeares that chrome give the text a default padding or some space under the text.

-chorme for windows

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by tobioye88** [comment]
CodePen
https://codepen.io/tobioye88/pen/VbBjxJ

**Comment by cr101** [comment]
@tobioye88 
> The new display class is awesome but doesn't wrap or scale well in small screens.
for a long word you coud use `word-wrap: break-word;`

**Comment by mdo** [comment]
Closing for #22856 for the display heading change.
