### ISSUE TITLE
seperator in dropdown menu in navbar

### ISSUE THREAD

**Issue by bardware** [twbs/bootstrap#22617]
I'm in a navbar. For Bootstrap 3 there's a nice [sample](http://getbootstrap.com/examples/navbar-fixed-top/) with a dropdown 
There's a seperator and a small heading below the horizontal line
I don't see such a sample in the bootstrap 4 documentation how it would be done there?

The [sample](https://v4-alpha.getbootstrap.com/components/navbar/) has div's instead of a nested list but no seperator and no heading.

Will it be possible to use seperators in a dropdown menu in a navbar?

**Comment by jipexu** [comment]
yes but there is no more class divider provided so you have to do it ...

**Comment by Johann-S** [comment]
This how you can have a divider in Dropdown : https://v4-alpha.getbootstrap.com/components/dropdowns/#menu-dividers
