### ISSUE TITLE
How to get working?

### ISSUE THREAD

**Issue by JohanTh** [twbs/bootstrap#22611]
Hi, I am unable to make this work. This is what I have done and is the only thing the instructions tells me to do:

- Add `twbs:bootstrap` to my meteor project
- Or I do `npm install bootstrap`
- I try to add a grid view from bootstrap docs in to a template:

```
  <div class="container">
    <div class="row">
      <div class="col">
        a
      </div>
      <div class="col">
        b
      </div>
    </div>
  </div>
```

Does not look like in the docs, the boxes are not even lined up horizontally. What am I missing? I don't see any more instruction steps in how to get it working.

METEOR@1.4.4.2

**Comment by mdo** [comment]
Without a complete example, no idea. You have to include the compiled CSS (and JS) in your pages before you can make use of Bootstrap with most package managers (we don't ship the compiled files there). Also, we don't ship our docs styles there either—those are for our use only.
