### ISSUE TITLE
Modern Alerts (Feature)

### ISSUE THREAD

**Issue by JayteeNZ** [twbs/bootstrap#22614]
Righteo,

Quite often when i'm working with Bootstrap, i'll usually always change the alert component. Either i'll give it an opaque background or completely change it to the type in the Bootstrap 3 docs (white panel with left border).

Just a thought and definitely not urgent / necessary, but what about either adding a variant for this or completely replace the old alerts with something like this?

[See on Pastebin](https://jsbin.com/muvicigayo/edit?html,output)

**Comment by bkdotcom** [comment]
Does this style change require alternate markup?  Or just some css tweaks / customization / theming?

**Comment by Johann-S** [comment]
I'm sorry @JayteeNZ but I don't understand what do you do to Bootstrap Modals, maybe you can create a  [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) to demonstrate that

**Comment by JayteeNZ** [comment]
Okay here's a rough concept. @bkdotcom Additional markup wouldn't need to be required.

Here's the pastebin @Johann-S

[Pastebin](https://jsbin.com/sizekuceso/edit?html,output)

**Comment by jipexu** [comment]
hi can you provide the same example with BS4 ?

**Comment by JayteeNZ** [comment]
@jipexu Uhm the markup for Bootstrap 4 hasn't changed but i've updated the Pastebin anyway.

[Pastebin](https://jsbin.com/muvicigayo/edit?html,output)

**Comment by LonerD** [comment]
But this small green line is uninformative. Filled form is much more visible.

**Comment by SnakeSVx** [comment]
Is thé new one not better in terms of contrast for accesibility reasons. Would be Nice to take them both through a checker/validator to compare thé two. I know our webmaster complained in bootstrap 3 about thé contrast not always being good enough for alerts and thé text they contain.

**Comment by LAUVz** [comment]
my proposition number 3 https://codepen.io/LAUVz/pen/ybdjeE It has both coloured background and the styling as suggested + possibility to have illustrative icons on the side

**Comment by bkdotcom** [comment]
IMHO:  I think it's unnecessary for bootstrap to have multiple "themes" in its core.
That said.  @LAUVz :  Your alert looks great.  I'd change `.alert-text` to `.alert-body`      .xxxx-body  is what bootstrap uses for modals (and with any luck, [tooltips, cards, & popovers](https://github.com/twbs/bootstrap/issues/22092))

**Comment by mdo** [comment]
We'll be passing on these. We use one of the styles in v4 and the other for our docs, where it's incredibly useful to have something that stands out from our normal content.

**Comment by mdo** [comment]
Also, see #21769.
