### ISSUE TITLE
[v4]: /utilities/image-replacement/ needs more documentation or examples

### ISSUE THREAD

**Issue by ahmetb** [twbs/bootstrap#22613]
https://v4-alpha.getbootstrap.com/utilities/image-replacement/ is not helpful. It doesn't show how to "replace an element's content with a background image" as advertised.

**Comment by dillonchanis** [comment]
@Johann-S I could submit a PR for this. Providing an example and perhaps a description on why you would use it.

**Comment by Johann-S** [comment]
Sure @dillonchanis go ahead 👍
