### ISSUE TITLE
Image heigth Internet Explorer 10

### ISSUE THREAD

**Issue by drolean** [twbs/bootstrap#22621]
Hello, 

i have a problem on a image sizes on IE10 
https://codepen.io/leandroross/pen/KmeQdP
working perfect on Chrome and Firefox but on IE10 show a blank spacing. 

if i set a heigth of image the problem resolve, but i need a image responsive.

apologies my english

**Comment by heikojansen** [comment]
Might be https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items ?
Just an unverified spontaneous idea, though.

**Comment by mdo** [comment]
That's most likely it, closing out. See #21650.
