### ISSUE TITLE
Problems configuring build system on Ubuntu 16.04 with bower installed bootstrap4

### ISSUE THREAD

**Issue by tamarmot** [twbs/bootstrap#22623]
I have carefully followed the steps here:
https://v4-alpha.getbootstrap.com/getting-started/build-tools/

Unfortunately when I try to run grunt dist, I get:

> Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'is-travis'

I have tried forcibly installing is-travis, but that does not fix the error.  Any pointers for how I should correct my installation so I can build will be greatly appreciated.

Thanks
Tamar

**Comment by Johann-S** [comment]
Sorry @tamarmot but our build system changed and we use Grunt only to test on SauceLabs.
This is the list of available tasks : https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L19
to run a task you have to do : `npm run <taskname>` for example : `npm run dist`
