### ISSUE TITLE
How to do version control of _custom.scss ?

### ISSUE THREAD

**Issue by praveenpuglia** [twbs/bootstrap#22627]
- I have installed boostrap using `npm`.
- `node_modules` is entirely ignored in gitignore.
- I am supposed to make changes to `_custom.scss` to override variables.
- If I do that, however, I can't version control it.
- So I decided to create my own `_custom-variables.scss`.

## What's happening?
I created an app level scss file, say app.scss and tried to import `bootstrap.scss` from node_modules and import my own `_custom-variables.scss` after that. I did this so I can have access to all the variables set by bootstrap in `_variables.scss` and then override the one I want in `_custom-variables.scss` without the `!default` option. 

```scss
@import "../node_modules/bootstrap/scss/bootstrap.scss";
@import "custom-variables";
```
This however doesn't seem to work. The values for variables aren't getting overridden.

How can I solve this?

**Comment by dagoss** [comment]
Would you want to flip those import statements so that your variables are defined first? Otherwise you're setting the variables after all the rules have been defined.

If your `custom-variables` needs a variable from `bootstrap.scss` to already be defined, I just copy those definitions over too.

**Comment by praveenpuglia** [comment]
Think [this](https://github.com/twbs/bootstrap/issues/21409) is related to this issue. In v6-alpha, the `_custom.scss` file in `bootstrap.scss` comes after `_variables.scss`. So to override things and use the existing variables from _variables, example
```scss
$body-bg: $brand-primary; // instead of the default white;
```

This worked. But having `_custom.scss` inside node_modules, creates a version control issue. So I thought, let's import bootstrap.scss into my own `app.scss` and then import my own `_custom-variables.scss` which would be able to do the same.

For some reason, that however doesn't work. 

I now see that `_custom.scss` has moved up in imports inside `boostrap.scss`. So how to I customize things without having to copy all the variables first? Right now, to do this, I'll have to do the following.

```scss
//app.scss
@import 'custom-variables';
@import 'node_modules/bootstrap/scss/bootstrap';
```

Then in `_custom-variables.scss`, 
```scss
// unnecessary copying of variables from _variables.scss
$blue:   #0275d8;
$brand-primary: $blue;

//overrides
$body-bg: $brand-primary;
```

I should have been able to just do
```scss
$body-bg: $brand-primary;
```
without the need of explicitly importing dependent variables.

**Comment by mdo** [comment]
Custom file is in the right spot; it can override `!default` values, but it cannot use the variables as well. It's super limited in functionality, but it provides some support.

**Comment by praveenpuglia** [comment]
I am sorry but I am still a bit confused.

So, if I do override values in `node_modules/bootstrap/scss/_custom.scss` and want to be part of git repo, I need to explicitly add this file to git? or How?

**Comment by mdo** [comment]
No idea on your particular setup. If you're checking in Bootstrap's source files, you can use it. Otherwise, use a different file outside `node_modules` to import all over Bootstrap and do your modifications there.
