### ISSUE TITLE
Unnecessary horizontally scrollable divs looks messy in IE

### ISSUE THREAD

**Issue by aakjaer** [twbs/bootstrap#22622]
Horizontal scrolling on multiple levels of containers seems a bit excessive.

<img width="1411" alt="screenshot 2017-05-15 10 32 21" src="https://cloud.githubusercontent.com/assets/16089337/26049143/47ad2b18-395a-11e7-920f-c8131660bbef.png">

Quick-fix: replace "overflow: scroll" with "overflow-x: auto"

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.
