### ISSUE TITLE
Dropdown and navbar

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#22628]
I try use the new dropdown with popper, but i can't use it in navbar. Popper always add position absolute to dropdown. How to be used dropdown and navbar in mobile?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by danijelGombac** [comment]
I was tried to create a JS Bin test, but alerted me: Sorry this bin is too large for as to save.

**Comment by danijelGombac** [comment]
The navbar css:

```
 .navbar-expand-md .navbar-nav .dropdown-menu {
    position: static;
    float: none;
}
```

But what can i see the position was overridden by popper and cannot be applied.

**Comment by Johann-S** [comment]
I made a CodePen and I don't see any issues here : https://codepen.io/Johann-S/pen/RVBoGM
Maybe I misunderstood something 😣

**Comment by danijelGombac** [comment]
Alpha 6 navbar for compared. Is different in mobile.

https://jsbin.com/cafeceyuwu/edit?html,css,js,output

**Comment by Johann-S** [comment]
Yes I see the display is different 👍 
But why is it a problem for you ?

**Comment by danijelGombac** [comment]
I don't use navbar like in documentation. In mobile i move it to the left and is opened like a drawer:

http://git.blivesta.com/drawer/

This dropdown menu is not very good for my design. The old version can expand and is better looking.

**Comment by Johann-S** [comment]
Hmm ok I see thank you for the explanation 👍
