### ISSUE TITLE
always set line-height to 1, use margin to add space !!!

### ISSUE THREAD

**Issue by iamybj** [twbs/bootstrap#22626]
always set line-height to 1, use margin to add space !!!

I found bootstrap use a lot of line-height = 1.4, this is not a good solution. 

This will make the text part and the other part looks like a more wide space.

If use margin, the space can be mixtured, and the space looks like the same.

**Comment by Johann-S** [comment]
Can you specify which release of Bootstrap do you speak ? Thank you 👍

**Comment by iamybj** [comment]
all release

**Comment by mdo** [comment]
There's a time and a place for all CSS properties that affect line-height and white space. Simply declaring one incorrect does not make the others more correct. We'll stick with the proven techniques we've used for the last five years.
