### ISSUE TITLE
Bootstrap Carousel is not responsive (Image Stretch)

### ISSUE THREAD

**Issue by surjithctly** [twbs/bootstrap#22639]
**Issue Screenshot:**
![untitled](https://cloud.githubusercontent.com/assets/1884712/26154370/d064b1aa-3b2c-11e7-8019-fbe841907a03.jpg)

**The issue can be seen on:**
https://v4-alpha.getbootstrap.com/components/carousel/

**Description:**
As you can see in the image, The Carousel Image is being stretched in mobile versions. Where in a live environment with a full-width slider and real images, this is a pain. So please make the carousel responsive.

**Workaround :** 
`object-fit: cover`

But this has limited browser compatibility.

**Comment by Wendtly** [comment]
https://github.com/twbs/bootstrap/pull/22392

**Comment by Johann-S** [comment]
thank you @Wendtly, so close because it's already fixed

**Comment by surjithctly** [comment]
Great.. @Johann-S Then why it's not updated in Docs?

**Comment by Johann-S** [comment]
Because our documentation will be updated on our next release
