### ISSUE TITLE
Documentation inconsistency - v4 migration for label/tag/badge

### ISSUE THREAD

**Issue by tobypinder** [twbs/bootstrap#22635]
[The Bootstrap v4 migration plan](https://v4-alpha.getbootstrap.com/migration/#labels-badges-and-tags) states

>Labels, badges, and tags
> * **Renamed `.label` to `.tag`** to disambiguate from the <label> element.
> * **Dropped the `.badge` component** as it was nearly identical to labels/tags. Use the `.tag-pill` modifier together with the label component instead for that rounded look.
> * Tags are no longer floated automatically in list groups and other components. Utility classes are now required for that.

However [current documentation](https://v4-alpha.getbootstrap.com/components/badge/) and the `alpha6` release appear to have renamed `.label` to **`.badge`**, not `.tag`.

I think the documentation on the v4 migration path just needs updating to match the most recent releases.

**Comment by Quy** [comment]
It will be updated to the following in the next release/beta:
https://github.com/twbs/bootstrap/blob/v4-dev/docs/migration.md

**Comment by Johann-S** [comment]
Closed thanks to @Quy comment 👍

**Comment by shvchk** [comment]
Migration docs were moved to https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/migration.md since 3e76d65
