### ISSUE TITLE
Dropdown (Select options) borders issues

### ISSUE THREAD

**Issue by padiyan** [twbs/bootstrap#22633]
With some browsers, and some window sizes, the dropdown (Select options) borders have issues - ex: no bottom border, very thick left border.

**Comment by cr101** [comment]
@padiyan Bug reports must include a live demo of the problem. Per the contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by padiyan** [comment]
@cr101 - CodePen link - https://codepen.io/anon/pen/BRPvGY
bootstrap version - 3.3.7
Browser details - Chrome 57.0.2987.133 (64-bit)
OS details - Windows 10 Pro

**Comment by cr101** [comment]
Bootstrap 3.x is no longer actively developed. See [#20631](https://github.com/twbs/bootstrap/issues/20631)
For general "how to" questions you might want to try [StackOverflow](https://stackoverflow.com/questions/tagged/twitter-bootstrap-3)

**Comment by padiyan** [comment]
@cr101 , Thanks.  This issue not occurring in bootstrap 4 beta version.

**Comment by Johann-S** [comment]
Thank you @cr101 to handled that issue you did great work 👍
