### ISSUE TITLE
[Docs] Incorrect id attribute in modal example

### ISSUE THREAD

**Issue by danielstrimpel** [twbs/bootstrap#22632]
The code example under https://v4-alpha.getbootstrap.com/components/modal/#live-demo says
```

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
```

but the id of the first modal div should be "exampleModal" not "myModal". 

Having forked and looked at the source file of the doc, the mistake seems to already have been corrected, but is not showing up live.

**Comment by Johann-S** [comment]
This fix will be online at our next release
