### ISSUE TITLE
New dropdown misplaced

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#22636]
When i updated to the new dropdown v-4-dev , dropdown-right is misplaced.

https://codepen.io/danijelGombac/pen/eWLmOK

**Comment by FezVrasta** [comment]
`.dropdown-menu-right` defines `left: auto !important; right: 0`, this breaks the inline style applied by Popper.js.

cc @Johann-S

**Comment by Johann-S** [comment]
I don't see any `.dropdown-menu-right` here @FezVrasta but yes I'll have to find a better way to do this instead of add `!important` any ideas ? 

but yes @danijelGombac the dropdown is misplaced

**Comment by FezVrasta** [comment]
I can't always get that class applied, I'm not sure how it works. By the way I think that if you upgrade to 1.9.4 one of the bugs will go. But the problem with the `.dropdown-menu-right` must be solved Bootstrap side.

**Comment by Johann-S** [comment]
`.dropdown-menu-right` is applied manually so if it's not present in the HTML this class isn't applied.

Yes I agreed about `.dropdown-menu-right` must be solved on Bootstrap side but I just asked if you have any ideas how to fix it 😄

**Comment by danijelGombac** [comment]
Hy,

i try to update the pen with the new code and i don't see any difference. When i add min-width to dropdown is worse.

https://codepen.io/danijelGombac/pen/eWLmOK

 I'm doing something wrong?

**Comment by Johann-S** [comment]
In the previous version of you CodePen you didn't use `.dropdown-menu-right` and `.dropdown-menu-large` if you remove those class they are no issue. But you find a new one, so can you open a new issue please

**Comment by im-bilaljafri** [comment]
Hi, I've an issue with drop-down menu. It goes under the navigation bar and hide half.
Do you guys have any idea or solution?

**Comment by julien-deramond** [comment]
@im-bilaljafri This issue is closed, please create [a new discussion](https://github.com/orgs/twbs/discussions/new/choose) if you need help from the Bootstrap community describing precisely your problem.
