### ISSUE TITLE
Dropping flex and max-width introduced issue for Variable content width

### ISSUE THREAD

**Issue by sachinsinghi** [twbs/bootstrap#22649]
Hi @mdo,

As advised by you, I am logging the defect.

With [this commit](https://github.com/twbs/bootstrap/commit/2436ad589cfc235c84160fe14e4cc4ec97a9c5ca) that dropped flex and max-width introduced a bug on [variable content width](https://v4-alpha.getbootstrap.com/layout/grid/#variable-width-content) feature.

Since the max-width is dropped, .col max-width takes over the width of columns and make it 100%. 

**Previous code:**
` @mixin make-col($size, $columns: $grid-columns) {
   flex: 0 0 percentage($size / $columns);
   max-width: percentage($size / $columns);
  }`

**New code:**
 `@mixin make-col($size, $columns: $grid-columns) {
   width: percentage($size / $columns);
  }
`
- Operating system and version: Windows 7+, Mac OS 10+, Android 4+, iOS 8+, Win10 Mobile
- Browser and version: Chrome, Firefox, Safari
- Here is the sample [JS Bin](https://jsbin.com/lecoxij/edit?html,css,output)

If the above mentioned commit is reverted, this issue will be fixed.

Please excuse me if I am not very clear with the explanation. As this is me first time logging a defect.

Happy to provide more details if needed.

**Comment by mdo** [comment]
Hmm, yeah, and the premise for the PR that dropped those values didn't turn out as I expected because our `.col` classes include padding by default. As such, we can't use them in place of the width/height utilities. Probably safe to revert that PR altogether.

**Comment by mdo** [comment]
Good looking out. I've opened a PR to revert that change. See #22706.

**Comment by mdo** [comment]
Merged #22706.
