### ISSUE TITLE
Readme links to vanished file

### ISSUE THREAD

**Issue by bardware** [twbs/bootstrap#22643]
The [readme](https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/build-tools.md) says:

> We maintain the list of browsers supported through Autoprefixer in a separate file within our GitHub repository. See [/build/postcss.js](https://github.com/twbs/bootstrap/blob/v4-dev/build/postcss.js) for details.

Seems to me this file was moved to: https://github.com/twbs/bootstrap/blob/v4-dev/build/postcss.config.js

**Comment by mdo** [comment]
Fixed by #22643.
