### ISSUE TITLE
Collapse - accordion first element opened by default

### ISSUE THREAD

**Issue by tsm91** [twbs/bootstrap#22642]
problem: After the initialisation `$('.collapse').collapse({parent: '#accordion'});` the first collapsible element is opened by default. I want all collapsible elements in a closed state if there is no `show` class.

plunkr: http://plnkr.co/edit/pclYOI6qymtqGZ8UrBjy?p=preview (seach for !!!this should stay closed!!!)
version: v4 alpha 6
docs: http://v4-alpha.getbootstrap.com/components/collapse/#accordion-example

**Comment by heikojansen** [comment]
Remove the Javascript, set "aria-expanded" to "false" on the first "a" and also add 'class="collapsed"' there (both like on the other "a" in the other headings) and it should work, I believe...

**Comment by tsm91** [comment]
@heikojansen hiho, u are right it was the js part `$.fn. collapse`, has already been initiated
