### ISSUE TITLE
Expensive tooltip smoothing

### ISSUE THREAD

**Issue by speller** [twbs/bootstrap#22656]
Windows 7 x64, system scale 125%, latest Chrome, chrome page scale 100%. 

Go to the official docs: https://v4-alpha.getbootstrap.com/components/tooltips/ , mouse over the example, and get badly-looking, expesively smoothed tooltips:

![212](https://cloud.githubusercontent.com/assets/1829515/26201541/70f0d978-3c0e-11e7-9844-79a069a797a9.jpg)

If I set Chrome scale to 80% tooltip look fine:
![213](https://cloud.githubusercontent.com/assets/1829515/26201628/e7b4fd32-3c0e-11e7-9bc1-7ea0b0ee6e2a.jpg)

Bootstrap 3 has no this issue.

**Comment by alecpl** [comment]
Maybe the same issue as in #22610 ?

**Comment by patrickhlauke** [comment]
@alecpl yup
