### ISSUE TITLE
Nested tabs via javascript issue

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#22654]
I try to make nested tabs with content loaded via ajax, but there is something wrong with tabs js. The active state was removed from tab link, but not the content. Try clicking on one of the account button and then go back from address tab to account tab. Address content remain open. 

For the account tabs is the opposite, the content is active and the active state removed from the link.

Dev 4

https://codepen.io/danijelGombac/pen/PmdLLw

Dev 4 with changes, working OK

https://codepen.io/danijelGombac/pen/GEgaXN

Last alpha 4:

https://codepen.io/danijelGombac/pen/BROeoY

**Comment by SamuelPinho** [comment]
@danijelGombac add these two line of codes, maybe not the best, but it will solve.

```
$(document).on('click', 'a[href=\'#tab-account\']', function() {
  $('#nav-address').html('<span class="nav-link font-weight-bold">Address</span>');
  $('#nav-method').html('<span class="nav-link font-weight-bold">Method</span>');
});

$(document).on('click', 'a[href=\'#tab-address\']', function() {
  $('#nav-method').html('<span class="nav-link font-weight-bold">Method</span>');
});
```

**Comment by danijelGombac** [comment]
I try to fix this problem with change (in my test is working ok):

`const active = $(container).find(Selector.ACTIVE)[0]` LINE 151

with

```
let active = false;
	  
if ($(container).is(Selector.NAV_LIST_GROUP)) {
	active = $(container).find(Selector.ACTIVE)[0];
} else {
	active = $(container).children(Selector.ACTIVE)[0];
}
```

Can you check if is ok?

@Johann-S

**Comment by danijelGombac** [comment]
Ok, is not good solution. I move it back like in alpha 6:

`ACTIVE_CHILD		  : '> .nav-item > .active, > .active',`

`const active = $(container).find(Selector.ACTIVE_CHILD)[0]`

With `.find(Selector.ACTIVE)[0]` i can't using nested tabs in nav.

**Comment by Johann-S** [comment]
PR for this issue : https://github.com/twbs/bootstrap/pull/23087
