### ISSUE TITLE
dead links in theme previews

### ISSUE THREAD

**Issue by netikras** [twbs/bootstrap#22652]
So I was browsing B4 themes and got a 404. 
1. Open up a Dashboard theme preview
2. activate LIGHT setup (from the bar below)
3. activate DARK setup
4. &joy the 404

Same applies for Marketing theme (STARTUP link is dead). Seems like links to default theme setups are not working from inside the preview page

Request URL:https://bootstrap-themes.github.io/dashboard/index/
Request Method:GET
Status Code:404 Not Found
Remote Address:151.101.112.133:443
Referrer Policy:no-referrer-when-downgrade

**Comment by Johann-S** [comment]
You should use this link : https://themes.getbootstrap.com/ found on v4 Documentation
And you'll find this link : https://themes.getbootstrap.com/products/dashboard

**Comment by netikras** [comment]
I think you missed my point :) I was just trying to point out a (probably) misconfiguration in public website leading to 404s. I don't really need those themes anyway :)

**Comment by Johann-S** [comment]
Oh ok thats right this link is dead, nice catch 👍 
/CC @mdo

**Comment by Quy** [comment]
Per Contributing to Bootstrap:
> Please do not open issues regarding the official themes offered on http://themes.getbootstrap.com/. Instead, please email any questions or feedback regarding those themes to themes AT getbootstrap DOT com.

**Comment by Johann-S** [comment]
Closed thanks to @Quy comments 👍

**Comment by dhg** [comment]
Hey y'all – this has been fixed fwiw. Thx for letting us know @netikras.
