### ISSUE TITLE
Bootstrap 4 breaks line-breaks in print css in Edge

### ISSUE THREAD

**Issue by jemminger** [twbs/bootstrap#22658]
Bootstrap 4 (currently 4.0.0-alpha.6) breaks the behavior of `break-before: always` and `page-break-before: always` in MS Edge.

See here, the "print" button should open a print dialog that has a preview with 3 pages, not 1.  If you remove bootstrap it behaves as expected.

https://codepen.io/jemminger/pen/VbEpZR

Tested on Win10, Microsoft Edge 38.14393.1066.0

**Comment by hultqvist** [comment]
I tried your example in Edge 40 and I get 3 pages, could it be fixed in edge?

Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by jemminger** [comment]
That's bizarre, I just tried it again now in 38, and it's working.  I'll go ahead and close this.
