### ISSUE TITLE
Regression in .input-group vs. grid cols

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#22667]
I'm testing update to the latest build from alpha6. I don't know if it's possible to create JSBin with unreleased bootstrap files, so here's the simple snippet:
```
<div class="form-group row">
    <label class="col-2 col-form-label">Label</label>
    <div class="input-group col-10">
        <div class="form-control"></div>
        <a href="#delete" class="input-group-addon icon cancel" title="Delete"></a>
    </div>
</div>
```
Problem is that label is above the input which has width:100% defined in _input-group.scss, which has precedence over the width defined for .col-10 class. 
The label should be on the left according to col-2 and col-10 classes used here, as it was in alpha6.

**Comment by Johann-S** [comment]
You can create a CodePen and you copy/paste last dist files in CSS and JS 😉

**Comment by mdo** [comment]
Don't put grid classes right on input groups—put it on the parent. That'll likely fix it.

**Comment by alecpl** [comment]
Really? I don't know about v3, but it definitely worked in v4 alpha6. I know you'd like to move forward with v4 releases, but please, reconsider. You use similar structure for normal form-controls, using the same with group inputs sounds reasonable and consistent. No?

**Comment by mdo** [comment]
You're not using the correct markup—your column class shouldn't be on the input group (which has it's own flex styles and more that interfere with column classes) and your `<input>` is actually a `<div>` for some reason. See https://jsbin.com/lopocakeho/edit?html,css,js,output.

**Comment by alecpl** [comment]
Ok, I get it. It just worked before, so I thought you may want to support this case. Anyway, thank you for your work.
