### ISSUE TITLE
.thead-inverse a should be white, not blue

### ISSUE THREAD

**Issue by hughbe** [twbs/bootstrap#22665]
I'm migrating to bootstrap 4, and have the following html structure:

```
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th><a>Created Time</a></th>
    </tr>
  </thead>
</table>
```

However, the anchor is styled as blue, not white:
![screenshot](https://cloud.githubusercontent.com/assets/1275900/26274066/d5de3b4e-3d69-11e7-84e0-8fa258b9d9fb.png)

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/22666#issuecomment-309254648
