### ISSUE TITLE
Chrome cuts off printing after a few pages with lots of div class="row"s in bootstrap v3.3.7

### ISSUE THREAD

**Issue by sethborg** [twbs/bootstrap#22662]
This is a really odd bug and it may be a bug in Chrome rather than Bootstrap v3.3.7 but I'm posting here in case you have a suggestion as to what could be the issue.

Printing works fine in firefox and IE but chrome cuts it off after a few pages. Here is an example. http://awrconference.com/test1.htm Press print and look at the preview. The preview won't show as many lines as the webpage. It stops midway through the 3s instead of going all the way to the 5s. I have 20 of each number.

I'm using this structure which when you print it, it comes out as rows rather than 3 columns

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title></title>
	<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" />
</head>
<body>

<div class="row">
	<div class="col-sm-3">
		1a
	</div>
	<div class="col-sm-6">
		1b
	</div>
	<div class="col-sm-3">
		1c
	</div>
</div>
this structure is repeated until you fill about 1000 lines

</body>
</html>
```

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by sethborg** [comment]
It's a chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=732834#c12 but you can add the word "screen" to your bootstrap.min.css in 3 places to fix it:

@media screen (min-width: 768px) { .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12 { float: left; }

@media screen (min-width: 992px) { .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12 { float: left; }

@media screen (min-width: 1200px) { .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12 { float: left; }
