### ISSUE TITLE
Modal Within Div with -webkit-overflow-scrolling: touch; ends up behind overlay

### ISSUE THREAD

**Issue by matt-filion** [twbs/bootstrap#22676]
OS: iOS
Browser: Chrome 58.0.3029.113
Test Case: http://jsbin.com/tigewotiko

The bug is fairly reliably disabled and enabled by removing -webkit-overflow-scrolling: touch. When its added, the modal will appear behind the overlay. When it is not, it behaves as expected, on top of the overlay.

If the modal, is not within the container with -webkit-overflow-scrolling: touch it works as expected. However, due to the nature of the framework I'm using the modal must appear at its point of use.

**Comment by mdo** [comment]
We've had a number of issues with the overflow scrolling in the past. I'd suggest keeping models outside any other DOM though (meaning, at the end of your pages before `</body>` to prevent issues like this from coming up. Similar things can happen with different `position`s if memory serves.
