### ISSUE TITLE
Why are the default Bootstrap form inputs so ugly?

### ISSUE THREAD

**Issue by petewulf** [twbs/bootstrap#22674]
Is there any reason why the default Bootstrap form inputs are so ugly?

There are so many good examples out there how to do better, i.e. "sky-forms", in my opinion this needs an urgent redesign.
I usually tend to use third party plugins, but in a so called "state of the art" frameworks this should be a standard at least.

**Comment by Johann-S** [comment]
Thank you for your opinion @petewulf 👍 
We are open for improvements in our inputs do not hesitate to open a PR
