### ISSUE TITLE
Documentation for Equal-width is slightly off

### ISSUE THREAD

**Issue by peterbenoit** [twbs/bootstrap#22677]
The columns for [Equal-Width](https://v4-alpha.getbootstrap.com/layout/grid/#equal-width) have repeating labels.

1 of 2 - 1 of 2
1 of 3 - 1 of 3 - 1 of 3

A nitpick, I know.

**Comment by tex0gen** [comment]
Depends how you look at it. If you see the column as literally 1 of the 3 columns then it's correct.

**Comment by peterbenoit** [comment]
The rest of the examples have the "correct" labels, this seems to be an outlier.

**Comment by mdo** [comment]
Yeah, we can update that later. Good eye.

**Comment by Scoutski** [comment]
Made a simple PR to update this:
https://github.com/twbs/bootstrap/pull/22697

**Comment by mdo** [comment]
Merged #22697, thanks!
