### ISSUE TITLE
Custom Select — has-danger icon is broken

### ISSUE THREAD

**Issue by surjithctly** [twbs/bootstrap#22685]
`has-danger` Icon for custom select is broken. See image
![screenshot-localhost-7880 2017-05-24 14-41-21](https://cloud.githubusercontent.com/assets/1884712/26396217/2fc6b270-4090-11e7-9be4-89e85d425fc4.png)

This is because the background size is already set in `.custom-select`

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by surjithctly** [comment]
Hello,

Just created a live demo. https://codepen.io/surjithctly/pen/OmdwQv

Thank you.

**Comment by wolfy1339** [comment]
This has already been discussed somewhere on an other issue. The icons aren't meant for select inputs

**Comment by surjithctly** [comment]
So, either the icon should be removed from select element or should be adjusted.  I guess it won't be a problem to adjust that for custom select because the default arrow is already hidden.

**Comment by alecpl** [comment]
It is #19852.
