### ISSUE TITLE
Grid display issue for col-xs-* on small viewport (3.3.7)

### ISSUE THREAD

**Issue by ahkelly** [twbs/bootstrap#22682]
When viewing xs grid elements on a small viewport with any combination that is not 1 12 column width column the right column will not properly render (extended beyond 100% viewing width). See test case below and shrink view to less then 600px wide.

![xs-1-cropped](https://cloud.githubusercontent.com/assets/7065207/26360123/4834f8da-3fa5-11e7-9544-73f77401cd4a.PNG)

- Operating system and version (Windows 10)
- Browser and version (Chrome, Firefox, MS Edge)
- Example Test case [JS Fiddle](https://jsfiddle.net/4kecosj6)

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by ahkelly** [comment]
Unsure how this is not a critical bug?

**Comment by Johann-S** [comment]
Currently we do not have time for v3 and I think we wont have time in the future too.
But if your issue is present in v4 do not hesitate to /CC me 👍

**Comment by ahkelly** [comment]
Understood, I appreciate all your efforts on v4 and if it was shipping your response would make 100% sense. It is not an issue on v4 as it uses flex. I apologize for the interruption.
