### ISSUE TITLE
navbar-link hover has same color as background color in navbar-inverse for dropdown

### ISSUE THREAD

**Issue by parsmizban** [twbs/bootstrap#22683]
Hi,

I have a navbar in inverse color, There are some navbar-link in the dropdown , But they have same color as background for hover status

```
.navbar-inverse .navbar-link:hover {
    color: #fff;
}

.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0,0,0,.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}

```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by vishusharmagit** [comment]
Hi @parsmizban,
As @Johann-S mentioned please create a JS Bin.

Also, Meanwhile you can try following code.

.navbar-inverse .navbar-link a:hover {
    color: #fff;
}

**Comment by mdo** [comment]
Don't use `.navbar-` classes within the dropdown—they're named and limited to their direct components because there's no other say to build a complex system like this.
