### ISSUE TITLE
Buttons in input groups have height mismatched and not align properly with the input box on IE

### ISSUE THREAD

**Issue by nguyenhthai** [twbs/bootstrap#22690]
So on IE with the latest dev commit, I noticed that the button addon within the .input-group-btn does not have the proper height or align properly with the input box. I believe this is a regression issue because when I checked with the Alpha 6 on the official website, this does not happen. I already checked both case #20155 and case #18083 but they already have been fixed and applied only to the Alpha 6 version.

Here is the codepen to demonstrate the problem with up to date Bootstrap dev commit CSS and JS:
https://codepen.io/nguyenthai/pen/QvYXJz

Viewing it on IE yield the problem. Also I have attached some screenshots.
This is what it looks like on the Alpha 6 version on IE
![input group - alpha 6](https://cloud.githubusercontent.com/assets/6546158/26414926/58a9976c-4076-11e7-8a57-ff1fcf581b52.jpg)

This is what it looks like on the latest dev commit on IE
![input group - latest commit](https://cloud.githubusercontent.com/assets/6546158/26414928/5b2b55b6-4076-11e7-88a6-c927ad903bb2.jpg)

Chrome nor Firefox does not have this issue. IE version is 11.296.15063 running on latest Windows 10 v1703.

**Comment by petertorelli** [comment]
I'm seeing the same thing on 3.3.7 + Electron 1.6.2. The bottom row of the input jitters up and down 1-pixel as the responsive columns change size. I can make it go away by reordering the position of the rows, or using multiple containers, but it is super annoying.

**Comment by mo-mannan** [comment]
Seeing the same of v4.beta

**Comment by mdo** [comment]
Fixed by #23810.
