### ISSUE TITLE
[v4] Right aligned dropdown in nav causes horizontal overflow

### ISSUE THREAD

**Issue by kedarv** [twbs/bootstrap#22699]
This issue occurs on all desktop platforms. When you have a right aligned dropdown in the navigation bar, it overflows off the page creating a horizontal scroll and misplaced dropdown.

Demo v4 alpha 6: http://jsbin.com/sozuva/1
Demo v3 (desired behavior): http://jsbin.com/jorobic/1

I'm not sure if this issue is related to #22636

**Comment by Johann-S** [comment]
Currently with the last dist of our v4 code : https://codepen.io/Johann-S/full/Pmgado/

/CC @zalog
