### ISSUE TITLE
What's included does not explain what's included

### ISSUE THREAD

**Issue by inorganik** [twbs/bootstrap#22691]
I just downloaded 3.3.7 and I'm excited to start writing markup and styles. However there's quite a bit of extra files that have no documentation that explain what they are for and whether they are necessary:

```
.editorconfig
.gitattributes
.gitignore
.hound.yml
.travis.yml
CHANGELOG.md
CNAME
CONTRIBUTING.md
Gemfile
Gemfile.lock
Gruntfile.js
ISSUE_TEMPLATE.md
LICENSE
README.md
_config.yml
bower.json
composer.json
dist
docs
fonts
grunt
js
less
nuget
package.js
package.json
```
I have no way of knowing (besides trial and error) which of these files I can delete safely. 

For instance, nuget? Gemfiles? 

The gruntfile is the same way. It has a **`jekyll`** task and a **`pug`** task and I have absolutely no idea what those are for. The documentation doesn't explain it. 

I would like to strip out as many dependencies and declutter as many files as possible. But I can't find any info on these files. Would love some additional documentation please.

It would be really cool if downloading just gave you the critical files - then you optionally add on jekyll, etc. Even jQuery, since if you're using Angular-UI bootstrap, you don't need.

**Comment by AllSeeingEye** [comment]
Most of these are GitNPM/Grunt/Bower/whatever configuration files and they are not related to Bootstrap's main task (app styling) - therefore they're not covered in the documentation.

Clearly, these are included to cover the most use cases (e.g. inclusion into build systems).

**Comment by patrickhlauke** [comment]
Where did you download it from? On http://getbootstrap.com/getting-started/#download it gives you fairly clear choices to get compiled bootstrap, source code, or sass version. The source one also points you to http://getbootstrap.com/getting-started/#grunt which explains further what you're doing.

It seems you should just stick with downloading the compiled version?

**Comment by inorganik** [comment]
@patrickhlauke I downloaded the source code because I want to compile my own less. I wish you didn't close this. 

I read the getting started guide, including the grunt part. It does not explain what jekyll and pug are used for, just to name a couple. There are lots of other tasks it doesn't explain either.

As I stated nothing on that page or anywhere explains what files like nuget/gemfiles are used for.

**Comment by patrickhlauke** [comment]
when you compile your own version, all you still then want to use in your own project is the end result dist that the local compilation does. so all those extra files and dependencies would only be there for when you compile, not for when you come to add bootstrap into your own project.

**Comment by inorganik** [comment]
Still, if you are including jekyll and pug in the gruntfile, don't they bear an explanation?

**Comment by tex0gen** [comment]
@inorganik You'll struggle to compile your own LESS with this because it's no longer written for LESS. It's now SASS.
