### ISSUE TITLE
sidenav with dropdown/accordion

### ISSUE THREAD

**Issue by wendt88** [twbs/bootstrap#22718]
It would be nice to have styles for a sidenav, maby also with dropdown/accordion functionality for submenus. Also a full height style (if sidenav is shorter than the content). And a responsive support to open/close the sidenav

**Comment by sthoward** [comment]
Check out the [samples](https://v4-alpha.getbootstrap.com/examples/), especially Dashboard for sidenav - gets you part of the way there. And here's an example of [slideout](https://bootsnipp.com/snippets/4OZ8R)

**Comment by mdo** [comment]
No plans to add this ourselves, though if someone had a PR I'd review it.
