### ISSUE TITLE
Scrollspy: Custom selector

### ISSUE THREAD

**Issue by strarsis** [twbs/bootstrap#22719]
The target option in scrollspy can be used for selecting a navigation element - 
but the selector for the anchor element (`<a>[...]</a>`) is always appended to it:
```js
[...]
    this.selector       = (this.options.target || '') + ' .nav li > a'
[...]
````
Because I really like to use the data attribute approach for initialization, 
it would be great if the anchor-element selector can be customized, too, using data attributes.

**Comment by mdo** [comment]
Closing as stale / won't fix.
