### ISSUE TITLE
[Doc V4] components/modal/#Live demo - Wrong data-target

### ISSUE THREAD

**Issue by gitfirenz** [twbs/bootstrap#22714]
The following exemple does not work : 
https://v4-alpha.getbootstrap.com/components/modal/  #Live demo

The data-target "exampleModal" is wrong : 
`<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>`

It should be "myModal" to match :
`<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>`

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/21671
Available in our futur release
