### ISSUE TITLE
Popover position on resize window

### ISSUE THREAD

**Issue by gbourgeat** [twbs/bootstrap#22725]
All OS, Browser.

http://getbootstrap.com/javascript/#popovers

When I open popover (click on button "Popover on top") and I resize window, the popover don't keep her position.

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements. 
It's fixed in our new V4
