### ISSUE TITLE
Slickgrid data table tr td inside bootstrap dropdown behind showing issue 

### ISSUE THREAD

**Issue by maniarasu** [twbs/bootstrap#22724]
I am Slickgrid data table tr TD inside bootstrap dropdown behind showing the issue  anybody has a solution for this

**Comment by patrickhlauke** [comment]
per https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker you need to provide a reduced test case showing the issue (in codepen, jsfiddle, jsbin or similar)

**Comment by maniarasu** [comment]
Thanks!.  I followed as well.
