### ISSUE TITLE
DataTables fixed column transparent with Bootstrap 4 striped table

### ISSUE THREAD

**Issue by ierturk** [twbs/bootstrap#22723]
In DataTables example [here](https://datatables.net/extensions/fixedcolumns/examples/styling/bootstrap4.html), when scroll the table to left, fixed cell is transparent on dark rows.
Is this a bug related BS4 or DataTables. If so, is there a workaround to correct it?

**Comment by Johann-S** [comment]
Was a Bootstrap "bug" but fixed by : https://github.com/twbs/bootstrap/pull/21741
