### ISSUE TITLE
popover doesn't not show in right place

### ISSUE THREAD

**Issue by FAAAAT** [twbs/bootstrap#22734]
bootstrap version:Bootstrap v3.3.7
---
Hi, guys.
I use an popover contain an img tag and set the placement left. but when i load the page and first show the popover, the popover doesn't show in right place. 
I see the source code and a find , the tooltip actualHeight and actualWidth are not correct.  
Now I must set img's height and width , then it can work fine.

Any other way to solve this problem?

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
In our new V4 you wont have this issue
