### ISSUE TITLE
Centering content blocks with buttons

### ISSUE THREAD

**Issue by Miqueliu** [twbs/bootstrap#22732]
The `center-block` class is fine to achieve a centered button only if it is really a button element. Applying to a link button does not work.

Examples (both cases):
- `<button type="button" class="btn btn-default center-block">Pure button</button>`.
- `<a href="#" class="btn btn-default center-block">Link button</a>`.

**Comment by patrickhlauke** [comment]
do you have a reduced test case example? (also, `center-block` has been replaced with `mx-auto`)

**Comment by Miqueliu** [comment]
This is in version 3.

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by Miqueliu** [comment]
[Here](https://stackoverflow.com/a/47938427/7068523) is a solution.

A CSS declaration like `a.center-block { display: table; }` is usefull.

**Comment by mdo** [comment]
Buttons are inline-block, use `text-align` on the parent to change their alignment.

**Comment by Miqueliu** [comment]
Using `center-block` class, buttons are not inline-block. This class has not to be applied to buttons or links? Only devised for images and resized `div`s?
