### ISSUE TITLE
.no-gutter: specificity issue in some build processes 

### ISSUE THREAD

**Issue by timknight** [twbs/bootstrap#22730]
Within the PR #21211 a class of `.no-gutter` was added to allow for no gutter rows.

Including the grid through a build process that has a media query cleaner (either through gulp or grunt) kills the cascade position and the margins on `.row` of -15px for left and right take precedence.

While I know it introduces some specificity issues, adding `.row` to the selector fixes the issue.

```sass
.row.no-gutters {
  margin-right: 0;
  margin-left: 0;

  > .col,
  > [class*="col-"] {
    padding-right: 0;
    padding-left: 0;
  }
}
```

**Comment by sqal** [comment]
I can confirm this behaviour. In my project, everything works fine in dev mode, but in production where i use postcss with css-mqpacker and options `{ sort: true }` .no-gutters margins are being overridden 

![img](https://image.prntscr.com/image/a22da2400b6c4336b026dd50af7b1b36.png)

**Comment by mdo** [comment]
So the problem here is that a build tool is juggling around our CSS? I don't know how well we can solve this and all other problems that could arise from that—there's a decent amount of things that rely on a particular order to our Sass imports.

**Comment by timknight** [comment]
Hey @mdo, yeah that's correct. I definitely agree with you, that we can't account for all of the issues that may pop up with anyone's various build system. But in this case, if you consider that `.no-gutter` is really a utility/helper class of a `.row` item, then following the same mentality of the other Bootstrap utilities by using `!important` to ensure that declarations are executed regardless of conflict seems appropriate. While I suggested turning the selector `.no-gutters` into `.row.no-gutters` to correct the specificity issue created by the media queries, an alternative solution of just using an `!important` might line up better with the mentality of existing utility classes.

**Comment by mdo** [comment]
Punting as a won't fix for now, but let's keep an eye on this for after Beta 1 drops.
