### ISSUE TITLE
Pager Doesn't do responsive properly

### ISSUE THREAD

**Issue by JohnGalt1717** [twbs/bootstrap#22735]
Before opening an issue:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
Windows, Mac
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Chrome, Firefox, IE, Edge (latest in all cases)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)
Go to the pager documentation and shrink the page.

Right now the pager doesn't wrap or otherwise size properly on mobile platforms. It is whatever size it is and that's it. It should be responsive like the rest of the controls and shrink in size to a point and then have a nice wrapping mode or something.

**Comment by mdo** [comment]
Pager is gone in v4, so closing as a won't fix. We might be doing some v3 fixes after we launch v4, though, so tagging appropriately in the mean time.

---

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

_This is a saved reply._

**Comment by JohnGalt1717** [comment]
Even the alternatives that I saw for the pager don't appear to work properly.

**Comment by mdo** [comment]
Which ones? Have a link or example of what you're trying to achieve?

**Comment by JohnGalt1717** [comment]
In here: https://github.com/twbs/bootstrap/pull/18782 there are some examples. From what I can tell they don't scale automatically to a point and then wrap nicely. A pager control should shrink as much as possible before it wraps and only if absolutely necessary wrap. Perfect world it would also drop pages shown while shrinking to fit mobile so that wrapping was never an issue.

By dropping the pager the shrinking of the text and dropping of items is now entirely programmatic when it should be part of the control to just do all of that automatically.
