### ISSUE TITLE
Linked site gone

### ISSUE THREAD

**Issue by bardware** [twbs/bootstrap#22736]
Hi,

the [page](https://github.com/twbs/bootstrap#documentation) says: `Run through the tooling setup to install Jekyll` 

The link [tooling support](https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/build-tools.md#tooling-setup)gives 404

**Comment by Johann-S** [comment]
Good catch thank you @bardware 👍

**Comment by bardware** [comment]
I ran `npm install` and `grunt docs` and got the errors `Fatal error: Unable to find local grunt.` and after I installed grunt locally `Local Npm module "grunt-saucelabs" not found. Is it installed?` 
I take it you're changing something...

**Comment by Johann-S** [comment]
We don't use grunt anymore, we use npm scripts
Take a look at our package.json
