### ISSUE TITLE
Separate label and input for checkboxes/radios

### ISSUE THREAD

**Issue by NathanDubord** [twbs/bootstrap#22738]
I need to separate a checkboxes label and input to conform with django forms. There's a similar issue #19095 where @patrickhlauke mentioned it may be possible to look into. Is this something that could still be possible? 

In the meantime I've built out our own checkboxes, but I'd rather not have a mix between custom created form elements and bootstraps.

Just to clarify, I need to be able to write this:
```
<input type="checkbox" id="test">
<label for="test">Remember my preference</label>
```

instead of this:
```
<label class="custom-control custom-checkbox">
    <input type="checkbox" class="custom-control-input">
    <span class="custom-control-indicator"></span>
    <span class="custom-control-description">Remember my preference</span>
</label>
```

**Comment by bkdotcom** [comment]
So you want styling applied by default to `label` and `input[type=checkbox]`
(Did you intentionally omit class attributes?)

Bootstrap's "policy" is to not enhance/style elements unless you explicitly want it too (via classname)

**How is your request different from #19095 ?**

**Comment by NathanDubord** [comment]
I omitted classes to keep it simple, custom classes could be applied to style the label (:before, :after, etc.) and to hide the default input. As for #19095, I'm not saying to remove/modify existing implementation, but to add custom classes to allow for the separation of labels/inputs. Patrick had mentioned it's something that could be looked into. Generally I wouldn't be pushing for 2 implementations of the same functionality, but in cases like mine where Django forms field widgets don't know about the fields label, the label needs to be independent from the input (for/id relationship).

**Comment by mdo** [comment]
Closing as a won't fix.

You can do this already, but without a wrapping element, there's little we can do to ensure proper alignment and layout of the checkbox and it's text.
