### ISSUE TITLE
Image issue with cards with bad link

### ISSUE THREAD

**Issue by jlrober** [twbs/bootstrap#22742]
I'm sorry if something is wrong with this post. First time reporting an issue on GitHub.

But it was previously reported that there was an issue with images stretching in cards. If the images width was smaller than the container, the image would stretch to fill the container while maintaining the same height. With the latest build they set the width to 100% so it stretches the image to fill the card while maintaining aspect ratio. One problem with this is if you have a bad link, which I'm assuming is showing up as really thin and tall, it stretches it out to 100% width while maintaining aspect ratio, which makes a really tall image.

A solution I found that works better is to just put the image in a div and set the max-width of the image to 100%. You can set the div to text-align center to center align it. You can have smaller images that just don't take up the entire width or larger images if you want to fill the entire card, either way it maintains aspect ratio and you don't get any funky behaviors.

**Comment by cr101** [comment]
@jlrober potential fix coming in #[22288](https://github.com/twbs/bootstrap/pull/22288)

**Comment by jlrober** [comment]
That fix doesn't work in some scenarios, I think this is a better fix.

**Comment by mdo** [comment]
Closing per previous comment.
