### ISSUE TITLE
jQuery Dependency

### ISSUE THREAD

**Issue by tateman66** [twbs/bootstrap#22748]
Hey Mark/Jacob,

Sorry to ask you guys such a pointless question, but I've been following the weaponry you guys have been creating since the early days and I'm just curious.

Why keep the jQuery dependency in V4 now?  Yes, I like the closest() method as much as the next guy, but what problem is it still solving?

Is it not time yet to let eJohn's brain child retire?

Thanks guys.
Keep up the good work.
Steven Tate

**Comment by Johann-S** [comment]
Hi @tateman66,

Currently we started the developement of `v4` for a while, so it's a bit earlier to begin to remove jQuery as dependency.
But we thought about removing it for a next major release. Thank you to follow the developement of Bootstrap 👍
