### ISSUE TITLE
Modal DOC`S mistake

### ISSUE THREAD

**Issue by Oberetti** [twbs/bootstrap#22747]
![bs4 mistake modal](https://cloud.githubusercontent.com/assets/18064765/26753817/820102f4-4877-11e7-8fd8-e4f71d8a1777.png)

It seems a mistake in Doc`s. 
it must be: id="exampleModal" i think :)

**Comment by patrickhlauke** [comment]
already fixed a while ago. thanks https://github.com/twbs/bootstrap/pull/22437/files
