### ISSUE TITLE
Child flexbox set to 100% height of parent flexbox exceeds 100% height in Safari

### ISSUE THREAD

**Issue by EdGonzalez-** [twbs/bootstrap#22743]
Safari 10.1.1 on MacOS 10.12.5, and Safari iOS 10.3.2

In both mobile and desktop Safari, the child div in the screenshot below (white box) is set to 100% of its parent (red box), but the actual height is the height of the viewport (gray box). https://codepen.io/aeroapps/project/editor/XmbOYG/

![screen shot 2017-06-01 at 5 14 08 pm](https://cloud.githubusercontent.com/assets/10816717/26706002/c4e8b966-46ee-11e7-9543-41ed76413226.png)

In both Chrome and Firefox, the flexbox behaves as expected, filling only 100% of the height of its parent div:

![screen shot 2017-06-01 at 5 14 39 pm](https://cloud.githubusercontent.com/assets/10816717/26706008/db553378-46ee-11e7-8753-1100734bc384.png)

**Comment by EdGonzalez-** [comment]
Renders properly on Safari Technology Preview R31

<img width="959" alt="safari-preview-r31" src="https://cloud.githubusercontent.com/assets/10816717/26749956/27285766-47cc-11e7-80e5-e675ce86be36.png">

**Comment by mdo** [comment]
Closing as this isn't a Bootstrap bug, but a flexbox one that's fixed in an upcoming release. Sorry, I know that sucks, but reading up at https://github.com/philipwalton/flexbugs might help.
