### ISSUE TITLE
Inconsistent navbar classes naming

### ISSUE THREAD

**Issue by marko-avlijas** [twbs/bootstrap#22745]
Opposite of light is dark, not inverse. Dark is also shorter.

Please use class `navbar-dark` instead of `navbar-inverse`.

**Comment by Varunram** [comment]
@Johann-S May I put in a PR for this? Thanks!

**Comment by Johann-S** [comment]
Yes you can @Varunram but I'm not sure if this change will be accepted

**Comment by Varunram** [comment]
Thanks!

**Comment by mdo** [comment]
We use inverse for cards, navbars, tables, and background utilities. For now, we'll leave them as-is.

**Comment by Varunram** [comment]
Sure @mdo Thanks!
