### ISSUE TITLE
ios bug

### ISSUE THREAD

**Issue by wormen** [twbs/bootstrap#22754]
what a strange bug?
screenshots enclose

It seems that styles are not applied at all
Version 3.3.7 is used

![2017-06-05 11 40 38](https://cloud.githubusercontent.com/assets/8462339/26777067/2b6b4126-4a1f-11e7-9777-3418b83a7e7f.png)
![2017-06-05 11 41 18](https://cloud.githubusercontent.com/assets/8462339/26777066/2b6a5dc4-4a1f-11e7-8473-d9e2250086d5.png)
![2017-06-05 11 41 34](https://cloud.githubusercontent.com/assets/8462339/26777065/2b672816-4a1f-11e7-81af-be0f2fa9ffa6.png)

screenshots were made in the latest version of the simulator xcode for ios 5

in browser safari last version, analogous situation

**Comment by patrickhlauke** [comment]
please provide a reduced test case in jsfiddle, jsbin or similar. this is likely a problem with whatever else you're doing in your site/app, as 3.3.7 works just fine in iOS Safari.

**Comment by wormen** [comment]
@patrickhlauke Unfortunately I can not put the code on the specified services, since this application is using cordova

**Comment by patrickhlauke** [comment]
then i'm afraid we won't be able to help further on this. I'd suggest asking on stackoverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by wormen** [comment]
@patrickhlauke 
Cut out a piece of code
https://jsfiddle.net/wormen/grnhck2e/

But can see that it works really well
When leaping over protocol `file://` everything is different

**Comment by patrickhlauke** [comment]
I'm afraid we don't officially support this sort of embedding/use in Cordova/etc, so can't provide any help/support on that, sorry.
