### ISSUE TITLE
navbar toggler button - no hover icon

### ISSUE THREAD

**Issue by matejlednar** [twbs/bootstrap#22755]
cursor: pointer; is missing

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by patrickhlauke** [comment]
`cursor:pointer` was removed from buttons - see https://github.com/twbs/bootstrap/pull/21812

**Comment by matejlednar** [comment]
What's indicator (visual feedback for user) that element is clickable, e.g. any icon on the screen (difference between clickable icon and static background image / standard image)?
