### ISSUE TITLE
IE 11 closes popover when scrolling

### ISSUE THREAD

**Issue by GarrisonJ** [twbs/bootstrap#22759]
If you attempt to scroll a popover by clicking the scrollbar the popover will close.  This only happens in IE.

I also found this related StackOverflow post: https://stackoverflow.com/questions/35804982/ie-11-closes-bootstrap-popover-when-scrolling

This _also_ happens in bootstrap 3: https://github.com/twbs/bootstrap/issues/22757

- Bootstrap Version:   4.0.0-alpha.6
- Operating System:   Windows 8.1
- Browser:                  IE 11
- Reduced Test Case: https://codepen.io/garrisonjensen/pen/awOBwP

**Comment by XhmikosR** [comment]
@Johann-S: have you looked at the linked SO thread for the workaround? Should we do something similar ourselves?

**Comment by Johann-S** [comment]
I'm not sure 🤔 seems like a browser bug instead of something on our end (after reading the thread)

**Comment by XhmikosR** [comment]
Doesn't seem to happen for me on IE 11.
