### ISSUE TITLE
IE 11 closes popover when scrolling

### ISSUE THREAD

**Issue by GarrisonJ** [twbs/bootstrap#22757]
If you attempt to scroll a popover by clicking the scrollbar the popover will close.  This only happens in IE.

I also found this related StackOverflow post: https://stackoverflow.com/questions/35804982/ie-11-closes-bootstrap-popover-when-scrolling

- Operating System:   Windows 8
- Browser:                  IE 11
- Reduced Test Case: https://codepen.io/garrisonjensen/pen/LLEgPa

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

If you can reproduce this issue on our V4 do not hesitate to create a new issue 👍
