### ISSUE TITLE
Dropdown shown and hidden event not wait for CSS Transition

### ISSUE THREAD

**Issue by kudonguyen** [twbs/bootstrap#22760]
Dropdown have 2 event are shown.bs.dropdown and hidden.bs.dropdown and their description:

shown.bs.dropdown: This event is fired when the dropdown has been made visible to the user (will wait for CSS transitions, to complete).

hidden.bs.dropdown: This event is fired when the dropdown has finished being hidden from the user (will wait for CSS transitions, to complete).

And this is my demo: [DEMO](https://jsfiddle.net/uert78Lf)

But shown event alway trigger after show event and not wait for CSS transition or wait for the dropdown has been made visible to the user. Alert dialog alway display before dropdown-menu appear. Hidden event too. What's happen? Does it is bug? Or I went wrong something?

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

FYI In your demo you don't used the last V3 release (3.3.7). If you can reproduce this in V4 do not hesitate to open a new issue

**Comment by filipe-carvalho** [comment]
@Johann-S Here you have an example of the event (show.bs.dropdown being fired before the css transitions|css animations) on Bootstrap v4.3.1

https://jsbin.com/pejobaxilo/edit?html,output

Please check it out and see the problem related

Thank you
