### ISSUE TITLE
dropdown.js isActive problem

### ISSUE THREAD

**Issue by muguliebe** [twbs/bootstrap#22761]
### problem
in my case, when i click dropdown first,
dropdown doesn't work, because the variable 'isActive' is setted 'true' in dropdown.js

so, i think should change dropdown.js like below.

### filename: dropdown.js
``` javascript
      var isActive = $(parent).hasClass(ClassName.SHOW);

      Dropdown._clearMenus();

      if (isActive) {
        return false;
      }
```

### have to change
``` javascript
      if (!isActive) {
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by muguliebe** [comment]
### first
I'd try JS Bin [here](https://jsbin.com/huduvin/edit?html,output), but there is no bug happened. (using CDN)

so, my test page is [here](http://dev.egstep.com/#/test) build with webpack2
and i added this code in dropdown.js

``` javascript
 console.log('[dropdown.js] isActive:', isActive);
```
can show console log when click dropdown nav item..

### environment
chrome: 58.0.3029.110 (64-bit)
Bootstrap: 4.0.0-alpha.6
webpack: 2.6.1
bootstrap-loader: 2.1.0

**Comment by Johann-S** [comment]
Sorry we cannot help with third libraries, but It seem's better to use this : https://github.com/bootstrap-vue/bootstrap-vue because you use Vuejs and it use a Virtual DOM

**Comment by muguliebe** [comment]
@Johann-S ok thanks reply. i'll try use bootstrap-vue.
