### ISSUE TITLE
[v4 a6] Problem with .row in IE 10/11 and my solution

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#22765]
Maybe same as #22692 

![immagine](https://user-images.githubusercontent.com/20642463/26873423-11229be6-4b7a-11e7-9185-a2c6aa628456.png)

my code:

>       <div class="container">
>         <h2 class="section-title sr-only">In Primo Piano</h2>
>         <div class="carousel slide" id="headline-carousel" data-ride="carousel">
>           <ol class="carousel-indicators justify-content-end">
>             <li title="" class="active" data-target="#headline-carousel" data-slide-to="0"></li>
>             <li title="" data-target="#headline-carousel" data-slide-to="1"></li>
>           </ol>
>           <div class="carousel-inner" role="listbox">
>               <article class="headline-item carousel-item  active">
>                 <div class="row"> 
>                   <div class="col-md-6 headline-item-image">
>                     <figure><img alt="Altro appuntamento" src="/immagine?i=5197&amp;v=O&amp;t=28&amp;c=6&amp;s=88e13ef2abdaf388d0e7c7884852d7c7.jpg"></figure>
>                   </div>
>                   <div class="col-md-6 headline-item-body">
>                     <p><a class="headline-item-cat" href="/appuntamenti">Appuntamenti</a><br>12 aprile 2016 - 20 dicembre 2017</p>
>                     <a class="color-inherit" href="/appuntamenti/altro-appuntamento-5197-1-7fa590cce7ec5d46bc14c356bafc6280">
>                       <h3>Altro appuntamento</h3>
>                       <p class="headline-item-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit bibendum nibh, nec porta ipsum molestie ac. Aliquam erat volutpat....</p>
>                     </a>
>                   </div>
>                 </div>
>               </article>
>               <article class="headline-item carousel-item ">
>                 <div class="row"> 
>                     <div class="col-md-6 headline-item-image">
>                       <figure><img alt="Test 2" src="/immagine?i=1095&amp;v=O&amp;t=29&amp;c=6&amp;s=0d5510728368d25e4b92ce0e4258a535.jpg"></figure>
>                     </div>
>                   <div class="col-md-6 headline-item-body">
>                     <p><a class="headline-item-cat" href="/avvisi">Avvisi - Novità</a><br>7 ottobre 2017</p>
>                     <a class="color-inherit" href="/avvisi/2017/test-2-1095-1-1c58c65e5e726895c28af496e273a5a0">
>                       <h3>Test 2</h3>
>                       <p class="headline-item-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...</p>
>                     </a>
>                   </div>
>                 </div>
>               </article>
>           </div>
>             ...

my solution:
simply...
`<div class="row w-100">`
it works!

![immagine](https://user-images.githubusercontent.com/20642463/26874528-45af26b4-4b7e-11e7-9cc2-bde2b688e71d.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Closing due to lack of a reduced test case.
