### ISSUE TITLE
Spacing Utility for XS only does not work

### ISSUE THREAD

**Issue by Cruiser13** [twbs/bootstrap#22766]
I looked through the issues and did not find an open issue regarding this topic.
If I want to have a 2rem margin-top at an object for XS devices only, the way according to the docs would probably look like this:
`<div class="mt-2 mt-sm-0 mt-md-0 mt-lg-0 mt-xl-0">Testcase</div>`

In Firefox 53.0.3 (32-Bit) and Microsoft Edge 40.15063.0.0 (Windows 10 Pro) there will be a 2rem margin-top in all sizes though. The mt-2 class will override the other classes using !important. Since there is no mt-xs-2 class, overriding the mt-2 with the specific -0 classes for other sizes seems the only option.

Tested with Bootstrap 4 Alpha 6.

Any support would be great!

**Comment by Cruiser13** [comment]
Not reproducable in Fiddle, must be some issue in the implementation here. Nevermind.

**Comment by HeapCoder786** [comment]
I got what is happening. The mb-sm-3 only affects min-width of 576px so in mobile, iphone 6 for instance, min-width is less than 576 so what I needed to do was:
<div class="col-12 mb-3 mb-sm-0"></div>
This creates a margin bottom of 3 for below sm (xs in the case) and then sm and above get zero.
