### ISSUE TITLE
Docs are incorrect re: JS plugin defaults

### ISSUE THREAD

**Issue by abrahamguo** [twbs/bootstrap#22771]
According to the [documentation](http://v4-alpha.getbootstrap.com/getting-started/javascript/#default-settings), you can access the defaults for the JS plugins at `Constructor.DEFAULTS`; however, it appears that in v4 this has been renamed to `Constructor.Default`, e.g. `$.fn.modal.Constructor.Default`. The docs should be updated to reflect this change.

**Comment by Johann-S** [comment]
Good catch ! Feel free to open a PR to fix that 👍

**Comment by Varunram** [comment]
@Johann-S It seems alright in the markdown file over <a href="https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/javascript.md"> here.</a> What might be the issue?

**Comment by Johann-S** [comment]
You're right @Varunram thank you 👍 it's already fixed
