### ISSUE TITLE
Borders around <pre> <blockquote> and .badge in @media print

### ISSUE THREAD

**Issue by dumb** [twbs/bootstrap#22774]
For some reason `<pre>`, `<blockquote>` and `.badge` elements all have borders defined in _print.scss (for `<pre>` and `<blockquote>`, the border is `1px solid #999`, and for `.badge` it's `1px solid #000`).

### Example

Standard screen view:
![screen](https://user-images.githubusercontent.com/857046/26899557-77ba1fd2-4b9d-11e7-85e6-5089c3feb939.png)

Print view (from Safari's print dialog):
![print](https://user-images.githubusercontent.com/857046/26899570-80ed331e-4b9d-11e7-98db-e1c001cac279.png)

I'm happy to submit a pull request to fix this, since the borders don't seem to serve any purpose, but figured I should ask first... is there a good reason that these elements have borders defined?

**Comment by mdo** [comment]
I'm guessing this is supposed to be for when printing without backgrounds—you'd want some kind of indication that this is a special element.

**Comment by mdo** [comment]
Closing as a won't fix given above comment.
