### ISSUE TITLE
[v4] Toggleable fixed navbar does not scroll if there is overflow.

### ISSUE THREAD

**Issue by Evsthomas** [twbs/bootstrap#22777]
The navbar does not gracefully handle navigation menus that extend beyond the bottom of the screen. This is more noticeable on smaller mobile devices.
See example: http://jsbin.com/bufinawebu

**Comment by chiraggmodi** [comment]
this is because you have used fixed nav. Best and easy sollution is to add height and overflow property.
you can add this css...
`.fixed-top  .collapse{max-height: 100vh;overflow-x: auto;}`

**Comment by mdo** [comment]
Yup, you'll want to add your own height. We provided this in v3, but have opted to leave it out for now in v4 until we learn more how folks will use the new navbar.
