### ISSUE TITLE
Bug in grid .offset-* logic

### ISSUE THREAD

**Issue by stuartaccent** [twbs/bootstrap#22772]
The  comment for the`if` statement on line Within https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_grid-framework.scss#L59 suggests that `.offset-xs-0` is not being produced:

```
// `$columns - 1` because offsetting by the width of an entire row isn't possible
      @for $i from 0 through ($columns - 1) {
        @if not ($infix == "" and $i == 0) { // Avoid emitting useless .offset-xs-0
          .offset#{$infix}-#{$i} {
            @include make-col-modifier(offset, $i, $columns)
          }
        }
      }
```
however  assuming `.offset-xs-0` applies to `.offset-sm-0` etc, these will infact enter this `if` because it is still false in all the cases where the infix is not "".

A simpler solution might be as follows:

```
@for $i from 1 through ($columns - 1) {
     .offset#{$infix}-#{$i} {
          @include make-col-modifier(offset, $i, $columns)
     }
}
```
See https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L1287

**Comment by mdo** [comment]
As far as I can tell, this is working as intended. There's no need to offset by 0 at the `xs` level—you can however offset by `1` or more. At `sm`, you'll need the `0` to override a `xs` offset.
