### ISSUE TITLE
[docs] Layout, Responsive utilities has some old 544px value

### ISSUE THREAD

**Issue by iamandrewluca** [twbs/bootstrap#22775]
Layout, Responsive utilities has some old 544px value
https://v4-alpha.getbootstrap.com/layout/responsive-utilities/

![image](https://user-images.githubusercontent.com/1881266/26903382-92703800-4be5-11e7-847f-be8f3a68b9d9.png)

**Comment by mdo** [comment]
Already fixed in `v4-dev`. See #21664.
