### ISSUE TITLE
The rows of textarea be unchanged by JQ in IE

### ISSUE THREAD

**Issue by miaocunzhi** [twbs/bootstrap#22779]
We want to change the `rows` of `textarea` by jquery in IE browser, but `textarea`‘s height  can not take effect in time.We need to click on this `textarea` to get the focus, then it's height can be changed. So how would we go about solving this problem？

**Comment by catherine917** [comment]
Steps to reproduce:

1. Open this url http://getbootstrap.com/css/#textarea
2. Find the `textarea` control and open DevTools
3. Change `rows` attribute , but it dose not work 


Platform: Windows 7, iE 11.0.9600, Bootstrap 3.3.7

**Comment by patrickhlauke** [comment]
For "how-to" type questions (rather than feature requests and bug reports) please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
