### ISSUE TITLE
[v4] Safari doesn't break .col's when .row width runs out

### ISSUE THREAD

**Issue by mxmzb** [twbs/bootstrap#22788]
Open this link: http://jsbin.com/gahago/1/edit?html,css,output in Chrome (or any other mainstream browser) and Safari and try to resize the output width, to see the difference. Safari will just keep the columns always in one row (visually).

(Unrelated note to myself: I recently feel like Safari increasingly becomes the new Internet Explorer, that just wants to piss off web devs)

**Comment by jipexu** [comment]
what you expect it seems ok ..??

**Comment by mxmzb** [comment]
Dunno, but I see this in Safari:
<img width="318" alt="screenshot 2017-06-09 15 28 43" src="https://user-images.githubusercontent.com/1580455/26977524-7e4a7748-4d28-11e7-82b6-458281cdf97f.png">

While it looks something like this in Chrome:
<img width="374" alt="screenshot 2017-06-09 15 29 03" src="https://user-images.githubusercontent.com/1580455/26977526-80af85aa-4d28-11e7-825c-0fbcc9afe8b4.png">

**Comment by mdo** [comment]
What version of macOS and Safari?

**Comment by dkrnl** [comment]
mxmzb, i catch similar bug -- last Safari 10.1.1 (12603.2.4)

**Comment by mxmzb** [comment]
For me, it's macOS 10.12.5 and Safari 10.1.1 (both latest).

**Comment by jipexu** [comment]
huumm i dont understand with the code provided i  believed that with the col class it will never pass in  one column except if you have more than 12 div with col class ? whatever the class you have for the element ... or i miss something ?

**Comment by mxmzb** [comment]
@jipexu it's a flexbox feature and issue. .col should just fit as many columns in a .row as you put it by itself and give each column the same space. however, if the width of the .row becomes too low to still fit all the columns in they should break into new rows visually by themselves.

**Comment by mdo** [comment]
Near as I can tell, this is just flexbox in Safari I'm afraid. https://jsbin.com/piwakik/edit?html,css,output Closing as a can't fix unless someone has a reasonable workaround. Only thing I can suggest is to get rid of the `min-width` on the content within each column.

**Comment by ethicka** [comment]
Just ran into a similar issue and was able to workaround by using .col-sm instead .col. This turns off the flexbox for small width screens. Might work for others use cases. 

Modified the jsbin from @mxmzb as an example: http://jsbin.com/hexepifofi/1/edit?html,css,output
