### ISSUE TITLE
[Question] Should we provide a bundled release of Bootstrap with Popper.js

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#22783]
Hi folks,

Currently if you want to use Tooltips/Popovers and Dropdown, you should include Popper.js before Bootstrap and I think it's a huge drawback that you cannot just include Bootstrap and all the provided plugins doesn't work.

So a simple solution should be to provide a bundled release of Bootstrap with Popper.js included.
The size of our minified JS will increase of 16kb see my test : 

![js](https://user-images.githubusercontent.com/1689750/27172372-4afd176a-51b5-11e7-8037-7c6c70f057a5.png)

Is it a good solution for you ? Or should we continue to provide a release without Popper.js ? 

/CC @mdo

**Comment by acshef** [comment]
Why not both?

**Comment by Johann-S** [comment]
Yes that's a possibility 👍

**Comment by mdo** [comment]
Yikes, that's a 26kb increase, not 16kb. 😬  A 50% increase is pretty bad.

**Comment by Johann-S** [comment]
Yes a bit strange because Popper's weight is 19kb 🤔

**Comment by deandob** [comment]
Are tooltips that difficult that a 3rd party dependency is needed for bootstrap? Another thing to go wrong, additional load time (as needs to be loaded before bootstrap) is a disadvantage for v4. If it has to be a separate plugin, agree with Johann-S to provide a pre-bundled package.

**Comment by Johann-S** [comment]
It's a decision we made at the beginning of `v4` release, because they are a lot's of use case to handle for positionning Tooltips (scroll, overflow, ...)

**Comment by pat270** [comment]
I think it should be bundled with Bootstrap.js. Popper documentation is kind of confusing. I couldn't find a link to their cdn on https://popper.js.org/. I had to go to their github repo to find a link to the cdn which provides a confusing list https://cdnjs.com/libraries/popper.js, then pick and choose to find the right one.

**Comment by Johann-S** [comment]
Don't worry @pat270 we will provide the appropriate Popper.js link in our documentation 👍

**Comment by Sungodragon** [comment]
Maybe, it is better if its bundled release.
Perhaps someone can investigate to make the bundle size smaller. 
@vanduynslagerp

**Comment by Johann-S** [comment]
I have some issue to build our `dist` files that's, I fixed that and finally this is the correct screenshot : 

![image](https://user-images.githubusercontent.com/1689750/27172372-4afd176a-51b5-11e7-8037-7c6c70f057a5.png)

**Comment by FezVrasta** [comment]
@pat270 feel free to send PRs to improve the documentation if you feel like it needs some love 🙃

**Comment by Johann-S** [comment]
@FezVrasta I concatenated popper.min.js with bootstrap.min.js it was just a try to have folks feedbacks

**Comment by FezVrasta** [comment]
Oh, now I see, that's not the minified size, eheh

**Comment by Johann-S** [comment]
I tried to bundle Bootstrap with `rollup` (see : https://github.com/twbs/bootstrap/commit/f53ae934e8329b8d35319530b398cdade5bd443c) but it's gave me the same size : 

![image](https://user-images.githubusercontent.com/1689750/27219821-538afb6c-5283-11e7-8545-17b38f738c47.png)

After that, I tried to check other an other lib which use Popper.js and it's the same result.
This lib is tippyjs, if you check tippyjs dist files here : https://github.com/atomiks/tippyjs/tree/master/dist

`tippy.standalone.js` : is the dist file without Popper.js included, size : `13.9 KB `
`tippy.min.js`: is the dist file with Popper.js included, size : `31.5 KB `

And that's normal because : Popper.js size is ~18 KB

**Comment by bogdaniel** [comment]
Since it's a dependency should be installed when you install bootstrap .... i got it installed using yarn fast and quick .. and i'm also using webpack behind the scenes. :D

**Comment by sschueller** [comment]
For those of us that are still stuck using Bower. Popper does not include a compiled version of `popper.js` (https://github.com/FezVrasta/popper.js/issues/274) which makes the dependancy a pain. Even doing `bower install https://unpkg.com/popper.js` will not work and require you to make manual adjustments to `bower_components`.

Bundling it would help a lot of people

**Comment by mdo** [comment]
@sschueller We do the same with our Bower package fwiw. Their spec shied away from including built/compiled files within `main` if memory serves.

**Comment by CameronJ** [comment]
As sschueller mentioned, and I totally agree, that it should be bundled in.  I use Bower for dependency management and Popper doesn't support Bower (explained by not including dist files in the defect sschueller mentioned).  Also, I'm having trouble actually compiling them.  I was able to resolve this by manually getting the dependency from NPM, then using Grunt to move it into my bower directory. (Not exactly something I would like to do going forward...)

**Comment by DaleMckeown** [comment]
I really think that bower.json should remove popper.js as a dependency. 

![image](https://user-images.githubusercontent.com/1249673/29307827-45124382-819b-11e7-8488-97fda4249099.png)

While being in there as a dependency is *techically* correct, it serves very little purpose, as there is no dist folder. Ss mentioned above, building it yourself from source is a pain.

I resorted to just using CDNJS, in the end. It will just be a wasted dependency to most people.

FezVrasta flat out refuses to include a dist folder in the source. Apparently it's easier for him if everyone else goes elsewhere to get the compiled code (https://github.com/FezVrasta/popper.js/issues/274#issuecomment-322115796).

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/releases/tag/v1.12.0
https://github.com/FezVrasta/popper.js/issues/390

**Comment by CameronJ** [comment]
I understand your point FezVrasta, it is totally your call about which packaging systems you would like to use.  But as a consumer of Bootstrap via Bower, it is a problem for me/us.  For now, I am just overriding Bootstrap's dependency of Popper, and getting this via NPM (as mentioned above).  This isn't the end of the world, but it's definitely not a direction which I'd consider proper from a package / dependency management option, as it either A) forces me to commit all of my dependencies into the repository or B) use Grunt scripts to orchestrate NPM and Bower installations.

**Comment by CameronJ** [comment]
@FezVrasta: Out of curiosity, with your NPM publish you are sending all of the dist files, why could you not publish to Bower the same way?

**Comment by FezVrasta** [comment]
@CameronJ as explained in FezVrasta/popper.js#390, Bower have some serious limitations.

1. It requires the compiled files to be hosted in the GitHub repository (this means I have to mix source code with compiled code)
2. It doesn't support monorepos (repositories that host the code of several libraries like in the case of Popper.js)

While the first point can be a matter of preferences, the second point is a technical limitation that is preventing my project from distributing all the libraries stored under `/fezvrasta/popper.js` to Bower.

**Comment by CameronJ** [comment]
Yep, I agree.  The limitation of bower in both of those cases is troublesome.  Thanks for the reply

**Comment by slidenerd** [comment]
What you should add for v5 release is 0 dependency on Jquery and popper, 100% native js for all dom manipulation with cross platform quirks wherever required

**Comment by Johann-S** [comment]
It's already the case here : https://github.com/twbs/bootstrap/pull/23586 we work on it @slidenerd
