### ISSUE TITLE
Navbar collapsed dropup caret should point down

### ISSUE THREAD

**Issue by Hopper262** [twbs/bootstrap#22786]
When in collapsed mode, a navbar's dropdowns and dropups behave identically (opening down). However, the triangle indicator still reflects the non-collapsed behavior, which for dropups, points away from the content.

Here's a test case on alpha 6, based on one of the documentation examples: https://jsfiddle.net/2htxfvz1/

**Comment by Hopper262** [comment]
The following CSS fixes the issue in my own use cases:

    @media (max-width: 767px) {
    .navbar-toggleable-sm .dropup .dropdown-toggle::after {
      border-top: .3em solid;
      border-bottom: 0;
    }
    }
    @media (max-width: 992px) {
    .navbar-toggleable-md .dropup .dropdown-toggle::after {
      border-top: .3em solid;
      border-bottom: 0;
    }
    }

**Comment by Johann-S** [comment]
If you want that behaviour you should add `.navbar-expand`
This class prevent navbar from expanding.
In a mobile first design this is a normal behaviour

**Comment by Hopper262** [comment]
No, the behavior itself is working perfectly fine. This is about a visual glitch:

![caret-bug](https://user-images.githubusercontent.com/2176248/26985597-2da51d36-4d12-11e7-9be0-baff251a2798.png)

I would expect that arrow to point downward, since the full-width menu appears below the toggle.

**Comment by Varunram** [comment]
Correct me if I'm wrong, but in the example you've used the class `dropup` which specifies for the caret to be bottom up. On removing the same, it defaults to the behaviour expected. Any reasons why? Thanks!

**Comment by Hopper262** [comment]
This is a fixed-bottom menubar. At desktop window sizes, the menus appear horizontally and I do want them to open upward toward the middle of the screen. At mobile resolutions, there's no behavioral difference between `dropdown` and `dropup`, but there's a valid reason to select the latter for desktops.

Basically, the problem is that the responsive behavior switches the direction of dropup menus at certain screen sizes, but it fails to switch the direction of the caret.

**Comment by Varunram** [comment]
Thanks for your clarification! Made it more clear for me to approach the same.
