### ISSUE TITLE
Carousel images distorted in Chrome

### ISSUE THREAD

**Issue by nurkka** [twbs/bootstrap#22781]
In Bootstrap v4 Alpha 6, when using a carousel within a col, images are distorted in Chrome, when they are bigger than the available space and have to be scaled down.

In Bootstrap `.carousel-item` is styled as `display: flex`. Chrome doesn't scale images with the correct aspect ratio within a flexbox. Instead it stretches them vertically. I think this is also the case for other browsers, but I only tested this issue with Chrome and Firefox, of which the latter scales the images correctly.

To fix this issue for Bootstrap Carousels, you can add `align-items: flex-start;` to `.carousel-item`:

See example here:
https://jsfiddle.net/k689hdko/3/

The carousel in the example is from the docs: 
https://v4-alpha.getbootstrap.com/components/carousel/#with-indicators

**Comment by Johann-S** [comment]
Can you try with our last `dist` files ? I think this issue is already fixed

**Comment by Johann-S** [comment]
It seems it works well on Chrome with our last `dist` files, see : https://codepen.io/Johann-S/full/vZNQgG/
Can you confirm that @nurkka ?

**Comment by nurkka** [comment]
Thanks Johann-S, it works with the last files - mine were from june 2nd.
