### ISSUE TITLE
HTML5 validation look and feel does not match with Bootstrap

### ISSUE THREAD

**Issue by binarykitchen** [twbs/bootstrap#22785]
When I pass on the HTML5 attribute `required` to a FormControl like that (in React):

```js
<FormControl
  required={required}
  {... input}
>
  {this.props.children}
</FormControl>
```

and submit that then this HTML5 validation error text pops in:

![screen shot 2017-06-09 at 11 40 06](https://user-images.githubusercontent.com/177641/26955085-6f36ae5e-4d08-11e7-939b-656c2bb0a0c0.png)

which does not match with the usual Bootstrap look and feel.

Using react-bootstrap v0.31.0 here which uses bootstrap v3.3.x and using latest Chrome v59 on Mac OS Sierra here.

I expect that kind of error text to be shown in the ControlLabel instead. Or at least make use of HTML's native `setCustomValidity()` and wire it with Controllabel? Not sure if that's doable ...

**Comment by mike3run** [comment]
@binarykitchen every browser styles those differently if you really need them looking just like you want you're gonna have to use your JS and CSS skills

**Comment by binarykitchen** [comment]
well, it is technically possible to fix this all in JS alone, to extract the native error message and redirect it to any control label

**Comment by mike3run** [comment]
that is true, its also true that those who care about that usually also don't want the default bootstrap look on their website, i guess you're always open to submit a PR

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements. 
We shouldn't help you on third library, but form validation is in a complete rewriting in V4 so do not hesitate to give us some feedbacks

**Comment by binarykitchen** [comment]
@Johann-S ok, understand. but for a starter, you should be using HTML5 attributes when possible, i.E. `required` (I could count many reasons why), and use `setCustomValidity`, this to redirect the error message from a popup to your choice.

**Comment by mike3run** [comment]
hey man its okay, you can set a PR on the v4 branch.

**Comment by binarykitchen** [comment]
yeah i can but that's a too big PR when looking at my avail time in the next weeks

**Comment by TheBuzzer67** [comment]
Is there something I can do to help?

**Comment by binarykitchen** [comment]
thanks but i really dont have the time due to familiar circumstances. just can point to this API for now
https://developer.mozilla.org/en-US/docs/Web/API/ValidityState

whenever input changes, parse validation state from that API and display its contents on your error label or whatever similar.
