### ISSUE TITLE
[v4] How will ml-auto and mr-auto be handled for RTL

### ISSUE THREAD

**Issue by ciar4n** [twbs/bootstrap#22780]
As Joomla will use BS4 for the next major version it would be good to know how you intend to handle the mr-auto and ml-auto classes in RTL? Knowing would help avoid any B/C breaks for when Bootstrap introduces RTL support.

**Comment by mdo** [comment]
We don't have RTL support right now and I don't know what would change for these utilities at this point. My hunch is that they won't be dependent on the text direction as utilities are immutable.
