### ISSUE TITLE
Problem with collapse navigation

### ISSUE THREAD

**Issue by afuno** [twbs/bootstrap#22795]
Example: https://jsfiddle.net/0j5prt9e/2/

Why initially it looks like a navigation on small screens? It is collapsed. This code is taken from the documentation.

Rails 5.1
Bootstrap [Rubygem](https://github.com/twbs/bootstrap-rubygem)

**Comment by patrickhlauke** [comment]
what do you mean "initially"? from what i can see, it only collapses when the window/browser isn't wide enough.

**Comment by mdo** [comment]
Looks like it's working as intended—navbars are collapsed to start and expand when clicked.

**Comment by afuno** [comment]
@mdo In your documentation the navigation initially is not minimized. In my example it is collapsed. Why? Screenshot:
<img width="871" alt="2017-06-12 12 42 55" src="https://user-images.githubusercontent.com/2853419/27028202-bf3b4f66-4f6c-11e7-9d24-2ce61b5eb6ac.png">

**Comment by patrickhlauke** [comment]
whether the nav is collapsed or expanded depends on the width of the *document*, not the width of the navbar itself.

in the documentation, it's shown expanded because the whole browser window / document width is below the 992px media query threshold. in the jsfiddle (since it uses iframes), the width of the live results part of the fiddle is below the 992px width, which triggers the collapse.

**Comment by afuno** [comment]
@patrickhlauke At me too most in the project which I now develop. This link is just an example of an error.

**Comment by jdno** [comment]
I have exactly the same issue. The navbar is always collapsed, independent of the width of the document.

This is what I did to reproduce the issue:

1. Create new Rails app
2. Install `bootstrap` gem
3. Add `navbar` to application layout
4. Generate view

I uploaded the test app here that demonstrates the issue: https://github.com/jdno/bootstrap4-navbar-test

**Comment by mdo** [comment]
Your markup is incorrect from the latest in `v4-dev`. Revisit our latest docs and source code in our dev branch and you should be fine.

Also, a Rails app isn't a reduced test case :D. Next time, if possible, all we need is a JS Bin or JSFiddle link to view your code in our browsers :).

**Comment by jdno** [comment]
Thanks I'll check it out. Thought you already have a fiddle, so I did the app. 😆
