### ISSUE TITLE
$container-max-widths must be in ascending order - Why can't they be equal?

### ISSUE THREAD

**Issue by bryankang** [twbs/bootstrap#22796]
I only have 2 widths, one for mobile and one for everything else. Is there a better way to achieve this? Or is this warning necessary for when they're equal?

**Comment by mdo** [comment]
If they're equal, they're also not ascending and would therefore not be separate container widths.

**Comment by bryankang** [comment]
I understand they're not separate. But how would you specify only two sizes?

**Comment by bryankang** [comment]
I understand they're not separate. But how would you specify only two sizes? @mdo

**Comment by bryankang** [comment]
Looks like all you had to do was specify the size for `sm` and delete the other sizes. Sorry for slight annoyance!
