### ISSUE TITLE
Unexpected alignment in 100%-width dropdowns

### ISSUE THREAD

**Issue by readonly** [twbs/bootstrap#22803]
When setting a v4 Dropdown to 100% width (e.g. on the `.dropdown-toggle`), the content remains centered. The open dropdown itself is left-aligned though. Shouldn't the button content be left-aligned as well?

Also, if I manually left-align the .dropdown-toggle content by applying `text-align:left`, the triangle also gets left aligned, but should be to the very right of the area IMHO.

codepen: https://codepen.io/readonly/pen/jwrZro
first dropdown = original
second dropdown = only width changed
third dropdown = width + alignment changed

affected versions: all os/browsers, bootstrap v4-alpha6

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Also, we don't have a `.dropdownMenuButton` class...

**Comment by readonly** [comment]
added a codepen plus corrected class name

**Comment by Varunram** [comment]
I get the part where you want to align the text to the left if the width is 100%. But, I don't quite understand what you mean when you say
> the triangle also gets left aligned, but should be to the very right of the area IMHO

**Comment by readonly** [comment]
Like in a `<select>`, a user would probably expect the triangle that indicates an item is a dropdown always to be to the far right of the button/box/dropdown shape. This also makes UIs more consistent where multiple dropdowns of the same size are below each other. In the current implementation, the triangle "wobble" depending on the length of the string in the dropdown, but it should IMHO be consistently always to the far right.

**Comment by Varunram** [comment]
Got it. Thanks for the clarification. @Johann-S This sounds acceptable? If so, may I work on this?

**Comment by mdo** [comment]
You can align it that way if you wish—we're inserting that arrow via `::after` in CSS. If you need something this wide that behaves more like a form control, I'd suggest using an actual `<select>`. For now though, we'll leave this as-is.
