### ISSUE TITLE
Components modal doc wrong html id

### ISSUE THREAD

**Issue by davidbonting** [twbs/bootstrap#22802]
Hi,

I have to open an issue, because I cannot find the code myself in this repo.

at the [components model doc](https://v4-alpha.getbootstrap.com/components/modal/#live-demo) the 
`data-target="#exampleModal"`

should be
`data-target="#myModal"`

I hope someone else can fix it.

Thanks,
David

**Comment by Johann-S** [comment]
Already fixed by : #21671
Available in our futur release
