### ISSUE TITLE
Triangle missing in .dropdown when it's size is too small

### ISSUE THREAD

**Issue by readonly** [twbs/bootstrap#22812]
codepen: https://codepen.io/readonly/pen/LLZQeO

When a `.dropdown` can't have it's natural size but has to be smaller (e.g. by applying a width, or the button's content is simply too large), the dropdown-triangle is pushed outside the box and overflow-hidden. 

Suggestion: make sure the triangle never leaves the box, plus maybe ellipsise the button's content. 

affected browser/os: all
bootstrap version: v4-alpha6

**Comment by mdo** [comment]
There's not really a way around this other than for you to wrap the inside of the button—it's text—with it's own `overflow: hidden` instead of putting it on the button itself.
