### ISSUE TITLE
Badges inside flex container look incorrect

### ISSUE THREAD

**Issue by matthiassiegel** [twbs/bootstrap#22825]
https://codepen.io/anon/pen/YQGxeq

If parent container has `display: flex`, labels appear larger and text is top aligned.

I tried using the flex helper classes but it doesn't seem to make a difference.

There is a related issue where the same problem can be seen, but the question there was about element alignment, not badge appearance: https://github.com/twbs/bootstrap/issues/21963

Tested with `v4-alpha6`, in Chrome/Firefox/Safari on macOS Sierra.

**Comment by mdo** [comment]
Add `.align-items-center` or `align-items: center;`. You're seeing the default styles for flexbox override the badge. We _could_ apply some extra styles to the badges (`inline-flex` and `align-self`), but that's largely unnecessary in most cases.
