### ISSUE TITLE
Navbar that shouldn't expand, expand

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#22831]
It seems we broke the navbar because currently navbar expand by default when it shouldn't expand see : 

https://codepen.io/Johann-S/full/owYgLR/

/CC @mdo

**Comment by TheBuzzer67** [comment]
Works on Firefox 53.0.3 on mac

**Comment by Johann-S** [comment]
I took the examples here : https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/examples/navbars/index.html

**Comment by Johann-S** [comment]
Finally I understood, my bad sorry for /CC
