### ISSUE TITLE
Bug in relation to dropdownlist

### ISSUE THREAD

**Issue by jt4000** [twbs/bootstrap#22832]
http://jsbin.com/gacapicana/edit?html,output

When you use the dropdownlist, the menu dont appear in the right position.

Please take a look at the link

It is bootstrap v3

Thank you!

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

FYI this is fixed in `v4`
