### ISSUE TITLE
Docs: scrollbar on top navigation on small screens

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#22846]
If browser window is resized below a certain size, a scrollbar appears for the main top navigation (in Edge, Chrome, Firefox...).

![edge-nav-scroll](https://user-images.githubusercontent.com/895831/27252719-1feccef4-535d-11e7-896d-089461943552.PNG)

**Comment by Varunram** [comment]
@patrickhlauke What were the exact windows dimensions at which this happens? Trying to reproduce the issue, so it'd help a lot. Thanks!

**Comment by patrickhlauke** [comment]
window width below 992px
