### ISSUE TITLE
Grid System, No support for Bootstrap Version 3.3.7 for Chrome

### ISSUE THREAD

**Issue by aayusharora** [twbs/bootstrap#22840]
- Grid system is not working with bootstrap 3.3.7. All other bootstrap classes works fine. 
## Additional details 
Not able to get the inbuilt `float` and `width` properties of `col-*-*`

When reporting a bug, include:
- Operating system Mac OS X
- Browser and version - Chrome Version 58.0.3029.110 (64-bit)

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
