### ISSUE TITLE
3.3.7 Thumbnail Not Mixin

### ISSUE THREAD

**Issue by markaplet** [twbs/bootstrap#22841]
In file `bootstrap/less/thumbnails.less` comment line says this is a mixin, but its missing the parenthesis. I believe this line should be `.thumbnail() {...}` 

As is, the `.thumbnail` class is greedy and not applicable to boostraps naming convention of `.img-thumbnail`

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
