### ISSUE TITLE
comment incorrect

### ISSUE THREAD

**Issue by 50774283** [twbs/bootstrap#22861]
Windows 7
Chrome up-to-date
Bootstrap  alpha 6

The link:
https://v4-alpha.getbootstrap.com/layout/grid/

Stack the columns on mobile by making one full-width and the other half-width 

It should 50% and 50% when working on level  sm and xs.
So I think the comment incorrect.

![bootstrap2](https://user-images.githubusercontent.com/16589080/27259005-8f9d8b60-543b-11e7-97ab-770a19f90d1c.PNG)

**Comment by mdo** [comment]
> So I think the comment incorrect.

What comment?

**Comment by mdo** [comment]
Ah, apologies. This has been fixed in v4-dev already.
