### ISSUE TITLE
Grid behavior incorrect

### ISSUE THREAD

**Issue by 50774283** [twbs/bootstrap#22867]
Chrome newest
Bootstrap 4.0.0-alpha.6

The link:
https://v4-alpha.getbootstrap.com/layout/grid/

In section Grid options.
Grid behavior ---》  Horizontal at all times   《-----Extra small
Why it is not horizontal when using iPhone 4(viewport width 320)?
Thank you.

![boot](https://user-images.githubusercontent.com/16589080/27289155-8dc51870-553b-11e7-95eb-31ab63964414.PNG)

**Comment by bkdotcom** [comment]
Based on your screen shot, I'd say it's horizontal.  (col1 and col2 are side-by-side)
vertical:   col2 would be underneath col1

**Comment by 50774283** [comment]
I am completely understanded now.
Thank you very much bkdotcom.
Share a song with you.
The link:
http://www.le.com/ptv/vplay/27082081.html
May be Ads playing before the music.
