### ISSUE TITLE
jquery selector  DATA_TOGGLE : '[data-toggle="collapse"]' invalid

### ISSUE THREAD

**Issue by nelisbijl** [twbs/bootstrap#22865]
data-xxx selectors are no valid jquery selectors.
This results in the event handler being called for every click.
The preventDefault call than stops any further processing (in my case the submit handler of a form, is never called)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.
