### ISSUE TITLE
Collapse click handler should only call preventDefault when a target was found

### ISSUE THREAD

**Issue by nelisbijl** [twbs/bootstrap#22866]
version 4.0.0-alpha.6

event.preventDefault is called regardless of whether a target is found.
In case no target exists, it prevents other code from being executed

https://codepen.io/anon/pen/eRvgYq

**Comment by Johann-S** [comment]
Fixed in our current code base see : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L364
And in Alpha6 : https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.6/js/src/collapse.js#L360

**Comment by nelisbijl** [comment]
No it is not, have you tried it?

**Comment by Johann-S** [comment]
Yes my bad 👍
