### ISSUE TITLE
custom-radio and label for attribute

### ISSUE THREAD

**Issue by koukou73gr** [twbs/bootstrap#22871]
In a Rails project, following the Bootstrap template for a custom radio button, I would write (in Slim):
```slim
    = f.label :preferred, class:"custom-control custom-radio" do
      = f.radio_button :preferred, 1, class: "custom-control-input"
      span.custom-control-indicator
      span.custom-control-description Preferred
```
and this would produce the following HTML:

```html
    <label class="custom-control custom-radio" for="gd_site_velocity_profiles_attributes_1497948625874_preferred">
       <input class="custom-control-input" value="1" name="gd_site[velocity_profiles_attributes][1497948625874][preferred]" id="gd_site_velocity_profiles_attributes_1497948625874_preferred_1" type="radio">
       <span class="custom-control-indicator"></span>
       <span class="custom-control-description">Preferred</span>
     </label>
```

Pardon the strange id and naming, this is straight out of my project.

The thing is, this HTML results in an unclickable radio button.

As soon as I take away the *'for'* attribute from the *'label'* element the radio button works as expected. The for value can apparently be anything, as longs as it is present the button is unclickable.

So, what am I missing? Why would the presence of an attribute have such an effect? Should it be mentioned in the documentation?

I am using 4.0.0-alpha6.

Thanks,
-Kostas

**Comment by koukou73gr** [comment]
Here's a generic live page you can test what I'm talking about. 

https://www.quackit.com/bootstrap/bootstrap_4/tutorial/bootstrap_custom_forms.cfm

Scroll to the radio-button example, change the HTML to add a for attribute in one of the radio-buttons and run the example again. One button can be clicked, the other not.

**Comment by alanstratos** [comment]
If you add an empty `for=""` it stops working because the label cannot find the element it's supposed to work with. If you add `for="somethingNotTheId"` it won't work because of the same thing. However if your radio input has an id of `id="radio1"` then you must use `for="radio1"` so it finds the element it's supposed to tick.

**Comment by mdo** [comment]
> In yor example it seems the weird id and for don't match. Look at them carefully.

Yup, likely this.

**Comment by koukou73gr** [comment]
This is how standard RoR form helpers produce element IDs. They look strange because this form has nested attributes. I didn't mess with them, honest. 

If I remove Bootstrap classes, leaving just the bare input type="radio" element inside the label element the radio button can be clicked w/o problem even if the for/id differ (by the input value).

Thanks for steering me in the right direction though.
