### ISSUE TITLE
Chrome details element doesn't correctly propagate box-sizing

### ISSUE THREAD

**Issue by andrewbelcher** [twbs/bootstrap#22872]
There is a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=589475&q=details%20box-sizing&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) where inheritance of box-sizing does not happen correctly with the `details` element. This results in all `input` (and every other element that is `width: 100%`)  overflowing the `details`.

This is demonstrated by [this codepen](https://codepen.io/andrewbelcher/pen/mwWZEM).

The solution is to add:
```
details > * {
  box-sizing: border-box;
}
```

Would post a PR, but can't get grunt working locally and don't have time to fix it now.

**Comment by mdo** [comment]
> Would post a PR, but can't get grunt working locally and don't have time to fix it now.

We're off Grunt now and on npm scripts :). Pull the latest, update bundler, `npm install`, and you should be good to go.

**Comment by prateekgoel** [comment]
I think the above solution will be specific to input elements.
I think, the better solution is to change box-sizing: inherit; to box-sizing: border-box;
Like this:

```
*, *:before, *:after {
  box-sizing: border-box;;
}
```

I would like to make this change.
