### ISSUE TITLE
Navbar toggle button is under .navbar-brand in window-width < 576px [4.0.0-alpha.6]

### ISSUE THREAD

**Issue by memboc** [twbs/bootstrap#22877]
This issue on examples page https://v4-alpha.getbootstrap.com/examples/navbars/

![eobfbzautoqgjmiswb4scw 1](https://user-images.githubusercontent.com/7403119/27375152-f2e44424-5676-11e7-9659-1ef5481a3cf5.png)

**Comment by obinnangini** [comment]
See [22817](https://github.com/twbs/bootstrap/issues/22817)

**Comment by Johann-S** [comment]
Closed thanks to the previous comment 👍
