### ISSUE TITLE
Documentation is not fully responsive

### ISSUE THREAD

**Issue by amgc** [twbs/bootstrap#22881]
https://v4-alpha.getbootstrap.com/content/images/

On my mobile (Huawei P9 lite) and also on Chrome for 320px images page is not properly responsive, content is overflowing for about 2px. Probably because container has 15px margin, but `bd-example bd-example-images` has 1rem, and it is not consistent. Will it be fixed?

**Comment by FelixRilling** [comment]
Right now the `.bd-example` class uses the following for alignment:
```css
padding: 1rem;
margin: 1rem -1rem;
```
This causes the inconsistency in question.

Using
```css
padding: 1rem 0;
margin: 1rem 0;
```
instead seems to fix this. I did *not* test if/how this would affect other parts of the documentation.

**Comment by mdo** [comment]
In v4-dev this looks fixed.
