### ISSUE TITLE
Checkboxes and radio buttons are not responsive

### ISSUE THREAD

**Issue by catchmareck** [twbs/bootstrap#22880]
Hey there, 

I was just looking at your documentation about checkboxes and radio buttons and noticed that on mobile they are not responsive. I checked them out also in your package and noticed the same thing. What I mean is when I place the buttons on my page the horizontal scroll appears on mobile (the same as on your documentation page). Shouldn't they break in the new line or something?

OS: Android 5.0.2 Lollipop
Browser: Chrome 58.0.3029.83

**Comment by Johann-S** [comment]
Can you specify which documentation ? v3 or v4 ?

**Comment by catchmareck** [comment]
Sure, it is v4

**Comment by mdo** [comment]
There's no really good way to design those to be responsive in a way that suites everyone. You have to choose how and where you use certain components for however you build your site/app.
