### ISSUE TITLE
Using data-toggle on a <label> with an <input> prevents default functionality

### ISSUE THREAD

**Issue by callumstrubi** [twbs/bootstrap#22885]
Using `data-toggle` on a `<label>` with a `<input type="radio|checkbox">` prevents default functionality of the input toggling between the items.

OS: MacOS Sierra
Browser: Safari

JSBin:
https://jsbin.com/selasukami/edit?html,css,output

v4 alpha-6 Bootstrap

**Comment by trusche** [comment]
Confirmed that this is still ongoing in 4.0.0-beta. I do recall a similar issue with a lengthy discussion but cannot find it now. It would be good to know if this is expected behaviour I have to work around, or a bug that might get fixed. 

Loving bootstrap! :heart:

**Comment by Johann-S** [comment]
That's due to : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js#L265

**Comment by XhmikosR** [comment]
@Johann-S: is this still valid?

**Comment by Johann-S** [comment]
Yep still valid

**Comment by mdo** [comment]
Do we close this as a won't fix for v4? Still an issue in v4.5.x: https://jsbin.com/coguvof/edit?html,output.

Unclear if we need to do anything for v5 here either...

**Comment by XhmikosR** [comment]
Must be present on v5 too:

https://github.com/twbs/bootstrap/blob/7e6d7b8f817ad1212238f15124335d37c93ebfea/js/src/tab.js#L205

Patches welcome to allow this case.

**Comment by GeoSot** [comment]
I think that in 5-beta3 is ok, (yes  I admit I cannot understand it ).
In any case I made one more Pr

**Comment by alpadev** [comment]
> I think that in 5-beta3 is ok, (yes I admit I cannot understand it ).
> In any case I made one more Pr
> 
> Example of beta-3: https://jsbin.com/hekipumuvi/edit?html,output

I think you have to use data-bs-target but it's **not** caused by the event.preventDefault(). There is simply no implementation for this exact case. If you step through the debugger you can see the radio is selected but then changes back.

**Comment by mdo** [comment]
@GeoSot Do you want to tackle this as a change in v5, or do we leave it as-is?

**Comment by patrickhlauke** [comment]
This sort of pattern https://jsbin.com/selasukami/edit?html,css,output seems to try and do two things at the same time. The controls should *either* be tab controls, *or* radio buttons...not both. As such, I'd suggest this is not a pattern we'd want to fix/support nor encourage in our code.
