### ISSUE TITLE
Is Carousel in Bootstrap 4 Beta compatible with IE 11?

### ISSUE THREAD

**Issue by jluisgarcia** [twbs/bootstrap#22882]
Hi,
Is Carousel compatible with Internet Explorer 11 in Bootstrap 4?
The transitions inside
`<div class="carousel-caption d-none d-md-block">`  <br>dont work properly.

Thanks

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by jluisgarcia** [comment]
Here is the Pen: https://codepen.io/jlgarcialopez/pen/dRWrqv
Look at the text, at the bottom of the page. 
This is the most noticeable place to see that something is wrong. But you can see also that the image does not slide. It is failing with Internet Explorer 11. 
Chrome and FF work fine.
Thanks

**Comment by TheWebAuthor** [comment]
This still doesn't work. When can we expect an update?

**Comment by martindohko** [comment]
You can try to specify the compatibility mode in the document header with:
`<meta http-equiv="X-UA-Compatible" content="IE=11" />`
