### ISSUE TITLE
Is there any hard deadline for Beta? 

### ISSUE THREAD

**Issue by numbertree** [twbs/bootstrap#22889]
Hi guys, 

First of all - awesome work. I watching progress since long time and I can't wait to when Beta will be released. 

I've seen that recently progress jumped to 99% few times, but later it again went down. The same happened 2 days back. Of course, I can understand that there are new things popping out which has to be taken care but I just wanted to ask you guys do you have any hard deadline (i.e. June 30th) when no matter what issues Beta will be released and new issues will be handled in next release? 

And second questions - what else has to be done as it seems that all related issue are already fixed so I wonder what is last 1% about and if I can somehow contribute to reach 100% as soon as possible :)

**Comment by Herst** [comment]
>  I wonder what is last 1% about

https://github.com/twbs/bootstrap/milestones and https://github.com/twbs/bootstrap/projects/3 (esp. *In progress* there) might point you in the right direction.

**Comment by mdo** [comment]
There's no date. Project and milestone have a few open ended items in there that I still have to wrap up.
