### ISSUE TITLE
[Bug] col-auto is overflowed with nested long text in google chrome

### ISSUE THREAD

**Issue by xfg** [twbs/bootstrap#22899]
The `col-auto` is overflowed when it has nested cols with long content. I had created [a live demo](https://codepen.io/xfg/pen/xrLrGM) on codepen.

This occurs because col-auto have `flex-shrink` equal to `0`, but I think that the `flex-shrink` for `col-auto` should be equal `1`.

Browser: google chrome version 59
System: ubuntu 16.04.2 LTS

**Comment by Borkason** [comment]
According to the docs:

> Thanks to flexbox, grid columns without a set width will automatically layout with equal widths

and:

> ### Auto-layout columns
> Utilize breakpoint-specific column classes for equal-width columns. Add any number of unit-less classes for each breakpoint you need and every column will be the same width.

[Source](https://v4-alpha.getbootstrap.com/layout/grid/#auto-layout-columns)

There is [no mention of `.col-auto` in the documentation](https://www.google.de/?gws_rd=ssl#q=%22col-auto%22+site:v4-alpha.getbootstrap.com).

If anything, I believe `.col-auto` must be removed from the source code.

**Comment by mdo** [comment]
I think this is the behavior that we'd expect. If a `.col-auto` is the only child of a row, it can occupy a maximum of the entire row. This behavior isn't limited to Chrome, too. You'll want to take a different approach with the markup and perhaps use different predefined grid classes.

**Comment by sniepoort** [comment]
@mdo I'd like to re-open this, as you mention that a `col-auto`, if an only child of a row, should occupy a maximum of the entire row. However, even as an only child, if the viewport is smaller than what can fit in a column (for example, a long text), the column still overflows. I'm guessing that's because `max-width` is set to none. I'm not sure why that is?
