### ISSUE TITLE
[Feature] Display utilities 

### ISSUE THREAD

**Issue by realappie** [twbs/bootstrap#22898]
After looking at PR [22113](https://github.com/twbs/bootstrap/pull/22113), I at first thought these classes were introduced.

```d-{breakpoint}-none``` which would equal 5 new classes, but after building something based on that knowledge, I realised only `d-none` and `d-md-none` exist. And that if I were to want to hide something on mobile for example, I would have to use this combination of classes

```d-none d-sm-flex d-md-flex d-lg-flex d-lg-flex``` Instead of just `d-xs-none`

I could be wrong on how I want to hide something just on mobile, but if Im not I would like to propose the following four css classes that are pretty much self explanatory.

- `d-xs-none`
- `d-sm-none`
- `d-lg-none`
- `d-xl-none`

This would make hiding an element on a certain breakpoint much easier, Im also willing to submit a PR my self if my proposal is accepted.

**Comment by mdo** [comment]
We have `.d-sm-none` and the like, they just don't operate how you'd like—they hide from `sm` and up, not for just `sm`. What you can do though is use just two classes: `d-none d-sm-flex`.

**Comment by realappie** [comment]
@mdo But what if I want to hide something only on mobile?

**Comment by mdo** [comment]
Use `d-none d-sm-block` (or `-flex`, `-inline`, etc).
