### ISSUE TITLE
Date Input buttons become vertically oriented in Input Groups

### ISSUE THREAD

**Issue by quinton-ashley** [twbs/bootstrap#22894]
<img width="442" alt="screen shot 2017-06-22 at 11 02 20" src="https://user-images.githubusercontent.com/20031683/27448720-a45cffca-573a-11e7-99ad-779a6e9e17da.png">

```Pug
div.input-group.input-group-sm.col-4.m-0.p-1
	div.input-group-addon Birth
	input.form-control(type='date' value=scan.PatientBirthDate)
```

I don't know if this a bug or if there is an option to keep the buttons in a horizontal row?  Loving version 4 of Bootstrap btw, keep up the good work devs!

**Comment by quinton-ashley** [comment]
https://codepen.io/qashto/pen/vZZwWw

Version 4.0 Alpha 6
Chrome 58.0.3029.110
macOS 10.12.5

**Comment by mdo** [comment]
This was fixed in v4-dev I believe: https://codepen.io/anon/pen/BZdNro.

**Comment by quinton-ashley** [comment]
Thanks!

**Comment by Nokel81** [comment]
When will this make it to a release?
