### ISSUE TITLE
Form-inline class on fieldset

### ISSUE THREAD

**Issue by md384** [twbs/bootstrap#22903]
Since updating to alpha6 from alpha4 a `fieldset` with the `form-inline` class is no longer displayed inline.

See https://jsbin.com/hewokovako/edit?html,output for example.

I only want a section of my form to be inline hence the use of `form-inline` on a `fieldset` instead of the `form`.

**Comment by mdo** [comment]
This is a flexbox bug: https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers.
