### ISSUE TITLE
stacking context issue, bootstrap dropdown zindex not working properly

### ISSUE THREAD

**Issue by nutangwari** [twbs/bootstrap#22900]
I am using bootstrap dropdown inside a div of limited height, I want to keep the height of this div fixed so that my footer is always visible even if the content of the div keeps on increasing.

to do that i have added overflow:auto to div, now whenever i click on dropdown it adds scrollbar to the div and dropdown list is cutting off.

    <div style="overflow:auto; height:100px;>
    <div class="col-lg-12">
      <form>
        <div class="col-lg-6">
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
          <span class="caret"></span></button>
        <ul class="dropdown-menu pull-right">
          <li><a href="#">HTML</a></li>
          <li><a href="#">CSS</a></li>
          <li><a href="#">JavaScript</a></li>
        </ul>
      </div>
    </div>
  </form>
</div>
    </div>
Attached Plunkr demo:

https://plnkr.co/edit/yeSqTMLyjn36g1VrFNC7?p=info

Note: I want to keep the height of container fixed, and i want the dropdown list to be on top (stack context high in dom).

Thanks.

**Comment by asyncdesign** [comment]
Change overflow: auto to overflow: none. The dropdown needs to overflow any containing element.

**Comment by asyncdesign** [comment]
Do you want your footer to stick to the bottom of the page? If so do the following:
Remove overflow: auto and add the fixed-bottom class on the footer.

If you want the footer to stay under your fixed height div, then remove overflow: auto and use sticky-bottom class on the footer instead.

**Comment by mdo** [comment]
No way around this unless you change your HTML or your CSS. Make the `overflow: visible` or try a different approach, I'm afraid.
