### ISSUE TITLE
Importing mixins in partials

### ISSUE THREAD

**Issue by theetrain** [twbs/bootstrap#22911]
Scope: Bootstrap 4 SCSS

I noticed the scss partials often `@include` mixins that are in the **mixins/** directory. If I decide to import a specific Bootstrap component or layout, such as:

```scss
@import "./node_modules/bootstrap/scss/navbar";
```

It would result in a compiler error since the [mixins](https://github.com/twbs/bootstrap/blob/f640ec96622790237bf0a5659440eb726af3118b/scss/_navbar.scss#L35) referenced in **_navbar.scss** are not imported. I'm curious if there is a reason not to `@import` mixins in each scss partial. Otherwise, I see value in being able to selectively import partials without having to think about which mixins to import as well.

**Comment by mdo** [comment]
We import everything into the master Sass files like `bootstrap.scss`. If you only need a subset of components, I heavily suggest including the first three imports from there—functions, variables, and mixins. We do the same with our `bootstrap-grid.scss` file.
