### ISSUE TITLE
Multiple buttons with glyphicon

### ISSUE THREAD

**Issue by vincent3569** [twbs/bootstrap#22914]
Hi

with Bootstrap 3.3.7, there is an issue with Multiple buttons using Glyphicon. Buttons do not have the proper height or align properly with the input box.

in fact, this issue can ba saw in boostrap documentation: http://getbootstrap.com/components/#input-groups-buttons-multiple 

tested with FF ESR 45.2.0 and IE11.

FF
![screenshot018](https://user-images.githubusercontent.com/1224809/27580209-4392d626-5b2a-11e7-8b11-b591b710cdb1.png)

IE
![screenshot019](https://user-images.githubusercontent.com/1224809/27580208-439223fc-5b2a-11e7-9bed-d0f8addf795b.png)

Maybe linked with https://github.com/twbs/bootstrap/issues/22690

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by vincent3569** [comment]
no workaround for v3 ?

**Comment by Johann-S** [comment]
Currently there is no plan to release new version of Bootstrap v3 because we have to ship the first beta of Bootstrap v4

**Comment by vincent3569** [comment]
Of course I understand that.
But there is a gap between make a new release of Bootstrap v3 to fix minor issues and think about a workaround or a tip that can be applied by users of Bootstrap v3.

I have asked a question on stackoverflow: maybe, somebody can help me (and of course the boostrap community) to solve this issue:
https://stackoverflow.com/questions/44782513/bootstap-v3-layout-issue-with-multiple-buttons-with-glyphicon

**Comment by vincent3569** [comment]
I found a fix to this issue.
You can see it in action here: https://www.bootply.com/mtNO2DGZTW
