### ISSUE TITLE
Forms - Selects - Multiple Select cmd/shift click controls

### ISSUE THREAD

**Issue by nstanard** [twbs/bootstrap#22929]
Freature Proposal: Improved Multiple Select controls. 

This one:
```
<select multiple class="form-control">
  <option>1</option>
  <option>2</option>
  <option>3</option>
  <option>4</option>
  <option>5</option>
</select>
```

Using command/control and shift to select the multiple items does not behave in the _exact_ manner I expect. MacOS finder is a great example of how it should behave IMO. 

Current behavior: select the first option, command click the 3rd option, and then shift click the 5th option. The remaining selected items are 3 through 5. I expect the first option to be selected still. 

Proposed behavior: Select first option, command click the 3rd option, and shift click the 5th option should result in the following options being highlighted/selected: 1, 3, 4, and 5.

_I was unable to find an existing issue related to this_

**Comment by mdo** [comment]
The `<select>` element is a native browser element, so we won't be making any changes to that. We default to the browser/OS.
