### ISSUE TITLE
Horizontal Scrollbar + Responsive Table + Microsoft Edge

### ISSUE THREAD

**Issue by PerseusTheGreat** [twbs/bootstrap#22920]
Horizontal scrollbar does not move on responsive table (`<table class="table table-responsive">`) on Microsoft Edge.
It works (Both v3.3.7 & v4.0.0-alpha.6) on IE11(11.0.43 KB4021558) , FireFox 54.0, Chrome 59.0.3071.115 
I am using Windows 10 x64 (1703 build 15063.413) + Edge 40.15063.0.0 (EdgeHTML 15.15063)

**Comment by cr101** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by PerseusTheGreat** [comment]
You can try/test/watch the official samples of official Bootstarp websites:

- [Responsive tables of version 4 alpha 6 official sample](https://v4-alpha.getbootstrap.com/content/tables/#responsive-tables)
- [Responsive tables of version 3.3.7 official sample](http://getbootstrap.com/css/#tables-responsive)

**Comment by patrickhlauke** [comment]
Looks like a strange Edge bug. Confirmed.

![edge-overflow-scroll-bug](https://user-images.githubusercontent.com/895831/27614191-fdeb8e10-5b97-11e7-885a-97f0faded7c0.png)

Removing the `-ms-overflow-style: -ms-autohiding-scrollbar` directive from `.table-responsive` fixes this, but obviously that leaves the scrollbar visible.

**Comment by patrickkettner** [comment]
This isn't replicating in Edge 16, and while I haven't finished reducing this it does seem limited to the docs page itself, rather than the same table with bootstrap

**Comment by PerseusTheGreat** [comment]
I have created a test page on JS Bin ([Here](https://jsbin.com/loyajivequ/1/edit?html,output)).
It seems every things are well on MS Edge 15.
Thanks to your attentions.
So, I am waiting to debugged version of B.S. docs.

**Comment by mdo** [comment]
So can this be closed if Edge 16 is fine?

**Comment by patrickkettner** [comment]
the underlying issue that is causing the problem would be great to figure out, especially since it will be a while before most are upgraded to that version.

**Comment by ysds** [comment]
Since fixed in #28153, closing this.
