### ISSUE TITLE
Problem with \n become <br>

### ISSUE THREAD

**Issue by Buisson** [twbs/bootstrap#22924]
I have a problem when using BootstrapDialog constructor.

here is my code :

```
$("#test").click(function(){
            $.post({
                type: "POST",
                url: 'somescript.php',
                data: data,
                success: function(data){
                    var dialog = new BootstrapDialog({
                        message: function(){
                            return data;
                        },
                        closable: true
                    });
                    dialog.open();
                },
                error: function(jqxhr){
                    alert("Problem");
                },
            });
        });
```

The script 'somescript.php' return a form with a script javascript in it with '\n'. But when it try to display the BootstrapDialog changing my \n by `<br />` and so my script crash.

How can I remove the replacement of \n by `<br />`  if it is possible. Thank you.

**Comment by Johann-S** [comment]
Sorry but it's the wrong repository, see : https://github.com/nakupanda/bootstrap3-dialog
