### ISSUE TITLE
Collapse js multiple targets

### ISSUE THREAD

**Issue by wtorsi** [twbs/bootstrap#22925]
Hi,

In bootstrap3 `collapse.js` has excited opportunity of collapsing multiple elements. 
This example will collapse all spans:
```html
<a href="#" data-toggle="collapse" data-target=".collapsible-element">
toggle
</button>
<span class='.collapsible-element'>collapsible</span>
<span class='.collapsible-element'>collapsible</span>
<span class='.collapsible-element'>collapsible</span>
```

But in `bootstrap  v4.0.0-alpha.6` this code will not work properly.
This code is not working because of these lines of code in dist files:
```javascript
Collapse._getTargetFromElement = function _getTargetFromElement(element) {
      var selector = Util.getSelectorFromElement(element);
      return selector ? $(selector)[0] : null;
};
```

Is this code going to be changed for multiple targets?

**Comment by Johann-S** [comment]
Added in our next beta see : https://github.com/twbs/bootstrap/pull/22713

**Comment by wtorsi** [comment]
Thank's for reply
