### ISSUE TITLE
Dropdown in navigation bar glitches at mobile breakpoint (v3)

### ISSUE THREAD

**Issue by wkeithvan** [twbs/bootstrap#22928]
The nav bar has a glitch with rending dropdown menu items when the browser is at exactly 767px as seen in this [JSBin](http://jsbin.com/benucuyoza/edit?html,output) (click the dropdown link so that the menu hovers down and then slowly stretch the output window between 760-770px to clearly see the issue). To reproduce this issue, make sure you read my display settings note at the bottom. If you can't reproduce, here is an [animated gif](http://imgur.com/a/YxFxw) of the glitch.

Instead switching from the desktop dropdown style at 768px+ to the mobile dropdown style at 767px- (like every other element does), the dropdown switches to the proper mobile style at 766px. This means that when the browser window is 767px, it renders a the mobile menu for everything except the dropdown, which is rendered in desktop mode.

I've tested this on
- Chrome 58 (Problem exists)
- Firefox 54 (Problem exists)
- Edge 40 (No problem)
- IE 11 (No problem)

**Important Note:** My screen is 1920x1080 and I am using the Windows 10 recommended display setting of 125% ( Setting > Display > Change size of text, apps, and other items > 125%). This issue goes away with my settings at 100% (but exists at every other size), however, since I am using a default Windows 10 Home install on a standard laptop screen size with the default/recommended display settings, this issue likely affects a lot of people. This is especially pronounced by the fact that 767px happens to be the half window size (Windows Key + Left arrow or Windows Key + Right arrow) for a 1920x1080 screen at 125%, so every time I snap my window to half size, this issue is clearly visible on my website.

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

_This is a saved reply._
