### ISSUE TITLE
No division lines between List Group Items within Card 

### ISSUE THREAD

**Issue by RubenJG** [twbs/bootstrap#22927]
I'm trying to use a List Group within a Card just as in the example from the [docs](https://v4-alpha.getbootstrap.com/components/card/#list-groups):

```
<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
</div>
```

But it doesn't show all the division lines between list group items. Here is a screenshot from the official docs:

![image](https://user-images.githubusercontent.com/2113642/27659759-ea5b8f1a-5c11-11e7-8a6a-6de3960637d1.png)

I'm using Chrome 59.0.3071.115 (Official Build) (64-bit) (cohort: 59_115_Win) and Windows 8. 

The thing is that I tried to reproduce the issue in Firefox and it works well there, so it has to be something related to cross browser support.

**Comment by alecpl** [comment]
I see no issue in Chromium 58.0.3029.110 Built on Ubuntu.

**Comment by RubenJG** [comment]
Can you try with this snippet?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
  </head>
  <body>
	<div class="card">
	  <ul class="list-group list-group-flush">
		<li class="list-group-item">Cras justo odio</li>
		<li class="list-group-item">Dapibus ac facilisis in</li>
		<li class="list-group-item">Vestibulum at eros</li>
	  </ul>
	</div>
  </body>
</html>
```

(This is how I see it)
![image](https://user-images.githubusercontent.com/2113642/27690703-55285f84-5c9f-11e7-8c54-c6fa054c4acb.png)

It's a weird error, because with the snippet above, the division lines are missing between the first and second `li` elements but you can see them between the second and third. But if you keep adding `li` elements and you try this snippet:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
  </head>
  <body>
	<div class="card">
	  <ul class="list-group list-group-flush">
		<li class="list-group-item">Cras justo odio</li>
		<li class="list-group-item">Dapibus ac facilisis in</li>
		<li class="list-group-item">Vestibulum at eros</li>
		<li class="list-group-item">Vestibulum at eros</li>
		<li class="list-group-item">Vestibulum at eros</li>
		<li class="list-group-item">Vestibulum at eros</li>
		<li class="list-group-item">Vestibulum at eros</li>
		<li class="list-group-item">Vestibulum at eros</li>
	  </ul>
	</div>
  </body>
</html>
```

(This is how I see it)
![image](https://user-images.githubusercontent.com/2113642/27690752-68089510-5c9f-11e7-9e57-8ac822886fe9.png)

Eventually you get to see division lines between all elements

Also if you have other cards in the page, the issue seems to fix it self. It seems to only happen when you have like the minimum amount of elements. If I add another card somewhere in the page it works...

I've been looking at the css, but I don't know which style generates that line...

**Comment by RubenJG** [comment]
I just saw that there is a `border: 1px solid rgba(0,0,0,.125);` applied to the class `.list-group-item`. If I change that to something like `border: 1px solid rgba(0,0,0,1);` I get to see all the lines... Maybe it could be like a Chrome issue...

**Comment by RubenJG** [comment]
I think that this might be just a hardware issue. I just asked a partner who was the exact same setup as me and it happens to him as well. But I asked two other partners with different laptops, but the same Chrome and they don't see the issue...

I think this can be closed. It must be a problem with my laptop.
