### ISSUE TITLE
Modal example in docs is broken

### ISSUE THREAD

**Issue by abrahamguo** [twbs/bootstrap#22923]
The "Live Demo" modal example in the documentation (http://v4-alpha.getbootstrap.com/components/modal/#live-demo) is broken because the `<button>` references a modal with an `id` of `exampleModal`, while the `id` of the modal is `myModal`. Thus, this example doesn't work.

**Comment by Johann-S** [comment]
Already fixed by : #21671 and will be available on our next release, thanks 👍
