### ISSUE TITLE
Missing semicolon in Scss grid example on getbootstrap.com

### ISSUE THREAD

**Issue by pawelkleczek** [twbs/bootstrap#22931]
https://v4-alpha.getbootstrap.com/layout/grid/#sass-mixins

Missing semicolon after $grid-gutter-widths map.
Causing minor problems with outsourcing code to css.

<img width="485" alt="bug" src="https://user-images.githubusercontent.com/20242777/27681929-176512ce-5cc1-11e7-8074-84580f0fe3cd.png">

**Comment by mdo** [comment]
I just nuked this part of the docs, so closing out. Thanks though!
