### ISSUE TITLE
Suggestion: Create Inverse Class For code Element

### ISSUE THREAD

**Issue by hokiecoder** [twbs/bootstrap#22937]
With many/most components in Bootstrap there is an inverse variant that flips the background & foreground contrast. However, the `<code>` element does not have one. The `<code>` element is always presented with a white background and red text, regardless of the parent element having a light or dark background. On a dark background, it is a bit of an eye sore, in my opinion. Example:
```html
<div class="card card-inverse card-success">
    <div class="card-block">
        <p class="card-text">
            This is an example using <code>.card-success</code>.
        </p>
    </div>
</div>
```

I am proposing that an inverse variant be created for `<code>`, perhaps `.code-inverse`? There are numerous ways this can be accomplished, but here is what I came up with that, in my opinion, works well against darker (but not close to black) backgrounds:
```sass
code.code-inverse {
    background-color: rgba($black, 0.1);
    color: rgba($white, 0.99);
}
```
I used the `rgba()` SASS function to generate the RGBA values so that if the browser is old enough to not support alpha, it will just ignore the color properties and look the same as it does now. I played around with the alpha of the black background color and found 0.1 to be my preferred sweet spot that roughly equals the difference in alpha that `<code>` currently has on a light background.

Something similar could also be done for the `kbd` element for when the background color approaches black.

**Comment by prateekgoel** [comment]
I would like to take a change and work on this.

**Comment by mdo** [comment]
Going to punt on this—when Beta 1 ships, you can use the `.badge-dark` on `<code>`.
