### ISSUE TITLE
Fixed bottom navbar hides dropdown content

### ISSUE THREAD

**Issue by WilliamMayor** [twbs/bootstrap#22935]
I have a page with a fixed navbar on the bottom. If a dropdown menu expands over the navbar then it renders underneath the navbar so there are always buttons you can't press.

This behaviour has been noticed on macOS (latest Firefox), and Windows (latest Chrome).

I think I have a fix for this. Set the `.dropdown-menu` to have a z-index of 1040.

Does this fix work? Am I overlooking anything?

Thanks!

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by WilliamMayor** [comment]
Whilst I understand the need for test cases and greater detail, you're placing a greater burden on the bug reporter than I would have thought healthy. Does this not put people off contributing bug reports? At the very least your saved reply could be friendly.

Here's an example: https://jsbin.com/pedawumeza/edit?html,output

You have to shrink the browser window until the expanded dropdown clips the navbar.

I don't have the exact details of the Windows machine where this bug was first reported. I do have the details of my machine.

macOS 10.12.5
FirefoxDeveloperEdition 55.0b3 (64-bit)
Bootstrap v4.0.0-alpha.6

**Comment by mdo** [comment]
> Whilst I understand the need for test cases and greater detail, you're placing a greater burden on the bug reporter than I would have thought healthy.

Reliably reproducing something is the first step in verifying it is in fact a problem :). We don't know what's in your extended setup, how you're using Bootstrap, what version you're using (latest prerelease? dev branch?), or anything else. It's as much a burden on maintainers who have to hunt things down with fewer problems.

> Does this not put people off contributing bug reports?

I hope not! It's the barebones information we need to help :).

> At the very least your saved reply could be friendly.

I'm open to iterating on it, though I did say please ;).

---

Thank you for the demo! Despite everything I just said, I should've looked closer at your post to understand what you're running into. Bootstrap has a list of `z-index`s in it's variables that provides a preferred stacking order:

```scss
// Z-index master list
//
// Warning: Avoid customizing these values. They're used for a bird's eye view
// of components dependent on the z-axis and are designed to all work together.

$zindex-dropdown:           1000 !default;
$zindex-sticky:             1020 !default;
$zindex-fixed:              1030 !default;
$zindex-modal-backdrop:     1040 !default;
$zindex-modal:              1050 !default;
$zindex-popover:            1060 !default;
$zindex-tooltip:            1070 !default;
```

As you can see from here, we anticipate dropdowns residing underneath the navbars. You can change these values as you need and recompile, or override them with custom CSS.

Hope that helps, and thank you for the example—it immediately showed me what you were running into so I could help <3.
