### ISSUE TITLE
[hidden] display:none Conflict with RevealJS transitions.

### ISSUE THREAD

**Issue by Glidias** [twbs/bootstrap#22941]
https://github.com/hakimel/reveal.js/issues/1515

The `[hidden]` selector code doesn't play well in "special" cases of using that attribute to determine custom (possibly animated) states. 

I guess it's a matter of customising reboot scss for one's own use? On a sidenote, can `_reboot` be safely omitted entirely without any repucussions on bootstrap dependencies?

**Comment by mdo** [comment]
No planned changes to the attribute, and yes, Reboot is required.
