### ISSUE TITLE
Navbar collapse showing up on normal screen

### ISSUE THREAD

**Issue by lauroengineer** [twbs/bootstrap#22957]
I have the current bootstrap version install on Rails 5.2. With all of the dependencies installed. 
 
I added a navbar and it shows up as a mobile view. I'm using Google Chrome and Safari, and the error persists. 

Is this a feature or a bug? 

![](http://i.imgur.com/s26NNcr.png )

**Comment by mdo** [comment]
Navbar is mobile-first in v4 now—you'll need to specify when it unfolds with a `.navbar-expand` class. See the latest in our `v4-dev` branch's docs.

**Comment by lauroengineer** [comment]
Thanks @mdo!
