### ISSUE TITLE
Small error in documentation (responsive utilities)

### ISSUE THREAD

**Issue by KrisGielen** [twbs/bootstrap#22968]
Unless I don't understand how it works, I think there is a small error in the one but last paragraph of https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/migration.md#responsive-utilities
It states:

> You can combine one .d-*-none class with one .d-*-block class to show an element only on a given interval of screen sizes (e.g. .d-none.d-md-block.d-lg-none shows the element only on medium and large devices).

However, I think it should read:

> You can combine one .d-*-none class with one .d-*-block class to show an element only on a given interval of screen sizes (e.g. .d-none.d-md-block.d-**xl**-none shows the element only on medium and large devices).

**Comment by mdo** [comment]
The paragraph is correct as-is.

With `.d-none.d-md-block.d-lg-none`, the element is hidden to start, hidden at `sm`, shown at `md`, and hidden again at `lg` and up (`xl`).

**Comment by KrisGielen** [comment]
@mdo exactly, but the statement says "shows the element only on medium **and large** devices). As you rightfully state, the `current .d-none.d-md-block.d-lg-none` does **not** show it on large devices.
The example is about "a given interval of screen sizes", so therefore I think it still should be `d-none.d-md-block.d-xl-none`.

**Comment by alanstratos** [comment]
While we understand how the classes work, I too believe the paragraph is not right. 

Read carefully: (e.g. .d-none.d-md-block.d-lg-none shows the element only on medium and large devices).

It should be fixed to "shows the element only on medium devices)."

Or update `d.none.d-md-block.d-xl-none` to match the description. Either fix the classes or fix the description.

**Comment by mdo** [comment]
Oh shit, totally missed that part.

**Comment by KrisGielen** [comment]
Thx! :)
