### ISSUE TITLE
[Bug] Css media width when half pixel

### ISSUE THREAD

**Issue by Keither** [twbs/bootstrap#22967]
@media (max-width: 991px)
.hidden-md-down {
    display: none!important;
}

@media (min-width: 992px)
.hidden-lg-up {
    display: none!important;
}

with window have width 991.5px, sorry my english very bad
thanks!

**Comment by mdo** [comment]
Nothing we can do about this, sorry. Closing as a can't fix.

**Comment by patrickhlauke** [comment]
one thing we *could* do is increase the precision, so the second query could go with `min-width: 991.001px` or similar. ugly, but would catch most of these situations (until browsers properly support range queries - see https://github.com/patrickhlauke/csswg-drafts/commit/d2dae8cb1a44c64494d3c3ee01d2695daa1fa2bf)

**Comment by mdo** [comment]
Not sure it's worth the trouble :\.

**Comment by patrickhlauke** [comment]
i'll add that fractional viewport widths are becoming slightly more common with higher density android and windows devices (with fractional `dpr` values), and that the effect can also happen when triggering browser zoom values like 150% (which yes, i know we're not officially supporting). the danger with BS' particular CSS is that if the current viewport does fall between the two values, you get to a page where both , say, `.hidden-md-down` and `.hidden-lg-up` are not displayed at the same time.
