### ISSUE TITLE
Remove position: static from dropdowns in navbar

### ISSUE THREAD

**Issue by mattonit** [twbs/bootstrap#22976]
Is there a reason to use `position: static;` for dropdowns in navbar? I use code from `v4-dev` and it works fine, but it causes a problem in your new website

The problem isn't visible in `v4-dev` because Popper set the position of the dropdown to absolute (as it should be). Previously my PR (#22010) was rejected because you said that was intentional to use `position: static`, but when currently it's fixed by popper.js

Here's what I'm talking about:
![image](https://user-images.githubusercontent.com/4998725/27785303-7751403a-5fdd-11e7-910a-4d048f4d55fd.png)

And without `position: static;`
![image](https://user-images.githubusercontent.com/4998725/27785321-86c7d9d4-5fdd-11e7-8d4e-6bab36d25ec7.png)

Isn't that better?

Tested on latest Chrome, Win 7/Win 10/Ubuntu 17.04/OS X Sierra 10.12.5

**Comment by Johann-S** [comment]
It seems that's because our documentation navbar don't have `.navbar-expand` to prevent expanding our should have a `.navbar-expand-sm` to expand only on small device

**Comment by zalog** [comment]
Hi there @mattonit, I understand but please take a look at my [comment](https://github.com/twbs/bootstrap/pull/22782#discussion_r122175913).

**Comment by gijsbotje** [comment]
@Johann-S i've been looking around but the docs layout files aren't accessible without writing access aren't they?
wanted to make a pr to fix this

**Comment by Johann-S** [comment]
If you are looking for the docs layout everything is here : https://github.com/twbs/bootstrap/blob/v4-dev/_includes/

**Comment by gijsbotje** [comment]
@Johann-S jup, thanks i'll get to work
got the PR up
