### ISSUE TITLE
Hamburger Menu is not collapsing

### ISSUE THREAD

**Issue by sachithhm** [twbs/bootstrap#22982]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://validator.w3.org/nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by envolute** [comment]
If you are using dist/js/bootstrap.min.js, use bootstrap.js instead. I did this and it worked!!
I think there is a problem with the minified file.

**Comment by Johann-S** [comment]
Please can you add some contexte here ?

**Comment by envolute** [comment]
I believe the problem is not with the "hamburger menu". But with the "collapse" component.
I updated the files and it stopped working. So, instead of using the "dist/js/bootstrap.min.js" file, I used the "dist/js/bootstrap.js" that was most recently edited.
After that the collapse started to work again.
So, i think there is a problem with the minified file.

**Comment by patrickhlauke** [comment]
We need to know what version of bootstrap this affects. We also need to have a minified demo showing the problem. Otherwise we're unable to help.

**Comment by envolute** [comment]
Sorry for the delay.
Well, i updated my version yesterday, when I checked the problem.
But remembering that who created the problem was @sachithhm . I just checked that the collapse component did not work when i used the "bootstrap.min.js" file located in the "dist/js" directory.
It worked again when i called the not minified "bootstrap.js" file instead "bootstrap.min.js"...

Sorry for my bad English!!

**Comment by envolute** [comment]
Well, I upgraded right now using the latest version of the "bootstrap.min.js" file and it worked fine. I do not know if it will work for @sachithhm , but for me the problem is solved !!

**Comment by undying-fish** [comment]
Getting this problem myself after I compiled from source a week or two back.
```
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <!--<img src="/Content/img/LogoHorizontal.svg" height="30" width="auto" alt="Logo" />-->
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/Observations">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Observations/New">New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Observations/List">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Admin</a>
                </li>
            </ul>
        </div>
    </nav>
```
I'll try the updated JS - currently using latest 4.0.0alpha6 from NuGet.

**Comment by envolute** [comment]
> Well, I upgraded right now using the latest version of the "**bootstrap.min.js**" file and it worked fine.
