### ISSUE TITLE
Grid System not working Properly

### ISSUE THREAD

**Issue by arvindkalra** [twbs/bootstrap#22983]
I was using the bootsrap grid system to make a web page... but when i wrote col-lg-12 the div area formed is bigger that the width of the browser page....
![bootstrap](https://user-images.githubusercontent.com/29686907/27814945-eecef682-609d-11e7-8fbe-f03451a5008d.png)
Bootstrap grid system is used for responsive designing but it itself is creating a horizontal scroller... So how can the page be responsive....

**Comment by envolute** [comment]
Show html code!

**Comment by arvindkalra** [comment]
![boot](https://user-images.githubusercontent.com/29686907/27815767-4fed5566-60a4-11e7-92df-c7c20bc338d5.png)
![boots](https://user-images.githubusercontent.com/29686907/27815766-4fe72d8a-60a4-11e7-8761-60cd684e5656.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by arvindkalra** [comment]
CodePen.io Link : https://codepen.io/anon/pen/qjYKQd
Bootstrap Version : 3.3.7
Google Chrome : Version 59.0.3071.86 (Official Build) (64-bit)
O.S. : Ubuntu 16.04

**Comment by envolute** [comment]
You did not add the container <div class="container"> ou "container-fluid"

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
