### ISSUE TITLE
Issue with printing a page containing an accordion

### ISSUE THREAD

**Issue by ajsmith27** [twbs/bootstrap#22988]
When I print a page containing a Bootstrap accordion in Chrome, a blank page is added to the end of the printout. 

As part of my investigation in to this issue, I navigated to the accordion example on the Bootstrap website in Chrome (http://getbootstrap.com/javascript/) and entered print preview mode where I was able to also see the issue. I don't see this issue in IE or Firefox within either my application or the Bootstrap website. If you access other pages on the Bootstrap website, without the accordion, there are no blank pages at the end of the printout (see: http://getbootstrap.com/components/, http://getbootstrap.com/css/, http://getbootstrap.com/customize/, http://getbootstrap.com/getting-started/).

Not sure whether this is a Bootstrap or Chrome issue. Could it be looked at please?

Chrome version: Version 59.0.3071.115 (Official Build) (64-bit)
Bootstrap version: v3.3.7

Thanks.

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
