### ISSUE TITLE
The utility class ".border" is using a "fixed" color

### ISSUE THREAD

**Issue by envolute** [twbs/bootstrap#22993]
The class ".border" (css/utilities/_borders.scss) is set the border-color to "$gray-200".
So I see that it would be nice to create a variable for the border color "$border-color". Because the default border should not always be "gray-200".
Another thing, there is a "$border-width" variable. Would not it be better to use this variable to set the default width of the border?

In this case we would have in "_variables.scss"
```
$border-width: 1px !default;
$border-color: $gray-200 !default;
```
And in "_borders.scss"
`.border { border: $border-width solid $border-color !important; }`

**Comment by gijsbotje** [comment]
might i suggest classes like `.border-success` and `.border-danger`?

**Comment by envolute** [comment]
If you're talking about classes like ".border-success, .border-primary, .border-danger", they are already defined!
The question here is referring to the "default" border. Let's say I want the default border to be darker, something like gray-400. The way it is has no way to change without an additional class or change the file "_borders.scss" (which I would not do)
Well, this change is quite obvious to me. I think, for my part, it was more a warning than a suggestion ...

**Comment by gijsbotje** [comment]
aah sorry, you're. i hadn't noticed them untill now
as for your issue, i agree
