### ISSUE TITLE
Custom checkbox issues

### ISSUE THREAD

**Issue by undying-fish** [twbs/bootstrap#22999]
It seems that when toggling the state of a custom checkbox, the state of the actual checkbox does not change. My code is as follows:

 ```
<div class="checkbox col-lg-4 align-self-center text-center">
            <label class="custom-control custom-checkbox">
                <input class="custom-control-input" data-val="true" data-val-required="The Resolved field is required." id="Observation_Resolved" name="Observation.Resolved" type="checkbox" value="true"><input name="Observation.Resolved" type="hidden" value="false">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">Resolved at point of observation?</span>
            </label>
        </div>
```

My diagnosis is that no matter the state of the custom checkbox, False is always returned upon submission. For some extra context, the second checkbox is generated by `@Html.CheckBoxFor()` in ASP.NET MVC 5 Framework. When watching the state of the HTML on the page, neither input is affected by clicking the custom checkbox.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by undying-fish** [comment]
[Reduced test case](https://codepen.io/anon/pen/xrzQLw)

Bootstrap ver. 4.0.0-alpha6

OS/Browser: Windows 10 running Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by undying-fish** [comment]
I've realised that this may not be a problem with Bootstrap itself but is probably more to do with how the submission to the form itself takes place.
