### ISSUE TITLE
Is .col-form-label really necessary?

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#22992]
There are two ways to order form fields.

In one column where field label and form field are on two rows,

```html
<form>
  <div class="form-group">
    <label for="formGroupExampleInput">Example label</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input">
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Another label</label>
    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
  </div>
</form>
```
... or in two colums, where field label and form field are in the same row.

```html
<form>
  <div class="form-group row">
    <label for="formGroupExampleInput" class="col-form-label">Example label</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input">
    </div>
  </div>
  <div class="form-group row">
    <label for="formGroupExampleInput2" class="col-form-label">Another label</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
    </div>
  </div>
</form>
```

I wonder why I need to assign `.col-form-label` class to my `<label>` when building forms in two colums (second example)? Shouldn't this be taken care of by Bootstrap? Seems really unnecessary to put the classes in, when I already assigned the parent `<div>` or `<fieldset>` the `.row` class (`class="form-group row"`).

Is this a technical requirement, or what is the reason for this double-assignment?

**Comment by herbalite** [comment]
To me it seems they are 2 different ways  to display a form, 

On FF 54.0.1 on a Win 10 machine the 2 examples show differently for me. (I did put the markup above direct under a body tag)

The first example puts the label text above the input box.

The second one puts everything into a row, plus it doesn't matter if I use .col-form-class or not.

If you get the same results for both forms, why not create a fiddle?

**Comment by mdo** [comment]
`.col-form-label` is only there to vertically position the label in horizontal forms.

**Comment by Borkason** [comment]
> .col-form-label is only there to vertically position the label in horizontal forms.

@mdo I built two forms in a [JSFiddle](https://jsfiddle.net/h3pu46sn/) and while `.col-form-label` does indeed vertically position the label in a horizontal form. That does not apply to `<textarea>`.

If you are omitting the class, the label aligns at the top. The visual difference is almost non-existent, even to larger rows like text areas.

In fact, omitting `.col-form-label` actually makes the form look unbalanced or "wrong". Hence my question.

My suggestion is that `.col-form-label` should be removed and worked into the form by default, if the parent div has both classes `.form-group .row`.

![btsp](https://user-images.githubusercontent.com/2971735/28016343-3ed6d8ea-6574-11e7-8c76-b915aaffbaff.png)

https://jsfiddle.net/h3pu46sn/
