### ISSUE TITLE
Explore adding bundlesize

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#23009]
Could be rad to see something like https://github.com/siddharthkp/bundlesize in our CI status. It's easy for compiled code to get outta hand with small changes. Could help with that.

**Comment by XhmikosR** [comment]
I can have a look and add it after beta1 if you'd like.

**Comment by XhmikosR** [comment]
@mdo @bardiharborow: https://github.com/siddharthkp/bundlesize or https://github.com/ai/size-limit?

**Comment by Johann-S** [comment]
I prefer bundlesize personaly it's convenient to see how many bytes we add on each PR
