### ISSUE TITLE
Data-Target doesn't match modal id in Modal Documentation.

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#23002]
There is an error in the documentation of the modal. The `data-target` of the button does not match the `id` of the modal `<div>`.

https://v4-alpha.getbootstrap.com/components/modal/#examples

```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

```

![grafik](https://user-images.githubusercontent.com/2971735/27869930-b5540c1c-61a1-11e7-8747-96f01c94cea2.png)

**Comment by Johann-S** [comment]
Already fixed by : [#21671](https://github.com/twbs/bootstrap/pull/21671 "Fix modal id in doc example (Fix #21665)") and will be available on our next release, thanks 👍
