### ISSUE TITLE
bootstrap3 model.js

### ISSUE THREAD

**Issue by conlin** [twbs/bootstrap#23007]
code : 
```
<a class="text-green" href="/backend/links/edit/1" title="edit"  data-toggle="modal" data-target="#myModal">edit</a>
<a class="text-green" href="/backend/links/edit/2" title="edit"  data-toggle="modal" data-target="#myModal">edit</a>
<a class="text-green" href="/backend/links/edit/3" title="edit"  data-toggle="modal" data-target="#myModal">edit</a>

<script>
    $('#myModal').on('hidden.bs.modal', function (e) {
        $(this).removeData('bs.modal');
    })
</script>
```
removeData()  Not triggered when hidden

Instead, you can see the content being replaced when you open it second times？

I don't want to see the process of content being replaced.

How to solve it ？

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
