### ISSUE TITLE
Tabs with pagination inside not working

### ISSUE THREAD

**Issue by DataTables** [twbs/bootstrap#23005]
- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)

Linux - Fedora 25

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

Chrome 59. But reproducible in other browsers and platforms.

- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

https://jsbin.com/zobenidike/edit?html,js,output

To see the issue, run the test case and click the second tab and then the third. Note that the content for the second and third tabs are visible, rather than just the third tab.

It appears to be caused by the `active` class in the pagination that is contained in the first tab. As such, it is possible this is related to #22654, but I'm not certain!

This did work okay with alpha 6.

**Comment by Johann-S** [comment]
Yes that's related to #22654 thank you 👍
