### ISSUE TITLE
Hover on Tooltips within a Modal does not allow you to close the Modal afterwards

### ISSUE THREAD

**Issue by coderste** [twbs/bootstrap#23003]
I seem to have stumbled across a bug with the Tooltips and Popovers while in a Modal.

For some reason when I open the Modal I can seem to close it just fine by hitting `'esc' / 'x' / 'close'` but when I hover over the Tooltip or click the button for the Popover I can't seem to then close the Modal by using any of them methods instead I have to refresh the page.

I also seem to have a similar bug in Safari but this time when clicking on the Popover I can close the modal but if I re-open the same Modal I can't seem to close it afterwards.

Link: https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers
OS: macOS Sierra 10.12.5
Browser: Chrome 59.0.3071.115 / Safari 10.1.1

I'm assuming this is not the expected behaviour?

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/21743 and will be present in our next release 👍
