### ISSUE TITLE
Background color of the carousel box containing the text can't be changed

### ISSUE THREAD

**Issue by cmoulliard** [twbs/bootstrap#23008]
- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)

Mac OS X

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

Chrome 59.0.3071.115

- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

See index.hml file containing the example here : https://gist.github.com/cmoulliard/3e4ad6fc84f44a89d5f733c5ef8057c0

When we change the background color of the class `carousel-inner`

https://gist.github.com/cmoulliard/3e4ad6fc84f44a89d5f733c5ef8057c0#file-gistfile1-txt-L9946-L9948

, the color displayed is always grey dark and not green

![screenshot 2017-07-06 19 02 02](https://user-images.githubusercontent.com/463790/27923124-a209d254-627d-11e7-98f4-872dd802a8f3.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
You have images in your carousel items: 

```
<img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
```
