### ISSUE TITLE
Wrong position of tooltip arrow when 'constraints' moves the tooltip

### ISSUE THREAD

**Issue by timfish** [twbs/bootstrap#23000]
bootstrap@4.0.0-alpha.6

Issue #20685 was closed but this is not an issue with tether.

If your tooltip is moved due to `constraints` (ie. to keep the tooltip on the viewport), the arrow no longer points to the target element. This has nothing to do with tether as said in  #20685 and everything to do with the use of `::before` elements positioned  `left: 50%;`.

![image](https://user-images.githubusercontent.com/1150298/27866061-4396c076-6195-11e7-8b81-801ec2ead919.png)

Check out the [originally supplied jsbin](https://jsbin.com/nixuvuyuqu/3/edit?html,css,js,output) and you'll see that there is nothing tether can do to fix this.

**Comment by Johann-S** [comment]
Currently we removed the use of Tether and now we use Popper.js and Popper.js manage the arrow position so this issue don't exist with latest `v4-dev` dist files.

X-REF: https://github.com/twbs/bootstrap/pull/22681

**Comment by timfish** [comment]
@Johann-S Many thanks
