### ISSUE TITLE
Nested tabs are not working in current build

### ISSUE THREAD

**Issue by ozguruysal** [twbs/bootstrap#23001]
I'm using the current build and nested tabs are not seem to be working. You can see the demo of this issue at https://jsfiddle.net/ozguruysal/5v8g6knu/ I've included the JS and CSS files from master branch.

On page load all looks ok. However clicking the tabs breaks the functionality.

**Comment by Johann-S** [comment]
Duplicate of : https://github.com/twbs/bootstrap/issues/22654
