### ISSUE TITLE
.list-group-flush not working properly with Chrome 59

### ISSUE THREAD

**Issue by mcrapts** [twbs/bootstrap#23013]
The following code used to work just fine in all browsers:
```
<div class="card mx-3 my-3" style="width: 300px">
    <h5 class="card-header list-group-header text-muted">Card header</h5>
    <div class="selection list-group-flush">
        <span class="list-group-item list-group-item-action">List item A</span>
        <span class="list-group-item list-group-item-action">List item B</span>
        <span class="list-group-item list-group-item-action">List item C</span>
        <span class="list-group-item list-group-item-action">List item D</span>
    </div>
</div>
```
Since the Chrome 59 update however, it does not work properly. The borders between the list items are missing.

Result in Edge (expected result):
![image](https://user-images.githubusercontent.com/16231555/27954554-c8d1e9ce-6310-11e7-954b-8da98d7ca842.png)

Result in Chrome 59:
![image](https://user-images.githubusercontent.com/16231555/27954460-63d4580e-6310-11e7-9ba4-f52736d844f9.png)

jsfiddle: https://jsfiddle.net/6oggze6h/

**Comment by gijsbotje** [comment]
works fine for me on macbook pro macOS 10.12.5 with chrome 59.0.3071.115

**Comment by mcrapts** [comment]
That's weird. I have been able to reproduce the issue on macOS, but not on a different (similarly specced) Windows computer. I'm puzzled.

**Comment by ghiscoding** [comment]
It also works fine for me on Windows 10 with Chrome Beta version 60.0.3112.50

**Comment by caseyjhol** [comment]
I'm experiencing this same issue - Chrome 59.0.3071.115 on Windows 10. The problem appears to be with transparent borders. Setting the border to a solid color or rgba(0, 0, 0, 1) makes them visible.

**Comment by mcrapts** [comment]
Issue isn't appearing in beta version 60.0.3112.50 for me. So it appears to be a Chrome bug and not a Bootstrap issue.
