### ISSUE TITLE
Responsive Nav Tabs

### ISSUE THREAD

**Issue by phlpedr** [twbs/bootstrap#23015]
I'd like to add this behaviour to my nav-tabs:
http://openam.github.io/bootstrap-responsive-tabs/
Is there anyone who implemented this plugin and made it work with bootstrap v4?

**Comment by gijsbotje** [comment]
your example just uses double content
the `nav-tabs` has the `hidden-xs hidden-sm` classes
and the `panelgroup` has `visible-xs visible-sm` classes on them

it's just smart use of visibility classes

**Comment by envolute** [comment]
I'm sorry, but who should solve this is @openam "openam/bootstrap-responsive-tabs" and not here in the bootstrap...

**Comment by mdo** [comment]
Closing as this isn't a feature request and is more of a how to issue.

Also, at some point, tabs are more or less impossible to do well on mobile. Not something we're going to try to tackle.
