### ISSUE TITLE
Issue in your code for first live-demo modal (static modal) 

### ISSUE THREAD

**Issue by RaykPlatzek** [twbs/bootstrap#23018]
Not sure if this is the right place, please delete if this is not the correct place to raise this issue.
On your website:
http://v4-alpha.getbootstrap.com/components/modal/

You have the following code for your first static live demo:

```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
```

Shouldn't the modal id be id="#exampleModal' or the data-target="myModal". I think otherwise the code will not work. Glad to hear your feedback.
Cheers,
Rayk

**Comment by mdo** [comment]
Already fixed in v4-dev branch. Please search before opening new issues if you can :).

**Comment by RaykPlatzek** [comment]
@mdo Thanks for the advice. Is this fix to be online soon because the code is still the old one on the website. 

Cheers,
Rayk
