### ISSUE TITLE
Issue in importing translate3d.scss

### ISSUE THREAD

**Issue by SKnewIonic** [twbs/bootstrap#23024]
Hi

I have imported project from Creator ionic and tried to follow below steps  to make the app working on my devices/machines.. When I finally run "ionic serve", I am getting below error:
[12:12:01]  sass started ...
[12:12:01]  sass: D:/MyProj/aaa/src/lib/ionic/scss/_animations.scss, line: 6
            no mixin named translate3d Backtrace: src/lib/ionic/scss/_animations.scss:6

       L5:  .slide-in-up {
       L6:    @include translate3d(0, 100%, 0);

I am unable to find any related issue.. When I checked, there is no "translate3d.scss" file in my lib folder that was imported when I downloaded the project.. Can someone pls help me.. Its really important that I need to get it moving ..

Thanks
SK

**Comment by patrickhlauke** [comment]
For how-to type questions, please refer to StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
