### ISSUE TITLE
Customizing ONLY grid includes a lot of non-grid, breaking CSS

### ISSUE THREAD

**Issue by hobarrera** [twbs/bootstrap#23021]
When downloading a customized version of bootstrap, a lot of unrelated CSS seems to leak. I visited [this page](http://getbootstrap.com/customize/?id=e7b16387cc5b9891b505be0e317dd5cf) and check **only** grid (since I wanted to to add boostrap's grid on an old, already-working system).

The generated CSS included a lot of extra styles completely unrelated to grid -- including changing the default font, removed underlines from likes (which is bad for accessibility), and several other unrelated changes, and lots of other layout and visual (eg: not-box-model-related) changes.

**Comment by mdo** [comment]
Yeah you're getting Normalize and a bit extra. No way around this for v3 so many years later.

**Comment by mdo** [comment]
My recommendation would be to pull the Less files and compile yourself if you need only one file.

**Comment by hobarrera** [comment]
Thanks for the suggestion, I'll try that. No change of fixing the v3 customizer any more?
