### ISSUE TITLE
Button Outline Default State !

### ISSUE THREAD

**Issue by Mustafa-Online** [twbs/bootstrap#23029]
Why there isn't default state for "**btn-outline**' that has no background ? what if i don't wanna choose a color? 
I thought when i use it i will get gray border with a transparent Bg, But it turns that it has a gray background !! .. it's not a big deal but i felt confuse with the result.
![capture](https://user-images.githubusercontent.com/5323832/27995317-9759dd50-64d4-11e7-80ff-458369c90216.PNG)

**Comment by mdo** [comment]
> Why there isn't default state for "btn-outline' that has no background ? what if i don't wanna choose a color?

Because `.btn-outline-*` classes are modifiers to the `.btn` class.
