### ISSUE TITLE
[v4] <hr> not visible in Cards

### ISSUE THREAD

**Issue by bradleygauthier** [twbs/bootstrap#23032]
When adding an `<hr>` inside a `.card`, the line does not appear. I believe this may be a bug.

The only way I found to make it appear, is by adding `width: 100%;` to the `<hr>`. But this doesn't seem like an intended feature.

**Comment by mdo** [comment]
Note for future me or someone who wants to fix this—probably the flex styles interfering.

**Comment by prateekgoel** [comment]
I did some research on this and found this:
https://stackoverflow.com/questions/34365271/hr-inside-container-with-display-flex-become-corrupted/34372979#34372979

Adding margin-left:0; and margin-right:0; seems to fix this issue.

@mdo I would like to fix this.
