### ISSUE TITLE
JavaScript enabled tab interfaces - is the ability to use dropdowns useful?

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#23035]
Currently the dynamic javascript enabled tab navs http://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior allow for the use of a dropdown.

This particular use is fairly non-standard, and from an accessibility point of view this impedes adopting a "proper" tabbed interface pattern with correct `role="..."` etc https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel as that pattern does not foresee anything other than straight "tab" triggers.

As such, I'd like to get opinion from implementers about whether or not they find the current tab with dropdowns useful, or if dropdowns can be removed (which would then allow a proper ARIA tab implementation).

**Comment by alecpl** [comment]
Indeed a feature that is definitely not so common and I'd live without it. I'm not sure I ever saw it implemented. However, I see one use-case for a "dropdown tab". It is for better (?) mobile support. E.g. if you have many tabs that do not fit the small screen size (width) we could create a "dropdown tab" to give access to those that are out of screen. I don't like tabs in multiple rows and I didn't see Bootstrap's addressing this issue. Please, correct me if I'm wrong.

**Comment by patrickhlauke** [comment]
Yeah, was thinking about that earlier. I'd argue it's bad UX/UI when you have to resort to that sort of thing on a small screen. Particularly since if you switched to a "tab" that hidden behind a dropdown, you as a user don't even get a visual indication of what the current active tab is (as it's hidden inside the dropdown). Just feels clumsy and bad as a "real" tabbed interface (for actual navigation that isn't an in-page tab panel, it's possibly less problematic I'd say, as you'd likely have some additional thing in your page like a breadcrumb to show the user where they are...)

**Comment by patrickhlauke** [comment]
For a real tab interface with many tabs on small screen you'd probably want something like a horizontally scrollable tablist bar...something outside of what BS currently provides.

**Comment by heikojansen** [comment]
"Dropdown-Tabs" might sometimes be useful to save some space, but to me ARIA conformance is more important.

That being said and with mobile support already mentioned here I'd also like to say that having a **responsive** _and_ ARIA-conformant tab bar solution would be even more important to me.
Maybe the current JavaScript tab interface solution could be replaced by adopting this: [https://codepen.io/pankajparashar/pen/oJEAF](https://codepen.io/pankajparashar/pen/oJEAF) (the link to which I found here: [http://www.cssmojo.com/tab-panel-the-right-way/](http://www.cssmojo.com/tab-panel-the-right-way/))?
