### ISSUE TITLE
[v4] Introduce variable for customizing margin-bottom for "p"

### ISSUE THREAD

**Issue by ahmetb** [twbs/bootstrap#23031]
_reboot.scss has:

```
p {
  margin-top: 0;
  margin-bottom: 1rem;
}
```

However the value is hardcoded. It would be nice to have it exported to _variables.scss so that people can customize (_custom.scss was nice but looks like it's removed now).

**Comment by envolute** [comment]
It's the same with breadcrumb, as I reported in issue #23016

**Comment by k-funk** [comment]
I'd also like to see this change. Personally I like having the same margin for lots of block-level elements. `p`, `figure`, `ul`, `ol`, `table`, etc. I think that bootstrap3 based these margin-bottoms off of `$line-height-computed` (sometimes `($line-height-computed / 2)`). Either way, it seems like a var is more flexible and clean than overriding css.

**Comment by BhaveshSGupta** [comment]
I would like to work on this for beta 2

**Comment by prateekgoel** [comment]
Sorry @BhaveshSGupta but I'm already working on this alognwith https://github.com/twbs/bootstrap/issues/23016

**Comment by prateekgoel** [comment]
@BhaveshSGupta Sorry but I was already working on this. I just noticed your comment.

**Comment by wautersj** [comment]
Should be able to manage margin-bottom of <ol> and <ul> in the same way, no?
