### ISSUE TITLE
[v4] Introduce margin-top for heading classes

### ISSUE THREAD

**Issue by ahmetb** [twbs/bootstrap#23030]
h1, h2, h3, h3, h5, h6 (and their respective classes) currently only have `margin-bottom: $headings-margin-bottom;` property.

Realistically, in long text, such as articles, people might want to add extra padding/margin to the top of headings, therefore there should be `margin-top` property that defaults to 0 (current behavior today) and can be customizable.

**Comment by mdo** [comment]
We specifically remove the top margin—we don't be adding a variable for it.

**Comment by ahmetb** [comment]
@mdo is there a particular reason?

**Comment by mdo** [comment]
http://v4-alpha.getbootstrap.com/content/reboot/#approach
