### ISSUE TITLE
Update responsive navbar padding to use variables

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#23034]
Currently .nabvar-expand-* classes adds padding to .nav-link wrapped by `media-breakpoint-up`
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L168-L171

This should be moved few lines above to `media-breakpoint-down`  https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L143 

It would be great if those paddings were variables.

EDIT:
should be moved to `media-breakpoint-down`

**Comment by mdo** [comment]
Without a screenshot or demo of what you're running into, I can't help more. The paddings have been built this way by design. Agreed though we need variables there.

**Comment by wojtask9** [comment]
If you plan to make variables then moving to `media-breakpoint-down` is not necessary

**Comment by mdo** [comment]
I believe this was closed by #25117.
