### ISSUE TITLE
Consider removing x and y classes for p-(x|y) to save space

### ISSUE THREAD

**Issue by bryankang** [twbs/bootstrap#23037]
I really like the modular approach v4 is taking. However, adding just a couple of spacers create more baggage than needed. How about we stick to the modular design? (e.g., enforce using `pl-` and `pr-`)?

Same for the convenient `p-` and `m-` classes. These are pretty useless anyway - they have a small number of use cases.

Exception: `mx-auto`

EDIT: Maybe even discard the convenient `mx-auto` in favor of `ml-auto` and `mr-auto`. These are actually useful by themselves in flex items.

**Comment by liquidvisual** [comment]
I respectfully disagree. I use these all the time.

**Comment by bryankang** [comment]
@liquidvisual I do too. `p(x|y)-`, `m(x|y)-` are super useful. `p-` and `m-` not so much. But what's bothering me is that adding just a few more spacers generates a huge chunk of classes, at least half of which I don't use. And it's highly necessary to add more spacers.

**Comment by mdo** [comment]
Going to keep them for now, thanks though!

**Comment by mdo** [comment]
Definitely noted on the size issue btw. I've been working to knock off a few kb here and there.
