### ISSUE TITLE
mx-auto don't work on iOS

### ISSUE THREAD

**Issue by EvanBor** [twbs/bootstrap#23038]
mx-auto don't work on iOS 10 without setting element width
for example brand-logo on navbar

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by EvanBor** [comment]
I apologize! As it turned out, the bug is related to the webkit engine, not to the framework. Close please issue
