### ISSUE TITLE
documentation issue - install bootstrap 4 via webpack

### ISSUE THREAD

**Issue by Chinese1904** [twbs/bootstrap#23048]
I just came across the documentation of how to import bootstrap via webpack here: https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/webpack.md

As you can see it has some styling issues with the highlighting of code syntax. Fairly new to Bootstrap's GitHub. Not sure how you want it fixed, but if you tell me, I could send in a PR. But shouldn't be too complicated either way.

Thanks for this 👍

**Comment by gijsbotje** [comment]
what's the issue exactly? i just ran the docs locally and it works like a charm
<img width="1099" alt="schermafbeelding 2017-07-12 om 00 20 14" src="https://user-images.githubusercontent.com/7714133/28093519-ec170ede-6697-11e7-97df-b60025bcfc61.png">

**Comment by Chinese1904** [comment]
Sorry, my fault. I didn't notice it was jekyll highlighting. I was just reading the markdown file and it looked really awkward. Sorry about that!

**Comment by matudelatower** [comment]
in https://github.com/twbs/bootstrap/blob/v4.0.0-beta/docs/4.0/getting-started/webpack.md#importing-precompiled-sass built-in custom variables link is broken, points to https://github.com/twbs/bootstrap/blob/v4.0.0-beta/getting-started/options, i have problem to naming variables i.e. `$brand-primary: #2c5e7b;`
