### ISSUE TITLE
Button in flex box (.d-flex) is stretched if not within a div

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#23042]
Not sure if I need to place elements in divs before putting them in a flex box, so it's possible this is working as intended. But just in case, if you place a button in a flex box `(.d-flex`) it's stretched to its height.
Look at the following code.

```html
<div class="container">
  <div class="row">
    <div class="col">

      <div class="d-flex justify-content-between">
        <div class=""><h1>Headline</h1></div>
        <div class=""><a href="#" class="btn btn-primary mx-left">I'm fine</a></div>
      </div>
      
      <div class="d-flex justify-content-between">
        <h1>Headline</h1>
        <a href="#" class="btn btn-primary mx-left">I'm stretched</a>
      </div>

    </div>
  </div>
</div>

```

https://jsfiddle.net/oraoe2z7/

Edit: Adding `.alingn-items-center` removes the stretched look: https://jsfiddle.net/oraoe2z7/2/

**Comment by morloderex** [comment]
I believe that this is normal flexbox behaveour. :) 
The flex property is set to strech so the button streches..

**Comment by Borkason** [comment]
@morloderex makes sense 🤦‍♂️
