### ISSUE TITLE
Please put bootstrap v4 new documentation online

### ISSUE THREAD

**Issue by TagWolf** [twbs/bootstrap#23046]
Google's SEO rankings cause v4 alpha documentation to load. This is drastically different than the jekyll documentation in the repository.

Any chance on getting this online at some point on the main site.

Or even just an advisory on the alpha docs. Stating many functions are deprecated such as offset etc.

**Comment by cr101** [comment]
The documentation on the live site gets updated when a new release is shipped.

**Comment by patrickhlauke** [comment]
Yes, as @cr101 said the content on v4-alpha is a snapshot that matches v4.0.0-alpha.6 when it was released. The repo has obviously evolved/changed since then. Once the next version (beta 1) drops, online documentation will be updated to match.
