### ISSUE TITLE
Extra Small Devices "Horizontal at all times"?

### ISSUE THREAD

**Issue by catchmyfame** [twbs/bootstrap#23045]
In the [Grid options](http://getbootstrap.com/css/#grid-options) table it says that for Extra Small Devices the grid behavior is "Horizontal at all times". Shouldn't that say "Vertical at all times"? 

The grid itself runs vertically from top down, with the rows spanning the full horizontal width.  In the [example section that follows the grid options](http://getbootstrap.com/css/#grid-example-basic) seems to agree with my interpretation as it says 

> you can create a basic grid system that starts out stacked on mobile devices and tablet devices (the extra small to small range) before becoming horizontal on desktop (medium) devices

Also, for small, medium, and large devices it says the grid behavior is "Collapsed to start, horizontal above breakpoints" which (mostly) makes sense. I'd vote to remove the "Collapsed to start" part, but I digress.

**Comment by acshef** [comment]
Perhaps something along the lines of the columns being "full-width at all times" clarifies which dimension?
