### ISSUE TITLE
What's holding the first BETA?

### ISSUE THREAD

**Issue by tx8821** [twbs/bootstrap#23054]
Hello everyone,

I'm watching closely the progress of the project, and already using it in soon-to-be-production apps (yeah I'm aware of all the risks of using non-rtm libs in real projects, don't bother reminding it yet again). I've been holding the breath for so long to see the beta versions, let alone release. I'm refreshing the Milestones page almost daily and it's been stuck at close-to-99% for so long I just can't remember. Right now it has no particular items so what's holding you back to release at least the first beta?

I know there will be (yet again!) breaking changes from the alpha 6 and I'd like to prepare my projects sooner rather than later.

Can't we have at least some sort of predictable cadence?... I.e. if you say we won't see another beta until 2019, that's ok, who's gonna be judging you... but... having next milestone stuck at 99% with no apparent reason and no communication about the plans... is not really helpful. We've been waiting for Bootstrap so long that we (well, anybody!) could not have imagined we'd still be stuck with ALPHA in Q3-2017...

To be clear: I'm not complaining about the progress. I'm complaining (if that's the right word) for the lack of communication about how should we align our expectations. If Beta is frozen until particular date, just let us know!

**Comment by bkdotcom** [comment]
~~182~~ 183 open bug reports?

**Comment by Manrix** [comment]
I'm waiting the bootstrap beta 1 and font awesome 5 to bring my personal project online. But both seem to be stuck.

**Comment by jensamunch** [comment]
Well..@bkotcom in fairness:

https://github.com/twbs/bootstrap/issues?q=is%3Aopen+is%3Aissue+label%3Av4+milestone%3Av4.0.0-beta

**Comment by Johann-S** [comment]
Related to https://github.com/twbs/bootstrap/issues/23027

Thanks for your concern 👍

**Comment by tx8821** [comment]
@Johann-S  The linked issue also does not have an answer, and is also closed.

The question is: **what is holding the release of Beta now, when the Milestone's to-do list is essentially empty?**

Please reopen this discussion.

**Comment by emmanueltouzery** [comment]
I think it was answered. The answer is that they've been breaking the API between alpha releases and now they want to call it a day, be sure that the API is stable from the beta onwards. That means reviewing all pending PRs, take a hard good look at what came out of these several years of development, and make sure they regret nothing once the beta is out.
They also said once the beta is out, they expect a final release relatively quickly, exactly because they take the beta really seriously.

Someone could ask 'why don't you do an extra alpha then?' and I guess that making a bootstrap release is not that little work at all, so that makes sense to me. I was curious too, but the answer fully satisfies me.

**Comment by Johann-S** [comment]
That's what explained @emmanuelgautier and I can add we have several things to setup in intern (CDN, server, etc...)

**Comment by tomlutzenberger** [comment]
@emmanuelgautier YOUR answer is satisfying as well. Nice and short summary.
Thanks! 😃

**Comment by bkdotcom** [comment]
I much prefer the methodical bootstrap philosophy over say  [Angular](https://github.com/angular/angular)'s  lets continue to break/completely-change core functionality in release candidates

**Comment by bardiharborow** [comment]
Put very simply, the beta will be released when all the issues we haven't gotten around to assigning to the milestone are assigned and closed. As we're a volunteer project, this will happen at an undefined time in the future. I can't give any more guarantees than that sorry.

**Comment by zedjr** [comment]
I understand that no one really knows when beta will be released. I see alot of pull requests and issues left so am assuming 99% doesn't mean at all 4.0 beta is 99 percent done. Just 99% of issues have been completed. I have been monitoring this for last couple weeks and waiting to start a project when beta was released as i didn't want to use alpha when so many things will break in beta. So please correct me if i am wrong in saying that it wont be beta by this weekend or probably in the next 2 weekends. BTW i do love the fact that yall are more careful with what you release than other products. I hated using foundation 6.2 when it was released and having lots of bugs in it for the features i was using.

**Comment by bardiharborow** [comment]
@zedjr I think one key point to reiterate, is that it's not helpful to wait until we do formal releases. You can go grab the CSS from git and start using that straight away. Then when we do a beta release, you have less things to fix, or maybe you don't even need to upgrade at all. Remember that Bootstrap is just a base, and doesn't need to be treated as a dependency if you don't find that helpful.

**Comment by zedjr** [comment]
@bardiharborrow I was wondering if that was something i can do and also have documentation to follow.

**Comment by bardiharborow** [comment]
@zedjr everything you need is in the `dist` folder on the `v4-dev` branch.

**Comment by Herst** [comment]
Maybe more alphas should have been released, maybe even in an automated fashion. But, oh well, hindsight is bliss.
