### ISSUE TITLE
Move .custom-select styles to select.form-control

### ISSUE THREAD

**Issue by pat270** [twbs/bootstrap#23058]
Is it possible to move `.custom-select` styles to `select.form-control`? As it stands, it's only really useful if you don't plan on changing the border-radius on form-controls. By adding the `form-control` class to the select element we are already committing to Bootstrap's contract to style the element, doesn't make sense why we would only have partial control.

Edit: Also, `.custom-select` is the only custom element that doesn't need an extra element to achieve custom styles.

**Comment by mdo** [comment]
Let's slate this for a follow up minor release; we can deprecate it later.

**Comment by alecpl** [comment]
That would be nice. Now .custom-select-* does not play nice with .form-control. And if I'd want to override some general controls style it would be simpler and smaller to do this for .form-control only.

**Comment by romieleo** [comment]
Pada tanggal Sel, 22 Mei 2018 15.40, Aleksander Machniak <
notifications@github.com> menulis:

**Comment by mdo** [comment]
This was fixed in #28450 for v5.
