### ISSUE TITLE
[v4-alpha] navbar broken on mobile

### ISSUE THREAD

**Issue by abacaj** [twbs/bootstrap#23056]
Looks like the navbar CSS, even on the example page is broken on mobile: https://v4-alpha.getbootstrap.com/examples/navbars/

here's a screenshot: 
![navbar](https://user-images.githubusercontent.com/7272343/28130616-5d946b98-6705-11e7-85d7-42a206a769c2.JPG)

**Comment by gijsbotje** [comment]
looks like it's already fixed in v4-dev

**Comment by Johann-S** [comment]
Closed thanks to @gijsbotje's comment 👍
