### ISSUE TITLE
Improving @media-breakpoint-only

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#23052]
Now i cant pass a few breakpoints like this:
```sass
@include media-breakpoint-only(xs sm lg) {
  text-transform: capitalize;
}
```
I have to duplicate same rule:
```sass
@include media-breakpoint-down(sm) {
  text-transform: capitalize;
}
@include media-breakpoint-only(lg) {
  text-transform: capitalize;
}
```
So cumbersome and inconvenience...

**Comment by mdo** [comment]
That's not how these media queries work. `media-breakpoint-only` is for a single breakpoint. 

> I have to duplicate same rule

Why?

**Comment by rorc** [comment]
@mdo `media-breakpoint-only` also can be for multiple breakpoints, as if "media breakpoint only for this breakpoints (xs sm lg)"
>Why?
```sass
@include media-breakpoint-down(sm) {
  text-transform: capitalize;
}
@include media-breakpoint-only(lg) {
  text-transform: capitalize;
}
```
Here i have to write `text-transform: capitalize;` twice...

**Comment by rorc** [comment]
Or we can create new mixin something like this `media-breakpoints-for()`?

**Comment by mattjackson1** [comment]
@mixin media-breakpoint-between()
