### ISSUE TITLE
[v4-alpha] Missing responsive classes d-xs-{block,display,none}

### ISSUE THREAD

**Issue by ahmetb** [twbs/bootstrap#23050]
I just wrote a small debugging label indicating the current breakpoint as follows:

```
<div style="position:fixed; top: 30px; right: 75px; background-color: rgba(255,0,0,0.1)">
    <span class="d-none d-xs-block d-sm-none">XS</span>
    <span class="d-none d-sm-block d-md-none">S</span>
    <span class="d-none d-md-block d-lg-none">M</span>
    <span class="d-none d-lg-block d-xl-none">L</span>
    <span class="d-none d-xl-block">XL</span>
</div>
```

This shows the current breakpoint fine, except XS: there's are no classes called `d-xs-block` or `d-xs-none`.

This is actually preventing me from defining my own custom breakpoint such as XXS and being able to test it. To preserve the symmetry, classes:

- d-xs-block
- d-xs-display
- d-xs-none

should be provided.

-----

To solve my initial problem and make the snippet above work, I had to change the line to:

        <span class="d-sm-none">XS</span>

which looks like a corner case handling. If the aforementioned classes were provided, I would've preserved the symmetry in the code just fine. Not to mention, I think `d-none d-xs-block` is a valid use case when someone like me defines classes smaller than xs, such as xxs.

**Comment by japrogramer** [comment]
Hello i believe im having the same problem, except im also missing other classes like bg-inverse, navbar-inverse, offset-sm-2 etc. Im using alpah-6
Here are the relevant files.
http://dpaste.com/2J3APQA

About my environment, I have bootstrap install via bundler here are my relevant Gemfile
http://dpaste.com/10CQ3H3

**Comment by razh** [comment]
@ahmetb You can declare your own custom `$grid-breakpoints` (the default value is located in `_variables.scss`) and the classes will be generated.

For example:

```scss
$grid-breakpoints: (
  xxs: 0,
  xs: 480px,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
);
```

Bootstrap removes the breakpoint infix for the smallest breakpoint. Thus, if `xs` is the smallest breakpoint, `.d-xs-none == .d-none`, `.d-xs-block == .d-block`and so on.

---

@japrogramer You are currently using the using the development branch (`v4-dev`), not alpha 6.

The development version has removed those classes entirely:

| Alpha 6 | Beta 1 |
|---|---|
| `.bg-inverse` | `.bg-dark` |
| `.navbar-inverse` | `.navbar-dark.bg-dark` |
| `.offset-sm-2` | `.ml-sm-auto` |

This is the referenced commit in your Gemfile: https://github.com/twbs/bootstrap-rubygem/commit/b156edfee2b9629ad4751ee2a118a04f824ef9eb

Instead, you want https://github.com/twbs/bootstrap-rubygem/commit/79c3fc026cbc1428e783135ec4ecfb7d71889497. (Although, you might as well stick with the dev branch as those classes are deprecated.)

**Comment by japrogramer** [comment]
@razh I had no idea they where deprecated, because i haven't seen them listed as deprecated on the v4 
site and they are used in the examples. I guess that makes sense. Are there any other classes that have been deprecated or renamed? there doesn't seem to be change list for the beta
 https://v4-beta.getbootstrap.com/migration/

**Comment by razh** [comment]
@japrogramer Yes, the documentation has not been updated because Beta 1 is not released yet.

The Beta 1 ship list has the most up-to-date list of changes but, since it's more of a commit log, it's not ideal for identifying deprecations/renames: https://github.com/twbs/bootstrap/issues/21568

**Comment by japrogramer** [comment]
@razh I can see that the milestone for beta 1 is at 99% complete but still no due date has been posted?
what is the 1% that is yet to be done?

**Comment by japrogramer** [comment]
oh, i see. just waiting on alpha to fix some brake points.

**Comment by ahmetb** [comment]
@razh thanks for the `$grid-breakpoints` pointer. I appreciate. 

Still going to keep the issue open to discuss whether infix breakpoints for smallest/largest breakpoints should exist. Feel free to close if you see as fit.

**Comment by razh** [comment]
@ahmetb 

Symmetry would work if `md` (or some other inner breakpoint) was the center breakpoint:

```
 ◀─────┬──────┬──────┬──────▶
xs     sm     md     lg     xl
```

But media queries behave like positive numbers + zero, so `xs` is a superset of `{sm,md,lg,xl}`, hence why it is superfluous.

```
 ○─────┬──────┬──────┬──────┬──────▶
xs     sm     md     lg     xl     ∞
```

**Comment by mdo** [comment]
`xs` breakpoint specific classes still exist, but the classes don't include that infix. Instead of `.d-xs-none`, it's `.d-none` as those styles are never bound to a media query—they apply from `min-width: 0` and up, across all viewports.

**Comment by mdo** [comment]
This was reiterated in the Alpha 6 blog post btw.

**Comment by redsoxfan2499** [comment]
I am running into issues with trying to display on xs and small only. I am using 4.0.0-beta.2 

in my div my classes are:  class="bg-primary py-5 d-block d-sm-block d-md-none"  

so what I am seeing. the div is hidden on everything medium and up. I get to small and my div shows up but then I hit a width of < 420px and my div disappears. I get a huge white blank space where my div is living but it is hidden. In my inspector, I am still seeing this:

.d-block {
    display: block!important;
}

any help would be greatly appreciated! 

Thanks, 
Darren

**Comment by mdo** [comment]
@redsoxfan2499 Classes without an infix—the breakpoint abbreviation in the middle—apply to all viewports, from `xs` to `xl`. All responsive classes like these apply to the given breakpoint and up, so you don't need `d-block` and `d-sm-block`—the first one alone would do. Your custom `d-xs-block` is the same as our `d-block`.

Assuming you're already using a `<div>`, you don't need `d-block` at all and can use only `d-md-none` to hide it from `md` on up.

**Comment by mdo** [comment]
Also, please refer to StackOverflow and Slack for how-to questions. I'm going to lock this thread given it's a not a bug or feature request, and there's no problem to resolve.
