### ISSUE TITLE
Add appropriate "fill" colours to Buttons to match "color"

### ISSUE THREAD

**Issue by robcresswell** [twbs/bootstrap#23066]
It's relatively common to add SVG icons to buttons, rather than using icon fonts. It would be convenient if we added fill styling that matches the colors of the buttons (i.e. white on .btn-primary, by default); otherwise I imagine there will be many people duplicating that code when using Bootstrap.

**Comment by patrickhlauke** [comment]
some users will use SVGs that need a fill, while others will be using SVGs that just rely on stroke. as such, i think it should be left up to authors to add their specific customisation depending on the kind of SVG they're adding.

**Comment by robcresswell** [comment]
I suppose so. If its all the same, I'd like to leave the issue open a short while to hear other opinions. Personally, I think leaving a default for fill out will mean a great deal of duplication in usage of bootstrap, but I can understand your point of view :)

**Comment by razh** [comment]
@robcresswell You could create utility classes that declare `fill: currentColor`/`stroke: currentColor`.

Declaring a default `fill` would override `fill` attributes (but not inline styles).

https://css-tricks.com/almanac/properties/f/fill/
