### ISSUE TITLE
Checked state not updating for checkbox and radio button groups

### ISSUE THREAD

**Issue by JustinY17** [twbs/bootstrap#23069]
https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

The checked attribute for the radio or checkbox input is not being set / changed based on the click event.

**Comment by Johann-S** [comment]
I think this was fixed in our current dist files 🤔 @patrickhlauke thoughts ?

**Comment by sroy** [comment]
As of 4.0.0-alpha.6, this is still an issue.

**Comment by sroy** [comment]
I found out what was wrong with this for me.  It appears laravel 5.4 overrides some functions, when I disabled their built in JS, it started working again for me.
