### ISSUE TITLE
Card Columns, Card card-text does not word-wrap properly.

### ISSUE THREAD

**Issue by skeith69** [twbs/bootstrap#23061]
Windows 10
All major browsers

Issue
"card-text" class does not word wrap properly the texts inside the tag. It overflows and looks ugly.

How to produce the issue
1. Create any data with textarea tag using WYSIWYG plugins.
2. Pull the data then use strip tags and string limit on it.

**Note I'm using Laravel string_tags and str_limit functions on this

3. use it inside the tag like this
<div class="card-columns">
  <div class="card">
    <div class="card-block">
      <p class="card-text">{{ DISPLAY HERE }}</p>
    </div>
  </div>
</div>

Solution
add "overflow-wrap: break-word" to the tag with "card-text" class to properly word wrap the texts inside

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Duplicate of #22740.

**Comment by Adonetinfernal** [comment]
> Duplicate of [#22740](https://github.com/twbs/bootstrap/pull/22740).





https://maximilian-addictive.github.io/7y29jJvN/
