### ISSUE TITLE
Suggestion to remove .col-form-label in horizontal forms in favour of cleaner code and better looking forms

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#23062]
From the documentation

> Be sure to add .col-form-label to your \<label\>s as well so they’re vertically centered with their associated form controls.

While working with forms I stumbled about something that seems overly tedious. I experimented with two forms in a [JSFiddle](https://jsfiddle.net/n4h2ejoj/) and the result is this:

In *Form 1* `.col-form-label` does indeed vertically position the label in a horizontal form. Although this does not apply to larger form controls like `<textarea>`. What actually happens is that the label's baseline is aligned with its associated form control's baseline of its first line of text. But that's just a side note.

If you are omitting `.col-form-label`, the label aligns at the top of its associated form control, making the form look unbalanced or even "broken". You can see this at *Form 2*

That practically makes `.col-form-label` a requirement in horizontal forms. So, if something is required, why not make it the default? My suggestion is that class `.col-form-label` should be removed, but it's properties should be the default for any label of horizontal forms. In my understanding this can easily be done, because  any affected label is a direct child of a div with both classes `.form-group` and `.row`.

This change would give all horizontal forms a clean visual look by default and make them easier to understand and quicker to write while removing unnecessary clutter from the code.
This would also improve the documentation as `col-form-label` is mentioned in the [form docs](https://v4-alpha.getbootstrap.com/components/forms/) 26 times at the time of writing this suggestion.

![grafik](https://user-images.githubusercontent.com/2971735/28160530-cacea9d8-67c0-11e7-9efc-c1222a66e137.png)

https://jsfiddle.net/n4h2ejoj/

**Comment by mdo** [comment]
> In my understanding this can easily be done, because any affected label is a direct child of a div with both classes .form-group and .row.

It's not that easy in practice, though. Our example markup is never the only way to do it, and there's no guarantee that `<label>`s will be an immediate child element. For that reason, we need the class.
