### ISSUE TITLE
Accessible alert with icon example

### ISSUE THREAD

**Issue by esr360** [twbs/bootstrap#23073]
I was looking at this example here ([source](http://getbootstrap.com/components/)):

```
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  Enter a valid email address
</div>
```

Rather than adding `aria-hidden` to the icon, and creating a new `sr-only` element, would it not be more appropriate to simply add an `aria-label` to the icon?

```
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-label="Error"></span>
  Enter a valid email address
</div>
```

Or is there a reason this wouldn't work?

**Comment by patrickhlauke** [comment]
using `aria-label` would be valid - see https://www.paciellogroup.com/blog/2017/07/short-note-on-aria-label-aria-labelledby-and-aria-describedby/ (as `role="alert"` falls under "elements that have an explicit widget role applied").

it's not necessarily better or worse or more or less appropriate. just another way of doing it. (and older assistive technologies don't always seem to properly support `aria-label` on things that aren't simple links/buttons, so the `sr-only` approach which used to be very common a few years ago is still a tried and tested method of achieving this).

**Comment by patrickhlauke** [comment]
for v4 the documentation is a bit clearer perhaps http://v4-alpha.getbootstrap.com/components/alerts/ 

> Ensure that information denoted by the color is either obvious from the content itself (e.g. the visible text), or is included through alternative means, such as additional text hidden with the `.sr-only` class.

so `sr-only` is only one of the "alternative means" we show
