### ISSUE TITLE
Links, when used as buttons have bad text color on focus

### ISSUE THREAD

**Issue by praveenpuglia** [twbs/bootstrap#23079]
## What's happening?
When a link is used has the `.btn` classes, their color on focused state is wrong.

## Reduced Test 
http://jsbin.com/yicatebulu/edit?html,output

## Relevant Information
- OS - MacOS Sierra
- Bootstrap - V4-Alpha6
- Browser - Chrome - 59, Firefox 54, Safari 10.1.1
- In Firefox, the link is not even accessible via tabbing. That's gonna be a different issue.
- If you have clicked on the element and still hovering, you won't see the problem. Take the cursor out of the element and the problem appears.

## Screenshot
![image](https://user-images.githubusercontent.com/313363/28205584-42bb2d42-68a0-11e7-94aa-e0d54f5312ca.png)

**Comment by patrickhlauke** [comment]
Already fixed https://github.com/twbs/bootstrap/pull/21539 :)

**Comment by praveenpuglia** [comment]
I confused as to why I couldn't find this issue when i was searching in the issues list. Sorry for the duplicate one.

**Comment by patrickhlauke** [comment]
no worries :)
