### ISSUE TITLE
Firefox, Accessibility - Links with .btn classes aren't focusable via keyboard in FF.

### ISSUE THREAD

**Issue by praveenpuglia** [twbs/bootstrap#23080]
## What's happening?
Can't focus on an anchor element with `.btn` classes on it.

## Reduced Test 
http://jsbin.com/yicatebulu/edit?html,output

## Relevant Information
- OS - MacOS Sierra
- Bootstrap - V4-Alpha6
- Works in - Chrome - 59, Safari 10.1.1

**Comment by patrickhlauke** [comment]
Works for me (macOS Sierra 10.12.5, Firefox 54.01). Make sure you have full keyboard access enabled in macOS keyboard settings (Settings > Keyboard > Shortcuts - full keyboard access set to "all controls")

**Comment by patrickhlauke** [comment]
If that's already set to all controls, but Firefox still stubbornly refuses to focus on links (not just in Bootstrap, but any site), see the about:config specific hack for Firefox here http://www.456bereastreet.com/archive/200906/enabling_keyboard_navigation_in_mac_os_x_web_browsers/ (but in short: it's a Firefox bug/shortcoming, not a problem with anything Bootstrap does)

**Comment by praveenpuglia** [comment]
@patrickhlauke - Thanks. that solved the issue. Never knew it.
