### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by mathiasmadsen** [twbs/bootstrap#23084]
There is a minor error on [this page](https://v4-alpha.getbootstrap.com/components/modal/#live-demo) of the v4 documentation.

The `data-target="#exampleModal"` is supposed to refer to `id="myModal"`

So in order for the modal to work, the id has to be identical. I expect the second id should be changed to `exampleModal` to avoid confusion from the other modals.

**Comment by patrickhlauke** [comment]
fixed ages ago https://github.com/twbs/bootstrap/pull/21671

**Comment by mathiasmadsen** [comment]
Hmm.. I see that it was supposed to be fixed ages ago, but the live documentation still contains the wrong code?

**Comment by patrickhlauke** [comment]
the live docs are for the alpha 6 release. the repo has moved beyond that. once beta 1 is released the fixed docs will go up

**Comment by mathiasmadsen** [comment]
Ok. Thanks :)
