### ISSUE TITLE
Sass and dynamic imports

### ISSUE THREAD

**Issue by kitsguru** [twbs/bootstrap#23086]
I have been looking at v4 and the move to sass now that beta is imminent. I have been using less and now need to move to sass if I want  to use bootstrap 4.

The issue I have is that sass does not, nor does it appear that sass supports conditional imports. I don't use all the functioanlity of bootstrap in every project. With BS3 I had a configuration file that set flags that controlled the import. This is no longer possible in BS4.

According to sass dev team, thet are not planning on supporting dynamic imports and recommend wrapping the entire partial and accessing it as a mixin. The discussion over at sass as been going on for years and still no resolution. This is also necessary for theming.

I am wondering ig the BS team has any thoughts and possible solutions to the issue of condtional imports and theming as they are related and in my mind essential going forward.

**Comment by mdo** [comment]
We didn't have dynamic imports in v3, at least anything on our end. There are no plans for conditional _imports_, though we do have a few build files (example `bootstrap-grid.scss`). We also have some global variables for enabling/disabling features like gradients, rounded edges, etc.

**Comment by kitsguru** [comment]
True, but with v3 I was able to add my own conditionals around the import statements because it was supported by LESS, and add my own flags in my main.less file. This is no longer an option with sass.

Theming andn custom builds are virtually impossible now. It does appear that in Feb, the sass team has decided to add a mechanism to do this but it may be a long way off.

 https://github.com/sass/sass/issues/739

Thnaks for your quick response @mdo
