### ISSUE TITLE
Navbar dropdown font-size using em/rem of .8 or .9 loses horizontal alignment

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#23089]
macOS 10.12.5
Safari 10.1.1

Open the codeply and notice the "Home" dropdown text in the navbar is not horizontally aligned with the "Home" link text. Whenever the font-size is set to .8em or .9em (same for rem), the dropdown text will be shifted down a few pixels when compared to the link text. Try changing the font-size in .1 increments to see this in effect.

https://www.codeply.com/go/FQDgYbNAze

**Comment by chiraggmodi** [comment]
@mrlife  i didn't find any alignment issue i have check in windows, can you share screenshot of your issue?

**Comment by mrlife** [comment]
I did more testing and can confirm it looks fine on Windows (Edge and IE) and Mac (Firefox and Chrome), but not Safari on Mac. Here is the screenshot:

![screen shot 2017-07-17 at 9 47 54 am](https://user-images.githubusercontent.com/213164/28271154-c8c76e64-6ad5-11e7-8e5f-f4ee3d656130.png)

**Comment by mdo** [comment]
I don't think I'm going to change anything here—changes like this given the relative component sizing will produce sometimes undesirable alignment. Important thing is to find the right balance between sizing and padding and adjust accordingly.
