### ISSUE TITLE
Putting button in a div inside a input-group-btn and clicking the button's text opens the select in Chrome

### ISSUE THREAD

**Issue by IWRichard** [twbs/bootstrap#23083]
If you put a `<button>` inside a `<div>` and put that inside of a `.input-group-btn`, and then clicking the button's text, it'll open the select.

I tested this in Chrome, Firefox and IE11 and it only seemed to happen in Chrome 59 on Windows Server 2012 R2, tested with Alpha 6.

Test: https://codepen.io/anon/pen/jwJmZe

I did manage to fix it by adding this to my style:

```css
.input-group-btn
{
    z-index: 10;
}
```

**Comment by alanstratos** [comment]
It's weird because I was unable to reproduce it. Then after opening it in a new tab, the bug was there but just for a short amount of time, then it worked fine.

W10. Mozilla 54 and Chrome 59.

**Comment by 36864** [comment]
As a quick note, clicking beyond the button, while still within the width of the option test, will also open the select dropdown. 
This happens for both controls in your pen. Tested on chrome, firefox and edge, only chrome is buggy.

**Comment by mdo** [comment]
Your markup is incorrect—the input group requires an immediate child element there for proper styling.

**Comment by IWRichard** [comment]
I know my markup is "incorrect", however this is neccessary for part of a project.

I did however find the behaviour interesting, hence this issue.
