### ISSUE TITLE
IE input-group doesn't resize in flex-row

### ISSUE THREAD

**Issue by korn3l** [twbs/bootstrap#23082]
In IE 11 if you have an input-group inside a div inside a flex-row, it will not resize to fit the row. Something like this:

```html
<div class="d-flex flex-row">
    <div class="p-2">
        <div class="input-group">
             <input type="text" class="form-control" placeholder="this doesn't work on IE 11">
        </div>
     </div>
</div>
```

This doesn't happen in chrome.
![no-resize](https://user-images.githubusercontent.com/1729922/28211049-4b98c35e-68a3-11e7-83ad-55f90eed70cc.PNG)

Bootstrap Version: 4.0.0-alpha.6
Operating System: Windows 10
Browser: IE 11
Reduced Test Case: https://plnkr.co/edit/rDdbbHXQ6ldMRyZyLpZp?p=preview

**Comment by XhmikosR** [comment]
@korn3l: could you try postcss-flexbugs-fixes and see if it fixes the issue for you?

**Comment by XhmikosR** [comment]
Oh, and try the latest release from the v4-dev branch.

**Comment by XhmikosR** [comment]
BTW I can't reproduce here.

![2017-07-30_15-01-47](https://user-images.githubusercontent.com/349621/28753133-19ed141c-7538-11e7-8f92-86aabf5ddc32.jpg)

**Comment by XhmikosR** [comment]
OK, I reproduced. The right panel needs to be small enough.

**Comment by korn3l** [comment]
@XhmikosR  Ok, I will try to reproduce it with the latest dev release

**Comment by korn3l** [comment]
@XhmikosR Tested with the latest release from the v4-dev branch and it's reproducible.

**Comment by MartijnCuppens** [comment]
This is a IE flexbox bug, you can use the grid with `.col-auto` classes to fix this.
