### ISSUE TITLE
Strange behaviour of ul in chrome

### ISSUE THREAD

**Issue by dpfahlbusch** [twbs/bootstrap#23096]
In Google Chrome the lines of some elements in the ul are not visible.

**Comment by patrickhlauke** [comment]
need a reduced test case showing the problem. otherwise we can't help. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by mdo** [comment]
Closing this outright—way too vague of an issue description to leave open.
