### ISSUE TITLE
Remove duplicate max-width and make it as default

### ISSUE THREAD

**Issue by nickjazz** [twbs/bootstrap#23100]
when put container in flex box. work well but not in xs size.

before : https://codepen.io/kimix/pen/VWNaXj

and remove duplicate max-width for each media query, just put width 100% as default

after: https://codepen.io/kimix/pen/NgmNYY

**Comment by mdo** [comment]
Your examples render the same to me in Safari and Chrome.

**Comment by nickjazz** [comment]
in small screen
https://ibb.co/cAAmxv

**Comment by mdo** [comment]
Merged #23100, so closing out.
