### ISSUE TITLE
Dropdown menu width and position

### ISSUE THREAD

**Issue by yamifr07** [twbs/bootstrap#23105]
There is a bug when positioning dropdown box in the menu, on large screen.
E.g.: [https://themes.getbootstrap.com/products/application](https://themes.getbootstrap.com/products/application)
Click user profile photo in the navbar on the right of the search form. The popup is outside the screen.

**Comment by mdo** [comment]
Not the place for Themes issues. Please email themes@getbootstrap.com instead.
