### ISSUE TITLE
Cannot mask input field in modal

### ISSUE THREAD

**Issue by ChrisGrigg** [twbs/bootstrap#23111]
- Operating system and version: Mac OS X, v10.12.5
- Browser and version Chrome, v59.0.3071.115
- Reduced test cases and potential fixes: https://jsbin.com/pajacelabo/edit?html,js,output

It is not possible to use .mask() for an input field when the input field is in a Modal. See https://jsbin.com/pajacelabo/edit?html,js,output for an example.

**Comment by gijsbotje** [comment]
if i'm not mistaken you need a plugin to use `.mask`, it is not a default function of jquery
https://css-tricks.com/input-masking/

**Comment by ChrisGrigg** [comment]
@gijsbotje thanks, I was not having a good day yesterday. The day after a Stag do/Batchelor weekend!
