### ISSUE TITLE
$line-height-sm/-lg is confusing

### ISSUE THREAD

**Issue by ahmetb** [twbs/bootstrap#23119]
https://github.com/twbs/bootstrap/blob/082c9d92fe1057f8dddda32e1002983d82c681aa/scss/_variables.scss#L211-L212

These two variables `$line-height-sm` and `$line-height-lg` give the impression that they're used for `body { line-height: ... }`, however they're only used in scss/_buttons.scss and scss/_pagination.scss. It seems like `$line-height-base` is the correct one to edit.

Please consider renaming those to distinguish.

**Comment by mdo** [comment]
They map to small/large components, yes, but they can also be used for other things if needed. It's difficult to deal with the grid tiers and a separate scale. Unlike margin/padding, a similar scale would need to map 1:1 to the `line-height` value`. For example: `.lh-1`, `.lh-15` (can't do `-1.5`), etc. That's a little more difficult and slightly less clear.

Thoughts from anyone else?

**Comment by prateekgoel** [comment]
There are similar classes for `font-size`, `border-radius`, etc.
I think if we are to change `line-height` classes, then we would also need to change such other classes for consistency.

**Comment by ahmetb** [comment]
Yes, it looks like I was also fooled by $font-size-lg and $font-size-sm names (and others did, too #23047).

**Comment by mdo** [comment]
Closing as a won't fix for now—this is too big of a change. We can revisit another time.
