### ISSUE TITLE
Move from grunt-saucelabs to Travis's built-in Sauce Connect

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#23116]
grunt-saucelabs is the last thing stopping us dropping grunt as a dependency altogether. I'd like to get this done before we ship the second beta. This will also allow us to start running Sauce tests against PRs.

https://docs.travis-ci.com/user/sauce-connect/

**Comment by XhmikosR** [comment]
Agreed. I was looking at it too the other day. If you make any progress, feel free to CC me to have a quick look.
