### ISSUE TITLE
IE 11 clear button on input group is cut off and positioned incorrectly

### ISSUE THREAD

**Issue by judowalker** [twbs/bootstrap#23115]
On IE 11 (Windows 10), the ms-clear button in an input group is partially cut off and is positioned center bottom.

![image](https://user-images.githubusercontent.com/5522073/28285687-82b0c294-6aea-11e7-973e-eb52f9770389.png)

**Comment by mdo** [comment]
Can you verify against the latest from v4-dev? Curious if this was fixed by our flexbox changes.

**Comment by judowalker** [comment]
@mdo this is fixed in the latest v4-dev.

**Comment by mdo** [comment]
Closing out then, thanks!
