### ISSUE TITLE
V4 badge-default or badge-secondary

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#23127]
Hi
here
https://twbs.github.io/staging/docs/4.0/components/badge/
we have **badge-default**
who is **NOT** in boostrap.css (**badge-secondary**)
what is right ? or i miss something ?

the doc is not updated isn't it ?

Thanks for answer

**Comment by jipexu** [comment]
oups....sorry  in the .md file is ok 
so maybe i misused this :  https://twbs.github.io/staging/docs/4.0/components/badge/  ??

**Comment by mdo** [comment]
Hosted docs don't ever match the current code in our dev branches.

**Comment by jipexu** [comment]
thanks
