### ISSUE TITLE
Actionable cards with hover

### ISSUE THREAD

**Issue by QuantumHive** [twbs/bootstrap#23123]
It would be a nice feature if card elements could be made _actionable_ (similar to [actionable list group items](https://v4-alpha.getbootstrap.com/components/list-group/#links-and-buttons)).

So for example add a `card-action` to any of the applicable card children:

```
<div class="card">
    <div class="card-header card-action">
        You could've used me for accordions
    </div>
</div>
```

My current workaround for a similar effect is to use one `list-group-item` within a `list-group` like so:

```
<div class="card">
    <div class="list-group list-group-flush>
        <a href="#" class="list-group-item list-group-item-action">
            Close enough, but it's not exactly ideal
        </a>
    </div>
</div>
```

Also I'm forced to use `<a>` and `href="#"` to get a pointer cursor and I cannot enjoy additional styling for example in the `card-header` or `card-footer`.

**Comment by Johann-S** [comment]
Seems related to : https://github.com/twbs/bootstrap/issues/18294
