### ISSUE TITLE
Carousel not responsive + i saw a small error on the website v4

### ISSUE THREAD

**Issue by tobioye88** [twbs/bootstrap#23128]
**Carousel is not responsive,**
- When width is larger than the image. It's distorts the image if w-100 is added to it and the image-fluid class doesnot seem to work as intended.
-  Also i saw a little bug on your web site. I have added a picture to help you with it. At the LiveDemo section (for some weird reasons uploading didn't wrok) so i'd try my best to explain.

On the Modals Page, the id in the data-target attribute on the button  is not the same as the one in the  id attribute in the modal. Therfore the button will not work if one was to copy and test as is.
I think that's it.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by XhmikosR** [comment]
Please see @Johann-S's reply and provide the needed info.
