### ISSUE TITLE
question about future of theme-colors

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#23126]
bootstrap v4.beta1 is around the corner so I would ask what is the future of theme-colors?

Currently all themeable components iterate over theme-colors map. 
It is possible that in future (v4 lifetime) there will be for example separate maps for components (example alert-theme, table-theme, buttons-theme, etc)?

And what about "color-levels"? Currently they are hardcoded.
`@include alert-variant(theme-color-level($color, -10), theme-color-level($color, -9), theme-color-level($color, 6));`
Is there a chance that after beta1 things will be more customizable?

**Comment by mdo** [comment]
Goal is for every color to have their own Sass map for `100` to `900` levels. We'll likely have variables for all those, too. There are currently no plans to provide different maps unique to each component.

What else are you thinking about for easier customization?

**Comment by wojtask9** [comment]
Maybe something misunderstood about color-levels.
For example how to make alerts border darker than default?
Currently there isn't any way to achieve this (see https://github.com/twbs/bootstrap/blob/v4-dev/scss/_alert.scss#L46) without modify sources.
Another example are buttons.
How to make border color other than background-color (https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L55).

Currently when we updating bsv4 sources we replace lines mentioned above using simple regexp to something similar:

`@include alert-variant(theme-color-level($color, $alert-bg-color-lvl), theme-color-level($color, $alert-border-color-lvl), theme-color-level($color, $alert-color-lvl));`

It's not ideal solution but works.

**Comment by mdo** [comment]
Closing for #23418.
