### ISSUE TITLE
support bg-faded as progressbar background for indeterminate-like state?

### ISSUE THREAD

**Issue by emmanueltouzery** [twbs/bootstrap#23131]
I saw a bug was rejected regarding implementing an indeterminate state for the progress bar (https://github.com/twbs/bootstrap/issues/22599). But I was thinking about a little hack for which it seems that it would cost almost nothing to implement and could enable a pretty good indeterminate-like state.

First, the problem that I have is that when you trigger an action in my GUI, it takes some time before the progress bar moves from 0%. So I'd like to show some animation in that time, to let the user know that the action was indeed triggered. Once the progress is strictly over 0%, then I would go back a more normal look. And my idea to give this feedback of indeterminate state is with the following CSS style:

    progress-bar progress-bar-striped progress-bar-animated bg-faded

So, width 100%, faded+animated. With the gray style and full-width progress bar, I would be a pretty good indeterminate state, I think.

Obviously the issue for me is that bg-faded doesn't exist for the progress bar :-)
So the question is, do you think it would make sense to add it for that purpose, or you see it as a hack and don't want to add it?

*EDIT:* aha I think I can achieve that myself by overriding the `background-color` to lightgray or something of the sort. Well, maybe this could still be already out of the box in bootstrap..

**Comment by mdo** [comment]
`.bg-faded` is gone now that `.bg-light` is here. `opacity`, custom CSS, and more are your best bet here. We might have variables, but not likely classes, for color shades in a v4.x ship.
