### ISSUE TITLE
Severe performance issues apparently due to bootstrap dropdown clearMenus

### ISSUE THREAD

**Issue by kikonen** [twbs/bootstrap#23134]
For a while I've pondered strange slowdown in web app pages (which I'm developing). After taking profiler into use, I could see that every click, anywhere on page, takes over 200+ms. And according to profiler this time is taken by bootstrap Dropdown.clearMenus. i.e. try to click just on page background, 200+ms delay, try to focus click any field, again 200+ms delay. More specificly time seems to be taken from jQuery selector execution within "clearMenus".

This is rather awkward, since this app needs to be able to show rather large tables (say 1000+ rows), but this 200+ms latency on every click starts to make pages unusably slow to respond to anything.

It looks like there nothing what I can do about this issue without hacking internals of bootstrap Dropdown code, which contains this hardcoded "try to clearMenus if user  clicks anywhere".

Screenshot from profiler:
<img width="755" alt="screenshot 2017-07-21 15 35 56" src="https://user-images.githubusercontent.com/478935/28463675-5246e082-6e2a-11e7-8028-5b4409ac0224.png">

Note: Pages encountering issue, don't actually have lot of of dropdown menus (and none of them reside in this large tables). Pages contain only around 10 dropdown menus in navbar (plus one or two elsewhere).

**Comment by Johann-S** [comment]
is it possible for you to let us know which version of Bootstrap do you use ?

**Comment by kikonen** [comment]
3.3.7

**Comment by kikonen** [comment]
Tried following hack

dropdown.js
```javascript
  var toggle   = '.dropdown-toggle[data-toggle="dropdown"]'
 ...
```
and time taken by clearMenus dropped significantly (from 200+ms 20+ms). That result is kind of understandable since selector queries using classes are generally rather optimized in browsers.

Btw, I'm using Opera/Chrome for testing this.

**Comment by mdo** [comment]
Closing as a won't fix for now as we're not actively developing v3. Might revisit in the future as time allows though.

**Comment by jordan-ware** [comment]
We had performance issues as well, most noticeable on devices with lower processing power.

@kikonen's suggestion solved the issue for us - our jquery attribute checks went from >200 down to roughly 30 due to the class narrowing down the elements before attributes were checked. If it's possible to remove the attribute check from the selector, that would be ideal as well but I'm not entirely sure. Will try it out.
