### ISSUE TITLE
Button classes not working when used with span. 

### ISSUE THREAD

**Issue by joshi-kunal-16** [twbs/bootstrap#23147]
The target is to use classes "btn btn-primary btn-default btn-sm" with <span> tag.
Although the classes work fine in case of  : 
``<span class = "btn btn-primary btn-sm" > span as button</span>``
with the output as 
![screen shot 2017-07-24 at 3 58 58 pm](https://user-images.githubusercontent.com/30405670/28519407-0e33f5fe-7089-11e7-8284-b6e70cdc928a.png)
but the style breaks when attribute type="button" is used.
`<span class = "btn btn-primary btn-sm" type="button">span as button</span>`
![screen shot 2017-07-24 at 4 01 24 pm](https://user-images.githubusercontent.com/30405670/28519496-6e2f5c00-7089-11e7-9c1a-0e23f359832f.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bkdotcom** [comment]
for starters, `<span type="button"></span>`  isn't valid html

valid attributes:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

don't expect pretty things for invalid html

**Comment by mdo** [comment]
Closing per above comment.
