### ISSUE TITLE
Feature request: Publish bootstrap releases to InterPlanetary File System (IPFS) directly and announce hashes on getbootstrap.com

### ISSUE THREAD

**Issue by pruflyos** [twbs/bootstrap#23154]
**Today** bootstrap relies on MaxCDN to distribute bootstrap releases across the web, so people can easily get started (http://getbootstrap.com/getting-started/).

**Tomorrow** it would be great if the bootstrap team would additionally publish official releases to IPFS (see https://ipfs.io/docs/getting-started/) and publish the hashes on their website.

**Why?**
Well first, because IPFS is - among many other things - a CDN. However, it is a CDN without a central authority or operator.

Second, because if I want to build an IPFS-based, bootstrap-based website/application today, I can take the desired bootstrap release and publish it along with my other files on IPFS. This will calculate the unique hashes for the bootstrap files and publish them to my local node.
If somebody else would download the same bootstrap release from getbootstrap.com and publish it to their local IPFS node, the bootstrap files would be published under exactly the same hashes. Actually it doesn't matter who publishes a bootstrap release first or how many people do it in parallel, if the files are identical, they will result in the same hashes.

**However, this step of downloading bootstrap release and then adding it to the local IPFS node via `ipfs add -r <path to unzipped boostrap release> wouldn't be necessary, if somebody who creates the releases and publishes them on MaxCDN anyway, would quickly publish them on IPFS as well and announce the hashes on http://getbootstrap.com/getting-started/**

**Comment by pruflyos** [comment]
I just corrected the description of this feature request. It it not correct that files are published on IPFS **under the public key** of the person who uploads them. Any file is always published **under the hash of its content**. So it doesn't matter who does it, an unmodified file will always be available under the same hash.

So this feature request is rather about just a *process step* in the release process of the bootstrap project to calculate the hashes of a new release and publishing them on the https://getbootstrap.com website, so people can avoid downloading a release zip file.

Example:
The hashes of the unzipped contents of https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip on IPFS are:
```
$ unzip bootstrap-3.3.7-dist.zip
ipfs add -r bootstrap-3.3.7-dist
added QmQ4Eux9Ur9qEirZ4MggGLLv4FG37pDLbx7EZ51BirakbP bootstrap-3.3.7-dist/css/bootstrap-theme.css
added QmWERBvuqiRyr4wug2t3LnACL8485pVrxRF9VbJpwt7smR bootstrap-3.3.7-dist/css/bootstrap-theme.css.map
added QmWkL3yitzoQwDS4TfUqEUznNcAv5zr2zuWNorTGpCTV9B bootstrap-3.3.7-dist/css/bootstrap-theme.min.css
added QmRJVLmKhceCrfyquiUtixRczdL5sWQAeV2RUBdbuXvcDT bootstrap-3.3.7-dist/css/bootstrap-theme.min.css.map
added QmbtNtuJEVzoVnKf6PNAjsAwXf6fq7hf8Ab7WD213Tt9m4 bootstrap-3.3.7-dist/css/bootstrap.css
added QmYG5TP8WA6TfuiCe49nvce727hKGECEx1b6CFxEzCFN1p bootstrap-3.3.7-dist/css/bootstrap.css.map
added QmYUaCPwvJWiueRXFSTTv8vdedWWzRhRdn8RMw35e7k67u bootstrap-3.3.7-dist/css/bootstrap.min.css
added QmbrzMumAwEPCoLs6jBdDyHz2TBjpkSFhcCHMT7fBsdFyr bootstrap-3.3.7-dist/css/bootstrap.min.css.map
added QmWhoNhVUb9bcjuKLB259VYogJpPsJaAe8dern9LK95tVN bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.eot
added QmbcbjLEC1aHy4j2qvtncevjenYwHjEF4qZ2kK5pRJzDLg bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.svg
added QmciDEkreBpY2S6Ktg1Zarbsx5K2DmHK59H261Bjr2fnuR bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.ttf
added QmaYEdLkMnEHVN8HZB2GGETottySZoHh3TnYZERke36PVr bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.woff
added QmUbUsBQbjJhm5iYba5jqibRr4A6gG3HVczSy5gs5PrMhY bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.woff2
added Qmf6hGLjL8aYXEFou9oWUmeSUk6JyAvJmrjoxzRiPwgimE bootstrap-3.3.7-dist/js/bootstrap.js
added QmNXRFREw7waGtKW9uBUze3PkR9E12HeeAQSkZQSiFUJqo bootstrap-3.3.7-dist/js/bootstrap.min.js
added QmVPCRWiZ6KyYt4fe5UYJAhQDH4qPDCiMiMfqApRrXtBLs bootstrap-3.3.7-dist/js/npm.js
added QmXNxcYpYt8yA14Cdi8rTUvSDcEQmZ1KSa92eAhsEQza6U bootstrap-3.3.7-dist/css
added Qmb3fJpXVGvUnNeRLC3P5sTXMzjpf5zq4tKt9XjhtYFf1k bootstrap-3.3.7-dist/fonts
added QmeFQhpJd6cn2Yq5RZzA1UdxAiAasArXX2pc1RYoCFqx6n bootstrap-3.3.7-dist/js
added QmPEJx9Bur2NNDPtBNT5zQ6bBnCkgYtKeNBAWRXx4j5hf2 bootstrap-3.3.7-dist
```

Hash of the entry directory (last line): `QmPEJx9Bur2NNDPtBNT5zQ6bBnCkgYtKeNBAWRXx4j5hf2`

So the release can be accessed by:
* via locally running IPFS node: http://localhost:8080/ipfs/QmPEJx9Bur2NNDPtBNT5zQ6bBnCkgYtKeNBAWRXx4j5hf2
* via ipfs.io gateway: https://ipfs.io/ipfs/QmPEJx9Bur2NNDPtBNT5zQ6bBnCkgYtKeNBAWRXx4j5hf2

**Comment by bardiharborow** [comment]
I doubt the rest of the team would be interested in this, but I might if I get around to it. For reference IPFS is just another P2P DHT.

**Comment by mdo** [comment]
Cloisng as stale.
