### ISSUE TITLE
tooltip: .top-left, .top-right; has a problem about left and right. it's upside dow

### ISSUE THREAD

**Issue by lu-yuan** [twbs/bootstrap#23152]
### v3.3.0: tooltip.less
```
  &.top-left .tooltip-arrow {  
    left: @tooltip-arrow-width; 
  } 

  &.top-right .tooltip-arrow { 
    right: @tooltip-arrow-width; 
  } 
```

### v3.3.7: tooltip.less  
 
```
  &.top-left .tooltip-arrow {  
    right: @tooltip-arrow-width; 
  } 

  &.top-right .tooltip-arrow { 
    left: @tooltip-arrow-width; 
  }
```

**Comment by mdo** [comment]
There's no example here to reproduce this and v3 isn't being actively worked on right now.

---

Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

_This is a saved reply._
