### ISSUE TITLE
Docs: needs to clarify if Bootstrap JavaScript plugins are required, or it just add some more functionality

### ISSUE THREAD

**Issue by m98** [twbs/bootstrap#23153]
### Current behavior
I was going to use Bootstrap 4 on my Angular 4 web app, and I prefer to not use third party JS libraries for now, and I started to read [Bootstrap 4 documentation](https://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start), the doc just say to import JS files and does not clarify why we should use JavaScript for Bootstrap and what are advantages of having or not having Bootstrap JavaScript plugins (it can also be linked to resource for more detail)

### Expected behavior
Describe what do those JavaScript plugins are going to use, and if are they required when we are going to use Bootstrap 4 or not.

- Latest version of Chrome
- Fedora 25

**Comment by mdo** [comment]
Does #23244 help?

**Comment by m98** [comment]
Yes, the edit on the doc is good! It make more sense now :+1: 
Thank you
