### ISSUE TITLE
Github pages support lacking

### ISSUE THREAD

**Issue by AbhirojPanwar** [twbs/bootstrap#23158]
I am trying to integrate bootstrap with a web page hosted on [github pages](https://abhirojpanwar.github.io). The web page, when tested on the local host, runs fine, showing all the bootstrap features. Same page, after committing does not load bootstrap at all, just displays the raw text. I believe that there is some issue with bootstrap support and github pages.

**Comment by patrickhlauke** [comment]
nothing wrong with bootstrap. i suggest you check where you put your css/js files (e.g. https://abhirojpanwar.github.io/_stylus/css/bootstrap-theme.css 404s)

**Comment by AbhirojPanwar** [comment]
Oh, I see that. I was testing on localhost, didn't know github pages work another way. Thank you! :)
