### ISSUE TITLE
Standardised heights for input groups and buttons not working on label elements

### ISSUE THREAD

**Issue by callumstrubi** [twbs/bootstrap#23166]
https://jsfiddle.net/3qydno2e/1/

OS: Mac OS X Sierra 10.12
Safari Version 10.1.1 (12603.2.4)

**Comment by bkdotcom** [comment]
culprit is reboot.scss     

```
label {
   margin-bottom: .5rem;
}
```

**Comment by mdo** [comment]
`.btn` classes aren't _meant_ to be applied to anything but a `<a>` and `<button>` elements, but they can obviously work on anything. For some of those elements, you'll need additional styles or overrides to display it properly. In this case, consider a `.mb-0` on the `<label>`.

I'm going to close as a won't fix for now, but open to revisiting in the future.
