### ISSUE TITLE
Carousel navigation problem (v4)

### ISSUE THREAD

**Issue by noir04** [twbs/bootstrap#23165]
OS: 
- Windows 10

Browsers:
- Chrome - 59
- Firefox - 54
- IE - 11
- Edge - 40

"Test case":
https://v4-alpha.getbootstrap.com/components/carousel/#with-controls

When doubleclicking the navigation arrows I end up at:
https://v4-alpha.getbootstrap.com/components/carousel/#carouselExampleControls
Instead of just advancing the carousel on the first click, and ignoring the second because of the animation
(on edge a triple click is "needed" to activate the problem)

The problem isn't present in bootstrap v3's carousel

Always calling e.preventDefault() when clicking instead of only sometimes would probably solve the problem.

**Comment by Johann-S** [comment]
Related to : https://github.com/twbs/bootstrap/pull/21743

Fixed in our current dev sources and will be available in our next release thanks 👍
