### ISSUE TITLE
Calling .tab("show") removes .active class from all children of tab-pane

### ISSUE THREAD

**Issue by albb0920** [twbs/bootstrap#23169]
Hi
When using v4_dev branch,
if one calls .tab("show"), it would remove all .active class from every tab-pane children.
This doesn't happen in alpha release.

I found this line seems to be the cause.
https://github.com/twbs/bootstrap/blob/db2db6cd0e654ddc3bfac5be5fbc93bf2bb3a674/js/src/tab.js#L151

**Comment by Johann-S** [comment]
Will be fixed by : https://github.com/twbs/bootstrap/pull/23087
thank you 👍
