### ISSUE TITLE
Switch back to the official vnu.jar for HTML validation

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23171]
I might have a look myself when I have some time.

Note that alternatively we could use https://github.com/zrrrzzt/html-validator-cli which shouldn't require Java installed.

**Comment by mdo** [comment]
No Java dependencies, please :).

**Comment by XhmikosR** [comment]
Sure, I don't like it either, believe me!

But what we have now is pretty much useless. It's like we don't have a validator. Only the official one can guarantee we are doing things right.

**Comment by XhmikosR** [comment]
BTW the cli I list above should work, I'll give it a try when I have some time and ping you guys.

**Comment by mdo** [comment]
> But what we have now is pretty much useless. It's like we don't have a validator. Only the official one can guarantee we are doing things right.

Why is it useless?

**Comment by XhmikosR** [comment]
Well, I shouldn't have said useless, but it's bad. The HTML specs exist for a reason. And vnu.jar is the official tool to do this job. I mean no disrespect for htmllint, but it just doesn't make sense to me to not use the official tool which follows the specs since they make the specs.

**Comment by XhmikosR** [comment]
Anyway, I had a look at html-validator-cli. It works fine, except it doesn't accept glob patterns. So we need a node script helper to do this job.

**Comment by bardiharborow** [comment]
[html-proofer](https://github.com/gjtorikian/html-proofer) might be worth a look, as suggested by [Jekyll's continuous integration advice](https://jekyllrb.com/docs/continuous-integration/travis-ci/).

**Comment by XhmikosR** [comment]
That isn't the official validator either. html-validator-cli is as close as
we can get to the official validator and without Java. We just need a
custom wrapper since it doesn't accept wildcards.

**Comment by Herst** [comment]
I see `html-validator-cli` also has the ability to ignore specific warnings which is very useful e.g. when using some workarounds for [certain Mozilla Firefox bugs and oddities](http://bugzil.la/654072).

**Comment by XhmikosR** [comment]
One example of broken HTML not caught by the current solution https://github.com/toshimaru/jekyll-toc/issues/25

**Comment by XhmikosR** [comment]
Another one... https://github.com/twbs/bootstrap/pull/23184

**Comment by mdo** [comment]
The toc issue was a problem with me having _two_ toc generators on that page.

**Comment by XhmikosR** [comment]
Yup, still the current solution didn't warn us, did it? :P

**Comment by XhmikosR** [comment]
@mdo: here are the remaining issues minus the ones we'd ignore anyway about `img` missing `src`.

https://gist.github.com/XhmikosR/9e417efb51b3b7b86c8502c8bb36b7a0

Until we have a proper HTML validation solution again.
