### ISSUE TITLE
Carousel Navigation Results in Page Jump When Clicked Quickly

### ISSUE THREAD

**Issue by ZacharyDraper** [twbs/bootstrap#23176]
The carousel navigation buttons in version 4.0.0-alpha.6 cause the page to jump to the top of the carousel when the the buttons are clicked before the animation completes from a previous click. To test, simply [open this JSBin](https://output.jsbin.com/ruzokiz) and click the navigation buttons in quick succession. You will notice after your second click that the page jumps so that the carousel is positioned at the top of your browser window. This is also reproducible in the [Bootstrap Documentation](https://v4-alpha.getbootstrap.com/components/carousel/#with-controls).

I have tested on Chrome 59.0.3071.115, Firefox 54.0.1, and Safari 10.1.1 all on Mac OS X 10.12.5.

**Comment by marcoarib** [comment]
Same here.
Chrome 59.0.3071.115, Firefox 54.0.1, Edge 40.15063.0.0 (Windows 10)

**Comment by XhmikosR** [comment]
I can't reproduce with the latest v4-dev.

https://output.jsbin.com/lalimoqeni/1

**Comment by XhmikosR** [comment]
So , I'm gonna close as fixed.

**Comment by patrickhlauke** [comment]
see also https://github.com/twbs/bootstrap/issues/23165
