### ISSUE TITLE
Bootstrap 4 flex push, pull, offset

### ISSUE THREAD

**Issue by Mike667** [twbs/bootstrap#23179]
In v4 push, pull, offset was removed? Because i cant find it in css file, but it is in official docs. Instead push, pull, offset now used ml-auto, mr-auto?

**Comment by jipexu** [comment]
true

**Comment by IamManchanda** [comment]
Source ordering replaces push and pull!

**Comment by Chinese1904** [comment]
you need to use float-left and right from now on. You can read about it in the docs.

**Comment by Mike667** [comment]
what about flexbox offset? i make it with margin auto, its right way?

**Comment by XhmikosR** [comment]
Yup.

**Comment by rlamorea** [comment]
This change also dropped the related mixins.  I'm not seeing an alternative to the `make-col-offset` mixin.  Perhaps I'm missing something?  Or has the option to control column offset (or, I guess, auto alignment) via mixins been dropped?
