### ISSUE TITLE
IE11 vertical-center not working - Bootstrap 4 Alpha 6

### ISSUE THREAD

**Issue by weilinzung** [twbs/bootstrap#23174]
I try to use class`align-self-center`;  and style on the parent div -> 'display:flex'; `justify-content:center;` for vertical centering, but on IE 11 layout which is broken. On IE EDGE is fine. Any ideas?

- Bootstrap 4 Alpha 6
- Windows
- IE 11
- example: https://codepen.io/anon/pen/PWLQME // screenshot: https://i.imgur.com/MTWywCp.png

Thanks!

**Comment by XhmikosR** [comment]
@weilinzung: I think you are doing something wrong.

Try this https://codepen.io/anon/pen/MvKQyX

This is with the latest v4-dev.

**Comment by weilinzung** [comment]
I don't think that markup is work for two columns`col-lg-6`, if there are two columns all of them will just vertical align not horizontal align. thanks!

**Comment by XhmikosR** [comment]
Then provide your full markup and use the latest dev version in your codepen.

**Comment by weilinzung** [comment]
sure, here is the link: https://codepen.io/weilinzung/pen/dzGqRg

**Comment by XhmikosR** [comment]
But that is still using alpha. And you are using stuff that don't exist like `col-sm-1-4`. Please use my codepen and adapt it to demonstrate your issue.

**Comment by weilinzung** [comment]
`v4-dev` it is also `v4.0.0-alpha.6 `, please check.  I also not sure what are the difference, I think the problem it is the parent & child problem while using `flexbox`.

It is working now: https://codepen.io/weilinzung/full/brExme/

anyways, thanks!
