### ISSUE TITLE
[v4][examples] Modal not closing when tooltip hovered

### ISSUE THREAD

**Issue by v-Stein** [twbs/bootstrap#23173]
### Environment information

- OS: Windows Server 2012
- Tested browsers: 
    - Chrome 59.0.3071.115 (64 bits)
    - Firefox 54.0.1 (64 bits)
    - Safari 10.1.2

### Steps to reproduce

1. Go to the [official modal documentation](https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers)
2. Click the `Launch demo modal` button
3. Hover a tooltip then try to close the modal (with `Close` button or `x` button

### What is expected?

The modal should close itself correctly and give control on the window back to the user.

### What happens instead?

The modal never closes resulting in a window stuck on the `Tooltips and popovers` modal demo.

**Comment by Johann-S** [comment]
Fixed here : https://github.com/twbs/bootstrap/pull/21743
will be available in our next release thanks 👍
