### ISSUE TITLE
Replace base64 gif placeholder images with SVG ones

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23185]
Currently we use gif base64 placeholder images in a few pages. We should switch to SVGs.

**Comment by bardiharborow** [comment]
I don't overly mind either way, but as the person who designed those GIFs, I'll just provide some context. I designed those GIFs to replace the previous base64-encoded images that were heavily suboptimal. The GIFs are the smallest 1x1px image file possible, and IIRC were stolen from [mathiasbynens/small](https://github.com/mathiasbynens/small) and manually hexedited to be the correct color. I'm happy to replace with SVG alternatives, but I'm not sure what the point would be.

**Comment by bardiharborow** [comment]
@XhmikosR You've said over in #23186 that you don't want the SVGs base64 encoded. Isn't the whole point of base64 encoding so that you can still use `<img>` tags and users of the template can quickly swap in an image of their own without having to replace inline svg? Or maybe that's really not an important use-case.

**Comment by XhmikosR** [comment]
Sure, but this is a one-time thing we need to do. The SVG doesn't need to be readable since it's just a few characters long.

**Comment by XhmikosR** [comment]
Generally the SVG will be smaller than the current gif. Compression will be slightly better and there's no reason not to use SVGs everywhere anymore. :)

**Comment by Varunram** [comment]
@XhmikosR can we close this? :)

**Comment by XhmikosR** [comment]
Nope, still a valid request :)

**Comment by Varunram** [comment]
Oh no, strike 2 :( I thought there were no gifs left, my bad

**Comment by XhmikosR** [comment]
Yeah, I never got to look into it, although there's a PR available too.
