### ISSUE TITLE
Headline should have a text-transform variable

### ISSUE THREAD

**Issue by MickL** [twbs/bootstrap#23197]
Currently setting headings to uppercase requires custom style for h1-h6 and .h1-.h6

**Comment by Johann-S** [comment]
Which release of Bootstrap do you use ?

**Comment by MickL** [comment]
v4.0.0-alpha.6

**Comment by gijsbotje** [comment]
@MickL so you would like a default class for heading uppercase? something that `.text-uppercase` does?

**Comment by MickL** [comment]
A variable like $headings-font-family

**Comment by mdo** [comment]
> Currently setting headings to uppercase requires custom style

Makes sense to me. No plans to provide an empty class or variable for this.
