### ISSUE TITLE
Card should have variables border and box-shadow

### ISSUE THREAD

**Issue by MickL** [twbs/bootstrap#23195]
- Card needs a variable to set a box-shadow. Currently we have to create a custom _card.scss only for the box-shadow.
- Card may needs a variable to show border by true/false. Currently we have to set $card-border-width to 0 and $card-border-color to transparent.

**Comment by mdo** [comment]
> Card needs a variable to set a box-shadow

Cards don't have box-shadows to start, so there's no reason to provide a variable for that.

> Card may needs a variable to show border by true/false

We don't toggle borders by variable like that.
