### ISSUE TITLE
input[type=number] placeholder clipped in Firefox

### ISSUE THREAD

**Issue by judowalker** [twbs/bootstrap#23209]
The placeholder is clipped in an input of type number in Firefox on Windows 10. This only happens with a class of `form-control`.

Minimal working example with latest dev:
https://codepen.io/anon/pen/NvRpgJ

**Comment by XhmikosR** [comment]
Works fine with Bootstrap alpha-6.

https://codepen.io/anon/pen/oezpKq

**Comment by judowalker** [comment]
I'm using the latest from v4-dev, not the cdn.

**Comment by XhmikosR** [comment]
Then please make a bin with rawgit and the files from the v4-dev branch.

**Comment by XhmikosR** [comment]
OK, confirmed: https://codepen.io/anon/pen/MvjXYj

/CC @mdo: did something change markup-wise or is the markup used fine?

**Comment by 36864** [comment]
I played around a bit with your demo and it looks like increasing line-height from 1.25 to anything over 1.39948 will fix it.
It's weird because it's not a progressive thing, it's fully clipped at 1.39947 and fully visible at 1.39948.

**Comment by mdo** [comment]
I don't see the issue in Firefox 53 on macOS.

**Comment by XhmikosR** [comment]
I definitely see it on Windows with FF 55 and 56 with the codepen I pasted above which is using the latest v4-dev version.

**Comment by XhmikosR** [comment]
For me, it gets fixed with `>= 1.381`. I believe it's due to the font being used on Windows; Segoe UI. If I switch the font to Arial, it's OK with 1.25.

**Comment by XhmikosR** [comment]
IE 11 and Edge work fine on the same Windows system.

**Comment by XhmikosR** [comment]
Hmm, I just noticed. The pen above doesn't include `<meta name="viewport" content="width=device-width, initial-scale=1">`. After adding that it is fine. Also, the `input`s are of type `number` yet their `placeholder` was text in the original codepen.

So I believe this is a non issue after all. See https://codepen.io/XhmikosR/pen/zdzvad

**Comment by XhmikosR** [comment]
If that's the case we should also close #23227 too.

**Comment by judowalker** [comment]
@XhmikosR your example is not showing the bootstrap styles because it has a console error:
```
Refused to execute script from 'https://github.com/twbs/bootstrap/raw/v4-dev/dist/js/bootstrap.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
It also doesn't have a placeholder.
It also doesn't include `<meta name="viewport" content="width=device-width, initial-scale=1">` which you stated fixes the issue.

> Also, the inputs are of type number yet their placeholder was text in the original codepen.

I don't understand what you are saying here. Why can't a placeholder be text?

**Comment by XhmikosR** [comment]
Please check the codepen [above](https://github.com/twbs/bootstrap/issues/23209#issuecomment-321518445). I'm still not sure your codepen is right or not and I don't have the time to investigate this more.

Someone else will have to have a look.

**Comment by judowalker** [comment]
That's the one I checked. See the screenshot below. It doesn't even have a placeholder and there's no Bootstrap styling.
![image](https://user-images.githubusercontent.com/5522073/29227799-2093e0ae-7e8c-11e7-9dc6-5bd499cf69c5.png)

**Comment by mdo** [comment]
Appears other input types have issues, too, with Firefox :\. #23355

**Comment by chiraggmodi** [comment]
@mdo don't see this issue any other input type. its appear only in number type.

**Comment by QuantumHive** [comment]
Can confirm this for `Windows 10, Firefox 55`:
![capture](https://user-images.githubusercontent.com/2554952/29707274-032d7788-8985-11e7-9e77-3a1179445a68.PNG)

No problems in `Windows 10, Chrome 60`:
![capture](https://user-images.githubusercontent.com/2554952/29707329-394fccb2-8985-11e7-9429-3f0dcab755f4.PNG)

**Comment by TravellerSam** [comment]
Also clipped in Firefox 55/Linux. Setting the `line-hight` to 1.35 in `$input-btn-line-height` fixes it.
Screenshots: https://github.com/twbs/bootstrap/issues/23347#issuecomment-324674515

**Comment by mdo** [comment]
Consolidating issues; closing for #23347.
