### ISSUE TITLE
Segmented buttons problem on Safari

### ISSUE THREAD

**Issue by rshmiraf** [twbs/bootstrap#23202]
Hi,
Safari and Chrome difference. Newest macOS
here : http://v4-alpha.getbootstrap.com/components/input-group/#segmented-buttons

![screen shot 2017-08-02 at 14 27 54](https://user-images.githubusercontent.com/14861637/28873679-f5156262-778e-11e7-9e3a-3f29b9417b9f.png)

**Comment by mdo** [comment]
Duplicate of #21593.
