### ISSUE TITLE
Carousel problem on Safari

### ISSUE THREAD

**Issue by rshmiraf** [twbs/bootstrap#23201]
Hi,
I found bug on Safari (newest macOS). I think that action doesn't prevent until change slide is finished.
[https://media.giphy.com/media/l41JSNp6lP306HCla/giphy.gif](https://media.giphy.com/media/l41JSNp6lP306HCla/giphy.gif) - here is example (gif)

On Chrome works fine (you can't change slide while animation). 
Example is from your documentation.

**Comment by XhmikosR** [comment]
@rshmiraf: please try the latest v4-dev. It should work.
