### ISSUE TITLE
Tooltips and popovers problem

### ISSUE THREAD

**Issue by rshmiraf** [twbs/bootstrap#23203]
Hi,
After hover on tootip i cant close modal. Newest macOS, doesn't work on Chrome and Safari.
https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers - here's where i found bug

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/21743
will be available in our next release thanks 👍
