### ISSUE TITLE
flex-x

### ISSUE THREAD

**Issue by P9Q** [twbs/bootstrap#23210]
Please add flex-x class to bootstrap 4, x is a variable:
```sass
.flex-#{$x} {
    flex: #{$x};
}
```
![](http://ninamind.com/flex-x.png)

**Comment by mdo** [comment]
I'm unsure what you're asking for here—we have dozens of flex utilities. Why do we need one with a variable in the name? How does that even work in Sass?

**Comment by P9Q** [comment]
@mdo, I do agree that the BS4 covers flexbox very well, but due to my BS4 experience `flex: n;` was the only thing that forced me to create a class for the elements,  Check this [Codepen ](https://codepen.io/mraccount/pen/RZoKKP)please, maybe 90% of people don't need more than `flex: 12;`, for those who need more than 12 they can do it manually, However, you can change 12 to a reasonable number.

**Comment by 36864** [comment]
Essentially this would be an alternative to sizing through the grid system. 
Rather than a fixed width for each column with col-X, you'd have flexible widths with flex-X.
Forked your pen to see how mixing and matching would work:
https://codepen.io/anon/pen/KvNmQM

I think I like it.

**Comment by mdo** [comment]
I don't think this is a great mental model for creating flexbox layouts. Your `.flex-12` is 12x the width of your `.flex-1` there. In a practical application, you might have a `.flex-2` and a `.flex-1`, but in the context of our existing grid system, that's rather confusing. It'd be a 2/3 and 1/3 display, but so would `.col-8` and `.col-4`.

**Comment by 36864** [comment]
I don't feel very strongly either way, but I think you're rather missing the point of these.
The grid system's column classes are great, but they're fixed-width. These new flex classes would be variable width. Here's a use case:
You want to display some data in a grid. By default, you'll want two columns and, for consistency's sake, let's say you want the first to be 2/3 of the container and the second column to be 1/3, so you define them as `col-8` and `col-4` respectively.
Now imagine there's a third, optional column. You want this column to be the same width as the second one, but you still want the first column to be the same size.
With the current system, you could resolve this by making the second column `col-2` and add the new one also as `col-2`. If you're doing it server-side, it's an if statement. If you're doing it dynamically, you're messing with the existing data just to add a new column.

Sure enough, for this simple example case you could use the new `col` class for the second and third columns, but if you make it just a little bit more complex with wanting the second column to be a bit bigger than the third, you're back to altering the existing columns to add a new one.

With flex classes, you could still define a fixed-length first column, set the second column to, say, `flex-4` and add the third column as `flex-3`. Together, columns 2 and 3 add up to `col-4` with a ratio that simply cannot be expressed by the default grid.

**Comment by mdo** [comment]
> but I think you're rather missing the point of these. The grid system's column classes are great, but they're fixed-width. These new flex classes would be variable width. 

I understand exactly what these are and how they function, and don't think it's worth the complication right now. We have responsive variations for each breakpoint—the full implementation in Bootstrap would require 5x the classes you've listed here for full responsive behavior. We'll pass on it, thank though.
