### ISSUE TITLE
btn-group with btn-primary missing separator in BS4

### ISSUE THREAD

**Issue by langdonx** [twbs/bootstrap#23213]
When using `btn-primary` inside of a `btn-group`, there's no border between the buttons like there was in 3 or like there is with `btn-secondary`.  I assume this is not by design.

This is on Windows 10, Chrome 60.

Bootstrap 3: https://jsfiddle.net/9uh3p6yq/1/
Bootstrap 4: https://jsfiddle.net/o71u2o9f/1/

![image](https://user-images.githubusercontent.com/441982/28934903-9f20602e-7850-11e7-87d8-aed9f3f49dd9.png)

...apologies for mspaint.

**Comment by mdo** [comment]
It's not missing, the colors are the same to start in v4.
