### ISSUE TITLE
_forms.scss padding & $input-btn-padding-x

### ISSUE THREAD

**Issue by bbmatt** [twbs/bootstrap#23211]
Using v4 on a custom build with a design that has a fair amount of x-padding on buttons.

 _forms.scss uses the $input-btn-padding-x variable for x-padding, so modifications to this variable has adverse impact on horizontal form input padding.

For my custom build I'll isolate those variables & create a new set for form padding - or at least padding-x variables.

Is this something that could be addressed in a future release, a new set of variables that control form input padding?

**Comment by mdo** [comment]
We tied them together on purpose in a previous alpha release. No plans to separate.
