### ISSUE TITLE
Grid issue safari and ucbrowser.

### ISSUE THREAD

**Issue by carloboy16** [twbs/bootstrap#23218]
Hello the i have a problem on gridding system the the column is adjusting the width but its not wrapping instead its overflowing
see the site in safari
https://eiexchange.com.au/index.php#

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by nimmolo** [comment]
Possible duplicate of #23193

**Comment by mdo** [comment]
Closing as duplicate of #23193.
