### ISSUE TITLE
Actions vs Links inside of Dropdowns

### ISSUE THREAD

**Issue by langdonx** [twbs/bootstrap#23224]
With the idea that cursors now convey meaning (https://github.com/twbs/bootstrap/pull/21812), the `dropdown` documentation seems to need some love.  The examples in the documentation refer to "actions" and "links", but each `dropdown-item` is just ultimately just an anchor (a link).

I'd be happy to submit a PR to improve the documentation (using `a` for links and `button` for actions with a small paragraph describing intent).

** Edited out link/button font nonsense that's already fixed.

**Comment by mdo** [comment]
`.dropdown-item`s can be buttons. I think ultimately I just need to bring back the `cursor: pointer`. We'll see how it goes in the first beta.

**Comment by langdonx** [comment]
Oh man, don't give up... it's such a great paradigm!

Imagine a web where you know what you can <kbd>Ctrl</kbd>/<kbd>Command</kbd>-click to open a new tab that contains exactly what you're expecting, instead of having to try it out and discover that someone just hacked another anchor and you end up with a new page with either the same content or if it's a url that's still using hash bang, the root of the site.  Same goes for <kbd>Shift</kbd>-click, middle-mouse-click, or any other way one might open a new tab or window.

It's going to be an uphill battle educating people, but the reasoning behind it is so sound.
