### ISSUE TITLE
col-*-auto does not reset max-width

### ISSUE THREAD

**Issue by inaitana** [twbs/bootstrap#23238]
When implementing a responsive grid layout, with a fixed col-n rule and a col-\*-auto after a given breakpoint, the fixed class for the smaller layout includes a max-width rule, while col-\*-auto doesn't overwrite it.

I.e. using "col-6 col-lg-auto":
1) col-6 would apply both "flex: 0 0 50%;" and "max-width: 50%"
2) col-lg-auto would only apply "flex: 0 0 auto" and "width: auto"

the max-width from 1) is still in effect at higher resolutions.

Demo [here](https://codepen.io/anon/pen/QMdeja)

**Comment by Johann-S** [comment]
Seems to be fixed with our last dist files : https://codepen.io/Johann-S/pen/gxgVRW ?

**Comment by inaitana** [comment]
It is indeed!
Sorry for not checking

**Comment by Johann-S** [comment]
Closed as resolved 👍 
That's ok @inaitana 👍
