### ISSUE TITLE
tooltip.js data-placement implementation

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#23235]
Hi
- as i look for solve this problem :
how to use tooltip on truncated element (with text-truncate) ...
in this case the tooltip is positioned on the middle axis of the original width element what is not acceptable and also the the text-truncate provide a second tooltip (browser?) starting at the mouse position ...

- so i said me i will use the data-placement top-start (but is not implemented in our js) so i quick and dirty modified the var AttachmentMap as adding "TOP-START":"top-start", "TOP-END":"top-end",

so now i can use top-start to solve this problem and it's work fine except that i havent the arrow on this case (forgot something in the js or is a popper.js problem ? )

I think it will be good, as we provide the use of data-placement, that we can use all (or let say the main) properties provided by popper for this attribut  ?? 

what are your advice on this ?

Thanks

**Comment by Johann-S** [comment]
This is related to : https://github.com/twbs/bootstrap/issues/22962
But yes we'll handle all the Popper's position 👍 

And we are open to any PR if someone want to tackle that 😄
