### ISSUE TITLE
Why custom selectbox has the same arrow as default one.

### ISSUE THREAD

**Issue by kleninb** [twbs/bootstrap#23236]
Does this make any sense to use the same style as user-agent, why 'custom-select' then? and single dropdown would be nice for the select box. And multi-arrows for multi-sections.

<img width="654" alt="browser-default" src="https://user-images.githubusercontent.com/7715837/29025123-e57943a2-7b92-11e7-9dc7-98f60fae4c23.png">
<img width="625" alt="rwoj_vmyrviw4kvg0vediw" src="https://user-images.githubusercontent.com/7715837/29025124-e58f019c-7b92-11e7-88ae-e1439e5e2d83.png">

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by kleninb** [comment]
@Johann-S Please check this, what is the difference between these 2 drop downs other than some border, colors and padding.
My question why using custom then if the default browser has the same styles?
My browser firefox: 54 and chrome: 59.

https://jsbin.com/tojofekide/edit?html,output

**Comment by kleninb** [comment]
This is good example of custom select-box
https://codepen.io/vkjgr/pen/VYMeXp?editors=1100#0

**Comment by Johann-S** [comment]
That's because we want to ensure every users who use Bootstrap have the same result in every browsers

**Comment by mdo** [comment]
Arrow style is a matter of personal preference and easy customization.
