### ISSUE TITLE
Add semicolon on example code in layout/grid docs page.

### ISSUE THREAD

**Issue by ivan-vilches** [twbs/bootstrap#23242]
Hello, in this doc page https://v4-alpha.getbootstrap.com/layout/grid/  in the **Variable** example , please add a semicolon at the end of the map .

```
$grid-gutter-widths: (
  xs: $grid-gutter-width-base, // 30px
  sm: $grid-gutter-width-base, // 30px
  md: $grid-gutter-width-base, // 30px
  lg: $grid-gutter-width-base, // 30px
  xl: $grid-gutter-width-base  // 30px
)  // **here add a semicolon;**
```

Because its can cause errors in preprocessors like Koala.
Thanks you and apologies because i dont know how add tags to this issue.

**Comment by mdo** [comment]
This is no longer an issue in `v4-dev`—grid gutters are gone temporarily.
