### ISSUE TITLE
btn-link colors

### ISSUE THREAD

**Issue by langdonx** [twbs/bootstrap#23240]
When using `text-danger` (or any others) with `btn-link`, hover and focus states don't affect the color because of `!important` on `text-danger`.

https://jsfiddle.net/oo7xy2bL/1/

Is this up for consideration for v4, or is the extra CSS not worth it?  I'm trying to break away from misusing anchors and desperately want consistent focus/hover effects.  I know icons were taken out, but this also helps with making clickable icons that still adhere to the palette.

Related v3 issue: https://github.com/twbs/bootstrap/issues/15940

**Comment by bkdotcom** [comment]
It doesn't really make sense to have both `btn-link` and `btn-danger`  on the same button

I don't believe there's any plans to have hover states for the text-* utility classes.  (ie text-danger)

**Comment by langdonx** [comment]
Yea, it doesn't, I was just trying different permutations to see if what I wanted already was possible.

Here's the code... it doesn't seem to add too much CSS and is incredibly helpful in avoiding anchor hacks and using clickable icons.

```
@mixin btn-link-text-emphasis-variant($parent, $color) {
  .btn-link {
    &#{$parent} {
      @include hover-focus {
        color: darken($color, 10%) !important;
      }
    }
  }
}

@include btn-link-text-emphasis-variant('.text-success', $brand-success);
@include btn-link-text-emphasis-variant('.text-info', $brand-info);
@include btn-link-text-emphasis-variant('.text-warning', $brand-warning);
@include btn-link-text-emphasis-variant('.text-danger', $brand-danger);
//  not sure if other text colors warrant the treatment?
```

**Comment by mdo** [comment]
If you need more than the `color` change, use custom styles. I don't see us adding another utility that basically does the same thing as our existing ones. Utilities aren't meant for every situation.
