### ISSUE TITLE
class="row flex-column-reverse flex-md-row" doesn't display properly in Safari, mobile Firefox, mobile Chrome, mobile Safari

### ISSUE THREAD

**Issue by JonathanNickerson** [twbs/bootstrap#23258]
class="row flex-column-reverse flex-md-row"

doesn't display properly in desktop Safari, mobile safari, mobile Chrome, and mobile Firefox. It seems to work fine in desktop Chrome and desktop Firefox.

    flex-md-row

seems to be the culprit. Basically, adding the class `flex-column-reverse flex-md-row` to a row causes the row below it to overlap it in Safari when collapsing to smaller than md screen sizes.

Example: https://jsbin.com/suyuzizoba/1/edit?html,output

I'm on macOS 10.12.5 and multiple browsers as stated above.

**Comment by mdo** [comment]
That class isn't the culprit—it's styles don't apply at all on the lower breakpoint.

**Comment by JonathanNickerson** [comment]
derp yea my bad. I think it is the flex-column-reverse causing the weirdness.

**Comment by XhmikosR** [comment]
Is this a valid issue?
