### ISSUE TITLE
`::before` from headings overlap previous element

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23252]
See the gif for a demonstration.

Opening the issue to track this.

A potential fix would be to reduce height and margin-top.

![2017-08-08_18-19-25](https://user-images.githubusercontent.com/349621/29079661-67cb8f30-7c66-11e7-8e3f-89bc3ae3d4e4.gif)

/CC @Johann-S

**Comment by mdo** [comment]
Leave it to Microsoft... It's a hack for offsetting the `position: sticky`. I have an idea on what could help.

**Comment by XhmikosR** [comment]
This doesn't have to do with IE :P

My suggestion is reducing height and margin-top to 4rem or something similar. Or do something else when `.highlight + h2::before`.
