### ISSUE TITLE
Not Showing in contributors lists

### ISSUE THREAD

**Issue by chiraggmodi** [twbs/bootstrap#23261]
sorry for bothering,
one of my pull request in merge in v4-dev, but i am not seeing my self in [contributors list](https://github.com/twbs/bootstrap/graphs/contributors). 
is there any thing wrong i did?
this is my first contribution to community so it may sound fumy, but i just curious.

**Comment by tomlutzenberger** [comment]
Is it already merged or still pending? If it's not merged, I guess that's the reason. It would make sense to only display contributors in the graph, when their changes have already applied.

**Comment by XhmikosR** [comment]
My guess it's because you have 1 commit and there must be either a limit by GitHub (4 for this repo) since there are too many contributors, or a bug. I'd say it's the former but you can ask GitHub support for more info :)

**Comment by chiraggmodi** [comment]
@tomlutzenberger its already merged.
@XhmikosR i will ask in GitHub support, Thank for the help.
