### ISSUE TITLE
Always use HTTPS for getbootstrap.com

### ISSUE THREAD

**Issue by mritzmann** [twbs/bootstrap#23262]
I recommend to use always SSL for getbootstrap.com. HTTPS has numerous benefits that are not available over unencrypted HTTP, including improved performance with HTTP/2, SEO benefits for search engines like Google and the reassuring lock icon in the address bar.

Cloudflare _(whitch is use for getbootstrap.com)_ has a option for that.

![ssl](https://user-images.githubusercontent.com/4533780/29119490-a192f8a2-7d06-11e7-8391-76d049026f33.png)

**Comment by XhmikosR** [comment]
Agreed, I have already suggested this to @mdo like a year ago. Maybe now it's a better time @mdo? :)

**Comment by XhmikosR** [comment]
@mdo: any progress on this? There shouldn't be any issues nowadays with everything that Cloudflare is offering.

**Comment by bardiharborow** [comment]
Also, HSTS preloading?

**Comment by jgacuca567** [comment]
@mritzmann the current site is using https. See https://getbootstrap.com/

**Comment by mdo** [comment]
I've enabled always enforce HTTPS.

**Comment by XhmikosR** [comment]
@mdo: can you also enable HSTS? As a first step choose a small age, and we increase it later with eventually 1 year to match HSTS preload's list requirements.
