### ISSUE TITLE
Flexbox order documentation

### ISSUE THREAD

**Issue by oskar1233** [twbs/bootstrap#23269]
https://v4-alpha.getbootstrap.com/utilities/flexbox/#order

The docs are inconsistent: `<div class="flex-last p-2">First flex item</div>` - here we can see `flex-last`, but in the "responsive variations" list the prefix is `order`, not `flex`, which is wrong.

**Comment by XhmikosR** [comment]
This is fixed in v4-dev. https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/utilities/flex.md#order
