### ISSUE TITLE
Bug in "Live Demo" example code in bootstrap/docs/4.0/components/modal.md

### ISSUE THREAD

**Issue by Martin521** [twbs/bootstrap#23265]
The demo code below "Live Demo" does not work when copied because `data-target="#exampleModal"` in the button does not match the `id="myModal"` in the Modal.

I would love to help out and create a fix (in the above file around line 1564), but I can't figure out how the example code is generated from the md.

**Comment by patrickhlauke** [comment]
already fixed in the repository. thanks.
