### ISSUE TITLE
Bootstrap V4-aplha Carousel bug

### ISSUE THREAD

**Issue by mrvincentlee** [twbs/bootstrap#23272]
Hi,

Looking at this example: https://v4-alpha.getbootstrap.com/examples/carousel/
If I double click quickly on either the carousel-control-next or prev, then the site drops into the browser slightly. I thought this was a problem with the website I was building, but it looks like it does it as well on your own link. 

I've tested this issue in IE, Chrome, and Firefox and it happens in all of them. 
In fact in IE the problem is even worse, I've attached two videos, one of Chrome and the other of what happens in IE. In IE there is just no slide animation.

I'm trying to build my site in the Aplha, but it looks very buggy so I might just stick to bootstrap 3. 

Browser versions as follows
IE = 11.0.9600
FF = 52.0
Chrome = 60.0.3112.90

Is this is a known issue and something in for a fix already? Is anyone aware what could be doing it?
Any help is appreciated. 
Lee

[Videos.zip](https://github.com/twbs/bootstrap/files/1214966/Videos.zip)

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/21743
Will be available in our next release thanks 👍
