### ISSUE TITLE
Variable overwrites

### ISSUE THREAD

**Issue by vivek-roy** [twbs/bootstrap#23270]
Hello

I have set up a build environment using gulp (which builds app.scss to a css).

app.scss
```
@import "bootstrap";
```

_bootstrap.scss
```
@import "custom";
@import "../../../node_modules/bootstrap/scss/variables";
@import "../../../node_modules/bootstrap/scss/mixins";

// rest imports
```

_custom.scss
```
@import url('https://fonts.googleapis.com/css?family=Raleway:400,800');

$bg-dark: #2c3e50;
$brand-primary: #1abc9c;
$body-bg: $bg-dark;
$font-family-sans-serif: Raleway, -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
$nav-link-padding: .5em 3em !important;
```

The problem is nav-link-padding doesn't work without the ```!important```.
Am I doing something wrong?

**Comment by mdo** [comment]
Few things to note here:

- Our `v4-dev` branch no longer has ` _custom.scss` file.
- `!important` doesn't apply to variables in Sass.
- We cannot help without an example file or more details.

I'd recommend asking around in Slack or StackOverflow for more guidance on general troubleshooting and how-to questions. I don't see a bug here that we can fix.

Please do follow up though if there's something else that'd give us more context.
