### ISSUE TITLE
v4 feature request - form-control-danger icon change

### ISSUE THREAD

**Issue by mudrz** [twbs/bootstrap#23274]
Icon change suggestion

Issue:
The `x` icon in inputs in most websites usually clears/deletes the input (including most custom select implementations), so users have come to expect that clicking the `x` clears the input.
As a result many users are clicking the `x` icon of `.form-control-danger` confused that nothing is happening.
![image](https://user-images.githubusercontent.com/9587050/29175166-fbb5cfea-7df0-11e7-9b3e-9dfb3c40e271.png)

Perhaps it can be changed to a circle with an exclamation mark to communicate more clearly that this is a status indicator and not a clear button

**Comment by mdo** [comment]
Icons are gone in `v4-dev` branch until we can redo them for the new HTML5-based validation styles. See #22762 for tracking that issue.
