### ISSUE TITLE
CDN integrity in new beta docs doesn't match

### ISSUE THREAD

**Issue by Manrix** [twbs/bootstrap#23284]
I'm using the cdn from the new documentation but i get an error about integrity not matching.

**Comment by Matheus28** [comment]
Same.

Hash in the docs is currently: `sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ`

Should be: `sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M`

**Comment by XhmikosR** [comment]
Give us some time, I'm working on it. See also https://github.com/MaxCDN/bootstrap-cdn/pull/865
