### ISSUE TITLE
Reorganize 3.x docs

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#23285]
I did this all in `gh-pages`, so I'll need to make it legit soon:

- [ ] Rearrange directory structure to put docs content in `docs/3.3/`
- [ ] Add redirects from old placement in directory
- [ ] Add version picker to docs navbar
- [ ] Update tracking codes

This will make future v4 docs updates a little bit easier.

**Comment by Varunram** [comment]
@mdo We can close this issue I guess?

**Comment by XhmikosR** [comment]
@mdo: ping to close this.

**Comment by mdo** [comment]
I think we're good here.
