### ISSUE TITLE
textarea on firefox have an extra height space corresponding to the horizontal scroolbar height

### ISSUE THREAD

**Issue by SuperPat45** [twbs/bootstrap#23295]
On firefox, contrary to all other browser, textarea have an extra height space corresponding to the horizontal scroolbar height.
Whereas it is impossible to have a horizontal scrollbar on a textarea.

Assigning a rows value of 3 and it appears to have 4.

It can easily be fixed by setting:
```
textarea {
    overflow-y: auto;
    overflow-x: hidden;
}
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by SuperPat45** [comment]
Live Demo:

https://jsbin.com/pogiwaqusu/edit?html,css,output

**Comment by Johann-S** [comment]
I don't see Bootstrap in your live example 🤔

**Comment by SuperPat45** [comment]
Because it makes no difference

**Comment by mdo** [comment]
I don't think we'd want to add this universally? I did run into this on our new docs homepage, but I'm unsure if it's something we should explicitly add.

**Comment by mdo** [comment]
Closing as a won't fix for now.
