### ISSUE TITLE
Scroll Navbar when change the width of the page

### ISSUE THREAD

**Issue by jaroga** [twbs/bootstrap#23296]
Hi,
If you scroll down in http://getbootstrap.com/ and then reduce your browser, the navbar will positionate on the top of the browser like this:
![image](https://user-images.githubusercontent.com/15203343/29206438-43dcee48-7e82-11e7-9b99-ccfb0e0e8934.png)

Then, if you scroll up, the navbar stays on the middle of the page:
![image](https://user-images.githubusercontent.com/15203343/29206572-bf360e30-7e82-11e7-816c-dc11de5793eb.png)

- Operating system and version: Windows 7
- Browser and version: Chrome 56.0.2924.87

Thanks,

**Comment by XhmikosR** [comment]
Works fine with FF 56 and Chrome that I tested here. Perhaps you are hitting a breakpoint. In which width does it happen for you?

**Comment by jaroga** [comment]
Sorry, you need reduce to mobile size (less than 765px) first, then scroll down, and resize more than 765px. After that, the navbar will positionate on the top of the browser (position absolute: 0px) and if you scroll down or up you see the issue that I comment.

**Comment by XhmikosR** [comment]
I still can't reproduce here so I blame your old Chrome version.
