### ISSUE TITLE
JavaScript behavior with tabbable panes

### ISSUE THREAD

**Issue by TiBej** [twbs/bootstrap#23304]
**Description**
- On v4.0.0-beta tabbable panes aren't working. It isn't possible to switch between the tabs. It works with the bootstrap.min.js from v4.0.0-alpha.6.

**System**
- Win 10
- Mozilla Firefox

**Includes files**
```
    <!-- css -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">

    <!-- js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
```

    
**Code**
```
            <nav class="col-md-12">
              <ul class="nav nav-tabs h5" role="tablist" id="myTab">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#about" role="tab">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#web" role="tab">Web</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#reputation" role="tab">Reputation</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#skill" role="tab">Skills</a>
                </li>
              </ul>
            </nav>

            <div class="tab-content col-md-11">

              <div class="tab-pane fade show active" id="about" role="tabpanel">
                </div>

              <div class="tab-pane fade" id="web" role="tabpanel">
              </div>

              <div class="tab-pane fade" id="reputation" role="tabpanel">
              </div>

              <div class="tab-pane fade" id="skill" role="tabpanel">
              </div>

            </div>
```

**Comment by svjansen** [comment]
Code seems to work for me tried on FireFox and Chrome.

However if I bind on the `show.bs.tab, shown.bs.tab or click` event of the tab and try to load something dynamic e.g. data from db, tab is not removing the `active` class from the previous active so you'll see 2 tab contents the same time.

**Comment by XhmikosR** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by TiBej** [comment]
**Link**
[Codepen](https://codepen.io/TiBej/project/editor/ZdPyWM/)

**Bootstrap Version**
v4.0.0-beta

**Browser**
Firefox 54.0.1 (32-Bit)

**OS Details**
**OS Name:**	Microsoft Windows 10 Pro
**Version:**	10.0.15063 Build 15063
**System Type:**	x64-based PC
**Processor:**	Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
**BIOS Version/Date:**	American Megatrends Inc. 0406, 2/14/2012
**Total Physical Memory:**	15.9 GB

**Comment by svjansen** [comment]
@TiBej your example don't work you're right but it's not even working on chrome.
 If you add  [popper.js](https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js) your example works just fine for me.

See [my Codepen](https://codepen.io/nitrode92/pen/Xagwaw)

**Comment by XhmikosR** [comment]
All right, closing this since popper.js is needed.

**Comment by TiBej** [comment]
@svjansen sorry for my mistake, thx for your help

**Comment by TiBej** [comment]
Alright, i checked your example @svjansen and included popper how you said. It still didn't worked. 
The "real" problem wasn't, how i realized pooper. The mistake was that included the js file on the top of the document. It's nessesary to include it at the bottom.
