### ISSUE TITLE
Nuget package still lists alpha.6 as the latest

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23306]
https://www.nuget.org/packages/bootstrap/absoluteLatest

/CC @mdo

**Comment by supergibbs** [comment]
@XhmikosR I'm on it

**Comment by supergibbs** [comment]
Done! 

Shield isn't updated yet but link works. Is probably cached and will update in a bit.

**Comment by XhmikosR** [comment]
Thanks!
