### ISSUE TITLE
Javascript - Tab two .active .tab-panes if tab-content contains .active

### ISSUE THREAD

**Issue by svjansen** [twbs/bootstrap#23311]
## OS Details
OS Name:	Microsoft Windows 10 Pro
Version:	10.0.15063 Build 15063
System Type:	x64-based PC
Processor:	Intel(R) Core(TM) i7-3770K CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
Total Physical Memory:	15.9 GB

## Browsers
Chrome Version 60.0.3112.90 (64-Bit)
Mozilla FireFox Version 54.0.1 (32-Bit)
IE 11

## Bootstrap 
Version 4 - Beta 1

## Description
When using Tabs (Nav's or Listgroup) it's not possible to use` .active` inside `.tab-pane`.
If tab is switched and the content contains `.active` anywhere, the `.active` class is removed within the content and 2 `.tab-panes` are shown the same time.
Short: the js code is removing the `.active` from content but not from the `data-toggle="list" role="tab"`.

## Example
[Codepen](https://codepen.io/nitrode92/pen/qXjGyb)

Click on `Profile`-Tab (pagination got `.active` on an element) on `Message`-Tab and after that on `Profile`-Tab again (pagination `.active` is gone and `Message`-Tab content is shown under the pagination).

**Comment by Johann-S** [comment]
Will be fixed by : https://github.com/twbs/bootstrap/pull/23087
thank you 👍
