### ISSUE TITLE
The "About" and "Examples" link at the footer is broken on the new Bootstrap 4 website

### ISSUE THREAD

**Issue by Timber232** [twbs/bootstrap#23316]
The "About" and "Examples" link at the footer is a broken link that leads to a 404 page.

![image](https://user-images.githubusercontent.com/627637/29213879-27cecf5a-7e73-11e7-944c-c605fdcb6a3c.png)

Goes to:

https://getbootstrap.com/about/history/
http://getbootstrap.com/examples/

**Comment by XhmikosR** [comment]
The about is fixed in #23298. Examples should redirect already.

BTW @mdo, there doesn't seem to be any way to navigate in the about subpages if one goes to an /about/ page.

**Comment by Johann-S** [comment]
Thanks @XhmikosR, so I'll close this issue 😃

**Comment by XhmikosR** [comment]
OK I submitted #23318 for the about sidebar.
