### ISSUE TITLE
Should text-muted be remove from bootstrap?

### ISSUE THREAD

**Issue by stuyam** [twbs/bootstrap#23326]
Now that there is the `.text-secondary` class that is the same color as `.text-muted` should text-muted still be included in bootstrap?

Only difference is seems is that text-secondary also has link styling.

Also linking my pull-request as this will determine how that should proceed: https://github.com/twbs/bootstrap/pull/23325

**Comment by bardware** [comment]
`text-muted` is defined `.text-muted { color: $text-muted !important; }` via it's distinct color variable `$text-muted` while `text-secondary` is based on it's own variable ` $theme-colors: (  secondary ... } ` 
A developer can override the secondary color but may want muted text still to be gray-600. Why not?

**Comment by stuyam** [comment]
Makes perfect sense to me.
