### ISSUE TITLE
Automate 404 links checking

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23322]
Maybe using something like simplecrawler.

**Comment by bardiharborow** [comment]
I used to run a crawler on the docs periodically, but I've been lazy recently. I feel like this has come up before, but it was suggested that it's probably too much extra CI weight for little gain, and it could make Travis flap. A separate script might be helpful though.

**Comment by XhmikosR** [comment]
I'd rather have a CI delay than having Sauce tests run for each patch. Previously we could skip sauce tests.

And honestly, simple crawler should be pretty fast.

**Comment by mdo** [comment]
Duplicate of #18568.
