### ISSUE TITLE
V4.beta Argument `$color` of `darken($color, $amount)` must be a color

### ISSUE THREAD

**Issue by papasikis** [twbs/bootstrap#23331]
I have update bootstrap to 4.0.0-beta, and i get this error while compiling:
$link-hover-color:      darken($link-color, 15%) !default;
                       ^
      Argument `$color` of `darken($color, $amount)` must be a color
Backtrace:
	node_modules/bootstrap/scss/_variables.scss:168, in function `darken`
	node_modules/bootstrap/scss/_variables.scss:168

**Comment by agentphoenix** [comment]
Just ran into this a few minutes ago. I ended having to pull in Bootstrap's functions SCSS file before the Bootstrap variables file to fix it.

**Comment by papasikis** [comment]
@agentphoenix, and how is it working now?

**Comment by agentphoenix** [comment]
Back to actually compiling, so that's a plus. Now I'm just trying to figure out the best way to handle responsive stuff after they removed all the responsive helpers in beta1...

**Comment by maxkorz** [comment]
@agentphoenix can you show an example of how you fixed the issue? I'm following this guide https://getbootstrap.com/docs/4.0/getting-started/webpack/ and simple
```scss
@import "custom";
@import "~bootstrap/scss/bootstrap";
```
doesn't work for me

**Comment by agentphoenix** [comment]
@maxkorz I was working on splitting out my styles and the vendor styles when this started happening. I couldn't figure out for a while why it was suddenly complaining, but after following the stack trace carefully, I think I found the culprit.

My app.scss just pulls in the Bootstrap variables so I can use them in my own styles for the time being, so I had to make sure I was pulling the functions in first then my own stuff, like so:

```scss
@import '~bootstrap/scss/functions', '~bootstrap/scss/variables';
@import 'variables', 'data-table';
```

Then in my vendor stylesheet, I just pulled in Bootstrap like normal:

```scss
@import '~bootstrap/scss/bootstrap';
@import '~jquery-confirm/css/jquery-confirm';
@import '~croppie/croppie';
```

**Comment by mdo** [comment]
> Back to actually compiling, so that's a plus. Now I'm just trying to figure out the best way to handle responsive stuff after they removed all the responsive helpers in beta1...

We still have them all, they're just different class names. Instead of `.hidden-xs-up`, use `d-none`, etc. And yes, you'll need the `_functions.scss` file.

**Comment by derkjn** [comment]
I'm still stuck on this. I'm not importing anything of my own. My `main.scss` is just:
```
@import "~bootstrap/scss/bootstrap";
```
and I still get 
```
Module build failed: 
    $link-hover-color:      darken($link-color, 15%) !default;
                           ^
          Argument `$color` of `darken($color, $amount)` must be a color
    
    Backtrace:
        node_modules/bootstrap/scss/_variables.scss:168, in function `darken`
        node_modules/bootstrap/scss/_variables.scss:168
          in /Users/ignitestudio1/Sites/wp_test/web/app/themes/ignitetheme/node_modules/bootstrap/scss/_variables.scss (line 168, column 25)
```
Any help is greatly appreciated!

**Comment by myorangeca** [comment]
@derkjn you need to import the functions scss before variables

**Comment by derkjn** [comment]
@myorangeca I'm importing the `bootstrap.scss` straight from bootstrap where the functions is already before the variables.

**Comment by myorangeca** [comment]
@derkjn I am not sure how you structured your main.scss; the error should resolve by adding functions before any bootstrap variable are declared.

**Comment by WatsonWeb** [comment]
Having exact same issue as @derkjn. Trying to compile bootstrap.scss and getting the same error, even though _functions.scss is the first import in that file.

To resolve, I had to import _functions.scss BEFORE bootstrap.scss.

Not sure if this is an issue with compiler (gulp-sass) or with bootstrap.

`@import "bootstrap/scss/functions";              // Bootstrap Functions
@import "bootstrap/scss/bootstrap";              // Bootstrap`

**Comment by derkjn** [comment]
@myorangeca Thanks for your help. Like I said in the first comment, my main.scss only includes bootstrap.scss and nothing more. I don't have any other style on my project yet. Which means that there's some sort of issue in bootstrap since I haven't added a single line of code. And in the source code of bootstrap the functions are already above the variables so that's not the issue in this case.

**Comment by GJordan904** [comment]
I got it working with Webpack 3 and Angular by using:
```scss
@import "~bootstrap/scss/bootstrap";
``` 
at the top of my main app.scss and then anytime i import the variables file I do like this:
```scss
@import "~bootstrap/scss/_functions.scss";
@import "~bootstrap/scss/variables";
```
This got rid of the errors but I don't remember having to do this with alpha 6

**Comment by alienlebarge** [comment]
@derkjn I have the same problem.
When compiling with *"gulp-sass": "^3.1.0"*
```
Error in plugin 'sass'
Message:
    src/assets/styles/bootstrap-variables.scss
Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
       	src/assets/styles/bootstrap-variables.scss:168, in function `darken`
       	src/assets/styles/bootstrap-variables.scss:168
        on line 168 of src/assets/styles/bootstrap-variables.scss
>> $link-hover-color:      darken($link-color, 15%) !default;
   ------------------------^
```
But when I compile directly with *Sass 3.5.1* `$ sass myStyle.scss`, everything work fine.

**Comment by alienlebarge** [comment]
same problem here #23313

**Comment by alienlebarge** [comment]
My bad, I was compiling two `.scss` files with Gulp 🤦‍♂️ . The replica of `_bootstrap.scss` and another one wich use `_variables.scss` too.
@derkjn check in you `gulpfile.js` that your are not compiling another file.

**Comment by jgacuca567** [comment]
Using **Grunt** I got it working by 

`@import 'bootstrap';`
`@import 'includes/variables';`

**Comment by morrow95** [comment]
Same as everyone else, but importing the functions file first doesn't solve the problem.  Main scss is below :  

`
@import "../vendor/bootstrap-4.0.0-beta/scss/functions";
@import "bootstrap/variables";
@import "../vendor/bootstrap-4.0.0-beta/scss/bootstrap";
@import "bootstrap/custom";
`

**Comment by speller** [comment]
Got the same issue. Don't understand why issue is closed if it still actual???

**Comment by morrow95** [comment]
Mine is working as listed above now.  Wish I could tell you what the problem was, but I didn't change my import order at all.

**Comment by jgacuca567** [comment]
@speller 

Using **Grunt** I got it working by 

`@import 'bootstrap';`
`@import 'includes/variables';`

**Comment by rfreites** [comment]
this bug still

**Comment by mseymour** [comment]
I've been having the same issue.

Setup:

    // Modules
    @import 'modules/all'; // Variables are imported through here
    // Vendor
    @import '~bootstrap/scss/bootstrap';
    // Partials
    @import 'partials/all'; // "Custom"

Error:

    error  in ./resources/assets/sass/app.scss

    Module build failed: ModuleBuildError: Module build failed:
     background-color: rgba($form-feedback-invalid-color,.8);
                      ^
         Argument `$color` of `rgba($color, $alpha)` must be a color

    Backtrace:
       node_modules/bootstrap/scss/_forms.scss:280, in function `rgba`

Using Laravel Mix/Webpack.

**Comment by twobyte** [comment]
I’m using bootstrap-sass version 3.3.7 and getting this error as well. 
Removed all my node_modules and upgraded gulp-sass, reinstalled but no joy. The error is 
`Error: argument `$color` of `darken($color, $amount)` must be a color`
I am echoing out the value of $color with @warn `WARNING: $thisColour: #1d99d3` this clearly shows a color. Think it must be something to do with node-sass...

**Comment by ABD-dev** [comment]
Be sure to check the bootstrap version! bootstrap@4.0.0-beta.2 works like a charm.

**Comment by Jonathan002** [comment]
So I ran into this problem also but found it weird how the solution was to add the @functions.scss first when in fact that it is already added first in the bootstrap.scss file in the bootstrap package.

// In boostrap package at node_modules
Bootstrap.scss
```
@import "functions"; // <-- already first
@import "variables";
@import "mixins";
//.. more bootstrap imports
```

So I went and looked at the variables.scss files and the error was trying to execute a function that needed access to a map called $theme-colors, which needed to access the $primary variable (which links to $blue which is a #007bff color at the end of the link path).

It should be noted though that $primary was set like this:
`$primary: $blue **!default**;`

So because this variable can be overwritten if you happen to want to use the $primary variable namespace, such as making a $primary() map for a material pallet. You change the $primary value from color to map. So be careful when defining the $primary variable or any $bootstrap variable that should be a color. The !default will get overwritten if your variables file happens to be before the bootstap @import.

So generally I got my boostrap working just fine with:
`@import "~bootstrap/scss/bootstrap";`
only and watching for the variable namespace.

**Comment by eness** [comment]
still have the same issue. I miss the days everything was just awesome ..

**Comment by myorangeca** [comment]
@eness We are just getting older :)

**Comment by eness** [comment]
@myorangeca have you found any solution for this shit brother? I've seen that you had created an issue for this.

**Comment by maxkorz** [comment]
@eness just make sure you import `functions` before `variables` in every place where you import `variables`

**Comment by myorangeca** [comment]
@eness  how are you importing? Can you paste your main.scss file here?

**Comment by mdo** [comment]
Look at the main `bootstrap.scss` file for how to set up your imports. We solved this problem long ago; update to the latest release.
