### ISSUE TITLE
Button Disabled - Cursor not-allowed no longer works

### ISSUE THREAD

**Issue by Sun3** [twbs/bootstrap#23334]
Updated to the latest 4.0 beta version I noticed that Buttons when in a disabled state the cursor not-allowed no longer shows up. This causes confusion for users on disabled buttons.

```
<button type="button" class="btn btn-secondary" style="border: none;" data-toggle="modal" data-target="#editPropertyModal"
                [disabled]="!isEditMode">View Secret Word</button>

```

Any ideas?
Thanks

**Comment by Sun3** [comment]
ps: For now I am using below in my css for a quick fix if anyone else also need it.

```
button:disabled {
  cursor: not-allowed;
}  
```

**Comment by max41479** [comment]
It was intended. #22403

**Comment by Johann-S** [comment]
Closed thanks to @max41479 👍

**Comment by Tirumalachary** [comment]
yes

**Comment by HassanAsghar123** [comment]
> ps: For now I am using below in my css for a quick fix if anyone else also need it.
> 
> ```
> button:disabled {
>   cursor: not-allowed;
> }  
> ```

It is not working for me

**Comment by Yagayev** [comment]
> > ps: For now I am using below in my css for a quick fix if anyone else also need it.
> > ```
> > button:disabled {
> >   cursor: not-allowed;
> > }  
> > ```
> 
> It is not working for me

It wasn't working for me as well, I was able to solve it by adding
`pointer-events: auto,`

**Comment by Jumzeey** [comment]
also doesn't work in vuejs
