### ISSUE TITLE
Broken Links on getbootstrap.com

### ISSUE THREAD

**Issue by trdwll** [twbs/bootstrap#23343]
In the footer of the site Examples links to http://getbootstrap.com/examples/ which is a 404 and About links to http://getbootstrap.com/about/history/ which is another 404.

**Comment by ocelotluke** [comment]
This is because the examples & history content is stored on the following links: 

https://v4-alpha.getbootstrap.com/examples/
http://v4-alpha.getbootstrap.com/about/history/

Someone must have changed the links target, but not the file path.

**Comment by XhmikosR** [comment]
Pretty sure this is a duplicate.

**Comment by trdwll** [comment]
@XhmikosR I did a quick search before posting as requested and I didn't find anything. It seems that @StevenBlack has fixed it in the PR above. Which I see that he didn't fix the about link in that PR.

**Comment by XhmikosR** [comment]
About was fixed in https://github.com/twbs/bootstrap/commit/bfd05c3423b8d92721444f002311e7d261ef30a7

And I don't know about his example "fix". Works fine locally.
