### ISSUE TITLE
hidden-*-up & hidden-*-down are missing from beta

### ISSUE THREAD

**Issue by christianklemp-imt** [twbs/bootstrap#23340]
When switching from alpha 6 to beta 1, I noticed that all the ```hidden-*-up``` and ```hidden-*-down``` classes are no longer available. I searched the documentation and it pointed me to a [non-existent page](https://getbootstrap.com/docs/4.0/layout/responsive-utilities/#available-classes).

Are these classes coming back or have they been moved away from?

Chrome on macOS Sierra

**Comment by serialinternet** [comment]
Missing it too!

**Comment by mosher13** [comment]
The best explanation is here --> https://getbootstrap.com/docs/4.0/migration/ where is explains they removed those classes in Beta and now use the new Utilities here --> https://getbootstrap.com/docs/4.0/utilities/display/

**Comment by christianklemp-imt** [comment]
Thanks @mosher13, totally missed that part of it!

**Comment by serialinternet** [comment]
So the equivalent for `.hidden-lg-down` is now `.d-none .d-xl-block`

**Comment by jipexu** [comment]
>So the equivalent for .hidden-lg-down is now .d-none .d-xl-block

if you are in a block context ....

**Comment by fjeddy** [comment]
Bootstrap 4 is the biggest peace of crap i have encountered. If you need to make these drastic changes from the last alpha version to the first beta, then it was never ready to go public in the first place.

Really HATE how bootstrap has gone from a simple framework, to a complicated mess. Bootstrap didn't get popular because it supported ten thousands options with complicated-non-self-explaining class names. It got popular because it was simple and efficient.

Bootstrap just entered my bloatware book.

**Comment by mdo** [comment]
> Bootstrap 4 is the biggest peace of crap i have encountered. If you need to make these drastic changes from the last alpha version to the first beta, then it was never ready to go public in the first place.

We could've done another alpha between Alpha 6 and Beta 1, but there wasn't any point to that really. No matter what, these changes were coming. It's precisely why the alpha period lasted this long.

>  Bootstrap didn't get popular because it supported ten thousands options with complicated-non-self-explaining class names. It got popular because it was simple and efficient.

We're pretty opinionated—I don't see how we're supporting tens of thousands of options with a change in strategies for how you hide content responsively. Take a few minutes and get to know the new classes before you bash our work.

See https://github.com/twbs/bootstrap/pull/22113 for the PR that changed these utilities.
