### ISSUE TITLE
.navbar-nav missing .navbar-toggleable-xx

### ISSUE THREAD

**Issue by paulincai** [twbs/bootstrap#23341]
Upgraded from alpha.6 to beta.
<ul class='navbar-nav'>...</ul>
**alpha6:** 
@media (min-width: 992px)
.navbar-toggleable-md .navbar-nav {
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -webkit-flex-direction: row;
    -ms-flex-direction: row;
    flex-direction: row;
}
**beta:**
the whole query is missing resulting in vertical centered menu instead of inline. All sizes are affected.

**Comment by mdo** [comment]
Class has been renamed. Please consult the latest docs at https://getbootstrap.com.
