### ISSUE TITLE
Comments in the Documentation

### ISSUE THREAD

**Issue by ocelotluke** [twbs/bootstrap#23345]
In the documentation there are blocks of CSS that can be copied to the clipboard (via a provided link), the code is all (from what I've seen) syntactically correct, however the comments are `\\` instead of `/* */`. 

An example of this is the following from the [responsive breakpoints article](https://v4-alpha.getbootstrap.com/layout/overview/):
```css
// Extra small devices (portrait phones, less than 576px)
// No media query since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

I understand that this is correct for SASS, but `/* */` is also SASS complaint,  as well as being complaint for people using `custom.css` to add custom code to their build.

**Comment by chiraggmodi** [comment]
@ocelotluke  is correct, we have added css rules in this code block not .scss, so i think we should add multi line comment instead of .scss single line. @mdo let me know you thought.

**Comment by bardiharborow** [comment]
Confirmed, but just noting that the beta docs are actually at https://getbootstrap.com/docs/4.0/layout/overview/

**Comment by chiraggmodi** [comment]
yes, but this issue still present in beta docs too.
will create PR sortly.

**Comment by mdo** [comment]
Closing as a won't fix—these should stay as Sass comments given Bootstrap is written in Sass. I understand many folks reading these docs will be using regular CSS, but this is in reference to how we use the media queries in our Sass code.

**Comment by ocelotluke** [comment]
I respect your decision @mdo but I feel like with v4 there needs to be a conscious effort made to accommodate long time developers in this area because they are going to have to change their way of working from raw CSS to Sass 👍
