### ISSUE TITLE
Disabled state for links inside navbar is not consistent with buttons

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#23358]
According to https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state

> The .disabled class uses pointer-events: none to try to disable the link functionality of &lt;a&gt;

It's not true for a `.nav-link` in navbar https://getbootstrap.com/docs/4.0/components/navbar/#toggler

![](https://i.imgur.com/dUKPei6.png)

**Comment by mdo** [comment]
Yeah, the docs you're mentioning are for for buttons, not nav links. Do we want to disable `pointer-events` for all our links?

**Comment by maxkorz** [comment]
@mdo I believe the styles must be consistent among all components. What I found out:

`pointer-events` is disabled for:
* [Buttons](https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state)
* [Pagination](https://getbootstrap.com/docs/4.0/components/pagination/#disabled-and-active-states)

`pointer-events` is not disabled for:
* [List group](https://getbootstrap.com/docs/4.0/components/list-group/#links-and-buttons)
* [Dropdown menu](https://getbootstrap.com/docs/4.0/components/dropdowns/#disabled-menu-items)
* [Navs](https://getbootstrap.com/docs/4.0/components/navs/)

It's important to point out that `.disabled` `<a>`s are still clickable without `pointer-events: none`

**Comment by mdo** [comment]
@patrickhlauke Any strong feelings here?

**Comment by patrickhlauke** [comment]
i *think* that shouldn't have any adverse side effects

**Comment by MartijnCuppens** [comment]
Fixed in the meanwhile: https://twbs-bootstrap.netlify.com/docs/4.3/components/navbar/
