### ISSUE TITLE
Bootstrap v4.0-Beta Navbar

### ISSUE THREAD

**Issue by Miyulasi** [twbs/bootstrap#23356]
Cannot center any item like logo or text

**Comment by bhurivaj** [comment]
my dropdown on navbar does not work too.

**Comment by benThijssen** [comment]
navbar dropdown is now depending on poppers.js You need to load poppers.js before bootstrap.js. If found it be checking my browser console. There was a message that bootstrap requires poppers.js
Check https://popper.js.org/

**Comment by simplewayUA** [comment]
Navbar does not work, for example. I just used simple code.
``` HTML
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
```
![Image example]
(https://image.ibb.co/cDBwsF/2017_08_12_18_28_12_1.png)

**Comment by nskforward** [comment]
Dropdowns don't work correctly on navbar

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Use the flexbox utilities. Our navbar example shows how to center content, in a navbar or otherwise.

**Comment by andreimcristof** [comment]
Is the navbar example that you refer to the one from v4 alpha? If so, this means there is no change for navbar in the beta, correct? Thank you

**Comment by smtrejo** [comment]
Here's a fiddle with the Navbar working on Bootstrap 4 Alpha 6:

https://jsfiddle.net/j66b6zez/1/

And here's another with Navbar on Bootstrap 4 Beta 3. It still displays the "burguer" menu on large screens:

https://jsfiddle.net/1dvk8cxh/1/
