### ISSUE TITLE
Dead links show up in docs search results

### ISSUE THREAD

**Issue by maxkorz** [twbs/bootstrap#23359]
https://getbootstrap.com/docs/4.0/getting-started/introduction/
For example: try to search for "responsive"

<img src="https://i.imgur.com/NSS6ett.png" width="400">

All links in "Layout" and "Utilities" sections lead to 404 page

**Comment by XhmikosR** [comment]
@mdo: how does the algolia thing work? Do we need to bug them to update the index or something?

**Comment by mdo** [comment]
Yeah we need to have them reindex the site. /cc @maxiloc

**Comment by maxiloc** [comment]
I updated the config and reindexed. Should be good now.

**Comment by mdo** [comment]
Thanks!
