### ISSUE TITLE
feature request "clickable card-header for Accordion" 

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#23352]
nice to see bs4 is go to beta 👍

can you add a clickable "card-header" for accordion simular the "list-group-item-action" maybe  "card-header-action"

thanks jonny

**Comment by Johann-S** [comment]
Hi @jonnysp ,

`.card-header` is already clickable in our accordion see : https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

Maybe can you add some explanations here ?

**Comment by jonnysp** [comment]
hi @Johann-S 

a full block style as a button with hover effect or the listgroup link and colorable with within the card style
https://getbootstrap.com/docs/4.0/components/list-group/#links-and-buttons

**Comment by mdo** [comment]
You can create a clickable header for it, but we're not going to provide any additional styles for it.
