### ISSUE TITLE
Button Outline Light visibility

### ISSUE THREAD

**Issue by psingl** [twbs/bootstrap#23351]
I would like to bring to the notice of the developers of bootstrap about a button issue. We will be using .btn-outline-light in dark background. It's visibility is alright in dark background but on hover the background color of the button becomes same as that of button text. On hovering the button with class='.btn-outline-light' the text must be dark.
![image](https://user-images.githubusercontent.com/13885706/29238449-722d65e4-7f53-11e7-85bd-63610a4b3104.png)

**Comment by mdo** [comment]
Ah yeah, we should make sure `background-color` is set to `transparent`.

**Comment by prateekgoel** [comment]
@mdo If we make `background-color` set to `transparent` that there won't be distinguishable hover effect. I think we should do something about the text color.

**Comment by psingl** [comment]
@mdo I think @prateekgoel  is right in that there won't be distinguishable hover effect. According to me the solution to this is that the .btn-outline-light button must be removed as what I noticed is that .btn-outline-secondary works really very fine in dark background and is very similar to the .btn-outline-light button. Rest upon you. Thanks.

**Comment by fran-worley** [comment]
@psingl I actually choose to use `btn-outline-light` over secondary on really dark backgrounds (the text colour is just too dark for me), so simply removing it wouldn't be an option.

In principle, outline buttons should follow a standard pattern. Regular display should be as they are currently, and on hover they should revert to the standard non-outline equivalent. This seems to be the case for all but the outline-light.

**Comment by mrlife** [comment]
On hover, it would make sense to match the standard light button's text color of #111.
