### ISSUE TITLE
Feature - Responsive Border 

### ISSUE THREAD

**Issue by MichaelRise** [twbs/bootstrap#23354]
Hey,

I have small idea - Responsive Borders.
This feature can help some developers.
Preview - [http://fiddle.jshell.net/pqonupeo/11/show/light/](http://fiddle.jshell.net/pqonupeo/11/show/light/)
Code - [https://jsfiddle.net/pqonupeo/11/](https://jsfiddle.net/pqonupeo/11/)

Thanks
Michael

**Comment by XhmikosR** [comment]
Yup, agreed. /CC @mdo 

Also @MichaelRise you can make a proper PR.

**Comment by mdo** [comment]
This should probably just be custom styling. I'm not interesting in responsive variants for every single utility we provide—if we did them all, it'd be a little unwieldy. Thanks though!
