### ISSUE TITLE
SCSS compilation error

### ISSUE THREAD

**Issue by myorangeca** [twbs/bootstrap#23366]
When compiling the new BS sass with gulp-sass I am getting the following error (image attached below)

gulp-sass v3.1.0
node v6.9.2

![image](https://user-images.githubusercontent.com/1827880/29243414-5cb47be4-7f6c-11e7-9559-10ab0e15b9af.png)

Can someone confirm if this is just me?

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/issues/23331

**Comment by myorangeca** [comment]
Thanks! Been trying to figure it out for 24 hrs..

**Comment by numan-ahmad** [comment]
plz help me out how to solve this issue?
