### ISSUE TITLE
Bootstrap v4 beta 1 and error npm run dist

### ISSUE THREAD

**Issue by mirshahreza** [twbs/bootstrap#23363]
In alpha 6 I use the clean command grunt dist to rebuild the bootstrap but in new version this removed from the package so I am using npm run dit but when run the command I get this output 

> bootstrap@4.0.0-beta dist C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> npm-run-all --parallel css js css-docs

> bootstrap@4.0.0-beta css-docs C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> npm-run-all css-lint-docs css-compile-docs css-prefix-docs css-minify-docs

> bootstrap@4.0.0-beta css C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> npm-run-all css-lint css-compile css-prefix css-minify

> bootstrap@4.0.0-beta js C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> npm-run-all js-lint js-compile js-minify

> bootstrap@4.0.0-beta css-lint-docs C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> bundle exec scss-lint --config .scss-lint.yml --exclude assets/scss/docs.scss assets/scss/*.scss

> bootstrap@4.0.0-beta js-lint C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> eslint js/ && eslint --config js/tests/.eslintrc.json --env node build/ Gruntfile.js

'bundle' is not recognized as an internal or external command,
operable program or batch file.
'eslint' is not recognized as an internal or external command,
operable program or batch file.

> bootstrap@4.0.0-beta css-lint C:\ToDoProjects\WebAssets\bootstrap-4.0.0-beta
> bundle exec scss-lint --config .scss-lint.yml scss/*.scss

'bundle' is not recognized as an internal or external command,
operable program or batch file.
npm npmERR! ERR!  codecode ELIFECYCLE
 ELIFECYCLE
npmnpmnpm   ERR!ERR!ERR!  codeerrno ELIFECYCLE
 1
 npmnpmerrno 1
  ERR!ERR!npm  bootstrap@4.0.0-beta js-lint: `eslint js/ && eslint --config js/tests/.eslintrc.json --env node build/ Gruntfile.js`
 errnonpmERR! 1
 npm  bootstrap@4.0.0-beta css-lint-docs: `bundle exec scss-lint --config .scss-lint.yml --exclude assets/scss/docs.scss assets/scss/*.scss`
ERR!ERR!npm Exit status 1
 bootstrap@4.0.0-beta css-lint: `bundle exec scss-lint --config .scss-lint.yml scss/*.scss`
 npmnpmERR!  ERR!ERR! Exit status 1

 Exit status 1
npmnpmnpm  ERR!ERR!  Failed at the bootstrap@4.0.0-beta js-lint script.
npm
ERR! ERR!npm
  This is probably not a problem with npm. There is likely additional logging output above.
ERR!npm  Failed at the bootstrap@4.0.0-beta css-lint-docs script.
npmERR! npmWARN  Failed at the bootstrap@4.0.0-beta css-lint script.
ERR! Local package.json exists, but node_modules missing, did you mean to install?
npm  This is probably not a problem with npm. There is likely additional logging output above.

ERR!npmnpm   This is probably not a problem with npm. There is likely additional logging output above.
WARNERR! Local package.json exists, but node_modules missing, did you mean to install?
 A complete log of this run can be found in:
npm
npm ERR! npm      C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_208Z-debug.log
ERR!WARN A complete log of this run can be found in:
 Local package.json exists, but node_modules missing, did you mean to install?
npm ERR!
     C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_208Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR!ERROR: "js-lint" exited with 1.
     C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_239Z-debug.log
ERROR: "css-lint-docs" exited with 1.
ERROR: "css-lint" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta js: `npm-run-all js-lint js-compile js-minify`
npm ERR!npm Exit status 1
 npmERR!  ERR!code ELIFECYCLE

npmnpm  ERR!ERR!  Failed at the bootstrap@4.0.0-beta js script.
errnonpm 1
 npmERR!  This is probably not a problem with npm. There is likely additional logging output above.
npmERR!  bootstrap@4.0.0-beta css-docs: `npm-run-all css-lint-docs css-compile-docs css-prefix-docs css-minify-docs`
npmERR!npm   codeERR!WARN ELIFECYCLE
npm Local package.json exists, but node_modules missing, did you mean to install?
 Exit status 1
 npmERR!  errnoERR!
 1
npmnpm
  npmERR!ERR!  bootstrap@4.0.0-beta css: `npm-run-all css-lint css-compile css-prefix css-minify`
ERR!npm A complete log of this run can be found in:
npm ERR! ERR! Failed at the bootstrap@4.0.0-beta css-docs script.
npm Exit status 1
     C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_324Z-debug.log
 npmERR! ERR! This is probably not a problem with npm. There is likely additional logging output above.

npmnpm WARN ERR! Local package.json exists, but node_modules missing, did you mean to install?
 Failed at the bootstrap@4.0.0-beta css script.

npmnpm  ERR!ERR! This is probably not a problem with npm. There is likely additional logging output above.
 A complete log of this run can be found in:
npm ERR!npm     C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_324Z-debug.log
 WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_339Z-debug.log
ERROR: "js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta dist: `npm-run-all --parallel css js css-docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@4.0.0-beta dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohsen Mirshahreza\AppData\Roaming\npm-cache\_logs\2017-08-12T16_05_47_424Z-debug.log

I searched error and unfortunately I didn't find a solution 

please guide me for recompiling the bootstrap 4 beta 1

Thanks

**Comment by Johann-S** [comment]
Please read our documentation : https://getbootstrap.com/docs/4.0/getting-started/build-tools/

**Comment by cruelmelody** [comment]
I'll shed some light on this because I was encountering the exact same issue. Here's what I did to fix:

1. Firstly, clone the Bootstrap repo. Don't just run `npm install bootstrap@4.0.0-beta` and expect all the dependencies to be there. You'll be missing a very important Gemfile if you do.
2. Add Bootstrap to your Gemfile, as mentioned in the docs. Reference here: `https://github.com/twbs/bootstrap-rubygem/blob/master/README.md`
3. Follow the tooling setup here: `https://getbootstrap.com/docs/4.0/getting-started/build-tools`
4. Run `bundle install` from the root directory where the Gemfile is located. Everything should be working. If you're getting Jekyll errors when bundling, just comment out the Jekyll dependencies from the Gemfile.

Hopefully this helps.

**Comment by mirshahreza** [comment]
I removed lint tasks from npm package file and everything is ok now. It seems some incompatibility issues causes this errors.
