### ISSUE TITLE
Disabled links accessible via keyboard (tab)

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#23361]
Disabled links (a) accessible via keyboard (tab) on latest firefox win 10.

in navbar
![link](https://user-images.githubusercontent.com/1651241/29241657-39ff5fe4-7f7e-11e7-9b52-b8b6af196ef4.jpg)

disable button
![buttin](https://user-images.githubusercontent.com/1651241/29241658-3ca1838a-7f7e-11e7-8daa-070b367b5dab.jpg)

**Comment by patrickhlauke** [comment]
see https://getbootstrap.com/docs/4.0/components/buttons/#link-functionality-caveat

this advice should probably be replicated in the navbar part of the documentation, and in both cases the examples should probably include `tabindex="-1"`
