### ISSUE TITLE
Extend section should either have a top level page, or the todo page should be removed and redirected.

### ISSUE THREAD

**Issue by gijsbotje** [twbs/bootstrap#23369]
on the migration page of the current docs for v4 there is a link that leads to a 'todo' page
http://getbootstrap.com/docs/4.0/migration/#components
the link to the 'extend' page leads to the wrong url or the redirect to `extend/icons` is broken

**Comment by XhmikosR** [comment]
@mdo: thoughts how to handle this?

**Comment by chiraggmodi** [comment]
there is no content for `/extend/` page. so i belive we should add redirection rule, or just change URL to `/extend/`

**Comment by mdo** [comment]
Going to leave it as-is for now.
