### ISSUE TITLE
Option for modals to cover the full screen on mobiles

### ISSUE THREAD

**Issue by pullthefuse** [twbs/bootstrap#23365]
Modals to fill the full screen on a mobile (Portrait & Landscape) and then expand into normal modals from md upwards. These days I don't see many sites not doing this, so it could even be the default.

**Comment by mdo** [comment]
Have an example?

**Comment by pullthefuse** [comment]
http://demo.studiomanager360.com/ Click on login or register, both modals are setup that way.

**Comment by mdo** [comment]
Ah, thanks. We'll pass for now—this can be accomplished with the existing modals through custom styles. I don't see much of a reason to bake this into the core project given that.
