### ISSUE TITLE
Add .badge-default changes to Migration docs.

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#23370]
Hi
https://getbootstrap.com/docs/4.0/migration/

on the label and badge section
why not add
- the  badge-default class changed to badge-secondary.

**Comment by XhmikosR** [comment]
@jipexu: you can always submit a PR.

**Comment by jipexu** [comment]
sure i can try (but not very familiar with this exercice ...) i will try

**Comment by jipexu** [comment]
https://github.com/twbs/bootstrap/pull/23409

done
