### ISSUE TITLE
migrate from 4.0.0-alpha.6 to beta and navbar totally broken - docs dont show what has changed

### ISSUE THREAD

**Issue by geetee24** [twbs/bootstrap#23373]
seems the beta broke the navbar that works fine in alpha 6.

the new change log docs dont highlight what has changed. 

Can someone provide new docs to show how to convert  form old to new?  Argh.  Have to revert to alpha until this is solved.  Boss is so mad.

Thank you.

**Comment by mdo** [comment]
Everything you're using is pre-release. We've rewritten plenty in every alpha release and haven't provided upgrade paths for any of them for good reason—it's far too much change. Please consult the hosted docs and go from there.
