### ISSUE TITLE
Why I miss "hidden-sm-down" from v4.0.0-alpha.6 and before.

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#23376]
I'm on the v4.0.0-beta now and I miss a lot "hidden-sm-down". I explain the reason:

With alpha I had this:

`<div class="col-10 col-md-6 push-md-2 pr-0 px-md-0 d-flex flex-column {{if mobileMode "hidden-sm-down"}}">Hello!</div>`

With beta I need to have this:

`<div class="col-10 col-md-6 push-md-2 pr-0 px-md-0 flex-column {{unless mobileMode "d-flex"}}{{if mobileMode "d-none"}}">Hello!</div>`

So now I have two binding css class with my javascript and not one = more heavy page.

Why `hidden` and company can't stay? Or maybe, why `d-none` can't win over `d-flex`?

Or maybe I'm missing something?

**Comment by gijsbotje** [comment]
you could just use your original code and use `d-none` and in your if statement use `d-md-flex`
for all breakpoint classes see http://getbootstrap.com/docs/4.0/utilities/display/#common-display-values

**Comment by mdo** [comment]
Yup, what @gijsbotje said.

**Comment by johnunclesam** [comment]
@gijsbotje @mdo No, you don't understand. My div is always visible in my first case. If I do as you say it is invisible unless `gameMode` is on, because of `d-none` which I need just in `gameMode`.

`mobileMode` is misleading, so I changed it in `gameMode`.

Is it more clear now the question?

**Comment by gijsbotje** [comment]
still doable
```
<div class="col-10 col-md-6 push-md-2 pr-0 px-md-0 d-flex flex-column {{if gameMode "d-none d-sm-flex"}}">Hello!</div>
```
because of the order `d-flex` will be overwritten by `d-none` and the same with `d-sm-flex`

**Comment by johnunclesam** [comment]
@gijsbotje, no this is the problem. `d-flex` wins on `d-none` also if `d-none` is the last. See:

![image](https://user-images.githubusercontent.com/21275217/29245187-8cd8b414-7fd2-11e7-9fb1-a7e93127ef8a.png)

**Comment by gijsbotje** [comment]
ok, and using if else is really bad?
```
<div class="col-10 col-md-6 push-md-2 pr-0 px-md-0 flex-column {{if gameMode "d-none d-sm-flex" else "d-flex"}}">Hello!</div>
```
or something like that?

**Comment by johnunclesam** [comment]
@gijsbotje Is not a solution, unfortunately.

**Comment by mdo** [comment]
You can’t have two utilities setting the same property like that, you’re going to have problems like this. Are you having problems with mixing reponsive utilities? Does `.d-none.d-md-flex` work as expected? Does `.d-flex.d-md-none` work as expected?
