### ISSUE TITLE
Switch to stylelint.

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#23383]

**Comment by XhmikosR** [comment]
Yup, agreed. Note for us, we could/should make use of more postcss plugins.

**Comment by XhmikosR** [comment]
I'm gonna work on this later today or tomorrow and make a PR to discuss/extend my patch.

**Comment by XhmikosR** [comment]
@mdo: before I spent more time with this, do you agree with the switch?

**Comment by mdo** [comment]
> do you agree with the switch?

Have we discussed it at all? What's the benefit? I know we had #20402, but I don't completely remember why there was a repo for it and why our linting rules had so many changes.

**Comment by XhmikosR** [comment]
Hmm I haven't followed that PR. IMHO it makes sense to use stylelint
especially if we have a config already set up. In my local branch I started
from scratch but if there's a config we have control of I will use that
instead.

**Comment by mdo** [comment]
>  if there's a config we have control of

We don't have that. It was suggested, but I don't know what it included or why that was suggested.

**Comment by XhmikosR** [comment]
I can make a config which results in no code changes and then we can make
it stricter. How does that sound? We can then make a repo with our config
if we want to.

**Comment by mdo** [comment]
> I can make a config which results in no code changes and then we can make it stricter. How does that sound?

Still doesn't answer why we'd switch—what's the difference between the two?

**Comment by XhmikosR** [comment]
I don't know the exact differences since personally I never used scss-lint.
Stylelint is very extendable and no Ruby requirement.

IMO it's worth doing this as long as we match the config.

**Comment by FezVrasta** [comment]
Probably a long term decision to move away from Sass in future?

**Comment by mdo** [comment]
> Stylelint is very extendable and no Ruby requirement.

Ayyy that's all you have to say to me :D.

**Comment by mdo** [comment]
> Probably a long term decision to move away from Sass in future?

Yeah eventually :)

**Comment by XhmikosR** [comment]
Cool, I'll make a PR and CC you with the minimum rules so that we extend it match our needs before merging.

**Comment by bardiharborow** [comment]
> Still doesn't answer why we'd switch—what's the difference between the two?

Do I need to say much more that this pretty screenshot? 😍 

![](https://raw.githubusercontent.com/stylelint/stylelint/3b4abf49878a977ba88d92bac18e31c5c76b2034/example.png)

The main thing is that Ruby Sass, and by extension scss-lint is being [gently depreciated](https://github.com/brigade/scss-lint#notice-consider-other-tools-before-adopting-scss-lint), so stylelint is the clear migration path, in addition to being more architecturally similar to our use of ESLint for JavaScript.

**Comment by XhmikosR** [comment]
I'm gonna push my branch when I have some time to clean it up and CC you guys so that we bring the rules on par or even better with scss-lint.

**Comment by rafalp** [comment]
I would like to add my vote for this move. Ideally building css/js in Bootstrap should require `npm install`. I can bite the bower as its node.js too, but if my app's in python, it'll be worked with by python devs, why the heck do I need to install ruby things? ;)
