### ISSUE TITLE
Simplifying the search results

### ISSUE THREAD

**Issue by dushkostanoeski** [twbs/bootstrap#23389]
I know that an external tool is used for the search and I don't know if this is possible or not, but it would be neat for the results to have a breadcrumb-like look (for the headers only) because I was looking to the `description list` markup and I got the following result

![capture](https://user-images.githubusercontent.com/1545030/29248913-8cb371d4-8024-11e7-83f8-04d1ce0aac9c.PNG)

In the Content area, the first result is in the `Reboot` page, and the second in the `Typography` page. Instead of having 

- Lists

- Lists

having something like 

- Reboot \ Lists

- Typography \ Lists

would be a lot more straight-forward.

**Comment by mdo** [comment]
Dunno if it's possible. Maybe @maxiloc or one of the Algolia folks can weigh in?

**Comment by mdo** [comment]
Sorry for the constant pings, Maxime! Lemme know if I should open issues elsewhere instead :).

**Comment by maxiloc** [comment]
@mdo No worries about the pings that is totally fine 😄.

Regarding the issue, it is a matter of display on your side. The actual index contains and default UI contains this data:

![image](https://user-images.githubusercontent.com/1689007/29304489-8ab60700-8193-11e7-94e8-e8cca532047b.png)

The content is in both `.algolia-docsearch-suggestion--subcategory-inline` and `algolia-docsearch-suggestion--subcategory-column`, you can show one of the two depending on how you want to display the information.

**Comment by dushkostanoeski** [comment]
I spent more than an hour trying to figure out how this works so I can make a PR, but failed miserably 😄 if it isn't a big hustle, can this be pushed for beta3?
