### ISSUE TITLE
Dropup styling delegated to Popper?

### ISSUE THREAD

**Issue by srvance** [twbs/bootstrap#23399]
I'm integrating the changes for the beta release into ember-bootstrap.

If I'm reading things correctly, and my experiments correlate, with the beta BS4 is now delegating issues of styling and placement of dropups, popovers, and tooltips to Popper, which injects raw styling onto elements in the page. Are there no longer Bootstrap classes to handle the correct offsets for dropups, arrows for tooltips, etc.?

I understand delegating behavior to other javascript libraries, but I'm surprised at delegating styling.

If you want to see what I'm referring to,

1. Clone ember-bootstrap
1. `git checkout bs4-beta`
1. `yarn install`
1. `BOOTSTRAPVERSION=4 ember serve`
1. Point your browser to [the server](http://localhost:4200)
1. Navigate to Components Overview > Dropdown (on left)
1. Exercise the Dropup in the first example. By comparison, the dropup on the BS4 docs works but injects a `style` attribute onto the element with `.dropdown-menu` the first time it's used.

**Comment by Johann-S** [comment]
Dropdown now depends on Popper.js so dropup too, we cannot handle resize or scrolling with CSS so we choose to delegate the positioning to Popper.js
We just kept the CSS class name to avoid a bigger breaking change that's all

**Comment by srvance** [comment]
Thanks for the info, @Johann-S. I think we'll try to use ember-popper in ember-bootstrap.
