### ISSUE TITLE
Missing form controls rules has-*

### ISSUE THREAD

**Issue by mi-g** [twbs/bootstrap#23391]
Bootstrap 4.0.0-beta misses rules using `.has-*`, such as `.has-success`.

For instance:
```html
<div class="form-group row has-success">
	<label class="col-4 col-form-label" for="myfield">My field</label>
	<div class="col-8">
		<input class="form-control" type="text" id="myfield"/>
		<div class="form-text"><em>Help text</em></div>
	</div>
</div>
```
does not make the input appear with a green border.

It works fine with 4.0.0-alpha.6. 

My apologies if those changes were intended, but i couldn't find any mention of such a modification between alpha and beta, nor the actual beta documentation (i referred the alpha one from [here](https://v4-alpha.getbootstrap.com/components/forms/#defining-states)).

**Comment by knoobie** [comment]
See https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by mi-g** [comment]
Ok, so the `has-{success,warning,danger}` utility has disappeared to the profit of a global 2-states (valid/not-valid) form validation mechanism. 
It's not a big deal to add custom CSS to the application to get the feature back anyway.
Thanks for the link.
