### ISSUE TITLE
[v4] When collapsed and using navbar-toggler-left, navbar-brand is on right side.

### ISSUE THREAD

**Issue by Michaelvas17** [twbs/bootstrap#23394]
I recently updated my project from the v4-alpha to 4.0 beta, and I've been having an issue that I can't seem to fix.

Basically, I'm trying to make a navbar that collapses, and has a navbar-toggler on the left side of the navbar. The navbar functions/displays correctly when it is not collapsed. However, when it is collapsed, it appears that the navbar-brand is on the opposite side of the navbar, and I cannot seem to get it to go back to the left side of the navbar. [Here's a JSBin of the issue](https://jsbin.com/towoluquzi/edit?html,output).

I've tried this twice, in my existing project and in an isolated environment, and I've yielded the same result. I'm not sure if something changed from alpha-6 to the beta in regards to the brand, but I have been unable to find anything that would help me resolve this issue in the docs (unless I somehow missed something)

Any help would be greatly appreciated!

**Comment by mdo** [comment]
I'm unsure what you're after—can you provide screenshots?

**Comment by Michaelvas17** [comment]
@mdo:
![image](https://user-images.githubusercontent.com/5721500/29252498-76513310-8036-11e7-9086-1b4ba987467b.png)
Basically, for some reason, the navbar-brand moves to the opposite side of the navbar when the navbar-toggler has the class navbar-toggler-left. To my knowledge, this is unusual behavior, as I was able to move the toggler to the left without the navbar-brand exhibiting this behavior in the previous alpha release, as seen in the image.
Sorry if this was unclear.

**Comment by mdo** [comment]
`.navbar-toggler-left` is no more in the beta. If you want to change the order of the toggler and brand, switch the HTML around.

**Comment by Michaelvas17** [comment]
@mdo Ok, will do. Thanks for the clarification
