### ISSUE TITLE
Different buttons looks almost identical: "btn-outline-secondary" and "btn-outline-dark disabled"

### ISSUE THREAD

**Issue by vaags** [twbs/bootstrap#23390]
See plunker: https://plnkr.co/edit/hBi8RhSqgtnLtki0K0KS?p=preview

**Comment by mdo** [comment]
Yeah, not much to do about this tbh. I'm inclined to wait it out and see how much of an issue it truly becomes for folks. Yes, we could decrease opacity, but that's a color contrast issue. We could further differentiate the grays, but that doesn't buy us much either.

**Comment by vaags** [comment]
I understand your reasoning. I'm thinking perhaps that btn-outline-secondary looks too much like a disabled button to begin with (and the regular btn-secondary too). For now I've simply stopped using these variants.
