### ISSUE TITLE
input-group and labels

### ISSUE THREAD

**Issue by peterbenoit** [twbs/bootstrap#23392]
My project requires labels on text fields for 508 accessibility. I've noticed that in the input-group control, the border-radius style applies to the first element only, and not the first form element such as an input, button, etc... so placing a label before that element breaks the rounded corners. While I could possibly move the label after the form control, I believe this CSS styling behavior is incorrect.

![image](https://user-images.githubusercontent.com/492000/29250922-663f2f1c-8019-11e7-8bfa-c0cf8cc970ac.png)

[CodePen Demo](https://s.codepen.io/peterbenoit/debug/ZJJNqw )

**Comment by mdo** [comment]
[From the docs:](https://getbootstrap.com/docs/4.0/components/input-group/)

> We do not support multiple form-controls in a single input group and `<label>`s must come outside the input group.

**Comment by patrickhlauke** [comment]
@mdo nonetheless, it could be probably made to work by replacing the check for `:not(:first-child)` to `:not(:first-of-type)` / `:not(:last-child)` to `:not(:last-of-type)`
