### ISSUE TITLE
tab.js problem with more ".active" classes in the Content Tab

### ISSUE THREAD

**Issue by dercodercom** [twbs/bootstrap#23408]
In the Bootstrap 4-Beta becomes a conflict with ".active" Class, when more .active Classes in content Tab. The active status will not work properly with this Problem.

Bootstrap 4-Alpha6
`ACTIVE: '.active',
 ACTIVE_CHILD: '> .nav-item > .active, > .active',`
` var active = $(container).find(Selector.ACTIVE_CHILD)[0];`

Bootstrap 4-Beta
`ACTIVE: '.active'`
` var active = $(container).find(Selector.ACTIVE)[0];`

![grafik](https://user-images.githubusercontent.com/16963738/29264420-49516afe-80dd-11e7-9331-b439ca26014f.png)

**Comment by Yeswanth-JG** [comment]
@dercodercom : Can you please create a reduced test case using **JSBIN** or **CODEPEN**.
Thanks

**Comment by adminhamza** [comment]
page-itex active

**Comment by dercodercom** [comment]
@Yeswanth-JG 
https://codepen.io/anon/pen/NvabQM

When click "Test1" Tab see the First Page was not ".active", then click "Test2" Tab the First Page was the ".active" Class

**Comment by svjansen** [comment]
Related to [#23311](https://github.com/twbs/bootstrap/issues/23311) and [#23304](https://github.com/twbs/bootstrap/issues/23304).

Will be fixed in [#23087](https://github.com/twbs/bootstrap/pull/23087).

**Comment by dercodercom** [comment]
@svjansen thx for info 👍

**Comment by Johann-S** [comment]
Closed thanks to @svjansen comment 👍
