### ISSUE TITLE
.btn-<sm/lg> definitions in _buttons.scss doesn't use $input-btn-line-height-<sm/lg> variable in Bootstrap 4 beta 1

### ISSUE THREAD

**Issue by dozer75** [twbs/bootstrap#23407]
The new variables `$input-btn-line-height-sm`/`$input-btn-line-height-lg` has been introduced in the latest beta of Bootstrap 4, but this isn't used by the `.btn-sm`/`.btn-lg` definition in _buttons.scss, this uses general `$line-height-sm`/`$line-height-lg`.

The `$input-btn-line-height-sm`/`$input-btn-line-height-lg` should also be defined to default beeing `$line-height-sm`/`$line-height-lg`

The .btn definition uses the correct `$input-btn-line-height`.

**Comment by mdo** [comment]
True, those are used everywhere else, but not in the `_buttons.scss` file.

**Comment by mdo** [comment]
First and last paragraphs have been resolved already, but just added a commit in #24199 to fix the middle paragraph's issue.
