### ISSUE TITLE
Navbar Trouble on Bootstrap 4 Beta

### ISSUE THREAD

**Issue by DodoTheDuck** [twbs/bootstrap#23404]
Having trouble with the new bootstrap 4 beta. The navbar is for some reason transparent and always collapsed, when using responsive behaviour. 

Pretty basic plunkr to show the problem: https://plnkr.co/edit/0L1zCLJjp3jzRqq3C9st

Using Windows, Chromium and Firefox.

**Comment by rixlabs** [comment]
They changed the toggler class. It seems you are using the example from the alpha site.

Try with this one https://getbootstrap.com/docs/4.0/components/navbar/#responsive-behaviors

**Comment by rixlabs** [comment]
It seems this one can be closed

**Comment by DodoTheDuck** [comment]
Seems like it. I saw the new documentation and I was 100% sure I took the code from that site. I am sorry for the inconvenience.

**Comment by rixlabs** [comment]
Had the same problem on friday 😄

**Comment by DodoTheDuck** [comment]
I'm using angular. They removed the tether dependency and required a manual popper.js install. My whole project got fucked up (design-wise) and I didn't recognize the bump from alpha to beta and thought, it was the sass files. Took me hours to figure out the update. God damned :dancer:
