### ISSUE TITLE
Add an order class to be before unspecified columns (like flex-first did previously)

### ISSUE THREAD

**Issue by chrisblakley** [twbs/bootstrap#23400]
Like I mentioned in another issue, I love how intuitive the new `order` classes are! However, when playing with them tonight I found that there is no way to move a `div` unless other `div`s in the row are also specified.

Since the default flex order is `0`, the Bootstrap order classes can only move `div`s to the right of an unspecified `div` (such as `.col` or `.col-md`).

```html
<div class="row">
	<div class="col-md">
		Unspecified column width. This will be first no matter what (default flex order of 0).
	</div>
	<div class="col-md order-1">
		Order declared, but remains right of unspecified column(s).
	</div>
</div>
```

### Previous solution
In the alphas, we had access to the class `flex-first` which would force the `div` to be the first column regardless (by setting the order to `-1`). I think the idea of this can be included while still maintaining the simplicity of the `order` classes.

### Proposed solutions
 - Having a class with the property of `order: -1` would be one idea. Maybe `order-first`, `order-before`, `order-0`, or even the former `flex-first`, or something completely different (just spitballing).
   - I'd hate to slip down the slope of requesting 12 more order classes for negative numbers, but maybe we could introduce one class to force a column first?
 - The default order could be changed as well, but this would cause the opposite problem.
 - Another solution could be to ignore it and just require devs to implement their own class if they want to reorder a column to be before an unspecified Bootstrap column `div`.

I want to make sure Bootstrap retains as much functionality as possible to allow these "width agnostic" columns because it is such a powerful feature that allows for so much elegant flexibility when developing.

**Comment by lukefrake** [comment]
👍  this, would be great to have 
```
.order#{$infix}-first{
   order: -1
}
```.

On the same point, in the beta we hard

```
.order#{$infix}-unordered {
   order: 0;
}
```
This is really useful as well and would be great to have this back in.

I much prefer having the `.order-n` classes, they're powerful but think first and unordered need to be added back in.

If this is acceptable I'll put a PR together to put this back in and update the docs

**Comment by Macintosher** [comment]
-- 



Bernhard Knab
Sebastian-Münster-Straße 3a
67549 Worms
Telefon: +49(0)6241-970020
Telefax: +49(0)6241-970749
bk@bknab.de

**Comment by Macintosher** [comment]
HELP Where can I stop getting 1000s of emails

-- 



Bernhard Knab
Sebastian-Münster-Straße 3a
67549 Worms
Telefon: +49(0)6241-970020
Telefax: +49(0)6241-970749
bk@bknab.de

**Comment by ragingdave** [comment]
Is this going to happen? I would love to be able to remove my custom implementation of this in favor of a supported version.

**Comment by mdo** [comment]
PRs would be great!

**Comment by lukefrake** [comment]
@mdo I've put together #24202 if you'd like to take a look. First PR on here
