### ISSUE TITLE
Huge changes in _variables.scss

### ISSUE THREAD

**Issue by dozer75** [twbs/bootstrap#23406]
With the new Beta, the variables file has been changed **A LOT** from earlier versions of Bootstrap (both v3 and v4alpha6). 

Since some of us are overriding these to customize colors etc, it would be nice to have some kind of migration documentation from the old variables layout to the new.

The only way to find out now is to compare old bootstrap with new which is a tedious work.

So a migration guide would have been great to ease the transition!

**Comment by andresgalante** [comment]
The new variables with colors map is pretty smart. I'll upgrade this week, document it and share my migration path

**Comment by dozer75** [comment]
#23418 Please look at this one too, it's related actually, and very frustrating issue.

**Comment by mdo** [comment]
Alpha releases were rewritten way too extensive to maintain changelogs or migrations for them. Our ship lists are your best bet to find out what's new. I'll consider doing a blog post or something on how to use the new Sass maps though.

That said, this is a new major version and the first stable-ish beta. There's going to be a lot that's new to you—don't expect something from the now four year old v3 to be here still.

If folks have any contributions they'd like to see added to the docs though to help, I'm very happy to hear suggestions! It'll be a couple weeks before I can jump in and start to write anything like that.
