### ISSUE TITLE
Variable changes in beta

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#23411]
I can see that many vairables has different names.
Ex there is no: `$btn-info-color`, `$btn-info-border`, `$cursor-disabled`, `$input-padding-x`, `$input-bg-disabled`, `$input-border-focus`

Whre can I find new variable names?

**Comment by andresgalante** [comment]
You'll find those things here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L53-L57

And they are generated with the `theme-color` map:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L106

**Comment by designbyadrian** [comment]
I suppose you could always check the commit history, but isn't there another change log?

**Comment by mdo** [comment]
The Beta 1 ship list in #21568 has nearly all the changes. There's no migration between alpha and beta.

**Comment by designbyadrian** [comment]
@mdo  Well my app doesn't compile anymore because I'm using Bootstrap variables - so there *is* some updates to do. Anyway, you're link was very helpful, and what affected me so far was https://github.com/twbs/bootstrap/pull/22287
