### ISSUE TITLE
Should the color of warning is light color?

### ISSUE THREAD

**Issue by todoubaba** [twbs/bootstrap#23410]
![badge](https://user-images.githubusercontent.com/4020640/29266502-9a252026-8117-11e7-89f7-a41c2362747e.png)
![warning](https://user-images.githubusercontent.com/4020640/29266501-9a243e2c-8117-11e7-8659-4657ecd1fdf0.png)

**Comment by CheungTatMing** [comment]
I thought this is personal preference and you can change the color yourself.

**Comment by todoubaba** [comment]
I just want to confirm that it is intended. In 3.x, the color of warning is `#fff`,  https://getbootstrap.com/docs/3.3/components/#available-variations.

![qq 20170814190543](https://user-images.githubusercontent.com/4020640/29269447-1163f49e-8124-11e7-87e9-5555edf3701a.png)

**Comment by mdo** [comment]
It's automated based on the contrast with the background.

**Comment by Owumaro** [comment]
Although I understand the contrast issue, this creates another issue: we lost consistency on text colors on buttons/badges.

Other related issue: the outline warning button is still white when hovered.
