### ISSUE TITLE
Any way to migrate alpha-6 projects to beta?

### ISSUE THREAD

**Issue by borishere** [twbs/bootstrap#23425]
Hi,
I know that I can do it by hand but may be there is some migrate tutorial or automatic way?

**Comment by robcresswell** [comment]
There's no automatic method. Just have to study the changes in https://github.com/twbs/bootstrap/releases and https://github.com/twbs/bootstrap/issues/21568.

Bootstrap doesn't seem to produce a full changelog, for some reason.

**Comment by mdo** [comment]
As mentioned, no automatic way to do it.

> Bootstrap doesn't seem to produce a full changelog, for some reason.

Changelogs in the ships lists are your best bet. Alphas changed way too much between each release to track every detail in a comprehendible way.

**Comment by robcresswell** [comment]
Yeah, that's reasonable. Alpha's are explicitly "pre-release, non-prod", so my comment was a bit unfair. Sorry about that.
