### ISSUE TITLE
Grayscale function overrides native CSS filter grayscale

### ISSUE THREAD

**Issue by KyleNeedham** [twbs/bootstrap#23428]
The `grayscale` function definiton in `_functions` overrides the native CSS grayscale function. This means that anywhere you do `filter: grayscale(100)`  it is set to a HEX value, which of course does not work.

Perhaps instead of naming it `graysacle` we could name it `gray`?

**Comment by byteworksng** [comment]
Had the same problem, wonder if there is work around to this without directly modifying the bootstrap _function.scss definition. But that's the option I'm left with.

**Comment by KyleNeedham** [comment]
@byteworksng You can do `#{'grayscale(100)'}`. Works fine, although I hope this will be updated for future releases.

**Comment by byteworksng** [comment]
@KyleNeedham Thanks a lot... It works now.
