### ISSUE TITLE
Dropdown (dropup) in bottom fixed navbar opens down

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#23429]
Either a bug or something I'm missing... When having a dropdown set to dropup in a bottom navbar, it opens the dropdown down instead of up (probably because the container limits the opening to the top). FYI it was working in alpha 6, the bug appeared in beta 1

See the example here: https://plnkr.co/edit/7iaSiawpvF6yqiL3DxGC?p=preview

**Comment by timthewebguy** [comment]
I believe this is referring to this part of dropdown.js right here: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L269

I encountered this issue in trying to have a right-aligned dropdown from a navbar. I cannot understand why this function is here, could someone please clarify the reason for disabling poppers in navbars?

**Comment by enso-media** [comment]
Yep, encountered the same problem. It was working in alpha, now in beta even dropups always opens to the bottom.

**Comment by myorangeca** [comment]
I think this is related to popper.js

**Comment by FezVrasta** [comment]
@myorangeca looking at the code linked by @timthewebguy, Popper gets disabled in this case

**Comment by myorangeca** [comment]
@FezVrasta ops, you are right!
