### ISSUE TITLE
Popper.js with Absolute Footer and Button Dropdowns

### ISSUE THREAD

**Issue by chris-oswald** [twbs/bootstrap#23433]
There is a bug with the latest version of Popper.js and the positioning of dropdown menus when using an absolute footer.  I lost way to much time on this and want others to have something to reference.

**Popper Issue Referenced**
https://github.com/FezVrasta/popper.js/issues/302

Moving back to popper.js version 1.9.3 fixed the button dropdowns issue, but introduced another bug in the navigation dropdowns when viewing in mobile.  The menus change to absolute positioning and overlay other menu items instead of pushing them down the page.  You only see this if you have nav menu items that expand in mobile.

I created the class as a work around and added it to each place i have dropdown-menu in the navbar.  IE: class="dropdown-menu dropdown-menu-position-fix"

// Fix Class for Nav Dropdowns
// You'll need to add a media query to only apply this for the mobile
.dropdown-menu-position-fix {
        position: relative !important;
}

**Comment by FezVrasta** [comment]
This has been fixed in 1.12.3

cc @Johann-S

**Comment by chris-oswald** [comment]
Confirmed - all the issues are fixed!  Thanks for the heads up
