### ISSUE TITLE
Card columns alignment on Edge

### ISSUE THREAD

**Issue by jjvainav** [twbs/bootstrap#23442]
Hello, I was playing around with Bootstrap 4 beta and discovered a potential alignment issue on Edge (v40.15063.0.0).

The below will align the 2 cards horizontally on Edge but vertically when tested on Chrome.

```
  <div class="card-columns">
    <div class="card text-center">
      <div class="card-block">Card 1...</div>
    </div>
    <div class="card text-center">
      <div class="card-block">Card 2...</div>
    </div>
</div>
```

You can see the example here:
https://jsbin.com/mobazixupo/edit?html,output

**Comment by eskirex** [comment]
'card-block' changed to 'card-body' on the v4 beta.

  <div class="card-columns">
    <div class="card text-center">
      <div class="card-body">Card 1...</div>
    </div>
    <div class="card text-center">
      <div class="card-body">Card 2...</div>
    </div>
</div>

https://jsbin.com/qanupupewi/edit?html,output

**Comment by jjvainav** [comment]
@eskirex thanks for the response. I ran your example on Edge with 'card-block' changed to 'card-body' and the 2 cards are still aligned horizontally.

**Comment by mdo** [comment]
This has come up before. There's no way right now to get all browsers to render these the same with so few cards. I'd recommend using the grid instead for now.
