### ISSUE TITLE
Form elements position is off

### ISSUE THREAD

**Issue by gmile** [twbs/bootstrap#23447]
On the ["Forms" page](https://getbootstrap.com/docs/4.0/components/forms/) In the docs some (not all) form elements position are off:

1. Bad:
    ![twbs_form_example_bad_1](https://user-images.githubusercontent.com/207112/29304032-84c6e872-8199-11e7-9f18-3118f3473618.png)

2. Good:
    ![twbs_form_example_good_2](https://user-images.githubusercontent.com/207112/29304037-8b2aadac-8199-11e7-9f3e-c29d36d9b03c.png)

3. Bad:
    ![twbs_form_example_good_3](https://user-images.githubusercontent.com/207112/29304043-90c01b08-8199-11e7-9724-352d90805cbe.png)

Versions I'm looking with:

- macOS 10.12.3
- Chrome 60.0.3112.90

**Comment by wojtask9** [comment]
This PR https://github.com/twbs/bootstrap/pull/23121 should fix issue with .col-form-label
