### ISSUE TITLE
.invalid-feedback doesn't show for .input-group with an invalid control

### ISSUE THREAD

**Issue by simmerz** [twbs/bootstrap#23454]
Example:

```html
<div class="form-group col-md-4">
  <label class="form-control-label is-invalid" for="valuation_value">Estimated Value</label>
  <div class="input-group is-invalid">
    <span class="input-group-addon">£</span>
    <input class="form-control is-invalid" min="0" type="number" value="" name="valuation[value]">
  </div>
  <div class="invalid-feedback">can't be blank, is not a number</div>
</div>
```

Results in:

<img width="217" alt="screen shot 2017-08-15 at 11 59 15" src="https://user-images.githubusercontent.com/24327/29313300-384e904a-81b1-11e7-962c-893d9d708c4c.png">

I would expect to see `can't be blank, is not a number` under the input-group.

**Comment by aedart** [comment]
In your example, you might need to place the `<div class="invalid-feedback">` right after the input (_at least from what I understood in the [docs](https://getbootstrap.com/docs/4.0/components/forms/#server-side)_).

**Comment by simmerz** [comment]
@aedart If I do that, it tries to fit in the feedback inside the input-group, which breaks the layout

**Comment by aedart** [comment]
Yes, you are right. Perhaps a `span` can do the trick.

Also, I just realized that you are also setting the `.is-invalid` on the parent `div`. I do not think that this has any effect at all. Only elements with `form-control` or `.custom-select` should be affected by this.

**Comment by simmerz** [comment]
I tried on the parent div. In the end, I've added the following which does what I want, but my gut says this should work off the shelf:

```scss
.input-group.is-invalid {
  ~ .invalid-feedback {
    display: block;
  }
}
```

**Comment by aedart** [comment]
You are right, just created the fiddle: https://jsfiddle.net/aedart/tLwsztc0/

**Comment by mdo** [comment]
Definitely something to see if we can support. We're also missing proper support for checks and radios as mentioned in another issue.

**Comment by mdo** [comment]
Sorry, to elaborate, the problem is we're not actively asking folks to add a class to the parent of an input. With the HTML5 validation move in Beta 1, we're triggering everything off the state of the input. We need to see if there's something else we can do for the input group, but it's tough given that markup and styling for presenting inputs that way.

**Comment by fjsuarez** [comment]
Related to this issue, when using `is-invalid` on an `input-group`, it should give the border to the entire component.

```
 <div class="input-group is-invalid">
          <div class="input-group-addon">%</div>
          <input  type="number"
                  class="form-control"
                  required>
          
</div>
<div class="invalid-feedback">
</div>
```

This snippet generates something that looks like this:


![image](https://user-images.githubusercontent.com/3099648/29346417-24548498-8213-11e7-9f85-8358f9fa5045.png)

Applying border to the entire `input-group` would make it look more consistent with other default input controls, such as file input:

![image](https://user-images.githubusercontent.com/3099648/29346349-9f862be0-8212-11e7-980a-087400c0cf5d.png)

**Comment by mdo** [comment]
> other default input controls, such as file input:

To be clear, that's not a default input control—that's a hacked up custom form control :).

**Comment by tochoromero** [comment]
I'm having the same problem.
But since I'm coming from the alpha version and I was using `form-control-feedback` with custom JS to hide it when needed, I was able to just override the display of the `invalid-feedback`: 
```
.invalid-feedback {
  display: block;
}
```

I know this is not ideal, but at least it allowed me to move forward.

**Comment by tmorehouse** [comment]
I was encountering this issue as well, trying to figure out how to get the invalid-feedback to show when the invalid-feedback is not a sibling of the input (i.e input groups, etc. (and using a feedback text for custom file-input is another good example.

Once could ad in a JavaScript routine to monitor the validity state of an input (or the is-valid/invalid class) and then check for any elements that may have a `for` attribute that matches the input's ID, or via the aria-describedby attribute (which can contain a list of element IDs) 

But it feels bad using JavaScript to correct this shortcoming.

It would be at least nice to get the ability to place a class on the input-group, and for radio-groups or stacked check boxes, etc (i.e feedback messages to select one)

**Comment by wilsmex** [comment]
I'm having this issue as well.  
As mdo mentioned, It's impossible to trigger the 'block' status with the following markup being that everything is being triggered from the single input state.  You **_have_** to have an 'is-invalid' state that gets added to the parent, as there are not 'parent' selectors in css...

```
  <div class="input-group mb-2 mr-sm-2 mb-sm-0">
    <div class="input-group-addon">@</div>
    <input type="text" class="form-control is-invalid" id="xyz" placeholder="xyz">
  </div>
  <div class="invalid-feedback">
     Please provide a valid state.
  </div>
```

Being that I use solely 'server validation' as they're calling it, I need that parent element 'is-invalid' hook back?

**Comment by talynone** [comment]
How would this be done on a centered bootstrap form centered using the grid system and I wanted to show validation message under the input box on an grouped input box ?

**Comment by holotrek** [comment]
Here's my temporary workaround until they fix this: [https://codepen.io/evshell18/pen/WEzOdj](https://codepen.io/evshell18/pen/WEzOdj)

It's not perfect, and only really works well as long as you have only 1 line of validation text. If your text is longer than a line it might be in danger of flowing over the elements below it, as shown in the example.

Hopefully this gets fixed soon. It should be based on applying the `.is-invalid` class to the `.input-group` and having `.form-control`s within react to it.

**Comment by jwnoz** [comment]
temporary solution is to add these css

`.input-group {
    flex-wrap: wrap!important;

    .invalid-feedback {
        flex-basis: 100%!important;
    }
}`

this will force the feedback to wrap into the 2nd line, then your html put feedback below input

`
<div class="input-group mb-2 mr-sm-2 mb-sm-0">
    <div class="input-group-addon">@</div>
    <input type="text" class="form-control is-invalid" id="xyz" placeholder="xyz">
<div class="input-group mb-2 mr-sm-2 mb-sm-0">
    <div class="input-group-addon">@</div>
    <input type="text" class="form-control is-invalid" id="xyz" placeholder="xyz">
  </div>
  <div class="invalid-feedback">
     Please provide a valid state.
  </div>
  </div>
`

**Comment by tbolon** [comment]
@jwnoz it does not work correctly when the addon is at the end of group: the right border is removed. It is caused by the `.input-group-addon:not(:last-child)` rule.

**Comment by jwnoz** [comment]
@tbolon for that you need to manually add back the border 

```css
.input-group .input-group-addon:nth-last-child(2) {
    border-left: 0!important;
    border-right: 1px solid rgba(0,0,0,.15);
    border-radius: .25rem!important;
    border-top-left-radius: 0!important;
    border-bottom-left-radius: 0!important;
}
```

[https://codepen.io/anon/pen/VzdPON](https://codepen.io/anon/pen/VzdPON)

**Comment by ReSpawN** [comment]
If you ask me, all solutions above seem hacky - at best. The validation support for forms in Alpha 6 and TWBS 3 was a lot better. We're now sorta forced to rely on HTML5 input states rather and advanced markup for column model, input grouped input's.

Eagerly looking forward to a solution, for now I rely on my own CSS skills to make it work, as even examples from the docs don't support is-invalid properly. :(

**Comment by FQ400** [comment]
Is there a reason behind setting `.invalid-feedback` to `display: none`?

**Comment by chrismbarr** [comment]
I'm using angular, and I control the visibility of the feedback with that so I don't care about the nearby element with the `is-invalid` class.

This is my solution to make it always show exactly when I want it.
```html
<div class="invalid-feedback d-block" ng-if="form.$submitted && form.username.$invalid">
```

**Comment by lilpug** [comment]
i ran into this issue as well as i personally use VueJS to i handle all my own showing of validation errors and classes etc. I have built the following quick CSS file that extends the bootstrap 4-beta validation and allows you to do what you did originally in bootstrap 3, I have also added a JSFiddle example link, hope this helps anyone looking to do something similar.

https://github.com/lilpug/bootstrap-4-beta-validation
https://jsfiddle.net/lilpug/1m7heqqr/1/

**Comment by martinbean** [comment]
Urgh, just ran in to this myself.

Why can’t we just have the `.has-error`, `.has-success`, and `.form-control-feedback` classes back? 😞

**Comment by tmorehouse** [comment]
We should be able to have both the old way and the new way.

As well, it is nice to be able to show feedback in the success state as well, not just the invalid state.

**Comment by jimmymain** [comment]
damn: logged a question on [stackoverflow](https://stackoverflow.com/questions/46462133/bootstrap-4-validation-classes-are-not-being-displayed-in-input-feedback-eleme) before finding this issue. maybe the visibility there will create some up-votes for supporting the `has-*` and `:invalid` feedback mechanisms.

**Comment by mdo** [comment]
Testing out something in https://codepen.io/emdeoh/pen/ZXXQKM. Not perfect yet, but wanted to capture something to see if I can make a fix in Beta 2.

**Comment by tmorehouse** [comment]
@mdo  Interesting.

It would be nice to be able to style the input addons too with the proper color/outline.

One thought would be to use flex ordering, and place the input first, and all the addons after, which would allow them to be styled with sibling selectors.  But this makes accessibility a bit awkward, as what is provided to screen readers is not in the same order as presentation (i.e. say a `$` was the first addon, or a checkbox was the first addon, and tab-order was changed since  flex ordering doesn't change tab ordering).

Still, It also doesn't work well with form-groups, where you might have the feedback outside of the input-group (say if someone is making a re-usable form-group component).

Another consideration is when using a framework such as Angular, vue, React, etc,  where validation is performed in the component (where more complex validation can take place, such as verifying that  user's email exists in the DB, etc).  There is no easy way to provide consistent feedback look and feel.

One may as well throw away the form-group markup, as it doesn't work with many of the custom inputs. (custom file - and even plain file inputs - especially has issues with the pseudo `:invalid` and `:valid` states in Firefox.  the button inside the native file picker has the pseudo state, but the outer box of the file input doesn't)

I still think it would be worth while extending the `.is-valid` and `.is-invalid` classes to a form-group (or other outer container), that will trigger styles on input-groups, etc, and  the valid/invalid feedback text similar to the bootstrap V3 and Boostrap V4.alpha code.

You can still leave in native browser validation for those that want it.

**Comment by mdo** [comment]
Thought about `order`, but that also fubars any hope of styling the rounded corners properly since first and last child or of type don't work.

No chance of extending the classes outside the inputs either right now. My goal is to provide as much validation behavior without any additional JS to toggle classes based on a parent or child.

**Comment by tmorehouse** [comment]
I still think both methods could be made available. native browser validation, and a few optional CSS class triggers for "server side" validation (which is a misnomer, as the validation could be done with client side JavaScript)

**Comment by tmorehouse** [comment]
And a note about accessibility... if one uses `aria-describedby` to point at the `invalid-feedback` element text, even though it may be hidden by CSS, some screen readers will still proudly read out the invalid feedback text (hidden or not), even when the input is valid or not validated.:

https://developer.paciellogroup.com/blog/2015/05/short-note-on-aria-labelledby-and-aria-describedby/
> The ARIA attributes aria-labelledby and aria-describedby can be used to provide an accessible name or accessible description for a subset of HTML elements. It is important to note that by design, hiding the content (using CSS display:none or visibility:hidden or the HTML hidden attribute) of the element(s) referenced by these attributes does not stop the content from being used to provide the name/description.

So the current "rely on the browser" to handle validation and feedback has many more issues than just being visually "pretty" or "the latest" fad.

**Comment by davhdavh** [comment]
Please support is-(in)valid on the form-group element, or just any parent element of the invalid-feedback and. input elements.. That would solve most of the issues.

**Comment by martinbean** [comment]
The warning state would be welcomed back, too. I used to use it for drawing attention to inputs on edit forms that _may_ have side effects but aren’t errors, i.e. inputting an article title in all-uppercase when it doesn’t need to be, or a warning that changing the name of an account will change that account’s URLs.

**Comment by shtse8** [comment]
I have the same issue. I can't use the `invalid-feedback` with `input-group` properly.

**Comment by Konafets** [comment]
`invalid-feedback` has the following properties:

```
    display: none;
    margin-top: .25rem;
    font-size: .875rem;
    color: #dc3545;
```

So its not displayed.

**Comment by printercu** [comment]
I've faced an issue and it's slightly related to `input-group`: it's usual to have some input groups, but have inputs separate, without collapsing borders like `input-group` does. For example:

- 2 inputs for range values,
- Rails shows date select by default with 3 inputs,
- inputs may be wrapped into `collapse`s to show one or another type depending on other fields.

And it may require that all of them should have single error. Workaround with `flex-wrap` may be unacceptable in some cases.

**Comment by datune** [comment]
To save others some time from reading the whole thread, it seems that currently, incl. beta2, one possible workaround is to use .flex-wrap and force a width of 100% on the .invalid-feedback element (so it wraps):
```html
        <div class="col-6">
            <label for="validationName">Your name</label>
            <div class="input-group flex-wrap">
                <div class="input-group-addon">@</div>
                <input type="text" class="form-control" id="validationName">
                <div class="invalid-feedback w-100"></div>
            </div>
        </div>
```

Note the w-100 class on the .invalid-feedback element and the .flex-wrap on the input-group element. 

@mdo Any plans for upcoming releases to resolve this? 

@martinbean : Why not use sass @extend if you really want to use .has*? 
```css
.has-error {
    @extend .is-invalid;
}
.has-success {
    @extend .is-valid;
}
```
Personally I don't think it makes any difference (other than bc) what those classes are named, but I do think that is-valid makes a lot more sense than .has-success. After all, a form control is-valid, but a form control has-success?

**Comment by printercu** [comment]
> Why not use sass @extend if you really want to use .has*?

@datune it doesn't work. Here is part of selector: `.form-control.is-invalid ~ .invalid-feedback` it requires `.invalid-feedback` to be sibling to `.has-error` but not the child. This works for inputs, but not for `form-check`s:

```scss
.has-error {
  .form-control { @extend .is-invalid; }
}
.has-success {
  .form-control { @extend .is-valid; }
}
```

However there seems to be an issue with highlighting label for invalid input: https://github.com/twbs/bootstrap/blob/2e920625395334c8211bff86daed7ffbf21a1f8f/scss/mixins/_forms.scss#L71-L79 . With css3 selector it's possible only to highlight only label following input. So `.has-error` is required for now to make it possible to customize label for invalid input.

**Comment by borriej** [comment]
just add a d-flex, like

`
<div class="input-group"></div>
<div class="invalid-feedback d-flex">
`

**Comment by yunti** [comment]
@borriej adding `d-flex` as you suggested worked perfectly and fixes the `display: none` that @Konafets mentioned as the cause of the issue.  For a permanent fix this will need to be included automatically. 


Note the border issue that @fjsuarez mentioned is definitely an ugly issue - is there a separate issue for this?

**Comment by borriej** [comment]
@yunti, in my opinion you should leave the invalid border-color as it is. Only the input is false, not the add-on. Else create your own styling.

**Comment by martinbean** [comment]
@borriej The border color isn’t the problem. It’s the fact the selectors then don’t show the corresponding `.invalid-feedback` messages because they’re not sibling elements of the input.

**Comment by migliori** [comment]
`d-flex` seems to me the best solution so far. it solves the problem while waiting for the next version without  CSS or HTML hack.

I think it is important **not to add anything to the input-group container**. Semantically, the error message should not be included in the group. The last-child should therefore not be modified.

An alternative to d-flex is to add the `.was-validated` class to the form (logical), and the simple css:
`. was-validated. invalid-feedback { display: flex! important}`

**Comment by mdo** [comment]
New take on this coming in #25020. Demo of a new upcoming example featuring input group validation styles is at https://codepen.io/emdeoh/pen/mpewXo (hit the submit button to test). Please share feedback!

**Comment by SPodjasek** [comment]
@wilsmex I have similar issue with server side validation. Luckily for me I had to cope with following markup:

```html
<div class="form-group has-danger">
    <label>Some field</label>
    <div class="input-group is-invalid">
      <span class="input-group-addon">@</span>
      <input type="text" class="form-control form-control-lg is-invalid">
    </div>
    <div class="invalid-tooltip">Error</div>
</div>
```

And solution for not displayed tooltip was pretty simple, replace this:

https://github.com/twbs/bootstrap/blob/eaaad9574c82a92f70c5a1870451b178e34b915a/scss/mixins/_forms.scss#L53-L56

...with this:

```scss
.form-control,
.custom-select,
.input-group {
    .was-validated &:#{$state},
    &.is-#{$state} {
```

@mdo Maybe this could be applied as solution for server side validation case, when you can place feedback in parent of `.input-group`?

**Comment by mdo** [comment]
We're aiming to only put the classes on the inputs, not the parents. Maybe that's something we can expand on in a future update?

**Comment by printercu** [comment]
@mdo is it planed to add ability to customize labels for invalid inputs as it was in bs3?

**Comment by mdo** [comment]
@printercu No, you cannot color the label of most inputs because the label comes before the input. There's no CSS selector that can target that. You could get fancy with some flexbox `order`, but that's about it.

**Comment by printercu** [comment]
This way is not as flexible as bs3 was :(

I think most of applications will not decide to move validations to js as they are not useful for now without external libs. Also, because server-side validation is required anyway for security reasons, implementing js validations doubles the work to be done.

What if small js plugin will simply add `.has-error/.has-succes` class to closest `.form-group` on validation state change? This will keep flexible customization and bring js validations support.

Or at least to add a setting similar to `$enable-transitions` to make bs4 work the old way (support `.has-error` class on `.form-group`).

**Comment by erwin16** [comment]
Using the latest beta-3, the invalid-feedback  does not show up ( as in the beta-2 )
If I add the class="d-flex" to the invalid-feedback , then it shows up BUT when valid , it does not disappear ( should become  display:none )  

`		<div id="userInputGroup4" role="group" aria-labelledby="userInputGroup4__BV_label_" class="b-form-group form-group">
			<label id="userInputGroup4__BV_label_" for="passwordInput" class="col-form-label pt-0">Password:</label>

			<div class="">

				<div role="group" class="input-group">
					<input id="passwordInput" aria-invalid="true" class="form-control is-invalid" aria-describedby="passwordLiveFeedback" type="password">
					<div class="input-group-btn">
					    <a href="#" role="button" class="btn btn-info"><i aria-hidden="true" class="fa fa fa-eye-slash"></i></a>
					</div>
				</div>

				<div id="passwordLiveFeedback" class="invalid-feedback">
				                     At least 6 characters
				 </div>

			</div>
		</div>




		<div id="userInputGroup5" role="group" aria-labelledby="userInputGroup5__BV_label_" class="b-form-group form-group">
		<label id="userInputGroup5__BV_label_" for="confirmPasswordInput" class="col-form-label pt-0">Confirm Password:</label>

		<div class="">

			<input id="confirmPasswordInput" class="form-control is-invalid" aria-describedby="confirmLiveFeedback" aria-invalid="true" type="password"> 
	
			<div id="confirmLiveFeedback" class="invalid-feedback">
			                     At least 6 characters
			    </div>
			</div>
	
		</div>`

Is this something to be fixed in the 4.0.0 release or not ( should I trick it ? )

![screen shot 2018-01-02 at 16 59 49](https://user-images.githubusercontent.com/11973/34490102-fea09658-efde-11e7-841f-f906cd34d1ff.png)

![screen shot 2018-01-02 at 17 00 25](https://user-images.githubusercontent.com/11973/34490112-087b11c6-efdf-11e7-8229-15592f741bb5.png)

**Comment by erwin16** [comment]
Using the latest beta-3, the invalid-feedback  does not show up ( as in the beta-2 )
If I add the class="d-flex" to the invalid-feedback , then it shows up BUT when valid , it does not disappear ( should become  display:none )  

`		<div id="userInputGroup4" role="group" aria-labelledby="userInputGroup4__BV_label_" class="b-form-group form-group">
			<label id="userInputGroup4__BV_label_" for="passwordInput" class="col-form-label pt-0">Password:</label>

			<div class="">

				<div role="group" class="input-group">
					<input id="passwordInput" aria-invalid="true" class="form-control is-invalid" aria-describedby="passwordLiveFeedback" type="password">
					<div class="input-group-btn">
					    <a href="#" role="button" class="btn btn-info"><i aria-hidden="true" class="fa fa fa-eye-slash"></i></a>
					</div>
				</div>

				<div id="passwordLiveFeedback" class="invalid-feedback">
				                     At least 6 characters
				 </div>

			</div>
		</div>




		<div id="userInputGroup5" role="group" aria-labelledby="userInputGroup5__BV_label_" class="b-form-group form-group">
		<label id="userInputGroup5__BV_label_" for="confirmPasswordInput" class="col-form-label pt-0">Confirm Password:</label>

		<div class="">

			<input id="confirmPasswordInput" class="form-control is-invalid" aria-describedby="confirmLiveFeedback" aria-invalid="true" type="password"> 
	
			<div id="confirmLiveFeedback" class="invalid-feedback">
			                     At least 6 characters
			    </div>
			</div>
	
		</div>`

Is this something to be fixed in the 4.0.0 release or not ( should I trick it ? )

![screen shot 2018-01-02 at 16 59 49](https://user-images.githubusercontent.com/11973/34490102-fea09658-efde-11e7-841f-f906cd34d1ff.png)

![Uploading Screen Shot 2018-01-02 at 17.00.25.png…]()

**Comment by SunnyEgbo** [comment]
How do we address a similar issue with HTML text?

e.g.,
`        self.helper.layout = Layout(
            HTML('<input type="text" name="first_name" maxlength="255" placeholder="First name" class="textinput textInput form-control col-lg-6" required id="id_first_name" />'),
            HTML('<input type="text" name="last_name" maxlength="255" placeholder="Last name" class="textinput textInput form-control col-lg-6" required id="id_last_name" />'),
....
)

`

**Comment by strongui** [comment]
This new setup doesn't make sense to me and I have no idea how it passed the alpha. 

What this causes, is having to mix our input and error components. Because you can't have two separate components like INPUT GROUP and ERROR, because your ERROR component has to be rendered inside the input group to show up. That means you have to nest these components, which makes no sense to me, as they are already grouped by the form-group component. 

Therefore, .has-error or .is-invalid on the .form-group should automatically  show the .invalid-feedback component, no matter where it is in the child structure. Forcing it to be a direct sibling of input makes no sense to me.

**Comment by martinbean** [comment]
@strongui Completely agree with this. Using sibling selectors is just wholly inflexible and only covers a fraction of use cases. It’s great if you have a simple form and copy the mark-up from the Bootstrap documentation, but a lot of websites have forms more complex than that.

**Comment by stevebauman** [comment]
This is really lame. Since when was relying on HTML5 and JS validation good practice?

We really really need an option for server side validation.

I'm using VueJS to apply error messages that are returned from my server, and even with just this simple setup, having **any** nested Vue components hides Bootstrap 4's `is-invalid` messages since the error message isn't a child of the input element.

Bootstrap 3's setup worked great, but this is a mess to workaround.

This needs to be fixed imo.

**Comment by lilpug** [comment]
@stevebauman this has definitely been an issue for awhile and still is with icon wrapping as well, just curious though if you have nested inputs put into a vuejs component can you not just use <slot></slot> in the component and style it how you usually would i.e. v-bind:class="{ is-invalid: "error logic here", is-valid: "valid logic here"}"

**Comment by strongui** [comment]
For anyone running into this issue, it is rather easy to fix in your own templates. I've already added this snippet to my app, and BS4 will act like BS3. I feel like this should be the default style markup, but at any rate, here you go: 

SASS CODE
```

.form-group {
  &.was-validated {
    &.is-invalid {
      background-color: #ffe9e6;
      label {
        color: #dc3545;
      }
      .invalid-feedback {
        display: block;
      }
    }
  }
}
```

**Comment by cbossi** [comment]
The `.invalid-feedback` element actually shows up if it is placed within the `input-group`. However, this leads to another problem regarding the border radius. A Solution for that problem is described here: https://github.com/twbs/bootstrap/issues/25110#issuecomment-371630552

**Comment by kjdion84** [comment]
^ Yup. The solution here is to simply add `d-block` to the `invalid-feedback` span.

**Comment by jimmymain** [comment]
I agree with @stevebauman this is properly broken.
Server side validation css is completely overridden by the local validation, making it effectively useless without hacking the scss.

setting `.is-valid` on the input to indicate a server side error is overridden by local validations.

![image](https://user-images.githubusercontent.com/2555050/37887361-a382a288-30c1-11e8-8826-5f1e4582e126.png)

**Comment by skn3** [comment]
adding more weight to this! Server side validation is totally broken in bootstrap4 apart from very very simple examples.

**Comment by skn3** [comment]
Here is a use case where the current syntax does not work. What if you have a composite input that is made of multiple inputs and then you want the validation info to appear below all the inputs? For example you might have a password and password-repeat and then want to show the error message underneath both.

**Comment by burzum** [comment]
Cab we get a proper, official fix for this please?

**Comment by alexandremagro** [comment]
Same issue, any official solution?

**Comment by kjdion84** [comment]
Just add d-block to invalid-feedback so it shows no matter what.

**Comment by wtorsi** [comment]
Hi, what about group of inputs, i mean group of radio buttons or checkboxes, they must have one feedback for whole group. 
What code should be in this case?

**Comment by wtorsi** [comment]
Ok, and what do you think, if we change an order in the input-group by flex order: the input  will be always the first element in the group. 
In this case the only thing we need to fix, is to change the layout markup of the input-group?

**Comment by martinbean** [comment]
@vedmant Agreed.

Can this _please_ be addressed? I get wanting to use progressive web technologies and being semantic, but it’s far too much of an idealistic view and is most web applications aren’t nearly marked up to have errors next to labels. It doesn’t work well with _other_ Bootstrap components (input groups) let alone “real world” layouts.

**Comment by wtorsi** [comment]
Actually, at this moment i've stopped on the bs3 solution

**Comment by Tush2890** [comment]
> Example:
> 
> ```
> <div class="form-group col-md-4">
>   <label class="form-control-label is-invalid" for="valuation_value">Estimated Value</label>
>   <div class="input-group is-invalid">
>     <span class="input-group-addon">£</span>
>     <input class="form-control is-invalid" min="0" type="number" value="" name="valuation[value]">
>   </div>
>   <div class="invalid-feedback">can't be blank, is not a number</div>
> </div>
> ```
> 
> Results in:
> 
> <img alt="screen shot 2017-08-15 at 11 59 15" width="217" src="https://user-images.githubusercontent.com/24327/29313300-384e904a-81b1-11e7-962c-893d9d708c4c.png">
> 
> I would expect to see `can't be blank, is not a number` under the input-group.

Well I was also facing the same issue for below code :-
<div class="form-group" >
      <label>Name<span class="asterisk">*</span></label>
       <input type="text" formControlName="PropertyName" [ngClass]="{ 'is-invalid': submitted && propertiesForms.PropertyName.errors }">
        <div *ngIf="submitted && propertiesForms.PropertyName.errors" class="invalid-feedback">
             <div *ngIf="propertiesForms.PropertyName.errors.required">Name is required</div>
         </div>
 </div>

To my surprise, when I added **form-control** class in input element, it worked like a charm. Best part is that I don't need to do any hack. So this my working code :- 

 <div class="form-group" >
      <label>Name<span class="asterisk">*</span></label>
       <input type="text" class="form-control" formControlName="PropertyName" [ngClass]="{ 'is-invalid': submitted && propertiesForms.PropertyName.errors }">
        <div *ngIf="submitted && propertiesForms.PropertyName.errors" class="invalid-feedback">
             <div *ngIf="propertiesForms.PropertyName.errors.required">Name is required</div>
         </div>
 </div>

**Comment by freddyouellette** [comment]
February 2019 and still no fix for this... input groups are broken for server-side validation. Bump

**Comment by azollai** [comment]
```
.invalid-feedback {
  display: block;
}
```

I am using it in an Angular component , that's why I don't specify it further...

**Comment by shanestreator** [comment]
is-invalid seems to be the way to go, you can conditionally use it with '[classnames](https://www.npmjs.com/package/classnames)'...

import classNames from 'classnames'

`className={classNames(
                            'custom-select',
                            'd-block',
                            'w-100',
                            'bg-light',
                            { 'is-invalid': errors.shippingCountry }
                          )}`

Hope this helps!

**Comment by martinbean** [comment]
C’mon. Is this get fixed properly? It’s been an issue since the beta(s), through two minor releases, and there’s now talk of version 5 when _this_ is still an issue.

@mdo? Can we get a _definitive_ response as to the status of this bug and the Bootstrap’s team to fix it? It’s a tiny bit ridiculous people can’t have error messages show up for inputs unless they’re marked in a particular way (which may not be suitable for all apps).

**Comment by bagaskarala** [comment]
im using bootstrap-vue and vuelidate
this is the fix

```
 <b-form-group label="Field Area" label-for="area" :label-cols-sm="3">
        <b-input-group append="ha">
          <b-form-input
            required
            v-model="$v.formField.area.$model"
            id="area"
            type="number"
            placeholder="1600"
            :state="$v.formField.area.$dirty ? !$v.formField.area.$error : null"
          ></b-form-input>
        </b-input-group>
        <b-form-invalid-feedback
          v-if="!$v.formField.area.required"
          :state="$v.formField.area.$dirty ? !$v.formField.area.$error : null"
        >Area field is required</b-form-invalid-feedback>
        <b-form-invalid-feedback
          v-if="!$v.formField.area.number"
          :state="$v.formField.area.$dirty ? !$v.formField.area.$error : null"
        >Area must use number only</b-form-invalid-feedback>
      </b-form-group>
```

**Comment by giorbismiguel** [comment]
See the following example: https://jasonwatmore.com/post/2018/08/01/vuejs-veevalidate-form-validation-example

**Comment by br3nt** [comment]
There are two working solutions (aka hacks) to get the `invalid-feedback` displaying for `custom-file`.

1) Adding the `flex-wrap` class to the `custom-file` and adding the `w-100` class to the `invalid-feedback` element.

```html
    <div class="section measurements-area" style="display: none">
        <h4>Measure your test sample and upload the csv file</h4>
        <form id="measurements-form" class="needs-validation" novalidate>
            <div class="input-group input-group-sm">
                <div class="custom-file flex-wrap">
                    <input type="file" class="custom-file-input" id="measurements" required>
                    <div class="invalid-feedback w-100">
                        The measurements file is required.
                    </div>
                    <label class="custom-file-label" for="measurements" data-browse="Browse">Upload measurements</label>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit" id="recalibrate">Recalibrate</button>
                </div>
            </div>
        </form>
    </div>
```

2)  Adding `style="position: absolute; top: 3.0em"` to the `invalid-feedback` element.  

```html
<form id="measurements-form" class="needs-validation" novalidate>
    <div class="input-group input-group-sm">
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="measurements" required>
            <div class="invalid-feedback" style="position: absolute; top: 3.0em">
                The measurements file is required.
            </div>
            <label class="custom-file-label" for="measurements" data-browse="Browse">Upload measurements</label>
        </div>
        <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit" id="recalibrate">Recalibrate</button>
        </div>
    </div>
</form>
```

The downside to both of these is that `invalid-feedback` element no longer takes up space so elements below the `custom-file` don't accommodate by moving down to maintain expected spacing.

Furthermore, The following solutions DO NOT work for `custom-file`:

1) Adding the class `d-block` or `d-flex` to the `invalid-feedback` element.

2) 
```css
.input-group {
    flex-wrap: wrap!important;
}

.input-group .invalid-feedback {
    flex-basis: 100%!important;
}
```

Also, the `invalid-feedback` element already has the property `display: block`.

**Comment by supermihi** [comment]
So why's this issue closed? Apparently, you need a hack (as summarized by @br3nt) to get it working, and the natural usage – just add the `invalid-feedback` after the input group – does not behave as expected..

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah, whis the hell is this closed? Please reopen this.

**Comment by br3nt** [comment]
F**k it! I've just created a new ticket.

**Comment by comhernandez28** [comment]
Just thought I'd drop my workaround in Vue. You can probably translate it to other libraries pretty easily. 
A little conditional styling does the trick: 
This goes in the div with the `invalid-feedback` class.

`:style="[ ERROR_TRUE ? {'display': 'block'} : {'display': 'none'}]"`

**Comment by mdo** [comment]
FWIW, this issue is quite old and there have been changes to the form validation styles to make things more bulletproof. v4.4 in particular I believe saw some improvements (see #29264). The input groups show invalid feedback: https://codepen.io/emdeoh/pen/PoqBdzN.

That said, our docs show this working for custom styles and server side, but do note that input groups lose their rounded corners. (We have no way of targeting those corners reliably unfortunately.)

![Screen Shot 2020-03-23 at 10 32 12 AM](https://user-images.githubusercontent.com/98681/77345301-a9ce2900-6cf1-11ea-83e8-11029e343c14.png)

![Screen Shot 2020-03-23 at 10 29 47 AM](https://user-images.githubusercontent.com/98681/77345305-aaff5600-6cf1-11ea-8cff-136883f5ae11.png)

**Comment by repoles** [comment]
It is still not completely consistent. Look at the right border of the input elements inside a .input-group. It is not rounded.

**Comment by stevebauman** [comment]
@repoles He literally said this in his comment:

> That said, our docs show this working for custom styles and server side, but do note that input groups lose their rounded corners. (We have no way of targeting those corners reliably unfortunately.)

**Comment by repoles** [comment]
@stevebauman sorry, I didn't see that note. Thanks!

**Comment by jenstroeger** [comment]
As per @mdo’s [comment](https://github.com/twbs/bootstrap/issues/23454#issuecomment-602747853):

> […] but do note that input groups lose their rounded corners. (We have no way of targeting those corners reliably unfortunately.)

I’ve spent the last hour trying to find a somewhat supported solution to this but there doesn’t seem to be one. Looks like a manual override like this [comment above](https://github.com/twbs/bootstrap/issues/23454#issuecomment-324281718) suggests is as good as it gets?

**Comment by themustafaomar** [comment]
```
<div class="custom-file">
    <input type="file" class="custom-file-input is-invalid">
   <label class="custom-file-label" for="thumbnail">Choose file</label>
</div>
<div class="text-danger small" role="alert">
   <strong>Some message</strong>
</div>
```
![image](https://user-images.githubusercontent.com/46113191/82724226-e2c85100-9cd4-11ea-92ca-7e12228e1ca3.png)

**Comment by martinbean** [comment]
@themustafaomar Yes, you can emulate `.invalid-feedback` with other CSS, but it’s not a great solution for projects using templating to build forms and inputs.

**Comment by francisco-rojas** [comment]
The rounded corners issue can be solved with the border classes too: https://getbootstrap.com/docs/4.0/utilities/borders/
(`border-right` and `border-left`)
