### ISSUE TITLE
Nested Modal in Custom Control

### ISSUE THREAD

**Issue by olcaolgun** [twbs/bootstrap#23453]
Hi,

I have a problem with nested modals. When i define a modal.component for my custom control and open this modal.component from another modal which is including my custom control, "child modal" is appearing inside the first modal's border. 

I want to display modals seperately. How can i solve this problem?

Normally, modals are defined in html in seperate div's. But when it is defined with custom control, it is defined inside the first model's div tag. I wrote an example for custom control behaviour below:

[https://plnkr.co/edit/h6HP98MnQhnCtsVVbUwL?p=preview](https://plnkr.co/edit/h6HP98MnQhnCtsVVbUwL?p=preview)

**Comment by mdo** [comment]
We don't support nested modals. For general how-to, check with StackOverflow or our Slack.
