### ISSUE TITLE
inline form doc example

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#23452]
Hi
https://getbootstrap.com/docs/4.0/components/forms/
inline form
the provided example seems to me confusing
it's work well at smallest screen and when the space is enough to display in one line BUT on screen size who need two line we dont have y margin between form elements...

here is a code pen .. with a possible correction if necessary ?

https://codepen.io/jipexu/pen/prWMKb

**Comment by malsf21** [comment]
Hey @jipexu , I tried reproducing your bug and wasn't able to replicate the issue. On my browser, each element in `form-inline` stacks properly with a vertical margin on a small viewport. Here's a screenshot of what I mean:

![doc](https://user-images.githubusercontent.com/14893287/29346781-ab422094-8215-11e7-8f72-b22d7136ce78.png)

In addition, I took a look at your codepen, and I wasn't able to find a difference between the two different examples (other than a bottom margin on the second inline form, but that exists on any viewport size).

![codepen](https://user-images.githubusercontent.com/14893287/29346760-92594026-8215-11e7-9baa-13b36055c640.png)

Both of these screenshots were taken on Chrome Version 60.0.3112.90.

Can you upload some screenshots of what problem you're encountering? Also, what browser are you using?

**Comment by jipexu** [comment]
@malsf21 thanks but i have this behavior on Safari, FF, and Chrome (all latest version) on Mac Sierra ?...

> it's work well at smallest screen and when the space is enough to display in one line BUT on screen size who need two line we dont have y margin between form elements.... 

??

**Comment by jipexu** [comment]
![form](https://user-images.githubusercontent.com/328101/29354201-0906a25c-826d-11e7-8799-f4eb880e2ee5.jpeg)

**Comment by jipexu** [comment]
![doc_bs4](https://user-images.githubusercontent.com/328101/29355077-ebc303ea-826f-11e7-9130-da27a6e55669.jpeg)
![foem-doc](https://user-images.githubusercontent.com/328101/29355094-f66cc704-826f-11e7-97a0-a11fcb136da2.jpeg)

**Comment by jipexu** [comment]
i dont really said it's bug i just say the html must provide some "y" class ... and in the Doc the provided class are not (enough or correct) ...

**Comment by malsf21** [comment]
Ah, I see what you're saying, that does look like a problem. If you already have a fix, you can submit a Pull Request against `v4-dev`. I can also help you do that if you want.

**Comment by jipexu** [comment]
Thanks ! No i have no idea if we must just a PR to correct the code of the doc Or if we have to go further in css ?

**Comment by malsf21** [comment]
I mean it's up to you, I'm not sure how easy (or necessary) a CSS fix even is. A PR to update the doc is probably enough for now, but you can also make a small note about the problem you faced in the docs.

**Comment by jipexu** [comment]
yep probably adjust the code doc by a pr
@mdo  or team please confirm if usefull or not ?? if yes i will make pr

**Comment by mdo** [comment]
A PR would be great @jipexu.

**Comment by jipexu** [comment]
@mdo  oups sorry  i missed this i will do it ! (because i see it's same in the new doc)
