### ISSUE TITLE
Getting "No mixin named -assert-ascending error" in bootstrap/scss/_variables.scss 

### ISSUE THREAD

**Issue by sushant24** [twbs/bootstrap#23451]
Getting this error when directly importing bootstrap/scss/_variables.scss - 

`@include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
        ^
      No mixin named -assert-ascending`

**Comment by mdo** [comment]
Make sure you're including `_functions.scss`. That's where that is defined. https://github.com/twbs/bootstrap/blob/v4-dev/scss/_functions.scss

**Comment by brajeshsipl** [comment]
@mdo i  checked my _functions.scss there is function name  _assert-ascending  but error is below

 @include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
  No mixin named -assert-ascending

**Comment by anity99** [comment]
I've same error

**Comment by kimmoh70** [comment]
I added following

> @import '~bootstrap/scss/functions', '~bootstrap/scss/variables';

in my main scss file to overcome this issue.

**Comment by janekolszak** [comment]
...and add the include before your variables ;)

**Comment by amo13** [comment]
For anyone landing here while having that problem: 
I also was able solve it by importing functions.scss and variables.scss (and variables_dark.scss), **but** I had to put these files into a subfolder of `app/assets/stylesheets`. So I downloaded them off this repo and put them into `app/assets/stylesheets/bootstrap` named beginning with an underscore, e.g.  `_variables.scss`.
My application.scss not looks like this:
```scss
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS (and SCSS, if configured) file within this directory, lib/assets/stylesheets, or any plugin's
 * vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 */

@import "bootstrap/functions";
@import "bootstrap/variables";
@import "bootstrap/variables_dark";

// here my customizations
$body-bg: $black;

@import "bootstrap";
```

**Comment by optonpo** [comment]
This has snuffed my spirit.

Is 5.4 still a possibility? I heard possibly not.

**Comment by Valsuh45** [comment]
Currently experiencing the same error, but so far I've tried all the above-proposed solutions but none works for me :confused:
