### ISSUE TITLE
Popper.js/Dropdowns - Incorrect Positioning  when body or html have height:100%

### ISSUE THREAD

**Issue by h3christophe** [twbs/bootstrap#23469]
Bootstrap v4 Beta
Code Pen:
https://codepen.io/h3christophe/pen/ZJXqJo

Basically if your html or body tag have a height:100%  the dropdowns will be positioned incorrectly 

You can see the behavior in the code pen, if you click on a dropdown menu positioned below the view port (meaning you need to scroll down)

[http://i.imgur.com/6A4LCHw.jpg](http://i.imgur.com/6A4LCHw.jpg)

Easy fix is to use min-height:100% instead

**Comment by myorangeca** [comment]
Not everyone will have minimum height, some apps I create uses dynamic min-height (changes upon content); this may cause a problem. I raised an issue earlier regarding this https://github.com/twbs/bootstrap/issues/23378#issuecomment-322058629

The custom JS styling offered by popper.js might be needed in most cases.

**Comment by Kopyov** [comment]
This is a serious problem for layouts with sidebar: min-height can fix it, but only partially - you can't stretch child flex container properly as child min-height is ignored. Any solution?

**Comment by myorangeca** [comment]
@Kopyov you will run into issues with IE later.

**Comment by Kopyov** [comment]
@myorangeca Yep you are right, sorry - IE doesn't work well with flex and vh. Removed from my previous comment.

**Comment by Johann-S** [comment]
Thank you to report that issue but we cannot fixed it here because it's a positioning issue with Popper.js maybe @FezVrasta know if this is a well known issue

**Comment by myorangeca** [comment]
@Johann-S maybe we should keep this opened as popper.js is a BS4 dependency.

**Comment by FezVrasta** [comment]
There's already an issue with a lot of informations https://github.com/FezVrasta/popper.js/issues/302

If anyone wants to work on it please leave a comment in the issue
