### ISSUE TITLE
Add Horizontal Cards

### ISSUE THREAD

**Issue by vaggelisifa** [twbs/bootstrap#23462]
I think would be good to add horizontal cards.

**Comment by myorangeca** [comment]
How so? What do you mean by horizontal cards?

**Comment by scrooby** [comment]
Do you mean like this: https://getbootstrap.com/docs/4.0/components/card/#card-groups or this: https://getbootstrap.com/docs/4.0/components/card/#card-decks ?

**Comment by mdo** [comment]
Please search first next time. Duplicate of #20794.

**Comment by vaggelisifa** [comment]
No I mean something like this [http://materializecss.com/cards.html#horizontal](http://materializecss.com/cards.html#horizontal)

**Comment by mdo** [comment]
Yeah, that's the same as the issue I referenced.
