### ISSUE TITLE
Add back responsive gutters

### ISSUE THREAD

**Issue by myorangeca** [twbs/bootstrap#23463]
We had the responsive gutters in Alpha.6 which was extremely helpful. If we are going full responsive and supporting multiple resolutions, why not keep the responsive gutters?

```
$grid-gutter-widths: (
  xs: $grid-gutter-width-base,         
  sm: $grid-gutter-width-base,         
  md: $grid-gutter-width-base,        
  lg: $grid-gutter-width-base,       
  xl: $grid-gutter-width-base     
);
```

**Comment by mdo** [comment]
Duplicate of #22944. As they were implemented, it generated extra and inaccurate markup.

**Comment by wujekbogdan** [comment]
@mdo 
Do I get it right? This feature is removed and it will not be available in the final version?
