### ISSUE TITLE
After switching my project from Bootstrap 3 to Bootstrap 4, the UI collapsed

### ISSUE THREAD

**Issue by tarekahf** [twbs/bootstrap#23466]
Several weeks ago, I tried to implement Bootstrap v4.0.0-alpha.6 (after removing references to Bootstrap 3 from the header), and the project UI collapsed. Basically, a lot of the elements disappeared, and the look and feel was slightly messed up. So, I reverted back immediately without doing any further investigation.

I am just wondering if you have to follow certain steps to migrate to Bootstrap 4 and if you need to make changes to your style.css file or any other changes in HTML.

Appreciate your feedback.
Tarek

**Comment by XhmikosR** [comment]
https://getbootstrap.com/docs/4.0/migration/

**Comment by XhmikosR** [comment]
BTW, if you notice any issues with the aforementioned page, please submit a PR to help improve it.

**Comment by tarekahf** [comment]
OK, thanks... but, if my understanding is correct, I am sure this is not going to be an easy journey !

I was wondering if there is some sort of tool that will assist in this migration process, since a lot of the tasks are about renaming classes used in your project.

Again, I appreciate your feedback, just to make sure that I understand what needs to be done.

Tarek

**Comment by XhmikosR** [comment]
I'm not aware of any such tool personally. It's not so hard, just read the docs and you'll get there. :)
