### ISSUE TITLE
Card overlay with header content overflows

### ISSUE THREAD

**Issue by Miced** [twbs/bootstrap#23467]
When using the new [card image overlay](https://getbootstrap.com/docs/4.0/components/card/#image-overlays) feature together with a featured card header, the overlay content is positioned relatively to the card and ignores the card header height.

Example: [JS Bin](https://jsbin.com/siwanunoze/edit?html,output)
Taken from the official doc examples (if you try to add a card header).

**Comment by mdo** [comment]
I think this might need to be a won't fix—I didn't anticipate folks overlaying headers and footers onto an image overlay like this. If you need that behavior, I'd ditch the overlay modifier and set the image as a `background-image` on the `.card` itself.

**Comment by mdo** [comment]
Closing as a won't fix.
