### ISSUE TITLE
Documentation with <ul>/<li>/<ol> Styles

### ISSUE THREAD

**Issue by Bizarrus** [twbs/bootstrap#23474]
I mot found the section for (unordered/ordered) Lists with specific styles like `square`, `disc` and other...

**Comment by bkdotcom** [comment]
ol: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#Attributes
ul: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul#Attributes
