### ISSUE TITLE
Documentation is using unminified scripts and styles in production

### ISSUE THREAD

**Issue by tomscholz** [twbs/bootstrap#23471]
It seems that the if statement `{% if site.github %}` in the [includes](https://github.com/twbs/bootstrap/tree/v4-dev/_includes) doesn't work as intended. Is [getbootstrap.com](https://getbootstrap.com/) actually hosted on github pages? If not it is no wonder this doesn't work. I am willing to create to a PR, but would like some feedback before I digg into it...

**Comment by XhmikosR** [comment]
Yup, I noticed it today too.

@mdo: you need to run `docs-github` in your script(s).

**Comment by mdo** [comment]
Likely an oversight on my part. Not super concerned given Beta 2 should land shortly. Fwiw, #23375 has the correct command in there.
