### ISSUE TITLE
While modal close the modal-body text is not hiding

### ISSUE THREAD

**Issue by sibaspage** [twbs/bootstrap#23484]
Close the modal,
But the modal-body text is hiding after the modal closed. V4 bootstrap

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bkdotcom** [comment]
dupe of #23288 ?
