### ISSUE TITLE
version 4 beta 1

### ISSUE THREAD

**Issue by luisarcia** [twbs/bootstrap#23480]
Hay inconveniente con col-md-6 al colocarlo dentro de la clase item de owl.carousel; no se elimina los margin izquiero y derecho.

ejemplo:

`<div class="owl-carousel owl-theme">
		<div class="item" id="banner1">
			<div class="row">
				<div class="col-md-6">
					<h1 class="title">Lo piensas. Nosotros lo creamos.</h1>
					<h2 class="subtitle">Diseño y desarrollo web.</h2>
				</div>
				<div class="col-md-6">
					<div class="img-main">
						<img src="images/brain.png"  alt="">
					</div>
				</div>
			</div>
		</div>
		<div class="item" id="banner2">
			<div class="row">
				<div class="col-md-6">
					<h1 class="title">Lo piensas. Nosotros lo creamos.</h1>
					<h2 class="subtitle">Diseño y desarrollo web.</h2>
				</div>
				<div class="col-md-6">
					<div class="img-main">
						<img src="images/brain.png"  alt="">
					</div>
				</div>
			</div>
		</div>
	</div>`

**Comment by mdo** [comment]
No idea what `.owl-carousel` is. We can't help with a static code example here I'm afraid. You'll need to provide a reduced live demo for a proper bug report
