### ISSUE TITLE
Vertical grid

### ISSUE THREAD

**Issue by rshadow** [twbs/bootstrap#23486]
Can you add `row-lg-...`, `row-md-...` etc. for vertical fixed grid? 
It`s a killer feature for fullscreen desktop and mobile web applications.

**Comment by JulBol** [comment]
sure u can buddy 👍

**Comment by XhmikosR** [comment]
You can use the flexbox utilities like `d-flex flex-row flex-md-column` etc.

**Comment by mdo** [comment]
I think you need to re-explain what you're looking for @rshadow. Have an example or screenshot?

**Comment by rshadow** [comment]
For expample one page mobile applications:

Main page: grid. All cells fixed % size. Dynamic font size by display resolution.   https://lh3.googleusercontent.com/SG1GDPJ81HzWYLvjpsnVA-anihXeglj9PffwMVxFSwEl4n7xlZlZKuF3hsGmW-zpxXfk=h900

Fixed top and bottom. Middle content crollable:
https://lh3.googleusercontent.com/2dOiitUhwUU0G9j4GJAHT5F-0L7RCMoeOQgrypfjffDOPbLBofdGvmTQjSTAJ_8P-84=h900

Primary golas:
* One page, fullscreen (only nested scroll).
* Vertical and horizontal grid.
* Responzitive font size by display size.
* For desktop and mobile.

**Comment by mdo** [comment]
No plans for this at the moment.
