### ISSUE TITLE
Collapsed navbar navpill links are all in active state

### ISSUE THREAD

**Issue by haraldpdl** [twbs/bootstrap#23482]
Bootstrap 4.0.0-beta1

Navpill links in a navbar are all displayed in an active state when collapsed. Tested with Edge/Firefox/Chrome. Example:

https://www.bootply.com/VAyFaYVO64

(please click on the mobile icon to show the collapsed view)

**Comment by Johann-S** [comment]
Not sure if it's a JavaScript issue or not but it can be

**Comment by danijelGombac** [comment]
I think is related to this .collapse.show:

https://github.com/twbs/bootstrap/blob/7b873fa0a15c0fb62671f95e966656967c6fd9b4/dist/css/bootstrap.css#L3194-L3198

**Comment by pat270** [comment]
https://github.com/twbs/bootstrap/pull/22513 will probably fix this.

**Comment by insad** [comment]
Solved the problem by patching _nav.css: 

```
//
// Pills
//

.nav-pills {
  .nav-link {
    @include border-radius($nav-pills-border-radius);

    &.active,
    .show > &.active { /* Patch */
      color: $nav-pills-link-active-color;
      background-color: $nav-pills-link-active-bg;
    }
  }
}
```

**Comment by mrjack88** [comment]
I am running into the same issue, when nav-bar collapses, all nav-pills are shown as active, and then when returned to a size bigger than md all nav-pills are active. Here is the sample code: https://codepen.io/mrjack88/full/qPXGaq/. Do you think i should grab alpha version, where it seems to work right according to this thread in the top?
PS. I am using 4.0.0-beta from CDN

**Comment by insad** [comment]
Simply download the latest development version and host it on your own server instead of using CDN... this problem and many others will be gone away...
