### ISSUE TITLE
Validation problems

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#23491]
In beta You introduced new validation classes. I think it's step backwards.
Ex. `invalid-feedback` has `display:none` by default. It displays only when brother element has `is-invalid` class.
I'm using angular which creates new DOM elements and `input` is in custom tag `my-field`.

Also now label is not marked when is invalid. Ex. using ckeditor. Changing ckeditor color is rather not necessary - changing label color worked perfectly.

Can You reconsider using `has-danger`?

**Comment by mdo** [comment]
We're sticking with native HTML5 form validation, sorry.

You can extend the default styles as much as you want. `.invalid-feedback` and `.invalid-tooltip` are there to provide contextual error messaging by their fields. If you need something else there, add that markup. This doesn't replace that.
