### ISSUE TITLE
MS Edge table columns

### ISSUE THREAD

**Issue by QuantumHive** [twbs/bootstrap#23493]
A rendering problem in Microsoft Edge when using `<table class="table">` with columns e.g.
```
<table class="table">
    <thead>
        <tr class="row">
            <th class="col-2">column 1</th>
            <th class="col-3">column 2</th>
            <th class="col-7">column 3</th>
        </tr>
    </thead>
</table>
```
This renders good in Firefox and Chrome, but **not** in MS Edge.

- Operating system and version: Windows 10
- Browser and version: MS Edge 40.15063.0.0

See this [SO post](https://stackoverflow.com/questions/45442207/bootstrap-4-table-column-width-not-formatting-correctly-in-ie11-and-microsoft-ed). That guy has included a [jsfiddle](https://jsfiddle.net/vqazpa15/), which is tested with `alpha-6`. However this still applies to `beta1`.

**Comment by mdo** [comment]
Don't use v4's row and column classes on table elements—it'll undo the table display styles from the browser and make them flexbox.

**Comment by QuantumHive** [comment]
Then what is the recommended approach for the same results?

**Comment by QuantumHive** [comment]
@mdo

**Comment by fuglede** [comment]
The discussion in #863 contains some workarounds that still do the job here.
