### ISSUE TITLE
Beta broke CSS

### ISSUE THREAD

**Issue by EdJones** [twbs/bootstrap#23492]
Not sure what this says. I only closed one open `<a href>` from previous working build. Heroku updated to Bootstrap beta and this is what happened:
```
remote:        Sass::SyntaxError: ".authform form" failed to @extend ".bg-faded".
remote:        The selector ".bg-faded" was not found.
remote:        Use "@extend .bg-faded !optional" if the extend should be able to fail.
remote:        /tmp/build_a05542fa183bf9aee218e38f349d8be7/app/assets/stylesheets/1st_load_framework.css.scss:59
remote:        /tmp/build_a05542fa183bf9aee218e38f349d8be7/vendor/bundle/ruby/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/extend.rb:56:in `block in check_extends_fired!
[bootstrap_beta_error.txt](https://github.com/twbs/bootstrap/files/1228274/bootstrap_beta_error.txt)
```

Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://validator.w3.org/nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by DaleMckeown** [comment]
Some of the classes were renamed. You'll either want bg-dark or bg-light going forward.

**Comment by XhmikosR** [comment]
Yup, @DaleMckeown is right.

**Comment by EdJones** [comment]
K. Looks like it is one of @DanielKehoe's files. Though I'm having trouble seeing which one. Thanks.
