### ISSUE TITLE
Carousel Documentation contains broken Link (B4)

### ISSUE THREAD

**Issue by herbalite** [twbs/bootstrap#23506]
Navigate to "Methods" on the carousel page => https://getbootstrap.com/docs/4.0/components/carousel/#methods

Broken Link has the following text=> "See our Javascript documentation for more informations.

Link points to => https://getbootstrap.com/getting-started/javascript/

Link probably should point to => https://getbootstrap.com/docs/4.0/getting-started/javascript/

**Comment by XhmikosR** [comment]
This is already fixed.

**Comment by shamotufei** [comment]
shaziJ8
