### ISSUE TITLE
Esc key closes modal and dropdown if dropdown is open inside it

### ISSUE THREAD

**Issue by GearTheWorld** [twbs/bootstrap#23507]
When I have a modal and in the model I have a DropDown.  If I click the DropDown and it opens clicking ESC doesn't close de DropDown but the entire modal.

If it's by design I don't understand.  ESC should check if a DropDown is opened and if so closing it then if there's nothing else opened the second ESC should close de dialog

This happens right now in 3.3.7 but I want to know if this changed in 4 or if this will remain like that ?

For instance : I pick a DropDown but it was not the right one.  Now I have to click somewhere else with the mouse but many people uses TAB to go from one control to the next

**Comment by bkdotcom** [comment]
currently same behavior in 4

**Comment by patrickhlauke** [comment]
note that the behavior of ESC has been changed recently ... worth evaluating this in the context of the new code https://github.com/twbs/bootstrap/pull/28912

if the problematic behavior described here is still present, i'd hazard a guess that the the ESC handling in the dropdown.js needs to `stopPropagation` and or `preventDefault` after it closes the dropdown.

**Comment by mdo** [comment]
Looks like no one followed up on this, but this does indeed happen in v4.5.3: https://codepen.io/emdeoh/pen/ZEpjNRZ. This CodePen was from another issue, but this described behavior does exist here.

**Comment by patrickhlauke** [comment]
just checked, and this is not an issue anymore in `v5`. i believe i know where the issue in `v4` can be patched though...

**Comment by patrickhlauke** [comment]
i'm a bit stumped because we do seem to call `event.stopPropagation()` for key events ... not sure why it's not preventing the `Esc` from bubbling up to the modal. unless we're not capturing events in the bubbling stage, or there's something else weird happening  https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L470

**Comment by patrickhlauke** [comment]
digging a bit deeper, it seems that the modal gets the `Esc` keydown event before the dropdown. this smells like it's to do with a fundamental way in which our events are being handled (capture phase rather than bubbling phase?) which is way beyond my JS knowledge to tackle (due to the overly convoluted event handling that we use)...

**Comment by alpadev** [comment]
@patrickhlauke looks like that's a problem with how we bind handlers with jQuery.

For `modals` we bind the key handlers directly to the [element](https://github.com/twbs/bootstrap/blob/v4.6.0/js/src/modal.js#L333) but for `dropdowns` the key handler is bound on the [document](https://github.com/twbs/bootstrap/blob/v4.6.0/js/src/dropdown.js#L512) instead (with a selector to filter events that are not related). This should explain the order in which events are fired and why stopPropagation in the `dropdown` wouldn't help.

**Comment by Jarek300** [comment]
I'm not sure that is is not an issue in v5.03. Check this [CodePen](https://codepen.io/Jarek3000/pen/LYxVJJg).

If you click dropdown and press Esc then dropdown closes and modal not. But if you press Esc again nothing happens - modal does not close. You have to press Tab to focus a button and then press Esc.

**Comment by patrickhlauke** [comment]
yes, in 5.0 the dropdown contains/swallows `Esc` (but also when it's closed, which arguably is a different sort of problem)

**Comment by GearTheWorld** [comment]
I took a look at @Jerek300 CodePen and after ESC the dropdown, we stay in the dialog GREAT but from there ESC the dialog is impossible due to the dropdown being focused and not the dialog.  If we click outside the dropdown then ESC is possible.

**Comment by patrickhlauke** [comment]
well yes as i said, the dropdown component swallows the `Esc` even when it's closed (as in when the button/trigger that opens the dropdown is focused)

**Comment by GearTheWorld** [comment]
Then an ESC on a focused dropdown should unfocus it?

**Comment by patrickhlauke** [comment]
no. `Esc` on a focused but closed dropdown trigger should not be intercepted/swallowed by the dropdown code. it would then travel up the DOM and be caught by the modal, which would then respond to it and close

**Comment by GearTheWorld** [comment]
I see!
Then we just have to hit TAB and make sure we are out of focused.  
Thanx for the explaination!

**Comment by GearTheWorld** [comment]
test

**Comment by GearTheWorld** [comment]
Testing why sometimes the editor doesn't clear its content after commenting

**Comment by mdo** [comment]
Closing as stale / won't fix for v4—this has been addressed in v5 I believe.
