### ISSUE TITLE
Scrollspy in bootstrap 4.0.0-beta seems not working

### ISSUE THREAD

**Issue by phangia2712** [twbs/bootstrap#23501]
#**I tried to follow the documentation:**
CSS:
body {position: relative;}
.active a, .active{color: red;}
HTML:
<code>
`&lt;body data-spy="scroll" data-target="#navbar-example"&gt;
&lt;div id="navbar-example"&gt;
        &lt;ul class="nav" role="tablist"&gt;
           &lt;li&gt;&lt;a href="#one"&gt;one &lt;/a&gt;&lt;/li&gt;
           &lt;li&gt;&lt;a href="#two"&gt;two &lt;/a&gt;&lt;/li&gt;
           &lt;li&gt;&lt;a href="#three"&gt;three&lt;/a&gt;&lt;/li&gt;
        &lt;/ul&gt;
      &lt;/div&gt;
.......
.......
.......
</body>`
</code>

**But it's not working. What's wrong with me??**

Please review this file that I did
https://www.dropbox.com/s/jfhvq1ip87ekcxs/Untitled-1.html?dl=0

Thank you for your support!

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by phangia2712** [comment]
Ok, it's my issue, scrollspy bootstraps 4 beta not working:
https://codepen.io/anon/pen/rzpWEr
Tks!

**Comment by pehaa** [comment]
I works once you add "nav-link" class to the links in your menu https://codepen.io/pehaa/pen/braKZB

**Comment by phangia2712** [comment]
Wow, so amazing! Thanks so much!!!!!

**Comment by Johann-S** [comment]
Closed thanks to @pehaa comment's 👍

**Comment by k-funk** [comment]
The required use of `nav-link` really ought to be in the docs.
