### ISSUE TITLE
button-variant mixin - calculating active color

### ISSUE THREAD

**Issue by gogy27** [twbs/bootstrap#23514]
Hi, guys

I thinks that `button-variant` mixin should calculate `color` property for hover state from its `$active-background` variable not the `$background` var. The problem is when I want a black button to change its `background-color` to white it leaves the `color` property also white not black as I would expected.

See here: https://github.com/twbs/bootstrap/blob/27637cf3bd6ffb80986a0894c70508ea1130cbc1/scss/mixins/_buttons.scss#L13

What do you think?

**Comment by mdo** [comment]
Fixed by #23657.
