### ISSUE TITLE
Bootstrap v4 Beta - Popover, Tooltip issue (popper.js)

### ISSUE THREAD

**Issue by DaleMckeown** [twbs/bootstrap#23517]
When a container has a set height, and the content overflows, and that overflowing content contains a tooltip or popover, the position of the popover/tooltip is not correct:

![image](https://user-images.githubusercontent.com/1249673/29415202-28e41bd4-835a-11e7-8921-c67e6ed76924.png)

Live example:
https://www.codeply.com/go/HcvuTaMZPu

@FezVrasta may be able to provide insight?

**Comment by DaleMckeown** [comment]
Argh, apparently this is an issue with popper.js directly.

https://github.com/FezVrasta/popper.js/issues/302

Closing...

**Comment by FezVrasta** [comment]
Sorry guys, I'll try to work on that error when I have some free time to allocate

**Comment by Jossnaz** [comment]
this is a big bug! because a lot of people use `html{ height:100%;} body{height:100%;}` then have the content scroll. That means all popovers will fail to work almost _always_. It's not even _only_ the bug reported, but placements are _completely_ wrong generally. E.g. they appear top, should be bottom etc.

**Comment by FezVrasta** [comment]
If I have to give my opinion, the whole practice of set a fixed height to html and body is quite bad.
It changes completely the behavior of the whole document without any kind of advantage.

Said that, it's still a bug and it will get fixed anytime soon.

**Comment by myorangeca** [comment]
> If I have to give my opinion, the whole practice of set a fixed height to html and body is quite bad.

@FezVrasta while I agree with you, but it is still and will continue to be practiced based on client's demand and project requirements.

**Comment by FezVrasta** [comment]
@myorangeca I'd be curious to see how this practice can need to be enforced to fulfill any requirement...

**Comment by myorangeca** [comment]
@FezVrasta the min-height and height for html,body is needed when having a left panel with absolute positioning. Almost all admin panels (premium and free), created with BS3 or BS4.alpha, are using this method.

**Comment by Jossnaz** [comment]
the height of html and body is used as well for full screen intro parts of the page. The thing is, using 100vh can cause some issues on mobile devices

**Comment by DaleMckeown** [comment]
@FezVrasta  Setting the height on the html or body isn't necessary to trigger this bug - simply set the height of any div, then set the content overflow to visible and make the the content overflow. 

See my live example below for a perfectly sound use case, which is to create a cross browser 'sticky footer'.

https://www.codeply.com/go/HcvuTaMZPu

**Comment by FezVrasta** [comment]
@DaleMckeown your bug has been fixed in Popper.js@1.12.3

**Comment by DaleMckeown** [comment]
@FezVrasta Confirmed, it has! Thank you :)
