### ISSUE TITLE
Bootstrap v4 beta - Documentation shows native font stack "system-ui" but it has been removed

### ISSUE THREAD

**Issue by dotnetshadow** [twbs/bootstrap#23518]
The documentation for native fonts needs to be updated to remove **system-ui**
https://v4-alpha.getbootstrap.com/content/reboot/#native-font-stack

```
// Chrome >= 56 for OS X (San Francisco), Windows, Linux and Android
system-ui,
```

A recent commit shows that this font is no longer used
https://github.com/twbs/bootstrap/issues/22328

When looking at the **dist/css/bootstrap.css** it is indeed gone
```
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  font-size: 1rem;
  font-weight: normal;
  line-height: 1.5;
  color: #212529;
  background-color: #fff;
}
```

**Comment by XhmikosR** [comment]
@dotnetshadow; I made #23521, but you are welcome to provide PRs yourself in the future for such things :)

**Comment by dotnetshadow** [comment]
@XhmikosR ahh cheers yeah I forgot about that thanks
