### ISSUE TITLE
Tooltip and body {height: 100%}

### ISSUE THREAD

**Issue by demyan1411** [twbs/bootstrap#23511]
If I write body {height: 100%}, tooltip position wrong,
This option: 'boundariesElement: 'viewport' in Popper.js, resolve this issue,
Please fix it

**Comment by Johann-S** [comment]
Related to this Popper.js issue https://github.com/FezVrasta/popper.js/issues/302 not to our hand but it can be useful to allow users to choose how Popper.js will prevent the overflow

**Comment by FezVrasta** [comment]
This has been fixed in 1.12.3, note that there's still https://github.com/FezVrasta/popper.js/issues/331 that could cause some headaches, PRs are welcome!

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/23626 and the awesome work of @FezVrasta
