### ISSUE TITLE
@media-breakpoint-only broken for largest and smallest breakpoint

### ISSUE THREAD

**Issue by rvock** [twbs/bootstrap#23516]
The mixin `media-breakpoint-only` checks if it's the largest or smallest breakpoint and then uses `media-breakpoint-up` or `media-breakpoint-down`. But it does not pass `@content` to those mixins.

https://github.com/twbs/bootstrap/blob/27637cf3bd6ffb80986a0894c70508ea1130cbc1/scss/mixins/_breakpoints.scss#L96-L104

**Comment by geetee24** [comment]
hi...   this bug is still present in current download latest version 4.0.0-beta.

When can this fix appear in a public downloadable release?  Thanks.

**Comment by patrickhlauke** [comment]
when beta 2 is released. no hard release date yet.
