### ISSUE TITLE
Bootstrap [v4.0.0-beta]: I can't find class "has-danger"

### ISSUE THREAD

**Issue by dejurin** [twbs/bootstrap#23515]
> Renamed .has-error to .has-danger.

I think you forget include .has-danger class

**Comment by mountash** [comment]
I think that was replaced with `.is-invalid`. See [docs](https://getbootstrap.com/docs/4.0/components/forms/#server-side). 
But what about `.has-warning`?

**Comment by DaleMckeown** [comment]
has-danger -> is-invalid
has-success -> is-valid
has-danger has been removed.

**Comment by Johann-S** [comment]
You can see how to use form validation here : https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by mountash** [comment]
@Johann-S and what about `.has-warning`?

**Comment by DaleMckeown** [comment]
@mohnish has-warning was removed.

**Comment by dejurin** [comment]
how use if I have multi checkbox? And I should SELECT something ones?

**Comment by dejurin** [comment]
https://puu.sh/xcuIP/98cb59d589.png

**Comment by Johann-S** [comment]
You have the `.is-invalid` class

**Comment by dejurin** [comment]
not working with multi checkbox

**Comment by Johann-S** [comment]
Please open a new issue with a reduce test case
