### ISSUE TITLE
Default badges are not visible in List Group documentation.

### ISSUE THREAD

**Issue by manoj-netlings** [twbs/bootstrap#23538]
Default badges are not visible on screen in the List group example:
https://getbootstrap.com/docs/4.0/components/list-group/#with-badges

`.badge-default` class is not working or doesn't have `background-color` css set correctly.

**Comment by jipexu** [comment]
yep is fixed on dev branch thanks

**Comment by Johann-S** [comment]
that's what I thought thanks @jipexu 👍
