### ISSUE TITLE
Navbar content goes off page on IE / Windows

### ISSUE THREAD

**Issue by neoschronos** [twbs/bootstrap#23531]
Hi,

on Windows 7, using Internet Explorer 10, and bootstrap 4 (beta) the navbar content goes off page. 

The easiest way to replicate the behavior is

**Option 1**

open Bootstrap's [fixed-navbar example](https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/) on the aforementioned combination of browser / OS. The rendered reply looks like in [this picture](https://www.browserstack.com/screenshots/c3197480c5c5ef0cfb7325d81ef945a08968f5c7/win7_ie_10.0.png) i.e. the search button goes off the page.

In case it is helpful - the same Bootstrap example works fine with other browser/OS combinations e.g. Edge14 / Windows 10, IE 11 / Windows 10.

**Option 2**

You can try to open the aforementioned [example](https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/) also on [Browserstack](https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/)

![win7_ie_10 0](https://user-images.githubusercontent.com/31112202/29433965-874b88d2-83a1-11e7-9c92-e2298746f106.png)

Cheers,
     Thomas

**Comment by neoschronos** [comment]
![win7_ie_10 0](https://user-images.githubusercontent.com/31112202/29433965-874b88d2-83a1-11e7-9c92-e2298746f106.png)

**Comment by neoschronos** [comment]
Apologies this was not supposed to be closed, this was a rookie error.

**Comment by Studio384** [comment]
Might be related to #23290?

**Comment by neoschronos** [comment]
I checked #23290 before submitting this. I cannot say if these are related, however the issue / example I submitted is about the fixed version of the navbar, whereas #23290 is about the sticky version. For sure both issues are about the navbar, I'd guess though this is where commonality stops. Cheers, Thomas
