### ISSUE TITLE
Bootstrap 4: heading won't align to center

### ISSUE THREAD

**Issue by jantivola** [twbs/bootstrap#23537]
Hi, I'm starting to fix my css since I just updated our website's bootstrap source code to version 4.

I've got an issue with regards to aligning the heading to center.  I've tried the following options:

**option 1**:
```
#sectionname h2 {
text-align: center;
}
```

**option 2**:
```
#sectionname h2 {
text-align: center!important;
}
```

**option 3**: (the latest i've added)
`<h2 class="text-center">How does it work?</h2>`

still, it won't work. I've shared a screen cap for reference. 

![untitled](https://user-images.githubusercontent.com/10664192/29448185-fade23be-8427-11e7-8522-25e6ad317cc2.png)

Any help will be appreciated. Much love to bootstrap!

**Comment by splice7** [comment]
You can use Flexbox here. Just add `.d-flex` and `justify-content-center` to them and it'll be centered.

**Comment by jipexu** [comment]
<div class="row d-flex justify-content-center">
  <h3>MY TITLE</h3>
</div>

**Comment by anaggh** [comment]
Since your screenshot shows that it is between `row` try using `mx-auto`

```
<div class='row'>
  <h2 class='mx-auto'>hello</h2>
</div>
```

**Comment by jipexu** [comment]
@anaggh 

yes this is the shortest way of the two solution

**Comment by mdo** [comment]
Columns should be the only children elements of a row. Rows are flexbox, thus your heading is behaving as a flex item.

**Comment by jantivola** [comment]
Thanks @anaggh , it worked :)

**Comment by jantivola** [comment]
Thank you, @mdo I'll keep that in mind :)
