### ISSUE TITLE
Navbar toggler is misaligned on iOS

### ISSUE THREAD

**Issue by neoschronos** [twbs/bootstrap#23532]
Hi,

on iPhone 6 Plus, iOS 8.3, and bootstrap 4 (beta) the toggler is misaligned

The easiest way to replicate the behavior is

**Option 1**

open Bootstrap's [fixed-navbar example](https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/) on the aforementioned combination of browser / OS. The rendered reply looks like in [this picture](https://www.browserstack.com/screenshots/c3197480c5c5ef0cfb7325d81ef945a08968f5c7/ios_iPhone-6-Plus_8.3_portrait.jpg) i.e. the toggler is aligned _left_, beside the Fixed Navbar (class:  `.navbar-brand`), when it should align _right_.

**Option 2**

You can try to open the aforementioned [example](https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/) also on [Browserstack](https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/)

A "fix" that worked was to overwrite Bootstrap 4 `.navbar-toggler`  definition by adding 

`.navbar-toggler { float: right; }`

Cheers,
     Thomas

**Comment by neoschronos** [comment]
![ios_iphone-6-plus_8 3_portrait](https://user-images.githubusercontent.com/31112202/29433854-28926fe0-83a1-11e7-870b-35ed3f27da75.jpg)

**Comment by neoschronos** [comment]
Apologies, this was not supposed to be closed, it was a rookie error.

**Comment by Joyrex** [comment]
If I understand the Docs, the toggler placement behavior has changed since Alpha 6, and now the position of the Toggler is dependent on their placement: https://getbootstrap.com/docs/4.0/components/navbar/#toggler

I confirmed this with the Docs on iOS 11/Safari

**Comment by neoschronos** [comment]
hi @Joyrex, I am using emulators of devices, and that was what I had available for testing. Thanks for confirming that in newer iOS versions there is no issue.
