### ISSUE TITLE
Hidden Responsive Utilities Missing in Beta 4

### ISSUE THREAD

**Issue by pskigen** [twbs/bootstrap#23549]
Hidden-*-up and hidden-*-down classes are now missing from the beta version of Bootstrap 4, and unless I am not understanding the documentation properly, the new solution using .d-*-none replacing does not achieve the same functionality.

This would require declaring a class for every screen size you don't want an element do display on, rather than a single class declaration which would take care of several screen sizes. I would greatly appreciate some replacement of the hidden-up and hidden-down classes before the official release, as I and many of the other developers I know using Bootstrap find these utilities extremely useful. 

As a side note, I appreciate all the hard work that goes into this project.

**Comment by jipexu** [comment]
Hi please have a look here
#23475

**Comment by pskigen** [comment]
Thank you for the link, sorry I must have missed that issue when I was checking for duplicate posts. Not really a great solution, in my opinion, but I suppose that means there's no interest in changing the class names, so I'll close this.

**Comment by mdo** [comment]
> This would require declaring a class for every screen size you don't want an element do display on, rather than a single class declaration which would take care of several screen sizes.

You're misunderstanding the new classes—they do what you want. `.d-none` hides for everything, `.d-md-none` hides for md and above. We just don't have a second direction anymore (no more hiding for a viewport and down). In those cases, use a mix of the display utilities.

**Comment by pskigen** [comment]
Thanks for the response @mdo. After reading through the thread @jipexu referenced, I have a better understanding of how the utility works. I was a fan of the alpha .hidden classes, but given some thought I can see the advantages to the new setup as well. I think it will just take some getting used to.
