### ISSUE TITLE
Dropdown menu alignment inside navbar

### ISSUE THREAD

**Issue by matkokvesic** [twbs/bootstrap#23548]
Dropdowns placed inside navbar are not aligned according to alignment classes: https://plnkr.co/edit/cEzEw6XKqRvml35UL9H1?p=preview

Version: 4.0.0-beta
Browser: Chrome 60.0.3112.101

**Comment by Johann-S** [comment]
Because as it written in our docs you should have a `.navbar-nav` in your navbar if you use dropdown see : 
https://getbootstrap.com/docs/4.0/components/navbar/#supported-content

**Comment by matkokvesic** [comment]
Can you provide a simple example for this? I cannot make it work by adding `.navbar-nav`

**Comment by Johann-S** [comment]
https://codepen.io/Johann-S/pen/dzdZyL?editors=1000
