### ISSUE TITLE
.navbar-inverse not in CSS file

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#23545]
Using either the bootstrap.css or bootstrap.min.css, a search for navbar-inverse returns no results.

Is there a list of all classes that are not included in the CSS files, to easily see what can and can't be used?

**Comment by jipexu** [comment]
Hi
in the doc .."Theming the navbar has never been easier thanks to the combination of theming classes and background-color utilities. Choose from .navbar-light for use with light background colors, or .navbar-dark for dark background colors. Then, customize with .bg-* utilities."

**Comment by leecollings** [comment]
The v4 example of 'dashboard' shows the usage of navbar-inverse:

https://v4-alpha.getbootstrap.com/examples/dashboard/

**Comment by jipexu** [comment]
yep unfortunatly  but this not up to date .. is not a BS 4 example ...

**Comment by Johann-S** [comment]
https://getbootstrap.com/docs/4.0/migration/#navbar

thanks @jipexu
