### ISSUE TITLE
pull push concept

### ISSUE THREAD

**Issue by viral16d** [twbs/bootstrap#23543]
pull push concept are not working. also not found in css

**Comment by patrickhlauke** [comment]
please read the migration documentation before filing bugs https://getbootstrap.com/docs/4.0/migration/#utilities

**Comment by viral16d** [comment]
it will not working ,
i will find 'pull', 'push' keyword in css file it also not found

**Comment by viral16d** [comment]
it was available in bootstrap4 alfa verstion

**Comment by prateekgoel** [comment]
push and pull have been replaced with floats. Please read https://getbootstrap.com/docs/4.0/migration/#utilities carefully.

**Comment by fsasvari** [comment]
Yeah, but there is no float-3-right ? Something to match col-3 or push-3
