### ISSUE TITLE
Bootstrap 3.3.7 - Why is the !important attribute implemented?

### ISSUE THREAD

**Issue by siide** [twbs/bootstrap#23540]
The bootstrap version 3.3.7 cause some major issues when using modals, functions etc.

If I want to use the class .hide for example, which is one of the declared classes in Bootstrap Css. The new version has set !important to that class, causing that the style never can be overwrite.
The same goes to the rest like .pull-right, .pull-left and .show.
.pull-right {
  float: right !important;
}
.pull-left {
  float: left !important;
}
.hide {
  display: none!important;
}
.show {
  display: block !important;
}
_________________________________________________________________________________________________________

 I was playing around with some older versions of Bootstrap from some old webpages of mine. The bootstrap 2.2.2 looks like this:

.pull-right {
  float: right;
}

.pull-left {
  float: left;
}

.hide {
  display: none;
}

.show {
  display: block;
}

These classes can be used anywhere with out having problem of the structure to overwrite the style like hide or show.

I don't want to touch the bootstrap file if new versions comes out etc. 

Why is it even set to !important?

**Comment by patrickhlauke** [comment]
naive question: why would you want to override what is essentially the core reason for those modifier classes? i.e. why would you want to have, say, `.pull-left` but override the fact that this class results in left floating? just don't use the class...

**Comment by patrickhlauke** [comment]
and to answer the question: the reason for the `!important` is to ensure a bit more that those classes, when applied, can more easily "punch through" any other (custom) CSS you may already have on the page.

**Comment by siide** [comment]
@patrickhlauke Thank you for the answer. I should have edited the question and specify what my little problem was, more like; shouldn't Bootstrap.css and Bootstrap.js work togheter with the class .hide? Because the modal function are using "display: block;". I mean, if you want to use a standard structure. 
I just thought "if a developer is new to Bootstrap and, let's say, he/ she are using the modal function and sets .hide", then Modal will never open if you're not modifying the Css class. Since the show/hide thinking is a standard. But yea, you can use .fade to make it work.

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
