### ISSUE TITLE
Why do you have to redeclare the whole SASS Map?

### ISSUE THREAD

**Issue by DarrenMack-OD** [twbs/bootstrap#23542]
Why do you have to redeclare the whole SASS Map when you re-map the variables?

I can't complete a build if I do this partially, I have to redeclare everything to make it work :(

**Comment by bardiharborow** [comment]
I assume you're referring to the maps added in #23260. The whole point is that you shouldn't have to redeclare the whole map, so if that's what's happening to you, can you share your code and what sass version you're using, and we'll try and figure out what's going on.

**Comment by takuhii** [comment]
This is your code;
```
$blue:    #007bff !default;
$indigo:  #6610f2 !default;
$purple:  #6f42c1 !default;
$pink:    #e83e8c !default;
$red:     #dc3545 !default;
$orange:  #fd7e14 !default;
$yellow:  #ffc107 !default;
$green:   #28a745 !default;
$teal:    #20c997 !default;
$cyan:    #17a2b8 !default;

$colors: (
  blue: $blue,
  indigo: $indigo,
  purple: $purple,
  pink: $pink,
  red: $red,
  orange: $orange,
  yellow: $yellow,
  green: $green,
  teal: $teal,
  cyan: $cyan,
  white: $white,
  gray: $gray-600,
  gray-dark: $gray-800
) !default;

$theme-colors: (
  primary: $blue,
  secondary: $gray-600,
  success: $green,
  info: $cyan,
  warning: $yellow,
  danger: $red,
  light: $gray-100,
  dark: $gray-800
) !default;
```

This is our code, in out themeing file, without the above variables declared, as they are already in _variables.scss;
```
$theme-colors: (
  primary: $orange,
  secondary: $gray-600,
  success: $green,
  info: $cyan,
  warning: $yellow,
  danger: $red,
  light: $gray-100,
  dark: $gray-800
) !default;
```

We our code is run, the compiler can't find the color variables. We are using Sass 3.4.23 (Selective Steve)

**Comment by DarrenMack-OD** [comment]
This is your code;
```
$blue:    #007bff !default;
$indigo:  #6610f2 !default;
$purple:  #6f42c1 !default;
$pink:    #e83e8c !default;
$red:     #dc3545 !default;
$orange:  #fd7e14 !default;
$yellow:  #ffc107 !default;
$green:   #28a745 !default;
$teal:    #20c997 !default;
$cyan:    #17a2b8 !default;

$colors: (
  blue: $blue,
  indigo: $indigo,
  purple: $purple,
  pink: $pink,
  red: $red,
  orange: $orange,
  yellow: $yellow,
  green: $green,
  teal: $teal,
  cyan: $cyan,
  white: $white,
  gray: $gray-600,
  gray-dark: $gray-800
) !default;

$theme-colors: (
  primary: $blue,
  secondary: $gray-600,
  success: $green,
  info: $cyan,
  warning: $yellow,
  danger: $red,
  light: $gray-100,
  dark: $gray-800
) !default;
```
This is our code, in our themeing file, without the above variables declared, as they are already in _variables.scss;
```
$theme-colors: (
  primary: $orange,
  secondary: $gray-600,
  success: $green,
  info: $cyan,
  warning: $yellow,
  danger: $red,
  light: $gray-100,
  dark: $gray-800
) !default;
```
We our code is run, the compiler can't find the color variables. We are using Sass 3.4.23 (Selective Steve). We have to redeclare the original variables whether we are using them or not :(

**Comment by pat270** [comment]
The color variable names aren't defined because Sass parses top down. The color variables are defined in the bootstrap import, either copy all the color variables above `$theme-colors` or just set:

```
$theme-colors: ( primary: #fd7e14 );
```

**Comment by mdo** [comment]
Demo I provided shows the map merging in action: https://codepen.io/emdeoh/pen/qXxYEO. Could be a Sass version issue?

**Comment by mdo** [comment]
Closing since this was resolved in our codebase.

**Comment by DarrenMack-OD** [comment]
So you are basically saying just redefine your entire theme-colors stack… That is an unusual way to do it :(

**Comment by mdo** [comment]
No, I'm saying we fixed this issue since our beta in our `v4-dev` branch. Pull the latest and try that with your Sass compiler. If it doesn't work still, see if there's a difference in the Sass compilers and we can go from there.

**Comment by DarrenMack-OD** [comment]
Ah, I misunderstood, my apologise, I will try that now ;) Thank you for listening
