### ISSUE TITLE
I just ran npm update/install, a new bootstrap 4 was pulled in and now my navbar has disappeared

### ISSUE THREAD

**Issue by anyadvisor** [twbs/bootstrap#23558]
From Firefox I inspected the element and it says:
```
.collapse {
    display: none;
}
```
It makes no difference what resolution I set my window to

I can roll back obviously, but a bit inconvenient

Edit: Just went back to alpha6, everything is fine again

**Comment by mdo** [comment]
There are breaking changes from v3 to v4, and between every alpha release, and between the last alpha and our current beta. You'll need to migrate your code, or change your npm range to prevent unwanted upgrades from happening.
