### ISSUE TITLE
Broken Links In Website Footer

### ISSUE THREAD

**Issue by Retroity** [twbs/bootstrap#23555]
The Getbootstrap.com website for 4.0 contains 2 broken links in it's footer. The Examples and About links on the footer are broken and lead to 404 pages.

The Examples link should lead to getbootstrap.com/docs/4.0/examples/ but instead links to getbootstrap.com/examples/

The About link should lead to getbootstrap.com/docs/4.0/about/history/ but instead links to getbootstrap.com/about/history/

This occurs on the front page and in the examples page.

**Comment by Johann-S** [comment]
I think it's already fixed in our current code base 🤔 
@XhmikosR

**Comment by XhmikosR** [comment]
Yup. https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=broken%20link
