### ISSUE TITLE
Padding for buttons and inputs

### ISSUE THREAD

**Issue by isychev** [twbs/bootstrap#23550]
Buttons and input inherit the padding from the _$input-btn-padding-x_ and _$input-btn-padding-y_. For _$input-btn-padding-y_ is entirely true, for there is a problem with _$input-btn-padding-x_, y buttons, large side indent and have indented input is much less. Please add to _$input-btn-padding-x_ and _$input-btn-padding-y_ variables **_$input-padding-x_** and **_$input-padding-x_**. Let them be the default

**Comment by prateekgoel** [comment]
Can I work on this?

**Comment by isychev** [comment]
@prateekgoel Of course. Tomorrow send pull request

**Comment by prateekgoel** [comment]
Sure @isychev .
Will submit PR soon.

**Comment by isychev** [comment]
@prateekgoel Hello send  [pull request](https://github.com/twbs/bootstrap/pull/24154)

**Comment by prateekgoel** [comment]
Great @isychev.
But I was already working on this.

**Comment by isychev** [comment]
@prateekgoel send new [pull request #24265 ](https://github.com/twbs/bootstrap/pull/24265)

**Comment by mdo** [comment]
See https://github.com/twbs/bootstrap/pull/24265#issuecomment-337783539 for a preferred approach on doing this.

**Comment by prateekgoel** [comment]
Thanks @mdo. I'll the submit the PR soon.

**Comment by mdo** [comment]
Changes were merged from referenced PR.
