### ISSUE TITLE
dropdown-menu-right works only inside navbars

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [twbs/bootstrap#23553]
dropdown-menu-right doesn't work with pure CSS if you put it outside navbars.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by EdnaldoNeimeg** [comment]
I used this CDNs:
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.[foo]

Here is the pen: https://codepen.io/Neimeg/pen/XaZVyd

**Comment by jipexu** [comment]
hummm ...the dropdown-menu-right seems not exist alone in the css ..?

**Comment by Johann-S** [comment]
Dropdown now depends on Popper.js so the positioning is done by Popper.js that's why you didn't find the CSS

**Comment by jipexu** [comment]
it doesnt work with too ...

**Comment by jipexu** [comment]
>Dropdown now depends on Popper.js so the positioning is done by Popper.js that's why you didn't find the CSS

so why we have those all classes (for each grid step)
 .navbar-expand-sm .navbar-nav .dropdown-menu-right with 

are they still usefull ??

**Comment by Johann-S** [comment]
https://codepen.io/Johann-S/pen/NvyyVr

**Comment by Johann-S** [comment]
We make the choice to disable Popper.js for Dropdown in navbar because we don't have the need

**Comment by jipexu** [comment]
cool 
so @EdnaldoNeimeg 
>dropdown-menu-right doesn't work with pure CSS if you put it outside navbars.

is true

**Comment by Johann-S** [comment]
Yep that's true I'll reopen to let @mdo answer if we should re introduce this CSS class in this particular use case

**Comment by wojtask9** [comment]
Just my thoughts.

Currently dropdown in BS i a little bit chaotic. There is `data-placement` attribute, `.dropdown-menu-right` class and another case for `.navbar`.

With current 'default' BS navbar implementation people can't use popper.js to position dropdown but there are cases when it is very helpful to use popper.js (kebab like menus, notification tips, etc)

I think the best solution is to add other placement from popper.js (top-left, bottom-left, top-right, bottom-right) and introduce placement `static`. 
`static` turns off popper.js and everything relies on BS classes `.dropup, .dropdown, .dropdown-margin-right`. 

Currently .navbar have a lot styles for dropdown so why not move this .dropdown-* classes to dropdown.scss? There is also PR that adds another dropdown class to .navbar https://github.com/twbs/bootstrap/pull/23520 
So moving all dropdown-* classes to dropdown will make BS more flexible.

Of course docs should mention that in navbar dropdown should use 'static' placement.

**Comment by mrlife** [comment]
> Of course docs should mention that in navbar dropdown should use 'static' placement.

This would be helpful. I just realized that if using `.container-fluid` in navbar, `.dropdown-menu-right` puts the dropdown in the right corner just under the navbar instead of right-aligned with the `.nav-item.dropdown`.

**Comment by forrest-akin** [comment]
Bumping this as the [bootstrap docs](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment) don't indicate that `.dropdown-menu-right` only works as a descendant to `.navbar-nav`. Had to dig around in the source to figure it out.

**Comment by ggjersund** [comment]
Can't get it working with the following code utilizing the ng-bootstrap library for Angular:
```
<ul class="navbar-nav ml-auto">
  <li ngbDropdown class="nav-item dropdown">
    <a class="nav-link dropdown-toggle cursor-pointer" id="accountDropdown" ngbDropdownToggle>Min konto</a>
    <div class="dropdown-menu dropdown-menu-right" ngbDropdownMenu aria-labelledby="accountDropdown">
      <a class="dropdown-item cursor-pointer">Item 1</a>
      <a class="dropdown-item cursor-pointer">Item 2</a>
      <a class="dropdown-item cursor-pointer">Item 3</a>
    </div>
  </li>
</ul>
```

**Comment by Johann-S** [comment]
It's written here: https://getbootstrap.com/docs/4.1/components/navbar/#supported-content

BTW there is no decision made here, so Dropdowns depend on Popper.js so if you want align your dropdown to the right, include Popper.js 👍
