### ISSUE TITLE
Can !important be removed from the generic flex-direction classes?

### ISSUE THREAD

**Issue by jdhines** [twbs/bootstrap#23551]
For much of my app, I'm using a _[utility-first](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/)_ approach using Tachyons, but also using Bootstrap 4, both to support `ng-bootstrap` as well as for certain components like navbars.

However, I ran into issues where I have components that use `.flex-column` and `.flex-row` but switch between them depending on screen width by using a custom class `.flex-row-ns` which makes the flex direction row-based on "not small" screens. But the problem is that the Bootstrap 4 classes are marked with `!important` which means my `.flex-row-ns` is overriden.

I considered renaming my custom classes (e.g. `.fx-column`), but those are really the best and most intuitive names. It just seems odd and defeats the purpose of utility classes to have `!important` thrown in all over the place.

**Comment by DaleMckeown** [comment]
It's perfectly reasonable to use `!important` for utility classes.

Can't you use a combination of media queries (for the screen size) and then use `!important` to change the flex direction on your `flex-row-ns` class?

If `flex-row-ns` is defined after the bootstrap utility class, it will win (The last defined `!important` wins).

**Comment by jdhines** [comment]
I'm just trying to avoid littering my CSS with !important since, if classes have low-enough specificity, it shouldn't be necessary, and in this case, only propagates the need for using it more and more.
Why would !important be needed anyway since you only use flex-direction for flex containers, and typically would set the direction for each one. In what case would you need an !important override for that, when simply setting the flex-direction on a nested flex container would be all that's needed?

**Comment by mdo** [comment]
If we remove the `!important` from one utility, we should remove it from them all. However, the majority of people I've asked wanted it to ensure the utility always is prioritized over other CSS.
