### ISSUE TITLE
Toggle mobile view button to see the documentation examples

### ISSUE THREAD

**Issue by salkii** [twbs/bootstrap#23554]
I just want to suggest something i think is helpful, for the examples on bootstrap 4 documentations we need a mobile phone or tablette toggle button to see what will be the example on mobile, now is there just html comment that say the box is 100% width on desktop but on mobile is 50% width, when i want to see what will be happen i resize the browser window but the example i want scroll to top or bottom and i just scroll down to find that example, 
Would you please add toggle mobile button side by side every exemple?
Thank you (edited)

**Comment by patrickhlauke** [comment]
in terms of feasibility, that would likely require each example to be in an `<iframe>`, and scripting to then dynamically change the dimensions of the `<iframe>` (and potentially the zoom level of the embedded document too)

**Comment by jerone** [comment]
I would suggest different buttons for all 5 [responsive breakpoints](https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints).

**Comment by mdo** [comment]
We're not going to do a mobile toggle—the docs are responsive for a reason. We're also definitely not going to add five buttons or options for all the breakpoints. Thanks for the suggestion, though!

**Comment by jerone** [comment]
> the docs are responsive for a reason

Responsible yes, useful no. For example [grid offsetting-columns](https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns), that page is so long that resizing the window scrolls the content out of view very fast, making it almost impossible to see the differences between different breakpoints.

**Comment by salkii** [comment]
Thnak you @mdo for your replay, i dont said that we want button o all the pages and all the breakpoints, there is some example definitely have a toggle button to see it not resize a big mega long page to see what will be on the mobile, you can suggest this feature on github and see what user want, and i am sure 100% any person will love this button.
Bootstrap 4 is a big project not just that a simple website i can just resize the window or see it on my phone to see the change you know Bootstrap not a website it is a mega project.
Thank you.
