### ISSUE TITLE
Extending Bootstrap

### ISSUE THREAD

**Issue by barbu110** [twbs/bootstrap#23564]
Hi guys!

I want to create a website theme based on Bootstrap. How can I extend Bootstrap using the source files (not the generated bundles)?

This theme will essentially use Bootstrap components/layouts but I need to change things like buttons' colors and borders etc. and I need to do this from the `.scss` files.

What do you recommend?

The first thing I would try is cloning the repo and changing Bootstrap itself but I am not sure what to do after that.

**Comment by patrickhlauke** [comment]
I'd suggest asking on Stackoverflow or Slack. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker :)
