### ISSUE TITLE
bootstrap-4-beta navtab inside tabpanel not working - wrong #active removed

### ISSUE THREAD

**Issue by macb74** [twbs/bootstrap#23563]
Having nav-tabs inside a tabpanel does not work no 4-beta. The 'active' class from the first element of the included nav-tabs is removed on switching tab.

4-alpha (and also bootstrap-3) it is working: [https://www.bootply.com/kFfJhLiBYk](https://www.bootply.com/kFfJhLiBYk)

4-beta:
[https://www.bootply.com/rOE6jBm34s](https://www.bootply.com/rOE6jBm34s)
At the top nav-tabs switch from 1st to 2nd - it shows the content of several tabpanels.

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/23087
And will be available in our next release thanks 👍
