### ISSUE TITLE
Can't scroll to bottom in fixed collapsed navbar

### ISSUE THREAD

**Issue by Ghost180195** [twbs/bootstrap#23571]
Link:
https://codepen.io/anon/pen/mMxOPj
Bootstrap version:
Bootstrap 4 (Beta 1)
Os version:
Windows 8.1, Google Chrome (60.0.3112.101)
Android 4.2.2, Opera for Android (42.9.2246.119956)

This problem also appears in Bootstrap 3 (3.3.7)

**Comment by mdo** [comment]
Duplicate of #23374.

**Comment by tmorehouse** [comment]
one option to get around this is to add the following CSS to navbar-collapse.

```css
.navbar-collapse {
  max-height: 280px;
  overflow-y: auto;
}

setting `max-height: 0.9vh` (viewport-height) would be ideal, but not all browsers support `vh` units
