### ISSUE TITLE
Bug in nested tabs. [4.0.0-beta]

### ISSUE THREAD

**Issue by memboc** [twbs/bootstrap#23576]
In nested tabs when switch parent tabs teveral times non-active tabs are showed
https://plnkr.co/edit/UNQUVV?p=preview
![image](https://user-images.githubusercontent.com/7403119/29497996-b9454b64-85fb-11e7-8f6d-bc491b2214a5.png)

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/23087
and will be available in our next release thanks 👍
