### ISSUE TITLE
Suggestion: Add link-* helper classes, just like text-*, to help with setting link colors (e.g., white links on dark background)

### ISSUE THREAD

**Issue by justindocanto** [twbs/bootstrap#23570]
Currently there is a .text-* (e.g., .text-white) helper class for making text a certain color, which has a great use case of making text white on a dark background. 

`<div class="bg-dark text-white">This is white text. Super helpful.</div>`

However, to my knowledge, there is no helper classes to easily make the links within a dark colored background also white. Links default to blue.

`<div class="bg-dark text-white">This is white text. Super helpful. <a href='#'>This link is blue by default. Bummer.</a></div>`

It would be great to have .link-* helper classes to solve this problem

Suggested class names:
.link-primary
.link-secondary
.link-success
.link-danger
.link-warning
.link-info
.link-light
.link-dark

Example use (white text & white link on dark background):
`<div class="bg-dark text-white link-white">This is white text. <a href='#'>This link is white. Awesome!</a></div>`

Example use (white text & warning link):
`<div class="bg-dark text-white link-warning">This is white text. <a href='#'>This link is the same color as warning text, alerts, buttons, borders, etc. Awesome!</a></div>`

**Comment by mdo** [comment]
The text color utilities apply to regular elements and anchors alike—there's no need for a separate set of utilities here. Your example use is also counter to how our utilities work; they don't get applied to a parent to override sub-elements. Apply once to each element only.
