### ISSUE TITLE
Update the documentation page about the new class .navbar-expand

### ISSUE THREAD

**Issue by januszm** [twbs/bootstrap#23573]
This page https://v4-alpha.getbootstrap.com/components/navbar/ still contains documentation about the old class name, `.navbar-toggleable`.

**Comment by jipexu** [comment]
yep but this page is https://v4-alpha.getbootstrap.com/components/navbar/ and in alpha navbar-toggleable was still alive so it's correct...
why not use this one https://getbootstrap.com/docs/4.0/   .....

**Comment by januszm** [comment]
Thanks, my bad
