### ISSUE TITLE
popper.js issues BS4 beta

### ISSUE THREAD

**Issue by MarkDijkstra** [twbs/bootstrap#23574]
So the new BS4 beta has been released but when I download the latest version of popper.js from there website it does not work(it will work with the provided version from the BS download), also is there a way to NOT use popper.js inline styling(why...?)?

**Comment by Johann-S** [comment]
You have to download the `UMD` release of Popper.js 👍 
You can override Popper.js style with custom CSS, but currently they aren't any way to avoid Popper.js inline style

**Comment by jipexu** [comment]
@Johann-S the link you provided is the last popper version who work with beta 4 ??

**Comment by Johann-S** [comment]
I have to make some check but when I read the change log they aren't any breaking change from Popper.js so it should work

**Comment by jipexu** [comment]
thanks i will check too

**Comment by mdo** [comment]
Keep open or close?
