### ISSUE TITLE
Don`t render div with class container

### ISSUE THREAD

**Issue by FireworksX** [twbs/bootstrap#23589]
I write
```html
<div class="container">
            <div class="row">
                <div class="content__avatar"></div>
            </div>
        </div>
```
but in output i get only row without .container

**Comment by XhmikosR** [comment]
How is this related to Bootstrap? You are responsible for the HTML you write...

**Comment by chiraggmodi** [comment]
@FireworksX  can you create a fiddle?
i have create with your code and it is rendering fine. check my  [fiddle](https://jsfiddle.net/d4mqsy4m/)

**Comment by XhmikosR** [comment]
Anyway, this looks like a support question.
