### ISSUE TITLE
Fix jumbotron padding

### ISSUE THREAD

**Issue by bangzek** [twbs/bootstrap#23583]
Please do visual comparison between:
http://getbootstrap.com/docs/4.0/examples/narrow-jumbotron/
and:
https://getbootstrap.com/docs/3.3/examples/jumbotron-narrow/

You would find v4 jumbotron padding is so much longer on the vertical.

On the old v3 the space is 68px on the vertical and 60px on horizontal,
this is because `h1` has 20px _margin-top_.

In the current v4 **the vertical is 64px** (on normal 16px default font size) and **32px on horizontal**.
Probably v4 just copy the older padding proportion but failed to adjust with the removal of all margin-top.

I propose to just make the padding equal, so the end result will be 64px on both.

BTW, the example thumbnails needs updating.

**Comment by mdo** [comment]
Closing as a won't fix.

**Comment by bangzek** [comment]
Could you explain the reason or at least give us the choice to pick the padding we like.

**Comment by mdo** [comment]
You can override an example's source code however you like, and there are spacing utilities for tweaking things further.

**Comment by bangzek** [comment]
Could you consider adding variable to customize jumbotron padding ratio, something along the line `$jumbotron-padding-x` and `$jumbotron-padding-y`?

The example is just to demo the problem. Sorry if it confusing.
