### ISSUE TITLE
Blurry text in Bootstrap dropdown menu

### ISSUE THREAD

**Issue by Sir-Genius** [twbs/bootstrap#23590]
By default popper.js uses the CSS 3d transformation for positioning of dropdown menu. This transform property causes font rendering issues in WebKit-based browsers. It would be nice to add native popper.js option [computeStyle.gpuAcceleration](https://popper.js.org/popper-documentation.html#modifiers..computeStyle.gpuAcceleration) into Bootstrap dropdown plugin to allow users to choose which type of positioning to use.

**Comment by FezVrasta** [comment]
Why you say it causes issues in webkit browsers? It doesn't cause any issue if the 3d transformation doesn't make use of half pixels (Popper.js makes sure to not use half pixels).

May you provide more info about your browser and OS?

**Comment by FezVrasta** [comment]
The pictures have very low quality so they actually look the same to me, any chance to get a CodePen or JSFiddle to reproduce the problem?

**Comment by Sir-Genius** [comment]
Take a look here http://sergius.16mb.com (Google map toolbar). Both _transform_ and _will-change_ affect type rendering.

**Comment by Herst** [comment]
If I see it correctly greyscale anti-aliasing is used in one screenshot while subpixel anti-aliasing is used in the other one.

AFAIR, various browsers can have various reasons for switching to grayscale AA, e.g. transparent background, subpixel positioning, recent repositioning or other transformations, …

**Comment by FezVrasta** [comment]
I don't see anything blurred both on macOS and Windows 10 actually

**Comment by Herst** [comment]
@FezVrasta On high DPI setups you might not notice the difference, because if the pixels are very small it makes no difference whether full or subpixels are used for AA.

**Comment by atomiks** [comment]
@Herst is correct, the "ClearType" Windows uses is being disabled. You need to zoom right in to see the difference in anti-aliasing.

![Before vs after](https://i.gyazo.com/30fec551eb38720935b12229b55378eb.png)

Left = with `transform`, right = without in his screenshots.

**Comment by FezVrasta** [comment]
They are just two different kind of anti aliasing, but neither of them looks blurry

**Comment by Herst** [comment]
> neither of them looks blurry

That is subjective.

**Comment by bardiharborow** [comment]
Ref #21132 from the days of Tether.

**Comment by FezVrasta** [comment]
Still waiting for feedbacks on this:
https://github.com/twbs/bootstrap/issues/23590#issuecomment-323987562

if it works I can fix this on Popper.js side of things.

**Comment by Sir-Genius** [comment]
> May you try to set -webkit-font-smoothing: antialiased; or -webkit-font-smoothing: subpixel-antialiased; to the popper element and see if it helps?

It was the first thing that came to my mind, but unfortunately it doesn't help.

**Comment by atomiks** [comment]
Given this may not be fixable, a `gpuAcceleration` option would help fix this for the affected platforms.

If the device's pixel ratio is below 1.5 and is a Windows device, set the option to false.

```javascript
$('#element').popover({
  gpuAcceleration: !(window.devicePixelRatio < 1.5 && /Win/.test(navigator.platform))
})
```

**Comment by Sahil1111** [comment]
Please have a look to the attached screenshot attached screenshot are from bootstrap 4  main website 

![tempsnip](https://user-images.githubusercontent.com/11404549/43395326-540e3a24-941b-11e8-9c4f-fc6ead3075f0.jpg)
![tempsnip1](https://user-images.githubusercontent.com/11404549/43395327-54407f20-941b-11e8-99ac-845371984601.jpg)

**Comment by XhmikosR** [comment]
Is this still an issue?

**Comment by Sir-Genius** [comment]
No, it is not. Now there is a built-in [option](http://getbootstrap.com/docs/4.1/components/dropdowns/#options) which allows the user to disable Popper.js.

**Comment by oweskeez** [comment]
I'm having this issue with tooltips. How exactly can I resolve this? Disabling popper.js gpu acceleration?

**Comment by FezVrasta** [comment]
You can disable gpu acceleration, right

**Comment by oweskeez** [comment]
@FezVrasta terribly sorry to bother you with such trivial matters, but could you provide a snippet of how to do this? (inside .js file)

**Comment by FezVrasta** [comment]
Actually I don't use Bootstrap anymore (it's been few years already) so I'm not able to help unfortunately.

**Comment by mindswoosh** [comment]
It seems like Chrome is a moving target for this. Following the idea of using `transform`, I got the left-side (grey-scale) of @atomiks example to work using `transform: rotateY(0);`
