### ISSUE TITLE
Question about variable reuse

### ISSUE THREAD

**Issue by joneff** [twbs/bootstrap#23595]
Many components (pagination, cards, dropdown-menu, input, modal, listgroup...) use `$white` for their background. The issue, to me, is that the said components reference it directly and not via another variable, say a new variable `$component-bg` or by referencing `$body-bg` or another suitable variable.

Then there is the matter of `*hover-bg` variable. I've counted 4 distinct background colors: for table, table inverse, for pagination and list-group / dropdown-link. The first two are playing with opacity; pagination uses a shade of gray and list group and dropdown-link both use the same slightly lighter shade of gray.

Then there is the `*border-color` variable, which varies from being `rgba($black, ...)`, trough shades of `$gray-*` variables and then some "hard-coded" to `#ddd`.

With #23748 I am trying to illustrate said variable reuse. Does such approach fit well with the direction Bootstrap is heading?

**Comment by MartijnCuppens** [comment]
Closing this (see https://github.com/twbs/bootstrap/pull/23748#issuecomment-462300416)
