### ISSUE TITLE
Button clipping in navbar with safari

### ISSUE THREAD

**Issue by acacia314** [twbs/bootstrap#23599]
In safari osx and ios, a button on the right of a navbar can be clipped.

See http://jsbin.com/quhocaquti/1/edit?html,output

I was able to resolve by setting flex:none on the .btn

**Comment by mdo** [comment]
Version of macOS and iOS? Of Safari? I see no issues in the upcoming release of Safari (testing High Sierra) on this particular computer, so could be a potentially fixed Safari issue.

**Comment by acacia314** [comment]
Don't see it anymore on my iOS. 

Still seeing the behavior on OSX EL Capitan Version 10.11.6, Safari 9.12.

**Comment by mdo** [comment]
No issue in Safari 11, so closing out as something fixed in an upgrade for them.
