### ISSUE TITLE
.invalid-feedback is displaying block on valid

### ISSUE THREAD

**Issue by bestmomo** [twbs/bootstrap#23592]
I think there is an issue with a rule with **.invalid-feedback** class on valid enter because it is displaying block and it should be not displayed. Easy to check [in documentation](https://getbootstrap.com/docs/4.0/components/forms/#custom-styles).

**Comment by max41479** [comment]
Confirmed. I just typed 123456 in ZIP and submitted, and it says "Please provide a valid zip." with green border.

**Comment by mdo** [comment]
Duplicate of #23372 I believe.
