### ISSUE TITLE
4 beta 1, Buttons disabled transition.

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#23606]
Before 4 beta 1 (with alpha6) disabling button (not using class "disabled", just disabled on tag <button>) had a background-color transition. Now with this 4-beta it doesn't.

Why?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by johnunclesam** [comment]
After some trial I understand. The problem here is a different final css using import in scss.

- 4.0.0-alpha.6: https://plnkr.co/edit/JjcFuveToRLx4hWUMtWC?p=preview

- 4.0.0-beta: https://plnkr.co/edit/LSeKKSaB2Lk2JMtoFi9K?p=preview

You can try in a simple `style.scss` file with both version (alpha6 and beta):

`@import "./node_modules/bootstrap/scss/bootstrap";`

then

`node-sass style.scss style.css`

and you'll have a different css for the .btn class:

**4.0.0-alpha.6**:
```
.btn {
  display: inline-block;
  font-weight: normal;
  line-height: 1.25;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 1rem;
  font-size: 1rem;
  border-radius: 0.25rem;
  transition: all 0.2s ease-in-out;
}
```

**4.0.0-beta**:
```
.btn {
  display: inline-block;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  line-height: 1.25;
  border-radius: 0.25rem;
  transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
```

Look at this:
`transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;`

**This is the problem I was talking about.**

**Comment by mdo** [comment]
Ah, yes, transitioning everything isn't ideal—for perf and unintended visual glitches. Customize if you need it to be different. Closing as a won't fix.

**Comment by johnunclesam** [comment]
Ok dear @mdo, but I don't understand.

In this file linked now on getbootstrap.com page I have this:

`https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css`

```
.btn {
    transition: all .15s ease-in-out
}
```

When I use this code in my app the "disabled" property works good.

If I use Bootstrap@4.0.0-beta with import in scss it doesn't anymore because of the problem above.

I really don't understand. Explain it to me, please.
