### ISSUE TITLE
Border utilities - add "border-x-0" and "border-y-0"?

### ISSUE THREAD

**Issue by phax** [twbs/bootstrap#23602]
It would be great to have "border-x-0" and "border-y-0" CSS classes to complement the existing "no border" styles (as shown on https://getbootstrap.com/docs/4.0/utilities/borders/)

This would also fit with the sizing properties where "x" and "y" are already present.

**Comment by LarryAzevedo** [comment]
Consider taking it a step farther and making the border utilities responsive.  Look at #23892

**Comment by mdo** [comment]
This feels less common and not highly requested, so going to pass on this.
