### ISSUE TITLE
Right aligned dropdown in navbar displays menu outside of window

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#23603]
When a right aligned dropdown menu is set in the navbar, the menu shows outside the screen. Here is an example, just open the dropdown on the right.

https://plnkr.co/edit/VcLlZkT5ipPCuyvnGEMt?p=preview

**Comment by Johann-S** [comment]
Your dropdown do not have the `.dropdown-menu-right`, if you want to align your dropdown at the right please add this class 👍

**Comment by revivemarketing** [comment]
@johan this is not a suitable solution as this just changes the issue of the dropdown overflowing the right side of the screen, to the left side of the screen..

**Comment by unclehooptie** [comment]
@revivemarketing The temporary workaround I am using is adding `.dropstart` to my `.nav-item `div. Have you found a solution?

**Comment by revivemarketing** [comment]
@unclehooptie thank you for the suggestion, I'm sure that will be helpful for someone. Unfortunately, I'm using the dropdown in a button group, so there is no nav-item, and applying it to the btn-group or other elements has no effect. 
Odd that the team hasn't addressed this issue.. viewport awareness/collision is a pretty basic expectation when developing dynamic components like this.
