### ISSUE TITLE
Modal with dynamic content does not close if animation is active

### ISSUE THREAD

**Issue by bluesurfer** [twbs/bootstrap#23604]
I have upgraded to Bootstrap 4 Beta from Alpha 6 and I am using jQuery 3.2.1 to dynamically populate the content of a modal. Here's the JS code inspired from the [docs](https://getbootstrap.com/docs/4.0/components/modal/#varying-modal-content).

```
    var $modal = $('#modal');

    $modal.on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var target = button.data('url');
        if (target) {
            $modal.load(target, function () {
                $modal.find('input:visible:first').focus();
            });
        }
    });
```

And here's the HTML:

```
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal" data-url="/foo">Open modal</button>

<div class="modal" id="modal" tabindex='-1' role="dialog" aria-labelledby="modal" aria-hidden="true"></div>
```

This works fine but if I add the `fade` class then the animation effect works but there's no way to close the modal. I had similar problem with Alpha 6 (see #22906)

**Comment by InvisaMage** [comment]
I have the same problem.

**Comment by Seika85** [comment]
I have the exact same issue. I also had the "Modal is transitioning" Error with Alpha-6.
I don't know if it helps, but I debugged bootstrap itself a bit and found out that `transitionComplete()` is never called and therefor `_isTransitioning` is never reset- even though `transitionEndEmulator()` is called.
I tried adding a callback to its function parameter and added its call to the `setTimout`. Then I just needed to add the respective callback to the call of `emulateTransitionEnd` and it worked.

I don't know if it's "good" what I did, but I hope someone can at least use it to spot the actual issue better than me.

**Comment by bluesurfer** [comment]
@Johann-S @Seika85 @InvisaMage 

At the end I manage to make this work (tested on Beta 2).  Adding `modal-dialog` and changing the event to `shown.bs.modal`did the trick.

```
    <div class="modal fade" id="modal" tabindex='-1' role="dialog" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog" role="document">
        </div>
    </div>
```

```
    // Vary modal content based on trigger button
    $modal.on('shown.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var target = button.data('url');
        if (target) {
            $modal.load(target, function () {
                $modal.find('input:visible:first').focus();
            });
        }
    });
```
And here the target url returns the HTML enclosed in modal-dialog tags.

**Comment by Johann-S** [comment]
@bluesurfer maybe you should update to our beta 2, we made some significant changes to our Modal Plugins and let us know if you still have this issue :+1:

**Comment by Johann-S** [comment]
So is it a fixed issue for you @bluesurfer ?

**Comment by bluesurfer** [comment]
@Johann-S

Seems a hack to me but it works. So, I guess it is fixed? It's up to you :)

**Comment by Johann-S** [comment]
I made a Codepen with our latest release (beta 2) and it works fine see : https://codepen.io/Johann-S/pen/KXOPPj?editors=1010#0

without using `shown` event :wink:

**Comment by ConorSheehan1** [comment]
Looks like this issue or something similar is on the getbootstrap website on the Tooltips and popovers modal. If you go to https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers 
once you open the modal and click ```This button triggers a popover on click.```  
the modal can no longer be closed.  Exception in the console is ```Uncaught Error: Modal is transitioning```

(On Google Chrome 60.0.3112.78, centos 7)

**Comment by Johann-S** [comment]
We are on Beta 3 @ConorSheehan1 so you should update your Bootstrap version 😉

**Comment by bluesurfer** [comment]
@Johann-S 

> I made a Codepen with our latest release (beta 2) and it works fine see : https://codepen.io/Johann-S/pen/KXOPPj?editors=1010#0
> without using shown event 😉

This is slightly different: you are using the `modal-body` element to populate the modal. One, instead, may want to dynamically change the `modal-dialog` in order to control the size of the modal using `modal-sm/md/lg`. And that still does not work with the show event - you cannot close modal once it gets shown (**tested on beta-3**). 

The only thing that seem to work is my hack and I am not using it 😄  (I preferred to disable the fade effect).

**Comment by bluesurfer** [comment]
@Johann-S 

I was looking back to this issue in my project and I think I finally come up with a clean solution using jQuery and data attributes:
```
    let $modal = $('#modal');

    // Vary modal content based on trigger button
    $modal.on('show.bs.modal', (e) => {
        let button = $(e.relatedTarget),
            target = button.data('url'),
            size = button.data('size') || 'modal-md';
        $modal.find('.modal-dialog').addClass(size);
        $modal.find('.modal-content').load(target);
    });
```
So for me this is closed :)

**Comment by habib535** [comment]
In a scenario when you have initially empty HTML and then you fill it with contents as a result of a response or any late binding, the constructor of the modal is called before the contents are available.
```
<div id="infoModal" class="modal fade">
</div>
```

So in my case the modal object `this._dialog` is `null` and when you click the close button it will wait for the transition to end on the `this._dialog` element.
https://github.com/twbs/bootstrap/blob/main/js/src/modal.js#L280

Which will never happen unless you set the `this._dialog` property to proper element.

Adding the following line at https://github.com/twbs/bootstrap/blob/main/js/src/modal.js#L267 fixed my problem
```
      if (!this._dialog && this._element) {
        this._dialog = this._element.querySelector(Selector$5.DIALOG)
      }
```

Of course, changing the library is not ideal but the strange thing is this started happening after we upgraded from version 3.2 to 4.4, fixing it in the library is better than adding hacks. Hopefully, this fix will be available in future releases.

**Comment by mdo** [comment]
Was this safe to close or is this something still to tackle here? /cc @twbs/js-review

**Comment by XhmikosR** [comment]
I'm not sure if this is still valid, but let's leave it open and PRs welcome.

**Comment by alpha1125** [comment]
This is still the case in Bootstrap 4.6.

show a modal, that has class "modal fade",
while it's displaying/animating, try closing the modal $("#myModal").modal('hide'), the modal will not close.

Removing the fade class, the code works fine.

**Comment by mdo** [comment]
Closing as stale for v4.
