### ISSUE TITLE
v4 doc not clearly describe the "optional" js files usage

### ISSUE THREAD

**Issue by SuperWangCC** [twbs/bootstrap#23608]
![_2017-08-22_08-26-55](https://user-images.githubusercontent.com/8223268/29543442-c33e878e-8713-11e7-81d4-12271615318f.png)
OS:Ubuntu 17.10
Browser:Chrome 60.0
Description:
V4 documention seems has a lot thing to upgrade.When i use the dropdown example code block in the doc.
WhenI copy it to my html file.**And click on the dropdown-navbar.It always go to example.com.But didn't show the dropdown menu**
**code:**
`
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
`

**Comment by mdo** [comment]
Did you include jQuery, Popper.js, and our Bootstrap JS?

**Comment by SuperWangCC** [comment]
@mdo oops,now i have debug that I didn't include Popper.js.But in the document,It is said "optional".No clearly marked its usage and function.I think the document should rewrite this part of content.

**Comment by Johann-S** [comment]
It's written in the overview here : https://getbootstrap.com/docs/4.0/components/dropdowns/#overview

**Comment by XhmikosR** [comment]
@mdo @Johann-S Maybe that should be a callout?

**Comment by martinbean** [comment]
I’m struggling to get dropdowns to work on my web pages. I’m using npm with Laravel and have this in my **resources/assets/js/bootstrap.js** file:

```js
window.$ = window.jQuery = require('jquery');

require('popper.js');
require('bootstrap');
```

But drop-downs still aren’t working—clicks aren’t intercepted and the address bar is updated with the link’s `href` attribute value (just an ID selector).

**Comment by Johann-S** [comment]
To allow Bootstrap to use Popper.js you should have a `window.Popper` present

**Comment by martinbean** [comment]
@Johann-S So if I add `window.Popper = require('popper.js')` to my **bootstrap.app** file, I get the following error in the console when clicking a drop-down link:

> Uncaught TypeError: Popper is not a constructor

**Comment by Johann-S** [comment]
Because you do not use the last release of Popper.js `1.12.3`

**Comment by martinbean** [comment]
@Johann-S I have `"popper.js": "^1.12.3"` in my **package.json** file.

**Comment by Johann-S** [comment]
that's strange maybe @FezVrasta have an idea why you still have this issue ?

**Comment by martinbean** [comment]
Fixed. Had to do the following in my **resources/assets/js/bootstrap.js** file:

```js
import Popper from 'popper.js';

window.$ = window.jQuery = require('jquery');
window.Popper = Popper;

require('bootstrap'); // Bootstrap, as in this library
```

**Comment by XhmikosR** [comment]
@Johann-S: what should we do with this issue? Close?

**Comment by Johann-S** [comment]
yep I'll close that issue
