### ISSUE TITLE
:valid & .is-valid on form element does not hide .invalid-feedback

### ISSUE THREAD

**Issue by plexus77** [twbs/bootstrap#23613]
Not sure whether or not this is intended behaviour but the styles below from the form-validation-state mixin will show .invalid-feedback for the :valid and .is-valid states...

`
.was-validated .form-control:valid ~ .invalid-feedback, 
.was-validated .form-control:valid ~ .invalid-tooltip, 
.form-control.is-valid ~ .invalid-feedback, 
.form-control.is-valid ~ .invalid-tooltip, 
.was-validated .custom-select:valid ~ .invalid-feedback, 
.was-validated .custom-select:valid ~ .invalid-tooltip, 
.custom-select.is-valid ~ .invalid-feedback, 
.custom-select.is-valid ~ .invalid-tooltip {
    display: block;
}
`

Shouldn't .invalid-feedback only be visible for the :invalid & .is-invalid states?

**Comment by pat270** [comment]
https://github.com/twbs/bootstrap/pull/23527 should fix this.

**Comment by plexus77** [comment]
Yes that's exactly what I found, have fixed it locally for now.
