### ISSUE TITLE
Incomplete page on the new documentation

### ISSUE THREAD

**Issue by Biuni** [twbs/bootstrap#23636]
I have found this incomplete page http://getbootstrap.com/docs/4.0/extend/ linked by the fourth element on this list https://getbootstrap.com/docs/4.0/migration/#components .

PS: Another problem is the link "card" in the first paragraph. The page returned is 404 because the true link is https://getbootstrap.com/docs/4.0/components/card/ and not https://getbootstrap.com/docs/4.0/components/cards/

**Comment by mdo** [comment]
Duplicate of #23369.
