### ISSUE TITLE
Progress Bar Height Documentation

### ISSUE THREAD

**Issue by ztvMark** [twbs/bootstrap#23630]
Before opening an issue:

- Operating system and version : Ubuntu 16.04
- Browser and version: Chrome 59

The documentation appears like this
https://getbootstrap.com/docs/4.0/components/progress/#height

```
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 25%; height: 1px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>
```

But for small heights the .progress does not automatically change in .progress-bar small

Example
http://imgur.com/a/V9AWA

Add to the documentation height: auto;

```
<div class="progress" style="
    height: auto;
">
 <div class="progress-bar" role="progressbar" style="width: 25%;height: 1px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>

```

**Comment by mdo** [comment]
https://getbootstrap.com/docs/4.0/components/progress/#height
