### ISSUE TITLE
v4 - Modal align vertical center

### ISSUE THREAD

**Issue by marlonmleite** [twbs/bootstrap#23638]
I need to leave my modal aligned to the center of the screen vertically.

I tried with Flex and with Translate, however the 2 solutions cause bizarre behavior in the modal.

Is there any native form of bootstrap v4 doing this or some workround?

Several workround's found have problem when content is large.

**Comment by Johann-S** [comment]
I don't think currently we have a workround on how to that 🤔 but maybe I'm wrong

**Comment by xcartmods** [comment]
https://stackoverflow.com/questions/41377501/how-to-vertically-align-bootstrap-v4-modal-dialogs

**Comment by krystyna93** [comment]
the .modal-dialog-centered does not work! Please explain??

**Comment by marlonmleite** [comment]
@krystyna93 you are using [v4.0.0-beta.3](https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.3) or more?

**Comment by sfgn** [comment]
Was also not working for me on v4.0.0-beta.2, but I've now upgraded to v4.0.0 and working perfectly.

**Comment by krystyna93** [comment]
It seems that I was using an earlier version of Bootstrap 4. My apologies.

**Comment by ChVince** [comment]
According to the [documentation](https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/) IE10+ [is supported](https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#internet-explorer). But class .modal-dialog-centered doesn't work correctly in IE11 (tried with sample [from docs](https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered)  ). As far as I understand it's known flexbox IE11 [issue](https://github.com/philipwalton/flexbugs#flexbug-3), for which [workaround](https://codepen.io/philipwalton/pen/JdvdJE) is available. Are there any known side effects of this workaround ? If no, why it's not included into bootsrap 4.0.0 ?

**Comment by larrybahr** [comment]
I am having the same issue as @ChVince. [IE10+ is supported](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/), but [.modal-dialog-centered](https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered) is not working in IE11. The modal stays near the top of the window just like it does without .modal-dialog-centered.
It is working on the latest versions of Chrome, Firefox, and Edge.
