### ISSUE TITLE
[feature request] Replace a common $spacer variable with $spacer-x and $spacer-y

### ISSUE THREAD

**Issue by wujekbogdan** [twbs/bootstrap#23639]
Before Bootstrap 4 was released I've been using Bootstrap grid for columns and [Sassy Gridlover](https://github.com/hiulit/Sassy-Gridlover) for vertical rhythm. So spacing X-axis spacing was controlled by Bootstrap, and Y-axis spacing was controlled by Sassy Gridlover.

Now, in Bootstrap 4.x we have a `$spacer` variable, so we can control the spacing in both axes with Bootstrap, which is cool. The thing that's not cool is that there's a common variable for vertical and horizontal spacing. 

It would be great if there were 2 variables: one for X and on for X axis.

---
In order not to introduce breaking changes you could do it like this:
``` css
$spacer: $value;
$spacer-x: $spacer;
$spacer-y: $spacer;
```

**Comment by mdo** [comment]
We used to have this and I removed it because it was introducing a set of variables we just weren't making any use of. For now, not going to change that, but you can definitely extend this on your end.
