### ISSUE TITLE
Form invalid message with navbar wrong position (viewport scroll to)

### ISSUE THREAD

**Issue by JDias** [twbs/bootstrap#23631]
Hi,
i did search all i could, and tested as i can (maybe not all the guidelines suggested here, so im not confident, but...)

does this issue still exists?

https://stackoverflow.com/questions/19814673/html5-input-required-scroll-to-input-with-fixed-navbar-on-submit

when you click the submmit button the injured input is out of the viewport, it got scrolled to the element and focus but with the wrong positioning of the invalid message, make the message out of context (as the input is hide by the navbar)

Regards,

**Comment by mdo** [comment]
This isn't a Bootstrap bug—these are browser behaviors and prompts—so closing out.
