### ISSUE TITLE
navbar-brand is cut off on Firefox

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23633]
So this is a weird one.

Using Firefox 56.0b5 64-bit on Windows 7 with a screen resolution of 1920x1206 with 125% DPI I get the navbar-brand cut off. It doesn't happen with Chrome or IE 10. Nor it happens on my main rig with a 4K resolution.

Now, the fix seems pretty simple: change the SVG dimensions to **38x38** or bigger.

**Before:**

![1-before](https://user-images.githubusercontent.com/349621/29607584-57087a42-87fa-11e7-996a-6b2876580c8b.png)

**After:**

![2-after](https://user-images.githubusercontent.com/349621/29607589-5bf219f0-87fa-11e7-9dfc-2389bba32952.png)

So, should I make a PR with this change?

/CC @mdo

**Comment by mdo** [comment]
Prolly need to cut a custom one somehow... looks blurry and pixelated even with the size change. Resizing is the last option in my mind—I've sized all that navbar stuff to work with the button and nav link heights.

**Comment by XhmikosR** [comment]
But it's SVG so it sizes pretty good :S

**Comment by Joyrex** [comment]
@XhmikosR - The fact you are using 125% scaling (which Windows 7 does not do well compared to Windows 10) is why your visuals are being displayed blurry/cut off. I bet if you set your display scaling back to 100%, the top line of the Bootstrap icon reappears. Chrome and IE rendering it properly might have to do with how those browsers work with the host OS to render the pixels in the browser window (just guessing on my part). Firefox may use the default OS renderer (or vice versa, their own custom renderer, again just guessing on my part).

**Comment by XhmikosR** [comment]
Yeah, I came to the same conclusion too after changing the DPI; 150% works OK too. It's my dev VM hence that weird resolution.
