### ISSUE TITLE
Double Scrollbar in modal dialogs in IE11

### ISSUE THREAD

**Issue by iomerCody** [twbs/bootstrap#23644]
When Viewing a modal in IE11 with zoom above 100% a double scrollbar appears(zoom set to 200% in thie screenshot):
![image](https://user-images.githubusercontent.com/25516705/29633871-f1733478-8804-11e7-844c-17265b3681f6.png)
http://getbootstrap.com/docs/3.3/javascript/

It seems to be most apparent when hovering/scrolling over the gray parts.

Windows 10
IE11 11.540.15063.0

**Comment by wolfy1339** [comment]
Is this issue also present in v4?

**Comment by Ghost180195** [comment]
This proble also appears in Microsoft Edge:
![edgebug](https://user-images.githubusercontent.com/31181880/29661431-72b53044-88dd-11e7-8d6f-13667d67a9f2.PNG)

Microsoft Edge version: 25.10586.0.0

**Comment by Ghost180195** [comment]
@wolfy1339 Yes

**Comment by mdo** [comment]
Closing because v3 isn't being worked on.
