### ISSUE TITLE
[Feature request] Improve typography 

### ISSUE THREAD

**Issue by wujekbogdan** [twbs/bootstrap#23640]
Bootstrap 3 had terrible typography. It was impossible to achieve nice spacing (based on the golden ratio, for instance) without additional tools. I've been using the [Gridlover](https://www.gridlover.net/try) tool, then I found [Sassy Gridlover](https://github.com/hiulit/Sassy-Gridlover).

It would be great if such a feature was included in Bootstrap 4. Bootstrap 4 is much more configurable than the previous release... but still, it's not the best tool for nice typography.

So maybe you could merge Sassy Gridlover (or a similar tool) with Bootstrap?

**Comment by mdo** [comment]
Closing as too general of an issue given we have more specific ones with #23053.
