### ISSUE TITLE
getbootstrap.com examples link goes to 404

### ISSUE THREAD

**Issue by AucT** [twbs/bootstrap#23646]
At the bottom of main site (http://getbootstrap.com/) link examples go to 404 not found http://getbootstrap.com/examples/

**Comment by fleumari** [comment]
Should be replaced with this link: http://getbootstrap.com/docs/4.0/examples/

**Comment by chiraggmodi** [comment]
This is corrected in latest version of beta. I think latest git repo is pending to push on live site.

**Comment by mdo** [comment]
Duplicate of #23555.
