### ISSUE TITLE
What happened to the “warning” states in forms?

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap#23643]
In previous versions of Bootstrap, and the version 4 alphas, you were able to apply a “warning” state on form elements like this:

```html
<div class="form-group has-warning">
  <label class="control-label" for="name">Name</label>
  <div class="form-controls">
    <input type="text" name="name" class="form-control" required />
  </div>
  <div class="help-block">Changing your name will change your profile URL.</div>
</div>
```

In the docs for the Bootstrap 4 beta, I now see there’s only classes for `.is-valid` (“success“) and `.is-invalid` (“danger”), and then `.invalid-feedback` for the corresponding message.

I found the warning styles handy, and use them in some of my applications. Are those warning styles now going away in Bootstrap 4?

**Comment by rafalrg** [comment]
**To jest tytuł**

**Comment by rafalrg** [comment]
###### The smallest heading

**Comment by mdo** [comment]
No more warning—we're using native HTML5 form validation now, which only has `valid` and `invalid`.

**Comment by martinbean** [comment]
@mdo Oh. What do you suggest for warning-like styling on form elements now then as my above example?

**Comment by rafalp** [comment]
Talking UX here, your warning is not really feedback to user's imput, its foreword to what will happen if user carries on with feature. As such it should imho be communicated as either help text, or proceeding inputs with lead copy or always-present alert informing user of consequences.

Perhaps text-warning on text-help should do the trick?

**Comment by martinbean** [comment]
@rafalp I some times use the warning state after input though, i.e. in another application if a user’s typed an all-uppercase headline for a news article, I applied the warning state and a message advising them to use titlecase instead.

**Comment by mdo** [comment]
You can use the mixin to generate your own states, though you might want to modify it since we're making use of the `:valid`/`:invalid` pseudo classes from the HTML5 form validation APIs. Using the mixins, you'll get broken CSS with an invalid `:warning` pseudo-class.

**Comment by klebinhopk** [comment]
@martinbean Did you get any solution for this problem?
Can you share with us if you succeeded?

**Comment by martinbean** [comment]
@klebinhopk No. As @mdo says above, these styles were removed. You’ll have to write your own styles for a warning state.
