### ISSUE TITLE
Background color on card styles with list groups get overriden

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#23648]
The `.list-group-item` class sets the `background-color` property which overrides the property declared by the `.bg-warning` class.

```html
  <div class="card text-white bg-warning mb-3">
    <div class="card-header">Card header</div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Item 1</li>
      <li class="list-group-item">Item 2</li>
      <li class="list-group-item">Item 3</li>
    </ul>
  </div>
```

Test case, see:
https://jsbin.com/tuqerepobe/edit?html,output

**Comment by xcartmods** [comment]
Instead, use .text-white on .card-header

<div class="card bg-warning mb-3">
    <div class="card-header text-white">Card header</div>

**Comment by mdo** [comment]
Yes, it is. You'd have to repeat the backgrounds on those elements given the list group has it's own `background-color`.
