### ISSUE TITLE
Form Validators missing in Beta css file

### ISSUE THREAD

**Issue by patelarpan06** [twbs/bootstrap#23641]
After doing some research, it seems that .has-feedback is the only validator that has made it to v4 Beta for Bootstrap. All the other validators were included up until v4 Alpha 6.

Could you please include the other "has" validators in Beta version as well?

**Comment by Johann-S** [comment]
The has validator have been changed you should follow what the new documentation said : https://getbootstrap.com/docs/4.0/components/forms/#validation
