### ISSUE TITLE
Swiper dont work if I include popper

### ISSUE THREAD

**Issue by lucasthibau** [twbs/bootstrap#23651]
If i Include the popper js in bootstrap 4.0 beta, the swiper js stop working. But if i remove the popper, i get a warning.
I should be oppening this in the popper git?

**Comment by danijelGombac** [comment]
Did you mean nolimits4web/Swiper?
Because i'm using both swiper js and popper js together without any problem.

**Comment by lucasthibau** [comment]
I changed to the CDN version and it worked like a charm, dont know what was happening...
