### ISSUE TITLE
Add a heatmap to a chord diagram

### ISSUE THREAD

**Issue by ilovecheez1** [twbs/bootstrap#23653]
I need help figuring out how to add a color bar to a chord diagram I have made. I would like to add a color bar such as in a heat map: ![heat map](https://plot.ly/~PythonPlotBot/833.png) but in a chord diagram: ![chord diagram](https://i.stack.imgur.com/w39s0.png)This is not to be confused with a filled chord diagram in python plotly. 

Here are their tutorials: [Heat Map](https://plot.ly/python/heatmaps), [Chord Diagram](https://plot.ly/python/chord-diagram), [Filled Chord Diagram](https://plot.ly/python/filled-chord-diagram)

The way in which I plan to use the heat map is to have each line on the chord diagram be a certain color based on the data. For example, if the data says the line has a value of 80, it would be red like in the heat map. If the data said 50, it would be an orange-ish yellow, like in the heat map.

Thank you so much!

**Comment by mdo** [comment]
Don't think we can help you with that here. 😁
