### ISSUE TITLE
Nav tabs javascript messes up when using active class in tab-pane

### ISSUE THREAD

**Issue by Owumaro** [twbs/bootstrap#23667]
Hi,

I'm using bootstrap 4 beta with Chrome Version 59.0.3071.115.

Here is the issue: when using bootstrap nav tabs with automatic javascript activation, using the class "active" inside a tab-pane content breaks the tab show/hide feature.

Here is a demo:
https://gist.github.com/anonymous/9f06df4f5d02a8512c4edbbfca9b7c84
https://output.jsbin.com/hujudepuda

Steps to reproduce:
- When loaded, "Home" tab is showing
- Click on "Profile", home tab is hidden and profile tab is shown
- Now click "Other": other tab is shown, but profile tab isn't hidden

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/23087
and will be available in our next release thanks 👍

**Comment by isneezy** [comment]
I've found it too!
Here is a workaround until the release of beta2
```js
// work arount to fix navtabs issue https://github.com/twbs/bootstrap/issues/23667
$('a[data-toggle="tab"]').click(function(){
    // todo remove snippet on bootstrap v4
    $('a[data-toggle="tab"]').click(function() {
      $($(this).attr('href')).show().addClass('show active').siblings().hide();
    })
 });
```
