### ISSUE TITLE
Duplicate text with component list-group

### ISSUE THREAD

**Issue by fabien91** [twbs/bootstrap#23660]
Hi,

I see that possible to "duplicate" text with list-group and radio.
Look here : https://www.codeply.com/go/v3jktzrNId
On the first page load, just click on "Profile" then "Home", you can see the Profile text in the Home.

I have Windows 10 Pro with Chrome Version 60.0.3112.101 (Build officiel) (64 bits)

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/23087
and will be available in our next release thanks 👍
