### ISSUE TITLE
The badges in the list-group example in docs are not visible

### ISSUE THREAD

**Issue by valexiev** [twbs/bootstrap#23678]
In the example here https://getbootstrap.com/docs/4.0/components/list-group/#with-badges the badges are not visible.
The example uses .badge-default class, but there is no such class for badges.
In branch b4-dev the example uses correct class .badge-primary.

**Comment by gijsbotje** [comment]
already fixed on the v4 dev branch, (`badge-default` has been changed to `badge-primary`)

**Comment by Johann-S** [comment]
Closed thanks to @gijsbotje 👍
