### ISSUE TITLE
Modal jumps position when the viewport is resized

### ISSUE THREAD

**Issue by techdavid** [twbs/bootstrap#23672]
Demo: https://jsfiddle.net/techdavid/g89ts0rs/2/

When the viewport is adjusted, the modal gets a margin applied to it, making it jump position slightly to the left (once only).

For the problem to occur, the main page content needs to overflow but not the modal. `_adjustDialog()` should be called when the modal opens initially so that this doesn't occur.

**Comment by Johann-S** [comment]
I'm sorry @techdavid but I don't see any issue in your jsfiddle, maybe I don't look where I should 🤔 
What should I do to see your this issue ?

I tried to resize my browser's window and check if they are a margin applied but that wasn't the case

**Comment by ddvorak** [comment]
@Johann-S if you resize the view of the html output in the bottom right corner, after clicking the modal, it does hop left a little.

**Comment by techdavid** [comment]
As @ddvorak said. For the problem to occur the preview pane needs to be small enough for the lorem ipsum text to overflow, but large enough for the entire modal to fit, and then it needs to be resized in height.

**Comment by techdavid** [comment]
So just to clarify you can resize the preview pane in JSFiddle by dragging the bar between the CSS pane and the preview pane - sorry if you already know this! (I suppose you're more familiar with JSBin since that's what was suggested for making demos in the issue template).

**Comment by Johann-S** [comment]
Ok so it's the `padding-right` applied when the scrollbar appeared, that's it ?
Sorry just want to be sure I fully understand this issue 😅

**Comment by techdavid** [comment]
Not exactly... here's a video: https://www.useloom.com/share/efa1bc8aa6ce4215807bbeb830b0aa9c
