### ISSUE TITLE
Add a d-<breakpoint>-initial to reset the display when using d-<breakpoint>-none

### ISSUE THREAD

**Issue by IvaWonderbush** [twbs/bootstrap#23670]
I suggest a `d-<breakpoint>-initial` class to override the `d-<breakpoint>-none`

The reason for this is that certain content on a page may have a dynamic `display` style. You can no longer hide these elements and display them again on certain breakpoints without knowing their initial display.

Use case: A client adds content to a page via a page builder, selects the `d-xs-none` yet doesn't want to hide it on `lg` and up, but content may be a table, block, inline-block - no one knows - so to solve every display case you can use `d-lg-initial`

**Comment by mdo** [comment]
Worth noting IE11 has no support for it: http://caniuse.com/#feat=css-initial-value

**Comment by IvaWonderbush** [comment]
@mdo Hm, I didn't even think of checking because I thought it would be one thing IE11 should have. Seems I was wrong. Any other solution to this problem?

**Comment by mdo** [comment]
None until IE supports it :). Closing out for now.
