### ISSUE TITLE
[v4b, modal, bug] Right padding added even if there is no scroll bar to hide

### ISSUE THREAD

**Issue by zorgoz** [twbs/bootstrap#23681]
Even if there is no scroll bar on body element to be hidden, an extra right padding is added when the dialog is shown. Look at the gap that appears between the green bar and the red rectangle in the reduced test case.

Environment:
- Windows 2016 x64
- Chrome 60.0.3112.101
- Reduced test case: https://jsbin.com/hurotibesi/edit?html,output

**Comment by techdavid** [comment]
The body width is detected via `document.body.clientWidth` (in the `_checkScrollbar` function). However, this doesn't account for if the body has margins (usually it doesn't) - a more accurate way of detecting the width is as follows:

    const rect= document.body.getBoundingClientRect();
    this._isBodyOverflowing = (rect.left + rect.right) < window.innerWidth;

**Comment by Johann-S** [comment]
If you want on a fix @techdavid do not hesitate 😄

**Comment by zorgoz** [comment]
I have put the margin to make it more visible. Ths issue is the same without margin.

**Comment by techdavid** [comment]
@Johann-S Just working on it now! The fix itself is simple, writing a proper test is the harder part...

**Comment by techdavid** [comment]
@Johann-S Something strange is going on... I wrote test, ran it in Chrome and PhantomJS (via js-test) before the fix and as expected, the new test fails. After implementing the fix, the tests all work fine in Chrome but 8 now fail in Phantom. So I thought, Phantom must have a buggy implementation of `getBoundingClientRect`, and tried the following instead:

    this._isBodyOverflowing = $('body').outerWidth(true) < window.innerWidth;

But for some reason, the same 8 tests fail in PhantomJS, despite outerWidth using a different method to detect width (as far as I'm aware - need to confirm this). And again, all tests pass in Chrome. Thoughts?

**Comment by Johann-S** [comment]
Maybe if you submit a PR I'll have thoughts ☺️ and if it's isn't possible to test that with Phantomjs a visual test would be a solution

**Comment by harishgadiya** [comment]
@zorgoz, I have checked your JS Bin link, Its happening because you have added margin and border in your body tag

**Comment by zorgoz** [comment]
@harishgadiya, good catch, seems that border is enough to fool it...
