### ISSUE TITLE
Run docs-github in Travis too

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23689]
This was broken for months and no one noticed, or maybe @mdo noticed but forgot to mention it :P

**Comment by bardiharborow** [comment]
Not running it in Travis was the original intended behaviour, as it's a rarely used code path and our builds are already slow, but you're welcome to hook it up if you want.

**Comment by XhmikosR** [comment]
The wrong intended behavior though. Something that is not tested will break without us knowing.

**Comment by mdo** [comment]
> maybe @mdo noticed but forgot to mention it :P

As @bardiharborow mentioned, I don't ever recall us compiling the docs for CI.

**Comment by XhmikosR** [comment]
Closing this for now.
