### ISSUE TITLE
Modal is just not working

### ISSUE THREAD

**Issue by Ashwin117** [twbs/bootstrap#23682]
I think the modal is broken. I've tried to re-use the example modal code in the docs, but I get no errors and nothing.
http://jsfiddle.net/x1hphsvb/101/

Please tell me what I'm missing or what needs to be done?

**Comment by Johann-S** [comment]
Bootstrap depend on jQuery so you should include jQuery before Bootstrap and your jsfiddle use the Alpha 2 but we are in Beta 1, so IMO you should use the latest release 👍 

I hope I helped you for other questions about how to use Bootstrap please use StackOverflow or our Slack channel. [See our readme for more details](https://github.com/twbs/bootstrap#community).

**Comment by Ashwin117** [comment]
Forgive me, but I forgot to save it properly. The JS fiddle is 
http://jsfiddle.net/x1hphsvb/102/

Which uses bootstrap 4. It still doesn't work. Why would I need JQuery here? The documentation doesn't have Jquery to get the modals working.

**Comment by patrickhlauke** [comment]
> Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)

**Comment by Ashwin117** [comment]
Even after adding "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" to the JSFiddle, it doesn't work..

**Comment by Johann-S** [comment]
Bootstrap plugins are built on jQuery see : https://getbootstrap.com/docs/4.0/getting-started/javascript/

**Comment by Ashwin117** [comment]
Ah ok, looks like it started working after including the relevant popper file. Thanks.
