### ISSUE TITLE
Text link doesn't get styled when using color schemes for navbar

### ISSUE THREAD

**Issue by sebask** [twbs/bootstrap#23693]
I am not sure if this actual a bug, or expected behaviour, but I think this might be worth changing.

**Expected behaviour:**
When I use certain color schemes (background) in combination with a navbar, while using text, while using plain links.
I expect the link to be colored in a way it's readable, thus enough contrast. Just like the text is readable.
<img width="1152" alt="screen shot 2017-08-26 at 18 29 18" src="https://user-images.githubusercontent.com/2178774/29743192-b773044e-8a8c-11e7-9d5d-bcb8e6227cd9.png">

**Actual behaviour:**
When I use certain color schemes (background) in combination with a navbar, while using text, while using plain links. 
The links do not get colored (with enough contrast). Rendering it unreadable while using it in combination with certain background color schemes.

```html
<div class="navbar navbar-expand navbar-dark bg-primary">
  <span class="navbar-text mx-auto">
    <small>We gebruiken cookies om de site te analyseren, te verbeteren en voor tracking doeleinden. Als je de website blijft gebruiken gaan we ervan uit dat je dat goed vindt. <a href="#">Lees Meer</a></small>
  </span>
</div>
```
<img width="1152" alt="screen shot 2017-08-26 at 18 15 54" src="https://user-images.githubusercontent.com/2178774/29743147-09332652-8a8c-11e7-8a4e-6a5b99a0f429.png"><img width="1151" alt="screen shot 2017-08-26 at 18 18 15" src="https://user-images.githubusercontent.com/2178774/29743146-093305e6-8a8c-11e7-90f8-9f0489d0e056.png">

I understand I can solve it by adding a color scheme to the link (i.e.: `<a class="text-light" href="#">Lees Meer</a>`). But I think it should work without it.

**Comment by andresgalante** [comment]
Hi @sebask I think this is a bug more than an enhancement. I agree that even though you can add a utility class to change the color of the link, it'd be better to have it work by default.

If you are ok with it I can send a PR to fix it.

**Comment by sebask** [comment]
@andresgalante Of course! :)

**Comment by andresgalante** [comment]
@saas786 Awesome, I've also changed the color of the light theme to be dark black instead of blue, that way it works with any color theme.

Thanks a lot for reporting it.
