### ISSUE TITLE
Feature Request: text-light & text-dark as transparent

### ISSUE THREAD

**Issue by Superpencil** [twbs/bootstrap#23696]
1. `text-dark` and `text-light` are classes used to make sure the text differentiates when we apply a special background.
2. As text is usually already black, and we have a `text-white` class for pure white, the current behavior doesn't add functionality
3. If `text-light` and `text-dark` were instead based on `rgba(255,255,255,.5)` and `rgba(0,0,0,.5)`, they would better represent their name; lightness and darkness

Current:
<img width="338" alt="screen shot 2017-08-27 at 3 18 39 pm" src="https://user-images.githubusercontent.com/3094044/29747609-2f6baf42-8b3b-11e7-8f93-486661bdb322.png"><img width="333" alt="screen shot 2017-08-27 at 3 23 28 pm" src="https://user-images.githubusercontent.com/3094044/29747637-cfc87664-8b3b-11e7-8c0c-c4b93de44edc.png">

Suggested:
<img width="337" alt="screen shot 2017-08-27 at 3 19 37 pm" src="https://user-images.githubusercontent.com/3094044/29747611-33a756a6-8b3b-11e7-8333-26a5587a2b44.png"><img width="334" alt="screen shot 2017-08-27 at 3 24 13 pm" src="https://user-images.githubusercontent.com/3094044/29747639-d34b99ce-8b3b-11e7-850b-d48ff4689878.png">

**Comment by mdo** [comment]
PR would be great! :)
