### ISSUE TITLE
P tag contents can not be wrapped When content too much

### ISSUE THREAD

**Issue by HelTi** [twbs/bootstrap#23698]
P tag can not be wrapped for too many content, only one line can be displayed
pc and phone
v4.beat
pc:
![bug](http://www.itcaca.com/static/img/b.png)
mobile
![bug](http://www.itcaca.com/static/img/bp.png)
code:
```
<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-6" id="aa">
            touch me
        </div>
        <div class="col-md-6 col-sm-6" id="bb">
            touch mepppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
        </div>
    </div>
    <div class="row">

        <p>
        pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
        </p>

    </div>
</div>
```
[jsbin](https://jsbin.com/diboziqupe/edit?html,output)

**Comment by HelTi** [comment]
I use the style:
```
       word-wrap: break-word;
        word-break: normal;
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by HelTi** [comment]
@Johann-S  OK,  I submit the jsbin code。。。

**Comment by jipexu** [comment]
Hi
some notice
1 : you load ONLY the grid.css  ...
2 the direct children class of row must be col ...

but according to your html and after load (bootstrap.min.css) in the both case you can add text-truncate class in the div and in the p

**Comment by HelTi** [comment]
@jipexu no, load bootstrap.css And that's the same

**Comment by jipexu** [comment]
>but according to your html and after load (bootstrap.min.css) in the both case you can add text-truncate class in the div and in the p

with this 
this work for me in your js bin

**Comment by HelTi** [comment]
@jipexu  i dont't load js
not p tag,all tag,like h tag, and you write text, can not wrap
we know default line feed in html.  i think bootstrap resulting in the text can not be wrapped

**Comment by mdo** [comment]
I think this is safe to close?
