### ISSUE TITLE
Alert - add .alert-icon container class to style icons within alerts easily

### ISSUE THREAD

**Issue by lakhman** [twbs/bootstrap#23692]
Could we add an `alert-icon` class which can be applied to icons inside an alert to style them (provide a fixed width).

JSFiddle: https://jsfiddle.net/koeg9d5q/

I can do this view the grid system like below, but I wanted to remove all the rows and cols if possible to clean up the HTML.

``` html
<!-- Using grids - View the jsfiddle: https://jsfiddle.net/koeg9d5q/ -->
<div class="alert alert-success" role="alert">
    <div class="row">
        <div class="col-1 alert-icon-col">
            <span class="fa fa-check fa-fw"></span>
        </div>
        <div class="col">
            <strong>Well done!</strong> You successfully read this important alert message.<br/> 
            Which spans multiple lines.
        </div>
    </div>
</div>
```
```css
/** CSS for above - Force the width for icons */
.alert .alert-icon-col {
    min-width: 25px;
    max-width: 25px;
}
```

Can we do this via BS4 CSS so the HTML looks cleaner - something like below, remove the rows and cols, and wrap the icon in a ``div.alert-icon`` which is styled by BS4.

``` html
<div class="alert alert-success" role="alert">
    <div class="alert-icon">
        <span class="fa fa-check fa-fw"></span>
    </div>
    <strong>Well done!</strong> You successfully read this important alert message.<br/> 
    Which spans multiple lines.
</div>
```

Would be great to have this out the box with BS4, the CSS would be minimal but would make alerts and icons easier to work with together.

Screenshot below, View the JSFiddle here: https://jsfiddle.net/koeg9d5q/

![screen shot 2017-08-26 at 17 13 26](https://user-images.githubusercontent.com/1582690/29743061-f38a9f6a-8a81-11e7-9395-43a99975c5ce.png)

**Comment by mdo** [comment]
No plans to add this ourselves as we have no icons in Bootstrap 4. Will keep in mind for the future though.

**Comment by CesarD** [comment]
For anyone coming here like I did, I found this answer on SO that did the trick for me without any custom CSS: https://stackoverflow.com/a/54038671

**Comment by MLDMoritz** [comment]
We now have icons, can we have alert-icon container now? :-)
