### ISSUE TITLE
div not support in row class

### ISSUE THREAD

**Issue by mofizul21** [twbs/bootstrap#23699]
It is my code, It's BootStrap4 version

```
<div class="container">
	<div class="row">
		<div class="somet">
			<div class="col-md-4">
				<h1 style="background: red">Col 1</h1>
			</div>
			<div class="col-md-4">
				<h1 style="background: red">Col 1</h1>
			</div>
			<div class="col-md-4">
				<h1 style="background: red">Col 1</h1>
			</div>
		</div>
	</div>
</div>
```

When I run the code I see http://prntscr.com/gdjfua it's not what I want. But when I remove **somet** class, then working fine. Has there anyway to use **div class** into **row** class ?

**Comment by gijsbotje** [comment]
you could use the class col on somet and then nest the other columns in another row

**Comment by mofizul21** [comment]
Can you give me an example code, please?

**Comment by andresgalante** [comment]
The problem is the `<div class="somet">` because `.row` flexes the items inside.

Use the grid wisely 😄 (and don't add extra markup)

**Comment by Sir-Genius** [comment]
From the documentation: 

> Content should be placed within columns, and only columns may be immediate children of rows.

Example:
```
<div class="container">
  <div class="row">
    <div class="col">
      <div class="row somet">
        <div class="col-md-4">...</div>
        <div class="col-md-4">...</div>
        <div class="col-md-4">...</div>
      </div>
    </div>
  </div>
</div>
```

**Comment by mdo** [comment]
As folks have mentioned, your markup is incorrect. Read the how it works section of the grid docs: https://getbootstrap.com/docs/4.0/layout/grid/#how-it-works.
