### ISSUE TITLE
Safari search navbar cut

### ISSUE THREAD

**Issue by FrenchMajesty** [twbs/bootstrap#23707]
I am using Bootstrap 4 with bootstrap-typeahead plugin and on Safari I'm having a weird issue.
When I type into the field, I get something like this:

![screen shot 2017-08-25 at 1 55 25 pm](https://user-images.githubusercontent.com/24761660/29752528-82c27dbc-8b25-11e7-9518-1f9ddd0113b1.png)

I messed around for a long time trying to figure out if the problem was with the plugin but its not. I am using the typeahead plugin on multiple fields and the issue appears in none of them. I tried resizing the navbar but it still get cuts the same amount of pixels below it. I also tested in other browsers and this issue does not appear.

You can test it here: http://design-by-verdi.com/demo/beta/public/

- System: Mac OS X 10.11.6
- Safari: 10.1.2, Chrome:60.0.3112.101 , Firefox: 55.0.3

**Comment by andresgalante** [comment]
I couldn't really debug your code since it seems messy, but I am sure you have a z-index and position problem. 

It's definitely not a bootstrap issue.

**Comment by FrenchMajesty** [comment]
But if it is a programming mistake then the problem should be seen across
the board, not just on Safari.

Sincerely,

-Verdi

**Comment by mdo** [comment]
We don't maintain the typeahead plugin—you'll likely need to talk to them first.
