### ISSUE TITLE
safari causes navbar brand to push navbar toggle to be pushed down in mobile view

### ISSUE THREAD

**Issue by ailisg** [twbs/bootstrap#23705]
Using Safari 10.1.2, bootstrap 4 on mac running Mac OS Sierra 10.12.6.
This is not an issue on chrome or firefox but in safari my toggle navbar is not displayed inline with my navbar brand when I shrink the viewport down and activate the toggle. I've seen posts that seem to be mentioning this bug but they're from years ago, usually referencing safari v7 and without apparent solutions. 
I have css applied at higher breakpoints that gives the nav items (UL) a left margin so that the menu is spaced the way I want it, but the original UL without a breakpoint I've applied margin:0.
Issue can be seen in this bootply: https://www.bootply.com/qlBBAGHYvU
(not sure why toggle nav is invisible, I changed the colors of the navbar background to be darker to show text but it's located just to the left of the right side of the viewport, just under the black bar of the navbar)

**Comment by mdo** [comment]
Your code is out of date with latest v4 Beta—please try that and report back.

**Comment by ailisg** [comment]
@mdo Sorry, could you explain what you mean? like what part is out of date? but also I'm using v4-alpha

**Comment by jgacuca567** [comment]
@ailisg Your current version is `v4alpha`, change your version to `v4beta` as it is the current version.

**Comment by ailisg** [comment]
@jgacuca567  thank you! I took a look into it and realized that beta is the most current (I didn't know the difference before, and learned from a lynda tutorial which used alpha). I am in the process of updating now, but what classes do I need to change on my nav to make it work with v4beta? when I just switch the css the nav disappears, but looking at the documentation on bootstrap's site I can't see any differences between my nav and their example navs. Thanks!

**Comment by jgacuca567** [comment]
@ailisg From https://getbootstrap.com/docs/4.0/components/navbar/ copy the examples on your page and change the menu items from there. That should be much easier and guaranteed that the navbar works.
