### ISSUE TITLE
tab.js active state stuck

### ISSUE THREAD

**Issue by DannyJoris** [twbs/bootstrap#23708]
2 of the 4 tab.js examples aren't working for me. In the "nav" example the items in the dropdown stay active and can't be accessed again after clicking way. Same goes for all the items in the vertical tabs: https://codepen.io/DannyJoris/pen/MvqMEW

At first I thought maybe there's a bug in the provided code snippets, but the bugs persist even when I copy the markup of the working example using the inspector tool. It does work when using Bootstrap 3.3.7: https://codepen.io/DannyJoris/pen/VzEZmw, so I'm thinking it may be a bug?

The snippets are taken from: https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior . I just added numbers to the content.

These are the included CDN files:

CSS:

- https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css

JavaScript:

- https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js
- https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js
- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.8/popper.min.js
- https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js

Tested on macOS 10.12.6, Chrome 60 & Firefox 55

**Comment by kuofp** [comment]
It seems good in beta version.
https://codepen.io/anon/pen/KvGdvL

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/23087
Will be available in our next release 👍

**Comment by DannyJoris** [comment]
Oh perfect, thank you!

**Comment by browner12** [comment]
yah, this worked in alpha all the way up to 6, and then beta 1 caused the issue when you have nested tabs.
