### ISSUE TITLE
form controls not aligned when using sm size modifier

### ISSUE THREAD

**Issue by hjalmers** [twbs/bootstrap#23713]
Since the beta release horizontal forms aren't aligned (labels and inputs) when using sm class.

Bootstrap 4 beta
https://run.plnkr.co/plunks/MfUsegsN0r7kgfvkKKzh/

Bootstrap 4 alpha.6
https://run.plnkr.co/plunks/nSYKZ417hxbeNWSnqRbx/

**Comment by wojtask9** [comment]
duplicate of https://github.com/twbs/bootstrap/issues/23447

This PR #23121 should fix issue with .col-form-label
