### ISSUE TITLE
Bootstrap modal is not opening in Chrome only

### ISSUE THREAD

**Issue by msavov** [twbs/bootstrap#23711]
I'm working on a site, and I have a problem with the bootstrap modal only in Chrome. Site is: http://cultureastrology.com/zodiac-signs/ and you need scroll to bottom and click 'About'.

Modal works in Firefox and also in Chrome private mode which is weird. Is there anyone with the same issue? Or is there anything wrong on that site?

**Comment by patrickhlauke** [comment]
For help with your specific use of Bootstrap, I'd suggest using Stackoverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by fdrcslv** [comment]
Hi @msavov @patrickhlauke, I had the same problem: modal working everywhere except Chrome, regardless of its version. I've found that certain browser extensions enter in conflict with bootstrap modals for some reason.
Try removing or deactivating them.

I've also visited the website you've linked, and it works.

Hope this helps!
