### ISSUE TITLE
Add possibility to hide Dropdown Toggle Caret

### ISSUE THREAD

**Issue by jackmu95** [twbs/bootstrap#23724]
I recently stumbled across the problem that there is no "out-of-the-box" way to hide the dropdown toggles caret which gets added by default.

This would be handy for situations like this where you want to provide additional actions behind a "..."-button:
https://codepen.io/jackmu95/pen/jLeRdM

A good and easy solution for me would be to add a `dropdown-toggle-no-caret` class to the dropdown toggle:
```html
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle dropdown-toggle-no-caret" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    ...
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
```

```sass
// scss/_dropdown.scss

.dropdown-toggle:not(.dropdown-toggle-no-caret) {
  ...
}

.dropup {
  ...

  .dropdown-toggle:not(.dropdown-toggle-no-caret) {
    ...
  }
}
```

**Comment by wojtask9** [comment]
You can remove class `.dropdown-toggle` from your button.

**Comment by jackmu95** [comment]
@wojtask9 Thats right. All the dropdown actions are bound on the `data-toggle="dropdown"` attribute. But I'am still not sure this is the best way to go.

**Comment by mdo** [comment]
There's a PR I liked to address this with a Sass variable. Would that suffice? See #22926.

**Comment by jackmu95** [comment]
@mdo The PR looks good to me but it doesn't really solve my problem completely. It does only offer a global on/off switch for the caret but no option to disable it on a per dropdown level.

**Comment by wojtask9** [comment]
@jackmu95 
According to your `_dropdown.scss` changes you want remove caret if you add `.dropdown-toggle-no-carret`. For me is the same if you remove `.dropdown-toggle`.
I don't see why you need `.dropdown-toggle`.
Similar situation. You want `.bg-primary` background-color only if element don't have `.bg-no-bg`.
It easier if you simply remove `.bg-primary`.
Can you explain why you need `.dropdown-toggle`?

**Comment by wojtask9** [comment]
@bkdotcom 
He wrote: `This would be handy for situations like this where you want to provide additional actions behind a "..."-button:
https://codepen.io/jackmu95/pen/jLeRdM"`

So probably `scrollspy.js` and `tab.js` isn't a case.

Simple fix for this issue
```
.dropdown-toggle-no-carret::after {
  display:none;
}
```

**Comment by mdo** [comment]
Global on/off is the best I can do with v4. Closing out as a won't fix (but we'll plan on merging that global option).

**Comment by fafournier** [comment]
Just for information and to eventually weigh in, removing .dropdown-toggle in a .btn-group makes corner rounding issues.

Using the example from https://getbootstrap.com/docs/4.0/components/button-group/ but without 'dropdown-toggle'

<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <button type="button" class="btn btn-secondary">1</button>
  <button type="button" class="btn btn-secondary">2</button>

  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <a class="dropdown-item" href="#">Dropdown link</a>
      <a class="dropdown-item" href="#">Dropdown link</a>
    </div>
  </div>
</div>

**Comment by dark-swordsman** [comment]
As @fafournier mentioned, it does cause rounding issues like this:

![image](https://user-images.githubusercontent.com/7909209/54475869-06d4fc00-47cd-11e9-9dfc-3163b339aee4.png)

**Comment by DaleyKD** [comment]
This would be a nice thing to have.  A simple extra CSS class would be cool.
