### ISSUE TITLE
Spacing: Scaling unit values

### ISSUE THREAD

**Issue by jsonUK** [twbs/bootstrap#23729]
**Congrats** on getting **v4** out to Beta stage 🎉

I'm impressed with how everything works -- love the new modules and the variables are easy to change/understand.

But there is 1 utility I use a lot but shy away from using more... **spacing**.

The prefixes **m-** and **p-**, along with **-0**, **directional lettering** and **auto** are all perfect!

But, I feel the 1-5 scaling feels clumsy, restrictive and not entirely useful...

Have you considered using a percentage based system?
eg. **p-50** for half and **p-100** for normal, **p-200** for double etc.

```
.p-0
.p-50
.p-100
.p-200
```

Creating new maps for this would be really easy in the variable options. They are also better to interpret and remember off the top of the head.

**Comment by mdo** [comment]
Thanks for the kind words!

> Have you considered using a percentage based system?

That seems less clear to me, and conflates the numbers from our color system. You can, however, override all these values as you see fit. Sass maps and variables are provided to modify.

**Comment by jsonUK** [comment]
Fair enough, I can see you already use a hundred based system on the grayscale. Thanks for answering my question.

And you are totally correct -- I can just as easily override the maps myself so I can use a percent system if I so wish ;)

Best of luck and thanks for the hard work!
