### ISSUE TITLE
Cursor: pointer

### ISSUE THREAD

**Issue by gultyaev** [twbs/bootstrap#23720]
I explored the documentation and I could not understand: why do not buttons have CSS rule `cursor: pointer`. It is very unusual, because when pointer is changed you can be sure that you can get some response after clicking. Otherwise it seems just like table with hover rule. Every button should have this rule by default I think.

**Comment by rafalp** [comment]
Here's PR and discussion that may be of interest to you:

https://github.com/twbs/bootstrap/pull/21812

**Comment by mdo** [comment]
Closing for the original PR.
