### ISSUE TITLE
.modal(); doesn't execute javascript with bootstrap4

### ISSUE THREAD

**Issue by ilidio** [twbs/bootstrap#23727]
.modal(); doesn't execute javascript with bootstrap4. While in bootstrap3 this work with no probem.

To make this work, in bootstrap4, I had to make this small fix, and I added an eval statment like this:

**javascript**
```
<script>
    $.get("test.html", function (data) {
        $('<div id="activate-modal" class="modal fade">' + data + '</div>').modal();

        // Javascript Fix - start
        $(window).on('shown.bs.modal', function() {
            $("#delete-modal").find("script").each(function(i) {
                eval($(this).text());
            });
            console.log("oneActivate @ shown.bs.modal");
        });
       // Javascript Fix - end

    });
</script>
```

**test.html**
```
<h1>Hello world</h1>
<script>
  // this is not executed without the fix
   alert("this is a test");
</script>

```

**Comment by bkdotcom** [comment]
> While in bootstrap3 this work with no probem.

Citation needed
a)  Bootstrap 3 (just like bootstrap 4) has no built in "remote-url" modal/lightbox support.   You gotta fetch the content on your own via an ajax call...    And jQuery.get() doesn't execute inline scripts out of the box

**Comment by ilidio** [comment]
Thanks for your reply. Helped a lot.

I would consider changing my javascript functions with jQuery's [.load](http://api.jquery.com/load/) method.
