### ISSUE TITLE
Example Code Typo

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#23723]
I think there's a typo in the example code for [Multiple targets](https://getbootstrap.com/docs/4.0/components/collapse/#multiple-targets).

The sample code for the second button has:
`aria-controls="multiCollapseExample1"`
but I think it should be:
`aria-controls="multiCollapseExample2"`

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/pull/23741
