### ISSUE TITLE
v4 form validation state using one change

### ISSUE THREAD

**Issue by matthewmalone** [twbs/bootstrap#23737]
Is there simpler way to set the v4 form validation state for a form field and a help-block (now form-text in v4)

v3 allowed this to be done by adding a single "has-success" to "form-group" (see below example).

    <div class="form-group has-success">
      <label class="control-label" for="inputSuccess1">Input with success</label>
      <input type="text" class="form-control" id="inputSuccess1" aria-describedby="helpBlock2">
      <span id="helpBlock2" class="help-block">All success!</span>
    </div>

To do the same thing in v4, you need to set two separate items e.g. "is-invalid" and "invalid-feedback". Is there a way to achieve the same output, but only have to set it once (instead of twice). 

    <div class="form-group">
        <label for="validationServer03">City</label>
        <input type="text" class="form-control is-invalid" id="validationServer03" placeholder="City" required>
        <div class="form-text invalid-feedback">Please provide a valid city.</div>
    </div>

**Comment by mdo** [comment]
Nope.
