### ISSUE TITLE
Missing jquery.min.js in vendor path for Examples pages

### ISSUE THREAD

**Issue by Saurabh1** [twbs/bootstrap#23733]
Just downloaded 4.0.0-beta version from Github and there is missing jquery.min.js file under the Example of Starter page index.html file. And it is the same for all example files. 
Script added at the bottom of the page as : 
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>

File doesn't exist in the path mentioned so I believe we need to change either the path or have the file it to the correct path.

**Comment by mdo** [comment]
Are you running the docs locally with Jekyll, or just viewing their source code?

**Comment by Saurabh1** [comment]
I am trying to do with CMS so far and I just noticed that it was missing. I believe still we need to fix it. Please correct me if I am wrong.

**Comment by mdo** [comment]
Run the docs locally (see our readme) and you won't have any issues.
