### ISSUE TITLE
Border radius of the first and last child of the button group in vertical variation do not render properly

### ISSUE THREAD

**Issue by nguyenhthai** [twbs/bootstrap#23739]
So I notice that with the latest commit after the release of beta, the border radius on the first child and the last child inside the vertical button group do not get applied correctly.  In the beta 1 on the official website and previously versions, the first child button has no bottom border radius and the last child button has not top border radius (See the below screenshot)

![42c052fc33e449d1bb743b551e4db3bb](https://user-images.githubusercontent.com/6546158/29850371-d1336f82-8cf2-11e7-841c-eb25c60bff54.png)

With the latest dev commit, this is no longer true. The bottom and top border radius for the first and last child buttons, respectively, are not being set to 0, hence, this is the result looks like:

![image](https://user-images.githubusercontent.com/6546158/29850420-3a71c912-8cf3-11e7-82e0-8cfbba2c83dd.png)

Also, attach is the CodePen that demonstrates this problem: [https://codepen.io/nguyenthai/pen/BdGYOQ](https://codepen.io/nguyenthai/pen/BdGYOQ)
Verified this on Windows machine at least with all the supported browsers rendered like in the CodePen.

Dig through the code, I found the problem: Apparently, sometimes after the release of the first beta, a merge happened from the branch button-cleanup with the pull request #22951. The particular commit is  [6875bea819a9e495a77c5f54ffbc1d075a4fecbe](https://github.com/twbs/bootstrap/commit/6875bea819a9e495a77c5f54ffbc1d075a4fecbe) and the subsequent commit that fixed the indentation. 
With that commit the old code, which was
```
.btn-group-vertical > .btn {
  // Truncate some other code for abbreviation
  
  &:first-child:not(:last-child) {
    @include border-bottom-radius(0);
  }
 
  &:last-child:not(:first-child) {
    @include border-top-radius(0);
  }
}
```
became
```
.btn-group-vertical {
  // Truncate some other code for abbreviation

  &:first-child:not(:last-child) {
    @include border-bottom-radius(0);
  }
  
  &:last-child:not(:first-child) {
    @include border-top-radius(0);
  }
}
```
So for the button group, the markup would be like:
```
<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
    <button type="button" class="btn btn-outline-success">Button</button>
    <button type="button" class="btn btn-success">Button</button>   
    <button type="button" class="btn btn-outline-success">Button</button>
  </div>
```
With compilation, one of the selector is `.btn-group-vertical:first-child:not(:last-child)` and that would return none. With the old code, that selector would be `.btn-group-vertical > .btn:first-child:not(:last-child)` and it successfully applied the style to the first button inside the group. Not sure if this a mistake or an intentional change that was not documented clearly.

**Comment by mdo** [comment]
Looks good in Beta 3: https://getbootstrap.com/docs/4.0/components/button-group/#vertical-variation.
