### ISSUE TITLE
Popover on a hidden element

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#23749]
I've built a menu system using bootstrap4's popovers. Now I have a use-case when I'd like to display popover for a hidden button. @Johann-S how hard a requirement it is? Could we (optionally) allow popovers on a hidden element?

My use-case is as follows. In a phone layout I have two buttons that would invoke the same popover. Only one button is visible at the same time. I'd like to display the invisible button's popover on click on the visible button. Simply: `$('#button-visible').click(function() { $('#button-invisible').click(); })`.

The problem is that the popover contains quite complicated menu elements, so I don't really can just clone it and use a separate popover instance.

In this case I don't really care about popover positioning, as for phones I anyway overwrite it's style to take full page height and be aligned to the right side of the screen.

**Comment by Johann-S** [comment]
Currently we just check if the element is hidden with `display: none;` (see: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L249)

So if your invisible button have `visibility` set to `hidden` for our current code base your element isn't totally not visible, maybe this would do what you want to achieve ?

**Comment by alecpl** [comment]
The button itself does not have display:none, but its parent have. But I just noticed that I need to stopPropagation() before invoke click(). With this it works. That could have been caused by some click handlers on the body element I have. Thanks anyway.
