### ISSUE TITLE
Input Group w/ Textarea

### ISSUE THREAD

**Issue by tpck** [twbs/bootstrap#23745]
The button does not align with the text-area anymore (in both Firefox and IE11).

This worked perfectly fine in Bootstrap 4 Beta:

```
<div class="input-group">
  <span class="input-group-addon">Id</span>
  <textarea class="form-control" maxlength="1000">Text</textarea>
  <span class="input-group-btn">
    <button class="btn btn-danger" type="button">Delete</button>
  </span>
</div>
```
Bootstrap 4 Beta:
![input-group](https://user-images.githubusercontent.com/15745615/29876813-58747160-8d63-11e7-9f2d-0266fe97339e.PNG)

Bootstrap 4 Alpha:
![input-group-2](https://user-images.githubusercontent.com/15745615/29876909-af6fd20c-8d63-11e7-9329-a7eba444fed4.PNG)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by tpck** [comment]
Here is a link to the [jsfiddle](https://jsfiddle.net/7e3grv25/) displaying the problem.

- Bootstrap 4.0.0-beta
- Firefox 45.9.0 & IE11
- Windows 7
