### ISSUE TITLE
Hover navbar and hide popovers just after click out of them

### ISSUE THREAD

**Issue by AdrianKuriata** [twbs/bootstrap#23743]
Hi, is this possible to add in new bootstrap v4 navbar on the hover displaying? I mean we can add navbar with dropdowns and the will be display after click on them, maybe good feature will be add displaying dropdowns on hover coursor on the dropdown element? This is possible to do manually, but 
this is really bugged.

Second idea is add hidding popovers after click out of them, but still display block them when we click on them. Now we can just set hide popover after click somewhere so when we add link or button with eg. modal this will not be triggered or will hide after click on button.

I don't know, i checked whole documentation and i don't found something about this. Let's discuss about it.

**Comment by SumiGovindaraju** [comment]
@AdrianKuriata: I agree that these features would be helpful to have built into future releases of Bootstrap, but in the meantime I can show you how to get around it with simple jQuery and DOM.

Expand Dropdown on Hover: https://jsfiddle.net/aq9Laaew/39165/

Hide popovers by clicking out of them: https://jsfiddle.net/aq9Laaew/39213/

Hope this helps!

**Comment by AdrianKuriata** [comment]
@SumiGovindaraju I did same code a lot time ago, I wrote this feature for faster working with hoverable for everyone, but thanks for response! I hope your code help others mates!

**Comment by mdo** [comment]
Rereading this a long time later, this is getting closed as a won't fix. Sorry we misread it earlier, but there are no plans for hover based dropdowns.
