### ISSUE TITLE
Do I still need the css autoprefix with modern browsers today in 2017? Seriously?

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#23756]
Let's say I'm building a modern site with Bootstrap 4 and I wanna be compatible just with the most modern browsers like these:

    'last 2 Chrome versions',
    'last 2 Firefox versions',
    'last 2 Safari versions',
    'last 2 Edge versions'

**Do I really still need to autoprefix my final css (built from scss)? Really? In 2017 times?**

**Comment by andresgalante** [comment]
Hi @johnunclesam, I don't understand your question. Yes, even in 2017 there is a need for vendor prefixes, and you can always change autoprefixer settings for your project and rebuild bootstrap scss if you don't like what you get by default.

**Comment by mdo** [comment]
Yup, it's still needed. http://caniuse.com is a good resource for checking what's absolutely needed.
