### ISSUE TITLE
Columns sound no good

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#23754]
[The documentation's first section on the Grid system](https://getbootstrap.com/docs/4.0/layout/grid/#how-it-works) asks "Sounds good?". It is hard to answer, but it sounds vague.

The whole section brings more questions than it answers, but one particularly problematic part is the item 
> Content should be placed within columns, and only columns may be immediate children of rows.

At this point, the meaning of "column" has not been defined, and I do not see it defined later neither.

**Comment by gijsbotje** [comment]
How would you describe a column? to me it describes it perfectly and i can't really understand what your issue is...
You mention `more questions than it answers`, which questions do you have?
That might clarify your issue

**Comment by MargateSteve** [comment]
When I first looked at Twitter back in V2 days, I did not like the rows/columns structure as it felt like it was over complicated to the naive me.
However, I now think they are perfect names and do exactly what they say on the tin. Even without the terms being defined, I would imagine most people would understand what a row or column is.

**Comment by andresgalante** [comment]
@Chealer if you rather use another grid system, roll your own or just use [CSS Grids](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) you can compile bootstrap without the grid here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L89

You'll still get all the components, but the grid will not be included in your CSS.

**Comment by mdo** [comment]
If there are more specific pieces of feedback, we can address them, but I think the row and column concept is straightforward enough. Happy to see suggestions in PRs if you have them.

**Comment by Chealer** [comment]
> How would you describe a column? to me it describes it perfectly and i can't really understand what your issue is...

@gijsbotje, what "it" are you referring to?

> You mention more questions than it answers, which questions do you have?

Here are some questions the section brings:

> Bootstrap’s grid system uses a series of containers, rows, and columns to layout and align content. It’s built with flexbox and is fully responsive.

This refers to the CSS Flexible Box Layout Module as "flexbox", without a link, as if every web developer should know what "flexbox" means. CSS Flexible Box Layout Module Level 1 is merely a W3C candidate recommendation.

> The above example creates three equal-width columns on small, medium, large, and extra large devices using our predefined grid classes.

To confirm that, one would need to inspect the example. The code is not shown.

> Containers provide a means to center your site’s contents. Use .container for fixed width or .container-fluid for full width.

Perhaps this is because I do not master CSS, but while I basically know what "fixed width" and "full width" mean, I cannot say what these mean in this context.

> We use the negative margin method on .row to ensure all your content is aligned properly down the left side.

What is the negative margin method (and do such implementation details belong in the introduction?)?

> Content should be placed within columns, and only columns may be immediate children of rows.

This of course brings the question "What are columns?" Beyond that, one wonders what happens if content is not placed within columns, or if rows have children other than columns. Will errors be reported? If not, is it possible to verify that a document makes valid use of Bootstrap?

> Column widths are set in percentages, so they’re always fluid and sized relative to their parent element.

What does "Column widths are set in percentages" mean? Is this talking about internals again? What does "always fluid" mean?

> There are five grid tiers, one for each responsive breakpoint: all breakpoints (extra small), small, medium, large, and extra large.

What is a "grid tier"?

> You can use predefined grid classes or Sass mixins for more semantic markup.

Which "predefined grid classes"?

> Be aware of the limitations and bugs around flexbox, like the inability to use some HTML elements as flex containers.

Does this belong in "How it works"? Should this not be "How it doesn't work" or "Warnings"? What are the limitations around flexbox? The paragraph sounds like "Our system provides an abstraction to a technology which is problematic, but we don't document the issues this causes, so 1. research the issues of that technology 2. try figuring out how we use that technology, so you may 3. deduce the issues in our abstraction". 

If the actual situation is similar, I recommend to move this paragraph to a dedicated section which could keep the 2 current links, but focus on the corresponding Bootstrap issues, linking to issue reports. It might help to evaluate the level of support offered by each browser, so that reader can understand workarounds more easily.


It is possible that some of these questions are answered later, in which case it may not be an issue that these questions arise.

**Comment by Chealer** [comment]
> When I first looked at Twitter back in V2 days, I did not like the rows/columns structure as it felt like it was over complicated to the naive me.

I am not convinced that I like how the grid system works, but this report is not about how it works, just about the documentation.

> However, I now think they are perfect names and do exactly what they say on the tin.

The [main] issue reported here is usage of an undefined term. I am not claiming that any name is imperfect.
That being said, clear undefined terms are certainly better than less clear undefined terms. From what I understand about columns, if a column is a child of a row, "cell" would be a more appropriate name.

> Even without the terms being defined, I would imagine most people would understand what a row or column is.

I am not saying they don't... I might be part of a minority, but that does not excuse usage of undefined terms.

**Comment by Chealer** [comment]
Thanks @andresgalante but this is not saying the grid system is suboptimal per se, just that its documentation is. One of my projects has been using Bootstrap's grid system for a couple of years, so I have no choice but to try understanding how it works as much as possible.

**Comment by andresgalante** [comment]
@Chealer if the docs aren't clear for you, I am sure there are others that find it confusing. Send a PR with improved docs 😄

**Comment by Chealer** [comment]
@andresgalante , the docs are not clear for me, but I do not know what a column is.

I have reported the content issue reported here in ticket #24075 . I also made a clearer (irony-free) report of the form issue in ticket #24076 .
