### ISSUE TITLE
Suggestion: BS4 - an easy way to see basic debug info

### ISSUE THREAD

**Issue by mwd-au** [twbs/bootstrap#23752]
Often when we are building websites & apps using bootstrap we need basic debugging info like what break point is currently being used & the current window size. I have created a quick javascript function that will display this info at the top of the page. I think something like this would be great to include in the core as it makes it easy to see what is going on.

Example JS Fiddle below. Run it, then resize the window to see the current break point that is being used & the current window size.
https://jsfiddle.net/v5hm16bk/

What does everyone think or am I the only one that thinks this would be handy to have by default?

**Comment by andresgalante** [comment]
Hi @mwd-au although this is really cool. 

To be honest I don't think it should be on core since you can get the same information from the inspector.

On the other hand if you can start a new project of debugging tools for bootstrap as a plugin or extension it would be completely awesome IMO.

**Comment by Johann-S** [comment]
I don't think it's something we should include in our code base, but I totally agree with @andresgalante you should make a plugin and share it on github 👍

**Comment by mwd-au** [comment]
Thanks guy - will do a plugin then.

**Comment by geeksareforlife** [comment]
Let us know here when you do - that plugin would be really useful!

**Comment by mwd-au** [comment]
I have posted the code in a GitHub gist for anyone interested in it:
https://gist.github.com/mwd-au/457b1f343532f60021550c1fe68211d0

Here is a quick JsFiddle to see it in action:
https://jsfiddle.net/v5hm16bk/
