### ISSUE TITLE
New theme variable makes things inflexible when customizing 

### ISSUE THREAD

**Issue by stephenbe** [twbs/bootstrap#23750]
Hello,

In alpha 6, you could customize the buttons exactly how you wanted with these variables  : 
https://github.com/twbs/bootstrap/blob/65ffb1c3b6e94440812a2e228cb8e8be512652ec/scss/_variables.scss#L362-L410

But now with the theme variables, you cannot theme the buttons independent from the rest. My secondary button has a white background and a green border. I don't want to change the secondary color for all my components that use the theme variable.

If I want my secondary alert to be blue, but it uses the white from the secondary button, do I have any other choice then to write additional css to overwrite this?

Is there something I am not seeing here? Seems like you cannot be as precise as before without needed to write extra css.

**Comment by mdo** [comment]
This is how we'll be moving forward with them in v4, however, additional control over hover states and the like need to be added as the issue reference above shows.
