### ISSUE TITLE
Remove inner white border effect on popovers

### ISSUE THREAD

**Issue by andresgalante** [twbs/bootstrap#23763]
The popovers have an inner white border on the headers, it's a nice effect but I think it makes the styles too opinionated, plus it's a code overhead to generate them and it makes it harder to convert popovers from px to rems.

How about we remove that effect and simplify the popover code?

**Comment by mdo** [comment]
Yeah, I'm fine nuking them :D.

**Comment by andresgalante** [comment]
@mdo Cool, I'll send a PR removing them and changing the units to `rem` today.
