### ISSUE TITLE
jquery-3.2.1.slim.min.js conflicting with .animate  function

### ISSUE THREAD

**Issue by MateenSalik** [twbs/bootstrap#23760]
$('a[href*="#"]')
  .not('[href="#"]')
  .not('[href="#0"]')
  .click(function(event) {
    if (
      location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') 
      && 
      location.hostname == this.hostname
    ) {
     
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
      if (target.length) {
        event.preventDefault();
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000, function() {
          var $target = $(target);
          $target.focus();
          if ($target.is(":focus")) { 
            return false;
          } else {
            $target.attr('tabindex','-1'); 
            $target.focus(); 
          };
        });
      }
    }
  });

This is the code I am using for smooth scrolling in Bootstrap v4. It is conflicting with jquery-3.2.1.slim.min.js when I change library it works fine. 

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

**Comment by Johann-S** [comment]
I don't think you targeted the good repository, it's an issue with jQuery not with Bootstrap
