### ISSUE TITLE
Carousel control icons not aligned correctly

### ISSUE THREAD

**Issue by CarlosTorrecillas** [twbs/bootstrap#23768]
The carousel control icons seem to be incorrectly aligned. If you take a look at the screenshots taken on the following issue: https://github.com/ng-bootstrap/ng-bootstrap/issues/1798 you should be able to see how the **next** icon should be aligned to the right as the **prev** icon is correcly aligned to the left.

When reporting a bug, include:

- Operating system and version: Windows 10
- Browser and version: Chrome 60.0.3112.113

In order to replicate that you can go to any of your carousels: https://getbootstrap.com/docs/4.0/components/carousel/ and add the background-color: black to **.carousel-control-next-icon, .carousel-control-prev-icon** and you'll see that straight away.

**Comment by Johann-S** [comment]
https://codepen.io/Johann-S/pen/MvZqGw?editors=1100

**Comment by mdo** [comment]
The SVGs need to be updated so that the chevrons site in the middle of the viewbox.
