### ISSUE TITLE
Request, Allow Accordion selectors starting from the parent to be discovered greater than 2 levels

### ISSUE THREAD

**Issue by coder4life** [twbs/bootstrap#23767]
## Summary of Issue

As the issue describes currently selectors from the parent are only discovered 2 levels down. This severely limits collapse to an exact structure. 

For clarification I am using the term "Accordion" to convey the intention that **showing** a collapsed section will **close** all other open sections.

## Where to find the Issue

The line that creates this problem can be located here:
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L132

## Suggestion to fix
Using jQuery find would work, however there are a few things to consider, like should it traverse the entire tree under the selected parent id. My suggestion would be able to set a max search depth.

Second problem is potential nested accordions. Although the parent selector could be the anchor to all other accordion events, which means the nested accordion would not get toggled unless they share the same parent id.

A side benefit, this would greatly open the opportunity to sidebar menus with accordion collapse behaviors.

## Concerns
While I understand the need for performance to avoid having to traverse all parent to child nodes, a compromise could be made to allow a certain search depth. Also jQuery find(), used in some of the Bootstrap Source Javascript files, once traversed the DOM and selectors discovered is cached.

**Comment by bkdotcom** [comment]
> This severely limits collapse to an exact structure.

how so / what does that mean?  What are you trying to do?

> A side benefit, this would greatly open the opportunity to sidebar menus with accordion collapse behaviors.

could you elaborate?

> side benefit

What's the primary issue you're trying to solve or primary benefit you need?

**Comment by coder4life** [comment]
> how so / what does that mean? What are you trying to do?

What this means is if you have intermediary markup between the the `id="myID"` and the child element with the assigned `data-parent="miID"` accordions cannot collapse other accordions unless the markup is exactly 2 levels. Obviously this is not always wanted behavior, but if bind to the same `` it should be allowed.

Right now the behavior is to have only two levels down for custom bind.

As in the docs:
[Multiple-Target Collapse](https://getbootstrap.com/docs/4.0/components/collapse/#multiple-targets)
_As a separate but important note the id element `data-children=".item" in the docs is meant to bind the adjacent nodes of the same `css.class` as in the document page._

The lookup where the child element gets loaded into the array of all bind accordions it only searches 1 child level. 

Code here:
[Code that binds element down 2 levels](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L132)

parent (id="myID) > node (.children())> node (.children())

For example, take a sidebar menu for example that uses accordions to reveal child nodes under a parent node. The binding element is the parent (also `id="myID") however the intermediary markup  might needed creating different heights of the tree at various points.

**Comment by n3o77** [comment]
Same problem here.

This works:
```html
<div>
    <ul id="exampleAccordion" data-children=".item">
        <li>
            <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content1">Toggle 1</a>
            <div id="content1" class="item collapse">...</div>
        </li>
        <li>
            <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content2">Toggle 2</a>
            <div id="content2" class="item collapse">...</div>
        </li>
        <li>
            <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content3">Toggle 3</a>
            <div id="content3" class="item collapse">...</div>
        </li>
    </ul>
</div>
```

This doesn't as it only searchs in the `ul` direct children for the child-selector:
```html
<div id="exampleAccordion" data-children=".item">
    <ul>
        <li>
            <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content1">Toggle 1</a>
            <div id="content1" class="item collapse">...</div>
        </li>
        <li>
            <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content2">Toggle 2</a>
            <div id="content2" class="item collapse">...</div>
        </li>
        <li>
            <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content3">Toggle 3</a>
            <div id="content3" class="item collapse">...</div>
        </li>
    </ul>
</div>
```

**Comment by bkdotcom** [comment]
@n3o77 
why not just move `id="exampleAccordion" data-children=".item"` attributes to the `<ul>` ?

**Comment by n3o77** [comment]
@bkdotcom Because this is just to illustrate the problem and I didn't want to post my whole structure :) My actual code looks more like this (but again, simplified):

```html
<div id="exampleAccordion" data-children=".item">
    <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content1">Toggle 1</a>
    <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content2">Toggle 2</a>
    <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content3">Toggle 3</a>

    <div id="content1" class="item collapse">... A ...</div>
    <div id="content2" class="item collapse">... B ...</div>
    <div id="content3" class="item collapse">... C ...</div>
</div>
```
Which to work needs an extra wrapper just for the parent. There are probably some other cases where the children could be down 3 levels or more.

**Comment by coder4life** [comment]
@bkdotcom Yes you can. But take a scenario where there is extra markup between the parent div `id="exampleAccordion" data-children=".item"` and the ul (which is possible in scenarios).

Like I said in a post above a sidebar menu does not necessarily conform to the ul > li > a structure. It can have sectioned rendered menus where each menu is encapsulated in some custom parent markup.

```html
<div id="exampleAccordion" data-children=".section">
    <div id="section_1" class="section">
        <ul>
            <li>
                <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#section_1-content1">Toggle 1</a>
                <div id="section_1-content1" class="item collapse">...</div>
            </li>
            <li>
                <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#section_1-content2">Toggle 2</a>
                <div id="section_1-content2" class="item collapse">...</div>
            </li>
            <li>
                <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#content3">Toggle 3</a>
                <div id="section_1-content3" class="item collapse">...</div>
            </li>
        </ul>
    </div>
    <div id="section_2" class="section">
        <ul>
            <li>
                <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="section_1-#section_2-content1">Toggle 1</a>
                <div id="section_2-content1" class="item collapse">...</div>
            </li>
            <li>
                <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#section_2-content2">Toggle 2</a>
                <div id="section_2-content2" class="item collapse">...</div>
            </li>
            <li>
                <a class="toggle" data-toggle="collapse" data-parent="#exampleAccordion" data-target="#section_2-content3">Toggle 3</a>
                <div id="content3" class="item collapse">...</div>
            </li>
        </ul>
    </div>
</div>
```

**Comment by mdo** [comment]
This is stale, but I believe it works in v4.5.3: https://codepen.io/emdeoh/pen/zYKLVRN.
