### ISSUE TITLE
Ugly buttons on lazy loaded anchor tags

### ISSUE THREAD

**Issue by kamranahmedse** [twbs/bootstrap#23766]
**Version 4**

If the anchor URL is lazy loaded into it (which is common if you are using e.g. angular or react), the buttons don't have `href` on page load for some time and [because of this style](https://github.com/twbs/bootstrap/blob/6b6f45ad673b4f1cbc63e29f01bc5ad10a87ebd5/scss/_reboot.scss#L208) buttons `inherit` the text color for sometime and look ugly, it would be great if there was a way to disable this style inheritance on specific anchor tags.

![image](https://user-images.githubusercontent.com/4921183/29913714-fbe7d650-8e46-11e7-8ba0-1bd505363795.png)

**Comment by patrickhlauke** [comment]
arguably, what this form of lazy loading is doing is to first inject "anchors" into the page (`<a>` elements without an `href`), and only later turning them into actual links (`<a href="..."`). The more fundamental fix would probably be for the lazy load not to inject one type of content and then changing its nature, but rather starting off with injecting actual links (even if their `href="#"` or something).

**Comment by mdo** [comment]
Closing as a won't fix.
