### ISSUE TITLE
bootrap 4 file reboot.scss is causing a lot major issues

### ISSUE THREAD

**Issue by adpurohit** [twbs/bootstrap#23765]
Bootstrap4
![untitled1](https://user-images.githubusercontent.com/23528249/29910492-cd951e56-8e47-11e7-8f47-b76c9dfcb807.png)

bootstrap3
![untitled](https://user-images.githubusercontent.com/23528249/29910491-cd950fba-8e47-11e7-8e35-9f93defe110f.png)

Check the difference of bootstrap 3 & 4. wells class is also removed and replaced with card a major drawback in bootstrap4

**Comment by mdo** [comment]
v4 is a major rewrite—we dropped and changed many many things. Consult our migration docs and ensure you're updating things properly.
