### ISSUE TITLE
Documentation: Clicking link to (anchor) "browser defaults" does not work (no effect)

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#23773]
[The How it works section of the Forms component documentation](https://getbootstrap.com/docs/4.0/components/forms/#how-it-works) contains a "browser defaults" link to an anchor on the same page. While the page does contain a Browser defaults section and this anchor seems valid, clicking that link has no effect here (Google Chrome 60 on Windows 8). Clicking does not trigger any error/warning but does not move the viewport, for a reason which is not obvious to me.

**Comment by Johann-S** [comment]
Sorry but it works for me on Win10 and Chrome 60

**Comment by patrickhlauke** [comment]
typo in the relative anchor (missing the "s" at the end)

**Comment by Chealer** [comment]
Was going to say that. Thanks Patrick
