### ISSUE TITLE
Blockquotes example and others use cryptic spacing classes before their introduction

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#23772]
Several examples in the documentation use cryptically named classes with an effect described in [the Spacing utility's documentation](https://getbootstrap.com/docs/4.0/utilities/spacing/). For example, the example in [the documentation of Blockquotes](https://getbootstrap.com/docs/4.0/content/typography/#blockquotes) uses the mb-0 class.

For examples which precede the Spacing utility's documentation, I strongly recommend to clarify by either:

1. Just dropping these classes, which seems like a perfectly valid choice in the example I mentioned.
1. Using CSS to achieve the effect of these classes
1. Moving the Spacing section so these classes are introduced before they are used in examples
1. Using classes with clearer names (such as margin-bottom-0), if the classes used have "aliases" with clear names
1. Refering to the documentation of the Spacing utility in the description of the affected examples

Examples which follow Spacing's documentation may still be unclear for some readers, but I consider improvements for these as optional.

**Comment by mdo** [comment]
We'll leave them as-is for now. This isn't a problem limited to spacing utilities; we mix and match things in many places. Search in the docs helps a ton and search the codebase is always a solid follow-up.

**Comment by Chealer** [comment]
@mdo , please explain what you mean by "for now" and why this report was closed.

**Comment by Chealer** [comment]
Please reopen this ticket.

**Comment by bardiharborow** [comment]
@Chealer this report was closed because we do not feel this is a bug, and we will not be fixing this.

**Comment by Chealer** [comment]
@bardiharborow , lack of clarity is not an anomaly. Nobody claims this ticket tracks a bug.
That thankfully does not prevent solving the issue. In any case, whether or not an issue will be fixed does not determine whether a report should be closed or not.
