### ISSUE TITLE
Create component shadow variables to keep consistency across components

### ISSUE THREAD

**Issue by andresgalante** [twbs/bootstrap#23775]
We are defining different shadows in different components. There are about 25 shadow definitions on variables.

To keep consistency, I think we unify all of them in 4 shadow variables (sm, md, lg and inset) and then reuse them across components.

For example, instead of:
```scss
$popover-box-shadow:                  0 .3rem .6rem rgba($black,.2) 
```

We would have something like:
```scss
$component-box-shadow-md:                  0 .3rem .6rem rgba($black,.2) 
$popover-box-shadow:                  $component-box-shadow-md 
```
This follows the same idea as #23674 

Before I send a PR I'd like to know what do you guys think?

**Comment by mdo** [comment]
I'm down!

**Comment by Herst** [comment]
Accomplished with #24429?

**Comment by mdo** [comment]
Revisiting this, I've put some existing `box-shadow` variables that we added awhile ago better use. See #29023.
