### ISSUE TITLE
features - Simplify the style of examples

### ISSUE THREAD

**Issue by planetoftheweb** [twbs/bootstrap#23787]
I feel like some of the documentation gets unnecessarily long because of all of the options. I ran into this same issue when I was trying to document the features for my online courses, so I switched to a model where I used more visually appealing formulas with colors. I think this could easily be accomplished with button tag classes. Something like the following.

![screen shot 2017-08-31 at 7 57 19 pm](https://user-images.githubusercontent.com/216426/29950149-da333a04-8e87-11e7-8fa0-fa6e7027c76e.png)

![screen shot 2017-08-31 at 8 04 48 pm](https://user-images.githubusercontent.com/216426/29950148-da2e8f22-8e87-11e7-8b51-b692a62b1d74.png)

![screen shot 2017-08-31 at 8 04 29 pm](https://user-images.githubusercontent.com/216426/29950147-da2ccb06-8e87-11e7-9ab0-ac0f6768e12d.png)

**Comment by andresgalante** [comment]
I seems complicated to me, but if this can be automatically generated I'd give it a thumbs up

**Comment by planetoftheweb** [comment]
Some of the docs have a really long list of options, this would make it shorter and easier to figure out

**Comment by andresgalante** [comment]
👍  you are right, I like the long list of options since it makes it easier to identify what is the impact of your changes when you contribute to bootstrap.

Can't we get both? the short notation with icons along side each section title and all the examples?

**Comment by mdo** [comment]
We'll stick with what we have currently. The lists can be a little long, but their purpose was to see if the explicit lists helped or hindered things. We'll wait and see a bit longer.
