### ISSUE TITLE
Dropdown main nav menu not working on iphone since switch to https

### ISSUE THREAD

**Issue by galexmay** [twbs/bootstrap#23785]
I have just reconfigured our site to use https. Everything seems to be working fine (including testing on Windows and Android using Chrome, Edge, IE, Opera and Safari) except that iphone and ipad users are reporting main nav dropdown menu clicks are doing nothing.

(Using minified bootstrap 3.2.0)

**Comment by patrickhlauke** [comment]
As this sounds more like an implementation issue specific to your site, rather than anything related to bootstrap, I'd suggest asking on StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by galexmay** [comment]
I don't think you should have closed this. You think it sounds like 
implementation, but you don't know. There have been bugs causing this sort 
of issue in the past.



--- Original message ---

**Comment by patrickhlauke** [comment]
please provide a reduced test case showing the problem. also, update to bootstrap 3.3 at least.
