### ISSUE TITLE
[docs] remove all but one table-inverse example

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#23790]
Why are all examples duplicated with 'table-inverse' ?
https://getbootstrap.com/docs/4.0/content/tables/

Just the example showing this class is enough.

**Comment by andresgalante** [comment]
Hi @mariusa I don't think there is anything wrong in showing all the variables. Although it's more "verbose" it lets users easily see what's available.

Plus it's a great way to avoid mistakes when contributors change styles, you can instantly see if something went wrong without having to build every single instance.

**Comment by mdo** [comment]
What @andresgalante said.
