### ISSUE TITLE
Modal: adding a background-color to modal-header results in square top corners

### ISSUE THREAD

**Issue by hfournier** [twbs/bootstrap#23798]
Bug description: If you set a background-color on the modal-header <div>, you get square corners at the top of the modal window. The background-color covers the rounded corners. Adding "overflow: hidden" to the modal-content class CSS seems to fix the issue.

Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/2VppXXpMUPUkBvRpSg4F

Version of Bootstrap: Bootstrap: 4.0.0-beta

- Operating system and version (Windows 10 Pro)
- Browser and version (MS Edge)

**Comment by andresgalante** [comment]
Hi, @hfournier this is a bug, I'll send a PR to fix it today.

**Comment by andresgalante** [comment]
Hi @hfournier Thanks a lot for reporting this.

An `overflow:hidden` is a bad idea because it'll cut off the modal shadow (if you have shadows enable).

I've just sent a PR that fixes it.
