### ISSUE TITLE
Tooltip arrows not centered perfectly

### ISSUE THREAD

**Issue by pkozlowski-opensource** [twbs/bootstrap#23793]
The issue is visible on the demo page here: https://getbootstrap.com/docs/4.0/components/tooltips/

If you look closer at the left / right positioning you will notice that arrows are not centered (vertically) perfectly:

![issue](https://user-images.githubusercontent.com/973550/29700497-4bb6c132-8965-11e7-8ae3-c6f1673f14f1.png)

**Comment by pkozlowski-opensource** [comment]
I've zoomed it in to exaggerate issue but the pb exists even without zooming.

**Comment by andresgalante** [comment]
Although it's not perfect yet, it's improved on this PR #23468

**Comment by Johann-S** [comment]
Is it the same on a Codepen ? Because here we display the arrow manually instead of using Popper.js

**Comment by gijsbotje** [comment]
i think they work correctly in a pen
https://codepen.io/gijsbotje/pen/YrMYxe
