### ISSUE TITLE
Validate readonly inputs

### ISSUE THREAD

**Issue by K1N5L4Y3R** [twbs/bootstrap#23803]
I am using a readonly input that displays the result of some user interaction. For example, the readonly input displays surface area of a polygon that a user draws in a map (e.g. 20 for 20 sq. kms). The input is readonly because the user does not enter the surface directly, but draws a polygon in the map, however the surface needs to be validated (e.g. min. 5, max. 100, present).

When using readonly and validating (i.e. adding `.was-validated` to the form), the readonly input doesn't get `:invalid`, nor does its `.invalid-feedback` show.

Is there a way to enable validation for readonly inputs?

[JSBin](https://jsbin.com/yocokahere/edit?html,js,output)

**Comment by mdo** [comment]
Readonly inputs aren't mutable, so they cannot be validated. The same goes for `disabled` near as I can tell. Some more info in the spec: https://html.spec.whatwg.org/multipage/forms.html#the-readonly-attribute. Suggested workarounds/hacks on Stackoverflow: https://stackoverflow.com/questions/12777751/html-required-readonly-input-in-form

**Comment by K1N5L4Y3R** [comment]
Gotcha.

Just as an FYI in case someone else needs to have this functionality, what I ended up doing was simulating a disabled input like this:

```
// CSS. Prevents clicking on the input and applies same style that Bootstrap
// applies to disabled / readonly inputs.
input.disabled-input {
  pointer-events: none;
  background-color: #e9ecef;
  opacity: 1;
}
```

```
// Coffeescript. Makes sure that navigating to the input via tab key impossible
$('input.disabled-input').each ->
    $(this).attr('tabindex', '-1')
```
