### ISSUE TITLE
v4 Migration docs still refer to .has-danger

### ISSUE THREAD

**Issue by exige81** [twbs/bootstrap#23802]
From docs/4.0/migration.md

### Forms

- Moved element resets to the `_reboot.scss` file.
- Renamed `.control-label` to `.form-control-label`.
- Renamed `.input-lg` and `.input-sm` to `.form-control-lg` and `.form-control-sm`, respectively.
- Dropped `.form-group-*` classes for simplicity's sake. Use `.form-control-*` classes instead now.
- Dropped `.help-block` and replaced it with `.form-text` for block-level help text. For inline help text and other flexible options, use utility classes like `.text-muted`.
- Dropped `.radio-inline` and `.checkbox-inline`.
- Horizontal forms overhauled:
  - Dropped the `.form-horizontal` class requirement.
  - `.form-group` no longer applies styles from the `.row` via mixin, so `.row` is now required for horizontal grid layouts (e.g., `<div class="form-group row">`).
  - Added new `.form-control-label` class to vertically center labels with `.form-control`s.
  - Added new `.form-row` for compact form layouts with the grid classes (swap your `.row` for a `.form-row` and go).
- Added custom forms support (for checkboxes, radios, selects, and file inputs).
- Added HTML5 form validation support via CSS's `:invalid` and `:valid` pseudo-classes.
**- Renamed `.has-error` to `.has-danger`.**
- Renamed `.form-control-static` to `.form-control-plaintext`.

This was replaced by .is-invalid

**Comment by andresgalante** [comment]
Hi @exige81, Do you want to send a PR with this? I can help you if you need a hand 👍

**Comment by exige81** [comment]
PR to fix this here: https://github.com/twbs/bootstrap/pull/23842
