### ISSUE TITLE
[v4] form-control: Remove background-image: none; 

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#23817]
form-control has 
background-image: none; 

Why is that?

On some sites there are customizations on select, which set webkit-appearance to none and add a background-image with an arrow.
Applying bootstrap removes that image, but also doesn't reset webkit-appearance (remains none), so select controls don't have a dropdown icon at all.

Would you please consider removing 
background-image: none; 
?

**Comment by Johann-S** [comment]
It's to reset unusual Firefox-on-Android default style see : 
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L16 and 
https://github.com/necolas/normalize.css/issues/214

**Comment by Fouzyyyy** [comment]
I'm wondering if adding this detail to the documentation [Form controls](https://getbootstrap.com/docs/4.0/components/forms/#form-controls) to make sure the twbs users are aware of this detail is a good idea.

**Comment by Herst** [comment]
The issue has been resolved in Firefox 35 (released January 2015) according to https://github.com/necolas/normalize.css/issues/214#issuecomment-56409892.
