### ISSUE TITLE
Curiosity: Why are nested items in BS4 have full class names again?

### ISSUE THREAD

**Issue by bertoost** [twbs/bootstrap#23815]
Like the `breadcrum-item`
```
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="#">Home</a></li>
  <li class="breadcrumb-item active">Library</li>
</ol>
```
Or like the `nav-item`
```
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
</ul>
```
Couldn't this be handled by CSS, using `.nav li a` etc?
What is the reason of this choice? This creates a lot of HTML.

Regards, Bert

**Comment by AkashGutha** [comment]
Yes, definitely true. 

The previous implementation was much cleaner and we had to write much less code. 
The carousel Example:

```html
<div class="carousel-inner">
  <div class="item">
    <img src="./1.jpg" alt="">
  </div>
  <div class="item active">
    <img src="./2.jpg" alt="">
  </div>
  <div class="item">
    <img src="./3.jpg" alt="">
  </div>
</div>
```

**Comment by rafalp** [comment]
Previous implementation was great if what you were going for was 100% what Bootstrap was giving to you, but as soon as you've tried to do something else (eg. notifications list in dropdown, custom carousel slide, etc ect.), this approach was quickly making your life miserable, forcing you to write resets for Bootstrap's styles.

This also went in other way, when you've tried to reuse styles from other item (eg. put link-like button in dropdown), you've had to dig up Bootstrap's styles and copy them over.

**Comment by gijsbotje** [comment]
i think this is a better approach, i've been seeing a lot of guides advising to **not** use html selectors in your css but give them a specific class
And probably the reason why bootstrap has this approach is that it is conform mdo's codeguide (http://codeguide.co/#css-selectors)

**Comment by mdo** [comment]
More flexible on the markup site. Our blog posts from previous alpha releases and getting started docs make this clear.
