### ISSUE TITLE
Problem Nav menu on mobile click, opera mini v4.x

### ISSUE THREAD

**Issue by daniakbar** [twbs/bootstrap#23812]
i use opera mini (v4.x )mobile for android and click nav menu the page reload for opening the dropdown menu..

close the dropdown menu the page reload again.

**Comment by daniakbar** [comment]
Website link: themes.dadesain.com

**Comment by patrickhlauke** [comment]
Opera Mini (and similar thin client browsers) are not officially supported by Bootstrap I'm afraid. Suggest asking for workaround on Stackoverflow or similar. https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by techdavid** [comment]
Uhh... that's how Opera Mini works - it processes JS on the server and returns it to the client. The same happens for every other website.

**Comment by patrickhlauke** [comment]
...and what @techdavid said (I thought the original issue was about the menu not opening/closing after the reload)
