### ISSUE TITLE
navbar dropdown not working 

### ISSUE THREAD

**Issue by joonkui95** [twbs/bootstrap#23818]
framework: laravel 5.5
use laravel-mix compile
need manual import Popper

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by joonkui95** [comment]
Browser : chrome
project : https://github.com/joonkui95/RTC/tree/dev-bug
live demo here : http://ahkui.com:99/
Popper.js missing doesn't have error

**Comment by gijsbotje** [comment]
I can find all the needed code in the app.js, really weird that the navbar-expand is working but the dropdown isn't
could you maybe try and an id line the documentation describes? https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropdowns

**Comment by Johann-S** [comment]
Here's how to use Bootstrap with Webpack : https://getbootstrap.com/docs/4.0/getting-started/webpack/
