### ISSUE TITLE
Using :after css property on .card-body doesn't work as expected

### ISSUE THREAD

**Issue by jerryasih** [twbs/bootstrap#23833]
This is my code snippet:
```
    .card-body:before {
		content: '';
		display: block;
		width: 100%;
                height: 100%;
		position: absolute;
		top: 0;
		left: 0;
		background: rgba(55,55,55,0.3);
		z-index: -1;
	}
```

![screenshot 241](https://user-images.githubusercontent.com/21135654/30038562-0ff84ccc-91be-11e7-938a-a29af33cfe77.png)

The style gets applied to the whole card instead of .card-body (where the circle image is) alone

**Comment by andresgalante** [comment]
The card-body should be set to position relative in order for your code to work. An absolute positioned element is positioned relative to its immediate absolute or relative positioned parent.

**Comment by jerryasih** [comment]
Oh. Thanks man. Resolved.
