### ISSUE TITLE
Docs: text-wrapping and overflow issue

### ISSUE THREAD

**Issue by joedaniels** [twbs/bootstrap#23835]
In the docs there is the following issue where an image placeholder is on top of some text:

<img width="822" alt="screen shot 2017-09-05 at 00 25 55" src="https://user-images.githubusercontent.com/10812338/30040016-f30eca10-91d0-11e7-8318-b3ea7296ffc7.png">

**Comment by mdo** [comment]
This example is designed to show the `.text-nowrap` behavior—it's intentional :).
