### ISSUE TITLE
Unexpected Results Using $enable-shadows

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#23837]
Changing `$enable-shadows` to `true` does not give the results I believe most people are expecting.
  
**Example 1:**
![screen-shot-2017-09-04-at-3 12 57-pm](https://user-images.githubusercontent.com/2222751/30037584-5bf109a4-918a-11e7-89a8-07b38bba9359.png)

**Example 2:**
![input_02](https://user-images.githubusercontent.com/2222751/30044633-4d83e3c2-91cc-11e7-9636-3bcb5dff4165.png)

So please consider changing line 339 of variables.scss from `$btn-box-shadow: inset 0 1px 0 rgba($white,.15), 0 1px 1px rgba($black,.075)` to something like `$btn-box-shadow: 0 2px 2px rgba($black,.2)`.

Also, what do you guys think about having shadows on active nav pills when `$enable-shadows` is set to `true`?

**Comment by andresgalante** [comment]
Hi @LarryAzevedo although I don't think pills should have shadows I think that shadows in general are all over the place. To me it doesn't matter if the shadow on btns is subtle, since that's an opinion, as long as it's consistent with other elements.

I've described a possible solution here #23775

**Comment by LarryAzevedo** [comment]
Hey @andresgalante, thanks for your feedback on pill shadows.  As far as your comment:
> To me it doesn't matter if the shadow on btns is subtle 

I understand that to you it doesn't matter.  Heck, it doesn't even matter to me (now that I know it works).  But what about others like myself that didn't notice anything different after turning on shadows?  Not the greatest user experience.

By the way, I like your solution on #23775
