### ISSUE TITLE
Arrow out of popover

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#23846]
Popover arrow can be placed incorrectly when button on the edge of the screen.
![arrow-issue](https://user-images.githubusercontent.com/546788/30098664-2ce12888-92e3-11e7-9d05-188237188b94.png)
Tested with most recent Bootstrap4 build.

**Comment by Johann-S** [comment]
Can you make a CodePen of this issue please ? As it mentionned in our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md)

**Comment by alecpl** [comment]
@Johann-S I thought it's obvious, but here you go: https://jsbin.com/horagubehe. See that horizontal as well as vertical position is buggy.

**Comment by Johann-S** [comment]
it seem's has a CSS problem because Popper.js position correctly our arrow but our arrow width is too high 🤔 

yes @alecpl but that's easier for us to made a fix with a reproducible bug in live 👍

**Comment by FezVrasta** [comment]
@Johann-S: Popper.js already takes care to include the arrow width in its computations (theorically), make sure the most outer arrow element has the right width set.

**Comment by Johann-S** [comment]
Thank you so much @FezVrasta 👍 if you want to do that changes do not hesitate

**Comment by alecpl** [comment]
Maybe #23820 should be considered first.

**Comment by wojtask9** [comment]
Can you check this https://codepen.io/anon/pen/jLjraP ?

**Comment by wojtask9** [comment]
I didn't saw #23820 
This PR should fix the issue

**Comment by wojtask9** [comment]
I was wrong. #23820 isn't working
https://codepen.io/anon/pen/ZJdLpW (css compiled with popover changes from #23820)

**Comment by Johann-S** [comment]
this CodePen : codepen.io/anon/pen/gxNxZw seems fine @wojtask9, isn't it ?

**Comment by wojtask9** [comment]
@Johann-S 
Yes.
This pen contains my fix to Popper.js and css popover changes.
I'll make PR when I'll get back home

**Comment by jipexu** [comment]
> this CodePen : http://codepen.io/anon/pen/gxNxZw seems fine @wojtask9, isn't it ?

the popover bottom left lost his left border ??

**Comment by wojtask9** [comment]
@jipexu 
Something with popper position is wrong. I'm not sure what.

@alecpl 
my PR https://github.com/twbs/bootstrap/pull/23936 that should fix your issues

**Comment by Johann-S** [comment]
It seems https://github.com/FezVrasta/popper.js/pull/489 fixe this issue, so when @FezVrasta will ship a new release of Popper.js we'll close this issue :+1:

**Comment by FezVrasta** [comment]
Released as v1.12.8

**Comment by Johann-S** [comment]
The new release of Popper.js fixe only one part of this issue see : https://codepen.io/Johann-S/pen/qVXEaX

But IMO the first issue is on our CSS here (see the first Popover)

**Comment by FezVrasta** [comment]
yes, you still need to perform the changes I described [in this comment](https://github.com/twbs/bootstrap/issues/23846#issuecomment-327465549)
