### ISSUE TITLE
static form control inside jumbotron

### ISSUE THREAD

**Issue by QuantumHive** [twbs/bootstrap#23845]
See [this codepen](https://codepen.io/anon/pen/vJMqEV).

When using a [Readonly plain text form control](https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text) inside a [jumbotron](https://getbootstrap.com/docs/4.0/components/jumbotron/), the input element renders a white background:

![capture](https://user-images.githubusercontent.com/2554952/30097696-2263ff7e-92df-11e7-977b-dc1a0dbcbdc1.PNG)

I think the desired effect would be the same background-color as the jumbotron?

**Comment by andresgalante** [comment]
Hi @QuantumHive thanks for reporting this. I don't know if that is what we want. At the end of the day a readonly input is still an input. And as part of a form it should look like one.

[Here is where the background is set](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L55).

Now, for your usecase, if you want to remove the background you cadd add this to your code:

```css
input[readonly] {
  background: transparent;
}
```

If anyone else agrees that removing backgrounds from read only is a good idea, I can send a PR to fix it, but IMO it's not a desirable thing to have

**Comment by patrickhlauke** [comment]
the idea with the plain text readonly fields is to indeed make them look exactly like (or at least as close to as possible) regular text. This allows authors to have all the advantages of a proper `<label>`/`<input>` type pairing, while keeping a "cleaner" look that is often desired.

**Comment by andresgalante** [comment]
@patrickhlauke thanks for the input, I'll send a PR now with a clear readonly input.
