### ISSUE TITLE
Use the 'main' element in documentation and examples

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#23840]
Use the semantic `main` element rather than the ambiguous `div` element in the documentation and examples.

https://getbootstrap.com/docs/4.0/examples/

**Comment by andresgalante** [comment]
I'd add to this issue: Go full accessible for examples, add aria tags, roles and `main` too 😄

**Comment by vanillajonathan** [comment]
Also `nav` needs to be investigated.

**Comment by asuh** [comment]
Is there a reason only `<main>` has an aria role and not `<header>` or `<footer>`? Further, while I support aria roles, are there still screen readers in 2017 that do not know the implicit landmark roles by default? My impression is that, at least for landmark roles like for the elements above, explicit aria roles don't add anymore value.

**Comment by patrickhlauke** [comment]
IE11 doesn't understand/implicitly map `<main>` http://html5accessibility.com/

**Comment by asuh** [comment]
Neat site, good reference. Bookmarked!
