### ISSUE TITLE
Bootstrap 4 Beta not supporting "hidden-*-up" or "hidden-*-down"?

### ISSUE THREAD

**Issue by tejashapani** [twbs/bootstrap#23847]
Hello,

I had designed a mockup with Bootstrap 4.0 Alpha where i was using classes like "hidden-sm-down" and "hidden-sm-up"..

But i found that those classes are no more supported on Boostrap 4.0 Beta release?
What is the alternate solution for this?

Thanks

**Comment by jipexu** [comment]
hi please have a look here
#23475

**Comment by Johann-S** [comment]
Please before open an issue, make a quick search, see : https://github.com/twbs/bootstrap/issues/23475#issuecomment-322667498

thanks @jipexu

**Comment by ErikThiart** [comment]
The new way of doing it is a shit show.

Please bring back the v3 style of hiding elements.
