### ISSUE TITLE
Nested Modals

### ISSUE THREAD

**Issue by tshad** [twbs/bootstrap#23841]
I am really interested in this reason for not having nested modals.  

From your documention:

_Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences._

Sure - on a phone or twitter this may not work as well, but on a desktop where people do real work, they are really useful and necessary in some cases FOR a better user experience.  There are plenty of people online wanting this and have wanted it for years.  They have had to jump through hoops, in some cases, to get it to work. I got it to work but it isn't perfect as to having to use a settimer to handle the scrolling.

**Comment by mdo** [comment]
Still no plans to change anything on our end for this. I don't see a huge need for us to tackle anything here when you can swap out the content of a modal as you need with custom JS. If there's something I'm missing, I'd be happy to see a PR from someone or at least an issue with demo that'd better explain what's truly needed here.

**Comment by tshad** [comment]
Not sure why you closed this since someone my send an issue with this.

**Comment by rnowak8** [comment]
Use this to fix it

```
$(document).on('hidden.bs.modal', function() {
	if ($('.modal.show').length) {
		$('body').addClass('modal-open');
	}
});
```

**Comment by iamandrewluca** [comment]
```js
;(function() {
  // bootstrap/scss/_variables.scss -> $zindex-modal
  const zIndexModal = 1050

  jQuery(document).on('show.bs.modal', '.modal', function(e) {
    const visibleModalsCount = jQuery('.modal:visible').length
    const zIndex = zIndexModal + (100 * visibleModalsCount)
    jQuery(e.target).css('z-index', zIndex)
    setImmediate(function() {
      jQuery('.modal-backdrop')
        .not('.modal-stack')
        .first()
        // bootstrap/scss/_variables.scss -> $zindex-modal-backdrop
        .css('z-index', zIndex - 10)
        .addClass('modal-stack')
    })

  })

  jQuery(document).on('hidden.bs.modal', '.modal', function() {
    if (jQuery('.modal:visible').length) {
      jQuery.fn.modal.Constructor.prototype._checkScrollbar()
      jQuery.fn.modal.Constructor.prototype._setScrollbar()
      jQuery('body').addClass('modal-open')
    }
  })
})();
```
