### ISSUE TITLE
Bootstrap 4 beta is missing the "hidden" classes

### ISSUE THREAD

**Issue by ramiy** [twbs/bootstrap#23856]
The **beta version** [CSS file](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.css) is missing the [`hidden` classes](https://v4-alpha.getbootstrap.com/layout/responsive-utilities/).

All the `.hidden-*-up` and the `.hidden-*-down` classes should be in main CSS file, but they are not there.

**Comment by ramiy** [comment]
I should add that **alpha.6 version** [CSS file](https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.css) has all the `hidden` classes.

**Comment by Herst** [comment]
The removal has been mentioned at https://getbootstrap.com/docs/4.0/migration/

**Comment by ramiy** [comment]
@Herst Thanks for the clarification.

So we need to update the Docs - https://v4-alpha.getbootstrap.com/layout/responsive-utilities/

**Comment by jipexu** [comment]
as your link show (alpha) you are in the wrong doc ...

**Comment by ramiy** [comment]
Silly me...

:-)
