### ISSUE TITLE
Collapse arrows/signs

### ISSUE THREAD

**Issue by Ruffio** [twbs/bootstrap#23854]
The older Bootstrap (v. 3.) included glyphicon where arrows/signs (+/-) where located.

In v. 4 it would be nice to have some 'default' arrows/signs to easily configure so it is easy to see that it is a collapse and which state it is in.

**Comment by gijsbotje** [comment]
i made a pen a view days ago to explain how easy it is to make some sweet effects by only using pseudo classes
https://codepen.io/gijsbotje/pen/XaoYGY
it might be what you are looking for
(keep in mind that this is not pretty and was only for demonstration purposes (although i use the plus minus variant a lot))

**Comment by Ruffio** [comment]
@gijsbotje cool thanks. I will have a look at it.

**Comment by Ruffio** [comment]
The above simple way would be a good idea to show in the doc. Just to show how easily it can be done.
