### ISSUE TITLE
Add border utility classes

### ISSUE THREAD

**Issue by alizain** [twbs/bootstrap#23852]
For my own projects, I'm using a set of border utility classes, that significantly extend the current number of border utilities. With these classes, you can add or remove borders on any side individually (top, bottom, right, left) and the two axis (x, y) for all breakpoints.

Would you be interested in accepting a feature PR to include this into the main repo? Below are the classes it would add:

```css
.bt # border top
.bb # border bottom
.br # border right
.bl # border left
.by # border y-axis
.bx # border x-axis
.bt-off
.bb-off
.br-off
.bl-off
.by-off
.bx-off
.bt-sm
.bb-sm
.br-sm
.bl-sm
.by-sm
.bx-sm
.bt-sm-off
.bb-sm-off
.br-sm-off
.bl-sm-off
.by-sm-off
.bx-sm-off
# ...and so on and so forth
```

I initially had used `-on` and `-off` suffixes, but decided to remove them in favor of the `-0` approach used by bootstrap in other places. The downside is that the shorter, not breakpoint classes become a little too terse to be easily understandable. What do you think?

**Comment by andresgalante** [comment]
I would't want to see a class for each CSS property, that's what I hate about frameworks like [atomic CSS](https://acss.io/) or [tachyons](http://tachyons.io/).

But if you do want to do this, I suggest to use the same naming conventions as [border utilities](https://getbootstrap.com/docs/4.0/utilities/borders/). So `.border-` instead of `.b`

**Comment by alizain** [comment]
I would generally agree with your sentiment. However, I've found that borders are often as useful as the other utility classes present in bootstrap, significantly more so than any other set of CSS properties. In my own workflow, I find that if I'm doing anything more complex, it's a lot easier to specify it directly in CSS.

That being said, I would only want to include this in the main repo if the broader community found it useful enough. I leave that choice to you.

Also, I agree on using `.border-` instead.

**Comment by mdo** [comment]
We have some: https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_borders.scss.

No plans to add more just yet.

**Comment by jandever** [comment]
@mdo
Similar to the "border-0" classes, adding the following classes would be practical, though.

.border-top      { border-top: 1px solid $gray-200 !important; }
.border-right    { border-right: 1px solid $gray-200 !important; }
.border-bottom   { border-bottom: 1px solid $gray-200 !important; }
.border-left     { border-left: 1px solid $gray-200 !important; }

Ref: https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_borders.scss

**Comment by robsilva** [comment]
I really like the naming convention used by the spacing utilities, so I created this mixin to do the same with borders:

```
/* Border Mixin */

$positions: t r b l;
$sizes: 3;

@mixin borders($size) {
  	@each $x in $positions {
	    @if $x == t {
	    	.b-#{$x}#{$size} { border-top: #{$size}px solid rgba(0,0,0,0.1); }
		} @else if $x == r {
			.b-#{$x}#{$size} { border-right: #{$size}px solid rgba(0,0,0,0.1); }
		} @else if $x == l {
			.b-#{$x}#{$size} { border-left: #{$size}px solid rgba(0,0,0,0.1); }
		} @else if $x == b {
			.b-#{$x}#{$size} { border-bottom: #{$size}px solid rgba(0,0,0,0.1); }
		}
	}
	.b-#{$size} { border: #{$size}px solid rgba(0,0,0,0.1); }
}

@for $i from 1 through $sizes {
	@include borders($i);
}

```
which generates:
```
.b-t1 {
  border-top: 1px solid rgba(0, 0, 0, 0.1); }

.b-r1 {
  border-right: 1px solid rgba(0, 0, 0, 0.1); }

.b-b1 {
  border-bottom: 1px solid rgba(0, 0, 0, 0.1); }

.b-l1 {
  border-left: 1px solid rgba(0, 0, 0, 0.1); }

.b-1 {
  border: 1px solid rgba(0, 0, 0, 0.1); }

.b-t2 {
  border-top: 2px solid rgba(0, 0, 0, 0.1); }

.b-r2 {
  border-right: 2px solid rgba(0, 0, 0, 0.1); }

.b-b2 {
  border-bottom: 2px solid rgba(0, 0, 0, 0.1); }

.b-l2 {
  border-left: 2px solid rgba(0, 0, 0, 0.1); }

.b-2 {
  border: 2px solid rgba(0, 0, 0, 0.1); }

.b-t3 {
  border-top: 3px solid rgba(0, 0, 0, 0.1); }

.b-r3 {
  border-right: 3px solid rgba(0, 0, 0, 0.1); }

.b-b3 {
  border-bottom: 3px solid rgba(0, 0, 0, 0.1); }

.b-l3 {
  border-left: 3px solid rgba(0, 0, 0, 0.1); }

.b-3 {
  border: 3px solid rgba(0, 0, 0, 0.1); }
```
