### ISSUE TITLE
Problem printing pages on IE vs Chrome

### ISSUE THREAD

**Issue by tigermarques** [twbs/bootstrap#23864]
I'm having trouble designing my pages so that they can be printed consistently accross browsers. I noticed that bootstrap homepage (in v3) itself does not print the same way for Chrome and IE.

I'm on Windows 10, using Chrome 60 and IE 11. When I print Bootstrap home page, i get the following results:

Chrome:
![image](https://user-images.githubusercontent.com/15315098/30167628-e5ada570-93de-11e7-934b-787337e4bd68.png)

IE:
![image](https://user-images.githubusercontent.com/15315098/30167675-111a3868-93df-11e7-8e00-6c9f7198029c.png)

As it is possible to see, when printing in Chrome it is possible to fit a lot more into the page. This happens consistently for all pages built in Bootstrap. I've tested with v4 homepage and the issue still happens.

Is there a way to overcome this, or is this an issue?

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by tigermarques** [comment]
Hi,

Thanks for the quick response. As I said above, the issue also happens in Bootstrap v4. Here are the screenshots for Chrome and IE.

Chrome:
![image](https://user-images.githubusercontent.com/15315098/30168583-bee907ba-93e1-11e7-891d-d515b58a7a8f.png)

IE:
![image](https://user-images.githubusercontent.com/15315098/30168618-de0eeab0-93e1-11e7-8ee4-9a49e091ff00.png)

As it is possible to see, in Chrome it is possible to fit a lot more into the page than IE. If the issue can be solved (or if there is a workaround for it) in v4, one of the possibilities for me may be to use the situation to migrate the website to v4.

Thanks a lot!

**Comment by tigermarques** [comment]
@Johann-S , do you reckon this is an actual bug, or is there a workaround?
Thanks!

**Comment by XhmikosR** [comment]
@patrickhlauke: wasn't there a related issue?

**Comment by guptgar** [comment]
Were you able to find a fix for the issue?
 Thanks!
