### ISSUE TITLE
Add popover margin

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#23863]
Tooltip has margin ($tooltip-margin variable), which allows us to add spacing between element and tooltip.
But popover doesn't have this option despite both components use popper.js. Looks a bit inconsistent.
Is there a valid reason for this?

**Comment by Johann-S** [comment]
In both cases (Tooltip and Popover) you have the `offset` parameter which allow you to add some spaces see : 
https://getbootstrap.com/docs/4.0/components/tooltips/#options
https://getbootstrap.com/docs/4.0/components/popovers/#options

**Comment by Kopyov** [comment]
In this case why do we need margin option for tooltips?

**Comment by Johann-S** [comment]
it's a customisation for folks who prefer to do it in CSS

**Comment by Kopyov** [comment]
Would be nice to add $popover-margin variable for those folks then :) Looks inconsistent - both components have offset option, but only one of them allows you to change it in CSS

**Comment by mdo** [comment]
No plans to change this right now.
