### ISSUE TITLE
Incorrect Documentation Code for List Group Badge Example

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#23867]
Badges are not displaying properly on https://getbootstrap.com/docs/4.0/components/list-group/#with-badges

![screen shot 2017-09-07 at 12 50 41 pm](https://user-images.githubusercontent.com/2222751/30175306-0bd7a894-93cc-11e7-96eb-a60566239bd4.png)

**Comment by jipexu** [comment]
Hi
this was solved
