### ISSUE TITLE
Bootstrap cards are not working proper , issue with responsiveness

### ISSUE THREAD

**Issue by wholovedeep** [twbs/bootstrap#23871]
I am facing issue with bootstrap4 cards , even copy code from website , images are squeezing when m resizing window . 

code below --

<div class="card">
    <img class="card-img-top img-fluid" src="images/hom.jpg" alt="Card image cap">
    <div class="card-body pd-50">
      <h4 class="card-title">Decoration Services</h4>
      <p class="card-text"> Some text </p>
      <a href="decorations.php" class="btn btn-primary">Decoration Gallery</a>
    </div>
    </div>
![capture](https://user-images.githubusercontent.com/31743134/30179240-54401cc6-9429-11e7-966c-d90a58c20131.PNG)
![capture2](https://user-images.githubusercontent.com/31743134/30179241-54472854-9429-11e7-8d0d-b79b9661b01c.PNG)

**Comment by andresgalante** [comment]
Hi @wholovedeep I can't see the images that you've sent. Can you please test the docs first, resize your browser and look at it on a mobile device:
https://getbootstrap.com/docs/4.0/components/card/

If that doesn't show the issue, then it's a problem on your code and I can try helping you out if you send me a codepen or somewhere were I can see code.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by wholovedeep** [comment]
i have checked on code pen same code copied and pasted working fine on codepen but not on my page -- code pasted below code ping link is also there and my pages image are also attached.

`<div class="card">
  <img class="card-img-top img-fluid" src="images/hom.jpg" alt="Card image cap">
  <div class="card-body pd-50">
    <h4 class="card-title">Decoration Services</h4>
    <p class="card-text"> some text here
    .</p>
    <a href="decorations.php" class="btn btn-primary">Decoration Gallery</a>
  </div>
  </div> `

[https://codepen.io/wholovedeep/pen/QMXezM?editors=1000](url)

![capture](https://user-images.githubusercontent.com/31743134/30226914-5f5829a6-94f5-11e7-801b-df8e082f36a3.PNG)
![capture2](https://user-images.githubusercontent.com/31743134/30226915-5f598c74-94f5-11e7-9b1b-1493ded00fb9.PNG)

**Comment by andresgalante** [comment]
@wholovedeep your links don't work 😞  can you send the URLs please

**Comment by wholovedeep** [comment]
https://codepen.io/wholovedeep/details/JyQgLw

**Comment by wholovedeep** [comment]
One more confusion...  If we need to define width of card or its parent compulsory?? 

Because i think its occupying 100% width however i have not mentioned any width or its class for wdth.

**Comment by andresgalante** [comment]
This is not a Bootstrap bug or issue. If you need community support and help on how to use bootstrap you'll find it on the slack channel.

But to answer your questions: You have two type of elements: components and layout.

As a rule every component stretches to the size of it's container, and the layout will rule what space the component takes on the screen.

That's an expected and desired behaviour of any design system.

**Comment by mdo** [comment]
Closing per last comment.
