### ISSUE TITLE
Firefox: Strange blinking effect on select

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#23884]
Steps:
1. Using Firefox go to https://getbootstrap.com/docs/4.0/components/forms/#form-controls
2. Click on the first visible select element.

Result: The options list is open, but there's some effect that looks like the selected option is unselected and then selected again. Or just a delay between opening the list and selecting the item. A fast but visible blink.

This does not happen in Chrome. It also does not happen when you click a select element that is already focused.

**Comment by ursuleacv** [comment]
The same effect happens on the custom checkbox after selected. When moving the mouse away, you can see a blinking effect that covers a part of the checkbox. In Chrome 61, Windows. Haven't tested in other browsers. [image](https://www.dropbox.com/s/4mkcx7gryxs6lq3/bootstrap-checkbox.png?dl=0)

**Comment by XhmikosR** [comment]
What FF version?

**Comment by alecpl** [comment]
55.0.2

**Comment by XhmikosR** [comment]
Please try with v56 beta. I can't seem to reproduce with v56 here.

**Comment by asyncdesign** [comment]
This happens only after first focus on the non-multiple select element. Can be seen here, and is reproducible every time.
[(https://getbootstrap.com/docs/4.0/components/forms/#form-controls)]
Firefox 55.0.3 (32-bit)

**Comment by mdo** [comment]
This appears present even without Bootstrap. Closing as a Firefox issue.
