### ISSUE TITLE
Feature request: colored modals

### ISSUE THREAD

**Issue by aolko** [twbs/bootstrap#23887]
It would be great to have colored modals akin to colored alerts.

![](https://i.imgur.com/NUoFzGC.png)
(*Colored alert*)

**a)** With only the modal header background+border color
**b)** With the whole modal dialog background+border color
Possible bug: background-color removes the border-radius

![image](https://user-images.githubusercontent.com/581458/30212979-c2fd88fc-94af-11e7-88ca-fea601aa86c5.png)
(*Example of **(a)***)

**Comment by bkdotcom** [comment]
example a: just add two classes to modal-header:
   `<div class="modal-header bg-danger text-white">`

https://getbootstrap.com/docs/4.0/utilities/colors/
https://getbootstrap.com/docs/4.0/utilities/borders/

**Comment by aolko** [comment]
@bkdotcom Yes, your way pretty much works, yet promblem with border radius persists
 ![](https://i.imgur.com/KQJrhII.png)

**Comment by andresgalante** [comment]
@aolko I've fixed it here #23799

**Comment by mdo** [comment]
No plans for colored modals.
