### ISSUE TITLE
Navbar Right-Dropdown Alignment

### ISSUE THREAD

**Issue by Xcreen** [twbs/bootstrap#23889]
When align a dropdown to the right in a navbar, the dropdown-content goes out of the page.
v4 beta-example: https://jsfiddle.net/kh0sfpm8/

![bootstrap4nav](https://user-images.githubusercontent.com/26636443/30214732-c2b0ef9e-94ad-11e7-8afb-74b851891d10.jpg)

**Comment by Johann-S** [comment]
That's right because you want to align your dropdown to the right, so you just have to add `dropdown-menu-right` and everything is fine see : https://codepen.io/Johann-S/pen/gxNqrm
