### ISSUE TITLE
Button group with outlined buttons & dropdown does not round if dropdown is last

### ISSUE THREAD

**Issue by aolko** [twbs/bootstrap#23883]
![](https://i.imgur.com/DHev1to.png)
```html
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <a class="btn btn-outline-secondary" href="#" role="button" data-toggle="tooltip" title="Hide avatars"><i class="fa fa-eye-slash"></i></a>

  <div class="btn-group" role="group">
    <button class="btn btn-outline-secondary" type="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Mod tools"><i class="fa fa-cog"></i></button>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="#">Edit</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#mdlRemoveFeedItem">Remove</a>
    </div>
  </div>
</div>
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by aolko** [comment]
[Pen](https://codepen.io/aolko/pen/QMXxgB)
Bootstrap: v4.0.0-beta
Browser: Chrome v61 + all chrome-like
OS: Windows 10 v1703 (build 15063.540)

**Comment by andresgalante** [comment]
Hi @aolko you are missing the class `.dropdown-toggle` on `class="btn btn-outline-secondary dropdown-toggle"`

**Comment by aolko** [comment]
it is mandatory, but then what if i don't want `:after` arrow at all?

**Comment by andresgalante** [comment]
@aolko that's my point :) I though we should make the caret optional.

**Comment by aolko** [comment]
fixed the pen

**Comment by Johann-S** [comment]
they are a PR for that @aolko (make the caret optional)

**Comment by andresgalante** [comment]
Found it ! #22926
Thanks @Johann-S  😄

**Comment by mdo** [comment]
#22926 was merged, so closing.
