### ISSUE TITLE
Feature Request: Old Bootstrap Style with Border

### ISSUE THREAD

**Issue by FellowTuts** [twbs/bootstrap#23891]
Bootstrap 4 has changed the way blockquote used to appear, removed the border now. Wouldn't it be better to add extra classes there like `blockquote-left` and `blockquote-right` (replacement of `blockquote-reverse`) to retain the old bordered style.

If anyone wish to use the same blockquote styles Bootstrap 4 carried till alpha version, he/she can add these classes then like:

`<blockquote class="blockquote blockquote-left">`
    `<p class="mb-0">This blockquote has border to left.</p>`
`</blockquote>`

<blockquote class="blockquote blockquote-left">
    <p class="mb-0">This blockquote has border to left.</p>
</blockquote>

Further like colors provided in Beta 4, additional blockquote border-color classes can be added. For example, same as alert, `blockquote-right-success` for a green border to right of blockquote element.

**Comment by andresgalante** [comment]
You can do that with BS4 using `text-` utility classes:
https://getbootstrap.com/docs/4.0/content/typography/#alignment

**Comment by mdo** [comment]
No plans to revert back to old styles here.
