### ISSUE TITLE
Running Build Tools Error on htmllint

### ISSUE THREAD

**Issue by frogydiak** [twbs/bootstrap#23893]
- Mac OS X
- Chrome
- Boostrap 4 Beta 1

Running npm test and I get an error on:

> htmllint --rc build/.htmllintrc _gh_pages/*.html _gh_pages/**/*.html js/tests/visual/*.html

_gh_pages/index.html: line 171, col 32, attribute names must match the format: dash
_gh_pages/index.html: line 188, col 32, attribute names must match the format: dash
_gh_pages/index.html: line 207, col 32, attribute names must match the format: dash

So, I went ahead and edit build/.htmllintrc and changed:

`"attr-name-style": "dashed"`
to 
`"attr-name-style": false`

just to test if the default value of dashed is the issue then rerun npm test again and I got:

[htmllint] found 0 errors out of 13 files

Looking at _gh_pages/index.html on the lines that were pointed out, it is a class sizing **mb-2**. It looks good to me. Maybe the attr-name-style value should not be dashed?

Thanks!

**Comment by XhmikosR** [comment]
You probably use the beta and not the git version so you shouldn't report such issues regarding development tools with obsolete versions. This was fixed in v4-dev a long time ago.

**Comment by frogydiak** [comment]
@XhmikosR wow! I cloned the v4-dev branch, is that what you called the git version? And how  in the world would I know that it was fixed long time ago? Chill dude :) relax!

**Comment by bluedge** [comment]
FYI: I have the very same issue with the package downloaded directly from your website... "Download Source"

**Comment by XhmikosR** [comment]
Like I said, this is already fixed in the v4-dev git branch.

**Comment by jkd77** [comment]
maybe the branch offered for download via the website could link directly to the git repo zip...

**Comment by rafalp** [comment]
@jkd77 that way you would be crushed by support requests for unreleased features.

**Comment by XhmikosR** [comment]
Or, people could stop using zip files for development purposes. Remember, this task isn't related to the end users. It's about our docs.

**Comment by jkd77** [comment]
No offense meant team, there's just a lot of stuff to wade through with v4. I recognize the inherent difficulty of what to offer / explain and where. It can be frustrating to find these fixes. My Google-fu is only so powerful. Is searching this repo the best first resort?

**Comment by XhmikosR** [comment]
Yup, thanks.

**Comment by frogydiak** [comment]
@XhmikosR no offense man, if you don't have the skill or patience to support people then simply don't answer or simply be kind in answering. Can't you be kind in saying, please clone the v4-dev git branch instead of downloading the zip then try again.
