### ISSUE TITLE
Syntax error in popper.min.js

### ISSUE THREAD

**Issue by gobi004** [twbs/bootstrap#23900]
While working n Dreamweaver it shows that “there is syntax error at popper.min.js file at line number 1, code hinting may not work until fix the error”. why its shows like this. not only single file i’ve tested,and tested with 3-4 websites.In previous versions i didn’t see this error in current version only am seeing.

**Comment by mdo** [comment]
Sorry, can't help you with Dreamweaver's errors here. We don't use it and it doesn't sound related to our code, so closing out.

**Comment by mdo** [comment]
Please try StackOverflow or our Slack if you need to reach out to folks, or the Popper repo.
