### ISSUE TITLE
'form-check-input' class on input tags really necessary?

### ISSUE THREAD

**Issue by bremussolutions** [twbs/bootstrap#23902]
Hi,

I implement custom tag helpers for all the bootstrap (v4.0) controls and components on .NET MVC Core. There is a massive problem with additional css classes in `<input type='checkbox' />` items. You add a 'form-check-input' class to each checkbox. By the way, not in Bootstrap v3.x, that was substantial better for a tag helper developer.

Is this class really necessary? Is it not possible to drop this class and style the item with inherit styles?

**Comment by mdo** [comment]
With v4, we moved from forced HTML in our selectors to classes wherever possible. This allows a bit of flexibility in our components at the cost of more required classes. We think it's a valuable trade-off, but there's also a balancing act. We'll keep it in mind for v5.
