### ISSUE TITLE
Remove Tether dependency/requirement

### ISSUE THREAD

**Issue by jony89** [twbs/bootstrap#23905]
`Tether` library is not maintained anymore, as declared under project status: https://github.com/HubSpot/tether

A library big as `bootstrap` should not have as a requirement a non-maintained library.

They do not even approve PRs anymore. I've created a PR for `Tether` while ago and got no answer.  ( https://github.com/HubSpot/tether/pulls ) 
The project was not updated for more than 5 months.

Under `Tether` documentation, the suggest to move to Poper : 

https://github.com/FezVrasta/popper.js

**Comment by wolfy1339** [comment]
This is already done in 4.0.0-beta

**Comment by jony89** [comment]
cool.
