### ISSUE TITLE
Bootstrap not good in Ultra HD monitor

### ISSUE THREAD

**Issue by asas111111** [twbs/bootstrap#23901]
In Ultra HD(3840 pixel x 2160 pixel)，All of things are too small。

**Comment by Herst** [comment]
I beg your pardon but our crystal ball is out of order ATM.
Could you please give us some more information, e.g. browser, browser version, OS, zoom factor, default font size, …?

**Comment by patrickhlauke** [comment]
There are currently no plans to make any specific styles for these sorts of high resolutions.
