### ISSUE TITLE
Custom Dividers Between Inline Lists

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#23910]
A popular pattern on the web are inline lists with dividers.  Take these two lists for example:
### A list with a "|" divider:
![screen shot 2017-09-10 at 11 02 25 am](https://user-images.githubusercontent.com/2222751/30250336-752e566c-961a-11e7-8e68-a23a40d7b8d0.png)
### A list with a "·" divider:
![screen shot 2017-09-10 at 11 22 57 am](https://user-images.githubusercontent.com/2222751/30250339-823ce10c-961a-11e7-8769-a82f568c21d8.png)

Does anyone else feel like this could be of value?

**Comment by tmorehouse** [comment]
You can to this with custom CSS to select all but the last child and use an `::after` psuedo element to set the content (i.e. `"|"`), similar to how breadcrumbs add a divider element.

**Comment by LarryAzevedo** [comment]
Yup, I'm aware of that.  It would just be nice to have a variable; similar to`$breadcrumb-divider:` that you could set in the _variables.scss file.

**Comment by andresgalante** [comment]
@LarryAzevedo This is a popular use case, but I think this should live in the user's code. In my opinion most of the times you'd want that diver to be a CSS border and not a generated content.

**Comment by mdo** [comment]
Yup, this isn't something we'll tackle on our end.

**Comment by mdo** [comment]
Closest we could get would be some nav-focused additions to our in-repo examples.

**Comment by andresgalante** [comment]
@mdo cool, let me know if I can help building those examples
