### ISSUE TITLE
Modal backdrop displays over modal in fixed container

### ISSUE THREAD

**Issue by Cronkan** [twbs/bootstrap#23916]
Having a "main-container" with 
``` 
.app-container {
     position: fixed;
     top: 0;
     right: 0;
     bottom: 0;
     left: 0;
     overflow-y: auto;
 }
```
```
<div class="app-container">
  <div class="modal">
....
   </div>
</div>
```
Makes the backdrop position above the modal, blocking everthing.

Plunker: https://plnkr.co/edit/8JvG9eje5FDssHykPwW8?p=preview 
(With `angular` where `modal.html` and `modal.ts` has code for autoopening modal and `app.ts` and `app.scss` has template for main window)

**Edit** Seems like using `.appendTo('body')` when opening modal is a workaround, i.e `$('#exampleModal').appendTo('body').modal('show');`

**Comment by solaomosola** [comment]
This also happens in ReactJs, once the modal window and backdrop are visible, and you navigate off the current page using the back button, the modal window disappears but the backdrop stays, thereby blocking access to everything else.

**Comment by ysds** [comment]
This issue is a duplicate of #20433 or #3217.

Also in [docs](http://getbootstrap.com/docs/4.0/components/modal/#how-it-works):
> Modals use position: fixed, which can sometimes be a bit particular about its rendering. Whenever possible, place your modal HTML in a top-level position to avoid potential interference from other elements. You’ll likely run into issues when nesting a .modal within another fixed element.

Another workaround is add `z-index: 1050` to your `.app-container`.

**Comment by ysds** [comment]
And related #25206. I believe #16432 will be reopen.

**Comment by ysds** [comment]
Yes, the workaround in my previous comment will fix:

> Makes the backdrop position above the modal, blocking everthing.

but your issue will not be fixed:

> and you navigate off the current page using the back button, the modal window disappears but the backdrop stays,

**Comment by steve3d** [comment]
well, I'm pretty sure, even if all the parent of the `div.modal` has `position: static`, this will happen very often.

**Comment by MartijnCuppens** [comment]
@ysds summarizes this nicely in his comment: https://github.com/twbs/bootstrap/issues/23916#issuecomment-364618947

Closing this.

**Comment by devt3000** [comment]
Hey, i just realized i was getting this issue because i had another package installed (https://www.npmjs.com/package/bulma) that was overriding bootstrap styling.

**Comment by VelkanGk** [comment]
> **Edit** Seems like using `.appendTo('body')` when opening modal is a workaround, i.e `$('#exampleModal').appendTo('body').modal('show');`

Was the best solution so far. The button that triggers the modal must be changed to a click action with a function containing the lines above.

**Comment by joshmoto** [comment]
```
<script>
     $('#exampleModal').appendTo('body');
</script>
```

I added this directly after my modal, and the modal html was being loaded in via ajax, so as soon as my ajax html loaded, all my modals stacked nicely before the closing tag of the modal.

**Comment by overtebay-api** [comment]
https://universal-analytics-ryle.github.io/3eUm3cV9BoL3lxwKWhVTDZBTfSiHd8873kMqJap0Xdk41LfcyH4bXJNdH4mjts/



Look this way
