### ISSUE TITLE
Bug with column-width and form elements

### ISSUE THREAD

**Issue by tamtakoe** [twbs/bootstrap#23913]
There are some container widths when parts of form elements are cuted:

![Image of Yaktocat](https://image.prntscr.com/image/xoPCqvJwRCOiIfZIr0ZwkQ.png)

https://plnkr.co/edit/vyAsUAJiEwcPD1ipbPad?p=preview

All Bootstrap versions

**Comment by asyncdesign** [comment]
This is not a bug in Bootstrap. Although it could be a useful feature, Bootstrap is not really designed that way.

If you do want the container to be 300px wide in total, giving you 2 x 150px columns for all screen sizes, you can do the following:
				.container-fluid {
					max-width: 300px;
				}
				.col-sm-6 {
					flex: 0 0 50%;
					max-width: 50%;
				}
However, you might want to wrap these in a media query, depending on the screen sizes you want to include. If you only want that layout for small screens you could do:

			@media (max-width: 576px) {
				.container-fluid {
					max-width: 300px;
				}
				.col-sm-6 {
					flex: 0 0 50%;
					max-width: 50%;
				}
			}
