### ISSUE TITLE
Is this correct  rendering collapsed menu on mobile?

### ISSUE THREAD

**Issue by kolkov** [twbs/bootstrap#23915]
![image](https://user-images.githubusercontent.com/3740898/30272377-e95ace52-96fc-11e7-952c-5caea31db544.png)
![image](https://user-images.githubusercontent.com/3740898/30272388-f90a8d56-96fc-11e7-8af3-88231b2f051b.png)

**Comment by Johann-S** [comment]
maybe we should add some styles when dropdown are in a dark navbar 🤔

**Comment by andresgalante** [comment]
I've started working on this one today. Fixing it means lot of overwrite and context selectors under `navbar`.

@mdo What do you think? Is it worth it?

**Comment by andresgalante** [comment]
@kolkov @Johann-S I was working now on this issue and I got it to work:

![Dark dropmenu](http://g.recordit.co/JNGWbzL7QH.gif)

But the amount of high specificity code needed to achieve it for every breakpoint renders it pointless in my opinion. 

I think this is something that can live in users code base. I like the idea of keeping the drop menu styles isolated from the navbar as a separate component, I think it's really smart.

@mdo If you think we should pursue the idea of a dark theme drop menu on navbar, let me know and I'll PR it.

**Comment by Johann-S** [comment]
IMO if this is accepted we'll have to do the same for `primary` navbar 🤔
Btw awesome work as always @andresgalante

**Comment by andresgalante** [comment]
@Johann-S if we do the same for primary, it might make things a bit less better. Let me try that and PR it so you guys can evaluate the code needed

**Comment by mdo** [comment]
Closing this issue out because it is intended. I'll leave the PR open though for now to see if we should revisit this and add the extra CSS for it. My gut says no, but I'm open to more feedback.
