### ISSUE TITLE
Form validation classes has-danger/form-control-danger stop working after update from alpha to beta.

### ISSUE THREAD

**Issue by ppazos** [twbs/bootstrap#23925]
I was using has-danger/form-control-danger classes documented [here](https://v4-alpha.getbootstrap.com/components/forms/#examples) to have the visual effect of validation on inputs (it shows a nice icon in the field).

After updating to beta, those classes stop to work and I couldn't see any red borders or icons on my inputs. Reading the [new 4.0 documentation](https://getbootstrap.com/docs/4.0/components/forms/#validation) I couldn't find the classes aforementioned, but a new is-invalid class. That works showing the red border but doesn't show the icon on the input.

Not sure why those classes were removed.

Is there a way to use the has-danger/form-control-danger on the beta version?

**Comment by andresgalante** [comment]
You can read more about that on this issue #22762

**Comment by shrosterneduryden** [comment]
Jesus Christ! 
**Update the documentation!** 
I spent ages tearing my hair out as to why this wasn't working.

**Comment by katrinluethi** [comment]
Could you please specify what was the outcome (why is this issue closed)? From the linked issue, it is not clear at all whether you decided to stop with this functionality or whether you are still fixing it. (Icons are not the problem!)

**Comment by mdo** [comment]
@shrosterneduryden @katrinluethi See https://github.com/twbs/bootstrap/pull/22395 for full context on the change—that's the PR where we introduced the new form validation method. Independent of the wrong issue/PR being referenced here, you need to be mindful of the release you're using, the docs matching that version of the docs, and you need to [read the migration docs page](https://getbootstrap.com/docs/4.0/migration/).
