### ISSUE TITLE
bootstrap 3 demo errors

### ISSUE THREAD

**Issue by peter-mumford** [twbs/bootstrap#23928]
There are a bunch of errors on the Bootstrap 3 page. See screenshot.
![image](https://user-images.githubusercontent.com/31707793/30340892-0a981532-97c2-11e7-8a83-01e7ede87c71.png)

**Comment by patrickhlauke** [comment]
images needs their initial slash removed (e.g. "/assets/img/expo-lyft.jpg" > "assets/img/expo-lyft.jpg")

**Comment by XhmikosR** [comment]
If anyone makes a PR please CC me.

**Comment by patrickhlauke** [comment]
any hints where these files (old docs) actually live in the repo?

**Comment by XhmikosR** [comment]
It's the master branch I believe.

**Comment by lucascono** [comment]
@mdo has closed the last PR as fixed. Is help still needed?

**Comment by peter-mumford** [comment]
No more broken images.. there is still an https error and a 404 from a missing .swf file.

**Comment by mdo** [comment]
No more errors for me.
