### ISSUE TITLE
Navbar responsive state is broken

### ISSUE THREAD

**Issue by andresgalante** [twbs/bootstrap#23926]
The navbar is broken on `v4-dev` on a mobile size :

![screen shot 2017-09-12 at 1 41 01 pm](https://user-images.githubusercontent.com/1832037/30337927-45d4ad9c-97c0-11e7-9ae1-8eb395c99d43.png)

it was introduced on this PR: https://github.com/twbs/bootstrap/pull/23652

`flex-grow: 1` makes element to grow, it will not wrap.

I am working on it, finding a solution that also works on IE, I'll send a PR soon

**Comment by Fouzyyyy** [comment]
Hi @andresgalante, 

I would like to work on this one. I tried to reproduce it but I couldn't. Could you tell us more about this behavior? browser? version?

**Comment by andresgalante** [comment]
@Fouzyyyy sorry, I've already sent a PR, you can review it, the bug is on IE10
