### ISSUE TITLE
missing css from _forms.scss in latest beta

### ISSUE THREAD

**Issue by FLasH3r** [twbs/bootstrap#23920]
In the documentation page for checkboxes & radios ([checkboxes-and-radios](https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios))

inspect any checkbox or radio and you will see under 
`.form-check-input` it contains `&:only-child {
    position: static;
  }`

When getting the latest beta, it's missing - couldn't find it in any other branch

**Comment by mdo** [comment]
It's here:

https://github.com/twbs/bootstrap/blob/404c1a37acdf3689bb38f9f73f289d97fd434a2a/scss/_forms.scss#L213-L248
