### ISSUE TITLE
.container-fluid has two width:100%

### ISSUE THREAD

**Issue by weilinzung** [twbs/bootstrap#23924]
`.container-fluid {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 15px;
    padding-left: 15px;
    width: 100%;
}`

latest v4 beta!

**Comment by andresgalante** [comment]
This is the output of `v4-dev` branch:
https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L631-L637

If there was a bug on beta, it is fixed now
