### ISSUE TITLE
Different fieldset rendering with "form-group row" class between Chrome and Firefox

### ISSUE THREAD

**Issue by ocvirksimon** [twbs/bootstrap#23934]
Hello guys!

OS: Ubuntu
Browser: Firefox (55.0.2) and Chrome (58.0.3029.110)
Bootstrap version 4.0.0-alpha6 -> upgraded to 4.0.0beta

Through development, we have noticed different form rendering between Firefox and Chrome. 

Fieldset in Firefox is shown correctly, as the label and the input are in the same line positioned. In Chrome, label and input are in 2 rows. We tried to upgrade from the alpha version to the newest beta, but that didn't solve the issue. 

Here is also a JS Bin link (try to open it with Firefox and Chrome):
https://jsbin.com/niyebut/edit?html,output

**Comment by wojtask9** [comment]
This is browser bug.
You cannot use `fieldset` and `display:flex` in Chrome.

For details see https://stackoverflow.com/questions/28078681/why-cant-fieldset-be-flex-containers
