### ISSUE TITLE
`.bd-search-docs-toggler` appearance

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23939]
@mdo: Not sure if this is something new, or if you wanted this, I just noticed it:

![nav-btn](https://user-images.githubusercontent.com/349621/30378110-c8419c9c-989a-11e7-973b-8f0ad905edd0.png)

On hover the button border goes away too.

**Comment by Johann-S** [comment]
is it on our hosted documentation or on our repository documentation ?

**Comment by XhmikosR** [comment]
@Johann-S: happens in v4-dev not the live site.

Now that I look at it, it seems a regression from cd22eb1da03d5dbc9062ad5c9e75c05429e4bcd0

**Comment by mdo** [comment]
I think we're missing the `.btn` base class?

**Comment by XhmikosR** [comment]
Damn, spot on @mdo. I made #23942
