### ISSUE TITLE
when ajax loading tab content into tab-pane, clicking tabs results in more than one visible pane

### ISSUE THREAD

**Issue by WebDragon** [twbs/bootstrap#23931]
there seems to be some sort of ajax timing issue that is causing the tab-pane to not have its active class removed after a few clicks on the tabs, and shortly you have two or even three visible panes.

[CodePen illustrating the problem](https://codepen.io/anon/pen/KXKvKO)
[CodePen with 'solution' of manually removing the previously active element](https://codepen.io/anon/pen/gGOgPR)

when not ajax-loading the pane's content, the problem does not occur.

**Comment by xnkjdxyql** [comment]
got it~

**Comment by Johann-S** [comment]
I forked your CodePen and use our last dist files and your issue will be fixed in our next release see : 
https://codepen.io/Johann-S/pen/veYVKw
