### ISSUE TITLE
missing rem unit of line-height in .btn class

### ISSUE THREAD

**Issue by blue-eyed-devil** [twbs/bootstrap#23933]
Seems like measure unit for `line-height` property of `.btn` class, in buttons.scss on line 8 is missing.

    .btn {
        display: inline-block;
        font-weight: 400;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        border: 1px solid transparent;
        padding: .5rem .75rem;
        font-size: 1rem;
        line-height: 1.25;
        border-radius: .25rem;
        transition: all .15s ease-in-out;
    }

**Comment by mdo** [comment]
Not needed—the default unit here is `em`, so it can be safely dropped.
