### ISSUE TITLE
sass compiled error in bootstrap 4

### ISSUE THREAD

**Issue by Codingba** [twbs/bootstrap#23944]
Hi, i have this error when compiled bootstrap files:
error bower_components/bootstrap/scss/_variables.scss (Line 167: $color: 'theme-color("primary")' is not a color for `darken'. 
I use windows 10 and complies files with --watch.
How fix this. Thanks.

**Comment by andresgalante** [comment]
What version of sass do you have?

**Comment by XhmikosR** [comment]
Works fine for us with node-sass and the version you see in https://github.com/twbs/bootstrap/blob/v4-dev/package-lock.json#L2874

Closing this, but someone else might help you anyway. Otherwise ask on StackOverflow.

**Comment by Codingba** [comment]
sass version is 3.5.1 (Bleeding Edge), i don0t write any code, i only try compiled files and get error

**Comment by jgacuca567** [comment]
@Codingba what's your **bootstrap version**, **node-sass** version

**Comment by Codingba** [comment]
i use bower latest version

**Comment by jgacuca567** [comment]
@Codingba `bower` support will be dropped soon, `npm ` is preferred.
