### ISSUE TITLE
.d-sm-none not working? 

### ISSUE THREAD

**Issue by tmilgron** [twbs/bootstrap#23947]
The first col on the biggest row got the .d-sm-none class but doesn't works. In fact, the col appears right in sm, but doesn't display in the another responsive classes. I'm using the CDN, not the files.

> <body>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 color5 borde">
				header
			</div>
		</div>
		<div class="row">
			**<div class="d-sm-none col-sm-6 col-md-3 color1 borde"> Left </div>**
			<div class="col-sm-6 col-md-6 color2 borde"> Content </div>
			<div class="col-sm-12 col-md-3 color3 borde"> Right </div>
		</div>
		<div class="row">
			<div class="col col-sm-12 color4 borde"> footer </div>
		</div>
	</div>
</body>

**Comment by mdo** [comment]
All responsive utilities _start_ at that viewport and apply to every viewport on up until overridden again. You'd want to add `d-sm-none d-md-block` or something to that effect.
