### ISSUE TITLE
Section headings in documentation

### ISSUE THREAD

**Issue by RichCaloggero** [twbs/bootstrap#23952]
## Section headings in documentation

I'm seeing the following pattern used throughout these doc pages for section titles:

```
<h2 id="important-globals">
<a class="anchorjs-link " href="#important-globals" aria-label="Anchor link for: important globals" data-anchorjs-icon="?"
 style="font-family: anchorjs-icons; font-style: normal; font-weight: normal; font-size: 1em; line-height: inherit; font-size-adjust: none; font-stretch: normal; font-feature-settings: normal; font-language-override: normal; font-kerning: auto; font-variant: normal; position: absolute; margin-left: -1em; padding-right: 0.5em;">
</a>Important globals
</h2>
```

Screen reader users see the text "Important globals" repeated twice (i.e. via the `aria-label`); sighted users do not see the contents of `aria-label`. Worse, we get even more noise from the extraneous "Anchor link for: " in the `aria-label`. 
The effect is that each section title looks something like this:

>Anchor link for: important globals
Important globals

P{lease remove the `aria-label` from all of these section headings; it is not needed, and severely degrades readability for all screen reader users!

Thank you.

**Comment by XhmikosR** [comment]
We use [anchor.js](https://github.com/bryanbraun/anchorjs) for the anchors.

/CC @bryanbraun

**Comment by bryanbraun** [comment]
@XhmikosR, I've put together a fix upstream at https://github.com/bryanbraun/anchorjs/pull/90. I'll merge it in the next couple of days unless anyone objects.

**Comment by XhmikosR** [comment]
@bryanbraun; LGTM, thanks!

I'll wait for a new patch release so that I update anchor.js here.

**Comment by bryanbraun** [comment]
@XhmikosR, version `4.1.0` is published and up on github / npm.

**Comment by XhmikosR** [comment]
@bryanbraun: thanks! I'm gonna make a PR now.
