### ISSUE TITLE
The bottom of truncated headings text is not visible

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#23956]
When I use a bootstrap heading with `text-truncate`, the bottom of text is not visible.

![image](https://user-images.githubusercontent.com/4065765/30462553-562322a8-9a01-11e7-8535-e60e71cf2525.png)

jsfiddle: https://jsfiddle.net/qx1b4sLu/

I know how to fix it (make line-height equal or larger than font-size). However, I think that it will be very useful if it is defined by default when heading and text-truncate are used together.

**Comment by mdo** [comment]
Yeah we should increase the `line-height`. Hoping `1.25` or similar works?

**Comment by ysds** [comment]
@mdo 
In my case, I overwrote `line-heght` to `1.3` like:

```sass
h1, h2, ..., .h6 {
 &.text-truncate {
    line-height: 1.3;
  }
}
```

However, top and bottom space of these headings are slightly different from other headings that doesn't have `text-truncate` class (= line-height: 1.1). Unfortunately I have no idea to make them the same height.
