### ISSUE TITLE
Overriding all variables after Bootstrap partials are imported

### ISSUE THREAD

**Issue by mseymour** [twbs/bootstrap#23950]
I've been trying to wrack my head around this issue for a while now and can't seem to find a concise solution. I want to override variables in Bootstrap (v4 beta) while also using other defined variables afterward, but I would prefer not to import every item and insert my `modules/_boostrap-variables` partial after `~bootstrap/scss/variables`.

What would be the best solution for this? If needed, I can import all Bootstrap partials manually, but (at the moment) is not preferred.

**Comment by felipelomeu** [comment]
```
// Custom Variables
//
@import '_improvements'; // your improvements, like spacers, sizes
@import '_variables'; // your variables like color system, fonts definition, etc, without !default

// Bootstrap
//
@import '../../bootstrap/scss/bootstrap'; // all bootstrap .scss or you can add each one below

// Theme
//
@import '_theme'; // your theme

```

**Comment by mdo** [comment]
Docs are updated in `v4-dev` branch for this, and the above comment should help. Also see #23611.
