### ISSUE TITLE
Can't find _custom.scss file

### ISSUE THREAD

**Issue by kooltechboy** [twbs/bootstrap#23968]
I have installed bootstrap using the bower install however, I have failed to find the _custom.scss file.  I am using a mac latest OS. help is needed can you please help ?

**Comment by Johann-S** [comment]
you have to create this file on your own

**Comment by jgacuca567** [comment]
@kooltechboy `bower` is no longer supported, use either  **npm**

**Comment by pandaa880** [comment]
Hi, i am a newbie here.. I created the file and then override the variables but it didn't make any change in my page. 
What am i missing here ?
Help me out plz.
