### ISSUE TITLE
sidenav fixed in bootstraps main website

### ISSUE THREAD

**Issue by Janatbek** [twbs/bootstrap#23960]
Hi all, 
would it be helpful to have side nav that stays in the right-side of the website to be fixed?
![capture](https://user-images.githubusercontent.com/16279325/30495629-01ed0d80-9a0a-11e7-87db-443e91d5582c.PNG)

The documentation is a very long list and I have to scroll up to read about another component. I am talking about this element on the page : `<nav class="bd-links" id="docsNavbarContent">`
or at least to have scroll up button.

**Comment by andresgalante** [comment]
Maybe I am missing something, but it is fixed.

**Comment by Janatbek** [comment]
https://v4-alpha.getbootstrap.com/components/alerts/
let's say you are on this page and you continue to read. 
The side nav moves to the top of the page. and if I want to navigate to another component I have to scroll all the way up and find side nav.

**Comment by andresgalante** [comment]
You are in the wrong place :) here are bs4 docs now: http://getbootstrap.com/

**Comment by Johann-S** [comment]
closed thanks to @andresgalante comment's, please use our new documentation 👍

**Comment by Janatbek** [comment]
Oh thanks, didn't know about that page
