### ISSUE TITLE
can't @extend any utility classes

### ISSUE THREAD

**Issue by stoplion** [twbs/bootstrap#23964]
I've noticed that I can't `@extend` any utility classes. 
It will break if I include the following:

`application.scss`

```
@import '~bootstrap/scss/bootstrap.scss';

.header {
  @extend .navbar; //works
  @extend .navbar-inverse; //works
  @extend .bg-primary; //works
  @extend .navbar-dark; //breaks
  @extend .navbar-expand-lg; //breaks
}
```

**Comment by andresgalante** [comment]
Hi @stoplion I've tested it and I can extend everything but `@extend .navbar-inverse;`

Can you please check again and see if you find the same as I do so I can try fixing it.
