### ISSUE TITLE
Customization Options docs could be clearer about variable overrides

### ISSUE THREAD

**Issue by ianbrandt** [twbs/bootstrap#23963]
The [customizing options doc](https://getbootstrap.com/docs/4.0/getting-started/options/#customizing-variables) says:
> Every Sass variable in Bootstrap 4 includes the !default flag, meaning you can override that default value in your own Sass **_even after that original variable’s been defined_**. Copy and paste variables as needed, modify the values, remove the !default flag, and recompile.

I read this to mean that I can override variables in my Sass _after_ importing bootstrap.scss:

```
@import "../../node_modules/bootstrap/scss/bootstrap.scss";
@import "my-overrides"
```

_my-overrides.scss:

```
$link-color: map-get($my-colors, link);
```

Per the [Sass docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Variable_Defaults___default) for `!default` variables:

> ...if the variable has already been assigned to, it won't be re-assigned, but if it doesn't have a value yet, it will be given one.

So really, I have to do overrides _before_ Boostrap imports _variables.scss:

```
@import "my-overrides"
@import "../../node_modules/bootstrap/scss/bootstrap.scss";
```

I think the docs could be a little clearer in this regard.

**Comment by andresgalante** [comment]
@ianbrandt I agree with you. Do you want to send a PR to fix it? If not I can send it for you

**Comment by Bobeta** [comment]
@ianbrandt I read it the same way as you and sent a PR

**Comment by mdo** [comment]
This has been updated and more is coming in #23611.

**Comment by ianbrandt** [comment]
Thanks, all!
