### ISSUE TITLE
The navbar of bootstrap v4.0 shifts on opening a dropdown component.

### ISSUE THREAD

**Issue by himanshukhosla123** [twbs/bootstrap#23976]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://validator.w3.org/nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible
![screenshot 193](https://user-images.githubusercontent.com/16256021/30519745-4cf204a4-9bbb-11e7-9a8f-42918404de35.png)
![screenshot 194](https://user-images.githubusercontent.com/16256021/30519746-4cf7fcb0-9bbb-11e7-8e2f-51556740716e.png)

**Comment by andresgalante** [comment]
Hi @himanshukhosla123 I can't duplicate it, can you send more info please?

**Comment by himanshukhosla123** [comment]
Hi @andresgalante  I couldn't figure out the problem in that dropdown , but whenever the dropdown-menu is visible/open , the navbar shifts by some space and when i closes the dropdown-menu its gets aligned back to the top . please try it on website to detect the bug as it is a huge version launch of bootstrap 4.x

**Comment by andresgalante** [comment]
I am trying it here https://getbootstrap.com/docs/4.0/components/dropdowns/ and I can't duplicate it.

What browser/OS ?

**Comment by himanshukhosla123** [comment]
yes , when you mentioned what browser , then i tried it on my computer browser's , it works fine on firefox, edge , but it has an issue with google chrome -- 56.0.2924.87

**Comment by michaelkrieger** [comment]
Please provide your nav code

I've seen this if drop down-menu is not nested within the drop down. For example the dropdown-toggle isn't within the dropdown (such as it being outside the div for the drop down)

Not 100% based on your example where you're seeing the problem but basically make sure your toggle or dropdown itself is within the dropdown div.  if it's outside, it does cause that behaviour.


So it should be

(Nav)
  (Navbar toggler)
  (Navbar collapse)


And for drop downs for second level menu (as a part of nav), note the dropdown menu is within the dropdown div. a common mistake is to put it beside it which will cause that to happen.
  

                                <li class="nav-item">
                                    <div class="dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownB" data-toggle="dropdown" aria-expanded="false" aia-haspopup="true">Main category</a>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownB">
                                            <a class="dropdown-item" href="#">Overview</a>
                                            <a class="dropdown-item" href="#">Second</a>
                                            <a class="dropdown-item" href="#">Third</a>
                                        </div>
                                    </div>
                                </li>

**Comment by mdo** [comment]
This looks like the Chrome box-shadow problem with `position: sticky` on non-retina monitors. Nothing we can do here—I spent far too much time hacking solutions at GitHub for the same problem on our PRs. Closing out.
