### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by Ashikpaul** [twbs/bootstrap#23971]
For the below link the styling is missing.

http://getbootstrap.com/docs/4.0/examples/

![image](https://user-images.githubusercontent.com/17526871/30518108-d03e41a8-9b91-11e7-91f0-85d9723c3773.png)

**Comment by Johann-S** [comment]
Sorry I don't see that on Chrome (60.0.3112.113) with Win10

**Comment by Ashikpaul** [comment]
The link has "http". When its "https" it works fine. Sorry, I should have checked.
