### ISSUE TITLE
Popover jumps down

### ISSUE THREAD

**Issue by vadimil** [twbs/bootstrap#23980]
**Description**
The popover jumps down when opening it while scroll bar is moved down

1. Open and close popover 
2. Make the window's height shorten so the scroll bar appears 
3. Move the scroll bar down
4. Open popover again

**Expected result:** Popover to be opened and stick to the header
**Actual result:**     Popover jumps down

![image](https://user-images.githubusercontent.com/20092862/30522064-c8b38e70-9bd2-11e7-8962-983f3925005c.png)

![image](https://user-images.githubusercontent.com/20092862/30522163-48401efa-9bd4-11e7-8161-b0eb608a3a9b.png)

________CSS_______
.launcher-popover {
  background-color: @app-launcher-color;
  border-radius: 0;
  padding: 10px 0 10px 10px;
  margin-left: -10px;
  border: none;
  position: fixed;

  .popover-content {
    padding: 0;
    margin-right: 0;
  }

  .arrow:first-of-type:after  {
    border-bottom-color: @app-launcher-color;
    margin-left: -13px;
    height: 12px;
  }
  .arrow:first-of-type {
    border-bottom-color: transparent;
  }
  .app-link {
    width: 96px;
    height: 126px;
    color: #ffffff;
    font-size: 11px;
    border-radius: 3px;
    display: inline-block;
    margin-right: 10px;
    font-family: opensans;
    &:hover {
      background-color: @app-launcher-hover;
      text-decoration: none;
    }
    .app-icon {
      width:50px;
      height: 50px;
      display: inline-block;
      padding: 25px 25px 15px 25px;
    }
    .app-launch{
      margin-top: 10px;
      width: 95px;
      text-align: center;
    }
    .app-name{
      width: 95px;
      text-align: center;
    }
    .app-name:hover, .app-name:focus {
      text-decoration: none;
    }
  }

}

--------------  Additional details ----------------------
- Bootstrap Version: 3.3
- Chrome
- Windows 7

**Comment by coderundebug12** [comment]
a

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
