### ISSUE TITLE
Carousel within nav pills tab conflicts

### ISSUE THREAD

**Issue by TobiasKrais** [twbs/bootstrap#23983]
**Version:** bootstrap 4 beta
**Browser testet:** Chrome, Firefox
**OS tested:** Windows 10, Ubuntu 16.04
**Reduced test case:** https://www.design-to-use.de/carousel-tab-bug.html
**Steps to reproduce:** In test case, click on "Tab 1", then "Tab 2" and at least "Tab 3". Now you'll see content of "Tab 2" and "Tab 3". Then return to "Tab 1". The slider is gone forever.

**Comment by Johann-S** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/23087
will be available in our next release
