### ISSUE TITLE
Logic of grid gutter units

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#23999]
What is the reason of using px in $grid-gutter-width? All other components are using REM units for horizontal spacing (navbar, navs etc), so if i want to align padding in components: navbar + content container with nested grids + footer, i need to add left/right padding to my container and footer in REM value, but nested grids will have padding in PX. What's the reason behind this?

**Comment by andresgalante** [comment]
Hi @Kopyov I am with you on this one, I'd rather do grid in rem. If you search you'll find a lot of issues related to this explaining the reasoning.

**Comment by mdo** [comment]
The answer is in the docs—this is because of viewports being measured in pixels.
