### ISSUE TITLE
Printing Problems

### ISSUE THREAD

**Issue by michaelkrieger** [twbs/bootstrap#23992]
Having a variety of issues with printing and created a test case to help explain it, with some PDF samples.  Using the v4 beta as can be seen in my print-demo.txt (rename to .html and you can view this in any browser).  Designed to be a test case which spans a number of pages for ease of debugging.

[print-demo.txt](https://github.com/twbs/bootstrap/files/1312376/print-demo.txt)

-SOME- of these can be fixed with uncommenting the media print stylesheet in the heading, but this causes other display problems of course with various browsers.

**Firefox v55:**
 Mostly Blank page 2
 Three full flex boxes
 Three cut off and missing headers
[print-demo firefox.pdf](https://github.com/twbs/bootstrap/files/1312318/print-demo.firefox.pdf)

**Chrome v61 (printing from full width):**
 Correctly displays the six flex boxes
 Stops after the first of the 3 cards
 Does not display two of the boxes
 Does not display the footer at all
[print-demo chrome.pdf](https://github.com/twbs/bootstrap/files/1312319/print-demo.chrome.pdf)

**Chrome v61 printing from a narrow width (by resizing the browser very narrow and then printing the page):**
 Seems to do everything correctly
[print-demo chrome (narrow).pdf](https://github.com/twbs/bootstrap/files/1312317/print-demo.chrome.narrow.pdf)

**Comment by XhmikosR** [comment]
Isn't this the same as #23864?

**Comment by michaelkrieger** [comment]
Not "the same".  May share similarities.

#23864 refers to printing inconsistencies between two browsers which would suggest a minor tweak to one browser to get the page to print right.  Moreover, it uses the Bootstrap homepage as the test which is not a "simplified" test case.

This bug refers to NONE of the browsers printing "properly" and provides a test case HTML file with basic elements configured in a common way.  No browser (other than, for some reason a very narrow Chrome when you hit the print button) prints properly.

This bugs refers to an overall problem with printing styles of Bootstrap pages across all browsers.

**Comment by XhmikosR** [comment]
Still seems like the same issue to me, but whatever.

**Comment by guptgar** [comment]
Hi michael krieger,
Were you able to find a fix for the print issue above?

Thanks
