### ISSUE TITLE
Bootstrap4 and modals

### ISSUE THREAD

**Issue by esx78** [twbs/bootstrap#23991]
Hi all, modals doesn't work in the last release: 4.0.0
[https://jsfiddle.net/p53ds3L6/1/](https://jsfiddle.net/p53ds3L6/1/)

**Comment by bkdotcom** [comment]
I see a discrepancy in your example
`<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">` 
vs
`<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">`

(the id of your modal is "myModal", not "exampleModal")

**Comment by esx78** [comment]
true. official site doc is wrong: [https://v4-alpha.getbootstrap.com/components/modal/](https://v4-alpha.getbootstrap.com/components/modal/)     (live demo)

the script is updated. the error persists:
[https://jsfiddle.net/p53ds3L6/3/](https://jsfiddle.net/p53ds3L6/3/)

**Comment by bkdotcom** [comment]
v4-alpha docs have that modal typo, [current docs do not](https://getbootstrap.com/docs/4.0/components/modal/)

developer console reveals
`Uncaught Error: Bootstrap dropdown require Popper.js`

ignoring the fact it says "dropdown"...  uncaught errors are never good...
sure enough, including popper.js clears up the javascript error and modal now works.

popper: 
https://getbootstrap.com/docs/4.0/getting-started/introduction/

> Add our optional JavaScript ~~plugins~~ (**plugins**??, how about "dependencies"), jQuery, and Popper.js) near the end of your pages, right before the closing `</body>` tag. Be sure to place jQuery and Popper.js first, as our JavaScript ~~plugins~~ ("**components**" seems to be the term used the most) depend on them**.

2 issues
* missing popper.js breaks javascript even if not using the components that require popper.js
* I take issue with the term "plugins" vs "dependencies" and "components" on the getting-started docs.

**Comment by Johann-S** [comment]
thank you @bkdotcom to handled that issue :+1: 
do not hesitate to open a PR if you want to update our documentation :wink:

**Comment by bkdotcom** [comment]
re the docs.. I'll brainstorm here before I (or anyone else open a PR)

IMHO: current getting-started docs just don't read well and need some tweaking.  There's too much being crammed in that javascript paragraph.   Users reading "getting started" probably need some more hand-holding / thorough explanation 

Anywho, something like: ?

> ### Add our optional JavaScript components.
> If you wish to use our [javascript components](https://getbootstrap.com/docs/4.0/components/alerts/), you will need to place the following three scripts near the end of your pages, right before the closing `</body>` tag.   jQuery and Popper.js first, followed by bootstrap's script.
>
> [code block showing the 3 script tags goes here]
>
> [info block these two bullet points:]
> * *jQuery, and [Popper.js](https://github.com/FezVrasta/popper.js) are dependencies that must also be included.*
> * *While we use [jQuery’s slim build](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) in our docs, the full version is also supported*.
>
> And that’s it—you’re on your way to a fully Bootstrapped site. If you’re at all unsure about the general page structure, keep reading for an example page template.

**Comment by esx78** [comment]
yes, docs are ambiguous (popper.js, modals, dropdown, etc.)
