### ISSUE TITLE
Popover documentation improvements, data-content movement and data-target feature

### ISSUE THREAD

**Issue by bkdotcom** [twbs/bootstrap#24005]
## documentation
https://getbootstrap.com/docs/4.0/components/popovers/

What is this bullet under "overview" referring to?:
> When triggered from hyperlinks that span multiple lines, popovers will be centered. Use `white-space: nowrap;` on your <a>s to avoid this behavior.

anchor text?   popover content?  I couldn't reproduce.
example or remove the bullet

## Dismissible popovers
> Use the focus trigger to dismiss popovers on the next click that the user makes."

Ironically not dismissed if the next click is on the button that opened the popover.  Yet Non-dismissible popover will toggle the popover on repeat btn clicks

## options
content option:  string | element | function
   * example usage for element/jquery-obj would be nice ie `$('#myPopoverContent')`
   * specifying an element currently moves the element within the dom when popover is displayed
   * since the element is moved,  something like `<div id="myPopoverContent" class="d-hide">tada</div>` will remain hidden.  calling `.show()` will not overwrite the `.d-hide`'s !important
   * add a small note that "obviously" only a string may be specified via `data-content` attribute
   
## Feature request:
new option:  `target`
This would provide the ability to specify content element via `data-target` attribute much like one can do with a modal.    
By providing this option, the "element" type could/should? be deprecated/removed from the `content` option

**Comment by Johann-S** [comment]
about dismissible popovers, I think that's the wanted behavior, so to close your popover you should click outside of the `<button>` which trigger your popover.

If you want to submit a PR which handle things you described do not hesitate :wink:

**Comment by mdo** [comment]
Addressed your first two points in 1a569bab3. Unsure how to handle the third—can you or @Johann-S take a stab at it?

**Comment by mdo** [comment]
Closing as stale / won't fix.
