### ISSUE TITLE
Component Navs bug??

### ISSUE THREAD

**Issue by OnlyBelter** [twbs/bootstrap#24008]
I am using bootstrap v4.0 with angular, but I meet some problems about component `navs` like this:

-------------
Firstly, I navigate to 'help', it works fine, current url is `http://localhost:4201/help`.

 ![help_01](https://user-images.githubusercontent.com/16537617/30629905-ce7e97ba-9e10-11e7-9a0b-3f39e3c6b000.png)

But if I refresh the whole page, I get this(same url):
![after_refresh](https://user-images.githubusercontent.com/16537617/30629910-d5081c14-9e10-11e7-8a15-7520e8d5fa95.png)

This is my code:

```html
<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" routerLink="/index" routerLinkActive="active">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" routerLink="/analysis" routerLinkActive="active">Analysis</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" routerLink="/help" routerLinkActive="active">Help</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" routerLink="/fqa" routerLinkActive="active">FQAs</a>
  </li>
</ul>

```

Is it a bug or I use it with a wrong way??

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by OnlyBelter** [comment]
Sorry, I don't know how to put an Angular app into JS Bin, if you like, please see here https://github.com/OnlyBelter/metDNA-angular/releases/tag/v0.1, download the code and you just need two step to repeat this problem if you have installed `anglular-cli` and `npm`:
```
npm install
ng server
```
Then you can see it at http://localhost:4200/help.

I use 61.0.3163.91 of Chrome, v4.0.0-beta of Bootstrap, Windows 7.

**Comment by XhmikosR** [comment]
@OnlyBelter: why are you using `active` for all `nav-link`s?

**Comment by sarbull** [comment]
```html
<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" routerLink="/index" routerLinkActive="active">Introduction</a>
...
```

The issue is that you include the "active" class in the first menu link as static class in the class tag and it remains there.

You should let angular decide when to add the class.

**Comment by OnlyBelter** [comment]
@sarbull Thanks, that's my fault.
