### ISSUE TITLE
Bootstrap Grid is broken for iPad

### ISSUE THREAD

**Issue by akhilkjuliyan** [twbs/bootstrap#24012]
Hello,
The examples provided in https://getbootstrap.com/docs/4.0/examples/carousel/ not seems to be working in iPad Mini 2.
![realios_ipad_mini_2](https://user-images.githubusercontent.com/30684727/30637000-be069cda-9e14-11e7-8e7d-1e693946550d.jpg)

Could you please provide a solution for this?

**Comment by gogy27** [comment]
I've also bumped up to this problem. Looks like ios 8 and smaller are not supported. None of this utilites works on ios 8: https://getbootstrap.com/docs/4.0/utilities/flex/

**Comment by patrickhlauke** [comment]
iOS8 was released 3 years ago. we're up to iOS11 now. as per https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/#mobile-devices we're really only targetting primarily the latest common version of browser/OS.
