### ISSUE TITLE
Get the original event in event handlers

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#24010]
I'm using v4 beta's popovers with `trigger:'click'`, but it also works with Enter key which is good.

In the shown.bs.popover event handler I'd like to know whether the popover has been invoked by mouse or keyboard. The first argument of the handler is an event object, but it does not have originalEvent property.

The purpose is to focus first item of the list or first input in the form inside the popover, but only when it's been opened using keyboard. See also #18618. 

An additional feature request would be to add a possibility to pass the original event as a 2nd argument of `.popover('show')` call (also 'hide', 'toggle' and 'dispose').

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
