### ISSUE TITLE
Add other variations for max-width // mw-25 mw-50 mw-75

### ISSUE THREAD

**Issue by michaelkrieger** [twbs/bootstrap#24018]
mw-100 was added in #21221 however, like many of the others, this should have other breakpoints (25/50/75 and maybe 33/66 as well).

This would be in _bootstrap/scss/utilities/_sizing.scss_

Example use, where I have a jumbotron where I wish for it to wrap at 50% and thus only be on the left side of the screen (showing the bootstrap-stack.png background image on the right side).  Imagine this with an image that is a light background on the left side and photography on the right.
```
<div class="container-fluid pl-0" style="background:#ffffff url('https://getbootstrap.com/assets/img/bootstrap-stack.png') no-repeat right center; background-size: cover; background-attachment: scroll">
    <div class="container">
        <div class="jumbotron mw-50" style="background-color: transparent; max-width: 50%">
            <h1 class="text-uppercase">Heading</h1>
            <p class="text-secondary">We can really help you...</p>
            <p><a class="btn btn-primary btn-block btn-lg" href="#" role="button">Call me</a></p>
        </div>
    </div>
</div>
```

**Comment by andresgalante** [comment]
Hi @michaelkrieger I've sent this today #24015

I know my PR doesn't solve your issue, but how far should we push utility classes? don't you think this can live in your codebase?

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/24015#issuecomment-332285258.
