### ISSUE TITLE
Dropdown not working properly

### ISSUE THREAD

**Issue by Jeanp12** [twbs/bootstrap#24022]
Bootstrap 4:

So I have this issue where on my website I click on the dropdown button it opens the dropdown all the way at the top, see image below to understand what I mean. Is there anyway to fix this? 

![bt4-issue](https://user-images.githubusercontent.com/5701309/30671441-e3f45016-9e34-11e7-95a9-bc8fcd9d1fd5.PNG)

**Comment by Johann-S** [comment]
sure you can disable the `flip` behavior see : https://getbootstrap.com/docs/4.0/components/dropdowns/#options

**Comment by Jeanp12** [comment]
I must be using this wrong because I'm still having this issue

**Comment by Johann-S** [comment]
flip attribute must be a Boolean so accepted values are true or false

**Comment by Jeanp12** [comment]
I don't get an error for it but it's still doing the same thing.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Jeanp12** [comment]
so.........it turns out another script was affecting it this whole time....didn't even realize it. Thank you for all your help Johann-S
