### ISSUE TITLE
Nested navs don't show/hide content properly [javascript]

### ISSUE THREAD

**Issue by nickelfault** [twbs/bootstrap#24021]
Bootstrap v4 Beta 1

When nav tabs, pills, etc. are nested, clicking the outermost tabs results in some weird behavior, see GIF below for a demonstration:

![Nav Bug](https://i.imgur.com/418sFc5.gif)

I assume this is a javascript selector problem however I've not had a chance to try and fix the problem.

Test case: https://jsbin.com/kosalokafo/edit?html,output

Steps to reproduce: Simply nest one set of tabs inside another.

Tested on Windows 10 x64 on the following browsers:

* Chrome 60.0.3112.113 x64
* Firefox 55.0.3 x64
* IE 11.540.15063.0

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/23087 and will be available in our next release
please search for your issue before opening a new one :+1:

**Comment by nickelfault** [comment]
I did search but missed it.
