### ISSUE TITLE
Utility class `w-40` won't resize img tag.

### ISSUE THREAD

**Issue by vedtam** [twbs/bootstrap#24035]
Hi,

While using bootstrap 4.x I am trying to set the `w-40` utility class for resizing an image tag but nothing happens, its not working. The issue can bee seen in the jsbin demo bellow as well:

http://jsbin.com/mixuzotifo/edit?html,output

Thanks.

**Comment by hebbet** [comment]
there is no class w-40 in default bootstrap.

**Comment by fchiumeo** [comment]
https://getbootstrap.com/docs/4.0/utilities/sizing/#content

**Comment by Johann-S** [comment]
closing thanks to @hebbet and @fchiumeo comment's :+1:
