### ISSUE TITLE
Label btn radio - click on disabled removes active class

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#24038]
It appears that clicking on disabled radio button label removes active class from previously selected label btn but input stays checked which is confusing.

https://codepen.io/anon/pen/XeKxML?editors=1100

**Comment by mayank-mittal** [comment]
The correct behavior should be that when you click on the disabled radio it shouldn't even remove the class much less uncheck the previously check radio button.
I tried to to this.
https://codepen.io/mayank_mittal/pen/xXLwLa
If you find this correct.
I've included that in my fork 
[Fork](https://github.com/mayank-mittal/bootstrap/blob/v4-dev/js/src/button.js)

**Comment by patrickhlauke** [comment]
Very late, but...this should now be fixed by https://github.com/twbs/bootstrap/pull/28834
