### ISSUE TITLE
Add variable for nav-link padding in navbar nav

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#24036]
Currently .nav-link in navbar nav has 0.5rem horizontal padding defined in _navbar.scss. If i want to override these values, i get all breakpoint classes with new values on top of the current ones. Would be better to change it to some variable for better overriding capability so that i can override them without adding new CSS.

**Comment by andresgalante** [comment]
Yes, you are right, A PR has been submitted to fixe it here #23109

**Comment by Johann-S** [comment]
duplicate of #23034
