### ISSUE TITLE
Tooltip data-trigger with multiple triggers not working properly

### ISSUE THREAD

**Issue by asilcetin** [twbs/bootstrap#24032]
[The documentation on tooltips' options](https://v4-alpha.getbootstrap.com/components/tooltips/#options) states that for the data-trigger attribute "you may pass multiple triggers; separate them with a space."

However when I use data-trigger="focus click" as in https://jsfiddle.net/8wc25b0e/ the trigger behaviour is strange: The tooltip is shown on click (so far so good) but it hides only after you click first on the button AND then somewhere else on the screen (losing focus), which would make no sense from a good UI perspective.

I think this combination (focus and click) is something that people would use often, which normally should result in tooltip being shown on click (which is a good choice for touchscreens rather than hover) and hidden on either click on the button OR somewhere else on the screen (losing the focus).

So I propose making the multiple data-trigger values work with OR logic rather than AND.

**Comment by Johann-S** [comment]
Same result with our last release : https://codepen.io/Johann-S/pen/yzJpBM

**Comment by mayank-mittal** [comment]
Can you try
[Codepen](https://codepen.io/mayank_mittal/pen/gGxaQr)

**Comment by asilcetin** [comment]
@mayank-mittal good that now it hides on clicking outside but it should also hide when user clicks the button again. That would be the behaviour of "click OR focus" that I imagine.

**Comment by Babita-Sandooja** [comment]
That's exactly what I need. Do we now have anything in place for it?

**Comment by alecpl** [comment]
The same for hover+click which is my use-case.

**Comment by obakengcondurre** [comment]
> @mayank-mittal good that now it hides on clicking outside but it should also hide when user clicks the button again. That would be the behaviour of "click OR focus" that I imagine.

Were you able to resolve this issue?

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
