### ISSUE TITLE
Folder dist/js appears to have to be present for js to be correctly processed.

### ISSUE THREAD

**Issue by webegguk** [twbs/bootstrap#24047]
If you delete the dist/js folder (css is fine) and regenerate the Javascript, an error is thrown which stops the js being processed. If you create a js folder, it runs fine and everything is created.

This is an issue when importing to a project via npm and changing where the js folder is to be located.

**Comment by XhmikosR** [comment]
I can't reproduce here with `npm run js`. What command do you run and which Bootstrap version are you using?

**Comment by webegguk** [comment]
Thanks for looking into it, this is on Mac OS Sierra with npm v5.3.0 and node v6.10.0. Bootstrap 4.0.0-beta of course!

This is not an issue if using in supplied format, it is if you change the folder you want the js to be generated. Unless you manually create the js folder in your chosen location, the node script won't generate it for you. It may not be perceived as an issue by some.

**Comment by XhmikosR** [comment]
And how do you change the folder you want the JS to be created?

If you try the latest v4-dev from git, you shouldn't have any issues either. So we need a complete test case to see the problem.

**Comment by webegguk** [comment]
So it would be a change to the `js-compile-bundle` script, I have changed where the bootstrap scripts are called from (the `node_modules` folder) and placed after processing, in my case changed from `dist/js/bootstrap` at the very end of the script, to `web/js/app.js` (it's a symfony project).

I'll also try the v4-dev version see if there's any change.

**Comment by XhmikosR** [comment]
I doubt we can support your custom use case.

That being said, you can always just make your own scripts. That is what I do in my personal projects.

The tools here aren't meant to cover all use cases.

**Comment by XhmikosR** [comment]
What do we do with this guys?
