### ISSUE TITLE
Card classes broken in v4.0.0-beta

### ISSUE THREAD

**Issue by DavidRueter** [twbs/bootstrap#24044]
Card classes such as card-inverse and card-primary work in v4.0.0-alpha.6 but do not work in v4.0.0-beta

Works:  https://jsfiddle.net/drueter/4b6nyc8x/

Does not work:  https://jsfiddle.net/drueter/ukqaraqh/1/

(only difference is the version of bootstrap.css in the external resources)

**Comment by Johann-S** [comment]
CSS classes changed but it works see : https://codepen.io/Johann-S/pen/EwggrO
and https://getbootstrap.com/docs/4.0/components/card/#card-styles
