### ISSUE TITLE
Use .navbar-nav-link instead of .nav-link in .navbar-nav

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#24049]
Current implementation of .nav-link inside .navbar-nav is a bit strange - now we can't use tabs and other navs inside navbar dropdowns, because styles for .nav-link are applied for all levels. I understand that navbar by default includes only basic components such as forms, buttons and navigation links with/out dropdowns, but would be much better to change .nav-link to .navbar-nav-link to avoid massive overrides in navbar.scss

**Comment by andresgalante** [comment]
Hi! Can you provide a code example where you'd use tabs inside a navbar item drop down?

I'd love to understand the impact of using nav-link in that corner case.

**Comment by rafalp** [comment]
> Can you provide a code example

Not code example but possible use case for this would be tabbed notifications list.

**Comment by Kopyov** [comment]
Here is jsfiddle - https://jsfiddle.net/g8c3wq7z/5/

Second thing that looks a bit inconsistent to me - nav items inside navbar-nav have same padding as tabs nav, but since tabs/pills can be used in content area, they should use separate padding values. Now if i change tabs nav padding, navbar nav items get same values. This is not correct, because navbar has a single use case.

**Comment by mdo** [comment]
Hmm, I could see doing this as one of the final breaking changes in our betas, but this problem also exists for any nav in a dropdown with any other nav. Only viable solution is returning the `>` in our selectors and forcing styles to only the immediate first child. So far, we haven't heard many requests for that in the two years of development.

**Comment by mdo** [comment]
Closing as we're past breaking changes in v4.
