### ISSUE TITLE
Bootstrap modal options manipulation issue after initialisation.

### ISSUE THREAD

**Issue by samuelting** [twbs/bootstrap#24045]
**Problem:**

According to documentation in https://getbootstrap.com/docs/4.0/components/modal/#via-javascript, modal options can be passed via javascript $().modal method. However, after the modal is initialised, when I passes another option object into .modal method as parameter, newer options is not effective.

For example, initially, the #exampleModal has its options set as 
```
$("#exampleModal").modal({
          "backdrop": "static",
          "show": false
})

```
#examplemodal behaves as  expected. The user cannot dismiss the modal by clicking the backdrop. However, in another part of the program, when I try to set the option of #exampleModal to be this one
 ```
$("#exampleModal").modal({
    "backdrop": true
})
```

However, The modal cannot be dismissed when the user click the backdrop of the modal.

**Expected behavior:**

The modal can be dismissed by clicking the backdrop after "backdrop": true option is set.

**Demo link:**
https://jsbin.com/qotoguv/edit?html,js,output

**Comment by Johann-S** [comment]
you should destroy your older modal before that, because here you create new modal each time so to do what you want you have to do : 
```javascript
$('#exampleModal').modal({
  backdrop: 'static',
  show: false
})
$('#exampleModal')
  .modal('dispose')
  .modal({
     backdrop: true
  })

**Comment by samuelting** [comment]
Opps. Where can I find the documentation of dispose method of modal object?

**Comment by Johann-S** [comment]
Oops not in our docs but in our code 😯

**Comment by Johann-S** [comment]
Is it working as expected with the use of `dispose` ?

**Comment by samuelting** [comment]
Yes it works well. Thanks for your help 👍 .
