### ISSUE TITLE
[FIXED] Dropdown wrong position v4

### ISSUE THREAD

**Issue by romanlex** [twbs/bootstrap#24053]
Hello. What I'm doing wrong?
I copy html from official doc and add popper.js, bootstrap.js
But dropdown not working(
Menu has wrong position style: 
```position: absolute; transform: translate3d(5px, -3391px, 0px); top: 0px; left: 0px; will-change: transform;```
![image](https://user-images.githubusercontent.com/3369304/30747816-073b37b4-9fb7-11e7-96a4-b88a1c6b7cdb.png)
If I clear all html - all works properly, I think what popper.js init wrong position for dropdown
On next screen I save one section in my template:
![image](https://user-images.githubusercontent.com/3369304/30748250-63095e4e-9fb8-11e7-8066-85d97f22abe0.png)
```html
<div class="dropdown">
                <button class="btn btn-go btn-go--full btn-go--dropdown dropdown-toggle" type="button" id="dropdownCityButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span id="selectedMapCity">Город</span>
                    <span class="d-inline-flex go">
                    <span class="fa fa-angle-right"></span>
                </span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownCityButton">
                    <a class="dropdown-item" href="#">Санкт-Петербург</a>
                    <a class="dropdown-item" href="#">Москва</a>
                    <a class="dropdown-item" href="#">Ижевск</a>
                </div>
            </div>
```

**Comment by romanlex** [comment]
I fix issues when load last version of popper.js. In bootstrap doc writed v1.11.0 version, but last is 1.12.5

**Comment by brooksco** [comment]
Same issue. Updating popper.js fixed for me as well, thanks @romanlex!

**Comment by Johann-S** [comment]
when we released our first beta the last release of Popper.js was `1.11.0` that's why
