### ISSUE TITLE
Horizontal scrollbar obstructs Bootstrap CDN links in ( Windows 7 ) Internet Explorer Version 11.0.9600.18792..

### ISSUE THREAD

**Issue by WHBitbucket** [twbs/bootstrap#24057]
The page

http://getbootstrap.com/docs/4.0/getting-started/download/

In ( Windows 7 ) Internet Explorer Version 11.0.9600.18792

Seems to add a horizontal scroll bar to the Bootstrap CDN sections that covers the lower part of the links shown when I give them focus (to copy them).

**Comment by bardiharborow** [comment]
IE7 is not supported by Bootstrap. I'll leave this for someone else to close, just to ensure that there's not a larger problem here though.

**Comment by WHBitbucket** [comment]
Sorry Its my miss typing, Doing to many things at once.

**Comment by bardiharborow** [comment]
Ah okay. I'm not on Windows, but maybe someone else can look into it.

**Comment by prateekgoel** [comment]
I can reproduce the issue at my end. Working on it. Will submit a PR soon.

**Comment by prateekgoel** [comment]
PR submitted.
