### ISSUE TITLE
form-control-static does not set display correctly

### ISSUE THREAD

**Issue by ngiebel** [twbs/bootstrap#24051]
I don't believe that `form-control-static` is behaving correctly when used in standard `form-group`s, it should be applying `display: block` and possibly `width: 100%` like `form-control`. 

https://codepen.io/anon/pen/MEjOvY

**Comment by mdo** [comment]
`.form-control-static` is no more as of Beta 2—we've change dour approach a bit here and are aiming to provide styles for native HTML forms and their attributes. You can still use the new class, `.form-control-plaintext`, as you used the old one, but as you've found, you may need an additional class like `.d-block`.
