### ISSUE TITLE
Set all font-sizes relative to $font-size-base

### ISSUE THREAD

**Issue by tillmon** [twbs/bootstrap#24056]
If all font-sizes are relative to $font-size-base, it would be simpler to change overall font-size:

```css
$font-size-base: 1rem !default;
$font-size-lg:   ($font-size-base * 1.25) !default;
$font-size-sm:   ($font-size-base * 0.875) !default;
```

**Comment by andresgalante** [comment]
Great for consistency! 👍 I would add to this heading font sizes:

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L219-L224

Do you want to send a PR? if not let me know, and I'll do it
