### ISSUE TITLE
Bootstrap 4 beta -> Nav bar stuck in mobile

### ISSUE THREAD

**Issue by Korigoth** [twbs/bootstrap#24065]
I'm trying to create the header in the bootstrap 4 (beta) navbar component. the navbar is stuck in mobile display with the hamburgers to show the menu under a dropdowns... but I am on a desktop, so i want it to show as a normal nav bar at top of the page

https://v4-alpha.getbootstrap.com/components/navbar/

Here is a simple project with the code for the header only and with the same probleme

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>test</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet" />


    <script src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
</head>

<body>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Navbar</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
</body>
```

anybody know what is the problem ?

![image](https://user-images.githubusercontent.com/10915055/30777002-2d4efaf8-a07f-11e7-96fb-6b57556af05d.png)

i've tested on a VM and on a Desktop and both do have the same problem... My Screen Resolution is 1920x1080 The NavBar width is 1920

i'm a bit lost...

**Comment by patrickhlauke** [comment]
Refer to https://getbootstrap.com/docs/4.0/components/navbar/ ... but for further "how to" questions, please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by Johann-S** [comment]
Please do not use this older URL : https://v4-alpha.getbootstrap.com use this one for our beta release : https://getbootstrap.com/docs/4.0/getting-started/introduction/

**Comment by Korigoth** [comment]
Yea i got it working nicely with the new URL, thx i didn't know about the new bootstrap portal

**Comment by enJames** [comment]
I just encountered the same issue, the new URL solved the problem.
