### ISSUE TITLE
Will the jQuery dependency be dropped

### ISSUE THREAD

**Issue by SamThilmany** [twbs/bootstrap#24067]
@techdavid said in an [older, now closed ](https://github.com/twbs/bootstrap/issues/23694), that the next version von BS will drop the jQuery dependency.

For systems that require _very_ fast loading websites this might be a nice feature, to not having to load jQuery first (if it's not cached), but only the really needed JS.

What do you think? Is it good to drop that dependency? Will it happen?

**Comment by gijsbotje** [comment]
it's already in progress :) 
https://github.com/twbs/bootstrap/tree/v4-without-jquery

**Comment by ryanelian** [comment]
Just chiming in; while waiting for v4-without-jquery to be completed, you might be able to use https://github.com/thednp/bootstrap.native to drop jQuery + popper.js dependencies.

**Comment by tamb** [comment]
@ryanelian I use this in a production environment.  It works great!  Plus you can custom build with their webpack-loader.
