### ISSUE TITLE
No display properties for xs

### ISSUE THREAD

**Issue by gmr** [twbs/bootstrap#24063]
While there are the following display sizing classes for `sm`:

- `.d-sm-none`
- `.d-sm-inline`
- `.d-sm-inline-block`
- `.d-sm-block`
- `.d-sm-table`
- `.d-sm-table-cell`
- `.d-sm-flex`
- `.d-sm-inline-flex`

There are no counterparts for `xs`. On mobile, this means that stuff I'm trying to hide on `sm` and down can't be hidden.

**Comment by myorangeca** [comment]
These serve as XS 
```
.d-none
.d-inline
.d-inline-block
.d-block
.d-table
.d-table-cell
.d-flex
.d-inline-flex
```

So you can have something like...

`<span class="d-none d-sm-block"> Will display block for SM/MD/LG/XL </span>`

**Comment by cgslivre** [comment]
Is this breaking point correct? I wonder if it would not be correct to be "max-width" due to the fact that I want the element not to be visible (d-sm-none) when the screen resolution is less than "576px"?

@media (min-width: 576px) {
  .d-sm-none {
    display: none !important;
  }
  .d-sm-inline {
    display: inline !important;
  }
  .d-sm-inline-block {
    display: inline-block !important;
  }
  .d-sm-block {
    display: block !important;
  }
  .d-sm-table {
    display: table !important;
  }
  .d-sm-table-cell {
    display: table-cell !important;
  }
  .d-sm-flex {
    display: -ms-flexbox !important;
    display: flex !important;
  }
  .d-sm-inline-flex {
    display: -ms-inline-flexbox !important;
    display: inline-flex !important;
  }
}

**Comment by 36864** [comment]
`d-sm-none` means `display: none` on screens sm and above.
`d-none d-sm-block` means `display: none` on screens up to, but not including, sm, `display: block` on screens sm and above.

**Comment by XhmikosR** [comment]
What others have said. xs is the default since Bootstrap is mobile first.

**Comment by RSpahn-Scope** [comment]
Curious why was this scheme chosen for show and hide over hidden-sm-down and etc?

I have Angular project where I am using tables throughout the project and I need to show and hide certain TDs based on viewport.  Yet with these latest Bootstrap classes this is just about impossible as the display: block !important overrides the needed display: table-cell.
