### ISSUE TITLE
Grid system documentation refers to undefined columns

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#24075]
[The documentation's first section on the Grid system](https://getbootstrap.com/docs/4.0/layout/grid/#how-it-works) contains:

> Content should be placed within columns, and only columns may be immediate children of rows.

At this point, the meaning of "column" has not been defined, and I do not see it defined later neither.

**Comment by Johann-S** [comment]
You have an example of what's a column in Bootstrap just above see : 

![image](https://user-images.githubusercontent.com/1689750/30797139-2e6ce5ce-a1d5-11e7-9e66-70b3dde3282f.png)

**Comment by Chealer** [comment]
@XhmikosR , why was this ticket closed?

**Comment by bardiharborow** [comment]
@Chealer because defining what a column is, is unfortunately not within the scope of our documentation. Our users are expected to be fluent in English and have at least some prior web design experience. This was made clear in #23754.

**Comment by Chealer** [comment]
@bardiharborow, this ticket is not asking the documentation to define the term "column" in English. This ticket is asking to define what **the Bootstrap documentation means when it refers to a "column"** (in general - there might be a few cases where it means the same thing as English). No amount of English fluency and web design experience will let readers figure that out.

**Comment by Chealer** [comment]
This issue persists and I cannot reopen this ticket. Can someone else do it?
