### ISSUE TITLE
Inappropriate paragraph in grid system documentation's "How it works" section ("Sounds good?")

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#24076]
[The documentation's first section on the Grid system](https://getbootstrap.com/docs/4.0/layout/grid/#how-it-works) asks "Sounds good?".

As pointed out in issue #23754 , "sounds not so good", so assuming a positive answer with "Great, let’s move on to seeing all that in an example." is pretentious at this time. In any case, it would be preferable to avoid unnecessarily questioning the reader. Since the paragraph is not immediately followed by examples, I would suggest to just remove it, or to fix and move down.

**Comment by andresgalante** [comment]
I think you might be overthinking it and been too picky, but since this issue was mention at least 2 times it doesn't hurt to remove it.

What don't you send a PR with a good rewording?

**Comment by semperfi33** [comment]
Hi , Can sou Speak German?


Am 24.09.2017 20:25 schrieb "Andres Galante" <notifications@github.com>:

**Comment by semperfi33** [comment]
I will Performance..... 50 % from Mail's are mit understan....

Am 24.09.2017 20:34 schrieb "Timo Schmitt" <tschmitt1984er@gmail.com>:

**Comment by Chealer** [comment]
@andresgalante , I didn't think much about this. As explained in ticket #23754 , there are many issues with that section. My opinion on that question was made as soon as I read it.

In terms of sending a pull request, I don't want to rule out a rewording, but I am far from convinced that the best course of action is rewording. I still suggest simple elimination.

**Comment by andresgalante** [comment]
I'd say send the PR removing the question and lets have a discussion with a solid proposal. If you want I can send it for you

**Comment by patrickhlauke** [comment]
so much activity for what is, essentially, a question of writing style / making the documentation a bit more colloquial...

**Comment by Johann-S** [comment]
I don't see any interest about that and that's not an issue but a matter of preferences on how we should write our documentation

**Comment by XhmikosR** [comment]
@mdo @bardiharborow

**Comment by Chealer** [comment]
@andresgalante , there are 2 ways to address this:

1. Enhancing the section, so that the answer to the question becomes "Yes"
2. Removing the paragraph

Since the paragraph brings no value and the second way is cheaper, I recommend the latter. Removing the paragraph is a clear proposal. A "PR" would not solidify the proposal nor ease implementation, so I will not send one, in particular since it is best to leave the choice between the 2 options to the paragraph's author in the first place.
