### ISSUE TITLE
there is a bug when  tab-pane has  active radio

### ISSUE THREAD

**Issue by newstatic777** [twbs/bootstrap#24085]
When reporting a bug, include:

- Operating system and version (Windows10)
- Browser and version (Chrome)

Click the home tab when profile tab was actived . we can see the profile content is showing below the home content . because the label which in home content has class 'active' ,and profile tab-pane also has this class . 
    &lt;ul class=&quot;nav nav-tabs&quot; id=&quot;myTab&quot; role=&quot;tablist&quot;&gt;
                    &lt;li class=&quot;nav-item&quot;&gt;
                        &lt;a class=&quot;nav-link active&quot; id=&quot;home-tab&quot; data-toggle=&quot;tab&quot; href=&quot;#home&quot; role=&quot;tab&quot; aria-controls=&quot;home&quot; aria-expanded=&quot;true&quot;&gt;home&lt;/a&gt;
                    &lt;/li&gt;
                    &lt;li class=&quot;nav-item&quot;&gt;
                        &lt;a class=&quot;nav-link&quot; id=&quot;profile-tab&quot; data-toggle=&quot;tab&quot; href=&quot;#profile&quot; role=&quot;tab&quot; aria-controls=&quot;profile&quot;&gt;Profile&lt;/a&gt;
                    &lt;/li&gt;
 &lt;/ul&gt;
  &lt;div class=&quot;tab-content&quot; id=&quot;myTabContent&quot;&gt;
                    &lt;div class=&quot;tab-pane fade show active&quot; id=&quot;home&quot; role=&quot;tabpanel&quot; aria-labelledby=&quot;home-tab&quot;&gt;
                        &lt;div class=&quot;btn-group mb-3&quot; data-toggle=&quot;buttons&quot;&gt;
                            &lt;label class=&quot;btn btn-info active&quot;&gt;
                                &lt;input type=&quot;radio&quot; name=&quot;options&quot; id=&quot;option1&quot; autocomplete=&quot;off&quot; checked&gt;  btn 1
                            &lt;/label&gt;
                            &lt;label class=&quot;btn btn-success&quot;&gt;
                                &lt;input type=&quot;radio&quot; name=&quot;options&quot; id=&quot;option2&quot; autocomplete=&quot;off&quot;&gt;  btn 2
                            &lt;/label&gt;
                        &lt;/div&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tab-pane fade&quot; id=&quot;profile&quot; role=&quot;tabpanel&quot; aria-labelledby=&quot;profile-tab&quot;&gt;Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.&lt;/div&gt;
&lt;/div&gt;

**Comment by Johann-S** [comment]
Reproducible here : https://codepen.io/Johann-S/pen/XepMjN (v4 beta)
But already fixed with our latest dist files see : https://codepen.io/Johann-S/pen/aLpJBW
