### ISSUE TITLE
Bootstrap not finding jQuery. Starter template not working

### ISSUE THREAD

**Issue by RedDuckss** [twbs/bootstrap#24091]
Been using BootStrap for years now and never had this issue, and decided to pick it back up for the first time in months for an Electron project. I'm importing jQuery first (as normal), then popper and then finally BootStrap. However BootStrap still complains that it cannot find jQuery, and none of the JS works. I have download jQuery locally, from https://code.jquery.com, I have used both the minified and unminified versions of both jQuery-slim and normal jQuery. I have also tried using the CDN provided by bootstrap, and even using several others, and BootStrap still complains that it cannot find jQuery.

I even went so far as to copy and paste the template on the BootStrap website (https://getbootstrap.com/docs/4.0/getting-started/introduction/), with 0 changes, and BootStrap _still_ complains that it cannot find jQuery.

### My imports
![https://i.imgur.com/C3vKfeW.png](https://i.imgur.com/C3vKfeW.png)

### The BootStrap starter template (with no changes, straight copy and paste, from the BootStrap website)
![https://i.imgur.com/CDfcoah.png](https://i.imgur.com/CDfcoah.png)

**Comment by Johann-S** [comment]
Sorry but I did a copy/past of our starter template and no error see : https://codepen.io/Johann-S/pen/vegmPL

**Comment by XhmikosR** [comment]
How did you save the JavaScript files? If you copied and pasted their contents and your text editor changes the line endings then the SRI hash won't match.

Otherwise, it should work fine since the live site is using the same values.

**Comment by RedDuckss** [comment]
Did a bit more testing, not a BootStrap issue. This seems to be an Electron issue, as the error seems to only happen in an Electron application. Apologies. Will close.
