### ISSUE TITLE
[Suggestion] Is it time for col-xxl?

### ISSUE THREAD

**Issue by egonsung** [twbs/bootstrap#24107]
With newer screens getting bigger that easily goes double the col-xl width. I believe its time for col-xxl with more or less 1920px?

**Comment by andresgalante** [comment]
I'd say no out the box, but you can easily customize it on your code by changing the breakpoints map.

**Comment by mdo** [comment]
Nope, add it when you need it—all that can be easily generated from source code.

**Comment by egonsung** [comment]
Ok, no. I get that I can add it when I need it, that's just like everything else. But, what's the reason behind "no"?
