### ISSUE TITLE
Wrong Table spaceing when using d-inline-block on table element

### ISSUE THREAD

**Issue by gloomytree** [twbs/bootstrap#24105]
There may be two issues: 

1. When using d-inline-block on a table, the table scales up to viewport width, regardless of the content
2. When using d-inline-block on a table, the table content (thead, tbody) does use up all space provided by the table

Tested on OS: Windows 10

Tested on Browser: 
- Firefox 56.0
- Brave 0.18.36
- Edge 40.15063.0.0

Reduced test case:
https://output.jsbin.com/jilulod/

**Comment by mdo** [comment]
You're going to run into a number of issues when changing the `display` of a `<table>`. That's nothing on our end that we can change—that's just HTML and CSS.
