### ISSUE TITLE
License Clarity

### ISSUE THREAD

**Issue by m-opt-develop** [twbs/bootstrap#24108]
We have been developing a commercial application for a client of ours and we have used the below packages along with their dependencies.

bootstrap

We would like to know the following:

Can we use this package (as-is from GitHub) to ship our commercial application?

Does it provide a legal cover to the dependencies and resources like (but not limited to) icon(s), image(s), font(s) that are required by the package as well?

How do we give attribution (legally speaking) according to the usage of this package in our commercial application?

**Comment by Johann-S** [comment]
Bootstrap is release under MIT license see : https://github.com/twbs/bootstrap/blob/v4-dev/LICENSE for more informations
