### ISSUE TITLE
`docs-github` broken after the workbox addition

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24104]
```
C:\Users\xmr\Desktop\bootstrap>npm run docs-github

> bootstrap@4.0.0-beta docs-github C:\Users\xmr\Desktop\bootstrap
> shx echo "github: true" > twbsconfig.yml && npm run docs-compile -- --config _config.yml,twbsconfig.yml && shx rm ./twbsconfig.yml
```

Not sure how to refactor our scripts at this point...

Also, I think we need something that runs all docs stuff so that it's less error-prone. For example if you run `npm run docs` the docs CSS and JS isn't being run.

/CC @Johann-S @bardiharborow for ideas

**Comment by Johann-S** [comment]
yep I agree, our `docs` task should run every docs tasks related
