### ISSUE TITLE
Opening a modal window twice makes it impossible to close it again.

### ISSUE THREAD

**Issue by bjornstenfeldt** [twbs/bootstrap#24117]
Opening a modal window twice makes it impossible to close it again.

So if you open the modal window #modal and then execute $("#modal").modal("show"); in the browser console, it is no longer possible to close the modal window.

I'm using Bootstrap 4.0.0-beta on Chrome 60.0.3112.113.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bjornstenfeldt** [comment]
https://jsbin.com/comugudafu/edit?html,output

I'm using Bootstrap 4.0.0-beta on Chrome 60.0.3112.113 and Windows 10.

**Comment by Joyrex** [comment]
I'm a bit confused by this: What would be the use case where you would open a modal _from itself_? Are you expecting the DOM to clone the modal and create another instance? Bootstrap has long had a rule against multiple modals, so I am not sure if this is really an issue.

**Comment by XhmikosR** [comment]
I don't see the use case here either.

@bjornstenfeldt: can you elaborate?

**Comment by bjornstenfeldt** [comment]
I don't want to open 2 modals. But I "extended" the modal so I could open it with a hash change event. I did that because I think it is more user-friendly on mobile devices, when you can close a modal by clicking back. At the same time I needed it to open in callback from a LinkedIn API call, so I ended up having 2 completely separated .modal('open') calls.

**Comment by XhmikosR** [comment]
OK, sounds like a fair use case. We have #24240 open, it lacks a unit test though.
