### ISSUE TITLE
.btn-group should wrap buttons

### ISSUE THREAD

**Issue by marcoscv-work** [twbs/bootstrap#24111]
I think Bootstrap should offer a behavior aligned with common responsive problems by default, so btn-groups should wrap buttons. And use "flex-nowrap" in "btn-group" when you need this specific infinite in-line behavior.

Besides, it would be more consistency with the previous version:

![image](https://user-images.githubusercontent.com/7963804/30856997-720bbd24-a2ba-11e7-8b55-239ecfef9a01.png)

**Comment by mdo** [comment]
No it shouldn't—you're using too many buttons. The CSS requires them to be attached—it's the entire point of the button group. If you want them to wrap, make them separate button groups or buttons within the button toolbar.

Closing as a won't fix.

**Comment by marcoscv-work** [comment]
@mdo sorry to use a "copy/paste button example" it was only to show the ease of breaking it.

If you need some example more close to reality we are working on an international product translated many languages and actually, you don't need to use many buttons, you only need to translate three of them to some language like German and you will have a bug in small devices.

Anyway, thank you for reading me.

**Comment by marcoscv-work** [comment]
![image](https://user-images.githubusercontent.com/7963804/30901267-6051bf0e-a367-11e7-9cf1-c4d8a220ca22.png)

**Comment by Johann-S** [comment]
how many button do you use ?

**Comment by marcoscv-work** [comment]
In the screenshot three

**Comment by marcoscv-work** [comment]
Maybe the wrap could be added only in small devices

**Comment by Johann-S** [comment]
Can you add a Codepen showing that issue ?

**Comment by marcoscv-work** [comment]
Of course

**Comment by marcoscv-work** [comment]
https://codepen.io/marcoscv/pen/boqLdN

**Comment by Johann-S** [comment]
maybe we should revisit that PR @mdo ? the Codepen made by @marcoscv-work is very explicit

**Comment by berniegp** [comment]
For others stumbling on this, adding `.flex-wrap` to the `.btn-group` enables wrapping.

**Comment by marcoscv-work** [comment]
> For others stumbling on this, adding `.flex-wrap` to the `.btn-group` enables wrapping.

I found the same fix, It would be awesome if we could document it! thanks!
