### ISSUE TITLE
eslint error `Unexpected newline between object and [ of property access  no-unexpected-multiline`

### ISSUE THREAD

**Issue by Mithrilhall** [twbs/bootstrap#24124]
Branch: **v3-dev**
File: **js/collapse.js**

current code:
```
this.$element
      [dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
```

Error when using [eslint](https://eslint.org/docs/user-guide/command-line-interface) on *js/collapse.js*.
`130:7  error  Unexpected newline between object and [ of property access  no-unexpected-multiline`

Proposed code change:
```
this.$element[dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
```

**Comment by XhmikosR** [comment]
Thanks but 1) v3 is unmaintained and 2) we don't use eslint there.
