### ISSUE TITLE
Refactor our npm scripts

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24121]
OK, so currently, I find it quite annoying that

1. I need to open 2 separate cmds to do local development (one with `bundle exec jekyll watch` and another one with `npm run watch`)
2. Most importantly, I feel like our scripts don't include important parts.

When I do `npm run css` it makes sense to me to run the `docs-css` script too, and so on.

Opening the issue to track it and to find solutions to improve this.

/CC @Johann-S @bardiharborow

**Comment by bardiharborow** [comment]
When I was building this, I had significant issues trying to imagine the most common groups of tasks you'd want to run, and some commands may be suboptimal. My only request is that when refactoring, you trying to keep internal consistency within the commands as a system. Happy to have a shoot at this tomorrow if I remember to do so (I need to stop self-assigning things and then never finishing them though).

**Comment by XhmikosR** [comment]
We definitely need to address the second point above. The watch situation is also annoying but it affects us for now, while if we miss running a script it will affect the users.

**Comment by XhmikosR** [comment]
Feel free to ping me if you make any progress.

**Comment by mdo** [comment]
My setup right now requires three tabs in Terminal (not complaining, totally fine with that):

1. `bundle exec jekyll serve`
2. `npm run watch`
3. Git commands and whatever else

If there's a way to knock it down to two, I'm in favor, but perhaps documenting these better could be helpful, too?
