### ISSUE TITLE
popper link version docs

### ISSUE THREAD

**Issue by pnxsaz** [twbs/bootstrap#24131]
Hi,

should docs be updated regarding https://github.com/twbs/bootstrap/pull/23626 ?

Changing url to use fixed popper version, not v1.11.0.

**Comment by andresgalante** [comment]
Sure, where is it that we mention the popper version on the docs? I couldn't find it.

Would you like to send a PR?

**Comment by pnxsaz** [comment]
I meant at website, sorry for confusion.

https://getbootstrap.com/
https://getbootstrap.com/docs/4.0/getting-started/introduction/

**Comment by Johann-S** [comment]
our documentation will be updated in our next release thanks :+1:
