### ISSUE TITLE
Column reset not working

### ISSUE THREAD

**Issue by dmolineus** [twbs/bootstrap#24136]
Resetting column does not work with current v4 beta. I've searched for any issues for it and looked at the current docs in v4-dev branch, it seems to not have changed:

You can look at the docs to see it: https://getbootstrap.com/docs/4.0/layout/grid/#column-resets

Tested with
 - Google Chrome 61
 - Firefox 55

The clearfix get's displayed with width `0px`. I can workaround the issue when I add another helper class: `w-100`.

**Comment by andresgalante** [comment]
Since the grid uses flex and not floats anymore, I wonder why do we even need a clearfix there? it doesn't make sense to me.

**Comment by mdo** [comment]
Yeah, I feel like this section should be rewritten to focus on breaking the flex wrap so that a column can appear on the next line without a new row.
