### ISSUE TITLE
Nav Tabs with Active Pagination Links Conflict/Broken

### ISSUE THREAD

**Issue by claytonrumley** [twbs/bootstrap#24130]
If you have tabs and pagination inside a `.tab-pane` and you use the `.active` class on the `.page-item` elements, the tabs malfunction and fail to hide properly when switching tabs. We can confirmed that it is the presence of an `.active` class on a `.page-item` that is causing this. Removing `.active` from all `.page-item`s stops the problem.

You can see a reduced test case example of the problem here:
[http://jsbin.com/kokifejuyu/edit?html,output](http://jsbin.com/kokifejuyu/edit?html,output)

We have tested it in FF 55.0.3, Microsoft Edge, and Internet Explorer 11.

This appears to be a JavaScript problem. We do not have a recommended fix, but we consider this of high importance as we have several cases in our web applications of paged data on tab panes.

This issue does not exist in Bootstrap 3, and it possibly didn't exist in Boostrap 4 alpha-6 (which is what we initially started coding against).

**Comment by Johann-S** [comment]
Already fixed in our current dist files see : https://codepen.io/Johann-S/pen/oGZoGj

**Comment by jonathanblancor** [comment]
What was the solution?
