### ISSUE TITLE
Outline button hover should apply same darken as filled button.

### ISSUE THREAD

**Issue by afholderman** [twbs/bootstrap#24144]
If you have two buttons with the same theme color next to one another, one filled and one outline, the outline button's hover state is visually confusing. When hovered it fills and matches the already filled button exactly. When the outline button it hovered the color should fill and have the same darken applied as the standard button to prevent this.

https://codepen.io/afholderman/pen/rGyqbK

**Comment by yunti** [comment]
Good spot, that does make it confusing.

**Comment by afholderman** [comment]
If you would like can submit a PR altering the mixin to perform the same way as the filled button.

**Comment by andresgalante** [comment]
@afholderman please send a PR, and good catch!

**Comment by afholderman** [comment]
PR open here: https://github.com/twbs/bootstrap/pull/24150

**Comment by mdo** [comment]
I agree the mixin should be updated and these colors should be customizable, but I'm going to merge the PR with the current values to keep the look of these as I originally intended. We can revisit eventually, but for now I'd like to keep the default colors.
