### ISSUE TITLE
Stop generating TOC entries for id-less example headings.

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#24142]
Excerpt from `docs/4.0/layout/media-object/index.html`:

```html
<li class="toc-entry toc-h2"><a href="#alignment">Alignment</a>
<ul>
<ul>
<ul>
<li class="toc-entry toc-h5"><a href="#top-aligned-media">Top-aligned media</a></li>
<li class="toc-entry toc-h5"><a href="#center-aligned-media">Center-aligned media</a></li>
<li class="toc-entry toc-h5"><a href="#bottom-aligned-media">Bottom-aligned media</a></li>
</ul>
</ul>
</ul>
</li>
```

`Top-aligned media`, etc. are in example blocks, and do not have element ids, therefore can possibly be linked to.

\cc @XhmikosR

**Comment by bardiharborow** [comment]
Oops, mostly a duplicate of toshimaru/jekyll-toc#25.

**Comment by XhmikosR** [comment]
Yeah, this needs to be addressed upstream even though it is sort of possible to work around it. But then we'd need to change all headers in the examples so it's better if it's sorted upstream.
