### ISSUE TITLE
Pressing escape in a modal dialog changes behaviour of tabs/paging

### ISSUE THREAD

**Issue by quintonn** [twbs/bootstrap#24141]
I created a modal dialog with a number of `<div>` elements inside of it that display set to 'none' by default.
I then use a list of buttons to implement tabs.
When I click on a button, i change all the div's to have display set to none and then the desired div to have display set to block. 
This works and all is well.
But if I close my modal dialog using the escape key, the tab behavior is broken forever until i refresh the page. If i set 'keyboard' option to 'false' for the modal dialog, it fixes the problem but then i can't press escape to close the dialog.
By inspecting the HTML elements, it seems the DIV elements always have display set to 'none' even though my jquery is changing one of them to 'block'. And all of this only after successfully closing the modal dialog using escape key.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by XhmikosR** [comment]
Closing due to lack of reply.
