### ISSUE TITLE
Suggest : add ultility class for xs class

### ISSUE THREAD

**Issue by C0d3rin0** [twbs/bootstrap#24151]
Although xs-* class have been replace with empty in bootstrap 4  : col-xs-* from col-*
But sometime i still need ultility to work with xs class such as : text-xs-left/center/justify/right
Please add support xs class ultility to bootstrap 4 components

**Comment by fchiumeo** [comment]
like [this](https://getbootstrap.com/docs/4.0/utilities/text/#text-alignment)
