### ISSUE TITLE
Overriding theme colors in Bootstrap 4 Beta

### ISSUE THREAD

**Issue by michaeldzjap** [twbs/bootstrap#24153]
If you wanted to override a single theme color in the alpha version you could just simply redefine the relevant variable, e.g. `$brand-primary: #7d71df`. In the beta version theme colors are kept in a map, which makes it more complicated to modify just a single theme color. I really see only two ways of doing this:

1 - In the example case (modifying the *primary* theme) you could override the `$blue` variable, since the `$theme-colors` map uses that variable for the *primary* theme. Although this is just as simple as before, this is far from ideal, since now `$blue` isn't necessarily blue anymore.

2 - Override part of the color system that is referenced in the `$theme-colors` map. This works better than the first solution, but requires you to redefine variables only so that they can be referenced successfully in the `$theme-colors` map, which is kind of ugly...
```
// Need to redefine these variables also, otherwise theme colors map
// cannot be constructed.
$gray-100: #f8f9fa;
$gray-600: #868e96;
$gray-800: #343a40;

$red:     #dc3545;
$yellow:  #ffc107;
$green:   #28a745;
$cyan:    #17a2b8;

$theme-colors: (
  primary: #7d71df,             // Only color I want to customize...
  secondary: $gray-600,
  success: $green,
  info: $cyan,
  warning: $yellow,
  danger: $red,
  light: $gray-100,
  dark: $gray-800
);
```

Although this is not a huge issue, it is quite inconvenient nonetheless. Perhaps I am overlooking something and this can be done more simply. If so, please share.

**Comment by michaeldzjap** [comment]
@Adam-Mould Right, I see. That would solve it indeed. I could just do `$theme-colors: (primary: #7d71df)` and Bootstrap would do the merging. This doesn't seem to be in the bootstrap version I pull in via npm just yet though. So until then I will just go with redefining the necessary color variables. Thanks for your help.

**Comment by noyessie** [comment]
The real problems is modify only one colours and kept the rest avalaible.

`map-merge` is designed for this case. 
```javascript
$theme-colors: map-merge(
  (primary: rgba(255,0,0,.5))
 , $theme-colors);
```

See the full example on my pen: https://codepen.io/neomaster/pen/zRXgOq
