### ISSUE TITLE
Opt-in responsive/mobile-first and state-management

### ISSUE THREAD

**Issue by intellix** [twbs/bootstrap#24157]
I've been using Bootstrap since 2, throughout 3 and have already delivered some using 4. 
What started out as server-generated HTML with jQuery became whole applications using libraries like Angular and React.

Herein lies my problem with the direction that BS3 took and where 4 is also going. Now that it's easier to create re-usable components and even manage layouts responsively using JS I find myself fighting the mobile-first/responsive functionality and state-management that's forced upon me via BS4.

Some examples of pain points: 
 - Navigations now require you to use a helper class to automatically collapse - `.navbar-expand`
 - Cards automatically wrap around as the screen gets smaller
 - Form styling depends on a specific ordering of DOM due to sibling selectors like: 

```scss
.invalid-feedback {
  display: none;
}

.form-control {
  &.is-invalid {
    ~ .invalid-feedback {
      display: block;
    }
  }
}
```

The above makes it difficult to componentise things without having an exact structure of DOM: 
```html
<input type="text" myValidationClasses>
<my-errors [ctrl]="form.controls.amount">
  <div class="invalid-feedback">Required</div>
</my-errors>
```

BS3 had direct-child selectors for things like navigations, which made it difficult for Angular because you had to do a lot of wrapping for conditionally displaying DOM. Now BS4 is enforcing siblings for state-management.

A couple of years ago all of this was excellent because state management and responsive sites required a lot of work and were difficult when the server-generated your DOM. Nowadays I'd just be happy with having a CSS framework that looked great out of the box, but allowed me to manage state/responsiveness myself.

What I'd like to see:
 - Responsive/mobile-first split away (at least different SCSS files so I can choose to not include them)
 - State management split away (things like `display: none` and sibling-selection to display things)

Would you accept PRs for stuff like this or does it go against where you'd like Bootstrap to be in the FE space?

**Comment by mdo** [comment]
Responsive and mobile-first isn't going anywhere—that needs to remain intact. I'd be curious to hear more about potential improvements for the state management.

**Comment by mdo** [comment]
Happy to see more discussion, but for now, closing out as there are no plans from the team to move forward on the ideas mentioned here.
