### ISSUE TITLE
Proposal: show/hide dropdown menus on mouseenter / mouseleave

### ISSUE THREAD

**Issue by heikojansen** [twbs/bootstrap#24155]
Especially when using dropdowns in a navbar as a site navigation element I would like to show the dropdown menu on "mouseenter" events without requiring the users to click on the split toggle.

I think this could be an optional feature and would require only a small amount of extra code; cf. my minimal test implementation at
https://github.com/heikojansen/bootstrap/commit/7ff501a314a9c4eb47a9e1db69ed2c9ea6a7a69a

This does require scripted initialization (the data api as currently implemented wouldn't suffice) and a special config flag but I would consider that a feature...

You can test it here: https://jsbin.com/caciqujudi/edit?output
(Note that I also need a small css modification to close a gap between the parent .nav-item and the dropdown which would trigger "mouseleave" events.)

I wonder if you would be willing to add this as an official feature to bootstrap?
If yes, I'd try to put together a proper pull request on the js source file.
If not, I am interested in the reasons, e.g. if you think that this has accessibility issues.

**Comment by heikojansen** [comment]
I don't see how the extra trigger events would degrade the experience for keyboard and touchscreen users?! Clicking/touching should just continue to work as before? Or am I overlooking a certain usage scenario?

Admittedly, im my JSBin, the ".btn-group" on the ".nav-item" apparently influences the width of the dropdown elements so they do not appear full width below the main nav item (on narrow screens when the navbar isn't expanded). But that should be easy to work around (and maybe it's even a separate bug?). Updated JSBin: https://jsbin.com/qejijujuki/2/edit?output

**Comment by patrickhlauke** [comment]
sorry, missed the jsbin link when skimming the issue. i'd say this is up to @mdo to make a decision.

**Comment by AdrianKuriata** [comment]
#23743

**Comment by mdo** [comment]
No plans to use hover for dropdowns.
