### ISSUE TITLE
bootstrap-v4-dev doesn't have 4.0.0-beta

### ISSUE THREAD

**Issue by azamanaza** [twbs/bootstrap#24162]
When suggesting a feature, include:

Situation:
Our site currently runs on both bootstrap 3 and 4, and we are the process of doing modular migrations.
Our approach was we used "bootstrap" and "bootstrap-v4-dev" as separate dependencies in your package.json (we use npm).

We then prefixed this on less.
```
.bootstrap4-ec {
  @import (less) "~bootstrap-v4-dev/dist/css/bootstrap.css";
  @import (less) "~bootstrap-v4-dev/dist/css/bootstrap-grid.min.css";
  @import (less) "~bootstrap-v4-dev/dist/css/bootstrap-reboot.min.css";
}
```

We wanted to upgrade to 4.0.0-beta and get this error:

```
npm ERR! notarget No compatible version found: bootstrap-v4-dev@4.0.0-beta
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.0.0-alpha.6, 4.0.0-alpha.5, 4.0.0-alpha.4, 4.0.0-alpha.2
```

Running a manual install
`npm install bootstrap-v4-dev@4.0.0-beta`

Results in the same error.

Would it be possible to update the version for your bootstrap-v4-dev branch as well?
https://www.npmjs.com/package/bootstrap-v4-dev

**Comment by fchiumeo** [comment]
the correct package is
https://www.npmjs.com/package/bootstrap

**Comment by azamanaza** [comment]
Hello @fchiumeo ,

As I mentioned in the first post, we currently use bootstrap3, which also uses "bootstrap" key.
We have this in our package.json
```
"bootstrap": "3.3.7",
"bootstrap-v4-dev": "4.0.0-beta",
```

**Comment by fchiumeo** [comment]
bootstrap-v4-dev is not the oficial npm of bootstrap
so you need mailing the maintainer of bootstrap-v4-dev

**Comment by azamanaza** [comment]
"so you need mailing the maintainer of bootstrap-v4-dev"
I understand, it's a dev branch. Which is why I am requesting if beta can be made available there as well.

**Comment by fchiumeo** [comment]
twbs is not the maintainer of this package !!!

**Comment by mdo** [comment]
As @fchiumeo mentioned, `bootstrap-v4-dev` is the incorrect package for any version of Bootstrap. Someone made this package on their own and we do not maintain it. If you want separate versions of Bootstrap, you'll need to specify them on your own from the `bootstrap` package.

**Comment by azamanaza** [comment]
I see.
For anyone else with the same situation, we decided to:
- Manually download/include bootstrap 3
- Included bootstrap 4 in our package.json
