### ISSUE TITLE
Unnecessary use of jQuery global

### ISSUE THREAD

**Issue by thheller** [twbs/bootstrap#24167]
It seems to me that bootstrap still has an artificial dependency on the `jQuery` global that seems unnecessary.

At the top of the file `jquery` is imported but then the `jQuery` global is used.
https://github.com/twbs/bootstrap/blob/a4667be152a3a4fed4e42f2a9efbf831bb5946b6/js/src/index.js#L1

But then the "check" uses the global
https://github.com/twbs/bootstrap/blob/a4667be152a3a4fed4e42f2a9efbf831bb5946b6/js/src/index.js#L21-L32

This pattern is repeated in other files as well, the top imports `jquery` as `$` but then uses `jQuery` in code. Should it not use `$` instead?

I'm asking from a build tool perspective which wouldn't have any issues if the imported object was used instead of the global?

**Comment by XhmikosR** [comment]
@Johann-S: should we also check for `$` in index.js? This should be more flexible.

**Comment by Johann-S** [comment]
yep agreed with @thheller
