### ISSUE TITLE
Using nav flex-column inside (tab-content > tab-pane) show both content at first time.

### ISSUE THREAD

**Issue by Swornh** [twbs/bootstrap#24175]
[exemple.txt](https://github.com/twbs/bootstrap/files/1345493/exemple.txt)
When you put a **nav flex-column** inside a **tab-pane** from another **nav flex-column** for the first time you switch from nav B to nav A it will show both content.

I'm not sure if it's related to #23976 

How to reproduce

- Open the page, after it is open, click on the PROFILE nav, it will show "B B B B"
- Now click on the HOME nav, and it will show both content panel.
- Notice that the fade effect stop working after the first switch.

Only happens at first time, if you click on PROFILE and HOME it will works fine.

It not happens if you remove the inner nav.

There is an very simple example page attached.

**Comment by Johann-S** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/23087
Available in our next release
