### ISSUE TITLE
Checkboxes inside Tabs

### ISSUE THREAD

**Issue by sezeresen** [twbs/bootstrap#24179]
First select tab3 then select tab2 and it shows both tabs. This happens because tab2 contains checkboxes as buttons.
It takes me 4 working days to figure out why it happens. I created a fiddle sample to duplicate this bug.

[https://jsfiddle.net/5645zwkv](https://jsfiddle.net/5645zwkv)

**Comment by Johann-S** [comment]
Already fixed by #23087
Will be available in our next release
