### ISSUE TITLE
Drop-down menu and links suddenly stopped working in Chrome & Android Chrome with the latest version / update

### ISSUE THREAD

**Issue by AfricanTrailblazers** [twbs/bootstrap#24170]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by AfricanTrailblazers** [comment]
I'm not any sort of web designer, web developer or web anything. I got a template off templatemo and customised it to create my website www.africantrailblazers.com using Dreamweaver. It worked great till recently when I visited and discovered that the menu and the links suddenly stopped working for no reason at all. I am at wits end. I even deleted my jquery.js file and that restored the links, but did not help with the dropdown menu. I'm not sure how this happened since I have not touched the website since it was last working. After my tablet laptop and android got updated, my website dropdown menu and links no longer work in Chrome. However, they still work perfectly in Edge. So obviously this is a problem with Chrome. None of the 'model solutions' suggested by Chrome worked for me. It also doesn't help for me to download an old / new / alternate version of Chrome or uninstall updates, since most of my clients use Chrome. I would be most grateful for any help please?

**Comment by patrickhlauke** [comment]
sorry, we can't help you with this sort of query. you'll need to ask on some other site like StackOverflow. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
