### ISSUE TITLE
<picture> with img-thumbnail class

### ISSUE THREAD

**Issue by t5k6** [twbs/bootstrap#24176]
I am trying to implement `<picture>` tag to selectively serve pictures; webp format for Chrome based browsers and jpeg fallback for other browsers. However using Bootstrap's `img-thumbnail` class is not working properly, it creates handlebar like artifact on border sides.

![image](https://user-images.githubusercontent.com/12563212/31033701-c1613bd6-a569-11e7-8d71-f184afdddf01.png)

Sample code:

```html
<picture class="img-thumbnail img-fluid">
  <source srcset="/path/to/image.webp" type="image/webp">
  <img class="img-thumbnail img-fluid" src="/path/to/image.jpg" alt="">
</picture>
```

Bootstrap version: 4 beta

**Comment by andresgalante** [comment]
I've just tested it. @t5k6 you are right, the way we setup images and figures don't support `picture`.

I'll send a PR with a possible solution.

**Comment by andresgalante** [comment]
@mdo @XhmikosR Do you think we should put this on reboot or under figures with a new class of `.picture` ?

**Comment by XhmikosR** [comment]
`.figure` is being set to inline-block in _`images.scss`. Not sure if we should add this in reboot or not. It's @mdo's final choice.

**Comment by andresgalante** [comment]
@XhmikosR Yeap. Sorry, I meant `_image.scss` or `_reboot.scss`

If it goes to reboot we don't document it. if it goes to images.scss then we would have to add a new section to the docs with `picture` or put it under `figure`.

**Comment by andresgalante** [comment]
Here is a live example of what this issue is describing with the inline-block solution:

https://codepen.io/andresgalante/pen/EwXJdj

**Comment by XhmikosR** [comment]
It's @mdo's final choice. Personally I wouldn't add it to reboot.

**Comment by mdo** [comment]
Rather than add a generic `.picture` class, couldn't we encourage folks to use `.d-inline-block`? And does this issue happen to all `<picture>`s, or only ones that have our particular thumbnail styles?

**Comment by andresgalante** [comment]
@t5k6 After testing it again I realized I was wrong, you don't need to change the display of the `picture` tag unless you want to add a border around it.

Use `img-*` classes only on the `img` tag and not on the `picture` tag and you'll be ok. Your markup should look like this:

```html
<picture>
  <source srcset="/path/to/image.webp" type="image/webp">
  <img class="img-thumbnail img-fluid" src="/path/to/image.jpg" alt="">
</picture>
```

The picture will handle where the source of that image comes from.

See an example here: https://codepen.io/andresgalante/pen/EwXJdj

@mdo There is nothing wrong with the way we handle images. Do you you I think it has value to document this on our docs under images?

**Comment by mdo** [comment]
> @mdo There is nothing wrong with the way we handle images. Do you you I think it has value to document this on our docs under images?

Yeah, good idea—I think it'd be helpful to have a code example and snippet in the Image docs page.
