### ISSUE TITLE
Active child elements in tab-pane break tabbed navigation.

### ISSUE THREAD

**Issue by xplinscott** [twbs/bootstrap#24174]
The ACTIVE selector in the Tab control is finding active child elements of the tab-pane during activation which breaks the tab navigation.

I first noticed this when using dataTables with pagination inside of a tabbed navigation. I narrowed it down to the Tab control finding the active page link in the pagination and updating it rather than the tab navigation.

Here is a JSFiddle with a small tabbed navigation with pagination in each of the tabs.

JSFiddle: https://jsfiddle.net/xplinscott/nrda8vjq/1/

Steps:
1) Loads with Home tab active
2) Click Profile which loads fine
3) Click Messages, and notice that the Profile tab is not hidden, and it shows Profile and Messages.

OS: Ubuntu 17.04
Browser: Google Chrome 61.0.3163.100

**Comment by Johann-S** [comment]
Already fixed by #23087
Will be available in our next release
