### ISSUE TITLE
Make the 'Bootstrap 4 Beta is here!' banner communicate Alpha's status more effectively.

### ISSUE THREAD

**Issue by bkdotcom** [twbs/bootstrap#24178]
I've noticed several issues related to incorrect / old documentation simply because people find themselves on outdated docs. (ie v4-alpha)

Google [bootstrap 4 documentation](https://www.google.com/search?q=bootstrap+4+documentation):  
the top link is for v4-alpha

The old docs have a "Bootstrap 4 Beta is here!" blue banner at the top, but I don't think it's nearly prominent enough..  And it doesn't explicitly state you're viewing old documentation.

---

Thoughts on making the banner `fixed-top` & first-and-foremost stating "This documentation is not current"?

**Comment by Johann-S** [comment]
Agreed that's lead to issues which don't use our latest documentation

**Comment by bardiharborow** [comment]
@mdo thoughts?

**Comment by mdo** [comment]
Done!
