### ISSUE TITLE
Incorrect Modal Documentation

### ISSUE THREAD

**Issue by Krystian95** [twbs/bootstrap#24172]
Hi,

in the example at [https://v4-alpha.getbootstrap.com/components/modal/#modal-components](url) the id specify in the button (#exampleModal) is not accorded to the real modal id (#myModal). "#exampleModal" should be changed  to "#myModal".

![doc bug](https://user-images.githubusercontent.com/24765669/31020435-4c7f1fee-a533-11e7-999c-f3bc7e6462d5.PNG)

Best regards,
Cristian Romanello.

**Comment by fchiumeo** [comment]
fixing in the beta version https://getbootstrap.com/docs/4.0/components/modal/#live-demo
