### ISSUE TITLE
Why bootstrap 4 have no offset class. IF i want 3 column margin from left what should i do?? Help

### ISSUE THREAD

**Issue by ochena** [twbs/bootstrap#24177]

**Comment by flo-sch** [comment]
Not sure what kind of result you want?

https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns

I might help a bit more precisely if you provide an example (JS Fiddle for instance?)

**Comment by Johann-S** [comment]
Closed thanks to @flo-sch 👍
