### ISSUE TITLE
Update introduction documentation quickstart and template with Popper v1.12.5

### ISSUE THREAD

**Issue by gygabyte017** [twbs/bootstrap#24184]
The Popper version used in documentation quickstart (https://getbootstrap.com/docs/4.0/getting-started/introduction/) uses Popper v1.11.0. This popper version has issues i.e. with dropdowns positioning (see #23469) which have been solved in later version (https://github.com/FezVrasta/popper.js/issues/302).

I recommend to update documentation with
`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.min.js" integrity="sha256-jpW4gXAhFvqGDD5B7366rIPD7PDbAmqq4CO0ZnHbdM4=" crossorigin="anonymous"></script>`

**Comment by XhmikosR** [comment]
We are already using 1.12.3, see https://github.com/twbs/bootstrap/blob/v4-dev/_config.yml#L73

/CC @Johann-S to decide if we should update or not.

**Comment by XhmikosR** [comment]
@Johann-S: I'm closing this since we use 1.12.3 which is basically the same as 1.12.5.
