### ISSUE TITLE
Navbar not working with current dist?

### ISSUE THREAD

**Issue by josh-byster** [twbs/bootstrap#24180]
With the current distribution bootstrap.min.css, none of the navbar examples on the docs show up or function even remotely correctly. Tried both the CDN and current file in the dist folder. I haven't had this problem before. 

[Example Gist](https://gist.github.com/josh-byster/e42db6f50095746e7a9448f700849e73)

**Comment by mayank-mittal** [comment]
Actually you are using the latest distribution of bootstrap but not the latest version of the code. Actually bootstrap 4 has a different structure all together 
For you navbar to work use this link [](https://v4-alpha.getbootstrap.com/components/navbar/) 


And for future references if you want to bootstrap v4, you have to look for https://v4-alpha.getbootstrap.com in the url.

Don't forget to close the issue.

**Comment by Johann-S** [comment]
The new URL of our latest release documentation : https://getbootstrap.com/docs/4.0/getting-started/introduction/
