### ISSUE TITLE
BUG? first close modal in hide.bs.modal return false;   then close modal  and never in hide.bs.modal 

### ISSUE THREAD

**Issue by tooever** [twbs/bootstrap#24181]
Bootstrap V4 
Bootstrap V3 is ok

    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Open Modal
    </button>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">
                        Title
                    </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        ×
                    </button>
                    
                </div>
                <div class="modal-body">
                    Click three times to close
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>
    <script>
     $(function (){
 	    var i=0;
 	    $('#myModal').on('hide.bs.modal', function () {
		   ++i;
	       if(i<3)
		     return false;
	       else i=0;
	    })
     });
    </script>

I'm from China. My English is not good, maybe some mistakes, hope you can understand.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.
