### ISSUE TITLE
New display utilities (d-{sm,md,lg,xl}) of the beta release break the hidden attribute

### ISSUE THREAD

**Issue by sebestindragos** [twbs/bootstrap#24182]
We are using Angular 4 for our application and have some markup for our navbar that hides some content based on responsive breakpoints and also by application logic.

Consider the following example:
We have a `<ul>` element in our navbar that is only visible on medium and up devices. The element is also hidden if the user is not logged into our app (using the hidden HTML attribute, controlled via Angular). This logic is required because that part of the navbar holds some contextual user controls, like notifications, profile image, etc. On smaller devices we hide it, because we use some other markup.

Using the alpha version the markup was as follows:
`<ul class="nav navbar-nav hidden-md-down" [hidden]="!this.isLoggedIn()">`
This worked just fine, because Bootstrap set display: none on those breakpoints, otherwise the element's display property was controlled using the angular binding to the hidden HTML attribute ([hidden] is Angular syntax).

After migrating to the beta version of Bootstrap the markup had to be changed to:
`<ul class="navbar-nav d-none d-md-flex" [hidden]="!this.isLoggedIn()">`

But this really breaks things. First of all, now developers are required to explicitly set an element's display property to something to be able to show it on a certain device. On the older version we didn't need to do this, instead the element had it's display property set to its initial value. Now, if we want to display the element, and also retain its initial display value, we have to know the default for each element (for a div set it to block, for a span set it to inline, etc.). I think a **d-{sm,md,lg,xl}-initial** class would help with this issue.

The other issue is more infuriating. **d-md-flex** sets the element's display value to **flex !important**. This makes the **hidden** attribute on the element useless. 

We are now facing this issue, and came up with a solution, but it isn't quite pretty. We've made an Angular directive to replace the usage of the hidden attribute with this custom functionality that basically set's the element's display property to **none !important** based on a condition using JavaScript code. So our markup became this: 
`<ul class="navbar-nav d-none d-md-flex" rz-hide [rz-hide-if]="!this.isLoggedIn()">`

Internally, that rz-hide stuff is also Angular syntax that does this under the hood:
```
toggleElement (hidden: boolean) {
    if (hidden) {
      this._element.style.setProperty('display', 'none', 'important');
    } else {
      this._element.style.setProperty('display', this._initialDisplayValue);
    }
  }
```

All of this could have been simpler, if only Bootstrap didn't use the **important** keyword in it's classes.
We have struggled for 2 days to find a solution to this, because apparently, it isn't easy to override the **important** keyword using JavaScript. See [this stackoverflow post](https://stackoverflow.com/questions/462537/overriding-important-style).

 Now, I do understand this is necessary, but the fact that we had to work around this issue is unpleasant.
Also, I think that it's bad to not use standard functionality for doing this kinds of stuff. The hidden attribute was used to do what it was meant to do. Now we are using custom attributes, which are not only semantically weird, but also more verbose.

I am reporting this as a bug, because it did break our code, but to conclude I would see this resolved by proposing to move back to the alpha approach, to set the display value to none on certain break point to show/hide element on different devices instead of explicitly setting it to block or flex etc.

I think this affects all environments, but for the record we are developing under:
Operating system: **Windows 10**
Browser: **Chrome > 50**
Bootstrap version: **4-beta**

**Comment by mayank-mittal** [comment]
Couldn't you do something like
<ul class="nav navbar-nav" ng-class="{d-none: !this.isLoggedIn()">

**Comment by mayank-mittal** [comment]
`<ul class="navbar-nav" ng-class="{d-none: !this.isLoggedIn()">`

**Comment by rickyruiz** [comment]
Instead of writing that much logic in JavaScript, you could use an attribute selector for hidden like so:

```
[hidden] {
  display: none !important;
}
```

Have in mind that the important flag should not be overused. Generally, Bootstrap uses it for helper classes to ensure functionality.

Notes: Reference your stylesheet after bootstrap's.

**Comment by mdo** [comment]
> All of this could have been simpler, if only Bootstrap didn't use the important keyword in it's classes.

Sorry, this is sticking around for v4 at least. Closing as a won't fix.

**Comment by sebestindragos** [comment]
@mayank-mittal d-none is already applied on that element for < md devices, so no.
@rickyruiz I fear that that could lead to other kind of hard to track bugs. I am strongly against global usage of different code constructs, regardless of the language (CSS, JavaScript, etc.).

@mdo The new display classes are great, they provide a lot of flexibility. Just to make it clear, I do not want them to be removed. They cannot be removed, being a beta version already. I was proposing to also bring back the **hidden-*** classes, as they provide functionality for other types of use cases.

IMHO this issue presented here is quite serious, maybe others can provide a different point of view. For now, we will stick with the work around described in the first posts, as it is isolated and semantically describes the issue that is resolved.

**Comment by bbugh** [comment]
We're having an issue with this too in a not-uncommon scenario. The `hidden-xs-down` class was working perfectly, but there doesn't seem to be a compatible way to solve our issue.

We have a floating support button (commonly found in the bottom right of web sites) that we don't want to appear in `xs`. When the button is clicked, we hide it and show a contact form. With the set up `class="d-none d-sm-block"`, attempting to hide the element after it's clicked will fail because of the `display: block !important` in `d-sm-block`.

We can work around it by setting the CSS class `d-sm-none` instead of `display: none` on the element, but that couples our basic hide/show JavaScript code to the Bootstrap framework.
