### ISSUE TITLE
Dropdown dynamic offset v4

### ISSUE THREAD

**Issue by romanlex** [twbs/bootstrap#24204]
Hello. I'm trying change dynamically position of the dropdown menu. My code is not work ((( How I can calculate and change position of dropdown dynamically before dropdown is showing?
Example, I trying change data attr of element data-offset on **show.bs.dropdown**  or **shown.bs.dropdown**
```
this.$parentUl.siblings('.dropdown-toggle').attr('data-offset', '-100').data('offset', -100);
this.$parentUl.siblings('.dropdown-toggle').dropdown('update');
```

**Comment by Johann-S** [comment]
Popper.js already handle that for you :+1:

**Comment by Johann-S** [comment]
Hmm sorry I misunderstood your question @romanlex, I'm not sure if Popper.js handle to change the offset dynamicly, maybe a simple you can try : 

```js
this.$parentUl.siblings('.dropdown-toggle').dropdown('dispose').dropdown({
  offset: '-100'
})

**Comment by romanlex** [comment]
I found what I can send fn function in offset to Proper
![image](https://user-images.githubusercontent.com/3369304/31079822-96f880d4-a78f-11e7-9b8e-4df66e77b366.png)
But in source code (dropdown.js) I see only statis offset for initialize plugin
![image](https://user-images.githubusercontent.com/3369304/31079786-7c1f08be-a78f-11e7-87b6-b62ccbf849a5.png)

**Comment by Johann-S** [comment]
that's true currently we only accept : `number | string` but we are open for a PR :smile:

**Comment by romanlex** [comment]
@Johann-S thx )) https://github.com/twbs/bootstrap/pull/24208

**Comment by Johann-S** [comment]
Related to : #24223
