### ISSUE TITLE
Nested tabs work with bootstrap4-alpha but not bootstrap4-beta

### ISSUE THREAD

**Issue by sandwichsudo** [twbs/bootstrap#24207]
Hiya,
On the docs for bootstrap 3 it stated that nested tabs were not supported. I've had a look for something similar in the latest docs, but couldn't see anything, so apologies if this is simply not a feature you wish to support.

Here is a pen using the alpha js:
https://codepen.io/sandwichsudo/pen/rGzgVN/
Nested tabs work fine

Here is the same pen with the js now pointed at the beta.
https://codepen.io/sandwichsudo/pen/YrxbzV?editors=1010
The tabs don't always show the correct content, and flicking between profile/buzz can make both bits of content appear.

Would be great to know if this is regression, unsupported, or user error.

Many thanks,
Gilly

**Comment by Johann-S** [comment]
Already fixed by #23087
Available in our next release

**Comment by sandwichsudo** [comment]
Great news, thanks very much
