### ISSUE TITLE
Bootstrap 4 columns not working properly on Safari

### ISSUE THREAD

**Issue by gilek555** [twbs/bootstrap#24219]
I made a website with Bootstrap 4 and everything works fine except auto wrap columns on Safari 10.1.1 on MacOS.
When number of columns in a row is equal to 12, then the last column jumps to the new line instead of wrap to previous column. When number of columns is smaller than 12 there is no problem.

For example my top header:
`<div class="container">`
`     <div class="row">`
`<div class="col-lg-3">logo</div>`
`<div class="col-lg-9">menu</div>`
`</div>`
`</div>`
On Chrome and Firefox logo and menu are in one line but on Safari menu starts in a new line (screen from Safari):
https://imgur.com/a/xTv9m

This looks like flexbug#11 and when I'm setting flex-basis to the columns the problem still occurs.
I tried also with the border 1px transparent workaround but also without success.

This issue appears also on another sections in my website where I used 12 columns in a row.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by gilek555** [comment]
The best way to show the problem is a live site: https://en.etrose.com because there is more section with this problem than only header.

Bootstrap version: 4.0.0-alpha.6
OS: OS X El Capitan v. 10.11.6 (15G1421)
Browser: Safari 10.1.1 (11603.2.5)

**Comment by Johann-S** [comment]
Sorry but we can debug on a live site because they are a lot of custom style applied

**Comment by gilek555** [comment]
Ok, I found what generate problem.  I was delete this line .row:before { content: " "; }

**Comment by pimisi** [comment]
In my case I overrode the class .row:before, set display: inline-block; That did the trick and did not affect Chrome snd Firefox

**Comment by DennisLoska** [comment]
@pimisi thank you this simple solution also helped me!

**Comment by neerajkarunakaran** [comment]
dfgfdgfdgfdgdfgdfgdf

**Comment by neerajkarunakaran** [comment]
dfsfdsf

**Comment by Peeripapo** [comment]
@pimisi You just saved my life. Thanks!!

**Comment by Jasminou** [comment]
@pimisi can you show us how to do to override bootstrap property ?

**Comment by Ajay493** [comment]
@pimisi Thanks!!

**Comment by vpokrityuk** [comment]
@pimisi Thank you so much, mate!!!

**Comment by Viktor-Bredihin** [comment]
it does affect chrome and other browsers as soon as you start using col-push

**Comment by carlo-activamedia** [comment]
Im having the same problem
url: https://thisquarterly.sg/

**Comment by pimisi** [comment]
@carlo-activamedia I loaded the url and cannot see where you have this issue.

**Comment by rhojackson** [comment]
Cheers!

**Comment by JKdreaming** [comment]
Your the $h!T and I love you baby! You also saved Jackie's life!
