### ISSUE TITLE
Button after input overlaps border in input group

### ISSUE THREAD

**Issue by jrysig** [twbs/bootstrap#24216]
@mdo Are you sure about this recent change?
https://github.com/twbs/bootstrap/commit/864c657488e2ec292c45c2d49322987ba3d56b3a

With light button background the missing border between input and following button seems strange to me, please see https://codepen.io/anon/pen/EwwmbK

When you hover or focus input, border is displayed.

![border](https://user-images.githubusercontent.com/7038517/31112863-95db7e68-a816-11e7-8752-b2efc0ce6143.png)

**Comment by mdo** [comment]
It looked better with the default Bootstrap button styles there :grin:

**Comment by mdo** [comment]
I'll see what I can do. The `focus` state is right as it overlaps the content that comes after it—might just need to mess with the `z-index` more to ensure proper overlapping.

**Comment by splice7** [comment]
@mdo you are right. This worked for me:

```
.theinput:hover + .thebutton {
	z-index: 3;
}

.theinput:focus + .thebutton {
	z-index: 2;
```

It might not be the most elegant but it proves that `z-index` is the way to go.

**Comment by alecpl** [comment]
I have a similar issue not related to buttons, but I think the change in last comment will not work. Consider two text inputs in a line, first focused. Then if you hover over the second input the focus shadow on the first will be broken. https://codepen.io/alecpl/pen/PJgRob

**Comment by ysds** [comment]
Hi @alecpl, Bootstrap does not support multiple form-controls in a single input group

http://getbootstrap.com/docs/4.0/components/input-group/#basic-example

@mdo I'm working on creating PR for this issue, but I need your help about z-index specifications. **In normal state** (not hovered/focused/actived), the following patterns are considered. Which one is the most preferable?

![image](https://user-images.githubusercontent.com/4065765/31925064-03e9cd78-b8c1-11e7-8e3d-63bd2c5a9dd9.png)

**Comment by mdo** [comment]
The second one is most ideal. Apologies for the delayed response—missed this while I was out this last week on vacation.

**Comment by ysds** [comment]
@mdo thank you for your reply. 

Input groups has become also support custom selects and custom files, we should check these z-indexes. I noticed about unsure z-index value of custom files, I reported the issue #24632 and PR.

**Comment by ysds** [comment]
I have been considering this issue for a while and noticed further related subject. I will create a issue later.

**Comment by mdo** [comment]
This will likely be addressed by #25020.

**Comment by mdo** [comment]
#25020 merged, so closing.

**Comment by rostovtsev** [comment]
The simple solution for existing projects would be simply adding this rule:

~~~CSS
.form-control:focus
{
    z-index: 9999;
    position: relative;
}
~~~
