### ISSUE TITLE
Additional classes for printing

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#24215]
An idea raised by me already in #24015, it might be nice to have classes which can be e.g.
 used in order to not just hide certain columns when printing (e.g. a side navigation bar) but also to display other columns (e.g. the main content) in full width, see <https://stackoverflow.com/a/32253969>.

**Comment by letorruella** [comment]
Has this been implemented? I would like to tackle it.

**Comment by Johann-S** [comment]
you can tackle everything @letorruella 😉

**Comment by mdo** [comment]
Closing as print-focused styles are not a priority for us and this doesn't seem like something many folks are looking for in Bootstrap.
