### ISSUE TITLE
Why dosent the navbar link to the doucmentation in the bootstrap documentation automatically redirect to the getting started page

### ISSUE THREAD

**Issue by jeffreymeng** [twbs/bootstrap#24232]
When you click on the `documentation` link in the [Bootstrap documentation](https://getbootstrap.com) navbar you get sent to `https://getbootstrap.com/docs/4.0/`.
That page, in turn, takes about 1/3 of a second to redirect you to `https://getbootstrap.com/docs/4.0/getting-started/introduction/`. Why not just directly redirect to the page, making a (slightly) better UI?

Also, on the getting started page, maybe you could automatically focus on the search bar so users who want to directly search can have a easier time?

If there's an obvious reason as to why these aren't already there, sorry, but it seems like these two changes would make it (a little) faster to navigate the Bootstrap documentation.

**Comment by XhmikosR** [comment]
I believe the reason is so that things work in the future when a new version comes out.

/CC @mdo.

**Comment by mdo** [comment]
We could maybe shortcut that? I dunno. What @XhmikosR said makes sense too, but we'll need to globally find-and-replace stuff when 4.1 drops for example. Worth a try!

**Comment by XhmikosR** [comment]
@mdo: I think we can change the nav link to the direct link to `{{ site.baseurl }}/docs/{{ site.docs_version }}/getting-started/introduction/`. Then we'll just need to remember to add a redirect to if the link changes.

**Comment by mdo** [comment]
Yeah that sounds right to me

**Comment by XhmikosR** [comment]
@mdo: I'm not sure if we should focus the searchbar here. If we had a search form which took the whole width that might make sense, but here I don't think it does.

If you agree, we can close this with #24263
