### ISSUE TITLE
Need improvements on Scrollspy and Forms

### ISSUE THREAD

**Issue by KailashPatil** [twbs/bootstrap#24239]
Hello Bootstrap Team,

Bootstrap 4 is a great framework to start a new project. 
Easy to build and super fast. Thanks for the such a great work. 

I tried working on a project using same and found couple of improvements needed:

- Component 'scrollspy' need better smooth scrolling instead it jumps as of now.
- Great custom style for 'radio' and 'checkbox' buttons, It would be good if we get custom style for 'select' fields as well. Current UX/UI trend need custom style very badly.

Please update if you need anymore info.

Thanks,
Kailash

**Comment by mdo** [comment]
> Component 'scrollspy' need better smooth scrolling instead it jumps as of now.

No plans to add this.

> Great custom style for 'radio' and 'checkbox' buttons, It would be good if we get custom style for 'select' fields as well. Current UX/UI trend need custom style very badly.

We have this in our current v4 beta docs.

---

On a side note, please create separate issues for separate requests <3.
