### ISSUE TITLE
Wrong link in Migration to v4 docs

### ISSUE THREAD

**Issue by aarongarciah** [twbs/bootstrap#24247]
**Test case**
https://getbootstrap.com/docs/4.0/migration/#components

**Description**
The link to Cards in the [Migration to v4](https://getbootstrap.com/docs/4.0/migration/#components) docs is wrong. Right now the link is pointing to https://getbootstrap.com/docs/4.0/components/cards/ but it should point to https://getbootstrap.com/docs/4.0/components/card/.

The link was fixed in [this commit](https://github.com/twbs/bootstrap/commit/6a5a38106ac518f0cd493901aac69c38e216944d#diff-0acfcc3020f39d1a05536c7f4f00bca5), but it seems that the docs website hasn't been updated.

![wrong-link](https://user-images.githubusercontent.com/7225802/31180772-c47198ac-a91f-11e7-861f-2cdd3603ce5e.jpg)

**Comment by XhmikosR** [comment]
The website will be updated when there is a new version.
