### ISSUE TITLE
Variable $card-border-width should take in $border-width as it's default.

### ISSUE THREAD

**Issue by afholderman** [twbs/bootstrap#24243]
Unlike other border-width properties (btn, input, etc.) which take in the `$border-width !default` card is set to `1px !default`. This means that resetting the global $border-width variable does not change the card. If making this change is approved I can submit a PR.

**Comment by andresgalante** [comment]
@afholderman You are right. It was fixed here: https://github.com/twbs/bootstrap/commit/1cfbc2c62df86ed1d243591160634965eb0ef2b7

It will be reflected on the next release.

Thanks for reporting this.
