### ISSUE TITLE
Why does the LI elements not the same as P

### ISSUE THREAD

**Issue by Jzarecta** [twbs/bootstrap#24253]
I notice this issue with the styles and I dont see the reason why lil should have a different style from the rest of the fonts from paragraph.
Is this an oversight?

**Comment by bkdotcom** [comment]
Here's a page with `<li>` and `<p>`
https://getbootstrap.com/docs/4.0/content/reboot/#lists
They both have the same font-family, font-size, font-weight, line-height, color, etc
what are you talking about?

**Comment by mdo** [comment]
Yeah, they're the same.
