### ISSUE TITLE
broken .card-header rendering on google chrome when background-color is customized

### ISSUE THREAD

**Issue by udos** [twbs/bootstrap#24258]
not sure if this is a browser bug...
- Operating system and version: Windows 10
- Browser and version
  - issue occurs in google chrome -> Version 61.0.3163.100 (Official Build) (64-bit)
  - it does not(!) occur in Microsoft Edge 38.14393.1066.0

how to reproduce:
- in google chrome, navigate to [jsfiddle.net/udos/1zodwu7a/3/](https://jsfiddle.net/udos/1zodwu7a/3/)
- in the html output you will see something like the following:
![image](https://user-images.githubusercontent.com/141107/31217272-bb1b6d2c-a9b6-11e7-843d-1eee0b8793ea.png)
- the `.card-header` looks "broken"<br>note: if you do not see the effect, slowly move the side-scroll (blue arrow) with the mouse until you see it (probably on some other `.card-header`)

if you remove the customized styling `background-color: #ff463c;`, everything works perfectly.

**Comment by XhmikosR** [comment]
Something is seriously broken on Chrome on Windows. I wonder if it's only Chrome or a VGA driver too.

At any case, please try Chrome beta or canary and see if the issue happens.

**Comment by XhmikosR** [comment]
Probably related judging from the screenshot: #24233

**Comment by udos** [comment]
in Google Chrome (beta), Version 62.0.3202.45 (Official Build) beta (64-bit) I get a similar result:
![image](https://user-images.githubusercontent.com/141107/31226450-611ef940-a9d6-11e7-92e8-9ab0aac453ef.png)

**Comment by XhmikosR** [comment]
What's your VGA and driver version? If it's not the latest can you update it? Also, do you recall updating the VGA driver recently?

Finally, could you try the canary build too?

**Comment by udos** [comment]
same effect in Google Chrome (canary), Version 63.0.3233.0 (Official Build) canary (64-bit):
![image](https://user-images.githubusercontent.com/141107/31227096-ed158bba-a9d8-11e7-8e50-aba2b1788ac3.png)

the VGA settings are the following: 
![image](https://user-images.githubusercontent.com/141107/31226966-739e4510-a9d8-11e7-9f9e-09709afce564.png)
note: this is my computer at work where I do not have admin rights. at home I'm not using windows...

**Comment by XhmikosR** [comment]
I certainly feels like a browser bug. But I can't seem to find any common links so far apart from the fact it happen with the latest Chrome stable on Windows.

Can you check your Windows Updates history to see if any Intel VGA drivers were installed recently?

**Comment by udos** [comment]
I just see this (and I don't know if this updates affected vga drivers):
![image](https://user-images.githubusercontent.com/141107/31228060-63ce737c-a9dc-11e7-814d-325bd175f5c8.png)

the strange part about this issue is that when you remove the custom styling, everything is displayed fine. and the edge browser does not have this issue. this might point towards the chrome browser...

**Comment by emilioRamirez24** [comment]
try this on bootstrap.min.css

.fade.in{opacity:1;-webkit-backface-visibility: hidden;}

**Comment by XhmikosR** [comment]
Closing this as I'm pretty sure it's the same as #24233. See https://github.com/twbs/bootstrap/issues/24233#issuecomment-334471177 for more info.
