### ISSUE TITLE
Big dropdowns are unusable when used inside an `overflow:scroll` container, due to being constrained inside it

### ISSUE THREAD

**Issue by ronjouch** [twbs/bootstrap#24251]
## Problem

When using a [Bootstrap (4.0.0beta) Dropdown](https://getbootstrap.com/docs/4.0/components/dropdowns/) in an element that is a child of an `overflow:scroll` element, the dropdown is "stuck" inside the container, making it unusable if the dropdown contents are too big horizontally/vertically:

![overflow-scroll_bootstrap-dropdown-fs8](https://user-images.githubusercontent.com/522085/31194832-54d24bda-a916-11e7-9ad3-85541dd35f62.png)

Contrarily, a vanilla HTML `<select>` will merrily bleed out of the `overflow:scroll` element as necessary:
![overflow-scroll_regular-select-fs8](https://user-images.githubusercontent.com/522085/31194823-50451b9c-a916-11e7-85be-41e113fc0895.png)

See demo at [JSFiddle/ronj/t6z6Lnfb](https://jsfiddle.net/ronj/t6z6Lnfb/).

## Use case

A few words on the use case justifying this combination, as shown in the JSFiddle which mimics a webapp I'm working on:

- In the *left sidebar* live a set of filters. It may contain several filters that will consume undetermined vertical space, thus lives in an `overflow-y:scroll` div. Each filter has a dropdown which lets users modify filter options.
- In the *right pane* lives the content, filtered by the filters in the left sidebar.

→ As a user,

1. I *do need* that `overflow-y:scroll` sidebar scrolling behavior (because the list of filters is of undetermined and potentially large height, depending on the number of filters)
2. But filter dropdowns (which can be large, both in width due to length of options and height due to count of options) should be able "escape out of" / not be constrained by the sidebar.

And as shown in the demo/screenshots, vanilla HTML `<select>` don't suffer from this problem, but it's not always practical/possible to revert back to using them, e.g. due to using features specific to Bootstrap Dropdown, or for consistent styling.

## Details

Bootstrap version: 4.0.0-beta

OS/Browser: Ubuntu 16.04.3 / {Chrome 63, Firefox 58}

This issue is a follow-up to [SO / Letting a bootstrap `b-dropdown` escape out of an `overflow:scroll` container](https://stackoverflow.com/questions/46569727/letting-a-bootstrap-b-dropdown-escape-out-of-an-overflowscroll-container), but noticing regular `<select>` are not affected, it starts to look like a bug, thus this issue. Sorry for the noise if I'm missing something obvious / if there's a workaround / if this is a known problem tracked in an existing issue.

Thanks 🙂.

**Comment by danijelGombac** [comment]
Try this:

```
$(document).on('show.bs.dropdown', '.scrolled-heighted-box', function(e) {
        var dropdown = $(e.target).find('.dropdown-menu'),
            dropdownParent = dropdown.parent();

            dropdown.appendTo('body');
        $(this).on('hidden.bs.dropdown', function () {
            dropdown.appendTo(dropdownParent);
        })
    });
```

**Comment by mdo** [comment]
Curious if this is doable with Popper @Johann-S? Previously we have been constrained by the manual placement of dropdowns in the DOM.

**Comment by Johann-S** [comment]
Yep we can add a `container` option the same used for Tooltips/Popovers and the Dropdown will be append inside this other container and will be positioned correctly

**Comment by ronjouch** [comment]
> *Yep we can add a container option the same used for Tooltips/Popovers and the Dropdown will be append inside this other container and will be positioned correctly*

@Johann-S @mdo thanks for the fast feedback 🙂! A proper fix in vanilla Bootstrap would be awesome, because even though the re-parenting trick works for vanilla Bootstrap, it's a no-no for downstream reactive bindings like bootstrap-vue. Quoting @tmorehouse at https://github.com/bootstrap-vue/bootstrap-vue/issues/1163#issuecomment-334291378 ,

> *Re-parenting live reactive components (such as the components inside a dropdown) is not the greatest thing to do with Vue, as it can start complaining that the parent element has changed, cause a re-render (back to the original spot, and cause elements to be "stuck" where ever they weer re-parented if for some reason the original container or component gets removed from the document (i.e. v-if, a route change, etc).*
>
> *The biggest issue is the latter (i.e. dropdown menus that get stuck open on a page when their parent component goes away). While you can try and use beforeDestroy/destroyed hooks to move the content back to where it was supposed to be, it doesn't always work (as the place where it is supposed to be in the DOM no longer exists.. Which can also lead to application memory leaks if event listeners have references to those DOM elements (so they may get removed from DOM, but are still in memory because someone else has a reference to it).*

@tmorehouse anything to comment on that `container` option proposed in [twbs/bootstrap PR#24257](https://github.com/twbs/bootstrap/pull/24257)? I see our [b-popover](https://bootstrap-vue.js.org/docs/components/popover) / [b-tooltip](https://bootstrap-vue.js.org/docs/components/tooltip) components do expose it and would assume a similar property looks portable to b-dropdown too, right?

**Comment by tmorehouse** [comment]
@ronjouch regarding b-popover/b-tooltips, dynamically _new DOM elements_ are created and appended to the DOM (body by default, or the optional container) when the tip/popover opens.  b-dropdown is different in that reactive content (i.e. the dropdown items which most likely have event listeners) are created by components outside of the dropdown component scope (even through they are children)

We could try a re-parenting option, but it would require a new "dumb" wrapper element around the `.dropdown-menu` that Vue.JS doesn't monitor.  The only issue is that anything that dynamically changes in the dropdown component (i'e button text, enabling/disabling split button, variants, etc) that would cause Vue to re-render the component would most likely create _new_ elements, leaving the r-parented sub-items duplicated with one batch "stranded" in the DOM.

**Comment by FezVrasta** [comment]
An usually unknown behavior of DOM and CSS is that an `overflow: scroll` element doesn't implicitly means that nothing can actually overflow from its boundaries.

https://codepen.io/FezVrasta/pen/GOoRxM

The only situation when an `overflow: scroll` element becomes completely "un-overflowable" is when it also has a `position` different from `static`

https://codepen.io/FezVrasta/pen/KyVKRb

This behavior can be leveraged to make a popper overflow its scrolling parent.

**Comment by tmorehouse** [comment]
@FezVrasta this appears to be a bit buggy in Firefox, and doesn't handle when the dropdown is wider than the container.  It is still partially off screen.

**Comment by FezVrasta** [comment]
@tmorehouse the problem with col-2 is because Popper.js is not yet optimized for this use case.

About Firefox, it looks like it's only the `outline` property that acts weirdly, other styling is fine.

**Comment by tmorehouse** [comment]
@FezVrasta, @Johann-S @mdo @ronjouch   For Bootstrap-Vue we have just added an option (via PR https://github.com/bootstrap-vue/bootstrap-vue/pull/1440) to change the `modifiers.preventOverflow.boundariesElement` (i.e. from the default of `scrollParent` to `viewport` or `window`), and if anything other than `scrollParent` is set, we add the CSS `position: fixed` to the outer wrapper around the dropdown button(s) (we always wrap the dropdown button(s) in a `.btn-group`, even when the dropdown is not in split mode).

This appears to work well from our tests so far, while still preserving the default behavior when scrollParent is set as the `boundariesElement`

**Comment by Johann-S** [comment]
seems nice @tmorehouse I'll give it a look :+1:

**Comment by tmorehouse** [comment]
We have also done something similar for popover/tooltips (without the use of `position: fixed`, but with the `boundariesElement` option), which allows the popover/tooltip placement to work when the trigger element is inside an element with `overflow: scroll`).  `position: fixed` wasn';t needed in this case as teh tooltips/popovers are typically appended to the body. PR https://github.com/bootstrap-vue/bootstrap-vue/pull/1439

Basically we have added a `boundary` config property in the tooltip class (defaults to `scrollParent`), which the user can override.  The `boundary` value is passed directly to the Popper config `modifiers.preventOverflow.boundariesElement`:
- Default Config:  https://github.com/bootstrap-vue/bootstrap-vue/blob/b007b09ddef97abe90501bd64a9c2fed379f47ad/src/utils/tooltip.class.js#L74-L91
- Popper config: https://github.com/bootstrap-vue/bootstrap-vue/blob/b007b09ddef97abe90501bd64a9c2fed379f47ad/src/utils/tooltip.class.js#L878-L898

**Comment by tmorehouse** [comment]
@Johann-S I could create a couple of PRs that would address this issue for dropdowns and for tooltips/popover (would just be a few lines of code in the tooltip class, and a few lines in the dropdown plugin).

**Comment by mdo** [comment]
@SoftCircuits Commenting on a four year old issue without looking through the referenced issues and PRs isn't helpful. We did ship an official response by adding boundary options in the plugins. See https://github.com/twbs/bootstrap/pull/24976.

If you're still having an issue, I highly suggest opening a new issue with a live demo to see if there's something else we can do.

**Comment by SoftCircuits** [comment]
> @SoftCircuits Commenting on a four year old issue without looking through the referenced issues and PRs isn't helpful. We did ship an official response by adding boundary options in the plugins. See #24976.

You have to keep in mind that not everyone is as familiar with where everything Bootstrap is located, as you may be. Rest assured, I've spent considerable time searching and have tried, without success, numerous posted workarounds. And, as you point out, many of those discussions are quite dated. So I don't view that as a mistake I made.

But I appreciate the link and will explore it more completely. Thanks.

**Comment by SoftCircuits** [comment]
@mdo I don't know if that was specific to Popper.js but I this doesn't appear to work for me using v4.3.1. I even copied his markup into my project and the dropdown is still clipped.

**Comment by TondeMoon** [comment]
@SoftCircuits if you add data-boundary="viewport" to bootstrap menu element and position-static to parent container with .dropdown class, the problem goes away. Positioning is still not ideal but it works.
