### ISSUE TITLE
Tab and paging active class collision

### ISSUE THREAD

**Issue by ohammersmith** [twbs/bootstrap#24250]
If I have a tab container with a paging control inside the first tab, the first switch back to the first tab will display both tabs. Subsequent tab switches display correctly, but lose some classes and may no longer animate the fade.

Example: https://codepen.io/ohammersmith/pen/jGaxNM

1. Refresh the page
2. Click the second tab
3. Click the first tab
4. See both tab contents

The issue seems to be that the `active` class on the `nav-link` gets that element picked up by the tab switching. You can see that visually... we lose the current page style on the paging button.

Note: further switches are displayed correctly, but the `show` and `fade` classes are lost. I'm not entirely sure why both tabs don't end up hidden without the `show` class.

No patch because the couple simple fixes I tried weren't complete fixes. I maybe able to contribute a patch later.

Chrome: Version 61.0.3163.100 (Official Build) (64-bit)
OS X: 10.12.6

**Comment by XhmikosR** [comment]
I believe this is fixed in v4-dev. It must be https://github.com/twbs/bootstrap/pull/23087.

/CC @Johann-S

**Comment by Johann-S** [comment]
Yep already fixed by #23087

**Comment by ohammersmith** [comment]
Awesome, thanks! I missed it when I searched.
