### ISSUE TITLE
Docs: Contradiction in documentation about whether containers are necessary to use grid layout

### ISSUE THREAD

**Issue by rgov** [twbs/bootstrap#24261]
The [Layout - Overview](https://getbootstrap.com/docs/4.0/layout/overview/) page says (emphasis theirs):

> Containers are the most basic layout element in Bootstrap and are **required when using our default grid system**. 

But [Layout - Grid](https://getbootstrap.com/docs/4.0/layout/grid/) says:

> **Need an edge-to-edge design?** Drop the parent .container or .container-fluid.

That seems to be a contradiction.

**Comment by mdo** [comment]
Grid docs have since been updated—latest release will clarify this more. Peep the latest `navbar.md` file in `v4-dev`.
