### ISSUE TITLE
Docs: Describe compiled CSS files in download bundle

### ISSUE THREAD

**Issue by rgov** [twbs/bootstrap#24262]
I downloaded the pre-compiled bootstrap-4.0.0-beta-dist.zip and it includes three flavors of CSS files:

- bootstrap-grid.css
- bootstrap-reboot.css
- bootstrap.css

It didn't seem evident from a few searches whether I needed all 3 files, whether they referenced each other with `@import`, or what. The only reference I can find in the documentation is this on the Download page (emphasis mine):

> Download ready-to-use compiled code for Bootstrap v4.0.0-beta to easily drop into your project, which includes:
> - Compiled and minified CSS bundles (**default, grid-only, and Reboot-only**)
> - Compiled and minified JavaScript plugins

These references cannot be found by search, since they don't match the file name.

It would be nice if the documentation went into more detail about these.

**Comment by XhmikosR** [comment]
Agreed. This could be clearer. PRs are welcome.

/CC @mdo
