### ISSUE TITLE
Dropdown and detectNavbar

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#24267]
Is there a reason why detectNavbar selector is not part of config options?

It could be an option like

data-navbar=".my-navbar"

Then the functionality could be extended to custom navbars.

**Comment by Johann-S** [comment]
Nope I just didn't handle that use case but we use the closest navbar

**Comment by danijelGombac** [comment]
It could be default '.navbar', but if someone need disable popper in custom navigation can use different selector to disable it.

**Comment by Johann-S** [comment]
This PR will allow you to disable Popper.js https://github.com/twbs/bootstrap/pull/24092

**Comment by danijelGombac** [comment]
Ok, thanks. I have another question. Why is used:

`!$(parent).closest(Selector.NAVBAR_NAV).length`

and not

`!this._inNavbar`

Is not the same? Navbar_nav should be inside navbar

**Comment by Johann-S** [comment]
Yep we can change that 👍

**Comment by Johann-S** [comment]
I think we can close this issue @danijelGombac ?

**Comment by danijelGombac** [comment]
Yes, thanks.
