### ISSUE TITLE
TextArea Required in Chrome and IE11 not shown has-danger

### ISSUE THREAD

**Issue by quizzlemanizzle** [twbs/bootstrap#24266]
In my angular page I have a text area input in a modal dialog

<textarea #inputElem #textarea="ngModel" class="form-control" rows=4 required [(ngModel)]="textareaValue" [ngModelOptions]="{standalone: true}">

when the dialog is shown the textarea is focused. In Firefox the text area is correctly marked with a red outline has-danger.

In Chrome and IE11 the red outline is missing.

When I inspect the dom element however I see in both cases that the text area is nested in a div with class=has-danger but it seemlingy just has no effect.

When I type I see it changing to has-success, when I delete all input and leave the textarea it changes to has-danger again but the display does not change.

- Windows
- IE11, Chrome61, FF55
- bootstrap-4.0.0.beta

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by quizzlemanizzle** [comment]
https://github.com/twbs/bootstrap/issues/23391
