### ISSUE TITLE
Issues for .fixed-top/.fixed-bottom navbars (Bootstrap v4.0.0-beta)

### ISSUE THREAD

**Issue by vadikom** [twbs/bootstrap#24260]
Hey guys, here's a short list of issues I stumbled upon in Bootstrap v4.0.0-beta (while working on the Bootstrap 4 addon for [SmartMenus jQuery](http://vadikom.github.io/smartmenus/src/demo/bootstrap-4-navbar.html)):

1. For `.fixed-top`/`.fixed-bottom` navbars `.navbar-collapse` doesn't have something like `overflow-y: auto; max-height: 360px;` (as in BS3) so the content cannot be scrolled and might be cut if too tall.
2. For `.fixed-bottom` navbars dropdowns are not properly positioned above the navbar.
3. For `.fixed-bottom` navbars `.dropdown-toggle` carets do not point up.

All these are demonstrated and can be tested here:

https://codepen.io/vadikom/pen/EwoKyz

**Comment by Johann-S** [comment]
For your two last points : 
if you want dropdowns positionned above the navbar use `.dropup` 

Side note: in beta 1 we have issue with dropup in navbar but it's already fixed in our current code and will be available in our next release

**Comment by vadikom** [comment]
Ah, I missed `.dropup`, thanks!

BTW, sorry for a dumb question I guess - in which branch is you most current dropdown code? Thanks!

**Comment by Johann-S** [comment]
use our `v4-dev` branch :+1:

**Comment by XhmikosR** [comment]
@Johann-S @mdo: that is why the bottom navbar example doesn't look good in small res? I haven't had the time to dig into this, just noticed it.

<img src="https://user-images.githubusercontent.com/349621/31798109-9389f42e-b53a-11e7-828a-ee1214dbcc60.png" alt="screen shot 2017-10-20 at 02 00 32-fullpage" height="500">

**Comment by Ghost180195** [comment]
Don't you forget about` max-height: %` and `overflow-y: scroll` for` .navbar-collapse`?

**Comment by mdo** [comment]
Punting second part of this to #24796.
