### ISSUE TITLE
nav-tabs: Inactive tab gets highlighted when tab change initiated by URL change in Angularjs (1.6) application

### ISSUE THREAD

**Issue by jannis-baratheon** [twbs/bootstrap#24275]
# Info

**Operating system and version:** Windows 10
**Browsers:** Chrome 61.0.3163.100 64-bit, Firefox 56.0 32-bit, Microsoft Edge 40.15063.0.0
**Reduced testcase:** https://codepen.io/jannis-baratheon/pen/JrpPXq
**Reproduction rate:** 100%

Please find attached a recording of the issue.

# Reproduction

1. Go to the TC in debug mode: https://s.codepen.io/jannis-baratheon/debug/JrpPXq/xnkabdVDZYOM#!/root/child1
2. Click on the 'Child 2' tab. The URL will change to https://s.codepen.io/jannis-baratheon/debug/JrpPXq/xnkabdVDZYOM#!/root/child2
3. Edit the URL in the URL field manually back to https://s.codepen.io/jannis-baratheon/debug/JrpPXq/xnkabdVDZYOM#!/root/child1

**Expected result:**
The tab changes to 'Child 1' and the tabset looks exactly as it did initially. ('Child 1' tab active, 'Child 2' tab inactive)

**Actual result:**
The tab changes to 'Child 1' but 'Child 2' tab has a highlight on it (the same way when the cursor is above it). Clicking anywhere in the page (apart from the tabset area) brings it back to normal.

![bootstrap_tabset_bug](https://user-images.githubusercontent.com/16115936/31269867-6406f836-aa82-11e7-98be-00ee69d7e79c.gif)

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

Side note : IMO that's not related to Bootstrap but Angular
