### ISSUE TITLE
html5 attribute hidden doesn't work

### ISSUE THREAD

**Issue by sunq0001** [twbs/bootstrap#24276]
OS: windows, only tested OS.
Browser: any browser. 

if i don't use boostrap class. below button can be hidden by 
` <input type="button" value="button" hidden>`

if i add `class = btn btn-default`, the button couldn't be hidden. 

but it can work fine for some other tags, such as
`<p class='well' hidden>i am well</p>`
this can be hidden with bootstrap class.

is it a bug?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by sunq0001** [comment]
http://jsbin.com/fuvecet/1/edit?html,output

**Comment by alecpl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
```
Note: Changing the value of the CSS display property on an element with the hidden attribute
overrides the behavior. For instance, elements styled display: flex will be displayed despite
the hidden attribute's presence.
```
So, this would be `display:inline-block` on .btn.

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
