### ISSUE TITLE
Card with .card-img-overlay and overflowing text

### ISSUE THREAD

**Issue by klor** [twbs/bootstrap#24285]
Cards with lots of text do not keep overflowing text inside the card box (Bootstrap 4).

In the example below, the card text overflows the H1 and div.row below it. The example uses an [image overlay](https://getbootstrap.com/docs/4.0/components/card/#image-overlays) example from the docs.

Screenshot:
![image](https://user-images.githubusercontent.com/129573/31305598-c61c2d1e-ab3d-11e7-9aaf-561719a423b2.png)

HTML:

```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Cards</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>


<div class="container">
    <div class="card bg-dark text-white">
      <img class="card-img" src="http://lorempixel.com/1822/937/sports/" alt="Card image">
      <div class="card-img-overlay">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">Last updated 3 mins ago</p>
      </div>
    </div>

    <h1>My heading</h1>
    <div class="row">
        <div class="col">
            <p>Some stuff</p>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

</body>
</html>
```

Windows 10.
Fails in Firefox 56 (all add-ons and plug-ins are disabled) and Edge. Works in IE11.

My workaround is to add "overflow-y: hidden;" to hide overflowing text on small screens, as shown here:

	<div class="card" style="overflow-y: hidden;">

**Comment by eddiecervello** [comment]
Try deactivating plugins in firefox?

I did a cross browser test using the code you supplied and get the following results:

<img width="1145" alt="screen shot 2017-10-07 at 4 12 19 pm" src="https://user-images.githubusercontent.com/17179138/31311833-5862252a-ab7a-11e7-9928-5065b11e8819.png">

**Comment by eddiecervello** [comment]
Add some media queries in CSS to change the font size on when the window scales down.

**Comment by andresgalante** [comment]
The overlay is an absolute positioned layer on top of the card:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L112-L120

I would not add an overflow hidden to the card, it will have other undesired side effects.

@mdo What do you think about this one? Until we have a parent select on CSS I don't see a good solution. Should we just leave it as is and add a note on the docs about this overflow?

**Comment by mdo** [comment]
I think this falls under something we shouldn't worry about. You'll need to manually adjust `background-image`s and `background-size`s and all that jazz to best suite your content. I don't think this warrants a docs note.

**Comment by MweuD** [comment]
For once bootstrap 4 has failed me

**Comment by robertandrews** [comment]
I just hit this issue. It doesn't seem in line with responsiveness. I am searching for the best way to avoid text busting out over the card boundary, as it looks terrible. People are advising me to jigger with responsive text sizes, but that doesn't feel right.
