### ISSUE TITLE
 Bootstrap modal background fade in screen showing whit space

### ISSUE THREAD

**Issue by MohammedMubeen** [twbs/bootstrap#24287]
Hi, Folks,
![whitespace](https://user-images.githubusercontent.com/26380140/31308013-9d0ef8f8-ab8c-11e7-9f2c-35762e6d350d.png)

Anyone, please help me.
Bootstrap modal background fade in screen showing whit space, please refer the above screenshot. This issue happens chrome only.
Version 61.0.3163.100 (Official Build) (64-bit).

bootstrap version 3.3.7

**Comment by rafalp** [comment]
This is duplicate of following issue:

https://github.com/twbs/bootstrap/issues/24233

**Comment by MohammedMubeen** [comment]
@rafalp Thanks for your response, now its working for me.
