### ISSUE TITLE
feature request: border positive classes (adding specific borders instead of removing)

### ISSUE THREAD

**Issue by yuvii** [twbs/bootstrap#24282]
I really like the `.border` class. However, I find I constantly add this to my code:

```
@border : 1px solid #e9ecef !important;
.border-top    { border-top:    @border; }
.border-right  { border-right:  @border; }
.border-bottom { border-bottom: @border; }
.border-left   { border-left:   @border; }
```
(I'm using Less, but you get the idea).

It's a quick addition which makes things a bit more readable, so instead of doing this:

`class="border border-top-0 border-left-0 border-right-0"`

I do this:

`class="border-bottom"`

I think it makes sense, and it's really easy to add.

**Comment by mdo** [comment]
This was added in #25021.
