### ISSUE TITLE
Input file not working

### ISSUE THREAD

**Issue by Sjoerrdd** [twbs/bootstrap#24286]
Hello,
[this](https://getbootstrap.com/docs/4.0/components/forms/#file-browser) doesn't work for me, i'm using chrome version is 61.0.3163.100.
instead of the upload box, im seeing this: https://gyazo.com/47012759c87e36ba53b0fc094f38e9c6

**Comment by bardiharborow** [comment]
Cannot replicate with Chrome 62.0.3202.38 on Mac OS X 10.12.4. Are you able to go to `chrome://version` and provide us with your full `User Agent`?

**Comment by patrickhlauke** [comment]
I'll hazard a guess that it's due to the fact that custom file input https://getbootstrap.com/docs/4.0/components/forms/#file-browser generates the text for placeholder/button based on language (i.e. `lang(en)`) and your language is set to dutch?

**Comment by patrickhlauke** [comment]
we should probably have a fallback (english) in the distribution version so that the custom file input doesn't look empty when the site *author* hasn't customised it to all possible languages that a site *visitor* may have. @mdo

**Comment by Sjoerrdd** [comment]
user-agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
--

**Comment by patrickhlauke** [comment]
xref https://github.com/twbs/bootstrap/pull/24259

**Comment by Johann-S** [comment]
The answer is what @patrickhlauke said 👍 

Closed related to #24259
