### ISSUE TITLE
Indicate getbootstrap.com website freshness (documentation version)

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#24288]
According to report #23347 , issue #23769 was fixed by pull request #24199 5 days ago. Unfortunately, I still see the bug on [the affected page](https://getbootstrap.com/docs/4.0/getting-started/introduction/).

And since I do not see any indication of which revision of the documentation the website serves, I am unable to confirm or infirm that the commit fixes the bug. Please indicate the version of the documentation somewhere on https://getbootstrap.com/

**Comment by mdo** [comment]
It says on the homepage that it's v4.0.0-beta. We update our docs when we ship a new release. Until then, everything is in development.

**Comment by Chealer** [comment]
@mdo, sorry for not specifying, but the case I described in the first paragraph was just an example. Thanks for the information but I was not just asking for help reviewing the case I described. This request is to make it possible for anyone to tell which revision of the code getbootstrap.com is running.

My interpretation of your comment is that the website's Bootstrap version is 4.0.0-beta, while the revision of the documentation may be different. If that is the case, then I think it would indeed be best to specify **both** the version of the documentation served, and the version of Bootstrap deployed.

**Comment by patrickhlauke** [comment]
the documentation is always in line with the latest release you get if you downloaded/followed the instructions on http://getbootstrap.com/. this is the released/deployed version of bootstrap.

updates are then made to the repo (in the `v4-dev` branch). if you're working off of the latest github repo version, you also need to build the latest docs locally yourself.

**Comment by Chealer** [comment]
This issue persists. Can someone reopen?
