### ISSUE TITLE
Allow for popovers to stay open while hovered

### ISSUE THREAD

**Issue by ashkitten** [twbs/bootstrap#24290]
When I hover a popover trigger, then move my mouse the popover that appears, I expect for the popover to stay open as long as my mouse is on either the trigger or the popover itself. Can this behavior be implemented?

I would provide a gif of this behavior but I'm not sure how to record it.

**Comment by lucascono** [comment]
You mean this @ashkitten? https://codepen.io/lucascono/pen/QqQXjB

**Comment by ashkitten** [comment]
@lucascono no, the popup should stay open if you move the mouse from the trigger to the popup

**Comment by patrickhlauke** [comment]
i assume you mean tooltips, rather than popovers?
https://getbootstrap.com/docs/4.0/components/tooltips/ show on hover, while popovers are explicitly triggered (and stay open) https://getbootstrap.com/docs/4.0/components/popovers/

**Comment by patrickhlauke** [comment]
further, assuming you do mean tooltips: do you want them to remain open because you have interactive content inside the tooltip? if so, i'll warn you that this will be problematic for keyboard users at this point, as they won't be able to go into the tooltip content (though this *could* be solved by extra JS that ensures that the tooltip stays open if the user's keyboard focus went into it, and making sure the tooltip comes straight after its triggering element in the dom/tab cycle)

**Comment by ashkitten** [comment]
I mean popovers, actually. The popovers must be enabled manually, but can be triggered without extra JavaScript.

**Comment by patrickhlauke** [comment]
ah sorry, popovers with `data-trigger="hover"` you mean? (seems we don't have any live examples in the docs, which is why i missed it)

**Comment by ashkitten** [comment]
Exactly.

**Comment by Erwane** [comment]
+1 for this

**Comment by samirmember** [comment]
+1

**Comment by aidabenzid** [comment]
+1

**Comment by icex** [comment]
+1

**Comment by florianlacreuse** [comment]
@patrickhlauke @Johann-S Do you have any feedback to give us about it? If such an option were available, we would use it. However, I would understand if this request is denied because of a11y constraints. Thanks.

**Comment by Johann-S** [comment]
I think something like that can be usable: https://codepen.io/Johann-S/pen/bOGzBw

**Comment by florianlacreuse** [comment]
@Johann-S Thanks but unfortunately, it's not exactly what @ashkitten described. FWIU he want to able to select text for example in this simple case https://codepen.io/anon/pen/VqYgOw.

**Comment by Johann-S** [comment]
Hmm ok I understand thanks @florianlacreuse 👍 
I don't have any concerns about adding that feature

**Comment by florianlacreuse** [comment]
Great! I'm not good enough in JS to do it myself but I hope someone with the necessary skills will.

**Comment by ashkitten** [comment]
> @Johann-S Thanks but unfortunately, it's not exactly what @ashkitten described. FWIU he want to able to select text for example in this simple case https://codepen.io/anon/pen/VqYgOw.

hi, please use they/them pronouns for me

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
