### ISSUE TITLE
About a static version of the documentation downloadable

### ISSUE THREAD

**Issue by fhermeni** [twbs/bootstrap#24295]
I wanted to get an offline version of the documentation to work while travelling.
Sadly, once downloaded, I saw that several softwares/packages/.. are required.

This seems not very user-friendly to me. The documentation is purely static.
I don't have the ruby and the node stack installed, I don't need them to do my work. Why not just providing a zipped version of the doc ? Like for Java, Python, Php.

**Comment by XhmikosR** [comment]
When beta2 is released, you can use the site offline.

Otherwise just download the source zip and look at the md files.
