### ISSUE TITLE
Bug with multiple data-toggles

### ISSUE THREAD

**Issue by zfrenchee** [twbs/bootstrap#24291]
I have a `list-group` with `list-group-item`s which data-toggle `tab-content`s. 

In those `tab-content`s I have a `nav-tabs` with `nav-link`s which data-toggle a set of `tab-pane`s. 

When I click the `list-group-item`s, it becomes obvious very fast that the way you would like this state machine to work is broken, probably because of crossing data-toggle paths. I start to get strange repeated `tab-pane`s in a single `tab-content`s. 

I thought this might be something else, but after a a bunch of successive refreshes, it seems the pattern of irregular UI artifacts is standard across refreshes, which suggests there's a logic error somewhere in the data-toggle code (or you aren't supposed to use data-toggle at multiple levels). 

It comes down to which `tab-pane`s are classed `active`. The strange UI effects I'm getting are from not handling the `addClass` and `removeClass` cases perfectly. 

Bootstrap 4 beta (latest). macOS 10.13 (High Sierra). Chrome 61.

**Comment by zfrenchee** [comment]
I have two different divs classed as `tab-content`. Is there a way to disambiguate these?

**Comment by XhmikosR** [comment]
See #23087.

**Comment by zfrenchee** [comment]
@XhmikosR so this is going to be fixed in v4 Beta 2? Did I read that right? If so, is it available via CDN or do I just have to wait?

**Comment by XhmikosR** [comment]
Beta 2 hasn't released yet.
