### ISSUE TITLE
Modal doesn't open without popper.min.js

### ISSUE THREAD

**Issue by m01key** [twbs/bootstrap#24304]
Modal component doesn't  work without including popper.min.js before bootstrap.js, console shows the error "Bootstrap dropdown require Popper.js"
Bootstrap v4

**Comment by Johann-S** [comment]
Indeed Bootstrap depends on Popper.js for our Tooltips/Dropdown and Popovers plugins.

@XhmikosR what do you think about moving this test : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L15-L21 in our plugins constructor ? 
Because folks who don't need to use those components, should be able to do that without this error

**Comment by XhmikosR** [comment]
@Johann-S: wouldn't then throw for people who don't want to use those components?

How about we have an extra global var like `needsPopper` and act accordingly in our constructor?

**Comment by Johann-S** [comment]
Nope people we'll only see this error if they are trying to use our Dropdowns/Tooltips or Popovers
seems a bit redundant because we can simply check if `Popper` is available or not

**Comment by XhmikosR** [comment]
@Johann-S: please make a PR and CC me.

**Comment by Johann-S** [comment]
Finally it seems we have no solution here (see : https://github.com/twbs/bootstrap/pull/24306)
so @m01key you have to add Popper.js because 3 of our plugins use it or you can wait for our next release which will add a new dist file with Popper.js inside

**Comment by XhmikosR** [comment]
Either we do what I suggested and throw in the constructor if a component which requires popper is used, or we leave it as it. Otherwise it will throw an error even though one might not use a popper descendant component.

**Comment by Johann-S** [comment]
Maybe I don't see how you'll do that but for me it wont change anything because our plugins are wrapped into IIFE ended with : `})($, Popper)`

**Comment by XhmikosR** [comment]
True that. Not sure if there's another way to do things, but with our current implementation I don't think we can do a lot.

**Comment by Johann-S** [comment]
true, it's hard to add optional dep :worried:

**Comment by Johann-S** [comment]
Maybe instead of throwing an error we should just use `console.warn` ? @XhmikosR
