### ISSUE TITLE
Collapsed Nav doesn't expand when popper.js and bootstrap.js are combined and minified

### ISSUE THREAD

**Issue by Fyrebox** [twbs/bootstrap#24302]
After combining Popper.js and Bootstrap.js and uglifying them, the collapsed nav doesn't expand when you clicked on it. Here is a reduced case on Codepen:
[https://codepen.io/anon/pen/oGqoPZ](https://codepen.io/anon/pen/oGqoPZ) 

Steps to reproduce the problem:
- reduce the window size to see the collapsed navbar
- Click on the 3 bars to expand
-> The navbar won't slide down

Tested on Chrome, Safari and Firefox. The same code works fine when files are loaded separately

**Comment by Johann-S** [comment]
Sorry we cannot handle how you bundle those two files but in our next release we will provide a bundle of Bootstrap with Popper.js inside see : https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.bundle.min.js

and it works perfectly with this file :+1:

**Comment by Fyrebox** [comment]
Worked like a charm, thanks
