### ISSUE TITLE
Problem with "d-*" classes (display properties)

### ISSUE THREAD

**Issue by lcassisi** [twbs/bootstrap#24301]
I think there's an issue with some display properties. They work only if a width is specified. E.g.: "d-none" is not working, but "d-xs-none" it is.

**Comment by lucascono** [comment]
"d-none" work. See https://codepen.io/lucascono/pen/xXWdBo

**Comment by lcassisi** [comment]
You are right Lucas. I'd changed xs breakpoint value and than explains the problem. I think that's the expected behaviour.

**Comment by lucascono** [comment]
@lcassisi that's right. You can delete, change and add all the breakpoints you need, but the first one must always have a value of 0.

Even if you look at the variables included with Bootstrap you will see that there is a function that verifies this.

```scss
@include _assert-starts-at-zero($grid-breakpoints);
```
