### ISSUE TITLE
.nav-pills links - wrong nesting in nav.scss 

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#24307]
In tabs we have correct nesting logic:
```
.nav-tabs {
    .nav-link.active,
    .nav-item.show .nav-link {
        ...
    }
}
```

But in .nav-pills it's incorrect:

```
.nav-pills {
    .nav-link {
        &.active,
        .show > & {
            ...
        }
    }
}
```

Basically `.show > &` means `.show > .nav-pills .nav-link`, but should be `.nav-pills .show > .nav-link`

**Comment by Johann-S** [comment]
It seems related to our v4, is that true @Kopyov ?

**Comment by Kopyov** [comment]
Yes, that is correct - in Beta. Sorry didn't mention it

**Comment by XhmikosR** [comment]
I think this was changed recently here https://github.com/twbs/bootstrap/pull/22513

**Comment by andresgalante** [comment]
@Kopyov thanks for reporting it, @XhmikosR is right, it was fixed: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_nav.scss#L80
