### ISSUE TITLE
List group top border is missing in the card body

### ISSUE THREAD

**Issue by hirenbhut93** [twbs/bootstrap#24300]
After the merge #23108 PR is missing top border in some card layout, see my attached image.

![screenshot-getbootstrap com-2017-10-04-23-16-24](https://user-images.githubusercontent.com/8121721/31319388-02ca077a-ac80-11e7-81b6-e1c04652fb60.png)

**Comment by Soundharyaam** [comment]
Hi @hirenbhut93 . I would like to work on this issue.

**Comment by vishub** [comment]
Hi @Soundharyaam 
i detect same problem.

**Comment by mdo** [comment]
Gah, my bad. I never checked the other examples I think and the original bug report wasn't a bug at all. Reverted PR over at https://github.com/twbs/bootstrap/pull/24411.
