### ISSUE TITLE
Missing margin-top in headings: $headings-margin-top

### ISSUE THREAD

**Issue by elpescador-nl** [twbs/bootstrap#24314]
There is a `$headings-margin-bottom`, but there is no `$headings-margin-top` variable.
I think this should be added.

**Comment by andresgalante** [comment]
Hi @elpescador-nl I see your point but since Bootstrap doesn't add margin top to headers I think this is something users can add to their codebase.

**Comment by elpescador-nl** [comment]
Well there is a `$headings-margin-bottom`, so then I would expect there to be a `$headings-margin-top` as well... or just none of these.
In Bootstrap 3.x there is both a `margin-top` and `margin-bottom`. Is this omitted for a reason in Bootstrap 4?

**Comment by andresgalante** [comment]
@mdo what do you think? Should we add a $headings-margin-top?

**Comment by mdo** [comment]
Nope, we purposely nuke it across the entire project. No need to add a variable for something we assume has a `0` value at all times. https://getbootstrap.com/docs/4.0/content/reboot/#approach
