### ISSUE TITLE
Try out greenkeeper

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24320]
From @tomscholz's [comment](https://github.com/twbs/bootstrap/pull/24298#issuecomment-335017772).

>What about using [greenkeeper.io](https://greenkeeper.io/) to automate dependencies updates?

**Comment by mdo** [comment]
GitHub will be doing this soon, too. https://github.com/blog/2447-a-more-connected-universe

**Comment by XhmikosR** [comment]
Passing on this for now.
