### ISSUE TITLE
Opening a modal will left-shift elements with sticky-top class

### ISSUE THREAD

**Issue by dentych** [twbs/bootstrap#24326]
Hello.

I have come across a very annoying bug. I have created a fiddle for the issue here: https://jsfiddle.net/uc90fupc/

Then problem is something that has been discussed before - the padding-right when opening a modal. I have searched old issues, some said it was fixed in a commit, but here am I still having this issue.

The issue is with *sticky-top*. I have tried to apply it to a navbar. When the modal is opened, the navbar content is slightly shifted to the left. I have tried it with cards/cols as well, where the same issue applies.

The code that applies the padding-right to elements with sticky-top class can be found in PR #23669 (Fix sticky margin when a modal is opened).

**Version stats:**
Operating system: Ubuntu 16.10
Browser version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Bootstrap version: 4.0.0-beta

**Comment by Johann-S** [comment]
Already fixed with our last dist files see : https://codepen.io/Johann-S/pen/BwVWPv

**Comment by dentych** [comment]
@Johann-S I see. And do we know when this will be pushed to any repository other than GitHub master? I tried bootstrapcdn and npm. Neither are updated, it seems.. Downloading bootstrap from GitHub is a bit tedious.

**Comment by Johann-S** [comment]
we hope to ship a new release soon :+1:
