### ISSUE TITLE
navbar items not visible on mobile view [desktop view]

### ISSUE THREAD

**Issue by kodani** [twbs/bootstrap#24331]
I’m using bootstrap 4 and when I do desktop view in mobile. navbar items does not appear. I’m using chrome browser in mobile.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Closing out given lack of demo.
