### ISSUE TITLE
How to show tipsy programatically after an ajax call

### ISSUE THREAD

**Issue by AbhijeetThakur** [twbs/bootstrap#24330]
I want to display tooltip  text dynamically from server using ajax call. Currently tooltip text is not updated on first click because ajax call takes some time to receive the data. 
How can I refresh tipsy or show tipsy tooltip programatically ? 

Thanks in advanced !!!

**Comment by patrickhlauke** [comment]
Please ask on StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
