### ISSUE TITLE
Variables won't overwrite

### ISSUE THREAD

**Issue by kevdotbadger** [twbs/bootstrap#24337]
I'm doing

> @import "../../node_modules/bootstrap/scss/bootstrap";
> @import "variables";

and if I put my variables in this file, the compiled file doesn't take these values. An I doing something wrong?

**Comment by andresgalante** [comment]
Hi @kevdotbadger put your variables before you import bootstrap. We've updated the docs here:
https://github.com/twbs/bootstrap/pull/24186

**Comment by kevdotbadger** [comment]
However, if I import them after I can't use other bootstrap vars within them. I.e If I want to set $breadcrumb-bg: $gray-100; it fails because $gray-100 doesnt exist despite that var existing in bootstrap.

**Comment by martpet** [comment]
```
@import "node_modules/bootstrap/scss/functions";
@import "node_modules/bootstrap/scss/variables";
 
$breadcrumb-bg: $gray-100; 

@import "node_modules/bootstrap/scss/bootstrap";
```
