### ISSUE TITLE
Tweak ESlint rules and git hook

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#24336]
Related to #24323 and ##22919

**Comment by NirvashPrime** [comment]
I see both of the related issues have been closed. Is this still an issue currently?

**Comment by XhmikosR** [comment]
Well we tweaked the rules at some point but they definitely need more tweaking. It'll probably happen in v5.

**Comment by XhmikosR** [comment]
The lint rules have been tweaked.

I don't think we need the hook because it's slow. One can always pass extra flags to existent npm scripts like `npm run js-lint-main -- --fix`.
