### ISSUE TITLE
How to set collapsed" class width dynamically on the basis of number of item total length (length the item in menubar )?

### ISSUE THREAD

**Issue by yadavsunil00001** [twbs/bootstrap#24346]
Hi All, 
             I have a specific problem. By default navigation bar collapsed once it reaches 767px. If the number of item in navigation bar is liitle more and taking space larger than 767px, then they stacked up on second line. 
So my question is how to decide the collapsed size on the basis of number of item in navigation bar so that menu item never comes on second line and if this happen they collapsed.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
General how-to questions cannot be helped here. Much of this depends on your own setup, and isn't something we can help you with.
