### ISSUE TITLE
HTML select tag with Bootstrap 4 Beta has the lower part of some letters like "gqpy"truncated in MS Windows?

### ISSUE THREAD

**Issue by zijianhuang** [twbs/bootstrap#24347]
- Operating system and version: Windows 10 or 7, standard DPI no scaling.
- Browser: FF, Chrome, Edge, IE
- Demo of the bug: https://codepen.io/zijianhuang/pen/RLBZRp

The same page works well in FF, Chrome, Safari on iPad, and Chrome and FF on Android tablets.

The same page but with Bootstrap 3.3.7 works well in browser on MS Windows.

**Comment by fchiumeo** [comment]
duplicate #23347 
fix in #24199

**Comment by zijianhuang** [comment]
Bootstrap 4 Alpha 6 does not have this problem. So I am looking forward to the release of Beta 2, while at this stage I don't want to have a local copy of the fix at #24199.
