### ISSUE TITLE
Modal is not hiding second time after preventing it from hiding with e.preventDefault() and fade mode on

### ISSUE THREAD

**Issue by horovody** [twbs/bootstrap#24343]
# Bug report
`Modal is not hiding second time after preventing it from hiding with e.preventDefault() and fade mode on`

# Versions
Jquery 3.2.1
Bootstrap 4.0.0-beta
Popper.js 1.12.5
Windows 10 / Chrome 61.0.3163.100, 64 bit

# How to reproduce
Please see my [plunkr](https://embed.plnkr.co/OzKpotrxFiVzpE6UhqmS/).

Im trying to prevent modal dialog from hiding with confirm dialog:

`$("#exampleModal").on('hide.bs.modal', function(e){
  if (confirm("Attention! You're about to close this dialog? Ok?")) {
        return true;
      } else {
        e.preventDefault();
      }
});`

After 1st time user prevents a modal from hiding it wont hide again, modal is not responding to user inputs. 

This issue is reproducable with modal animation is on, i.e. modal has class `fade`. When I remove animations it works as expected.

**Comment by bkdotcom** [comment]
when you click close, this is what's happening internally

return if  `_isTransitioning` is true
set `_isTransitioning` to true
trigger `hide.bs.modal` event
if (event isDefaultPrevented) -> return.

so... isDefaultPrevented returned, but left _isTransitioning to true...  which prevents any attempts to dismiss the modal from happening...

looks like bootstrap needs to reset `_isTransitioning`  before the isDefaultPrevented return.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/commit/8e7ba02c5cf56bdc5b4c0fff71edec19ade1e3e9

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/24318
