### ISSUE TITLE
Inconsistent gray-dark

### ISSUE THREAD

**Issue by supergibbs** [twbs/bootstrap#24353]
The color `gray-dark` is specified in the [_variables.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L74) as `gray-800` but in the [theming.md doc](https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/theming.md) as `gray-900`. I'd make a PR but not sure which is right.

**Comment by andresgalante** [comment]
Hi @supergibbs 

The source of truth should be `_variables.scss`. If you don't have time to send the PR please let me know and I'll update the documentation.

Thanks a lot!

**Comment by supergibbs** [comment]
@andresgalante Thanks for the clarification, fixed that and updated the rest of the colors too

**Comment by andresgalante** [comment]
ups sorry, I've just sent a PR. It seems like patience is not one of my virtues.
Please send yours and I'll close mine. I am sorry @supergibbs
