### ISSUE TITLE
Bootstrap 4: Button Dropdown Block - Centered Arrow Placement

### ISSUE THREAD

**Issue by aaroncadrian** [twbs/bootstrap#24351]
Whenever I use a button dropdown with the btn-block class, the arrow indicator for the dropdown is weirdly centered with the text in the button.  

Is there a way to have the arrow flushed to the right like in Bootstrap 3?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Custom CSS or use a segmented button in a button group.
