### ISSUE TITLE
Btn Group does not respect column bounds

### ISSUE THREAD

**Issue by th3fallen** [twbs/bootstrap#24367]
https://codepen.io/anon/pen/mBGpXW

OS: Mac OSX High Sierra
Browser: Chrome 61.0.3163.100

**Comment by adigoun2005** [comment]
I think two options arwe there: 
-> either consider changing the font-size when this occurs in javascript.
Or
->Consider using overflow poperty
.col-3 {
  border: 1px solid red;
}

.btn-group {
  border: 10px solid blue;
  width: inherit; 
  overflow-x: hidden;//or scroll
}
personnaly, i would prefer the fist solution

**Comment by mdo** [comment]
You can wrap this yourself with some flexbox utilities, but there's no planned changes from us for this. Not every component works in every situation.

**Comment by th3fallen** [comment]
@mdo thanks for the message, actually it turns out it's the `white-space: nowrap;` that was causing it for prosperity
