### ISSUE TITLE
Badges invisible on list - ref demo page

### ISSUE THREAD

**Issue by Karan1458** [twbs/bootstrap#24363]
Hello twbs, 

I have been checking out the beta version. Seems like the badges are missing from list group. I checked the CDN version and provided version. Seems like the badges are coming with color #fff, But no background color is set. 

Regards,
Karan
![screenshot from 2017-10-13 21-53-45](https://user-images.githubusercontent.com/7886431/31556063-048e67ba-b061-11e7-8ac4-4bded8f9274f.png)

Ref : https://getbootstrap.com/docs/4.0/components/list-group/#with-badges

**Comment by andresgalante** [comment]
Hi @Karan1458 Thanks for reporting this. It was fixed here https://github.com/twbs/bootstrap/commit/3935e069f0918010840c40939f6de69a17f25438
