### ISSUE TITLE
Long item-list in Dropdown drops-up instead of down :(

### ISSUE THREAD

**Issue by rranke** [twbs/bootstrap#24369]
Long item-list in Dropdown drops-up instead of down :(
I think it should better drop-down instead of drop-up if the item-list doesnt fit either in "up-or-down-case".

Tested with FF on Linux and Safari on iOS 11 on https://getbootstrap.com/docs/4.0/components/dropdowns/

Screenshot reflects the web-browsers current window-size:
![dropdown](https://user-images.githubusercontent.com/5783257/31565717-311d02e4-b068-11e7-9068-4db1152dc77f.png)

**Comment by Johann-S** [comment]
That's the normal behavior but you can disable that with `flip` option https://getbootstrap.com/docs/4.0/components/dropdowns/#options

**Comment by rranke** [comment]
yep, thanks!

adding
```
data-flip="false"
```
to the button fixed that problem.

**Comment by bretonio** [comment]
It sure did and I thank you guys.

**Comment by archyonrails** [comment]
Worked perfectly. Thank you.
