### ISSUE TITLE
Model popup close option is not working when used with tooltips and popovers

### ISSUE THREAD

**Issue by sarveshkumar1991** [twbs/bootstrap#24361]
When we use model popup with tooltips and popovers , close option does't work.

Case 1. When open a model popup with tooltips and popovers , then click on outside the model popup or click on close button , it closed without any problem

Case 2. When open a model popup with tooltips and popovers, then we take cursor on tooltip or click on popover button , now if click outside the model popup or click on close button , it does not close ,  I have to refresh the page.

Please see screenshot for more info or try demo at following link (tooltip and popup section)
https://v4-alpha.getbootstrap.com/components/modal/

![image](https://user-images.githubusercontent.com/25073117/31544574-1c1fa060-b039-11e7-83b0-29f0d4eb77e7.png)

**Comment by Johann-S** [comment]
Please use our latest release : https://getbootstrap.com/docs/4.0/components/modal/
