### ISSUE TITLE
compile error with _root.scss

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#24368]
Hi

If i compile like this  i get an fatal error from the _root.scss ..

// core bootstrap functions
@import "bootstrap/scss/functions";
@import "bootstrap/scss/mixins";
// bootswatch variable overrides
@import "bootswatch/cerulean/variables";
// full bootstrap mumbo humbo
@import "bootstrap/scss/bootstrap";
// bootswatch style overrides
@import "bootswatch/cerulean/bootswatch";

if i comment(remove)  this lines on _root.scss  it's works

```
  @each $color, $value in $colors {
    --#{$color}: $value;
  }

  @each $color, $value in $theme-colors {
    --#{$color}: $value;
  }
```
what i miss ?

https://github.com/thomaspark/bootswatch/pull/685

**Comment by XhmikosR** [comment]
Probably https://github.com/twbs/bootstrap/pull/24354. If that's the case you should use what we use; node-sass. Or wait for the next release.

/CC @glebm for confirmation.

**Comment by glebm** [comment]
This is most likely fixed by #24354. @jipexu Simply use a more recent version of Bootstrap v4-dev.

**Comment by jipexu** [comment]
@glebm  @XhmikosR thanks i will try with this new PR

**Comment by jipexu** [comment]
with the last version i still have this error

```
Error: Invalid CSS after "...lor}: #{$value}": expected "{", was ";"
        on line 4 of /Users/jpb/Documents/developpement/testcsscompile/scss/_root.scss
        from line 11 of /Users/jpb/Documents/developpement/testcsscompile/scss/bootstrap.scss
        from line 9 of /Users/jpb/Documents/developpement/testcsscompile/slate/bootstrap.scss
  Use --trace for backtrace.
```

**Comment by glebm** [comment]
What Sass compiler are you using? For Ruby Sass, v3.5.2+ is required

**Comment by jipexu** [comment]
i use koala ...

**Comment by jipexu** [comment]
Sass @ 3.4.23

**Comment by jipexu** [comment]
ok it's work now

**Comment by frizbee** [comment]
Same error with `compass compile`
sass -v 
Sass 3.5.3 (Bleeding Edge)

output:
```
error sass/vendor/bootstrap.scss (Line 4 of node_modules/bootstrap/scss/_root.scss: Invalid CSS after "...lor}: #{$value}": expected "{", was ";")
Compilation failed in 1 files.
```

**Comment by glebm** [comment]
If you use compass, it uses an older version of Sass. Don't use compass.

**Comment by frizbee** [comment]
@glebm Thanks, you're right, didn't know that.

**Comment by geetee24** [comment]
i use jekly.   will the next version beta 3 allow us to use the older compilers?
What is the purpose of the _root.scsss file?
