### ISSUE TITLE
V4 Documentation - Various Issues

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#24373]
The doco. needs to be reviewed by some people who:
a) have never used Bootstrap before
b) have only used v3 before

From the perspective of migrating a site from v3 to to v4, and so far...

I can do a pull request if you don't already have people working on it.

1) Navbar ( https://getbootstrap.com/docs/4.0/components/navbar/ )

Add : For an explanation of the utility classes used here, see:  colours (e.g. bg-light) and spacing (e.g. my-2, m is for margin)

It would be worth doing this for all the components, especially were its not obvious, i.e. text-danger you can guess, my-3 you'd have to know.

2) Display Utility

"Responsive variations also exist for every single utility mentioned above."
Add: These classes effect the breakpoint and above. e.g.
```
<span class="d-md-none">Not displayed on medium and above (i.e. display on small and below)"</span>
<span class="d-none d-md-inline">Only displayed on medium and above (i.e. not on small and below)</span>
```

"Display in print"

There are no d-screen classes, so:
```
<span class="d-none d-print-inline">print only</span>
<span class="d-print-none">screen only</span>
```

3) Cards

Add: Cards have a zero margin by default, so to mimic v3's panels (see spacing utility for an explanation of mb-3)
`<div class="card mb-3"> ... </div>`

**Comment by xdvarpunen** [comment]
@saturdaywalkers Basically complete example would be best. Documentation assumes too much knowledge (:

**Comment by saturdaywalkers** [comment]
"[The] Documentation assumes too much knowledge" - Yes! 
More examples - Yes!

**Comment by XhmikosR** [comment]
You can improve the migration page by submitting a PR.

**Comment by aavmurphy** [comment]
OK, so I did 1 page (navbar). 
There'll be a learning curve for me in doing PR's, e.g. as soon as I made the PR, I saw how to link to other website pages :)
Its a little hard to test without a local copy of the bootstrap website
Added
1) a reference to (not navbar) classes used, e.g. my-2, 
2) navbar's don't print, so said this, and added a 'print-only' example.
Hopefully, this'll make other think about things that are missing.

**Comment by stephaniepurvis** [comment]
I'll work on adding to the utility class documentation.

**Comment by aavmurphy** [comment]
@stephaniepurvis Have you started utility/display, I was going to do that next.

**Comment by aavmurphy** [comment]
Started doing this as I'm migrating a site to V4, so going through its learning curve. 

One thing that would really help is, in the left-hand-nav, having the 'utility' and 'component' blocks as expandable section of links, as I've been going back and forth between the two a lot. i.e. in navbar, click 'utility' to get (expand)  the list then (say) on 'display', or simply have them all shown.

**Comment by stephaniepurvis** [comment]
@aavmurphy I got busy and haven’t been able to start yet. If you’d like to make edits on this one, please do! Let me know if I can help on anything specific.

**Comment by Herst** [comment]
+aavmurphy
On a side note, if you are migrating a larger project my sadly incomplete but yet possibly useful port of Bootlint might help: <https://github.com/Herst/bootlint>, see the pull request for details: <https://github.com/twbs/bootlint/pull/410>.

I would also gladly accept contributions, I have done most of the work on when I ported my project, but now as the porting of my project has been completed I can't justify spending work time on it.

**Comment by mdo** [comment]
PRs have been merged, and some docs updated for the cards comment.
