### ISSUE TITLE
Grid System ( Bootstrap V4 )

### ISSUE THREAD

**Issue by CrazY770** [twbs/bootstrap#24377]
Hello,  I don't know what is the problem, but the grid system is not functioning properly. The classes justify-content-* and align-items-* do not align absolutely anything, and the columns are one underneath the other, even if they are in the same div (class row). What would be the problem?

P. S: I do not have Internet connection on the computer, but from what I could perceive, only the dropdown requires Internet to work due to a jquery plugin.

**Comment by myorangeca** [comment]
You have to pair those classes with d-flex.

**Comment by andresgalante** [comment]
Hi @CrazY770, @myorangeca is right, you can't justify content or align items if the element is not flexed, this is a reference on how flex works: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes

If you think there is a bug on Bootstrap utility classes please send a codepen or a code sample.

**Comment by CrazY770** [comment]
Well, thanks for the suggestions, but the problem is in version v 4.0.0-Beta. I tested the version 4.0.0-Alpha6, and it's working properly.

**Comment by edwardmp** [comment]
@CrazY770 
I noticed the same, using justify worked fine in alpha6 without using d-flex, but no longer in Beta2. Not sure why it worked in alpha6 but that doesn't seem supported behavior.
