### ISSUE TITLE
btn-group inside of tabs not setting correctly active tab

### ISSUE THREAD

**Issue by foonster** [twbs/bootstrap#24381]
When creating a tab interface and including a btn-group on the first tab.  The entire tab active function becomes confused.  As you click back and forth between the tabs the btn-group will deactivate each btn-group until all are exhausted and then it will start displaying the tabs correctly.

However, after that the btn-groups are non-functional.

https://www.bootply.com/uRr63yABIZ

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/23087
will be available in our next release :+1:
