### ISSUE TITLE
Footer link to Examples is incorrect

### ISSUE THREAD

**Issue by openbuilds-engineer** [twbs/bootstrap#24382]
On the bottom of all pages on http://getbootstrap.com/, the link to "Examples" is incorrect, it point to http://getbootstrap.com/examples/ (404 error) whereas the "Examples" link in the top nav points to http://getbootstrap.com/docs/4.0/examples/ (working page)

![broken link](https://user-images.githubusercontent.com/31449271/31586392-96366954-b1d0-11e7-9bd1-0487a0182064.gif)

**Comment by andresgalante** [comment]
Hi! thanks for reporting it, it was fixed here: https://github.com/twbs/bootstrap/commit/7b8afff038e251acbdb28e455aec886d24a766e7
