### ISSUE TITLE
Use scrollspy in docs ToC

### ISSUE THREAD

**Issue by JamesPierce82** [twbs/bootstrap#24383]
Hello,

I was recently browsing the BootStrap 4 [docs](https://getbootstrap.com/docs/4.0/components/scrollspy/) and found that the scrollspy example does not appear to work in the docs. I remember seeing it work properly in the docs for Bootstrap 3 so was surprised to see it no longer working in the BS4 docs.

As I usually look to the docs for my examples, I hope this issue is able to be resolved.

Thanks in advance for any assistance.

James

**Comment by Johann-S** [comment]
Sorry @JamesPierce82 but our examples works perfectly in our documentation :thinking: 
https://getbootstrap.com/docs/4.0/components/scrollspy/#example-in-navbar
https://getbootstrap.com/docs/4.0/components/scrollspy/#example-with-list-group

**Comment by bkdotcom** [comment]
I'm guessing that @JamesPierce82 is referring to the right-side navigation (`.section-nav`), which doesn't implement scrollspy

**Comment by Johann-S** [comment]
I think you're right @bkdotcom but I'll wait a bit ☺️

**Comment by XhmikosR** [comment]
@Johann-S: what do we need for this to work?

**Comment by XhmikosR** [comment]
It seems we have `<body class="bd-docs" data-spy="scroll" data-target=".bd-sidenav-active">` which is useless in v4, right?

**Comment by mdo** [comment]
Scrollspy isn't implemented in the docs, and it cannot be as we do not control the output of that menu—it's from a Jekyll plugin. I opened #24408 to address @XhmikosR's comment about that `<body>` element's attributes.

**Comment by bkdotcom** [comment]
Jekyll-TOC just released v0.9.0 which *might* [addresses this](https://github.com/toshimaru/jekyll-toc/issues/15)
https://github.com/toshimaru/jekyll-toc/releases/tag/v0.9.0

**Comment by XhmikosR** [comment]
Yeah, I already updated in #27540, still waiting for the ID support.

I already discussed this with @Johann-S so instead of me making a new issue let's re-open this one.

**Comment by mdo** [comment]
Is this still an issue?

**Comment by SevereOverfl0w** [comment]
I'm interested in scrollspy support in my own ToC (based on the bootstrap one).

The docs do specify that:

> It must be used on a Bootstrap nav component or list group.

But I don't think this needs to be a constant necessarily does it? Without the hierarchy functionality, it can work on near enough anything. With the hierarchy functionality, I think it can be inferred from the toc form.

**Comment by mdo** [comment]
Right now scrollspy requires particular markup. I have a new docs design for v5 that eliminates the right side ToC for a central ToC. For now though, given the lack of movement on this issue, going to close this out regardless.
