### ISSUE TITLE
how to hidden content in small screen

### ISSUE THREAD

**Issue by buuug7** [twbs/bootstrap#24387]
i found class `d-sm-none` it only show content that sm and up size, where i expected to hidden something in sm and down screen, is there have some common utilities for use  ?

**Comment by mattruma** [comment]
yes, I discovered the same challenge, what if you want to hide something md and down?

**Comment by chiraggmodi** [comment]
you can combine multiple classes like this `d-none d-sm-flex`

**Comment by XhmikosR** [comment]
Yeah, you need to use a combination of the above.
