### ISSUE TITLE
Should validation use box-shadow?

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#24389]
.form-control inputs when focused do not use box-shadow, so why inputs with .is-invalid/.is-valid do? I propose to get rid of the box-shadow. Or maybe there are some variables that need to be used/set properly?

No test case. All you need is to visit https://getbootstrap.com/docs/4.0/components/forms.

**Comment by alecpl** [comment]
Another inconsistence: `.btn:focus` shadow is disabled on screen width less than 768px. This does not happen on inputs.

**Comment by mdo** [comment]
Yes it should, and I should re-enable the focus shadow on inputs by default.

**Comment by alecpl** [comment]
I understand you want to see focus/validation state at the same time. I'm fine with this as long as it's consistent. Thanks.
