### ISSUE TITLE
Showcase: Soundready is no more. Now you're linking to SPAM

### ISSUE THREAD

**Issue by sesam** [twbs/bootstrap#24384]
On your webpage http://getbootstrap.com/2.3.2/ under the headline "Built with Bootstrap" you link to Soundready.fm but the shut down #16318 and now it's spam.

Please stop linking to them.

**Comment by patrickhlauke** [comment]
to clarify this refers to https://getbootstrap.com/2.3.2/

**Comment by mdo** [comment]
Normally I don't favor editing four year old docs, but I'll fix it up.

**Comment by mdo** [comment]
Removed the links to `soundready.fm`, but left the images in. It'll be a broken link, but that's okay I think (until we get an issue about it 😆).
