### ISSUE TITLE
why i the icon missing? 

### ISSUE THREAD

**Issue by sekti92** [twbs/bootstrap#24391]
Dear Bootstrap, why the icon is missing? Am i need to put font-awesome in my project?

![capture](https://user-images.githubusercontent.com/14885417/31604050-07c12b70-b25a-11e7-9ef8-abff131f210e.PNG)

Result:
![capture1](https://user-images.githubusercontent.com/14885417/31604051-07d9c39c-b25a-11e7-9f6d-eab7f6a4acab.PNG)

**Comment by patrickhlauke** [comment]
for how-to questions, please use stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
