### ISSUE TITLE
Button disabled has the clicked animation if content is an icon

### ISSUE THREAD

**Issue by gygabyte017** [twbs/bootstrap#24394]
If a button with "disabled" attribute has only some text inside, clicking on it has no effect (i.e. the visual content remains the same).

If a button with "disabled" attribute has something else inside like an icon, clicking on the icon still shows the visual "clicking" effect.

See: https://codepen.io/anon/pen/rGqPgL

**Comment by patrickhlauke** [comment]
should be fixed by https://github.com/twbs/bootstrap/pull/23544
