### ISSUE TITLE
[v4.0.0-beta] ".btn-light" class missing in the sources files ?

### ISSUE THREAD

**Issue by nicoguefveneu** [twbs/bootstrap#24397]
Hello,

In the v4.0.0-beta, how come the ".btn-light" class is in the default dist CSS files but not in any source files ?

Therefore, when I run a build ("npm run css"), there isn't the class anymore in the dist CSS files.

Is there something I'm missing ?

Thanks !

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/blob/658e81a0840a2b49e7977206e3d5feabea797677/dist/css/bootstrap.css#L2475-L2501

**Comment by nicoguefveneu** [comment]
I've seen that, but I don't understand where is this code in the sources ?
It should be in the _buttons.scss isn't it ?

**Comment by XhmikosR** [comment]
Of course it exists; the link is from the dist file.

As for how it's generated, why does it matter? It's just a simple Sass function that does it.

**Comment by nicoguefveneu** [comment]
I may be missing something but that's the thing, why is it in a generated file and not a source file ?

**Comment by XhmikosR** [comment]
It **is** in the source file; it's generated by a Sass function like I mentioned above...

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/blob/99eece13929cf69515927a04a176cc3e578c4194/scss/_buttons.scss#L53-L57

**Comment by nicoguefveneu** [comment]
Thanks for the clarification !
