### ISSUE TITLE
'.no-shrink' class may be needed in flex utilities.

### ISSUE THREAD

**Issue by ganeshvelanki** [twbs/bootstrap#24403]
In flex-box utilities need no-shrink class (in my opinion), this helps when someone want to shrink only one row in a page of multiple rows.

**Comment by iatek** [comment]
This would be a nice compliment to the `.flex-fill` class.

```
.flex-shrink {
    flex-shrink: 0;
}
```

I found it's necessary when using flex-column and flex-fill to grow 1 row in height, other rows get squished. Adding `flex-shrink:0` to the other rows prevents this.
