### ISSUE TITLE
Auto-scroll to item when collapsing, if it isn't in the users view

### ISSUE THREAD

**Issue by Klooven** [twbs/bootstrap#24405]
If a link in the footer (**user cannot scroll further down**) opens a collapse **under it**, the user wont see it.

**Could we have some type of auto-scroll in this case?**

See example here: https://jsbin.com/yezuvevici/edit?output

~~Tested on: Windows 10 with Microsoft Edge 40.15063.674.0 and Ubuntu 16.04 LTS with Firefox 56.0~~

**Comment by Johann-S** [comment]
Sorry if I misunderstood something but, user just have to scroll a bit and they will see

**Comment by patrickhlauke** [comment]
I'm guessing you mean "it should auto-scroll into view"?

**Comment by Klooven** [comment]
Yep! I didn't just explain it very well.

**Comment by morrissey-ingenious** [comment]
I would leave this to be a user implemented feature that they call when the event `show.bs.collapse` or `shown.bs.collapse` is triggered.

**Comment by mdo** [comment]
Punting as a won't implement—agree with the latest comment.
