### ISSUE TITLE
Example template doesn't work in IE10 - Nav Issue

### ISSUE THREAD

**Issue by koto4** [twbs/bootstrap#24407]
This example page does not work in IE 10:
https://getbootstrap.com/docs/4.0/examples/jumbotron/

The nav at the top right floats off the page.

Issue screenshot: 
https://www.dropbox.com/s/pqq8gdmy7q1ayc3/nav-v4.png?dl=0

**Comment by XhmikosR** [comment]
The issue isn't present in v4-dev.

**Comment by koto4** [comment]
Don't mind me asking a stupid question - I am a newbie:
What do you mean it isn't present in v4 dev? I downloaded the most recent code and that is what  see. If it's fixed in dev, how do I get that fixed version?

**Comment by XhmikosR** [comment]
Either clone the repo and get the v4-dev branch or download the zip file. All this will be redundant when beta-2 is released, hopefully in the next days.
