### ISSUE TITLE
IE11 mr-auto in flexbox buggy

### ISSUE THREAD

**Issue by BlackDark** [twbs/bootstrap#24413]
![image](https://user-images.githubusercontent.com/9947112/31708760-446e536c-b3f0-11e7-85f5-bf38c9159feb.png)

The mr-auto class for example moving a button to left side of a flex container is not working correctly.
Even the official website http://v4-alpha.getbootstrap.com/utilities/flexbox/#with-justify-content has this problem (see above screenshot).

OS:
- Windows 7
- IE11 (11.0.9600.18792)

**Comment by Johann-S** [comment]
Please us our latest release : https://getbootstrap.com/docs/4.0/utilities/flex/#with-justify-content and let us know if it still occur

**Comment by BlackDark** [comment]
Yes, it still exists. It has even slipped further to right.
![image](https://user-images.githubusercontent.com/9947112/31710213-a5f937c4-b3f4-11e7-8d23-8c0306998c76.png)

**Comment by mdo** [comment]
See #24427.
