### ISSUE TITLE
Input group bug on Ios + Safari

### ISSUE THREAD

**Issue by basmbbl** [twbs/bootstrap#24416]
See https://getbootstrap.com/docs/4.0/components/input-group/
on any iphone / safari. 
See attached
![bs_realios_mobile_iphone 6-8 0](https://user-images.githubusercontent.com/20164457/31720657-71875994-b417-11e7-9a01-7453823b58ff.jpg)

**Comment by patrickhlauke** [comment]
cannot reproduce (iOS 11.0.3)

![photo 18-10-2017 14 21 48](https://user-images.githubusercontent.com/895831/31720927-d918fa3e-b40f-11e7-8f0a-0827df80283d.png)

**Comment by basmbbl** [comment]
It must have been a browserstack thing, i cant reproduce it myself either any more.
