### ISSUE TITLE
`font-weight: 500` with Segoe doesn't exist

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24419]
So, at least for docs, we might want to try something else.

![screen shot 2017-10-17 at 21 38 12-fullpage](https://user-images.githubusercontent.com/349621/31730895-feecd2c2-b43b-11e7-864f-6df0b800c473.png)

**Comment by Varunram** [comment]
What's the status on this? :)

**Comment by XhmikosR** [comment]
Still valid, we'd still need to revisit eventually our `font-weight`s.

**Comment by Varunram** [comment]
Yeah, I mean, I knew it's still valid, but I guess the sidebar now highlights the individual page, so was wondering what happened with Segoe after all. Thanks for replying :)

**Comment by XhmikosR** [comment]
I don't see any change in the behavior...

**Comment by Varunram** [comment]
<img width="1278" alt="screen shot 2018-03-31 at 9 15 19 pm" src="https://user-images.githubusercontent.com/18598959/38164866-a6befa6c-3528-11e8-9622-82ff6276f416.png">

**Comment by XhmikosR** [comment]
That us how it was and is. There has been no change.

Please always check with latest v4-dev. No point in asking if something
should be closed when nothing's has changed.

**Comment by Varunram** [comment]
Sure, sorry for taking up time by asking this, I couldn't see in the first screenshot whether it was highlighted, thanks for responding.
