### ISSUE TITLE
Insufficient documentation for column offsetting

### ISSUE THREAD

**Issue by thepurpleblob** [twbs/bootstrap#24414]
In Grid system > Offsetting columns it says...

> With the move to flexbox in v4, we no longer have v3’s style of offset classes. Instead, use margin utilities like .mr-auto to force sibling columns away from one another.

There is no further clue what this means. What is '.mr-auto'? The example doesn't help. Well, it doesn't help me anyway.

**Comment by jipexu** [comment]
offset are back in next beta ...

**Comment by thepurpleblob** [comment]
Ahh... I assume it's talking about this stuff, http://v4-alpha.getbootstrap.com/utilities/spacing/

How would you know? It needs a link at least.

**Comment by jkry97** [comment]
For me what is not clear from the docs is, using mr-auto/ ml-auto etc., is it possible to achieve what we can with bootstrap 3 offsets.
Say for example I want to create a layout with col-6 offset by 4 cols in a col-12 division.
In BS 3, I could do, `.col-offset-4 .col-6`, how to achieve this in BS 4?

**Comment by thepurpleblob** [comment]
Yeh - I don't get it either. I couldn't get the ml-auto style things to do anything useful. I gave up and stuck some empty columns in. It's not as elegant but gets the job done.

**Comment by jipexu** [comment]
yes not proper way to do every things ...

but be happy all this class are back ...
https://github.com/twbs/bootstrap/issues/23360

**Comment by mdo** [comment]
Closing as offsets are back and with improved docs.
