### ISSUE TITLE
Accessibility nav tabs : disabled tabs need to have tabindex set to -1

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#24436]
To prevent keyboard focus, when a tab is disabled, we need to set the tabindex to -1

http://getbootstrap.com/docs/4.0/components/navs/#tabs

Can be done in static mode for the doc, and also could be managed by the plugin.

Maybe also need to use the aria-disabled attribute to inform screen reader.

**Comment by alecpl** [comment]
Please, fix the title. It's not z-index, but tabindex.

**Comment by Lausselloic** [comment]
oh yes i'm confused

**Comment by Varunram** [comment]
@patrickhlauke Still on this or may I put in a PR? :)

**Comment by XhmikosR** [comment]
@Varunram: I don't even know if @patrickhlauke saw this; I had assigned it to him back then.

So, just go ahead.

**Comment by patrickhlauke** [comment]
Seems to have been sorted now (though one instance of disabled links that are still focusable/not marked with `aria-disabled` remained, which will be fixed by https://github.com/twbs/bootstrap/pull/27788).

Closing (and apologies for not actioning this at the time...life got in the way)
