### ISSUE TITLE
Colour of list item is black instead of white (when `href` is not used)

### ISSUE THREAD

**Issue by iamvitali** [twbs/bootstrap#24433]
**Issue:** When not using `href` tag on list element, once active, the colour of the item is black instead of white.

> - Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)

Windows 7 SP1 x32

> - Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

Chrome, Version 59.0.3071.115 (Official Build) (32-bit)

> - Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

Test case: https://codepen.io/anon/pen/dVaKYB (Latest  Bootstrap v4.0.0-beta)
(On my website the switch between options happens using VueJS and `@change="function"` & `:class="functionToReturnClass(someArg)"` but that is not really necessary to implement in the test case as this is more of a css issue, imho.

**Comment by gijsbotje** [comment]
I found the inherit property of reboot is the one causing this
https://github.com/twbs/bootstrap/blob/ba44eb1279a6b07c07ba2a0694950e843681d176/scss/_reboot.scss#L216
is the line that does this

**Comment by nip3o** [comment]
This is also an issue when using a-tags without href, and with a `.btn` class - for example the text of `<a class="btn btn-primary">Link</a>` will be black (or whatever color inherited) for the same reason.

**Comment by mdo** [comment]
No plans to change this for links without `href`s.
