### ISSUE TITLE
[V4 Beta 2] Outline button mouseover animation is jarring

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#24447]
For a test case, the outline buttons in the docs exhibit the issue. It appears that the font color changes immediately, while the button color transitions. The effect is jarring when compared to the smooth/coordinated transition of V4 Beta 1. See: https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons

This is on macOS 10.13 and Safari 11.0.

Can the behavior be changed back to the pleasant experience from Beta 1?

**Comment by XhmikosR** [comment]
@mdo @andresgalante: maybe we should not add transition for outline variants?

**Comment by mdo** [comment]
That hasn't changed from Beta 1 to Beta 2—the `$btn-transition` variable is still as it has been for the last six months.

**Comment by XhmikosR** [comment]
Yeah, but it still looks weird :P

**Comment by jipexu** [comment]
and in the doc the button  btn-outline-light is unreadable (too clear) perhaps a more heavy gray in the variable will be ok ?

**Comment by XhmikosR** [comment]
The color is fine; it's just the background is white thus the contrast ratio is low.

@mdo @andresgalante: maybe we should use a darker background across the docs for all light variants?

**Comment by andresgalante** [comment]
@XhmikosR That's a good idea, but it'd mean having different example boxes for the examples. In the case of btns it's nice to have the group together.
