### ISSUE TITLE
Responsive table doesn't work within a table

### ISSUE THREAD

**Issue by arogachev** [twbs/bootstrap#24458]
Responsive table doesn't work as expected when placed inside a `div` with CSS property `display` set to `table`, `table-row` or `table-cell`. Horizontal scrollbar appears at the bottom of the page, not at the table itself. This causes layout to break. Removing these styles is not acceptable solution for me because they are used on the root containers in the project's base layout.

Tested on both latest Bootstrap 3 and 4:

[JSFiddle - Bootstrap 3 responsive table within a table](https://jsfiddle.net/arogachev/gp414Lnp/)
[JSFiddle - Bootstrap 4 responsive table within a table](https://jsfiddle.net/arogachev/736s3kxa/)

Related StackOverflow questions:

- https://stackoverflow.com/questions/26394072/bootstrap-3-table-table-responsive-not-working
- https://stackoverflow.com/questions/19640190/bootstrap-3-table-responsive-inside-displaytable-cell-doesnt-work
- https://stackoverflow.com/questions/42729619/css-table-responsive-inside-displaytable-displaytable-row-cell
- https://stackoverflow.com/questions/31692323/boostrap-responsive-table-is-not-responsive-inside-a-table

I created the workaround based on setting fixed `max-width` (as suggested in this [StackOverflow answer](https://stackoverflow.com/a/32013813/4323648)) and updating it with JS on page load and window resize. It's not perfect, but works. Looking for a better pure CSS solution.

**Comment by Johann-S** [comment]
Please can you check your issue with our latest release : https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css

**Comment by arogachev** [comment]
@Johann-S Thanks for the fast reply. I updated JSFiddle for Bootstrap 4 to use CSS from the latest release you mentioned. The problem still exists.

**Comment by XhmikosR** [comment]
/CC @mdo @andresgalante: judging by the issues we get with responsive tables, we need to come up with something better.

**Comment by mdo** [comment]
This should've been resolved with the change in Beta 3 to responsive tables—we're back to a parent class. See #25058.
