### ISSUE TITLE
Dismissible alert - long text overlaps close button

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#24469]
Not sure i understand why close button now has absolute positioning in Beta2, but now if text in alert is too long, it overlaps close button. I think we need to add extra right padding to dismissible alert to ensure text and button are always visible.

![Image](https://i.gyazo.com/9a259ae5ff34db88750b6d042b20292e.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Kopyov** [comment]
Here is a fiddle - https://jsfiddle.net/ggefb28f/2/

**Comment by Johann-S** [comment]
they are no issue in your JSFiddle :astonished:

**Comment by Kopyov** [comment]
Try to resize browser window ;-) I clearly see that text doesn't wrap when reaching the close button

**Comment by jipexu** [comment]
> Try to resize browser window ;-) I clearly see that text doesn't wrap when reaching the close button
yes true .. it's wrap but too late ....
i noticed the same behavior

**Comment by XhmikosR** [comment]
/CC @andresgalante: maybe https://github.com/twbs/bootstrap/commit/f02f545e0eb4cc8fca282465ccdf54f29d0a1acc#diff-98a05acc8656119323ad1630818d4719?

**Comment by MattJLeach** [comment]
Would love to contribute to bootstrap and have submitted a PR to resolve this. https://github.com/twbs/bootstrap/pull/24478

**Comment by andresgalante** [comment]
Yeah, we knew of this when we merged it: https://github.com/twbs/bootstrap/pull/23673

@MattJLeach I'll check your PR, thanks!

**Comment by andresgalante** [comment]
@mdo I am trying to think of a solution but I don't see how we can do it without introducing a new class on the parent selector. What do you think? should we go back to how it was before?

**Comment by Kopyov** [comment]
Quick workaround:
```
.alert-dismissible {
    padding-right: ($close-font-size / 2) + ($alert-padding-x * 2);
}
```
Not sure though if ($close-font-size / 2) is a good solution.

**Comment by andresgalante** [comment]
@Kopyov you are right! we have a parent selector! That was the exact fix I had in my head. It does create a larger padding to the right, but I'd be ok with it, Do you want to PR it?

**Comment by andresgalante** [comment]
@Kopyov 
![alert](http://g.recordit.co/tA6FnQEToA.gif)

```scss
.alert-dismissible {
  padding-right: ($close-font-size + $alert-padding-x);
}
```

**Comment by Kopyov** [comment]
@andresgalante added your version, since it saves some space :blush:
