### ISSUE TITLE
Bad rendering of server-side only validation on inputs

### ISSUE THREAD

**Issue by SPodjasek** [twbs/bootstrap#24468]
When (as in my case) you only use server side or code validation on your inputs, you'll get this kind of output:
![image](https://user-images.githubusercontent.com/3293161/31820475-ca3f63ca-b5a1-11e7-908b-7d3f1a6c4b52.png)

Pen with this issue is here: https://codepen.io/anon/pen/yzwoyy?editors=1000

This issue is related to this line & mixin seen here:
https://github.com/twbs/bootstrap/blob/9a1d81f154f4391f9fea47fc26cd2fa864d6ae8a/scss/_forms.scss#L260

IMHO simplest fix is to add `!important` to invalid state border color - at least it worked for me.

**Comment by Johann-S** [comment]
Please can you use our latest release ?

**Comment by SPodjasek** [comment]
I've checked it with latest git clone

**Comment by Johann-S** [comment]
CodePen with our latest release (beta 2) : https://codepen.io/Johann-S/pen/LzajBr

**Comment by SPodjasek** [comment]
With this it works: https://github.com/inway/bootstrap/commit/78adfc81ca0476cc9bb41432ee4ea2cecc5e88b4

**Comment by mdo** [comment]
You're mixing server-side and client-side from our docs. Remove the `.was-validated` from the first column and you'll have the intended styles; these aren't dependent on the parent `.was-validated` class. You're seeing it this way because your input is implicitly looking for client-side validation.

**Comment by SPodjasek** [comment]
@mdo That's the case for us, we do have server-, client- and browser-side validation, so `.was-validated` is always there. We'll try to change templates and drop this in some cases so it would work with stock bootstrap styles.

**Comment by SPodjasek** [comment]
We've decided to drop `.was-validated` on parent element
