### ISSUE TITLE
table-responsive are wider than content

### ISSUE THREAD

**Issue by cinqlair** [twbs/bootstrap#24464]
With table-responsive, according to the size of the view port, table may have strange behaviors. Table may become larger than its content : [jsfiddle](http://jsfiddle.net/nzsaf12z/9/)

**Comment by Johann-S** [comment]
Please update your JSFiddle with our latest release

**Comment by dushkostanoeski** [comment]
I'm guessing related to #24256  and #24462

**Comment by cinqlair** [comment]
Here is the updated JSFiddle with the last release (4.0.0-beta.2) : [Updated JSFiddle](http://jsfiddle.net/nzsaf12z/10/)

**Comment by mdo** [comment]
Closing as duplicate of #24256.
