### ISSUE TITLE
Look if we need to disable autoprefixer in some parts

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24460]
Maybe in reboot for example.

https://github.com/postcss/autoprefixer#disabling

/CC @mdo

**Comment by MartijnCuppens** [comment]
I've checked the prefixed and unprefixed version of `dist/css/bootstrap-reboot.css` and the only line which is added is L64:
https://github.com/twbs/bootstrap/blob/73a98d97380e52d4cf2ec5aa8071b93e97e390ae/dist/css/bootstrap-reboot.css#L64
So I don't think this is relevant.
