### ISSUE TITLE
Position classes not working

### ISSUE THREAD

**Issue by carlosnpz** [twbs/bootstrap#24476]
None of the position classes are working (E.g. position-absolute, position-fixed)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by carlosnpz** [comment]
Sorry, found out that my Bootstrap version wasn't updated. Just got the latest and now it's working like a charm!
