### ISSUE TITLE
$gray Variable is not defined in _variables.scss File

### ISSUE THREAD

**Issue by pmkumaar** [twbs/bootstrap#24472]
I am new to Bootstrap and SASS.
I'm using bootstrap 4.0 beta version.
OS: Windows 10 Professional.

I am unable to find the definition of "$gray" color variable.
I searched for "$gray:" variable to find the color hex code.
It is not defined in "_variables.scss" file or elsewhere in bootstrap npm folder

$gray is being used in a lot of places in "_variables.scss" but it itself is not defined any where?

I believe, this needs to be fixed.

**Comment by jipexu** [comment]
yes ....
use $gray_600 instead
in _variables.scss there is no more $gray

**Comment by andresgalante** [comment]
Hi @pmkumaar, gray variables are here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L13-L21

@jipexu is right, you can probably use `-600` as a mid saturation gray
