### ISSUE TITLE
[V4 Beta 2] modal-content is now mandatory

### ISSUE THREAD

**Issue by s3rg3** [twbs/bootstrap#24477]
Hello,

As stated in the title for modals to work correctly it is now mandatory to have the modal-content class.

Otherwise nothing work correctly and clicking on it close it.

It should be add in the doc.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bkdotcom** [comment]
Does the documentation omit `.modal-content`  anywhere ?
Why would you assume any part of the specified markup is optional?

**Comment by s3rg3** [comment]
Here is a [CodePen](https://codepen.io/anon/pen/EwMOQa) with bootstrap 4.0.0-beta.2, change the bootstrap version to 4.0.0-beta and when you click on the one without the modal-content class it will not close.

@bkdotcom 
i don't think the documentation omit it.
And i did not assume it was optional, previously it worked without and you could put every thing you liked in it.
I have worked it around by setting another class with a transparent background in the same div as the modal-content class.
I was just saying it should be add to the doc because other people like me might like to put custom content in the modal  and if they were doing it previously might like to understand why it does not work anymore.

**Comment by mdo** [comment]
It's implied that the markup in the examples is required—going to leave as-is and close as a won't fix.

**Comment by jereckley** [comment]
I thought the point of versioning was you could still use that version... another example is input-group-prepend, input-group-append on input groups is replacing input-group-addon... but wait you also need to put a span with class="input-group-text" inside of that. What? A change to an established version? Your changes are totally breaking me man and kinda freaking me out like maybe I shouldn't have gone with bootstrap 4... **are these required changes being documented anywhere?** please... please restore 4.0.0-beta to 4.0.0-beta and stop changing older versions? I don't understand is there some principle I'm missing?
