### ISSUE TITLE
Theme colors

### ISSUE THREAD

**Issue by iantbarker** [twbs/bootstrap#24474]
I see old issues about theme colors but the answers seem to be that it is resolved in beta 2. I upgraded to beta 2 and I cannot get theme colors to work. My file structure is to import individual BS files into main.scss. I have:

`@import "bootstrap/functions";
@import "bootstrap/variables";
@import "_variables_custom.scss";`

In my "_variables_custom.scss" file I have:

`$brand-primary: 	#e95362;
$theme-colors: (
	"primary":    $brand-primary
);`

This code changes the primary color but wipes out all other colors in the theme-colors map. I have to redeclare all the color variables and the colors in the colors map to make it work.

Am I missing something?

**Comment by jipexu** [comment]
Hi
i use like this way and work perfectly 

// core bootstrap functions
@import "../scss/functions";
@import "../scss/mixins";

// variable overrides
@import "variables"; <== your variables (in wich you need the new grayscale and colors function...)

// full bootstrap
@import "../scss/bootstrap";

// style overrides if need
@import "xxxxx";

**Comment by andresgalante** [comment]
Hi @iantbarker, as @iantbarker mentions import your variables **before** Bootstrap's it's documented here:
http://getbootstrap.com/docs/4.0/getting-started/theming/#variable-defaults

**Comment by iantbarker** [comment]
Ah, my bad. Apologies.
