### ISSUE TITLE
title's indexed as sections on cards.md

### ISSUE THREAD

**Issue by gijsbotje** [twbs/bootstrap#24489]
on the cards page there are some headings from examples that are indexed for the nav
http://getbootstrap.com/docs/4.0/components/card/#text-alignment
I encountered this on v4-dev but it happens on the live docs aswel

screenshot,
<img width="184" alt="schermafbeelding 2017-10-21 om 11 56 47" src="https://user-images.githubusercontent.com/7714133/31850705-54798b96-b657-11e7-8cfc-7326e941b443.png">

**Comment by XhmikosR** [comment]
Yeah it's an issue with our TOC plugin.

**Comment by XhmikosR** [comment]
I have a PR, see #24466, but that still has the same issue.

I have opened https://github.com/allejo/jekyll-toc/issues/3 and https://github.com/toshimaru/jekyll-toc/issues/37.

At this point, both solutions aren't perfect, so I don't know with which I'll go in the end.

**Comment by XhmikosR** [comment]
I'll work around it but I really want this to be properly solved.

```css
ul ul .toc-entry.toc-h4 {
    display: none;
}
```

**Comment by gijsbotje** [comment]
aah oke, yeah that's not really pretty...
