### ISSUE TITLE
feature: Mega Menu

### ISSUE THREAD

**Issue by wilson-young** [twbs/bootstrap#24480]
Will future bootstrap 4 version got Megamenu Navigation included?

**Comment by mdo** [comment]
Not likely, but perhaps an example to show it? I'd love to see a PR for that until I find time to do it myself. No plans for a new feature though.

**Comment by wilson-young** [comment]
@mdo, something like this: https://codepen.io/subodhghulaxe/pen/zxwKBo
* i found it on google. just for example.
