### ISSUE TITLE
Datetimepicker month/year selection ignores sidebyside=false

### ISSUE THREAD

**Issue by Ekjon** [twbs/bootstrap#24485]
I am using Bootstrap version 3.3.6. I have this datetimepicker configured as:     

`$(".dateTimePickerElement").datetimepicker({        toolbarPlacement: "top",        showTodayButton: true,        sideBySide: false,        showClear: true,        showClose: true,        useCurrent: true,        keepOpen: true,        locale: "en",        format: "YYYY-MM-DD h:mm A",        debug: true    }); `

When the year month is clicked to make a selection of months or years, it ignores sideBySide: false and shows up wide on the screen on other elements.
![image](https://user-images.githubusercontent.com/32969814/31843609-4b455ba0-b5b1-11e7-8763-529d2233caf2.png)

Help will be appreciated from Bootstrap team or anyone else.
Thanks.

**Comment by gijsbotje** [comment]
as this is not a default bootstrap feature you might be better of asking this at the github page of the package you are using

**Comment by patrickhlauke** [comment]
yup

**Comment by Ekjon** [comment]
Is there a way this can be moved over to that page or I need to delete this and create a new one over there?

**Comment by jgacuca567** [comment]
@Ekjon create a new one over there.
