### ISSUE TITLE
Background Gradients not rendering in docs

### ISSUE THREAD

**Issue by swrobel** [twbs/bootstrap#24484]
My guess is that `$enable-gradients: true` isn't set for the [docs](https://getbootstrap.com/docs/4.0/utilities/colors/#background-gradient)

**Comment by gijsbotje** [comment]
you are correct, but it is intentional :)
read the paragraph about it http://getbootstrap.com/docs/4.0/utilities/colors/#background-gradient

**Comment by swrobel** [comment]
lol, guess I need to rtfm! 😳
