### ISSUE TITLE
ServiceWorker registration failed

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#24490]
When running **`npm run docs`**, the following happens:

1. **`bundle exec jekyll build`**: generates the documentation files.
2. **`node build/workbox.js`**: which, in turn, performs the following:
2.1 Obtains the location of the **`workbox-sw`** module currently installed in `node_modules`.
2.2 Copy the main file obtained in 2.1 to `gh_pages/assets/js/vendor`. With the current version of `workbox-sw`, the path to the copied file would look like this: `gh_pages/assets/js/vendor/workbox-sw.prod.v2.1.0.js`.
2.3 Read the file `sw.js` in the repository root, replace the `{fileName}` pattern with the file name copied in 2.2 (`workbox-sw.prod.v2.1.0.js`) and save it in the `gh_pages` root.

Then, when running the documentation server, the `index.html` page includes `<script src="/assets/js/src/pwa.js">`. And this script invokes, in turn, the file `sw.js` created in point 2.3.

So far everything would be OK, but there is a problem when running the test server using **`npm run docs-serve'**. As Jekyll's documentation mentions (see https://jekyllrb.com/docs/usage/): **Destination folders are cleaned on site builds**. Then, when executing "npm run docs-serve", when the documentation files are rebuilt, all the work done in point 2 is lost. And, for this reason, the service worker stops working, throwing errors in console.

Error in Windows shell:
![error-sw-shell](https://user-images.githubusercontent.com/29401668/31850671-96e48d9e-b62c-11e7-9f70-bbb95372d402.jpg)

Error in Firefox console:
![error-sw-console](https://user-images.githubusercontent.com/29401668/31850670-96b7bb98-b62c-11e7-9e29-431ff8956f66.jpg)

I am now working on proposing a solution for this. I have to find a way for **`docs-serve`** script not to overwrite or delete files generated during **`docs-compile`** and **`postdocs-compile`** scripts.

**Comment by XhmikosR** [comment]
This is known and there is no way to work around it so just ignore it. It's just a local issue.

If you can come up with a better organization of the scripts, make a PR and CC me.

**Comment by lucascono** [comment]
Hello @XhmikosR. I have already solved it, shortly I send the PR. I wanted to open this issue for reference later in the PR.

**Comment by XhmikosR** [comment]
Personally I don't use the `docs-serve` script at all. I just do `bundle exec jekyll s`.

Either way, if we find a good way to generate the precache files, that would be nice. If not, we can live with it, like we did until now :P

My problem was when I was testing things locally; in that case I just fired up a Python server `python -mSimpleHTTPServer 4000`.
