### ISSUE TITLE
Vertical button style radios/checkboxes bottom label margin not removed

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#24496]
- Bootstrap V4.0.0.-beta.2
- Operating system and version (any)
- Browser and version All
- Reduced test case https://codepen.io/tmorehouse/pen/BwEpOr

When using button style radios or checkboxes in vertical mode, the label margin-bottom is not set to 0 causing spacing issues between the "buttons":

![image](https://user-images.githubusercontent.com/2781561/31856557-70a4a8bc-b69a-11e7-88f0-6541980e6ef7.png)

**Expected behavior:**
That the bottom margin be set to 0 for the labels, as would be for regular buttons in a vertical button group.

**Workaround:**
```css
.btn-group-vertical label.btn {
  margin-bottom: 0;
}
```
or manually setting class `mb-0` on each `label.btn`

**Comment by gijsbotje** [comment]
working on a fix :)
