### ISSUE TITLE
Bootstrap 4 Beta v2 JS not working with WordPress jQuery

### ISSUE THREAD

**Issue by danimalweb** [twbs/bootstrap#24500]
Similar to #24417 which is closed.

When including the latest Beta v2 JS in a WordPress environment the following error is in the console: ```TypeError: Cannot read property 'fn' of undefined``` on Chrome. Safari and Firefox also fail to load, but a slightly different error.

JS Bin: https://jsbin.com/sowahazege/1/edit?html,js,console,output

I have included jQuery from a current live WP install on my server.

Swapping out the Beta V2 JS for the Beta V1 JS corrects the issue. As does loading jQuery from a CDN instead of the bundled WP version.

Has something changed between Beta v1 and v2 on how the jQuery object is accessed?

**Comment by XhmikosR** [comment]
@Johann-S: I think it's the `$` change. We need to revert to `jQuery` which is always defined I believe.

**Comment by metalandcoffee** [comment]
I've been banging my head, trying to figure out what I'm doing wrong, so I'm glad someone else is experiencing this issue.

**Comment by Johann-S** [comment]
A quick fix for those who have this issue, in a script tag under jQuery script tag add : `var $ = window.jQuery`

**Comment by nextgenthemes** [comment]
[Not fixed!](https://github.com/twbs/bootstrap/issues/24417#issuecomment-338807660) But you trigger happy close all this issues.

**Comment by drducmanh** [comment]
I fixed it with a litle code in **functions.php**:

> wp_deregister_script('jquery' ); // 
> wp_register_script('jquery', 'http://code.jquery.com/jquery-latest.min.js',null,false,true);
> wp_enqueue_script('jquery');
