### ISSUE TITLE
Add text utility for monospace font

### ISSUE THREAD

**Issue by saviomd** [twbs/bootstrap#24502]
We have utilities for weight, italic, smaller/bigger size, why not have one for monospace?
It would be useful for tables with columns showing numbers, to easily see which number is greater.
i.e. 99999 (5 numbers) gives the false impression of being greater than 111111 (6 numbers) because it has a bigger width when using the default font and size

**Comment by RaceProUK** [comment]
While I can see potential use cases, isn't this already covered by the HTML `<pre>` and `<code>` elements?

**Comment by saviomd** [comment]
@RaceProUK No... numbers in a table (my example) aren't a preformatted text (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) or a fragment of computer code (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code)
Always have semantics on your mind! (https://www.wikiwand.com/en/Semantic_HTML)

**Comment by RaceProUK** [comment]
Good point: `<tt>` would have been a better choice... if it wasn't deprecated 😊

**Comment by saviomd** [comment]
true :)

**Comment by patrickhlauke** [comment]
i'll admit i'm not a massive fan of the huge number of utility classes we have already (as we'll soon reach a point where we reflect every possible CSS property as a class), so not too hot personally on adding more like these. at some point authors should be able/expected to just add their own things into an additional stylesheet...
