### ISSUE TITLE
Any chance of bringing the web based customizer back?

### ISSUE THREAD

**Issue by jeffreymeng** [twbs/bootstrap#24508]
The old web-based customizer(https://getbootstrap.com/docs/3.3/customize/) was very useful. I understand that you guys got rid of it in favor of customizing your own sass, but this was very useful for me(and I bet many other people too). I don't really use sass(or know how to compile it), and I know it's a lot of work to create and mantain bootstrap 4, but maybe when the heat cools down you could consider adding it back?

**Benefits:**

- You don't have to know sass
- It's quick(the customizer took me less than five minutes to use)

**Disadvantages**
- Enlighten Me

**Comment by vms82** [comment]
Something similar to https://www.bootstrap-live-customizer.com/ would be even more awesome, the guy that made it is working on v4 too but not sure about his progress.

**Comment by thinkcreatedo** [comment]
I really appreciated the ability to select only certain functionalities for the downloads of the previous version. I work on a lot of older client websites who only want a small feature added, so I can't/don't want to use the whole bootstrap theme and frameworks if I _just_ wanted the modal feature.

**Comment by mdo** [comment]
No chance of an official one at this point.
