### ISSUE TITLE
col-

### ISSUE THREAD

**Issue by pgklada** [twbs/bootstrap#24509]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by pgklada** [comment]
On the page https://getbootstrap.com/docs/4.0/layout/grid/ there is an item labeled "Class prefix" that has a value ".col-" in the column "Extra small" and I believe it should be ".col-xs-". Please fix.

**Comment by RobertSmits** [comment]
It was so in bootstrap 3,  however because xs is the default (works for all screen sizes) the ``-xs`` got removed in bootstrap 4

**Comment by mdo** [comment]
The docs are correct.

**Comment by pgklada** [comment]
thanx :-)
