### ISSUE TITLE
Horizontal rule hard-coded margin introduced in Beta

### ISSUE THREAD

**Issue by ernestbofill** [twbs/bootstrap#24517]
Since the beta version of Bootstrap, the margin of the horizontal rule defined in _type.scss is a hard-coded making it difficult to customize.

In latest alpha:
```
// type.scss line 53:
hr {
  margin-top: $spacer-y;
  margin-bottom: $spacer-y;
  //...
}
```

In beta:
```
// type.scss line 53:
hr {
  margin-top: 1rem;
  margin-bottom: 1rem;
  //...
}
```

I would like this margin to use a variable so that it can be customized.

**Comment by andresgalante** [comment]
Hi @ernestbofill it was updated here: https://github.com/twbs/bootstrap/commit/ed1de86794cc0911dc7a3dbbf3bb9dfe421ef4b6

I'll create a PR to add `hr` variables.
