### ISSUE TITLE
safari  dont know some css ? [V4B2]

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#24516]
Hi
on the safari console i got some alert from the reboot_scss

-webkit-text-size-adjust: 100%; (100% is not handle for this property)
-webkit-tap-highlight-color: transparent (he dont know)

we can ignore it or it's have some bad effect ?

Thanks for advice

**Comment by XhmikosR** [comment]
The browser ignores the properties it doesn't support; nothing to worry about.

**Comment by jipexu** [comment]
thanks
