### ISSUE TITLE
Series of buttons in input group 

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#24528]
There are both code for `.input-group-btn > .btn + .btn` and `input-group-btn > btn-group` in **input-group.scss**. Bootstrap supports the both markup?

```html
<div class="input-group">
  <input type="text" class="form-control">
  <span class="input-group-btn">
    <button class="btn btn-primary" type="button">Button</button>
    <button class="btn btn-primary" type="button">Button</button>
  </span>
</div>
```

```html
<div class="input-group">
  <input type="text" class="form-control">
  <span class="input-group-btn">
    <div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-primary">Button</button>
      <button type="button" class="btn btn-primary">Button</button>
    </div>
  </span>
</div>
```

If not support either one, scss code will be more simple. And also it would be helpful if the document mention about a `btn-group` in the input group .

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by ysds** [comment]
Demo: https://jsbin.com/sivavuyuxa/1/edit?html,css,output
Both markup are the same results. I do not think this is a bug.

**Comment by mdo** [comment]
Both are in the docs and the source code, so yes.

**Comment by ysds** [comment]
I updated the demo to `btn-outline-xxx` from `btn-xxx`
https://jsbin.com/giyuwobuxi/edit?html,css,output

Screenshot:
![image](https://user-images.githubusercontent.com/4065765/32255581-53a88788-beec-11e7-9cb6-51716bbeac54.png)

The right side buttons border are different according to the markup.
