### ISSUE TITLE
[Feature] Add a less variable in order to scale the bootstrap

### ISSUE THREAD

**Issue by sarbull** [twbs/bootstrap#24526]
I would want to add a `@scale` less variable who will have an initial value of `1` and if it is being lowered or highered it should scale the whole application values.

This feature can be similar to `CTRL++` or `CTRL--` in the browser but being done programatically.

Any thoughts on this?

**Comment by mdo** [comment]
We don't use Less in v4 anymore, and we're not actively working on v3 at the moment. v4 does this automatically with `rem` units.

**Comment by sarbull** [comment]
Hi,

Thank you for the response, where is this ‘rem’ documented?

Cezar

**Comment by tomlutzenberger** [comment]
@sarbull Have a look at https://www.sitepoint.com/understanding-and-using-rem-units-in-css/
