### ISSUE TITLE
jQuery 1 noconflict still not working.

### ISSUE THREAD

**Issue by nextgenthemes** [twbs/bootstrap#24527]
Following up on #24417. I saw #24513 And it looks like this is exactly what was needed.

However since the dist/ files are not updated to include that fix yet. I compiled myself and pasted the minified version into [my testing bin](https://jsbin.com/wizoxehihu/1/edit?html,js,output) for this. I get the same error I got b4 with the minified version.

That is `TypeError: e is undefined` in Firefox.

**Comment by Johann-S** [comment]
You're right that's a compatibility issue see my Codepen(s) : 

Using your jQuery 1.12.4 : https://codepen.io/Johann-S/pen/PJvLMK
Using jQuery 3 : https://codepen.io/Johann-S/pen/MEdxZP

**Comment by Johann-S** [comment]
I was wrong in my last comments, they are something which break or JS in Wordpress 

Using jQuery 1 from jQuery CDN : https://codepen.io/Johann-S/pen/PJvLMK (working)
Using jQuery 1 from your jQuery link : https://codepen.io/Johann-S/pen/rGgbOE (not working)
