### ISSUE TITLE
RFE: Vertical Slide out lateral nav at tablet and below for bootstrap 4

### ISSUE THREAD

**Issue by WebDragon** [twbs/bootstrap#24524]
asked [this question](https://stackoverflow.com/questions/46697469/vertical-slide-out-lateral-nav-at-tablet-and-below-for-bootstrap-4) on StackOverflow almost two weeks ago, but have not had any response -- thought I might toss it out over here as well to get some of you who are working on these features thinking about the concept and maybe having a solution by the next beta release.

**Comment by mdo** [comment]
There are issues and PRs aimed at this—horizontal collapse, custom modal, navbar variant. Closing as a duplicate issue. Take a quick search and you'll find something with a recommendation before we try to get to something like this in v4.1 or later.

**Comment by WebDragon** [comment]
ahh finally found mention if it in #9481  guess it was the 'drawer variation' wording that threw me off the trail vs how I was thinking of it as a "lateral collapse", when I was skimming around. Sometimes having too much vocabulary at ones disposal can be a bit of an unexpected burden. :)

**Comment by WebDragon** [comment]
regrettably many of the examples people have provided in the referenced PRs and Issues have gone away and are no longer available to look at :( Be nice if more people used gists for code examples
