### ISSUE TITLE
Beta 2 Nuget Package Needed - Still loads Beta 1

### ISSUE THREAD

**Issue by Grandizer** [twbs/bootstrap#24525]
I have a Visual Studio 2017 DotNetCore project where I have had BS 4 Beta in there.  I love it, looks great.  I see that BS 4 Beta 2 is available so I checked the box for Prerelease software and it is not in the updates.  I have even tried your:

Install-Package bootstrap -Pre

Which just wants to install what is already there.
Can you please update your nugget package.

I could add files manually, but then that seems to take away from the point of a package.

**Comment by XhmikosR** [comment]
@mdo: who's in charge of that? Can you ping them?

**Comment by mdo** [comment]
@supergibbs I think maybe?

**Comment by supergibbs** [comment]
Sorry, I’ll definitely update it but I am traveling abroad without a computer until November 6th so it’ll be a little delayed.

**Comment by Grandizer** [comment]
Ouch. Ok. Enjoy and good luck!

Sent from my Windows 10 phone

________________________________

**Comment by supergibbs** [comment]
@Grandizer, you should look into using npm. The NuGet package is more for older projects before npm support was added.

**Comment by Grandizer** [comment]
Will do.

[http://www.mygotoguy.net/Images/ACSPOHRBikeLTR.png]<http://main.acsevents.org/goto/kg18>       Kevin Grigsby

Proud supporter of more Birthdays!
Please click here<http://main.acsevents.org/goto/kg18> to visit my Pan Ohio Hope Ride page to donate, volunteer or join me for the ride.
________________________________

**Comment by nixxholas** [comment]
bower bootstrap#v4.0.0-beta.2       EMALFORMED Failed to read C:\Users\CoinHako\AppData\Local\Temp\DESKTOP-06IVB8M-CoinHako\bower\ca4c50b905dc21ea17a10549a6f5944f-11332-eGQwos\bower.json
Additional error details:
Unexpected token @

**Comment by vanillajonathan** [comment]
@nixxholas Bower support has been dropped in beta 2.

**Comment by 0xF6** [comment]
@vanillajonathan 
Why drop support? Bower prevents than what?

**Comment by vanillajonathan** [comment]
@0xF6 If you look at the bower website it says: "...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!".

So Bootstrap dropped support for Bower since it is considered a deprecated platform.

**Comment by 0xF6** [comment]
@vanillajonathan 
Microsoft doesn't think so. 
ASP.Core uses Bower. Because npm doesn't know how of certain things.

**Comment by supergibbs** [comment]
I quickly found this post showing how to replace bower with webpack and just use npm. There are prob others too. (See part 2 also) http://leruplund.dk/2017/04/15/setting-up-asp-net-core-in-visual-studio-2017-with-npm-webpack-and-typescript-part-i/

**Comment by vanillajonathan** [comment]
@0xF6 Well besides npm there is also yarn.
I hope Visual Studio and ASP.NET Core soon gets better support for yarn and/or npm.

I understand why they removed Bower support, but would have appreciated until they still had beta 2 and the upcoming beta 3 on bower and hopefully Microsoft had got npm/yarn support ready by then.

**Comment by 0xF6** [comment]
@vanillajonathan  
NPM has, but for some reason I cannot install the custom folder install packages via .npmrc.
In Bower this is configured through .bowerrc
```
{
  "directory": "wwwroot/lib"
}
```
At least I can not :(

**Comment by masterjs** [comment]
@0xF6 If you want to see how to to use NPM in ASPNET Core 2 projects, in VS 2017, just create a project with the Angular template. It will show you how to get ready with NPM & Webpack. They are also aware of the Bower deprecation, but they had to priorize. So slowly all their web templates will be updated.

**Comment by supergibbs** [comment]
Sorry for the delay, the NuGet packages have been updated:

https://www.nuget.org/packages/bootstrap/4.0.0-beta2
https://www.nuget.org/packages/bootstrap.sass/4.0.0-beta2

**Comment by Grandizer** [comment]
Thanks for the update.  Based on your suggestion I moved to NPM already.

[http://www.mygotoguy.net/Images/ACSPOHRBikeLTR.png]<http://main.acsevents.org/goto/kg18>       Kevin Grigsby

Proud supporter of more Birthdays!
Please click here<http://main.acsevents.org/goto/kg18> to visit my Pan Ohio Hope Ride page to donate, volunteer or join me for the ride.
________________________________
