### ISSUE TITLE
Tootlip does not display intermittently when moving up a list of elements

### ISSUE THREAD

**Issue by ericcarino** [twbs/bootstrap#24539]
OSX 10.13
Chrome 61.0.3163.100
Bootstrap 3.3.7

I basically copy/pasted the tooltip sample code from the bootstrap website.

`<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button><br>
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button><br>
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button><br>
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button><br>  
`

When I move up this list of buttons with my mouse, I intermittently get the tooltip to display.  Going down the list works perfectly, it only happens moving up.  I notice the faster I move from one button to the next, the issue is more likely to happen.

[jsbin example](http://jsbin.com/yadixec/1/edit?html,js,output)

![bootstrap-tooltip-issue](https://user-images.githubusercontent.com/7257924/31966734-7e32faf6-b8c0-11e7-97bd-9a70a7cc8a78.gif)

**Comment by gijsbotje** [comment]
IMO this is an example of how not to implement the tooltips, covering up other buttons
i would advice popping them to the right
it is fixed though by adding `pointer-events: none;` to the tooltip css
Leaving it up to the team how to proceed

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by ericcarino** [comment]
@Johann-S 

Thanks.  I have confirmed the issue does not exist in Bootstrap 4.
