### ISSUE TITLE
Progress bar doesn't handle 0% case

### ISSUE THREAD

**Issue by jacroe** [twbs/bootstrap#24538]
This is a duplicate of #12848 but for v4. It looks like it was reintroduced.

What happens is that when it's 0%, the text is pushed off-screen and is back to sitting on the edge. Compare the same HTML with v3.3.7 (https://jsfiddle.net/pz0dj4eo/) with v4.0.0-beta.2 (https://jsfiddle.net/dy5mecan/).

This is happening on Windows with Chrome 61, Firefox 55, and Edge 38.

**Comment by gijsbotje** [comment]
this is caused by replacing `text-align: center;` by `justify-content: center;`
a fix is switching these back again
i'll make a pr for it
