### ISSUE TITLE
Bootstrap 4 beta 2 dropdowns don't work with full jQuery only slim

### ISSUE THREAD

**Issue by smartbloke** [twbs/bootstrap#24537]
Dropdown components do not drop down when using jQuery 3.2.1 instead of 3.2.1.slim alongside bs4 beta 2.

**Comment by XhmikosR** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bkdotcom** [comment]
Here's a "it works fine" live demo
https://codepen.io/bkdotcom/pen/VMJQdG

**Comment by Johann-S** [comment]
What jQuery said about that slim version :
>Sometimes you don’t need ajax, or you prefer to use one of the many standalone libraries that focus on ajax requests. And often it is simpler to use a combination of CSS and class manipulation for all your web animations. Along with the regular version of jQuery that includes the ajax and effects modules, we’ve released a “slim” version that excludes these modules.

**Comment by pypetey** [comment]
It does not seem to work with my configuration also.

I've upgraded from bootstrap 4 alpha6 to  bootstrap 4 beta 2 and dropdowns stopped working.

I use Webpack + jQuery 3.2.1 (tested both with slim and non-slim) + newest popper.js.

Dropdowns did not work at all and no console errors were showing up.

**Comment by smartbloke** [comment]
Apologies. I was caught out by the integrity attribute on the script tag for jQuery. I copy pasted the standard bs4 beta 2 template, then edited the src attribute to use the non-slim version without changing / removing the integrity attribute. The dropdown I was testing in sandbox page then failed. Sorry for wasting your time.

**Comment by Johann-S** [comment]
Thanks @smartbloke to confirm that to us :+1:
