### ISSUE TITLE
missing styles for form-control-lg errors (and for -sm appendix too)

### ISSUE THREAD

**Issue by OdifYltsaeb** [twbs/bootstrap#24546]
Try this:
- Go to https://getbootstrap.com/docs/4.0/components/forms/ and find an input with .form-control class that also has .is-invalid class. 
- change form-control class for form-control-lg class. You'll see that error message disappears and also error styles disappear.

so yeah - styles for these class combinations are missing. Found within beta2.1

**Comment by andresgalante** [comment]
Hi @OdifYltsaeb this is what I see:

![screen shot 2017-10-25 at 9 37 04 am](https://user-images.githubusercontent.com/1832037/31999022-37ed65a6-b968-11e7-98b2-aad3565f7444.png)

Can you provide a codepen that spots the problem please?

**Comment by mdo** [comment]
Do not change the `.from-control` for `.form-control-lg`—the latter is a modifier class. You need both classes.
