### ISSUE TITLE
Grid system is not working under `table-layout: fixed`

### ISSUE THREAD

**Issue by kuofp** [twbs/bootstrap#24548]
In former version(v3.3.7), we build a table as following.

```html
<table class="table table-bordered">
  <tr>
    <td class="col-md-5">5</td>
    <td class="col-md-5">5</td>
    <td class="col-md-9">9</td>
  </tr>
</table>
```

After adding "table-layout: fixed" on table tag, everything works fine even if sum of those columns is greater than 12.

```css
table{
   table-layout: fixed;
}
```
result:
https://codepen.io/anon/pen/eGwXBy

However in v4, columns are all separated in the same width.
https://codepen.io/anon/pen/NaZVoq

I wonder if there is any alternate in this situation.
Thanks in advance

**Comment by Johann-S** [comment]
Please can you update your CodePen to our last release (beta 2) ?

**Comment by kuofp** [comment]
Sure. Now it's using beta 2.

**Comment by mdo** [comment]
The column classes cannot be mixed with tables anymore—it's a side effect of our move to flexbox. No way to mix and match those two.
