### ISSUE TITLE
card-header-tabs incorrectly positioned with a float button

### ISSUE THREAD

**Issue by fredgate** [twbs/bootstrap#24559]
Conditions :
- Version: bootstrap 4 beta 2
- Operating system and version: Windows10
- Browsers: Firefox 56.0.1, Edge 38.14393.1066.0
- Test case: https://jsfiddle.net/Ld3uwxse/

When a header card contains tabs and a (right) float button, then the tabs are not positioned to the bottom of the header, so the border of card body is visible.

The problem was mentionned in the issue #19822 for a button, but I am using a small button (`btn-sm`).
In a prior version of bootstrap, it worked fine as this fiddle poves it : https://jsfiddle.net/0xdwv2wk/

It seems caused by new style of btn-sm that sets `line-height` to 1.5. So the button height is now 31 px, while it was previously 27.5 pixels.

**Comment by mdo** [comment]
You mention Beta 2 here, but you're fiddle uses Alpha 2. I've created a CodePen with the latest version: https://codepen.io/emdeoh/pen/OOLbXZ. Tons has changed since that release, so be careful in updating. This, however, still doesn't solve the problem.

There's no good way to solve this either—the nav doesn't know that the button is next to it, nor does the header know there's a nav and a button. I don't think we can write any good CSS that would target both situations for everyone.

**Comment by fredgate** [comment]
No my fiddle uses the beta 2 : https://jsfiddle.net/Ld3uwxse/
It is the old fiddle issued from another old issue that uses alpha 2. And in alpha2, it was working.
With new beta2, it does not work.

**Comment by gijsbotje** [comment]
it's exactly what you described @fredgate , but i'm with @mdo on this one: there is no good way to fix it
in customized sass builds this error will still exist

**Comment by andresgalante** [comment]
+1 I agree with what @gijsbotje and @mdo comments. I don't think there is a way to create a universal solution for it. This is something that each user will have to fine tine on their implementations.

**Comment by Joyrex** [comment]
A simple solution is to add `py-0` to the floated button - very minor visual difference, and solves the issue.

**Comment by andresgalante** [comment]
@fredgate Here is an ugly way to get around it with utility classes:
https://codepen.io/andresgalante/pen/qVEMLv?editors=1100

flex instead of float and then adjust the margin/padding.

**Comment by mdo** [comment]
Closing as a won't fix.
