### ISSUE TITLE
Popover over zero-width element is displayed on the top-left corner of the page

### ISSUE THREAD

**Issue by stepancheg** [twbs/bootstrap#24552]
Fiddle: https://jsfiddle.net/stepancheg/uuhrfws1/4/
Code:

```
<div style="background: cyan; height:  100px">Padding</div>

<div
  data-toggle="popover"
  title="Popover title"
  data-content="Amazing content"
  data-trigger="hover"
  data-animation="false"
  data-placement="bottom"
  style="border: solid 5px red">
<!-- Zero height div; hover here -->
</div>

Popover is expected to appear right above this message
when you hover over red border.
But it appears at the top of the page.
```

Screenshot:
<img width="494" alt="2017-10-25_1438" src="https://user-images.githubusercontent.com/28969/32001670-595f78da-b992-11e7-8c2f-ca74a6903f1e.png">

Hover over red line (border).
**Actual result**: popover appears near the top left of the page.
**Expected**: popover should be near red line.

Bootstrap: 4.0 beta 2
Operating system: macOS
Browser: Firefox 56.0 or Chrome 62.0.3202.62.

**Comment by Johann-S** [comment]
Seems related to Popper.js 
Maybe @FezVrasta already know this issue ?

**Comment by FezVrasta** [comment]
That looks like a Popper.js bug, mind if I ask you to open this issue on the Popper.js repository?

**Comment by Johann-S** [comment]
@FezVrasta did you fix that bug ?

**Comment by FezVrasta** [comment]
I don't think anybody opened an issue for this bug on the repository, I use it to schedule my work

**Comment by mdo** [comment]
Given where this convo ended off, closing as stale and not a Bootstrap bug.
