### ISSUE TITLE
valid/invalid custom select reverts to default border color on focus

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#24553]
Version: Boostrap V4.0.0-beta.2
Browser: Any
OS: Any

Custom select border color, when valid or invalid, reverts back to default (non-validated) blue border color while focused, although box-shadow coloring is correct In this example I am using classes `.is-invalid` and `.is-valid` on the custom select.

![image](https://user-images.githubusercontent.com/2781561/32021827-ebf09680-b9aa-11e7-8dc8-b1ec9baac749.png)

And a zoomed in image to show the detail:
![image](https://user-images.githubusercontent.com/2781561/32022894-209e93e8-b9ae-11e7-86c0-f4b78dad5ba7.png)

**Comment by mdo** [comment]
Can you verify the problem in `v4-dev` with a live demo?

**Comment by tmorehouse** [comment]
Sure,  I'll see if I can get a fiddle or jsbin set up.

**Comment by tmorehouse** [comment]
Here is a pen with beta.2: https://codepen.io/tmorehouse/pen/vWBgaw

I'll try and get a pen with the dev branch CSS made in a few moments

**Comment by tmorehouse** [comment]
And here is a pen using the raw link to bootstrap.css from the dev-branch (via https://rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css)

https://codepen.io/tmorehouse/pen/GOKreg

**Comment by tmorehouse** [comment]
Bot of the above pens exhibit the same behavior when the custom selects are focused.

**Comment by sabrown84** [comment]
Hi @tmorehouse,

I took a look. I see what you mean. Thank you for providing the codepen and the raw link. I added the !important to the css and I think it works.
I forked your pen and added the change. What do you think? @mdo @tmorehouse

**Comment by sabrown84** [comment]
Oh here is the pen link:

https://codepen.io/sdporter84/pen/pdzqrL

**Comment by mdo** [comment]
@sabrown84 Instead of adding `!important` to the previous rule, we need to override the `:focus` state's `color` for the `.custom-select`. So in this snippet, instead of just the `box-shadow` in that `&:focus { }`, add `border-color: $color;`.

https://github.com/twbs/bootstrap/blob/380c920f1c32681fdd0f3375b2ea3e1739fdd6a9/scss/mixins/_forms.scss#L53-L68

See this in action at https://codepen.io/emdeoh/pen/YEzpeQ.

**Comment by NoobCoder-f** [comment]
gncgncgnn

**Comment by SuperJ-1** [comment]
I don't understand anything here 😔 even though I want this help
