### ISSUE TITLE
Issue in the bootstrap Popover page in website

### ISSUE THREAD

**Issue by RandyRam** [twbs/bootstrap#24558]
In the website of bootstrap 4, popover page (i.e) https://v4-alpha.getbootstrap.com/components/popovers/
has an issue. The issue is regarding the static popover section in which when we scroll down the page the popovers overlaps the fixed box on the top of the page.

**Comment by Johann-S** [comment]
what's your issue ?

**Comment by tmorehouse** [comment]
I can see that effect in the docs as well:
![image](https://user-images.githubusercontent.com/2781561/32059275-02020994-ba42-11e7-83d2-13f15a7ff6c5.png)

It appears the z-index of the static popovers it still high, rather than set back to initial for the static demos.
