### ISSUE TITLE
btn-group with radiobuttons does not change checked state of radiobutton when clicking button

### ISSUE THREAD

**Issue by jurgendl** [twbs/bootstrap#24564]
example found here: https://getbootstrap.com/docs/4.0/components/buttons/

when clicking a button it doesn't change the selected radiobutton (input type=radio) it represents, only the active state of the label=btn

```
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-secondary active">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Radio 1 (preselected)
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="option2" autocomplete="off"> Radio 2
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Radio 3
  </label>
</div>
```

**Comment by jurgendl** [comment]
it seems the  'checked' attribute does not change on plain radiobuttons when inspecting in chrome/firefox

so I think you can close this issue

**Comment by ysds** [comment]
The `checked` attribute means **checked by default**. This attribute won't change when the radio/checkbox is clicked.

**Comment by patrickhlauke** [comment]
yes, the attribute (which you see in DevTools inspector) won't change. you'd want to check the actual `checked` *property* of the node (which does seem to work fine from testing the example in the docs).
