### ISSUE TITLE
Scrolling modals with iOS is not fluid

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#24560]
If you open a modal in iOS (tested on 10) that needs to be scrolled (http://getbootstrap.com/docs/4.0/components/modal/#scrolling-long-content) the scroll of the modal is not fluid.

I'm not sure if this is related to [this bug](https://github.com/twbs/bootstrap/issues/22311) and the scroll of the modal is laggy because of the background or if it's a different bug.

**Comment by andresgalante** [comment]
Hi @natcohen thanks for reporting this. I'll close this issue since there is a discussion about this topic here #24737
