### ISSUE TITLE
dropup not working with dropdown-header

### ISSUE THREAD

**Issue by devmws** [twbs/bootstrap#24568]
When creating a "dropup" button including a "dropdown-header" it's not working and it act as it is a usual .dropdown

see the snippet: https://codepen.io/anon/pen/bYbGdG?editors=1100 
-- try to delete the dropdown-header and it will work!

**Comment by mdo** [comment]
Give the dropup more room: https://codepen.io/emdeoh/pen/QOLGrX?editors=1100. It'll automatically move if there's not enough room.

**Comment by Johann-S** [comment]
if you don't want the `flip` behavior you can add : `data-flip="false"` :wink:
