### ISSUE TITLE
Bootstrap 4 Offline Docs as (HTML) Files

### ISSUE THREAD

**Issue by Mu9tafa-Online** [twbs/bootstrap#24567]
Is there any way to download (BS4 Docs) as HTML files ?? so there is no need to open localhost, many people are looking for it.

**Comment by bkdotcom** [comment]
> many people are looking for it.

citation needed

**Comment by mdo** [comment]
Download the `gh-pages` branch and run a local server somehow, like Python: `python -m SimpleHTTPServer 8000`.

**Comment by XhmikosR** [comment]
Or if you use a browser which supports service workers, you can visit https://getbootstrap.com/ and navigate offline.

**Comment by Mu9tafa-Online** [comment]
Thanks @XhmikosR - i downloaded the ph-pagrs + using live-server branch as Mdo said .. it works fine :)
