### ISSUE TITLE
Reset Bootstrap CSS

### ISSUE THREAD

**Issue by aavmurphy** [twbs/bootstrap#24578]
The documentation ( http://getbootstrap.com/docs/4.0/getting-started/introduction/#box-sizing ) shows how to reset bootstrap for 3rd party things.

Its missing a few things to un-opinionate "reboot".

.reset {
  box-sizing: content-box;
  line-height: normal;
  }
.reset table {
  width:auto;
  border-collapse: separate;
  }

The doco. gives Google Maps as an example - no worries, it works fine without this. Google Custom Search however, does need it.

Could add a new .reset utility class, or just update the doco.  Can do a PR

**Comment by mdo** [comment]
No plans on adding such a class, thanks though.
