### ISSUE TITLE
Div Wrap Bug

### ISSUE THREAD

**Issue by BurtiNET** [twbs/bootstrap#24576]
```
<div class="container-fluid mt-3 bet-slip">
	<div class="row">
		<div>
			<div class="col-12 text-center">
				<h5 class="col-title">Slip</h5>
			</div>
			<div class="clearfix"></div>
			<div class="col-6 text-center">
				<a href="#" class="btn btn-danger">Login</a>
			</div>
			<div class="col-6 text-center">
				<a href="#" class="btn btn-register">Logout</a>
			</div>
		</div>
	</div>
</div>
```
If wrap any div on col its not working normally.

**Comment by jipexu** [comment]
Hi 
from the doc ...
In a grid layout, content must be placed within columns and only columns may be immediate children of rows.

remove the unclassed div or give it a appropriate class ...

**Comment by BurtiNET** [comment]
@jipexu I know if I insert any display type or any details it cannot be working but it was work on alpha version.

**Comment by jipexu** [comment]
flex flex flex ....
yep...  in other word the .col lost the flex properties because the div ...

**Comment by BurtiNET** [comment]
How can I wrap one div for this ? I want only white background...
