### ISSUE TITLE
Carousel left and right buttons only working with 3.2.1.slim.min.js

### ISSUE THREAD

**Issue by sunnydumalu** [twbs/bootstrap#24575]
Carousel left and right indicators not working with minified and full jquery library.

**Comment by patrickhlauke** [comment]
you need to provide a live reduced test case to show the issue.

further, 3.2.1 is an outdated version, 3.3.7 is the latest on the v3 branch.

lastly, there are no more planned fixes for v3, as all efforts are focused now on getting v4 to first stable release.

in light of this, I'd suggest directing your question/problem to StackOverflow or similar, see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
