### ISSUE TITLE
Don't block using Bower

### ISSUE THREAD

**Issue by NielsHolt** [twbs/bootstrap#24584]
Hi

I understand why you don't support Bower anymore, but there are no need to block for Bower by having an invalid bower.json
Could you please remove bower.json making it possible for those of us who haven't had time to switch away from Bower to  still include Bootstrap (manually) in our projects

**Comment by myorangeca** [comment]
@NielsHolt 

Wondering if this was the reason why I was seeing the error in bower(?)
https://github.com/twbs/bootstrap/pull/24590#issuecomment-340313483
