### ISSUE TITLE
glyphicons fonts

### ISSUE THREAD

**Issue by engrshahabuddin** [twbs/bootstrap#24581]
Did you remove glyphicons fonts from bootstrap 4.0.0 ?

**Comment by jgacuca567** [comment]
@engrshahabuddin 
Glyphicons Fonts was dropped check out the **Components** from the Bootstrap Link https://v4-alpha.getbootstrap.com/migration/

**Comment by mdo** [comment]
Yes, and it's in the migration docs. Head there if you're curious about any other changes like this.

**Comment by engrshahabuddin** [comment]
I also saw that bootstrap is 1140px that was 1170px in 3.x
Why ?
