### ISSUE TITLE
Custom Select Border and Custom File Browser when active or focus not displaying properly

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#24597]
only the normal 
the validation variant works

testet on FF and Chrome win 10

![unbenannt-1](https://user-images.githubusercontent.com/1651241/32160252-37b3b508-bd51-11e7-8a35-eb902d92549e.jpg)

**Comment by mdo** [comment]
Hmm, to do this right, we need `-webkit-appearance: none` on the `<select>`s... might have to merge custom select and this one after all. Let me think about it for a bit.

**Comment by jonnysp** [comment]
not that we talk past each other . I mean the thick border on focus, around the the custom select! 
On validation it works but not on standard focus.

**Comment by mdo** [comment]
@jonnysp I fixed the thick dark border on focus of the custom file input in #24699. Custom selects are also good to go with the changes in that PR. However, there is a problem with regular `<select>`s where, given browser default styles, we need to make additional changes for focus styles to be applied there via `box-shadow`. You cannot style the shadows without resetting so much more for these macOS based browsers.

**Comment by jonnysp** [comment]
@mdo the border is again different in version 4

**Comment by victorwpbastos** [comment]
Same here
