### ISSUE TITLE
Custom Radio and Checkbox broken when $enable-gradients is true

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#24598]
![unbenannt-2](https://user-images.githubusercontent.com/1651241/32160656-f60f10a0-bd52-11e7-8986-8ecc82a802f0.jpg)

**Comment by Bilal-io** [comment]
How can this be tested?
Does it behave the same way in different browsers, or is browser specific?

**Comment by jonnysp** [comment]
Hi
i testet on win 10 in latest ff, ie and edge
![firefox](https://user-images.githubusercontent.com/1651241/32209386-53cac9f4-be08-11e7-8839-88def71cf40f.JPG)

![ie](https://user-images.githubusercontent.com/1651241/32209389-5875029e-be08-11e7-8038-a60da19c458d.JPG)

![edge](https://user-images.githubusercontent.com/1651241/32209391-5b8563d4-be08-11e7-892d-fe8f5589e9b4.JPG)

and on macosHS safari and latest ff
![osx-safari](https://user-images.githubusercontent.com/1651241/32209411-73dc2ca6-be08-11e7-9edb-97f6c0a4001d.JPG)
![osx - firefox](https://user-images.githubusercontent.com/1651241/32209412-768db4b0-be08-11e7-9b12-c55d17359a34.JPG)

**Comment by mdo** [comment]
Fix coming in #24697. Please review and test if you can!
