### ISSUE TITLE
missing map ressources in DOC page

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#24608]
Hi on this page 
https://getbootstrap.com/docs/4.0/components/forms/
we get : 
Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (docsearch.min.js.map, line 0)

https://cdn.jsdelivr.net/docsearch.js/2/dist/cdn/docsearch.min.js.map

**Comment by mdo** [comment]
Probably something the DocSearch folks can help with? /cc @maxiloc

**Comment by MartinKolarik** [comment]
For the map files to work, you'll need to use a new version of the CDN link: https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js

The official documentation should be updated soon (see algolia/docsearch#207).

**Comment by XhmikosR** [comment]
@MartinKolarik: please make a PR, thanks.
