### ISSUE TITLE
"nav-tabs" and "nav-link" border color the same as "border"

### ISSUE THREAD

**Issue by kisonic** [twbs/bootstrap#24600]
There is a little difference between border color in `.nav-tabs`, `.nav-tabs .nav-link.active` (`#dddddd`) and in `.border` (`#e9ecef`).

https://codepen.io/kisonic/pen/WXbRLb

Why not make them the same?

**Comment by Johann-S** [comment]
Please can you use our latest beta ? (beta 2)

**Comment by kisonic** [comment]
@Johann-S yep, updated https://codepen.io/kisonic/pen/WXbRLb
Still different colors.

**Comment by andresgalante** [comment]
Hi @kisonic thanks for reporting this. I think the difference is intentional to make hover look a bit lighter. Having said that I'll send a PR to remove hardcoded colors.
