### ISSUE TITLE
Add `cursor: pointer` for `details`?

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24617]
Noticed this on our docs, https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/introduction.md

/CC @mdo

**Comment by andresgalante** [comment]
What's the point to hide that list? I think we should remove the collapsible section and have the list visible.

**Comment by XhmikosR** [comment]
That too; I was thinking the same after I opened the issue.

**Comment by mdo** [comment]
That list is hidden as IMO it goes too far in depth to be always shown for "getting started" but it's still the best place to show that information.
