### ISSUE TITLE
Button cursor is default arrow..

### ISSUE THREAD

**Issue by boutzamat** [twbs/bootstrap#24616]
Is there any specific reason that cursor:pointer has been removed from buttons? 
Previous Bootstrap versions all had a pointer when hovering input-type button, and "btn" classes.

Is easy to override per use, but would be cool to have as a default setting in Bootstrap.

**Comment by Johann-S** [comment]
A simple search : "Button cursor" would give your the reason : https://github.com/twbs/bootstrap/pull/21812
