### ISSUE TITLE
Undefined variable: "$alert-padding-y".

### ISSUE THREAD

**Issue by IonicaBizau** [twbs/bootstrap#24614]
I'm trying to add Bootstrap 4 in a Ruby on Rails app, using [RubyGems](https://getbootstrap.com/docs/4.0/getting-started/download/#rubygems).

- Operating system and version: macOS High Sierra 

I'm simply getting this error from the server:

```
Sass::SyntaxError at /
Undefined variable: "$alert-padding-y".
```

I included Bootstrap Beta 2 in Gemfile, and ran `bundle update`.

**Comment by mikeburry** [comment]
I'm having the same issue.  Same setup.  :-(

**Comment by mdo** [comment]
Hmm, can you try with the latest from `v4-dev` instead by chance? The variable is there in `_variables.scss`. Alternatively, can you verify the variable exists in your `_variables.scss` file?

**Comment by IonicaBizau** [comment]
I think it's because of the `precompile` array... but I'm not a RoR expert. There is a similar issue here: https://github.com/twbs/bootstrap-sass/issues/863

From what I can understand a different `scss` file is loaded before `_variables.scss`, therefore it can't find that variable.

If I get some free time, I will try the `v4-dev` and see.
Thanks for the amazing work! ✨

**Comment by zeiv** [comment]
Using current master didn't work, however _this_ did:

`gem 'bootstrap', '4.0.0.alpha6'`

**Comment by mdo** [comment]
Closing since this isn't sounding like a bug on our end.

**Comment by bgaillard** [comment]
Hi, I also encountered this problem today. 

In my case I'm using Bootstrap 4 with Jekyll, the problem was that I declared `gem 'bootstrap'` outside `group :jekyll_plugins`. 

This does not work and generates the `Undefined variable: "$alert-padding-y"` error. 

```
gem 'bootstrap'
```

Moving the instruction inside `group :jekyll_plugins` makes it work.

```
# If you have any plugins, put them here!
group :jekyll_plugins do
   gem 'bootstrap'
   ...
end
```
