### ISSUE TITLE
Endless loading of service workers on getbootstrap website

### ISSUE THREAD

**Issue by TomasFrantik** [twbs/bootstrap#24622]
Hello 🙂 

I get [these warnings](https://slack-files.com/T04GZKGQY-F7S46MJBT-a94af5f718) after clicking on the links. It causes an infinite pageload and I will not get to the desired pages. I get same warnings across the whole website - all links causes this problem and it loads new service worker over and over again..

Win10, Chrome v61.0.3163.100

**Comment by gijsbotje** [comment]
error message says it all, you have an option in the dev tools checked

open your dev tools > go to the application tab and uncheck `update on reload`

**Comment by TomasFrantik** [comment]
Yes I know but it does not affect service workers if the devtools are turned off or does it?

**Comment by gijsbotje** [comment]
apparently it does, otherwise you wouldn't get that behaviour

**Comment by TomasFrantik** [comment]
No.. rly.. it does not, you can try it :) Maybe I chose the wrong way to report the problem. I had problem with page loading couple of minutes **before** I opened the devtools. I opened devtools to find out where is the problem, why the new pages are not being loaded after click on link, and all I saw was repeated loading of sw.js in network panel and after reload i get these warning messages..

Now it works.. I cleared the site data. However `update on reload` option is still checked and it does not affect the web when the devtools are turned off. So.. The question is, why did I have to copy links urls to the address bar to get to the next page (devtools off) before `clear site data`? :) And why sw.js on my or other sites do not have such problems when `update on reload` option is checked?

**Comment by XhmikosR** [comment]
Not sure what we can do, or if there's even something we can do...

**Comment by TomasFrantik** [comment]
@XhmikosR It looks like the workbox-sw have not unregister method for removing service workers on update. This may cause new registration or update issues.

**Comment by XhmikosR** [comment]
@TomasFrantik: can you make an issue there and CC me?

**Comment by XhmikosR** [comment]
Closing in favor of #24868
