### ISSUE TITLE
feature request: .list-striped

### ISSUE THREAD

**Issue by exige81** [twbs/bootstrap#24628]
Looking to add a **`list-striped`** class that is similar to **`table-striped`** to create a little more visual distinction between list-group-items.  This is especially helpful on wider lists.  _Switching to a single column table to use table-striped isn't really semantically correct._

Sample codepen here: https://codepen.io/anon/pen/JOdBGG

Unfortunately this starts to fall apart when combined with other styles such as .active or the contextual classes..

If it's acceptable that a list-group-striped class doesn't play well with other list-group styles, I could submit a PR for this, otherwise perhaps someone with more expertise can provide a more elegant solution.

**Comment by mdo** [comment]
Is it enough to have folks use `.bg-light` where this is needed?

**Comment by exige81** [comment]
That's an option, though if you have a huge list you'd need to add `.bg-light` dynamically to every other item (or via custom css).

**Comment by mdo** [comment]
Closing per #27871.
