### ISSUE TITLE
table-responsive class does not take full width

### ISSUE THREAD

**Issue by davidism** [twbs/bootstrap#24638]
This was previously reported in #24256, which was closed after #24438 was merged. However, that merge was only documentation, and the issue doesn't actually appear to be fixed in Beta 2.

A table with the `table-responsive` class will not render at full width. I'm not sure why it works in the example in the docs, but this [codepen](https://codepen.io/anon/pen/EbVvRb) demonstrates that the issue still persists.

```html
<table class="table table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>David</td>
      <td>Developer</td>
      <td>None</td>
    </tr>
  </tbody>
</table>
```

![screenshot_2017-11-01_12-00-12](https://user-images.githubusercontent.com/1242887/32292098-3ddc184c-befc-11e7-8824-7cff68857ebc.png)

![screenshot_2017-11-01_12-01-01](https://user-images.githubusercontent.com/1242887/32292134-5985d3c6-befc-11e7-9d55-c05841d8b2bb.png)

The issue occurs on both Firefox 58 and Chrome 62.

**Comment by browner12** [comment]
simple solution, use a wrapping `<div>` with the `table-responsive` class.

```html
<div class="table-responsive">
    <table class="table"></table>
</div>
```

**Comment by davidism** [comment]
OK, but why doesn't the documentation example need that?

**Comment by jipexu** [comment]
this is the display block in .table-responsive  ...

**Comment by tmorehouse** [comment]
In the documentation examples, the reason it appears to "work" is that there is enough content in the table to force it to full width inside the container..

**Comment by jipexu** [comment]
true

**Comment by matthewmalone** [comment]
+1 to get the documentation updated, please!

**Comment by FTWinston** [comment]
Is it definitely the intention that the table-responsive class _not_ be put on a table any more?

Or is that just a workaround? Cos it seems a bit weird.

**Comment by shtse8** [comment]
It seems we should have to wait for the next release.

**Comment by tmorehouse** [comment]
One other caveat with placing `table-responsive` on the table element  is for screen readers.

When a `<table>` has a CSS `display` of any value other than `table`, the table is no longer presented to screen readers as being a table structure, and requires placing an explicit `role` on each element within the table (i.e. `table`, `rowgroup`, `row` and 'cell`)

**Comment by mdo** [comment]
Stylistically I've preferred the narrower tables on larger screens, and I've stated it's intentional. However, for the a11y reason alone, we'll fix this up.

**Comment by suraj3103** [comment]
> simple solution, use a wrapping `<div>` with the `table-responsive` class.
> 
> ```
> <div class="table-responsive">
>     <table class="table"></table>
> </div>
> ```

THANKS MAN

**Comment by stonestecnologia** [comment]
Hi, 
see doc
https://getbootstrap.com/docs/4.0/content/tables/

`<div class="table-responsive">
    <table class="table"></table>
</div>`

#sucess

**Comment by dsm-72** [comment]
@browner12 Nope not doing it for me. Any other ideas? Note that the div and the table when view with inspector are 100% but the thead and tbody are not

**Comment by suraj3103** [comment]
Thanks

**Comment by kamleshwebtech** [comment]
> simple solution, use a wrapping `<div>` with the `table-responsive` class.
> 
> ```
> <div class="table-responsive">
>     <table class="table"></table>
> </div>
> ```

This does not work if table-responsive div is inside a table's td. Any solution?? Please suggest me. Thanks.
