### ISSUE TITLE
.form-control-file breaks out of column if input's width is bigger than column's width

### ISSUE THREAD

**Issue by istratos** [twbs/bootstrap#24637]
When using an input of type file (no classes) or with `.form-control-file` class inside a smaller column than the input's width, it breaks out of the column instead of being 100% width of its parent. Apparently custom file input is fine.

OS: macOS Sierra 10.12.6
Browser: Firefox 56, Chrome 61, Safari 11
JSBin: http://jsbin.com/xukuvofuwu/1/edit?html,output

You can resize the output window to around 700px to see what I mean. I don't know if it's supposed to be this way but I feel like it needs a fix. At least for the `.form-control-file` class since that is present in BS and should behave accordingly if possible.

**Comment by mdo** [comment]
This was fixed in #25054 with the `width: 100%` on that class.
