### ISSUE TITLE
Uncaught ReferenceError: Popper is not defined

### ISSUE THREAD

**Issue by maofree** [twbs/bootstrap#24635]
Hi
I get the same error reported here
https://stackoverflow.com/questions/46952775/bootstrap-4-uncaught-referenceerror-popper-is-not-defined

bootstrap's version is 4.0.0 beta 2
popper's version is 1.12.6

I use them on wordpress 4.8.2 with chromium 62.0.3202.75 on Arch Linux 64bit (I'm testing it on my local server on debian 9)

![1](https://user-images.githubusercontent.com/653230/32269905-218529f2-bef4-11e7-90c5-4eb5c5c87fd5.png)

I report here another small problem that I see from its web toolkit
"invalid proporty value" if I select the "a" tag
-webkit-text-decoration-skip: objects;

a {
    color: #007bff;
    text-decoration: none;
    background-color: transparent;
    -webkit-text-decoration-skip: objects;
}

from _reboot.scss on line 199

![2](https://user-images.githubusercontent.com/653230/32270151-06ee2138-bef5-11e7-9d72-ef9d5ba158ee.png)

thanks
bye

**Comment by Johann-S** [comment]
Popper.js should be included before bootstrap not after 😉 
About the invalid that's because your browser don't need this CSS rule but they are users which will need that

**Comment by maofree** [comment]
Hi
thanks
changing the order now it is ok

bye

**Comment by engrshahabuddin** [comment]
I am getting same issue.
Please check my link-
http://devstheme.net/

give solution.

**Comment by NazreAlam** [comment]
ReferenceError: Popper is not defined

After changing order I am getting this error..

SyntaxError: export declarations may only appear at top level of a module
popper.min.js:4:17879
ReferenceError: Popper is not defined
[Learn More]
bootstrap.js:3849:1

**Comment by Johann-S** [comment]
That's because you didn't choose the UMD release of Popper.js @NazreAlam

**Comment by shmakovpn** [comment]
Use https://unpkg.com/popper.js@1.12.9/dist/umd/popper.js.

**Comment by PCMS88** [comment]
@shmakovpn so where do you paste the info in the file you provided?? I'm new a JS and attempting to create a basic app (my first one!), I'm very early into the project and I CANNOT seem to get my JS to work because of this undefined..popper bullshit. I have the script in the correct order. I downloaded it properly and am using local storage... yet I keep getting this error. Please help. Thanks!

**Comment by shmakovpn** [comment]
@PCMS88 templates/base.html
You need it
<script src="{% static 'js/popper.js' %}" ></script> 
before that
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
You can find popper.js and my base.html in github.com/shmakovpn/jobex
