### ISSUE TITLE
Tooltip/popover overwrites existing aria-describedby attribute

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#24640]
- Operating system and version : Any
- Browser and version: Any
- Reduced test case: https://codepen.io/tmorehouse/pen/RjWMgg (Bootstrap latest DEV version)

Tooltips and popovers do not preserve the trigger element's existing `aria-describedby` attribute value. 

The `aria-describedby` attribute supports specifying multiple space separated element ID's.

When adding a tooltip or popover to an element that has an existing `aria-describedby` attribute, the attribute is removed. And when opened the attribute is set only to the auto generated tooltip/popover ID.  When the tooltip (or popover) is closed, the original `aria-describedby` is not restored. (the attribute is completely removed)

The above codepen results in the following markup:
![image](https://user-images.githubusercontent.com/2781561/32302029-5eb5e83e-bf3f-11e7-9e12-3526241914a9.png)

Noe that the original `aria-describedby` attribute is not present on the input element.

**Expected behavior:**
That the tooltip (or popover) ID is added to the existing `aria-describedby` attribute when opened, and when closed the tooltip/popover ID is removed from the `aria-describedby` attribute (leaving any original ids in the attribute).  If there wasn't any `aria-describedby` attribute on the trigger element, then the attribute can be removed.

**Comment by tmorehouse** [comment]
The following code can be used to add/remove the tooltip/popover ID from `aria-describedby` (assumes the generated ID is in `id`)

```js
// Setting aria-describedby:
let adb = el.getattribute('aria-describedby') || ''
el.setAttribute('aria-describedby', adb.split(/\s+/).concat(id).join(' '))

// Clearing aria-describedby:
let adb = el.getAttribute('aria-describedby') || ''
adb = adb.split(/\s+/).filter(i => i !== id).join(' ')
if (adb) {
  el.setAttribute('aria-describedby', adb)
} else {
  el.removeAttribute('aria-describedby')
}
```

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
