### ISSUE TITLE
Safari layout bug

### ISSUE THREAD

**Issue by NHWhiteley** [twbs/bootstrap#24647]
See a stripped down version here: https://jsfiddle.net/dkmsuhL3/

I believe I have the syntax correct but the two col-sm-6 columns are not fitting horizontally on Safari (5.1.7)

Visual: https://i.stack.imgur.com/qACrs.jpg

**Comment by Ghost180195** [comment]
Is it safari for Microsoft Windows os?

**Comment by NHWhiteley** [comment]
Yes

**Comment by Ghost180195** [comment]
Dear friend, you are behind the times.)
Apple has long ceased to develop safari for Microsoft Windows os.

**Comment by tousif12** [comment]
check on apple device . Ghost180195 is right

**Comment by NHWhiteley** [comment]
My clients certainly are behind the times... I thought I'd raise the issue as I wasn't sure how far back bootstrap support intended to go, clearly not this far. Good to know.
