### ISSUE TITLE
 just link-the new Bootstrap’s documentation for simplified Chinese 

### ISSUE THREAD

**Issue by zoomla** [twbs/bootstrap#24642]
hi，Dear Bootstrap team,
We translated the bootstrap 4 Documents ,the website is：http://code.z01.com/v4 ， TI Is the best simplified Chinese version, hoping to add to http://getbootstrap.com/docs/4.0/about/translations/ … list.

Hope can pass

**Comment by XhmikosR** [comment]
@zoomla: you can make a PR to add it.

**Comment by zoomla** [comment]
Thanks for accepting
In order to translate it, we spent 2 weeks, and will continue to maintain it!
