### ISSUE TITLE
Expansion for bg- classes

### ISSUE THREAD

**Issue by sisao** [twbs/bootstrap#24655]
When reading the docs for color utils (http://getbootstrap.com/docs/4.0/utilities/colors/#background-color) I expected the bg- classes would be generated for all colors, not just for theme-colors.

Is it useful to add those classes or is this there a reason for this decision?

I added a pull requst for explanation:  #24654

**Comment by mdo** [comment]
As mentioned in the PR, we purposefully want to limit the color utilities.
