### ISSUE TITLE
$enable-* Variables for each component

### ISSUE THREAD

**Issue by FlorianKoerner** [twbs/bootstrap#24653]
What do you think about creating a `$enable-*` variable for each component? So the [bootstrap.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss) would be even more modular.

By default, the variables would be set to `true`. For example, if the "jumbotron"component is not desired, you could disable it as follows:

```
$enableJumbotron: false;
```

https://v4-alpha.getbootstrap.com/getting-started/options/

**Comment by andresgalante** [comment]
Hi @FlorianKoerner that's not a bad idea. It'd be a way to bring back a feature similar to what the customizer did from v3: https://getbootstrap.com/docs/3.3/customize/

You can do that today by importing the scss files you want on your scss, instead of importing bootstrap as a whole.

Also, heads up, documentation for BS4 beta are here now: https://getbootstrap.com/docs/4.0/

**Comment by FlorianKoerner** [comment]
Sure. But I think variables are more convenient than duplicating the `bootstrap.scss`. And the customizer are not so helpful, if you use `npm` or `bower`.

**Comment by andresgalante** [comment]
@FlorianKoerner yeap, not only more convenient but also more maintainable for users.

It's up to @mdo to decide.

**Comment by mdo** [comment]
This is essentially the same as commenting out an import statement in `bootstrap.scss`. I know there's a bit more to it when it comes to shared components, but it's basically 1:1. It's been requested before and I was a pass then, still am now.

**Comment by FlorianKoerner** [comment]
@mdo yes, but you have to copy the `bootstrap.scss` before. Duplicated content has always been a bad practice.

The following example shows - this is not 1:1 the same thing.

```scss
$enableImages: false;

@import 'node_modules/bootstrap/scss/bootstrap.scss'
```

vs

```scss
@import "node_modules/bootstrap/scss/functions";
@import "node_modules/bootstrap/scss/variables";
@import "node_modules/bootstrap/scss/mixins";
@import "node_modules/bootstrap/scss/root";
@import "node_modules/bootstrap/scss/print";
@import "node_modules/bootstrap/scss/reboot";
@import "node_modules/bootstrap/scss/type";
//@import "node_modules/bootstrap/scss/images";
@import "node_modules/bootstrap/scss/code";
@import "node_modules/bootstrap/scss/grid";
@import "node_modules/bootstrap/scss/tables";
@import "node_modules/bootstrap/scss/forms";
@import "node_modules/bootstrap/scss/buttons";
@import "node_modules/bootstrap/scss/transitions";
@import "node_modules/bootstrap/scss/dropdown";
@import "node_modules/bootstrap/scss/button-group";
@import "node_modules/bootstrap/scss/input-group";
@import "node_modules/bootstrap/scss/custom-forms";
@import "node_modules/bootstrap/scss/nav";
@import "node_modules/bootstrap/scss/navbar";
@import "node_modules/bootstrap/scss/card";
@import "node_modules/bootstrap/scss/breadcrumb";
@import "node_modules/bootstrap/scss/pagination";
@import "node_modules/bootstrap/scss/badge";
@import "node_modules/bootstrap/scss/jumbotron";
@import "node_modules/bootstrap/scss/alert";
@import "node_modules/bootstrap/scss/progress";
@import "node_modules/bootstrap/scss/media";
@import "node_modules/bootstrap/scss/list-group";
@import "node_modules/bootstrap/scss/close";
@import "node_modules/bootstrap/scss/modal";
@import "node_modules/bootstrap/scss/tooltip";
@import "node_modules/bootstrap/scss/popover";
@import "node_modules/bootstrap/scss/carousel";
@import "node_modules/bootstrap/scss/utilities";
```
