### ISSUE TITLE
PLEASE BACK BOWER!!

### ISSUE THREAD

**Issue by htmldiz** [twbs/bootstrap#24650]
Hi here is link see how many people use bower http://prntscr.com/h5et9j PLEASE back it. We cant work without bower and boostrap .

**Comment by browner12** [comment]
Probably not going to happen.

As you probably know, Bower is no longer in active development, and suggests using Yarn or Webpack to manage your dependencies. 

I'm pretty sure you can continue using BS3 with Bower, but if you want the latest and greatest, yah gotta upgrade.

**Comment by mdo** [comment]
That number is stars here on GitHub, not a Bower specific stat.

Bower is dead—you should be migrating your projects to npm, Yarn, webpack, etc.
