### ISSUE TITLE
bg-colors and links

### ISSUE THREAD

**Issue by Soullivaneuh** [twbs/bootstrap#24658]
On current beta2, with this HTML piece:

```html
<div class="bg-primary text-light pl-5 pr-5 pt-5 pb-5">
    <p>
        This is a sample paragraph.
    </p>
    <p>
        And here, a <a href="#">link</a>.
    </p>
    <p>
        And another <a href="#" class="text-light">one</a> with color class.
    </p>
</div>
```

We have this:

![image](https://user-images.githubusercontent.com/1698357/32372329-a7ca1a9e-c094-11e7-85d3-164d0e272ace.png)

So in order to not have issue with links, we have to specified `text-light` on each of them. This will going to be cumbersome when having multiple links like this.

IMHO, we should find a way to apply a color globally from the div containing the `bg-*` class.

#23570 was closed, but it should be re-considered, it's not a bad idea. cc @mdo @justindocanto

Or maybe another solution? In any case, something should be proposed for this case.

Regards.

**Comment by mdo** [comment]
My comment there still stands: https://github.com/twbs/bootstrap/issues/23570#issuecomment-323601774. Utilities are used for very specific situations; they don't always work for every situation.

**Comment by Soullivaneuh** [comment]
@mdo What would you recommend for this case? An entry on the cookbook would be appreciated. :+1:

**Comment by Soullivaneuh** [comment]
@mdo May I have any answer? Even short? Thanks.
