### ISSUE TITLE
Tooltip stays in place after element removal

### ISSUE THREAD

**Issue by dominikfiala** [twbs/bootstrap#24663]
If you define a Tooltip on an element that is later removed from DOM, the tooltip stays in place and must be deleted manually.

Probably Popper.js/Tooltip.js issue.

See https://codepen.io/dominikfiala/pen/vWLMMz?editors=1010

Edit: Not a Popper.js issue. The problem does not occur in Popper.js, see https://codepen.io/dominikfiala/pen/aVdgBr?editors=1010

**Comment by dominikfiala** [comment]
Edit: Not a Popper.js issue. The problem does not occur in Popper.js, see https://codepen.io/dominikfiala/pen/aVdgBr?editors=1010

**Comment by alecpl** [comment]
There's a note in documentation: "Tooltips must be hidden before their corresponding elements have been removed from the DOM." However, it would be nice to have this limitation removed.

**Comment by mdo** [comment]
Closing as a (stale) won't fix given the docs mention.
