### ISSUE TITLE
RTL Support for Bootstrap 4

### ISSUE THREAD

**Issue by peylight** [twbs/bootstrap#24662]
Hello contributors 
I heard already you will be add RTL (Right To Left) languages support to Bootstrap 4
Now it's coming to release version soon ...
But it seems there are no any RTL support feature.

There are some RTL versions of bootstrap like these:
https://github.com/morteza/bootstrap-rtl
https://github.com/parsmizban/Bootstrap-RTL
https://github.com/AbdullahDiaa/Bootstrap-RTL
....

But why we make one that official, instead of fork many and many RTL versions?
And if that will be added soon, someone can tell me when? We are many years waiting for official RTL support of bootstrap!
If you want to know how much is it important, you can check this link:
http://www.i18nguy.com/temp/rtl.html

Best Regards,
peylight

**Comment by Johann-S** [comment]
Related to : https://github.com/twbs/bootstrap/pull/23703
We plan to add this feature when we will be on stable releases

**Comment by r-shakeri** [comment]
@Johann-S 

> Related to : #23703
> We plan to add this feature when we will be on stable releases

please send us a time!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by r-shakeri** [comment]
> Related to : #23703
> We plan to add this feature when we will be on stable releases

also tell me how can i have rtl export using https://bootstrap.build/app
