### ISSUE TITLE
bootstrap.js TypeError: $ is undefined

### ISSUE THREAD

**Issue by rogerlos** [twbs/bootstrap#24667]
My web console shows the subject line error (at line 88) when using jQuery in "no conflict mode" (for example, within a WordPress plugin or theme). The fix is easy enough

```
...
}( {}, $||jQuery, Popper ));
```

In the anonymous function params. BS4 did not throw its "jQuery is required" message(s). This is using the un-minified script in Windows Firefox.

**Comment by bkdotcom** [comment]
Dupe of  #24549, #24417, #24513
