### ISSUE TITLE
Popover 'content' callback is executed twice

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#24664]
Goto https://codepen.io/alecpl/pen/GOobLM, open console and see that the function is called twice when the button is clicked. It would be nice if it was called once. But make sure it's called always when you click the button, not only on a first click (initialization). I prefer that function to do some actions on content over the 'show.bs.popover'. Also, maybe the documentation should state clearly in what order these "popover configuration callbacks" are executed.

**Comment by Johann-S** [comment]
FYI if you include `bootstrap.bundle.min.js` they are no need to include Popper.js :wink:
