### ISSUE TITLE
No rounded corners for .card-img(-*) when not first/last, better naming

### ISSUE THREAD

**Issue by ct-martin** [twbs/bootstrap#24675]
_Using v4.0.0-beta.2_

When using `.card-image-top` the image automatically has the following applied:
```
    border-top-left-radius: calc(.25rem - 1px);
    border-top-right-radius: calc(.25rem - 1px);
```
However, this makes the assumption that the image is the first item in the card. In the event it is not, such as when `.card-header` is first, it still has rounded corners, leaving a gap. This is an assumption that even `.card-header` doesn't make - `.card-header` uses `:first-child` for its rounded corners. I would propose that the same thing is applied to `.card-image-top`. The reverse affects `.card-img-bottom` when it's not at the bottom (for example a `.card-footer` below it) as well as `.card-img` when it's used for anything other than with a `.card-img-overlay`.

Additionally, I would suggest that changing to `.card-img-flush` or just `.card-img` with `:first-child` and `:last-child` selectors makes more sense (similar to `.list-group-flush`), removing `.card-img-(top|bottom)`, and renaming the current `.card-img` to `.card-img-(overlayed|hasoverlay|rounded)` so as not to break `.card-img-overlay` due to it no longer being `:last-child`, but still allowing a more canonical name.

**Comment by mdo** [comment]
`.card-image-top` _should_ be the first item in the card. That's why it's `-top`. Don't use the class if it's not the first image; just make it a child element of the `.card`.

**Comment by ct-martin** [comment]
@mdo Arguably `.card-header` should be the first item in a card as well, which was part of why I was making the point. Since there are `"first-child` and `:last-child` selectors, I see no reason why Bootstrap needs to add more classes to hardcode an easily detectable scenario that's not an edge case. You could easily just do away with both `.card-img-top` and `.card-img-bottom` and use `.card .img-fluid:(first|last)-child` instead. Then if you're generating cards from a list you don't need to handle multiple cases for which classes a card needs depending on if there was a header going above the image or not.
