### ISSUE TITLE
Dropdown - Add a better description on which element trigger the events

### ISSUE THREAD

**Issue by djryanj** [twbs/bootstrap#24672]
Hi there,

It seems as though the dropdown events (i.e. hidden.bs.dropdown. show.bs.dropdown, etc.) do not ever seem to fire. For example:

https://www.bootply.com/xVuE4LjekJ#

The alert never fires.

I suspect this is due to some namespace conflict, perhaps between popper and bootstrap. 

It also does not work if the dropdown is NOT in a nav: https://www.bootply.com/BNRritTKHC#

It's of course possible that I have a code problem, but I can't see it.

Thanks.

**Comment by Johann-S** [comment]
That's because dropdown are wrapped in a container and it's this container which will trigger the events see my CodePen with our latest release (beta 2) : 
https://codepen.io/Johann-S/pen/JOXqZZ?editors=1010

**Comment by djryanj** [comment]
Hi @Johann-S ,

Thanks for that. I have confirmed in my code that the event fires on the PARENT element; in my actual code it's more complex than just nested in a single container, so I wanted to mention that's the correct place to listen for the event.

I would request one or both of the following:

1. The documentation be updated, as it indicates that the events fire on the element itself and not its parents, or;
2. This is still a bug, at least from the perspective of how you would expect to code for this and complexity. event.target will obviously refer to the parent element, which can be useful, but generally will require a second traversal back down the tree in the code to be able to do something to the element in question (for example, disabling it): [https://codepen.io/anon/pen/JOKPGr?editors=1011](https://codepen.io/anon/pen/JOKPGr?editors=1011) This is, at the very least, inefficient.

Thanks.

**Comment by Johann-S** [comment]
It's written in our documentation here : https://getbootstrap.com/docs/4.0/components/dropdowns/#events

**Comment by djryanj** [comment]
@Johann-S : The documentation is confusing because the example and behavior is either wrong or inconsistent. 

It DOES say that it fires at the parent element, but then the example just below it uses the following code: 

`$('#myDropdown').on('show.bs.dropdown', function () {
  // do something…
})`

That appears to directly target the dropdown created in non-existent example HTML, NOT the dropdown's parent. 

With tabs [https://getbootstrap.com/docs/4.0/components/navs/#events]( https://getbootstrap.com/docs/4.0/components/navs/#events), a very similar example exists: 

`$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
  e.target // newly activated tab
  e.relatedTarget // previous active tab
})`

Which clearly targets the element that is used to activate the tab, NOT that element's parent and NOT the tab pane itself. 

Ultimately this is where my confusion stems from; I have a nav that includes both tabs and a dropdown, and the behavior is inconsistent between the two types of elements (which is fine so long as it's documented clearly).

I admit that I am barely more than a junior dev so perhaps this is obvious to more senior folks, but without a complete example (or a more consistent one to the other examples on the page, NONE of which have an element with id=myDropdown which would be selected by the example code above).

Thanks very much for the good work (and help) and for replying on a Sunday :)

**Comment by Johann-S** [comment]
I'll reopen this issue and mark as a documentation one if someone want to improve this section

**Comment by djryanj** [comment]
@Johann-S :+1: Thank you!

**Comment by RobertoMalatesta** [comment]
Hi @djryanj ,
If you include popper.js from your html page be sure to include it in its UMD version.
say, i.e.:
`<script src="/libs/popper.js-1.12.6/dist/umd/popper.js"></script>`

if you have all the dependencies into a root lib of the site.

--R

**Comment by mdo** [comment]
Haven't seen any movement here, safe to close now or is there something we can do still?
