### ISSUE TITLE
Button addons: Outline buttons are missing a border when on the left side

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#24689]
If you switch the buttons under [Button addons](https://getbootstrap.com/docs/4.0/components/input-group/#button-addons) to any outline button (e.g. `btn-outline-primary`) you'll see that the buttons on the left side are missing their right border:

Browser: Firefox/Chrome on Windows 10

![image](https://user-images.githubusercontent.com/1199486/32434654-0010821e-c2df-11e7-8f7f-b0160097dbef.png)

**Comment by mdo** [comment]
Duplicate of #24216.

**Comment by arechsteiner** [comment]
Ah sorry, my bad!
