### ISSUE TITLE
<ol class="list-group-item"> renders 0 on each <li>; occurs only in FireFox, only with bootstrap4 and only with class provided in docs

### ISSUE THREAD

**Issue by ownsourcing** [twbs/bootstrap#24688]
## unexpected behavior

The number zero appears on each list-item of ordered lists when viewed in Firefox for Mac with `class="list-group-item"` applied to the `ol` tag per ["List group" docs for v4.0](https://getbootstrap.com/docs/4.0/components/list-group/).

This behavior persists even with addition of a start attribute to the related `ol` tag (e.g. `<ol class="list-group" start="3">`).

## expected behavior

Each list-item of an ordered list should show a sequential number, starting from 1 unless otherwise specified in a start attribute on the `ol` tag.

This expected behavior appears when 
- viewing the reduced test case in Safari and Chrome for Mac, or Firefox for Windows
- removing the `class="list-group-item"` from the `ol` tag and loading the case in any of the tested browsers (including Firefox) on any of the tested platforms
- replacing v4.0 with v3.3.7.

## reduced test case

https://codepen.io/onso/pen/XzKgpB

purposes of this reduced test case: 
- confirm issue occurs only in FireFox, only with bootstrap4 and only with class provided in docs
- confirm use case works as expected in Chrome & Safari
- confirm use case works as expected with Bootstrap3 in Firefox.

## browser / os / user agent info

fails: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:49.0) Gecko/20100101 Firefox/49.0
works as expected: Firefox Versions 55.0.3 & 56.0 on Windows 10
works as expected: Safari Version 11.0 (12604.1.38.1.7) on Intel Mac OS X 10.12.6
works as expected: Chrome Versions 61.0.3163.100 & 62.0.3202.75 on Intel Mac OS X 10.12.6

--

fyi, the following steps are all completed prior to submission of this bug report:

> Before opening an issue:
> 
> - Search for duplicate or closed issues
> - Validate using html5.validator.nu
> - Lint using github.com/twbs/bootlint#in-the-browser
> - Prepare a reduced test case
> - Read the contributing guidelines

**Comment by patrickhlauke** [comment]
The latest version of stable Firefox is 56. Testing on Fx56 on Windows 10 seems to render the numbers correctly in that codepen example (even after removing your additional CSS that tries to fix things)

**Comment by ownsourcing** [comment]
agreed with @patrickhlauke - apparently didn't catch ff version mismatch where it counted!
