### ISSUE TITLE
Add bit more color weight to bg-light utility class.

### ISSUE THREAD

**Issue by Nudasoft** [twbs/bootstrap#24681]
Operating system: Windows 10 pro.
Browser: Chrome version 61.0.3163.100 (Official Build) (64-bit) 
Bootstrap version: 4.0.0-beta.2

For me it's really hard to identify the color difference of bg-white and bg-light.

<img src="https://image.prntscr.com/image/8rTTtGOHRLOzz1BZOfjRuQ.png">

<hr>

My color suggesion for bg-light class.

<img src="https://image.prntscr.com/image/8k7DSPbDQAKSzuJCSUWzsQ.png">

**Comment by andresgalante** [comment]
Hi @Nudasoft thanks for bringing this up. At the moment `bg-light` is defined by `gray-100: #f8f9fa` here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L13

I see what you mean, `bg-light` when used on a white background is too light. 

For your implementation maybe you can use a different shade of gray fro the gray color variables.

`#f9f9f9` and `#f8f9fa` are *almost* the same color, I don't think the difference is enough to make a change on the codebase

**Comment by Borkason** [comment]
Hm, I agree that the [contrast between both colors](http://leaverou.github.io/contrast-ratio/#%23f8f9fa-on-white) is extremely low. However, the border adds enough contrast that I personally can clearly distinguish both colors. At least on my calibrated display. I assume that the contrast possibly gets worse (or even better) on cheap display or notebook displays. But I would argue that the reference should be a calibrated monitors. Just my 2 cents.

**Comment by mdo** [comment]
Closing as stale—darn near impossible to get colors seen reliably across monitors.
