### ISSUE TITLE
Wrong border radius top right on btn-group-vertical

### ISSUE THREAD

**Issue by ezetojo** [twbs/bootstrap#24693]
https://codepen.io/ezetojo/pen/VrjqqW

btn-group-vertical first child must have border-top-right border radius 4px

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
