### ISSUE TITLE
justify-content-end goes out of container in IE11

### ISSUE THREAD

**Issue by jvanderkroon** [twbs/bootstrap#24702]
On Windows10 in IE11 the content goes to the next col when justify-content-end is used

I made a demo https://codepen.io/jvanderkroon/pen/pdEewx
The first example shows the problem. The button goes out of the col-8 and is not clickable

In the second example the button shows in the correct col-8 and is clickable

**Comment by Johann-S** [comment]
Please can you update your Codepen using our latest release ? https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.min.css

**Comment by jvanderkroon** [comment]
The Codepen example is updated with beta2 css.

**Comment by mdo** [comment]
This is a IE10 and IE11 bug: https://stackoverflow.com/questions/37534254/flex-auto-margin-not-working-in-ie10-11/37535548#37535548. You're using competing methods of alignment with the auto margins and the `justify-content` utility. Choose one or the other, but not both.
