### ISSUE TITLE
V4 beta 2 / thead-dark change

### ISSUE THREAD

**Issue by hebeldark** [twbs/bootstrap#24703]
Hi

i'm download css and js files about v4 beta 2.

i rename thead-inverse to thead-dark in my files

but sometimes, i have the header of my table black, sometimes no

i don't understand why i have this difference ?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by hebeldark** [comment]
so this is a part of my page
i'm using at first a simple table => the dark theme on header is OK

but in tab panel, the header attribute doesn't show dark header

[link to sample](https://codepen.io/HEBELDARK/pen/wPzmjW)

in my another code, i build html code with data from AJAX, and i add this code in DIV

same result. but i can't to past the ajax code

**Comment by miguelcaravantes** [comment]
![image](https://user-images.githubusercontent.com/17279582/32508181-be40e02c-c3a6-11e7-89a7-db264c60299e.png)
In second table table dont contains .table class

fix adding .table class

**Comment by hebeldark** [comment]
ok now, i must to add table attribut in class

i try on my original code and it's working

thx
