### ISSUE TITLE
Justified text with ideography adds corrupted letter in iOS (v4)

### ISSUE THREAD

**Issue by konn** [twbs/bootstrap#24719]
`text-justify` class or `text-align: justify` with ideographic letters causes letter corruption in some environment, at least in iOS Safari.

For example, consider the following:

```html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="ja" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="ja" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="ja" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="ja" class="no-js"> <!--<![endif]-->
<!--[if !IE]><html lang="ja"><![endif]-->
<head>
  <meta charset="utf-8">
  <title>あああああ</title>
  <meta name="viewport" content="width=device-width">
  <link href="./css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
    <div class="text-justify">
<p>ああああああああ（<em>something long words</em>）ああ．ああああああああ</p>
    </div>
  <script src="/js/bootstrap.min.js"></script>
</body>
</html>
```

This results in, on iPhone (iOS 11.1), the following:

![img_3380](https://user-images.githubusercontent.com/21860/32548151-076c0fa2-c4c8-11e7-9cbb-21245fd71b15.png)

Note that there is a corrupted letter, which looks like `[X]`, just above the closed parens.
Similar occurs in iOS.

I use Bootstrap v4-beta.2.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by konn** [comment]
Oh, Sorry. I thought that it included reduced tests and environment information, but it seems that it didn't match your official definitions.

OK, here's [reduced test](https://jsbin.com/rohacaj/2/edit?html,output).

A bit detailed environment information:

* Bootstrap v4.0.0-beta.2
* Safari on iOS 11.1 (15B93), iPhone 7, Japanese locale.

**Comment by mdo** [comment]
I don't think this is exactly a Bootstrap issue—this seems like a browser/OS issue with how it's rendering a character in a particular font. We could look into changing the fonts, but that doesn't seem likely given this is the first report of a problem we've seen. Closing as a won't fix for now.
