### ISSUE TITLE
toggle doesn't

### ISSUE THREAD

**Issue by jtara** [twbs/bootstrap#24714]
dropdown "toggle" doesn't toggle.

This seems by design... so I guess the issue is with the terminology.

`$().dropdown('toggle')` OPENS the dropdown.

Given that, why isn't it called something with clear semantic meaning - like "open"?

And there isn't any API call to CLOSE the dropdown!

There isn't any API call to toggle the dropdown.

I would think that having both open and close would be essential.

Not sure what the thinking was here...

Indeed, clicking on the opening button gives the appearance of toggling - but only because clicking anywhere outside of the menu will close it. 

The issue here, though, is with the API call.

To close programatically, apparently the only way to to remove the `show` class on the dropdown menu.

**Comment by mdo** [comment]
Yeah, we have three clear methods and a few specific events for the dropdown: https://getbootstrap.com/docs/4.0/components/dropdowns/#methods. Programmatically, you can call `show.bs.dropdown` and `hide.bs.dropdown` as needed to manually toggle dropdowns via JS.

**Comment by jtara** [comment]
^ Call, or trigger? Documentation needs to be clearer. I assume it is trigger. It is not obvious that triggering those events would do anything. I would assume they are for for notification of user code.

I guess "toggle" is a historical usage? This is NOT a toggle. Again, the documentation should clarify that "toggle" OPENS the dropdown. It does not toggle it. (Toggle would close if already open.)

**Comment by Johann-S** [comment]
Related to #22835
