### ISSUE TITLE
BS4: mixin make-row does not accept args anymore

### ISSUE THREAD

**Issue by nicmare** [twbs/bootstrap#24724]
in BS4 Alpha it was possible to pass an sass map to the make-row mixin like:
@include make-row($grid-gutter-widths_thin);
i've noticed in BS4 Beta this is not possible anymore. Why? Can't find an answer for it.

**Comment by mdo** [comment]
We dropped the grid gutters awhile ago in #22940. There’s an issue to bring them back eventually at #22944.
