### ISSUE TITLE
Theming Bootstrap file structure documentation

### ISSUE THREAD

**Issue by NYCJacob** [twbs/bootstrap#24728]
It seems to me there is an error in explaining the file structure for customizing bootstrap as explained in this link (https://getbootstrap.com/docs/4.0/getting-started/theming/#file-structure)
- In the section Sass - File Structure
--  it states, Assuming you’ve downloaded our source files or are using a package manager, you’ll have a file structure that looks like this:
your-project/
├── scss
│   └── custom.scss
└── node_modules/
    └── bootstrap
        ├── js
        └── scss
-- this is not what I have from the repo here nor from the source files download
-- I see two errors 
1- there is no file custom.scss
2- if you download the source files they are not located in node_modules.  They would be if using npm but this seems to combine the two methods

-- I would be happy to work on this if it is deemed needed.

**Comment by andresgalante** [comment]
Hi @NYCJacob

Assuming you’ve are using a package manager you would get a `node_modules/` folder, and the custom.scss file is something that belongs to your project, you wouldn't get it from installing bootstrap.

If you read the whole paragraph and the next one I think it's explicit of that idea, but if you have a suggestion to reword it better, make please send a PR so we can review a more concrete proposal.

Thanks!
