### ISSUE TITLE
Possible false positive on XSS from Retire.js for v4.x

### ISSUE THREAD

**Issue by arc95** [twbs/bootstrap#24729]
Hi. Ran [Retire.js](https://github.com/retirejs/retire.js/) on my app to check for vulnerable JS libraries. The app had TWBS 3.3.7 and the tool produced the following in its report:

`â†³ bootstrap 3.3.7 has known vulnerabilities: severity: medium; issue: 20184, summary: XSS in data-target attribute; https://github.com/twbs/bootstrap/issues/20184`

So upgraded to latest 4 beta and ran the tool again:

`â†³ bootstrap 4.0.0-beta.2 has known vulnerabilities: severity: medium; issue: 20184, summary: XSS in data-target attribute; https://github.com/twbs/bootstrap/issues/20184`

Is this a false positive? [This issue](https://github.com/twbs/bootstrap/issues/20184) indicates the problem has been fixed in 4.

**Comment by Johann-S** [comment]
Yep it's a false positive we fixed that in our beta 2 see : #23679
