### ISSUE TITLE
Remove flex class utilities from bootstrap-grid.scss if $enable-grid-classes is false

### ISSUE THREAD

**Issue by david-treblig** [twbs/bootstrap#24727]
It seems that bootstrap-grid.scss generates many useless classes for flex utilities because it is directly included : https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap-grid.scss#L35, https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_flex.scss

It should look for $enable-grid-classes and, if false, not generate the flex utility classes because right now we get those uselessly thrown in even when they're not needed.

Or there could be another variable $enable-flex-utility-classes if you feel it's more appropriate.

**Comment by mdo** [comment]
Flex utilities are fairly necessary for any grid customization or sufficiently complex layouts (even simple ones, tbh). We have discussed an additional flag for each group of utilities, though. I don't think the grid classes var should toggle flex classes though.

**Comment by david-treblig** [comment]
They're usefull, but there should be an option to disable them otherwise there are many classes added for nothing if you don't use them. I definitely agree that it could be a different toggle.

To my point: many people use the bootstrap-grid only and use the breakpoint mixins to build styles from scratch by using bootstrap as a responsive framework, basically. Those classes end up being useless and clutter up the output CSS file.

**Comment by moso** [comment]
There's also a problem within Sass, where you, afaik, can't have conditional imports.

Example:
```
$enable-flex: true;

if($enable-flex) {
    @import 'utilities/flex'
}
```

This will result in an error, at least in its current state.
However, you can do it with `@mixins`, so you can `@include` something conditionally.

**Comment by mdo** [comment]
Going to punt on this for now. The flex utilities are quite essential and so far this is the only issue I've heard regarding these classes in the grid bundle.

**Comment by vinkla** [comment]
Sorry for commenting on an closed issue. I think this feature would come in handy since it will make the file sizes smaller if you don't use the flex helpers.

@mdo would it be okay to send a pull request for this?
