### ISSUE TITLE
Show hanburger icon only in responsive area

### ISSUE THREAD

**Issue by nanny90** [twbs/bootstrap#24736]
Hello,
I have the problem that my hamburger-icon is always there.
I want only to show it in the responsive areas.
I tried to copy from other sites but it doesnt work.
can someone help me?

`<div class="header-nav clearfix">
               <nav class="navbar navbar-fixed-top">
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="navbar-collapse collapse " id="navbarSupportedContent">
                     <ul class="nav">
                        <li class="nav-item">
                           <a class="nav-link" href="#">Über uns</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="#">Karriere</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="#">Downloads</a>
                        </li>
                        <li class="nav-item nav-item-gruen">
                           <a class="nav-link" href="#">Kontaktieren Sie uns!</a>
                        </li>
                     </ul>
                  </div>
               </nav>
            </div>`

**Comment by patrickhlauke** [comment]
for help/how-to type questions, please use stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
