### ISSUE TITLE
Input group loses border-radius

### ISSUE THREAD

**Issue by sream** [twbs/bootstrap#24738]
Input group loses border-radius if input with type hidden is inside. Example:
	
```
<div class="input-group">
		
	<input type="hidden" name="_token" value="{!! csrf_token() !!}">

</div>
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by alecpl** [comment]
Hidden elements are not supported. .input-group uses :first-child/:last-child selectors to style border radius, and that's why it does not work. If I'm correct.

**Comment by mdo** [comment]
What @alecpl said.
