### ISSUE TITLE
Disabled Outline Button With Icon Still Shows Click Effect

### ISSUE THREAD

**Issue by Rabadash8820** [twbs/bootstrap#24741]
Normally, mousing over a `btn-outline-*` button makes the background turn some color, e.g., red for `btn-outline-danger`.  However, this behavior does not go away when clicking a disabled button.  Here is a [CodePen](https://codepen.io/Rabadash8820/pen/POpOdL) showing the behavior.  This strikes me as unintentional, especially with the differences between browsers described below, but I could be wrong.

Reproduced on my machine running Windows 10 Pro in these browsers:
- **IE 11**
- **Edge 40.15063.674.0**
- **Google Chrome 62.0.3202.89** (curiously, the disabled button only changes color in Chrome when I click directly on the *icon*)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Rabadash8820** [comment]
@Johann-S I have cleaned up the original description to remove some unnecessary info and provide a CodePen link.

**Comment by patrickhlauke** [comment]
this should be fixed by https://github.com/twbs/bootstrap/pull/23544

**Comment by patrickhlauke** [comment]
confirmed, fixed in beta 2. see https://codepen.io/team/Bootstrap/pen/ooWXKY

**Comment by Rabadash8820** [comment]
damn, I hate to be that guy that makes duplicate bugs. 😛
