### ISSUE TITLE
Allow `.is-invalid` class to override `:valid` pseudo-class

### ISSUE THREAD

**Issue by nwoltman** [twbs/bootstrap#24743]
I'm mostly using HTML5 validation, but sometimes part of a form has to use custom validation. The problem is that if a form has the `was-validated` class and an input has the `is-invalid` class, but HTML5 says the input is valid, it has the green border to indicate it is valid.

![invalid-boostrap](https://user-images.githubusercontent.com/5128013/32634018-ca7972c8-c577-11e7-8237-1d8ae639b889.PNG)
[See this JS Bin example](http://jsbin.com/quseyeseze/1/edit?html,output)

It would be nice if `is-invalid` would work regardless of the HTML5 validity state.

This could be fixed by adding:

```scss
.was-validated &.is-#{$state},
```

after [this line](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_forms.scss#L55).

Would a PR with this fix be accepted?

**Comment by mdo** [comment]
Validation _classes_ and validation _pseudo-classes_ are not meant to be mixed like this.

> work regardless of the HTML5 validity state.

Disable the required validation of the input or the form.

**Comment by IonicaBizau** [comment]
I have the same use-case like @nwoltman... This would be handy to be implemented.

**Comment by IonicaBizau** [comment]
@mdo By removing the `required` attribute, the field will be `:valid`, hence it still cannot be made red using `is-invalid`. Opened #24847.
