### ISSUE TITLE
Navs - activate hidden tab

### ISSUE THREAD

**Issue by ArmRes** [twbs/bootstrap#24755]
In bootstrap 4 alpha 6 this code work (activate tab3, but only once)
In bootstrap beta 2 don't work, even once.

```html
<div>
  <ul class="nav nav-tabs align-items-center">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" data-target="#tab1" href="">Tab 1</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" data-target="#tab2" href="">Tab 2</a>
    </li>       
  </ul>
</div>
<div class="tab-content">
  <div id="tab1" class="tab-pane fade show active">
    Tab 1 <a data-toggle="tab" data-target="#tab3" href="">Activate tab 3</a>
  </div>
  <div id="tab2" class="tab-pane fade">
    Tab 2
  </div>
  <div id="tab3" class="tab-pane fade">
    Tab 3
  </div>
</div>
```

It is necessary to be able to switch the panel from other panels, but at the same time in tab navs it was not

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by armres** [comment]
OS: Windows; Browser: FireFox & Chrome

Action steps: 
1) Click "Activate Tab 3"
2) Click "Tab 2"
3) Click "Tab 1"
4) Click "Activate Tab 3"

Bootstrap-4 alpha-6: https://codepen.io/armres/pen/ooWRrb (Step 4 - don't work, tab 3 in step 4 don't show)
Bootstrap-4 beta-1: https://codepen.io/armres/pen/qVjdvE (After step 1, tab 3 don't hide)
Bootstrap-4 beta-2: https://codepen.io/armres/pen/NwjVMw (Step 1 - don't work, tab 3 - don't show)

**Comment by ArmRes** [comment]
@Johann-S

**Comment by wolfy1339** [comment]
What version of Windows

**Comment by ArmRes** [comment]
@wolfy1339 updated post

**Comment by wolfy1339** [comment]
We also need browser version.

**Comment by ArmRes** [comment]
@wolfy1339 update post

**Comment by ArmRes** [comment]
@Johann-S 
Anyone

**Comment by XhmikosR** [comment]
Is this still an issue?

**Comment by Johann-S** [comment]
seems a bug in v4.1.3 too: https://codepen.io/Johann-S/pen/JmrYNQ

**Comment by XhmikosR** [comment]
I think this markup isn't supported by our plugin. Not sure if there's something we can do.

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
