### ISSUE TITLE
[v4-beta] Modules structure

### ISSUE THREAD

**Issue by Andarist** [twbs/bootstrap#24750]
From what I understand what you publish in terms of js are such directories:
- src
- dist

`src` ofc hold your source files which contain es6+ syntax - most people ignore their `node_modules` during transpilation.

`dist` holds files which assume **global context**

This makes it hard to use with webpack and such, I'd like to load just a plugin or two, ideally pretranspiled, and use it right away.

Can't use `src` because its untranspiled, I cannot ship like that to production and also it won't let uglify js to minimize the file.

Can't use `dist` because webpack wraps each module in a closure (reasonably) and inter-plugin dependencies are shared through assumed globals.

Im wondering if this situation is a choice of yours or that is thing that could be fixed. I'm open to help out and provide a PR, we'd only need to establish what kind of files you want to publish to npm. Ideally: transpiled es modules, transpiled cjs modules and umd (rolluped?) bundles.

**Comment by Johann-S** [comment]
You can use `js/dist/*.js` files which are transpiled :wink: 
but yep we want to improve our module structure

**Comment by Andarist** [comment]
Ok, docs are helpful here, sorry for not checking thoroughly it before, I just went straight into the source code 😅 

Ideally such using special webpack's plugins wouldnt be required to make it work though.

**Comment by Johann-S** [comment]
that's right, we are open for PR to improve our documentation :+1:

**Comment by Andarist** [comment]
Well, improving the docs won't help. You'd need to ship more output formats so they could be used directly in the code without having to tweak webpack's setup - I'm willing to work on this, if we establish what formats you'd like to ship

**Comment by Johann-S** [comment]
An UMD release of Bootstrap would be nice :+1: 
To produce ES module it will be difficult because we depend on jQuery and jQuery do not provide ES module :worried:

**Comment by Andarist** [comment]
> To produce ES module it will be difficult because we depend on jQuery and jQuery do not provide ES module

This one can be treated as global. If one is using jQuery he/she already needs to setup it correctly. But at least bootstrap's modules would be imported between each other correctly.

**Comment by Johann-S** [comment]
If you want to work on a UMD release of Bootstrap and ES modules that's ok to me :+1:

**Comment by Johann-S** [comment]
Since our beta 3 our `bootstrap.js` is totally compatible with UMD but not each of our modules

**Comment by Johann-S** [comment]
Since `v4.1.3` our plugins are built in UMD too
