### ISSUE TITLE
Nested card in card groups are displayed wrong

### ISSUE THREAD

**Issue by jhhazelaar** [twbs/bootstrap#24752]
I have a card-group with nested cards in de card-body of the grouped. This nested card act like they are grouped. Nested card doesn't have a left border or no rounded corner just like the grouped cards.

Maybe adding some `>` to de card scss. I didn't have the time to figure out the solutions, sorry for that.

**Comment by jhhazelaar** [comment]
I don't think this is the best way. But for now it's a solution:
```
.card-group {
  .card {
    @include media-breakpoint-up(sm) {
      .card {
        border: $card-border-width solid $card-border-color;
        @include border-radius($card-border-radius);

        &:not(:first-child):not(:last-child):not(:only-child) {
          @include border-radius($card-border-radius);
        }
      }
    }
  }
}
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by jhhazelaar** [comment]
Sorry, here it is: https://codepen.io/jhhazelaar/pen/LOWWKw

**Comment by Johann-S** [comment]
Can you update your CodePen to our latest release please ? 
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.min.css

**Comment by jhhazelaar** [comment]
Still the same issue. Sorry for the incompetence, first time creating an issue

**Comment by Johann-S** [comment]
don't worry that's ok :+1:

**Comment by gijsbotje** [comment]
maybe using `.card-group > .card` everywhere would be a good solution
@Johann-S what'd you think?

**Comment by Johann-S** [comment]
It's seems we try to avoid child selector in Bootstrap 🤔 
maybe @andresgalante have ideas on how to fix that ?

**Comment by andresgalante** [comment]
Thanks a lot @jhhazelaar for reporting this one.

Hi @Johann-S to me this is a really good case for a child selector, since we want to select just `.card` child and nothing else.

The other option is to undo the styles for card-group card on nested cards which will add way more specificity and styles. I've send a PR so we can discuss in more concrete ideas
