### ISSUE TITLE
Blue background on custom checkbox

### ISSUE THREAD

**Issue by SamThilmany** [twbs/bootstrap#24756]
There is a blue background on custom checkboxes in BS4 while clicking. 
I checkeg the `:active` and the `:focus` states, but could not find anything...
If setting a background color to the `:active` or `:focus` state of the `custom-control-indicator` it is simply not displayed. However, in the web console, the color is not crossed out...

See here: https://codepen.io/SamThilmany/pen/jaBxmy

**Comment by mdo** [comment]
This is by design.

**Comment by SamThilmany** [comment]
Yeah, but how could it be removed? It looks awful. :disappointed:

**Comment by SamThilmany** [comment]
@mdo I would be really grateful if you could help me (and all the other users of BS 4) with fixing this. It really isn't a great design. And it gets even worse if you use FontAwesome icons in the `:after` pseudo class as symbol because the blue square does not match the symbol at all...

**Comment by patrickhlauke** [comment]
it's by design, so if you want to not use it and are looking for a way to suppress it, i'd suggest asking on StackOverflow or similar? https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
