### ISSUE TITLE
Inputs padding problem

### ISSUE THREAD

**Issue by 3mmarg97** [twbs/bootstrap#24758]
Hello. I'm customizing bootstrap using sass variables for my project. I'v noticed that If I change $input-btn-padding-y or $input-btn-padding-x this will be effective on both (buttons and inputs). Because you are using these variables with .btn class inside _buttons.scss file and .form-control class inside _forms.scss. Why not to create something like this:
```sass
$btn-input-padding-x = $input-padding-x !default;
$btn-input-padding-y = $input-padding-y !default;
```

So with the previous code the default situation that there's the same padding for the inputs and the buttons. But also I can customize buttons only.

I hope that you will add this feature. Thanks!

**Comment by andresgalante** [comment]
Hi @3mmarg97! Thanks for reporting this issue. 

You are right, it is a problem and it has been fixed here: https://github.com/twbs/bootstrap/commit/58e553d7bcdd440cafa13a4a9b97cc293dbfcb04

You can change them both with `$btn-input-padding-x` or customize them individually with either `$btn-padding-x` or `$input-padding-x`.

It will be available on the next release.
