### ISSUE TITLE
d-flex justify-content-between not centered

### ISSUE THREAD

**Issue by imabot2** [twbs/bootstrap#24764]
I used d-flex justify-content-between to get content centered as [in this example](https://getbootstrap.com/docs/4.0/utilities/flex/#justify-content) 
Unfortunatly it's malfunctioning, see the jsfiddle here : https://jsfiddle.net/wga9rfhh/1/

**Comment by artemsky** [comment]
It shouldn't, because block has different width in your example,
In case you add some size , it will work as expected - https://jsfiddle.net/wga9rfhh/2/

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

**Comment by mdo** [comment]
`justify-content: between` only sets the spacing _between_ the elements to be equal; it cannot optically center the middle element with the parent.

**Comment by hungcung2409** [comment]
> `justify-content: between` only sets the spacing _between_ the elements to be equal; it cannot optically center the middle element with the parent.

Do you have any workarounds?
