### ISSUE TITLE
New style for the tables

### ISSUE THREAD

**Issue by slyk-style** [twbs/bootstrap#24765]
Do you think it would be possible to take a look at the tables. I know it seams responsive but i think it would be more ideal to implement a new type of table where you dont need to swipe right to see more because each row simply floats and becomes a new section where there is a header next to it. See below for examples. I think it would be a really cool feature to have. Im sure many agree. That way you don't need to swipe right. Its all right there. Its easy to use and read and then becomes truly responsive. If you are already working on something then please tell me haha. This would be one of my new favourite features.

https://codepen.io/team/css-tricks/pen/KzWORB
https://css-tricks.com/responsive-data-table-roundup/
https://codepen.io/team/css-tricks/pen/PNpMaj
http://www.irishstu.com/stublog/wp-content/uploads/2011/12/table-childs.html

**Comment by patrickhlauke** [comment]
accessibility is always slightly problematic for those "morphs from one thing to another" approaches. worth looking at this http://blog.adrianroselli.com/2017/11/a-responsive-accessible-table.html though as a starting point, if we decide to go for it.

**Comment by slyk-style** [comment]
Definitely agree with all points. Many will still want it, but its worth looking towards a flexible approach option. Love the link btw. Although i doubt it would be high resource use to let javascript process, might be important to note the resource use. I might try to test its speed. Potentially even give a go for an integration with the current BS4 version on my project so that as you said both scenarios can work and it follows the same structure. As you would already know that some classes cross over and it shouldn't happen on things that such as fonts.   If i get something going ill list the code and working table unless someone else has already had a crack at integrating.

**Comment by mdo** [comment]
Going to say we'll pass on more table features for now. Thanks though!
