### ISSUE TITLE
Mobile menu navbar-toggle button does not work

### ISSUE THREAD

**Issue by conciousweb** [twbs/bootstrap#24761]
Clicking the 'hamburger' icon or 'navbar-toggle' does nothing in mobile or any in any browser with mobile window width. No errors are output to console either.

twbs:bootstrap - 3.3.6

**Comment by patrickhlauke** [comment]
as they work fine on https://getbootstrap.com/docs/3.3/ i'd suspect it's something to do with your code. suggest asking on stackoverflow or similar. https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
