### ISSUE TITLE
Override bg-variables ?

### ISSUE THREAD

**Issue by CalibanAngel** [twbs/bootstrap#24779]
Hello,

How can we override the bg-variables to create our own theme ? Because i don't find them in _variables.scss

Thanks !

**Comment by andresgalante** [comment]
Hi @CalibanAngel You'd want to edit the theme variables here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L65-L72

I'll change all your colors across all components. And you can add more colors by adding another value on this map:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L74-L85

I hope this helps 😄
