### ISSUE TITLE
jQueryUI DatePicker Misaligned on BS Modal in IE11/Edge when Background is Scrolled (new in Beta2)

### ISSUE THREAD

**Issue by claytonrumley** [twbs/bootstrap#24773]
We are using Windows workstations. This issue affects Internet Explorer 11 and Microsoft Edge.

The problem is that when you pop up a modal containing a jQueryUI DatePicker and the background is scrolled, the datepicker is displayed offset vertically by the amount of the vertical scroll of the page.

In Beta-1 this problem only existed in Internet Explorer 11. After Beta-2 came out the problem now occurs in Microsoft Edge as well. FireFox and Chrome appear to be functioning properly in both versions. The version of jQuery UI we're using (1.12.1) remained the same between the two versions of BS4.

Here is a pen illustrating the issue: [https://codepen.io/anon/pen/dZzpwj](https://codepen.io/anon/pen/dZzpwj)

The button at the top will show the desired behaviour (as you won't have scrolled the page yet), and the button at the button will show the undesired behaviour. You may have to adjust your browser size in order to get a vertical scrollbar to appear.

Please let me know if you require any further clarification.

Thank you for your time,

Clayton

**Comment by patrickhlauke** [comment]
i'd suggest the issue here is with jQuery UI, not Bootstrap. worth posting the issue there?

**Comment by claytonrumley** [comment]
Well as I mentioned, the only thing that changed for us was the version of Bootstrap, not jQueryUI, which implied that something in Bootstrap related to IE/Edge positioning had changed.

Thus is made sense to post here first.

**Comment by Johann-S** [comment]
It's possible they are something changed in Bootstrap related to IE/Edge but that's not us which do the positionning of jQueryUI so that's not on our end

**Comment by JihedHalimi** [comment]
@claytonrumley Thank you for reporting this problem. We do have the same issue and the positioning of the datepicker is simply a call to the jquery offset method:
position = $( obj ).offset();

**Comment by florianlacreuse** [comment]
@claytonrumley @JihedHalimi I may have a mixed good / bad new for you. I had an issue about JQuery UI datepicker widget too and I found something on JQuery UI side which looks like a bug to me.

See my bug report on JQuery UI: https://bugs.jqueryui.com/ticket/15316

On Chrome / Firefox, input height is `38px`, on Edge input height is `37.84px`. As explained in the ticket, JQuery UI fail to take into account scroll height when input height is a demical number...

I confirm this is not a Bootstrap issue.
