### ISSUE TITLE
.d-(sm, md, lg, xl)-* utilities Not Working.

### ISSUE THREAD

**Issue by bbearche** [twbs/bootstrap#24772]
I believe the issue is here under where they are defined.
`@media (min-width: 576px) {
  .d-sm-none {
    display: none !important; }
}`

It should be max-width not min width. It's only loading the classes when they arent needed and doesnt load them when they are.

**Comment by bbearche** [comment]
Here's a Patch I applied to my own code.

@media (max-width: 576px) {
    .d-sm-none {
        display: none !important;
    }

    .d-sm-inline {
        display: inline !important;
    }

    .d-sm-inline-block {
        display: inline-block !important;
    }

    .d-sm-block {
        display: block !important;
    }

    .d-sm-table {
        display: table !important;
    }

    .d-sm-table-row {
        display: table-row !important;
    }

    .d-sm-table-cell {
        display: table-cell !important;
    }

    .d-sm-flex {
        display: flex !important;
    }

    .d-sm-inline-flex {
        display: inline-flex !important;
    }
}

@media (min-width: 576px) and (max-width: 992px) {
    .d-md-none {
        display: none !important;
    }

    .d-md-inline {
        display: inline !important;
    }

    .d-md-inline-block {
        display: inline-block !important;
    }

    .d-md-block {
        display: block !important;
    }

    .d-md-table {
        display: table !important;
    }

    .d-md-table-row {
        display: table-row !important;
    }

    .d-md-table-cell {
        display: table-cell !important;
    }

    .d-md-flex {
        display: flex !important;
    }

    .d-md-inline-flex {
        display: inline-flex !important;
    }
}

@media (min-width: 992px) and (max-width: 1200px) {
    .d-lg-none {
        display: none !important;
    }

    .d-lg-inline {
        display: inline !important;
    }

    .d-lg-inline-block {
        display: inline-block !important;
    }

    .d-lg-block {
        display: block !important;
    }

    .d-lg-table {
        display: table !important;
    }

    .d-lg-table-row {
        display: table-row !important;
    }

    .d-lg-table-cell {
        display: table-cell !important;
    }

    .d-lg-flex {
        display: flex !important;
    }

    .d-lg-inline-flex {
        display: inline-flex !important;
    }
}

@media (min-width: 1200px) {
    .d-xl-none {
        display: none !important;
    }

    .d-xl-inline {
        display: inline !important;
    }

    .d-xl-inline-block {
        display: inline-block !important;
    }

    .d-xl-block {
        display: block !important;
    }

    .d-xl-table {
        display: table !important;
    }

    .d-xl-table-row {
        display: table-row !important;
    }

    .d-xl-table-cell {
        display: table-cell !important;
    }

    .d-xl-flex {
        display: flex !important;
    }

    .d-xl-inline-flex {
        display: inline-flex !important;
    }
}

**Comment by mdo** [comment]
The current classes are correct—we only use `min-width` for the utilities to keep things a bit simpler.

**Comment by bbearche** [comment]
@mdo So what do i do if my screen size for small is less than 576px? It wont load the class then.

**Comment by mdo** [comment]
I don’t understand your question. If you need to do something like hide an element to start, show it for one breakpoint, and then hide it for the remaining, you’d need something like this.

```html
<div class=“d-none d-sm-flex d-md-none”>...</>
```
