### ISSUE TITLE
Grid Overrides

### ISSUE THREAD

**Issue by tateman74** [twbs/bootstrap#24786]
Hey Mark/Jacob, et al,

I'm having a tiny issue and was wondering if you guys could suggest any weaponry for my situation.  I'd like to make everything from the medium breakpoint and lower (768 obviously) be 100% fluid.  The barrier to doing that is the small container max width at 720 and the grid gutter width.

In my variables override file (which runs before the bootstrap one), I'm just doing this which is lame:

`$container-max-widths: (
	sm: 719px,
	md: 720px,
	lg: 960px,
	xl: 1140px
);`

And even then, the 15px side padding remains and I have to override that OUTSIDE of a variables file as make_container has no concept of breakpoints.

Would you guys suggest a better way?  Or, is there something I'm missing to easily be able to make 767 and below stretch without gutters?

Thanks,
Steven Tate

**Comment by mdo** [comment]
Sorry, I missed this as a general how-to.

Without going too far into it, you can override the breakpoints and max-widths here by setting those values to `100%`. Recompiling with that should give you effect you want, but for more hands on how-to help, I'd suggest our Slack or StackOverflow.
