### ISSUE TITLE
[Bootstrap 4.0.0-beta.2] Dropdown's don't work

### ISSUE THREAD

**Issue by scorpion35** [twbs/bootstrap#24782]
Hello,

I am using Angular 5 and Bootstrap 4.0.0-beta.2 and think I found a bug with Dropdowns in this bootstrap version. Dropdown buttons are not working on this version. If I use 4.0.0-alpha.6, they work fine. 

**Not working:** 
CDN: `<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">`
Code: https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropdowns

**Working:** 
CDN: `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">`
Code: https://v4-alpha.getbootstrap.com/components/dropdowns/#single-button-dropdowns

My custom Angular 5 Directive: 
I have added my custom directive to add "show" class and change "aria-expanded" to true. 
```
@Directive({
  selector: '[appDropdown]'
})
export class DropdownDirective {
  @Input() show = "show";
  @HostBinding('class.show') isOpen = false;

  @HostListener('click') toggleOpen() {
    this.isOpen = !this.isOpen;
    this.elementRef.nativeElement.querySelector('.dropdown-toggle').attributes['aria-expanded'].nodeValue = this.isOpen;
  }

  constructor(private elementRef: ElementRef) { }

}
```

The code for dropdowns and directive is same in both alpha and beta version, but the dropdown doesn't open in Beta version.

[Bootstrap 4 Beta - dropdowns don't work in Angular 5.docx](https://github.com/twbs/bootstrap/files/1474501/Bootstrap.4.Beta.-.dropdowns.don.t.work.in.Angular.5.docx)

**Comment by Johann-S** [comment]
Dropdown depends on Popper.js as it written in our documentation see : https://getbootstrap.com/docs/4.0/components/dropdowns/#overview

**Comment by scorpion35** [comment]
Thanks for the reply, Johann-S! Yea it's working if I include script links - https://getbootstrap.com/docs/4.0/getting-started/introduction/#js. 

I was trying to get it work purely from Angular 5, which may not be possible because as you pointed out dropdowns depend on 3rd party Popper.js. Or do you know of anyway to get it working from Angular 5? 

Thanks again for your help!!

**Comment by Johann-S** [comment]
Nope sorry currently it's the only way to make it worked as expected
