### ISSUE TITLE
Annoying popper warning when you're using the bundle

### ISSUE THREAD

**Issue by dushkostanoeski** [twbs/bootstrap#24781]
I'm making an Angular app with Webpack. I am using `boostrap.bundle.min.js` which already has `popper` and because of that I removed the popper dependency. I know this isn't that big of an issue but when another developer tries to rebuild my app, the first thing they say is always `you're missing a dependency`. I'm guessing that this would create a bit of confusion for everyone using the bundle instead of both packages. Is there a plan to ship a second bootstrap package without the `popper` dependency, but only with the `bundle` script?

**Comment by Johann-S** [comment]
Sorry but we cannot do that because we need Popper.js as peerDeps for user who want to use the latest release of Popper.js instead of the one bundled in `bootstrap.bundle.min.js`

**Comment by FezVrasta** [comment]
I don't think the whole idea of the bundle is that good actually... You guys should just fix your package to properly work with commonjs

**Comment by Johann-S** [comment]
It's an easy way for users which do not use bundlers (webpack, rollup ...) but we are open for PRs to fix that :smile:

**Comment by dushkostanoeski** [comment]
I know @Johann-S, that's why I suggested a separate package. There would be two packages:

- package with the peerDep  and without the bundled popper script for users that use the latest popper
- package without the peerDep and with the budled popper script for users that don't need popper anywhere else in their project.

I'll look into this and try to make a PR next week.

**Comment by FezVrasta** [comment]
@Johann-S the problem is that the `bundle` thing is being used mostly by people that **do use** bundlers, because Bootstrap right now doesn't work properly with them otherwise.

**Comment by Johann-S** [comment]
I don't think that's true, we have a documentation which explain exactly how to work with Bootstrap using Webpack

**Comment by FezVrasta** [comment]
All the steps described in your documentation shouldn't be needed if Bootstrap worked properly tho.

**Comment by Johann-S** [comment]
It's just two steps :smile: but anyway if someone want to improve that it's open :+1:

**Comment by Johann-S** [comment]
To answer @dushkostanoeski , I don't think we will ship two packages as you described it, I prefer @FezVrasta solution

**Comment by FezVrasta** [comment]
https://github.com/twbs/bootstrap/pull/24783

**Comment by Johann-S** [comment]
Closed thanks to @FezVrasta PR :+1:

**Comment by elipeters** [comment]
Seems to be a common problem with Popper undefined in Bootstrap Bundle - using Node with Sails
