### ISSUE TITLE
Missing 'cursor:pointer' on .btn class

### ISSUE THREAD

**Issue by artefacus** [twbs/bootstrap#24780]
Hi,
Think it would be best to add :
cursor:pointer on the .btn class
Thx
Sébastien

**Comment by artefacus** [comment]
It have been removed from the 3.3.7.
Must be for some reasons....

**Comment by patrickhlauke** [comment]
decision was taken here https://github.com/twbs/bootstrap/pull/21812
informed by articles like https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by artefacus** [comment]
Thx for the link
