### ISSUE TITLE
Bootstrap 3 Modal displays incorrectly in Firefox 57

### ISSUE THREAD

**Issue by italodirenzo93** [twbs/bootstrap#24794]
Probably has something to do with the new CSS engine they shipped in this release. Here are two comparison images. The first is in Chrome and the other is in Firefox 57.

![image](https://user-images.githubusercontent.com/12662675/32860966-4ba3587a-ca21-11e7-84d8-6aa459e71be6.png)

![screenshot-2017-11-15 projects - caddetails](https://user-images.githubusercontent.com/12662675/32860899-0d02a3a0-ca21-11e7-9dc9-a0357ee3d850.png)

The element that is being drawn over the modal is set to "display: block".

**Comment by bkdotcom** [comment]
extremely hard to diagnose from a screenshot.  
Live example or it didn't happen.

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
