### ISSUE TITLE
Increase visual contrast of carousel controls 

### ISSUE THREAD

**Issue by exige81** [twbs/bootstrap#24798]
Depending on the content of a carousel, the control icons and indicators can get lost against the background, especially when the background content is light.

Changing colors of the controls is not a good solution if you don't know what the background will be in advance (e.g. an image album).

By using the SVG `stroke` property for the `carousel-control-*-icons` and using a box-shadow for the `carousel-indictator`, we can get carousel controls that work well against multiple backgrounds.  This would solve some of what was brought up in #21985

[Codepen of default & enhanced controls](https://codepen.io/anon/pen/WXZprY)

If something like this is a good, idea, I'll be happy to submit a PR.

**Comment by pwagland** [comment]
@Johann-S Thanks for these. I am using them in a site that I am building now, and they work pretty well. Certainly much better than the white on white that I had earlier.

**Comment by mdo** [comment]
Thanks, but we'll pass on this.

**Comment by miken32** [comment]
Thanks but we'll just make no allowances for people who want carousel controls on a light background? Helpful.
