### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by TJMusiitwa** [twbs/bootstrap#24799]
- **Bootstrap version**: v4.0.0-beta.2 
- **Operating system**: Windows 10 version 1703
- **Coding environment** : VS Code
- **Browser**: Latest Firefox version 57
- **Bug can be seen over at** : [url](http://sanattradinglimited.azurewebsites.net/Products.html)

## Issue:
When putting together my dropdown views and allocating the ids and menu as shown in the documentation, the ids do not seem to point to the right  dropdown menus assigned.

For example:
```
<button type="button" class="list-group-item list-group-item-action dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Accessories
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2">
                <button class="dropdown-item" type="button">Bar Accessories</button>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" type="button">Display Accessories</button>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" type="button">Kids Accessories</button>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" type="button">Medical Accessories</button>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" type="button">Phone Accessories</button>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" type="button">Sporting Accessories</button>
              </div>
```
and 

```
<button type="button" class="list-group-item list-group-item-action dropdown-toggle" id="bagMenu" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Bags
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bagMenu">
                <button class="dropdown-item" type="button">Bag</button>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" type="button">Bag Accessories</button>
              </div>
```

The dropdown referenced by id "bagMenu'" will not point to dropdown menu "bagMenu" but instead will point back to "dropdownMenu2"  

Again please have a look at the link provided to see the effect in the button group to the left of the page  and let me know what the issue is.
Thank you

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.
