### ISSUE TITLE
modal-backdrop is present when navigating to a new page.

### ISSUE THREAD

**Issue by kcdrez-dwd** [twbs/bootstrap#24791]
When navigating to a new page with the modal-backdrop open, that class remains on the screen after the page is loaded.

Expected: The class would be closed/not present.

Note: This is using knockout-js for the data-bind function call.

HTML:
```
<div class="modal fade" id="editTemplateModal" tabindex="-1" role="dialog" aria-labelledby="defaultModal" aria-hidden="true" style="color: black">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">My Header</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input style="width:100%" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-bind="click: editName">Submit</button>
            </div>
        </div>
    </div>
</div>
```

JS:
`
        editName = function () { 
            [ajaxservercall]
            .done(function (response) {
                window.location.assign(myURL);
            })
        }
`
Repro:
1. Click the Submit button on the modal 
2. After the new page loads from editName button, the <div class="modal-backdrop fade show"></div> is present on the new page.

**Comment by patrickhlauke** [comment]
this is not a bootstrap problem, but rather related to your own custom work on top of it. as such, it would be better to ask on StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker (but the short answer is your custom function will likely need to close the modal itself before doing its AJAX call).
