### ISSUE TITLE
Inconsistency in text colour for 'warning' (.bg-gradient-warning)

### ISSUE THREAD

**Issue by Ruffio** [twbs/bootstrap#24793]
In the blog entry for Beta 2 it looks like there are inconsistency in the text color for 'warning':
![image](https://user-images.githubusercontent.com/1877612/32860215-4093eed8-ca51-11e7-8482-c386fb7f1948.png)

**Comment by mdo** [comment]
Buttons automatically change the color since they're components. Background classes only change the background, so they don't get automatically set. That said, we should update the example to use a different color.
