### ISSUE TITLE
Possible to give .navbar-nav a width of 100%?

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#24804]
Is it possible to give `.navbar-nav` a width of 100%? This way we are able to use '.ml-auto' on the `<li>` elements for advanced layouts to keep semantics intact.

![grafik](https://user-images.githubusercontent.com/2971735/32895510-96e4dba0-cae0-11e7-926d-af3d13cf3551.png)

Unfortunately a consequence is that on non-collapsing navbars, those items keep sticking to the right. Maybe it's possible to have `width:100%` apply only above the breaking point where it goes from horizontal nav to vertical nav?

![grafik](https://user-images.githubusercontent.com/2971735/32895437-5e0b9ada-cae0-11e7-8301-9657bcaa28c1.png)

```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav" style="width:100%">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item ml-auto">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Dropdown link</a>
      </li>
    </ul>
  </div>
</nav>
```

**Comment by mdo** [comment]
No plans to add this ourselves, but as you've found with the inline style (or our `.w-100` class), you can easily add this yourself.
