### ISSUE TITLE
Button in List group not getting hover state on focus

### ISSUE THREAD

**Issue by aiventimptner** [twbs/bootstrap#24806]
In my card I added a list group with `<a>` elements and one `<button>`. With normal background the items and also the button will get into hover state on focus but with bg-dark the button will no longer support hover state.

![photo_2017-11-16_22-05-31](https://user-images.githubusercontent.com/10517363/32915806-6a39912e-cb1a-11e7-8aa7-5963aea0765f.jpg)
![photo_2017-11-16_22-05-36](https://user-images.githubusercontent.com/10517363/32915807-6a52552e-cb1a-11e7-8af3-652bff3b6982.jpg)

**Comment by aiventimptner** [comment]
**Live demo:**
[codepen.io](https://codepen.io/anon/pen/GOOojM)

**Browsers tested:**

Opera :x:

Chrome :x:

Firefox :x:

Safari :x:

**Bootstrap Version:**
4.0.0-beta2

**Comment by tmorehouse** [comment]
There also appears to be a related issue when the button has the `active` class as well. it lacks any hover/focus styling.
