### ISSUE TITLE
docs: color utilities are not described in text utilities page

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#24809]
At the http://getbootstrap.com/docs/4.0/content/typography/#text-utilities: 

> Text utilities
> Change text alignment, transform, style, weight, and color with our text utilities.

However, the text utility page does not describe how to change **color**.

**Comment by exige81** [comment]
Color utilities are covered in http://getbootstrap.com/docs/4.0/utilities/colors/

Personally, I feel like that is sufficient, but perhaps a link from the text-utilities page would be good?

**Comment by ysds** [comment]
Yes, my point is, it is not good navigation. It is better remove "color" or add link to the color utilities page.

**Comment by andresgalante** [comment]
Hi @ysds, I don't think we should remove colors since it's not only text color but also background colors.

**Comment by ysds** [comment]
@andresgalante and @mdo 
I feel you didn’t fully understand what I meant, so please let me explain it try again.

I read the following sentence, I expect that the link target page includes how to change color.

![image](https://user-images.githubusercontent.com/4065765/33069959-9ef5ee34-cef9-11e7-88b9-dee6d86a4425.png)

But the page (**text utilities**) does not mention about color. The **color utilites** page explaines that.

I my opinion it would be better to remove the word 'color' from the sentence:

> Change text alignment, transform, style, and weight with our [text utilities](http://getbootstrap.com/docs/4.0/utilities/text/).

add link to color utilities page like:

> Change text alignment, transform, style, weight, and color with our [text utilities](http://getbootstrap.com/docs/4.0/utilities/text/) and [color utilities](http://getbootstrap.com/docs/4.0/utilities/colors/).

**Comment by andresgalante** [comment]
@ysds you are right, thanks a lot for the clarification. I rather have the second option. Do you have time to send a PR? if not let me know and I'll fix it
