### ISSUE TITLE
Add example of .valid-feedback, .valid-tooltip and .invalid-tooltip

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#24811]
The example of `.valid-feedback`, `.valid-tooltip` and `.invalid-tooltip` does not seem to be in the document. Should we add these examples? especially it would be useful to clarify how to use invalid/valid-tooltip. Thanks.

Related SCSS:
https://github.com/twbs/bootstrap/blob/8df34b075a1ffffcc90d37fc44fac07c4c5d5791/scss/mixins/_forms.scss#L31-L51

**Comment by tmorehouse** [comment]
`.valid-feedbck` works nicely, although not sure about invalid or valid tooltip.  It appears to make a fixed width (250px) red or green background _behind_ the tooltip, rather than changing the tooltip background color.
