### ISSUE TITLE
possible bug carousel

### ISSUE THREAD

**Issue by Rugiewitz** [twbs/bootstrap#24815]
So i have the latest version of bootstrap, yes everything is set up correctly, and I have tried this on two different projects.
So take the carousel you guys use in the documentation, look for this line of html code
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
And remove the class "slide". I was told doing this will remove the sliding feature of the images which is what I want. Now remove the 3rd item so there is only 2 items left. Seems like it won't switch the active class to the next image. It will work with 3,4,5,6 what ever amount but just not if there are 2 items. 
I think this might be an actual bug (or i just really goofed up)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Johann-S** [comment]
I just have two slide and no `slide` class and it works as expected see : https://codepen.io/Johann-S/pen/qVVMMq?editors=1000
