### ISSUE TITLE
Collapse: Multiple Targets Accordion only works once, then fails

### ISSUE THREAD

**Issue by sweisgerber-dev** [twbs/bootstrap#24810]
I created a collapse with multiple targets in an accordion-style setup (set data-parent).
The switching works well, exactly once.
The second group of targets then has the `show` class removed and never added again (only after page reload

## Steps to reproduce

Check the codepen sample below and click  the numbered collapse links from 2-3, then click on 1 again.
The second group switches perfectly when clicking 2&3, when clicking on 1 again it fails.

# environment

- Operating system and version Linux (Manjaro, Arch-Based
- Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Example, based on he official docs: https://codepen.io/sweisgerber-dev/pen/mqqBbK

**Comment by Johann-S** [comment]
It's a multi accordion :thinking: that's not something we thought when we added that feature so currently it's something unsupported but I'm not against it if someone want to handle that case
