### ISSUE TITLE
Cards with grid markup lose bottom margin

### ISSUE THREAD

**Issue by Spetnik** [twbs/bootstrap#24827]
I tried implementing the recommendation at https://getbootstrap.com/docs/4.0/components/card/#using-grid-markup here: https://codepen.io/AJSpetner/pen/OOzEbB

When resizing the browser, the cards stack, but the `@media (min-width: 576px) .card-deck .card` selector (and all other widths, except `xs`) overrides the margin-bottom and sets it to `0`.

![image](https://user-images.githubusercontent.com/1311919/32989777-78795494-cce2-11e7-9711-13fc3be83c20.png)

This is easily fixed with an override in the CSS, but why would we want the margin to be 0 here?

**Comment by mdo** [comment]
Don't mix grid classes with component classes like that. Separate them and you'll be fine.

**Comment by Spetnik** [comment]
See https://codepen.io/spetnik/pen/zPLBJq - I copied the code straight out of the example at https://getbootstrap.com/docs/4.0/components/card/#using-grid-markup and when the cards wrap there is no margin. Is the doc wrong? Am I missing something?

**Comment by mdo** [comment]
We don't include a default margin on cards.
