### ISSUE TITLE
Bootstrap for academic publishing

### ISSUE THREAD

**Issue by Gitubert** [twbs/bootstrap#24823]
Hello,

Is it possible to use Bootstrap by non-developers like me to build a scholarly science journal that requires a workflow steps of actions (submit manuscripts, review them by editor/reviewers, and then publish them online in HTML and PDF formats alongside some article tools such as providing citation download link and citation format to be displayed along with the text?
If not, is there already any themes/plugins developed specifically for such goals that one can eventually try/buy to customize as an academic journal?

Thank you in advance.
Gitubert

**Comment by mdo** [comment]
Bootstrap's can help style those artifacts and add interactive behaviors, but it is not a publishing system for creating or sharing that content. Unsure about themes or add-ons to target it—I'd suggest asking in our Slack or on StackOverflow.

**Comment by Gitubert** [comment]
Thanks for the reply.
What's a pity though!
Bootstrap seems to be clean and powerful tool.
