### ISSUE TITLE
Pagination active page-link lacks noticeable focus styling in Firefox

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#24838]
- Operating system and version : Any
- Browser and version: Firefox (and maybe others)
- Reduced test case: https://codepen.io/tmorehouse/pen/MOQXyd

The current CSS for pagination `.page-item.active .page-link` does not include any noticeable focus styling when using Firefox, which makes it difficult for keyboard only users to know if the `active` link is focused or not.

Tab through the page links in the codepen to see the issue (and one possible solution) using Firefox

I've used the following workaround CSS to provide focus styling for the active page-link:

```css
.pagination .page-item.active .page-link:focus {
    box-shadow: 0 0 0 3px rgba(0,123,255,.5);
    z-index: 2;
}
```
Currently the active page link looks like this with focused and not focused (the change in outline is negligible):
![image](https://user-images.githubusercontent.com/2781561/33040193-b44eff94-ce10-11e7-9365-3b78298130cb.png)

With the proposed focus styling it looks as follows (which uses similar styling as the primary button focus styling):
![image](https://user-images.githubusercontent.com/2781561/33040268-ea269f46-ce10-11e7-878b-bb1399363784.png)

Another quick workaround is to place the class `.btn-primary` (without the `.btn` class) on the active page-link (the `<a>` tag), which produces the same effect when focused.

**Comment by andresgalante** [comment]
Hi @tmorehouse, thanks for reporting this.

The focus on anchors is the default focus of the browser, for example: on a mac on chrome it looks like this:

![img](http://g.recordit.co/GXGeiOAlJA.gif)

I see what you mean about the focus ring not been consistent with `.btn` and I am for adding the shadow on pagination. @patrickhlauke What do you think?

**Comment by tmorehouse** [comment]
I should have mentioned that I was also using Firefox, which has a very subtle focus ring

**Comment by andresgalante** [comment]
@tmorehouse I agree, different browsers will show less noticeable focus rings. Let's wait for @patrickhlauke comment. As I mention before I think we should add the same focus ring as in btns for consistency.
