### ISSUE TITLE
[HELP] - v4-beta2 - is-warning for input forms

### ISSUE THREAD

**Issue by Tiago-Marques** [twbs/bootstrap#24846]
Reading [documentaion](https://getbootstrap.com/docs/4.0/components/forms/) i can't found about warning state for input forms.

Is this on developing or removed?

I can found some instruction on v4-alpha version [documentation](https://v4-alpha.getbootstrap.com/components/forms/#examples)

**Comment by istratos** [comment]
Warning states were removed in favor of only success and danger ones.

**Comment by mdo** [comment]
They've been gone for a long time now and aren't coming back. Search for related issues if you want more background.
