### ISSUE TITLE
Navbar not appearing correctly

### ISSUE THREAD

**Issue by harrisdb** [twbs/bootstrap#24843]
Hi!

I am trying to add a navbar to my website and I'm having a problem with the way it is appearing. I am copying the code from the Bootstrap website for a basic navbar. 

The navbar should look like this: 
![80ccb6236a03b1824840762ebaeefb03](https://user-images.githubusercontent.com/32749317/33063436-7926a36c-ce70-11e7-9a27-ee75c4292923.png)

but instead it is looking like this:
![image](https://user-images.githubusercontent.com/32749317/33063463-8daaea96-ce70-11e7-8f53-3255776c3b52.png)

Here is the code for the navbar (github is auto removing the first line which is the nav class): <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Navbar</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

and here is my scripts:
  
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    
    <script>
    $('#myModal').on('shown.bs.modal', function() {
      $('#myInput').focus()
    })
    </script>

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Tapakan** [comment]
There is truth in his words, the same thing happened with me. I ever can't find` .navbar-toggleable-md` class in dist.

**Comment by JarryHua** [comment]
1) win7, chrome
2) use the following link and the next navbar code. 
3) I also did the validation via js bin. it still does not work, actually when i use navbar-expand-sm instead of navbar-toggleable-sm, it works. what's behind? 

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous"> 
  
  <div class="navbar navbar-toggleable-sm navbar-inverse bg-inverse fixed-top">
        <div class="container">
            <a href="#" class="navbar-brand">LoopLab</a>
            <button type="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#mainMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="mainMenu" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#explore-head-section">Explore</a></li>
                    <li class="nav-item"><a class="nav-link" href="#create-head-section">Create</a></li>
                    <li class="nav-item"><a class="nav-link" href="#share-head-section">Share</a></li>
                </ul>
            </div>
        </div>
    </div>

</body>
</html>
