### ISSUE TITLE
is-(in)valid doesn't seem to work at all

### ISSUE THREAD

**Issue by IonicaBizau** [twbs/bootstrap#24847]
```html
<form action="" class="was-validated">
  <input type="text" class="form-control is-invalid">  
</form>
```

`:valid` seems to have higher priority over `is-invalid`, hence the input is green. I have a piece of JavaScript which decides if the input is valid or not, and adds this class.

- Operating system and version: macOS High Sierra
- Browser and version: Google Chrome
- Reduced test cases and potential fixes: https://jsfiddle.net/fxxrqd13/

Related: https://stackoverflow.com/q/47427827/1420197 
Related issue: #24743

**Comment by tmorehouse** [comment]
`.was-validated` triggers the native browser validation (depending on your form's `novalidation` attribute).

If you are doing "server side / client JavaScript validation), you do not need to add in the `.was-validated` class.

**Comment by tmorehouse** [comment]
I would suggest dipping into the HTML5 validation API to determine validity state

**Comment by IonicaBizau** [comment]
@tmorehouse If I remove the `.was-validated` class, the `:valid` and `:invalid` inputs do not have colors anymore.

Are you suggesting I should use `myField.setCustomValidity("invalid")` for that input instead of adding a class?

**Comment by Johann-S** [comment]
Please can you update your JSFiddle with our latest release ? (Beta 2)

**Comment by IonicaBizau** [comment]
@Johann-S Updated: https://jsfiddle.net/fxxrqd13/1/

**Comment by tmorehouse** [comment]
@IonicaBizau, if you are programmatically adding the class `.is-invalid`, then you can use the validity checks from the API to see if the input passes native browser validation, and apply the `is-invalid` class accordingly.

**Comment by mdo** [comment]
The docs are pretty clear on this—`.was-validated` for is for live HTML5 validation in the browser while the classes `.is-valid` and `.is-invalid` are for custom validation you'd setup. In your latest fiddle, you were still using the class on the input when you should be using the `required` attribute.

**Comment by IonicaBizau** [comment]
@mdo I understand that, but how can we combine them?

My use case is that I use `.was-validated` on the form, and call the `checkValidation()` method, except one field has custom validation (I want to add `is-(in)valid` classes there).

**Comment by leob** [comment]
I also want to use both HTML 5 validation, and server side validation, in the same form, because it makes sense (in my use case). Solution/workaround turns out to be simple: I moved the "is-valid" class from the form group to the form control. Then when I generate a "server side error" I just remove the "was-validated" from the form, and voila. HTML5/client side validation also still works fine (with "was-validated" on the form). Can have my cake and eat it too.
