### ISSUE TITLE
Feature: Monorepo with Lerna.

### ISSUE THREAD

**Issue by marcobiedermann** [twbs/bootstrap#24848]
How about using [Lerna](https://github.com/lerna/lerna) to create a mono repo which holds multiple components which would work on it's own.
This way it is really easy to test each component and to publish independent versions.
Also you can only install the needed packages via npm.
[GitHub's Primer](https://github.com/primer/primer) and [Babel](https://github.com/babel/babel/) are using the approach as well. Maybe this helps getting some references / ideas.

I would like to hear your opinion on this topic if it might be useful for this project.

**Comment by Johann-S** [comment]
They are a PR which try to setup Lerna on Bootstrap see : https://github.com/twbs/bootstrap/pull/23614
Related to #23557
