### ISSUE TITLE
Overriding $theme-colors

### ISSUE THREAD

**Issue by Djules** [twbs/bootstrap#24849]
Using v4.0.0-beta.2, I found out something changed with map of theme colors.

Now default `$theme-colors` is merged with custom one, no matter what.
But what if I don't need _success_, _info_, _danger_, etc… for background or text utility classes?

**Comment by andresgalante** [comment]
Hi @Djules you can remove the colors you don't want from the theme map and you wont get that CSS compiled.

**Comment by Djules** [comment]
Hi @andresgalante, unfortunately not since the last version, because in file [_variable.scss](https://github.com/twbs/bootstrap/blob/dcb761350c72d77a4288493efc5b9a043feb9a26/scss/_variables.scss#L75), you can see that `$theme-colors` var is merged with the custom one.

So you can add or modify existing key in the map, but you can't remove one as far as I know.

**Comment by Djules** [comment]
One solution is to remove undesirable keys after the import of the Bootstrap variables file. 

```scss
@import "custom";
@import "~bootstrap/scss/bootstrap";

$theme-colors: map-remove($theme-colors, "success", "info", "danger");
```
Maybe this is what what you meant @andresgalante.

**Comment by andresgalante** [comment]
Sorry @Djules I am kinda lost, the only difference I see between v2 and v3 is that now the variables are have reference outside the map due to this PR #23918

What's the goal of removing them? I am just unsure that the hit on performance is significant to the point that you'd want to remove them.

**Comment by Djules** [comment]
Just for performance purpose yes, to save some bytes is the compiled CSS, as I don't need those state colors in my custom theme.

**Comment by andresgalante** [comment]
@Djules I see, thanks a lot for taking the time to clarify it.

It'll be up to @mdo to decide if we want to keep the `map-merge` function for themes.

**Comment by mdo** [comment]
The `map-merge` is kind of essential to customization. We'll likely want to add some docs though for how to _remove_ values. Want to take a stab at that @Djules or should I?
