### ISSUE TITLE
iPhone X Support

### ISSUE THREAD

**Issue by surjithctly** [twbs/bootstrap#24850]
Any plans for Bootstrap 4 to support iPhone X by default? esp, the landscape mode? 

or should users do it manually? A clarification would be great!

_Related Links:_

https://webkit.org/blog/7929/designing-websites-for-iphone-x/

https://booking.design/how-we-adapted-the-booking-com-mobile-site-for-the-iphone-x-notch-e880fa00e989

**Comment by patrickhlauke** [comment]
as how you adapt your site will depend on your actual layout, how you want your backgrounds to work, etc, i'd say it's up to authors to do it themselves at this stage.

**Comment by BUYMERCIER** [comment]
Agreed with @surjithctly, it would be nice to have the navbar and background colors automatically fill the notch zones by default.

This looks a bit weird:
![img_1132](https://user-images.githubusercontent.com/21960643/50725844-efc3bf00-1136-11e9-8404-8e08c1c8d5ac.JPG)

Especially now most phones are based on the iPhone X design.
