### ISSUE TITLE
Compatibility issues with Tab drop

### ISSUE THREAD

**Issue by pau1phi11ips** [twbs/bootstrap#24859]
I currently use this BS3 plugin which is pretty handy - http://www.eyecon.ro/bootstrap-tabdrop/

I've forked it and made it work with BS4 flexbox style nav-tabs but it falls over because of this in tabs.js

`ACTIVE_UL             : '> li > .active'`

Is there any chance of changing ACTIVE_UL to

`> li .active`

**Comment by Johann-S** [comment]
if all of our unit tests and visual tests works with that change why not 👍

**Comment by XhmikosR** [comment]
This change had broken nested tabs @Johann-S.

**Comment by Johann-S** [comment]
Closed thanks to @XhmikosR 👍

**Comment by pau1phi11ips** [comment]
@Johann-S Surely tabs within tabs is just bad UI?

**Comment by XhmikosR** [comment]
It broke too many things which it shouldn't. So we need to be more specific with the current markup.

**Comment by pau1phi11ips** [comment]
That's a bummer. I just tried using nested tabs in this pen with `> li .active` and it seems to work OK.
https://codepen.io/pau1phi11ips/pen/MOGNvv

Could you let me know what it broke as I was going to just run with my modded version of tabs.js but if there's something I should not do then it'd be good to know.

**Comment by XhmikosR** [comment]
See the issues we reference in https://github.com/twbs/bootstrap/pull/23087 at the bottom.

**Comment by pau1phi11ips** [comment]
Thanks, much appreciated!
