### ISSUE TITLE
Example screenshots are not accurate

### ISSUE THREAD

**Issue by asilcetin** [twbs/bootstrap#24852]
Example screenshots for starter templates need to be updated.

See them under: http://getbootstrap.com/docs/4.0/examples/
And inside the git repo under: docs/4.0/examples/screenshots

Nearly all navbars in the screenshots are inside containers whereas the actual templates use full-width navbars. There are also other inconsistencies such as elements, colours etc.

This is a minor issue regarding representation but still important for people who use those templates a starting point.

**Comment by Johann-S** [comment]
They will be updated in our next release thanks 👍

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/pull/24395
