### ISSUE TITLE
enable/disable bootstrap plugins for certain elements/areas

### ISSUE THREAD

**Issue by jofran73** [twbs/bootstrap#24858]
I have a bootstrap themed site that utilizes a common master layout including a navbar. One page is hosting an angular application, which is only rendering parts of the content, not the full page. Since bootstrap plugins do not work in Angular, I'm using ng-bootstrap inside my Angular app. Unfortunately, the bootstrap javascript I load for my page layout conflicts with the code ng-bootstrap is providing.

The problem would be eliminated if there was a way to restrain bootstrap plugins to a certain page area (i.e. '#page-navbar' and all children) or to disable the bootstrap plugin for a certain page area (i.e. '#my-angular-app-container' and all children).

I understand that it is possible to globally turn off the data-api with `$(document).off('.data-api')`, but not for specific elements like `$('#my-angular-app-container').off('.data-api')`.
Is there any existing solution that I missed or an idea what might be done to enable this scenario?
How about introducing a selector like `.no-bootstrap-js` that blocks the instantiation of bootstrap code on the element and its children?
```
<nav id="page-navbar" class="navbar navbar-expand-lg navbar-light bg-light">...</nav>
<div id="my-angular-app-container" class="container no-bootstrap-js"><myAngularApp></myAngularApp></div>
```

I hope that is making some kind of sense. Thanks for reading.

**Comment by mdo** [comment]
> The problem would be eliminated if there was a way to restrain bootstrap plugins to a certain page area (i.e. '#page-navbar' and all children) or to disable the bootstrap plugin for a certain page area (i.e. '#my-angular-app-container' and all children).

No plans to add this kind of behavior. If you don't want to load Bootstrap on a particular _area_ of a page, I'd suggest revisiting why you're including Bootstrap like that. I'm sure there are other implementation methods that could better suite your needs.
