### ISSUE TITLE
Responsive amount of elements / items in Carousel

### ISSUE THREAD

**Issue by Uzumymw95** [twbs/bootstrap#24853]
Hello,
I think that option should be in each slider, so Carousel too - reponsive items.

For example:
devices ≥992pxs: 5 items*
devices ≥768px: 3 items*
devices <576px: 1 item*

*by items i mean bootstrap cards, panels etc in 1 slide. Options could be changed by breakpoint classes in carousel structure or javascript code like:

```
$('.carousel').carousel({
responsive : {
'ES': { items: 1 }, // ES <576px
'SM': { items: 3 }, // SM ≥768px
'LG': { items: 5 } // LG ≥992pxs
}
});
```

**Comment by mdo** [comment]
No thanks, we'll pass on this.

You can accomplish something similar though by customizing the contents of your carousel slides. Put some grid items in there or some custom HTML/CSS for multiple contents per slide.
