### ISSUE TITLE
[Bug: Documentation] loading years, if you click a Link

### ISSUE THREAD

**Issue by Bizarrus** [twbs/bootstrap#24864]
- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
`Windows 7 Professional x64`
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
**Opera**, User-Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36 OPR/49.0.2725.47`

If you go to the bootstrap-website (`https://getbootstrap.com`) and click on a link (for sample, in the main navigation to `Documentation`), the page don't react. Only the `Favicon` changes to an `Loading indicator`, the same problem is, when you click on the side-navigation on the `Documentation`.

If you using `right click` and open the selected link in a new tab, the page will be loaded directly.

**Comment by patrickhlauke** [comment]
Cannot reproduce the issue. I'd suggest this is some problem at your end?

**Comment by XhmikosR** [comment]
Yeah, works fine here too.
