### ISSUE TITLE
Conditional value for $yiq in the color-yiq function

### ISSUE THREAD

**Issue by proactivo** [twbs/bootstrap#24865]
I searched here but found nothing about it.
Several clients have asked me about buttons with the "btn-warning" class. So I did some tests with other colors and, in my opinion, the condition:
@if ($ yiq> = 150) {
would have a better result if the conditional value were changed to:
@if ($ yiq> = 195) {

Here are some examples below:
![color-yiq](https://user-images.githubusercontent.com/3412503/33210855-94e94488-d0fa-11e7-8fcd-1627fc1934a9.png)

But I also believe this to be a personal opinion. In this way, we could consider a variable for this value. I think we'd shut the functionality down.
Well, I think it's a simple change and it's going to have a positive impact.

**Comment by mdo** [comment]
> In this way, we could consider a variable for this value. I think we'd shut the functionality down.

I'm down for a variable.
