### ISSUE TITLE
Your service worker creates an infinite loop on page load

### ISSUE THREAD

**Issue by adamzr** [twbs/bootstrap#24868]
At https://getbootstrap.com/ I get an infinite loop trying to load the documentation tab. See dev tools:
<img width="1164" alt="screen shot 2017-11-24 at 10 48 23 am" src="https://user-images.githubusercontent.com/455518/33221537-1b97e9f8-d105-11e7-8d78-d7faf93397fc.png">

There's an infinite loop in the service worker.

Chrome Version 62.0.3202.94 (Official Build) (64-bit) on MacOS

**Comment by XhmikosR** [comment]
Works fine here, I'm not sure how to reproduce. This is the second time we get a report so something must be wrong.

/CC @gauntface @addyosmani if you guys have any ideas.

**Comment by phaidon** [comment]
If I do it I get the following message in the console:

ServiceWorker registration failed:  DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

**Comment by gauntface** [comment]
To reproduce I did the following:

1. Go to https://getbootstrap.com/
1. Go to Document site (everything should be fine) 
1. Open DevTools and go to Application tab and click the update on reload
1. Refresh the page - get the loop

**Comment by gauntface** [comment]
Best guess is this chunk of code:

```js
(function e() {
    "use strict";
    if ("serviceWorker" in navigator) {
        window.addEventListener("load", function() {
            navigator.serviceWorker.register("/sw.js").then(function(e) {
                console.log("ServiceWorker registration successful with scope: ", e.scope);
                e.onupdatefound = function() {
                    var t = e.installing;
                    t.onstatechange = function() {
                        switch (t.state) {
                            case "installed":
                                if (navigator.serviceWorker.controller) {
                                    console.log("new update available");
                                    location.reload(true)
                                }
                                break;
                            default:
                        }
                    }
                }
            }).catch(function(e) {
                console.log("ServiceWorker registration failed: ", e)
            })
        })
    }
})();
```

**Comment by gauntface** [comment]
Ok, so what I hit was that update on reload was continually resulting in the page loading, installing a new SW, reloading, which then forced a new service worker to install.

I'm not sure how else you would get in this loop. Are others seeing the "new update available" log?

**Comment by XhmikosR** [comment]
@gauntface: Thanks for the reply, I really appreciate it!

Now, the source for that is https://github.com/twbs/bootstrap/blob/v4-dev/assets/js/src/pwa.js which was basically added in https://github.com/twbs/bootstrap/commit/5951508898b1f92d04026c0038dfc3ba95fa0fdf#diff-a81ed3855367b28b54556dd67ace9caa

Looking at the code it seems we are explicitly reloading the page when in `navigator.serviceWorker.controller` which doesn't seem right indeed.

I can reproduce too with Chrome 62.0.3202.94 and Dev Tools open. Firefox on the other hand doesn't have this issue.

**Comment by XhmikosR** [comment]
/CC @Lyricalz since he is the author of that patch.

**Comment by XhmikosR** [comment]
Should we just call `registration.update()`? What is the right way to handle this? Or can we just remove the whole `onupdatefound` block?

**Comment by adamzr** [comment]
You could do what https://www.chromestatus.com does and display a toast to prompt the user to update. See https://github.com/GoogleChrome/chromium-dashboard/blob/master/static/js/service-worker-registration.es6.js

**Comment by XhmikosR** [comment]
Hmm, that would require quite a few changes.

Isn't there a default cache that the browser will respect and if it's expired request a new one? What is the downside if we just remove the whole `onupdatefound` block?

Any PRs are welcome BTW (don't forget to CC me).

**Comment by Lyricalz** [comment]
i'll try to get a PR in for this soon!

**Comment by gauntface** [comment]
Few ideas off the top of my head:

1.) Simply don't reload and wait for the user to visit the page again
2.) Call skipWaiting and clientsClaim which will allow the current service worker to control all currently open windows. Then on the users next click, they'll be hitting the new service worker.
3.) Do the same as 2, but reload on activation. This may incur the loop with updateOnReload, but it shouldn't get an infinite loop for normal users since the service worker won't update unless it's actually changed, I think with your current flow, if service worker could be installing but not activated due to multiple windows being open and you'll just keep on looping until the windows are shut.

Skip waiting and clients claim can be done with:

```js
new WorkboxSW({
  skipWaiting: true,
  clientsClaim: true,
});
```

**Comment by XhmikosR** [comment]
Thanks for all the info!

@Lyricalz: I say we just remove the offending code and don't do anything fancy when an update is available, just download it and nuke the old one.
