### ISSUE TITLE
[doubt] custom bootstrap

### ISSUE THREAD

**Issue by AlexMCoder** [twbs/bootstrap#24867]
Is there a possibility in bootstrap 4 to only download some parts?

For example, download the part of grids and buttons.

I researched and found this option only for bootstrap version 3

**Comment by andresgalante** [comment]
@AlexMCoder yes, you need to use the sass source and recompile. Please read http://getbootstrap.com/docs/4.0/getting-started/theming/ and let me know if it answers your question.

**Comment by mdo** [comment]
There's no web-based customizer, though I think there are some third party ones if you search around. As @andresgalante mentions though, we have clear docs for customizing yourself and include some build options in our download page.
