### ISSUE TITLE
Best practices for adding bootstrap CDN link to my project (and its dependencies jquery and popper)

### ISSUE THREAD

**Issue by carloshmm** [twbs/bootstrap#24874]
I read here: https://getbootstrap.com/docs/4.0/getting-started/introduction/
instructions on how to add all the required scripts and style-sheet files to get Bootstrap toolkit working properly on my project.

There, we can see that links were provided to Bootstrap and all its dependencies.

These links all have hard coded versions, ex: bootstrap/4.0.0-beta.2.

I have two questions:
Regarding security, should I worry about updating my project to always use the latest version of Bootstrap and its dependencies? If so, how people deal with this?

**Comment by mdo** [comment]
> These links all have hard coded versions, ex: bootstrap/4.0.0-beta.2.

Always use a particular version—things change that can easily cause different or unexpected rendering of items across browsers and devices.

> Regarding security, should I worry about updating my project to always use the latest version of Bootstrap and its dependencies? If so, how people deal with this?

If you use our JS, try to stay on the latest version. CSS is less important, but the two (CSS and JS) tend to go hand-in-hand. Manually updating isn't too bad, but does take time. Don't bother with super old projects though—major releases like v3 to v4 are fundamentally different code bases.

**Comment by carloshmm** [comment]
Thank you for your explanation.
Last question:
Is the documentation available here: https://getbootstrap.com/docs/4.0/getting-started/introduction/
always up-to-date regarding these links (Bootstrap and its dependencies)?
Could you please provide me a reliable source where I can find a link for the latest minified version of popper?
I already found links for the latest versions of Bootstrap (https://getbootstrap.com/docs/4.0/getting-started/download/) and jQuery (https://jquery.com/download/), I was unable to find a link for the minified version of popper, the only source I found was their github repository (https://github.com/FezVrasta/popper.js#installation) but there doesn't seem to have a link for the 'popper.min.js'.

**Comment by Johann-S** [comment]
they are a link for Popper.js minified in each of our plugin's page, but you can find it here  https://cdnjs.com/libraries/popper.js (prefer the UMD version)
