### ISSUE TITLE
Cards with background variant - colors not  showing

### ISSUE THREAD

**Issue by nisalup** [twbs/bootstrap#24875]
I've noticed an issue with bootsrap version 4 cards in the beta release. As per the documentation [here ](https://v4-alpha.getbootstrap.com/components/card/), it says to use the following code:

```
<div class="card card-inverse card-primary mb-3 text-center">
  <div class="card-block">
    <blockquote class="card-blockquote">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
      <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
    </blockquote>
  </div>
</div>
```
However, this does not provide any type of themed color (primary, warning etc)
I figured a workaround by changing `card-primary` in the first div to `bg-primary`.
Checked on Chrome and Edge in windows 10.
(This is my first report, so pardon for any errors please)

**Comment by mdo** [comment]
Use the latest docs at https://getbootstrap.com—the CSS has changed.
