### ISSUE TITLE
Custom stacked checkbox label stretches to full width

### ISSUE THREAD

**Issue by jackmu95** [twbs/bootstrap#24888]
**Operating system and version:** Any
**Browser and version:** Any
**Test case:** https://getbootstrap.com/docs/4.0/components/forms/#stacked

![bootstrap_v4_custom_checkbox_stacked_old](https://user-images.githubusercontent.com/2737132/33269421-e94eaa6c-d380-11e7-8831-d5497076a088.png)

As seen in the picture above, the label of a stacked checkbox stretches to the full with of the parent container. This can cause issues when a user clicks far right from the visible label and accidentally toggles a checkbox or radio.

A simple fix would be to set `align-items` for the `custom-controls-stacked` container to `flex-start` (see picture below).

![bootstrap_v4_custom_checkbox_stacked_new](https://user-images.githubusercontent.com/2737132/33269926-9e9dc802-d382-11e7-9127-fd5fd759befc.png)

**Comment by mdo** [comment]
This will be fixed by #23444.
