### ISSUE TITLE
Checkbox in disabled+checked state has part of left border cut off on Safari on iOS 8 and up when using some col-classes

### ISSUE THREAD

**Issue by chce** [twbs/bootstrap#24885]
Operating system: iOS 8, iOS 10.3.3, iOS 11.1.2
Browser: Safari
Bootstrap version: 3.3.7
Minimal example: https://jsbin.com/joduqizuru

I experience the bug using Browserstack on:
* iPad Air 2 with iOS 8 using Safari
* iPhone 6 with iOS 8 using Safari

With physical devices, I experience the bug on:
* iPhone 5 with iOS 10.3.3 using Safari
* iPhone 6 with iOS 11.1.2 using Safari

It seems to be the percentage width setting of col-\*-\* that causes the border issue. Changing the percentage width in developer console has some effect on the border, cutting less or more off.

I've also added a bug report to the webkit bugtracker: https://bugs.webkit.org/show_bug.cgi?id=180030

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
