### ISSUE TITLE
Layout vs presentation

### ISSUE THREAD

**Issue by mgwalm** [twbs/bootstrap#24882]
I'm always having problems with layout and/or presentation.

I think layout are things like sizes, positions, grids, table, etc.

Presentation are things like colour, fonts, etc.

I think bootstrap (and other libraries) should not change the presentation of a page, or to put it another way, the fonts, font sizes and colours, ie, presentation should be determined by the developer, not the library.

I'm always having to override presentation aspects of bootstrap, eg, fonts.

**Comment by mdo** [comment]
> I think bootstrap (and other libraries) should not change the presentation of a page

I think Bootstrap should change the presentation of the page—because that's what it was designed to to and what it has continued to do for over six years :). No plans to change this.

**Comment by mgwalm** [comment]
Bootstrap is good for layout (the main thrust of it).

**Comment by mgwalm** [comment]
Maybe all presentation rules should only be in themes which should be easily changed be the developer.
