### ISSUE TITLE
Ideas for BootStrap v5: Use CSS Grid Layout

### ISSUE THREAD

**Issue by SuperPat45** [twbs/bootstrap#24887]
Hello,

Bootstrap 5 may be rely on the new standard CSS Grid layout which allow to divide available space for layout into columns and rows:

https://caniuse.com/#feat=css-grid

**Comment by andresgalante** [comment]
Check this out 😄 
https://mdo.github.io/bootstrap-css-grid-layout/

**Comment by mdo** [comment]
Yup, it'll be on our list :).

**Comment by RehanSaeed** [comment]
@andresgalante Your demo is really cool. CSS Grid support is now viable (if you don't have to support IE  and even then there are [prefixes](https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/) to get that working).

I'm trying to understand if the twelve column grid makes sense anymore to layout a page. The twelve column grid can only use a subset of the features of CSS grid, without some utility classes added on to help and even then I'm not sure. If using React/Vue or some other framework, perhaps it's time to dump the twelve column grid and use raw CSS grid instead. What are your thoughts?
