### ISSUE TITLE
Change Bootstrap4 font-sizes relative to Scss $font-size-base

### ISSUE THREAD

**Issue by syed-haroon** [twbs/bootstrap#24896]
I posted this question in StackOverflow but did not find much help:
https://stackoverflow.com/q/47487054/1292050

I am customizing Bootstrap4 but finding it hard to understand why the things are not working as expected.

Importing original _variables.scss and changing `$font-size-base` should work else we need to change it in 14 variables (eg. `$h1-font-size: $font-size-base * 2.5`). And in future when I update my "node_modules > bootstrap" then I don't have to check again if the $font-size-base has been referred in any new variables by bootstrap team.

I created and new `_custom-variable.scss` and imported variables in it:

    @import '../node_modules/bootstrap/scss/variables';

and changed `$font-size-base: 1rem` to `$font-size-base: 0.875rem;`

this works fine when I see compiled css for `body`:

    // ../node_modules/bootstrap/scss/_reboot.scss
    body {
      ...
      font-size: $font-size-base;
      ...
    }

    // compiled css
    body {
      ...
      font-size: 0.875rem;
      ...
    }

But here is the problem, it doens't work for heading tags:

    // In my _custom-variable.scss, when I change $font-size-base from 1rem to 0.875 
    // then I expect the values changed to:
    h1 { font-size: 2.1875rem }
    h2 { font-size: 1.75rem }
    ...
    h6 { font-size: .875rem }
    
    // but nothing gets changed
    h1 { font-size: 2.5rem }
    h2 { font-size: 2rem }
    ...
    h6 { font-size: 1rem }

I am not sure about this but I feel like this is due to calculation here:

    //../node_modules/bootstrap/scss/_variables.scss
    $h1-font-size: $font-size-base * 2.5 !default;
    $h2-font-size: $font-size-base * 2 !default;
    ...
    $h6-font-size: $font-size-base !default;

**Comment by mdo** [comment]
This was changed in v4-dev already and is coming in the Beta 3 release. https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L239
