### ISSUE TITLE
Use actual bootstrap markup in examples

### ISSUE THREAD

**Issue by bschlenk** [twbs/bootstrap#24895]
In the [current documentation](https://getbootstrap.com/docs/4.0/layout/overview/) examples for using the `container` class, the example html doesn't even use the container class, it uses some `bd-example-container-body` class. I would expect the documentation source to be viewable as documentation in and of itself. Here's a screenshot of the page with devtools open:

<img width="1112" alt="screen shot 2017-11-27 at 3 31 18 pm" src="https://user-images.githubusercontent.com/1390303/33295342-b09c26e6-d389-11e7-87a3-54e7d711aac9.png">

**Comment by mdo** [comment]
That's for illustration purposes; it's not the actual component.

**Comment by bschlenk** [comment]
That’s my point - why not illustrate the usage of the class by using the class itself? It would be much more useful. I can’t be the only one who dove into the source code expecting to see how that layout was accomplished using bootstrap, only to be disappointed.
