### ISSUE TITLE
Bootstrap missing Card Outlines

### ISSUE THREAD

**Issue by updatesvc** [twbs/bootstrap#24892]
From the Documentation [Cards Outline](https://v4-alpha.getbootstrap.com/components/card/#outline-cards)

The cards have the appropriate colours but on using the **4.0.0-beta.2 version**
The css selectors _card-outline-*_ are missing from the bootstrap.min.css
But are available on alpha v6 which is used for the documentation.
Please add the cards css:
`.card-outline-primary{background-color:transparent;border-color:#0275d8}.card-outline-secondary{background-color:transparent;border-color:#ccc}.card-outline-info{background-color:transparent;border-color:#5bc0de}.card-outline-success{background-color:transparent;border-color:#5cb85c}.card-outline-warning{background-color:transparent;border-color:#f0ad4e}.card-outline-danger{background-color:transparent;border-color:#d9534f}`

Hopefully this wasn't deprecated, if so I hope the docs get updated.

**Comment by mdo** [comment]
https://getbootstrap.com/docs/4.0/components/card/#border

**Comment by updatesvc** [comment]
Seems I was using the old alpha docs.
