### ISSUE TITLE
Revisit text-hide mixin

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#24890]
This helper comes from html5 Boilerplate. It was removed in 2013 in [this PR](https://github.com/h5bp/html5-boilerplate/pull/1475).

We should revisit it or remove it too.

/CC @mdo

**Comment by moso** [comment]
Isn't `text-hide` sort of reduntant now that we have [display utilities](https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_display.scss), which are even responsive?

One could easily use `<p class="d-sm-none">Text</p>` if one wants to hide text responsively (I know I have done the same in the past where I hide the text in a button and only show its icon on small devices). If it's for screenreaders only, then we have utilities for that aswell.

**Comment by mdo** [comment]
@moso The goal of text hiding is to _visually_ hide the text while still rendering the element's overall size and shape, often with a `background-image` to show something else. Display utilities wouldn't accomplish that, nor would visibility utilities.

**Comment by mdo** [comment]
That said, it is an old technique :).

**Comment by mdo** [comment]
We're kinda stuck with this now that we're heading to v4 stable. We _could_ drop it, but it'd technically be a breaking change. Thoughts?

**Comment by moso** [comment]
Leave it in, and maybe do a `$enable-text-hide`-variable so people can disable it?

**Comment by patrickhlauke** [comment]
i'd say remove the whole image replacement thing in 4.1 (or do an unscheduled breaking change, nobody would die from that presumably). maybe replace with more modern approaches (e.g. using `sr-only` to include actual text in html). generally (from my experience anyway) authors will set a custom width/height when doing IR, so the fact that `text-hide` maintains the size etc is mostly pointless, i'd say.

**Comment by mdo** [comment]
Let's deprecate for 4.1 or 4.2 if we can.
