### ISSUE TITLE
Can't vertically center the modal

### ISSUE THREAD

**Issue by lvxianchao** [twbs/bootstrap#24908]
I added `.modal-dialog-centered` to `.modal-dialog` to vertically center the modal, but it doesn't work.

I used this cdn `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">`

![code](https://user-images.githubusercontent.com/22412818/33368556-f9ad0054-d52c-11e7-8d0a-d61af6b36a1f.png)

![_003](https://user-images.githubusercontent.com/22412818/33368872-d1c1d10e-d52d-11e7-8931-f44682ad125e.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by tmorehouse** [comment]
Vertically centered modals are not available in v4.0.0-beta,2, but will be in v4.0.0-beta.3

**Comment by Johann-S** [comment]
Oh good catch @tmorehouse 😆 my bad 👍

**Comment by lvxianchao** [comment]
OS: Ubuntu 16.04
Browser: Google Chrome  62.0.3202.94 (x64)
Bootstrap Version: 4.0.0-beta.2
