### ISSUE TITLE
programmatic dropdown toggle

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#24914]
How is the javascript dropdown supposed to work?

I've spent some time trying to figure it out, mostly running into the same issues described here:

https://github.com/twbs/bootstrap/issues/22835
https://github.com/twbs/bootstrap/issues/24672

I have produced some of my issues/findings here:

https://jsfiddle.net/01wxw4L8/1/

Basically, I can't get reliable dropdown opening through javascript.

**Comment by 719media** [comment]
So, it appears the "test button 2" way of doing the dropdown is the proper way. The issue at hand here is that after calling "toggle", popper attached some events that immediately remove the dropdown.

One method around this is to add e.stopPropagation(); to the click event like so:

https://jsfiddle.net/g09bzzzw/10/

Not sure if that's something that really needs fixing... but it definitely caught me off guard. Perhaps the dropdown could be attached after a setTimeout({}, 1) or something... but that may cause other problems.

**Comment by Johann-S** [comment]
Yep your `test button 2` is the proper way to toggle your dropdown programmaticaly 👍 

I'll close your issue because it seems they are no issue here
