### ISSUE TITLE
Add explicit Firefox entry to browser list

### ISSUE THREAD

**Issue by retyui** [twbs/bootstrap#24911]
I look the current [browser list](http://browserl.ist/?q=Chrome+>%3D+45%2C+Firefox+ESR%2C+Edge+>%3D+12%2C+Explorer+>%3D+10%2C+iOS+>%3D+9%2C+Safari+>%3D+9%2C+Android+>%3D+4.4%2C+Opera+>%3D+30)

And I have one question: why do you support only one version of the firefox browser?

![image](https://user-images.githubusercontent.com/4661784/33378131-ed104c6e-d524-11e7-8fc2-169299f94b27.png)

**Comment by fchiumeo** [comment]
[Firefox ESR](https://www.mozilla.org/en-US/firefox/organizations/)

**Comment by mdo** [comment]
Yup, it's the only one that really needs explicit stating I think, though maybe we should add an entry for the non-ESR version @XhmikosR?

**Comment by XhmikosR** [comment]
You mean the fast that the current browser list doesn't include an entry for FF? I guess that's a mistake and we should add an entry like we do with Chrome.

We also need an entry for FF ESR like we already have.

**Comment by XhmikosR** [comment]
@mdo ba3fb3c98f170636e36dd34c949d63f2e1113f67

**Comment by mdo** [comment]
@XhmikosR Yup, `package.json` and `postcss.config.js` are both missing a dedicated FF entry.

**Comment by XhmikosR** [comment]
The browser list is in the package.json.

Feel free to add one and ping me.

**Comment by XhmikosR** [comment]
@mdo: which FF version should I use?

Note that that's why it's advised to use something like `last 2 major versions`.
