### ISSUE TITLE
Feature request: col-form-label should have optional size classes

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#24917]
- Operating system and version: Any
- Browser and version: Any
- Bootstrap V4

Currently, `.col-form-label` and two helper classes for sizing `.col-form-label-sm` and `.col-form-label-lg`, so that the label can be matched with the form-control's sizing.

When using a `<fieldset>` to group related controls in a form-group, one uses the `<legend>` element to label the group of inputs, and one can use the corresponding class `.col-form-legend` to style the legend. 

Unfortunately there are no helper classes `.col-form-legend-sm` or `.col-form-legend-lg` to control the legend text size so that it matches up with the form-control size or other `col-form-labels` that may be in the same  form.

I have tried applying the `.col-form-label-sm` (or `-lg)` classes to the `<legend>` along with `.col-form-legend`, but it does not work, due to the order of the definition of the CSS rules which make `.col-form-legend`'s font size overrule `.col-form-label-sm`

Maybe just simply moving the `.col-form-legend` CSS rule before the `.col-form-label-{size}` rules would suffice?

**Comment by tmorehouse** [comment]
PR #24932 adds in two size classes for horizontal form-group legend elements

**Comment by mdo** [comment]
> Maybe just simply moving the .col-form-legend CSS rule before the .col-form-label-{size} rules would suffice?

Why do the PR if this would've sufficed? I'd prefer the simpler rearrangement vs a whole new suite of modifier classes.

**Comment by tmorehouse** [comment]
There are a few differences between table and legend, when I checked the latest `_forms.scss`, where `.col-form-label` includes a calculation to add on the input border widths, while the `.col-form-legend` class doesn't.

If they were identical styling, it would be just a matter of moving the base `.col-form-legend` class above the label definitions.

**Comment by tmorehouse** [comment]
The question is, why couldn't legend and label use the same classes (`.col-form-label` & `.col-form-label-{size}`) and forgo the use of a special class for `.col-form-legend`?

**Comment by mdo** [comment]
Yeah, I feel that. Just tested it—can you make that change? Let's drop `.col-form-legend` and move the `font-size` reset to `.col-form-label` as `font-size: inherit`.

**Comment by mdo** [comment]
Maybe there's something more in the log as to why it needed to be another class?

**Comment by tmorehouse** [comment]
OK, I'll make some tweaks

**Comment by tmorehouse** [comment]
It appears `.col-form-legend` (when it was called `-form-control-legend`) was added in this commit https://github.com/twbs/bootstrap/commit/727722da59d16e421851dbc5d11bcd652ef55d97#diff-55562cf68df408880356390d08c7a3cb but no real explanation why it is not the same as `.col-form-label`

**Comment by tmorehouse** [comment]
`.col-form-legend is now gone altogether (and form docs updated)

For backwards comparability, would it be good to specify both class names?

```css
.col-form-label,
.col-form-legend {
 /* ... */
}
```

**Comment by mdo** [comment]
> For backwards comparability, would it be good to specify both class names?

Not necessary—we're still at beta, so we can break things.
