### ISSUE TITLE
Nav Toggleable show event not firing on Android device.

### ISSUE THREAD

**Issue by bmartinGithub** [twbs/bootstrap#24927]
Bootstrap: 4 beta 2
OS: Android 26? 27 
Device: Galaxy S7 and Emulator
With a togglable nav the show event does not seem to be called on androids. I noticed popup modals also do not work.

What it does? 
Click on the collapsed Icon, i.e. the Hamburger Icon and nothing opens|shows. 

What is expected?
 Click on the collapsed Icon, i.e. the Hamburger Icon the navigation menu displays.

I have an example at: 
www.roaringbrookbaptistchurch.org/RBBC/public

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bmartinGithub** [comment]
Ok I'm not sure if this is displaying the same issue since I don't have an Android to test with at the moment. I only noticed it on the Android or using the Emulator to view the site.

https://jsbin.com/jafufac/edit?html

**Comment by patrickhlauke** [comment]
the roaringbrook site in Chrome/Windows gives the following error in console:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js' with computed SHA-256 integrity 'GIa8Vh3sfESnVB2CN3rYGkD/MklvMq0lmITweQxE1qU='. The resource has been blocked.
```
So not purely an Android problem, but perhaps a problem with MaxCDN? @XhmikosR @mdo

**Comment by XhmikosR** [comment]
Nothing to do with us or BootstrapCDN for that matter. The site is using the wrong SRI hash, thus it's being blocked.

**Comment by XhmikosR** [comment]
The right script is this:

```html
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
```

**Comment by XhmikosR** [comment]
Closing since it's not our issue.
