### ISSUE TITLE
bootstrap 4 beta 2 css issue

### ISSUE THREAD

**Issue by Li0nardO** [twbs/bootstrap#24925]
Using netbean IDE 8.2 with WAMP server

Both bootstrap.css and bootstrap.min.css have the same issues

issue 1: unexpected token error found
:root {
--blue: #007bff;
--indigo: #6610f2;

issue 2 (line 5492): unexpected token LPAREN/ WS/ RPAREN found
@supports ((-webkit-transform-style**:** preserve-3d) or (transform-style: preserve-3d)) {
.carousel-item-next.carousel-item-left,
.carousel-item-prev.carousel-item-right {
-webkit-transform: translate3d(0, 0, 0);
transform: translate3d(0, 0, 0);
}
};

I'm not using scss to install boostrap, I just need to copy-paste js/css files into my project

**Comment by mdo** [comment]
I'd suggest filing an issue with netbean or WAMP—our source and compiled CSS works in our editors and build tools.
