### ISSUE TITLE
Add Edge for Android and iOS to supported browsers?

### ISSUE THREAD

**Issue by xfq** [twbs/bootstrap#24929]
In https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/#mobile-devices, Microsoft Edge for Android and iOS are currently "N/A".

Microsoft has announced Edge for Android and iOS, using Blink and WebKit respectively: https://blogs.windows.com/msedgedev/2017/10/05/microsoft-edge-ios-android-developer/

**Comment by Johann-S** [comment]
As it mentionned in your article : 
> You can expect that, from a compatibility perspective, Microsoft Edge for Android will match the version of Chrome that is currently available for Android.


So, IMO we can update our documentation to say it's supported
