### ISSUE TITLE
show class on expanded collapse and nested navlinks are all active

### ISSUE THREAD

**Issue by QuantumHive** [twbs/bootstrap#24928]
- Bootstrap version: 4.0.0-beta.2
- Operating system and version: N/A, but Windows 10
- Browser and version: N/A, but tested on Chrome 62 and Firefox 57
- Reduced test cases: https://codepen.io/anon/pen/zPyjKX

In [`_navbar.scss`](https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/scss/_navbar.scss#L279) you can observe the following line of code:

```
.show > .nav-link {
    color: $navbar-dark-active-color;
}
```

and in [`_nav.scss`](https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/scss/_nav.scss#L79):

```
.show > .nav-link {
    color: $nav-pills-link-active-color;
    background-color: $nav-pills-link-active-bg;
}
```

Now these `.show` classes represent an active `.nav-link` just like `.nav-link.active`.
As you might know, [collapse](https://getbootstrap.com/docs/4.0/components/collapse/) also has the `.show` class to expand it's content.

Now whenever you have a collapse inside a (navigation) menu (e.g. `.nav-pills` or `.navbar-nav)` and that collapse has nested menu items (e.g. `.nav-link`), all items inside that collapse gets and active style when expanded. You can see the effect in the [codepen](https://codepen.io/anon/pen/zPyjKX) I've provided.  

I think this is a bug, because I _expect_ that the developer should be able to mix and match the collapse with the navigation menu. My _expectation_ for highlighting an active state is only when you use the `.active` class.
An improvement would be to **not** use the same `.show` class for two different components (collapse and navmenus), but that each component have different names for their corresponding functionality (perhaps just ditch the `.show` class on navs?).

In the codepen I've also written css styling which has been commented out. In our application, we've included that styling to unset the `.show` colors and then reset the `.nav-link` colors as a **workaround**:

```
.nav-pills {
    .show > .nav-link {
        background-color: unset;
        color: unset;
    }

    .nav-link.active {
        color: $nav-pills-link-active-color;
        background-color: $nav-pills-link-active-bg;
    }
}

.navbar-dark {
    .navbar-nav {
        .show > .nav-link {
            color: unset;
        }

        .show > .nav-link {
            color: $navbar-dark-color;
        }

        .active > .nav-link,
        .nav-link.show,
        .nav-link.active {
            color: $navbar-dark-active-color;
        }
    }
}
```

**Comment by mdo** [comment]
Why are you using the collapse to make dropdowns?

**Comment by QuantumHive** [comment]
Because our customer wants a vertical navigation menu and wants the same effect as the collapse rather than the dropdown. So we thought we could achieve this with pure Bootstrap classes. The desired visual result:

![capture](https://user-images.githubusercontent.com/2554952/29603040-e116c08a-87e2-11e7-91b4-d051d9fd17fc.PNG)

I'd like to **note** that in v-4.0.0-alpha.6 this issue didn't arise. The `.show` class was applied to `.nav-items` for [`.nav-pills`](https://github.com/twbs/bootstrap/blob/65ffb1c3b6e94440812a2e228cb8e8be512652ec/scss/_nav.scss#L81). And for the `.navbar` there was no `.show` class, but there was an [`.open`](https://github.com/twbs/bootstrap/blob/65ffb1c3b6e94440812a2e228cb8e8be512652ec/scss/_navbar.scss#L249) class.

**Comment by mdo** [comment]
That's a great solution to that. My only suggestion for a workaround in v4 is an extra `<div>` inside that collapse. See https://codepen.io/emdeoh/pen/KZWdxZ.

We standardized our "active" states for the JS behaviors to a single class for all components—it was previously guess work and inconsistent. I don't see us changing this, or changing our approach to selectors again until we absolutely have to. And that'd be for v5 at this point :).

Hope that helps!
