### ISSUE TITLE
Dropdown got clipped by fixed-top navbar, 4 alpha 6 -> 4 beta 2 regression

### ISSUE THREAD

**Issue by shine-on** [twbs/bootstrap#24920]
Please run codepens

4 alpha 6 - https://codepen.io/anon/pen/EbOGGK
4 beta 2 - https://codepen.io/anon/pen/ooQJZL

Expected: while opened, dropdown content (no matter how long it is) should be populated downwards (it's a drop**DOWN**, right?) so there's no conflict with fixed-top navbar.

Reality: with 4 beta 2, while opened,  dropdown (with relatively long) content got populated both upwards and downwards, clipped by fixed-top navbar as a result.

**Comment by Johann-S** [comment]
Seems a bit better with the use of `data-flip="false"` but it's a positioning issue here
https://codepen.io/Johann-S/pen/wPQNLa

/CC @FezVrasta

**Comment by FezVrasta** [comment]
I think you should change the flip strategy to be something like `['bottom', 'top', 'bottom']`, doing so if there's no space on both sides, it will get back to the initial placement (bottom)

**Comment by shine-on** [comment]
@Johann-S, dropping strictly down (or strictly up, if instructed so) without any additional bells and whistles - is the **expected** dropdown behaviour for the most of the world.

**Comment by FezVrasta** [comment]
Actually all the native dropdowns (`<select />`) will try to stay in the viewport (and flip if necessary)

**Comment by shine-on** [comment]
@Johann-S, your codepen doesn't solve anything and simply moves a problem to other place: now dropdown button is clipped. It isn't *better*, it's the same: dropdown isn't droppingg down, it's dropping "somewhere close to that direction".

@FezVrasta, your statement about SELECTs is an attempt to push "hey, all previous bootstrap versions did dropdown wrong" agenda.

**Comment by FezVrasta** [comment]
No, I'm talking about the native dropdowns provided by the operative systems

**Comment by shine-on** [comment]
@FezVrasta, before referring to SELECTs, try this out https://codepen.io/anon/pen/dZQrwP in various browsers with different viewport heights.

And, in the end of the day, so called "native dropdowns", either drop up or drop down, and neither both directions (which is the case here).

**Comment by shine-on** [comment]
@Johann-S, try to play with your codepen by adjusting result window height while dropdown is opened. Compare with my 4 alpha 6 codepen.

**Comment by mdo** [comment]
@FezVrasta @Johann-S There is something wrong with our current dropdowns here. In the Beta 2 example, I cannot see the first two dropdown items. We either need to document a solution here—some `overflow-y: auto` could work for just CSS—or improve dropdown menus so that they do not exceed the visible viewport.

**Comment by Johann-S** [comment]
Yep I'll try what @FezVrasta suggested

**Comment by 719media** [comment]
The only consistent way I can avoid the behavior shown in the examples with beta.3 bootstrap is if I set preventOverflow.enabled = false in popper. Unfortunately, this option is not exposed in bootstrap and so the fix cannot be applied easily.

If you set `flip.enabled = false;` (which bootstrap exposes by setting data-flip="false"), the menu appears OK initially on first load, but as you scroll the preventOverflow default behavior of popper manifests the issue again.

I attempted to use `flip.behavior = ['bottom', 'top', 'bottom'];` which has the same affect as  `flip.enabled = false`, that is, initially, the dropdown is placed appropriately, but as you scroll, the placement gets jacked up.

So, I see some solutions:

1) Do nothing, and let `position: fixed` people suffer :)
Or 2) Allow configuration of `preventOverflow.enabled` which, in combination of `flip.enabled = false` will solve problems like this
Or 3) Come up with better solution than this

Here was my jsfiddle to test this:

https://jsfiddle.net/w1x2vwet/

**Comment by 719media** [comment]
@mdo another solution here staring me in the face and didn't realize: just setting the z-index higher. I mean really, when you think about this problem, popper doesn't avoid all the various positioned fixed elements like navbar-fixed. That's an issue for z-index to solve.

I'm not familiar with why the z-index values were selected the way they were for bootstrap: https://getbootstrap.com/docs/4.0/layout/overview/#z-index

So I'm not sure why $zindex-dropdown is lower than $zindex-fixed and $zindex-sticky

**Comment by tillmon** [comment]
> So I'm not sure why $zindex-dropdown is lower than $zindex-fixed and $zindex-sticky

Is there any explanation?

**Comment by mdo** [comment]
> So I'm not sure why `$zindex-dropdown` is lower than `$zindex-fixed` and `$zindex-sticky`

So that when you scroll a page with a fixed/sticky navbar, the dropdowns from within the page don't overlap the navbar.

Given the age of this issue, and the fact that it only seems to happen with extensively long dropdowns, I'm inclined to close as stale/wontfix. This can be worked around with a `max-height` and `overflow-y: auto`, too fwiw.
