### ISSUE TITLE
Grid system order classes not even working on Bootstrap's own documentation page?

### ISSUE THREAD

**Issue by BrianWeb** [twbs/bootstrap#24936]
Hello,
Thanks for reading this and thanks to all those who contribute and support Bootstrap. Quick question, re. V4x and 4 Alpha, at:

https://getbootstrap.com/docs/4.0/layout/grid/#vertical-alignment

The second column says 'Third, but first'. Is it not in fact the second column? Can't seem to get 
'col order-1' (or col order-*) working.

Sorry if this question has been raised before. Couldn't find any reference to it.

Thanks for reading.
Brian
![bootstrap vertical ordering](https://user-images.githubusercontent.com/1760507/33528069-54e9d9aa-d853-11e7-8bfe-efdae482ef31.jpg)

**Comment by onneri** [comment]
This example is under the order columns section, the vertical section is before that.
And regarding to the ordering, the first column doesn't have order, so has priority, then the columns with class col-order-*, that's  why the appear after the col with no order class, so the order apply to the set of columns that has the "col-order" class, you can use order-first to force appear before the others because it applies an order -1 to the column

**Comment by BrianWeb** [comment]
Hi Onneri, sorry for late reply. Just saw your message. That solves it, thanks very much. I've changed the question title to what it should be. 
Brian

**Comment by tmorehouse** [comment]
@BrianWeb the documentation is working as expected. Anything **without** an explicit class `order=*` (which adds the CSS styke  `order: #;`) will always appear first, before anything that does have `order: #` set, as @onneri has mentioned above.

**Comment by BrianWeb** [comment]
Thanks tmorehouse for explaining that. Personally I think your and  onneri's explanations are more comprehensive than the explanation on Bootstrap's website, as it's hard to see where it says that not giving a div an order, means it will appear before divs with an order.  Also the text 'Third, but first' might be clearer if it said something like 'Third written div, ordered first, placed second'. Thanks again guys.

**Comment by onneri** [comment]
@BrianWeb, I think you're right, a clearer text could be helpful and can save time figuring out how order works on divs that has no order class
