### ISSUE TITLE
reapplying Modal applies additional background fade

### ISSUE THREAD

**Issue by brettwinters** [twbs/bootstrap#24939]
Hello

I'm using asp.net. When I postback, I need to re-show the modal 

`$('#xxxx').modal('show');`

The model is re-shown, but the background darkening is re-applied. So if you repeat the "show" the background becomes black. 

To solve this issue, if I re-show the model, I first need to remove the class 

`$('.modal-backdrop').removeClass('modal-backdrop');`

Why can't Bootstrap check to see if the class is already applied before adding the class?

Regards

Brett

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by brettwinters** [comment]
Unfortunately, I can't simulate an asp.net postback in jsbin, but here goes 

[](https://jsbin.com/gelisuriju/edit?html,js,console,output)

Process:
(1) show the modal from asp.net 
`$('#modalClaimAdd').modal('show');`
(2) User does postback while the modal is open (by clicking a button inside the modal)
(3) I do some work in codebehind to process the event
(4) then re-show the model
(5) background gets darker. 

The fix is to remove the class before before showing the modal again, so step (4) becomes:
`$('.modal-backdrop').removeClass('modal-backdrop');
$('#modalClaimAdd').modal('show');`

Regards

Brett

**Comment by danijelGombac** [comment]
Why you don't hide the modal before show it again?

**Comment by brettwinters** [comment]
for some unknown reason cyling 

```
$('#modalClaimAdd').modal('hide');
$('#modalClaimAdd').modal('show');
```
Using ScriptManager.RegisterStartupScript disables the show

But that's not my point. I have a workaround in place by removing the class, but just wondering if this is a bug.

**Comment by mdo** [comment]
I think it makes sense that you're not actually removing the first modal, but adding another. As such, the backdrop continues to be darkened. Any further thoughts from @Johann-S or @bardiharborow on the JS side for us?

---

Random side idea for a future update, I'm curious if we could generate the backdrop from `.modal::after` or something?

**Comment by Johann-S** [comment]
Sorry I followed your steps and maybe I misunderstood something but your modal is still visible so what's the reason you're calling again `show` on this modal ?

**Comment by brettwinters** [comment]
sorry for my late response - tied up with the usual family stuff this time of the year haha. 

I'm using asp.net so an event triggered by one of the web controls on the modal causes a postback. This causes the modal to disappear. That's why I need to reload the modal from the code-behind.

**Comment by XhmikosR** [comment]
@Johann-S is this still valid?

**Comment by brettwinters** [comment]
I worked around this issue by doing an asynchronous postback inside the modal content.
