### ISSUE TITLE
Navbars appear by default when printing, contrary to stated documentation

### ISSUE THREAD

**Issue by jacroe** [twbs/bootstrap#24931]
In the documentation for navbars, [it's stated](http://getbootstrap.com/docs/4.0/components/navbar/#how-it-works) that, by default, navbars are hidden when printing unless a `.d-print` class is added. This seems to run contrary to what I've experienced so far.

When using one of the example navbar HTML, the navbar still appears when going to print. I've included a screenshot of the print preview and the HTML file I used.

![image](https://user-images.githubusercontent.com/1142635/33498359-0b848a0e-d69f-11e7-8535-69914f366ee9.png)
[example-navbar-printing.txt](https://github.com/twbs/bootstrap/files/1522601/example-navbar-printing.txt)

This is happening in Chrome 62, Firefox 57, Internet Explorer 11, and Edge 25.

This may be related to #23489, #23864, and #23992, but those seemed to be more focused on content and not the navbars.

**Comment by Klooven** [comment]
I have the same problem (using Edge).

_I think_ something is overriding it, beacuse it's not using `!important` in the CSS:

https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/dist/css/bootstrap.css#L38

https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/dist/css/bootstrap.css#L77-L79

Using the class `d-print-none` hides it **correctly** (it declares `!important`):

https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/dist/css/bootstrap.css#L6033-L6037

(code from the **`v4.0.0-beta.2`** tag)
