### ISSUE TITLE
Alert and modal close button has dotted outline on focus

### ISSUE THREAD

**Issue by MoritzBru** [twbs/bootstrap#24937]
The close button of alerts and modals has a dotted outline when focused.
Observed in the [docs](https://getbootstrap.com/docs/4.0/components/alerts/)

I don't know if this is desired behavior but i think `.close:focus` should have `outline: 0;`

**Comment by patrickhlauke** [comment]
it's intended behavior, as just relying on the subtle color change is not quite sufficient to let keyboard users know if their focus is on the button or not.
