### ISSUE TITLE
.col-form-label with .form-control-sm, .form-control-lg don't line up correctly

### ISSUE THREAD

**Issue by kiranvj** [twbs/bootstrap#24930]
.col-form-label with .form-control-sm, .form-control-lg don't line up correctly

Please check the pen at https://codepen.io/kiranvj/pen/wPRQbJ

![image](https://user-images.githubusercontent.com/3539487/33490052-ce818b74-d6db-11e7-8c39-3930f3558431.png)

Operating system and version : Win 10
Browser and version : Chrome 58.0

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L82-L107 and https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form-label-sizing
