### ISSUE TITLE
Modal adding 16px padding to body

### ISSUE THREAD

**Issue by myorangeca** [twbs/bootstrap#24934]
Activating bootstrap modal is auto adding  padding-right:16px value to the body element of the page. The padding is messing up some of my styles. 

Is there a particular reason why the padding was added? 
Is there a way to disable the padding without adding important values to the body css?

**Comment by Ghost180195** [comment]
This is the width of the scrollbar. In different browsers the width is different. It seems to me that the padding is added, so that when the scrollbar is hidden, the contents of the page do not jerk (mostly in desktop browsers).

**Comment by myorangeca** [comment]
That part I understood, but my page has a custom scrollbar and has a different width. So it ends up producing a jerk motion. Which is why I wanted to turn this feature off. We did not have this feature for v3 (I think?)

**Comment by Ghost180195** [comment]
This feature exists also in v3.

**Comment by myorangeca** [comment]
@Ghost180195 You are right. I guess I must have missed it and thought it was a new feature.

**Comment by mdo** [comment]
Since this hasn't been described as a bug, just a confusion around the behavior, closing out. If there's a bug around it, please open a new issue with a live example.
