### ISSUE TITLE
Bootstrap doesn't build the grid using screen-xs

### ISSUE THREAD

**Issue by DarrenMack-OD** [twbs/bootstrap#24942]
It's just been noticed that when compiling Bootstrap 3.3.7 you don't use $screen-xs to build the grid/visible classes/responsive utilities.

In my mind it would seem more appropriate for the breakpoints to be like this; 
screen-xs = 0px - 768px
screen-sm = 769px - 992px
screen-md = 993px - 1200px
screen-lg = 1201px +

**Comment by DarrenMack-OD** [comment]
thank you my friend :)

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
