### ISSUE TITLE
qunitjs Deprecated in package.json

### ISSUE THREAD

**Issue by venusvavadiya** [twbs/bootstrap#24945]
I just want to suggest Bootstrap team to update **qunitjs** dependency to **qunit** because it is deprecated and name needs to be referred to new package name.

Log when I ran `npm install`

npm WARN deprecated qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.

**Comment by XhmikosR** [comment]
There is nothing we can do unfortunately. Plus I have already opened an
issue upstream a few days ago. So if anyone wants this fixes you should
comment / submit patches there.

**Comment by XhmikosR** [comment]
For reference: https://github.com/jonkemp/node-qunit-phantomjs/issues/30

**Comment by venusvavadiya** [comment]
Got it. Thanks for your support!
