### ISSUE TITLE
What is left to do with BS4?

### ISSUE THREAD

**Issue by DarrenMack-OD** [twbs/bootstrap#24944]
Hi guys,
You've done a fantastic job so far, and I was just wondering what was left to do with BS4...

**Comment by Herst** [comment]
For beta 3 have a look at https://github.com/twbs/bootstrap/projects/10

**Comment by mdo** [comment]
Yeah, just working through some final breaking changes. It takes a lot of energy and time to make sure we don't screw up some important markup changes around our forms. I'm close to that, but still need some time.
