### ISSUE TITLE
Select adds height to card body in Chrome

### ISSUE THREAD

**Issue by seveves** [twbs/bootstrap#24948]
When hovering over a select that is placed in a ```card```'s ```card-header``` then the height of the corresponding ```card-body``` increases. The problem only occurs in my Chrome browser in version 62.0.3202.94. The problem does not occur in Firefox 58.0b8 (64-Bit). I'm running Windows 10 and I'm using bootstrap v4 beta2 as you can see in the attached codepen.
![slider](https://user-images.githubusercontent.com/4233173/33606607-4eabb2d6-d9be-11e7-8b35-3ab2f1338871.gif)

I've added an example to codepen:
https://codepen.io/seveves/pen/XzQXYP?editors=1000

**Comment by andresgalante** [comment]
Hi @seveves this is a super strange bug, it seems to be in Chrome to me.

It's trigger by the ` h-100` class on `card`. It'd be great to reduce this codepen down to exactly what's needed to show the bug and report it to Chrome. what do you think?

also consider using `d-flex justify-content-between` on the header instead of the `ml-auto`

**Comment by seveves** [comment]
@andresgalante https://codepen.io/seveves/pen/MORjNB
I also sent a bug report via Chrome.
A workaround could be to remove the ```text-decoration: none;``` from the ```select``` on ```:hover```

**Comment by andresgalante** [comment]
👍  thanks a lot!

**Comment by seveves** [comment]
imho we can close this issure because it is not related to bootstrap

For your information:
https://bugs.chromium.org/p/chromium/issues/detail?id=792344

**Comment by Johann-S** [comment]
we can at least add it to our wall of browser bugs

**Comment by mdo** [comment]
Closing this out since it's an old issue, not a Bootstrap bug, and the `.custom-select` has been heavily redone in v5 so that it shouldn't impact things here.
