### ISSUE TITLE
Select issue in IE and Edge

### ISSUE THREAD

**Issue by StewBash** [twbs/bootstrap#24953]
I posted this issue before, but it was closed because I did not provide enough information... The issue occurs in IE and Edge... Chrome works fine!

This example is off the Bootstrap 4 documentation... components... forms... 

The list starting position is not below the select and is outlined with a black box. In addition, the list starting position moves after selection is made.

```
<div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
```

**Comment by patrickhlauke** [comment]
both are native IE/Edge behaviors when it comes to `<select>` elements. they cannot be suppressed/changed unless you build your own custom pretend selects, which we're not intending to do for Bootstrap I'm afraid.

![capture](https://user-images.githubusercontent.com/895831/33635936-e30be308-da11-11e7-9690-7c5b96c2ee13.PNG)

**Comment by StewBash** [comment]
This is odd behavior... I have not seen this behavior before. I have several Bootstrap 3.3.7 applications running and I do not see this in IE, or Edge... this is NOT native behavior from what i can see. 

Because this is such a "basic" input element on a prominent browser base, this is a deal breaker for me using Bootstrap v4...

thanks for the feedback!

**Comment by wolfy1339** [comment]
I just tested this, and this is native behaviour

**Comment by StewBash** [comment]
Thank you for the confirmation... I also tested this... my bad! this is native behavior from what I can see as well...

My apologies! I am new to the GUI side... I have been the DB, Web Service, Infrastructure guy... newly converted. So far, I hate this front end stuff, although I have to say that Bootstrap 4 has taken a lot of the layout issues and made it manageable!

It appears that the previous guy used a custom control for this...
