### ISSUE TITLE
form-validation-state mixin should allow other state classes

### ISSUE THREAD

**Issue by dietergeerts** [twbs/bootstrap#24950]
The `form-validation-state` mixin now assumes that the `$state` parameter is a pseudo selector and adds the selector and a class `is-{$state}`. This is not ok in a sense that we can't re-use this mixin now, it only works for those instances. In my current project, we use AngularJS, where the invalid class is `ng-invalid`, so I want to re-use this mixin to have that class instead of `is-invalid`. I could copy the selectors, but if those change, my code will fail.

I saw similar issues with several other mixins, where they are too spicific to easily be re-used. I think this is bad practice, and the framework would benefit from a more general approuch. You can use optional arguments for the default, so I don't see a reason to not make them better re-usable.

So this is a feature request to update this mixin in order to re-use it for other purposes.

**Comment by mdo** [comment]
Negative, these mixins are built primarily around HTML5 form validation—`:valid` and `:invalid`. The goal isn't to allow the most customization here, it's to encourage folks to use newer browser functionality instead of rolling our own custom implementations.

**Comment by dietergeerts** [comment]
@mdo , I agree that we should encourage the use of the browser functionality, but not every framework does use it, so for those cases, and more in general, it should be possible to better use the mixins. It's not about opinion here, it's about the mixins being too restrictive and not re-usable. The ones for buttons are even more restrictive, so you can't add extra buttons easily....
