### ISSUE TITLE
Set `cursor: pointer` for interactive elements

### ISSUE THREAD

**Issue by printercu** [twbs/bootstrap#24954]
In #21812 @mdo provided links which says that pointer cursor should be used only for links. 

Both [Microsoft's design guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466%28v=vs.85%29.aspx) and [Apple's HIG](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Pointers.html) are related to desktop applications. While [W3C spec](https://www.w3.org/TR/CSS21/ui.html#propdef-cursor) is related to web, it does not follow it's recommendation: all provided sources use cursor pointer for buttons on their web pages, some of them for checkboxes (ex.: [Apple](https://appleid.apple.com/account#!&page=create), [Microsoft](https://login.microsoftonline.com), [W3C](https://www.w3.org/)).

There are some issues with having `cursor: pointer` for links but not for buttons.

1. It's usual to have controls in forms like this:
```html
<button class='btn btn-primary' type='submit'>Save</button>
<a class='btn btn-secondary' href='/back'>Cancel</a>
```

This way both controls looks the same, but have different cursors. This looks inconsistent.

2. `.navbar-toggler` is good example when it's not clear if element is interactive or not: https://getbootstrap.com/docs/4.0/components/navbar/#external-content

### Why desktop application design guides should not be used for web pages?

The main difference is that web-page contains mostly static content (not-interactive) but desktop app usually almost totally interactive (this should be considered in global scale, not for single web-site that can be fully interactive: users use browser to visit different web-sites). So it has become usual to use pointer cursor to help users distinguish interactive elements on webpages. Especially with custom-styled inputs.

Please consider to set back pointer cursor for interactive elements.

**Comment by Herst** [comment]
Somewhat related discussion in #24156.

**Comment by Gredys** [comment]
I completely agree with the author. Interactive elements MUST have CURSOR on web pages. Otherwise, this will mislead users regarding the interactivity of the elements. Do not confuse desktop applications and web pages - these are completely different things.
