### ISSUE TITLE
Hiding element not working as expected.

### ISSUE THREAD

**Issue by berpcor** [twbs/bootstrap#24955]
<div class="col-xs-2 d-none d-xs-block d-md-none" >
	    Something
    </div>

As I understand div should be visible on xs and sm breakpoints. **d-none** stands for hide all from xs to xl. **d-xs-block** stands for show as block xs and above, **d-md-none** stands for stop showing element starting from md including it.

But the block doesn't show up at all. What is the problem?

**Comment by andresgalante** [comment]
Hi @berpcor you are overdoing it.

By default any div will be block, `d-md-none` will remove it on `md` and up:

https://codepen.io/andresgalante/pen/pdmjyX?editors=1000

**Comment by mdo** [comment]
There is no `.d-xs-block`. You're `.d-none` is applying for the first grid tier (xs). You want `d-none d-sm-block d-md-none` or the equivalent.
