### ISSUE TITLE
No separation of button and form element styling

### ISSUE THREAD

**Issue by geoffbeaumont** [twbs/bootstrap#24966]
The form fields in bootstrap4 share a number of variables with buttons (e.g. $input-button-focus-box-shadow) - this means for most sites it's either necessary to replace the bootstrap buttons or forms SCSS file(s) with custom versions, or to override the styles in additional custom CSS. This shouldn't be necessary - they should have separate variables. One set can default to being set from the other to allow the same default build, but the buttons and form fields can then be styled separately just by setting variables.

**Comment by mdo** [comment]
These were split in v4-dev. Coming in Beta 3.

**Comment by geoffbeaumont** [comment]
Brilliant! Thanks.
