### ISSUE TITLE
Pattern inconsistency in dropdowns 

### ISSUE THREAD

**Issue by rloos289** [twbs/bootstrap#24968]
All of the dropdown [examples](http://getbootstrap.com/docs/4.0/components/dropdowns/) have the `btn` class applied to the buttons they use. 

```
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>
```

The [Navbar](http://getbootstrap.com/docs/4.0/components/navbar/) dropdowns are inconsistent with this pattern and do not have the `btn` class. 

```
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
```

This is causing a problem for our design system because adding the `btn` class to these dropdowns causes styling issues like the text centering below. 
![screen shot 2017-12-07 at 1 17 17 pm](https://user-images.githubusercontent.com/19877994/33739182-fa084868-db50-11e7-8722-b3698fa3b20c.png)

**Comment by Johann-S** [comment]
The only requirements to use our dropdowns it's : 
- You must have a wrapper with `.dropdown` class
- You must have a button or a link with `data-toggle="dropdown"` (inside the wrapper)
- You must have a div with `.dropdown-menu` (inside the wrapper under the element which trigger the dropdown)

```html
<div class="dropdown">
  <button data-toggle="dropdown">Dropdown</button>
  <div class="dropdown-menu">
    <!-- some items here -->
  </div>
</div>

**Comment by mdo** [comment]
You don't need the `.btn` on all dropdown toggles—only dropdown toggles that are buttons. When used with navs, only add `.dropdown-toggle` to the anchor.
