### ISSUE TITLE
Add support for bower 

### ISSUE THREAD

**Issue by elizad** [twbs/bootstrap#24963]
Add support for bower 
- because there are a lot of projects that are using Bower instead NPM 
- Bower is not dead yet and it's having many of years because Bower js is better than NPM  for managing front end components like html, css, js etc.

**Comment by Johann-S** [comment]
Sorry @elizad but we won't use Bower again, because we plan our next release to ship our components in differents package and it's not possible with Bower.

See : https://github.com/twbs/bootstrap/pull/23568 for more details
