### ISSUE TITLE
How to chang order of col-xs-12 blocks?

### ISSUE THREAD

**Issue by berpcor** [twbs/bootstrap#24961]
<div class="row d-flex">
        <div class="col-xs-12">1</div>
        <div class="col-xs-12">2</div>
        <div class="col-xs-12">3</div>
    </div>

I need to change order. 2-nd should be the first and opposite.
    
    <div class="row d-flex">
        <div class="col-xs-12 col-sm-4 order-xs-2">1</div>
        <div class="col-xs-12 col-sm-4 order-xs-1">2</div>
        <div class="col-xs-12 col-sm-4">3</div>
    </div>

This variant doesn't work. Why?

http://jsfiddle.net/x1hphsvb/352/

Example from docs doesn't even work - http://jsfiddle.net/x1hphsvb/353/

> (https://v4-alpha.getbootstrap.com/utilities/flexbox/#order)

**Comment by tmorehouse** [comment]
Columns without orders take precedence over columns with orders specified.

See http://getbootstrap.com/docs/4.0/layout/grid/#reordering (this this is v4.bet.2 not V4.alpha.6)

Also note for `xs` you do not specify the breakpoint (and columns are already flex items):
```html
<div class="row">
    <div class="col-12 col-sm-4 order-2 col-sm-order-1">1</div>
    <div class="col-12 col-sm-4 order-1 col-sm-order-2">2</div>
    <div class="col-12 col-sm-4 order-3 col-sm-order-3">3</div>
</div>
```

**Comment by berpcor** [comment]
http://jsfiddle.net/x1hphsvb/361/
Your example doesn't work. Why?

**Comment by patrickhlauke** [comment]
note that your fiddle uses bootstrap 4 alpha 2. we're at beta 2 now.

**Comment by mdo** [comment]
Upgrade to Beta 2 (or latest from v4-dev) and you'll be good.
