### ISSUE TITLE
grid layout:

### ISSUE THREAD

**Issue by trainsOE2** [twbs/bootstrap#24965]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by trainsOE2** [comment]
In class "row"
overlapping columns "col-md-3"
unequally spaced columns "col-md-4"

**Comment by kamlekar** [comment]
@trainsOE2 if this is question please ask on Stackoverflow. It is not clear what you are asking.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by trainsOE2** [comment]
![screenshot 5](https://user-images.githubusercontent.com/22859804/33792705-e0de7952-dccc-11e7-872b-2c4c9c5b0690.png)

version of bootstrap used... 4.0.0-beta.2

**Comment by wolfy1339** [comment]
Sorry, but screenshots won't work here. We need code posted on CodePen or JS Bin.
You also haven't provided all the details asked: What OS and version of that OS are you running?

**Comment by trainsOE2** [comment]
OS: Windows 10 Pro
Bootstrap version: 4.0.0-beta.2
Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
GitHub link:
 **header:** https://github.com/trainsOE2/WebDev/blob/master/Backend_Node/YelpCamp/v1/views/partials/header.ejs
**body:**
https://github.com/trainsOE2/WebDev/blob/master/Backend_Node/YelpCamp/v1/views/campgrounds.ejs
**footer:**
https://github.com/trainsOE2/WebDev/blob/master/Backend_Node/YelpCamp/v1/views/partials/footer.ejs

**Comment by trainsOE2** [comment]
GitHub link to project: https://github.com/trainsOE2/WebDev/tree/master/Backend_Node/YelpCamp/v1

**Comment by trainsOE2** [comment]
I just noticed... The "navbar" too isn't working!! "YelpCamp" is supposed to be the navbar brand. There are no "login", "signup", "logout" buttons that I had included in the code. I hope this should do it... :)

**Comment by fchiumeo** [comment]
[you not using bootstrap 4.0.0-beta-2 ](https://github.com/trainsOE2/WebDev/blob/master/Backend_Node/YelpCamp/v1/views/partials/header.ejs#L6)
and not using correct [navbar](https://getbootstrap.com/docs/4.0/components/navbar/)

**Comment by trainsOE2** [comment]
I am not using version 4.0.0.-beta-2 anymore because of the issues! The same code doesn't work with version 4.0.0.-beta-2.
I am sorry, this could be because I am following a tutorial for an older version of BootStrap :(
