### ISSUE TITLE
List group item heading link is dead

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#24975]
https://getbootstrap.com/docs/4.0/components/list-group/

In the side menu to the right you can see three anchor links named "List group item heading" under "Custom content", none of these works.

Dead anchor links:
https://getbootstrap.com/docs/4.0/components/list-group/#list-group-item-heading
https://getbootstrap.com/docs/4.0/components/list-group/#list-group-item-heading-1
https://getbootstrap.com/docs/4.0/components/list-group/#list-group-item-heading-2

**Comment by mdo** [comment]
@XhmikosR Did we ever have a bug report for the ToC?

**Comment by XhmikosR** [comment]
Nah, and I doubt it will ever be fixed. Yet another reason to have considered Hugo.

**Comment by mdo** [comment]
#24940 wasn't descriptive, but this was addressed there with an update to the `jekyll-toc` plugin. We have our Jekyll config set to only output a certain range of headings now.

**Comment by XhmikosR** [comment]
Yeah, sorry about that.
