### ISSUE TITLE
Download in Main Nav is for Source Code

### ISSUE THREAD

**Issue by ajfarkas** [twbs/bootstrap#24970]
Bug: The Download button on the top right in the Nav bar downloads the source code. As the default download, this should point to the compiled code, and people who want the "advanced" version should have to dig for it, not the other way around.

It's kinda hostile to newcomers.

**Comment by asyncdesign** [comment]
Have you checked the "dist" folder in the download? It contains the compiled and minimised css and javascript.

**Comment by Johann-S** [comment]
And you can find the Quick start section which should help new comers :wink: 
http://getbootstrap.com/docs/4.0/getting-started/introduction/#quick-start

**Comment by patrickhlauke** [comment]
have to admit that i agree in part with the sentiment. thinking back to my early encounters with bootstrap, it's not completely obvious as a newcomer (who just wants to make some pages and use bootstrap) what you're supposed to do with the download, to be honest. on the other hand, more experienced developers will want to have the SCSS etc. maybe to square that circle, in future we could have two separate download options: one the source, one a basic demo single-page (with an index.html, subfolder for styles, subfolder for scripts). /cc @mdo
