### ISSUE TITLE
Card or list group in an area with a dark background color

### ISSUE THREAD

**Issue by toshi0820** [twbs/bootstrap#24982]
When placing a card or list group in an area with a dark background color ( character color: white), characters are not visible.
https://jsfiddle.net/p4Lyrrrb/

**Comment by ashvin777** [comment]
Hi @toshi0820 , 

If you checkout the styles for card-title, card-body or list-items the `color` property of css inherits the color from parent. To make it work you need to add a `color:black`style property to `card` element. Just like below -

```
<div class="card" style="width: 20rem;color: black;">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>
```

Regards,
Ashvin

**Comment by tmorehouse** [comment]
Or use the utility class `text-dark` on the card element.

**Comment by toshi0820** [comment]
hi ashvin777 and tmorehouse.

Thank you for responding.

When placing .form-control and .dropdown-menu in an area with a dark background color(character color: white).
Because they are added a color style property (color: #212529) which is the same as body color.
And if I add a color: black or .text-dark to .card and .list-group, it's not the same as body color.
So I think we should add a color style property same as body color to them.

Like that 

.card, .list-group {
  color: #212529;
}
