### ISSUE TITLE
<a>-primary button color is black without "href" attribute

### ISSUE THREAD

**Issue by phip1611** [twbs/bootstrap#24983]
I'm developing angular applications, therefore I'm not using href as an attribute. This causes that the color for primary buttons is black instead of white! Reproduce it like this: `<a class="btn btn-primary">Click me</a>` 

![image](https://user-images.githubusercontent.com/5737016/33806487-399dcb36-ddc9-11e7-85dd-e26493b6b08a.png)

![image](https://user-images.githubusercontent.com/5737016/33806445-a8a44f24-ddc8-11e7-9c1f-4a064ee672ea.png)

**Comment by tmorehouse** [comment]
An `<a>` tag without an `href` is not presented to screen reader users as a link (or button for that matter).  `<a>` tags without an `href` are also not in the document tab sequence by default, making them inaccessible to keyboard only users.

I would recommend setting `href="#"` or switching to a more semantic markup such as `<button>` which will make your site usable for users of assistive technologies

**Comment by phip1611** [comment]
thanks!
