### ISSUE TITLE
Uncaught ReferenceError: Popper is not defined 

### ISSUE THREAD

**Issue by michelejolie** [twbs/bootstrap#24984]
I have an error in Browser's console that Popper is not defined  "Uncaught ReferenceError: Popper is not defined at bootstrap.min.js:6"

This is at the bottom of my index.html it's a simple form using bootstrap can you help please! 

    <script src="https://code.jquery.com/jquery-3.2.1.js"
    integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
    crossorigin="anonymous"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
   </body>
</html>

**Comment by razh** [comment]
@michelejolie You need to include Popper.js as well:

Here's the example with CDN links:

```html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
```

https://getbootstrap.com/docs/4.0/getting-started/introduction/#js

**Comment by Johann-S** [comment]
Or you can use your bundled file which contain Bootstrap dans Popper.js

```html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.bundle.min.js" integrity="sha384-3ziFidFTgxJXHMDttyPJKDuTlmxJlwbSkojudK/CkRqKDOmeSbN6KLrGdrBQnT2n" crossorigin="anonymous"></script>

**Comment by michelejolie** [comment]
Thank you, i will give that a try...

**Comment by michelejolie** [comment]
OMG! thank you!!! it worked. I appreciate your help.

**Comment by EKanadily** [comment]
so why the bundled version is not included in the download version of bootstrap? is it "not recommended"?
