### ISSUE TITLE
Any method to how z-index is implemented?

### ISSUE THREAD

**Issue by benrondeau** [twbs/bootstrap#24999]
I noticed that the implementation of `z-index` has varying values with a 1070 spread:

![bootstrap z-index](https://user-images.githubusercontent.com/5001219/33960505-8f62a214-e010-11e7-858b-134c4741321d.PNG)

I was wondering what the rationale is behind this implementation of `z-index`. There seems to be groups of content, single digit (2-15) and thousand digit (990-1070).

I ask because 1) y'all are the some of the smartest minds when it comes to css and 2) I am trying to implement some organization in my app's CSS files [using this method](https://hackernoon.com/my-approach-to-using-z-index-eca67feb079c) but it won't work with how bootstrap handles CSS.

Thanks for any insight you can provide.

**Comment by mdo** [comment]
We'll add something to the docs to explain this.

- Single digits are used for overlapping elements to "collapse" their borders (e.g., button groups). On hover/focus/active, we bring those elements to the forefront with a higher `z-index` value to show their border over the sibling elements.

- Higher values are an arbitrary range where we start to layer our own components. We need a standard set of these across our layered components—tooltips, popovers, navbars, dropdowns, modals—so we can be reasonably consistent in the behaviors. There's no reason we couldn't have used `100`+ or `500`+.

**Comment by mdo** [comment]
Turns out we had most of this covered in our layout docs, but I've clarified it further in b3e9547c5.

**Comment by benrondeau** [comment]
Thanks @mdo!!
