### ISSUE TITLE
jQuery ui close button is not shown but it works properly

### ISSUE THREAD

**Issue by cpsTinK** [twbs/bootstrap#24996]
I am using the jQuery-ui dialog and I have added the libraries:

```
<link rel="stylesheet" href="../css/jquery-ui.css">
<link rel="stylesheet" href="../css/bootstrap.min.css">

<script src="../js/jquery-3.2.1.min.js"></script>
<script src="../js/jquery-ui.js"></script>
<script src="../js/bootstrap.min.js"></script>
```

But when the dialog box appears, you can not see the close button X.

I can see it as this: https://jsfiddle.net/3wfuogvq/

Errors in console no and the button works! But is displayed incorrectly!
There may be more conflicts...

I am using: jQuery 3.2.1, jQuery-UI 1.12.1 and Bootstrap 3.3.7

**Comment by patrickhlauke** [comment]
as this is not a bug with bootstrap, but relates to your own implementation, i'd suggest asking on stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
