### ISSUE TITLE
When buttons stack, theres no space between them

### ISSUE THREAD

**Issue by Klooven** [twbs/bootstrap#24997]
When the viewport **gets small enough** for buttons to stack there isn't any space between them.

![image](https://user-images.githubusercontent.com/12278148/33950321-c5b56350-e034-11e7-8b3f-4090570b89b2.png)

This is not a problem with `btn-block`:

![image](https://user-images.githubusercontent.com/12278148/33950383-ed2aa2a6-e034-11e7-8027-8dae4a54affc.png)

I have also created a [reduced test case](https://jsbin.com/nucexowopu/edit?html,output).

I use Bootstrap 4 beta 2, and I've tested this on Edge(HTML) 15 and IE mobile for WP 8.1.

**Comment by tmorehouse** [comment]
Use responsive bottom margin class, or always set a bottom margin class on your buttons (i.e. `.mb-2`) when you know there is a chance of a series of buttons wrapping.

See the docs at: http://getbootstrap.com/docs/4.0/utilities/spacing/

**Comment by Klooven** [comment]
Yep I know that these classes are available, but **is is intended to be like that**?

As a responsive framework I'd expect that it would look "right" even on smaller screens...

**Comment by tmorehouse** [comment]
I can't answer that, but I know that is just the way it is.  I've always used margin classes to tweak things at various breakpoints, etc.

**Comment by mdo** [comment]
It's intended to be like this—we don't know the circumstances under which you use the buttons. Someone might need a margin, others might not.
