### ISSUE TITLE
Feature request: White (or light weight) background button with input group like v3

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25006]
The background of a secondary button was darken than v3, I feel "heavy" when use a secondary button into input group. To make lighter, @mdo comments in #24216:

> It looked better with the default Bootstrap button styles there

But, the default button does not have borders and hover state.

I think not a few people prefer light buttons like v3. Could you consider adding a button with a white (or light weight) background like v3? It may be similar to pagination items.

![image](https://user-images.githubusercontent.com/4065765/33975093-b8a6845a-e0cf-11e7-99db-17cde69a438b.png)

**Comment by mdo** [comment]
No plans just yet. Maybe we change the styles down the line, but for now an outline button gets you close. Perhaps we make those `border-color` values the same?

**Comment by mdo** [comment]
Punting on this since we have `.btn-outline-secondary` and that gets us pretty darn close.
