### ISSUE TITLE
Margin & padding class with Gutter

### ISSUE THREAD

**Issue by fhfournier** [twbs/bootstrap#25009]
You should have a margin and padding class who reflect the gutter!

Like mt-gutter who will have gutterX2 to reflect the same space of col

Like this!

`$grid-gutter-width: 30px;

$spacer: 1rem;
$spacers: (
  0: 0,
  1: ($spacer * .25),
  2: ($spacer * .5),
  3: $spacer,
  4: ($spacer * 1.5),
  5: ($spacer * 3),
  gutter: $grid-gutter-width
);`

**Comment by fhfournier** [comment]
Like this!

`$grid-gutter-width: 30px;

$spacer: 1rem;
$spacers: (
  0: 0,
  1: ($spacer * .25),
  2: ($spacer * .5),
  3: $spacer,
  4: ($spacer * 1.5),
  5: ($spacer * 3),
  gutter: $grid-gutter-width
);`

**Comment by mdo** [comment]
Spacers are rems, grid is pixels. Right now they don't mix. Maybe in v5.
