### ISSUE TITLE
Jekyll giving warning on Windows

### ISSUE THREAD

**Issue by wolfy1339** [twbs/bootstrap#25004]
- OS: Windows 10
When I run `npm run docs-serve`, I get this warning/recommendation:

```
 Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```

**Comment by mdo** [comment]
I don't think this is coming from anything of ours—perhaps this is something Jekyll is depending on?
