### ISSUE TITLE
Bootstrap 2 docs link "latest version" to Bootstrap 3 instead of 4

### ISSUE THREAD

**Issue by joeyscarim** [twbs/bootstrap#25003]
I accidently ended up on the Bootstrap 2 docs, i.e. http://getbootstrap.com/2.3.2/components.html and when you click the "Check out the latest version of Bootstrap!" link in the danger alert it is linked to the Bootstrap 3 docs instead of Bootstrap 4.

**Comment by wolfy1339** [comment]
Well... v3 is still the latest stable version, so theoretically it isn't completely wrong

**Comment by Johann-S** [comment]
Yep seems fine to me too :+1: 
But that's something we should update when we will release our first stable version of BS 4
