### ISSUE TITLE
Different way are used to control overlap border of `input-group-addon` between` input-group-btn` 

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25005]
Regarding overlapping of borders of a grouped element, @mdo commented in #24453 that it is not good way to control the border color. As an alternative, we can use `border-width: 0` or negative margin.

In input group, `.input-group-addon` uses **border width to 0**, and ` input-group-btn` uses **negative margin**. I think we should use a same way (negative margin), since ` .input-group-addon` and `input-group-btn` are similar in principle.

https://github.com/twbs/bootstrap/blob/9de141f42819f3ad374bf4774ddbefea7df8f950/scss/_input-group.scss#L145-L151

https://github.com/twbs/bootstrap/blob/9de141f42819f3ad374bf4774ddbefea7df8f950/scss/_input-group.scss#L165-L172

**Comment by Mrdaocao** [comment]
aaa

**Comment by ysds** [comment]
And, **RIGHT SIDE** `.input-group-btn > .btn + .btn` has double border;

https://jsfiddle.net/35n8yt2x/

You can reproduce this issue on the docs:
http://getbootstrap.com/docs/4.0/components/input-group/#segmented-buttons

`.btn-secondary` to `.btn-outline-secondary`:

![image](https://user-images.githubusercontent.com/4065765/34020048-40125040-e175-11e7-9d12-9a08b457fe7b.png)
