### ISSUE TITLE
Change or modify the behavior of card-columns ???

### ISSUE THREAD

**Issue by poilozorey** [twbs/bootstrap#25010]
Hello.

Is it possible to change or modify the behavior of "**card-columns**" of bootstrap 4?

via **card-columns**, the cards are arranged in columns, but they are classified from **top to bottom**.

Is it possible to change this behavior and classify them from **left to right** ???

**Comment by ysds** [comment]
Hi @poilozorey, If you want to like this:

![image](https://user-images.githubusercontent.com/4065765/34020359-1ee11120-e177-11e7-8835-6b4ea496e723.png)

Unfortunately, probably no solution. Please see: 
https://stackoverflow.com/questions/33891709/when-flexbox-items-wrap-in-column-mode-container-does-not-grow-its-width

**Comment by poilozorey** [comment]
Currently with **card-columns** the cards disposition is like this ...
```

Column one | Column two | Column three |
Card one   | Card four  | Card five    |
Card two   |            |              |
Card three |            |              |

```
I will want a "**card-colums**" with this disposition ...
```
Column one | Column two | Column three |
Card one   | Card two   | Card three   |
Card four  | Card five  |              |
           |            |              |
```
Its possible with card-colums (modify via css or jscript) ??
Its possible not with card-colums but with **card-deck** ??
Thx for more anwsers

**Comment by ysds** [comment]
Sorry, my above comment was wrong!

**Comment by mdo** [comment]
Card columns are built with the CSS3 column spec—if you need more control over their layout, use our grid system or an external JS library like Masonry.

**Comment by poilozorey** [comment]
> Card columns are built with the CSS3 column spec—if you need more control over their layout, use our grid system or an external JS library like Masonry.

Sorry for my bad compression, but would you have an example (Boostrap 4 gray, CSSS3 or JS) to change the behavior of "card-columns" vertical in horizontal ?

**Comment by hgghyxo** [comment]
Still looking for a solution in this

**Comment by binbsr** [comment]
Out of the box solution would be great. Still depending on workarounds.

**Comment by hgghyxo** [comment]
Display flex is the solution
