### ISSUE TITLE
"no-gutter" class does not affect a sass @extend row, when there is no "col" class present

### ISSUE THREAD

**Issue by NiviJah** [twbs/bootstrap#25012]
https://v4-alpha.getbootstrap.com/layout/grid/#no-gutters

since the code targeting a ".col" class,
if sass is being used to affect html without said ".col" class, the code will work on the "row" itself, but not any children [who has no "col" class]

**Comment by wolfy1339** [comment]
You are using an outdated version of Bootstrap. Please upgrade to v4.0.0-beta.2
Docs are now here: https://getbootstrap.com/docs/4.0/

**Comment by Johann-S** [comment]
like @wolfy1339 said :smile:

**Comment by hamittoprak06** [comment]
:) okey

**Comment by mdo** [comment]
Closing because version was outdated.
