### ISSUE TITLE
Tooltips not centered

### ISSUE THREAD

**Issue by kjdion84** [twbs/bootstrap#25013]
I am getting bizarre results with my tooltips. They are not centered properly.

Please see this fiddle: https://jsfiddle.net/uf0epmxm/6/

I have absolutely no idea why this is happening. I reproduced it in the fiddle. You can see that it is not centered when you hover over the "Add Role" button:

    <button type="button" class="btn btn-primary" data-modal="http://laraback.dev/roles/add" data-toggle="tooltip" title="Add">Add Role</button>

One thing I noticed is if I remove the top blue navbar entirely it centers correctly.

Thanks for the help.

**Comment by Johann-S** [comment]
Seems like a positioning issue here :thinking: 
Can you confirmed that @FezVrasta ?

**Comment by FezVrasta** [comment]
I can't see anything wrong, what are the steps to reproduce it?

**Comment by Johann-S** [comment]
You have to move your cursor hover the `Add role` button and you'll see the attached tooltip isn't center

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/34034715-e2edc0d8-e17f-11e7-8c18-02ba2b1eb4c0.png)

🤷‍♀️

**Comment by Johann-S** [comment]
![image](https://user-images.githubusercontent.com/1689750/34034834-54beb0be-e180-11e7-9b9e-eca4572b587a.png)

:astonished:

**Comment by FezVrasta** [comment]
browser version?

**Comment by Johann-S** [comment]
Chrome 63.0.3239.108 (Build officiel) (64 bits)

**Comment by FezVrasta** [comment]
Ok if I make the scrollbars be always visible I reproduce it.

Pasting here the CodePen version just for my own convenience:
https://s.codepen.io/FezVrasta/debug/vpOMdG/WPMLYGBEgGNr

**Comment by Johann-S** [comment]
Thank you @FezVrasta :+1: 
As it related to Popper.js I close this issue

**Comment by kjdion84** [comment]
I resolved this by using **flex: 0 0 250px** on the sidebar and **flex: 0 0 auto*** on the content div.
