### ISSUE TITLE
bootstrap-4-beta.2  tabpanel not working - wrong #active removed

### ISSUE THREAD

**Issue by PSalador** [twbs/bootstrap#25027]
In bootstrap-4-beta all working - `.active` removed https://jsfiddle.net/q2tf3naw/

In bootstrap-4-beta.2 not working - `.active` not removed https://jsfiddle.net/q2tf3naw/3/

**Comment by Johann-S** [comment]
It's because your `.tab-content` is a `<ul>` instead of a `<div>` see my CodePen which work using this small change : https://codepen.io/Johann-S/pen/PEZmdQ

**Comment by PSalador** [comment]
Thanks. Everything is working.
