### ISSUE TITLE
Add border-{top,bottom,left,right}-1

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#25024]
When I want to have a border only on the bottom, I need to add a border on all sides and remove then afterwards:
So the code looks like:
` border border-left-0 border-top-0 border-right-0 border-dark`
Which would be much easier, if there was a `border-bottom-1`

Also, there is no way to match a border the border color of a card. So maybe add another `border-grey` or something to match that color.

Since I try to re-create the `page-title` class with utility classes, this would be very helpful. 
Because a simple `mb-3 pb-1 border-bottom-1 border-grey` would do the trick

**Comment by MichaelRise** [comment]
@TheZoker Check my example: https://github.com/twbs/bootstrap/issues/23354

**Comment by mdo** [comment]
PR for it was added five hours before you opened this issue ;). See #25021.
