### ISSUE TITLE
Nav into container not fullscreen on mobile

### ISSUE THREAD

**Issue by crive69** [twbs/bootstrap#25032]
in bootstrap 3 this was working fine
but in bootstrap 4 when you put the nav items into a container the nav items are not full width when opened on mobile

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Closing given lack of live demo.
