### ISSUE TITLE
wrong grid layout in safari

### ISSUE THREAD

**Issue by cmk128** [twbs/bootstrap#25037]
wrong grid layout in safari, ok in chrome. It shouldn't wrap my col to next row

<img width="1680" alt="screen shot 2017-12-19 at 1 11 27 pm" src="https://user-images.githubusercontent.com/34470546/34141758-4b04a7a4-e4be-11e7-905e-afc0dc8d8fac.png">

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
In all likelihood you're problem is the Safari flex container bug with psuedo-elements like `::before` and `::after`.
