### ISSUE TITLE
remove the overflow from example container, currently it breaks the dropdown 

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#25038]
https://github.com/twbs/bootstrap/blob/eaaad9574c82a92f70c5a1870451b178e34b915a/assets/scss/_component-examples.scss#L121
![screenshot-2017-12-19 dropdowns](https://user-images.githubusercontent.com/1651241/34144217-e0ceb01e-e490-11e7-85a2-83d5b9996297.png)

**Comment by patrickhlauke** [comment]
@mdo can't test at the moment, but i'm guessing this then reintroduces the problem noted in https://github.com/twbs/bootstrap/pull/24878#issuecomment-347034636 ?
