### ISSUE TITLE
IE11 W7 doesn't wrap large .row > .col elements

### ISSUE THREAD

**Issue by oschonrock** [twbs/bootstrap#25033]
**BS4-beta2 IE11 on W7**

When using the basic equal column width example from docs:
https://getbootstrap.com/docs/4.0/layout/grid/#equal-width
and one column contains large un-wrappable content (eg text without spaces or a replaced element like image), then IE11 does not wrap the remaining columns. Instead IE11 lets the long col1 overflow over the top of col2 and col3. 

```html
<div class='row'>
    <div class='col'>
        col1WithReallyLongContentThatCantWrapOrIsALargeReplacedElementEgAnImage
    </div>
    <div class='col'>
        col2
    </div>
    <div class='col'>
        col3
    </div>
</div>
```
When reducing the BS4 CSS down to the bare essentials we can demonstrate the problem with this codepen: https://codepen.io/oschonrock/pen/NXxXEj (test in IE11 and shrink your codepen window to see the effect). 

The current BS4 css has `flex-basis: 0;` for `.col`. This doesn't work in IE11 as shown in bottom example row in the codepen, col1 overflows onto col2 & col3. If we change it to `flex-basis: auto;` for `.col` it does work as the top row in the code-pen shows. 

Works as expected in recent FF or Chrome. ie both rows in codepen, wrap as expected. 

Is this an IE flexbox bug or an issue with the BS4 `.col` CSS?

**Comment by mdo** [comment]
This is currently an undocumented flexbug: https://github.com/philipwalton/flexbugs/issues/170. We cannot change `flex-basis` to `auto` though as it will cause our columns to stack in IE11 vs layout as you intend. Note that your first column isn't equal-width to the second and third in your "good column" example.

Flexbox is still buggy in IE, and it has quirks in every other browser, too. There are usually a few options for every situation, but nothing that's uniformly perfect. Sorry!

**Comment by oschonrock** [comment]
Yeah, I realise flex-basis: auto is not a generic fix. It works in my specific (original) case, but layout is certainly different for the general case.

Thanks for looking into it. I feel like IE11 is the new IE6, and corporates will be very slow to upgrade away from W7, hence IE11 will be here for a long time... sigh

At least this broken behaviour now has one more piece of Googlebait, and people will realise what's happening.

**Comment by mdo** [comment]
Yeah it’s a bit of a pain for sure :). Hopefully we can get there with time—IE11 isn’t that big overall.

**Comment by plantsmiles** [comment]
Just ran into this myself, and after a few hours of tinkering I was looking at the `col` source and realized there is also a `col-auto` that fixed this in ie11 for me.
