### ISSUE TITLE
Container does not fit on large screens, Container no se ajusta en pantallas grandes

### ISSUE THREAD

**Issue by OCHOASV** [twbs/bootstrap#25036]
El div **container** no se ajusta en pantallas grandes ya que tiene una medida especifica.
*The div ** container ** does not fit on large screens because it has a specific size.

`@media (min-width: 1200px) {
  .container {
    width: 1170px;
  }
}`

Así, cuando se ve en pantallas de 2048 * 768 no se ajusta al tamaño del navegador, para solventarlo hay que manejar los tamaños por porcentaje así:
*Thus, when viewed on screens of 2048 * 768 it does not adjust to the size of the browser, to solve it you have to manage the sizes by percentage like this:

`@media (min-width: 1200px) {
  .container {
    width: 90%;
  }
}`

*English

**Comment by mdo** [comment]
You're using Bootstrap 3 and it's no longer being actively developed. Changes like this make sense for your own site, but there will be no changes to Bootstrap.

**Comment by OCHOASV** [comment]
No importa la versión, Bootstrap 4 lo hace igual
*No matter the version, Bootstrap 4 does the same
 `@media (min-width: 1200px) {
  .container {
    max-width: 1140px;
  }
}`

Y como se le ocurre decir que solo sirve para mi sitio ?? Osea que en el mundo no hay pantallas grandes ?? Que clase de desarrollador es que a las ventanas mayores de 1200px de resolución les deja un ancho de 1140px ??????????????? Hasta le redujeron en bootstrap 4 x_x
*And how does it happen to say that it only works for my site? So in the world there are no large screens ?? What kind of developer is it that windows greater than 1200px resolution leaves them a width of 1140px ??????????????? They even reduced him in bootstrap 4 x_x

**Comment by mdo** [comment]
Your tone doesn't help anyone—calm down and read the docs. See [this section on how to customize our grid system](https://getbootstrap.com/docs/4.0/layout/grid/#customizing-the-grid). We don't support every single situation, be it for a component or the general layout. If you need to support screens that large, customize the Sass variables and maps. Alternatively, write custom CSS to accomplish what you need.

Each time we add a new tier to our grid—say a new `xxl`—we generate hundreds of new classes. That's not something we rush into.

**Comment by OCHOASV** [comment]
Tiene razón. A sido muy amable en responder. Personalicé mi Bootstrap y logre lo deseado con el ancho al 90%. Es muy amable en responder.
Felicidades Bootstrap es de lo mejor (Y)

*Is right. He has been very kind in answering. Personalized my Bootstrap and achieve the desired with the width to 90%. He is very kind in answering.
Congratulations Bootstrap is the best (Y)
