### ISSUE TITLE
Uncaught ReferenceError: $ is not defined 

### ISSUE THREAD

**Issue by clay-f** [twbs/bootstrap#25034]
I'm using jsp import `bootstrap.min.js` occur error

<img width="912" alt="screen shot 2017-12-18 at 21 34 57" src="https://user-images.githubusercontent.com/16079417/34108525-5bd4b5fc-e43b-11e7-9944-1979e96eaea9.png">

this is code
```
<head>
    <title>register</title>
    <link rel="stylesheet" href="<c:url value="/statics/css/bootstrap.min.css"/>">
    <link rel="stylesheet" href="<c:url value="/statics/css/bootstrap-grid.min.css"/>">
    <script href="<c:url value="/statics/js/jquery.min.js"/>"></script>

    <script src="<c:url value="/statics/js/popper.js"/>"></script>
    <script href="<c:url value="/statics/js/bootstrap.bundle.min.js"/>"></script>
    <script src="<c:url value="/statics/js/bootstrap.min.js"/>"></script>
</head>
```

jquery: 3.2.1
popper: 1.12.9 
bootstrap: v4.0.0-beta.2

**Comment by Johann-S** [comment]
Do you use jQuery in noConflict mode ? 

FYI `bootstrap.bundle.min.js` include Bootstrap and Popper.js so you juste have to include jQuery and `bootstrap.bundle.min.js` that's all

**Comment by clay-f** [comment]
oh, yes, after remove `popper.js` and `bootstrap.min.js`, browser show is right.
and I'm trying remove `bootstrap.bundle.min.js`, leave both file, browser give same issue

```
    <link rel="stylesheet" href="<c:url value="/statics/css/bootstrap.min.css"/>">
    <link rel="stylesheet" href="<c:url value="/statics/css/bootstrap-grid.min.css"/>">
    <script href="<c:url value="/statics/js/jquery.min.js"/>"></script>

    <script src="<c:url value="/statics/js/popper.js"/>"></script>
    <%--<script href="<c:url value="/statics/js/bootstrap.bundle.min.js"/>"></script>--%>
    <script src="<c:url value="/statics/js/bootstrap.min.js"/>"></script>
```

<img width="882" alt="screen shot 2017-12-18 at 22 03 41" src="https://user-images.githubusercontent.com/16079417/34109701-65069cf4-e43f-11e7-97b1-58c2f608e134.png">

**Comment by clay-f** [comment]
😃, OK, found issue with this
I'm import script file wrong
```html
<script href="<c:url value="/statics/js/jquery.min.js"/>"></script>
<%-- should be --%>
<script src="<c:url value="/statics/js/jquery.min.js"/>"></script>

```
thanks

**Comment by Johann-S** [comment]
You're welcome :+1:
