### ISSUE TITLE
Problem with installing the latest beta (v4.0.0-beta.2) using bower

### ISSUE THREAD

**Issue by sunpietro** [twbs/bootstrap#25031]
Spotted on MacOS Sierra.

I'm trying to install the latest beta version using bower commands, but it looks like it has issues with JSON. The previous beta had installed without any issues.
The command I'm using: `bower install bootstrap#v4.0.0-beta.2`

It gives the following error:
![bower bootrstrap error](https://user-images.githubusercontent.com/1736658/34095722-cd6dd310-e3d2-11e7-9b0a-da7273c4d323.jpg)

**Comment by Johann-S** [comment]
We removed the support of Bower in our latest release see : https://github.com/twbs/bootstrap/pull/23568

**Comment by sunpietro** [comment]
That's so unfortunate. Thanks for informing about it.
