### ISSUE TITLE
Card or list group in an area with a dark background color

### ISSUE THREAD

**Issue by toshi0820** [twbs/bootstrap#25043]
When placing ```.form-control``` and ```.dropdown-menu``` in an area with a dark background color character (```color: white```) characters are visible.
Because they are added a color style property (```color: #212529```) which is the same as body color.

But when placing a card or list group in an area with a dark background color ( character ```color: white```), characters are not visible.
So I think we should add a color style property same as body color to them.

https://jsfiddle.net/p4Lyrrrb/

Like that
``` css
.card, .list-group {
  color: #212529;
}
```

**Comment by mdo** [comment]
Add `.text-dark` where you need it.

**Comment by toshi0820** [comment]
@mdo 
Hi, mdo Thank you for responding.<https://github.com/twbs/bootstrap/issues/25043>
If I add `.text-dark`, this color style property is not the same as `#212529` which is body color .
And depending on the component, some color is not defined as being defined.
There is no sense of unity because there are differences among components.
So I think we should add a color style property to ```.card``` and ```.list-group```.
