### ISSUE TITLE
jQuery.noConflict( true ) support

### ISSUE THREAD

**Issue by WraithKenny** [twbs/bootstrap#25041]
## Feature Request

**Please allow configuring Bootstrap to use a second version of jQuery that is available in a global other than `$` or `jQuery`, via use of `jQuery.noConflict(true)`.**

Several issues have already been addressed regarding `$.noConflict()` support (in which `$` would be unavailable, but `jQuery` would be). This was largely due to WordPress running jQuery in no conflict mode. 

WordPress also runs an old version (`1.12.4`) which no longer receives patches (and is [vulnerable](https://nodesecurity.io/advisories/jquery_xss) ). Many developers will "upgrade" jQuery before WP does. However, upgrading WordPress's jQuery in place via `wp_deregister_script` is typical, but [responsible developers should not replace WP's jQuery](https://pippinsplugins.com/why-loading-your-own-jquery-is-irresponsible/).  [A better way is described by WP Engine](https://nodesecurity.io/advisories/jquery_xss): WP developers should leave WP Core's library alone as to not break what is depending on them, and register a new version with `$.noConflict(true)`.

If Bootstrap looked for jQuery in some other global, `var twbs$ = jQuery.noConflict(true)` (naming variables is hard) would allow using a modern version of jQuery in Bootstrap, while preserving WP core's version for itself.

There may be other use-cases of wanting to use a jQuery that isn't on the `jQuery` or `$` globals.

**Comment by Johann-S** [comment]
A temporary way to achieve what you want would be to use a bundler (Rollup, Webpack) to import Bootstrap and jQuery together

**Comment by WraithKenny** [comment]
Just as a note, because of how WordPress handles it's dependances (i.e., poorly) using bundlers isn't really in the cards for publicly released themes and plugins. They'd still need to use `wp_enqueue_script` which basically means globals, but I suppose that WordPress devs could agree on a variable name (`jQuery3` I guess?) and use a bundler to import that global via configuration. 

I'm thinking that having TWBS address WordPress's bug/vulnerability is probably inappropriate, so I'll close this.

**Comment by puzumaki** [comment]
I would like to re-open this request. I need noConflict support because our Drupal instance uses a different version of jQuery, it is not limited to a WordPress concern. I need a non dollar sign symbol in my JS, please provide a solution that allows noConflict.

**Comment by Johann-S** [comment]
You can use Bootstrap in noConflict mode but you cannot specify an other name that `jQuery` in noConflict
