### ISSUE TITLE
Shim for easy upgrade from v3 to v4

### ISSUE THREAD

**Issue by JahlomP** [twbs/bootstrap#25046]
This will make it very easy to still use bootstrap 3 while progressively migrating to v4.
The Font Awesome theme has a nice example of this at https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by Johann-S** [comment]
Not sure if we will have time to implement that :thinking:

**Comment by Herst** [comment]
Not sure whether improving Bootlint in this direction wouldn't be a more reasonable (and less error-prone) approach, I am personally no friend of such client-side shims.

**Comment by mdo** [comment]
Sorry, but this just isn't feasible or productive—for us or folks using Bootstrap. v3 doesn't go away, and v4 is such a sweeping overall. Providing a shim would be bloated, slow, difficult to produce, etc.

**Comment by JahlomP** [comment]
OK. Thanks.
