### ISSUE TITLE
Bootstrap css How do you format that nicely

### ISSUE THREAD

**Issue by 547377507** [twbs/bootstrap#25055]
Thank you for all the answers,Bootstrap css How do format that nicely
![qq 20171222180133](https://user-images.githubusercontent.com/13267376/34294159-2ad2c03e-e742-11e7-9c8a-7df6575850ba.png)

**Comment by patrickhlauke** [comment]
it's not really clear if this is a question, or just a suggestion to reformat all scss files. assuming it's the latter, i don't think this will get much traction, so closing for now.

**Comment by mdo** [comment]
I think they're asking how we formatted it—it's just spaces manually tweaked as needed.
