### ISSUE TITLE
The interface is wrong

### ISSUE THREAD

**Issue by hksanduo** [twbs/bootstrap#25053]
![image](https://user-images.githubusercontent.com/31351525/34282085-f6891b5a-e6fd-11e7-842d-464ee9c6bafb.png)

**Comment by hksanduo** [comment]
class="pull-left"

**Comment by mdo** [comment]
You're looking at a super old version of Bootstrap—something around v2.x—and I'm guessing it's also a translated copy. It's correct on our site: https://getbootstrap.com/2.3.2/components.html#helper-classes.
