### ISSUE TITLE
Best practices with tables size

### ISSUE THREAD

**Issue by gygabyte017** [twbs/bootstrap#25078]
I know it may be asked several times, but I can't find a satisfying way to display a nice table.

I usually develop management/database application, so I use tables to display and manipulate data. So my tables aren't the classic tables with text data, instead each cell may contain text (very long / very short), buttons, inputs, checkboxes, ..., and the cell content may vary with user actions (i.e. a text in a cell may become a input text for edit the value).

My goal is to make sure that:

- columns width doesn't not flicker around as a cell content change (i.e. from text to input text).
- columns width remains between some borders, meaning that if the screen size is small a text in a cell doesn't wrap like a word per line.
- columns width and cells content should be somehow responsive, i.e. if the screen size is large, a cell which contains two buttons shows them one next to the other, while if the screen size is small, such a cell shows the two buttons stacked BUT, if the screen size is very small the column width shouldn't be less than some value (making the buttons unreadable) and, if the screen size is very small, the column width shouldn't be greater than some value (making the buttons width huge or instead making the margin between them huge).
- rows height should be controllable, i.e. if a text in a cell is long and wraps making the row height larger, I may want that all the other rows share the same larger height.

I tried with the table and table-responsive classes, I tried with the grid system, I tried with flex, but I haven't found a clean way to have full control on a table.

May you help me to understand which way should I pursue?

Thanks a lot

**Comment by MartijnCuppens** [comment]
> columns width doesn't not flicker around as a cell content change (i.e. from text to input text).  

You must explicitly set the width to the tablecells to achieve this behaviour. This really depends on how many columns you have and how you want them to behave.

> columns width remains between some borders, meaning that if the screen size is small a text in a cell doesn't wrap like a word per line.  

Check out the `.text-nowrap` class: https://getbootstrap.com/docs/4.0/utilities/text/#text-wrapping-and-overflow 

> columns width and cells content should be somehow responsive, i.e. if the screen size is large, a cell which contains two buttons shows them one next to the other, while if the screen size is small, such a cell shows the two buttons stacked BUT, if the screen size is very small the column width shouldn't be less than some value (making the buttons unreadable) and, if the screen size is very small, the column width shouldn't be greater than some value (making the buttons width huge or instead making the margin between them huge).

This looks very case specific. Totally depends on content of the buttons, how many buttons, ...

> Rows height should be controllable, i.e. if a text in a cell is long and wraps making the row height larger, I may want that all the other rows share the same larger height.

As far as I know, this is not possible with only css.


Personally, I think you should stick to with the tables bootstrap provides, use `.text-nowrap` to prevent some text from wrapping add custom classes to control the width of the tablecells.

**Comment by mdo** [comment]
@MartijnCuppens has a solid answer here for you. I'm unsure why you need such strict control of the table's layout, but what you're asking for seems out of scope for our help. We can provide some of the various tools you'll need to do this, but not everything.
