### ISSUE TITLE
NuGet packages do not include .js.map files

### ISSUE THREAD

**Issue by HamsterExAstris** [twbs/bootstrap#25079]
The bootstrap JavaScript files included in the NuGet packages include references to matching .map files at the end; however, the .map files are not included in the package. Chrome therefore tries to download the file from the site using Bootstrap, which will result in a 404.

I will submit a pull request with a fix to the .nuspec files shortly.

**Comment by mdo** [comment]
I think it was @supergibbs who added NuGet support originally—any chance you can confirm and review this?

**Comment by supergibbs** [comment]
Looks good to me! Is there a `beta.3` coming out soon or should I update the `beta.2` package?

**Comment by mdo** [comment]
I just shipped Beta 3 :D. But, we can get this in v4 stable—hoping for 1-2 weeks out on that.

**Comment by supergibbs** [comment]
Oh awesome! I'll update the nuget package now and hotfix this patch locally so the map files are included.

**Comment by supergibbs** [comment]
beta.3 tag but includes map files:
https://www.nuget.org/packages/bootstrap/4.0.0-beta3
https://www.nuget.org/packages/bootstrap.sass/4.0.0-beta3
