### ISSUE TITLE
Bower Package ERROR for bootstrap 4.0.0.b2 with VS2017 15.5.2

### ISSUE THREAD

**Issue by robjuca** [twbs/bootstrap#25089]
![bowererror](https://user-images.githubusercontent.com/12336342/34361730-9e682f50-ea4b-11e7-9ec8-1995eb590a10.jpg)

**Comment by mdo** [comment]
We no longer publish to Bower, it’s been deprecated by its maintainers. Try npm or NuGet.

**Comment by robjuca** [comment]
Hi my friend I did BUT  NuGet report "Incompatible use Bower instead".
![error2](https://user-images.githubusercontent.com/12336342/34363273-65e1ab94-ea59-11e7-8569-17ef2d5d1911.jpg)

**Comment by supergibbs** [comment]
This happens on dot net core projects. NuGet is designed for code libraries, not css/js ones. It's recommended to use NPM or VS built in libman to get bootstrap on those. It works still on .NET Framework projects.
