### ISSUE TITLE
Sections are overlapping Sticky Navbar

### ISSUE THREAD

**Issue by alva59** [twbs/bootstrap#25084]
I have created a sticky navbar using Bootstrap 4 and Sticky JS plugin. But when I scroll down my sticky navbar get overlapped by other sections. Now I need someone help me solving this issue. It is also behaving different in different browsers.

here is the link https://alva59.github.io/pf1/

**Comment by patrickhlauke** [comment]
For help/how-to questions, please use StackOverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
