### ISSUE TITLE
Build relies on too many tools ! I hate ruby & gem

### ISSUE THREAD

**Issue by xiuno** [twbs/bootstrap#25096]
I tracking the Bootstrap 4  from alpha4, to beta2, I want to put forward 2 suggestions, 
1: the Bootstrap 4 release version is waiting too long, and each alpha document is updated missing (only the last version), a formal version of it is a pressing matter of the moment to us. Unified upgrade.

2:Build relies on too many tools, the international network is too slow, especially ruby Gem, which is slow as a dead cow. Doesn't nodejs have relevant tools, and needs another ruby? Gem and in the update to half off net, will be rather baffling problem, need to work to clean up some residual files. For the front-end people, this is just too bad.

I hope bootstrap 4 team (the great twitter UI team) can listen to suggestions and get better development.

**Comment by mdo** [comment]
Yeah, I hate the dependencies, too. We're working on that piece by piece. We have a branch for removing jQuery that's being contributed to with smaller pull requests here. Members of the team have also explored other changes like moving from Jekyll to Hugo.

Long story short, it's not super easy, but we're going to get there.

**Comment by xiuno** [comment]
Thanks for your reply, and I will continue to pay attention to the progress of bootstrap 4.
