### ISSUE TITLE
Wrong image position with padding of 15px.

### ISSUE THREAD

**Issue by robjuca** [twbs/bootstrap#25090]
![error](https://user-images.githubusercontent.com/12336342/34363180-73ef80a4-ea58-11e7-8cb9-cad41e75103e.jpg)

**Comment by andresgalante** [comment]
To make the grid system work correctly `.container` has a 15px padding left, it's set here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_grid.scss#L8
