### ISSUE TITLE
Multiple select dropdown

### ISSUE THREAD

**Issue by Diar77** [twbs/bootstrap#25094]
So I am trying to create a dropdown where you can select movie genres. But I am wondering if bootstrap has one. Check this example [here](https://semantic-ui.com/collections/form.html). Scroll down to "Multiple Select".

And if bootstrap doesnt have one. Is there any plans to add it? And till then do you have other suggestions how I could implement this? Thanks.

**Comment by mdo** [comment]
We do not provide such a component. There's probably a third-party one out there though.
