### ISSUE TITLE
Back to CSS prefix

### ISSUE THREAD

**Issue by ggondim** [twbs/bootstrap#25105]
Even after three years that #1235 was locked, it still makes sense to add a `prefix` variable that prefixes all classes OR scopes all classes within the prefix class.

According to contribution guidelines, this is a feature request. It is also a duplicate, but I could never explain my use case in a locked issue like #1235.

I've been using Bootstrap since its beggining. I updated from v2 to v3 with a very nice smile on my face. Last year we started to use it from Less sources compiled with Webpack. We changed some variables, but not the styles.

By the end of this year, we made a corporate rebranding. All the styles were standardized and we started a separate project to customize Bootstrap Less files in order to apply our new brand guidelines.

However, we are in a crisis here. Some parts of the website can be updated with the new styles, but other can't because it doesn't makes sense to invest any effort to adapt old features to new styles.

So we had the brilliant idea to wrap all the old BS styles inside a contextual class ".oldbs"  and apply it only to webpages that need to be compatible with the old interface.

It would be nice if BS had an option to build this prefix or contextual way of framework application. Searching across the web, we found some people considering this feature for BS3 to BS4 transition. And now, well... we also are considering this for future migration.

In the end, we've ended up with this tutorial for Less: https://formden.com/blog/isolate-bootstrap. It consists of compiling all bootstrap.less file and then prefix all the CSS compiled file with another Less.

Backwards compatibility or even an easier way to make softer transitions is a must have for a mature and globally used framework like Bootstrap.

Best regards to all.

**Comment by mdo** [comment]
This can be solved outside our framework with whatever build tooling you need. I’m unsure if we’d try to bake this in ourselves given the various nuances of everyone’s setup.

If you use PostCSS, these options are available:

- https://github.com/thompsongl/postcss-class-prefix
- https://github.com/marceloucker/postcss-prefixer

I’m sure there are more, too.

**Comment by mdo** [comment]
Closing as a won't fix for now.

**Comment by lsong98sh** [comment]
it's a tough work to change css prefix in js files.
