### ISSUE TITLE
What would be the advantages of dropping IE10?

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#25100]
Thinking aloud, probably just relevant for post-4.0 (right, @mdo?):

* #23770 could be reverted, possibly improving JS minimization and be a micro-optimization for `undefined` checks
* Notes about missing `pointer-events` (as added in e.g. #23826) could be removed.
* The `pointer-events` workaround for #23222 might be worth checking out again.
* SVG images fix not needed any more (#23476)
* Some of the notes about disabled `<a>` buttons could be possibly removed
* #22493?
* Doing `flex-basis: 100%` instead of `flex-grow: 1` might not be needed any more (#23652).
* No need for `-ms-` prefix for flexbox properties (as noted by @alecpl, thanks!), dropping `-ms-` prefix for `touch-action`

_Can I use_ comparison: <http://caniuse.com/#compare=ie+10,ie+11>
IMHO, most noteworthy from there:
* `pointer-events`
* `hidden` attribute
* `const` and `let` (not whole ES6 though, no idea whether Babel can make use of this)

Some other possibly relevant things:
* Various touch improvements, sadly most of them have to do with the pointer events API, but also various touch related (but mostly IE/Edge specific) CSS properties: 
   * https://msdn.microsoft.com/library/bg182636.aspx
   * https://blogs.msdn.microsoft.com/ie/2013/07/31/ie11-touch-browsing-for-todays-web-and-beyond/
   * https://blogs.msdn.microsoft.com/ie/2013/10/22/enabling-new-interoperable-panning-experiences-through-the-css-scrolling-snap-points-specification/
---
(Concerning desktop browser usage, it is below the .45% of Edge16 and .59% of IE8 according to <http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201711-201711-bar>, with no significant numbers in any continent. It's also considered unsupported by Microsoft on any desktop end-user operating system, see <https://support.microsoft.com/help/17454>, under _"What is the Lifecycle Policy for Internet Explorer?"_; Other UI libs which don't support IE10: [[1]](https://jqueryui.com/browser-support/), [[2]](https://github.com/Dogfalo/materialize#supported-browsers), [[3]](https://github.com/uikit/uikit#browser-support), [[4]](https://material-ui-next.com/getting-started/supported-platforms/))

**Comment by alecpl** [comment]
No need for `-ms-` prefix for flexbox properties - smaller css output.

**Comment by mdo** [comment]
Appreciate the discussion, but it's sticking around for v4.

**Comment by Herst** [comment]
@mdo, that's why I wrote:
>  _probably just relevant for post-4.0 (right, @mdo?)_

You already have [open issues for 4.1+](https://github.com/twbs/bootstrap/projects/5) so I thought I add to that.

**Comment by tarkhov** [comment]
I have now rewritten a few components on a clean javascript and will end in the next month - https://tarkhov.github.io/postboot/

**Comment by kukuleta** [comment]
, Z

24 Nis 2018 Sal 05:46 tarihinde Alexander Tarkhov <notifications@github.com>
şunu yazdı:

**Comment by zoldello** [comment]
In version 5, if IE11 and lower support is dropped, bootstrap can iterate much faster, will not be dragged down by dinosaurs and can fully embrace new CSS and HTML feature (even right after they are released). Version 4 can be the version those still needing to dry-nurse IE11 and lower, can use.

**Comment by coliff** [comment]
@zoldello IE11 support won't be going away anytime soon. It is still very popular (has more desktop users than all versions of Safari combined - and even Microsoft's own Edge browser!). It's the only preinstalled browser on Windows 7 and Windows 8.1 which are supported by Microsoft for many years to come.
 
Of course I agree that IE10 can be dropped in the next major version of Bootstrap. That is unsupported by Microsoft and has a tiny marketshare (0.1%)

**Comment by Kout** [comment]
@coliff The decline of IE might be quicker than expected. Last week one of Microsoft officials called [Internet Explorer “a compatibility solution”](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732) (eg. not a browser :grin:). 

Our part of developers can be giving the IE less care. I know all the arguments of how much money can bring a 0.1 % of users visiting our e-commerce website. But I also think, we are helping to keep this dinosaur alive with too much care and conservativness.

**Comment by coliff** [comment]
@Kout  Let's not go off-topic too much here...
- **IE10** support should be dropped from Bootstrap as usage is now 0.07% globally.
- **IE11** is still very popular (2.37% globally), still more used than all versions of Safari for MacOS combined and still more used than all versions of Edge combined.
Reference: https://caniuse.com/usage-table

**Comment by XhmikosR** [comment]
BTW I agree with @coliff's answer. That being said, I'm not sure what the verdict will be for v5. Because dropping IE11 makes JS cleaner. We could suggest a specific snippet for any needed polyfills from <polyfill.io> thus making the transition smoother. CSS is another issue, but we'll need to assess that when time comes.

**Comment by Kout** [comment]
@coliff You are aboslutely right. In ideal world it would be nice to separate Bootstrap version supporting IE11 from the non-IE11. Eg. having for the first one extra stylesheets, polyfills etc. With rise of HTTP/2 having more requests is not big deal anymore (and rather “punish” IE11 users than the majority with modern browsers). In plain words the strategy of jQuery and their slim/full versions. But I don’t know if it won’t be a hell for maintenance.

**Comment by dvmuccillo** [comment]
[IE11 isn't recommended anymore by microsoft itself.](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732)

Can't we afford the price and remove its support?
When v5 release come maybe someone will still be developing to support a software marked as dead or that will touch a very old app and try to upgrade it.

But aren't there no more positive points than cons as to the removal of the support?

**Comment by Herst** [comment]
@dvmuccillo 
> But aren't there no more positive points than cons as to the removal of the support?

Feel free to create a new thread discussing the possible upsides of dropping IE11 support (this thread is about dropping IE10). I am sure the list of advantages would be much longer than the one here, since much more changed between IE11 and Edge than between IE10 and IE11. I guess even more so if only rather recent versions of Edge would be supported.

**Comment by dvmuccillo** [comment]
@Herst my bad!
Sorry and thanks for the tip.

**Comment by ray73864** [comment]
Would love to have used Bootstrap 5 when it comes out, but the lack of IE11 support would be a deal-breaker for me unfortunately.

In our business, all our stores log onto a series of terminal servers (our admin people log onto another one), a store might have 5 thin clients and all 5 are logged onto the same user, the unfortunates of Chrome, Firefox, etc... is that they don't support session-profiles, only user-profiles, so with 5 logged into the same user, the first one to open Chrome/FF sets the lock on the profile and both require kludges to get them to be semi-useful.

We have in the past attempted Chrome, but it's never been 100% successful. IE on the other hand supports user-session profiles, so each logged in session has a slightly separate way of using the browser (especially from the task-manager POV).

If there was a stylesheet + polyfills for V5 that allow it to continue to work on IE11 that would be super-awesome, then I could get rid of jQuery completely.
