### ISSUE TITLE
Collapse and two columns layout

### ISSUE THREAD

**Issue by starkskalle** [twbs/bootstrap#25119]
I am trying to use one accordion for two columns layout and this is only working in bootstrap 4 alpha and is NOT working since any beta release (tried even with the latest beta 3).

## Steps to reproduce with CodePen examples
Take a look at this [codepen](https://codepen.io/starkskalle/pen/YYVPpw) - once you click on any collapsible element it stays collapsed forever unless you click on it again. However the expected behaviour is that only one element should be collapsed at a time.

Take a look at the very same [HTML markup](https://codepen.io/starkskalle/pen/mpmymO) using Bootstrap Alpha 6. Everything is working as expected. You are not able to have more than a one element collapsed.

## Related issues
There is a similar issue #24810 but I am not sure whether it is related or not.

## Environment

- Windows 7 64 bit
- Chrome version 63 (64 bit)

**Comment by MartijnCuppens** [comment]
On line 133 of `collapse.js` only children of children of the accordion parent are filtered to hide. 

```js
actives = $.makeArray($(this._parent).children().children(Selector.ACTIVES))
```

I changed this behaviour in #25121 

```js
actives = $.makeArray(
  $(this._parent)
    .find(Selector.ACTIVES)
    .filter(`[data-parent="${this._config.parent}"]`)
)
```

This works, but throws an error during the karma test, does anyone know how to fix this?

**Comment by XhmikosR** [comment]
@MartijnCuppens: did you run your branch locally with `npm test`? Maybe an existent test needs adaptation.

**Comment by MartijnCuppens** [comment]
@XhmikosR, the unit tests indeed needed some adaption. PR #25121 is just updated.
