### ISSUE TITLE
Carousel OffsetWidth Console Error in Docs

### ISSUE THREAD

**Issue by braginteractive** [twbs/bootstrap#25128]
- Operating system and version: macOS High Sierra
- Browser and version: Chrome Version 63.0.3239.108 (Official Build) (64-bit)

This is what I am seeing:

<img width="2280" alt="screen shot 2017-12-29 at 4 32 56 pm" src="https://user-images.githubusercontent.com/2836834/34448776-68b29d42-ecb6-11e7-890b-fa1111f87b94.png">

**Comment by kevdotbadger** [comment]
Can't replicate it over here. Same OS, same browser. The only console feedback I get is the ServiceWorker info line.

**Comment by MartijnCuppens** [comment]
I also can't replicate this.

**Comment by Johann-S** [comment]
Weird jQuery version : 
![image](https://user-images.githubusercontent.com/1689750/34460901-8d567be8-ee1c-11e7-932e-d89dc61242da.png)


and not the one used by our documentation
