### ISSUE TITLE
custom-file selector isn't a valid CSS value since upgrade to beta3

### ISSUE THREAD

**Issue by javinto** [twbs/bootstrap#25127]
I have a Ruby-on-rails project (using the Bootstrap gem) where I use the custom file selector text according to the documentation:

```
$custom-file-text: (
  placeholder: (
    en: "Choose file...",
    nl: "Selecteer bestand..."
  ),
  button-label: (
    en: "Browse",
    nl: "Selecteer"
  )
);
```

After upgrading from beta 2.1 to beta 3 I now get the following error:
> (en: "Choose file...", nl: "Selecteer bestand...") isn't a valid CSS value.

As I'm using SASS I ensured not upgrading any other gem but Bootstrap to exclude other gems from being the problem gem. 

I could not find any upgrade or migration information on this specific component. So I suspect it is a bug. Here is my error:

<img width="535" alt="schermafbeelding 2017-12-29 om 23 32 08" src="https://user-images.githubusercontent.com/363831/34448739-8ed91bd8-ecf0-11e7-823a-10f4e3a1898a.png">

**Comment by mdo** [comment]
We need to update the Migration docs—that Sass map has changed. See our `_variables.scss` file.

**Comment by javinto** [comment]
Yes, its working now. Even better, so much simpler. Thanks for the quick response.
