### ISSUE TITLE
No Hand Cursor in button Boostrap 4 beta 3

### ISSUE THREAD

**Issue by hamzahamidi** [twbs/bootstrap#25131]
- Operating system : Ubuntu 16.4
- Browser: Chrome 63, Firefox 58
- Bootstrap 4 beta 3

 I don't get the "hand" cursor when pointing on a button. 
![icons8-hand-cursor-50](https://user-images.githubusercontent.com/22576950/34450185-1bfffd30-ed03-11e7-9f9f-670b59b18209.png)
Here's the code: `<button type="button" class="btn btn-primary">Primary</button>`
And here's a [bootsnipp](https://bootsnipp.com/snippets/gv6Pe) to confirm that. Take a look please at the **add user button**.
But in the official bootstrap beta 3 website it's working fine I see the **hand cursor**.
https://getbootstrap.com/docs/4.0/components/buttons/

**Comment by browner12** [comment]
looks like they are still using the beta 2. give them a little time to update, services like this don't update immediately after release

**Comment by mdo** [comment]
Yup, closing per @browner12.
