### ISSUE TITLE
[beta 3] Card-deck does not have the same rendering under safari vs firefox and chrome

### ISSUE THREAD

**Issue by poilozorey** [twbs/bootstrap#25136]
Hello.
I just tested the beta 3.
I realize that "card-deck" does not have the same rendering depending on the browser (especially on **safari**).
On Firefox and Chrome the rendering is similar, but on Safari it's broken!

**Firefox rendering screenshot**
![card-deck-firefox](https://user-images.githubusercontent.com/32791447/34454043-854d867c-ed62-11e7-8a28-8554ac8f100f.jpg)

**Chrome rendering screenshot**
![card-deck-chrome](https://user-images.githubusercontent.com/32791447/34454044-8d528f0c-ed62-11e7-90d2-aad00f6a57b9.jpg)

**Safari rendering screenshot**
![card-deck-safari](https://user-images.githubusercontent.com/32791447/34454046-929548a6-ed62-11e7-91eb-5f4a47515436.jpg)

Do you have a solution so that the rendering under Safari is the same as on Firefox and Chrome please?

**Comment by MartijnCuppens** [comment]
Which version of safari is this?

**Comment by poilozorey** [comment]
I have the version **Safari 5.1.7 (7534.57.2)**.

If it does not have the latest version or can I download the latest version of Safari for windows 7 ?

**Comment by MartijnCuppens** [comment]
Safari is not supported for Windows.

More about browser support for Bootstrap: https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/#desktop-browsers

**Comment by poilozorey** [comment]
Ah phew !!! 
I realize that safari is version 11 (against 5.17 for windows)
So the compatibility of bootstrap 4 beta 3 must be the same on Safari as on Chrome and Firefox.

Well, I hope.

Thank you for your answers !!!
I love bootstrap

**Comment by Herst** [comment]
For testing current desktop Safari versions which only exist on OS X there are various online testing services available, in many of them cost money this particular setup costs money but some offer trial periods.
