### ISSUE TITLE
btn-outline.active box shadows

### ISSUE THREAD

**Issue by mudrz** [twbs/bootstrap#25135]
Bootstrap 4 beta 3

Related to active buttons issue
@ysds
https://github.com/twbs/bootstrap/issues/24760
Related pull request
@mdo
https://github.com/twbs/bootstrap/pull/25070

>I agree to remove the focus box shadow from .active.

>The focus outline(box shadow) should only be used to highlight the focused elements - only one >element per window has the focus at a time.

In beta 3 the `.active` box shadow button issue was fixed for regular buttons, but not for outline buttons.
Additionally active outline buttons no longer change their text color when active
https://codepen.io/anon/pen/vpmZZM?editors=1000#0

**Comment by 719media** [comment]
I'm not sure if @mudrz  is saying that the btn-outline-* buttons' :active state should have a different text color, but I think it is... and I agree. I think having `color: color-yiq($color-hover);` on the :active looks "wrong" in that the dark text just seems out of place. It should be a lighter color like the hover (`color: color-yiq($color);`) IMO.
