### ISSUE TITLE
Update "Theming" documentation to include info on using CSS vars

### ISSUE THREAD

**Issue by willthemoor** [twbs/bootstrap#25147]
Loving BS4. Needed to make a few tweaks to the default colors so I installed the SCSS via NPM, created my own `_variables.scss` doc, updated links, blah blah blah. All the while I'm thinking, "shouldn't BS4 use CSS vars for this?".  Lo! I inspected an element for some other reason and saw a beautiful set of `--vars` on the `:root` element! 😃 🏕 

I'm already invested in the custom SCSS route (and need to adjust a few other variables not accounted for in `_root.scss`) but I'm very glad to learn of this feature. If https://getbootstrap.com/docs/4.0/getting-started/theming/ had info on a) their availability and b) how to use them, I might have just sorted it all out with `--vars` and saved a bunch of time.

This is a really fantastic feature update to Bootstrap; this issue is me hoping it gets the documentation attention I reckon it deserves. TBH, my _CSS Variables_ fu is weak (been hooked on pre-processors for so long) or I'd offer up a starter PR. Still, down to help get it going if someone wants to point my inner Energizer Bunny in the right direction.

**Comment by Herst** [comment]
I was about to open my own thread on the theming page, more specifically on how it would be neat if the page also gave some hints on tooling, for those people that don't just want to reverse-engineer [package.json](https://github.com/twbs/bootstrap/blob/v4-dev/package.json) just so they their custom build will be similar to bootstrap's.

**Comment by mdo** [comment]
I can jump on this. Unsure about how much of the tooling I'll get into @Herst, but noted.

**Comment by mdo** [comment]
@Herst We have our [build tools page](https://getbootstrap.com/docs/4.0/getting-started/build-tools/)  by the way—perhaps we need to expand on things there? Can you open a separate issue with any additional thoughts/recommendations?

**Comment by gijsbotje** [comment]
@Herst this article might help
https://medium.com/@gijsbotje/how-to-setup-a-bootstrap-project-like-bootstrap-does-it-3825a726b09a
