### ISSUE TITLE
Boostrap V4 Beta 3 will crash Angular 5

### ISSUE THREAD

**Issue by Nikodermus** [twbs/bootstrap#25153]
Bootstrap 4 beta 3 throws error with angular-cli.

For Angular 5 developers that might come into this, using bootstrap@4.0.0-alpha.6   or bootstrap@4.0.0-beta.2 to solve this issue.

**Comment by wolfy1339** [comment]
We've been having many issues with angular lately.
Please include more info on your problem. What is the stack trace?

**Comment by Johann-S** [comment]
Related to https://github.com/twbs/bootstrap/issues/25118
