### ISSUE TITLE
4.0.0-beta.2 => 4.0.0-beta.3 - outline buttons active state incorrect

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#25158]
I can't seem to find any documentation as to why the active state color was changed for buttons such as `.btn-outline-secondary`.  The contrast on active state is horrible and this seems recently changed between beta version 2 and 3.

https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons (press in / trigger active state on the buttons)

the desired result should be what was in beta version 2 where the text color is white on active state/press.

the only change seems to be https://github.com/twbs/bootstrap/blob/v4.0.0-beta.2/scss/mixins/_buttons.scss#L80 and https://github.com/twbs/bootstrap/blob/v4.0.0-beta.3/scss/mixins/_buttons.scss#L82

I think there's a typo, shouldn't `color: color-yiq($color-hover)` actually be `color: color-yiq($active-background)`?

**Comment by niftylettuce** [comment]
looks like it needs fixed in two places, thanks @omgimalexis

https://github.com/twbs/bootstrap/commit/7c10068c76751ee0ae8aab8cf0b7bdfdf40912ae

**Comment by mdo** [comment]
Closing since #25159 was closed.
