### ISSUE TITLE
Fixed column width isn't the same as normal columns

### ISSUE THREAD

**Issue by BenjaminHoegh** [twbs/bootstrap#25155]
Fixed column width isn't the same as normal columns, why that?

if you have 2 divs in a row like this:

    <div class="row">
        <div class="col-5 position-fixed"></div>
        <div class="col-5"></div>
    </div>

those two divs will have different widths why?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by kevdotbadger** [comment]
URL: https://codepen.io/anon/pen/JMJYaB

Bootstrap: 4.0 Beta 3

Browser: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
FireFox Developer Version 58.0b13 (64-bit)
FireFox 57.0.3 (64-bit)
Safari Version 11.0.1 (13604.3.5)

OS: OS X High Siera Version 10.13.1 (17B1003)

Notes: The widths are different, perhaps a flexbox issue. Weirdly the fixed div in Chrome is 15px (or so) larger than Firefox.

https://imgur.com/a/xX208

**Comment by MartijnCuppens** [comment]
The %-width of an element is relative to it's parent, but if the position is fixed, it's relative to the screen width. You can work around this by setting the parents class to `position-relative`: https://codepen.io/MartijnCuppens/pen/NXgNqz?editors=1100

**Comment by mdo** [comment]
What @MartijnCuppens said :).
