### ISSUE TITLE
Radio button and checkboxes not accepting .form-check class on mobile device

### ISSUE THREAD

**Issue by 14u2ponder** [twbs/bootstrap#25160]
Device noted on:
Motorola Z2 force, with Nougat 8.0. (recently upgraded.)

Expected behavior: left padding/margin styling. 
Current behavior: radios and checkboxes are to the extreme left and cutoff partially.

So I tested this and it definitely has something to do with the .form-check class. Apparently when you add form-check it is supposed to push the radio button and checkbox to the right, and then the form-check-input is supposed to correct the padding by applying the opposite padding amount to the left to zero it out to even.

As it stands, on the moto z2 force, only the form-check-input is being added to the dom, and thus it is pushing the radio and checkboxes off of the screen to the left since it is basically applying it's padding without form-checks padding to counteract it. Not sure if this is just with this phone or not, but once I remove those classes the radio buttons line up properly. 

Incidentally, form-check works properly on other form elements. Only the radio and checkboxes seem affected at this point.

**Comment by 14u2ponder** [comment]
It also has same problem with the custom class. The only thing that works is to remove the styles completely.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by 14u2ponder** [comment]
I believe that my problem had to do with my browser cache. Sorry for the open issue. I had to clear the entire cache, which before I was just clearing my webpage from the cache. After I did that everything worked correctly for some reason.
