### ISSUE TITLE
Button menu dropleft incorrectly renders split button

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#25172]
[Fiddle](https://jsfiddle.net/w4vhygvg/)

When using the dropleft variation with the toggle button in its most natural position (to the left), the button components are rendered with incorrect border radius.

![dropleft](https://user-images.githubusercontent.com/6351149/34496324-5080b9cc-efb6-11e7-8562-5c1381242ea7.png)

**Comment by ysds** [comment]
Your `<button class="btn btn-dark btn-lg">Menu</button>` must be after the child `.btn-group`.
Refs: http://getbootstrap.com/docs/4.0/components/dropdowns/#dropleft-variation
