### ISSUE TITLE
Scrolly via data attributes not scroll to really accurate

### ISSUE THREAD

**Issue by huy23121994** [twbs/bootstrap#25187]
When I try to use scrollpy via data attributes, it don't scroll to really accurate but it work perfect via javascript

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by huy23121994** [comment]
Oh sorry, I found my mistake, I set wrong data-offset. Close this issue please
