### ISSUE TITLE
.dropdown does not display inline with sibling anchors

### ISSUE THREAD

**Issue by Kramb** [twbs/bootstrap#25183]
Simply adding `display: inline-block` seemed to fix the issue in the test case provided.

[.dropdown display inline-block](https://codepen.io/Kramb/pen/YYxKyG)

**Comment by ysds** [comment]
> .dropdown does not display inline

I'm sure this is correct expected behavior. Also your way to fix is correct too. But a most simply way is use of `.btn-group`:

```html
<div class="btn-group">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
    Dropdown button
  </button>
  <div class="dropdown-menu">...</div>
</div>
```

**Comment by gijsbotje** [comment]
default behavior for a div is block, in your case (and any case really) a button element would be a better on to use

**Comment by mdo** [comment]
Correct, functioning as intended.
