### ISSUE TITLE
Improvement for outline and split buttons

### ISSUE THREAD

**Issue by ansem78** [twbs/bootstrap#25190]
Outline buttons, when clicked, have the same style as normal clicked buttons, but the button text gets black. I think the style of clicked buttons must be consistent between outline and normal ones. In some color variant (especially the btn-outline-dark and btn-outline-secondary), text has bad contrast with the background when the button is clicked.

Split buttons might have a vertical border to visually separate the two buttons, as in version 3. They now are rendered with more space between text and caret than normal dropdown buttons. But each button clickable area is not well delimited visually. In mobile devices, there is not a :hover state, so the user can not see where the first button ends and where the second one starts until he/she has clicked on it.

**Comment by mdo** [comment]
Outline buttons have since been fixed in `v4-dev`. Split buttons won't see any stylistic changes—they're intentionally simplified for easier customization.
