### ISSUE TITLE
Add second example for card - image overlays

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#25198]
Basic example for [card - image overlays](http://getbootstrap.com/docs/4.0/components/card/#image-overlays) create `.card` with height by `.card-img`
> This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.

For create card with short height by `.card-img-overlay` need add some changes in example:
[codepen demo](https://codepen.io/WinterSilence/pen/KZvYqW)
~~~
<style>
.card-body { z-index: 1; }
.card-img-overlay { z-index: 0; overflow: hidden; padding: 0; }
.card-img-overlay .card-img { width: auto; height: 100%; }
</style>
<div class="card">
  <div class="card-img-overlay">
    <img class="card-img" src="..." alt="Card big image">
  </div>
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is short version.</p>
  </div>
</div>
~~~

**Comment by mdo** [comment]
I'm inclined to close this as a won't fix. We generally don't add examples with that much customization to them as it's outside the scope of the project. If folks find this code lacking, I'll happily revisit.

**Comment by WinterSilence** [comment]
@mdo "much customization" is 2 short strings of css? (`padding: 0;` = `.p-0`, `.card-img-overlay .card-img { width: auto; height: 100%; }`  = `.h-100`)? I dont want add this code as part of bootsrap because it's not important thing (`.card-img-overlay` too not important) and added as example because this is useful.
