### ISSUE TITLE
Modal documentation update

### ISSUE THREAD

**Issue by jrYeole** [twbs/bootstrap#25200]
- Operating System - WIndows 7 x64
- Browser - Firefox Quantum 57.0.3 64 bit

in the example of Vertically centered Modal documentation.

the class name **modal-dialog-centered** is not given along with **modal-dialog**

please check the link and attached image.

https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered 

![no-class-name](https://user-images.githubusercontent.com/14156850/34561449-136543a8-f170-11e7-974f-fb380f1a9f8f.png)

**Comment by zacchaeusluke** [comment]
Already fixed by #25111 & this issue has been raised before (#25178) - search before raising an issue :)

**Comment by Johann-S** [comment]
Closed thanks to @zacchaeusluke 👍
