### ISSUE TITLE
Changing/overriding $carousel-transition in _variables.scss glitches out animation.

### ISSUE THREAD

**Issue by Enkrod** [twbs/bootstrap#25203]
When you change $carousel-transition in _variables.scss things become glitchy.

The timings are off, speed varies during animation, slides glitch away and change size.

https://codepen.io/Enkrod/pen/XVeXJa (not the same way to get there, since no scss includes, but the exact same outcome)

Happens everytime, every browser, every OS.

Even when you initialize the carousel via JS things stay weird.

**Comment by Enkrod** [comment]
Had some time to look into this, the problem is that I can change the transition-duration in the SCSS but there is a seperate declaration of  `const TRANSITION_DURATION = 600` in the JavaScript without making this obvious or controllable through the 
`$(".carousel").carousel({
    interval: 5000
});`
method.

Maybe this should take it's duration from the CSS already applied to the object instead of from a constant?

**Comment by Johann-S** [comment]
Please can you update your CodePen to our latest release

**Comment by Enkrod** [comment]
Updated to beta3. Still glitchy, same problem also with the updated beta3 npm-package I use for locally processing the SCSS.

If you use `.carousel-inner {overflow: visible;}` you can get a better view of the problem. JS expects a shorter animation duration (`const TRANSITION_DURATION = 600`) while the animation time in `$carousel-transition` is now longer. Then JS deletes the slide that is pushed away before the (now slower) CSS-animation is actually done.

Either the transition-duration should not be changeable in the SCSS or the JS should read the slides transition-duration and change it's own variable to match, so slides don't get deleted too early.

I don't know yet what causes the difference in movement speed once the old slide has been deleted and why the slides get higher during sliding.
