### ISSUE TITLE
Floating point media queries don't work correctly on iOS

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#25208]
The floating point media-queries that have been introduced in beta.3 don't work correctly on iPad.

The code generated by `media-breakpoint-up` and `media-breakpoint-down` now looks like this:

```
@media (min-width: 768px) {
  .ipad-media-query-desktop {
    background: blue;
  }
}

@media (max-width: 767.99px) {
  .ipad-media-query-mobile {
    background: blue;
  }
}
```

Now with these dummy divs you'd expect only one to be blue at any given screen size:
```
<div class="ipad-media-query-desktop">I'm blue on the big screen</div>
<div class="ipad-media-query-mobile">I'm blue on the small screen</div>
```

On Chrome this works correctly if you jump back and forth between 767px and 768px, hower on iPad on portrait mode both are blue:

![image](https://user-images.githubusercontent.com/1199486/34616764-75c65db0-f239-11e7-8378-52ded76794ed.png)

**Comment by patrickhlauke** [comment]
Fixed via https://github.com/twbs/bootstrap/pull/25177

**Comment by arechsteiner** [comment]
Ah thanks. I searched for "floating" and "media" but couldn't find anything in the issues.
