### ISSUE TITLE
Custom file inputs do not show on documentation page

### ISSUE THREAD

**Issue by smlombardi** [twbs/bootstrap#25212]
## Browser and version: Safari Version 11.0.2 (13604.4.7.1.3)

Looking at https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input

I see only the buttons:

<img width="428" alt="secreenshot" src="https://user-images.githubusercontent.com/835148/34628034-e534eb7a-f230-11e7-8324-557e32458a6f.png">

**Comment by gijsbotje** [comment]
i think the docs need an update on this, the structure of the file browser has changed
therefore these components seem broken 

the actual documentation on custom file browser is here https://getbootstrap.com/docs/4.0/components/forms/#file-browser
