### ISSUE TITLE
bootsrap 4 ordering col in mobile doesnt work

### ISSUE THREAD

**Issue by SamSam79** [twbs/bootstrap#25214]
After bootstrap removed the push and pull classes, I have tried with all the way using the order class but its not working with me?

I have container with 
<div class="container">
<div class="row"> 
<div class="col-md-4  "> A</div> 
<div class="col-md-8  "> B</div> 
</div></div> 

I want to re-order this in mobile by making B show first in mobile.
I am using the latest bootstrap 4 version

**Comment by skybrandevs** [comment]
let me assist you would post a code soon

**Comment by myorangeca** [comment]
```
<div class="d-flex flex-row">
  <div class="p-2">Flex item 1</div>
  <div class="p-2">Flex item 2</div>
  <div class="p-2">Flex item 3</div>
</div>
<div class="d-flex flex-row-reverse">
  <div class="p-2">Flex item 1</div>
  <div class="p-2">Flex item 2</div>
  <div class="p-2">Flex item 3</div>
</div>
```

**Comment by mdo** [comment]
Use the order classes. https://getbootstrap.com/docs/4.0/layout/grid/#order-classes
