### ISSUE TITLE
[v4] Enabling Custom Themes (Documentation)

### ISSUE THREAD

**Issue by Renader** [twbs/bootstrap#25215]
**Usecase:**

I work at a large company and we want to use Bootstrap 4 in order to create a unified theme that we can share across our organisation. So that all teams use our customized Bootstrap instead of the official one. For sure we don't want to make any changes to bootstrap itself but only to variables. To give the teams all the freedom they need we don't want to offer compiled CSS and JS sources but rather deliver the raw sources (SCSS). 

**The Problem:**
The _custom.scss file is now gone and the official way seams to define all custom variables before the user  imports bootstrap. The default variables will then use the users value. So far so good. **But** to give users a better survey we'd love to produce our own docs. A compiled version of getbootstrap.com using our variables.

We could do this very quick and dirty by forking the bootstrap repository and adjusting the docs generation by adding a custom file or something like this. But this solution will cause problems. Especially when we think on **upstream changes** we want to include. So if we fork - we want only to do minimal changes in order to keep merge conflicts at a appropriate level and maybe Bootstrap should keep this user story in mind and even **offer a solution** to this situation.

I did a ton of google searches - and believe me this is hard since the search results are polluted - and since I'm not going to be the last one I'm opening this issue to discuss the best way, maybe implement a generic solution that works at scale and to keep track of some resources. 

Theming docs:
https://getbootstrap.com/docs/4.0/getting-started/theming/

**An example what was achieved regarding this issue for bootstrap 3:**
http://styleguide.daimler.com/bootstraptheme/

I think actually Bootstrap itself is currently running in this issue. Because for the official Bootstrap Themes [the description](https://themes.getbootstrap.com/pages/about-us) says:

> **Beautiful example pages**
> **Custom documentation**
> Several brand new, custom components
> **Source Less and JavaScript files**
> Easy build tools with Gulp

Currently all of the documentation is only working in Bootstrap 3 ([1](https://bootstrap-themes.github.io/dashboard/docs/index.html),[2](https://bootstrap-themes.github.io/marketing/docs/index.html),[3](https://bootstrap-themes.github.io/application/docs/index.html))

_______________________________________________

**Requirements - Create a custom bootstrap Theme:**

- Customized variables
- A documentation generated using customized variables
- Provide raw SCSS and JS sources that other users can consume as they consume official Bootstrap 
- As few changes as possible if a fork is even required in order to receive upstream changes

**Comment by mdo** [comment]
I've been unsure how best to respond to this. It's awesome what you were able to do with the v3 docs, and I'd suspect you could do the same to v4's. However, it'd likely be asking for more trouble than it's worth. Instead, I'd suggest rolling your own for something as potentially large and complex as this. You would definitely want to import Bootstrap and structure it as needed.
