### ISSUE TITLE
The column ordering should respect class over order in HTML

### ISSUE THREAD

**Issue by revolutionnaire** [twbs/bootstrap#25228]
I'm thinking of adding a line of code to the class `.col#{$infix}` in _grid-frameworks.scss:
`order: $grid-columns;`

May I submit a pull request to address this?

**Comment by mdo** [comment]
We have `.order-` for that :).

**Comment by revolutionnaire** [comment]
But this is to address the issue in the example that the column with the text "First, but unordered" is still first even when the column with the text "Third, but first" has a class `order-1`. Thereby, it doesn't follow the supposed declared order because the one at the beginning of the row doesn't even have a specified order and it overrules the one that has a specification to be first.

**Comment by chall8908** [comment]
To come back to this, I noticed this while perusing the docs and it feels like incorrect behavior based on the surrounding documentation:

![Demonstration](https://user-images.githubusercontent.com/315948/35161866-18b67f8c-fd07-11e7-98a7-8e550d9426aa.png)

It seems like it should be "Third, but first" -> "First, but unordered" -> "Second, but last" based on the way it's described, but I'm guessing that this is a problem with the way flexbox is designed as setting `.order-0` on the third element still doesn't place it at the front - only `.order-first` does.

I'm guessing the correct answer to this is to make the documentation more clear that the order shown is correct.

**Comment by revolutionnaire** [comment]
That's what I mean, but my solution is different. This solves the problem of not requiring adding classes to column that should be arbitrarily ordered.

All you need to do is just add `order: $grid-columns` to `.col#{$infix}` in `_grid-frameworks.scss`
