### ISSUE TITLE
Blockquotes example and others use cryptic spacing classes before their introduction

### ISSUE THREAD

**Issue by Chealer** [twbs/bootstrap#25225]
Several examples in the documentation use cryptically named classes with an effect described in [the Spacing utility's documentation](https://getbootstrap.com/docs/4.0/utilities/spacing/). For example, the example in [the documentation of Blockquotes](https://getbootstrap.com/docs/4.0/content/typography/#blockquotes) uses the mb-0 class.

For examples which precede the Spacing utility's documentation, I strongly recommend to clarify by either:

1. Just dropping these classes, which seems like a perfectly valid choice in the example I mentioned.
1. Using CSS to achieve the effect of these classes
1. Moving the Spacing section so these classes are introduced before they are used in examples
1. Using classes with clearer names (such as margin-bottom-0), if the classes used have "aliases" with clear names
1. Refering to the documentation of the Spacing utility in the description of the affected examples

Examples which follow Spacing's documentation may still be unclear for some readers, but I consider improvements for these as optional.

This was reported in ticket #23772, but the ticket was closed and I could not get it reopened.

**Comment by Johann-S** [comment]
If @mdo made the choice to close your old issue he had his own reason (explained here : https://github.com/twbs/bootstrap/issues/23772#issuecomment-327036703), so it's not a good choice to create a new one with nothing new
