### ISSUE TITLE
Adding script to modal pop up

### ISSUE THREAD

**Issue by manuel-remus-stanca** [twbs/bootstrap#25222]
Hi,
I tried to put the below script from w3schools into modal pop up window
`<script>
var text;
switch (new Date().getDay()) {
    case 6:
        text = "Today is Saturday";
        break;
    case 0:
        text = "Today is Sunday";
        break;
    default:
        text = "Looking forward to the Weekend";
}
document.getElementById("demo1").innerHTML = text;
</script>

> `
I followed the same pattern, I put it before the closing body, I put the id to a p tag, I read all related topics on stackoverflow. I used some  solutions provided there, it not worked
can be seen here
manuel-site-test.co.nf/ModalPop/

**Comment by patrickhlauke** [comment]
I'm afraid we can't help you with "how to" type questions like this. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
