### ISSUE TITLE
button-variant color parameter removed?

### ISSUE THREAD

**Issue by SerdarSanri** [twbs/bootstrap#25237]
https://github.com/twbs/bootstrap/blob/ced70da441d487efb8589acbff445d6b5fa68bb9/scss/mixins/_buttons.scss#L7

On latest alpha build, color is a parameter but for some reason in latest beta build color parameter is removed and color set to background color variable. Is this change on purpose? If so do we need to override text color of buttons each time we use? 
```
@mixin button-variant($color, $background, $border) {
  $active-background: darken($background, 10%);
  $active-border: darken($border, 12%);


  color: $color;
  background-color: $background;
....
````

**Comment by mdo** [comment]
The difference between latest alpha and latest beta is huge, so don't be surprised if other changes pop up on you. We changed this awhile back to automatically select the proper color based on the contrast it'd have with the background. So, lighter buttons get a dark gray text color and darker buttons a white text color.
