### ISSUE TITLE
<!DOCTYPE html> got me problem with layout

### ISSUE THREAD

**Issue by Files90** [twbs/bootstrap#25238]
Hi,
I'm using Bootstrap V4, the latest version, and I'm having some weird problem when I add <!DOCTYPE html> in my html. If I add it, the form I created is not centered horizontally and vertically in the window. If I remove it, the form is centered in the right way. It seems that adding <!doctype html> doesn't make work this classes .row .h-100 .justify-content-center .align-items-center

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
https://getbootstrap.com/docs/4.0/getting-started/introduction/#important-globals
