### ISSUE TITLE
Input group append/prepend missing border in non-outline button styles

### ISSUE THREAD

**Issue by jacroe** [twbs/bootstrap#25233]
In the beta 2 and previous versions of Bootstrap, there was a border separating multiple buttons on an input group addon. ([JSFiddle example](https://jsfiddle.net/rfyj5kfw/1/))

Now in the beta 3 and using the new `.input-group-append`, that border separator only appears if using one of the `.btn-outline-*` classes. ([JSFiddle example](https://jsfiddle.net/v3k8oak8/)) However, it *does* appears when using `span.input-group-text`. ([Docs](https://getbootstrap.com/docs/4.0/components/input-group/#multiple-addons))

This is happening in Chrome, Firefox, and Edge.

**Comment by mdo** [comment]
The border is there, it's just the same color as the `background-color`. This is an aesthetic choice we made to keep our default styles quite minimal.

**Comment by jacroe** [comment]
Thanks for the clarification, @mdo!
