### ISSUE TITLE
.on('hide.bs.dropdown') fires too early?

### ISSUE THREAD

**Issue by schnoodly** [twbs/bootstrap#25236]
Hey there,

Trying to add a fade animation using animate. my code:

```
$('.dropdown').each(function(){
    var item = $(this).find('.dropdown-toggle');
    var content = $(this).find('.dropdown-menu');
    var height = $(this).height() + 4.4;
    $(this).on('show.bs.dropdown', function () {
      $(content).first().stop(true, true).animate({
        left:0,
        opacity:1
      }, { duration: 150, queue: false }, 'easeOutCubic');
    });
    $(this).on('hide.bs.dropdown', function (e) {
      $(content).first().stop(true, true).animate({
        left: 50,
        opacity:0
      }, { duration: 150, queue: false }, 'easeOutCubic');
    });
    $(this).on('hover', function(){ $(item).dropdown('toggle'); });
  });
```
So, this is a custom animation for the navbar, actually. The first part works perfectly fine, the `show` animation fires all at once and looks clean - but the `hide` event hides the dropdown, then executes the `animate()` I have in there. I thought `shown` was supposed to do it after, and `show` before? Am I wrong, or is this a bug? I couldn't find anything on this for BS4, found some old stuff for BS3 though.

**Comment by Johann-S** [comment]
Please can you update your Codepen to our latest release ? (beta 3)

**Comment by schnoodly** [comment]
Updated. Nothing changed unfortunately. Very possible I'm just being dumb, though :P

**Comment by Johann-S** [comment]
I don't understand what's your bug here 😟 

The event order is : `show` --> `shown` and `hide` --> `hidden`

**Comment by schnoodly** [comment]
Apologies, I was slammed the past couple days - 

The bug, if there actually is one, is just that I cannot add any animation to the `hide.bs.dropdown` event. It just disappears. Neither CSS transition nor calling `on.('hide.bs.dropdown' ...)`, as I have in the codepen, animates the `hide` event.

So, to be specific, I want the dropdown to slide back to the right when you stop hovering/toggle again.

**Comment by Johann-S** [comment]
sorry but currently I don't see your issue as an "issue" but plus as you need help to achieve something, so I'll close this issue, if you can demonstrate that it's due to Bootstrap you're not able to animate the your Dropdown when `hide` is triggered do not hesitate to tag me and I'll reopen this issue 👍 

BTW if you want to ask question or if you need help [see our readme for more details](https://github.com/twbs/bootstrap#community).

**Comment by schnoodly** [comment]
I've updated the Codepen with a barebones representation - and a `collapse` that has the same exact settings, but actually works.

Is this proper way to report the issue? @Johann-S 

Again, the `hide` event appears to happen before any animation is done. it just disappears without `left` or `opacity` animating, which you can compare to the `collapse` that works below it.

## [updated codepen](https://codepen.io/schnoodly/pen/pppqRo)
