### ISSUE TITLE
[v4 beta-3] Dropdown menu appearing off screen

### ISSUE THREAD

**Issue by joeybk85** [twbs/bootstrap#25243]
This started hapenning when I upgraded from beta 2 to beta 3:

When a dropdown menu is position near the edge of the screen, it appears partly off screen when opened.

This seems to happen with Chrome and Firefox, I haven't tried other browsers.

Here is a snippet:
https://codepen.io/anon/pen/baLrQP

And this is what it should do (beta 2):
https://codepen.io/anon/pen/EoQvzX
  
(Note that the version of popper.js is different, so I don't know if this is a popper.js bug, or a Bootstrap configuration bug)

**Comment by Johann-S** [comment]
it's related to Popper.js because if you use `1.11.0` (instead of `1.12.9`) in beta 3 everything is fine

/CC @FezVrasta

**Comment by FezVrasta** [comment]
I think it's this one https://github.com/FezVrasta/popper.js/issues/251

**Comment by sagudev** [comment]
Still same in Bootstrap 4 stable.

**Comment by sagudev** [comment]
Still same in Bootstrap 4 stable.

**Comment by danieluyo** [comment]
```
"bootstrap": "^4.0.0",
"popper.js": "^1.11.0",
```
![captura de pantalla 2018-02-20 a las 23 11 06](https://user-images.githubusercontent.com/17558554/36464098-819cedf6-1693-11e8-937f-17a1f7bdc6e7.png)

**Comment by miguelmich** [comment]
Yes, it's happening on last stable version:
![image](https://user-images.githubusercontent.com/662930/36569612-7fc471ba-17fc-11e8-9aeb-eb2b9a1df493.png)

Do you guys know if there's a workaround for this? thanks in advance :)

**Comment by FezVrasta** [comment]
FezVrasta/popper.js#251 has been fixed but I can still reproduce this problem.

If anyone could be so kind to open an issue on FezVrasta/popper.js providing a CodePen repro of the problem (without Bootstrap code) that would be awesome.

Without that I can't be sure if the problem relies in some Bootstrap logic or in Popper.js itself.

**Comment by XhmikosR** [comment]
Is this still an issue?

**Comment by sagudev** [comment]
Yes, it is.
https://codepen.io/anon/pen/REBbPe

**Comment by yamijuan** [comment]
Hi, is there any workaround to fix this?

**Comment by FezVrasta** [comment]
This invite is still valid 👌

https://github.com/twbs/bootstrap/issues/25243#issuecomment-380520537

**Comment by mdo** [comment]
https://codepen.io/emdeoh/pen/gOwjNvQ still shows an issue, but this can also be handled with the `.dropdown-menu-right` class in v4, so closing out as stale.
