### ISSUE TITLE
IE11: Figure with .img-fluid is not resized 

### ISSUE THREAD

**Issue by bentrm** [twbs/bootstrap#25242]
The fluid image in a figure container is not resized at all making it overflow the content area.

On MacOS with Safari 11.0.2 it looks fine:
![macos-safari](https://user-images.githubusercontent.com/1186959/34723302-62691f00-f54a-11e7-921f-e5eca9be8259.png)

On Win 7 with Internet Explorer 11 .0.9600.18015 it looks like this:
![bildschirmfoto 2018-01-09 um 14 36 47](https://user-images.githubusercontent.com/1186959/34723357-8c7062b8-f54a-11e7-9731-03b05026996a.png)

Does seem to be somewhat related to `display: inline-block` on `figure` as deactivating that property (falling back to 'display: block' makes it look fine on IE11:
![win7-ie11-display](https://user-images.githubusercontent.com/1186959/34723297-5da039c2-f54a-11e7-8160-eeab046e95a9.png)

There have been related issues (#20970, #21360, #21886, #21888) describing this behavior for older versions of Firefox or which are closed to inactivity. There doesn't seem to be a fix for IE11 (which is a supported version I suppose).

I created a [minimal example on JS Bin](http://jsbin.com/yewehaz/1/edit?html,output).

**Comment by jonathangreco** [comment]
easy pick

**Comment by Geshtu** [comment]
.img-responsive has the max-width:100%; display:block; and height:auto; styling. I wonder if the 'Reponsive Images' section on https://getbootstrap.com/docs/4.0/content/images/ should be updated from .img-fluid to .img-responsive?

**Comment by XhmikosR** [comment]
Fixed in #30809.
