### ISSUE TITLE
Incorrect example code on website docs

### ISSUE THREAD

**Issue by whittredge** [twbs/bootstrap#25240]
Hello Bootstrap team, thanks so much for providing a great product!

I believe the example code displayed on getbootstrap.com for a Vertically Centered Modal ([here](http://getbootstrap.com/docs/4.0/components/modal/#vertically-centered)) may be incorrect.  In the prose description before the code, you all write "Add `.modal-dialog-centered` to `.modal-dialog` to vertically center the modal."  However class `.modal-dialog-centered` does not appear anywhere in the example code.  The class _is_ contained in the html source for the correctly functioning button and demo modal.

Again, thank you sincerely for your continued efforts on this superlatively helpful project.

**Comment by Johann-S** [comment]
Already fixed by : #25111 
and will be available in our next release thanks 👍

**Comment by whittredge** [comment]
My mistake! 😅
