### ISSUE TITLE
Dependency 'popper.js' in define statement should be renamed

### ISSUE THREAD

**Issue by FuweiChin** [twbs/bootstrap#25256]
Bootstrap Version: 4.0.0-beta.3

### Background
1. Popper.js doesn't declare itself with a module id.
2. Bootstrap requires popper.js with module id 'popper.js' when working with RequireJS. 

### Problem
When using Bootstrap with RequireJS:  

1. I have to put popper.js directly under the `baseUrl`  directory configured for RequireJS since the `paths` config doesn't work for name which ends with '.js', at lease in my case.
2. if I want to use minimized edition of popper.js, I have to rename `popper.min.js`  to `popper.js`

```js
window.require={
  "jquery": "/ajax/libs/jquery/3.2.1/jquery.min",
  "popper.js": "/ajax/libs/popper.js/1.12.9/umd/popper.min.js",//DOESN'T WORK for require(["popper.js"])
  "bootstrap": "/ajax/libs/bootstrap/4.0.0-beta.3/js/bootstrap.min",
};
```

### Solution
It is necessary to change the define statement from `define(['exports', 'jquery', 'popper.js'], factory)` to `define(['exports', 'jquery', 'popper'], factory)`

```js
window.require={
  "jquery": "/ajax/libs/jquery/3.2.1/jquery.min",
  "popper": "/ajax/libs/popper.js/1.12.9/umd/popper.min",//WORKS FINE  for require(["popper"])
  "bootstrap": "/ajax/libs/bootstrap/4.0.0-beta.3/js/bootstrap.min",
};
```

**Comment by Johann-S** [comment]
Your issue is related to RequireJS see : https://github.com/requirejs/requirejs/issues/1560 and see this issue on Popper.js : https://github.com/FezVrasta/popper.js/issues/405

Not sure we are able to do fix that because we rely on Rollup to bundle our files

**Comment by nE0sIghT** [comment]
Looks like setting "nodeIdCompat" RequireJS options is simpliest workaround for this issue.
With that option it's possible to define "popper" module paths.

**Comment by mikila85** [comment]
how to solve this problem?
