### ISSUE TITLE
[v4-beta 3] "navbar sticky-top" does not work in <header>

### ISSUE THREAD

**Issue by poilozorey** [twbs/bootstrap#25258]
The "**sticky-top**" position of the navigation bar does not seem to work when it is taken in the **< header >**:
```
<header>
<nav class="navbar sticky-top ... "> ... </nav>
</header>
```

Look here :
**Sticky-top normal (it's ok !)**
https://codepen.io/anon/pen/PEEbrp

Look here :
**Sticky-top in < header > (does not work)**
https://codepen.io/poilozorey/pen/mpxyPB

**Comment by 719media** [comment]
This is not a bug in bootstrap. This is a misunderstanding of how to apply position: sticky in CSS. You've created a containing block with <header>, whose height is defined by the navbar itself, and so it has nowhere to flow to.

Read something like this: https://gedd.ski/post/position-sticky/ before creating an issue

**Comment by mdo** [comment]
Yup, as mentioned this isn't a Bootstrap bug. Positioning in CSS is a little picky at times, so best of luck!

**Comment by tomasts248** [comment]
Question: if I want to use the navbar inside the header tag, how should it be done?
