### ISSUE TITLE
[request] Adding .col behavior to different media breakpoints

### ISSUE THREAD

**Issue by eeaquino** [twbs/bootstrap#25268]
As of now using .col to fill up rest of space works great, but it will be the same no matter the size of the screen. 

I think it would be good to have a way to have that behaviour applied to all breakpoints, that way I could have something like .col-md that fills up the remaining space on my flexbox only if I am in the md breakpoint; then use .col-12 to make it have its own line on smaller screens. 

Not sure if there is already something like this or if it can be achieved by combining other classes, it just seems more straight forward to have something like this. 

Thanks for all the great job you do!

**Comment by mdo** [comment]
We already have those—`.col-md` and the like.
