### ISSUE TITLE
main Boostrap site having issues

### ISSUE THREAD

**Issue by drmscpxl** [twbs/bootstrap#25262]
main site giving a notification 

Error 522 Ray ID: 3daf8b641a4b17ec • 2018-01-10 12:12:56 UTC
Connection timed out

also when typed url just like this in browser: getbootstrap.com is not secured 

just a heads-up though, probably not a big issue

**Comment by mdo** [comment]
There's an open issue for me to look into 100% `https`, but otherwise site seems to be working fine for me. Closing out.
