### ISSUE TITLE
[4.0.0-beta.3] Headers (h1, h4...) doesn't add line break

### ISSUE THREAD

**Issue by priverop** [twbs/bootstrap#25263]
Hello,

# ISSUE
- Headers (h1, h2...) doesn't add a line break as any block should do.

# TECH
- Bootstrap 4.0.0-beta.3
- jQuery 3.2.1

# EXAMPLE
[This codepen](https://codepen.io/anon/pen/ZvxpdW) shows what I'm talking about.

I didn't find anything with the search function, nor in the last commits. Is this a bug?

**Comment by apuntovanini** [comment]
@priverop if you wrap them in a row (that uses flex), they properly don't add a line break. For what you need you should remove the div class="row"

**Comment by bkdotcom** [comment]
you either have a row div you don't need, or you forgot a col div

```html
  <div class="container">
    <div class="row">
      <div class="col">
      <h2>Yes line break</h2>
      <h4>I'm so happy</h4>
      </div>
    </div>
  </div>
```

or

```html
  <div class="container">
      <h2>Yes line break</h2>
      <h4>I'm so happy</h4>
  </div>
```

**Comment by priverop** [comment]
That's perfect. Didn't know that.

Thanks.
