### ISSUE TITLE
Control multiple tabs with one nav

### ISSUE THREAD

**Issue by User934903920432** [twbs/bootstrap#25260]
Hi,

You used to be able to control multiple tab-contents with one nav-bar with Bootstrap 3.
E.g: http://jsfiddle.net/ju9sV/6/

However when I try this it doesn't seem to work with v4.
E.g: http://jsfiddle.net/ju9sV/196/

Does anybody know how to fix this or knows a workaround that works ?

**Comment by Johann-S** [comment]
Related to : #19964

Closed for consistancy
