### ISSUE TITLE
Menu form is broken in input group

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25278]
When using a [menu form](http://getbootstrap.com/docs/4.0/components/dropdowns/#menu-forms) in a input group, the form controls in the dropdown will be broken.

![image](https://user-images.githubusercontent.com/4065765/34853303-5f560a98-f776-11e7-8672-1cfec1a400fb.png)

Demo: https://jsfiddle.net/tdf22y9t/

The usability of such UI may be questionable, but does bootstrap support this usage? If support it, hopefully I can work on solving this problem by adding a selector `>`.

**Comment by mdo** [comment]
Yes, we should support it.

**Comment by ysds** [comment]
OK 👍 I created a PR.

**Comment by slidenerd** [comment]
Yup i double side this. Also try adding 2 input groups with a dropdown form in each, one of them ends up broken

**Comment by ysds** [comment]
Could you make a pen?

**Comment by slidenerd** [comment]
Sure thank you for the quick response @ysds [HERE ](https://codepen.io/zupkode/pen/jYpYOm) is the pen Once you expand the dropdown menu and inspect element, you ll notice that only one of them has the form inside while the other one doesnt, any suggestions are super appreciated

**Comment by ysds** [comment]
The bootstrap CSS on your pen is not latest v4-dev. Also, I'm not sure your problem related this issue.

**Comment by slidenerd** [comment]
Thank you for pointing that out. I updated it to the latest bootstrap version 4 beta 3 , the issue still exists :)
