### ISSUE TITLE
bootstrap 4 modal too wide with wide page content 

### ISSUE THREAD

**Issue by zspitzer** [twbs/bootstrap#25276]
When content on the page is wider than the mobile screen width, 
the modal sizes itself too wide on mobile devices

https://plnkr.co/edit/EFMyr1yFhaOOPzL1d7Ug?p=preview

**Comment by zspitzer** [comment]
setting a max-width on .modal using $(window).width() is a quick workaround

**Comment by andresgalante** [comment]
Hi @zspitzer I don't think this has nothing to with the modal. The fixed width div is causing the overflow.
