### ISSUE TITLE
Include Easy Navigation in Docs for versions

### ISSUE THREAD

**Issue by LeAcid** [twbs/bootstrap#25275]
As I am sure you are all aware the majority of bootstrap users will still have things on bootstrap 3. Personally, I have a few projects on 4 and a few on 3 and some really old stuff on 2. I think it would be beneficial to include a drop-down with links to previous versions docs as a lot of projects on the older versions are internal tools and we don't have the time to upgrade. I know its a little thing but I think it would be a very welcomed feature on the site.

If this is the wrong repo to be posting this please let me know and I will move it over.

**Comment by wolfy1339** [comment]
There actually is a dropdown menu for selecting v4, v4-alpha6, v3, and v2

**Comment by LeAcid** [comment]
I see it now, haha I feel like a fool. Thanks for the reply!
