### ISSUE TITLE
Wizard Style Navigation Tabs

### ISSUE THREAD

**Issue by FritzHerbers** [twbs/bootstrap#25286]
Besides tabs and pills add a wizard style navigation tab.

See http://benjii.me/2014/03/wizard-style-navigation-tabs-for-bootstrap/ for a demo.

See https://gist.github.com/tiesont/5b291c8344944f22c3d67cb902464048 for some more recent css.

**Comment by venusvavadiya** [comment]
Is this an issue? If this is to promote or show an implementation of Bootstrap, this might not be a good place to showcase it.

**Comment by mdo** [comment]
No plans for adding this to the core project. Thanks though!
