### ISSUE TITLE
Toggle modals don't function correctly

### ISSUE THREAD

**Issue by DigitalAndSEO** [twbs/bootstrap#25285]
I have 2 modals:
#modalWebs
#modalSEO

In the #modalWebs have a link (with class".closeModalWebsOpenModalSEO") to #modalSEO. To action use this code:

```
$(document).on('click', '.closeModalWebsOpenModalSEO', function () {
  $('#modalWebs').modal('hide');
  $('#modalWebs').on('hidden.bs.modal', function () {
    $('#modalSEO').modal('show');
  })
});
```

It works perfectly.
The problem is that when you open #modalWebs in a normal way and close it with the "close" button or whatever the event is, the #modalSEO opens automatically again always by default.

View: https://www.digitalandseo.com/indexgerard.php

In the same way, I provided the data-toggle and modals do is overcome one another.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bkdotcom** [comment]
> The problem is...

The problem is that you register a `hidden.bs.modal` event listener on `#modalWebs` every time you click `.closeModalWebsOpenModalSEO`

so, no matter how `#modalWebs` gets closed, it's going to trigger that event.

**Comment by DigitalAndSEO** [comment]
Resolved to put off event.
Thanks.
