### ISSUE TITLE
No Top Border for Additional Card Header

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#25283]
It seems there is no native way to add a top border when adding an additional card header.

```
<div class="card">
<div class="card-header">
<h4 class="card-title">Header 1</h4>
</div>
<div class="card-body">
<p class="card-text">Stuff 1</p>
</div>
<div class="card-header">
<h4 class="card-title">Header 2</h4>
</div>
<div class="card-body">
<p class="card-text">Stuff 2</p>
</div>
</div
```
![capture](https://user-images.githubusercontent.com/5879776/34859606-666c6a86-f7ab-11e7-9bf1-308f5fb8afe3.PNG)

**Comment by mdo** [comment]
I don't think we'd add much for this—does `.border-top` help?

**Comment by chrisbo** [comment]
It seems there is only a border-top-0 class. However, I fixed my issue by adding a border-top style. In hindsight, a bit unorthodox adding a second header.

**Comment by mdo** [comment]
Oh sorry, v4 stable will be adding the additional border utilities. See #25021.
