### ISSUE TITLE
Bootstrap Lock Glyphicon not visible in IE11

### ISSUE THREAD

**Issue by sameerpanicker** [twbs/bootstrap#25298]
I am opening this issue because there are many posts similar to this issue but none has an precise answer.

Here is my current issue - There are some glyphicons in my application that are not getting displayed in IE11 but it works fine on Chrome. Since, my application users are only using IE this is a open problem.

Here are few things about my application. 
MVC .NET 4.5 web application deployed on Windows 2012 R2 Servers.
jquery-3.2.1.js and Bootstrap v3.3.7 are used.

The icon which I am facing a problem is at the login window where there are User Name and Password boxes and a user (glyphicon-user) and password (glyphicon-lock) icons are present

Issue is the password icon (lock) is not visible in IE11, only user is getting displayed.

I checked the bootstrap css class and I can see that there is a value for lock.

.glyphicon-user:before {
    content: "\e008";
}
.glyphicon-lock:before {
    content: "\e033";
}

I am using <link rel="stylesheet" href="~/Content/bootstrap.min.css"> this line for having bootstrap included in my project.

The password icon is displayed if I use below line instead of the above - 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

I have checked if the contents are same. They are the same. 

Can anyone please let me know what am I missing here? I have checked all the values using Chrome and IE console and everything looks same to me.

Please help !!!

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._

---

Also, you haven't included a live demo of your particular problem. No one can help without that. Feel free to ask around in our Slack or on StackOverflow, too.

**Comment by SaranganBaskar** [comment]
Hi Team, Regarding Glyph icon issue in IE browser (IE 11) issue, I am using Bootstrap (v 3.3.7). It's not working for me too. Kindly suggest
