### ISSUE TITLE
Modal live demo code may be incorrect.

### ISSUE THREAD

**Issue by andrewnding** [twbs/bootstrap#25291]
The current code for the live demo modal doesn't work if copied https://v4-alpha.getbootstrap.com/components/modal/#live-demo. The button that opens the modal has `data-target="exampleModal"`, but the modal's id is `id="myModal"`. I inspected the button and modal and they have a data-target and id of `exampleModalLive` and was thinking that the data-target and the id should be updated to `exampleModalLive` to match what's on the page and so that the code works.

**Comment by gijsbotje** [comment]
please try with the latest documentation and release
the link you mention is for the alpha version and is outdated, we're at beta3 at the moment
go to http://getbootstrap.com/docs/4.0/components/modal/ for the latets modal docs
