### ISSUE TITLE
New custom checkboxes/radios doesn't work when no ID (label for) is set

### ISSUE THREAD

**Issue by phip1611** [twbs/bootstrap#25296]
The new custom control checkboxes/radios doesn't work when no ID (label for) is set, because now the input element can't be clicked but only the label, because the label contains the custom checkbox/radio indicator. If no `for="an_id"` is set, the checkbox/radio can't be clicked.

A solution would be to always use IDs and label for, but e.g. in my Angular SPA I'm not using HTML ID's at some variable parts of the app.

Is that intentional behavior?

**Comment by mdo** [comment]
Yes, it's intentional. See our latest blog post and migration docs.
