### ISSUE TITLE
IE Edge and col-*-auto isn't working correct

### ISSUE THREAD

**Issue by icehawk-de** [twbs/bootstrap#25309]
bootstrap-beta-3

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
Win 10 x64
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Edge (Microsoft Edge 41.16299.15.0, Microsoft EdgeHTML 16.16299)

I show you the problem with screenshots:

Fig1. html-code.jpg
This ist the html-structure I use. CSS is core.
![html-code](https://user-images.githubusercontent.com/19264337/34930287-2337469e-f9c9-11e7-9807-d8df8f003127.JPG)

Fig2. view-edge.jpg
The view in IE Edge
![view-edge](https://user-images.githubusercontent.com/19264337/34930313-36fedaf2-f9c9-11e7-945b-8619fda50ca7.JPG)

Fig3. view-other.jpg
Expeced view in IE Edge (other browsers FF, Chrome shows correct)
![view-other](https://user-images.githubusercontent.com/19264337/34930388-7e71046e-f9c9-11e7-9d3a-3a05ba936585.JPG)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by icehawk-de** [comment]
OK, sorry. I've done a codepen demo now:
https://codepen.io/Icehawk/pen/ZvjRON

Bootstap:
**bootstrap 4 beta 3**
OS:
**Win 10 (x64)**
Browser with problem:
**Edge (Microsoft Edge 41.16299.15.0, Microsoft EdgeHTML 16.16299)**

Chrome & Co it is and should be
test  test  test  test

In IE Edge it is:
test  test
test  test

**Comment by mdo** [comment]
You're unnecessarily nesting grid classes—that outermost row and `col-xl` don't seem necessary at first glance. This also sounds like one of the [flexbugs](https://github.com/philipwalton/flexbugs)—you likely need a `.w-100` somewhere.
