### ISSUE TITLE
Dropright/dropleft is broken on navbar or with static position

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25304]
I wondered why `position: relative` is not given to dropright and dropleft, so examined any influence. 

Related code:

https://github.com/twbs/bootstrap/blob/ed286e0f3d7a376087bcb990f5721dff73153d50/scss/_dropdown.scss#L2-L5

Then, I found a position of dropright or dropleft is not as expected when using it on a navbar. [Demo](https://codepen.io/anon/pen/ppZrjW) Please see on a large screen.

Also, a dropright/dropleft outside navbar works well since it is positioned by popper, but if disable poper (#24092) it will break position.

**Comment by Johann-S** [comment]
Yep we made the choice a few release before to not enable Popper.js in our navbar component but with `.dropleft` or `.dropright` I'm not sure if we'll have the choice to not use Popper.js

**Comment by mdo** [comment]
Perhaps we limit left/right to everything but navbars? Or do we try to do some basic positioning for them inside navbars?

**Comment by ysds** [comment]
Resolved in #25400
