### ISSUE TITLE
Bug in Bootstrap 4 Beta 3: Custom file input not displaying properly

### ISSUE THREAD

**Issue by WebDevBooster** [twbs/bootstrap#25314]
Simply visit this URL to see the issue: 
https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input

The borders of the input fields next to the upload buttons aren't visible.

**Comment by WebDevBooster** [comment]
Also, clicking the buttons or the "Upload" span doesn't do anything. A click on one of those should trigger the same action as the click on the input field.

**Comment by WebDevBooster** [comment]
Thirdly, the text entered in the `custom-file-control` span should be set to "white-space: nowrap" to prevent it from wrapping.

**Comment by gijsbotje** [comment]
i believe this was fixed on the v4-dev branch
https://github.com/twbs/bootstrap/issues/25212

**Comment by patrickhlauke** [comment]
indeed
