### ISSUE TITLE
Missing .modal-dialog-centered class in Modal Documentation

### ISSUE THREAD

**Issue by brecons** [twbs/bootstrap#25329]
Within the demo code of a centered modal dialog in docs the `.modal-dialog-centered` is missing:

This:
```
<div class="modal-dialog" role="document">
</div>
```
must be:
```
<div class="modal-dialog modal-dialog-centered" role="document">
</div>
```

**Comment by Johann-S** [comment]
Already fixed by : https://github.com/twbs/bootstrap/pull/25111
will be available in our first stable thanks
