### ISSUE TITLE
[v4 beta-3] bug: d-inline-block text-truncate doesn't work properly

### ISSUE THREAD

**Issue by WebDevBooster** [twbs/bootstrap#25321]
The output of the `d-inline-block text-truncate` classes is buggy when the span with those classes is surrounded by text within a paragraph. 

In other words, the output of this: 

`<span class="d-inline-block text-truncate" style="max-width: 150px;">dolor sit amet, consectetur adipiscing elit. Phasellus tristique, dui vitae pharetra sollicitudin, felis metus dignissim sapien, at sodales libero massa condimentum dui.</span>`

will be shifted 6px above the baseline of the text that surrounds it in a paragraph.

**Comment by mdo** [comment]
`inline-block` is different from `inline`, and has a different `vertical-align`. You'll need to adjust that as your code requires. We have some utility classes for that, too.
