### ISSUE TITLE
[v4 beta-3] bug: dropdown('dispose') method doesn't seem to work.

### ISSUE THREAD

**Issue by WebDevBooster** [twbs/bootstrap#25323]
Just came across the following SO post. 

According to that the `$().dropdown('dispose')` method doesn't seem to work... 

https://stackoverflow.com/questions/48243220/bootstrap-destroys-an-element-s-dropdown

**Comment by mdo** [comment]
Is there a live demo of the problem?

**Comment by xiuno** [comment]
I have the same problem, becuase in modal dispose, only clear the variable to null, but DOM not removed. 

File: bootstrap.js Line: 2047:

    _proto.dispose = function dispose() {
      $$$1.removeData(this._element, DATA_KEY);
      $$$1(window, document, this._element, this._backdrop).off(EVENT_KEY);

      
      // fix by axiuno: remove the DOM
      **$(this._dialog).remove();
      $(this._backdrop).remove();
      $(this._element).remove();**

      
      this._config = null;
      this._element = null;
      this._dialog = null;
      this._backdrop = null;
      this._isShown = null;
      this._isBodyOverflowing = null;
      this._ignoreBackdropClick = null;
      this._scrollbarWidth = null;
    };

**Comment by Johann-S** [comment]
Our dispose method : clear listener and our variables that's all see : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L187

**Comment by Johann-S** [comment]
@xiuno what you linked isn't the dropdown's dispose method

**Comment by xiuno** [comment]
modal have the same problem, dropdown I have not use yet.

**Comment by Johann-S** [comment]
I don't see issue in Dropdown and Modal but if you have an issue please create a new issue with a live example which show your bug @xiuno

**Comment by WebDevBooster** [comment]
I'm glad to hear that @xiuno can confirm the problem and provide further information. I myself have absolutely no clue about this particular problem. I just saw that post on SO and thought it would be a good idea to alert you guys about this issue.

**Comment by mdo** [comment]
@Johann-S I'm unsure where in the source code this is an issue, but I tried disposing `.dropdown.show` from the Safari inspector and it did nothing. Using `toggle` worked perfectly though.

**Comment by Johann-S** [comment]
Dispose should only clear our internal vars that's all but if you prefer we can add this behaviour to close the current Dropdown

**Comment by mdo** [comment]
Hmm, maybe that's the problem. Folks are expecting `dispose` to destroy it, but it's unclear what that means. If `toggle` is the only way to remove, we need to clarify our docs everywhere to explain that.

**Comment by peterblazejewicz** [comment]
@WebDevBooster 
The BS listens for document-level events and matches instances via data attrib. So on next event the control is being rebuilt from the ground up (the 'destroy' does what it means, the 'create' phase is not obvious here).
This will remove and deactivate:
```js
$().dropdown('dispose').removeAttr('data-toggle')
```
or better (less obtrusive):
```js
$('.dropdown-toggle').dropdown('dispose').prop('disabled', true)
```

**Comment by woto** [comment]
Oh, may be it will help to locate the problem https://codesandbox.io/s/bootstrap-dropdown-demo-forked-ds6k4?file=/src/index.js
Thought that I'm doing something wrong :(

**Comment by mdo** [comment]
Is this still relevant?

**Comment by woto** [comment]
Can't say. Do not use this feature. Also switched to v5

**Comment by mdo** [comment]
Closing as stale.
