### ISSUE TITLE
form-inline disappearing checkbox in Chrome Linux

### ISSUE THREAD

**Issue by bischofb** [twbs/bootstrap#25336]
Using dev-v4 with Chrome on Linux Ubuntu. Note: this works fine when I test with Chrome on Windows. 

When using checkbox with form-inline and it the label is more than one line, the checkbox keeps getting smaller and smaller. Thus, two lines of makes the checkbox smaller and four lines makes is super small. Effectively the label text is "squeezing out" the space available for the checkbox to appear. This only happens with form-inline. I tested without form-inline and the checkbox stays the same size regardless of how many lines of text appear next to it.

```
<form class="form-inline">

<div class="form-check col-sm-2">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
  <label class="form-check-label" for="inlineCheckbox1">1 asdf sdfasdf asdf asdfasdf asdf asdf asdf asdf asdf sdaf asfd </label>
</div>

</form>
```

![checkboxsmall](https://user-images.githubusercontent.com/1018692/35011664-d67be870-fabb-11e7-84a8-eaf07fecbc62.png)

**Comment by mdo** [comment]
I imagine your problem is the `.col-sm-2`. Generally speaking, we don't allow grid classes to be mixed with other component classes—too much chance for interference and buggy behaviors. Do you have a link to the codepen you created?

**Comment by bischofb** [comment]
Here is a link. It works fine on Windows Chrome but not in Linux Chrome.
https://jsfiddle.net/bischofb/po83a34e/2/

**Comment by bischofb** [comment]
I looked at the sample code in the docs for checkboxes and changed it to form-inline. Here is the jsfiddle for it (I removed the non-checkbox components for simplicity).
https://jsfiddle.net/bischofb/po83a34e/3/
