### ISSUE TITLE
[v4 beta-3] Scrollspy: issues with Firefox

### ISSUE THREAD

**Issue by Vitaliy-1** [twbs/bootstrap#25335]
Don't know really if it is a bug. 
I am using Scrollspy for spying on elements just like in Bootstrap documentation. With Google Chrome all work ideally, but when using Firefox, it can be seen that on clicking an item from the menu the previous menu item becomes active (but not the one that was clicked).
You can see the example from the Bootstrap site by clicking these items on Firefox browser (except item 3-2):
http://getbootstrap.com/docs/4.0/components/scrollspy/#item-1-2

**Comment by mdo** [comment]
Confirming this is still an issue in v4.1.

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
