### ISSUE TITLE
Blogger comment box doesn't work on mobile devices

### ISSUE THREAD

**Issue by ac-barros** [twbs/bootstrap#25344]
Hi,
I'm having a problem with the comments box on my blogger template and I hope you can help me.

I'm having trouble with readers being able to submit comments on my blog. If they send a comment from a PC/Mac, it goes through, but if they try from a mobile device or tablet the comment box just doesn't work (it shows up but the items are not clickable).

How can I fix this? I've tried everything (from different platforms, with and without Google login) but it doesn't seem to work. The template designer isn't available to fix the problem right now so I have to fix it myself.

Here's my website: http://www.dimplesblog.com/

Thanks

**Comment by patrickhlauke** [comment]
sorry, but this is not the right place to ask for help with specific implementations. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
