### ISSUE TITLE
Touch target sizing/spacing

### ISSUE THREAD

**Issue by Nettsentrisk** [twbs/bootstrap#25346]
A key accessibility and usability concept is to provide large enough click/touch targets.

Apple, Google, etc. have recommendations on touch target sizing/spacing.

From [Google's Material Design guidelines](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-sizing-by-increments):

> To ensure balanced information density and usability, touch targets should be at least 48 x 48 dp. In most cases, there should be 8dp or more space between them.
>
> Size elements at least 48dp high and wide to ensure a physical size of about 9mm regardless of screen size. The recommended target size for touchscreen objects is 7-10mm.

Bootstrap should incorporate the possibility of this sizing and spacing through Utilities.

For example, if I'm making a button group or button toolbar, I want to ensure that the buttons are spaced properly in line with usability recommendations (at a minimum), and that the buttons themselves are a minimum size to make them easily clickable/touchable.

**Comment by mdo** [comment]
Closing as stale. We long ago removed the `xs` variants to our buttons and more. I don't think we need anything in our docs to recommend sizes here given how much variance there is across native web elements and controls.
