### ISSUE TITLE
[v4 beta-3] form-control-lg class does not increase checkbox size

### ISSUE THREAD

**Issue by WebDevBooster** [twbs/bootstrap#25341]
According to this: https://getbootstrap.com/docs/4.0/components/forms/?#sizing

the `form-control-lg` class is supposed to increase the size/height. That does not happen in the case of a checkbox. 

Code: 
`<div class="custom-control form-control-lg custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck1">
        <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
    </div>`

The result of the above code is the increased font size of the label but the size of the checkbox does not increase.

**Comment by WebDevBooster** [comment]
Correct me if I'm wrong but I believe adding the following css would fix the issue: 

`.custom-control-label::before, 
        .custom-control-label::after {
            top: .8rem;
            width: 1.25rem;
            height: 1.25rem;
        }`

**Comment by mdo** [comment]
Those classes only apply to textual inputs. They’re documented under a heading a paragraph that explains this. As it stands right now, we won’t be customizing native radios/checkboxes. We have the custom ones for that.
