### ISSUE TITLE
Feature request beta-3: Add a class that mimics dropdown-item:hover

### ISSUE THREAD

**Issue by scottieslg** [twbs/bootstrap#25349]
I have a custom drop down that I've created, which includes functionality to use the arrow keys to move up and down the list.  

As of right now, the only way to highlight an item is with li.dropdown-item:hover.  I have no way to highlight an item using a class.

I would like to propose adding a class that I can add to my li.dropdown-item that will mimic the hover style.

**Comment by mdo** [comment]
No plans to add this just yet—going to punt on it given we'd likely need to add this everywhere if we do it in one place.
