### ISSUE TITLE
Tooltip not getting closed after click a anchor tag in angular js 

### ISSUE THREAD

**Issue by meeravalishaik** [twbs/bootstrap#25342]
Bootstrap tool tip is not getting closed after clicking on anchor tag having uisref attribute  i used trigger:"hover" worked in  chrome but not working in firefox ie11  please check the screenshot 
![capture](https://user-images.githubusercontent.com/13207250/35047504-140a28e2-fb92-11e7-94bf-5428669f4666.PNG)

**Comment by meeravalishaik** [comment]
https://plnkr.co/edit/UX4cV4ZAES8K4ObKl0X7?p=preview click on view then click any link in table actually i m not getting issue when i m doing on small data

**Comment by Johann-S** [comment]
default trigger option is `hover focus` so that's the normal behavior, if you want to change that behavior you'll find how here : https://getbootstrap.com/docs/4.0/components/tooltips/#options
