### ISSUE TITLE
<button> menu items inside dropdown have cursor: default

### ISSUE THREAD

**Issue by devoto13** [twbs/bootstrap#25350]
With beta.3 Bootstrap brought back `cursor: pointer` for buttons. However when having menu items using `<button>` tags inside dropdown they still use `cursor: default` (see this [example from docs](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-items)). I believe it is a bug and menu items should also have `cursor: pointer`.

**Comment by patrickhlauke** [comment]
FWIW i agree...PR incoming

**Comment by MaPePeR** [comment]
Same problem with Buttons in List Groups ([example from docs](https://getbootstrap.com/docs/4.0/components/list-group/#links-and-buttons))

**Comment by MartijnCuppens** [comment]
This was fixed by #27021
