### ISSUE TITLE
Not able to import bootstrap.scss file

### ISSUE THREAD

**Issue by Kalpesh300** [twbs/bootstrap#25364]
I am working on my angular 5 project. In my styles.scss file I am trying to import bootstrap.scss file. I installed bootstrap-4 beta using npm. But I am facing an error about mixins. In your bootstrap.scss you are trying to import mixins. But mixins is folder in my downloaded package. So, how to fix that?

**Comment by Kalpesh300** [comment]
@import "../../node_modules/bootstrap/scss/bootstrap";
My styles.scss has path src/app/styles/styles.scss .

**Comment by wolfy1339** [comment]
Please upgrade to v4 stable. It got released today.
This isn't a question regarding Bootstrap directly, this would be more suited somewhere else like StackOverflow

**Comment by Kalpesh300** [comment]
Okay.
Thank You.

**Comment by CunningFatalist** [comment]
I also agree, this is more of an StackOverflow question. However, I take you are using SASS. So the following should work just fine (in any of your files):

`@import "~bootstrap/scss/bootstrap";`
