### ISSUE TITLE
[v4-dev] dispose method of alert and button is omited

### ISSUE THREAD

**Issue by tangxuyang** [twbs/bootstrap#25366]
I am reading bs4 source code recently.
Today I find that the alert and button components forget to expose the dispose method. I think it is a bug. Below is the source code and I comment it.
```
    static _jQueryInterface(config) {
      return this.each(function () {
        let data = $(this).data(DATA_KEY)

        if (!data) {
          data = new Button(this)
          $(this).data(DATA_KEY, data)
        }

        if (config === 'toggle') {// here is the problem^_^
          data[config]()
        }
      })
    }
```

**Comment by Johann-S** [comment]
Good catch ! 👍 
A quick solution if you can't wait for a fix would be : `$('#yourButton').data().dispose()`

**Comment by tangxuyang** [comment]
Thanks for your reply. 
I just learn you guys' coding practice through reading the source code.

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
