### ISSUE TITLE
Carousel has no light theme (with dark arrows/indicators)

### ISSUE THREAD

**Issue by michaelkrieger** [twbs/bootstrap#25360]
Carousel has no theme where the control arrows aren't white. In this case, using a bg-light (or if someone used a bg-white) it should have black or dark grey left/right controls. Right now it's white-on-light or white-on-white and so the arrows are useless.

```html
<div id="carouselReviews" class="carousel slide bg-light " data-ride="carousel">
  <div class="carousel-inner bg-light">
    <div class="carousel-item active">
        <div class="d-block w-100 bg-light">CONTENT</div>
    </div>
    <div class="carousel-item">
        <div class="d-block w-100 bg-light">CONTENT</div>
    </div>
    <div class="carousel-item">
        <div class="d-block w-100 bg-light">CONTENT</div>
    </div>
  <a class="carousel-control-prev" href="#carouselReviewsControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselReviewsControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```

**Comment by LeeEvans1234** [comment]
The theme is about light and darkness of what one see in there self and
choose there path but more important is the knowledge to be shared for all
this is my goal your help is very important to do this and thank you

**Comment by anirudhdggl** [comment]
I may like to sort it out!

**Comment by gordon7up** [comment]
I have come across this problem also when using light images.

**Comment by Verringer** [comment]
You can get around this by changing the fill of the svg in the background image.

`css
.carousel-control-prev-icon {
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23**000**' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
}`
