### ISSUE TITLE
Bootstrap 4 documentation js error (Menu not opening) in mobile

### ISSUE THREAD

**Issue by isurendrasingh** [twbs/bootstrap#25377]
When opening bootstrap's documentation, the menu is not opening & also the autocomplete in search that is working in desktop is not working in mobile.
- Device- Smartphone
- Browser-Chrome [updated]
- OS- Android & Ios both

![screenshot_2018-01-20-07-16-11-203_com android chrome](https://user-images.githubusercontent.com/7621607/35178752-5bb5462c-fdb3-11e7-97ee-90c5e481e68f.png)

**Comment by mdo** [comment]
Both menu and search are working fine for me.

**Comment by isurendrasingh** [comment]
@mdo It's not working for chrome in android, but it's working in other browser.
