### ISSUE TITLE
Skip validation feedback on certain inputs

### ISSUE THREAD

**Issue by K1N5L4Y3R** [twbs/bootstrap#25374]
**Note 1**: I know that questions don't go in issues, but I haven't had any luck in Stackoverflow or Slack 😢
**Note 2**: This is a duplicate from https://stackoverflow.com/questions/48312772/skip-validation-feedback-on-certain-bootstrap-4-inputs so feel free to close this issue if you can help me there

-------

By following Bootstrap's docs on form validation, I can validate my forms, but I haven't found a way so that specific fields (e.g. a text input or a checkbox) don't show validation feedback while all of the others do.

What I mean is: how can I make that some specific fields either skip getting the `:valid` or `:invalid` pseudoclasses when the form is validated, or even if they do get the pseudoclasses applied to them, how can I skip them from being visually formatted as the other fields?

Maybe there is a class that acts as the opposite of `.was-validated` that can be applied to specific fields?

**Comment by ludovicofischer** [comment]
I have tried answering your question on StackOverflow https://stackoverflow.com/questions/48312772/skip-validation-feedback-on-certain-bootstrap-4-inputs/48724029#48724029

**Comment by blackst0ne** [comment]
Came here with the same question.

**Comment by Johann-S** [comment]
Sorry but that's not the right place to ask for help here, you'll find other place for that on this link : [See our readme for more details](https://github.com/twbs/bootstrap#community).
