### ISSUE TITLE
Recommend official removal of Ruby, 4.0.0 build Failed! but beta3 ok.

### ISSUE THREAD

**Issue by xiuno** [twbs/bootstrap#25372]
Ruby is a very small minority language, its package installation and related sites are very slow, I am a partial Server developer, but it is still difficult to deal with the Ruby, Gem, Bundler, Devkit a large pile of version dependencies and settings, each Bootstrap upgrade, I re git clone, then npm install, bunlder install will appear a lot of rather baffling problems.
I really don't think it's necessary to have a simple CSS problem, to bring in a lot of technology to come in and install a lot of packages.

Look the following picture, ruby related problems, google 1 day, no answer:
![image](https://user-images.githubusercontent.com/3362277/35153128-2eb52fe6-fd60-11e7-9a59-2107609933a7.png)

![image](https://user-images.githubusercontent.com/3362277/35152631-1a94bd1c-fd5e-11e7-99ca-9990cb911a01.png)

![image](https://user-images.githubusercontent.com/3362277/35151432-3e29e23e-fd59-11e7-9a4a-fb7db55f414d.png)

![image](https://user-images.githubusercontent.com/3362277/35151409-2b2cc87c-fd59-11e7-8b8a-6736981873ce.png)

**Comment by xiuno** [comment]
Thanks to the official public the 4.0.0 release version by fast speed, and I hope Bootstrap is getting better and better.

**Comment by bardiharborow** [comment]
You shouldn't need to use Ruby unless your are trying to compile the documentation.

**Comment by xiuno** [comment]
you are right, if only complie .scss, only node-sass enough.
Anyway, I finally compiles the past, What the shit ruby.
![image](https://user-images.githubusercontent.com/3362277/35155085-809b5d24-fd67-11e7-8699-570d563c33bc.png)
![image](https://user-images.githubusercontent.com/3362277/35155096-8f2e4e78-fd67-11e7-8919-7e90b3c7f762.png)

**Comment by mdo** [comment]
Yup, Ruby stuff (and more) is only for our docs building, and we’re working on improving that. Closing out since that’s being worked on and tracked in a few other issues (search for Hugo, build tools label, etc)
