### ISSUE TITLE
Bootstrap 4 tooltip freeze with jquery Smooth.state

### ISSUE THREAD

**Issue by zieru** [twbs/bootstrap#25389]
i'm using bootstrap 4 tooltip for anchor, and jquery smoothstate for ajax load, but if I click a link, the tooltip is hanging on the next page, here a screen capture:
![image](https://user-images.githubusercontent.com/1273033/35192668-c2cc9cd6-fec9-11e7-9cc4-00c5a616b89a.png)
is there any fix for this ?

here the demo link: http://0o.mrnazi.com:81/bs4/index.html
jquerysmoothstate link : https://github.com/miguel-perez/smoothState.js

using bootstrap3 no problem with this

**Comment by Johann-S** [comment]
It's your responsability to close the tooltip @zieru see : https://getbootstrap.com/docs/4.0/components/tooltips/#tooltiphide
