### ISSUE TITLE
v4 seems to forget the definition select > option {}

### ISSUE THREAD

**Issue by xiuno** [twbs/bootstrap#25380]
Not found the select > option, so in the dark background, the select > option background is default color white!

![image](https://user-images.githubusercontent.com/3362277/35184696-ee16c1aa-fe33-11e7-9852-65b42e179461.png)

![image](https://user-images.githubusercontent.com/3362277/35184691-e079ad6e-fe33-11e7-9898-72d844487efe.png)

**Comment by patrickhlauke** [comment]
you need to provide a reproducible reduced live test case...not just screenshots. thanks.

**Comment by mdo** [comment]
As far as I know, there's no consistent cross-browser styling of `<option>` elements.
