### ISSUE TITLE
About the principle of a design, background-color and foreground-color is important.

### ISSUE THREAD

**Issue by xiuno** [twbs/bootstrap#25383]
Most Compnent shoud caculate from the $background-color and $foreground-color.

```scss
$background-color: #111;
$foreground-color: #eee;

$grey-100: lighten($background-color, 90%); 
$grey-200: lighten($background-color, 80%);
$grey-200: lighten($background-color, 70%);
```

just like this, and component background should use use the value of calculating $background-color.
because：The atmosphere of the page is often expanded around the background color.

When I made the darkened theme, we can see that the default value of BS4 design principle is not reasonable：
![image](https://user-images.githubusercontent.com/3362277/35185564-ba384bc0-fe41-11e7-832a-49e5780787ad.png)

**Comment by MartijnCuppens** [comment]
Our [color utilities](https://getbootstrap.com/docs/4.3/utilities/colors/#color) can be used to fix this.
