### ISSUE TITLE
push-[size]-[col-number] and pull-[size]-[col-number] classes seem to be missing

### ISSUE THREAD

**Issue by mattcamp-work** [twbs/bootstrap#25397]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by mattcamp-work** [comment]
![pasted_image_1_22_18__6_55_am](https://user-images.githubusercontent.com/6834267/35219607-5e5f702a-ff41-11e7-9bd3-be6745526c54.png)

**Comment by AmrKafina** [comment]
Yup, column re-ordering doesn't seem to be working on the latest stable release, but works fine on 4.0.0-alpha.5.

**Comment by mattcamp-work** [comment]
Okay, that makes sense. Turns out, I was in the documentation for alpha 4, where it is mentioned. 
Thanks.
