### ISSUE TITLE
Make links inside .alert-* automatically inherit .alert-link style

### ISSUE THREAD

**Issue by tomsommer** [twbs/bootstrap#25396]
It seems foolish to have to add `.alert-link` to every link inside an `.alert`.

The `.alert-*` classes change the text color etc., so it makes sense to change the link colors automatically as well, so they fit the text.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by ysds** [comment]
Hmm we already have `.alert-xxx hr {...}` 😞 

https://github.com/twbs/bootstrap/blob/5068b437a45ffb9ab7b74620d9edec600b1a28aa/scss/mixins/_alert.scss#L1-L8

**Comment by tomsommer** [comment]
I think it's fair to do `.alert-xxx A`. For exampling having `$link-color: #000` and `$alert-danger-text: #fff` makes all links inside `.alert-danger` look horrible, and adding `.alert-link` to dynamically generated or imported links is a major pain.

**Comment by mdo** [comment]
Closing as a won't fix. In v5, we'll likely remove the inherited styles for `hr` elements and maintain the class-specific approach here.
