### ISSUE TITLE
v4.0.0 Scss Compilation Error: Invalid US-ASCII character “\xE2” (_hover mixin partial)

### ISSUE THREAD

**Issue by Syden10** [twbs/bootstrap#25391]
Good day, 

Was trying to update projects from beta 3 to v4.0.0 but kept receiving the following error when compiling some modules.
![screen shot 2018-01-21 at 4 42 36 pm](https://user-images.githubusercontent.com/12631452/35198622-2a35e228-fed0-11e7-8e2e-65a53ad98539.png)

After isolating the affected file _**mixins/_hover.scss**_ and going through it, seems to be the `-` character from _iOS-an._. in top comments (line 6). 
Replacing the `-` character with your own or setting `@charset: 'UTF-8';` at the top of the file does the trick.

![scssboot](https://user-images.githubusercontent.com/12631452/35198671-f08c079a-fed0-11e7-9625-c9aa490b22c3.jpg)

Thank you!

**Comment by vankooch** [comment]
I can confirm this on ubuntu 16.04 and sass 3.5.5. I've installed 4.0.0 with yarn no changes made.

```
Error: Invalid US-ASCII character "\xE2"
                on line 6 of wwwroot/node_modules/bootstrap/scss/mixins/_hover.scss
                from line 7 of wwwroot/node_modules/bootstrap/scss/_mixins.scss
                from line 12 of wwwroot/styles/bootstrap.scss
```

For ```scss/mixins/_hover.scss``` the error is the comments:

```scss
// stylelint-disable indentation

// Hover mixin and `$enable-hover-media-query` are deprecated.
//
// Origally added during our alphas and maintained during betas, this mixin was
// designed to prevent `:hover` stickiness on iOS ^ ^ an issue where hover styles   <-- THIS LINE
// would persist after initial touch.
//
// For backward compatibility, we've kept these mixins and updated them to
// always return their regular psuedo-classes instead of a shimmed media query.
//
// Issue: https://github.com/twbs/bootstrap/issues/25195
```

**Comment by rvanlaak** [comment]
I've filed a MR. Let's hope a hotfix will get deployed soon!

**Comment by XhmikosR** [comment]
I'm not aware of anything yet, but it's been a while since I talked with @mdo on Slack, so better wait for him to give you a definite answer.

**Comment by emregozel** [comment]
I'm having this problem and the solutions mentioned didn't solve the problem.

**Comment by fatcrobat** [comment]
Sass supports a `default-encoding` argument. You should add `--default-encoding=UTF-8` when compiling bootstrap from sass, that should fix the issue.
