### ISSUE TITLE
Should the .input-group be wrappable?

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#25409]
I just noticed that .input-group have flex-wrap:wrap style. This breaks some of my widgets built with .input-groups. So, is this really intentional? What's the reasoning behind it?

**Comment by ysds** [comment]
For validation feedback:
https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by mdo** [comment]
Yup, validation feedback. We should add a docs example and note around using a utility to override it though I think. Would that be acceptable @alecpl?

**Comment by alecpl** [comment]
I can fix this on my side as I don't need validation feedback in my case. So, no problem from my side. Thanks.

**Comment by mdo** [comment]
Okay, I'm going to leave open for now still and see about a docs update.
