### ISSUE TITLE
Checkbox-inline can not align gracefully

### ISSUE THREAD

**Issue by LauShawn** [twbs/bootstrap#25406]
I used the class 'checkbox-inline' to modify my checkboxlist in form,but the first one don't have 'margin-left:10px'.
It looks like this:
![image](https://user-images.githubusercontent.com/12406839/35264234-e3d6b2ca-0056-11e8-9b6e-db6d440210d5.png)
I found it because this:
![image](https://user-images.githubusercontent.com/12406839/35264363-7464587e-0057-11e8-8357-1fd5cec65272.png)
So I add the attribute of 'margin-left:10px' to every checkbox.
**Is there any other gracefull method to solve this?Can we support some choice to make the first one looks like the follows.**
![image](https://user-images.githubusercontent.com/12406839/35264566-38d3e17a-0058-11e8-9eab-b5869054c6f0.png)

**Comment by razh** [comment]
It looks like you want the `.checkbox` class.

https://getbootstrap.com/docs/3.3/css/#checkboxes-and-radios

`.checkbox-inline` is for checkboxes that appear on the same line.

**Comment by LauShawn** [comment]
@razh Thanks your addives,i tryed it just now.The align looks better now,but they are all bolded.
![image](https://user-images.githubusercontent.com/12406839/35266916-a003f7e8-005f-11e8-9bce-88532b488307.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Closing as a won't fix. If this is for v3, we're no longer maintaining that version, and general how-to questions should be asked on StackOverflow or in our Slack.

**Comment by LauShawn** [comment]
@mdo @Johann-S  OK,thanks!I used the V3 because my project is a old one.I will ask questions on StackOverflow at first next time.
