### ISSUE TITLE
Modal doc error, bootstrap 4

### ISSUE THREAD

**Issue by CostanzoPablo** [twbs/bootstrap#25402]
The documentation provided on the Bootstrap official website does not work. You have to make an adjustment. I attach details.
![modal](https://user-images.githubusercontent.com/1820045/35244283-6b0695e4-ff9e-11e7-9196-5bcd952c4fe1.png)

**Comment by patrickhlauke** [comment]
that's documentation for the alpha. which was fixed in the first beta. we're now a 4.0 stable, whose documentation is here http://getbootstrap.com/docs/4.0/getting-started/introduction/
