### ISSUE TITLE
Bootstrap v4.0.0 Heading Margin Inconsistency Between Images

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#25405]
I started a new project with Bootstrap v4.0.0 and noticed that when an h1 precedes an image that is 20px tall, there is a bottom margin of 11px, yet when it precedes an image that is 50px tall the bottom margin is just 7px. I then prepared a reduced test case (see link below) to find out what was going on to no avail and can only put it down to being a Bootstrap issue. I also noticed the same applies to the bottom margin of all h tags with the slight exception that the h4 bottom margin is always 1px less.

Reduced Test Case: https://codepen.io/chrisbowyer/pen/goqeNX
Operating System: Windows 7 Professional - Service Pack 1
Browser: Chrome 64.0.3282 (Official Build) beta (64-bit)

**Comment by mdo** [comment]
Headings in v4 have a `margin-bottom: .5rem`, meaning it should always net out to `8px`. Your Codepen example also has `margin-top` mentioned for headings, however, none of our headings have `margin-top`—we `0` that out.

I don't think this is a Bootstrap bug?

**Comment by guylepage3** [comment]
@mdo it would be very nice to have an option to allow users to "turn on" `margin-top` capabilities.

I can get such great vertical spacing control when I implement the following;
```
// Staggered margin-top
// For staggered margin-top values, use the following method

$h1-margin-top:               ($font-size-base * 2.5 * 2.75)!important;
$h2-margin-top:               ($font-size-base * 2 * 2.75)!important;
$h3-margin-top:               ($font-size-base * 1.75 * 2.75)!important;
$h4-margin-top:               ($font-size-base * 1.5 * 2.75)!important;
$h5-margin-top:               ($font-size-base * 1.25 * 2.75)!important;
$h6-margin-top:               ($font-size-base * 2.75)!important;

h1, .h1 {
  margin-top: $h1-margin-top;
}

h2, .h2 {
  margin-top: $h2-margin-top;
}

h3, .h3 {
  margin-top: $h3-margin-top;
}

h4, .h4 {
  margin-top: $h4-margin-top;
}

h5, .h5 {
  margin-top: $h5-margin-top;
}

h6, .h6 {
  margin-top: $h6-margin-top;
}
```
Results are amazing, even when Images are thrown in. I can simply "set it, and forget it" which is something we need. I get a super consistent vertical spacing with only a few lines.

But I would really like to remove those `!important` rule as it is super **[bad practice](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)**.

**Comment by guylepage3** [comment]
[The above comment](https://github.com/twbs/bootstrap/issues/25405#issuecomment-434733951) results in the following...

![screencapture-localhost-3000-home-2018-10-31-11_44_24](https://user-images.githubusercontent.com/1711854/47800290-62ad5580-dd02-11e8-8f3b-b585c5de2fda.png)

**Comment by mdo** [comment]
Adding those styles, as you've done here, would be the way to "turn on" that approach though. Doesn't make sense to bake that into the core project as an option to flip on or off.

**Comment by guylepage3** [comment]
@mdo I can see that but it was not exactly a quick process. If I am a Bootstrap beginner to intermediate, this would not be so obvious to execute. I also feel that a lot of folks that use Bootstrap may not have a design eye to understand the importance of spacing. Food for thought.
