### ISSUE TITLE
Would Bootstrap4 add the Responsive Font Size Feature? 

### ISSUE THREAD

**Issue by weilinzung** [twbs/bootstrap#25401]
Would Bootstrap add the Responsive Font Size Feature?  It would be great if add this as official feature, no need to add another 3rd library codes~

or how do you usually change font sizes with Bootstrap? maybe I don't know if there is already something like that~

I use this: https://www.smashingmagazine.com/2015/06/responsive-typography-with-sass-maps/

Thanks~

**Comment by myorangeca** [comment]
If you really want true font-sizes based on screen size, then better to formulate something like:

font-size: unquote("calc(16px + 5 * ((100vw - 320px) / 680))")

That article does not address all screen sizes, so you will need to keep updating the font-size as screen sizes gets larger.

**Comment by morrissey-ingenious** [comment]
There is already a section covering responsive typography in the docs.

[https://getbootstrap.com/docs/4.0/content/typography/#responsive-typography](https://getbootstrap.com/docs/4.0/content/typography/#responsive-typography)

**Comment by weilinzung** [comment]
@morrissey-ingenious  You are right, but I don't think that is simple enough, it is just the normal responsive breakpoints.  We have to add `@include media-breakpoint-up(xx)` each time, same as the normal `@media screen`. For fonts, should have a better solution.

**Comment by morrissey-ingenious** [comment]
Maybe something like below, note I have not tested this.

`@each $breakpoint, $key in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {

	html {
		font-size:  $font-size-base + (index(($grid-breakpoints), ($breakpoint $key)) * 0.25);
	}

  }
}`

**Comment by mdo** [comment]
This is being tracked in a PR: #23816.

**Comment by weilinzung** [comment]
hopefully would be quick~
