### ISSUE TITLE
[v4 docs] Provide a basic template HTML in docs

### ISSUE THREAD

**Issue by dsentker** [twbs/bootstrap#25408]
When i used bootstrap v3, it was always handy to copy-paste the [basic template html](https://getbootstrap.com/docs/3.3/getting-started/#template) structure when i started a new website. I am missing this template code and it would be great to add it.

**Comment by iqbalaqaba** [comment]
It have been added to the website since its 1st release.
Check it here:
https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template

**Comment by Johann-S** [comment]
closed thanks to @iqbalaqaba
