### ISSUE TITLE
Custom Selects Now Fill Entire Form Width

### ISSUE THREAD

**Issue by Rabadash8820** [twbs/bootstrap#25413]
In v4.0, custom selects now have "width: 100%", causing them to fill up an entire line of a form.  I assume that this is a bug, as it looks pretty weird.  A perfect test case is the Bootstrap documentation.  In the "Components > Forms" section, under "Inline forms", there is an example under "Custom form controls and selects are also supported" that includes a custom select.  Back in v4 alpha 6, this select was only as wide as its widest text; now in the v4 full release, the select takes up the entire width of the form, pushing all following controls onto the next line, as seen below:

- v4 Alpha 6: https://v4-alpha.getbootstrap.com/components/forms/#inline-forms
![image](https://user-images.githubusercontent.com/8388785/35299695-0fd4809e-0054-11e8-8b4a-e915452982a3.png)

- v4.0: https://getbootstrap.com/docs/4.0/components/forms/#inline-forms
![image](https://user-images.githubusercontent.com/8388785/35299715-2211bdd0-0054-11e8-8076-aafe46e74556.png)

I observed this behavior in Windows 10, on Chrome 63 (64-bit), Edge 41, and IE 11.

**Comment by Rabadash8820** [comment]
Okay, upon further investigation, it looks like this _is_ intended behavior, according to commit c468f89.  However, I would appreciate an explanation as to why this change was made, and possibly a workaround.

**Comment by wolfy1339** [comment]
You can set the width using some custom CSS, or utility classes https://getbootstrap.com/docs/4.0/utilities/sizing/

**Comment by Rabadash8820** [comment]
@wolfy1339  I don't think any of the current sizing utilities will adjust the width as before.  `mw-100` changes `max-width`, not `width`, and I'd prefer not to hard-code any other width classes because I want the width to just fit the widest text in the select, as before.

**Comment by mdo** [comment]
It's not intended behavior for the inline forms; we need to override the `width: 100%`. It is intended for default horizontal/stacked forms, where we're matching the behavior of our text inputs, selects, and file inputs as much as possible.

**Comment by Rabadash8820** [comment]
@mdo Wow, thanks for the fast fix!
