### ISSUE TITLE
New dashboard example is broken

### ISSUE THREAD

**Issue by miken32** [twbs/bootstrap#25415]
The top item in the sidebar is hidden for me on Firefox 58 Mac:

<img width="1380" alt="screenshot 2018-01-23 14 14 55" src="https://user-images.githubusercontent.com/1329102/35303746-e2760bec-0047-11e8-940b-2dc38dfd057d.png">

Looks like the navbar could use a `.pt-5` or something?

**Comment by mdo** [comment]
Could be some issues with the `position: sticky` implementation. I'll take a look when I'm able.

**Comment by PerseusTheGreat** [comment]
Hi.
I have changed `.sidebar `class as below:
```
.sidebar {
  /*position: fixed;*/
  /*top: 0;*/
  /*bottom: 0;*/
  /*left: 0;*/
  z-index: 100; /* Behind the navbar */
  padding: 0;
  box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
}
```
the problem has gone!

**Comment by asbachb** [comment]
When you switch to mobile view there's also no possibility to select a menu entry.

**Comment by vforvoid** [comment]
```
@-moz-document url-prefix() {
    .sidebar-sticky {
        padding-top: some amount of px here;
    }
}
```

Did the trick for me

**Comment by gamelaster** [comment]
Also it happens sometimes in Chrome

**Comment by cashlionjp** [comment]
@mdo Commenting out top fixed the issue for me.
`.sidebar {
  position: fixed;
  /* top: 0; */
  bottom: 0;
  left: 0;
  z-index: 100; /* Behind the navbar */
  padding: 0;
  box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
}
`
