### ISSUE TITLE
No .text- utility class for default body color

### ISSUE THREAD

**Issue by razh** [twbs/bootstrap#25412]
There is currently no way of resetting an `<a>` element (or any other element) to have the same color as `<body>` (`$gray-900`).

`.text-dark` exists, but it's a slightly lighter color (`$gray-800`).

https://getbootstrap.com/docs/4.0/utilities/colors/

Maybe something like `.text-default`?

### Prior art

- **Primer** (`.text-gray-dark` & `.link-gray-dark`): https://github.com/primer/primer/blob/master/modules/primer-utilities/lib/colors.scss
- **Tailwind** (`.text-black`): https://tailwindcss.com/docs/text-color

### Related issues

- https://github.com/twbs/bootstrap/pull/19847 (there's a recommendation of `.text-body` here)

**Comment by client9** [comment]
just bumped into this myself.   Adding `.text-default` or `.text-body` is one option.  The other is that this is a bug and `.text-dark` is wrong and it's suppose to be text default color.   I don't know enough about the goals of `.text-dark` to make a recommendation.

How can we get this into v4.1 ?  I'm happy to attempt a PR but I'm definitely not the best person to do this.

also may I recommend this gets added to the  `:root` as well

regards,

n

**Comment by client9** [comment]
see also #23696 has a recommendation of making text-light and text-dark transparent

**Comment by client9** [comment]
not exactly the same but  #25383 has a proposal for basing grays from background colors and not be absolute
