### ISSUE TITLE
Fix border-radius of form-control within input-group-append/input-group-prepend

### ISSUE THREAD

**Issue by hafezdivandari** [twbs/bootstrap#25411]
The `border-radius` is wrong when `form-control` is inside the `input-group-append` or `input-group-prepend`:

```html
<div class="input-group">
  <input type="text" class="form-control">
  <div class="input-group-append">
    <select class="form-control">
      <option>years ago</option>
      <option>months ago</option>
      <option>weeks ago</option>
      <option>days ago</option>
    </select>
  </div>
</div>
```

result:
![image](https://user-images.githubusercontent.com/7051289/35290899-e2f6e42c-0080-11e8-85ed-fc602bccc795.png)

I think this should be added to `_input-group.scss`:

```scss
.input-group > .input-group-prepend > .form-control,
.input-group > .input-group-append:not(:last-child) > .form-control {
    @include border-right-radius(0);
}

.input-group > .input-group-append > .form-control,
.input-group > .input-group-prepend:not(:first-child) > .form-control {
  @include border-left-radius(0);
}
```

result:
![image](https://user-images.githubusercontent.com/7051289/35291181-ca009124-0081-11e8-87c3-ab8f5b7f271f.png)

**Comment by alecpl** [comment]
I think you don't need an .input-group-append wrapper for .form-control elements.

**Comment by mdo** [comment]
> I think you don't need an .input-group-append wrapper for .form-control elements.

This is correct.

**Comment by hafezdivandari** [comment]
But without `.input-group-append` they get equal width.
`.input-group-append` makes appended `.form-control` have natural width of its content.

**Comment by mdo** [comment]
The statement stands; that's not what those classes are intended to do, and we won't explicitly support that behavior. You can, however, set `width: auto` (or soon, `.w-auto`) on elements to reset this. The required HTML and CSS for these component is super tricky, it does limit what we can do.

**Comment by hafezdivandari** [comment]
@mdo It doesn't work with `width: auto` but works with `flex: 0 0 auto; width:auto`. I think we should wait for `w-auto`.
