### ISSUE TITLE
Pre with horizontal scrollbar causes grid to stack

### ISSUE THREAD

**Issue by stephenbe** [twbs/bootstrap#25410]
If a pre has a horizontal scrollbar it will stack thus causing the grid to malfunction.

**Operating system**
Windows  7 (Microsoft Windows [version 6.1.7601])

**Browser and version**
Chrome 61.0.3163.100

**Reduced test cases**
https://codepen.io/stephenbe/pen/zpXWyy

In this codepen, you can see that the first examples stack while the other without a horizontal scrollbar it works just fine.

Thanks!

**Comment by Johann-S** [comment]
Please update your CodePen because we released our first stable version and you used an old one (beta 2)

**Comment by stephenbe** [comment]
@Johann-S I just updated the codepen, the same problem occurs

@chriscoyier codepen needs to update their default codepen quick-add bootstrap to 4.0.0
