### ISSUE TITLE
Carousel animation stucks in Firefox 58

### ISSUE THREAD

**Issue by neralex** [twbs/bootstrap#25418]
Since the update to Firefox 58 the animation stucks while sliding through the items. It affects the carousel in v3 and v4.

https://getbootstrap.com/docs/4.0/components/carousel/
https://getbootstrap.com/docs/3.3/javascript/#carousel

Windows 7, 10 with Firefox 58

**Comment by sagudev** [comment]
Yes it's not working for me too

**Comment by anantajitjg** [comment]
#24657 check my comment!

**Comment by neralex** [comment]
Thanks, mate!

**Comment by Johann-S** [comment]
Related to : #24657
