### ISSUE TITLE
Unable to use .is-valid or .is-invalid on nested .form-control(s)

### ISSUE THREAD

**Issue by leaski** [twbs/bootstrap#25425]
Using a simple layout as the below:
```
<div class="form-group">
  <input type="text" class="form-control">
  <span>.</span>
  <input type="text" class="form-control">
</div>
```
the .is-valid or .is-invalid class must currently be applied to every form-control element

I would suggest that the validation selector should include `.is-valid` or `.is-invalid` on a `form-group` and apply the styling to nested `.form-control`(s)

**Comment by leaski** [comment]
#25426 - PR

**Comment by mdo** [comment]
We're not styling parent elements in v4's form validation—this was discussed during our alphas and betas. We're basing everything around the `:valid` and `:invalid` states for inputs.
