### ISSUE TITLE
Add a var for the border radius of dropdown-menu

### ISSUE THREAD

**Issue by dietergeerts** [twbs/bootstrap#25420]
When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap

For the moment, there are several vars to set the border radius of multiple components:
```
$alert-border-radius:         $border-radius !default;
$progress-border-radius:        $border-radius !default;
$badge-pill-border-radius:    10rem !default;
// and so on....
```
so I see no reason to also have this for dropdown-menu.

I believe that in the first place, if you want to edit the styling to fit your needs, the first step should be to only edit the variables to get what you want. In this way, you can benefit from updates and don't have to keep your own styling up-to-date. That's why I think border radius vars should be there for every component.

**Comment by mdo** [comment]
We have `$dropdown-border-radius` already.

**Comment by dietergeerts** [comment]
Oh, it's not in our version but it seems to be adding not long ago. We'll upgrade. Thx
