### ISSUE TITLE
Outdated info on webpage

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#25423]
https://getbootstrap.com/docs/3.3 blue header says "The first Bootstrap 4 beta is here!"

**Comment by wolfy1339** [comment]
As a note, only the text needs to be changed. The link is still the same

**Comment by mdo** [comment]
Ah, yes, thanks for the heads up @alecpl. I'll take a look at that.

**Comment by jslewis90** [comment]
Unless I’m mistaken, it looks to be coming from the `docs` folder in the `gh-pages` branch.

**Comment by mdo** [comment]
Done!
