### ISSUE TITLE
card-body padding is only defined by $card-spacer-x

### ISSUE THREAD

**Issue by kristho91** [twbs/bootstrap#25427]
I noticed in Bootstrap 4.0.0 that .card-body in _card.scss is defined like this:

```
.card-body {
  ...
  padding: $card-spacer-x;
}
```

I suppose this should be defined like this:

```
.card-body {
  ...
  padding: $card-spacer-y $card-spacer-x;
}
```

**Comment by mdo** [comment]
The variables are misleading here. We should have a `$card-body-padding` variable instead of using these semi-generic spacers. For now, closing as a won't fix. We can adjust in v5.
