### ISSUE TITLE
Popover positioning regression

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#25428]
I built multi-level menu using Bootstrap 4 popovers. It worked like a harm with Popper 1.12.6 (Bootstrap 4-beta2), but since 1.12.7 menu positioning is broken. Tested with all versions including 1.13.0-next, and Bootstrap 4.0.

Looks like the second-level popover is placed incorrectly. It works if I use Bootstrap 4.0 with Popper 1.12.6.

https://codepen.io/anon/pen/mpYmVX

I've found out that removing my `.popover-body { overflow-x: hidden; }` fixes the issue, but I need the popover scrollable.

I created also https://github.com/FezVrasta/popper.js/issues/532, but I can't provide Popper-only test case.

**Comment by mdo** [comment]
We'll have to look into why we're including that overflow.

**Comment by alecpl** [comment]
Sorry if I wasn't clear. That overflow style is added by my custom css not Bootstrap. However, I think it's a valid use-case even if you didn't think about popovers containing buttons that open another popovers before.

**Comment by tompat** [comment]
I also have a popover placement issue from popper 1.12.7
Still broken with popper 1.12.9
1.12.6 works well

After few investigation, it seems that if the element triggering the popover has a container with an overflow set to scroll or hidden and the popover doesn't have enough space to position itself in the container with the right placement then the popover rollback to an unexpected position.

Bootstrap 4.0.0 + popper 1.12.9 + container with overflow set to scroll > unexpected position
https://codepen.io/anon/pen/RxXKgY

Bootstrap 4.0.0 + popper 1.12.6 + container without overflow > expected position
https://codepen.io/anon/pen/opKBQM

**Comment by alecpl** [comment]
Create a new Popper ticket with simpler test case https://github.com/FezVrasta/popper.js/issues/535

**Comment by alecpl** [comment]
A workaround is to set `boundary: 'window'` (or 'viewport') in popover config. Maybe this should become a default for popover if Popper.js does not fix the issue on their side. For more see https://github.com/FezVrasta/popper.js/issues/535

@Johann-S you think you can fix that, or you rather wait for @FezVrasta for an opinion?

**Comment by Yacie** [comment]
@ tompat you helped me bro.
With the sroll issue, working as expected

**Comment by Johann-S** [comment]
@alecpl we have boundary option in our Popover/Tooltip plugins see : https://getbootstrap.com/docs/4.0/components/popovers/#options

Is it still an issue ?

**Comment by alecpl** [comment]
As I said before it works with `boundary: 'window'`, but not with default settings.

**Comment by Johann-S** [comment]
@mdo this issue can be solve if folks use `boundary: 'window'` for their Popovers but not sure if it's enough to close this issue 🤔

**Comment by Johann-S** [comment]
I'll close this issue, because there is a solution using `boundary: window`
