### ISSUE TITLE
Pagination border is cut off on hover

### ISSUE THREAD

**Issue by sqal** [twbs/bootstrap#25424]
This bug is present in the lastest stable version (4.0)

Steps to reproduce
- Go to https://getbootstrap.com/docs/4.0/components/pagination/
- Using chrome devtools force `.page-link` to be in `hover` state
- Change border color to e..g red to see the bug

Looks like z-index for `:hover` was accidentally removed in this commit https://github.com/twbs/bootstrap/commit/797149ed267c59189fcf043c1a95484cfb9c7469

![image](https://image.prntscr.com/image/x4_ShD3TRGK25qYgyMenQg.png)

**Comment by mdo** [comment]
Yeah, I missed a `z-index` on the `:hover` state that is currently set for `:focus` and `:active`.
