### ISSUE TITLE
Bootstrap Tooltips display for effectively invisible elements when toggled manually

### ISSUE THREAD

**Issue by proteus-aholt** [twbs/bootstrap#25432]
- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
  Linux - Ubuntu 16.04
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
  Chrome 63
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

Tried looking to see if there was anything already opened about this, but could not find any current issues related.

When toggling tooltips using `$('.selector').tooltip()` with a selector that matches on both elements that are visible and elements that are effectively not displayed, the tooltip is still toggled on those elements that are not displayed.

I think this is a result of the code within `tooltip.js` that checks the css `display` property, when it should, instead, check if the entire element is actually visible.

```
show() {
      if ($(this.element).css('display') === 'none') {
        throw new Error('Please use show on visible elements')
      }

      const showEvent = $.Event(this.constructor.Event.SHOW)
```

should be

```
show() {
      if (!$(this.element).is(':visible')) {
        throw new Error('Please use show on visible elements')
      }

      const showEvent = $.Event(this.constructor.Event.SHOW)
```

or

```
show() {
      if (!$(this.element).is(':visible')) {
        console.warn('Please use show on visible elements');
        return;
      }

      const showEvent = $.Event(this.constructor.Event.SHOW)
```

I'm in favor of logging a console warning here, rather than throwing an error.  A jquery selector can _easily_ select multiple elements, and throwing here can cause a short-circuit of the enumeration, resulting in some odd tooltip behavior.

I have put together a CodePen as a demo: https://codepen.io/aholtventuretech/pen/WdBmJG

Unless there is a completely sane reason to show tooltips for elements that aren't displayed, in which case, feel free to disregard.

**Comment by Fouzyyyy** [comment]
What about silently ignoring invisible elements? and only show tooltip on visible elements?

**Comment by proteus-aholt** [comment]
That would be acceptable, as well, to me.   Was trying to keep the original functionality, to an extent, by letting the developer know that they were trying to show a tooltip for an invisible element

**Comment by Johann-S** [comment]
`:visible` isn't a good solution here, related to jQuery documentation see: 
>Elements with visibility: hidden or opacity: 0 are considered visible, since they still consume space in the layout.

https://api.jquery.com/visible-selector/

maybe a combination like that should be better : 
```js
if ($(this.element).is(':hidden') || $(this.element).css('display') === 'none') {

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
