### ISSUE TITLE
Easylist (Adblock & uBlock) blocking .alert-dismissible globally

### ISSUE THREAD

**Issue by karolyi** [twbs/bootstrap#25433]
Hey,

this is not really a Bootstrap issue per se, but important to know:
"Fanboy’s Annoyance List" in easylist (https://easylist.to/easylist/fanboy-annoyance.txt) seems to be blocking dismissible alerts (`.alert-dismissible`) **globally**.

This means, anyone who tries to use those, will have to make them unblock their site individually, or not use dismissible alerts.

Just letting you know, do what you want with the information.

**Comment by bardiharborow** [comment]
Hey @karolyi, the attached ruleset doesn't seem to contain the rule you mentioned. Am I looking in the wrong place? It doesn't not surprise me though that they've blocked this. `on-hold` as we can't fix this easily.

**Comment by karolyi** [comment]
Hey @bardiharborow,

if you look at the referenced easylist issue, they've just fixed it.
