### ISSUE TITLE
[Question] Will the no jquery get merged to master?

### ISSUE THREAD

**Issue by QuantumInformation** [twbs/bootstrap#25431]
Any updates on this? It's sad to see jquery still being a necessary part of this.

https://github.com/twbs/bootstrap/tree/v4-without-jquery

Will it go into master?

**Comment by mdo** [comment]
It's not the _top_ priority, and we don't have a hard deadline, but it will happen. Best way to see that it does is to help with contributions, issues, and testing.

**Comment by wolfy1339** [comment]
master is v3, v4-dev is well v4. It is planned for a future release of v4. Check the projects of this repository
