### ISSUE TITLE
Make collapse transition duration dynamic

### ISSUE THREAD

**Issue by artifex404** [twbs/bootstrap#25448]
Collapse.js transition duration is taken from a constant of value of 600.

However in some cases the transition needs to be altered with CSS, for example:

```
.collapsing {
    transition: none;
}
```

This prevents the collapsing trigger to work properly as it always waits for the 600ms timeout.

The collapse.js transition duration should take its value dynamically from css.

Demo: https://codepen.io/artifex404/pen/LewydR
(Note: auto updating is disabled, rerun codepen to see changes)

**Comment by MartijnCuppens** [comment]
We could use the same approach as #25218 for this

**Comment by artifex404** [comment]
Agree, or at least expose the transition timing variable, so it could be modified.
