### ISSUE TITLE
[Suggestion] Use canonical meta tags to indicate the latest version of documentation

### ISSUE THREAD

**Issue by YPCrumble** [twbs/bootstrap#25449]
Currently, when I google something like "bootstrap navbar", the alpha docs come first: https://cl.ly/463u3m151Y2t

If I'm not very careful to inspect the URL (or I scroll too quickly and don't see the banner at the top), it means that I end up getting confused as to why things like `navbar-toggleable-*` aren't working because they were changed after the alpha release. 

My suggestion is to use a `canonical` meta tag to point to the correct version of the documentation. An example would be how Django handles this (this shows the source of the Django 1.11 docs pointing Google to Django 2.0): https://cl.ly/2y1H0O1h3q3n

**Comment by XhmikosR** [comment]
I thought we already had this but apparently not. I'll add it soon, unless someone else makes a PR.

**Comment by mdo** [comment]
Forgot to mention, I added a bunch of canonical tags to the v3.3 hosted docs. Didn't add to the source code though, pushed it a couple weeks ago right to the `gh-pages` branch.

**Comment by coliff** [comment]
I think it'd be good to add canonical meta tags to the docs to indicate to search engines to index the HTTPS version of the docs (to take advantage of performance improvements of HTTP/2, improved security, service workers etc).

Currently the site indexed by Bing is showing the HTTP version of the docs which isn't ideal.

**Comment by XhmikosR** [comment]
This was added in #28093
