### ISSUE TITLE
list-group with dropdown and input-group with button -> button displayed over opened dropdown

### ISSUE THREAD

**Issue by simon11196** [twbs/bootstrap#25446]
![bootstrap-bug](https://user-images.githubusercontent.com/21359517/35430013-bf393a38-0276-11e8-8264-901174ee7550.png)

I have some code like the following example. when i open the dropdown, the button of the input-group in the next list-group-item ist showed over the dropdown, while the dropdown-menu is hovered. When the mouse is outside the dropdown-menu, all is as normal... 

    <div class="col-2">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown button
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-cubeBlue" type="button">Button</button>
                    </div>
                </div>
            </li>
        </ul>
    </div>

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by simon11196** [comment]
[https://jsbin.com/mawemow/edit?html,output](https://jsbin.com/mawemow/edit?html,output)

it is something with dropdowns and input-groups in a list-group...

 - latest version of bootstrap, i didn't recognize this effect in the earlier versions of bottstrap 4 (alpha)
 - every browser (Firefox, Chrome, IE, Edge, Opera...) on windows 10 (I think, OS and browser don't matter)

**Comment by leaski** [comment]
Having similar issues with the datepicker, the problem seems to stem from a mis-match of z-index on the `.list-group-item:hover` and the `input-group-append/input-group-prepend' z-index

Changing `list-group-item:hover` z-index to 3 fixes the issue - this may impact other elements though.

**Comment by rlamorea** [comment]
Saw this as well in a case with a drop-down inside a list item.  Displays ok until I hover over the list-item, and then the top vanishes under the fixed-top navbar.  

I also had to change the z-index of the menu itself since Popper wants to translate the menu to the top of the screen and therefore "under" the navbar.

**Comment by mdo** [comment]
Very strange. Confirmed that this is still an issue with https://jsbin.com/netajum/1/edit?html,output. Could be a Popper positioning issue vs a Bootstrap bug? Selecting any element or changing the viewport dimensions resolves the issue after the dropdown is toggled.

**Comment by ovpv** [comment]
@mdo @simon11196  its seems like a z-index issue

```
.input-group-append .btn, .input-group-prepend .btn {
    position: relative;
    z-index: 2; // disabling this property fixes the issue
}
```

i don't understand why the .btn element has been given the z-index of 2 🤔 ??

so If we set the z-index of button to "auto", this issue can be fixed.

Thoughts?
