### ISSUE TITLE
Accordion not closing when implemented with anchor element and href attribute

### ISSUE THREAD

**Issue by karkut** [twbs/bootstrap#25445]
I was unable to find an open or closed issue reporting this behavior.

In v4.0.0, accordions that use anchor elements and the href attribute to target the collapsible element do not function as expected. The closing of other expanded elements does not occur.

I have a project written with v4.0.0-beta in which I wrote an accordion using this method. It stopped working with the bootstrap.js from v4.0.0. The functionality returns if I substitute the bootstrap.js from v4.0.0-beta. I've been unable to find the change in bootstrap.js that is causing this.

A reduced test case of the issue is demonstrated on the w3schools page for Bootstrap 4 collapse. https://www.w3schools.com/bootstrap4/bootstrap_collapse.asp https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_collapsible_accordion&stacked=h
Under the accordion example, you will find that opening a div does not close other expanded divs. They have implemented the accordion using anchor elements with href attributes pointing at the collapsible elements.

I have been able to repeat this behavior on Chrome 63.0.3239.132 and Safari 11.0.1 running on macOS 10.12.6, as well as Safari iOS 11.2.2.

Apologies for any missing information, this is my first issue submission.

**Comment by Johann-S** [comment]
They are error in those examples see : https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

**Comment by karkut** [comment]
To be clear: the accordion is no longer meant to function with href attributes? Does accordion only work with buttons and data-target attributes?
I found an earlier request showing examples like the one I previously posted.[#22025](https://github.com/twbs/bootstrap/issues/22025) [#22138](https://github.com/twbs/bootstrap/pull/22138)

**Comment by RaghavKannan** [comment]
@karkut I am facing the same issue. In bootstrap 3 its working. I am using Bootstrap 4. My requirement is http://jsfiddle.net/nuNsp/1797/. How you fixed it?
