### ISSUE TITLE
Bring back the responsive utilities page

### ISSUE THREAD

**Issue by thecodingdude** [twbs/bootstrap#25455]
[This page](https://v4-alpha.getbootstrap.com/layout/responsive-utilities/) was extremely useful for visually seeing where break points were used in Bootstrap.

The closest thing I've found is [this](https://getbootstrap.com/docs/4.0/utilities/display/) or [this](https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints) which are not as useful for visually understanding how the breakpoints are applied.

**Comment by mdo** [comment]
No plans to add this myself. If folks have some ideas and time, I'd be open to PRs, but that page was also pretty annoying to setup :).
