### ISSUE TITLE
does bootstarp 4 supports in netbeans ide?

### ISSUE THREAD

**Issue by AmitSaha018** [twbs/bootstrap#25454]
i am facing problem with the bootstrap 4 in netbeans ide when i am pasting the offline version of bootstrap 4 in the netbeans ide of my project(under public_html folder) it is showing error but when i am pasting the bootstrap 3.3.7 in the netbeans ide of my project on that very same place it is not showing any error. Please help out to find remedy on using bootstrap4 in netbeans
![error3](https://user-images.githubusercontent.com/31251262/35475646-0802c8fe-03c8-11e8-8aaa-350429137c75.jpg)
![error2](https://user-images.githubusercontent.com/31251262/35475649-0ab3c472-03c8-11e8-99a8-fb832b76843f.jpg)

**Comment by wolfy1339** [comment]
Does it not have a more detailed error message than that?

**Comment by AmitSaha018** [comment]
No ,only showing that much

On 28-Jan-2018 1:33 AM, "wolfy1339" <notifications@github.com> wrote:

Does it not have a more detailed error message than that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/issues/25454#issuecomment-361011045>,
or mute
the thread

**Comment by Johann-S** [comment]
Not sure if it's related to Bootstrap here or Netbeans

**Comment by NYPD** [comment]
If the bootstrap 4 CSS is syntactically correct and the browser has no complaints, can't you just have the NetBeans IDE just ignore validation on that file?

**Comment by mdo** [comment]
Closing as this isn't a Bootstrap bug.

**Comment by Joelpc** [comment]
nadie sabe como solucionar este error
![image](https://user-images.githubusercontent.com/8442306/43971479-d9eae178-9c96-11e8-82b8-a9124dddb7ab.png)
