### ISSUE TITLE
Tables are not printing correctly

### ISSUE THREAD

**Issue by duksi1993** [twbs/bootstrap#25453]
Hello,
today I've added feature to print tables from my website.
Then I have noticed that tables with classes below are **not printing correctly**, although they are displayed correctly on screen.

- `<thead class="thead-dark">` - Header and font are both white so header is not readable

- `<table class="table table-dark">` - Like header, whole table is white, including the font.

- `<table class="table table-striped">` - There are no striped rows when printing. Class has no effect when printing. Print result is the same with and without it.

At first I suspected that something is wrong with my website (that my CSS is overriding Bootstrap CSS because it is linked after it), but then I tried to print tables from [official Bootstrap website](https://getbootstrap.com/docs/4.0/content/tables/) and got the same issue.

I'm using Bootstrap v4.0

Hope this will be resolved soon.
Thanks.

**Comment by mdo** [comment]
Background colors aren't always printed; there's usually a browser option for that. Unsure how much we should override that, which would screw things up for folks who want that background-color.

**Comment by ewaschen** [comment]
Any update for this?  I've tried writing my own `@media print` but it does not seem to have any effect.

**Comment by scemby** [comment]
@ewaschen @duksi1993  
Try to use `-webkit-print-color-adjust: exact;` like this:

`.elementWhichShouldBeRedAndBlue {
      background-color: red;
      color: blue;
      -webkit-print-color-adjust: exact;
}`

**Comment by onassar** [comment]
Did this ever get fixed? I'm using `v4.1.3` and rendering PDFs with puppeteer, but the coloring is still off. I've tried setting `-webkit-print-color-adjust: exact;` on the appropriate elements as well.

**Comment by bidipeppercrap** [comment]
> Did this ever get fixed? I'm using `v4.1.3` and rendering PDFs with puppeteer, but the coloring is still off. I've tried setting `-webkit-print-color-adjust: exact;` on the appropriate elements as well.

Same, not quite sure how it's work.

**Comment by cireficc** [comment]
@mdo "*Unsure how much we should override that, which would screw things up for folks who want that background-color*"

Well, [Bootstrap definitely overrides it](https://github.com/twbs/bootstrap/blob/e57a2f244ba8446fffe71847e6a58b18f7b2d541/scss/_print.scss#L110) and sets the background to white. Shouldn't it be `inherit` so that you don't override any colors that we've set in the table cell? Seems like Bootstrap is telling developers how things should print, instead of developers telling Bootstrap how it should print things.

**Comment by clintnetwork** [comment]
It's a real problem, need to be fixed!

**Comment by bound2** [comment]
Was this ever fixed? Seems to still be a problem. `-webkit-print-color-adjust: exact;` doesn't work for table elements. I can color any other div.

**Comment by megasnort** [comment]
Concerning the striped tables: I was able to get this working by adding the `print-color-adjust` property to the `td` en `th` elements. If applied to the `tr` element it does not work.

Thus, this **does not** work:

```
@media print {
    .tallies-list-table.table-striped > tbody > tr:nth-of-type(2n+1){
        background-color: red !important;
        print-color-adjust: exact !important;
    }
}
```

This **does** work:

```
@media print {
    .tallies-list-table.table-striped > tbody > tr:nth-of-type(2n+1) > td,
    .tallies-list-table.table-striped > tbody > tr:nth-of-type(2n+1) > th{
        background-color: red !important;
        print-color-adjust: exact !important;
    }
}
```

Note that this is for Bootstrap 3.
