### ISSUE TITLE
[iOS Safari] Input cursor placement in input tag used in the modal behavior

### ISSUE THREAD

**Issue by parthshah000** [twbs/bootstrap#25496]
https://getbootstrap.com/docs/4.0/components/modal/#varying-modal-content
Hit the link in iOS safari and try to fill the content message and see the cursor placement. It strangely goes wrong.
![download](https://user-images.githubusercontent.com/10954475/35481772-6000053e-0450-11e8-94d5-dc093e83a530.gif)

**Comment by razh** [comment]
This is an iOS Safari issue and will be fixed in iOS 11.3:

https://bugs.webkit.org/show_bug.cgi?id=176896

Here's is a short-term solution from StackOverflow:

https://stackoverflow.com/questions/46339063/ios-11-safari-bootstrap-modal-text-area-outside-of-cursor/46866149#46866149

**Comment by mdo** [comment]
Closing per previous comment.
