### ISSUE TITLE
Custom file input button border radius not correct

### ISSUE THREAD

**Issue by QballDevelop** [twbs/bootstrap#25499]
If you look good at below screenshot of the custom file input from [BS4 docs](https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input), you'll see a border radius bug in the second button from right.

![screen shot 2018-01-29 at 13 04 34](https://user-images.githubusercontent.com/2426724/35509935-729f735e-04f6-11e8-92aa-976bb176dc3f.png)

Now it's not that striking but if you change the button background color, it will be.

I believe that the fix is very simpel:
In the _input-group.scss file on line 49 and 51 it's styling the "::before" selector. I think it should be the "::after" selector.

I've done a search for the custom-file-label class and found another line at which the developers should take a look at when fixing this issue, it's in the mixin/_forms.scss on line 122. I don't know if that's not correct as well because I didn't give it much attention but it does look like it's not correct.

**Comment by ysds** [comment]
dup of #25356
