### ISSUE TITLE
Tooltip position issue

### ISSUE THREAD

**Issue by MartinTichovsky** [twbs/bootstrap#25506]
Hello, i found an issue with tooltip. In my case sometime have tooltip bad position and i found possible solution. I don't changed any other styles before. Please, see the video if is possible to fix this issue in future. Thanks

https://youtu.be/PHfL3uz8nb8

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.
