### ISSUE TITLE
Can't make text stronger with lead

### ISSUE THREAD

**Issue by imabot2** [twbs/bootstrap#25505]
The following line doesn't make the text stronger with Bootstrap 4:

`<p class="lead">An example of <strong>stronger text</strong> malfunctioning</p>`

The lead attribute prevent the strong markup to work properly.

**Comment by XhmikosR** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by imabot2** [comment]
https://jsfiddle.net/akopn3yv/

**Comment by XhmikosR** [comment]
It works fine on here. What browser and OS are you on?

**Comment by XhmikosR** [comment]
My guess is that your system font just doesn't cover all font weights thus it seems like strong isn't stronger.

**Comment by XhmikosR** [comment]
![screenshot](https://user-images.githubusercontent.com/349621/35556695-a2b127c6-05ab-11e8-87e7-d0b530397ed0.png)

**Comment by imabot2** [comment]
I'm using Chrome Version 64.0.3282.119 (Official Build) (64-bit) under Ubuntu 16.04.
I also tested with Firefox Quantum 58.0 (64-bit), same issue. 
What is really strange is that when I inspect the element and unchecked  the strong markup, the text becomes stronger :

![capture_2](https://user-images.githubusercontent.com/33400146/35559231-79f4de1e-05aa-11e8-9840-150296d2984c.png)
![capture_1](https://user-images.githubusercontent.com/33400146/35559233-7a175de0-05aa-11e8-9e11-4c6195ba6cb9.png)

**Comment by XhmikosR** [comment]
Please check with another browser or chrome version.

**Comment by imabot2** [comment]
It works fine on my smartphone.

**Comment by XhmikosR** [comment]
Not sure we can do anything, then...

**Comment by imabot2** [comment]
I understand, sorry for the trouble.
