### ISSUE TITLE
Meteor not finding @4.0.0

### ISSUE THREAD

**Issue by klynicol** [twbs/bootstrap#25504]
Trying to install the newest release on meteor. 

`meteor add twbs:bootstrap@4.0.0` is throwing an error: no such version

If I install without  a version is downloads 3.3.6, how do I get version 4?

**Comment by XhmikosR** [comment]
@mdo: who maintains the meteor package?

**Comment by mdo** [comment]
@XhmikosR No idea honestly. I'll have to look into it when I'm back next week.

**Comment by klynicol** [comment]
@mdo Thanks. I would much appreciate it.

**Comment by namkyux** [comment]
Please update this!  Thanks

**Comment by klynicol** [comment]
Looks like the name of the package may have changed to `bootstrap` instead of `twbs:bootstrap`... I was able to install version 4.0.0 using `meteor npm install --save bootstrap`.

**Comment by klynicol** [comment]
^^ or rather they are just going with npm packages instead.

**Comment by caseyjhol** [comment]
@mdo @klynicol It looks like nobody is currently maintaining the Meteor package. Autopublish is no longer supported, and it looks like Meteor support has been dropped now that Meteor supports npm (#21420, #20389). Any reason to not remove package.js and the other mentions to Meteor?

**Comment by XhmikosR** [comment]
@caseyjhol: no point in resurrecting old issues. Please make a new one.
