### ISSUE TITLE
Responsive tables - best practices confusion

### ISSUE THREAD

**Issue by Webotvorba** [twbs/bootstrap#25509]
In [migrating to v4](https://getbootstrap.com/docs/4.0/migration/#tables) it says:

```
Responsive tables no longer require a wrapping element. Instead, just put the .table-responsive right on the <table>.
```

In [docs](https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables) it says:

```
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

So which one is the best?

**Comment by midzer** [comment]
Since Beta 3: "Responsive tables are once again parent classes to avoid accessiblity issues with changing a <table>’s display."

So docs are right but migration page is outdated.

**Comment by XhmikosR** [comment]
PRs welcome. Feel free to CC me if you make a PR.
