### ISSUE TITLE
Button group - dropdown-toggle styling bug (v4.0.0)

### ISSUE THREAD

**Issue by alessandromercier** [twbs/bootstrap#25507]
Hello,

In combination with DataTables, the admin has discovered a little bug inside the Bootstrap CSS causing a rather weird looking styling bug:
https://i.imgur.com/TvtifKl.png

**You can see a live preview of this issue:**
http://live.datatables.net/wiyuhohu/2/edit

(Keep in mind though, that the theme used is used only to magnify the underlying issue that is present in the Bootstrap CSS. It is not as 'nuanced' using the default bootstrap css, but still very much there)

The problem is inside the following code:
`.btn-group>.btn-group:not(:last-child)>.btn,
.btn-group>.btn:not(:last-child):not(.dropdown-toggle) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}`

**Version:** 4.0.0 (Release)
**Browser:** All of popular ones (Chrome, FireFox, Android Chrome, Opera, Edge)

**Comment by ysds** [comment]
Not a bootstrap bug.

A `dropdown-menu` must be last child of the wrapper (`.dropdown`, `.btn-group` or another element that declares `position: relative`). This condition is the same as bootstrap v3.

**Comment by XhmikosR** [comment]
^^

**Comment by hackerESQ** [comment]
Am also having the same issue here:

<img width="442" alt="screenshot 2018-09-29 02 00 39" src="https://user-images.githubusercontent.com/16628119/46242217-8724b380-c38b-11e8-9db8-ffaf5a4b7ae8.png">

Looks like this is styled according to BS4 docs. Not sure what's happening? If I take out .dropdown-toggle, it seems to work? 
```

<div class="dt-buttons btn-group">
	<button class="btn buttons-copy buttons-html5 btn-outline-secondary" tabindex="0" aria-controls="time_entries_table" type="button" title="Copy to Clipboard">
		<span>
			<i class="fas fa-copy"></i>
		</span>
	</button>
	<button class="btn buttons-excel buttons-html5 btn-outline-secondary" tabindex="0" aria-controls="time_entries_table" type="button" title="Download to Excel">
		<span>
			<i class="fas fa-file-download"></i>
		</span>
	</button>
	<button class="btn buttons-print btn-outline-secondary" tabindex="0" aria-controls="time_entries_table" type="button" title="Print">
		<span>
			<i class="fas fa-print"></i>
		</span>
	</button>
	<button class="btn buttons-collection dropdown-toggle buttons-colvis btn-outline-secondary" tabindex="0" aria-controls="time_entries_table" type="button" title="Visible Columns" aria-haspopup="true">
		<span>
			<i class="fas fa-columns"></i>
		</span>
	</button>
	<button class="btn buttons-collection dropdown-toggle buttons-page-length btn-outline-secondary" tabindex="0" aria-controls="time_entries_table" type="button" title="Number of Rows" aria-haspopup="true">
		<span>
			<i class="fas fa-th-list"></i>
		</span>
	</button>
	<div class="dt-button-collection dropdown-menu" role="menu" style="display: block; top: 38px; left: 159px;">
		<a class="dt-button dropdown-item button-page-length active" tabindex="0" aria-controls="time_entries_table" href="#">
			<span>10 rows</span>
		</a>
		<a class="dt-button dropdown-item button-page-length" tabindex="0" aria-controls="time_entries_table" href="#">
			<span>25 rows</span>
		</a>
		<a class="dt-button dropdown-item button-page-length" tabindex="0" aria-controls="time_entries_table" href="#">
			<span>50 rows</span>
		</a>
		<a class="dt-button dropdown-item button-page-length" tabindex="0" aria-controls="time_entries_table" href="#">
			<span>Show all</span>
		</a>
	</div>
</div>
```

Looks like there may be an issue with the way .dropdown-toggle is handled here (_button-group.scss, Line 51):
```
  // Reset rounded corners
  > .btn:not(:last-child)**:not(.dropdown-toggle),**
  > .btn-group:not(:last-child) > .btn {
    @include border-right-radius(0);
  }
```
