### ISSUE TITLE
.table-bordered is adding borders to nested tables

### ISSUE THREAD

**Issue by roooodcastro** [twbs/bootstrap#25516]
Hello, I have a table which has the `.table-bordered` class assigned to it. Inside it, I have an input with a timepicker from a third-party library that uses a table to display its calendar.

The problem is that this inner table from the timepicker is now inside my bordered table, and it renders with borders too, due to the way borders are implemented in `bootstrap/_tables.scss` (using the selector `.table-bordered td`, instead of something like `.table-bordered > tbody > tr > td`).

Using the child selector rule with `.table-bordered > tbody > tr > td` fixes this issue, but it's needed in multiple places within `_tables.scss`.

Here's a [JSFiddle](https://jsfiddle.net/rooood/0wpo6n18/2/) showing the issue. Notice that the inner table also shows full borders, even if I didn't assign the `.table-bordered` class to it.

Is this an expected behavior? In my opinion I should need to specify the styling classes to the inner table in order to make it styled like the outer one. If this behavior is following some Bootstrap convention of inheriting all styles, is there any way, other than writing CSS myself, to un-style this nested table? I also expect other table style classes, such as `.table-hover` and `.table-striped` to have the same issue.

If this is indeed labelled as a bug, I already made a solution for me and will gladly open a PR with it.

**Comment by ysds** [comment]
Good point. Bootstrap v3 solved this problem with #7478, but it was removed in v4 (547f16b)

**Comment by mdo** [comment]
Correct, we removed the scoped styles to greatly reduce the complexity of our selectors. This is true across the bulk of our project now. Only way to address it is to update the CSS yourself I'm afraid.
