### ISSUE TITLE
What's wrong? My dropdown sample works in  ver. 4.0.0-alpha.6 but doesn't work in ver. 4.0.0

### ISSUE THREAD

**Issue by ChristopherRobinSuperStar** [twbs/bootstrap#25517]
[JSBIN My sample dropdown](https://jsbin.com/fayaqinuve/edit?html,css,js,output)

```
<!--this works well!--><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
<!--BUT this doesn't work !--> <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">!-->
```

**Comment by Moniet** [comment]
Did you include the bootstrap.js / bootstrap.min.js file in your main html?

**Comment by XhmikosR** [comment]
Please read the docs. You are probably missing implementing a markup change. See also the related migration docs part http://getbootstrap.com/docs/4.0/migration/#dropdowns.
