### ISSUE TITLE
Tooltip runs update after dispose, triggering null reference error, repeating on scroll events.

### ISSUE THREAD

**Issue by clemdavies** [twbs/bootstrap#25519]
Tooltip is running an update after being disposed of.
After error occurs, reliable but not consistent across all tooltips, Tooltip continues to try to update and producing the same error when scrolling up and down page.

Only tested in Aurelia typescript environment.
tooltip is a custom attribute
basically setup like so:

```js
attach(){
        $(this.element).tooltip(options);
    }
    detached(){
        $(this.element).tooltip("dispose");
    }
```

```
"TypeError: Cannot read property 'template' of null\n    at o.m.getTipElement (http://localhost:9000/scripts/vendor-bundle.js:50459:35772)\n    at o.m._cleanTipClass (http://localhost:9000/scripts/vendor-bundle.js:50459:38934)\n    at o.m._handlePopperPlacementChange (http://localhost:9000/scripts/vendor-bundle.js:50459:39075)\n    at Object.onUpdate (http://localhost:9000/scripts/vendor-bundle.js:50459:34291)\n    at Popper.update (http://localhost:9000/scripts/vendor-bundle.js:4678:18)\n    at Popper.update$$1 (http://localhost:9000/scripts/vendor-bundle.js:6159:21)\n    at http://localhost:9000/scripts/vendor-bundle.js:3838:7\n    at <anonymous>\nFrom previous event:\n    at http://localhost:9000/scripts/vendor-bundle.js:3836:30"
```

It is not happening on all tooltip instances, can have as many as 20 active at a time, but I can reliably replicate the error by navigating my site in a particular way.
I have checked to ensure I am not creating the bug in my code. No duplicate references, duplicate instances, timing, etc.

I have traced it to bootstrap's tooltip.js code:

```js
this.tip = this.tip || $(this.config.template)[0]
```

It looks like there is no check from 

```js
    _handlePopperPlacementChange(data)
```

being called, through to trying to access template property on this.config.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by tomaszbiedka** [comment]
I believe the error cause is that you call the "show" method more than once, without calling "hide" or "destroy".
There is new instance of Popper created in "show" method, which is destroyed only in "hide" and "destroy" methods.

**Comment by Inva0** [comment]
Can reproduce on CodePen, I am creating and destroying tooltips only once.
Seems to affect only html tooltips.
[https://codepen.io/anon/pen/VXMVXK](https://codepen.io/anon/pen/VXMVXK)

**Comment by Johann-S** [comment]
Reproduced thanks @Inva0 👍

**Comment by rodolfosouza** [comment]
I found a solution, before $ele.tooltip("dispose")  if you inicialize $ele.tooltip().tooltip("dispose") works fine ....strange

**Comment by Invulner** [comment]
Any workaround here? Solution of @rodolfosouza unfortunately doesn't work for me.

**Comment by Johann-S** [comment]
https://github.com/twbs/bootstrap/pull/26418 will fix that
