### ISSUE TITLE
Toggle collapse doesn't work inside a toggle buttons

### ISSUE THREAD

**Issue by welcoMattic** [twbs/bootstrap#25512]
Hi, I'm trying to get an `input[data-toggle="collapse"]` working inside a `.btn-group[data-toggle="buttons"]`.

Here is an example https://www.bootply.com/FmRE67XWHN

The problem is that the collapse doesn't work.

I found this issue on Firefox 58.0 on macOS 10.12.6, with Bootstrap 3.3.7

Thanks

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
