### ISSUE TITLE
gray conflicts with cssnext's implementation

### ISSUE THREAD

**Issue by dkrutsko** [twbs/bootstrap#25525]
Hey there, apologies if this was brought up in the past but I noticed that the new [`gray`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_functions.scss#L75-L77) function introduced in one of the beta's is now conflicting with the cssnext [`gray`](http://cssnext.io/features/#gray-function) declaration.

**Comment by wolfy1339** [comment]
I think this has been brought to their attention already

**Comment by mdo** [comment]
At this point, I don't think we'd do anything about the naming of that function. It previously was `grayscale()` and we changed it because it conflicted with Sass's function. We can't outright remove it, but we could provide an alternative and deprecate the current one if it makes sense to do so.

**Comment by dkrutsko** [comment]
Would it be possible to place them behind variables (or separate filenames)? I noticed that things like `$brand-primary` became `theme-color` but then `$primary` came back. So changing the core library to use `$primary` and putting these extra functions such as `gray` behind a separate variable/filename might work.

**Comment by mdo** [comment]
Closing out given I let this set for so long.
