### ISSUE TITLE
New feature suggested for Dropdown: able to disable Popper's preventOverflow

### ISSUE THREAD

**Issue by mapher87** [twbs/bootstrap#25529]
Get an issue when using [Menu forms](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-forms) with a large form which is supposed to fix itself below the button.
The PreventOverflow feature is good, but we'd disable it in a lot of cases which is impossible when using Dropdown.

Thanks and Best Wishes.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mapher87** [comment]
https://codepen.io/anon/pen/QQjKEJ
Click the button several times or scroll up and down, you will see the form reset its position by the preventOverflow feature.

**Comment by Johann-S** [comment]
A quick fix would be to add this line on your application : 
```js
Popper.Defaults.modifiers.preventOverflow = { enabled: false };
```

See the result here (with our first stable v4) : https://codepen.io/Johann-S/pen/vdNymv?editors=1010

**Comment by mapher87** [comment]
As there an option "data-boundary" to manage the behavior of the preventOverflow, would you like to disable one Dropdown's preventOverflow feature by given false or null? 

For example:
```html
<button type="button" data-boundary="false" ...>
  button
</button>
```

**Comment by Johann-S** [comment]
They are a PR to disable Popper.js for dropdown : https://github.com/twbs/bootstrap/pull/24092

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
