### ISSUE TITLE
Obsolete scope attribute in table docs examples.

### ISSUE THREAD

**Issue by bouzlibop** [twbs/bootstrap#25528]
As of now in [docs section regarding tables](https://getbootstrap.com/docs/4.0/content/tables/) there is such an example: 

```html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      ...
```
[MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td) `scope` attribute is marked as obsolete in HTML5.

Shouldn't it be removed from example in the docs?

**Comment by patrickhlauke** [comment]
`scope` is obsoleted on `<td>` cells only. NOT on `<th>` cells. see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th / https://www.w3.org/TR/html53/obsolete.html#non-conforming-features
