### ISSUE TITLE
Datepicker isn't opened after clicking on scroll bar if datepicker was opened. 

### ISSUE THREAD

**Issue by LiberVitalik** [twbs/bootstrap#25523]
Steps to reproduce:
- Click on the "Datepicker"
- Click on the scroll bar
- Click on the "Datepicker"

Actual result:
- Calendar isn't opened after clicking on scroll bar

Expected result:
- Calendar should be opened after changing focus

Environment:
- Windows 10
- Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by patrickhlauke** [comment]
there's no "datepicker" in bootstrap. also, you don't seem to have provided an actual URL showing the problem.

**Comment by LiberVitalik** [comment]
I'm understood, thank you.
