### ISSUE TITLE
[Docs] Search not including all results

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#25533]
When searching the docs for "d-inline", only one result is provided: https://getbootstrap.com/docs/4.0/utilities/flex/#enable-flex-behaviors

However, the result I was looking for that should be provided as well is: https://getbootstrap.com/docs/4.0/utilities/display/#notation
or
https://getbootstrap.com/docs/4.0/utilities/display/#examples

Tested on Safari and Chrome on macOS.

**Comment by mdo** [comment]
Yeah we'll need to reindex. @maxiloc can you help by chance?

**Comment by maxiloc** [comment]
I updated the config and reindex, should be good now

**Comment by XhmikosR** [comment]
Hmm, I still don't see the new results. Do we need to do something on our side?

**Comment by maxiloc** [comment]
The result is there, I also double check in the index:

![image](https://user-images.githubusercontent.com/1689007/35724345-a960a73c-07fd-11e8-8c0b-53049985af62.png)

A refresh of the page should be enough on your side

**Comment by XhmikosR** [comment]
Thanks!
