### ISSUE TITLE
Add pointer cursor on hover of form labels

### ISSUE THREAD

**Issue by leesmith** [twbs/bootstrap#25531]
I'm curious as to what the opinions are to add a pointer cursor to form labels on hover. This may not be as useful for text fields or select boxes but for check boxes and radio buttons, I think these are very useful in offering better usability to the tiny check box and radio button controls.

This is the only issue I could find on the subject (very old):

https://github.com/twbs/bootstrap/issues/5742

Barebones example:
https://codepen.io/smitjel/pen/aEOYgQ

Thanks!

**Comment by mdo** [comment]
We won't be adding `cursor: pointer` to these since a label has no idea if the field is enabled or disabled. For the latter, we'd be essentially encouraging folks to interact with something that's not interactive at all.

**Comment by patrickhlauke** [comment]
agree, it becomes a slippery slope. i was also pondering what would happen if authors just randomly use `<label>` elements that don't point to an actual form control...they'd still get a hand cursor, without it actually doing anything.

**Comment by aboveyunhai** [comment]
I stumbled by the same issue and wonder any historical reasons/contexts that `<label>` was not using `hover: cursor-point` by default.
End up here and feel a bit of disappoint that this type of change was largely denied 10ys ago.
As of today a lot of `<label>` were random abused as `<span> | <div>` that points to nothing.
Also the interactive area of `<label>` is always large than the text content itself: The huge empty space after the text content if the label occupy the full width. It always leads to misclick without a cursor indictor,
