### ISSUE TITLE
Menu behaviour in bootstrap3 template without bootswrapper plugin

### ISSUE THREAD

**Issue by ggieling** [twbs/bootstrap#25545]
Giuseppe,

First of all, thank you for sharing this template.  I like the presence of a menu bar option, the detailed configuration options and the use of hooks that can be defined using standard wiki pages.

I am testing a dokuwiki environment with bootstrap3 plugin as base template and ran into an issue when I create a menu.  The menu is defined as a standard unordered list and all but one items have second level subitems.  A part of the menulist is included below.
```
  * Members section
    * [[members:alv_presentaties|Presentations AGM]]
    * [[members:notulen_alv|Minutes / Reports]]
    * [[members:seminar_presentaties|Presentations seminar]]
    * [[members:notulen_sacepo|Minutes SACEPO - PDI]]
    * [[members:ledenlijst|WON representatives]]
  * [[public:en:vacatures|Vacancies]]
  * Links
    * [[public:en:ug|User groups]]
    * [[public:en:patinf|Public sources]]
    * [[http://sites.google.com/site/wonwiki/|WSI information]]
    * [[http://www.won-nl.org/ipc-nl/ipc.htm|IPC-NL]]
```
The issue is with the entry `  * [[public:en:vacatures|Vacancies]]`.
If the bootswrapper plugin is installed together with the bootstrap3 template everything functions as expected, but without this bootswrapper plugin the 'vacancies' entry is displayed below the line of the other entries.

The code created for this menu section is displayed below:
```
<li class="level1 node dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Members section <span class="caret"></span></a>
--
  | <ul class="dropdown-menu" role="menu">
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/alv_presentaties" class="wikilink1" title="members:alv_presentaties">Presentations AGM</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/notulen_alv" class="wikilink2" title="members:notulen_alv" rel="nofollow">Minutes / Reports</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/seminar_presentaties" class="wikilink2" title="members:seminar_presentaties" rel="nofollow">Presentations seminar</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/notulen_sacepo" class="wikilink2" title="members:notulen_sacepo" rel="nofollow">Minutes SACEPO - PDI</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/ledenlijst" class="wikilink2" title="members:ledenlijst" rel="nofollow">WON representatives</a>
  | </li>
  | </ul>
  | </li>
  | <li class="level1 dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><a href="/dokuwiki/doku.php/public/en/vacatures" class="wikilink1" title="public:en:vacatures">Vacancies</a> <span class="caret"></span></a>
  | </li>
  | <li class="level1 node dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Links <span class="caret"></span></a>
  | <ul class="dropdown-menu" role="menu">
  | <li class="level2"> <a href="/dokuwiki/doku.php/public/en/ug" class="wikilink1" title="public:en:ug">User groups</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/public/en/patinf" class="wikilink2" title="public:en:patinf" rel="nofollow">Public sources</a>
  | </li>
  | <li class="level2"> <a href="http://sites.google.com/site/wonwiki/" class="" target="ext" title="http://sites.google.com/site/wonwiki/" rel="nofollow noopener">WSI information</a>
  | </li>
  | <li class="level2"> <a href="http://www.won-nl.org/ipc-nl/ipc.htm" class="" target="ext" title="http://www.won-nl.org/ipc-nl/ipc.htm" rel="nofollow noopener">IPC-NL</a>
  | </li>
  | </ul>
  | </li>
```
The critical section is the section for the "vacancies" link which, without the bootswrapper plugin, is generated as:
```
<li class="level1 dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><a href="/dokuwiki/doku.php/public/en/vacatures" class="wikilink1" title="public:en:vacatures">Vacancies</a> <span class="caret"></span></a>
</li>
```
and with the bootswrapper plugin as:
```
<li class="level1"> <a href="/dokuwiki/doku.php/public/en/vacatures" class="wikilink1" title="public:en:vacatures">Vacancies</a>
</li>
```
Since the "a" element inside a "li" element of a navbar class is defined as a block element with padding, the code generated without the bootswrapper plugin produces two "a" blocks inside the "li" element.

The issue apparently is that without the bootswrapper plugin an entry without subitems generates the dropdown "a" element the actual link "a" element and the "span", whereas the same entry with bootswrapper plugin generates only the actual link "a" element.

Also the classes for the parent "li" elements differ.  Without the bootswrapper plugin the "li" element has the classes "level1 node dropdown" regardless of the presence of submenu items.  With the bootswrapper plugin an item without subitems generates an "li" element with only the "level1" class.

It seems as if a critical piece of code is present in the bootswrapper plugin, but missing in the bootstrap3 template.

Since I do not yet know if I am actually going to use any of the bootswrapper functions, I would like to see the menu in the bootstrap plugin behave as expected with and without the bootswrapper plugin to allow me to choose to leave out the bootswrapper plugin if I do not need it.

To prevent possible incompatibilites with other plugins, I prefer to install only plugins I really use.

Tested in:
Chromium Version 64.0.3282.119 (Developer Build) (64-bit) (Arch Linux) and
Firefox 58.0 (64-bit) (Arch Linux)

**Comment by mdo** [comment]
Bootswrapper plugin isn't developer or maintained by us. You'll need to find the developer of it elsewhere.
