### ISSUE TITLE
Add `backface-visibility: hidden` to elements with box-shadow on focus

### ISSUE THREAD

**Issue by atomiks** [twbs/bootstrap#25549]
- macOS 10.13.3 Chrome 64

There is some kind of Blink bug where junk pixels/remnants of the box-shadow are left behind when it's transitioned out, and looks really bad. `backface-visibility: hidden` fixes it.

<img src="https://i.gyazo.com/f5694de28ed73aa8a232d39a051d95b2.png">

https://codepen.io/anon/pen/qxZMBG

It's not reproducible 100% of the time and is sort of random, but when it does happen it ruins the UI leaving random pixels when the element is defocused.

**Comment by mdo** [comment]
Until we can track down the actual cause, it seems excessive to apply this property to every instance of a shadow for a bug that occasionally happens. If it can be narrowed down more, it should be reported to Chrome, too.

**Comment by atomiks** [comment]
From what I can see, Chrome 65 has fixed this, so it's all good 👍
