### ISSUE TITLE
Badges misaligned inside a table row

### ISSUE THREAD

**Issue by Zhigalin** [twbs/bootstrap#25543]
When inside a table row the badge lacks proper vertical alignment thus being positioned slightly under the table row text.
Tested under linux Chrome 64 and Firefox 56.
Example: https://codepen.io/anon/pen/ZrQgPg
Something like 
```
tr .badge {
  vertical-align: text-bottom;
}
```
would solve the problem but I think this should be a default...

**Comment by mdo** [comment]
This isn't something we'll universally add to Bootstrap—it all depends on how you structure your HTML. We'll pass, thanks though.
