### ISSUE TITLE
Example docs usage of `form-check` requires `form-group`

### ISSUE THREAD

**Issue by peterblazejewicz** [twbs/bootstrap#25546]
Hello,

I'm under impression the sample form markup in the docs needs a correction here:

http://getbootstrap.com/docs/4.0/components/forms/

```html
<div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
</div>
```

The problem with sample snippet is that AFAIK the `form-check` improves rendering of custom checkbox control but not a layout within a form. So I think it should be supported by a `form-group` to both layout a group and customer control:

```html
<div class="from-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
</div>
```

Sample in CodePen:
https://codepen.io/blazejewicz/pen/YeqEPR

Thanks!

Before opening an issue:

- [x] [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- [x] Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs

When suggesting a feature, include:

- [x] As much detail as possible for what we should add and why it's important to Bootstrap
- [x] Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by supergibbs** [comment]
Either this or `.form-check` should include `margin-bottom: $form-group-margin-bottom;`
