### ISSUE TITLE
Responsive sidebar in Dashboard example

### ISSUE THREAD

**Issue by gamelaster** [twbs/bootstrap#25552]
At the moment, the sidebar is not visible on phone devices (so making the example absolutely useless on phones). It would be nice to make sidebar responsive

**Comment by mojimi** [comment]
Would be great if they could implement responsive sidebar collapsible navbar, a feature I would really like to see in bootstrap

**Comment by johnny-bit** [comment]
I wonder if responsive sidebar can be sliced out from https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 as an example.

**Comment by mariusa** [comment]
It would be great to have a sidebar component in Bootstrap.

Example:
https://coreui.io/docs/components/sidebar/
https://coreui.io/demo/3.0.0/#main.html

Note how it can be collapsed to a small sidebard (icons only view) and auto-hides on small screens, having a menu button to show it.
