### ISSUE TITLE
Convertor from BT3 to BT4

### ISSUE THREAD

**Issue by landsman** [twbs/bootstrap#25554]
Hello,

i am thinking about create some convertor from BT3 to BT4 for my frontend projects.
This convertor could search and replace strings in all project in files of type:`.scss`, `.css`, `.html.twig.` ...

Important is for me some changelog in readable format (js object / yaml / ...).
Here is my quick draft: https://gist.github.com/landsman/526d88db01cf5ec50fad257fe2d44574

Final convertor can be wrapped in `npm` module.
What you think about? Manually refactoring is annoying 😞

Something like 😍 [Rector](https://github.com/rectorphp/rector) could be pretty to future!

**Comment by mdo** [comment]
Sounds neat! Unfortunately I'm going to have to close your issue though since it isn't a feature request or bug report. Feel free to share and gather feedback in our Slack!

**Comment by landsman** [comment]
@mdo OK, thanks. Is there some change log as I said? Do you have some ideas about it?

**Comment by wolfy1339** [comment]
check the docs, there's a migration section that starts from the Alphas and goes all the way to the stable release, change for change
