### ISSUE TITLE
Why is the `.figure` class set to `display: inline-block`?

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#25567]
The `figure` element is defined as a `display: block`, but then the `.figure` class is set to `inline-block`:

    .figure {
        display: inline-block;
    }

It's not a huge deal; I can simply leave off the `.figure` class, but it seems like a curious setting.

**Comment by mdo** [comment]
There's a comment on this in our source code—`block` is used as part of Reboot, specifically for helping IE10 with HTML5 elements. `inline-block` is for aligning captions with `.figure`. One is part of a general reset, the other a Bootstrap component.

https://github.com/twbs/bootstrap/blob/9057d8da164bed683f49d30c6414753dad41de3e/scss/_images.scss#L25-L42
