### ISSUE TITLE
Custom checkboxes do not work without label

### ISSUE THREAD

**Issue by SchweizerSchoggi** [twbs/bootstrap#25566]
Custom checkboxes/radios appear to be broken in cases where the label is missing. This should not happen. It should be possible to display custom checkboxes without label.

https://www.bootply.com/SSKHrAAGWD

**Comment by mdo** [comment]
It's not possible given how the component is built—the custom check is built from the `<label>` element via `::before` and `::after`. You can have an empty label if you must, but the `<label>` element must be present.
