### ISSUE TITLE
Class modal-dialog-centered does not work on IE 11

### ISSUE THREAD

**Issue by Webdude737** [twbs/bootstrap#25569]
This might an issue with Flexbox and IE 11.  In any case, opening up the modal does not vertically center it.

Easy to Reproduce:  In IE11, go to https://getbootstrap.com/docs/4.0/components/modal/  and click on the "Launch demo modal" button in the section "Vertically centered".

IF there is a workaround class or code, please advise.  Thanks.

**Comment by peterhpchen** [comment]
Thank @larrybahr. It works for me.

**Comment by ray73864** [comment]
Having the same issue with the modal-dialog-centred, as a work-around I am setting the "top" css rule on the modal.

At first I thought it was just what I was doing, so I loaded the example in the documentation on IE11 and it too had the same problem.
