### ISSUE TITLE
(Bootstrap 4) What happaned the caption class? 

### ISSUE THREAD

**Issue by muhammetbalci** [twbs/bootstrap#25560]
Caption class has vanished with Bootstrap 4.
There is this features in Bootstrap 3: `.caption{padding:9px;color:#333}`

While I trying to adapt v4, I couldn't find any migration or just the same class.

**Comment by andresgalante** [comment]
Hi, where are you using the caption?

There are utility classes for color and for size on bs4

**Comment by muhammetbalci** [comment]
Hello,
I'm using for image description. For instance: https://codepen.io/anon/pen/gvwraR
Without caption class it seems unpleasant. Also figcaption is not in the same function

**Comment by andresgalante** [comment]
Tyr this: 
http://getbootstrap.com/docs/4.0/content/figures/

Does it help?

**Comment by muhammetbalci** [comment]
No unfortunately it is not give the same result. I need padding 9px and color #333, as before caption class in BS 3.3.5. I wondered why it is deleted?

**Comment by mdo** [comment]
We basically rewrote the entire codebase several times over in the move from v3 to v4. There are differences and not everything was carried over. Use our utilities instead.

https://getbootstrap.com/docs/4.0/utilities/colors/
https://getbootstrap.com/docs/4.0/utilities/spacing/

**Comment by muhammetbalci** [comment]
py-2 class is perfect. Thank you.
