### ISSUE TITLE
Responsive sizing options

### ISSUE THREAD

**Issue by AndiLeni** [twbs/bootstrap#25568]
Hello,

I wanted to make a suggestion for improvement. It concerns the sizes options w-* and h-*.
Wouldn't it make sense to provide responsive classes? Like w-sm-50, h-lg-75, etc.?

Regards
Andi

**Comment by bpierson** [comment]
That may get confusing when combined with the responsive grid. Could you achieve the same result using the responsive grid and placing the content with a `w-50` in a grid div?

**Comment by mdo** [comment]
There are a handful of issues about this that have been closed. We're in no rush to add more utilities at this point and want to make sure, as you've mentioned, that we're not simply duplicating core parts of our grid system.
