### ISSUE TITLE
Form section on reboot page looks broken

### ISSUE THREAD

**Issue by xen** [twbs/bootstrap#25571]
On Reboot page, Forms section looks missing some of the CSSs.

Steps:
- Open page https://getbootstrap.com/docs/4.0/content/reboot/#forms (current version 4.0, available on screenshot)
- Checkout Forms section

**Result** as seen on screenshot:

![screenshot from 2018-02-07 01-22-22](https://user-images.githubusercontent.com/31260/35889775-b81085e4-0ba5-11e8-8d95-6b618aeae09a.png)

**Expected** something similar to [Components / Forms](https://getbootstrap.com/docs/4.0/components/forms/#overview)

Other:
- Operating system and version: macOS 10.13 High Sierra, Ubuntu 17.10
- Browser and version: current version of the Chrome and Firefox

Why it is important:
- I think this should be fixed because this is the part of the documentation that will visit most people who updating their projects to the latest version of the Bootstrap.

**Comment by patrickhlauke** [comment]
Reboot simply normalizes components across browsers - as many browsers have their own idiosyncratic values for things like spacing/margin, borders, etc.

It does not set any of the bootstrap-specific styles themselves. These only kick in once authors add the relevant classes.
