### ISSUE TITLE
Errors in W3C Unicorn Validator

### ISSUE THREAD

**Issue by markw707** [twbs/bootstrap#25577]
[](https://validator.w3.org/unicorn/check?ucn_uri=www.currnews.com%2F&ucn_task=conformance#)

I ran http://www.currnews.com/ in the W3C Unicorn code validator and received these errors:

URI: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css | a
-- | --
5 |   | .form-control-feedback | Property “pointer-events” doesn't exist :  		none | a
5 |   | a.btn.disabled, fieldset[disabled] a.btn | Property “pointer-events” doesn't exist :  		none | a
5 |   | [data-toggle="buttons"] > .btn  input[type="checkbox"], [data-toggle="buttons"] > .btn  input[type="radio"], [data-toggle="buttons"] > .btn-group > .btn  input[type="checkbox"], [data-toggle="buttons"] > .btn-group >  .btn input[type="radio"] | Property “pointer-events” doesn't exist :  		none

Not sure if the issue is the code or the validator itself.

**Comment by markw707** [comment]
The error message is:
Property “pointer-events” doesn't exist : none

**Comment by XhmikosR** [comment]
The validator doesn't support everything yet, so you should make such issues to their repo.

**Comment by patrickhlauke** [comment]
related https://twitter.com/patrick_h_lauke/status/961224271296069634

and noting that `pointer-events` is generally supported, just not officially spec'd, and therefore flagged as an unknown property.
