### ISSUE TITLE
Dropdown caret in `.navbar-nav` wrapped to the second line if not enough space is availble

### ISSUE THREAD

**Issue by sesemaya** [twbs/bootstrap#25582]
The dropdown caret of a dropdown toggle in a `.navbar-nav` would be wrapped to the second line, leaving the text by itself on a separate line, when there is not enough space to fit all the `.nav-item`s.

![screen shot 2018-02-08 at 3 09 56 pm](https://user-images.githubusercontent.com/1403640/35955331-dc05b9f4-0ce2-11e8-8af6-6ba96915ac96.png)

For example, go to the current Navbar documentation page: https://getbootstrap.com/docs/4.0/components/navbar/#supported-content, and then resize the browser to somewhere between `992px` and and `1100px` wide, and you should be able to see the problem as illustrated in the above screenshot.

Although one can argue that it is up to the developer to fit appropriate amount of components in a particular area, I think the CSS should still try to make sure the dropdown toggle behaves as intended (i.e. its caret and text should stay on the same line).

**Comment by andresgalante** [comment]
Hi @sesemaya this issue was reported #23932 and it was decided not to fix. Let me know if you have a good idea of how to fix it.

Thanks!

**Comment by sesemaya** [comment]
On a second thought, wrapping is probably the right behaviour (or the best we can do since there is no way to stop just the caret from wrapping). For example, the navbar shown in the screenshot below is probably the acceptable and expected behaviour:

![screen shot 2018-02-12 at 10 19 34 am](https://user-images.githubusercontent.com/1403640/36080053-5c9600f8-0fde-11e8-9871-8154f3d3f162.png)

It is just unlucky that the caret may end up on a separate line by itself sometimes.

The only way I can think of to get around this issue is to allow `flex-wrap: wrap;` by default when the navbar can be expanded, but I am assuming there is a reason for not doing it.

**Comment by mdo** [comment]
Closing as a won't fix for now. We could force the wrapping, but that'd probably screw up someone else's code and customization. Folks can manually tweak the wrapping with our text utilities.
