### ISSUE TITLE
Bug: Dropdown submenu disappearing on scroll

### ISSUE THREAD

**Issue by joneslloyd** [twbs/bootstrap#25588]
We have dropdown submenus on our site.

When a user scrolls down the page, the dropdown submenu disappears.

[Here’s a GIF of the issue](https://giphy.com/gifs/xThtaecIA8zRNWsDoQ/fullscreen)
(The parent menu isn’t moving out of view – It’s always glued to the top of the screen. The GIF is a bit misleading in that respect, as it implies that the parent nav menu goes away, but it doesn’t, rather, just the submenu goes up and over it.)

I’ve noticed the div with a class of `dropdown-menu` also has this attribute:
`x-placement="bottom-start"`
…and when the menu disappears on scrolling, the attribute changed to:
`x-placement="top-start".`

Similarly, the style attribute of the same div changes from:
`position: absolute; transform: translate3d(0px, 60px, 0px); top: 0px; left: 0px; will-change: transform;`

(`60px` being the height of the menu), to:

`position: absolute; transform: translate3d(0px, -257px, 0px); top: 0px; left: 0px; will-change: transform;`

…upon scroll (the `-257px` updates to however far down the page the user has scrolled).

~~I know an obvious/hacky solution is to have a jQuery event to listen for a certain scrollTop position and then manually modify these attributes so that the dropdown always has `x-placement="bottom-start"` and `position: absolute; transform: translate3d(0px, 60px, 0px); top: 0px; left: 0px; will-change: transform;`.~~
**EDIT:**
It turns out the ‘hacky’ solution doesn’t work:
```
const dropdownMenu = () => {
  const $window = $(window);

  $window.on("scroll", () => {
    if (
      $(".dropdown-menu").length &&
      $(".banner").length &&
      $(".dropdown-menu").hasClass("show")
    ) {
      let dropdownMenu = $(".dropdown-menu.show");
      const bannerHeight = $(".banner").height();

      $(dropdownMenu)[0].style.setProperty(
        "cssText",
        `transform: translate3d(0px, ${bannerHeight}px, 0px)!important`
      );
    }
  });
};

export default dropdownMenu;
```
_Variations of the CSS modifying code above also don't work_
I think my updating of the `transform` property is getting over-written by the PopperJS / Bootstrap code that modifies it.

I was wondering if there’s a more ‘correct’ way of solving this than the above, for example interacting with the Bootstrap Dropdown Javascript class, or even PopperJS?

I printed the contents of `window` to the console, and couldn’t find anything Bootstrap-related to interact with.

Any pointers on this would be great!

Cheers,
Lloyd

**Comment by andresgalante** [comment]
Hi @joneslloyd, I don't know JS and I am sure @Johann-S will be able to help here.

But I did put together and out of the box bootstrap page that shows your use case and I don't see the problem:
https://codepen.io/team/Bootstrap/pen/ddvPgg

Is this na issue on your implementation?

**Comment by joneslloyd** [comment]
Hey @andresgalante – Thanks for getting back to me!

I put together an example of the problem [here](https://bay-a.co.uk/bootstrap-issue/).

Just click "Link 2" and then scroll down the page.

I don't _think_ this is an implementation issue, though it's entirely possible.

**Comment by victorsilent** [comment]
Probably one class that you have in your body tag is applying that behavior, if you inspect him you can see that the dropdown respect the body size, but the rest of your html are out of him.
![image](https://user-images.githubusercontent.com/8001358/36066868-54d9660c-0e99-11e8-93c8-430107122c2b.png)

**Comment by joneslloyd** [comment]
@victorsilent – Wow, that's it! Problem solved! Thanks very much for that!
