### ISSUE TITLE
Tooltips and Popovers in img map

### ISSUE THREAD

**Issue by cschra** [twbs/bootstrap#25592]
Hi all,

when migrating from 3.3.7 to 4.0 - The Popovers and Tooltips don't have the same behavior in image maps. I have a SVG image and an image map area which should trigger Popovers - in Bootstrap 3 it worked like a charm, but unfortunately in BS4 this functionality is not working.

The Error is:
Error: Please use show on visible elements tooltip.js

I looked into #25432 and #24918 , but could not find a solution to my problem. 

You can test and see the bug here - just change the Bootstrap version to 4.0 (working until BS4-alpha 5 and not working from BS4-alpha-6 upwards):
https://www.codeply.com/go/y1nltmzO0O/bootstrap-tooltip-over-map-area

I tested on Windows 10 and Linux Mint on Chrome and Firefox.

Kind regards

**Comment by Johann-S** [comment]
Please can you provide a CodePen with our latest release of your bug ?

**Comment by cschra** [comment]
Just out of curiosity, why is my codeply smaple not sufficient?
Here is the codeply version with the most recent release:
https://codepen.io/anon/pen/BYwgyg/

**Comment by Johann-S** [comment]
Because it's easier for us to debug v4 code instead of v3

**Comment by cschra** [comment]
I made a screenshot of the console.log that is displayed, when the Error occurs.

![bug](https://user-images.githubusercontent.com/11518295/36369872-3207d256-155d-11e8-844a-099e41909c5b.JPG)

Any advice how to fix this would be awesome :)
to your reply: in codeply, with the gear at the top, you can adjust the bootstrap version - thats how I found out until which version it was actually working

**Comment by mdo** [comment]
Closing as a stale won't fix. Please update with any relevant details and an updated example if this is still an issue worth pursuing.
