### ISSUE TITLE
Add property for transparent backdrop

### ISSUE THREAD

**Issue by myorangeca** [twbs/bootstrap#25594]
In some instances, I would like to have a the backdrop completely transparent. Currently this is only possible with CSS hack, but it will end up applying the rule for all backdrops. 

I tried the data-backdrop="false" property, however the backdrop does not get generated, thus the 'click backdrop to cancel modal' function is never rendered.

I suggest we add a property for transparent backdrop using data attributes (data-backdrop-transparent="true").

**Comment by mdo** [comment]
You can override this with CSS—change the `background-color` on `.modal-backdrop`.

**Comment by myorangeca** [comment]
@mdo that change will override for all modals. Is there a way to give only selected modals transparent backgrounds?
