### ISSUE TITLE
Collapse Is Firing Twice

### ISSUE THREAD

**Issue by huffdesign** [twbs/bootstrap#25593]
Hello, I'm having an issue with collapse. 

My collapse is firing twice. I have a button at the top of my site when pushed the collapse fires. 
I also have an if statement that has parameters if not met will show the collapse. When the collapse is open and I hit the button the button collapse will open, so I have to hit the button again to close it.

How would I fix this issue? Thanks for your time. 

    <button class="blue-button" type="button" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" >
                    <img src="/img/plus.png" style="padding-right:10px; padding-bottom: 2px; margin: 0px auto; width: 25px; "> REDEEM CLAIM CODE
                </button>
                <div class="
                    @if( count( $corporateLicenses ) )
                        collapse
                    @endif
                    " id="collapseExample" >

**Comment by davidliang2008** [comment]
<button> element doesn't have href attribute does it? Change the <button> to <a> or change href to data-target and see if that fixes the issue?

**Comment by mdo** [comment]
Yup, try fixing the HTML and let us know.

**Comment by huffdesign** [comment]
Thanks for the help.
