### ISSUE TITLE
Sizing up (.form-control-lg) of radio/checkbox produces misaligned labels

### ISSUE THREAD

**Issue by nighthawkbravo** [twbs/bootstrap#25595]
When up-sizing any of checkbox or radio group with form-control-lg, the labels aren't aligned anymore, per screenshot. 

Tested on:
* Chrome 64.0.3282.119 (Official Build) (64-bit) - Linux
* Firefox Quantum 58.0.1 (64-bit)

![infodeq-web-ui - mozilla firefox_048](https://user-images.githubusercontent.com/35754952/36070213-fed319ba-0ebb-11e8-9857-932840fdfa18.png)

**Comment by patrickhlauke** [comment]
Please provide a reduced test case (in codepen, jsbin, jsfiddle or similar) where we can see this in action.

**Comment by mdo** [comment]
`.form-control-lg` and other modifiers are not for our custom controls.
