### ISSUE TITLE
Text center

### ISSUE THREAD

**Issue by cbo317110** [twbs/bootstrap#25603]
Why we don't have a 'tool' for make text centered, like: 'text-sm-center, text-xs-center...' ?

**Based on**
https://getbootstrap.com/docs/4.0/utilities/text/

``` html
<p class="text-sm-left">Left aligned text on viewports sized SM (small) or wider.</p>
<p class="text-md-left">Left aligned text on viewports sized MD (medium) or wider.</p>
<p class="text-lg-left">Left aligned text on viewports sized LG (large) or wider.</p>
<p class="text-xl-left">Left aligned text on viewports sized XL (extra-large) or wider.</p>
```

> It can be a way to maintain code plain and standardized

**Comment by cbo317110** [comment]
**I'm using this right now:**

``` sass
@media (max-width: #{map-get($container-max-widths, 'sm')}) {
  .text-xs-center { text-align: center; }
}

@each $width in $container-max-widths {
  @media (min-width: #{nth($width, 2)}) {
    .text-#{nth($width, 1)}-center { text-align: center; }
  }
}
```

**Comment by razh** [comment]
There is?

https://github.com/twbs/bootstrap/blob/8a628b943cf31ca0a002c08af661a95772480225/dist/css/bootstrap.css#L8753

**Comment by mdo** [comment]
https://getbootstrap.com/docs/4.0/utilities/text/

**Comment by cbo317110** [comment]
@mdo  @razh 
i was using beta version yet,
but when look at docs it's not clear that option
tks for atention
