### ISSUE TITLE
empty dropdown still makes dropdown

### ISSUE THREAD

**Issue by usuarionuevor** [twbs/bootstrap#25609]
ISSUE:
When dropdown-menu is empty (without any dropdown-item) it still shows a very tight empty square.
it should be removed (or not created in first place) if there are no items, just like collapse does.

FIX:
**dropdown-menu should show dropdown-items only when there are actual dropdown-items to show** (just like collapse does with its elements).

Example:
I'm making search bar to show suggestions, it works wonderful with Bootstrap 4.0.0 dropdown but before you start writing it already shows the empty tight square (this is dropdown-menu without any dropdown-item yet):

![empty dropdown](https://user-images.githubusercontent.com/35457371/36149381-bce8a212-10bf-11e8-9aaf-51009caab40f.png)

tested on:
- Microsft Edge 41.16299.15.0
- Google Chrome 64.0.3282.140

**Comment by mdo** [comment]
This seems more like an implementation detail on your end than our own. You shouldn’t show the dropdown until you have something to put in it. We _could_ do something like `.dropdown-menu::empty`, but that feels unnecessary given how most folks use them.

**Comment by usuarionuevor** [comment]
What's the difference with 'collapse' then? because collapse works fine without any element inside.

When you generate dropdown items dynamically it will be always a problem, even if you make dropdown hardcoded it should not drop anything if there is nothing to drop, collapse does the job but I'd prefer to use dropdown here.

Seriously I though that empty tight square looked like a bug.

**Comment by danijelGombac** [comment]
@usuarionuevor  

I change line 133 - 135 of plugin

```
if (isActive) {
        return
}
```

with

```
if (isActive || $(this._menu).is(':empty')) {
        return
}
```

with autocomplete input text and works fine.

**Comment by dvmuccillo** [comment]
Dropdowns in Bootstrap are meant to be triggered by click, so wouldn't be better to you just disable the button that trigger the menu when there is no content?
After all user expect some action when they click something like a button.

**Comment by danijelGombac** [comment]
@dvmuccillo 

I was try disable the input text. But when you typing in the autocomplete input, sometimes  the menu is populated, but sometimes is empty and then should disappear.

**Comment by aGeNET** [comment]
:empty Selector won't be failsafe, if there is any whitespace in your element, it won't be considered as empty anymore - see: https://jsfiddle.net/bpa6sq9e/2/
this has to be checked on your side and the dropdown should only be rendere if there are items in it

**Comment by rafalp** [comment]
There's no smart way to go about this using `:empty` IMHO. You'll do it assuming that dropdown is just `<ul>`, somebody well go "but hey, my js framework puts extra cruft inside dropdown making check fail and display empty anyway!". Somebody else will consider `<ul><li>Search results:</li></ul>` empty and looking at how Bootstrap goes about will seek way to inject custom condition into BS.

If you are programmatically filling the dropdown, you know best when it has contents and doesn't, and so should programmatically show or hide it. Issue's author mistake is trying to use Bootstrap's dropdown logic made for dropdown menus shown on item click for search suggestions.

**Comment by usuarionuevor** [comment]
'empty' maybe is not 100% bullet proof but I think is better than nothing.
If you have white space or pagejump inside and so is not detected as empty then I assume you want to create a empty item on purpose.

The search thing is just an example where I saw that weird pseudo dropdown square, I already fixed using other method is not a problem, THANKS everyone for answers and ideas, and mdo for taking the time and explain things!

**Comment by usuarionuevor** [comment]
Simple css fix, using original bootstrap links, just add a new <style> (after Bootstrap css) with this:


`		.dropdown-menu:empty{
			display:none;
		}
`


I have a few edits to Bootstrap class in my css like add shadows (from Google's Material Design) to `card` class I can share code but is not related here.

**Comment by mdo** [comment]
Closing as a won't fix given the latest comments.
