### ISSUE TITLE
Update system font stack

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#25604]
Chrome will soon deprecate it's `BlinkMacSystemFont` system font alias for `system-ui`, but there are issues with that, too. Need to dig in more and prep something for that.

##

X-ref: https://github.com/sindresorhus/modern-normalize/issues/18

**Comment by walberty** [comment]
Possible approach that uses both `system-ui` and `BlinkMacSystemFont`: https://furbo.org/2018/03/28/system-fonts-in-css/

**Comment by salisburybs** [comment]
> Possible approach that uses both `system-ui` and `BlinkMacSystemFont`: https://furbo.org/2018/03/28/system-fonts-in-css/

This is affecting me on Arch Linux with the Chromium browser version 70.0.3538.102 (Official Build) Arch Linux (64-bit). If I add system-ui, the fonts display correctly again.

I've been trying to locate a chromium changelog showing that BlinkMacSystemFont has been deprecated by I've come up empty so far. Bootstrap 4.0.0 renders correctly, 4.1.X has about two spaces between every character.

**Comment by wolfy1339** [comment]
Linux isn't officially supported by Bootstrap. You might be able to find the or that added the Linux font stack and use those values (they were reverted before v4 stable)

**Comment by bardiharborow** [comment]
@walberty's solution unfortunately won't work because of the issues in #22328. @salisburybs the depreciation is at [crbug 554590](https://bugs.chromium.org/p/chromium/issues/detail?id=554590).

**Comment by tats-u** [comment]
This must be reverted even in languages using Latin or Greek.

https://github.com/tailwindlabs/tailwindcss/issues/19767

<img width="1608" height="411" alt="Image" src="https://github.com/user-attachments/assets/d26037f9-8080-47e1-9a42-2848e06140fe" />

In Japanese Windows, the Greek "Ω" is displayed as the Cyrillic "и" when bolded. ₥i¢r¤$¤₣₮ tends to leave font problems unaddressed.
