### ISSUE TITLE
No date module example code in bootstrap??

### ISSUE THREAD

**Issue by krystyna93** [twbs/bootstrap#25605]
While looking through the bootstrap documentation, I found there is no example output code for the date module.

In the 'reboot' page, https://getbootstrap.com/docs/4.0/content/reboot/?optionsRadios=option1#forms there is the actual date module under the form header that you can test out, but I cannot find that date module with any example code within the https://getbootstrap.com/docs/4.0/components/forms/ in the documentation.

Can anyone explain this, as I would like to use the date module in my bootstrap project.

Thanks.

**Comment by mdo** [comment]
We don't have a date picker if that's what you mean. There are external libraries for this.

**Comment by wolfy1339** [comment]
I think he means, just the date picker input. It's shown on the reboot page, but not on the forms page (using `.form-control` or other class)

**Comment by krystyna93** [comment]
@wolfy1339 Ah, okay, cool. Do you know what the external library bootstrap is using to sample the date picker?

**Comment by wolfy1339** [comment]
None. Just HTML and some CSS
________________________________

**Comment by krystyna93** [comment]
@wolfy1339 I dont think you understand what I mean. @mdo said its an external library that bootstrap is using to use the date picker as a sample in their reboot page... Does anyone know what it is?

**Comment by patrickhlauke** [comment]
(also, the short answer to your question: if you want to use a date picker just like on the reboot page, use `<input type="date">` form control - but be aware that how it works/looks will be completely up to the browser, and will change between browsers)

**Comment by krystyna93** [comment]
@patrickhlauke Ah, Ok, cool. I understand now. Thanks for the clarification 👍

**Comment by mdo** [comment]
Ah yeah. Date input is wildly inconsistent (so is color input) by browser and OS, so we’re kinda hamstrung by what we can do with HTML and CSS. We prefer modifying browser defaults for this vs creating new complex custom solutions.

Perhaps there’s some documentation that could be improved here though for Reboot (ensure folks know those things look as intended) and our forms page to highlight these other input types?

**Comment by krystyna93** [comment]
@patrickhlauke Ah, Ok, cool. I understand now. Thanks for the clarification 👍
