### ISSUE TITLE
carousel transition problem in Firefox

### ISSUE THREAD

**Issue by ben13oit** [twbs/bootstrap#25608]
bug here:
https://getbootstrap.com/docs/4.0/examples/carousel/

W7 pro 64
Firefox 58.0.2

irregular scrolling from right to left only.
White spaces between pics, irregular scrolling speed

**Comment by mdo** [comment]
Confirmed on macOS latest Firefox, too. Affects all carousels it seems.

**Comment by tmacallister** [comment]
Is there a fix for this?

**Comment by jonnysp** [comment]
i wrapped the item contend in a row - col
https://jsfiddle.net/jonnysp/f3pdL9eg/

not the fine english variant - but it works

**Comment by certain2** [comment]
It´s still flickering in FF while sliding. Is there any workaround?

**Comment by XhmikosR** [comment]
This should be fixed in v4-dev. It'd be nice if someone could confirm.

**Comment by XhmikosR** [comment]
Closing for now, since it should be fixed in v4-dev. If not leave a comment.
