### ISSUE TITLE
Bootstrap Modal doesn't allow to override configuration options on runtime

### ISSUE THREAD

**Issue by ash1982ok** [twbs/bootstrap#25619]
Bootstrap modal should allow to override configuration from its 'bs.modal.show' event. Usecase might be to modify the behaviour like backdrop on runtime.
Or 
We can have a bs.modal.initialize event where it can be done?

**Comment by Johann-S** [comment]
you can modify your modal configuration on each of our events.

```js
$('#modal').on('show.bs.modal', () => {
 $('#modal').modal({
   // your new configuration
 });
});
