### ISSUE TITLE
Does modal windows not working after changing from version 3.1.1 to newest version 4.0.0?

### ISSUE THREAD

**Issue by Alex-DE-74** [twbs/bootstrap#25618]
Hello together,

first, thank you for fantastic work!

In order to reproduce a problem here is the link how I done that: https://gist.github.com/rnkoaa/8333940
(of course changed $modal to $uibModal and $modalInstance to $uibModalInstance)

I'm using angular-cli (currently newest version) on Windows 10.

With the following configuration:

```
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  <link data-require="bootstrap-css@3.1.1" data-semver="3.1.1" rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />

  <script data-require="bootstrap@*" data-semver="3.1.1" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <script data-require="ui-bootstrap@*" data-semver="2.5.0" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.js"></script>

was anything fine - modal dialogs were pop-ups and closed as required.

But only with a changed configuration:

  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
  
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script data-require="ui-bootstrap@*" data-semver="2.5.0" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.js"></script>
```

I don't see any modal windows anymore? Also no errors in the log (F12 in Chrome) - that's very strange...

Nothing else is changed. As you can see, only Bootstrap is changed from version 3.1.1 to 4.0.0. May be there are more problems - I don't test further.

What going wrong?

Many thanks for considering my question!

Alex

**Comment by wolfy1339** [comment]
Did you update your HTMl?

**Comment by mdo** [comment]
v3.x to v4 is a massive upgrade—it's a complete rewrite. Make sure you're updating all your HTML, CSS, and JS because it's massively different.

**Comment by Alex-DE-74** [comment]
@wolfy1339 , @mdo 

Excuse me, but I'm totallynew in Angular/Bootstrap.
What should be updated , in case of very simpe example above? Is here any instruction like "how to V3 --> V4"? Is nothing more backward compatible? And why I need to updtae HTML whoch is a simple template?
Thank you again.

**Comment by rafalp** [comment]
> Is here any instruction like "how to V3 --> V4"?

There is one: http://getbootstrap.com/docs/4.0/migration/

**Comment by Alex-DE-74** [comment]
@rafalp 

Excise me, but I don't see here anything about migration or why something old does not work anymore.
Example "Modal":

-  Rewrote component with flexbox.
- Given move to flexbox, alignment of dismiss icons in the header is likely broken as we’re no longer using floats. Floated content comes first, but with flexbox that’s no longer the case. Update your dismiss icons to come after modal titles to fix.
- The remote option (which could be used to automatically load and inject external content into a modal) and the corresponding loaded.bs.modal event were removed. We recommend instead using client-side templating or a data binding framework, or calling jQuery.load yourself.

So, how to migrate from 3.x to 4.x accordingly to above "how-to"? Is templateUrl does not work anymore? The last point about "remote" option is pointless in this situation, because remote option was not used. The rest is about dismissed icons. Nothing more. So, this instruction may be useful for people, who already knows everything about migration (and does not need this instruction) and is totally useless for all, who don't know :(

Thank you.

**Comment by wolfy1339** [comment]
The migration docs are for people who use Bootstrap directly without angular or other things like that.
You should raise your issue with the people at angular.
________________________________

**Comment by Alex-DE-74** [comment]
@wolfy1339 striped off angular, node.js, ui.bootstrap, javasripts, all anithing like that - now the migration doc looks much cleaner... :)
