### ISSUE TITLE
padding class

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#25620]
Any chance of getting the padding class (as found here: https://getbootstrap.com/docs/4.0/utilities/spacing/#notation) made so that it can be applied directly to a `<thead>` or `<tr>` element?

The standard padding on a table header is too much compared to the rest of the table if you use the table-condensed class, If I add a 'p-<size>' class to each <th> element it works, would just rather be able to apply it to the table as a whole (maybe even do away with table-condensed completely).

I at present have a table-padding-xs class which sets the padding on <th> and <td> to 0 because 'condensed' isn't enough.

**Comment by andresgalante** [comment]
What you are asking sounds like a customization of the table. you can write a bit of CSS and do it on your implementation rather than using a utility or modifier class.

**Comment by mdo** [comment]
We have `.table-sm` right now, but no plans for changes to the padding classes for inheriting padding values like this otherwise.
