### ISSUE TITLE
Button sizing

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#25622]
One button size I used all the time with BS3 was 'btn-xs', it fit quite nicely on a table compared to the other sizes, I noticed the option is now gone from BS4, besides changing the size of the 'btn-sm' button in the SCSS files, I suppose the only other way to get it back is a custom CSS file?

**Comment by nardocesar** [comment]
Yes, unfortunately. There's no corresponding to 'btn-xs' in v4, but 'btn-sm' comes smaller than in v3. To get the same fit as v3 'btn-xs' you need to do your own custom class. Something like:

`xs{
    padding: 1px 5px;
    font-size: 12px;
    line-height: 1.5;
    border-radius: 3px;
}`

**Comment by mdo** [comment]
Yup, no plans to restore an `xs` value. You can add these yourself though fairly easily given the mixins and variables we have in place for existing classes.
