### ISSUE TITLE
Accessing the various colours

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#25621]
Is there any way to access the various colours besides the standard 'primary, danger, info, success, etc...'? Possibly something like 'text-<name of colour>'

**Comment by marco-carvalho** [comment]
for me, classes like `bg-success` or `text-danger` shouldnt exist, while classes like `text-orange`, `bg-green`, `text-indigo`, `bg-red` makes **way** more sense

**Comment by ray73864** [comment]
I like having the text-danger, etc.. It's what I'm used to from BS3, but I would also like to have 'bg-blue, text-blue, etc...'.

I already had to create a new version of 'yellow' since the BS4 'yellow' is more like gold.

**Comment by mdo** [comment]
Not currently, and no plans for it right now given how we generate the classes that consume those variables (via Sass maps). Sass cannot generate a list of variables from a map either, so it'd be a manual process to create all these.

**Comment by patrickhlauke** [comment]
if you want to roll your own classes, note that the various colours *are* available as CSS variables https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables / https://caniuse.com/#feat=css-variables

```
--blue: #007bff;
--indigo: #6610f2;
--purple: #6f42c1;
--pink: #e83e8c;
--red: #dc3545;
--orange: #fd7e14;
--yellow: #ffc107;
--green: #28a745;
--teal: #20c997;
--cyan: #17a2b8;
--white: #fff;
--gray: #6c757d;
--gray-dark: #343a40;
--primary: #007bff;
--secondary: #6c757d;
--success: #28a745;
--info: #17a2b8;
--warning: #ffc107;
--danger: #dc3545;
--light: #f8f9fa;
--dark: #343a40;
```

**Comment by ray73864** [comment]
Unfortunately I have to support IE11 which has no support for CSS variables.
