### ISSUE TITLE
Modal not usable without JavaScript. No Fallback

### ISSUE THREAD

**Issue by MaPePeR** [twbs/bootstrap#25625]
A modal is hidden by default, which makes it not usable if one wants to statically show a modal dialog for a user, which might not have JavaScript enabled.

As you can see in [this JSBin](https://jsbin.com/yiyoduvoja/edit?html,output) example one can use `d-block` or `style="display:block"` to force showing the modal and also manually add the backdrop to the html without JavaScript, but the resulting modal is not "JavaScript-enabled". It is not possible to dismiss it by clicking the X or the backdrop.

So at the moment, when showing a Modal to non-JavaScript users the modal has reduced functunality for users with Javacript (In comparison to what would be "possible" for these users). But to add the missing functionality one has to hide the modal for non-JavaScript users which is not an option, because they need to be able to see/use it as well.

I would prefer if users with JavaScript would have access to the full functionality without completely removing the functionality for non-JavaScript users.

EDIT: This issue is kind of related to #24939. If the Javascript code would have an option to read an already shown modal from the DOM both issues could be fixed.

**Comment by patrickhlauke** [comment]
if your concern is making sure that a site which would normally show a modal for JS users on page load to still work (without the modal) for non-JS users, you should trigger the modal programmatically via JS once the page is loaded (so without JS, it's not triggered). or am i missing something?

**Comment by MaPePeR** [comment]
I would like to show the modal for non-JS users.

**Comment by patrickhlauke** [comment]
but those users won't be able to close/dismiss it? i'm failing to understand the specific scenario here

**Comment by MaPePeR** [comment]
They can if the Modal contains a link or form. Sorry, maybe i should have made that more clear and include it in the example.

**Comment by bkdotcom** [comment]
> They can (close the modal) if the Modal contains a link or form. Sorry, maybe i should have made that more clear and include it in the example.

That's not closing... that's navigating away from the page.

**Comment by MaPePeR** [comment]
> That's not closing... that's navigating away from the page.

Yes, but if they navigate away they don't need to close it anymore.

**Comment by bkdotcom** [comment]
If you want the modal open on page load  just use
`class="modal show"`  ??
(instead of simply `class="modal"` or `class="modal fade"`)

**Comment by MaPePeR** [comment]
@bkdotcom yes i know i can do that. But then the modal does not work with javascript. The modal does not behave like a modal unless it is opened with `$(...).modal()`.

**Comment by bkdotcom** [comment]
`<a data-toggle="modal" data-target="#exampleModal" href="some url explaining it's 2018">No JS fallback</a>`

**Comment by MaPePeR** [comment]
@bkdotcom This link will either not be visible for non-js users or not work for js users, so I don't see how it solves the problem.

**Comment by patrickhlauke** [comment]
@bkdotcom's suggestion is perhaps a bit facile.

taking a step back then, this request is asking for the ability to have a modal made explicitly visible in the static HTML by default, and then when JS is present, being able to "bless" the existing open modal to be a working modal.

in the interim, an approach that would possibly also work (and possibly much nicer, because then when JS in not enabled it wouldn't have non-functioning close buttons or similar) is to design the non-JS-enabled version of the page, have the static overlay (made appropriate for the non-JS scenario, i.e. without the "X" close etc) wrapped in a `<noscript>...</noscript>` block, and for the JS-enabled case having the actual modal which triggers on page load. (though yes, that'd mean duplication of the content).

**Comment by MaPePeR** [comment]
> taking a step back then, this request is asking for the ability to have a modal made explicitly visible in the static HTML by default, and then when JS is present, being able to "bless" the existing open modal to be a working modal.

Yes, exactly.

**Comment by herbalite** [comment]
I'm not completely sure if my suggestion below solves your problem completely, but here it goes. Also I haven't tested it completely for possible side effects.

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <script src="https://code.jquery.com/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<style>
		.static-modal
		{
			display: block;
		}
	</style>
	<script>
		var sheet = document.styleSheets [ document.styleSheets.length - 1 ];
		sheet.deleteRule ( 0 );
	</script>
	
</head>
<body>
<div class="modal static-modal" tabindex="-1" role="dialog" id="modal" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <!-- The form and the link are accessible to all users -->
        <form>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
        <a href="#" class="btn btn-secondary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>
	
	<a href="#" data-toggle="modal" data-target="#modal">Open</a>
</body>
</html>
```
This JS code is portable back to IE9. What it does is simply add a class in a local stylesheet and add that class to the modal, and if JavaScript is enabled immediately remove it before the browser engine even reaches the modal markup. If you want the dialog open to JavaScript enabled browser, you'd open it with a script placed after the modal markup on. In my example I just added the usual link to open and I had to remove the modal-backdrop markup part. That's most likely solvable however.

What you have to watch out for is that you know the exact position of the local stylesheet (in this case it's the last one, and as well the position of the rule that you want to remove in the local stylesheet.

Hope that helps

**Comment by MaPePeR** [comment]
@herbalite Thats a very good workaround, which solves the problem i tried to describe in this issue! :+1: 
I think it would be better to change bootstrap in a way that does not require this workaround, though.
(I think) one could easily add the default "show all modals"-class to bootstrap.css and the "hide all modals"-Javascript to the bootstrap.js.
Making the modals "show by default" instead of "hide by default"

@noobshow Sadly this is basically a reimplementation of a modal dialog, which should not be needed, because Bootstrap already has a very good CSS modal implementation. Or i'm missing something obvious here.

**Comment by Johann-S** [comment]
Sorry but currently there is no plan to use our Modal without JavaScript.

Before closing this issue, @mdo do you have any plan to allow that ?

**Comment by noobshow** [comment]
@Mapeper You're missing the point there... It's not just a dialog i mean.
You can port the open and close to your custom css which would make the modal(even bootstrap modal) open and close with/without javascript.

**Comment by bkdotcom** [comment]
@noobshow 
Cool!  Looks like one of the examples on MDN:
https://developer.mozilla.org/en-US/docs/Web/CSS/:target

**Comment by noobshow** [comment]
Is there anyone watching this?
Maybe this could be implemented as a fallback?

**Comment by mdo** [comment]
Apologies for the delay—no plans to implement any changes here to run the modal without JavaScript.
