### ISSUE TITLE
How do I run npm run dist for a custom scss file outside of bootstrap folder?

### ISSUE THREAD

**Issue by aligajani** [twbs/bootstrap#25635]
![image](https://user-images.githubusercontent.com/1730778/36266656-e92f8bf0-1269-11e8-9221-f4bc685b69cc.png)

So I am using the latest version of bootstrap, which is 4, and I am running into some issues on how I can customize scss from a folder outside of `bootstrap-4.0.0'. Is there a cleaner way to do this? 

If I run `npm run dist` inside the `bootstrap-4.0.0` folder, I will only build the `.css` files in the `bootstrap-4.0.0/dist` and this is fine, but how can I link in my `scss/_custom.css` in the root?

**Comment by wolfy1339** [comment]
Check `package.json`, the commands are all there.
You'll need to update them for your custom SCSS

Did you import Bootstrap from your SCSS file?

**Comment by aligajani** [comment]
You are right. I just realized that I can potentially output the `dist` into my root, can't I?

**Comment by wolfy1339** [comment]
Yes

**Comment by aligajani** [comment]
Okay here's the interesting question now. How can I actually build the site while making realtime changes to my `scss` files. AFAIK know `npm run dist` only is for building production files. If I link the production .css file into my .html and run `npm run watch`, I wouldn't see changes. What's the prefered way to solve this problem @wolfy1339 .

**Comment by mdo** [comment]
That all depends on your setup, and is outside the scope of this issue tracker. Check our readme for links to our Slack and StackOverflow for more information.

**Comment by aligajani** [comment]
@mdo  Thanks, I will check other places out. I hacked together a solution but I still think there needs to be either better documentation or at least a cleaner build system that just lets us compile SCSS to CSS, without all the doc-compile, etc.
