### ISSUE TITLE
Bootstrap navbar not loading properly every time

### ISSUE THREAD

**Issue by GeorgEdy** [twbs/bootstrap#25634]
It looks like the navbar isn't fully loading everytime, it stucks middleway. If I empty the cache, or I have developer tools open, it loads properly, but if I refresh the page a couple of times it doesn't. The issue appears on Chrome on windows 10 (I'm using the last Version 64.0.3282.167) and Safari 11 on OX High Sierra. I tested it also on Firefox Developers Edition and Opera Neon, and on those is working properly every time. 
I thought it was maybe from my styling, but I removed it and it still does the same. I attached some screenshots. First 2 with my styles(first one bugged, the second looking properly) and the latter 2 with no styling(first bugged, second properly). As you can see, the logo is smaller when it's not loading how is supposed to. I see the animation of elements placing in their supposed position everytime, but some of the times it just stops middleway.

![1stylednotworking](https://user-images.githubusercontent.com/16291317/36261720-ffc95d24-126d-11e8-825b-1e47d54a1a99.jpg)
![2styledworking](https://user-images.githubusercontent.com/16291317/36261717-ff71b3e4-126d-11e8-91ed-e27560a5895b.jpg)
![3nostylenotworking](https://user-images.githubusercontent.com/16291317/36261718-ff8ffb6a-126d-11e8-97f2-ab0a8ed5edaa.jpg)
![4nostyleworking](https://user-images.githubusercontent.com/16291317/36261719-ffabb346-126d-11e8-869f-b3dc6e104e00.jpg)

**Comment by andresgalante** [comment]
Hi! can you please send a preview where I can reproduce this problem, can you please test it here also: http://getbootstrap.com/docs/4.0/examples/navbars/

see if it happens in out of the box bootstrap too.

Thanks!

**Comment by GeorgEdy** [comment]
Hello,

The website is built on wordpess, with a custom theme. It's very hard to replicate the circumstances, so I'll just give you the current link: http://dev.itup.ro/rives/ . 
The bootstrap resources are loaded from cdn. 

Note: you might notice that there are 2 menus on the site, one for desktop, one for mobile. It has nothing to do with that. The second one was added just today, the issue is present since last week but until now I thought it has something to do with my styles, but I think there is a problem on bootstrap's javascript.

**Comment by mdo** [comment]
Our JS doesn't affect the initial rendering of our navbars. I'm guessing your page's assets are timing out—your page load is 16.4MB currently, according to my inspector.

**Comment by GeorgEdy** [comment]
Unfortunately, that's not the issue. I made a new test page( http://dev.itup.ro/rives/test/ ), where I'm loading just the header and the footer, and also used one of the navbars from your templates. Still the same issue. Only 500kb is loaded and the load time is reduced to more than half. 
![empty](https://user-images.githubusercontent.com/16291317/36304124-23f6c6d8-1317-11e8-85f0-f550d963e68f.jpg)
![network](https://user-images.githubusercontent.com/16291317/36304134-2b3b21a0-1317-11e8-852d-9410122fc579.jpg)

**Comment by mdo** [comment]
Oh, looks like it could be your `padding` values set in `%` units mixed with the changing size of the `<body>` element. Try not using percentages for those padding values and ensuring `<html>`/`<body>` elements are matching 100% height. By default a `<body>` element will not grow beyond it's contents.

**Comment by GeorgEdy** [comment]
Damn it, that was it. The irony is that my current purpose is to stop using percentage values for padding, and use em instead. A bad habit evolved from lack of enough knowledge which I'm trying to fix. 
Thank a lot and sorry for the trouble. I'm also glad that nothing is wrong with bootstrap. You can close the thread now.
