### ISSUE TITLE
Tooltips on flex full-height containers glitch and appear off-center on IE11

### ISSUE THREAD

**Issue by dave96** [twbs/bootstrap#25638]
Hi,
I stumbled upon a browser-specific bug with tooltips today. So far I've been able to reproduce it with:

- Windows 7 + IE11
- Windows 10 + IE11

The problem appears when the document body is set as a flex container and forced to span the full height of the viewport. This is usual when using footers that stick to the bottom of the page.
The main content then is set as flex: 1 0 auto; and the footer and header stick then to its respective positions.

On IE11, when using this kind of configuration, tooltips will glitch the page for a moment, as they make the scrollbar appear and disappear quickly, and then will be positioned off-center as a result of that glitch (the scrollbar will move the components and Popper.js will calculate the position with the scrollbar, then the scrollbar disappears and the tooltip is no longer in the right place).

This is the end result:
![image](https://user-images.githubusercontent.com/948343/36270010-f69a5e9e-127a-11e8-9c8f-e129eef6b25e.png)

Attaching an absolutely positioned element on the document body when it is a flex container as I've described, will cause the scrollbar to appear on IE11. This is the root of the problem.

I've fixed this at work with a pretty simple addition to the .tooltip class. If the position is set to top left by default, attaching it will not cause the scrollbar to appear. So this would fix the problem (with no side effects for other browsers that I've tested):

`.tooltip {
  left: 0;
  top: 0;
}`

A minimal example of the issue that I'm mentioning is availible here (browse with IE11): https://codepen.io/ReyJamonico/pen/PQOoQo 

The fix is commented out as well. 
I would be open to creating a PR for this fix if it saves time.

**Comment by SjoerdWesterhof** [comment]
Had the same issue. Quickly flashing the scrollbar due to content added to body in IE11 on Windows 10. Your solution fixed it.

**Comment by mdo** [comment]
Given the age of the issue and v5 dropping IE11, I'm inclined to call this one a stale won't fix. I do wonder if changing the `container` option for the tooltip would solve these issues vs custom CSS, which we can't unilaterally add as far as I can tell.
