### ISSUE TITLE
Affix usage bad example

### ISSUE THREAD

**Issue by a-rusak** [twbs/bootstrap#25633]
#### [Affix usage via JavaScript example:](https://getbootstrap.com/docs/3.3/javascript/#affix-usage)
```javascript
$('#myAffix').affix({
  offset: {
    top: 100,
    bottom: function () {
      return (this.bottom = $('.footer').outerHeight(true))
    }
  }
})
```
This code doesn't work as expected: reassign `this.bottom` from `Function` to `Number` causes the bottom position is not updated.
#### Correct sample:
```javascript
$('#myAffix').affix({
  offset: {
    top: 100,
    bottom: function () {
      return $('.footer').outerHeight(true)
    }
  }
})
```

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by a-rusak** [comment]
> docs improvements
my suggestion is docs improvement
