### ISSUE TITLE
incompatible units 'rem' and 'px ; bootstrap\scss\_variables.scss line 420

### ISSUE THREAD

**Issue by ringodotnl** [twbs/bootstrap#25632]
OS: Win10, Browser Chrome latest, Bootstrap 4 (installed with npm)

Trying to include the bootstrap styling into an Angular 5+ project by adding it at styles.scss with:
@import "~bootstrap/scss/bootstrap";

When compiling  gives the following error:
[1] ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
[1] Module build failed:
[1] undefined
[1]                                        ^
[1]       Incompatible units: 'rem' and 'px'.
[1]       in D..\node_modules\bootstrap\scss\_variables.scss (line 420, column 41)

Also line 423 and line 599 do give the same issue when manual fix it by line.

**Comment by wolfy1339** [comment]
The issue is not with Bootstrap and is quite clear.
px and rem are incompatible units, you can't use px values in Bootstrap 4 anymore.
Also, this issue has already been posted, please search before opening an issue

**Comment by andresgalante** [comment]
Hi @ringodotnl if you are trying to customize the grid breakpoints please use `px` as it's described here:

> Make sure to set grid values in px (not rem, em, or %).
http://getbootstrap.com/docs/4.0/layout/grid/

If you want to use px's for font size, you can probably read this issue:
https://github.com/twbs/bootstrap/issues/23982

**Comment by ringodotnl** [comment]
@wolfy1339  Thank you, I saw that issue but this is a different story I think. 
So I only included bootstrap scss in the project, haven't use / modify anything in the project so didn't expect to see an error at this point.

@andresgalante thank you, I haven't used bootstrap at all other then including it in the project.

**Comment by wolfy1339** [comment]
That's abnormal, but Bootstrap doesn't have this problem though. :shrug:
I'm not sure what it could be other than that
________________________________

**Comment by ringodotnl** [comment]
@wolfy1339  when I change the 3 lines listed before in bootstrap to 1 rem then it's solved. 
Also when I use like bootstrap/dist/css/bootstrap.min.css instead of the scss there's no problem either.

Cheers,
Ringo.

**Comment by ringodotnl** [comment]
It turned out that there was loaded some other scss before bootstrap which caused the issue. 
Switching the load order (so bootstrap first) solved this.

Thank you @all!

**Comment by devsekhar** [comment]
Thanks It worked for me! Placing the @import "../node_modules/bootstrap/scss/bootstrap";
on top into the styles.scss file.
