### ISSUE TITLE
Form validation Input type email regex

### ISSUE THREAD

**Issue by MARISAAVAST2** [twbs/bootstrap#25648]
bootstrap 4.0 -> validation

https://getbootstrap.com/docs/4.0/components/forms/#validation

Input -> type -> email -> Value = **x@x**  is valid -> form submit -> show div class -> valid-feedback

regex used in type=”email” from W3C:
`  /^[a-zA-Z0-9.!#$%&’*+/=?^_`{\|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/ `

- Operating system  (Windows 10 x64)
- Browser  (Chrome Versión 64.0.3282.167 (Build oficial) (64 bits) )

**Comment by patrickhlauke** [comment]
so what's the point you're trying to make? the validation section doesn't include an email example (and validation itself uses the browser's built-in validation, so it's up to the browser to run appropriate regexp behind the scenes to then set the correct valid/invalid pseudoclass that bootstrap then styles.

**Comment by bkdotcom** [comment]
> Value = x@x is valid

you are correct

> regex used in type=”email” from W3C:
`/^[a-zA-Z0-9.!#$%&’*+/=?^_{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$/ `

regex matches 'x@x'  

Official w3c email regex tester:
https://www.regextester.com/97767

https://en.wikipedia.org/wiki/Email_address#Examples
valid:   'user@localserver'
