### ISSUE TITLE
breadcrumb-Component has default margin/padding/background-color

### ISSUE THREAD

**Issue by MaPePeR** [twbs/bootstrap#25640]
To me it feels like the `breadcrumb`-Component is stuck in Bootstrap v3.
It seems like in v4 a lot of default margin/padding and background-colors were removed in favor of the `m-`, `p-` and `bg-` classes. This is not true for the `breadcrumb`-Component, though. I would expect it to be like `breadcrumb bg-transparent m-0 p-0` instead of its current style in 4.0.0, that does use margin, padding and a background color.

See [this JSBin Comparison](https://jsbin.com/pavitafabu/1/edit?html,output).

**Comment by mdo** [comment]
Thanks for the feedback, but we'll likely be leaving it as-is for the time being.
