### ISSUE TITLE
Navbar colors not in new Alpha update

### ISSUE THREAD

**Issue by dougie84mo** [twbs/bootstrap#25650]
I have looked everywhere when updating to the new Alpha 6.0.0 version while installing with yarn. Using symfony encore, i got everything to work properly due to the new css selectors used for things like the input groups. I even downloaded the new version from the website and here on github. None of these three versions have the navbar-{insert color here} selectors in the css file. None of the colors work or are in the css nor scss.

Now my navbar has no determinate colors other as the same color as the background.

Please fix this bug! Its in the documentation but not in the new update.
Thanks!

ALSO ******** PLEASE ADD GOOD SUPORT FOR YARN!

As well the new input group feature does not work either

**Comment by dougie84mo** [comment]
Here is the old beta version css if someone needs a work around for now

.navbar-light .navbar-brand {
  color: rgba(0, 0, 0, 0.9);
}

.navbar-light .navbar-brand:focus, .navbar-light .navbar-brand:hover {
  color: rgba(0, 0, 0, 0.9);
}

.navbar-light .navbar-nav .nav-link {
  color: rgba(0, 0, 0, 0.5);
}

.navbar-light .navbar-nav .nav-link:focus, .navbar-light .navbar-nav .nav-link:hover {
  color: rgba(0, 0, 0, 0.7);
}

.navbar-light .navbar-nav .nav-link.disabled {
  color: rgba(0, 0, 0, 0.3);
}

.navbar-light .navbar-nav .show > .nav-link,
.navbar-light .navbar-nav .active > .nav-link,
.navbar-light .navbar-nav .nav-link.show,
.navbar-light .navbar-nav .nav-link.active {
  color: rgba(0, 0, 0, 0.9);
}

.navbar-light .navbar-toggler {
  color: rgba(0, 0, 0, 0.5);
  border-color: rgba(0, 0, 0, 0.1);
}

.navbar-light .navbar-toggler-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
}

.navbar-light .navbar-text {
  color: rgba(0, 0, 0, 0.5);
}

.navbar-dark .navbar-brand {
  color: white;
}

.navbar-dark .navbar-brand:focus, .navbar-dark .navbar-brand:hover {
  color: white;
}

.navbar-dark .navbar-nav .nav-link {
  color: rgba(255, 255, 255, 0.5);
}

.navbar-dark .navbar-nav .nav-link:focus, .navbar-dark .navbar-nav .nav-link:hover {
  color: rgba(255, 255, 255, 0.75);
}

.navbar-dark .navbar-nav .nav-link.disabled {
  color: rgba(255, 255, 255, 0.25);
}

.navbar-dark .navbar-nav .show > .nav-link,
.navbar-dark .navbar-nav .active > .nav-link,
.navbar-dark .navbar-nav .nav-link.show,
.navbar-dark .navbar-nav .nav-link.active {
  color: white;
}

.navbar-dark .navbar-toggler {
  color: rgba(255, 255, 255, 0.5);
  border-color: rgba(255, 255, 255, 0.1);
}

.navbar-dark .navbar-toggler-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
}

.navbar-dark .navbar-text {
  color: rgba(255, 255, 255, 0.5);
}

**Comment by browner12** [comment]
why are you installing an Alpha version? we are at a stable release now that you should be using.

updates are not made to Alpha and Beta versions.

**Comment by wolfy1339** [comment]
What's wrong with Yarn and Bootstrap? It should "just work" out of the box, as yarn is a step-in replacement for NPM

**Comment by patrickhlauke** [comment]
going to close this as it refers to the old alpha. please try using the current stable, and if you are still experiencing problems, open a new issue (with some more information, and a test case, showing the problem).

**Comment by dougie84mo** [comment]
I didnt want to be left behind with the new version. And Seeing that the new version was out i figured it was legit. I just didnt want to be stuck using developing with the older version and liked what the 4th one had to offer in cleanliness. 

Thanks though I will be using the stable version for now until the new 4.1 comes out. Do you know when that will be.
