### ISSUE TITLE
Card width excesively narrow

### ISSUE THREAD

**Issue by usuarionuevor** [twbs/bootstrap#25658]
`card` get too shrunk before suddenly turn into one card instead of making a more progressively transition like 3cards > 2cards > 1card.

 

Example: https://getbootstrap.com/docs/4.0/components/card/

 
![card](https://user-images.githubusercontent.com/35457371/36371970-ecfad706-1563-11e8-8caf-5ae72100d190.png)

 

and then:

 

![1](https://user-images.githubusercontent.com/35457371/36372020-114af4d8-1564-11e8-907c-3d32cbcd7335.png)

**Comment by mdo** [comment]
Going to close as a won't fix for v4. We'll end up deleting this card layout come v5 given it's lack of control over horizontal card layouts like Masonry can provide.
