### ISSUE TITLE
Custom select focus glow not correct/consistant.

### ISSUE THREAD

**Issue by Bodom78** [twbs/bootstrap#25656]
Live example can be see on the docs page https://getbootstrap.com/docs/4.0/components/forms/#select-menu

When you focus the glow is not consistant with other inputs.
[
![bscs1](https://user-images.githubusercontent.com/139152/36361863-a6170bc8-1583-11e8-9fa1-8df1f61de594.jpg)
](url)

Valid and Invalid apply the correct focus glow when I add the classes via console.
![bscs2](https://user-images.githubusercontent.com/139152/36361888-d44cc4ec-1583-11e8-9716-0e0d5bc4bfb3.jpg)
![bscs3](https://user-images.githubusercontent.com/139152/36361889-d755173e-1583-11e8-800e-ec66e93fdf42.jpg)

**Comment by Bodom78** [comment]
https://github.com/twbs/bootstrap/blob/c381d199655586d949a0929868bea889aed46fa8/scss/_variables.scss#L499

Should be

```
$custom-select-focus-box-shadow:    $input-focus-box-shadow !default;
```

Or

```
$custom-select-focus-box-shadow:    $input-btn-focus-box-shadow !default;
```

**Comment by victorwpbastos** [comment]
Same here

**Comment by MoritzBru** [comment]
Also visible in the screenshots that firefox does not respect the `outline: 0;` on `select` when you use the keyboard to focus  :(
However there is a really hacky way to get rid of it: https://stackoverflow.com/questions/3773430/remove-outline-from-select-box-in-ff/18853002#18853002

**Comment by martinbean** [comment]
As well as the “glow” styling not being consistent, custom selects don’t have an inner shadow when `$enable-shadows` is `true`, leading it to look inconsistent to other input types on the same page:

![screen shot 2018-05-30 at 20 14 52](https://user-images.githubusercontent.com/167312/40742361-2fe227aa-6446-11e8-945b-3574c271b4b3.png)
