### ISSUE TITLE
this.element.getAttribute is not a function

### ISSUE THREAD

**Issue by thenitai** [twbs/bootstrap#25655]
Including:

jquery-3.3.1.js
popper.js ((1.12.9)
bootstrap.js (4.0.0)

I get in the console the error:

TypeError: this.element.getAttribute is not a function

Same error in all browser, i.e. Safari, Firefox, and Chrome (all latest versions).

**Comment by bkdotcom** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, and specific browser and OS details.

**Comment by Johann-S** [comment]
what @bkdotcom said 👍

**Comment by thenitai** [comment]
It was an issue with my gruntfile and concat
