### ISSUE TITLE
Where did blockquote-reverse go?

### ISSUE THREAD

**Issue by setjmp2013** [twbs/bootstrap#25669]
Before opening an issue: Not sure if this is my own environment. Though the code:

&lt;blockquote class="blockquote blockquote-reverse"&gt;
&nbsp;&nbsp;&nbsp;&lt;p&gt;This is my quote to make me famous&lt;/p&gt;
&nbsp;&nbsp;&nbsp;&lt;footer class="blockquote-footer"&gt;By Laurence Svekis&lt;/footer&gt;
 &lt;/blockquote&gt;

   Does not align right and move the long dash prior to the footer to the end of it.. I searched the bootstrap.css and it comes up with no occurance of .blockquote-reverse. The specific bootstrap is sources via npm, version 4.0.0 . Built via SASS into the used bootstrap.css however it also appears the dist in the bootstrap npm module also lacks the class.

  OS Windows 8.1
  Browser Google Chrome 64.0.3282.140 (Official Build) (64-bit)
  Browser Firefox Quantum 58.0.2 (64-bit)

 I attempted class+="text-right" that does handle the alignment, however the leading dash remains leading on the footer rather than after the text.

  With numerous google searches and on this github, found no similiar issues. I'm in the process of migrating from alpha to release for mainstream use and hopeful to find the changes that effect this, or simple extra CSS to re-implement it if the feature is gone. Thank you for any response.

**Comment by Johann-S** [comment]
Not found in our dist files 😟

**Comment by kevdotbadger** [comment]
Huh? 

`Custom <blockquote> styling has moved to classes—.blockquote and the .blockquote-reverse modifier.` does that not do what it used to do?

**Comment by mdo** [comment]
Removed in #22949, but looks like I never updated the migration docs.

**Comment by ayershov777** [comment]
Hello,

The migration docs have still not been updated yet.
