### ISSUE TITLE
Documentation sample-code typo

### ISSUE THREAD

**Issue by JonRicht** [twbs/bootstrap#25663]
Good afternoon,

I couldn't find information as to how I should report _a typo at the Bootstrap website_, so I'm mentioning it here; my apologies if this is the wrong place to do so.

https://v4-alpha.getbootstrap.com/components/modal/

The second example on the page ("Live Demo") contains a button that works, but the sample code does not.  I've used too many square brackets to highlight the problem in the sample code below:

```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" [[[[data-target="#exampleModal"]]]]>
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" [[[[id="myModal"]]]] tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
```

It didn't cause me any problems, so this shouldn't be isn't a huge issue.  Just thought I'd mention it.

Thanks,

Jon Richt

**Comment by mdo** [comment]
Alpha is long out of date. Please use the latest version at https://getbootstrap.com.
