### ISSUE TITLE
Table row-variants does not respect font-color

### ISSUE THREAD

**Issue by tomsommer** [twbs/bootstrap#25675]
When adding `table-danger`, it does not adjust `color` like other *-danger contexts do, like buttons etc.

Basically https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_table-row.scss#L10 needs `color: color-yiq($background);`

**Comment by mdo** [comment]
Closing this out as a won't fix—the class names don't dictate exactly what CSS properties are applied, only their general color and semantics. I think we can address this another time if we ever reboot how we do our utilities and modifiers.
