### ISSUE TITLE
light weight version of bootstrap

### ISSUE THREAD

**Issue by BigGitWorld** [twbs/bootstrap#25676]
I'm going to use bootstrap in a raspberry pi.
but I dont have sufficient memory for 500 kb needed by version 4.
so I need a lighter version.
How can I do this?

please notify me
thanks in advance

**Comment by MartijnCuppens** [comment]
For Bootstrap 3, this might be useful: https://getbootstrap.com/docs/3.3/customize/. 

I don't think there is a v4 version of this, but you can download the source, exclude stuff you don't need and use the compiled js/css?

**Comment by Johann-S** [comment]
I don't know how do you get Bootstrap but if you download `bootstrap.min.css` it's `145kb` and if you download `bootstrap.bundle.min.js` it's `67.2kb` you won't have `500kb` of Bootstrap but `212.2kb`

**Comment by BigGitWorld** [comment]
Therefore the only file that is needed for css is bootstrap.min.css?
So what is the other files like bootstrap.min.css.map , bootstrap-grid.min.css and others? 
what about javascript too?

**Comment by Johann-S** [comment]
the only one you need if you want all of our css features it's `bootstrap.min.css` and the other will be usefull if you need for example just our grid (`bootstrap-grid.min.css`).

About JS you only need : jQuery and `bootstrap.bundle.min.js` that's all

**Comment by BigGitWorld** [comment]
thank you very much...
