### ISSUE TITLE
Can not create new breakpoints in bootstrap 4 using CDN

### ISSUE THREAD

**Issue by kizoso** [twbs/bootstrap#25683]
I use BootstrapCDN. Other styles written in sass and built by gulp. I need to create my own breakpionts. Is it possible to make them if I use CDN? For example, I want to create these breakpoints:

    --breakpoint-xxxs: 0;
    --breakpoint-xxs: 320px;
    --breakpoint-xs: 568px;
    --breakpoint-sm: 667px;
    --breakpoint-md: 768px;
    --breakpoint-lg: 992px;
    --breakpoint-xl: 1200px;
    --breakpoint-xxl: 1440px;
    --breakpoint-xxxl: 1600px;

I want to get something like this with working media:

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <div class="container">
    	<div class="row">
    		<div class="col col-xxxs-1 col-xxs-2 col-xs-3 col-sm-4 col-md-5 col-lg-6 col-xl-7 col-xxl-8 col-xxxl-9">
    			<div style="height:100vh;background:purple">text</div>
    		</div>
    	</div>
    </div>

I found [the manual][1] and I'm trying this:

    $grid-breakpoints: (xxxs: 0, xxs: 320px, xs: 568px, sm: 667px, md: 768px, lg: 992px, xl: 1200px, xxl: 1440px, xxxl: 1600px)!default
  
    $container-max-widths: (xxxs: 0, xxs: 320px, xs: 568px, sm: 667px, md: 768px, lg: 992px, xl: 1200px, xxl: 1440px, xxxl: 1600px)!default

    \:root
      --breakpoint-xxxs: 0
      --breakpoint-xxs: 320px
      --breakpoint-xs: 568px
      --breakpoint-sm: 667px
      --breakpoint-md: 768px
      --breakpoint-lg: 992px
      --breakpoint-xl: 1200px
      --breakpoint-xxl: 1440px
      --breakpoint-xxxl: 1600px

    

But it doesn't work. What I'm doing wrong?  
If that is not possible... Is there any alternative? Can I easily edit my code to simulate bootstrap grid with my breakpoints? 
Thank you in advance for your help.

  [1]: http://blog.codeply.com/2016/06/06/how-to-create-a-new-breakpoint-in-bootstrap-4/
  [2]: https://codepen.io/kizoso/pen/oEyeVd
  [3]: https://stackoverflow.com/questions/48924751/how-to-create-new-breakpoints-in-bootstrap-4-using-cdn/48925128#48925128

**Comment by browner12** [comment]
The CDN is providing you **compiled css**, not the source SASS.  Therefore, you cannot use the SASS variables to add extra breakpoints.

If you would like to create custom code, download BS4 from Yarn/NPM/etc

**Comment by mdo** [comment]
Yup, what @browner12 said. You're mixing CSS variables with Sass variables; if you want to customize Bootstrap's source code, you'll need to compile the Sass.

**Comment by kizoso** [comment]
@browner12 @mdo Thank you, but I found [the solution](https://stackoverflow.com/questions/48924751/how-to-create-new-breakpoints-in-bootstrap-4-using-cdn/48974556#48974556).
