### ISSUE TITLE
Feature suggest - .card-columns

### ISSUE THREAD

**Issue by Medellic** [twbs/bootstrap#25689]
I read up on the behavior of the card-columns which is supposed to provide the kind of masonry look like Pinterest. I understand that there is a default behavior that makes the thing load from top to bottom and then from left to right and that this was intended so. But I find this extremely terribly horrible, for the following reason, which I encountered in my own code and which forced me to stop using this option.
I was loading over 300 cards into the screen, with images and texts on each. It takes time for the whole thing to load, and you can clearly see how the cards are pushed from left to right as the columns are filling up, right until the beginning of the right-most column. The entire content jumps and scrolls and terribly annoyingly moves until then.
On the other hand, if the cards were loaded from left to right first, and only then from top to bottom, you'd only see the first dozen or so items loaded, and the rest would fall outside of your screen. The prolonged loading time would no longer be in front of you, you would not notice any changes due to the time required for loading being too long.
Not to mention that if you wish to organize something, it gets organized from top to bottom, while your viewers expect to see it organized from left to right.
The way card-columns works today may be beneficial for some issues - though I can't think of a single one -, but it's definitely terrible for the most common use cases.
**I suggest to create a version of this feature that loads from left to right first, and from top to bottom after that.**

**Comment by mdo** [comment]
It'd be cool to have that, but that's beyond the scope of CSS's columns spec. That requires either some different HTML & CSS (consider using our grid perhaps?) or a custom JS solution (Masonry works, too).
