### ISSUE TITLE
Buttons do not consume button focus box shadow variable

### ISSUE THREAD

**Issue by gregbown** [twbs/bootstrap#25681]
Bootstrap version 4.0.0 the _buttons.scss does not utilize the already defined variable for button box shadow, therefore; overriding the variables has no effect because the box shadow is hard coded inside _buttons.scss.   It would seem that this was unintentional since time was taken to define these in the variables?

```
  &:focus,
  &.focus {
    // box-shadow: 0 0 0 $btn-focus-width rgba($color, .5); // <- Bootstrap is not using it's own variables
    box-shadow: $input-btn-focus-box-shadow;
  }
```
- Operating system and version (Windows 10)
- Browser and version (All)

**Comment by mdo** [comment]
You're quoting the button mixin CSS, which we use to color the focus shadow to match each button. Default buttons and inputs use the variable you're citing while button variants use custom.
