### ISSUE TITLE
Overflow issue on .sr-only

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#25686]
As identified by @Orhleil on boosted : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/84

Reduced test case https://jsfiddle.net/etr3yjv6/10/

On chrome (v64 tested) there's an oveflow onto the main container. That one could be fixed by adding a `margin: -1px` onto the sr-only class

**Comment by mdo** [comment]
Is this still an issue?

**Comment by Lausselloic** [comment]
Hello, Yes it's still an issue. We need to add `margin: -1px;` on `.sr-only` class

**Comment by MartijnCuppens** [comment]
I can't seem to reproduce this anymore. If this is still an issue, please reopen with browser & OS info.

**Comment by ysds** [comment]
It seems to be reproducible.

Current: https://codepen.io/anon/pen/bZBjRa (`body` has scrollber)
After: https://codepen.io/anon/pen/drOjzG

![image](https://user-images.githubusercontent.com/4065765/53846018-b00e3c00-3fee-11e9-9d7b-0399ae4b9f49.png)

**Comment by AnupamKhosla** [comment]
@ysds I don't see the issue anymore in my mac M4 chrome:

Current: https://codepen.io/anon/pen/bZBjRa (body has scrollber)
After: https://codepen.io/anon/pen/drOjzG

Both are same
