### ISSUE TITLE
Custom checkbox checkmark fails to display on IE11

### ISSUE THREAD

**Issue by ptoghb** [twbs/bootstrap#25696]
The checkmark in custom checkbox does not display consistently in IE11 when checked, while the background color does.    This issue usually happens when the page first loads.  After that, it works fine.

The issue can be recreated here : https://www.quackit.com/html/html_editors/scratchpad/preview.cfm?example=/bootstrap/bootstrap_4/tutorial/bootstrap_4_custom_forms_checkboxes

It's happening in Windows 7 Pro and Windows 10.

**Comment by ysds** [comment]
very strange behavior.

Demo: https://codepen.io/anon/pen/gvQgXV

![checkbox](https://user-images.githubusercontent.com/4065765/36710016-974073b4-1bbe-11e8-963c-827c8ef09685.gif)

There had been a problem that pseudo-element is not updated with hover in old IE, but this is similar to it.
