### ISSUE TITLE
Bootstrap popover breaking on google chrome and Firefox but working fine on Safari

### ISSUE THREAD

**Issue by karankia** [twbs/bootstrap#25695]
Facing a issue with bootstrap popver with mouseover event and trigger as hover. In Google chrome the Popover box will either break or disappear, however its working fine on  Safari. I am using google Chrome Version 64.0.3282.167 (Official Build) (64-bit)
![screen shot 2018-02-23 at 2 29 33 pm](https://user-images.githubusercontent.com/8050469/36617105-3b2232aa-18b4-11e8-819e-586fe967b13e.png)
![screen shot 2017-12-18 at 2 10 48 pm](https://user-images.githubusercontent.com/8050469/36617152-6316cf6e-18b4-11e8-8263-a9590176f926.png)

**Comment by wolfy1339** [comment]
Please complete your issue with the following details: Bootstrap version, OS name & version

**Comment by karankia** [comment]
Using BootStrap Version 3.3.4 OS:Mac OSX High Sierra 10.13.3

**Comment by mdo** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

---

_This is a saved reply._
