### ISSUE TITLE
Buttons focus box shadow

### ISSUE THREAD

**Issue by Simpleqode** [twbs/bootstrap#25693]
Overriding neither `$input-btn-focus-box-shadow` nor `$btn-focus-box-shadow` seem to affect the actual button box shadow in the focus state.

```
$input-btn-focus-box-shadow: none;
```
removes the box shadow from the input fields, However buttons keep theirs:

```
.btn-primary:focus, .btn-primary.focus {
    box-shadow: 0 0 0 0.2rem rgba(232, 48, 140, .5);
}
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Button box shadows are derived from their background colors.

**Comment by Nael-Saeed** [comment]
Did you find a solution for this? There should be a way to disable btn box-shadow for the entire application
