### ISSUE TITLE
$(el).popover("update") not calling placement method

### ISSUE THREAD

**Issue by adrianstas** [twbs/bootstrap#25692]
Hi. 
From unknown reason the function used for set up popover position is called only once when popover is on showing. After window resize I want again display popoup using my custom placement function, but unfortunately $("el").popover("refresh") not using it

https://codepen.io/gtdc/pen/XZBRQq?editors=1111

scenario:
- click the "click me!" button <- function placement is used
- click the "refresh" button 
     is: placement function **isn't** called out
     should be: placement function **is** called out

Thanks a lot

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by adrianstas** [comment]
@Johann-S I prepared codepen script. Let to know if you need any additional info. thanks,

**Comment by Johann-S** [comment]
Hmm I think we should disable Popper.js auto repositionning when user provide a placement method

**Comment by Johann-S** [comment]
sure

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
