### ISSUE TITLE
Android or if internet connection slow: .modal('show') from $(document).ready does not work after page reload.

### ISSUE THREAD

**Issue by Alex-DE-74** [twbs/bootstrap#25698]
Hello,
I've noticed very strange error on android devices (with chrome).

Using Bootstrap 4 (where window open via service does not work anymore, see my other issues).

Following striped-down code from controller to show the problem:

        $(document).ready(function ()
        //window.onload = function () {  // does not work
        //$(window).on('load', function () // doesnot work
        {
          $scope.getUrlParams();
          if ($scope.confirm.mode == 'confirmation')
          {
            alert("IF TRUE"); // <-- always work
            $('#modalConfirmReg').modal('show'); // <-- does not work after page reload.
          }
        });

This works nearly always on desktop with Chrome & Edge browsers. Sometimes after first reload on chrome and nearly always after first reload on edge browser (this is also strange). It shows alert window and modal form.

But... on Android device it works ONLY on first load - it shows alert window and modal form. But, after reload only alert window pop up, but never the modal form again.

This is reproduceable.

My assumption (from GUI World on Windows) is, the window is hidden, but the object is not removed and is in "shown" state, so it will be not show again?

Sad to say, I don't found the possibility to show errors on android browser :(

Thank you for considering this issue.

**P.S. Additional info: tested website on my older much slower notebook - and see exactly the same issue. So it depends on speed of computer and is a race condition. Now I assume it is really a bug.**

Greetings,
Alex

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Alex-DE-74** [comment]
Ok, I spent a lot of time to stripe down the really big application to a minimalistic example. It can be found here: http://output.jsbin.com/horucat

All versions incuded in this example in a head-section.

Unfortunatelly, this example works as expected also after reload also on android browser, edge & firefox on windows. But this shows exactly, how it done in a real (not always working) application.

But a real application, which is much bigger shows modal only at first load on all browser mentioned abowe. Sometimes it shows only certain continuous reloads again. One exception here is Chrome browser on Windows - here the modal popups correctly Sad to say, currently I can't publish a whole code base for different reasons. P.S. I checked console output and don't even see errors, all seems to be ok.

Thank you!

**Comment by Johann-S** [comment]
Sorry but we cannot work on an un-reproductible bug 😟

**Comment by Alex-DE-74** [comment]
Ok, today I leaved workstation on for test purpose, BUT... my ISP do currently lot ow work on all internet connection, so I'm not sure if all works (at the morning all was ok), i.e. my fix IP6 is already gone :(

Here the link (long because Url is important):
http://challenge.srvdns.de:4200/?test=Z-adg-uagA&mode=Y29uZmlybWF0aW9u&userMail=aW5mYWxhbmRhQGdtYWlsLmNvbQ&contact=SGVyciBPbGl2ZXIgU2NobWl0dA

**Comment by Alex-DE-74** [comment]
The site is currently online.
And I have that currently tested - the bug IS reproductible - depend on browser and internet connection speed  - it does work after reload or not.

**Comment by Alex-DE-74** [comment]
Hello,

the site is since two days online, the bug is reproductible.
Will somebody see it in action?
For securiy reason the site will be deactivated because it is in
development.
Thank you!
Alex

Am 26.02.2018 09:46 schrieb "Johann-S" <notifications@github.com>:

**Comment by patrickhlauke** [comment]
![capture](https://user-images.githubusercontent.com/895831/36909758-ded4a522-1e36-11e8-8f91-8094398b3c42.PNG)

the url you provided never finishes loading its JS scripts, so not really possible to diagnose. i would suggest that your problem, however, is not related to bootstrap (as there's no behavior built into bootstrap that would stop something from working on subsequent page loads). i'd suggest you ask on stackoverflow or similar, as this sounds very much like a problem with your implementation, rather than a bug in bootstrap per se.

https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by Alex-DE-74** [comment]
Follow up - now I'm 99% sure this is a problem with embedded content which
in turn depends on connection speed :(
There are a lot of other mentioned problems if use document.ready together
with ng-include :(((
Sad to say, it's due to not well documented property $includeContentLoaded.
I tried that, but got now fired 4 times, because I have ng-include 4 times,
so need to resolve that problem,
but now it popups :)

Thank you again!

Greetings from Augsburg,
Alex

2018-03-02 18:29 GMT+01:00 Alexander Landa <infalanda@gmail.com>:
