### ISSUE TITLE
Button active and hover look identical

### ISSUE THREAD

**Issue by winterstein** [twbs/bootstrap#25701]
The button active and hover (mouseover) states look exactly the same.

This is confusing, especially if using .active toggle buttons. The user clicks on an active button -- and it switches off, but they see no change, because it's still in :hover and that looks the same.

Suggested fix: Bootstrap 3 had a different appearance for active vs active & hover.

OS: Linux Mint 18.2
Browser: Chrome v64

**Comment by mdo** [comment]
They're slightly different, but close enough on purpose to keep our predefined styles to a minimum. No planned changes here just yet, but you can customize this.
