### ISSUE TITLE
Add CSS styling for datalist elements appearing with .custom-range

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#25707]
custom-range looks great! How about adding styling for datalist elements linked to &lt;input type=range &gt; ? For example, the following HTML code should display range with tick marks:

&lt;label for="datalistRange">Marks&lt;/label>
&lt;input type="range" class="custom-range" min="0" max="5" id="datalistRange" list="marks"&gt;
&lt;datalist id="marks"&gt;
&lt;option value="0"&gt;
&lt;option value="40"&gt;
&lt;option value="60"&gt;
voption value="80"&gt;
&lt;option value="100"&gt;
&lt;/datalist&gt;

Thanks,
Nitin

**Comment by mdo** [comment]
Apparently support is real bad for this, so punting as a won't fix. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by rik702** [comment]
Any chance of re-opening now supported by Safari (as of 12.1)?  Already supported by Chrome and Firefox https://caniuse.com/#feat=datalist
