### ISSUE TITLE
Auto Columns with Images seem to be broken in Chrome

### ISSUE THREAD

**Issue by shawnwildermuth** [twbs/bootstrap#25715]
I'm using Win10 Pro with Chrome (63.0.3239.132), Firefox (59.0b12), Edge (41.16299.248.0). It's working somewhat as expected on all browsers but Chrome. Here's what it looks like in Firefox:

![image](https://user-images.githubusercontent.com/568272/36647376-afa5e2e4-1a52-11e8-8997-f750d494b9fa.png)

And in Chrome it looks like this:

![image](https://user-images.githubusercontent.com/568272/36647380-c0e5d24e-1a52-11e8-9c87-3f3d2917b531.png)

Often in Chrome it doesn't break at all and just shows four columns (depending on image size). I've tried:

- wrapping with div's with col instead of inside the img tags. 
- adding img-fluid or img-responsive

The code that breaks looks like this (not using non-auto columns, works fine):

```
<div class="container">

  <div class="row">
    <img src="http://wilderminds.com/images/logo.png" class="col" />
    <img src="http://wilderminds.com/images/logo.png" class="col" />
    <img src="http://wilderminds.com/images/logo.png" class="col" />
    <img src="http://wilderminds.com/images/logo.png" class="col" />
  </div>

</div>

```
Here is a jsfiddle that shows the problem:

https://jsfiddle.net/x4xnLg8m/8/

Thoughts?

**Comment by chrisbo** [comment]
Hmmm. Never seen `col` used as a class in `img` before. I always wrap e.g.

```
<div class="col">
	<img src="/images/logo.png">
</div>
```

That said. Weird why auto doesn't work. May have something to do with using an inline element instead of a block.

Anyway, I experienced the same problem as you, although, not when I tried wrapped as above.

**Comment by andresgalante** [comment]
`col` has a `flex-grow: 1` so it'll stretch the element when it wraps.

Having said that @chrisbo is right. You should not mix layout classes with elements or components. First define the grid and then put the elements inside:

```html
<div class="row">
  <div class="col">
    <img>
  </div>
</div>
```

also, just a tip: don't autoclose the img tag, it's not valid in HTML5

**Comment by shawnwildermuth** [comment]
Free to close this, this does seem to fix it (it didn't fix it in my larger example, i'll have to figure out why, probably because it's not fitting the images (they're larger) into the column. I didn't think Auto-columns could wrap. I thought the whole idea was to get even columns. In order to prevent the wrapping, I had to tell the images to be img-fluid which makes sense:

https://jsfiddle.net/x4xnLg8m/15/

**Comment by andresgalante** [comment]
if you want not wrap replace col with col-"size"

**Comment by shawnwildermuth** [comment]
That's what I didn't want to do. I was trying to explain auto-columns and my examples weren't working in Chrome, but now that I realize it needs to be on a container, all good.
