### ISSUE TITLE
Spacing with more features

### ISSUE THREAD

**Issue by Moedella** [twbs/bootstrap#25716]
I guess it would be nice to have the spacing based on the screen size or based on the breakpoints. so we can end up with classes mb-xs-3, mt-sm-2 .. etc.

https://getbootstrap.com/docs/4.0/utilities/spacing

**Comment by dushkostanoeski** [comment]
They aren't documented, but they do exist. The issue is with the documentation.

**Comment by Moedella** [comment]
Thansl @dushkostanoeski , You're right
