### ISSUE TITLE
Table CSS is not working in v3 documentation?

### ISSUE THREAD

**Issue by TechFanDan** [twbs/bootstrap#25714]
I am currently looking at the Bootstrap v3 table CSS documentation:
https://getbootstrap.com/docs/3.3/css/#tables

I'm not seeing striping nor do I see hover working in the examples. I've tried in Firefox, Chrome and IE.

I'm trying to figure out why it's not working on my own site and noticed that it possibly doesn't work in the documentation either?

**Comment by patrickhlauke** [comment]
they work fine. they use a subtle shade of grey. it may well be that your particular monitor/calibration is set in a way that makes them indistinguishable from regular white?

**Comment by TechFanDan** [comment]
My bad. I tried on another screen, and indeed, it works.
