### ISSUE TITLE
What if we are using Google Fonts?

### ISSUE THREAD

**Issue by mittalyashu** [twbs/bootstrap#25710]
What if we are using Google Fonts?

```
--font-family-sans-serif: #{inspect($font-family-sans-serif)};
--font-family-monospace: #{inspect($font-family-monospace)};
```

In that we only get this much: `font-family: 'Roboto', sans-serif;`

- Operating system and version: Windows, 10
- Browser and version: Chrome

https://www.useloom.com/share/1e0ac486103140ec99a5f3bcee88b403

I posted a comment on [this issue](https://github.com/sass/sass/issues/2383#issuecomment-363767634)

**Comment by andresgalante** [comment]
If you are using CSS variables, you'll neeed first to import the google font and then set the variable to the name of the font.

Can you send me a codepen that shows the result so I can debug it please?

**Comment by mdo** [comment]
This is a how-to question and not a bug report. @andresgalante is correct that you'd have to change the value manually in our compiled CSS, or in the source Sass variables and recompile.
