### ISSUE TITLE
Split button dropup/ right/ left carets are misaligned

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25718]
Dropdown is OK, but **dropup** / **right** / **left** carets seems to be misaligned.

![image](https://user-images.githubusercontent.com/4065765/36656670-c9b8e63a-1b0c-11e8-8ae4-e4d4de215082.png)

Demo: https://codepen.io/anon/pen/oEapLg

Docs: http://getbootstrap.com/docs/4.0/components/dropdowns/#dropup-variation

**Comment by alecpl** [comment]
All these :after elements should use vertical-align:middle.

**Comment by ysds** [comment]
@alecpl My point is horizontal alignment. Current CSS seems to have lack of alignment overwrite of horizontal direction. I have already created a PR #25719 to fix this.
