### ISSUE TITLE
Display utility affects the [hidden] attribute

### ISSUE THREAD

**Issue by Aristocr2t** [twbs/bootstrap#25729]
I'm using the `[hidden]` attribute. In the Angular, this attribute is used by default. But it doesn`t work with display utility classes. Please find a solution...

![image](https://user-images.githubusercontent.com/15344468/36732238-372d4180-1bde-11e8-8b29-46e6846322f3.png)

**Comment by bkdotcom** [comment]
so you have something like
`<div class="d-lg-block d-none" hidden">am I hidden or not</Nodiv>`
?

Between `.d-lg-block` and `.d-none`, now you know who wins in a fight.

**Comment by Aristocr2t** [comment]
@bkdotcom yes, i have so.

**Comment by mdo** [comment]
The class and attribute selector have the same specificity value—they'll apply in order of usage in your HTML. So if you want it hidden to start, do `d-none d-lg-block` and avoid `hidden` altogether.
