### ISSUE TITLE
Feature Request: Input Group Prepend/Append

### ISSUE THREAD

**Issue by justin-oh** [twbs/bootstrap#25727]
The class names `.input-group-prepend` and `.input-group-append` are misleading in that they imply the element will be positioned according to the verb in that class name. I tried changing the class name expecting the element to be displayed on the other side of the input, but that was not the case. The class names seem to be used merely for styling purposes.

I propose two possible, but mutually exclusive, solutions:

1. Update `.input-group-prepend` and `.input-group-append` so they affect the rendered position of the element.

2. Rename the class names so they are not misleading. (Eg. `.input-group-pre` and `.input-group-post`.)

**Comment by mdo** [comment]
Classes cannot be renamed until a breaking release, so closing as a won't fix. Sorry for any potential confusion!
