### ISSUE TITLE
Incomplete documentation for spacing

### ISSUE THREAD

**Issue by dushkostanoeski** [twbs/bootstrap#25721]
The documentation about spacing doesn't mention that the size mixins can be used as well.

**Comment by mdo** [comment]
Size mixins aren't the same as margin and padding utilities—there's no reason to show them on those pages.

**Comment by dushkostanoeski** [comment]
@mdo my bad, I was thinking of the breakpoints, not the size mixins, It isn't mentioned that you can use `mt-md-2 mt-sm-0` etc. Have a look at #25716
