### ISSUE TITLE
Modal Documentation

### ISSUE THREAD

**Issue by abbyfleming** [twbs/bootstrap#25723]
The [live demo modal](https://v4-alpha.getbootstrap.com/components/modal/#live-demo) code section shows `data-target="#exampleModal"` for the button and `id="myModal"` for the modal itself. To cause less confusion and to work from simply copy/pasting, myModal should be exampleModal. 

I'd be happy to tackle this small change!

![inkedfireshot capture 76 - modal bootstrap_ - https___v4-alpha getbootstrap com__li](https://user-images.githubusercontent.com/22598014/36682553-02db943e-1ae1-11e8-83eb-adc41e308316.jpg)

**Comment by Johann-S** [comment]
You use our old documentation please use our latest see : https://getbootstrap.com/docs/4.0/components/modal/#live-demo
