### ISSUE TITLE
Hiding elements

### ISSUE THREAD

**Issue by Legends** [twbs/bootstrap#25725]
When reporting a bug, include:
Win10 x64, - Tested with Chrome Version 64.0.3282.167 (Official Build) (64-bit)

In this test case I have added a refrence to [Bootstrap 4 css](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css).
[Test case - Code-Pen](https://codepen.io/Legends/pen/RQedXP?editors=1100)

Doesn't hide at all, no matter what screen size.
Example from the [docs](https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements)
```
<div class=".d-none .d-md-block .d-lg-none">.d-none .d-md-block .d-lg-none - Visible only on md</div>
<div class=".d-block .d-sm-none">.d-block .d-sm-none - Visible only on xs</div>
```

**Comment by pesochek** [comment]
You shouldn't be using dots when putting CSS classes in HTML tags attribute. Dots are only used in selectors when writing CSS rules or querying DOM.

**Comment by Legends** [comment]
Oooooo my......, pleaaase delete this issue from the repo, should definitely go to bed earlier...
