### ISSUE TITLE
jquery 3.0.0 does not support by twbs:bootstrap

### ISSUE THREAD

**Issue by deligence-dharmendra** [twbs/bootstrap#25722]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by deligence-dharmendra** [comment]
I have upgrade jquery in my project to jquery 3.0. After upgrade jquery to 3.0, i'm getting console issue.

**Comment by kukac7** [comment]
@deligence-dharmendra what's the issue? what is the code?

https://jsbin.com/cowaboxoci

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by deligence-dharmendra** [comment]
Hi, i'm using twbs:bootstrap@3.3.6,Ubuntu14.4, Chrome, Firefox latest version . Please see the console error in attached snapshot.
![img 20150603 wa0008](https://user-images.githubusercontent.com/32898978/36713885-b3065874-1bb5-11e8-85c1-5053a1332bf5.png)

**Comment by ashoksahoo** [comment]
https://stackoverflow.com/questions/29170799/bootstraps-javascript-requires-jquery-version-1-9-1-or-higher

**Comment by Johann-S** [comment]
@deligence-dharmendra you should update to BS v3.3.7

**Comment by deligence-dharmendra** [comment]
@Johann-S , How, meteor atmospherejs "twbs:bootstrap"  does not provide 3.3.7 version.

**Comment by deligence-dharmendra** [comment]
@Johann-S , if it support, then please provide me installation link
