### ISSUE TITLE
Card image card-img-top bad antialiasing in Safari / MacOS

### ISSUE THREAD

**Issue by TheAccountant1** [twbs/bootstrap#25726]
Hello guys,

I just noticed that images put inside card element with class card-img-top have a problem with antialiasing with Safari. Basically depending on the size of the windows of browser a sort of semi transparent border of 1px is put at the left or the right of the image. 

I suppose it's due to the antialiasing. This issue happens just with Safari. 
![screen shot 2018-02-26 at 11 30 02 pm](https://user-images.githubusercontent.com/36867017/36700547-55e0e17e-1b50-11e8-9621-54dfb24c6029.png)

As you can see from the file attached (it's the right part of a card element with an image) there's a sort of 1px border on the right. Magnifying the border you can notice that's a semi-transparent part of the image. 

Is there any work-around? It's very annoying mostly when you change the background of the card in case of :hover like I do.

Thanks
S

**Comment by mdo** [comment]
You're likely to encounter that in nearly any browser when they render half pixels. Not anything we can do about that unfortunately.
