### ISSUE TITLE
Missing styles from _custom_forms.scss in Bootstrap 4.0.0

### ISSUE THREAD

**Issue by derekws** [twbs/bootstrap#25731]
This one caused me a lot of grief!  It looks like the following two lines are missing in _custom_forms.scss and should be placed on line 179:

-webkit-appearance: none;
-moz-appearance: none;

Strange that they're there in the CDN version.

**Comment by wolfy1339** [comment]
No, they should not be added.
Bootstrap uses Autoprefixer to add vendor prefixes automatically at build time

**Comment by derekws** [comment]
That makes more sense, but I guess the "appearance" property is getting skipped.  Where does the fix need to happen?

**Comment by wolfy1339** [comment]
I just tested `appearance: none;` on [Autoprefixer](https://autoprefixer.github.io/) and it adds both the `-moz-` and `-webkit-` prefix.

**Comment by mdo** [comment]
Closing given @wolfy1339's comments.

**Comment by derekws** [comment]
When I download the most recent version and compile without ANY customizations using Scout, they are not added to .custom-select.  appearance:none; is there, but no -moz- or -webkit- prefixes.

**Comment by wolfy1339** [comment]
You need to add Autoprefixer to your build process. This is not a Bootstrap problem.
