### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by mydappy** [twbs/bootstrap#25739]
my website is not loading properly on opera mini

**Comment by mdo** [comment]
Read the issue template and contributing guideline again and post a new issue when you can share a valid and reproducible bug report. This description isn't helpful enough to debug.

**Comment by mydappy** [comment]
I am not reporting a bug just need help on how i can make my website load properly on opera mini https://scholarshipdraw.com/

**Comment by patrickhlauke** [comment]
this is not the place to ask for general help - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
