### ISSUE TITLE
More compiled css files, for more control

### ISSUE THREAD

**Issue by patrioticcow** [twbs/bootstrap#25733]
Feature request.

bootstrap.min.css is rather large and not all classes are needed, at least not initially. Older versions of bootstrap had a way to only grab what is needed.

Taking this a step further, it can be useful to have css files split per browser. As in, a css file for IE only and one for Chrome only, etc. The browser can be detected before the css files are loaded, and they can be served depending on the browser, making the requests smaller.

**Comment by mdo** [comment]
No plans on doing browser-specific bundles. If you need to customize a bundle, pull down the source files and work with those instead of the compiled CSS.
