### ISSUE TITLE
Migration docs: Says badge are dropped

### ISSUE THREAD

**Issue by henriksjodahl** [twbs/bootstrap#25746]
I was going through the migration from bs3 to bs4 and found that the migration guide says:

> Renamed .label to .tag to disambiguate from the <label> element.
> Dropped the .badge component as it was nearly identical to labels/tags. Use the .tag-pill modifier together with the label component instead for that rounded look.

But according to the documentation Badges still exists and tags do not

https://v4-alpha.getbootstrap.com/migration/#labels-badges-and-tags

**Comment by patrickhlauke** [comment]
shouldn't look at alpha docs. current stable docs are here https://getbootstrap.com/docs/4.0/migration/#labels-and-badges

however you're right, seems that part of the migration doc related to some earlier change, does not reflect what 4.0 does (it removed labels in the end, not badges https://getbootstrap.com/docs/4.0/components/badge/)

**Comment by henriksjodahl** [comment]
Oh I didn't see that I was on the alpha (I blame Google).

**Comment by wolfy1339** [comment]
This problem has been raised may times before where people get the alpha docs instead of the current docs.
Maybe someone should ask google to remove it altogether, and remove those docs too. Redirect them to the current docs saying that Bootstrap is now stable and to use these docs instead

**Comment by patrickhlauke** [comment]
i'd say the onus is on us to signpost the fact that that doc relates to the alpha, and to refer back to the stable docs/release.

however, in substance the problem is the same even on our stable docs. the migration says badges have been removed, when they haven't.

**Comment by patrickhlauke** [comment]
@mdo probably expanding the text beyond "there's a new bootstrap version" and more "this documentation refers to an alpha version of bootstrap. please refer to the latest stable release version..." or something

**Comment by patrickhlauke** [comment]
however, back on main topic: any idea about the badge/label thing?

**Comment by kevdotbadger** [comment]
https://getbootstrap.com/docs/4.0/migration/#labels-and-badges

The example doesn't make sense.

> Renamed .label to .badge to disambiguate from the <label> element.

> **Dropped the .badge component** as it was nearly identical to labels. Use the .badge-pill modifier together with the label component instead for that rounded look.

What was actually dropped? `.badge` clearly wasn't as it goes on the say "use the badge- modifiers".

**Comment by wolfy1339** [comment]
The old badge component from v3 was dropped and labels were renamed to badges

**Comment by mdo** [comment]
Correct. Badges are still in and it needs updating. I’ll fix it up.
