### ISSUE TITLE
Class name of new range control

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25742]
The new range control is defined with `.custom-range` class, but I wonder why it is **CUSTOM**.

The following is a list of bootstrap custom forms:

![image](https://user-images.githubusercontent.com/4065765/36826270-9495db80-1d4f-11e8-8965-79e4ca060a2f.png)

Why not `.from-control-range` or `.form-range` ?

Furthermore, I found `.form-control-range` class in the current SCSS:

https://github.com/twbs/bootstrap/blob/f81f419b22949d2bf0f4d346891be44724109135/scss/_forms.scss#L75-L80

but `.form-control-range` is not documented anywhere.
@mdo Any chance to treat the new range control as a standard or default rather than a custom, and change the class name to `.from-control-range` or `.form-range`?

Thanks.

**Comment by wolfy1339** [comment]
I agree that it should be documented.
As for .custom-range, it's called "custom" because it looks the same across every browser. .form-control extends native styles

**Comment by mdo** [comment]
We should document `.form-control-range` for sure. I thought I did, but clearly missed it :).

**Comment by ysds** [comment]
My doubt was all clear now. Thanks.
