### ISSUE TITLE
Why can't  you develop good touchable carousel ?

### ISSUE THREAD

**Issue by telsanin** [twbs/bootstrap#25741]
Dear bootstrap,
thank you very much for your grat product, but

Why can't  you develop good touchable carousel ?

That's one of the most user user interface element in responsive websites!
Nowadays carousel is used on almost each website and for responsive website it must be touchable!

Thank you very much for answer!

**Comment by Johann-S** [comment]
Related to : https://github.com/twbs/bootstrap/issues/17118

**Comment by rinogo** [comment]
The wording in this Issue is a bit inflammatory/entitled, but the overall message is valid - Bootstrap's carousel really does need to support touch events (e.g. swipe between slides).

**Comment by telsanin** [comment]
I'm sorry for my inflammatory wording. It's just because I'm not native speaker and my English is not as good as I would like it to be.

**Comment by rinogo** [comment]
@telsanin No worries - I figured that was the case! That's why I jumped in to back you up! :)
