### ISSUE TITLE
bootstrap-table limit number rows to  display from mysql table

### ISSUE THREAD

**Issue by bhrochdi** [twbs/bootstrap#25744]
Hello,
I use the bootstrap-table plguin to display data from a mysql DB it works perfectly. However my table-bootstrap does not show anything these last days. I have this error in my web console « **SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data** ».
number rows to displayed : 2348
I use echo **json_encode($data)** to encode the data;
is my code to display the data from bootstap-table:
```
var url = "req.php";
$.get( url, function( data ) {
$.ajaxSetup({async:false});
$.ajaxSetup({ cache: false});
if(data!=null)
{
	$('#table').bootstrapTable('load',data);
	$('#table').bootstrapTable('refresh');
}
else
{
	$('#table').bootstrapTable('destroy'); //Destroy bootstrap table
	$('#table').bootstrapTable();
}
});
```
help me.

**Comment by patrickhlauke** [comment]
as this has nothing to do with bootstrap itself...i'd suggest you ask for help at the appropriate place (presumably https://github.com/wenzhixin/bootstrap-table)
