### ISSUE TITLE
Compiling SASS

### ISSUE THREAD

**Issue by kamov** [twbs/bootstrap#25749]
I am trying to compile sass files by including in my project.

But I get two issue, this:

Error: Undefined mixin '_assert-ascending' in bower/bootstrap/scss/_variables.scss
and
Error: Incompatible units: 'rem' and 'px' in /bower/bootstrap/scss/_variables.scss

In my main.scss I include:

// Import bootstrap from bower_components
@import "../bower/bootstrap/scss/bootstrap";

Thanks

**Comment by wolfy1339** [comment]
This issue is with your code, not Bootstrap's.
You HAVE to use `rem` units, and not pixels

**Comment by mdo** [comment]
Closing per last comment.
