### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#25748]
We have a lot's of unit test, and it's difficult to see which case our units tests covered or not.

We should add a something to see our code coverage

/CC @XhmikosR, @bardiharborow

**Comment by XhmikosR** [comment]
@Johann-S: which solution do you have in your mind? Using nyc?

Generally speaking it's a good idea, so feel free to CC me if you have a working branch.

**Comment by Johann-S** [comment]
Something like this : https://github.com/marketplace/coveralls
