### ISSUE TITLE
img-retina mixin

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#25754]
The `img-retina` mixin is not documented in the docs.
https://github.com/twbs/bootstrap/blob/29f178d89129732d35ae812667709c64cdb28a6f/scss/mixins/_image.scss#L19-L36

Shall we:
- document this
- or remove the mixin (anno 2018 it might be better to use `.svg`s as background images)

**Comment by jessicawhoocna** [comment]
Mixer

**Comment by bastienmoulia** [comment]
Documentation in https://getbootstrap.com/docs/4.0/utilities/ seems good.
SVG is not always good for background images, if it's a picture it's better to have a JPG or PNG.

**Comment by MartijnCuppens** [comment]
@bastienmoulia The `img-retina` mixin is not documented in the v4 docs.

Sometimes you might indeed need jpg background images, but this mixin requires to pass a width and height. I don't know if this technique is still relevant today.

**Comment by MartijnCuppens** [comment]
I'm closing this.
Discussion about mixins documentation here: #25977
Once we have an overview of all the mixins, we can figure out which mixins need to be deprecated in the future.
