### ISSUE TITLE
Size mixin

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#25752]
The `size` mixin is not documented in the docs.
https://github.com/twbs/bootstrap/blob/29f178d89129732d35ae812667709c64cdb28a6f/scss/mixins/_size.scss#L1-L6

Shall we:
- document this
- or remove the mixin (`width` and `height` are not the most complex properties to remember)

**Comment by XhmikosR** [comment]
I think we should drop this, but let's hear @mdo's thoughts too.

**Comment by Kopyov** [comment]
I personally find it very useful, especially in complex SCSS files.

**Comment by kevdotbadger** [comment]
Not sure why anyone would want to drop this?  It's not like it increases build sizes or anything. I find it cleans up the code a bit actually.

**Comment by mdo** [comment]
Yeah, it doesn't hurt anything having it, but it does apparently need documenting.

**Comment by kevdotbadger** [comment]
Hmm, at the moment there's no dedicated place in the documentation for the sass mixins. They are mentioned a couple of times but under their section (i.e. grid and float).

I think we would have add a root level doc for the mixins because I'm not sure it fits anywhere else.

**Comment by MartijnCuppens** [comment]
I'm closing this.
Discussion about mixins documentation here: #25977
Once we have an overview of all the mixins, we can figure out which mixins need to be deprecated in the future.
