### ISSUE TITLE
Dropdown items in <nav> tabs doesn't remove .active

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25759]
Tab JS with `<nav>` and a dropdown cause issue #17371.

![image](https://user-images.githubusercontent.com/4065765/36889563-e27e1eb8-1e3d-11e8-9e6d-fcb40655218f.png)

Demo: https://codepen.io/anon/pen/NyJyBX

But I'm not sure this is a bug or my markup is wrong.

**Comment by ysds** [comment]
It seems that `<ul>` with `dropup`, `dropright` and `dropleft` has the same issue:
https://codepen.io/anon/pen/ddrmNv

**Comment by bkdotcom** [comment]
related
* https://stackoverflow.com/questions/34025624/bootstrap-4-dropdowns-only-work-one-times-with-tabs-menu
* issue #17371 (Dropdown items in nav tabs can get stuck in .active mode)

**Comment by brettalton** [comment]
This is happening to me as well and seems to only occur when you edit the HTML/CSS to a non-standard format, such as using nested divs and columns.

My codepen on the issue: https://codepen.io/anon/pen/oqMwGw

You should see one lime green box, and then two more as you click the navigation.

**Comment by iatek** [comment]
@ysds in your Codepen example, `.dropdown` seems to work correctly. It's the other up, right and left variations that are not working.

**Comment by ysds** [comment]
Closing this because:

> Note that dynamic tabbed interfaces should not contain dropdown menus, as this causes both usability and accessibility issues.

https://getbootstrap.com/docs/4.1/components/navs/#javascript-behavior

**Comment by mritunjayr** [comment]
Hi,
I am still facing issue with dropright. it is not removing .active class. it should be fixed.
