### ISSUE TITLE
Comparison on version bugs 

### ISSUE THREAD

**Issue by blachawk** [twbs/bootstrap#25753]
Hello,
I'm looking for a resource that can show me the "number" of official outstanding bugs that still need resolution in the new official Bootstrap 4 release, vs the number of bugs that were still outstanding in Bootstrap 3.3.6.  If any of the administrators of Bootstrap happen to know that information off the top of their heads, then that works as well.

I am new to seeking this type of information.  Thanks for any guidance!

**Comment by mdo** [comment]
Sorry, we don't track that. You can find some bugs for v3 with that label in our issues, but we haven't used it through the life of v3.
