### ISSUE TITLE
[npm] Failing to install required dependencies

### ISSUE THREAD

**Issue by lspoor** [twbs/bootstrap#25768]
I'm experiencing the following error:
<img width="682" alt="screen shot 2018-03-02 at 22 50 05" src="https://user-images.githubusercontent.com/1685176/36925743-3532c432-1e6c-11e8-81d9-87e5e1e7723a.png">

The following steps I have taken are as follows..

1. Create an empty directory and cd into it via Terminal
2. Run `npm init -y`
3. Run `npm install bootstrap`

Then I receive the error above.

NPM - v3.10.10
NodeJS - v6.11.2
macOS High Sierra v10.13

**Comment by wolfy1339** [comment]
That is a completely normal error.
You have to add jQuery and Popper.js to your dependencies in `package.json`
