### ISSUE TITLE
Responsive 'show' classes for collapsible items

### ISSUE THREAD

**Issue by drdogbot7** [twbs/bootstrap#25765]
It would be useful to be able to set the initial state of collapsible items at different breakpoints using css classes.  e.g.  `.show-md`, `.show-lg`.

```
<p>
  <a data-toggle="collapse" href="#collapseExample" role="button">
    toggle button
  </a>
</p>
<div class="collapse show-md" id="collapseExample">
   shown by default at 'md' breakpoint and up.
</div>
```

**Comment by bkdotcom** [comment]
any luck with the display utilities?
http://getbootstrap.com/docs/4.0/utilities/display/

**Comment by mdo** [comment]
Display utils would override entirely. I'm unsure how we'd do this other than it wouldn't be a `show-md` so much as a `collapse-md`. That becomes the opposite behavior of our navbar's _expand_ behavior then, too, which is built on collapse :).

**Comment by mdo** [comment]
Closing as stale
