### ISSUE TITLE
Floating-Labels only works with "for" and "Input-ID" :-( 

### ISSUE THREAD

**Issue by rranke** [twbs/bootstrap#25764]
https://getbootstrap.com/docs/4.0/examples/floating-labels/

First of all... providing "floating-labels" -> nice done!!!!

But i have a question:
Why is it implemented in that way, that it does only work correctly, if the "ID-attribute" for the input-field is the same as the "FOR-attribute" of the label?

Is there a way to make it work without the need for setting an ID?
I think it would be much simpler to make it work indirectly, having a ```<input>``` nested inside of an ```<label>``` like so:

```html
<div class="form-label-group">
    <label>Email address
        <input class="form-control" placeholder="Email address">
    </label>
</div>
```

I am currently working on an project where i have many input-fields, multiple forms and i have to do some cloning and so on and it gets really stressful, because i have to think about setting unique IDs for all the fields :..(

**Comment by bkdotcom** [comment]
please provide a "working" example of it it not working  (jsbin or codepen, etc)

**Comment by rranke** [comment]
https://codepen.io/anon/pen/KQYppq

Thanks, but that all sounds a bit like a "dirty-hack-solution" - which is what i do not want to do ;)
All i want is a nice and easy solution that i do not have to set any IDs.

Would it be a big problem, if the "floating-labels"-feature gets implemented that it works "automagically" without setting any IDs? So it could check if "input" and "label" is inside of "form-label-group", then "floating-labels"-feature works :-) ?

````html
      <div class="form-label-group">
        <input class="form-control" placeholder="aaa">
        <label>does currently not work, but should work automagically</label>
      </div>
````

**Comment by bkdotcom** [comment]
not sure if you saw my last edit, but
```css
label:not([for]) {
  pointer-events:none;
```
does the trick

**Comment by rranke** [comment]
yes, wow, that works!
my first tests are working with your solution!
nice :-) 

thanks, an have a nice friday night!
