### ISSUE TITLE
Feature Request: Floating Labels for Textarea and Input-Group

### ISSUE THREAD

**Issue by rranke** [twbs/bootstrap#25767]
**Feature Request**
 
Floating Labels (https://getbootstrap.com/docs/4.0/examples/floating-labels/) for:
- Textarea
- Input-Group in combination with Buttons with dropdowns (https://getbootstrap.com/docs/4.0/components/input-group/#buttons-with-dropdowns)

Thanks

**Comment by mdo** [comment]
Given how it's built, not going to happen right now. No plans to expand this out to additional input types given it's an experimental example.

**Comment by appel** [comment]
Sorry to reopen this, but I ran into the same issue and may have fixed at least the input-group-append part of it. So I figured I'd share [my attempt at a partial fix](https://codepen.io/appel/pen/zYrZpXQ) for whoever might be interested.
