### ISSUE TITLE
Documentation for v4 no longer gives info on browser support

### ISSUE THREAD

**Issue by jwatt** [twbs/bootstrap#25762]
There is browser support info for v3.3:

https://getbootstrap.com/docs/3.3/getting-started/#support

It would be helpful if the docs for v4 also detailed what browsers and versions should work.

**Comment by fchiumeo** [comment]
https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/ ?

**Comment by jwatt** [comment]
Ugh. Sorry for the noise!
