### ISSUE TITLE
Cursor appears outside of input on mobile

### ISSUE THREAD

**Issue by bluenike** [twbs/bootstrap#25777]
* I created a page with a modal popup
* After triggering the popup, I click into the first input.
* The mobile keyboard appears and the view is slightly scrolled to adjust for the keyboard.
* The cursor appears outside of the input (by approximately or exactly the amount the view was adjusted for the keyboard).

Bug confirmed on:
* iPhone X
* Safari or Chrome 64

![image-1](https://user-images.githubusercontent.com/8681536/36941539-896d9170-1f12-11e8-95ae-fb69eb549e58.jpg)

**Comment by patrickhlauke** [comment]
iOS webkit bug, it seems...

**Comment by mdo** [comment]
Duplicate of #24352
