### ISSUE TITLE
Alignment of cards inside card-columns

### ISSUE THREAD

**Issue by dana86** [twbs/bootstrap#25778]
I have a slight issue with the logic of card alignment within .card-columns. I use latest Bootstrap and CSS only. My issue is that the last card in my example aligns to the right instead of the left on large screen. 

I'd have thought that the last card would align in the left column since it's shorter than column on the right. Is there a way to fix this?

EDIT: I'm using latest Firefox and Chrome, both display it the same way.

[Screenshot here](https://i.imgur.com/kl9xA5q.png) 
[JSFiddle here](https://jsfiddle.net/rggy50rm/7/)

Any help will be appreciated! If there is another way I can do this in Bootstrap, I'll be happy to learn (just please don't suggest Masonry and similar scripts). Thank you!

**Comment by mdo** [comment]
You can try forcing the columns to break (see https://developer.mozilla.org/en-US/docs/Web/CSS/break-after), but CSS columns are a little funky. If you need a bit more control, I'd suggest using the grid system.
