### ISSUE TITLE
Responsive Table not working with variable width columns

### ISSUE THREAD

**Issue by Nickno95** [twbs/bootstrap#25786]
When using auto width columns and variable width columns, a responsive table breaks the layout.

Example JSFiddle: https://jsfiddle.net/Nickno/px573g8x/8/

**Comment by asyncdesign** [comment]
It's the table cell content width that stops the columns from shrinking - it's difficult to make a truly responsive html table. To do so, the table would have to be transformed into some other type of layout.

**Comment by Nickno95** [comment]
That is what the responsive-table wrapping div is for; it makes the table scroll in it's column. See  The correct layout for the example should be the blue column is the width of its contents, the green column is the width of its contents, and the table's column should be the remaining horizontal space for the row. This works correctly when defining specifying the columns: https://jsfiddle.net/Nickno/b3m3pusb/ ; but not when having autowidth and variable width columns in the first example.

**Comment by theZieger** [comment]
I don't think that the behaviour you are looking for can be achieved with the bootstrap grid or with flexbox in general. The overall problem here is that the column of the table will grow until 100% of the rows width.

To achieve a working layout you would have to set explicit column widths like you did here: https://jsfiddle.net/Nickno/px573g8x/8/

At least I don't see any kind of "flexbox magic" that would let you define three auto-width columns where one would have an block-level child which could grow to any width and the layout would work at any scenario.

**Comment by Nickno95** [comment]
After playing around with it for a while, I managed to find a fix. By styling the parent col (the auto width one) with "overflow-x:auto", it makes any responsive tables in it work correctly.

JS Fiddle: https://jsfiddle.net/Nickno/4o6m9cqg/4/

**Comment by mdo** [comment]
Thinking we should close this as a won't fix—we shouldn't go adding `overflow` properties to our columns unnecessarily. Feel like it'd be asking for issues with positioning, cropped content, and more.

**Comment by ysds** [comment]
Closing per last comment.
