### ISSUE TITLE
Popover auto placement does not recognize edge of parent window from within iFrame

### ISSUE THREAD

**Issue by ss-coder** [twbs/bootstrap#25780]
I have been using Bootstrap's Popover with (data-placement="auto left") so that it will dynamically reorient the popover when it nears the edge of the window. This works great!

However, when the Popover is in an iFrame it does recognize the edges of the parent window and will get cut-off by the parent window. If the Popover is still within the boundary of the iFrame, it does not realize that it has passed the boundary of the main window.

Attached are 2 screen shot showing the same Popover in a normal window and then in a framed window. You can see, by example, how the same Popover gets cut-off while in the iFrame, even though it still has (data-placement="auto left").

Does anyone have a solution to fix this bug? Thank you!

![popover in framed window](https://user-images.githubusercontent.com/37033657/36952654-9e59841c-1fc7-11e8-8581-9755abbaaa31.gif)

![popover in normal window](https://user-images.githubusercontent.com/37033657/36952650-8a251ee8-1fc7-11e8-8160-9d98470142c8.gif)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by ss-coder** [comment]
Hello... as requested I created test case via CodePen. I am using Bootstrap v3.3.7 and this error happens on any browser PC or MAC. Here is the test link:
https://s.codepen.io/ss_coder/debug/GQVQVV/PBrNWxJWvmVA

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by ss-coder** [comment]
Hello... as requested I created test case via CodePen. I am using Bootstrap v3.3.7 and this error happens on any browser 
PC or MAC. Here is the test link:

https://s.codepen.io/ss_coder/debug/GQVQVV/PBrNWxJWvmVA

I was not sure if you wanted me to reply here in this email, or add a comment to the thread? So I did both.

Thank you!
