### ISSUE TITLE
Back to top button - scroll website to the top

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#25787]
I did a lot of projects on BS3, today I started testing BS4 and still I don't see special button to scroll whole page to the top of them.

I think that today it is standard in mobile friendly website, so I think that it could be great idea to add extra special button with JS/jQuery smooth scroll to the top.

**Comment by mdo** [comment]
Cmd/Ctrl Up or Page Up.

**Comment by inwardmovement** [comment]
I think indeed a "back to top" button would be relevant in a "mobile-first" framework like Bootstrap, for version 5 maybe? It makes sense from a UX point of view and its a pretty usual component.

We could take inspiration from the one on the [Google Fonts website](https://fonts.google.com/) which is pretty clean/neutral/straightforward:

![image](https://user-images.githubusercontent.com/9438102/77224190-680f7800-6b63-11ea-9c89-59692faa76ec.png)
