### ISSUE TITLE
Animated hamburger button

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#25788]
My next idea is create an animation for hamburger button for example change from strips to X (I could do it in BS3, but in BS4 is a svg which I can't change).

You can add choice for user which button wants to use (normal or animated)

**Comment by browner12** [comment]
you can use whatever you want for the icon. simply change

```html
<span class="navbar-toggler-icon"></span>
```

to something else.

**Comment by SkuterPL** [comment]
I know that and already I did it, but I think that as option it would be good for newer users of Bootstrap. They wouldn't be able to have to write extra CSS code for that.

**Comment by browner12** [comment]
BS can't be everything to everyone.  But if you really want it, send a PR.

**Comment by mdo** [comment]
Thanks, but we'll pass.
