### ISSUE TITLE
grid system not working properly

### ISSUE THREAD

**Issue by kudchikarsk** [twbs/bootstrap#25796]
```

<div class="container">
<div class="row">
  <div class="col col-md-8">
  </div>
  <div class="col col-md-4">
  </div>
</div>
</div>

```
col-md-4 is not breaking columns in two, when browser size is less than 768px in some pages,

The live page where its not working is [here](https://kudchikarsk.github.io/multithreading-in-c-sharp/threads-in-c-sharp-overview.html)

The page where its working is [here](https://kudchikarsk.github.io/multithreading-in-c-sharp/getting-started-with-thread-class-in-c-sharp.html)

**Comment by lucastavaresjd** [comment]
use brackpoint col-sm
col-md is for pc 

https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by browner12** [comment]
Welcome to Bootstrap! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general use issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Bootstrap Slack (http://bootstrap-slack.herokuapp.com/)
StackOverflow (https://stackoverflow.com/questions/tagged/twitter-bootstrap)

Thanks!

**Comment by patrickhlauke** [comment]
what @browner12 said :)

see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by kudchikarsk** [comment]
Ok issue is sorted though thanks, @lucastavaresjd

**Comment by Pelesibt** [comment]
How did you tackle this issue?

**Comment by kudchikarsk** [comment]
> use brackpoint col-sm
> col-md is for pc
> 
> https://getbootstrap.com/docs/4.0/layout/grid/

Try this

**Comment by Pelesibt** [comment]
You mean breakpoint or brakpoint? Can I see how you applied it to your problem above?

<div class="container">
<div class="row">
  <div class="col col-md-8">
  </div>
  <div class="col col-md-4">
  </div>
</div>
</div>

Thanks.

**Comment by Pelesibt** [comment]
Applied breakpoint both ways, not sure if this is what you're referring to?:
<div class="container">
	<div class="row">
		<div class="col-sm-6">aa</div>
		<div class="col-sm-6">aa</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col">aa</div>
		<div class="col">aa</div>
	</div>
</div>
