### ISSUE TITLE
mouse click is not working with IE for bootstrap typeahaed.js

### ISSUE THREAD

**Issue by sumakuni** [twbs/bootstrap#25792]
I have an issue with the bootstrap typeahead.js in IE.the mouse click event is not firing when i select with the mouse.This is happening only in IE working fine with chrome. This is my code for the typeahaed
 var init = function () {
        $(document).ready(function () {
            var $input = $(".textbox");
            var apiURLData = Urls.ByNameSearch + "?query=";
            $input.typeahead({
                source: function (query, process) {
                    if ($.trim(query).length >= typeAheadSettings.minLength) {
                        return search(apiURLData + $.trim(query)).done(function (data, textStatus, jqXHR) {
                            var resultList = data.map(function (item) {
                                var aItem = { id: item.Id, name: item.Name };
                                return (aItem);
                            });
                            return process(resultList);
                        });
                    }
                }
                , minLength: typeAheadSettings.minLength
                , items: typeAheadSettings.itemsToShowInDropDown
                , displayText: function (item) {
                    return item.name;
                }
                , scrollHeight: typeAheadSettings.scrollHeight
                , updater: function (item) {
                    $("#Id").val(item.id);
                    $("#Name").val(item.name);
       
                    return item;
                }
                , matcher: function (item) {
                    return typeAheadSettings.typeAheadCustomMatcher(this, item);
                }
                , highlighter: function (item) {
                    return typeAheadSettings.typeAheadCustomHighlighter(this, item);
                }
            });
            hideMessges();
        });
        selectedLocations = [];
    };//Ends Init

    var onTextBoxChanged = function (txtBox) {
        var current = $(txtBox).typeahead("getActive");
        if (current) {
            if (current.name !== $(txtBox).val()) {
                $("#Id").val("");
                $("#Name").val("");
           }         
                    }
                }             });
            hideMessges();
        });
        selectedLocations = [];
    };//Ends Init

**Comment by mdo** [comment]
This isn't where typeahead is developed.
