### ISSUE TITLE
Validator - get notification from JS API

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#25791]
I can see that in BS4 you use HTML5 validation, but we have to write own notification for valid and invalid classes, maybe you could add option to get this communicate automatically from API? It is good for different language website, because when someone enter on my website from other country, she/he will see text in her/him language.

**Comment by mdo** [comment]
No plans to build JS to interface with the API—that's entirely dependent on your setup beyond what we can assume in Bootstrap.
