### ISSUE TITLE
Labels for checkboxes & radio buttons don't align properly (vertically) using Bootstrap Reboot

### ISSUE THREAD

**Issue by hisyam** [twbs/bootstrap#25794]
![bootstrap4 reboot forms](https://user-images.githubusercontent.com/31984069/37019348-f7d7e326-2152-11e8-89fa-6ead679acb96.png)

Using Bootstrap Reboot the labels for either checkboxes or radio buttons don't align vertically properly with the elements.

Example code:

```
<form>
  <fieldset>
    <div>
      <label>
        <input type="checkbox" value="" />
        Check this checkbox
      </label>
    </div>
    <div>
      <label>
        <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="" />
        Option one is this and that
      </label>
      <label>
        <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2" />
        Option two is something else that's also super long to demonstrate the wrapping of these fancy form controls.
      </label>
      <label>
        <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3" disabled="" />
        Option three is disabled
      </label>
    </div>
  </fieldset>
</form>
```

Tested on 
- Chrome 64.0.3282.186 (Official Build) (64-bit)
- macOS 10.12.6
---
EDIT:
I think it's better to align the labels to the middle of the checkbox/radio button?

![bs_reboot_align](https://user-images.githubusercontent.com/31984069/38189224-af27255c-3691-11e8-9cf9-52184a1f8418.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by hisyam** [comment]
Codepen demo: [https://codepen.io/anon/pen/NYKevX](https://codepen.io/anon/pen/NYKevX)

Tested on :
Bootstrap Reboot v4.0.0
Chrome 65.0.3325.146 (Official Build) (64-bit)
macOS 10.12.6

**Comment by GEMI** [comment]
Demo: https://getbootstrap.com/docs/4.0/components/forms/#default-stacked

Tested on:
Bootstrap v4.0.0
Chrome 65.0.3325.162 (64-bit)
macOS 10.13.2

**Comment by pamtbaau** [comment]
Demo: [https://codepen.io/anon/pen/oyypKQ?editors=1100](https://codepen.io/anon/pen/oyypKQ?editors=1100)

Tested on:
Bootstrap v4.1
Chrome: 67.0.3396.87
Windows 10

Vertical alignment fixed using:
```
.form-check {
  display: flex;
  align-items: center;
}

.form-check-input {
    margin-top: 0;
}
```

**Comment by mdo** [comment]
This looks like a Chrome bug. Take a look at the attached screenshot—you'll see the default radio input is sitting outside it's bounding box by 1-2px. I can't fix that for all browsers without adverse affects in another browser unfortunately.

<img width="421" alt="screen shot 2018-09-16 at 6 34 17 pm" src="https://user-images.githubusercontent.com/98681/45603258-41f1a080-b9df-11e8-898f-f5d88b793be0.png">

**Comment by GEMI** [comment]
This is not Chrome only issue. The same thing is happening on Firefox 61.0.2
![screenshot 2018-09-17 09 06 20](https://user-images.githubusercontent.com/769500/45608041-0bf10280-ba59-11e8-9862-c6acee84ccb7.png)

**Comment by kgeographer** [comment]
You can override the .form-check-input class with a margin-top value that work for your font.

**Comment by MR-T77** [comment]
So, the easiest way to solve this is downgrade to Bootstrap 3.?
