### ISSUE TITLE
Navbar with dropdown create ugly offset

### ISSUE THREAD

**Issue by danieluyo** [twbs/bootstrap#25798]
When use navbar with dropdown this generate offset
https://output.jsbin.com/vumubok
![captura de pantalla 2018-03-06 a la s 14 06 34](https://user-images.githubusercontent.com/17558554/37055541-9e66ce20-2147-11e8-8630-60a175f5c20e.png)

Bootstrap 4.0
Popper.js 1.12.9

**Comment by fchiumeo** [comment]
https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment

**Comment by mdo** [comment]
Yup, please change the alignment manually.
