### ISSUE TITLE
Please explain the point of having to set and map colour variables and which I should be using

### ISSUE THREAD

**Issue by IvaWonderbush** [twbs/bootstrap#25795]
Maybe I've just not had an issue where both of these options are necessary, but I don't see the point in setting colour variables to then map them to the `$colors` array moments later. Why not just set the colour directly in the array? Then again, why is there even a `$colors` array?

Can someone explain the use, because I just don't get it. When should I be using `$primary` or `theme-color("primary")`, and if I should always be using one, why define the other?

I feel as if the only reason I should be using the `theme-color()` and `color()` functions instead of the variables directly is because.. they exist.. But I just can't seem to figure out _why_ they exist.

My apologies if this has been explained elsewhere, I could not find it.

**Comment by mdo** [comment]
Use Sass maps when you need to loop over a series of key-value pairs to generate a family of classes vs a one-off class. For example: our buttons are generated with the Sass map. If you're adding custom CSS, you might just need a variable. Purely there for options based on how you write Sass/CSS.

Some more of this is covered in [our Theming docs](https://getbootstrap.com/docs/4.0/getting-started/theming/).

**Comment by IvaWonderbush** [comment]
So shouldn't the defined variables in the variables.scss use `$primary` instead of `theme-color("primary")`?

For example: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L151
