### ISSUE TITLE
nav-item dropdown stretching navbar on smaller screens

### ISSUE THREAD

**Issue by MargateSteve** [twbs/bootstrap#25797]
Not sure if this an issue, feature request or something I am missing. 

I want a fairly simple navbar with the main menu items to the left in a .navbar-collapse, but on the right a separate .nav-item dropdown that is always visible (it will hold a login/logout form). 

On larger screens it works fine, but once the collapse has kicked in, although the trigger still displays fine, the dropdown pushes the whole navbar down. I want it to work exactly the same as it does on larger screens. 

It seems a fairly common thing that people may want to utilise and googling did turn up a few instances of the same or similar question, but the best solution I saw was a hugely complicated structure and a host of extra css.  I do not think it is browser specific but have tried it in Chrome 64 and FF 54 with the same results.

[jsfiddle](https://jsfiddle.net/58m1somf/3/)

![image](https://user-images.githubusercontent.com/13920439/37043658-1d39836c-2159-11e8-9b8b-5feb6a15e1cb.png)
![image](https://user-images.githubusercontent.com/13920439/37043677-2ddb2112-2159-11e8-96ba-0e2372d2dc88.png)

**Comment by bakedbird** [comment]
What you are trying to do can be easily achieved with bs4. The problem lies in your markup.
Please see this [fiddle](https://jsfiddle.net/12sgrj6a/4/) for a working -but not perfect- example.

**Comment by MargateSteve** [comment]
Thanks @bakedbird 

It wan't quite there as the right trigger was dropping but a bit of tweaking has got it nearly there as per this [Fiddle](https://jsfiddle.net/12sgrj6a/9/), albeit I think it hacky as I simply moved the right trigger to before the nav button in the code. The only thing is it appears dropdown-menu-right is not working but that may work locally as I can see no reason it wouldn't.

**Comment by mdo** [comment]
Right-aligned dropdown menus appear to work as intended in the latest release. Sorry for getting to this so late, but I think it's safe to close out.
