### ISSUE TITLE
Change suggestion: Add padding to the column when using make-col() mixin.

### ISSUE THREAD

**Issue by GramozKrasniqi** [twbs/bootstrap#25793]
Change suggestion: Add padding to the column when using make-col() mixin.

**make-col($size)** it is not adding right & left padding.
If you use the col classes e.g .col-$infix-$size it will add it (extended from %grid-column)

```
@mixin make-grid-columns($columns: $grid-columns, $gutter: $grid-gutter-width, $breakpoints: $grid-breakpoints) {
  // Common properties for all breakpoints
  %grid-column {
    position: relative;
    width: 100%;
    min-height: 1px; // Prevent columns from collapsing when empty
    padding-right: ($gutter / 2);
    padding-left: ($gutter / 2);
  }
```

Then the other variant, when using make-col-ready() mixin it will add it directly.

```
@mixin make-col-ready() {
  position: relative;
  // Prevent columns from becoming too narrow when at smaller grid tiers by
  // always setting `width: 100%;`. This works because we use `flex` values
  // later on to override this initial width.
  width: 100%;
  min-height: 1px; // Prevent collapsing
  padding-right: ($grid-gutter-width / 2);
  padding-left: ($grid-gutter-width / 2);
}
```

I think it is a time saver if implemented and adds consistency on how the columns behave.

Is there any reason why this thing was left out?

**Comment by mdo** [comment]
It's separate for generating our responsive classes—see our `_grid-framework.scss` file for how it's all put together.

**Comment by GramozKrasniqi** [comment]
@mdo yes i know but that means when using the mixin directly you will not have padding.

And as i know many people including me are trying to use these mixins (avoid classes) to get cleaner HTML.
**make-grid-columns** is used by bootstrap internally and dosent help in this case unless you use column class names.

p.s thank you for editing my post
