### ISSUE TITLE
Nested .btn-group doesn't inherit .btn-group-[size]

### ISSUE THREAD

**Issue by quasipickle** [twbs/bootstrap#25800]
When one adds a dropdown to a button group, one must wrap it in .btn-group as documented here: https://getbootstrap.com/docs/4.0/components/button-group/#nesting.

However, when applying `.btn-group-sm` to the outer button group, the dropdown button inside the inner button group don't inherit the size set by the outer button group.

An example case is here: https://codepen.io/anon/pen/qxeqJK  Both buttons should be the small size.

Looking at the SCSS file, the rule selector is `.btn-group-sm>.btn, .btn-sm`.  I'm not certain why the `>` needs to be there - I can't picture a use case where I'd set a size on an outer button group, and not have it cascade to any inner button groups.

I doubt this is a browser quirk, but nonetheless my OS is Win 10, and this is appearing on both Firefox and Chrome.

**Comment by mdo** [comment]
Most nested components won't do this, and we wouldn't want to do it here either. Consider you might have a `.btn-group-sm` with a dropdown and a `.btn-group` within—should that be automatically small, or the normal sized? Too much uncertainty from what we can know about your project to make that call for everyone.

**Comment by quasipickle** [comment]
> Consider you might have a .btn-group-sm with a dropdown and a .btn-group within—should that be automatically small, or the normal sized?

That was the point I made too.  It should be automatically small. I can't think of any situation where I would have a button group within a button group, and NOT want it to be the same size.  What possible reason could there be for that?

**Comment by mdo** [comment]
> I can't think of any situation where I would have a button group within a button group, and NOT want it to be the same size. What possible reason could there be for that?

Expand your thinking to include projects and approaches that differ from your own :). While you can't think of a situation where you'd want that, I can, and so could other folks. I see it from both ends, but I'd always defer to opting into that kind of behavior.

**Comment by quasipickle** [comment]
So you think there are more people who would want the result displayed in the Codepen, than would want them to look the same size? I continue to respectfully disagree.

If I've got a group of 5 buttons and I set the group to be small, all the buttons will look small.  If I add a dropdown - which is really a dropdown by name only, visually it's a button - it won't look the same.  Stuff that looks the same should behave the same I think.

Of course you're not required to give me an example, but I would appreciate one where, in a button group, one would want buttons of different sizes - and sizing the buttons separately won't work.  An esoteric use case seems plausible, but not one that is more common than - "I've got a group of buttons here, I'd like them all sized the same, so let's add a class to the group".

**Comment by ysds** [comment]
The simple reason is for support [menu forms](http://getbootstrap.com/docs/4.0/components/dropdowns/#menu-forms).
No one wants to affect the size of the "sign-in" button.

**Comment by mdo** [comment]
I misread your CodePen originally—I see what you mean, but I also stand by the lack of automatic inheritance of those parent classes. For example, in this example I don't want the nested button group to be large (or small): https://codepen.io/anon/pen/RQXVoY.

**Comment by quasipickle** [comment]
Ah, I see.  I think ideally the sizing would cascade to immediate children like:
```
.btn-group-sm .btn,
.btn-group-sm > .btn-group .btn,
.btn-sm
```
but no further.

Or alternatively, just apply the proper styles to `.dropdown` when in `.btn-group`, instead of re-using `.btn-group`.

**Comment by mdo** [comment]
What if your markup is nested within another wrapping element? Limiting to immediate children like that further limits the effectiveness of the code.

**Comment by quasipickle** [comment]
Fair point.  This may be why you author the world's most popular UI framework and I do not.
