### ISSUE TITLE
BS4 popover dynamic content (image)

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#25801]
I tried doing a codepen for this problem, but I can't reproduce it there (likely because of how it needs to work in our system vs a simple example).

I have a table with a list of stuff in it, the first column in the table is a camera which when you hover over is supposed to show the image for the product.

I have the data-toggle set to "popover" and data-content for each camera set to basically do: img src="get_image.p?serial_no=1234"

I then have a $('[data-toggle="popover"]).popover({ html: true, trigger: 'hover' }), however when I hover over the camera, the popover is all screwed up, it isn't aligned properly with the arrow or the popover itself, and the popover isn't wide enough to fit the image.

If I move the mouse away and then back onto the same camera, the popover is aligned perfectly however it still isn't wide enough for the image.

Normally I use tooltipster, I find it better than popper.js (more configurable, etc...) and to fix it there I would set a 'width' on the image since the image isn't loaded until the moment you hover over the camera.

Wish I could do up a codepen, but as said, I'm guessing my case is very unique and I can't recreate it easily enough (I tried, but it doesn't have the same issue, likely because all the images I tried to use are regular files and not stored in a database).

**Comment by ray73864** [comment]
ok, managed to get a working example. Not sure if i'm doing this codepen thing properly or not, but:

https://codepen.io/anon/pen/EQqwMQ

It's the black camera you want to hover over.

**Comment by ray73864** [comment]
OK, never mind, I should learn to look closer (having a cold doesn't help I guess), in my older BS3 ones I used the class 'img-responsive' on the image tag, looks like I just had to change 'img-responsive' to 'img-fluid' and it all works.

**Comment by ray73864** [comment]
Though it still has an alignment issue on first showing it, if I mouse away and back over the alignment issue is resolved.

I may just give up and go back to tooltipster, would rather not but i'm just not liking popper at this present stage.

**Comment by Johann-S** [comment]
Hi I would like to give a look at your CodePen but no Popover is shown on hover because you didn't set any content, can you update your CodePen ?

**Comment by ray73864** [comment]
I did have earlier, but I removed the image because it pointed to a sensitive area, will have to update it later with a better example.

For now I have gone back to tooltipster where all I had to do to make it work there was set a CSS width.

**Comment by Johann-S** [comment]
Ok but can you update you codepen with a random image ? It'll allow us to work on your issue

**Comment by ray73864** [comment]
Replacement codepen (Apparently I don't know how to codepen...).

I just chose a random image off of Google Images, unfortunately it doesn't exhibit the same behaviour that I am seeing.

https://codepen.io/anon/pen/aqeQgr

**Comment by Johann-S** [comment]
Hmm ok, but it doesn't help us 😟 

Maybe you can add a delay to let time to your browser to download your image.
See: https://getbootstrap.com/docs/4.0/components/popovers/#options

**Comment by ray73864** [comment]
Ok, done a new codepen, created a test file on our server that only pulls up that one image. 

https://codepen.io/anon/pen/NyQoLP

When you hover over the bottom camera, the image appears too low with the arrow at the top of the popover, when you mouse away and then back on it again, it all works fine.

Have also added the class="img-fluid" to each one which fixes the width problem.

**Comment by Johann-S** [comment]
a solution for your issue would be to bind the load of your image and when it's done calling the update method of our popover plugin see: https://getbootstrap.com/docs/4.0/components/popovers/#popoverupdate
