### ISSUE TITLE
Form Row - Margin Bottom

### ISSUE THREAD

**Issue by dday9** [twbs/bootstrap#25804]
As per the documentation for [Form Grids](https://getbootstrap.com/docs/4.0/components/forms/#form-grid), it is recommended to use the following:
```
<form>
  <div class="row">
    <div class="col">...</div>
    <div class="col">...</div>
  </div>
</form>
```
However, the margin-bottom for an element that contains the class attribute _row_ is 0 and the margin-bottom for an element that contains the class attribute _form-group_ is 1REM. Because of this difference, I propose changing the documentation to:
```
<form>
  <div class="form-group row">
    <div class="col">...</div>
    <div class="col">...</div>
  </div>
</form>
```
As to demonstrate consistent behavior regarding the margin-bottom attribute.

**Comment by dday9** [comment]
I apologize for the delayed response. To clarify, I opened the ticket it to point out that there is a lack of consistency with regards to the documentation. I think that it would benefit users who're following the documentation from the _Form Grid_ section to include the `form-group` class in all of the examples. Doing this will provide the same behavior with regards to the margin-bottom attribute that is used throughout most of the other examples.

In fact, after re-reading the documentation, the inclusion of the `form-group` class is used in the second example of the _Form Row_ as well as the examples in the _Horizontal Form_ section. It is just not being used in neither the example found in the _Form Grid_ section nor the first example in the _Form Row_ section.

**Comment by mdo** [comment]
I see what you mean now, but the `.form-group` class isn't required in either of these situations for a single input without a label. It's not demonstrating the `.from-group` class, it's demonstrating the form row and column classes. For now, closing as a won't fix.
