### ISSUE TITLE
Clarify docs of breakpoint responsive table

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#25813]
I'm not fully understood those use cases sorry, but there is almost no difference in [the demo of the breakpoint specific responsive tables](http://getbootstrap.com/docs/4.0/content/tables/#breakpoint-specific).

![table](https://user-images.githubusercontent.com/4065765/37187941-0d2142f6-2390-11e8-8bc5-3ed1234060b4.gif)

Could someone update the demo so that the effective usage of these breakpoint options will become clear? Thanks.

**Comment by Varunram** [comment]
PR: #25827

**Comment by ysds** [comment]
Thanks but I don't think it shows a effective use case. It really just looks like a bug to me.

![table2](https://user-images.githubusercontent.com/4065765/37278449-167d10ee-262b-11e8-8675-b2a799dfb4ea.gif)

In what situation do you use those UX?

**Comment by Varunram** [comment]
yeah, the question regarding their utility is a point of contention. Maybe the maintainers can expand on whether they would still like this feature to exist.

**Comment by ysds** [comment]
I suggest to deprecate the responsive variations except `.table-responsive` and remove them in the next major release v5.
