### ISSUE TITLE
.accordion-flush

### ISSUE THREAD

**Issue by BrainFeeder** [twbs/bootstrap#25811]
It might be interesting to add an `accordion-flush` class like `list-group-flush`.

**Comment by kampalex** [comment]
Due to a different bug in the accordion component I've created a [sample page](https://codepen.io/kampalex/pen/XweKKL) to express multiple accordion variants.
Maybe this is the idea to create.

**Comment by BrainFeeder** [comment]
A late comment, but yeah, I like that 'flushed' accordion :) . I managed to get something similar too. But this is better in my opinion.
