### ISSUE TITLE
bootstrap css broken after build

### ISSUE THREAD

**Issue by charlesverge** [twbs/bootstrap#25818]
Several css elements are removed after executing a fresh `npm install ; npm run-script dist` on the dev-4 branch. An example is display: -ms-flexbox; this breaks some browsers  ios 7 and ios 8. I've not tested on ios 9, 10 or 11.

The build environment is a ubuntu install and a mac os x install.

```
.row {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px;
}
```
From the git repo
```
.row {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px;
}
```

**Comment by wolfy1339** [comment]
The dist on the repo isn't up to date.
That output is correct.
As per the [docs](https://getbootstrap.com/docs/4.0/migration/#browser-support) and #25429:
> Dropped IE8, IE9, and iOS 6 support. v4 is now only IE10+ and iOS 7+. For sites needing either of those, use v3.
