### ISSUE TITLE
:hover and .hover

### ISSUE THREAD

**Issue by sezeresen** [twbs/bootstrap#25819]
Sometimes hover effect needs to set by programmatically.

For example I have a table with comment row belongs to previous row.
When this row on hover it needs to set both of rows on hover effect.

I set a class `.hover` for not hovered row. Both of rows connected to each others and manage their on hover effects.

With tweak of table scss files I solve this problem. But I think this must be in core of bootstrap.

Please add `.hover` class for all `:hover` things.

**Comment by mdo** [comment]
No plans to do this. We'd be expected to do the same for `:focus` and we already do it for `:active`.
