### ISSUE TITLE
Open 3rd Collapse on load

### ISSUE THREAD

**Issue by chiraggmodi** [twbs/bootstrap#25814]
hi
is there any method to open 3rd collapse in accordion by default. I.e on page load?
https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

**Comment by Johann-S** [comment]
yep just add the `.show` class on the third collapse 😉 use your linked example, remove the `.show` class from the first one, and add it to the third one

**Comment by chiraggmodi** [comment]
thanks, this i already know, 
actually there is jQuery event added which overriding this. 
Thanks for help.
