### ISSUE TITLE
Bootstrap 4 Popover placement does not recognize boundary of parent window from within iFrame

### ISSUE THREAD

**Issue by ss-coder** [twbs/bootstrap#25810]
I have tested Bootstrap 4 Popover. When the Popover is in an iFrame it does recognize the edges of the parent window and will get cut-off by the parent window. 

If the Popover is still within the boundary of the iFrame, but the iFrame scrolls past the edge of the parent window, the Popover does not realize that it has passed the boundary of the parent window.

You can see a working example on CodePen here:
https://s.codepen.io/ss_coder/debug/NYKeGv/dXkqBbvObqzM

This bug applies to all browsers on PC, MAC, Android & iOS.

Hopefully this can be resolved. Thank you!

**Comment by FezVrasta** [comment]
I get a 403 when I open the codepen

**Comment by Johann-S** [comment]
Strange ! Everything is fine for me 😟 
You can try this link : https://codepen.io/ss_coder/pen/GQVQVV?editors=1000#0

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/37141368-0f5069b6-22b5-11e8-836a-37d4a024b12e.png)

**Comment by Johann-S** [comment]
I forked this CodePen : https://codepen.io/Johann-S/pen/wmwQJa?editors=1000

**Comment by FezVrasta** [comment]
Still having the same problem :(

**Comment by ss-coder** [comment]
My debug mode expired in CodePen. You will need to view it in debug mode. I will update... give me a few minutes

**Comment by ss-coder** [comment]
I have updated the comment with a new link. Here is the link:
https://s.codepen.io/ss_coder/debug/NYKeGv/dXkqBbvObqzM

I am not sure how long the debug mode will last. Thank you!

**Comment by FezVrasta** [comment]
Ok thanks, I'm not sure if this is expected or not actually. It does support reference elements inside iframes (while the popper element is outside of it) but we never added support for this use case.

Feel free to open an issue on the Popper.js repository asking for this feature, if someone is interested it may get implemented.

**Comment by ss-coder** [comment]
Ok... I will do that. Thank you for viewing my test case!

**Comment by Johann-S** [comment]
So I'll close as it's a Popper.js issue

**Comment by mavrosxristoforos** [comment]
Hello. I'm a Joomla extension developer. Joomla 4 uses Bootstrap 4.5.2, which includes the bundled version with Popper 1.16.1.
I think this issue needs to be re-opened here, because Popper has moved to version 2, and it hasn't been fixed in 1.16.1 as per this post: https://github.com/popperjs/popper-core/issues/791
