### ISSUE TITLE
<a class="btn" href="#" role="button">Link</a> does not display a button

### ISSUE THREAD

**Issue by paceband** [twbs/bootstrap#25821]
`<a class="btn" href="#" role="button">Link</a>`
does not display a button. I except to see the default button.

`<a class="btn btn-primary" href="#" role="button">Link</a>`
works of course but the is no way to display the "default" button as we can with a "button" tag.

**Comment by hercial61** [comment]
Thanks

**Comment by patrickhlauke** [comment]
bootstrap doesn't aim to replicate the default vanilla look of a `<button>` - particularly as that is browser/platform dependent, so that wouldn't be possible in any case.
