### ISSUE TITLE
Bootstrap Dropdowns and Popovers call parent element's hide function

### ISSUE THREAD

**Issue by gwhenne** [twbs/bootstrap#25837]
When a Bootstrap Dropdown item is selected or a Popover closed, the popped up content is closed. However, a call is also made to the hide() function of the parent:
```
    <div id="Dropdown" class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
        Dropdown button
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </div>
    
    <button id="Button" type="button" class="btn btn-lg btn-danger" data-toggle="popover" data-placement=bottom title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
    
    <script>
    Button.hide = function() {console.log('hide button called')};
    Dropdown.hide = function() {console.log('hide dropdown called')};
    </script>
```
In the above code, messages will appear on the console when the dropdown or popover are dismissed. Looking at the stack trace, the actual call to the hide function is coming from jQuery.

This happens in both Bootstrap 3 and 4.

Is there anyway to prevent this from happening? If not, is there a way to detect if hide() is being called from jQuery?

Here's a jsfiddle: https://jsfiddle.net/ghenne/yeo3nh17/

**Comment by Johann-S** [comment]
I don't understand, what's your issue here ? What's the bad behavior you want to show us ? Because if you don't and unknown methods to your DOM elements you won't have any issue here 😟 

Our plugins always throw an `hide` and `hidden` events so you'll be able to detect when hide is called.

**Comment by gwhenne** [comment]
In that case, is there any way to detect that the `hide` was called by Bootstrap?

I can then get Button.hide to execute its code only if it isn't called by Bootstrap.

**Comment by Johann-S** [comment]
you only have to listen to our `hide` or `hidden` events to execute your code when our internal hide method is called.

For example: 
```js
$('#myPopover').on('hide.bs.popover', function () {
 // your code
})

**Comment by gwhenne** [comment]
Thanks - that works.
