### ISSUE TITLE
[FEATURE] Support for nested input-group-append/input-group-prepend

### ISSUE THREAD

**Issue by StickNitro** [twbs/bootstrap#25830]
When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible
I am wondering if it would be possible to support nesting with `input-groups`.  My use case is that I am using Angular 5 and have written a dropdown button component with the template being the following

Below is the template for component named `question-dropdown-button`
```
<div class="input-group-append" ngbDropdown>
  <button ngbDropdownToggle class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</button>
  <div ngbDropdownMenu class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div role="separator" class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>
```

I then use this component anywhere that I need it, for example:

```
<div class="input-group">
  <input type="text" class="form-control" />
  <question-dropdown-button></question-dropdown-button>
</div>
```

When loading this does not apply the border radius correctly to the dropdown button even though this is in an `input-group-append`.  Looking at the generated CSS I believe this is down to the combinator that is used and relies on the `input-group-append` being a child of the `input-group` class.

In the case of Angular 5 and it's component rendering the following is the HTML output

```
<div _ngcontent-c12="" class="input-group">
  <input _ngcontent-c12="" class="form-control" type="text">
  <question-dropdown-button _ngcontent-c12="" _nghost-c13="">
    <div _ngcontent-c13="" class="input-group-append dropdown" ngbdropdown="">
      <button _ngcontent-c13="" aria-expanded="false" aria-haspopup="true" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle" data-toggle="dropdown" ngbdropdowntoggle="" type="button">Dropdown</button>
      <div _ngcontent-c13="" class="dropdown-menu" ngbdropdownmenu="">
        <a _ngcontent-c13="" class="dropdown-item" href="#">Action</a>
        <a _ngcontent-c13="" class="dropdown-item" href="#">Another action</a>
        <a _ngcontent-c13="" class="dropdown-item" href="#">Something else here</a>
        <div _ngcontent-c13="" class="dropdown-divider" role="separator"></div>
        <a _ngcontent-c13="" class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>
  </question-dropdown-button>
</div>
```

You will notice the additional element that wraps the `input-group-append` element which means this is no longer a direct child of `input-group` and so "breaks" the combinator.

**Comment by mdo** [comment]
Regrettably, we're basically hamstrung and need to limit it to immediate children. Nesting can't be supported without causing a bunch more problems for folks who nest content in dropdowns and other customized markup.
