### ISSUE TITLE
Collapse unintentionally receives padding from columns

### ISSUE THREAD

**Issue by Mitcheljager** [twbs/bootstrap#25845]
When using the `collapse` class, it receives the gutters from the `col` classes.
The `cols` receive their padding from `[class^="col"], [class*=" col"]`. `collapse` of course starts with `col`, and thus receives the padding unintentionally.

A temporary fix is to add the utility class `px-0`.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Columns don't receive padding from those selectors; `.col` classes have their padding set explicitly on their individual class names. We override padding in two situations in our source code, but the selector is looking at `col-` and not `col` to avoid this exact problem.

**Comment by Mitcheljager** [comment]
Upon further investigation I can no longer recreate the issue. I'm not certain where it came from.
