### ISSUE TITLE
forms in Modals don't work on mobile devices

### ISSUE THREAD

**Issue by iamjaime** [twbs/bootstrap#25844]
I noticed that the modal forms are not working on mobile devices.

The cursor seems to jump around everywhere.

![image uploaded from ios](https://user-images.githubusercontent.com/7141706/37405036-f3817310-2769-11e8-8306-6b58017777d4.png)

**Comment by patrickhlauke** [comment]
duplicate of https://github.com/twbs/bootstrap/issues/24352 which unfortunately is due to a webkit/ios bug outside of our control, but which hopefully will get fixed
