### ISSUE TITLE
The background color of responsive table with .table-dark is not applied

### ISSUE THREAD

**Issue by nk-aoi** [twbs/bootstrap#25842]
When scrolling the responsive table with `.table-dark`, the background color of the hidden part is not displayed correctly.

![image](https://user-images.githubusercontent.com/17547966/37383421-0f5a7f7e-278c-11e8-9b93-863e09f9b000.png)

Delete `max-width: 100%;` property of `.table` will display correctly.

![image](https://user-images.githubusercontent.com/17547966/37383499-6e69f65c-278c-11e8-83b8-2fee7dcea000.png)

- OS: iOS 10.3.3
- Browser: Safari
- Sample Code: https://codepen.io/aoi70/pen/ZxQRer

**Comment by Johann-S** [comment]
Unable to reproduce it on Win10, Chrome 64

**Comment by Bennet11** [comment]
I can't reproduce it on Mac OSX as well. Im using chrome

**Comment by ysds** [comment]
iOS Safari: 

![ios-safari](https://user-images.githubusercontent.com/4065765/37446971-f6b58d42-2862-11e8-9d70-26616f837636.jpg)

**Comment by bakedbird** [comment]
Issue confirmed on macOs Safari. It seems that max-width: 100% on table causes the issue

**Comment by jamesbradleym** [comment]
Still having this issue on iOS Safari.
![1](https://user-images.githubusercontent.com/33179100/48636399-c2f5f580-e998-11e8-8c0e-21a58ba66c33.png)
![2](https://user-images.githubusercontent.com/33179100/48636400-c38e8c00-e998-11e8-81e1-f759d3cbee06.jpg)
![3](https://user-images.githubusercontent.com/33179100/48636402-c38e8c00-e998-11e8-9fe9-b5ce5e5aba6c.png)
