### ISSUE TITLE
Using the grid in a navbar makes row's width auto

### ISSUE THREAD

**Issue by rvdheijdennl** [twbs/bootstrap#25843]
When using the grid in the navbar, the row's width is not 100% anymore.

Problem occurs because of `.navbar > .container` = flexbox display.

    <nav class="navbar">
        <div class="container">
            <div class="row">
                auto width
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            100% width
        </div>
    </div>

Example: https://jsfiddle.net/8exp8kde/

**Comment by Bennet11** [comment]
Im not sure if this is what you want but I tried this and width is not 100%
https://jsfiddle.net/8exp8kde/4/

**Comment by mdo** [comment]
Yeah, the container because a flex item in addition to being a flex container. This is flex behavior, not a bug. Also, empty rows aren't required for full-width content inside a container. You can nix that unless you're just shortcutting for code snippet and plan to use columns.
