### ISSUE TITLE
getbootstrap.com download button sends beta3 not rtm

### ISSUE THREAD

**Issue by robrich** [twbs/bootstrap#25851]
Repro steps:

1. Visit getbootstrap.com
2. Click on download button on top-right
3. Get Bootstrap 4 beta 3.zip

Expected to get Bootstrap 4 dist.zip

getbootstrap.com/docs/4.0/getting-started/download/ also has a download button in the middle of the page, and this button works correctly.

I'd send a PR but I can't find the repo for the getbootstrap.com site.

**Comment by XhmikosR** [comment]
Work fine here, not sure why that happens to you.

**Comment by mdo** [comment]
Yeah, looks fine on my end, too. Link points to the v4 release zip.

**Comment by patrickhlauke** [comment]
hypothesis: something to do with web app / offline storagey stuff that cached a really old outdated version of the site on the user's machine?

**Comment by XhmikosR** [comment]
Could be, but I'm not sure what to do to ensure this doesn't happen. In theory, it shouldn't happen...
