### ISSUE TITLE
In docs, .modal-footer code is not the same as output

### ISSUE THREAD

**Issue by altbdoor** [twbs/bootstrap#25853]
I am referring to the [modal components](https://getbootstrap.com/docs/4.0/components/modal/#modal-components) section of the Bootstrap documentation for v4.

The code example shows:
```html
<div class="modal-footer">
  <button type="button" class="btn btn-primary">Save changes</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>
```

But the output rendered is:
![image](https://user-images.githubusercontent.com/3540471/37446218-dec31710-2856-11e8-93a6-a5bd6718bc4d.png)

And upon inspecting the rendered HTML content, its:
```html
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <button type="button" class="btn btn-primary">Save changes</button>
</div>
```

Looks like a small mistake on the order of the buttons in the code example?

**Comment by Bennet11** [comment]
Hi there, Im just new here also in bootstrap but I tried to reproduce the same code mentioned in the documentation and it seems like the button were interchanged.
