### ISSUE TITLE
模态框设置属性tabindex ,input 不能输入

### ISSUE THREAD

**Issue by EY5740** [twbs/bootstrap#25856]
在模态框上添加时间控件 foundation-datepicker。我在上面扩展了一个input.
当模态框显示时，input 不能输入。

**Comment by patrickhlauke** [comment]
I'm afraid we can't help you with implementation-specific questions (e.g. how Bootstrap interacts with Foundation). I'd suggest asking on StackOverflow or similar - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
