### ISSUE TITLE
[BUG] some FontAwesome icons (fa-chart) don't display as input tooltips 

### ISSUE THREAD

**Issue by fr33z00** [twbs/bootstrap#25857]
Plateform: linux
browser : firefox 58, chrome 64
bootstrap : v4.0.0 release
fontAwesome: v5.0.8

Create an input-group div, populate it with a text input, add a div tooltip with classes input-group-text and fa-chart-line/fa-chart-graph. Icon won't display in tooltip.

When changing tooltip class to fa-chart-bar, icon displays. When removing the input-group-text class, icon will display (albeit not as a tooltip).

[Code example on jsbin](https://jsbin.com/zoketivavu/edit?html,output)

So weird...

**Comment by magiclen** [comment]
Hi, I think the attribute `font-weight` for your FontAwesome icon needs to be 900. But after inserting the `input-group-text` class, the attribute `font-weight` is set to 400.

Therefore, you can just change the HTML code,

```html
<span class="input-group-text fa fa-chart-line"></span>
```

to

```html
<span class="input-group-text"><i class="fa fa-chart-line"></i></span>
```

**Comment by fr33z00** [comment]
Thx magiclen, your suggestion does the trick.
So subtile!
