### ISSUE TITLE
Quickly switching tabs using Navs with JavaScript makes the tab content go wrong

### ISSUE THREAD

**Issue by magiclen** [twbs/bootstrap#25854]
#### Environment

Operating system: Linux Mint 18.3 Cinnamon
Browser: Chrome 65.0.3325.162 and Firefox 58.0.2
JS Bin: https://jsbin.com/pidaziv

#### Snapshot
https://imgur.com/a/1MAWb

#### Steps to Reproduce

1. Click the tab `Contact`
1. Click the tab `Profile` and then click the tab `Contact` again in few milliseconds.

**Comment by bakedbird** [comment]
I tried reproducing the issue on the jsbin you provided and it works as it should.

**Comment by magiclen** [comment]
I made a video on YouTube. If you can't reproduce, perhaps you can check out the following link,
https://youtu.be/feXLwYA8D9M

Currently, I'm sure this problem happens on Linux Mint, Windows and Android.

**Comment by Johann-S** [comment]
Unable to reproduce it too 😟

**Comment by bakedbird** [comment]
Was able to reproduce on my Android device. It only happened when tapping on another tab before the animation of the previous has finished.

**Comment by Johann-S** [comment]
ok, so we should handle the transitionning state and disallow to change tabs during this transition

**Comment by bakedbird** [comment]
@Johann-S Found a way to reproduce it on a browser if that would be of more help to you.

On the jsbin @magiclen provided
**Steps to reproduce**
- Have the first tab shown (Home)
- hit `tab` then `enter` twice, fast

this will have the second and third tabs open simultaneously (Profile, Contact).
Now, if you click on the first or second tab (Home, Profile) the Contact tab remains shown (until you click to show that one too).

**Comment by Johann-S** [comment]
I think I'm not quick enough to reproduce that but thanks @bakedbird 😆 But I see where is the issue

**Comment by bakedbird** [comment]
@Johann-S Took me some days to train my speed too 😝

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
