### ISSUE TITLE
[Issue] PDF Reverse Words

### ISSUE THREAD

**Issue by vinkla** [twbs/bootstrap#25861]
I'm using Bootstrap 4.0.0 to create printable PDF templates in the browser. It is working and looking great when I in the browser select to print the current page and then select to download the print as a PDF. When I copy text from the generated PDF file and paste it into my text editor all words are reversed.

<img width="1197" alt="screen shot 2018-03-15 at 4 52 25 pm" src="https://user-images.githubusercontent.com/499192/37474721-51af2e84-2871-11e8-8d7e-eef73e9a7185.png">

I've tried writing custom CSS templates and downloaded and it works fine. I'm guessing this doesn't have anything to do with the download as PDF functionality in Google Chrome.

Is this something that has come up before? I couldn't find anything related in the issues. Maybe I'm writing my template files wrong, is there are way to configure Bootstrap to make the words look ok?

**Comment by patrickhlauke** [comment]
we'd need a reproducible live test case for this. but a priori, this sounds like a problem or bug in Chrome's PDF printing. does it happen in other browsers when printing to PDF?

**Comment by vinkla** [comment]
You're right @patrickhlauke! This works fine in both Safari and Firefox. Thanks for taking the time to answer. I'll move this issue to another repository.

**Comment by patrickhlauke** [comment]
no worries @vinkla ... it's an intriguing bug regardless :)
