### ISSUE TITLE
H Tag Utilities

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#25862]
Was just thinking. In the same way as we have utilities like `pb-3` `pb-lg-5` to have h tag utilities too, e.g. `h2-md-h4` `h2-lg-h3` `h2-xl-0`.

**Comment by browner12** [comment]
can you please explain what you are trying to accomplish with these classes?

**Comment by bakedbird** [comment]
If I understand right, what @chrisbo is trying to accomplish is to have the font size of the h tags change responsively.
Although this can be useful, I think that it should be handled on app base styles and not on the framework level.

**Comment by browner12** [comment]
agreed.

**Comment by fchiumeo** [comment]
this #23053 ?

**Comment by chrisbo** [comment]
@bakedbird is correct. I raised this because I hate titles that wrap or go off to the right of the screen on small devices. In fact, it's just about the only thing I use additional media queries for these days. Anyway, I can live without it. Just a suggestion.

**Comment by mdo** [comment]
We'll do responsive typography at some point, but I don't see us adding the responsive type utilities.
