### ISSUE TITLE
Buttons in sample accordion don't have type="button"

### ISSUE THREAD

**Issue by franktopel** [twbs/bootstrap#25860]
![grafik](https://user-images.githubusercontent.com/10668603/37471919-208565b8-286b-11e8-9ffd-b6ceb4e5fc32.png)

https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

**Comment by franktopel** [comment]
It'd be helpful if you checked before closing. The issue still exists.

**Comment by wolfy1339** [comment]
@franktopel The docs in the repo already contain the fix. The live docs aren't synced to the repo.

**Comment by franktopel** [comment]
Ah, thanks for the information. I was expecting the docs to always reflect the current master branch.

**Comment by wolfy1339** [comment]
Actually, that's wrong too. `npm install bootstrap` installs the code for v4.0.0 not the current "master"

**Comment by patrickhlauke** [comment]
the npm package, and what you get on getbootstrap.com, relate to stable releases. after a stable release, work continues on the repo (with changes, fixes, etc) until the next release...

**Comment by patrickhlauke** [comment]
(of course, if that wasn't clear, it could have been discussed over on https://github.com/twbs/bootstrap/pull/25859 instead of opening a new issue...but anyway)
