### ISSUE TITLE
Scroll Don´t Work in a modal (IOS)

### ISSUE THREAD

**Issue by AnkorAzul** [twbs/bootstrap#25865]
I am working in a website with mvc .net and boostrap(v3.3.7).
when open a modal and the content is a external website, the scroll dont work in the modal but it work in the background  (only in apple mobile device)(Safari and Chrome).

i tried with
         -Embed.
         -iFrame.
         -Object.

**Comment by altbdoor** [comment]
@AnkorAzul I think this is a general issue with modal boxes and iOS devices in general. Please refer to #24737 .

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding!

---

_This is a saved reply._
