### ISSUE TITLE
Including individual js scripts via npm not working

### ISSUE THREAD

**Issue by webbyhall** [twbs/bootstrap#25877]
Just installed npm package 4.0.0 and complied individual js files for the dropdown/toggle menus but it doesn't seem to work, but did on the last version.

I compiled dropdown.js, collapse.js, until.js and popper.js.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by Johann-S** [comment]
You can try to reproduce your issue on StackBlitz: https://stackblitz.com/
