### ISSUE TITLE
readonly-plain-text with button addon

### ISSUE THREAD

**Issue by caiquecastro** [twbs/bootstrap#25870]
The readonly plain text doesnt work with button addon.

Live example: https://codepen.io/caiquecastro/pen/eMdmYo

![image](https://user-images.githubusercontent.com/3316550/37526649-b245d4ee-290e-11e8-87bc-27c0189d9e8e.png)

```
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <button class="btn btn-outline-secondary" type="button">Button</button>
  </div>
  <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
</div>
```

**Comment by patrickhlauke** [comment]
why would you use it this way? simply dropping the `.input-group-prepend` solves this of course. it's not really possible, to my knowledge, to rewrite styles so that the button takes account of an element that comes *after* it.

**Comment by patrickhlauke** [comment]
ah, i thought you meant the right-hand border of the button not being rounded, and missed the email showing on a new line...doh

**Comment by mdo** [comment]
I understand the desired affect here, but why would you do this? An input group is intended to visually connect button/text and form control.

**Comment by patrickhlauke** [comment]
i'd imagine for consistency if the form is read/write at one point/for certain users, but some of the fields are read-only after submission/for other users, so you can keep the scaffolding the same

**Comment by caiquecastro** [comment]
I have it readonly, but if I click it. I should remove its readonly state, and enable change the value.

**Comment by mdo** [comment]
Why not use only the [`readonly` attribute](https://getbootstrap.com/docs/4.0/components/forms/#readonly) then? If the idea is that at some point a user could interact with that field, I would think it should be a field from the beginning.

**Comment by patrickhlauke** [comment]
regardless of the specific use case here, though, i'd say the fix (or something similar to it) seems legit to me.

**Comment by Defatul** [comment]
Line 3316
append -> .input-group > .form-control-plaintext,

Line 3353
append -> .input-group > .form-control-plaintext:not(:last-child),

Line 3361
.input-group > .form-control-plaintext:not(:first-child),

Line 3441
.input-group-lg > .form-control-plaintext,

Line 3460
.input-group-sm > .form-control-plaintext,
