### ISSUE TITLE
 nav does not justify right if menu inside a row

### ISSUE THREAD

**Issue by broros** [twbs/bootstrap#25882]
I am trying to justify menu to the right, does not work inside a row...
```
<div class="row">
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>
</div>
```

**Comment by mdo** [comment]
Re-read https://getbootstrap.com/docs/4.0/layout/grid/#how-it-works. Only columns can be children of rows. Your `.nav` is a flex item because of this and won't behave as you're expecting. Either use an `align-` utility, or change the markup.
