### ISSUE TITLE
bootstrap.js has a line that makes an error

### ISSUE THREAD

**Issue by dinzr7** [twbs/bootstrap#25884]
![report](https://user-images.githubusercontent.com/23526628/37566624-bae5d2b8-2af6-11e8-9b9f-b780bc31a96d.png)

downloaded JS at 3/17/2018

**Comment by patrickhlauke** [comment]
i'm going to assume that you're just trying to use bootstrap.js without also including jquery? if so, see http://getbootstrap.com/docs/4.0/getting-started/introduction/#js

**Comment by dinzr7** [comment]
Well i already added jquery too

**Comment by dinzr7** [comment]
Well i did but it was inserted after the script for bootstrap.js my bad
