### ISSUE TITLE
can't use Bootstrap.css file to make Navbar as drop-down on Responsive Mobile View

### ISSUE THREAD

**Issue by dhavalveera** [twbs/bootstrap#25883]
Hello

I need help, I want to learn Bootstrap where I can use Bootstrap.css to to Website's Navbar as Drop-Down on Responsive Mobile View.

Please help me in this.

Waiting for your quick reply,

Dhaval

**Comment by patrickhlauke** [comment]
sorry, the issue tracker is only to discuss bugs/issues in bootstrap, not for general help/how-tos. suggest using StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
