### ISSUE TITLE
Any solution for smoothly change auto width of input based on content ?

### ISSUE THREAD

**Issue by mijatovicmile** [twbs/bootstrap#25880]
Hello, 

I am using Bootstrap 4 inline form and I want to dynamically **smoothly** change **auto** width of the inline form elements if it is possible.

I know how to achieve that with for example **col-md-4** to **col-md-6** with transition: width 1s ease; but problem is with col-auto

Is there any any solution for that?

I have [this ](https://pastebin.com/7JeZm9i2)code - 

and it looks like like this

![pcp](https://user-images.githubusercontent.com/28740895/37558817-40f69ed8-2a1a-11e8-9032-54c82fedc2d4.png)

**Because my application will be multilanguage, english and german, the label will be changed dynamically** and for the same input I will have german version, like this...

![hzv](https://user-images.githubusercontent.com/28740895/37558821-50ca1434-2a1a-11e8-9c6f-23e03332bed7.png)

As you can see label for german version is longer word that english, so I would like to achieve when user changed the language by click on the english or german flag, smooth shrink of input proportional to the length of the label.

If you have some question , feel free to ask me, I will explain in more detail.

Thank you in advance

**Comment by mdo** [comment]
This isn't the place for how-to questions, but this is accomplishable with the grid system and some flex utilities. Worst case scenario, you could use table styles, too.
