### ISSUE TITLE
There isn't any .navbar-nav-scroll in bootstrap.css but getbootstrap.com used it

### ISSUE THREAD

**Issue by amirahmadKhordadi** [twbs/bootstrap#25897]
Is there any .navbar-nav-scroll in bootstrap?
![capture](https://user-images.githubusercontent.com/30090310/37659819-2a4539f8-2c66-11e8-9a3c-6aa5d53f1cd6.PNG)

**Comment by mdo** [comment]
Yes, it's currently limited to the docs and the offcanvas example. It's not a complete implementation by any means, and as such, we don't have it documented as an official component.
