### ISSUE TITLE
Dropleft and Dropright Split Button Dropdowns are Different Widths

### ISSUE THREAD

**Issue by Joyrex** [twbs/bootstrap#25892]
Split button dropleft/right button dropdowns are different widths

See documentation and inspect using Developer tools: https://getbootstrap.com/docs/4.0/components/dropdowns/#dropright-variation
Split Dropright: 33.69px
![image](https://user-images.githubusercontent.com/651646/37608024-6587295e-2b67-11e8-98f3-2af496f54288.png)
Split Dropleft: 28.89px
![image](https://user-images.githubusercontent.com/651646/37608045-75b0b0d4-2b67-11e8-9018-20d18894b9a5.png)

Tested on Chrome 65.0.3325.162 (Official Build) (64-bit) Windows 10

Can't quite figure out why; CSS for each looks consistent in terms of what I could see that would affect the width of the button dropdown - will report back if I can find a fix.

**Comment by MartijnCuppens** [comment]
This was fixed 7 days ago ;)
See https://github.com/twbs/bootstrap/pull/25719/files#diff-29d9f48468617f7a651cb764d91ff944

**Comment by Joyrex** [comment]
Awesome! I should have checked the pull-requests on my search...
