### ISSUE TITLE
Hover transition doesn't working on Firefox.

### ISSUE THREAD

**Issue by adsingh14** [twbs/bootstrap#25909]
##### _Please check the pen link on all web browsers._

<p data-height="384" data-theme-id="light" data-slug-hash="YaVyjO" data-default-tab="result" data-user="adsingh14" data-embed-version="2" data-pen-title="Bootstrap 4 :hover problem" class="codepen">See the Pen <a href="https://codepen.io/adsingh14/pen/YaVyjO/">Bootstrap 4 :hover problem</a> by AMAN (<a href="https://codepen.io/adsingh14">@adsingh14</a>) on CodePen.</p>

**Comment by patrickhlauke** [comment]
works fine in Firefox 60.0b4

**Comment by patrickhlauke** [comment]
ah, correction. missed that this was about the transition effect. i'm guessing it's a browser bug, not something bootstrap-specific

**Comment by patrickhlauke** [comment]
and explicitly setting a starting color for the transition fixes it in Firefox as well (e.g. `box-shadow: 0 1px 0px #000;`)
