### ISSUE TITLE
Variable ratios for responsive embeds

### ISSUE THREAD

**Issue by c0defre4k** [twbs/bootstrap#25906]
Since colors, spacers, sizes, ... are generated based on map I think it would be just as suitable to introduce a `$embed-ratios` variable.

See [this gist](https://gist.github.com/c0defre4k/9699b11263ca6df239be3962eb1d0e01) for an implementation example,

**Comment by midzer** [comment]
I think this might come handy in certain situations :+1:

**Comment by MartijnCuppens** [comment]
Made a PR for this 2 days ago (see #25894)
