### ISSUE TITLE
jquery.slim.js don't work well with Bootstrap

### ISSUE THREAD

**Issue by ekoulemaneng** [twbs/bootstrap#25902]
In one of my web front-end project, I noted that neither jquery-3.3.1.slim.js nor jquery-3.3.1.slim.min.js don't work when we want to use the jQuery animate effect. It's better to use either jquery-3.3.1.min.js nor jquery-3.3.1.js. Therefore, the jQuery slim version is not yet appropriate. Thanks !.

**Comment by Johann-S** [comment]
We suggest jQuery slim, but you're free to choose the version you want if you need some special features from jQuery 😉
