### ISSUE TITLE
Add JS to remove focus styling from anchor tags as btns or remove focus styling

### ISSUE THREAD

**Issue by NJM8** [twbs/bootstrap#25907]
Hello, 

I have come across an issue while using an anchor tag styled as a button. The anchor tag in this case opens a link in a new window. On click bootstrap applies some focus styling, when I return back to my page the anchor tag still has the focus styling applied. @dardandemiri helped me with a hack to remove the styling after the click, however I think that since bootstrap is applying the styling it should handle the removal by default. This also affects tooltips if they are used on the anchor tag as they will not go away while the element has focus. 

A working example can be found here: https://www.natethedev.com/bootstrapanchorfix/

If I have done something wrong with my anchor tag use I'm happy to learn, thanks for looking.

**Comment by patrickhlauke** [comment]
The current behavior is intended, as those elements do have focus. We may, in future, explore using `focus-visible` to provide more granular styling of focus https://drafts.csswg.org/selectors-4/#the-focus-visible-pseudo but there's no plans to now inject JS to do it.

**Comment by NJM8** [comment]
Thanks @patrickhlauke. Would it be appropriate to add to the button documentation to highlight this behavior when using anchors tags as buttons? That way users are aware of the difference and that it will not act like a regular button.
