### ISSUE TITLE
custom-select appearance:none not work

### ISSUE THREAD

**Issue by kamov** [twbs/bootstrap#25901]
On your demo I don't see the browser default arrow in select, as I see that **appearance: none** remove it.

However in my site is not removed.

I see that in your demo you have also equivalent for firefox _moz-* and _webkit-* in the compiled css, but in sass file custom-forms.scss there is only _appearance: none;_

**Comment by mdo** [comment]
https://getbootstrap.com/docs/4.0/getting-started/build-tools/ will help you—you need Autoprefixer.
