### ISSUE TITLE
d-sm-block breaks bootstrap tabs

### ISSUE THREAD

**Issue by hcanning2014** [twbs/bootstrap#25908]
Hi,
Using below to switch between PC and phone view and it breaks the default bootstrap 4  tabs layout/styling.
`<ul class="nav nav-tabs d-none d-sm-block" id="myTab2" role="tablist">....`
Issue is with `d-sm-block and d-none applying display: block !important; `in its  CSS
Thanks

**Comment by mdo** [comment]
Navs are built with flexbox, you'll need `d-sm-flex`.
