### ISSUE TITLE
Making it possible to split into multiple stylesheets depending on media

### ISSUE THREAD

**Issue by ClausSPedersen** [twbs/bootstrap#25915]
Performance is becoming more and more important for websites, which makes it a problem with very large stylesheets.

It would be great if it was easy to generate lower footprint stylesheets for specific device sizes, so it was possible to have stylesheet references to specific breakpoints like:
`<link rel="stylesheet" href="/css/bootstrap-lg.min.css" type="text/css" media="(min-width: 992px)">`

which would cause that small devices doesn't waste time on downloading the styles they don't need anyway.

I would also like an easier way to only load critical css in the beginning and defer other parts to later. I use scss to build my own builds, but they quickly inflate as soon as the I start to import basic parts.

**Comment by herbalite** [comment]
With CSS @import you can split up CSS files according to media queries.

https://developer.mozilla.org/en/docs/Web/CSS/@import

Deferred loading isn't possible with this approach, and the downside is always extra requests to the server, which might in the end up being worse than having one big file. Mileage varies.

**Comment by wolfy1339** [comment]
You can definitely do this using SASS and some custom include files.

**Comment by mdo** [comment]
This is entirely dependent on your setup though, and not something we should try to do for everyone.
