### ISSUE TITLE
.btn-outline-light color should be dark

### ISSUE THREAD

**Issue by ziruhel786** [twbs/bootstrap#25912]
In .btn-outline-light color should be black or more dark and border should be little more dark. 
![btn-prob](https://user-images.githubusercontent.com/4748229/37751792-8ac54d14-2dbe-11e8-84f4-d768f9d2d449.jpg)

And this is existing code: 
```
.btn-outline-light {
    color: #f8f9fa;
    background-color: transparent;
    background-image: none;
    border-color: #f8f9fa;
}
```
It should be like: 
```
.btn-outline-light {
    color: #343a40;
    background-color: transparent;
    background-image: none;
    border-color: #eeeeee;
}
```

**Comment by mdo** [comment]
It should stay exactly as it is—it's for use against dark backgrounds.
