### ISSUE TITLE
Carousel events not working correctly under Firefox

### ISSUE THREAD

**Issue by nevez** [twbs/bootstrap#25916]
Using Bootstrap v4.0.0 with Firefox 59 under Lubuntu 16.04 (tested under windows 7 too). Carousel events sometimes fire sometimes don't. If you set a handler for just one event ("slide" OR "slid"), it doesn't work correctly. Curiously, if you register both handlers ("slide" and "slid"), they both fire correctly (???). Might be a Firefox quantum issue.

Steps to reproduce:

1. Open the carousel documentation page with Firefox: https://getbootstrap.com/docs/4.0/components/carousel/
2. Open console and type $('#carouselExampleControls').on('slid.bs.carousel', function (ev) { console.log('slid!'); })
3. Try to slide the second carousel example with the controls or just wait to see if the "slid" event fires.
4. Add the other event listener: $('#carouselExampleControls').on('slide.bs.carousel', function (ev) { console.log('slide!'); }) , and see how both events now works.

Note: everything works under Chrome.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by nevez** [comment]
This is not a bug. It was the console aggregating repeated messages... must get some sleep! :-D Sorry.
