### ISSUE TITLE
Mistake in Jumbotron docs

### ISSUE THREAD

**Issue by daveonestar** [twbs/bootstrap#25918]
In the Jumbotron docs example, the foloowing code appears:
```
<p class="lead">
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</p>
```

The 'lead' class here does nothing to the button and therefore should be omitted.
In addition, I think a div should be used instead of a paragraph because there is no real paragraph here, it just holds a button.

**Comment by Varunram** [comment]
Agreed, a button within a `p` tag doesn't make much sense. We could either leave the button as is within the anchor tag or enclose it within a div.

**Comment by BrainFeeder** [comment]
Not only the `<a>` tag inside the jumbotron has wrapping `<p>`.. Probably used to have some margin between text and button...
