### ISSUE TITLE
What is $input-height-inner for ?

### ISSUE THREAD

**Issue by MWDavidH** [twbs/bootstrap#25914]
Hi, 

I can't find the use of `$input-height-inner` , `$input-height-inner-sm`, `$input-height-inner-lg` in bootstrap scss files Bootstrap v4.0.0 ?

**Comment by stevebauman** [comment]
You could have resolved this with a quick search in this repository:

https://github.com/twbs/bootstrap/blob/27f553c9651dbe81a8aaf821aa2bf15670d9adb8/scss/_variables.scss#L422-L431

https://github.com/twbs/bootstrap/blob/f81f419b22949d2bf0f4d346891be44724109135/scss/_forms.scss#L61

https://github.com/twbs/bootstrap/blob/f81f419b22949d2bf0f4d346891be44724109135/scss/_forms.scss#L154

https://github.com/twbs/bootstrap/blob/f81f419b22949d2bf0f4d346891be44724109135/scss/_forms.scss#L167

**Comment by MWDavidH** [comment]
I downloaded 4.0.0 with bower.
You are true for `$input-height;`, I use it. Also I didn't find `$input-height-inner`, I made a search without result and can't find it in `_forms.scss`.

**Comment by mdo** [comment]
Those variables are simply for our calculations and shouldn't be modified. They're there in the `v4-dev` branch.
