### ISSUE TITLE
Modal state becomes stuck when toggling rapidly

### ISSUE THREAD

**Issue by joliss** [twbs/bootstrap#25920]
When you toggle a modal programmatically with `$(...).modal('toggle')`, toggling it too rapidly causes the modal state to become "stuck", and the modal will not show anymore. I assume that this happens because the fade-in/fade-out CSS transitions haven't had a chance to finish.

The following JSBin demonstrates this:

https://jsbin.com/suhijuzodu/edit?html,js,console,output

* Click "Run with JS", and then click "toggle every 1000ms". The modal appears and disappears every second as expected.
* Click "Run with JS", and then click "toggle every 250ms". The modal appears and disappears once, and then nothing happens even though `$(...).modal('toggle')` is still being called.

I believe the correct behavior would be to either honor the toggle, or to ignore any toggle that occurs while the modal is still transitioning/animating.

This happens on v4-dev, though the behavior seems to have been present since 3.x at least.

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
