### ISSUE TITLE
Stuck :hover state on carousel controls

### ISSUE THREAD

**Issue by nevez** [twbs/bootstrap#25926]
OS: Lubuntu 16.04.
Browser: Firefox 59 (tested on Chromium v64 too)
Bootstrap: 4.0.0

After clicking carousel controls, it looks like their :hover status gets stuck. I've increased the opacity difference between the two states to make it more visible.

It gets weirder than that: if you move the pointer away from the control you just clicked and then you put the pointer over it again, you can still see a small change in opacity...it's like there are multiple layers below (although it doesn't seem to be the case).

https://output.jsbin.com/qamozozime

**Comment by patrickhlauke** [comment]
it's not `:hover`, it's `:focus` style. once you click a control, it receives focus in the browser. we may implement `:focus-visible` workarounds in future, but for now i'm afraid there's no clean workaround.
