### ISSUE TITLE
Text transform doesn't work on all uppercase.

### ISSUE THREAD

**Issue by caverman11** [twbs/bootstrap#25922]
I tested Text transform on some text that starts out as all capitals and it doesn't camel case the text when you apply class="text-capitalize" to it. It does work if the text is all lowercase. At my work most of the data comes out of the database as in all caps. The workaround is to set it to all lowercase first and then use class="text-capitalize" but it would be nice to have it work when starting out with all caps.

**Comment by browner12** [comment]
this is a limitation of CSS. there's nothing Bootstrap can do about it

https://css-tricks.com/almanac/properties/t/text-transform/#article-header-id-1

**Comment by patrickhlauke** [comment]
and the documentation actually mentions this

> Note how `text-capitalize` only changes the first letter of each word, leaving the case of any other letters unaffected.
