### ISSUE TITLE
Is jumbotron-fluid necessary?

### ISSUE THREAD

**Issue by BrainFeeder** [twbs/bootstrap#25931]
Am I missing something with this `.jumbotron-fluid` class I stumbled upon in the docs?
It says the fluid one will take the entire width of it's parent container. Isn't that what the normal `.jumbotron` does already? `.jumbotron-fluid` has the padding set to zero.. you could respond.. but what's the point if we wrap all the `.jumbotron-fluid` contents inside of a `.container` (as in the docs)?

We could do the same with:

    <div class="jumbotron rounded-0 py-0">
        <div class="container">..some crazy shit content inside..</div>
    </div>

Now what I was looking for, and what would be realy handy (in my opinion), is the `.jumbotron-fluid` to go negative in the margin when wrapped inside a `.container-fluid`. That way we could have all page elements inside a `.container-fluid` and still be able to go edge-to-edge using the `.jumbotron-fluid` 'option'.

If there is a real usecase for the class as it is now, I would love to get some explanation so I can experience that magic myself ;)

Congrats on the bs4 by the way!

**Comment by mdo** [comment]
Jumbotron is a weird one, we'll nuke it entirely at some point. I pulled a ton of it's code out during v4's development before the stable release and left what I felt was enough. The only thing the original `.jumbotron` class has that utilities can't replace right now is a different `padding` scale.
