### ISSUE TITLE
Jumbotron-fluid needs 100% width inside container > row

### ISSUE THREAD

**Issue by pmaojo** [twbs/bootstrap#25937]
![captura de pantalla 2018-03-25 11 49 10](https://user-images.githubusercontent.com/411551/37874198-af1ec904-3022-11e8-9d0a-3fa11010834b.png)
![captura de pantalla 2018-03-25 11 49 02](https://user-images.githubusercontent.com/411551/37874199-af3b4fca-3022-11e8-8ee6-4f97d874db88.png)
![captura de pantalla 2018-03-25 11 48 42](https://user-images.githubusercontent.com/411551/37874200-af57068e-3022-11e8-8bd7-df6a63440f24.png)

width: 100% should be added to .jumbotron-fluid to make this ok

**Comment by mdo** [comment]
Only columns are allowed as direct children of rows. Use the width utility if you must, but I don’t think we need this.
