### ISSUE TITLE
Carousel Not Working with Angular4 Binding

### ISSUE THREAD

**Issue by saurabhzx** [twbs/bootstrap#25938]
Bootstrap Carousel is showing "Cannot read property 'offsetWidth' of undefined" during binding process of Angular4.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by Johann-S** [comment]
@saurabhzx can you provide an example of your issue on https://stackblitz.com ?
