### ISSUE TITLE
Feature request: Alignment of badges and text

### ISSUE THREAD

**Issue by om-mani-padme-hum** [twbs/bootstrap#25932]
First off, let me just say thank you for this awesome project.  It has made my life easier and more successful as this has made my user interfaces look way better.

As for my request, I was using badges for the first time recently and was immediately caught off guard by the vertical alignment of the badges with respect to the text.  It would seem that badges are aligned to the top of text, yet are sized several pixels larger than the corresponding text.  I believe it would be more aesthetically pleasing to have the badge aligned with the center of the text rather than the top.

I know I can make this adjustment myself, and I will for now, but thought it would be more appropriate as the default.  Thanks for your time!

**Comment by mdo** [comment]
You can tweak it with our [`vertical-align` utilities](https://getbootstrap.com/docs/4.0/utilities/vertical-align/).

**Comment by om-mani-padme-hum** [comment]
Roger that, thanks!  Still think it would be better as default, but best part is being able to change it so easily.  Keep up the good work!
