### ISSUE TITLE
justified data-toggle="buttons" shows inputs

### ISSUE THREAD

**Issue by BrainFeeder** [twbs/bootstrap#25943]
https://www.bootply.com/XIslhnwWEk

Using the `btn-group` as justified (with `d-flex` en `w-100`) on a `data-toggle="buttons"` results in the `input`'s being visible. Saw this was a bug in earlier versions. Don't know if this is a known issue?

**Comment by razh** [comment]
In Bootstrap 4.0.0-alpha.3, the styling and JS behavior was decoupled.

> Updated selector for input-based button groups. Instead of `[data-toggle="buttons"] { }` for style and behavior, we use the `data` attribute just for JS behaviors and rely on a new `.btn-group-toggle` class for styling.

https://getbootstrap.com/docs/4.0/migration/#forms

**Comment by BrainFeeder** [comment]
Ah yes :) I should've read the migration page I guess.. Thanks for pointing me to the solution.
