### ISSUE TITLE
Safari - grid doesn't breakline 

### ISSUE THREAD

**Issue by pikl-cz** [twbs/bootstrap#25942]
Hello I found this bug. Safari doesn´t break line with grid - you can see 2 screenshots.

![safaribootstrapbuggridnobreakline](https://user-images.githubusercontent.com/11502547/37898503-40c5f2c6-30e9-11e8-8a69-242a90994452.JPG)
![safaribootstrapbuggridnobreaklineform](https://user-images.githubusercontent.com/11502547/37898633-9e5d05fa-30e9-11e8-90ca-824f04decc01.JPG)

code of form is:
...
 <div class='form-row'><div class='form-group col-lg-6 col-md-6 col-sm-12'>                                     
                                        <label for='contactName'>
                                            Jméno a příjmení <span class="required">*</span>
                                        </label>
                                        <input  type="text" 
                                                value="" 
                                                size="35" id="contactName" name="contactName"
                                                class="form-control">
                                               
                                    </div>
                                    <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                        <label for="contactEmail">Email <span class="required">*</span></label>
                                        <input type="text"
                                               value="" 
                                               size="35" id="contactEmail" name="contactEmail"
                                               class="form-control">
                                    </div>
                                </div>
...

**Comment by Ghost180195** [comment]
Bootstrap 4 does not support Safari for Windows. No one supports this browser.

**Comment by rafalp** [comment]
Safari for Windows is EOL since 2012. That's 6 years ago.

**Comment by pikl-cz** [comment]
thank you for information
