### ISSUE TITLE
Incorrect displaying .row inside .col-auto

### ISSUE THREAD

**Issue by andrii-trush** [twbs/bootstrap#25957]
Bootstrap 4.
OS: Windows 10 (x64)
Browser: Edge

All elements would be in single line without whitespaces and wrap

All are ok in Chrome, Opera, Firefox

Error in Edge (Microsoft Edge 41.16299.248.0, Microsoft EdgeHTML 16.16299)

https://codepen.io/andrii-trush/pen/yKpYVp

**Comment by ejones31** [comment]
This also occurs in MACOS Safari, and Chrome.

**Comment by mdo** [comment]
Doesn't happen with latest Safari, Chrome, or Firefox on Mojave. https://codepen.io/anon/pen/GPjpbb

Will revisit later this week on my Windows PC.

**Comment by MartijnCuppens** [comment]
Hi @andrii-trush, 

The reason the text wraps in some browsers is that they don't handle their widths the same way if negative margins (from `.row`) are applied, there's not much we can do about that. If you don't want the text to wrap, you can make use of the `.text-nowrap` utility class, this should help you out: https://codepen.io/MartijnCuppens/pen/xmWedX
