### ISSUE TITLE
Opening of dropdown scrolls up to top

### ISSUE THREAD

**Issue by felixoi** [twbs/bootstrap#25952]
Given is a fixed navbar with dropdowns. If I scrolldown and click on the dropdown to open it, the page is scrolled up to top before the dropdown is opened.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
Consult the docs again—dropdowns work properly there. https://getbootstrap.com/docs/4.0/components/dropdowns/
