### ISSUE TITLE
BootStrap Example fixed nav bar covers content

### ISSUE THREAD

**Issue by Spadgerian** [twbs/bootstrap#25956]
BootStrap 4 When viewing the fixed nav bar example the expanded menu bar covers part of the content that is supposed to be opened beneath it. This happens when a desktop browser is reduced in width. Happens on Chrome and Firefox when viewing example online from bootstrap and when run on win 10 64 bit laptop running browser-serve and gulp.

**Comment by Spadgerian** [comment]
Sorry got confused with name. Make that the Scrolling Nav bar example. The live preview closes the nav bar after clicking but it doesn't automatic close on my device system.

**Comment by mdo** [comment]
The docs mentioned that fixed navbars will require additional work—there's no way for us to reliably account for this in every user's codebase, so it's up to you.
