### ISSUE TITLE
Sidebar first nav menu hide in firefox in example dashboard project.

### ISSUE THREAD

**Issue by qichunren** [twbs/bootstrap#25959]
Firefox 55.0.2 (64-bit)
https://getbootstrap.com/docs/4.0/examples/dashboard/

![image](https://user-images.githubusercontent.com/39784/38006189-a4ffa974-3276-11e8-87e4-c7eb7b9a2bf6.png)

And in chrome it work right:

![image](https://user-images.githubusercontent.com/39784/38006218-bf3884f0-3276-11e8-802a-e3a65ff5f828.png)

**Comment by mbystryantsev** [comment]
Still reproducing (Mozilla Firefox 60.8.0esr & 68.0).
