### ISSUE TITLE
Freeze popover

### ISSUE THREAD

**Issue by passa1248** [twbs/bootstrap#25950]
Hi all!
I need to show up a popover inside datatable that refresh data every 3 seconds. The problem is that after refreshing, the popover reference is destroyed and popover showed go up to coordinate 0,0 when scroll page. 
Can it be solved? 
Thanks in advance!

Codeply demo https://www.codeply.com/go/y2VQrjqdjf

**Comment by Johann-S** [comment]
Can you provide to us a CodePen or JSBin or Codeply without extra libs just Bootstrap and Popper.js ?

**Comment by passa1248** [comment]
Ok sorry,
this is the demo: https://jsfiddle.net/passa1248/1nd8dgso/1/

**Comment by Johann-S** [comment]
Hmm that's a positionning issue and we use Popper.js for that 🤔 maybe we're not using correctly Popper.js 

/CC @FezVrasta

**Comment by FezVrasta** [comment]
That's not a positioning issue, the reference element gets destroyed and Popper.js doesn't know where to position it anymore.

**Comment by passa1248** [comment]
@FezVrasta  seem that setStyles.js (popper.js/src/utils/setStyles.js) edit transform attribute also after delete the refence element. This is the screen with break on "attribute modifications":
![screen](https://user-images.githubusercontent.com/19681865/37970794-a2392a00-31d4-11e8-9f6c-33637358150a.png)

**Comment by FezVrasta** [comment]
How can you pretend Popper.js to work if you delete the reference element? You should first destroy the Popper.js instance.

Nowhere in the documentation I say that Popper.js can work with a detached/removed reference element.

**Comment by passa1248** [comment]
I do not pretend it but Falcon Heavy must return to base :(
I have resolved removing library and create custom panel myself
https://jsfiddle.net/passa1248/1nd8dgso/50/

**Comment by mdo** [comment]
Closing as not a Bootstrap bug.
