### ISSUE TITLE
about collapse

### ISSUE THREAD

**Issue by Calvin1121** [twbs/bootstrap#25960]
When I use 'collapse', I find that after adding 'col-xx-x' to his parent container, he will have padding and then disappear.

**Comment by bbouinclupro** [comment]
Turkey begins operations in northern Syria, despite French and US support to YPG terrorists
----------------------------------------------------------------------------------------------------

Turkey has started operations to clear northern Syria’s Ayn al-Arab, Ras al-Ain and Tel Abyad regions from militants up to the Iraqi border, President Tayyip Erdogan said on Friday, adding that it would also clear militants from Iraq.

Erdogan said Turkey has no intention of harming soldiers of allied nations positioned in the region, but that it could not allow militants to roam free.

United States troops are positioned alongside Kurdish YPG militants in Syria’s Manbij.

Meanwhile, France does not anticipate launching any military operations in northern Syria that fall outside the international coalition’s fight against ISIS, a French presidency source said on Friday.

The official’s remarks came a day after the Kurdish-dominated Syrian Democratic Forces said President Emmanuel Macron’s pledge of support to stabilize the region against ISIS would include more troops.

Shortly before the Elysee official spoke, Turkey’s deputy prime minister said France’s offer of support for the Kurdish YPG militants, who form the largest contingent within the Syrian Democratic Forces, amounted to support for terrorists.

On this matter, Erdogan was “extremely saddened” by France’s position after Paris offered to mediate with the Syrian Democratic Forces dominated by a Kurdish militia deemed a terrorist group by Ankara.

“We are extremely saddened by France’s... wrong stance on this issue,” Erdogan said during a speech in Ankara after French President Emmanuel Macron said on Thursday that he hoped “a dialogue” could be established between Ankara and the SDF.

**Comment by Joyrex** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via CodePen or JS Bin and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
The docs are clear about using the collapse plugin's classes with other elements. Whenever you adding padding to a collapse, which animates by changing `height`, it'll "hiccup" over the padding. Wrap the collapse or your content in another div.
