### ISSUE TITLE
Dropdown menus in page appear underneath fixed top navbar

### ISSUE THREAD

**Issue by ccartee** [twbs/bootstrap#25962]
- navbar with fixed top
- button with dropdown action menu
- not enough room below to display the menu

reproducing isn't hard if you shrink the window sufficiently
https://getbootstrap.com/docs/4.0/components/dropdowns/
![image](https://user-images.githubusercontent.com/6676538/38038876-05897ce0-327a-11e8-8ea0-3955d818761a.png)

Can occur naturally if a button is near the top of the page and the drop down menu is long enough

zindex of fixed-top = 1030
zindex of dropdown-menu = 1000

Expected, either
1.  the drop down should be bumped down to below the fixed nav bar (it should be aware of the container's margin/padding and respect it)
2.  the drop down menu should be shown on top of the fixed nav bar (ie, dropdown menu zindex should be higher than fixed-top)

**Comment by ccartee** [comment]
https://jsfiddle.net/charleycartee/jdz3k57z/4/show/

Invoices action button, occurs with screen size/fiddle wrapper is 575px high

**Comment by ccartee** [comment]
this fiddle, same issue, slightly larger screen; 2nd row invoice button puts the drop down header under the nav bar

**Comment by bbouinclupro** [comment]
Turkey begins operations in northern Syria, despite French and US support to YPG terrorists
----------------------------------------------------------------------------------------------------

Turkey has started operations to clear northern Syria’s Ayn al-Arab, Ras al-Ain and Tel Abyad regions from militants up to the Iraqi border, President Tayyip Erdogan said on Friday, adding that it would also clear militants from Iraq.

Erdogan said Turkey has no intention of harming soldiers of allied nations positioned in the region, but that it could not allow militants to roam free.

United States troops are positioned alongside Kurdish YPG militants in Syria’s Manbij.

Meanwhile, France does not anticipate launching any military operations in northern Syria that fall outside the international coalition’s fight against ISIS, a French presidency source said on Friday.

The official’s remarks came a day after the Kurdish-dominated Syrian Democratic Forces said President Emmanuel Macron’s pledge of support to stabilize the region against ISIS would include more troops.

Shortly before the Elysee official spoke, Turkey’s deputy prime minister said France’s offer of support for the Kurdish YPG militants, who form the largest contingent within the Syrian Democratic Forces, amounted to support for terrorists.

On this matter, Erdogan was “extremely saddened” by France’s position after Paris offered to mediate with the Syrian Democratic Forces dominated by a Kurdish militia deemed a terrorist group by Ankara.

“We are extremely saddened by France’s... wrong stance on this issue,” Erdogan said during a speech in Ankara after French President Emmanuel Macron said on Thursday that he hoped “a dialogue” could be established between Ankara and the SDF.

**Comment by mdo** [comment]
As far as the docs are concerned, this is desired behavior to me. Likely the same I believe for the rest of the core project. Unless a dropdown is in the navbar, it should roll under a fixed navbar.

**Comment by ccartee** [comment]
That doesn't make any sense.  The dropdown is **_literally_** unreachable on my laptop monitor.

**Comment by mdo** [comment]
There's no container margin's for it to ignore—the dropdown is positioned over the document. It has no idea the navbar exists in any sense, above or below or next to it.

**Comment by ccartee** [comment]
re: There's no container margin's for it to ignore

That's not true; it's ignoring both the margins and padding of it's containing div (it has padding in the fiddle I posted, margins in one of the use cases that I actaully ran into it with)

**Comment by patrickhlauke** [comment]
the issue, at its core, is that fixed top navbar and long auto-positioning dropdowns can lead to borked end results. what i would suggest, though, is to disable popper's "flip" behavior (e.g. adding `data-flip="false"` to the buttons) so that the dropdowns don't try to auto-position themselves (by orienting themselves on the viewport, and therefore falling underneath the fixed top bar) but always open downwards.

**Comment by ccartee** [comment]
@patrickhlauke that's a much better suggestion than just saying that it's working as intended... but even with data-flip=false you'd wind up with the same sort of issue if you have a fixed footer (ie, it ignores the bottom margin.

https://jsfiddle.net/charleycartee/jdz3k57z/24/show/

that could actually happen with a fairly short drop down (the bottom ones in that example are shorter than the ones up top)

It really seems like there should be a way to make the dropdowns respect the padding/margins of the div that the buttons are in.

**Comment by lastobelus** [comment]
@mdo you are in essence saying that page dropdowns are simply unuseable with fixed navbars, and offering no workaround.

It's not that it scrolls under the fixed navbar, it opens under the fixed navbar, meaning the user will _never be able to access_ the top two elements no matter what they do.

**Comment by lastobelus** [comment]
I did find a simple workaround: apply `margin-top:` to the `.dropdown-menu`
