### ISSUE TITLE
Radio and checkbox alignment issue

### ISSUE THREAD

**Issue by pribilinskiy** [twbs/bootstrap#25961]
There's an issue with radio and checkbox alignment when font size is not `1rem`
![image](https://user-images.githubusercontent.com/3078595/38033521-e448e3d4-32a8-11e8-9b7b-0fd5d26ca2c4.png)

Another example with non-custom radios:
![image](https://user-images.githubusercontent.com/3078595/38033541-eec12038-32a8-11e8-9319-7ff5b750569f.png)

Here's an example of proper checkbox/radio rendering in a theme that's based on Bootstrap 4 - [bracket theme](http://themepixels.me/bracket/app/form-elements.html)
![image](https://user-images.githubusercontent.com/3078595/38033695-3fee7c3a-32a9-11e8-8849-2323da5dc556.png)

**Comment by pribilinskiy** [comment]
The difference is in markup and styling:

```
<label class="ckbox">
  <input type="checkbox">
  <span>Checkbox Unchecked</span>
</label>
```

There is one more advantage - no need to specify unique `id` for `input` and `label`

**Comment by bbouinclupro** [comment]
Turkey begins operations in northern Syria, despite French and US support to YPG terrorists
----------------------------------------------------------------------------------------------------

Turkey has started operations to clear northern Syria’s Ayn al-Arab, Ras al-Ain and Tel Abyad regions from militants up to the Iraqi border, President Tayyip Erdogan said on Friday, adding that it would also clear militants from Iraq.

Erdogan said Turkey has no intention of harming soldiers of allied nations positioned in the region, but that it could not allow militants to roam free.

United States troops are positioned alongside Kurdish YPG militants in Syria’s Manbij.

Meanwhile, France does not anticipate launching any military operations in northern Syria that fall outside the international coalition’s fight against ISIS, a French presidency source said on Friday.

The official’s remarks came a day after the Kurdish-dominated Syrian Democratic Forces said President Emmanuel Macron’s pledge of support to stabilize the region against ISIS would include more troops.

Shortly before the Elysee official spoke, Turkey’s deputy prime minister said France’s offer of support for the Kurdish YPG militants, who form the largest contingent within the Syrian Democratic Forces, amounted to support for terrorists.

On this matter, Erdogan was “extremely saddened” by France’s position after Paris offered to mediate with the Syrian Democratic Forces dominated by a Kurdish militia deemed a terrorist group by Ankara.

“We are extremely saddened by France’s... wrong stance on this issue,” Erdogan said during a speech in Ankara after French President Emmanuel Macron said on Thursday that he hoped “a dialogue” could be established between Ankara and the SDF.

**Comment by mdo** [comment]
We're not going to be changing the markup back to the wrapping label. There's another issue open on the placement of the inputs though. Will look into that part.

**Comment by mdo** [comment]
Closing for #25828.
