### ISSUE TITLE
bootstrap 4 tooltip "steals" hover state from table

### ISSUE THREAD

**Issue by kikonen** [twbs/bootstrap#25963]
bootstrap 4:
I'm trying to have tooltips shown for entries inside table. Also same table is needed to have row highlight hovering to clarify context.

Problem:
When tooltip is shown, and user moves mouse, then mouse pointer may enter over tooltip, which "steals" hover state from table. However, when mouse is moved, it isn't actually any longer in hit area for displaying tooltip, thus tooltip disappears and table row receives back hover state. This causes constant flickering, since hover state goes on/off in table rows, since it's temporarily "stolen" by popup tooltip.

At some specific point, hover goes actually into constant on/off flickering (mouse pointer located around the edge of tooltip's trigger area, around the area where tooltip's "triangle leg" is shown. This apparently triggers that tooltip tries to show itself, but detects immediately that it actually shouldn't and hides itself (?!?).

Context:
- v4.0.0
- Encountered with Chrome/Opera

**Comment by kikonen** [comment]
Turning off tooltip arrow and fade animation and adding small show delay effectively fixed issue (i.e. change of hover stealing reasonably is reasonably low).

_variables.scss
```
...
$tooltip-margin:              .4rem !default;
$tooltip-arrow-width:         0 !default;
$tooltip-arrow-height:        0 !default;
...
```

tooltip_init.es6
```
   ...
    $(elem).tooltip({
      animation: false,
      delay: {
        show: 150
      },
      ...
   });
   ...
```

**Comment by bbouinclupro** [comment]
Turkey begins operations in northern Syria, despite French and US support to YPG terrorists
----------------------------------------------------------------------------------------------------

Turkey has started operations to clear northern Syria’s Ayn al-Arab, Ras al-Ain and Tel Abyad regions from militants up to the Iraqi border, President Tayyip Erdogan said on Friday, adding that it would also clear militants from Iraq.

Erdogan said Turkey has no intention of harming soldiers of allied nations positioned in the region, but that it could not allow militants to roam free.

United States troops are positioned alongside Kurdish YPG militants in Syria’s Manbij.

Meanwhile, France does not anticipate launching any military operations in northern Syria that fall outside the international coalition’s fight against ISIS, a French presidency source said on Friday.

The official’s remarks came a day after the Kurdish-dominated Syrian Democratic Forces said President Emmanuel Macron’s pledge of support to stabilize the region against ISIS would include more troops.

Shortly before the Elysee official spoke, Turkey’s deputy prime minister said France’s offer of support for the Kurdish YPG militants, who form the largest contingent within the Syrian Democratic Forces, amounted to support for terrorists.

On this matter, Erdogan was “extremely saddened” by France’s position after Paris offered to mediate with the Syrian Democratic Forces dominated by a Kurdish militia deemed a terrorist group by Ankara.

“We are extremely saddened by France’s... wrong stance on this issue,” Erdogan said during a speech in Ankara after French President Emmanuel Macron said on Thursday that he hoped “a dialogue” could be established between Ankara and the SDF.

**Comment by EvilLooney** [comment]
I have a similar problem. This usually happens when I only have 1 row in my table.

Here's a reduced CodePen of the problem: https://codepen.io/EvilLooney/pen/MVqapM

Problem seems to go away without the `table-sm` or `table-responsive` classes.

Bootstrap: 4.0.0
System: MacOS 10.11.6 (15G19009)
Chrome: Version 65.0.3325.181

**Comment by Johann-S** [comment]
It seems a positioning issue in table here @FezVrasta, do you already know that ? Or I miss something 🤔

**Comment by FezVrasta** [comment]
We have some issues related to tables, please double check if any of them cover your case.

https://github.com/FezVrasta/popper.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+table

**Comment by Johann-S** [comment]
@kikonen it's a Popper.js issue so I'll let you check what FezVrasta answer and how to proceed to help them to fix this issue.

**Comment by kikonen** [comment]
Related to this I noticed additionally also conflict between jquery.floatThead.js and bootstrap 4 tooltip implementation, causing occasionally inifinitely flickering tooltips for cells within "floated" table thead.

Since jquery.floatThead.js should be more-or-less separate from boostrap 4 context (while used in bs4 based layout), it would indicate that issue is more related into popper.js than bootstrap 4.
