### ISSUE TITLE
broken col-md-*

### ISSUE THREAD

**Issue by darkmanAmazigh** [twbs/bootstrap#25975]
Hi,
i try to use bootstrap 4, but it not working fine, 
i want to create too input in same line like this :

    `<!DOCTYPE html>
     <html>
      <head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js" > 
        </script>
	<title>Générateur de jeux de testes DTC</title>
        </head>
        <body>
	<div class="container">
	<div class="row">
	<form class="">
		<fieldset>

			
			<legend>Création d'une ligne ENT</legend>

			
			<div class="form-group">
				
				<div class="col-md-4">
					<input id="idCommunication" name="idCommunication" type="text" placeholder="idCommunication sur 14 digit" class="form-control input-md">
				</div>
				
				<div class="col-md-4">
					<input id="codeEnregistrement" name="codeEnregistrement" type="text" placeholder="codeEnregistrement sur 3 caractère ENT" class="form-control input-md">
				</div>
			</div>
			
			
			<div class="form-group">
				<div class="col-md-4">
					<button id="next" name="next" class="btn">Créer des lignes </button>
				</div>
			</div>
		</fieldset>
	</form>
	</div>
	</div>
</body>
</html>`

in chrome i got this 
https://ibb.co/ikQb9n
<a href="https://ibb.co/ikQb9n"><img src="https://preview.ibb.co/dFMuvS/issue.png" alt="issue" border="0"></a>

the too input isn't in the same row in largest screen

**Comment by mdo** [comment]
You're using the grid classes incorrectly—add `.row` to the `.form-group`.

**Comment by darkmanAmazigh** [comment]
in bootstrap 3, that's work !
