### ISSUE TITLE
.nav Incorrect Safari Prefixes

### ISSUE THREAD

**Issue by Michael-M-Judd** [twbs/bootstrap#25970]
While creating a sidebar I noticed that all browsers except Safari have the same functionality. I figured out the problem was due to the web-kit prefixes being wrong.

**Sidebar in Safari**
![image](https://user-images.githubusercontent.com/17029928/38096603-50018bb0-3341-11e8-9eb8-10a9d09e47a6.png)

**Sidebar in latest version of all other browsers**
![image](https://user-images.githubusercontent.com/17029928/38096670-764e759e-3341-11e8-8a70-a464c7240c1f.png)

In _nav.scss:7 we have 
`.nav {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    padding-left: 0;
    margin-bottom: 0;
    list-style: none;
}`

The display: -webkit-box I think should be display: -webkit-flex; ? Or at least added. Additionally, There's no webkit prefix for flex-wrap. My proposed solution would be:

`.nav {
    display: -webkit-box;
    display: -ms-flexbox;
    display: -webkit-flex /* safari fix */
    display: flex;
    -ms-flex-wrap: wrap;
    -webkit-flex-wrap: wrap; /* safari */
    flex-wrap: wrap;
    padding-left: 0;
    margin-bottom: 0;
    list-style: none;
}`

If someone agrees here I can easily do the PR.

**Comment by mdo** [comment]
This was updated in a recent commit where I rebuilt our dist CSS. Should be good to go with those old Webkit versions of flexbox removed.
