### ISSUE TITLE
btn-group in flex container exhibits spacing

### ISSUE THREAD

**Issue by Joyrex** [twbs/bootstrap#25980]
I was wanting to leverage Flexbox on a column so elements are left- and right-aligned at either end, one of which being a btn-group. Odd spacing between the buttons in the btn-group appear, and I cannot for the life of me figure out what's causing them.

Not sure if this is a potential bug, so I am submitting it here for review: https://codepen.io/Joyrex/pen/xWWYzq

Ignore the extra button set for responsive - that is behaving correctly, and I only included it for completeness.

This was tested in Chrome 64 Windows 10

**Comment by Joyrex** [comment]
@peterblazejewicz - I changed the `d-md-inline` on the `.btn-group` element to `.d-md-inline-flex` as I am assuming you are suggesting and while it gets rid of the spaces, it blows out the alignment of the text on the button elements:
![image](https://user-images.githubusercontent.com/651646/38150243-9515411e-3423-11e8-8334-b42a915039ec.png)

**Comment by mdo** [comment]
Yeah, `inline-flex` will render HTML white-space, which is what you're seeing. Rather than position it inline, try using flex utilities on the parent like `d-flex justify-content-between`.

**Comment by Joyrex** [comment]
@mdo  - but doesn't `.btn-group` inherently use inline?

Also, I'm not using `inline-flex` anywhere in my CodePen; that was what @peterblazejewicz suggested, but as I noted, it blows out the vertical alignment on the buttons that make up the `btn-group`.

Removing the ` d-none d-md-inline` from the `btn-group` and adding the `d-flex justify-content-between` to the `col` DIV creates the same alignment issues as seen above.

Does this basically mean that `btn-group` elements cannot be used in flex containers (or aligned using flex utilities)?

**Comment by mdo** [comment]
Change `.d-md-inline` to `d-md-inline-flex align-self-center`.

**Comment by Joyrex** [comment]
@mdo - Awesome, thank you - works like a charm!

**Comment by mdo** [comment]
No problem! The main issue was that `display: inline` will render that HTML whitespace, but `inline-flex` won't. The behavior you were seeing was the default `align-content: stretch` inherited from the parent flex container, hence the `align-self-center` on the button group. You could also add a similar class to the parent instead, `align-content-center`, if you needed additional control of the content that shares that "row" with the button group.
