### ISSUE TITLE
dropdown toggles content (dropdown menus) not showing when add .show class

### ISSUE THREAD

**Issue by chungbiom** [twbs/bootstrap#26165]
Bootstrap 4 work incorrectly, when add .show class to the .dropdown element, dropdown menus not showing
```
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown">
    Dropdown link
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
```
when add .show class to the .dropdown-menu element, dropdown menus is showing

**Comment by peterblazejewicz** [comment]
You need `show` on the `dropdown-menu` element itself:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_dropdown.scss#L147
The `.dropdown` is provided just to wrap with relative positioned element:
http://getbootstrap.com/docs/4.0/components/dropdowns/#examples

**Comment by chungbiom** [comment]
@peterblazejewicz 
In bootstrap v3.3.7, add **.open** class to the **.dropdown** element, dropdown menus is showing
In bootstrap v4.0.0-alpha.6, add **.show** class to the **.dropdown** element, dropdown menus is showing
[https://v4-alpha.getbootstrap.com/components/dropdowns/](url)
But, in bootstrap 4, add **.show** class to the **.dropdown** element, dropdown menus **not** showing
[https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropdowns](url)

Dropdown menus is showing when add **.show** class to the **.dropdown-menu** element, because it change css code from
```
.show > .dropdown-menu {
  display: block;
}
```
to
```
.dropdown-menu.show {
  display: block;
}
```
I think this feature of previous version very  good
**I don't know bootstrap try to change the css code or missing css code**

**Comment by mdo** [comment]
Dropdowns in v4 are working as intended and there are no planned changes.
