### ISSUE TITLE
Left Fixed Menu Scroll Problem

### ISSUE THREAD

**Issue by mertdogan** [twbs/bootstrap#26166]
Left fixed menu bar is not scrollable when menu height is bigger than page height.

You can check it from your demo: https://blackrockdigital.github.io/startbootstrap-sb-admin/

At previous alpha versions, it was scrollable but not scrollable for latest stable version.

**Comment by patrickhlauke** [comment]
is this related to bootstrap? we don't provide a "left fixed menu bar" style to my knowledge...

**Comment by patrickhlauke** [comment]
https://github.com/blackrockdigital

**Comment by mertdogan** [comment]
I don't know any because of but; this demo menu is scrollable : https://blackrockdigital.github.io/startbootstrap-simple-sidebar/ but this is not : https://blackrockdigital.github.io/startbootstrap-sb-admin/ when browser window height is smaller than menu height.

**Comment by rafalp** [comment]
Those are issues by code from `startbootstrap` by "black rock digital", not by bootstrap itself.

**Comment by mertdogan** [comment]
Ok. What must i change for sb-admin sidebar has scrollbars when there is a height problem?

**Comment by rafalp** [comment]
This is not the place to seek help with `sb-admin`. Please ask on of the repositories belonging to its authors.

**Comment by patrickhlauke** [comment]
...which i pointed at above...
