### ISSUE TITLE
example problem (offcanvas)

### ISSUE THREAD

**Issue by AGhasemzadeh** [twbs/bootstrap#26174]
Hello,
In: https://getbootstrap.com/docs/4.0/examples/offcanvas/
we have nav-scroller which is very useful but it has one problem.
It won't go to active links just it change color while we need to focus on active link.

**Comment by mdo** [comment]
Yup, there's no plans to add this ourselves. We could try to add some custom JS for it, but much of that relies on your own implementations.

**Comment by AGhasemzadeh** [comment]
@mdo Can you give me example JS?
