### ISSUE TITLE
Enhancement: Improve carousel reponsiveness

### ISSUE THREAD

**Issue by udf2457** [twbs/bootstrap#26177]
Hi,

At the moment, unless I'm missing something, the carousel feature in Bootstrap 4 is sorely missing proper responsiveness.

What I mean is that if I have a large/wide images that look great on a desktop/laptop screen, there really should be some proper responsiveness functionality so that smaller images can be substituted when the site is visited on a mobile screen.

**Comment by mdo** [comment]
Swap the images as you need. The tools are there to make this happen with our own CSS `display` utilities, your own server side image solutions, or something like the [`<picture>` element](https://www.html5rocks.com/en/tutorials/responsive/picture-element/).
