### ISSUE TITLE
.scss files missing -webkit and -moz classes

### ISSUE THREAD

**Issue by giantsrg1** [twbs/bootstrap#26187]
I am not sure if I am doing this right but I have a custom-select on my site that is missing all the webkit classes.
![image](https://user-images.githubusercontent.com/12544363/38217890-e812aa6a-369d-11e8-8589-6219111f98ef.png)
![image](https://user-images.githubusercontent.com/12544363/38217942-1c48bafe-369e-11e8-804a-d08dae3e43fd.png)

As you can see in the dev tools the webkit classes are missing.

So I went deeper and looked at the bootstrap.css and the _custom-forms.scss
Bootstrap.css shows:
![image](https://user-images.githubusercontent.com/12544363/38218042-7e52a908-369e-11e8-81f0-023c74efb31f.png)

and _custom-forms.scss shows:
![image](https://user-images.githubusercontent.com/12544363/38218007-656fbad4-369e-11e8-992b-94e933968286.png)

As you can see the -webkit-appearance (and -moz) do not exist. 

Am i doing something wrong?
This is what my custom.scss class looks like(nothing fancy)
![image](https://user-images.githubusercontent.com/12544363/38218095-a95bb31a-369e-11e8-84bf-77c9115a65cf.png)

**Comment by patrickhlauke** [comment]
bootstrap uses autoprefixer as part of its build process - see http://getbootstrap.com/docs/4.0/getting-started/build-tools/#autoprefixer

if you're rolling your own bootstrap from source with a different build chain, you'll need to include it as well.

**Comment by giantsrg1** [comment]
@patrickhlauke Thank you! I knew it was something small I missed.
