### ISSUE TITLE
Simple grid example displays incorrectly in a narrow IE11 window

### ISSUE THREAD

**Issue by PJBaker** [twbs/bootstrap#26186]
Consider the following simple use of the Bootstrap 4 grid - what happens as the `container-fluid` is made narrower?

    <div class="container-fluid">
      <div class="row">
        <div class="col px-0">
          AAAAAAAAAAAAAAAAAAAA
        </div>
        <div class="col px-0">
          BBBBBBBBBBBBBBBBBBBB
        </div>
      </div>
    </div>

In most browsers I've tested, as soon as the `container-fluid` becomes too narrow for the As and Bs to fit side-by-side, the layout changes to stack the As above the Bs. I assume this is the intended behavior.

In IE11, however, when the `container-fluid` becomes too narrow, the As and Bs overlap.

Is there a way to get IE11 to act the same as the other browsers?

https://jsbin.com/nikupifata/1/edit?html,output

**Comment by jonpemby** [comment]
By adding `col-12 col-sm-6` to the classes of the columns, I was able to achieve the desired result on IE11.

I tested on BrowserStack:

<img width="1418" alt="screenshot 2018-04-04 08 48 50" src="https://user-images.githubusercontent.com/8012318/38311547-11dc9868-37e5-11e8-8ec0-156b98b468b8.png">

Hope this helps!

**Comment by mdo** [comment]
Closing as stale and won't fix—this sounds like one of the flex bugs with IE and not something we'd be able to solve at scale.
