### ISSUE TITLE
SCSS Import Problem

### ISSUE THREAD

**Issue by jordanzabar** [twbs/bootstrap#26199]
I'm trying to import @import "node_modules/bootstrap/scss/bootstrap"; in my styles.scss file. When I go to check in my boostrap none of the files are there. The only files that are there package.json and README.md. I'm using Visual Studio Code.

**Comment by browner12** [comment]
I'm not sure if the Bootstrap repo behaves that same as other repos, but traditionally the issues here are reserved for known bugs, or feature discussions.

Something like this, which is most likely just an error with your setup, is more appropriately asked in a forum like StackOverflow, and you'll most likely get a quicker answer there as well.

Thanks,

**Comment by mdo** [comment]
Yup, that's right @browner12. Folks will need more information, too. Code snippets for `package.json`, scripts you're running, versions of node/npm, etc. Ask around in our Slack if you can.

Also, I'm working on a demo repo for building Bootstrap's CSS via npm. More on that soon, but feel free to email me and I can perhaps add you as a collaborator if you think it'd help. Could also give me some early feedback :).
