### ISSUE TITLE
Adding modal-over-modal support

### ISSUE THREAD

**Issue by FuweiChin** [twbs/bootstrap#26191]
**Overview**
First modal's scrollbar doesn't work when opened multiple modal and closed the last.

**Steps to Reproduce**
1. show a modal A
2. show a modal B over modal A,
3. hide modal A

**Actual Result**
Scrollbar doesn't work as expected, the overflow part become not accessible

**Expected Result**
The first modal's scrollbar works as normal.

**Additional Information**
By viewing source code, I found that to show a modal, Modal will do `$(document.body).addClass('modal-open');`, and to hide a modal, Modal will do `$(document.body).removeClass('modal-open');`.

This may also be a feature request called "Adding modal-over-modal support".

**Comment by bkdotcom** [comment]
> This may also be a feature request called "Adding modal-over-modal support".

yup.
see 3rd bullet
http://getbootstrap.com/docs/4.0/components/modal/

**Comment by FuweiChin** [comment]
I fixed it by adding a `"hide.bs.modal"` event listener which adds class `modal-open` and css `padding-right` to `document.body`.  
```
bsModal.on("hide.bs.modal",function(){
	if($('.modal.show').length>0){// if there still are visible modals
		$(document.body).addClass("modal-open").css("padding-right",getComputedStyle(this).getProperty("paddingRight"));
	}
});
```

**Comment by Johann-S** [comment]
Not going to happen, see what @bkdotcom link but thank you

/CC @mdo if you want change your mind on that but I don't think so 😆
