### ISSUE TITLE
Conflict Between Bootstrap and Wordpress

### ISSUE THREAD

**Issue by atef81** [twbs/bootstrap#26190]
I found out this problem a couple of months ago when I started using a Wordpress plugin that depends on Bootstrap.
The problem is that whenever I use Bootstrap elements in Wordpress, I get every element showing on a separate line, like this screenshot:
[prntscr.com/j02ys6](url)

After extensive research in this point, I found out that that there is a conflict between Wordpress and Bootstrap.

Wordpress simplifies the text editing process by introducing invisible line breaks `< /br>` after each line. When Using Bootstrap elements (e..g buttons) with Wordpress, a line break `< /br>` gets introduced after each button code, leading them to appear one button per line, like the screenshot.

Wordpress has a function to stop adding the line breaks and paragraph tags, `remove_filter( 'the_content', 'wpautop' );`but when used, it solves the problem with Bootstrap, but corrupts all text in the Wordpress posts that is inserted without proper html markup. So it is not a viable solution.

I posted 2 posts on Stack Exchange to try to find a solution, but no one came up with a solution:
post 1: [https://stackoverflow.com/questions/48115844/how-to-show-bootstrap-buttons-inline-instead-of-one-per-line-in-wordpress-specif](url)
Post 2: [https://stackoverflow.com/questions/49621836/how-to-create-a-shortcode-edit-a-function-to-solve-the-conflict-between-bootstra](url)

Given that both Bootstrap and Wordpress are 2 major and key players in the web development world today, I am just wondering if there is any solution? I believe that I am not the first person to use Bootstrap in Wordpress?

Any solution is much appreciated. I have been stuck for months.
Thanks in Advance.

**Comment by Johann-S** [comment]
It doesn't seems an Bootstrap issue, you should ask on WordPress, because I don't think we can handle that use case

/CC @mdo

**Comment by jonpemby** [comment]
@atef81 I think I can help you, can you DM me on Twitter or send me an email?

[@jonpemby](https://twitter.com/jonpemby) [Email](mailto:jonpemby@icloud.com)

**Comment by mdo** [comment]
Agreed, not a Bootstrap issue.
