### ISSUE TITLE
Mistake on gray variable - SCSS v4

### ISSUE THREAD

**Issue by JAGFx** [twbs/bootstrap#26195]
When i want to extend and build bootstrap v4 with SCSS files, i can't beacause i've an `undefined $grey-800` error.

On `bootstrap/scss/_variables.scss`, i can't find the "$grey-800".

```scss
$gray-100: #f8f9fa !default;
$gray-200: #e9ecef !default;
$gray-300: #dee2e6 !default;
$gray-400: #ced4da !default;

$gray-600: #6c757d !default;
$gray-700: #495057 !default;
$gray-500: #343a40 !default; // Here is the mistake
$gray-900: #212529 !default;
```

It's already patch in the next version ?

**Comment by MartijnCuppens** [comment]
It's `$gray-800` not `$grey-800`, maybe that's your problem?

**Comment by patrickhlauke** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L20
