### ISSUE TITLE
_input_group.scss fails to compile without _forms.scss

### ISSUE THREAD

**Issue by alecho** [twbs/bootstrap#26209]
Error when not importing `scss/_forms.scss` but importing `scss/_input_group.scss`.

I was under the impression that we could create custom builds by importing the necessary modules "a la carte". Having one depend on the other is a little unexpected.
```
Error: ".input-group-lg > .form-control" failed to @extend ".form-control-lg".
       The selector ".form-control-lg" was not found.
       Use "@extend .form-control-lg !optional" if the extend should be able to fail.
        on line 124 of node_modules/bootstrap/scss/_input-group.scss
>>   @extend .form-control-lg;
   ----------^
```
https://github.com/twbs/bootstrap/blob/4880385b8f22261ca4946ef9568b61ba8f0500c5/scss/_input-group.scss#L124

Happy to open a PR if the suggested fix of appending `!optional` is indeed correct.

**Comment by mdo** [comment]
Button groups and input groups are the only places we extend from outside the Sass file. Probably need to document that, or figure out an alternate approach. I don't think an `!optional` flag is right.
