### ISSUE TITLE
CSS variables in media queries: clarification?

### ISSUE THREAD

**Issue by smlombardi** [twbs/bootstrap#26205]
The 4.1 docs currently say

> While we include breakpoints in our CSS variables, they unfortunately cannot be used in media queries. 

What, exactly, does that mean? The "they" is ambiguous.  Do you mean you can't use variables _as_ media queries, as in
```
@media (min-width(var(--breakpoint-sm))) {
  .content-secondary {
    display: block;
  }
}
```

or is it the combination that won't work:

```
@media (min-width(var(--breakpoint-sm))) {
  .some-class {
    color: var(--primary);
  }
}
```

or that you can't use a variable  _in a standard media query_, as in

```
@include media-breakpoint-up(sm) {
  .some-class {
    color: var(--primary);
  }
}
```

Big difference to me.

**Comment by mdo** [comment]
Yes, this is what isn't supported (though your syntax is also wrong):

```
@media (min-width(var(--breakpoint-sm))) {
  .content-secondary {
    display: block;
  }
}
```

And this is what is supported (with syntax corrected):

```
@media (min-width: 768px)) {
  .some-class {
    color: var(--primary);
  }
}
```

And finally, I don't think you'd want to mix Sass with CSS variables. I'd steer clear of that last example.
