### ISSUE TITLE
btn rendering issues between Chromium and Firefox

### ISSUE THREAD

**Issue by boardfish** [twbs/bootstrap#26204]
On my personal site, [simon.fish](https://simon.fish), most things seem a-okay. However, my buttons (using `<a>`) render differently between Chrome/Chromium (tested on Linux and Windows) and Firefox (tested on Linux). Buttons on Chrome render without the border radius applied and with a small black border. Skews apply as intended, slanting the buttons while keeping their text upright.

This seems purely visual - the right attributes are inherited according to developer tools, so I can only think it's a Chrome-specific issue.

As an additional issue, links in the cards aren't clickable on Chrome. This can be fixed by taking the cards out of a `card-columns` div for reasons unknown.

**Comment by patrickhlauke** [comment]
for the buttons...there's to `type="button"` on links. that's invalid markup https://validator.w3.org/nu/?doc=http%3A%2F%2Fsimon.fish%2F

but in general: we can't help you with specific uses of bootstrap. if you suspect there's a bug in bootstrap itself, please provide a clean reduced test case (in jsfiddle, bootply or similar) showing the problem.

**Comment by boardfish** [comment]
Those used to be buttons - I think I forgot to remove that attribute. Thanks for spotting that, it'll help big time!
