### ISSUE TITLE
Typeahead option : Typeahead_append_to_body

### ISSUE THREAD

**Issue by SahnounM91** [twbs/bootstrap#26203]
typeahead-append-to-body won't display the suggest list in width of the whole page not only in the width of the modal !

**haml file :** 

```
.modal-body
  %tabset.specification-template-tabset
    %tab{ heading: "{{ 'modal.specification_template.specification' | translate }}" }
      .row
        .col-md-4
          %label{ translate: 'modal.specification_template.name' }
          %am_mandatory_field
        .col-md-8
          %input.specification-template-name{ type: 'text', typeahead_append_to_body:'true', typeahead: 'name for name in names | filter:$viewValue | limitTo:15',
                        ng: { model: 'specificationTemplate.name', disabled: 'contractPeriod.isArchived()' }}
```

**sass code :** 
```
@import "mixins/mixins.sass"

.modal-contract-specification
  .specification-template-tabset
    +tabset( inherit )

  textarea
    min-height: 140px !important
    width: 100%
  input.specification-template-name
    width: 100%
  .dropdown-menu
    z-index: 9999

```

![selection_024](https://user-images.githubusercontent.com/10802803/38376060-a792e8ac-38ef-11e8-9441-34817f4cf333.png)
![selection_023](https://user-images.githubusercontent.com/10802803/38376062-a7c3343a-38ef-11e8-84ec-838d6c7be3b6.png)

I don't understand why the selection list don't appear in the front of modal with the whole page width ! help !

**Comment by patrickhlauke** [comment]
typeahead stuff hasn't been part of bootstrap for more than 5 years...so i'm afraid we can't help you there.
