### ISSUE TITLE
Two types of column structure with same grid

### ISSUE THREAD

**Issue by muhammadrizwans** [twbs/bootstrap#26207]
How can I have two different column structure in the same grid layout with bootstrap 4
For example, I need to have 12 columns base structure in desktop and 6 columns structure in tablet and mobile.

**Comment by andresgalante** [comment]
Hi @muhammadrizwans 

You can't change the base column template, but you can control the size of your columns and have the same effect. Read about [how to implement a responsive grid here](http://getbootstrap.com/docs/4.0/layout/grid/#mix-and-match).

If there is a specific use case where you need a 6 column template that Bootstrap grid can't acomodate please send me a codepen or example.

**Comment by mdo** [comment]
Closing per last comment.

**Comment by muhammadrizwans** [comment]
Hi @andresgalante 
I have a structure as below
https://stackoverflow.com/questions/49674754/how-can-i-have-different-column-structure-with-bootstrap-4

Please have look and advice what can be altered to have 12 columns grid in md and above while 6 column grid in sm and below.

Thanks
