### ISSUE TITLE
Hover menu suggestion

### ISSUE THREAD

**Issue by vosidiy** [twbs/bootstrap#26223]
Hi folks, this is not an issue but recommendation. (I don't know where to post)
So, most people requested for hover menu. 
I made a simple example of hover menu based on (@media query)  by adding .hover class which works only for desktop.
Here is I am sharing 
https://codepen.io/vosidiy/pen/ZxVjLr 

It would be good for many people if authors include this feature in the future versions.

**Comment by midzer** [comment]
Hi @vosidiy and welcome to GitHub.
This issue has been answered several times already. Use the search functionality for more info.

Nevertheless, you can implement this feature for yourself on your site https://stackoverflow.com/questions/8878033/how-to-make-twitter-bootstrap-menu-dropdown-on-hover-rather-than-click#comment14236825_8878033

**Comment by mdo** [comment]
No plans to add hover menus at this time.
