### ISSUE TITLE
Custom Control Checkbox not working without label

### ISSUE THREAD

**Issue by petewulf** [twbs/bootstrap#26221]
When ommitting the label tag in a custom-control-input, the checkbox is not showing up

```
<div class="custom-control custom-radio">
  <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
</div>
```

Sometimes one would need a styled checkbox without a label, especially when working with selection lists or tables.

**Comment by FrancisStat** [comment]
Yup i got the same problem. I have a table of radio buttons and the label is in the table column headers. The custom radio don't show up if there's no label.

`<div class="custom-control custom-radio" role="group">
    <input type="radio" name="quest-27" id="quest-27-10" class="custom-control-input position-static" aria-label="Never" value="1">
</div>`

**Comment by jipexu** [comment]
why omitted the tag ? you can let the label text  empty or use sr-only ?

**Comment by FrancisStat** [comment]
@jipexu it doesn't work either is you add the `sr-only` class to the label. En empty label element with the class `custom-control-label` works but it's kind of a hack ...

**Comment by jipexu** [comment]
you noticed this for the 4.0 and 4.1 ?

**Comment by FrancisStat** [comment]
I'm on 4.0.0 right now which is the last version published on npm.

**Comment by jipexu** [comment]
i use this method empty label in several context ... probably not the best way but found only this one

**Comment by FrancisStat** [comment]
I just updated to 4.1.0 and still not showing up. I guess i'll have to use en empty label for now. Here'S what i did i think it's probably cleaner than an empty label :+1: 

```
<div class="custom-control custom-radio" role="group">
    <input 
        type="radio" 
        name="quest-27" 
        id="quest-27-10" 
        class="custom-control-input position-static"
        value="1">
    <label class="custom-control-label">
        <span class="sr-only">Never</span>
    </label>
</div>
```

**Comment by petewulf** [comment]
My version is 4.0.0 published on npm.

Working with empty labels is working, but thats not a good practice as it results in unneeded code overhead.

**Comment by FrancisStat** [comment]
I looked the css code and i don't think it's an issue. It's actually by design. The `custom-control-label` class basically attaches a fake control to the label and when you click that fake control you in fact click the label since it's part of it and when you click a label in a browser it clicks the checkbox or radio button. You can do fake on/off slider with the same technic. Of course can't work if there's no label. So to make it works they would need to use a new _hack_.

**Comment by AndyCJ** [comment]
The custom checkbox is also off-center when used with a blank label.

https://jsfiddle.net/wkewpegp/8/

**Comment by AndyCJ** [comment]
@FrancisStat 

Thank you for the suggestion, that worked a treat. I'll pop a helper class in to our SASS to cover this usage.

I agree you want a label when making a "classic" form layout for sure.
Two fairly mainstream "alternative" uses would be a checkbox in a Table cell where the column header is the label, or on a panel where you're indicating your selecting what the entire panel represents.

**Comment by mdo** [comment]
Docs explain how these are built—the `<label>` element with `.custom-control-label` is used to generate the custom "checkbox". The only way around this, which isn't ideal given there's no label to explain the element, is another element with that class. Example: https://jsbin.com/hoxuvuteza.

**Comment by cichy380** [comment]
This problem starts from Bootstrap v4.1.1 (https://github.com/twbs/bootstrap/pull/25944)

**Comment by Thomas-Obale** [comment]
The problem is the label. Try

`.custom-control-label::after {
display: none;
}`

**Comment by Omi0** [comment]
I've checked and checked and checked all over again and realized that I've forgotten to put for attribute to the label...

**Comment by DiegoAndresCortes** [comment]
Checkboxes doesn't work properly for 'mass' checking.
E.g. If I have a table/list with checkboxes it can't get the "id" of the main checkbox because there's none for the label

**Comment by anthonyadamski** [comment]
Suggesting we reopen this. When hiding label using the "text-hide" method, checkboxes are still off centered due to the padding that exists to offset the label from the checkbox.

**Comment by futhr** [comment]
```scss
.custom-control {
    padding-left: 0;

    .custom-control-label {
      // set same width/height as before and after
      width: 1em; 
      height: 1em;

      &::before,
      &::after {
        left: 0;
      }
    }

    .custom-control-input {
      display: none; // optional
    }
  }
```

**Comment by JohnRostislavovich** [comment]
The problem is, that You have to use label **"for"** attribute, and id for input, because it triggers the script

**Comment by setezerocinco** [comment]
This worked 100% for me. Checkbox is there without label:
```
<div class="custom-control custom-checkbox mr-sm-2">
    <input id="FieldName" type="checkbox" class="custom-control-input" />
    <label for="FieldName" class="custom-control-label">
        <span class="sr-only"></span>
    </label>
</div>
```
