### ISSUE TITLE
linux emoji and adding 'noto color emoji' to the font stack

### ISSUE THREAD

**Issue by client9** [twbs/bootstrap#26227]
With Ubuntu 18.04 and Fedora 28 brings full color emoji support to Linux.  By adding "Noto Color Emoji" the end of the bootstrap font stack should improve linux support.

Firefox uses some internal emoji font for rendering, but it isn't what the system uses (meaning, if you cut-n-paste emoji from firefox into terminal, it will look differently).  Chrome  seems to use "Noto Color Emoji" automatically.

Attached is screen shot on firefox before and after adding "Noto Color Emoji" with various defaults.  It's "better" but not perfect since some of the default fonts contain B/W emoji.  That can only be fixed by more complicated @font-face and unicode-range hacks and don't recommend it.

<img width="421" alt="screen shot 2018-04-06 at 7 41 29 am" src="https://user-images.githubusercontent.com/217179/38514835-28eee3d4-3be7-11e8-87e7-adacdc74d7d5.png">

This was generated from https://codepen.io/client9/pen/qoJoZW and some other  https://www.client9.com/css-color-emoji-stack/

thoughts?  Maybe not a big enough problem to justify the change. 

Regards,

n

**Comment by XhmikosR** [comment]
Feel free to make a PR and link to this.
