### ISSUE TITLE
Carousel jerking issue in IE 11 browser

### ISSUE THREAD

**Issue by sajithchandra** [twbs/bootstrap#26220]
Found an issue in the bootstrap carousel. When we are in IE 11 browser, the entire bootstrap carousel is moving left and right (jerking) while clicking on the next, previous buttons multiple times. Please fix this issue as soon as possible. 

Thanks & regards by Sajithchandra.

**Comment by Johann-S** [comment]
Related to: https://github.com/twbs/bootstrap/issues/25900
