### ISSUE TITLE
text-hide() warning message

### ISSUE THREAD

**Issue by arechsteiner** [twbs/bootstrap#26237]
When building the new 4.1 scss source code, I get the following warning message:

```bash
alex@ubuntuVM:~/code/bootstrap-41/scss$ scss bootstrap.scss  bootstrap.css
WARNING: The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.
         on line 10 of mixins/_text-hide.scss, in `text-hide'
         from line 57 of utilities/_text.scss
         from line 14 of _utilities.scss
         from line 41 of bootstrap.scss
```

It seems text-hide() ist still used in https://github.com/twbs/bootstrap/blob/v4.1.0/scss/utilities/_text.scss#L57

**Comment by XhmikosR** [comment]
Yes, but it's deprecated; that is the whole point of the warning message. :)

**Comment by arechsteiner** [comment]
I feel like the vanilla Bootstrap source code shouldn't spawn warning messages about itself.

I have some projects where I build custom versions of Bootstrap and they all spawn warnings now even though I'm not using `text-hide()` and am perfectly innocent. 😇

**Comment by XhmikosR** [comment]
Yeah unfortunately that is correct.

I'm not sure if it's technically possible to achieve what we want without
removing the actual mixin call and atill show the warning.

If your anyone else finds a way, let us know.

**Comment by arechsteiner** [comment]
One solution I can think of:

Mixin:
```scss
@mixin text-hide($ignoreWarning: false) {
  ...
  @if ($ignoreWarning == false) {
    @warn "The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.";
  }
}
```

Usage in `_text.scss`
```
.text-hide {
  @include text-hide(true);
}
```

This will spawn a warning for normal use of `text-hide()` but gives the option to suppress the warning.

**Comment by XhmikosR** [comment]
Hmm, nice approach. Can you make a PR and CC me?

**Comment by arechsteiner** [comment]
Will do, give me half an hour.

**Comment by arechsteiner** [comment]
Done here: https://github.com/twbs/bootstrap/pull/26242

**Comment by TheSharpieOne** [comment]
Usually when there is a deprecation warning about something being going to be remove, the package itself doesn't use that thing. Typically I see the package migrating to the new preferred usage, and others can use commit as an example way to migrate any of their own usage.
It seems like bootstrap is planning on removing something and are not quite sure what to do when it gets removed.

**Comment by Merovex** [comment]
I just commented out the warning...since I don't use the feature. ;)
