### ISSUE TITLE
Separate npm package for sass | css only

### ISSUE THREAD

**Issue by anjmao** [twbs/bootstrap#26233]
Hi, It would be really useful to be able to install only sass | css module. Why you may ask. Currently bootstrap depends on jQuery and popover which are listed in peerDependencies, but when installing bootstrap I don't want to install jquery just to get rid of npm warnings. In fact I don't remember last time when I was using jQuery.

**Comment by Johann-S** [comment]
Related to: https://github.com/twbs/bootstrap/issues/23557 
please before openning an issue take time to search in our openned issues
