### ISSUE TITLE
Fix class in the example code for text-monospace in docs v4.1

### ISSUE THREAD

**Issue by abhitalks** [twbs/bootstrap#26235]
Utilities > Text > Monospace

The docs say, "_Change a selection to our monospace font stack with .text-monospace._", describing the use of the class `.text-monospace`.

However, the code in the example uses the class `.font-monospace` as in `<p class="font-monospace">This is in monospace</p>`.

**Comment by XhmikosR** [comment]
Probably a leftover.

PRs welcome.

**Comment by Laxmi-Thrylokya** [comment]
Thank you. font-monospace is working
