### ISSUE TITLE
Use Chrome on Android for our unit tests

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#26236]
In Sauce Labs, currently we run our unit test on Android stock browser, which is not a supported browser of Bootstrap, so we should test on Chrome for Android.

Related:
- https://wiki.saucelabs.com/display/DOCS/2017/03/31/Android+6.0+and+7.0+Support+Released
- https://travis-ci.org/twbs/bootstrap/jobs/364476658#L820

**Comment by XhmikosR** [comment]
@Johann-S: isn't this fixed now?

**Comment by Johann-S** [comment]
you're right, it's fixed since we use BrowserStack 👍
