### ISSUE TITLE
Should table really set margin-bottom?

### ISSUE THREAD

**Issue by swrobel** [twbs/bootstrap#26230]
Out of curiosity, why do tables have [margin-bottom](https://github.com/twbs/bootstrap/blob/v4.1.0/scss/_tables.scss#L8) by deafult? It seems like it's been in the source forever, so I guess that's how it's always been, and it can't be changed, yada yada, but it still makes me morbidly curious...

Could this possibly be changed in the future?

**Comment by Joyrex** [comment]
Wouldn't `.mb-0` on the `table` tag work?

**Comment by swrobel** [comment]
Yes, I end up putting it on all of my tables, hence the question. It seems like an odd default.

**Comment by mdo** [comment]
We do this because we consider tables part of web content, much like body paragraphs or headings, which also share a `margin-bottom`. We could revisit in the future, but I think this should stick around for v4.

**Comment by swrobel** [comment]
@mdo wondering if you'll reconsider this for v5 now that work is in progress?
