### ISSUE TITLE
Release v4.1 isn't available in npm

### ISSUE THREAD

**Issue by Sibiraj-S** [twbs/bootstrap#26231]
~~Release v4.1 isn't available in npm~~

It is there, but `npm install` still installs v4.0

**Comment by Sibiraj-S** [comment]
<strike>Release v4.1 isn't available in npm</strike>

It is there, but `npm install` still installs v4.0

**Comment by XhmikosR** [comment]
@mdo: you have marked 4.1.0 as `next`. It should be as latest.

**Comment by XhmikosR** [comment]
https://docs.npmjs.com/cli/dist-tag

**Comment by johnunclesam** [comment]
![image](https://user-images.githubusercontent.com/21275217/38557821-8b1eeb8e-3cce-11e8-9def-86700e2babba.png)

**Comment by mdo** [comment]
Should be all cleared up now!

**Comment by mdo** [comment]
@XhmikosR Heads up, I opened a PR in our team repo to fix my shipping doc so I don't screw this up next time :).
