### ISSUE TITLE
Question: Bootstrap 4.1 - custom-file-label wrong ::after?

### ISSUE THREAD

**Issue by knoobie** [twbs/bootstrap#26232]
Hey guys, I was updating our 4.0 instance and was checking the delta and was wondering if this was an error?

https://github.com/twbs/bootstrap/blob/8dd1fe38932c47d9aa93e401aa1fc65f26207add/scss/_input-group.scss#L51

https://github.com/twbs/bootstrap/blob/8dd1fe38932c47d9aa93e401aa1fc65f26207add/scss/_input-group.scss#L49

especially the line above was ::after as well. Shoudn't it be: ::before if you address the left border? or am I missing something obvious here?

**Comment by ysds** [comment]
Good catch.

https://github.com/twbs/bootstrap/blob/8dd1fe38932c47d9aa93e401aa1fc65f26207add/scss/_input-group.scss#L51

>  Shoudn't it be: ::before if you address the left border?

No, `.custom-file-label::before` element does not exist.

So, is `.custom-file-label::after` correct? No. The left border of `.custom-file-label::after` never rounds.

We can remove the Line 51.
