### ISSUE TITLE
Add cusom range input control

### ISSUE THREAD

**Issue by ratajs** [twbs/bootstrap#26241]
Can you add custom `<input type="range">` to v4.2?

**Comment by mdo** [comment]
Was just added yesterday! https://getbootstrap.com/docs/4.1/components/forms/#range :)

**Comment by agustinhaller** [comment]
Hi @mdo, are you considering adding multi-range support? I think it's a super useful feature and key to many use cases. Maybe this [tiny polyfill](https://github.com/LeaVerou/multirange) will do the trick.
