### ISSUE TITLE
The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.

### ISSUE THREAD

**Issue by iPazooki** [twbs/bootstrap#26246]
Hi
  After updating to Version 4.1.0. When I wanna compile my SCSS files I get this error: 
 `The "text-hide()" mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.`
But when I comment `.text-hide` class in _text.scss every things go fine and there is no issue!

**Comment by mdo** [comment]
It shouldn't be an error, it should be a warning, which shouldn't affect compilation. The mixin was deprecated with v4.1 and was mentioned in our blog post.

**Comment by casdevs** [comment]
ok, but shouldn't bootstrap itself not use `@include text-hide()` any longer then?
it's still included from line 57 of ./scss/utilities/_text.scss, so users get the deprecation warning even if they are not using text-hide() themselves anymore...

**Comment by RobertSmits** [comment]
@casdevs True, but then the precompiled version wouldn't include .text-hide which can break sites using the precompiled bootstrap css or a cdn. And semantic versioning says you can only make breaking changes if you bump the major version.

**Comment by casdevs** [comment]
@RobertSmits ok, without further investigation I've assumed that internally, there is an alternative to the now deprecated text-hide mixin so bootstrap itself can set a good example of how to avoid using this deprecated feature now. I've just wondered why compiling bootstrap without further modifications issued a warning now.

**Comment by wolfy1339** [comment]
This will be fixed in v4.1.1 (Fix committed to v4-dev)
In the mean time, you can't do very much about it.

**Comment by wlipa** [comment]
Great, thanks!  I see this now:

https://github.com/twbs/bootstrap/pull/26242

**Comment by vladanPro** [comment]
I have same problem also in v4.1.1 ?

**Comment by wolfy1339** [comment]
Can you confirm that you are using v4.1.1?
What does the actual `text-hide()` mixing look like?

**Comment by vladanPro** [comment]
I am sorry i use "bootstrap-material-design": "4.1.1" but not bootstrap. So i update and now i don't have problem. Thank you.

**Comment by suniLPATIDARr** [comment]
I am using core ui template of react and facing same issue none of given solution worked for me  "@coreui/coreui": "^2.0.1",
