### ISSUE TITLE
Text Monospace Documentation Issue

### ISSUE THREAD

**Issue by jnaquin** [twbs/bootstrap#26251]
The new bootstrap 4.1 release introduced a new text utility for monospacing (.text-monospace) which can be found here https://getbootstrap.com/docs/4.1/utilities/text/#monospace.

The documentation says to use the css class of .text-monospace but the example directly below is incorrect because it using the wrong class of .font-monospace.

![image](https://user-images.githubusercontent.com/17296768/38581646-133220b4-3cd3-11e8-911f-54223e90a828.png)

Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by huphtur** [comment]
fixed in #26235
