### ISSUE TITLE
How to run npm install ?

### ISSUE THREAD

**Issue by michaelanhvu83** [twbs/bootstrap#26253]
=== Bootstrap Guide ===
Tooling setup
Bootstrap uses NPM scripts for its build system. Our package.json includes convenient methods for working with the framework, including compiling code, running tests, and more.

To use our build system and run our documentation locally, you’ll need a copy of Bootstrap’s source files and Node. Follow these steps and you should be ready to rock:

Download and install Node.js, which we use to manage our dependencies.
Navigate to the root /bootstrap directory and run npm install to install our local dependencies listed in package.json.
=== Bootstrap Guide ===

I'm downloaded and Installed NodeJS, but i run "npm install", it's show me an error like this picture.

How can i fix that ?

![sketch](https://user-images.githubusercontent.com/16274116/38587692-975a2750-3d4c-11e8-9fe4-34307ce85b96.png)

Tks you.

**Comment by michaelanhvu83** [comment]
No. I have installed Python.
And add variable like this:
C:\Users\micha\AppData\Local\Programs\Python\Python36-32\python.exe
C:\Users\micha\AppData\Local\Programs\Python\Python36-32\Scripts\
C:\Users\micha\AppData\Local\Programs\Python\Python36-32\
Don't know i have setup wrong path ?

**Comment by TrejGun** [comment]
can you please check if this file actually exists
`C:\Users\micha\AppData\Local\Programs\Python\Python36-32\python.exe`

**Comment by XhmikosR** [comment]
Python is not needed. I just tried it on my dev VM after clearing npm's global cache and works fine.

```
C:\Users\xmr\Desktop\bootstrap>ver

Microsoft Windows [Version 6.1.7601]

C:\Users\xmr\Desktop\bootstrap>node -v && npm -v
v8.11.1
5.6.0

C:\Users\xmr\Desktop\bootstrap>npm i

> uws@9.14.0 install C:\Users\xmr\Desktop\bootstrap\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> iltorb@1.3.10 install C:\Users\xmr\Desktop\bootstrap\node_modules\iltorb
> detect-libc prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\iltorb-v1.3.10-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\xmr\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MayhemYDG-iltorb-releases-download-v1.3.10-iltorb-v1.3.10-node-v57-win32-x64.tar.gz
prebuild-install http request GET https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v57-win32-x64.tar.gz
prebuild-install http 200 https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v57-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\xmr\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MayhemYDG-iltorb-releases-download-v1.3.10-iltorb-v1.3.10-node-v57-win32-x64.tar.gz.2280-af58701333db7.tmp
prebuild-install info renaming to @ C:\Users\xmr\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MayhemYDG-iltorb-releases-download-v1.3.10-iltorb-v1.3.10-node-v57-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\xmr\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MayhemYDG-iltorb-releases-download-v1.3.10-iltorb-v1.3.10-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\xmr\Desktop\bootstrap\node_modules\iltorb\build\bindings\iltorb.node
prebuild-install info unpack required C:\Users\xmr\Desktop\bootstrap\node_modules\iltorb\build\bindings\iltorb.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> node-sass@4.8.3 install C:\Users\xmr\Desktop\bootstrap\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-57_binding.node
Download complete  ] - :
Binary saved to C:\Users\xmr\Desktop\bootstrap\node_modules\node-sass\vendor\win32-x64-57\binding.node
Caching binary to C:\Users\xmr\AppData\Roaming\npm-cache\node-sass\4.8.3\win32-x64-57_binding.node

> node-sass@4.8.3 postinstall C:\Users\xmr\Desktop\bootstrap\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\xmr\Desktop\bootstrap\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> nodemon@1.17.3 postinstall C:\Users\xmr\Desktop\bootstrap\node_modules\nodemon
> node -e "console.log('\u001b[32mLove nodemon? You can now support the project via the open collective:\u001b[22m\u001b
[39m\n > \u001b[96m\u001b[1mhttps://opencollective.com/nodemon/donate\u001b[0m\n')" || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate


> sinon@4.5.0 postinstall C:\Users\xmr\Desktop\bootstrap\node_modules\sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

npm WARN bootstrap@4.1.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies y
ourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1511 packages in 90.524s

```

**Comment by michaelanhvu83** [comment]
Yep. Look like wrong path. Install Python ver 2.7, and work fine.
Tks all.

**Comment by XhmikosR** [comment]
You don't need Python...

**Comment by michaelanhvu83** [comment]
Don't run if don't have Python.
View image below.
![sketch](https://user-images.githubusercontent.com/16274116/38746001-74ff5132-3f70-11e8-9e2e-4957cadfd5dd.png)

**Comment by michaelanhvu83** [comment]
I just reinstall windows. It's very clean. That's the clean source download from bootstrap. I don't think it error or something. I'm feel confused.

**Comment by XhmikosR** [comment]
What console is that?

**Comment by michaelanhvu83** [comment]
@XhmikosR PowerShell.
I think if you download bootstrap source and using sass. We have two step.
1. Install python version 2.7 ( depend on your windows os is x86 or x64 )
2. Install windows-build-tools from npm with command: npm install --global windows-build-tools.
Done.

**Comment by XhmikosR** [comment]
I use plain Windows CMD and works fine without Python. I do have Visual Studio installed but as you can see from above, the binaries are downloaded prebuilt, so VS isn't used.

Anyway, as long as it worked for you. Just know that you are doing something weird because all this shouldn't be needed...

**Comment by beuss** [comment]
@XhmikosR it seems that you've to install windows-build-tools to get it working, just experienced the same issue. No prebuilt binary are downloaded because latest node looks for v67 which has no prebuilt binary.
Thanks to @michaelanhvu83 I didn't lose the whole day on it
