### ISSUE TITLE
Release 4.1.0: index.js header reports v4.0.0

### ISSUE THREAD

**Issue by volans-** [twbs/bootstrap#26250]
Minor nitpick, it seems that the 4.1.0 release of Bootstrap didn't bump the version of `js/src/index.js`, that is still reporting:

```
 * Bootstrap (v4.0.0): index.js
```

This header line appears also in the following files, that I think are derived from the one in `src`:
- `js/dist/index.js`
- `dist/js/bootstrap.js`
- `dist/js/bootstrap.bundle.js`

**Comment by XhmikosR** [comment]
Yup, confirmed.

@mdo: you reverted the whole index.js after the version bump and we missed this.

I guess it doesn't matter for 4.1.0 but we'll make sure it won't happen in the next release.
