### ISSUE TITLE
Card overflows outside card-deck bounds

### ISSUE THREAD

**Issue by rohan-buchner** [twbs/bootstrap#26258]
My app is currently experiencing this issue... (the hand drawn x indicates the cursor position)
![sokoso_gif](https://user-images.githubusercontent.com/418810/38601283-4da5e520-3d67-11e8-8034-126b2eab2fef.gif)

When hovering underneath the card deck it seems to render an invisible instance of the card item underneath the card deck too.. It triggers the original hover as well as is 100% interactive (meaning I can click on it)

Here is a [LINK](https://www.sokoso.ng/jobs) to the affected area for your viewing pleasure.

...and the markup in question:
```
<div class="card-deck d-block">
   <div class="card-columns col px-0 px-sm-3">
      <a class="card mx-0">
         <div class="card-body">
            <div class="row">
               <div class="col">
                  <h1 class="h6 card-title text-truncate">Social Media Marketer/Advertiser</h1>
               </div>
            </div>
            <div class="row">
               <small class="col">
                  <h6 class="cord-substitute mb-2 text-muted text-truncate">Zainab</h6>
               </small>
            </div>
            <div class="row">
               <small class="col-8">
                  <div class="text-muted"><i class="text-primary fa fa-map-marker-alt"></i>&nbsp;Garki I</div>
               </small>
               <small class="col-4 text-muted">
                  <div class="float-right">--</div>
               </small>
            </div>
         </div>
      </a>
     
      <!-- card repeated more times -->
   </div>
</div>
```

I believe this is bug within Bootstrap 4 at this stage.

**Temporary fix:**
We've managed to resolve this locally by adding an overflow hidden on the `card-deck` class.

**Comment by mdo** [comment]
- Card columns don't go in card decks—you're implementing competing card layout methods.
- You have unnecessary rows throughout. A `.row` with only one `.col` does nothing for you.
- A `<small>` around an `<h6>` does nothing.
- You have no `href` on your links, likely causing some link styling issues.

Bottom line, your example code hasn't removed all your modifications to sufficiently narrow it down to a Bootstrap bug.

**Comment by rohan-buchner** [comment]
@mdo wow thanks!
Ill revise some of the css. notes on your comments:

- columns don't go in card decks—you're implementing competing card layout methods.
    * first thing ill look into. (still somewhat new to cards)
- You have unnecessary rows throughout. A .row with only one .col does nothing for you.
    * Literally did not know that and i've been using bootstrap for as long as that you been making it... assumptions are killer :| (but thanks for the guidance)
- A <small> around an <h6> does nothing. 
   * Got it
You have no href on your links, likely causing some link styling issues.
   * Just removed the href in the pasted sample
