### ISSUE TITLE
how to disable modal with media queries?

### ISSUE THREAD

**Issue by kremeshnoy** [twbs/bootstrap#26252]
____________________________________________________________________________________________________
My code 🠗

HTML

```html
<div id="myModal" class="modal">
	<!-- The Close Button -->
	<span id='unlocker' class="close" 
        onclick="document.getElementById('myModal').style.display='none'">&times;
	</span>
	<!-- Modal Content (The Image) -->
	<img class="modal-content" id="modalImage" src="">
	<!-- Modal Caption (Image Text) -->
	<div id="caption"></div>
</div>
```

JS

```javascript
function handleImageClick(c){
	var modal = document.getElementById('myModal');
	var modalImg = document.getElementById("modalImage");
	var captionText = document.getElementById("caption");
	modal.style.display = "block";
	modalImg.src = c.src;
	captionText.innerHTML = c.alt;
};
```
____________________________________________________________________________________________________
My fails 🠗

e.g №1
```javascript
$('#myModal').modal('hide') /* is not working for me
```
e.g №2
```sass
@media only screen and (max-width : 768px)
	/**/
	.modal
		display: none !important
/* is not the solution, 'cuz I am using mouse-wheel scroll lock
```

**Comment by pjones235** [comment]
Per your first example, not sure why you would offer a javascript example when you're trying to accomplish this with media queries.

If you were to be able to successfully hide the modal via a media query, what are your intentions? Are you trying to prevent a user from opening the modal or are you trying to hide a modal that is already displaying?

**Comment by patrickhlauke** [comment]
Sorry, this is not the place for "how to..." questions. Use stackoverflow or similar for that. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
