### ISSUE TITLE
Button checkbox and external label

### ISSUE THREAD

**Issue by challet** [twbs/bootstrap#26265]
Hi, 

A button with a checkbox is also linked to an external label. When clicking on this label, the button itself is able to switch its active state, but the inner input is switched twice, getting it back to its original state.

http://jsfiddle.net/jrfygm5v/19/

I've read here https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons that : 
> The checked state for these buttons is only updated via click event on the button

As suggested, the workaround would be
> to toggle .active on the label manually.

http://jsfiddle.net/37bx98wa/4/

The original event is indeed not from the button, but a click is still triggered on the input (by the browser ?) and bubbles to the button. It might then be seen as fullfilling this condition, or not ?

**Comment by Rishab49** [comment]
I think you should write full jquery command means starting from $(document).Ready(); and you should add true next to the "checked" value.

**Comment by challet** [comment]
@Rishab49 that is right I should wait for load to be finished. Though the example is not breaking because of that. Your exemple is only about checkboxes and nothing related to bootstrap, that's not the place to make adverts please.

**Comment by mdo** [comment]
My guess is you're running into issues with using two different labels for the same input. I don't know any hard steadfast rules around that, but that seems like _an_ issue at least.

**Comment by Johann-S** [comment]
very weird use case 😲

**Comment by mdo** [comment]
This looks like default checkbox behavior. The second example here triggers shows two log events in this instance: http://jsfiddle.net/rjfmzu0t/2/. This matches the first example.

This is hella old, but given the lack of movement around it and additional reports, I think it's safe to close as a won't fix. Happy to revisit though!
