### ISSUE TITLE
Remove .text-hide mixin from documentation or mark as deprecated

### ISSUE THREAD

**Issue by mhlozek** [twbs/bootstrap#26262]
Shouldn't be this page http://getbootstrap.com/docs/4.1/utilities/image-replacement/ removed or marked as deprecated? I think it could be confusing for new users.

**Comment by XhmikosR** [comment]
@mdo: should I remove the page and redirect to `/utilities/`?

**Comment by XhmikosR** [comment]
Actually, scratch that. The proper thing would be to show a warning in the docs page for now.
