### ISSUE TITLE
why is <dialog> defaulted to `display: block`?

### ISSUE THREAD

**Issue by cskinfill** [twbs/bootstrap#26264]
See this line https://github.com/twbs/bootstrap/blob/8f7bd419935adfcd53c471a0202083464800619e/dist/css/bootstrap-reboot.css#L27

It seems that this is causing the contents of the `<dialog>...</dialog>` to be rendered when the page is loaded.  If bootstrap is not used, it will hide the contents until `myDialog.showModal()` is called.

**Comment by bak12** [comment]
B

**Comment by cskinfill** [comment]
In the document below, if its loaded as is, the dialog box will be hidden and only appears when the button is clicked.  If the stylesheet link is uncommented, the dialog box will appear when the page loads.

<!doctype html>
<html lang="en">
<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
</head>
<body>
  <dialog id="dialogTest">
    This should not show at load-time!!!!
    <button id="closeDialog">Close</button>
  </dialog>
  <span>This should show</span>
  <button id="showDialogBtn">Show dialog</button>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script>
  (function() {
    var showDialog = document.getElementById('showDialogBtn');
    var dialogToShow = document.getElementById('dialogTest');
    var closeDialog = document.getElementById('closeDialog');

    // Update button opens a modal dialog
    showDialog.addEventListener('click', function() {
      dialogToShow.showModal();
    });

    // Form cancel button closes the dialog box
    closeDialog.addEventListener('click', function() {
      dialogToShow.close();
    });
  })();
  </script>
</body>
</html>
