### ISSUE TITLE
inputs with class btn-* partly styled

### ISSUE THREAD

**Issue by TravellerSam** [twbs/bootstrap#26279]
![bootstrap 4 1 input primary](https://user-images.githubusercontent.com/872730/38678220-b848d10e-3e60-11e8-860c-99df6f48884e.png)

`inputs`s styled with `btn-*` class (like `btn-primary`) are not styled with colors. 

`a` and `button` tags with same classes are styled correctly.

Bootstrap 4.1.0

**Comment by patrickhlauke** [comment]
just a screenshot is...not helpful. please provide a working reduced test case (ideally live on jsfiddle, codepen, or similar).

but for what it's worth, just tried `<input type="button" class="btn btn-primary" value="Boom">` and it's styled just fine. 

![capture1](https://user-images.githubusercontent.com/895831/38678938-5da711ee-3e5a-11e8-8c1a-4cda7c28457a.PNG)
