### ISSUE TITLE
Form Validation Javascript

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26271]
I'm not sure whether this issue is related to lack of detailed documentation or whether it's a possible bug in the way the Javascript and forms behave in different browsers / frameworks, needless to say, I've experimented and provided a working fix along with the current Bootstrap 4 version.

#### Introduction & Issue

So I was experimenting with the Bootstrap 4 validation in a working project built using CS Cart (https://www.cs-cart.com/), their current register form doesn't really have any strong validation in terms of checking passwords or anything modern.

I essentially installed Bootstrap 4, copied over the HTML form components in the structure that the documentation says to do so and placed the Bootstrap 4 example validation JS code at the bottom (https://getbootstrap.com/docs/4.1/components/forms/#validation), jQuery had already been loaded at this point.

The following input fields and types were used:

- First Name (text)
- Last Name (text)
- Email Address (email)
- Password (password)
- Confirm Password (password)

After entering some valid details in the first name field, and leaving the rest blank and hitting the submit button, I realised **I couldn't submit the form again despite entering valid data** into the empty fields.

After scrolling through the JS code in the Bootstrap 4 docs for form validation here's what I've gathered:

```
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('js_twbs_form');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
```

```
 form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
```

The above code taken from the docs appears to behave weirdly, as you can see where we're checking for  the formValidity **if there are any INVALID fields** we're then preventing the form from being submitted which is understandable.... 

The problem then comes when after I've filled in the invalid fields **I then cannot actually submit the form again and the code doesn't run** and check for valid/invalid fields because the button exists inside the form, and the form is disabled due to `event.preventDefault();` and `event.stopPropagation();` from the first time I submitted the form.

Take a look at this codepen I've created to demonstrate, I must emphasise that this is a  **reduced test case** example without the bloat from a framework and likely will perform as expected (but likely not the best javascript)

Bootstrap 4 demo => https://codepen.io/anon/pen/WzWNob

#### One solution

To overcome the problem of checking that the user has filled in any invalid fields, I've modified the code slightly to instead now check the Validity of the form whenever the **clicks** the submit button rather than submitting the form, take a look....

Custom Working Demo => https://codepen.io/anon/pen/wmZvWV

In the above demo we're not actually preventing the user from clicking the submit button by using the 'on submit', instead, we're allowing the user to submit the form, but by modifying the code and checking the Validity of the form when the user clicks the submit button we can then prevent the form being submitted without disabling the form, this code has been tested and works.

```
 $("#submitBtn").click(function(event) {
          if (form.checkValidity() === false) {
            form.classList.add('was-validated');
            event.preventDefault();
            event.stopPropagation();
          }
        });
```

#### Conclusion / Suggestions

Regardless of the outcome, I feel that the NEW documentation for the form validation section still isn't sufficient enough and doesn't really contain a way of resetting the form despite the new bullet being added as follows:

> To reset the appearance of the form (for instance, in the case of dynamic form submissions using AJAX), remove the .was-validated class from the form again after submission.

I feel that there's more to it than just this, and in the event that the user isn't using AJAX the current Javascript Botostrap 4 provides for form validation **doesn't really work too well** and should be considered revising.

I hope this helps! Many thanks :)

**Comment by patrickhlauke** [comment]
The validation script works as it should.

> The problem then comes when after I've filled in the invalid fields I then cannot actually submit the form again and the code doesn't run and check for valid/invalid fields because the button exists inside the form, and the form is disabled due to `event.preventDefault();` and `event.stopPropagation();` from the first time I submitted the form.

not quite. `event.preventDefault()` / `event.stopPropagation()` only block the submit event if `form.checkValidity()` returns false. they don't "disable" the form itself in any way.

i'd suggest that perhaps you need to add an actual `action="..."` attribute to your form (assuming you're submitting your data somewhere?). see the same form and script as in the docs, but modded to submit to an actual domain. https://codepen.io/team/Bootstrap/pen/zWXGQo

if instead you're using some JavaScript (AJAX or otherwise) to handle the submission, then you'll need to programmatically reset the form.

**Comment by three-hourcai** [comment]
Check this explanation



https://jqcode.space/questions/the-form-fails-to-submit-even-after-the-validation-process-is-completed
