### ISSUE TITLE
Form Validation for Password & Password Confirm fields

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26270]
I've used the Bootstrap 4 form validation in some projects and find it great, however, the form validation doesn't contain anyway of comparing the values of two password fields.

For Example:

Assume I want a signup page with the following fields:

- Email
- Password
- Password Confirm

I don't want the user to be able to proceed with signing up if the 'password confirm' field doesn't match the value of the 'password' field.

I know there isn't really a HTML5 solution to this, so in projects where I'm using the Bootstrap 4 form validation I'm having to create my own jQuery, it would be nice to see this feature implemented into Bootstrap 4.2 along with the additional form tweaks?

Reference: https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by patrickhlauke** [comment]
There are no plans to implement actual validation scripts in Bootstrap beyond what browsers do natively with HTML5 validity, I'm afraid.
