### ISSUE TITLE
Wordpress issue

### ISSUE THREAD

**Issue by emran-shaikh** [twbs/bootstrap#26277]
Hello Friends I Have an issue with my wordpress its giving this issue n every page i dont know how to get ride off plz help me thanks in advance "Warning: Parameter 2 to WPE\Site_Preview::the_posts() expected to be a reference, value given in C:\xampp\htdocs\theme-name\wp-includes\class-wp-hook.php on line 286"

**Comment by Johann-S** [comment]
Sorry but for issues related to Wordpress you should go to WordPress support instead of Bootstrap's repository. See: https://wordpress.org/support/

**Comment by emran-shaikh** [comment]
sorry for that.
