### ISSUE TITLE
One Place for 3rd party/out of the box plugins/components

### ISSUE THREAD

**Issue by shivajivarma** [twbs/bootstrap#26285]
Can we have a page on the bootstrap website listing 3rd party/out of the box plugins or components (or allow developers to submit there plugins/components and get listed on the page). Categorized them based on compatibility with bootstrap version. 

This really saves lot of time for developers looking for common componets.

**Comment by pjones235** [comment]
Along with that, perhaps add documentation for the provided bootstrap themes' components.

**Comment by mdo** [comment]
We tried a low key version of this on the Expo for awhile and it got out of hand pretty fast. Perhaps rely on the tags in npm or other package managers for this? Google isn't bad for this and my sense is there are far too many for us to keep up with.

**Comment by shivajivarma** [comment]
Something like this https://github.com/therebelrobot/awesome-bootstrap will be nice.  Git Repository where people can contribute and display it on bootstrap official website. Support by bootstrap team will drive more people to contribute.

**Comment by aledalgrande** [comment]
Even better than a list, would be a contrib repo, so devs know what's stable/maintained

**Comment by aledalgrande** [comment]
Also: for development speed and ease contrib could just be a series of git submodules of approved repos

**Comment by mdo** [comment]
Closing this out—if we want something like this, I'd punt it to a separate repo and site like the Expo. Problem is getting folks to maintain it and monitor submissions :). For now, I don't see us taking that on.
