### ISSUE TITLE
Navbar-nav list type not being respected on refresh in Edge

### ISSUE THREAD

**Issue by jonny64bit** [twbs/bootstrap#26287]
So if you load up this bootstrap 4 example in Edge with the browser window in md or above

https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar

Shrink the window so you see the navbar-toggeler and expand.

Refresh the window and expand again.

You'll see the that list-style: none; isn't being respected.

![example](https://user-images.githubusercontent.com/3177463/38726440-18abdd92-3f02-11e8-98c2-0f9004b74447.png)

i've checked this in chrome, firefox and IE11 so this looks to be a edge only bug.

**Comment by XhmikosR** [comment]
@mdo: what do you think about the aforementioned workaround?

**Comment by mdo** [comment]
I've seen little to no feedback around this problem since the issue was opened. Is this still an issue or was the problem solved with an update to IE? Feel like if this was a bigger issue, we'd have more input from developers here.

**Comment by jonny64bit** [comment]
@mdo this is still an issue in the latest Edge verison.

**Comment by patrickhlauke** [comment]
confirming that this is still a problem in Edge (but strangely, not in IE11). smells like a browser bug (with the understanding that Edge is going to use Blink in future so the issue will disappear)

**Comment by patrickhlauke** [comment]
Seems this bug is fixed now in Edge.
