### ISSUE TITLE
1px black line with .embed-responsive-16by9 and YouTube video in Firefox

### ISSUE THREAD

**Issue by apiening** [twbs/bootstrap#26284]
Since the original issue #18261 was closed without a solution, I created a new one.

Please take a look at this very simple markup using the full screen preview in Firefox: https://www.bootply.com/IBqa3KimQL

At the bottom of the YouTube video is a black line with 1 pixel.
This is especially annoying on a white background page and a white video.
The black line does not show up with Google Chrome or Apple Safari. I have this issue only with Firefox (version 59.0.2 here).

**Comment by Chaosxmk** [comment]
Tested at various screen sizes, seems more like an aliasing issue on the video itself and not an actual border from no where.

**Comment by XhmikosR** [comment]
I think it's something unrelated to Bootstrap.

Just zoom in or zoom out; the black line goes away.

**Comment by XhmikosR** [comment]
And I can see the same line after playing around with zoom in / out on Chrome too.

**Comment by XhmikosR** [comment]
On the other hand, changing `.embed-responsive-16by9::before` padding-top to 56.20% - 56.22% fixes the problem for me.

Something weird is going on with the math the browser is doing. I also see the 1px line to the right under some resolutions.

**Comment by XhmikosR** [comment]
That was my idea too, @patrickhlauke. But then I noticed that with 21by9 there's a 1px black line to the right this time, after zooming in/out.

Not sure we can make this right for all cases...

**Comment by apiening** [comment]
@XhmikosR Yes you're right: When I resize the window, every now and then the black bar shows up even in Chrome.
I understand that the fractional part of the percentage value might cause different results in different browsers.
One of my customers complained that the black line is on the videos. It might get tricky to explain why it is probably not possible to remove it.
One solution would be to change the background-color of the youtube iframe to the color of the page. A white 1 px line at the bottom wouldn't be noticeable on a white page.
Unfortunately it looks like there is no option to add custom styling to the youtube iframe embed url.

**Comment by XhmikosR** [comment]
I don't think the border fixes the issue. What really fixes it is changing the padding. But I can't find a number that works in all cases from a quick look...

PRs welcome as always.

**Comment by patrickgrey** [comment]
In my responsive container div, I added clip-path: inset(1px 1px); Works for newer browsers except Edge. Only solution I have come up with to remove the black lines from the thumbnail.

```
.embed-container iframe, .embed-container object, .embed-container embed
{ 
  position: absolute; top: 0; left: 0; width: 100%; height: 100%; clip-path: inset(1px 1px);
}
```

**Comment by LuisMiguelSS** [comment]
This issue also happens to me using Safari 11.1, but the solution that @patrickgrey wrote is neither working for me.
Also it adds another 1px line on top of the video (both Firefox 60.0.1 and Safari 11.1). Notice the "padding" you can see on the bottom screenshot has been inserted by me.
<img width="1280" alt="captura de pantalla 2018-06-02 a las 17 37 16" src="https://user-images.githubusercontent.com/37138444/40878658-f90a0e9e-668b-11e8-858e-18a2b7ff82e4.png">
<img width="1280" alt="captura de pantalla 2018-06-02 a las 17 37 08" src="https://user-images.githubusercontent.com/37138444/40878659-f93c058e-668b-11e8-83b0-8cab8981416a.png">

**Comment by ovpv** [comment]
hello @LuisMiguelSS ,

After looking into your issue, I found out that the border that you are seeing is actually the background color of your youtube content. 

Look at the following screenshot:
![desktop screenshot 1](https://user-images.githubusercontent.com/18413362/41082859-43ed029e-6a4d-11e8-94f3-844e8b227cef.png)

I dont think its an issue with .embed-responsive-16by9. That background is added by the youtube content structure.

One thing you can do to fix this issue is that when you are adding the src in you demo add **theme=light** as shown below:

`<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/wqd81s0vrAQ?theme=light&rel=0&amp;controls=0&amp;showinfo=0"></iframe>`

I hope this fixes the issue. 👍

**Comment by MartijnCuppens** [comment]
@ovpv is right.

I don't think we shouldn't change something here, tweaking the percentage or using clipping hacks only for youtube iframes just doesn't feel right and will cause more issues in other situations.

**Comment by RK-developer** [comment]
As @ovpv said, that issue belongs to youtube's  (`iframe> body {background-color: #000}`).
So we can solve this issue by applying this style ( `margin-top:-1px` ) to the selector either   `.embed-responsive-16by9 ` or  `.embed-responsive-item`.
![issues-fixed-1](https://user-images.githubusercontent.com/40082889/47508815-6bc99d00-d892-11e8-8532-09e253c7c353.png)

**Comment by XhmikosR** [comment]
Closing since it's not an issue with our CSS.

**Comment by espaistelematics** [comment]
The @patrickgrey solutions works fine in youtube iframes.
Thanks patrick
