### ISSUE TITLE
Documentation website somehow reverted to Bootstrap 4.0.0 Beta 2

### ISSUE THREAD

**Issue by liviubunda** [twbs/bootstrap#26289]
I needed to look up some docs on extending Bootstrap using SaaS and noticed the page was missing. I then noticed that an older version of the docs was live.

Printscreens with obvious visual cues attached. 

![screenshot_1](https://user-images.githubusercontent.com/689876/38731580-93041b74-3f23-11e8-9d40-77c842324e77.png)

![screenshot_2](https://user-images.githubusercontent.com/689876/38731581-9322090e-3f23-11e8-96be-f2716c19cf49.png)

**Comment by XhmikosR** [comment]
I can't confirm, nor do you give us any info like Browser version.

So, just clear your browser's cache.

**Comment by liviubunda** [comment]
Loads 4.1 now. 
Thanks for the quick reply. It worked by clearing cache manually from debugger, hard refresh didn't work.
Shouldn't your cache expire after a given period? Beta 2 was a while ago.
