### ISSUE TITLE
https down for stackpath.bootstrapcdn.com - us est

### ISSUE THREAD

**Issue by rifflesbits** [twbs/bootstrap#26280]
Hi I believe https is down for  stackpath.bootstrapcdn.com  when referencing it from the Eastern US.  

```
C:\>tracert https://stackpath.bootstrapcdn.com
Unable to resolve target system name https://stackpath.bootstrapcdn.com
```

From a browser I can access this:

http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

but cannot access:

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

When I visit public popular sites that use bootrstap, from an incognito browser, their style is not loaded.

**Comment by scottymcraig** [comment]
Cannot confirm - Eastern US here too and both ones load for me.

**Comment by Swardu** [comment]
Both work for me, Central Europe.

**Comment by XhmikosR** [comment]
@rifflesbits: please use the proper repository to report such issues; I didn't see this earlier.

For now,I forwarded this to the right people, but timing is of the essence  when it comes to such issues.

**Comment by XhmikosR** [comment]
Anyway, closing this since it's unrelated to Bootstrap itself.

If you have issues with BootstrapCDN, report them on the GitHub repo https://github.com/MaxCDN/bootstrapcdn

**Comment by rifflesbits** [comment]
Hi @XhmikosR  ok thank you - I'll use the MaxCDN/bootstrapcdn repo if I see it again.  

I noticed it's fixed today - I can reference the https css from an incognito browser.  I don't believe my local dns resolver or firewall settings have changed at all since yesterday when I couldn't reference it.

Here was a tracert from yesterday when I couldn't reference the css via https:

```
C:\>tracert stackpath.bootstrapcdn.com

Tracing route to cds.j3z9t3p6.hwcdn.net [205.185.216.10]
over a maximum of 30 hops:

  1     2 ms     1 ms     1 ms  10.204.24.1
  2    <1 ms    <1 ms    <1 ms  10.1.6.117
  3     1 ms    <1 ms    <1 ms  10.2.2.129
  4     1 ms     1 ms     1 ms  10.2.2.1
  5     *        *        *     Request timed out.
  6     *        *        *     Request timed out.
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9     *        *        *     Request timed out.
 10    17 ms    16 ms    16 ms  map2.hwcdn.net [205.185.216.10]

Trace complete.
```

Yesterday - the https://www.bootstrapcdn.com/ site was displaying poorly for me when it couldn't reference its css style, when viewed from an incognito browser - but today it looks good.
