### ISSUE TITLE
Collapse no longer works if data-target has a space in it

### ISSUE THREAD

**Issue by mojimi** [twbs/bootstrap#26295]
I understand this is easy to fix, but this broke our webapp that was working fine with 4.0.

After MUCH searching I discovered that was the space in the data-target/id.

Our ids are dynamically created that's why they have spaces, but I understand it's not a good practice.

Here's a working example : https://jsfiddle.net/aq9Laaew/5509/

**Comment by patrickhlauke** [comment]
FWIW a valid `id` must not contain space characters https://www.w3.org/TR/html51/dom.html#the-id-attribute though it seems (some?) browsers interpret it as part of the `id` itself regardless. it appears jquery's ID selector doesn't like spaces in `id`s either.

**Comment by diamantgjota** [comment]
Collapse no longer works on IE 11! I'm working on an app and when I updated bootstrap 4 to 4.1 I noticed that collapses are not working, same error is on getbootstrap.com page aswell "Object.keys: argument is not an Object".

Sorry for my English!

**Comment by Johann-S** [comment]
@diamantgjota it'll be fixed in our next release (the fix is merged see: https://github.com/twbs/bootstrap/pull/26291)

**Comment by Johann-S** [comment]
As @patrickhlauke said you should generate a valid `id`
