### ISSUE TITLE
some part of .navbar interfers with onclick events

### ISSUE THREAD

**Issue by SumNeuron** [twbs/bootstrap#26298]
I have a custom form element in my sticky navbar that requires an onclick event. 
Somewhere in the inheritance the class navbar interferes with detecting clicks directly center on the element (the borders are fair game however).  The form element is not the issue as after moving the form element anywhere else in the page (or just a page with the form element itself) the event works fine.

I have a solution to my problem. If I replace .navbar with

```
.fixed-finicky-navbar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  padding: .5rem 1rem;
}
```

the click event registers always.

Where what is above is just the main styling of .navbar in the scss file.

So there is some kind of inheritance in the scss file that affects the registration of a click event.

I am posting this simple to log the fact that this issue exists. 
It is fairly niche that it likely will not affect many others.

**Comment by mdo** [comment]
Sounds like a z-index issue perhaps? Without a live demo though as the issue template requires, not much we can do.
