### ISSUE TITLE
babel/cli is not in the npm registry

### ISSUE THREAD

**Issue by cpburnz** [twbs/bootstrap#26293]
I'm having trouble building Bootstrap when following the instructions from [Build tools](https://getbootstrap.com/docs/4.1/getting-started/build-tools/). I downloaded the source (bootstrap-4.1.0.zip), and extracted it. Upon running `npm install` in the `bootstrap-4.1.0/` directory, I receive the following output:

```
npm WARN deprecated qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'babel/cli' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'bootstrap'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.15.0-2-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/caleb/Downloads/bootstrap-4.1.0
npm ERR! node -v v8.9.3
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/caleb/Downloads/bootstrap-4.1.0/npm-debug.log
npm ERR! not ok code 0
```

It appears that the "babel/cli" package is not available from NPM.

I'm running Debian 10 (buster/testing) and have Node.js v8.9.3 and NPM v1.4.21 installed.

**Comment by cpburnz** [comment]
I tried cloning the *v4-dev* branch and ran `npm install`. I get a similar error but for `babel/core`:

```
npm WARN deprecated qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'babel/core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'bootstrap'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.15.0-2-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/caleb/Downloads/bootstrap
npm ERR! node -v v8.9.3
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/caleb/Downloads/bootstrap/npm-debug.log
npm ERR! not ok code 0
```

Bootstrap v4.1 is requires babel "7.0.0-beta.42" according to its `package.json`, and v4-dev requires babel "7.0.0-beta.44".

**Comment by thatnini** [comment]
Are you really using NPM v1.4.21? 

Its an extremely old version and I don't think it has the ability to install scoped packages eg `@babel/cli` and `@babel/core`. 

Doesn't Node.js v8 normally come with NPM v5? 

You might want to check that you don't have another NPM installed somewhere else. If not, then I would suggest upgrading NPM.

**Comment by cpburnz** [comment]
@thatnini I must preface this by saying that I know absolutely nothing about the Node.js ecosystem. I'm running an up-to-date Debian 10/testing system. I installed the *nodejs* and *npm* packages from the Debian testing apt repos. Should I be installing Node.js or NPM from elsewhere?

**Comment by thatnini** [comment]
I know nothing about Debian :P

A quick google came up with [https://stackoverflow.com/questions/44095985/why-can-i-only-install-an-outdated-version-of-npm-on-debian-ubuntu#44096057](https://stackoverflow.com/questions/44095985/why-can-i-only-install-an-outdated-version-of-npm-on-debian-ubuntu#44096057)

**Comment by wolfy1339** [comment]
You can use nodesource, that have an automated script to install it automatically, but first remove your current install:
```
curl -sL https://deb.nodesource.com/setup_9.x | bash -
apt-get install -y nodejs
```

**Comment by cpburnz** [comment]
@thatnini  Fair enough. I would have expected it to be relatively up-to-date on Debian but I guess it's not. 

@wolfy1339  Thanks, using the nodesource repo worked.

**Comment by Abdelaziz-Mahdi** [comment]
Typo @ npm command will lead to the same issue copy the following and try: `npm i @babel/cli`
