### ISSUE TITLE
Unable to show Header Image, without having Banner Title and Tagline.

### ISSUE THREAD

**Issue by THREELabs** [twbs/bootstrap#26303]
Maybe I am seeing this wrong.  But is it possible to have the header image show, but without the Header Tagline and Header Title.  Just have it show a logo instead?

![2018-04-14 20_42_08-customize_ three skateboarding skateboarding news and shit](https://user-images.githubusercontent.com/8344415/38774795-185de3b6-4025-11e8-8123-c1cef892e2d6.png)

**Comment by patrickhlauke** [comment]
nothing to do with bootstrap.

**Comment by THREELabs** [comment]
Great news.
