### ISSUE TITLE
It has some lines in IE11 150%

### ISSUE THREAD

**Issue by laoruiwen** [twbs/bootstrap#26306]
This is an example in [Bootstrap Chinese official website](https://v3.bootcss.com/javascript/#modals).
We can see a line on the left of the picture.
![官网模态框实例.png](https://upload-images.jianshu.io/upload_images/11133151-c395f6b5bc5678d8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

````
// Bootstrap3.3.7 modals.less
// Actual modal
.modal-content {
  position: relative;
  background-color: @modal-content-bg;
  border: 1px solid @modal-content-fallback-border-color; //old browsers fallback (ie8 etc)
  border: 1px solid @modal-content-border-color;
  border-radius: @border-radius-large;
  .box-shadow(0 3px 9px rgba(0,0,0,.5));
  // background-clip: padding-box;    
  // Remove focus outline from opened modal
  outline: 0;
}
````

I find the lines shows because of `background-clip: padding-box` .
This bug shows in IE11 pantograph ratio 150%.
Pantograph ratio 149% or 151% cannot shows this bug.
I guess this maybe is a bug of IE11.

**Comment by mdo** [comment]
None of the translations are official, and they're not maintained here. You'll have to find the person who published that and report it there.
