### ISSUE TITLE
Drop down menu broken in 4.1

### ISSUE THREAD

**Issue by virgiltu** [twbs/bootstrap#26307]
Under 4.0 everything works, however when using 4.1 the responsive drop down menu in mobile will just fliker and return to open. 

Reverted back to 4.0 and it all works.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by albertovivar** [comment]
Good morning,

same here, i can confirm that. With Bootstrap v4.1 and IE 11 the drop down menus via 'data-toggle' are broken. Working in v4.0

**Comment by Johann-S** [comment]
Seems related to: https://github.com/twbs/bootstrap/pull/26291

If not, do not hesitate to /CC me 😉
