### ISSUE TITLE
Oversized Lead Class Characters

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#26304]
I noticed last night in Chrome and Firefox that the lead class is producing some oversize characters. The snippet below shows oversized d's and 1's

![image](https://user-images.githubusercontent.com/5879776/38775437-01ee4cc8-40c6-11e8-9bf4-b0d3faaa763f.png)

Running: Windows 7 Professional - Service Pack 1

**Comment by patrickhlauke** [comment]
Not something that can be fixed by Bootstrap I think. Likely some issue with Win7 and its font rendering subsystem

**Comment by patrickhlauke** [comment]
![capture2](https://user-images.githubusercontent.com/895831/38776606-956ea1bc-4091-11e8-8aba-59330bebbcd7.PNG)

For reference, Chrome/Win10. How the font is rendered then comes down to the OS and how it handles/rounds/aliases fonts.
