### ISSUE TITLE
Modal dialog in IE11 error with V4.1.0

### ISSUE THREAD

**Issue by fjfer** [twbs/bootstrap#26314]
Hi.

I've found an issue with the version 4.1.0 while trying to display a modal dialog in IE11 using jquery.

The error is:

Object.keys: Invalid argument
rollupPluginBabeHelpers

If I use the version 4.0.0 all is ok

Codepen to test
https://codepen.io/anon/pen/xWvXgm

Thanks

**Comment by Johann-S** [comment]
already fixed by: https://github.com/twbs/bootstrap/pull/26291 and will be available in our next release 👍

**Comment by Johann-S** [comment]
If you have other issues do not hesitate to open issues @ThiloL

**Comment by ThiloL** [comment]
backdrop isn't removed with `.hide()` in my sceanrio
