### ISSUE TITLE
IE 11 javascript error dismissing modal in 4.1

### ISSUE THREAD

**Issue by MarcoNegroni** [twbs/bootstrap#26310]
Good morning, after updating our web tools to 4.1 we are facing javascript errors closing modals in Internet Explorer 11:

SCRIPT5007: Object.keys: argument is not an Object
bootstrap (1,584)

You can get this error also using the official documentation: [https://getbootstrap.com/docs/4.1/components/modal/](https://getbootstrap.com/docs/4.1/components/modal/) clicking on the "Launch demo modal" button and then close.

Thanks in advance

**Comment by deanpienaar** [comment]
We are also getting this. @MarcoNegroni did you update your jQuery? I realised the docs updated to 3.3.1 but yarn didn't list it as an outdated dependency. I'm hoping updating will fix it.

**Comment by deanpienaar** [comment]
Tried upgrading jQuery. It doesn't seem to have fixed it.

**Comment by deanpienaar** [comment]
Some further info:
1. It's the `__objectSpread` function in `bootstrap.js`.
2. It seems to be that sometimes one of the arguments is `false` and thus "Not an Object". This looks like it's linked to line 1327 in `bootstrap.js` as the 4th argument would be a boolean.

`var _config = _objectSpread({}, Default, $this.data(), typeof config === 'object' && config);`

**Comment by deanpienaar** [comment]
Ahha. I see this was already fixed here #26291

**Comment by Adam-Mould** [comment]
This is happening for me both on tooltips and modals.

By the looks of it, if the constructor's config is not an object, then `_getConfig()` is trying to do a spread operator on a non object, which is throwing an error in IE11. So for example;

`$('.my-selector').tooltip();` Throws the error
`$('.my-selector').tooltip({});` Doesn't throw the error.

**Comment by Johann-S** [comment]
Those sort of error are fixed here: #26291

**Comment by Joyrex** [comment]
I'm invoking modals using the following code (I have a mixture of modals with their content in-page as well as remotely-loaded modals) and the solution @Adam-Mould mentions I can't seem to apply:
`$('body').on('click.modal.data-api', '[data-toggle="modal"][href]', function(){
	$($(this).data("target")+' .modal-content').load($(this).attr('href'));
});`
Here's a CodePen showing the issue (launch in IE 11): https://codepen.io/Joyrex/pen/xWWYzq?editors=1000
I'm using the `bootstrap.bundle.min.js` - how would I apply the fix from #26291 or is there an updated bundle file I could download with the fix in it?

**Comment by Johann-S** [comment]
It'll be fixed in a new release soon

**Comment by joho1968** [comment]
Getting this too with bs4.1 / jq3.3.1. Also could not get $('#myModal').modal ('show') to work in MSIE. Had to do $('#myModal#').modal ({'show':true}). Using just $('#myModal').modal ('show') works with FF, Edge, and Chromium/Chrome. Since .hide() doesn't work, I guess we'll have to wait for 'hide' to work (and 'show') :)

**Comment by ThiloL** [comment]
Is there a fix for IE11?

**Comment by joho1968** [comment]
I don't know, but I coded around it by rolling my own "modal". Something like:

- Create hidden div which via jQuery inherits height of input form
- When needed, show hidden div, hide input form
- At the same time, add click handler which just swallows everything without action
- Wait for modal action to complete
- Hide modal again, show input form
- At the same time, remove click handler

The "modal" is just a regular div in my case, which I use hide/show/toggle on, and this works fine with JQ331/BS41x and MSIE11. It's not optimal, but it'll do for me :)

**Comment by peteristhegreat** [comment]
This looks like it has been fixed since Bootstrap v4.1.1  
https://github.com/twbs/bootstrap/pull/26291  
https://github.com/twbs/bootstrap/issues/25971  
 https://stackoverflow.com/a/50046357/999943
