### ISSUE TITLE
Версии браузеров, на которых поддерживается bootstrap4

### ISSUE THREAD

**Issue by liliana2** [twbs/bootstrap#26315]
Интересны максимально старые версии браузеров под системы windows, mac, linux, на которых корректно будет работать Bootstrap4. Спасибо

**Comment by afuno** [comment]
Во-первых, по английски :)
Во-вторых, вот тут поищите - http://getbootstrap.com/docs/4.1/getting-started/browsers-devices/

**Comment by patrickhlauke** [comment]
we do not keep a list of which old browser version is still able to run Bootstrap. we target the latest stable releases, plus IE 10/11

**Comment by liliana2** [comment]
Well, prompt still browser list For bootstrap3 please. Thanks
