### ISSUE TITLE
Provide an minimalistic example project for theming (change global font size)

### ISSUE THREAD

**Issue by stephanema** [twbs/bootstrap#26312]
Hi,

I finally got to build bootstrap 4.1 from the sources on my Win7 64bit PC.

Now I would like to build 3-5 different bootrap4.1 versions:
 - every one with a different global font size so user can select
   the preferred font size (depending on their eyes and/or screens)
 - with a different navbar background (dark blue instead of black)

... thats all, but now I am stuck googeling around because I don not understand:
http://getbootstrap.com/docs/4.1/getting-started/theming/

Do I need to create a package.json somethere, do I need to learn gulp or whatever tool?
What do I need to type on the command line...?

Yes I am a newbie in bootstrap and not a super web designer, but the documentation
is quite good, all steps are well described howto compile it yourself.

But here (theming) I am really lost.

Can you provide an official miminal example, described step by step?

I the meanwhile I will go the "no-go way":
 1. manipulate the official sources (change parameters for font size)
 2. run : npm run dist
 3. rename the files in dist  dir and move them outside
 4. continue with step 1.

I you have a hint, it would be great. Thanks.

**Comment by pjones235** [comment]
@stephanema I don't think this should be considered an issue. Feel free to post on [StackOverflow](https://stackoverflow.com/questions/tagged/bootstrap-4), and I could share what I've done with over a dozen themes.

**Comment by stephanema** [comment]
Hi I am just trying to hack around... I want the 14px font size like in bootstrap 3.x.

I changed in bootstrap-4.1.0\scss\_variables.scss line 239:

   `$font-size-base:              1rem !default;`

to
  
  `$font-size-base:              0.875rem !default;`

But I get build errors.

If I set:
  `$font-size-base:              14px !default;`

I get an error "Error: Incompatible units: 'rem' and 'px'."

puuuuhhh ... didn't immagine I would run in such problems for such a trivial change.

Is this a bug, or is only `1rem`, `2rem`, `3rem` ... and so on allowed?

**Comment by pjones235** [comment]
It's because the default unit for SASS calculations is in rem. You can always just set the default font size for the HTML tag: `     html { font-size: 14px;} `. That's what all rem values are relative to. And, per [Bootstrap's documentation](https://getbootstrap.com/docs/4.1/content/typography/), `$font-size-base` should always use rem's. No bug.

**Comment by mdo** [comment]
This is beyond our help here—issues are for bug reports and feature requests only. Moreover, the point of Bootstrap using rem units over pixels is so users can scale their entire page with browser page zooming. There shouldn't be any need for your font-size changes.

Regarding theming in general, you have several options, all dependent on your entire application, site, build tools, dependency manager, etc. If you have that figured out, it sounds like you want to generate two different stylesheets. I'd suggest cloning the `bootstrap.scss` file and any associated files and make those changes as needed. You might be able to get away with duplicating just the `_variables.scss` file, but I'm not sure.

**Comment by stephanema** [comment]
Hmm perhaps I was not clear.

I want to have the same "size" style as in bootstrap 3.3.x.

As I understood all sizes (fonts and all other things, like navbar height ...)
are calculated using `$font-size-base` as base.

1. I do not want to change the font size **only**, I do want to get the sizes as in bootstrap 3.3.x
    back (bootstrap 4 wastes too much space on the screen).
2. By the way I want to propose my users to be able to switch the font size ... hmmm ok this
    could be zoom, I didn't figure out howto do this just now.

One question remains: 
If I set in bootstrap-4.1.0\scss_variables.scss line 239:

1. `$font-size-base: 1rem !default;` I can run `npm run dist`
1. `$font-size-base: 2rem !default;` I can run `npm run dist`
1. `$font-size-base: 0.875rem !default;` **I run in an error with** `npm run dist`

So why can I not set a fractional part for the rem unit like in 0.875rem
(this works in normal css).
Did I miss a point? Or is this behaviour a bug?
