### ISSUE TITLE
Cards with no borders

### ISSUE THREAD

**Issue by ClemMakesApps** [twbs/bootstrap#26326]
It would be great if we could have a css class that disables borders for cards.

Something like, `<div class="card border-none"></div>`

**Comment by DeathRay2K** [comment]
Is this not handled by border-0?
https://getbootstrap.com/docs/4.1/utilities/borders/#subtractive

**Comment by ClemMakesApps** [comment]
Ah, silly me. Must have missed that section. Thanks for linking that @DeathRay2K 💯
