### ISSUE TITLE
Issue with IE11 and Bootstrap 4.1.0

### ISSUE THREAD

**Issue by dustinrowland12** [twbs/bootstrap#26327]
Hi,

I am running into a bug in IE11 with Bootstrap 4.1.0. I think it has to do with IE11 not fully supporting ES6. The bug happens in the following function. If I call $("#id").modal() (so there are no arguments passed when calling the function), then the code will break on Object.keys(source) because source evaluates to "false" here.  

 function _objectSpread(target) {
    for (var i = 1; i < arguments.length; i++) {
      var source = arguments[i] != null ? arguments[i] : {};
      var ownKeys = Object.keys(source);   <-- (code breaks here on 3rd iteration of loop)

The specific error I get in the IE11 Developer Tools console is "Object.keys: argument is not an Object".

If I do $("#id").modal({}) (so there is an empty object as an argument to the function), it works just fine. 

I also found this resource on Object.keys(): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys
That resource mentions the issue with ES5 and passing in non-object types.

Anyway, Bootstrap 4.0.0 does not have this issue, so we are using that for now. I'd like to use the latest though, so if this can be fixed in a newer version, please do so!

**Comment by dustinrowland12** [comment]
To add more information, I created a code pen: https://codepen.io/dustinrowland12/pen/GdKzKL
IE11 on Windows 10, Bootstrap version 4.1.0

**Comment by Johann-S** [comment]
Already fixed by: https://github.com/twbs/bootstrap/pull/26291 and will be available in our next release 👍

**Comment by dustinrowland12** [comment]
Thank you for the quick reply. Any thoughts on when the next release may come out? I'm sure that is always the golden question. I just want to be on the lookout for it. 

Thanks again!

**Comment by Johann-S** [comment]
We'll try to release a new version soon to fix some critical bugs. It'll be a 4.1.1 😉

**Comment by catbadger** [comment]
Sorry to prod, but we're pushing back release for 4.1.1. Is there a timeline for 4.1.1 yet?

**Comment by kosinix** [comment]
Should remove <IE11 from the list of supported browsers until then.

**Comment by Johann-S** [comment]
@kosinix 4.1.1 is already out 😉
