### ISSUE TITLE
Twitter is down 😱

### ISSUE THREAD

**Issue by mike3run** [twbs/bootstrap#26324]
We  complain on Twitter when github is down but were do we express that Twitter is down??

<img width="960" alt="screen shot 2018-04-17 at 9 30 15 am" src="https://user-images.githubusercontent.com/7088511/38876395-010dad5a-4222-11e8-88d7-c972c0ae9327.png">

**Comment by Johann-S** [comment]
Sorry but we cannot help you 😆 here it Bootstrap's github and we are not part of Twitter
