### ISSUE TITLE
Will bootstrap support d-table-row-group display?

### ISSUE THREAD

**Issue by ittus** [twbs/bootstrap#26330]
At the moment it only supports 
![screen shot 2018-04-18 at 10 50 34](https://user-images.githubusercontent.com/5120965/38907349-6ef88022-42f6-11e8-94cd-e1498e3cf92f.png)

Will `d-table-row-group` is added in the future?

**Comment by andresgalante** [comment]
Hi @ittus `table-row-group` make the element display like a `tbody`. 

It looks like a rare usecase that an author can have on their CSS, What use case do you have for it?

**Comment by ittus** [comment]
For example, if I want a tbody only available on big screen, I want to do like this:
```
<tbody class="d-none d-sm-table-row-group">
</tbody>
```
At the moment I have to write customized css for that `tbody`

**Comment by andresgalante** [comment]
ok, even though to me it's uncommon I see your point.

@mdo what do you think? should we add it?

**Comment by mdo** [comment]
Closing as a won't fix for now given it's not as common. Our utilities don't suite every need, nor should they.
