### ISSUE TITLE
Add originalEvent to eventListeners

### ISSUE THREAD

**Issue by jakubhonisek** [twbs/bootstrap#26336]
Add `originalEvent` to bootstrap `eventListeners` like hide.bs.dropdown, if support it.

I need to know, which element was clicked, before a dropdown was closed. I tried to add this code to the `Dropdown._clearMenus` function in `dropdown.js` file (after the definition of the `relatedTarget` variable).

`if (event) {
 relatedTarget.original = event.originalEvent;
}`

This code snippet make the `originalEvent` accessible from the `hide.bs.dropdown` event. For other events may be used similar way.

**Comment by Johann-S** [comment]
you already know which element was clicked before the dropdown was closed by `relatedTarget` 🤔

**Comment by jakubhonisek** [comment]
In `relatedTarget` is toggle element (`link`, `button`), but i need to know, which element was actually clicked. For example: if you click to `body` or some element inside `dropdown`, like `p`, `span` etc., the dropdown will close. I need to know the actually clicked element, because i want, for example, stop closing dropdown, if the element has certain `class`.

**Comment by Johann-S** [comment]
Hmm ok, understood thanks 👍

**Comment by morrissey-ingenious** [comment]
You could include something like this above where you include bootstrap js.

```
       $(document).on('click', function(e){
          if($(e.target).hasClass('prevent-dropdown-close')){
            e.stopImmediatePropagation();
            return false;
          }
        });
```
If you want to modify the function you were with something like this.

```
    static _clearMenus(event) {
      if(event && $(event.target).hasClass('prevent-dropdown-close')){
        return;
      }
```

**Comment by Johann-S** [comment]
thats right ! Thanks @alecpl, so close for consistency 👍

**Comment by Hust4k** [comment]
@morrissey-ingenious: But this modification stops propagation all click on the page. I have the same problem.

@Johann-S Will you modify dropdown.js?

**Comment by Johann-S** [comment]
When I'll have time to work on that @ondrajodas, but every issues are open, so if someone want to fix this issue he should do it 😄
