### ISSUE TITLE
Bootstrap 4.1 table with fixed title

### ISSUE THREAD

**Issue by MikaelBox** [twbs/bootstrap#26337]
Hi. How can I make fixed title for the table? I want to create tables with scrollable body and fixed title with Bootstrap 4.1

**Comment by andresgalante** [comment]
Hi @m-smith there are ways to do that with a few lines CSS, I don't think that should be part of Bootstrap though since it involves measuring heights, inner scrolling or display fixie.

**Comment by Joyrex** [comment]
My recommendation would be to use the excellent [DataTables](https://datatables.net) jQuery plugin (which has a [Bootstrap 4 theme](https://datatables.net/examples/styling/bootstrap4.html)), and use its [fixed header](https://datatables.net/extensions/fixedheader/examples/styling/bootstrap4.html) extension.

**Comment by mdo** [comment]
Agreed, no plans to implement this ourselves.
