### ISSUE TITLE
{% example html %} does not indent correctly {% include %}

### ISSUE THREAD

**Issue by vdesdoigts** [twbs/bootstrap#26347]
Hello 👋 

```
<div class="form-group">
  <label for="inputEmail1">Example label</label>
  {% include components/input.html type="email" id="inputEmail1" placeholder="Example input" %}
</div>
```

Render 👇 
![capture d ecran 2018-04-19 a 16 07 38](https://user-images.githubusercontent.com/2852794/38996608-dd855358-43eb-11e8-9f48-5a773032a296.png)

Is it correct? Maybe i'm missing something, but I don't understand how to fix it. Could you help me?

**Comment by mdo** [comment]
This doesn't look like a Bootstrap bug—this looks like you're modifying some Jekyll docs. Please refer to our contributing guidelines and ask in StackOverflow or our Slack.
