### ISSUE TITLE
Modal not hiding when static

### ISSUE THREAD

**Issue by CarlBrindle87** [twbs/bootstrap#26344]
Hi,

I have created a loading modal js file which is dynamically created so it can be called from any other js file, and is static with no keyboard input. It has show and hide functionality:

`var waitingDialog = waitingDialog || (function ($) {
	'use strict';

	// Creating modal dialog's DOM
	var $dialog = $(
        '<div id="loadingDialog" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true" style="padding-top:15%; overflow-y:visible;">' +
        '<div class="modal-dialog modal-dialog-centered modal-lg" role="document">' +
        '<div class="modal-content">' +
        '<div class="modal-header"><h3 class="modal-title" style="margin:0;"></h3></div>' +
        '<div class="modal-body">' +
        '<div class="progress" style="margin-bottom:0;"><div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%"></div></div>' +
        '</div>' +
        '</div></div></div>');

	return {
		/**
		 * Opens our dialog
		 * @param message Custom message
		 * @param options Custom options:
		 * 				  options.dialogSize - bootstrap postfix for dialog size, e.g. "sm", "m";
		 * 				  options.progressType - bootstrap postfix for progress bar type, e.g. "success", "warning".
		 */
		show: function (message, options) {
			// Assigning defaults
			if (typeof options === 'undefined') {
				options = {};
			}
			if (typeof message === 'undefined') {
				message = 'Loading...';
			}

			$dialog.find('h3').text(message);

			// Opening dialog
			$dialog.modal();
		},
		/**
		 * Closes dialog
		 */
        hide: function () {
            $dialog.modal().hide;
		}
	};

})(jQuery);`

In bootstrap 3, the above code worked perfectly. I updated to bootstrap 4 (it was 4.1 but I experienced the Object.Keys issue) and no matter what I did, the modal would not hide. All other modals in my project would hide (as they accept user input), and if I took the static off this, I could hide this also, but it defeats the purpose of what I want from it (automatically hiding when my data has loaded, with no input from the client)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by CarlBrindle87** [comment]
I actually just managed to fix the issue by modifying the hide function to read:

`
hide: function () {
            $('.modal').modal('hide');
		}
`
I don't know why the previous version would no longer work in v4 but at least I have created a workaround for it now!

Thanks for the information regarding the guidelines, I will keep a copy of them for future ref.

**Comment by Johann-S** [comment]
@CarlBrindle87 in your previous version : 

```js
$dialog.modal('hide') // should work

and

$('#loadingDialog').modal('hide') // should work too
