### ISSUE TITLE
reattach all JavaScript data- elements in a lazy load ui scenario

### ISSUE THREAD

**Issue by pepperlk** [twbs/bootstrap#26340]
say im loading a partial html fragment and want to reattach all the data- items in boostrap js components is there a way to call reload() somehow on that element and its children so that we dont have to engage all the elements directly after load.

This also would be useful to have for web components as the bootstrap data- events are already loaded before web components attach.

Thoughts?? Workarounds??

**Comment by pepperlk** [comment]
Sorry about that .. here is the target example with polymer.. 
https://jsfiddle.net/aq9Laaew/15089/

**Comment by Johann-S** [comment]
A simple, would be enough : 

```js
$('[data-toggle="dropdown"]')
  .dropdown('dispose')
  .dropdown()
```

**Comment by pepperlk** [comment]
That is cool and all but I want to reattach all possible bootstrap controls easily. 
This is specifically for just a drop down not any and all Bootstrap JavaScript.

Is that more clear??

I could make a helper if there was a specific set of instructions to call to rebind all components.

**Comment by morrissey-ingenious** [comment]
Maybe I'm mistaken but most items that self initialize are bound on the click event, with the exception of the carousel and scrollspy? You can insert dropdowns from a template and they should would with out issue.  So you only would need to initialize ones that you would need to any how.

**Comment by pepperlk** [comment]
No reload command or any hidden gems to reattach all onclick events in the case above?

**Comment by Johann-S** [comment]
Our components use events delegation, so you shouldn't have to initialise manually, except for Tooltip and Popover

**Comment by Johann-S** [comment]
I tried you JSFiddle (https://jsfiddle.net/aq9Laaew/15089/) but there is an error which block me to help you 😟 

![image](https://user-images.githubusercontent.com/1689750/39528824-7724b5a6-4e25-11e8-996c-2257f52639ca.png)

**Comment by morrissey-ingenious** [comment]
I was able to get this working by redoing it based on a Polymer example.
[http://plnkr.co/edit/pryPwUFCKN8DW3IQ0RbK?p=preview](
http://plnkr.co/edit/pryPwUFCKN8DW3IQ0RbK?p=preview)

I don't see any issues, no need to attach manually.

**Comment by Johann-S** [comment]
it works perfectly on @morrissey-ingenious Plunker, but indeed it doesn't work on Chrome, so I'll close this issue
