### ISSUE TITLE
Bootstrap css compiled is different from the dist one

### ISSUE THREAD

**Issue by hfittipaldi** [twbs/bootstrap#26353]
Hi, there are some differences between bootstrap compiled and the dist one:

Bootstrap compiled (right)
@media (min-width: 768px) {
  .container {
    max-width: 750px;
  }
}
@media (min-width: 992px) {
  .container {
    max-width: 970px;
  }
}
@media (min-width: 1200px) {
  .container {
    max-width: 1170px;
  }
}

And at the dist one (wrong):
@media (min-width: 768px) {
  .container {
    max-width: 720px;
  }
}

The dist one
@media (min-width: 992px) {
  .container {
    max-width: 960px;
  }
}

@media (min-width: 1200px) {
  .container {
    max-width: 1140px;
  }
}

The margins, widths and paddings (at compiled) show 5 decimals insted 6 (not that it will make any difference, but...)

.form-control::-webkit-input-placeholder, :-ms-input-placeholder and ::-ms-input-placeholder are missing at bootstrap compiled

user-select support is missing

appearance support is missing

Some colors are different too. My sugestion is to use rgb as default.

**Comment by patrickhlauke** [comment]
i'm assuming you're not using the build tools, as outlined in http://getbootstrap.com/docs/4.1/getting-started/build-tools/ ?

if not, that's probably the source of the divergence (for instance, the vendor prefixes are generated by autoprefixer http://getbootstrap.com/docs/4.1/getting-started/build-tools/#autoprefixer)

**Comment by hfittipaldi** [comment]
Hi Patrick, I downloaded de bootstrap 4.1 source and compiled it using leafo scssphp compiler.

Thanks.
