### ISSUE TITLE
Bootstrap 4.1.0 Carousal caption text jumps when sliding after adding media queries to caption text

### ISSUE THREAD

**Issue by jtevo** [twbs/bootstrap#26356]
I added below CSS to caption text 

```
.carousal-caption-text {
    font-size: 1.2rem !important;
  }
}

/* Medium devices (tablets, 768px and up) */
@media (min-width: 768px) {

	.carousal-caption-text {
    font-size: 1.5rem !important;
  }
	
}


/* Large devices (desktops, 992px and up) */
@media (min-width: 992px) {
.carousal-caption-text {
    font-size: 1.8rem !important;
  }
	
}

```

This is HTML for the caption part of carousal item:

```
<div class="carousel-caption carousal-caption-text">
<p> some  text </p>
<p> more text </p>
</div>
```

After making caption text responsive Carousal text jumps up from lower position to higher position as the image frame slides in all devices. Jump occurs at end of slide transition for each slide. Very annoying. Any fix?

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._
