### ISSUE TITLE
[css][v4] fix _code.scss error

### ISSUE THREAD

**Issue by SharKoo** [twbs/bootstrap#26366]
line 13 
"word-break: break-word;"
is
"word-wrap: break-word;"
?

**Comment by SharKoo** [comment]
"word-break: break-word;" and "word-wrap: break-word;"" has same effect.
Property "word-wrap" was used in other .scss files of this project,
It may be better? Browser support?

**Comment by mdo** [comment]
Closing as what's there is intended I believe.
