### ISSUE TITLE
Dropdowns Improvement

### ISSUE THREAD

**Issue by mohammadayoub96** [twbs/bootstrap#26360]
### Issue
Issue with Dropdown Menus

### Description

Bootstrap 4 dropdown-menu closes on click, it has to stay be opened.
And offten it opens on second click, this also has to be fixed.

If i have to made Mega Menus then it causes problem for me, I have to add this JS to prevent this error.
Please have a look at this.

### Bootstrap Version
4.1

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by mohammadayoub96** [comment]
Please take a look at dropdowns you will see the problem that i mentioned.

First Problem
-- It often opens on second click.

2nd Problem
-- Drop-down Menu closes on clock.

I uses this JS to prevent this from closing.

//Code used to prevent unexpected menu close when using dropdown components
        // Please add the next JavaScript to your page
    	`$(document).ready(function(){
            $(document).on('click', '.navbar .dropdown-menu', function(e) {e.stopPropagation();});
        });`
