### ISSUE TITLE
bootstrap.min.css broken on GitHub

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [twbs/bootstrap#26367]
When I use...
`<link rel="stylesheet" href="https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.min.css" type="text/css"/>`
...instead of...
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">`
...then the CSS of my site is broken.

URL to my project: http://www.LV-Crew.org

**Comment by DRXDesign** [comment]
Well because the git link is not for that use you can just get the "bootstrap.min.css" and link it into your HTML 
`<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">`
you put the bootstrap.min.css in folder called CSS

**Comment by mdo** [comment]
Yeah, this is GitHub blocking you from hotlinking to their hosted files.

**Comment by wolfy1339** [comment]
If you absolutely must use the version from `v4-dev`, use [RawGit](https://rawgit.com/)

**Comment by Tobias-B-Besemer** [comment]
I use some more Frameworks, hosted on GitHub, where no CDN exist... So I will try RawGit... :-)
