### ISSUE TITLE
Navbar not showing with 4.1.0

### ISSUE THREAD

**Issue by weilinzung** [twbs/bootstrap#26365]
The latest 4.1.0 will hide the navbar because of this.
It looks like load after the custom CSS then overwrite than everything, so I have to put `display: block !important;` to make it show now.

```
.collapse {
  &:not(.show) {
    display: none;
  }
}
```

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._
