### ISSUE TITLE
badge with font-size: smaller is not beautiful.

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26369]
![image](https://user-images.githubusercontent.com/21275217/39152590-24a8c2b4-4749-11e8-943f-16cec3161918.png)

`badge` with `font-size: smaller` is not beautiful.

**Comment by marchershey** [comment]
Looks good to me.. what would you like it to be?

**Comment by mdo** [comment]
There's only so much that can be done for cross browser font rendering. If you're customizing it, be prepared to customize it further, and pay close attention to rendering across Mac and Windows.

**Comment by johnunclesam** [comment]
It is just a problem of padding in the bottom like you see when I use badge in a list-group-item with font smaller. Is there a way we can fix this?
