### ISSUE TITLE
Card Column Issue

### ISSUE THREAD

**Issue by deepakSP** [twbs/bootstrap#26378]
I am Using bootstrap 4.1
card column is not behaving like the way i like to special for small devices.
i have 2 column for small devices and 2 column of first raw never fits in properly ,
and if there is only one column it separate top header and body footer.

here is some screenshoot.

![card1](https://user-images.githubusercontent.com/11506967/39224109-1a31c0ea-4863-11e8-9bec-dd6a04a3961f.png)
![card2](https://user-images.githubusercontent.com/11506967/39224110-1a5b75ac-4863-11e8-8588-83db0403a3bf.png)
![card3](https://user-images.githubusercontent.com/11506967/39224111-1a86e9da-4863-11e8-8cd5-c3df8b9adb68.png)

**Comment by deepakSP** [comment]
after searching here i found out display: inline-block; is the solution but there is no display: inline-block; for small devices.

adding .card { display: inline-block; } for small screen work great

**Comment by mdo** [comment]
> there is no display: inline-block; for small devices.

There is in fact a utility for this, but what you may be running into is a bug we attempted to solve in 4.1 where Chrome was rendering CSS columns differently.
