### ISSUE TITLE
Change box-shadow class with built in shadows utilities for some example page

### ISSUE THREAD

**Issue by adiramardiani** [twbs/bootstrap#26377]
Since bootstrap added built in shadows utilities, I think some example like [off-canvas](https://getbootstrap.com/docs/4.1/examples/offcanvas), [blog](https://getbootstrap.com/docs/4.1/examples/blog), etc page can remove box-shadow class and use bootstrap built in shadows utilities

And example page who not use box-shadow like [checkout](https://getbootstrap.com/docs/4.1/examples/checkout) page can remove box-shadow class in css stylesheet file

**Comment by parammittal16** [comment]
Hi @adiramardiani  I want to work on this issue

**Comment by adiramardiani** [comment]
Of course @parammittal16 , @mdo will glad :+1:

**Comment by parammittal16** [comment]
Thanks a lot. 
Sir these are some builtin bootstrap utilites - 
shadow-sm, shadow and shadow-lg 
I have to apply which one of them and on which examples [here](http://getbootstrap.com/docs/4.1/examples/)

**Comment by parammittal16** [comment]
Sir, I cloned the project from master branch but I didn't get all the examples [here](https://github.com/twbs/bootstrap/tree/master/docs/examples) like pricing example was not there. In the Contribution.md file, it is cleared that we should edit code on master branch but it does not contain all examples. What should I do now ??

**Comment by parammittal16** [comment]
ok sir thank you.

**Comment by parammittal16** [comment]
@adiramardiani @mdo I have opened the pull request [https://github.com/twbs/bootstrap/pull/26493](https://github.com/twbs/bootstrap/pull/26493).
