### ISSUE TITLE
request: bootstrap 4 plugin boilerplate (jquery plugin with babel+eslint  and for webpack)

### ISSUE THREAD

**Issue by rpokrovskij** [twbs/bootstrap#26373]
Bootstrap 4 is masterpeace and is good sample by itself, but it is not easy to extract only those steps that should be used for writing "true" bootstrap 4 plugins. 

Could you create a boilerplate?

P.S. This should include the advice how to communicate with the BS team in case plugin developer need some new tooling (e.g. css variables or "functional classes" the sample could be missed ".placeholder-color" to emulate placeholder text)

**Comment by Johann-S** [comment]
@mdo should we handle that in our documentation ? 🤔 
/CC @XhmikosR

**Comment by rpokrovskij** [comment]
or you can explain it in  any plugin comments.

E.g. I would like to understand what means this line from tooltip.js

` $.fn[NAME].Constructor = Tooltip`

**Comment by rpokrovskij** [comment]
First (as I know) plugin developed for BS4 and using BS4 conventions and tools.
Need your suggestions.

https://github.com/DashboardCode/BsMultiSelect

Also there is need to access some SASS variables in javascript (e.g. as classes)

**Comment by helmutgranda** [comment]
I didn't develop a plugin but following the structure I was able to recreate something similar, it is missing tests for now:

https://github.com/helmutgranda/jquery-plugin-rollup-boilerplate

**Comment by Elia-Sh** [comment]
+1, 
as the original repor
ter noted - 
bootstrap is awesome, webpack is standard de facto,
an end to end example for how to "bootstrap" bootstarp to webpack, 
will be amazing,
the current bootstrap documentation - 
https://getbootstrap.com/docs/4.5/getting-started/webpack/ 
would use a full example of a "boilerplate" package,
like: 
https://github.com/noreading/bootstrap4-webpack-boilerplate
https://github.com/bootpack/bootpack

Especially when the webpack documentation refers to **bootstarp** explicitly at - 
https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules

The migration of bootsrap projects to webpack is not so simple,
and **end to end example** of all loaders, plugins, handling of jQuery dependencies, 
will be highly beneficial by simplifying the this common use case of bootstrap.

**Comment by mdo** [comment]
Closing as stale. Happy to see PRs here if folks want to suggest something.
