### ISSUE TITLE
Margin utilities aren't included in bootstrap-grid.css

### ISSUE THREAD

**Issue by Racso** [twbs/bootstrap#26371]
Margin utilities such as `ml-auto` should be included in `bootstrap-grid.css`. They are even mentioned in the [Grid System documentation](https://getbootstrap.com/docs/4.0/layout/grid/), but right now, those examples don't work if you only include the Grid System.

Is there any reason why those aren't included with the Grid System?

**Comment by Johann-S** [comment]
That's because `bootstrap-grid` is just our grid, and it would be strange to include other feature than our grid in this file.

/CC @andresgalante, @mdo

**Comment by Racso** [comment]
That makes sense, but let me back up a little to see if I'm making sense, too.

Right now, the grid has ways to create columns with a specific width (col-*) and columns with automatic width (col-auto). It also has ways to offset columns by a specific amount (offset-*). What I'm missing is a way to offset columns by automatic amounts (i.e. how to make an "automatic offset"). There's some kind of "feature asymmetry" in there.

I'm new to Bootstrap so I'm probably missing something, but I think that the "margin utilities" (maybe only the "auto" versions?) should be included with the grid. Right now, it feels to me that you can't deal effectively with columns with automatic width because you're lacking some tools in the grid file.

**Comment by mdo** [comment]
We can add these in for v4.2—we'll want them there for sure.
