### ISSUE TITLE
Custom range focus style issue

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#26379]
There is a bug in the focus style of the custom range input. Related on 6c620de01fdbfed50c34849d3d17d601d0bc48d3

https://github.com/twbs/bootstrap/blob/8f7bd419935adfcd53c471a0202083464800619e/dist/css/bootstrap.css#L3740-L3743

It seems that the focus shadow is defined, but this does not apply:
![image](https://user-images.githubusercontent.com/4065765/39226078-18567d60-488b-11e8-9069-50aaaa6c8fcc.png)

Demo: http://getbootstrap.com/docs/4.1/components/forms/#range

The `:focus` selector must be put after the  `.custom-range`: Also, `outline: none;` before the `box-shadow` is unnecessary.

Therefore, it can be fixed as follows:
```css
.custom-range:focus::-webkit-slider-thumb {
   box-shadow: 0 0 0 1px #fff, 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}
```

This fixes add focus shadow, but IE and Edge have new issue of cutting focus shadow.

Chrome:
![image](https://user-images.githubusercontent.com/4065765/39226012-b4704dee-488a-11e8-9f2b-cc1d9eaab029.png)

IE11/Edge
![image](https://user-images.githubusercontent.com/4065765/39226071-07f523b8-488b-11e8-90a4-2eeaf19bb692.png)

Demo: https://codepen.io/anon/pen/BxzyNB

So we should:
+ Remove the wrong focus shadow CSS? (Current style, but has accessibility issue)
+ Fix the focus shadow CSS as above? (IE/Edge has issue)
+ Add an alternative focus style?

**Comment by mdo** [comment]
Oh interesting, I remember running into issues with this one. Was super difficult to even trigger a focus state if memory serves. We should fix the focus styles for sure, and then deal with the IE/Edge issue (at least document it?).

**Comment by ysds** [comment]
OK. The IE/Edge issue will be fixed hopefully. I will create PR later :)
