### ISSUE TITLE
Animations not working for Safari 11.0.2

### ISSUE THREAD

**Issue by rossluebe** [twbs/bootstrap#26376]
As of v4.1 certain animations no longer work in Safari 11.0.2

These are the ones I noticed:
 - the slide animation for carousel [[broken: v4.1](https://getbootstrap.com/docs/4.1/components/carousel/)][[working: v4.0](https://getbootstrap.com/docs/4.0/components/carousel/)]
 - the expand/collapse animation for collapse [[broken: v4.1](https://getbootstrap.com/docs/4.1/components/collapse/)][[working: v4.0](https://getbootstrap.com/docs/4.0/components/collapse/)]

I'll try to dig around later to see if I can't source the problem, but I thought I would submit the issue here as I couldn't find it brought up yet.

**Comment by mdo** [comment]
Do you have reduced motion enabled by chance? https://support.apple.com/kb/PH25204?locale=en_US https://github.com/twbs/bootstrap/pull/25641

**Comment by rossluebe** [comment]
I do, and that's a cool feature. I didn't connect the dots when looking at the ship list.
