### ISSUE TITLE
When buttons is disabled and gradients are enabled, hover state changes background

### ISSUE THREAD

**Issue by jhhazelaar** [twbs/bootstrap#26372]
When a buttons is disabled and gradients are enabled. The hover state of a disabled button change to button hover gradient background. I think this should stay in the disabled state background.

Now it looks weird when disabled and hover changes background of button.

Can't reproduce a codepen example, because I can't enabled gradients without compiling the scss. I think the solution is to change the `background-color` to `background` in the `button-variant` mixin here: https://github.com/twbs/bootstrap/blob/4bc5cc149a104edda9da7d439c2b45810d180d89/scss/mixins/_buttons.scss#L32

- Operating system and version: Mac OS 10.13.4
- Browser and version: Chrome 66.0.3359.117

**Comment by ysds** [comment]
You are right. We should add  `background-image: none ` like dropdown items?

https://github.com/twbs/bootstrap/blob/14f712601edf87aa4e2e65243775682b1270124e/scss/_dropdown.scss#L136-L144

**Comment by jhhazelaar** [comment]
Yes exactly! That's the solution
