### ISSUE TITLE
The main role is unnecessary for element main.

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#26388]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fgetbootstrap.com%2Fdocs%2F4.1%2Fgetting-started%2Fintroduction%2F

**Comment by patrickhlauke** [comment]
for compatibility with IE11 (which hasn't implemented the element at all, so has no implict role tied to it), it is. see http://www.html5accessibility.com/
