### ISSUE TITLE
Fix needed in 4.1 Docs: Utilities - Text - Monospace

### ISSUE THREAD

**Issue by VasilisParaschos** [twbs/bootstrap#26387]
In 4.1 Docs: Utilities - Text - Monospace (https://getbootstrap.com/docs/4.1/utilities/text/#monospace) I found two instances of "font-monospace" that should be replaced with "text-monospace".

Line numbers in HTML: 507 and 509

**Comment by phax** [comment]
I also just stumbled upon the same issue right now :)

**Comment by coliff** [comment]
I think this will be fixed in 4.1.1 with this PR #26239

**Comment by VasilisParaschos** [comment]
Yes, so it seems!!
