### ISSUE TITLE
Table not working the way I want them too PLEASE HELP ME !!! LOL 

### ISSUE THREAD

**Issue by Swapun** [twbs/bootstrap#26384]
Hey Guys I cant for the love of life it my tables to work I'm not sure what i'm doing wrong or is it just it wont work I have software i using for my business I had a image on there and it worked fine but now I want it to where my users can click on the Facebook or other services but everything I use the code to place the table it keeps dropping downward 

I was using the code as a test `<table width="838">
<thead>
<tr>
<th>[HEADER]</th>
<th>[HEADER]</th>
<th>[HEADER]</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="http://www.liftedfromdarkness.com/wp-content/uploads/2015/08/lifted-fb.png" alt="" width="265" height="120" /></td>
<td><img src="http://www.liftedfromdarkness.com/wp-content/uploads/2015/08/lifted-fb.png" alt="" width="265" height="120" /></td>
<td><img src="http://www.liftedfromdarkness.com/wp-content/uploads/2015/08/lifted-fb.png" alt="" width="265" height="120" /></td>
</tr>
</tbody>
</table>`

but the outcome is always the same does anyone have a trick or something I can do to make this work I thought at first it could be because I was missing something but I don't know what it can be and I also thought it because the box is small so I would open a invoice from a user and its still shows the same it's like it wont go from right to left at all it just drops down can  someone please help me Thanks

![test](https://user-images.githubusercontent.com/12092955/39279794-eceb0fa2-48c0-11e8-861e-11c81c5a2dd5.png)

**Comment by browner12** [comment]
Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Bootstrap Slack (https://bootstrap-slack.herokuapp.com/)
StackOverflow (https://stackoverflow.com/questions/tagged/twitter-bootstrap)

Thanks!
