### ISSUE TITLE
button-outline-variant focus box-shadow not set using variable

### ISSUE THREAD

**Issue by DavidCzadilek** [twbs/bootstrap#26380]
Tried to remove the button focus box-shadow for outline buttons by setting the variable:
`$btn-focus-box-shadow:        none;`

Currently only overwriting the property or setting `$btn-focus-width` to 0 produces the desired result.
The reason for that seems to be that the button shadow utilizes the button theme color, which currently wouldn't be able to be passed down using a variable:
https://github.com/twbs/bootstrap/blob/4bc5cc149a104edda9da7d439c2b45810d180d89/scss/mixins/_buttons.scss#L69-L72

And here as well..
https://github.com/twbs/bootstrap/blob/4bc5cc149a104edda9da7d439c2b45810d180d89/scss/mixins/_buttons.scss#L87-L94

The naming of variable `$btn-focus-width` is also quite confusing. Shouldn't it be more appropriately `$btn-focus-box-shadow-width` according to variable naming conventions?

Proposal:
Rename `$btn-focus-width` to `$btn-focus-box-shadow-width`
Add `$btn-outline-focus-box-shadow` bool variable to output box-shadow only when set to true.

**Comment by CaitlinWeb** [comment]
I noticed the same issue but for `@button-variant` as well. So it's all buttons and not just the outline variants that has this issue. For `@button-variant` it's using `$border` for the `box-shadow` color, not at all what I'd expect.

Why don't both mixins use `$btn-focus-box-shadow`? Note that `@form-control-focus`, for inputs, is how I would expect it to be.

**Comment by mdo** [comment]
Closing as a won't fix. To disable the shadows, use the `$enable-shadows` variable. We can deal with variable names in v5 when breaking changes are back on the table :).

**Comment by Wellusioner** [comment]
> Closing as a won't fix. To disable the shadows, use the `$enable-shadows` variable. We can deal with variable names in v5 when breaking changes are back on the table :).

`$enable-shadows` is not working in v5 too.

I had to do this:
```
$btn-active-box-shadow : none;
$btn-focus-box-shadow : none;
$btn-box-shadow:unset;
$btn-focus-width:0;
```
