### ISSUE TITLE
Navbar Title and menu element alignment

### ISSUE THREAD

**Issue by ruudvddries** [twbs/bootstrap#26386]
Hi!

is it just my OCD or is it true that the navbar title and the following menu items are not aligned (but probably are aligned to the center of both texts)

![image](https://user-images.githubusercontent.com/3681276/39291403-319c4e3c-4933-11e8-8078-2cf03b948b6c.png)

Is it possible to align the elements to the bottom of the letters?

best regards,

Ruud

**Comment by mdo** [comment]
Could be if we play with the flexbox alignment and try out the `baseline` option instead of `center`.

**Comment by LarryAzevedo** [comment]
@ruudvddries It honestly looked **good** to me when I first saw your screenshot.

**Comment by mdo** [comment]
Closing as a won't fix.
