### ISSUE TITLE
Accordion Example: ID and class duplicated in v. 4.1

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#26389]
4.0
https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example
`<div id="accordion">`

4.1
https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example
`<div class="accordion" id="accordion">`

why?

**Comment by Johann-S** [comment]
a bit weird yes, because we don't have `.accordion` in our CSS 🤔

**Comment by patrickhlauke** [comment]
https://github.com/twbs/bootstrap/commit/c0246e926f0e9e955f34b34286f97cc201582ba1

**Comment by AlessandroVecchi** [comment]
I think it would be better:
`<div class="accordion" id="accordionExample">`

**Comment by Johann-S** [comment]
Closed thanks to @patrickhlauke 👍

**Comment by patrickhlauke** [comment]
yeah the `id` could be tweaked for clarity

**Comment by patrickhlauke** [comment]
https://github.com/twbs/bootstrap/pull/26391
