### ISSUE TITLE
Using select breaks td height (and borders) in chrome due to calculated height

### ISSUE THREAD

**Issue by andrewtch** [twbs/bootstrap#26381]
![image](https://user-images.githubusercontent.com/925330/39237598-a6bbe6dc-4884-11e8-8096-aa8408d6e358.png)

Subj; the same issue still persists in `td > select.form-control` structure and in `td > .form-group select.form-control` structure. Issue is specific in Chrome, FF renders OK. Issue appears due to this line https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L60 .

Is there a general workaround for this issue / is it a known Chrome issue?

**Comment by mdo** [comment]
No plans to change this, the height is required for cross browser friendly form control rendering.
