### ISSUE TITLE
IE8-9 support

### ISSUE THREAD

**Issue by gustavoomacedo** [twbs/bootstrap#26398]
When will version 4 support IE9 and earlier versions?
The version 4 is awesome but needs support for all versions of browsers.

Thank you.

**Comment by gilbertoalbino** [comment]
BS4 will not be compatible to IE versions lesser than 10. There's no suport for modern features in IE 9 or lesser.
Internet Explorer 10+ is supported; IE9 and down is not. Please be aware that some CSS3 properties and HTML5 elements are not fully supported in IE10, or require prefixed properties for full functionality. Visit Can I use… for details on browser support of CSS3 and HTML5 features.

If you require IE8-9 support, use Bootstrap 3. It’s the most stable version of our code and is still supported by our team for critical bugfixes and documentation changes. However, no new features will be added to it

**Comment by patrickhlauke** [comment]
indeed, what @gilbertoalbino said.
