### ISSUE TITLE
Is Our Campus Network Being Blocked by BootstrapCDN?

### ISSUE THREAD

**Issue by profmiller** [twbs/bootstrap#26394]
Weird question, right?

I teach front-end development courses at a SUNY school and none of our networked workstations can successfully connect to the Bootstrap Library. The "Quick Start" page takes a very long time to load, and when it does, there is no styling. When the page [finally] renders, it uses the browser default styles.

I logged a ticket with our network administrator thinking that it was a firewall issue, but I have been assured that it is not. Is there any reason that bootstrapcdn.com would block all requests from our network domain?

**Comment by wolfy1339** [comment]
This isn't related to Bootstrap directly. Try using [cdnjs](https://cdnjs.com/libraries/twitter-bootstrap) instead

**Comment by profmiller** [comment]
Thanks. Good solution. Any idea what is causing this? Is it the move from MaxCDN to StackpathCDN?The people at Stackpath told me to contact Bootstrap directly.

**Comment by profmiller** [comment]
Sentinel was blocking the IP for stackpath.bootstrapcdn.com (205.185.216.10). Apparently stackpath.bootstrapcdn.com is hosted on an IP that also hosts malware for mobile phones. The alert that caused this issue appears to be legitimate. We were able to download the file masquerading as a .jpg image - it turned out to be an Android application.

**Comment by mdo** [comment]
cc @jdorfman

**Comment by jdorfman** [comment]
@profmiller thanks for the report. I reached out to support and they updated the ip.

----

Hello Justin,

The change has been completed successfully on your bootstapcdn (j3z9t3p6) site. Please see the following cases:

Before Change:

```
$ curl -IX GET "https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
HTTP/1.1 200 OK
Date: Fri, 27 Apr 2018 00:25:18 GMT
Connection: Keep-Alive
Accept-Ranges: bytes
ETag: 1523290490
Cache-Control: max-age=31536000
Content-Length: 140421
Content-Type: text/css; charset=utf-8
Last-Modified: Mon, 09 Apr 2018 16:14:50 GMT
X-Hello-Human: Say hello back! @getBootstrapCDN on Twitter
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
X-Cache: HIT
```
```
$ dig +noall +answer stackpath.bootstrapcdn.com
stackpath.bootstrapcdn.com. 288 IN  CNAME   cds.j3z9t3p6.hwcdn.net.
cds.j3z9t3p6.hwcdn.net. 179 IN  A   205.185.216.42
cds.j3z9t3p6.hwcdn.net. 179 IN  A   205.185.216.10
After Change:
```

```
$ curl -IX GET "https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
HTTP/1.1 200 OK
Date: Fri, 27 Apr 2018 00:32:28 GMT
Connection: Keep-Alive
Accept-Ranges: bytes
ETag: 1523290490
Cache-Control: max-age=31536000
Content-Length: 140421
Content-Type: text/css; charset=utf-8
Last-Modified: Mon, 09 Apr 2018 16:14:50 GMT
X-Hello-Human: Say hello back! @getBootstrapCDN on Twitter
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
X-Cache: HIT
```

```
$ dig +noall +answer stackpath.bootstrapcdn.com
stackpath.bootstrapcdn.com. 300 IN  CNAME   cds.j3z9t3p6.hwcdn.net.
cds.j3z9t3p6.hwcdn.net. 300 IN  A   209.197.3.15
```

You can monitor DNS propagation here: https://www.whatsmydns.net/#A/stackpath.bootstrapcdn.com

**Comment by profmiller** [comment]
Thank you for your prompt support and attention. While unfortunate, this situation turned into an excellent learning experience for our students. They now understand the procedure for determining what is causing this type of problem. And, the importance of finding an alternative method to keep their projects on schedule.

**Comment by jdorfman** [comment]
It should have been faster but I'm glad there was a silver lining. =)
