### ISSUE TITLE
Navbar collapse not working in IE11

### ISSUE THREAD

**Issue by srvnkmr-sk** [twbs/bootstrap#26399]
Getting below error in IE11 on clicking toggle button to close navlinks.

Same exists even in bootstrap site. https://getbootstrap.com/docs/4.1/components/navbar/

![image](https://user-images.githubusercontent.com/5716859/39347977-d80e256c-4a12-11e8-95bc-9da096aa68c5.png)

**Comment by CodeDead** [comment]
https://github.com/twbs/bootstrap/pull/26291

**Comment by Johann-S** [comment]
The PR linked by @CodeDead fix this issue, and will be available in our next release 👍

**Comment by srvnkmr-sk** [comment]
pls guide me on how to update the fix mentioned in #26291 in bootstrap.min.js file
