### ISSUE TITLE
Install bootstrap3

### ISSUE THREAD

**Issue by swaps19** [twbs/bootstrap#26392]
I am trying to install `bootstrap 3` using `npm`. But its installing the latest `4.1.0`.
Is there any way I can get the `bootstrap 3.3.5` version?

I am running `npm install bootstrap --save-dev`.

> P.S. - Output for `npm view bootstrap dist-tags ` is `{ latest: '4.1.0' }`.

**Comment by skmedix** [comment]
`npm install bootstrap@3.3.7`

**Comment by swaps19** [comment]
Closing.
Thanks. :smiley:
