### ISSUE TITLE
Feature: Extract Bootstrap Reboot into a mixin

### ISSUE THREAD

**Issue by ahasall** [twbs/bootstrap#26396]
Hello,

I propose that we extract the content of `_reboot.scss` into a mixin.

This will make possible for library authors building on top of Bootstrap, to provide to their users the ability to enable or disable reboot.

## Current situation:
Today the use of `Reboot` is determined by whether the file is imported or not.

## Desired situation:
in `bootstrap/scss/_variables.scss`:
```scss
$enable-reboot: true !default;
````
in `bootstrap/scss/_reboot.scss `
```scss
@if $enable-reboot {
    @include reboot();
}
```
With this architecture, as library author, my users user have the choice to use disable `Reboot`. I do not force them to use them if they use another reset file. And disabling `Reboot` would be as easy as writing `$enable-reboot: false;`.

This won't introduce any breaking change.
If you all agree, I will make a PR.

Thanks,
Amadou

**Comment by mdo** [comment]
We include Reboot because it's pretty essential to the rest of the framework. There's no reason to make this an optional flag, and would break many things if you removed it.

**Comment by ahasall** [comment]
Hello @mdo,
What about creating a mixin `bootstrap/scss/mixins/_reboot.scss` and include it in `_reboot.scss`.

This way, anybody who want to leverage the modularity of Bootstrap, and include `Reboot` conditionally will be able to do that. And nothing will break.

**Comment by patrickhlauke** [comment]
you seem to misunderstand what "pretty essential to the rest of the framework" means. if it's included conditionally, and somebody doesn't include it, all other styles applied by bootstrap are likely to break/behave oddly on different browsers.

**Comment by ahasall** [comment]
@patrickhlauke,
I think you didn't understand my second comment. But it was my fault because I wasn't not vey clear.

What I wanted to say is this:
1. we create a mixin, `bootstrap/scss/mixins/_reboot.scss`, containing all the code that is currently at `boostrap/scss/_reboot.scss`
2. we replace the content of `boostrap/scss/_reboot.scss` with:
```scss
@include reboot();
```
This is just a refactoring. It won't do any harm to any Bootstrap user.

Then me, as a library author building on top of Bootstrap, I will be able to leverage the reboot mixin to do some stuff conditionally.

I hope that my explanations are more clear now.

**Comment by mdo** [comment]
> can we have a mixin that provides the content of Bootstrap Reboot?

Nope, no plans to add this. Conditional imports are already possible with `@import` queries. If you need it, import it :).

**Comment by ahasall** [comment]
Okay.
Thank you very much.
