### ISSUE TITLE
Carousel with previous and next item

### ISSUE THREAD

**Issue by noook** [twbs/bootstrap#26395]
It is currently impossible to build a carousel that allows us to preview the previous and the following item, that's too bad, we don't always need our items to be full width

**Comment by Johann-S** [comment]
Maybe a CodePen of your use case would help us to find a solution 😉

**Comment by LarryAzevedo** [comment]
I feel like this is one of those things that would be a separate plugin; not part of the core functionality.

**Comment by mdo** [comment]
Punting as a won't fix.
