### ISSUE TITLE
Missing classes in SCSS Files

### ISSUE THREAD

**Issue by oaltmann** [twbs/bootstrap#26405]
Hi!
I use the bootstrap 4.1.0 version and I find a issue. The css and scss files are different. In the scss file i don't find the .d-none class and other classes for the grid rendering. Is that possible?

**Comment by morrissey-ingenious** [comment]
Its located here.
[https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_display.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_display.scss)
