### ISSUE TITLE
Asp.net LIstView and bootstrap 4 

### ISSUE THREAD

**Issue by santoslopes** [twbs/bootstrap#26415]
Hi
Problems with listVidew and bootstrap 4. Please look at http://programamos.pt/cheirabem/eric.aspx
The last item allways misconfigured. Please look at my code and tell me why:
`
<head>
    <title></title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body> 
<div class="row">
        <div class="col-md-12 pt-1 ml-4">            
                    <asp:ListView ID="ListView1" runat="server" GroupItemCount="3" GroupPlaceholderID="groupPlaceHolder1" ItemPlaceholderID="itemPlaceHolder1" DataSourceID="SqlDataSource1">
                        <EmptyDataTemplate>
                            <table runat="server" style="">
                                <tr>
                                    <td></td>
                                </tr>
                            </table>
                        </EmptyDataTemplate>
                        <LayoutTemplate>
                            <div class="row text-center">
                                <asp:PlaceHolder runat="server" ID="groupPlaceHolder1"></asp:PlaceHolder>
                            </div>
                        </LayoutTemplate>
                        <GroupTemplate>
                            <hr />                            
                            <div class="row text-center">                               
                                <asp:PlaceHolder runat="server" ID="itemPlaceHolder1">
                                </asp:PlaceHolder>
                            </div>                          
                        </GroupTemplate>
                        <ItemTemplate>
                            <div class="col-md-4 ">
                                <div class="card-deck">
                                <div class="card">
                                    <div class="card-header">
                                        <asp:Label ID="Label2" runat="server" Text='<%#Eval("sku")%>'></asp:Label>                                       
                                    </div>
                                    <div class="card-body">                                       
                                    </div>
                                    <div class="card-footer">
                                        <asp:Label ID="Label1" runat="server" Text='<%#Eval("descricao")%>'></asp:Label>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </ItemTemplate>                        
                    </asp:ListView>             
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:perfumes %>" ProviderName="<%$ ConnectionStrings:perfumes.ProviderName %>" SelectCommand="select * from perfumes where marca =&quot;Azzaro&quot; LIMIT 4 "></asp:SqlDataSource>
</body>
`

**Comment by patrickhlauke** [comment]
Please see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
