### ISSUE TITLE
add new tool's class ".h-input" to set the css min-height to $input-height variable

### ISSUE THREAD

**Issue by rpokrovskij** [twbs/bootstrap#26412]
```
.h-input {
    min-height: #{$input-height};
}

```
this is usefull when you want to make "input field emulation" (e.g."multiselect") using "div" panel that "looks like input" and want to prevent its collapse when it is empty.  

create panels that "looks like input" is quite common situation for plugin developers.

why not to include it to my plugin.css ?
because it is not a really customizable style of plugin. it is something that inherited from bootstrap and I will be more happy to hardcode addClass("h-input") .

**Comment by mdo** [comment]
Thanks for the suggestion, but we'll pass on it for now.

**Comment by rpokrovskij** [comment]
so what is your suggestion on how to get "input height" variable in plugin code?
