### ISSUE TITLE
A fix for proper anchor links inside .tabs

### ISSUE THREAD

**Issue by Hydra9268** [twbs/bootstrap#26427]
Hi, all! 

I encountered the bootstrap.js:1729 Uncaught Error: Syntax error, unrecognized expression: error, and decided to try and fix it myself. The following are the results I came up with:

```
    Tab.prototype.show = function() {

        var $this = this.element;
        var $ul = $this.closest('ul:not(.dropdown-menu)');
        var selector = $this.data('target');

        if (!selector) {
            selector = $this.attr('href')
            selector = selector && selector.replace(/.*(?=#[^\s]*$)/, '') //strip for ie7
        }

        var isTabSelector = new RegExp("[\#]").exec(selector);
        isTabSelector = (isTabSelector == null) ? false : true;

        if (isTabSelector) {

            if ($this.parent('li').hasClass('active')) return

            var previous = $ul.find('.active:last a')[0]
            var e = $.Event('show.bs.tab', {
                relatedTarget: previous
            })

            $this.trigger(e)

            if (e.isDefaultPrevented()) return

            var $target = $(selector)

            this.activate($this.parent('li'), $ul)
            this.activate($target, $target.parent(), function() {
                $this.trigger({
                    type: 'shown.bs.tab',
                    relatedTarget: previous
                });
            });
        }
        else
        {
            if (selector.indexOf('http') >= 0)
            {
                window.open(selector);
            }
            else
            {
                window.open(window.location.origin + selector);
            }
        }
    }
```

In this fix, the logic first checks for the presence of a pound in the href (which we know is native to Bootstrap tabs). If found, the code proceeds as expected. If not detected, then the logic switches to regular href link. The "(selector.indexOf('HTTP') >= 0)" checks to see if the link has a full URI via 'HTTP' (e.g. external link). Otherwise, it uses window.location.origin for the domain and appends the selector variable (e.g. internal link). This fix applies to jQuery v1.11.3 and Bootstrap v3.1.1.

Hope this helps you all. :)

Referenced error:
![image](https://user-images.githubusercontent.com/932134/39447537-ef243370-4c76-11e8-94e6-0dc9b503ae37.png)

Referenced Stackoverflow discussion
https://stackoverflow.com/questions/35539374/bootstrap-dropdown-jquery-uncaught-error-syntax-error-unrecognized-expression/49517080

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by Hydra9268** [comment]
I wasn't asking for the code to be included in Bootstrap 3.x. The fix is meant for someone to manually patch up their bootstrap.js file.
