### ISSUE TITLE
Fix a typo in the docs

### ISSUE THREAD

**Issue by eyal0803** [twbs/bootstrap#26428]
Sorry for the vague issue title but I have no idea how to fix this since the source of the examples in the docs are not in the Markdown files of the docs. If someone knows how to do this please do tell.

Under [Monospace](https://getbootstrap.com/docs/4.1/utilities/text/#monospace), in the [Utilities](https://getbootstrap.com/docs/4.1/utilities) docs for [Text](https://getbootstrap.com/docs/4.1/utilities/text/), the instructions for using monospace are correct, which state to use the `.text-monospace` class, but the example uses `.font-monospace`, which doesn't exist in Bootstrap.

Again, sorry for the issue instead of a PR.

**Comment by eyal0803** [comment]
Force refreshing does fix it temporarily.

**Comment by mdo** [comment]
Yup, should be good to go now. Purged our cache.
