### ISSUE TITLE
Issue with Carousel on Bootstrap 4.1 docs after v4.1.1 release

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26426]
Hi, I've noticed an issue with your Carousel on the Bootstrap docs since the v4.1.1 release. If you clear your browser cache and try clicking the left/right arrows or even on the indicators the page will just jump down to the carousel like an on page anchor rather than functioning correctly:

https://getbootstrap.com/docs/4.1/components/carousel/#carouselExampleIndicators

**Tested on**

Windows 7, Latest version of Chrome

**Comment by sts-ryan-holton** [comment]
Seems to be some weird Cache related problems going on with the Bootstrap website.

If you clear your browser Cache and refresh it loads the new 4.1.1 release, but every refresh after that seems to only load the 4.1.0 version.

As you can see I referenced this problem in another issue that someone else is having the same problem, any ideas?

**Comment by mdo** [comment]
Guessing this is something going on with Cloudflare. Let me look into it.

**Comment by mdo** [comment]
Just purged the cache. Should be set now!

**Comment by sts-ryan-holton** [comment]
@mdo  I'm still experiencing this problem, cleared browser cache multiple times, have been checking throughout the day, in particular on this page is a good test -> https://getbootstrap.com/docs/4.1/components/carousel/

the indicators for the carousel. Try clearing your browser cache, it'll then work, but refresh normally after that and `cursor: pointer` is missing which I assume is related to some additional cache problems?
