### ISSUE TITLE
Dropdown - The OFFSET option does not work when used as a navbar menu item

### ISSUE THREAD

**Issue by emage** [twbs/bootstrap#26424]
I am using the dropdown offset option to slightly push the dropdown menu below the main navbar.  However, it seems to not be working.

As a standalone link outside the navbar it seems to work.  What am I missing?

here is the demo pen: 
https://codepen.io/anon/pen/ELWyyO

**Comment by Johann-S** [comment]
That's right we do not use Popper.js for Dropdown in navbar, we should add a notice in our documentation 🤔

**Comment by tsmuse** [comment]
Is there some reason why I wouldn't want to manually add popper to my navbar dropdowns? The current setup makes putting a dropdown in a right-aligned nav group in a navbar create a menu that bleeds off the right edge of the viewport, which is not ideal.

**Comment by Johann-S** [comment]
I thinks it's due to your implementation @tsmuse, if you can provide a CodePen we'll help you

**Comment by tsmuse** [comment]
I hope it's just an implementation issue. I've put the stripped down version of what I'm doing here: 
https://codepen.io/tsmuse/pen/yxWQgp

I expected the dropdowns on the right side of the navbar to flip when they hit the edge of the viewport, I tried setting the boundary property explicitly when it didn't and when that didn't work I found this post saying that Popper wasn't being used in this case. 

Thanks for the help :)

**Comment by mdo** [comment]
Closing this as a stale won't fix—as @Johann-S mentioned, we don't position dropdowns in the navbar with Popper.
