### ISSUE TITLE
Extract navbar themes into separate file

### ISSUE THREAD

**Issue by sevab** [twbs/bootstrap#26421]
Would it be worthwhile extracting `.navbar-light` and `.navbar-dark` into a separate file, say `navbar-themes.scss`, so those who define their own themes can exclude them from final build? Together they take ~2.5kb.

**Comment by mdo** [comment]
I'm leaning toward no given none of our theming capabilities or modifier classes are isolated to separate files for any other components. They're all baked in by default. We can keep this in mind for a future release though.
