### ISSUE TITLE
Sizing utility is not responsive friendly

### ISSUE THREAD

**Issue by andrewpucci** [twbs/bootstrap#26429]
The [sizing utility](https://getbootstrap.com/docs/4.1/utilities/sizing/) does not provide responsive variations. For example, you cannot use `.w-lg-75` to assign a 75% width to an element only on large screens and up.

**Comment by mdo** [comment]
There are no plans to add these responsive variants at this time. There are some older issues and PRs that aimed to do this if you're curious to look them up.
