### ISSUE TITLE
toggle doesn't close the dropdown if there are no [data-toggle="dropdown"]

### ISSUE THREAD

**Issue by rpokrovskij** [twbs/bootstrap#26420]
ver 4.1

I've created Dropdown in javascript

```
 $(this.dropDownMenu).dropdown({
                    placement: 'bottom-start',
                    flip: false,
                    reference: this.filterInput
                });
```
dropDownMenu `<ul>` element contains both `dropdown` `dropdown-menu` 

first point: `toggle` method open it  (btw `dropdown` class is vital there, without it plugin doesn't work - why?)

second point: `toggle` doesn't close it. 

Through debugger I see this logic

```
           // bootstrap dropdown code
          var context = $$$1(toggles[i]).data(DATA_KEY);
          var relatedTarget = {
            relatedTarget: toggles[i]
          };

          if (!context) {
            continue; // here we enter
          }
         //  remove `show`  class will be never passed.
```

I expecect that Dropdown could be opened and closed manually (through JS) - then requrements to have toggles is excessive (the same is true for `dropdown` class requirement - you use it to find `dropdown-menu` but if dropdown-menu by itself is an jquery element - it still should work )

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by rpokrovskij** [comment]
Johan, first of all I would like to know does it sounds as a bug: `data-toggle="dropdown"` required.
May be this is normal behaviour.

**Comment by Johann-S** [comment]
Yep `data-toggle="dropdown"` is a requirement for us, it's the only way to be sure there is only one dropdown open (see: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L336)

**Comment by rpokrovskij** [comment]
Then it just should be added to documentation: `dropdown-menu` is not enough to use Dropdown plugin from JavaScript there should be corresponded `dropdown` and `data-toggle="dropdown"` on the form (even if you do not really need them since you are using JavaScript events ). 

P.S. I have tried to use it as autosuggestion (that means my toggle is keyup)

**Comment by XhmikosR** [comment]
@Johann-S: is this still an issue (docs update)?

**Comment by Johann-S** [comment]
yep we should update our docs

**Comment by chamnap** [comment]
It happens to me the same as @rpokrovskij.

When adding `data-toggle='dropdown'`, the initialization is already done by the data api on the document level, https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L515. Therefore, we cannot manually initialized it.

Without `data-toggle='dropdown'`, the dropdown doesn't itself when clicking outside.

Any workarounds for now?

**Comment by mkleehammer** [comment]
Same.  To be clear, I think OP is looking for a way to have a manually controlled dropdown without the automatic data-api triggering it to open.

In my case I'd like to display a dropdown under search input group, but I don't want the user toggling it open and closed while the search is still executing.  I'll find a workaround, but it would be simpler if there was an alternative markup that would stop the built-in event handler.  (I'll probably go adding the "disabled" class to the input group, which I see the dropdown looks for.  Not sure where that rabbit trail leads, though.)

**Comment by nteetor** [comment]
I ran into this issue trying to using a text input as a dropdown toggle. I want to allow the user to click around in and edit the input's text value without triggering the menu. Adding and removing the `disabled` class did solve some of the related problems, i.e. clicking in the input no longer triggers the menu. However, adding the `disabled` class prevents some of the dropdown keyboard interactions.

**Comment by mdo** [comment]
Docs state the requirement about the data attribute in a (hopefully obvious) callout. https://getbootstrap.com/docs/4.5/components/dropdowns/#via-javascript

https://github.com/twbs/bootstrap/commit/f3d0fee91ec30aa6cde08de821b06fd6f337a3a3

Beyond that, I don't think there are any planned changes to how dropdowns work here unless @Johann-S wants to revisit things.

**Comment by Map-function** [comment]
@chamnap https://affront-aspen.github.io/pyzmq/
