### ISSUE TITLE
Bootstrap 4.1.1 docs search pointing to 4.0.0??

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26436]
I've just tried using the search on the docs, seems to be pointing to 4.0.0 docs? I've cleared my browser cache? Anyone getting this issue?

**Comment by coliff** [comment]
This has been reported before:
https://github.com/twbs/bootstrap/issues/26397
I think you can close your issue as a duplicate.

**Comment by sts-ryan-holton** [comment]
Awesome! Hope this issue gets addressed quickly! :)
