### ISSUE TITLE
Long dropup menu in footer doesn't position as expected

### ISSUE THREAD

**Issue by guoyunhe** [twbs/bootstrap#26435]
https://codepen.io/guoyunhebrave/pen/rvyZLE

![screenshot_20180501_101752](https://user-images.githubusercontent.com/5836790/39464931-0e8c24f4-4d29-11e8-9422-b6136686f618.png)

Dropup became "dropdown" direction.

**Comment by Johann-S** [comment]
That's the normal behavior, if you want to disable the `flip` behavior use: `data-flip="false"` see: https://getbootstrap.com/docs/4.1/components/dropdowns/#options
