### ISSUE TITLE
Bootstrap Homepage is buggy

### ISSUE THREAD

**Issue by legionio** [twbs/bootstrap#26432]
When loading https://getbootstrap.com and looking in the console, there are various 404 errors as seen in the picture. This stops the the version selector top right of the nav from working correctly. 
There maybe more problems as a result but I haven't looked further.

Tested on MacOS 10.13.4 High Sierra with Chrome Version 65.0.3325.181 (Official Build) (64-bit) & on Incognito mode & on Windows 10 with Edge Version 41.16299.371.0. 

<img width="1680" alt="screen shot 2018-05-01 at 03 55 29" src="https://user-images.githubusercontent.com/16267903/39459464-aad65eaa-4cf3-11e8-8053-3102638d4c2e.png">

**Comment by lazarohcm** [comment]
It seems to be working fine in here. 
Maybe cleaning your browser cache?

**Comment by mdo** [comment]
Just pushed up a fix for the homepage. Some of this is something else, but I can confirm at least one broken URL on the homepage.

**Comment by Kopyov** [comment]
URL with https:// opens 4.0.0 homepage, with http:// 4.1.1
