### ISSUE TITLE
Nav dropdown blurry

### ISSUE THREAD

**Issue by 01CodeLT** [twbs/bootstrap#26445]
The nav text in the nav dropdown seems to be blurry, I turned off the transform property in the element (    transform: translate3d(5px, 41px, 0px)) and it went back to normal, but this property seems to be added inline by js.

![blurred dropdown](https://user-images.githubusercontent.com/11212855/39568070-ede64ffe-4eb8-11e8-9a7b-3deb926a448b.PNG)

**Comment by rohit2sharma95** [comment]
Same issue with me, it would be good if there will be any option to disable the popper.js on particular element.
Like:
`$('.dropdown-toggle').dropdown({
    "popperjs" : false
})`

**Comment by Sir-Genius** [comment]
You can do this with [display: static](http://getbootstrap.com/docs/4.1/components/dropdowns/#options).

**Comment by Johann-S** [comment]
Or you can disable gpu Acceleration in Popper.js with: 
```js
Popper.Defaults.modifiers.computeStyle.gpuAcceleration = false;
```

Closed because it's not a Bootstrap issue and you have solutions 😉
