### ISSUE TITLE
Documentation search redirects to v4.0 instead of v4.1

### ISSUE THREAD

**Issue by yamenarahman** [twbs/bootstrap#26444]
I noticed that in the latest documentation whenever I search for anything the page redirects to previous version of Bootstrap, I'm managing to fix this with a PR but I couldn't find where it is, So where can I fix this in this repo?

**Comment by sts-ryan-holton** [comment]
Already mentioned this :) => https://github.com/twbs/bootstrap/issues/26441

**Comment by mdo** [comment]
Closing as duplicate of #26441.
