### ISSUE TITLE
select (38px) in form has less height than input element in the form(46.38px)

### ISSUE THREAD

**Issue by gauravsinghaec** [twbs/bootstrap#26440]
Below are the screenshot taken in chrome browser, windows 10
select.form-control
![image](https://user-images.githubusercontent.com/15084301/39530580-e9767574-4e46-11e8-9aa2-801968bece48.png)

input.form-control
![image](https://user-images.githubusercontent.com/15084301/39530708-258628ca-4e47-11e8-9532-b9528509342a.png)

**Comment by gauravsinghaec** [comment]
@mdo please check it. I saw the earlier issue #20809 and #20874 but please comment on the issue I am facing.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by gauravsinghaec** [comment]
@mdo Please find below link.I see the default top, bottom padding is 6px so my code is basically adding total 8px in y direction. When I add padding top, bottom as 10px in input and select element then the height of select element (i.e 38px) remains same but the height of input element is changed (i.e 38px to 46px). 
https://jsbin.com/dosewifiya/edit?html,output

**Comment by mdo** [comment]
You need to change the `height` on the select. Selects are difficult to style consistently across browsers, so they get an explicit instead of implicit height.

**Comment by gauravsinghaec** [comment]
Indeed I did the same but was waiting for your response. Thanks a lot.
select.form-control:not([size]):not([multiple]) {
  height: calc(2.77rem + 2px);
}

**Comment by Quix0r** [comment]
Which version has fixed this issue? I'm having the same here with 4.0.

**Comment by oweskeez** [comment]
Still present in 4.2.1

**Comment by robinmalik** [comment]
Fixed in 4.3.1 for me! 👏
