### ISSUE TITLE
BUG: modal after modal (fade/transition mode)

### ISSUE THREAD

**Issue by multigcs** [twbs/bootstrap#26454]
sorry for my english :)

if i close a modal and direct after open an new modal and fade is active,
the class in body will removed after the new modal is all ready open.
so the overflow will affect on the body, not on the modal.

FIX: bootstrap.js

--- modal.js.org	2018-05-04 18:20:23.851752230 +0200
+++ modal.js	2018-05-04 18:22:37.011368935 +0200
@@ -186,6 +186,7 @@
 
 
       if (transition) {
+        $(document.body).removeClass(ClassName.OPEN)
         const transitionDuration  = Util.getTransitionDurationFromElement(this._element)
 
         $(this._element)
@@ -310,7 +311,6 @@
       this._element.setAttribute('aria-hidden', true)
       this._isTransitioning = false
       this._showBackdrop(() => {
-        $(document.body).removeClass(ClassName.OPEN)
         this._resetAdjustments()
         this._resetScrollbar()
         $(this._element).trigger(Event.HIDDEN)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by multigcs** [comment]
here you can see the problem:
https://codepen.io/multigcs/pen/QraOPX

**Comment by Johann-S** [comment]
@multigcs you have two differents ways to fix your issue instead of editing a lib (which is a very bad practice) :

- Remove `fade` class on your modals (by doing that you'll remove modal's animation)
- Listening Modal's events, Modal use transition so you have to wait to the end of this transition, so you can do that : 
```js
$('#myModal1').on('hidden.bs.modal', function () {
  $('#myModal2').modal('show')
})
```

Next button HTML
```html
<button onClick="$('#myModal1').modal('hide')" type="button" class="btn btn-danger">Next</button>
```

And everything will work correctly 😉
