### ISSUE TITLE
form-control-sm select box cuts off the bottom side of the text

### ISSUE THREAD

**Issue by IonicaBizau** [twbs/bootstrap#26459]
The letters having *bottom side* (e.g. `g`) are cut off on the bottom side in `form-control-sm`.

https://jsfiddle.net/78c569bf/1/

```html
<select class="form-control form-control-sm custom-select">
  <option value="">The g is cut off</option>
</select>
```

![screen shot 2018-05-07 at 09 38 16](https://user-images.githubusercontent.com/2864371/39688235-6afe3a3c-51da-11e8-9a43-c32ba6223b1f.png)

**Comment by IonicaBizau** [comment]
Related: #24070, #23769, but both are closed

**Comment by ysds** [comment]
`.form-control{-xxxx}` and `.custom-select` can not be used at the same elements.

[Form control size options](http://getbootstrap.com/docs/4.1/components/forms/#sizing):

```html
<select class="form-control form-control-lg">
  <option>Large select</option>
</select>
```

[Custom select size options](http://getbootstrap.com/docs/4.1/components/forms/#select-menu):

```html
<select class="custom-select custom-select-lg">
  <option>Large select</option>
</select>
```

**Comment by IonicaBizau** [comment]
@ysds Indeed, good point! But `custom-select-sm` doesn't seem to resize the whole box. Perhaps I need to do both?

```html
  <select class="form-control form-control-sm custom-select-sm custom-select">
    <option value="">This g seems to be okay, and select box is smaller, like expected</option>
  </select>
```

Updated jsfiddle: https://jsfiddle.net/78c569bf/2/

**Comment by alecpl** [comment]
`custom-select-sm` changes the font size which makes no sense to me. It should align padding as `form-control-sm` does for inputs. Something is wrong/inconsistent here indeed.

Note that I see no issue in Firefox as it renders the font differently. So, use Chrome for testing.

**Comment by mdo** [comment]
Your HTML is incorrect. Review our docs again—you don't add `.custom-select` to inputs with `.form-control` classes. Custom selects are simply `class="custom-select"`.

---

@alecpl The behaviors are functioning as they should. Both `.form-control-sm` and `.custom-select-sm` will change `font-size`, `padding`, and more.

**Comment by alecpl** [comment]
@mdo, `<select class="form-control form-control-sm">` and `<select class="custom-select custom-select-sm">` end up with different font size. Is it a bug?

**Comment by IonicaBizau** [comment]
@mdo Umm, well of course I wouldn't add `.custom-select` to inputs. That was just to check different cases.

But, like @alecpl mentioned, I'm confused about the `custom-select-sm` behavior. I would expect that `custom-select-sm` would make the select box smaller (along with the font-size), like `form-control-sm` does it.

**Comment by alecpl** [comment]
@IonicaBizau The point is to not mix form-control and custom-select on a select element.

Anyway, the two examples in @ysds comment produce different font-size. Which is a bug, imo. I'll create a separate ticket.
