### ISSUE TITLE
Different heights for inputs

### ISSUE THREAD

**Issue by LonerD** [twbs/bootstrap#26458]
Input fields look very similar, but have slightly different heights.
"custom-file-input" and "form-control"
Is this normal behavior or bug?
Impossible use two forms one next one because eyes see difference...

![2018-05-05_190418](https://user-images.githubusercontent.com/8951928/39665145-35e628de-5098-11e8-8e53-e38d1c3a42bd.png)
![2018-05-05_190601](https://user-images.githubusercontent.com/8951928/39665147-360455ac-5098-11e8-99d2-1d2d4cace79a.png)

**Comment by LonerD** [comment]
https://jsbin.com/yuquyiyaxu/
Bootstrap 4.1.0
Google Chrome 66.0.3359.139
Browser Zoom - 90% (or another zoom, more noticeably with <100%)
Windows 10 Home SL

**Comment by mdo** [comment]
I cannot reproduce this—both are `38px` computed height for me.
