### ISSUE TITLE
Sticky footer with long text presents problem

### ISSUE THREAD

**Issue by matmiranda** [twbs/bootstrap#26450]
This problem occurs when the text is too long

Follow link: https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/

Follow image: https://s17.postimg.cc/ey9ligry7/chrome_2018-05-03_16-31-28_LI.jpg

# **Update:**

**Browser:** Google Chrome: Version 66.0.3359.139 (Official Build) (64-bit)

**Bootstrap:** https://getbootstrap.com/docs/4.1/getting-started/introduction/ (Version 4.1)

**S.O:**

- Edition: Windows 10 Pro

- Version: 1709

- SO Compilation: 16299.402

JSFiddle: https://jsfiddle.net/nhac1zxw/

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by morrissey-ingenious** [comment]
@matmiranda there is a fixed height on the custom `.footer` css in that example along with a margin-bottom of the same height on the `body`.  This isn't a problem with bootstrap you will need to adjust the custom css to suit you needs by hiding the overflow or increasing the height based on your content.

**Comment by matmiranda** [comment]
@morrissey-ingenious You're right, I did not see a custom CSS.

**Comment by Johann-S** [comment]
Closing since it was in the example code 👍
