### ISSUE TITLE
CJK letters on first column in table gets collapsed by letter

### ISSUE THREAD

**Issue by TakahiRoyte** [twbs/bootstrap#26457]
check the result below to see the problem.

https://codepen.io/takahiroyte/pen/deVGRE

I want my table to be shown like one on the right with「項目１」lined up horizontally, but bootstrap's default appearance is one on the left.  As a work around, I placed 2byte space 「　」in the header to adjust the length,  and it works on Chrome and Firefox but not in IE or Edge.

Is there any utility to be added? or should I customize my CSS and set fixed pixels to use?

thanks for the great CSS framework.

**Comment by MartijnCuppens** [comment]
Add the `text-nowrap` class
https://getbootstrap.com/docs/4.0/utilities/text/#text-wrapping-and-overflow

https://codepen.io/MartijnCuppens/pen/VxMzmN

**Comment by TakahiRoyte** [comment]
thank you for your rapid help.
helped me alot!
