### ISSUE TITLE
Import Bootstrap in Angular 6 with ng add

### ISSUE THREAD

**Issue by bastienmoulia** [twbs/bootstrap#26456]
With the last version of Angular (6.0.0) there is a CLI to automatically add dependencies to an angular project. This makes it possible to import the NPM library and to modify the files of the project to use this library.
https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4#cff5

It could be great to have a shematic to just have to launch `ng add bootstrap` and the last version of bootstrap is added in the package.json, installed and the main style file import the bootstrap css or scss.

**Comment by Johann-S** [comment]
@mdo it's to allow Angular user to install the last release of Bootstrap easely

I'm not against it, but I'll have to dig it a bit before adding that

**Comment by oleksiipotiekhin** [comment]
There should be a @bootstrap/schematics for angular! To use `ng add bootstrap` or `ng add @bootstrap/schematics` to combine bootstrap and angular. It will improve integration experience by 200%.

**Comment by mdo** [comment]
Thinking this is stale and not someone on our radar for v4 or v5 @Johann-S?

**Comment by Johann-S** [comment]
yep currently out of time to do that and maintain that too, but @pkozlowski-opensource seems a better option to do that 👍
