### ISSUE TITLE
Idea: Add a border to custom-controls

### ISSUE THREAD

**Issue by MoritzBru** [twbs/bootstrap#26466]
I think it would be cool if there were variables that let us control the border of custom-controls.
With borders something like in the picture below would be possible in bootstrap natively.

![custom-controls_with_border](https://user-images.githubusercontent.com/23639869/39769736-4fcc60c2-52ed-11e8-8f4a-00592109c9f1.png)

**Comment by mdo** [comment]
Since we don't set a border by default, we wouldn't add an empty variable by default. For now we'll punt on any changes to this.
