### ISSUE TITLE
Tool-tip position wrong when anchor breaks to two lines

### ISSUE THREAD

**Issue by Nyx23** [twbs/bootstrap#26463]
I am sorry if I am missing information this is my first time posting an issue here.
I am using bootstrap 3.3.7 

If a link due its positioning breaks into two lines its tool-tip is not placed correctly; it points to the wrong place.

![image](https://user-images.githubusercontent.com/39056719/39706475-f968f994-51e7-11e8-88ef-4c9a71860868.png)

The html

    <div class="container">
      <div class="row">
        <div class="col-xs-7">
        .col-md-8
        </div>
        <div class="col-xs-5">
          Text to Test the Positioning Issue
                                        <a href="https://stackexchange.com/" target="_blank" data-toggle="tooltip" title="Test Tooltip">Link to Test Positioning Issue</a>
                                        
        </div>
      </div>
    </div>

The javascript configuration:

    $('[data-toggle="tooltip"]').tooltip({
      trigger: 'hover'
    });

[Here a fiddle](https://jsfiddle.net/Dzyann/rzL3qLs6/) that reproduces the issue.

**Comment by InsanityMeetsHH** [comment]
In my opinion the position is correct calculated but it looks broken.
Where do you expected the tooltip be?

**Comment by Nyx23** [comment]
So I think the issue has to do with how the browser is returning the coordinates, but I think at the very least the tool-tip should point to the link and not just the middle of the container as it seems to be doing.
We detected this issue because a user got confused when we had two links one close to the other and the tool-tip was apparently pointing to the other link. Like in this image:

![image](https://user-images.githubusercontent.com/39056719/39771142-81d5744e-52c7-11e8-9b33-243042aa36d1.png)

**Comment by thatnini** [comment]
Have you tried adding in `white-space: nowrap;` as mentioned in the multiple-line links callout in the [docs](https://getbootstrap.com/docs/3.3/javascript/#markup-1)?

**Comment by Nyx23** [comment]
Hi @thatnini  I don't recall if I tried that before but it forces the link to show in one line, rather than two. Like this: 
![image](https://user-images.githubusercontent.com/39056719/39773724-3ec3a880-52cf-11e8-9efa-15965454b34e.png)
Which wouldn't be desired in my case.
However reading carefully the documentation it seems the tooltip is working as intended:

![image](https://user-images.githubusercontent.com/39056719/39773983-f402179a-52cf-11e8-954e-5a0842a06235.png)

Even if it is slightly confusing in cases where you have 2 links, like this:
![image](https://user-images.githubusercontent.com/39056719/39771142-81d5744e-52c7-11e8-9b33-243042aa36d1.png)

So maybe I should close this?

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
