### ISSUE TITLE
custom-select not displayed properly on firefox

### ISSUE THREAD

**Issue by jeckyhl** [twbs/bootstrap#26472]
Bootstrap v4.1 on firefox 55.0.3

custom-select is not displayed properly on firefox because the « appearance » CSS property is not supported by Firefox

![custom-select](https://user-images.githubusercontent.com/1909153/39815493-6bee5340-5398-11e8-9f9c-52cd6bb261ae.png)

My solution is to change `.custom-select` rule in _custom-forms.scss
Replace
````
appearance: none;
````
with
````
-moz-appearance: none;
appearance: none;
````

**Comment by thatnini** [comment]
Vendor prefixes aren't included by default in the scss files, so you need to include something like [Autoprefixer](https://getbootstrap.com/docs/4.1/getting-started/build-tools/#autoprefixer) in your own build tools.

**Comment by jeckyhl** [comment]
I take good note of this! Thx

**Comment by patrickhlauke** [comment]
https://getbootstrap.com/docs/4.1/getting-started/download/#source-files
