### ISSUE TITLE
Multiple clicks on custom radio/checkboxes leads to label text selection

### ISSUE THREAD

**Issue by UXMichael** [twbs/bootstrap#26473]
To reproduce use the link https://getbootstrap.com/docs/4.1/components/forms/#checkboxes-and-radios-1

Click multiple on the check or radio buttons.

Tested Browsers are IE11 and Chrome 

![image](https://user-images.githubusercontent.com/3916022/39822720-8d90ab02-53ab-11e8-9fe5-512d06a283d0.png)

![image](https://user-images.githubusercontent.com/3916022/39822741-9f549b3c-53ab-11e8-9e90-493956f3032b.png)

**Comment by patrickhlauke** [comment]
that's standard browser behavior for text like in labels. happens without bootstrap as well.

**Comment by UXMichael** [comment]
Sorry. No. The Bug is in the custom checkboxes and radios. U can try it against the standard ones.
The standard ones works
![image](https://user-images.githubusercontent.com/3916022/39859019-b0a76a08-5438-11e8-8b6b-d57383ebcd5f.png)

**Comment by patrickhlauke** [comment]
and those still use a standard `<label>`, and what you're seeing is default behavior in browsers for `<label>`. double-clicking anywhere on text (which label is) on a webpage will have the browser selecting the word you clicked.

**Comment by UXMichael** [comment]
Please check it by yourself. I saw the problem . If you inspect in the developer console you wil see the input fields of custom elements are rendered in the label. The default ones doesnt. Thats the reason.

**Comment by ysds** [comment]
I think @UXMichael says a behavior when double-clicking on an indicator not text.

**Comment by UXMichael** [comment]
@ysds is right. It isnt the expected behaviour if i click on the checkbox and the text of the label is random marked. It only happens on custom check/radio buttons. Not on the standard ones.

**Comment by patrickhlauke** [comment]
ok, that wasn't quite clear from the issue description

**Comment by UXMichael** [comment]
@alecpl is right. Firefox seems to be ok. But Edge have the same Problem

**Comment by MartijnCuppens** [comment]
We could add `user-select: none;` to the labels, but this would make all the text unselectable. I guess we can just leave it like it is now, this is default browser behaviour.
