### ISSUE TITLE
.form-control-sm and .custom-select-sm give different font size/padding

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#26476]
I expect these two to give the same font-size and left-padding:
```
<select class="form-control form-control-sm">
  <option>Small select</option>
</select>
<select class="custom-select custom-select-sm">
  <option>Small select</option>
</select>
```
https://jsfiddle.net/6oj656wb/

**Comment by alecpl** [comment]
And in *-lg variant left padding is different https://jsfiddle.net/6oj656wb/1/

**Comment by alecpl** [comment]
And BTW, left padding is inconsistent with inputs https://jsfiddle.net/6oj656wb/2/

**Comment by mdo** [comment]
Nearly everything between our custom components is different, why would there be an expectation to keep these the same values? I'm inclined to leave them as-is.

**Comment by alecpl** [comment]
Because if I use input.form-control-sm together with select.custom-select-sm in my forms they do not look consistent. And I want to use custom selects instead of just form-controls because it looks just nicer.

**Comment by Johann-S** [comment]
Just a quick note maybe @alecpl you should upgrade to our latest release `4.1.1`: https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css

**Comment by RobertSmits** [comment]
I can confirm this issue. 
The padding of the `custom-select` and `-sm` and `-lg` variants is different from the `form-control` and variants padding.

So is the font size: `form-control-sm` has `font-size: .875rem` and `custom-select-sm` has `font-size: 75%`

And in a form this font size difference is very noticeable.

![image](https://user-images.githubusercontent.com/6593428/40446851-e67132de-5ed0-11e8-889a-ac5bb9a5ce97.png)

**Comment by MedShake** [comment]
Fix it temporary with :  

```
<select class="custom-select form-control form-control-sm">
  <option>Small select</option>
</select>
```
