### ISSUE TITLE
form-control-sm border style error 

### ISSUE THREAD

**Issue by LuisReinoso** [twbs/bootstrap#26487]
**Version:** 4.0.0-beta.2

When I try this:
```HTML
<div class="col-5 form-inline">
   <input type="text" class="form-control">
</div>
```
[![Correcto.png](https://s7.postimg.cc/4fqbapszv/Correcto.png)](https://postimg.cc/image/4fqbapszr/)

The error is when I try:
```HTML
<div class="col-5 form-inline">
   <input type="text" class="form-control-sm">
</div>
```
[![Incorrecto.png](https://s7.postimg.cc/tlr9hlcaj/Incorrecto.png)](https://postimg.cc/image/4fqbarb07/)

It's a border style error?

**Comment by chicheng** [comment]
You need to use both css classes

    class="form-control form-control-sm"

**Comment by mdo** [comment]
Yup, requires both.

**Comment by LuisReinoso** [comment]
Thanks..

**Comment by kevdotbadger** [comment]
Also, any reason you're using the beta version?
