### ISSUE TITLE
Body font-size and system fonts. Starting from a post.

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26480]
How about this post: http://markdotto.com/2018/02/07/github-system-fonts/ ?

Why in Bootstrap 4, for example, we still have `font-size: 1rem` (16px)?

Just one thought after reading...

**Comment by mdo** [comment]
This is addressed in http://getbootstrap.com/docs/4.1/content/typography/.

**Comment by johnunclesam** [comment]
Yes, @mdo, I was wondering why in post you said `14px` for `body font-size` and in Bootstrap 4 we still have `16px`?

**Comment by kevdotbadger** [comment]
"For a more inclusive and accessible type scale, we assume the browser default root font-size (typically 16px) so visitors can customize their browser defaults as needed."

**Comment by johnunclesam** [comment]
@kevdotbadger I don't understand this phrase. Can you explain it to me?
