### ISSUE TITLE
Still showing bootstrap 4.1.0 on landing page

### ISSUE THREAD

**Issue by mohammadayoub96** [twbs/bootstrap#26482]
still showing bootstrap 4.1.0 on landing page

![screenshot 84](https://user-images.githubusercontent.com/20210961/39891960-7f764fe6-54b8-11e8-9d96-c062ba4add7a.png)

update this in documentation

**Comment by mdo** [comment]
Definitely weird caching stuff happening that has me stumped. Closing as dupe though.

**Comment by mohammadayoub96** [comment]
Thanks Now its fine
