### ISSUE TITLE
Modal, navbar fixed-top, margin-right 16px and overflow scrollbar.

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26489]
Bootstrap **v4.1.1**.

When I use header `navbar fixed-top` and I open a modal and it adds `margin-right: 16px` to the body element the `navbar fixed-top` doesn't move to the left like all the page.

If I use `sticky-top` (at least in Chrome) it works.

Is it really useful to add that `margin-right: 16px` ?

Can we agree on leave there the scrollbar? Why we need to hide it?

Also in some retina display I can really see some pixel movement when I open modal, as if we were to use `17px`.

**Comment by Johann-S** [comment]
seems related to: https://github.com/twbs/bootstrap/pull/25745

@zalog am I right ?

**Comment by zalog** [comment]
Yep, it is.

**Comment by Johann-S** [comment]
Closed because it's related to @zalog, I hope you'll have time to update your unit test 😉

**Comment by zalog** [comment]
Yeah, we must do that :(
