### ISSUE TITLE
Add toggle switch

### ISSUE THREAD

**Issue by mohammadayoub96** [twbs/bootstrap#26497]
Please Add toggle switch in bootstrap 
as

![music](https://user-images.githubusercontent.com/20210961/39950865-27ae04f2-559e-11e8-8e40-ebb88dced644.jpg)

**Comment by kevdotbadger** [comment]
What's the point? You know this will get closed.

**Comment by mohammadayoub96** [comment]
Toggle Switches are not in boostral i just say add them in bootstrap

**Comment by alecpl** [comment]
See https://github.com/twbs/bootstrap/pull/23004
