### ISSUE TITLE
3 vulnerabilities found

### ISSUE THREAD

**Issue by Limoli** [twbs/bootstrap#26494]
I have simply created a new react app:
```
npm install -g create-react-app
create-react-app my-app
cd my-app/
```
When I try to install bootstrap version 4.1.1
```
npm install --save bootstrap@4.1.1
+ bootstrap@4.1.1
added 197 packages from 158 contributors, removed 181 packages and updated 1076 packages in 44.565s
[!] 3 vulnerabilities found [14375 packages audited]
    Severity: 3 Low
    Run `npm audit` for more detail
```
<img width="596" alt="screen shot 2018-05-11 at 21 09 29" src="https://user-images.githubusercontent.com/5011711/39943389-f6a4ed16-5562-11e8-952d-a758eabacd8d.png">

**Comment by thatnini** [comment]
This isn't a Bootstrap issue, as installing Bootstrap doesn't install react-scripts - if it did, then the security report would say `Dependency of Bootstrap`. (You could also try creating a new app with just Bootstrap to verify)

You need to report this at [https://github.com/facebook/create-react-app](https://github.com/facebook/create-react-app) as you've already been [advised](https://github.com/reactstrap/reactstrap/issues/1015#issuecomment-388472422)

And no, I don't have a clue why npm audit didn't say anything when you installed create-react-app but waited until you installed bootstrap, but it is a new feature from npm.

**Comment by Johann-S** [comment]
Your vulnerabilities doesn't come from Bootstrap, please refer to the corresponding packages
