### ISSUE TITLE
Is there a thought about an XL modal?

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26490]
Is there a thought about an XL modal?

**Comment by johnunclesam** [comment]
https://github.com/twbs/bootstrap/pull/19925

**Comment by Johann-S** [comment]
so you found your answer 😉

**Comment by johnunclesam** [comment]
@Johann-S are you gonna to merge it?

**Comment by Johann-S** [comment]
Will see, you can follow this PR to know if we merge this one or not
