### ISSUE TITLE
Still showing v4.1.0 on getbootstrap.com

### ISSUE THREAD

**Issue by mohammadayoub96** [twbs/bootstrap#26498]
Still showing v4.1.0 on getbootstrap.com
also downloads v4.1.0, no way to download 4.1.1 

![screenshot 91](https://user-images.githubusercontent.com/20210961/39953875-394263d6-55ce-11e8-88c6-541b7f198893.png)

**Comment by isurendrasingh** [comment]
It's showing 4.1.1 
![screenshot 29](https://user-images.githubusercontent.com/7621607/39954736-a705be28-55e1-11e8-9b91-4f8bdd1f020a.png)

**Comment by mohammadayoub96** [comment]
Bot showing bro

**Comment by isurendrasingh** [comment]
Use Ctrl+F5 and then check.

**Comment by mohammadayoub96** [comment]
Yeah not with CTRL+F5 but resolved the problem anyways, Thanks to you
