### ISSUE TITLE
Mgiration Docs Not Updated

### ISSUE THREAD

**Issue by mohammadayoub96** [twbs/bootstrap#26499]
Since stable release this section is not update, I think should updated release by release, So any one can better migrate from previous version. Thank You
 
![screenshot 93](https://user-images.githubusercontent.com/20210961/39955191-3eedb48c-55e4-11e8-8d7d-b9339bf46f30.png)

It should be update as:
![screenshot 93 - copy](https://user-images.githubusercontent.com/20210961/39955238-cab72ac0-55e4-11e8-8684-2d2a07392a38.png)

**Comment by mdo** [comment]
Migration page hasn’t only ever been for major releases.

**Comment by mohammadayoub96** [comment]
So where to find migration docs for smaller releases

**Comment by bardiharborow** [comment]
@mohammadayoub96 there generally shouldn't be breaking changes. If there are, they will be underscored in the blog post.
