### ISSUE TITLE
Is there a thought about list-group-small? /idea

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26495]
Is there a thought about `list-group-small`?

/idea

**Comment by sts-ryan-holton** [comment]
@johnunclesam  We might need more details about what your `.list-group-small` class is meant to do? Is that to make the width of the list group smaller? or is this about reducing padding  on the `.list-group-item` items? You could simply make use of Bootstrap padding helper classes? https://getbootstrap.com/docs/4.1/layout/utilities-for-layout/#margin-and-padding

**Comment by johnunclesam** [comment]
@sts-ryan-holton both. I believe this is one of those cases where you need a new element and not a series of classes in html to get to the goal. No?

**Comment by mdo** [comment]
Punting on this for now, thanks for the suggestion though!
