### ISSUE TITLE
Add cross browser animations classes

### ISSUE THREAD

**Issue by al1khavari** [twbs/bootstrap#26502]
Hi , I want to suggest a feature to you , add some coll transitions and animations like fadein, fadeout, bounce, rotate and ......

**Comment by bardiharborow** [comment]
Is there something you are unable to achieve using standard CSS? We have some utility classes, but we try to keep them at a minimum and this may be beyond our scope.

**Comment by mdo** [comment]
There are libraries that provide generic helpers for that already, no plans for us to add our own. We'd map them to components if anything.
