### ISSUE TITLE
Bootstrap 4 emails feature proposal

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26505]
### Awesome new emails feature proposal!

I've been using Bootstrap 4 for quite some time, **I'm a huge fan of what Bootstrap has to offer**, especially with quick and efficient utility classes for margin, padding and alignment.

However, there is one **big feature** that I think Bootstrap needs and it's one of the reasons I turn to the _(in my opinion)_ less popular framework... Zurb Foundation.

I'm talking about Emails. Unlike Bootstrap, Zurb Foundation has the ability to create email-friendly markup using their CSS inliner and email templates, see this link => https://foundation.zurb.com/emails.html

**I think this would certainly make a great feature to Bootstrap** and possibly attract another type of audience to Bootstrap.

It could take a while to potentially develop, but it could be worth releasing it in a beta stage similarly to how Bootstrap 4 was released in an Alpha stage. I've mocked up how we could potentially add this section to the Bootstrap site by including a 'Emails' link, making use of your badges to highlight that it's a beta feature, this would be great because it releases a new feature quicker so people can start using it and providing feedback!

#### Current Navbar
![bootstrap-nav](https://user-images.githubusercontent.com/25177538/39961258-64a07f20-562a-11e8-8a54-f43f607455e0.PNG)

#### Proposal mockup with Emails
![bootstrap-nav-mockup](https://user-images.githubusercontent.com/25177538/39961257-6487e32a-562a-11e8-9dc1-a969da79ff50.PNG)

What do you guys think of this? I think emails are just as important these days for marketing and interacting with customers and generating leads! By implementing this you're essentially showing the Bootstrap brand to even more people because they could see your logo in emails that people generate.

**Personally, I think this feature would be great to see! <3**

**Comment by bardiharborow** [comment]
I'm afraid this is beyond our project's scope. The resource constraints we have as a volunteer project mean that we maintain an comparatively [aggressive browser deprecation schedule](https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/) compared to Foundation, and supporting the poor standards compliance of email clients would be step in the opposite direction. We do however appreciate the considered feature request. If you'd like to build such a thing yourself, you may have better luck starting from v3.3.7, the last release before most of the pre-IE10 compatibility code was ripped out.
