### ISSUE TITLE
Floating labels cursor

### ISSUE THREAD

**Issue by ratajs** [twbs/bootstrap#26503]
Hello, I've been browsing the Floating Labels examle and I discovered that if it's in the css for `.form-label-group > label` rule `cursor: text`, it works. In my opinion it's more pretty.

**Comment by surjithctly** [comment]
@andresgalante I guess he is specifically asking about the floating label section where label is inside the textbox at first. So showing text cursor is good or accessibility or users will think this field is not typable. 

So, I agree with @ratajs 

~Surjith

**Comment by andresgalante** [comment]
Right, I see what you mean, on an initial state I agree that the cursor should be text. Once the label go smaller it should be default since that area is not editable.
