### ISSUE TITLE
.btn-outline-light can't really be seen on Bootstrap docs

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26506]
Hi!

I've just noticed whilst browsing the Bootstrap 4.1.1 docs that you can't really see the text of the `.btn-outline-light` button.

Could we consider some other text colour here? I don't think it's really legible and people who could be somewhat visually impaired might find it difficult to read?

**Take a look:**

![outline-btn](https://user-images.githubusercontent.com/25177538/39969050-66fed33a-56ce-11e8-908f-8e89e6d5dd90.PNG)

(https://getbootstrap.com/docs/4.1/components/buttons/)

**Comment by sts-ryan-holton** [comment]
@bardiharborow Completely understand, couldn't we just make the text a little darker for the docs for that particular button?

**Comment by bardiharborow** [comment]
I imagine that would confuse people more than it would help unfortunately.

**Comment by patrickhlauke** [comment]
> couldn't we just make the text a little darker for the docs for that particular button?

no because then (if just done for the docs) it wouldn't reflect the actual color you'd get when using the class
