### ISSUE TITLE
Error on download for github:twbs/bootstrap TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by timbjames** [twbs/bootstrap#26518]
We are suddenly seeing this error within our build server;

```
warn Error on download for github:twbs/bootstrap
     TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
         at makeCallback (fs.js:132:11)
         at Object.fs.mkdir (fs.js:822:14)
         at D:\a\1\s\Installations\Project\node_modules\jspm-github\github.js:588:29
         at tryCatch (D:\a\1\s\Installations\Project\node_modules\rsvp\dist\rsvp.js:525:12)
         at invokeCallback (D:\a\1\s\Installations\Project\node_modules\rsvp\dist\rsvp.js:538:13)
         at publish (D:\a\1\s\Installations\Project\node_modules\rsvp\dist\rsvp.js:508:7)
         at flush (D:\a\1\s\Installations\Project\node_modules\rsvp\dist\rsvp.js:2415:5)
         at process._tickCallback (internal/process/next_tick.js:172:11)
err  Error downloading github:twbs/bootstrap.
```
We are using `github:twbs/bootstrap@3.3.6` and nothing has changed within the project. Is this something related to this repository? Or npm related?

**Comment by Johann-S** [comment]
Seems inside `jspm-github` not our packages sorry !

**Comment by jgacuca567** [comment]
@timbjames why are you using `3.3.6` instead of `4.1.1`

**Comment by timbjames** [comment]
@jgacuca567 we are currently tied into bootstrap 3 which is being used by a 3rd party component.

@Johann-S Thanks for the reply. It looks to be down to versioning of node/npm and jpsm. So like you said, not your package which is good. Thanks,

**Comment by rbengtsson** [comment]
@timbjames I'm getting the same problem, using "bootstrap": "github:twbs/bootstrap@^3.3.7" in my package.json and our automatic build is getting errors since a week or two back. It is working fine locally however. What did you do to fix it?

**Comment by timbjames** [comment]
@rbengtsson for now we had to use a different build machine which is running version 8.11.2 of node rather than the latest version 10.1.0 and that has fixed the issue.

**Comment by rbengtsson** [comment]
@timbjames Thanks for your answers. We're building in VSTS, will look into our options there. 👍
