### ISSUE TITLE
Collapse doesn't work if id contains dot

### ISSUE THREAD

**Issue by lystor** [twbs/bootstrap#26516]
Hello

Collapse doesn't work if id contains dot.

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <title>Hello, world!</title>
</head>
<body>

<div class="accordion" id="accordion">
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse.One">
                    Collapsible Group Item #1
                </button>
            </h5>
        </div>

        <div id="collapse.One" class="collapse show" data-parent="#accordion">
            <div class="card-body">
                xxx
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse.Two">
                    Collapsible Group Item #2
                </button>
            </h5>
        </div>
        <div id="collapse.Two" class="collapse" data-parent="#accordion">
            <div class="card-body">
                yyy
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</body>
</html>
```

Please fix the bug.
Thank you.

--
Mykola

**Comment by sts-ryan-holton** [comment]
@lystor  I've been working with CSS for some time now, I haven't ever came across a point where I'd use a `.` in my naming conventions for IDs. I'd recommend simply changing from a `.` to a `-`, this should work after then. Is there a specific reason why we're using a dot in your ID?

**Comment by lystor** [comment]
@sts-ryan-holton

> Is there a specific reason why we're using a dot in your ID?

Yes.
I use product versions as id. Url contains them too. Required target is opened automatically on page load.

Example:
http://example.com/products/xxx#5.11.3 will open tab with id=5.11.3

JQuery supports meta-characters in id:
https://api.jquery.com/category/selectors/ 

> To use any of the meta-characters ( such as  !"#$%&'()*+,./:;<=>?@[\]^`{|}~ ) as a literal part of a name, it must be escaped with with two backslashes: \\. For example, an element with id="foo.bar", can use the selector $("#foo\\.bar"). The W3C CSS specification contains the complete set of rules regarding valid CSS selectors. Also useful is the blog entry by Mathias Bynens on CSS character escape sequences for identifiers.

I have been using JQuery UI many years and it works with dots in id out of the box.

Now I can't migrate to Bootstrap from JQuery UI due to this issue :(

**Comment by Johann-S** [comment]
You have to escape your selector that's what jQuery said by : 
> can use the selector $("#foo\.bar")

and it'll be fine 😉 

Everything passed in our `data-target` attribute is passed to jQuery as a selector

**Comment by lystor** [comment]
Hi, @ Johann-S

It works, thank you.

May be it is better to improve Bootstrap to escape meta-characters in data-target automatically?
So collapse will work without any workarounds out of the box like in jQuery UI.

Thank you

**Comment by Johann-S** [comment]
We made that in a previous PR but finally we reverted that because it's too hard to detect correctly special selectors.

See: 
- #25390
- #25273


We added a quick note in our documentation see: https://getbootstrap.com/docs/4.1/getting-started/javascript/#escaping-selectors
