### ISSUE TITLE
Full-height Jumbotron?

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26514]
I was wondering whether it would be possible to include a section in the jumbotron component of the Bootstrap 4.1 docs for essentially creating full-height jumbotrons.

I'm finding more and more designs these days using full-height banners on their website, and I guess this is usually done using `height: 100vh` with some kind of possible fallback.

Firstly, we don't seem to have that as a utility class in Bootstrap, we have `height: 100%` but not `100vh`.

Is it possible to create a full-height jumbotron example in the docs and possibly this additional utility class?

https://getbootstrap.com/docs/4.1/components/jumbotron/

**Comment by andresgalante** [comment]
Hi @sts-ryan-holton this has been discussed here #24374

**Comment by sts-ryan-holton** [comment]
@andresgalante  Will this be added? Looks like that discussion been completed yet?

**Comment by andresgalante** [comment]
I don't see it likely, we pass on that idea back then. I'll leave it open maybe mdo reconsiders now

**Comment by sts-ryan-holton** [comment]
@mdo What's your thoughts on this?

**Comment by mdo** [comment]
Unlikely to make it's way into the project I think. One line of custom CSS largely accomplishes this as it stands now, and we don't need utilities for this across every breakpoint either I think.
