### ISSUE TITLE
Add responsive spacing example on spacing page

### ISSUE THREAD

**Issue by pcmulder** [twbs/bootstrap#26524]
I've noticed a lot of people visiting the spacing page, but remain unaware of the option to specify a breakpoint while it is in the documentation. After talking with some of them it seems that they are mostly looking at the Examples section. 

Is it an idea to add a breakpoint example to the Examples section?

**Comment by andresgalante** [comment]
Hi @pcmulder thanks for reporting this. Improvements on the docs are always welcome.

Would you like to send a PR adding more examples to `utilities/spacing/` or improvement the text to be more clear?

**Comment by mdo** [comment]
Could be interesting to do one for the framework section that's just all our spacing options?

**Comment by mdo** [comment]
Closing out as I don't want to make this myself 😁 but if someone has an idea, please send a PR! <3
