### ISSUE TITLE
h-sm-100 h-md-100 & h-lg-100 

### ISSUE THREAD

**Issue by greenscript** [twbs/bootstrap#26527]
Hello, I think some responsive variations to the <code>.h-100 </code>  class would be useful. 
Thanks!

**Comment by MartijnCuppens** [comment]
Heights in percentage do not always work the way you want to. Maybe it's better to use flexbox utility classes for this?

**Comment by greenscript** [comment]
The reasoning behind why I consider that these classes could be useful is to make sure that some elements just take the the full height on certain breakpoints, I've been using my own .h-breakpoint-100 class in some projects lately and they have become in handy, just figured someone could find them useful as well.

**Comment by MartijnCuppens** [comment]
Here is a demo to explain what I mean with _"Heights in percentage do not always work the way you want to"_:
https://codepen.io/MartijnCuppens/pen/WJLKyP
A solution is to use flexbox: 
https://codepen.io/MartijnCuppens/pen/ZoVjjE

The problem is that `.h-100` will only work if the height of the parent is not auto or if the parent element is an absolute/fixed element, and this will confuse people.

For your case, flexbox can also be enabled at some breakpoints if needed:
https://getbootstrap.com/docs/4.0/utilities/flex/#enable-flex-behaviors

**Comment by mdo** [comment]
No plans to add these.

**Comment by greenscript** [comment]
Well that really had nothing to do with what I was saying, but I appreciate the time you put into making the demonstrations, maybe I just didn't express my self as I should have, doesn't matter anymore anyways, seems I'll have to keep adding the .h-breakpoint-100 class on my own, thanks anyways tho.

**Comment by vgdbs** [comment]
> Well that really had nothing to do with what I was saying, but I appreciate the time you put into making the demonstrations, maybe I just didn't express my self as I should have, doesn't matter anymore anyways, seems I'll have to keep adding the .h-breakpoint-100 class on my own, thanks anyways tho.

Maybe you could share us your own version, it could be usefull for all of use :)

**Comment by skrosoft** [comment]
> Well that really had nothing to do with what I was saying, but I appreciate the time you put into making the demonstrations, maybe I just didn't express my self as I should have, doesn't matter anymore anyways, seems I'll have to keep adding the .h-breakpoint-100 class on my own, thanks anyways tho.

Maybe you could share us your own version, it could be usefull for all of use :)

**Comment by MartijnCuppens** [comment]
You will have the ability to use the utility API in the next version of Bootstrap (`v5`).
https://twbs-bootstrap.netlify.com/docs/4.3/utilities/api/

Adding these line will enable responsive height utility classes:

```
$utilities: (
  "height": (
    property: height,
    responsive: true,
    class: h,
    values: (
      25: 25%,
      50: 50%,
      75: 75%,
      100: 100%,
      auto: auto
    )
  ),
);
```
