### ISSUE TITLE
Feature request: Variable sizing utilities based on user's viewport

### ISSUE THREAD

**Issue by alsoknownasdrew** [twbs/bootstrap#26528]
I didn't find a way to set different sizes on one element with [sizing utilities classes](https://getbootstrap.com/docs/4.0/utilities/sizing/). It would be nice to be able to use classes like

```html
<div class="w-25 w-md-50 w-lg-100"></div>
```

And resize the element according to the breakpoint.

I would be happy to work on it if it gets approved.

**Comment by Mitcheljager** [comment]
This isn't a solution, but if you are using scss you can use the following in the meantime:

```
@each $breakpoint, $breakpoint-value in $container-max-widths {
  @include media-breakpoint-down($breakpoint) {
    @each $size, $value in $sizes {
      .w-#{$breakpoint}-#{$size} {
        width: $value !important;
      }
    }
  }
}
```

This will create the following:

```
@media (max-width: 575px) {
  .w-xs-25 {
    width: 25% !important;
  }

  .w-xs-50 {
    width: 50% !important;
  }

  .w-xs-75 {
    width: 75% !important;
  }

  .w-xs-100 {
    width: 100% !important;
  }
}
@media (max-width: 767px) {
  .w-sm-25 {
    width: 25% !important;
  }

  .w-sm-50 {
    width: 50% !important;
  }

  .w-sm-75 {
    width: 75% !important;
  }

  .w-sm-100 {
    width: 100% !important;
  }
}
@media (max-width: 991px) {
  .w-md-25 {
    width: 25% !important;
  }

  .w-md-50 {
    width: 50% !important;
  }

  .w-md-75 {
    width: 75% !important;
  }

  .w-md-100 {
    width: 100% !important;
  }
}
@media (max-width: 1199px) {
  .w-lg-25 {
    width: 25% !important;
  }

  .w-lg-50 {
    width: 50% !important;
  }

  .w-lg-75 {
    width: 75% !important;
  }

  .w-lg-100 {
    width: 100% !important;
  }
}
```

**Comment by mdo** [comment]
No plans to add this at this time.

**Comment by leecollings** [comment]
> No plans to add this at this time.

Why not?

**Comment by leecollings** [comment]
> This isn't a solution, but if you are using scss you can use the following in the meantime:
> 
> ```
> @each $breakpoint, $breakpoint-value in $container-max-widths {
>   @include media-breakpoint-down($breakpoint) {
>     @each $size, $value in $sizes {
>       .w-#{$breakpoint}-#{$size} {
>         width: $value !important;
>       }
>     }
>   }
> }
> ```
> 
> This will create the following:
> 
> ```
> @media (max-width: 575px) {
>   .w-xs-25 {
>     width: 25% !important;
>   }
> 
>   .w-xs-50 {
>     width: 50% !important;
>   }
> 
>   .w-xs-75 {
>     width: 75% !important;
>   }
> 
>   .w-xs-100 {
>     width: 100% !important;
>   }
> }
> @media (max-width: 767px) {
>   .w-sm-25 {
>     width: 25% !important;
>   }
> 
>   .w-sm-50 {
>     width: 50% !important;
>   }
> 
>   .w-sm-75 {
>     width: 75% !important;
>   }
> 
>   .w-sm-100 {
>     width: 100% !important;
>   }
> }
> @media (max-width: 991px) {
>   .w-md-25 {
>     width: 25% !important;
>   }
> 
>   .w-md-50 {
>     width: 50% !important;
>   }
> 
>   .w-md-75 {
>     width: 75% !important;
>   }
> 
>   .w-md-100 {
>     width: 100% !important;
>   }
> }
> @media (max-width: 1199px) {
>   .w-lg-25 {
>     width: 25% !important;
>   }
> 
>   .w-lg-50 {
>     width: 50% !important;
>   }
> 
>   .w-lg-75 {
>     width: 75% !important;
>   }
> 
>   .w-lg-100 {
>     width: 100% !important;
>   }
> }
> ```

There's a problem with these. Usually, if I use anything current in the form *-md-*, this will apply for all sizes MD and above, meaning a min-width media query would be used.

It seems your outputted CSS is doing the other way around, and only applying up to this size.

Are you sure that's correct?

**Comment by Hassan-Moin** [comment]
@leecollings is correct, the query should be
```
@each $breakpoint, $breakpoint-value in $container-max-widths {
  @include media-breakpoint-up($breakpoint) {
    @each $size, $value in $sizes {
      .w-#{$breakpoint}-#{$size} {
        width: $value !important;  
    } 
   }
  }
}
```

Replaced ` @include media-breakpoint-down` with  ` @include media-breakpoint-up` as this complies to
`@media (min-width: 544px) {} ` etc instead of max-width.

**Comment by leecollings** [comment]
@mdo Can this be reconsidered please?

**Comment by guettli** [comment]
For me using `min-width` and `max-width` (without media queries) was enough.

Related: https://stackoverflow.com/a/66758895/633961

**Comment by Yaroslav1994** [comment]
> @leecollings is correct, the query should be
> 
> ```
> @each $breakpoint, $breakpoint-value in $container-max-widths {
>   @include media-breakpoint-up($breakpoint) {
>     @each $size, $value in $sizes {
>       .w-#{$breakpoint}-#{$size} {
>         width: $value !important;  
>     } 
>    }
>   }
> }
> ```
> 
> Replaced ` @include media-breakpoint-down` with ` @include media-breakpoint-up` as this complies to
> `@media (min-width: 544px) {} ` etc instead of max-width.

Doesnt work
Error - Undefined variable: "$sizes"

**Comment by TrioMatt** [comment]
@Yaroslav1994 
> Doesnt work
Error - Undefined variable: "$sizes"

Not sure if there should be a bootstrap scss variable for it, but I added the variable myself to get it working.
```
$sizes: ("25":25%, "50":50%, "75":75%, "100":100%);

@each $breakpoint, $breakpoint-value in $container-max-widths {
    @include media-breakpoint-up($breakpoint) {
        @each $size, $value in $sizes {
            .w-#{$breakpoint}-#{$size} {
                width: $value !important;
            }
        }
    }
}
```

**Comment by karlshea** [comment]
This works to get the built-in sizes:

```scss
@each $breakpoint, $breakpoint-value in $container-max-widths {
  @include media-breakpoint-up($breakpoint) {
    @each $size, $value in map-get(map-get($utilities, 'width'), 'values') {
      .w-#{$breakpoint}-#{$size} {
        width: $value !important;
      }
    }
  }
}
```

**Comment by ffoodd** [comment]
In v5, the recommended way is [to override utilities to make them responsive](https://getbootstrap.com/docs/5.1/utilities/api/#override-utilities).
