### ISSUE TITLE
Docs search results in 4.1 link to 4.0 docs

### ISSUE THREAD

**Issue by Spetnik** [twbs/bootstrap#26523]
If I go to https://getbootstrap.com/docs/4.1/getting-started/introduction/ and in the search box on the left, type "alerts" and then click on the first result, it takes me to https://getbootstrap.com/docs/4.0/components/alerts/ instead of https://getbootstrap.com/docs/4.1/components/alerts/

**Comment by sts-ryan-holton** [comment]
@Spetnik  Already aware of the issue, see => https://github.com/twbs/bootstrap/issues/26441

For a solution, do this:

> open Chrome Devtools, open Application tab and then Application > Clear Storage. Then tap the 'Clear site data' button to wipe service worker storage etc. That'll fix it for you.

**May as well close this issue**

:-)

**Comment by Spetnik** [comment]
Sorry for the duplicate issue - I guess I didn't search well enough!
