### ISSUE TITLE
(feature): Allow control of invalid-tooltip position

### ISSUE THREAD

**Issue by AbakumovAlexandr** [twbs/bootstrap#26522]
Form validation [tooltip](https://getbootstrap.com/docs/4.0/components/forms/#tooltips) displays to the bottom of input.

It would be nice to have the ability to show it to the right (and probably to the left and top as well), since currently it might overlay other inputs making it difficult to an user to see what's typed in other form inputs.

**Comment by AbakumovAlexandr** [comment]
@Johann-S , thank you! This is certainly an option! I just thought that having the ability to control the placement of `invalid-tooltip` might be an useful feature for your team to consider.

**Comment by mdo** [comment]
For now, no plans to add the directional control. Should be straightforward to override though—you'll only need to tackle the positioning properties with a selector like `.valid-tooltip, .invalid-toolip { ... }`.
