### ISSUE TITLE
SVG images and IE 10 fix

### ISSUE THREAD

**Issue by namiltd** [twbs/bootstrap#26534]
Fragment of: https://getbootstrap.com/docs/4.1/content/images/:
<p>In Internet Explorer 10, SVG images with <code class="highlighter-rouge">.img-fluid</code> are disproportionately sized. To fix this, add <code class="highlighter-rouge">width: 100% \9;</code> where necessary. This fix improperly sizes other image formats, so Bootstrap doesn’t apply it automatically.</p>

Why not do it automatically?
This code should be added to css to solve the already known problem of displaying SVG on IE10
```
.img-fluid[src$=".svg"] {
    // IE10 code
    width: 100% \9;
}
````
[_image.scss.patch.txt](https://github.com/twbs/bootstrap/files/2019248/_image.scss.patch.txt)

Or full case insensitive version:
```
.img-fluid[src$=".svg"],
.img-fluid[src$=".SVG"],
.img-fluid[src$=".sVg"],
.img-fluid[src$=".SvG"],
.img-fluid[src$=".svG"],
.img-fluid[src$=".SVg"],
.img-fluid[src$=".Svg"],
.img-fluid[src$=".sVG"] {
    // IE10 code
    width: 100% \9;
}
```
[_image.scss.patch-ci.txt](https://github.com/twbs/bootstrap/files/2019253/_image.scss.patch-ci.txt)

**Comment by Herst** [comment]
You can't match the MIME type.

**Comment by mdo** [comment]
Punting on this, thanks though. Haven't seen much complaining around this issue given IE10's overall state I'm assuming.
