### ISSUE TITLE
sass import variables and mixins only

### ISSUE THREAD

**Issue by marcoflorian** [twbs/bootstrap#26532]
I use Webpack to generate a vendor.css and an app.css. vendor.css contains all the bootstrap styles and the app.css the styles for the application.

I want to use the sass variable and mixins in the app.css, but if I import the bootstrap into my app.sass, the vendor styles are included.

How can I import the sass variables and mixins only?

**Comment by marcoflorian** [comment]
At the beginning of any sass file import the functions, variables and mixins files.

```
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
```

**Comment by janswist** [comment]
Can you do it once globally? For bigger projects it might be a bit repetetive.
