### ISSUE TITLE
Simplyfy classes for carousel images

### ISSUE THREAD

**Issue by midzer** [twbs/bootstrap#26535]
Hi all,
in docs it states for carousel: `Note the presence of the .d-block and .w-100 on carousel images to prevent browser default image alignment.`

Doing some testing on this subject, it seems `img-fluid` is enough for this task: https://codepen.io/bugmenot/pen/OZrPyY

Would be happy to do PR, if I'm not misleading on this subject.

Cheers
midzer

**Comment by mdo** [comment]
We'll leave it as-is, thanks.
