### ISSUE TITLE
Url in background-image are not encoded

### ISSUE THREAD

**Issue by pvollenweider** [twbs/bootstrap#26530]
Some background images define SVG threw data:image.
This URL should be better encoded (at least replace spaces with %20 to prevent related issues such as https://github.com/yui/yuicompressor/issues/274)

**Comment by pvollenweider** [comment]
Here is a pull request that should make such URLs more readable in the Sassy CSS variables file using a simple sunction. https://github.com/twbs/bootstrap/pull/26529

**Comment by wolfy1339** [comment]
This is a duplicate issue. Please check your PR, for the aforementioned issue

**Comment by pvollenweider** [comment]
duplicate https://github.com/twbs/bootstrap/issues/25211
