### ISSUE TITLE
How does preview.twbsapps.com work?

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#26541]
This PR #20179 looks interesting, but how does it work?

cc @cvrebert

**Comment by Johann-S** [comment]
IMO currently it's not used because this script is never called : https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L62

**Comment by XhmikosR** [comment]
We might as well remove the script if it's obsolete.

**Comment by Johann-S** [comment]
Finally I found it's called here: https://github.com/twbs/bootstrap/blob/v4-dev/.travis.yml#L17

**Comment by mdo** [comment]
Let's remove it since it's unused.
