### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by ItsPugle** [twbs/bootstrap#26546]
Hey,

I'm looking through the [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), and I've noticed that it directs future-contributors to edit documentation on the master branch, under the `/bootstrap/docs/` directory.

> Similarly, when contributing to Bootstrap's documentation, you should edit the documentation source files in the /bootstrap/docs/ directory of the master branch. Do not edit the gh-pages branch. That branch is generated from the documentation source files and is managed separately by the Bootstrap Core Team.

However:

1. There is no `/bootstrap` directory (there is a `/docs` though)
2. The documentation in `/docs/_includes` hasn't been updated in ~2 years (apart from #23808)

So, should where should I be targeting my PRs against?

**Comment by coliff** [comment]
Hi. For changes to the Bootstrap 4 documentation you should make PRs against the `v4-dev` branch (which is the default). https://github.com/twbs/bootstrap/tree/v4-dev/docs/4.1
The docs includes are at: https://github.com/twbs/bootstrap/tree/v4-dev/_includes

Agree that the contributing guidelines could be updated to make that clearer though I don't think it's incorrect to specify that the root directory is `/bootstrap`. That is what shows in GitHub's web interface and it's referenced as such consistently in the documentation e.g.  `/bootstrap/scss/` and `/bootstrap/js/`

**Comment by ItsPugle** [comment]
Ah, gotcha! I'll make a PR with the changes that I was going to do originally, then also one for clarifying about Documentation PRs 😄 Thanks for your help!
