### ISSUE TITLE
Bootstrap 3 navbar dropdown arrow issue

### ISSUE THREAD

**Issue by cis-surbhi** [twbs/bootstrap#26547]
In Bootstrap 3 navbar dropdown arrow is not showing on ipad
--

![img_2147](https://user-images.githubusercontent.com/24669334/40311475-803f4f04-5d2d-11e8-867f-580382ccaa44.PNG)

**Comment by mdo** [comment]
We're not really maintaining v3 actively right now, so closing as a won't fix.
