### ISSUE TITLE
Border card-group doesn't work in a accordion collapse

### ISSUE THREAD

**Issue by Jaapinator** [twbs/bootstrap#26556]
I have no idea if it is my problem but when I use a card-group in a accordion collapse it doesn't show borders properly. 
Version: bootstrap 4.1.1
Browsers: IE, Edge, Chrome, Opera, Firefox
Code: https://codepen.io/anon/pen/qYvLdN

**Comment by InsanityMeetsHH** [comment]
May be it is a bug [here](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L292)

**Comment by Gehanii** [comment]
It affects any cards that might be used inside the accordion, which limits the accordion's utility somewhat. It appears that this is the result of the "fix" for the doubled-borders for the accordions (#23836).

**Comment by Gehanii** [comment]
Wouldn't changing the rule from .accordion .card:first-of-type to .accordion > .card:first-of-type resolve both issues? It certainly looks like it is in dev for me but I also have rotten luck these days when I post something... :)

**Comment by linusbrolin** [comment]
Possibly related:
The bottom border is not visible when the accordion only has one child.
So this section:
```
.accordion {
  .card:first-of-type {
    border-bottom: 0;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
}
```
should really be changed to:
```
.accordion {
  .card:first-of-type:not(:last-of-type) {
    border-bottom: 0;
  }
  .card:first-of-type {
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
}
```

**Comment by zhulb001** [comment]
I noticed this also, I just took the accordion example from the documentation and deleted the two last cards and the first card does not have a bottom border.

**Comment by Ruffio** [comment]
I'm also seeing this issue as I use single item accordion. I ended up with overruling by usage of !important

**Comment by fabswt** [comment]
Indeed, accordions with a single card do not display properly. They lose their round borders (top and bottom) and their bottom border:

<img width="1140" alt="Bootstrap 4.1 accordion bug" src="https://user-images.githubusercontent.com/3042488/49452103-d5698f00-f7e0-11e8-9934-45b93c96b266.png">
