### ISSUE TITLE
Warning: Ruh roh! Could not save gist file, configuration not saved.

### ISSUE THREAD

**Issue by cylkee** [twbs/bootstrap#26558]
> Warning: Ruh roh! Could not save gist file, configuration not saved.

After clicking Compile and Download at https://getbootstrap.com/docs/3.3/customize/

Tested on Windows 10 (1803) in Firefox 60 and Chrome 66.

**Comment by mdo** [comment]
Regrettably v3 isn't supported much anymore. In all likelihood we'll take down the customizer in the future to negate these issues. Sorry for the hiccups! Your best bet is a third party customizer or your own build system.
