### ISSUE TITLE
Feature request: default .col behavior  of the direct .row descendants

### ISSUE THREAD

**Issue by apomili** [twbs/bootstrap#26564]
Is a silly idea to apply the style .col on the descendants of a row container if none is explicted?

Something like this

```
<div class="row">
    <div>Auto colum</div>
    <div>Auto colum</div>
</div>


<div class="row">
    <div class="col-md-6">Class behavior column</div>
    <div class="col-md-6">Class behavior column</div>
</div>
```

**Comment by mdo** [comment]
No, not silly, but an intentional choice on our part. Explicit styles means fewer overrides on our part. No plans to change this in v4 though.
