### ISSUE TITLE
_tables.scss contains overly broad selectors

### ISSUE THREAD

**Issue by nickcoad** [twbs/bootstrap#26560]
In my opinion the selectors used for styling tables in Bootstrap (in _tables.scss) are not specific enough and result in false hits. The selectors, when generated, look like this `.table tr td` for example. This selector will hit any `td` inside `.table`, even if those `td` elements reside within a table that does not have the `.table` class.

The selectors in _tables.scss should really be using the direct descendant selector to ensure that it only captures cells and rows belonging to that particular table and doesn't catch nested tables.

It's possible I guess that this was a deliberate design decision, but I think it should be re-examined. As an example:

```
<table class="table">
    <tr>
        <td>I would expect this to be captured and styled.</td>
        <td>
            <table>
                <tr>
                    <td>I would not expect this table to be styled like a Bootstrap table.</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
```

**Comment by patrickhlauke** [comment]
Sounds reasonable that the selectors could be rewritten to target only the direct descendant `tr` and `td` (a la `.table > tr > td`. Docs to be updated to then note that when using nested tables, and you DO want them to be styled, you need to add `.table` to each sub-table.

**Comment by nickcoad** [comment]
Note that some tables will have the `tr` and `td` inside `thead` or `tbody`, so you would need to include `thead` and `tbody` for some of the rules:
```
.table > thead,
.table > tbody,
.table {
    > tr > td {
        // Some stuff
    }
}
```

**Comment by mdo** [comment]
This would be a breaking change, and it was purposefully changed _to_ this setup from v3, which had the direct descendant selectors. For now, closing as a won't fix.

**Comment by nickcoad** [comment]
It did occur to me that it would be a breaking change and unlikely to be fixed, but thought I'd raise it just in case. Out of interest, is there an issue recorded for the original change to the non-specific selectors? Curious about the reasoning behind the change. It seems to be counter to expectations, unlikely to be the desired behaviour and difficult to work with as you would need to manually reset all the Bootstrap styles on nested tables (and if the Bootstrap styles change you'll need to know this and tweak your resets).

I'm sure it was required for something, hence the request for information because my curiosity is piqued now. But if not it seems like something worth revisiting if there is ever another major version with breaking changes that this could also go into.

**Comment by mdo** [comment]
It's mentioned on our migration page: https://getbootstrap.com/docs/4.0/migration/#tables. There's also likely a PR for this, but I can't dig up right now. High level though, the selectors are incredibly gnarly and often over done for common needs.

**Comment by patrickhlauke** [comment]
@mdo however, there's currently no way to have a non-bootstrapped table inside a bootstrapped table (unless you make your own styles that essentially undo the bootstrap styles)...

**Comment by mdo** [comment]
@patrickhlauke Correct, a trade-off I made long ago during v4's development as I was rewriting these styles. If we wanted to support something like this again, it'd either have to wait for v5 or be another selector and separate set of styles.
