### ISSUE TITLE
Icons inside collapse card take the entire row.  

### ISSUE THREAD

**Issue by carpben** [twbs/bootstrap#26565]
I'm trying to display 3 icons horizontally inside a collapse card. I added the icon (i tags) into the card, but they show vertically. For some reason the i element takes the entire line. I tried changing css properties, including: 
``` 
display: inline; 
width: 20px
```
I also tried changing the parent div to ```display: flex```. All of those did not help. 
Here is a Jsfiddle example: https://jsfiddle.net/benCarp/Lz40t409/

These doesn't seem to be the desired behavior of an expansion card. Not sure what causes this unique behavior of the icons inside of the card.

**Comment by ryelo** [comment]
It looks like `.card` has a `flex-direction: column` as you can see [here](https://github.com/twbs/bootstrap/blob/c2b13b9c7851d62d3072989552a784e6c598580b/scss/_card.scss#L8).

You can, for example, set the `.card`'s `flex-direction` to `initial` or `row` just to see how it could change.

**Comment by alecpl** [comment]
The html structure is wrong. `.card-body` should be a child of `.card`.

**Comment by alecpl** [comment]
At least for 4.1 this is not true. https://getbootstrap.com/docs/4.1/components/card/

**Comment by mdo** [comment]
> I just checked "card" and "card-body" are there on the same div.

We should change that in our docs example.

**Comment by NirvashPrime** [comment]
I see the docs have been updated. Is this still an issue?

**Comment by mdo** [comment]
Closing since docs were adjusted.
