### ISSUE TITLE
macOS High Sierra & Firefox. Enabling scrollbars to display "always" causes page behind modal to move on opening modal

### ISSUE THREAD

**Issue by DannyJJK** [twbs/bootstrap#26562]
To replicate this issue:
- I'm using a MacBook Pro with Retina display. The Retina display may assist in causing the issue but I'm not sure.
- On macOS High Sierra, go to System Preferences then General and set "Show scroll bars" to "Always".
- Open the bootstrap modal documentation pages, both v3 and v4 replicate the issue
https://getbootstrap.com/docs/3.3/javascript/#modals
https://getbootstrap.com/docs/4.1/components/modal/
- Press the "Launch demo modal"

You should see the page "move" because the scroll bar disappears. Normally Bootstrap applies padding to the body of the page to accomodate this and it seems to work correctly in both Chrome and Safari, but it does not always seem to get added on Firefox. I have also tested Firefox in Windows which worked correctly to (scrollbars were already displaying by default)

**Comment by MartijnCuppens** [comment]
I just tested this with Firefox 64.0 and everything looks fine. Can you check if everything is fine or your side, @DannyJJK?

**Comment by DannyJJK** [comment]
Yes this seems to be working fine now 👍 Thanks
