### ISSUE TITLE
[OSX][Chrome] button-default doesn't have background

### ISSUE THREAD

**Issue by adomas000** [twbs/bootstrap#26566]
Tested on 2 macs, and 5 windows pc, at very least if the syntax is incorrect, the result should be consistent. 
http://jsfiddle.net/x1hphsvb/4586/

Chrome version: 66.0.3359.139 64-bit (Mac OS)

**Comment by Johann-S** [comment]
Hi @adomas000 can you test with our latest release ? (4.1.1)

**Comment by patrickhlauke** [comment]
there is no `btn-default` class in bootstrap 4 anymore http://getbootstrap.com/docs/4.1/components/buttons/

**Comment by adomas000** [comment]
I see, didn't bother to look at the docs since it was obviously working the same on all windows browsers I tested on with 'btn-default'. Sorry for bothering you, should have paid more attention myself.
