### ISSUE TITLE
Custom file input has no focus indication in Firefox

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#26563]
It's because the input element itself is hidden with `opacity:0`. However I think it would be possible with something like `.custom-file-input:focus + label` selector.

ps. I think `position:relative` on `.custom-file-input` is redundant.

**Comment by andresgalante** [comment]
Hi @alecpl , are you sure?

it does here http://getbootstrap.com/docs/4.1/components/forms/#file-browser

![screen shot 2018-05-23 at 4 12 31 pm](https://user-images.githubusercontent.com/1832037/40446009-29a743d6-5ea4-11e8-9f41-fd60e7ae8643.png)

**Comment by alecpl** [comment]
Indeed. It have to be some Firefox (59.0.2) issue. It works when I use developer tools, but not when I jump to the input using keyboard. No issue in Chrome.

**Comment by ysds** [comment]
I have confirmed. Firefox ignores the `input[type="file"]:focus`. [firefox input type file :focus bug](https://www.google.com/search?q=firefox+input+type+file+%3Afocus+bug)

**Comment by alecpl** [comment]
And I've found a workaround: `.custom-file:focus-within .custom-file-label`. Would be nice to have it in the next patch release.

**Comment by alecpl** [comment]
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1430196
