### ISSUE TITLE
Support for responsive list columns.

### ISSUE THREAD

**Issue by trufa** [twbs/bootstrap#26575]
I would like to implement a feature for lists.

Were you would be able to use a responsive class to modify the amount of columns in a list.

```
<ul class="columns-2">
  <li>In col one</li>
  <li>In col two</li>
</ul>
```

Or 

```
<ul class="columns-md-2">
  <li>In col one</li>
  <li>In col two from md-onwards</li>
</ul>
```

Basically the class would be applicable to `<ul>, <ol>, and <dl>` and have the format: `columns-{breakpoint}-{amount}`.

I would implement using the css[ columns property](https://caniuse.com/#search=columns).

Is there interest for this feature?

**Comment by flexjoly** [comment]
As far as I can see, you can do this with:
```
<div class='row'>
  <div class='col'>col 1</div>
  <div class='col'>col 2</div>
</div>
```
Maybe you can do this on ul/li also...

**Comment by mdo** [comment]
Passing on this, thanks for the suggestion though!
