### ISSUE TITLE
input-group hidden at load not rendering correctly  

### ISSUE THREAD

**Issue by dev810vm** [twbs/bootstrap#26574]
I have a number of input groups hidden at load and shown using $.show(). When they're shown the input is 1% width and the input-group-text is wrapped to the next line.

```
<div class="input-group mb-3 rename-file">
            <input type="text" class="form-control file-textbox" value="@file.FileName">
            <div class="input-group-append">
                <div  class="input-group-text">@file.Extension</div>
            </div>
        </div>
```

![image](https://user-images.githubusercontent.com/29607205/40457751-2339685e-5ec6-11e8-8736-b178fe3737dd.png)

**Comment by razh** [comment]
`.input-group` uses `display: flex`.

jQuery's`.show()` applies a `display: block` style to the `.input-group` element.

Toggle the `.d-none` class or the `hidden` attribute instead.

**Comment by mdo** [comment]
Yup, see previous comment.
