### ISSUE TITLE
npm install bootstrap

### ISSUE THREAD

**Issue by reachdevelopers** [twbs/bootstrap#26582]
`npm install boostrap` installs version 2.0.0

**Comment by fredDesign** [comment]
OUCH

npm install bootstrap
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bootstrap@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by zengxianglinSimon** [comment]
node.js: npm install bootstrap -g, the result is: date of all .js file is 1985-xx-xx???
