### ISSUE TITLE
Enlarge color palette and variables

### ISSUE THREAD

**Issue by djibe** [twbs/bootstrap#26581]
Hi,
for easier plugin integration and site editing, could we enrich the :root variables with 2 more tones for each color, --color-light and --color-dark (ex: --primary-light and primary-dark)
So does Maya Ma in his Daemonite material theme and it is awesome for an everyday use. See CSS here : https://github.com/Daemonite/material/blob/master/css/material.css

Therefore we can use these variables in plugins for perfect theme match. Ex : https://jsfiddle.net/djibe89/t5sqqw8L/
All the colors of the Datetimepicker are provided by --variables of the material.css

Thanks a lot.

**Comment by mdo** [comment]
No plans to add to those CSS variables right now.
