### ISSUE TITLE
Card Columns is badly structured

### ISSUE THREAD

**Issue by Vimal-Raghubir** [twbs/bootstrap#26586]
In the Documentation / Components / Cards > Card columns section, there is a duplicate section in the second column and in the third column the card title box is in the wrong position. It should be connected to the image like the two previous columns.

**Comment by coliff** [comment]
I thought the example was designed intentionally like that to show how different size and style cards can work together in columns.

As it mentions in the introduction - it allows for Masonry-like columns. See the site for examples: https://masonry.desandro.com/

**Comment by Vimal-Raghubir** [comment]
![old look](https://user-images.githubusercontent.com/25648267/40666245-3f937074-632d-11e8-83da-53c332b47c2a.PNG)

As you can see the card column that has the black outline is a duplicate of the card column above and the red column is the one that had to be placed into the card body like the 2 sections before it.
