### ISSUE TITLE
List inline needs vertical alignment

### ISSUE THREAD

**Issue by vosidiy** [twbs/bootstrap#26592]
I suggest to add  vertical-align:middle   to   .list-inline-item 

.list-inline-item{vertical-align:middle;  ..... other styles }

Reason is: 
I added inline form inside list inline item, But alignment not in same line, After long research :-) Solved simply by adding 
.list-inline-item{vertical-align:middle}
check image ( this is product filter bar) 

![1](https://user-images.githubusercontent.com/36692987/40545551-bbf60452-601b-11e8-8aee-323c23bc21f9.png)

**Comment by andresgalante** [comment]
Hi @vosidiy I don't think this is a problem on Bootstrap codebase. You'll probably need more structure for that usecase, flexing it and centering it would do it. 

You could use utility classes http://getbootstrap.com/docs/4.1/utilities/flex/

**Comment by mdo** [comment]
Agreed on previous comment.
