### ISSUE TITLE
bootstrap 3.3.7 local min.js works but cdn min.js does not

### ISSUE THREAD

**Issue by HastyK** [twbs/bootstrap#26591]
I have just downloaded the official bootstrap 3.3.7 and it works fine out of the box but when I change the local links to maxcdn as recommended it does not

`<script src="../../dist/js/bootstrap.min.js"></script>`  -  works!

`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>`  -  Does NOT work!

any ideas please

**Comment by XhmikosR** [comment]
What does work exactly?

**Comment by HastyK** [comment]
My apologies for not being more specific - I downloaded bootstrap 3.3.7 from here:-
https://getbootstrap.com/docs/3.3/getting-started/
I was interested in using docs/examples/navbar-fixed-top/index.html and it works fine as it is but bootstrap state :-

The folks over at MaxCDN graciously provide CDN support for Bootstrap's CSS and JavaScript. Just use these Bootstrap CDN links

```
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```


Using the CDN link the dropdown menu in the example does not work but if I use the local link:-
`<script src="../../dist/js/bootstrap.min.js"></script>`
then it works

**Comment by HastyK** [comment]
I am also confused about this line in the Footer:-
`<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>`
I have no idea what it is for or if I should remove it for CDN

**Comment by XhmikosR** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by HastyK** [comment]
Hi sorry I have no idea how to use CodePen or JS Bin or what a reduced test case is, Ijust wondered why local bootstrap.min.js works in this example and CDN does not - thanks anyway
