### ISSUE TITLE
Dropdown arrow placement

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26602]
I've recently been using the dropdown component in Bootstrap 4. I've recently noticed that the placement of the dropdown icon is a little off (see attached images). After inspecting the element and taking a look at the CSS for the `::after` pseudo element on the dropdown it's now clear as to why the placement looks off.

In the current CSS it looks like we're setting a **px** value rather than a **keyword** value, see below:

```
.dropdown-toggle::after {
    vertical-align: .255em;
}
```

**This gives the following result:**

![dropdowns](https://user-images.githubusercontent.com/25177538/40577269-ccfd85ba-60fa-11e8-9a42-d6bbf0cdc2e4.PNG)

Since we're currently setting the `::after` pseudo element on the dropdown to a static value it doesn't really become vertically centred. I think a better solution which would look slightly more visually pleasing is to set the value to `middle` rather than ` .255em`:

```
.dropdown-toggle::after {
    vertical-align: middle;
}
```

When we set it to **middle** it does indeed vertically centre the icon in the middle, **see below:**

![dropdowns-new](https://user-images.githubusercontent.com/25177538/40577307-3ad62920-60fb-11e8-9744-865873486841.PNG)

Notice how the icon now is flush with the text rather than slightly above it.

What's your suggestions on this?

**Comment by alecpl** [comment]
I agree. It should also help to remove some redundant style for drop right/left position.

**Comment by SanjanaSunil** [comment]
May I work on this issue?

**Comment by Johann-S** [comment]
@SanjanaSunil you can, it's open to everyone 😉

**Comment by mdo** [comment]
Sadly, `middle` sits far too low on macOS. Made a trade-off here for something that gets us pretty close to accurate across all major browsers.

**Comment by rj-wowza** [comment]
it should not include an icon at all, let the user pass an icon with the button label if they want one
