### ISSUE TITLE
Auto-sizing form label doesn't align correctly with custom form controls

### ISSUE THREAD

**Issue by andresgalante** [twbs/bootstrap#26616]
Since the custom select has a `width: 100%` [here](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L166) the [custom select goes to a new line when there is a label](http://getbootstrap.com/docs/4.1/components/forms/#auto-sizing):

![screen shot 2018-05-28 at 9 15 55 am](https://user-images.githubusercontent.com/1832037/40614253-79798c54-6258-11e8-910a-5e4829db8f5b.png)

I've added a `sr-only` class to the label on #26615 to fix the docs.

If an author wants to use a label with a custom element they can use the `form-inline` class on the form element and it'll work just fine, but not with Auto-sizing.

**Comment by mdo** [comment]
Yeah, we could override this to `width: auto` I think?

**Comment by mdo** [comment]
I think I'm going to close this as a won't fix? Only viable option I see here is to customize the `.col-auto` with some utilities (e.g., `d-flex` and margins).
