### ISSUE TITLE
.text-monospace / .font-monospace

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#26619]
The `.text-monospace` class name is little confusing. `.font-monospace` is more appropriate. Is there a plan to change the class name in the future (v5)? Is there a chance to coexist both classes in v4? Thanks.

**Comment by sts-ryan-holton** [comment]
I'm sure this once was `.font-monospace` and was changed to `.text-monospace` in 4.1?

**Comment by ysds** [comment]
That is a typo #26239. I think that the confusion of the class name caused the typo.

**Comment by andresgalante** [comment]
I agree `font` makes more sense than `text` for `monospace`.  Names are messed up [even in CSS](https://twitter.com/jensimmons/status/1001242807758196736).

A change now would be a breaking change, I'd avoid having 2 classes that do the same on v4, but I'll add this issue to v5 ideas.

**Comment by ysds** [comment]
@andresgalante OK, thanks. It’s up to you to close this issue or leave as a backlog.

**Comment by mdo** [comment]
Closing for now :).
