### ISSUE TITLE
Bootstrap 4.0.0-alpha.4

### ISSUE THREAD

**Issue by mcms90** [twbs/bootstrap#26610]
I'm using Bootstrap 4.0.0 alpha.4 and I have been having problems with this version all week. I have a web using it for some clients and if it is possible, I would need to know what happens and if this issue will be fixed early.

Thank you so much.

<img width="1347" alt="screen shot 2018-05-28 at 08 54 30" src="https://user-images.githubusercontent.com/18629125/40603783-e5bf40ec-6254-11e8-8f81-0c65558b09ed.png">

**Comment by midzer** [comment]
According to your screenshot it appears Bootstrap alpha 4 version has been removed from CDN.
Why not upgrade to latest version?

**Comment by patrickhlauke** [comment]
Indeed. In the first instance, please use the latest stable version of Bootstrap, not some alpha release.
