### ISSUE TITLE
anchor state color in text-emphasis-variant-mixin should be excluded

### ISSUE THREAD

**Issue by xima-eko** [twbs/bootstrap#26617]
if you give an anchor a class like "text-dark", it automatically gets the hover/focus color of darken($color, 10%). I would like to set the "active" state colors explicit and not like that.

So, for example, you have an anchor `<a ... class="text-dark text-active-primary">...` and the hover/focus color becomes the primary color. (i hate to overwrite implicit stylings and just wanted to change the color :) )

**Comment by mdo** [comment]
Closing as a won't fix for v4. I imagine we can change this in v5, but no plans for now.
