### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'global.bootstrap = {}')

### ISSUE THREAD

**Issue by panosru** [twbs/bootstrap#26611]
Hello,

I'm using gulp to process my assets for production.

![image](https://user-images.githubusercontent.com/400362/40607222-87f85342-6270-11e8-8e57-0c890c3467a8.png)

When I process my js files via babel (both v6 and v7) bootstrap throws the following error on the browser:

`TypeError: undefined is not an object (evaluating 'global.bootstrap = {}')`

![image](https://user-images.githubusercontent.com/400362/40607162-6010107c-6270-11e8-8fb8-01abd6fbe951.png)

When I remove the following code from gulp, then bootstrap works fine again...
```js
.pipe(babel({
    presets: ['@babel/env']
}))
```

but since I'm bundling the files, I have few files written in ES6, thus I really need babel.

Currently, as a workaround, I have bootstrap placed in a separated file, but I would prefer to have it bundled.

The issue for some reason is here: 

https://github.com/twbs/bootstrap/blob/976aad0059a22ec1251646a1b4a9f3454c7aed64/dist/js/bootstrap.bundle.js#L9

 I'm not sure why when bootstrap passed via babel the `global.bootstrap` is undefined.

Thanks!

**Comment by Johann-S** [comment]
You should avoid to compile Bootstrap which is already compiled, so you should exclude Bootstrap from you Gulp build process

**Comment by panosru** [comment]
But what if I want to bundle it in one file?

**Comment by Johann-S** [comment]
it's difficult to help you with just a few images 😟 you can bundle Bootstrap but you shouldn't compile Bootstrap

**Comment by panosru** [comment]
@Johann-S 
Thank you for letting me know that pass Bootstrap through babel isn't a good idea!

I ended up using `gulp-if` package and now I pass through babel only the scripts from my "allow" list:

```js
.pipe(gulpif(function (file) {
    // Pass through babel:
    return [
        'my-custom-script'
    ].includes(file.stem);
}, babel({
    presets: ['@babel/env']
})))
```

**Comment by jcemoller** [comment]
@panosru just ran into the same issue. In the original Bootstrap code _this_ is sent in the IIFE as the argument for _global_. After babel compiles the file, _this_ will be replaced with _undefined_. As to why, I do not have a clue and will try your solution to exclude Bootstrap in my gulp script. Thanks.
