### ISSUE TITLE
XSS possible in collapse data-parent attribute

### ISSUE THREAD

**Issue by 1Jesper1** [twbs/bootstrap#26625]
XSS possible in collapse data-parent attribute
`data-parent="<img src=1 onerror=alert(123) />"`
Bootstrap 4.1.1 in combination with JQuery 3.3.1

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by jenhae** [comment]
Hi @anarcat,

I don't know how the Debian LTS Team tested this issue, but I have an JSBin https://jsbin.com/xixaqeyofi/edit?html,output using bootstrap 2.3.0 which is affected by this CVE. I could track down the issue to line 34 of bootstrap-collapse using my example, see https://github.com/twbs/bootstrap/blob/v2.3.0/js/bootstrap-collapse.js#L34. This code behaves the same as https://github.com/twbs/bootstrap/blob/v2.0.0/js/bootstrap-collapse.js#L29.
