### ISSUE TITLE
Add form-feedback class to avoid "jumping" forms

### ISSUE THREAD

**Issue by georgmu** [twbs/bootstrap#26624]
If I use the .(in)valid-feedback class, there is no built-in possiblity to leave space for the feedback if it is not validated so far. Because of the sibling rule, I cannot embed the .invalid-feedback into a div with a min-height.

Now, when validating a form (only .invalid-feedback, no valid-feedback) with invalid syntax the content below the input jumps down when .invalid-feedback gets active

Thus, I propose to add a form-feedback container to allow reserving some space.

Here my example css code, limited to .invalid-feedback:

```
/* show invalid-feedback inside form-feedback if form was validated and form control is invalid */
.was-validated .form-control:invalid ~ .form-feedback .invalid-feedback {
  display: block;
}

/* reserve some space for the embedded invalid-form */
.form-feedback {
  margin-top: 0.25rem;
  min-height: 1.25em;
}

/* margin-top is applied by .form-feedback, don' add it again */
.form-feedback .invalid-feedback {
  margin-top:0;
}
```

**Comment by kambleaa007** [comment]
ok

**Comment by georgmu** [comment]
Should I prepare the changes and crate a pull request?

**Comment by mdo** [comment]
No plans to add this ourselves as part of the form layout or feedback styles.
