### ISSUE TITLE
XSS possible in data-target property of scrollspy

### ISSUE THREAD

**Issue by 1Jesper1** [twbs/bootstrap#26627]
XSS possible in scrollspy data-target attribute
`data-target="<img src=1 onerror=alert(123) />"`
Bootstrap 4.1.1 in combination with JQuery 3.3.1

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by 1Jesper1** [comment]
https://jsbin.com/toxogipewo/edit?html,output

Browser: Chrome Version 66.0.3359.181 64x
OS: Windows 10 64x
