### ISSUE TITLE
Tooltip position in responsive tables doesn't work

### ISSUE THREAD

**Issue by eugen0188** [twbs/bootstrap#26621]
Hi,

position is wrong, if the tooltip is used inside 'table-responsive' and the content (of the tooltip) is too big.

https://jsfiddle.net/bLbrkh4a/1/

the problem: 
'overflow-x: auto' of the 'table-responsive' class, so overflow-y  is hidden.

Any ideas?

**Comment by Johann-S** [comment]
Related to this Popper.js issue: https://github.com/FezVrasta/popper.js/issues/276

**Comment by eugen0188** [comment]
Its not only the tooltip. I have also select2 field (editable in the table).
Same problem with the overflow-y. The search field will not be completely shown,
beacause the overflow-y is hidden.

I think there are a lot of elements with the same issue.
So its not only the problem of the popper.js.
'table-responsive' makes this issues.

**Comment by Johann-S** [comment]
I don't understand why it's our issue, here, the bad positionning of your tooltip it's a Popper.js issue, and if you have an issue with select2 that's not our responsability too,
unless you show us a CodePen without any JavaScript plugin with the issue you have I won't reopen this issue

**Comment by eugen0188** [comment]
Ok, i agree to you. It's the problem of the popper / select2.

**Comment by simbunch** [comment]
Workaround that works for now:

    <div class="table-responsive" style="margin:-200px 0;">
        <table class="table" style="padding:-200px 0;">
            
        </table>
    </div>
