### ISSUE TITLE
Dropdown not positioning correctly inside navbar

### ISSUE THREAD

**Issue by redSilkTie** [twbs/bootstrap#26623]
I'm trying to place a dropdown on the right side of a navbar, but when it opens it goes off to the right edge of the screen and a scroll bar appears at the bottom of the browser. I've tried using standard bootstrap classes from the docs, but it doesn't work. Here's my markup (v4) : 
```
 <header class='mx-3'>
	<nav class='navbar sticky-top navbar-expand-md navbar-dark bg-dark'>
		<a href='/' class='navbar-brand'>SNAHL</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navContent" aria-controls="navContent" aria-expanded="false" aria-label="Toggle navigation">
	              <span class="navbar-toggler-icon"></span>
		</button>
		<div class='collapse navbar-collapse' id='navContent'>
                      <ul class='navbar-nav ml-auto'>
				<li class='dropdown nav-item'>
					<a role='button' data-toggle='dropdown' class='nav-link btn btn-info dropdown-toggle'></a>
					<div class='dropdown-menu'>
						<!-- NAVBAR CONTENT-->
					</div>
				</li>
			</ul>
		</div>
	    </nav>
    </header>
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Johann-S** [comment]
Please include our JavaScript in your CodePen

**Comment by redSilkTie** [comment]
[There you go](https://codepen.io/redsilktie/pen/LrRegE). I'm using the latest version of Bootstrap, this is happening both on Firefox and Chrome.

**Comment by danijelGombac** [comment]
@redSilkTie 

You need to add dropdown-menu-right to dropdown-menu. In navbar auto positionig is disabled.

**Comment by redSilkTie** [comment]
Thanks a lot it's fixed now
