### ISSUE TITLE
Change direction on carousel slide

### ISSUE THREAD

**Issue by ri8ika** [twbs/bootstrap#26626]
I'm facing an issue with the direction when the carousel slides. For eg.

`carousel.carousel(10)`

This will normally slide to 10th item but I need to change it's direction. But there's not any such something like this:

```
carousel.carousel({
  number: 10,
  direction: 'right'
})
```

Note: I'm aware of changing direction from css and ltr and rtl. But I need a solution with javascript.

**Comment by notaphplover** [comment]
Hi @ri8ika, yeah, it would be great to have that option.

If you want, I have an ugly workaround to you: https://jsfiddle.net/ypkrpdp6/2/

The idea is to use the carousel events to hack the carousel swaping elements.

If we want a transition with direction: right, we will swap my active children with the next element and then we will call next(), ensuring a transition with right direction. After the transition is complete, we will restore the carousel swaping the elements again.

The same is for direction: left.

Of course, it´s better to use something like 

carousel.carousel({
  number: 10,
  direction: 'right'
})

But I think that this could be helpfull until someone implement the feature requested.

**Comment by ri8ika** [comment]
@notaphplover 

Obviously, ugly workaround. But until someone utilize such feature, this workaround will be a great solution.

BTW, I'm also looking for some good solution myself. Once I figure out, I'll also post that here.

Thanks.

**Comment by ri8ika** [comment]
I wrote a function to slide the carousel in desired direction. Here's only pseudo code:

```
fn slideTo(carousel, number, direction):
  if direction == 'right':
    insert target carousel item before active item
    carousel.carousel('prev')
    setTimeout(fn: insert target item in previous position)
 else: 
   reverse code of 'right'
```
  
Now, we can use:

`slideTo(carousel, 10, 'right')`

**Comment by MRaafat53** [comment]
/* Change the direction of the transition.  Left To Right in **bootstrap4***/

`@media all and (transform-3d),
(-webkit-transform-3d) {
    .active.carousel-item-left,
    .carousel-item-prev:not(.carousel-item-right) {
        -webkit-transform: translateX(100%);
        transform: translateX(100%);
    }
    .active.carousel-item-right,
    .carousel-item-next:not(.carousel-item-left) {
        -webkit-transform: translateX(-100%);
        transform: translateX(-100%);
    }
}`

**Comment by mona-mohey** [comment]
> /* Change the direction of the transition. Left To Right in **bootstrap4***/
> 
> `@media all and (transform-3d), (-webkit-transform-3d) { .active.carousel-item-left, .carousel-item-prev:not(.carousel-item-right) { -webkit-transform: translateX(100%); transform: translateX(100%); } .active.carousel-item-right, .carousel-item-next:not(.carousel-item-left) { -webkit-transform: translateX(-100%); transform: translateX(-100%); } }`

It worked, Thanks, But it's kindda of slow!
what shall i do to make it a little fast, **Thanks again**.
