### ISSUE TITLE
Feature Request: Add Ability to Have Pure CSS Sticky Sidebars into Core Grid

### ISSUE THREAD

**Issue by whatnickcodes** [twbs/bootstrap#26639]
Here me out first... Based on this technique:

* https://scotch.io/tutorials/build-multiple-stacking-sticky-sidebars-with-pure-css-and-bootstrap-4

With Bootstrap 4 flex grid, all columns are equal height. See:

* https://codepen.io/ncerminara/pen/EjqbPj

This means doing `position: sticky;` is really easy, performant and useful for "sticky" content or affixing content.

Here's a demo in pure CSS:

* COMPLEX: https://codepen.io/ncerminara/pen/VdLpzd
* SIMPLE: https://codepen.io/ncerminara/pen/eKNROb

**PROPOSAL**

Add a `utility class` called `.make-me-sticky`. Where:

```sass
.make-me-sticky {
	position: sticky;
	top: 0;
        padding: 0 15px; // 15 is equal to padding of gutter
}
```

Then, based on column collapse of sm, md, lg have things additional class to disable the stickiness.

**Light-weight, easy, high functionality.**

Anyway just a thought. Love Bootstrap and feel like it makes sense to have as part of the project. `sticky` has really good browser support and at the very least will fall back to `position: relative` (partial support).

**Comment by TheCire** [comment]
I would suggest adding the Feature tag to this Feature request so it can show up with the rest

**Comment by mdo** [comment]
We have a sticky utility class for most of this—`.sticky-top`. No plans to add anything else.
