### ISSUE TITLE
Modal: slow scrolling on iOS

### ISSUE THREAD

**Issue by PolHaghverdian** [twbs/bootstrap#26631]
Hi,

The modal in Bootstrap 4 is very slow to scroll compared to the modal in Bootstrap 3. 

I was migrating from 3 to 4 , and noticed it there on my own site. 

Video is provided when testing the modals from the bootstrap examples on the site.  

https://streamable.com/2a8wa

Tested on iOS: 11.3 and 11.4 (latest)

**Comment by andresgalante** [comment]
Hi @PolHaghverdian your are right.

That's because we are not using `-webkit-overflow-scrolling: touch;` due to a browser bug:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L25-L27

 But you can turn it on by adding this snippet to your code:

```css
.modal { -webkit-overflow-scrolling: touch; }
```

**Comment by PolHaghverdian** [comment]
@andresgalante  Perfect thank you! 👍
