### ISSUE TITLE
Twitter/Facebook Image not showing (broken image link)

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#26637]
I noticed that the image doesn't show in the Twitter Card when sharing a link to the Bootstrap Docs on Twitter. (e.g. https://twitter.com/christianoliff/status/1002077097844621312).

I see in the docs markup the following:
`<meta name="twitter:image" content="https://getbootstrap.com/assets/brand/bootstrap-social-logo.png">`
but https://getbootstrap.com/assets/brand/bootstrap-social-logo.png is broken link.

Same issue wtih Facebook sharing since the same image is referenced:
`<meta property="og:image" content="http://getbootstrap.com/assets/brand/bootstrap-social.png">`

Do the Twitter Card / OpenGraph image links need updating to the following?
`http://getbootstrap.com/docs/4.1/assets/brand/bootstrap-social.png`

**Comment by XhmikosR** [comment]
The docs refactoring is again to blame...

/CC @mdo

**Comment by mdo** [comment]
Fixed in live docs.

**Comment by mdo** [comment]
Proper fix coming in #26732.
