### ISSUE TITLE
<a> without href is styled like a link

### ISSUE THREAD

**Issue by ehahn** [twbs/bootstrap#26636]
Bootstrap 3 styles `<a>` elements without a `href` attribute as if they were links. The only difference is that the cursor does not change when hovering over them and, of course, that clicking them does nothing.

The default styles of at least Firefox and Chrome do not do this, which I think makes more sense.

Example:

    <html>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <body>
    Not a link <br>
    <a>Not a link</a> <br>
    <a href="wherever">A link</a> <br>
    </body>
    </html>

**Comment by patrickhlauke** [comment]
Bootstrap 3 is in maintenance mode. Only critical patches are made to it, as development focus is now primarily on Bootstrap 4, I'm afraid.
