### ISSUE TITLE
btn-sm rendering (line-height?) issue on Android Chrome

### ISSUE THREAD

**Issue by sys-SB** [twbs/bootstrap#26641]
It seems like there is a line-height type rendering issue with text within the btn-sm buttons. The text (to my eye, at least) doesn't appear centered vertically within the button. This issue does not appear on any other button sizes, nor does it appear on desktop. First noticed on my own project but have noticed the same on the Bootstrap website itself. See image below from https://getbootstrap.com/docs/4.0/components/buttons/

OS: Android 8.0.0
Browser: Chrome 66.0.3359.158
Device: Moto G6 Plus

![screenshot_20180531-195229](https://user-images.githubusercontent.com/39809112/40802879-c7430452-650e-11e8-950f-4988f1bab66a.png)

**Comment by sys-SB** [comment]
I could not find the source of the problem on the Bootstrap website using the inspector, however I suspect it is something to do with the native font stack, perhaps different base line heights across different operating systems.

In my own project the issue was down to a webfont I was using. I suspect the built-in line height of that webfont was irregular which caused the issue. I've ended up reverting to the native font stack for all but heading tags/classes.

**Comment by coliff** [comment]
I can see this issue too on a Nexus 7 (2013) with Android 7.0 and Chrome 67.

![screenshot_20180601-234728](https://user-images.githubusercontent.com/1212885/40848102-2e831afe-65f9-11e8-9ecc-7ece35e91c19.png)

**Comment by MartijnCuppens** [comment]
This seems to fixed in the meanwhile
