### ISSUE TITLE
SCSS bootstrap question

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26640]
Does the Bootstrap SCSS variant include the prefixed browser classes for older browsers?

E.g:

```
.d-flex {
    display: flex !important;
}
```

it doesn't seem to contain the prefixed classes? I think it would be a good idea, especially for flex classes to include the older browser variants as part of the SCSS files as sometimes it's not always possibly to use NPM or some other build tool in a project, I'd much rather just import Bootstrap SCSS like:

```
@import "bootstrap-reboot";
@import "bootstrap";
```

... and have those classes added. Am I missing something here?

**Comment by fchiumeo** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L29

**Comment by XhmikosR** [comment]
https://getbootstrap.com/docs/4.1/getting-started/download/#source-files
