### ISSUE TITLE
Improve how we traverse the DOM

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#26643]
I think we need to eventually do the following across the whole codebase:

1. use `querySelector` when we just need the first match
2. use `node.querySelectorAll` instead of `document`
3. **always** cache the result to a var

These might be micro-optimizations, but they should definitely help with large DOMs.

**Comment by arunikayadav42** [comment]
Definitely :)

**Comment by arunikayadav42** [comment]
but exactly how do I start , can you let me know please.I am a beginner to open source

**Comment by Arvind-Suthar** [comment]
Can i know the problem with large DOM
I can help minimize the problem?
