### ISSUE TITLE
Migration to GitLab

### ISSUE THREAD

**Issue by ItaloBC** [twbs/bootstrap#26659]
[Microsoft acquired GitHub](https://www.theverge.com/2018/6/3/17422752/microsoft-github-acquisition-rumors).

There is a [tutorial to import to GitLab](https://www.youtube.com/watch?v=VYOXuOg9tQI&feature=youtu.be).

**Comment by wolfy1339** [comment]
At this point those are just rumors. And it is up to the Bootstrap team to make that decision to migrate.

**Comment by ItaloBC** [comment]
@wolfy1339 We must prepare for the storm. Save water. Gather the troops. The end is near.

**Comment by bkdotcom** [comment]
![ynlqwrm](https://user-images.githubusercontent.com/2137404/40893746-83ebb610-6769-11e8-844b-14247abbe836.jpg)

(apologies)
