### ISSUE TITLE
Modal dialog documentation error

### ISSUE THREAD

**Issue by winzig** [twbs/bootstrap#26655]
The [modal documentation](https://getbootstrap.com/docs/4.0/components/modal/) has an example modal dialog near the top with the primary button on the right side. In the example HTML below it, the primary button is defined first, and so would appear on the left if rendered, making the documentation confusing. (At first I got excited because I thought Bootstrap was doing something fancy at the platform level to control primary button placement according to OS guidelines.)

<img width="792" alt="screen shot 2018-06-02 at 11 33 01 am" src="https://user-images.githubusercontent.com/127062/40879702-bb20808c-6658-11e8-9dd8-289a9a006601.png">

**Comment by Bennet11** [comment]
Hi,
   I remember fixing this on #25855 but apparently it's still there? Thanks for the heads up though

**Comment by thatnini** [comment]
Your fix appears in [4.1 version](https://getbootstrap.com/docs/4.1/components/modal/) of the docs.
