### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by nftstudio** [twbs/bootstrap#26657]
so,how to use gulp.js?
my gulp.js tools list
gulp
gulp-concat
gulp-uglify
gulp-rename
gulp-ruby-sass
gulp-autoprefixer
gulp-clean-css
gulp-sourcemaps
gulp-sequence

**Comment by patrickhlauke** [comment]
Bootstrap 3 uses grunt. https://getbootstrap.com/docs/3.3/getting-started/#grunt
Bootstrap 4 npm scripts http://getbootstrap.com/docs/4.1/getting-started/build-tools/#using-npm-scripts

for anything else, suggest you ask on StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
