### ISSUE TITLE
Can we support BootStrap 3 existing  CSS in BootStrap 4, if yes How to Migrate  ?

### ISSUE THREAD

**Issue by akashshrimali** [twbs/bootstrap#26661]
We are planning to migrate from bootstrap 3 to Bootstrap 4 however, we are finding couple of changes in the C.S.S. 
For example: form-group-margin is now form-control-margin and other related changes..

Can we minimize the impact and perform the migration ?

**Comment by Johann-S** [comment]
Sorry that's a major release so there are breaking changes, you can find a migration guide here : https://getbootstrap.com/docs/4.1/migration/
