### ISSUE TITLE
there is case when text inside small button is not perfectly aligned vertically 

### ISSUE THREAD

**Issue by rpokrovskij** [twbs/bootstrap#26666]
https://codepen.io/rpokrovskij/pen/GGZwpV

text inside button is not perfectly aligned vertically. it even doesn't look as small button.
it depends on form sturcture.

true for BS 4 an 4.1

**Comment by mdo** [comment]
You're mixing grid classes with components, which per our grid docs you shouldn't do. Place the `.row` on a parent wrapper instead of the `.form-group`.
