### ISSUE TITLE
Bootstrap 4.1.1 input-group issue

### ISSUE THREAD

**Issue by lugavin** [twbs/bootstrap#26665]
When add some validation messages inside the input group, the **border-(top|bottom)-right-radius** style of form control doesn't work.  Code see: https://jsfiddle.net/lugavin/aserqdx4/1/

![issue](https://user-images.githubusercontent.com/28991162/40979942-cc131d56-6909-11e8-8150-68d05938eccf.JPG)

**Comment by alecpl** [comment]
This is duplicate of #25110.

**Comment by Johann-S** [comment]
Closed as duplicate 👍 thanks @alecpl
