### ISSUE TITLE
Documentation – Missing gradients on Utility/Colors

### ISSUE THREAD

**Issue by muuvmuuv** [twbs/bootstrap#26675]
Gradients are not visible: https://getbootstrap.com/docs/4.1/utilities/colors/#background-gradient

**Comment by MartijnCuppens** [comment]
Read the bold text.

**Comment by ahtee** [comment]
The documents say $enable-gradients is disabled and the example is intentionally left broken

**Comment by MartijnCuppens** [comment]
Because if it is enabled by default, all buttons (and some other elements) will have gradients. `$enable-gradients` gives you the choice: _Do I want gradients or not?_

**Comment by muuvmuuv** [comment]
Ah now I got it, thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
