### ISSUE TITLE
bootstrap-solid.svg is 404

### ISSUE THREAD

**Issue by davethegr8** [twbs/bootstrap#26673]
On https://getbootstrap.com/docs/4.0/components/navbar/, the bootstrap-solid.svg image is throwing a 404.

`https://getbootstrap.com/assets/brand/bootstrap-solid.svg`

![screen shot 2018-06-05 at 2 52 21 pm](https://user-images.githubusercontent.com/55392/41004844-20f5272c-68d0-11e8-95bd-0d6c2b56c31f.png)

**Comment by davethegr8** [comment]
I'm not sure if this is an issue since the current version is 4.1 and that page looks fine (https://getbootstrap.com/docs/4.1/components/navbar/) and the cause looks like probably the new docs url format, but I thought I'd open an issue anyways.

**Comment by XhmikosR** [comment]
@mdo: please make sure you copy all the brand assets for v4.0 too.

**Comment by mdo** [comment]
Pushed a commit to `gh-pages` to resolve.

**Comment by tonykelly** [comment]
I get the same error and am using v4.13. Am loading Bootstrap from <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">.

Haven't yet tried the locally hosted version of 4.13

**Comment by AndRossi** [comment]
I get the same error using Bootstrap 4.1.3 from the [webjars mvnrepository](https://mvnrepository.com/artifact/org.webjars/bootstrap/4.1.3).
