### ISSUE TITLE
Bootstrap .bundle.js content file

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26679]
I'm not sure how many will agree with me on this one, but after using Bootstrap for some time, it's genuinely taken me a while to figure out exactly what the `bootstrap.bundle.js` file actually contains. In fact, for a long time, I've defaulted to the `bootstrap.min.js` file and have followed the **Getting Started Introduction** section found here => https://getbootstrap.com/docs/4.1/getting-started/introduction/#js and have simply used the link to **jQuery**, and the link to the **popper.js**.

I decided to see if I can find out more about what the `bootstrap.bundle.js` file actually is, and found this hidden away in the **Contents** section (https://getbootstrap.com/docs/4.1/getting-started/contents/#precompiled-bootstrap):

> This is the most basic form of Bootstrap: precompiled files for quick drop-in usage in nearly any web project. We provide compiled CSS and JS (bootstrap.*), as well as compiled and minified CSS and JS (bootstrap.min.*). CSS source maps (bootstrap.*.map) are available for use with certain browsers’ developer tools. Bundled JS files (bootstrap.bundle.js and minified bootstrap.bundle.min.js) include Popper, but not jQuery.

In particular, the last sentence, without any prominence:

> Bundled JS files (bootstrap.bundle.js and minified bootstrap.bundle.min.js) include Popper, but not jQuery.

Now, I'm not sure if this is just me, but personally, I think we should state what the `bootstrap.bundle.js` does on the getting started section: https://getbootstrap.com/docs/4.1/getting-started/introduction/#js

I think it needs to be made a little clearer, and lastly, I'm just wondering whether the term `bundle` is actually clear enough? For me, I figured it might be: Bootstrap, Popper and jQuery all together, but then found out it doesn't include jQuery.

**Whilst it possibly might be a breaking change to change the file name, I think it should be made a little clearer on the getting started section, and actually, wouldn't take too long to implement other than a README.md update? or something similar.**

**Comment by Johann-S** [comment]
No concerns about that change 👍 feel free to make a PR @sts-ryan-holton

**Comment by sts-ryan-holton** [comment]
@Johann-S  PR submitted :)
