### ISSUE TITLE
(modal, feature): Add ability to overlay a specific element

### ISSUE THREAD

**Issue by AbakumovAlexandr** [twbs/bootstrap#26677]
Currently, modal can block the whole page only. However, if you have a more complex layout, you often want to be able to have an interactive component allowing to overlay just a specific element without blocking the rest of the page.

The quick example could be a layout containing a header menu and a tab set below. Each tab content represents components user could interact independently with. In this case, if such component wants to show a modal, it should not block the rest of the page, i.e. menu, switching to other tabs, etc.

**Comment by ItaloBC** [comment]
For what I have read, the Modal purpose is to block the page against a needed user notification or action. If there is not a need for that, you shouldn't use a Modal at all.

The problem is that the `modal-backdrop` is appended at the end of the body, and only one modal can appear in the page at a time.

It's not quantum science to make your own modal appear using bootstrap's SCSS, or jQuery for that matter. You would need to append a backdrop to the parent tag, show the modal, and have the right event listeners.

**Comment by AbakumovAlexandr** [comment]
@ItaloBC , Right, but are there any technical issues, BS API worsening or unreasonable effort to make the current modal so flexible, that it appends its `modal-backdrop` to the end of a specific element instead of `body` and allow multiple instances of it?

Sure, I can implement my own one, but I'd like to propose we have this flexibility in BS out-of-the-box.
It's fine it could be only modal at a time.

**Comment by ItaloBC** [comment]
@AbakumovAlexandr I sincerely think that over a mobile-first web, multiple modals would be a cluster f*. IF you need to hook a modal to a parent, I think modals its not what you need. And extending Bootstrap to multi-modals would hinder the experience unless you are doing an SPA JS-driven App, were you can save the state of the page. In the latter case, you would make your own implementation.

**Comment by AbakumovAlexandr** [comment]
You probably right about multiple modals in mobile web apps. However even in this case, forcibly leaving framework users with a single modal at a time feels like not the best approach.

Moreover, there are huge number of BS apps that do not care about how they good they are on mobile devices.

My point is that devs of the specific app must be able to decide what is right and what is not when it comes to their app's UX and BS should not limit them in cases where it easily could provide flexibility.

**Comment by ItaloBC** [comment]
First, I don't think BS will ever get multiple modal in the short term. Modals behave like iOS modals, where you are bound to take a decision (like accepting or dismissing) that you can't avoid. That's the point of the modal. If you need to make multiple modals, **modals may not be what need**. You may want to take a look into making [Notifications](http://bootstrap-notify.remabledesigns.com/) instead.

> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

Second, and again, you're free to make your own implementation using Bootstrap as a foundation, and adding the event listeners you need to make.

> My point is that devs of the specific app must be able to decide what is right and what is not when it comes to their app's UX and BS should not limit them in cases where it easily could provide flexibility.

Nobody said BS limits you. You can still use the modal classes to bring your own modal implementation a bound it to a parent if you think modals is the only way to fix your problem. If you think BS limits development then you should make your own framework without these self-imposed limits or understand better the concept of a front-end framework.

**Comment by AbakumovAlexandr** [comment]
@ItaloBC , the very point of the statement you've quoted from the BS docs:

> Nested modals aren’t supported as we believe them to be poor user experiences.

is that:
We understand that nested modals is a valid real-world scenario, but we believe them to be poor user experiences.
This is to answer to your first point.

As per second, BS team

> **_believes_** them to be poor user experiences

Since it's opinion-based decision, as I already said this issue is opened in attempt to reconsider it, since there are valid real-world scenarios for it and it does not seem to be the best approach to leave framework users with limited functionality when you could provide flexibility with ease, and only then.

Also, since it's a valid scenario which could benefit the community, there is no point in saying "make your own framework, if you need it".

**Comment by ItaloBC** [comment]
Then extend Bootstrap.

I rest my case, your honor.

**Comment by AbakumovAlexandr** [comment]
No, I still would like to go the better way: proposing a feature and openly discussing its pros and cons with the team (hopefully) and the community :)

**Comment by Johann-S** [comment]
IMO we wont change that behavior that's a design choice, multiple modal for us is a bad practice and as a framework we shouldn't encourage this practice.

/CC @mdo

**Comment by AbakumovAlexandr** [comment]
@Johann-S , thank you. We understand that the team considers it to be a bad practice.

My thoughts on encouraging part. I think we have to answer this question:

> If we add the ability to have multiple modals, would people, who otherwise does not intend to have a design with multiple modals, use it just because this feature exists?

My common sense says "No". Every framework we use has tons of features including those that could be considered bad under certain circumstances. However, we do not use them if we do not need them and use them when our design requirements dictate so.

Moreover, having added this feature, you always could add a clear message "You can even open multiple modals, but we strongly believe it is a bad practice and discourage you from using it" to the docs.

**Comment by bpierson** [comment]
@AbakumovAlexandr try this JS code. Been using it for stacked modals for years with BS3 and seems to work unchanged with BS4:

    $(document).on({
        'show.bs.modal': function () {
            var zIndex = 1040 + (10 * $('.modal:visible').length);
            $(this).css('z-index', zIndex);
            setTimeout(function () {
                $('.modal-backdrop').not('.modal-stack').css('z-index', zIndex - 1).addClass('modal-stack');
            }, 0);
        },
        'hidden.bs.modal': function () {
            if ($('.modal:visible').length > 0) {
                // restore the modal-open class to the body element, so that scrolling works
               // properly after de-stacking a modal.
                setTimeout(function () {
                    $(document.body).addClass('modal-open');
                }, 0);
            }
        }
    }, '.modal');

**Comment by AbakumovAlexandr** [comment]
@bpierson , thank you! I'll give it a try and am sure it'll be helpful for others dealing with multiple modals in BS.

**Comment by mdo** [comment]
Modal is a blocking UI element—no intentions to change this or add other variations.
