### ISSUE TITLE
old version on https://getbootstrap.com/ 

### ISSUE THREAD

**Issue by cwildfoerster** [twbs/bootstrap#26684]
Hi,

i just noticed that the Bootstrap website delivers different content for HTTP and HTTPS!

- [https://getbootstrap.com/](https://getbootstrap.com/) Currently v4.0.0
- [http://getbootstrap.com/](http://getbootstrap.com/) Currently v4.1.1

**Comment by InsanityMeetsHH** [comment]
When i open the source code of both pages I see
````html
<!-- Bootstrap core CSS -->
<link href="/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
````
And when I open the css file
````css
/*!
 * Bootstrap v4.1.1 (https://getbootstrap.com/)
 * Copyright 2011-2018 The Bootstrap Authors
 * Copyright 2011-2018 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
````
So I can't confirm this. (Or they fixed it)

**Comment by cwildfoerster** [comment]
No, for me the HTTPS version is still v4.0.0

Where are you from? I'm from germany and the website is served by cloudflare, maybe their CDN is just wrong?

**Comment by sts-ryan-holton** [comment]
Already been discussed here - https://github.com/twbs/bootstrap/issues/26441, issue has been fixed as far as I'm aware and will go live at some point
