### ISSUE TITLE
.btn.btn-link's `white-space: nowrap` prevents long headings from wrapping

### ISSUE THREAD

**Issue by aumkarthakur** [twbs/bootstrap#26687]
As you can see in image attached, the Accordion title are not breaking by default, we have to apply `white-space:inherit;` on button to fix it. Please make it by default thing.

![image](https://user-images.githubusercontent.com/20535658/41153155-9278fce2-6b33-11e8-97a5-fca69cdec59a.png)

![image](https://user-images.githubusercontent.com/20535658/41153290-ee66fd9c-6b33-11e8-872f-25ada6fb97fe.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by aumkarthakur** [comment]
Hi Johann,

Here is the demo of the problem on codepen: https://codepen.io/aumkar/pen/oyZYWv

As you can see accordion title is overflowing it's parent instead of breaking.

Bootstrap version: 4.1
Browser: Chrome
Operating System: Windows

**Comment by mdo** [comment]
This is not the accordion heading, it's the `.btn` class. We could look at overriding this for the `.btn-link` class.

**Comment by mdo** [comment]
Fixed by #27010.
