### ISSUE TITLE
Unexpected chars in IE11

### ISSUE THREAD

**Issue by Jag2ooo** [twbs/bootstrap#26683]
The bootstrap-slider.js contains not JS conform quaotes. So all ` have to replace with ' to fix all IE11 errors.

**Comment by patrickhlauke** [comment]
Nothing to do with Bootstrap. Suggest you file this with whoever created/maintained bootstrap-slider.js

**Comment by patrickhlauke** [comment]
https://www.google.co.uk/search?q=bootstrap-slider.js
