### ISSUE TITLE
Card group Images don't scale down correctly in Chrome/Safari

### ISSUE THREAD

**Issue by tehunk** [twbs/bootstrap#26680]
There are similar issues I found from the last year #21885 and #22448 , but my case happens even without `.img-fluid` class.
Codepen: https://codepen.io/tehunk/pen/eKzqQo

**To reproduce**:
1. Create a card group
2. Add multiple cards with `.card-img-top` mixed with SVG and JPG

**Expected**: 
All card images scaled down with the correct ratio.

**Behavior**:
Firefox works fine, but Chrome and Safari disrespect the ratio of JPG.

When the `box-sizing` is changed to `content-box`, the ratio starts working correctly even though the size will of course increase. Or, if the `display` is changed to `block`, the ratio and size will be fine, but the footer won't be aligned. 

Finally, it may be just a Chrome flexbox bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=625560
https://github.com/philipwalton/flexbugs/issues/225

My workaround is to change box-sizing to content-box with shrinking width or wrapping image with another div as suggested in the flexbugs repo. The [example of Bootstrap](https://getbootstrap.com/docs/4.1/components/card/#example) shows using `.card-img-top` without a container, but I think this is subject to break image ratio on Chrome.

**Comment by mdo** [comment]
This issue only exists in that CodePen as far as I can see when you attempt to use `padding` on those images with the utilities. Place the padding elsewhere and there should be no issue. Could be just that?

**Comment by mdo** [comment]
Closing as a won't fix for now given prior comment.
