### ISSUE TITLE
Textarea lags in some cases

### ISSUE THREAD

**Issue by Stichoza** [twbs/bootstrap#26690]
## Description

The final result of bug is that textarea lags. Outer shadow appears slowly and scrolling the contents of the textarea becomes nearly impossible.

### The bug appears only if:

- Browser is Safari (WebKit).
- Bootstrap version 4 (All OK on v3).
- Only on unicode letters (Ex.: Georgian).
- If there are non-unicode letters in-between (like spaces).
- Textarea has larger height (probably 300px or more).

### The bug has no relation to:

- Custom CSS
  - This bug appears even on Bootstrap documentation
  - This bug also appears in the very textarea I'm typing this issue in (so, GitHub).
- JavaScript
  - Removed all js files and disabled JavaScript in browser, still lags.

### The lag stops when I:

 - Disable the `border-radius` on the textarea.
 - **OR** if I set the textarea font-family to Helvetica.

## Reproduction

You can simply copy the following text (just some random Georgian gibberish), paste into the comment textarea in this issue page.

Play with the textarea (focus, unfocus, scroll the contents, etc.). You'll see that the whole browser starts lagging and after several seconds the MacBook cooler (fan) will try to fly away from you.

### Text to copy

`
სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს სდკჯნფს სკჯდ ლსკდსდკფნჯკს კსდფჯ სდ დფკჯგ ჯდფგნ ჯდფნგ ჯდნფგ ნჯ ნაკსჯდნ აჯსდფ ჯსაიდნი ჯასფგ ჯდფნგ ჯკდფნგ ჯდნფჯგ ნაფდგნ აფსდფდს 
`

That's just a "sdkj jsdn sdjkfsdnjsdn fs" in Georgian.

----
Also involved in debugging of this issue: @Lotuashvili and @Lukakva.

**Comment by Stichoza** [comment]
I have temporarily fixed this using the following CSS:

```css
@supports (-webkit-backdrop-filter: blur(1px)) {
    /* Only in Safari */
    textarea {
        font-family: sans-serif !important;
    }
}
```

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Stichoza** [comment]
Sure thing! Here is a reduced demo: https://jsbin.com/waxalujeqi/1/edit?html,output

Just open it with Safari browser and focus-unfocus and scroll two textareas. First textarea is buggy, the second is normal.

**Comment by XhmikosR** [comment]
This seems more like a browser bug to me.

Did you try reporting the bug to Apple?

**Comment by Stichoza** [comment]
It seems that Apple has already fixed this in MacOS Mojave. I guess I should close it now. Thanks!
