### ISSUE TITLE
bootstrap-affix violent flicker when scrolling #4647

### ISSUE THREAD

**Issue by ventralnet** [twbs/bootstrap#26707]
http://jsfiddle.net/ventralnet/r6hL2z1m/show

I made a JSFiddle for #4647 as it doesn't look like anyone made one.  The comment section was disabled so I decided to open this issue.

Ultimately the issue is if your document height minus your affixed elements heights cause the y-axis scrollbar to go away once position:fixed is set, there will be flicker and your affixed items will be reset to the affix-top state.

**Comment by patrickhlauke** [comment]
thank you, but...bootstrap 2 is now quite out of date. closing this.

**Comment by ventralnet** [comment]
@patrickhlauke sorry my bad.  I forked a jsfiddle that was using a way old version of bootstrap.

I can confirm this is still an issue in the most recent v3 codeline (3.3.7) see below
http://jsfiddle.net/xzu15wfb/
http://jsfiddle.net/xzu15wfb/show

**Comment by patrickhlauke** [comment]
affix has been dropped in Bootstrap 4 https://getbootstrap.com/docs/4.1/migration/#components
Bootstrap 3 is very unlikely to get any more fixes, unless absolutely security-critical. leaving this here for posterity though.

**Comment by ventralnet** [comment]
Sounds good thanks. I wasn't sure of a real viable solution in it's current impl anyways.
