### ISSUE TITLE
The Bootstrap Carousel has role="listbox"

### ISSUE THREAD

**Issue by DavidMacDonald** [twbs/bootstrap#26701]
This doesn't appear to be a great use of the role. And if one can say a carousel is 
> "A widget that allows the user to select one or more items from a list of choices. " 

As is described in the [aria 1.1 spec,](https://www.w3.org/TR/wai-aria-1.1/#listbox) then each choice needs role="option". I'm seeing in the wild tons of these carousels without role="option" on the choices.

Personally, I think its a stretch to present it to assisitive technologies as such, and I would simply remove role="listbox".

**Comment by XhmikosR** [comment]
Ping @patrickhlauke

**Comment by XhmikosR** [comment]
Ping @patrickhlauke

**Comment by mdo** [comment]
Fixed back in #22405
