### ISSUE TITLE
I have a  problem about Media queries

### ISSUE THREAD

**Issue by chinabin1993** [twbs/bootstrap#26703]
use media queries
when the content is differ in div
          
               ` <div class="row media">

                <div class="col-md-4">aaaaa</div>

                <div class="col-md-4">
                    bbbbbbbbbbbbbbbbbbbbbbbbb
                    bbbbbbbbbbbbbbbbbbbbbbbb
                    bbbbbbbbbbbbbbbbbbbbbbb
                    bbbbbbbbbbbbbbbbbbbbbbb
                    bbbbbbbbbbbbbbbbbbbbbbbb
                </div>

                <div class="col-md-4">cccccccccccccccccccccccccc</div>

            </div>`
**How to make highly adaptive?**
![image](https://user-images.githubusercontent.com/25213840/41267543-68d80ec0-6e2e-11e8-86e4-9dcfdc08c511.png)

i used "flex" or setting margin and padding unable to achieve demand ---- div have "border-bottom"

**Comment by patrickhlauke** [comment]
This isn't the right place for help/how to questions. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
