### ISSUE TITLE
Feature request: Close Tooltip when clicking outside of it (useful when high hide delay set)

### ISSUE THREAD

**Issue by juanmaguitar** [twbs/bootstrap#26719]
### Issue description

- components: `Tooltip`
- bootstrap version `4.1.1`

### What is happening?

If the Tooltip is set with some delay on hide, clicking outside doesn't close it
https://codepen.io/TheSharpieOne/pen/pKpzBj

### What should be happening?

Clicking outside the tooltip should close it

**Comment by nikhilbarar** [comment]
Can i pick this?

**Comment by Fak3** [comment]
This feature is already implemented in popper.js version 1.14.7: https://github.com/FezVrasta/popper.js/pull/661
Can the support for it be added to bootstrap?

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
