### ISSUE TITLE
Dropdown items with tooltips don't disappear immediately when scrolling 

### ISSUE THREAD

**Issue by ClemMakesApps** [twbs/bootstrap#26712]
![2018-06-14 15 37 25](https://user-images.githubusercontent.com/3363898/41436946-df9f4cd8-6fe8-11e8-9d32-406798c2cc56.gif)

Is this a bug or is it intentional? I've set the boundary to `viewport` because I need the tooltip displayed outside of the dropdown but it seems to create this weird bug whenever scrolling occurs.

Codepen for testing: https://codepen.io/clemmakesapps/pen/WyEYBz

**Comment by Johann-S** [comment]
How did you set the `boundary` to `viewport` in your example ?

**Comment by ClemMakesApps** [comment]
@Johann-S I used data attributes

```
<button ... data-boundary="viewport">dropdown item</button>
```

**Comment by Pritraj** [comment]
Facing the same issue...

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
