### ISSUE TITLE
New <audio> component feature

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26715]
Hi, I'm not sure whether this would be absolutely necessary, but since we're all consuming content on the web nowadays, I wondered whether it would be useful to implement some kind of `<audio>` component into Bootstrap which would add some **basic** layout styling to the default `<audio>` component.

The `<audio>` component by default has different styling based on the browser, but, one thing across all browsers seems to be the width being statically set, and whilst adding the `.w-100` class to the `<audio>` element likely would make it full width, I was thinking of building something a little more relevant which could easily be expanded on and provide a base for building an audio component.

As an example, I've put together a super simple code pen example which demonstrates what we could do, view it here: https://codepen.io/sts-ryan-holton/pen/XYevgL

I thought that it's unlikely that anyone else has thought of a feature so far related to this, and it's something Bootstrap doesn't directly have built in.

Thoughts?

**Comment by MartijnCuppens** [comment]
Hmm, I think `.w-100` fully covers this functionality.

**Comment by XhmikosR** [comment]
Agreed with @MartijnCuppens .
