### ISSUE TITLE
Problem using navbar fixed-top

### ISSUE THREAD

**Issue by golnoschekovma** [twbs/bootstrap#26726]
If my template has a <header class = "navbar fixed-top"> structure, then the subsequent <div> is hidden behind it. In order to <div> align <header>, I need to specify <div style = "margin-top: 6rem">? Or is there a more universal solution? 
For example, if I use the solution suggested by me, then when I increase any element related to <header>, I should also change the margin-top from 6rem to large. 
How right?

**Comment by mdo** [comment]
Our docs covers this: https://getbootstrap.com/docs/4.1/components/navbar/#placement.
