### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by rohan-koli** [twbs/bootstrap#26720]
https://github.com/twbs/bootstrap.git", exit code of #128 fatal: unable to access 'https://github.com/twbs/bootstrap.git/': transfer closed with outstanding read data remaining
10:51:04 
10:51:04 Additional error details:
10:51:04 fatal: unable to access 'https://github.com/twbs/bootstrap.git/': transfer closed with outstanding read data remaining
10:51:04 Build step 'Execute shell' marked build as failure

**Comment by radutopala** [comment]
Same here:
```
git clone git@github.com:twbs/bootstrap.git
Cloning into 'bootstrap'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rohan-koli** [comment]
yes

**Comment by rohan-koli** [comment]
Its working now

**Comment by Johann-S** [comment]
Don't think it's related to Bootstrap, it's related to your network or Github

**Comment by radutopala** [comment]
Apparently it was a Github's infrastructure problem, they resolved after I've sent an email to support. There was no status update at https://status.github.com/messages..

**Comment by nikasioMel** [comment]
Still happens, apparently is a problem with this repo when trying to execute: 

`git ls-remote --tags https://github.com/twbs/bootstrap.git`

**Comment by lucasmarques-DINNI** [comment]
It's happening to me as well, when running my project's `bower install`:
`ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/twbs/bootstrap.git", exit code of #128 fatal: unable to access 'https://github.com/twbs/bootstrap.git/': transfer closed with outstanding read data remaining`

**Comment by lmcuong25** [comment]
It's happening: 

bower bootstrap#~3                      ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/twbs/bootstrap.git", exit code of #128 fatal: unable to access 'https://github.com/twbs/bootstrap.git/': GnuTLS recv error (-54): Error in the pull function.
 Additional error details:
 fatal: unable to access 'https://github.com/twbs/bootstrap.git/': GnuTLS recv error (-54): Error in the pull function.
