### ISSUE TITLE
Split JavaScript / jQuery plugins into external npm package

### ISSUE THREAD

**Issue by felixfbecker** [twbs/bootstrap#26724]
Currently, the `bootstrap` package contains the JavaScript and jQuery plugins, and peerDependencies on `jquery` and `popper`. However, a lot of projects nowadays don't use jQuery anymore, but purely the CSS/SCSS and/or external interactive modules that integrate into e.g. React or Angular. Every consumer who falls into that category will get this warning printed every time they run `npm install`:

```
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
```

This warning can be ignored, since the JS is not used.
In a team of a certain size these kind of warnings however confuse people, or they train themselves to ignore these kind of warnings in general - which is dangerous because some unmet peerDependencies warnings can point to real issues and version incompatibilities.

I think the right solution would be to stop shipping the jQuery plugins in the core `bootstrap` package, but split them into an external package like `boostrap-jquery-plugins`.

**Comment by MartijnCuppens** [comment]
If I'm not mistaken, this is planned for v4.3 (see https://github.com/twbs/bootstrap/projects/9)

**Comment by Johann-S** [comment]
Please search a bit before opening an issue there is already one see: https://github.com/twbs/bootstrap/issues/23557
