### ISSUE TITLE
Shadow bleeds to bottom with card-columns

### ISSUE THREAD

**Issue by shkm** [twbs/bootstrap#26733]
Fine in Firefox, bugs on Safari and Chrome. IE untested.

See bottom-left of the example:

https://jsbin.com/hofolilura/edit?html,css,output

**Comment by mdo** [comment]
What are you trying to accomplish with this? Your custom shadow is interfering with the default border styles on the card component.

**Comment by mdo** [comment]
Closing due to lack of response.
