### ISSUE TITLE
Text Should Be Responsive Out Of The Box (like Bootstrap 3)

### ISSUE THREAD

**Issue by KeplerIO** [twbs/bootstrap#26731]
In Bootstrap 3, I'm fairly certain that if you created  new HTML page, put in the references to Bootstrap, then made a `<p>` tag, text would break and resize and otherwise be responsive. 

In Bootstrap 4, on a brand new HTML page, I implement Bootstrap and a `<p>` tag full of text and begin resizing the screen to see if I've set it up correctly, but text is unresponsive. Jumbotron works.

BS4 should have responsive text out of the box like it's older brother.

**Comment by diegocam** [comment]
i think it depends wether or not your `<p>` tags reside inside an element with `.container` or `.row`

**Comment by KeplerIO** [comment]
@diegocam I've tried with the `<p>` by itself, in a row, and inside a column inside a row.

**Comment by diegocam** [comment]
Maybe present us with a sample on CodePen or Fiddle? im not sure what you mean.

**Comment by KeplerIO** [comment]
@diegocam I have made a very stupid mistake that I hope you will forgive me on..

Turns out, the text must have spaces and breaks..... 

Entering gibberish strings such as "sadf;ljkasdf" into the `<p>` tag will cause the entire string to read from left to right, right off the page. Adding spaces to the string resolves this.. 

I do apologies for wasting your time.. please do close this issue and I hope no one ever sees it..
