### ISSUE TITLE
Incorrect documentation in visibility util about screen reader

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#26734]
https://getbootstrap.com/docs/4.1/utilities/visibility/

> Set the visibility of elements with our visibility utilities. These do not modify the display value at all and are helpful for hiding content from most users, **but still keeping them for screen readers.**

The last description is correct? The [visibility - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#Accessibility_concerns) describe:

> Using a visibility value of hidden on an element will remove it from the accessibility tree. This will cause the element and all its descendant elements to no longer be announced by screen reading technology.

**Comment by patrickhlauke** [comment]
@ysds you're absolutely correct. it seems somewhere moving from 3.x to 4.x this error crept in. the docs for 3.x state, correctly, that content is "hidden (including for screen readers)" https://getbootstrap.com/docs/3.3/css/#helper-classes-show-hide

Filed a PR #26786
