### ISSUE TITLE
Position Utility class need responsive breakpoints

### ISSUE THREAD

**Issue by aneeskodappana** [twbs/bootstrap#26736]
In the docs https://getbootstrap.com/docs/4.0/utilities/position/ it's mentioned that Quick positioning classes are available, though they are not responsive. Why is like that. it's a handy utility class and it's more convenient if there are responsive utilities too.

**Comment by mdo** [comment]
There are many utilities that do not include responsive variations. There's not a high demand for all of these, so we kept them out until we heard more from the community on them as they add a significant amount of weight to the compiled CSS. For now, going to leave as-is though.

**Comment by phivk** [comment]
I'd very much appreciate the ability to use the position utility classes responsively.
As mentioned [here](https://github.com/twbs/bootstrap/issues/28350) the class names could be kept consistent with the `p-[breakpoint]-[value]` pattern used for the [Display utility](https://getbootstrap.com/docs/4.3/utilities/display/).

**Comment by p-groarke** [comment]
+1
For the time being, you can find them here : https://stackoverflow.com/questions/62675880/bootstrap-4-applying-responsiveness-to-position-on-elements-depending-on-device
