### ISSUE TITLE
Why don't the components use the css-color-variables?

### ISSUE THREAD

**Issue by reFX-Mike** [twbs/bootstrap#26748]
Why don't you even let me reply instead of putting words in my mouth and then closing the issue? Why so rude?

Wouldn't it be possible to set a fallback first, then override it with a variable, and if the browser doesn't support the variable, the previous fallback would still work?

```
color: red;
color: var(--primary-color);
```

I looked it up, and it works fine.

**Comment by mdo** [comment]
Hey there, no offense was meant on the team's part. You asked a question in #26747 and Patrick responded saying we cannot go that route given IE11. We support IE10 and up. Come v5 we can talk about dropping more browsers given that's a change in backward compatibility.

> Wouldn't it be possible to set a fallback first, then override it with a variable, and if the browser doesn't support the variable, the previous fallback would still work?

Sure we could, but that's doubling up on a _ton_ of variables. We're talking hundreds of `color` and `background-color` declarations for our color variables alone. That's far too much CSS for a setup not many folks have fully embraced yet.

Our CSS is built with Sass, therefore all our customization and docs assume that setup. There are no plans to change that in v4's lifespan.
