### ISSUE TITLE
Why don't the components use the css-color-variables?

### ISSUE THREAD

**Issue by reFX-Mike** [twbs/bootstrap#26747]
Why are the colors hard-coded into the CSS? I know that I can use the SASS files and compile my own, but wouldn't it make much more sense to use the css-variables that exist, so they can be overridden by the user (themes etc.)?

**Comment by patrickhlauke** [comment]
not if we're currently maintaining compatibility with IE11, no

**Comment by reFX-Mike** [comment]
Does anybody who uses Bootstrap care about IE? According to caniuse.com, its global market-share is 2.71%

Whoever uses any version of IE, apparently doesn't care about latest standards or compatibility.

**Comment by patrickhlauke** [comment]
yes, some people who use Bootstrap do.

and no, it's not always the users who have a choice - it's often organizations that lock down browsers. and regardless, even if the users themselves didn't care about the latest standards, that not a good enough reason to then just serve them no colors at all.

**Comment by reFX-Mike** [comment]
Why don't you even let me reply instead o putting words in my mouth and then closing the issue? Why so rude?

Wouldn't it be possible to set a default first, then override it with a variable, and if the browser doesn't support the variable, the previous default would still work?

```
color: red;
color: var(--primary-color);
```
