### ISSUE TITLE
Support checkbox that can be only deselected (.disable rule additionally to :disable) - to provide selected disabled option behavior

### ISSUE THREAD

**Issue by rpokrovskij** [twbs/bootstrap#26750]
HTML allows `select multiple` option be selected and disabled at the same time.
This means it can be deselected but not selected back.

Semantically this means: this option was allowed in past, but now it is disabled, change it.

Realization aspect: its color is as with `disabled`, and background is as with `selected`

https://codepen.io/rpokrovskij/pen/wXXqpV

I am not asking to provide special component, just add `.disable` class to your `:disable`

This means
```
.custom-control-input.disabled ~ .custom-control-label {
    color: $custom-control-label-disabled-color; }
```

to your 

```
.custom-control-input:disabled ~ .custom-control-label {
    color: $custom-control-label-disabled-color; }
```

Why not "keep calm and create your classes"? I'm developing custom plugin and it would be nice if it will be working with all bootstrap themes.

Thank you for your work. Sorry if I ask you something that is out of scope.

**Comment by mdo** [comment]
No plans to add another class to these selectors—we'll stick to the `disabled` attribute.

**Comment by rpokrovskij** [comment]
But did you get why I need it? because if didn't - give me another chance to explain. It you understand - and still do not want to change anything - I'm accept it.
