### ISSUE TITLE
Flex responsive utilities not working

### ISSUE THREAD

**Issue by lvar** [twbs/bootstrap#26758]
I have this part of code

```html
<div id="contenedor" class="container d-flex d-sm-flex flex-sm-column justify-content-between justify-content-sm-center align-items-sm-center">

            <div>
              <i class="far fa-envelope fa-3x"></i>
            </div>
            <div >
              <h4>¿Tienes alguna pregunta?</h4>
              <p>algo</p>
            </div>

            <div>
              <i class="fas fa-phone fa-3x"></i>
            </div>
            <div>
              <h4>Llámanos</h4>
              <p>algo</p>
            </div>

            <div>
              <i class="fab fa-facebook fa-3x"></i>
            </div>
            <div>
              <h4>Escríbenos en facebook</h4>
              <p>algo</p>
            </div>

          </div>
```

And all the classes with sm , are not working when I try to visualice them on firefox responsive view (specific samsung galaxy s5 view ) ...Is there a minimal measure for flex-sm class ? more than certain number of pixels ? ...because on bootstrap documentation I can't see a  "xs" value for flexbox....only sm , md , and lg.

https://getbootstrap.com/docs/4.1/utilities/flex/

**Comment by nteetor** [comment]
I think you may want to swap your `-sm-`. Use `justify-content-center` to center on all screens, including extra small. Then use `justify-content-sm-between` to change the layout for small, medium, and larger screens, leaving extra small as is.

Going forward you're best off asking a question over at https://stackoverflow.com/.

**Comment by lvar** [comment]
@nteetor But I want on sm screen turn the flex direction from row to column...thats why I tried with flex-sm-column ...Maybe I'm a little confused...

**Comment by mdo** [comment]
These utilities will accomplish what you wish, but you likely need to review the docs a bit more to see exactly what you need. Few quick notes:

- `d-flex` is our "xs"` option—it applies from `min-width: 0` and above.
- `d-sm-flex` here is unnecessary as you've already added `d-flex`. You'd only need `d-sm-flex` if you wanted a different `display` up until the `sm` breakpoint.
- If you want these columns on phone sized devices, nix the `sm` infixes.
