### ISSUE TITLE
Collapse Issue

### ISSUE THREAD

**Issue by IndhuVelayutham** [twbs/bootstrap#26755]
(function(){
  var searchTerm, panelContainerId;
  // Create a new contains that is case insensitive
  $.expr[':'].containsCaseInsensitive = function (n, i, m) {
    return jQuery(n).text().toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
  };
  
  $('#accordion_search_bar').on('change keyup paste click', function () {
    searchTerm = $(this).val();
    $('#accordion > .panel').each(function () {
      panelContainerId = '#' + $(this).attr('id');
      $(panelContainerId + ':not(:containsCaseInsensitive(' + searchTerm + '))').hide();
      $(panelContainerId + ':containsCaseInsensitive(' + searchTerm + ')').collapse (searchTerm);
    });
  });

This is my jQuery file, I have filtered my search and able to display. But it is displayed in collapse form, i want to expand and show the particular result.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

_This is a saved reply._

---

On top of that, this looks like it's JS for v3. We're not maintaining that right now.
