### ISSUE TITLE
Feature: Please include a components much like Foundation's abide

### ISSUE THREAD

**Issue by bauereileen01** [twbs/bootstrap#26751]
Abide is an HTML5 form validation library that supports the native API by using patterns and required attributes. 
To enable validation with Abide, add the data-abide attribute to your form element. Then add the required attribute to each input that you want to require. Additionally, you can define a pattern to define restraints on what users can input.

Name | Valid Example or Format
-- | --
alpha | Foundation
alpha_numeric | A1Sauce
integer | -1
number | 2937
card | visa, amex, mastercard
cvv | 384 or 3284
email | foundation@zurb.com
url | http://zurb.com
domain | zurb.com
datetime | YYYY-MM-DDThh:mm:ssTZD
date | YYYY-MM-DD
time | HH:MM:SS
dateISO | not sure yet
month_day_year | MM/DD/YYYY
color | #FFF or #FFFFFF

**Comment by sts-ryan-holton** [comment]
@bauereileen01 Would be a great feature! However, can you utilise any of the current form validation? https://getbootstrap.com/docs/4.1/components/forms/#validation

**Comment by bauereileen01** [comment]
Eh, I think the very beginning is there, but I'll have to code alot more to provide the validation my app needs.

**Comment by mdo** [comment]
We default to the browser native form fields already, and much of these validations you'd want come free with the `<input>`'s `type` attribute. We could connect the dots for folks, but I don't see the value in it overall right now.
