### ISSUE TITLE
Feature: Please include a components much like Googles Material Design's Spinners

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/bootstrap#26753]
Feature: Please include a components much like Googles Material Design's Spinners

![snackbars-container-do](https://user-images.githubusercontent.com/20210961/41822616-0ba2d874-780c-11e8-95bc-38fe7f2ff7e3.png)

https://material.io/design/components/snackbars.html#

**Comment by wolfy1339** [comment]
This is already in the works, see #22960

**Comment by mdo** [comment]
Closing since this is tracked in the feature PR.
