### ISSUE TITLE
Modal modal-dialog-centered dont close

### ISSUE THREAD

**Issue by reunix** [twbs/bootstrap#26763]
Hi, using the modal-dialog-centered class I can not close using the default buttons

`<div class="modal-dialog-centered">`

I already researched a lot but I can not find a solution.

tks!

**Comment by reunix** [comment]
Em Português....
Estou usando a classe modal-dialog-centered para meus modais , porém tem um bug que os botões de fechar não funcionam, nem o X nem o botão do dodapé!! alguém já passou por isso!, baixei uma versão 4.1 no github mas o bug continua!!
Obg!!!

**Comment by mdo** [comment]
`.modal-dialog-centered` is a modifier class. Read the docs again and see the example code has `.modal-dialog` and `.modal-dialog-centered`. https://getbootstrap.com/docs/4.1/components/modal/#vertically-centered

**Comment by reunix** [comment]
hi,
the purpose of using this class was to open the modal with width 100%
when I use modal-dialog modal-dialog-centered together it returns to the default size, anyway thanks
