### ISSUE TITLE
Too fast nav switching makes multiple contents visible.

### ISSUE THREAD

**Issue by hanguokai** [twbs/bootstrap#26768]
If switch nav too quickly and use `fade` with `tab-pane`, multiple tab-pane content will show.

For easy reproduce this problem, I made a demo https://codepen.io/hanguokai/pen/JZmywb .
It let you use space or any key to switch nav. When switch nav, different content will show different color. If you keep pressing the key, it will switch very fast. Then multiple color will display together when you stop pressing.

This problem produce only with fade class. Without using fade, it is no problem. 

In the actual environment, the nav content is more complicated and often lazy load content by show.bs.tab event listener. In that case, it will happen event manually by clicking quickly to switch nav.

#8117 is a similar issue to this, but for old BS version that fixed.

**Comment by Johann-S** [comment]
With `.fade` class our `show` method is asynchronous, so you should listen to our events before calling `show` to avoid your issue.

See: https://getbootstrap.com/docs/4.0/getting-started/javascript/#asynchronous-functions-and-transitions

**Comment by hanguokai** [comment]
Yes, `.tab(‘show’)` is asynchronous method. But it also said “a method call **on a transitioning component will be ignored**” on the ducument. If it's ignored really, it will has no effect for switching continuously and will not has this problem.

@fat said " it's a limitation of css transitions – the transition end event isn't being fired. fixed with emulateTransitionEvent" at issue 8117.

**Comment by Johann-S** [comment]
Stay closed because related to this issue: #26525
