### ISSUE TITLE
col-min classes

### ISSUE THREAD

**Issue by SuperPat45** [twbs/bootstrap#26764]
What do you think about adding col-*-min classes to keep the minimum "natural" size of a component?
Something like:
```
.col#{$infix}-min {
      @extend %grid-column;
      width: auto;
}
```
and no flex-basis, flex-grow or width at all.

**Comment by razh** [comment]
What would be the difference between this proposal and the `.col-auto` classes?

https://github.com/twbs/bootstrap/blob/e57a2f244ba8446fffe71847e6a58b18f7b2d541/scss/mixins/_grid-framework.scss#L37-L41

**Comment by mdo** [comment]
Indeed, you likely want the auto cols :).

**Comment by SuperPat45** [comment]
The auto class distribute free space to all auto cols due to flex 0 0 auto and it is not what i need.
I need  class that cell do not expand col but keep the padding.
