### ISSUE TITLE
some errors in the latest doc of components_nav

### ISSUE THREAD

**Issue by scutjyj** [twbs/bootstrap#26777]
The error landed on the demo code in the part "Base nav" of this doc.
If we use the demo code, the brower will not show the right display of the **active** nav.
The reason for this is that the "active" html-lable-class-attribute is not in the right place.
To solve it, we should put the "active" attribute on the "\<li\>" lable class attribute instead of that of the "\<a\>" lable.
about this doc: <https://getbootstrap.com/docs/4.1/components/navs/#base-nav>

**Comment by mdo** [comment]
Per the docs' callout above the example, there is no active state for the base nav.
