### ISSUE TITLE
Dropdown doesn't close when an outside select element is clicked

### ISSUE THREAD

**Issue by mburrows02** [twbs/bootstrap#26772]
OS/Browser: Ubuntu 16, Chrome 67

To reproduce:
1. Click dropdown button - dropdown opens
2. Click on a select field elsewhere on the page - dropdown remains open and select field opens (potentially on top of the dropdown as in the example, depending on placement)

The (expected) behaviour observed in Firefox is that the dropdown closes and the select field opens, so this might be a browser bug.

[Example](http://jsbin.com/gikewenaku/edit?output)

**Comment by alecpl** [comment]
Works in Firefox. There's however a different issue. If you click on the select first and then on the button it will not display the dropdown. In both browsers.

**Comment by Johann-S** [comment]
Work in Firefox, and Chrome 67 on Win10 😟 

BTW this link : https://maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.js is outdated see: https://getbootstrap.com/docs/4.1/getting-started/download/#bootstrapcdn

**Comment by mburrows02** [comment]
[Updated to the 4.1 links](http://jsbin.com/yorukohoge/edit?html,output) and still seeing the broken behaviour on chrome/ubuntu. However, I had a colleague check and it works in chrome and safari on OSX.

**Comment by varshasachan** [comment]
Working

**Comment by mdo** [comment]
Closing as stale.
