### ISSUE TITLE
Jumbotron border-radius

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26783]
I've been using the Jumbotron component in Bootstrap 4 (https://getbootstrap.com/docs/4.1/components/jumbotron/) as a full-width banner like section with a background colour/image. The issue I've noticed, is for some reason it comes with `.3rem` of border-radius... just wondering why, and whether this can be removed?

```
.jumbotron {
    padding: 2rem 1rem;
    margin-bottom: 2rem;
    background-color: #e9ecef;
    border-radius: .3rem;
}
```

**Comment by mdo** [comment]
`.jumbotron-fluid` exists to accomplish the full-width banner you're referring to. Regular jumbotron is for use within a fixed-width parent.
