### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by Maaacoooo** [twbs/bootstrap#26789]
I'm sure everyone relates. But goddamn, why does it have to rename the classes? I mean, goddamn it. I have to rewrite almost everything just to apply the **4.1** Update.

**Comment by mdo** [comment]
What classes were renamed from v4.0 to v4.1?

**Comment by mdo** [comment]
@Maaacoooo Let us know if there's something we can help with here. Minor releases add new features, but shouldn't introduce breaking changes from the v4.0 stable release.
