### ISSUE TITLE
Clicking on the checkbox white square does not toggle checkbox

### ISSUE THREAD

**Issue by ckashby** [twbs/bootstrap#26782]
Click on the white square of the checkbox buttons and they do not change state.

div class="btn-group mb-3" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="checkbox" checked autocomplete="off"> Checkbox 1 (pre-checked)
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off"> Checkbox 2
  </label>
  <label class="btn btn-primary disabled">
    <input type="checkbox" autocomplete="off"> Checkbox 3
  </label>
</div>

**Comment by ckashby** [comment]
<pre>
div class="btn-group mb-3" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="checkbox" checked autocomplete="off"> Checkbox 1 (pre-checked)
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off"> Checkbox 2
  </label>
  <label class="btn btn-primary disabled">
    <input type="checkbox" autocomplete="off"> Checkbox 3
  </label>
</div>
</pre>

**Comment by ckashby** [comment]
<code>
div class="btn-group mb-3" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="checkbox" checked autocomplete="off"> Checkbox 1 (pre-checked)
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off"> Checkbox 2
  </label>
  <label class="btn btn-primary disabled">
    <input type="checkbox" autocomplete="off"> Checkbox 3
  </label>
</div>
</code>

**Comment by ckashby** [comment]
`div class="btn-group mb-3" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="checkbox" checked autocomplete="off"> Checkbox 1 (pre-checked)
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off"> Checkbox 2
  </label>
  <label class="btn btn-primary disabled">
    <input type="checkbox" autocomplete="off"> Checkbox 3
  </label>
</div>`

**Comment by ckashby** [comment]
This is also true for radio buttons.

Click on the white circle and they do not toggle.

**Comment by ckashby** [comment]
This is also true for radio buttons.  Click on white circle. Button is not selected.

**Comment by patrickhlauke** [comment]
please show an actual live (jsfiddle or similar) reduced test case

**Comment by ckashby** [comment]
Here is a gist with instructions and markup.

https://gist.github.com/ckashby/f8f6ca3690ced0346ae636d3f3bfb9fd

Just load in Chrome and click on the white squares on the button

Cheers

**Comment by webframing** [comment]
@patrickhlauke Here is the live demo for the issue:
[https://codepen.io/anon/pen/wXRLNK?editors=1000](https://codepen.io/anon/pen/wXRLNK?editors=1000)

**Comment by patrickhlauke** [comment]
button group is currently only set up to work with actual `<button>` elements. see http://getbootstrap.com/docs/4.1/components/button-group/#basic-example
