### ISSUE TITLE
Collapse button jumps to the top of page

### ISSUE THREAD

**Issue by shaal** [twbs/bootstrap#26792]
(The bug seems to exist only on iPhone with safari browser and chrome browser)

This issue happens when there's a long text above the collapse button and a long text that is hidden and being expanded.
Clicking on the collapse button to close the expanded text - jumps to the top of the page, instead of staying in the same position of the page.

Steps to repeat -

1. On an iPhone device, scroll down until you can see the button to collapse.
2. Click on the button once to expand the text.
3. **_(The page will jump to the top, instead of staying in the same position)_**
4. Scroll down until the button is on top of the view.
5. Click on the button again to collapse the text.
6. **_(The page will jump to the top, instead of staying in the same position)_**

https://codepen.io/shaal-the-reactor/full/ERMWJG/

**Comment by mdo** [comment]
Upgrading to latest releases seems to fix this for me.
