### ISSUE TITLE
Saas Variables

### ISSUE THREAD

**Issue by boozeahead** [twbs/bootstrap#26795]
### Case 1

```scss
@import"../../node_modules/bootstrap/scss/functions";
@import"../../node_modules/bootstrap/scss/bootstrap";

//Colors
$theme-colors: (
  "primary": #2699FB,
  "danger": #ff4136,
);

$h1-font-size:				$font-size-base * 3;
);
```

### Case 2

```scss
@import"../../node_modules/bootstrap/scss/functions";

$theme-colors: (
  "primary": #2699FB,
  "danger": #ff4136,
);

@import"../../node_modules/bootstrap/scss/bootstrap";
$h1-font-size:				$font-size-base * 3;
```

Above is my case scenario, I would like to use my own variables which can be done by "Case 2" but it doesnot allow me to use bootstrap variables '$font-size-base'.

But if I use the 'Case 1' bootstrap variable is working and I can edit and customize but my variable primary is not working.

Is anyone knows where I am wrong?

**Comment by mdo** [comment]
You're including `bootstrap` which already includes `functions`, and also includes `variables`. Re-read the Theming docs and take a look at [Option B under Importing](https://getbootstrap.com/docs/4.1/getting-started/theming/#importing) and our [variable defaults](https://getbootstrap.com/docs/4.1/getting-started/theming/#variable-defaults).

**Comment by boozeahead** [comment]
`@import"../../node_modules/bootstrap/scss/bootstrap";

//Colors
$theme-colors: (
  "primary": #2699FB,
  "danger": #ff4136,
);
$h1-font-size:	$font-size-base * 1;

// Bootstrap and its default variables
@import"../../node_modules/bootstrap/scss/bootstrap";
`
Thanks Mark, but the task i accomplished is importing `@import....bootstrap` twice. My concern is "Is this the right way to do it". If I do not import bootstrap.scss on top, it will give you a Error saying Undefined Variable "$font-size-base". :(

**Comment by mdo** [comment]
Open up `bootstrap.scss` and see what's included there. Only included what you need.

For this, you need three files:

```scss
@import "functions";
@import "variables";
@import "mixins";
```
