### ISSUE TITLE
Issues with Bootstarp4

### ISSUE THREAD

**Issue by ssandhyap** [twbs/bootstrap#26793]
Iam in process of upgrading bootstrap version from 3.3.6 to 4.0.0 for existing applications,

After upgrading tooltips,dropdowns and date-picker are not working........

Can somebody please me to resolve my issues?????

**Comment by patrickhlauke** [comment]
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
