### ISSUE TITLE
[Bug] Sticky column in table

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#26797]
I've noticed one bug with `table` class.
Here is reproduction: https://stackblitz.com/edit/bootstrap-table-sticky-position?file=style.css

When You scroll table right border is moving as well (in chrome and opera).

It's because `table` has `border-collapse: collapse` style.
When You switch it to `border-collapse: separate; border-spacing:0` all is working as it should.

But it can have other implications.

**Comment by bkdotcom** [comment]
It's a browser bug
https://bugs.chromium.org/p/chromium/issues/detail?id=712847

**Comment by piernik** [comment]
Very well - so You can close it.
