### ISSUE TITLE
Tooltip viewport example

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#26809]
The _Tooltip Viewport Example_ page exists, but there is no reference to it in the docs. Also it doesn't seem to work, the tooltips in `.container-viewport` aren't shifted.

http://getbootstrap.com/docs/4.1/examples/tooltip-viewport/

![image](https://user-images.githubusercontent.com/11559216/42346527-4553c41c-80a3-11e8-844f-be4b3e445a41.png)

**Comment by XhmikosR** [comment]
@mdo: do you remember why this page wasn't included? Probably because it didn't work right but if we are not going to use it we should remove it (perhaps redirect it too if possible to the examples index page)

**Comment by Johann-S** [comment]
The `viewport` option do not exist in v4 but exist in v3 see:

- https://getbootstrap.com/docs/4.1/components/tooltips/#options
- https://getbootstrap.com/docs/3.3/javascript/#tooltips-options

So for me we can remove this page

**Comment by XhmikosR** [comment]
OK, let me check if can redirect it.
