### ISSUE TITLE
Problem with Modal events.

### ISSUE THREAD

**Issue by AlvaroStockle** [twbs/bootstrap#26817]
Hi, I want to report this problem I had with the events with modals and how I manage to fix it.

In the documentation, the events displayed are:

$('#myModal').on('hidden.bs.modal', function (e) {
  // do something...
})

, which worked perfectly fine unless I used an XMLHttpRequest triggered by intervals. When 'show.bs.modal' I showed a console.log, and when 'hide.bs.modal' I triggered another. When the interval triggered the Ajax function I needed, the events didn't reacted anymore.

 The solution I found was to detect the event using JDOM the following way:

$(document).on('hidden.bs.modal', '#myModal', function(e) {
  // do something...
})

Could it be a good option to suggest this way in the documentation?

Thank you in advance.

P.S.: Excuse my if my technical lenguage is not correct, for english is not my native lenguage.

**Comment by Johann-S** [comment]
Hi @AlvaroStockle,

Thank you for your feedback 👍 

Your use case is a particular one and it's related to your application and how you use jQuery, most of the time we do not have to use events delegation so there is no benefits to add your use case in our documentation.

**Comment by DLLluoluo** [comment]
$scope.exportLicense = function () {
            if(typeof ($scope.licenseData.selected) == 'undefined' && $scope.licenseData.selected == null) {
                return false;
            }
            $('#progress').modal('show');
            var params =  $scope.licenseData.selected;

            cfgLicenseMgmtService.exportBy(params)
                .then(function (dataObject) {
                    $('#progress').modal('hide');
                    var data = dataObject["data"];
                    if(0 == data['return']) {
                        $scope.licenseData.exportFileName = data.FileName;
                        commonService.downloadFile('/download/'+data['FileName'], data['FileName']);
                    } else {
                        commonService.popUpErrBox($translate.instant('xccErrMsg_LICENSED_export'));
                    }
                },function (data) {
                    commonService.popUpErrBox($translate.instant('xccErrMsg_LICENSED_export'));
                });
        };

The above method is an operation to export the license. When the user clicks the export button, a "#progress" modal box will pop up. After the background data is returned correctly, the "#progress" modal box will be hidden. This code works fine in bootstrap 3.4.1, but the #progress "modal box is not hidden in bootstrap 4.4.1, and $ ('# progress'). Modal ('hide') seems to be invalid. This caused the problem What is the reason and is there a solution?
