### ISSUE TITLE
Netbeans showing error in bootstrap.css file.

### ISSUE THREAD

**Issue by JacobMahto** [twbs/bootstrap#26819]
I am using bootstrap 4 in Netbeans 8.2 ;Netbeans shows error in bootstrap.css
![image](https://user-images.githubusercontent.com/34985809/42413833-71d3aa26-8246-11e8-9777-a8c204c9f1e8.png)
The error is : **Unexpected token SEMI found**
What is it ? How to resolve it?

**Comment by bkdotcom** [comment]
https://netbeans.org/bugzilla/show_bug.cgi?id=262769

**Comment by mdo** [comment]
Closing per latest comment.
