### ISSUE TITLE
Why  don't you develop RTL version of Bootstrap?

### ISSUE THREAD

**Issue by hrahimi270** [twbs/bootstrap#26818]
Hi there, I'm Hossein from Iran.
Why don't you develop **RTL** version of **Bootstrap**?
There is **a lot** of websites that use Bootstrap but they make it RTL **theme selfs**.
**When they make it RTL, there will be a lot of problems.**

> If you have problems with Iran, develop it for Arab countries (or any RTL language country) which you have no problem.

Please, release the RTL version of Bootstrap in v4.

Regards.

**Comment by mhhg78** [comment]
Oops. I have this problem too.
Why don't you release the RTL version of Bootstrap?

**Comment by JamesVanWaza** [comment]
@hrahimi270, @mhhg78 

See https://github.com/twbs/bootstrap/issues/19545 

It will probably be released in either 4.1 or 4.2

**Comment by mdo** [comment]
Plenty of past issues on this.
