### ISSUE TITLE
.img-fluid

### ISSUE THREAD

**Issue by win10forever** [twbs/bootstrap#26822]
Здравствуйте!

.img-fluid{max-width:100%;height:auto}

Ничего не смущает Вас?

:)

**Comment by mdo** [comment]
Without a proper bug report or demo, nothing for us to do here.

**Comment by win10forever** [comment]
.img-fluid{max-width:100%;height:auto}
![2018-07-09](https://user-images.githubusercontent.com/40942865/42439885-c3a52d62-836c-11e8-881c-a24e51953c97.png)
.img-fluid{width:100%;height:auto}
![2018-07-09 1](https://user-images.githubusercontent.com/40942865/42439901-d2ab34fa-836c-11e8-89b2-104083e4a91e.png)

**Comment by Ruffio** [comment]
@win10forever I think that you need to write in english in order for anyone to understand you...

**Comment by win10forever** [comment]
https://translate.google.by/?hl=ru

**Comment by sharomet** [comment]
This person simply does not understand what he is talking about.
