### ISSUE TITLE
Display headings lead text are not responsive, opt-in should be [Suggestion]

### ISSUE THREAD

**Issue by ItaloBC** [twbs/bootstrap#26838]
## Problem

Considering that Bootstrap is a mobile first framework, display headings and lead text are not useful on mobile screens out-of-the-box due to its high font sizing.

## Demonstration

Consider using `display-4` and `lead` classes for a text, and a default `md` viewwidth:

![image](https://user-images.githubusercontent.com/26698421/42465645-93c85746-837a-11e8-9ac1-88d8b17a1181.png)

It looks good, but on small screens the text is kept too big. **And we are only using `display-4`**, which is the smallest display class available:

![image](https://user-images.githubusercontent.com/26698421/42465762-ead5c58c-837a-11e8-8a7a-714f2378a812.png)

Imagine using `display-1` here. Total madness! The text remains it's size, and on small screens is prone to overflow, as it barely fits. 

Using `display` classes is pointless unless the developer switches display to other styled text between sizes.

## Solution: add `-responsive` class

Instead of breaking changes, a new class should opt-in the responsiveness of the display and lead text to acceptable percentages (based on the original size) on small screens.

```html
<div class="container">
    <h4 class="display-4 display-responsive">This is a big-text</h4>
    <p class="lead lead-responsive">And this is the lead text</p>
</div>
```

With this, the developer can opt-in to the responsiveness font-size. Considering `md` size (768px) and `xs` smallest width (320px) relativeness to be 41%, the `display-responsive` and `lead-responsive` should decrease the font size by 40%, and a quarter (25%) in `sm`.

With that approach, the font size allow the texts to fit relatively well with such width constraints, without the developer having to take into account text fitting and overflow with other design objects.

I made a demonstration using 40% in `xs` and 20% in `sm`. I'll leave the final numbers decision to the Bootstrap team, as these number are only what I suggest.

![gif](https://user-images.githubusercontent.com/26698421/42466854-2463f46a-837e-11e8-8caa-16d508bddaef.gif)

## Did you code it?

[I made a pull request](https://github.com/twbs/bootstrap/pull/26800) but I don't have any hopes to be accepted considering it breaks some tests. But the main idea is to have a list, each item comprised of the display heading size and font-weights. A function will get the list and output every display class, along with `@media` queries to decrease the font size for each width size.

**Comment by tarkhov** [comment]
Implemented here:

1. https://tarkhov.github.io/postboot/#type-heading-responsive
2. https://tarkhov.github.io/postboot/#font-size-responsive

**Comment by MartijnCuppens** [comment]
Solved by RFS
