### ISSUE TITLE
[Docs] Role "button" in Navbar dropdowns

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#26830]
hi,
in the first example
https://getbootstrap.com/docs/4.1/components/navbar/#supported-content
.dropdown-toggle has a "role="button"
in the second example
https://getbootstrap.com/docs/4.1/components/navbar/#nav
"role=button" is missing

which is the correct version?

**Comment by patrickhlauke** [comment]
@XhmikosR hah...you beat me to the PR :)

**Comment by XhmikosR** [comment]
Yeah, please review that instead :)
