### ISSUE TITLE
Card border offset by 1px

### ISSUE THREAD

**Issue by andrei-gheorghiu** [twbs/bootstrap#26843]
Considering this library's wide audience and its consistent past pixel-perfect-ness, having a `2px` difference in size between `.card-body` and `.card-img-*` should not be acceptable. Possible solutions are to either move the border around the whole card or to resize either the image or the card body so they have same relevant size in each case.

IMHO, having the border all around the image is bad, as some images might not look good with border, so the preferred solution would be to have the image and card body same height/width (depending on layout) and the body to have borders inside that size, on all sides except the joint side towards the image.

    width: calc(100% + 2px);
    margin-left: -1px;

fixes the issue when applied to vertical cards images and a similar fix would probably work for increasing the image height on horizontal cards, but I believe making body `2px` smaller is better and creates fewer problems than making the image `2px` bigger.
___
I'd like to ask if this is currently considered an issue and if a "proper" fix is anywhere in sight.

**Comment by mdo** [comment]
If you don't want the border around the image, remove it from the card and put it on another element. For most folks though, the current solution is acceptable. I'm not after pixel perfection, and most of our components aren't even built with pixels anymore with the move to rems.
