### ISSUE TITLE
.modal('show') not working on stock android browser

### ISSUE THREAD

**Issue by entwwwicklung** [twbs/bootstrap#26841]
Hi all,

Noticed that when I want to open modal manually using **.modal('show')**, it is not opening modal on stock android web browser on some devices that are on android v4.4.2 kit-kat & v5.0 lollipop. It is working with newer devices (and newer versions of android browsers) but on old ones it is not.

Examples:
_LG L70 - Kit-Kat 4.4.2 - Stock Internet Browser version 5.2.30D18_
_Samsung J3 - Lollipop 5.0 - Stock Internet Browser version 3.5.38.162-0_101401_1780611_

Trying to open modal using:

**$( "#testing-modal" ).modal('show');**

Working fine on mobile browsers: Chrome, Firefox, Opera, and newer versions of stock browsers for android, but on above mentioned ones it simply not doing anything.
But when i set data-toggle to modal for button within html code, it is opening modal, so this is an issue with **.modal()** function itself.

Here is code:

http://jsbin.com/kisidak/1/edit?html,js,output

Can you please advise on this one?

Or maybe I am doing something wrong.

**Comment by Johann-S** [comment]
Hi that's what it's written in our documentation, we do not support Android Stock Browser < Android v5.0 see: https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#mobile-devices
