### ISSUE TITLE
Padding right when opening modal

### ISSUE THREAD

**Issue by amlne** [twbs/bootstrap#26845]
When opening a modal, bootstrap 3.3.7 add a padding-right to the HTML body (about 12px), is there any tip to avoid this behavior? the framework is used in an angular 5 application so it's imported from node modules.
the line of code that generate the behavior:
this.bodyIsOverflowing&&this.$body.css("padding-right",a+this.scrollbarWidth).

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by amlne** [comment]
OK, but is there any way to avoid this behavior?
