### ISSUE TITLE
Carousel ignoring borders

### ISSUE THREAD

**Issue by glassputan** [twbs/bootstrap#26858]
I've got a strange issue with Bootstrap 4.  My carousel seems to be ignoring the div borders to which its set in.   The orange border in the attached picture is the div in which the carousel is set.  It's completely ignoring that div.  I've even tried adding the 'img-fluid' class with no success.  Any ideas?

![carousel-overflow](https://user-images.githubusercontent.com/2262812/42584609-94d3d970-8501-11e8-8029-cd601d79c360.png)

```html
<div class="col" style="border: 1px solid orange;">
    <div id="carousel-title" class="carousel slide" data-ride="carousel" data-interval="10000">
        <ol class="carousel-indicators">
            <li data-target="#carousel-title" data-slide-to="0" class="active"></li>
            <s:iterator value="%{#slideShow.images}" status="idx">
                <li data-target="#carousel-title" data-slide-to="<s:property value='%{#idx.index+1}'/>"></li>
            </s:iterator>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class= "carousel-item active">
                <img class="d-block w-100" src="<s:url value='/assets/home.png' />" alt="HSC" />
                <div class="carousel-caption d-none d-md-block">
                    Hulmeville Soccer Club, Hulmeville, PA
                </div>
            </div>
            <s:iterator value="%{#slideShow.images}">
                <div class="carousel-item">
                    <img class="d-block w-100" src="<s:property value="src" />" />
                    <div class="carousel-caption d-none d-md-block">
                        <s:property value="caption" />
                    </div>
                </div>
            </s:iterator>
        </div>
    </div>  
</div>
```

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by glassputan** [comment]
Mark, 

  My apologies.. 

 

Here’s the JS Bin

https://jsbin.com/dixipeb/edit?html,css,output

 

Google Chrome is up to date

Version 67.0.3396.99 (Official Build) (64-bit)

 

Windows 10 Home with the latest patches, etc.

 

Thanks,

Scott

**Comment by MartijnCuppens** [comment]
@glassputan, every `.col` or `.col-...` class adds padding to the left and right, that's why the carousel isn't spread over the full width. 

Also, you can better ask these questions on https://stackoverflow.com/, unless you really found a bug and can scope what's wrong.
