### ISSUE TITLE
Error in  Bootstrap.min.js dialog box not opening after upgrade to bootstrap 4.1. Screen Fades. 

### ISSUE THREAD

**Issue by akashshrimali** [twbs/bootstrap#26851]
![bootstrap min](https://user-images.githubusercontent.com/3968151/42564793-541cb744-851f-11e8-8345-66f723718212.png)
![this element](https://user-images.githubusercontent.com/3968151/42564794-547f4b02-851f-11e8-84c7-a4c313715df0.png)

Dialog box is not opening and is showing following error as per the attachment in the browser console.

Typeof this._element is object

**Comment by akashshrimali** [comment]
![html](https://user-images.githubusercontent.com/3968151/42568446-c8251496-852a-11e8-9851-d26501e72cbd.png)

**Comment by akashshrimali** [comment]
In Bootstrapdialog.js following is written in  comments: 
         * To make multiple opened dialogs look better.
         * 
         * Will be removed in later version, after Bootstrap Modal >= 3.3.0, updating z-index is unnecessary.
         */
 updateZIndex: function () {
            if (this.isOpened()) {
                var zIndexBackdrop = 1040;
                var zIndexModal = 1050;
                var dialogCount = 0;
                $.each(BootstrapDialog.dialogs, function (dialogId, dialogInstance) {
                    if (dialogInstance.isRealized() && dialogInstance.isOpened()) {
                        dialogCount++;
                    }
                });
                var $modal = this.getModal();
                var $backdrop = $modal.data('bs.modal').$backdrop;
                $modal.css('z-index', zIndexModal + (dialogCount - 1) * 20);
                $backdrop.css('z-index', zIndexBackdrop + (dialogCount - 1) * 20);
            }

            return this;
        },
        open: function () {
            !this.isRealized() && this.realize();
            this.getModal().modal('show');
            this.updateZIndex();

            return this;
        }

**Comment by Johann-S** [comment]
Sorry but with that we cannot reproduce your bug, so please could you create a [CodePen](https://codepen.io/) and follow our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md)

**Comment by akashshrimali** [comment]
Please close this issue.
