### ISSUE TITLE
how to override the styles of 'dropdown-menu'?

### ISSUE THREAD

**Issue by MarvinWang** [twbs/bootstrap#26856]
Hi all,

I have a question about Dropdowns. I want to remove the styles of 'dropdown-menu' when the menu is shown. I use the event of 'shown.bs.dropdown' in my js file to override the styles but failed. 

I checked the method 'computeStyle(data , options)' from 'bootstrap.bundle.js', and found the following codes always work finally. So my codes to override the styles are failed.
'data.styles = _extends({}, styles, data.styles);'

how to make my js codes work after this code 'computeStyle(data , options)'?

**Comment by patrickhlauke** [comment]
For how-to type questions, please use stackoverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
