### ISSUE TITLE
Button group dropdown list scroll

### ISSUE THREAD

**Issue by vishuB** [twbs/bootstrap#26850]
[Button group](https://getbootstrap.com/docs/4.0/components/button-group/) dropdown list scroll issue. 

Here issue is when large list of data. at that time auto scroll is not set. 

show below image

![button group dropdown issue-1](https://user-images.githubusercontent.com/13677102/42452710-7c18fd70-83a8-11e8-8ed6-1c3efb740226.gif)

**Comment by mdo** [comment]
This is something we cannot accurately predict and style for everyone. You'll want to add the `overflow` and `max-height` yourself.
