### ISSUE TITLE
Badge padding using em not rem

### ISSUE THREAD

**Issue by howardcox** [twbs/bootstrap#26859]
Hia, I've just noticed that `$badge-padding-y` and `-x` are using `em` not `rem`.

This has made some size maths not work as `rem` and `em` are incompatible.

Is there a reason these are using `em` not `rem`, or is it just an oversight? Happy to PR a patch if so.

**Comment by howardcox** [comment]
Also the following are also using `em`:

- `$badge-pill-padding-x`
- `$caret-width`
- `$mark-padding`

**Comment by mdo** [comment]
`em` units are used so it scales to the parent element's `font-size`.
