### ISSUE TITLE
 Custom checkbox mobile events bug

### ISSUE THREAD

**Issue by rshmiraf** [twbs/bootstrap#26852]
Hi,
Checkboxes works exactly how they should until they are not inside of box which is fixed.

![jul-12-2018 10-49-14](https://user-images.githubusercontent.com/14861637/42622691-47eb53a2-85c1-11e8-942d-fad9053d67c5.gif)

https://jsbin.com/wuvenuyana/ - here is example
To see problem:
1. select one
2. scroll down
3. select second and third one
4. scroll to see results
It doesn't work only on mobile safari. Probably it is browser problem.

Bootstrap: 4.1.2
iOS 11.4.1 with Safari

**Comment by rshmiraf** [comment]
Hope that new gif will be helpful. For now i have to keep using native checkboxes unfortunately.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by rshmiraf** [comment]
Hi @mdo,
Problem is much more complicated than i though. Checkboxes works exactly how they should until they are not inside of box which is fixed. 

https://jsbin.com/wuvenuyana/ - here is example
To see problem:
1. select one
2. scroll down
3. select second and third one
4. scroll to see results

It doesn't work only on mobile safari. Probably it is browser problem not your.

Bootstrap: 4.1.2
iOS 11.4.1 with Safari

**Comment by ysds** [comment]
`-webkit-overflow-scrolling: touch;` is well known to cause bugs.

Try remove your `-webkit-overflow-scrolling: touch;`.

**Comment by rshmiraf** [comment]
@ysds great! Thanks a lot - its working

**Comment by mdo** [comment]
Closing as not a Bootstrap bug.
