### ISSUE TITLE
Nuke service worker

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#26868]
/CC @mdo

**Comment by sts-ryan-holton** [comment]
@XhmikosR  Are we still having issues with this? Caching etc? I'm not sure

**Comment by mdo** [comment]
4.1.2 release should be great, but it's more pain than it's worth it seems. We're going to remove it outright given how we're versioning and deploying docs right now.

**Comment by XhmikosR** [comment]
I don't want to remove it, but it clearly is causing us more issues than I could imagine when we added it. And having a broken site is worse than not having the service worker at this point...
