### ISSUE TITLE
Dropdowns background-color css

### ISSUE THREAD

**Issue by arch-rd** [twbs/bootstrap#26869]
Dropdowns background-color not being applied in Safari mobile. Background is always rendered white regardless of css color.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._
