### ISSUE TITLE
Issue when we fired a modal fully created using JS

### ISSUE THREAD

**Issue by agazzi** [twbs/bootstrap#26865]
Everything is in the title, at this time, i cannot show modal white $('...').modal('show'); when content is injected inside the DOM with pure JS.

**Comment by patrickhlauke** [comment]
Please provide a reduced test case - see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by agazzi** [comment]
Oky, i've double check original source code of my template and i found where's located, the original developer override modal function of jQuery and cause disrtub.

Sorry for loosing your time

Have a nice day

William

**Comment by patrickhlauke** [comment]
:+1:
