### ISSUE TITLE
popper.js mentioned against "sources" in bootstrap.bundle.js.map but actually missing inclusion in bootstrap.bundle.js or bootstrap.bundle.js or bootstrap.bundle.min.js

### ISSUE THREAD

**Issue by singh-arvind** [twbs/bootstrap#26864]
Kindly add popper.js and update bootstrap.bundle.*.js.

**Comment by XhmikosR** [comment]
Is there anything that can be improved on our docs?

**Comment by MarvinWang** [comment]
In my jsp file, it includes the following code section.

`<script src="jquery/js/jquery-3.3.1.min.js"></script>
	<script src="jquery-ui/jquery-ui.min.js"></script>
	<script src="bootstrap-4.1.1/dist/js/bootstrap.bundle.js"></script>
	<script src="bootstrap-4.1.1/dist/js/bootstrap.js"></script>
	<script type="text/javascript" src="js/workbench/t-workbench.js"></script>
`
but when I use `$(this).dropdown()` the js file like the following code section.
`	$('.ttm-footer').find('.ttm-ft-menu-art').on('click','.dropdown-toggle',function(){
		$(this).dropdown();
	});` 
then error in the browser console is 

> TypeError: Bootstrap dropdown require Popper.js (https://popper.js.org).


By the way the version is 4.1.*

How to resolve my issue?

**Comment by Johann-S** [comment]
@MarvinWang you have to include `bootstrap.min.js` or `bootstrap.bundle.min.js` not both
