### ISSUE TITLE
Update docs for Webpack 4?

### ISSUE THREAD

**Issue by bcardarella** [twbs/bootstrap#26875]
The current docs callout Webpack 3 specifically. Is there anything different required in installation for webpack 4?

**Comment by Johann-S** [comment]
Nope, it works the same in Webpack 4, but we should update our docs thanks 👍

**Comment by mac9416** [comment]
Looks like the way Bootstrap handles modules has been changed and should be reflected instead of the docs.

There's no longer any need to use exports-loader to load modules individually.

https://github.com/twbs/bootstrap/commit/eb81c39f2c36d88d4ebc062a2fa179980827e8be

**Comment by Johann-S** [comment]
We already removed the part about `exports-loader` @mac9416 see: https://getbootstrap.com/docs/4.1/getting-started/webpack/#importing-javascript

**Comment by XhmikosR** [comment]
@Johann-S: is this still valid?

**Comment by Johann-S** [comment]
Yep, I think at least we shouldn't specify a Webpack version, because we don't use custom things, it's a basic usage of Webpack

**Comment by XhmikosR** [comment]
All right, I will make a PR to remove the version reference.
