### ISSUE TITLE
Collapse causes Problems after update to 4.1.2 (previously 4.1.2)

### ISSUE THREAD

**Issue by BernhardBehrendt** [twbs/bootstrap#26874]
Made an upgrade to 4.1.2 which results in an error concerning collapsing accordions.

<img width="617" alt="bildschirmfoto 2018-07-13 um 09 04 00" src="https://user-images.githubusercontent.com/1717382/42677720-e67a390a-867c-11e8-9548-2917808400f7.png">

After I made a downgrade it was fully functional again.

Will dig deeper into it and update this issue once I got more information.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by BernhardBehrendt** [comment]
It was my fault but interesting behavior...
Had wrong ID namings (button<> accordion root element) but interesting part I want to share is that it's working with 4.1.0.

<img width="1678" alt="bildschirmfoto 2018-07-13 um 10 57 30" src="https://user-images.githubusercontent.com/1717382/42683000-5eb6201e-868c-11e8-9923-aa551c7717b2.png">

**Comment by Johann-S** [comment]
yep that's because now we query our elements in Vanilla JS to optimise our performances, in 4.1.0 we queried our elements thanks to jQuery

**Comment by BernhardBehrendt** [comment]
Thanks for the insight  👍

**Comment by jeffreytbush** [comment]
You just saved me potentially hours of work.  Just what I needed, thanks for posting that!!
