### ISSUE TITLE
Dropdowns additional Popper.js 'padding' option

### ISSUE THREAD

**Issue by anthony0579** [twbs/bootstrap#26873]
Popper.js by default adds a padding of 5px between its boundary and popper in it's preventOverflow modifier. Would be nice to have the ability to have this as an Option for dropdowns.

**Comment by Johann-S** [comment]
You always can access to that thanks to `Popper` global var

**Comment by anthony0579** [comment]
I didn't realise I could access that thanks Johann, I know this is not the place for it but could you give me a quick example of how I would set the padding to zero using the global var please?

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
