### ISSUE TITLE
Unknown browser query `dead`

### ISSUE THREAD

**Issue by lschnetler** [twbs/bootstrap#26876]
When building with the latest version we came across this issue with the --prod --aot flags:

```
ERROR in ./node_modules/bootstrap/scss/bootstrap.scss[39m[22m[0m
[0m[1m[31mModule build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `dead`[39m[22m[0m
[0m[1m[31m    at /home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/browserslist/index.js:164:11[39m[22m[0m
[0m[1m[31m    at Array.reduce (<anonymous>)[39m[22m[0m
[0m[1m[31m    at resolve (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/browserslist/index.js:132:18)[39m[22m[0m
[0m[1m[31m    at browserslist (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/browserslist/index.js:224:16)[39m[22m[0m
[0m[1m[31m    at Browsers.parse (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/autoprefixer/lib/browsers.js:61:16)[39m[22m[0m
[0m[1m[31m    at new Browsers (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/autoprefixer/lib/browsers.js:52:30)[39m[22m[0m
[0m[1m[31m    at loadPrefixes (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/autoprefixer/lib/autoprefixer.js:70:24)[39m[22m[0m
[0m[1m[31m    at plugin (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/autoprefixer/lib/autoprefixer.js:81:24)[39m[22m[0m
[0m[1m[31m    at LazyResult.run (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/postcss/lib/lazy-result.js:277:20)[39m[22m[0m
[0m[1m[31m    at LazyResult.asyncTick (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/postcss/lib/lazy-result.js:192:32)[39m[22m[0m
[0m[1m[31m    at /home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/postcss/lib/lazy-result.js:197:27[39m[22m[0m
[0m[1m[31m    at <anonymous>[39m[22m[0m
[0m[1m[31m    at runLoaders (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/webpack/lib/NormalModule.js:195:19)[39m[22m[0m
[0m[1m[31m    at /home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/loader-runner/lib/LoaderRunner.js:364:11[39m[22m[0m
[0m[1m[31m    at /home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/loader-runner/lib/LoaderRunner.js:230:18[39m[22m[0m
[0m[1m[31m    at context.callback (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/loader-runner/lib/LoaderRunner.js:111:13)[39m[22m[0m
[0m[1m[31m    at Promise.resolve.then.then.catch (/home/default/workspace/Galleries/Sybrin.UI.Modules.AppBuilder/node_modules/postcss-loader/lib/index.js:194:71)[39m[22m[0m
[0m[1m[31m    at <anonymous>[39m[22m[0m
Build step 'Execute shell' marked build as failure
```

**Comment by XhmikosR** [comment]
Clearly something on your side, probably obsolete local node_modules.

**Comment by tncho** [comment]
This error happened to many of us as well and locking Bootstrap to version 4.1.1 fixed the error (don't know what the cause is yet). Check out https://github.com/browserslist/browserslist/issues/266

**Comment by XhmikosR** [comment]
Yes, because you are using an outdated browserslist version somewhere, probably indirectly.

I don't get why whatever module you are using is loading **our** package's .browserslist though.

**Comment by tncho** [comment]
Well, I'm not sure. Leaving it as it is for now. Thanks for the quick response!

**Comment by XhmikosR** [comment]
My suggestion would be to prune your local node_modules and check for any npm updates.

But if our package.json is being used by other projects, which it shouldn't (for this exact reason), we can move the browserslist config to a separate file. I just want to know why this happens, because it must be something weird which I don't hit myself and thus I don't get :)

**Comment by tncho** [comment]
After performing what you suggested, I ran into the same error, but I don't think it's directly related to BS, in our case we're using angular 5.2 with an angular CLI version of 1.74, which has a dependency on 'autoprefixer' (outdated) which itself has a dependency on an old version of browserslist, as you can tell by this comment https://github.com/browserslist/browserslist/issues/266#issuecomment-404676720. There's something that bootstrap 4.1.2 doesn't like about browserslist 2.*, don't know what that would be. 
Thanks again for the quick reply **@XhmikosR** ! 🥇

**Comment by XhmikosR** [comment]
The `not dead` part is something new. But I still don't get why your tool tries to use our browsersconfig :S

Can you copy the related part into your project's package.json and try again?

If that still doesn't work, I guess we should move it outside of package.json. I just don't get why this happens.

**Comment by ai** [comment]
`npm ls` output will be more useful. It will show all Browserslist I instances and who required then.

**Comment by nicksterx** [comment]
clipped output from npm ls
```
+-- @angular/cli@1.7.4
| +-- autoprefixer@7.2.6
| | +-- browserslist@2.11.3
| | | +-- caniuse-lite@1.0.30000836 deduped
| | | `-- electron-to-chromium@1.3.45
| | +-- caniuse-lite@1.0.30000836
| | +-- normalize-range@0.1.2
| | +-- num2fraction@1.2.2
| | +-- postcss@6.0.22 deduped
| | `-- postcss-value-parser@3.3.0
```

@angular/cli is using the outdated browserslist. I added my own browserslist to my package.json and it still read in the bootstrap browserlists from their package.json.

**Comment by ai** [comment]
This is very outdated `angular/cli`. The current one is 6.x.

**Comment by nicksterx** [comment]
@ai Angular jumped the version number to put the angular projects in step with each other so they are all on 6.x. It's not as old as it appears, only a few months. 

Is `not dead` a best practice for browserslist? Should it be removed the Bootstraps package.json?
Why does bootstrap include this configuration when they are not including browserslist as a dependency?

**Comment by nicksterx** [comment]
This version of angular has LTS support until May 1, 2019.
https://angular.io/guide/releases#support-policy

**Comment by XhmikosR** [comment]
@nicksterx: you are confusing things. browserslist is being used by various projects we use including autoprefixer.

I've yet to find an explanation from someone who's having this issue why **our** browserslist is being used.

Like I said above, I can move the config to a `.browserslist` file, but I still don't get why this happens.

**Comment by ai** [comment]
@XhmikosR yes, `not dead` is the best practice and even part of default query

**Comment by ai** [comment]
@nicksterx yes, `not dead` is the best practice and even part of the default query

**Comment by nicksterx** [comment]
@XhmikosR I'm not sure why it's being used either. 

```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser query `dead`
```
This is the specific error I get.

**Comment by XhmikosR** [comment]
@ai: any idea why the postcss-loader loads our browserslist config from our package.json?

**Comment by ai** [comment]
@XhmikosR Browserslist uses a relative path to the file. If you are processing `app/main.css`, it will look to `app/` for config. If you are processing `node_modules/bootstrap/index.css`, it will look at `node_modules/bootstrap/`.

Maybe you should remove Browserslist config from npm package if you don’t use.

**Comment by XhmikosR** [comment]
We are using autoprefixer.

If I move the config to a `.browserslist` file, the same error will happen, right?

**Comment by ai** [comment]
@XhmikosR if you will add `.browserslistrc` to `.npmignore` it will fix the error and make npm package smaller

**Comment by XhmikosR** [comment]
We don't use an `.npmignore` file but since it won't be in the `files` section it won't be included.

OK, I'm gonna move the config there then.

**Comment by nicksterx** [comment]
Any idea on when this would make it out to a bootstrap 4.1.3 release?

**Comment by mgol** [comment]
> @XhmikosR Browserslist uses a relative path to the file. If you are processing app/main.css, it will look to app/ for config. If you are processing node_modules/bootstrap/index.css, it will look at node_modules/bootstrap/.

@ai OK, this is the reason then. I think this logic is a design mistake - which browsers are supported should be a decision of the final project, not libraries used. If one is compiling a Bootstrap CSS file into a final bundle they should not have random Browserslist configurations from dependent packages used for this file but whatever they configured.

**Comment by XhmikosR** [comment]
Yup, I agree with @mgol there.

@nicksterx: no ETA yet, I'll need to discuss it with @mdo.

**Comment by ai** [comment]
The design was created with the idea that npm packages will not contain development files.

The origin idea is to change Browserslist config for separated parts of the project.

**Comment by ai** [comment]
BTW, it is great chance to show [this nice project](https://github.com/shashkovdanil/clean-publish) to publish package without dev configs in `package.json`

**Comment by XhmikosR** [comment]
@ai: this was a choice made by someone. It's not by mistake. Still, I don't think this situation should happen IMO.

Anyway, I made #26896

**Comment by ai** [comment]
Hey, calling other project decisions a “mistake” is not cool 😏 it is software development, there are mistakes everywhere. In hardware (there are a lot of complain about x86), OS (only microkernel is good), VM (Node.js authors made a talk about his mistakes) and package manager.

Just finding one person and blame him is not cool 😏

I will add warning and will consider to change behavior if the problem will be repeated with some other project.

**Comment by XhmikosR** [comment]
@ai I'm personally not blaming "you". I just couldn't even imagine this could happen. And being that we didn't want to fill the repo with separate config files, we went with the config in package.json.

**Comment by ai** [comment]
> I just couldn't even imagine this could happen

It's always happens in IT. The most popular and dangerous bugs are not from typo, but from misunderstandings between the people.

> we didn't want to fill the repo with separate config files

Completely agree with you. This is why I am using `clean-publish` to keep config in package.json, but do not bloat npm packages from development configs.

**Comment by XhmikosR** [comment]
At this point, I'm afraid people *might* expect something to be there :P

I remember people using our babelrc for example.

**Comment by tncho** [comment]
Thank you very much @XhmikosR @ai for being open to discussion & tackling this issue altogether. In our project we wanted to keep everything updated and a fix seemed like the way to go here. You guys backing up on each other is nice to know when someone encounters this kind of issue, so, thanks again for the good work 🎉

**Comment by ai** [comment]
@tncho =^_^= thanks

**Comment by tetreault** [comment]
I ran into this using `create-nuxt-app`. The odd thing is I literally started a fresh project like 3 days ago and didnt face this problem. I now faced it this morning when starting another fresh project. It points to an error failing to compile bootstrap, but the error is raised by the BrowserList node module. Interestingly enough, I created a new fresh project from `create-nuxt-app` using Bulma instead of bootstrap and didn't have this issue pop up. Something funky is going on for sure.

**Comment by ai** [comment]
@tetreault yeap, dependencies hell :D. Anyway, the solution is simple — update Browserslist is dependencies.

**Comment by mgol** [comment]
What's the use case of hierarchically reading browserslist files? If you work on an app whatever browser support a particular dependency uses in its own package shouldn't matter; it's the application author that decides which browsers they support and they may decide to limit the support further.

I'd vote to remove this behavior even regardless of breakages like this one.

**Comment by ai** [comment]
> What's the use case of hierarchically reading browserslist files?

`src/.browserslistrc` for common front-end with many different browsers and `src/admin/.browserslistrc` with Chrome-only.

Babel use the link same hierarchical API (but they merge configs).

**Comment by mgol** [comment]
I see, thank you. Is there a use case that involves `node_modules`? Only third-party projects are here a problem in practice.

**Comment by ai** [comment]
I don't see use case with `node_modules`

**Comment by ai** [comment]
@mgol I will remove looking into `node_modules` in next major release. If there will be more packages with this config in npm package I will think to change in patch release
