### ISSUE TITLE
Bootstrap should use float-start, float-end instead of float-left, float-right to stop rtl confusion

### ISSUE THREAD

**Issue by wisamx** [twbs/bootstrap#26879]
Now when using bootstrap in RTL I used to use this:

```
[dir=rtl] {
  .float-left {
    float: right;
  }
  .float-right {
    float: left;
  };
}
```

I think bootstrap should use float-start, float-end instead of float-left, float-right to stop rtl confusion, like this:

```
  .float-start {
    float: left;
  }
  .float-end {
    float: right;
  };
```

So I could write:

```
[dir=rtl] {
  .float-start {
    float: right;
  }
  .float-end {
    float: left;
  };
}
```

**Comment by wolfy1339** [comment]
This would be a breaking change, and would need to happen in a major version bump

**Comment by mdo** [comment]
@wolfy1339 is correct, and we're aware this would be the preferred approach to directional properties. Thanks!
