### ISSUE TITLE
Modal with picture

### ISSUE THREAD

**Issue by AlexQuiniou** [twbs/bootstrap#26871]
Hi

I'm not sure if someone allready posted or the way I have code it is the good way

It work with Firefox and Edge in some cases, but not with chrome and everything else
Is it normal ?

![image](https://user-images.githubusercontent.com/34091990/42657190-d70e3990-8621-11e8-8c19-d10af85033c6.png)

Live preview : https://alexquiniou.github.io/portfolio/
--> "Travaux" button and "Logo"

                    
                    <button type="button" class="btn bg-white m-2 p-1" data-toggle="modal" data-target="#arche">
                        <img class="img-responsive" src="media\logo\concept\LOGO - ARCHE_COULEUR.png" alt="">
                    </button>

                    
                    <div class="modal fade" id="arche" tabindex="-1" role="dialog" aria-labelledby="archeTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered d-flex justify-content-center" role="document">
                            <div class="modal-content border-0 w-75 h-75">
                                <div class="modal-header border-0 d-flex justify-content-center">
                                    <button type="button" class="close m-0 p-0" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body d-flex justify-content-center bg-white rounded-bottom">
                                    <img class="img-responsive" src="media\logo\concept\LOGO - ARCHE_COULEUR.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by asyncdesign** [comment]
You need to use the class `img-fluid` on your image, not `img-responsive`. Also, remove the flex styles `d-flex` and `justify-content-center` from the modal body so that the image height doesn't stretch - you don't need them.

**Comment by AlexQuiniou** [comment]
Thank you 
Problem resolved
