### ISSUE TITLE
Feature Request: Add 'All Versions' link to dropdown docs menu for better UX/accessibility

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26883]
This is a feature request, possibly for Bootstrap 4.2 and onwards. Whilst the [https://getbootstrap.com/](https://getbootstrap.com/ ) website **does have a dropdown in the top right** for the latest versions of each version of Bootstrap, this isn't always going to facilitate for older versions of Bootstrap, or versions which are being used in some themes these days (see [here as an example](https://themeforest.net/category/ecommerce/magento?compatible_with=Bootstrap&sort=price-asc)).

**The current docs selector:**

<img width="312" alt="screen shot 2018-07-15 at 16 05 29" src="https://user-images.githubusercontent.com/25177538/42735270-f073e0e6-8848-11e8-817a-5b0a295a5d94.png">

There are plenty of themes out there which I've used in the past which use **Bootstrap v3.0.0**, and whilst this is older than 3.3.7, it's not always possibly to upgrade and we shouldn't be limited to not being able to access documentation for each of these.

**A suggestion, and something to consider**, once **Bootstrap 4.2** is released I'm not sure whether another link in the dropdown for versions will be added, or whether the 4.1 link will be replaced, but either way, whatever option that is chosen could clutter and make it hard to find older versions if you're less technologically advanced.

What you could do, is something very similar to what Bulma are doing, I think it's simple, straightforward and allows you to link to all of your versions, and allows us developers and designers to quickly find the **exact** version that we need, see the example below:

**Example: https://versions.bulma.io/**

<img width="796" alt="screen shot 2018-07-15 at 16 04 32" src="https://user-images.githubusercontent.com/25177538/42735261-d00e41ac-8848-11e8-8d7a-586f0a0da49d.png">

**Maybe consider adding an 'All Versions' link to the current dropdown, e.g-**

<img width="287" alt="screen shot 2018-07-15 at 16 08 52" src="https://user-images.githubusercontent.com/25177538/42735303-648e617c-8849-11e8-9fbc-4c40b6a0e9f2.png">

**Comment by coliff** [comment]
Good suggestion. I think it'd be a good idea to remove 'v4 Alpha 6' completely too. This version is really old, isn't supported and has lots of bugs which were fixed in later versions. Providing documentation on using that version doesn't help anyone because no one should be using it now.

**Comment by fchiumeo** [comment]
WIP #26989

**Comment by mdo** [comment]
@coliff I've left Alpha 6 given it was out there for like two years during development. Could maybe nix it, but it feels like a milestone worth keeping still for a bit. 😅
