### ISSUE TITLE
v3 .input-group-btn, first-child .btn trigger a paint event on hover.

### ISSUE THREAD

**Issue by petvas** [twbs/bootstrap#26905]
- Operating system and version: Windows
- Browser and version: tested on: latest Chrome and Firefox

**Step to reproduce the problem:**
1. goto: https://codepen.io/anon/pen/NBrdJO
2. open chrome dev tool, rendering tab, enable Paint flashing
3. hover the mouse on the 1st button and the last one,

**What is the expected behavior?**
hovering the buttons not triggering the paint event (paint not flashing)

**What went wrong?**
the 1st button is triggering the repaint

**Any other comments?**
the issue come from:  `\bootstrap\less\input-groups.less`
line: 153, `z-index` is changing to `2` 
in line 167 last-child has `z-index` already on `2`, meanwhile in line 161 the first-child doesn't.

Most of the time the input form is not in separate layer, what means this repaint is affected to the whole page.  (you can see it in google performance tab)

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work is focused on v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community).
