### ISSUE TITLE
more sizes, borders, and colored shadows

### ISSUE THREAD

**Issue by JuanMarchetto** [twbs/bootstrap#26903]
- More sizes
the w- and h- sizes utilitie is great and i think it should be extended, many sizes are very commonly used and it can be a good way for reducing code.
w-0 width: 0;
h-0 height: 0;
i found this two very helpfull when i make a collapsable sidebar with js
but here are a comlete list of clases that a usually added to my projects: 
  0: 0,
  25: 25%,
  50: 50%,
  75: 75%,
  100: 100%,
  auto: auto,
  1rem: 1rem,
  2rem: 2rem,
  3rem: 3rem,
  4rem: 4rem,
  5rem: 5rem,
  6rem: 6rem,
  7rem: 7rem,
  8rem: 8rem,
  9rem: 9rem,
  10ren: 10rem,
  15rem: 15rem,
  20rem: 20rem,
  25rem: 25rem,
  30rem: 30rem,
  40rem: 40rem,
  50rem: 50rem

- Borders sizes, i think the  border utilities should be extended adding a size subfix, like:
border-0 border: none; 
border-1 border-width: 1px;
border-2: border-width: 2px;
border-3: border-width: 3px;
border-4: border-width: 4px;
border-5: border-width: 5px;

so this can be use in combination whit thr border and border-color clases, like this:
border border-primary border-5

-Colored Shadows: the shadow utilities only have some size based options, adding color option can be a great function, for example: shadow-primary, shasow-sm-danger, etc.

**Comment by Johann-S** [comment]
Not sure if we will add more utilities because it will grow Bootstrap size 🤔 

/CC @andresgalante and @mdo

**Comment by mdo** [comment]
For the examples listed here, I'm a no on them all. Utilities cannot and shouldn't be added for every property-value pair we can imagine. Thanks for the suggestion though!
