### ISSUE TITLE
getbootstrap.com won't load Bootstrap CSS in macOS Safari

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#26915]
It looks like Safari on macOS has a different "integrity" string when loading the site's Bootstrap CSS file.

macOS 10.13.6 (17G65)
Safari 11.1.2 (13605.3.8)

This is the error in the console:

>Cannot load stylesheet https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css. Failed integrity metadata check.

In Safari, this is the full tag for that file:
`<link href="/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">`

Here is the same tag in Chrome, FireFox, and Opera:

`<link href="/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">`

**Comment by mdo** [comment]
Appears to be working fine for me and haven't seen any other complaints yet. Can you purge your browser cache to see if it resolves things? Safari doesn't include service workers, so I don't imagine it's that causing the issue @XhmikosR?

**Comment by XhmikosR** [comment]
Safari 11.1 does support service workers, see https://caniuse.com/#feat=serviceworkers.

Anything else shown in the browser console?

**Comment by mrlife** [comment]
Looks like I was doing it wrong. To clear the cache, it's Command+Option+E, not Command+Option+R. That fixed it, so this user error.

How did I end up with a reference to a different "integrity"?

**Comment by mrlife** [comment]
Looks like I was doing it wrong. To clear the cache, it's Command+Option+E, not Command+Option+R. That fixed it, so this is user error.

How did I end up with a reference to a different "integrity"?

**Comment by mdo** [comment]
Not sure honestly. I didn't think service workers were available in Safari because I didn't see anything in the console for it like I do in Chrome. Perhaps I have something disabled? Haven't dug into this more yet.

**Comment by XhmikosR** [comment]
Could this be a case where the visitor had visited before v4.1, thus was using the old 4.0 broken SW?

**Comment by mdo** [comment]
Could be, yeah

**Comment by coneybeare** [comment]
Rani into this today in Safari
![screen shot 2018-12-21 at 2 42 53 pm](https://user-images.githubusercontent.com/35369/50360661-c26bf400-052e-11e9-92f4-200dcb8c2dd8.png)

**Comment by XhmikosR** [comment]
Something isn't right @mdo in https://github.com/twbs/bootstrap/commit/6c8f6cebd46ed47db6ac31a63dacced34760ffc9

Why were the 4.1 dist files changed? Those should be reverted.
