### ISSUE TITLE
Custom input file doesn't show the filename after select a file.

### ISSUE THREAD

**Issue by wilsonrneto** [twbs/bootstrap#26914]
After select a file, the filename doesn't show in the field.

![tela-file-input](https://user-images.githubusercontent.com/41375989/42883752-7cbf96c6-8a6a-11e8-9af1-959c5e17e205.png)

Test case: https://jsbin.com/xawatagaro/edit?html,output
Browser and version: Chrome 67.0.3396.99 64 bits
Bootstrap: 4.1.2

Best regards,
Wilson Rocha

**Comment by Johann-S** [comment]
Yep that's exactly what it's written in our documentation see: https://getbootstrap.com/docs/4.1/components/forms/#file-browser

>The file input is the most gnarly of the bunch and requires additional JavaScript if you’d like to hook them up with functional Choose file… and selected file name text.
