### ISSUE TITLE
Under flex-layout, Help-Text with container is not aligned on Mobile Devices(in responsive)

### ISSUE THREAD

**Issue by akashshrimali** [twbs/bootstrap#26913]
-Bootstrap version 4.1
- Browser and version (Chrome Browser).Version 67.0.3396.99 (Official Build) (64-bit)
- Operating System :  Windows 7 operating system.
- Please find the test case on JS Fiddle :  https://jsfiddle.net/vipbhavsar/aq9Laaew/98073/ 

In this particular above fiddle: all input boxes shall align in same base line even if they are provided with varied help-text .
  "mt-auto" is applied on all the container however, with or without help-text it is not align in flex layout.
![saver1](https://user-images.githubusercontent.com/3968151/42880818-50e0cb4e-8ab3-11e8-8644-a342ee6ec964.png)

**Comment by mdo** [comment]
This isn't a Bootstrap bug, and it I don't know for sure if it can be accomplished with pure flexbox CSS. Your best bet is to ask around our Slack and Stackoverflow (links in readme).
