### ISSUE TITLE
Bootstrap example (Pricing)

### ISSUE THREAD

**Issue by NicoCG** [twbs/bootstrap#26918]
I am not sure if I am posting this in correct repository but related to this [Example](https://getbootstrap.com/docs/4.1/examples/pricing/) where can I find the complete example meaning the missing page `features` does anyone have a bootstrap 4.0 example of a feature page that will suit this amazing clean example?

I would do it my self but I am not really good with front-end dev (I am extremely messy which is why I use themes.)

**Comment by Derplicity** [comment]
Not 100% sure what you are asking for, but if you 'View Page Source' on the example you linked, you will find the HTML and Bootstrap 4 classes that make up the view.

**Comment by NicoCG** [comment]
Hi @Derplicity Basically what I was asking could you add a features page to the pricing example it would be helpful but for now I will use 'View Page Source'

**Comment by mdo** [comment]
This is something you can handle by downloading the source code and modifying it yourself. Closing as we won't be making this change to the example itself.
