### ISSUE TITLE
Modal Documentation - .modal-dialog & .fade interaction

### ISSUE THREAD

**Issue by bhgeorge** [twbs/bootstrap#26924]
Hello, this is my first issue submission. I have attempted to follow the posted guidelines but if I have made an error please let me know so I may remedy that issue in the future.

### The short version
There should be documentation outlining the fact that if a modal is created with the `.fade` class it is also required to have a `.modal-dialog` class.

### What is occuring

If a modal is created with the `.fade` class and not the `.modal-dialog` class the modal will show but it's `_isTransitioning` property will never be reset.

https://github.com/twbs/bootstrap/blob/eb81c39f2c36d88d4ebc062a2fa179980827e8be/js/src/modal.js#L263-L271

As is shown here a listener for `transitionEnd` is attached to the child element of the modal with the class `.modal-dialog`. However, since `.modal-dialog` is `null` the listener is not attached and the `transitionComplete` method is never called. This results in a modal that cannot be hidden as it is considered to be transitioning at all times.

### The issue

It makes sense to enforce the addition of the `.modal-dialog` class. A check could be implemented to skip the `transitionEnd` listener if the dialog element is `null` but that could lead to issues where users could re-trigger the modal before it has visually finished animating, which is what the entire `_isTransitioning` property seems to be preventing in the first place.

This information should be exposed in the documentation so developers looking to co-opt the javascript modal functionality without the styling are aware of this requirement.

### Suggested solution

Refactor the [Remove Animation](https://getbootstrap.com/docs/4.0/components/modal/#remove-animation) section to be an **Animation** section that details the fact that `.modal-dialog` is required when using the `.fade` class because it is used to listen for a transition and then contains a second paragraph containing the existing remove animation content.

**Comment by mdo** [comment]
`.modal-dialog` is a required class and structural element for the component. No where does it imply in the docs that this class is optional as far as I know. Why assume it's not required when it's in the component's code examples?

**Comment by bhgeorge** [comment]
Thank you for the response.

I do believe that is a fair point, and if the desired purpose for the component is to be used wholesale without edit my point is moot.

However I believe that for those who are looking to simply use the functionality of the component and handle the styling themselves that it could be stated more explicitly.

There are a large number of optional pieces to the modal component, and they are stated as such.
However it is not explicitly stated anywhere what is required. The fact that the modal can function properly without `.modal-dialog` as long as `.fade` is not present is what I believe warrants the need for it to be explicitly stated.

Again if the purpose of the component is to be copied wholesale I do not believe this request to be valid any longer, however I do not see the harm in explicitly stating the required  structure for the proper function of the component if the use of this component is to be more of a baseline of functionality to be expanded upon.

**Comment by XhmikosR** [comment]
PRs to improve the docs are welcome.
