### ISSUE TITLE
Why not releasing a ready to use code for example use in a Wordpress custom theme

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#26928]
For the past 3.3.1 there was http://www.initializr.com/

>  Hey everyone! Initializr is going to retire at the end of 2017. I'd recommend using H5BP or Bootstrap directly instead. It doesn't take that long to combine them together and you'll get more up-to-date versions of those. Thank you for using Initializr all these years!

Including a ready to use pack should help make Bootstrap more popular and make it easier to use for it's userbase. Also to consider it is a good idea to enable legacy code support in a separate version, similar as Fontawesome does in order to enjoy new features without having to completely migrate the website! And instead allow for a progressive migration...
Kind Regards!

**Comment by mdo** [comment]
You can download and include Bootstrap's compiled CSS, ready to use for any Wordpress theme or any other project.
