### ISSUE TITLE
Tinkerboard basic overlay support

### ISSUE THREAD

**Issue by oliskoli** [twbs/bootstrap#26925]
Hi together and many thanks for your work!

I've made some patches to get basic overlay support into the next (!) branch. I have successfully tested common sensors like dht11 or onewire w1, but got also other stuff working as pps or a fbtft display (waveshare). These patches would be enough for me, but would need some work to get a full support (i.e. fixup script).

Are there interests on that ? And, if yes, do I have to go over git/fork/... or can I provide my "userpatch" directory ?

Kind regards

**Comment by oliskoli** [comment]
sorry, wrong place :-(

**Comment by andricksantos** [comment]
you welcome
