### ISSUE TITLE
Odd spacing on bottom of modals in IE11

### ISSUE THREAD

**Issue by nformer** [twbs/bootstrap#26935]
Odd spacing is being added to the modals in Internet Explorer 11 when adding labels and inputs enclosed in a div.  The spacing grows larger for each added block.

[Code Pen Here](https://codepen.io/nformer/pen/jpyEEz) 

```
<div>
          <label>aaa</label>
          <input type="text" name="name" value="" />
</div>
```
![capture](https://user-images.githubusercontent.com/17071923/43017148-196b5a14-8c23-11e8-8140-f07907dc75ab.PNG)

If you take the enclosing div out, the spacing goes away, but blows the layout.

```
          <label>aaa</label>
          <input type="text" name="name" value="" />
```

![c2](https://user-images.githubusercontent.com/17071923/43017427-1ac24a84-8c24-11e8-8778-29b64fd4733f.PNG)

This behavior does not seem to manifest in edge, chrome, or firefox.

Summary:
- OS: Windows 10
- Browser: Internet Explorer 11
- [Code Pen Here](https://codepen.io/nformer/pen/jpyEEz) 
- bs-css: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css
- bs-js: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js
- jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
- popper: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/esm/popper.js

**Comment by mdo** [comment]
I've seen this reported for selects too in modals and I have no idea what's causing it. The presence of a `<div>` should have no impact here. This has to be something unique to IE11, but I never was able to figure out what. Regrettably, I think this is a can't fix. Please share if there's been any improvements or insights to the problem though!
