### ISSUE TITLE
Bootstrap can't works with css-module properly in react [help wanted]

### ISSUE THREAD

**Issue by cjs840312** [twbs/bootstrap#26930]
### Bootstrap Modal Never pops out
I'm using **React** front end on **Express**  server,  using **webpack** with **babel, css, style loader** and **Bootstrap** for styling.
I'm trying to add a **Bootstrap modal** to my website which should pop out when button clicked. However the Button was rendered successfully but the modal never shows up after clicked. I found many related question but none of them have the same environment as mine. Some use react-bootstrap or reactstrap while others not using webpack or css-module.

This is my github [repo](https://github.com/cjs840312/testWEB) which only contains minimum files used to reproduce the problem .

It seems to be related to **JQuery** issue since Bootstrap used some of it's feature to implement Modal. However I couldn't find the solution

###  Bootstrap modal works well without css-module
I have noticed that if I don't use **css-module**, which means
` {   loader: 'css-loader'   ,   options: { modules:'false' } }  `
and change
` import BS from  'bootstrap/dist/css/bootstrap.css'; // in App.jsx`
to
`import 'bootstrap/dist/css/bootstrap.css'; // in index.jsx`
`import 'bootstrap' // in App.js`

and change all
`
className={BS.someclass}" 
`
back to
`
className='some class'
`
the modal will shows up as expected.

However since css-module is the recommend way to deal with css styling, I still wondering if there's a way to use Modal without turning off css-module.

Please refer to the repo to help me solve this problem.

### Files related :

webpack.config

    const path = require('path');
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const webpack = require('webpack');
    module.exports = {
        entry: './src/front/index.jsx',
        output: {
            path: path.join(__dirname, 'src/dist/'),
            filename: 'bundle.js',
        },
        plugins: [
            new HtmlWebpackPlugin({
                template: './src/front/HomePage.html',
                filename: 'HomePage.html',
                inject: 'body',
            }), 
        ],
        devtool: 'eval',
        resolve: {
            extensions: ['.js', '.jsx'],
        },
        module: {
            loaders: [
                { test: /\.(js|jsx)$/, loader: 'babel-loader' },
                {
                    test: /\.css$/,
                    use: [
                        { loader: 'style-loader' },
                        { 
                            loader: 'css-loader'   ,
                            options: { modules:'true' }
                        },
                    ],
                },
            ],
        },
    };

App.js

    import React, { Component } from 'react';
    import BS from  'bootstrap/dist/css/bootstrap.css';
    class App extends Component {
        constructor(props) {
            super(props);
            this.state = {};
        }

        render() {
            return (
                <div>
                    <button type="button" className={[BS.btn, BS["btn-primary"]].join(' ')} data-toggle="modal" data-target="#exampleModal">
                        Launch demo modal
                    </button>

                    <div className={[BS.modal, BS.fade].join(' ')} id="exampleModal" tabIndex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div className={BS["modal-dialog"]} role="document">
                            <div className={BS["modal-content"]}>
                            
                                <div className={BS["modal-body"]}>
                                    ...
                                </div>
                            
                            </div>
                        </div>
                    </div>
                </div>
            );
        }
    }

    export default App;

**Comment by Johann-S** [comment]
That's because Bootstrap 4 isn't compatible with `css-module` so you should use reactstrap or react-bootstrap, or simply do not use css-module

**Comment by cjs840312** [comment]
Oh!  Thank you very much for the response.
I was wondering if there're some bugs in mode code.
Will Bootstrap work on **css-module** and supports in the future ?

**Comment by Johann-S** [comment]
I'm not pretty sure about that, since it's already handle by reactstrap or react-bootstrap

/CC @mdo
