### ISSUE TITLE
Dropdown menu content with a max-height will not scroll in IE 11

### ISSUE THREAD

**Issue by emage** [twbs/bootstrap#26936]
When displaying a lot of content in a dropdown menu with a max-height and overflow set to auto, holding down the track button to drag and scroll will not scroll the content.  They appear stuck.
Using any other method will scroll the content - up/down button, mouse wheel, click inside the track.

NOTE: A normal overflow block of text will, however, scroll by holding and dragging the track button.

Testing:
Works in all major browser except IE 11. 
Edge works as well.

CODE PEN DEMO: https://codepen.io/anon/pen/mjRVGB

**Comment by sts-ryan-holton** [comment]
@emage 

Please refer to => https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#supported-browsers

Although supported, IE isn't the best browser and isn't used by many peopl https://caniuse.com/usage-table

**Comment by emage** [comment]
@sts-ryan-holton 
Thanks for the info.
The issue seems to be related to the **'transform:translate3d()`.**  
The old version of bootstrap does not generate this so it works -- only drawback in the old version was that it was not changing position if not enough space below etc.

The new Bootstrap does this with translate -- but i guess at a cost.

**Comment by Johann-S** [comment]
You can disable Popper.js which position our elements and fix your issue see: https://codepen.io/Johann-S/pen/gjxGjW

but you loose autopositioning 😟

**Comment by emage** [comment]
@Johann-S 
Popper.js is needed as we use a lot of tooltips and popovers as well.  I am using the bundle files.

Currently my solution was to override it via CSS to remove the transform property only on this dropdown.  And yes , I lose the auto positioning.  Users will have to scroll down as I made some extra spaces below it.

**Comment by mdo** [comment]
Testing this again, I don't see an issue in IE11 on Browserstack. https://cdpn.io/emdeoh/debug/JjRaQXX

Looking at the referenced issue above here too in #28693, there's also a possible solution there if this indeed doesn't "just work" as my demo showed me.

**Comment by xaviarnl** [comment]
@mdo: I opened your browserstack page, and it still shows the problem for me in IE11. Using the handle to scroll the list in the top list works without problems. However, if I click the "Dropdown button" and try to use the handle in the dropdown, the list won't scroll in IE. Or more correct: it only scrolls a few pixels at a time - after that you have to release the handle and move it again to be able to scroll a few more pixels.
