### ISSUE TITLE
Input group in table scrolling on IE11

### ISSUE THREAD

**Issue by mhspelt** [twbs/bootstrap#26932]
Hi,
I am trying to do a layout where i have a <table> with some input groups in it. This works fine in Chrome and Edge: the input fields scale their widths so that the table fits on the width of the page, for as long as feasible. See this JSBin: http://jsbin.com/sozetategi and try resizing the screen.

But Internet Explorer 11 wants to make the input groups of a fixed width, pushing the columns beyond the widths specified in the `th` and making the table scroll horizontally even when maximized on my 1900x1200 resolution screen.

Here are two screenshots, from Chrome and IE11 respectively, showing the expected and incorrect output:
  [1]: https://i.stack.imgur.com/xHHDv.jpg
  [2]: https://i.stack.imgur.com/SRtAB.jpg

**Comment by mdo** [comment]
I'm guessing this is some IE-specific flexbox bugs, and not likely something we can tackle for everyone in every situation. Take a look at https://github.com/philipwalton/flexbugs.
