### ISSUE TITLE
Tooltip with Word "Exchange"

### ISSUE THREAD

**Issue by malbert55** [twbs/bootstrap#26939]
Any form input item that has a title element (for tooltips) that starts with the word "Exchange" will cause the field's autocomplete feature to turn on.  I know it sounds bizarre but I've tested this with several fields.  I grep'ed all of my code for the word "Exchange" and there is nothing that exists that would turn on that feature.  Any help would be appreciated.  Thanks!

```html
<input id="rate" name="rate" class="form-control" type="number" step="0.0001"
                     placeholder="Exchange Rate to USD"
                     data-toggle="tooltip" title="Exchange rate, automatically supplied but you can change it"
                     data-validation="required">
```

**Comment by mdo** [comment]
Autocomplete is opt-out, so the solution here is to disable autocomplete on that input field. This isn't a Bootstrap bug. Also, `title` isn't a valid attribute on inputs. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by malbert55** [comment]
I have come back to this and am still having issues.  Autocomplete will not turn off for this field - and it is only this field.  I have turned autocomplete off on the form and on the input field.  Here is an extract of my form…

<form id="editMainForm" autocomplete="off">
            <div class="form-group">

              <input id="transDate" name="transDate" class="form-control" type="text"
                     placeholder="Transaction Date"
                     data-toggle="popover" data-trigger="focus" title="Transaction Date"
                     data-content="The effective date of this transaction">

              <input id="account" name="account" class="form-control" type="text"
                     placeholder="Account Name" autocomplete="off"
                     data-toggle="popover" data-trigger="focus" title="Account Name"
                     data-content="Choose an account from the list below. If you don't see something you like just type it in and it will automatically be \
added to your list.  Accounts are typically things like CASH, CHECKING and SAVINGS.">


Here are the tools I am including…

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQR\
IY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" cros\
sorigin="anonymous"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJ\
iSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7w\
o/CG0xlczd+2O/em" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq7\
9v+lsFkW54bOGbiDQ" crossorigin="anonymous">

I can send you the complete source code if you’re interested.  Thanks for looking.


Marc Albert
www.ourtripnotes.com <http://www.ourtripnotes.com/>

**Comment by patrickhlauke** [comment]
again: this is nothing to do with Bootstrap. please ask in StackOverflow or similar...this isn't the right place to ask for general development help. https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
