### ISSUE TITLE
Update npm registry info versions! 

### ISSUE THREAD

**Issue by NikitaKharkov** [twbs/bootstrap#26941]
I couldn't find any new list of versions in [this link](https://registry.npmjs.org/boostrap) searching by `npm info boostrap` or `yarn info boostrap`. It suggest me to install 1.0.0 or 2.0.0 version. Could you update this json? It will be more comfortable to understand which packages are available.
Maybe I do something wrong - just correct me. 
Thanks a lot!

**Comment by mdo** [comment]
Yup, looks right to me as well.

**Comment by fchiumeo** [comment]
https://registry.npmjs.org/boostrap
wrong name boostrap => bootstrap
https://registry.npmjs.org/bootstrap
