### ISSUE TITLE
btn-link does not work if using div instead of ul

### ISSUE THREAD

**Issue by josejmoran** [twbs/bootstrap#26944]
I am using bootstrap 4.1.2 for an ASP.NET project I am trying not to use the ul and instead using a div, but when I do that in the code below sample the button becomes longer when I go to mobile size view port.
It seems the btn-link does not hold when using a div. As soon as I put the ul the size of the button fit the label.

Also the undeline when I hover does not show.

The code below works, but the underline never shows when I hover, plus if I change the ul to a div to have a less cluttered code the button gets bigger than the title and I do not want that, but what it seems is that the btn-link class is not taking hold in either case me putting the div or ul. The ul does make the button fit the content though.

        <ul class="navbar-nav">
            <li><a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" class="nav-item nav-link">Hello @UserManager.GetUserName(User)!</a></li>
            <li><button type="submit" class="btn btn-link nav-item nav-link">Logout</button></li>
        </ul>

Also if I take out the nav-item nav-link from the button the link underline works, but the color of the text is blue so I want it to match the color of the navbar text. Well it is not easy to do. I added .btn-secondary and other classes but the color do not match. There has to be an easier way to make them all match. I guess I can figure out the default color for the nav and force the link button to match.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

That aside, you're combining buttons and nav styles, which isn't strictly allowed. You should be splitting the button styles from the nav item/link styles here. You're bound to run into trouble with that kind of approach. I'm sure I'm missing some of your code here, but a submit button without a parent form doesn't make sense either.

Lots to unpack there, but beyond what I can help with here. If you can, split the component classes by nesting. If not, you may need additional styles.
