### ISSUE TITLE
list group item -1px bottom margin

### ISSUE THREAD

**Issue by ChadTaljaardt** [twbs/bootstrap#26940]
- Operating system:
**macOS**
 
- Operating System version:
**10.14**

- Browser and version 
**Chrome 67.0.3396.99**

Issue can be seen on the Boostrap website :
https://getbootstrap.com/docs/4.1/components/list-group/

When clicking on the list group items, you see this (which is correct behaviour):
<img width="1324" alt="screen shot 2018-07-22 at 09 45 15" src="https://user-images.githubusercontent.com/13891249/43043949-afe6a684-8d94-11e8-824c-f3d8e29e3290.png">

However when you click away, the bottom border dissapears and it looks weird: 

<img width="1290" alt="screen shot 2018-07-22 at 09 45 29" src="https://user-images.githubusercontent.com/13891249/43043952-bf0b0a24-8d94-11e8-9a08-e8d348751852.png">

Offending class: 
```
.list-group-item {
    margin-bottom: -1px
}
```

You can set this to be 0 and therefore the issue doesn't persist, but then you get certain side effects, being that each of the items now have a big bottom border.

**Comment by caneno** [comment]
I am pretty new here but what if you remove the margin-bottom and in border to change it from 1px to 0.5px like this:
```
.list-group-item{
       /* margin-bottom: -1px;  THIS LINE SHOULD BE REMOVED */
      border: 0.5px solid rgba(0,0,0,.125);
}
This way the thickness of the border will not b compromised

**Comment by mdo** [comment]
The borders overlap, it's an approach we use to avoid having to toggle borders entirely. It's not perfect, but it's easier in my opinion and consistent with our other components that use the same approach.
