### ISSUE TITLE
Product example page uses semi-transparent navbar by intent?

### ISSUE THREAD

**Issue by Ruffio** [twbs/bootstrap#26945]
Is it by intent, that the product example page (http://getbootstrap.com/docs/4.1/examples/product/) uses semi-transparent navbar?

![image](https://user-images.githubusercontent.com/1877612/43089005-e1d44b32-8ea3-11e8-9c06-bff2aa394928.png)

**Comment by mdo** [comment]
Look at the source code—there's an `rgba()` background that can answer your question :).

(It's a yes, it's by design.)
