### ISSUE TITLE
Modal: adding a background-color to modal-footer results in square bottom corners

### ISSUE THREAD

**Issue by thiagoesser** [twbs/bootstrap#26955]
Just like in Issue #23798, only applied to **modal-footer**: if you set a background-color on the modal-footer, you get square corners at the bottom of the modal window. The background-color covers the rounded corners. 

Version of Bootstrap: v4.1.1
- Operating system and version (macOs High Sierra v10.13.4)
- Browser and version (v67.0.3396.99)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by thiagoesser** [comment]
Live demo: https://codepen.io/thiagoesser/full/oMJNmz

- Version of Bootstrap: v4.1
- Operating system and version: macOs High Sierra v10.13.4
- Browser and version: Chrome version 67.0.3396.99

**Comment by charlesfries** [comment]
`.modal .modal-body { border-radius: 0 0 $modal-content-border-radius $modal-content-border-radius; }`
