### ISSUE TITLE
Form variable definitions appear inconsistent

### ISSUE THREAD

**Issue by Dagothig** [twbs/bootstrap#26953]
Both forms and buttons share variable definitions form the `$input-btn-` line of variables. However some of the computed default values use the `$input-btn-` variables rather than the `$input-` ones. For instance inner height is defined as `($font-size-base * $input-btn-line-height) + ($input-btn-padding-y * 2)`. Each of these btn variables is also defined so it means that changing the input line height doesn't change the actual input height, but changing the input btn line height does, which comes off as a little surprising.

In a similar manner, the `$custom-select` variables mix both `$input-btn` and `$input` variables when all of the variables are defined by `$input`.

Overall this leads to situations where overriding all the `$input` variables only partially changes the values that are used (so for instance the custom select's height does not match the other input heights).

**Comment by tkrotoff** [comment]
After reading [the source code](https://github.com/twbs/bootstrap/blob/v4.1.3/scss/_variables.scss#L445), found it strange to have:
`$input-height-inner: ($font-size-base * $input-btn-line-height) + ($input-btn-padding-y * 2) !default;`

I think this should be written like this:
`$input-height-inner: ($font-size-base * $input-line-height) + ($input-padding-y * 2) !default;`
so without btn. btn means button right?

Same for $input-height-inner-sm and $input-height-inner-lg

**Comment by k-funk** [comment]
I agree with @tkrotoff. It should be:
```
$input-height-inner: ($font-size-base * $input-line-height) + ($input-padding-y * 2) !default;
```

 https://github.com/twbs/bootstrap/pull/27249 may have cleaned some things up, but not this particular one.

**Comment by XhmikosR** [comment]
@k-funk: please make a PR :)
