### ISSUE TITLE
Alignment of footer for cards in card deck not possible?

### ISSUE THREAD

**Issue by Ruffio** [twbs/bootstrap#26962]
I would like to align the footers in a card deck, but I can't see how that can be done. Is it possible with native Bootstrap (https://getbootstrap.com/docs/4.1/components/card/)?

Here is my code:
> <div class="card-deck">
    <div class="card">
        <div class="card-header">
            <img src="~/Content/Image/lock-outline.svg" class="card-header-icon" alt="lock" />Stærk end-to-end kryptering
        </div>
        <div class="card-body">
            <p>
                Beskeden krypteres i browseren inden afsendelse med en stærk krypteringsalgoritme (AES-256).
            </p>
            <p>Beskeden dekrypteres ligeledes i browseren men kun, hvis den rigtige kode anvendes.</p>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <img src="~/Content/Image/clock-outline.svg" class="card-header-icon" alt="clock" />Tidsbegrænset i 24 timer*
        </div>
        <div class="card-body">
            <p>
                Modtageren af beskeden har 24 timer til at hente og læse beskeden.
            </p>
            <p>
                Efter 24 timer slettes beskeden på serveren og kan ikke genskabes.
            </p>
            <footer class="blockquote-footer">
                for Premium kan varighed ændres
            </footer>
        </div>
    </div>
    <div class="card">
        <div class="card-header"><img src="~/Content/Image/mail-var-outline.svg" class="card-header-icon" alt="mail" />Engangsbesked*</div>
        <div class="card-body">
            <p>
                Modtageren af beskeden har kun ét forsøg til at indtaste korrekt kode og læse beskeden.
            </p>
            <p>
                Ved første forsøg slettes beskeden på serveren og ikke gendannes.
            </p>
            <footer class="blockquote-footer">
                for Premium kan antal ændres
            </footer>
        </div>
    </div>
</div>

When using `<footer class="blockquote-footer">`, I get:
![image](https://user-images.githubusercontent.com/1877612/43193833-4ccee7c2-9001-11e8-808e-2222e97704e5.png)

and when using `<div class="card-footer text-muted">` I get:
![image](https://user-images.githubusercontent.com/1877612/43193892-6af58abc-9001-11e8-8bb8-156235548696.png)

If this is by intend, just close this issue.

**Comment by wfw40869** [comment]
Would using a flexbox solve this like they did for this? @Ruffio [https://github.com/twbs/bootstrap/issues/19381](url)

**Comment by Ruffio** [comment]
Lol, I didn't make the markup correct :-( After correcting the markup, I ended up with:

>  <div class="card">
        <div class="card-header"><img src="~/Content/Image/mail-var-outline.svg" class="card-header-icon" alt="mail" />Engangsbesked*</div>
        <div class="card-body">
            <p>
                Modtageren af beskeden har kun ét forsøg til at indtaste korrekt kode og læse beskeden.
            </p>
            <p>
                Ved første forsøg slettes beskeden på serveren og ikke gendannes.
            </p>
        </div>
        <div class="card-footer text-muted">
            <small>* ved Premium kan antal ændres</small>
        </div>

That results to: 
![image](https://user-images.githubusercontent.com/1877612/43220788-36021fe2-904b-11e8-9e7d-139215c96066.png)

I will close this issue as it is working as expected :-)

However I did find this redundency. It looks like 'small' is defined in both 'type' and 'reboot' with 'font-size: 80%'. Shouldn't defining 80% one place be enough?:
![image](https://user-images.githubusercontent.com/1877612/43220932-9fa2c4f6-904b-11e8-8956-4108b6e6ba04.png)

**Comment by wfw40869** [comment]
The example you have above looks like a redundancy. I don't see a .small class in your HTML above, but if you wanted to segregate only the .small class to inherit the font-weight: 400; you could write your CSS like so:

```

.small{
	font-size: 80%;
	font-weight: 400;
}

small{
	font-size: 80%;

}

```
