### ISSUE TITLE
Doesn't work with jQuery.noConflict()

### ISSUE THREAD

**Issue by jigarius** [twbs/bootstrap#26964]
## Problem

If jQuery is included using `jQuery.noConflict()`, which many CMSs and frameworks do, Bootstrap JS doesn't work at all. I think this is because Bootstrap assumes jQuery to be available with `$` instead of `jQuery`.

```javascript
(function($) {
  // Bootstrap stuff here.
})($);
```

## Solution

Look for jQuery in the `jQuery` variable instead.

```javascript
(function($) {
  // Bootstrap stuff here.
})(jQuery);
```

**Comment by Johann-S** [comment]
I don't know about which version you're talking about but that's not the case, currently Bootstrap 4 and Bootstrap 3 works in no conflict mode see: https://codepen.io/Johann-S/pen/QBgzPM?editors=1010#0
