### ISSUE TITLE
Navbar: add $navbar-nav-link-padding-y

### ISSUE THREAD

**Issue by royklutman** [twbs/bootstrap#26977]
Is it an idea to add `$navbar-nav-link-padding-y` to the navbar links?

`_navbar.scss` currently only sets the x-padding:
https://github.com/twbs/bootstrap/blob/a194abbb5aaa999f5c0eba4bba4f7aff6ab2d0ad/scss/_navbar.scss#L165-L168
The y-padding is currently inherited from `_nav.scss`:
https://github.com/twbs/bootstrap/blob/a194abbb5aaa999f5c0eba4bba4f7aff6ab2d0ad/scss/_nav.scss#L14-L26

Thanks!

**Comment by mdo** [comment]
Because the value is inherited, we don't need to reset it again in the navbar styles unless we're overriding it. We go back and forth on this in Bootstrap, but the `.nav` base class is definitely geared towards inheritance.
