### ISSUE TITLE
Text Utility: text-default

### ISSUE THREAD

**Issue by tthorp** [twbs/bootstrap#26971]
I have a situation where I want my top-level nav to be uppercase and the dropdowns to be as-typed. Since the dropdowns have prepositions and acronyms, I need a class that renders the text as typed and it would need to override the parent class of text-uppercase. 

Perhaps text-default? or text-no-transform

Thanks! 

Tim

PS: I can make my own CSS for this but thought I would ask

**Comment by MartijnCuppens** [comment]
Hi Tim,
I would just add the `.text-uppercase` class to all elements that need to be in uppercase and don't add it to a parent container?

**Comment by mdo** [comment]
Closing as a won't fix. This is possible with explicit classes and doesn't require a full reset.
