### ISSUE TITLE
Need to set 'min-height: 0' for blank columns.

### ISSUE THREAD

**Issue by adsingh14** [twbs/bootstrap#26975]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile): Windows
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser): Chrome 67+
- [Reduced test case](https://codepen.io/adsingh14/pen/KBvOba)

**Comment by royklutman** [comment]
Just to elaborate on this, it's currently set to `1px` to prevent collapsing:
https://github.com/twbs/bootstrap/blob/a194abbb5aaa999f5c0eba4bba4f7aff6ab2d0ad/scss/mixins/_grid-framework.scss#L8-L14
Maybe someone can explain why this is done exactly and why columns may not collapse when empty?
