### ISSUE TITLE
Cursor misalignment

### ISSUE THREAD

**Issue by jensamunch** [twbs/bootstrap#26974]
Anybody else seeing this:

<img width="374" alt="screen shot 2018-07-26 at 18 09 39" src="https://user-images.githubusercontent.com/1650140/43277297-8e35d2f8-90ff-11e8-8e16-228e843669d3.png">

**Comment by MartijnCuppens** [comment]
It's probably a misalignment in the custom font you're loading, not something Bootstrap can take care of.

**Comment by jensamunch** [comment]
yes i think you're right..just checked.

weird since its avenir from myfonts.com with no modification.
