### ISSUE TITLE
Box-sizing: border-box not working on IE11

### ISSUE THREAD

**Issue by zeroplexer** [twbs/bootstrap#26980]
I have a subnavigation with different boxes on my page, but the size of the content in the box are different. In FF, Chrome and Edge they scale the boxes to the same height but IE11 didn't do that. How can I fix that?

![box-sizing](https://user-images.githubusercontent.com/41778593/43312144-b4a9f90e-918c-11e8-80b3-ef3d227dabfa.png)

**Comment by Joyrex** [comment]
@zeroplexer Have you looked at using [Card Decks](https://getbootstrap.com/docs/4.0/components/card/#card-decks)? (You may be in your example but since it's a screenshot it's hard to determine for sure)

**Comment by sts-ryan-holton** [comment]
@zeroplexer  I'd agree with @Joyrex. Please read the documentation fully as it contains up-to-date information about how to use certain components. Make sure to nest elements within the natural grid flow, and be sure to update to the latest v4.1.3. Only then consider opening an issue. please see: https://getbootstrap.com/docs/4.1/components/card/#card-decks

**Comment by mdo** [comment]
Hard to tell if this is a Bootstrap powered page, but there's no live demo and other details. Closing out as a won't/can't fix for now.
