### ISSUE TITLE
Website Layout Broke - Was using version 3

### ISSUE THREAD

**Issue by DragonOsman** [twbs/bootstrap#26988]
Hi, everyone.

I have a website published via GitHub.  It was using version 3 of Bootstrap for the layout but now the layout part is broken.  For one thing, I can't get the items in the navbar in the header to be aligned horizontally with spaces between them.  And while the footer navbar is aligned horizontally, the links have no spaces.  And I also can't get the bullets on the navbar items in the header to disappear even though I've set `list-style-type` to `none` on them.  

The GitHub for the website, with the files, can be found here: https://github.com/DragonOsman/DragonOsman.github.io .  Any help is appreciated.  Thanks in advance.

**Comment by patrickhlauke** [comment]
for general help/advice, please use stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
