### ISSUE TITLE
[doc][build task] wrong path to lint css in task css-lint-docs

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#26994]
Hello,

Following the move of docs under site folder, I think there's a mistake in npm task `css-lint-docs` https://github.com/twbs/bootstrap/blob/0b5a8d9c981ae70153cdd64b250a3d9e53014422/package.json#L32 try to lint css under docs folder, maybe need to be site/docs ?

Same error on `css-prefix-docs` https://github.com/twbs/bootstrap/blob/0b5a8d9c981ae70153cdd64b250a3d9e53014422/package.json#L35

**Comment by Lausselloic** [comment]
Hello,

Thanks for the fix. Maybe it's just my dev environnement but task css-lint-docs doesn't work and finish with : 
```
> stylelint --syntax scss "site/docs/4.1/assets/scss/*.scss" && stylelint "site/docs/**/*.css"

Error: Could not find "../../../.stylelintrc". Do you need a `configBasedir`?
```
Just look at the travis build on the PR and the task css-lint-docs isn't run.

**Comment by XhmikosR** [comment]
I'm gonna fix this too.

More broken things after the docs refactoring...
