### ISSUE TITLE
Which font weights to import for standard project?

### ISSUE THREAD

**Issue by abrambailey** [twbs/bootstrap#26993]
I am adding a font from Google fonts and I want to ensure coverage of all the font-weights used by Bootstrap. What are the font weights used by default. Couldn't find here: https://getbootstrap.com/docs/4.0/getting-started/theming/#variable-defaults

Also, how do we override the default font weights? Thanks.

**Comment by royklutman** [comment]
https://github.com/twbs/bootstrap/blob/0b5a8d9c981ae70153cdd64b250a3d9e53014422/scss/_variables.scss#L246-L317

These variables show the font-weights used by default:

- 300
- 400
- 500
- 700

**Comment by mdo** [comment]
Previous comment is right—use the variables Sass file. We don't list out each variable in the docs because that's just unnecessary duplication from the source code. We primarily use `300`, `400`, and `500` (making bold text more semibold).
