### ISSUE TITLE
FR: horizontal list-group

### ISSUE THREAD

**Issue by dalu** [twbs/bootstrap#26995]
I searched for previous open issues and found none.

I have a card with "fields" (divs), currently divided by `.row` and `.col-md-8` `.col-md-2`. It looks something like this:

![list-group-large](https://user-images.githubusercontent.com/2694548/43420066-0e56a5f2-9443-11e8-9b6e-8c3fb98cf048.png)

Now when I view that on a xs/sm screen it looks like this:
![list-group-small](https://user-images.githubusercontent.com/2694548/43420251-7c708dbe-9443-11e8-852e-1feb77bda03f.png)

I would be nice to have some kind of horizontal line. So I was searching and sure enough there's the list-group example in cards, but those can't be arranged horizontally. A `.border-bottom-sm-1` doesn't exist either.

I propose that the list-group should receive a horizontal display option, unless you have a better idea.

**Comment by mdo** [comment]
This is essentially the grid with some utility classes, so we'll punt on implementing any new features to create this with a list group.

**Comment by dalu** [comment]
What utility classes?

**Comment by mdo** [comment]
Apologies, we're closing this as a won't fix. There are no plans to implement this feature. Our docs have all the answers for the grid and [utility classes](https://getbootstrap.com/docs/4.1/utilities/).

**Comment by dalu** [comment]
Thanks. Those are not breakpoint-conditional aka I can't say, show border-bottom if viewport is xs or sm.

I'll figure something custom out then.
