### ISSUE TITLE
Docs: popover selector option example broken 

### ISSUE THREAD

**Issue by gricey432** [twbs/bootstrap#26990]
In the docs for popover under the selector option https://getbootstrap.com/docs/4.1/components/popovers/#options it links to "an informative example" https://jsbin.com/zopod/1/edit?html,css,js,console,output however the example is broken.

```
"ReferenceError: $ is not defined
    at zopod.js:10:1
    at https://static.jsbin.com/js/prod/runner-4.1.4.min.js:1:13924
    at https://static.jsbin.com/js/prod/runner-4.1.4.min.js:1:10866"
```

Linux, Chrome

**Comment by Johann-S** [comment]
it seems more related to JSBin than us @gricey432, I did a copy/paste in a CodePen and it works see: https://codepen.io/Johann-S/pen/djJYPb

But we have to use in this JSBin `bootstrap.bundle.min.js` because our Popover needs Popper.js

So we should update this JSBin or change to a CodePen
