### ISSUE TITLE
Modal-Collapse conflict

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#26991]
When I use a Modal both inside and outside a collapse, the second one does not work if the collapse is not shown.
https://codepen.io/alessandrovecchi/pen/pZpPbb

How can i fix it?

**Comment by AlessandroVecchi** [comment]
NB. In my project I use the modal to open the "privacy policy" whenether is needed

**Comment by Johann-S** [comment]
That's because you've twice the same modal, with the same id, see my CodePen: 

https://codepen.io/Johann-S/pen/zLpdZr?editors=1000#0

It works well

**Comment by AlessandroVecchi** [comment]
oops... 😳
