### ISSUE TITLE
Cursor: pointer

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#26998]
`cursor: pointer;` is used for `.btn`, `.close` and some other buttons, but not for `button` and `input[type="button"]` in `reboot.scss`. Shouldn't we also add it there?

Something related: when `cursor: pointer;` is used, the following comment is shown:
```
// Opinionated: add "hand" cursor to non-disabled .navbar-toggler elements
```
I was thinking about making a `$enable-` variable and a mixin instead of this comment, because now people who don't want the hand still have got to override every case.

What's people's opinion on this?

**Comment by Herst** [comment]
Previous discussions can be found e.g. in #24156.
