### ISSUE TITLE
.btn backgrounds

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#27002]
`a.btn` doesn't have a background, `button.btn` has a background (browser default)
See https://codepen.io/MartijnCuppens/pen/pZpxmr

If we add `background-color: transparent;` to `.btn` the 2 elements are rendered the same. We can than also remove this line from the `.btn-outline-*` buttons.

**Comment by patrickhlauke** [comment]
but `.btn` isn't meant to be used in isolation, but only in conjunction with more explicit secondary classes like `.btn-primary` http://getbootstrap.com/docs/4.1/components/buttons/

i guess we *could* normalize this, but it's not the intended use of `.btn` per se

**Comment by MartijnCuppens** [comment]
I know, but if people want to extend the `.btn` functionality, I think the base should always render the same? And if we move the transparent background from the `.btn-outline-*` classes to the `.btn`, we also same a tiny bit of css.

**Comment by MartijnCuppens** [comment]
Hmm, also the `color` is different for `a.btn` and `button.btn`. Maybe we should also fix this? And what color should we use, the default text color or the link color?
