### ISSUE TITLE
Navbar: Collapse incorrectly

### ISSUE THREAD

**Issue by topfyplus** [twbs/bootstrap#27009]
Navbar Collapse incorrectly in Laravel 5.4 
but Laravel 5.6 Navbar Collapse correctly 
when click button has collapse down and collapse up

https://www.picz.in.th/images/2018/08/01/B3Y3ND.gif

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.
