### ISSUE TITLE
why are new navbars so verbose?

### ISSUE THREAD

**Issue by garretwilson** [twbs/bootstrap#27001]
In Bootstrap 3 I had a navbar like this (excerpt of collapsible part):

```java
...
<ul class="nav navbar-nav">
  <li><a href="./#foo">Foo</a></li>
  <li><a href="./#bar">Bar</a></li>
</ul>
```

The `nav` and `navbar-nav` seemed a little redundant. But it gets out of control in Bootstrap 4! Look at this:

```java
...
<ul class="nav navbar-nav">
  <li class="nav-item"><a class="nav-link" href="./#foo">Foo</a></li>
  <li class="nav-item"><a class="nav-link" href="./#bar">Bar</a></li>
</ul>
```

Why do I have to specify that the `<li>` is a `nav-item`? If it's inside a `ul.nav`, then obviously it's a navigation item.

And why do I have to specify that the `<a>` is a `nav-link`? If it's a link inside a navigation item, then of course it's a navigation link.

Why does Bootstrap 4 force me to add extra styles to almost every element on the page? At least Bootstrap 3 could recognize `.navbar-nav > li > a`. Now Bootstrap 4 forces me to make _everything_ explicit. I might as well create my entire site using `<div>`, if I'm forced to add Bootstrap 4 classes to everything.

Why doesn't Bootstrap continue to be clever enough to determine the style of something from its context? Can we bring back the previous functionality, so that my web page can regain some semblance to a plain, semantic HTML page with a few necessary style classes here and there?

**Comment by patrickhlauke** [comment]
Because going by class names, rather than elements, allows authors to use Bootstrap with their own arbitrary markup structures, without forcing them into using a set specific construct. Their own markup may be non-semantic, or it may be non-standard/more complex than what we'd have originally envisaged.
