### ISSUE TITLE
Floating label example has misaligned label due to change of height of inputs

### ISSUE THREAD

**Issue by Ruffio** [twbs/bootstrap#27011]
I was thinking of using the floating label on my website, but it appears to have been changed :-(

4.0 (https://getbootstrap.com/docs/4.0/examples/floating-labels/):
![image](https://user-images.githubusercontent.com/1877612/43541385-9dcea2a6-95ca-11e8-8d1a-8aba81fa8535.png)

4.1 (https://getbootstrap.com/docs/4.1/examples/floating-labels/):
![image](https://user-images.githubusercontent.com/1877612/43541409-aed3056a-95ca-11e8-9281-8265d71e1533.png)

Actually I think that the changes happened when 4.1.3 was released and a fixed height of 38px was introduced as it goes from 50px (calculated) to 38px (set):
![image](https://user-images.githubusercontent.com/1877612/43541755-72be4e44-95cb-11e8-95f2-24f0577d2a24.png)

![image](https://user-images.githubusercontent.com/1877612/43541835-aa1aedde-95cb-11e8-8196-af6b2b2ad80c.png)

**Comment by mdo** [comment]
Thanks!

To recap the other issue, this is because we added fixed `height` to `.form-control` in v4.1.3. Will need to override it here.

**Comment by Ruffio** [comment]
Keeping the standard 38px for input heights, I have come to that these adjustments work nicely:
![image](https://user-images.githubusercontent.com/1877612/43581700-2d080ab8-965a-11e8-870f-527c087e74c7.png)
and:
![image](https://user-images.githubusercontent.com/1877612/43581723-421b1792-965a-11e8-9ab7-ec75ce6c24f5.png)
That results to:
![image](https://user-images.githubusercontent.com/1877612/43581748-5752600c-965a-11e8-971b-ed05d37e43c8.png)
and:
![image](https://user-images.githubusercontent.com/1877612/43581763-61ae3bca-965a-11e8-9231-3d7db08179c1.png)

Use it for inspiration :-)

**Comment by fessor10** [comment]
How do we get back the 50px (calculated) for floating labels?

**Comment by Ruffio** [comment]
Ideally we shouldn't require a fixed/specific height but the code should adjust accordingly to the height of the input/textarea

**Comment by fessor10** [comment]
Yeah, i removed the `height` entirely and got what i wanted. I think i agree with you about not having fixed/specific `height`

**Comment by mdo** [comment]
See the PR where we added the `height` for why: #26820. We need to account for it here by providing a new height.

**Comment by Ruffio** [comment]
@mdo will the fix/adjustment be a part of 4.2?
