### ISSUE TITLE
Detect click on modal background

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27019]
Is there a way we can reliably detect a click on the modal background of the modal component (https://getbootstrap.com/docs/4.1/components/modal/#live-demo) using jQuery? There's not really anything under the usage section for this https://getbootstrap.com/docs/4.1/components/modal/#usage

**Comment by sts-ryan-holton** [comment]
@Johann-S  Which class do I listen for? Could you provide me an example please?

**Comment by Johann-S** [comment]
Thanks @MartijnCuppens 😉
