### ISSUE TITLE
Bootstrap 4 JS not working with Turbolinks 5

### ISSUE THREAD

**Issue by wirelessed** [twbs/bootstrap#27012]
Hi

I've been trying to get the JS working with turbolinks. For example, on first load of the page, modals work fine. But upon going to other pages, $().modal() does not work anymore.

Also tried to do the following but doesn't work
```
document.addEventListener("turbolinks:load", function() {
    global.$ = global.jQuery;
    require('bootstrap');
    console.log($.fn.modal.Constructor.VERSION);
});
```

$().modal() gets exposed to the console but not to the global $ variable.

Anyone managed to get it working with turbolinks?

**Comment by Johann-S** [comment]
Our plugins are available when the DOM ready event is fired.

BTW we cannot help you without a live exemple in a CodePen or JSBin

**Comment by wirelessed** [comment]
Hi,

Thanks for your comment. I actually tried to replicate the issue on JSBin, but I couldn't. Later on, I discovered that PHPDebugBar's JQuery is causing a conflict and causing Bootstrap plugins JS not to bind to JQuery properly. So I think I've found the issue. Thanks again.
