### ISSUE TITLE
Height issue on floating labels

### ISSUE THREAD

**Issue by ChadTaljaardt** [twbs/bootstrap#27023]
- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
**Mac OSX**

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
**Chrome 68 on macOS (Mojave)**

The issue is that the height property is causing issues with the floating element component as found here : https://getbootstrap.com/docs/4.1/examples/floating-labels/

Here is a picture of the error: 
<img width="693" alt="screen shot 2018-08-05 at 19 54 34" src="https://user-images.githubusercontent.com/13891249/43688906-9b6c4de8-98e9-11e8-868a-7a4257e01ad8.png">

Here is the expected result: 
<img width="662" alt="screen shot 2018-08-05 at 19 54 52" src="https://user-images.githubusercontent.com/13891249/43688909-9f6e685e-98e9-11e8-8286-332999c0430c.png">

Removing this line from the input field fixes the issue : 

https://github.com/twbs/bootstrap/blob/6233ea378d1b35e393aa71cf8c83b316f40effd7/dist/css/bootstrap.css#L1814

**Comment by Ruffio** [comment]
This issue has already been registered: https://github.com/twbs/bootstrap/issues/27011

**Comment by ChadTaljaardt** [comment]
@Ruffio Sorry, i didn't see it.
