### ISSUE TITLE
Responsive Spacing

### ISSUE THREAD

**Issue by dustydingo** [twbs/bootstrap#27022]
Being a mobile first framework, I feel that users would get a lot of utility from having spacing functions that are responsive. For example, margin can become 0 whenever the screen falls below a certain width. Otherwise, certain components look awkward without being responsive.

**Comment by florianlacreuse** [comment]
As I understand it, this already exists: https://getbootstrap.com/docs/4.1/utilities/spacing/#notation

> The classes are named using the format `{property}{sides}-{size}` for `xs` and `{property}{sides}-{breakpoint}-{size}` for `sm`, `md`, `lg`, and `xl`.

For example: `mx-0 mx-md-2 mx-lg-3`.

**Comment by dustydingo** [comment]
Thank you so much for this! This somehow missed my notice. These are super helpful.
