### ISSUE TITLE
form inputs with col-xs not working. They are not clickable on xs viewport

### ISSUE THREAD

**Issue by ateeqrgondal** [twbs/bootstrap#27025]
I am using col-xs-6 for form input. But the form in not clickable. I can not click on input box to type something. How can I fix this?
 I am using Google Chrome for windows 12 developer tools mobile devices. It does not work on any device.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

_This is a saved reply._

---

Aside from that saved reply, this is unclear if you're talking about v3 of v4. v4 has no `.col-xs` classes—use `.col` instead. And finally, v3 is no longer supported.
