### ISSUE TITLE
IE11 Form validation: invalid feedback message not removed when input becomes valid

### ISSUE THREAD

**Issue by lazylester** [twbs/bootstrap#27020]
OS: Windows 10
Browser: IE11

Problem can be seen in the bootstrap [online documentation for form validation:](http://getbootstrap.com/docs/4.1/components/forms/#custom-styles), when using the browser/OS combination mentioned above.

1. Trigger the problem by clicking the submit button for the custom styles example.
2. As expected, the invalid feedback message is displayed for empty fields.
3. Start typing text into the "city" field.
4. The border of the field changes from red to green, as expected.
5. But the invalid feedback message remains displayed, incorrectly.
6. Strangely, the expected behaviour can be triggered by mouseenter or mouseleave for the text input.

**Comment by sts-ryan-holton** [comment]
Maybe this helps: https://github.com/twbs/bootstrap/issues/26271 @lazylester

**Comment by lazylester** [comment]
thanks for the suggestion @sts-ryan-holton, however the #26271 issue is related but not the same as the one I'm reporting here. I'm not concerned with the success/failure of form submission here, but with the information presented to the user regarding the validity of form fields.

If you try the sequence of actions in my report on a different browser (Edge, Chrome etc) it behaves as expected, and the feedback message is removed when a value is typed into a 'required' field. Only in IE11 does the message remain, even though the form field is populated and understood by the browser to be valid (b/c the  border turns green).

There are, of course, javascript workarounds possible, but they are workarounds nonetheless, and users who wish to be IE11 compatible will need to deploy them.

**Comment by ffoodd** [comment]
I tried this on IE11 in both Windows 10 and 8.1 with the same behaviour. 

The feedback only disappear when not hovering input anymore. I don't think there's a solution for this, though. I'll check IE11 known bugs.

**Comment by mdo** [comment]
Closing as a stale won't/can't fix for v4. Doesn't apply to v5 either. Happy to reopen and tackle if someone has a fix that can be applied though!
