### ISSUE TITLE
Scrolling event

### ISSUE THREAD

**Issue by gabrr** [twbs/bootstrap#27024]
Make scroll event understand in which section the user is currently seeing, and do an action. It could be make the content fade in, or just colorize a section.
HTML JavaScript

**Comment by mdo** [comment]
If this is a feature request, closing out as a won't fix.

**Comment by Johann-S** [comment]
You can get the `relatedTarget` on the `activate.bs.scrollspy`
```js
$('[data-spy="scroll"]').on('activate.bs.scrollspy', function (event) {
  console.warn('where you are --->', event.relatedTarget)
})

**Comment by gabrr** [comment]
I am very new yet. I have no idea how to insert this code. But I really appreciate your help!
