### ISSUE TITLE
Bootstrap Material design theme suggestion

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27037]
Hi, I love using Bootstrap. Thanks to the components, helper classes and overall community it makes it pretty great to use. However, I've recently wanted to combine something like https://materializecss.com/ with Bootstrap, I feel Bootstrap needs some kind of theme. I was thinking of building my own, essentially a theme that sits on top of Bootstrap which would provide a more material like design, but still allowing people to use the same classes. Is this something Bootstrap happily supports? What do people think of this?

**Comment by ocarreterom** [comment]
Maybe can be implemented a theming system like material2 https://github.com/angular/material2/tree/master/src/lib/core/theming.
I was using it months ago and I love it 😄 .

More refs: https://material.angular.io/guide/theming

**Comment by knoobie** [comment]
DI you check https://fezvrasta.github.io/bootstrap-material-design?

**Comment by mdo** [comment]
The more themes the merrier! We don’t have a place for them inside the core Bootstrap project, but that’s why we have all the Sass maps and variables we do.
