### ISSUE TITLE
navbar-nav-scroll problem iPhone 4s

### ISSUE THREAD

**Issue by rostovsales** [twbs/bootstrap#27032]
navbar-nav-scroll narrows to the width of the screen at Iphone 4s. Elements run over each other. 
Problem at page https://getbootstrap.com/ and https://getbootstrap.com/docs/4.1/examples/blog/

![2018-08-07 21 16 31](https://user-images.githubusercontent.com/32207366/43791590-2fd44d84-9a87-11e8-94bd-a2943ae6acf9.jpg)

![2018-08-07 21 16 21](https://user-images.githubusercontent.com/32207366/43791591-301028b8-9a87-11e8-9ba9-3a1448aa960b.jpg)

**Comment by alecpl** [comment]
What iOS version? I don't think Bootstrap supports anything older than iOS 9. Actually, it says "the latest versions of each major platform’s default browsers".

**Comment by rostovsales** [comment]
9.3.5

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/.browserslistrc

**Comment by XhmikosR** [comment]
Is this an issue? Maybe it was fixed with a dep update?

**Comment by mdo** [comment]
Closing as stale, especially since we're onto v5 which changes browser support. This could've been an issue with the browser versions and some prefixes being missed—I recall some PRs addressing that earlier in v4's development.
