### ISSUE TITLE
V4 - Dropdown menu within accordion

### ISSUE THREAD

**Issue by Bossman1337** [twbs/bootstrap#27039]
This issue looks like it has been asked a couple of times on here but I can't find any solution that works.

Dropdown menus inside accordions are getting cut off..

https://codepen.io/anon/pen/OwrJOj

Any idea's or workarounds?

**Comment by MartijnCuppens** [comment]
It's not the accordion that causes this, it's the table with the `.table-responsive` wrapper. I think you don't need a table for what you're trying to achieve?

**Comment by Bossman1337** [comment]
Thanks for that, it points me in the right direction. I do need the table for this project, thats just an example i posted with 1 column.. Looks like its the `overflow-x: auto;` causing the problem. I'll see what i can come up with as a work around..
