### ISSUE TITLE
hidden-* is missing (isn't equal to introducing d-*)

### ISSUE THREAD

**Issue by icefront** [twbs/bootstrap#27049]
Thumbs down for excluding the hidden-* classes.
The opposite of display: none isn't display:block.
The hidden-* classes will hide all inline, inline-block and other display properties, while the newly introduced d-* classes force display:block.
hidden-* should be reintroduced in my opinion.

**Comment by mdo** [comment]
Your understanding of the display classes is inaccurate. `.d-none`, `.d-inline`, `.d-flex`, etc do not force any other `display` value.
