### ISSUE TITLE
Should validation styles respect input box-shadow settings? 

### ISSUE THREAD

**Issue by z1m1n** [twbs/bootstrap#27040]
https://github.com/twbs/bootstrap/blob/0b5a8d9c981ae70153cdd64b250a3d9e53014422/scss/mixins/_forms.scss#L73

I think if shadows disabled for input, e.g. setting `$input-box-shadow`, `$input-box-shadow` to none, so they also should be disabled on 'input.is-invalid' focus?

**Comment by mdo** [comment]
We still want to encourage proper accessibility, so they stick around less as decoration and more as a usability feature.
