### ISSUE TITLE
use  window.print(); can't see nav element on preview print

### ISSUE THREAD

**Issue by s952787097** [twbs/bootstrap#27051]
OS: Win7
Browser : Chrome, Firefox

use  window.print(); can't see nav element on preview print

who can help me, thanks

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._
