### ISSUE TITLE
Boostrap breaks Google Maps styling

### ISSUE THREAD

**Issue by echoAlexey** [twbs/bootstrap#27065]
![image](https://user-images.githubusercontent.com/3122131/44076810-33bc40e6-9faa-11e8-8902-652eee2d447f.png)

removing box sizing style makes icons appear back, but clearly not the solution. 
```

*, ::after, ::before {
    /* box-sizing: border-box; */
}
```

**Comment by findmind** [comment]
Same for Bulma. Thanks for your tip, setting `box-sizing: inherit` helps.

**Comment by fchiumeo** [comment]
[Box-sizing](https://getbootstrap.com/docs/4.1/getting-started/introduction/#box-sizing)

**Comment by echoAlexey** [comment]
Google Maps team working on fix.

**Comment by echoAlexey** [comment]
fixed by google maps team on their side.
