### ISSUE TITLE
Background gradients not working on docs

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27068]
Just noticed that the Background gradients aren't working on the **Bootstrap 4.1.3** (https://getbootstrap.com/docs/4.1/utilities/colors/#background-gradient). See below image:

<img width="780" alt="screen shot 2018-08-14 at 20 02 14" src="https://user-images.githubusercontent.com/25177538/44112426-fb52adfa-9ffc-11e8-8c39-97925ed2750f.png">

if you highlight over the page, the text is clearly there for the gradients, but they're not showing:

<img width="368" alt="screen shot 2018-08-14 at 20 03 01" src="https://user-images.githubusercontent.com/25177538/44112475-126a0d08-9ffd-11e8-87df-6c2a28e6ce40.png">

Viewing in latest Google Chrome, Macbook Pro 15 inch.

**Comment by mdo** [comment]
The docs mention this is explicitly broken on purpose :). Could try to make that clearer perhaps?

**Comment by sts-ryan-holton** [comment]
@mdo  I'd consider making it clearer. Also, when turning gradients on, the gradients are applied to buttons as well? Can we have it so that we can prevent it from applying to buttons
