### ISSUE TITLE
[Feature Request] Add bg-white-25 & bg-black-25

### ISSUE THREAD

**Issue by JoshuaLicense** [twbs/bootstrap#27077]
#### Add `bg-white-25` & `bg-black-25`

I think it may be useful to have the background transparency classes such as: `bg-white-25`, `bg-black-25`.

Can be used to fade elements onto a background.

#### Screenshots using the classes on an `<input>` element in the dashboard [example](https://getbootstrap.com/docs/4.1/examples/dashboard)
![example-danger](https://user-images.githubusercontent.com/638172/44171164-6cdf9080-a0d1-11e8-801a-df6a8e4bda12.PNG)
![example-info](https://user-images.githubusercontent.com/638172/44171165-6cdf9080-a0d1-11e8-80d5-5f8c7d54a9fe.PNG)
![example-dark](https://user-images.githubusercontent.com/638172/44171246-af08d200-a0d1-11e8-92b5-93601be28089.PNG)
![example-light](https://user-images.githubusercontent.com/638172/44171247-af08d200-a0d1-11e8-8f41-54961ed7158e.PNG)

**Comment by mdo** [comment]
Thanks, but we'll pass on adding these. 25% feels arbitrary, and it'll open us up to folks asking for more.
