### ISSUE TITLE
data-toggle not working when using ids with leading integers

### ISSUE THREAD

**Issue by chadlevn** [twbs/bootstrap#27076]
When using data-toggle, any id with a leading integer doesn't seem to work.
https://jsfiddle.net/urjtepyo/

Using integers in other places of the id doesn't seem to be an issue.

Working example:
https://jsfiddle.net/gpur1sxb/

This seemed to work in bootstrap 4.1.1 but not in 4.1.2,

Operating System: Windows 7 Pro 64bit
Browser: Firefox 61.0.2 (64-bit)

**Comment by JoshuaLicense** [comment]
Element ID's cannot start with a number, as per the [spec](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier).

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit.

Although valid in [HTML5](https://www.w3.org/TR/html5/dom.html#the-id-attribute); jQuery, and `querySelector`, and `querySelectorAll` uses CSS selectors to select elements.

**Comment by Johann-S** [comment]
That's what @JoshuaLicense said, we use native methods to query our elements (`querySelector` and `querySelectorAll`), we made a fix to use `getElementById` when it's possible but it'll be in our next release (4.2)
