### ISSUE TITLE
Update Popper.js to 1.12.4

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#27070]
REF: https://github.com/FezVrasta/popper.js/releases

**Comment by Johann-S** [comment]
We are in 1.14.4 thanks @coliff see: https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L127

**Comment by coliff** [comment]
Oops, sorry I missed that. I saw an older version here:
https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L214
Should that be updated too?

**Comment by Johann-S** [comment]
Oh yes you are right we should update this line too ! Nice catch 😉
