### ISSUE TITLE
No way to restore the default 30px gutter when using negative margin class

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27072]
The new negative margin classes (#26825) allow to change gutters width in responsive. But there is no way to restore the default 30px, since spacing classes are based on rem (16px). I think that this is not a problem, but what do you think?

**Comment by MartijnCuppens** [comment]
> TLDR: adding extra utility classes will generate a lot of css, I don't know if it's worth adding them for this scenario.

Hmm, this is not a simple one. First thing that comes to my mind is to add 2 extra spacers, something like this:
```scss
$spacers: map-merge(
  (
    0: 0,
    1: ($spacer * .25),
    2: ($spacer * .5),
    3: $spacer,
    4: ($spacer * 1.5),
    5: ($spacer * 3),
    grid-gutter: $grid-gutter-width,
    half-grid-gutter: ($grid-gutter-width / 2),
  ),
  $spacers
);
```

But as expected this adds a lot of css:

Bundlesize at this moment:
```
 PASS  ./dist/css/bootstrap-grid.css: 6.73KB < maxSize 7KB gzip 
 PASS  ./dist/css/bootstrap-grid.min.css: 5.91KB < maxSize 6KB gzip 
 PASS  ./dist/css/bootstrap.css: 23.44KB < maxSize 25KB gzip 
 PASS  ./dist/css/bootstrap.min.css: 21.51KB < maxSize 22KB gzip 
```

Bundlesize with suggested `$spacers`:
```
 FAIL  ./dist/css/bootstrap-grid.css: 7.74KB > maxSize 7KB gzip 
 FAIL  ./dist/css/bootstrap-grid.min.css: 6.84KB > maxSize 6KB gzip
 PASS  ./dist/css/bootstrap.css: 24.56KB < maxSize 25KB gzip 
 FAIL  ./dist/css/bootstrap.min.css: 22.52KB > maxSize 22KB gzip 
```

Bundlesize with only `half-grid-gutter` added to `$spacers`:
```
 FAIL  ./dist/css/bootstrap-grid.css: 7.25KB > maxSize 7KB gzip 
 FAIL  ./dist/css/bootstrap-grid.min.css: 6.4KB > maxSize 6KB gzip 
 PASS  ./dist/css/bootstrap.css: 24.04KB < maxSize 25KB gzip 
 FAIL  ./dist/css/bootstrap.min.css: 22.04KB > maxSize 22KB gzip
```

Bundlesize with only `half-grid-gutter` added to `$spacers`, but abbreviated as `hg` (so `.mb-hg` ect classes are generated):
```
 FAIL  ./dist/css/bootstrap-grid.css: 7.2KB > maxSize 7KB gzip 
 FAIL  ./dist/css/bootstrap-grid.min.css: 6.36KB > maxSize 6KB gzip
 PASS  ./dist/css/bootstrap.css: 23.98KB < maxSize 25KB gzip 
 PASS  ./dist/css/bootstrap.min.css: 22KB < maxSize 22KB gzip
```

I personally always override the `$spacers` map and make sure one spacer equals the value of the grid gutter (to add bottom margins in grids) and one class equals the half of the grid gutter (to achieve what ysds mentions in this ticket). For the rest I use spacers that are very specific for each project (these spacers can be a lot bigger, like `80px` for margins between sections). 

Changing the default values of the `$spacers` map now won't be a good idea, but maybe it's something to consider for v5?

@ysds, do you have any suggestions yourself how we could handle this?

**Comment by ysds** [comment]
I changed the `$grid-gutter-width` to `16px` or `1rem` in my project.  We can solve this issue by customizing SCSS like this, I don't think this is a "problem". But, since the [document mentions about responsive gutters](https://github.com/twbs/bootstrap/pull/26825/files#diff-62e25700ddcfdb0ae620729b4d0bf6f0R327), I think it is better to show how to address this issue. 

Plus, the closed issues(#24283, #23999 and more) and [the doc](https://getbootstrap.com/docs/4.1/layout/grid/#grid-options) says: "Use `px` instead of `rem`". I am concerned about responsive gutter width is inconsistent with that.

Why don't we think again about the unit of garters?

**Comment by alejandroiglesias** [comment]
I do think, in my humble opinion, that moving forward to using `16px` instead of `15px` for each side (giving a gutter of `32px`) allows for more flexibility in terms of playing with halving the values and avoiding decimal values as a result. I do vote for 16px/32px gutters. That being said, I don't know if it can be released in v4.

**Comment by hassanbinsafdar** [comment]
will bootstrap 5 use display grid
