### ISSUE TITLE
@bootstrap/schematics

### ISSUE THREAD

**Issue by oleksiipotiekhin** [twbs/bootstrap#27081]
**Describe the solution you'd like:**
Is there a possibility to add **@bootstrap/schematics** for angular? To use `ng add bootstrap` or `ng add @bootstrap/schematics` to combine bootstrap and angular. It will improve integration experience.

**Comment by pkozlowski-opensource** [comment]
This is a duplicate of the existing issue #26456. Let's centralise the discussion in there.

**Comment by oleksiipotiekhin** [comment]
https://github.com/twbs/bootstrap/issues/26456
