### ISSUE TITLE
formnovalidate="formnovalidate" is not respected

### ISSUE THREAD

**Issue by tkapler** [twbs/bootstrap#27083]
bootstrap https://getbootstrap.com/docs/4.0/components/forms/#validation do not respect inputs formnovalidate property (https://www.w3schools.com/tags/att_input_formnovalidate.asp).

Scenario: I do have a form with checkbox "show more options", that just shows more details of the form on click. But after submiting the form, even this checkbox is validated (so made green), what is confusing for a user as there is just this declaration

```
.was-validated .custom-control-input:valid ~ .custom-control-label, .custom-control-input.is-valid ~ .custom-control-label {
    color: #00c9a7;
}
```

proposed solution - add novalidate class for input / label / form-group, and/or check input:not(formnovalidate) (but i guess it would not work for custom elements and labels)

**Comment by wolfy1339** [comment]
Bootstrap uses the `novalidate` attribute to disable the browser's validation and to use their own

**Comment by mdo** [comment]
Think this is safe to close per last comment?

**Comment by rpokrovskij** [comment]
@wolfy1339 Did you miss that `novalidate` works for whole form when HTML's `formnovalidate` works per element?  I think there should be way to exclude some inputs (e.g. custom checkboxes) from .was-validated validation...

**Comment by rpokrovskij** [comment]
@mdo could you reopen this issue considering that `formnovalidate` should work per element as HTML spec required. Or get us additional information why .was-validated should ignore `formnovalidate`  on element?

Such rule is easy to add: 

```
.was-validated .custom-control-input:valid:not([formnovalidate]) ~ .custom-control-label::before,
            .was-validated .custom-control-input:valid:not([formnovalidate]) ~ .custom-control-label::after{
                background-color: green;
            }
```
