### ISSUE TITLE
tab customize "active" and "show"

### ISSUE THREAD

**Issue by imsheng** [twbs/bootstrap#27089]
I hope it will be stronger. can customize "active" and "show" and more.
Example：
`<ul class="nav nav-tabs" id="myTab" role="tablist" tab-active-class="xxxxx" >`

Example2：
```
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" tab-active-class="xxxxx">Home</a>
  </li>
```

**Comment by Johann-S** [comment]
So what you mean is to pass custom active class ?

**Comment by imsheng** [comment]
@Johann-S  yes,  and "show"  and more customization.

**Comment by rahmatalisyahbana** [comment]
Great

**Comment by mdo** [comment]
Closing as a won't fix—we rely on the same active class for all our styling needs. This feels like an unnecessary complication for the component right now.
