### ISSUE TITLE
Add different translations for browse button on custom file input

### ISSUE THREAD

**Issue by emilmuller** [twbs/bootstrap#27084]
The custom-file-label class features an ::after pesudo element where the English text "Browse" is hard coded.

If people are using the lang attribute on the html tag, maybe feature other string values?

E.g.

```
html[lang="no"] {
    .custom-file-label::after {
        content: "Bla igjennom";
    }
}
```

Or, in the documentation, point out that it is possible.

**Comment by mdo** [comment]
Docs on customizing this are available at https://getbootstrap.com/docs/4.1/components/forms/#file-browser.
