### ISSUE TITLE
Remove min-width from .card component?

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27095]
Just browsing through the Bootstrap docs and wondered what the purpose of adding `min-width: 0` to a `.card` would be? I've tried disabling it in the dev tools of Google Chome on Windows and it doesn't appear to break anything. What's the purpose of this and is it technically needed?

```
.card {
    ...
    min-width: 0;
    ...
}
```

I'd class this as a **feature** rather than bug as it isn't broken.

**Comment by MartijnCuppens** [comment]
See https://github.com/twbs/bootstrap/pull/22740#issuecomment-305868106
