### ISSUE TITLE
Dropdown menu in navbar create scrollbar

### ISSUE THREAD

**Issue by fabianobn** [twbs/bootstrap#27105]
- Operating system and version: Ubuntu 16.04
- Browser and version (Chrome, Firefox)

Hello,
I'm going to create a theme for wordpress and use the bootstrap in version 4.1.3.
But on screen larger than 1800 the drop down list in navbar create scrollbar instead of getting floated.

![captura de tela de 2018-08-20 10-36-58](https://user-images.githubusercontent.com/5238462/44343692-08bc2400-a465-11e8-8732-565fd6dec9fb.png)
![captura de tela de 2018-08-20 10-37-14](https://user-images.githubusercontent.com/5238462/44343693-08bc2400-a465-11e8-8efe-11a1af36495a.png)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by fabianobn** [comment]
sorry the mistake is mine
I created a maximum width and put a hidden overflow.
