### ISSUE TITLE
Documentation does not have tables with right-aligned text

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#27107]
The Bootstrap documentation does not include any example with text that is aligned to the right in the column.

This is commonly used in table where you have numbers, example quantity or cost. This can be done by using the `.text-right` class on the `<td>` element. Can also be done using the `<colgroup>` element.

| Item   | Quantity | Cost |
| -------|---------:| ----:|
| Apple  | 8       | $100 |
| Banana | 20        |  $50 |
| Carrot | 300      |   $1 |

**Comment by mdo** [comment]
I don't think we need an example of this—this is an application of text alignment and not something unique to the project's CSS.
