### ISSUE TITLE
Tooltip placement is wrong when body has horizontal scroll

### ISSUE THREAD

**Issue by zolototrubova** [twbs/bootstrap#27106]
Tooltip placement calculation are wrong when "body" has horizontal scroll and element is located outside the screen.
https://plnkr.co/edit/lGT1uHdvWUKc1Hm1uQRc

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.
