### ISSUE TITLE
support native es6 module loading

### ISSUE THREAD

**Issue by rpokrovskij** [twbs/bootstrap#27119]
Bootstrap 4.3  (budnle from dist folder) fails when global is null.

From sources:
```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('jquery'), require('popper.js')) :
  typeof define === 'function' && define.amd ? define(['exports', 'jquery', 'popper.js'], factory) :
  (factory((global.bootstrap = {}),global.jQuery,global.Popper));
}(this, (function (exports,$,Popper) {...});

```
There `this` from next line can't be null since we will get an excpetion on `global.bootstrap = {}`

And there are situations when `this` can be null during loading e.g. importing using native module support:

 ```
<script type="module">
            import Popper from "./js/popper.js"; // esm version
            window.Popper = Popper;
            import "./js/bootstrap.js"; // TODO : error
            // expected : window.bootstrap created , plugins attached to jquery etc.
</script>
```

Check sources of jquery. They support this new type of loading by checking (this==null)?window:this.

**Comment by Johann-S** [comment]
About that we should ship an ESM version of Bootstrap

**Comment by rpokrovskij** [comment]
It seems it was rollup problem
Now when you have updated rollup.js code looks like
```

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('jquery')) :
  typeof define === 'function' && define.amd ? define(['exports', 'jquery'], factory) :
  (global = global || self, factory(global.bootstrap = {}, global.jQuery));
}(this, function (exports, $) { 'use strict';
```

so there we have global = global || self

**Comment by Johann-S** [comment]
Hmm yep, that's why I think we should ship an ESM version of Bootstrap not just UMD

**Comment by KayakinKoder** [comment]
Sorry to interject, but does this mean bootstrap can't be built with an ES module bundler like Rollup?

**Comment by Johann-S** [comment]
Hi @KayakinKoder absolutly not, Rollup or Webpack prefer ESM build but if there is no ESM build they use the UMD one (for Bootstrap) 😉 

BTW this issue is solved by: https://github.com/twbs/bootstrap/pull/28386

And will be in our v5
