### ISSUE TITLE
RTL version issue  border-top-right-radius:0 into border-top-left-radius:0

### ISSUE THREAD

**Issue by allaghi** [twbs/bootstrap#27122]
Hello everyone,
I am working on RTL version of bootstrap . I just want to know where I can find
 `input-group>.custom-select:not(:first-child), .input-group>.form-control:not(:first-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}`
to change it from border-top-right-radius:0  into border-top-left -radius:0 and so on

**Comment by MartijnCuppens** [comment]
Hi @allaghi,

You can find it here: `scss/_input-group.scss`, line 43-47:
https://github.com/twbs/bootstrap/blob/da717b03e6e72d7a61c007acb9223b9626ae5ee5/scss/_input-group.scss#L43-L47

**Comment by allaghi** [comment]
Thank you so much @MartijnCuppens
