### ISSUE TITLE
Floating label stay at empty input position browser preload input 

### ISSUE THREAD

**Issue by munzirstudio** [twbs/bootstrap#27121]
Hi

When browser preload input (saved username & password) at floating label input, it seem the placeholder still visible:
![image](https://user-images.githubusercontent.com/4507016/44517274-daa34200-a6f9-11e8-84e5-0afd6d0daf34.png)

only after the input is focused/clicked the label move to it top position:
![image](https://user-images.githubusercontent.com/4507016/44517378-18a06600-a6fa-11e8-8cc8-9e5338077949.png)

Thanks

**Comment by mdo** [comment]
This has been open for quite awhile, and I'm not a daily Chrome user, so I apologize for that. Is this still an issue for folks? Does #30449 make a difference at all?

**Comment by eduardogoncalves** [comment]
Hi @mdo, I fixed this on #31948

**Comment by eduardogoncalves** [comment]
@mdo I think this can be closed.
