### ISSUE TITLE
RTL Official support

### ISSUE THREAD

**Issue by Alirezamohammadi** [twbs/bootstrap#27123]
Hi, Does the Bootstrap developers team intend to add right-to-left support for this project?
Unofficial tools are mostly out of dated or don't work properly. A great community of bootstrap users with right-to-left languages (like Persian, Arabic & ...) are facing this problem for several years. please pay attention to us 😥 .

**Comment by alecpl** [comment]
Duplicate of #24807.

**Comment by Alirezamohammadi** [comment]
@alecpl Yes that's right, I see had seen this issue before but no clear answer was given, so I opened a new issue.

**Comment by mRizvandi** [comment]
RTL and LTR version:
https://github.com/mRizvandi/AryaBootstrap/blob/master/ReadMe.En.md
