### ISSUE TITLE
Double border on .list-group-item when followed by .card-footer

### ISSUE THREAD

**Issue by royklutman** [twbs/bootstrap#27125]
When using a `.list-group .list-group-flush` in a card followed by `.card-footer`, the list last list group item does have a border, so basically this is not being applied: https://github.com/twbs/bootstrap/blob/da717b03e6e72d7a61c007acb9223b9626ae5ee5/scss/_list-group.scss#L100-L104

It is however correctly applied when followed by a `.card-body`, as supposed:

![image](https://user-images.githubusercontent.com/14876024/44582343-9ff4e480-a7a1-11e8-8b06-cacd111b9c9e.png)

CodePen to reproduce:
https://codepen.io/anon/pen/PdPxgG?editors=1000

**Comment by nitishchopra92** [comment]
Hi @royklutman ,  It can easily be achieved by adding a bootstrap class "border-bottom-0" with last anchor tag that contains class "list-group-item list-group-item-action". I have create a sample of this at https://jsfiddle.net/25nitish/6az7m5e1

**Comment by royklutman** [comment]
Yes I know this would be a workaround, but the `.list-group-flush` is supposed to remove the bottom border from the last `.list-group-item`, and it isn't at the moment.

**Comment by royklutman** [comment]
The culprit was the margin-bottom on following line: https://github.com/twbs/bootstrap/blob/da717b03e6e72d7a61c007acb9223b9626ae5ee5/scss/_list-group.scss#L56-L59

Simply removing this line fixes this issue, see this CodePen: https://codepen.io/anon/pen/GXpajd?editors=1000#0
