### ISSUE TITLE
Add `justify-self` to flex utilities

### ISSUE THREAD

**Issue by ocarreterom** [twbs/bootstrap#27141]
Could be useful to have a `justify-self` utility in the same way that `align-self`.

https://github.com/twbs/bootstrap/blob/e57a2f244ba8446fffe71847e6a58b18f7b2d541/scss/utilities/_flex.scss#L44-L49

**Comment by MartijnCuppens** [comment]
Hi @ocarreterom,
I don't know if this is really necessary, you can use the margin utility classes to achieve this.

**Comment by derhintergrund** [comment]
@MartijnCuppens is right.

Plus it won´t work on flexbox items:

> In flexbox layouts, this property is ignored (more about alignment in Flexbox)

[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self)

But you can  use the margin utility classes to position items horizontal.

**Comment by mdo** [comment]
Skipping on this then, thanks y'all!

**Comment by Arturace** [comment]
Would be nice to have this in v5, considering the more common use of css-grid. But from what I saw, v5 doesn't do anything with css-grid, so it might not have any value for the framework.
