### ISSUE TITLE
Modal closes on any click within it

### ISSUE THREAD

**Issue by lcsqlpete** [twbs/bootstrap#27140]
I have a page with several modals on it each containing a form.  One of them closes as soon as I click anywhere within it (note, not on the backdrop but inside the modal itself).  The other all work correctly and only close when I click the close button.

The page can be viewed at www.celticsociety.org/Newwebsite.  Click the green "Submit your event" button to display the modal.

This is using Chrome 68.0.3440.106 on OSX 10.13.6.  The page was generated using Bootstrap Studio using the Materia theme from Bootswatch.

**Comment by danijelGombac** [comment]
Remove data-toggle="modal" and data-target="#submitEvent" from the modal.

**Comment by lcsqlpete** [comment]
Whoops, my bad, sorry!
