### ISSUE TITLE
Validation feedback icon issues

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27142]
I noticed that there are three issues about validation icon.

**First issue:**
The icon hides behind scrollbar when a textarea has very long text.

![image](https://user-images.githubusercontent.com/4065765/44709163-e28d2880-aae3-11e8-86d4-9aa03766a906.png)

**Second issue:**
`<select class="form-control">` show icon.

![image](https://user-images.githubusercontent.com/4065765/44709386-719a4080-aae4-11e8-848d-c6c37801a47c.png)

In [the docs](https://github.com/twbs/bootstrap/pull/26824/files#diff-de50c25d3ce7f70d19229665020d03aaR772):

> Background icons for `<select>`s are only available with `.custom-select`, and not `.form-control`.

and @mdo [commented](https://github.com/twbs/bootstrap/pull/26824): 

> Only applies to textual inputs and textareas with `.form-control` and selects with `.custom-select`

but icon is appeared. That is expected?

**Third issue:**
`<select class="custom-select" multiple>` doesn't show icon.

![image](https://user-images.githubusercontent.com/4065765/44709632-10bf3800-aae5-11e8-9f8d-b0905fca9d7e.png)

[All demo](https://codepen.io/anon/pen/LJZxgm)

**Comment by MartijnCuppens** [comment]
I'm afraid this would be something we can't just fix with CSS.

**Comment by mdo** [comment]
Custom select without `multiple` attribute could maybe be fixed. Scrollbar on the `<textarea>` is tougher, too. And a multiple `<select>` is probably out too because it'd be hidden with a selected `<option>`'s background I think?

**Comment by ysds** [comment]
It is easy to remove the feedback icon of both `<textarea>` and multiple `<select>`. My only concern is consistency.

**Comment by mdo** [comment]
Yeah, I think the best bet here is to remove them for now. We can possibly revisit with a fresh approach in v5. Let me know if you have any thoughts on that @ysds.

**Comment by MartijnCuppens** [comment]
I wouldn't remove it for `<textarea>` and `<select>` because this isn't an issue for MacOS.

**Comment by mdo** [comment]
Do we change the positioning then, or try some CSS hacks to target Windows?

**Comment by MartijnCuppens** [comment]
Shifting the icon a bit to the left looks weird if the scrollbar is not present. I wouldn't go for CSS hacks for windows, since it is also possible to always show your scrollbar in mac (see for example: http://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/). Not sure how to continue with this one.

**Comment by pcodedviral** [comment]
just use given js in wich you need make diffrent background image for **scrollble textarea**

http://jsfiddle.net/qKNXH/

thanks.

**Comment by ysds** [comment]
I have no idea to solve this problem by CSS only while maintaining the current HTML structure. It would definitely requires a wrapper element.

**Comment by MartijnCuppens** [comment]
@pcodedviral, our css should work independent of js, so we can't use those techniques, thanks though.

Like @ysds mentioned, I don't think there's a way to get control of this with our current HTML structure.

**Comment by mdo** [comment]
Thinking we close this as a won't/can't fi?. The select issue has been fixed in v5 with #28450 and there's still some improvement to be done there.

**Comment by MartijnCuppens** [comment]
This is a _can't fix_ indeed

**Comment by Ragavendhran-N** [comment]
Can't we just modify the background-position style to comfortable values.
