### ISSUE TITLE
Add the copyright notice to the _functions.scss file

### ISSUE THREAD

**Issue by RichDeBourke** [twbs/bootstrap#27151]
It would be nice to have the copyright notice in the _functions.scss file.

When using the customizing Sass option for Bootstrap ([importing ](https://getbootstrap.com/docs/4.1/getting-started/theming/#importing)just the needed parts), the copyright notice isn’t automatically added to the resulting css file. The copyright notice is in bootstrap-grid.scss, bootstrap-reboot.scss, and bootstrap.scss, but none of those files are imported when picking just the parts that are needed. If the copyright notice was added to the _functions.scss file (which is required for all Sass compilations), then the copyright notice would be in all compilations of Bootstrap Sass.

It would be a little easier to have the notice there automatically rather than having to remember to add it manually to the Custom.scss file for each new project.

**Comment by XhmikosR** [comment]
Actually, I was thinking about this the other day.

**Comment by XhmikosR** [comment]
But I'm not sure it would work right if we added it there. It wouldn't be on the top of our files.

**Comment by XhmikosR** [comment]
Unless maybe we had the license header to a separate include? And we included that first.

**Comment by RichDeBourke** [comment]
If the copyright string (/*!  * Bootstrap…) is at the top of _functions.scss, which is imported first, the copyright notice will be near the top of any complied code, subject to whatever is before the @import statements in the calling file – I just have a bunch of variable settings (my files are imported after all of the Bootstrap files), so the copyright would be first in my case.

I'm guessing that so long as the copyright is referenced somewhere in the compiled CSS file (it doesn't have to be first), it meets the spirit and the letter of the MIT license.

**Comment by RichDeBourke** [comment]
If the copyright string (/*!  * Bootstrap…) is at the top of _functions.scss, which is imported first, the copyright notice will be near the top of any complied code, subject to whatever is before the @import statements in the calling file – I just have a bunch of variable settings (my files are imported after all of the Bootstrap files), so the copyright would be first in my case.

I'm guessing that so long as the copyright is referenced somewhere in the compiled CSS file (it doesn't have to be first), it meets the spirit and the letter of the MIT license.

**Comment by mdo** [comment]
Eh, I don't think this needs to be explicitly in the functions file. If someone's super interested in seeing the change and the team agrees, I wouldn't turn it down. For now though, I'm a pass.
