### ISSUE TITLE
IE Edge Carousel slide animation bounces slightly on completion 

### ISSUE THREAD

**Issue by AlexKa** [twbs/bootstrap#27156]
Similar Issues:
#22291
#21751
#22392

Issue seems **not be be solved** with current version using Microsoft Edge 42.17134.1.0 and BS v4.1.3:
https://getbootstrap.com/docs/4.1/components/carousel/

![microsoft edge 30 08 2018 19_20_52_1](https://user-images.githubusercontent.com/361999/44868334-d394aa80-ac8a-11e8-9774-d3b6a45fbba5.gif)

**Comment by XhmikosR** [comment]
@Johann-S @mdo: [IE11](https://caniuse.com/#feat=css-supports-api) doesn't support `@supports`.

So doesn't this mean that `translateX` is used instead of `translate3d`?

**Comment by XhmikosR** [comment]
Also /CC @MartijnCuppens to chime in.

From a quick look I think the supports check is wrong, but I need someone else to confirm too.
