### ISSUE TITLE
Invalid feedback message are not shows for custom files

### ISSUE THREAD

**Issue by dmolineus** [twbs/bootstrap#27164]
**Description**
I know there is another issue handling some cases of the hidden invalid feedback message (See #23454). As the issue also occurs with the custom form file upload whih is part of bootstrap itself, open a new issue.

The `invalid-feedback` message is not  shown if a custom file upload is in an invalid state. I looked at the selector for displaying it, the `custom-file` is not listed here.

```css
.custom-select.is-invalid~.invalid-feedback, 
.custom-select.is-invalid~.invalid-tooltip, 
.form-control.is-invalid~.invalid-feedback, 
.form-control.is-invalid~.invalid-tooltip, 
.was-validated .custom-select:invalid~.invalid-feedback, 
.was-validated .custom-select:invalid~.invalid-tooltip, 
.was-validated .form-control:invalid~.invalid-feedback, 
.was-validated .form-control:invalid~.invalid-tooltip
```

**Codepen**
Codepen is available here: https://codepen.io/anon/pen/xagBWb

**OS and browser**
I can reproduce issue on Chrome 68, Firefox 61 and Vivaldi 1.15 using manjaro linux.

**Comment by mdo** [comment]
Indeed, we cannot show a message as the input for a custom file form element is within another element. The adjacent selectors do not allow us to target an element outside the parent. The supported elements list for the validation styles is at https://getbootstrap.com/docs/4.1/components/forms/#supported-elements. I imagine we should be more explicit in this list though.

**Comment by mdo** [comment]
Tracking that request in #27169.
