### ISSUE TITLE
Location of document page of media object

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27165]
I often forget the location of the [media object page](https://getbootstrap.com/docs/4.1/layout/media-object/). I don't know why it belongs to the layout category. From [the position of the `@import`](https://github.com/twbs/bootstrap/blob/v4.1.3/scss/bootstrap.scss#L34) in the SCSS, it looks like it is treated like a component. How about moving the page into the components category?

![image](https://user-images.githubusercontent.com/4065765/44942045-4c5b4a00-ade4-11e8-818e-0b994bea573c.png)

**Comment by patrickhlauke** [comment]
I'd agree. @mdo ?

**Comment by andresgalante** [comment]
Since the media object only positions elements in the screen, I'd consider it a layout type of component. On the other hand @ysds is right on pointing out the position on the imports.

I could go either way. (this comment doesn't add anything, to the discussion other than noise and a lose opinion, sorry)

**Comment by ysds** [comment]
@andresgalante Thanks, I understood why the media object page is in layout. Move the doc page or move the `@import` position, either's fine :)

**Comment by mdo** [comment]
I see it more as a layout tool, but I'm open to leaving this issue around to gather some more feedback. It's the first time I've heard any concern around it's position lately.

That said, I also question it's usefulness at this point as a layout tool or component. Our utilities can do all of this for folks with ease. Thoughts?

**Comment by MartijnCuppens** [comment]
I'm leaning a bit more towards the component side. The content in a media object has some correlation, while the grid is more to used separate different components.

But indeed, this component/layout type can easily be replaced with flex utilities: https://codepen.io/MartijnCuppens/pen/OoEvLy
