### ISSUE TITLE
Docs - List Group - Custom Content: Missing or superfluous class names

### ISSUE THREAD

**Issue by philmayfield** [twbs/bootstrap#27162]
In the example for Custom Content in the List Group docs, the example shows the following anchor tag:

`<a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">`

The 'list-group-item' and 'list-group-item-action' classes do not apply the 'display: flex' property, but we've got the flex helper classes 'flex-column' and 'align-items-start'

Suggestion:  Either add the 'd-flex' class to the example, or remove the flex helper classes.

**Comment by mdo** [comment]
Looks like we can nix them entirely.
