### ISSUE TITLE
Restyle close icon's focus style

### ISSUE THREAD

**Issue by raqibjs** [twbs/bootstrap#27163]
This button shouldn't be styled that way when focused (clicked) :(

![image](https://user-images.githubusercontent.com/11327451/44931830-ca880400-ad84-11e8-8b64-cb7b3ccc5578.png)

**Comment by mdo** [comment]
If it's focused, it should have a focus style, no?

**Comment by patrickhlauke** [comment]
until browsers have more consistent support for `:focus-visible` (and we also supplement it with a polyfill https://github.com/WICG/focus-visible), i'm afraid that yes there's no way around this. (on `:focus-visible`, see also https://developer.paciellogroup.com/blog/2018/03/focus-visible-and-backwards-compatibility/)

**Comment by arraqib** [comment]
@mdo Yes of course. But shouldn't we make a better style on focus?

**Comment by patrickhlauke** [comment]
PRs / suggestions welcome

**Comment by TruptiM18** [comment]
Hi @patrickhlauke ,
I went through your blog https://developer.paciellogroup.com/blog/2018/03/focus-visible-and-backwards-compatibility/ .
Can we use the negation pseudo class approach that you have mentioned in the blog for solving this issue?
Thanks

**Comment by patrickhlauke** [comment]
We could, but since support for `:focus-visible` is currently...bad https://caniuse.com/#search=focus-visible ... and we're not adding the polyfill at this point ... it would be rather pointless for now

**Comment by flammea** [comment]
Hi, I can suggest 2 solutions.
1. Font-weight
![image](https://user-images.githubusercontent.com/27705542/56751244-e1e98680-6785-11e9-8c73-ef65127e06d7.png)

2. Underline
![image](https://user-images.githubusercontent.com/27705542/56751312-09d8ea00-6786-11e9-9cf5-89683a4df4b3.png)

**Comment by mdo** [comment]
Unfortunately I don’t think a color change is enough for focus states. Neither is underline, which is synonymous with hover states. Perhaps we could at least revisit the `width` and `height` so it’s a perfect square, and then maybe make use of `border`/`box-shadow` like we use on inputs and buttons?

**Comment by HERBOD7** [comment]
why you set outline none?

**Comment by Demactus** [comment]
Hello, I would like to have a look at it together with a colleague from university. If its still open, updates and suggestion will follow
