### ISSUE TITLE
Bootstrap needs to abandon Jquery

### ISSUE THREAD

**Issue by codenome** [twbs/bootstrap#27170]
Jquery is an incredible tool, Twt Bootstrap even more so. However, to integrate the bootstrap tool in some SPA frameworks has been a challenge, since TWT Bootstrap comes with Jquery.
Most modern SPAs already have incredible DOM access features as well as libraries of consumer services animations. My hironic and affirmative question is:

Why does Bootstrap still use Jquery when it's already possible to do a lot with JS Vanilla? Bootstrap has ceased to be a modern framework.

**Comment by Johann-S** [comment]
Thank you for your feedback, we work on that see: https://github.com/twbs/bootstrap/pull/23586
