### ISSUE TITLE
Modal scrolls down the page

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27176]
The occurrence condition is not clear, but when open a modal, the page may scroll down. It appears to be affected by the window size or length of the page. Often it happens when the window size is small, it may occur even when the window is wide.

Windows 10 / macOS (Show scroll bars - always)
![modal](https://user-images.githubusercontent.com/4065765/45009343-9e99a680-b042-11e8-9ead-8ae211b26b7f.gif)

https://getbootstrap.com/docs/4.1/components/modal/

**Comment by Johann-S** [comment]
I wasn't able to reproduce it on macOS High Sierra with Firefox 61 (thanks to BrowserStack 😄)

**Comment by ysds** [comment]
I tested 4 browsers on Windows 10. It seems to happen only in Chrome.

IE11/Edge/Firefox/Chrome:
![modal-scroll-down](https://user-images.githubusercontent.com/4065765/45285077-2a1ca700-b51d-11e8-9d56-71f7761d3e3f.gif)

**Comment by XhmikosR** [comment]
Maybe try Chrome canary/beta etc and if it still happens then might be a good idea reporting it.

**Comment by edwinfrc** [comment]
is functional no?

**Comment by Joyrex** [comment]
Confirmed in latest Canary build (Version 71.0.3556.1 (Official Build) canary-dcheck (32-bit)) that it still happens.

**Comment by helmutgranda** [comment]
When a scrollbar is present modal ads padding the width of the scrollbar (~15px), every browser is happy to oblige except Chrome...

Measurements are also correct between Chrome Canary/FireFox

https://github.com/twbs/bootstrap/blob/0350858edfd1b27b558281e1df379fe84ed5e41f/js/src/modal.js#L454-L458

I went ahead and removed the padding for testing and in fact Chrome is happy with the 0px padding applied to the body but now all the other browsers complain.

Still looking...

**Comment by JyotirmoyGoswami** [comment]
I am seeing another behaviour in iphone 5s chrome that the modal background gets scrolled when modal overlay is being scrolled. My believe that it happens in all ios phones. 


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16276752/48066107-b2a08680-e1f2-11e8-91ad-9e521aef967e.gif)

**Comment by ysds** [comment]
@JyotirmoyGoswami That is a known issue - 
https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#modals-and-dropdowns-on-mobile
