### ISSUE TITLE
Could someone help me with this please

### ISSUE THREAD

**Issue by audiodk** [twbs/bootstrap#27182]
I am having a problem trying to get this to work right.  Was wondering if someone might be able to help me with this.  http://bans.generationsmc.com/status is the test area I am using.  I am trying to make the progress bar work with the number of people in my server.

This is my code:
`<!DOCTYPE html>

<html>

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Server Statuses</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/gh/leonardosnt/mc-player-counter@1.1.1/dist/mc-player-counter.min.js"></script>
        

        <style>
        
            .progress-bar {
                border-radius: 4px;
            }
        
        </style>

    </head>

    <body>

        <div class="container">

            <p>Network: <b><span data-playercounter-ip="play.generationsmc.com">0</span></b></p>
            <p>Network: <div class="progress-bar" role="progressbar" style="width: 1%" aria-valuenow="1"  aria-valuemin="0" aria-valuemax="64"><small><span data-playercounter-ip="play.generationsmc.com" data-playercounter-format="{online}/{max}">0</span></small></div></p>
            <p>Network: <b><span data-playercounter-ip="play.generationsmc.com" data-playercounter-format="{online}/{max}">0</span></b></p>
            <p>Network is currently <span data-playercounter-ip="play.generationsmc.com" data-playercounter-status>...</span></p>

        </div>        

    </body>

</html>`

**Comment by Wruczek** [comment]
It is not possible with the script you are using. You will need to write your own script that will:
- Get result of `https://use.gameapis.net/mc/query/players/play.generationsmc.com`
- Get the value of `players.online` and `players.max`
- Calculate the percentage of those two numbers
- Set the `style="width: 25%"` of the progressbar, where 25% is your calculated percentage

In the future please don't create issues that are not directly related to Bootstrap. Thanks!

**Comment by patrickhlauke** [comment]
indeed...use StackOverflow or similar instead. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
