### ISSUE TITLE
Custom Select needs Vendor Prefixes in SASS

### ISSUE THREAD

**Issue by wpchannel** [twbs/bootstrap#27181]
Hi,
I'm using Custom Select in BS4 with SASS. When I'm compiling it, it seems that appearance property is no more using: 

`.custom-select {
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
}`

But:

'.custom-select {
	appearance: none;
}'

So Firefox is showing default dropdown select.

**Comment by fchiumeo** [comment]
[bootstrap autoprefix](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L34)

**Comment by XhmikosR** [comment]
http://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#supported-browsers

**Comment by patrickhlauke** [comment]
if you compile it yourself, you need to make sure to use autoprefixer - see https://getbootstrap.com/docs/4.2/getting-started/build-tools/#autoprefixer
