### ISSUE TITLE
Give navbar-brand it's own color variables

### ISSUE THREAD

**Issue by David-Tennant** [twbs/bootstrap#27187]
Currently the only color variables for `.navbar-brand` is the same as navbar dark active links. I am not quite sure if this is a feature request or an issue.

My suggestion would be to add color variables for the navbar-brand

Use case : A theme wants to use text instead of a logo as their brand appears on majority of the page already.

Current : _navbar.scc:250

```
  .navbar-brand {
    color: $navbar-dark-active-color;

    @include hover-focus {
      color: $navbar-dark-active-color;
    }
  }
```

Could there be a seperate color variable that can be overridden if needed?
My current solution below:

 _navbar.scc:250-257

```
  .navbar-brand {
    color: $navbar-brand-color;

    @include hover-focus {
      color: $navbar-brand-hover-color;
    }
  }

```
 _variables.scss:649-651

```
$navbar-brand-color : $white !default;
$navbar-brand-hover-color : $white !default;
$navbar-brand-font-size:            $font-size-lg !default;
...other brand variables
```

**Comment by andresgalante** [comment]
Good catch! I've created a PR using a reference to the old colors so it doesn't produce a breaking change. But it'll allow users to modify the brand color independent to the links.

Thanks for reporting it
