### ISSUE TITLE
Bug when switching carousel item, shows two slides instead of one

### ISSUE THREAD

**Issue by victor192** [twbs/bootstrap#27184]
If you frequently press the slide switch buttons, two items appear instead of one. Here is a screen:
![bug1](https://user-images.githubusercontent.com/20374844/45096265-d2e79280-b128-11e8-80d0-7e397e160d20.png)
If I inspect this item, we'll see:
![bug2](https://user-images.githubusercontent.com/20374844/45096266-d3802900-b128-11e8-9943-533d76b46288.png)
You can see that bootstrap adds two `active` classes, although initially this class is set only for the first record. He does not seem to have time to remove it from the previous slide. And why in the visible, the item is added two `row`, although there must be one.

I repeat, this bug occurs if you switch slides too often. Seen on all browsers. Is it a bootstrap bug or am I doing something wrong?

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by victor192** [comment]
You can see it on homepage. URL: https://blockchair.com/

**Comment by Johann-S** [comment]
We cannot debug your entire app, that's why we asked for a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by victor192** [comment]
I created an example here: http://jsfiddle.net/x1hphsvb/9518/ If you start switching slides too often, you will see that two `row` will be in the same item

**Comment by Johann-S** [comment]
I'm not able to reproduce it on your JSFiddle 😟
BTW you added two times `bootstrap.min.js` and you use a pretty old version of Bootstrap (our latest release is 4.1.3)

**Comment by Johann-S** [comment]
Which buttons do you press ?

**Comment by AliSinaSaemi** [comment]
Hello,
I checked your code @victor192 and there was no bug or problem in it even showing it in the firefox.
![1](https://user-images.githubusercontent.com/20682029/45906093-c25d3a80-bdff-11e8-98c2-df367be395b8.jpg)
However, I recognize a delay of switching slides when i launched your code in firefox browser.
If you did not solve your problem just let us know and give us more information.

**Comment by XhmikosR** [comment]
Seems to work fine here also.

**Comment by FlexIDK** [comment]
I'm reply this "bug" with jquery 1.7.1 (very old lib). In 1.12.x, 1.9.x, 3.x -  can't reply.

**Comment by ghazaleheravi** [comment]
I have this problem too, I was looking for the reason and got here, did you find a reason?
