### ISSUE TITLE
Static Code Analysis Findings

### ISSUE THREAD

**Issue by codeanalysis9876** [twbs/bootstrap#27198]
Key Management:   Hardcoded Encryption Key - At Line: 1896 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
--
Key Management: Hardcoded Encryption Key   - At Line: 1958 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 1959 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2054 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2055 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2255 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2260 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2261 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2376 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2378 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2380 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2382 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2384 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2385 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2388 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2390 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2434 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2436 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2438 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2440 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2442 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2443 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2445 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2447 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2491 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2493 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2495 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2497 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2499 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2500 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2501 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2503 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2717 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Key Management: Hardcoded Encryption Key   - At Line: 2737 of File:   processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Insecure Randomness - At Line: 206 of   File: processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Insecure Randomness - At Line: 2090 of   File: processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js
Insecure Randomness - At Line: 6415 of   File: processes/Server/WebContent/lib/angular-ui/ui-bootstrap-tpls-1.2.5.js

**Comment by fchiumeo** [comment]
wrong repo
https://github.com/angular-ui/bootstrap
