### ISSUE TITLE
Collapse not hiding when parent set from JS

### ISSUE THREAD

**Issue by HACKHERS** [twbs/bootstrap#27200]
Collapse not hiding other elements with the same parent when they are initialized from JS.

jQuery element: http://jsbin.com/puhoyexiti/0/edit?html,js,output
Selector: http://jsbin.com/doyixohula/1/edit?html,js,output

It's working with `data-parent`: http://jsbin.com/zoqizukuvu/1/edit?html,js,output

- Windows
- Chrome (lastest)

**Comment by Johann-S** [comment]
Hi @HACKHERS,

That's because of this line: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L130

We have to change that check, I'll push a PR soon to fix that !
