### ISSUE TITLE
Collapse animation is not working on Mobile

### ISSUE THREAD

**Issue by sonphnt** [twbs/bootstrap#27207]
Hi Everyone,

I realized that collapse class is not working with animation on Mobile. I tested with Safari and Chrome. Is this a bug or it works as intended?

https://getbootstrap.com/docs/4.1/components/collapse/

Access the link above on Mobile and see Collapsible panel has no animation. Even though it works fine on Desktop.

Thanks

**Comment by sonphnt** [comment]
Hi @Johann-S  . Yes It works with Chrome on Iphone 6s my mistake but not with Safari. I tried in browser private mode as well. Can we have a look at Safari ?

**Comment by sonphnt** [comment]
@Johann-S  Thanks for your test. I can see my coworker iphone 6 works fine as well. Have no idea what wrong with my phone.

**Comment by eberhapa** [comment]
I actually have the same issue now. I figured out that the animation isn't working if accessibility reduce motion is active on iOS. But why?
