### ISSUE TITLE
Tab not chaning tab-pane when element id attribute is a UUID.

### ISSUE THREAD

**Issue by JRSofty** [twbs/bootstrap#27208]
Issue occurs on Windows 10 x64 Desktop, testing with Firefox 62 (64bit) using Bootstrap 4.1.3 (Tests with Bootstrap 4.0.0 does not show this problem).

The problem is that when using UUID or GUID for id attributes for the tab-pane of the tab functionality the change in the tab itself occurs but the tab pane is not changed. No messages are logged in the browser console. The classes "show" and "active" do not appear for the tab-pane with the provided id. 

Use of shorter id names does seems to work. 

When tested against the Bootstrap 4.0.0 version the problem did not occur, and UUID/GUID could be used for element id. 

I have attached an index.html file (zipped) that shows the failing functionality with version 4.1.3 using the libraries from the CDN. Problem seems to also appear using version 4.1.2. However, version 4.1.1 works as expected.

[index.zip](https://github.com/twbs/bootstrap/files/2368284/index.zip)

**Comment by Johann-S** [comment]
We added some information about what's a valid selector with Bootstrap see: https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/getting-started/javascript.md#selectors and https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

But maybe we shouldn't catch the error and return `null` [here](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js#L86) to allow user to understand why their code fail 🤔 

What do you think about that @XhmikosR ?

**Comment by JRSofty** [comment]
Ah, so basically my problem is that the id attribute starts with a digit, and if I were to change my code slightly to provide a character before the UUID/GUID then the functionality should work as expected, correct?

Nice to know, shame there's not a validation for id attributes that would have told me that my id values were invalid. 

Thanks for the info, I will make some changes to test that this will fix my problem.

**Comment by XhmikosR** [comment]
Well, hiding the error isn't nice for sure. This issue keeps popping up and it will keep doing so because it was a breaking change which admittedly we didn't think of it right.

**Comment by Johann-S** [comment]
Yes that's, right but the error is pretty explicit and will help folks to understand what they did
