### ISSUE TITLE
Sass precision documentation

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27201]
It seems we are using precision: 6 for node-sass, while its default is 5. Shouldn't we document this in the theming page and/or somewhere else?

/CC @mdo @andresgalante @MartijnCuppens

**Comment by andresgalante** [comment]
Do we really need the adding character? would it make any difference if we just reduce it to 5?

**Comment by XhmikosR** [comment]
I guess this was chosen on purpose at some point. /CC @mdo

**Comment by MartijnCuppens** [comment]
This was probably done to prevent some rounding issues.
See https://codepen.io/MartijnCuppens/pen/bxvNPV (5 digits):
![image](https://user-images.githubusercontent.com/11559216/45357900-12e6c380-b5c8-11e8-83ec-c8b917d03544.png)
And https://codepen.io/MartijnCuppens/pen/gdebVY  (6 digits):
![image](https://user-images.githubusercontent.com/11559216/45357924-2a25b100-b5c8-11e8-9efc-ed8c14fb5817.png)
