### ISSUE TITLE
Opening dropdown-menu-right dropdowns can cause horizontal overflow

### ISSUE THREAD

**Issue by samcic** [twbs/bootstrap#27212]
Occasionally, opening a `dropdown-menu-right` on "small" viewport sizes can cause horizontal overflow after certain sequences of actions involving scrolling and opening multiple dropdowns.

- Operating system and version: **Windows 10, Android**
- Browser and version: **Chrome, Version 69.0.3497.81 (Official Build) (64-bit)**
- [JS Bin](https://output.jsbin.com/durobafibe)
- Repro video: http://recordit.co/iWFsbXtqNz

Repro steps:
1. Bring up Chrome DevTools and use the device toolbar to set it to "mobile" size
2. Refresh the page
3. Click on the first dropdown button (but do NOT close it)
4. Scroll down to the second dropdown button
5. Click on the second dropdown button (but do NOT close it)
6. Scroll back to the first dropdown button
7. Click on the first dropdown button again. Here the page width increases (i.e. horizontal overflow) as shown in the video. This is clearly unexpected.

I was not able to reproduce this on Firefox or Edge.

**Comment by Johann-S** [comment]
I was able to reproduce it on Chrome too, seems a positioning issue here, as we're dependant of Popper.js you should report this issue to them: https://github.com/FezVrasta/popper.js
