### ISSUE TITLE
Increase clickable area - collapse accordion 

### ISSUE THREAD

**Issue by naemtl** [twbs/bootstrap#27210]
Increase clickable section of accordion. At the moment you must click the anchor text to expand/collapse, and clicking the remaining heading area does nothing.

(I have tried to solve this using an earlier thread where someone was using Bootstrap 4 but from what it looks like the solution given by you is no longer valid with 4.1)

**Comment by andresgalante** [comment]
Hi @naemtl, thanks for reporting this.

The accordion is a composition of different components: a card + a btn.

You could extend the clickable area of the btn  by using utility classes or just adding `btn-block`, would that solve the issue?

**Comment by naemtl** [comment]
Hi @andresgalante, thanks for your reply!

Add btn-block solved it. Thanks so much!
