### ISSUE TITLE
Collapse doesn't work if target/id attribute starts with a number

### ISSUE THREAD

**Issue by daharmon** [twbs/bootstrap#27215]
After upgrading from 4.1.1 to 4.1.2, collapse no longer works if the target/id combination starts with a number. I can provide an example that you can run in codepen. I have tried to paste the full html sample in here but it doesn't display correctly.

**Comment by daharmon** [comment]
[Example Codepen](https://codepen.io/daharmon/pen/aaGjao)

**Comment by alecpl** [comment]
Because it's not a valid ID attribute value. The same issue as in #27208.

**Comment by Johann-S** [comment]
Yep that's because currently we use native methods to query our DOM elements (`querySelector` and `querySelectorAll` for more information about correct selector see: https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/getting-started/javascript.md#selectors
