### ISSUE TITLE
Is Android 4.4+ supported?

### ISSUE THREAD

**Issue by maxkorz** [twbs/bootstrap#27214]
Hi. In `.browserslistrc` I see `Android >= 4.4`, but on page https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/ you say that `Android v5.0+ supported`. 

So, do you support Android >= 4.4?

**Comment by Johann-S** [comment]
We should test that on BrowserStack to be sure, but IMO it should works too

**Comment by coliff** [comment]
For reference, a useful comparison here: https://caniuse.com/#compare=android+4.4,android+67

**Comment by mdo** [comment]
The docs are likely the correct one here—we should be supporting Android 5 and up as far as I know.

**Comment by wolfy1339** [comment]
I think that was left there so things wouldn't break too badly on those older platforms. I remember this being said in a comment in the config files somewhere before

**Comment by XhmikosR** [comment]
@mdo: the call is yours :)

BTW if we decide to leave .browserslistrc as is, I say we add a comment above the Android 4.4 line explaining this choice.

**Comment by XhmikosR** [comment]
OK, let's leave things as is. 4.4 isn't supported, as per our docs

**Comment by maxkorz** [comment]
@XhmikosR I suggest to keep the issue open until `.browserslistrc` is updated

**Comment by XhmikosR** [comment]
We are not going to update it. The prefixes for 4.4 are quite few so if this just helps not looking completely broken why remove it?
