### ISSUE TITLE
Badges in table header columns (<th>)

### ISSUE THREAD

**Issue by deefeloper** [twbs/bootstrap#27224]
I would like to add badge support to table headings, particularly the <th> elements, I use this for indicating wether a column can be sorted and if it is sorted, show which direction and what sort index is.

I am not a frontend developer so I cannot asses if this is even the correct way to try this.

An alternative would be to do this outside of bootstrap, but I like having the idea of a frontend framework which includes all elements needed in a web application

**Comment by mdo** [comment]
You can indeed use badges in nearly any other HTML element. Nothing should be stopping you from placing the badge markup in a table heading.
