### ISSUE TITLE
Wrong row margins set in Standard Bootstrap

### ISSUE THREAD

**Issue by Sebi2020** [twbs/bootstrap#27225]
The negative margins cause the row-container to overflow the container div if you **haven't** specified no-gutters. The content relies in the row container but the row border overlaps the main container. You can see that if you assign some background color to the .row class. If you set the margins of row to zero, no overlap occurs.  You don't have to use negative margins if your cols use paddings (what they currently do).
```html
<div class="container">
    <div class="bg-primary row">
       <div class="col-md-1">
          <img src="https://via.placeholder.com/256x256" width=256 class="img-fluid">
      </div>
      <div class="col-md-11">
         <h1 class=" text-light ">Some title <small class="text-white-50">Some subtitle</small></h1> 
      </div>
   </div>
</div>
```
Reduced Test Case: https://codepen.io/anon/pen/ZMjLxo
OS: Win 10 64 Bit
Browser: Chrome 68.0.3440.106 64 Bit

**Comment by edwinfrc** [comment]
the structure proportional to responsive

**Comment by Sebi2020** [comment]
What do you mean by "the structure proportional to responsive"? It's not off-topic if the header is much wider than the footer of a page because of wrong-alignments.

**Comment by mdo** [comment]
This isn't related to any changes—it's how the grid works.

**Comment by Sebi2020** [comment]
So does it was the design goal to make rows greater than other content if you don't assign no-gutters? Would be much better if rows would behave in a consistent way meaning no-gutters would only affect the space between columns and not the space between the container border. Even you say in your documentation that the negative margin is used to compensate the padding. But that makes no sense because you cannot compensate paddings with negative margins **if you use border-box model** instead of content-box.
