### ISSUE TITLE
eliminate section migration v4 .... reemplace for getting started

### ISSUE THREAD

**Issue by edwinfrc** [twbs/bootstrap#27231]
Before opening:

![feature](https://user-images.githubusercontent.com/10235189/45562071-8544e700-b806-11e8-8c81-d0975142aeb6.png)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by patrickhlauke** [comment]
sorry, but no
