### ISSUE TITLE
Keyboard Accessibility in Modals - SHIFT + TAB should cycle backwards 

### ISSUE THREAD

**Issue by DavidMacDonald** [twbs/bootstrap#27241]
- Operating system and version : All versions
- Browser and version : All versions
- Test case: Launch demo modal and Press Shift+Tab
https://getbootstrap.com/docs/4.0/components/modal/

- Expected Result: When focus leaves first interactive element, it should go to the last interactive element.
- Actual Result: Focus stops on the first interactive element and no further action can be taken with SHIFT +TAB

**Comment by patrickhlauke** [comment]
closing this issue here - tracking the problem in the meta-issue https://github.com/twbs/bootstrap/issues/28481
