### ISSUE TITLE
Use of native javascript

### ISSUE THREAD

**Issue by torresgol10** [twbs/bootstrap#27259]
Go into the possibility in future versions of bootstrap to eliminate the jquery library, I have implemented everything with native javascript as github has done with its platform, it would make the libra of bootstrap less heavy in addition to when it is used in web do not objected to load jquery for the web optimization.

https://githubengineering.com/removing-jquery-from-github-frontend/

**Comment by mdo** [comment]
Well ahead of you with #23586.
