### ISSUE TITLE
Popover content should have the options to work async (function returning a promise)

### ISSUE THREAD

**Issue by yepeekai** [twbs/bootstrap#27266]
Currently, there is no built in support for async content in popover.  There are some implementations on stackoverflow having content ="Loading ...." and then manually changing the content on the promise callback or update data-content and call setContent.  I think this should be handled by the bootstrap library.  [https://stackoverflow.com/a/14560039/413464](https://stackoverflow.com/a/14560039/413464)

**Comment by Johann-S** [comment]
I don't see any interest to add that, as you said you can use `setContent` method, and it's pretty easy to update a Popover content
