### ISSUE TITLE
See if we can use a random port in karma for `js-test-karma*`

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27263]
So that we can run them in parallel again

**Comment by alekitto** [comment]
From the karma [documentation](http://karma-runner.github.io/2.0/config/configuration-file.html):
`If the defined port is already in use, karma will automatically increase its value in steps of 1 until a free port is found.`

I just tried to add `--parallel` option to the `js-test` script and it runs flawlessy.
I saw that a couple of fix were committed to the `karma-runner` repository to fix an "address already in use" issue, maybe was a bug in the runner preventing the parallelization?

**Comment by XhmikosR** [comment]
Hmm, thanks for the info, I didn't know they had related fixes.

I will try next time after I upgrade the deps and see how it goes.

**Comment by XhmikosR** [comment]
After playing with this a bit, it seems Travis is slower with parallel, but locally it is faster.

So, let's leave it as is now and we can revisit in the future.

**Comment by Johann-S** [comment]
@XhmikosR AppVeyor 👼

**Comment by XhmikosR** [comment]
Yeah, but I can't try it unless an admin links it to the repo...
