### ISSUE TITLE
example dashboard (4.1): sidebar disappears at width below 768 pixels

### ISSUE THREAD

**Issue by jppresents** [twbs/bootstrap#27273]
I have found an issue with this bootstrap example: 

https://getbootstrap.com/docs/4.1/examples/dashboard/

At a content-width of below 770 pixel the *sidebar* disappears complety.
Tested in the latest Chrome Desktop Browse (Version 69.0.3497.100 (Offizieller Build) (64-Bit)).

(Edit: it said navbar instead of sidebar originally)

**Comment by jppresents** [comment]
To clarify, in image one I have marked the sidebar in pink.
This content goes missing (see image 2) if the width goes below 770px.

As far as I can tell there is no button or menu to get it back (without resizing over 770px again).

![sidebar1](https://user-images.githubusercontent.com/6362294/45745599-7f357880-bc01-11e8-94dd-42f2482f5078.png)

![sidebar2](https://user-images.githubusercontent.com/6362294/45745606-82c8ff80-bc01-11e8-8f4e-19bf21f7082d.png)

**Comment by XhmikosR** [comment]
Well that is different from what you initially described ;)

And that's expected from the markup: `col-md-2 d-none d-md-block bg-light sidebar`

@mdo: your call

**Comment by mdo** [comment]
Closing as a won't fix for now. I designed the example this way. Feel free to customize those grid classes and create something different :).
