### ISSUE TITLE
after closing a modal and opening another it displays the previous modal

### ISSUE THREAD

**Issue by ramsesrom** [twbs/bootstrap#27270]
I have to modal both arr trigger by a script but when the event to display another modal it displays the previous close modal

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._
