### ISSUE TITLE
Card Deck Stacks on Top of Eachother in Mobile View

### ISSUE THREAD

**Issue by DanJ210** [twbs/bootstrap#27280]
I've searched for this specific issue and though I've seen topics about decks and columns, I haven't seen this issue. But I'm using the standard way of creating a card deck and it works pretty well except doesn't center itself well so I add a `col` attribute to one of the divs which makes that happen. Works perfectly at any size except when I make it small like mobile size. Here's the code I have to setup the card deck. Below is a screenshot of what it looks like when resized to a mobile vertical view. Is this supposed to be happening?

```html
<transition-group name="fade" class="card-deck">
    <div v-for="item in items" :key="item.id" class="col">
        <div class="card shadow text-center hvr-box-shadow-outset brand-primary mt-3">
```

![bootstrap](https://user-images.githubusercontent.com/16159685/45764927-cc194f00-bc01-11e8-9a0c-25f5f1002ffa.PNG)

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by DanJ210** [comment]
@mdo I have a massive application powered by Vue so it would be a large undertaking to reproduce a demo application in a CodePen type site. I'd also have to create a modified version which includes a datastore different than what's being used or mock somehow. It would take me a large amount of work to create that and I do want to help but I'd fall behind at work. So if that is required to show a bug like above then unfortunately as much as I want to help, this issue will have to persist.

I don't have to use the cards for mobile but when I do and I am on a mobile size, you see the cards stack. Any other size is perfect. So I have to add extra code to change how the cards work when under the "sm" size.

I can take a video showing this in action and paste the code like I have above for displaying the cards. It's just like in the tutorial in W3Schools which is what taught me. The code will show the above, the card deck class and then the cards being generated with the card contents in the middle.

I'm using the bootstrap CDN for 4.1.0. 
Using Chrome Dev at 71.0.3578.20
Using Chrome 69.0.3497.100
