### ISSUE TITLE
Wrong responsive with col-sm-* (missing max-width in `sass-mixins`)

### ISSUE THREAD

**Issue by tlbiz** [twbs/bootstrap#27286]
Replicate:
- open `https://getbootstrap.com/docs/4.0/layout/grid/#sass-mixins` with chrome
- open chrome `toggle device tools`
- choose ipad/ipad pro
- search div with text `.col-sm-5 .col-md-6`
Issue: `.col-sm-5` never affects because there is no `max-width` in responsive media
![screen shot 2018-09-21 at 10 09 26 am](https://user-images.githubusercontent.com/1656191/45858273-c600ab00-bd86-11e8-87d4-2b1d0ca2286f.png)

**Comment by florianlacreuse** [comment]
See https://getbootstrap.com/docs/4.0/layout/grid/#grid-options : **medium** breakpoint start from `≥768px`.

The width in your example is 768px so the `.col-md-6` wins over the `.col-sm-5`.

**Comment by mdo** [comment]
Closed per last comment.
