### ISSUE TITLE
spacing classes for print media

### ISSUE THREAD

**Issue by achtan** [twbs/bootstrap#27287]
hi, 
pls add spacing classes for print media like:
```
m-print-0
m-print-1
...
mt-print-0
mt-print-1
...
p-print-0
p-print-1
...
and so on...
```

**Comment by AliSinaSaemi** [comment]
Hi,
They already made global spacing classes for developers such as mt-0, mt-1, and others
Use global spacing classes I think that'll work for all

**Comment by mdo** [comment]
No plans we add these for print styles. Print isn't really something I feel we should invest our time and energy in with Bootstrap.
