### ISSUE TITLE
<hr> Declared Twice

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#27283]
`hr` is being declared in **/scss/_reboot.scss** first and then again in **/scss/_type.scss**

**_reboot.scss**
```
hr {
  box-sizing: content-box; // 1
  height: 0; // 1
  overflow: visible; // 2
}
```

**_type.scss**
```
hr {
  margin-top: $hr-margin-y;
  margin-bottom: $hr-margin-y;
  border: 0;
  border-top: $hr-border-width solid $hr-border-color;
}
```

I propose we remove the one on **_type.scss** and update **_reboot.scss** to this:
```
hr {
  box-sizing: content-box; // 1
  height: 0; // 1
  overflow: visible; // 2
  margin-top: $hr-margin-y;
  margin-bottom: $hr-margin-y;
  border: 0;
  border-top: $hr-border-width solid $hr-border-color;
}
```

**Comment by morrissey-ingenious** [comment]
The point of `_reboot.scss` is to normalize elements across all browsers, I don't think they should be merged.

**Comment by rafalp** [comment]
@morrissey-ingenious is correct, `_reboot.scss` resets styles across browsers, and `_type.scss` gives the `hr` default bootstrap flavour. If you look deeper, you'll find that there are more elements that have their styles defined both in `_reboot.scss` and elsewhere.

**Comment by XhmikosR** [comment]
Yup, what the other people said above.
