### ISSUE TITLE
Card Columns - hover fails with scrollable card content

### ISSUE THREAD

**Issue by sakthivelsekar33** [twbs/bootstrap#27293]
hover css effects not applied consistently on cards columns with scrollable contents.

In the code pen - https://codepen.io/sakthivelsekar33/pen/aaxLbV

- Resize the pane so that you should see 3 cards per row
- I have applied hover css effect( background-color: red) for the list items
- go to card with title **Card 2** and hover it, you will see a red background
- now on the same card **scroll to the end** of list and hover it - **the hover effects(red background) is not applied** ( if i inspect i could see the css applied in dom but not getting applied until i resize the browser itself)
- this works fine with Card 1

**Bug Background**

- macOS high seira
- Browser chrome Version 69.0.3497.81
- Bootstrap version - 4.0

**Comment by RudyHui** [comment]
I think the problem is because CSS class list-group-item property position that have default value relative.. If you set to static the problem is fixed..

In the code pen - [https://codepen.io/rudyhui/pen/YOmGqy](https://codepen.io/rudyhui/pen/YOmGqy)

**Comment by helmutgranda** [comment]
I recreated your layout with BS layout classes and things seem to be working as expected. It seems to be more of an edge case:

https://codepen.io/helmutgranda/pen/gdVdYr

**Comment by sakthivelsekar33** [comment]
> I think the problem is because CSS class list-group-item property position that have default value relative.. If you set to static the problem is fixed..
> 
> In the code pen - https://codepen.io/rudyhui/pen/YOmGqy

This works good and fix my issue 👍 , can you explain how this change fix the issue?

**Comment by sakthivelsekar33** [comment]
> I recreated your layout with BS layout classes and things seem to be working as expected. It seems to be more of an edge case:
> 
> https://codepen.io/helmutgranda/pen/gdVdYr

I don't see you using card-column class in your code pen and the problem occurs when we use that class.

**Comment by RudyHui** [comment]
Change property position in class list-group-item..
See my codepen at css part..

**Comment by sakthivelsekar33** [comment]
@RudyHui As already said (https://github.com/twbs/bootstrap/issues/27293#issuecomment-425122228) it's working great. Thought of asking why changing position property affects this one?

**Comment by sakthivelsekar33** [comment]
Working after changing list-group-item position css property. 👍
