### ISSUE TITLE
Rename close icon class to btn-close

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#27294]
Imo:
1. `close` name is very generic, but adds a lot of styling and interferes with any use of such word for other purposes. Example: For buttons with icons I often use `btn btn-secondary <icon-name>`, If my icon is named `close` the button will get a lot of unwanted styles. 
2. Close icon's use-case is generally a button, so why not `btn btn-close`?

**Comment by mdo** [comment]
We could make it more specific, but this shouldn’t be a modifier class on `.btn`.

**Comment by mdo** [comment]
Will close this out and track it for v5 since that’s the earliest we could change the class.

**Comment by MartijnCuppens** [comment]
What do you guys think about a more generic name, something we could apply for more buttons which have icons like the navbar toggler button?

**Comment by ffoodd** [comment]
@MartijnCuppens FWIW, [we have a `.btn-icon` in Boosted](https://boosted.orange.com/docs/4.4/components/buttons/) dedicated to this — to ensure we have a square and icon (either from an icon-font, inline SVG or background-image) is properly sized.

Our main example uses an inlined SVG with a `.sr-only` text. Hope it helps!

**Comment by MartijnCuppens** [comment]
I think icon might be too specific, people might add a label like `Menu` to the icon.

**Comment by mdo** [comment]
Revisiting this again, I agree the class name is super generic, but there's an advantage to keeping it as-is for the upgrade path from v4 to v5. Thoughts from @twbs/css-review on keeping it the same?

Also down for other options:

- Rename it and turn it into an inline SVG (putting the class right on the SVG?)
- Rename it and require different markup as an actual `<button>`.
- Leave the name, use background SVG
- Leave it as-is

I believe @ffoodd already spiked out some ideas in #30927 after #27163 was opened. Any other options I'm missing?

**Comment by calvinkarpenko** [comment]
I think it would be worthwhile to make it in line with other "buttons", for the sake of consistency. It would break things, but that's the reason breaking changes are made on major versions. It'll be changed in the documentation as well and anyboody updating to version 5 will, upon finding the close button not working, no dobut check the documentation and realise it has been changed, or will check a changelog.
