### ISSUE TITLE
Horizontal list group feature suggestion

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27291]
I've been playing around the list group component recently in some projects. One thing I'd like to see in **Bootstrap 4.2** is possibly to have a **horizontal list group** or the ability to make any of the list groups provided (https://getbootstrap.com/docs/4.1/components/list-group/#basic-example) horizontal by adding a class. Technically, I don't know if it would be too difficuilt to add. I was playing around in the inspector and changed two things:

```
.list-group {
    // originally flex column
    flex-direction: row;
}

.list-group-item {
    // originally margin-bottom
    margin-left: -1px;
}
```

By making these relevant changes, you'd get the following:

![list-group-horizontal](https://user-images.githubusercontent.com/25177538/45917292-b7d88a80-be6b-11e8-912d-349cf3ff2056.PNG)

And if we remove the `max-width` from the documentation:

![list-group-horizontal-100](https://user-images.githubusercontent.com/25177538/45917302-e6566580-be6b-11e8-871f-df9facb37e10.PNG)

I was thinking we could have a modifier class to the `list-group-*` something like:

`-horizontal`
`-vertical`

Thoughts?

**Comment by bromine355** [comment]
Agreed. I came here to suggest this. You can add flex-direction: row and it almost works out of the box. The corner rounding needs to be handled though.
