### ISSUE TITLE
Problem with tables and display utilities 

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#27307]
see example:
https://codepen.io/alessandrovecchi/pen/yxdKBM

`<th scope="col" class="d-none d-md-block">First</th>`

![immagine](https://user-images.githubusercontent.com/20642463/46022453-e613cf80-c0e2-11e8-8f94-7ae49afc26db.png)

**Comment by InsanityMeetsHH** [comment]
you could use `d-none d-md-table-cell` [ref](https://getbootstrap.com/docs/4.1/utilities/display/)

**Comment by AlessandroVecchi** [comment]
example 2

https://codepen.io/alessandrovecchi/pen/QVXmGd

**Comment by AlessandroVecchi** [comment]
> 
> 
> you could use `d-none d-md-table-cell` [ref](https://getbootstrap.com/docs/4.1/utilities/display/)

(embarrassed)
i'm sorry... you are right!
