### ISSUE TITLE
VM976 bootstrap.min.js:formatted:96 Uncaught TypeError: Cannot read property 'fn' of undefined     at VM976 bootstrap.min.js:formatted:96     at VM976 bootstrap.min.js:formatted:106     at VM976 bootstrap.min.js:formatted:7     at VM976 bootstrap.min.js:formatted:8

### ISSUE THREAD

**Issue by vaishnavkishan** [twbs/bootstrap#27300]
VM976 bootstrap.min.js:formatted:96 Uncaught TypeError: Cannot read property 'fn' of undefined
    at VM976 bootstrap.min.js:formatted:96
    at VM976 bootstrap.min.js:formatted:106
    at VM976 bootstrap.min.js:formatted:7
    at VM976 bootstrap.min.js:formatted:8

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment]
@Johann-S Nowadays, I don't wait for a reply on these. Folks ignore the issue templates, we can ignore their incomplete issues until they follow-up.
