### ISSUE TITLE
4.1.3 + Latest codes and changes + Example Pages + NavBar + DropDown

### ISSUE THREAD

**Issue by PerseusTheGreat** [twbs/bootstrap#27303]
Hi.
I apologize in advance, I'm beginner in English.

Recently, I have downloaded latest changes of **v4-dev** branch, as a local repo. I have updated all node modules (`npm run maintenance-dependencies`), then I have successfully built B.S. (`npm run test`, `npm run docs`, `npm run dist`). After building process, When I was navigating to `_gh_pages\docs\4.1\examples\`, I have found issue about **DropDowns** within **NavBars**.

In 3 examples (navbars, offcanvas, product), **DropDowns** have not worked. When related `anchor` element has been clicked, the browser's console has shown JS Error (`SyntaxError: 'https://example.com' is not a valid selector'`). So, I have reviewed html codes and I have found the value of `a.nav-link.dropdown-toggle[href]` had been set as `https://example.com`. I have set `a.nav-link.dropdown-toggle[href]` to `#` and then **DropDowns** have woked correctly.

What do you think?
Is this a BUG or I have missed some thing(s)?

I am using:
- Windows 10 Version 1803 (Build 17134.286) x64
- Microsoft Edge 42 (EdgeHTML 17)
- Mozilla Firefox 62 (64-bit)
- Google Chrome 69 (64-bit)

Also I have used these as build tools:
- VS Code 1.27.2
- Node 10.11.0 (64-bit)
- NPM 6.4.1
- Ruby 2.5.0-1-x64

**Comment by Johann-S** [comment]
You found a bug in our examples @PerseusTheGreat thanks ! 👍

**Comment by Johann-S** [comment]
BTW feel free to create a PR 😉
