### ISSUE TITLE
disqus component not rendering with Bootstrap v4.1.3 WITH JSF template, it works with Bootstrap v3.3.7 WITH JSF template

### ISSUE THREAD

**Issue by mswdev1823** [twbs/bootstrap#27305]
**Environment**: Windows 10 or Ubuntu 18.04, Chrome v68.0,  Bootstrap v4.1.3, Wildfly Application Server v14.0.1 with Java Server Faces template, https://disqus.com

**Live Test Cases**
PASS - https://mystory.work/test_disqus_bootstrap337_with_JSF_template
**FAIL** - https://mystory.work/test_disqus_bootstrap413_with_JSF_template

PASS - https://mystory.work/test_disqus_bootstrap337_WITHOUT_JSF_template
PASS - https://mystory.work/test_disqus_bootstrap413_WITHOUT_JSF_template

**Comment by XhmikosR** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mswdev1823** [comment]
Attached test files for source code reference
[test-cases-files.zip](https://github.com/twbs/bootstrap/files/2417456/test-cases-files.zip)

**Comment by XhmikosR** [comment]
@mswdev1823: please create a codepen, not share zip files.

**Comment by XhmikosR** [comment]
NVM, just saw the edit.

For one you are not loading jQuery/popper.js.

**Comment by XhmikosR** [comment]
Sorry, pressed the wrong button.

So, try loading jQuery and report back.

**Comment by mswdev1823** [comment]
@XhmikosR  This test case  FAIL - https://mystory.work/test_disqus_bootstrap413_with_JSF_template  is a very reduced test case by design. I had left out Jquery and popper js. For your request, I have added them but the test case still fails.

As I commented (edited) earlier that if I replace the

```
<link rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
		crossorigin="anonymous" />

```
with the following; the test cases passes.

```
<link rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
		integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
		crossorigin="anonymous" />
```


I cannot repdroduce with CodePen. This specific test case (please see the updated title/name) runs on
Environment: Windows 10 or Ubuntu 18.04, Chrome v68.0, Bootstrap v4.1.3, Wildfly Application Server v14.0.1- Java EE8, with Java Server Faces template, https://disqus.com

**Comment by XhmikosR** [comment]
Not sure if it's not reproducible on CodePen. From a quick look IMO you are using the classes wrong. `content row` shouldn't have a `row` there.

**Comment by mswdev1823** [comment]
> From a quick look IMO you are using the classes wrong. `content row` shouldn't have a `row` there.

@XhmikosR You are right that was the root cause. Thank you.
