### ISSUE TITLE
Google audit - vulnerability detected

### ISSUE THREAD

**Issue by GlauberF** [twbs/bootstrap#27302]
## bootstrap 3.3.7
I need to improve my score and security, through google audit, I verified that the library is vulnerable, according to the attached image and I can not migrate to version 4.0.0

![captura de tela de 2018-09-24 18-04-56](https://user-images.githubusercontent.com/11314585/45978605-257ae700-c023-11e8-8c05-bff359f635b3.png)

**Comment by XhmikosR** [comment]
It's a known issue, wait for #27288 .
