### ISSUE TITLE
Popover not triggered on long press on a button in Firefox mobile

### ISSUE THREAD

**Issue by curtisy1** [twbs/bootstrap#27317]
## Operating System:
Android 8.1
## Browser:
Firefox Nightly for Android 64.0.1a
Firefox for Android 62.0.2
## Reduced Test Case:
[Can be found here](https://curtisy1.github.io/demo/bootstrap-popover)
## Expected behavior:
Long pressing a button in mobile browsers such as Chrome opens the popup, which makes sense in my eyes since it's mostly common knowledge that if you long press something on mobile devices, a popup might appear.
This behavior should also happen in Firefox for mobile devices
## Actual behavior:
Long pressing the button does nothing
## Suggested fix:
I'm not sure as the only fix that I can see is listening for specific browser events such as ```touchstart```, however this would probably be a massive change so I'm not fond of it either.. would be better if this is a bug within Firefox that can be identified and temporarily worked around until a fix happens.

**Comment by Johann-S** [comment]
Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by curtisy1** [comment]
> 
> 
> Bootstrap 3 is essentially in maintenance mode as we focus on working on v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

@Johann-S sorry, that was an error on my end. I pulled the wrong version from CDN. The updated version using Bootstrap 4 still has the behavior I described above, so it still applies to v4 as well.

**Comment by Johann-S** [comment]
@curtisy1 can you provide a CodePen with Bootstrap v4 ?

**Comment by patrickhlauke** [comment]
as the control there is triggering an in-page action, have you considered using a `<button>` rather than a link?

**Comment by curtisy1** [comment]
@Johann-S Working fiddle [here](https://codepen.io/curtisy/pen/mGNpXR)
@patrickhlauke Yes, however that seems to have the same effect as using a link. I've updated the fiddle to reproduce said behavior with both a button and a link

**Comment by curtisy1** [comment]
> 
> 
> arguably...it would be bad form to work against a browser's native behavior in this case. if it does, by default, offer users a context menu even for buttons, then we shouldn't prevent that from happening with ugly hacks.

I guess what you're trying to say is that we'd have to find out whether Firefox supports those popovers on mobile at all or not?
What I can say for sure is that they work when clicking the link/button, so I guess the support is there but simply not working for long press.

Whether this is expected behavior or not is ultimately your (respectively Firefox') decision, however I'm in favor of it because it's conformant with native Android browser approaches, as well as Chrome and having it in one but not the other would just look confusing for end-users.

Ultimately, it might very well be the case that this is a Firefox bug causing it, so if I can test that somehow let me know

**Comment by patrickhlauke** [comment]
what i mean is: it's the way Firefox behaves by default (for buttons etc). yes, it's different from how Chrome behaves on Android, but it's Firefox's decision to behave that way. Firefox users will expect it to work (or not work) that way, as that behavior will happen everywhere else (being able to trigger a context menu on form controls/buttons).

**Comment by curtisy1** [comment]
I agree with everything you say, but the question remains: are we actually sure that this behavior is expected on Firefox? If you are sure that it's working as intended, feel free to close this issue. Otherwise, I'd file a bug at Mozzila's issue tracker, to clarify if long pressing should offer a context menu for form controls

**Comment by XhmikosR** [comment]
@patrickhlauke: should we close this/document it or something?

**Comment by patrickhlauke** [comment]
i would say close it, with no need to document as it's standard Firefox behavior.
