### ISSUE TITLE
display datepicker in list-group-item

### ISSUE THREAD

**Issue by Mand** [twbs/bootstrap#27315]
Test on Chrome Version 69.0.3497.81 (Build officiel) (64 bits) and IE 11 (Edge compatibility)

It seems that the datepicker z-index is not set correctly when it is inside a list-group-item which is inside a modal.
It works if we remove the relative position added by list-group-item class but i'm not sure about the impacts

Example :
https://jsfiddle.net/aq9Laaew/235836/

Regards,

**Comment by patrickhlauke** [comment]
That's a problem with jQuery-UI, not with Bootstrap (which doesn't have datepicker or similar custom components).
