### ISSUE TITLE
Form validation - border color change not working in Chrome and Edge

### ISSUE THREAD

**Issue by Petrhol** [twbs/bootstrap#27316]
Form validation doenst work properly in some browsers.
Test on official bootstrap sides
https://getbootstrap.com/docs/4.0/components/forms/#overview
Insert nonsense email and go to next field
Firefox 62.0.2 - border color changed to red
Chrome 69.0.3497.100, Edge 41.16299.15.0 - border color is not changed

OS: Win 10 64 bit

**Comment by patrickhlauke** [comment]
See https://getbootstrap.com/docs/4.0/components/forms/?#how-it-works

Bootstrap doesn't define `:invalid` styles by default, they need to be opted into. What you're seeing in that form is Firefox's own default validation approach, which is different from what Chrome and Edge do. It's nothing to do with Bootstrap's validation styles.
