### ISSUE TITLE
textarea with class="input-group-sm" or "input-group-lg" html attrib row="5" in 4.1.3

### ISSUE THREAD

**Issue by db585** [twbs/bootstrap#27319]
- Operating system and version macOS v.10.14,
- Browser and version Chrome 69.0.3497.100
- [CodePen](https://codepen.io/db585/pen/vzozVg) Bootstrap v 4.1.3 

It works fine in Bootstrap v4.1.1 and 4.1.2
But doen't work in 4.1.3

**Comment by helmutgranda** [comment]
Here is a Pen with 4.1.1 and the same behavior exists:
https://codepen.io/helmutgranda/pen/zJgVRR

**Comment by mdo** [comment]
`.form-control` is a required class.
