### ISSUE TITLE
Cannot set property 'emulateTransitionEnd' of undefined

### ISSUE THREAD

**Issue by miracle0403** [twbs/bootstrap#27326]
I install bootstrap@latest in my node v10.10.0 using termux emulator (Android phone). After installing jquery and popper.js, i got this error

    $$$1.fn.emulateTransitionEnd = transitionEndEmulator;
    TypeError: Cannot set property 'emulateTransitionEnd' of undefined

**Comment by Johann-S** [comment]
Bootstrap need to run in a Browser because we need to access to the `window` object

**Comment by XhmikosR** [comment]
Closing due to lack of reply.
