### ISSUE TITLE
Form input does not inherit font-weight

### ISSUE THREAD

**Issue by brnrd87** [twbs/bootstrap#27327]
If the variable $font-weight-normal is set to a non-default value, e.g. "300", this value is not inherited by text inputs. The computed value of the font-weight property is found to be 'reset' to 400 in the developer tools (Firefox 62.0). When you add 'font-weight: inherit;' to the text input, this is solved. Another solution could be to add a $input-font-weight variable. 

![font-weight](https://user-images.githubusercontent.com/7702839/46132767-3ef87a80-c23f-11e8-8e5c-1369e349feca.PNG)

**Comment by MartijnCuppens** [comment]
The case where font weights of `300` and `400` are available might indeed be a situation where this might come in handy. If we continue on this, we need to make sure we'll also add this for `.custom-select`.

**Comment by andresgalante** [comment]
The user agent in chrome will also reset the font weight to `400`.

I'll fix this.
