### ISSUE TITLE
[v3] navbar-fixed-* don't get right padding on modal open

### ISSUE THREAD

**Issue by iamandrewluca** [twbs/bootstrap#27330]
When opening a modal and there is a vertical scrollbar on body,
body gets added a pading right of scrollbar width and overflow hidden,  
because without it content will move left and right.  

Same applies for `navbar-fixed-top` and `navbar-fixed-bottom`,  
When body has overflow hidden, `navbar-fixed-*` is moving left and right on modal toggle

- Linux 4.15.0-34-generic #37-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- https://codepen.io/iamandrewluca/pen/VEZNdY

**Comment by XhmikosR** [comment]
Fixed in #27331
