### ISSUE TITLE
Gray is tinted blue

### ISSUE THREAD

**Issue by Illiou** [twbs/bootstrap#27332]
Why are the predefined shades of gray tinted towards blue, or more accurately, muted shades of blue?
I feel like this is quite unexpected given their names, and potentially unwanted, at least it was for me. You kind of rely on them being actual gray without having to check.

**Comment by mdo** [comment]
Grays can be cool (often giving a blue-ish tint) or warm (giving a brown/yellow tint). All depends on preference. No plans to change this in our grays at this time.

**Comment by patrickhlauke** [comment]
if this refers to the various `text-black-50` / `text-white-50`, i could see how that would be confusing though (as one would expect those to be based on tints of pure black/white, rather than also skewing towards blue.

**Comment by Illiou** [comment]
@mdo I just think it's a bit dangerous having this as the unmentioned default as many people will base their design on it, mostly without making a conscious decision about what grays they want to have. And while what you said is true, the expectation and definition of gray is being neutral and without color. 

@patrickhlauke These are defined differently, this is about the color variables $gray-x00 and everything that's based on these.

**Comment by patrickhlauke** [comment]
Ah, sorry, you mean the ones here http://getbootstrap.com/docs/4.1/getting-started/theming/#grays

@mdo I understand where you're coming from, but agree with @Illiou that it's, at the very least, confusing/surprising to people. I'll work on at least adding a prominent note there that explains these aren't true neutral greys, but cool greys.

**Comment by mdo** [comment]
Not trying to be combative, but I wanted to make sure we're not reacting to every piece of feedback we receive. None of our colors are their "true colors"—the blue is it's own blue, the green a little yellow-ish, the red a little pink, and the indigo a random smattering of blue and purple. None of these values are locked in stone, and neither are shades of gray. This is the first and only piece of feedback regarding the gray colors that I can recall—we should make a note of it for ourselves, and keep it in mind for the future if others share the sentiment here.

I don't see much value in adding more to the docs—especially in the form of a callout—to explain how or why these exact hex values were chosen.

**Comment by patrickhlauke** [comment]
It's not a hill I want to die on either. But I recall my own surprise when I was looking at a Bootstrap site on another computer with a differently color calibrated monitor and the blue tint on certain elements was obvious, while on my own machine I never noticed and thought it was a neutral gray. And I'd still say the expectation when you see a scale of grays is that they're neutral (the same way you'd also expect "white" to mean `#fff` and "black" to mean `#000`, rather than some off-white or almost-black.

I'd be happy to change the PR to drop the "true" word, and to turn it into just a sentence rather than a callout. But I'd still say it would be good to just mention it in passing, based on my own anecdotal surprise when I discovered the blue-ish tint of what I thought (based on what I saw on my screen at the time, and the name of the color) was neutral grays.

**Comment by Illiou** [comment]
I'm with @patrickhlauke here. I think a sentence noting they are not neutral grays doesn't bloat the docs much while providing people with this information without having to tell this from the Hex codes.

The colors are not set in stone, true, but while it is probably common to change the "colored" colors I don't see many people changing (or even looking at) the grays since for the essential dimension, brightness, many options are already provided. Only some people will think about the temperature dimension and will want to deviate from neutral (which is why I'd argue for neutral grays in the first place but that's your call).
And for every person verbal about some issue there are many more being quiet about it so I would assume more people will benefit from the note in the docs.

**Comment by wrabit** [comment]
My pref is no blue, FWIW, here are the base grays when extending variables:

```
$white:    #fff;
$gray-100: #f9f9f9;
$gray-200: #ececec;
$gray-300: #e2e2e2;
$gray-400: #d4d4d4;
$gray-500: #b5b5b5;
$gray-600: #757575;
$gray-700: #505050;
$gray-800: #3a3a3a;
$gray-900: #252525;
$black:    #000;
```
