### ISSUE TITLE
Add 'new' & 'updated' badges to docs to show what's changed

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27340]
I thought it would be a good idea to add a small badge next to the docs navigation, next to each component/utility etc to show what's new and what's been updated with each new version of Bootstrap starting with 4.2

I think this will help people find new and updated features at a glance, the idea being that these badges could stay around until the next iteration (new major & minor releases).

e.g:

<img width="219" alt="screenshot 2018-09-29 at 14 03 27" src="https://user-images.githubusercontent.com/25177538/46246156-1ca65e80-c3f1-11e8-9a97-91716889b9f9.png">

**Comment by sts-ryan-holton** [comment]
@MartijnCuppens  The release notes absolutely would cover new changes, I was just thinking for those who don't really look at the release notes/Github, but rather just want to quickly see what's new with a visual indicator (a badge next to the component), maybe instead of two types, consider just having a **NEW** badge for new features, or if a component has extra modifier classes, consider then adding an **UPDATED** badge?

**Comment by XhmikosR** [comment]
We could automate it, not sure if it's worth the trouble though.

Anyway, if anyone wants to submit a simple solution, glad to review it.

**Comment by mdo** [comment]
Per last comments, could be cool, but currently not on our radar given the release notes and more.
