### ISSUE TITLE
Upgrading from Bootstrap 3 to Bootstra 4 breaks site.

### ISSUE THREAD

**Issue by DanJ210** [twbs/bootstrap#27355]
I've searched for duplicates.

It's so strange but I have boostrap installed via NuGet package manager in visual studio. It's a simple ASP.NET application. I'm using the UI not the PMC. v3.0.1 is install and if I update to 4.1.3, everything bootstrap stops working. Navbars, datatables stop displaying correctly and I have already updated the datatables. 

Below is a code pen of the simple navbar that completely stops working after updating. No navbar-inverse. Nothing. On W3 schools I don't see anything different than what is already there. 

Also, the codepen doesn't even seem to want to render properly so I'm not sure what I'm not understanding about why this is such a pain. Any guidance would be much appreciated.

https://codepen.io/danj210/pen/rqeEyK

Bug reports must include:

- Operating system and version (Windows,)
- Browser and version (Chrome Latest, Firefox Latest, MS Edge Latest)

**Comment by patrickhlauke** [comment]
moving from bootstrap 3 to bootstrap 4 involves more than just grabbing the latest package. 4 has fundamental changes. see http://getbootstrap.com/docs/4.1/migration/

**Comment by DanJ210** [comment]
Ok thanks. Except I didn't see anything to change with the navbar so I'm not understanding why it would not work as shown.

**Comment by fchiumeo** [comment]
http://getbootstrap.com/docs/4.1/migration/#navs
