### ISSUE TITLE
Custom file input > selected file indication

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#27358]
There is no indication if a file is selected with the custom file input. Should we make a new javascript component which take care of this? 

https://getbootstrap.com/docs/4.1/components/forms/#file-browser

**Comment by Johann-S** [comment]
We suggest in our doc a plugin which handle that see here: https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/components/forms.md#file-browser

**Comment by MartijnCuppens** [comment]
Thanks!
