### ISSUE TITLE
Input in modal lose focus when clicking in scrollbar

### ISSUE THREAD

**Issue by AlexMaguey** [twbs/bootstrap#27364]
I don't know if this is a bug or is the intended behavior but when i click in the modal scrollbar input loses focus. How can i prevent this to happen?

**Comment by bkdotcom** [comment]
it's browser behavior caused by the modal's container having the `tabindex="-1"` attribute.

I suppose an ugly workaround would be to listen for the blur event.  If the modal is still open and nothing within the modal has focus, return the focus
