### ISSUE TITLE
No 'Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by zhyocean** [twbs/bootstrap#27361]
Redirect from 'https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://zhyocean.cn' is therefore not allowed access.

How to solve this problem？？thanks

**Comment by coderzzp** [comment]
i met the same problem...how to reslove?

**Comment by ms29ash** [comment]
Yeah same problem
