### ISSUE TITLE
More font size utilities like `margin` and `padding`

### ISSUE THREAD

**Issue by wxs77577** [twbs/bootstrap#27365]
Most of mobile apps use smaller font sizes, but it's not a good idea to modify the base font size, so shall we add some font size classes?

### Just like `margin` and `padding` utilities
- `m-1`
- `m-2`
- `m-3`

### Font sizes
- `fs-1` - font size level 1, means the smallest font size, maybe 0.7rem (or em ?)
- `fs-2` - font size level 2, maybe 0.8rem
- `fs-3` - font size level 3, maybe 0.9rem

### Better way
- `fs-sm-1` - **smaller** font size level 1 , maybe 0.9rem
- `fs-sm-2` - **smaller** font size level 2 , maybe 0.8rem
- `fs-sm-3` - **smaller** font size level 3 , maybe 0.7rem
- `fs-lg-1` - **larger** font size level 1 , maybe 1.25rem
- `fs-lg-2` - **larger** font size level 2, maybe 1.5rem
- `fs-lg-3` - **larger** font size level 3, maybe 1.75rem
- etc...

> `sm` or `lg` may confuse us. Any other advice?

**Comment by mdo** [comment]
Definitely not going to do responsive versions of utilities here. I've thought about doing `.f1`-`.f6` though to match `.h1`-`.h6`.

**Comment by mdo** [comment]
Closing this out for now as I want to super cautious on adding new utilities.
