### ISSUE TITLE
Deprecate theme-color, gray, color functions

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#27377]
As suggested here https://github.com/twbs/bootstrap/issues/27338#issuecomment-425655377, we can deprecate the `theme-color`, `gray`, `color` functions. The `color` and `gray` functions are not used by Bootstrap and it's easy to remove the `theme-color` dependency. These functions don't really add anything to Bootstrap.

With a small changes we can make Bootstrap independent of these functions and throw a warning like we did here, so we can deprecate them in a next major release:
https://github.com/twbs/bootstrap/blob/f59c2d946c276ccc247a34ccfe6f5063c847306b/scss/mixins/_text-hide.scss#L10-L12

**Comment by XhmikosR** [comment]
Personally I'd say go for this, but perhaps wait for @mdo and @andresgalante to chime in.

We just need to make sure we don't introduce breaking changes in minor/patch releases.

**Comment by mdo** [comment]
I think the expectation I had here was that functions like `theme-color` would generate the different shades of each color, allowing us to easily create a family of one color's shades (e.g., our `$gray-100` through `$gray-900`). I imagine we can nuke these in v5 if we're not using them though.

**Comment by mdo** [comment]
I believe this was resolved.
