### ISSUE TITLE
Centering Bootstrap Tables?

### ISSUE THREAD

**Issue by ProfGold** [twbs/bootstrap#27376]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by ProfGold** [comment]
I have a bootstrap table that is 50% wide (using w-50 and p3) but is left aligned.  Is there a way to center the table while leaving the contents as left aligned?

**Comment by xcartmods** [comment]
Add class mx-auto
