### ISSUE TITLE
Customizable @media tag in scss (wanted for printing)

### ISSUE THREAD

**Issue by dkline** [twbs/bootstrap#27384]
I'm trying to force lg styles for printing, and i'm not seeing an easy way to do that. 

The reason i'm attempting to do this is mostly because chrome seems to always use the sm styles unless I change the `scale` in it's print preview and it's also a bit odd for the layout to change as the user changes the scale.

The only way i've been able to make it work so far is by manually editing the `@media` tags in the compiled bootstrap css. e.g., for sm/md/xl I changed `@media (min-width: 576px)` to `@media screen and (min-width: 576px)`. Then for lg I changed `@media (min-width: 992px)` to `@media screen and (min-width: 992px), print`

I believe the proper way to change this would be to create a custom .scss file, however I don't see a way to edit the media tags the way I want. It looks like they are hard coded in this file: https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_breakpoints.scss

Some potential ways to add this feature:
 - Add scss variables that allow these media tags to be submitted as raw text.
 - Add scss variables that designate which styles have screen and/or print media tags. 
 - Add a single scss variable that designates which grid size should be used for printing.

**Comment by mdo** [comment]
> * Add a single scss variable that designates which grid size should be used for printing.

This would be the path to take, but I'm unsure how to do it. Right now we just have a `@media print { ... }` for our selector.

**Comment by mdo** [comment]
We're likely going to remove the bulk of our custom print styles in v5—far too many issues with the sizing stuff I tried to do in v4. Closing this as a won't fix for now.
