### ISSUE TITLE
.border 

### ISSUE THREAD

**Issue by jospel** [twbs/bootstrap#27387]
Hi, 
I am not sure I am on the right place and maybe it will be silly post.
I am learning bootstrap 4 and I have a problem with border class.
https://getbootstrap.com/docs/4.1/utilities/borders/

**I think there is a mistake in the page**, about Subtractive part because when I try : 
**.border-0** (for example)  It doesn't work.
but if i use  **border border-0**  it does, as it 's explained for color border part.

(note : I am practicing on codepen)

**Comment by pjones235** [comment]
I'm assuming you're not including the leading period when you say it's not working, correct? Also, the point of border-0 is to remove the border for the element...

**Comment by jospel** [comment]
Hello  pjones35, thank you for your time.

When i type .border-0 , indeed i meant class="border-0".
Yes it was bad example as .border-0 is supposed to show nothing.
Let's take another example  , according to the page : 
`<span class="border-top-0"></span>`  is supposed to show an element without the top border.
but they forgot the class border, so it should be : 
`<span class="border border-top-0"></span>`

I was thinking maybe they didn't forget it, coz it's supposed to be obvious ?. but why for the next explanation about color, they  do show it   : 
`<span class="border border-primary"></span>

I think they made a mistake and forgot "border"  and should correct it .
Not a big deal, just wanted to warn.
`
