### ISSUE TITLE
Selection option disabled

### ISSUE THREAD

**Issue by jokohoko** [twbs/bootstrap#27386]
When using select menu's a common standard is to include a disabled selected first option to act as a placeholder. This is visible on page load but needs to be changed by user to be accepted. (and users cannot select this disabled element). 

However in bootstrap the disabled element can be selected without a problem. Thus breaking this principle.

OS: Windows 10 v1709
Browser: Chrome V69
text example: https://codepen.io/anon/pen/YJNgxL

```
<select required>
  <option selected disabled>Select...</option>
  <option>example1</option>
  <option>example2</option>
</select>
vs
<select class="form-control" required>
  <option selected disabled>Select...</option>
  <option>example1</option>
  <option>example2</option>
</select>
<input type="submit"/>
```

I do not have a solution myself yet, but am trying to fix this for a project of mine, (although my solution would be a bodge and i prefer clean solutions).

**Comment by xcartmods** [comment]
No problems in Chrome here - https://codepen.io/xcartmods/pen/wYgZoM

**Comment by jokohoko** [comment]
Ok, cancel that error! the problem appears to be in the device emulator in Chrome.
I am building a web-app and thus am using the device emulator constantly, but in this emulator the disabled is ignored. When testing a live version on my smartphone indeed there is no issue.

Sorry for the false issue report, will search for the chrome issue report location with this message.
