### ISSUE TITLE
Add migration guide section for 4.0 to 4.1

### ISSUE THREAD

**Issue by robbieaverill** [twbs/bootstrap#27385]
Hi team,

As discussed in https://github.com/twbs/bootstrap/pull/25806, there is a small breaking change between 4.0 to 4.1 in that users can no longer use `.collapse.show` classes to indicate that an element should be displayed. The new behaviour is that `.collapse:not(.show)` elements should be hidden, which is a slightly different behaviour.

It would be great it we could note this somewhere in the migration guide: https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/migration.md

**Comment by araphiel** [comment]
Thanks for posting this - I'm running into a variant of this using the accordion.

**Comment by XhmikosR** [comment]
PRs welcome!

**Comment by robbieaverill** [comment]
Happy to make one if someone would be so kind as to point me in the direction of where you'd like it =)

**Comment by mdo** [comment]
If you still want this @robbieaverill, the page you linked to is likely the correct place to put it. For now though, I'm going to close this out as we've never done migration guides for minor releases. Generally speaking, the release notes and blog posts cover everything you need to know about what's new.

**Comment by robbieaverill** [comment]
Thanks @mdo, that's fine. I guess people may find this thread if they run into the issue anyway.
