### ISSUE TITLE
Getbootstrap.com Components Code Formatting

### ISSUE THREAD

**Issue by MarthinusStrydom** [twbs/bootstrap#27391]
Please consider using tabs in your example code to indent, instead of spaces. It's really convenient to be able to just copy and paste blocks of example code, but then one has to spend time formatting to a standard. I think most use tabs, unless I am wrong.

**Comment by Johann-S** [comment]
Hi @MarthinusStrydom,

Sorry but everything in our code base is formatted using spaces, so we won't change for tabs.
That's a huge debate spaces VS tabs see: https://thenewstack.io/spaces-vs-tabs-a-20-year-debate-and-now-this-what-the-hell-is-wrong-with-go/
