### ISSUE TITLE
example.html doesn't replace the whole holder.js line

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27395]
This

```liquid
{{- include.content | replace: 'data-src="holder.js', 'src="...' -}}
```

Matches only the `holder.js` part and not the whole string. As far as I can tell there's no regex support here, so I'm not sure how to proceed.

/CC @m5o

**Comment by XhmikosR** [comment]
Nope, the idea was to replace the whole `data-src=holder.js...` with `src=...`.

**Comment by morrissey-ingenious** [comment]
I think you will need to include a `gem` like this one [https://github.com/sparanoid/match_regex](url)

**Comment by m5o** [comment]
For reference, this https://github.com/twbs/bootstrap/pull/25784#issuecomment-372826444 is the last comment before @XhmikosR continued and did some final changes and merged the PR.

---

If regex dosn’t work out of the box and to make the example html working without a js dependency. What do you think to replace the `holder.js` prefix with `//picsum.photos/`? This would at least create a working image url.

**Comment by XhmikosR** [comment]
I'd even go with a simple SVG too if we can make it work and just pass the fill color, width and height.

**Comment by XhmikosR** [comment]
Not sure what you mean. Embed doesn't have any placeholder images.

**Comment by morrissey-ingenious** [comment]
@XhmikosR there is a sample YouTube video in the embed example that is not replaced by `...` I was thinking that all `src` elements should be replaced with `...` not just the placeholder `data-src` ones.

**Comment by XhmikosR** [comment]
Well, ideally, we could do that. But it's only one case so it's not so important to just use `highlight` manually.

**Comment by XhmikosR** [comment]
@m5o: so do you have any suggestions? Otherwise I guess we'll need to revert back to the plugin.

**Comment by m5o** [comment]
I'm traveling currently and don't have my tech stuff with me. Sorry, bad timing.

* An inline SVG could work, but it won't be a short one-liner if I get the [inline SVG](https://css-tricks.com/lodge/svg/09-svg-data-uris/) correctly. IMHO this creates to much noise into the example markup.
* Probably easiest would be a link to a spacer gif, self hosted (bootstrapcdn?) or hot linked (unsplash)

**Comment by XhmikosR** [comment]
We can wait a bit more, no hurry :)

I already have #27491 open and ready to be merged and to be honest I feel like it's the best solution due to Liquid's lack of regular expression support.

But if we can come up with a simple patch with SVGs, we can decide then which one to merge.

**Comment by XhmikosR** [comment]
We can wait a bit more, no hurry :)

I already have #27491 open and ready to be merged and to be honest I feel like it's the best solution due to Liquid's lack of regular expression support.

But if we can come up with a simple patch with SVGs, we can decide then which one to merge.

**Comment by XhmikosR** [comment]
@MartijnCuppens: any luck with the placeholder SVG solution?
