### ISSUE TITLE
Horizontal collumn ordering

### ISSUE THREAD

**Issue by bryanwillis7** [twbs/bootstrap#27398]
https://github.com/twbs/bootstrap/issues/17882
It was talked about earlier and shrugged off, but this feature should seriously have some deeper consideration. The current card-column solution is ordered in a way that's useless for just about everyone. Vertical ordering pushes old and irrelevant content to the top of the page which, for just about any designer, merchant, or artist is pretty annoying. 

The referenced issue linked above was swept under the rug with the suggestion of just using masonry. But currently masonry has shoddy compatibility with bootstrap 4. A bunch of users, myself included, are unable to get it working at all.

https://github.com/desandro/masonry/issues/1063

I'm sure there are other solutions for this, but with that being said, masonry galleries are so popular among users and ubiquitous across the net, that it seems like a feature bootstrap should provide for properly. I hope you'll consider adding horizontal sorting for a future update.

**Comment by helmutgranda** [comment]
See my comment in quoted thread: 

https://github.com/desandro/masonry/issues/1063#issuecomment-429110236

**Comment by mdo** [comment]
Yup, looks like Masonry works just fine with Bootstrap. Doesn't seem like something we need to worry about, though perhaps an example, demo, or link would be helpful in the docs?

**Comment by helmutgranda** [comment]
@mdo, I was pondering the same the other day. Wondering whose responsibility it is to confirm that both libraries work well together.

In my mind I came to the conclusion that neither library should be responsible to demo that they work together. People can submit bug reports and ask for assistance doing the integration but it is rather easy to have people expect library creators gap that bridge.

Maybe this ticket should suffice? I am not sure if search engines would surface tickets like this when people are looking for recommendations. Doing a quick search in Google for "bootstrap 4 masonry example" brings some good examples already in place.

**Comment by mdo** [comment]
Masonry is the best thing for this. I'm inclined to remove the card columns in v5 given their limitations. There's no CSS-only approach here that works, and I don't think we should be getting into the business of recreating Masonry, a proven project that does this really well.

Closing for now given we can't make this change now in v4.
