### ISSUE TITLE
Consider using let instead of var

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27390]
Just a query, shouldn't we consider migrating over to `let` instead of `var` for some JS like this:

https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#select-menu

**Comment by XhmikosR** [comment]
I don't think we should track such things so early.

**Comment by Johann-S** [comment]
So I'll close this issue but let it marked as `v5`

**Comment by jyxjjj** [comment]
@Johann-S 
I want to only make my website's bootstrap use let instead of var.
What can i do?
Just replace all by my editor?

**Comment by Johann-S** [comment]
@jyxjjj You can use our src files and build them (with Babel for example) with your own Browserlist config and it'll replace all the `var` by `const` or `let`

**Comment by SuperPat45** [comment]
Next jQuery 4 will drop support for IE10:
https://github.com/jquery/jquery/issues/4299

As IE10 is no more supported by Microsoft, Is it really necessary to keep compatibility for bootstrap 5?

**Comment by Johann-S** [comment]
@SuperPat45 we won't support IE 10 in v5 only IE 11
