### ISSUE TITLE
Setting color of some UTF-8 characters doesn't work

### ISSUE THREAD

**Issue by jrief** [twbs/bootstrap#27405]
How can one override the color of the UTF-8 characters	✔ (U+2714) and ✖ (U+2716)? Other UTF-8 characters, such as ✓, ✕ and ✗ seem to work perfectly.

This effect can be reproduced on Chrome 71, Chrome 69, Safari 11.2 and Firefox 62.0.3 (all Mac 10.11). It only happens for versions of Bootstrap-4. Bootstrap-3 or no CSS at all, works as expected.

Here is a Codepen: https://codepen.io/jrief/pen/LgjyjX using Bootstrap version 4.1.3

**Comment by XhmikosR** [comment]
I guess you are on Windows? It seems `Segoe UI Emoji` doesn't work with this while `Segoe UI` works.

**Comment by jrief** [comment]
@XhmikosR Did you read my post? I wrote 
> Mac 10.11

and further, why then does it work with BS-3 or no CSS at all, but not with BS-4?

**Comment by XhmikosR** [comment]
Because of the system fonts we have in v4.

**Comment by jrief** [comment]
> Because of the system fonts we have in v4.

That was the missing hint!

By overriding the font family in my project's `_variables.scss` this problem is solved.
```
$font-family-sans-serif: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```
 The culprit is `"Apple Color Emoji"`, which is part of Bootstrap-4's [Native font stack](https://getbootstrap.com/docs/4.0/content/reboot/#native-font-stack).

This should be annotated in the documentation. It took me several hours to figure out why.

**Comment by XhmikosR** [comment]
You are welcome to make a PR.

**Comment by jrief** [comment]
It would be great if someone with access to other operating systems (Windows, Linux, etc.) could check their status using the Codepen at https://codepen.io/jrief/pen/LgjyjX and tell me about their experience.

**Comment by madflow** [comment]
@jrief 

* Arch Linux
* FF 62

![image](https://user-images.githubusercontent.com/183248/46905795-e391e200-cef8-11e8-9fc3-fc52c6e564b1.png)

**Comment by LouCle** [comment]
- Chrome 69
- win10

![image](https://user-images.githubusercontent.com/38225675/46978314-e6dec680-d0ce-11e8-9d90-d03b69ce6a15.png)

**Comment by wolfy1339** [comment]
Works fine on Android 8.0.0 (w/ July 2018 security patches) and Chrome 69.0.3497.100

**Comment by XhmikosR** [comment]
That's because it's OS-dependent due to the system font stack.

**Comment by LouCle** [comment]
Is it necessary by the way? I can't really see the context in which coloured symbols would belong.

**Comment by mdo** [comment]
Closing as a won't fix. The emoji stack ensures the best symbol for each OS and browser based on our testing. Please feel free to suggest docs improvements that'd better explain this if it's needed.
