### ISSUE TITLE
Form-control changed behaviour between version 4.1.2 and 4.1.3

### ISSUE THREAD

**Issue by sannyjacobsson** [twbs/bootstrap#27404]
Windows 10,
Microsoft Edge Version 42.17134.1.0, 
Chrome Version 69.0.3497.100 (Official Build) (64-bit), 
Firefox Version 62.0.3 (64-bit)

In version 4.1.2 and previous versions a div with form-control class expands to contain children. See 
https://jsbin.com/yelahovoxi/edit?html,output 

In verison 4.1.3 it does not. See 
https://jsbin.com/hiyumuwace/edit?html,output

**Comment by MartijnCuppens** [comment]
You're not supposed to add the `.form-control` class to a div.

**Comment by XhmikosR** [comment]
Yup, what @MartijnCuppens said above.
