### ISSUE TITLE
Allow user to configure look of button states.

### ISSUE THREAD

**Issue by dilame** [twbs/bootstrap#27406]
https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss
In this mixin button states parameters are hardcoded, for example
`$hover-background: darken($background, 7.5%), $hover-border: darken($border, 10%), $active-background: darken($background, 10%), $active-border: darken($border, 12.5%)`
And i can't affect this parameters from my code, the only solution i know is to redefine the whole mixin with another hardcoded arguments.
I think we could configure this with _variables.scss

**Comment by herbalite** [comment]
Can you give an example how you include the mixin?

Because the parameters in the mixin you refer to have default values that can be overriden. ( http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixin-arguments )

**Comment by dilame** [comment]
Tre trick is i don't include this mixin from bootstrap itself. I copy all the code from https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss in my project, and include my own mixin for button with my own default and not include bootstrap's one.
I believe it's not the right way, but i don't see another at the moment.
Here is my code for make it clear for you

```scss
@import "~bootstrap/scss/functions";
@import "variables";
@import "~bootstrap/scss/mixins";
@import 'root';
@import '~bootstrap/scss/bootstrap-reboot';
@import '~bootstrap/scss/type';
@import '~bootstrap/scss/images';
@import '~bootstrap/scss/grid';
@import "~bootstrap/scss/tables";
@import '~bootstrap/scss/forms';
@import 'buttons';
@import '~bootstrap/scss/transitions';
@import '~bootstrap/scss/button-group';
@import '~bootstrap/scss/input-group';
@import 'custom-forms';
@import '~bootstrap/scss/card';
@import '~bootstrap/scss/alert';
@import '~bootstrap/scss/list-group';
@import '~bootstrap/scss/close';
@import 'modal';
@import '~bootstrap/scss/popover';
@import '~bootstrap/scss/utilities';
@import '~bootstrap/scss/dropdown';
@import '~bootstrap/scss/tooltip';
```

**Comment by mdo** [comment]
Unfortunately we can't really do this exact approach in just the variables file as Sass doesn't support "dynamic" variables like this. We can't put `$active-border: darken($border, 12.5%)` in vars, but we could put `$active-border-darken: 12.5%`.

We could potentially try to address that in v5 with a different approach, but I believe there's not much to be done right now.
