### ISSUE TITLE
Custom select in input-group-prepend

### ISSUE THREAD

**Issue by tomswinkels** [twbs/bootstrap#27401]
Hi,

In a input group prepend i wan't added a custom select.

When i put the custom select in the groep-prepend the border is rounded.

``                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <select class="custom-select form-control">
                                                <option>test</option>
                                            </select>
                                        </div>
                                        <input type="text" class="form-control" placeholder="">
                                    </div>``

I have added this in my css to fix it

``       .input-group .input-group-prepend .custom-select, .input-group .input-group-prepend .form-control {
            border-top-right-radius: 0;
            border-bottom-right-radius: 0;
        }``

Maybe this is a good feature.

**Comment by mdo** [comment]
That's interesting, but I don't think we'll go this route given that if we do this for one component, we'll be expected to do it for all of them.
