### ISSUE TITLE
Border radius - padding - margin - font size - border

### ISSUE THREAD

**Issue by uulgie** [twbs/bootstrap#27447]
###  _border radius_
> 
> @for $i from 0 through 100 {
>   .r-#{$i} { border-radius: $i+px !important; }
> }
> 
 // border radius circle
> 
> .rc{ border-radius: 50% !important; }
> 
// border radius top left
> 
> @for $i from 0 through 100 {
>   .rtl-#{$i} { border-top-left-radius: $i+px !important; }
> }
> 
// border radius top right
> 
> @for $i from 0 through 100 {
>   .rtr-#{$i} { border-top-right-radius: $i+px !important; }
> }
> 
// border radius bottom left
> 
> @for $i from 0 through 100 {
>   .rbl-#{$i} { border-bottom-left-radius: $i+px !important; }
> }
> 
// border radius bottom right
> 
> @for $i from 0 through 100 {
>   .rbr-#{$i} { border-bottom-right-radius: $i+px !important; }
> }
> 

### We can use class like
**Number after - variable from 0 to 100**

> = Border-radius: 1px;

< div class="r-1">
Example content
< /div>

> = Border-radius: 100px

< div class="r-100">
Example content
< /div>

> = Border-radius: 50%;

< section class="rc">
Example content
< /section>

= Border-top-left-radius: 15px;

< div class="rtl-15">
Example content
< /div>

-----------------------------------------------------------------------

### Padding

> @for $i from 0 through 100 {
>   .p-#{$i} { padding: $i+px !important; }
> }
> 
// padding top
> 
> @for $i from 0 through 100 {
>   .pt-#{$i} { padding-top: $i+px !important; }
> }
> 
// padding Bottom
> 
> @for $i from 0 through 100 {
>   .pb-#{$i} { padding-bottom: $i+px !important; }
> }
> 
// padding left
> 
> @for $i from 0 through 100 {
>   .pl-#{$i} { padding-left: $i+px !important; }
> }
> 
// padding right
> 
> @for $i from 0 through 100 {
>   .pr-#{$i} { padding-right: $i+px !important; }
> }
> 
// padding x
> 
> @for $i from 0 through 100 {
>   .px-#{$i} { padding-right: $i+px !important; padding-left: $i+px !important; }
> }
> 
// padding y
> 
> @for $i from 0 through 100 {
>   .py-#{$i} { padding-top: $i+px !important; padding-bottom: $i+px !important; }
> }

### Example padding

< div class="p-14">
Example content
< /div>

// padding
> 
> @for $i from 0 through 100 {
>   .p-#{$i} { padding: $i+px !important; }
> }
> 
// padding top
> 
> @for $i from 0 through 100 {
>   .pt-#{$i} { padding-top: $i+px !important; }
> }
> 
// padding Bottom
> 
> @for $i from 0 through 100 {
>   .pb-#{$i} { padding-bottom: $i+px !important; }
> }
> 
// padding left
> 
> @for $i from 0 through 100 {
>   .pl-#{$i} { padding-left: $i+px !important; }
> }
> 
// padding right
> 
> @for $i from 0 through 100 {
>   .pr-#{$i} { padding-right: $i+px !important; }
> }
> 
// padding x
> 
> @for $i from 0 through 100 {
>   .px-#{$i} { padding-right: $i+px !important; padding-left: $i+px !important; }
> }
> 
// padding y
> 
> @for $i from 0 through 100 {
>   .py-#{$i} { padding-top: $i+px !important; padding-bottom: $i+px !important; }
> }

-----------------------------------------------------------------------

### Example Margin

> < div class="m-17">
> Example content
> < /div>
> `
// margin
> 
> @for $i from 0 through 100 {
>   .m-#{$i} { margin: $i+px !important; }
> }
> 
// margin top
> 
> @for $i from 0 through 100 {
>   .mt-#{$i} { margin-top: $i+px !important; }
> }
> 
// margin Bottom
> 
> @for $i from 0 through 100 {
>   .mb-#{$i} { margin-bottom: $i+px !important; }
> }
> 
// margin left
> 
> @for $i from 0 through 100 {
>   .ml-#{$i} { margin-left: $i+px !important; }
> }
> 
// margin right
> 
> @for $i from 0 through 100 {
>   .mr-#{$i} { margin-right: $i+px !important; }
> }
> 
// margin x
> 
> @for $i from 0 through 100 {
>   .mx-#{$i} { margin-right: $i+px !important; margin-left: $i+px !important; }
> }
> 
// margin y
> 
> @for $i from 0 through 100 {
>   .my-#{$i} { margin-top: $i+px !important; margin-bottom: $i+px !important; }
> }

-----------------------------------------------------------------------

### Font size

> @for $i from 0 through 100 {
>   .s-#{$i} { font-size: $i+px !important; }
> }

-----------------------------------------------------------------------

### Border

> @for $i from 0 through 100 {
>   .b-#{$i} { border: $i+px solid #ccc !important; }
> }

**Comment by bastienmoulia** [comment]
Too much unused css will be generated.

**Comment by gijsbotje** [comment]
if you want all these options, add them to the sass maps.
adding this to core is absolute overkill
