### ISSUE TITLE
Sidebar: 3 clicks necessary to open it on mobile

### ISSUE THREAD

**Issue by PierreClementCazon** [twbs/bootstrap#27459]
Hi,

I have a problem on my mobile when I want to open my sidebar by clicking on the sidebar-toggle: the menu only opens after an average of 3 clicks, the first two don't work.

Any ideas?
Thank you in advance for your help.

**Comment by patrickhlauke** [comment]
what "sidebar" are you referring to? also, without a reduced test case, it's difficult to diagnose any issues. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md

**Comment by PierreClementCazon** [comment]
Hi,

Sorry for the lack of reactivity, here is a simplified page where the problem is present : https://jobphoning.com/bug-menu

Thank you in advance for your help !
