### ISSUE TITLE
Override variables through media queries

### ISSUE THREAD

**Issue by tuxtux59** [twbs/bootstrap#27451]
Hi,

I would like to know how to override variables through media queries
For example i want to have three different ``$font-size-base``, one regular, one for max-width 991px and one for max-width 448px
Here is my **SCSS** code
`$font-size-base: 14px`
`@media (max-width: 991px)`
 `     $font-size-base: 12px`
`@media (max-width: 448px)`
`     $font-size-base: 10px`

When I modify first line  it does have an impact
but media queries never called

To clarify I have no other conflicts from other files or theme, the last value come from $font-size-base content.

**Comment by rafalp** [comment]
Sass is CSS **pre**processor. This means it takes scss files, evaluates them and spits out css files. It doesn't really care about media queries.

**Comment by mdo** [comment]
What @rafalp said :).
