### ISSUE TITLE
Change docs search to take into account the current domain

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27463]
So that Netlify previews' search doesn't send us to the main docs pages.

**Comment by XhmikosR** [comment]
@Johann-S maybe we should just use `window.hostname` in https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/assets/js/src/search.js#L32

I don't recall why I went with this back then...

**Comment by Johann-S** [comment]
Yep `window.location.origin` should do the tricks 👍

**Comment by XhmikosR** [comment]
IIRC this isn't supported on IE so we'll need to construct this manually.

**Comment by Johann-S** [comment]
Yep I did that on our v4 customizer here: https://github.com/Johann-S/bs-customizer/blob/master/src/js/util.js#L120-L124

**Comment by XhmikosR** [comment]
Cool, I'll try to make a PR later.
