### ISSUE TITLE
Move `.modal-scrollbar-measure` styles into `Modal.prototype._getScrollbarWidth`

### ISSUE THREAD

**Issue by iamandrewluca** [twbs/bootstrap#27471]
Is there any reasons that styles for `.modal-scrollbar-measure` are in Bootstrap `SCSS`?
As they are not related to `modal` styles, I'd suggest to move them into `Modal.prototype._getScrollbarWidth` because only there are used, and are directly related to that functionality.

**Comment by Johann-S** [comment]
Hi @iamandrewluca,

Personaly I'm not a big fan of adding inline CSS with JS, moreover when it's not a dynamic CSS.

/CC @twbs/js-review

**Comment by XhmikosR** [comment]
Yeah, I don't like this approach either.

**Comment by Johann-S** [comment]
Currently it's used only in our Modal components

**Comment by iamandrewluca** [comment]
@Johann-S If this is a no n, I can just reuse `_getScrollbarWidth` in tests, redefining that function in tests it's not so good. I'll move styles back in SCSS.

**Comment by Johann-S** [comment]
yep seems good to me 👍

**Comment by mdo** [comment]
Closing since this seems like a no-go from us and OP has an answer :).
