### ISSUE TITLE
Appended input group loses styling when a invalid feedback element exists in the same div.

### ISSUE THREAD

**Issue by david-nguyen** [twbs/bootstrap#27470]
An appended element that is part of an input group containing an `invalid-feedback` div will lose its border radius. The cause is the CSS selector is checking for last-child in the `input-group` div. Judging by the example here (https://getbootstrap.com/docs/4.0/components/forms/) the `invalid-feedback` div should be included within the `input-group` div.

- OS: Windows 10
- Browser: Chrome 67.0.3396.79
- Reduced test case: https://jsfiddle.net/ek89ctsg/

**Comment by morrissey-ingenious** [comment]
there is already an open issue for this #25110
