### ISSUE TITLE
[V4.1.3] Carousel example code will not show images in IE11

### ISSUE THREAD

**Issue by vpxavier** [twbs/bootstrap#27485]
Hi, 
I'm using the code from the Carousel example here: https://getbootstrap.com/docs/4.1/examples/carousel/
This works on any browser I tested but on Internet Explorer 11 (tested on Windows 10), the carousel doesn't display the images.

Another user has the same proble on his live website here: http://www.claudiaspaziani.com/

I'm sorry if it is a duplicate but I couldn't find any.
Thanks for your help.

**Comment by patrickhlauke** [comment]
you can't just use `<img srcset="...">` as IE doesn't understand that.

in any case, the problem is not with bootstrap, but with your implementation. in future, it'd be best to ask on StackOverflow or similar first. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by vpxavier** [comment]
That is sad because I didn't consider it as a personal issue regarding the fact that it is the "official" carousel example that is not working.

**Comment by patrickhlauke** [comment]
the official carousel https://getbootstrap.com/docs/4.1/examples/carousel/ works exactly the same in IE11 as in Chrome etc. the issue on the http://www.claudiaspaziani.com/ site was the wrong use of the `<img>` element, which is nothing to do with Bootstrap. unless you have an actual example where you use `<img src="...">` properly and it still doesn't work?

**Comment by vpxavier** [comment]
Well, indeed, originally the code contains  `<img srcset="` which seems to be replaced, once the page is displayed, with `<img src="` but not on IE11

Here's a site were I'm using the code: https://www.lapause.be/
So, the main problem seem to be that the code should be replacing this 
`<picture>
              <source srcset="img/cover2000x500.jpg" media="(min-width: 1400px)">
              <source srcset="img/cover1400x500.jpg" media="(min-width: 769px)">
              <source srcset="img/cover800x500.jpg" media="(min-width: 577px)">
              <img srcset="img/cover600x500.jpg" alt="responsive image" class="d-block img-fluid">
            </picture>`
With this
 <img src="img/cover600x500.jpg" alt="responsive image" class="d-block img-fluid">
But it does not.
