### ISSUE TITLE
Theming page in documentation, a wrong variable name

### ISSUE THREAD

**Issue by Micro-Shadi** [twbs/bootstrap#27481]
Hello,
here's the link: https://getbootstrap.com/docs/4.1/getting-started/theming/#variable-defaults

in the example it says **$body-color**, i think it should be **$text-color**

**Comment by XhmikosR** [comment]
I don't think so.

>Here’s an example that changes the **background-color** and color for the <body> when importing and compiling Bootstrap via npm:
