### ISSUE TITLE
Classes alert primary danger info warning

### ISSUE THREAD

**Issue by uulgie** [twbs/bootstrap#27483]
We use class alert like this:

```html
<div class="alert">
    Div with class alert simple
</div>

<div class="alert alert-primary">
    Div with class alert primary
</div>
```
alert-primary --> only

```html
<div class="alert">
     Div with class alert simple
</div>

<div class="alert-primary">
    Div with class alert primary
</div>
```

All classes extend from basic alert + style of alert danger or warning or anything

**Comment by mdo** [comment]
Base and modifier class pairings are our established approach. Not going to change anytime soon :).
