### ISSUE TITLE
Multiple col-md-9 and one col-md-3 in a row

### ISSUE THREAD

**Issue by ofyalcin** [twbs/bootstrap#27498]
I'm creating a Wordpress theme with Bootstrap 4. I got stuck at one point.

I created 5 different sections. Each section can be individually sized. Users can choose section width 9/12 or 12/12. If the width is set to 9/12, the right side automatically comes with a sidebar. I have a problem here.

When more than one section with a width of 9/12 arrives at the bottom, the sidebar is located on the right side of the last section.

I can visually express this as:
[IMAGE 1](https://i.stack.imgur.com/serlN.png)
[IMAGE 2](https://i.stack.imgur.com/fFDqm.png)

My code is:

```
<div class="row">
  <div class="col-md-9"></div>
  <div class="col-md-9"></div>
  <div class="col-md-9"></div>
  <div class="col-md-3"></div>
</div>
```
I know I can do it like this:

```
<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12"></div>
            <div class="col-md-12"></div>
            <div class="col-md-12"></div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
```

But when the user chooses the width of the first section as 12/12, I want the sidebar to go down. Like this:

[IMAGE 3](https://i.stack.imgur.com/STf8X.png)
[IMAGE 4](https://i.stack.imgur.com/dgnP2.png)

Does anybody know how to do this? Thanks everyone!

**Comment by mdo** [comment]
What you need then is the more complex markup or CSS Grid. Our flexbox-based grid cannot do what you're looking for out of the box.
