### ISSUE TITLE
Clean up/finalize our stylelint config and publish it on npm

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27490]
/CC @MartijnCuppens

**Comment by MartijnCuppens** [comment]
@XhmikosR, shall we create a new repo under twbs for this?

**Comment by XhmikosR** [comment]
@MartijnCuppens: yeah we can should do that.

**Comment by XhmikosR** [comment]
Closing this since our config is now on https://github.com/twbs/stylelint-config-bootstrap
