### ISSUE TITLE
Custom style.css media queries are not working in Bootstrap4

### ISSUE THREAD

**Issue by kvkv** [twbs/bootstrap#27499]
I am using bootstrap4. I am using my own styles in style.css file. Added media queries in style.css, but the media queries are not working whichever added in my style.css. Bootstrap4 inbuild media queries are working.

In Chrome Development tools styles tab shows .scss files, I am not using scss files of bootstrap using only CSS files. But I can't understand how the scss files are coming.How to activate the media queries in style.css I am adding media queries below whichever added in my style.css file.

Please help me resolve the issue to activate media queries in my custom styles.css file.
--
`// Large devices (desktops, less than 1200px)
@media (max-width: 1199.98px) { 
    body{background:yellow};
}

// Medium devices (tablets, less than 992px)
@media (max-width: 991.98px) {
    body{background:red};
}

// Small devices (landscape phones, less than 768px)
@media only screen and (max-width:767.98px) { 
    body{background:pink};
}

// Extra small devices (portrait phones, less than 576px)
@media (max-width: 575.98px) { 
    body{background:gray};
}`

**Comment by mdo** [comment]
You code comments are the Sass version, and they'll likely making the stylesheet invalid. Use `/* Comment style */` instead.

**Comment by kvkv** [comment]
Ohhh. Thanks a lot mdo. I removed '//' , it is working fine.
