### ISSUE TITLE
Custom File translated Label

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#27496]
I 've done some quick search, without results, so I opened this issue as suggestion 

In order to use scss variables we can use the following css with the help of a **data-attribute** so every developer can use any string he wants

```
.custom-file-input~.custom-file-label::after {
    content: attr(data-label);
}

<div class="custom-file">
  <input type="file" class="custom-file-input" id="customFileLang" >
  <label class="custom-file-label" for="customFileLang" data-label="Can't see me?">Seleccionar Archivo</label>
</div>
```

The result as I tested, below
https://jsfiddle.net/hc0v648r/1/

**Comment by Johann-S** [comment]
We explain here how to translate : https://getbootstrap.com/docs/4.1/components/forms/#translating-or-customizing-the-strings

**Comment by Johann-S** [comment]
We explain here how to translate : https://getbootstrap.com/docs/4.1/components/forms/#translating-or-customizing-the-strings

**Comment by GeoSot** [comment]
Yes I have read the above link @Johann-S .... thank you for pointing it to me.

As i wrote on my first message , i suggested the above implementation as a future concern in order to be easy to change the string, on the fly

**Comment by Johann-S** [comment]
Oh ok sorry for the misunderstanding

**Comment by alecpl** [comment]
Oh, it would be nice to support this. All we need is to add:
```
& ~ .custom-file-label[data-label]::after {
    content: attr(data-label);
}
```
after the :lang() rules in `.custom-file-input` block.

**Comment by alecpl** [comment]
Or maybe before? @mdo need a hint, and I'll provide a PR.

**Comment by alecpl** [comment]
This is already implemented with https://github.com/twbs/bootstrap/pull/27651. Though, maybe `data-label` is better than `data-browse`. Please, consider the change.

**Comment by MartijnCuppens** [comment]
Indeed, this is already implemented. Not sure if `data-label` is better than `data-browse`, @mdo, what do you think?

**Comment by MartijnCuppens** [comment]
I'm going to close this. Changing this to `data-label` would be a breaking change at this point.
