### ISSUE TITLE
`_fixTitle` in docs

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27501]
IIRC this isn't part of the public API but we use it in docs.

https://github.com/twbs/bootstrap/blob/807e8fe4a2d955503425ec6f20fa000228089453/site/docs/4.1/assets/js/src/application.js#L78

and

https://github.com/twbs/bootstrap/blob/807e8fe4a2d955503425ec6f20fa000228089453/site/docs/4.1/assets/js/src/application.js#L95

Either we should replace it in docs or maybe make it public?

/CC @Johann-S

**Comment by Johann-S** [comment]
This method have been made to be private (like our other methods which start with `_`), for me here it's bad practice to do that, we should instead destroy our tooltip and create new one

**Comment by XhmikosR** [comment]
Sounds good to me.

**Comment by jamesgeorge007** [comment]
@Johann-S @XhmikosR What do you think of replacing those es5 functions (for callbacks) with arrow functions which is a more concise way within the same file?

**Comment by XhmikosR** [comment]
Nope, the docs are ES5.

**Comment by XhmikosR** [comment]
It seems we still have a couple of instances, reopening.
