### ISSUE TITLE
Nested Card inside Accordion's `body` missing bottom border

### ISSUE THREAD

**Issue by JJCoolBean** [twbs/bootstrap#27510]
When nesting a card inside an accordion's card body, the nested card inside the card body of an accordion is missing the bottom border.

- Operating system and version: Windows 7 SP1 64 bit 
- Browser and version: Chome 69.0.3497.100
- Reduced test case: https://codepen.io/JJCoolBean/pen/KGraWv

**Comment by ovpv** [comment]
Is this issue confirmed? If so, I would like to PR to this issue.
