### ISSUE TITLE
btn-link-inline to use button element for functionality in text

### ISSUE THREAD

**Issue by michapietsch** [twbs/bootstrap#27515]
We can add ```btn-link``` with ```role="button"``` to an ```a``` element but it feels cleaner to use ```<button>``` for non-navigation functionality as the common way to go. So I regularly add a modified ```btn-link-inline``` to my projects.

I suggest to add this class that provides essentially a ```btn-link``` but with ```display: inline```, no padding and no border instead. And that's already it.

At this point I do not recommend a general ```btn-inline``` modifier because I think it doesn't work with the other buttons with colored backgrounds. If buttons would be visually adapted in this case I imagine they look more like a highlight when they'd instead need to convey their button character.

**Comment by patrickhlauke** [comment]
i believe the problem currently still is that, no matter how hard one tries, an inline button still suffers from subtle line-height/alignment differences when placed inline with regular text, despite trying to nuke most button-like stylings. will need to investigate if this is still the case.

**Comment by michapietsch** [comment]
I created a code pen to preview in different browsers: https://codepen.io/michapietsch/pen/WaLGOJ

There are other properties to consider. It this case I override them but a ```btn-link-inline``` or ```btn-inline``` instead of ```btn-link``` could just not specify them.

**Comment by mdo** [comment]
Passing on this for now, thanks though!
