### ISSUE TITLE
Missing vertical alignment from spacing documentation

### ISSUE THREAD

**Issue by panoscool** [twbs/bootstrap#27517]
Add more details on spacing and alignment documentation. For example how to align cards vertically - horizontally, form sizing, navbar items alignment etc. It will perfect if you cover all this situations under the spacing page.

**Comment by XhmikosR** [comment]
Deferring this to @mdo

**Comment by mdo** [comment]
I'm unclear what specifically we should change here. Nearly every component can use our utilities, and custom styles, for alignment and spacing. Please feel free to open PRs with specific suggestions or to make more detailed recommendations here for the kind of things you'd like to see that don't exist currently.
