### ISSUE TITLE
'shown' event on modal called before transition completed.

### ISSUE THREAD

**Issue by DataTables** [twbs/bootstrap#27519]
- Operating system and version: Fedora 28
- Browser and version: Chrome 66
- Reduced test case: http://jsfiddle.net/fouavchs/1/

I think this is a duplicate of #5045, but that issue was closed without a test case being provided and I can't reopen it. Apologies if I should have posted in the closed issue.

I've been hitting a problem in Bootstrap 4 (wasn't able to reproduce the issue in Bootstrap 3) whereby I position an element over a Bootstrap modal when it opens (a date picker for my use case, but it applies to any overlay). I use `shown.bs.modal` to know when the modal is visible and the transition is complete - the [docs say](http://getbootstrap.com/docs/4.1/components/modal/#events)

> show.bs.modal | This event fires immediately when the show instance method is called. If caused by a click, the clicked element is available as the relatedTarget property of the event.

However, I've been finding that the `shown` event triggers before the CSS transition is completed. The [test case](http://jsfiddle.net/fouavchs/1/) demonstrates this:

1. Click the "Launch demo modal" button in the output view (I've just used the docs demo HTML for the modal)
2. Observe that the blue line is just above the model footer initially.
3. After a second observe that the blue line is moved to exactly match the top of the modal footer.

I've got a little function that positions the blue bar to where the modal footer position is read. When `shown.bs.modal` is triggered, this is not the final position of the modal, hence the need for a timeout to shift it to the correct position.

Expected result: The blue bar should be shown exactly at the top of the footer when the CSS transition is completed. It appears that `shown.bs.modal` is triggering too early.

I should note that in #5045 it was noted that the `fade` class is needed for this to work. The modal the HTML I've used has that class and this problem is still present.

Tested with Bootstrap 4.1.0, 4.1.1 and  4.1.3.

**Comment by DataTables** [comment]
That's odd! Its pulling in `http://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css` and seems to render the modal okay for me:

![screenshot from 2018-10-26 13-37-11](https://user-images.githubusercontent.com/278219/47566674-556c2180-d924-11e8-8e1e-1991e3887f9b.png)

**Comment by Johann-S** [comment]
If you load your assets using HTTPS it'll work fine 😉 
![image](https://user-images.githubusercontent.com/1689750/47567350-9a955100-d92e-11e8-8a26-7effae76db11.png)

**Comment by DataTables** [comment]
Doh - sorry. Updated the JSFiddle to use https and it shows the issue correctly now: https://jsfiddle.net/fouavchs/2/ .

**Comment by Johann-S** [comment]
Ok I found why...

By default we use `transitionend` event, but it seems in Chrome `transitionend` is triggered too early, and if I use `webkitTransitionEnd` it's triggered on time... Very weird behavior here

/CC @XhmikosR and @patrickhlauke if you have any information

**Comment by Johann-S** [comment]
@DataTables I made a fix here: #27521

**Comment by Johann-S** [comment]
I made a JSFiddle with my fix: https://jsfiddle.net/wh2jf9st/ 😉

**Comment by DataTables** [comment]
That's awesome - thanks!
