### ISSUE TITLE
select-improved not working when inject from ajax request

### ISSUE THREAD

**Issue by Expartis** [twbs/bootstrap#27516]
` 
$.ajax({
        url: "",
        type: "POST",
        success: function (ret) {
            $("#test").html(ret);
            $("#test").modal('show');
        }
});
`
Le code ci-dessus est utilisé pour injecter le contenu d'une partial view (Razor) dans le DOM et afficher une modal, si la partial view contient l'un de vos select-improved ce dernier ne fonctionne pas, l'élément ne réagit pas au click.

Par contre si votre select est présent dans le DOM au chargement de la page, aucun problème.

**Comment by patrickhlauke** [comment]
select-improved? ca ne fait pas parti de bootstrap. un plug-in, peut-etre? et generalement: si il-y-a du code d'initialisation, it faut l'executer apres un changement dynamique du DOM.
