### ISSUE TITLE
no $font-weight-lg

### ISSUE THREAD

**Issue by phazei** [twbs/bootstrap#27528]
Currently it's possible to set the padding, line-height, font-size, and border-radius for large element buttons and inputs, but there's no choice for font weight.  It would seem natural that if there were a larger element, it might want to have a stronger weight.

**Comment by namiltd** [comment]
See: https://github.com/twbs/bootstrap/commit/c8a4d9dd745e0529e8868aef4551dc2a493745a3#diff-d8ee409a461718bfb6240710c8c73382
