### ISSUE TITLE
label element stylized by display-inline in reboot scss doesnt wrap the long text

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#27526]
HI

I got some wrap text problem with custom-control-label the long label text are not wrapped ... adding a d-block class  to this label and it's work better ...

here is a jsfiddle :
https://jsfiddle.net/jipexu/12q3xr05/48/

Any advice or i miss something ?

Thanks

**Comment by mdo** [comment]
At first glance this seems like the card word wrap problem. There's a PR to remove that line which would likely fix this issue. See #25063.

**Comment by jipexu** [comment]
ok thanks i will look 
and until this i will give display-block for label on our final css .. (until now i dont noticed some bad effect in other place ...or  but it's maybe to early to say this ....  ) ... and continue to follow this
thanks

**Comment by mdo** [comment]
Yeah, same issue. Closing as dupe.
