### ISSUE TITLE
Sizing for custom-control

### ISSUE THREAD

**Issue by adaniello** [twbs/bootstrap#27527]
About sizing we can use `.form-control-lg` or `.form-control-sm`, and the same `.custom-select-lg` or `.custom-select-sm`.

Maybe we're missing `.custom-control-lg` or `.custom-control-sm` for `.custom-checkbox` and `.custom-radio`.

Thanks

**Comment by mdo** [comment]
No plans to add sizes for these—they're built with `rem`s so they should scale as you need them to.

**Comment by ceejayoz** [comment]
@mdo They scale with the base font size, but they don't scale to fit the font size of their `.custom-control` div as far as I can tell. If I bump up its `font-size`, the labels get bigger, but the radios remain (now comically) small.

Can this be reconsidered? Or can you provide info on how to override the size of the custom controls?
