### ISSUE TITLE
$input-height isn't pulled with new defined values while transpilling to css

### ISSUE THREAD

**Issue by createdwithlove** [twbs/bootstrap#27538]
This is how my theme.scss looks:
```
// required Bootstrap files
@import "bootstrap/scss/variables";

//overwrite Bootstrap settings
@import "my-variables";
```

When setting `$input-btn-padding-y` in `_my-variables.scss` this value is ignored in calculation of `$input-height` (https://github.com/twbs/bootstrap/blob/v4.1.3/scss/_variables.scss#L446).
To make it generate the right output, also the complete line from $input-height-inner and $input-height has to be placed in `_my-variables.scss`.

It's maybe more a scss problem with not lazy loading variables and the escaped values in calc(#{}).

**Comment by MartijnCuppens** [comment]
@createdwithlove, you need to include your variables before including bootstrap. See docs: http://getbootstrap.com/docs/4.1/getting-started/theming/#variable-defaults

**Comment by createdwithlove** [comment]
Thank you @MartijnCuppens.

The reason I put my variables after the bootstrap ones was that I wanted to cleanup the color maps. Something like the example below does not work wenn placed before `bootstrap/_variables` resp. leads to the complete default `$color`map + `$mycol`:
```
$mycolor: #ff00ff;
$colors: ();
$colors: map-merge((
  "mycolor": $mycolor
), $colors);
```

Is it right, that the only solution would mean to split the definition of the $mycolor variable (before  `variables.scss`) and the remapping of $colors (after `variables.scss`)?
````
// theme.scss
@import "_my-variables"
@import "bootstrap/_variables"
@import "_my-bootstrapoverwrite"
````

**Comment by MartijnCuppens** [comment]
@createdwithlove  Yes indeed.

**Comment by createdwithlove** [comment]
😢 I want {Less} back – okay, maps wouldn't then be a problem anyway…
