### ISSUE TITLE
[reboot] default background on <body> triggers box-shadow bug in Chrome

### ISSUE THREAD

**Issue by leeoniya** [twbs/bootstrap#27535]
i found and reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=899342

**Comment by XhmikosR** [comment]
If anyone wants to make a PR to document this in the browser bugs page, please do so.

Although if it gets fixed soon, not sure if we should even bother adding it.

**Comment by leeoniya** [comment]
i guess the other side of this question is whether setting a body background color is necessary?

> // 2. As a best practice, apply a default `background-color`.

why is this best practice? why only in the case of `<body>`?

**Comment by XhmikosR** [comment]
For themes and generally so that it's inherited properly.

**Comment by leeoniya** [comment]
> For themes

can you elaborate with an example? i expect themes that need non-white / non-transparent body bg will be defining it explicitly already.

> and generally so that it's inherited properly

background is not an inheritable property, though [1].

https://developer.mozilla.org/en-US/docs/Web/CSS/background

**Comment by XhmikosR** [comment]
I don't have any more info on this since I wasn't the one who made this choice. That being said, there's definitely needed for some cases with themes.

Either way, you can make another issue about that. This is for the browser bug.

**Comment by leeoniya** [comment]
ok, that makes sense. thanks for the clarification.

**Comment by leeoniya** [comment]
this bug is now fixed in Chromium:

https://bugs.chromium.org/p/chromium/issues/detail?id=899342#c5
