### ISSUE TITLE
Vertical rhythm proposal

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#27554]
**Description**
I have been doing research on **vertical rhythm** lately and feel that Bootstrap is lagging with **vertical spacing** customization and could use some rethinking.

**Proposal**
I would like to propose the addition of the **.5rem grid system** (based off of the 8-pt grid concept) to Bootstrap. The concept, is very simple, objects are separated by .5rem's which, since Bootstrap uses the browser default root font-size (typically 16px) 1rem works quite well for organization of objects as it is divisible by .5rem.

This system would allow us to add a much better vertical spacing system that would look like so..

```
n - for classes that eliminate the margin or padding by setting it to 0
0 - (by default) for classes that set the margin or padding to $spacer * .5
1 - (by default) for classes that set the margin or padding to $spacer
2 - (by default) for classes that set the margin or padding to $spacer * 1.5
3 - (by default) for classes that set the margin or padding to $spacer * 2
4 - (by default) for classes that set the margin or padding to $spacer * 2.5
5 - (by default) for classes that set the margin or padding to $spacer * 3
6 - (by default) for classes that set the margin or padding to $spacer * 3.5
7 - (by default) for classes that set the margin or padding to $spacer * 4
8 - (by default) for classes that set the margin or padding to $spacer * 4.5
9 - (by default) for classes that set the margin or padding to $spacer * 5
auto - for classes that set the margin to auto
```
n = stands for `nil`

This would significantly allow for a much wider range of vertical spacing.

References
- [The 8-Point Grid](https://spec.fm/specifics/8-pt-grid)
- [Setting Type on the Web to a Baseline Grid](https://alistapart.com/article/settingtypeontheweb)
- [Compose to a Vertical Rhythm](https://24ways.org/2006/compose-to-a-vertical-rhythm)

**Comment by MartijnCuppens** [comment]
Don't think this is a good idea for the following reasons:
- `.m-0` would result in `margin: .5rem`, that weird, especially because at the moment `.m-0` means `margin: 0`
- This would generate way to many classes, we need to make sure we don't generate too much CSS.

This issue isn't about vertical rhythm either, vertical rhythm is about the relation between line heights and font sizes.

That being said, there is room improvement for the current spacing utilities. Not sure which way we can go, but we'll need to make sure we have some of relation with the grid gutters (see #27072).

**Comment by guylepage3** [comment]
>Don't think this is a good idea for the following reasons:

>.m-0 would result in margin: .5rem, that weird, especially because at the moment .m-0 means margin: 0
>This would generate way to many classes, we need to make sure we don't generate too much CSS.

I definitely disagree. One thing I need to always add in is vertical spacing and it can be problematic. If I have to add it for readability, I'm sure quite a few others do as well.

>This issue isn't about vertical rhythm either, vertical rhythm is about the relation between line heights and font sizes.

Actually, yes it does. If you do the math it works out. It's only partially about the line distance but the math works.

>That being said, there is room improvement for the current spacing utilities. Not sure which way we can go, but we'll need to make sure we have some of relation with the grid gutters (see #27072).

I will check that out for sure. Thank you for sharing.

**Comment by MartijnCuppens** [comment]
@guylepage3, I'm closing this for now because you can easily achieve what you wish for by altering the `$spacers` map:
https://github.com/twbs/bootstrap/blob/2ffa1bff6eec53331d494b4cb0c915b3f0a213f0/scss/_variables.scss#L130-L140

**Comment by guylepage3** [comment]
@MartijnCuppens Ok. Thank you. I still feel that this should be built in for everyone else. It's not very heavy.

**Comment by guylepage3** [comment]
For reference. Here's a quick copy & paste for those looking to add something similar to my spec.

```
// Spacing
//
// Control the default styling of most Bootstrap elements by modifying these
// variables. Mostly focused on spacing.
// You can add more entries to the $spacers map, should you need more variation.

$spacer: 1rem;
$spacers: ();
// stylelint-disable-next-line scss/dollar-variable-default
$spacers: map-merge(
  (
    n: 0,
    0: ($spacer * .5),
    1: $spacer,
    2: ($spacer * 1.5),
    3: ($spacer * 2),
    4: ($spacer * 2.5),
    5: ($spacer * 3),
    6: ($spacer * 3.5),
    7: ($spacer * 4),
    8: ($spacer * 4.5),
    9: ($spacer * 5),
    auto: auto
  ),
  $spacers
);
```

**Comment by guylepage3** [comment]
I rethought the above and recommend just adding a few more additional values to the `$spacers` mapping.

```
// Spacing
//
// Control the default styling of most Bootstrap elements by modifying these
// variables. Mostly focused on spacing.
// You can add more entries to the $spacers map, should you need more variation.

$spacer: 1rem; // !default
$spacers: (); // !default
// stylelint-disable-next-line scss/dollar-variable-default
$spacers: map-merge(
  (
    0:  0,
    1:  ($spacer * .25),
    2:  ($spacer * .5),
    3:  $spacer,
    4:  ($spacer * 1.5),
    4b: ($spacer * 2),    // Custom value
    5:  ($spacer * 3),
    6:  ($spacer * 3.5),  // Custom value
    7:  ($spacer * 4),    // Custom value
    8:  ($spacer * 4.5),  // Custom value
    9:  ($spacer * 5),    // Custom value
    10: ($spacer * 5.5),  // Custom value
    11: ($spacer * 6),    // Custom value
    auto: auto            // Custom value
  ),
  $spacers
);
```
