### ISSUE TITLE
Find a way to run Browser Stack in all PRs

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27551]
The credentials for Browser Stack are not available to PRs people open without push rights. This means that the browser tests don't run there and we've been hit quite a few times due to this.

Now, in the past we were using https://github.com/twbs/savage but personally I don't have the knowledge to revive or maintain this.

/CC @twbs/team

**Comment by XhmikosR** [comment]
I think GitHub actions could help here. @mdo we need someone familiar with actions, to help us out here.

**Comment by mdo** [comment]
Did our move to Actions tackle this?

**Comment by XhmikosR** [comment]
Currently we don't run BrowserStack for PRs from other forks.

**Comment by XhmikosR** [comment]
IIRC the secrets are not available on PRs from forks.

**Comment by XhmikosR** [comment]
Closing since there's no way to achieve this for the time being.
