### ISSUE TITLE
Util.getSelectorFromElement and absolute path ( href="C:\web\#tab-content-id" )

### ISSUE THREAD

**Issue by Ronan-Lenor** [twbs/bootstrap#27557]
Hello,
i noticed that the method Util.getSelectorFromElement isn't removing an absolute path defined before the ID in the href attibute.

with this example:
 href="C:\web\\#tab-content-id"

the `document.querySelector("C:\web\\#tab-content-id")` will always fail to find an element.

using the data-target attribute is a solution. But it's just a circumvention of the problem.
(also, the documentation doesn't explain that trick)

**Comment by Johann-S** [comment]
Hi @Ronan-Lenor,

Sorry but I don't understand your use case here.
`document.querySelector` only allow valid CSS selector

**Comment by Johann-S** [comment]
Sorry but that's not our job to substring when you put wrong data in our plugins. Please follow our documentation and put valid selector on the `href` attribute or `data-target`

**Comment by Ronan-Lenor** [comment]
Well, can you mention somewhere in the online Documentation that href is used as a selector (where an unaware developer seeing an URI field). And then explain that the data-target attribute can be used as a fallback?

**Comment by Johann-S** [comment]
it's written here:

![image](https://user-images.githubusercontent.com/1689750/47731416-5e325f80-dc64-11e8-9f40-8c99e9a3395d.png)

**Comment by Ronan-Lenor** [comment]
yup, seen that didn't help to understand it was a Selector, as defined by mozilla
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

is it ok to rewrite it like that:
"Tab should have either a data-target or an href using a selector for a container node in the DOM."

and that would be great if you could put "selector" with a link to the Mozilla documentation.

=P

**Comment by Johann-S** [comment]
We added that about our selectors : https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/getting-started/javascript.md#selectors

Bootstrap use selectors through data api see: https://getbootstrap.com/docs/4.1/getting-started/javascript/#data-attributes

And you can put only strings on data attributes 👍

**Comment by Ronan-Lenor** [comment]
Nice details (that i didn't saw) about the selectors.

but i still think that the usage of the href attribute "alone" (as it is write: "either a data-target OR an href") is lacking the mention that bootstrap expect it to be a selector while it's URI field.

or maybe there's a section in the documentation, that i haven't see, mentioning that every html tags handled by bootstrap and that have a href attribute, is expecting a selector?
