### ISSUE TITLE
Tooltip documentation missing data-original-title

### ISSUE THREAD

**Issue by totegi** [twbs/bootstrap#27569]
```
  getTitle() {
    let title = this.element.getAttribute('data-original-title')

    if (!title) {
      title = typeof this.config.title === 'function'
        ? this.config.title.call(this.element)
        : this.config.title
    }

    return title
  }
```
the default for the tooltip title is the data-original-title attribute wich is not mentioned in the bootstrap 4 tooltip documentation

**Comment by Johann-S** [comment]
No we use `data-original-title` to store the original title and remove it from the element which trigger the tooltip.

See: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L511
