### ISSUE TITLE
All Contributors

### ISSUE THREAD

**Issue by MatheusRV** [twbs/bootstrap#27567]
All Contributors is a fair and effective way to recognize all contributors who have helped and assisted Bootstrap. All Coladorabores is transparent, democratic and easily understood. The implementation at this time can be difficult because this repository has more than 1000 contributors.

Reference:
https://github.com/kentcdodds/all-contributors

CLI:
https://github.com/jfmengels/all-contributors-cli

I vote for the file with the photo of all staying in the documentation and not in the README because of the size and proportions that the file will contain.

**Comment by XhmikosR** [comment]
Personally, I'm against this due to the amount of contributors. We do list to all contributors in the docs footer.

**Comment by MatheusRV** [comment]
The All Contributors is a way to value not only the developers of code but every community like journalists who write about bootstrap, people who help to get funding. There are several categories that All Contributors use.

**Comment by mdo** [comment]
We'll pass on this for now, but thanks for the recommendation!
