### ISSUE TITLE
SCCS variables causing printing Issues

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#27576]
2 SCCS variables are causing issues with printing in _variables.sccs

`$print-page-size` - should be `auto` (or possible `A4` or `A4 portrait` - note the capital A), but not the current `a3`.

`$print-body-min-width` - `500px` ( the current min-width, "LG breakpoint", is much too wide for A4 portrait printing, and causes shrink-to-fit in IE) Why 500 not 595? Allow for browser set printer margins

See #25629  and  #26781 

See https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size and https://github.com/cognitom/paper-css

**Comment by XhmikosR** [comment]
We need to consolidate the related issues into one @MartijnCuppens :)

**Comment by mdo** [comment]
I think we should just drop most of our print styles for v5 at this point—far too many inconsistencies between browsers to make it worth our while to get things locked in. The current variable values where the only way I was able to get any consistency.

**Comment by saturdaywalkers** [comment]
@mdo Agree. Helper classes are great, but don't set print styles in the "reboot" default.

**Comment by mdo** [comment]
Okay, flagging this in my v5 planning doc and closing out for now as a won't fix.
