### ISSUE TITLE
Error overriding $theme-colors Bootstrap 4.1.3

### ISSUE THREAD

**Issue by ScottKane** [twbs/bootstrap#27571]
$theme-colors: ( gray-dark: #0000 );
    
    @import "node_modules/bootstrap/scss/bootstrap";

Running the above is producing the following error:

    Error in plugin "sass"
    Message:
        node_modules\bootstrap\scss\_functions.scss
    Error: argument `$color-2` of `mix($color-1, $color-2, $weight: 50%)` must be a color
            on line 85 of node_modules/bootstrap/scss/_functions.scss, in function `mix`
            from line 85 of node_modules/bootstrap/scss/_functions.scss, in function `theme-color-level`
            from line 103 of node_modules/bootstrap/scss/_tables.scss
            from line 17 of node_modules/bootstrap/scss/bootstrap.scss
            from line 16 of wwwroot/scss/custom.scss
    >>   @return mix($color-base, $color, $level * $theme-color-interval);

I have also tried adding the functions and variables before changing `$theme-colors` e.g: 

    @import "node_modules/bootstrap/scss/functions";
    @import "node_modules/bootstrap/scss/variables";
    
    $theme-colors: ( gray-dark: #0000 );
    
    @import "node_modules/bootstrap/scss/bootstrap";

Sorry if I am missing something simple, I don't normally do front-end work. Thanks in advance.

**Comment by florianlacreuse** [comment]
See https://getbootstrap.com/docs/4.1/getting-started/theming/#add-to-map

This should fix it:

```
$theme-colors: (
  "gray-dark": #000000
);
```

**Comment by ScottKane** [comment]
Now that's removed the error when I compile, but the `$theme-colors` don't contain the updated color for `"gray-dark"`, it still has the original bootstrap value it gets from `$gray-800`.

**Comment by florianlacreuse** [comment]
`$colors` and `$theme-colors` are two different maps.

See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L49

**Comment by mdo** [comment]
Please see the docs on how to customize Sass maps: http://getbootstrap.com/docs/4.1/getting-started/theming/#maps-and-loops
