### ISSUE TITLE
Font size issue between input group and form control size option

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27575]
The font size of `.form-control` in `.input-group-sm` is different from a single `.form-control-sm` when customize `$input-font-size-sm` or `$input-btn-font-size-sm`.  The same is true for `lg` and `.btn`.

```scss
$input-font-size-sm: .5rem;
$input-font-size-lg: 2rem;
```

<img width="566" alt="2018-11-01 22 46 27" src="https://user-images.githubusercontent.com/4065765/47855465-08a6b000-de28-11e8-9d23-e91d1c05b267.png">

Demo: https://codepen.io/anon/pen/PyMyKo

One cause is related to the following lines:

- https://github.com/twbs/bootstrap/blob/4b15ec9cad9296821b9f1771034c7c656cc11dc3/scss/_forms.scss#L145
- https://github.com/twbs/bootstrap/blob/4b15ec9cad9296821b9f1771034c7c656cc11dc3/scss/_input-group.scss#L149

**Comment by Joyrex** [comment]
I think the text in the regular form-control-lg is too big; the input-group-lg text looks to be the right size, or perhaps a tad larger (but not as big as the form-control-lg text).
