### ISSUE TITLE
In bootstrap v 4, the navigation is not working right.

### ISSUE THREAD

**Issue by abhimanyunaikare** [twbs/bootstrap#27587]
Before opening:

https://stackoverflow.com/questions/53082868/laravel-pagination-without-style

Bug reports must include:

- Operating system and version (Windows 8)
- Browser and version (Chrome Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by patrickhlauke** [comment]
that's not a problem with Bootstrap. we can't help you with specific implementation issues. I'd wait to see if somebody on StackOverflow can help. alternatively, try slack or IRC. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
