### ISSUE TITLE
Custom checkbox/radio with NO label is misaligned

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#27598]
No label in a custom checkbox/radio makes the checkbox/radio misaligned

In this example:

    <div class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" id="customCheck1">
      <label class="custom-control-label" for="customCheck1"></label>
    </div>

http://plnkr.co/edit/lYHpjKpKR2T8b9ncpUqg?p=preview

There should not be any margin between the box and the top of the page like this:

    <div class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" id="customCheck1">
      <label class="custom-control-label" for="customCheck1">Test</label>
    </div>

http://plnkr.co/edit/AF03rpE4YltjeyjiluYn?p=preview

Also there is no such example in the documentation (there is one for non-custom checkboxes).

**Comment by florianlacreuse** [comment]
See this hack to fix it: https://stackoverflow.com/a/50798065

**Comment by ysds** [comment]
Fixed in #27566 :)

**Comment by Johann-S** [comment]
Closed because will be fixed in our next release 👍 thanks @ysds 👍

**Comment by natcohen** [comment]
@Johann-S & @ysds Thanks for the fix and sorry for the duplicate... I still think we should add it in the documentation exactly like the non-custom one
