### ISSUE TITLE
Button spacing/position in Dropdowns forms component docs

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27606]
The button placement within the dropdown menu in the Docs example doesn't look great being so squashed against the 'remember me' checkbox, I think there needs to be some additional margin at the top here: https://getbootstrap.com/docs/4.1/components/dropdowns/#forms

**Comment by XhmikosR** [comment]
You mean the button, right?

PRs welcome as usual :)

**Comment by sts-ryan-holton** [comment]
Yeah, just a small marginal amount of margin to the top will hopefully make this look a little better! I'll open a PR soon.
