### ISSUE TITLE
Tooltip not working with the 'button-remove' class

### ISSUE THREAD

**Issue by Sshahar** [twbs/bootstrap#27607]
I'm trying to figure out why does the 'button--tooltip' class work for the 'button-envelope' icon, but doeosn't work for 'button-remove' icon.

The following code's tooltip works:
[(Working screenshot of button-envelope's tooltip)][1]

    <button class="button-envelope" type="button" onclick="location.href='...'">
        <span class="button--tooltip">View envelope</span>
    </button>

This code doesn't work:
[(Cursor on (X) button-remove - tooltip not showing)][3]

    <button class="button-remove" type="button" onclick="location.href='...'">
        <span class="button--tooltip">Remove form</span>
    </button>

- In each case the cursor is placed upon the related icon.

Currently, I worked this issue around using the following code:

    <button class="button-remove button-documents" type="button" onclick="location.href='...'">
        <span class="button--tooltip">Remove form</span>
    </button>

  [1]: https://i.stack.imgur.com/AhSFi.png
  [3]: https://i.stack.imgur.com/ZnkxB.png

**Comment by Johann-S** [comment]
We do not have those CSS class in our CSS, I'm afraid you chose the wrong repository 😟
