### ISSUE TITLE
Modal data-target with number doesn't work

### ISSUE THREAD

**Issue by RemonVanNieuwenhuizen** [twbs/bootstrap#27616]
When using a ID with numbers in it as a data-target for a modal it doesn't show when clicked.
This used to work in 4.0.0 but not in 4.1.3.

Have a look at this example: [jsfiddle](https://jsfiddle.net/0c5be9wj/).

**Comment by Johann-S** [comment]
That's because an `id` with a number isn't a valid selector see:
https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/getting-started/javascript.md#selectors

and

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier
