### ISSUE TITLE
Background gradients 'intentionally broken' in documentation

### ISSUE THREAD

**Issue by boardfish** [twbs/bootstrap#27617]
On [this page](https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/utilities/colors.md), the background gradient classes are outlined. They're considered 'intentionally broken' – they don't display because `$enable-gradients` is false in the default config.

![image](https://user-images.githubusercontent.com/20680337/48068846-cc7aa300-e1cb-11e8-9cf9-8f54c91a9d7e.png)

I'm sure I'm not alone in using the docs as a visual reference. Previously, gradients were considered part of Bootstrap styling, so there are probably still use cases in design for them.

Should we add a Jekyll include to load the compiled classes for this page?

**Comment by XhmikosR** [comment]
See #27209
