### ISSUE TITLE
Outline button mouseover transition missing in macOS Safari

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#27613]
Operating system and version: macOS 10.14.1
Browser and version: Safari 12.0.1

[Reduced test case](https://getbootstrap.com/docs/4.1/components/buttons/#outline-buttons)
- Notice that instead of the animated color transitions, colors immediately swap
- I cleared Safari's cache for the this page and saw no change

Notes:
- There is a HTTP 404 error in the browser console on the test case page for the following file: 
https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js.map
- macOS Chrome displays the buttons as expected

**Comment by mdo** [comment]
Works fine here. You may have reduced motion enabled though.

**Comment by mrlife** [comment]
@mdo. Thanks, yes, it was reduced motion.
