### ISSUE TITLE
Radio groups with only icons are smaller inside form-inline

### ISSUE THREAD

**Issue by ambischof** [twbs/bootstrap#27618]
If you use a radio button group inside a form-inline and use no normal text, the buttons are smaller. In my case, I'm using icons.

only happens: `@media (min-width: 576px)`

OS: macOS High Sierra 10.13.6
Browser: Chrome  70.0.3538.77 

Test case https://jsbin.com/corelalomo/1/edit?html,output

**Comment by alecpl** [comment]
This is because `display: flex` on `.form-inline label`.

**Comment by ambischof** [comment]
@alecpl I agree, this did seem to be the cause. It shouldn't do that though.

**Comment by mdo** [comment]
Ah, this one is tough to deal with. We need to move from generic label element selectors to class-based ones moving forward. The styles are being inherited here. Might not be fixable until v5 where we could rewrite the form label styles.

/cc @twbs/css-review for ideas.

**Comment by ovpv** [comment]
@ambischof @mdo ,

After checking the demo, I found that the issue gets fixed if we set the align-items property to "stretch".

Maybe an additional class (like 'form-icons-inline') should be defined which has all properties of form-inline and  has  align-items set to "stretch" .

Thoughts?

**Comment by mdo** [comment]
We’ll want to change how these styles work entirely in v5 instead of patching with another custom class. If you need to set the flex `align-items` property, we have utilities for that :).

**Comment by mdo** [comment]
This is moot in v5 since `.form-inline` has been removed.
