### ISSUE TITLE
Feature Request: Accessibility and headings in your components

### ISSUE THREAD

**Issue by k-spen** [twbs/bootstrap#27619]
I have noticed in some of your components, headings are used.  Headings are also used by screen readers for the blind.  The readers scan the page for headings and then organize them to be browsed.  If I take a component, like an accordion that uses an h5 in the .card-header element and the last heading before my that accordion in my page was an h2, this breaks accessibility rules.  The reader would expect an h3.  Usually I just change them to divs and use role='heading'  but I am also using ng-bootstrap.  I have reached out them about this and they have recommended that I contact you guys.  They would be willing to update this when the original code is updated.  Would you please consider making your components more screen reader compliant?  Thank you.

**Comment by knoobie** [comment]
I think that's not an issue on bootstraps side. Copy+Paste the example code is not always the perfect solution. You have to know what you do (especially for the used html elements (div, headings and so on) - examples are just examples. ;)

**Comment by mdo** [comment]
We do our best to have our docs in order when it comes to this, but as @knoobie mentioned, there's only so much we can do with other people's code. If there are further changes we can make to our docs (in addition to the already open changes), let us know with specific issues or suggestions via PR.

**Comment by pkozlowski-opensource** [comment]
@knoobie  @mdo right, but we should at least make sure that:
* Bootstrap documentation pages don't suffer from the described issue (that is, there is no issue on https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example);
* there is an indication of an valid, alternative markup - to be honest I'm not sure what `<h5>` should be replaced with in this particular case, say on a page that doesn't have any other headings.

**Comment by patrickhlauke** [comment]
skipping heading levels isn't a big issue, but yes ideally they should follow whatever the current page's structure is. for authors who then grab the code, there's an assumption that they know which heading level they should be using. anyway, fixed up the accordion in docs https://github.com/twbs/bootstrap/pull/27620

**Comment by knoobie** [comment]
@pkozlowski-opensource Depending on your use case - div would be the best approach, if you don't know how many h1-hx are above the elements. See here for more details about headings: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

**Comment by pkozlowski-opensource** [comment]
Thnx @patrickhlauke for fixing docs so quickly and @knoobie for clarifications, much appreciated!

**Comment by k-spen** [comment]
Yes @knoobie, I could always copy and paste and it would be fine.  But it's the ng-bootstrap that I'm not copying and pasting :)

**Comment by k-spen** [comment]
This is just my opinion, but I would think this would be the most flexible and accessible:

``    <div class="card-header" id="headingOne" role="heading">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </button>
    </div>``

**Comment by patrickhlauke** [comment]
while in theory an ARIA heading with no `aria-level="..."` should generically be exposed/announced simply as "heading", there's a rather nasty bug in Chrome (known for a while, but don't think it had been filed anywhere until now, so went ahead here https://bugs.chromium.org/p/chromium/issues/detail?id=902508).

in any case, we assume that authors know their content, and will choose the most appropriate markup/heading level for their particular need. i don't think we can/want to genericize all our examples to make them into universally copy/pasteable code fragments...it still requires authors to know what they're doing (and BS doesn't mandate a particular structure, as the magic happens based on classes etc, not markup structures themselves.

**Comment by patrickhlauke** [comment]
closing the loop, it was pointed out to me that the chrome behavior is actually per spec. so: a `role="heading"` without an explicit `aria-level="..."` has an implicit level of 2. so...uhm...pretty pointless/erroneous
