### ISSUE TITLE
Consider adding max-width & max-height variants

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27628]
Bootstrap has classes for controlling the width and height, e.g: `.w-75` but it would be useful to also have a max width variant of this https://getbootstrap.com/docs/4.1/utilities/sizing/, similar to the max height class currently listed there.

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/27708#issuecomment-441437917.
