### ISSUE TITLE
Bootstrap logo in navbar on docs looks pixelated on corners

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27626]
On the live Bootstrap site on an Apple Macbook Pro Late 2015, latest version of Chrome the logo looks pixelated in the corners as shown. I don't think this affects Windows

![screenshot 2018-11-07 at 16 56 53](https://user-images.githubusercontent.com/25177538/48147022-41bea480-e2ae-11e8-8ea2-342e5411edba.png)

**Comment by sts-ryan-holton** [comment]
@patrickhlauke  Ah right, could we consider maybe having this as an `<img>` tag that references a white SVG logo? Or maybe consider a `<div>` element with a background image, I know this prevents you from changing the colour of the SVG via CSS/SASS, but it would save some HTML space as well maybe?

**Comment by XhmikosR** [comment]
It affects various OS/Browsers in combination with DPI values != 100%.
