### ISSUE TITLE
getbootstrap.com is not auto-redirecting to HTTPS anymore?

### ISSUE THREAD

**Issue by mattonit** [twbs/bootstrap#27622]
Today I discovered that when you go to http://getbootstrap.com, you won't be automatically redirected to the https version of the website. I can bet, the website was redirecting me from HTTP to HTTPS in the past (issue #23262 proves it). Is it a bug or this was intentional?

If this matters, I've checked this issue on Chrome 70 running on Mac OS High Sierra and Ubuntu 16.10

**Comment by XhmikosR** [comment]
It never did redirect. It'll be fixed at some point and we have an issue somewhere but I can't find it rn.

**Comment by ThomHurks** [comment]
@XhmikosR I found this out the hard way today when I opened up the Bootstrap documentation (apparently via a HTTP link) in an airport and the airport's wifi hijacked the connection to show me ads for "tax-free" goods amongst others. Please please please let it redirect to HTTPS *and* use HSTS (with preloading ideally). 

The ads injection is an inconvenience at most (well unless the ad provider gets hacked), but people can also inject random other code or alter content which is very not nice when you live in, ehhh, less democratic countries.

It also just doesn't fit Bootstrap's image of a CSS framework for the modern (secure) web.

**Comment by XhmikosR** [comment]
I don't control the Cloudflare account myself otherwise I'd done this years ago, trust me.

I will push @mdo again today.

**Comment by mdo** [comment]
Working through some weird access issues in Cloudflare, but @XhmikosR is indeed on it once that's all sorted. Thanks for keeping us on top of it. <3

**Comment by ThomHurks** [comment]
Thanks @mdo can't wait 🥇

**Comment by jpacanowski** [comment]
Hey guys... You'd better find some hobby or start a new project... Life is so beautiful...

**Comment by XhmikosR** [comment]
OK, I managed to access the Cloudflare account today so I'll take care of this soon-ish. I started enforcing https for the subdomains first.

**Comment by XhmikosR** [comment]
This is done now. If there's any issue do let us know.

Next step HSTS.

**Comment by ThomHurks** [comment]
Can confirm it redirects to HTTPS now, nice work! HSTS next is perfect, and you can even apply for [preloading](https://hstspreload.org/).

**Comment by mattonit** [comment]
I can confirm too ;) Thank you!

**Comment by ThomHurks** [comment]
@XhmikosR Great work on enforcing HTTPS so far, I also noticed that responses contain the Expect-CT header with reporting to ReportURI; if you see no incoming reports there then that header could be switched to enforce mode at some point. 

With regards to HSTS, you could enable it with a (very) low max-age value and ramp it up over time so you can see if anyone has issues.

**Comment by XhmikosR** [comment]
I don't add the header myself, it's Cloudflare that adds it. Also, the free report-uri.com account won't cut us even a day or two anyway :)

Yeah, HSTS is in my list, I wait for all subdomains to be https only first and then enforce it and never look back.

**Comment by ThomHurks** [comment]
Report-URI's free account is 10k reports per month, are you getting >10k failure reports for Expect-CT? That would be something to investigate, haven't seen that happen personally.

Ah, all subdomains https-only first, okay!

**Comment by XhmikosR** [comment]
Ah, no, I'm using report-uri for CSP reports hence the ridiculous reports I'm getting :P

**Comment by ThomHurks** [comment]
Ah yes, CSP reports can be a mess. Some browser extensions people have create them like crazy. I don't see CSP headers for getbootstrap.com on my machine though, or is that due to CloudFlare not sending it to everyone?
