### ISSUE TITLE
Input text: IE11 shows clear symbol on input - Chrome and Firefox don't

### ISSUE THREAD

**Issue by voland10557** [twbs/bootstrap#27623]
In IE11, as soon as I start to type into a text input element, a clear symbol (x) appears at the end/right side of the input element. This doesn't happen in Firefox and Chrome.
Clear symbol in IE11 is only visible when focus is on the input element.

https://getbootstrap.com/docs/4.1/components/input-group/

Chrome:
<img width="444" alt="chrome_screenshot" src="https://user-images.githubusercontent.com/4406497/48136373-c8b85080-e29f-11e8-80ef-4a6fb23dd6f2.png">
IE11:
<img width="396" alt="ie11_screenshot" src="https://user-images.githubusercontent.com/4406497/48136374-c8b85080-e29f-11e8-93b7-66464cb0dcb6.png">

Tested with:
- Bootstrap 4.1.3
- Win7
- IE11, Chrome 69+70 and Firefox 63

**Comment by voland10557** [comment]
Thanks for your reply! Sorry, my fault: I thought that behavior was coming from bootstrap - not IE11 (I didn't know _ms-clear_). It is actually handy - but in my case I implemented a universal fontawesome version of the clear control, so the ms-clear feature got in my way.

**Comment by patrickhlauke** [comment]
@twbs/team am i right in thinking we don't want to override this in our reset?
