### ISSUE TITLE
.text-wrap class doesn't seem to wrap & can't see white text on white background?

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27627]
If I'm not mistaken the `.text-wrap` class should wrap text onto both lines? If not, the white text doesn't quite work great here with this example in the screenshot. I'd suggest a similar approach to the  `.badge-warning` colour with black text and an orange background so at least it can be seen?

This has been identified in the `v4-dev` branch running locally.

I've highlighted the white text here to illustrate the problem, could be bad for accessibility.

![screenshot 2018-11-07 at 17 04 03](https://user-images.githubusercontent.com/25177538/48147716-d970c280-e2af-11e8-91cf-90550ef61685.png)

**Comment by XhmikosR** [comment]
You need to run the build scripts properly. You are using outdated dist files.

**Comment by sts-ryan-holton** [comment]
@XhmikosR  Ah right, looks like I missed that. Is there anyway to add a new NPM command that will generate the dist files and do the docs serve command? Or plug the dist command into the docs serve?

**Comment by XhmikosR** [comment]
I stopped bothering with it since it's inherently broken IMO.

And Jekyll is so freaking slow for me I just don't want to deal with it.

Things will improve if I ever manage to find the motivation + time to work on the Hugo switch.
