### ISSUE TITLE
Browser support list messed up design on next version of Bootstrap running locally

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27625]
I've recently updated my local copy of Bootstrap with the `v4-dev` branch, the supported browsers list formatting looks weird compared to the current site. I'm running locally via the `npm run docs-serve` and haven't compiled but surely this wouldn't make a difference?

See screenshot below:

![screenshot 2018-11-07 at 16 54 26](https://user-images.githubusercontent.com/25177538/48146943-12a83300-e2ae-11e8-8ff7-2093662a233f.png)

**Comment by XhmikosR** [comment]
That's how it's supposed to look.

**Comment by sts-ryan-holton** [comment]
@XhmikosR  Is it? Here's a photo from https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/, there's a noticeable difference here

![live](https://user-images.githubusercontent.com/25177538/48156109-835a4a00-e2c4-11e8-8bef-a4d1a4fd492c.PNG)

**Comment by XhmikosR** [comment]
Like I said that's how it's supposed to look.

It's not `js` anymore, it's plain text.

**Comment by patrickhlauke** [comment]
to add context: the repo itself is always ahead of the live site, since it refers to all the stuff for the next release...

**Comment by XhmikosR** [comment]
Yeah, but it's not JS anymore. We could highlight it as a shell script or something, but again, the file isn't a shell script.
