### ISSUE TITLE
Bootstrap 4 dropdown issue inside navbar fixed-top

### ISSUE THREAD

**Issue by AMeshu** [twbs/bootstrap#27638]
If you look at that generic example via phone, and rotate the orientation to landscape, you will see that the links on the dropdown are unreachable.
When I remove the class "fixed-top" from the nav it all work as expected so I guess it is something with that.
This is the [codepen](https://codepen.io/AMeshu/pen/NErxyq)
I ask the same on [SO](https://stackoverflow.com/questions/53215905/bootstrap-4-dropdown-issue-inside-navbar-fixed-top), and i got semi-solution (adding scroll to dropdown, but the links are still unreachable).
Something happen in the JS/CSS that ignores other rules when it's navbar fixed-top + dropdown and i can't figure out what.

**Comment by Johann-S** [comment]
What @coliff said 👍

**Comment by ranggirahman** [comment]
> If you look at that generic example via phone, and rotate the orientation to landscape, you will see that the links on the dropdown are unreachable.
> When I remove the class "fixed-top" from the nav it all work as expected so I guess it is something with that.
> This is the [codepen](https://codepen.io/AMeshu/pen/NErxyq)
> I ask the same on [SO](https://stackoverflow.com/questions/53215905/bootstrap-4-dropdown-issue-inside-navbar-fixed-top), and i got semi-solution (adding scroll to dropdown, but the links are still unreachable).
> Something happen in the JS/CSS that ignores other rules when it's navbar fixed-top + dropdown and i can't figure out what.

**Comment by mdo** [comment]
If you need the dropdowns to be accessible in that orientation with that number of items, you may need to customize the `max-height` further.

**Comment by AMeshu** [comment]
Thank you for the reply @mdo but since i already try this ( without success ), i would appreciate if you can show me how.

**Comment by kitsguru** [comment]
I have the same issue on a desktop where I have a long menu that extends below the bottom of the screen and elements not visible are unreachable. Removing fixed-top solves the issue as the whole page scrolls.

I'll work on a codepen for this.

This might be a use case for sub dropdowns...
