### ISSUE TITLE
popper.js integrity problem

### ISSUE THREAD

**Issue by thisismrsanjay** [twbs/bootstrap#27645]
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js' with computed SHA-256 integrity 'f/3u5OOj9c7fUgL5NEWK2U65jTKCMSzCWp6P+l+eKGI='. The resource has been blocked.

this is showing on all my bootstrap pages

**Comment by XhmikosR** [comment]
Where does this happen exactly?

**Comment by morrissey-ingenious** [comment]
@thisismrsanjay Your `integrity` check is wrong you can double check this [https://cdnjs.com/libraries/popper.js/1.14.3](https://cdnjs.com/libraries/popper.js/1.14.3) but it should be `<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha256-98vAGjEDGN79TjHkYWVD4s87rvWkdWLHPs5MC3FvFX4=" crossorigin="anonymous"></script>`
