### ISSUE TITLE
.DS_Store file in 4.1.3 dist zip file at getbootstrap.com

### ISSUE THREAD

**Issue by snixon** [twbs/bootstrap#27643]
- Operating system and version: MacOS 10.13.6
- Browser and version: Firefox 63.0.1
- [Reduced test case] 
  - Download https://github.com/twbs/bootstrap/releases/download/v4.1.3/bootstrap-4.1.3-dist.zip
  - Unzip bootstrap-4.1.3-dist.zip

- Issue: .DS_Store file made its way into the dist zip file
```$ unzip bootstrap-4.1.3-dist.zip
Archive:  bootstrap-4.1.3-dist.zip
   creating: css/
  inflating: css/bootstrap.min.css
  inflating: css/.DS_Store
  ....
```

**Comment by XhmikosR** [comment]
Already fixed in v4-dev.

**Comment by ysdw** [comment]
Same in yarnpkg:
https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/
```
dist/.DS_Store
dist/css/.DS_Store
```

**Comment by XhmikosR** [comment]
Like I said it's already fixed in v4-dev.

https://github.com/twbs/bootstrap/pull/27013
