### ISSUE TITLE
Examples -- files not found: bootstrap.min.css, bootstrap.min.js

### ISSUE THREAD

**Issue by djdavies** [twbs/bootstrap#27647]
Extracting all of the archive for bootstrap-4.1.3.zip, and then trying to open album's index.html, I still see that we actually get a ERR_FILE_NOT_FOUND for bootstrap.min.css and bootstrap.min.js. 

I have noticed that the 'examples' included do not link to their CSS and JS, and we have to manually fix the path, for example:
`<link href="../../../../../dist/css/bootstrap.min.css" rel="stylesheet">`

**Comment by XhmikosR** [comment]
This didn't work and won't work. You'll either need to build the docs or just copy and paste the assets from the browser.
