### ISSUE TITLE
Feature request: new .btn-white & .btn-black

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27654]
I can't remember if this has been mentioned already so apologies if it has but it would be great if we could have a `btn-white` and/or `btn-black` variant of the buttons here: https://getbootstrap.com/docs/4.1/components/buttons/#examples :smile:

**Comment by wolfy1339** [comment]
The `btn-dark` and `btn-light` could have aliases to those names

**Comment by sts-ryan-holton** [comment]
@wolfy1339  I don't think so because the `.btn-dark` isn't **black**, and the `.btn-light` isn't **white**

**Comment by XhmikosR** [comment]
Yeah, I don't think we'll implement this. You can always extend the current Sass code.
