### ISSUE TITLE
button-goup not working with <a> on Opera

### ISSUE THREAD

**Issue by derrodirik** [twbs/bootstrap#27664]
Hi,

i would like to build a button-group with <a> tags but the problem is that the opera engine renders badly and i can't use <button> tags because otherwise the other GET parameters will be overwritten.

https://imgur.com/a/vEp7GJq

https://codepen.io/anon/pen/eQvNWz

Bootstrap version 4

Is there any Fix?

**Comment by ysds** [comment]
Remove `type=“button”` from `a` tag :)

**Comment by derrodirik** [comment]
*facepalm* thx
