### ISSUE TITLE
Right hand side square corners with validation

### ISSUE THREAD

**Issue by j1418926** [twbs/bootstrap#27669]
I really hope I'm not missing something obvious but is there a bug where, when adding validation to an input form, the upper and lower right corners appear square instead of rounded?

In its most basic form:

```
<form>
  <div class="input-group">
    <input class="form-control">
    <div class="valid-feedback">
      Pass!
    </div>
    <div class="invalid-feedback">
      Fail!
    </div>
  </div>
</form>
```

Specifying is-valid or is-invalid still leaves the two corners squared...

**Comment by mdo** [comment]
Already an open issue for this regrettably. It's been a difficult one to solve.
