### ISSUE TITLE
bootstrap new (failing with errors)

### ISSUE THREAD

**Issue by bootstapper123** [twbs/bootstrap#27674]
i have installed
python-3.7.1.exe
Git-2.19.1-64-bit.exe
node-v10.13.0-x64.msi
bootstrap-4.1.3.zip

i was getting python 2 errors and followed below steps. python 2 errors were resolved but i am getting new errors now.

unistall and reinstall node (from control panel >>programs)
npm rebuild node-sass
npm --add-python-to-path='true' --debug install --global windows-build-tools
npm install --global node-gyp
npm install -g grunt bower
npm install -g gulp bower
npm install -g bootstrap-cli
bootstrap new
? What's the project called? (no spaces) Chapter1
? Which template would you like to use? Basic Template: includes a Sass compiler

**_gyp verb check python checking for Python executable "C:\Program Files (x86)\Python37-32\python.exe" in the PATH
gyp verb which succeeded C:\Program Files (x86)\Python37-32\python.exe C:\Program Files (x86)\Python37-32\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack File "", line 1
gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Windows\system32\Chapter1\node_modules\grunt-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Windows\system32\Chapter1\node_modules\grunt-sass\node_modules\node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1_**

**Comment by XhmikosR** [comment]
I don't see how this is related to Bootstrap.
