### ISSUE TITLE
Impossible To (Properly) Center Navbar Brand

### ISSUE THREAD

**Issue by FireController1847** [twbs/bootstrap#27676]
When creating a navbar, there is no way to center the navbar brand properly. If you have the three lines, the bar will off-set the brand to either the right or left. The only way to 'fix' this is to set the brand to be fixed or absolute. The issue is, when doing this the brand will then start moving with the dropdown when you hit the button. This makes it extremely difficult to have a properly centered brand, and I guess could be considered an OCD issue but it's super annoying.

I'm not sure if this is a bug, or a needed feature request.. I believe it could be both, but I am unsure. As of right now I believe this is a bug.

- OS: Windows 10 Home, Version 1803 (64-Bit)
- Browser: Google Chrome, Version 70.0.3538.102 (64-bit)
- Test Case: https://codepen.io/FireController1847/pen/LXLLKX/

**Comment by mdo** [comment]
This is a limitation of CSS—flexbox cannot inherently do what you want it to do without setting fixed widths on the first and last items (assuming three items). Absolute positioning is another option. So is grid layout, depending on your browser audience's intended support.

**Comment by FireController1847** [comment]
@mdo I'm not sure you're understand the issue. It centers fine, it does exactly what I want it to do. The only issue is, when you dropdown the menu, the brand MOVES with the menu. I have a STRONG belief this is an issue in how the JavaScript handles dropping down the menu, and not with any CSS or flexbox issues...

**Comment by mdo** [comment]
This still isn't a bug with Bootstrap—the navbar's navigation that you're toggling open is changing the height of the navbar. If you're asking about the vertical centering of the `.navbar-brand`, you'll need to account for that yourself since you're overriding the Bootstrap defaults.

**Comment by FireController1847** [comment]
Ugh, alright. There's so many small things here and there that bootstrap 3 had and now with bootstrap 4 it's just overall worse. Like multi-level dropdowns, and the fact that you can't fkin center the damn brand without it being off-center. It's stupid. Whatever, I'm switching to MaterialCSS anyways so.... Thanks anyways.
