### ISSUE TITLE
Feature request: Background highlight colors

### ISSUE THREAD

**Issue by mojtabakaviani** [twbs/bootstrap#27685]
Background highlight colors very useful for highlighting  background of any objects such as tables, cards for defendant it from others. 
```
.bg-highlight {
    background: #fafbfc;
}

.bg-highlight-primary {
    background: #ebf7fd;
}

.bg-highlight-success {
    background: #f2fae3;
}

.bg-highlight-warning {
    background: #fffceb;
}

.bg-highlight-danger {
    background: #fff1f0;
}
```

**Comment by sts-ryan-holton** [comment]
https://getbootstrap.com/docs/4.1/utilities/colors/#background-color

**Comment by MartijnCuppens** [comment]
These are indeed already available.

**Comment by MartijnCuppens** [comment]
@mojtabakaviani, you can edit or add highlighting colors to the `$theme-colors` and rebuild sass if you want:
https://github.com/twbs/bootstrap/blob/38ca58bf3c886d99e75e307dd6f631a2c9e2c7a2/scss/_variables.scss#L80-L92
