### ISSUE TITLE
Tooltip shows at wrong place on Windows, when using perfect-scrollbar jquery plugin

### ISSUE THREAD

**Issue by amikrop** [twbs/bootstrap#27689]
I have this code http://jsfiddle.net/cv9mps5w/ which is supposed to show tooltip on hover of the highlighted lines. It already works perfectly on linux (chrome, firefox). On windows though, the tooltips always appear at a standard, fixed place (and not over their own line). I checked the position of the current element and it is correct. I also tried to call .tooltip() just right before I enable the mouseenter event (right after dynamically positioning the element) but no luck. Even data-container="body" didn't do the trick. Note that the jsfiddle code does not work for some reason, you can just use it to download the code.

**Comment by amikrop** [comment]
Specifically, this is the code responsible for the tooltips (already included in the JSFiddle, but just in case): https://pastecode.xyz/view/ba2ed1b8

**Comment by amikrop** [comment]
[test.zip](https://github.com/twbs/bootstrap/files/2596494/test.zip)

Here is the directory tree. It works on linux but not on windows. Any help would be much appreciated.

**Comment by Johann-S** [comment]
Hi @amikrop can you provide a reduce live test (with just Bootstrap) to demonstrate your bug please ?

**Comment by amikrop** [comment]
I am not sure how much point there is in making a test case with just bootstrap, as the issue occurs in special circumstances. I mean I don't claim that "Bootstrap doesn't work on Windows". It happens in combination with other code (3rd party and mine as well). And not always (so as to say that my code is wrong), just on Windows. I was really hoping that you guys as more experienced with bootstrap could help explain why this strange behavior occurs. I was hoping I would get your guys' educated guess to be able to avoid making a reduced test case, but I 'll have to make it anyway. Some last facts that may help you point me to a right direction as where to seek the problem:

1) I can't just attach tooltips to elements I want cause there are no real elements (highlighted lines are just parts of a <pre>).
2) So, I have some <divs> with the appropriate attributes (data-toggle and title) which I set them with position: absolute and z-index: -1.
3) I detect the coordinates of mouse inside the <pre> and find out if I am on a highlighted line (and which one).
4) If I am on a highlighted line, I set the "width:" and "top:" CSS attributes of the corresponding <div> to correct values (the same as the line) and I activate its mouseenter event.

All the above WORK LIKE A CHARM on Linux (Chrome and Firefox) and that's the strange thing. Otherwise I would just assume my code is wrong. On Windows though, the tooltips appear not above their corresponding lines, but on a standard place.
I even tried calling .tooltip(container: 'body') right just after setting the new "width" and "top" of the <div> (and not on document load) so as it takes the element's last position under consideration, but no luck.
Replacing div.mouseenter() and div.mouseleave() with div.tooltip('show') and div.tooltip('hide') did not work as well.
So, what is so different in browsers on Linux and on Windows? I was hoping you guys could enlighten me and save me a huge amount of work with an aducated guess or two.
Otherwise, as I said before, I ll have to make the reduced test case.
This is not necessarily a bug report, as much as a support request.
Thanks in advance.

**Comment by amikrop** [comment]
I found the source of the problem. I could not reproduce a live example as I faced technical difficulties. I upload the code of a reduced-enough test case, though. The problem lies in the perfect scrollbar js library. Opening index.html of the uploaded code *on Windows only* showcases the problem (try hovering over the first 4-5 highlighted lines and see). If you comment out the `<script>` line that loads perfect-scrollbar in index.html though, it works correctly. So, this is proved to be the source of the problem. One solution would be for me to discard perfect scrollbar, but I can't, as it is a dependency for other js libs I am using (dashboard material js) so if I drop it it breaks my code. Any workarounds
 you can think of?
Thanks again.
[test.zip](https://github.com/twbs/bootstrap/files/2600629/test.zip)

**Comment by patrickhlauke** [comment]
As this is not an issue with bootstrap itself, but the way you're using it / how it interacts with other libraries, I'd recommend asking on stackoverflow or similar. See https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by amikrop** [comment]
I see, thanks. Personally, I resolved the issue by stopping using perfect-scrollbar (managed to get free from the dependency of my code to it), so I have no problem any more. You have the information now, you can do whatever you want with it, if anything. Cheers!
