### ISSUE TITLE
Print problems with d-print-none

### ISSUE THREAD

**Issue by mendizalea** [twbs/bootstrap#27690]
Operating system: Windows 10 x64
Browser: Chrome 70
Bootstrap version: 4.1.3

Hi,

I'm having problems printing when I use d-print-none to hide a div.

As you can see in the first photo, without the d-print-none the page break is correct in the table:

![01](https://user-images.githubusercontent.com/4532871/48725635-0cf70980-ec2d-11e8-9d28-2439331f39c0.PNG)

But when I add the d-print-none, the page break does do badly. Shows a blank line (with grey color in the picture), as if it were the page break, but then continues with more lines and when it jumps to the second page the same line divides it between the two pages.

![02](https://user-images.githubusercontent.com/4532871/48725637-0cf70980-ec2d-11e8-866c-4fe2807d8da1.PNG)

I do not know if I'm doing something wrong or I'm missing something.

And how can I print the background of a striped table? Even activating in chrome to print the background graphics does not print. DIV backgound print ok, but not those of the tables.

Thanks

**Comment by mdo** [comment]
Unfortunately I don’t think this is something that’s wrong with Bootstrap. If all you’re doing is toggling an element, the page content should just be moving up, which it appears to be doing. Moreover, without a live demo, there’s nothing I can do to help.

**Comment by mendizalea** [comment]
Hello, thanks you. Here live demo:

https://jsfiddle.net/jL3feuv1/

**Comment by XhmikosR** [comment]
Reopening for the live demo addition @mdo.

**Comment by gizmo49** [comment]
You could try placing the "d-print-none" class in each of your element
```html
<div class="row row-centered" id="filters">

	<div class="d-print-none col-md-4 col-centered bg-transparent text-dark text-center">
			FILTER 1
	</div>
	<div class="d-print-none col-md-4 col-centered bg-transparent text-dark text-center">
			FILTER 2
	</div>
	<div class="d-print-none col-md-4 col-centered bg-transparent text-dark text-center">
			FILTER 3
	</div>
	
</div>
```

**Comment by mendizalea** [comment]
Thanks @gizmo49 

I try but same problem.

Thanks,

**Comment by ffoodd** [comment]
Having a look at this, it seems that [Blink and WebKit based browsers have troubles when it comes to automatically split felx children](https://bugs.chromium.org/p/chromium/issues/detail?id=660611) and I seriousl think this is related.

I tested the test case in Firefox and it works fine, however Chromium seems to only works fine when I drop `.row`s everywhere (or disable `display: flex` on it in dev tools).

There are tons of issues related to fragmentation in either grid, flexbox and tables…

I'd recommend you to set a small workaround:
```css
@media print {
  .row {
     display: block;
  }
}
```

Using this prevents `tr` from being broken. But I'm quite sure there's nothing we can do in Bootstrap, unfortunately.

**Comment by mdo** [comment]
Closing as a stale won't fix given v5 drops the bulk of our print styles.
