### ISSUE TITLE
Problem display on phone

### ISSUE THREAD

**Issue by cyphos1973** [twbs/bootstrap#27694]
Hello
Bootstrap 4.1.1

I thinks a bug exists but I don't be sure.
Actually, i see on my phone two img and on my desktop one img

I should display 
 -> on my phone only the img "HeaderBackground_ht_mobile" with the text "test phone" 
 -> and on the desktop, only the img "HeaderBackground_ht_desktop" with the text "test desktop".

Thanks a lot for your response.

This is my codeplay
https://www.codeply.com/go/YZdc0YqTaB

`

**Comment by XhmikosR** [comment]
Just use one of the display utilities https://getbootstrap.com/docs/4.1/utilities/display/

**Comment by cyphos1973** [comment]
Sorry
I say well the docs but I always thinks this bug exists
