### ISSUE TITLE
Docs: problem display on xs

### ISSUE THREAD

**Issue by cyphos1973** [twbs/bootstrap#27704]
hello
in the docs about display
https://getbootstrap.com/docs/4.1/utilities/display/

Wrong :
Visible only on sm : d-none .d-sm-block .d-md-nonek

because on my phone landscape (between 575 and 767), I see xs et sm
Normally, it must display only sm

Thnaks you for your response

**Comment by Johann-S** [comment]
For me it works well see: https://codepen.io/Johann-S/pen/RqQaeb

I added a Badge which show in which breakpoint we are

**Comment by cyphos1973** [comment]
you can try here on phone
[https://www.codeply.com/go/WpcEhb9gO6](url)

**Comment by cyphos1973** [comment]
I didn't know for adding d-sm-flex
now, I resolve
[https://www.codeply.com/go/WpcEhb9gO6](url)
I close
