### ISSUE TITLE
Navbar toggle focus outline

### ISSUE THREAD

**Issue by FlukeFan** [twbs/bootstrap#27709]
Originally reported in #12030 (the second cosmetic issue).

It looks like the fix (to remove the outline when the toggler has focus) was lost in the change from less to sass.

**Comment by patrickhlauke** [comment]
Focus outline is consciously kept for keyboard accessibility reasons. There's a chance we might transition to using `:focus-visible` once it has actual widespread support in browsers though. xref https://github.com/twbs/bootstrap/issues/22447

**Comment by FlukeFan** [comment]
Ahh ok, thanks.
