### ISSUE TITLE
Sidebar: 3 clicks necessary to open it on mobile

### ISSUE THREAD

**Issue by PierreClementCazon** [twbs/bootstrap#27715]
Hi,

I have a problem on my mobile when I want to open my sidebar by clicking on the sidebar-toggle: the menu only opens after an average of 3 clicks, the first two don't work.

Here is a simplified page where the problem is present: https://jobphoning.com/bug-menu

Any ideas ?
Thank you in advance for your help.

**Comment by patrickhlauke** [comment]
we can't help you debug your pages. suggest trying StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
