### ISSUE TITLE
Importing boostrap.scss won't generate the same default bootstrap.css

### ISSUE THREAD

**Issue by Weizzrd** [twbs/bootstrap#27711]
I'm trying to modify some default styles so I'm importing bootstrap.scss from node modules in a custom scss file and I compile it with gulp-sass. Everything works ok except that the generated file is not identical with the default bootstrap.css. Is there something that I'm missing? The problem is that other libraries in my project use bootstrap and the styles become slightly messed up.
> With the original `bootstrap.css`
![capture](https://user-images.githubusercontent.com/10563207/48911441-58065c00-ee7b-11e8-9169-59ae7d65ff35.JPG)

>After compiling  `bootstrap.scss`
 ![capture2](https://user-images.githubusercontent.com/10563207/48911444-5a68b600-ee7b-11e8-8f7f-a6e16c398c3f.JPG)

**Comment by InsanityMeetsHH** [comment]
You need to install [gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer).
Here is an [example](https://github.com/InsanityMeetsHH/gulp-templating/blob/master/gulpfile.js#L24) how solve this.

**Comment by patrickhlauke** [comment]
http://getbootstrap.com/docs/4.1/getting-started/build-tools/#autoprefixer

**Comment by Weizzrd** [comment]
> 
> 
> You need to install [gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer).
> Here is an [example](https://github.com/InsanityMeetsHH/gulp-templating/blob/master/gulpfile.js#L24) how I solve this.

Thanks a lot for the answer!

> 
> 
> http://getbootstrap.com/docs/4.1/getting-started/build-tools/#autoprefixer

Thank you, apparently I missed this.
