### ISSUE TITLE
boxing

### ISSUE THREAD

**Issue by dpertal** [twbs/bootstrap#27725]
Hi,
https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/ as is this example, but in boxing
how can I do that?
I want to do as in the picture below!
![boxing](https://user-images.githubusercontent.com/8488074/48999994-f1c25780-f160-11e8-8ca9-994e615fa7ef.png)
I am waiting for any answer
Thanks!

**Comment by patrickhlauke** [comment]
for help/how-to advice, please use StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker
