### ISSUE TITLE
col-sm not working

### ISSUE THREAD

**Issue by OStefani** [twbs/bootstrap#27724]
col-sm class doesn't work if there is a col-md class in the code when I use google chrome developer tool
why?
https://codepen.io/OStefani/pen/QJxNyY

**Comment by coliff** [comment]
It looks like it is working correctly.

It is full-width in the container at 767px width viewport which is expected. (add the class `border` to the `container` div to see it clearly.

REF: http://getbootstrap.com/docs/4.1/layout/grid/#grid-options

**Comment by mdo** [comment]
Closing since @coliff explained.
