### ISSUE TITLE
Why doesn't use `.sr-only` in spinner?

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27727]
https://twbs-bootstrap4.netlify.com/docs/4.1/components/spinners/#about

> For accessibility purposes, ...., using a text hiding technique to prevent it from rendering on screen.

Text hide technique is not a modern approach (#24890). IMO we should use `.sr-only` to hide `Loading...` text:

```html
<div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div>
```

**Comment by patrickhlauke** [comment]
don't think there's any particular disadvantage to how it's done now. my comment about modern/not modern was to do with `text-hide` as a class/old-school image replacement techniques

**Comment by ysds** [comment]
@patrickhlauke Thanks for your reply. Current the `text-indent: -999em;` technique is a outdated technique, the [html5-boilerplate technique](https://github.com/h5bp/html5-boilerplate/commit/aa0396eae757) is better. But that is the same with the [deprecated `text-hide()` mixin](https://github.com/twbs/bootstrap/blob/056e28d9e084c134f6c58ad0ede31467a51294e6/scss/mixins/_text-hide.scss). If deprecate the text-hide() minix, we should use `.sr-only` for consistency.

**Comment by mdo** [comment]
@ysds Honestly did it the way it’s currently implemented because it’s engrained in my head to do it that way hah. We can definitely use `.sr-only`.

**Comment by XhmikosR** [comment]
Can someone make a PR?

**Comment by ysds** [comment]
Leave it to me 🙂
