### ISSUE TITLE
No modal backdrop in Firefox

### ISSUE THREAD

**Issue by albawan** [twbs/bootstrap#27743]
Using v4.1, windows 10 and Firefox 63.0.3 I do not see the darkened backdrop when opening a modal. Tested this on different projects and also on the official website. On my system the backdrop does work in Chrome, Edge, and IE.

**Comment by albawan** [comment]
When restarting Firefox and trying again the backdrop will show for a split-second before disappearing.

**Comment by Johann-S** [comment]
Hi @albawan,

I don't have any issues with Win10 and Firefox 63.0.3 😟

**Comment by albawan** [comment]
I discovered the issue (which was local and did not have to do with bootstrap). My adblocker _AdGuard_ is responsible for blocking the backdrop. I tried using another add blocker _Adblock Plus_ which caused no issues. 

I am closing it because this is not a bootstrap issue.
