### ISSUE TITLE
Don't set color for button's :hover state if the same as the button's color

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#27745]
Would that be possible to not define `color` for buttons in :hover (and :active) state if the color would be the same as the button color in normal state? It would make some style overriding simpler.

I'm talking about `.btn-primary`, `.btn-secondary`, etc.

**Comment by mdo** [comment]
I'd love to not set it, but some folks asked for it, so we ended up adding the extra properties. Can't get rid of it now in v4 though—I'd consider that semi-breaking for backward compatibility.

**Comment by mdo** [comment]
Closing per last comment for now.
