### ISSUE TITLE
Npm Start Showing Modifications to Dist Files

### ISSUE THREAD

**Issue by pixelshaded** [twbs/bootstrap#27740]
Windows 10
Using branch v4-dev.

Ran
```
npm ci
bundle install
```

At this point no files have changed.

Ran ```npm start```, killed the process after opening the docs in the browser, then ran ```git status```.

```
modified:   dist/css/bootstrap-grid.min.css
modified:   dist/css/bootstrap-grid.min.css.map
modified:   dist/css/bootstrap-reboot.min.css
modified:   dist/css/bootstrap-reboot.min.css.map
modified:   dist/css/bootstrap.css
modified:   dist/css/bootstrap.css.map
modified:   dist/css/bootstrap.min.css
modified:   dist/css/bootstrap.min.css.map
modified:   site/docs/4.1/assets/css/docs.min.css
modified:   site/docs/4.1/assets/css/docs.min.css.map
```

My initial expectation was that since I didn't change any source files, the output shouldn't have changed.

If I look at the diff of bootstrap.css for instance:
Its changing ```.btn-group-vertical > .btn``` selector's flex values from 0 to 1.

This seems like a significant change. Should this be happening?

**Comment by XhmikosR** [comment]
Yes, it's normal, we don't update the dist files on each commit.
