### ISSUE TITLE
Documentation for Dismissible Popovers needs clarification

### ISSUE THREAD

**Issue by coredumperror** [twbs/bootstrap#27742]
I just wasted a ton of time trying to figure out why my Dismissible Popovers weren't working because the docs don't make it clear that (unlike the rest of Bootstrap's functionality) the javascript that's displayed alongside the markup is actually *required*.

I think this is a docs bug because Dismissible Popovers, unlike *every* other Bootstrap component I've ever used, actually require the use of javascript rather than just `data-` attrs and such in the markup. I do not know why this is, but I couldn't get Dismissible Popovers to work in Chrome 72 on macOS Mojave without it.

I propose one of two solutions:

1) Remove the `role="button" data-toggle="popover" data-trigger="focus"` attributes from the [example](https://getbootstrap.com/docs/4.1/components/popovers/#dismiss-on-next-click). When you're using the javascript (which you have to do), they are redundant, and therefore confusing. I had assumed that their existence would be sufficient with no additional javascript, because that's how the rest of Bootstrap works.

2) Add additional instructions to the [example](https://getbootstrap.com/docs/4.1/components/popovers/#dismiss-on-next-click) that make it clear that the javascript is actually *required* for this particular style of the component.

**Comment by Johann-S** [comment]
Hi @coredumperror,

I think you didn't read well our documentation here: https://getbootstrap.com/docs/4.1/components/popovers/#overview

It's written: 
>Popovers are opt-in for performance reasons, **so you must initialize them yourself.**

- The `data` attributes aren't redundant, they are convenient because it's easy to config your popover with them.

**Comment by coredumperror** [comment]
> Popovers are opt-in for performance reasons, **so you must initialize them yourself.**

How is anyone supposed to know what that means? It doesn't mention anything about the data attributes not working by themselves, or that you *have* to use Javascript. 

And since none of the other examples on that page includes any Javascript, that means users who want something besides Dismissible Popovers are going to be *even more confused* than I was.

> The data attributes aren't redundant, they are convenient because it's easy to config your popover with them.

I didn't claim that every `data` attribute is redundant. I specifically said that `role="button" data-toggle="popover" data-trigger="focus"` is redundant, because they collectively do exactly the same thing as the example javascript:
```
$('.popover-dismiss').popover({
  trigger: 'focus'
})
```
