### ISSUE TITLE
custom-select inside a input-group-sm does not render as custom-select-sm

### ISSUE THREAD

**Issue by tiesont** [twbs/bootstrap#27753]
### Operating system and version 

Windows 10 Pro
    
### Browser and version

Chrome 70.0.3538.110 (64bit), Firefox 63.0.3 (64bit), IE11, MS Edge

### Code to reproduce

Bootply (using 4.1.3):

https://www.bootply.com/iOZaCYxDfA

Code:

```html
<div class="input-group input-group-sm">
  <div class="input-group-prepend">
    <div class="input-group-text">Label here</div>
  </div>
  <select class="custom-select">
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
  </select>
</div>
```

From the [input-group documentation](http://getbootstrap.com/docs/4.1/components/input-group/#sizing), I was assuming my custom-select would automatically render the same as a small custom select if I added the `input-group-sm` class. It does not appear to be the case. Is this intentional?

**Comment by herbalite** [comment]
Add form-control, as it is shown in the example page you are referring too, and things should be fine
```
  <select class="custom-select form-control">
```

**Comment by tiesont** [comment]
@herbalite That changes how the custom select renders, and really shouldn't be necessary. I get the sizing I was looking for by adding `custom-select-sm`, but the point is that the docs don't reflect what (I assume) was intended to happen.

**Comment by alecpl** [comment]
Probably fixed by: https://github.com/twbs/bootstrap/pull/27677

**Comment by mdo** [comment]
Closing per last comment.
