### ISSUE TITLE
Fix wrong docs npm command

### ISSUE THREAD

**Issue by urielz1987** [twbs/bootstrap#27752]
I'm trying to run the [Running documentation locally](https://www.npmjs.com/package/bootstrap#running-documentation-locally), I followed to commands -

- bundle install
- npm install

and when I run the npm start I get an error -

`npm ERR! missing script: start`

How can I run this documentation correctly ?

**Comment by Besam-juajua** [comment]
In your package.json, without the word "start" in "scripts"
`"scripts": {
    "start": "webpack-dev-server --hot"
  },`

**Comment by urielz1987** [comment]
@Besam-juajua  You mean I have to add this line ? 

So why it doesn't already in the package.json ?

**Comment by XhmikosR** [comment]
There's no `start` script nor we mention that anywhere.

`npm run docs-serve` or `bundle exec jekyll s`

**Comment by urielz1987** [comment]
@XhmikosR  ,Thank you it helped, but yes you did mention , you wrote  -

>  Run npm start to compile CSS and JavaScript files, generate our docs, and watch for changes

**Comment by XhmikosR** [comment]
Hmm, I definitely didn't add this there, and I have no idea how it was added there.

I'll change the docs, but in general, the local dev scripts are a little messy and they will change hopefully soon.

**Comment by XhmikosR** [comment]
In fact I don't see anywhere in our docs mentioning `npm start`.

This will improve after we switch to Hugo.
