### ISSUE TITLE
Bootstrap CSP compatibility - adding a custom navbar toggler icon

### ISSUE THREAD

**Issue by mjgs** [twbs/bootstrap#27763]
_Originally posted by @mjgs in https://github.com/twbs/bootstrap/issues/25394#issuecomment-443697450

**Comment by XhmikosR** [comment]
No need to make a new issue, though.

**Comment by mjgs** [comment]
Seems like there was as posting a reply didn't re-open the issue.

**Comment by XhmikosR** [comment]
It doesn't automatically re-open an issue.

**Comment by mjgs** [comment]
@XhmikosR the issue now has some visibility in the other thread, thanks.
