### ISSUE TITLE
Flex basis

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#27772]
I thinks You can add more flex utilities.
Here is for `flex-basis`. What does it do?
It stretches div to full width. 
It could be useful (I needed it as in screenshots).
There could be also variations like 25, 50, 75 (as in `w-x`)
```
.flex-basis-100 {
  flex-basis: 100% !important;
}

.flex-basis-0 {
  flex-basis: auto !important;
}


@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    .flex#{$infix}-basis-100 {
      flex-basis: 100% !important;
    }
    .flex#{$infix}-basis-0 {
      flex-basis: auto !important;
    }
  }
}
```

![bootstrap-basis-md](https://user-images.githubusercontent.com/420691/49500918-0fcf3c80-f872-11e8-84ff-fa7e7a92546d.png)
![bootstrap-basis-sm](https://user-images.githubusercontent.com/420691/49500919-0fcf3c80-f872-11e8-95c8-f76e366f6e46.png)

**Comment by florianlacreuse** [comment]
Just to let you know that this is already possible with the current available utilities: https://codepen.io/anon/pen/zMVOyK

**Comment by Johann-S** [comment]
According to @florianlacreuse answer I close this issue, plus we don't plan to add more utilities.

/CC @twbs/css-review If I'm wrong do not hesitate to re open this issue

**Comment by MartijnCuppens** [comment]
Yup indeed, thanks for answering this, @florianlacreuse!

**Comment by florianlacreuse** [comment]
@piernik Confirm, there are no reponsive sizing utilities and according to this [comment](https://github.com/twbs/bootstrap/issues/26429#issuecomment-385591590) there are no plans to add responsive variants any time soon (for sizing things).
