### ISSUE TITLE
Custom select small size not applying

### ISSUE THREAD

**Issue by ionesculiviucristian** [twbs/bootstrap#27775]
I applied the form-control-sm class on a custum-select but that doesn't work:
https://www.bootply.com/GWW8z0E62V

I'm doing it wrong or this is not supported? I'm using version 4.1.3 but seems to work "as expected" on 4.0.0 - 4.1.2.

**Comment by florianlacreuse** [comment]
You need to remove `.form-control` and use `.custom-select-sm` instead of `.form-control-sm`.

See doc: https://getbootstrap.com/docs/4.1/components/forms/#select-menu

Your test case fixed: https://www.bootply.com/1omAQj3IOL

**Comment by ionesculiviucristian** [comment]
Many thanks. I was looking on another version of the docs, I guess.

**Comment by florianlacreuse** [comment]
Happy to help. Can you close the issue? Thanks.
