### ISSUE TITLE
Toast animation doesn't work

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27779]
Fade animations are expected according to the [JS documents](https://twbs-bootstrap4.netlify.com/docs/4.1/components/toasts/#options) and existence of the `.fade` class, but it looks like not working. To reproduce, click any toast `close` button or run `$('.toast').toast('show')`, `$('.toast').toast('hide')`.

**Comment by Johann-S** [comment]
It's because we use `display: block;` and `display: none;`

**Comment by Johann-S** [comment]
If you want to test my fix: https://deploy-preview-27792--twbs-bootstrap4.netlify.com/docs/4.1/components/toasts/#basic 👍
