### ISSUE TITLE
Something to think (or not) about

### ISSUE THREAD

**Issue by ionesculiviucristian** [twbs/bootstrap#27778]
I'd like to use as many classes as needed to design a web app's interface, without redoing the same things all over again. Thinks like d-none-sm or mb-1 are very clean for me without the need to add them in custom classes all the time. I was doing something like this:

```html
    <div class="d-inline-block position-relative">
      <i class="fas fa-times position-absolute position-right-center z-index-1 hoverable"></i>
    </div>
```

The positioning (place not type), z-indexing and hoverable are things that are frequently used and would be good to have them as class tools when building interfaces. Just my thoughts...

**Comment by mdo** [comment]
We'll keep that in mind alongside future feature requests, thanks!
