### ISSUE TITLE
dropdown.js line 471

### ISSUE THREAD

**Issue by emilmuller** [twbs/bootstrap#27786]
Incidentally, while creating my own dropdown class that has no jQuery dependencies, I came across this peculiar line:

`[...] (event.which !== ESCAPE_KEYCODE || event.which !== SPACE_KEYCODE) [...]`

which, by all logical means, will always be true. Should it be && ?

Line 471, dropdown.js :)

**Comment by patrickhlauke** [comment]
indeed, well spotted. https://github.com/twbs/bootstrap/pull/27787

**Comment by emilmuller** [comment]
@patrickhlauke Also, hide() does not set aria-expanded = false :)

**Comment by Johann-S** [comment]
Maybe it can help you @emilmuller we already wrote our Dropdown plugin without jQuery here: https://github.com/twbs/bootstrap/blob/v4-without-jquery/js/src/dropdown.js

**Comment by emilmuller** [comment]
@Johann-S Thanks! I'm replacing my code now :)
