### ISSUE TITLE
A comprehensive reference guide to all functionality is required...

### ISSUE THREAD

**Issue by LJ9999** [twbs/bootstrap#27783]
...and needs to be made easily accessible. I can't believe there is not such a document anywhere on the internet. Do people have to waste time figuring it all out?

**Comment by patrickhlauke** [comment]
what's missing from https://getbootstrap.com/docs/4.1/ that you'd like to see?

**Comment by herbalite** [comment]
Something like this?
https://hackerthemes.com/bootstrap-cheatsheet/

There are other results when searching the Web for Bootstrap4 cheatsheet

**Comment by arechsteiner** [comment]
Thank you for mentioning my cheat sheet @herbalite.

FWIW I think the official documentation is pretty damn good. It fits the description "comprehensive reference guide" better than my cheat sheet.

**Comment by jipexu** [comment]
really ? the BS doc seems me better than numerous project on internet with long, dark and dry api list without any example ... Even if is not totally complete i agree with @arechsteiner the BS doc is good ! and cheat sheet is another useful tool  !
