### ISSUE TITLE
I think i found a typo but i'm not sure it might have been intended.

### ISSUE THREAD

**Issue by spil3141** [twbs/bootstrap#27796]
![screen shot of typo](https://user-images.githubusercontent.com/21377035/49624639-8f494100-fa15-11e8-8db8-4a0367576458.png)

Bootstrap documentation main page:
![screen shot 2018-12-07 at 11 46 15 am](https://user-images.githubusercontent.com/21377035/49624685-cae40b00-fa15-11e8-9095-b4b8ab104048.png)

**Comment by mdo** [comment]
Intended to be as-is. Thanks though!
