### ISSUE TITLE
Deprecate/Remove Prefix Styles

### ISSUE THREAD

**Issue by thecodingdude** [twbs/bootstrap#27793]
If we look at the latest [boostrap.css](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css) we can observe the following:

-ms-: 492
-webkit-: 57
-moz-: 20

total: 569 browser prefixes.

I'd like to eventually see this number get to 0 since prefixes are not CSS spec compliant. Is there any we can remove? For example, -ms-flexbox might be redundant now?

**Comment by mdo** [comment]
These can only change when we change browser support, which only happens in major releases. v5 will drop IE10 and IE11, possibly some older Firefox, Safari, and Chrome versions. That will reduce those. If you need to reduce them on your end, you can compile the source Sass without Autoprefixer.
