### ISSUE TITLE
Modified theme colors map can not change color of some components

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#27801]
From my comment: https://github.com/twbs/bootstrap/issues/27712#issuecomment-444167717.

About a way of changing the theme colors, the document explains as:
https://getbootstrap.com/docs/4.1/getting-started/theming/#modify-map

But, it actually is incorrect after #27378.

demo1: https://codepen.io/fellows3/pen/WYBbEM

```scss
$theme-colors: (
  "primary": green
);
```

demo2: https://codepen.io/fellows3/pen/ZmNYNd

```scss
$primary: green;
```

**Comment by MartijnCuppens** [comment]
I think we'll need to revert to the state before #27378 to avoid breaking changes.

The way we define colors need to be reviewed at some point because we do not document what the purpose of `$primary` is in our documentation. 

Ref: #23908

**Comment by mdo** [comment]
I'm okay with reverting that other PR if it solves this problem for now. We can revisit how we use maps/variables with our v5 changes.
