### ISSUE TITLE
Non-horizontal form-group using fieldset renders legend font-size different than label

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#27805]
When using a `<fieldset>` as the root element of a non-horizontal `.form-group` (i.e. no `.form-row` or `.row`), the `<legend>` element renders differently than a `<label>` (specifically the font-size being set to `1.5rem` via reboot)

```html
<div class="form-group">
  <label for="input">Label</label>
  <input type="text" class="form-control">
</div>

<fieldset class="form-group">
  <legend>Foobar</legend>
  <div role="group">
    <div class="form-check form-check-inline">
      <input id="check1" class="form-check-input" type="checkbox" name="checks" value="A">
      <label for="check1" class="form-check-label">Radio A</label> 
    </div>
    <div class="form-check form-check-inline">
      <input id="check2" class="form-check-input" type="checkbox" name="checks" value="B">
      <label for="check2" class="form-check-label">Radio B</label> 
    </div>
  </div>
</fieldset>
```

Renders:
![image](https://user-images.githubusercontent.com/2781561/49701433-b4c77d80-fbc2-11e8-8840-e4f88d70d1a8.png)

Manually adding a style `font-size: inherit;` or `font-size:  1rem;` to the `<legend>` appears to fix this issue, but it would be preferential not to have to add the additional styling.

Proposed solution (to mimic `<label>` default) in `/scss/_forms.scss` before the `.col-form-label` rule definition:
```css
.form-group legend {
  font-size: inherit;
}
```

Which renders the following (using the same above HTML):
![image](https://user-images.githubusercontent.com/2781561/49701608-7c28a380-fbc4-11e8-9dc6-f4cd470c9f25.png)

**Comment by mdo** [comment]
Every `<legend>` has that font-size though, it's not a matter of being in a particular form layout. See https://codepen.io/anon/pen/BvKwNV for an example. I don't think this is something we'd change.

Thoughts @MartijnCuppens or @andresgalante?

**Comment by tmorehouse** [comment]
When creating a non-horizontal form composed of multiple inputs and, say, a group of radios or checkboxes, the checkboxes and radios should be placed in a fieldset for proper semantic markup (and for screen readers).  Labels cant be associated with fieldsets, so one uses a legend.  

The default behaviour breaks the cadence of the form "labels" as the `<legend>` pops out visually at 50% larger font size than a `<label>`.

**Comment by mdo** [comment]
Oh I agree it should be improved, but overriding like that could cause issues for folks who've built around this existing behavior.

> Since it is suggested it can be used on fieldsets, the form-group component should probably treat labels and legends the same stylistically.

Eh, just because a particular HTML element can have a class doesn't mean something nested within that element should change. Again, I agree there should be some control here, just not in the solution offered here thus far.

In all likelihood, we should move from general `label { ... }` rulesets to `.form-label { ... }` to help avoid issues like this as we could just apply that class. Perhaps for now v4 should have `label, .form-label { ... }` or something akin?

**Comment by akrawchyk** [comment]
This is already merged https://github.com/twbs/bootstrap/pull/28450 but would a follow-up PR that includes the above decision make sense @mdo ?

**Comment by akrawchyk** [comment]
@tmorehouse looks like a `$legend-font-size` variable was added to allow theming the default `<legend>` element: https://github.com/twbs/bootstrap/commit/855d763ae57fd1dea1c26af1f197d3d84002dc55#diff-d8ee409a461718bfb6240710c8c73382R345

Can this be backported to v4?

**Comment by louismaximepiton** [comment]
As the v4 reached the end of support is this still a thing ? Should Bootstrap default to `$legend-font-size: null/inherit/$form-label-font-size !default;` in v5? Imo, since it is a value to change it shouldn't be breaking for folks so it might be a thing to think about.

**Comment by mdo** [comment]
Going to close this out as stale. If there's still desired effort here, we could see about a new class or something for the legend, but that's probably covered already by our font-size utilities.
