### ISSUE TITLE
Coding conventions documentation

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#27815]
A lot of (junior) developers use Bootstrap as starting point for front end development, but we don't reference to guidelines like http://codeguide.co/ in our docs where they can find out the best practices for HTML & (s)css. 

Maybe there are also other interesting sites we can refer to?

**Comment by XhmikosR** [comment]
@mdo: maybe you should move this repo under the twbs org?

**Comment by MartijnCuppens** [comment]
I agree, maybe we should work on a `v2` because some information might be a bit outdated? Things we should definitely change:
- Add something about stylelint
- Add something about autoprefixer
-  Remove the _IE compatibility mode_ section

@XhmikosR, we once talked about publishing the stylelint config somewhere, how shall we approach this?

**Comment by okoyeO** [comment]
Make editing easily accessible in bracket 1.14

**Comment by mdo** [comment]
Stubbed out a first pass at #32778 (where we already have Autoprefixer documented).
