### ISSUE TITLE
Disabled radio buttons do not indicate selection

### ISSUE THREAD

**Issue by kleinph** [twbs/bootstrap#27814]
A disabled radio button group does not indicate the (pre)selcted value as other form fields do. I am not sure if this is intended behavior, but native radio buttons do show their state when disabled.

- Operating system: Arch Linux
- Browser and version: Firefox 63.0.3, Chromium 71
- Reduced test case: https://codepen.io/anon/pen/OrVLOV

**Comment by ysds** [comment]
x-ref: #23544

**Comment by kleinph** [comment]
@ysds as far as I understand, the referenced PR was to fix a problem where the active state could be triggered on an inactive button. In my issue the button should indicate its preset state also when disabled analogous to native radio buttons.

**Comment by ysds** [comment]
OK, I understand. Probably, that is a styling issue of buttons. 

<img width="550" alt="2018-12-14 23 31 37" src="https://user-images.githubusercontent.com/4065765/50008735-71bd3e00-fff8-11e8-8409-0d8b8f5b3744.png">

Demo: https://codepen.io/anon/pen/BvKaqz

@kleinph I recommend you to change the issue title for clarification.

**Comment by tmorehouse** [comment]
I'm wondering if disabled elements should just have a reduced opacity for simplicity in styling?

**Comment by kleinph** [comment]
@ysds sure, how should I name it?
BTW your demo makes it pretty clear what my issue is. Thanks!

**Comment by tmorehouse** [comment]
Maybe active+disabled should just be mentioned as incompatible/not-supported for button mode?

**Comment by mdo** [comment]
Well, `.active:disabled` seems logical and useful—a button is selected and it's processing/loading, for example. `:active:disabled` isn't useful though because disabled shouldn't be interactive. Perhaps the problem is coming from us conflating those two vs separating the `.active` from `:active`?

**Comment by tmorehouse** [comment]
In the above examples it would really be `:checked:disabled`, rather than `active:disabled` (button style checkboxes)

**Comment by ysds** [comment]
I agree separating those two state:

- Pressed (`:active`)
- Selected (`:checked`, `aria-pressed`, `aria-selected`, `aria-current`) - `.active` class

**Comment by mattressauthority** [comment]
Well, .active:disabled seems logical and useful—a button is selected and it's processing/loading, for [example](https://gist.github.com/mattressauthority/13b8d120fd4c26844cbf8fc8d5a59812). :active:disabled isn't useful though because disabled shouldn't be interactive. Perhaps the problem is coming from us conflating those two vs separating the .active from :active?

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
