### ISSUE TITLE
Bootstrap's out of the box values for column gutters and spacing utilities are incoherent

### ISSUE THREAD

**Issue by alejandroiglesias** [twbs/bootstrap#27816]
I'm wondering for some time now why the grid gutter has (out of the box) a `15px`/`30px` gutter value (`15px` * 2 = `30px`) while the spacing utilities have values in `rem` unit which translate (for a standard `16px` base font size) to `4px`, `8px`, `16px`, `24px`, `48px`. It was just a doubt until now I found a case in which this might be (or is) an issue.

The current project I'm working on needs a custom three-column layout that I made with flexbox (including `min-width` and `max-width` limits) and works fine for us. For the rest of the app, we still use the Bootstrap grid. The problem is that if I try to use spacers for the margins/paddings of the custom layout to match Bootstrap grid's gutters, I end up with different values. Furthermore, if I try to customize the grid gutters so that they are `24px` (ie, so it matches `.ml-4`, `.pl-4`, etc) there are many other components that still rely on `30px` values, which make the customization quite a project. Also, it would be ideal to use the even values of the spacing utilities so that in case of adjustment (ie, halving the size of gutters/paddings) it's still doable without decimal values and sub-pixel rendering issues. Finally, wouldn't the grid benefit from using `rem` values as well?

The current difference in values seems incoherent but at the same time, I guess there has to be a rationale for it. Can you provide some insights into this?
Thanks.

**Comment by mdo** [comment]
Regarding units, see http://getbootstrap.com/docs/4.1/layout/grid/#grid-options.

Regarding customizing the grid with spacers, we're shipping negative margins in v4.2 (see #26825). This will allow folks to completely control their grid gutters, and an example was added to demonstrate it with the grid. Still need to tackle #27072.
