### ISSUE TITLE
Popover positioned partially off-screen and cropped

### ISSUE THREAD

**Issue by peterblazejewicz** [twbs/bootstrap#27817]
The `top` popover, when triggered near the page border, is being rendered in such way it gets cropped:
https://stackblitz.com/angular/rdokjdpkdoq
https://ng-bootstrap.github.io/#/components/popover/examples

![image](https://user-images.githubusercontent.com/14539/49836572-750bbc00-fda3-11e8-81cf-d5d794944a18.png)
                                                                              
The BS uses popper.js, rendering in 4.1.3:

![image](https://user-images.githubusercontent.com/14539/49836690-dcc20700-fda3-11e8-93be-236daf984b04.png)

ng-bootstrap: v4.0.0
Chrome, macOS

**Comment by Johann-S** [comment]
Hi @peterblazejewicz,

I think your issue is for this repository: https://github.com/ng-bootstrap/ng-bootstrap
As you noticed we use Popper.js to handle those use cases, but I'm not sure if ng-bootstrap use Popper.js under the hood or not 🤔 

If I'm wrong tell me and I'll re open this issue.

**Comment by peterblazejewicz** [comment]
@Johann-S 
yes, you're correct. I'm feeling stupid and could blame only the late hour when posting this.
🤦‍♂️ 
Sorry for bumping up the counter
> As you noticed we use Popper.js to handle those use cases, but I'm not sure if ng-bootstrap use Popper.js under the hood or no

They do not, so the case should be reposted. Will do this asap.
Thanks!
