### ISSUE TITLE
Remove similar colors

### ISSUE THREAD

**Issue by Scrabble96** [twbs/bootstrap#27819]
I have recently used yellowlab.tools to rate a website that is using Bootstrap 4.1.3/css/bootstrap.min.css.

It has flagged up 12 similar colors in that file. They are:

#badaff and #b8daff
#ffffff and #fdfdfe
#ffffff and #fefefe
#e2e6ea and #dee2e6
#eeeeee and #f1f1f1
#eeeeee and #ebebeb
#23272b and #212529
#f8f9fa and #f7f7f7
#343a40 and #32383e
#000000 and #040505
#fdfdfe and #fefefe
#171a1d and #16181b

Are they all necessary?

**Comment by XhmikosR** [comment]
I doubt anyone is going to look into such stuff.
