### ISSUE TITLE
Duplicate css selectors in 4.1.3/css/bootstrap.min.css

### ISSUE THREAD

**Issue by Scrabble96** [twbs/bootstrap#27821]
Not exactly a bug, but unnecessary, are the following duplicated selectors:

 pre (x3)
.table-bordered td, .table-bordered th (x2)
hr (x2)
.navbar-expand>.container, .navbar-expand>.container-fluid (x2)
.container (x2)
.table (x2)
.table td, .table th (x2)
body (x2)
.table .thead-dark th (x2)
.table-dark (x2)
.dropright .dropdown-toggle::after (x2)
.dropleft .dropdown-toggle::after (x2)
.dropleft .dropdown-toggle::before (x2)
.navbar (x2)

**Comment by XhmikosR** [comment]
Similarly as #27819

**Comment by Scrabble96** [comment]
Well, duh. Messy code slows down site performance.

**Comment by Scrabble96** [comment]
I’m not sure what a ‘PR’ is, but I’m guessing it’s a more official/systematic way of submitting problems and corresponding solutions. If you can point me towards some instructions on how to submit these correctly, I’d be more than happy to help.

For example, using the W3C CSS Validator tool (which I’m sure you will agree is a useful tool) shows that the first 30 lines of code at [https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css] (https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css) - and therefore carried through to the minified version - have parse errors. Basically, the double hyphen in front of each item is not valid. Change it to just one hyphen and it’s fine. How would I submit that?

**Comment by XhmikosR** [comment]
Re CSS validator, unfortunately the tool is wrong, i.e. doesn't support the custom variables.

Everything else was fixed after I bugged @sideshowbarker some time ago.

Like I said, the tools don't mean anything by themselves.

**Comment by sideshowbarker** [comment]
>> For example, using the W3C CSS Validator tool (which I’m sure you will agree is a useful tool) shows that the first 30 lines of code at [https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css] (https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css) - and therefore carried through to the minified version - have parse errors. Basically, the double hyphen in front of each item is not valid.
>
> Re CSS validator, unfortunately the tool is wrong, i.e. doesn't support the custom variables.

Yeah, try checking it instead with https://validator.w3.org/nu/ (which does support CSS variables):

https://validator.w3.org/nu/?doc=https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css

…that reports only one error:

> Error: size: Property size doesn't exist

…which is probably also a false positive

**Comment by Scrabble96** [comment]
Ok. Thank you, both. I'll make a note of the 'new' validator. (I wonder why they don't 301 redirect the old one to the new one).

There are quite a few -webkit prefixes which are no longer needed - e.g. -webkit-text-decoration. Or are they there to support those who still insist on using ancient browsers?

**Comment by XhmikosR** [comment]
Everything that needs to be there should be there already since we use autoprefixer to handle this task.

**Comment by Scrabble96** [comment]
Going back to my original post, there are duplicate selectors, e.g.

line 4238
.navbar-expand > .container,
.navbar-expand > .container-fluid {
  padding-right: 0;
  padding-left: 0;
}

line 4258
.navbar-expand > .container,
.navbar-expand > .container-fluid {
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap;
}

which could be combined.

**Comment by XhmikosR** [comment]
PR welcome like I suggested before.

**Comment by Scrabble96** [comment]
Will do. So a PR is a Pull Request? I've never done one before so no doubt I would get told off for choosing the wrong fork, spoon, whatever. Please point me in the right direction and I'll submit all the duplicates.

**Comment by XhmikosR** [comment]
PR = pull request, yes. You will need to figure out some things for yourself. If you have issues please point them out preferably with a PR to improve any docs.

**Comment by Scrabble96** [comment]
Hi.

 

I’ve created a repository, edited the bootstrap.css file, opened a pull request, but it’s in my fork, i.e. Scrabble96 / bootstrap. Should I have opened the PR in twbs / bootstrap or are they automatically linked? I can’t see it in twbs/bootstrap.

 

Thank you.
