### ISSUE TITLE
Bootstrap v3.3.7 Syntax Error

### ISSUE THREAD

**Issue by HDVinnie** [twbs/bootstrap#27822]
There seems to be a syntax error in Bootstrap v3.3.7. When using Laravel Mix to compile SASS assets it results in a error. The steps to reproduce are as follows.

```
$ npm install bootstrap-sass@3.3.7 # latest version
```
```
// webpack.mix.js
mix.sass('test.scss');
```
```
// test.scss
@import 'node_modules/bootstrap-sass/assets/stylesheets/bootstrap';
```
```
npm run prod
```

This will result in the following error:

```
SyntaxError

(55:2) Missed semicolon

  53 | input[type="checkbox"] {
  54 |   margin: 4px 0 0;
> 55 |   margin-top: 1px \9; // IE8-9
     |  ^
  56 |   line-height: normal;
  57 | }
```

https://github.com/JeffreyWay/laravel-mix/issues/1846

**Comment by patrickhlauke** [comment]
the error is an intentional CSS hack http://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#validators

the fault lies with Laravel Mix for not ignoring it, I'd say.

**Comment by JeffreyWay** [comment]
It's related to this: https://github.com/sass/sass/issues/2590
