### ISSUE TITLE
Add $gutter parameter (with default value) to mixins make-container and make-row?

### ISSUE THREAD

**Issue by florianlacreuse** [twbs/bootstrap#27836]
Hi,

I noticed that both mixins `make-container` and `make-row` use directly the variable `$grid-gutter-width` while mixin `make-grid-columns` use a parameter `$gutter` with default value as `$grid-gutter-width`.

Is there a reason I don't know about?

If not it would be useful in some cases to add this parameter `$gutter: $grid-gutter-width` to both mixins.

https://github.com/twbs/bootstrap/blob/c031584bcde710841ef4324558f40242080c53a9/scss/mixins/_grid.scss#L23-L28

https://github.com/twbs/bootstrap/blob/c031584bcde710841ef4324558f40242080c53a9/scss/mixins/_grid-framework.scss#L6-L13

If you give me the go-ahead, i can do a PR.

Kind regards.

**Comment by MartijnCuppens** [comment]
It makes sense also adding it on those mixins, PR would be most welcome!

**Comment by florianlacreuse** [comment]
Thanks, see PR #27841.
