### ISSUE TITLE
rounded-0 is more specific than directional classes

### ISSUE THREAD

**Issue by SampsonCrowley** [twbs/bootstrap#27844]
why is `rounded-0` set to be more specific then the individual `rounded` classes? `rounded-bottom` should override `rounded-0`. the only class `rounded-0` should be more specific than, of the 5 available, is `rounded`

this makes it impossible to use the built in classes to override things like the default button styles to only have the bottom of the button rounded

can we at least add in more specific `rounded-0` classes? one for each `rounded` directional option?

```
.rounded-top-0
.rounded-right-0
.rounded-bottom-0
.rounded-left-0
```

**Comment by mdo** [comment]
`.rounded-0` is more specific simply because it comes later in the CSS. All of them are the same specificity beyond that as they're just classes. Beyond that, I don't see why `.rounded-bottom` would override `.rounded-0`—you're explicitly saying hide all borders with `.rounded-0`. As it stands now, changing this behavior could constitute a breaking change, as some folks may be expecting the very behavior you want to change.

> this makes it impossible to use the built in classes to override things like the default button styles to only have the bottom of the button rounded

This likely shouldn't be done with just utilities given buttons are a component that's repeatedly reused across sites and applications.

> can we at least add in more specific `rounded-0` classes? one for each `rounded` directional option?

Not convinced we need these after one request, but I'm always open to seeing more/improved utilities. If we keep hearing input for it, we can revisit.

**Comment by SampsonCrowley** [comment]
@mdo you literally missed the entire point.. I'm very aware of the technical parts of how CSS works. What I don't understand is why bootstrap made the decision to place `rounded-0` below the other  rounded classes, giving it more specificity over the other more specific rounded classes

```
This likely shouldn't be done with just utilities given buttons are a component that's repeatedly reused across sites and applications.
```

what are you talking about? That's what the utility functions are for. To override styles on individual components

I absolutely should be able to choose to have a button that is rounded only on the bottom if it fits my application

**Comment by SampsonCrowley** [comment]
Not every button across the application needs to always have the exact same style

**Comment by SampsonCrowley** [comment]
I understand it would be a breaking change, which is why the more specific rounded-0 classes are necessary. How is having control over button design with out needing custom css a bad thing?

**Comment by SampsonCrowley** [comment]
https://github.com/twbs/bootstrap/issues/23865

**Comment by SampsonCrowley** [comment]
I'm very aware of the technical parts of how CSS works. What I don't understand is why bootstrap made the decision to place `rounded-0` below the other `rounded` classes, giving it more specificity over the other more specific `rounded` classes

```
This likely shouldn't be done with just utilities given buttons are a component that's repeatedly reused across sites and applications.
```

what are you talking about? That's what the utility classes are for. To override styles on individual components

I absolutely should be able to choose to have a button that is rounded only on the bottom if it fits my application

But as it stands, because `rounded-0` is the last on the list, it's impossible to combine rounded utility functions

I understand it would be a breaking change, which is why the more specific `rounded-0` classes are now necessary (even though originally the `rounded-0` *could* be combined with them and someone made the change to put it below them later). how is having more fine-grained control over button design with out needing custom css a bad thing?

https://github.com/twbs/bootstrap/issues/23865#issuecomment-327892669

https://github.com/twbs/bootstrap/issues/23865#issuecomment-386560659

**Comment by mdo** [comment]
(Also making a note to check our other utilities for similar issues.)
