### ISSUE TITLE
Bold & Bolder font-weights should be swapped

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27859]
In deploy preview (https://twbs-bootstrap4.netlify.com/docs/4.1/utilities/text/#font-weight-and-italics) the `.font-weight-bolder` class sits below **bold**?

Surely these should be swapped around for consistency?

**Comment by XhmikosR** [comment]
FYI there is no need and it can be wrong to link to a PRs deployment. twbs-bootstrap4.netlify.com is the link.

**Comment by MartijnCuppens** [comment]
It doesn't matter that much, `.font-weight-bolder` is relative. LGTM like it is now.
