### ISSUE TITLE
Any Bootstrap 4 Theme that uses CSS variables?

### ISSUE THREAD

**Issue by tekoyaki** [twbs/bootstrap#27865]
I'm working on a project that doesn't need IE11 compatibility. Since BS 4.1 already includes CSS vars on the top, I wonder if there's any version of the default bootstrap.css that fully utilizes CSS vars? Preferably in CDN.

If one doesn't exist yet, I will manually edit it. Though it's not preferable for maintaining future updates.

```
:root {
  --blue: #007bff;
  --indigo: #6610f2;
  --purple: #6f42c1;
  --pink: #e83e8c;
  --red: #dc3545;
  --orange: #fd7e14;
  --yellow: #ffc107;
  --green: #28a745;
  --teal: #20c997;
  --cyan: #17a2b8;
  --white: #fff;
  --gray: #6c757d;
  --gray-dark: #343a40;
  --primary: #007bff;
  --secondary: #6c757d;
  --success: #28a745;
  --info: #17a2b8;
  --warning: #ffc107;
  --danger: #dc3545;
  --light: #f8f9fa;
  --dark: #343a40;
  --breakpoint-xs: 0;
  --breakpoint-sm: 576px;
  --breakpoint-md: 768px;
  --breakpoint-lg: 992px;
  --breakpoint-xl: 1200px;
  --font-family-sans-serif: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
```

**Comment by mdo** [comment]
> I wonder if there's any version of the default bootstrap.css that fully utilizes CSS vars? Preferably in CDN.

Not from our team, sorry! I'd suggest asking around in Slack or on StackOverflow though if someone else is maintaining one.

**Comment by jannejava** [comment]
@tekoyaki Curious, did you find any?
