### ISSUE TITLE
Remove now unnecessary `shrink-to-fit` viewport directive

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#27861]
Opening to track this for v5.

**Comment by patriciamarchand** [comment]
Why is the "shrink-to-fit" is not present in the doc v3 and included in v4?

v4 doc : https://getbootstrap.com/docs/4.3/getting-started/introduction/#starter-template
v3 doc : https://getbootstrap.com/docs/3.4/getting-started/#template

**Comment by XhmikosR** [comment]
Because it was added in v4 and not in v3.

**Comment by patriciamarchand** [comment]
why was it added only in this version 4?

**Comment by XhmikosR** [comment]
It was needed back then.

**Comment by patrickhlauke** [comment]
3.x only gets critical patches, not new features/tweaks. that's why it was only added at the time for 4.x
