### ISSUE TITLE
Version numbering.

### ISSUE THREAD

**Issue by Suprawow** [twbs/bootstrap#27868]
How do we go from:
4.1.0
4.1.1
4.1.2
4.1.3 to 3.4.0???

**Comment by browner12** [comment]
there are 2 active branches, v3 and v4.

loads of sites still use v3, so updates have been made to it over the years.

3.4.0 will be the last release of the v3 branch, and all future development will focus on v4 and v5.

If you have a new site, it is highly recommended to go with v4.

**Comment by Suprawow** [comment]
Ah, OK. Got you. Sorry wasn't aware of that.
I have my own reporter that tells me when many dev tools & libs update so this reported that it had gone from 4.1.3 to 3.4.0.
Thank you for your very prompt reply. All good now.

**Comment by browner12** [comment]
Great.

You can close the issue then.
