### ISSUE TITLE
[Bug] Order classes also generate a class .order#{$infix}-0 for every infix

### ISSUE THREAD

**Issue by kopax** [twbs/bootstrap#27886]
## Order classes are starting from 0 instead of 1 for every infix

- source: https://github.com/twbs/bootstrap/blob/v4.1.3/scss/mixins/_grid-framework.scss#L54

It should be like : 

- source: https://github.com/twbs/bootstrap/blob/v4.1.3/scss/mixins/_grid-framework.scss#L22

Generate css is wrong: 

```css
.order-1-0 {
  order: 0;
}

.order-1-1 {
  order: 1;
}

.order-1-2 {
  order: 2;
}

.order-1-3 {
  order: 3;
}

.order-1-4 {
  order: 4;
}

.order-1-5 {
  order: 5;
}

.order-1-6 {
  order: 6;
}

.order-1-7 {
  order: 7;
}

.order-1-8 {
  order: 8;
}

.order-1-9 {
  order: 9;
}

.order-1-10 {
  order: 10;
}

.order-1-11 {
  order: 11;
}

.order-1-12 {
  order: 12;
}
```

Possible fix: 

```diff
// Framework grid generation
//
// Used only by Bootstrap to generate the correct number of grid classes given
// any value of `$grid-columns`.

@mixin make-grid-columns($columns: $grid-columns, $gutter: $grid-gutter-width, $breakpoints: $grid-breakpoints) {
  // Common properties for all breakpoints
  %grid-column {
    position: relative;
    width: 100%;
    padding-right: $gutter / 2;
    padding-left: $gutter / 2;
  }

  @each $breakpoint in map-keys($breakpoints) {
    $infix: breakpoint-infix($breakpoint, $breakpoints);

    // Allow columns to stretch full width below their breakpoints
    @for $i from 1 through $columns {
      .col#{$infix}-#{$i} {
        @extend %grid-column;
      }
    }
    .col#{$infix},
    .col#{$infix}-auto {
      @extend %grid-column;
    }

    @include media-breakpoint-up($breakpoint, $breakpoints) {
      // Provide basic `.col-{bp}` classes for equal-width flexbox columns
      .col#{$infix} {
        flex-basis: 0;
        flex-grow: 1;
        max-width: 100%;
      }
      .col#{$infix}-auto {
        flex: 0 0 auto;
        width: auto;
        max-width: 100%; // Reset earlier grid tiers
      }

      @for $i from 1 through $columns {
        .col#{$infix}-#{$i} {
          @include make-col($i, $columns);
        }
      }

      .order#{$infix}-first { order: -1; }

      .order#{$infix}-last { order: $columns + 1; }

-      @for $i from 0 through $columns {
+      @for $i from 1 through $columns {
        .order#{$infix}-#{$i} { order: $i; }
      }

      // `$columns - 1` because offsetting by the width of an entire row isn't possible
-      @for $i from 0 through ($columns - 1) {
+      @for $i from 1 through ($columns - 1) {
        @if not ($infix == "" and $i == 0) { // Avoid emitting useless .offset-0
          .offset#{$infix}-#{$i} {
            @include make-col-offset($i, $columns);
          }
        }
      }
    }
  }
}
```

**Comment by knoobie** [comment]
Why should they not start with 0? (https://developer.mozilla.org/en/docs/Web/CSS/order)

**Comment by kopax** [comment]
Because : 

- the documentation says it start at `1` (See https://getbootstrap.com/docs/4.1/layout/grid/#reordering) 
 > Use `.order-` classes for controlling the visual order of your content. These classes are responsive, so you can set the `order` by breakpoint (e.g., `.order-1.order-md-2`). Includes support for `1` through `12` across all five grid tiers.

- `order-0` would be the equavalent to `order-first`, so it won't be very useful to have `15` instead of `14` order (we already have 12 + 2 with first and last)

**Comment by florianlacreuse** [comment]
IMHO, `.order-0` is not the same as `.order-first`: https://codepen.io/anon/pen/YdZGqe

I would prefer to keep `.order-0`. Instead, may be we can just update doc to include 0 case?

**Comment by kopax** [comment]
## `.order-first`

```css
.order-first {
    -ms-flex-order: -1;
    order: -1;
}
```

They did name `-first` and `-last` their utilities for user convenience. 

- **first**: the equivalent of beginning 
- **last**: the equivalent of the end 

Following your logic, we could also add from `.order-12` to `.order-128` to get the `.order-last ` equivalent.

I have trouble to understand how `order-0` should be read if it's not a duplicate, but I am also curious, may I know in what user case you want to have `order-first` and `order-0` together?

Documentation will confuse user like me having twice time the same utility in our code. 
The trick of setting `order: -1` is not really useful to demonstrate anything, perhaps `order-first` should be `order: 0` to avoid confusious Instead of updating the documentation as you suggest?

**Comment by florianlacreuse** [comment]
`.order-first` has more weight than `.order-0`, this is why I'm trying to tell you that technically both are not equivalent (as you said).

`.order-0` could also be used to override the `order` property define by a custom css class to reset it and set the default 0 value.

**Comment by MartijnCuppens** [comment]
As explained by @florianlacreuse, `.order-0` and `.order-first` are not the same. I'm going to close this because everything works as documented.

Thanks for taking your time to explain things here, Florian!

**Comment by kopax** [comment]
Thanks Martijn Cuppens I was waiting for a Bootstrap member position. Thank you for your answers @florianlacreuse  and @MartijnCuppens and keep up the good work.
