### ISSUE TITLE
cenos

### ISSUE THREAD

**Issue by rockmelodies** [twbs/bootstrap#27882]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

ERROR in ./resources/assets/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/assets/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(55:2) Missed semicolon

  53 | input[type="checkbox"] {
  54 |   margin: 4px 0 0;
> 55 |   margin-top: 1px \9; // IE8-9
     |  ^
  56 |   line-height: normal;
  57 | }

**Comment by rockmelodies** [comment]
cenos 报错这个

**Comment by rockmelodies** [comment]
mac 不报错

**Comment by royklutman** [comment]
If you are trying to ask why that error appears, well that's probably because the `margin-top` has a backslash in it, change it to:

```scss
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px; // IE8-9
  line-height: normal;
}
```

**Comment by ysds** [comment]
That code is not in v4. I found in v3. https://github.com/twbs/bootstrap/blob/v3.4.0/less/forms.less#L66

But v3 written in LESS syntax, and also v3 is essentially in maintenance mode.

**Comment by mdo** [comment]
Closing since this isn't something we'll change or classify as a bug in Bootstrap.
