### ISSUE TITLE
hyperlink in modal make request twice and form in modal submit twice

### ISSUE THREAD

**Issue by bc96123** [twbs/bootstrap#27884]
OS: Microsoft Windows 10
Browser: Chrome/FIrefox
Bootstrap version: 4.0

While I click the link in the modal, I found that browser is browse the link two times and if I submit the form in the modal, it submit the form two times. I found this situation from my back-end logs. The form submit two times make the bug of back-end development.

Please help me if there is any solution like put in some option for modal.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

---

Also, please update to the latest version of Bootstrap before reporting any bugs.
