### ISSUE TITLE
Why did you remove $grid-gutter-widths and how to set grid gutter width per viewport?

### ISSUE THREAD

**Issue by kopax** [twbs/bootstrap#27895]
Hi, I have been using twbs Bootstrap v4 alpha for quite long and we were having an efficient way to set the `$grid-gutter-width` per viewport:

**before**

```scss
$grid-gutter-width-base: 20px;

$grid-gutter-widths: (
  xs: 10px,
  sm: 10px,
  md: $grid-gutter-width-base, // 20px
  lg: $grid-gutter-width-base, // 20px
  xl: $grid-gutter-width-base, // 20px
  xxl: $grid-gutter-width-base // 20px
)
```

**after**

```scss
$grid-gutter-widths: 30px
```

Why did you remove $grid-gutter-widths and how to set grid gutter width per viewport?

**Comment by mdo** [comment]
We removed this long ago due to how we were compiling our CSS and never brought it back. Rather than do it this way, with v4.2.x we added [negative margin utilities](https://getbootstrap.com/docs/4.2/utilities/spacing/#negative-margin) to work with padding utilities to customize your gutters.

**Comment by kopax** [comment]
Thanks @mdo, I know we must have told you, but that's a very good framework. Is there a form/irc/rss feed where we could subscribe/be informed of discussion leading to change in twbs/bootstrap or is it all already all here?
