### ISSUE TITLE
Custom file  input don't show selected file

### ISSUE THREAD

**Issue by MikaelBox** [twbs/bootstrap#27923]
System: Debian Linux 9
Browser: Firefox 64 

I tried to use custom file input, but it's not work successfully. 
I use downloaded version of Bootstrap 4.2.1. 
Used: bootstrap.css, jquery-3.3.1.js and bootsrap.bundle.js in the same order.

I got example code [from this](https://getbootstrap.com/docs/4.2/components/forms/#file-browser)  and in browser I saw same controls, but when I select some file, it's name has no revealed into input field. 

Through browser's inspector I see that input has no assigned js, but when I do this on [example page](https://getbootstrap.com/docs/4.2/components/forms/#file-browser)  I see that input field has assigned js from docs.min.js

Is it a bug or not?
How can I fix it?

**Comment by wolfy1339** [comment]
It is the intended behavior. Bootstrap does not ship JS for the custom input.

**Comment by wolfy1339** [comment]
You can copy the JS from that page and use it no problem

**Comment by Johann-S** [comment]
Bootstrap docs use this plugin: https://www.npmjs.com/package/bs-custom-file-input to animate our custom file input, as it's written here: https://getbootstrap.com/docs/4.2/components/forms/#file-browser
