### ISSUE TITLE
Open tab from URL

### ISSUE THREAD

**Issue by dignajar** [twbs/bootstrap#27926]
Hi,
I have a page with settings, the settings are splited in `tabs`, and each tab has a button save, when the user click on the save button the page is reload and the tab is close and open the default one, would be good to include open tabs via the URL like the bellow example.

https://example.com/settings#general
this open the tab `general`

https://example.com/settings#advanced
this open the tab `advanced`

Thank you

**Comment by Johann-S** [comment]
Related to this #25220 issue
