### ISSUE TITLE
dropdown link issue

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#27922]
in below code if i am use href="#" then it will work but if i will change to href="#!" it give consol error in my as well as bootstrap live site also

```
<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#!" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
```

**Comment by xcartmods** [comment]
Same here, I'm hoping they fix this, as it's a closed issue here...
https://github.com/twbs/bootstrap/issues/27903

**Comment by Johann-S** [comment]
Fixed by: https://github.com/twbs/bootstrap/pull/27912

Will be available in our next release
