### ISSUE TITLE
Link to the latest version is not available in dropdown

### ISSUE THREAD

**Issue by maxkorz** [twbs/bootstrap#27930]
https://getbootstrap.com/docs/4.1/getting-started/introduction/
https://getbootstrap.com/docs/4.0/getting-started/introduction/

![image](https://user-images.githubusercontent.com/25089646/50483031-e336bc80-09fa-11e9-8484-ee64d36cb2f0.png)

P.S. it would be cool to have a special tag for the latest version, something like
https://getbootstrap.com/docs/latest/getting-started/introduction/

**Comment by XhmikosR** [comment]
@mdo: how do you want to solve this? I'm not sure if it's worth bothering with the version toggler if we add a callout in 4.1 too.

**Comment by mdo** [comment]
We can add it to the `gh-pages` branch.

**Comment by XhmikosR** [comment]
Fixed in #27950
