### ISSUE TITLE
Navbar logo on site

### ISSUE THREAD

**Issue by deqq1** [twbs/bootstrap#27938]
![Navbar logo](https://pp.userapi.com/c852216/v852216604/794b9/tg98M3ZMO4E.jpg)

Navbar logo looks pixelated on 1080p display. I've checked out [this issue](https://github.com/twbs/bootstrap/issues/27626) where the contributor @XhmikosR says it's seen on displays with DPI != 100% but I do have 100%:

![Screen settings](https://pp.userapi.com/c852216/v852216604/794ce/PmKFwwRPLoc.jpg)

However, it looks much better using Edge:

![Edge screenshot](https://pp.userapi.com/c852216/v852216604/794df/OvqDWkvpihY.jpg)

Ask you to use PNG image as suggested or rebuild the SVG for compatibility.

Seen on Windows 10 with latest Chrome.

**Comment by XhmikosR** [comment]
Going back to PNG is not a solution.

That being said the logo does have various issues with various browsers and display configurations.

IIRC @mdo didn't you have a different logo ready?

**Comment by XhmikosR** [comment]
With the new icon this should be fixed.
