### ISSUE TITLE
New utility classes: `rounded-lg` and `rounded-sm`

### ISSUE THREAD

**Issue by Simpleqode** [twbs/bootstrap#27934]
Would be nice to have utility classes like `rounded-lg` and `rounded-sm` as you already have SCSS variables for `border-radius-lg` and `border-radius-sm`.

**Comment by sts-ryan-holton** [comment]
This could be something useful, you might want to remove border radius from buttons as an example on smaller screens or when things become stacked as a result of breakpoints.
