### ISSUE TITLE
Bootstrap 4.2.1 Navbar

### ISSUE THREAD

**Issue by asas111111** [twbs/bootstrap#27945]
I use this theme [https://github.com/BlackrockDigital/startbootstrap-creative](url)
Navbar is not working well when upgrade to Bootstrap 4.2.1.
In the code of the Navbar,If the href attribute of `<a href="">Link</a>` contains `"/"` E.g: `<a href="Account/SignIn">Link</a>`,Navbar cannot add CSS (.navbar-shrink) when scrolling the page.(Navbar background changes from transparent to white), Javascript is not working. Without /,then it is good.
Only Bootstrap 4.2.1 has this issues.Outher version is good.
Why?

**Comment by XhmikosR** [comment]
Duplicate of #27903
