### ISSUE TITLE
4.1 docs don't mention latest version banner?

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#27943]
Unlike older versions of Bootstrap, the 4.1 docs don't have a banner at the top mentioning the latest version being 4.2.1?

I think this should be required for Major & Minor releases, but not patch releases. And considering 4.2.1 contains a lot of changes, it might be worth quickly adding the banner to the top of the 4.1.3 docs?

**Comment by XhmikosR** [comment]
It's already reported in https://github.com/twbs/bootstrap/issues/27930 and we'll take care of it soon-ish.
