### ISSUE TITLE
Add sizes or em-sizing for custom form controls

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#27958]
Just like input, dropdown, pagination and button; checkbox, toggle and slider should have a class (`form-control-lg`) to increase or reduce the size.

**Comment by mdo** [comment]
This will likely come in v5 with em-based sizing and consolidated form controls.

**Comment by natcohen** [comment]
@mdo When is v5 release planned?

**Comment by mdo** [comment]
It's our next focus after v4.3, so not too long from now I hope :).

**Comment by tmorehouse** [comment]
Duplicate of #27803

**Comment by mdo** [comment]
Duplicate of #27803, and also fixed in #28450.
