### ISSUE TITLE
Replace use of "destroys" jargon with an appropriate explanation.

### ISSUE THREAD

**Issue by linjialiang** [twbs/bootstrap#27957]
![default](https://user-images.githubusercontent.com/8848263/50553911-dd3b2700-0ceb-11e9-8b73-e9b70f6d2519.png)

> I looked at the source code and didn't see what the code did.I am a little confused about the function of this code. Can you give an example in the official manual?

**Comment by Johann-S** [comment]
This method remove stored data on the DOM element and unset the alert's attributes.

But I agree the description isn't clear at all 👍
