### ISSUE TITLE
Tooltips flickering

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#27965]
Bug reports must include:

- Bootstrap: 4.2.1
- Operating system and version: Windows 10
- Browser and version: Chrome 71
- Reduced test case: https://jsfiddle.net/3kwnto9f/

If you hover over the "VERY LONG" table cell two bugs occur:
1) Always: the tooltip is not correctly positioned.
2) Sometimes (try to hover over different positions, it's somewhere in the middle): the tooltip starts to flicker excessively (see attached GIF).

![flickeringtooltip](https://user-images.githubusercontent.com/1516470/50629257-1a95f380-0f3c-11e9-822d-71a6a0b62230.gif)

**Comment by Johann-S** [comment]
It's explained in our docs how to fix that see: https://getbootstrap.com/docs/4.2/components/tooltips/#usage

You have to change the `boundary` property:
```js
$('#example').tooltip({ boundary: 'window' })
