### ISSUE TITLE
Base Bootstrap on Tailwind

### ISSUE THREAD

**Issue by borekb** [twbs/bootstrap#27978]
I sort of dream that Bootstrap would be based on Tailwind CSS one day. This would mean that together with high-level convenience classes, I'd be able to use Tailwind's powerful utilities. For example, this would be a way to achieve sticky navbar on "md" devices and up:

```html
<nav class="navbar navbar-light md:sticky md:pin-t">
  <a class="navbar-brand" href="#">Sticky top</a>
</nav>
```

Just an idea :)

**Comment by mdo** [comment]
Interesting idea, but very unlikely to happen :). We do have similar utility classes though to accomplish these things, just not that syntax.

**Comment by borekb** [comment]
I don't think Bootstrap has utility classes that can achieve the above. But I completely understand that this is not likely to happen, just wanted to share the idea.
