### ISSUE TITLE
Add Husky

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#27973]
I've been using [husky](https://github.com/typicode/husky) lately to run stylelint (with `--fix` option) before things are committed. Adding this to Bootstrap would prevent a lot of failing tests for our PRs (for example the properties that aren't in correct order or trailing spaces). Maybe it could be interesting to add this?

**Comment by Johann-S** [comment]
Yep I think we talked about that and I'm sure there is an issue already open about that 🤔

**Comment by Johann-S** [comment]
Found here: https://github.com/twbs/bootstrap/issues/24336
We should close on of this issues

**Comment by MartijnCuppens** [comment]
@XhmikosR, what do you think about this?

**Comment by XhmikosR** [comment]
Please make a PR to see it in action. When I used husky last time, it annoyed me because some checks are slow thus slowing me down when committing and personally I'm already used to running the commands manually.

**Comment by XhmikosR** [comment]
@Johann-S #24336 isn't about husky only.
