### ISSUE TITLE
Position of radio elements using form-group label and form-check-inline

### ISSUE THREAD

**Issue by JacobNeergaard** [twbs/bootstrap#27987]
Radio elements are placed after the form-group <label> not below it like when using stacked radio and other form elements.

Code is the same except the "form-check-inline" class.

Boostrap: 4.1.3

Present in
Google Chrome 71.0.3578.98
Safiri 12.0.2

Suspect checkbox might suffer the same bug.

[checkbox:radio inline bug.html.zip](https://github.com/twbs/bootstrap/files/2729907/checkbox.radio.inline.bug.html.zip)
![skaermbillede 2019-01-05 kl 22 10 56](https://user-images.githubusercontent.com/24679577/50729285-8e502000-1137-11e9-8b49-7ae8e2b2d640.png)
![skaermbillede 2019-01-05 kl 22 16 09](https://user-images.githubusercontent.com/24679577/50729286-95772e00-1137-11e9-9ee5-148173861dd9.png)

**Comment by mdo** [comment]
This is behaving correctly, `<label>`s are `display: inline-block`, similar to the `.form-check-inline` (`inline-flex`). We cannot make `<label>`s `block`-level because they every bit of negative space around them would be clickable. Your best option is wrapping the inline checks with another element.

**Comment by bggardner** [comment]
For anyone looking for a solution, try the following.  The inline radios are now wrapped, but the secret sauce is the `my-auto` class.
```html
<div class="form-group row">
  <label for="Options" class="col-sm-2 col-form-label">Option</label>
  <div class="col-sm-10 my-auto">
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="option" value="1">
      <label class="form-check-label">Option 1</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="option" value="2">
      <label class="form-check-label">Option 2</label>
    </div>
  </div>
</div>
```
