### ISSUE TITLE
The keyboard key under the modal box is not valid

### ISSUE THREAD

**Issue by linjialiang** [twbs/bootstrap#27980]
> The keyboard key under the modal box is not valid

## I can use custom methods to control the keyboard

```js
$('#button-selector').on('click', function() {
    $('#modal-selector').modal('toggle');
    $('body').keydown(function(e) {
        if (e.which == 27) {
            $('#modal-selector').modal('toggle');
        }
    });
});
```

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
  > `windows 10`

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
  > `Firefox` `Chrome`

- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by linjialiang** [comment]
bootstrap v4.2.1

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
