### ISSUE TITLE
Btn-grey missing in 4.2

### ISSUE THREAD

**Issue by caiquecastro** [twbs/bootstrap#28002]
When I upgraded the bootstrap version to 4.2, It's missing the btn-grey. I looked into the changes from 4.1 but I could not found any changed related to it.

In the previous minor version, it has the same theme-colors variable.

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile): Windows 10
- Browser and version: Chrome 71
- Test case:
Bootstrap 4.2: https://codepen.io/caiquecastro-the-sasster/pen/JwZmjM
Bootstrap 4.1: https://codepen.io/caiquecastro-the-sasster/pen/GPGYKP

**Comment by Johann-S** [comment]
Hi @caiquecastro,

`.btn-grey` isn't an existing class 

You can check here in v4.2.1: https://github.com/twbs/bootstrap/blob/v4.2.1/dist/css/bootstrap.css

And here in v4.1.3: https://github.com/twbs/bootstrap/blob/v4.1.3/dist/css/bootstrap.css

I don't think it's a regression here 🤔 

/CC @twbs/css-review

**Comment by florianlacreuse** [comment]
I confirm, `.btn-grey` never existed.

The new behavior of a `.btn` without variant (`.btn-*`) is related to PR #27003 by @MartijnCuppens.

**Comment by caiquecastro** [comment]
If I add a valid style: "btn-secondary" for example, there is no regression.
