### ISSUE TITLE
Big porblem! in bootstrap 4.2.1 does NOT work in navbar dropdown menu.

### ISSUE THREAD

**Issue by Homelux** [twbs/bootstrap#28003]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by Homelux** [comment]
Big porblem! in bootstrap 4.2.1 does NOT work in navbar dropdown menu.

**Comment by florianlacreuse** [comment]
As you said it in your first comment, bug reports must include a reduced test case, thanks.

**Comment by Homelux** [comment]
the error is described in detail here:

https://github.com/twbs/bootstrap/issues/27903

Thanks.

**Comment by florianlacreuse** [comment]
Ok, thanks for the input.

1. Your issue is a duplicate and need to be closed.
2. A temporary fix until v4.3 is given by @Johann-S [here](https://github.com/twbs/bootstrap/issues/27903#issuecomment-450292043) (same issue).

**Comment by Johann-S** [comment]
It'll be released in our next release @Homelux
