### ISSUE TITLE
Form control mixin documentation/feature?

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#28006]
Hi, I was just wondering whether there is currently a `form-control ` mixin that can be included on any input to make it become the Bootstrap ` .form-control`.

I ask because sometimes it's difficult to add the actual class to an input and would rather use the mixin as it's easier in some cases.

I get the same could be said about most elements, like buttons, but I believe there's a large number of mixins coming up in the next release so thought now would be ideal to ask?

**Comment by MartijnCuppens** [comment]
You can `@extend` the `.form-control` class to achieve what you want. I'm not really a fan of creating more mixins in `v5` because this makes it harder to get an overview of all the code that is outputted.

**Comment by sts-ryan-holton** [comment]
@MartijnCuppens  so would something like this work:

```
.my-custom-input {
    @extend .form-control;
}
```
