### ISSUE TITLE
Bootstrap Swag

### ISSUE THREAD

**Issue by LieselGorlov** [twbs/bootstrap#28009]
Do you have a swag shop (like [https://store.gatsbyjs.org/](https://store.gatsbyjs.org/) e.g.)?

**Comment by bardiharborow** [comment]
We don't currently, but if there is community demand it might be something we would think about.

**Comment by Johann-S** [comment]
We already thought about that and I hope it'll happen 🤞 

/CC @mdo

**Comment by mdo** [comment]
We don't have any now, but this wouldn't be the place to discuss if if/when we do, so going to close this out. Maybe sometime soon after we get a proper logo! :)
