### ISSUE TITLE
Problem for node_module string, lodash and npm run test

### ISSUE THREAD

**Issue by Pataco80** [twbs/bootstrap#28019]
Hello,

I changed my strategy to install Bootstrap 4.2 and got the following results.

1. During the installation, I have 3 vulnerabilities.
-1 hight: string (no patch available)
-2 low: lodash (update version> = 4.17.5)

I update Lodash but do not do anything, either with the sudo command or the Lodash installation in the package.json> devDependencies, I deleted the node_modules folder and redo an installation name, it does not change anything . These errors persist.

2. When running npm, the error message "
js / tests / integration / bundle.js → js / coverage / bundle.js ...
created js / cover / bundle.js in 1.9s

> bootstrap@4.2.1 docs-compile / Users / ricardodovale / Sites / github / bootstrap / bootstrap
> Jekyll build bund bundle

sh: bundle: command not found
npm ERR! sh file
npm ERR! ELIFECYCLE Code
npm ERR! errno ENOENT
npm ERR! system call spawn
npm ERR! bootstrap@4.2.1 docs-compile: `jekyll build exec bundle '
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed boot script bootstrap@4.2.1 docs-compile.
npm ERR! It's probably not a problem with NPM. There is an additional logging output above.

npm ERR! A complete diary of this run can be found in:
npm ERR! /Users/ricardodovale/.npm/_logs/2019-01-10T14_47_12_308Z-debug.log
ERROR: "docs-compile" is out with 1.
npm ERR! ELIFECYCLE Code
npm ERR! errno 1
npm ERR! bootstrap@4.2.1 test: `npm-run-all lint dist js-test docs-compile docs-lint bundlesize`
npm ERR! Release status 1
npm ERR!
npm ERR! Failed bootstrap@4.2.1 test script.
npm ERR! It's probably not a problem with NPM. There is an additional logging output above.

npm ERR! A complete diary of this run can be found in:
npm ERR! /Users/ricardodovale/.npm/_logs/2019-01-10T14_47_12_329Z-debug.log
imac-pro-of-ricardo-1: ricardodovale bootstrap $ "appears in the console.This led me to the questionhttps: //github.com/twbs/bootstrap/issues/25330

I have not found a solution yet. Do you have a track to give me?

Cordially.

Ricardo

[2019-01-10T14_47_12_329Z-debug.log](https://github.com/twbs/bootstrap/files/2745883/2019-01-10T14_47_12_329Z-debug.log)

**Comment by XhmikosR** [comment]
The vulnerabilities are in dev dependencies and don't affect normal users.
Theres nothing we can do and I always monitor this stuff myself.
