### ISSUE TITLE
Error Run npm install : Command failed: /usr/local/bin/git checkout 4.0

### ISSUE THREAD

**Issue by Pataco80** [twbs/bootstrap#28015]
Hello,

I'm trying to install Bootstrap via name because I want to enjoy all the benefits of workflow. Unfortunately, when I run "Install Name" I have this displayed on the console.

imac-pro-de-ricardo-1:gulp-webpack-bootstrap ricardodovale$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: pleaseread babeljs.io/env to update!
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ricardodovale/.npm/_logs/2019-01-09T19_21_40_328Z-debug.log
imac-pro-de-ricardo-1:gulp-webpack-bootstrap ricardodovale$

I have not found a solution so far. So I attached the .log file of the error mentioned in the console as an attachment.

[2019-01-09T19_21_40_328Z-debug.log](https://github.com/twbs/bootstrap/files/2742413/2019-01-09T19_21_40_328Z-debug.log)

Here are the versions of DevTools I use:

Mac OS 10.14.2
Node v10.13.0
npm v6.5.0
git version 2.17.0

If anyone can explain to me how I can fix this problem I thank him in advance.

P.S. Happy New Year

**Comment by XhmikosR** [comment]
Unfortunately, this is unrelated to Bootstrap.

**Comment by XhmikosR** [comment]
But I believe you can just fix it if you find which of your packages requires gulp and switch to gulp 4.0 npm package instead of the branch.

```
2808 silly fetchPackageMetaData error for gulp@github:gulpjs/gulp#4.0 Command failed: /usr/local/bin/git checkout 4.0
2808 silly fetchPackageMetaData error: pathspec '4.0' did not match any file(s) known to git.
```
