### ISSUE TITLE
Popover/tooltip arrow class names are not consistent

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#28028]
For the arrow inside of the popover, the `.arrow` class is used, while `.arrow` isn't a standalone component. We don't do that anywhere else in our css. A better name would be something like `.popover-arrow`. This will be something we can look in to for `v5`, since this is a breaking change.

Edit: We should do the same with the tooltips.

**Comment by MartijnCuppens** [comment]
Also, we got to get rid of those attribute selectors

**Comment by Johann-S** [comment]
it's the same for our Tooltips so we should rename it to `.tooltip-arrow`

**Comment by peterblazejewicz** [comment]
Not sure if that is a little too premature, but I've made a #28105 for this. 
Do you already accept PRs for v5, or should I help with 4.3 v4 in general?
Thanks!

**Comment by Johann-S** [comment]
We will make a `v5-dev` branch soon @peterblazejewicz 

But you can targe this branch: `v4-without-jquery` which will be merge in our futur `v5-dev` branch

**Comment by XhmikosR** [comment]
Closing since #28105 is merged.
