### ISSUE TITLE
Caret in Dropdown Wrapping

### ISSUE THREAD

**Issue by Joyrex** [twbs/bootstrap#28021]
After updating to 4.2.1, I noticed that some of my button dropdowns when inside a table cell were now wrapping (the dropdown caret was wrapping to a new line), whereas in 4.1.3 they did not. I have provided two Pens showing the same code producing different results.

This is probably related to https://github.com/twbs/bootstrap/issues/23932, but 4.1.3 does not have this behavior (see both Pens for examples). I have not seen this until upgrading to 4.2.1.

**4.2.1. Behavior** (caret wrapping): https://codepen.io/Joyrex/pen/MZPejm
![image](https://user-images.githubusercontent.com/651646/50995456-c1eacb80-14e4-11e9-994d-783b9bc1af42.png)

**4.1.3 Behavior** (caret does not wrap): https://codepen.io/Joyrex/pen/aPRZLK
![image](https://user-images.githubusercontent.com/651646/50995440-b697a000-14e4-11e9-9b53-23cee3f33740.png)

- Operating system and version (Windows 10)
- Browser and version (Chrome Latest)

**Comment by mdo** [comment]
We removed the `white-space: nowrap`, but you can restore that with `.text-nowrap`. I don't think we'll be bringing that property-value back though. Thoughts @twbs/css-review?

**Comment by MartijnCuppens** [comment]
Maybe only bring it back for `.dropdown-toggle`?

**Comment by Joyrex** [comment]
@mdo @MartijnCuppens - I see, and thank you for the interim solution! I agree that perhaps having this only on elements where the caret is present (since it is a bit odd having the caret underneath the text or icon on a button, but I am sure there are some valid use cases out there as well).
