### ISSUE TITLE
Website shows v4.1 series as latest

### ISSUE THREAD

**Issue by adamchainz** [twbs/bootstrap#28020]
When I visit https://getbootstrap.com/ , even with hard refresh, I still only see version 4.1.

<img width="719" alt="screen shot 2019-01-10 at 17 10 03" src="https://user-images.githubusercontent.com/857609/50984819-a7235180-14fa-11e9-858c-c7a8d4dfd398.png">

**Comment by herbalite** [comment]
If it helps..

I had that too. No matter from where I launched getbootstrap.com (Address bar, FF start page or Speed Dial

In my case it was because of a speed dial add-on in Firefox. Clearing all cached data relating to the bootstrap site helped ( browser and add-on cache ).

**Comment by knoobie** [comment]
Same for me.. (Firefox Developer Edition (65.0b9) and only Addon Wappalyzer)

![bildschirmfoto_2019-01-11_09-00-34](https://user-images.githubusercontent.com/3968629/51020695-9d8ffd00-157f-11e9-9698-8a501732d3c5.png)

![bildschirmfoto_2019-01-11_09-04-18](https://user-images.githubusercontent.com/3968629/51020791-e47df280-157f-11e9-9511-ce9d6890dc66.png)

**Comment by XhmikosR** [comment]
I personally don't know what else to do. We currently unregister the service worker. Whoever has this issue, just unregister the service worker manually.

**Comment by adamchainz** [comment]
Chrome. I just tried again and it shows 4.2 now. Service workers hey!

**Comment by XhmikosR** [comment]
Anyone who has this issue please paste the full URL to sw.js from the browser. Maybe we missed the path when the docs structure was changed and the current path isn't the same thus it doesn't get unregistered.

**Comment by MartijnCuppens** [comment]
Got the same issue, sw path is just `https://getbootstrap.com/sw.js`. Got it in every browser, hard refresh doesn't solve it, unregistering the service worker doesn't help either.

**Comment by XhmikosR** [comment]
That file does contain the unregister code. I have no idea why it keeps happening for some people.

**Comment by MartijnCuppens** [comment]
@XhmikosR, I got this in every browser. This problem is also reproducible on BrowserStack btw.

**Comment by XhmikosR** [comment]
Well, it's not reproducible here for sure. You are welcome to find a solution yourself.

**Comment by MartijnCuppens** [comment]
I misinterpreted this issue, I was checking the dropdown where the latest version wasn't correctly labeled:
![image](https://user-images.githubusercontent.com/11559216/51087047-658ae480-174e-11e9-8380-85648de7f0b3.png)

**Comment by MartijnCuppens** [comment]
We'll handle the dropdown issue of the versions in older docs in #28115. 

I couldn't reproduce any issues with an outdated Bootstrap homepage, it was probably some aggressive browser caching which was causing this back when this was reported.
