### ISSUE TITLE
Carousel data-touch="false" not working

### ISSUE THREAD

**Issue by ezarowny** [twbs/bootstrap#28025]
I am unable to disable touch support for Carousels in Bootstrap 4.2.1. Adding an HTML attribute for `data-touch="false"` doesn't seem to change anything.

- Operating System: iOS 12.1.2
- Browser: Safari
- Reduced test case: https://codepen.io/ezarowny/pen/dwQOgV

**Comment by ezarowny** [comment]
Ah, maybe [this line](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/carousel.js#L275) should have something like `|| !this.config.touch` added to the conditional 🤔

**Comment by Johann-S** [comment]
Thanks @ezarowny I made a PR to fix that 👍

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is it possible that this is appearing again? Having the same problem now with 4.5.0?

**Comment by Yorik56** [comment]
<img src="https://i.ibb.co/xSQxg9T/touch-false.jpg" alt="touch-false" border="0" />

I made this modification on bootstrap.js, it's worked nice for me, hope it will help :p

**Comment by patrickhlauke** [comment]
confirming that it seems we have a regression. opened a fresh ticket here https://github.com/twbs/bootstrap/issues/32629
