### ISSUE TITLE
.footer{z-index:99999999999} but ....

### ISSUE THREAD

**Issue by hktalent** [twbs/bootstrap#28031]
.footer{z-index:99999999999} but ....
![image](https://user-images.githubusercontent.com/18223385/51082607-6d925680-1745-11e9-9704-b9bf891a7f00.png)
<footer class="footer mt-auto py-3 shadow">
  <div class="container">
    <span class="text-muted">xxxxxxx</span>
  </div>
</footer>

**Comment by dvmuccillo** [comment]
Please take a look: https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports

**Comment by MartijnCuppens** [comment]
This doesn't look Bootstrap related, you should have a look at how the stacking context works:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
