### ISSUE TITLE
Popover's 'content' option doesn't work if i use 'selector' option and 'trigger' option equal 'manual'

### ISSUE THREAD

**Issue by boikoeugene** [twbs/bootstrap#28048]
**Browser**: Chrome 71.0.3578.98;

I use dynamical content with popovers and i came across a problem.
When you init popover using delegating  and set **trigger** option like **manual**, **content** option doesn't work.
You can see it on the link - https://jsfiddle.net/zac43y8e/ .

**Comment by Johann-S** [comment]
I forked your JSFiddle and it seems it works: https://jsfiddle.net/b873yxs5/

Maybe I misunderstood what you want to do 🤔 
You make a mistake here: `$(this).popover('toogle');` it's not `toogle` it's `toggle`

**Comment by boikoeugene** [comment]
> You make a mistake here: `$(this).popover('toogle');` it's not `toogle` it's `toggle`

Yes. I've fixed it.
But my case still doesn't work. 
I've looked at your example and why do you use parent element like `$('#bad-wrapper').popover('show')` instead of `$('.popover-trigger').popover('show')`? and if you are right where is my title? :)
I want to get the same result like first example with **click** value of trigger option. How can i do this with **manual** value?

**Comment by Johann-S** [comment]
Ok so after worked a bit on that, currently we cannot use dynamic content (if `content` option is a function) with a selector, because everything is stored in the parents.
So we have to figure how to use that content function for childs.

**Comment by boikoeugene** [comment]
> So we have to figure how to use that content function for childs.

I forked your example https://jsfiddle.net/quy7k8d3/ and what i want to say..
It looks as if you save popover's settings in a child but dynamic content function in a parent, because if you click '**toggle child**' you will get the popover with settings and title (attribute of a child) but without content. 
On the other hand, if you click '**show parent**' you will get the popover with content without settings and title.
I guess, that you should also save function in a child element.

And at the same time - this case works if you choice any `trigger` option is different from `manual` - it's very strange. (see first '**works very-good**' button)

At last, i don't understand, why toggle a popover doesn't work with the help of `on` delegation ('**works very bad**' button), although '**toggle child**' button works fine or almost fine:
```
$('#bad-wrapper').on('click', '.popover-trigger', function () {
    $(this).popover('toggle');
});
```

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
