### ISSUE TITLE
Aspect ratios embed tag

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#28054]
hello sir,
you can mention aspect ration class **"embed-responsive-4by3"** in given below links

https://getbootstrap.com/docs/4.2/utilities/embed/#aspect-ratios

but 

in bootstrap CSS **actual class is "embed-responsive-3by4"** find in given link

https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css

**so I request you either change in documentation or css package.**

thanks,
Mr. Viral Dhimmar

**Comment by MartijnCuppens** [comment]
Hi @pcodedviral,

We are aware of this. This has been addressed in https://github.com/twbs/bootstrap/pull/27910 and will be shipped in the next release.
