### ISSUE TITLE
Multiple collapse imports not working

### ISSUE THREAD

**Issue by sabmah** [twbs/bootstrap#28065]
**OS** : windows 10
**Browser**: Chrome 71.0.3578.98
**Compiler** : webpack
**Framework**: .netcore 2.1

I have two files main.js and foo.js which is both added as entry point on webpack and bundled. main.js is added into the layout and hence it always loads. foo.js is only loaded on a specific page. Both main.js and foo.js have `import 'bootstrap\js\collapse`. 

When I test the accordion on the page that has foo.js, it expands the collapsed div and then closes back again. I put some break points on collapse.js and turns out its toggling twice.

When I remove the `import "bootstrap\js\collapse"` from main.js, the accordion works.

This only happens on collapse. I added `import 'bootstrap\js\modal` on both main.js and foo.js and it doesn't conflict with each other.

**Comment by sabmah** [comment]
@Johann-S Webpack can't resolve `import 'bootstrap/js/dist/collapse'` . 
There is no /dist folder under /js. However, there is a folder boostrap/dist but it only has bootstrap.js, bootstrap.min.js and npm.js

**Comment by Johann-S** [comment]
Hmm ok that's why you don't have a `js/dist` folder.
I cannot be sure but maybe you use our data attribute API on your JS files, which add two listeners: https://github.com/twbs/bootstrap/blob/v3.4.0/js/collapse.js#L200 

If I were you I would create a third js file which will contains my shared Bootstrap plugins.

However Bootstrap v3 isn't very compatible with bundlers (Webpack, Rollup, etc...) compared to our v4.

**Comment by sabmah** [comment]
Thanks @Johann-S for looking into this!
After many thoughts, I resolved this issue by externalizing both bootstrap and jQuery scripts. Added external option in webpack `externals:[{jquery:'jQuery'}]`

**Comment by Johann-S** [comment]
That's a good solution too 👍 You're welcome 😃

**Comment by kevinaltaf** [comment]
> Thanks @Johann-S for looking into this!
> After many thoughts, I resolved this issue by externalizing both bootstrap and jQuery scripts. Then, added external option in webpack `externals:[{jquery:'jQuery'}]`

How it's work with property JQuery in webpack?
