### ISSUE TITLE
Masonry-ish grid

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#28076]
Follow-up on https://twitter.com/getbootstrap/status/1083797119742267392

Maybe we should just add a masonry-ish css grid? We currently only have the [card columns](https://getbootstrap.com/docs/4.2/components/card/#card-columns), but we might just provide a card independant implementation with responsive classes?

**Comment by mdo** [comment]
Definitely down to explore!

**Comment by MartijnCuppens** [comment]
I'm afraid this will just lead to more issues like https://github.com/twbs/bootstrap/issues/28676. Maybe some day we 'll have better web standards to deal with this, until then manonry will be the tool to use.

We currently still have the card groups, but to honest, that's not really a bulletproof solution for this layout and it still lacks some flexibility (determine how many columns should be used and control over responsive breakpoints).

Should we ditch the card decks, change our demo to a masonry example or just add a clearer warning about its limits?

cc @twbs/css-review

**Comment by mdo** [comment]
Best implementation I’ve seen so far, but haven’t dived into yet, is this: https://tobiasahlin.com/blog/masonry-with-css/. Unsure if or how we could make that generalized for enough people and projects.

**Comment by MartijnCuppens** [comment]
Saw that, but if you look to it more in detail you'll see this is a way uglier that the columns solution we have now, it uses a fixed container height and doesn't take height into account.

**Comment by mdo** [comment]
Yeah, it’s not without trade offs. Might make most sense to build an example with Masonry and Cards, and how you can move from our CSS columns to Masonry.

**Comment by dvinodeluru** [comment]
Any help on this #28921
