### ISSUE TITLE
Add make-max-widths-container mixin in docs

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#28073]
Sometimes it's not always possible to automatically add the `.container` class to an element, so I typically will instead - target the element and add the `@include make-container()` mixin. However, this doesn't seem to automatically generate the breakpoints specific widths.

After some googling, and some trial and error, I found that using the mixin `make-max-widths-container-width` works:

```
@mixin make-max-widths-container-width($max-widths: $container-max-widths, $breakpoints: $grid-breakpoints) {
  @each $breakpoint, $container-max-width in $max-widths {
    @include media-breakpoint-up($breakpoint, $breakpoints) {
      max-width: $container-max-width !important; /* stylelint-disable-line declaration-no-important */
    }
  }
}
```

However, I don't see this easily listed in the docs: https://getbootstrap.com/docs/4.2/layout/grid/#example-usage and think it should be added

Usage example:

```
.some-class {
  @include make-container();
  @include make-max-widths-container-width();
}
```

**Comment by MartijnCuppens** [comment]
We 're currently working on an automated way to extract the mixins with documentation from the code and print them in our docs: https://github.com/twbs/bootstrap/pull/26500 (currently on hold because we'll be switching to hugo to build our docs). That'll cover this.
