### ISSUE TITLE
Drop `.position-sticky` utility class

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#28077]
`.position-sticky` doesn't work out of the box without `top` value. I think we better drop it in `v5`. `.sticky-top` fully covers the behaviour people will need.

**Comment by mdo** [comment]
What if we kept that class and added utilities for `top`, `right`, etc?

**Comment by MartijnCuppens** [comment]
Imo that would give a false impression of how `position: sticky` works.

**Comment by mdo** [comment]
> Imo that would give a false impression of how `position: sticky` works.

In what way?

**Comment by MartijnCuppens** [comment]
Nevermind, we have `.sticky-top` and dropping this won't be that much of a difference.
