### ISSUE TITLE
Card column not align properly

### ISSUE THREAD

**Issue by justinechacko** [twbs/bootstrap#28083]
I am using bootstrap 4.0.0 scss version. In windows 10, chrome card column layout shows a black block at the bottom of the page.
Link https://justinechacko.in
![image](https://i.postimg.cc/0NpvZNg8/12.jpg)

**Comment by XhmikosR** [comment]
1) Update to latest stable
2) If the problem persists provide a codepen

**Comment by MartijnCuppens** [comment]
This is caused by the `top: -16.75%;` in your custom code:

![image](https://user-images.githubusercontent.com/11559216/51424651-0a834280-1bd1-11e9-9dff-a3c63e284306.png)

Please debug your code first before opening a ticket here.

**Comment by justinechacko** [comment]
Thanks for reply. Resolved.
