### ISSUE TITLE
Abilty to choose what is needed before starting a project

### ISSUE THREAD

**Issue by harlyon** [twbs/bootstrap#28080]
i am looking towards a way for  allowing developers choose components needed in their project before starting out with bootstrap framework

**Comment by MartijnCuppens** [comment]
@harlyon, are you looking for something like this? https://johann-s.github.io/bs-customizer/

**Comment by harlyon** [comment]
@MartijnCuppens exactly what i am looking for.....thanks mate

**Comment by MartijnCuppens** [comment]
No problem, amigo. Have a great weekend! 🎉
