### ISSUE TITLE
Precise measurements when printing in Chrome & Safari

### ISSUE THREAD

**Issue by fvitali** [twbs/bootstrap#28085]
I have run into a Bootstrap problem related to precise measurements in absolute sizes with `@media print`. I have found a workaround for my pages, but I believe the current choice in the deployed code is in error and should be fixed. 

While trying to get absolute measures in a print CSS using Bootstrap on Chrome, it seemed that everything was shrunk by about two thirds. Printing the page with 150% zoom made everything work fine. With zoom 100%, everything is still correctly proportioned, but uses two thirds of the space it should use, even when using absolute values for print units  (e.g., mm). 

This happens only on Chrome (Mac & Win) and Safari (only tried Mac). Neither Edge nor Firefox seem to have this problem, which I was able to pinpoint to line 93 of `_print.scss` of Bootstrap 4.2.1: 

```
    body {
      min-width: $print-body-min-width !important;
    }
```
converted into line 9851 of `bootstrap.css` as

```
  body {
    min-width: 992px !important;
  }
```
To show the problem I created a web page as follows: 

```
<html>
	<head>
		<meta charset="utf-8"> 
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.css">
		<title>A printing experiment</title>
		<style>
		@media print {
			@page {
				size: A4; 
			}
			body {
// 				min-width: auto !important;
			}
		}	

		#container {
			position: absolute; 
			width: 200mm; 
			height: 287mm; 
			top: 5mm;
			left: 5mm; 
			border: solid black 1pt;
			background-color: #ffffff ; 
		}
		</style>
	</head>
	<body>
		<p id="container">Hello world</p>
	</body>
</html>
```
It contains a single bordered box as big as a full A4 page (minus 5mm as margins). The document can be found on https://codepen.io/anon/pen/BvgdZV (but you cannot print it) or on http://www.fabiovitali.it/bugs/bootstrap/printingsizeBad.html (and you can print it). You do not need to print it, the preview of the printing driver shows the exact problem. 

Line 14 is commented, so the above-mentioned line 9851 of bootstrap.css is active and the preview of the printing engine shows a box much smaller than the full page, as follows: 

![screenshot 2019-01-18 14 49 51](https://user-images.githubusercontent.com/11316541/51393521-2ab2f300-1b38-11e9-897b-e8868e3ba256.png)

By uncommenting line 14 of the web page (see http://www.fabiovitali.it/bugs/bootstrap/printingsizeGood.html), line 9851 is overloaded and the preview shows the box as it was intended, as follows:  

![screenshot 2019-01-18 14 50 11](https://user-images.githubusercontent.com/11316541/51393522-2b4b8980-1b38-11e9-84f5-460eb740dc67.png)

I believe the bootstrap code to be in error (why is a print CSS using px at all?) and that a different choice for min-width should be used, much closer to the real measurement of a physical page. 

Details: 
- OS: _Mac OsX 10.12.6_, Browsers: _Chrome 71.0.3578.98, Safari 12.0.1 (12606.2.104.1.2)_
- OS: _Windows 10 version 1803 (build 17134.523)_, Browser: _Chrome 71.0.3578.98_

Bug tested on Bootstrap 4.1.3 and 4.2.1

Running example:
https://codepen.io/anon/pen/BvgdZV  (but you cannot print the html)
http://www.fabiovitali.it/bugs/bootstrap/printingsizeBad.html and http://www.fabiovitali.it/bugs/bootstrap/printingsizeGood.html

**Comment by mendozagioo** [comment]
@MartijnCuppens @fvitali  Is this issue is fixed to v4.4.1? I can't find something wrong when I configure size paper, and `.min-width` for `body`. To me all depends about Bootstrap initial configuration and printer configuration.

**Comment by MartijnCuppens** [comment]
Each browser handles printing different, there's not really a solid way to fix this. We tried hardcoding the width in `v4`, which in the end just introduced other issues. I did some research about this here https://github.com/twbs/bootstrap/pull/28753#issuecomment-504671905, but I'm afraid we'll only be able to fix these issues with better browser standards and uniform browser implementations.

**Comment by MartijnCuppens** [comment]
We've removed the print hacks in `v5`. As for `v4`, I would indeed suggest using `body {min-width: auto !important;}`. Not planning on fixing this, since it might reintroduce other issues we had before.

**Comment by barbalex** [comment]
yep, this has royally hit our project. Took me about a month of work distributed over two years to finally realize that bootstrap was the reaseon our A4 portrait prints were shrunk

**Comment by barbalex** [comment]
There is another problem causing an extra page to be printed when using A4 portrait. I have not found the exact reason yet. Only, that bootstrap causes it (removing bootstrap solves the issue).
