### ISSUE TITLE
Decimals?

### ISSUE THREAD

**Issue by BearoTooth** [twbs/bootstrap#28088]
I believe if you allowed for tables to have decimals it would make it more customizable for users and would be pretty cool.

He is an example of what it currently is:
.col-md-6{
  border: 20px;
  height: 200px

But I believe it would be more customizable if you allowed for something like this:
.col-md-2.5{
  border: 0px;
  height: 200px

Meaning that you could still add to 12, or possibly change the value, but incorporating the decimals will allow for more customization to websites using base web coding.

**Comment by mdo** [comment]
Thanks, but no plans to add this.
