### ISSUE TITLE
Website has old version listed for download on homepage

### ISSUE THREAD

**Issue by pratnala** [twbs/bootstrap#28091]
The homepage shows v4.0.0-beta3. Incognito shows v4.2.1.

Browser: Google Chrome

![image](https://user-images.githubusercontent.com/1689565/51409303-44dbd980-1b16-11e9-912b-d2aa3fdf88df.png)

**Comment by MartijnCuppens** [comment]
Just to make sure, are you visiting https://getbootstrap.com/ or another page/site?

**Comment by pratnala** [comment]
getbootstrap.com it is

**Comment by pratnala** [comment]
It is seemingly fixed today

**Comment by XhmikosR** [comment]
No, you were affected by the broken SW which was live in the past, and that is being explicitly unregistered since some time now.
