### ISSUE TITLE
ScrollSpy issue with links to documents

### ISSUE THREAD

**Issue by Sin3W** [twbs/bootstrap#28108]
Good morning,

I have an issue with the latest version of bootstrap and scrollspy behavior. In the previous version, I had in my NavBar links to tags inside the document, and also links to other document (login page). This works smoothly without problems.

Now, with v4.2 if I have an internal document link ScrollSpy stops working or log error in console.

My website is https://www.sin3w.com/demos/abogadosDemo/

You can also see a codepen in this link: https://codepen.io/sin3w/pen/JxopXj

The CodePen has a fake link, if you delete it ScrollSpy starts working again. Also if you downgrade the bootstrap version to v4.1, it also starts working again.

Thanks!

**Comment by Johann-S** [comment]
Hi @Sin3W,

It's a well known issue and it'll be fixed in our next release.
During that time you can add a `data-target` attribute to avoid the error, see my CodePen forked from yours: https://codepen.io/Johann-S/pen/LqEdWO

**Comment by Sin3W** [comment]
Thanks a lot for your quick answer!!!
