### ISSUE TITLE
Contributing guidelines possibly outdated

### ISSUE THREAD

**Issue by JLammeer** [twbs/bootstrap#28109]
Hey, guys?!

I was wondering whether the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#pull-requests) is outdated, especially in the "Pull Requests" section.
When it mentions `master`, isn't it supposed to be `v4-dev`?

I tried to follow the steps using `master` at first, but I would have to fix lots of conflicts. So, I decided to use `v4-dev` instead, had no conflicts problems and an accepted PR.

If so, it would be misleading some developers. Right?!

**Comment by bardiharborow** [comment]
It still references `grunt test` as well. :(

**Comment by XhmikosR** [comment]
The branches are switched now, so master is again the base branch.

I'll remove any obsolete info from there later.
