### ISSUE TITLE
Cards specify background but not foreground color

### ISSUE THREAD

**Issue by vsalvino** [twbs/bootstrap#28102]
This seems like an inconsistency to specify a background color but not a foreground color. For example, if you have a card nested in a div that specifies a background and foreground color, the cards will specify a background but inherit foreground from parent.

``` html
<div style="background-color:#000; color:#fff;">
    <div class="card">
        ...
    </div>
</div>
```

An alternate use-case is building the sass and specifying a dark card background. Then the card would contain a dark background but inherit the foreground color from body.

See relevant code at https://github.com/twbs/bootstrap/blob/f7e8445f72875a49a909dc0af8e4cf43f19f535e/scss/_card.scss#L11 

Live demo: https://codepen.io/anon/pen/YBXqzX

**Expected behavior:** Card should either inherit both background and foreground color from parent, or specify both background and foreground color in Bootstrap CSS. Currently it is inheriting foreground but specifying background which is not consistent.

**Comment by MartijnCuppens** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [Codepen](https://codepen.io) and report back with your link.

---

_This is a saved reply._

**Comment by MartijnCuppens** [comment]
You can add the `.text-body` class to the card. Alternatively, you can set the `$card-color` in your `scss` (this will be available in our next version).
