### ISSUE TITLE
Documentation - nav-justified

### ISSUE THREAD

**Issue by retan** [twbs/bootstrap#28117]
The documentation for `.nav` components has bug.
The first example for `.nav-justified` isn't working at all.
https://getbootstrap.com/docs/4.2/components/navs/#fill-and-justify

![image](https://user-images.githubusercontent.com/3779428/51700128-a3212480-200e-11e9-84b4-559073cc8d22.png)

My guess is that the example should use the `ul>li.nav-item` structure.

**Comment by XhmikosR** [comment]
Yeah something is wrong either with the docs or the CSS.

/CC @MartijnCuppens

**Comment by XhmikosR** [comment]
I believe it's a docs issue though, since by design this needs `.nav-item` so that flexbox works.
