### ISSUE TITLE
Docs: Dropdown from v4.0 does not link to 4.2.1

### ISSUE THREAD

**Issue by alexlenail** [twbs/bootstrap#28115]
The docs pages for bootstrap v4.0 contain a dropdown. That dropdown contains v4.1.3 listed as latest. It does not contain v4.2.1.

Example: https://getbootstrap.com/docs/4.0/components/list-group/

**Comment by MattMski** [comment]
I would be interested in working on this

**Comment by XhmikosR** [comment]
Doesn't it make sense, though? They are old docs, hence the callout at the top.

**Comment by artjomsimon** [comment]
Hm, I think it's a usability bug. People landing at the old docs (via search engines, or by following old, but still valid links) don't necessarily *know* that the docs they're currently reading are, in fact, old.

If they doubt the freshness of the docs, they naturally will reach for the version dropdown, which worsens the situation by suggesting that 1) yes, they were right about suspecting the docs to be old, but 2) sugesting the 4.1 docs as if *they* were the right version.

For example, looking at old [PostgreSQL docs](https://www.postgresql.org/docs/8.4/queries-select-lists.html), even when browsing old docs, the *(Current)* label always points to the current release.

I think this is much clearer to understand, what do you think?

**Comment by XhmikosR** [comment]
The thing is that is a maintenance nightmare. We aren't rebuilding the old docs every time we have a new major/minor version.

So, I'm unsure how to proceed.

**Comment by MartijnCuppens** [comment]
Maybe we can load the versions list with ajax?

**Comment by XhmikosR** [comment]
You can try if you are up to it and ping me :)

**Comment by alecpl** [comment]
Maybe you could do something with "There's a newer version of Bootstrap 4!" element too. It appears if I access 4.2 docs e.g. https://getbootstrap.com/docs/4.2/components/forms/ which does not make sense.

**Comment by leodluz** [comment]
> 
> 
> The thing is that is a maintenance nightmare. We aren't rebuilding the old docs every time we have a new major/minor version.
> 
> So, I'm unsure how to proceed.

Make a link named to "lastest'  which automatically redirects to the latest available version. Try accessing https://getbootstrap.com/docs/ and you'll see that this is what happens. This way you will no longer have to change old docs.

**Comment by joliss** [comment]
This still seems to be happening. E.g. Google landed me on https://getbootstrap.com/docs/4.1/getting-started/introduction/ (version 4.1), but its dropdown doesn't list the [4.5 version of the same page](https://getbootstrap.com/docs/4.5/getting-started/introduction/).

**Comment by techboyg5** [comment]
> 
> 
> This still seems to be happening. E.g. Google landed me on https://getbootstrap.com/docs/4.1/getting-started/introduction/ (version 4.1), but its dropdown doesn't list the [4.5 version of the same page](https://getbootstrap.com/docs/4.5/getting-started/introduction/).

Grest!

**Comment by XhmikosR** [comment]
Closing for #28115
