### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by fullermetric** [twbs/bootstrap#28111]
Windows 10 64bit, Browser Chrome Version 71.0.3578.98 (Official Build) (64-bit)

See this codepen: https://codepen.io/kbrfuller/pen/omgzxm

I include the following javascript libraries in this order:
https://code.jquery.com/jquery-3.2.1.slim.min.js
https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js

The console reads:
bootstrap.min.js:6 Uncaught TypeError: Cannot read property 'fn' of undefined
(anonymous) @ bootstrap.min.js:formatted:119
(anonymous) @ bootstrap.min.js:formatted:7
(anonymous) @ bootstrap.min.js:formatted:8

When I pretty-print bootstrap.min.js it shows the error here:
  g.fn.emulateTransitionEnd = n,                                   <-- this line is highlighted
  g.event.special[_.TRANSITION_END] = {
    bindType: e,
    delegateType: e,
    handle: function(t) {
      if (g(t.target).is(this))
        return t.handleObj.handler.apply(this, arguments)
    }
  };

**Comment by MartijnCuppens** [comment]
@fullermetric, make sure you include jQuery before the Bootstrap js.

**Comment by Johann-S** [comment]
It looks like what @MartijnCuppens said 👍

**Comment by crobinson42** [comment]
issue #26745 is the same.

It's related to the lack of jquery or order jquery is instantiated being after bootstrap

**Comment by fullermetric** [comment]
That's very interesting as I inserted these javascript libraries into my codepen in the exact order as shown on this bootstrap page.
[https://getbootstrap.com/docs/4.0/getting-started/introduction/](url)

And a snapshot of the library insertion on codepen.io
![image](https://user-images.githubusercontent.com/46577513/51702719-5e26cf00-1fc9-11e9-9b13-bc53a0fca810.png)

The only thing I see a different of is the bootstrap version being used in my codepen.
