### ISSUE TITLE
Opacity utility classes - .opacity-[0-5]

### ISSUE THREAD

**Issue by JacobLett** [twbs/bootstrap#28110]
It would be handy to have some opacity utility classes.

**Use cases**
-  Quickly make tinted images with a parent that has a background color.
- It could also help making common opacity hover effects. Like the initial value is set to 0 and on hover you want it to have full opacity.

Here is an example.
https://codepen.io/JacobLett/pen/ZwGQKX

**Comment by Arvind-Suthar** [comment]
Well that you can do with just 2-5 lines of code. Why do you need seperate classes for it

**Comment by mdo** [comment]
Going to say we hold off on this for the time being. I don't often see `opacity` as a highly repetitive property across code bases, which is the primary reason for utilities.

**Comment by JacobLett** [comment]
Ok thanks Mark that is a good point and I will keep the "highly repetitive" requirement for any future suggestions.
