### ISSUE TITLE
Make bootstrap.css independent and portable...

### ISSUE THREAD

**Issue by username1565** [twbs/bootstrap#28120]
Bootstrap.css and bootstrap.min.css need to include glyphicons:

```
src:url(../fonts/glyphicons-halflings-regular.eot);
src:url(../fonts/glyphicons-halflings-regular.eot?#iefix) format('embedded-opentype'),
url(../fonts/glyphicons-halflings-regular.woff) format('woff'),
url(../fonts/glyphicons-halflings-regular.ttf) format('truetype'),
url(../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format('svg')
```

You can make bootstrap.css portable and more complete, if you will using dataURL in this url's.
For example, `url(data:application/octet-stream;base64,BLAH-BLAH-BASE64) format('woff')`
working fine, and you can get base64 string `BLAH-BLAH-BASE64` after try to uploading this file to this textarea: https://username1565.github.io/brainwallet.github.io/#converter

You can replace url's in your download-repositaries, just for fun.

Have a nice day.

**Comment by XhmikosR** [comment]
We no longer use glyphicons since v4.

**Comment by username1565** [comment]
But... I see some `url(` by searching in the source code of `bootstrap.css`.
This means this bootstrap.css need requiremens...

**Comment by XhmikosR** [comment]
We don't use glyphicons in v4, you can check the code yourself. What we use in v4 is inlined SVG in CSS.
