### ISSUE TITLE
Collapse Accordion transitions not working

### ISSUE THREAD

**Issue by kokaruk** [twbs/bootstrap#28123]
Since v4.1 transitions are no longer working. 

https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

Open / close events are smooth transition

https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example

Open / close no animation transition is happening

**Comment by MartijnCuppens** [comment]
I can not reproduce this. What browser/OS are you using?

**Comment by patrickhlauke** [comment]
I will hazard a guess that this is related to `prefers-reduced-motion` ?

**Comment by kokaruk** [comment]
> I can not reproduce this. What browser/OS are you using?
Safari, FF and Chrome on Mac 
and FF and Chrome on Win 10

> I will hazard a guess that this is related to `prefers-reduced-motion` ? [#27525 (comment)](https://github.com/twbs/bootstrap/issues/27525#issuecomment-433620865)
ah, yes. That exactly it. 

So, its a feature, not a bug. 
Is it reflected in the release notes somewhere so I can show it to the team? 

Anyway, that resolves the issue.

**Comment by patrickhlauke** [comment]
> Is it reflected in the release notes somewhere so I can show it to the team?

shiplist for 4.2.0 https://github.com/twbs/bootstrap/issues/26952 which lists, under CSS:

> #27581: Add Sass variable for prefers-reduced-motion, add callout to affected components

In the docs, see the note in https://getbootstrap.com/docs/4.2/components/collapse/#how-it-works which points to https://getbootstrap.com/docs/4.2/getting-started/accessibility/#reduced-motion

**Comment by patrickhlauke** [comment]
(and yes, the above are for 4.2.0, not 4.1.0 - the `prefers-reduced-motion` stuff was introduced earlier, but the ramifications / apparent side effects weren't that apparent at the time, which is why those notes/mentions only got shipped with 4.2.0)
