### ISSUE TITLE
[Bootstrap 4] Peer dependency is reported as being insecure by npm

### ISSUE THREAD

**Issue by alan-at-1up-health** [twbs/bootstrap#28122]
When installing bootstrap 4 via npm you receive a message `npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.`.

However, jQuery 1.9.1 has a security issue that gets flagged by npm's security audit tool as being high severity.
![image](https://user-images.githubusercontent.com/46764367/51794339-8e739680-219e-11e9-85f2-46e02bc9390b.png)
https://github.com/jquery/jquery/issues/2432

Does it makes sense to bump the peer dependency version of jquery to be at least 3.3.1?

**Comment by XhmikosR** [comment]
Unfortunately we can't do that, because last time we bumped the minimum jQuery version we got many complaints.

This is just a warning, and if you install jQuery 3.3.1 or whatever version has the security issues fixed, it'll go away.

**Comment by XhmikosR** [comment]
Closing since we'll drop jQuery anyway.

**Comment by alan-at-1up-health** [comment]
Makes sense.  👍 Thanks for the response.
