### ISSUE TITLE
Popover Action Confirmation

### ISSUE THREAD

**Issue by bhall7** [twbs/bootstrap#28136]
It would be rad if Bootstrap had an officially supported, built-in popover action confirmation feature, similar to the [PopConfirm](https://github.com/Ifnot/PopConfirm) jQuery plug-in. This would allow for confirmation of form submissions, button clicks, or any other action when confirmation is necessary (such as deleting a user or item), and would allow the user to configure various parameters of the popover confirmation such as the placement, the button styles, confirmation verbiage, etc.:
<img width="288" alt="popconfirm" src="https://user-images.githubusercontent.com/513487/51921913-6d30c700-23a5-11e9-9a42-5c9a06c68e59.png">

Example of PopConfirm in action:
http://jsfiddle.net/RDh7E/28/

**Comment by Arvind-Suthar** [comment]
Yup I like the idea. It is really handy to have this component.

**Comment by MartijnCuppens** [comment]
This looks indeed useful but I don't think we 'll add this by default because there are a lot of these handy plugins we could include but will make our codebase harder to maintain.

**Comment by bhall7** [comment]
The suggestion was not to simply include another plug-in, but to add a new feature built natively into Bootstrap. The idea is to be able to eliminate the need for plug-ins. Popover action confirmation is a very common use case.
