### ISSUE TITLE
add css class js to element with or without a "dot"

### ISSUE THREAD

**Issue by Kasperx** [twbs/bootstrap#28133]
In all docs that I read I need to write a dot at the beginning of a classname from bootstrap. But that doesn't work. Only all names without a dot work.
Can someone tell me why pls?

**Comment by XhmikosR** [comment]
Classes as attributes in HTML don't need the dot.

**Comment by patrickhlauke** [comment]
to clarify: the fact that our docs show the dot is simply a convention of the docs (and related to the CSS selector you'd use to target those classes). all our code samples clearly show that the dot isn't meant to be used in the actual html.
