### ISSUE TITLE
Is it necessary to continue using -ms-flex and -ms-flex-wrap?

### ISSUE THREAD

**Issue by Scrabble96** [twbs/bootstrap#28137]
-ms-flex and -ms-flex-wrap are for IE10, IE10 mobile and earlier. Is it necessary to continue including them? Other outdated property prefixes have been dropped, so why not these, too? Anything to reduce file size should be encouraged.

**Comment by browner12** [comment]
could you provide some links to where this is used?

**Comment by XhmikosR** [comment]
Yeah, this will happen in the next major version bump. We can't just do it in a minor or patch release.
