### ISSUE TITLE
List group should support keyboard accessibility just like dropdown

### ISSUE THREAD

**Issue by zadam** [twbs/bootstrap#28132]
Dropdown can be controlled with keyboard (up-down arrows can activate items). 

List group can be used for similar use cases and being able to use keyboard to activate a list item would be very useful.

**Comment by mdo** [comment]
Building on this issue, it'd be awesome if we extrapolated our keyboard navigation from the dropdown menu items and made it applicable to any list of items. GitHub has some awesome keyboard navigation for lists—could be nice to support something like this. Writing down some quick ideas:

- Probably a completely JS-only component that supports keyboard navigation that sets an active and focus styling? With other components extending and supporting as needed?
- Maybe a `data-list` for the parent?
- `data-list-active` or something similar to indicate any child element (independent of markup?) has active focus?
- Customization of keyboard keys used to move up and down (up/down arrows, j/k keys, etc)?

Let me know what you think @twbs/js-review.

**Comment by mrahhal** [comment]
Would like to try my hand at this. I like the idea of having common infrastructure for keyboard navigation logic that can be applied to various components. I've done that on a large scale in my own apps.

A few clarifications if you don't mind.

> Maybe a `data-list` for the parent?

You mean the selector for this new component can be `[data-bs-list="navigation"]` or something like that?

> `data-list-active` or something similar to indicate any child element (independent of markup?) has active focus?

Are you saying this will mark the child elements that _can be focused_, that the navigation component will take into account when handling keyboard events?

> Customization of keyboard keys used to move up and down (up/down arrows, j/k keys, etc)?

Cool idea. Where/on what level will this be configured exactly?

**Comment by mdo** [comment]
Closing as stale.

I'll likely open an issue soon for a v5 plugin for generic keyboard navigation though.
