### ISSUE TITLE
Sass utility mixins for margin and padding

### ISSUE THREAD

**Issue by passcod** [twbs/bootstrap#28149]
_Proposal: to add a set of Sass mixins that mimic the margin and padding utility classes' look and feel, without actually using these._

### Background

On a project early last year, while prototyping views, the margin and padding utilities were used extensively. When it came to finalising the views into solid templates and styles, instead of translating the utilities into plain sizings, we wanted to use the same syntax and set of sizes. After writing a few `padding-top: map-get($spacers, 3)` rules, we wrote a set of mixins that helped. We've been using these across projects for the past year now.

### Rationale

When using Bootstrap, the `.m-1`, `.mx-2`, `.pb-3` classes are available for use in markup. These are highly useful for various reasons I won't rehash. However, they are _not_ useful when paired with `@extend`, because those classes are defined with `!important`.

When one knows the Bootstrap utilities, these mixins are intuitive. Rewriting styles from an inline-classes approach to an external-sass approach is straightforward. Using the same set of sizings everywhere helps with consistency.

### What it looks like

```scss
.action {
  @include ml(3);
  @include px(2);
}

.service {
  @include p(0);
}
```

### Other things we added

The utility classes got negative variants in 4.2. The mixins also have negative variants, but they were written before 4.2, so they use a different syntax. That may be more intuitive, or less, I'm not sure at this point.

```scss
@include mr(-2);
```

The familiar names and the x/y shorthands were great, but sometimes we still needed to use different sizes than the Bootstrap set. So the mixins also accept arbitrary sizes:

```scss
@include my(2.3em);
@include p(3vh);
```

`auto` works through the same mechanism:

```scss
@include ml(auto);
```

### Sizing function

This started off as an internal, but sometimes it's actually useful: the function backing these mixins. For example:

When applying a Bootstrap "standard" space size to something that's not a space, such as borders:

```scss
border-width: bsize(2);
```

Or when doing math:

```scss
border-radius: 6.28 / bsize(2);
```

### Code and question

The code: these mixins obviously already exist, but more, they are already public (aka "I've been forgetting to open this issue for two months"): https://gist.github.com/passcod/a44db3503799cb89c3ccea3f75ca715e

The question: is this something that fits within the scope of Bootstrap itself? I think it's pretty useful, I know people (not just us) like it, but I don't know whether it fits within the vision. That's what this issue is about!

**Comment by MartijnCuppens** [comment]
Hi @passcod,

We're actually trying to get rid of all the mixins that only add one property because they are rarely used and just extends our codebase that needs to be maintained. Adding more mixins will increase the quantity of mixins people will need to learn before they can develop things and this can also lead to mixed usage of properties and mixins (for example if in one place `@include p(0);` and in another `padding: 0;` is used).

We 'll pass on this.

**Comment by passcod** [comment]
No worries, thanks for the consideration nonetheless!
