### ISSUE TITLE
Custom input range thumb not styled properly, when using Sass files.

### ISSUE THREAD

**Issue by JLammeer** [twbs/bootstrap#28145]
- Operating system and version: Windows 10 64-bit
- Browser and version: 
    - Google Chrome 72.0.3626.81 (Official Build) (64-bit);
    - Opera 58.0.3135.53.

### Reduced test case

**HTML**

``` HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <meta http-equiv='x-ua-compatible' content='ie=edge'>

    <link rel="stylesheet" href="main.css">

  </head>

  <body>
    <label for="customRange1">Example range</label>
    <input type="range" class="custom-range" id="customRange1">

  </body>
</html>
```

**SCSS**

``` scss
@import '../node_modules/bootstrap/scss/bootstrap-reboot.scss';

@import '../node_modules/bootstrap/scss/forms';
@import '../node_modules/bootstrap/scss/custom-forms';
```

The shown code generates an input range without proper thumb styling:

![](https://user-images.githubusercontent.com/35262827/52002269-6cb43100-2476-11e9-9097-4e6f3c16eaef.png)

### Notes

- It works fine on Firefox 65.0;
- It works on every mentioned browsers if I import the bootstrap CSS file (`dist/css/bootstrap.css`).

**Comment by MartijnCuppens** [comment]
Hi @JLammeer,

I can't really debug this with the information you provide. I've checked the Bootstrap in Chrome 72 on WIndows and couldn't reproduce this.

**Comment by JLammeer** [comment]
@MartijnCuppens 

I've made [this repository](https://github.com/JLammeer/uglythumb), so you could download the reduced test case.

Make sure you have gulp-cli globally, so you can run `gulp build` or `gulp serve`.

**Comment by TheoBP** [comment]
I think there is an issue with node-sass. I was experiencing the same issue before I switched to dart-sass. The problem is node-sass doesn't add the `-webkit-appearance: none` CSS rule to the `.custom-range` class.

**Comment by patrickhlauke** [comment]
https://getbootstrap.com/docs/4.3/getting-started/build-tools/#autoprefixer

**Comment by MartijnCuppens** [comment]
Yup, it's probably autoprefixer. Thanks for pointing us in the right direction here, @TheoBP!

**Comment by Sire** [comment]
It was indeed. Will make a note in the documentation for my particular build tool (WebCompiler for Visual Studio).
