### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bystefu** [twbs/bootstrap#28146]
Hello, i installed this in server with composer, but i don't know how to use it?I checked in "/public_html/vendor/twbs/bootstrap" and file exist, i run it:

```
Using version ^4.2 for twbs/bootstrap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing twbs/bootstrap (v4.2.1): Downloading (100%)
Writing lock file
Generating autoload files
```
And i trying to put in my php file: 

`use Twbs\Bootstrap;`

and checked at the source page, or simple `<a class="btn btn-danger">test</a>`

but nothing happened.I apologize, i'm new to composer ...

**Comment by rafalp** [comment]
Bootstrap is frontend framework built with HTML/CSS/JS. It's not a PHP package so you can't do `use  Twbs\Bootstrap;` in your PHP script. You will need to write custom PHP to generate HTML that is required by Bootstrap, or use templating engine to do that.

**Comment by mdo** [comment]
Yup, closing since we cannot help with using Composer and PHP here. Sorry! Try StackOverflow or Slack, both linked from our readme.

**Comment by waqaspuri** [comment]
Is there some autoloader ?
