### ISSUE TITLE
Carousel animation not working in Firefox

### ISSUE THREAD

**Issue by kanlukasz** [twbs/bootstrap#28143]
Hello,

Carousel animation not working in Firefox. Slides work but without animation

V 4.0 working fine. I tested you official example:
https://getbootstrap.com/docs/4.0/examples/carousel/

V 4.2 not working in firefox. I tested you official example:
https://getbootstrap.com/docs/4.2/examples/carousel/

System details:
- Windows 7 64 bit
- Firefox 65.0 64bit (tested in Safe Mode)

**Comment by patrickhlauke** [comment]
see the note about `prefers-reduced-motion` in https://getbootstrap.com/docs/4.2/components/carousel/#how-it-works
