### ISSUE TITLE
Unusual lines in Bootstrap modal while hovering/clicking on Input/button controls

### ISSUE THREAD

**Issue by parthsw** [twbs/bootstrap#28154]
Hi,

This is in continuation to Defect #15677. Our application has heavy usage of bootstrap modal. However, Internet explorer 11 has some unusual behavior at 150% zoom level.

For instance, If a modal has input/button controls placed on it then there are some unusual black lines appear on the modal. I have tested this issue with demo examples available on bootstrap official website and it is reproducible. Additionally, If you would click multiple times on any text block, you would find these unusual lines.

I use bootstrap v3.3.7, however, I am able to replicate the issue with latest version as well.

Below are the list of links where issue is reproducible in IE 11 with 150% zoom level:
https://getbootstrap.com/docs/4.0/components/modal/
https://dojo.telerik.com/IdozEHUR/2
https://getbootstrap.com/docs/3.3/javascript/#modals

Attached here are few snapshots of the issue from above links:
![image](https://user-images.githubusercontent.com/30234487/52111665-55b64000-262a-11e9-80d6-00b625b2389b.png)

![image](https://user-images.githubusercontent.com/30234487/52111688-68307980-262a-11e9-8494-e230c4cb728c.png)

![image](https://user-images.githubusercontent.com/30234487/52111757-9746eb00-262a-11e9-8251-38c8cdcabd9d.png)

Looking forward to any concrete solution.

**Comment by parthsw** [comment]
@cvrebert could you please have a look?

**Comment by mdo** [comment]
Finally checked this out on my PC—no issues in IE11 here on v4.0 or v4.4 docs.
