### ISSUE TITLE
Dropdown Input Group Issue

### ISSUE THREAD

**Issue by seanbotha123** [twbs/bootstrap#28150]
Hi guys.

Looks like there is an issue when adding a dropdown button to an input group, and not having the dropdown as the last element, the border-radius' are not correct:

![screenshot from 2019-01-31 07-21-54](https://user-images.githubusercontent.com/5496698/52032299-06d4b180-2529-11e9-8beb-ada5f1714bb2.png)

Please see fiddle for reproduction: http://jsfiddle.net/nxqdgkas/6/

- Operating system and version: **Ubuntu 18.04.1 LTS**
- Browser and version: **Chrome 70.0.3538.77**

Thanks!

**Comment by ysds** [comment]
If you want to use a dropdown on the button that isn't at the last element of the input group, you can do it by using multiple `.input-group-append`s. I mentioned about this usage in #25075, but it isn't described in the documents.

Demo: https://codepen.io/anon/pen/wNJWeL

Why need multiple `.input-group-append`? A `.dropdown-menu` must be the last child of the wrapper (`.dropdown`, `.btn-group` or an element has `position: relative`). This mean the following code is incorrect:

```html
<div class="input-group">
  <input type="text" class="form-control">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown</button>
    <!-- dropdown-menu must be at the last of the container. -->
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
    <button class="btn btn-outline-secondary" type="button">Button</button>
  </div>
</div>
```

So, you should use multiple `.input-group-append`s:

```html
<div class="input-group">
  <input type="text" class="form-control">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown</button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button">Button</button>
  </div>
</div>
```

**Comment by MartijnCuppens** [comment]
@seanbotha123,

You could indeed go for the approach suggested by @ysds.

**Comment by XhmikosR** [comment]
@ysds maybe we should add this to the docs on master/v4-dev?

**Comment by ysds** [comment]
yep it is better for v4. But no need for v5 because #29885 made allow multiple dropdown menus in a single parent.
