### ISSUE TITLE
Accordion parent is not set correctly when setting with Javascript

### ISSUE THREAD

**Issue by Rudedog9d** [twbs/bootstrap#28159]
It appears that setting the parent of an accordion with Javascript (as described in [the docs](https://getbootstrap.com/docs/4.0/components/collapse/#via-javascript)) does not set the `data-parent` attribute on the DOM element. This causes the element to not collapse when another element is selected.

I suspect the problem is related to [collapse.js#132](https://github.com/twbs/bootstrap/blob/9e4e94747bd698f4f61d48ed54c9c6d4d199bd32/js/src/collapse.js#L132)

### Steps to reproduce

- Take the [example from the docs](https://getbootstrap.com/docs/4.0/components/collapse) and convert the first card to be initialized with JS instead of HTML.
  - JS FIDDLE: https://jsfiddle.net/4ykrjwgo/3/
- Open Card 2
- Open Card 1
  - Observe Card 2 collapses as expected
- Open Card 2
  - Observe Card 1 **does not** collapse as expected

**Comment by Rudedog9d** [comment]
This may be related to #23767

**Comment by Johann-S** [comment]
This condition is needed because we allow nested accordion, without that we can't find which collapse element is related to which accordion.

So you have to set the `data-parent` on your collapse element

**Comment by Rudedog9d** [comment]
I'm still unclear what the `parent` option within the JS constructor is for. It might be useful (for myself and others) to provide an example of how `$('.collapse').collapse({parent: ...})` can be used in the docs

**Comment by KushalBhanot** [comment]
Hey! I would like to work on this issue. Can someone please guide me?

**Comment by mdo** [comment]
I think we need to update the Collapse docs to remove the mention of explicitly tying `parent` to the `.card` class now that we have Accordion in v5: https://getbootstrap.com/docs/5.0/components/accordion/.

Is there something else to do here beyond that?

**Comment by mdo** [comment]
Closing as stale for v4. We'll be moving onto focus entirely on v5 and v4 will only see critical updates.
