### ISSUE TITLE
Suggestion for .table-hover

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#28160]
If you use different styles for individual cells in a table to set the background color, e.g., \<td class="table-warning"\>...\</td\>, the hovering effect is not propagated to those cells.

I am not an expert on CSS, but I was able to add the following lines to my CSS file:

.table-hover **tbody** **tr**:hover > .table-warning {
&emsp;&emsp;background-color: #ffe8a1;
}

I don't know if this is the best way, or even if it is correct, it works for me.  I think it would be a good addition to a future release.

**Comment by mdo** [comment]
Punting on individual cell hovering, sorry.

**Comment by rxbracho** [comment]
A disappointing decision, because some of us use background colors to signal different situations in a table, and thus they are used at the <td> not <tr> level.  And I have all the CSS modifications to bootstrap.css (I load them in my style sheet), so the only work on your part was to check them out and release them.  I did much more work than what I posted in the original bug report.

Cheers,
Rafael

From: Mark Otto 
Date: 06 March 2020 10:22
To: twbs/bootstrap 
Cc: Rafael Bracho ; Author 
Subject: Re: [twbs/bootstrap] Suggestion for .table-hover (#28160)
Punting on individual cell hovering, sorry.

**Comment by tmorehouse** [comment]
@rxbracho hopefully the linear-gradient background image "hack" will be styled to move the hover/strip effect to the cells (which will work regardless of where the variant colors are applied to the table).  See comment https://github.com/twbs/bootstrap/issues/29244#issuecomment-595610814
