### ISSUE TITLE
Expose toast states

### ISSUE THREAD

**Issue by karimcambridge** [twbs/bootstrap#28165]
Can toast states be exposed to the user?

Example, to check if a toast is currently being shown, or if it's hidden. Get the current toast's delay.
Is the toast being auto hidden? Is the toast's animation on?

A function to toggle toast's animation also.

This will greatly improve toast usage.

**Comment by Johann-S** [comment]
You can have those information currently 😉 

If a toast is currently being shown or hidden: `$('#yourToast').hasClass('.show')`

To get internal attribute you can do: 
```
var toast = $('#yourToast').data('bs.toast')
console.warn(toast._config)
```

to toggle the animation you can simply add `.fade` to your toast
