### ISSUE TITLE
Dropdown menu items won't trigger click event after the first time if dropdown closed programmatically

### ISSUE THREAD

**Issue by BillHenning** [twbs/bootstrap#28161]
We are running into an bad issue where we have a dropdown menu, and when we click a menu item link, we want to close the dropdown, perform an action (like show a dialog), and prevent any navigation (we normally 'return false' in the click handler).  

This repro shows the issue, although we didn't need to include a 'return false;' at the end to trigger the issue:
https://jsbin.com/joduwoviqe/1/edit?html,js,output

Anyhow if you open the dropdown and click the menu item, you'll see an alert box the first time.  The dropdown is closed per the manual toggle.  But from this point on, clicking the menu item won't trigger a click.

This is a blocking issue for us.  Is there a workaround for this issue, or a better way to achieve the same goal?  

Is it a confirmed bug?  It seems like we should be able to close the drop-down in the click handler without repercussions.

**Comment by BillHenning** [comment]
It will if you don't return false at the end.  However if you do return false without calling toggle, that default close logic won't occur:

`$(document).on('click', 'a.dropdown-item', function(){
  // $(".dropdown.show").dropdown("toggle");
  alert("CLICK")
  return false;
})`

So here's the thing, I want to return false at the end because otherwise my link href will get navigated to.  I want to keep the page position in the same spot it's at without navigation.  Returning false achieves that.  But then the only way to get rid of the dropdown is to programmatically toggle it and that triggers the bug I show.

**Comment by Johann-S** [comment]
Instead of returning `false` you should call `preventDefault()` and it will stop the navigation see: https://jsbin.com/tameyetoco/edit?html,js
