### ISSUE TITLE
bootstrap 4.2.1 toast delay does not 'restart' if the toast is shown again before the timeout ends

### ISSUE THREAD

**Issue by karimcambridge** [twbs/bootstrap#28164]
The title explains it well.

```if(this._timeout !== null) {
    clearTimeout(this._timeout)
}
```

The code above should be added in `show()` for the toast class at https://github.com/twbs/bootstrap/blob/9e4e94747bd698f4f61d48ed54c9c6d4d199bd32/js/src/toast.js#L80

- Windows 10.0.17763 Build 17763
- Version 71.0.3578.98 (Official Build) (64-bit)

Don't think there is need for a test case.

**Comment by Johann-S** [comment]
Hi @karimcambridge,

I tried to reproduce your issue but I'm not able to 😟 
See my CodePen: https://codepen.io/Johann-S/pen/QYqrPw

**Comment by karimcambridge** [comment]
https://codepen.io/karimcambridge/pen/RvLdGr

Try now, with a larger data-delay (5000).

**Comment by Johann-S** [comment]
Hmm ok now I understand 👍 

For me in this particular use case, I would call manually `show` and `hide` method to avoid that behavior, but you're right we should fix that 👍

**Comment by karimcambridge** [comment]
Thank you.

**Comment by jeffehobbs** [comment]
FYI for anyone still grappling with this, I worked around it by "disposing" of the toast before showing it again.

**Comment by karimcambridge** [comment]
Same, but needs to be fixed.

**Comment by davidluhn** [comment]
Has this been fixed?
