### ISSUE TITLE
Small Forms: custom-file-control and input-group don't work well with form-control-sm

### ISSUE THREAD

**Issue by petertorelli** [twbs/bootstrap#28167]
Forms that are using `form-control-sm` and `custom-select-sm` do not match visually with `custom-file-input/label` because the latter do not support a small mode. Same goes for input groups: `form-control-sm` only impacts the label and not the overall group.

Here is a jsfiddle illustrating the problem on the latest bootstrap:

https://jsfiddle.net/5sxavyp9/1/

If there is a hidden combo of modifiers already in the library that fix these two issues, please document it on the form pages.

Thanks,
Peter

**Comment by mdo** [comment]
Sizes have been added for file input in v5 with the new markup.
