### ISSUE TITLE
Screen reader breakpoint classes

### ISSUE THREAD

**Issue by NickDJM** [twbs/bootstrap#28162]
It would be handy to have breakpoint selectors within the `.sr-only` class.

There have been a few times where sites I've worked on need to reveal hidden items at certain breakpoints.

**An example:**
A section on a page has enough visual context (through menus or otherwise) to tell a sighted user where they are, but for visually impaired users you have a heading with `.sr-only`. 

When you go to a mobile display however, maybe some objects are moved or menus collapsed and sighted users no longer have any context as to where they are or what they're looking at. This would be when a class such as `.sr-md-only` would come in handy.

If we take this one step further, we could hook into all of the media breakpoints to have classes like `.sr-md-up`, `.sr-md-down`, and `sr-md-only`.

Using the media-breakpoint and sr mixins makes it real simple to implement something like:

```scss
@each $breakpoint, $value in $grid-breakpoints {
  .sr-#{$breakpoint}-only {
    @include media-breakpoint-only($breakpoint) {
      @include sr-only;
    }
  }

  .sr-#{$breakpoint}-up {
    @include media-breakpoint-up($breakpoint) {
      @include sr-only;
    }
  }

  .sr-#{$breakpoint}-down {
    @include media-breakpoint-down($breakpoint) {
      @include sr-only;
    }
  }
}
```

We could implement similar to `.sr-only-focusable` as well.

**Comment by MartijnCuppens** [comment]
Hi @NickDJM,

I get the idea, but the amount of code that will be generated will be huge because the `sr-only`  mixin generates 8 lines of code. We'll pass on this for now.
