### ISSUE TITLE
Switches to support the :indeterminate pseudo class

### ISSUE THREAD

**Issue by jpduvet** [twbs/bootstrap#28174]
Custom checkboxes can utilize the :indeterminate pseudo class when manually set via JavaScript (there is no available HTML attribute for specifying it).
A switch has the markup of a custom checkbox but uses the .custom-switch class to render a toggle switch. 

Switches should support the :indeterminate pseudo class.

(https://getbootstrap.com/docs/4.2/components/forms/)

**Comment by ysds** [comment]
Interesting. But the Google, Apple and Microsoft’s switches don’t have the tri state.

Can you show a use case and a demo?

**Comment by jpduvet** [comment]
A typical use case: settings.

A single parameter can only be 'on' or 'off'.
To enable settings of many parameters at once (set all to 'on' or all to 'off') you need first to show a control representing the current situation: all are currently 'on', all are currently 'off' or there is currently a mix of 'on' and 'off'.

The later case can be done with custom Bootstrap checkbox (:indeterminate) but not with Bootstrap switch.

From a design point of view for 'indeterminate' switch, some UI use a switch without toggle:
![image](https://user-images.githubusercontent.com/31750764/52924069-e3ea3000-3365-11e9-8829-31c297ac1501.png)
and some others use a toggle in a middle position:
![image](https://user-images.githubusercontent.com/31750764/52924116-3592ba80-3366-11e9-9974-1c7c4c3fcdf8.png)

**Comment by mdo** [comment]
Thanks, but after review, we won't be changing anything here.

**Comment by umbrient** [comment]
Ah dang it, would be useful.

**Comment by radu-cs** [comment]
This is easily achieved using CSS.
```CSS
.form-switch .form-check-input:indeterminate {
  background-position: center;
  background-color: var(--bs-body-bg);
  border-color: var(--bs-body-color);
}
```

**Comment by OlegKlimenko** [comment]
This is amazing, @radu-cs !
Thank you!

**Comment by radu-cs** [comment]
> This is amazing, @radu-cs ! Thank you!

You are welcome!
I'm glad it helped. 🙂
