### ISSUE TITLE
Secondary action for list-group

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#28177]
A common usage on mobile apps is to have a list with a large primary action area and a smaller secondary action to the side.

Where 3 in the image below could be for example a **⋮** (vertical ellipsis) button.

The list group component in Bootstrap currently does not support this usage. It would be nice if it did.

<img src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1yj1ckm1If1FCbn6fgBuEHB4LexRNi30l%2Flist-elements-2.png" />

**Comment by tmorehouse** [comment]
Could you not just use a non-action list-group-item, and then embed a flex row with the avatar, a link and the checkbox (or ellipsis button)?  Or nest a media component inside the list-group-item with the avatar, link, and checkbox?

**Comment by vanillajonathan** [comment]
I don't know. The image is just an example, I am not all that interested in a avatar, but more interested in having a secondary action (aligned to the right side) with a checkbox, switch, button or dropdown menu.

https://jsfiddle.net/vgdh6nr8/
It doesn't seem to be any clear way to have a primary and secondary action.

**Comment by ocarreterom** [comment]
@vanillajonathan you can combine some utility classes.
https://jsfiddle.net/sqxpcgef/6/

**Comment by vanillajonathan** [comment]
That has only one action that covers the whole row. It does not have a primary action and a secondary action.

**Comment by ocarreterom** [comment]
Something like this? https://jsfiddle.net/d987234a/6/
(It's true that the switch it's not clickable without label 🤔 )

**Comment by vanillajonathan** [comment]
A bit messy with so many classes, but yeah something like that.

**Comment by dragontheory** [comment]
Many of us out here are looking to do something similar but with a checkbox and label [https://jsfiddle.net/dragontheory/78aj5dhr/](https://jsfiddle.net/dragontheory/78aj5dhr/) . The entire list-item toggles the checkbox. Seen various implementations but all seemed a bit kludgy. This type of layout enables bulk actions such as select/deselect all or groups of product filters like Amazon.  Is there a better or even an "official solution"?

**Comment by tmorehouse** [comment]
Why not place a media conponent I side a list group item? The media aside could be the dripdown/checkbox, etc, and the content could be an anchor tag.

**Comment by dragontheory** [comment]
In my case, I need the entire list-item (or whatever) to be clickable to toggle the checkbox. I am just looking for the most efficient semantic solution or if there is an "official solution" that I may have missed. This is probably not the right context and I should post my question in a new thread? Thanks!

**Comment by MartijnCuppens** [comment]
https://twbs-bootstrap.netlify.com/docs/4.3/components/list-group/#checkboxes-and-radios, additional theming can be done with utility classes.
