### ISSUE TITLE
modal backdrop new class option & class manager

### ISSUE THREAD

**Issue by rejoan** [twbs/bootstrap#28170]
Currently there are no option in bootstrap modal to add new class into backdrop when a modal opened. We generally do it by `$('#modalID').on('shown.bs.modal')` this but there should be a such option when modal created like below
```
$('#myModal').modal({
  class: 'my_custom_class'
})
```

Secondly when a modal being closed then `modal-open` class should remain available as it is in `<body>` tag until last modal close.

Hope bootstrap next release will consider this 2 minor feature but very much important when work with multiple modal

**Comment by Johann-S** [comment]
Hi @rejoan,

We do not support multiple modal as it said in our documentation, and what you describe seems pretty simple to handle on your side, so we will pass on that.

Thank you for using Bootstrap ❤️
