### ISSUE TITLE
Carousel prev/next not responding

### ISSUE THREAD

**Issue by digitall-it** [twbs/bootstrap#28179]
Carousel prev/next buttons do not work in dev environment (local web server) but work by loading the HTML static file. Seems like the carousel finds the prev/next links, but doesn't detect their `href` target. As there is a `data-target` attribute that works the same way, I used it to circumvent the problem. 

The webpack is pretty standard, it imports bootstrap as a whole.

Chrome console reports:
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '/#carousel_element_15' is not a valid selector.
    at Object.getSelectorFromElement (webpack-internal:///2:149:35)
    at HTMLAnchorElement._dataApiClickHandler (webpack-internal:///2:1065:27)
    at HTMLDocument.dispatch (webpack-internal:///0:5183:27)
    at HTMLDocument.elemData.handle (webpack-internal:///0:4991:28)
getSelectorFromElement @ bootstrap.js?2b72:149
_dataApiClickHandler @ bootstrap.js?2b72:1065
dispatch @ jquery.js?eedf:5183
elemData.handle @ jquery.js?eedf:4991
```

Ambient:
- Tried on v4.1 and v4.2.1
- Happens on real HTML code and on demo sample from the website
- webpack compiled JS/CSS bundle
- macOS Mojave
- Safari and Chrome, latest production

_I would like to express my gratitude for the work that all the community is doing. In no particular order, from the programmers to the testers, the supporters and the documentation writers._

**Comment by XhmikosR** [comment]
Same as other issues, that's not a valid selector and you should fix it eventually because it can break again.

That being said it's fixed in v4-dev and will be in the next version.
