### ISSUE TITLE
Change the default toast duration

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#28185]
The default toast duration is 500 milliseconds.

I would argue that this duration is too short which leads to the toast often disappearing before user can fully read the toast message.

I argue in favor of raising the default toast duration.

Android also have the concept of toasts and provides two constants. `SHORT_DELAY` at 2000 ms and `LONG_DELAY` at 3500 ms.

**Comment by Johann-S** [comment]
Hi @vanillajonathan,

You can override that by passing options when you create your toasts for example:
```js
$('#yourToast').toast({
  delay: 2000
})
```

But you're right on one thing, we should change the default options of our Toast plugin, to allow you to change that for all of your toasts 🤔

**Comment by Johann-S** [comment]
@vanillajonathan #28186 merged so in our next release you'll be able to do:
```js
bootstrap.Toast.Default.delay = 2000
```

And it'll be the default delay for all of your toasts 😉

**Comment by vanillajonathan** [comment]
Yes, I am aware that the duration can be changed by passing in options. My point was that the _default_ duration is too short.

Also my request is not for the introduction of a variable or property to define the default duration, but for the Bootstrap project to consider increasing the default duration.

**Comment by vanillajonathan** [comment]
Android have constants for a long  and a short duration, they are 4 seconds for the short toast and 7 seconds for the long toast.

These _might_ be well thought out (or not?) durations backed by UX research.

https://github.com/aosp-mirror/platform_frameworks_base/blob/android10-release/core/java/android/widget/Toast.java#L384
> ```java
> static final long SHORT_DURATION_TIMEOUT = 4000;
> static final long LONG_DURATION_TIMEOUT = 7000;
> ```
