### ISSUE TITLE
Toggle button

### ISSUE THREAD

**Issue by rudyhadoux** [twbs/bootstrap#28180]
Hi,

I am a fan of Bootstrap 4 but I do not understand why you don't have Toggle Buttons like Material ?

Rudy.

**Comment by patrickhlauke** [comment]
https://getbootstrap.com/docs/4.2/components/buttons/#toggle-states ?

**Comment by patrickhlauke** [comment]
https://getbootstrap.com/docs/4.2/components/forms/#switches ?

**Comment by nteetor** [comment]
Hello Rudy,

Have you looked at the button plugin, https://getbootstrap.com/docs/4.2/components/buttons/#button-plugin ? The checkbox plugin behaviour seems similar to toggle buttons.

Whoops, seconds behind Patrick.

**Comment by rudyhadoux** [comment]
I did not know B4 switches... Nice.
Thanks.
