### ISSUE TITLE
.table-striped tbody tr:nth-of-type(odd) { background-color: rgba(0, 0, 0, 0.05); } doesn't work on Firefox

### ISSUE THREAD

**Issue by vfilatov** [twbs/bootstrap#28190]
.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgba(0, 0, 0, 0.05);
}
---
doesn't work on Firefox
change rgba(0, 0, 0, 0.05); -> rgba(0, 0, 0, 0.1); as workaround

- Operating system and version (Ubuntu 18.10)
- Browser and version (Firefox 65.0 (64-bit))
- [Reduced test case]https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_table_striped&stacked=h

```
<div class="container">
  <h2>Striped Rows</h2>
  <p>The .table-striped class adds zebra-stripes to a table:</p>            
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
  </table>
</div>
```

**Comment by XhmikosR** [comment]
Works fine here.

![2019-02-06_20-26-45](https://user-images.githubusercontent.com/349621/52364322-9c9e9e00-2a4d-11e9-9826-9354d7a6b9ff.jpg)
