### ISSUE TITLE
3.7 Customize Broken

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#28198]
![screencapture-getbootstrap-docs-3-3-customize-2019-02-07-21_26_53](https://user-images.githubusercontent.com/5879776/52405557-ab558580-2b1f-11e9-9a83-2242841549fd.png)

**Comment by XhmikosR** [comment]
1. 3.7 isn't a valid version
2. if you meant 3.3.7, you are out of luck, it'll be broken, so just use 3.4.0.
