### ISSUE TITLE
Breakpoint specific border removal

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#28191]
It would be useful to have breakpoint specific border removal classes such as: `border-md-none` or something similar. I often find myself having to remove borders particularly when three elements are side by side with a separating middle line that then requires removal on mobiles due to stacking elements. Thanks! https://getbootstrap.com/docs/4.2/utilities/borders/#border

**Comment by MartijnCuppens** [comment]
Hi @sts-ryan-holton,

You 'll be able to achieve this with our utility API which will land in `v5`. https://twbs-bootstrap.netlify.com/docs/4.3/utilities/api/
