### ISSUE TITLE
Bootstrap without jquery

### ISSUE THREAD

**Issue by slloyd88** [twbs/bootstrap#28206]
In my humble opinion Bootstrap would be used WAY more if it did not have a jQuery dependancy.   That is my biggest issue with Bootstrap and why I  switch to to other platforms instead of evangelizing Bootstrap.  Can you please make Bootstrap independent?

**Comment by mdo** [comment]
#23586

**Comment by bardware** [comment]
> would be used WAY more

Highly doubt that.
