### ISSUE TITLE
Readonly plain text inside input group 

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#28205]
`.form-control-plaintext` inside `.input-group`s are supported from v4.2  (#25871). But the result is:

![image](https://user-images.githubusercontent.com/4065765/52458710-67f12a80-2ba4-11e9-8c66-6fd9c60dd9b5.png)

Demo: https://codepen.io/anon/pen/aXEGMZ

It this an expected appearance?

**Comment by alecpl** [comment]
I has been suggested elsewhere that using readonly form-control is the way to go. However, I agree that if we support form-control-plaintext there it should be fixed or the support should be removed.
