### ISSUE TITLE
Dark toast variant

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#28201]
I would like to propose the addition of a dark variant of the toast component.

**Comment by KrisKodira** [comment]
Maybe something like this:

<img width="404" alt="bildschirmfoto 2019-02-21 um 12 50 07" src="https://user-images.githubusercontent.com/24395956/53167077-4302ab80-35d7-11e9-9162-206013013f62.png">

**Comment by bardiharborow** [comment]
Will likely be shipped with #27514.

**Comment by vanillajonathan** [comment]
But it would be nice to be able to use the dark toast variant on light backgrounds too. Because if you do it without the header, and position it at the bottom of the screen then it looks like the [snackbar](https://material.io/design/components/snackbars.html) component from Material Design as used in Android.
