### ISSUE TITLE
Dropdown + data-target documentation

### ISSUE THREAD

**Issue by stevelacey** [twbs/bootstrap#28207]
Dropdowns support `data-target` but it has to reference a parent to both the `.dropdown-menu` and the trigger – which is not something I understood until I banged my head against it for a while and read through the source, this either needs documenting or changing – maybe it's a bootstrap standard for `data-target` I missed but I totally assumed it'd have to reference the `.dropdown-menu` given that's the "perceived default" if you don't supply the target.

The resulting behaviour of getting it wrong is that the dropdown will pretty much work correctly but doesn't close when you click the trigger whilst the dropdown is open.

**Comment by dom111** [comment]
I've been looking around for a solution to this and rather than documenting what it does currently, would it be worth adding in functionality for `data-target` to allow targeting a specific `.dropdown-menu` directly if specified, falling back to `SelectorEngine.findOne(Selector.MENU, parent)` otherwise?

**Comment by dario-l** [comment]
`data-target` is really helpful. This would allow to create dropdown-menu with `form` out of scope of the current container which can be another `form`.

**Comment by mdo** [comment]
Not only is this stale, but I don't think this is applicable? We don't use `data-target` on any of our dropdown docs in v4 or v5. This is tagged as a docs issue and I'm not seeing a docs issue to work out here, so closing it out as a won't fix. If I missed something and this still applies to v4 or v5, please open a new issue with some additional information. Thanks!
