### ISSUE TITLE
list-group-flush has a double border

### ISSUE THREAD

**Issue by oldrich-s** [twbs/bootstrap#28213]
- Windows 10 x64
- Chrome 72.0.3626.96 (Official Build) (64-bit)

Border of `list-group-flush` here:

https://getbootstrap.com/docs/4.2/components/list-group/#flush

looks ugly because `border: 1px solid rgba(0,0,0,.125);` is applied - so every item has a double border:

![image](https://user-images.githubusercontent.com/37391/52482867-b0afe000-2bb2-11e9-8374-c81c0fbd7a85.png)

vs:

![image](https://user-images.githubusercontent.com/37391/52482903-cc1aeb00-2bb2-11e9-98fc-947c9d7c5b6b.png)

Is it not possible to use only single border (e.g. only top) to make it look nice?

**Comment by bardiharborow** [comment]
Fixed by #28940.
