### ISSUE TITLE
Tooltips on disabled button wrapper also don't work

### ISSUE THREAD

**Issue by smares** [twbs/bootstrap#28211]
I am trying to display tooltips for some buttons that trigger Bootstrap 3 modals. Due to limitations of Bootstrap regarding only a single type being supported for `data-toggle` as well as the fact that disabled buttons don't emit mouse events, I wrapped the buttons in some elements that have the tooltips while the buttons themself trigger the modals.

With Chrome 71 and Edge 44 / EdgeHTML 18, the tooltip of the button wrapper is not displayed when the button is disabled. It works in Firefox 65 though.

See a codepen here: https://codepen.io/smares/pen/QYaPKr

Any idea how to work around this?

**Comment by razh** [comment]
You need to add `pointer-events: none` to the disabled buttons.

https://getbootstrap.com/docs/4.3/components/tooltips/#disabled-elements

https://github.com/twbs/bootstrap/blob/1ded0d6a4eefb7daca62c44e4e735aec200f0b6f//site/docs/4.3/components/tooltips.md#L129-L140

https://jakearchibald.com/2017/events-and-disabled-form-fields/

> Turns out, mouse events don't fire when the pointer is over disabled form elements, except in Firefox.

**Comment by smares** [comment]
Thanks! https://codepen.io/smares/pen/vbrLVY
