### ISSUE TITLE
Use run-p and run-s shortcuts installed with npm-run-all

### ISSUE THREAD

**Issue by fifn2** [twbs/bootstrap#28217]
[npm-run-all](https://www.npmjs.com/package/npm-run-all) comes preinstalled with two shortcut commands, [run-s](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/run-s.md) and [run-p](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/run-p.md), short for `npm-run-all [commands]` and `npm-run-all --parallel [commands]`, respectively. Why not use them instead of the npm-run-all command?

**Comment by XhmikosR** [comment]
Mostly because I personally prefer to be explicit and because the package name is `npm-run-all`.

But we might revisit later.
