### ISSUE TITLE
Wrong bottom margin in responsive tables

### ISSUE THREAD

**Issue by Miqueliu** [twbs/bootstrap#28214]
I saw that in version 3 tables (`.table`) have problems with bottom margin when these are wrapped by a scrolling `.table-responsive`.

[Here](https://jsfiddle.net/r2apfbez/1/) is a live testing. The error is in the second table: The scroollbar is separated to its table and joined to next element.

I think a possible solution is (in Less):

> ``` less
> .table-responsive {
> 	margin-bottom: @line-height-computed;
> 	> .table {
> 		margin-bottom: 0;
> 	}
> }
> ```

**Comment by ysds** [comment]
We're no longer maintaining v3. It'll soon be EOL (end of life) entirely, so closing this.

**Comment by Miqueliu** [comment]
[In version 4, the same happens](https://jsfiddle.net/4b6gryws/1/).

In this case, its solution would be:

> ``` scss
> .table-responsive {
> 	margin-bottom: $spacer;
> 	> .table {
> 		margin-bottom: 0;
> 	}
> }
> ```

**Comment by mdo** [comment]
I think I'm inclined to leave this as-is, given there's been very little reporting of this being a problem and it prevents the scrollbar from overlapping the last row of the table.
