### ISSUE TITLE
Crossfade carousel with transparent background

### ISSUE THREAD

**Issue by Daegaladh** [twbs/bootstrap#28227]
- Windows 10 x64
- Chrome 72.0.3626.96 (64 bits)
- Firefox 65.0 (64-bit)

In v4.2.1 crossfade carousel performs a sudden transition when changing between images.
This is not visible with opaque backgrounds, but looks really ugly when working with transparent backgrounds or images.

This bug was introduced in 5aed968750177ec35f99dc03e71eec3632beb844

- Example: https://jsbin.com/xomelak/2

**Comment by jahanzaibsuleman07** [comment]
Hi @XhmikosR, I have created the [PR](https://github.com/twbs/bootstrap/pull/28278) for this fix. This is my first PR for bootstrap. Please review. Thanks!

**Comment by mdo** [comment]
Closing per closed PR.
