### ISSUE TITLE
Question: How should security issues be reported

### ISSUE THREAD

**Issue by markcarver** [twbs/bootstrap#28222]
I cannot find any documentation on how to report security issues for this project.

Ideally, they should be reported in confidence to the maintainers. A direct message, however, seems inappropriate and could potentially get lost.

I'm honestly a bit surprised that GitHub doesn't have a mechanism that allows someone to create a security issue for a project that only the OP and maintainers can view.

Is there another service this project uses for reporting security issues that just isn't documented?

**Comment by markcarver** [comment]
I have a security vulnerability to report that affects the latest releases, both 3.4.0 and 4.2.1.

**Comment by XhmikosR** [comment]
You can send me an email with the info for now.

**Comment by markcarver** [comment]
Sent

**Comment by bardiharborow** [comment]
We're working on a contact process internally and will be announcing it shortly (i.e. in [6 to 8 weeks](https://meta.stackexchange.com/questions/19478/the-many-memes-of-meta/19514#19514)).
