### ISSUE TITLE
Card header 1px width error.

### ISSUE THREAD

**Issue by newsash** [twbs/bootstrap#28224]
Windows 10
Google Chrome 71

https://codepen.io/anon/pen/aXYYQK
1px flickering between header and border while resizing window - I think it's rounding issue
![image](https://user-images.githubusercontent.com/6377930/52540075-90407b00-2d96-11e9-8c1a-75f1605df939.png)

**Comment by mdo** [comment]
Don't think there's anything we can do here—the browser is misrendering on a half pixel or so, creating the visible gap you're seeing. No good way around that unless we're redoing how we build the component, which isn't likely to happy. Sorry!
