### ISSUE TITLE
Firefox checkbox shown as checked when is unchecked

### ISSUE THREAD

**Issue by jacofda** [twbs/bootstrap#28229]
firefox 65.0 / ubuntu 18.04 / bootstrap 4.2.1

in firefox 

`           <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="pickup" id="pickup">
                    <label class="custom-control-label" for="pickup">Pickup</label>
                </div>
            </div>`

sometimes is shown as checked and other not.
[https://streamable.com/cbvok](url)

in Chrome all fine
[https://streamable.com/kgu7y](url)

css applies ::checked even when is not
![screenshot from 2019-02-11 21-12-37](https://user-images.githubusercontent.com/14827571/52587065-c850c800-2e41-11e9-84aa-4237ded05189.png)

as you can see in the screenshot the input type="checkbox" is not checked, but the css applies .custom-checkbox .custom-control-input:checked ~ .custom-control-label::after

any solution other than changing input type?
thanks

**Comment by patrickhlauke** [comment]
as the styling relies solely on the `:checked` pseudo-class, which is controlled by the browser itself, i'd check first at your end if your site/code is setting the checked property correctly in firefox

**Comment by mdo** [comment]
We also cannot help without a reproducible example, as mentioned in our issue template.

---

Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by ysds** [comment]
Closing per last comment.
