### ISSUE TITLE
v4.2.1 doesn't show as outdated version

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#28234]
Hi 👋 I appreciate 4.3 has just been released :rocket: but I thought a notice at the top of the 4.2.x docs would automatically show as an outdated version? There isn't one despite clearing caches? I thought this might've been an automatic feature, see: https://getbootstrap.com/docs/4.2/getting-started/introduction/

**Comment by XhmikosR** [comment]
It's not automatic
