### ISSUE TITLE
Checkbox and radio buttons : no cursor pointer on buttons hover

### ISSUE THREAD

**Issue by ghusta** [twbs/bootstrap#28237]
## Environment

- OS : Win 10
- Browser : Firefox 65.0 / Chrome 72.0

## Test case

Since version 4.3, when hovering the mouse pointer on a radio button within a button group (_btn-group-toggle_), there is no cursor pointer anymore. It worked with version 4.2.

The behaviour is the same with both examples in the documentation (group of 1 button / group of 3 buttons).

Reproducible within the documentation :
- v4.2 : https://getbootstrap.com/docs/4.2/components/buttons/#checkbox-and-radio-buttons 🆗 
- v4.3 : https://getbootstrap.com/docs/4.3/components/buttons/#checkbox-and-radio-buttons 🐛 

For information, I had this style enabled in version 4.2 with `cursor: pointer`, but not anymore in version 4.3 : 
> .btn:not(:disabled):not(.disabled)

**Comment by patrickhlauke** [comment]
this is intended. by default, browsers don't provide a pointer cursor for checkboxes and radio buttons, so the opinionated use of `cursor: pointer` was moved in 4.3 - see https://github.com/twbs/bootstrap/pull/27021

**Comment by ghusta** [comment]
Thanks for the clarification and for pointing me to this PR.
I find it strange since it primarily looks like buttons, but OK...

**Comment by patrickhlauke** [comment]
(FWIW buttons also don't get a pointer cursor by default)

**Comment by ghusta** [comment]
I better understand this intention by looking at these links :
- [#26998](https://github.com/twbs/bootstrap/issues/26998)
- [Buttons shouldn’t have a hand cursor](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)

But when you say that buttons don't get a pointer cursor by default, this behaviour doesn't seem to have been updated according to the documentation v4.3 ? 

For example on https://getbootstrap.com/docs/4.3/components/buttons/ buttons still have a pointer cursor, whatever they are html buttons, links with role = "button", etc.

**Comment by patrickhlauke** [comment]
oh, interesting. maybe i've missed one of the iterations of the overall discussion (it's been going back and forth for months/years). i'll dig in and see why we now have this mismatch again...

**Comment by astegmaier** [comment]
I agree with @ghusta that it seems a bit strange to say at the same time "things styled with the `btn` class _shouldn't_ have the hand cursor" and "`<button>` elements _should_ have the hand cursor".

It looks like both changes were made in the same PR - #27021 ([here ](https://github.com/twbs/bootstrap/pull/27021/files#diff-7f9eec82312835f6155c8de839bf0e49R352)and [here](https://github.com/twbs/bootstrap/pull/27021/files#diff-8a4fc4262c9197c73b80fb80d8863ae5L37)).
