### ISSUE TITLE
data-trigger="focus" doesn't work on svg elements

### ISSUE THREAD

**Issue by vikkya** [twbs/bootstrap#28239]
Hi,
I'm using bootstrap 4.1 version. I tried to implement bootstrap popover on a svg circle element. It is working fine until I add data-trigger="focus" to the element. 
It works with other data-trigger options. and it works fine with other HTML elements.
I have added a fiddle link below.

- Operating system and version (Windows 10)
- Browser and version (Chrome (latest version))
-[JS fiddle](https://jsfiddle.net/g4sn2qbe/1/)

Thanks.

**Comment by razh** [comment]
By default, SVG elements are not focusable so you have to add `tabindex="0"`.

https://allyjs.io/tutorials/focusing-in-svg.html#making-svg-elements-focusable

**Comment by vikkya** [comment]
Thanks @razh. :)
