### ISSUE TITLE
Chrome macOS Adding Padding

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#28241]
Very odd, I'm seeing the same thing as this issue #7519.

I'm running macOS Chrome Version 72.0.3626.96 (Official Build) (64-bit)

Somehow the `user agent stylesheet` is not being overridden with normalize.

```
ul, menu, dir {
    display: block;
    list-style-type: disc;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    padding-inline-start: 40px;
}
```

**Comment by mdo** [comment]
That was likely true in v2/v3 back in 2013, but we no longer reset the `padding-left` on those elements as part of Reboot. I don't believe we have for some time now. Closing as a won't fix for the time being.
