### ISSUE TITLE
The `disabled` property value of the custom radio button is not reflected in the display on Microsoft Edge

### ISSUE THREAD

**Issue by 4dn-oss** [twbs/bootstrap#28247]
On Microsoft Edge, on changing the `disabled` property value of a custom radio button from JavaScript, the display of radio button is not updated. The display of radio button is updated correctly on  Firefox (65), Chrome (72.0.3626.96), IE11 (11.590.17134.0).

OS: Windows 10 (1803)
Browser: Microsoft Edge (42.17134.1.0)

Sample: https://codepen.io/4dn-oss/pen/KJeOdz

Expected Behavior: Every time the 'disable/enable' button is clicked, radio buttons will be disabled/enabled.
Result: On Microsoft Edge, radio buttons are always displayed as if it is enabled.

**Comment by ysds** [comment]
Confirmed on Windows 10 (1809), Microsoft Edge 44.17763.1.0

![edge](https://user-images.githubusercontent.com/4065765/52720050-3e902e80-2fea-11e9-92c8-62c90a0a61a4.gif)

I found a similer report: https://github.com/IBM/carbon-components/issues/1536

**Comment by tmorehouse** [comment]
I wonder if calling `vm.$forceUpdate()` on the checkbox after changing the disabled state would get around this issue? If it does, it would be a bit of a hack (as it would force the radio to re-render).  In carbon, it looks like they used a CSS hack to fix it.

**Comment by 4dn-oss** [comment]
Adding the CSS style `[disabled] ~ _ {}` introduced in the https://github.com/IBM/carbon-components/issues/1536 seems to solve this issue.

https://codepen.io/4dn-oss/pen/LqJGWQ

**Comment by 4dn-oss** [comment]
In my project, `[disabled] ~ _ {}` has deleted by webpack production build process. Dummy style such like  `[disabled]~_{font-size:inherit}` solved this probrem.
