### ISSUE TITLE
Validation classes for input-group and label

### ISSUE THREAD

**Issue by Daegaladh** [twbs/bootstrap#28244]
It would be very useful to add validation classes for `input-group` and `label`, since currently there's no easy way to select this class and label to apply styles to `label `or `input-group-prepend` like this:

![captura](https://user-images.githubusercontent.com/4557962/52651390-61d4b400-2eec-11e9-91e4-0f0611e54094.JPG)

**Comment by mdo** [comment]
There are old issues and PRs that address the capabilities here and their current status. Long story short, we use CSS only to style the inputs for validation states—we are limited by CSS's selectors and cannot target the `<label>` based on the `<input>` if it comes before the input.
