### ISSUE TITLE
custom-switch on the right side of the label

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#28242]
I would like the switch on the right side of the label.
Also have a spacing between them label and the switch so the label is on the left and the switch is on the right edge.

<img src="https://cdn-images-1.medium.com/max/1600/1*fdwLSREs3VTpiMvzNYf4Zw.png">

**Comment by Lausselloic** [comment]
Hello,
I had propose something like that : https://github.com/twbs/bootstrap/pull/28052
But maybe not the right way.
You could update the custom_forms.scss file to do that

If you find better way please share it :-)

**Comment by linuxonrails** [comment]
> Hello, I had propose something like that : #28052 But maybe not the right way. You could update the custom_forms.scss file to do that
> 
> If you find better way please share it :-)

https://github.com/twbs/bootstrap/pull/28052#issuecomment-947563918 ?
