### ISSUE TITLE
Ability to restrict JS behavior to specified scope/selector

### ISSUE THREAD

**Issue by DougPuchalski** [twbs/bootstrap#28246]
Request the ability to override the current `const Selector = ` in each of the JS submodules. Alternative: provide root selector that would override `document` or prefix all query selectors.

Use-case: large enterprise app is partially migrated from Bootstrap v2 to v4 and completion is a long-term effort. Goal is to allow v2 and v4 code to co-exist on the same page. I believe this can be accomplished by using querySelector within a scope rather than the entire document.

To me, it seems prudent to be able to restrict bootstrap behavior via a custom selectors for many reasons beyond this one.

I'll be happy to submit a PR if there is not opposition to the idea.

**Comment by mdo** [comment]
This is almost two years old, with no movement, so if there's still an interest in doing something to iterate on this in v5, please open a new issue or spiked out PR to stir the conversation :). Thanks!

**Comment by ffoodd** [comment]
FWIW I guess our `bs` namespace in v5 covers this.
