### ISSUE TITLE
Bootstrap 4 Modal (modal-backdrop) don´t close in Google chrome 72

### ISSUE THREAD

**Issue by eccck** [twbs/bootstrap#28250]
Modal in bootstrap 4.1.3 don´t close the  <div class="modal-backdrop fade show"></div>. Even on the official bootstrap site the demo don´t close on google chrome 72. So the screen stays greyed..

**Comment by XhmikosR** [comment]
Works fine here. We need more info.

**Comment by eccck** [comment]
I got the problem. Was an extension for google called Keyboard 
ID: aebnnochodigmgkihkmadggmbncnahen
I turned this off and modals works fine. Thanks a lot for the fast reply..
