### ISSUE TITLE
smooth scrolling issue when using jquery-3.3.1.slim.min.js

### ISSUE THREAD

**Issue by rajivverma343** [twbs/bootstrap#28257]
When i am using bootstrap 4.2 with below Jquery CDN then smooth scrolling doesn't happen

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

but when i use the below cdn then it's working

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

**Comment by XhmikosR** [comment]
That's unrelated to Bootstrap. Just use the full jQuery build if you need such features.
