### ISSUE TITLE
Animation collapse in firefox doesn't work

### ISSUE THREAD

**Issue by dolibarr95** [twbs/bootstrap#28258]
- windows server 2012 R2
- Firefox Quantum 65.0.1 (64 bits)
Works very well with Chrome 72.0.3626.109 (Build officiel) (64 bits)
- [official example](https://getbootstrap.com/docs/4.1/components/collapse/)

If I visit the official boostrap website (https://getbootstrap.com/docs/4.1/components/collapse/) with Firefox (components/collapse/) there is no animation when the element collapses (open and close without animation).
If I visite the same page with Chrome the elements collpases with an animation (as .toggle() jquery).

Tks for reading

**Comment by XhmikosR** [comment]
You are using a pretty old version as an example. Works fine here with the latest FF though.

**Comment by dolibarr95** [comment]
Tks for your answer :) 

Still have the same issue with the latest version :
https://getbootstrap.com/docs/4.3/components/collapse/

My firefox is the last version (65.0.1 / February 12, 2019)

**Comment by XhmikosR** [comment]
Maybe you have enabled a system setting to reduce animations or something?

**Comment by dolibarr95** [comment]
No, i've re-install Firefox to be sure but still the same issue :(
**Maybe because i'm in  windows server 2012 R2**

I've tested on my labtop win10 & firefox it's work perfectly

**Comment by XhmikosR** [comment]
The thing is that it's clearly something specific to your OS/setup.

**Comment by dolibarr95** [comment]
Yes!
Tks for your quick support!

**Comment by patrickhlauke** [comment]
i'll hazard a guess...per the documentation

> The animation effect of this component is dependent on the `prefers-reduced-motion` media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/4.3/getting-started/accessibility/#reduced-motion).

You probably have windows animations turned off. firefox is currently (but not for long, as chrome is shipping this soon as well) the only browser that takes that as a hint of `preferes-reduced-motion`

**Comment by dolibarr95** [comment]
PERFECT !!!!!
i've' tuned this option 


![screen](https://i.kinja-img.com/gawker-media/image/upload/1415739062675782285.jpg)
