### ISSUE TITLE
Changing the row's color on a value

### ISSUE THREAD

**Issue by Csyfer** [twbs/bootstrap#28254]
Is there anyway of changing the table row's color based on a cell value? this would be really helpful I cant seem to make it work no matter what i try.

**Comment by ralmidani** [comment]
I'm not aware of a way for CSS to read what is in your HTML. What are you using to generate your page? You could apply the classes conditionally with JavaScript, but I don't know if you're using JavaScript.

**Comment by XhmikosR** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/attr
