### ISSUE TITLE
[Question] When will the most recent patched versions be published on CDNJS?

### ISSUE THREAD

**Issue by mkArtakMSFT** [twbs/bootstrap#28269]
Our infrastructure is setup to consume the Bootstrap libraries from `CDNJS`. However it seems like the most recent patches aren't published in there yet. So I'm wondering whether `CDNJS` is going to get the patches soon or should we switch to `BootstrapCDN` now?

**Comment by mdo** [comment]
We only support and care about BootstrapCDN at the moment. I'd ask that you ping other CDN services if you need something else :).
