### ISSUE TITLE
Adding Breakpoint using Window Width v5

### ISSUE THREAD

**Issue by DevRush94** [twbs/bootstrap#28277]
Just a concept I was trying to implement
adding a class to the body according to the window width and then ` .bodyclass .my-class ` will boost the CSS without writing media query
Refer below link for the concept.

https://github.com/DevRush94/Rush/blob/master/Assests/JS/main.js

**Comment by MartijnCuppens** [comment]
We'll stick to the media queries because we want our code to work independent from js.

**Comment by DevRush94** [comment]
@MartijnCuppens fine, But just in case you can also add quick device base class for user breakpoint in a faster manner. which may help in user ease 
example
```
.custom-div{border:1px solid #000}
.xs .custom-div{border:0}
```

**Comment by patrickhlauke** [comment]
Yes, but nonetheless we'll pass on this approach. The modern way to handle this are media queries - if authors are creating their custom styles, it's not too much of an effort for them to also write out their custom stylings wrapped in appropriate `@media` blocks. I don't think having additional JavaScript in core Bootstrap is a good trade-off here.

**Comment by Johann-S** [comment]
I'm not sure if it'll interest you @DevRush94 but I made a little plugin: https://www.npmjs.com/package/bs-breakpoints

Which allow you to detect Bootstrap break points

**Comment by DevRush94** [comment]
> Yes, but nonetheless we'll pass on this approach. The modern way to handle this are media queries - if authors are creating their custom styles, it's not too much of an effort for them to also write out their custom stylings wrapped in appropriate `@media` blocks. I don't think having additional JavaScript in core Bootstrap is a good trade-off here.

I just read today that Bootstrap 5 will be independent of Jquery so just an idea to contribute.
But understood your approach too. I am still learning sorry if something went wrong.

**Comment by DevRush94** [comment]
> I'm not sure if it'll interest you @DevRush94 but I made a little plugin: https://www.npmjs.com/package/bs-breakpoints
> 
> Which allow you to detect Bootstrap break points

Even I was about to create a similar plugin just started a few days ago.
https://github.com/DevRush94/Rush

the whole concept was to get more breakpoint with ease to add custom CSS ASAP
And currently, the only drawback of using Bootstrap is not detecting 1366 to higher res like 1920.
1200+ is XL and for HD and HD ready device the breakpoints don't work which was extremely sad.
And Noob me xD thought of replacing 4.1 bootstraps with adding Javascript support to touch carousel and many more, But it seems bootstrap 4.2 add that xD.
