### ISSUE TITLE
Responsive Font Sizes via Bootstrap CDN

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#28281]
I like to use Bootstrap via the CDN - but I'd also like to use the new [Responsive Font Sizes](https://getbootstrap.com/docs/4.3/content/typography/#responsive-font-sizes).

Are there any plans to add a compiled/minified version to the CDN? Maybe something like:
`https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.rfs.min.css`

**Comment by kukac7** [comment]
it is a mixin, it doesn't work as a separate css.

**Comment by coliff** [comment]
[From the docs](https://getbootstrap.com/docs/4.3/content/typography/#responsive-font-sizes):
> RFS can be enabled by changing the $enable-responsive-font-sizes Sass variable to true and recompiling Bootstrap.

So you need to enable it and then compile it. The compiled CSS would be the same but with RFS enabled.

**Comment by XhmikosR** [comment]
The CDN just has what we offer here.

**Comment by mdo** [comment]
@MartijnCuppens Up to you if you want to modify our v4.x build process to output an RFS flavor. Please note though that this likely won't be needed in v5 since we discussed leaning towards enabling it by default there.

**Comment by coliff** [comment]
> The CDN just has what we offer here.
@XhmikosR Sorry it wasn't clear, I meant an additional `bootstrap.rfs.min.css` in the Download dist ZIP (as well as CDN).

**Comment by XhmikosR** [comment]
IMO, we shouldn't do anything for v4. We move forward with v5 where it'll be enabled by default.

**Comment by MartijnCuppens** [comment]
Lovely to hear you like RFS, @coliff!

It 'll be quite easy to generate a custom a version with RFS enabled but once we're going to generate custom versions of Bootstrap people will start asking for other configurations to be hosted via a CDN. We currently have the ability to configure Bootstrap to your needs with Sass and this should cover the need for customization.

`v4.3` is meant to be the "soft launch" of RFS where people can experiment with the font resizing if they want to without having them to wait until `v5`.
