### ISSUE TITLE
:checked and :disabled switch border color

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#28293]
That might be a personal preference, but I think border color of a checked+disabled custom switch should be lighter. From what I see only background-color is modified by `.custom-switch .custom-control-input:disabled:checked ~ .custom-control-label::before` rule.

**Comment by mdo** [comment]
I think for the time being these will stay as they are. They’ll be getting some refinements in v5 as we move to consolidate native and custom forms though.
