### ISSUE TITLE
Bootstrap 3.4.1 popover content not shown on Chrome

### ISSUE THREAD

**Issue by tbrcrl** [twbs/bootstrap#28290]
Hi,
Windows 10
Chrome 72
The popover content (div class="container-fluid") is not shown on Chrome when using Bootstrap 3.4.1. In the attached screenshot the same popover using Bootstrap 3.4.1 and Bootstrap 3.4.0 (do not care about style as I used different customization). As you can see, in version 3.4.1 the div with class "container-fluid" has a computed height of 0px.
I am sorry but I can't provide an accessible test case as the application is on an a company intranet.
Workaround: keep the 3.4.1 css folder and replace the js folder with 3.4.0 version
I suppose the issue is related to the tooltip and popover XSS sanitization updated in version 3.4.1
[https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/](https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/)
Thanks
![bootstrap-v3 4 0](https://user-images.githubusercontent.com/16580030/52902421-c6578200-3210-11e9-851e-2dc38a340f50.JPG)
![bootstrap-v3 4 1](https://user-images.githubusercontent.com/16580030/52902422-c6578200-3210-11e9-8525-888b42fb7b75.JPG)

.

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

BTW if it's related to our latest release, can you set `sanitize` at `false` for your dropdown and see if it fix your issue ?

**Comment by tbrcrl** [comment]
Hi thanks, for the quick answer.
I set `sanitize : false,` at row 1462 of bootstrap.js and this solved the issue.
Do you still need the live demo?

**Comment by robinwilson16** [comment]
This is also broken in Bootstrap 4.3.1 with exactly the same issue.
Popovers show no content.
Had to revert back to 4.3.0
Earlier versions are fine too.

**Comment by jokamax** [comment]
Broken in firefox 65.0.1 too (no content html loaded in popover).

**Comment by Johann-S** [comment]
@tbrcrl you shouldn't change that in Bootstrap source code, you can set that when you initialize your Popover, see:

```js
$('#yourPopover).popover({
  sanitizer: false,
})
```
For the other answers, since Bootstrap 4.3.1 and 3.4.1, Popovers and Tooltips sanitizer their options which contains HTML, so if you don't need that because your users cannot change the HTML of those options, you can set `sanitize` at false.

You'll find more informations here:
https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer

And in the related plugins pages.

**Comment by robinwilson16** [comment]
As this has been closed does it mean the bug has been addressed and popovers work again?
4.3.1 still seems to be the latest version.
Or do we need to wait for 4.3.2/3.4.2?

**Comment by Johann-S** [comment]
@robinwilson16  There is no fix for that issue, it's related to how you use Bootstrap.

>For the other answers, since Bootstrap 4.3.1 and 3.4.1, Popovers and Tooltips sanitize their options which contains HTML, so if you don't need that because your users cannot change the HTML of those options, you can set `sanitize` at false.

**Comment by robinwilson16** [comment]
@Johann-S Thanks I see. Sorry I didn't realise this was a new requirement - I thought it was just to help track the issue down.
So basically if we need HTML inside the popover we must set sanitize to false otherwise it should be left as default, which is true.
Thanks will amend my .js files and switch back to the newer version in my next commit.

**Comment by inad9300** [comment]
Please, refer to this issue as a breaking change in the [release notes of 3.4.1](https://github.com/twbs/bootstrap/releases/tag/v3.4.1) and mention explicitly the `sanitize` flag. I wasted a long time wondering why a couple of very simple buttons were not displayed! Suspecting that a +0.0.1 increase on one of your dependencies has such a breaking change is not the first thing that comes to mind.

**Comment by robinwilson16** [comment]
This has broken again now between Bootstrap Bundle 4.3.0 and 4.3.1
Please can you tell me what has changed now as I already have sanitize in the code.

This is 4.3.0 (how it should work):
![Bootstrap 4 3 0](https://user-images.githubusercontent.com/9021962/60457766-bb881180-9c34-11e9-9e4c-d2e44d712fea.png)

This is 4.3.1 (showing it not working):
![Bootstrap 4 3 1](https://user-images.githubusercontent.com/9021962/60457786-c93d9700-9c34-11e9-9ac2-f4c2e7c6b422.png)

Content is:
```
$(elem).popover({
            trigger: 'manual',
            html: true,
            sanitizer: false,
            title: function () {
                return "Filter and Sort <span class=\"close\">&times;</span>";
            },
            content: function () {
                return $("#FilterPanel").html();
            }
        }).popover('show');
```

It seems to not mind simple HTML but anything including form tags seems to be blocked.
I have switched back to 4.3.0 for now until this can be fixed.

**Comment by Basirk** [comment]
In the Bootstrap documentation for tooltips and popovers, the sanitize option should be mentioned in the html option description. It should specifically highlight that some HTML will not be rendered unless sanitize options are changed.

**Comment by dayanrr91** [comment]
> @tbrcrl you shouldn't change that in Bootstrap source code, you can set that when you initialize your Popover, see:
> 
> ```js
> $('#yourPopover').popover({
>   sanitize: false,
> })
> ```
> 
> For the other feedbacks, since Bootstrap 4.3.1 and 3.4.1, Popovers and Tooltips sanitize their options which contains HTML, so if you don't need that because your users cannot change the HTML of those options, you can set `sanitize` at false.
> 
> You'll find more informations here:
> https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
> https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer
> 
> And in the related plugins pages.

dude, you fuc****saved me, I've been stocked with this for the past two hours. Thanks.

**Comment by Commifreak** [comment]
Just came accros this issue. I wonder, why I cant turn off sanitizing by adding a data-attribute.

`data-html="true"` is accepted, but `data-sanitize="false"` does nothing. Is this wanted behavior?
