### ISSUE TITLE
Look if we need to add a fallback for `word-break`

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#28304]
Currently we are using `word-break: break-word;` in various places like `code`.

This isn't a standard property, at least not yet.

See if we need to provide a fallback.

/CC @mdo @MartijnCuppens

**Comment by bardiharborow** [comment]
See #28381 for a possible solution.

**Comment by XhmikosR** [comment]
It's not a browser bug... this isn't a standard yet.

**Comment by bardiharborow** [comment]
Browser support, is I guess what I meant. I don't know if we should have a label for that or not, but that's another issue.

**Comment by XhmikosR** [comment]
We don't, thus how I actually noticed the issue. Using vnu.jar's web interface, which can also lint CSS, I saw the `break-word` errors and then looked into it.

IMO we shouldn't use non-standard properties when possible, and when we do we need to make sure we have fallbacks.

Because something works in Chorme/Chromium, certainly doesn't mean is standard, and we shouldn't endorse this.

**Comment by XhmikosR** [comment]
/CC @twbs/css-review, not sure if this is still applicable.
