### ISSUE TITLE
Sticky based on viewport

### ISSUE THREAD

**Issue by boutzamat** [twbs/bootstrap#28311]
Would be lovely with the possibility to add the "sticky-top" class based on viewport.
Like for an example: sticky-top, sticky-sm-top, sticky-md-top, sticky-lg-top sticky-xl-top, and same for sticky-bottom.

Couldn't find this as a feature request, so here it is.

The good thing is, it wouldn't break any existing sites :)

**Comment by jahanzaibsuleman07** [comment]
Hello,
I have created PR at https://github.com/twbs/bootstrap/pull/28352 to make `sticky-top` responsive. Please review. Thanks!
