### ISSUE TITLE
Custom 404 Page for Docs

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#28319]
Currently the 404 page is the default GitHub Pages one. It'd be nice to have a custom Bootstrap branded one with links in header and footer so any folks reaching the page can quickly get to where they want to go on the site. Jekyll has support for this: https://jekyllrb.com/tutorials/custom-404-page/

**Comment by coliff** [comment]
Cool - I'm working on this now. I've got the `404.md` in the content dir.

When you make a build though the 404 page gets added to the sitemap. A while ago you posted a helpful solution to this issue on the Hugo GitHub issues (https://github.com/gohugoio/hugo/issues/653#issuecomment-306246149) shall I modify the `sitemap.xml` in this same PR so we can use `private: true` in the front-matter?

**Comment by XhmikosR** [comment]
You can add `sitemap_exclude: true` in 404.md front matter and should work.

**Comment by coliff** [comment]
we'd also need to edit the `sitemap.xml` too though otherwise it gets included.
REF: https://github.com/gohugoio/hugo/issues/653#issuecomment-423154439

**Comment by XhmikosR** [comment]
The sitemap.xml I have in the branch already has this functionality :)

**Comment by coliff** [comment]
I got it to work (exclude from sitemap) by changing:
`{{- range .Data.Pages -}}{{ if ne .Site.Params.sitemap_exclude true }}`
to:
`{{- range .Data.Pages -}}{{ if ne .Params.sitemap_exclude true }}`
in the `sitemap.xml`

**Comment by XhmikosR** [comment]
Ah yeah that's a typo in the search and replace. Let me rebase the branch.

**Comment by XhmikosR** [comment]
No, actually it works fine here.

**Comment by XhmikosR** [comment]
Please use the hugo branch. It works fine there.

**Comment by coliff** [comment]
I'm using `v4-dv-xmr-hugo` branch with Hugo v54 extended on Windows. When I run `hugo` the generated sitemap.xml includes the 404 page... but in any case I'll ignore that for now and just commit the 404 page if this is ok.

![image](https://user-images.githubusercontent.com/1212885/53151388-743ea400-35f6-11e9-88ca-34504dd1f4fe.png)

**Comment by XhmikosR** [comment]
Just make a PR and I'll have a look there.
