### ISSUE TITLE
Floating labels - IE Edge support?

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#28313]
Are you going to fix floating labes for IE EDGE? Because still it doesn't work on this browser.

Maybe you change :placeholder-shown for something else which works on IE too?

**Comment by patrickhlauke** [comment]
as they're only experiments, not part of core bootstrap, and a solution for IE/Edge would require additional JS, going to close this for now. no immediate plans to write up custom scripting for this at this point.
