### ISSUE TITLE
Right-aligned dropdown menu is broken in documentation demo

### ISSUE THREAD

**Issue by loucadufault** [twbs/bootstrap#28327]
Edit: my mistake, see below.

It still shows as left-aligned, despite ".dropdown-menu-right" being added to the dropdown-menu div.
At [this documentation section](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment)

macOS, Google Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by Lausselloic** [comment]
Same on latest 4.3 version but you could achive same result by replacing `.dropdown-menu-right` by the utilities `.text-right`

**Comment by patrickhlauke** [comment]
the menu itself is right-aligned. note that this refers to the dropdown menu itself, not the trigger/button.

![left aligned menu](https://user-images.githubusercontent.com/895831/53098159-f8235e00-351a-11e9-8098-141777bff722.PNG)

![right aligned menu](https://user-images.githubusercontent.com/895831/53098182-01142f80-351b-11e9-8ac9-3cadd86a2070.PNG)

**Comment by patrickhlauke** [comment]
unless i'm missing something, or it behaves differently on macOS/Chrome?

**Comment by loucadufault** [comment]
Nope, I just realized my mistake but looks like I was too late to close it.
Sorry about that! Feel free to close.

(I initially thought it was referring to the text within the menu, not the menu itself relative to parent button)

**Comment by patrickhlauke** [comment]
pas de probleme...just wanted to make sure i wasn't missing something :)
