### ISSUE TITLE
Sanitizer does not accept <dl>/<dd>/<dt> for popovers [3.4.1]

### ISSUE THREAD

**Issue by sunflower-seed** [twbs/bootstrap#28325]
Using version 3.4.1, upgraded from 3.3.7

We are using `<dl class="dl-horizontal">, <dt>, <dd>` in the `content: function()` for a custom popover.

The new sanitizer does not accept `<dl>` but `<ul>`
Is there a reason?

I know there is a reason to extend the whitelist.
Are you planning to add the html elements mentioned above?

p.s: Your link to https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md is outdated (404) ;-)

**Comment by Johann-S** [comment]
Personally I don't plan to add those tags, but you can easily do that according to our docs see: https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer

solution:
```js
$.fn.tooltip.Constructor.DEFAULTS.whiteList['dl'] = [];
$.fn.tooltip.Constructor.DEFAULTS.whiteList['dt'] = [];
$.fn.tooltip.Constructor.DEFAULTS.whiteList['dd'] = [];
```

/CC @XhmikosR

**Comment by XhmikosR** [comment]
Yeah, agreed. We already give the ability for this to be customized as needed.

**Comment by sunflower-seed** [comment]
Thanks for information!
