### ISSUE TITLE
How about add a tree component？

### ISSUE THREAD

**Issue by db1995** [twbs/bootstrap#28320]
![image](https://user-images.githubusercontent.com/34293412/53069427-f6579b80-3516-11e9-9d66-0c0e12908a01.png)
Like this.

**Comment by mdo** [comment]
Not something we'll be building into Bootstrap anytime soon. You can get there with our collapse and accordion functionality, and I imagine others have built this as a plugin/extension.

**Comment by db1995** [comment]
> Not something we'll be building into Bootstrap anytime soon. You can get there with our collapse and accordion functionality, and I imagine others have built this as a plugin/extension.

Thank you. I will try to achieve it.
