### ISSUE TITLE
Add a "white-space: pre-line" text class

### ISSUE THREAD

**Issue by d012345** [twbs/bootstrap#28324]
Just like the .text-wrap and .text-nowrap classes that sets white-space to "normal" and "nowrap", there could also be a text class as mentioned in the title?

**Comment by mdo** [comment]
Utilities are for frequently repeated property-value pairs—I don't think this is as utilized as the others. Closing as a won't fix for now.

**Comment by ThomasLandauer** [comment]
This would be handy to mimic PHP's [`nl2br()`](https://www.php.net/manual/function.nl2br.php) function.

**Comment by shadinamrouti** [comment]
It's bad that Bootstrap 4 cannot satisfy its users. One person is controlling everything instead of the community.

**Comment by HakamFostok** [comment]
@mdo I think this is really on demand, consult the following SO question if you want

https://stackoverflow.com/a/48680684

**Comment by paulsmithkc** [comment]
<pre> changes the font to monospace and introduces another tag.

**Comment by jukka-maljanen-solteq** [comment]
I guess I need to make that css class my self.

**Comment by paulsmithkc** [comment]
@HakamFostok Yeah, I've found this useful any time I have users entering multi-line text through a text area.

**Comment by LuisValgoi** [comment]
That is why nobody uses this 💩 anymore 😆

**Comment by tobiasnitsche** [comment]
Whats your definition for frequently used @mdo ?

For me its pretty useful and would use it frequently. Others too with pretty good reasons. The rejection is a bit harsh.

![Image](https://github.com/user-attachments/assets/59d46e04-9d02-45c0-92ca-737ec0309984)

**Comment by tobiasnitsche** [comment]
I would create a proper merge request on this, but with an expectation of rejection i would not do it.

**Comment by dani832m** [comment]
Needed this class in several situations, and I agree that it would be extremely useful.
