### ISSUE TITLE
Adding the possibility to orientate the shadow

### ISSUE THREAD

**Issue by alexandreDavid** [twbs/bootstrap#28326]
In some case, I need to orientate the shadow of my div to another direction than the bottom.
Example, for a sidebar component which comes from the edge of the page.
If you are okay, I can create a PR.
Second thing, (not really useful) I can add the notion of color on the shadows.

**Comment by mdo** [comment]
Nearly all of our `box-shadow` properties are controlled via Sass variables that can easily be modified. No plans to change how these work in the future.

**Comment by alexandreDavid** [comment]
Maybe I wasn't very clear but my intention was to add, in the utility file, new classes like shadow-left, shadow-right and also shadow-sm-left, etc.

**Comment by alexandreDavid** [comment]
@mdo 
For my case I use a shadow for my sidebar 
![left-shadow](https://user-images.githubusercontent.com/3982980/53157200-e6909380-35b8-11e9-988c-34f3e0b44e0d.PNG)

and for my bottom navigation in mobile view.
![top-shadow](https://user-images.githubusercontent.com/3982980/53157187-ded0ef00-35b8-11e9-9d39-bcf6edc3a16d.PNG)
