### ISSUE TITLE
More import customization (or split) on scss level

### ISSUE THREAD

**Issue by pavelloz** [twbs/bootstrap#28333]
Hello,

Im trying to keep my bundles size down so i always create custom-bootstrap.scss and comment out what i dont need.

Then i extract whats critical to critical.css and inline it to make the page fast.

Now, when i sometimes see how many KBs some files add i just give up and reimplement them on my own.

The best example is utilities/spacing - https://github.com/twbs/bootstrap/blob/master/scss/utilities/_spacing.scss

This thing generates so many classes, for every combination of breakpoints and numbers, it blows up to around 20KB with prefixes.

My proposition is to either:
* allow some kind of granular setting/config for particular partials to skip some groups (maybe choose sizes, maybe choose breakpoints)
* split it further down - margin, padding + add opt-out option from some of them

Im sure there are other files that would benefit greatly, and "unused css" metric in devtools gives good idea of what and why most devs would out-out from. I know framework idea is to have everything needed and thats hard to cater for everyone, but since scss has selective import and you already noticed the problem by suggesting custom-bootstrap.scss, you are well aware that minimizing bundle is pretty important and its entirely possisble to achieve very light webpages using bootstrap.

**Comment by mdo** [comment]
We're discussing something like this in #28367. Closing this out though as there won't be any other changes until that lands (in v5).
