### ISSUE TITLE
print issue

### ISSUE THREAD

**Issue by sebalaini** [twbs/bootstrap#28334]
I'm trying to print a long div inside a modal but for some reason I don't have a second page in IE11.

I created a question in Stackoverflow.

https://stackoverflow.com/questions/54825421/css-print-long-div-inside-modal-no-second-page-in-ie

I think is Bootstrap related as I created a minimum project where I can have the second page in all browsers but when I attach bootstrap css to the html it stop to work

I can create a repo in github and share it so you can see that it happens just when I have bootstrap

**Comment by sebalaini** [comment]
little update, I've applied `display table` to the main div that contain the 2 page and now I can print in IE now but not in FF.

**Comment by MartijnCuppens** [comment]
There are a lot of print issues, but sadly enough browsers just behave too inconsistent to provide a solution for all scenarios with. We're probably going to remove a lot of the default print styles (if not all) we now provide in Bootstrap for the next major version.
