### ISSUE TITLE
"rem" and "em" used in your CSS codes

### ISSUE THREAD

**Issue by qwerbycom** [twbs/bootstrap#28346]
So looking at your CSS code: example bootstrap.css, you have "rem" and "em" mixed in together. Shouldn't you just use just one such as only use "rem"? Makes it more convuluted the way it is now.

Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by patrickhlauke** [comment]
no, `rem` always refers to the base size for of the root of the document, while `em` is relative to whatever the parent size is. so both have their uses, in different contexts.
