### ISSUE TITLE
Collapse multiple targets fails to toggle both elements

### ISSUE THREAD

**Issue by djibe** [twbs/bootstrap#28344]
Hi,
using latest Chrome 72 and BS 4.3.1 doc for the Collapse : https://getbootstrap.com/docs/4.3/components/collapse/, I experience some pb with the button Toggle both elements.

If you toggle/untoggle 1 of the elements, you cannot anymore toggle both elements simultaneously (both opened or closed after clicking button : Toggle both elements).

Is it an expected behaviour or a bug ?
Thx a lot.

**Comment by Johann-S** [comment]
I agree it's a weird behavior, but I don't thinks it's a real use case.

What I mean it's, in a real app, you have to choose one way, you toggle multiple elements or just one for the targets.
I don't see a real use case here 🤔 

/CC @twbs/js-review if you have something in mind

**Comment by XhmikosR** [comment]
Why does it happen though? IMO this shouldn't happen, but I haven't dug into it to see where it fails.

**Comment by mdo** [comment]
Revisiting this, I don't see a bug here. If you toggle the first, then click the toggle both, you're toggling both collapses independent of their states. We _could_ change this in our docs, but honestly, I like that it shows that this behavior is possible. Closing as a won't fix.
