### ISSUE TITLE
Horizontal checkbox issue

### ISSUE THREAD

**Issue by geogan** [twbs/bootstrap#28359]
Vertical alignment of checkboxes with labels has gone wrong (way too much vertical space)

I did a bit of research and it appears to be caused by this line in bootstrap.css v3.4.0

```
.form-horizontal .radio, .form-horizontal .checkbox {
	min-height: 9rem;
}
```

In previous bootstrap v3.3.7 it was this:

```
.form-horizontal .radio, .form-horizontal .checkbox {
	min-height: 27px;
}

```
I'm not sure but I think this bug is only in the latest [3.4.0 customizer download](https://getbootstrap.com/docs/3.4/customize/) which is what I used to generate the bootstrap CSS.

This is the code affected:

```
<div id="persistent_p.row" class="form-group">
  <div class="col-sm-9 checkbox">
    <label for="login:elements:persistent_p:t">
       <input type="checkbox" name="persistent_p" value="t" id="login:elements:persistent_p:t" checked="checked" class="checkbox"> 
       Remember my login on this computer
    </label>
  </div>
</div>
```

Now the checkbox for the label is way below the actual text "Remember my login on this computer". It used to be vertically aligned correctly.

I would presume the correct value should be 2.7rem now to match previous bootstrap?

**Comment by geogan** [comment]
I'm not sure but the vertical alignment of checkboxes has just gone strange (way too much vertical space) and I did a bit of research and it appears to be caused by this line in bootstrap.css v3.4.0

.form-horizontal .radio, .form-horizontal .checkbox {
	min-height: 9rem;
}

In previous bootstrap v3.3.7 it was this:

.form-horizontal .radio, .form-horizontal .checkbox {
	min-height: 27px;
}

I'm not sure but I think this bug is only in the latest 3.4.0 customizer download which is what I used to generate the bootstrap CSS.

**Comment by XhmikosR** [comment]
We need more info like a Codepen and customizer's JSON file. Also, note 3.4.0 is NOT the latest 3.x version.

**Comment by XhmikosR** [comment]
Also, there's no `rem` in the dist CSS from customizer nor our builds so it's something on your side. Perhaps, you changed some variables in the customizer config to include `rem` values.

**Comment by geogan** [comment]
It appears that using the default values for customizer and just changing the "font-size-base" from 14px to 1.4rem (which I did so the site scales better), causes this. 

When I export this and look at the produced bootstrap.css, I get the "min-height: 9rem;"

This used to work so maybe something changed recently with customizer. Clients only noticed checkbox misalignment in last month or so.

Anyway, I just put in CSS in a custom client file to set it back to 2.7rem instead of 9rem.

**Comment by XhmikosR** [comment]
No idea what you can use there, but it's your job if you change the default values to handle any issues.
