### ISSUE TITLE
nav-tabs loose .active state on scrollspy

### ISSUE THREAD

**Issue by burdyga** [twbs/bootstrap#28356]
If I use scrollspy on body and nav-tabs in same place my first nav tab loose active state on start scrolling.

– Mac OS X 10.14.3
– Opera 58.0.3135.68
– https://codepen.io/brv/pen/PLowRy

**Comment by angelaCTO** [comment]
Encountering the same issue, but noticed issue running on Opera as well as Firefox

**Comment by mdo** [comment]
Ideally is resolved by our recent scrollspy revamp for v5 in #33421.
