### ISSUE TITLE
Stop Allowing Google to use its "Backdoor" script loader

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#28351]
I use [Dan Pollock's hosts file](https://someonewhocares.org/hosts/) to block Google Analytics but they found a way around it. I've seen this on the Telegram website and now I'm seeing it on Bootstrap while helping with the Hugo dev:

https://www.reddit.com/r/privacy/comments/8clrzn/google_your_backdoor_to_the_internet/

The way this works is Google uses a backdoor script loader as explained above—it's base64 encoded—the specific script Bootstrap tried to load on my machine while working doing development was this one here: https://www.google.com/js/bg/4mrRnEPnWo81qWPG8_xcGP85HCscbg1O2YUrIewxQYY.js

This script loader relies on the fact many may have explicitly blocked google analytics and it uses the technique to get around the block in a most uncouth way. If you'd like a HAR file showing the requests I will reproduce this for you—if you can commit to an investigation and fix for this cross-domain JS script loader.

**Comment by Johann-S** [comment]
Hi @jhabdas,

I read what you linked to us, but I can't figure how it's related to Bootstrap source code 🤔

**Comment by patrickhlauke** [comment]
i'll take a stab in the dark and say this relates to getbootstrap.com's analytics snippet? (which you'd also get when viewing offline/locally built site/documentation when developing)

**Comment by jhabdas** [comment]
@patrickhlauke yep. it defeated my hosts file. i have more info on it which I can dig up but I haven't seen it in about 6 months (not a GA user personally—don't have a google account). again, if you need more research I can dig it up but the basics should be in the reddit link above.

**Comment by jhabdas** [comment]
Overall I feel this can be mitigated with a tracking opt-out, which probably should've been added last may along with a so called "cookie disclaimer".

Ref: https://github.com/freeCodeCamp/devdocs/issues/971 https://github.com/badges/shields/issues/3026

**Comment by bardiharborow** [comment]
We should disable GA for local docs, consider GDPR implications, and see what can be done to make GA well-behaved. Ideally we'd remove it in favour of server/CDN-side analytics but that's probably more mdo's call.

**Comment by Lausselloic** [comment]
or put a cookie-consent manager like https://github.com/AmauriC/tarteaucitron.js ?

**Comment by XhmikosR** [comment]
A cookie consent is doable although TBH they annoy me a lot.

@mdo: what do you prefer: opt-in or opt-out tracking?

**Comment by bardiharborow** [comment]
@jhabdas, I know you've deleted your account, but perhaps you'll see this. Blocking `www.google-analytics.com` by any means will disable GA tracking. I'm not sure what the Reddit thing is all about, but we load a JavaScript file from `www.google-analytics.com` and if this doesn't load then GA will never have a chance to boot up. Dan's host file includes a commented our rule for this, which I assume you have enabled. That should work.

@XhmikosR I also share a mutual disdain for cookie consent. While I understand there may be EU law implications, from a purely technical perspective and given the current state of the internet, the best option was have going forward is honoring Do Not Track. We should consider disabling GA on this switch:
```js
navigator.doNotTrack === "1" || navigator.doNotTrack === "yes" || window.doNotTrack == "1" || navigator.msDoNotTrack == "1"
```

**Comment by XhmikosR** [comment]
Yeah, I personally don't care about local. But maybe we should do something so that we are GDPR compliant. IIRC we just ignored it until now.

**Comment by coliff** [comment]
There a number of 'built-in' privacy features in Hugo we could take advantage of. I often add the following to my Hugo sites `config.yml`:

```
privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
```
The Google Analytics one will use session storage instead of cookies, won't track the last octet of the user's IP address and respect do not track.

You can read more about the options here: https://gohugo.io/about/hugo-and-gdpr/

**Comment by XhmikosR** [comment]
Yeah, I'm aware of those, but when I made the branch I didn't want to expand to further additions apart from the Hugo switch. That being said, I don't like the internal Hugo templates for these features due to the bad whitespace they output.

So, I don't want to switch to those until I have the time and make upstream patches.

**Comment by coliff** [comment]
gotcha. I could make a PR against master (for v4/jekyll) if you like with the analytics.html being this:
```
{% if jekyll.environment == 'production' %}
<script>
var dnt = (navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack);
var doNotTrack = (dnt == "1" || dnt == "yes");
if (!doNotTrack) {
  window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
  if (window.sessionStorage) {
    var GA_SESSION_STORAGE_KEY = 'ga:clientId';
    ga('create', 'UA-146052-10', 'getbootstrap.com', {
      'storage': 'none',
      'clientId': sessionStorage.getItem(GA_SESSION_STORAGE_KEY)
     });
     ga(function(tracker) {
      sessionStorage.setItem(GA_SESSION_STORAGE_KEY, tracker.get('clientId'));
     });
   }
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');
}
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>
{% endif %}
```
This includes the privacy improvements, as well as not running the code during local build and then this the same code can be easily moved to Hugo when needed.

**Comment by XhmikosR** [comment]
You can make this if you want, but it might be moot being that I haven't discussed it with the others.

Let alone that it'll go away when we switch to Hugo, which will probably be very soon, and I doubt I'll have made upstream patches.

But I guess it doesn't hurt to have the PR.

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/28489#issuecomment-472675719.

**Comment by mdo** [comment]
(If we need to revisit anything else here, please holler in our Slack or team repo)
