### ISSUE TITLE
onbeforeunload does not work on iphone

### ISSUE THREAD

**Issue by zskiredj** [twbs/bootstrap#28364]
- OS : Ios (Iphone)
- Browser : chrome last version

I have a page with this body :

```
<body>
    <div class="loading">
            <div class="loader"></div>
    </div>
    <div class="site-content">
 [... all the content]
</div>
</body>
```
I am using this code to show / hide a spinner

```
function unLoader(e) {
    $(".site-content").hide();
    $(".loading").show();    
    }
   
   $(window).on('load', function() {
         $(".loading").hide();
         $(".site-content").show();
          window.onbeforeunload = unLoader;
     });
```

The problem is that the spinner works in desktop both PC and mac, on safari, firefox, chrome etc...

But it does not work on my Iphone.

On the other side, i am using the spinner for calls in ajax :

```
var $loading = $('.loading').hide();
$(document)
    .ajaxStart(function () {
        $loading.show();
    })
    .ajaxStop(function () {
        $loading.hide();
    });
```

But this time the spinner works in mobile device (iphone) !

How can I make the spinner work for the mobile devices in all my pages (using the code shown first) ?

I know the problem is from `onbeforeunload `event

Thanks in advance.

**Comment by XhmikosR** [comment]
Unfortunately this is outside of Bootstrap. Try asking on StackOverflow.

**Comment by zskiredj** [comment]
I have already asked the question and no answer ...

**Comment by XhmikosR** [comment]
But you say it yourself, it happens with `onbeforeunload`.

Otherwise, provide a Codepen for us to test.
