### ISSUE TITLE
Failed Compilation of Bootstrap 4.3.1 &} {

### ISSUE THREAD

**Issue by wilecoyte78** [twbs/bootstrap#28363]
On my compiler I was getting this error:

<b>Warning</b>:  Scss Compliation of file: '/css/bootstrap.scss' failed:parse error: failed at `&} {` scss/mixins/_badge.scss on line 5

    @mixin badge-variant($bg) {
      color: color-yiq($bg);
      background-color: $bg;

      @at-root a#{&} {
        @include hover-focus {
          color: color-yiq($bg);
          background-color: darken($bg, 10%);
        }

        &:focus,
        &.focus {
         outline: 0;
         box-shadow: 0 0 0 $badge-focus-width rgba($bg, .5);
        }
      }
    }

I changed it to

    @mixin badge-variant($bg) {
	color: color-yiq($bg);
	background-color: $bg;
  
	&[href] {
		@include hover-focus {
			color: color-yiq($bg);
			background-color: darken($bg, 10%);
		}
	}
  
	&:focus,
        &.focus {
		outline: 0;
		box-shadow: 0 0 0 $badge-focus-width rgba($bg, .5);
        }
    }

and in _badge.scss in the root folder
Change:

    .badge {
      display: inline-block;
      padding: $badge-padding-y $badge-padding-x;
      @include font-size($badge-font-size);
      font-weight: $badge-font-weight;
      line-height: 1;
      text-align: center;
      white-space: nowrap;
      vertical-align: baseline;
      @include border-radius($badge-border-radius);
      @include transition($badge-transition);

      @at-root a#{&} {
        @include hover-focus {
          text-decoration: none;
        }
      }

      // Empty badges collapse automatically
      &:empty {
        display: none;
      }
    }

TO:

    .badge {
      display: inline-block;
      padding: $badge-padding-y $badge-padding-x;
      @include font-size($badge-font-size);
      font-weight: $badge-font-weight;
      line-height: 1;
      text-align: center;
      white-space: nowrap;
      vertical-align: baseline;
      @include border-radius($badge-border-radius);
      @include transition($badge-transition);

      &[href] {
        @include hover-focus {
          text-decoration: none;
        }
      }
      // Empty badges collapse automatically
      &:empty {
        display: none;
      }
    }

and no longer got the error.

I was wondering could the team use my fix for later releases?

**Comment by XhmikosR** [comment]
You could use what we use which is node-sass. You don't mention the name or the version of your compiler, so I'm gonna assume it's not node-sass.

**Comment by wilecoyte78** [comment]
Ok thank you
