### ISSUE TITLE
Collapse not working with numeric id

### ISSUE THREAD

**Issue by handre** [twbs/bootstrap#28369]
I'm using Bootstrap 4.13 and "Collapse" is not working when the id of the collapsible element is numeric.

https://codepen.io/handre/pen/jJEjgZ

This is easy to overcome in my project, but I think it worth mention since I lost some time to debug.
Thanks for this awsome tool!

**Comment by Johann-S** [comment]
Indeed that's the normal behavior because numeric id isn't a valid id, you can read more about that here:

- https://getbootstrap.com/docs/4.3/getting-started/javascript/#selectors
- https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier
