### ISSUE TITLE
Any chance we can see CSS Grid Layout now that @supports exists!

### ISSUE THREAD

**Issue by guledali** [twbs/bootstrap#28385]
I know it was a discussion before but I will bring this up again, any chance that the grid system in bootstrap could be rewritten using CSS Grid  and for the older browser fallback to flexbox/float based grid if necessary. 

This shouldn't be hard to do anymore thanks to https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

**Comment by wolfy1339** [comment]
I think this is planned for v5. (If you look at the repo project boards)

**Comment by SuperPat45** [comment]
Prototype shared in https://github.com/twbs/bootstrap/issues/24887#issuecomment-347215557

**Comment by MartijnCuppens** [comment]
`@support` wil cause browsers to behave different, that's exactly what we want to avoid.
