### ISSUE TITLE
HTTP:// link for svg icons

### ISSUE THREAD

**Issue by MattCCC** [twbs/bootstrap#28383]
Hello,

firstly thank you for a great front-end framework. You're making a great job guys! Recently I came across an issue with svg links that are http instead of https, there is:
http://www.w3.org/2000/svg

should be: https://www.w3.org/2000/svg

Currently Firefox may encounter issues with displaying a green lock next to links, if BS4 is inlined.

Thank you.

Regards,

**Comment by bardiharborow** [comment]
XML namespaces are not network resources to be loaded, but rather unique identifiers to specify a protocol. See [this StackOverflow question](https://stackoverflow.com/questions/22976359/xml-namespace-a-security-issue) for why they shouldn't be changed to HTTPS.

> Currently Firefox may encounter issues with displaying a green lock next to links, if BS4 is inlined.

You will have to be more specific here. XML namespaces don't cause mixed-content warnings.
