### ISSUE TITLE
Missing jQuery detection not working

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#28387]
If you fail to load jQuery you'll get `TypeError: $ is undefined`, or `TypeError: g is undefined` if you load the minified version.

**Comment by Johann-S** [comment]
Fix here: https://github.com/twbs/bootstrap/commit/0524944b584caf988888c64b9a531955ca8e2cee
But we'll have to do a proper v4 branch to merge that

/CC @XhmikosR

**Comment by XhmikosR** [comment]
Yeah, on it. I will create a new branch and start cherry picking stuff, and we'll force push it to the current v4-dev.

**Comment by XhmikosR** [comment]
Closing this since it's in the v4-dev-new branch, which well be pushed to v4-dev when I can force push it.
