### ISSUE TITLE
Custom Range track variable overwrites not working

### ISSUE THREAD

**Issue by wadclapp** [twbs/bootstrap#28398]
```css
$custom-range-track-width:          100% !default;
$custom-range-track-height:         0;
$custom-range-track-cursor:         pointer !default;
$custom-range-track-bg:             $gray-200;
$custom-range-track-border-radius:  1rem !default;
$custom-range-track-box-shadow:     none;
```

changing height, background variables etc since recent update are no longer taking effect on the custom range input's track?

also changing `$custom-range-track-cursor` appears to change the custom range thumb's cursor (but not the track), I don't know if that's normal behaviour or not though.

**Comment by wolfy1339** [comment]
Are you setting default on your variables? Or is that just a snippet from Bootstrap

**Comment by wadclapp** [comment]
that's a snippet from my custom variables file which I use to overwrite bootstrap variables, I remove `!default` when I want to overwrite. Was working before updating to Bootstrap to a recent version (and the original Bootstrap variables in src folder haven't changed name), and all other variable overwrites appear still to be working.

**Comment by mdo** [comment]
Closing this out as stale. Only thing I can see as a potential problem is that you cannot have a `0`-height element I believe. There's nothing special about these variables compared to the rest of the entire project.
