### ISSUE TITLE
Consider drop REM units, switch back to PX and automate converting to REM by postcss

### ISSUE THREAD

**Issue by VitalijPetras** [twbs/bootstrap#28396]
I really love bootstrap, but i really hate _incompatible units rem/px_ in same time.

What is the benefit of using REM units in Bootstrap variables? Why we just can't write all in pixels and then use tools like [postcss-pxtorem](https://github.com/cuth/postcss-pxtorem)? 

Reasons to consider switching back to px:
1. faster development and debugging
2. bootstrap uses rem units only somewhere, but what is the benefit of this if this can be everywhere full automated
3. easier development for bootstrap developers when you skip thinking about "what unit should we use: px, em, or rem"
4. ceeps code simple and readable

I use postcss-pxtorem in all my projects and its awesome. I write all css in px and in production code i add postcss-pxtorem plugin to convert all css to REM units. It's so simple without needless headache.

Why dont you write your code with -prefixes- and recommend to use autoprefixer instead? So why to not do same think with rem units? It's live saver for me, and for all i think.

What do you think about it? :-)

**Comment by patrickhlauke** [comment]
> What is the benefit of using REM units in Bootstrap variables?

Because `em` and `rem` adapt to situations where the browser has a different base font size set (either because the users themselves set it, or because it's on a particular device where the manufacturer decided that a different base size is more appropriate).

> Why we just can't write all in pixels and then use tools like postcss-pxtorem?

Because that completely negates the above advantage, and just naively assumes that `1rem` = `16px`.

**Comment by VitalijPetras** [comment]
> Because that completely negates the above advantage, and just naively assumes that 1rem = 16px.

**This is not true.** What about `rootValue: 16` property in postcss plugin? All advantages you mentioned can be automated with this postcss plugin..

So i dont know why you closed the issue. Its still not answered for me.

**Comment by patrickhlauke** [comment]
ok, having looked at the specific postcss-pxtorem, it seems indeed that it doesn't have most of the problems of similar solutions. in essence then, this is a developer convenience plugin that allows authors to still "think" in terms of `px` and then magically converts to `rem`. i can see that the end result is...ok, but beyond making it a convenience for authors who still can't think/don't want to think in terms of `em`/`rem`, i see little value in this myself. @twbs/team thoughts?

**Comment by XhmikosR** [comment]
Yeah, agreed. All rem is preferred to me too.
