### ISSUE TITLE
custom-file-input issues height

### ISSUE THREAD

**Issue by arcanisgk** [twbs/bootstrap#28393]
i find that .custom-file-input class in BT 4.1 have this:

```
.custom-file-input {
    position: relative;
    z-index: 2;
    width: 100%;
    height: calc(2.25rem + 2px);
    margin: 0;
    opacity: 0;
}
```
And on 4.3 has this:

```
.custom-file-input {
    position: relative;
    z-index: 2;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    margin: 0;
    opacity: 0;
}
```

and it not showing igual not the same size... why you change it?

**Comment by alecpl** [comment]
The same happened on `.form-control` so it should be the same as other inputs. What browser? Provide a sample code and/or screenshot.

**Comment by MartijnCuppens** [comment]
It is changed to make Bootstrap ready for responsive font sizes. If the size is not the same, you 've probably overridden the font size of the `html` element, which influences the value of `rem`. In that case you can set your font size to the body.
