### ISSUE TITLE
Expand border utilities to include {sm,md-lg-xl}-{top,bottom,left,right}

### ISSUE THREAD

**Issue by marcanuy** [twbs/bootstrap#28403]
As we already have utilities like: `text-sm-left` and `float-sm-left`, it would make sense to  alsohave `border-sm-left` and similar for the rest of sizes. (#25024)

I find it pretty often using borders that I don't want to show in smaller sizes when the grid may change to a stacked one. For example: a `border-left` makes sense in a column layout to separate columns, but not when they are stacked.

**Comment by mdo** [comment]
This has been requested before, and I'm still a no on it. Thanks though!
