### ISSUE TITLE
error of popover in bootstrap 4.3.1

### ISSUE THREAD

**Issue by phangia2712** [twbs/bootstrap#28407]
In custom popover, I insert button tag and section tag, all has been removed (can't show in DOM)
I think it's a bug of popover when using bootstrap/4.3.1/js/bootstrap.min.js

Please check it! Tks =))))

**Comment by Johann-S** [comment]
Hi @phangia2712,

It's not a bug, we mentionned that in our blog post (see: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/) we added a sanitizer to avoid XSS so if you need to allow button and section tags you can add them in the whitelist see: https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer

**Comment by phangia2712** [comment]
ok, tks your feedback @Johann-S , I will check it =)))
