### ISSUE TITLE
Toast color variants

### ISSUE THREAD

**Issue by AndreiIgna** [twbs/bootstrap#28418]
The new Toast element looks good, but with a bit more color variants it may be even better.
<img width="294" alt="screenshot 2019-03-06 at 12 51 19" src="https://user-images.githubusercontent.com/263021/53879500-fffcfb00-400e-11e9-8880-1905efd3c8e9.png">

In my project I've quickly added the variants with code copied from Alerts https://github.com/twbs/bootstrap/blob/master/scss/_alert.scss#L43. Is this something that would be useful for others and helpful to be added in Toast component?

Cheers

**Comment by visionlewis** [comment]
Does this still work with the toast titlebar / close button?

**Comment by mdo** [comment]
We'll pass for now, thanks though!
