### ISSUE TITLE
`npm install` throws an error while installing a packages

### ISSUE THREAD

**Issue by salunkeprashant** [twbs/bootstrap#28415]
When I install Bootstrap trough NPM and try to install the dependencies in the package.json (for `grunt-sed`)
I get an error.

These are the steps I take,
Download and extract `bootstrap-3.3.5` zip to a local directory.
Navigate to the directory and hit `npm install`.

It is trying to resolve all packages inside package.json. At `grunt-sed` it will ask you to enter GitHub credential or directly throws below error.

` C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/twbs/grunt-sed.git
Warning: Permanently added 'github.com,***.***.***.***' (RSA) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128`.

Is this repository removed? Or moved to another location?

**Comment by mdo** [comment]
This doesn't appear to be a Bootstrap problem so much as a problem with your local setup. Also, v3.3.5 is very old and no longer maintained.

**Comment by szekely-szabolcs** [comment]
Apparently the grunt-sed repo was removed from the `twbs` (aka Bootstrap's ) available repositories.
So you basically broke the build possibility of old (3.x) versions. I understand that it is not maintained, fixed or improved, but at least you should keep the dependencies up.
