### ISSUE TITLE
Popover not rendering form elements inside itself

### ISSUE THREAD

**Issue by pcarballeda** [twbs/bootstrap#28410]
Hello everyone. I found this bug after update Bootstrap to the latest version (4.3.1) in my project.

The thing is that popover component is not rendering form elements like <form>, <input> or <button> inside it. This feature was working for the previous version of Bootstrap.

You can find this problem here: https://codepen.io/pcarballeda/pen/pYNzzR

**Comment by mdo** [comment]
For security purposes, `<form>` and other interactive elements are no longer whitelisted by default for inclusion in tooltips and popovers. See our sanitizer docs for details on how to update this for yourself. https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
