### ISSUE TITLE
upgraded to 4.3.1 and modal error getSelectorFromElement

### ISSUE THREAD

**Issue by v3nt** [twbs/bootstrap#28412]
Trying to open Modal causes error and modal doesn't open.

Have tried latest documentation of example modals and still the same issue (from https://getbootstrap.com/docs/4.1/components/modal/).

Popper 1.14.7 is installed.

#Dev site
Added to top of dev site.
http://wonkhe2dev.jynk.net/about-us/

Same issue when trying to use JS method.

        `$('#signup_modal').modal('show');`

#Error
modal.js:606 Uncaught TypeError: Cannot read property 'getSelectorFromElement' of undefined
 
line modal.js:606
var selector = Util.getSelectorFromElement(this);
 
##MacOS
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Latest Safari, Safari tech preview, Chrome

**Comment by MartijnCuppens** [comment]
Your target is not set correctly, see `data-target="#exampleModal"`. Please debug your application before opening an issue.

**Comment by v3nt** [comment]
thanks but that doesn't explain this js issue. The examples was added to debug the 1st.

  `$('#signup_modal').modal('show');`

**Comment by MartijnCuppens** [comment]
You are not including the necessary styles for the modal. Please debug your application first.

**Comment by v3nt** [comment]
styles there now and still a clear js error.

**Comment by v3nt** [comment]
Hey Martin - was wondering if this could be re-opened?

**Comment by MartijnCuppens** [comment]
You are not including the Util. Please read the documentation (https://getbootstrap.com/docs/4.3/getting-started/javascript/#util) and read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md) before opening an a bug report.
