### ISSUE TITLE
How to give credit to code snippets and html codes

### ISSUE THREAD

**Issue by AlirezaAlipour** [twbs/bootstrap#28420]
In [Licence](https://github.com/twbs/bootstrap/blob/master/site/docs/4.3/about/license.md) mentioned: 

> Bootstrap is released under the MIT licenses and is copyrighted 2019 Twitter

In addition, in the Copyright and licence section of [REDME](https://github.com/twbs/bootstrap/blob/master/README.md) mentioned as follow:

> Code and documentation copyright 2011-2019 the [Bootstrap Authors](https://github.com/twbs/bootstrap/graphs/contributors) and [Twitter, Inc](https://twitter.com/). Code released under the [MIT License](https://github.com/twbs/bootstrap/blob/master/LICENSE). Docs released under [Creative Commons](https://github.com/twbs/bootstrap/blob/master/docs/LICENSE).

Firstly, the link for "Creative Commons" is not valid.

My confusion is as follow:

- Is it require to give credit to code snippets in the [docs](https://github.com/twbs/bootstrap/tree/master/site/docs)? If it is require how to do it?
- Is it require to give credit to html codes of the [examples](https://github.com/twbs/bootstrap/tree/master/site/docs/4.3/examples)? if it is require how to do it?

**Comment by mdo** [comment]
If you're using the project's source code, it has attribution in there—nothing else is required.

**Comment by AlirezaAlipour** [comment]
Thank @mdo very much. As stated in the footer of [Bootsrap](https://getbootstrap.com/):

> Designed and built with all the love in the world by the [Bootstrap team](https://getbootstrap.com/docs/4.3/about/team/) with the help of [our contributors](https://github.com/twbs/bootstrap/graphs/contributors).
Currently v4.3.1. Code licensed [MIT](https://github.com/twbs/bootstrap/blob/master/LICENSE), docs [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/).

Base on [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) I need to give credit to code snippets and the [examples](https://github.com/twbs/bootstrap/tree/master/site/docs/4.3/examples). as you mentioned:

>  If you're using the project's source code, it has attribution in there—nothing else is required.

Codes files contain attribution, like [this](https://github.com/twbs/bootstrap/blob/master/scss/bootstrap.scss), but my problem is html codes in the [examples](https://github.com/twbs/bootstrap/tree/master/site/docs/4.3/examples) don't contain attribution, for example [this](https://github.com/twbs/bootstrap/tree/master/site/docs/4.3/examples/navbars). Also code snippets don't contain attribution, for example:

![screenshot from 2019-03-07 10-39-49](https://user-images.githubusercontent.com/14098141/53938426-7fe59c80-40c5-11e9-884f-06839bba2af0.png)
