### ISSUE TITLE
Non ul or ol based .nav-link should require .nav-item class

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#28423]
The non `ul` or `ol` based navs e.g.

```html
<nav class="nav">
  <a class="nav-link active" href="#">Active</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link" href="#">Link</a>
</nav>
```

should be require `.nav-item` class:

```html
<nav class="nav">
  <a class="nav-item nav-link active" href="#">Active</a>
  <a class="nav-item nav-link" href="#">Link</a>
  <a class="nav-item nav-link" href="#">Link</a>
</nav>
```

Because there are many snippets without `.nav-item` class in the docs, so it looks like it's not necessary, but the `.nav-item` class is often required. As an example, the pill style does not require `.nav-item`, but the tab style needs it (this usage isn't documented).

![image](https://user-images.githubusercontent.com/4065765/53945740-9d3a5b00-4105-11e9-99a5-44c5b7321e06.png)

demo: https://codepen.io/anon/pen/wOJWJo

And the [example in the navbar nav](https://getbootstrap.com/docs/4.3/components/navbar/#nav) use `.nav-item` with `.nav-link`.

![image](https://user-images.githubusercontent.com/4065765/53946273-c5768980-4106-11e9-853b-795b17148cd2.png)

This lack of consistency caused the problem of #28117.

I strongly recommend add `.nav-item` to all `.nav-link` of the non `<ul>` or `<ol>` based nav.

**Comment by ms-yogi** [comment]
@MartijnCuppens I want to contribute to the repo. Can I take this issue?

**Comment by MartijnCuppens** [comment]
@ms-yogi, sure, go ahead! For this case, we might maybe better more the `margin-bottom: -1px;` from `.nav-tabs .nav-item` to `.nav-tabs .nav-link`, this way we don't need to add this additional class. (I haven't tested if there are any downsides to this though)

**Comment by ysds** [comment]
@MartijnCuppens 
My point is `.nav > a` requires both classes. Please see 
https://github.com/twbs/bootstrap/issues/28117#issuecomment-457549231

**Comment by rohit2sharma95** [comment]
> My point is `.nav > a` requires both classes.

@ysds `.nav-item` class is required only if `.nav` has `.nav-justified` class.

As the border issue has been fixed (in V5) by adding margin in the `.nav-link` inside `.nav-tabs`
https://github.com/twbs/bootstrap/blob/62626db320ee982a5576fa9c71f5bd7530056009/scss/_nav.scss#L37-L41

Thus `.nav-item` will no longer be required if the following lines:
https://github.com/twbs/bootstrap/blob/62626db320ee982a5576fa9c71f5bd7530056009/scss/_nav.scss#L101-L107

are changed to:
```css
.nav-justified {
  > .nav-link,
  .nav-item {
    flex-basis: 0;
    flex-grow: 1;
    text-align: center;
  }
}
```
