### ISSUE TITLE
Sample table from Bootstrap rendering twice in nuxt app.

### ISSUE THREAD

**Issue by Hey-tom** [twbs/bootstrap#28429]
Hi Group, I've made an new app with npx create-nuxt-app and then a new file in the pages folder. I've added in a sample datatabe from bootstraps website and I see that the table is rendering twice? Has anyone experienced this before? Is this a bug with nuxt or bootstrap?

Here's a sandbox with the issue replicated.
https://7wo3jr51.sse.codesandbox.io/Table

Thanks

**Comment by Hey-tom** [comment]
Hi Group, I've made an new app with npx create-nuxt-app and then a new file in the pages folder. I've added in a sample datatabe from bootstraps website and I see that the table is rendering twice? Has anyone experienced this before? Is this a bug with nuxt or bootstrap?

Here's a sandbox with the issue replicated.
https://7wo3jr51.sse.codesandbox.io/Table

Thanks

**Comment by patrickhlauke** [comment]
for "how-to" type questions, use stackoverflow or similar please. see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
