### ISSUE TITLE
Popover content removes button element

### ISSUE THREAD

**Issue by joviniko** [twbs/bootstrap#28427]
Adding a Button-element as content to a popover used to work under Bootstrap 4.2.1.

[Codepen Testcase using Bootstrap 4.3.1](https://codepen.io/joviniko/pen/moWRvr) 
![bootstrap-popover-bug](https://user-images.githubusercontent.com/2021626/53951007-cc34da80-40cd-11e9-918a-3b5976a3caad.png)

In bootstrap 4.3.1 the content is simply an empty div:
```html
<div class="popover-body"></div>
```
Doing the same with a Link-element instead of a Button works:
```html
<div class="popover-body"><a href="#" class="btn btn-warning">Test link</a></div>
```
[Working Testcase using Bootstrap 4.2.1](https://codepen.io/joviniko/pen/wOJgOr)
![bootstrap-popover-working](https://user-images.githubusercontent.com/2021626/53951191-2fbf0800-40ce-11e9-95fc-59bc8f14b9ae.png)

- Operating system: Ubuntu 18.04.2
- Tested Browsers: Chrome 72.0.3626.121 & Firefox 65.0.1

**Comment by InsanityMeetsHH** [comment]
See #28407

**Comment by joviniko** [comment]
> See #28407

thanks, closing this issue
