### ISSUE TITLE
Label inside Button

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#28430]
Hello,

According to a project need, i had to create some labels inside buttons.
The initial idea was based on Jasny package, but as it isn't active anymore, I had to recreate the result for Bootstrap 4 Version
<a href="https://codepen.io/GeosSV/pen/JzNjKa/">
  Codepen Example</a>

If you think it could fit here, I can make a pull request

**Comment by mdo** [comment]
Looks slick, but we'll pass on adding it to Bootstrap for now :).
