### ISSUE TITLE
No Spaces Between Tabs

### ISSUE THREAD

**Issue by Shrubhog** [twbs/bootstrap#28436]
- Operating system: Ubuntu 18.04.1 LTS
- Browser and version: Chrome 72.0.3626.121
- Reduced test case: [https://codepen.io/anon/pen/WmONZx](https://codepen.io/anon/pen/WmONZx)

# Expected Behaviour:

![Screenshot from 2019-03-08 14-49-17](https://user-images.githubusercontent.com/37482938/54055023-628dfc80-41b1-11e9-8fb1-9dcf96574ead.png)
# Actual Behaviour:

![Screenshot from 2019-03-08 14-47-49](https://user-images.githubusercontent.com/37482938/54054952-34a8b800-41b1-11e9-8fc9-66cfe639e510.png)

**Comment by knoobie** [comment]
Could this be related to #28423?

**Comment by Shrubhog** [comment]
I don't think so. These are tabs with content rather than navs. They could be, but adding a nav wrapper doesn't seem to have an effect.

**Comment by herbalite** [comment]
Additionally to the nav-item class on li elements as already pointed out above, you have to add the nav-link class to the a tag.

Same link as in the post from max-ci

**Comment by Shrubhog** [comment]
Thank you all! I misread the documentation but you solved my PEBKAC. 
Sorry for the inconvenience.
