### ISSUE TITLE
Bootstrap - Simple Sidebar - modifica comportamento

### ISSUE THREAD

**Issue by fulviot66** [twbs/bootstrap#28432]
Hi Guys,
I hope you're doing well.
Btw where can I read a complete explanations of properties about the Bootstrap #sidebar-wrapper class?
Thanks a lot in advance for your support.
Cheers
Fulvio 
[startbootstrap-simple-sidebar-gh-pages.zip](https://github.com/twbs/bootstrap/files/2945971/startbootstrap-simple-sidebar-gh-pages.zip)

**Comment by mdo** [comment]
This element doesn’t exist in Bootstrap—looks like you may be using a theme.
