### ISSUE TITLE
Bootstrap v2.x and v3.x - End of Life

### ISSUE THREAD

**Issue by babatundeko** [twbs/bootstrap#28434]
Hi, Bootstrap Help Desk Support,

My organization is currently using Bootstrap v3.3.7 for the internal web application and plan to upgrade v.3.4.1 due to XSS vulnerability issue. However, is a Bootstrap v2.x and v3.x end of life(EOL)? And no longer supported and maintained? If not, then we need an upgrade to Bootstrap v4.x. Please confirm and provide a brief description of why these versions no longer supported/maintained. Any significance information relates to EOL would be appreciated. 

Thanks, 
Kazeem

**Comment by mdo** [comment]
We're formulating an official release status and you can find it at https://github.com/twbs/release.

**Comment by babatundeko** [comment]
Hi!

Regarding my old ticket, what kind of security scan software tool do you use to scan on each version and upcoming release version?  NIH and NHLBI are using NetSparker and IBM AppScan, and we want to ensure that we are using a similar tool to test an application to avoid confusion on what acceptable and whatnot on vulnerability part. Any significance information relates to security would be appreciated for my organization.
