### ISSUE TITLE
Cross symbol (Clear button) for input element with invalid state

### ISSUE THREAD

**Issue by sstativa** [twbs/bootstrap#28431]
What is the point of showing the cross symbol on `.form-control.is-invalid` if it's doing nothing? There is no attached event listener and there is no way to attack your own `onclick` function to the symbol.

If this is a button, it should work as a button. If this is just a symbol to highlight the invalid state of the field then some other image should be used. The cross symbol only confuses the user.

**Comment by mdo** [comment]
It's an `x` that says it's invalid, as in crossed out. It's not a clear the form button.

**Comment by sstativa** [comment]
Cross symbol is a terrible choice for this.

First of all, because it is used by [Microsoft](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear). Secondly, the cross symbol usually represents a button with delete (or close) functionality (this is the expected behaviour on all mobile devices where the cross is shown). Showing cross on the input without any supporting action will only confuse users.

In addition, there is a discrepancy between [Documentation](https://getbootstrap.com/docs/4.1/components/forms/#server-side) and the current state of `bootstrap.css` library. You will not see the cross symbol if you play with form validation in the Documentation.

**Comment by mdo** [comment]
The &times; for error is pretty widely used, though I do agree it could be confusing. This is the first report I've seen suggesting it's confusing or problematic though, so I'm not rushing to any changes.

You're also looking at outdated documentation—validation icons weren't restored until v4.2. [Here's the latest page (v4.3.x).](https://getbootstrap.com/docs/4.3/components/forms/#server-side)

**Comment by fjordaan** [comment]
Just as a data point on this issue: I have just disabled the validation icons as some of our users also attempted to click the X icon, expecting it to clear the field. I agree with the suggestion elsewhere to change the invalid icon – perhaps to an exclamation mark.
