### ISSUE TITLE
Remove focus & hover states from `bg-variant` mixin

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#28444]
About this code:
https://github.com/twbs/bootstrap/blob/8896827bd072a120705a0576a5bcde69c8ce2cda/scss/mixins/_background-variant.scss#L9-L14

I think we should remove it. IMO focus and hover background states don't belong in these utilities and we are also not defining an active state here. We have the buttons with backgrounds, if this doesn't cover the needs I think the developer will need to write custom code, because it's quite specific.

I guess we can just remove the mixin, just use the `background-color` property in `v5` and use the `deprecate` mixin to deprecate this in `v4`.

Thoughts?

**Comment by mdo** [comment]
Big fan of this. Nix the mixin and the hover/focus states. We'll inevitably get the question of how to set hover styles via utilities, but I don't think that's a path we should go down. Maybe provide some guidance in our docs though for how to customize that kind of stuff?

**Comment by MartijnCuppens** [comment]
> Maybe provide some guidance in our docs though for how to customize that kind of stuff?

If we ditch the mixin, we can use the utility API https://github.com/twbs/bootstrap/issues/28367 (or whatever it will be called) and  clarify this in its documentation section.

> We'll inevitably get the question of how to set hover styles via utilities, but I don't think that's a path we should go down

I agree, I experimented with hover utilities before, but you'll end up with elements tons of utility classes. It's just better to create a custom component if an element needs hover states to get a better overview of all the properties.
