### ISSUE TITLE
Unable to compile text-dark to override anchor tags

### ISSUE THREAD

**Issue by guylepage3** [twbs/bootstrap#28441]
I'm encountering a compiling issue when attempting to compile parts of bootstrap, the classes `text-dark` and `text-light` do not compile to override anchor tags.

```
<a href="#" class="text-dark">Content</a>
<a href="#" class="text-light">Content</a>
```

This is how I've setup my bootstrap parts

```
@import "functions";
@import "variables";
@import "mixins";
@import "root";
@import "reboot";
@import "type";
@import "images";
@import "code";
@import "grid";
@import "components";
@import "forms";
@import "buttons";
@import "transitions";
@import "dropdown";
@import "button-group";
@import "input-group";
@import "custom-forms";
@import "nav";
@import "navbar";
@import "card";
@import "alert";
@import "list-group";
@import "tooltip";
@import "utilities";
```

But when I use the entire bootstrap SCSS file, it compiles correctly and I am able to override the anchor tags no problem.

Any thoughts on what is going on here?

**Comment by herbalite** [comment]
Which version are you using?

What is in the file called components? Can't find that in 4.3.1 If you remove that, what happens?

**Comment by guylepage3** [comment]
There is only the following and when I remove that import it does not change the issue.

```
// Components
//
// Define common padding and border radius sizes and more.

$border-color:                $white;

$border-radius:               .25rem;
$border-radius-lg:            .25rem;
$border-radius-sm:            .25rem;

.line {
  height: 1px;
}
```

**Comment by InsanityMeetsHH** [comment]
> `text-dark` and `text-light` do not compile to override anchor tags.

Are the classes missing? Or do they have the wrong color?

> But when I use the entire bootstrap SCSS file, it compiles correctly and I am able to override the anchor tags no problem.

How do you override?

`text-dark` and `text-light` are generated in utilities/_text.scss and looped through `$theme-colors`.
So you have to override `$theme-colors`.

**Comment by guylepage3** [comment]
>Are the classes missing? Or do they have the wrong color?
Missing.. but only in my setup. They are there when compiling the entire bootstrap `bootstrap.scss`.

>How do you override?
```
<a href="#" class="text-dark">Content</a>
```

>text-dark and text-light are generated in utilities/_text.scss and looped through $theme-colors.
>So you have to override $theme-colors.
Sure. But they are not compiling and are missing as stated above.

**Comment by InsanityMeetsHH** [comment]
By the given information I can't see any misconfiguration.
For `text-*` you need to import utilities/_text.scss and mixins/_text-emphasis.scss. I assume that they are imported.
What you can do is to import all SCSS files and disable one, save and check if it works or not. If it works disable next one and so on.

**Comment by guylepage3** [comment]
>For text-* you need to import utilities/_text.scss and mixins/_text-emphasis.scss. I assume that they are imported.

Yes they are. I even went so far to import them all directly.

>What you can do is to import all SCSS files and disable one, save and check if it works or not. If it works disable next one and so on.

I'll give that a shot again and see what I find. I'll check back with a response in an hour or two.

**Comment by mdo** [comment]
Is this still an issue? Just tried the override on our live docs and it works as expected, so I'm wondering if there was/is something off in any of your custom CSS. Potentially some hidden errors?

**Comment by guylepage3** [comment]
I will confirm tonight. Thanks.

**Comment by MartijnCuppens** [comment]
Overriding this should work as expected.
