### ISSUE TITLE
alert-success no styling

### ISSUE THREAD

**Issue by TeoDiaz** [twbs/bootstrap#28448]
There you got a problem.  First of all, the link for issue guidelines is broken... and then: 

While:
```alert-info``` 
```
Appears:

.alert-info {
    color: #31708f;
    background-color: #d9edf7;
    border-color: #bce8f1;
}
```
When:
```alert-success```

Appears only:
```
.alert {
    padding: 15px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    border-radius: 4px;
}
```

**Comment by mdo** [comment]
> First of all, the link for issue guidelines is broken...

What link would that be?

Your issue is unclear and lacks a demo, per the bug report issue template. Alerts look fine to me in our latest hosted docs: https://getbootstrap.com/docs/4.3/components/alerts/.

**Comment by TeoDiaz** [comment]
Link is now ok... sorry about that.
