### ISSUE TITLE
Bootstrap bug with popper on the latest update

### ISSUE THREAD

**Issue by myorangeca** [twbs/bootstrap#28442]
I noticed a very peculiar bug with the latest version release of bootstrap's JS file. In version 4.3.0 this was working as expected (see example below)

**Code pen working version in version 4.3.0** 
https://codepen.io/anon/pen/KEqrWz

After the release of BS v4.3.1 this is no longer working (see example below)

**Same code but latest version 4.3.1 (no longer working)**
https://codepen.io/anon/pen/oVwQEa

My guess would be something to do with the  tools/sanitizer.js that was recently added. There must be conflict somewhere. It will not display any form tags to be placed inside the popper.js (with data-html=true state)

**Comment by asyncdesign** [comment]
You need to update the hash in your CDN link if you are using a newer version of the Bootstrap js file. 

See: https://getbootstrap.com/docs/4.3/getting-started/introduction/#js

**Comment by mdo** [comment]
@asyncdesign is correct on that, but also yes, you need to modify the sanitizer whitelist to allow for form elements. See the popover options docs for details. https://getbootstrap.com/docs/4.3/components/popovers/#options
