### ISSUE TITLE
Type display as map

### ISSUE THREAD

**Issue by afanjul** [twbs/bootstrap#28451]
Why do you code "display-x" class types, as a separatad variables, instead of a more "robust and best practice" code using a map (as many other parts in bootstrap)? I think that using a map it would be easier to extend or remove display types... 

**In _variables.scss**

```
$displays: (
  1:(6rem, 300),
  2:(5.5rem, 300),
  3:(4.5rem, 300),
  4:(3.5rem, 300),
);
```

**In _types:**

```
@each $index,$values in $displays {
  .display-#{$index} {
    @include font-size(#{nth($values,1)});
    font-weight: #{nth($values,2)};
    line-height: $display-line-height;
  }
}
```

**Comment by bardiharborow** [comment]
I think last time we tried this, it caused people problems having to redefine the whole map.

**Comment by afanjul** [comment]
> I think last time we tried this, it caused people problems having to redefine the whole map.
That does not sound like a good reason to not implement it... is it? anyway I did a pull request with the code: https://github.com/twbs/bootstrap/pull/28453

**Comment by mdo** [comment]
Was done in #30568
