### ISSUE TITLE
Cannot include bootstrap 4.3.1

### ISSUE THREAD

**Issue by kev1807** [twbs/bootstrap#28468]
```<!DOCTYPE html>
<html>
<head>
	<title>test</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-default">
	<li>Test</li>
</nav>
</body>
</html>
```

does not give a proper boostrapped Navbar, but only a "html-standard" output, as can be seen on the image

**Comment by kev1807** [comment]
Jesus, what did I do to github :-/ 

When I'm using bootstrap from https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css

I get the wanted output, but not with the 4.3.1 Version from stackpath, what am I doing wrong?

**Comment by mdo** [comment]
Fixed your code formatting here, but your code snippet is invalid HTML (e.g., `<li>`s are for within `<ol>` and `<ul>` elements). Other than that, you should be getting the proper CSS. For more help, I suggest asking in our Slack or StackOverflow (linked in our readme).
