### ISSUE TITLE
How do I get all the files in the master branch through 'npm install'

### ISSUE THREAD

**Issue by zhnoah** [twbs/bootstrap#28465]
When I use 'NPM install', I get only a few files in the branch. How do I get all of them？

**Comment by Johann-S** [comment]
We don't distribute all of our files, if you want all the files you can download our repository thanks to github.

![image](https://user-images.githubusercontent.com/1689750/54194953-bc4a3b80-44bd-11e9-9bf9-9e5fb89203a9.png)
