### ISSUE TITLE
Split -x in navbar-nav-link-padding-x to -r (right) and -l (left)

### ISSUE THREAD

**Issue by gentledawn** [twbs/bootstrap#28470]
At this current state, if a navbar menu is positioned to the right side, the last menu/item will have an extra (unnecessary) padding on the right side, so that it is not on the very right edge of the container.

Similarly, if a navbar is positioned to the left without anything before the navbar, then the first menu/item will have an extra padding on the left side, so that it is not on the left edge of the container.

If the $navbar-nav-link-padding-x is being splitted into $navbar-nav-link-padding-l and $navbar-nav-link-padding-r then it will be easier to manage this.

**Comment by mdo** [comment]
We don't do that really anywhere so, so unlikely to happen at this time. Generally speaking, padding should be balanced as it affects the hit area for links.
