### ISSUE TITLE
Button in list-group-item-action

### ISSUE THREAD

**Issue by AndiLeni** [twbs/bootstrap#28477]
I encountered a problem using the list-group-item.
See: https://jsfiddle.net/AndiLeni/7vgwahdf/21/

If the list item is just a `<li>` the button is placed nice without problems. But if it's a `<a>` link the additional button is missaligned.

Is there a solution for this?

regards
Andi

**Comment by florianlacreuse** [comment]
Having a `<a>` inside another `<a>` is a bad practice. See [W3C specs](https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element).

**Comment by AndiLeni** [comment]
@florianlacreuse 
I know. But I could not think about another solution. That's why I'm asking here.

**Comment by patrickhlauke** [comment]
indeed, this looks like a rather odd construct, and - unless I'm missing something - not something that's supported by Bootstrap. depending on what you're actually trying to do, there may be better ways to go around this (other than nesting a link inside an anchor?), but i'd suggest initially asking on stackoverflow or similar, explaining what it is you're actually trying to achieve. see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md
