### ISSUE TITLE
Inconsistent validation/custom-select icon position

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#28476]
![boot-issue](https://user-images.githubusercontent.com/546788/54278376-790dcc80-4592-11e9-953f-6e5d724532ef.png)

Not a big issue, but it would be good the icon position and padding is consistent for these two elements.

**Comment by mdo** [comment]
No longer an issue as, at least for select menus, the validation icon appears in addition to the toggle icon in both v4 and v5.

**Comment by alecpl** [comment]
@mdo I think you missanderstood the issue. It's not about validation icon on a select element. See the example above. It is an input element above the select element. Input uses padding-right `36px` (calculated) the select uses padding-right: `28px` (calculated). That is inconsistent. The issue is not big but you can actually see the icons are not perfectly aligned with each other and if both elements contain text that fills the whole width you'll notice that the text in the input is cut "earlier".

This is still an issue in 4.5.0.
