### ISSUE TITLE
Closing an open collapsed navbar on clicking outside of the navbar element on mobile

### ISSUE THREAD

**Issue by imabot2** [twbs/bootstrap#28474]
Example: [https://friconix.com](https://friconix.com)

Open this page on mobile (or in desktop with resized browser window to width less than 768px) and try to collapse menu by clicking outside of dropdown. In this case nothing happens. So you can collapse menu only by clicking on button with bars (navbar-toggle button).

It seems natural to close the dropdown when clicking outside the menu. 

This also happens on bootstrap examples : [https://getbootstrap.com/docs/4.1/components/navbar/#external-content](https://getbootstrap.com/docs/4.1/components/navbar/#external-content)

This has already been reported on Bootstrap 3, but issue has been closed : [https://github.com/twbs/bootstrap/issues/19768](https://github.com/twbs/bootstrap/issues/19768)

Is it a bug or am I missing something ?

**Comment by Johann-S** [comment]
It's the normal behavior, collapse do not handle click outside of the trigger but Dropdown handle that behavior
