### ISSUE TITLE
[v3] input[type=date] placeholder is not centered vertically in latest Mozilla Firefox

### ISSUE THREAD

**Issue by Dartui** [twbs/bootstrap#28475]
Example: https://codepen.io/dartui/pen/drJPjQ
Code which generates bug: https://github.com/twbs/bootstrap/blob/v3.4.1/less/forms.less#L186-L202
And screenshot:
![obraz](https://user-images.githubusercontent.com/2657856/54276859-a22c5e00-458e-11e9-91b5-c10ed79e7906.png)

This is not causing any errors in Google Chrome.

Browser: Mozilla Firefox 65.0.1 (64 bit)
OS: Ubuntu 18.04.2 LTS

**Comment by mdo** [comment]
Thanks for reporting, but v3 development has ceased save for some recent security fixes. It'll soon be EOL (end of life) entirely, so closing this as a won't fix.
