### ISSUE TITLE
Move certain functions to variables in _variables.scss

### ISSUE THREAD

**Issue by dhodvogner** [twbs/bootstrap#28485]
## Idea
Move functions like darken/lighten into variable/variables in the "_variables.scss", to enable developers to customize bootstrap better.

## Short example

```sass
$test-color: #ff0000;
$test-function: get-function("darken");
$test-function-value: 10%;

@mixin test-mixin($color, $final-color: call($test-function, $color, $test-function-value)) {
  background-color: $final-color;
}

// All three should produce the same output

.foo {
  @include test-mixin($test-color);
}

.bar {
  background-color: call($test-function, $test-color, $test-function-value);
}

.check {
  background-color: darken(#ff0000, 10%);
}
```
**Tested with:**  node-sass 4.11.0

## Usage ideas

Customizable hover/active on buttons:

**_variables.scss**
```sass
// Buttons
$btn-hover-fnc: get-function("darken") !default;
$btn-active-fnc: get-function("darken") !default;

$btn-hover-background-fnc: $btn-hover-fnc !default;
$btn-hover-background-fnc-value: 7.5% !default;

$btn-hover-border-fnc: $btn-hover-fnc !default;
$btn-hover-border-fnc-value: 10% !default;

$btn-active-background-fnc: $btn-active-fnc !default;
$btn-active-background-fnc-value: 10% !default

$btn-active-border-fnc: $btn-active-fnc !default;
$btn-active-border-fnc-value: 12.5% !default;
```

**mixins/_buttons.scss**
```sass
@mixin button-variant(
$background, 
$border, 
$hover-background: call($btn-hover-background-fnc, $background, $btn-hover-background-fnc-value), 
$hover-border: call($btn-hover-border-fnc, $border, $btn-hover-border-fnc-value),
$active-background: call($btn-active-background-fnc, $background, $btn-active-background-fnc-value), 
$active-border: call($btn-active-border-fnc, $border, $btn-active-border-fnc-value)
) {
...
}
```

## Epilogue
I think it could be really really useful for people (like me) who have to create many customizations for bootstrap. My recent 3 project needed buttons with a lighter color on hover for example. 
What do you think?

I tried to search back in the Issues history, but if there is/was any similar idea I'm sorry for the duplicate :/

**Comment by mdo** [comment]
I agree some generated code like our button and alert component variants could use additional customization power, but this feels rather complicated. I don't see us going this route as it stands now though, but would like to hear more ideas on how to improve your customizing.
