### ISSUE TITLE
Bootstrap as a styled-components library

### ISSUE THREAD

**Issue by ahtee** [twbs/bootstrap#28494]
Would it make sense to also include a library through styled-components? Would it be too difficult to execute? Not exactly sure how we would handle mixins and other sort of css variables available in Sass.

Just a thought :)

**Comment by rafaelblink** [comment]
https://github.com/aichbauer/styled-bootstrap-components

**Comment by mdo** [comment]
I don't think I can see us doing this in the main repo? /cc @MartijnCuppens

**Comment by ahtee** [comment]
Even like an approved version you see would be fine I think. there's also https://github.com/xDae/styled-bootstrap. If people want to use the bootstrap-style css-in-js it could be helpful to have a verified or recommended library if it already exists.

**Comment by MartijnCuppens** [comment]
Maybe one day, but for now we better pass on this IMO. @Johann-S, what's your opinion on this, I remember you once said something about styled components somewhere but I can not recall what that was.

**Comment by ahtee** [comment]
Sounds good, just wondered what the team thought since react seems very popular but also seems some devs steer clear of bootstrap since the primary method of adding bootstrap to a site is by importing everything at once instead of per component

**Comment by MartijnCuppens** [comment]
We try to make Bootstrap available for as many developer environments possible, so we probably won't go this direction. If you are interested in styled components, I would suggest trying out the third party solution mentioned above.
