### ISSUE TITLE
Error while compling 4.3.1

### ISSUE THREAD

**Issue by f86597** [twbs/bootstrap#28495]
I import variables.scss file into my custom.scss file.When I compile custom.scss file It show this erorr on my compiler. 
"Error: argument `$color` of `darken($color, $amount)` must be a color on line 174 of sass/e:\Xampp\htdocs\custom-bs\custom\_customVariables.scss, in function `darken` from line 174 of sass/e:\Xampp\htdocs\custom-bs\custom_customVariables.scss  from line 1 of sass/e:\Xampp\htdocs\custom-bs\custom\custom.scss
>> $link-hover-color: darken($link-color, 15%) !default;"
`$link-color:                              theme-color("primary") !default;
$link-decoration:                         none !default;
$link-hover-color:                        darken ($link-color, 15%) !default;
$link-hover-decoration:                   underline !default;
// Darken percentage for links with `.text-*` class (e.g. `.text-success`)
$emphasized-link-hover-darken-percentage: 15% !default;`

This is 174 line number
`$link-hover-color:                        darken ($link-color, 15%) !default;`

I am using [this](http://koala-app.com/) visual studio code extension and [koala](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass) to compile scss in css both giving same error on compiling

Windows 10 version 1809 X_64 build 17763.316
Visual studio code version 1.32.2
Live sass compiler version 3.0.0

**Comment by xshiiiidev** [comment]
Got this same issue with the 4.3.1
