### ISSUE TITLE
[Popover] : When toggle popover, its data-* attribute removed

### ISSUE THREAD

**Issue by dpr-odoo** [twbs/bootstrap#28492]
**OS:**
macOS Mojave: 10.14 (18A391)
**Browser:**
Chrome:  72.0.3626.121 (Official Build) (64-bit)

With ``html: true`` and ``content: <<text>>`` with data-* attribute, when toggling Popover it not adding ``data-*`` attributes to element in popover. So when we trigger click on an element inside popover and try to find data on target it fails to load.

Video Demo: https://youtu.be/bUTovHhwUAY
Demo: https://www.bootply.com/npPXvDAKvS

**Comment by InsanityMeetsHH** [comment]
Since BS 4.3 you have to whitelist `data-id` for span tag.
See #28407

**Comment by Johann-S** [comment]
Exactly what @InsanityMeetsHH said 👍 

More information on how to do that: https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer

**Comment by dpr-odoo** [comment]
Thank you @InsanityMeetsHH @Johann-S 👍

**Comment by SlimDeluxe** [comment]
This also applies to BS 3.4 as described [here](https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer).
