### ISSUE TITLE
Ditch the sass maps

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#28506]
Continuing on https://github.com/twbs/bootstrap/pull/28445#issuecomment-473151602 and https://github.com/twbs/bootstrap/issues/27927#issuecomment-450583968. Copy/paste from @mdo s comment which describes the situation:

---

I think we need to ditch these built-in `map-merge`s for regular Sass maps. It now feels over-engineered, and perhaps poorly documented for how folks can customize things.

With the usage of `map-merge` everywhere, we have the ability to easily add key-value pairs, but not to remove them. There's no option in Sass to do this, but you can replace a value or add new ones (with `map-merge`). This is an issue because if you want fewer key-value pairs in a Sass map, you'll see errors like those of https://github.com/twbs/bootstrap/issues/27927#issuecomment-450060013.

So, what if we remove all `map-merge` in our variables?

Let's consider an example where we look at our `$grid-breakpoints`.

```scss
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;
```

To replace all of the values, we redefine the keys' values:

```scss
$grid-breakpoints: (
  xs: 0,
  sm: 400px,
  md: 800px,
  lg: 1200px,
  xl: 1600px
);
```

To replace individual key-value pairs, we use `map-merge`:

```scss
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;

$grid-breakpoints: map-merge($grid-breakpoints, (xl: 1600px));
```

To add additional values, we also use `map-merge`:

```scss
$grid-breakpoints: map-merge(
  $grid-breakpoints,
  (
    xxl: 1600px,
    xxxl: 1800px
  )
);
```

To do a bit of everything, we can use replace the default values and use multiple `map-merge`s:

```scss
$grid-breakpoints: (
  xs: 300px,
  sm: 500px,
  md: 800px,
  lg: 1100px,
  xl: 1400px
);
$grid-breakpoints: map-merge(
  (
    xxs: 0
  ),
  $grid-breakpoints
);
$grid-breakpoints: map-merge(
  $grid-breakpoints,
  (
    xxl: 1600px,
    xxxl: 1800px
  )
);
```

**You can [see all of this in this Sassmeister gist](https://www.sassmeister.com/gist/245cd80c5efd1ed77ade9e2a6b322a08).**

**Comment by rupasix** [comment]
I came late but just started to be interested in the new version of the bootstrap. By removing the map-merge, we lose the ability to add new items without recreating the entire network of variable dependencies. For example: if I want to add $nicecolor to $theme-colors, I can't do it without copying colors and grays from original variables.scss. So, minimal configuration in my _variables.scss for that one additional color is:
```
$blue:    #0d6efd !default;
$indigo:  #6610f2 !default;
$purple:  #6f42c1 !default;
$pink:    #d63384 !default;
$red:     #dc3545 !default;
$orange:  #fd7e14 !default;
$yellow:  #ffc107 !default;
$green:   #198754 !default;
$teal:    #20c997 !default;
$cyan:    #0dcaf0 !default;

$white:    #fff !default;
$gray-100: #f8f9fa !default;
$gray-200: #e9ecef !default;
$gray-300: #dee2e6 !default;
$gray-400: #ced4da !default;
$gray-500: #adb5bd !default;
$gray-600: #6c757d !default;
$gray-700: #495057 !default;
$gray-800: #343a40 !default;
$gray-900: #212529 !default;
$black:    #000 !default;

$nicecolor: pink;

$theme-colors: (
  "primary":    $primary,
  "secondary":  $secondary,
  "success":    $success,
  "info":       $info,
  "warning":    $warning,
  "danger":     $danger,
  "light":      $light,
  "dark":       $dark,
  "nicecolor":  $nicecolor
);
```

Is this price you want to pay to remove values easily or just an oversight?
