### ISSUE TITLE
Can't make .d-none elements visible

### ISSUE THREAD

**Issue by RomainSanchez** [twbs/bootstrap#28507]
As the d-none class is applied "display: none !important" modifying the style of the element with vanilla js or jQuery can't work.

Bootstrap 4.1.3

jQuery 3.3.1

Pen: https://codepen.io/anon/pen/gEvGjP?&editable=true

**Comment by Johann-S** [comment]
You should remove the class `.d-none` with jQuery or Vanilla JS
```js
// jQuery
$('p').removeClass('d-none')

// Vanilla JS
document.querySelector('p').classList.remove('d-none')
