### ISSUE TITLE
Carousel Current Items Providing Wrong Index

### ISSUE THREAD

**Issue by naimurhasan** [twbs/bootstrap#28509]
I have created a carousel slide and i need to animate different styles based on current slide number. 

`$("#carouselSliderWithIndicator").on('slide.bs.carousel', function(evt) {
 slideNumber  = $(this).find('.active').index();
})`

This code works well when slide change autometically.

But if I click on the previous Indicators `$("#carouselSliderWithIndicator").on('slide.bs.carousel', function(evt) {})` this function **always output the next number** only on slide changes not the real current index number.
Though I solved it with onclick indicators. Doing the animation first checking if the slide changes with indicator click or just auto. If it's indicator click then i do animation with counting that number of indicator.

**Comment by patrickhlauke** [comment]
Please ask on StackOverflow or similar. This isn't the place for "how to" type questions. See https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md
