### ISSUE TITLE
Validation icons position problem

### ISSUE THREAD

**Issue by Webotvorba** [twbs/bootstrap#28526]
I have just updated to v4.3.1 I am importing bootstrap scss in my scss and I noticed the X icon is at the far right corner and the css is wrongly compiled. I see in comment that I am suing 4.3.1 bootstrap but at docs there is this css rule:

`background-position: center right calc(.375em + .1875rem);`

but my compiled version is: `background-position: 100% calc(.375em + .1875rem);`

![GitHub Logo](https://uc5a5b17fb53e272f49a279abc55.previews.dropboxusercontent.com/p/thumb/AAVkPC2qdS4IpdJ0fd-xDXMblx67FxQPxzayEvDfgsUBL4EXtf-OeLRPXRP2Ak4tTbZUpo1Kj6x6mfWIhI_5BS7XSPuXi0b9gvRfuPsRgrHyAHYmt-glg2dAsaP85UfAsG76qKbqf6MHfSW3xdV_yXUExBxSvmbI_f7Ae41MY595baV-WUUt32QgO-aR_ceZlBI7sQ8bFaReTYgavzUrcxVrmbVyphgjfjHTQA4vWFoKHOQlqR9Erid69pHyIspnxAZPXt9CHfYC_0U6oEjghJqdVI1J7LAkGeDaSv3TivNk4Ieu9qYyt1sNKiAh_p_mvTaFktoKiceYXfrkf9f7RWoypZCX82oRajj-BMwh3NU4LLKKLJWhCmC9vnFRTFOXx6hi8cxpxKSWnydm_un4OxsagZLjoyEGU4KZXQIOi1_7ow/p.png?size_mode=5)

**Comment by tpetry** [comment]
Same problem for me but i can add more context:

Everything is correct when doing development builds with `sass`, but production builds do have the wrong css rule as outlined by Webotvorba.

**Comment by mdo** [comment]
Without a demo, can't help. https://getbootstrap.com/docs/4.3/components/forms/#validation shows the icons as intended.

**Comment by DesertCat** [comment]
It is known problem with cssnano minifier used in [Optimize CSS Assets Webpack Plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) : 
https://github.com/cssnano/cssnano/issues/712

**Comment by eckdanny** [comment]
@Webotvorba 

I too just ran into this on `v4.3.1`. https://github.com/twbs/bootstrap/pull/28814 fixes for me on `node-sass@4.12.0`. npm still at `4.3.1` atm.
