### ISSUE TITLE
Official checkbox in list or menu item

### ISSUE THREAD

**Issue by dragontheory** [twbs/bootstrap#28524]
Is there an official/sanctioned/blessed/Bootstrap best practices solution for having checkboxes (natural or custom) in a menu like list of items, wrapped in a collapsible drop down (see screen shot)? Clicking anywhere on the item toggles the checkbox. There are various implementations around but all seem a bit kludgy and bloated - including mine that stuffs everything in the checkbox label to preserve their click relationship. 

[https://jsfiddle.net/dragontheory/78aj5dhr/](https://jsfiddle.net/dragontheory/78aj5dhr/)

Is it possible to create a **new feature** that demonstrates best practices for implementation? Any guidance would be appreciated. Thank you!

BTW, your hard work has improved UX for millions of users. No pressure! Doing great!

![checkbox_radio_btn_example_01](https://user-images.githubusercontent.com/80736/54556565-81e61000-498f-11e9-88b6-79c266e8e20f.jpg)

**Comment by tyrex1975** [comment]
Can't provide any helpful response, but just wanted to say that your own solution works really well, so thank you for sharing 👍
