### ISSUE TITLE
Popopver Sanitizer accepting HREF with javascipt

### ISSUE THREAD

**Issue by emage** [twbs/bootstrap#28529]
Code pen: https://codepen.io/Emage/pen/gEdbOp

with just the 'javascript' handler: https://codepen.io/Emage/pen/vPzxGB

The first and third link has the normal HREF so it's ok, however, the 2nd link has a javascript to open the tools in a popup window.  In this case, the HREF is scrubbed.

Anyway around this?

Thanks

**Comment by Johann-S** [comment]
Hi @emage,

Yes by default we remove the use of `javascript:` in an `href` attribute.
There is different workaround for that, you can add a `onClick` attribute, or you can use event delegation to handle that.

```html
<a href="#" onClick="PopupWindow(color.aspx?finishes=1,Colors,900,650,null)"></a>
```
If you use that solution, be sure to allow the `onClick` attribute.

with event delegation:

```js
$(document).on('click', '.media a', function (e) {
  e.preventDefault()
  PopupWindow(color.aspx?finishes=1,Colors,900,650,null)
})
```

BTW, if it's you who chose your popover content and template, you can also disable the sanitizer.

I hope it'll help you 👍

**Comment by emage** [comment]
@Johann-S 
Thank you for the work around solution.  Yes, we do control all of our popover content.  Currently I am using the recommended option to disabled it entirely using the DOMPurify in the documentation. Just not working as intended so far.  If you have a way disabled it entirely - that would be great.
Thanks,

**Comment by Johann-S** [comment]
To disable totally the sanitizer you just have to pass the `sanitize` option at false 👍

**Comment by emage** [comment]
@Johann-S 

Thanks.  Ya i was trying to do so at a more global level where I didnt have to go into each component and make the "data-sanitize="false" or into scripts to add the options.  We have these scatter throughout our sites.

**Comment by Johann-S** [comment]
$.fn.tooltip.Constructor.Default.sanitize = false

Should do the trick

**Comment by emage** [comment]
@Johann-S 

code pen: https://codepen.io/Emage/pen/ZPmMbB

I'm missing something?

**Comment by emage** [comment]
@Johann-S 

I needed to change the 'tooltip' to 'popover'.  All works now

This saved me a lot of searching .

Thanks!!!
