### ISSUE TITLE
sanitizer.js has issues on IE11

### ISSUE THREAD

**Issue by lekoala** [twbs/bootstrap#28520]
I have the following js error (IE11 - Win10)

TOOLTIP: Option "sanitizeFn" provided type "window" but expected type "(null|function)".

I think it's due to the change for XSS, it only happens on bootstrap 4.3.1, not 4.2.x

**Comment by Johann-S** [comment]
I @lekoala I cannot reproduce that error, can you share a reduce test case on CodePen or JSFiddle ?

**Comment by lekoala** [comment]
@Johann-S well, as far as I can tell, neither CodePen or JSFiddle support IE11 anymore, which is fair in a modern world but doesn't help me showing what's wrong. It's not happening on 4.3.0 either, so it's has to do with 4.3.1. 

So in order to test I made a simple html file. It works out of the box, but as soon as I add polyfill.io it doesn't work anymore. I also checked if it was due to the use of deferred scripts, but it's not the case, it seems really linked to polyfill.io and bootstrap 4.3.1.

So here is the test case

```
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Bootstrap 4 Tooltip Issue IE11</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" defer="defer" type="application/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js" defer="defer" type="application/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.0/js.cookie.min.js" defer="defer" type="application/javascript"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js" defer="defer" type="application/javascript"></script>
</head>


<body>

    <div class="container">
        <a href="#" id="tt-link" data-toggle="tooltip" title="Hooray!" style="">Hover over me</a>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function(){
            $('[data-toggle="tooltip"]').tooltip();
        }, false);

    </script>
</body>

</html>
```

**Comment by Johann-S** [comment]
Ok so I created a CodePen with your code, and what I see it's if I remove Polyfill.io everything works fine on IE 11 see: https://s.codepen.io/Johann-S/debug/zbaJPV on IE 11

Maybe you should be more restrictive on what you need to polyfill, but here it seems it's note related to Bootstrap.

**Comment by lekoala** [comment]
yes, when removing polyfill.io it works fine. The strange thing is that if you try with Bootstrap 4.3.0 and polyfill.io it works fine! I'm not sure it's a good thing that bootstrap breaks on a minor upgrade for people relying on polyfill.io (for browser as such as IE11, which need them).
so it has to do with a change between 4.3.0 and 4.3.1.

**Comment by XhmikosR** [comment]
Please try to pinpoint which polyfill exactly is causing this.

While 4.3.1 a minor release, due to the security fixes, it was known it could break some things. And we can't exactly know all the use cases out there.

So, let's try and pinpoint what exactly is causing this and we'll how to proceed.

**Comment by lekoala** [comment]
well i know that it is from the es6 bundle, not sure which polyfill though as there are many! i've opened an issue on polyfill.io tracker as well.

**Comment by XhmikosR** [comment]
Cool, let us know if you have any results.

**Comment by fullygit** [comment]
https://github.com/fullygit/fullygit

**Comment by adamwinn** [comment]
I have this same issue also

**Comment by adamwinn** [comment]
I have narrowed it down to the `Array.from` bundle

**Comment by adamwinn** [comment]
The polyfill I'm using is `https://cdn.polyfill.io/v3/polyfill.js?features=Object.assign,Array.from,Element.prototype.matches,Object.entries,Array.prototype.includes`

Breaks:
`https://cdn.polyfill.io/v3/polyfill.js?features=Object.assign,Array.from,Element.prototype.matches,Object.entries,Array.prototype.includes`

Works:
`https://cdn.polyfill.io/v3/polyfill.js?features=Object.assign,Element.prototype.matches,Object.entries,Array.prototype.includes`

**Comment by XhmikosR** [comment]
@adamwinn: you should mention this to the referenced upstream issue, not here.

**Comment by EamonNerbonne** [comment]
I'm running into this too, but I'm not so sure the bug is in the polyfill:  Array.from seems to work fine using the polyfill.  Perhaps sanitizeFn is feature detecting on Array.from, and assuming if that's available, that it's dealing with a modern browser that also has other features?

**Comment by EamonNerbonne** [comment]
Ok, so it does turn out to be the polyfill, but it's the Symbol polyfill, weirdly enough; see https://github.com/Financial-Times/polyfill-library/issues/164 for details and a temporary workaround until the issue is fixed.

**Comment by XhmikosR** [comment]
@EamonNerbonne: thanks for the debugging and the upstream PR!

I'm going to close this issue since we have now confirmed it's an upstream issue.

**Comment by EamonNerbonne** [comment]
Upstream issue resolved.
