### ISSUE TITLE
输入框和modal结合之后出现的bug

### ISSUE THREAD

**Issue by YuFy1314** [twbs/bootstrap#28531]
Operating environment: windows 7操作系统, chrome浏览器
technology: nw.js, Vue, bootstrap v3.3.7
在无论是input或是textarea中, 从后台回显的数据, 再修改里面的数据, 先将里面的数据全部选中, 退格删除之后点击模态框之外的页面, 需要点击两次才可以将模态框关闭, 这是为什么?
如果是将输入框中的数据正常退格删除或是选中不全删的话, 再点击模态框外面就可以正常触发hidden.bs.modal关闭模态框.

**Comment by newyhj** [comment]
哥们，用英文！

**Comment by mdo** [comment]
We're not actively developing v3.x, so closing as a won't fix.
