### ISSUE TITLE
Buttons don't work in popover content

### ISSUE THREAD

**Issue by shaneparsons** [twbs/bootstrap#28533]
I wasn't able to find this issue documented anywhere, but buttons break popover content. See [here](http://jsfiddle.net/k49guq1y/) for an example. This happens in all browsers.

**Comment by jipexu** [comment]
Hi
please read :  https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer

button are not in white list ..

**Comment by shaneparsons** [comment]
Ah right on, I guess I missed that. Thanks!
