### ISSUE TITLE
Form-control class enclosing Radio buttons works for 4.0.0, but not 4.3.1

### ISSUE THREAD

**Issue by wvwhome** [twbs/bootstrap#28537]
The Form-control class enclosing Radio buttons works for 4.0.0, but not 4.3.1.  Examples below.
This happens with Safari, Chrome, Firefox, or Edge browsers.

Bootstrap 4.0.0 example that works enclosing both radio buttons in the unordered list:

https://www.w3schools.com/code/tryit.asp?filename=G2APVTL2QLWX

Bootstrap 4.3.1

https://www.w3schools.com/code/tryit.asp?filename=G20XJHKPDKNJ

WTForms 2.2 Radiofield expands to unordered lists.
The border class is my work-around.

**Comment by Lausselloic** [comment]
You are perveting `form-control` class used only for ìnput tag in bootstrap to create a visual wired fieldset.

I don't know how radio buttons are vocalized with an assistive tool but looks strange to include them in a list element.

By the way you could pervert `form-control` till the end by adding the class ` h-auto` in to the `form-control` element. Here's what it could looks like : https://www.w3schools.com/code/tryit.asp?filename=G2FNXK1K2GWW

**Comment by mdo** [comment]
Radio buttons are working as intended in v4.3.1—please use the markup that's shown in our docs.
