### ISSUE TITLE
Configure the theme with css variables

### ISSUE THREAD

**Issue by ardiadrianadri** [twbs/bootstrap#28547]
I'm trying to overwrite the bootstrap variables to create my own color theme but it is not working...

To be more exactly I was trying to change the value of ```---primary``` to ```purple``` in that way:

```
.page-footer {
    --primary: purple;
}
```

Searching, in the bootstrap code, the reason because it did not work, I found this in the dist css files:
```
.bg-primary {
  background-color: #007bff !important;
}
```

Which is generated by this sass code:
```
@each $color, $value in $theme-colors {
  .bg-#{$color} {
    background-color: $value !important;
  }
}
```

The question that comes at my mind is why the bootstrap sass is not generated using the css variables. Something like this:
```
@each $color, $value in $theme-colors {
  .bg-#{$color} {
    background-color: var(--#{$color},#{$value}) !important;
  }
}
```

**Comment by asyncdesign** [comment]
I think the idea is to generate the final colors you want in your own custom Bootstrap build, rather than generate a new set of variables. Import what your need for your projects from Bootstrap into your own custom SASS file, then build that.

**Comment by ardiadrianadri** [comment]
Thank you for your answer @asyncdesign and probably you have right. The main idea is to compile you own version of bootstrap using sass but there are two points that I think are quite important about this issue:

1. **To give more value at the work already done**:
  I mean... the bootstrap.css has the next lines:
```
:root {
  --blue: #007bff;
  --indigo: #6610f2;
  --purple: #6f42c1;
  --pink: #e83e8c;
  --red: #dc3545;
  --orange: #fd7e14;
  --yellow: #ffc107;
  --green: #28a745;
  --teal: #20c997;
  --cyan: #17a2b8;
  --white: #fff;
  --gray: #6c757d;
  --gray-dark: #343a40;
  --primary: #007bff;
  --secondary: #6c757d;
  --success: #28a745;
  --info: #17a2b8;
  --warning: #ffc107;
  --danger: #dc3545;
  --light: #f8f9fa;
  --dark: #343a40;
  --breakpoint-xs: 0;
  --breakpoint-sm: 576px;
  --breakpoint-md: 768px;
  --breakpoint-lg: 992px;
  --breakpoint-xl: 1200px;
  --font-family-sans-serif: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
```
Which is amazing because it makes it easy to reuse the styles defined by bootstrap in your own styles. However, the fact that overwriting these variables has no effect on web styles eliminates the versatility that css variables give. It feels like only half the work was done.

2. **It makes hard to customize the bootstrap style when you are using CDN link**:
The easiest way to use bootstrap is through the CDN link. However, changing the colors with the CDN link is difficult and you have to use the "important" rule to overwrite it. The "important" rule is not a good thing. This makes difficult to reuse styles in different parts of a web application. On the other hand, what is the point of publishing a CDN link to use a style framework that can not be easily adapted? If everyone has to download the source code of the framework to compile it, in the end, what will happen is that no one will use the CDN link ...so... what is the reason for having it?

**Comment by mdo** [comment]
Way too much to get into here, but utilities are designed with the important flag in mind. Bootstrap is built and compiled from Sass, so there’s little to no benefit for us to optimize around CSS custom properties at this point in time given supported browsers.

Sometime soon, perhaps, but until then, the limited CSS variables we include are there for some small conveniences and nothing more.
