### ISSUE TITLE
Firefox print (and preview) problem with card and table (flex problem)

### ISSUE THREAD

**Issue by slolo2000** [twbs/bootstrap#28545]
Hello,

I am not sure if the problem is on the Bootstrap 4.3.1 or in Firefox but the printing and preview printing is truncated (only one page in printed or previewed) if a long table is contained in a Card component.

You can see a simple example on jsbin here: [link to example](https://jsbin.com/veyetanise/edit?html,output)

For information, it works well on Chrome and Edge.
The problem seems to be due to display:flex on div element.

The way to avoid this problem is to add in your stylesheet:
```
@media print {
	div.card {
	  display: block !important;
	}
}
```

Operating system and version:
Windows 10 (version 1809)
**Firefox 66 : not working**
Google 73.0.3683.86 : Work well
Microsoft Edge 11 : Work well

**Comment by mdo** [comment]
Closing as a stale won't fix—v5 drops the bulk of our print styles.
