### ISSUE TITLE
Navbar Collapse Toggle Styles

### ISSUE THREAD

**Issue by hashnimmo** [twbs/bootstrap#28548]
Right now there is only 1 collapse style which collapses down from the navbar. Can you add more default styles like off canvas slide, push and reveal effects into the next release so it would be much easier for noobs like me to design webpages.

I have found this, but I kinda feel like it would be better if this feature comes from the Bootstrap devs themselves; http://www.jasny.net/bootstrap/components/#offcanvas

Any reason why these features weren't included in the release?

**Comment by mdo** [comment]
Plenty of existing issues for this, closing as a dupe. Reason they haven’t been included is the core team hasn’t built it yet or picked a direction yet.
