### ISSUE TITLE
dropdown menu can't be open on one click.

### ISSUE THREAD

**Issue by mehulRojasara** [twbs/bootstrap#28542]
- Windows, macOS, Android, iOS
- Chrome, Firefox, Safari, MS Edge
- jQuery version : 3.3.1
- Bootstrap version : 4.3.1

[codepen](https://codepen.io/Mehul_Rojasara/pen/gEBYjv) 

when i refresh the page first time it only focus the button, not open the dropdown-menu, after first click you can open this as it was before.

**Comment by Lausselloic** [comment]
Hello,

Yes dropdown requires "popper.js" https://getbootstrap.com/docs/4.3/components/dropdowns/#overview

```
Dropdowns are built on a third party library, Popper.js, which provides dynamic positioning and viewport detection. Be sure to include popper.min.js before Bootstrap’s JavaScript or use bootstrap.bundle.min.js / bootstrap.bundle.js which contains Popper.js. Popper.js isn’t used to position dropdowns in navbars though as dynamic positioning isn’t required.
```

So in your codepen, load only the bundle and not both bootstrap.js and bootstrap.bundle https://codepen.io/anon/pen/MxZWRw

**Comment by mehulRojasara** [comment]
Thank you so much it working now...

Thanks for solving my issue and also improve my understanding on the same, i was pointing bundle file as separate file then bootstrap.js, so that i use both of them , now it clear to me 

##Tanks

**Comment by moxuanyuan** [comment]
Dropdowns  use " Popper.js" but navbar dropdown not use....
