### ISSUE TITLE
Inputs are removed from HTML popovers

### ISSUE THREAD

**Issue by rvfx** [twbs/bootstrap#28555]
In Bootstrap 4.3.x input fields are removed from HTML popovers.
[Here is a working example. (CodePen)](https://codepen.io/foxpen/pen/wOOZYN)

This is the defined popover content:
```
<div class=&quot;alert alert-info&quot;>Before the input</div>
<input type=&quot;text&quot; name=&quot;test_input&quot; value=&quot;Test value&quot; />
<div class=&quot;alert alert-info&quot;>After the input</div>
```
The input field isn't even in the popover HTML:
```
<div class="popover-body">
  <div class="alert alert-info">Before the input</div>
  <div class="alert alert-info">After the input</div>
</div>
```

**Comment by Lausselloic** [comment]
Yes a sanitizer has been added : 
You could whitelist what you need so if you need to whitelist those elements you're free to do it using: https://getbootstrap.com/docs/4/3/javascript/#js-sanitizer

**Comment by rvfx** [comment]
Thank you!
