### ISSUE TITLE
Modals Broken if ID is Numeric

### ISSUE THREAD

**Issue by derekws** [twbs/bootstrap#28559]
With nothing but the starter template and modal example code, the modal works fine until I change the id to a number:

https://jsbin.com/danesor/1/edit?html,output

**Comment by Johann-S** [comment]
That's right, you have to use valid selectors see:
 - https://getbootstrap.com/docs/4.3/getting-started/javascript/#selectors
 - https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier
