### ISSUE TITLE
Classes to control gutters sizes

### ISSUE THREAD

**Issue by Seb33300** [twbs/bootstrap#28550]
Actually, when we use the grid system, we only have 2 ways to manage columns gutters:
- use the default gutters size
- use the `.no-gutters` class to remove gutters

I would like to suggest adding new gutters utility classes in the same way of padding and margin classes to manage gutters spacing: `.gutters-0`, `.gutters-1`, `.gutters-2`, etc...

**Comment by mdo** [comment]
We added negative margin utilities a couple releases ago to pair with padding classes so that this can be accomplished. Check our docs and blog posts for examples.
