### ISSUE TITLE
IE11 CSS columns + form-check-input

### ISSUE THREAD

**Issue by PatrickRose** [twbs/bootstrap#28568]
- Operating system and version: Windows (via browserstack)
- Browser and version IE11
- Reduced test case: https://jsfiddle.net/2ze6a4h3

In IE11, using the CSS columns property for a wrapping element for a group of checkboxes and `form-check-input` for each of the input and `form-check-label` for each of the labels means that at the bottom of the column the label is moved to the top of the next column, but the input stays at the bottom. This doesn't seem to happen in Chrome 72.

Removing the `position: absolute` from the `form-check-input` rule fixes the problem on IE11 but makes it look strange in non-IE

**Comment by ysds** [comment]
Can you reproduce it with Bootstrap v4.3.1?

**Comment by PatrickRose** [comment]
Yes (updated the fiddle to be https://jsfiddle.net/kat3rbud/1/ which makes sure it's loading 4.3.1)

**Comment by mdo** [comment]
Add `break-inside: avoid` to your CSS for the `.form-check`.
