### ISSUE TITLE
Sizing utilities relative to the viewport not present

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#28563]
According to the docs:

> Relative to the viewport
> You can also use utilities to set the width and height relative to the viewport.

However, when using the class `vh-25`, there appears to be no styles associated with it (or any variation of `vh-*`.

**Comment by mdo** [comment]
There are only four supported classes for that as shown in the docs.

**Comment by leecollings** [comment]
Then add them in.... Pretty obvious
