### ISSUE TITLE
File browser plugin does not show file name when pressing back button in browser

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#28560]
Bug reports must include:

- Operating system and version Windows 10
- Browser and version: Chrome current

Steps to reproduce:
1. Submit a form with a file browser field
2. On the following page press the back button in the browser
3. Observe the file browser field:
3.1. The file is still selected - yep
3.2 The file is still shown in the tooltip - yep
3.3 The file name is displayed - nope.

3.3 should be fixed :-)

I hope this is the right location to report this...according to the docs it is the recommended plugin, so I hope I'm right here.

Best regards,
D.R.

**Comment by Johann-S** [comment]
@drauch I think it's more related to this repository: https://github.com/Johann-S/bs-custom-file-input

**Comment by drauch** [comment]
Ok, if somebody finds this via Google -> here is the follow-up issue: https://github.com/Johann-S/bs-custom-file-input/issues/43
