### ISSUE TITLE
SASS compile error on 4.3.1 

### ISSUE THREAD

**Issue by xshiiiidev** [twbs/bootstrap#28566]
So I was trying to compile the bootstrap _variables.scss on version 4.3.1 and I got this error

> Error: $color: theme-color("primary") is not a color.
> $link-hover-color:                        darken($link-color, 15%) !default;

**Comment by XhmikosR** [comment]
This seems like a configuration on your side, but we need to see how you load bootstrap and everything related so we need more info.

**Comment by MartijnCuppens** [comment]
The `theme-color()` function is defined in `scss/functions.scss`. Make sure that file is imported before using the function.
