### ISSUE TITLE
dropdown menu isn't not ontop of sticky div

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#28569]
There's an issue in the current release where the z-index values of dropdown menus and sticky-top items are round the wrong way.

The current behaviour makes any sticky divs appear ontop of active dropdown menus, which is not correct.

The following should be applied (I'm not sure how to create pull requests for BS, because it needing to be compiled, I didn' t just want to create a PR for the distributed CSS file).

```
.sticky-top {
    z-index:5;
}
```

**Comment by mdo** [comment]
This sounds about right—our z-index is documented and covered in our docs. https://getbootstrap.com/docs/4.3/layout/overview/#z-index

**Comment by leecollings** [comment]
No, don't close it! Why do you do this!? You need to STOP thinking you're GOD of the world, and actually listen to people when they come to you with issues for your bugged code.

You clearly haven't understood the issue. I've even told you how to fix it. Please re-read what I said.
