### ISSUE TITLE
Proposal: .is-warning / .is-half-valid

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#28578]
Bootstrap have the `.is-valid` and `.is-invalid` classes for form input controls. ([docs](https://getbootstrap.com/docs/4.3/components/forms/#server-side))

These two classes can be used to mark an input as either valid or invalid.
We could take into consideration the addition of a `.is-warning` class (or `is-half-valid`, or `is-suspicious`?) with a yellow border.

### Preview
![image](https://user-images.githubusercontent.com/10222521/55277070-33743200-52fc-11e9-92dd-9ca6532de99f.png)

## Live demo
https://jsfiddle.net/4o8c0bxy/

### Use cases
- URL starts with http:// instead of https://. 🔒
- Password could arguably be considered less than sufficiently strong. 💪
- "3.14159", decimal precision will be lost.
- Date coincidences with full moon. 🌕
- Whoa! That's a hefty donation, are you drunk? 🥴
- Email address is syntactically valid but mail delivery bounced. 📧
- Encoding at less than 96 kbit/s could result in significant quality loss.
- MD5 is insecure and should only be used for legacy applications.
- Travel destination requires you to pay a highway toll. 🛣️
- Speed at or exceeding 88 mph might result in time travel.

**Comment by sts-ryan-holton** [comment]
Pretty cool idea

**Comment by myorangeca** [comment]
This could be easily done via scripts, I don't see the need to bloat BS CSS for this. Usually with errors, its either true or false, there is no in between...

**Comment by knoobie** [comment]
This is already possible, see https://github.com/twbs/bootstrap/issues/28380

**Comment by mdo** [comment]
Been covered before—no plans for adding this by default. There's no semantic equivalent.

**Comment by vanillajonathan** [comment]
@myorangeca The backend or a JavaScript could add ´.border-warning` to the input, but it would not get the yellow focus glow unless there were any CSS additions.
