### ISSUE TITLE
Card columns do not align correctly

### ISSUE THREAD

**Issue by smarek** [twbs/bootstrap#28572]
Example of ill behavior
https://jsfiddle.net/L0bawmf2/

No custom css or js, tested with Linux Chrome 

75

Cards, depending on window width, align as 2x2, 3+1-aligned-right, 3+1-aligned-left

Screenshots as follows

1st
![2019-03-29-073208_1044x453_scrot](https://user-images.githubusercontent.com/384824/55213817-d6da1f80-51f4-11e9-935c-c887e16ff759.png)
2nd
![2019-03-29-073225_625x493_scrot](https://user-images.githubusercontent.com/384824/55213818-d8a3e300-51f4-11e9-83b4-c579b51cf278.png)
3rd
![2019-03-29-073236_773x539_scrot](https://user-images.githubusercontent.com/384824/55213822-da6da680-51f4-11e9-8fc1-5e25a791445b.png)

**Comment by nandaleite** [comment]
This is the expected behavior of ```.card-columns``` - cards will be organized into Masonry-like columns, by placing elements in optimal position based on available vertical space.

You could try ```.cards-group```  to render cards as a single, attached element with equal width and height columns, or ```.cards-deck``` if you need a set of equal width and height cards that aren’t attached to one another.

**Comment by smarek** [comment]
ok, that is little confusing, because of columns i'd expect the items to overflow on the next row in LTR/RTL manner, instead the elements are placed in various places depending on browser implementation of masonry (or whatever the correct term is)

Basically I like the way the .card-columns behave generally, with large amount of cards, however with small amount of cards or data expected to be in cols/rows more in table-manner, it does confuse one.

`.card-deck` does not create columns, 6 cards will try to stuck all to one row

I was hoping for solution, that would create (even non-equal-height) blocks in number of columns, depending on the screen size, ie. 4 for lg, 3 for md, 2 for sm and 1 for xs. I seek css only solution, without need to place additional html elements to break the rows.

What could imho be naively implemented by using `float:left` and element size based on screen size, could be probably better implemented with some, to me unknown, bootstrap provided class

**Comment by mdo** [comment]
We know it's not the best solution, which is why the shortcomings are documented at https://getbootstrap.com/docs/4.3/components/card/#card-columns. Regrettably, not much we can do about this in v4—may be able to explore alternatives in v5.
