### ISSUE TITLE
dropdown inside other dropdown

### ISSUE THREAD

**Issue by claudioalmeiida** [twbs/bootstrap#28571]
I do not know if it is a bug or if it is not possible, my question is, I would like to set up a dropdown menu, but inside it I need another dropdown (the red button in the example), but the default behavior of the dropdown is always to have only one Open.

My question, is it possible for me to do this somehow? Thank you.

Example code, I left one fixed for you to see what my need is.
https://codepen.io/claudioalmeiida/pen/LawQQb

![image](https://user-images.githubusercontent.com/942899/55203553-3a872d00-51a2-11e9-88c6-ceb5e650510b.png)

**Comment by Lausselloic** [comment]
yes you could replace the first dropdown by a collapse instead : https://codepen.io/lausselloic/pen/ywmZeQ

**Comment by claudioalmeiida** [comment]
but there is not a dropdown inside another

**Comment by herbalite** [comment]
That's tricky. Using Javascript you'd have to cancel the hide.bs.dropdown event, in case the show.bs.dropdown has been called from the inner dropdown.

**Comment by mdo** [comment]
Not supported currently, by design.
