### ISSUE TITLE
White gaps in modals because of border radius

### ISSUE THREAD

**Issue by sstativa** [twbs/bootstrap#28585]
This is not critical and easy to fix but I suppose it should work right out of the box.

If you set a dark background color to the `modal-header` there will be white space between the border of `mobile-content` and `modal-header`. 

This is a zoomed example:
<img width="455" alt="Screen Shot 2019-04-01 at 17 18 24" src="https://user-images.githubusercontent.com/3362679/55307642-ddda8980-54a3-11e9-95bc-ecd333b3d0b9.png">

There are several options to fix but I'm not sure which one is the best.

For now, I use this "fix" 
```
.modal-content {
  overflow: hidden;
}

.modal-header {
  border-radius: 0;
}
```

**Comment by ysds** [comment]
A solution to that issue is to add `$modal-inner-border-radius` like `.popover-header` or `.card-header`. But we don't have a variable to change the background color of the `.modal-header` or `.modal-footer`.

@twbs/team That customize is beyond the scope of our support? Or should we support?

**Comment by MartijnCuppens** [comment]
I think we can tweak the modals a bit more to support colored modal footers and headers. `overflow: hidden` might simplify things a lot for us I guess.
