### ISSUE TITLE
Sizings as maps

### ISSUE THREAD

**Issue by ray73864** [twbs/bootstrap#28584]
Not really sure how to word this one, and I realise this could be done via a separate CSS file, it just looks cleaner if it is in the Bootstrap SASS stuff.

Anyway, on to it.

It would be nice if the various different sizing classes were defined in a SASS map (eg. Button sizes, Modal sizes, etc...).

Currently the only way to add additional sizes is to use a separate CSS file, what I would find handy is being able to define the new size in a sass map that BS then uses to create its own CSS files.

Currently there are sizes for buttons that are 'sm' and 'lg' and modals that go 'sm, md, lg, and xlg', but what I find myself often needing are buttons that go right down to 'xs' and modals that can go larger than 1140px (I currently have a modal size for 1600px).

With a sass map, I could just do:

$modal-sizes: map-merge(
  (
    "xxlg": "1600px"
  ),
  $modal-sizes
);

Recompile and my new modal size would be available, without having to inspect an existing modal to work out how to define the CSS style.

**Comment by mdo** [comment]
This isn't the route we'll be going in v5, but thanks for the input! Please explore the open PRs that refer to our maps and more.
