### ISSUE TITLE
iPhone X landscape works XS Max and XR not

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap#28597]
Hi,
Noticed that iPhone X in landscape mode is supported, but iPhone XS Max and iPhone XR not.
Any plans to fix the issues for iPhone?
Regards & Thanks,
David

**Comment by crispycat0** [comment]
I have a simple fix: Don't use iPhone X XD

**Comment by wolfy1339** [comment]
What do you mean by "not supported" and "doesn't work".

Please provide screenshots as well as more detailed explanation as to what doesn't work

**Comment by mdo** [comment]
Nothing planned to change right now. If you have suggestions on how to better support them, I'm happy to hear them.
