### ISSUE TITLE
Spinner in Large Buttons

### ISSUE THREAD

**Issue by codemewell** [twbs/bootstrap#28592]
spinner in large buttons doesn't match a text line.

// --- here's a fix:
.btn-lg span.spinner-border-sm {
  vertical-align: baseline;
}

**Comment by mdo** [comment]
Not every use case can be considered for every component, so it makes sense you may need to optimize things with custom styles or utilities. We do have some alignment utilities that could help here, but if you can provide a live demo of the problem, we can revisit.
