### ISSUE TITLE
carousel fade effect broken after 4.1.3 -> 4.3.1 upgrade

### ISSUE THREAD

**Issue by jakubklimek** [twbs/bootstrap#28599]
- Operating system and version: Windows 10, Android P
- Browser and version: Chrome 73.0.3683.86, Firefox 66.0.2

In 4.3.1, the original state is not fading away, it disappears at once at the end of transition, mixing akwardly with the new content which fades in.
- [Carousel fade in 4.1.3](https://jsbin.com/qubonip/1/edit?html,output) (OK)
- [Carousel fade in 4.3.1](https://jsbin.com/qanejiw/1/edit?html,output) (Broken)

**Comment by Johann-S** [comment]
Not sure it's JS related here 🤔

**Comment by XhmikosR** [comment]
@MartijnCuppens: any ideas? If it's not a markup issue, and we are not missing any FF mobile vendor properties, this could be a bug in the browser.

**Comment by jakubklimek** [comment]
@XhmikosR just to clarify, it is not working in Chrome and Firefox, both mobile and desktop versions.

**Comment by XhmikosR** [comment]
Hmm, then it might be something else like respecting the OS setting to reduce animations maybe?

**Comment by MartijnCuppens** [comment]
@jakubhonisek,

You can add a background (`.bg-white`) to carousel items to fix this: https://jsbin.com/puhuvorohi/1/edit?html,output

We fixed the background of the carousel leaking through while transitioning in `4.2`, you can see the issue in `4.1`:
https://getbootstrap.com/docs/4.1/components/carousel/#crossfade

Current implementation:
https://getbootstrap.com/docs/4.3/components/carousel/#crossfade

That fix was causing this, but this can easily be solved with setting a background.

**Comment by jakubklimek** [comment]
@MartijnCuppens I do not think setting a background will solve this for me. It has a white background only in the minimal example. Live it looks like [this](https://data.gov.cz/) (OK) and [this](https://nkod-test.opendata.cz/) (Broken)

**Comment by jjacobson** [comment]
Running into this issue as well

**Comment by MartijnCuppens** [comment]
We should fix this, but I think we can't find a solution for both cases (fix for transparent slides & prevent background leaks for non-transparent slides). So I guess we'll need 2 types of crossfade carousels to deal with this.

Anyway, to help you guys out for now, by adding these lines you should be fine:
```
.carousel-fade .active.carousel-item-left,
.carousel-fade .active.carousel-item-right {
  transition: .6s opacity ease;
}
/* Disable transitions for if reduced motion is enabled: */
@media (prefers-reduced-motion:reduce) {
  .carousel-fade .active.carousel-item-left,
  .carousel-fade .active.carousel-item-right {
    transition: none;
  }
} 
```

I'll have a look at how this should be fixed in core, I'll probably end up with an additional class to switch between the behaviours.

**Comment by owendswang** [comment]
v4.3.1 carousel not working for me too.
even the effect of the example in the doc is not working too.

**Comment by MartijnCuppens** [comment]
@owendswang:
> The animation effect of this component is dependent on the `prefers-reduced-motion` media query. See the reduced motion section of our accessibility documentation.

See https://getbootstrap.com/docs/4.3/components/carousel/#how-it-works

**Comment by owendswang** [comment]
> 
> 
> @owendswang:
> 
> > The animation effect of this component is dependent on the `prefers-reduced-motion` media query. See the reduced motion section of our accessibility documentation.
> 
> See https://getbootstrap.com/docs/4.3/components/carousel/#how-it-works

Thanks for reply. I think I figured out why it was not working.
Because the new feature: prefers-reduced-motion.
Sorry for buthering.

**Comment by mdo** [comment]
@MartijnCuppens Do you still want us to add a new class for this? Or maybe we add an example to the docs for how to support this?

**Comment by mdo** [comment]
Closing as stale. Happy to revisit in the future if needed.
