### ISSUE TITLE
Alternative to Glyphicons icon font

### ISSUE THREAD

**Issue by imabot2** [twbs/bootstrap#28593]
On these pages :

- https://getbootstrap.com/docs/4.3/extend/icons/#preferred
- https://getbootstrap.com/docs/4.3/migration/#components

I would like to propose a new alternative : [Friconix](https://friconix.com) - https://friconix.com (very similar to Font Awesome, including CDN and fully free).

There is the Bootstrap logo : https://friconix.com/icon/fi-xnsuxl-bootstrap/

Hope this will help.

**Comment by mdo** [comment]
Thanks, we'll consider it!

**Comment by cinqlair** [comment]
Great alternative. It deserves to be known !
