### ISSUE TITLE
Add variables to form-control-plaintext 

### ISSUE THREAD

**Issue by jerchap** [twbs/bootstrap#28596]
Please add variables to the form-control-plaintext class so the background color and borders can be styled through variables.  Similar to how form-control supports more variables.

**Comment by mdo** [comment]
Inclined to skip this given `.form-control-plaintext` is somewhat of an override to the `.form-control` styles—it's not meant to look like anything but plain text. Thoughts @twbs/css-review?

**Comment by patrickhlauke** [comment]
agree with @mdo here. if you wanted it to look more like a control (with background/border), should probably opt for a regular `readonly` input.

can those (without the plaintext) be styled more thoroughly with variables?

**Comment by mdo** [comment]
Closing per last comments.
