### ISSUE TITLE
.dropdown-header padding-y should reference $dropdown-item-padding-y

### ISSUE THREAD

**Issue by k-funk** [twbs/bootstrap#28601]
https://github.com/twbs/bootstrap/blob/master/scss/_dropdown.scss#L179

It seems to me that a `.dropdown-header` should use the y-padding of a dropdown-item (`$dropdown-item-padding-y`), not the dropdown-menu.

The problem I have is that I want to set `$dropdown-padding-y: 0;` for my menus, so that the items are the only thing controlling y-padding within the dropdown. However, this ends up effecting `.dropdown-headers` by putting 0-y padding on them as well.

**Comment by mendozagioo** [comment]
With a new variable it could be set you own padding on `.dropdown-header`
