### ISSUE TITLE
custom checkboxes inside input groups

### ISSUE THREAD

**Issue by claudioalmeiida** [twbs/bootstrap#28603]
You think of allowing custom checkboxes inside input groups, this example is bugged when using `form-control-sm`

https://codepen.io/claudioalmeiida/pen/XQmRYE

![image](https://user-images.githubusercontent.com/942899/55461419-618a9800-55c2-11e9-9f9b-a5d383b89d3e.png)

**Comment by Lausselloic** [comment]
you could play with utilities helper as a fallback : https://codepen.io/lausselloic/pen/PgPKOd

**Comment by tmorehouse** [comment]
We've just suggested using margin utility classes to handle the small input group:

https://bootstrap-vue.js.org/docs/components/input-group#custom-radio-checkbox-and-switch-addons
