### ISSUE TITLE
nav bar items don't align center as per docs

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#28604]
According to https://getbootstrap.com/docs/4.3/components/navs/#horizontal-alignment, you can set nav menus to have centred or right alignment by adding `justify-content-center` or `justify-content-right` to the main `ul` element. However this doesn't seem to have any effect when `navbar-nav` is also used... (toggling the `flex-direction:column` rule switches between centred alignment and left alignment.

**Comment by mdo** [comment]
`.nav` and `.navbar-nav` are different components—the same code won't always work on them both.

**Comment by mdo** [comment]
You can apply `.justify-content-center` to the `.navbar-collapse` to align the content within that, but given the navbar's markup, we're super limited on customizing like that.
