### ISSUE TITLE
Width of Toasts

### ISSUE THREAD

**Issue by db1995** [twbs/bootstrap#28607]
### If close one toast, the **width** of another toast will be changed.
Is it a bug or it doesn't matter？
How to let it unchangeable?
See the example in Bootstrap documents.

![image](https://user-images.githubusercontent.com/34293412/55521612-0d5fe080-56b4-11e9-8d2d-47493018e183.png)

![image](https://user-images.githubusercontent.com/34293412/55521810-ddfda380-56b4-11e9-82b7-afad32ff8600.png)

**Environment:**
- Operating system and version (Windows 10)
- Browser and version (Chrome, Firefox, IE, MS Edge)

**Comment by Johann-S** [comment]
Hi @db1995,

That's because the `<div />` which contains the toasts doesn't have a fixed width 👍
