### ISSUE TITLE
Add mixins for .form-control & addons

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#28605]
We are writing a Bootstrap theme for [select2](https://select2.org/), so that select2 looks like a normal form-control.

For this we had to copy&paste large amounts of SCSS from the `.form-control` class, as well as the `form-control-focus()` mixin (we can't use it, as select2 never gets the `:focus` pseudo-class), the `.form-control:disabled` class, and furthermore the `is-invalid` styling. This is a maintenance hell, as for every Bootstrap minor update we have to go and copy&paste the correct styles again.

It would be nice if you provided mixins for the styles in question. Is this something you would accept a pull request for?

**Comment by MartijnCuppens** [comment]
Hi @drauch,

You should be able to use `@extend .form-control;` in your custom styles, this would also output less css. We are trying to avoid mixins introducing new mixins to theme our components because this makes our code less maintainable.

**Comment by drauch** [comment]
For us using `@extend` is not really an options for two reasons:

1) it is discouraged to use it (e.g., check out https://webinista.com/updates/dont-use-extend-sass/ or https://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/)

2) We can only extend a selector if it is available in the SCSS file, however, we can't include non-mixin non-function/variable-only Bootstrap files as this would duplicate the rules (once included in the web page and once more for every SCSS file which happens to extend something from bootstrap). This would include some of the Bootstrap styles dozens of times into our final CSS.

**Comment by MartijnCuppens** [comment]
The best approach is to add the `.form-control` class to element you want to be themed this would prevent the output of duplicate css. I guess this is possible with select2's API, if not you should ask to implement it on their side.

**Comment by drauch** [comment]
As I told you in my initial post this would not work for :focus, or :disabled

**Comment by MartijnCuppens** [comment]
It does work. I just tested this and the following code was generated:

```
.form-control, .test {
  display: block;
  width: 100%;
  height: calc(1.5em + 0.75rem + 2px);
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

@media (prefers-reduced-motion: reduce) {
  .form-control, .test {
    transition: none;
  }
}

.form-control::-ms-expand, .test::-ms-expand {
  background-color: transparent;
  border: 0;
}

.form-control:focus, .test:focus {
  color: #495057;
  background-color: #fff;
  border-color: #80bdff;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}

.form-control::placeholder, .test::placeholder {
  color: #6c757d;
  opacity: 1;
}

.form-control:disabled, .test:disabled, .form-control[readonly], .test[readonly] {
  background-color: #e9ecef;
  opacity: 1;
}

select.form-control:focus::-ms-value, select.test:focus::-ms-value {
  color: #495057;
  background-color: #fff;
}
```
