### ISSUE TITLE
Auto report in Boostrap with ngrok and chrome extension

### ISSUE THREAD

**Issue by pedroguilhermelima** [twbs/bootstrap#28618]
Hi, how are you?

I do not have much to talk about. But if there is, a pop-up may appear for people who communicate about error. And it already reports without problems Github like 'bug'. I do not know how I would send it to Github with the issues prepared. But, the auto report process could be done like this

**Example**

Reference
https://stackoverflow.com/questions/12407778/connecting-to-tcp-socket-from-browser-using-javascript

```
chrome.experimental.socket.create('tcp', '127.0.0.1', 8080, function(socketInfo) {
  chrome.experimental.socket.connect(socketInfo.socketId, function (result) {
        chrome.experimental.socket.write(socketInfo.socketId, "Hello, world!");         
    });
});
```

`
> ngrok  http 8080 // proxy reverse to localhost

Note 
1. We could create an application. Js that reserves for localhost a reverse proxy .
2. If Bootstrap has a problem ... we can use Google Chrome browser to open a local connection. With this, we tell ngrok to run a reverse proxy with that local connection. 
3. Then you would need a server or use an email API to send this error.

`
Regards,
Pedro Guilherme.

**Comment by pedroguilhermelima** [comment]
_**Note**_
If you want to help build this idea with me, open my repository and we can discuss this idea.

Reference
https://github.com/pedroguilhermelima/bootstrap-autoreport


Regards,
Pedro Guilherme.

**Comment by MartijnCuppens** [comment]
Please stop opening these issues here, @pedroguilhermelima

**Comment by pedroguilhermelima** [comment]
> Please stop opening these issues here, @pedroguilhermelima
Dude, did you get my message? Do you understand what I want done?

**Comment by patrickhlauke** [comment]
> Do you understand what I want done?

you're after some very specific functionality that you want for your specific needs / things you're wanting to build on top of bootstrap, and hoping that these get added directly into bootstrap core. and the general feeling here is that no, these are not things that make sense to be added to bootstrap core, which is just a framework for styling and a few custom interface widgets.

**Comment by pedroguilhermelima** [comment]
Hi, how are you?

 I do not want it for me. I'm happy if it's for everyone. So, look. I'm creating a new way to be used. 

I'm creating bootstrap-business.js to raise money through services to the community. 

I am creating bootstrap-autoreport.js if it gives a problem it will have a reverse proxy to email that problem. And I'm going to create bootstrap-elements.js to help people generate the template as Wix with draggable.js and jquery-context-menu.js. 

These problems and resolutions can help a lot, what's the problem with that?

**Comment by pedroguilhermelima** [comment]
**Note:** I've sent several resolutions to Github and they will or may help the community. Are these


1- Message resource by profile.

2- Popup to talk within the issues. Like a notification with Twitter login.

3- Simulate the actions of several programmers and generate graphs. Use this to alert about empty repositories or users that do not exist.

**Comment by patrickhlauke** [comment]
The point is: fine, feel free to do those things. But there's no interest in adding these to core bootstrap, so there's no point in opening issues here on bootstrap's issue tracker about them.
