### ISSUE TITLE
Generate different and automatic screens 'media queries'

### ISSUE THREAD

**Issue by pedroguilhermelima** [twbs/bootstrap#28617]
Hi, how are you?

**Note**
1. I would like to use this site : http://quirktools.com/screenfly/ to create different standards for 'media queries' with Bootstrap.
2. Or, instead of typing in standard 'media queries' Bootstrap it calculates the size of the screen and already makes the patterns.

_**Thought , Example**_

 This is created with css. What if Bootstrap had it... this  without css?

```

// Extra small devices (portrait phones, less than 576px)
// No media query since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px)  ... 

// Medium devices (tablets, 768px and up)
@media (min-width: 768px)  ... 

// Large devices (desktops, 992px and up)
@media (min-width: 992px)  ... 

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px)  ...

```
`commandline "represent this"
`

> boostrap.media( auto )  // Generate different and automatic screens 'media queries' 
> 
> - auto = ' automatic calculation' 
> - media = 'media queries'
> - media = 'resource x'  x is 'width x height'  = '576 x 992px ' or ' media -= 992px ' or 'media += 992px'
> - media have  'px, em, rem, margin.... ' and  import 'css'.

_**Thought , Example**_

```

bootstrap.media(auto)  //  @media (min-width: 576px)  ...

/* 
   bootstrap.media(auto) represent this 
   Extra small devices (portrait phones, less than 576px)
   @media (min-width: 576px)  ...
   Small devices (landscape phones, 576px and up)
   Medium devices (tablets, 768px and up) @media (min-width: 768px)
   Large devices (desktops, 992px and up) @media (min-width: 992px)  ... 
   Extra large devices (large desktops, 1200px and up)
  @media (min-width: 1200px)

   boostrap.media { import site/style.css } : auto (); // bootstrap import file style.css from folder 'site' and 
   generate different and automatic screens 'media queries'

*/ 

```

Regards,
Pedro Guilherme.

**Comment by pedroguilhermelima** [comment]
_**Note**_
If you want to help build this idea with me, open my repository and we can discuss this idea.

Reference
https://github.com/pedroguilhermelima/bootstrap-mediaqueries


Regards,
Pedro Guilherme.

**Comment by herbalite** [comment]
Recently I have found media breakpoints based on min-width or max-width not sufficient enough.  So you might consider the following.

There are better ways to scaling a page. In Bootstrap for example put 4 cards into a carousel. If the screen is large enough that is no issue, once the screen (or window) is smaller, the 4 cards will be broken up, doubling the height of the carousel. Most the time this is not the desired design solution. I've seen non Bootstrap solutions that either scale the content within the carousel, or make the content within the carousel scrollable. Now this is not just within a carousel, you can do the same with several cards in a simple row. Same thing is happening, because of flexbox.  Height is doubling.

For your topic, please consider that there are more ways required and already available for truly responsive design.

**Comment by pedroguilhermelima** [comment]
So... but... I know about that. I'm just trying to add this rule and another rule of Bootstrap via a js script instead of the css resources. As you have seen, I am trying to create and style a library that does this without have writing css.

**Comment by patrickhlauke** [comment]
This seems well outside of the kind of thing we'd want in core bootstrap. @twbs/team feel free to reopen if you disagree.

**Comment by pedroguilhermelima** [comment]
Please, reopen. Because you do not put up support! With these rules in javascript?
Instead of CSS? So... Is there any particular reason not to do it? So... I'm trying to develop this feature to improve CSS. So... with this unique line `bootstrap.media(auto)`

Note: I researched and found this

```
0.
var w = window,
    d = document,
    e = d.documentElement,
    g = d.getElementsByTagName('body')[0],
    x = w.innerWidth || e.clientWidth || g.clientWidth,
    y = w.innerHeight|| e.clientHeight|| g.clientHeight;

1.
$(window).height();   // returns height of browser viewport
$(document).height(); // returns height of HTML document (same as pageHeight in screenshot)
$(window).width();   // returns width of browser viewport
$(document).width(); // returns width of HTML document (same as pageWidth in screenshot)

2.
var width = window.innerWidth
|| document.documentElement.clientWidth
|| document.body.clientWidth;

3.
var height = window.innerHeight
|| document.documentElement.clientHeight
|| document.body.clientHeight;

4.
alert(window.screen.availWidth);
alert(window.screen.availHeight);

5.
window.innerWidth, window.innerHeight

```

> '0, 1,2,3,4,5' is number (total and example answers  )  the question: How to calculate screen size with javascript?

## What is your thinking?

**Add these rules and represent this**

```
bootstrap.media(auto)  //  @media (min-width: 576px)  ...

/* 
   bootstrap.media(auto) represent this 
   Extra small devices (portrait phones, less than 576px)
   @media (min-width: 576px)  ...
   Small devices (landscape phones, 576px and up)
   Medium devices (tablets, 768px and up) @media (min-width: 768px)
   Large devices (desktops, 992px and up) @media (min-width: 992px)  ... 
   Extra large devices (large desktops, 1200px and up)
  @media (min-width: 1200px)

   boostrap.media { import site/style.css } : auto (); // bootstrap import file style.css from folder 'site' and 
   generate different and automatic screens 'media queries'

*/ 

```
