### ISSUE TITLE
Drag and drop elements, objects.

### ISSUE THREAD

**Issue by pedroguilhermelima** [twbs/bootstrap#28616]
Hi, how are you?

**Note**:  
1. I love this lib https://shopify.github.io/draggable/
2. So, you can add this feature in Bootstrap?

_**Description of problem and solution**_

   1.  Wix is ​​one of the largest platforms to select, drag and drop. This good, creates websites. Which is great for those who do not know about CSS / HTML / JS.

 2. But, I believe Bootstrap can use this, but do better. Well, programmers or 'web designers like you and me' can write the website with Boostrap with the drag and drop feature and selects. At the same time, create something and import from scratch.

3. Another thing, we can break standards and create others standards .

4. If I click on the div, a menu appears where I can drag and drop or select with the mouse.
```
  Menu context ( resource mouse )     1. select.    2. drag.  3. drop

```

_**Example of menu context**_

`
<span class="context-menu-one btn btn-neutral">right click me</span>

`

```
 $(function() {
        $.contextMenu({
            selector: '.context-menu-one', 
            callback: function(key, options) {
                var m = "clicked: " + key;
                window.console && console.log(m) || alert(m); 
            },
            items: {
                "Select": {name: "Select", icon: "select"},
                "Drag": {name: "Drag", icon: "drag"},
                "Drop: {name: "Drop", icon: "drop"}
                    return 'context-menu-icon context-menu-icon-quit';
                }}
            }
        });

        $('.context-menu-one').on('click', function(e){
            console.log('clicked', this);
        })    
    });

```
**Lib/ Reference https://swisnl.github.io/jQuery-contextMenu/demo.html**

Regards,
Pedro Guilherme.

**Comment by Johann-S** [comment]
Hi @pedroguilhermelima,

Thanks for your suggested feature, we'll pass on that, there are libs which handle that and are specialized to those use cases
