### ISSUE TITLE
Bundle Install - Could not locate Gemfile

### ISSUE THREAD

**Issue by gx2g** [twbs/bootstrap#28614]
I'm on Mac OS Mojave Version 10.14.4

Trying to install the build tools. I have npm installed and also ruby installed, verson of ruby is,
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

I ran gem bunder install
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Done installing documentation for bundler after 5 seconds
1 gem installed

but when I run bundle install I'm getting this error
bundle install
Could not locate Gemfile

Can you guys please help me get this installed correctly for the ruby dependencies. I asked bundler and they stated that it looks like the instructions on boostrap are incomplete.

**Comment by XhmikosR** [comment]
The instructions are fine. On master we no longer need Ruby.

**Comment by ironthirst** [comment]
I have the same problem with the bootstrap package I got from `npm install`. It's missing Gemfile.

I try to skip the `bundle install` part, since it was stated that bootstrap no longer need Ruby, but then got build errors because the package is missing the `build` directory.

I clone another bootstrap project from github directly and the instructions work fine for that copy.

**Comment by flowl** [comment]
How can this be closed, when it's not fixed.

Following the instructions, the gemfile is still clearly missing, when using bootstrap through `npm install bootstrap`:

```
macbook:bootstrap daniel$ npm start

> bootstrap@4.3.1 start /Users/daniel/Projects/d/node_modules/bootstrap
> npm-run-all --parallel watch docs-serve


> bootstrap@4.3.1 docs-serve /Users/daniel/Projects/d/node_modules/bootstrap
> bundle exec jekyll serve


> bootstrap@4.3.1 watch /Users/daniel/Projects/d/node_modules/bootstrap
> npm-run-all --parallel watch-*

Could not locate Gemfile or .bundle/ directory
npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! bootstrap@4.3.1 docs-serve: `bundle exec jekyll serve`
npm ERR! Exit status 10
npm ERR! 
npm ERR! Failed at the bootstrap@4.3.1 docs-serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2019-09-25T22_14_27_270Z-debug.log
ERROR: "docs-serve" exited with 10.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.3.1 start: `npm-run-all --parallel watch docs-serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.3.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2019-09-25T22_14_27_379Z-debug.log
```

**Comment by flowl** [comment]
I can canfirm this when installing Bootstrap 4.3.1 through `npm install bootstrap`. The local build process there does not work.

The master branch is working, nicely done, looking forward to the new release.

**Comment by b0lle** [comment]
same here with bootstrap 4.4.1

`bundle install
>>>Could not locate Gemfile`

**Comment by flowl** [comment]
@XhmikosR  Closing this with the message "Everything is fine" is inpolite towards the people reporting the software's unintended behaviour.

**Comment by XhmikosR** [comment]
@b0lle: you are clearly doing something wrong. Our [CI works fine](https://github.com/twbs/bootstrap/runs/583503302#step:17:1) and v4-dev does have [a Gemfile](https://github.com/twbs/bootstrap/blob/v4-dev/Gemfile).

You could either be on the wrong branch or something else.

https://github.com/twbs/bootstrap/blob/master/.github/SUPPORT.md#how-to

**Comment by flowl** [comment]
@XhmikosR 

Following the steps from here: https://getbootstrap.com/docs/4.4/getting-started/build-tools/#tooling-setup

It's easy to reproduce:

% npm install bootstrap
% sudo gem install bundler
% bundle install
Could not locate Gemfile

**Comment by XhmikosR** [comment]
@flowl please read my message again.

**Comment by flowl** [comment]
How does the Gemfile get into the project, why it's not installed through `npm install bootstrap` or at least mentioned in the manual ?

**Comment by flowl** [comment]
Ok, took me a while, the Gemfile is only in the `-dev` packages... it should be mentioned in the docs tho!
