### ISSUE TITLE
Buy, sell templates internally , bootstrap-business.js

### ISSUE THREAD

**Issue by pedroguilhermelima** [twbs/bootstrap#28619]
Hi, how are you?

_**My suggestion, idea**_
 1. I would like Bootstrap to go beyond the community, to be a community of companies and people interested in this sale process or buy of 'layouts, designs' inside Bootstrap and not outside of Bootstrap. 
 2. I could charge my services or support within Bootstrap. For example, I can be 'Web Designer Bootstrap' and not just a 'Wordpress Web Designer'. 
3.  So, what I'm talking about is an internal store and not external to the framework services. 
4.  Everything could go back to the community and thus improve the framework more and more. 

_**Note**_

1. I believe the community with the 'gnu / linux / public / free ' software.  I believe should charge services of the software. And... so. My thought is... It may be easy to have several people interested in something and charge for it. Than to sell a product.

2. I do not know if people today like products. I read about 'collaborative economics'.

3. I do not know much, but I want to help here with that thought and If possible.

4. We have several services that we can make people as diverse monetary values. What's good to get back to the software or to the person / group that made the software or to outsiders or just the community and part of it.

5. I love money, because it allows for many things. Today our biggest money is information. Selling information,  can cost a lot or less depending on your problem.

6. I believe that selling information to the  'framework Bootstrap' the case should be. For example, if you want services as part of the framework Bootstrap the value will be high. And we can hire more people and make more things.

7. Another thing, 'Web Design' can be part of this process. Another process would be a new construction of graphs or graphical interfaces 'UI / UX'. In addition, web projects have turned to animation, new libraries and resources inside to 'framework Bootstrap'.

8. The sale and purchase would be made by API PayPal. And,  communication between Whatsapp / Telegram API inside Boostrap Business.

_**Going back through the idea.**_
```

Name Lib: Bootstrap Business.
Language programming: Javascript, CSS, HTML.
Name file: bootstrap-business.js

```
**Example**

> **boostrap-business.js**
> - API PAYPAL   - API TELEGRAM - API WHATSAPP

```
<!DOCTYPE html>
<html>
<body>
<bootstrap-business>
<!------- Template Bootstrap 1 with Whatsapp active and Telegram active ---->
<template paypal="R$2000,00" whatsapp="active" telegram="active"></template>

<!------- Template Bootstrap 2 with Whatsapp active  ---->
<template paypal="R$2000,00" whatsapp="active"></template>

<!------- Template Bootstrap 4 with Telegram active  ---->
<template paypal="R$2000,00""></template>

<!------- Template Boostrap 4, only price in Bootstrap ---->
<template paypal="R$2000,00""></template>
</bootstrap-business>

<!------- USD, R$ ( Value Brazil ) ... values of money ---->

<!------- attribute paypal 'Paypal' is https://www.paypal.com/cgi-bin/webscr?cmd=_ ---->
<!------- attribute whatsapp 'Whatsapp' is https://api.whatsapp.com/send?l=pt&phone=  ---->
<!------- attribute telegram 'Telegram' is  ---->

<script src="bootstrap-business.js"></script>
<script src="socket.js"></script>
<script>
import template { array(); } // import all <template to array with index 0. <template .... 1. <template 
show.array() when sets() // show array to sets "config"
// config have "mail, server, port or proxy reverse... peer to peer or generate QRCODE "

</script>
</body>
</html>

```
**Concept**
No servers, peer to peer. Use socket  for this and ngrok "proxy reverse"

_**Example of menu context**_

`
<span class="context-menu-one btn btn-neutral">menu</span>

`

```
 $(function() {
        $.contextMenu({
            selector: '.context-menu-one', 
            callback: function(key, options) {
                var m = "clicked: " + key;
                window.console && console.log(m) || alert(m); 
            },
            items: {
                "Buy": {name: "Buy", icon: "buy"},
                "Sell": {name: "Drag", icon: "sell"},
                    return 'context-menu-icon context-menu-icon-quit';
                }}
            }
        });

        $('.context-menu-one').on('click', function(e){
            console.log('clicked', this);
        })    
    });

```
**Lib/ Reference https://swisnl.github.io/jQuery-contextMenu/demo.html**

Regards,
Pedro Guilherme.

**Comment by pedroguilhermelima** [comment]
_**Note**_
If you want to help build this idea with me, open my repository and we can discuss this idea.

Reference
https://github.com/pedroguilhermelima/bootstrap-business


Regards,
Pedro Guilherme.

**Comment by MartijnCuppens** [comment]
Not planning on adding this in Bootstrap.
