### ISSUE TITLE
Chrome | Scrolling broken for list-group within card

### ISSUE THREAD

**Issue by santjosie** [twbs/bootstrap#28612]
- Operating system and version: Windows 10
- Browser and version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

Issue Description:
I have a "card-columns" which contains a few "cards". The "cards" have "list-groups" within them. Overflow-y is enabled for these and the "cards" are of fixed height.

The vertical scrolling of the list-group within a card is broken when using Chrome. It works fine in Firefox. I am attaching an MP4 showing the difference in the responses between the two browsers. I am also attaching the reduced test case with cards and list-group data.
[bootstrap.zip](https://github.com/twbs/bootstrap/files/3046193/bootstrap.zip)

[2019-04-05_04-11-59.zip](https://github.com/twbs/bootstrap/files/3046219/2019-04-05_04-11-59.zip)

**Comment by santjosie** [comment]
I have logged this as a bug with the Chromium project.

Here's the link

[Chromium Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=950274)

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by santjosie** [comment]
The Chromium team is fixing this now.
