### ISSUE TITLE
Toast hide event fired timing

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#28629]
When use an autohiding toast, the hide event is fired just after shown, it ignore the delay time.

demo: https://codepen.io/anon/pen/YMpRyE?editors=1111 (Please see the console view)

I expected the hide callback is called after 3000ms, but it is actually called right after the toast is shown. Is it intended? Thanks.

**Comment by Johann-S** [comment]
Hi @ysds,

That's the normal behavior, `hide.bs.toast` is triggered right after we call our `hide` method, but `hidden.bs.toast` is triggered when the toast is totally hidden.

In your CodePen just add the following code and you'll see :
```js
  $toast.appendTo('#toastArea')
    .toast({delay: 3000})
    .toast('show')
    .on('hide.bs.toast', function () {
      console.log('hide');
    })
    .on('hidden.bs.toast', function () {
      console.log('hidden')
    });
```

**Comment by ysds** [comment]
Year, I know the hidden event.

The hidden events is fired when end the fade animation, and I think the hide events should be fired the start the fade animation. But the hide events is fired the same timing with shown event.

**Comment by ysds** [comment]
Note: the `delay` option is not the duration of fade animations. It is wait time before auto hide.

**Comment by Johann-S** [comment]
That's not how we designed the rest of our components, on other components we trigger the `hide` event when we start to `hide` the components, that's not totally related to the animation.

Here you use `delay` and `autohide` so it's normal `hide` event is immediatly triggered right after the `shown` event because of the `autohide`.

**Comment by ysds** [comment]
No, the `hide()` (and the callback) should be called after the `delay` time.

**Comment by ysds** [comment]
I will show my thought in a PR, so would you see it?

**Comment by Johann-S** [comment]
Can you explain why ? Because here, I don't see any use case why we should do that like that, but just someone who said: "I want that like that."

**Comment by ysds** [comment]
Because It is different from the general behaviors. e.g. the mdc has similar event: `closing`, it is fired when start its closing animation.

demo: https://codepen.io/anon/pen/dLNyGR?editors=1111
