### ISSUE TITLE
[IE] carousel keyboard navigation and ripple-like effect on last slide

### ISSUE THREAD

**Issue by VlkaFenryka** [twbs/bootstrap#28628]
> Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
* Windows 10 Pro 1809 build 17763.379
* macOS Mojave (only Safari via browserstack)

> Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
* Chrome 73.0.3683.103 (Official Build) (64-bit)
* Chromium 73.0.3683.86 (Official Build) (64-bit)
* Firefox 66.0.2 (64-bit)
* Opera 60.0.3255.27
* Edge 44.17763.1.0  /  18.17763
* IE11 11.379.17763.0
* Safari 12.0 (14606.1.36.1.9)

### Problem
- The slide is navigationable via arrow keys only on IE11
https://drive.google.com/file/d/1hxCLL-bNMS2Asx5RmrgQCSE4_u2-P_H-/view
![image](https://user-images.githubusercontent.com/25515219/55783733-644c2800-5aaf-11e9-974e-cfef40dac841.png)
- The last slide has a ripple like effect when slided

### Steps to reproduce
1. get to the official documentation
2. https://getbootstrap.com/docs/4.1/components/carousel/#slides-only
3. click in the carousel and use the arrow keys to slide forward/backward

**Comment by Johann-S** [comment]
I can confirme it on IE 11 with Win 10

**Comment by mdo** [comment]
Revisiting this almost 2 years later, I'm not seeing any visual glitches here in IE11. Closing given staleness and that v5 drops IE11.
