### ISSUE TITLE
.tab('hide') method

### ISSUE THREAD

**Issue by boutzamat** [twbs/bootstrap#28624]
I can't seem to find any method to hide an active tab.

I can only find .tab('destroy') - in my search of finding .tab('hide'), as an opposite to .tab('show')

Is there any method to hide/toggle an active tab?
If no - can we add it as a feature request?

**Comment by chiraggmodi** [comment]
for hide, basically it is doing display:none, so you can use Javascript to remove active/show class from tabs

**Comment by boutzamat** [comment]
> for hide, basically it is doing display:none, so you can use Javascript to remove active/show class from tabs

Won't work for tabs with fade :)

**Comment by rohit2sharma95** [comment]
@boutzamat Is this even required :)
Usually, a single tab should always be active :thinking:

**Comment by Johann-S** [comment]
Yep I agree with @rohit2sharma95 here, if you want to hide a tab, you have to switch tab
