### ISSUE TITLE
Feedback Clarification on $enable-shadows with box-shadows on custom-controls

### ISSUE THREAD

**Issue by classicmike** [twbs/bootstrap#28636]
Hi,

I was in the middle of tweaking the box shadows for custom controls and I found something that looks questionable in the source SASS file? Screenshot attached.
![Screen Shot 2019-04-10 at 10 37 08 am](https://user-images.githubusercontent.com/1841040/55843804-709eb680-5b7d-11e9-8037-bbd7dead1d4f.png)

If logic tells me right my expectation is that, ```$enable-shadows``` is a boolean that will enable all styles that have a shadow to show a shadow meaning, if it is set to true, things like ```form-control``` on focus and ```custom-control``` on focus have a shadow style applied to it. On the contrary, if it is false, it would apply NO SHADOW at all. Would that be a reasonable interpretation of what I should be expecting just by looking at ```$enable-shadows``` alone?

What didn't make sense to me is that we have a variable called ```$custom-control-indicator-focus-box-shadow``` which is called when ```$enable-shadows``` is false!?!?

So what that basically means is that if I wanted to style custom control indicators to have different box shadows to ```form-controls```, I can't, unless if I could find a way quickly change the bolean to ```false```, "Just before SASS parses the custom control SCSS" then "reset it to ```true``` after"?!?!

At the moment from me reading the code, the logic seems a little questionable so maybe for clarification purposes, could you explain the purpose of the ```$enable-shadows``` variable and the rationale for making the calling ```$custom-control-indicator-focus-box-shadow``` where it currently is in the source please? Also if this is confirmed as a bug or issue, would this be something you will fix?

Look forward to your reply.

Thanks.

**Comment by mdo** [comment]
Our custom forms, and our buttons and other components, use a homegrown focus style that's built on `box-shadow`. As such, to ensure accessibility, we always provide this shadow focus style. That's why we have this logic here.
