### ISSUE TITLE
sanitize option is undocumented

### ISSUE THREAD

**Issue by tomsommer** [twbs/bootstrap#28647]
The newly added `sanitize` option is not documented in the Tooltip and Popover documentation

**Comment by Johann-S** [comment]
It's present in the Tooltip and Popover docs see: https://getbootstrap.com/docs/4.3/components/tooltips/#options
https://getbootstrap.com/docs/4.3/components/popovers/#options

And you also have: https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer

It's the same for our v3.4.1:
https://getbootstrap.com/docs/3.4/javascript/#tooltips-options
https://getbootstrap.com/docs/3.4/javascript/#tooltips-options

**Comment by tomsommer** [comment]
Appologies, I was looking at the https://getbootstrap.com/docs/4.1/getting-started/introduction/ documentation - The "This is an old documentation"-warning in the top should be more visible, and the 4.3 documentation should be linked in the dropdown in the top
