### ISSUE TITLE
Extension: editable fails with other functions that use onChange

### ISSUE THREAD

**Issue by devshell** [twbs/bootstrap#28644]
http://jsfiddle.net/3L7vgcx0/22/

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
Windows

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by patrickhlauke** [comment]
suggest you file this on the actual bootstrap-editable project, which is nothing to do with us :)

https://vitalets.github.io/bootstrap-editable/
