### ISSUE TITLE
Allow toggling heading element styles with a SASS variable.

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#28641]
As we have the class selectors for h1 etc, it could be handy for UI vs SEO reasons, to be able to choose if we want to style default headings or to style them with the use of the proper class

Example
```
//Variables.scss

$enable-style-on-heading-elements:false;
$heading-sizes: () !default;
// stylelint-disable-next-line scss/dollar-variable-default
$heading-sizes: map-merge(
                (
                        1: $font-size-base * 2.5,
                        2: $font-size-base * 2,
                        3: $font-size-base * 1.75,
                        4: $font-size-base * 1.5,
                        5: $font-size-base * 1.25,
                        6: $font-size-base * 1,
                ),
$heading-sizes
);
```

```
//type.scss

@each $abbrev, $size in $heading-sizes {
    $selector: '.h#{$abbrev}';
    @if $enable-style-on-heading-elements {
      $selector: 'h#{$abbrev}, .h#{$abbrev}';
    }
    #{$selector} { @include font-size($size); }
}
```

**Comment by MartijnCuppens** [comment]
Are you looking for `.h1,.h2,...` classes? We already have these. This is also documented: https://getbootstrap.com/docs/4.3/content/typography/#headings

**Comment by GeoSot** [comment]
No, I am looking for an option, in order to avoid styling by default  "h" elements

**Comment by MartijnCuppens** [comment]
You could set all your `$heading-*` variables to `null` to disable styling.

**Comment by mdo** [comment]
I don’t see us moving anywhere beyond the functionality @MartijnCuppens has mentioned. Always need to strike a balance on this stuff to avoid making things overly complex or less approachable for the majority of folks.
