### ISSUE TITLE
Don't close Dropdown onclick dropdown item

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#28640]
hello sir,
I am using windows 10, Chrome 73.0.3683.103,

i am using Bootstrap 4.3.1 

in which I am using the dropdown menu in which if i am clicked on and dropdown item then dropdown item it will automatically close how to make dropdown menu open when I will click on the dropdown item.

I will attach demo of the dropdown code.

[dropdown-demo.zip](https://github.com/twbs/bootstrap/files/3067935/dropdown-demo.zip)

**Comment by ysds** [comment]
The problem isn't clear. Could you create an online demo?

**Comment by pcodedviral** [comment]
@ysds I have already attached demo file please check in the first message https://github.com/twbs/bootstrap/issues/28640#issue-431924243

**Comment by ysds** [comment]
Even if you are not malicious, for security reasons, I never open a attached file.
