### ISSUE TITLE
nav-justified with navbar - missing info in documentation

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#28646]
Hello,
I have noticed that if we want to use .nav-justified in .navbar we have to add .w-100 (I found that here: https://github.com/twbs/bootstrap/issues/21874) but in docs I don't see any info about that, please add this info or fix it to work without .w-100

**Comment by ysds** [comment]
Could you create a demo ([CodePen](https://codepen.io/) etc.) with 4.3.1?

**Comment by SkuterPL** [comment]
No problem, here you are: https://jsfiddle.net/fuvL7o3y/

`<ul class="navbar-nav mr-auto nav-justified nav-pills w-100">`

Here I had to add `.w-100` to work property

**Comment by ysds** [comment]
Thanks, but please update the bootstrap version.

**Comment by SkuterPL** [comment]
> Thanks, but please update the bootstrap version.

https://jsfiddle.net/nmbar9y4/ - updated to 4.3.1

**Comment by ysds** [comment]
Umm, it seems broken.

**Comment by SkuterPL** [comment]
https://codepen.io/anon/pen/QRMRqq

**Comment by XhmikosR** [comment]
I think what you are trying to achieve here doesn't fall into the same category of the navs docs, hence why you need `w-100` there.

@twbs/css-review: your call.

**Comment by SkuterPL** [comment]
I wanted to get full with menu, in BS3 we could do without any extra class as I remember in documentation I found that info, in BS4 we need to add extra class because of flex, so I think that in navbar section you should write about that

**Comment by XhmikosR** [comment]
But it's not needed for the current examples.

Generally, you do need to step up things when you create more custom stuff.

Now, if it'd be nice to have an example like yours in the navbar or navs docs, feel free to open a PR.

**Comment by ysds** [comment]
I agree with @XhmikosR. The change of navbar rewritten to flex based is described in the migration guide.
And flex items are positioned align left, this is one of the basic specification of flex.

**Comment by SkuterPL** [comment]
> But it's not needed for the current examples.
> 
> Generally, you do need to step up things when you create more custom stuff.
> 
> Now, if it'd be nice to have an example like yours in the navbar or navs docs, feel free to open a PR.

But without this `.w-100` I don't see full width menu and `.nav-justified` doesn't work:
![image](https://user-images.githubusercontent.com/37087362/58368651-1d47b400-7ef0-11e9-9068-1c044755cf79.png)

Let see in BS3:
![image](https://user-images.githubusercontent.com/37087362/58368668-7e6f8780-7ef0-11e9-8180-afe2c5cd667b.png)

There is native 100% width in CSS.

I think that we could add tip in documentation when we want  to full width and the most important get the same width of all bookmarks in menu we have to add `.w-100` to get this.

You wrote about demo, here you can see it: http://irson.linuxpl.eu/ (delete `.w-100` and see whats happened)

**Comment by XhmikosR** [comment]
Like I explained above, your use case isn't a usual one. If you still think it'd be useful, you can make a PR for the docs.

**Comment by SkuterPL** [comment]
How to do this?

**Comment by mdo** [comment]
The justified nav example has never been in v4, so if you want it, you'll have to pull styles from that old example. There are no plans to bring it back to v4 or to v5 at this time. There are modifiers for the v4 nav component that allow for full-width tabs. See https://getbootstrap.com/docs/4.3/components/navs/#fill-and-justify.

**Comment by SkuterPL** [comment]
In this documentation is written that with justified we should see the same width of every bookmark, but in my example it didn't work without w-100
