### ISSUE TITLE
Bootstrap css style script for strong html tag prevents text "bolding" feature at v4.3.1 

### ISSUE THREAD

**Issue by javatutorials2016** [twbs/bootstrap#28652]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
macOS
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Chrome, Safari
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

In bootstrap.css at line 131 , exists the below style 

b,
strong {
  font-weight: bolder;
}

This css prevents "Bolding" when I use <strong> </strong>html tag. I debugged in chrome and removed this style and see the text getting bold.

I am using v4.3.1. Thank you.

**Comment by javatutorials2016** [comment]
When I apply <strong></strong> HTML tag, the text was not getting bold. When I checked, bootstrap.css (v4.3.1) has font-weight:bolder; which was preventing it.

**Comment by alecpl** [comment]
It's not clear what your issue is. Please, provide a live example and follow the ticket template.

**Comment by patrickhlauke** [comment]
my guess is that on the user's browser/OS combination, with the font family they use (perhaps changing from the default), `font-weight: bolder` is not having a strong enough/perceptible bold effect, compared to `font-weight: bold`...

**Comment by javatutorials2016** [comment]
Yes. It looks like normal text even with strong tag in chrome browser/Mac
OS.

**Comment by MartijnCuppens** [comment]
Looks pretty **bold** to me on Chrome,mac (https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag):
![image](https://user-images.githubusercontent.com/11559216/57036323-44de9000-6c54-11e9-841f-27b5f10db868.png)

**Comment by patrickhlauke** [comment]
I'm assuming/guessing that @javatutorials2016 has defined their own font family, and for THAT `bolder` isn't having as strong an effect? If that's the case, however, there's an argument there that once you start to change things like fonts, it's reasonable that you may also need to override certain other aspects of bootstrap's core styles if they don't work well with that customisation...

**Comment by javatutorials2016** [comment]
Thanks for looking into this. Please find the screenshot attached that
explains the issue that I have reported about.

Hope it helps and kindly let me know if you have any questions.

**Comment by XhmikosR** [comment]
I don't see any screenshot @javatutorials2016

**Comment by mdo** [comment]
The very snippet of code mentioned in the opening comment shows we're doing using `bolder` vs `bold` for the `<b>` and `<strong>` elements. Whenever possible, the browser will make the text within those elements bolder, not bold. Closing as there's nothing to fix.
