### ISSUE TITLE
How can I get latest shipped changes of v4?

### ISSUE THREAD

**Issue by PerseusTheGreat** [twbs/bootstrap#28658]
Hi,
As you said before, in official blog post (Bootstrap 4.3.0, 11 Feb 2019), there is a "**v4-dev**" branch for tracking v4 development changes, and a new "**master**" branch for next major release (v5) developments.
Now, my question is:
**How can I get latest shipped changes (marked as backport-to-v4) of Project v4.3.2?**
The "**v4-dev**" branch has not been updated since 19 days ago (until today: 15 Apr 2019).

I apologize, I'm not good in English.

**Comment by XhmikosR** [comment]
Just checkout the v4-dev branch `git clone https://github.com/twbs/bootstrap.git -b v4-dev`. There's a PR pending with further v4 updates, but it needs some time before merged.

**Comment by PerseusTheGreat** [comment]
I am confused...😜
Does it mean there are shipped changes on "**Project v4.3.2**" but they have not been merged to "**v4-dev**" branch yet?
Why they have been marked as shipped?!

**Comment by XhmikosR** [comment]
No, v4-dev only includes merged stuff.

**Comment by patrickhlauke** [comment]
"shipped" means it's released. v.3.2 is not shipped yet. it's the one that's now in progress, and will be shipped next.

**Comment by PerseusTheGreat** [comment]
> No, v4-dev only includes merged stuff.

Ok, Thanks.

**Comment by PerseusTheGreat** [comment]
> "shipped" means it's released. v.3.2 is not shipped yet. it's the one that's now in progress, and will be shipped next.

I understand now (I hope so...).
It seems some BS's development approaches have changed for v4.3.2.
In near past (before 4.3.2 project), I remember, there was 4 or 5 task columns in project page, and when a task had been moved to the last column, I could tracked it as committed in branch's history; But now, tasks of last column, have not merged to v4-dev branch yet.
This made me confused.
