### ISSUE TITLE
Allow us to pass other Popper.js configurations to dropdowns and tooltips

### ISSUE THREAD

**Issue by istratos** [twbs/bootstrap#28661]
Popper.js provides a lot of configuration that can be used for our utilities, but most of them are not being used by the plugins themselves.

I'm in a situation where I require a `dropdown` to be of `fixed` position rather than `absolute`, popper allows this via:

```
Popper.Defaults.positionFixed = true
```

However that would change everything that is using Popper in my page. I can't really change this configuration per-element basis.

It would be of great help to let us pass a second param to the built in functions, being the Popper options (not supported in the plugin) to be merged in the Popper config when initializing an object.

```
$('.dropdown-toggle').dropdown({
    boundary:'viewport' // Plugin config
}, {
    positionFixed: true // Popper config
});
```

**Comment by Johann-S** [comment]
Yep I agree 👍

**Comment by randomnt** [comment]
i need positionFixed too, but in my case it would be more suiteable to set it via data- attribute. Maybe we need to add attributes like data-popper-* to pass params to popper?
