### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#28668]
Bootstrap is fantastic for full fledged Web browsers. Unfortunately, HTML email clients do not present the same feature set, and so Bootstrap does not currently render properly for email templates.

Can we get better support for common  HTML email clients, so that we can have more confidence that our Bootstrap styles will carry across emails just like our websites?

Prior art:

* [Bootstrap Email](https://bootstrapemail.com/), which unfortunately has a hard requirement on both Rails and SCSS in order to function.

**Comment by mdo** [comment]
Would be cool but not right now. Other tools are available and do a solis job of this.
