### ISSUE TITLE
 -webkit-text-decoration-skip-ink: none > Property > w3c error

### ISSUE THREAD

**Issue by Marc-pi** [twbs/bootstrap#28669]
With W3c validator, we get error with BS 4.3.1 with text-decoration-skip-ink property

(https://github.com/twbs/bootstrap/blob/8fa0d3010112dca5dd6dd501173415856001ba8b/dist/css/bootstrap-reboot.css#L63)

Error: CSS: text-decoration-skip-ink: Property text-decoration-skip-ink doesn't exist.

**Comment by herbalite** [comment]
It's in the W3C draft though
https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-ink-property

**Comment by mdo** [comment]
Yup, closing as not a big at this point.
