### ISSUE TITLE
Use :hover and :focus instead outline

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [twbs/bootstrap#28673]
Hi, I worked in many websites with bootstrap but I have problem with **outline**!
I know should not make outline to none or 0 but we can do it when merge :hover and :focus for visual effect when element focused with TAB key.
By this idea we can remove bad visual effects (Outline) in normal usage of website same as when click on a navigation bar which has child menu and other property does show outline when click and also we have visual effect for highlight when navigate element by TAB key.

**Comment by mdo** [comment]
We already have a custom focus style for our major components, so not sure what else you're looking for us to explore here.
