### ISSUE TITLE
Bootstrap 4 modal does not allow to scroll on input field

### ISSUE THREAD

**Issue by manesvenom** [twbs/bootstrap#28674]
When the modal is opened and drag down on the blank space between fields. It does work fine. However, if the touchstart event on the top of an input field, the scrolling does not work.

- Operating system and version 
iOS 12
- Browser and version 
 Safari, Chrome

- [Reduced test case]
https://www.bootply.com/SCifOFaozG

**Comment by manesvenom** [comment]
Here is my tweak to make the input field to be scrollable when touch on it 
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

//allow scrolling the page when touch starts on the top of an input field
.modal{
    -webkit-overflow-scrolling: touch;
}

**Comment by mdo** [comment]
Plenty of reasons for now adding the overflow scrolling that are mentioned in issues and PRs. Closing as a won't fix for now.
