### ISSUE TITLE
Remove Bottom Margin after Last Child in Alert

### ISSUE THREAD

**Issue by rasamassen** [twbs/bootstrap#28686]
One bootstrap override that I've found useful is:

.alert :last-child { margin-bottom: 0; }

This fixes extra margins in paragraphs, lists, and more.

I'm don't use GitHub much, so I don't feel comfortable making my own contribution, but think it's addition would be simple and welcome.

**Comment by mdo** [comment]
While we do use universal selectors in some places, this is not the place to use it. Sorry, but instead, use margin utility.

**Comment by arthurshlain** [comment]
@mdo, how about this?

```css
.mb-last-0>:last-child {
  margin-bottom: 0 !important;
}
```

Usage:

```html
<div class="alert mb-last-0">
  <p>Paragraph 1</p>
  <p>Paragraph 2</p>
  <p>Paragraph 3</p>
</div>
```
