### ISSUE TITLE
Compiling issue with line in _custom-forms.scss

### ISSUE THREAD

**Issue by Melisunde** [twbs/bootstrap#28685]
When compiling Bootstrap 4.3.1 with Prepros I receive the following message:

> 1%/% 50% isn't a valid CSS value. on line 98:27 of (bootstrap-path/)_custom-forms.scss

The line in question in _custom-forms.scss is:
`background: no-repeat 50% / #{$custom-control-indicator-bg-size};`

If I comment out that line everything else complies as it should. A search here doesn't show anyone else having this problem though. Is the problem with that line or with the preprocessing? Thanks!

**Comment by mdo** [comment]
Regrettably, this sounds like a problem with your preprocessor app and not Bootstrap as this compiles fine with our build tools.
