### ISSUE TITLE
Custom forms is a hack

### ISSUE THREAD

**Issue by vytsci** [twbs/bootstrap#28680]
Custom forms should be removed and forgotten in an abyss it came from. In the programming world, everything that requires the word "custom" in their name is a hack.

You should call those "hack" forms. Imagine your frontend developer adds custom-radio in their HTML and you have multiple libraries that render default form, you add bootstrap theme to it. Now you have a big problem deciding which element to render "custom-hack-radio" or default expected "radio".

You should either have one or other not both and their HTML structure should not be changed.

This is a perfect example of a hack and lazy workaround. Please reconsider this feature.

**Comment by patrickhlauke** [comment]
> You should call those "hack" forms. Imagine your frontend developer adds custom-radio in their HTML and you have multiple libraries that render default form, you add bootstrap theme to it. Now you have a big problem deciding which element to render "custom-hack-radio" or default expected "radio".

but it's for the developer to decide and to opt into. and developers do want to have the ability to use custom controls. so no, no plans to remove these for now...

**Comment by vytsci** [comment]
Please provide at least one proper reason to use such feature, at least name it properly. Such features just shows incompetence behind the wheel...

**Comment by patrickhlauke** [comment]
how about "a very large number of developers find that the way default form controls - in particular checkboxes and radio buttons - can be styled to be very limiting, and the want more control over their appearance". anyway, if you're just here to slag people off...have a nice one.

**Comment by mdo** [comment]
Opening an issue to complain about a thing you're unsure how or when to use, then blaming us for having the idea and feature in the first place, is a pretty shitty approach to getting someone to see things from your perspective. Next time, please rethink your feedback approach to project maintainers.

And fwiw, we're moving from separate custom/native forms and into a single set of form components in v5. Expect custom forms to improved (including the HTML and CSS under the hood) and to be the default moving forward.
