### ISSUE TITLE
Checkbox and radio - why waste "for" and "id"

### ISSUE THREAD

**Issue by vosidiy** [twbs/bootstrap#28684]
Here is current checkbox from documentation:

```
<div class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input" id="customCheck1">
  <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
</div>
```

If I want to show list of checkboxes, I have to add unique id and for attributes for each input and label.  otherwise it will not be clickable. You may confuse and make mistakes when you have many checkboxes

To make it simple I suggest to replace outer div with label. No need id and "for" attributes. it is clickable
Here is it:
```

<label class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input">
  <span class="custom-control-label">Check this custom checkbox</span>
</label>

```

**Comment by mdo** [comment]
Many reasons covered in our docs and past issues/PRs. See https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios for an overview of input/label sibling elements to start.
