### ISSUE TITLE
.sr-only should use !important

### ISSUE THREAD

**Issue by Jakobud** [twbs/bootstrap#28691]
It seems like .sr-only should explicitly use `!important` for all attributes. If you are using `.sr-only` anywhere, you want ALL of it's attributes to take priority no matter what. There are no exceptions to this.

There are many cases where server side templating logic would add the `sr-only` class to an element depending on various conditions. The problem here is that if that element has, for example `padding` on it, and this style is defined AFTER you added your Bootstrap CSS to a page, then the `sr-only` class is never going to have priority in the cascade, so therefore the `padding: 0` that is part of the `sr-only` class is going to get overwritten by the `padding` on the element that you defined elsewhere. Does that make sense?

**Comment by MartijnCuppens** [comment]
> Does that make sense?

Yeah, it does.

@ysds, @twbs/css-review, thoughts?

**Comment by patrickhlauke** [comment]
agree

**Comment by ysds** [comment]
Basically agree but, I doubt the necessity of adding `!important` to all properties. The [sample code of Wordpress](https://make.wordpress.org/accessibility/tag/screen-reader/) adding only to the `position` and the `word-wrap`.

**Comment by Jakobud** [comment]
So here is a basic example of the issue:

```
<!DOCTYPE html>
<html lang="en">
<head>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"/>

  <style>
    .my-element {
      padding: 2em;
    }
  </style>

</head>
<body>

  <div class="my-element sr-only">This should be essentially hidden</div>
  
</body>
</html>
```

In this basic example, `my-element` is going to have padding applied to it, when according to `sr-only` it should have `padding: 0`. This is because the page's custom code is defined after bootstrap css is brought in, which is a very common way to use bootstrap.

Now, one might think "Oh well just don't give the `my-element` any padding and you'll be fine." But in reality, in many cases, a website's server-side templating (or event client-side templating via React/Vue/Angular) will be set up render various classes like `sr-only` on elements depending on various conditions (like for example, "`if (userIsLoggedIn())... else...`".

I don't take lightly the idea of adding `!important` to anything. It's something that should be very carefully considered. But I believe in this case it should be used. When you are putting `sr-only` on something you are being VERY specific in saying that "This element should be ONLY visible to screen readers and it should not have any sort of decoration on it and should not take up any space on the page no matter what." There is never a case where you would put `sr-only` on something but still want it to take up space on the page or else you wouldn't be using `sr-only`.

In an ideal world, utility classes like `sr-only`, `hidden`, etc would always be defined at the end of all of your CSS in order to help give them priority in the cascade. But the reality is that most people simply add in `bootstrap.min.css` first and then add their custom CSS afterwords, which leads to the above issue.

**Comment by MartijnCuppens** [comment]
> Basically agree but, I doubt the necessity of adding !important to all properties.

In most cases those `! important`s will indeed be redundant, but the purpose of the class is to provide a solution for any situation, like @Jakobud described above, so I think we can add them here.

@Jakobud, could you make a PR for this?

**Comment by Jakobud** [comment]
Done sir #28701

**Comment by ysds** [comment]
> In this basic example, my-element is going to have padding applied to it, when according to sr-only it should have padding: 0. 

Have you ever tried that before? 

https://codepen.io/anon/pen/xeBrqR

It's hidden.

**Comment by Jakobud** [comment]
https://codepen.io/jakobud/pen/VNRgJm

All it takes is a `position: relative;` for it to all unravel unfortunately. I've had situations where I had to have position relative and some padding on an element for something and then conditionally added `sr-only` to it in certain situations.
