### ISSUE TITLE
Class to disable column behaviour

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#28706]
Sometimes is better not to use a defined col, but rather a static width for example for a logo and the website title, that can behave as columns with certain screen sizes (like mobile ones). The actual way of doing it is replacing min and max width css values with an @media.

**Comment by mdo** [comment]
I don’t think we’d add additional classes to disable core behaviors. If you need grid behaviors, but without the `.col` classes, I’d suggest checking out the flexbox utility classes.
