### ISSUE TITLE
Pagination: possibility of combining active and disabled on page-item

### ISSUE THREAD

**Issue by artellador** [twbs/bootstrap#28700]
I am asking for this feature because I can't think of an example where I would need to click on the active item in a pagination component. If I leave it `active`, the cursor shape on hover invites the user to click there, even if I disabled any action on that click. 

Thanks in advance

**Comment by mdo** [comment]
As `.active` and `.disabled` are classes only, they cannot affect the behavior of an anchor element. `disabled` also doesn't work on anchors, so you either have to remove the hyperlink or prevent the click some other way.

**Comment by artellador** [comment]
First of all, thanks for the explanation. I reviewed again my code looking for what made me asking this, and I found that bootstrap.css does the following on disabled page-item's:

```
.page-item.disabled .page-link {
  color: #6c757d;
  pointer-events: none;
  cursor: auto;
  background-color: #fff;
  border-color: #dee2e6;
}
```

I think that `pointer-events: none;` is affecting the behavior of the `page-link`. And even that `cursor:auto;` makes cursor look different than when hovering active elements.

**Comment by ysds** [comment]
It makes sense to be able to click on an active link(tab) for reloading, so that you can click the "Issue" tab on this page. Of course, there are cases where you want to be disabled it, but that is by design. Bootstrap is taking an "clickable active" approach.
