### ISSUE TITLE
How to custom color about pre-scrollable ?

### ISSUE THREAD

**Issue by GavinMoreYoung** [twbs/bootstrap#28708]
Hello, the great bootstrap creater, i am in trouble on development my webpage.  I find a lot of information about pre-scrollable, but i do not find how to custom color about pre-scrollable property,i hope you help.thank you.
![image](https://user-images.githubusercontent.com/12248194/56974860-3f287200-6ba2-11e9-948c-153428877886.png)

**Comment by patrickhlauke** [comment]
sorry, this issue tracker is not the right place for asking general "how to" type questions. see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
