### ISSUE TITLE
Tooltip interoperability issue with clipboard.js after upgrading from 3.3.7 to 3.4.1 (reproduced)

### ISSUE THREAD

**Issue by giro83** [twbs/bootstrap#28703]
I have tooltips where I display a registration key and I give the user the ability to copy such key to their clipboard (via clipboard.js). Essentially, the tooltip is HTML-enabled and clipboard.js is activated in there via a class.

This used to work fine in bootstrap 3.3.7 (and all previous versions I can recall, this project is several years old). This broke after upgrading to bootstrap 3.4.1.

Working demo based on 3.3.7: https://jsfiddle.net/t8vfhura/3/

Broken demo based on 3.4.1: https://jsfiddle.net/kgusa857/3/

I'm happy to open an issue with clipboard.js, if you think this is not a twbs problem. Just starting here as it's the upgrade that broke this for me.

Thanks!

**Comment by Johann-S** [comment]
It's related to the security fix we released see: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

Title is attribute is sanitized, so if you have to whitelist elements please refer to this guide: https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer

**Comment by giro83** [comment]
Thank you.
