### ISSUE TITLE
Version 4.3.1 breaks form elements in popover not working 

### ISSUE THREAD

**Issue by simbunch** [twbs/bootstrap#28702]
Hi

Maybe I'm missing a new option, but version 4.3.1 strips away form elements in popover content body: https://jsfiddle.net/simbunch/a1ud4y9m/2/

The same code works as expected with Bootstrap 4.1.3
https://jsfiddle.net/simbunch/56ygrbx8/1/

**Comment by ray73864** [comment]
Popovers in 4.3.1 now sanitise the data, I found this out when trying to use them for something.

If you look down the list of options for popovers you will see 3 new ones: sanitize, whitelist, and sanitizeFn.

By default, form elements are removed from popovers, in my case, all I did was turn the sanitisation off completely for the particular popover I needed the form in.

**Comment by mdo** [comment]
Closing per last comment.
