### ISSUE TITLE
NPM Date problem

### ISSUE THREAD

**Issue by RudyMas** [twbs/bootstrap#28712]
Hello,

I use NPM to install new versions of Bootstrap, and I noticed that the date of the files are wrong! I can't check for the older versions, but the current version has the date and time of the files at: 26/10/1985 10:15.

I use PhpStorm to upload the files to the server and because of those dates, PhpStorm always thinks that the version on the server is newer than the one I just downloaded.

Can you fix this in a future release. It would make updating my websites so much easier and less time consuming.

Thanks in advance!

Best regards,
Rudy Mas

**Comment by MartijnCuppens** [comment]
I don't think this is related to Bootstrap, I just checked this with `v4.3.1` and the modified date seems to be the same as the release date.

**Comment by RudyMas** [comment]
![image](https://user-images.githubusercontent.com/17342220/57042740-dc001380-6c65-11e9-868d-e10288136b21.png)

I just created a test project and ran npm install and it gave me the result you can see in the image. This is happening for a while now and only with Bootstrap. All other js-packages have normal dates.

Today, I used nodejs v11.12.0 and NPM v6.7.0. But it also happened with previous versions of nodejs and NPM. It's rather late now, but I'll try nodejs v10 tomorrow on another machine. Just to check if it is maybe a nodejs v11 problem, although, it's strange that it only happens with the Boostrap package.

Didn't anyone else mention this before? Because I can't believe I could be the only one that is having this problem.

**Comment by MartijnCuppens** [comment]
@XhmikosR, any idea what could be going on here and if we can do anything about this?

**Comment by XhmikosR** [comment]
Nothing we can do, AFAICT, and I've seen such issues reported on npm in the past.

The only thing I could do is, try Node.js 12 which comes with an updated npm, and see if this has changed there.

**Comment by XhmikosR** [comment]
Here's the upstream issue https://github.com/npm/npm/issues/20439

So, please try and see if they've changed it after v6.4.1.

**Comment by RudyMas** [comment]
I just tested it at work on different machines with version 10, 11 & 12. All have the same problem. Thanks for linking that issue. Sorry for wasting your time! I know how precious time is for coders. :-)

I just didn't expected it to be a problem with NPM, because all the other packages get processed correctly.

I sure appreciate the time you took to answer me and all the time that is spend on developing Bootstrap. It's something I often rely on for my layouts.

**Comment by XhmikosR** [comment]
Any package published with npm >= 6.0.0 has the same behavior so you probably just haven't hit it with other packages because people must have been using the old version which came with Node.js 6.x.

**Comment by RudyMas** [comment]
OK, thanks for the info. Then I have been very lucky, until now. :)
