### ISSUE TITLE
Bootstrap 4.3.1 breaks blob images in popovers

### ISSUE THREAD

**Issue by misanek** [twbs/bootstrap#28714]
Hi, 
current release of BS 4.3.1 breaks popovers containing images with blob in `src` attribute.
jsfiddle: https://jsfiddle.net/yg34t89v/4/
 
I tried to add `sanitize="true"` but it didn't work. 
With BS 4.1.0 it works fine.

Env.:
Windows 10, Chrome  74.0.3729.131

**Comment by Johann-S** [comment]
Hi @misanek,

![image](https://user-images.githubusercontent.com/1689750/57073851-99305100-6ce2-11e9-8dca-f6fc278ee8d1.png)

so to disable the sanitizer you have to do that in your JS file, or you can add `img` in the whitelist.

See: https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
