### ISSUE TITLE
Display:flex issue for safari 8 and older version

### ISSUE THREAD

**Issue by allisonaung** [twbs/bootstrap#28724]
I have issue with ngbootstrap date picker which styling is not working properly.After I inspect and play around, i found out that no prefix for display:flex for safari 8 and older.
Here is the screenshot
![Screen Shot 2019-05-03 at 12 01 59 pm](https://user-images.githubusercontent.com/15527046/57116878-4e264480-6d9b-11e9-88c4-1cb9f52f1dbc.png)

Is bootstrap solved the issue or any better way can i solve it from my end?

**Comment by mdo** [comment]
We don’t support Safari 8. https://getbootstrap.com/docs/4.3/getting-started/browsers-devices/#supported-browsers
