### ISSUE TITLE
Feature Request: Button Progress Indicator

### ISSUE THREAD

**Issue by akhilpai** [twbs/bootstrap#28728]
It would be nice if there were a way to indicate progress in buttons. Some examples:
https://tympanus.net/Development/ProgressButtonStyles/
https://lab.hakim.se/ladda/#progress
https://coreui.io/docs/components/loading-buttons/#built-in-progress-bar
https://tutorialzine.com/2013/10/buttons-built-in-progress-meters

The value is providing information while preserving space.

An implementation might embed progress bars similarly to spinners:
https://getbootstrap.com/docs/4.3/components/spinners/#buttons

**Comment by mdo** [comment]
Thanks, but we'll pass on this for now.
