### ISSUE TITLE
Responsive collapsing elements

### ISSUE THREAD

**Issue by stormriderstudios** [twbs/bootstrap#28730]
There are options to show and hide elements based on the width of the screen but, to the best of my knowledge (and I'd be very happy to be corrected) there is no way to "collapse" an element based on the width of the screen (xs, sm, lg, etc).

I currently want to collapse a div when the screen reaches xs, or rather automatically expand it when the screen goes above that. However, when the screen is small I still want to have the option to collapse and show the div. The bahaviour is very similar to the navbar but that comes with a whole host of overhead and extra features.

I just want an option to collapse something rather than hide it, or for the hide to be undone by a collapse toggle.

I hope that makes sense?

**Comment by ysds** [comment]
You can do that with combination of `.d-{breakpoint}-none` and `.d-{breakpoint}-block`.

https://codepen.io/anon/pen/PvwNwE

Is this demo something you want?

**Comment by stormriderstudios** [comment]
Thank you @ysds, I was using the display visiblity tags but obviously wrongly (I had .d-none and .d-breakpoint-block both on the same element, hadn't considered using collapse instead of the .d-none.

I'm still learning :)
