### ISSUE TITLE
Bootstrap - Security scan tool

### ISSUE THREAD

**Issue by babatundeko** [twbs/bootstrap#28748]
Hi!

Regarding my old ticket, what kind of security scan software tool do you use to scan on each version and upcoming release version? NIH and NHLBI are using NetSparker and IBM AppScan, and we want to ensure that we are using a similar tool to test an application to avoid confusion on what acceptable and whatnot on vulnerability part. Any significance information relates to security would be appreciated for my organization.

**Comment by RinkAttendant6** [comment]
I'm not speaking on behalf of Bootstrap but [Snyk](https://snyk.io) is a good option for scanning open-source project dependencies for JavaScript, Python, Go, PHP, Ruby, Scala, and .NET projects.

For JavaScript, the `npm audit` command also scans for known vulnerabilities.

**Comment by bardiharborow** [comment]
Bootstrap only loads two external dependencies: jQuery and Popper, of which jQuery is going away soon. We sometimes monitor the state of devDependencies, but short of there being an incredibly nasty minifier bug, these don't impact production in any way. As such we really have minimal external attack surface and these tools provide little benefit. This shouldn't discourage you for using them if they suit your project, just that they don't do anything for us.
