### ISSUE TITLE
Scrollspy didn't use data attribute when I manually init it

### ISSUE THREAD

**Issue by xiejiangzhi** [twbs/bootstrap#28743]
I saw the scrollspy code, it only use data attributes when automatically create.

if we new a instance without a config, the code will not automatically take the config from data attributes.

```
$(window).on(Event.LOAD_DATA_API, () => {
  const scrollSpys = [].slice.call(document.querySelectorAll(Selector.DATA_SPY))
  const scrollSpysLength = scrollSpys.length

  for (let i = scrollSpysLength; i--;) {
    const $spy = $(scrollSpys[i])
    ScrollSpy._jQueryInterface.call($spy, $spy.data())
  }
})
```

**Comment by Johann-S** [comment]
Hi @xiejiangzhi,

That's right, that's a desigin decision when one of our components can be initialized automaticaly, if you create it manually you have to pass all the config you want.
It's the same for our carousel or collapse components.
