### ISSUE TITLE
popover data-content with iframe is not display

### ISSUE THREAD

**Issue by sverdier** [twbs/bootstrap#28759]
Hi,

Iframe is not display on popover:

<button type="button" class="btn btn-lg btn-danger" data-html="true" data-toggle="popover" title="Popover title" data-content='<b>before iframe</b> <iframe width="560" height="315" src="https://www.youtube.com/embed/3eGv-yIr1QE"></iframe> <b>afer iframe</b>'>Click to toggle popover</button>

http://jsfiddle.net/56emxcd1/

**Comment by patrickhlauke** [comment]
iframes are not allowed by default. you'll need to add exceptions for them with the sanitizer. see https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
