### ISSUE TITLE
Dropdowns should not open/trigger on "ESC"

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#28751]
This seems to be a regression from 3.x (see https://github.com/twbs/bootstrap/issues/14646)

Currently, dropdowns https://getbootstrap.com/docs/4.3/components/dropdowns/ can be opened by setting focus to the trigger element and pressing the "ESC" key. It's not a major problem, but non-standard and unexpected behaviour, which should really be removed.

**Comment by pcodedviral** [comment]
hello patrickhlauke,

before pressing "ESC" key please make sure that you are a **focus on dropdown button or link**.

in the demo it will work fine

thanks. . .

**Comment by patrickhlauke** [comment]
aeh...thanks @pcodedviral ... not quite sure what your point is. when focus is on the trigger for the unopened dropdown, ESC should NOT open the dropdown...

**Comment by patrickhlauke** [comment]
this appears to be fixed in v5 (though there's another issue now relating to dropdowns which i'll file as separate problem)

**Comment by XhmikosR** [comment]
@patrickhlauke closing since #28912 was merged a long time ago, but feel free to reopen.
