### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by rranke** [twbs/bootstrap#28754]
Idea:

- Providing a simple Dark-Mode theme in addition to the current default light-colors
- Switch between Light- and Dark-Mode

I know, "themes" and "colors" are a pretty individual thing, but maybe there is a simple and easy way to provide some fundamental stuff to start with when using bootstrap.

Would be cool!
Cheers

**Comment by rranke** [comment]
related to:
https://github.com/twbs/bootstrap/pull/28449
https://github.com/twbs/bootstrap/issues/28424
https://github.com/twbs/bootstrap/issues/28540

**Comment by waterfoul** [comment]
I believe #27514 will satisfy this one

**Comment by mdo** [comment]
Closing for #27514.

**Comment by xcartmods** [comment]
I had a quick go at this here - https://xcartmods.com/bs/
While it's a bit old skool, it might give you some pointers :)

**Comment by rranke** [comment]
> I had a quick go at this here - https://xcartmods.com/bs/
> While it's a bit old skool, it might give you some pointers :)

Yes, this switcher is exactly what is was looking for, thanks for that!
Would be kool, if this will be included in bootstrap in future!
