### ISSUE TITLE
Initialised (but not visible) toast overlaps page content (preventing clicks on page)

### ISSUE THREAD

**Issue by KjelleJ** [twbs/bootstrap#28752]
A Bootstrap toast is not closed (using the close button) before the app is "finished" (reloaded or at browser exit). When the app is started again the buttons under the "invisible toast" cannot be used although they are visible. So it looks like the toast "stays on top" but is invisible.

The solution to the problem is to click the button that shows the toast and close the toast. Now all buttons are clickable.

Bootstrap 4.3.1. Windows 10 Home v1809. Chrome Version 74.0.3729.131.

To see a demo of this problem goto [tutorialrepublic](https://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=toast-methods) and adjust the window size so part of the buttons are under the toast. Press 'Show Toast', reload the page and if you hoover the cursor you can see where the toast was located (arrow instead of hand). See also [stackoverflow](https://stackoverflow.com/questions/56028939/bootstrap-toast-remains-on-top-invisible)

**Comment by Johann-S** [comment]
Hi @KjelleJ,

So that's because by default `opacity` of our toasts is `0` so it's not visible but the `display` property is equal to `block`

Thanks for reporting that 👍 

/CC @twbs/css-review

**Comment by patrickhlauke** [comment]
on that topic, it would be nice if our documentation had an actual live example of a toast that starts out hidden, and is then triggered (just by a simple button). just to see it actually in action (and to potentially debug things like this)

**Comment by mdo** [comment]
Wondering if this is still valid?

**Comment by GeoSot** [comment]
Yes
[Bs4 example](https://jsbin.com/xufojetire/edit?html,output)
[Bs5 example](https://jsbin.com/pedicepixi/1/edit?html,output)

Probably #33610 could do the job, as below
[Example](https://jsbin.com/gugatopiwi/1/edit?html,output)

**Comment by patrickhlauke** [comment]
just as this always confuses me...the issue here has nothing to do with the "after reload" part, right? (because reloading a page would not maintain state or anything like that)
it's simply that an initialised toast is positioned on top of content, even when not visible.

**Comment by GeoSot** [comment]
> 
> 
> just as this always confuses me...the issue here has nothing to do with the "after reload" part, right? (because reloading a page would not maintain state or anything like that)
> it's simply that an initialised toast is positioned on top of content, even when not visible.

Exactly .  if `hide` class is missing, the toast has only `opacity:0`

**Comment by sr13579** [comment]
This problem is solved in 5.2.x . Now the overlapping problem is gone.

**Comment by 4braincells** [comment]
Why not also fixing this in V4? Blocks my language selector and needs a real nasty tweak to get rid of ...
