### ISSUE TITLE
Collapsing table row - Unexpected row height 

### ISSUE THREAD

**Issue by 1anchen** [twbs/bootstrap#28765]
Using `collapse` on a parent table row to display additional child table rows with `<tbody>` on IE, experiencing a jumpy behaviour when the child row is displayed.
(similar but slight different behaviour is occurring in EDGE)  
- Bootstrap 4.3.1 
- IE 11. 648
- Microsoft Edge 42.17134.1.0

Please see the reproduce of this bug
http://jsfiddle.net/y7_7c/sp9h28af/12/

Steps to reproduce :
1. Open above link in IE
2. Click the `+` sign
3. 2 new rows will appear with this behaviour

Screen-shot from IE
![image](https://user-images.githubusercontent.com/37550259/57637129-85b69d00-75a2-11e9-99d3-6572a8d86844.png)

**Comment by XhmikosR** [comment]
FYI the CDN links are http which are blocked at least by Firefox here.

**Comment by 1anchen** [comment]
I have amended the jsfiddle accordingly, please have a look. 

http://jsfiddle.net/y7_7c/sp9h28af/12/

**Comment by XhmikosR** [comment]
I can confirm the behavior with IE 11. With Edge it throws a TypeError thus the jsfiddle output isn't shown here.

**Comment by mdo** [comment]
Closing as a stale won't fix, since v5 drops IE11 and we haven't seen much movement here in almost two years.
