### ISSUE TITLE
about social icon design

### ISSUE THREAD

**Issue by vicky2395** [twbs/bootstrap#28763]
Line (https://line.me/) is a very popular app in Asia and is widely used by the public.  Can you  add place public icon into your icon? Please.....

**Comment by ashfahan** [comment]
Hello @vicky2395 

As stated in bootstrap Docs 

> Bootstrap doesn’t include an icon library by default

however you can use external font libraries like

- [Font Awesome](https://fontawesome.com/)
- [Iconic](https://github.com/iconic/open-iconic)
- [Octicons](https://octicons.github.com/)
- [Bytesize](https://github.com/danklammer/bytesize-icons)
- [Google Material icons](https://material.io/tools/icons/)
- [Ionicons](https://ionicons.com/)
- [Feather](https://feathericons.com/)
- [Dripicons](http://demo.amitjakhu.com/dripicons/)
- [Ikons](http://ikons.piotrkwiatkowski.co.uk/)
- [Glyph](https://glyph.smarticons.co/)
- [Icons8](https://icons8.com/)
- [icofont](https://icofont.com/)

I personally use icofont :)

**Comment by XhmikosR** [comment]
Closing as per the reply above :)
