### ISSUE TITLE
Soften box-shadow

### ISSUE THREAD

**Issue by ashfahan** [twbs/bootstrap#28761]
Default :
![before](https://user-images.githubusercontent.com/19289015/57580982-2edd9480-74ca-11e9-84ea-067f0260b9dc.png)

After : 
![after](https://user-images.githubusercontent.com/19289015/57580991-3e5cdd80-74ca-11e9-8414-472c0bd037b6.png)

any thoughts of changing the box-shadow of form-control and button to soften out.
*ignore the change in color value and icon

I can submit pull request to change it all around .

the link to example is given below
https://jsfiddle.net/ashfahan/sxz72ay8/

**Comment by mdo** [comment]
Thanks, but we'll be leaving it as-is for now.
