### ISSUE TITLE
Small/large file chooser

### ISSUE THREAD

**Issue by AnReZa** [twbs/bootstrap#28769]
Right now, it looks like there aren't small or large file choosers. That's problematic, when you want to use the file chooser in a form, where all other fields are small. In the end, it looks rather ugly.

Or is there something, that I've missed or overlooked?

I already opened this ticket, but they say, that it's a bootstrap issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/3285

**Comment by mhatvan** [comment]
not sure if I understand the issue correctly, but did you try to add the classes `btn-sm` or `btn-lg` to the `<input type="file" />` ?

**Comment by AnReZa** [comment]
At least not directly. bootstrap-vue usually adds the correct classes to the DOM element(s), if you set the size property of its corresponding control (in this case `b-form-file`). But it seems like small or large file choosers simply don't exist at all right now. Therefore, bootstrap-vue can't set anything, because that functionality simply isn't implemented into bootstrap yet.
