### ISSUE TITLE
Animation effects not working on Chrome and Firefox on Windows 7

### ISSUE THREAD

**Issue by tightcode** [twbs/bootstrap#28772]
Animation effects for components such as collapse and carousel (in versions 4.2.1 and 4.3) are not working on Chrome (version 74 64-bit) and Firefox (version 65+ 64-bit and possibly others between it and version 61.02 64-bit, which is not affected) on Windows 7 64-bit.

**Comment by XhmikosR** [comment]
Seems like a duplicate of many issues, example #28300

**Comment by tightcode** [comment]
It is apparently specifically related to that issue, with the browser updates triggering support for the prefers-reduced-motion CSS media feature.
