### ISSUE TITLE
Carousel can not work well on Chrome --Version 74.0.3729.157 (official version) (64 bits)

### ISSUE THREAD

**Issue by LurenAA** [twbs/bootstrap#28776]
just like this gif， I recorded this in https://getbootstrap.com/docs/4.3/components/carousel/

![GIF](https://user-images.githubusercontent.com/45759613/57837379-4a5fdc80-77f5-11e9-8517-3f6ed4efaf49.gif)

I tried in Edge and ie, Carousel can work well.

In Windows，the code is the Example in https://getbootstrap.com/docs/4.3/components/carousel/

![image](https://user-images.githubusercontent.com/45759613/57838224-de7e7380-77f6-11e9-8105-4f958869f076.png)

**Comment by LurenAA** [comment]
In Windows，the code is the Example in https://getbootstrap.com/docs/4.3/components/carousel/，
![image](https://user-images.githubusercontent.com/45759613/57838224-de7e7380-77f6-11e9-8105-4f958869f076.png)

**Comment by Johann-S** [comment]
Hi @LurenAA,

Can you explain how do you get this behavior ? I'm unable to reproduce it on Chrome with Win10

**Comment by XhmikosR** [comment]
I actually noticed this with v3.3.7 and Brave mobile which is based on Chrome 74. I will check with v4 later.

Refreshing or doing a full cycle or a combination of both "fixed" it, which is weird.

**Comment by XhmikosR** [comment]
I cannot reproduce on Windows 10 with Chrome 74.

I believe it's an issue with the Windows accessibility settings.

Please try searching the existent issues https://github.com/twbs/bootstrap/issues/28772

**Comment by LurenAA** [comment]
> Hi @LurenAA,
> 
> Can you explain how do you get this behavior ? I'm unable to reproduce it on Chrome with Win10

Thank you ，I find the reason is that I use a Browser plug-ins namd AdGuard AdBlocker

**Comment by XhmikosR** [comment]
Hehe even worse :P

**Comment by luck2011** [comment]
+1

**Comment by laurenthiernard** [comment]
Noticed the same problem. Opening Chrome in Incognito fix it -  so yeah probably from one of my extensions.
