### ISSUE TITLE
!important scattered throughout Bootstrap CSS files

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#28770]
Bootstrap includes many `!important` keywords throughout the stylesheets, which makes customization of Bootstrap themes unnecessarily difficult. This happens, for example with colors, such as in the main Bootstrap dark theme.

**Comment by XhmikosR** [comment]
This is by design so that the utilities have the desired effect.

If one wants to customize things further they have to do it via the Sass files.

**Comment by mdo** [comment]
Yes, this is intentional.
