### ISSUE TITLE
File to import not found or unreadable: ../bootstrap/scss/_normalize.

### ISSUE THREAD

**Issue by Chubek** [twbs/bootstrap#28794]
I'm converting an old Vue frontend from Webpack 2 to Webpack 4. I have deleted the node_modules file and used ncu to upgrade everything. Then I ran install again. Then, I deleted the build folder, and ran webpack-cli init. However, Webpack is saying:

`File to import not found or unreadable: ../bootstrap/scss/_normalize.`

I have ack'd _normalize and "_normalize" and nothing came up. What's the problem?

**Comment by wolfy1339** [comment]
Bootstrap no longer uses normalize. It has been that way for a very long time in the lifecycle of v4

**Comment by XhmikosR** [comment]
Like wolfy1339 says, there's no such file from our side.
