### ISSUE TITLE
CSS Bug if $card-border-width: 0;

### ISSUE THREAD

**Issue by endcoreAK** [twbs/bootstrap#28792]
Hey there,

if I set the `$card-border-width` to "0", 
the output will look like this and ends in an error (at least Chrome):

`.card-img { border-radius: calc(0.25rem - 0); }`

As a workaround I also had to change:

`$card-inner-border-radius: calc(#{$card-border-radius} - #{$card-border-width});`

to 

`$card-inner-border-radius: $card-border-radius;`

Maybe it's possible to fix this (small) issue. :) 

Kind regards
André

**Comment by TheCynster** [comment]
I would like to look into this issue

**Comment by endcoreAK** [comment]
I just saw that I had a copy/paste error in the last code. So please use the updated when testing. :)

**Comment by TheCynster** [comment]
Could you give more details about what you are doing? I haven't been able to recreate this issue.

**Comment by endcoreAK** [comment]
Hope this will help :) https://jsfiddle.net/tudm9xLg/

**Comment by florianlacreuse** [comment]
Try with `$card-border-width: 0px` as a workaround.

**Comment by endcoreAK** [comment]
I didn't even think of that, that solves the problem. Thanks :)

**Comment by florianlacreuse** [comment]
Good to hear! Does this issue still have to be open or can you close it? Thanks.

**Comment by endcoreAK** [comment]
I don't know if it's necessary, but maybe BT can extend the function with an if query, since with 0px you don't need the calc attributes at all. Also I wouldn't specify "0px" instead of "0 or none" for the `border-width` via CSS. imho

**Comment by aditya1906** [comment]
does if else in scss solve the problem?
