### ISSUE TITLE
change carousel-indicators style

### ISSUE THREAD

**Issue by forghan89** [twbs/bootstrap#28791]
![Capture1](https://user-images.githubusercontent.com/47449690/57978970-dd825780-7a2b-11e9-94c8-c28e463835ea.PNG)

Many users want to change the carousel indicators style, 
so please add two classes below:

- **square** :
**.carousel-indicators-square**

`.carousel-indicators-square{
width: 14px;
height: 14px;
}`

![Capture2](https://user-images.githubusercontent.com/47449690/57978976-ff7bda00-7a2b-11e9-904d-2564ea8f7bac.PNG)

- **round** :
**.carousel-indicators-round**

`.carousel-indicators-round{
width: 14px;
height: 14px;
border-radius: 100%;
}`

![Capture3](https://user-images.githubusercontent.com/47449690/57979017-9e083b00-7a2c-11e9-9606-5bc90c65ee95.PNG)

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/28815#issuecomment-496408360.

**Comment by CJpaekil** [comment]
Dear
How can I change the style when I click third indicator?

**Comment by 7CodeWizard** [comment]
Hi there? your skill is very good, I wanna ask you sth.
![Screenshot 2024-09-04 100735](https://github.com/user-attachments/assets/68a8395a-e29b-4204-a477-d8ef364cac8d)
I am trying to make this slide indicators, then I can't do that. Can you help me to do this?
