### ISSUE TITLE
Override buttons and input paddings and font

### ISSUE THREAD

**Issue by e30alex** [twbs/bootstrap#28793]
I'm trying to change de padding for the buttons and inputs. I modified the $input-btn-padding-y, $input-btn-padding-x and $input-btn-font-size. These variables are included before the bootsrap core variables and are not working. 

If i define these variables too, all the things are working correctly:
$btn-padding-y:               $input-btn-padding-y;
$btn-padding-x:               $input-btn-padding-x;
$btn-font-size:               $input-btn-font-size;

$input-padding-y:             $input-btn-padding-y;
$input-padding-x:             $input-btn-padding-x;
$input-font-size:             $input-btn-font-size;

This is not the easiest way because there are a lot of places where the main variables are assigned. Any idea? Thanks!

**Comment by MartijnCuppens** [comment]
The way you described this should work. Have a look at https://getbootstrap.com/docs/4.3/getting-started/theming/#sass to find out what's could be the reason why things are going wrong.
