### ISSUE TITLE
Checkbox shadow should not be cropped when focused

### ISSUE THREAD

**Issue by AntoineMirande** [twbs/bootstrap#28799]
Hi,

I noticed there is no margin on _custom-control-input_ and it would be great to have one so the shadow around a clicked checkbox cannot be cropped by a parent element.

In my case, the checkbox is in a label element with overflow: hidden.

![Capture](https://user-images.githubusercontent.com/23663643/58088422-3ea95700-7bf5-11e9-95f2-5a2798fbb288.PNG)

**Comment by mdo** [comment]
No way around this I'm afraid. You'll need to release the `overflow` or otherwise modify the markup.
