### ISSUE TITLE
fatal error - cygheap base mismatch detected - 0x13A1410/0x13D1410

### ISSUE THREAD

**Issue by rezaee** [twbs/bootstrap#28790]
I was trying to install `poppe` using this command `npm install popper --save` but I got a bunch of errors like this error message:

          3 [main] sh (28644) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x13A1410/0x13D1410.
    This problem is probably due to using incompatible versions of the cygwin DLL.
    Search for cygwin1.dll using the Windows Start->Find/Search facility
    and delete all but the most recent version.  The most recent version *should*
    reside in x:\cygwin\bin, where 'x' is the drive on which you have
    installed the cygwin distribution.  Rebooting is also suggested if you
    are unable to find another cygwin DLL.
          1 [main] sh 956 fork: child -1 - forked process 28644 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
          2 [main] sh (24104) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x13A1410/0x11B1410.

What is the problem and how can I fix?

**Comment by patrickhlauke** [comment]
As this is clearly a problem with cygwin/your particular command line setup, and not bootstrap itself, i'd recommend asking on stackoverflow or similar. see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
