### ISSUE TITLE
Order Class

### ISSUE THREAD

**Issue by Quocnamit** [twbs/bootstrap#28800]
Hi,

I can't see the the .order-# class in bootstrap 4v0.0.6. I download the css file and use it directly

Please advice

Thanks,

**Comment by alecpl** [comment]
Where did you get that css file from? What is 4v0.0.6? If that's v4.0.0-alpha.6 then it indeed does not contain it. You need at least the 4.0.0 release.

**Comment by Quocnamit** [comment]
Thanks @alecpl downloaded wrong version
