### ISSUE TITLE
Collapse does not work with element ID consisting only of digits.

### ISSUE THREAD

**Issue by trafium** [twbs/bootstrap#28806]
macOS Sierra 10.12.6, Chrome 74.0.3729.131, https://codepen.io/anon/pen/xNPobM

**Comment by Johann-S** [comment]
Hi @trafium that's because only digits it's not a valid CSS selectors.

You'll find more information here:
https://getbootstrap.com/docs/4.3/getting-started/javascript/#selectors
https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

**Comment by trafium** [comment]
@Johann-S Thanks! Was confused by specs saying that id in HTML 5 can be anything but space character. Did not suspect that a valid id attribute might be invalid as selector.
