### ISSUE TITLE
HTML form inside popper?

### ISSUE THREAD

**Issue by hartey11** [twbs/bootstrap#28803]
Hi,
Is it possible to include a form inside a popper? I've included a CodePen with the HTML and js that I'm using. The popper shows but it's empty.

CodePen demo
https://codepen.io/hartey11/pen/byYaxP

Steps to reproduce the problem
Use do_shortcode() to add a form to a popper data attribute
popper is empty
What is the expected behaviour?
To see the form within the popper

Any other comments?
Using WordPress plugin search filter pro to generate the form

**Comment by hartey11** [comment]
I've seen examples of it working but for some reason, form elements are stripped out when I try to do it. Has this been removed in v4 or something?

**Comment by Johann-S** [comment]
Hi @hartey11,

We added a sanitizer for our Tooltips and Popovers to remove dangerous html elements.
You'll find more informations here: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

And if you want to whitelist `<form>`s element you'll find an example on how to do that here: 
https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
