### ISSUE TITLE
multiple items responsive carousel

### ISSUE THREAD

**Issue by eturerer** [twbs/bootstrap#28801]
using ecommerce sites.
https://prnt.sc/nrdial

We use swiper as mandatory. problem for google speed. loading extra swiper
example
https://idangero.us/swiper/demos/380-responsive-breakpoints.html

var swiper = new Swiper('.swiper-container', {
      slidesPerView: 5,
      spaceBetween: 50,
      // init: false,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      breakpoints: {
        1024: {
          slidesPerView: 4,
          spaceBetween: 40,
        },
        768: {
          slidesPerView: 3,
          spaceBetween: 30,
        },
        640: {
          slidesPerView: 2,
          spaceBetween: 20,
        },
        320: {
          slidesPerView: 1,
          spaceBetween: 10,
        }
      }
    });

we want a responsive carousel.

**Comment by wilsonmontelo** [comment]
Why do not you use bootstrap carousel? so I saw the elements are already adjusting to the browser. What behavior did you want?

**Comment by mdo** [comment]
Thanks, but we'll pass on this.
