### ISSUE TITLE
https://bootstrap-slack.herokuapp.com/ not working 

### ISSUE THREAD

**Issue by ZaidBarghouthi** [twbs/bootstrap#28805]
Getting: 

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

**Comment by XhmikosR** [comment]
@mdo: we should change to the new Slack, right?

**Comment by mdo** [comment]
What's the new Slack?

**Comment by patrickhlauke** [comment]
https://getbootstrap.slack.com ?

**Comment by XhmikosR** [comment]
So, it seems the URLs are fine, the app has some issues. We need to wait until @mdo sorts it out.

**Comment by mdo** [comment]
`https://getbootstrap.slack.com` is the right URL for how to sign into the Slack, but there's currently no free signup flow for "public" Slack channels. They actively discourage it. `https://bootstrap-slack.herokuapp.com/` is an app called Slackin that gets around this for us.

For some reason, the Heroku app is all messed up. At a conference and can't fix right now.

**Comment by XhmikosR** [comment]
@mdo ping

**Comment by mdo** [comment]
I think the `slackin` project has seemed unmaintained and busted. Just saw there was an update last week to the project's readme, so maybe something is better now? Will look again.

https://github.com/rauchg/slackin

**Comment by bradrhine** [comment]
With the Heroku app being temperamental, is there a different way to get an invitation to the Bootstrap Slack channel? Thanks!

**Comment by mdo** [comment]
**Use this invite link:** https://join.slack.com/t/getbootstrap/shared_invite/enQtNjQ4MzI2NDc3NDU4LWI0YWVlN2I0ZjBkZWMxNWRmNzU1ODIzMTM5OTg4MmZiZmYwY2I2M2EyMTE0ZWRiOWIzZTQxMjI1YmRmNTg3ZmU

**Comment by bradrhine** [comment]
Sweet! Thank you!

**Comment by mdo** [comment]
Closing this now since we have our Slack invite page working today.

**Comment by bhaveshjadav713** [comment]
Hi @mdo  I want your help.
Can you please tell me where can i contact to you 
Any contact details like WhatsApp, skype or email ?
