### ISSUE TITLE
Carousel does not respond to the first click on arrows after being swiped with touch first  [Chrome - Android]

### ISSUE THREAD

**Issue by StayCoolDK** [twbs/bootstrap#28819]
Bootstrap 4.3.1
Operating system: Android 9 - OxygenOS 9.0.13
Browser and version: Google Chrome - 74.0.3729.157
(this can also be replicated on Microsoft Edge for Android - 42.0.2.3438)

Test case:
https://getbootstrap.com/docs/4.3/components/carousel/ 

- On initial load start out by swiping ONCE in either direction.
- After the swipe try clicking on an arrow in either direction:
* The first click on either arrow does nothing (non-responsive).
* The second click on either arrow does as expected (responsive).  

Minor note: I can see that the arrows get a slightly different grey color after being clicked, however this only happens after the second click (if i swipe first), so it seems to be an issue with the click event after swiping?

**Comment by XhmikosR** [comment]
Works fine for https://getbootstrap.com/docs/4.3/components/carousel/, tested on Android with latest Chrome.

Something else is wrong on your code. Try making a reproducible example on Codepen.

**Comment by StayCoolDK** [comment]
Nothing is wrong with my code. The issue is present for me in the official documentation which my code is simply a copy off. Perhaps its a niche issue for Oneplus phones - which runs a own custom version of Android (Oxygen OS).

**Comment by XhmikosR** [comment]
Well, I cannot confirm what you are saying. We test with various Browsers on BrowserStack and it works as expected there.

**Comment by Erickatransgenderdeveloper** [comment]
Wait one second did dudes just call me a spam bot what the fizzy how heck im AFROTRANGENDER HUMAN MARKS

**Comment by patrickhlauke** [comment]
Confirming that I also tried with a Pixel 2 and latest Chrome and couldn't reproduce the problem. It would be odd that the actual OS of the phone would have any influence on this, unless Oxygen really does something odd/extra when it comes to touch/pointer events...

**Comment by patrickhlauke** [comment]
revisiting this, as it niggled in the back of my mind. and it seems that it does happen, at least on first load. not quite sure why/how it's happening, but indeed swiping first and then trying the button to go the other way of the swipe, the first tap is ignored.

**Comment by StayCoolDK** [comment]
@patrickhlauke Have you had time to check out this issue any further? Do you only see the issue on the very first load? Because i'm experiencing it on every reload, not only the initial load.

**Comment by mdo** [comment]
Safe to close as stale ahead of v5?

**Comment by patrickhlauke** [comment]
i've actually not been able to reproduce the issue, or at least not noticed it consciously, in my recent messing with carousels. not sure if this is something in our code or something that's more of a specific implementation/browser bug. i'd say close for now.
