### ISSUE TITLE
v4.3.1 -> IE11 Support

### ISSUE THREAD

**Issue by interactivevalues** [twbs/bootstrap#28811]
When I integrate the js-files collapse and tooltip IE11 throws an error and stops the whole js-part.
Is this a global problem or just me? With older versions of v4 I didn't run into this IE problem.

looks like IE thinks this line is not good for him ;)
const EVENT_KEY           = `.${DATA_KEY}` in collapse.js
The error-message is: Invalid character

**Comment by interactivevalues** [comment]
**UPDATE:**
when using the dist not the src version it works

**Comment by Johann-S** [comment]
Hi @interactivevalues,

Only our dist files should be used in a browser, that's mean JS files in `dist/js/` and `js/dist/`.

**Comment by interactivevalues** [comment]
I used the src in my setup and bundled all with webpack. so I thought src is ok. @Johann-S

**Comment by Johann-S** [comment]
If you want to use our `src` files be sure to tell Babel or any other transpiler to transpile Bootstrap
