### ISSUE TITLE
.row within responsive table causes horizontal overflow

### ISSUE THREAD

**Issue by fschick** [twbs/bootstrap#28816]
A grid (.row) inside a responsive table causes a horizontal scrollbar. It appears at least with FF, IE and Chrome running Windows 10. Example: [https://www.bootply.com/WnFBMNiTKB](https://www.bootply.com/WnFBMNiTKB)
```
<div class="container">
 <div class="table-responsive">
  <table class="table">
	<tr>
	 <td>
	  <div class="row">
	   <div class="col">C1</div>
	  </div>
	 </td>
	</tr>
  </table>
 </div>
</div>

```

Quick fix:
```
.table-responsive .table .row {
    margin-right: 0;
}
```

**Comment by ashfahan** [comment]
in Bootstrap 4 they have no-gutters class that removed margin and padding over row and col respectively 
use that ?

if you are using bootstrap 3 add this css code to use no-gutters class

`.no-gutters {
  margin-right: 0;
  margin-left: 0;
}

.no-gutters > .col,
.no-gutters > [class*="col-"] {
  padding-right: 0;
  padding-left: 0;
}
`

**Comment by ashfahan** [comment]
in Bootstrap 4 they have no-gutters class that removed margin and padding over row and col respectively
use that ?

if you are using bootstrap 3 add this css code to use no-gutters class

.no-gutters {
margin-right: 0;
margin-left: 0;
}

.no-gutters > .col,
.no-gutters > [class*="col-"] {
padding-right: 0;
padding-left: 0;
}

**Comment by fschick** [comment]
I'm using Bootstrap 4.3.1. Using no-gutters is certainly better than a custom fix.
Even having a slightly different context, it might be related to https://github.com/twbs/bootstrap/issues/8959.
Not sure, if it should still handled as bug. When it's by design or won't fix it can be closed.

**Comment by ashfahan** [comment]
@fschick #8959 was related to bootstrap 3 and bootstrap 4 was released in suggest 2017.

and i thought you are using bootstrap 3 because the link to your example uses bootstrap 3.

**Comment by fschick** [comment]
Yes, the ticket https://github.com/twbs/bootstrap/issues/8959 is very old, for bootstrap 3 and closed. But similar.
The link from above [https://www.bootply.com/WnFBMNiTKB](https://www.bootply.com/WnFBMNiTKB) shows 'Bootstrap v4.3.1' to me. Whatever, I will be more precise in future.
Do you like to handle the issue itself as bug or should it be closed?

**Comment by ashfahan** [comment]
i think it should be closed :)

**Comment by fschick** [comment]
Closed because there is a usable workaround
