### ISSUE TITLE
Could we have navbar type menu functionality for nav-tabs?

### ISSUE THREAD

**Issue by johnaau** [twbs/bootstrap#28810]
nav-tabs look great on desktops but on mobiles/small screens if the tabs don't fit on one line then they don't look so good and can take up too much vertical space.

It would be great if we could set a breakpoint for nav-tabs to collapse down to a navbar style menu with hamburger.

Ideally the active tab would be shown (might not be possible with CSS only) along with a hamburger button which when pressed would toggle display of the other tabs as a vertical menu.

Example:

![Untitled-1](https://user-images.githubusercontent.com/6590573/58217194-f13bff80-7d44-11e9-80ee-ddedc534b329.jpg)

Maybe it could look something like this once collapsed:

![Untitled-2](https://user-images.githubusercontent.com/6590573/58217541-9d321a80-7d46-11e9-89bb-0a6f8daa7477.jpg)

**Comment by mdo** [comment]
The code required to do this is limited to our navbar—it requires additional markup in its current implementation than the tabs. I don't think we'll add something like this right now.
