### ISSUE TITLE
Popover regression from 4.2.x to 4.3.x

### ISSUE THREAD

**Issue by jenstroeger** [twbs/bootstrap#28812]
(Mac OS Mojave 10.14.4, Chrome 74.0.3729.157)

It looks like more complex `data-content` for a [Popover](https://getbootstrap.com/docs/4.3/components/popovers/) is not rendered correctly. For example, these two spans with a popover ([fiddle](https://jsfiddle.net/awjLxzhv/1/)):
```html
<span id="span-id-1" data-toggle="popover" data-placement="right" data-html="true" title="Title" data-content="<button type='button' class='btn btn-secondary btn-sm' id='btn-id-1'>Button</button>">POP</span>
<span id="span-id-2" data-toggle="popover" data-placement="right" data-html="true" title="Title" data-content="&lt;button type='button' class='btn btn-secondary btn-sm' id='btn'&gt;Button&lt;/button&gt;">POP</span>
```
 work fine with [v4.2.1](https://usebootstrap.com/cdn/4.2.1)

![popover-4 2 1](https://user-images.githubusercontent.com/12053937/58236268-e2297180-7d85-11e9-958d-c1dc359c1589.jpg)

but the button in the Popover disappear when I switch to [v4.3.2](https://usebootstrap.com/cdn/4.3.1)

![popover-4 3 1](https://user-images.githubusercontent.com/12053937/58236278-e6ee2580-7d85-11e9-9798-b99f32c8e4b3.jpg)

This seems to be the case with input elements in general, whereas text in `p` and `span` shows up ok.

**Comment by Johann-S** [comment]
Hi @jenstroeger,

That's the correct behavior and you'll find why by reading that: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

And you'll find how to fix that behavior here: https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer

BTW it's a good practice to read changelogs when you update any libs 👍

**Comment by jenstroeger** [comment]
@Johann-S, ugh, yes I missed that. All fixed and working now again, thank you 👍🏼
