### ISSUE TITLE
Move carousel caption outside carousel 

### ISSUE THREAD

**Issue by gardezii** [twbs/bootstrap#28827]
OS: Mac
Browser: 74.0
Bootstrap version: 4.1.1

Hello guys, I'm trying to move the caption outside the coursel but the problem it's not working.  When ever it moves outside its parent container it's stop showing. Can somebody please help me out. Here is ia JS bin link --> https://jsbin.com/gikatihesu/edit?html,output

**Comment by XhmikosR** [comment]
What's not working exactly? In the jsbin above you have only one carousel item, the other 2 are commented out.

**Comment by XhmikosR** [comment]
Also, please use the latest stable version of Bootstrap and jQuery.

**Comment by mdo** [comment]
Sorry, but we don’t provide support for customizing Bootstrap. This is technically possible, but I don’t have any code to help or demo it. I’d suggest asking in StackOverflow or in our Slack, both are linked from the readme.
