### ISSUE TITLE
Article clarity. 

### ISSUE THREAD

**Issue by polishedwp** [twbs/bootstrap#28822]
I am new to Bootstrap and am digging through the documentation. I came across the following that is unclear. 

In `Documentation/Theming` in the [Remove from map](https://getbootstrap.com/docs/4.0/getting-started/theming/#remove-from-map) section, the code examples is as follows:

```
$theme-colors: map-remove($theme-colors, "success", "info", "danger");
```
However, just below this area in [Required keys](https://getbootstrap.com/docs/4.0/getting-started/theming/#required-keys) the paragraph reads in part:

```
For example, we use the primary, success, and danger keys from $theme-colors for links, buttons, 
and form states. Replacing the values of these keys should present no issues, 
but removing them may cause Sass compilation issues. 
```
This paragraph, in essence, contradicts the code example indicated. 

## Suggestion
For clarity, it might be better to uses a different example in the `Remove from map` section. Something like this for instance:
```
$theme-colors: map-remove($theme-colors, "secondary", "info", "light");
```
If this is acceptable, I will be glad to open a PR.

**Comment by ysds** [comment]
The latest documentation has already been fixed 👍 

https://getbootstrap.com/docs/4.3/getting-started/theming/#remove-from-map
