### ISSUE TITLE
Navbar randomly change font size

### ISSUE THREAD

**Issue by TheAccountant1** [twbs/bootstrap#28831]
- Operating system: MacOS Mojave 10.14.6
- Browser: Safari 12.1.2

I have "over-written" the font-size of the link of the navbar with

.my-class {
	font-size: 0.9rem;
}

Sometimes it happens that the font size in the browser is slightly bigger or smaller and, when smaller, :hover make it bigger. It happens just with Safari, that's why I think it's a bug.

Thanks,
SF

**Comment by patrickhlauke** [comment]
as per issue template, we need to see an actual live reduced test case of this happening.

**Comment by mdo** [comment]
Closing, doesn't sound like a bug with Bootstrap given the custom styles.
