### ISSUE TITLE
Mailchimp ad at the top of every doc page is extremely annoying

### ISSUE THREAD

**Issue by danchaseCTS** [twbs/bootstrap#28838]
Basically this made me go back to google and use w3schools instead, I kept reading the ad thinking I was reading about whatever component I clicked on. I can't think of a worst place to put something unrelated to the page. I imagine they pay well for this, because well, who would do that otherwise.

**Comment by danchaseCTS** [comment]
> Basically this made me go back to google and use w3schools instead, I kept reading the ad thinking I was reading about whatever component I clicked on. I can't think of a worst place to put something unrelated to the page. I imagine they pay well for this, because well, who would do that otherwise.

Let's put it this way - it was annoying enough that I actually took the time to go find the github, and post an objection. oh my god is still echoing in the back of my head, I don't think I ever want to see mailchimp or anything related to it again after browsing for about 20 mins :)

**Comment by mdo** [comment]
I haven’t seen the specific ad you’re talking about, so if there’s a problem with it, please elaborate here and screenshot it. From there I can report an egregious ad to the ad network and block it. Otherwise, you’re more than welcome to shield yourself from any and all ads with an ad blocker in your browser.

**Comment by dannychase2004** [comment]
Now that I am a bit more calm, I realize my complaint looks to be about mailchimp specifically, but its not, rather the placement being in the worst possible place and on a doc page. Who exactly is paying for the development of bootstrap nowadays, that is, who wanted ad revenue, twitter?..  oh well I say just pay the developers.
