### ISSUE TITLE
Migration Documentation

### ISSUE THREAD

**Issue by BillyErwin** [twbs/bootstrap#28835]
I am upgrading from 2.x to 3.4.1.  Going through the migration documentation, it seems there may be some mistakes mapping old classes to new ones, although, I could be totally wrong.
https://getbootstrap.com/docs/3.4/migration/#classes under the major class changes section, it appears that some of the accordion to panel classes may be wrong.  I am working on documenting the internal changes we need to make to our code base and I want to make sure these are accurate.
![Screen Shot 2019-05-28 at 9 30 49 AM](https://user-images.githubusercontent.com/16211472/58481897-5455d980-812b-11e9-90c9-f48e83c619f7.png)

**Comment by mdo** [comment]
Help with upgrading from v2 to v3 isn't supported here, sorry. We've been on v4 for well over a year. The documentation, however, should be correct. If there is a specific problem you're running into, versus things _seeming_ to be wrong, please ask around in our Slack.
