### ISSUE TITLE
Tabs border color on card header should be match the card border color?

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#28837]
Tab's border and card's border have different color.

<img width="432" alt="スクリーンショット 2019-05-29 2 22 54" src="https://user-images.githubusercontent.com/4065765/58498278-b14ba100-81b8-11e9-9545-2e4a24149808.png">

https://codepen.io/anon/pen/KLBbwz

Those should be the same color?

**Comment by kaderi** [comment]
It's not a border color problem, try to add some padding to .na-link.active

**Comment by mendozagioo** [comment]
@ysds  Card and nav are different components, try to config variable: `$nav-tabs-link-active-border-color`

**Comment by mdo** [comment]
Closing as a stale won't fix. No plans to support this via utilities or additional classes. If you need this, you'll have to finish the customization yourselves.
