### ISSUE TITLE
Theming with CSS Variables

### ISSUE THREAD

**Issue by martinschaible** [twbs/bootstrap#28832]
File : _root.scss

To simplify and extending theming with bootstrap, i would recommend to change this to

:root, [data-theme="default"] {
  ...
  ...
}

Introducing [data-theme="default"] to all CSS variables would give us new ways to switch themes at runtime.

**Comment by mdo** [comment]
Since we only offer a fraction of our variables as custom properties, I don’t think this would net us or you much of a win here. Good to note for the future though!
