### ISSUE TITLE
IE10/11 :  carousel image spacing issue

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#28839]
hello sir,

I am using **windows 10** with **chrome and IE lettest version** browse.

- when I am using **carousel** in a **different column** then its work very fine in chrome or firefox.
- but if I am run code in **IE 10/11** then in **smaller column carousel** will make **bottom space**.
- I have attached **one demo file** please try to **run this file in chrome and IE10/11** 

[demo.zip](https://github.com/twbs/bootstrap/files/3230762/demo.zip)

- please give us a solution for IE10/11

**Comment by ysds** [comment]
Bug reports must include a **live demo**. Don't attach a zip file. Please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link.

**Comment by pcodedviral** [comment]
@ysds in zip file demo will include check carefully

**Comment by pcodedviral** [comment]
https://svelte-rbums1.stackblitz.io

**Comment by ysds** [comment]
@pcodedviral Thank you. I forked and updated the pen:

* https://codepen.io/fellows3/pen/QRJmmx
* https://s.codepen.io/fellows3/debug/QRJmmx/mVAbGpzzKxVk (debug view)

A workaround is add `min-height: 1px` to the `.card-body`. I'll create a PR later.

**Comment by pcodedviral** [comment]
@ysds thanks for the **response**,
please give me **informed** once a **bug is resolved**

**Comment by XhmikosR** [comment]
Does this happen with IE11 too? If so we need a fix in master @ysds preferably.

**Comment by ysds** [comment]
Yep, reproducible in IE10 and IE11.

**Comment by pcodedviral** [comment]
hello can problem was solved ???
