### ISSUE TITLE
What is fusv?

### ISSUE THREAD

**Issue by ZaidBarghouthi** [twbs/bootstrap#28840]
What is `fusv` seen in [package.json](https://github.com/twbs/bootstrap/blob/072622d95943d2c2c57f5cfb44c509829c5e26fb/package.json#L34)

```json
"css-lint-vars": "fusv scss/ site/static/",
```

Thanks!

**Comment by Johann-S** [comment]
Hi @ZaidBarghouthi,

It's a npm package: https://www.npmjs.com/package/find-unused-sass-variables we use to find unused scss variables.

It's made by @XhmikosR and myself

**Comment by ZaidBarghouthi** [comment]
@Johann-S Thank you )
