### ISSUE TITLE
Refactor input range

### ISSUE THREAD

**Issue by djibe** [twbs/bootstrap#28848]
Hi, I don't want to mess up all your PR so I propose my code here for faster and easier input-range customization. I introduce a pseudo-selector for cross-browser common styles.

Please show some mercy ;-)

// Range
//
// Style range inputs the same across browsers. Vendor-specific rules for pseudo
// elements cannot be mixed. As such, there are no shared styles for focus or
// active states on prefixed selectors.
%range-thumb {
	width: $custom-range-thumb-width;
	height: $custom-range-thumb-height;
	@include gradient-bg($custom-range-thumb-bg);
	border: $custom-range-thumb-border;
	@include border-radius($custom-range-thumb-border-radius);
	@include box-shadow($custom-range-thumb-box-shadow);
	@include transition($custom-forms-transition);
	appearance: none;
	
	&:active {
      @include gradient-bg($custom-range-thumb-active-bg);
    }
}

%range-track {
	width: $custom-range-track-width;
  height: $custom-range-track-height;
  color: transparent;
  cursor: $custom-range-track-cursor;
	background-color: $custom-range-track-bg;
  border-color: transparent;
	@include box-shadow($custom-range-track-box-shadow);
}

.custom-range {
  width: 100%;
  height: calc(#{$custom-range-thumb-height} + #{$custom-range-thumb-focus-box-shadow-width * 2});
  padding: 0; // Need to reset padding
  background-color: transparent;
  appearance: none;

  &:focus {
    outline: none;

    // Pseudo-elements must be split across multiple rulesets to have an effect.
    // No box-shadow() mixin for focus accessibility.
    &::-webkit-slider-thumb { box-shadow: $custom-range-thumb-focus-box-shadow; }
    &::-moz-range-thumb     { box-shadow: $custom-range-thumb-focus-box-shadow; }
    &::-ms-thumb            { box-shadow: $custom-range-thumb-focus-box-shadow; }
  }

  &::-moz-focus-outer {
    border: 0;
  }

  &::-webkit-slider-thumb {
    @extend %range-thumb;
    margin-top: ($custom-range-track-height - $custom-range-thumb-height) / 2; // Webkit specific
  }

  &::-webkit-slider-runnable-track {
    @extend %range-track;
    @include border-radius($custom-range-track-border-radius);
  }

  &::-moz-range-thumb {
    @extend %range-thumb;
  }

  &::-moz-range-track {
    @extend %range-track;
    @include border-radius($custom-range-track-border-radius);
  }

  &::-ms-thumb {
    margin-top: 0; // Edge specific
    margin-right: $custom-range-thumb-focus-box-shadow-width; // Workaround that overflowed box-shadow is hidden.
    margin-left: $custom-range-thumb-focus-box-shadow-width;  // Workaround that overflowed box-shadow is hidden.
    @extend %range-thumb;
  }

  &::-ms-track {
    @extend %range-track;
    border-width: $custom-range-thumb-height / 2;
  }

  &::-ms-fill-lower {
    background-color: $custom-range-track-bg;
    @include border-radius($custom-range-track-border-radius);
  }

  &::-ms-fill-upper {
    margin-right: 15px; // arbitrary?
    background-color: $custom-range-track-bg;
    @include border-radius($custom-range-track-border-radius);
  }

  &:disabled {
    &::-webkit-slider-thumb {
      background-color: $custom-range-thumb-disabled-bg;
    }

    &::-webkit-slider-runnable-track {
      cursor: default;
    }

    &::-moz-range-thumb {
      background-color: $custom-range-thumb-disabled-bg;
    }

    &::-moz-range-track {
      cursor: default;
    }

    &::-ms-thumb {
      background-color: $custom-range-thumb-disabled-bg;
    }
  }
}

**Comment by ysds** [comment]
Don't worry about creating a PR. Suggesting improved code in a PR will helps reduce our load more than opening an issue that has such a long code attached like this 😉

Closing this for now, but feel free to open a PR, thanks.
