### ISSUE TITLE
Modal dialog closes when dragging and releasing mouse button outside dialog in the new Google Chrome update Version 74.0.3729.169 

### ISSUE THREAD

**Issue by akashishu777** [twbs/bootstrap#28844]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows)
- Browser and version Google Chrome Version 74.0.3729.169 
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

[Example](https://plnkr.co/edit/mxDLAdnrQ4p0KKyw?p=preview)

**Comment by akashishu777** [comment]
I think the issue is due to the Event.CLICK_DISMISS which is used in the _showBackdrop function in the modal.js file, I think we should use Event.MOUSEDOWN_DISMISS instead of Event.CLICK_DISMISS.

**Comment by ysds** [comment]
Thanks for reporting, but we're no longer maintaining v3. It'll soon be EOL (end of life) entirely, so closing this as a won't fix.
