### ISSUE TITLE
Ability to add colors to $theme-colors which generates all classes (button variants etc.)

### ISSUE THREAD

**Issue by Disane87** [twbs/bootstrap#28843]
Hi guys, first of all, thank you for this awesome framework. We really love it!
Now we want to extend the standard theme for some own colors with all variants.

Only adding it to the `$theme-colors` / `$colors` map doesn't work and we don't want to generate all by ourselves manually, like stated here: https://getbootstrap.com/docs/4.3/getting-started/theming/#modifiers

So it would be nice, if there is a color in the map, which is not standard, all classes for all components are generated.

Example:
If we add color `hotpink: rgba(255,105,180 ,1)` to the map, we expect to use `btn btn-hotpink` after that, without the need to manually generate (and therefore know which variants are existing).

Is the possible or planned?

**Comment by mdo** [comment]
This is currently possible with a Sass compiler and is documented at https://getbootstrap.com/docs/4.3/getting-started/theming/#maps-and-loops.

**Comment by mdo** [comment]
This is currently possible with a Sass compiler and is documented at https://getbootstrap.com/docs/4.3/getting-started/theming/#maps-and-loops.

**Comment by Disane87** [comment]
We already sutdied the documentation about this topic, especially this point:

> Add, remove, or modify values within the map to update how they’re used in many other components. Unfortunately at this time, not every component utilizes this Sass map. Future updates will strive to improve upon this. Until then, plan on making use of the ${color} variables and this Sass map.

But unfortunatly its not working. When we added `hotpink: rgba(255,105,180 ,1)` to the map, we can't use `btn btn-hotpink`

We even use the sass compiler.

**Comment by Disane87** [comment]
@mdo my fault. We declared our colors after the import of the bs sass stuff. meh. Just dragged it before it (as mentioned in the dics) and now it works. Hurray.
