### ISSUE TITLE
button text position using badge in IE10/11

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#28856]
hello sir,

I am using **windows 10** with **chrome** and **IE** lettest version browse.

when I am using **badge inside a button** at that time if I **click on button** other browsers will work fine but i**n IE10/11 button text position will be reflecting at the click( button active state )**.

- please **check** the code in **IE10/11**

https://codepen.io/pcodedviral/pen/oJwdpB

- the same **bug** will also happen in **documentation** also

https://getbootstrap.com/docs/4.3/components/badge/

thanks. . .

**Comment by pcodedviral** [comment]
hello sir,

- it's only **happening** in **button only** .
- if i use **<a> tag** with **.btn class** then also its **work fine**.

thanks. . .

**Comment by ysds** [comment]
That is IE’s behavior. We can do nothing. If you want to know more, please google.
