### ISSUE TITLE
Tab Javascript Plugin needs .nav or .list-group class as parent?

### ISSUE THREAD

**Issue by davidliang2008** [twbs/bootstrap#28854]
The tab javascript plugin actually needs `.nav` or `.list-group` class as the parent in order for it to work properly. It is not mentioned anywhere in the documentation.

### Without .nav or .list-group

```html
<div>
	<a href="#prices" class="btn btn-primary active" data-toggle="tab">
		Prices
	</a>
	<a href="#features" class="btn btn-secondary" data-toggle="tab">
		Features
	</a>
</div>
<div class="tab-content">
	<div class="tab-pane active" id="prices">Prices content</div>
	<div class="tab-pane" id="features">Features Content</div>
</div>
```

The tabs structure is just wrapped with a div without any class. The tab will work once: clicking "Features" will show the feature tab content. But it won't work after that. If you click "Prices" tab, the prices content won't show up.

### With .nav or .list-group

If you add `.nav` or `.list-group` class to the `<div />` wraps the tabs, the tab plugin will work perfectly.

```html
<div class="nav">
	<a href="#nav-prices" class="btn btn-primary active" data-toggle="tab">
		Prices
	</a>
	<a href="#nav-features" class="btn btn-secondary" data-toggle="tab">
		Features
	</a>
</div>
<div class="tab-content">
	<div class="tab-pane active" id="nav-prices">Prices content</div>
	<div class="tab-pane" id="nav-features">Features Content</div>
</div>
```

**Demo:** https://jsfiddle.net/davidliang2008/jtrzqfcu/39/

By the way, with _bootstrap 4.1_, it will throw a javascript error as well if you don't have `.nav` or `.list-group` class as the tab parent:

> tab.js:146 Uncaught TypeError: Cannot read property 'nodeName' of undefined

**Demo:** https://jsfiddle.net/davidliang2008/r2v8qwub/1/

- Operating system and version: **Windows 10 Pro, Version 1809**
- Browser and version: **Chrome, Version 74.0.3729.169**

**Comment by XhmikosR** [comment]
It's actually mentioned in the markup.

**Comment by davidliang2008** [comment]
@XhmikosR : maybe I am stupid. I didn't see them mentioned in the documentation as **required** class.

The closest I can find is:

To help fit your needs, this works with <ul>-based markup, as shown above, or with any arbitrary “roll your own” markup. Note that if you’re using <nav>, you shouldn’t add role="tablist" directly to it, as this would override the element’s native role as a navigation landmark. Instead, switch to an alternative element (in the example below, a simple <div>) and wrap the <nav> around it.

**Comment by XhmikosR** [comment]
Well, the markup is required otherwise CSS styling won't work. So, it's implied, it always has been.

**Comment by davidliang2008** [comment]
@XhmikosR: this issue is not complaining CSS styling. What I am saying is, if you don't have the CSS class `.nav` or `.list-group` as the parent class, the tab won't work! And this behavior is not stated anywhere in the documentation.

**Comment by XhmikosR** [comment]
Yes, because like I told you above, it's required syntax like everything else.

/CC @Johann-S

**Comment by Johann-S** [comment]
Maybe we should add a section about require CSS classes for our components 🤔 

@davidliang2008 do you need to know that to customize the CSS of those classes ?

**Comment by XhmikosR** [comment]
The markup suggested in docs, is always the only recommended way for things to work. I personally don't see any value in adding notes. If one wants to do their own thing, they need to adapt many stuff. Or just stick to the markup we show in our docs.

**Comment by davidliang2008** [comment]
@XhmikosR: It might be my bad English but I think you kept misunderstanding what I meant. I didn't mean the **markup**. I meant **the CSS class `.nav` and `.list-group`**! They **are required** in order for the tab plugin to work correctly. It's nothing about the markup. You can have the tabs have a structure of ul, ol, etc. But you **got to have either `.nav` or `.list-group`** in order for the tab to work. I've already demonstrated the issue at the beginning.

All I complain is that the necessary of `.nav` or `.list-group` **class** is not documented anywhere in the bootstrap documentation.
