### ISSUE TITLE
Browser default validation messages not aligned with custom checkbox

### ISSUE THREAD

**Issue by kakigorimochi** [twbs/bootstrap#28850]
![image](https://user-images.githubusercontent.com/16938949/58649321-6196e200-833e-11e9-9062-23e746495f83.png)

Using custom forms(custom-checkbox) with required attribute, message bubble validation not aligned with the checkbox.

https://codepen.io/kakigorimochi/pen/oRQNwb

- Operating system and version: Windows 10 64-bit Version 1809
- Browsers affected: Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser

**Comment by ysds** [comment]
Hi @kakigorimochi, thank you for your report, and congratulations on your first issue 🎉

**Comment by XhmikosR** [comment]
Fixed by #28852
