### ISSUE TITLE
missing attribute

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#28858]
hello sir,

I am using **windows 10**  with chrome and **IE lettest** version browse.

- in **IE10/11** **disabled form** required **"disabled" attribute** in **input tag** please check the **document link in IE10/11**
https://getbootstrap.com/docs/4.3/components/forms/#disabled-forms

- the select menu was disabled but **input was still editable in IE10/11**

thanks. . .

**Comment by ysds** [comment]
Please see the "Cross-browser compatibility" note in the "Disabled forms" section.
