### ISSUE TITLE
Disable smooth scrolling if `prefers-reduced-motion`.

### ISSUE THREAD

**Issue by Malvoz** [twbs/bootstrap#28868]
The [`scroll-behavior`](https://www.w3.org/TR/cssom-view/#smooth-scrolling) property specifies the behavior of scrolling where:

- [`auto`](https://www.w3.org/TR/cssom-view/#valdef-scroll-behavior-auto) (default) specifies scrolling without a timing function / "transition".
- [`smooth`](https://www.w3.org/TR/cssom-view/#valdef-scroll-behavior-smooth) allows scrolling: "in a smooth fashion using a user-agent-defined timing function over a user-agent-defined period of time".

I think it is sensible to unset any potential smooth scrolling when a user `prefers-reduced-motion`.

**Comment by mdo** [comment]
We don't set any smooth scrolling.

**Comment by patrickhlauke** [comment]
bootstrap doesn't explicitly set any scrolling, so it would feel intrusive if we explicitly disabled it

**Comment by Malvoz** [comment]
That is not my concern, but rather that developers themselves do.

**Comment by patrickhlauke** [comment]
it's not our job to that as part of Bootstrap though.
