### ISSUE TITLE
ScrollSpy does not work with numeric anchor IDs

### ISSUE THREAD

**Issue by gcushen** [twbs/bootstrap#28866]
If an anchor begins with a number (e.g. `#1`, `#1-something`, then ScrollSpy does not function (no active link highlighting).

- Bootstrap: 4.3.1
- Operating system and version: macOS
- Browser and version: Safari 12.1.1
- Test case:
   - Go to https://www.codeply.com/go/7CDRomtM0D/bootstrap-4-scrollspy
   - replace the two instances of `#one` in the code with `#1`
   - click Run
   - the active link highlighting of the Section 1 is now broken

**Comment by Johann-S** [comment]
Hi @gcushen,

That's right, it's because you have to use valid CSS selectors.

>In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

see:
- https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier
- https://getbootstrap.com/docs/4.3/getting-started/javascript/#selectors
