### ISSUE TITLE
unused mixin "make-col-ready"

### ISSUE THREAD

**Issue by ashfahan** [twbs/bootstrap#28863]
mixin make-col-ready is not used anywhere in project but still exist

**Comment by florianlacreuse** [comment]
According to the documentation, this mixin can be used to define your own css classes for custom grid.

https://getbootstrap.com/docs/4.3/layout/grid/#mixins

That being said, internally, BS use instead a placeholder class (`%grid-column`) to define the default grid. I don't know why but I'm interested in the answer.

https://github.com/twbs/bootstrap/blob/87030c98accc7d2dbdbbd22eccbd4a5a837648ff/scss/mixins/_grid-framework.scss#L8-L13

Maybe it's just a small mistake and we could use the mixin in `_grid-framework.scss`?

**Comment by mdo** [comment]
We moved from the mixin to the placeholder during v4 development, but for backward compatibility, we left the mixin intact. We can drop it in v5.

/cc @twbs/css-review

**Comment by ashfahan** [comment]
> According to the documentation, this mixin can be used to define your own css classes for custom grid.
> 
> [getbootstrap.com/docs/4.3/layout/grid/#mixins](https://getbootstrap.com/docs/4.3/layout/grid/#mixins)
> 
> That being said, internally, BS use instead a placeholder class (`%grid-column`) to define the default grid. I don't know why but I'm interested in the answer.
> 
> https://github.com/twbs/bootstrap/blob/87030c98accc7d2dbdbbd22eccbd4a5a837648ff/scss/mixins/_grid-framework.scss#L8-L13
> 
> Maybe it's just a small mistake and we could use the mixin in `_grid-framework.scss`?

That is why i was curious.

> We moved from the mixin to the placeholder during v4 development, but for backward compatibility, we left the mixin intact. We can drop it in v5.
> 
> /cc @twbs/css-review

well that satisfies my question =)

**Comment by mdo** [comment]
@MartijnCuppens Should we remove this, or should it stay? We document this, but our own grid setup uses a different approach.

**Comment by MartijnCuppens** [comment]
Let's ditch it if we don't use it ourselves.

**Comment by mdo** [comment]
So revisiting this, I think we need to leave it as-is or replace this with a Sass placeholder that mimics what's found in `mixins/_grid_framework.scss`. Otherwise we have a more verbose and incomplete set of grid mixins for those who role their own.

**Comment by mdo** [comment]
Keeping this around for now.
