### ISSUE TITLE
Search ability for local documentation app

### ISSUE THREAD

**Issue by ordinaryzelig** [twbs/bootstrap#28878]
When using the [locally installed documentation app](https://github.com/twbs/bootstrap#running-documentation-locally), the search bar uses Algolia's DocSearch. This makes the search unusable for a local server since it requires internet. Would be nice to somehow be able to use the search locally. Even a watered down topic search could be useful.

**Comment by XhmikosR** [comment]
I don't think there's a solution for this nor any plan to support this.

/CC @mdo
