### ISSUE TITLE
Can someone explain where this selector would be necessary?

### ISSUE THREAD

**Issue by exception-io** [twbs/bootstrap#28875]
I was going through the main (compiled) boostrap.css file and came across several uses of this selector:

**.btn-group-vertical > .btn:first-child:not(:last-child) {}**

So it's selecting an element that has the **.btn** class which is a first child (but also not a last child?) of an element with the class **.btn-group-vertical**

Why would there be a need for the chained **:not()** pseudo-class? If the point was to select an only child why not use **:only-child** which has the same browser compatibility? I can't imagine a use case for this and haven't been able to find an answer, although I know this is the wrong section to ask but I haven't found a better place, apologies in advance, I just really want to understand.

**Comment by mdo** [comment]
`:first-child` and `:last-child` can apply to the same element if it's the only child element. We do this to avoid overriding properties again and again. If we did `:only-child` we'd have to write another selector altogether.
