### ISSUE TITLE
Remove padding-right on input.form-control for clarity

### ISSUE THREAD

**Issue by Superpencil** [twbs/bootstrap#28871]
Currently on text input fields using the .form-control class, a nice padding is applied to the right and left of the input. This looks good.

However, when there is more text in the field than the width of the field allows, the padding on the right makes it a little unclear that we have 'overflowed' the input.

Here is what it looks like currently:
![Screen Shot 2019-06-05 at 14 46 56](https://user-images.githubusercontent.com/3094044/58932985-cae47e00-87a0-11e9-8ec7-c78d8a8bd0dc.png)

Here is what it looks like currently if the width is just right, hiding the rest of the numbers:
![Screen Shot 2019-06-05 at 14 47 58](https://user-images.githubusercontent.com/3094044/58933023-ee0f2d80-87a0-11e9-8c73-f3972d282e38.png)

Here is what it would look like if we set `padding-right: 0`:
![Screen Shot 2019-06-05 at 14 48 57](https://user-images.githubusercontent.com/3094044/58933072-1139dd00-87a1-11e9-821d-d61f69facad0.png)

It is a tiny amount more clear that we have overflowed to the right. 

And even if we again have the width just right, hiding the next number perfectly:
![Screen Shot 2019-06-05 at 14 50 45](https://user-images.githubusercontent.com/3094044/58933151-5100c480-87a1-11e9-90f4-99cc42df5492.png)

The fact that there is padding on the left more clearly indicates we have reached the end of our input on the right, and might have overflowed.

**Comment by mdo** [comment]
I don't see us changing this right now, but it's interesting to think about for sure. For now, please use the margin utilities with `.pr-0`.
