### ISSUE TITLE
Form validation icon appears above the input if the label has more than one line.

### ISSUE THREAD

**Issue by alexhutcheson** [twbs/bootstrap#28884]
Bootstrap version 3.4.1 (release)

When using the form validation feedback icons, if the <label> text takes up more than one line, then the validation icon will appear above the input field.

Reduced test case: https://jsbin.com/husapev/edit?html,output
The test case is just copy+paste of the example boilerplate and the form validation icon example from the docs, plus some additional text in the label to make it wrap.

OS/Browser: ChromeOS/Chrome, also reproduced on iOS/Safari

**Comment by fkoepke** [comment]
I would like to work on it, if it's okay.

**Comment by mdo** [comment]
Sorry, but v3 is officially end of life.
