### ISSUE TITLE
getbootstrap.com/docs/3.4/ version options in the top right nav are outdated

### ISSUE THREAD

**Issue by alexhutcheson** [twbs/bootstrap#28888]
On https://getbootstrap.com/docs/3.4/, there is a drop-down menu on the right side of the top nav bar to select which version of the docs you want. 

Right now, the only listed options are:
- Latest (4.x)
- v4 Alpha 6
- v3.4.1
- v3.3.7
- v2.3.2

This is confusing for users who might have arrived at the page from a search engine or other external link, because it makes it look like there is no official release of Bootstrap v4. It would probably be worth it to bring it in sync with the drop-down that appears on https://getbootstrap.com/ to make it clear that v4 has had multiple point releases.

**Comment by mdo** [comment]
`Latest (4.x)`, plus the blue banner at the top of every page, should be pretty clear there's a new major version. It doesn't need every version listed.
