### ISSUE TITLE
Navbar component is horizontal only can we add vertical Navbar option

### ISSUE THREAD

**Issue by pixieaka** [twbs/bootstrap#28881]
80% of admin templates in themeforest is Vertical Navbar because it's can have many items inside it because it's scrollable & core bootstrap navbar without it, it's very weird

![Untitled-1](https://user-images.githubusercontent.com/17777237/59141270-ecfd1c80-89a9-11e9-832b-80bdf5eaad38.jpg)

**Comment by vietanhdtd** [comment]
okay

**Comment by XhmikosR** [comment]
You can do it with `flex-column`. See the dashboard example.

**Comment by pixieaka** [comment]
Vertical navbar is very important it 80% used in admin templates, it must to include with examples in documentation like horizontal navbar menu it's more important than it for all dashboard out there. @XhmikosR

**Comment by pixieaka** [comment]
And dashboard example it's not responsive like main navbar menu component it's not working on mobile @XhmikosR

**Comment by XhmikosR** [comment]
You can use the utilities to achieve what you want.

And then improve the current example.

**Comment by pixieaka** [comment]
I just hope navbar menu component to have vertical option with all handsome functionality of it. Bootstrap is No.1 front end in the world & vertical navbar is main stream for all dashboard now. Just think about it with bootstrap team i hope you develop it @XhmikosR

**Comment by XhmikosR** [comment]
@twbs/team: please chime in here.

An proper example would help indeed.

**Comment by pixieaka** [comment]
@XhmikosR this link 404

**Comment by MartijnCuppens** [comment]
We might combine this somehow with https://github.com/twbs/bootstrap/issues/27033, so that we also have a responsive solution.

**Comment by mdo** [comment]
Going to close as a duplicate of #24718 and #27033.

I don't think we'd leverage a navbar variation for this so much as figuring out the JS and general CSS needed to trigger a hidden sidebar with whatever contents folks want.

**Comment by mrlife** [comment]
> Going to close as a duplicate of #24718 and #27033.
> 
> I don't think we'd leverage a navbar variation for this so much as figuring out the JS and general CSS needed to trigger a hidden sidebar with whatever contents folks want.

@mdo Trying to understand preferring offcanvas to a hideable/minimizable vertical nav. Can offcanvas have an inline-block option?
