### ISSUE TITLE
Icon in Menu slightly moved (attached image)

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#28894]
The icon is slightly moved to the right, while this may be a minor issue, if the font-size is increased (as I did) it is way more noticeable. Do note the screenshot is from the Bootstrap's Docs.

I'm using Firefox in Windows 7 x64

![bug-bootstrap icon moved](https://user-images.githubusercontent.com/32283036/59316241-72731c00-8c8b-11e9-836a-80c7a8a678d4.png)

**Comment by AlokTakshak** [comment]
@MartijnCuppens  I would like to contribute , can tell me what all needs to be done
Thanks

**Comment by MartijnCuppens** [comment]
@AlokTakshak, you can have a look at the contributing guidelines to get started: https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#pull-requests

**Comment by AlokTakshak** [comment]
> @AlokTakshak, you can have a look at the contributing guidelines to get started: https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#pull-requests

Can you tell me how can i simulate the issue?

**Comment by MartijnCuppens** [comment]
@tomasts248, could you provide a codepen demo?

**Comment by tomasts248** [comment]
Sure.. tomorrow I will get into it, right now is 4:00 a.m

**Comment by mdo** [comment]
Closing as a won't fix with this being a zoom and pixel-rounding issue. We may also end up moving this to an inline SVG in v5 anyway, so could be moot soon.
