### ISSUE TITLE
Should button-variant function allow a manually-specified color?

### ISSUE THREAD

**Issue by jrochkind** [twbs/bootstrap#28899]
In [Bootstrap 3, the button-variant function/mixin](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/mixins/_buttons.scss#L6) had this signature:

    @mixin button-variant($color, $background, $border)

You specified the (text) color, background color, and border. Other values (such as focus/hover colors) were computed automatically derived from these. 

In [Bootstrap 4, the button-variant function/mixi](https://github.com/twbs/bootstrap/blob/2ac2a5a91e2958a367c46a61d05162f640457db5/scss/mixins/_buttons.scss#L6) has this signature instead:

    @mixin button-variant($background, $border, $hover-background: darken($background, 7.5%), $hover-border: darken($border, 10%), $active-background: darken($background, 10%), $active-border: darken($border, 12.5%)) {

You specify, at least, the background and border color. All other values are computed derived from those. You can *optionally* specify your hover and active border/backgrounds instead. The [built-in uses of button-variant](https://github.com/twbs/bootstrap/blob/2ac2a5a91e2958a367c46a61d05162f640457db5/scss/_buttons.scss#L61) only specify $background and $border (and actually specify $border to be the same value as $background), and allow the default computation for the rest. 

There is no way to manually specify the actual (text/foreground) `color` as an option though -- for default, hover, or active. You are stuck with the computed/derived value based on [contrasting colors with specified/default backgrounds](https://github.com/twbs/bootstrap/blob/2ac2a5a91e2958a367c46a61d05162f640457db5/scss/mixins/_buttons.scss#L7). 

If you wanted to manually override this to something that worked better, for your particular palette or branding stylesheet, than the automatically computed value, you could do it by applying button-variant mixin and then providing CSS overrides -- but the need to deal with all the pseudo-selectors and nesting (which can be [complex and non-obvious](https://github.com/twbs/bootstrap/blob/2ac2a5a91e2958a367c46a61d05162f640457db5/scss/mixins/_buttons.scss#L43) ) makes this kind of challenging to do in a reliable way. 

Should button-variant function allow optional arguments with manually specified `color` values? Which if not provided, would still default to the automatically computed value with `color-yiq` and relevant background color.

**Comment by mdo** [comment]
> Should button-variant function allow optional arguments with manually specified `color` values? Which if not provided, would still default to the automatically computed value with `color-yiq` and relevant background color.

That would seem like a nice enhancement.

**Comment by wingleung** [comment]
For accessibility purposes it would be nice to define a unified style for the focus/hover states.

I would think overriding the following variables would override any other focus colors 
- $input-btn-focus-color
- $input-focus-border-color
- $input-focus-color

But it does not because of the dynamic color generation of https://github.com/twbs/bootstrap/blob/f1e6e6e4a19dac0fa08bc235c701cbdc99969eaf/scss/mixins/_buttons.scss#L24-L28
