### ISSUE TITLE
card-columns and google maps issue

### ISSUE THREAD

**Issue by cjshaw1976** [twbs/bootstrap#28891]
Good day,

There is a silly bug when you insert a google map in a card div, inside a card-columns div and it seems to be something to do with the column count property. There are 4 div's in my case, 2 below and 2 above the map that prevent any other element being clicked. In my example below, the update address button cannot be clicked.
 
<img width="465" alt="Screen Shot 2019-06-11 at 09 18 36" src="https://user-images.githubusercontent.com/13312104/59251495-3bb8e980-8c2a-11e9-86e6-f1c4c3a99a01.png">

I have tried playing around with the z-index of the button, but this does not work.

**Comment by florianlacreuse** [comment]
Can you provide a live demo with a reduced test case?

**Comment by cjshaw1976** [comment]
Will work on it now

**Comment by cjshaw1976** [comment]
I have created two fiddles. The only difference is one uses 'card-deck' and the other 'card-columns'.

With card-columns, you cannot click the button as a hidden part of the map is in the way. In fact you can even drag the map from over the button: https://jsfiddle.net/cjshaw/ws46qbv1/

With card-deck, you can click the button and everything works as you would expect: https://jsfiddle.net/cjshaw/ws46qbv1/1/

**Comment by mdo** [comment]
Card columns use the `columns` CSS property. If you need columns and have stuff like Google Maps to place within, I'd suggest the grid versus a browser-based content layout mechanism. Content is distributed so oddly across CSS columns and I'm betting they have no idea how to handle these kind of objects within.

Food for thought on eliminating the `.card-columns` class outright in v5 given their confusion and problems we've seen, @twbs/css-review.

**Comment by morrissey-ingenious** [comment]
I don't think its a Bootstrap issue ... it only happens in Google Chrome.

**Comment by mdo** [comment]
Closing as a won’t/can’t fix.
