### ISSUE TITLE
Documentation: Equal-width multi-row example doesn't illustrate concept

### ISSUE THREAD

**Issue by catchmyfame** [twbs/bootstrap#28892]
[https://getbootstrap.com/docs/4.3/layout/grid/#equal-width-multi-row](https://getbootstrap.com/docs/4.3/layout/grid/#equal-width-multi-row)

**Layout > Grid > Equal-width multi-row**

The documentation for this topic begins with, "Create equal-width columns that span multiple rows by..." however the example given does not demonstrate any columns spanning multiple rows. In the example:

```
<div class="container">
  <div class="row">
    <div class="col">col</div>
    <div class="col">col</div>
    <div class="w-100"></div>
    <div class="col">col</div>
    <div class="col">col</div>
  </div>
</div>
```

Each column spans a single row in a 2 x 2 grid.

There's a similar topic located higher up on the same page with the same code example that has the text, "Equal-width columns can be broken into multiple lines" which makes a little more sense as the concept seems to be showing how you can split, or break, equal-width columns over multiple lines within a row.

**Comment by mdo** [comment]
Ah yes we have some duplicate grid docs here. The examples are correct, but the text is confusing.
