### ISSUE TITLE
Long label for custom file input overflows

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#28897]
There is already a Firefox-only report of this issue at https://github.com/twbs/bootstrap/issues/26933, however, it's been closed already and it seems still to be a problem in Bootstrap 4.3.1.

Operating system and version Windows 10
Browser and version: At least Chrome 74

Reduced test case: https://jsfiddle.net/vrawcu19/1/

This is especially a problem when using the recommended bs-custom-file-input plugin, as the label is dynamic in width (i.e., it is the file name) and the visual problem happens a lot when our customers select very long files or have narrow displays (e.g., some mobile displays).

**Comment by ysds** [comment]
This has been resolved for v5, but in v4, there is no common and easy solution.

https://github.com/twbs/bootstrap/issues/26933#issuecomment-468900825 is one of the workaround.

@MartijnCuppens Should we add #28511 to v4?

**Comment by MartijnCuppens** [comment]
You can have a look at https://bs-custom-file-input.netlify.com/ for a solution for `v4` (It's not perfect since it uses the `.w-75` utility class and doesn't take the width of the button into account. You can also try to get the desired effect with padding or margin utilities.). Another solution would be a breaking change I guess.

**Comment by drauch** [comment]
> You can have a look at https://bs-custom-file-input.netlify.com/ for a solution for v4 (It's not perfect since it uses the .w-75 utility class and doesn't take the width of the button into account. 

I've showcased this in my test case above, this does not have the desired effect on very broad displays and also fails if the display is very narrow.

> Another solution would be a breaking change I guess.
So this means no fix for v4? :(

**Comment by MartijnCuppens** [comment]
Fixing this in `v4` would be a breaking change. With a bit of additional css this can be fixed in your project for now.

**Comment by ysds** [comment]
Closing this as a wontfix.

Workarounds: https://codepen.io/anon/pen/GbMMrv
