### ISSUE TITLE
Future of NuGet support in v5

### ISSUE THREAD

**Issue by supergibbs** [twbs/bootstrap#28902]
I maintain the Bootstrap NuGet packages and am wondering if support should continue for v5. I am happy to do it but officially NuGet shouldn't be used for frontend bits. Newer Visual Studio projects support `npm` as discussed 4 years ago https://github.com/twbs/bootstrap/issues/16692.

https://www.nuget.org/packages/bootstrap
https://www.nuget.org/packages/bootstrap.less
https://www.nuget.org/packages/bootstrap.sass

Please comment below if you have any preference to drop or keep a NuGet package for v5.

**Comment by tiesont** [comment]
I'm sure I'm in the minority, but I'm not super keen on using npm for Bootstrap (especially when it would be the _only_ reason I'd have npm installed). 

There's always libman, though, so as long as it's available _somewhere_, I think dropping NuGet support is okay.

**Comment by MartijnCuppens** [comment]
I'm ok with keeping NuGet support, we also have a composer package while it should also only be used for PHP packages. It looks like we have about 310000 downloads for the last 4 months, which still is quite a lot.

Not sure if NuGet is something we have in our release checklist, maybe we should add that? (cc @XhmikosR)

**Comment by XhmikosR** [comment]
It's not in our list because @supergibbs handles NuGet :P

That being said I'm not sure about it. I personally don't use it, so I can't really comment on it.

**Comment by Johann-S** [comment]
I don't use it neither but according to what @MartijnCuppens said I think we should keep it

**Comment by supergibbs** [comment]
Microsoft's old project template uses bootstrap so I am guessing that is a lot of the downloads. It's still on v3.x so v5 support doesn't help that (actually breaks it and causes confusion https://github.com/twbs/bootstrap/issues/27355). 

That being said I've been thinking about it. If I drop the NuGet package, someone will probably just recreate it with a different name then stop updating it until another one is created and so on.  That was the state of things before @mdo and I unified them. So even though users should start using npm, I think we should keep it around for a better experience until the numbers drop to low enough to not need it.

@XhmikosR @MartijnCuppens It would be great to add it to the release checklist so we can coordinate or automate the NuGet package. Ping me on Slack if we can set something up.

**Comment by MartijnCuppens** [comment]
I've added this to our internal release checklist, so that you 'll be notified when a new release comes out.
