### ISSUE TITLE
Ditch line heights

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#28907]
A lot of our components contain `line-height`s, and `sm/lg` versions with configurable `line-height`s. I wonder if it's really needed for all those components to have configurable `line-heights`, a mixed usage of different line heights might result in an inconsistent design, so I really doubt people really change these values per component. Also these variables look a bit strange: https://github.com/twbs/bootstrap/blob/0829decce075e190c0bb6e9992ca2a1ca56c60c7/scss/_variables.scss#L219-L220

Imo, we can just remove the different line-heights for `sm/lg` versions which would make our codebase a bit less bloated. 

We might add some utilities to increase or decrease line heights though.

Thoughts @twbs/css-review?

**Comment by mdo** [comment]
This was more impactful in v3 where we had much smaller buttons and font sizes at play. Overall though I think we should explore cleaning this up.

> We might add some utilities to increase or decrease line heights though.

Definitely want to look into this as `.lh-*` for a small scale of line-heights.
