### ISSUE TITLE
Why .modal-xl max-width same as .modal-lg

### ISSUE THREAD

**Issue by vVvlife** [twbs/bootstrap#28909]
![image](https://user-images.githubusercontent.com/20148964/59584742-6ebf1980-9111-11e9-9d8c-fc6b3264a6b9.png)

**Comment by vVvlife** [comment]
version: bootstrap 4.3

**Comment by florianlacreuse** [comment]
It's related to PR #27094.

**Comment by coliff** [comment]
.modal-lg has `max-width: 800px`
.modal-xl has `max-width: 1140px`

REF: https://getbootstrap.com/docs/4.3/components/modal/#optional-sizes

It only shows that modal-lg and modal-xl have the same max-width (800px) if you are at viewing at a smaller than XL viewport... so it's working as intended.
