### ISSUE TITLE
Single line of code nested dropdown submenu

### ISSUE THREAD

**Issue by tarkhov** [twbs/bootstrap#28908]
```javascript
if (event && event.target !== toggles[i] && $.contains(parent, event.target)) continue
```

**Comment by patrickhlauke** [comment]
doesn't handle correct keyboard behavior, so...not really production-ready.

**Comment by tarkhov** [comment]
@patrickhlauke If I make keyboard navigation works you accept this feature?

**Comment by patrickhlauke** [comment]
i believe @mdo decided that we wouldn't support it at this point...it will be up to him/the group to decide. in the meantime i'd suggest working on it as a plugin/extension.

**Comment by tarkhov** [comment]
@patrickhlauke I tried to implement this feature as a plugin several times, but the events do not allow to fully implement it, `clickEvent `doesn't work on child dropdowns https://github.com/twbs/bootstrap/blob/v4.3.1/js/src/dropdown.js#L402
