### ISSUE TITLE
Text input height in input groups not adjusted properly when input-group-text height is increased

### ISSUE THREAD

**Issue by catchmyfame** [twbs/bootstrap#28901]
I'm not sure if this is a bug or intended, but if you increase the font size or height of the `input-group-text` in an input group, the associated input field doesn't adjust its height properly.

Sample input group (takes from https://getbootstrap.com/docs/4.3/components/input-group/):

```
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">@</span>
  </div>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>
```
Generates:
![image](https://user-images.githubusercontent.com/78397/59526579-3caa7f00-8ea7-11e9-93d2-bbdf0777c5f9.png)

Increase the font size on the `input-group-text` element:
```
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" style="font-size: 2em">@</span>
  </div>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>
```

Generates:
![image](https://user-images.githubusercontent.com/78397/59526733-a591f700-8ea7-11e9-956e-0f9d766df8ec.png)

A simple solution is to add `height: auto;` to the input field which produces what I would think is the desired result:

![image](https://user-images.githubusercontent.com/78397/59526835-f30e6400-8ea7-11e9-8722-007784be650e.png)

When browsing the docs I noticed that in the 4.0.0 version that changing the font size or height of the `input-group-text` element didn't have this issue, but it does on the 4x releases going forward.

**Comment by m5o** [comment]
Guess this is why the sizing classes like `.input-group-lg` are there. It keeps the prepend text and input font size consistent in sync.

**Comment by bkdotcom** [comment]
re .sizing classes:

those don't help if the "addon" is an image

**Comment by MartijnCuppens** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/29124
