### ISSUE TITLE
Responsive Grid Image gallery using Grid css

### ISSUE THREAD

**Issue by rmfranciacastillo** [twbs/bootstrap#28916]
Feature requests must include:

It would be awesome to have a grid made from Grid CSS to create simple responsive galleries. It's easy to debug and allows the flexibility to create different grid variations. 

I know this can be made with the current code but if there is a tool designed for grids take advantage of it. 

Suggestion: Grid CSS Gallery Mixin
  https://codepen.io/rmfranciacastillo/pen/dBGOrd?editors=1100

**Comment by mdo** [comment]
Already an issue open for CSS grid. See #28385.
