### ISSUE TITLE
 4.1.3 bootstrap version supports IE 8?

### ISSUE THREAD

**Issue by tkr6743** [twbs/bootstrap#28923]
Dear team,

Currently we are using bootstarp version 3.3.6 when in security scan we got an issue to upgrade required to version 4.1.3. 

Please guide me on 4.1.3 bootstrap version supports IE 8?

If not then how do I fix it without upgrading to the latest version?

Thanks for your support.

Thanks,
Kondal

**Comment by arthurfigueiredo** [comment]
https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/

**Comment by patrickhlauke** [comment]
in short no, Bootstrap 4.x supports IE10+ only. and i'm afraid we can't help/support 3.x anymore, particularly when it comes to fixing things so they also maintain compatibility with IE8.

my best suggestion would be to try and upgrade to 4.x on a test environment, and see if the way you're using it works acceptably in IE8. depending on which specific styles/features/widgets you're using, it may actually be ok.

**Comment by Johann-S** [comment]
Hi @tkr6743 you should update to Bootstrap v3.4.1 which contains security fixes: https://getbootstrap.com/docs/3.4/
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
