### ISSUE TITLE
Re-arrange z-index of sticky-top to be lower than dropdown

### ISSUE THREAD

**Issue by moonraking** [twbs/bootstrap#28926]
It is document [here in z-index](https://getbootstrap.com/docs/4.3/layout/overview/#z-index) that sticky is above dropdown.

It would be nice to have dropdown above sticky as navbar dropdown will be hidden by any sticky element in the normal document flow. e.g. a `thead.sticky-top` of a large table.

A quick example can be made by applying the sticky-top class to the 4th nav bar in the Bootstrap Examples [here](https://getbootstrap.com/docs/4.3/examples/navbars/) and then activating the dropdown of the 3rd navbar.

This seems like an odd behavior.  Maybe there is a good reason or use case for this behavior.

There are a few work arounds I can think of
1. Override the z-index of .sticky-top or .drop-down at a project level.
2. Don't use .sticky-top and implement at project level.
3. Add some Javascript to add and remove the .sticky-top class of the element while the element is not at the top, but this negates the reason for having sticky-top in the first place.
4. Add another helper class to the Bootstrap library to change the z-index.
5. Add another .sticky-top-less-than-dropdown (with a better name, obviously).

None of the above seem like a sensible solution, although in my project I have opted, reluctantly, for option 1.

Maybe there is a very good reason why .sticky-top is higher than .drop-down, if so, maybe we can add it to the documentation with an example of best practice and use case around site navigation and sticky-top elements.

**Comment by mdo** [comment]
Sorry, not going to make any changes to the z-index scale anytime soon. You're welcome to customize things (hence the Sass variables), but it's a delicate balance. I'll see what can be done to better explain things in our docs though.
