### ISSUE TITLE
Button Loading

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#28930]
Hello,

Are we interested on a button loading class/state?
Is very simple and inspired from spinners 

![Screenshot from 2019-06-19 10-40-50](https://user-images.githubusercontent.com/22406063/59746116-d8106b00-927e-11e9-9b92-56205eb7f787.png)

[Codepen Example](https://codepen.io/anon/pen/MMjxrg)

**Comment by MartijnCuppens** [comment]
We already have something like this, have a look at https://getbootstrap.com/docs/4.3/components/spinners/#buttons 😉

**Comment by GeoSot** [comment]
@MartijnCuppens 
I use it already, but as you can  see it's not the same. Give it a try. 

The existing option, sets another element inside button and the button's size is changed.
 My proposal, uses a class modifier and nothing is changed on button

**Comment by MartijnCuppens** [comment]
We'll pass on this for now, the buttons become a bit less readable with this animation and we got to make sure not to add too many loading states.

**Comment by GeoSot** [comment]
May I leave a pull request or not?

**Comment by MartijnCuppens** [comment]
Nah, leave it. Thanks for the willingness though!
