### ISSUE TITLE
License for 3.4.1 Bootstrap for Glyphicons cannot be found

### ISSUE THREAD

**Issue by RobertRogers24** [twbs/bootstrap#28934]
Hello all,

I am looking to find the actual license used by Bootstrap 3.4.1 for the Glyphicon set. I understand it has been removed for version 4.X however seeing as how we use version 3.X we require this license for legal compliance.

I checked the following issue in 2012: https://github.com/twbs/bootstrap/issues/3942#issuecomment-12557565
However the link no longer works, as it seems the website has been redesigned (go figure after 7 years :P)

If anyone can provide me with a link to the actual license, or include the license in the source that would be awesome. Just to be clear I have read that the license is the same as Bootstrap, however need actual linkages to provide to the legal team.

**Comment by patrickhlauke** [comment]
Bootstrap doesn't seem to have included a license file specifically, but rather the glyphicon site hosted the license. As this is going back years, your best bet is pointing to https://web.archive.org/web/20121127024134/http://glyphicons.com/glyphicons-licenses/

**Comment by RobertRogers24** [comment]
I reached out to Jan who put the old license back up on his site. Putting it here so others who have the same issue can find it:
https://glyphicons.com/old/license.html#old-halfings-bootstrap
