### ISSUE TITLE
Changing font size of select options for mobile devices.

### ISSUE THREAD

**Issue by farhankarim** [twbs/bootstrap#28935]
I have tried using media queries but it only reflects the changes on debugging view not on a physical mobile device.

More info here: [https://stackoverflow.com/questions/56663363/changing-size-of-bootstrap-select-pop-up-on-mobile-devices?noredirect=1#comment99895357_56663363](url)

**Comment by patrickhlauke** [comment]
Those elements are rendered by the system/browser and cannot be styled,

**Comment by farhankarim** [comment]
> Those elements are rendered by the system/browser and cannot be styled,

Thanks for the clarification.
