### ISSUE TITLE
input [radio] top margin issue

### ISSUE THREAD

**Issue by twinpixxx** [twbs/bootstrap#28932]
Bootstrap version => 3.3.5
OC: macOS
HTML example:
~~~HTML
<form>
  <label class="radio-inline">
    <input type="radio" name="optradio" checked="" />opt1
  </label>
  <label class="radio-inline">
    <input type="radio" name="optradio" />opt2
  </label>
  <label class="radio-inline">
    <input type="radio" name="optradio" />opt3
  </label>
  <label class="radio-inline">
    <input type="radio" name="optradio" />opt4
  </label>
  <label class="radio-inline">
    <input type="radio" name="optradio" />opt5
  </label>
</form>
~~~
In google chrome we have:
<img width="380" alt="Screen Shot 2019-06-19 at 1 17 32 PM" src="https://user-images.githubusercontent.com/10453907/59757531-a30f1300-9294-11e9-9584-e901615cfd83.png">
In firefox: 
<img width="380" alt="Screen Shot 2019-06-19 at 1 18 08 PM" src="https://user-images.githubusercontent.com/10453907/59757563-b4581f80-9294-11e9-8ba1-071e11c03f9d.png">
In safari:
<img width="409" alt="Screen Shot 2019-06-19 at 1 19 14 PM" src="https://user-images.githubusercontent.com/10453907/59757621-de114680-9294-11e9-8aa2-d5d3c4542d35.png">
I investigate that this part of _forms.scss makes that issue
~~~css
// Position radios and checkboxes better
input[type="radio"],
input[type="checkbox"] {
    margin: 4px 0 0;
    margin-top: 1px \9; // IE8-9
    line-height: normal;

    // Apply same disabled cursor tweak as for inputs
    // Some special care is needed because <label>s don't inherit their parent's `cursor`.
    //
    // Note: Neither radios nor checkboxes can be readonly.
    &[disabled],
    &.disabled,
    fieldset[disabled] & {
        cursor: $cursor-disabled;
    }
}
~~~

**Comment by ysds** [comment]
We're no longer maintaining v3. It'll soon be EOL (end of life) entirely, so closing this.
