### ISSUE TITLE
custom-file input with `is-invalid` doesn't show error messages

### ISSUE THREAD

**Issue by theomega** [twbs/bootstrap#28945]
If you try to mark an `custom-file` form field as invalid using the `is-invalid` class on the `<input>` element, the error messages in an `invalid-feedback` div, are hidden.

See this fiddle: https://jsfiddle.net/cg2975jo/

The "This field is required." error message is never displayed.
The `invalid-feedback` div is actually visible as `display: block;` is set. Still, the div never displays.

Funny fact: If you actually choose a file, then the error message is displayed, but at a weird location underneath the button.

Validated on:
- MacOS, Firefox 67.0 (64-bit)
- MacOS, Google Chrome 75.0.3770.100 (Official Build) (64-bit)

**Comment by mdo** [comment]
Problem is that it's in an `.input-group`. The HTML and CSS are quite tricky and part of the limitations of the components. Sorry, but for now, you'll have to place it outside an that input group.

**Comment by theomega** [comment]
@mdo thanks for the answer. What do you mean with "it"? What do I have to place outside the input group? The `invalid-feedback` div? I tried this and this doesn't work either:
https://jsfiddle.net/c97zsw4e/

In this fiddle, the `invalid-feedback` div is outside the input group. Still, I'm not seeing the messages.

**Comment by theomega** [comment]
@mdo any clarification you can provide? Thanks!
