### ISSUE TITLE
Can I put a .container in my container?

### ISSUE THREAD

**Issue by uCryNet** [twbs/bootstrap#28949]
In this case, the bootstrap container acts as a container of content, and mine as the container parent is the maximum width of the site.

For example:
There is a 800px wide layout, the content itself is inside - 590px (the maximum width of the media container has been changed).

```
<div class="my-container">  <!-- 800px -->  
  <div class="container"> <!-- 590px -->  
    <div class="row">
      <div class="col-md-6">
        <p>Text</p>
      </div>
      <div class="col-md-6">
        <p>Text</p>
      </div>
    </div>
  </div>
</div>
```

Why is that: sections are unique and have their own background and border.
The key question is: can this be done or is it a bad practice?

**Comment by leecollings** [comment]
There's nothing wrong with it, you can do this if you wish.

**Comment by uCryNet** [comment]
> There's nothing wrong with it, you can do this if you wish.

Thank

**Comment by mdo** [comment]
Since containers have `max-width`, you're fine, but you may end up with nested horizontal padding and extraneous markup: https://codepen.io/anon/pen/xoLjKQ. But that's only if you're using our built-in containers.
