### ISSUE TITLE
"Stacked to horizontal" documentation issue

### ISSUE THREAD

**Issue by bsl** [twbs/bootstrap#28946]
"Using a single set of .col-sm-* classes, you can create a basic grid system that starts out stacked and becomes horizontal at the small breakpoint"

This seems exactly backwards. You can create a grid system that starts out horizontal and becomes stacked at the small breakpoint.

**Comment by mdo** [comment]
It's not backwards. Bootstrap's grid is mobile first, so it starts from the absolute lowest breakpoint with no infix (`.col`) and scales up across `sm`, `md`, `lg`, and `xl`.
