### ISSUE TITLE
The website https://getbootstrap.com is not accessible from AWS.

### ISSUE THREAD

**Issue by TimotheeJeannin** [twbs/bootstrap#28950]
It looks like the bootstrap website does not respond to requests coming from AWS.

    ubuntu@ip-172-31-2-45:~$ curl -v https://getbootstrap.com/
    *   Trying 104.20.30.249...
    * TCP_NODELAY set
    *   Trying 2606:4700:10::6814:1ff9...
    * TCP_NODELAY set
    * Immediate connect fail for 2606:4700:10::6814:1ff9: Network is unreachable
    *   Trying 2606:4700:10::6814:1ef9...
    * TCP_NODELAY set
    * Immediate connect fail for 2606:4700:10::6814:1ef9: Network is unreachable

This causes a variety of issues, for example a small search engine hosted on ec2, cannot index it.

Tested on AWS Lambda and various AWS EC2 instances using Chrome, curl, wget, ...

**Comment by mdo** [comment]
Cloudflare was having issues, but seems cleared up.
