### ISSUE TITLE
No focus style on checkbox and radios

### ISSUE THREAD

**Issue by alienlebarge** [twbs/bootstrap#28957]
### Description

There's no visual feedback when focusing a checkbox or radio.

### Ask

- Is this intended ?
- If not, will it be fixed ?

### Test case

Can be tested on [the current doc](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios)

![2019-06-25 11-48-09 2019-06-25 11_53_51](https://user-images.githubusercontent.com/611234/60089045-fde6b580-973f-11e9-9cb5-bbd0c4e5aa58.gif)

### Additional Info

- A similar bug was opened for v.3 and has been fixed #14923
- [Custom form controls](https://getbootstrap.com/docs/4.3/components/forms/#custom-forms) checkboxes and radios have a focus style.

**Comment by patrickhlauke** [comment]
There's no explicit style, but the default browser outline indicator is not suppressed (but that won't show up when forcibly triggering it via developer tools).

> ![focused checkbox showing dotted outline](https://user-images.githubusercontent.com/895831/60089601-bc064100-9738-11e9-8d41-43d53dac4d29.PNG)

However yes, it would be good to include the more visible custom blue shadow outline for these too (though for radio buttons, it will look rather odd, as it will be a block/square around a round radio input)

**Comment by alienlebarge** [comment]
@patrickhlauke 
It looks not so bad on radios
![Capture d’écran 2019-06-25 à 14 23 29](https://user-images.githubusercontent.com/611234/60097997-e36b0700-9754-11e9-8d5b-7c83a4b322fc.png)


I have done the fix locally. 
Can I propose a PR ?

**Comment by patrickhlauke** [comment]
> Can I propose a PR ?

sure thing, that'd be super helpful

**Comment by alienlebarge** [comment]
done

**Comment by mdo** [comment]
Regular checks are going to be gone in v5 starting soon, so this will be moot for that version. We don't explicitly override any focus styles here if memory serves though, so this is the browser not doing its job very well.

**Comment by patrickhlauke** [comment]
so no extra styles for regular checkboxes/radio buttons in v5? https://twbs-bootstrap.netlify.com/docs/4.3/components/forms/#checkboxes-and-radios

as for browsers not doing their job: we set explicit focus styles for other form controls with `.form-control:focus`, so why not also for `.form-check-input:focus` ?

**Comment by MartijnCuppens** [comment]
It would be consistent to have the focus style in `v4`.

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/28975#issuecomment-525383491.
