### ISSUE TITLE
add max sizes for "Relative to the viewport" in utilities/sizing

### ISSUE THREAD

**Issue by Naokimi** [twbs/bootstrap#28965]
Current viewport helpers:

```
.min-vw-100 { min-width: 100vw !important; }
.min-vh-100 { min-height: 100vh !important; }

.vw-100 { width: 100vw !important; }
.vh-100 { height: 100vh !important; }
```

Proposed new helpers:

```
.max-vw-100 { max-width: 100vw !important; }
.max-vh-100 { max-height: 100vh !important; }
```

Noticed this missing when I was building a page with one element having flexible size based on viewport. Fixed it with inline styling, but thought that maybe other people might want to use this feature too.

**Comment by filipkis** [comment]
I wonder why was this closed?

**Comment by ahmafi** [comment]
I'm missing this too!
