### ISSUE TITLE
Compiled CSS and JS vs. Source files

### ISSUE THREAD

**Issue by Naokimi** [twbs/bootstrap#28960]
Hi there, new to programming, but fell in love with Bootstrap (don't tell my wife) and would like to start contributing.

I downloaded the compiled CSS and JS files for one project (wanted to change the color variables) and found some issues with the CSS. How would I go into suggesting changes specifically for the compiled version? 

Thanks in advance for the replies!

**Comment by mdo** [comment]
The issue tracker here can be used for sharing bug reports or feature requests :). The compiled version is generated from our build scripts, so if you're seeing an issue, it's likely in the source Sass files or our `package.json`.
