### ISSUE TITLE
Documentation, Package Manager Composer

### ISSUE THREAD

**Issue by My6UoT9** [twbs/bootstrap#28967]
See https://getbootstrap.com/docs/4.3/getting-started/download/#package-managers

> ### Package managers
> Pull in Bootstrap’s source files into nearly any project with some of the most popular package managers. No matter the package manager, Bootstrap will require a Sass compiler and Autoprefixer for a setup that matches our official compiled versions.

It says that no matter the package manager, compatible build tools are required.
At least for composer that is not true, I don't know about the other package managers.
The given composer.json has actually zero requirements.

Obviously one can run `npm install`, since package.json and package-lock.json exists, but that is not whats suggested.

**Comment by patrickhlauke** [comment]
"require" as in "it requires it to run, so you need to make sure they're correctly called in your package manager". it doesn't mean "we've set it all up so it will automatically pull any dependencies into your package manager of choice"
