### ISSUE TITLE
Scrollspy Documentation Typo

### ISSUE THREAD

**Issue by adlesh** [twbs/bootstrap#28971]
### Current
.
.
.
```
  <h5 id="item-1-1">Item 1-1</h5>
  <p>...</p>
  <h5 id="item-1-2">Item **2-2**</h5>
```
.
.
.

### Fix
.
.
.
```
  <h5 id="item-1-1">Item 1-1</h5>
  <p>...</p>
  <h5 id="item-1-2">Item **1-2**</h5>
```
.
.
.
The content for #item1-2 in 'Example with nested nav' should read >Item 1-2 <; rather than, Item 2-2
[Bootstrap 4.0 Docs: Scrollspy](https://getbootstrap.com/docs/4.0/components/scrollspy/)

**Comment by ysds** [comment]
Thanks. That is already being fixed (#27079)

**Comment by adlesh** [comment]
I didn't see it as I was posting the issue, but the corresponding data in the actual content section was also incorrect 

`  <h5 id="item-1-2">Item **2-2**</h5>`

this should be 
`  <h5 id="item-1-2">Item **1-2**</h5>`

**Comment by ysds** [comment]
The latest document is here https://getbootstrap.com/docs/4.3/components/scrollspy/

**Comment by adlesh** [comment]
Ok awesome! Sorry if I was viewing the wrong thing! Was just trying to help; you guys do an awesome job!
