### ISSUE TITLE
[Q] [v4] Is it safe to change to gutter without touching the breakpoints?

### ISSUE THREAD

**Issue by dehghani-mehdi** [twbs/bootstrap#28976]
I like to change the gutter between columns, replacing `15px` with my value (e.g: 10px) is enough or should I change the breakpoints too?

I asked this question because of following discussions:
https://github.com/twbs/bootstrap/issues/21333
https://github.com/twbs/bootstrap/issues/18054
https://github.com/twbs/bootstrap/issues/14894

**Comment by mdo** [comment]
You don't need to change the breakpoints unless you want.

**Comment by dehghani-mehdi** [comment]
@mdo I changed the gutter to `0px`, now cols doesn't fill the width of the container.

![Screenshot_2](https://user-images.githubusercontent.com/9152330/61868718-46d08c00-aeef-11e9-9602-dbc47dbb3c63.png)
