### ISSUE TITLE
Opinion on TypeScript

### ISSUE THREAD

**Issue by cyberhck** [twbs/bootstrap#28977]
Hi, I'm so exited for v5 with the removal of jQuery, I wanted to know the maintainer's opinion on using TypeScript.

It'd be really helpful for new contributors to look into project and try to contribute, and we won't have to maintain type definition.

**Comment by Johann-S** [comment]
Hi @cyberhck,

I love TypeScript, I use it a lot, but it's a huge move to remove jQuery so there is no plan to use TypeScript currently maybe in our next major release 👍 

BTW there is a type definition maintained here: https://www.npmjs.com/package/@types/bootstrap

**Comment by cyberhck** [comment]
thanks for your response, definitely felt good that you'll think about it on your next major release, very excited for v5 as well though :) let me know if I can help on v6 :slightly_smiling_face:
