### ISSUE TITLE
.form-control-sm doesn't work inside .form-group.row

### ISSUE THREAD

**Issue by mayeenulislam** [twbs/bootstrap#28982]
Tested with the following code in my code base with Bootstrap 4.3.1
```html
<div class="form-group row">
    <label for="whatever" class="col-sm-2 col-form-label">Label</label>
    <div class="col-sm-10">
        <input type="text" id="whatever" class="form-control-sm">
    </div>
</div>
```

and found while the `.form-control` is working, the `.form-control-sm` is not working.
![Form Control SM inside .form-group.row](https://user-images.githubusercontent.com/4551598/60495147-0a37b900-9cd2-11e9-8ece-9092a29fb76a.png)

---

- Operating system: Windows 7 Ultimate (64-bit)
- Browser: Google Chrome v75.0.3770.100 (Official Build) (64-bit)

**Comment by tu4mo** [comment]
You need to have both, `.form-control` and `.form-control-sm`.
