### ISSUE TITLE
4.3.1 toast animation fadein fadeout doesn't work

### ISSUE THREAD

**Issue by Arryboom** [twbs/bootstrap#28987]
Accross the https://getbootstrap.com/docs/4.3/components/toasts/
we know

Options can be passed via data attributes or JavaScript. For data attributes, append the option name to data-, as in data-animation="".

animation | boolean | true | Apply a CSS fade transition to the toast

so simple code below import jquery,boostrap4.3.1.css,bootstrap4.3.1.js:
```
<script>$("#errortip").toast('show')</script>
<div id="errortip" role="alert" aria-live="assertive" aria-atomic="true" class="toast" data-animation="true" data-autohide="true" data-delay=8000 style="position: absolute; top: 0; right: 0;">
  <div class="toast-header">
    <img src="error2.png" class="rounded mr-2" alt="...">
    <strong class="mr-auto text-danger">Error</strong>
    <small>11 mins ago</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    Cannot decode this text.
  </div>
</div>
```
should got a toast showed with fadein and wait for 8000ms then fadeout,but actually nothing happen,a toast suddenly showed and after 8000ms suddenly disappear,no fade in or fade out style

**Comment by Johann-S** [comment]
Hi @Arryboom there is no fadein when the toast is shown only a fadeout on hide.
See: https://codepen.io/Johann-S/pen/KjBgze?editors=1010 you'll see the fadeout

**Comment by patrickhlauke** [comment]
@Johann-S and i assume the fadeout would only show if the reduce-motion preference wasn't set, right? (if so, that docs page needs the boxout pointing to that)

**Comment by Johann-S** [comment]
Yes you're right @patrickhlauke ! Good catch, I forgot (again) that reduce-motion preference 😄

**Comment by ysds** [comment]
In fact, it behaves strangely with or without the `hide` class.

https://codepen.io/anon/pen/qzyVdy

**Comment by ysds** [comment]
@Johann-S In you demo, the toast has a fadein animation when the first time (it is difficult to notice because it too early). There is no fadein when the second time and after. Please add:

```css
.fade {
  transition-duration: 2s;
}
```

**Comment by Johann-S** [comment]
I updated my CodePen: https://codepen.io/Johann-S/pen/KjBgze but sometimes I have the fadein each time, and sometimes not 😲

**Comment by patrickhlauke** [comment]
at the start, the toast only has a class of `toast`. triggering it adds the `toast fade showing` > `toast fade show` classes. once it disappears again, it has `toast fade hide`, and jumping from THAT to `toast fade showing` makes it show right away without fading in.

incidentally, we probably need to revisit the initial behavior for toasts...on load, they're still accessible via assistive technologies / screen readers, even though they're not visible. they should start off with `display: none` or `aria-hidden="true"`

**Comment by Arryboom** [comment]
don't know if anyhelp,i've been post this issue on stackoverflow and got a answer said "Try keeping the line  $("#errortip").toast('show') in a setTimeout."

https://stackoverflow.com/questions/56886034/toasts-animation-in-bootstrap/56886452#56886452

**Comment by XhmikosR** [comment]
@patrickhlauke: is this still valid?

**Comment by patrickhlauke** [comment]
i'd check with @Johann-S / using a codepen, as need to see a live example...but likely still has the problems i mentioned above (that were kind of separate from this bug here though, i guess)

**Comment by ysds** [comment]
This is a bug. CSS Transition can’t animate from a `display: none` element like:

```css
.element {
  opacity: 0;
  transition: opacity 300ms;
}

// from 
.element.hide {
  display: none;
}

// to
.element.show {
  display: block;
  opacity: 1;
}
```

It need "reflow" (one animation frame) between `from` and `to`.

https://github.com/twbs/bootstrap/blob/a76c13589dc06df32d38100c8488aa1a0b90931c/js/src/toast/toast.js#L116-L117

```js
 this._element.classList.remove(ClassName.HIDE) 
 reflow(this._element) // Add
 this._element.classList.add(ClassName.SHOWING) 
```
