### ISSUE TITLE
Starting to use bootstrap

### ISSUE THREAD

**Issue by catnipper40** [twbs/bootstrap#28996]
Hello,
   I've been coding for 18 years and I am now needing to learn to create responsive web pages.  I was told that Bootstrap was the way to go, but I am VERY confused by this very long .css file.  I'll check out the messages shown above.

**Comment by patrickhlauke** [comment]
i'd suggest reading the documentation https://getbootstrap.com/docs/4.3/getting-started/introduction/ rather than diving into the issues here.

**Comment by catnipper40** [comment]
Hi Patrick,
   I'm just  a little flustered with all this.  When you've always been able to understand something, then you have to switch to a new "language" it's a little overwhelming.  Will read the link, thanks.



________________________________
