### ISSUE TITLE
Bootstrap 4.3.1. tooltip (1) has white background color, (2) incorrectly positioned at the bottom.  I don't have the same problem with Bootstrap 3.3.7.

### ISSUE THREAD

**Issue by Brian1111** [twbs/bootstrap#28998]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by patrickhlauke** [comment]
You need to provide a reproducible reduced test case, Also, as tooltips don't have that issue, it is very likely a problem with your code and how you've implemented them.

**Comment by Brian1111** [comment]
It worked after I added popper.js before Bootstrap version 4.3.1.
