### ISSUE TITLE
Horizontal form button has .col-sm-10 with no .offset-sm-2

### ISSUE THREAD

**Issue by ryanneary** [twbs/bootstrap#28994]
https://getbootstrap.com/docs/4.3/components/forms/#horizontal-form

Button row should either be `class="col-sm-10 offset-sm-2"` or it shouldn't be a `.row` at all, depending on your preferred styling choice.

Personally I'd go for an offset, because it follows the flow of the form controls in `sm` and above.

**Comment by florianlacreuse** [comment]
According to me, the choice made for the button placement is just an example and not a strict rule. From this starting point, you can do anything you want to.

**Comment by ryanneary** [comment]
@florianlacreuse A row with just a `.col-sm-10` makes no sense?

**Comment by florianlacreuse** [comment]
Ok I understand now what you mean. I wouldn't say it makes no sense but I agree it seems useless. Thus, adding `offset-sm-2` sounds like a good idea to me. Do you want to do a PR?
