### ISSUE TITLE
Apply $zindex-fixed to position-fixed utility class

### ISSUE THREAD

**Issue by drakej** [twbs/bootstrap#29011]
It appears that **position-fixed** unlike **fixed-bottom** and **fixed-top** does not get the _$zindex-fixed_ variable set to it. All of them are part of the position utilities and use **fixed** positioning.

I would expect them to be consistent but I'm not sure this is a bug so I'm creating this as a feature request. 

https://getbootstrap.com/docs/4.3/layout/overview/#z-index

Can this get mentioned in the documentation to avoid confusion if this is expected behavior?

**Comment by mdo** [comment]
Utilities are generally single `property-value` pairings, so this would go against that approach. Thoughts from @MartijnCuppens on helper vs utilities here for v5?

**Comment by MartijnCuppens** [comment]
Yup, we've split the documentation to make it clearer in `v5`:
https://twbs-bootstrap.netlify.com/docs/4.3/helpers/position/
&
https://twbs-bootstrap.netlify.com/docs/4.3/utilities/position/

**Comment by drakej** [comment]
Cool, sounds like it's been fixed in 5 with documentation. Works for me.
