### ISSUE TITLE
Popover doesn't display content HTML5 tags when used as a function

### ISSUE THREAD

**Issue by webmasterlv** [twbs/bootstrap#29010]
When popovoer `content` function returns HTML string with HTML5 tags in it (such as `<article>`, `<time>` etc.) The content doesnt get displayed.

Here is a demonstration: https://codepen.io/mark-tyler/pen/NZobEw

**Comment by Johann-S** [comment]
Hi @webmasterlv,

You'll find the reason why here:
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

And how to fix that here:
https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
