### ISSUE TITLE
!important usage for .text-secondary

### ISSUE THREAD

**Issue by klierik** [twbs/bootstrap#29016]
Good day.

This issue about `!important` usage for .text-secondary.

Take a look:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_text-emphasis.scss

This code was added at Oct 30, 2015
Maybe it's time to remove `!important` ;)

**Comment by mdo** [comment]
Utilities include `!important` on purpose, and it won't be going away anytime soon on any of them.
