### ISSUE TITLE
drop-down <select> arrow is not display correctly in the Firefox

### ISSUE THREAD

**Issue by dslas4ever** [twbs/bootstrap#29015]
drop-down <select> arrow is not display correctly in the Firefox browser, with Bootstrap 4, attached issue screenshot below.

![arrow-issue](https://user-images.githubusercontent.com/1371043/61023383-1a941600-a3ed-11e9-94c0-c2f8fe911e5f.JPG)

**Comment by VamshiSeshasayan** [comment]
I see no issues with the dropdown arrow in firefox (see image below). Yours may be specific issue. You can share your code and screenshot so the community can address the issue. Screenshot is missing from your question.
![image](https://user-images.githubusercontent.com/4988277/61023095-16083700-a3c6-11e9-9648-7041ba07c98a.png)

**Comment by dslas4ever** [comment]
![arrow-issue](https://user-images.githubusercontent.com/1371043/61023402-2f70a980-a3ed-11e9-9205-6a0dbc22309f.JPG)

**Comment by dslas4ever** [comment]
@VamshiSeshasayan Thanks for your reply,
Just noticed imaged is not attached with the previous post! Just add it back, And this happened only in Firefox browser, this how it's looks like in chrome browser, attached below,

![arrow-in-chrome](https://user-images.githubusercontent.com/1371043/61023597-e836e880-a3ed-11e9-9da4-7e1f91bc64d6.JPG)

**Comment by dslas4ever** [comment]
However I found a way to fix it using below CSS, but it's actually css hacked.

.bootstrap-select > .dropdown-toggle::after {
    position: absolute;
    top: 50%;
    right: 12px;
    margin-top: -2px;
    vertical-align: middle;
}

**Comment by VamshiSeshasayan** [comment]
Ok. Nice that you found a solution. However, from the CSS hack you have used, it seems the issues is with bootstrap-select but not bootstrap dropdown. SO issue related to it can be posted in its repo [here](https://github.com/snapappointments/bootstrap-select)
