### ISSUE TITLE
scrollbar cover the content on horizental mode in pre bracket

### ISSUE THREAD

**Issue by KyleBing** [twbs/bootstrap#29028]
Bug reports must include:

- macOS
- Chrome
- v4.3

<img width="553" alt="Screen Shot 2019-07-13 at 17 26 49" src="https://user-images.githubusercontent.com/12215982/61169784-dc852680-a593-11e9-8c08-b4036554fc67.png">

**Comment by patrickhlauke** [comment]
duplicate of https://github.com/twbs/bootstrap/issues/28498
