### ISSUE TITLE
Multiple broken documentation links

### ISSUE THREAD

**Issue by m-alzam** [twbs/bootstrap#29034]
Hello.
There are various broken documentation links, that points to licenses.
- The "Creative Commons" link in the [README.md](https://github.com/twbs/bootstrap/blob/master/README.md#copyright-and-license) file.
- The "MIT license" link in the [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/v4.3.1/.github/CONTRIBUTING.md#license) file.
- ~~The "Creative Commons Attribution 3.0 Unported License" link in the same file.~~ (Already fixed?)

Thanks.

**Comment by midzer** [comment]
Hi @m-alzam 
Good spotting and thanks for filling :)

Do you want to contribute by opening a PR to fix this issue?

**Comment by m-alzam** [comment]
Thanks.
I would like to contribute.
