### ISSUE TITLE
JavaScript size improvements

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#29043]
In order to minify a bit the js size of each js plugin , does it seems valid to use a global subtractive approach on the following?

```js 
 static _jQueryInterface(config) { ....
```

```js

if (typeof $ !== 'undefined') {
  const JQUERY_NO_CONFLICT = $.fn[NAME]
  $.fn[NAME] = Popover._jQueryInterface
  $.fn[NAME].Constructor = Popover
  $.fn[NAME].noConflict = () => {
    $.fn[NAME] = JQUERY_NO_CONFLICT
    return Popover._jQueryInterface
  }
}
```

```html
[data-dismiss="{class}"]
```

And final **show** , **hide** and **toggle** functions maybe can be used in a generic way, handling by default the appropriate events, aria-hidden, 'show' class and give access to specific functionality , with the use of callbacks

**Comment by Johann-S** [comment]
Hi @GeoSot,

Not sure if I understand totally what you mean, but feel free to create a PR to demonstrate what you mean

**Comment by mdo** [comment]
Closing as stale. Good news is we did shave ~5-6 off our JS in v4.5.0!
