### ISSUE TITLE
Font weight of all <a> tags temporarily increases on carousel scroll

### ISSUE THREAD

**Issue by akmadian** [twbs/bootstrap#29042]
When a carousel's image changes, the font weight of all <a>'s go from the default 400 to somewhere around 450ish. This happens when the carousel is auto scrolling, and when it is manually scrolled. It looks like the surrounding pixels of each letter in the <a> text go from white (the background) to a very light blue. This effect begins when the carousel begins the scrolling animation, and reverts to normal when the animation stops. I've looked in Chrome dev tools, and the dev tools do not show the font-weight attribute changing. This effect is visible on multiple resolutions.

- Operating system and version: Windows 10 Pro 1809 17763.15 (64-Bit)
- Browser and version: Chrome 75.0.3770.100 (64-Bit), was not able to replicate on Firefox 67.0.1
- [Reduced test case](https://codepen.io/akmadian/pen/PrvvRg). This codepen isn't able to replicate it (as far as I can see). I can provide a video if needed, but I imagine it will be quite difficult to see, especially with YouTube's compression.

**Comment by patrickhlauke** [comment]
i'm seeing no images in that codepen.

i'll hazard a guess that it's a problem with Chrome's accelerated GPU rendering of text when things use CSS transforms - Chrome is notorious for making text look horridly blurry in those situations (particularly coupled with zoom settings in browser)

**Comment by akmadian** [comment]
Thanks! Will look into GPU Acceleration stuff tomorrow. This (possibly) being an issue with Chromium rendering would make sense, as Firefox does not have the same problem.

**Comment by patrickhlauke** [comment]
https://www.google.com/search?q=chrome+font+rendering+hardware+acceleration

sadly, it's a thorny problem with no good solution to it it seems...unless one drops CSS that uses hardware acceleration (i.e. no CSS transforms or similar), which has performance penalties

**Comment by akmadian** [comment]
Tried turning off hardware acceleration in Chrome settings, did not fix the issue. Is there a setting in Windows or somewhere in my Geforce Experience that I should take a look at?

**Comment by mdo** [comment]
https://stackoverflow.com/questions/12502234/how-to-prevent-webkit-text-rendering-change-during-css-transition

**Comment by mdo** [comment]
Hit submit too soon. Basically this is the hardware acceleration problem, but I'm unsure how to help on all of Windows machines. On macOS you can get around it by disabling LCD font smoothing.

**Comment by mdo** [comment]
Closing as a (stale) won't fix.
