### ISSUE TITLE
conent bleading issue when using bootstrap card-columns CSS class

### ISSUE THREAD

**Issue by Rahul-Narayanasamy** [twbs/bootstrap#29045]
Hi Bootstrap team,

We have facing some strange scenario while using bootstrap **card-columns** CSS class. Here, we have rendered our scrollable data table in one bootstrap card-column class then its working fine. But we have faced the bleeding content issue (in all Grid except first one), when we render the same table in more than one inside bootstrap **card-columns**.

Here, we have attached sample and screenshot for your reference for your reference.

Sample: https://codepen.io/Rahul23/pen/NZZbpV 

ScreenShot;
![image](https://user-images.githubusercontent.com/34653188/61218333-6ddcd000-a72f-11e9-8595-dd8a377a4577.png)

Note: The reported problem is occurred in Chrome browser 

Could you please check this and update further details.

Regards,
Rahul

**Comment by mdo** [comment]
CSS columns are super buggy across browsers. Please change to using the Bootstrap grid and you should have fewer issues.
