### ISSUE TITLE
Buttons plugin for checkbox does not work when checkbox is outside <label>

### ISSUE THREAD

**Issue by yuriiz** [twbs/bootstrap#29052]
Buttons plugin for checkboxes (https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons) currently work properly only when checkbox is directly inside label like in docs:
```
<div class="btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-secondary active">
    <input type="checkbox" checked autocomplete="off"> Checked
  </label>
</div>
```
But it does not work when it is placed somewhere else and attached to label with `for`->`id` mechanism.

Consider following use case: I would like to use toggle button to change appearance of some other elements down below layout based on button's state. They only way to do it is with markup like this:
```
<input type="checkbox" checked autocomplete="off" id="toggle-styles">
<div>
  <!-- some button surroundings like placing it in .col of .row for example -->
  <div class="btn-group-toggle" data-toggle="buttons">
    <label class="btn btn-secondary active" for="toggle-styles">
       Toggle styles
    </label>
  </div>
  <!-- some button surroundings -->
</div>
<div>
  <!-- some elements with dynamic styles based on #toggle-styles:checked -->
</div>
```
###### Current behaviour
However with this layout button plugin only toggles `.active` state for `<label>` but does not change `:checked` state of checkbox.
###### Explanation
The reason is that Bootstrap's click handler for [data-toggle=buttons] for no good reason does event.preventDefault() blocking browser's builtin handler from toggling attached checkbox.
###### Expected behaviour
Bootstrap's click handler should not interfere with browser's standard behaviour for labels and checkboxes and after toggling `.active` state it should allow event to propagate so checkbox's `:checked` state would be toggled as well.

Demo: https://codepen.io/anon/pen/NZQKam

Tested on Firefox 68 on Ubuntu 19.04 Bootstrap 4.3.1.

**Comment by patrickhlauke** [comment]
should be fixed by https://github.com/twbs/bootstrap/pull/28834 which, among other things, removes the `preventDefault()`
