### ISSUE TITLE
Popover input elements in modal window not working in IE11

### ISSUE THREAD

**Issue by dshchupak** [twbs/bootstrap#29056]
When trying to load input elements inside a popover that is within a modal window, behavior of the input is strange. The placeholder does not disappear when focus is applied to the input element and is selectable. The value of the element is null/empty no matter what is typed inside.

An example can be found here: https://jsfiddle.net/k01eu9zt/1/
* Open the modal window and then click on the blue person with a plus sign. A popover will appear and the input element inside that popover is displaying the issue mentioned above.

This **ONLY** occurs in IE11.

**Comment by MartijnCuppens** [comment]
This is a browser bug we can't fix. The placeholder text is even selectable and deletable.
