### ISSUE TITLE
Scrollspy: adding URL in href breaks scrollspy

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#29055]
Linux OS, Chrome 75 browser

Adding URL in href breaks scrollspy. 
Usecase: navbar section has links to other HTML pages, not just the current one, eg
```
<a class="nav-link" href="/contact#main">Contact</a>
```

To replicate: In Bootstrap example, change href from
```
<a class="nav-link" href="#fat">@fat</a>
```
to
```
<a class="nav-link" href="/#fat">@fat</a>
```

Thanks

**Comment by morrissey-ingenious** [comment]
you can use the `data-target="#fat"` to overcome this.

[fiddle](https://jsfiddle.net/morrissey_ingenious/2rj1aphx/)

**Comment by mariusa** [comment]
You're right, it works! Thank you :)
