### ISSUE TITLE
Hover Sticky Issue on Mobile Device

### ISSUE THREAD

**Issue by dhruv-tank** [twbs/bootstrap#29063]
Hi,

Bootstrap button hover is getting stuck in active state on mobile devices. Working properly on the desktop/laptop screen. Please help.

Thanks in Advance
Dhruv

Current code:
     `` <div class="d-flex justify-content-center">
	<div class="btn-toggle" data-toggle="buttons" >
	<div id="1" align="center">
	<label id="option1s" class="btn btn-outline-primary">
        <input type="checkbox" id="option1" name="values" value="Achievement"> Achievement
	</label>
	</div>
	</div>
	</div> ``

**Comment by dhruv-tank** [comment]
@cvrebert can you please help?

**Comment by coliff** [comment]
Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

I don't think checkboxes within buttons would be supported.
