### ISSUE TITLE
Make use of svg-escape function

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29065]
We should introduce a function to escape SVGs. Some SVGs are not escaped, causing them not to render in IE:
https://github.com/twbs/bootstrap/blob/78c9c8bdd4cad5e6d1fc349d45b7503bad84a19b/scss/_variables.scss#L541

Some SVGs are escaped, but they are harder to read/maintain:
https://github.com/twbs/bootstrap/blob/78c9c8bdd4cad5e6d1fc349d45b7503bad84a19b/scss/_variables.scss#L547

I've used these functions in the past, they're freakin awesome to get this fixed: https://codepen.io/kevinweber/pen/dXWoRw?editors=1100

**Comment by XhmikosR** [comment]
After we have this, we can tackle #29066 easier.
