### ISSUE TITLE
Iconic is unmaintained and should not be recommended

### ISSUE THREAD

**Issue by patja** [twbs/bootstrap#29076]
The iconic font library recommended in the documentation is no longer being maintained, and should not be recommended as one of the two recommended icon solutions for bootstrap.   The ssl cert on the documentation site at useiconic.com has expired several times and is presently (July 18 2019) expired.  It appears that the firm who made iconic was acquired and the buyer is uninterested in maintaining it.

see

https://github.com/iconic/open-iconic/issues/45

https://waybury.com/

**Comment by mdo** [comment]
Tackling for v5 in #29048, but wouldn't mind a PR from you or someone else to tackle this for v4 :).

**Comment by catchmyfame** [comment]
Isn't this still referenced on https://getbootstrap.com/docs/4.1/components/forms/#checkboxes-and-radios-1?

> In the checked states, we use base64 embedded SVG icons from [Open Iconic](https://useiconic.com/open). This provides us the best control for styling and positioning across browsers and devices.

**Comment by XhmikosR** [comment]
v4.1 is quite old.

**Comment by catchmyfame** [comment]
@XhmikosR Sorry, wrong link. Updated to the latest version which still has the same text

**Comment by XhmikosR** [comment]
That's because we never fixed that. This issue was about another page.

Generally, it's better to make a new issue if there's no open issue for something, instead of commenting in old issues.

So, please make a new issue.

**Comment by XhmikosR** [comment]
Actually, wait, I can't find any references in the v4-dev branch, so we probably fixed that in the meantime.
