### ISSUE TITLE
Bootstrap modal position in WebView UI

### ISSUE THREAD

**Issue by coda-apps** [twbs/bootstrap#29084]
Using Bootstrap 4.3.1

On my site, modals work perfectly, in responsive mode too.

I also have an Android app, that among other functions, contains my site in WebView. When I trigger a modal within WebView in the App, on a long page - it opens at the top of the page (not vertically centered) and if you happen to be half scrolled down the page, you will not see it, as the position is fixed to the top, and you now need to scroll UP to see it (if you even know it opened).

Again, in a log web-page, in mobile form - the issue does not exist - only in WebView. Has anyone run into this?

This is the code/position for the modal.

```
.modal {
    position: fixed;
    top: 0;
    right: 0;
    z-index: 1050;
    display: none;
    width: 100%;
    height: 100%;
    overflow: hidden;
    outline: 0;
}
```

It seems that in WebView, the position: fixed; is ignored - as it's relative to the window, so if it scrolls down, the modals goes up with the page.

Tests for this are tricky, as to test properly, you need to test **within an app**, within a WebView Container (as I mentioned, in Chrome responsive on mobile, this issue does not exist) and not just in web/chrome. So one would need a super simple app using **Android Studio** (which I used) or similar.

**Comment by patrickhlauke** [comment]
As this sounds like a shortcoming/incompatibility of how the WebView component handles things (ignoring `position:fixed`), I'm not sure there's much that can be done at Bootstrap's end. I'd suggest checking in StackOverflow of Slack - see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
