### ISSUE TITLE
form-control is-invalid shows valid

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#29085]
`<input id="security_code" name="security_code" type="text" class="form-control is-invalid">` shows valid because of `form-control:valid` comes before `.form-control.is-invalid` at https://github.com/twbs/bootstrap/blob/master/scss/mixins/_forms.scss#L31

CodePen: https://codepen.io/bassjobsen/pen/WVQWKe

Bootstrap version: 4.3.1
Browser: Version 74.0.3729.131 (Official Build) (64-bit)
OS: Ubuntu 18.04.2 LTS

Notice that if `.is-invalid` is only intend as a fall-back for `:valid` this is not a bug at all.

In my use case i want to use `.is-invalid` for any kind of invalid input.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by mdo** [comment]
You shouldn't be mixing the psuedo classes with the standard classes. Remove `.was-validated` and add `novalidate` on the form and it works as intended.

```html
<form class="p-3" novalidate>
  <input id="security_code" name="security_code" value="this is invalid" type="text" class="form-control is-invalid">
</form>
```
