### ISSUE TITLE
-webkit-background-clip: text; doesn't work on a column children

### ISSUE THREAD

**Issue by whatistheplot** [twbs/bootstrap#29093]
Hey there,

trying to have a gradient text but if I set a ```  -webkit-background-clip:text;``` on container or a row which has a child column the whole thing gets bugged on chrome and safari. (everything works fine on Firefox)

```
.blue{
     background-color: blue;
     -webkit-background-clip:text ;
     -webkit-text-fill-color: transparent;
   }
 
<div class="row blue">
  <div class="col">
    text
  </div>
</div>
```
this works:
```
.blue{
     background-color: blue;
     -webkit-background-clip:text ;
     -webkit-text-fill-color: transparent;
   }
 
<div class="row">
  <div class="col blue">
    text
  </div>
</div>
```

**Comment by ysds** [comment]
Closing this because those CSS are experimental and doesn't look a bug of Bootstrap.

https://codepen.io/anon/pen/eqpbrd
