### ISSUE TITLE
Can't embed dynamic content in popover

### ISSUE THREAD

**Issue by Johnnii360** [twbs/bootstrap#29103]
Hi guy's,

I'm try now over day's to embed dynamic content into a popover.

OS: Windows 10
Browser: Chrome Latest
Boostrap: 4.3
jQuery: 3.4.1
Popper.js: Latest

This is the popover code that be loading once:
`var popu = $('.popu');
    popu.popover({
        container: 'body',
        html: true,
        placement: 'left',
        trigger: 'hover',
        content: '<div class="d-flex justify-content-center"><div class="spinner-border" role="status"><span class="sr-only">Lade...</span></div></div>'
    });
    popu.each(function() {
        let element = $(this);
        let id = element.attr('id');
        $.ajax({
            dataType: 'html',
            url: 'ajax/SucheBedarfspositionenAuslesen.php?nr=' + id,
            cache: true,
            success: function(data) {
                $(".popover-content", element).html(data);
            }
        });
    });`

And this is one of the dynamical generated contents that I want to embed in a popover:
`<table class="table">
<thead class="bg-info">
    <tr>
        <th scope="col">Bestellung</th>
        <th scope="col">Bezeichnung</th>
        <th scope="col" class="text-center">Anzahl</th>
        <th scope="col">Lieferant</th>
    </tr>
</thead>
<tbody>
        <tr>
        <th scope="row">14013MAIL</th>
        <td>Logitech Wireless Mouse</td>
        <td class="text-center">1</td>
        <td>Conrad</td>
    </tr>
        <tr>
        <th scope="row">14013TOOL</th>
        <td>Tastatur</td>
        <td class="text-center">1</td>
        <td>HP</td>
    </tr>
    </tbody>
</table>`

The issue is that I still see the loading spinner and get no content in the popover. I already tried much of variations that I can find on Google oder Stackoverflow but nothing worked.

It's really strange because the data loading very well and can be displayed in a `alert()`.

**Comment by Johann-S** [comment]
Hi @Johnnii360,

Bootstrap sanitize html content, so if you want to allow some html tags, please refer to our docs: 
https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
