### ISSUE TITLE
Sidebar first nav menu hide in firefox in example dashboard project (again)

### ISSUE THREAD

**Issue by mbystryantsev** [twbs/bootstrap#29108]
Mozilla Firefox 68.0 (64-bit)
https://getbootstrap.com/docs/4.0/examples/dashboard/

The same problem as in #25959 - first nav menu item is not visible in Firefox.

**Comment by coliff** [comment]
have you checked against the latest version of Bootstrap (4.3) ?
https://getbootstrap.com/docs/4.3/examples/dashboard/

**Comment by coliff** [comment]
It works correctly in Firefox since Bootstrap 4.1 so I think you can close this issue.
Make sure to always use the latest version of Bootstrap :-)
