### ISSUE TITLE
How do I extend / overwrite a specific popover show function

### ISSUE THREAD

**Issue by stephenbe** [twbs/bootstrap#29117]
Hi,

With bootstrap 3 it was possible to extend a specific function like this where they use a _super to call the original constructor : 
https://stackoverflow.com/a/12689534/1646514

So if I wanted to, I could overwrite the show function and write my own code there without having to modify directly the sourcefiles. 

```
var _show = $.fn.popover.Constructor.prototype.show;
$.fn.popover.Constructor.prototype.show = function() {
    _show.apply(this, arguments);
    //Do custom stuff here
};
```

So far I was able to do this where I can apply code after the popover is created, but I cannot overwrite the show completely. 

I know it's better to use the api, but it's for a framework built on bootstrap so we have specific needs that required an overwrite.

The framework is very friendly overwriting sass files and creating something completely custom, but with JS there is less documentation about how to overwrite certain parts of it. Probably due to the fact that the visuals need to change where as the JS is not something everyone needs to change

**Comment by Johann-S** [comment]
Hi @stephenbe,

In v4, you can overwrite any function by changing the prototype, for example:
```js
var defaultShowPopover = bootstrap.Popover.prototype.show
bootstrap.Popover.prototype.show = function () {
    defaultShowPopover.apply(this, arguments);
    // Your custom stuff here
}
```

is it what you wanted?

**Comment by stephenbe** [comment]
Hi @Johann-S ,

Thank you so much for the fast reply. Actually that is really close it's the same solution I listed above, but I wasn't clear enough. I would like to take all of bootstrap show code and put it in there instead of defaultShowPopover.apply(this, arguments); and change their code ever so slightly. 

With this solution I can put my code after the popover has already initialised.

https://github.com/twbs/bootstrap/blob/master/js/dist/tooltip.js#L525-L622
I would like to put this code back in and modify it to fits my needs. I am getting errors because it is referencing EventHandler variable that is defined at the top of the file which is generated by rollup.js.

**Comment by Johann-S** [comment]
You linked a file from our v5, which do not use jQuery. `EventHandler` is our internal event system (https://github.com/twbs/bootstrap/blob/master/js/dist/dom/event-handler.js).

So, if I were you I would inherit from Bootstrap classes, like that you would be able to override or to use our built-in methods, it would be a reliable way to customize our components behavior

**Comment by stephenbe** [comment]
When you say inherit bootstrap classes do you mean extending Tooltip class here?
https://github.com/twbs/bootstrap/blob/v4.3.1/js/src/tooltip.js#L120

I have the same problem util is not defined because of the generated code on top of that file
https://github.com/twbs/bootstrap/blob/v4.3.1/js/dist/tooltip.js#L379-L475

Thank you for your patience with me on this

**Comment by Johann-S** [comment]
Yep you should inherit from the class you want to override some methods.

Yep we use Rollup to bundle our files, that's why we split our source code into several files. So you should use a bundler too (Webpack, Rollup, etc) and install Bootstrap as a dependency of your project, like that you won't have that kind of errors

**Comment by stephenbe** [comment]
Alright thanks so I would need to create a whole new bs build myself with webpack rollup and import tooltip myself.

I might be able to avoid that with the overwrite you offered in the beginning.

If you have a boilerplate to make a custom js build of bootstrap that would be awesome.

**Comment by vrushank** [comment]
> Hi @stephenbe,
> 
> In v4, you can overwrite any function by changing the prototype, for example:
> 
> ```js
> var defaultShowPopover = bootstrap.Popover.prototype.show
> bootstrap.Popover.prototype.show = function () {
>     defaultShowPopover.apply(this, arguments);
>     // Your custom stuff here
> }
> ```
> 
> is it what you wanted?

What about v5? How can we do the same in v5? It used to work for me in v4 but not working in v5.
