### ISSUE TITLE
Modal not opening

### ISSUE THREAD

**Issue by alexandre433** [twbs/bootstrap#29129]
Windows 10 Home
Chrome 75.0.3770.142 64 bits

I've found that each time you make a modal and in the id of it you start it with an integer e.g.
`id="1abc"` and on the button that shows it `data-target="#1abc"` it does not display the modal.

Once you turn the first character into a letter, it will work. In the js that calls the id it might be casting to integer instead of string.

**Comment by xcartmods** [comment]
https://css-tricks.com/ids-cannot-start-with-a-number/

**Comment by Johann-S** [comment]
Hi @alexandre433 it's written in our docs why: 
 - https://getbootstrap.com/docs/4.3/getting-started/javascript/#selectors
 - https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

**Comment by jzabate** [comment]
Hi Guys,

Is there any workaround on this? Like staying with id="1abc" data-target="1abc".

Much appreciated.
