### ISSUE TITLE
empty h3 in popover when title is not defined

### ISSUE THREAD

**Issue by stevenbriscoeca** [twbs/bootstrap#29127]
**Operating system**
Windows
**Browser and version**
Chrome 73
**Reduced test case**
https://getbootstrap.com/docs/4.3/components/popovers/#four-directions

On popovers that do not have a title defined, the h3 is still there as empty. I feel this could be an accessibility problem having an empty h3 on the page : 
![image](https://user-images.githubusercontent.com/3018441/61815613-a60f9d00-ae18-11e9-8e45-935b58351496.png)

I would make sure the h3 disappears if the title is not defined.

**Comment by Johann-S** [comment]
@patrickhlauke do you think it can be an accessibility problem?

BTW you can customize the default template see `template` option: https://getbootstrap.com/docs/4.3/components/popovers/#options

**Comment by XhmikosR** [comment]
I'd say that the fewer things we add in DOM the better generally.

**Comment by charlottedestrait** [comment]
Hello, I'd like to fix this issue, is it possible ?

**Comment by Johann-S** [comment]
it's open @charlottedestrait so feel free to tackle it 😉
