### ISSUE TITLE
class="form-signin" only allow refresh

### ISSUE THREAD

**Issue by jinwei14** [twbs/bootstrap#29133]
```<form class="form-signin">```
 will make the page refreshed when clicking the signing button. 

This error happed in the [signin](https://getbootstrap.com/docs/4.3/examples/sign-in/) example and the [floating label](https://getbootstrap.com/docs/4.3/examples/floating-labels/). 

My intension was to click on the link and redirect to another page. But the sign in button will only refresh the page no matte what is entered in the form.

I have searched on online but don't know how to solve it. I am new to this, Pls help me if any of you know how to solve it, thanks in advanced.

**Comment by coliff** [comment]
Both the form examples are intended as simple layout examples and don't include any logic on how the form would submit the data.

Maybe you're using PHP, or using with Angular or React - or connecting to a 3rd party API. There are many different ways, so it really depends on what technology you're using and what exactly you want to happen. If you're creating a signin form then I'd imagine you'd want that connecting to a server/database of some sort and your form would have something like:
`<form class="form-signin" action="signin.php" method="POST">`

**Comment by jinwei14** [comment]
Thank you for your quick response, I will try it out, My first intension was to assign a javascript to catch the input username and password then redirect to another page such as '../index.html'. is there any way to do the function of action="signin.php" using javascript ?

**Comment by coliff** [comment]
It'd be possible using JavaScript, but I wouldn't advise it - doing it like that would mean there would be no validation and anyone could 'login' with any username/password combination.
