### ISSUE TITLE
Package with SASS to cdnjs or unpkg for use with LibMan (VS .net core projects)

### ISSUE THREAD

**Issue by jerchap** [twbs/bootstrap#29137]
Can you make bootstrap (with SASS) available for asp.net core developers.  Libman is the only package manager with a simple workflow for Visual Studio developers building asp.net core applications, because it is the only one that will install the package in the correct location.  Nuget doesn't support content files in .net core projects for some reason, and npm installs to the node_modules directly that is outside of wwwroot.  Can you publish bootstrap packages with sass so they are available using libman?  I think that means publishing to cdnjs or unpkg.

**Comment by coliff** [comment]
Have you tried unpkg CDN?
https://unpkg.com/bootstrap@4.3.1/scss/

**Comment by mdo** [comment]
No plans to split up how we publish our packages, or to pick up new package managers. Sorry!
