### ISSUE TITLE
See if we can use Hugo v0.56's enhancements

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29142]
https://gohugo.io/news/0.56.0-relnotes/

**Comment by MartijnCuppens** [comment]
> A new module configuration section where you can import almost anything. You can configure both your own file mounts and the file mounts of the modules you import. This is the new recommended way of configuring what you earlier put in configDir, staticDir etc. And it also allows you to mount folders in non-Hugo-projects, **e.g. the SCSS folder in the Bootstrap GitHub project**.

I guess so, since they explicitly mention us 😄

**Comment by XhmikosR** [comment]
Yeah, I saw that too, but we need to actually try this ourselves in a PR and see it in action. Like try to use it for the SRI hashes.

**Comment by bep** [comment]
Yes, you can use this, but my mention of this project was more the other way around ... for people to mount your `SCSS` folder in their Hugo project.

**Comment by bep** [comment]
@XhmikosR if you want to SRI hash this you need to mount it into `assets` (not `static`)  and use `resources.Get` to load.

**Comment by gautambhaskar** [comment]
Is this still open?
