### ISSUE TITLE
IE 11 and IE Edge Dropdown and copy code to clipboard issue

### ISSUE THREAD

**Issue by ravanda2** [twbs/bootstrap#29169]
I cloned this repository to upgrade from 4.1.3 to 4.3.1 to resolve the security issue found in 4.1.3. 
After adopting the project code to the newer release (4.3.1) we are experiencing some issues only in IE 11, and Edge. For example Dropdowns don't work, and code copy to clipboard is also stop working. We don't have any problem in Chrome, Safari and FireFox. When I use debug console in IE that says there are issues with bootstrap.js file, I don't get that error in other browsers. I found a quick fix with replacing bootstrap.js from Bootstrap website but that doesn't tell me what's cause of the issue. I tested a simple bootstrap dropdown without my custom js code and got the same result.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by ravanda2** [comment]
https://codepen.io/adn75/pen/zgwGmQ

**Comment by Johann-S** [comment]
Hi @ravanda2,

I forked your CodePen, but I'm unable to reproduce any error on Win10 with IE 11 😟 Maybe can you share with us the JavaScript error ?

My codepen forked from yours: https://codepen.io/Johann-S/pen/WVjXLW
Debug link for IE 11: https://s.codepen.io/Johann-S/debug/WVjXLW

**Comment by ravanda2** [comment]
Hi Johann-S and mdo,

Thanks for checking. Following is the error 
(same error from 2 different files "const { jQuery } = window")

SCRIPT1010: Expected identifier
bootstrap.js (23,9)
SCRIPT1010: Expected identifier
bootstrap.bundle.js (21,9)

**Comment by Johann-S** [comment]
I think you're trying to use our v5 which is under development, to get the latest release of our v4 see: https://getbootstrap.com/docs/4.3/getting-started/introduction/#js

The code you shared is from our v5

**Comment by ravanda2** [comment]
I cannot confirm if it was v5 because it was a couple of weeks ago but was v5 found on the brach master?

**Comment by ravanda2** [comment]
Again Thanks for your support and quick response. The bootstrap.js doesn't say anything about v5. Please see the following release note of the bootstrap.js that we used. Thanks   

/*!
  * Bootstrap v4.3.1 (https://getbootstrap.com/)
  * Copyright 2011-2019 The Bootstrap Authors (https://github.com/twbs/bootstrap/graphs/contributors)
  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
  */

**Comment by Johann-S** [comment]
Our master is our development branch and this is where we build the next major release (v5) that's why I gave you a link where you can download the latest release
