### ISSUE TITLE
Not found switch toggle styling (.custom-switch) after compiling sass

### ISSUE THREAD

**Issue by vosidiy** [twbs/bootstrap#29179]
Before opening:

We can use custom-switch element from ready to use /dist folder
But, there is nothing like this when we download sass files of Bootstrap

![2019-07-31_1802](https://user-images.githubusercontent.com/36692987/62213970-869ae600-b3bd-11e9-9431-50768ae2fd2f.png)

**Comment by coliff** [comment]
`custom-switch` is included in the Sass source files latest ZIP. I use it myself by compiling from Sass. Search for `custom-switch` and you'll see it.

![image](https://user-images.githubusercontent.com/1212885/62226253-dcd74b80-b3f4-11e9-8b1e-50462e43f9ea.png)

**Comment by XhmikosR** [comment]
This doesn't exist in master. Make sure you are on the branch you intended to be.
