### ISSUE TITLE
class form-control inside input-group truncated in Webkit

### ISSUE THREAD

**Issue by teran-mckinney** [twbs/bootstrap#29187]
Hi Bootstrap team,

First of all, thank you for helping me not write so much CSS. It is a godsend.

Now, I'm seeing this really weird behavior that may be a Bootstrap bug, may be a Webkit bug. I haven't yet validated the Webkit version, but I'm seeing this on a Kindle e-reader browser and wkhtmltoimage.

```
<!DOCTYPE html>.
<html>
<head>
    <title>webkit truncated form-control inside input-group Bootstrap 4.3.1 behavior</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<div class="input-group">
    <input class="form-control" type="text" maxlength=4096 name="data" placeholder="Say something... If you want me to get back to you, leave an email or another contact method.">
</div>
</body>
</html>
```

This looks like this in Chrome, Firefox, Safari, etc.

![Working](https://pic8.co/sh/hm0eGB.png)

And in Webkit.

![Not so working](https://pic8.co/sh/bo11Nm.png)

I understand if this is too dated to care about or if it's a browser bug. Just hoping to know where to go with this, if I should report it to Webkit, if it's a known bug or what have you.

Thank you for your time.

-Teran

**Comment by mdo** [comment]
I'd start with Webkit bug, yes. Sounds like a difference in how flexbox is implemented. I'm unaware of any meaningful differences though, and vanilla Webkit is not explicitly on our list of supported browsers.

**Comment by teran-mckinney** [comment]
Thank you! Just confirmed webkit2 works anyway. webkit1 seems to have the issue. Will see if I can come up with a workaround or if I'll just let it be.
