### ISSUE TITLE
Button - box-shadow --variable settings fails!? (glow effect)

### ISSUE THREAD

**Issue by Lakro** [twbs/bootstrap#29180]
Bootstrap 4.3.1 - Buttons

When I try to style buttons by variables settings and to remove box-shadow (glow effect) I try:

```
$btn-box-shadow:           	unset;
$btn-focus-width:                    0;
$btn-active-box-shadow:         unset;
```

Unfortunately on button focus-state Bootstrap generates:
 
```
.btn-primary:focus:     unset, 0 0 0 0 rgba(38, 66, 99, 0.5)
.btn:focus:                  0 0 0 0.2rem rgba(0, 123, 255, 0.25)
```

In following older issue:
[https://github.com/twbs/bootstrap/issues/24242]
I found some workarrounds - no real solutions!
For whatever the issue had been closed uncommented.
Obviously without fixing it?

Is there anyone who could confirm that behaviour?

...
@Bootstrap-Team:
That's definitively wrong code and a little hustle in it.
It would be wonderful if you could fix it ... 
Maybe some more intuitive variables could help?
...

And doing this you would save a lot of time of a lot of devs who will look arround for a solution wondering that the correct/intuitiv way in a damned good framework does not work ;-)

Thx a lot!

> Workarround:
> Best quick work-arround for me has been:
> Advise '.shadow-none' to the button.
> But that doesn't help on theming a genral theme.
> In That case only hardcoding (overwriting) in (s)css seems to help ;-)

**Comment by mdo** [comment]
This is for accessibility reasons—you should always maintain a keyboard focus indicator of some kind.

**Comment by Lakro** [comment]
@mdo 
Thank you very much for quick checking it.

But sorry to be honest: that is not the point and does not match the reported issue.

Your answer: 

> Accessibility reasons—you should always maintain a keyboard focus indicator of some kind

Accessibility would concern a/the .outline. around elements. But the issue is NOT on a/the .outline. but on the outer box shadow to create a glow effect!

Indeed you have a little hustle in the organization of your variables:

(1) The default values in the variables mixes values of standard-buttons up with the settings of input-buttons in form elements.

and:
(2) It seems, that the settings for normal standard-buttons do not overwrite the settings for special input-buttons to create a separate effect for standard-buttons. That indicates to a little hustle in the mixins (here: organization and use of variables as well)

Please: 
This is a serious feedback!
You can check it when you try to do a variables setting for a theming with buttons without glow-effect ... (of course let the outline intact). 

If there is a solution it would be wonderful to get a/the solution.

Once more: thx for all the great work to this wonderful project at all :-)

**Comment by hy505** [comment]
@Lakro 
try this.
`$btn-active-box-shadow : none;
$btn-focus-box-shadow : none;
$btn-box-shadow:unset;
$btn-focus-width:0;
$btn-active-box-shadow: unset;`

**Comment by mdo** [comment]
The glow effect via `box-shadow` is the replacement for the `outline`, which is designed as an accessibility feature for creating consistent and cross browser friendly focus styles.

**Comment by Lakro** [comment]
@hy505

That works! Great. It really helps!
The first working hint about that special variables setting solution in web I found about it.
Thx a lot :-)

--------------

@mdo 

**Thx for your feedback once more.** 

Well. Bootstrap is a great and successful(!) framework as it makes web development easy. And for this I like it very much. Thx once more for your great work :-) 

But there is nothing which not could been improved … Styling buttons in BS seems to be a little detail which could/should be improved. 

**(1) Actual theming buttons by variables is not really intuitive** 

Several feedbacks in several issues/comments how developers understand the code/variables are indications to that. Their attempts indeed leads to hustle (means: not only my attempts!) … and the variables settings combination which leads to the solutions at the end is a little bit complicated or let’s say unexpected specific.

One point that really irritates is (and I indeed still believe it is an unwanted issue): setting in single variables are working unexpectedly. They seems to mix css output up with values taken from other variables which seems to be set in another context (see reported output in this thread above and other threads as well) … 

PLEASE: really check that. To myself it still irritates up to now from where the output comes from …

Well: button styling indeed is not the easiest task in theming at all … 

**(2) Suggestions to improve**

Make css output of variables more intuitive especially on this(!) context. 

On this(!) context: better documentation how variables work. 

Maybe an own forum for BS specific discussion could be helpful. 

Stackoverflow and reddit are good platforms, but concentrated community knowledge is not a bad idea for a framework with this relevance. I suppose that place should be 'the official slack room' which is mentioned on the introduction page? That doesn’t work (just for a long awhile) … so maybe you would like to remove that link ;-)


**(3) Not a bug: glow effect as outline indicator**

To replace outline with a glow effect indeed is a nice and welcome option for a styling. But it is not a wanted styling solution for all designs. Maybe not a wanted styling for most individual pages/project … 

So indeed it is not a bug … but the issue may lead to a wish/suggestion to make the handling of BS easier at this detail.

**On occasion: a wish for BS v5:**

Even if that is not longer possible/wanted for v4.x that could be a good suggestion for v5 ;-)

Although I believe that the actual lifetime planning for BS version is a little bit short as most webpages have a much(!) longer lifetime as your plan assumes I am looking forward to your new ideas :-)

Once more: a really big 'THANK YOU' to you and your team for you fantastic work :-) :-) :-)

**Comment by tuuling** [comment]
@mdo 
> The glow effect via `box-shadow` is the replacement for the `outline`, which is designed as an accessibility feature for creating consistent and cross browser friendly focus styles. This is not a bug.

Sure, but why then I can disable the focus via variables on form inputs? I say it is a bug - they should behave similarly.

And bootstrap should not force people to use box-shadow instead of outline. I get that there is no way to configure outline via variables currently in bootstrap, but forcing box-shadow seems _a bit too much_.

You have no problem disabling the focus shadow on form elements, but removing it from buttons is not possible? see: [button](https://github.com/twbs/bootstrap/blob/master/scss/mixins/_buttons.scss#L24) vs [forms](https://github.com/twbs/bootstrap/blob/master/scss/mixins/_forms.scss#L20)

**Comment by vichaunter** [comment]
> $btn-active-box-shadow : none;
> $btn-focus-box-shadow : none;
> $btn-box-shadow:unset;
> $btn-focus-width:0;

This worked, thankyou very much!
