### ISSUE TITLE
Order of margin and padding classes

### ISSUE THREAD

**Issue by oleg-tsalabionak** [twbs/bootstrap#29188]
Hi!

There is one strange behaviour with full classes m-*, p-* and its 'sided' version ml-*, mt-*, etc.

If I write classes "m-0 mb-1", I suggest that all margins (if they was set earlier) except bottom will be zero. And it is works. 
But in the reverse way (classes "m-1 mb-0") it doesn't. I expect, that "m-1 mb-0" will set all margins except for the bottom to non-zero, but class mb-0 does nothing.

This is because class order in the resulting bootstrap.css file is: m-0, mb-0, m-1, mb-1 etc
But I think it should be: m-0, m-1, mb-0, mb-1
I think, all 'side related' classes should be present in the bottstrap.css file after ALL common classes m-* p-*.

Now the workarond of this behaviour is simple - use only 'sided' versions of classes, but it increases the size of the final HTML code.

**Comment by mdo** [comment]
@MartijnCuppens I believe we've been asked this before? Something seems off on the order of these utilities perhaps. Or we might need to document the order and it's reasoning?

**Comment by MartijnCuppens** [comment]
We fixed this when our utility API was introduced, see:
https://codepen.io/MartijnCuppens/pen/RXLQbJ
and
https://codepen.io/MartijnCuppens/pen/mNBXdj

Changing this `v4` will be a breaking change, since this might affect existing implementations.
