### ISSUE TITLE
EOL on Bootstrap 3 and 4

### ISSUE THREAD

**Issue by babatundeko** [twbs/bootstrap#29184]
My NHLBI organization is using Bootstrap 3 and 4 on several internal application. I learned that the Bootstrap just announced last week that EOL on Bootstrap 3 was last month (July) and Bootstrap 4 will be on February 2020. How can we have time to migrate to Bootstrap 5 if you announced in short timeframe? Plus, the Bootstrap 5 is not available for us to review, analyze, test, develop, and prepare for the transition phase. Bootstrap 4 should not declare EOL date until Bootstrap 5 is entirely built and ready to use. What is your thought on this? Is there a way you can change the EOL date?

**Comment by midzer** [comment]
I think table in https://github.com/twbs/release and latest announcement in blog https://blog.getbootstrap.com/2019/07/24/lts-plan/ don't properly match to each other.

In blog:
`Bootstrap 4 will move to Long Term Support after we release v4.4`

while in the table
`Active LTS Start` is `2019-02-14`

So, `Active LTS Start` should be set when `v4.4` is released (and of course `Maintenance LTS Start` + `End-of-life` accordingly)

**Comment by XhmikosR** [comment]
Yeah, v4 date will be adapted after we release 4.4.0.

**Comment by XhmikosR** [comment]
For v3, we just don't have the manpower to keep supporting it. It's been so old already. I mean, I even have to look up the docs for the CSS classes myself. :P

**Comment by midzer** [comment]
Meanwhile we could fix those v4 dates in release repo to not generate more confusion.

Would be happy to open up a PR :)

cc @bardiharborow

**Comment by XhmikosR** [comment]
Yeah I've already pinged Bardi on slack

**Comment by bardiharborow** [comment]
@babatundeko @midzer our apologies, there was an oversight internally regarding the existence of pending 4.4 changes when we released this all and we're playing catch up (a prime example of why a release plan is needed and why it will be very valuable once it's settled). I've tweaked the release repo and we'll be working on getting things running smoothing soon. I'm available on Slack for anyone who wants to discuss our project direction or needs any advice.

**Comment by babatundeko** [comment]
@bardiharborow  Can Bootstrap 4.x remain as Active LTS or Maintenance LTS with no EOL date until Bootstrap 5.x land on Active LTS? I can hold off the preparation for migration to Bootstrap 5.x due to enterprise policy on EOL.  It will allow our UIUX team to review all components, elements, etc. until BS 5.x tools fully developed and ready to use. It will give us enough time to communicate with many product development teams to process the migration in their timeline. Often, many organization has limited resources to upgrade the front-end framework in a short amount of time. For instance, EOL on BS 4.x is in 6 months (Feb 2020).  If not possible to halt the EOL, could you at least postpone the EOL date for extra one year?

**Comment by midzer** [comment]
@babatundeko New dates have been fixed, check https://github.com/twbs/release

**Comment by jstoppa** [comment]
thanks for awesome work with boostrap 
@midzer is the EOL support for Boostrap 4 still at the end of this year (2020-11-26)? Do you know when Boostrap 5 is expected to be officially released?

**Comment by midzer** [comment]
@jstoppa New dates have just been updated https://github.com/twbs/release
According to v5 blog post https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/ there are several alpha versions to come before an official release

**Comment by babatundeko** [comment]
@jstoppa As I worked on getting several internal applications to upgrade from Bootstrap 3 to 4 due to EOL on 3, I learned that 4 have an EOL date, which is Jan 2022, and there are no 5 (not beta) available to use. From a security and enterprise perspective, EOL on current group 4 versions shouldn't announce EOL date like around the corner until group 5 version has maturing versions file available with either on Active LTS Start or Maintenance LTS Start status. Many organization recognizes EOL as a high-security risk, and we need to allow us to have time to proceed the upgrade phase from 4 to 5 without complexities. How can we upgrade when the resource is not available and protect ourselves at the same time? Does that sound rational? Please tag someone who should address this matter. Thanks!

**Comment by midzer** [comment]
@babatundeko I agree that v4 EOL date (2022-01-01) is maybe too early. But I don't know how long bootstrap team wants to keep maintaining it. In any case, EOL does not mean it's broken or something. If there are security issues they will get fixed. This happenend for v3 as well.

How do others see this? cc @XhmikosR @bardiharborow

**Comment by XhmikosR** [comment]
The dates are all subject to change. We are on March 2021 and v5 hasn't hit stable. The dates are probably off and will need to be adapted.
