### ISSUE TITLE
Unexpected value 3rem parsing width/height attribute.

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29190]
It seems on master docs we get this kind of warnings on Firefox:

```
Unexpected value 3rem parsing height attribute.
```

Maybe we should move this in CSS?

See also https://stackoverflow.com/a/46337386

/CC @mdo @MartijnCuppens

**Comment by Hardik500** [comment]
Could you provide the code?

**Comment by DhiaDjobbi** [comment]
Change `3rem `to `48px `.
