### ISSUE TITLE
Bootstrap 4 Carousel First Slide Data-Interval Not Working With YouTube

### ISSUE THREAD

**Issue by wilecoyte78** [twbs/bootstrap#29200]
This may be a bug. 

I load a YouTube Video on the first slide using JavaScript and the data-interval is set to 269000 milliseconds but it only stays on the slide for 5000 milliseconds

If I place the  data-interval="269000" on the Div tag with class carousel the first slide works as expected

https://codepen.io/wilecoyte78/pen/dxVQOE

**Comment by Johann-S** [comment]
Hi @wilecoyte78,

To achieve that, you have to set the global carousel interval to: `269000` and override that interval in each of your slide

See: https://codepen.io/Johann-S/pen/jgGjrm
