### ISSUE TITLE
Bad behaviour when clicking on custom forms checkboxes while holding shift key

### ISSUE THREAD

**Issue by QuentinChampeau** [twbs/bootstrap#29206]
[Custom forms checkboxes](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes) does not behave like classic
checkboxes when they are clicked while holding shift key.

Scenario: 
1. Click a checkbox
2. Click a second checkbox while holding shift key

**Normal behaviour** on simple checkboxes: both checkboxes are clicked.

1. ![Normal behaviour1](https://user-images.githubusercontent.com/20285621/62380123-d0640780-b548-11e9-8540-3fbf29a4d75e.png)
2. ![Normal behaviour2](https://user-images.githubusercontent.com/20285621/62380162-e96cb880-b548-11e9-82da-819cf7b8213d.png)

**Bad behaviour on custom forms checkboxes**: the first checkbox is checked, the other one is not and the text in between
is highlight.

1. ![First checkbox clicked/ticked](https://user-images.githubusercontent.com/20285621/62378330-de178e00-b544-11e9-941a-6fa440cf5c9b.png)
2. ![Bad behaviour when clicking the third checkbox while holding the shift key](https://user-images.githubusercontent.com/20285621/62377270-bf17fc80-b542-11e9-9516-c88d6a9726de.png)

[Link to my gist](https://gist.github.com/QuentinChampeau/2b20acbe5abf8b1f0682d1a9b4dc75de)

- Browser tested
    * Chrome 76
    * IE 11
    * Microsoft Edge 44

ps: if the checkboxes are double clicked (while still holding shift key) then they are normally checked.

**Comment by ysds** [comment]
This behavior is related to #26473, won't fix for v4 but already fixed in v5.

v5 demo: https://codepen.io/anon/pen/GVOLMm
