### ISSUE TITLE
docs broken form examples

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29204]
It seems we still have a fewbroken form examples

* the second one in https://twbs-bootstrap.netlify.com/docs/4.3/forms/layout/#auto-sizing
* a few more here https://twbs-bootstrap.netlify.com/docs/4.3/forms/validation/. Basically where `input-group-prepend` is used

**Comment by XhmikosR** [comment]
Some more details, this seems to happen only on Firefox (68.0.1)

![2019-08-05_17-45-44](https://user-images.githubusercontent.com/349621/62473456-744bee00-b7a9-11e9-8b5e-42043d51327a.png)

![2019-08-05_17-46-25](https://user-images.githubusercontent.com/349621/62473457-744bee00-b7a9-11e9-8d0f-402171044a88.png)

**Comment by ysds** [comment]
This must be related https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size
