### ISSUE TITLE
No documentation on bd-callout - (recurring issue)

### ISSUE THREAD

**Issue by viktorsmari** [twbs/bootstrap#29207]
As a heavy user of Bootstrap, I think it is **confusing** that the documentation is using `bd-callout` - something that is not offered with Bootstrap.

The callouts are beautiful, and they would be a very nice addition to Bootstrap.

I think we should either:
* Not use them at all in the Documentation.
* Offer them with Bootstrap, or document how to add them _unofficially_. 

I browse the documentation regularly to get new ideas on things to use. I suspect other users to the same. I spent time researching how to add them or if this was simply missing in the docs, and I think I did the same ~2 years ago. I also suspect other users have had the same issue.

**The debate:**
Would it not be confusing to users, if the documentation would start using multiple things that are not possible with Bootstrap?

After looking at the other issues, it is still not clear to my why it was not possible to include it.

Related: #18723 #9938 #8296

**Comment by mdo** [comment]
There's a lot we use in the docs that is not included in Bootstrap. No changes here, they'll stay as docs only. We have alerts in Bootstrap proper and they'd be duplicative of the same function.
