### ISSUE TITLE
Top, bottom placement for tooltips results in an ugly hover, un-hover loop

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#29211]
When tooltips are placed on top or on bottom of elements, then they cycle on and off and on and off forever, as a result of interacting with the z-axis of the cursor. Really, tooltips should remain on screen until the cursor's 2-dimensional (x, y) coordinate leaves the tooltip's underlying DOM element hitbox.

**Comment by Johann-S** [comment]
Hi @mcandre we use Popper.js for the positionning of our Tooltip, so feel free to open an issue here: https://github.com/FezVrasta/popper.js/issues
