### ISSUE TITLE
Tooltip position doesn't take Bootstrap h1, h2, h3, ... classes into account

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#29213]
Tooltip position is artificially lower and to the left of where it should be, when placing tooltips on .h1, .h2, .h3, etc. Bootstrap class elements.

**Comment by Johann-S** [comment]
Hi @mcandre for the positioning issue feel free to open an issue on Popper.js Github: https://github.com/FezVrasta/popper.js/issues and you should definitly add a live example for each of your issues

**Comment by mcandre** [comment]
Ah, I think I found the root cause. When the tooltip element surrounds a Bootstrap modal button and its underlying form, then poor XHTML, such as the example `<span>`s inside of the Close 
modal buttons, can confuse the rendering engine. This sometimes leads to tooltips being off-center from the modal toggle button.
