### ISSUE TITLE
position auto always puts tooltips on the bottom

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#29212]
I expect position auto to place tooltips on the opposite side of the DOM element where my cursor entered the hitbox, so that it is easiest to see the tooltip. Instead, auto always places tooltips on the bottom.

**Comment by Johann-S** [comment]
Again @mcandre we use Popper.js for the positioning so feel free to open an issue here: https://github.com/FezVrasta/popper.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc 😉
