### ISSUE TITLE
Tippy tooltips integrate better with Bootstrap than Bootstrap tooltips

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#29220]
Maybe Bootstrap should adopt Tippy tooltips, which integrate better with Bootstrap components such as modals, than Bootstrap tooltips! Tippy is also based on Popper, but resolves a lot of kinks around delay timers.

https://atomiks.github.io/tippyjs/customizing-tooltips/

**Comment by mdo** [comment]
Thoughts from @Johann-S and @patrickhlauke on this one?

**Comment by patrickhlauke** [comment]
at a very high level/quick test, these seem to be ok ... at least the docs say the right things about accessibility, for the most part

**Comment by XhmikosR** [comment]
Closing as the issue is too vague.
