### ISSUE TITLE
XHTML5 Support

### ISSUE THREAD

**Issue by fsologureng** [twbs/bootstrap#29235]
Hi, 
   I'm trying to make to work _scrollspy_ of bootstrap over a xhtml5 page, but _active_ classes over the links doesn't work.
   I created an example of [HTML5 with the functionality working correctly](https://pillan.newtenberg.com/~fsologuren/bootstrap/landing.html) and an example of [XHTML5 with the functionality that isn't working properly](https://pillan.newtenberg.com/~fsologuren/bootstrap/landing.xhtml).
   Diving in the code and following [a comment in a popper's issue](https://github.com/FezVrasta/popper.js/issues/575#issue-302531282) , I realized that the problem is in the treatment of response of nodeName and tagName.
   Changing the code adding _toUpperCase()_ in [line 79 of scrollspy.js](https://github.com/fsologureng/bootstrap/blob/e0b5b832d1bc2580f2ae255818500526aab596e6/js/src/scrollspy/scrollspy.js#L79), the functionality goes fixed.
   With this change (and all others I detect of the same type), there are a [well working example](https://pillan.newtenberg.com/~fsologuren/bootstrap/landing_ok.xhtml).

Can I make a pull request to add all those changes to the repository?

**Comment by mdo** [comment]
No plans to make XHTML work for Bootstrap at this time. Similar to the referenced issue, this is the first time it's been ask I believe. I don't have any concrete examples of why XHTML is needed over HTML, so feels weird to try to bake that in.

**Comment by fsologureng** [comment]
One example of use of XHTML is that is possible to apply XSLT transformations into browser side, as DSPACE do today.

Necessity of XHTML is part of my bussiness and JQuery supports it, so I don't understand your reasons to not do it, too; The changes are minimal and inoffensives, and I haven't found more issues than this.

At least you could especify explicitly that boostrap don't support XHTML, because is not mentioned anywhere into documentation nor is a requirement. HTML5 is not just SGML.

Thank you.

**Comment by Felistrix** [comment]
I have spend several hours to find out, why my bootstrap dropdown won't work and found this reason; XHTML and HTML.

> Similar to the referenced issue, this is the first time it's been ask I believe.

Then this will be the second time.

> I don't have any concrete examples of why XHTML is needed over HTML

At least my intention is not to put XHTML **over** HTML, _just_ XMTL **besides** HTML. The script will not stop working on HTML-pages; that would be a "putting over".

> so feels weird to try to bake that in.

Sorry, but for me it sounds weird not to do so. HTML is a very, very loose standard.

HTML says &lt;html&gt; is valid code and &lt;HTML&gt; is valid code; even &lt;Html&gt;, &lt;HtMl&gt;, &lt;HtmL&gt; - all valid code. Even any combination for opening and closing tag, like &lt;HtmL&gt;&lt;/hTMl&gt; is valid code. XHTML is a strict standard, which is case sensitive and differences them.

Now is your argumentation, you want to be compatible with the "everything is correct" standard, that need to convert all tags in uppercase, just to make it possible to handle it and you are using strict comparsion (=== and !==) for it but don't want to be compatible with the XHTML standard, which is strict by itself?

So I can just repeat fsologureng:
> and JQuery supports it, so I don't understand your reasons to not do it, too

**Comment by Felistrix** [comment]
Just to inform the participants of this issue: I think my answer have not been seen, because this issue is closed. In fact of there is now more than just one, who ask for it (as said in the answer for closing the issue) I have tried to get new attiontion to this topic by opening a new request.

https://github.com/twbs/bootstrap/issues/30705
