### ISSUE TITLE
Add loading=lazy to images on docs

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#29242]
Native lazy loading of images is available now in Chrome - it works great and can improve page load performance by only loading images in the viewport. There aren't a huge number of images in the Bootstrap Docs but I'd like to see `loading=lazy` added to the ones that are there.

REF:
- https://web.dev/native-lazy-loading/
- https://addyosmani.com/blog/lazy-loading/

**Comment by XhmikosR** [comment]
Unless the specs allow this, I'm against it personally.

Also, we don't really have that many images. The old docs are the old docs and will remain untouched.

**Comment by MartijnCuppens** [comment]
> Unless the specs allow this, I'm against it personally.

I agree.

**Comment by coliff** [comment]
No problem. I think this is a great feature - hopefully it'll become a standard, gain more browser support and then we can reconsider. :-)
