### ISSUE TITLE
input-group-prepend / append and d-none

### ISSUE THREAD

**Issue by tristenator** [twbs/bootstrap#29249]
it would be nice if adding d-none to an input-group-prepend / append would restore the rounded borders where applicable to the input element(s) contained between.

ie, exactly like if the prepend/append wasn't present at all.

currently, if d-none is present on the prepend / append then the input element(s) in between still display with squared borders. this is true for static (present @ page load) and dynamic (eg: subsequent adding of the d-none class using javascript.)

...edit: and vice versa on removal of d-none :)

best regards

**Comment by MartijnCuppens** [comment]
We can not style our components based on if utilities are added to an element in a component. I would recommend removing the element with javascript instead.

**Comment by tristenator** [comment]
yep i suspected that may be the case, no worries and thank you for your response
