### ISSUE TITLE
Docs improvment for grid system ordering

### ISSUE THREAD

**Issue by philipmountifield** [twbs/bootstrap#29248]
After looking at the example here: https://getbootstrap.com/docs/4.3/layout/grid/#order-classes

It was not at all clear why the item labelled "First, but unordered" was appearing before the item with `order-1` and the description of the item showing second "Third, but first" only made it more confusing, because it wasn't first.

After researching I found it was due to the fact that items without an explicit order in flexbox default to an order of 0.

It would be great if the docs could reflect/note this nuance.

**Comment by florianlacreuse** [comment]
FWIW, the [docs](https://getbootstrap.com/docs/4.3/layout/grid/#how-it-works) already advises to read the flexbox guide from css-tricks. In the [guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), the `order` property behavior is explained in the beginning of the page.
