### ISSUE TITLE
CSS form-row class: element size exceeds parent

### ISSUE THREAD

**Issue by trueleader** [twbs/bootstrap#29243]
A form row html element exceeds the parents form width, due to -5px left and right margin on the .form-row css class.

As example the official https://getbootstrap.com/docs/4.3/components/forms/#form-row can be used for reproduction (Firefox and Chrome tested):
- Open Browser-Tools and select the "First name" input element
- Add a background color to the parent div.col element
- Add a outline to the parent form element

Result: The background of the input container exceeds the outline of the form
I found this issue, because we have different background colors for different parts of one of our pages.

![image](https://user-images.githubusercontent.com/7026107/62882540-66aae100-bd32-11e9-8e08-645af00e1243.png)
![image](https://user-images.githubusercontent.com/7026107/62882549-6dd1ef00-bd32-11e9-8ea2-1fb355751c91.png)

**Comment by florianlacreuse** [comment]
It seems there's no issue here. BS grid works with cols using horizontal padding and cols container (parent) using negative horizontal margin to compensate cols padding on the left and right edges. Don't apply style to `col` or `col-*`, nor `.container`, `.form-row`, etc (unless you realy want to / know what you are doing).

**Comment by trueleader** [comment]
You mean: If a correct background color for a column is wanted, we must create an inner wrapper element and split the class assignments?

I tried the following which creates the desired result:
`<div class="form-row">
    <div class="col-1"><div class="bg-light"><label class="col-form-label">label 1</label></div></div>
    <div class="col-2"><input type="text" class="form-control"></div>
</div>`

But is this the way it should be done?
If yes, I have to create another ticket at bootstrap-vue, which creates another structure

**Comment by florianlacreuse** [comment]
According to me, yes. Maybe you could wait for other opinions.

**Comment by mdo** [comment]
> Seems the WYSIWYG editor doesn´t like newline inside "Insert code"

Multi-line code blocks require three backticks at beginning and end instead of the usual one.

---

The behavior you're seeing is intentional because of the use of `padding` in our grid classes.
