### ISSUE TITLE
Carousel caption flex alignment

### ISSUE THREAD

**Issue by AndiLeni** [twbs/bootstrap#29250]
Hello,
I wanted to center the carousel caption vertically inside the carousel but I noticed the caption has an absolute position. 
Is it somehow possible to use flex with the carousel to align the caption?

Regards
Andi

**Comment by PowerMostafa** [comment]
there is a lot of ways to center the carousel caption vertically inside the carousel 
the best and easy way by using custom CSS  but if you wont to make it by bootstrap flex here is away 
but the caption inside <div class="h-100 w-100"> and try to use flex as you want

**Comment by mendozagioo** [comment]
@AndiLeni If the commit is merged, just add `caption-centered` in `carousel-caption`:
`<div class="carousel-caption caption-centered">`
Or check the commit to add it to your project

**Comment by AndiLeni** [comment]
@mendozagioo Thanks! I will keep this in mind :)

**Comment by mdo** [comment]
Closing out as stale and something that can be done via custom HTML and CSS.
