### ISSUE TITLE
master docs: fix Previous Releases empty href

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29258]
@mdo where did you mean this link to point to?

https://github.com/twbs/bootstrap/blob/6335fbe224f28d2ce65c628756a84113ea65643f/site/layouts/partials/home/masthead.html#L24

**Comment by malsf21** [comment]
Not @mdo, but I assume it's supposed to link to something like [this](https://getbootstrap.com/docs/versions/)?

**Comment by malsf21** [comment]
Not @mdo, but I assume it'd point to a list of previous docs like [this page](https://getbootstrap.com/docs/versions/), or an archive of previous releases?

**Comment by XhmikosR** [comment]
Yeah, probably, I just want to double check.
