### ISSUE TITLE
Carousel slide animation doesnt always work as intended

### ISSUE THREAD

**Issue by amshegarh** [twbs/bootstrap#29256]
Sometimes .carousel-item-right and .carousel-item-left are set with transform: translateX(0) before display:none is disabled, therefore animation (transition time) is ignored and action is instant. For some reason  it can be reproduced with any b4 carousel if any .carousel-item is selected in chrome inspector, but can occur at any time

example https://drive.google.com/file/d/1xB8stncIJZUH6Y4GU6pY376JMGd-ogmT/view

**Comment by MartijnCuppens** [comment]
Hmm, I can not reproduce this

**Comment by amshegarh** [comment]
> Hmm, I can not reproduce this
Reproduceable certainly on chromium based browsers in win7&10 and also some kind of arch linux, to do so you
1. Select carousel in inspector
2. Select any div with carousel-item class
3. Swipe back/forth until mentioned element has class 'active'
It works with any carousel with 3 slides+
It also occurs randomly while the page is loading, but we are talking about gulp+browser sync

**Comment by Johann-S** [comment]
@XhmikosR can you reproduce that on Linux ? I'm unable to reproduce it on Win10 with Chromium 76

**Comment by XhmikosR** [comment]
@Johann-S I need a codepen or something.

**Comment by MartijnCuppens** [comment]
The video looks like this example page: https://getbootstrap.com/docs/4.3/examples/carousel/

**Comment by XhmikosR** [comment]
I cannot reproduce on Linux Mint 19.2 with Chromium 76.0.3809.100 either.

**Comment by MartijnCuppens** [comment]
Closing this, since we can not reproduce this.
