### ISSUE TITLE
Grid Breakpoints for phone, tablet, notebook, desktop, tv

### ISSUE THREAD

**Issue by astrahov** [twbs/bootstrap#29261]
There are many different devices in the modern world: phones, tablets, notebooks, desktops and TVs.

I am a web programmer and I have been given the task of creating a site layout. The layout was drawn for a monitor with a resolution of 1920 × 1080, and I have a monitor in 1440 × 812 (MacBook Pro). And the difference of 500 pixels (1920-1440) prevents us from making the layout of the site normally. I wanted more control points for more flexible settings.

If you do not add custom control points, then 2 options remain:
- The designer can fit the content in 1140 pixels ($ container-max-widths), despite the fact that the monitor resolution: 1920 pixels ...
- On the notebook display content as for a tablet ...

I propose to supplement the table of breakpoints:

$grid-breakpoints: (

// Mobile
 xs: 0, // for Phone portrait and up
 sm: 576px, // for Phone landscape and up
 md: 768px, // for Tablet portrait and up
 lg: 992px, // for Tablet landscape and up

// Desktop
 xl: 1200px,  // for Notebook and up
 hd: 1500px,  // for Desktop and up
 tv: 2000px,  // for TV and up

) !default;

**Comment by XhmikosR** [comment]
You can already customize the breakpoints.

/CC @MartijnCuppens

**Comment by MartijnCuppens** [comment]
Yup, you already can customize this now. Adding more breakpoints by default won't be worth the additional file size.
