### ISSUE TITLE
Contextual table classes apply tr class instead of td class to individual cells

### ISSUE THREAD

**Issue by kjsalexander** [twbs/bootstrap#29290]
Windows 10.0.17763 Build 17763
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
JSBin of the problem: https://output.jsbin.com/zoqonukaru/
Using Bootstrap 4.3.1

When using Contextual Classes (such as table-warning, table-success) on Bootstrap tables, the class on the `tr` element applies to the entire row as expected, but placing an additional class on one of the `td` elements does not apply the new color - it continues to have the color from the `tr` element. I would expect the `td` element's class and color to take precedence over the parent `td` element's class and color.

I'm not sure where the fix would go to be properly compiled from a `.scss` file into the dist `.css` file, but adding `tr > td ~ .table-danger` to the dist `.css` file seems to make the cell-specific coloring work as intended. This fix doesn't apply to single cell rows, but you wouldn't need to color a single cell differently from the row color if your row is a single cell in the first place, so it's hopefully a moot point.

The fix (in compiled css file, so only a little useful):
`bootstrap/dist/css/bootstrap.css` line 1681
```
.table-danger,
.table-danger > th,
.table-danger > td {
  background-color: #f5c6cb;
}
```
to
```
.table-danger,
.table-danger > th,
.table-danger > td,
tr > td ~ .table-danger {
  background-color: #f5c6cb;
}
```

**Comment by mendozagioo** [comment]
@kjsalexander yes, it's a moot point. To me is not an issue, because the documentation say that you can applly a contextual class on table OR row OR cell, but don't describe that you can apply a contextual class over another contextual class, if not, the code could be diferent, more simple, something like:
````
.table-danger {
  background-color: #f5c6cb;
}
````
instead of:
````
.table-danger,
.table-danger > th,
.table-danger > td {
  background-color: #f5c6cb;
}
````
What do you think about this @MartijnCuppens ?

**Comment by mdo** [comment]
@mendozagioo has it right—this is coming in #30342 where I'm redoing some table styles and improving documentation.

**Comment by timhunt** [comment]
Really glad this is being fixed for v5. Does anyone have a suggested work-around fo v4.x? Thanks.
