### ISSUE TITLE
Add a .uncontainer utility function

### ISSUE THREAD

**Issue by augnustin** [twbs/bootstrap#29295]
So I have had [this issue](https://stackoverflow.com/questions/57612222/boostrap-background-image-in-a-container-at-the-very-left-of-the-screen/57614157), where I need a `div` to be full-width within a `.container` class that is in the layout so I don't want to break it.

With other SO contributors, I was able to write a solution that does this and called it `.uncontainer` so that we get :

```
body
  .container
    .row
    .uncontainer // this is full width
 ```

I wanted it to be clean, reusing bootstrap variables, so I went for:

```
@import '~bootstrap/scss/functions', '~bootstrap/scss/variables';

@mixin make-uncontainer-responsive($max-widths: $container-max-widths, $breakpoints: $grid-breakpoints) {
  @each $breakpoint, $container-max-width in $max-widths {
    @include media-breakpoint-up($breakpoint, $breakpoints) {
      // Still hesitating with two other attribute : margin-left and translateX;
      // Anyone has an opinion on this?
      left: calc((#{$container-max-width} - 100vw)/2);
    }
  }
}

.container {
  position: relative;
  .uncontainer {
    position: absolute;
    width: 100vw;
    @include make-uncontainer-responsive();
  }
}
```

How about making this a utility class available by default?

**Comment by morrissey-ingenious** [comment]
I personally don't like this approach. If you need something outside of a container that's where it should be, or you can use other already available classes to accomplish what you need.

Can you provide a CodePen or JSFiddle example.  I want to see why it would be needed and if it can be accomplished another way.

**Comment by MartijnCuppens** [comment]
You should just change your markup and go for a solution like this:

```
body
  .container
    .row
  div // this is full width
```

I've also experimented with this technique in the past but the fact is it's quite hard to provide a solid solution. Just changing the markup is the way to go.

**Comment by augnustin** [comment]
Hi,

Thanks for getting back. I wish discussion could have gone further before immediate closing but fine. 

I am very aware that the simplest/cleanest solution is to move the `div` out of the `.container`. 

But in my case, (and this has happened to me several times, hence the desire to find a reusable solution, and I am sure I am not the only one), more or less everything in my website is within the `.container`, which logically is in my layout file.

But for a specific landing page, there are background images that are within the content, but stuck to the very left of the screen. Doing what you guys suggest means the following:

1. Adding a `noContainer` variable to the layout that defaults to false, which means writing :

```
render("my-fancy-landing.html", {
  noContainer: true
});
```

2. Editing `layout.html` to:

```
.body
  = "navbar.html"
  #content{class: noContainer ? '' : 'container'}
    = yield
  = "footer.html"
```

3. In `my-fancy-landing.html`, repeating: 

```
.container
  // Beginning of my content
div{style: "background-image: url('image/left.jpg'); background-position: left;"}
  .container
    // more content
.container
  // other content
div{style: "background-image: url('image/right.jpg'); background-position: right;"}
  .container
    // more content
```

I find this to be:
- a lot of work/code rewrite
- quite inelegant, nor DRY`
- bad separation of concern: besides decoration, it makes perfect sense to have the `.container` within the layout
- not responsive

which means many flaws only for a background image.

I wish there was a CSS-only solution, but for now, the only solution I found is this hacky one.

Hope I was clear and this eventually will speak to some readers.

Best
