### ISSUE TITLE
Use jsDelivr as recommended CDN for all files in docs

### ISSUE THREAD

**Issue by Veratyr** [twbs/bootstrap#29301]
It would be better to use jsDelivr for all files (BS, jQ, Popper) in docs instead of 3 different CDNs.

1. jsDelivr has better availability all around the world, than any of currently referenced CDNs.
It's fast, no matter where user is. Can't say the same about bootstrapcdn.com and jquery.com
2. Using of one CDN instead of 3 will decrease DNS requests, what also will improve the speed for end-users.

Related links:

- https://www.jsdelivr.com/network
- https://www.cdnperf.com/

**Comment by XhmikosR** [comment]
Thanks for the suggestion, but:

1. jQuery is gone in v5
2. You can already use our bundle file, which includes Popper.js

I should create a patch which will suggest the bundle file instead of 2 files, because we don't expose this enough.
