### ISSUE TITLE
Feature request: Table column-only bordering

### ISSUE THREAD

**Issue by blunket** [twbs/bootstrap#29303]
In HTML there used to be a `rules` attribute for tables, where one would write `rows`, `cols`, `none` and it would change the border styling. I would like a feature in Bootstrap where one could emulate how the `rules="cols"` attribute used to work.

I see that #13515 is closed but might be *somewhat* related to this idea.

My example usage for this would be a tiered pricing table.

Here's a quick thing I made with just `.table-bordered`:
![image](https://user-images.githubusercontent.com/17580512/63641174-7948e280-c66f-11e9-907f-d46effdd9c95.png)

But I think it looks nicer with just column rules:

![image](https://user-images.githubusercontent.com/17580512/63641165-528aac00-c66f-11e9-94a2-61181c41c795.png)

Would something like this be considered? Or is there some reason not to include it that I'm unaware of?

Currently one can accomplish this by using `.border-left` on a lot of elements or just using custom CSS, which is what I've done in the screenshot above. I'd love to make a pull request to implement this myself in Bootstrap if the idea is approved.

**Comment by mdo** [comment]
If you’re using a built in Bootstrap `.table`, you’ll need to remove the vertical `border`s, and then reset the horizontal ones. You could use sibling selectors `td + td`, remove the `border-left` on the `:first-child`, etc.

The `rules` attribute isn’t in HTML5 (I didn’t even know it was a thing until now). I don’t see us adding helper or modifier classes for this just yet, but if there’s enough feedback we could explore it.
