### ISSUE TITLE
we are not able to use hex code directly with class instead of very few colors like info, dark, primary etc. 

### ISSUE THREAD

**Issue by pedestrian1119** [twbs/bootstrap#29307]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by patrickhlauke** [comment]
that's not how classes work...and no, we don't plan on creating classes that reflect every single possible hex code. at that stage, you need to make your own stylesheets i'd say.
