### ISSUE TITLE
List group with transparent background in card - wrong border color.

### ISSUE THREAD

**Issue by florianlacreuse** [twbs/bootstrap#29318]
In #26711, it states that we can use `.bg-transparent` on each `.list-group-item` to override the default white background.

I'm ok with this solution but in this case the borders of the list group are darker, and not the same as the borders of the card, because of the `rgba` in the `border-color` property. Having darker borders for a sub elements seems weird.

Reduced test case to show the issue : https://codepen.io/florianlacreuse/pen/BaBZyzK

**Comment by ysds** [comment]
Why not use the `.bg-primary` instead of the `.bg-transparent`?

**Comment by florianlacreuse** [comment]
Thanks for your reply.

It would do the trick just for few cases but I use `.bg-*` utilities for the cards just for the example, it could be [any color](https://codepen.io/florianlacreuse/pen/XWrYBQE).

But may be there is a good reason for `list-group` to have a white background? FWIT, `.table` has a transparent background, for comparison / example.

**Comment by mendozagioo** [comment]
@florianlacreuse just use: `.border-primary` for each `.list-group-item` to you specific case:
````
<ul class="list-group list-group-flush">
  <li class="list-group-item border-primary">Cras justo odio</li>
  <li class="list-group-item border-primary">Dapibus ac facilisis in</li>
  <li class="list-group-item border-primary">Vestibulum at eros</li>
</ul>
````
`.bg-<variants>` just change card background, not list-group's border.
To me, this is not a issue

**Comment by florianlacreuse** [comment]
And what if, as I said in my previous message, the background isn't a BS color theme? Anyways, IMHO, it doesn't seem convenient.

**Comment by mendozagioo** [comment]
The same thing. To me, the proper way to solve this problem is create cards variants and list-group variants

**Comment by mdo** [comment]
Leaving this as-is and not implementing card and list-group variants at this time. We're moving towards more interoperability with utilities and our components.
