### ISSUE TITLE
Dropdown inside Table Responsive in Safari of iOS 12.4

### ISSUE THREAD

**Issue by rodrigopedra** [twbs/bootstrap#29313]
When using dropdowns inside scrollable elements, such as table-responsive, there is an option to set the dropdown's boundary to the viewport, this way the dropdown is not clipped by the scrollable parent overflow.

It works great, I use it and works fine in many browser. However it is not working on Safari for iPhone. Even with the boundary set to the viewport, the dropdown gets clipped inside the table-responsive element.

The iPhone I tested against is an IPhone 8 using iOS 12.4. 

I also tested against an iPad Pro (10") using iPadOS 13 Beta. In this device everything works as expected.

I do not have access to a machine with macOS, therefore I cannot tell if this problem happens in the desktop version of Safari. I tried with Gnome/Web (Epiphany) which uses WebKit and it works as expected on desktop. In all other browsers I tested it worked as expected (Firefox, Chrome, both on Desktop)

The reduced test case is the following:

~~~html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Demonstration</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container my-5">
    <div class="table-responsive">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>Lorem ipsum dolor.</td>
                    <td>Laboriosam, optio, ratione.</td>
                    <td>Consequatur dolorum, quisquam.</td>
                    <td>Accusamus in, quaerat!</td>
                    <td>Ducimus excepturi, inventore.</td>
                    <td class="text-right">
                        <div class="dropdown d-inline-block">
                            <button
                                type="button"
                                class="btn btn-outline-secondary"
                                data-boundary="viewport"
                                data-toggle="dropdown">
                                Toggle
                            </button>

                            <div class="dropdown-menu dropdown-menu-right">
                                <button type="button" class="dropdown-item">
                                    Option 1
                                </button>
                                <button type="button" class="dropdown-item">
                                    Option 2
                                </button>
                                <button type="button" class="dropdown-item">
                                    Option 3
                                </button>
                                <button type="button" class="dropdown-item">
                                    Option 4
                                </button>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

</body>
</html>
~~~

I also created a Code Pen with the same code, the error only happens on Safari for iPhone:

https://codepen.io/rodrigopedra/pen/gOYWQPZ

As it is difficult to me to debug this code on Safari for iOS (because there is no Mac around) I could not dive into the problem to make a suggested fix.

I searched for previous issues regarding this same problem and I found these closed issues:

#11037 / #15288 / #15374  / #24251

In any of them there were mentions to this behavior happening only on Safari for iPhone.

It was not very clear (to me at least, not a native English speaker) in the issue template if I should have added a comment on a closed issue or open a new one. As I think it is a different problem I opened a new one. Sorry if I misunderstood something.

**EDIT** Just tested on my son's iPad Air 2 which is also running iOS 12.4 and it also does not work as expected. I updated he issue's title to reflect that

**Comment by Johann-S** [comment]
It seems it's a positioning issue so maybe @FezVrasta can help us here

**Comment by FezVrasta** [comment]
If you could please prepare an example using only Popper.js and not any of the Bootstrap code I'll be happy to give it a look next week after I come back from my vacation 🌴

**Comment by TheSharpieOne** [comment]
I don't think this is limited to Safari since I am seeing something similar in Chrome.
Check out: https://codepen.io/TheSharpieOne/pen/WNNjjvb (the first table is not responsive (for comparison), the second is responsive.)

![dropdown-in-responsive-table](https://user-images.githubusercontent.com/664714/67498900-3646c380-f64e-11e9-8bba-01d27bbf5e28.gif)

**Comment by tmorehouse** [comment]
Try adding `position-static` class to the `table-responsive` element.

**Comment by dmitry-rychkov** [comment]
I had the same issue. Only on iOS/iPadOS any dropdown or other Popper.js element got clipped by `.table-responsive`

The reason is _not_ `overflow-x: auto;`
The real reason is `-webkit-overflow-scrolling: touch;` which enforces smooth touch scrolling. This property is iOS-specific only, no other browser supports it.

**Quick fix for dropdowns:**
`.table-responsive { -webkit-overflow-scrolling: auto; }`

The downside is that horizontal scrolling of table is not smooth. It may have sense to override this property only when some dropdown is shown. But it doesn't seem possible via pure CSS, only JS solution.

Works on latest iOS 12 and 13.3 for me. iPhone 5S and 11.

**Comment by linlovefon** [comment]
> I had the same issue. Only on iOS/iPadOS any dropdown or other Popper.js element got clipped by `.table-responsive`
> 
> The reason is _not_ `overflow-x: auto;`
> The real reason is `-webkit-overflow-scrolling: touch;` which enforces smooth touch scrolling. This property is iOS-specific only, no other browser supports it.
> 
> **Quick fix for dropdowns:**
> `.table-responsive { -webkit-overflow-scrolling: auto; }`
> 
> The downside is that horizontal scrolling of table is not smooth. It may have sense to override this property only when some dropdown is shown. But it doesn't seem possible via pure CSS, only JS solution.
> 
> Works on latest iOS 12 and 13.3 for me. iPhone 5S and 11.

You're a lifesaver!! THANK YOU!!

**Comment by XhmikosR** [comment]
@twbs/css-review is this something we can fix in core?

**Comment by mdo** [comment]
Late to this, but I don't believe we can fix without introducing other issues. We've long known that tables with `overflow` cause these issues. Adding `data-display="static"` to the `.dropdown` fixes the positioning glitch, but not the cut off styling from `overflow`. Setting `data-boundary="window"` fixes it I think.

See https://codepen.io/emdeoh/pen/qBaJWME.

**Comment by aimeos** [comment]
In Bootstrap 5 beta `data-boundary="window"` doesn't work, even no `data-bs-boundary="window"`. How is it supposed to work there?

**Comment by alpadev** [comment]
> In Bootstrap 5 beta `data-boundary="window"` doesn't work, even no `data-bs-boundary="window"`. How is it supposed to work there?

The example, updated to use v5: https://codepen.io/-alpa-/pen/YzZrGQg

**Comment by heyjoe1984** [comment]
Just add the `position-static` class to the `dropdown` container.

**Comment by totoprayogo1916** [comment]
> The example, updated to use v5: https://codepen.io/-alpa-/pen/YzZrGQg

example havent close tag `</div>` for `.table-responsive`
![image](https://user-images.githubusercontent.com/2387514/151789936-9507514c-260e-4321-b6ce-0ae505af250a.png)

after added `</div>`, Not working the 2nd example
![image](https://user-images.githubusercontent.com/2387514/151790043-70fb3b79-79c0-4467-ac0c-dc5eb373efbc.png)

**Comment by SoftCircuits** [comment]
> after added </div>, Not working the 2nd example

Yep, this is still the case. Looks like we can't get the issue addressed though.
