### ISSUE TITLE
Docs - Word break

### ISSUE THREAD

**Issue by Oreoz** [twbs/bootstrap#29319]
I was trying to apply the `text-break` class in order to wrap text. Everything was working fine in Chrome. But once I moved over to IE and Edge, things were all over the place. I then visited the docs site and saw that even the docs site doesn't exhibit the intended behavior.

![image](https://user-images.githubusercontent.com/3945623/63880198-4bc7a600-c99b-11e9-8d42-8dd034fc5eef.png)

**Mandatory Information:**
Windows 10 Version 1709 / 16299.1331
Internet Explorer v. 11.1331.16299.0 / 11.0.140 (KB4511872)
Microsoft Edge 41.16299.1004.0 / Microsoft EdgeHTML 16.16299

**Comment by florianlacreuse** [comment]
I think we should add the historical property `word-wrap: break-word` (originally a IE-only feature) to be IE10 and old Edge compliant. However, with the latest browsers we need to use `overflow-wrap`, as a new standard in CSS specs. We need both of them.

On a side note, as explained in [this article](https://css-tricks.com/almanac/properties/o/overflow-wrap/#similarities-to-the-word-break-property), `word-break` specifies soft wrap opportunities between letters commonly associated with languages like Chinese, Japanese, and Korean (CJK). We can keep it, won't hurts.

I will do a PR tomorrow if no one did one before.

**Comment by florianlacreuse** [comment]
@Oreoz See PR #29325.
