### ISSUE TITLE
Review v5 browsers

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29314]
Our current browserslist config includes support for opera mini, which we do not support. We need to exclude that somehow or review our current approach.

We also need to update our https://twbs-bootstrap.netlify.com/docs/4.3/getting-started/browsers-devices/ page.

**Comment by XhmikosR** [comment]
Things work sort of OK on Opera Mini, I'd rather not exclude it intentionally.

Note that this isn't the same case as IE. Many people use Opera Mini in places with bad internet.

**Comment by MartijnCuppens** [comment]
Opera mini doesn't support `calc()`, `vw` (and other viewport units), `box-shadow`, gradients, `border-radius` ect. That's a problem if we need to find solutions for these properties/values in our css.

We 'll need to check what the effect of having it in our `.browserslist` file is exactly, but if it increases our file size too much, I rather drop it

**Comment by XhmikosR** [comment]
You are welcome to look into it, I doubt it's a lot, and I'd rather have a little overhead due to this for the less fortunate people.

See my comment [here](https://github.com/twbs/bootstrap/pull/28317#issuecomment-465460572)

**Comment by mdo** [comment]
Referenced PRs are all merged, seems safe to close.
