### ISSUE TITLE
Provide SASS variables for Carousel Indicators

### ISSUE THREAD

**Issue by jahaganiev** [twbs/bootstrap#29332]
Hey folks, 

Currently, carousel indicators comes with `opacity: .5;` in _carousel.scss file (on line ~173). It could be great to have a variables for it inside `_variables.scss` file.

![image](https://user-images.githubusercontent.com/5040828/63940155-7d279b00-ca9b-11e9-9c3a-ce451a61ff6e.png)

Thanks.

**Comment by MartijnCuppens** [comment]
There's currently an open PR for carousel improvements: https://github.com/twbs/bootstrap/pull/28266

**Comment by jahaganiev** [comment]
Thanks for letting us know. Great!
