### ISSUE TITLE
docs breadcrumb tweaks

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29336]
First of all, I think we should move `icons/booticon-chevron-right.svg` to Sass.

Secondly, I think we should properly implement breadcrumbs.

Thirdly, right now we don't follow our own [accessibility guidelines](https://twbs-bootstrap.netlify.com/docs/4.3/components/breadcrumb/#accessibility)

About the second part, I'll see what I can do with Hugo.

**Comment by mdo** [comment]
> Secondly, I think we should properly implement breadcrumbs.

What's that mean?

**Comment by XhmikosR** [comment]
Currently the current page or its parent isn't listed. And the version
toggler just links to the docs index page. I'm not sure it should be there.
It makes me expect that when I click on it it'll take me to the same page's
other version.

That whole thing needs rework IMO
