### ISSUE TITLE
add `bg-body` class

### ISSUE THREAD

**Issue by skeets23** [twbs/bootstrap#29355]
`text-body` exists, but `bg-body` is [missing](https://getbootstrap.com/docs/4.3/utilities/colors/) from Bootstrap. It's commonly needed... for example, with absolute / fixed position elements that overlap other elements, or just when you have one element with `bg-success` or something and you need a "plain" background element inside it.

It's super easy to add, but I've had to add it to every project I've ever used bootstrap in. It just seems like it would make sense to be there to begin with.

**Comment by DevchamploO** [comment]
What do you mean by plain?

**Comment by skeets23** [comment]
sorry, plain background = same background color as `body`

**Comment by MartijnCuppens** [comment]
Not sure if it's really needed, we already have a `.bg-dark` class.

Thoughts @twbs/css-review?

**Comment by mdo** [comment]
I see the value in adding it to do a series of layered components that automatically adjust to their surroundings when customized. `.bg-dark` is an implicit connection to a dark background, and not every customized body background will match one of our predefined colors.

I'll open a PR :).
