### ISSUE TITLE
Bootstrap 4.0.0 Single button dropdowns

### ISSUE THREAD

**Issue by MichaelAchterberg** [twbs/bootstrap#29353]
When copying the code i get the button but no drop down list, what can i do to make it work?

machterberg@devoptec.com

**Comment by myorangeca** [comment]
This isn't related to bootstrap - its the way you copied the codes.

**Comment by MichaelAchterberg** [comment]
I used the copy button

**Comment by patrickhlauke** [comment]
suggest you work your way through https://getbootstrap.com/docs/4.3/getting-started/introduction/
