### ISSUE TITLE
example shortcode: see if we can use a regex

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29351]
https://github.com/twbs/bootstrap/blob/919b526f17a08cefba51c42b831c922adecb4a9f/site/layouts/shortcodes/example.html#L35-L38

The above basically extracts the class, removes `bd-placeholder-img` and `bd-placeholder-img-lg`.

I wonder if we can use `findRE` along with `replaceRE` to achieve the same thing.

Not a huge deal, it just feels like a more elegant solution.

Similarly we could try doing the same for:

https://github.com/twbs/bootstrap/blob/919b526f17a08cefba51c42b831c922adecb4a9f/site/layouts/shortcodes/example.html#L27-L29

This just extracts the `<svg></svg>`.

**Comment by morrissey-ingenious** [comment]
Something like this?

``{{ replaceRE "<svg.*class=.bd\-placeholder\-img(.*?)".*?<\/svg>" `<img src="..." class="$1" alt="..." >` $content_chunk }}``

**Comment by morrissey-ingenious** [comment]
I modified this a bit, I think this will work for all instances.

``{{- $content_chunk = replaceRE `<svg.*class=.bd\-placeholder\-img(?:\-lg)?.?(?:bd\-placeholder\-img\-lg)?(.*?)".*?<\/svg>` `<img src="..." class="$1" alt="..." >` $content_chunk -}}``

**Comment by XhmikosR** [comment]
@morrissey-ingenious Can you make a PR and CC me, please?
