### ISSUE TITLE
sidebar nav-item dropdown-menu in dashboard example 

### ISSUE THREAD

**Issue by rhalp10** [twbs/bootstrap#29369]
can u add nav-item dropdown/accordion functionality for submenu in bootstrap4 admin example

**Comment by mdo** [comment]
We don't have an admin example. Are you referring to the Dashboard example?

**Comment by rhalp10** [comment]
> We don't have an admin example. Are you referring to the Dashboard example?

yes , imean dashboard sorry about that..

**Comment by rhalp10** [comment]
I fix this issue, using `data-toggle="collapse" ` and `css `
**Preview**:
![bandicam2019-09-0601-33-02-408](https://user-images.githubusercontent.com/13925864/64366244-65768680-d048-11e9-9d90-b4e17f8f505b.gif)
[Snippet](https://gist.github.com/rhalp10/1ee5ff07027dc9badcbf3badf5d0f0db)

**Comment by mdo** [comment]
Closing since problem was solved with collapse and custom code. No plans to add more to the Dashboard example at this time.
