### ISSUE TITLE
Button Disabled Hover

### ISSUE THREAD

**Issue by wilecoyte78** [twbs/bootstrap#29360]
When a user hovers over a button that is disabled they still see the pointer. This gets confusing for a lot of users, because they think it is clickable. So when they click on it and it does nothing, they think the website is broken. When the button is disabled can we do cursor: auto. 

    <button disabled class="rounded-lg btn btn-info btn-block">Click Me</button>
    <style>
         .btn.disabled, .btn:disabled {
             opacity: 0.65;
             box-shadow: none;
             cursor: auto;
         }
    </style>

**Comment by florianlacreuse** [comment]
Everything seems to be fine from the [documentation](https://getbootstrap.com/docs/4.3/components/buttons/#disabled-state). We have the default cursor as it should be, instead of the pointer cursor. Could you provide a reduced test case?

**Comment by acshef** [comment]
@florianlacreuse, you've provided outdated documentation. Here's a reduced test case from v4.4.0: https://getbootstrap.com/docs/4.4/components/buttons/#disabled-state
