### ISSUE TITLE
Modal-lg and modal-xl problem

### ISSUE THREAD

**Issue by dganan** [twbs/bootstrap#29371]
When applying modal-xl to a modal-dialog, the corresponding media css rule changes the max-width for the modal-xl, but the max-width:500px of the modal-dialog from the min-width:576px media still applies so it does not work.

If solved it adding the .modal-dialog class in the corresponding media rules, but !important is required to override the default value:

@media (min-width: 992px) {
    .modal-dialog,
    .modal-lg,
    .modal-xl {
        max-width: 800px !important;
    }
}

@media (min-width: 1200px) {
    .modal-dialog,
    .modal-xl {
        max-width: 1140px !important;
    }
}

**Comment by florianlacreuse** [comment]
Could you provide a reduced test case? FWIW, everything works as expected in [this example](https://codepen.io/florianlacreuse/pen/MWgrYLj).

**Comment by dganan** [comment]
Hi Florian, I’ve investigated deeper, and seems a problem with the bundler of the platform I use, not a bootstrap problem. Sorry for the issue. Thank you very much.
