### ISSUE TITLE
btn-outline-light Not Readable

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [twbs/bootstrap#29373]
The Button text not readable(visible) properly.
Screenshot:  https://www.screencast.com/t/dgQIel6y8
https://getbootstrap.com/docs/4.3/components/buttons/#outline-buttons

**Comment by florianlacreuse** [comment]
The `light` theme color is made to be used with darker backgrounds.

Example: https://codepen.io/florianlacreuse/pen/LYPeQXa

**Comment by Johann-S** [comment]
That's right thanks @florianlacreuse 👍
