### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by qureshiawais67** [twbs/bootstrap#29375]
I want to put a logo image on the right in front of collapsed nav menu bar can any one help z-index is not working on nav bar 
I want to do it in only HTML & CSS (Bootstrap). No javascript

**Comment by patrickhlauke** [comment]
per the contributing guidelines https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker you should ask on StackOverflow or similar. thanks.
