### ISSUE TITLE
Left border detached in Alerts + List Groups in IE11 in v4.3.1 (Windows 8.1)

### ISSUE THREAD

**Issue by timmi4sa** [twbs/bootstrap#29385]
![Bootstrap4-3-1-bug-IE11-windows81](https://user-images.githubusercontent.com/4761646/64493465-64567c80-d235-11e9-9944-4db7f2844e8a.PNG)

The bootstrap v4.3.1 fails to display alerts, list groups (and perhaps more things) correctly. The screenshot is attached: the left border is detached from the body of the components.

Versions:
- Windows 8.1 (on desktop)
- IE11 version 11.0.9600.19431
Windows 10: IE11 on an updated Windows 10 doesn't have this bug.

**Comment by XhmikosR** [comment]
I don't think that's supported. I personally don't have any way to test 8.1, and its market share is so small anyway.

**Comment by Johann-S** [comment]
Unable to reproduce on Win 8.1 with IE 11

**Comment by timmi4sa** [comment]
@Johann-S We have dug deeper and it looks like a "VirtualBox guest Windows 8.1" issue. When connecting using an RDP session to the same VM we can't reproduce this bug. There must be something that VirtualBox video driver introduces that causes this failure. [Since the number of people that would attempt to use the web app inside a Virtualbox guest OS in IE11 is slim to none we want to apologize and suggest closing this item]
