### ISSUE TITLE
Extra font weights

### ISSUE THREAD

**Issue by Starlette** [twbs/bootstrap#29380]
Hi there. I was busy customizing Bootstrap when I realized you can't add extra font weights (like semi bold). Would it not be better if you converted the font weight variables into a map so that we can add custom values to it (like we can do with theme colors) then in the _text.scss you loop through the map and dynamically create the font weight classes - something like this:
`@each $font-weight, $value in $theme-font-weights {
.font-weight-#{$font-weight}: $value;
}`

**Comment by MartijnCuppens** [comment]
Hi @Starlette,

Our next major release, `v5`, will have a [utility API](https://twbs-bootstrap.netlify.com/docs/4.3/utilities/api/) where you can control which font weight will be generated:
https://github.com/twbs/bootstrap/blob/713dd824038aba59185b05e4c87bce8e5452e893/scss/_utilities.scss#L361-L370
