### ISSUE TITLE
Remove utilities from bootstrap-grid

### ISSUE THREAD

**Issue by jksdn** [twbs/bootstrap#29383]
Hi, I usually use bootstrap-reboot and bootstrap-grid to build my websites, and I have noticed a lot of useless utility classes in my build CSS file that I don't frequently use, I suggest to remove utility classes from bootstrap-grid and use bootstrap-utilities apart

**Comment by mdo** [comment]
Can't remove them in v4, that's a breaking change. v5 could maybe introduce a split there that makes it grid and utilities as separate files. Not sure if that's just getting us into roundabout modular approach in our dist files vs the source files, too.

Thoughts @twbs/css-review?

**Comment by MartijnCuppens** [comment]
You will have the ability to control the spacing utilities in `v5` with our utilities Sass map. I do see the offset classes are still part of the grid, maybe we can also move them to the utility API?

**Comment by mdo** [comment]
Offset should stay with the grid. I'm inclined to leave this as we have it now as we work through v5's alpha development. I imagine the most we'd do is actually to customize the utilities a bit for the grid build.
