### ISSUE TITLE
Signup not working

### ISSUE THREAD

**Issue by bokobza** [twbs/bootstrap#29395]
Trying to sign up and the "Sign Up" button isn't working.
Looking at the console, I see the following:
![image](https://user-images.githubusercontent.com/1867877/64533423-5d9a3900-d30b-11e9-808f-fe5eed790cbf.png)

Tried on Chrome, Opera, Brave.

**Comment by Johann-S** [comment]
Hi @bokobza,

There is no "Signup" feature provided by Bootstrap 🤷‍♂ 
I think you're in the wrong repository
