### ISSUE TITLE
Payments not working

### ISSUE THREAD

**Issue by bokobza** [twbs/bootstrap#29394]
Trying to buy a theme on getbootstrap.com and it's not working, I get an error message saying 
```
Please enter your card details to make a payment. Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.
```

Tried on Chrome and Opera, with 2 different cards.

![image](https://user-images.githubusercontent.com/1867877/64531929-65a4a980-d308-11e9-9627-1af837527f4c.png)

Related issue: https://github.com/twbs/bootstrap/issues/29389

**Comment by Johann-S** [comment]
Hi @bokobza,

It seems you have issues with https://themes.getbootstrap.com/ which is a different project and not maintained by Bootstrap core members.

You should ask in the official Slack team, there is a channel `#themes` and you'll be able to ask for help here. [See our readme for more details](https://github.com/twbs/bootstrap#community).

**Comment by bokobza** [comment]
Apologies for that, I was under the impression it was the same team.
Thanks for the pointers.

**Comment by mdo** [comment]
Should be resolved now, sorry about that!

**Comment by bokobza** [comment]
It is, thanks @mdo 👍
