### ISSUE TITLE
Non HTTPS links broke in tab content for dynamic tabs and pills

### ISSUE THREAD

**Issue by JeusuDigital** [twbs/bootstrap#29391]
- **Operating system and version:** 
Windows 10 1903
- **Browser and version:** 
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- **Bootstrap Version:** 
4.3.1
- **Reduced test case:** 
https://jsfiddle.net/s0dh57fr/

Hi I have copy and pasted the default dynamic pills and tabs code from the official docs in the test case above. I have then added a HTTP and HTTPS link for 2 sites in the home tab content.

The HTTP links do not work but the HTTPS links work.

- **Update:** 
On further looking into this It seems that the non HTTP error is being blocked by Chrome:

> This page is trying to load scripts from unauthenticated sources: The site that you are trying to visit isn't secure.

**Comment by rafalp** [comment]
This looks like an [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue on your site, and not something bootstrap specific.

**Comment by patrickhlauke** [comment]
indeed. closing, per https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
