### ISSUE TITLE
Set cursor: pointer as class

### ISSUE THREAD

**Issue by zmija** [twbs/bootstrap#29397]
### Is your feature request related to a problem? Please describe...

I use Bootstrap in combination with vue.js and I try to avoid using any custom styling at all since Bootstrap options cover the majority of what I need. One thing that I quite often have to add to the scoped styling is ```cursor: pointer;``` if I, for example, use an icon which performs an action. Another example is adding click action to the table row.

### Describe the solution you'd like

It would be awesome if you include an option to simply use ```cursor-pointer``` (or similar) class which will add ```cursor: pointer;``` CSS.

### Additional context

If you decide to include that in Bootstrap, it would be probably wise to add also some other options (grab, move, etc.). 

Keep up the good work 🥇

**Comment by patrickhlauke** [comment]
i'd say no, for the same reason given here https://github.com/twbs/bootstrap/pull/29374
