### ISSUE TITLE
Ability to open several modals

### ISSUE THREAD

**Issue by Julia1996** [twbs/bootstrap#29393]
Currently if I open modal when there is one modal is already opened and then I close that modal, both modal will be closed. The button that launch the second modal is inside body of the fist modal. It would be good to have ability to open several modals
https://codepen.io/julia1996/pen/PoYQLaW

**Comment by Johann-S** [comment]
Hi @Julia1996,

According to our documentation:
>Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

I don't think there is a plan to change that 🤔 

/CC @twbs/css-review @twbs/js-review

**Comment by MartijnCuppens** [comment]
> I don't think there is a plan to change that 🤔

Nope. I don't think we should support this for the reason above.
