### ISSUE TITLE
Documentation Version Switch to Same/Similar Page

### ISSUE THREAD

**Issue by erayerdin** [twbs/bootstrap#29406]
# What Happens

Oddly, Google, in my area, still indexes 4.0 version of the docs while the current version is 4.3. So the search redirects to `https://getbootstrap.com/docs/4.0`.

When I open up the docs from the search, naturally it says:

 > There's a newer version of Bootstrap 4!

When I click on that, it redirects to home page rather than the same page of the component.

# What I Expect

`There's a newer version of Bootstrap 4!` should redirect to the latest version of Bootstrap of the same component or whatever. This means, the link on `https://getbootstrap.com/docs/4.0/components/popovers/` sohuld redirect to `https://getbootstrap.com/docs/4.3/components/popovers/` or we should do something similar to `https://getbootstrap.com/docs/latest/components/popovers/`.

**Comment by XhmikosR** [comment]
The thing with this that not all pages exist in newer versions.

**Comment by yakov116** [comment]
@XhmikosR can you make a fall back?

**Comment by erayerdin** [comment]
@XhmikosR As @yakov116 said, a fallback to the home page would be okay. The target audience of the docs is developers anyways, so they would get the idea that the component/feature they have requested is not available in the latest version.

**Comment by XhmikosR** [comment]
PRs welcome.

**Comment by HASITHNIMHARA2003** [comment]
i like it

**Comment by midzer** [comment]
How can we modify old version docs pages?

I can't find respective source code in repo. There is only `site/content/docs/4.3/` in master branch.

**Comment by XhmikosR** [comment]
It's in the gh-pages branch. But I **really** don't want to change the old versions without discussion.

**Comment by skmedix** [comment]
Google still points to version 4.0 (sometimes newer), which is pretty annoying. Does anything was discussed towards this? Also, should docs for 4.3 show an alert that a new version is available?

**Comment by XhmikosR** [comment]
Closing for #28115
