### ISSUE TITLE
[Question About Docs] Translation workflow

### ISSUE THREAD

**Issue by kburakozdemir** [twbs/bootstrap#29408]
Is there a guide for a proper way of translating the documentation into another language by directly using a fork of this repository? I want to translate the latest version of documentation on a fork and publish it on GitHub pages? Any suggestions, recommendation?

*Note: I am aware of the unofficial translations are done separately and then the link is added to translation pages.*

**Comment by mdo** [comment]
No formal guide or workflow recommendations from us, we've never done it ourselves.
