### ISSUE TITLE
Possible Docs Typo

### ISSUE THREAD

**Issue by JStyle21** [twbs/bootstrap#29407]
Hi,

Just started reading the docs, was wondering if the overview page has a typo
https://getbootstrap.com/docs/4.3/layout/overview/
It mentions Sass everywhere but the syntax shown is actually Scss which is strange especially after coming from the introduction section which only talks about Scss.

**Comment by florianlacreuse** [comment]
`SCSS` (`scss` files) is one of the two syntaxes of `Sass`: https://sass-lang.com/documentation/syntax

**Comment by JStyle21** [comment]
Yes that's true but why mix the two in one page? No other page mentions Sass at all just Scss

**Comment by florianlacreuse** [comment]
According to me, there is no mix in [layout overview page](https://getbootstrap.com/docs/4.3/layout/overview/). No matches for "scss" word in the page.

Also, other page mentioning `Sass`: https://getbootstrap.com/docs/4.3/getting-started/webpack/#importing-precompiled-sass

**Comment by JStyle21** [comment]
I meant overview uses Sass while other pages used Scss for example the [Theme page](https://getbootstrap.com/docs/4.3/getting-started/theming/) is full of it
But if you say its not an error good enough for me, sorry for the troubles

**Comment by florianlacreuse** [comment]
This page uses `scss` for file extension, folder name, etc. as It should be because BS use the SCSS syntax from Sass.

**Comment by ysds** [comment]
Sass is like Japanese. Japanese can be written in hiragana, katakana and kanji, but all are Japanese.

The Sass language has Saas and Scss syntax. Both are Saas languages.

Our documents use Saas (language) to refer to broader concept.

* Japanese file > Hiragana file
* Saas file > SCSS file

**Comment by JStyle21** [comment]
Thanks for the clarification, i've learned from this :)
