### ISSUE TITLE
Javascript Tabs Bug

### ISSUE THREAD

**Issue by dday9** [twbs/bootstrap#29404]
- OS: Windows 10 64 bit
- Browser: Mozilla Firefox Quantum
- Stackoverflow Question: https://stackoverflow.com/q/57872680/1920035
- Live example: https://codepen.io/Johann-S/pen/wvwXpOp

What I have found is that when setting up a tab control to dynamically display content does not work if you do not specify a tablist. The markup that I'm using is:
``` html
<div class="tab-content">
  <form class="tab-pane active" id="login">
      <fieldset>
          <legend>Sign In</legend>
          <div class="form-group">
              <label for="username">Username</label>
              <input class="form-control" id="username" type="text" required="required" />
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <input class="form-control" id="password" type="password" required="required" />
          </div>
          <div class="form-group text-center">
              <button type="submit" class="btn btn-primary">SIGN IN</button>
          </div>
      </fieldset>
      <a class="d-block text-center" href="#password-reset" data-toggle="tab">Forgot Password?</a>
  </form>

  <form class="tab-pane" id="password-reset">
      <fieldset>
          <legend>Forgot Password</legend>
          <div class="form-group">
              <label for="email">Email</label>
              <input class="form-control" id="email" type="email" required="required" />
          </div>
          <div class="form-group text-center">
              <button type="submit" class="btn btn-primary">SEND RESET</button>
          </div>
      </fieldset>
      <a class="d-block text-center" href="#login" data-toggle="tab">Go Back</a>
  </form>
</div>
```
If you click on the Forgot Password link it will redirect you to the password-reset form. If you click on Go Back it will redirect you back to the login form. If you attempt to click on the Forgot Passowrd link (a second time) it does nothing.

**Comment by Johann-S** [comment]
Hi @dday9,
It doesn't work because your html markup doesn't follow the markup recommended by Bootstrap.

Because of that our Tab plugin is unable to find the previous activated item see:
https://github.com/twbs/bootstrap/blob/master/js/src/tab/tab.js#L88-L96

So for a quick fix I recommend to follow Bootstrap's markup see: https://getbootstrap.com/docs/4.3/components/navs/#javascript-behavior

And on our end maybe we should allow our users to pass a custom selector to find activated triggers and activated contents (/CC @twbs/js-review)

**Comment by XhmikosR** [comment]
The markup requirement is there for all components for years, I'm not sure it makes sense to change this.

**Comment by mdo** [comment]
Agreed. Closing as a won’t fix.

**Comment by dday9** [comment]
That's a shame that using a custom selector isn't being considered. I understand that there are single page application libraries out there, but for something as simple as this I would've hoped for a Bootstrap solution.
