### ISSUE TITLE
Allow our constructors to accept a CSS selector

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#29417]
Currently in all of our plugins constructors, the first parameter is an element, we should allow our users to use CSS selector too.

X-Ref: https://github.com/twbs/bootstrap/issues/29416

**Comment by rohit2sharma95** [comment]
If the selector returns a node list then the constructor should use just the first element? Or maybe you will use `querySelector()` always for it. What is your idea? @Johann-S
