### ISSUE TITLE
Nothing compiled?

### ISSUE THREAD

**Issue by Xbeninni** [twbs/bootstrap#29412]
Hey everyone,

I was trying to [partially import Bootstrap](https://getbootstrap.com/docs/4.3/getting-started/theming/#importing) for compiling but nothing happened. It does successfully compile when using the full import.  Did I miss something? Thank you!
![screenshot](https://i.ibb.co/GTdPJbj/screenshot.gif)

**Comment by bodograumann** [comment]
Well, you have left all optional parts away. The 3 required parts only provide sass functions etc, which do not actually generate any css output.

**Comment by Xbeninni** [comment]
# oh I get it, thank you @bodograumann
