### ISSUE TITLE
[ Input Groups ] Missing responsive for Input Groups 

### ISSUE THREAD

**Issue by 0wczar** [twbs/bootstrap#29418]
In my opinion, there is no responsive behavior from Input Group.

**Desktop:** 
![form-inline_ Staff Mobile Number](https://user-images.githubusercontent.com/2330394/65049077-79ce5380-d965-11e9-9c0d-687dcccb8750.png)

**Mobile MD, XS:**
![form-inline_ Staff Mobile Number-xs](https://user-images.githubusercontent.com/2330394/65049123-8d79ba00-d965-11e9-851d-f1af838945e4.png)

What do you think?

**Comment by mdo** [comment]
I don't know how we could reliably predict what you want for your form layout with this. There's only so much we can do out of the box before it becomes a nightmare for you to further customize. For now I'm still a pass on doing anything more than stacking individual fields and input groups without physically attaching them to one another.

**Comment by 0wczar** [comment]
Hey @mdo @julien-deramond Time showed that I was right? :)
Maybe context helps here: 
![image](https://github.com/twbs/bootstrap/assets/2330394/658221d9-8879-41c9-b031-eb0f56bc0b0f)

Maybe time to rethink this again?:)

**Comment by julien-deramond** [comment]
Could you please create a new follow-up issue reminding the context and the new information @0wczar? We have a lot of ongoing topics to tackle right now and we will forget about this comment in a closed issue.

**Comment by 0wczar** [comment]
@julien-deramond Yes I'll do it. I have a few ideas. I will come back soon.
