### ISSUE TITLE
V5 Show / Hide / Toggle Not working correctly

### ISSUE THREAD

**Issue by yakov116** [twbs/bootstrap#29416]
```javascript
const bsCollapse = element => new bootstrap.Collapse(element, {
	hide: true
});

const collapseTwo = document.querySelector('#collapseTwo');
bsCollapse(collapseTwo);
```

When ever running `bsCollapse` it will hide/show depending on what the status is.

This issue is both if I use show/hide.

Next I have a suggestion. 
Can the `new bootstrap.Collapse` (for that matter any of the methods) take a CSS selector or in addition to an element?

Thanks for your great work!

**Comment by Johann-S** [comment]
Hi @yakov116,

There is no `hide` parameter allowed in our Collapse plugin, see: https://getbootstrap.com/docs/4.3/components/collapse/#options

BTW instead of creating a new Collapse each time, you should store the result and call directly our `toggle` method.

For example:
```js
const collapseTwo = document.querySelector('#collapseTwo');
const bsCollapse = element => {
  return bootstrap.Collapse.getInstance(element) ?
    bootstrap.Collapse.getInstance(element) : 
    new bootstrap.Collapse(element, { toggle: false })
}

const myCollapse = bsCollapse(collapseTwo);
myCollapse.toggle()

**Comment by yakov116** [comment]
@Johann-S thanks!

It would be great if the docs had some more examples.

**Comment by Johann-S** [comment]
@yakov116 if you have some idea about good examples do not hesitate to send PR(s) 👍

**Comment by designxsteph** [comment]
I would love to see an example of how to use the hide/show methods. There are none in the docs and I'm having a hard time migrating off v4. I would be using the hide/show methods to automatically hide/show the collapsed item based off viewport, or when certain conditions are met.
