### ISSUE TITLE
Modal resize breakpoints incorrect

### ISSUE THREAD

**Issue by tedma4** [twbs/bootstrap#29423]
- iOS
- Chrome 76
- https://getbootstrap.com/docs/4.3/components/modal/#optional-sizes
The x-large modal does is not breaking at the respective col sizes(992, 768, 576)

**Comment by florianlacreuse** [comment]
Unless I misunderstood, everything is fine.

Using `.modal-xl` implies `.modal-lg`, and `.modal-sm` (and of course the modal default medium size).

https://github.com/twbs/bootstrap/blob/129bb08fc4d2c850ae71250371adf82a4441dc70/scss/_modal.scss#L222

https://github.com/twbs/bootstrap/blob/129bb08fc4d2c850ae71250371adf82a4441dc70/scss/_modal.scss#L225-L234
