### ISSUE TITLE
Split variables into different files, at least only for grid

### ISSUE THREAD

**Issue by SilencerWeb** [twbs/bootstrap#29428]
I need only grid from the bootstrap, but for this, I need to import `_variables.scss` with over 400 variables and some of my variables overwrite bootstrap variables (like font-size and line-height variables that are not related to the grid at all) and because of this, everything fails. It would be much better if I could import only variables for the grid.

![image](https://user-images.githubusercontent.com/20713191/65370402-cbcaee00-dc71-11e9-959f-c46e7f287a02.png)

**Comment by florianlacreuse** [comment]
I don't know about splitting variables file but see #28240 as it may solves your issue.

**Comment by SilencerWeb** [comment]
@florianlacreuse yeah, I've already seen this issue, it won't help in my case

**Comment by InsanityMeetsHH** [comment]
@SilencerWeb to avoid this error you could use a variable prefix / namespace. I use the term "theme".
e.g. $theme-font-size, $theme-line-height in your case.

**Comment by mdo** [comment]
Closing as a won't fix after closing #29451.
