### ISSUE TITLE
Problem which is unfixable and common. This is just for people to be educated

### ISSUE THREAD

**Issue by FiecyLick** [twbs/bootstrap#29424]
Fishy websites like get free money or free stuff for games is used by a free license to get by with Google site security domain's so Google doesn't get fishy and shut it down. 

I provided a image of what sites like these can do and create domain sites for this type of stuff. When you get to the authorization page to complete 2 surveys or whatever. It is common where you complete 1 and never let you finish the rest. that's because the site is design that way, you can't go any farther and will trick you of wasting your time. When that builds up, the owner of the website makes money profit off of their fishy advertisements that they make off of. This is just to help others be more aware what this can do. This license is under MIT was made by this github source. Fishy is fishy after all. 

Hope you learned something.

![Clash of Clans Hack - Google Chrome 9_19_2019 11_58_39 PM](https://user-images.githubusercontent.com/33188682/65298423-77245780-db39-11e9-8a7f-50f947225a80.png)

**Comment by Johann-S** [comment]
Hi @FiecyLick,

Bootstrap is just a frontend framework which can be used by everybody, we are not responsible of the actions of our users.
