### ISSUE TITLE
Updating the Meteor Package

### ISSUE THREAD

**Issue by BrianMulhall** [twbs/bootstrap#29431]
Could the meteor package be kept up to date with the current release of Bootstrap?

This is a very popular package in the Meteor Community and Bootstrap 5 looks like it would gain a following among devs using Meteor.

https://atmospherejs.com/twbs/bootstrap

**Comment by XhmikosR** [comment]
@mdo: do you have access yourself? If so we need to add this in the release checklist.

**Comment by BrianMulhall** [comment]
I'm sorry, Im not sure I'm following the question? do i have access to what?

**Comment by XhmikosR** [comment]
My message was directed to @mdo, not you @BrianMulhall.
