### ISSUE TITLE
[request] Add option to disable modal animation on the methods .modal('hide') .modal('show')

### ISSUE THREAD

**Issue by nicolomonili** [twbs/bootstrap#29446]
https://getbootstrap.com/docs/4.3/components/modal/#methods

I know the possibility of remove the class **fade** for remove the animation (_open_ and _close_) of a **modal** (https://getbootstrap.com/docs/4.3/components/modal/#remove-animation).

But in some cases (especially when working with a modal that must be opened immediately after the closure of another) it would be useful using the methods `.modal('hide')` and `.modal('show')` to disabled a single animation of a modal.

Scenario:
- Open **modal A** with animation
- With a button on modal A open a **modal B** (close the modal A without animation and open modal B without animation)
- Close modal B with animation or back to modal A without animation

Example (add a second parameter to disable the animation)
```
.modal('hide', true) //close modal without animation
.modal('show', true) //open modal without animation
```

**Comment by Johann-S** [comment]
Hi @nicolomonili,

Thanks for your suggestion, but I think we'll pass on that, it's totally doable currently.

For example:
```js
$('#modalA').removeClass('fade')
  .modal('hide')
  .one('hidden.bs.modal', function() {
    $(this).addClass('fade')
  })
$('#modalB').modal('show')
```

/CC @twbs/js-review for feedbacks

**Comment by nicolomonili** [comment]
There is a small error.
`.on `not `.one`

**Comment by Johann-S** [comment]
@nicolomonili https://api.jquery.com/one/#one-events-data-handler 😉
