### ISSUE TITLE
Disabled input form control should be without focus status

### ISSUE THREAD

**Issue by vraajesh** [twbs/bootstrap#29442]
![image](https://user-images.githubusercontent.com/7411711/65612566-1f22a080-dfd2-11e9-80d7-8bd27539c24a.png)

From the user experience point disabled / read only input form control should not have focus state, this might confuse the user.

**Comment by patrickhlauke** [comment]
read-only form controls are focusable by default in browsers. forcing them NOT to be focusable would be an opinionated change that goes against browser conventions.

**Comment by mdo** [comment]
Closing per last comment.
