### ISSUE TITLE
[BUG] Form input with input-group-prepend and valid-feedback/invalid-feedback lose border radius

### ISSUE THREAD

**Issue by BattlefieldDuck** [twbs/bootstrap#29459]
The `border-radius` is not rounded when `form` with `input-group-prepend` and (`valid-feedback` or `invalid-feedback`) lose `border-radius`.

Normally with `input-group-prepend` only: 
![2019-09-28](https://user-images.githubusercontent.com/29337428/65818132-24d1ed80-e241-11e9-9cf0-e237f87e7814.png)

Normally with `invalid-feedback` only: 
![2019-09-28 (1)](https://user-images.githubusercontent.com/29337428/65818149-52b73200-e241-11e9-9847-f63cff4bc912.png)

But with both `input-group-prepend` and `invalid-feedback` lose `border-radius` on the right side:
![2019-09-28 (2)](https://user-images.githubusercontent.com/29337428/65818155-62367b00-e241-11e9-8fd3-cb7cf61e340f.png)

Code that regenerate the border bug:
``` html
<div class="col-md-4 mb-3">
  <label for="validationCustomUsername">Username</label>
  <div class="input-group">
	<div class="input-group-append">
	  <span class="input-group-text" id="inputGroupPrepend">@</span>
	</div>
	<input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>
	<div class="valid-feedback">
	  Please choose a username.
	</div>
  </div>
</div>
```

You can see the bug in Bootstrap document too
https://getbootstrap.com/docs/4.3/components/forms/#custom-styles

**Comment by midzer** [comment]
This happens because of
```
<div class="invalid-feedback">
    Please choose a username.
</div>
```
as last child inside `.input-group`

**Comment by BattlefieldDuck** [comment]
Oh I see! I understand now.

**Comment by alexdarahan** [comment]
Sorry... But I personally didn't get... What's workaround for it? 
I mean if I want a div with a 'feedback-invalid' to be present in order to show that this error belongs to this field.. 
Any decision for this?

**Comment by BattlefieldDuck** [comment]
The solution of this is add a **.rounded-right** in `input`.
See: https://tatlead.com/bootstrap/BUG-FormInputBorderRadius.html

**Comment by francoisrouault** [comment]
I reopen a similar issue since the bug remains in bootstrap 4.4 https://github.com/twbs/bootstrap/issues/30116
