### ISSUE TITLE
`tooltip#sanitizeHtml()` missing `null` check

### ISSUE THREAD

**Issue by Klinton90** [twbs/bootstrap#29474]
Operating system: Windows 10
Browser: Chrome 77

Test case:
In update to 3.4.1 community added `sanitizeHtml` feature to `tooltip.js`. Code itself works fine, but it is missing _null check_ before attempt to sanitize string/content/title, which breaks (at least in my project) existing code.

Proposed fix:
```
function sanitizeHtml(unsafeHtml, whiteList, sanitizeFn) {
    // if (unsafeHtml.length === 0) {
    if (!unsafeHtml || unsafeHtml.length === 0) {
      return unsafeHtml
    }
...
}
```

**Comment by Johann-S** [comment]
Hi @Klinton90 can you us how do you initialize your tooltips ?

**Comment by Klinton90** [comment]
```
app.factory('popoverDirectiveFactory',
    function () {
        return {
            popoverDirective: function popoverDirective(title, template, directiveObject) {
                return function ($compile) {
                    return angular.extend({
                        restrict: 'E',
                        link: function ($scope, el, attrs) {
                            ...
                            $(el).popover({
                                trigger: 'manual',
                                html: true,
                                content: $compile(template)($scope),
                                placement: attrs.placement,
                                title: title || '',        // <-- this changed to prevent exception
                                container: 'body'
                           });
                           ...
                       }, directiveObject);
               });
           }
       };
    }
};
```

**Comment by Johann-S** [comment]
Hi @Klinton90,

I tried to reproduce your error but I'm unable to reproduce it, see: https://github.com/twbs/bootstrap/pull/29733

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link.

**Comment by Klinton90** [comment]
Codepen: https://codepen.io/Kl1nton/pen/eYYwNOz
Please note, I specifically mentioned v3.4.1
I did not test with v4+

Thank you anyway for looking into this.

**Comment by XhmikosR** [comment]
@mdo I suppose we stick with our plan and consider v3 dead, right? Otherwise this seems like an easy fix...

@Johann-S if this does not happen with v4 or master let's change the issue labels to reflect this

**Comment by Johann-S** [comment]
done @XhmikosR

**Comment by shainegordon** [comment]
that was quite an annoying bug, as a dependency updated from 4.3.0 to 4.3.1 and all our tooltips broke.

we had to fix this by change `title=""` to `title=" "`

**Comment by mdo** [comment]
Correct on v3 (phew I’m late here). Any thoughts on latest comment above though? Feel free to close if this isn’t an issue.

**Comment by XhmikosR** [comment]
`title` is supposed to be sanitized so the docs apply AFAICT.

**Comment by XhmikosR** [comment]
PRs welcome to fix any issues in master and subsequently we can backport the fix to v4-dev.
