### ISSUE TITLE
Recent commit breaks modularity

### ISSUE THREAD

**Issue by Algorithmus** [twbs/bootstrap#29471]
Ever since this commit: https://github.com/twbs/bootstrap/commit/114a0ee193ffe7869c8369f25ef4dcc44929fbf5#diff-5160056bcd6d0f990ba7775663f6d27f

I have been unable to include bootstrap components in a modular way.

Instead of `require('bootstrap')` which includes every single module contained in bootstrap, I just want the modal: `require('bootstrap/js/dist/modal.js')` (or perhaps there's a better include I'm supposed to be using? I couldn't find it)

I'm using encore webpack, but it's unable to find the dependencies in `js/dist/modal.js` or the src one after this commit.

**Comment by Johann-S** [comment]
Hi @Algorithmus,

it seems you're using our unreleased v5.

Can you show the error message you have? And how do you install our v5?

**Comment by Algorithmus** [comment]
We are using v5 because we don't need jQuery.

We are using npm. Here is the entry in package.json:

`"devDependencies": {
...
"bootstrap": "git+https://github.com/twbs/bootstrap.git",
...}`

And when running encore, it looks like this:

```
Running webpack ...

 ERROR  Failed to compile with 4 errors                                                                                                                                                                                                                                 08:40:00

These relative modules were not found:

* ../dom/data.js in ./node_modules/bootstrap/js/dist/modal.js
* ../dom/event-handler.js in ./node_modules/bootstrap/js/dist/modal.js
* ../dom/manipulator.js in ./node_modules/bootstrap/js/dist/modal.js
* ../dom/selector-engine.js in ./node_modules/bootstrap/js/dist/modal.js
```

**Comment by Johann-S** [comment]
Ok it's due to our new file structure (`pluginName/pluginName.js`) nice catch 👍
