### ISSUE TITLE
Add a namespace for data-* attribute?

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#29479]
Hello,

As of V5 is coming, maybe it's also time to add a namespace on `data` attribute to prevent conflict with others library?

Something like for events `data-bs-toggle`?

**Comment by Johann-S** [comment]
I think it can be a good change for us 👍 

/CC @twbs/css-review and @twbs/js-review for other feedbacks

**Comment by XhmikosR** [comment]
Yup, agreed.

**Comment by MartijnCuppens** [comment]
Yup, I agree!

**Comment by GeoSot** [comment]
A bit stupid but "'data-bs-" or "'data-" prefix could be given by a helper function.  
example `bsDataName('toggle')`

It may would help on the minimization of js files and for backward compatibility reasons
