### ISSUE TITLE
A11y_WindowsVirtualDesktopWeb_AboutTab_K4W: ARIA hidden element must not contain focusable elements (rdp-client-top-view).

### ISSUE THREAD

**Issue by 12-shweta** [twbs/bootstrap#29487]
**Issue**
ARIA hidden element must not contain focusable elements (aria-hidden-focus)
**Target application**
[Remote Desktop Web Client](https://rdweb.wvd.microsoft.com/webclient/index.html)
**Element path**
rdp-client-top-view
**Snippet**
<rdp-client-top-view data-bootstrap-modal-aria-hidden-count="1" aria-hidden="true">

**How to fix**

Fix all of the following:
- Focusable content should have tabindex='-1' or be removed from the DOM

**Environment**
Chrome version 75.0.3770.100 This accessibility issue was found using Accessibility Insights for Web 2.5.5 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

**Attachment**
![22356445_A11y_WindowsVirtualDesktopWeb_AboutTab_K4W](https://user-images.githubusercontent.com/54656883/66111395-674f4d80-e5e6-11e9-8e9a-a61623289635.png)

**Comment by patrickhlauke** [comment]
no idea what you're on about...
