### ISSUE TITLE
Arrow of popover is positioned 4px different on Firefox

### ISSUE THREAD

**Issue by jelhan** [twbs/bootstrap#29485]
The arrow of popover (`.arrow`) is positioned 4px differently on Firefox than on Chrome, Safari, Edge and IE 11.

This was caught when introducing Firefox as a new target to a CI pipeline, which already targeted the other browsers. You could find details and TravisCI reports here: https://github.com/kaliber5/ember-bootstrap/pull/901

I was able to reproduce manually on getbootstrap.com to ensure that this is not an integration issue:

![popover-firefox-4px-missing](https://user-images.githubusercontent.com/4965703/66082658-e141f100-e56a-11e9-9ac5-1a054b05761b.png)

You see Firefox 69.0.1 on the left side and Chromium 77.0.3865.90 on the right side. Both windows are resized so that the popover container (`.bd-example-popovers`) has a width of 465px. In this case the popover is positioned to fit into the container. The `left` CSS property on Firefox is 4px less than the one on Chromium.

The CI results mentioned above suggest that the other browsers behave like Chromium in this manual test. So this seems to be a Firefox specific bug.

**Comment by mdo** [comment]
The different here seems to be the placement and size of the scrollbar not the width of the container.
