### ISSUE TITLE
Figure captions do not wrap to image width

### ISSUE THREAD

**Issue by leecollings** [twbs/bootstrap#29492]
It's been noted by some users on the internet that when using a figure caption that is quite long, the caption will not wrap under the image, instead it will keep running pushign the figure width out further than the image width.

Here's an example:
![image](https://user-images.githubusercontent.com/6681733/66193138-dfbb1a80-e689-11e9-951d-ffd4552ed079.png)

What should be happening, is the figure width should be taking the image width as the max width, and then the caption should wrap underneath that, making the figure look neat and tidy.

Like this:
![image](https://user-images.githubusercontent.com/6681733/66193251-1133e600-e68a-11e9-9379-ff10731c7e1c.png)

An easy way to do this would be to use a display table on figures:
```
.figure{
    display:table;
}
.figure-caption{
    display:table-caption;
    caption-side:bottom;
    font-size:90%;
    color:#6c757d;
    margin-top:.5em;
    margin-bottom:2em;
}
```

**Comment by mdo** [comment]
If this were to be something we wanted to do, it'd make the most sense as a modifier class. As it stands now, I don't think we should be doing this because it's a stylistic choice to size and align the images and captions.
