### ISSUE TITLE
Size utility screen dependent 

### ISSUE THREAD

**Issue by Serhioromano** [twbs/bootstrap#29505]
Would be nice to have 

```
w-100
w-sm-100
w-lg-100
```

and so on...

I am using Flex utility and I want to make a sort of grid but not by rows. Automatically adjustable. And I need to control width of every element so that it looks as grid and can change width depending on screen size. It would be analog of `col-md-3` in grid but for flex.

**Comment by florianlacreuse** [comment]
See #2948. According to this issue (and others), it will never be done in BS. The good news is that you will be able to customize the new v5 utilities API to do it.

**Comment by mdo** [comment]
There are some other issues about this, and I'm still against this as it continues to add more bloat to our codebase with duplicative code compared to our grid system and more. Note the cross reference above, we may be able to tackle this with v5's grid where we make changes to the grid classes to just set `width`, so they can double up.
