### ISSUE TITLE
Out of date popper link?

### ISSUE THREAD

**Issue by brettz9** [twbs/bootstrap#29529]
Your docs at https://getbootstrap.com/docs/4.3/getting-started/introduction/ list this for Popper:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
```

...but I see that https://www.npmjs.com/package/popper.js is up to 1.15.0.

Do you indicate the highest version with which you have tested (and which your users can safely use), or are your docs out of date?

Thanks!

**Comment by XhmikosR** [comment]
The version shown on the website is what it was when the latest stable was out. At the time the latest popper.js version was 1.14.7.

On master and v4-dev the version has been bumped to the latest.
