### ISSUE TITLE
Carousel - sliding in v4.0.0, not anymore in newer versions?

### ISSUE THREAD

**Issue by Taapo** [twbs/bootstrap#29520]
When looking at the demo for v4.0.0, the carousel is sliding (from left to right):

https://getbootstrap.com/docs/4.0/components/carousel/

When looking at newer versions, it's not sliding anymore (it's switching instead) - is this by design?

https://getbootstrap.com/docs/4.1/components/carousel/
https://getbootstrap.com/docs/4.2/components/carousel/
https://getbootstrap.com/docs/4.3/components/carousel/

**Comment by patrickhlauke** [comment]
https://getbootstrap.com/docs/4.3/components/carousel/#how-it-works

> The animation effect of this component is dependent on the prefers-reduced-motion media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/4.3/getting-started/accessibility/#reduced-motion).

https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/
