### ISSUE TITLE
navbar fixed-top obscures portion of the next element

### ISSUE THREAD

**Issue by AlKult** [twbs/bootstrap#29539]
Hi,

There appear to be other issues somewhat related to fixed-top in the github, but they didn't seem to be related to what I'm experiencing here, therefore apologies if this is a duplicate after all.

If I have a navbar without fixed-top, and an element underneath it - let's say a table - the whole table is shown correctly. However, the moment I add fixed-top, top part of the table equivalent to the navbar's height disappears under the navbar.

Without fixed-top:
![image](https://user-images.githubusercontent.com/1583023/67005653-055d1080-f0db-11e9-87a5-38b854f972b5.png)

With fixed-top:
![image](https://user-images.githubusercontent.com/1583023/67005740-350c1880-f0db-11e9-87f3-9f0fcac8313d.png)

I would've been treating it as normal behaviour if I were to scroll down beyond what fits in a single screen - that's what the point of fixed top is after all - to stay on top when you keep flicking down screens. But if my element fits in a single screen under the navbar, it should be shown in full.

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>navtop</title>
    </head>

    <body>
        <header class="site-header">
            <!-- Navigation bar -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">navtop</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <!-- Navbar Left Side -->
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link mr-sm-2" href="#">#1</a>
                            <a class="nav-item nav-link mr-sm-2" href="#">#2</a>

                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <div class="table-responsive">
            <table align="center">
                <thead>
                  <tr>
                    <th>H1</th>
                    <th>H2</th>
                    <th>H3</th>
                  </tr>
                </thead>

                <tbody>
                    <tr><td>A1</td><td>A2</td><td>A3</td></tr>
                    <tr><td>B1</td><td>B2</td><td>B3</td></tr>
                    <tr><td>C1</td><td>C2</td><td>C3</td></tr>
                </tbody>
            </table>
        </div>

    </body>
</html>
```

The same appears to be happening to regular text: if I replace the whole table div with `<h1>TEST</h1><h1>TEST</h1>,` only the second h1 is shown:
![image](https://user-images.githubusercontent.com/1583023/67006255-908ad600-f0dc-11e9-9cec-41f34e7721f8.png)

Bootstrap 4.3.1
Tested in Browsers:

- Chrome 75.0.3770.80
- FF 69.0.1
- Edge 44.17763.1.0

Best regards,
Albert.

**Comment by herbalite** [comment]
Add position: sticky to the nav tag, and see if that works for you.  This simply changes position fixed to sticky on this nav.

`<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" style="position:sticky">`

You always could write a new rule, instead of making a local style override.

**Comment by AlKult** [comment]
With `<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" style="position:sticky">`, the navbar isn't fixed to the top anymore.

**Comment by mdo** [comment]
This is covered in our docs, and the behavior you're seeing is expected as this is how the CSS properties we're using function.
