### ISSUE TITLE
Download Link is dead on https://getbootstrap.com/docs/4.3/getting-started/download/

### ISSUE THREAD

**Issue by Castellanox7** [twbs/bootstrap#29543]
Page: https://getbootstrap.com/docs/4.3/getting-started/download/

Under the Compiled CSS and JS link, the button is dead.

**Comment by mdo** [comment]
Link works fine for me.

**Comment by Castellanox7** [comment]
Apologies @mdo -- internal networking items prevented me from hitting the download url. Thanks! Have a great weekend.
