### ISSUE TITLE
Custom file input

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#29549]
hi sir,
I am using **bootstrap4.3.1** with **windows 10,** **Chrome ( lettest version )**,

- in **Custom file input** **all work fine in the document** page
https://getbootstrap.com/docs/4.3/components/input-group/#custom-file-input

- but when we **follow given code** it will **not work** to display **uploaded file name**,
  please check the given demo
  https://codepen.io/pcodedviral/pen/Rwwordw

- Give me the solution on how to **display file name using Custom file input**.

Thanks,
Viral Dhimmar

**Comment by sinjuangajan** [comment]
[Check this link](https://stackoverflow.com/questions/48613992/bootstrap-4-file-input-doesnt-show-the-file-name?noredirect=1&lq=1)

**Comment by florianlacreuse** [comment]
As explained in [this part of the documentation](https://getbootstrap.com/docs/4.3/components/forms/#file-browser), it's recommended to use [bs-custom-file-input](https://www.npmjs.com/package/bs-custom-file-input) js plugin to animate custom file input.

**Comment by Johann-S** [comment]
What's @florianlacreuse said 👍
