### ISSUE TITLE
Dark/Light Mode Mixins

### ISSUE THREAD

**Issue by juniorRubyist** [twbs/bootstrap#29551]
I'd like to help push forward with #27514 by implementing a mix-in for dark mode or light mode that can be used by users and throughout the Bootstrap source code. I will file a pull request with my improvements when I'm finished (if this sounds OK).

**Comment by juniorRubyist** [comment]
@piernik I'm simply just writing a mixin for Sass for the media query. If someone wanted to force the theme, they could write the theme as a class and `@extend` it in the `@include dark-scheme {}`.

**Comment by ysds** [comment]
@juniorRubyist I'm not sure your suggestion. Can you create a PR or show demo on https://www.sassmeister.com/ for clarity?

**Comment by juniorRubyist** [comment]
@ysds #29552

**Comment by ysds** [comment]
@juniorRubyist thanks, I missed it
