### ISSUE TITLE
npm package doesn't include `build` directory

### ISSUE THREAD

**Issue by yursha** [twbs/bootstrap#29555]
I installed Bootstrap with `npm install bootstrap` and am trying to recompile it to enable `$enable-responsive-font-sizes` as per official documentation. Running `npm run dist` crashes because `build` directory is not included in the Bootstrap npm package. What is the recommended way of customizing Bootstrap? Should the src code be cloned and then copied to my project's version control repository? This is a bug against either the npm package contents or the official documentation since provided instructions for installation/customization do not play well together.

**Comment by yursha** [comment]
Bootsrap version 4.3.1.

**Comment by XhmikosR** [comment]
Yeah, that's not included on purpose. If you want to develop Bootstrap, you need to clone the repo.
