### ISSUE TITLE
selector-engine.js has issue with findOne. 

### ISSUE THREAD

**Issue by LVDuong** [twbs/bootstrap#29561]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by LVDuong** [comment]
After upgrating bootstrap 3 to bootstrap 4, I has this issue:
![Issue](https://user-images.githubusercontent.com/32818804/67193840-31043180-f420-11e9-9a71-b40d0736cdf8.PNG)
I am using jquery 1.12.1 with project, any can help resolve this problem?
Thanks!

**Comment by Johann-S** [comment]
Hi @LVDuong, you're not using our Bootstrap v4, you're using our next major release (v5) under active development 😆 

To start using our v4 please use: https://getbootstrap.com/docs/4.3/getting-started/introduction/#js

BTW can you share a live reproduction of your bug with our v5? I'm very interested to see what's wrong 👍

**Comment by LVDuong** [comment]
Hi @Johann-S, thanks for your advise. But I use requirejs structure in my project, and I am new with it. I upgrade by replacing my dist file with your dist file, and I add bootstrap: '../lib/bootstrap/dist/js/bootstrap.bundle.min' in requirejs config. Could you help me show the way to use your v4 for my project? 
Thanks so much!

**Comment by LVDuong** [comment]
Hi @Johann-S , sorry for my storage experience. My issue was resolved after I had added your bootstrap.bundle.min.js in v4.
Thanks for your help!
