### ISSUE TITLE
Popover options discarded, offset works on primary axis only

### ISSUE THREAD

**Issue by IGreatlyDislikeJavascript** [twbs/bootstrap#29569]
I've opened this issue in popper.js repo as well, however there is a BS4 specific component.

Issue 1: bootstrap does not pass popover options to popper.js directly. Instead, it reconstructs the options into a new object, and only passes a subset. This renders most popper.js options inaccessible. Bootstrap should pass the complete options object.

Issue 2: using the offset modifier, a popover should be adjustable in both axis. However for some reason it only works on the primary axis.

https://github.com/FezVrasta/popper.js/issues/832

### CodePen demo

https://codepen.io/IGreatlyDislikeJavascript/pen/bGGNgOj

### Steps to reproduce the problem

Popper won't reliably adjust X/Y positioning on both axis, only the primary axis depending on popper placement. 

1.  Simply try to adjust popper position on both axis

### What is the expected behavior?

Ability to adjust in both axis as per docs!

### What went wrong?

Popover doesn't adjust

### Any other comments?

Code is correct because one axis adjustment happens successfully. Using an offset modifier of (for example) `"100px, 200px"` will correctly adjust one axis at a time, but not both. So if the placement is to the left or right of the element, the horizontal offset of 100px will be used but the 200px vertical element ignored. 

If placement is made above or below element, the horizontal offset of 200px has no effect but the vertical offset of 100px is correctly set.

**Comment by Johann-S** [comment]
Hi @IGreatlyDislikeJavascript,

Thanks for your issue 👍 
It's fixed by this PR: https://github.com/twbs/bootstrap/pull/29251

and it'll be available in our next releases

**Comment by IGreatlyDislikeJavascript** [comment]
Thank you. 

For anyone reading this issue, please note there are 2 issues - see the popper.js issue linked in the original post. 

As well as BS4 not exposing the options (fixed as per above post), there is also an issue with popper v1.x that prevents the offset working regardless of option exposure. Fezvrasta has confirmed this will be fixed in popper v2, but as of time of writing this post there is no release date yet.
