### ISSUE TITLE
Dot Leaders

### ISSUE THREAD

**Issue by tony-long** [twbs/bootstrap#29573]
I have some old word docs that I wanted to convert to HTML/CSS using Bootstrap supplied in ASP.NET Core MVC . Many pages with dot leaders and need an easy way to transform these docs.  Don't see support/info in the docs on this so please let me know if the CSS for this exists and how to use it.

**Comment by patrickhlauke** [comment]
for how-to questions, please use StackOverflow or similar. see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker

(and as an aside though, it's not clear what a "dot leader" actually is, so would recommend some further clarity once the question is asked in those places)

**Comment by tony-long** [comment]
It's one of those typography things that go back a hundred or two years ago.   (still used) Thank you for the link - because it is either well hidden or in plain slight, the way to submit a question.
