### ISSUE TITLE
Negative offsets

### ISSUE THREAD

**Issue by Simpleqode** [twbs/bootstrap#29572]
Bootstrap already has negative margin utilities that can be used to customize grid column gutters. However, sometimes  you need to position columns so that they overlapped each other yet took 100% of the `.row` width. Negative offsets might be handy in this case:

```
<div class="container">
    <div class="row">
        <div class="col-12 col-md-5"> ... </div>
        <div class="col-12 col-md-9 offset-md-n2"> ...</div>
    </div>
</div>
```

This might be useful when you want copy to overlap an image to the right or similar cases.

**Comment by mdo** [comment]
With changes to the grid and utilities APIs, I think we'd handle this there where folks can customize and add these types of classes. Thoughts @MartijnCuppens?

**Comment by MartijnCuppens** [comment]
Yeah, something like this should do the trick:
```
$negative-offsets: ();
@for $i from 1 through $columns {
  $negative-offsets: map-merge((n#{$i}: percentage($i / $columns)), $negative-offsets);
}
$utilities: (
  "negative-offsets": (
    property: margin,
    responsive: true,
    class: offset,
    values: $negative-offsets
  )
 );
```

Wouldn't add it by default since it's not worth the additional generated CSS.
