### ISSUE TITLE
Extending Bootstrap documentation english fail

### ISSUE THREAD

**Issue by mrstewar** [twbs/bootstrap#29575]
https://getbootstrap.com/docs/4.3/extend/approach/#html-and-css-over-js

Second paragraph, first sentence.  Seems off to me. :)

"This principle is our first-class JavaScript API is data attributes."

**Comment by MartijnCuppens** [comment]
Duplicate of https://github.com/twbs/bootstrap/issues/29163
Fixed by https://github.com/twbs/bootstrap/pull/29168
