### ISSUE TITLE
box-sing _reboot.scss

### ISSUE THREAD

**Issue by theking2** [twbs/bootstrap#29576]
I search and found a [5 year old issue](https://github.com/twbs/bootstrap/issues/12351) on the box-sizing reset to border-box.  It did refert to https://www.paulirish.com/2012/box-sizing-border-box-ftw/

The current code in bootstrap (4.3.1) is a bit different which potentially clashes with 4-rd party styles;
```
    *,
    *::before,
    *::after {
         box-sizing: border-box; // 1
    }

```
Paul Irish article has been updated since and, for good reason, to a bit different code:
```
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

which yields slightly better compatibility. (see article _update_ 2014)

Would it be possible to update this? Or would it break to much existing code?

**Comment by MartijnCuppens** [comment]
Chrome has an inheritance bug for elements in `details` (see https://github.com/twbs/bootstrap/issues/22872 for more details), that's why we stick to the current implementation.
