### ISSUE TITLE
Problem with navbar animation menu in mozille and opera

### ISSUE THREAD

**Issue by koltonweb** [twbs/bootstrap#29574]
Hello, unfortunately I do not know much English. I am writing this through Google translator. I have a question. Why in the latest bootstrap versions in the mozilla and opera browser the smooth animation of the menu dropout does not work. In all other browsers, everything seems to be fine.

**Comment by MartijnCuppens** [comment]
We use the `prefers-reduced-motion` query to detect wheter the animations should be applied:  https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
