### ISSUE TITLE
Glyphicons or icons or buttons with icons are not working with v4.3?

### ISSUE THREAD

**Issue by nimasdj** [twbs/bootstrap#29582]
Glyphicons or icons or buttons with icons are removed from v4.3? Why I cannot have this with v4.3?
https://codepen.io/danielmariveles/pen/jPrwxv

**Comment by florianlacreuse** [comment]
As specified in the documentation, Bootstrap 4 doesn’t include an icon library by default.

https://getbootstrap.com/docs/4.3/extend/icons/

**Comment by mdo** [comment]
We have a new icon set coming soon as a separate project. Stay tuned for that, but it won't be part of the main project for a few reasons. But they'll be awesome SVGs and open source!
