### ISSUE TITLE
the modal will add the padding to the body?

### ISSUE THREAD

**Issue by lurongjiang** [twbs/bootstrap#29589]
I use a modal for my app,but i found a little case:
when the modal hide,the body's padding add,just like this
---
 before:
![Pa](https://user-images.githubusercontent.com/44705885/67574685-7e103c80-f76d-11e9-93fe-7a0e71ae7ebb.png)

when the modal show,the body attribute padding-right: 17px;,just like this:
![p2](https://user-images.githubusercontent.com/44705885/67574667-76509800-f76d-11e9-8f64-d6a83df012fd.png)

after I click the confirm btn
the padding don't remove

after serveral try,the padding more and more greater.

is it a issue for v3.3.5?

I guess the code maybe:
```javascript
  Modal.prototype.adjustDialog = function () {
    var modalIsOverflowing = this.$element[0].scrollHeight > document.documentElement.clientHeight
    this.$element.css({
      paddingLeft:  !this.bodyIsOverflowing && modalIsOverflowing ? this.scrollbarWidth : '',
      paddingRight: this.bodyIsOverflowing && !modalIsOverflowing ? this.scrollbarWidth : ''
    })
  }
```
I wander to find the this.scrollbarWidth,then the source around here
```javascript
 Modal.prototype.setScrollbar = function () {
    var bodyPad = parseInt((this.$body.css('padding-right') || 0), 10)
    this.originalBodyPad = document.body.style.paddingRight || ''
    if (this.bodyIsOverflowing) this.$body.css('padding-right', bodyPad + this.scrollbarWidth)
  }

```
I can't preview the image ,so sorry

**Comment by XhmikosR** [comment]
3.3.5 is ancient and unsupported. If this happens with v4 or master, comment with a codepen
