### ISSUE TITLE
Typography: <u> should not be used to underline text in HTML5?

### ISSUE THREAD

**Issue by florianlacreuse** [twbs/bootstrap#29584]
According the the HTML5 specs and as explained [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u), `<u>` has been previously deprecated and reintroduced with a new meaning.

> This element used to be called the "Underline" element in older versions of HTML, and is still sometimes misused in this way. To underline text, you should instead apply a style that includes the CSS `text-decoration` property set to **underline**.

However, the BS docs suggests to use `<u>` element to underline text as it's used to be in the past (as I understand it): https://getbootstrap.com/docs/4.3/content/typography/#inline-text-elements

One more thing, from [this ressource from w3](https://www.w3.org/TR/REC-html40/present/graphics.html#h-15.2.1) about `<b>`, `<i>`, etc.:

> The following HTML elements specify font information. Although they are not all deprecated, their use is discouraged in favor of style sheets.

May be BS should at least provide an utility class to underline text? We can already use `.font-weight-bold` instead of `<b>` and `.font-italic` instead of `<i>`.

**Comment by XhmikosR** [comment]
Yeah, I think this would be a good addition. Personally I almost have to use `u`, `b` or `i`

**Comment by XhmikosR** [comment]
Fixed in #29604
