### ISSUE TITLE
Make Card Decks Responsive

### ISSUE THREAD

**Issue by michealjroberts** [twbs/bootstrap#29580]
I would suggest the following changes to the card-decks layout to make it responsive:

```
// Card deck

.card-deck {
  display: flex;
  margin: 0 -$card-deck-margin;
  flex-flow: row wrap;

  .card {
    margin-bottom: $card-deck-margin;
  }

  @include media-breakpoint-down(md) {
    .card {
      flex: 0 0 calc(100%);
    }
  }

  @include media-breakpoint-up(md) {
    .card {
      flex: 0 0 calc(50%);
    }
  }

  @include media-breakpoint-up(lg) {
    .card {
      flex: 0 0 calc(33.33%);
    }
  }
}
```

to _card.scss

Tested on Firefox 70.0b13 (64-bit), Chrome Version 77.0.3865.75 (Official Build) (64-bit) and Safari Version 13.0.2 (15608.2.30.1.1). 

I would open this as a pull request but I am not familiar with the processes needed to fully test amendments to the source code.

**Comment by midzer** [comment]
This issue has been already merged https://github.com/twbs/bootstrap/pull/29073

**Comment by michealjroberts** [comment]
@midzer Awesome. Has it been released into the wild?

**Comment by mdo** [comment]
Yup big upgrades to our grid to allow for responsive cards (and more!).
