### ISSUE TITLE
combining row and table-responsive

### ISSUE THREAD

**Issue by tristenator** [twbs/bootstrap#29596]
hello, i am trying to make a "full page width table" responsive and i'm having some troubles.

i routinely use "row" on the div to ensure the table goes full width (meaning: no padding or margin on the left or right.)

but if i add the class "table-responsive" to the div then the table leaves no gap on the left side of the div (expected) however on the right hand side it leaves a gap between the table and the right hand side of the div (unexpected)

"row": the table stretches all the way from left to right (expected).

```
<div class="row">

	<table class="table table-striped table-hover">

	<thead>
	<tr>
		<th scope="col">A</th>
		<th scope="col">B</th>
		<th scope="col">C</th>
	</tr>
	</thead>

	<tbody>
	<tr>
		<th scope="row">One</td>
		<td>Two</td>
		<td>Three</td>
	</tr>
	</tbody>

	</table>

</div>
```

"table-responsive": the table leaves a gap on the left and right (expected).

```
<div class="table-responsive">

	<table class="table table-striped table-hover">

	<thead>
	<tr>
		<th scope="col">A</th>
		<th scope="col">B</th>
		<th scope="col">C</th>
	</tr>
	</thead>

	<tbody>
	<tr>
		<th scope="row">One</td>
		<td>Two</td>
		<td>Three</td>
	</tr>
	</tbody>

	</table>

</div>
```
"row table-responsive": the table leaves no gap on the left (expected) but leaves a gap on the right (unexpected)

```
<div class="row table-responsive">

	<table class="table table-striped table-hover">

	<thead>
	<tr>
		<th scope="col">A</th>
		<th scope="col">B</th>
		<th scope="col">C</th>
	</tr>
	</thead>

	<tbody>
	<tr>
		<th scope="row">One</td>
		<td>Two</td>
		<td>Three</td>
	</tr>
	</tbody>

	</table>

</div>
```

**Comment by mdo** [comment]
Per our docs, only columns can be immediate children elements of a row. From the looks of it, you likely don’t need the row here at all.
