### ISSUE TITLE
Collapse should animate padding

### ISSUE THREAD

**Issue by inwardmovement** [twbs/bootstrap#29594]
Windows 10 / Firefox 71

Collapse animation is not smooth when a padding (and the likes?) is applied to the collapsible container:
![bs-collapse-padding-60fps](https://user-images.githubusercontent.com/9438102/67617437-72f7f380-f7e3-11e9-9a1a-69a4206eada4.gif)

Suggestion: the collapse animation should animate not only the height but also the container's spacing (padding but also margin? etc.)

I tried
`$transition-collapse: height .35s ease, padding-top .35s ease;`

together with
```
.collapsing {
  position: relative;
  height: 0;
  padding-top: 0;
  overflow: hidden;
  @include transition($transition-collapse);
}
```

but it doesn't change anything, what am I missing?

A workaround I found is to add an extra container inside the `.collapse` and apply the padding to it, but it seems twisted/redundant.

**Comment by mdo** [comment]
This is a constraint of CSS—the padding cannot be transitioned. You’ll need to apply it to an element within the collapsible section.
