### ISSUE TITLE
Add `font-style-normal`

### ISSUE THREAD

**Issue by Simpleqode** [twbs/bootstrap#29590]
When you need to change the font style to italic, you can use `font-italic`. However, sometimes you need to change it back to normal (say all of your `.blockquote`s are italic and you need to make one of them normal). We already have `font-weight` utilities which names start with `font-weight`. Probably `font-style` utilities naming should be corrected as well: 

`font-style-normal`
`font-style-italic`

**Comment by Arvind-Suthar** [comment]
You can simply go and add
.font-normal{
    font-style: normal;
}

**Comment by MartijnCuppens** [comment]
I'm ok with this addition, feel free to open a PR for this.
