### ISSUE TITLE
Select class custom-select deprecation style

### ISSUE THREAD

**Issue by Sin3W** [twbs/bootstrap#29599]
Good day,

In my forms, I have some select tags with class 'custom-select', and I have noticed an alert in my console (Chrome) which contents:

`[Deprecation] '-webkit-appearance: listbox' for elements other than listbox select is deprecated and will be removed in M79, around December 2019. See https://www.chromestatus.com/features/5070237827334144 for more details.`

I have no own styles applied, this means that bootstrap is adding CSS that will be deprectated on Chrome

**Comment by RodionMun** [comment]
Same issue for me with `input[type=date]`

**Comment by acostaf** [comment]
same thing for on with input[type="time"]

**Comment by razh** [comment]
This was already removed in https://github.com/twbs/bootstrap/commit/855d763ae57fd1dea1c26af1f197d3d84002dc55#diff-7f9eec82312835f6155c8de839bf0e49L423 as part of https://github.com/twbs/bootstrap/pull/28917.

**Comment by frederikhors** [comment]
https://github.com/twbs/bootstrap/pull/28917 has the tag "NO BACKPORT TO v4".

I think we should backport it in a 4 patch release, right?

**Comment by MartijnCuppens** [comment]
Correct, feel free to open a pull request

**Comment by mdo** [comment]
This was addressed in v4.5.0 with #30353.
