### ISSUE TITLE
IE 10/11/Edge custom control indicators in a parent element with column-count do not render on the last column

### ISSUE THREAD

**Issue by mattywong** [twbs/bootstrap#29607]
- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
**Windows 10**
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Reproduced on **IE Edge, IE 11 and IE 10**
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Screenshot of issue:**
![ie-custom-control](https://user-images.githubusercontent.com/1550219/67825996-10199b80-fb06-11e9-85c5-861ea9359372.png)

**Codepen reproduction:**
https://codepen.io/mattywong/full/NWWajYJ

Seems like the fix is to create a new stacking context on custom-control to get it rendering correctly (ideally z-index, though transform and opacity will also create a new stacking context).

**Comment by mdo** [comment]
Confirmed this is an issue, and that `z-index: 1` on the `.custom-check` resolves the issue. Unsure what other potential problems that introduces though.

**Comment by XhmikosR** [comment]
Fixed in #30810
