### ISSUE TITLE
Inputs in modal not working

### ISSUE THREAD

**Issue by tamimibrahim17** [twbs/bootstrap#29608]
When a bootstrap modal initiate from a Jquery-ui dialog modal, all input type text / textarea within bootstrap modal are not editable/focusable. Here is an example of this problem. I have tried changing z-index value of both modal but it did not worked.

https://codepen.io/tamimibrahim17/pen/RwwLZeK

**Comment by herbalite** [comment]
In the code snippet below set modal to false.

It seems a bit counter intuitive when reading the jquery-ui documentation, but works for me with all the latest library versions.


	    $("#eventContent").dialog({ 
	        modal: false, 
	        title: 'some title', 
	        width:550, 
	        clickOutside: true
	    });

**Comment by tamimibrahim17** [comment]
Thanks @herbalite, after set modal to false, it's working.
