### ISSUE TITLE
Nested elements in popover won't work

### ISSUE THREAD

**Issue by moeen** [twbs/bootstrap#29613]
Since the 4.3.1, I can not use nested elements such as tables in bootstrap popovers.

See the example:
https://codepen.io/moeinroid/pen/xxxXyqV

**Comment by Johann-S** [comment]
Hi @moeen,

You'll find why in those links:
- https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
- https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
- https://getbootstrap.com/docs/4.3/components/popovers/#options
