### ISSUE TITLE
Documentation/Proposal: change/add non-equal width examples to flex

### ISSUE THREAD

**Issue by birdspider** [twbs/bootstrap#29614]
_I had a nice issue description before github/related issues-beta ate it, here's the gist:_

https://getbootstrap.com/docs/4.3/utilities/flex/#justify-content

The  flex justify documentation examples only display equal-width items (`<div>Flex Item</div>`). 
It might be wise to add one or two examples with non-equal-width divs and more than 3 cols.

Specifically to illustrate that the middle item is _not_ necessarily centered.

confused user in the wild: https://stackoverflow.com/questions/58647355/bootstrap-4-justify-space-around-and-justify-content-center-not-lining-up

**Comment by MartijnCuppens** [comment]
Feel free to open a PR for this, the file you'll need to adjust is located here: https://github.com/twbs/bootstrap/blob/master/site/content/docs/4.3/utilities/flex.md

**Comment by mdo** [comment]
Inclined to leave this as-is unless someone else wants to submit a PR with small changes. The goal of those examples is to show alignment across all viewports, so making them wider and more varied could also introduce other issues. The linked SO post also has some issues with utility overload and HTML issues. While Bootstrap helps in a lot of ways, folks will always find a way to do something unexpected or invalid :).
