### ISSUE TITLE
Not able to change order of items of a map in scss variables

### ISSUE THREAD

**Issue by Dassderdie** [twbs/bootstrap#29616]
It is currently not possible to change the order in e.g. the `$theme-colors` map. The order is important if e.g. a card has both `.border-info` and `.border-warning`  and you want the info class to be applied instead of the warning one. This comes more into play if you add a custom theme-color.

One possible solution I could think of is instead of:
```
$theme-colors: map-merge(
  (
    "primary":    $primary,
    "secondary":  $secondary,
    "success":    $success,
    "info":       $info,
    "warning":    $warning,
    "danger":     $danger,
    "light":      $light,
    "dark":       $dark
  ),
  $theme-colors
);
```
this:
```
$theme-colors: map-merge(
  $theme-colors,
  (
    "primary":    $primary,
    "secondary":  $secondary,
    "success":    $success,
    "info":       $info,
    "warning":    $warning,
    "danger":     $danger,
    "light":      $light,
    "dark":       $dark
  )
);
```

This would introduce a breaking change.

**Comment by MartijnCuppens** [comment]
> The order is important if e.g. a card has both .border-info and .border-warning and you want the info class to be applied instead of the warning one. 

You should avoid this, it doesn't make sense to add multiple utility classes which target the same property.

The solution you're proposing won't override the default colors.

For the next major version, we're thinking about removing the map merges (see https://github.com/twbs/bootstrap/pull/28508).

For now, you could define/override your `$theme-colors` after the variables inclusion. See https://getbootstrap.com/docs/4.3/getting-started/theming/#remove-from-map.

**Comment by ysds** [comment]
Closing per last comment.
