### ISSUE TITLE
Issue about #29544 backport to v4 docs

### ISSUE THREAD

**Issue by PerseusTheGreat** [twbs/bootstrap#29637]
Hi.
Recently, you have shipped [#29544](https://github.com/twbs/bootstrap/pull/29544) and have backported it to v4.x documentations in project [v4.4.0](https://github.com/twbs/bootstrap/projects/18).

In file `/site/_includes/docs-navbar.html`, at **line 18**, the expression `{{ .Site.Params.icons }}/` does not generate correct `href` for new **icons** hyperlink in navigation bar of v4.x docs.
It should be `{{ site.icons }}/`.
So. please consider it.

To ensure, get and build [my forked repo](https://github.com/PerseusTheGreat/bootstrap-4-rtl).

**Comment by XhmikosR** [comment]
Thanks, it's fixed in #29623
