### ISSUE TITLE
Dark theme for pagination

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [twbs/bootstrap#29635]
Hi, Many components of Bootstrap has both light and dark theme,
I found Pagination component does not have dark theme variant.
Please make Pagination component compatible with dark colors.

![Screenshot from 2019-11-04 15-08-10](https://user-images.githubusercontent.com/17345129/68118332-f799ee80-ff14-11e9-919a-6e38ef7be6da.png)

**Comment by Arvind-Suthar** [comment]
You can try making one yourself and making a pull request

**Comment by aapljack** [comment]
I would like to take this on if it hasn't been started yet.

**Comment by AmirHosseinKarimi** [comment]
@aapljack Good news! I did not work on this.

**Comment by RaquelAM** [comment]
Hi!
Did anyone work on this or can I take it?

**Comment by AmirHosseinKarimi** [comment]
@RaquelAM Hi, Looks like no.

**Comment by RaquelAM** [comment]
@AmirHosseinKarimi  ok, I will work on this
Thanks!

**Comment by aapljack** [comment]
@RaquelAM I have started on this feature, but do not have a PR ready yet.

**Comment by RaquelAM** [comment]
@aapljack Oh! I'm so sorry but I solved the issue, I will send the PR to verify my solution, you could do that too, best wishes

**Comment by aapljack** [comment]
@RaquelAM No worries. I took a slightly different approach with the colors and hover states so I went ahead and submitted my PR also. Sorry for the confusion. I had only started to work on this last night. :)

**Comment by aapljack** [comment]
#29893

**Comment by MartijnCuppens** [comment]
Closing this for now. In the future we'll have a look at providing a solution for all components, but let's wait until we drop IE support and be able to use CSS custom properties.

**Comment by chrisluedtke** [comment]
also hoping for a `class="pagination-primary"` `class="pagination-secondary"` etc.

**Comment by danger89** [comment]
Or `paginationdark`
