### ISSUE TITLE
Weird bug with modal

### ISSUE THREAD

**Issue by julesbl** [twbs/bootstrap#29645]
Hi

Pixel 2, Android 10, Firefox Mobile 68.2.0

I'm very puzzled by this one, the problem only occurs in firefox mobile on one page, I've looked for any fault in the page html, there are no errors being thrown by the JavaScript.

https://w34u.com/portfolio

Click on the See more... in portrait orientation displays the modal with the correct content but incorrectly formatted, has not adjusted to the screen width etc. and you cannot close the modal using the close window icon or the close button at the bottom. If you change the orientation to landscape it works properly.

This routine works properly on the home page.

Jules

![Screenshot_20191106-155214](https://user-images.githubusercontent.com/1729463/68315845-521b8200-00b0-11ea-9e9c-bf5daf3909b8.png)
![Screenshot_20191106-155627](https://user-images.githubusercontent.com/1729463/68315855-5778cc80-00b0-11ea-9508-dfe85fea6106.png)

**Comment by MartijnCuppens** [comment]
The `.img-fluid` class is not added on the content you're loading by default: https://w34u.com/popup/ssp

**Comment by julesbl** [comment]
Yes the .img-fluid is being added to the image by JavaScript, I have checked, the modal just seems totally broken in this situation, won't close etc.
