### ISSUE TITLE
Shorthand for spacing utilities

### ISSUE THREAD

**Issue by rmgreenstreet** [twbs/bootstrap#29655]
https://getbootstrap.com/docs/4.3/utilities/spacing/#notation

It would make me really happy if there could be a shorthand notation for the `p` and `m` classes, as far as responsiveness/breakpoints.

Currently, you have to set a class with which side(s), which breakpoint, and then the value for each padding/margin style.

It would be great to have the option of something like:

`{property}{sides}-{xl size}-{lg size}-{md size}-{sm size}-{xs-size}`

so for example:

`mx-5-4-3-2-0`

That may be a lot of work for a little return (`5!` different classes/cases), but I think could it save a lot of time while coding versus

`mx-xl-5 mx-lg-4 mx-md-3 mx-sm-2 mx-0`

Or maybe I'm just lazy!

**Comment by florianlacreuse** [comment]
Just my opinion: I find it harder to read than the current one. Also, it will increase the size of the generated css file. And last, it wouldn't be consistent with other css classes like `col{breakpoint}-{size}`, etc.

**Comment by mdo** [comment]
Laziness isn't a bad thing haha, but I think this is less clear. Keeping it as-is for now :).
