### ISSUE TITLE
Bootstrap 4.3.1 card-body error

### ISSUE THREAD

**Issue by FabioAdorno** [twbs/bootstrap#29659]
Please check padding option of this class. I think that has an error

**Comment by florianlacreuse** [comment]
I don't understand, can you tell us more and provide a reduced test case for the issue? Thanks.

**Comment by FabioAdorno** [comment]
I think that has a problem on bootstrap-4.3.1.min.css on card-body class

See attached




Regards,

Fabio Adorno

**Comment by florianlacreuse** [comment]
Padding is `1.25rem` as it should be. Am I missing something?

**Comment by FabioAdorno** [comment]
OK. Thank You
