### ISSUE TITLE
Tables in modal windows overrun the page when table data is long

### ISSUE THREAD

**Issue by ar613** [twbs/bootstrap#29652]
- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile): Windows 10
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser): Chrome/Firefox
- Bootstrap version: 4.3.1

Tables in modal windows overrun the page when table data is long. The table doesn't appear to know it's in a modal.
![image](https://user-images.githubusercontent.com/17624776/68401056-12ec4000-0147-11ea-83c9-0ad60c042a2a.png)

**Comment by neralex** [comment]
I'd say it's normal behavior. Single words usually do not have such long strings. But if you expect such long strings in your output, you can assign the class .text-break to the td-tags. But to break all strings by default inside a modal could probably cause other issues.

https://getbootstrap.com/docs/4.3/utilities/text/#word-break

**Comment by ar613** [comment]
Thank you, that works. I think the correct behaviour should be the table scrolls horizontally when the contents exceed the modal width though.

**Comment by neralex** [comment]
Maybe this should do the trick for you.

https://getbootstrap.com/docs/4.3/content/tables/#responsive-tables

**Comment by mdo** [comment]
Yeah, you'll need to opt into that behavior. We try to limit resets of global elements in other components.

**Comment by ar613** [comment]
That works, thank you!
