### ISSUE TITLE
Navbar documenation demos appear to be broken

### ISSUE THREAD

**Issue by themacleod** [twbs/bootstrap#29669]
Hi there, appologies if this is not the correct forum, but the navbar examples on your webpage seem to not be displaying the toggle icon. 

https://getbootstrap.com/docs/4.3/components/navbar/

**Comment by redPhyco** [comment]
They didn't complete any demo. Even bootstrap 3 demo files are also altered. I can't find any working bootstrap demos anywhere.

**Comment by peterblazejewicz** [comment]
@themacleod 
One need to look at the page at the specific viewport, as these are behind breakpoints. You should see something like really:

![image](https://user-images.githubusercontent.com/14539/69013328-21c0c700-097f-11ea-97f7-62ce27af2aa5.png)

So was this a question why these are not visible or request, to override the default breakpoints and present toggles without depending on viewport size?

**Comment by themacleod** [comment]
Many thanks for the reply. Indeed you are correct, this was simply not viewing the collapsible elements from the correct view port.
