### ISSUE TITLE
"d-none d-lg-block d-flex flex-column-reverse" doesn't work

### ISSUE THREAD

**Issue by jameskentTX** [twbs/bootstrap#29668]
Debian, chrome, Angular 8, Bootstrap 4.3.1 (css only)
(ng-bootstrap installed too).

If you **combine** d-flex with visibility classes, it won't work. For example:

```
<div class="d-none d-lg-block d-flex flex-column-reverse">
  <div class="p-2">Flex item 1</div>
  <div class="p-2">Flex item 2</div>
  <div class="p-2">Flex item 3...</div>
</div>
```

It doesn't work!
Flex doesn't work, because on bigger screens items are NOT reversed, visibility classes doesn't work because items are visible even on small screen.

If flex is not combined with visibility classes, everything is working fine:

```
<div class="d-none d-lg-block">
  <div class="d-flex flex-column-reverse">
    <div class="p-2">Flex item 1</div>
    <div class="p-2">Flex item 2</div>
    <div class="p-2">Flex item 3...</div>
  </div>
</div>
```

That code is working fine.

**Comment by ffoodd** [comment]
Hi @jameskentTX ,

You probably should use `d-lg-flex` instead of `d-lg-block`, I guess:

`<div class="d-none d-lg-flex flex-column-reverse">`

Could you try?

**Comment by jameskentTX** [comment]
Yep, `<div class="d-none d-lg-flex flex-column-reverse">`  it works. Thank you.
