### ISSUE TITLE
Modals shouldn't ignore calls to hide/show while transitioning

### ISSUE THREAD

**Issue by opennota** [twbs/bootstrap#29674]
Modals return early from hide/show methods while in the transitioning state:
https://github.com/twbs/bootstrap/blob/a7e920baffc442f915dcba1a052ffa317c43109d/js/src/modal.js#L170-L172

This means that the close button won't work in this state:
https://codepen.io/opennota/pen/vYYQBVd
Here the close button is clicked, but the modal doesn't close, unless you change the timeout to e.g. 1000 (1 second).

This also means that if you add an event listener to a button and in this listener try to close the modal, it won't:

https://codepen.io/opennota/pen/VwwVZOQ

I suggest that modals should save these calls and replay them later, after the transition is complete.

**Comment by marchershey** [comment]
@opennota Could this work in your situation?

``` javascript
document.addEventListener('DOMContentLoaded', () => {
  document.querySelector('.button-trigger-modal').click();
  $('#exampleModal').on('shown.bs.modal', function (e) {
    $('#exampleModal').modal('hide'); 
  }); 
});
```

https://codepen.io/marchershey/pen/zYYMBZz

**Comment by opennota** [comment]
@marchershey 

The modal can be already shown, so you need to make *two* calls:

```
document.addEventListener('DOMContentLoaded', () => {
  document.querySelector('.button-trigger-modal').click();
  $('#exampleModal').modal('hide'); 
  $('#exampleModal').on('shown.bs.modal', function (e) {
    $('#exampleModal').modal('hide'); 
  }); 
});
```

I'd rather not.

**Comment by Johann-S** [comment]
Hi @opennota like that it works well: https://codepen.io/Johann-S/pen/MWYpgVM

And if you want to prevent the opening of a modal, just list to `show.bs.modal` and call event.preventDefault()

**Comment by DLLluoluo** [comment]
$scope.exportLicense = function () {
if(typeof ($scope.licenseData.selected) == 'undefined' && $scope.licenseData.selected == null) {
return false;
}
$('#progress').modal('show');
var params = $scope.licenseData.selected;

        cfgLicenseMgmtService.exportBy(params)
            .then(function (dataObject) {
                $('#progress').modal('hide');
                var data = dataObject["data"];
                if(0 == data['return']) {
                    $scope.licenseData.exportFileName = data.FileName;
                    commonService.downloadFile('/download/'+data['FileName'], data['FileName']);
                } else {
                    commonService.popUpErrBox($translate.instant('xccErrMsg_LICENSED_export'));
                }
            },function (data) {
                commonService.popUpErrBox($translate.instant('xccErrMsg_LICENSED_export'));
            });
    };

The above method is an operation to export the license. When the user clicks the export button, a "#progress" modal box will pop up. After the background data is returned correctly, the "#progress" modal box will be hidden. This code works fine in bootstrap 3.4.1, but the #progress "modal box is not hidden in bootstrap 4.4.1, and $ ('# progress'). Modal ('hide') seems to be invalid. This caused the problem What is the reason and is there a solution?

**Comment by DLLluoluo** [comment]
setTimeout（function（）{
        $（'＃progress'）。modal（'hide'）;
 }，1000）


If you add a 1 second delay, the modal box can be hidden normally. There are multiple uses of the .modal ('hide') method in our project; is there a new solution? thanks.
