### ISSUE TITLE
Front page BootstrapCDN section still points at jQuery 3.3.1

### ISSUE THREAD

**Issue by alimony** [twbs/bootstrap#29672]
The [Bootstrap front page](https://getbootstrap.com/) has a BootstrapCDN section that points at an old version of jQuery, that among other things causes a security warning in Lighthouse.

This is a content issue and is therefore valid regardless of browser etc.

**Comment by MartijnCuppens** [comment]
This will be updated when we release the next minor:
https://github.com/twbs/bootstrap/blob/6b7ca1234bb5c699804d09126585f317000d1c78/_config.yml#L59
