### ISSUE TITLE
Weird bug with modal

### ISSUE THREAD

**Issue by julesbl** [twbs/bootstrap#29671]
Hi

Sorry to post this again, but this does not work, cant find any javascript or html errors, the image has the correct class on it, img-fluid, and it works on the home page.

Pixel 2, Android 10, Firefox Mobile 68.2.0

I'm very puzzled by this one, the problem only occurs in firefox mobile on one page, I've looked for any fault in the page html, there are no errors being thrown by the JavaScript.

https://w34u.com/portfolio

Click on the See more... in portrait orientation displays the modal with the correct content but incorrectly formatted, has not adjusted to the screen width etc. and you cannot close the modal using the close window icon or the close button at the bottom. If you change the orientation to landscape it works properly.

This routine works properly on the home page.
https://w34u.com

Jules

**Comment by neralex** [comment]
Your issue is not based on Bootstrap, it is based on a long string in one of your headlines, which is moving the main-container to the right.  "Content capsule - Content **marketing/communications** platform" Add a space bettween "markting/" and "communications".

**Comment by julesbl** [comment]
Thanks
