### ISSUE TITLE
breadcrumb spacing still an issue

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#29689]
Breadcrumb spacing with whitespace is still an issue. Please either reopen #17473 or track here.

Thanks

**Comment by mdo** [comment]
Breadcrumbs are built with flexbox and shouldn't be picking up whitespace. Without a new live demo to reproduce, I'm closing this for now.

**Comment by 719media** [comment]
@mdo 

he live demo was at the end of the above-linked issue. This is happening in v4.3.1

Here it is:

https://codepen.io/francescomazzurco/pen/BaazRLY

**Comment by mdo** [comment]
Ah sorry about that. Looking at this particular behavior, I don't know how we could fix it off the top of my head. Reformatting the HTML is an easy fix, but that's also not an acceptable answer.

**Comment by ffoodd** [comment]
Hey there,

FWIW, simply adding `d-inline-flex` utility on your active breadcrumb item solves this. So I guess it's safe to add `display: inline-flex` to `.breadcrumb-item`, isn't it?

**Comment by MartijnCuppens** [comment]
Adding `display: inline-flex` will indeed fix this. Maybe we can just use `display: flex` since the `inline` part is moot because `.breadcrumb` already has `display: flex` applied to.

We should add this by default to our `.breadcrumb-item`, feel free to open a PR for this.

**Comment by ffoodd** [comment]
@MartijnCuppens Does this need to be done in V5, or V4 — maybe both? I'd be pleased to open dedicated PR if it can help.

**Comment by MartijnCuppens** [comment]
![Why not both?](https://media.giphy.com/media/3o85xIO33l7RlmLR4I/source.gif)

Both is fine, just open a PR for `master` and we'll cherry-pick this in `v4`.
