### ISSUE TITLE
should be able to apply table-sm only on small screens

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#29683]
We'd like to apply ```table-sm``` class, which makes tables more compact, only on small screens.

The solution should be similar to ```.table-responsive{-sm|-md|-lg|-xl}``` : have a responsive class
```.table-compact{-sm|-md|-lg|-xl}```

Thanks

**Comment by mdo** [comment]
I don’t think we’ll be doing this at this time. Thanks for the idea though, I’ll keep an eye out for more folks who may ask about this.
