### ISSUE TITLE
Reauthorize my commits

### ISSUE THREAD

**Issue by zdroid** [twbs/bootstrap#29685]
My old commits are not authorized properly due to an email change. Is it possible to fix this issue? I had ~200 pull requests, most of them merged, and was among the top contributors.

[There](https://github.com/zdroid/dotfiles/blob/master/git/bin/author-rewrite)'s a script with a possible fix. Old email is legospace9876@gmail.com (deleted), new one is the one on my profile.

**Comment by XhmikosR** [comment]
Sorry, that is a destructive operation. You could provide a PR with the .mailmap approach and we can review that.

**Comment by zdroid** [comment]
@XhmikosR does `.mailmap` group commits under GitHub contributors tab too?

**Comment by XhmikosR** [comment]
No idea, but GH should respect the file.

**Comment by zdroid** [comment]
Okay, I understood. The syntax would be:
`<zlatanvasovic@gmail.com> <legospace9876@gmail.com>`

Now the question is, is it fine with other maintainers of the repository to add another file in the main directory of the repository?
