### ISSUE TITLE
Looks like RTL languages use the same progress bar as LTR languages

### ISSUE THREAD

**Issue by DmitriyIvanko** [twbs/bootstrap#29680]
Looks like RTL languages use the same progress bar as LTR languages:
https://ar.wikipedia.org/wiki/%D8%B4%D8%B1%D9%8A%D8%B7_%D8%A7%D9%84%D8%AA%D9%82%D8%AF%D9%85
You can improve ths component: https://getbootstrap.com/docs/4.3/components/progress/

**Comment by mdo** [comment]
We don’t support RTL yet.
