### ISSUE TITLE
Viewport height classes should include all percentage heights

### ISSUE THREAD

**Issue by Soviut** [twbs/bootstrap#29697]
Before opening:

Feature requests must include:

Currently, the `h-` height classes include `h-25`, `h-50`, `h-75`, `h-100`. However, the related `vh-` viewport height class only includes `vh-100` and `min-vh-100`.

https://github.com/twbs/bootstrap/blob/master/scss/_utilities.scss#L125

https://github.com/twbs/bootstrap/blob/cc6f66f72a180af1910bb5f520f2067ad705f1b8/dist/css/bootstrap.css#L6084

I propose that all height percentage classes be normalized to use all the common sizes.

**Comment by MartijnCuppens** [comment]
> all the common sizes

These "common sizes" can differ for each project and that's why we decided to move to a Sass-based [Utility API](https://twbs-bootstrap.netlify.com/docs/4.3/utilities/api/) in `v5` where you'll have more control over which classes are generated.

**Comment by danihodovic** [comment]
@MartijnCuppens the link is broken

**Comment by MartijnCuppens** [comment]
https://twbs-bootstrap.netlify.app/docs/5.0/utilities/api/
