### ISSUE TITLE
Sidebar navigation

### ISSUE THREAD

**Issue by boniface193** [twbs/bootstrap#29694]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by boniface193** [comment]
A lightweight JavaScript & CSS based side navigation which allows to toggle an Android-style off-canvas navigation by clicking on the toggle icon or swiping the screen right/left on touch devices. this will allow and easy mobile first development. if this will be considered,  in the next update, i am very sure that a lot of developers will be willing to see a bootstrap sidebar toggle navigation for small devices. looking at the initial topbar for bootstrap i personally don't use it in some occasion i tried using, but when i tested it on a smaller device it occupied almost everywhere until i added my custom style to it. thanks

**Comment by MartijnCuppens** [comment]
There's a offcanvas component which is currently in development: https://github.com/twbs/bootstrap/pull/29017
