### ISSUE TITLE
Add additional test to to check if dart Sass or node-sass with compressed output are still working

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29701]
We only test for the `expanded` output style, but the compressed style could potentially break things.

We should also add tests for Dart Sass.

First step is to just check if compilation works, but we might also check if the output is the same (this can get tricky since the output ain't always the same, and I thought the way Dart Sass and lib sass handle `@extend`s is different).

**Comment by XhmikosR** [comment]
I don't think it's our job to catch such issues, though. I mean, if it's a compiler bug, that's the place they test such things.

**Comment by MartijnCuppens** [comment]
Agreed.

Closing this, since we have tests for Sass and node sass in the meantime
