### ISSUE TITLE
Modal backdrop inconsistent 

### ISSUE THREAD

**Issue by flightltd** [twbs/bootstrap#29703]
Bootstrap v3.3.7:

I suppress the backdrop on all modals but it sometimes appears for no apparent reason and then persists on all subsequent modals even though backdrop is set to false on all of them. Reloading the page clears the problem.

**Comment by florianlacreuse** [comment]
Could you provide a reduced test case?

Also, just for information, [Boostrap 3 has moved to end of life](https://blog.getbootstrap.com/2019/07/24/lts-plan/) 4 months ago.

**Comment by flightltd** [comment]
Hi, thanks for getting in touch. Providing a reduced test case would be difficult as it's a very big system and it's difficult to know where to look. I have performed a string search though on the only file (app.js) that contains modal instructions and these are the results:

Three instances of "modal({" all with "backdrop: false". One of these is the function showModal which is then called 119 times.

`function showModal(modalName, userKeyboard) {

	$('#' + modalName + 'Modal').modal({backdrop: false, keyboard: userKeyboard});

}`

There are also 56 invocations of BootBox.js all of which have the parameter "backdrop" set to false.

Moving to Bootstrap 4 is on the to do list but I doubt that it would be plug and play and would require a lot of testing.

**Comment by flightltd** [comment]
Update - there were three instances of showModal() that didn't include the second parameter. Do you think that this would invalidate the backdrop parameter as well? Probably. Thank you so much for taking the time to address my question and forcing me to perform a proper audit.

Cheer,

Paddy

**Comment by florianlacreuse** [comment]
As said in [the bug reports guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#bug-reports), provide a reduced test case help you to **isolate the issue** and a live example is really helpful for us. May be someone will be able to help you without it but I can't sorry. Good luck!

**Comment by raxraj** [comment]
hEY! You have to send in some Example! What exactly are you referencing
