### ISSUE TITLE
A lot of broken links (404) found on a website

### ISSUE THREAD

**Issue by tigranbs** [twbs/bootstrap#29715]
Tested website getbootstrap.com with website analyzer and seems the official website has a lot of broken links, it is very recommended to be fixed!
https://hexometer.com/broken-links/getbootstrap.com

- Operating system **All**
- Browsers **All**

Can make a PR if that's OK.

**Comment by MartijnCuppens** [comment]
> Can make a PR if that's OK.

Sure, go ahead! 😃

@XhmikosR, didn't we have tools to check this?

**Comment by XhmikosR** [comment]
We already aware of these, and yes, we do have a tool which checks the internal links only.

For external links I have [a branch](https://github.com/twbs/bootstrap/compare/master-xmr-linkinator-prod) that I run from time to time.

As for the tool you link to, it seems it has issues with relative URLs.
