### ISSUE TITLE
Tooltip Color Property

### ISSUE THREAD

**Issue by joshua-noronha13** [twbs/bootstrap#29718]
Currently, its really hard to implement a fool-proof responsive colored tooltip, we can try giving it some custom CSS but the problem is that when you change the view of the screen the color of the bottom arrow changes because the tooltip orientation changes. I have provided a screenshot of the same .
![1](https://user-images.githubusercontent.com/26717735/69479965-63db8400-0e29-11ea-8fb9-96b5d73bc8f1.png)
![2](https://user-images.githubusercontent.com/26717735/69479967-63db8400-0e29-11ea-8c12-4ab07d38e2f2.png)

**Comment by MartijnCuppens** [comment]
By just changing `$tooltip-bg` in Sass, the background and arrow colors can be changed.
