### ISSUE TITLE
.table-responsive is not compatible with Chinese.

### ISSUE THREAD

**Issue by cn-ray-o** [twbs/bootstrap#29722]
![QQ截图20191125084529](https://user-images.githubusercontent.com/51994475/69504680-05fd8800-0f60-11ea-8702-7566bd5fd349.png)

**Comment by ysds** [comment]
That is not just Chinese, but expected behavior. If you want to control wrapping text, consider using `text-nowrap` class etc.

![image](https://user-images.githubusercontent.com/4065765/69744242-278a8980-1183-11ea-831e-42e4ccba4016.png)
