### ISSUE TITLE
Support for dark mode on documentation pages

### ISSUE THREAD

**Issue by donhuvy** [twbs/bootstrap#29720]
Please has dark mode for document page at here 

https://getbootstrap.com/docs/

https://getbootstrap.com/docs/4.3/getting-started/introduction/

(Dark mode at this site https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.0&tabs=windows is a good example.)

**Comment by hectorbus** [comment]
This issue seems to be the same from this drafted pull request #28449

**Comment by ThisGitHubUsernameWasAvailable** [comment]
Related issue: https://github.com/twbs/bootstrap/issues/27514
