### ISSUE TITLE
Check/radio doesn't consider disabled fieldset 

### ISSUE THREAD

**Issue by jeromelebleu** [twbs/bootstrap#29739]
As disabled attribute is used instead of :disabled pseudo-class, check/radio inputs are not rendered as disabled when they are contained in a disabled fieldset (see: https://jsfiddle.net/o17mLfda/1/).

**Comment by ysds** [comment]
v4 demo https://jsbin.com/yibalokuqu/1/edit?html,css,js,output

**Comment by mdo** [comment]
Closing as associated PR was merged and shipped with v4.4.1.

**Comment by ysds** [comment]
Still open for v5 #29740
