### ISSUE TITLE
Algolia search isn't working in v4.4.0 documentation

### ISSUE THREAD

**Issue by humayunkabir** [twbs/bootstrap#29748]
- Operating system [macOS] and version [iMac (21.5-inch, Mid 2011)]
- Browser and version [Chrome, Firefox, Safari, Brave]

![Screen Shot 2019-11-27 at 3 01 37 PM](https://user-images.githubusercontent.com/11034890/69709094-faa88900-1126-11ea-8b2f-3d99ec0a58ed.png)

**Comment by XhmikosR** [comment]
It's fixed now.
