### ISSUE TITLE
Card Deck row-cols-sm1

### ISSUE THREAD

**Issue by wilecoyte78** [twbs/bootstrap#29742]
win 10, Chrome

When screen is in the small range it shows 3 columns when it is supposed to show 1 column

The reason this happens is because the flex property is not being overwritten by the row-cols- flex properties:

    @media (min-width: 576px) {
        .card-deck .card {
            flex: 1 0 0%;
            margin-right: 15px;
            margin-bottom: 0;
            margin-left: 15px;
        }
    }

Here is my html I used:

	<div class="card-deck row-cols-sm-1 row-cols-md-3 row-cols-lg-3 row-cols-xl-4">
		<div class="card">
			<svg aria-label="Placeholder: Image cap" class="bd-placeholder-img card-img-top" height="180" preserveaspectratio="xMidYMid slice" role="img" width="100%" xmlns="http://www.w3.org/2000/svg">
			<title>Placeholder</title>
			<rect fill="#868e96" height="100%" width="100%"></rect>
			<text dy=".3em" fill="#dee2e6" x="50%" y="50%">
				Image cap
			</text></svg>
			<div class="card-body">
				<h5 class="card-title">Card title</h5>
				<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
			</div>
			<div class="card-footer">
				<small class="text-muted">Last updated 3 mins ago</small>
			</div>
		</div>
		<div class="card">
			<svg aria-label="Placeholder: Image cap" class="bd-placeholder-img card-img-top" height="180" preserveaspectratio="xMidYMid slice" role="img" width="100%" xmlns="http://www.w3.org/2000/svg">
			<title>Placeholder</title>
			<rect fill="#868e96" height="100%" width="100%"></rect>
			<text dy=".3em" fill="#dee2e6" x="50%" y="50%">
				Image cap
			</text></svg>
			<div class="card-body">
				<h5 class="card-title">Card title</h5>
				<p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
			</div>
			<div class="card-footer">
				<small class="text-muted">Last updated 3 mins ago</small>
			</div>
		</div>
		<div class="card">
			<svg aria-label="Placeholder: Image cap" class="bd-placeholder-img card-img-top" height="180" preserveaspectratio="xMidYMid slice" role="img" width="100%" xmlns="http://www.w3.org/2000/svg">
			<title>Placeholder</title>
			<rect fill="#868e96" height="100%" width="100%"></rect>
			<text dy=".3em" fill="#dee2e6" x="50%" y="50%">
				Image cap
			</text></svg>
			<div class="card-body">
				<h5 class="card-title">Card title</h5>
				<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
			</div>
			<div class="card-footer">
				<small class="text-muted">Last updated 3 mins ago</small>
			</div>
		</div>
	</div>

**Comment by wilecoyte78** [comment]
I created a fix for this:

    @mixin row-cols($count) {
      & > * {
        $percent: 100% / $count;
        $margin: $card-deck-margin * 2;
        flex: 0 0 calc( #{$num} - #{$margin} ) !important;
        max-width: 100% / $count;
      }
    }

**Comment by mdo** [comment]
You need to wrap the cards in another layer unfortunately. This was the best way to implement a grid enhancement and not something that was super focused on the card component itself. Check the docs once more for an example, please.

**Comment by wilecoyte78** [comment]
Ok the problem with it is that the cards are no longer the same height

**Comment by wilecoyte78** [comment]
So I did this:

I added to .card-deck in _card.scss:

      @each $breakpoint in map-keys($grid-breakpoints) {
        $infix: breakpoint-infix($breakpoint, $grid-breakpoints);
        @include media-breakpoint-up($breakpoint, $grid-breakpoints) {
          @for $i from 1 through $grid-row-columns {
            &.row-cols#{$infix}-#{$i} {
              @include row-cols($i,$card-deck-margin);
            }
          }
        }
      }

and in _grid.scss

    @mixin row-cols($count,$px: 0) {
      & > * {
        $percent: 100% / $count;
        $margin: $px * 2;
        @if $px == 0 {
          flex: 0 0 #{$percent} !important;
        } @else {
          flex: 0 0 calc( #{$percent} - #{$margin} ) !important;
        }
        max-width: 100% / $count;
      }
    }

**Comment by wilecoyte78** [comment]
http://x-v.it/z4fdvn

**Comment by wilecoyte78** [comment]
The top section is my HTML and new SCSS
The bottom is the section in your docs.
