### ISSUE TITLE
import using /deep/ keyword error!!

### ISSUE THREAD

**Issue by kiss9815** [twbs/bootstrap#29746]
I use bootstrap scoply
like this.
```html
<style scoped lang="scss">
    .bootstrapWrapper /deep/ {
      @import "node_modules/bootstrap/scss/bootstrap.scss";
    }

</style>

```

but when version 4.4 updated, It is not working.
error message is 
.was-validated #{if(&, "&", "")}:#{$state},

so I use 4.3.2 version

**Comment by GauthierPLM** [comment]
You can use ::v-deep instead of /deep/ which is [deprecated](https://github.com/vuejs/vue-cli/issues/3399) and do not work with dart-sass (and probably not anymore with node-sass).

**Comment by MartijnCuppens** [comment]
`/deep/` is indeed deprecated, thanks for chiming in here @GauthierPLM
