### ISSUE TITLE
row-cols classes not available

### ISSUE THREAD

**Issue by o-alquimista** [twbs/bootstrap#29757]
I'm trying to use [row columns](https://getbootstrap.com/docs/4.4/layout/grid/#row-columns), but the classes don't have any effect. I can see it in the browser inspector that these classes do not apply any CSS.

```
  <section class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
      <div class="col">column</div>
      <div class="col">column</div>
      <div class="col">column</div>
      <div class="col">column</div>
    </div>
  </section>
```

With this code, I always have 4 columns. They do not change depending on the viewport size.

I've searched for the `.row-cols` classes in some Bootstrap files (anything with 'grid' in its name), but I couldn't find any so far. It seems they are not being included.

I am using Bootstrap 4.4 installed with Yarn, imported into my .scss asset file in my Symfony web application. I've tested both Firefox 70 and Chromium 78. I'm running Fedora Workstation 31.

This is how I import Bootstrap with Sass:
```
// Import required Bootstrap files
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
```
*Change some variables*
```
// Import remaining Bootstrap files
@import "~bootstrap/scss/bootstrap";
```

This is currently the only Bootstrap feature I'm unable to use. Everything else works.

**Update: the Sass mixin works: `@include row-cols(x);`**

**Comment by XhmikosR** [comment]
You are using and old or wrong version. This should be in >= 4.4.0.

**Comment by o-alquimista** [comment]
Impossible. Look at my package.json line:
`"bootstrap": "^4.3.1",`

Look at my lock file:
```
bootstrap@^4.3.1:
  version "4.4.0"
  resolved "https://registry.yarnpkg.com/bootstrap/-/bootstrap-4.4.0.tgz#477103fa44d44191971c8ca3e0b51a85ae62ea4d"
  integrity sha512-dqCYJNs/Fxa3IVQ+v/lC694POCThUjZsA4wwqs8l+yk67B6ww2Ki++WaM6CVGe5+tArBBrknzjjh01/NT5rLjA==
```

Version 4.4.0.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/blob/1dc390197909daa3123a0301a2150a1d8245ac4b/dist/css/bootstrap.css#L606-L634

**Comment by XhmikosR** [comment]
Please post a repo.

**Comment by o-alquimista** [comment]
I gave the classes another try just now, and they are working. Unbelievable.

Most likely reason: didn't compile assets after 4.4 update.

Sorry. Closing issue...
