### ISSUE TITLE
Input height has unvalid height

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#29752]
In `bootstrap@4.4.0` there is problem with `form-control`'s height. In chrome's console I see that: `calc(1.5em + 0.75rem2px)`.

I suppose it should be `calc(1.5em + 0.75rem - 2px)`.

I'm using `scss` version with `@import "~bootstrap/scss/bootstrap";`

**Comment by nicolomonili** [comment]
duplicate of [https://github.com/twbs/bootstrap/issues/29743](https://github.com/twbs/bootstrap/issues/29743)
