### ISSUE TITLE
Navbar Toggler gets responsive font-size when RFS is set to true

### ISSUE THREAD

**Issue by Joe1am** [twbs/bootstrap#29756]
As described in the topic, the toggle button gets a responsive font-size when the RFS feature ist set to true.

Because the container is set to display flex and the item alignment is set to center, my logo in navbar-brand moves when resizing the browser window. In my case between 516 and 517px. The height of the logo is 30px.

Not a big issue, but I wonder why the navbar-toggler needs a responsive font-size?

I use Bootstrap 4.3.1

**Comment by MartijnCuppens** [comment]
By default `$navbar-toggler-font-size` is `1.25rem` which doesn't rescale. You might have changed something else which made the toggle button rescale.

> Not a big issue, but I wonder why the navbar-toggler needs a responsive font-size?

We didn't explicitly implemented this, this is just a result of enabling the responsive font sizes. You could change this behaviour by configuring `$navbar-toggler-font-size` in `em`.

**Comment by Joe1am** [comment]
@MartijnCuppens Thanks for your reply. Makes all sense now. I had set the `$font-size-lg` to `$font-size-base * 1.5`. Changing the `$navbar-toggler-font-size` back to `1.25rem` did the trick for me.
