### ISSUE TITLE
New release not published on packagist

### ISSUE THREAD

**Issue by spipu** [twbs/bootstrap#29764]
Hi,

The new release 4.4.0 is not published on https://packagist.org/packages/twbs/bootstrap

thanks ;)

**Comment by XhmikosR** [comment]
@mdo please upload v4.4.0 and v4.4.1 to the other package managers you have access yourself only

**Comment by mattborja** [comment]
Assets don't appear to have been uploaded to StackPath either. I'm still getting a HTTP 403 at https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css

**Comment by XhmikosR** [comment]
Yeah, I know, see https://github.com/MaxCDN/bootstrapcdn/pull/1420.

I'll take measures so that this doesn't happen in the future.

**Comment by XhmikosR** [comment]
BTW v4.4.0 is on the CDN

**Comment by mattborja** [comment]
Gotcha, thanks!

**Comment by mdo** [comment]
I’ve never uploaded anything to Packagist as far as I know. I also don’t have a laptop on me because it’s Thanksgiving today in the US.

**Comment by XhmikosR** [comment]
The CDN is updated with the new versions

**Comment by mattborja** [comment]
I'm able to access 4.4.1 now. Thanks!

**Comment by XhmikosR** [comment]
@mdo unless we control packagist, we should remove any links. Ultimately we should control it, though.

**Comment by MartijnCuppens** [comment]
Than who is https://packagist.org/users/twbs/? 🤔

Shall we contact packagist about this?

**Comment by spipu** [comment]
I think the twbs user and this commit have been created at the same time : https://github.com/twbs/bootstrap/commit/be0974802d9ff19d6b4c12c288b3a4fd5c625415

**Comment by chrisc0** [comment]
It would be great if this could get fixed soon so I can access the latest releases on the CDN we use.

**Comment by Lausselloic** [comment]
On our fork, we have a webhook configured to publish on packagist, maybe somebody disable or remove it from bootstrap repository?
![image](https://user-images.githubusercontent.com/11272238/70217151-e37a2480-1740-11ea-95a9-572d5e55b0a5.png)

**Comment by mdo** [comment]
Confirming the webhook was the culprit. We were using the old legacy one, so I’ve just done two things:

1. Manually triggered an update on Packagist, so we’ve picked up the latest releases.
2. Updated the webhook to the newest version for future releases.

Sorry about that, y’all!
