### ISSUE TITLE
Differences between CDN and /dist/ version

### ISSUE THREAD

**Issue by Giulico** [twbs/bootstrap#29761]
Hi,
I wander what the differences are between the CDN and the /dist/ folder of the same v4.3.1 of bootstrap.js

*Example*
**CDN:**
https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.js
**Repo /dist/ folder:**
https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js

Here the comparison:
https://www.diffchecker.com/IF50vthq

Thank you

**Comment by XhmikosR** [comment]
There should be no difference since the CDN is using the npm package. You are comparing the master branch dist file from this repo, so it's moot.
