### ISSUE TITLE
Docs: Modals should not have aria-hidden attribute on a dialog element

### ISSUE THREAD

**Issue by hrvojegolcic** [twbs/bootstrap#29769]
I've found several places in the docs modal code snippets using `aria-hidden="true"` attribute on a dialog element. Correct me if I'm wrong but I don't see any benefit of it. Huge drawback is that the entire modal is not available to a screen reader. My understanding is that Bootstrap overcome this issue by removing `aria-hidden="true"` dynamically when modal is shown using Javascript (but why?!).
Moreover in combination with `tabindex="-1"` makes even less sense since `aria-hidden` elements shouldn't be combined with or contain any focusable elements.

**Example:**
![image](https://user-images.githubusercontent.com/6906827/69799856-60068380-11d4-11ea-8af6-6f828bdb0f4d.png)

**Reasons not to use `aria-hidden` attribute on a dialog element:**
* Not used by officials - w3.org - https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html
* Not used by MDN - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role
* Discouraged to use unnecessarily by ADG:  https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/hidden/
* `aria-hidden="true"` must not be combined with or contain any focusable elements
* If the content is hidden by CSS there is no need to hide it additionally from assistive technology. We already do have a solution that works for all so why to target screen reader only? 

Maybe there was some history reasons why this exists but even if so it's implemented incorrectly in my opinion. Either way I think it's not needed and does not increase the level of accessibility. It only increase the maintenance and brinks a confusion to developers.

**More from w3.org:**
> In legacy dialog implementations where aria-hidden is used to make content outside a dialog inert for assistive technology users, it is important that:
aria-hidden is set to true on each element containing a portion of the inert layer.
**The dialog element is not a descendant of any element that has aria-hidden set to true**.

This is my understanding and I referred the arguments.
I am happy to discuss.

**Comment by patrickhlauke** [comment]
it's `aria-hidden="true"` when it's currently not visible. once displayed, that's dynamically removed (and re-added when closed).

**Comment by patrickhlauke** [comment]
and `tabindex="-1"` means something can be *programmatically* focused. not that it's in the focus order. it only gets programmatically focused once it's made visible, which is when `aria-hidden="true"` is also removed.

**Comment by patrickhlauke** [comment]
true that `display:none` also removes the modal from the accessibility tree, making `aria-hidden` redundant. but it also doesn't have any adverse effect.

**Comment by hrvojegolcic** [comment]
I don't really understand how can it be acceptable having a redundant confusing piece of code and additional Javascript script to remove it?
Why to maintain this? Shouldn't we just remove it? I can do that as well if you don't mind.

Not only that it's redundant but it also confuses the users and general understanding of accessibility practices. It might also happen that someone tries to create a similar component and decides to keep `aria-hidden="true"` thinking that this is something relevant or required.

I don't see a single reason to keep it except that "yeah doesn't have any adverse effect".

**Comment by patrickhlauke** [comment]
conversely, authors may create a similar component, and instead of `display:none` use some other method to visually hide it (for instance, just moving the inert dialog off-screen and settings its opacity to zero, so they can then make it animate and swoosh in from the side while fading in), without realising that this still results in the dialog being present for assistive tech users unless it's `aria-hidden`.

**Comment by hrvojegolcic** [comment]
I agree that it can be argued. It's hard to be smart when it comes to accessibility.

It's a good argument but in my opinion not the correct way of thinking. Let me explain.
In this case the screen reader would at least announce that the content exist even if implemented incorrectly. That's opposite to the content which is permanently hidden and never accessible to the user in either way.

From my experience due to majority of inaccessible websites the users handle such content quite well. It's NOT a problem to skip an irrelevant block but IT IS a problem to hide a content from specific groups of users making them unaware that there is anything.

We must focus making solution that works for all, not targeting specific groups of users if not absolutely necessary!

More is not always batter. I would strongly recommend to read the articles here on sensible ARIA usage:
https://www.accessibility-developer-guide.com/examples/sensible-aria-usage

I still believe the current implementation is just a workaround and I don't see a point of keeping it. O only see drawbacks and I am happy to discuss further.

Best regards!
- Hrvoje

**Comment by Adriani90** [comment]
@patrickhlauke how long does the dialog need until it appears in case of an annimation? I am a blind NVDA user and I would say a sighted person would most probably see the dialog comming faster than me even if I could theoretically discover it while opacity is zero without aria hidden="true". However, this is a matter of miliseconds probably and in practice I would never have an advantage of finding this dialog faster than a sighted person.

cc: @jcsteh maybe you have some suggestions here because we see lots of such dialogs implemented with the current bootstrap documentation stating that aria hidden="true" and tabindex="-1" should be set. This cauuses issues when using a screen reader indeed.

**Comment by Adriani90** [comment]
Real use case where removing hidden atribute and restoring focus on a dialog causes an issue:
https://github.com/nvaccess/nvda/issues/11237
https://codepen.io/mijordan/live/qBbdWxN

Although in this case the hidden was not directly put on the dialog element, it shows the reporting effects on NVDA when removing it in the background.

**Comment by patrickhlauke** [comment]
@Adriani90 for context, the example fiddle used in https://github.com/nvaccess/nvda/issues/9156 uses Bootstrap 3.3.7 ... we're now at Bootstrap 5.3, so I'd hazard a guess that that example is out of date and should be re-checked with recent versions.

Testing hhttps://getbootstrap.com/docs/5.3/components/modal/#live-demo in Chrome/NVDA and Firefox/NVDA shows no adverse behaviour.

https://github.com/nvaccess/nvda/issues/11237 is completely unrelated to Bootstrap, so not directly relevant here.

**Comment by Adriani90** [comment]
@patrickhlauke thanks very much for the link to the modal docs, that's helpful.
Indeed there is no adverse behavior in Chrome and Edge when closing the modals.
In Firefox though the window title is sometimes read two or three times in a row before the focused element is announced. This is what I get in the NVDA log but I am not sure this is related to the aria-hidden atribute being removed:

```
IO - speech.speech.speak (18:36:03.778) - MainThread (4020):
Speaking ['Schalter', 'Launch static backdrop modal ', ' ']
IO - speech.speech.speak (18:36:03.798) - MainThread (4020):
Speaking ['Launch static backdrop modal ', 'Schalter']
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:03.798) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:03.798) - MainThread (4020):
description IA2Attribute is: 
IO - inputCore.InputManager.executeGesture (18:36:06.168) - winInputHook (6516):
Input: kb(laptop):NVDA+space
IO - inputCore.InputManager.executeGesture (18:36:06.628) - winInputHook (6516):
Input: kb(laptop):enter
DEBUG - treeInterceptorHandler.update (18:36:06.698) - MainThread (4020):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x053CF830>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (18:36:06.698) - virtualBuffers.gecko_ia2.VirtualBuffer.loadBuffer (13712):
Buffer load took 0.000 sec, 111 chars
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:06.708) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:06.708) - MainThread (4020):
description IA2Attribute is: 
IO - speech.speech.speak (18:36:06.708) - MainThread (4020):
Speaking ['Modal title', 'Dialogfeld', CancellableSpeech (still valid)]
IO - speech.speech.speak (18:36:06.708) - MainThread (4020):
Speaking ['Überschrift', 'Ebene 1', 'Modal title']
IO - inputCore.InputManager.executeGesture (18:36:07.238) - winInputHook (6516):
Input: kb(laptop):downArrow
IO - speech.speech.speak (18:36:07.238) - MainThread (4020):
Speaking ['Schalter', 'Close']
IO - inputCore.InputManager.executeGesture (18:36:07.568) - winInputHook (6516):
Input: kb(laptop):enter
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.594) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.594) - MainThread (4020):
description IA2Attribute is: 
DEBUGWARNING - RPC process 8696 (firefox.exe) (18:36:07.618) - Dummy-8 (13072):
Thread 14428, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::render, 1442:
Could not get IAccessible2, returning

DEBUGWARNING - RPC process 8696 (firefox.exe) (18:36:07.626) - Dummy-8 (13072):
Thread 14428, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::replaceSubtrees, 697:
Empty temp buffer

DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationTargetsOfType (18:36:07.628) - MainThread (4020):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationTargetsOfType (18:36:07.628) - MainThread (4020):
IA2_2 is not available, fall back to old approach
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (18:36:07.628) - MainThread (4020):
Unable to get nRelations
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationTargetsOfType (18:36:07.628) - MainThread (4020):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "browseMode.pyc", line 1845, in event_gainFocus
  File "documentBase.pyc", line 74, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 210, in __init__
  File "textInfos\offsets.pyc", line 465, in __init__
  File "virtualBuffers\__init__.pyc", line 206, in _getOffsetsFromNVDAObject
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1554, in _get__IA2Relations
_ctypes.COMError: (-2147220995, 'Objekt ist nicht mit dem Server verbunden.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1688, in _getIA2RelationTargetsOfType
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1557, in _get__IA2Relations
NotImplementedError
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.628) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.628) - MainThread (4020):
description IA2Attribute is: 
IO - speech.speech.speak (18:36:07.628) - MainThread (4020):
Speaking ['Schalter', CancellableSpeech (still valid)]
DEBUGWARNING - RPC process 8696 (firefox.exe) (18:36:07.642) - Dummy-8 (13072):
Thread 14428, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::render, 1442:
Could not get IAccessible2, returning

DEBUG - treeInterceptorHandler.killTreeInterceptor (18:36:07.658) - MainThread (4020):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x053CF830>
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:36:07.674) - MainThread (4020):
accRole failed: (-2147220995, 'Objekt ist nicht mit dem Server verbunden.', (None, None, None, 0, None))
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.678) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.678) - MainThread (4020):
description IA2Attribute is: 
IO - speech.speech.speak (18:36:07.678) - MainThread (4020):
Speaking ['Modal · Bootstrap v5.3 – Mozilla Firefox', CancellableSpeech (still valid)]
IO - speech.speech.speak (18:36:07.698) - MainThread (4020):
Speaking ['Modal · Bootstrap v5.3 – Mozilla Firefox', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.698) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.698) - MainThread (4020):
description IA2Attribute is: 
IO - speech.speech.speak (18:36:07.698) - MainThread (4020):
Speaking ['Modal · Bootstrap v5.3', 'Dokument', CancellableSpeech (still valid), ' ']
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.722) - MainThread (4020):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (18:36:07.722) - MainThread (4020):
description IA2Attribute is: 
IO - speech.speech.speak (18:36:07.722) - MainThread (4020):
Speaking ['Launch static backdrop modal', 'Schalter', CancellableSpeech (still valid)]
```

So looking at the speaking [] parts of this log snippet you can see how NVDA repeats the browser window title multiple times.

**Comment by patrickhlauke** [comment]
Well, all I can say is: I can't reproduce that problem in my setup (Firefox 125.0.2 (64-bit), NVDA 2024.1 (2024.1.0.31547)).
