### ISSUE TITLE
NuGet 4.4.0 Requires Popper.Js 1.16, which isn't on NuGet

### ISSUE THREAD

**Issue by cdcummings10** [twbs/bootstrap#29770]
Hey all,

As I was installing 4.4.0 through NuGet, I wasn't able to due to popper.js 1.14 being the highest version available on NuGet [Link](https://www.nuget.org/packages/popper.js/)

I was able to install 4.3.1 just fine.

Here is a picture of the error:
![NuGetErrorPopperJs](https://user-images.githubusercontent.com/53797906/69829255-1f0e6f00-11d4-11ea-9f6e-b812a6f81203.png)

Thanks, keep up the great work!

**Comment by XhmikosR** [comment]
You should probably ask @FezVrasta to publish this on Nuget.

We should probably drop any support for non-npm packages since we don't control nor test them.
