### ISSUE TITLE
Responsive containers not working correctly when using Sass

### ISSUE THREAD

**Issue by kosvrouvas** [twbs/bootstrap#29773]
- Operating system and version (Windows 10, MacOS Catalina)
- Browser and version (Chrome, Firefox)

I think something's wrong with the Sass implementation, some classes are overiding causing not to work. See:

![εικόνα](https://user-images.githubusercontent.com/3307723/69873235-70942800-12c0-11ea-8c63-f0fb7b41ee6a.png)

Building sass with `sass sass/bootstrap.scss:theme.css`

Using compiled version works great.

**Comment by ysds** [comment]
We need more details. Bug reports must include a live demo of the problem. Please create a [reduced test case](https://css-tricks.com/reduced-test-cases/) via [Stackblitz](https://stackblitz.com/) etc and report back with your link and Bootstrap version.

**Comment by kosvrouvas** [comment]
Hm, It was my bad. It works as expected, closing this!

For the story: When using sass and you edit from inspect element, containers are not working. When using compiled version, it works.
