### ISSUE TITLE
Online Customizer for 4.x

### ISSUE THREAD

**Issue by Sledge-Hammer** [twbs/bootstrap#29776]
Hello,
Just wanted to mention that the lack of this feature https://getbootstrap.com/docs/3.4/customize/ is the only reason that stops me from migrating to version 4.x of Bootstrap.

And to be more specific - I'm talking about the component selection... the whole theming section is not that important (we can always override something we don't like in a custom css file) but being able to choose which css and js components to include is crucial, especially nowadays when everyone is using mobile devices and bandwidth is important (plus google penalizes slower loading sites).

You can all agree that Bootstrap is quite a large project and most of the time not everything that comes with it is needed for every site... for example why should I make the visitors download code for modals and forms if the site they open doesn't have any?

I know that you've said in the past that you won't add this feature to version 4, but please reconsider it for performance reasons... if not - could you at least publish the source of the current customizer so someone else could make it work with the latest version (I tried searching for it but couldn't find anything).

**Comment by mdo** [comment]
@Johann-S created this one: https://johann-s.github.io/bs-customizer/.

**Comment by Sledge-Hammer** [comment]
Thank you, that is exactly what I needed!
Just a small suggestion - since this is made by an official team member you guys might want to add it to the main site - for example the reason I posted here is because I couldn't find it after a few different google searches... and back in the day when I was looking around for a framework to replace what I had cobbled on my own, the customizer was the cherry on top that made me choose Bootstrap :)

**Comment by slorber** [comment]
same here, will submit a PR to the doc because it's really useful...

On only need a custom grid system, don't want to setup webpack loaders just for building it once for all
