### ISSUE TITLE
Row columns are not working correctly with responsive breakpoints

### ISSUE THREAD

**Issue by RodrigoSiqueira-Dev** [twbs/bootstrap#29778]
Row columns are not working correctly with responsive breakpoints, for exemple:

`< div class="row row-cols-1 row-cols-md-2" >
    < div class="col" >Some content< /div>
    < div class="col-12" >Some content< /div>
    < div class="col" >Some content< /div>
    < div class="col" >Some content< /div>
< /div >`

doesn't matter the breakpoint this code will always show 1 column in small devices and 2 columns in largers. The col-12 div doesn't get the whole size above md breakpoint as expected.

I made some fix in a custom mixin make-col by adding !important and just works fine now as the code below:

`// Fix make-col mixin to work correctly with responsive row-cols breakpoints
@mixin make-col($size, $columns: $grid-columns) {
  flex: 0 0 percentage($size / $columns) !important;
  // Add a `max-width` to ensure content within each column does not blow out
  // the width of the column. Applies to IE10+ and Firefox. Chrome and Safari
  // do not appear to require this.
  max-width: percentage($size / $columns) !important;
}
`

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by Pelesibt** [comment]
Not working. Any suggestion?

<div class="container">
   <div class="row">
   	<div style="border:1px solid" class="col-lg-6">COL LG 6</div>
   	<div style="border:1px solid" class="col-lg-6">COL LG 6</div>
   </div>
</div>

**Comment by mavelo-llc** [comment]
Trying to find a solution for same/similar issue
https://github.com/twbs/bootstrap/issues/35523#issuecomment-2480672904
