### ISSUE TITLE
Change navbar GitHub link to org?

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#29796]
As we’re using the same navbar across all our projects now—docs, icons, and blog—I’m wondering if we should be linking to our GitHub org profile instead of the Bootstrap (or Icons) projects in the main navbar.

Thoughts @XhmikosR, @MartijnCuppens, @ysds, @Johann-S?

**Comment by MartijnCuppens** [comment]
Fine by me!

**Comment by XhmikosR** [comment]
I guess it can be handy and problematic too. I'm not sure what I prefer myself... maybe linking to the repo saves some time, but since we can pin the important repos (reminder to pin icons or any other important ones) I guess we can just go with the org link.

**Comment by asifuran2019** [comment]
I want to do this as my first task on github.
So to confirm if I correctly understand this, does this require updating the url on that github icon to "github.com/twbs"?
![image](https://user-images.githubusercontent.com/55647986/72275033-2c33d000-3653-11ea-99df-022f360fdffe.png)
