### ISSUE TITLE
关于Scrollspy中，标题的class名无法被加active  下面提供页面代码

### ISSUE THREAD

**Issue by SHIJIE0313** [twbs/bootstrap#29795]
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
		 crossorigin="anonymous">

		<title>系统介绍</title>

	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">校园社团招新系统</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
			 aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<div class="navbar-nav">
					<a class="nav-item nav-link" href="/index">首页 <span class="sr-only">(current)</span></a>
					<a class="nav-item nav-link" href="/login">登录</a>
					<a class="nav-item nav-link active" href="#">系统介绍</a>
					<a class="nav-item nav-link" href="Aboutus.html">关于我们</a>
				</div>
			</div>
		</nav>
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 com-lg-12">
					<div class="jumbotron">
						<h1 class="display-4">校园招新系统V1.0</h1>
						<p class="lead">2018年9月正式上线
						</p>
						<hr class="my-4">
						<p>一个基于PHP打造的线上招新系统</p>
						<div class="row">
							<div class="col-4">
								<div id="list-example" class="list-group" style="position: relative;">
									<a class="list-group-item list-group-item-action" href="#list-item-1">技术介绍</a>
									<a class="list-group-item list-group-item-action" href="#list-item-2">服务器情况</a>
									<a class="list-group-item list-group-item-action" href="#list-item-3">使用情况</a>
									<a class="list-group-item list-group-item-action" href="#list-item-4">潜在问题</a>
								</div>
							</div>
							<div class="col-8" style="height: 200px;overflow-y: scroll;">
								<div data-spy="scroll" data-target="#list-example" data-offset="0" class="scrollspy-example" style="position: relative;">

									<h4 id="list-item-1">技术介绍</h4>
									<p>第一代招新系统前端使用bootstrap3，后端使用PHP+MYSQL+PHPMyadmin搭建。</p>
									<h4 id="list-item-2">服务器情况</h4>
									<p>服务器使用Windows Server数据中心版</p>
									<h4 id="list-item-3">使用情况</h4>
									<p>总报名数10000+，未出现过宕机情况，使用CDN加速，以保证网页最佳效果</p>
									<h4 id="list-item-4">潜在问题</h4>
									<p>1.第一代系统对于面向对象编程思想，仍有欠缺。<br>2.没有做到工程化，代码冗余。<br>3.数据库没有进行过多设计。<br>4.代码可读性低，可维护性差。<br>5.过多堆积图片等资源，无法合理利用带宽。</p>

								</div>

							</div>
						</div>
					</div>

				</div>

			
		</div>

		
		
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
		 crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9+4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb"
		 crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		 crossorigin="anonymous"></script>
	</body>

</html>

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
