### ISSUE TITLE
btn-outline-

### ISSUE THREAD

**Issue by justinvalceanu** [twbs/bootstrap#29807]
btn-outline-* - Not working in /dist for 4.4.1

**Comment by midzer** [comment]
For me, it is available https://github.com/twbs/bootstrap/blob/9894000b42472c8bb2deb514ecc8c896093f945e/dist/css/bootstrap.css#L2887

And in v4 branch, too.

**Comment by justinvalceanu** [comment]
internal squid cache - my fault
