### ISSUE TITLE
is it possible to provide less version in the latest release?

### ISSUE THREAD

**Issue by xyktiger** [twbs/bootstrap#29806]
We were using less in bootstrap 3, now cannot find a less version in release 4.
Any input is appreciated, thanks.

**Comment by midzer** [comment]
Bootstrap moved from LESS to SASS in Bootstrap 4 alpha https://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by mdo** [comment]
A quick search across GitHub might find something, but we don’t maintain a Less version at all since v4. We’ll be sticking with Sass in v5, too.
