### ISSUE TITLE
$headings-color overrides white color in active list group item

### ISSUE THREAD

**Issue by swrobel** [twbs/bootstrap#29800]
Because the heading color rule is more specific, it overrides the white color for text in active list group items. I don't know if this is necessarily a bug, but it definitely doesn't look right and follow the behavior to be expected from the example. It doesn't come up in [the example](https://getbootstrap.com/docs/4.4/components/list-group/#custom-content) because `$headings-color` is `null` by default.

I'm having a hard time putting together an easy test case on CodePen, JsBin, etc, because I can't easily import the scss from an external source so that I can set variables. **If anyone knows how to do this, I'd love to know.**

Anyway, this is the easiest repro I've been able to find. Unfortunately the site I'm using is on a beta version of Bootstrap v4, but I've reproduced this on 4.4.1 locally.

1. https://pikock.github.io/bootstrap-magic/app/index.html
1. Dismiss top bar message
1. Click "Import" button in top nav
1. Paste `$headings-color: $yellow;`
1. Click "HTML editor" in the top nav
1. Paste this, which is straight from the docs:
```html
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">I think this should be white</h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">It makes sense that this is yellow</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
</div>
```
1. Click "Preview" in the secondary nav
1. Note that the active list group item heading text is yellow
<img width="716" alt="Screen Shot 2019-12-03 at 11 22 52 AM" src="https://user-images.githubusercontent.com/157270/70082446-4a6fd000-15bf-11ea-9d36-8fda60013038.png">

- Operating system: macOS 10.14
- Browser: Firefox 71, Chrome 78

**Comment by mdo** [comment]
Unsure how we can handle this ourselves without creating more complexity. Thoughts from @twbs/css-review?

**Comment by MartijnCuppens** [comment]
If you don't want your headings to always have the same color, you shouldn't set `$headings-color`. I've also had this issue before, but I'm afraid there isn't a simple way to tackle this. In this case I would add a little custom CSS to fix the styling.

**Comment by swrobel** [comment]
Fair enough. Regarding this question, any ideas? It seems like the current options for providing easy code repros that depend on using SASS features are limited.

> I'm having a hard time putting together an easy test case on CodePen, JsBin, etc, because I can't easily import the scss from an external source so that I can set variables. If anyone knows how to do this, I'd love to know.
