### ISSUE TITLE
disabled custom checkbox with gradients is not grayed out in checked state

### ISSUE THREAD

**Issue by kkozlik** [twbs/bootstrap#29809]
If the custom checkbox is in checked state and if gradients are enabled it has a same look whether it is enabled or disabled. 

Can't reproduce a codepen example, because I can't enabled gradients without compiling the scss.

I think the solution might be adding:
```
background-image:none;
```
to scss/_custom-forms.scss line 138

Tested with:
* bootstrap 4.4.1
* linux
* chromium  78.0.3904.108

**Comment by kkozlik** [comment]
And the same is for custom radio button

**Comment by ajcerejeira** [comment]
I can confirm that this is also happening to me:

```html
<div class="custom-control custom-switch">
  <input type="checkbox" id="checkbox" class="custom-control-input" checked disabled>
  <label for="checkbox" class="custom-control-label disabled"></label>
</div>
```

**Result:**

![image](https://user-images.githubusercontent.com/22506305/76796551-9ab41c00-67c3-11ea-94db-5de825015d8d.png)

**Expected:**

![image](https://user-images.githubusercontent.com/22506305/76796644-cfc06e80-67c3-11ea-9a72-23b0840283cc.png)

**Comment by XhmikosR** [comment]
Fixed by 30922
