### ISSUE TITLE
Enable `recursivelyOptimizeProperties` option

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29818]
Lines like these can be optimised in our generated CSS by enabling  [`recursivelyOptimizeProperties`](https://github.com/jakubpawlowicz/clean-css#level-2-optimizations)
https://github.com/twbs/bootstrap/blob/1a5b7f4a8e235b0733b2ead9a4404ffaabb9ead2/dist/css/bootstrap.css#L5035

I tried, but I don't have a clue how to enable this here:
https://github.com/twbs/bootstrap/blob/1a5b7f4a8e235b0733b2ead9a4404ffaabb9ead2/package.json#L28

Probably worth backporting since this will decrease our file size.

@XhmikosR, could you help me out with this?

**Comment by XhmikosR** [comment]
Generally I don't like enabling any of the level 2 optimizations because they can break stuff. And if we go down this route, we'll end up with us specifying a ton of level 2 optimizations...

That being said did you try ` -O1 recursivelyOptimizeProperties:true`?

**Comment by XhmikosR** [comment]
And please share how much we save. I'm not sure how many cases we have that we could benefit, and again, I'm not sure if we should just go with the -O2 optimizations at all. Judging from this https://goalsmashers.github.io/css-minification-benchmark/ the gain isn't big enough to justify the risk of breaking things IMHO.

**Comment by MartijnCuppens** [comment]
> Generally I don't like enabling any of the level 2 optimizations because they can break stuff

This one feels pretty safe. 

> That being said did you try `-O1 recursivelyOptimizeProperties:true`?

Yup, doesn't seem to work.

**Comment by XhmikosR** [comment]
It might feel safe, but then why don't we enable further O2 optimizations? I'd rather keep it simple and safe than having to maintain a huge list of potential optimizations...

**Comment by mendozagioo** [comment]
@MartijnCuppens why not just change variables configuration?
For example:
`$modal-header-padding: 1rem;`
instead of:
`$modal-header-padding: $modal-header-padding-y $modal-header-padding-x !default;`
The same for another situations

**Comment by XhmikosR** [comment]
```diff
 package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/package.json b/package.json
index 15170d720..1ac77f3fb 100644
--- a/package.json
+++ b/package.json
@@ -25,7 +25,7 @@
     "css-lint": "npm-run-all --continue-on-error --parallel css-lint-*",
     "css-lint-stylelint": "stylelint \"**/*.{css,scss}\" --cache --cache-location .cache/.stylelintcache --rd",
     "css-lint-vars": "fusv scss/ site/assets/scss/",
-    "css-minify": "cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap.min.css dist/css/bootstrap.css && cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap-grid.min.css dist/css/bootstrap-grid.css && cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap-utilities.min.css dist/css/bootstrap-utilities.css && cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap-reboot.min.css dist/css/bootstrap-reboot.css",
+    "css-minify": "cleancss -O2 \"all:off;recursivelyOptimizeProperties:on\" --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap.min.css dist/css/bootstrap.css && cleancss -O2 \"all:off;recursivelyOptimizeProperties:on\" --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap-grid.min.css dist/css/bootstrap-grid.css && cleancss -O2 \"all:off;recursivelyOptimizeProperties:on\" --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap-utilities.min.css dist/css/bootstrap-utilities.css && cleancss -O2 \"all:off;recursivelyOptimizeProperties:on\" --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/bootstrap-reboot.min.css dist/css/bootstrap-reboot.css",
     "css-prefix": "npm-run-all --parallel css-prefix-*",
     "css-prefix-main": "postcss --config build/postcss.config.js --replace \"dist/css/*.css\" \"!dist/css/*.min.css\"",
     "css-prefix-examples": "postcss --config build/postcss.config.js --replace \"site/content/**/*.css\"",

```

Not sure it's worth it or if it breaks something...

That being said, we could look into enabling some of the O2 level optimizations that we deem safe and assuming the result is what we want.

**Comment by MartijnCuppens** [comment]
This is the diff: https://www.diffchecker.com/5n0Vx08Y. Some shorthand properties are ordered in the right order here too.

Enabling other options can be dangerous it seems. Apart from `removeEmpty` (but this is taken care of by Sass anyway), other rules could cause issues. I tested with the default level 2 options and it looks like rules with engine prefixes got combined with other rules which make them invalid in other browsers. Also the rearranging of rules could be problematic, eg if `.btn-sm` would be declared before `.btn` itself (this is not the case, but something similar could happen).

**Comment by XhmikosR** [comment]
@MartijnCuppens can you check if we can apply any of those optimizations in Sass? Like the order.

And I can make a PR with adding `recursivelyOptimizeProperties` but I suppose it won't save us a lot. Bringing the precision back to 6 will probably save us more.

Because we don't test the CSS on CI, I'm generally very cautious with the minifier; we've been hit in the past and we can be hit at any time without noticing. Heck, even JS breaks and we have automated tests 😟

**Comment by XhmikosR** [comment]
Made a quick branch to see the diff: https://github.com/twbs/bootstrap/compare/main...main-xmr-cleancss-test

**Comment by XhmikosR** [comment]
So, how do you think we should proceed @twbs/css-review? I'm generally OK with such options, but like I said above, since we don't test CSS, it's trickier.

That being said, we can explicitly enable any options we find are safe.

**Comment by ffoodd** [comment]
I may try this branch and check our dist? Starting by check that `1rem 1rem` has been removed?

**Comment by MartijnCuppens** [comment]
Go ahead @ffoodd 😉

**Comment by ffoodd** [comment]
Just tested `main-xmr-cleancss-test` branch: it's working fine, however gains are indeed negligible as of now.
We may try to open a PR (rebased on `main`) to check Bundlewatch outputs, but for the `1rem 1rem` case there were only 4 occurrencies to drop, so it's really rare.

However comparing dist files is a nightmare, so I may have missed some other cases.

**Comment by mdo** [comment]
Worth keeping this open, or is it safe to close out as stale?

**Comment by XhmikosR** [comment]
I'm not sure it's worth it judging by the gains.  We might need to revisit later, though.

We are better off using CSS variables in more places; that should save a lot more if used wisely :)

**Comment by mdo** [comment]
I'm good punting for now then. Happy to reopen if anyone wants to take a pass.
