### ISSUE TITLE
Group-by V2 and new table to modal: Lost group-by

### ISSUE THREAD

**Issue by manukieli** [twbs/bootstrap#29816]
- Operating system and version: Win10)
- Browser and version:  Chrome
- Bootstrap-table: V1.15.5

In the main page I've a table with group-by activate and a column to open to modal window a new table without group-by.
After modal is closed and change the page of the table of the main page, group-by option and header are lost
![groupby_modal_lost](https://user-images.githubusercontent.com/14294794/70369822-590bff00-18bf-11ea-94a5-3cd968ad1b50.gif)

You can see it to this link: https://live.bootstrap-table.com/code/manukieli/1355

**Comment by patrickhlauke** [comment]
Bootstrap Table has nothing directly to do with official bootstrap. Suggest filing an issue with them https://bootstrap-table.com/

**Comment by manukieli** [comment]
Forgive the confusion
