### ISSUE TITLE
Font "width" in browsers is very different (possible kerning) 

### ISSUE THREAD

**Issue by wtorsi** [twbs/bootstrap#29811]
Hi,

I've noticed that font "width" differs in Chrome 78, Safari 13, Firefox 70
And i could not find any browser specific property which is responsible for this behaviour.
Any ideas how to deal with it? 

![image](https://user-images.githubusercontent.com/2115840/70329889-7902da80-184d-11ea-82b2-6682fe92def1.png)

Here is the difference in pixels. In Chrome and Firefox the width of letter is smaller than in Safari.

![image](https://user-images.githubusercontent.com/2115840/70329993-acde0000-184d-11ea-93bd-bdfbb10a85b0.png)
![image](https://user-images.githubusercontent.com/2115840/70330008-b5ced180-184d-11ea-95f5-a8369724dd2b.png)
![image](https://user-images.githubusercontent.com/2115840/70330159-0cd4a680-184e-11ea-89e9-1f045c14aaa4.png)

**Comment by patrickhlauke** [comment]
I'd hazard a guess that this is not a Bootstrap-specific issue, but that it affects text rendering in general. Try out the same thing just with a plain, non-BS page. Browsers will do their sub-pixel rounding very slightly differently. It's best not to rely on pixel-accurate rendering across different browsers.
