### ISSUE TITLE
Remove engines version from package.json

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29821]
I was thinking about it and I *think* it makes sense if we actually dropped this.

Consumers of the npm package just get the dist files so they aren't affected by this AFAICT. What we use to build and develop Bootstrap itself does not affect consumers. So having a version could be considered wrong.

This will allow us to use whatever Node.js version we want to use without having to support unsupported Node.js versions anymore. Which means, we could just stop testing Node.js 6.x in v4-dev and be able to update the devDependencies. I'm not sure if this can be considered a breaking change, though, so please chime in in case I'm missing something.

People willing to contribute can always check what we test on CI for each branch. Or we can just mention it in README.md or CONTRIBUTING.md.

@twbs/team: thoughts?

**Comment by Johann-S** [comment]
I totally agree! That's pretty weird to specify a Node.js engine for a front-end framework
