### ISSUE TITLE
Disabled button pointer cursor

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#29833]
The cursor is a pointer.

* 4.4: https://getbootstrap.com/docs/4.4/components/buttons/#disabled-state
* v5: https://twbs-bootstrap.netlify.com/docs/4.3/components/buttons/#disabled-state

**Comment by ysds** [comment]
This issue related #29239

CC/ @MartijnCuppens

**Comment by mdo** [comment]
Removing the v5 label and project here to be clear about this now only needing a fix in v4.

**Comment by MartijnCuppens** [comment]
Closed by #29835
