### ISSUE TITLE
Drop Edge (render engine) support

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29830]
Since Edge is switching to Chromium next month, we could/should drop support for the older layout engine in `v5`. Thoughts @twbs/team?

**Comment by mdo** [comment]
Will the switch roll out to all existing Edge users, or are we going to see another significant fracture in browsers?

**Comment by XhmikosR** [comment]
Could be, because some systems stay behind. Like Microsoft supports older Windows 10 versions.

**Comment by MartijnCuppens** [comment]
By default, Edge will replace their old engine unless some option is explicitly enabled: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#allowsxs

**Comment by Studio384** [comment]
The browser is being replaced, the render engine within Windows however is not. Apps from the Microsoft Store, for now, will continue to rely on EdgeHTML (including PWAs in the Store like Twitter) and even once Microsoft provides WebView2 (the Blink-based webview) here, developers will have to actively enable it.

Regardless, Edge is a default update, but it isn't mandatory. People will be able to uninstall it even if it is applied to their system by default and many will have legitimate reasons to remain on the old Edge, or run them side-by-side.

Edge will be supported as a fully functional browser until at least May 2022, and that's assuming Microsoft will replace Edge by default with no way back in the Spring update for 2021 (as the EdgeHTML-based browser is still the default in version 2004 and won't be replaced in the second release for 2020).

Sure, Bootstrap doesn't need to provide support for that long, but killing support before normal users reasonably would no longer come into contact with software that do use EdgeHTML is just premature. Given that with Bootstrap 4 you ("you" as in "Bootstrap") were to afraid to kill of Internet Explorer 10, suddenly killing an entire browser seems extreme.

**Comment by MartijnCuppens** [comment]
Thanks for the info @Studio384. Where did you get that from?

**Comment by XhmikosR** [comment]
It's common knowledge, TBH.

Let's drop this patch for the time being.
