### ISSUE TITLE
dropdown doc example bug with classes .btn-group and .dropdown

### ISSUE THREAD

**Issue by jrochkind** [twbs/bootstrap#29837]
In the bootstrap dropdown docs at:

https://getbootstrap.com/docs/4.0/components/dropdowns/

The first simple examples, with button or <a> tag, put a class `dropdown` on the outer div, and do *not* put a class `btn-group` on them. 

```html
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
```

I believe that is correct. 

However, the next example for button variants is inconsistent. I believe it should be identical but for (eg) `btn-danger` instead of `btn-secondary`, but instead:

```html
<!-- Example single danger button -->
<div class="btn-group">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>
```

* It has the `btn-group` class -- I think this is unnecessary,  "split" buttons need this, but this isn't a split button, and shouldn't have the superfluous `btn-group` class
* It lacks the `dropdown` class -- while it seems to work anyway without it, there is a `dropdown` class defined in bootstrap source, and I believe dropdowns are meant to apply it to the outer div, as in the first examples?

The subsequent examples of "split button dropdowns" have the `btn-group` class (which I believe is correct, they need it for split buttons), but also lack the `dropdown` class, which I believe is in error again.

**Comment by mdo** [comment]
Either can be used, depending on the situation—they don't need both. `.btn-group` is set to `inline-block`, so it naturally appears inline with the other buttons instead of stacking as `.dropdown` is usually block level (assuming a  `<div>` as the element).
