### ISSUE TITLE
Update Popper.js to v2.x

### ISSUE THREAD

**Issue by NemoDima** [twbs/bootstrap#29842]
Hello

Could you please plan the process of updating Popper.js to ver2.0.0. X ?
As a result, a lot of bugs will be fixed: https://github.com/popperjs/popper.js/labels/Fixed%20in%20v2
One of them is my https://github.com/popperjs/popper.js/issues/835

I'll be appreciated.
Regards, Dmytro

**Comment by XhmikosR** [comment]
Sorry, v2.0.0 isn't released. When this happen we'll revisit it later.

**Comment by FezVrasta** [comment]
We just released the first alpha (`@popperjs/core@2.0.0-alpha.1`).

It would be awesome to get some feedback.

**Comment by XhmikosR** [comment]
@Johann-S any thoughts how to proceed with the 2.x update? I see popper.js 2.x doesn't properly support IE 11 and requires polyfills...

**Comment by FezVrasta** [comment]
We left a note about the IE support:
https://popper.js.org/docs/v2/browser-support/#ie10-and-older

Now that Microsoft ships a browser, compatible with old Microsoft operative systems, with support for compatibility mode, there's no reason for **anyone** to stick to Internet Explorer.

Big corporations can upgrade to a Microsoft browser, and keep their legacy websites working. Users can upgrade even if they run an operative system that didn't support Edge before.

In any case, with polyfills, Popper 2 should just work. I'm quite sure websites that support IE need to include polyfills for several reasons already.

**Comment by XhmikosR** [comment]
>Now that Microsoft ships a browser, compatible with old Microsoft operative systems, with support for compatibility mode, there's no reason for anyone to stick to Internet Explorer.

As much as it might seem logical to you (and me), things aren't like that. The fact that Microsoft switched to another engine means nothing for corporate environments, despite them (Microsoft) trying to ignore this fact. IE cannot be diminished in one day.

That being said, and since we are already late in releasing v5, I think we might as well drop IE 11 support. As long as we offer a solution for people regarding the JS part.

The problem is that if we are going to really drop IE support (since this is the only thing that would really benefit us size-wise), things would start looking broken. I'm not sure we are this point yet. Which means, we'd need to semi drop IE support. And that's something that I'm not sure it's good either.

**Comment by FezVrasta** [comment]
As I said, Popper 2 should work fine on IE 11.

A good plan to me would be to drop polyfills from Bootstrap, and ask users to import them manually, with a tool such as polyfill.io

**Comment by XhmikosR** [comment]
>As I said, Popper 2 should work fine on IE 11.

With polyfills.

So, as things are now, we have these solutions as far as I'm concerned:

1. ignore popper 2.x and ship what we have as v5
2. revisit IE support and drop our built-in polyfills, but update the docs with the needed snippets and stuff
3. revisit IE support and drop it completely

The 3rd solution is something I don't think we are ready to do.

The second solution doesn't really gain us anything in the sense that the CSS prefixes will still need to be there and we will still be limited in the CSS features we use.

**Comment by FezVrasta** [comment]
I think 2 would be a good solution. If we received feedback earlier during the development phase we could have came up with a better plan probably.

**Comment by atomiks** [comment]
I agree that 2 is best. Users should polyfill based on their target browser requirements rather than Bootstrap bundling them in. 

`polyfill.io` is a fantastic service too, because browsers that don't need the polyfills aren't burdened with their cost - which is an advantage over bundling in the polyfills!

It would be a shame if Bootstrap didn't migrate to Popper 2, as we won't be maintaining it anymore. Users will likely be making issues for it due to Bootstrap's large adoption, and it will be a problem for the whole ecosystem.

**Comment by Johann-S** [comment]
Personally I would prefer if we can totally drop IE.

- The first solution isn't a good solution for us, because we aren't able to ship a lot of release and we'll be stuck with an old unmaintained lib (Popper.js v1).

- The second solution is a bit better but Polyfill.io do not provide all the needed polyfills. For example they do not polyfill `Event.preventDefault`.

That's why I would prefer the third solution.

**Comment by FezVrasta** [comment]
Polyfill.io can polyfill `preventDefault` with the `Event` flag:

```
https://polyfill.io/v3/polyfill.min.js?features=Event
```

**Comment by XhmikosR** [comment]
Let's try one more time and if now the polyfill works fine we can drop the built-in ones and unblock the popper.js update.

The only downside is that we'd need to change all templates and examples to include the polyfill. Or we could just mention it in the migration notes and in the browsers and devices page with a huge warning regarding IE support.

**Comment by FezVrasta** [comment]
I think the huge warning regarding IE support is the way to go, it's okay to support ancient browsers, but it's not okay to tailor the whole process to take them in consideration. People who want to support such old browsers should take extra care.

**Comment by SilvioDoMine** [comment]
I think we should indeed leave IE behind. @FezVrasta said a good point.

**Comment by atomiks** [comment]
Bootstrap dropping IE11 support would be a big step to ensuring it dies off quicker. The longer we support IE the longer it will stick around...

**Comment by XhmikosR** [comment]
If anyone can help us with dropping our custom polyfills and updating the docs accordingly, this is one less thing that's blocking us for v5. Don't forget to CC me if you make a PR.

**Comment by XhmikosR** [comment]
In the last team group call, we decided that at this point, it might be easier for us to drop IE 11 support from v5. v4 will be supported for as long as we can (we'll update the release repo to reflect his when we release v5), so people who want to support IE can still use v4.

After we remove IE 11 support from master, we can use any help available to update the docs, update popper.js to v2 and so on.

Generally, we could use any help we could get in the JS department, so if anyone's interested in helping us out, please drop by our Slack and DM me.

**Comment by hatuhay** [comment]
Drupal 9 is upgrading to popper 2 [https://www.drupal.org/node/3112670](url)
To continue using Bootstrap based themes, we should upgrade too.

**Comment by XhmikosR** [comment]
PRs welcome as usual for master.

**Comment by FezVrasta** [comment]
👋 I just published a new `popper.js@1.x` version, it's `1.16.1-lts`. It's just like 1.16.1, but without the deprecation warning.

It's meant to be used by those libraries that aren't willing to update to 2.x for whatever reason (for example, Bootstrap 4.x may never update so this LTS allows to not show the deprecation warning to the users).

**Comment by Ronner** [comment]
> 👋 I just published a new `popper.js@1.x` version, it's `1.16.1-lts`. It's just like 1.16.1, but without the deprecation warning.
> 
> It's meant to be used by those libraries that aren't willing to update to 2.x for whatever reason (for example, Bootstrap 4.x may never update so this LTS allows to not show the deprecation warning to the users).

Thx for doing this, however I have a question. With NPM I installed bootstrap (4.4.1) en this 1.16.1-lts version of popper.js, but npm install still gives me this message:

`npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.`

Any way to get rid of that?

**Comment by FezVrasta** [comment]
Bootstrap will need to update its peerDependencies to explicitly allow this new version.

**Comment by Ronner** [comment]
They require ^1.16.0 currently. Does the use of letters (-lts) in this version number confuse npm or bootstrap that it doesn't recognize it as a correct version? Or should versioning this version of popper.js not have been 1.16.2 in that case? (mind you I do not have much experience with NPM and the way it checks dependencies etc)

**Comment by FezVrasta** [comment]
the `-lts` is a pre-release flag, so the existing `^` selector will not include it. I can't release it as 1.16.2, because doing so all the consumers who update to `popper.js@latest` would miss the warning.

The `-lts` strategy, instead, provides a way for library maintainers to explicitly opt in the LTS version.

**Comment by Ronner** [comment]
Gotcha. So now we have to wait until Bootstrap includes the -LTS version as an allowed peerDependency.

**Comment by Ronner** [comment]
Are the bootstrap devs aware of this fact?

**Comment by XhmikosR** [comment]
We are and keeping spamming us is not helpful.

**Comment by Ronner** [comment]
I'm sorry. I never looked at the address bar in my browser. I thought I was on the popper.js repo 😊  Wasn't my intention to spam you guys.

**Comment by atomiks** [comment]
Congrats on releasing Bootstrap 5 alpha 🎉  

I noticed it's still using Popper v1 though, are there plans to migrate to v2 before beta/final release?

**Comment by Johann-S** [comment]
Yes we plan to do it ASAP

**Comment by octogonz** [comment]
Can we make Popper.js optional somehow? We don't even use any Bootstrap features that require Popper, but we see this annoying warning every day.

**Comment by NemoDima** [comment]
Sorry to bother all of you, but could you provide any updates, please?
appreciate your help.

**Comment by Jevenji** [comment]
For anyone who is using v2 globally with vendor code referencing the old v1 class, you could do something like this (I haven't checked the compatibility for all methods etc. but it should allow Popper to be instantiated using both as a class (v1) and by using createPopper() (v2)).

`// Ensure Popper version 2.
if (typeof Popper != 'undefined' && typeof Popper.createPopper == 'function') {
  //Stash version 2.
  window.Popper2 = Popper;

  // Create a constructor for v1 uses.
  Popper = function(reference, popper, options) {
    return window.Popper2.createPopper(reference, popper, options);
  }
  
  // Create the createPopper() method for v2 uses.
  Popper.createPopper = function(reference, popper, options) {
    return window.Popper2.createPopper(reference, popper, options);
  }
}`

**Comment by FezVrasta** [comment]
Popper modifiers are different in v2, you can't do that
