### ISSUE TITLE
sticky-top implementation differs from _position.scss to bootstrap.css

### ISSUE THREAD

**Issue by ardiaca** [twbs/bootstrap#29848]
In a custom built bootstrap, using **[/scss/helpers/_position.scss line 25](https://github.com/twbs/bootstrap/blob/master/scss/helpers/_position.scss#L25)**, .sticky-top class is missing ios **position: -webkit-sticky**.

In the prebuilt distribution **[/dist/css/bootstrap.css line 5765 on](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L5765)**, .sticky-top does has ios **position: -webkit-sticky**.

It makes sticky-top, in built bootstraps, not to work on ios without custom code.

- Operating system and version: Ubuntu 18.04.3
- Browser and version Chrome 78.0.3904.87

**Comment by florianlacreuse** [comment]
Do you use Autoprefixer? https://getbootstrap.com/docs/4.4/getting-started/build-tools/#autoprefixer

**Comment by ardiaca** [comment]
No. Thank you Florian.
