### ISSUE TITLE
DOCUMENTATION | Read in offline mode

### ISSUE THREAD

**Issue by abelardolg** [twbs/bootstrap#29845]
Hi there!
I compiled your documentation to see at local browser but I wonder if any Internet connection is a must to previously compile it.

If it does, why don't you offer the documentation ready to be read with no previous compilation process? 

Brs.

**Comment by mdo** [comment]
Docs are built with Bootstrap, Hugo, npm scripts, and several dependencies. It's unrealistic to expect them to work entirely without some kind of compilation. Aside from dependencies, no other internet connection is required for locally running the docs.
