### ISSUE TITLE
Support specific breakpoints for auto flexbox

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#29846]
`Example: <div class="col-md-6 col-lg-4 col-xl-auto">`
Where "col-xl-auto" would be applied only on xl breakpoint.

**Comment by florianlacreuse** [comment]
Good news for you, this already exists!

See: https://getbootstrap.com/docs/4.4/layout/grid/#variable-width-content

https://github.com/twbs/bootstrap/blob/dca1ab7d877bc4b664b43604657a2b5fbe2b4ecb/scss/mixins/_grid-framework.scss#L24-L27

https://github.com/twbs/bootstrap/blob/dca1ab7d877bc4b664b43604657a2b5fbe2b4ecb/scss/mixins/_grid-framework.scss#L43-L45

**Comment by tomasts248** [comment]
Then why is not working? already tried it... seems like a bug then

**Comment by mischa-s** [comment]
I've run into this today @tomasts248 did you ever figure it out?

**Comment by Snippet24816** [comment]
I honestly don't remember...

**Comment by mischa-s** [comment]
For future reference, I've ended up using `<div class="col-12 col-md-3 flex-md-grow-1">` as `col-12 col-md-auto` wasn't working for me
