### ISSUE TITLE
SVG no more displayed in tooltips

### ISSUE THREAD

**Issue by imabot2** [twbs/bootstrap#29858]
With the previous versions of Bootstrap, inline SVG were displayed in tooltips. With the current version, inline SVG are not displayed. I made a JSFiddle to show the problem :

[https://jsfiddle.net/Imabot/3c9tnz6h/6/](https://jsfiddle.net/Imabot/3c9tnz6h/6/)

**Comment by mdo** [comment]
This is very likely due to the change we needed to make to our tooltips and popovers for sanitizing the HTML (due to XSS concerns). You'll need to whitelist the element. See the [tooltips options docs](https://getbootstrap.com/docs/4.4/components/tooltips/#options) for more information.

**Comment by imabot2** [comment]
Thank you. I finally was able to do what I wanted, but I spend a lot of time trying to understand the [documentation](https://getbootstrap.com/docs/4.4/getting-started/javascript/#sanitizer). Maybe, the documentation would gain to be clarified.
