### ISSUE TITLE
IE: docs, search box appearance

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29855]
The search box looks a bit odd:
![image](https://user-images.githubusercontent.com/11559216/70851665-374ee100-1e98-11ea-84d1-602b5f55c0a3.png)

**Comment by ysds** [comment]
@MartijnCuppens I cannot reproduce this in the latest documentation. Would you check again?

![image](https://user-images.githubusercontent.com/4065765/74521727-3c461480-4f5d-11ea-8fda-b210c1b97435.png)

**Comment by MartijnCuppens** [comment]
Indeed!
