### ISSUE TITLE
Add Material Design Icons to documentation

### ISSUE THREAD

**Issue by PanderMusubi** [twbs/bootstrap#29860]
Please list [Material Design Icons](http://materialdesignicons.com/bootstrap) in https://getbootstrap.com/docs/4.4/extend/icons/

The maintainer has to choose to add this listing under `Preferred` or under `More options`

Motivation for supporting these icons is the combination of the design quality (based on Material Design) and the quantity obtained by remixing.

**Comment by XhmikosR** [comment]
You can always make a PR and someone will review.

**Comment by mendozagioo** [comment]
Google Material icons is added in https://getbootstrap.com/docs/4.4/extend/icons/

**Comment by MartijnCuppens** [comment]
> Google Material icons is added in getbootstrap.com/docs/4.4/extend/icons

Indeed, closing this.
