### ISSUE TITLE
Should row-cols-* support auto-sizing?

### ISSUE THREAD

**Issue by kosmiq** [twbs/bootstrap#29866]
Bootstrap 4.4.0 added the row-cols-* classes (awesome job btw, so nice to have).

I did notice that it does not add classes for autosizing columns based on breakpoints and that might be something to add.

Consider the following case:
- For small devices we set `.row-cols-2`
- For medium devices `.row-cols-md-4`
- But for some reason we might want large devices to auto-size the columns, thus arises the need for `.row-cols-lg-auto` (not currently existing)

This is currently solvable by setting `.row-cols-2.row-cols-md-4` on the row and then setting `.col-lg-auto` on the individual cols.

I think that this addition would give even greater flexibility in using the new .row-cols without the need to add classes to the nested columns.

I can create a PR for it, if we decide that it is a worthwhile addition. I read through parts of the discussion with row-cols but didn't manage to find anything regarding this (sorry if I have missed any prior discussions about it).

**Comment by MartijnCuppens** [comment]
> sorry if I have missed any prior discussions about it

Nope, you haven't afaik. Your request makes sense, I might include this in the new grid (see https://github.com/twbs/bootstrap/pull/28517), or do a separate PR if it gets merged.
