### ISSUE TITLE
I can't do search directly in getbootstrap.com!!

### ISSUE THREAD

**Issue by Navid61** [twbs/bootstrap#29865]
Hi
it seems search field in getbootstrap.com is disabled! I can't find document by search in getbootstrap.com

**Comment by MartijnCuppens** [comment]
Seems to work fine here:
![image](https://user-images.githubusercontent.com/11559216/70974640-84a19d00-20a8-11ea-8ec6-eaa6006e59a3.png)

**Comment by Navid61** [comment]
I captured a video from my screen, I attached that below
I don't know why it didn't work on my browser 🤔

**Comment by MartijnCuppens** [comment]
@Navid61, could you do a hard refresh in your browser and check if that fixes your issue?

**Comment by Navid61** [comment]
I think I found where is my problem, it seems my ISP filtered or banned some services which search field need to that if it want run correctly, Because when I search through Tor-Browser I had't any problem, I should find out which service or services closed by Iranian governments

https://easyupload.io/lww7aw    --this video show my problem
https://easyupload.io/ykisor       --this video show my problem fixed by tor-browser!
@MartijnCuppens I think my problem is associated to filtering problem in Iran,

**Comment by MartijnCuppens** [comment]
Ok, thanks for reporting this. I don't think there's much we can do from our side.
