### ISSUE TITLE
Unused navbar brand height variable

### ISSUE THREAD

**Issue by Miqueliu** [twbs/bootstrap#29861]
Why the `$navbar-brand-height` Sass variable is not used (in Bootstrap 4)? It is defined in variables file ("scss/_variables.scss") but not applied in any code line.

Perhaps, it would has to be appeared for usual logo images, as:
> ``` scss
> .navbar-brand img {
> 	height: $navbar-brand-height;
> }
> ```

**Comment by ffoodd** [comment]
It's currently used to [compute `$navbar-brand-padding-y`](https://github.com/twbs/bootstrap/blob/e2530bf3125849fcd6a9f0bdb832a7a76c52f63a/scss/_variables.scss#L731).

Might be done another way, but it is used :)

**Comment by Miqueliu** [comment]
Yes, I am aware of this size calculation. But it has no sense if it is not assigned to any element, since... Why is an image padded in relation to its height if this precised height is not defined to anything? It is not understandable.

**Comment by mdo** [comment]
Closing as this is staying as-is I think. Could maybe try something else with flexbox, but unsure if it'd have the same effect without introducing new issues.
