### ISSUE TITLE
Add option for treating `<caption>` in table as a table title above the table

### ISSUE THREAD

**Issue by cdmo** [twbs/bootstrap#29879]
Before opening:

I read https://github.com/twbs/bootstrap/issues/28499 and would like to request an additional configuration instead of a reversion.

I think it's pretty common to want to have a table's caption come before the table, see [Example 1](https://www.w3.org/WAI/tutorials/tables/caption-summary/#identifying-a-table-using-a-caption) from Web Accessibility Tutorials' Caption & Summary. 

It'd be nice to be able to apply a class to a caption and have it override default behavior like:

```css
    padding-top: .75rem;
    padding-bottom: .75rem;
    text-align: left;
    caption-side: top;
    /** insert additional properties to mimick a, say, h2
}
```

**Comment by artopaavola** [comment]
Also, the html spec says that the (optional) caption element must be the first child element of a table element. So caption is the first element inside a table which is read for example for screenreader users. Putting it below the table content with css messes with the reading order which will be confusing for sighted screenreader users.

**Comment by cdmo** [comment]
Thanks @artopaavola I didn't know that bit, all the more reason.
