### ISSUE TITLE
Equal Height Columns not working outside of viewport on Safari and IE

### ISSUE THREAD

**Issue by panosru** [twbs/bootstrap#29876]
### Problem Description:
I have 3 columns and I need them to have equal height. For Safari, the equal height works only up to the dimensions of the viewport.

To provide a visual representation:

This is how it is working on Chrome, Firefox, Opera and Edge for Mac:
![chrome-scroll](https://user-images.githubusercontent.com/400362/71096708-755d4500-21b7-11ea-801a-42561dab8a55.gif)

And that is how it behaves in Safari (and IE based on what a friend of mine told me):
![safari-scroll](https://user-images.githubusercontent.com/400362/71099084-61b3dd80-21bb-11ea-857a-7d054e1ec963.gif)

### Tested On:
**OS:** macOS 10.15.2

**Browsers Tested:**
- Google Chrome _(Version 79.0.3945.88)_
- Opera _(Version 65.0.3467.72)_
- Microsoft Edge _(Version 81.0.367.0)_
- Firefox _(Version 71.0)_
- **Safari _(Version 13.0.4 (15608.4.9.1.3))_**
- **IE _(Unknown version, I asked a friend of mine over messenger to test it)_**

**Bootstrap Versions:**
- v4.0.0 - v4.1.3
- **\>=v4.2.0**

Affected browsers and bootstrap versions are marked as bold

I haven't tested ~v3 of Bootstrap, I'm trying to keep up with latest version.

### Test Case:
Does not work with Bootstrap \>=v4.2.0 on Safari and IE
https://codepen.io/panosru-the-flexboxer/pen/ExaZQVY

Works with Bootstrap v4.1.0 on Safari and IE
https://codepen.io/panosru-the-flexboxer/pen/rNajJeE

A second a bit more complicated example that resembles better a closer to real-world scenario:
https://codepen.io/panosru-the-flexboxer/pen/ExaZQpK
If you modify the Bootstrap version from v4.2.0 to earlier, it will work, but with v4.2.0 and higher it doesn't _(on the affected browsers of course)_

#### Example 1: 
```html
<!DOCTYPE html><html><head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <link rel="stylesheet" type="text/css" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
</head>
<body>
<div class="container-fluid vh-100">
  <div class="row h-100">
    <header class="col-12 col-lg-2 p-0 d-flex flex-column flex-md-row flex-lg-column bg-primary">
      <div class="small content">
        1 of 3
      </div>
    </header>
    <section class="col-xs-12 col-lg-3 order-1 order-md-2 bg-secondary">
      <div class="medium content">
        2 of 3
      </div>
    </section>
    <section class="col order-1 order-md-3 bg-success">
      <div class="big content" style="height: 2000px;">
        3 of 3
      </div>
    </section>
  </div>  
</div>
</body></html>
```
_That is a bare minimum code that I could post for testing, it is not production quality by any means._

#### Example 2:
```html
<!DOCTYPE html><html><head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <link rel="stylesheet" type="text/css" href="//stackpath.bootstrapcdn.com/bootstrap/4.2.0/css/bootstrap.min.css">
</head>
<body>
<div class="container-fluid vh-100">
  <div class="row h-100">
    <header class="col-12 col-lg-2 p-0 d-flex flex-column flex-md-row flex-lg-column bg-primary">
      <div style="height: 100px;">
        Object 1 of 1st column
      </div>
      <div style="height: 100px;">
        Object 2 of 1st column
      </div>
      <div style="height: 150px;">
        Object 3 of 1st column
      </div>
      <div style="height: 200px;">
        Object 4 of 1st column
      </div>
    </header>
    <section class="col-xs-12 col-lg-3 order-1 order-md-2 bg-secondary">
      <div style="height: 300px;">
        Object 1 of 2nd column
      </div>
      <div style="height: 500px;">
        Object 2 of 2nd column
      </div>
    </section>
    <section class="col order-1 order-md-3 bg-success">
      <div style="height: 200px;">
        object 1 of 3rd column
      </div>
      <div style="height: 700px;">
        Object 2 of 3rd column
      </div>
      <div style="height: 500px;">
        Object 3 of 3rd column
      </div>
    </section>
  </div>  
</div>
</body></html>
```

Any help or suggestion would be highly appreciated.

Thanks in advance!

**Comment by neralex** [comment]
Add the class h-100 to the divs inside the col-containers instead to the row-container.

**Comment by panosru** [comment]
Removed the `vh-100` from parent container seems to solve the issue.

so, converting `<div class="container-fluid vh-100">` to `<div class="container-fluid">` will solve the problem.

I followed the Bootstrap changes related to layout, and I saw that the class `vh-100` was introduced on v4.2.0; thus on the code above it worked for versions earlier to v4.2.0.

But, my question remains, why it is working on the other browsers and not in Safari and IE? Who is handling it properly? Safari & IE or the others?

**Comment by neralex** [comment]
Nut sure, but I guess the IE needs also 100vh on the body-element.
```
<body class="d-flex flex-column min-vh-100">
	<div class="container-fluid min-vh-100">
		<div class="row h-100">
			<header class="col-12 col-lg-2 p-0 d-flex flex-column flex-md-row flex-lg-column bg-primary">
				<div class="small content">
					1 of 3
				</div>
			</header>
			<section class="col-12 col-lg-3 order-1 order-md-2 bg-secondary">
				<div class="medium content">
					2 of 3
				</div>
			</section>
			<section class="col order-1 order-md-3 bg-success">
				<div class="big content" style="height: 1000px;">
					3 of 3
				</div>
			</section>
		</div>
	</div>
</body>
```

**Comment by panosru** [comment]
@neralex Thanks for the suggestion, I will check it out once I'll have access to IE to do some testing :)
