### ISSUE TITLE
Master package json is not set to version 4.4.1

### ISSUE THREAD

**Issue by dave0783** [twbs/bootstrap#29873]
https://github.com/twbs/bootstrap/blob/master/package.json

![ss](https://user-images.githubusercontent.com/2146963/71026842-0230d180-20d8-11ea-8fdc-1a06b0975e42.png)

**Comment by ffoodd** [comment]
`master` is currently v5 under development, I guess it does not need an up-to-date `package.json` until v5 is properly released, does it?

**Comment by dave0783** [comment]
I would think v5 would be being developed in its own branch and then merged into master; that said I don’t know their branching strategy; regardless I would still think the package.json would reflect the latest tag and and not a previous one until the tag was updated to v5

**Comment by mdo** [comment]
@ffoodd is correct, `master` is primary dev branch.
