### ISSUE TITLE
Will there be support (better way too use) for the ugly "CSS Grid Layout"?

### ISSUE THREAD

**Issue by DominikErnst** [twbs/bootstrap#29881]
Hi there,
I would like a beautiful abstraction of the CSS Grid layout. Are there plans to support CSS Grid Layout with Bootstrap 5?

https://www.w3schools.com/css/css_grid.asp

**Comment by MartijnCuppens** [comment]
No, Bootstrap 5 will support Internet Explorer 11 which doesn't fully support CSS Grid. We will probably add this in BS6.

**Comment by warudin** [comment]
Bootstrap [announced](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/) that support for Internet Explorer was dropped for version 5. I personally would've loved it if Bootstrap would adopt CSS Grid as has so many advantages. But I guess we still have to wait for Bootstrap 6 to arrive..

**Comment by MartijnCuppens** [comment]
See https://github.com/twbs/bootstrap/pull/31813
