### ISSUE TITLE
Annoying deprecation warning for: text-emphasis-variant

### ISSUE THREAD

**Issue by flexjoly** [twbs/bootstrap#29884]
Hi,

Recently I updated to the latest v.4.4.1 version and now we get numerous warnings: 
```
WARNING: `text-emphasis-variant()` has been deprecated as of v4.4.0. It will be removed entirely in v5.
```

But this mixins is used by _text.scss from bootstrap itself. So it seems I cannot do anything to solve the warning. 
Or am I doing anything wrong?
Otherwise can this be fixed, for it is really anoying, giving tens of warnings on just 1 issue, while doing nothing wrong 😵 

Greetz, flexJoly

**Comment by MartijnCuppens** [comment]
Bootstrap itself suppresses this warning by setting `$ignore-warning: true`. You probably load the mixin in your custom code or you also load older bootstrap code too.

**Comment by flexjoly** [comment]
Oops!!!
Found it, sorry!

I overlooked the @ignore-warning parameter, when we used the mixin ourselves. 

@MartijnCuppens tx, I just found it indeed.

Sorry!!! 😳
