### ISSUE TITLE
d-flex has !important attached to it

### ISSUE THREAD

**Issue by goelrohan6** [twbs/bootstrap#29880]
It causes problems in frameworks like vue.js in which you use directives to show hide elements which apply `display:none` style which doesn't work with elements with d-flex applied to them as d-flex has `!important` attached to it.
Is there a reason why !important is there in d-flex

**Comment by ffoodd** [comment]
Hi there,

It's a utility class, meaning that if you're using you **really** want it to apply. Also: if you don't want it ao apply, don't use it.
In a hide/show component — assuming you are already good on the accessibility side, using the same ARIA design pattern like in Bootstrap's collapse component —, you probably want to toggle both classes: switching between `d-flex` and `d-none` will show and hide your component.

Does this sound possible to you?

**Comment by goelrohan6** [comment]
Hey,
I'm sorry but I didn't get the point because it is a utility class so it has `!important` attached.

I can do that with toggling d-none for sure but it causes issues in vue.js v-show
Check out this issue for instance - https://github.com/vuejs/vue/issues/3761#issuecomment-249686732

**Comment by goelrohan6** [comment]
Also @ffoodd 
I am sure anyone with so specific use case easily add a specific selector to apply `!important` to the property. With that argument, every property in the bootstrap class should have `!important` as everything is used as a utility class.

**Comment by mdo** [comment]
All our utilities are designed with this in mind. Not everything in Bootstrap is a utility—we have components, layout tools, modifiers, and helpers, too. Utilities are immutable classes that always work with whatever they are being applied to. As such, they receive the important flag.
