### ISSUE TITLE
v4.4.1 mixin bg-variant parameter error

### ISSUE THREAD

**Issue by php4world** [twbs/bootstrap#29895]
node_modules\bootstrap\scss\utilities\_background.scss

@each $color, $value in $theme-colors {
  @include bg-variant(".bg-#{$color}", $value**, true**);
}

Here is an extra parameter "true", Cause compilation to fail.

**Comment by MartijnCuppens** [comment]
That snippet calls this mixin:

https://github.com/twbs/bootstrap/blob/e2530bf3125849fcd6a9f0bdb832a7a76c52f63a/scss/mixins/_background-variant.scss#L5-L16

which should work?

**Comment by MartijnCuppens** [comment]
Closing this, the default build seems to work fine. If there's anything we're missing, please let us know

**Comment by Artistan** [comment]
deprecated in 4.4.0 and then removed in 4.4.1. 
WOW, maybe wait until v5 so you do not break everyone's code!!!  
Minor release breaking changes, fun time.... not.

**Comment by Artistan** [comment]
This even states that it will be removed in v5 https://github.com/twbs/bootstrap/pull/28938/files

but it is not in 4.4.1

**Comment by MartijnCuppens** [comment]
@Artistan,

Please watch your tone of voice.

As I linked in https://github.com/twbs/bootstrap/issues/29895#issuecomment-568890839, the mixin is still present in `v4`.
