### ISSUE TITLE
Modal event doesn't provide any information about key or keyCode

### ISSUE THREAD

**Issue by kossidts** [twbs/bootstrap#29894]
It seems to be no way to identify which action actually triggers the `hidePrevented.bs.modal` event on a modal.  
I couldn't find a way to make set the backdrop to static (don't close the modal on a click outside) and at the same time make the modal close on escape key keyboard. 
It would be very helpful if the `hidePrevented.bs.modal` event does provide the key/Code. Currently, they are undefined:
```js 
$theModal.modal({
    'keyboard': true,
    'backdrop': 'static',
})
// ....
$theModal.on('hidePrevented.bs.modal', (event) => {
    console.log(event)
});

// console output
...
key: undefined
keyCode: undefined
...
```

**Comment by alecpl** [comment]
Similar to #24010. It would be great if Bootstrap events contained reference to the original event.

**Comment by Johann-S** [comment]
Agree with @alecpl, it'll be tackled when #24010 will be closed
