### ISSUE TITLE
[feature] Easy multiple items slider,  supporting `grid` and `flex`, with native fallback on mobile. need discussion

### ISSUE THREAD

**Issue by wtorsi** [twbs/bootstrap#29928]
Hello everyone.

In the last project i thought about horizontal/vertical slider for thumbs, partners and other things which everybody use for scrollable lists, and which can be slid right and left/up and down, and i hope i found a easy solution. 

So, my idea was to provider the
- Minimal weight slider supporting bootstrap grid system. 
I want `carousel` behaviour (not all behaviour for now), but for multiple items. As a note, there are a lot of supporting Google queries which make standard bootstrap carousel works as I want, but they a very complicated and not unique - you always need cheating solutions, need more code. 
I want to use usual `grid` and `flex` utilities to create the slider which you need. 
At this moment I've dropped infinite loop at all, because I don't have tests which passing this option in usability. Those kind of elements usually come from _design_ and _common things for nowage web_. 

- No nav slider utils on mobile (nav is redundant when you have swipes). I want native browser swiping (because it's cheaper for fx). 
- I want easy and fast customisation with `html` only, because it's independent from other languages.
 
As the result, I came up to the following solution, and I want to discuss it (it has bugs). Because it needs more work, but I think it can become a new component.

https://github.com/twbs/bootstrap/pull/29929

Here is the fiddle:
https://jsfiddle.net/wtorsi/2agmz9cp/9/

And here is the vertical:
https://jsfiddle.net/wtorsi/7g0zdyv5/5/

**Comment by MartijnCuppens** [comment]
We already have the carousel, I don't think we need another component like this?

/CC @twbs/team

**Comment by wtorsi** [comment]
Hi, @MartijnCuppens, thanks for you attention.

Yes your are right, but it was not my idea.
At this moment carousel is good only for **one** item.
My idea is to add support of multiple `grid` items with simple and native/browser markup.
It's better to compare my idea with https://owlcarousel2.github.io/OwlCarousel2/ or smth kind of, rather than with bootstrap `carousel`.

**Comment by XhmikosR** [comment]
Ideally this shouldn't be a new component. I'm definitely in favor of adding the feature, see an old attempt of mine in #28210 and we track this in #29130

**Comment by mdo** [comment]
Closing as a won't fix—`.carousel-item`s can contain just about any HTML and CSS you want, so this is possible. Leaving #29130 open for now, though.
