### ISSUE TITLE
Install dependencies problem [node-sass; file missing]

### ISSUE THREAD

**Issue by AKopytenko** [twbs/bootstrap#29922]
**SORRY! I was building an old version [BS 4.0.0] :)**
===================

An error occurs during dependency installation:
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-ia32-64_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-ia32-64_binding.node":
> 
> HTTP error 404 Not Found

There are no **win32-ia32-64_binding.node** file in SASS developer repository:
https://github.com/sass/node-sass/releases/tag/v4.7.2

If possible, please check the compatibility of the assembly with other versions of node-sass.

**Comment by XhmikosR** [comment]
Old versions are unsupported. You should ask in node-sass or just try to update it in your fork.
