### ISSUE TITLE
Cli to build custom bootstrap builds?

### ISSUE THREAD

**Issue by slorber** [twbs/bootstrap#29926]
Hi,

As far as I understand, there is no more an official bootstrap online customizer in v4, but we need to handle the build ourselves as part of our app's build process.

I think it would be cool to simplify the customization of bootstrap by offering a cli.

```
npm install -g bootstrap

bootstrap build customBootstrap.scss
```

In my case, I only need the grid system with customized options as a one-shot. Setting up Webpack to handle this seems overwhelming and inefficient as every webpack restart will rebuild the scss.

Having a cli would be helpful to enable users to easily build custom bootstraps, without you having to maintain the infrastructure required to build it online. 

Or at least the doc should probably mention how we should build it as a one-shot if we don't want to include bootstrap build in our build process.

I've found those 2 tools but they do not really fit my needs as I need only grid + ability to customize vars, and may not be using the version of bootstrap I want. 

https://johann-s.github.io/bs-customizer/
http://bootstrapcustomizer.com/

A cli would be better as you would get the bootstrap output for the version of bootstrap you installed. 

```
npm install -g bootstrap@4.4

# builds bootstrap 4.4 custom CSS
bootstrap build customBootstrap.scss
```

Also, it would enable people to integrate this building with a custom npm script, for example in a postinstall script. It would be way simpler than having to setup Webpack.

**Comment by XhmikosR** [comment]
The first customizer should fit your needs, but if you find any issues feel free to submit a PR there.

We don't plan to maintain a customizer ourselves. @Johann-S's customizer was a first attempt and it should do work, but time and motivation are serious problems so feel free to support him if you want.

Do note that I personally find it handy to have a customizer. We just need it as a separate project and we need more people to help maintain our side-projects.

Finally, you can always just include the Sass files you need to. If you just want the grid, you can include the mandatory files like variables and functions and then just only the grid.
