### ISSUE TITLE
display-*-1

### ISSUE THREAD

**Issue by AndreyChursin** [twbs/bootstrap#29930]
I think it's will be good to added "display-*-1" classes, because it's can be some bug for different form factor.
e.x. on desctop 'display-4' it's so good ( http://joxi.ru/Vrwj4NGc87LoWA ), but in small mobile devices it's look very big ( http://joxi.ru/Q2KXNGkiwLeOVA )

**Comment by florianlacreuse** [comment]
You could use (Bootstrap) Responsive Font Size (aka RFS): https://getbootstrap.com/docs/4.4/content/typography/#responsive-font-sizes

**Comment by MartijnCuppens** [comment]
For font sizes you can use RFS indeed. See it in action here:
https://twbs-bootstrap.netlify.com/docs/4.3/content/typography/#display-headings
