### ISSUE TITLE
Enable OpenSearch

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#29949]
It would be nice to use open search to search through the docs. I made a PR (https://github.com/twbs/bootstrap/pull/29872), but first we got to figure out how to deal with caching and have a solution for the absolute urls in the config xml. Maybe we should also make a separate search page in the docs.

**Comment by christiford** [comment]
https://static.xx.fbcdn.net/rsrc.php/v3/yv/l/0,cross/4n1lj2H7pYc.css?_nc_x=Ij3Wp8lg5Kz

**Comment by mdo** [comment]
Closing as stale.
