### ISSUE TITLE
Toast is shown behind input-group

### ISSUE THREAD

**Issue by vicovictor** [twbs/bootstrap#29942]
Using Chrome and Mac.

Here's the markup:

```
<div class="container toast-container">
    <div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false" data-delay="3000">
      <div class="toast-header">
        <strong class="mr-auto">Blog</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <i class="f7-icons">multiply</i>
        </button>
      </div>
      <div class="toast-body">
        User not found.
      </div>
    </div>
    <script>
      $('.toast').toast('show');
    </script>
</div>
<div class="input-group mb-2">
  <!-- <div class="input-group-prepend">
    <div class="input-group-text">@</div>
  </div> -->
  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Username">
</div>
```

Screenshot:

<img width="304" alt="Screenshot 2020-01-01 at 3 43 06 PM" src="https://user-images.githubusercontent.com/397034/71639195-74dfa680-2cad-11ea-9f95-4869c31fda67.png">

Bug:
So I have deduced it to `input-group` issue (commented out other stuff). When I have a toast that's meant to be `position: absolute`  to float above everything else, `input-group` would be fighting with toast in terms of z-index.

**Comment by florianlacreuse** [comment]
Can you provide a (live) reduced test case? Thanks

**Comment by vicovictor** [comment]
Thanks for the suggestion. Looks like it could be something wrong on my end. Will close this for now.

**Comment by vicovictor** [comment]
Looks like it happens when the toast is above the input-group. The toast is with position absolute. See https://jsfiddle.net/zctv512q/1/

**Comment by florianlacreuse** [comment]
As I understand it, it's just a CSS issue. Use a higher `z-index` on the toasts container can do the job, something like: https://jsfiddle.net/sh6e03xL/1/.

**Comment by vicovictor** [comment]
Don't you think Toast should have highest z-index? (https://getbootstrap.com/docs/4.3/layout/overview/#z-index)

**Comment by florianlacreuse** [comment]
I'm not sure, according to the docs:

https://getbootstrap.com/docs/4.3/components/toasts/#overview

> Please note that you are responsible for positioning toasts.

But I'll let the BS team answer that.

**Comment by mdo** [comment]
Our docs clearly state, "Please note that you are responsible for positioning toasts." z-index is part of the positioning. See https://getbootstrap.com/docs/4.4/components/toasts/ for details and recommendations.
