### ISSUE TITLE
@include form-control-focus($ignore-warning: true); causes compile error

### ISSUE THREAD

**Issue by tatsujb** [twbs/bootstrap#29957]
- Windows 10
- Chrome Version 76.0.3809.132 (Official Build) (64-bit)

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L40

this line causes any React/ Vue or Angular project including bootstrap v.4.3 and above fail at compilation. (I have  `"bootstrap": "^4.4.1"`, it's the latest I could get).

I see you've fixed this in the upcoming 5 but in the absence of 5 a hotfix is needed, or you should release 5.

**Comment by MartijnCuppens** [comment]
> @include form-control-focus($ignore-warning: true); causes compile error

What kind of error? Could you provide the output?

**Comment by tatsujb** [comment]
```undefined
^ No argument named $ignore-warning. 
    ╷ 
40 │ @include form-control-focus($ignore-warning: true);```

**Comment by MartijnCuppens** [comment]
The `form-control-focus` mixin does accept the `$ignore-warning` variable:
https://github.com/twbs/bootstrap/blob/0d1aee6a2fecc865066c90e85422e192ca69ba34/scss/mixins/_forms.scss#L13

You probably have a reference to an older codebase somewhere in your code.

**Comment by tatsujb** [comment]
I'll check it out.
