### ISSUE TITLE
4.4.1 Why is there no hide method in tab.js?

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#29954]
https://github.com/twbs/bootstrap/blob/master/js/src/tab.js
https://getbootstrap.com/docs/4.4/components/navs/#methods
https://codepen.io/zhangchenglin/pen/PowEqav

Why is there no .tab ('dispose')When using Navs, use the button-group style instead of the default nav-tabs style, and then do not use the data attribute data-toggle = 'tab' in the button in the button-group. Use pure JavaScript and jQuery. In the case of the hide method, can it only be solved by classList.remove ('active', 'show')?In addition, the two methods event.target and event.relatedTarget mentioned at the bottom of the tutorial are not applicable to the current form.Do you need to add a hide method?

**Comment by MartijnCuppens** [comment]
One of the tabs is always supposed to shown I guess?

**Comment by zhangchenglin** [comment]
@MartijnCuppens  
是的，如果不选择按钮all 的时候，其他按钮总是显示一个标签。
选择 all ，会显示所有标签。

Yes, if the all button is not selected, the other buttons always show a label.
 Selecting all displays all labels.

**Comment by MartijnCuppens** [comment]
@zhangchenglin, please leave out the Chinese comments. I'm not following what you mean, could you provide a demo of your issue?

**Comment by zhangchenglin** [comment]
@MartijnCuppens 

I submitted a feature suggestion
 Without the hide method, it would be inconvenient to implement the sample code structure in my first question.
 Do you have a better way?

**Comment by zhangchenglin** [comment]
@MartijnCuppens  


` https://github.com/zhangchenglin/tools/blob/df64e8f49859de3714ee3d49bda80e80802b0e1f/tools_static_src/js/index.js
`

**Comment by Johann-S** [comment]
We should always keep an active tab.

What's your use case @zhangchenglin ?

**Comment by zhangchenglin** [comment]
@Johann-S 

Is there a label that keeps everything displayed?

**Comment by MartijnCuppens** [comment]
> We should always keep an active tab.

I agree, for other use cases, use our [collapse methods](https://getbootstrap.com/docs/4.4/components/collapse/#methods).
