### ISSUE TITLE
Prefix Bootstrap CSS

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#29953]
Hi, I'm not totally sure whether this has already been asked, but I'm trying to implement Bootstrap into a standalone custom component that I'm building, I'm looking at using the Bootstrap CSS, however, I'd like to prefix all the Bootstrap CSS classes with a custom prefix of my choice? E.g: `.mycomponent__col-lg-4`, I'm sure this was available with Bootstrap 3?

**Comment by florianlacreuse** [comment]
Duplicate of #29547?

**Comment by mdo** [comment]
> I'm sure this was available with Bootstrap 3?

It was not.

> Duplicate of #29547?

Yup! (Sorry I don't have a better answer for y'all, not something we have a plan for at this time.)
