### ISSUE TITLE
[4.4.1] Modal doesn't close when escape key is pressed and backdrop option like 'static'

### ISSUE THREAD

**Issue by mendozagioo** [twbs/bootstrap#29978]
This issue is due to a question in Slack by: Asif Qureshi.

Tested on:
- MacOS 10.15.2
- Firefox 72

Description:
A new documentation of v4.4.1 describe that modals doesn't close when is used backdrop option in 'static', that is correct, but only should apply when the keyboard option is false, and that is not happens, so, if you want to use keyboard option in false or true, the modal doesn't close.
The documentation also describes:

Name | Type | Default | Description
-- | -- | -- | --
keyboard | boolean | true | Closes the modal when escape key is pressed

With version 4.3.1 this didn't happen

Test case:
v4.4.1: https://codepen.io/asif8q/pen/zYxRobw
v4.3.1: https://codepen.io/asif8q/pen/LYEQxYm

**Comment by XhmikosR** [comment]
Fixed by #29986
