### ISSUE TITLE
Windows 10: Edge Browser + Modal window with form elements on focus can see unwanted borders 

### ISSUE THREAD

**Issue by SridhanyaG** [twbs/bootstrap#29983]
Operating System : windows 10 and (size of text of display is 150% recommended by windows)
Browser : Edge browser
<img width="448" alt="Bootstrap4edge_issue" src="https://user-images.githubusercontent.com/17043940/71967203-f47af180-3228-11ea-910c-e93a842a88de.png">
JSFIDDLE: https://jsfiddle.net/sridhanyag/k0cqgsf8/

Summary of the issue 
Please refer to screenshot above. When focus moves between input elements we can see lines around the element and it stays for ever

** Note it is replicable only in windows 10 150% (is the size of apps and text and recommended by windows 10)

**Comment by ysds** [comment]
This is a browser issue, unfortunately there's nothing we can do.
