### ISSUE TITLE
alert-dismissible close button not clickable with stretched-link

### ISSUE THREAD

**Issue by LeaTark** [twbs/bootstrap#29985]
The close button of a dismissible alert is not clickable if the alert contains a stretched link.
https://codepen.io/LeaTark/pen/bGNLyZy

It works if the close button is given a z-index greater than that of stretched-link.
https://codepen.io/LeaTark/pen/MWYQMej

**Comment by mdo** [comment]
This makes sense as as the purpose of a stretched link is to overlay everything within the parent element. If you need multiple tap targets overlapping that, you'll have to customize those elements to do so.

/cc @MartijnCuppens for thoughts before closing though.

**Comment by MartijnCuppens** [comment]
Maybe we can add some `z-index` utilities to fix issues like this so that we have a solution for other components too?

**Comment by mdo** [comment]
Would love to hear how we can create a z-index scale for utilities. Right now our only scale is for our components, which I don't think we'd want to put as utilities. What other use cases other than stretchy links need solving here? Perhaps a sticky/fixed top (one of our current scale)? Anything else?

**Comment by ffoodd** [comment]
@mdo @MartijnCuppens I don't think another scale would solve this kind of issues. A single utility with `z-index: 1` would solve the issue (no need for a higher value in this example case).

Combined with our `position` utilities, it should be enough to solve most of those cases. And we may only mention this in the stretched link docs.

Thoughts?

**Comment by ffoodd** [comment]
Another way around: creating a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) on `.stretched-link`.

The simplest way is `isolation: isolate` but [it's not supported by IE11 nor Edge Legacy](https://caniuse.com/#search=isolation); same issue with `contain: layout;` or `paint`.

The working solutions (for both v4 and v5) would be:
1. `perspective: 0;`
2. `opacity: .999;`
3. `transform: scale(1);`

[I forked the pen](https://codepen.io/ffoodd/pen/bGVPzKE) so you can play with those solutions.

**Comment by MartijnCuppens** [comment]
I rather don't use those hacks, we either add a z-index to the close button or introduce z-index utilities

**Comment by ffoodd** [comment]
Sounds good to me, but I'd be in favor of a single `z-index: 1` utility for now.

**Comment by ffoodd** [comment]
BTW, this is somehow related to #29804—missing stacking context, too.
