### ISSUE TITLE
IE11 input-group inside form-inline, width is 0

### ISSUE THREAD

**Issue by cooljeffro** [twbs/bootstrap#29987]
Browser: IE 11 (doesn't occur in other browsers)
OS: Windows 10
Bootstrap: 4.4+ (doesn't occur in 4.3)

When using input-group inside a form-inline, the width of the input is 0.  This can be seen on the bootstrap website when using IE11:

https://getbootstrap.com/docs/4.4/components/forms/#auto-sizing

Does not occur in bootstrap 4.3:
https://getbootstrap.com/docs/4.3/components/forms/#auto-sizing

**Comment by jkamleh** [comment]
**Issue is in scss/_input-group.scss:**

IE11 has an issue with Flexbox and requires:
`flex: 1 1 auto;`
and a width to be set to fix this
`width: 1%;`

Looks like these were previously in there:
> // Add width 1% and flex-basis auto to ensure that button will not wrap out
    // the column. Applies to IE Edge+ and Firefox. Chrome does not require this.

[https://github.com/twbs/bootstrap/blob/487e5f8b827572892ba73efeabff14b1397d246b/scss/_input-group.scss](https://github.com/twbs/bootstrap/blob/487e5f8b827572892ba73efeabff14b1397d246b/scss/_input-group.scss)
