### ISSUE TITLE
Extra small device equal columns issue

### ISSUE THREAD

**Issue by vishwa12345** [twbs/bootstrap#29995]
According to Bootstrap [Documentation](https://getbootstrap.com/docs/4.0/layout/grid/) if I give the only **col**, the number of columns will be divided into equal size for the given number of div elements. 
 I tried with [CodePen](https://codepen.io/vpcodepenuser/pen/vYERwMp)
Till 514px all 12 columns will be in the same row, For 513px the last column will take the second row. 

And I tried with removing col padding-right. Then it will work fine. Please let me know whether my understanding is not correct or Bootstrap issue.

Thanks in Avance

**Comment by MartijnCuppens** [comment]
It's because width of the content within the cols exceeds the column width. If you do not want this effect, you can add the `.flex-nowrap` class to `.row`. This will cause an overflow though.
