### ISSUE TITLE
Compiling negative border-radius by "0px"

### ISSUE THREAD

**Issue by endcoreAK** [twbs/bootstrap#29994]
If i change the variable

`$border-radius: .25rem !default;` to  `$border-radius: 0px !default;`

all the variables wich contain **subtract** like

`$card-inner-border-radius: subtract($card-border-radius, $card-border-width) !default;`

will result in a negative border-radius wich means an invalid property value:

`.card-header:first-child { border-radius: -1px -1px 0 0; }`

**Comment by mendozagioo** [comment]
@endcoreAK if you need to remove all borders, just modify: `$enable-rounded: false`

**Comment by mendozagioo** [comment]
Anyway I added a conditional to avoid negative values ​​with the subtract function

**Comment by mendozagioo** [comment]
So, I return to my original idea: this is not an issue (to me), because if you target is remove rounded, you just need to change to `false` the variable `$enable-rounded` to avoid negative values and it create less code

**Comment by endcoreAK** [comment]
Yes, I usually go this way too, but I forgot to set it to false in one project and that's when I noticed it. Your solution with the additional query is great! :)
