### ISSUE TITLE
/bootstrap/latest/css/bootstrap.min.cs -> v4.0.0 instead of latest ?

### ISSUE THREAD

**Issue by mutantsausagedog** [twbs/bootstrap#30000]
The bootstrap link https://stackpath.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css returns version 4.0.0 instead of the latest 4.4.1 at the time of writing. From the /latest in the path I'd though this would be the current version. 

I thought maybe this might be a error and whatever job updates the "latest" link isn't working, hence reporting in case.

[disclaimer] I'm not a webdeveloper or bootstrap user. I didn't know if this was expected behaviour or accidental, so just raising for consideration. I did search the previous reports but there's a lot of results for these search terms so if this is already raised I apologise.

The only reason I was looking at this was I was going to do a scripted job that compared the version on the local site to the version returned by the "latest" URL and then the job would notified the admin if there was a difference so they could take a look. But of course the git notifications system for new releases already exists.

**Comment by mutantsausagedog** [comment]
I've just read the similar situation with jQuery detailed here: https://forum.jquery.com/topic/what-happened-to-jquery-latest-min-js-on-code-jquery-com which explains why a "latest" url causes problems for projects. I hadn't realised.

As an alternative feature query would a URL that when called returned simply a string of the current release (for example "4.4.1") be possible?

**Comment by XhmikosR** [comment]
@mutantsausagedog you are not supposed to use this. It's not exposed anywhere in the frontend and it's not updated.
