### ISSUE TITLE
Angular 6 with Bootstrap 4 is not working

### ISSUE THREAD

**Issue by debjit93** [twbs/bootstrap#30005]
Only solution I have right now, is to downgrade to bootstrap 3. And straight way it has started working. Please tell me the reason.

**Comment by patrickhlauke** [comment]
you're going to have to be a lot more specific than just "is not working"

**Comment by debjit93** [comment]
okay! I am sending you some screenshots here. "With Bootstrap 4" and "With Bootstrap 3".
--angular.json
![Angular_json](https://user-images.githubusercontent.com/54183616/72220296-4303f500-3575-11ea-9490-d98b5a23d1f6.JPG)
--HTML file
![component_html_file](https://user-images.githubusercontent.com/54183616/72220354-db9a7500-3575-11ea-853d-ed4d02be8daa.JPG)

--Added bootstrap3 to my solution, package.json
![Bootstrap3_in_package json](https://user-images.githubusercontent.com/54183616/72220323-9413e900-3575-11ea-8b2f-966ea6c1da0b.JPG)
--Output
![Bootstrap3 output](https://user-images.githubusercontent.com/54183616/72220363-ee14ae80-3575-11ea-8df6-4d0f64dfb23a.png)

--With bootstrap4, package.json
![Bootstrap4_in_package_json](https://user-images.githubusercontent.com/54183616/72220506-48623f00-3577-11ea-9407-7b8854f609c7.JPG)
--Output
![Bootstrap4_output](https://user-images.githubusercontent.com/54183616/72220507-4d26f300-3577-11ea-9d45-4fb13795bd0f.png)

      **I am not getting this. Thanks for helping me out.**

**Comment by fchiumeo** [comment]
you need read this [migration 3 => 4](https://getbootstrap.com/docs/4.4/migration/)

**Comment by debjit93** [comment]
> 
> 
> you need read this [migration 3 => 4](https://getbootstrap.com/docs/4.4/migration/)

Now it makes sense. They have removed these classes which I was using. Thanks @fchiumeo !
