### ISSUE TITLE
Create standalone accordion component

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30015]
The accordion now is a mixture of cards with a header made of a button and some utility classes. I think it should be a standalone component which is configurable with some Sass variables.

Maybe we should also have a striped (like the [tables](https://getbootstrap.com/docs/4.4/content/tables/#striped-rows)) or flushed (like the [list group](https://getbootstrap.com/docs/4.4/components/list-group/#flush)) variant.

**Comment by geekfreak97** [comment]
what do you mean by stand alone accordiaon
elaborate please??

**Comment by LeaTark** [comment]
This sounds good.

Could a standalone component build in the accessibility guidance of [https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html) ?

My take on it is a horrendous mess and I'd dearly love for it to come out-of-the-box.

[https://codepen.io/LeaTark/pen/PoqovVY](https://codepen.io/LeaTark/pen/PoqovVY)

**Comment by patrickhlauke** [comment]
as the current accordion is a series of disclosure widgets that already has all the required ARIA, and the arrow/home/end controls are optional...sure
