### ISSUE TITLE
Use curentColor by default for SVGs

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30011]
By default SVGs fill with black, but imo it would make more sense to use the currentColor, unless the fill attribute is defined: https://codepen.io/MartijnCuppens/pen/PowaapW?editors=1100

Shall we add this to our reboot @twbs/css-review?

**Comment by patrickhlauke** [comment]
too opinionated for my taste. may end up interfering with styles the authors themselves used for other svgs somewhere on their page if they decided to style those with CSS as well (e.g. if they just had a `svg { fill: blue; }` intentionally in their CSS but no fill attribute, this would override it.

**Comment by MartijnCuppens** [comment]
We could make it a variable, just in case you want your SVGs to be blue by default for example.

We do have styles like this in our reboot already:
https://github.com/twbs/bootstrap/blob/a79a83e7c470015e00387b3c24eb37bab812fe61/dist/css/bootstrap-reboot.css#L78-L86

**Comment by mdo** [comment]
Since we don't use SVGs outside the ones embedded in our CSS, I'm inclined not to offer a default styling here.

**Comment by MartijnCuppens** [comment]
Allright then, I'll stick to `<svg fill="currentColor">...</svg>` for now.
