### ISSUE TITLE
Nested list-group-horizontal inside list-group-flush renders without proper borders

### ISSUE THREAD

**Issue by jarodhanko** [twbs/bootstrap#30027]
Bug reports must include:

- Operating system and version (Windows)
- Browser and version (Tested on Chrome and Firefox)
- Test Case : https://codepen.io/jarodhanko/pen/vYEaoKr
- Bootstrap Version: 4.4.1

Perhaps this is a bit of an edge case or simply unsupported behavior, but if you attempt to nest a list-group-horizontal inside of a custom list-group that is using list-group-flush, the list-group-horizontal renders with the inner borders, the side borders, or the top border of the first item.  It is inheriting the css from .list-group-flush .list-group-item.  Any nested list groups that are not horizontal list groups render as list-group-flush as well.

It works fine with a normal list group.

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/30110#issuecomment-585988983
