### ISSUE TITLE
Incorrect line-height of temporal input elements in Firefox

### ISSUE THREAD

**Issue by dvdbng** [twbs/bootstrap#30028]
OS: Ubuntu 18.04
Browser: Firefox 72
Bootstrap version: v3.4.1

Test case: https://jsfiddle.net/4qvc1gsy/1/ (This issue appears in Firefox, potentially in Edge browser too but I haven't tested this).

Screenshot:
 ![](https://bengoa.me/i/2020-01-16-10:58:33.png)

This is causing by Firefox using a workaround meant only for iOS here: https://github.com/twbs/bootstrap/blob/627b359/less/forms.less#L195

**Comment by XhmikosR** [comment]
Sorry, v3.x is EOL. You should update to v4.x.
