### ISSUE TITLE
Sliders (input range) disappear during using Developer tools of Google Chrome

### ISSUE THREAD

**Issue by botamochi6277** [twbs/bootstrap#30033]
Sliders(range-inputs) is invisible in an [official site](https://getbootstrap.com/docs/4.1/components/forms/#range-inputs) when I use developer tools of Google Chrome.

My environment: 
- Operating system and version: macOS Mojave 10.14.5
- Browser and version : Google Chrome v75.0.3770.142（Official Build） （64 bit）

**Comment by ffoodd** [comment]
I think it has nothing to do with Bootstrap.

Could you please try:
- [ ] the same page with all your extensions disabled?
- [ ] another range input example — without Bootstrap — with your your extensions enabled (eg: https://form.kloh.ch/#input-range)?

If the first try works, Bootstrap works as expected. If the second doesn't work, you have an extension hiding range input for any reason (probably conflicting styles).

I tried on Chromium / Ubuntu and it works fine in that case.

**Comment by jorimvanhove** [comment]
Couldn't reproduce on Browserstack using macOS Mojave 10.14.5 / Google Chrome v75.0.3770.142

**Comment by MartijnCuppens** [comment]
Couldn't reproduce this either. Thanks @ffoodd & @jorimvanhove for testing this.
