### ISSUE TITLE
Using SVGs inline

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30052]
For the carousel indicators, the navbar toggler and the upcoming stand alone accordion components it would be handy to switch from svg background images to inline SVGs. This way we'll have more control over hover states and we could save some file size in our generated CSS.

Maybe we should switch to SVG for the close button to, this will make it easier to theme the focus state (see https://github.com/twbs/bootstrap/issues/27163)

- [ ] Convert carousel indicators (#30268)
- [ ] Convert navbar toggler
- [ ] Convert accordion icons
- [ ] Convert close button

**Comment by ffoodd** [comment]
Also I think it'd be better for accessibility, since inline SVGs are not as much affected by Windows High Contrasts Mode as `background-image` (at least if they're filled with `currentColor`).

**Comment by mdo** [comment]
Other than the form controls, I'm fine with the SVGs coming out of the CSS. For the carousel for example, it'll enable more customization that we cannot do with images in CSS (e.g., inheriting colors, `currentColor`, easier transitions/styling, etc).

**Comment by alecpl** [comment]
I'm guessing this might be a BC break. In this case consider #27294 again, please.

**Comment by Glenn-Domin** [comment]
> Also I think it'd be better for accessibility, since inline SVGs are not as much affected by Windows High Contrasts Mode as background-image (at least if they're filled with currentColor).

I wonder if this could be covered by the `prefers-color-scheme: dark` media query.

**Comment by ffoodd** [comment]
BTW, using `width="1m" height="1em"` on those SVGs would allow us to size them using `font-size`— which could be very handy too.

**Comment by mdo** [comment]
This is being punted on for v4 and v5 due to difficulties and inconsistencies in getting all our components to use a single approach that's not embedded in CSS. For example, inline SVGs aren't possible in the bulk of our form controls and as such, they must be used via CSS (either embedded or referenced externally).
