### ISSUE TITLE
input-group in navbar not rendering correctly in IE 11

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [twbs/bootstrap#30061]
Operating system and version: Win 10 1909
Browser and version: IE 11

[test.txt](https://github.com/twbs/bootstrap/files/4094602/test.txt)
![BS4 1](https://user-images.githubusercontent.com/5867975/72855038-7f8ec980-3cb6-11ea-97b4-8d9ce82df008.PNG)
![BS4 4](https://user-images.githubusercontent.com/5867975/72855041-7f8ec980-3cb6-11ea-9fc6-421f8bb1b3a0.PNG)

The input fields of input groups collapse to width zero inside nav bars. Can be tested with attached html file as well as on the Bootstrap doc page (screenshot also attached). Used to work fine on Bootstrap 4.1.

**Comment by ysds** [comment]
Fixed by #30043
