### ISSUE TITLE
Implementing a Customizable Search Engine

### ISSUE THREAD

**Issue by constellationmig** [twbs/bootstrap#30063]
Do you offer services or recommendations on implementing a Customizable Search Engine that would search within the website?

**Comment by JamesVanWaza** [comment]
Try the following 
[Google Cloud Search](https://cloud.google.com/products/search/)
[Algolia](https://algolia.com)

**Comment by MartijnCuppens** [comment]
Please do not use our Github repository to ask questions unrelated to Bootstrap.
