### ISSUE TITLE
data-live-search="true" in dropdown not there ?

### ISSUE THREAD

**Issue by mathewjacobp** [twbs/bootstrap#30078]
looking for search in Dropdown  
 <select class="form-control custom-select" style="width: 100%;" id="purchaseSupplier"></select>
show me changed to search in Dropdown

 <select class="selectpicker" data-show-subtext="true" data-live-search="true">

data live search must included 
o.options = Object.assign({
            "": "-- Select Supplier --"
        }, o.options);
        for (let e = 0; e < a.data.length; ++e) o.options[a.data[e].spid] = a.data[e].Head;
        vm._utils.createSelect(o); 
[](url)

**Comment by mdo** [comment]
We don't offer a search in our dropdown via JS—there are only static HTML/CSS examples for this.
