### ISSUE TITLE
.custom-switch that adapts to font-size

### ISSUE THREAD

**Issue by 01e9** [twbs/bootstrap#30087]
I would like to have a version of [`.custom-switch`](https://getbootstrap.com/docs/4.4/components/forms/#switches) that adapts to text size.
At the moment it's "hardcoded" to `rem`.

Here is an example https://jsfiddle.net/dfmbe60u/13/
I this example I did full label width switch because I encountered some difficulties while trying to make the switch on the left side of the label, also this is what I need for my current project.

**Comment by mdo** [comment]
This is coming in v5 :).
