### ISSUE TITLE
Can you add highlighting to the drop-down menu like this

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#30089]
https://github.com/twbs/bootstrap/blob/3350931585b9fc061bf6ddc56847caa748c79010/scss/mixins/_buttons.scss#L84-L85

Add !important to button-outline-variant:hover to highlight the .dropdown-menu>.dropdown-item 
 element

Wouldn't it be so if there were no compatibility errors?
There may be a problem with the formatting of the code style.
The general meaning is this.

The final comparison is this.

![{39234D9C-C5BF-4631-AD3B-04CC2018928C}_20200126192619](https://user-images.githubusercontent.com/30773389/73134719-d0b30a80-4074-11ea-970b-e749bf01567b.jpg)

![{05173B3D-17C1-4F35-A90B-3703E6F173A6}_20200126193135](https://user-images.githubusercontent.com/30773389/73134721-d577be80-4074-11ea-952f-59fbcd2b4b3a.jpg)

![{EFBBB62C-EE39-48AF-9EA8-4EA2691D0CDA}_20200126194602](https://user-images.githubusercontent.com/30773389/73134731-f5a77d80-4074-11ea-94bf-ae41efeeb654.jpg)

**Comment by zhangchenglin** [comment]
并不是必须这样做，只不过现在的样式，是基于 .dropdown-item 的元素是a元素的情况下，如果换成其他元素的时候，就需要调整 .dropdown-item 的样式。
如下代码样式，padding元素就是多余的了。


https://github.com/zhangchenglin/tools/commit/b4a1a3901067e2332d7a669abc3ae6b4efa03aef#diff-bbc3a8374d56a5acadb4adc83f95648b

**Comment by mdo** [comment]
> Add !important to button-outline-variant:hover to highlight the .dropdown-menu>.dropdown-item element

We don't arbitrarily mix component styles, so this is intentionally done as-is. If you want buttons in the dropdown, use buttons and those classes instead of the dropdown items. That said, we cannot guarantee all the proper JS behavior for that.

**Comment by zhangchenglin** [comment]
@mdo 
我是说他们俩个的 hover  有冲突。
所以是不是需要加上 优先？

**Comment by zhangchenglin** [comment]
@mdo  
I'll try again later.
