### ISSUE TITLE
popper.js peer dependency moved to @popperjs/core on npm

### ISSUE THREAD

**Issue by cbharris** [twbs/bootstrap#30083]
Minor issue, but apparently the peer dependency popper.js has moved its home on npm. Relevant link here: https://www.npmjs.com/package/popper.js/v/1.16.1
Installing bootstrap forces one to install a deprecated version because of name conflicts. Can someone change the package.json to the new package name and latest version? 
Many thanks.

**Comment by ryanelian** [comment]
Less than minor issue for me because the new popper JS package name apparently caused my CI to fail...

A. If I don't install the popper JS package, the CI will fail due to peerDependency warning.

B. If I install the old popper JS package, peerDependency warning disappears but the package deprecation warning appears.

**Comment by FezVrasta** [comment]
There’s no reason to worry about the message, it’s there just to inform consumers of that package name change, but if one needs to use popper v1 it’s completely fine to use it.

**Comment by FezVrasta** [comment]
I just changed the message to the following:

> You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

I hope it's going to be clearer.

**Comment by cbharris** [comment]
@FezVrasta, can you say if the v1 popper is actually deprecated, or will it continue to get the v2 code backported into it? If it is actually deprecated, I renew my request that this package update to v2 so we can play with the new toys like all the other cool kids.

**Comment by FezVrasta** [comment]
I don’t plan to work on v1 anymore, but it’s not like v1 will stop work out of the blue

**Comment by XhmikosR** [comment]
#29842
