### ISSUE TITLE
Edge - select`s opened list is moving oddly "with" control when user resize window

### ISSUE THREAD

**Issue by michal-kaminski-parm** [twbs/bootstrap#30091]
We stumble on this behavior only on the Edge browser and it is easily repeatable on the forms documentation page https://getbootstrap.com/docs/4.0/components/forms/

Just try to open the select list and with list opened try to resize window and make it very small or large.

![image](https://user-images.githubusercontent.com/60339594/73158071-24f4d380-40e3-11ea-8178-33468c67c821.png)

Microsoft Windows 10 Pro, 10.0.17763 17763
Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

**Comment by ysds** [comment]
Thank you for reporting this, but sorry nothing we can do.
