### ISSUE TITLE
bootstrap.se

### ISSUE THREAD

**Issue by diypa** [twbs/bootstrap#30101]
I want to have the the entire bootstrap, the latest version translated into Swedish. Did search alot and did not found good information and instructions  for how to use bootstrap. 
The domain bootstrap.se was availabe so I did decide to have it for bootstrap. The bootstrap founding team are doing a good job and bootstrap is good for web development. OpenSource forward -> If you want to help  with the  translation, any help would be greatly appreciated.

**Comment by SilvioDoMine** [comment]
@diypa thanks for you contribution. Would be nice if you put this site though a cloudflare https ssl or Let's Encrypt SSL.

**Comment by mdo** [comment]
Let us know how it goes! All translations are community translations, so have at it :).
