### ISSUE TITLE
dropdown-dark

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [twbs/bootstrap#30105]
In the current bootstrap version, dark mode is a painful choice for the dropdown menu (and a few other components).

Dark nav bar with white can create troubles for people sensitive to UI/UX.

There are existing workarounds, but the implementation gives us the feeling that there is a bug in the design of bootstrap, dropdown menu dark mode should be as accessible as navbar dark mode.

Plenty of people are proposing complicated workarounds of something that should as basic navbar-dark bg-dark **dropdown-dark**:

- https://stackoverflow.com/questions/44612813/how-to-change-bootstrap-4-drop-down-colors/44612898

- https://community.plot.ly/t/i-cant-change-color-of-dropdown-menu/28174

**Comment by ysds** [comment]
This issue has been discussed in the past (#23915), but I think this is definitely an issue we must consider.

In the future (v6), we will go on the path of CSS Custom Properties, but for v5 we might be able to add a variable to customize the color of the dropdown on the navbar.

Perhaps something like:

```scss
$navbar-dropdown-bg: null;

.navbar .dropdown-menu {
  background-color: $navbar-dropdown-bg;
  ...
}
```

**Comment by mdo** [comment]
Proposed a basic implementation at https://github.com/twbs/bootstrap/pull/30171 to get conversation started.

**Comment by L4ZZA** [comment]
This is not a feature it's a bug. The navbar when added the class `navbar-dark ` just shows the drop-down very badly..
It doesn't follow the rest of the navbar. 
![image](https://user-images.githubusercontent.com/17835185/76528108-3104dc80-6468-11ea-8185-99bb0662fd98.png)
