### ISSUE TITLE
New include placeholder for SVG graphics - not working in the examples. 

### ISSUE THREAD

**Issue by marlae** [twbs/bootstrap#30108]
After bootstrap version 4.0.0,  pretty much all the examples don't work to due the new includes/svg;
as far as I can tell, in addition, instead of head section there are just comments as in the example below for Carousel:

---
layout: examples
title: Carousel Template
extra_css: "carousel.css"
---

I get adding in your own head section to get around this, but this new include placeholder for the vector (svg) graphics appears not to work, unless I'm missing something.  And, why was this even changed?

   {% include icons/placeholder.svg width="100%" height="100%" background="#777" color="#777" text=" " title=" " %}

Windows 10
Chrome (latest) -> Version 79.0.3945.130 (Official Build) (64-bit)   

Mark Leavitt

**Comment by ffoodd** [comment]
These are Liquid templates, meant to industrialize Jekyll static site building.
These are not HTML document, only partial templates.

You'll have to install and run the project to get the final HTML pages — however [they're also available on Github in the `gh-pages` branch](https://github.com/twbs/bootstrap/tree/gh-pages/docs/4.4/examples), which is basically the one deployed at [getbootstrap.com](https://getbootstrap.com).

Maybe zipping compiled examples and make it the target of the « Download source code » link in the Examples page could be something?

**Comment by XhmikosR** [comment]
You are not supposed to use the sources. The sources are used to build the docs.
