### ISSUE TITLE
Tootip not working in last row of bootstrap table

### ISSUE THREAD

**Issue by bastiengrignon** [twbs/bootstrap#30102]
The **tooltip** component is not working for the **last row of a table**. All the other rows are working fine but the last one is not even when i change the order of mys different rows this is still the last one which is not working.

**Comment by florianlacreuse** [comment]
Can you provide a reduced test case? Thanks!

**Comment by bastiengrignon** [comment]
Yes of course : 
In a `<tr>` tag, I've had tooltip data parameter (title, placement, toggle) and the working result in `<tr>` tag looks like this : 
`<tr title data-toggle="tooltip" data-placement="auto" data-original-title="xxxxxxxxxx">...</tr>` 

**But** when it comes to the last row of my bootstrap table the result is different : 
`<tr title="xxxxxxxxxx" data-toggle="tooltip" data-placement="auto">...</tr>` 

There is no `data-original-title` parameter (_automatically added by bootstrap_), it seems that bootstrap is not doing the same process for the last row of the table. As a result the title property of the tag is acting like a normal `title` property and shows on mouse hover but not in a bootstrap style.

**Comment by florianlacreuse** [comment]
Sorry, I meant a reduced test case with a live example, as suggested in the [bug report guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#bug-reports).

**Comment by bastiengrignon** [comment]
Oh ok sorry I didn't see this report, i'm going to check this out

**Comment by bastiengrignon** [comment]
I'm sorry for this issue I think the problem comes from my code when I copy the bootstrap table I create and his content from the dev tools to another clean directory the tooltip works fine for the last row of the table. I don't understand why but i'll try to figure it out ! 
Sorry for the inconvenience and I think this issue can be closed.
