### ISSUE TITLE
Background-color of dropdown-item on active state is always blue even if it's relevant button have different color  

### ISSUE THREAD

**Issue by flayestdev** [twbs/bootstrap#30118]
# Reproducible Example
```
<div class="dropdown-menu show" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 38px, 0px);" x-placement="bottom-start">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
</div>
```

# Screenshots

![issue](https://user-images.githubusercontent.com/29292050/73595047-49521500-4514-11ea-9c02-341935a303cb.PNG)

**Comment by irwing-reza** [comment]
If you want to have those colors you could add a custom class that overrides the default behavior.
You could also modify the default color
https://github.com/twbs/bootstrap/blob/44372484594b99304c80f9b6f42f28a59c922010/scss/_dropdown.scss#L160

Example:
https://jsfiddle.net/2tnr40pg/

**Comment by mdo** [comment]
This is intentional and unlikely to change.
