### ISSUE TITLE
open modal when another modal already open

### ISSUE THREAD

**Issue by exxizor** [twbs/bootstrap#30113]
I have tried open modal with id "exampleModal2" from anchor.
 this anchor inside other modal already open with id exampleModal1 

by adding:
      `data-toggle="modal" data-target="exampleModal2"` to anchor,

it's working fine , it's closing the current modal "exampleModal1" and open new modal "exampleModal2" ,

**problem**:
scroll work on body not on modal "exampleModal2".

**note:**
_modal-open_ class not added when open model2 , when i added to body it's working fine.

**Comment by mdo** [comment]
Sorry, but modals on top of modals aren't supported. This is mentioned in our docs.
