### ISSUE TITLE
Scroll bug in iOS with fixed-top and inputs

### ISSUE THREAD

**Issue by PierBover** [twbs/bootstrap#30115]
When a user focuses on an input inside a `fixed-top` navbar there is a weird scroll bug. For some reason iOS scrolls a small amount to the top of the page every time the input is focused. Another issue is that the user can scroll while the virtual keyboard is displayed.

You can see the weird behavior here: https://youtu.be/mEiL8UxTjVs

Here is the code to reproduce: https://github.com/PierBover/webkit-ios-input-scroll-bug/blob/master/repro-bootstrap.html

Tested on iOS 11, 12, and 13. It seems to only happen on iPhones. I can't reproduce it in my iPad Pro with iOS 12.

In Android this doesn't happen either. An element with `position: fixed;` stays fixed as expected.

This is most likely a bug with iOS but I wanted to have some precedence in case someone stumbled upon this problem (or if Bootstrap wanted to alleviate it with some hack).

I've reported the bug to the Webkit team:
https://bugs.webkit.org/show_bug.cgi?id=207049

**Comment by ysds** [comment]
> This is most likely a bug with iOS but I wanted to have some precedence in case someone stumbled upon this problem (or if Bootstrap wanted to alleviate it with some hack).

Thank you reporting this but sorry nothing we can do.
