### ISSUE TITLE
w-100 randomly adds way too much padding and a scroll bar on a responsive table

### ISSUE THREAD

**Issue by zerocarbthirty** [twbs/bootstrap#30114]
Windows 10.0.18363.592
Google Chrome | 79.0.3945.130

Bootstrap 4 appears to be adding a ton of padding to columns without any way to control it when using w-100 on a responsive table. It is also adding a horizontal scroll bar that is not required for the size of the screen. On a page with multiple tables using w-100 looks the best because then all of the tables are the same size so it would be great if you guys could fix this problem.

here is an image showing the issue

![bootstrap10-why](https://user-images.githubusercontent.com/16668354/73547682-723bb280-440d-11ea-90a9-9c35bb2abc4c.png)

**Comment by acshef** [comment]
The table cell has extra top-bottom padding added to it make it the same height as the rest of the cells in the row -- one of the other cells must have taller content (I would guess one of the cells with the icons). See https://jsfiddle.net/19twx54L/ and look at the padding that's automatically added to the second cell.

As for the width of the cells, I'll defer to someone else to explain that quirk. Suffice to say, I don't believe Bootstrap is causing it.

As for the scrollbar, I would guess that it has to do with the element you chose to add the class `.w-100` to (`table.table` vs. `div.table-responsive`) but without a **reduced test case** (as recommended by the bug report template) it's hard to know.

**Comment by zerocarbthirty** [comment]
Here you are.

[Example](https://jsfiddle.net/tu2f4svp/1/)

**Comment by florianlacreuse** [comment]
This is caused by the borders (left and right) on your custom `<tbody class="product-table-body">`. Not Bootstrap fault.

**Comment by mdo** [comment]
Not sure what you're after exactly, but `.w-100` only has a `width` property on it. It doesn't add padding or anything else.

**Comment by zerocarbthirty** [comment]
> This is caused by the borders (left and right) on your custom `<tbody class="product-table-body">`. Not Bootstrap fault.

I reported three different issues and your response didn't apply to any of them.

**Comment by zerocarbthirty** [comment]
> Not sure what you're after exactly, but `.w-100` only has a `width` property on it. It doesn't add padding or anything else.

What I was after was trying to figure out why bootstrap was adding so much horizontal spacing between the first column and the second column without being told to do so.

**Comment by zerocarbthirty** [comment]
> The table cell has extra top-bottom padding added to it make it the same height as the rest of the cells in the row -- one of the other cells must have taller content (I would guess one of the cells with the icons). See https://jsfiddle.net/19twx54L/ and look at the padding that's automatically added to the second cell.
> 
> As for the "Column being pushed too far out," I'll defer to someone else to explain that quirk. Suffice to say, I don't believe Bootstrap is causing it. I would guess the scrollbar is appearing due to your choice of which element you added the class `.w-100` to (`table.table` vs. `div.table-responsive`) but without a **reduced test case** (as recommended by the bug report template) it's hard to know.

w-100 does nothing when being added to the div.table-responsive so I don't really think that you are correct.

**Comment by zerocarbthirty** [comment]
text-center on the table is adding the padding to the columns that is making everything look wrong.
