### ISSUE TITLE
[help w/ form validation] How to remove 'valid' styling

### ISSUE THREAD

**Issue by o-alquimista** [twbs/bootstrap#30141]
I've asked on IRC, asked on a [related issue](https://github.com/twbs/bootstrap/issues/26759#issuecomment-582619763), but I couldn't get an answer, so I'm asking here.

How do you remove ":valid" styling? I'm trying this:
```
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

$form-validation-states: map-remove($form-validation-states, "valid");
```

But after rebuilding the assets and reloading the page, I can see it didn't change anything.

This is the [documentation page](https://getbootstrap.com/docs/4.4/components/forms/#customizing) I was reading.

_Bootstrap version 4.4.1_

**Comment by ysds** [comment]
Looks like no error in your SCSS and it works correctly: https://repl.it/repls/BreakableMysteriousTrees.
Maybe there is a problem with your build environment.

**Comment by o-alquimista** [comment]
You're right. It's working now.

__________________
_Information for future readers with the same problem:_

It's a Symfony project with Webpack Encore, and I create styles for each section of the site, like 'admin', 'user' and 'login'. I import Bootstrap in these files and perform variable overrides.

But one of them, `app.scss`, applies common styling to all sections of the site, and that's where I was trying to override the validation states. It doesn't work like this. I presume it's because we're already importing and overriding variables in the section-specific files, so the changes won't apply here.
