### ISSUE TITLE
Popover is not displaying the  content inside<time> tag

### ISSUE THREAD

**Issue by wenky** [twbs/bootstrap#30149]
Hi ,
We are updating bootstrap version from 4.1.3 to 4.4.1.
It seems that in bootstrap 4.4.1,it is not rendering the time tags.
Could you please provide  the workaround for it.

Please find the jsbin here.
https://jsbin.com/cujocad/edit?html,output

Could you please help on it.
It seems to be broken from 4.3 version it seems

**Comment by florianlacreuse** [comment]
Tooltips and Popovers use the BS built-in sanitizer to sanitize HTML.

`time` is not in the default white list: https://getbootstrap.com/docs/4.4/getting-started/javascript/#sanitizer. You can add it by yourself (see docs).

I hope this helps.

**Comment by bardiharborow** [comment]
As above, the following will solve the issue.

```js
$.fn.tooltip.Constructor.Default.whiteList.time = ['datetime'];
```
