### ISSUE TITLE
Missing RFS helper mixins (for paddings and margins)

### ISSUE THREAD

**Issue by dangelion** [twbs/bootstrap#30144]
Hi
I installed Bootstrap via npm

`npm install bootstrap`

But in this file `/node_modules/bootstrap/scss/vendor/_rfs.scss` there aren't any helper mixins (`@mixin padding()`, `@mixin padding-top()`, ...) while I can see them on the repo here:
https://github.com/twbs/bootstrap/blob/master/scss/vendor/_rfs.scss
from line 267

Why I have not them? To have them I need to install bootstrap directly from Github with a command like:

`npm install https://github.com/twbs/bootstrap.git --save`

Well, installing with that I have the mixins, but I don't want to install Bootstrap in that awful way.

Some help?

**Comment by ffoodd** [comment]
Hi there,

The released version on npm is v4.4.1 — and `master` is v5.
So the `_rfs.scss` you're installing through npm is this: https://github.com/twbs/bootstrap/blob/v4-dev/scss/vendor/_rfs.scss

So if you need the `master` version, you indeed have to install the master branch like you did (no v5 published on npm for now).

You basically want to use an unreleased development version, so it's kinda normal to use this "awkful way". :)
