### ISSUE TITLE
Add Scroll-to-Top FAB for docs on mobile screens

### ISSUE THREAD

**Issue by nainardev** [twbs/bootstrap#30151]
#Before opening:

[x] [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
[x] Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

It's harder to scroll all the way to top to move to another page. Or keep the navbar floating

**Comment by mdo** [comment]
Don't know if this exists for Android, but on iOS you table the status bar to go to the top. Or you swipe down briefly to see the browser UI on either major OS. In our docs, we have fixed navbars though, so this shouldn't be an issue.

Closing as a won't fix.

**Comment by nainardev** [comment]
@mdo it doesn't exist for Android
