### ISSUE TITLE
  Responsive class names and size class names, identifying overlapping names（sm/md/lg/xl）

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#30178]
Some examples are incomplete and I'd love to see someone willing to complete by type.

| Responsive variations |  |  |  |
|:------------:|:------------:|:------------:|:------------:|
|  d-sm-block  |  d-md-block  |  d-lg-block  |  d-xl-block  |
|  flex-sm-row |  flex-md-row |  flex-lg-row |  flex-xl-row |
| text-sm-left | text-md-left | text-lg-left | text-xl-left |
|    p-sm-1    |    p-md-1    |    p-lg-1    |    p-xl-1    |
| container-sm | container-md | container-lg | container-xl |
|     ...      |              |              |              |

---

| Sizes |  |  |
| :------------: | :------------: | :------: |
| input-group-sm | input-group-lg |          |
|     btn-sm     |     btn-lg     |          |
|    modal-sm    |    modal-lg    | modal-xl |
|   shadow-sm    |   shadow-lg    |          |
|  btn-group-sm  |  btn-group-lg  |          |
|      ...       |                |          |

 
Text translated by Google

 
The two tables above illustrate the use of (sm / lg / xl) in two tables for different purposes, which is confusing.
If it takes time later, such as (btn-sm-sm btn-lg-lg), how can it be easily and clearly understood?
Even if it doesn't appear, naming the class name like this is not a good way to name it.

 
There are many other words in English that indicate size. I will not give any examples. After all, it is not my mother tongue and I do n’t know more.

**Comment by MartijnCuppens** [comment]
No problem, it's clear to me what you mean. Basically the problem is our namespacing which is used for as well responsive variants as sizing components. This has been mentioned before in https://github.com/twbs/bootstrap/issues/28367#issuecomment-467797690.

One way to fix it is to adapt Tailwinds responsive variants approach. This way, we'll have classes like `sm:d-block`, `md:col-3`, `lg:p-3`. I'm in favor of switching to this (or a similar namespacing), but this is a huge change which will make upgrading harder.

**Comment by zhangchenglin** [comment]
Just need to change 2 characters.
Need to do so much?

**Comment by mdo** [comment]
> Just need to change 2 characters.
> Need to do so much?

It'd be a breaking change and a departure from how we've done things for several years, so yes, it's a bit more work than simply swapping a couple characters :).

It could be nice to differentiate, but the class names have been working well for us overall. I think in v6 when we make even broader changes we can tackle something like this.

**Comment by zhangchenglin** [comment]
Fine, I agree.
My intention is to make a simple distinction, not to use a very strange and rare class name.
I hope Bootstrap gets better and better.
