### ISSUE TITLE
Different :focus color on "a" link and "a.text-primary"

### ISSUE THREAD

**Issue by endcoreAK** [twbs/bootstrap#30173]
I've found a little "bug" imho.

If I use a basic link (primary), there is a hover color but not a focus color.

But if I use a link with the class -text-primary (identical looking) there is a darker color on focus

https://jsfiddle.net/ogj1edzq/

**Comment by mdo** [comment]
Our work in progress v5 docs in `master` are out of date, but we're removing hover and focus styles from those text utilities in v5. The explicit omission of focus styles in our default `<a>` styles is on purpose as we don't want to be unsetting that for every single stylized link. It's similar in choice to not styling `:visited` much these days.
