### ISSUE TITLE
Add support for block buttons based on specific screen widths, eg. btn-xs-block

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#30223]
This is an easy feature that anyone can implement with a little extra css, but I think it is a extremely common case that I think it would be necessary and useful for it to be built into Bootstrap.

**Comment by ysds** [comment]
I created #30376 for v5, but v4 can also achieve that. [demo](https://codepen.io/fellows3/pen/XWbZjPM)

**Comment by mdo** [comment]
This was addressed in v5 Alpha 3 with #31995
