### ISSUE TITLE
Import single bootstrap module

### ISSUE THREAD

**Issue by AleeeKoi** [twbs/bootstrap#30233]
Hello,
There something strange happening on a project.

I'm compiling with webpack some js file, 2 of these include a boostrap.js file that initialize all js requirements like jquery, some boostrap modules (like dropdown), bootstrap-select ecc.
In one page of my application there is 2 js file compiled, one generic used in the entire application and one that is relative to the page showed.
Both of them import the bootstrap file (described before).

In a page of my application there is a select that is initialized with the bootstrap-select plugin but if the bootstrap.js file is included multiple time (2 in my case) this plugin not works.
Looking at the events binded on the select component I can find 2 click event, normally only one should exists.
Bootstrap select is not working because the two click event are in conflict, one open the select and the second close it immediately making the select not usable.
Importing only one time the module ```bootstrap/js/dist/dropdown``` the select works again.

There any way to import multiple time ```bootstrap/js/dist/dropdown``` without conflicts?
Thank you

**Comment by ysds** [comment]
Bug reports must include a live demo of the problem. Please create a [reduced test case](https://css-tricks.com/reduced-test-cases/) via [Stackblitz](https://stackblitz.com/) etc.
