### ISSUE TITLE
bg-variant() mixin gone missing?

### ISSUE THREAD

**Issue by quasipickle** [twbs/bootstrap#30255]
I may be going crazy, but what happened to the `bg-variant()` mixin in 4.4.1?

It doesn't exist in https://github.com/twbs/bootstrap/blob/master/scss/mixins/_background-variant.scss, but when I look at the docs for 4.4.1, background colours are defined using `bg-variant()` mixin in the `_background-variant.scss` file (according to Firefox DevTools).

The deprecation message says it will be removed in v5 - not v4.4.1.  Where did it go?

**Comment by mdo** [comment]
`master` is our dev branch, which reflects much of what's coming in v5. Browse by the git tag or the release to see it on GitHub.
