### ISSUE TITLE
flex-box wrong description: row/column

### ISSUE THREAD

**Issue by jc-lau** [twbs/bootstrap#30261]
Hello Ladies and Gentlemen,
in the bootstrap dokumentation there is a wrong description about flex-row/column. You mixed them up! Please edit this.
Thx
Greatings

**Comment by ysds** [comment]
Where is that? Please paste its URL and the sentence.

**Comment by jc-lau** [comment]
https://getbootstrap.com/docs/4.4/utilities/flex/#direction
![bootstrap-flex-direction](https://user-images.githubusercontent.com/61270996/74926216-d5e64980-53d5-11ea-8384-f83f5a4f9f2a.jpg)

**Comment by florianlacreuse** [comment]
There are no mistakes here. See https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction.

**Comment by jc-lau** [comment]
Sorry, that was a fail in my own logic.
Now I understand:
So it just says that the divs are in one column and therefore they are vertical.
