### ISSUE TITLE
`bs-custom-file-input` doesn't work anymore since the form updates

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30265]
https://twbs-bootstrap.netlify.com/docs/5.0/forms/file/ broke since the class names aren't identical anymore.

Also, imo the plugin should be part of Bootstrap by default, since the file input's don't work without it. Also this should work out of the box without initializing it, this will be way more flexible if content is added to the DOM async.

**Comment by MartijnCuppens** [comment]
Something like this should do the job: https://codepen.io/MartijnCuppens/pen/abOBKMQ?editors=1010. No clue how to make a Bootstrap plugin from it though.

/CC @twbs/js-review

**Comment by XhmikosR** [comment]
I can't remember right now why we didn't add this in core, maybe @Johann-S remembers?

**Comment by Johann-S** [comment]
If I remember correctly, it was because it's a very little plugin so I did it separately

**Comment by MartijnCuppens** [comment]
The current file input is broken, this is definitely something we should fix before releasing an alpha version. We should include this in bootstrap by default, it doesn't make sense not to include it.

@Johann-S, could you have a look at this?

**Comment by robbaker1974** [comment]
I will look into it and get back to you

---------- Forwarded message ---------
