### ISSUE TITLE
Animated Navbar Toggler for Better UX

### ISSUE THREAD

**Issue by gatewayitconsulting** [twbs/bootstrap#30287]
Hello!

I was wondering if we could work in an animated Navbar Toggler for better UX when on a website.

I love the hamburger that comes with Bootstrap but it lacks in the UX department. When I open a menu, the only way I can tell the menu is open is with the menu being open. There is no animation with the Navbar Toggler (hamburger) when I open the menu and no animation when I close the menu.

I have have been using code that I built upon for projects for months now and finally made a pen out of it so I could share it with people having the same issues. The example is incredibly basic for demonstration purposes. It takes care of some simple issues:
- Animate the Navbar Toggler to an "x" when open and back to the default toggler when closed.
- Remove the outline around the toggler when active and focused.
- Close the menu when clicking on a link.

That code can be found [here with the example of it functioning](https://codepen.io/jmontanye/full/WNvppEg).

It could use a bit of work with the animation end position but is pretty close to perfect.

Bootstrap is a phenomenal framework and I enjoy using it the most out of other frameworks. Thank you for all the hard work you do to make it functional.

Thank you for taking the time to read my post!

Sincerely,
John M

**Comment by mdo** [comment]
Appreciate the demo and the post, but I don't think this is something that's necessary out of the box. Could be useful to do an example maybe though with some animation work applied to our components. Thanks!
