### ISSUE TITLE
Sass: Add Option like $enable-grid-classes for All Utility Classes

### ISSUE THREAD

**Issue by arminlinzbauer** [twbs/bootstrap#30280]
At the moment, it is only possible to disable generation of grid classes and makee use of @include make-grid/row/col() instead.
It would dramatically reduce the compiled size if we could also disable generation of utility classes. This could be achieved by using placeholders (%) instead of classes (.) for each or at least some utility helper if it is disabled.
One of the biggest offenders regarding output size is the sizing utility, which adds some 5000 lines to compiled CSS (about half of the total line count!)

We could then `@extend %utility;` instead. That way we could only render classes that are really needed.

**Comment by MartijnCuppens** [comment]
> One of the biggest offenders regarding output size is the sizing utility, which adds some 5000 lines to compiled CSS (about half of the total line count!)

Keep in mind the file size gzipped is way smaller.

We will have a Utility API to control all utilities in v5, with this you can add, but also remove all utilities. There's not a single variable to disable this though, but I assume it won't be that hard to implement on our side.

**Comment by mdo** [comment]
Closing as a won't fix given low priority and interest. If there's a PR for something around here, we'd happily review and reconsider though. Thanks!
