### ISSUE TITLE
Bootstrap 3.4.1 Firefox 73.0.1 problem with <details><summary> arrow

### ISSUE THREAD

**Issue by devFinar** [twbs/bootstrap#30289]
Using Bootstrap 3.4.1 and Firefox 73.0.1 we have no left arrow in `<details><summary>.`

The problem is because of 
_summary {display: block;}_ 
in Bootsrap 3.4.1.

The possible solution is to add this definition:
details > summary:first-of-type {display: list-item;}

Demo: https://jsbin.com/gacayigifa/edit?html,output

**Comment by ysds** [comment]
Sorry but v3 is EOL. Does this appear in v4.4.1?

**Comment by mdo** [comment]
Arrow is there in v4: https://twbs-bootstrap.netlify.com/docs/4.3/content/reboot/#summary.
