### ISSUE TITLE
Update image previews on the Bootstrap examples page

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30286]
Although they are a visual enhancement, they are quite hard to maintain. The colors have changed in `v5` and probably the grid gutters and carousel navigation will follow.

I would prefer to ditch them unless we can easily automate the image generation process.

https://twbs-bootstrap.netlify.com/docs/5.0/examples/#content

EDIT (XhmikosR): Also, we should resize them to the dimensions we need them to be.

**Comment by mdo** [comment]
I'm still happy to maintain this page and keep the screenshots. I think they're super useful. Not going to do it until clearer milestones for v5 though, so I could probably squeeze it in for the first alpha.

**Comment by XhmikosR** [comment]
I agree they are helpful, and updating them once a year or so it's not a big deal. Automating this seems a bit too much at this point, but Hugo could do it for us if we wanted in the future (assuming we still have only the 2x images committed and we generate the 1x ones).

**Comment by MartijnCuppens** [comment]
Ok, I've changed the title and added this to the latest `v5` board, just so we don't forget to do this before `v5` launches.

**Comment by mdo** [comment]
This was done in #33214.
