### ISSUE TITLE
Small & Large Progress

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#30318]
1rem height is by default for Progress currently. if, We will want increase or decrease progress height. So, We will need to add inline css style. So, Here, I am request you to for add `.progress-sm` (Small progress) and `.progress-lg` (Large progress).

https://stackoverflow.com/questions/23414333/thinner-bootstrap-progress-bars/60463601#60463601

**Comment by mdo** [comment]
All that's needed is to change the height as the docs mention: https://getbootstrap.com/docs/4.4/components/progress/#height. I don't think we need the variants?

**Comment by harnishdesign** [comment]
> I don't think we need the variants?

I know. But, it have possible with inline css.

**Comment by MartijnCuppens** [comment]
I agree with @mdo, the height of the default progress bar is configurable in Sass.


What we could do though is switching the height to a `em` height. This way we can size the progress bar and font size with font size utilities once they land.

**Comment by mdo** [comment]
> What we could do though is switching the height to a `em` height. This way we can size the progress bar and font size with font size utilities once they land.

In this case, I think an explicit `height` is better and more bulletproof. Say you have a super small font-size and things get nested with `em` units—ultimately the progress bar could disappear or just be unusable.

**Comment by mdo** [comment]
Closing per convo above.
