### ISSUE TITLE
Code of Dropdown Menu does not Work

### ISSUE THREAD

**Issue by Sh-Zh-7** [twbs/bootstrap#30324]
Using bootstrapv3.3.7 and jQuery 3.1.1, the code of dropdown menu which represented in [Chinese official documentation](https://v3.bootcss.com/components/#dropdowns) **doesn't show the menu after clicking.** Both in firefox and Chrome.
And the botton written in this code, which is shown in front of the example code, doesn't work well, too. **It will show the menu directly before you clicking. And you can't cancel the menu by clicking elsewhere**.
I wondered if the writing dropdown menu method has changed or it's just a unfixed bug.

**Comment by patrickhlauke** [comment]
- bootstrap 3 is not supported anymore
- the documentation's dropdown was not interactive, and already shown/forced open in the docs (for whatever reason at the time) - adapting the code (along same lines as the following dropup example) will fix this
- the chinese documentation isn't "official" in so much as it's a fan translation that somebody did

**Comment by Sh-Zh-7** [comment]
Thank u. So I will use the latest version of bootstrap and close the issue by myself.
