### ISSUE TITLE
Click on Static Modal Backdrop Scaling up the Modal Content and Adding Scrollbar to Backdrop

### ISSUE THREAD

**Issue by Behseini** [twbs/bootstrap#30322]
Using Bootstrap 4.4.1, I am facing an issue on clicking outside of static backdrop modal. As you can see in attached image when clicking outside of modal it is scaling up the size of Modal Content and eventually adding scrollbar to the backdrop. I have test this on Chrome and Firefox and same issue is happening. Can you please let me know how to stop this?
Here is the image link
![Static](https://i.stack.imgur.com/66J03.gif)

    ` <div class="container p-5">
      
      <button type="button" class="btn btn-primary" data-toggle="modal" data- 
        target="#staticBackdrop">
       Launch static backdrop modal
      </button>
      
     <div class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
     <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
     <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
      </div>
     </div>
       </div>
         </div>`

**Comment by Behseini** [comment]
I find a fix on Stackoverflow which is working

`    .modal.modal-static .modal-dialog {
     -webkit-transform: none !important;
     transform: none !important;
    }
`

**Comment by ysds** [comment]
demo: https://codepen.io/fellows3/pen/gOpRebZ
