### ISSUE TITLE
The float-left mixin is deprecated but still shown in the documentation for v4.4

### ISSUE THREAD

**Issue by marksiemers** [twbs/bootstrap#30327]
I was looking for the proper way to replace the float-left mixin to address the deprecation warning.

The documentation still references 3 deprecated mixins: https://getbootstrap.com/docs/4.4/utilities/float/#mixins

It looks like there is a WIP PR for over-hauling the mixin documentation entirely (as of the time of this writing, the call-out for deprecated mixins was not completed): https://github.com/twbs/bootstrap/pull/26500

For reference, the deprecation was added here: https://github.com/twbs/bootstrap/pull/28104

- Is there a recommended change for replacing the use of the mixin?
- Would it be helpful to have a stand-alone PR that puts the deprecation call-out in the documentation, or just wait for the PR linked above?

**Comment by mdo** [comment]
Deprecated doesn't mean removed in the current version. Deprecated means it'll be removed from the next major release, aka v5. I believe these mixins have been removed from our docs in the `master` branch when we removed their source code.

Recommended change would be recreating the mixin or replacing with regular CSS.
