### ISSUE TITLE
HTML style reboot issue for placeholder link

### ISSUE THREAD

**Issue by Nness** [twbs/bootstrap#30343]
- Operating system: Windows, MacOS, Android, iOS, Win10 Mobile
- Browser: any browser
- Test case: [CodePen](https://codepen.io/Nness/pen/qBdPzEN)

Since bootstrap 4, we had reboot for hyperlink tag. Such as:
```
// 4.1, 4.2
a:not([href]):not([tabindex]) {
}
```
Then later stage, it changed to
```
a:not([href]) {
}
```

It is getting harder and harder to style link. Before, we can get around by using `tabindex`. With latest change, it is impossible to restyle link unless use multiple classes to boost priority.

I understand people point from #19402 that placeholder link shouldn't be styled, which make sense. The problem is it shouldn't block general use of CSS. If **one single class** cannot change a simple style, then something is wrong right? That's the example I have given at [here](https://codepen.io/Nness/pen/qBdPzEN).

The whole idea on reboot isn't that allow every browser to look similar and then we can use class to style? This is not helping but ruining the experience as user point of view. Since element style can be override by css class, but element style condition cannot be override by a single css class.

The CSS rule introduced to link that doesn't have `href` should allow easy opt out. If it cannot be easily opt out, then it shouldn't be exist. 

For people who want that, they can opt in easily by adding additional `SCSS` file. For people who don't want, it is hard to opt out. For us, we have to copy the whole `reboot.scss` and remove items we don't want to be able to opt out.

As you can see, to opt out from current behaviour, it is really not play well when upgrade bootstrap. When opt in, it is so easy.

My suggestion would be any of following
- Remove `a:not([href])`
- Reintroduce `a:not([href]):not([tabindex])`, so people can get around with `tabindex`
- Split reboot to multiple file, so if we want to replace the reboot for link tag, we can modify that small scope `scss` file.

**Comment by Nness** [comment]
I believe most people that have issue with `a:not([href])` is either they cannot easily restyle placeholder link, or they want to add subtle clickable element.

If specifically style [a\[href\]](https://codepen.io/Nness/pen/PoqJrjB), then it fix problem in most cases but restyle proper link will be harder. Which is similar pain as people want to style placeholder link.

For people just want to change placeholder link, where it has nothing to do clickable element. Then the only fix is what I have suggest in initial comment.

For people who want to style a clickable element. The reason they came to link element is easy to restyle. Button is not easy to restyle.

e.g. `<button class="badge badge-success"></button>`. It looks ugly. 

Here is fix for people who seek to easily restyle button. [remove button style](https://codepen.io/Nness/pen/NWqaZLV).

@mdo should remove button style to be in reboot? That way people can easily restyle button to fit their need. Since when people choose to use a CSS library, they don't want to use default button style right?

There are many element people want to be clickable, selectable. Such as `card`, `list-item`, `table`, `image`, etc etc. If use link element, not every link element will have `href`. If use button, then we might want button to be card, list item, table cell, image etc etc. 

Where is boundary, where is too much for a reboot? Is `not([href])` too much for reboot? Those are question in my head at moment. Or if anyone have good explanation on the reasoning behind the reboot, what it try to achieve?

If `<a class="btn btn-primary" href=""></a>` is acceptable, why not `<a class="btn btn-primary"><a>`? Without `href` then shouldn't use link tag? Enforce what link tag supposed to be? Then what about only allow `btn btn-primary` to be only working on link and button tag? How come `<div class="btn btn-primary"><div>` works fine but not placeholder link tag? Placeholder link tag is worse than div to be a button?

Use [tailwindcss](https://github.com/tailwindcss/tailwindcss/blob/master/src/plugins/css/preflight.css) as example. They don't have `not([href])`, they also removed style for button. To make easier for people to opt in on style. Since when people choose to use tailwindcss they want to style their webpage to be different from default. 

Tailwindcss is not really a fair compare, since bootstrap's reboot try to sync style between browser, but what I feel `not([href])` is a bit of too much.

**Comment by Nness** [comment]
Another way is to make this easily opt out. [Example](https://codepen.io/Nness/pen/abOLepq)

Which uses `$if` inside SCSS, so people who don't want that can setup flag to not compile it.

If this been implemented, it is still not an solution for people who is not using SCSS but CDN.

**Comment by mdo** [comment]
Closing this as a won't fix—no plans to deviate from this or add a new global Sass option to configure it.

**Comment by Nness** [comment]
For people who struggling on restyle button. Here is SCSS reset for button.
```SCSS
button {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
  margin: 0;
  padding: 0;
  text-transform: none;
  background-image: none;
  background-color: transparent;
  border-style: none;

  &:focus {
    outline: 1px dotted;
    outline: 5px auto -webkit-focus-ring-color;
  }
}

button,
[role='button'] {
  cursor: pointer;
}
```
In that way, button can be easily style into badge, link or any kind of component. Most of time used in SPA. e.g. application such as PostMan. All their button that displayed as button, tab, link etc are achieved using `div`. In that case, it should be easier to use button.
