### ISSUE TITLE
Revisit constants usage as Objects

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#30357]
See https://github.com/twbs/bootstrap/pull/30285#issuecomment-595084753 and https://github.com/twbs/bootstrap/pull/30285#issuecomment-595085785

We need to test this, but it should result in smaller minified size due to mangling.

**Comment by ysds** [comment]
x-ref: #20011

**Comment by XhmikosR** [comment]
Thanks! I knew there was an issue about this but I couldn't find it :)
