### ISSUE TITLE
Create mixin for anchor tag (link)

### ISSUE THREAD

**Issue by jannakha** [twbs/bootstrap#30365]
Currently links are defined by:
https://github.com/twbs/bootstrap/blob/master/scss/_reboot.scss#L256

Can you please move it into mixins (something like make_link(color, color)).

I found I had to override links all the time, eg I can't use alert-link in alerts, so I have to override links styling in alerts etc, etc

I like how you have make_row() mixin!

I think it'll be awesome to maximise usage of mixins: btn, card can become mixins too (as I'm working with a CMS which provides its own structure and classes, I end up extending or duplicating lots of Bootstrap structures)

**Comment by mdo** [comment]
We've only really made mixins where it serves as a utility to us for building or maintaining the framework, save for the grid where we want folks to have what everyone calls "semantic mixin" usage.

Thoughts @twbs/css-review on doing more mixins? I'm inclined to say no, especially given what we've discussed for future versions of the project not having Sass...

**Comment by mdo** [comment]
Closing as stale.
