### ISSUE TITLE
Adding negative orders in flex

### ISSUE THREAD

**Issue by Khuthaily** [twbs/bootstrap#30368]
Similar to [negative margins](https://getbootstrap.com/docs/4.4/utilities/spacing/#negative-margin), I thinks it would be great to add negative [orders](https://getbootstrap.com/docs/4.4/utilities/flex/#order) in flex. Here is what I have added in a project I am working:

`@for $i from 1 through 12 {
  .order-n#{$i},
  .order-sm-n#{$i},
  .order-md-n#{$i},
  .order-lg-n#{$i},
  .order-xl-n#{$i} {
      order: -$i;
  }
}`

The result:

`.order-n1,
.order-sm-n1,
.order-md-n1,
.order-lg-n1,
.order-xl-n1 {
  order: -1;
}`

`.order-n2,
.order-sm-n2,
.order-md-n2,
.order-lg-n2,
.order-xl-n2 {
  order: -2;
}`

`.order-n3,
.order-sm-n3,
.order-md-n3,
.order-lg-n3,
.order-xl-n3 {
  order: -3;
}`

`.order-n4,
.order-sm-n4,
.order-md-n4,
.order-lg-n4,
.order-xl-n4 {
  order: -4;
}`

`.order-n5,
.order-sm-n5,
.order-md-n5,
.order-lg-n5,
.order-xl-n5 {
  order: -5;
}`

`.order-n6,
.order-sm-n6,
.order-md-n6,
.order-lg-n6,
.order-xl-n6 {
  order: -6;
}`

`.order-n7,
.order-sm-n7,
.order-md-n7,
.order-lg-n7,
.order-xl-n7 {
  order: -7;
}`

`.order-n8,
.order-sm-n8,
.order-md-n8,
.order-lg-n8,
.order-xl-n8 {
  order: -8;
}`

`.order-n9,
.order-sm-n9,
.order-md-n9,
.order-lg-n9,
.order-xl-n9 {
  order: -9;
}`

`.order-n10,
.order-sm-n10,
.order-md-n10,
.order-lg-n10,
.order-xl-n10 {
  order: -10;
}`

`.order-n11,
.order-sm-n11,
.order-md-n11,
.order-lg-n11,
.order-xl-n11 {
  order: -11;
}`

`.order-n12,
.order-sm-n12,
.order-md-n12,
.order-lg-n12,
.order-xl-n12 {
  order: -12;
}`

This works great for me, and I think it will be great if Bootstrap includes negative flex orders by default.

**Comment by mdo** [comment]
I feel like the existing classes accomplish the ordering with fewer classes. To me this doesn't really add anything new, but rather another way to do the same thing. What's the use case?

**Comment by Khuthaily** [comment]
> ... What's the use case?

@mdo I found it useful in a couple of projects that needed Arabic (right-to-left) and English text on the same page. It helped me move things before an element of `order-0` easily without writing exceptions. I understand [other libraries](https://github.com/angular/material/issues/4482) included negative orders, and I thought it would be great to see it in Bootstrap. Here is an example (not mine) for another use case for negative orders: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items#Use_cases_for_order

**Comment by MartijnCuppens** [comment]
We already have:

- responsive `row-reverse` and `column-reverse` to completely reverse the orders
- 15 responsive order classes to reorder elements in v4
- 8 responsive order classes to reorder elements in v5 and a utility API to add as many classes as you which.

This should definitely cover any almost case.
