### ISSUE TITLE
Incorrect files in Bootstrap download

### ISSUE THREAD

**Issue by LeftParallel360** [twbs/bootstrap#30367]
According to the Udemy_The Complete 2020 web development course; 
There was supposed to be a file called "Bootstrap.css" in the folder DIST of the download of bootstrap. 
There was not. 

![BootstrapCSS_Claim](https://user-images.githubusercontent.com/40411330/76270188-8b682800-6231-11ea-8681-a88c882559b0.jpg)

**Comment by skmedix** [comment]
But `boostrap.css` actually **IS** included in the Bootstrap download.

BS4.4:
https://getbootstrap.com/docs/4.4/getting-started/download/#compiled-css-and-js

If you really need 4.1:
https://getbootstrap.com/docs/4.1/getting-started/download/#compiled-css-and-js

**Comment by LeftParallel360** [comment]
not in the 4.0 download






SincerelyAlfred Medrano 

    On Monday, March 9, 2020, 06:35:28 PM PDT, SKmedix <notifications@github.com> wrote:  
 
 
But boostrap.css actually IS included in the Bootstrap download.

BS4.4:
https://getbootstrap.com/docs/4.4/getting-started/download/#compiled-css-and-js

If you really need 4.1:
https://getbootstrap.com/docs/4.1/getting-started/download/#compiled-css-and-js

**Comment by ysds** [comment]
The behavior of the download button have been changed from 4.1.2.

You can download the dist file of the 4.0.0 at https://getbootstrap.com/docs/4.0/getting-started/download/#compiled-css-and-js
