### ISSUE TITLE
Responsive Variations for `sticky-top`

### ISSUE THREAD

**Issue by Rabadash8820** [twbs/bootstrap#30385]
I am trying to replicate the behavior of the navbar from the Bootstrap docs site, and having some difficulty. Specifically, I am trying to make the navbar `sticky-top` on wider breakpoints, but part of the content flow on smaller breakpoints, so that it doesn't take up vertical space on mobile as the user scrolls. on Bootstrap Docs, this behavior seems to be handled by a custom `bd-navbar` class, which uses Bootstrap's responsive breakpoints to toggle `position: sticky`. I request this functionality be built into Bootstrap with classes like the following:

1. `sticky-top-xs`
1. `sticky-top-sm`
1. `sticky-top-md`
1. `sticky-top-lg`
1. `sticky-top-xl`

I've some discussion in this repo about having `sticky-x` classes for other areas of the screen; presumably those could have responsive variations also, but I'm just asking for the `top` variants. 🙂

**Comment by ysds** [comment]
Will be available in v5 #29158

**Comment by Rabadash8820** [comment]
Wow, guess I missed that while searching for existing Issues but not PRs. Sorry for the duplicate!
