### ISSUE TITLE
Please REFUND themes.getbootstrap.com (customer)

### ISSUE THREAD

**Issue by michaeljakob** [twbs/bootstrap#30393]
Dear sir or madam,
I have been unable to reach you by email or any other way, so this is my last resort as an unsatisfied customer to reach out to you.

I've erratically bought a theme from https://themes.getbootstrap.com/product/landkit/ and would love to get a full refund. I had erratically (my fault) believed this was a Wordpress theme. I can't and will not use Landkit, thus I request a full refund. Please show me you're a customer first company!
My Order ID ends with # XX937

Sincerely,
Michael

**Comment by rjhancock** [comment]
https://themes.zendesk.com/hc/en-us/articles/360000011072-How-can-I-get-a-refund- is where you need to go.

This is the place for submitting issues with the base Bootstrap theme.

**Comment by mdo** [comment]
Sorry for any inconvenience if you've been unable to reach the Themes team. I've passed this along to them regardless so they can process it accordingly.

**Comment by dhg** [comment]
@michaeljakob Hey Michael – we're sorry for the drop in communication. Our usual support member that handles incoming emails has been under the weather and taking it very seriously given the current situation. I just issued you a refund so you should see that come through shortly. Figured this was the easiest channel to reach you. 

We'll keep working hard to make sure we take care of all incoming support requests in a timely manner to the best of our ability and will be trying to find solutions to be more efficient. 

If you need anything else, do let us know – here to help. 

Dave

**Comment by nebohbernard** [comment]
Hi please I would like to upgrade my theme license from standard to a multisite license

**Comment by dhg** [comment]
Hi @nebohbernard! Sure thing, we'd be happy to do this. Just email themes@getbootstrap.com to get this taken care of in ~24 hours, but if you're having any issues with this, please feel free to reply and I'll investigate.

**Comment by nebohbernard** [comment]
Dear Dave

We have already mailed sent a mail and we are yet to get a response them.

**Comment by dhg** [comment]
Hey @nebohbernard – I'm almost positive you've been taken care of here, but if not, please send me your Order number and I will personally make sure you're taking care of.

**Comment by nebohbernard** [comment]
Hi

No I have not, I and my team have had to pay for the multi site and are yet
to get a response on the the refund for the standard.

**Comment by dhg** [comment]
Gotcha. Lemme take care of you, but need to know your original and upgrade order numbers.

**Comment by mtomczak123** [comment]
I have the same problem. They are not giving back money. They ignore messages. No contact

**Comment by mtomczak123** [comment]
> Dear sir or madam, I have been unable to reach you by email or any other way, so this is my last resort as an unsatisfied customer to reach out to you.
> 
> I've erratically bought a theme from https://themes.getbootstrap.com/product/landkit/ and would love to get a full refund. I had erratically (my fault) believed this was a Wordpress theme. I can't and will not use Landkit, thus I request a full refund. Please show me you're a customer first company! My Order ID ends with # XX937
> 
> Sincerely, Michael

I have the same problem. They are not giving back money. They ignore messages. No contact. Standard procedure is shown. The return policy is not working

**Comment by yichunkuo** [comment]
hey, I have the same problem. They are not giving back money. They ignore messages. No contact.
@dhg  could you help me please~~~

**Comment by mtomczak123** [comment]
> @michaeljakob Hey Michael – we're sorry for the drop in communication. Our usual support member that handles incoming emails has been under the weather and taking it very seriously given the current situation. I just issued you a refund so you should see that come through shortly. Figured this was the easiest channel to reach you.
> 
> We'll keep working hard to make sure we take care of all incoming support requests in a timely manner to the best of our ability and will be trying to find solutions to be more efficient.
> 
> If you need anything else, do let us know – here to help.
> 
> Dave

Why don't you do refund for me?

**Comment by schwartzmj** [comment]
I've also been trying to get a refund for weeks on Order #118483 with no response. I've sent multiple emails to themes@getbootstrap.com.

**Comment by yichunkuo** [comment]
me too, I am  Order #118509 , I've sent multiple emails  
hi @dhg do you know why  not making a refund to us?

**Comment by skgith1** [comment]
@dhg I am also having major issues reaching support regarding my purchase, please reach out if possible. Thank you.

**Comment by MartensWebshops** [comment]
@dhg I'm having the same issue. No response what so ever. I have send multiple emails.

**Comment by spmatthews03** [comment]
Same. Please issue me a refund. Tried 4 times, no responses after 3 weeks.

**Comment by JimmyMalark** [comment]
Same here, I have sent a bunch of emails but haven't received any answers yet.
If I don't here from you in the next 24 hours I will be forced to take legal action.
Either refund my order or give me the download link

**Comment by xffdd** [comment]
Did anyone manage to get a refund?

**Comment by karlospg** [comment]
Same here, total SCAM, no refund, no response.
