### ISSUE TITLE
Different values in cols between getbootstrap CSS and NPM

### ISSUE THREAD

**Issue by everlast000** [twbs/bootstrap#30406]
Hi,

After some examination I figured the compiled CSS from NPM ("bootstrap": "^4.4.1") differs from this one: https://getbootstrap.com/docs/4.4/dist/css/bootstrap.css. See attachment. The right column is the good one.

![image](https://user-images.githubusercontent.com/4980700/76845741-a2b1a180-683f-11ea-9776-07c4ca9e023c.png)

This results in weird subpixels like the image below:

![image](https://user-images.githubusercontent.com/4980700/76845825-c674e780-683f-11ea-9762-eefabf03d231.png)

Seems like something I don't wanna be fixing myself.

**Comment by ysds** [comment]
Please increase the Sass rounding precision option to 6. https://getbootstrap.com/docs/4.4/getting-started/theming/#sass

**Comment by XhmikosR** [comment]
Yeah, you need to set precision to 6.
