### ISSUE TITLE
Are bootstrap themes compatible with silverstripe

### ISSUE THREAD

**Issue by john1309** [twbs/bootstrap#30409]
Hi, 
I would like to know if the boostrap themes are compatible with silverstripe. I saw nice themes on the store. Thanks

**Comment by mdo** [comment]
I've never used Silverstripe, but if it takes custom HTML, CSS, and JS, I'm sure themes could be modified by you or your team to work with any CMS or backend. There's no inherent support for this kind of thing though from us or the Themes team, so you're on your own for any modifications there.
