### ISSUE TITLE
What happened to adding more colors?

### ISSUE THREAD

**Issue by NeuronButter** [twbs/bootstrap#30422]
On [this page](https://getbootstrap.com/docs/4.0/getting-started/theming/#all-colors), it says "This will be expanded upon in subsequent minor releases to add additional shades, much like the grayscale palette we already include." What happened to that, and are people still working on it? It seems like a really good idea, but it hasn't been implemented yet I don't believe (or I couldn't find documentation or code in the .SCSS files)

**Comment by nteetor** [comment]
Shades and tints are coming in v5, https://github.com/twbs/bootstrap/pull/29348.

**Comment by NeuronButter** [comment]
Wow, did not see that. Thanks!
