### ISSUE TITLE
CSS minification can interfere with table border inheritance

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#30429]
In v5, as discussed in thread https://github.com/twbs/bootstrap/pull/30342#pullrequestreview-370800094, table cell border inheritance only works when the `border-*` properties are listed in long-hand notation.  When `border-*-width`, `border-*-color` and `border-*-width` are specified, some CSS minifiers will merge these into shorthand properties.

While the following `clean-css` directives will prevent `clean-css` from merging these rules: 

```scss
    /* clean-css ignore:start */
    border-color: inherit;
    border-bottom-style: solid;
    border-bottom-width: $table-border-width;
    /* clean-css ignore:end */
```

It assumes that all users are using either `clean-css` or the Bootstrap provided compiled CSS, which is not always the case (some users may use `css-nano` or other CSS minifiers).  So other minifier users may run into style issues with tables.

Perhaps a note in the documentation (or even in the SCSS source) about the potential issues with CSS minification should be added.

/cc @mdo

**Comment by MartijnCuppens** [comment]
> some CSS minifiers will merge these into shorthand properties

It would be very odd if minifiers do this. Also, you can't combine the properties you mentioned into a shorthand.

Could you give an example of this?

**Comment by tmorehouse** [comment]
It happened with mdo's PR for tables.  Se our conversation at: https://github.com/twbs/bootstrap/pull/30342/files?file-filters%5B%5D=.scss#r389413697

> mdo: We use clean-css, which did in fact recombine these. I've disabled that rule for now.

**Comment by MartijnCuppens** [comment]
I checked the generated CSS and this doesn't seem to be an issue. 

> ... and many minimizers (clean-css, cssnano) will combine longhand rules into shorthand

They only do this if it's impossible to cause issues.

I think we can close this issue, unless there is something I'm missing?

**Comment by tmorehouse** [comment]
@mdo asked me to open the issue, mainly to mention in the docs that some minifiers (if using anything other than clean-css) and the Bootstrap v5 source SCSS can cause issues (specifically with tables).

Table border inheritance only works when the properties are long-hand.  And as mdo found, it mangled the table styles and broke border inheritance.

**Comment by XhmikosR** [comment]
> They only do this if it's impossible to cause issues.

You trust minifiers more than you should 😛

Please keep it open. I also checked the CSS from #30342, but that includes the clean-css fix, so I'd like to verify again myself.

**Comment by XhmikosR** [comment]
Although, IMO we should try to find a workaround and definitely mention it in the source files when needed.

**Comment by MartijnCuppens** [comment]
We already use `border-color: inherit` in our source code, this wasn't an issue before afaict:
https://github.com/twbs/bootstrap/blob/1cc1a476468d8106ef2954f959dc7b747159a353/scss/forms/_form-file.scss#L53-L55
https://github.com/twbs/bootstrap/blob/1cc1a476468d8106ef2954f959dc7b747159a353/scss/forms/_form-file.scss#L67-L69

**Comment by XhmikosR** [comment]
I'll verify tomorrow myself.

**Comment by tmorehouse** [comment]
https://github.com/twbs/bootstrap/pull/30342/files?file-filters%5B%5D=.scss#r389413697

> We use clean-css, **which did in fact recombine these**.

**Comment by mdo** [comment]
Revisiting this (sorry!), I'm inclined to close this out given the code comment and lack of problems since this was opened. Thanks for having documented it so many months ago!

**Comment by rejhgadellaabsl** [comment]
> > ... and many minimizers (clean-css, cssnano) will combine longhand rules into shorthand

> They only do this if it's impossible to cause issues.

Turns out cssnano makes mistakes, too :)

I just ran into a case where I suddenly had a border rule in the `:root { }` css class (it's supposed to only contain css variables).

Turned out, cssnano is actually merging this:

```scss
/* _root.scss */
  --#{$prefix}border-width: #{$border-width};
  --#{$prefix}border-style: #{$border-style};
  --#{$prefix}border-color: #{$border-color};
```

not into:

```css
  --bs-border-width: 1px;
  --bs-border-style: solid;
  --bs-border-color: rgba(0, 0, 0, 0.175);
```

but into this:

```css
  border: 1px solid rgba(0, 0, 0, 0.175);
```

Setting cssnano option `mergeLonghand: false` fixed the issue.
