### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [twbs/bootstrap#30428]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Bootstrap on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by Johann-S** [comment]
Maybe @LeandroStanger can you tell us why should we consider to use Flatpak ?

**Comment by mdo** [comment]
We don't build Linux apps, this doesn't seem useful to us at all. Thanks, but we won't be adding more package managers.
