### ISSUE TITLE
bootstrap 4 grid

### ISSUE THREAD

**Issue by kyslyi** [twbs/bootstrap#30421]
Hello. I understand bootstrap 4 is 1140 wide. So the content part will be 1110, right? Where can I get the 1140 psd grid?

**Comment by patrickhlauke** [comment]
We don't provide PSD grids or similar, sorry. Worth checking on Slack or similar places if somebody's made one https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
