### ISSUE TITLE
Instagram builtin browser problem

### ISSUE THREAD

**Issue by tansut** [twbs/bootstrap#30431]
![A3988DE2-DEB7-45AE-BFFE-4E04C971035C](https://user-images.githubusercontent.com/3591623/77225809-d6643280-6b83-11ea-9ded-4cab0e61fdfd.PNG)

I'am using Instagram for IOS. When a bootstrap page with modal has been opened by the user, modal window does not position itself correctly inside instagram builtin browser. I set my Instagram account's address as https://getbootstrap.com/docs/4.4/components/modal/, see screenshot.

To reproduce:

1. Open your instagram account
2. Click Edit Profile
3. Set your web site as above
4. Close and view your profile
5. Click your web site

This is a huge problem for us because we use instagram ads and unfortunately users cannot use our web site when they click an ad.

Regards,

**Comment by acshef** [comment]
Have you tried vertically centering the modal via https://getbootstrap.com/docs/4.4/components/modal/#vertically-centered ?

**Comment by ysds** [comment]
confirmed. But I'm mot sure what we can do.

**Comment by MartijnCuppens** [comment]
This is not an issue on android, not sure how to debug this 🤷‍♂️

**Comment by tansut** [comment]
This is a bug of Instagram for IOS, fixed display with top 0 css class does not work as expected. I also had problems at other libraries like lightgallery.

A workarround:

  .lg-toolbar {
    margin-top: 40px !important;
  }

  .modal-dialog {
    margin-top: 3rem !important;
  }

  .toast-top-left, .toast-top-center, .toast-top-right {
    top: 3rem !important;
  }

**Comment by mdo** [comment]
Do we close as a won't fix?

**Comment by tansut** [comment]
sure
