### ISSUE TITLE
Who's running BOINC?

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#30436]
Hi, I'd like to plug BOINC, a hackathon anyone can join. No programming experience necessary. We are 1.3 million users strong, volunteering our CPU time to synthesize a COVID-19 vaccine.

BOINC supports macOS, Windows, Linux, Android, and Docker. If you would like to contribute, check out the documentation:

https://boinc.bakerlab.org/

**Comment by mdo** [comment]
This has nothing to do with us, sorry.
