### ISSUE TITLE
Using CSS global variables

### ISSUE THREAD

**Issue by alexandreDavid** [twbs/bootstrap#30453]
It could be amazing if all the CSS colors are defined from the :root of the app.
The new version of Facebook does that. The aim is to switch between dark / light mode. The only erased css code is the variables css defined for all the stylesheet

Finally it's the same ticket: https://github.com/twbs/bootstrap/issues/26596

**Comment by dylan-westbury** [comment]
We just converted a project from scss to css to allow for dark mode also. With scss it's not possible without bloating the code, whereas css variables are dynamic.

**Comment by MartijnCuppens** [comment]
Closing this, reopened #26596
