### ISSUE TITLE
V5 package.json: get ready for ES6 exports/imports

### ISSUE THREAD

**Issue by dilyanpalauzov** [twbs/bootstrap#30473]
Per https://github.com/twbs/bootstrap/pull/28386 and others, bootstrap5 is going to be delivered as ES6  module (apart from pre-ES6 formats).  On the master branch package.json contains `"main": "dist/js/bootstrap.js", "module": "dist/js/bootstrap.esm.js"`.  This is not going to work is Node modules.  I use node 13.12.0 and I get
```
/git/bootstrap master=$ node dist/js/bootstrap.esm.js
(node:30255) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/git/bootstrap/dist/js/bootstrap.esm.js:6
import Popper from 'popper.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

• To be able to execute the above `node`-line, dist/js/ must containg package.json with "type":"module"
• To make `import Alert from 'bootstrap';`  work under NodeJS, the (root) package must contain [conditional exports](https://nodejs.org/api/esm.html#esm_conditional_exports), something like `"exports": {"import" : "dist/js/bootstrap.esm.js", "require":…}`. In particular, NodeJS ignores `"module"`.

**Comment by XhmikosR** [comment]
Thanks for making the issue, patches welcome 🙂

**Comment by Johann-S** [comment]
Bootstrap cannot work on a Node.js environment, it works only in a Browser, so your example is not relevant here

**Comment by dilyanpalauzov** [comment]
I do not pretend to understand everything.  But my idea is to create a javascript file importing something (or everything) from bootstrap es6, then do tree shaking and end with a single file, created by Node.

**Comment by Johann-S** [comment]
to do what you're trying to achieve you've to use a bundler, something like Rollup or Webpack, it'll do exactly what you want 👍
