### ISSUE TITLE
Bring back `.form-text`

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30477]
In the notorious form updates PR (https://github.com/twbs/bootstrap/pull/28450), `.form-text` was dropped. I don't think that was the right thing to do, having a class which we can use to keep form descriptions consistent would help. We could also add some `null` variables (font size, font weight, font style, color) to make this element more more configurable.

Thoughts @twbs/css-review?

**Comment by zalog** [comment]
Yep, and eventually be consistent with `.*-feedback` classes too.

**Comment by MartijnCuppens** [comment]
I've asked @mdo about this on Slack and he's ok bringing `.form-text` back. Since we also did https://github.com/twbs/bootstrap/pull/30476, I think it makes sense to continue with this.

@zalog do you mind having a look at this, since you already did some research in https://github.com/twbs/bootstrap/pull/30397?

**Comment by zalog** [comment]
Yep, sure. I'm glad that I can help :)
I'll get back on it soon.
