### ISSUE TITLE
Media queries according to div element

### ISSUE THREAD

**Issue by Ravindersingh1526** [twbs/bootstrap#30478]
Feature
I have an one row in which three columns. When i change the with width of row manually to 360px then    each column width moved to 100% means (co-120) if i set width of row 1024px then i want  three column in an row means width 33.333% each. media queries work on screen size
Current behaviour
The row will show two, three columns based on screen size

**Comment by mdo** [comment]
There's currently no way to do this in CSS without a polyfill as far as I know.
