### ISSUE TITLE
Review `*-bg-level` and `*-border-level` variables

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30487]
It seems there are some inconsistencies in the color levels of the tables/list-group-items/alerts (https://github.com/twbs/bootstrap/pull/30009#issue-362140343). We better equalize these variables and check their color contrast.

**Comment by ffoodd** [comment]
Indeed — I'm not familiar yet with `color-level()` but some issues I raised in #30468 are related to these (`.alert-light` and `.table-dark` for example).

**Comment by mdo** [comment]
Did we normalize anything here with the move to %s for our shade/tint functions @MartijnCuppens?

**Comment by MartijnCuppens** [comment]
Yes we did 🙌

**Comment by MartijnCuppens** [comment]
Ow, but the color contrasts are still an issue, I remembered 😥

**Comment by mdo** [comment]
Believe this was closed by #32085.
