### ISSUE TITLE
Review skip links theming

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30491]
In https://github.com/twbs/bootstrap/pull/30414 we discovered the skip links do not look that well if backported to `v4`:
![image](https://user-images.githubusercontent.com/11559216/78049364-455b3b80-737b-11ea-86ca-e4e7d9a0c93f.png)

We could also improve the theming in v5, in some viewports, it also covers a critical part of the navbar
![image](https://user-images.githubusercontent.com/11559216/78049277-26f54000-737b-11ea-88e7-e76464f2ce59.png)

CC @patrickhlauke @ffoodd

**Comment by MartijnCuppens** [comment]
Maybe we can just add one of the `.btn` classes here?

**Comment by ffoodd** [comment]
We may try. FWIW what's important with my PR IS making them top left: we may get the previous styling back, but simply left align links. 

And maybe display both of them at thé same time in docs template, BTW.

**Comment by ffoodd** [comment]
Could also be a navbar, otherwise.

**Comment by ffoodd** [comment]
Let me try something :)

**Comment by vishalsharma2063** [comment]
we can construct a new navbar
