### ISSUE TITLE
docs space

### ISSUE THREAD

**Issue by jorjik** [twbs/bootstrap#30499]
https://i.imgur.com/uc4vsJX.png
url https://getbootstrap.com/docs/4.0/utilities/colors/

**Comment by ffoodd** [comment]
Hi there,

Please read carefully the paragraph above: those examples, which I repeat here just in case:

> When `$enable-gradients` is set to true, you’ll be able to use `.bg-gradient-` utility classes. **By default, `$enable-gradients` is disabled and the example below is intentionally broken.** This is done for easier customization from the moment you start using Bootstrap. Learn about our Sass options to enable these classes and more.

Thanks :)
