### ISSUE TITLE
Redirects to http://127.0.0.1:8000/js/popper.js.map after logging in

### ISSUE THREAD

**Issue by roniloapin** [twbs/bootstrap#30506]
Hello everyone! I tried modifying the 'Register' Page of Laravel. I test it and added new user data to Register Page and it saved successfully to my database then redirected me to the Home Page (or dashboard) with images being displayed. I clicked the logout button to test if I can logout and it also works. <br><br>However, when I tried to login back the account, it redirected me to 'http://127.0.0.1:8000/js/popper.js.map' instead of the homepage and the images failed to load. Thank you in advance!
![picture](https://user-images.githubusercontent.com/26215333/78334307-1da7e580-75be-11ea-8ec0-509370403da8.png)

**Comment by patrickhlauke** [comment]
sorry, we can't help you with "how to" type questions or debug your specific use of bootstrap in combination with other code.

**Comment by khechinimed** [comment]
@roniloapin did you found a solution ?
