### ISSUE TITLE
Docs improvement: Sass references (variables & mixins)

### ISSUE THREAD

**Issue by Deckluhm** [twbs/bootstrap#30519]
Hi,

I'd love to see a **Sass reference** section on each component.

Basically, a section which lists every Sass variables & mixins related to a component.
Something like the JS reference (https://getbootstrap.com/docs/4.4/components/modal/#via-javascript) you can see on every component but for Sass.

**Why?**

One of the strength of a framework like Bootstrap is that it is built on Sass.

Sass variables and mixins are powerful ways to customize components but it's currently pretty hard to discover and search Sass variables and mixins.

We currently have:
- https://getbootstrap.com/docs/4.4/getting-started/theming but it's a pretty general guide and lack reference to all variables/mixins
- `scss/_variables.scss` but it is 1200+ lines long and I think I shouldn't be necessary to read sources to use/customize Bootstrap
- `scss/mixins` same thing + it isn't that easy to read/find, especially if you are a Sass beginner

**Example**

Here is an example with Foundation "Reveal" (modal) component: https://get.foundation/sites/docs/reveal.html

I'm obviously open about the format/content of this new section, this link is just an example.

-----

**Update**

Here are basic, unfinished examples of what it might look like for Bootstrap docs:

**Alerts**
https://trusting-bardeen-d7b45d.netlify.com/docs/4.3/components/alerts/#sass-reference

**Toasts** (no mixins)
https://trusting-bardeen-d7b45d.netlify.com/docs/4.3/components/toasts/#sass-reference

**Buttons**
https://trusting-bardeen-d7b45d.netlify.com/docs/4.3/components/buttons/#sass-reference

**Comment by MartijnCuppens** [comment]
Yesterday we've merged https://github.com/twbs/bootstrap/pull/30502, which will make it easier to refer to scss snippets. The documentation is not going to write itself, so any help is welcome here.

**Comment by Deckluhm** [comment]
> The documentation is not going to write itself, so any help is welcome here.

I first wanted to know what people think of the idea I suggested but I will do the PR if the idea is validated.

**Comment by Deckluhm** [comment]
I just created basic, unfinished examples of what it might look like for Bootstrap docs:

**Alerts**
https://trusting-bardeen-d7b45d.netlify.com/docs/4.3/components/alerts/#sass-reference

**Toasts** (no mixins)
https://trusting-bardeen-d7b45d.netlify.com/docs/4.3/components/toasts/#sass-reference

**Buttons**
https://trusting-bardeen-d7b45d.netlify.com/docs/4.3/components/buttons/#sass-reference

**Comment by mdo** [comment]
Wondering how much we need to create a full table of variables, values, and descriptions vs just referencing the source variables with our Sass references @MartijnCuppens mentioned. Length, string, color, list, etc—this seems less important to me, but I'm not the one modifying these all that often.

Thoughts?

**Comment by MartijnCuppens** [comment]
Yeah indeed, also some variable can be of multiple types (colors or string like inherit). This will also be hard to maintain on the long term.

@Deckluhm, thanks for the suggestions, feel free to improve our docs where needed with our `scss-docs` comments explained in #30502 ❤️
