### ISSUE TITLE
".js" extension is missed in main attribute in package.json

### ISSUE THREAD

**Issue by davidmtobias** [twbs/bootstrap#30514]
https://github.com/twbs/bootstrap/blob/dca1ab7d877bc4b664b43604657a2b5fbe2b4ecb/package.json#L91

This issue makes that "require bootstrap" configuration fails. For example, using Sprockets with Rails 6, It's neccesary to add the whole path of bootstrap "require bootstrap/dist/js/bootstrap.min" in application.js instead of simply "require bootstrap"

**Comment by XhmikosR** [comment]
@Johann-S it seems in master we do specify the extension.

**Comment by XhmikosR** [comment]
Ping @Johann-S

**Comment by Johann-S** [comment]
yep we can do that in v4 too

**Comment by XhmikosR** [comment]
@Johann-S can you make a patch about this please?

**Comment by Johann-S** [comment]
Pushed here: https://github.com/twbs/bootstrap/pull/30682/commits/4cd01b8363641bad2217224110bd0d0f53c720a4
