### ISSUE TITLE
Grid / Sizing / Small Device bug ?

### ISSUE THREAD

**Issue by techmiester** [twbs/bootstrap#30513]
I think I have found a bug with grid on small devices only.  Seems to work fine on tablets and larger.

For example I have a sticky footer, works good until I use the grid (ex row/column anywhere on page).  Then it does not behave like a sticky anymore on my android cell.  

The other issue is the grid is not handling the screen width properly.  It seems to think the width is larger than it is, so it throws off the center and I get text cut off.  

It also is easier to replicate on the device itself vs chrome developer.  

Example:
https://www.phoenix-shows.ca/pss-alpha/sitemap2020.php

**Comment by MartijnCuppens** [comment]
You've applied a fixed width, which is causing this:
```
.link {
  width: 500px;
  white-space: nowrap;
  display: block;
}
```
