### ISSUE TITLE
v5: Revisit `escape-svg`

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#30527]
It's quite possible we don't need to escape all the characters anymore. Opening this as a reminder to evaluate the function.

**Comment by mdo** [comment]
I think I needed to do this for Chrome still in another project, at least the `#` for hex values.

**Comment by XhmikosR** [comment]
`#` needs to be escaped for sure. The other characters might be redundant. But either way, let's try first and see how much we save.

**Comment by mdo** [comment]
Thinking for safety's sake, we can leave the function as-is. Thoughts?
