### ISSUE TITLE
Removal of Code Of Conduct

### ISSUE THREAD

**Issue by mryellow** [twbs/bootstrap#30520]
This Code of Conduct excludes rather than includes.

https://github.com/twbs/bootstrap/blob/83b49aa688e30f0d2af22110b94c7d8b3deffcf0/CODE_OF_CONDUCT.md

Competition in comparison:

https://github.com/foundation/foundation-sites/blob/30f3247db9ca61ab1d525cf36b373760db96a85b/CONTRIBUTING.md

Bootstrap includes politically motivated tone-policing anti-debate tactics against meritocratic contributors. Where Foundation does not.

This makes framework choice easy in that I can choose the one which doesn't have such a policy.

**Comment by patrickhlauke** [comment]
you're comparing bootstrap's code of conduct with foundation's contributing document...which then points out that all contributions are expected to follow foundation's code of conduct https://github.com/foundation/foundation-sites/blob/30f3247db9ca61ab1d525cf36b373760db96a85b/code-of-conduct.md ... which seems to me pretty much the same (unless there's a specific wording that makes you say it's any different?)

**Comment by mryellow** [comment]
Yeah does look like the same parasites (`contributor-covenant.org`) got to them too.

Bummer. 

This is a much better template:

```
# Code of Conduct

## Free Speech and Consideration

Everyone has the right to communicate opinions and ideas without fear of censorship. Consideration shall be given to all constructive speech that is based in fact and reason.
```

**Comment by patrickhlauke** [comment]
you do you.

**Comment by mdo** [comment]
Rarely do we have to enforce these guidelines and take action—general guideline as always is to not be a jerk and you’ll be just fine :).
