### ISSUE TITLE
Bootstrap v5 removes animations even when prefers-reduced-motion is unset.

### ISSUE THREAD

**Issue by Justsnoopy30** [twbs/bootstrap#30526]
Bootstrap v5 removes animations even when prefers-reduced-motion is unset. Tested on Windows 10 and Android 10 phone running the latest version of chrome.
See https://deploy-preview-29925--twbs-bootstrap.netlify.com/docs/5.0/forms/checks/

**Comment by patrickhlauke** [comment]
which animations? i don't think any of those controls ever had animations?

**Comment by Justsnoopy30** [comment]
They did, in v4 the switches slided.

**Comment by Justsnoopy30** [comment]
See these:
v4 Switches: 
https://getbootstrap.com/docs/4.4/components/forms#switches
v5 Switches:
https://deploy-preview-29925--twbs-bootstrap.netlify.com/docs/5.0/forms/checks#switches
v4 Checkboxes:
https://getbootstrap.com/docs/4.4/components/forms#checkboxes
v5 Checkboxes: 
https://deploy-preview-29925--twbs-bootstrap.netlify.com/docs/5.0/forms/checks#switches

Notice that the v4 versions have animations, and the v5 versions do not.

**Comment by XhmikosR** [comment]
The latest master preview is this: https://twbs-bootstrap.netlify.com/docs/4.3/forms/checks#switches. Please don't rely on PR previews as they become very fast outdated.

@twbs/css-review any thoughts why this might happen?

**Comment by Justsnoopy30** [comment]
It still says 4.3 docs.

**Comment by XhmikosR** [comment]
It doesn't matter, the version bump will happen when v5.0 is out.

**Comment by Justsnoopy30** [comment]
Okay, so that is the up-to-date v5 doc.
