### ISSUE TITLE
custom-select next to text input with form-control-sm is too high

### ISSUE THREAD

**Issue by eduarddrenth** [twbs/bootstrap#30521]
When a custom-select sits next to an input with form-control-sm it is too high, see https://frisian.eu/custom-select.html.

- Os: ubuntu 1804
- firefox 74.01
- https://frisian.eu/custom-select.html

my workaround is: style="max-width: 31px" on the select.

**Comment by MartijnCuppens** [comment]
You need to add the `.custom-select-sm` class to `.custom-select`

**Comment by eduarddrenth** [comment]
thnx, could have thought of that. Didn't ran into this class in the docs.

**Comment by mdo** [comment]
https://getbootstrap.com/docs/4.4/components/forms/#select-menu

**Comment by eduarddrenth** [comment]
Yeah, missed that, new glasses perhaps
