### ISSUE TITLE
Switch indicators move 1px when focused

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#30539]
![5zyey-thm0u](https://user-images.githubusercontent.com/4065765/78798192-a629ea00-79f3-11ea-8c18-ee24c04af59e.gif)

**Comment by mdo** [comment]
Not seeing this myself in Chrome and Safari. From what I can see in the gif, the focused state is actually the correct one. Perhaps some pixel rounding issues?

**Comment by infoassef** [comment]
Essa opção deve ter como ativar e desativar. Nem todos gostam desse tipo de efeito, pode ser que atrapalhe dependendo do layout de cada projeto.

**Comment by ysds** [comment]
Sorry I forgot to mention the environment. I can see that in Chrome on macOS.

**Comment by MartijnCuppens** [comment]
I can only reproduce this if I zoom in.

This seems to be a browser bug, backgrounds seem to shift when focused (even if no additional CSS is applied).

**Comment by mdo** [comment]
Since this only happens with zooming, should we close? I don't believe we try to iron out zooming issues anywhere else.

**Comment by ysds** [comment]
Close this as won't fix :)
