### ISSUE TITLE
Dismissable popover color conflicts with a:not[href])

### ISSUE THREAD

**Issue by ffoodd** [twbs/bootstrap#30531]
Next to [#29140](https://github.com/twbs/bootstrap/pull/29140), we now have a conflicting style in dismissible popovers since it has no `[href]` and its styles rely on a single class specificity:

https://twbs-bootstrap.netlify.com/docs/4.3/components/popovers/#dismiss-on-next-click

I'm not quite sure about the solution for this:
- re-introduce `:not([tabindex])`, which would reintroduce what @ysds wanted to remove;
- use `!important` on `.btn-*` variants (ugh)?
- force color by using `.text-white` in that case?
- anything else? Maybe using colored links or something?

And moreover, is there any other case of links without target styled as buttons?

**Comment by mdo** [comment]
This button is lacking an `href` and should likely just be converted to a `<button>` element. That'd fix the issue I think?

**Comment by ffoodd** [comment]
@mdo Indeed! Noted this quickly while theming things around, but should definetely be a button!

**Comment by ffoodd** [comment]
It's been fixed in v5 and backport in progress to v4.
