### ISSUE TITLE
min-height, min-width to 100% utilities

### ISSUE THREAD

**Issue by JochLAin** [twbs/bootstrap#30543]
In current version of bootstrap classes `mh-100` and `mw-100` respectively define the `max-height` and `max-width` to `100%`.
But none for `min-height` and `min-width` ; usefull, for example, in the `dropdown-menu` aligned to the width of its parent but not restricted.

I had the idea to use the classes : 
- `mh-100` and `mw-100` for `min-height` and `min-width`
- `Mh-100` and `Mw-100` for `max-height` and `max-width`

I know that this feature is complicated because of long time implemented feature but it's cool if you can think of that in future versions.

Thank you

**Comment by JochLAin** [comment]
Another possibility is to create classes like the viewport helper classes :
- `min-h-100` and `min-w-100` for `min-height` and `min-width`
- `max-h-100` and `max-w-100` for `max-height` and `max-width`

**Comment by Derplicity** [comment]
Hey @JochLAin this feature is already implemented :)
You can use min-vh and min-vw to define the respective min-width and min-height.

```
// bootstrap/scss/_utilities.scss
"min-viewport-width": (
      property: min-width,
      class: min-vw,
      values: (100: 100vw)
),
"min-viewport-height": (
      property: min-height,
      class: min-vh,
      values: (100: 100vh)
),
```

Hope this helps!

**Comment by Derplicity** [comment]
Can I work on this feature? :)

**Comment by psjishnu** [comment]
@mdo Fixed the Issue .

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/pull/30891#issuecomment-694523498
