### ISSUE TITLE
Repairing a Broken Navbar - Know your audience.

### ISSUE THREAD

**Issue by SunbeamRapier** [twbs/bootstrap#30576]
About me: I learned to program in 1977 using RPG-II on an IBM System 3.  Over the last 40 years I have worked with various languages and platforms.  Currently I am re-skilling in the full stack web development arena, which is how I come to be looking at the bootstrap navbar.

On the getbootstrap navbar page there is a lengthy dissertation on the usefulness of your navbar.  However, for me, this information is absolutely impenetrable - it may as well be written in Swahili for all the use it is to me.

And this brings me to a wider point: that documentation in the open-source environment is almost always poor and I feel that this is most likely the result of technical experts writing the documentation, rather than documentation experts who seem to be in short supply in this arena.

So let me give you an example.  I arrived at this site because the Udemy Full Stack course that I am halfway through uses an earlier version of your navbar and the current version of the navbar is incompatible with the existing code.  While it is possible to downgrade the environment and use the old version of the navbar, I would prefer to be working with the latest components - which I will be implementing in my own websites.

So, I arrived at this navbar page with a specific need - how to fix a navbar which was broken when you rewrote the code.

It seems to me that many people will arrive at this webpage for the same reason and I find myself wondering why you do not have a specific ready-made solution to this issue.  Instead, as I have already said, you offer a lot of information but not in a form that I can digest and I remain none the wiser and my navbar is still broken.

So I would ask you a couple of questions here.  Firstly, who do you think your audience is?  In other words, who did you have in mind when you wrote this long treatise on the new navbar?

It seems to me that, in every aspect of your software technologies, your audience will range from absolute beginners to experts.  I think you probably know this already, but when you wrote this material you appear to have written it for the experts, and paid no attention at all to the beginners. In my experience, this is how technical people write - they tend to write for other technical people.

Knowing your stuff does not mean you can teach it to others...

And that is the problem we have here.  You have broken the navbar, but you are not teaching your users, new or old, how to fix their broken navbars.

But that is not the only issue.  I do not have a navbar in my own website as yet but I want a navbar with certain behaviours.  I want the links on the right and I want to be able to easily change the fonts and font sizes.

Again, your documentation does not assist me in any way.  I do not have a starting point and I do not see any simple steps that I could take to make the changes I require.

My mother was a music teacher all her life, specialising in the 'cello for children.  Her father was a language master in a British public school.  We had many conversations about teaching.

She once gave me some very good advice when I got a student job to teach music after school:  When you are teaching someone anything new, it is vital that you establish where your student is, and then lead the student in simple steps from where they are to where you want to take them.

It is very simple, but it works.

So, how might you apply this idea to your navbar documentation?

Firstly, I think you need to establish why someone has arrived on this part of your website.  Are they here to fix a broken navbar?  Are they new to bootstrap navbars and looking to implement one for the first time?  Are they looking to change the behaviour or add features to an existing bootstrap navbar?

Then you should present the simplest navbar first and explain, in detail, its every component in simple terms.

Only then should you explain how to add or modify components, one by one, to add greater sophistication to, or change the look and feel of, the navbar.

This is what an experienced teacher would do.  What do you do?  Instead of a simple navbar as an example, you present the most complex navbar imaginable right at the start and the implication of this is that you expect the reader to review the full documentation of every navbar feature first before looking for a solution to their specific problem.  And, as a consequence, you probably instantly lose every reader who is not already an expert. 

It is probably also true that those who are already experts in your navbar do not often end up on this page and are not, therefore, among your target audience.  Most likely, most of your readers are not experts and this is probably your largest audience and your documentation should speak to them.

Technical people delight in the technical aspects of their work, and they love to show it off.  In doing so, they often adopt an "audience" of other technical experts. They are not trained to teach and, as here, either do not consider the new users at all or do not know how to engage them.

Sunbeam Rapier
Sydney Australia

**Comment by mdo** [comment]
My dude, if you have a troubleshooting problem, please share the details like our issue template kindly requests. There’s no need to get on a high horse to tell us your life’s story or lecture us on our project and complain about all of open source.

I’ll leave this open in hopes you’ll try again and share what the problem is so we can offer to help.

**Comment by SunbeamRapier** [comment]
Dude

I don’t have a troubleshooting problem, other than finding the appropriate instructions in a readable format for the navbar.


You have not addresses the issues I raised, though I am not surprised.  Nor am I surprised by your tone.

We can leave it there.  I will pursue other options.

**Comment by Flyer53** [comment]
First of all bootstrap is a great tool and we should be grateful that it's provided for free. But ...

@SunbeamRapier Your words about the bootstrap docs (and technical docs in general) are 100% correct 👍 

@mdo Your answer to the original post is completely inappropriate and you obviously missed the gist about it.

**Comment by SunbeamRapier** [comment]
The final nail in the coffin here is the lack of support, not to mention the gratuitous insults thrown in for good measure.

The issues you asked me to document were already discussed in the original post: links on the left instead of the right, no clue to how to set the fonts.  However I do not now require a solution.  I have a working navbar from an earlier project which does everything I need and it will not be broken unless I break it. :-)

I could never again recommend the use of bootstrap code in any commercial undertaking.  I will pass on my comments, along with your disappointingly immature response, to the Udemy instructor and my fellow and future students, and suggest that Udemy distance itself from an organisation which behaves in such a manner.

**Comment by mdo** [comment]
The use of `my dude` in my comment was unnecessary, but there were no insults, nor anything inappropriate here. No offense was intended and if you're upset by this, please re-examine your opening remarks.

Your 920+ words that appear to be about the problem of alignment and font-size in the navbar—which I apologize for glossing over—starts with your history with computers, includes lessons learned from your parents, and doesn't tell me what version of Bootstrap you're using or anything else doesn't help us help you and others in this situation. It comes across as very condescending and unnecessary, while also showing you ignored the guidelines we have in place for reporting issues.

Next time, please do as the issue templates and contributing guidelines request—tell us your Bootstrap version, operating system or device and version, include a demo or code snippet, and succinctly tell us what the issue (bug or troubleshooting or question) is, and we can more quickly answer it as best as we can.

Here's what I mean by that, and why I made my earlier comment:

> And that is the problem we have here. You have broken the navbar, but you are not teaching your users, new or old, how to fix their broken navbars.

There are no details on what's broken here. I don't know if you've updated from v2 to v3 or v3 to v4, or some other release entirely. I don't know if you're missing the JS to make the responsive navbar and dropdowns work. I don't know if it works on one browser or another. The navbar is incredibly complex, and it's been iterated upon heavily across every major release, so it makes sense that there are complications or questions. However, we cannot improve it if we don't know the exact issues people face. Hence why our issue templates exist and we ask people to provide context around their code.

If this was indeed an upgrade problem from say v3 to v4, we have a [migration docs page](https://getbootstrap.com/docs/4.4/migration/#navbar) to address the largest changes, including how to upgrade in most situations.

You go on to say:

> But that is not the only issue. I do not have a navbar in my own website as yet but I want a navbar with certain behaviours. I want the links on the right and I want to be able to easily change the fonts and font sizes.

Okay, that's solvable in v4. The beginning of the [navbar docs discusses how it works](https://getbootstrap.com/docs/4.4/components/navbar/#how-it-works), including mention of spacing and alignment:

> Use our spacing and flex utility classes for controlling spacing and alignment within navbars.

Even v3 has a section on [navbar component alignment](https://getbootstrap.com/docs/3.4/components/#navbar-component-alignment). I can definitely look into an explicit section for alignment of navbar contents for v4 and v5—that's an easy enough fix to the docs that I do think could help some folks, especially with flexbox.

Have a look at the v4 navbar docs for those spacing and alignment links, and if that doesn't help, please ask here again or in the community Slack. While I realize you might not know what utilities are, or some of the other terms there, I'd expect the "how it works" section and numerous examples of varying complexity on the navbar docs page to be a decent starting point.

Font-sizes would need to be custom styles in addition to Bootstrap, or an override of our global font styles, as we don't have any prebuilt classes in v4.4 for that, but we have a PR open to add options there for v5.

Moreover, there are other parts of our docs that we could've shared if you had told us more about your setup. I've been assuming you're using v4, so keeping with that, don't forget to review [the four example pages of navbars in our docs](https://getbootstrap.com/docs/4.4/examples/#navbars), including one with several responsive navbar variations and alignment options.

Share what you wish with others about your experience here—I'll leave this all as-is for you and them.
