### ISSUE TITLE
Modals do not open in Citrix or Remote Desktop environments 

### ISSUE THREAD

**Issue by kduraiswami** [twbs/bootstrap#30574]
Using: Bootstrap 4.4.1
Operating System: Windows ONLY in Citrix or Remote Desktop environments
Test: https://codepen.io/kaipie/pen/YzyyzmZ

We have customers that try to access our site in Chrome or Firefox within Microsoft Remote Desktop and Citrix environments. In both cases modals will not open and only the backdrop will show. Other Bootstrap JS functions that we use like collapse or tab navigation work correctly, only the modals will not show. If I type bootstrap in the Chrome console it shows all the correct functions including Modal and they are using the latest Chrome version. The same customer can use the same exact build of our site in a regular Windows environment normally.

We have standard use of the modal and data attributes as I understand:

```html
<button data-toggle='modal' data-target='#myModal' class="btn btn-success col-2 mt-1">Show Modal</button>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-modal="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">My Modal</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        Hi
      </div>
    </div>
  </div>
  </div>
```

Please let me know if you need any other information on it or any further clarification from me. If you think it is a Chrome issue I will raise it with them, but because this happens with both Firefox and Chrome I am coming here first.

**Comment by XhmikosR** [comment]
Some quick thoughts:

1. jQuery 3.5.0 is broken with our collapse, not sure if this affects your other codebase and throws; use jQuery 3.4.1 in the meantime
2. please use v4.4.1 just to be safe
3. please post the complete console log and check if there are any network errors
4. please post how you are loading our assets (full HTML tags if they are loaded from a public CDN)

I don't have any of the environments you described, but feel free to contact me on Slack or via e-mail with temporary access to a machine so that I try. But make sure to tackle my aforementioned points first.

**Comment by kduraiswami** [comment]
Thank you, responding to your points: 

1. We are using jQuery 3.4.1 
2. We are using Bootstrap 4.4.1
3. The console log is clean besides some unrelated SameSite issues. 
4. We are loading our assets via rails pipeline and the Bootstrap gem v 4.4.1 

I will ping you on email and we can schedule a time with one of these vendors thank you very much.

**Comment by XhmikosR** [comment]
I'm going to close this since after a discussion via email this was worked around.

**Comment by superego1984** [comment]
Hi @XhmikosR , we met the same issue, could you please let us know the work around?
Thanks in advance

**Comment by kduraiswami** [comment]
Our workaround was to create a custom function to open the modal and show the backdrop. Just attached a listener to the .modal class on show or hide and add / remove class d-none from modal backdrop. That code is all private so I cannot post it here unfortunately. It is slower, but there was no way for us to determine why this issue came up. Very strange, I would be curious to hear if you come up with an explanation.
