### ISSUE TITLE
`.form-text` follow-up

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#30577]
Follow up on https://github.com/twbs/bootstrap/pull/30565

- We use `<small>` in our docs, which might not always be correct, the font size is not smaller per se.
- We still use `text-muted` in the horizontal form here: https://twbs-bootstrap.netlify.com/docs/4.3/forms/overview/#form-text
- We should share properties between `.form-text`, `.valid-feedback` and `.invalid-feedback`

I think we better remove `display: block` from `.form-text` and replace the `<small>`s with `<div>`s and use a `<span>` in the horizontal form.

**Comment by zalog** [comment]
Hm, agree. I can take this to.

**Comment by MartijnCuppens** [comment]
Go ahead, thanks man!
