### ISSUE TITLE
Slimmer than jquery.slim.js

### ISSUE THREAD

**Issue by dilyanpalauzov** [twbs/bootstrap#30607]
Document what are the absolutely minimal jQuery modules, necessary for Bootstrap 4.4.1.

[jQuery can be build with diffent modules](https://github.com/jquery/jquery/blob/master/README.md#modules).  The slim distribution excludes the modules: ajax, callbacks, deffered and effects.  This means that the slim distribution includes the modules: css, css/showHide, deprecated, dimensions, event, event/trigger. offset, wrap, core/ready, deferred, exports/global, exports/amd.

I see that bootstrap uses the modules css, css/showHide, event, event/trigger, while it does not use core/ready and deferred.

Please clarify, whether bootstrap uses the deprecated, dimensions, offset, and wrap modules in the documentation, and provide a hint how to build jQuery that is slimmer than than jQuery.slim yet runs Bootstrap 4.4.

**Comment by mdo** [comment]
I think we'll pass on doing this ourselves, but if someone wants to contribute for v4, we'd love a PR. v5 is dropping jQuery and that's our focus at this point.

**Comment by garak** [comment]
I think you should reconsider this, as long as Bootstrap 4 is supported.
I'm just struggling with tooltip component, which unfortunately work only with full jquery (not with jquery slim).
If you don't want to spend effort on this, you should at least remove the statement about jquery slim in v4 documentation.
