### ISSUE TITLE
.dropdown-toggle :: after vertical-align: 0.255em;

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#30614]
https://github.com/twbs/bootstrap/blob/338ca8382187ecf9cd7c4c1f63c28f7853330c2d/dist/css/bootstrap.css#L3703

.dropdown-toggle :: after vertical-align: 0.255em;
Why is it 0.225em and why is it a specific value instead of a fixed parameter?

**Comment by mdo** [comment]
You can use relative unit-less values or specific units, which we've done here. This ensures the CSS trick for creating these little carets for dropdowns is aligned based on it's relative size. Check the source code for the `caret()` mixin.
