### ISSUE TITLE
Documentation for Radio Button Group

### ISSUE THREAD

**Issue by einfallstoll** [twbs/bootstrap#30615]
At the moment the documentation for grouped button-styled radio buttons is located in the "Buttons" component. However, I think it should be placed (or at least referenced) in the "Button Groups" component or the "Forms" component page. What do you think?

**Comment by mdo** [comment]
Could probably do a cross link of some kind—right now it's there because it's powered by the button JS plugin.

**Comment by patrickhlauke** [comment]
noting that - if this does go through in the end - for the non-JS based version in future, we were planning to have proper mentions in both "buttons" and "button groups" https://github.com/twbs/bootstrap/pull/28463

**Comment by tumbleshack** [comment]
I'd like to give this a shot by adding a reference to [the details](https://github.com/twbs/bootstrap/blob/master/site/content/docs/4.3/components/buttons.md#checkbox-and-radio-buttons) from "Button Groups" and from "Forms"

I'm new to contributing and eager to learn :)

**Comment by tumbleshack** [comment]
[There appears to already be a link](https://github.com/twbs/bootstrap/blob/master/site/content/docs/4.3/components/button-group.md#basic-example) from `Button Groups` to the button plugin:

```Wrap a series of buttons with .btn in .btn-group. Add on optional JavaScript radio and checkbox style behavior with [our buttons plugin]({{< docsref "/components/buttons#button-plugin" }}).```

Is this correct or am I looking at the wrong branch?

**Comment by einfallstoll** [comment]
@tumbleshack You're correct. However this issue refers to the button group styled _radio buttons_. Maybe we can improve the existing text?

**Comment by vishalsharma2063** [comment]
can be fix by grouping all together

**Comment by simpjack99** [comment]
I think you can find the answer on this site bro http://www.joker123gaming.co have a good day everyone

**Comment by simpjack99** [comment]
i think the documentation for radio button is very important. it can be fix by together at https://Joker123gaming.co lets do it!

**Comment by TimmyGunawan123** [comment]
> i think the documentation for radio button is very important. it can be fix by together at https://Joker123gaming.co lets do it!

Lol you sure bout that?
