### ISSUE TITLE
footer can be included in https://getbootstrap.com/docs/4.4/examples/starter-template/

### ISSUE THREAD

**Issue by jyothi0093** [twbs/bootstrap#30627]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by mdo** [comment]
Please re-read the issue templates instead of posting them blindly across five issues. We understand you'd like updated and expanded examples—this could've been done in a single issue, and with more description than five titles.

**Comment by mdo** [comment]
In regards to each issue you opened:

- **This issue:** Sure we could add a footer, but that's more than what a starter template needs. The goal of this file is to show a single component and some grid basics. You can easily create your own footer, or look to another example.
- #30624: The goal of an example isn't to provide you with every single piece or step. We've created a checkout form, feel free to create the invoice page based on that.
- #30626: Similar to the aforementioned, you can easily create your own forgotten password page and more from this template.
- #30625: As noted in the first comment there, this is possible.
- #30623: A quick Google search will yield you some fantastic options for copy to clipboard, including the one we use in our own documentation.
