### ISSUE TITLE
corousel can be autoscroll with the timer rather than manually scrolling it  v4.4

### ISSUE THREAD

**Issue by jyothi0093** [twbs/bootstrap#30625]
https://getbootstrap.com/docs/4.4/examples/carousel/

**Comment by thedhanrajsingh** [comment]
`<div class="carousel-item" data-interval="2000">`
this will get your carousel on auto slide . But why are you saying auto-slide is not there?

**Comment by mdo** [comment]
Centralizing in #30627.
