### ISSUE TITLE
Collapse animation is not working on iOS

### ISSUE THREAD

**Issue by eberhapa** [twbs/bootstrap#30635]
The collapse animation isn't working on iOS if reduce motion is active on iOS in the accessibility settings? Why is that? All other animations are working?

**Comment by mdo** [comment]
> Bootstrap includes support for the prefers-reduced-motion media feature. In browsers/environments that allow the user to specify their preference for reduced motion, most CSS transition effects in Bootstrap (for instance, when a modal dialog is opened or closed, or the sliding animation in carousels) will be disabled.

https://getbootstrap.com/docs/4.4/getting-started/accessibility/#reduced-motion

**Comment by patrickhlauke** [comment]
> All other animations are working?

just wondering...which "other animations" are you referring to? in Bootstrap? or just "on other sites"?

**Comment by eberhapa** [comment]
Thank's for your help. I think I'm bad at using google :S 

@patrickhlauke I mean custom animations.
