### ISSUE TITLE
JQuery 3.5.0 and Bootstrap 3.4.1

### ISSUE THREAD

**Issue by MarcGodard** [twbs/bootstrap#30644]
`collapse.js:178 Uncaught TypeError: Cannot convert object to primitive value`

Looks like reverting to an earlier version of jquery fixes it.

**Comment by XhmikosR** [comment]
Duplicate of #30553

**Comment by psttf** [comment]
@XhmikosR isn't this issue specifically about Bootstrap v3? Are there any plans to support jQuery 3.5.0 in Bootstrap v3?

**Comment by XhmikosR** [comment]
v3 is EOL, sorry.

**Comment by MarcGodard** [comment]
@XhmikosR This is a security update, not a feature request. I think security updates should always be considered. I have so much work in V3 that changing that is a huge amount of work. Not doing security updates will make people use tools that continue with security updates.

**Comment by XhmikosR** [comment]
I'm aware of that, but be my guest and try yourself and see what works or
not.

Security issues are not always applicable to every website the same way.

**Comment by XhmikosR** [comment]
There's a time for everything. Feel free to use a tool that fits your needs better and is supported 7 years after its first release.

/CC @mdo

**Comment by MarcGodard** [comment]
@XhmikosR There are lots, but like I said I am already invested. Its not about the number of years, but the number of users, and the number of versions. I am only 1 major version behind. Also, I still get security updates for many things that are older... think Windows XP.... Anyway, I guess I will need to fork it.

**Comment by XhmikosR** [comment]
Well, we are not Microsoft, are we? If this wasn't open-source things might have been different.

Also, we have announced v3 EOL a long time ago.

**Comment by MrP01** [comment]
As I also have a huge project still running on Bootstrap 3 & jQuery, I had a similar problem. Plans are to upgrade the UI framework as soon as possible anyway. However, the problem seems to have vanished with jQuery 3.6.0!

**jQuery 3.6.0 and Bootstrap 3.4.1 work again**, like a charm!

**Comment by achamberlin** [comment]
@MrP01 you just saved my bacon! Thanks.
