### ISSUE TITLE
Bootstrap v4.4.1 Modal with data-backdrop="static" data-keyboard="false" blinks on outside click.

### ISSUE THREAD

**Issue by TanvirArjel** [twbs/bootstrap#30647]
From version **4.4.0**, modal with `data-backdrop="static" data-keyboard="false"` blinks on outside click.

If the page has a scroll or the modal is vertically centered then the scrollbar also blinks which so is disturbing. Please take look onto it.

Thank you.

**Note: Before version 4.4.0, it's fine.**

**Comment by mguilmineau** [comment]
I second this - bootstrap 4.4.1 on data-backdrop="static" with a scrollbar in the background page, blinks on clicking in the grey zone. Even if there is no scrollbar, the modal disappearing and reappearing instantly makes for a weird jerky experience.

**Comment by TanvirArjel** [comment]
@mguilmineau I see it has been fixed in 4.4.2: https://github.com/twbs/bootstrap/pull/30326

**Comment by mguilmineau** [comment]
Thank you - the hot fix
.modal.modal-static .modal-dialog {
	-webkit-transform: none !important;
	transform: none !important;
}
also addresses this in the meantime.

**Comment by XhmikosR** [comment]
@ysds is this the same as #30322?

**Comment by TanvirArjel** [comment]
I expected that it has been fixed in version `4.5.0` but I have just checked that it has not been fixed in version `4.5.0` release! 😥

**Comment by ffoodd** [comment]
The PR tackling this —previously mentionned— is still open: #30326

It'll probably merged soon. FWIW, the next v4 is scheduled for the next month—and we'll probably stick to a monthly release from now on.

**Comment by ysds** [comment]
> @ysds is this the same as #30322?

@TanvirArjel Please create a online demo for clarify your issue.

**Comment by TanvirArjel** [comment]
@ysds Yes! This is the same issue as https://github.com/twbs/bootstrap/issues/30322

**Comment by ysds** [comment]
@TanvirArjel Thank, Close this due to duplication.
