### ISSUE TITLE
navbar-nav / nav "active" class inconsistency

### ISSUE THREAD

**Issue by vladrusu** [twbs/bootstrap#30652]
Hello!
To make an item active, on a navbar we have to add "active" class to the "nav-item", which I found normal.

But on tabs/pills we have to add the "active" class to the nav-link (not on the nav-item!), which I found strange.

Can I ask what is the logic behind this? Logically, the TAB (nav-item) should be the one selected (active), not the link within (nav-link).

I propose to **ALWAYS** add the active class to the nav-item, as it makes css styling easier. With the current design basically I can't style the selected nav-item, only the nav-link.

**Comment by kwaaui** [comment]
@vladrusu have you tried using the <nav>-based navigation? This way you can use the anchors with both classes (nav-item and nav-link) on the same element and style them easily, ignoring the nav-link.

**Comment by vladrusu** [comment]
Hi @kwaaui !
That's correct. I didn't know it, thank you for the answer.
Still, the inconsistency question remains for the BS team.

**Comment by kwaaui** [comment]
That's right, although they mention that it can be applied directly to either nav-item or nav-link:
https://getbootstrap.com/docs/4.4/components/navbar/#nav

**Comment by mdo** [comment]
We'll update the docs to fix the inconsistency, but you can use both. In v5 I'm going to propose we drop the parent `.active > .nav-link` and stick to using `.nav-link.active`.
