### ISSUE TITLE
bootstrap表头固定偶尔失效

### ISSUE THREAD

**Issue by yuankaifan** [twbs/bootstrap#30658]
在用bootstrap创建表格时 添加了固定表头的配置 但创建之后表头没有固定 但是如果改变一下浏览器窗口大小后表头就变为固定 请问能够怎么解决 紧急！！！！！

---

From Google Translate:

> When creating a table with bootstrap, a fixed header configuration was added, but the header was not fixed after the creation, but if you change the size of the browser window, the header becomes fixed. What can I do? Urgent! ! ! ! !

**Comment by zhangchenglin** [comment]
你需要翻译成中文
You need to translate into chinese

**Comment by mdo** [comment]
Bootstrap tables don't have fixed table headers, so unsure if you're referring to that.

If you've added a table to the page and then a fixed header like a fixed navbar and that overlaps, that's another issue and one that's covered by our docs.

Beyond that, unsure what to do here without more details.
