### ISSUE TITLE
Overflow hidden on body element doesn't work on mobile when modal is open

### ISSUE THREAD

**Issue by cichyadam** [twbs/bootstrap#30661]
# Operating system and version
iOS 12.4.5
# Browser and version
Google Chrome 81.0.4044.124, Safari 12
# Bug description 
When the modal is open actually does not work on mobile devices. I tested in on documentation website of modal for bootstrap-modal and react-bootstrap-modal - it does ‘work’ when testing in desktop browser, however not on the mobile in real life.

https://getbootstrap.com/docs/4.0/components/modal/

**Comment by mdo** [comment]
Unsure what you're looking at, but modals launch just fine on mobile in our docs. Just tested https://getbootstrap.com/docs/4.4/components/modal/#live-demo.

**Comment by patrickhlauke** [comment]
I'm guessing it might be that the page behind the modal can still be scrolled on mobile (depending on length of modal)?

**Comment by cichyadam** [comment]
I'm not sure about the answer of @mdo, I have tested his provided link and the `overflow:hidden` does not seems to work on the body on my mobile so the page behind modal still can be scrolled, which I personally think that user should not be able to scroll the page while the modal is open does not matter on the length - the modal in docs is not that high and page can still be scrolled while modal is open.

**Comment by mdo** [comment]
Ah, sorry, that’s unfortunately a known issue I believe with #22311.
