### ISSUE TITLE
Cannot change carousel control colors in v4: New Simple Solution

### ISSUE THREAD

**Issue by ulvimardaliyev** [twbs/bootstrap#30675]
In this #21985 issue, it is asked to change the arrows' color of `carousel-control-prev` and `carousel-control-next`. When I reading the issue, the following answer is recommended:

```
.carousel-control-next-icon {
    background-image : url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23ff0000' viewBox='0 0 8 8'%3E%3Cpath d='M1.5 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E")
    color: black;
}
```
I found that we can change the arrows color to any color with doing following steps:

- inside the code above, find `fill='%23ff0000`;

- add any hex color instead of  `ff0000`; (for example: `fill='%2332a852`, `fill='%23d9b00b`, etc.)

- color:black; => this is unnecessary.

**Comment by mdo** [comment]
Yes, this is a potential solution, but not something we're addressing in v4. We're aiming to redo the controls in v5 with SVGs in the HTML instead of the CSS.
