### ISSUE TITLE
The element with .dropdown-toggle class will appear mistake border-radius on right side.

### ISSUE THREAD

**Issue by Ray-Aries** [twbs/bootstrap#30698]
The element with .dropdown-toggle class will appear mistake border-radius on right side when it in the element with .input-group-append class. (except .dropdown-toggle class element is last child element.) 
Note. 
This issue has been confirmed on chrome( 80.0.3987.132 x64), firefox(75.0 x64）and Edge(81.0.416.68 x64).
This issue happen on Bootstrap ver 4.4.1, ver 4.3.1, ver 4.2.1 & 4.0.0.

[BS4InputGroups.txt](https://github.com/twbs/bootstrap/files/4558828/BS4InputGroups.txt)

![BS4issue](https://user-images.githubusercontent.com/48224669/80718270-84bca980-8b2c-11ea-8114-dc9306f38d4f.jpg)

**Comment by XhmikosR** [comment]
What's your display's DPI?

**Comment by Ray-Aries** [comment]
Hi, XhmikosR

> What's your display's DPI?
My notebook resolution is 1366*768.
I have been confirm resize browser window that still found this issue.
This issue on my mobile device - using chrome v80.0.3987.132 also.
> Also, please provide a codepen.
I have provide the complete source code as BS4InputGroups.txt in last comment.

**Comment by Ray-Aries** [comment]
Hi, XhmikosR

> What's your display's DPI?
My notebook resolution is 1366x768~96 dpi.
I have been confirm resize browser window that still found this issue.
This issue on my mobile device(resolution 1520x720~269 ppi density) - using chrome v80.0.3987.132 also.
> Also, please provide a codepen.
I have provide the complete source code as BS4InputGroups.txt in last comment.

**Comment by Ray-Aries** [comment]
I have short term solution that is add attribute style="border-top-right-radius: 0;border-bottom-right-radius: 0;" on element with .dropdown-toggle class  inside the container element with .input-group-append class.

Base on short term solution, check original file bootstrap.css that found root couse is original style code have problem.

![BS4issueRootcouse](https://user-images.githubusercontent.com/48224669/80778150-faab2a00-8b99-11ea-95a7-b9c3db53c90e.jpg)

**Comment by XhmikosR** [comment]
@twbs/css-review

**Comment by ysds** [comment]
See #28150

**Comment by Ray-Aries** [comment]
Hi @ysds thanks for your commend,
but this issue happened on bootstrap ver 4.5.0 still.
the issue ＃28150 solution can't solve in my test case.
test case sample https://codepen.io/ray-aries/pen/mdeKBYV
I have read your commend in issue ＃28150. and check the element style code with chrome's DevTools and original bootstrap.css file.
I am made shure .dropdown class has position: relative (as your commend in ＃28150),
but in test case(both ＃28150 and this  ) with chrome's DevTools can't find position: relative on issue happend element, due to test case used class is .dropdown-toggle (not .dropdown) and not is child element inside .dropdown class element.
I'm sorry to bother you.
just make a note in here.
