### ISSUE TITLE
input group buttons should have their own $input-group-btn-border-radius variable set

### ISSUE THREAD

**Issue by bbarry** [twbs/bootstrap#30704]
If you are setting variables and importing the scss in a project:

    $btn-border-radius: 0;
    $btn-border-radius-lg: 0;
    $btn-border-radius-sm: 0;

    @import '~bootstrap/scss/bootstrap';

causes the `.btn` rule to not have border radius but it also kills the border radius on input group buttons which I would like to keep derived from the `$input-border-radius` 

at the moment I'm adding this after my import:

    .input-group .btn {
      @include border-radius($input-border-radius, 0);
    }

**Comment by mdo** [comment]
Closing this as a stale request for now—I don’t think we should reset this for input groups. We already have too much variable abstraction IMO and I’d like to see it reduced for our following major version. Feel free to update here if there’s something I should reconsider though!
