### ISSUE TITLE
Feature Request: Additional breakpoints for wide/ultra wide/QHD/UHD/8K monitors

### ISSUE THREAD

**Issue by NguyenTran-JavaDeveloper** [twbs/bootstrap#30718]
Hi Bootstrap team,

First of all, I would like to thank all the members in the team for building Bootstrap framework. It is such an amazing, powerful, and flexible tool that is needed in designing every responsive web app. However, there is some missing feature that could be a game changer (and future proof).

In the past, monitors with high resolution are (extremely) rare (and expensive). As a result, **HD** or **HD+** is very common. As technology evolves, **FullHD** has become a norm even on laptop let alone desktop. In the recent years, **_ultra-wide_** monitors (**21:9**) are becoming more and more popular thanks to their high productivity and truly immersive experience. Lastly, **QHD**, **4K**, **5K**, and **8K** monitors are also making their way to the market due to a huge decrease in price and high demand (movie, games, etc.)

Therefore, I think that the current breakpoints (**xs** to **xl**) in _v.4_ as well as the new ones (**xs** to **xxl**) in _v.5_ are not enough for the current market.

For instance, I would like to have _4 equal-width_ columns (**col-xl-3** or **col-xxl-3**) across a FullHD screen on desktop. Then I could only use a single breakpoint (1200px or 1400px) for FullHD screen.

When moving to a mobile devices such as tablet (iPad Pro or Galaxy Tab S6), I would like to have _3 equal-width_ columns (**col-xl-4** or **col-xxl-4**) instead of 4 (the screen is now smaller) since putting 4 columns are too tight, crowded, (and ugly).

Unfortunately, there is no option as the largest breakpoint is 1200px (or 1400px). The problem gets even worse on ultra-wide or super high resolution screen such as QHD, 4K, 5K, and (8K) as all the columns expand to take up the whole screen.

So my suggestion is that there could be additional breakpoints to handle these ultra-wide and super resolution monitors. Something like this:

**col-fhd-**: 1920px
**col-qhd-**: 2560px
**col-uhd-**: 3840px
**col-8k-**: ....

(the naming convention could be better ^__^)

Yup, that's all I would like to request for the next release of bootstrap. It would be really nice and handy to have extra breakpoints for those high-end monitors so that a truly responsive design could be implemented on all the screens.

Thank you very much for all your hard work and dedication to the project,
Nguyen Tran

**Comment by morrissey-ingenious** [comment]
While adding additional breakpoints would be nice, it bloats the css files.  You can add your own breakpoints easily and recompile to suite your needs.

[Grid Tiers](https://getbootstrap.com/docs/4.4/layout/grid/#grid-tiers)

**Comment by mdo** [comment]
Yup, I don't see us implementing these. Just haven't come across something widespread enough. If there's enough demand, maybe make an add-on package that modifies the upcoming v5 utilities API :).

**Comment by NguyenTran-JavaDeveloper** [comment]
@morrissey-ingenious Thanks for reminding me about the Sass variables. Even though it does address the issue, it is just a temporary workaround (not a solution). Adding variables may not be difficult but time-consuming and inefficient. The custom Sass file has to be recompiled whenever a newer version is released. This makes migration a painful process. Honestly speaking, the purpose of using a framework is to reduce development time by conducting code reuse and production-ready/predefined implementation. If developer has to provide his/her own implementation due to the lack of features/standard/implementation, then what's the point in using framework when it cannot meet all the requirements...

@mdo Actually, the advantage of additional breakpoints is to give developers a higher granularity of control in designing the layout for the GUI. Like I mentioned above, those hi-end tablets with high resolution (which are common these days) will have the same layout on laptop/desktop screen. Either the content has to be terribly shrinked down to fit the tablet or expanded infinitely on the desktop. For my case, the FullHD screen (1920px width) is having the same layout as my tablet (1280px width). As you could clearly observe, the gap in screen width is so big (nearly 700px) which could fit a small tablet screen. For the ultra-wide/QHD/4K monitors, I have seen many (and many) people have to resize the browser about one third of the screen to surf the web as the content could not scale up to fit the whole screen properly. Some people don't resize but simply zoom up the page up to 250% via browser or OS settings. It's jut really terrible and painful... You could take a look at the link below:

https://imgur.com/a/wa4HGy1

I really like Bootstrap especially the grid system. I use it daily for my project but I just wish that it could be more comprehensive and more complete for the modern tech ^__^

**Comment by joehanna** [comment]
Thank you for the amazing work that goes into producing Bootstrap.

>  maybe make an add-on package that modifies the upcoming v5 utilities API :).

We wouldn't mind having to include another Bootstrap-maintained CSS in projects to get the higher resolution breakpoints up to 5120 for the big curved monitors. I understand what people are saying about keeping the framework small so it doesn't bloat with the additional breakpoints. However, Bootstrap is indeed mobile-first, but it is not mobile-only.  Having an add-on CSS file to support larger resolutions would mean it is opt-in and so everyone could be happy. 

I agree with @NguyenTran-JavaDeveloper that the big screens are on the rise, especially now that they are more affordable. We work with Bootstrap daily, and heavily for desktop dashboards. Maxing out at 1400 when a tonne of 5K iMacs are out there with 2560 means our layouts are stunted for nearly half the screen width. 

We don't use SASS directly in any of our projects, and as also mentioned previously, using a framework like Bootstrap is in aid of reducing workloads, especially when upgrading. Having to recompile Bootstrap every time a new version is released, and then host it on a separate CDN adds layers of complexity and time to our workflows.

Please reconsider an addon package to allow for ultra wide breakpoints.

**Comment by NguyenTran-JavaDeveloper** [comment]
@joehanna, it feels so good when there is someone having the same issue like I had a year ago ^__^.

It's just really weird that no one has ever thought about the issue when using the UI at high resolution monitor. If you check the UI for websites from even big corporations, they are still not ready for 2K, 4K or anything higher. Maybe, the developers do not have high resolution monitor or simply do not think about that...Or just because they are lazy...

A quick survey at the computer market nowadays could easily show that the high resolution monitor is nearly everywhere. Desktop, laptop, or even high-end tablet (Samsung Galaxy Tab S8 Ultra) not to mention those folding screens...

For the solution in dealing with high resolution monitor, the grid system in Bootstrap just does not work...Sadly speaking, the grid system is no longer applicable nor useful at those resolutions even if there are additional breakpoints...For that reason, I have stopped using Bootstrap since then...

To handle the issue at high resolution, an entire different approach has to be used...

If I discuss here, it would be irrelevant to the topic (being requested and closed). Moreover, it is no longer related to Bootstrap...

If you would like to know more about the approach, you could contact me via the following email:

**nguyen.tran.javadeveloper@gmail.com**

Have a nice day ^__^

**Comment by joehanna** [comment]
Thanks @NguyenTran-JavaDeveloper.

I need to add to my comments, that this is really only an issue when using the class `container-fluid`, which uses the entire width of the screen.
