### ISSUE TITLE
Since v4.4.0, dropdown-item with "active" class without href attribute have black text on hover

### ISSUE THREAD

**Issue by caseyjhol** [twbs/bootstrap#30726]
Windows 10: Chrome, Firefox, IE, Edge

Bootstrap v4.4.1 test case: https://codepen.io/caseyjhol/pen/ExVoYGg
1. Click button
2. Hover over active item
3. Text is black

Bootstrap v4.3.1 test case: https://codepen.io/caseyjhol/pen/bGVabzZ
1. Click button
2. Hover over active item
3. Text is white

Caused by commit 970c41755a2bdd8f3a4f5dbee039ca7c2dc8b053 (#29140). Obviously a button element could be used instead, but it would potentially require changing a lot of markup, and any existing `a` styling would also have to be applied to `button`. An empty `href` tag could also be used, but that's technically invalid HTML. Perhaps an exception for links with the dropdown-item class could be added?

**Comment by XhmikosR** [comment]
I couldn't reproduce with the latest v4-dev, soon to be v4.4.2

```
https://v4-dev--twbs-bootstrap.netlify.app/docs/4.4/dist/css/bootstrap.min.css
```

/CC @MartijnCuppens

**Comment by mdo** [comment]
I think in this case, since you're not using an `href` on the anchors, you should use the `<button>` element or add `href="#"`. #29140 seems right given the comparison to the native browser styles. Thoughts from @twbs/css-review?

**Comment by MartijnCuppens** [comment]
In theory, a link without href is valid and can be used like in the demo provided. We could do

```css
a:not([href]):not([class]) {
  &,
  &:hover,
  &:focus {
  &:hover {
    color: inherit;
    text-decoration: none;
  }
}
```

which only removes the styles from links without href or class.

**Comment by mdo** [comment]
I'm okay with the not class addition there... it'd at least fix issues where things overlap with our components.

**Comment by Jukien** [comment]
Hi @MartijnCuppens and @mdo, since Bootstrap 4.5.1, all my color links can't be overridden because you add `:not([class])`.
It would be better I think to add another case with `:not([class])` if not it's too restrictive.

```
a:not([href]),
a:not([href]):not([class]) {
  &,
  &:hover,
  &:focus {
    &:hover {
      color: inherit;
      text-decoration: none;
    }
  }
}
```

For example, I can't color all my links once and add a custom class for each link separately: 
```
<div class="text-muted">
  <a class="hover-success" (click)="add()"> <--- since I have a class on the `<a>` my `text-muted` class on the `div` can't be applied, I need to add it to all my links with 4.5.1 :/
    <fa-icon [icon]="['fas', 'plus']"></fa-icon>
  </a>
  <a class="hover-primary" (click)="edit()">
    <fa-icon [icon]="['fas', 'pencil-alt']"></fa-icon>
  </a>
  <a class="hover-warning" (click)="viewHistory()">
    <fa-icon [icon]="['fas', 'history']"></fa-icon>
  </a>
  <a class="hover-danger" (click)="delete()">
    <fa-icon [icon]="['fas', 'trash-alt']"></fa-icon>
  </a>
</div>
```

What do you think?

**Comment by MartijnCuppens** [comment]
@Jukien, you should use a button instead of an `<a>` tag if you're handling things with js.

**Comment by Jukien** [comment]
@MartijnCuppens thank you for your answer. A button comes with a different html layout (padding, border, outline).

What I have today (4.5.0):
![image](https://user-images.githubusercontent.com/32452023/89539343-ec555580-d7fb-11ea-9747-f297db82414c.png)


When I replace `<a>` with `<button>`:
![image](https://user-images.githubusercontent.com/32452023/89539261-d8115880-d7fb-11ea-9206-0c9742d403a1.png)


If I use a button link:
![image](https://user-images.githubusercontent.com/32452023/89539190-c0d26b00-d7fb-11ea-8a57-0a64535384ae.png)


It's better but still need to:
- overide the link color (blue) and add some more css to get my `text-muted`
- the button is too big so add `btn-sm` but my icons will shrunk
- add `d-flex align-items-center` to center all elements (title and buttons)

A button isn't as flexible as a link.

**Comment by Jukien** [comment]
@MartijnCuppens thank you for your help. You're right.

**Comment by devoto13** [comment]
> it'd at least fix issues where things overlap with our components.

And break things, where it does not overlap with Bootstrap components.

I really don't understand how it makes sense that:

    <a>Something</a>

and 

    <a class="my-custom-class">Something</a>

Behave differently. It just does not make sense and if the goal was to fix styling of Bootstrap components the fix should have probably been connected to such components classes, not the global reset styles.
