### ISSUE TITLE
Tooltips don't work as expected on Chrome for Android

### ISSUE THREAD

**Issue by carlos-mg89** [twbs/bootstrap#30738]
- Operating system and version: doesn't work on Android 9 and 10, at least
- Browser and version: latest Chrome

It works as expected on Firefox (Windows, Linux and Android) and it works on Chrome for Linux and Windows.

The issue is that I have to do a long tap in order for the tooltip to be shown. If I do a quick tap, as I do in Firefox (Android) it shows the tooltip.

I have checked and the Popper version is 1.16, which was released on November 2019. Perhaps at that time, Chrome for Android worked as expected, and now it doesn't. Haven't tested the Chrome version that was available in November 2019.

Anyone else having this issue?

**Comment by Deckluhm** [comment]
I just checked docs example on Chrome (Android 10) and it works as expected :man_shrugging:

**Comment by carlos-mg89** [comment]
Did the tooltip show up after a quick tap or after a long tap?

Cause I've tested this in 2 different devices and the same happens for both of them.

However, doing some more tests on these Android devices, on Chrome, I visited the bootstrap tooltip page, where there are some examples. And they work as expected (show up after a quick tap on the buttons).

I'm a bit puzzled right now after this test. As I say, this issue only happens on Chrome for Android. Could it be some incompatibility or misbehaviour because of another library¿? My tooltip doesn't have anything fancy. Just a plain text tooltip bound to an img tag.

**Comment by patrickhlauke** [comment]
we can't help you with your specific situation/implementation. if you can isolate a test case that just uses bootstrap and shows the problem - indicating it's a problem with bootstrap - we can investigate. otherwise, suggest you ask for help on StackOverflow or similar... see https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker

**Comment by carlos-mg89** [comment]
Totally. Will come back either with more information, there's definitely something going on that's pretty weird.

Will close this issue for the moment. If needed, I'll reopen it with the details. I definitely thought it was some kind of bug, since this issue just happens on Chrome for Android.
