### ISSUE TITLE
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".

### ISSUE THREAD

**Issue by oivinds** [twbs/bootstrap#30760]
Exerpt from package.json

 "peerDependencies": {
    "jquery": "1.9.1",
    "popper.js": "^1.16.0"
  }

**Comment by XhmikosR** [comment]
Your package.json should have our peerDependencies and dependencies.

**Comment by hiradyazdan** [comment]
@XhmikosR react-bootstrap/react-overlays depends on `@popperjs/core` v2.0.0. May be this is to do with their implementation, but I wonder if bootstrap also upgrades this package it causes breaking changes elsewhere? Those packages already taken the risk if there is one.

**Comment by XhmikosR** [comment]
We won't be updating to popper.js 2.x in v4 because it drops support for some browsers that our v4 supports. For master it's planned as long as someone provides a patch.
