### ISSUE TITLE
Is it possible to add more predetermined colors for custom styles

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#30767]
https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_forms.scss#L143-L148

https://getbootstrap.com/docs/4.4/components/forms/#custom-forms

---

Is it possible to add more predetermined colors for custom styles.

With other colors, the overall collocation of the form will be more coordinated.

**Comment by mdo** [comment]
You're welcome to customize the colors of our form controls, but we won't be providing more options built in as it can interfere with the styles we have for form validation and more (green and red colors).
