### ISSUE TITLE
HTML tooltip broken when it contains tables (4.3)

### ISSUE THREAD

**Issue by tbasallo** [twbs/bootstrap#30764]
Starting 4.3 tables in a tooltip breaks the tooltip. HTML works normally, it's just when adding a table in the tooltip that it breaks.

Repros in jsfiddle:

4.4.1 (broken)
https://jsfiddle.net/tbasallo/y321exf8/3/

4.2.1 (works)
https://jsfiddle.net/tbasallo/vswy0Ln3/1/

I didn't see any breaking changes from 4.3 that would cause them, but...

**Comment by XhmikosR** [comment]
Might be due to the sanitizer. https://getbootstrap.com/docs/4.4/getting-started/javascript/#sanitizer

**Comment by tbasallo** [comment]
Yep. That was it and I didn't truly get the sanitize mentions in the options.

I updated the jsfiddle for others. For example, you have to add all the table components for it to work, not just the table. Which is odd - the table in the example doesn't have a tbody. Not sure if that's by design or not.

**Comment by jt196** [comment]
I managed to get tables working but I had to disable the sanitizer:
```JS
            var tooltip = new Tooltip(myRow, {
                sanitizeFn: function (content) {
                    return content
                 }
            })
```
Which I'm guessing isn't a great idea. The Whitelist by the way, doesn't seem to work. If you add all the table elements in BS 5.0, nothing shows up. 
```
            var myDefaultAllowList = Tooltip.Default.allowList

            // To allow table elements
            myDefaultAllowList.table = []
            myDefaultAllowList.td = []
            myDefaultAllowList.tbody = []
            myDefaultAllowList.tr = []
            myDefaultAllowList.th = []
```
