### ISSUE TITLE
Using tabs into disabled fieldset not working with Firefox

### ISSUE THREAD

**Issue by tflorac** [twbs/bootstrap#30774]
Hi,

I'm creating a form containing a fieldset inside which is a set of tabs.

When the fieldset is disabled (using an associated checkbox), the navigation tabs are still usable to display tabs contents when using Chrome or Chromium, which is the behaviour I'm looking for!

But with Firefox, the tabs are not working: clicking on a tab is just updating the window hash with the ID of the tab specified into tab's link href!

I've tried to add a JQuery listener on tab's click event, but this one doesn't seems to be triggered in Firefox!

So is it a bug ? Or is there any way to have the same behaviour in Firefox as in Chrome?

Best regards,

Thierry

**Comment by patrickhlauke** [comment]
As per the issue template...please provide an isolated reproducible test case example.

**Comment by tflorac** [comment]
OK... should an HTML extract be enough in this use case?

**Comment by mdo** [comment]
The issue template for reporting a bug includes all the details we ask you to provide:

> Before opening:
> 
> - [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
> - [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
> - Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md)
> 
> Bug reports must include:
> 
> - Operating system and version (Windows, macOS, Android, iOS)
> - Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
> - [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
>

**Comment by tflorac** [comment]
Here is a small CodePen sample: https://codepen.io/tflorac/pen/pojKNLW

The problem occurs actually on Windows and Linux with Firefox 68.7.0esr.

**Comment by mdo** [comment]
Per <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset>:

> If this Boolean attribute is set, all form controls that are descendants of the `<fieldset>`, are disabled, meaning they are not editable and won't be submitted along with the `<form>`. They won't receive any browsing events, like mouse clicks or focus-related events. By default browsers display such controls grayed out. Note that form elements inside the `<legend>` element won't be disabled.

**Comment by tflorac** [comment]
Just to be sure to understand correctly, are links (<a> elements) considered as "form controls" as long as they are located inside a fieldset?

**Comment by patrickhlauke** [comment]
I think the issue title caused some confusion there. no, links themselves should not be considered "disabled" inside a disabled fieldset. this may well be a bug in Firefox.

**Comment by tflorac** [comment]
I opened a Firefox bug report for this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1637321
