### ISSUE TITLE
Bootstrap v4.4.1 modal with data-backdrop="static" can't be dismissed via the Escape key.

### ISSUE THREAD

**Issue by vsajip** [twbs/bootstrap#30784]
OS: Ubuntu 18.04
Browser: Firefox 76.0
Demonstration of problem: https://jsfiddle.net/vsajip/pmvtwL27/1/

Even if `data-keyboard="true"`, setting `data-background="static"` prevents closure of the modal via the Escape key. This isn't intuitive, and not documented - the info [here](https://getbootstrap.com/docs/4.0/components/modal/#options) doesn't mention any connection between the `backdrop` and `keyboard` settings.

**Comment by XhmikosR** [comment]
Please try with v4.5.0.

**Comment by vsajip** [comment]
OK, it seems to work on 4.5.0.
