### ISSUE TITLE
v4.5: Missing minified css in dist package

### ISSUE THREAD

**Issue by andig** [twbs/bootstrap#30799]
Not much detail to add here. This is the dist package from the release downloads: 

```
bootstrap-grid.css           bootstrap-grid.min.css       bootstrap-reboot.css         bootstrap-reboot.min.css     bootstrap.css
bootstrap-grid.css.map       bootstrap-grid.min.css.map   bootstrap-reboot.css.map     bootstrap-reboot.min.css.map bootstrap.css.map
```

I had expected the full file in minified version, too.

**Comment by ffoodd** [comment]
It's included, I just double-checked. Did you download [bootstrap-4.5.0-dist.zip](https://github.com/twbs/bootstrap/releases/download/v4.5.0/bootstrap-4.5.0-dist.zip)?

**Comment by andig** [comment]
It is. Sorry for the confusion- not sure what I did there, sorry....
