### ISSUE TITLE
Improving docs search indexing

### ISSUE THREAD

**Issue by calmwater** [twbs/bootstrap#30792]
Starting today I can't search in the bootstrap docs. Searching for "buttons" yields no results.  Looks like a new version of BS and Docs.  Needs a little love.

**Comment by XhmikosR** [comment]
Opened an issue upstream: https://github.com/algolia/docsearch-configs/issues/1951

**Comment by mdo** [comment]
Search is working again in v4.5 and according to the upstream issue they're working on making it on-demand. Up to @XhmikosR if we leave this open to track that.

**Comment by XhmikosR** [comment]
Indeed, they fixed it quickly last night. I'll keep an eye on it.
