### ISSUE TITLE
This fix brokes border between card-header and list-group, it's doubled in 4.5.0.

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#30793]
This fix brokes border between card-header and list-group, it's doubled in 4.5.
See diffierence...
https://getbootstrap.com/docs/4.4/components/card/#list-groups
https://getbootstrap.com/docs/4.5/components/card/#list-groups

_Originally posted by @waclaw66 in https://github.com/twbs/bootstrap/pull/30497#issuecomment-627523760_

**Comment by mdo** [comment]
> We need to check if master is affected too.

Confirmed, PR opened.

**Comment by tveimo** [comment]
I think this regression is also for a card-footer following a list-group. Adding to the patch above, this seems to work:

.card {
[...]
 > .list-group + .card-footer {
    border-top: 0;
  }
}

But I'm unsure if this is the correct fix.
