### ISSUE TITLE
Extend/Icons Docs

### ISSUE THREAD

**Issue by asportnoy** [twbs/bootstrap#30796]
[This page](https://getbootstrap.com/docs/4.5/extend/icons/) should have information about the new Bootstrap Icons in v4.5.

**Comment by mdo** [comment]
We're nuking that page in v5 so I don't think it makes sense to add much to that page except maybe a mention of the icons project. It's still technically in alpha as well.

**Comment by mdo** [comment]
Thoughts @twbs/css-review?

**Comment by XhmikosR** [comment]
I guess we should mention Bootstrap Icons indeed.

**Comment by mdo** [comment]
Closing per merged PR.
