### ISSUE TITLE
Form input rendering issue after upgrading to version 4.5.0 and purging with PurgeCSS 

### ISSUE THREAD

**Issue by bluesurfer** [twbs/bootstrap#30802]
I have just updated to Bootstrap 4.5.0. Everything works fine but when using it with PurgeCSS (v. 2.2.0) I got strange rendering issues:
<img width="101" alt="Untitled2" src="https://user-images.githubusercontent.com/4722772/81825761-4f09be80-9537-11ea-9b6e-cf28e7697d54.png">
<img width="41" alt="Untitled" src="https://user-images.githubusercontent.com/4722772/81825766-503aeb80-9537-11ea-88ab-4f532fafa79c.png">

Consider that nothing breaks on 4.4.1.

**Comment by mdo** [comment]
This is a tough one since we don't officially provide PurgeCSS support, and I don't believe our custom forms have changed much between v4.4.1 and v4.5.0. Anything stick out to you here? https://github.com/twbs/bootstrap/compare/v4.4.1...v4.5.0

Perhaps there's something to adjust on PurgeCSS's options?

**Comment by bluesurfer** [comment]
Mmm.. It looks like the problem is PurgeCSS version > 1.3.0. Downgrading to 1.3.0 fix my problems. I have mistakenly blame Bootstrap 4.5.0. Sorry for that :)

For the record I'll post my `postcss.config.js` (pretty simple):

```
const purgecss = require('@fullhuman/postcss-purgecss')({
    content: [
        './**/*.html',
    ],
    keyframes: true,
    whitelistPatterns: [
        /popover/,
        /tooltip/,
        /modal/,
        /fade/,
        /show/,
        /hide/,
        /alert/,
    ],
});

const cssnano = require('cssnano')({
    preset: ['default', {
        discardComments: {
            removeAll: true
        },
    }],
});


module.exports = {
    plugins: [
        require('autoprefixer')(),
        ...process.env.NODE_ENV === 'production'
            ? [cssnano, purgecss]
            : []
    ]
};

```
