### ISSUE TITLE
When included in navbar and actived, dropdown-toggle have a border in Firefox 76

### ISSUE THREAD

**Issue by eldk** [twbs/bootstrap#30801]
Hello,

- Ubuntu 16.04
- Firefox 76 (64 bits)
- Bootstrap V5-alpha1
- example page (Boostrap example page, Never Expand) : http://localhost:9001/docs/5.0/examples/navbars/#

When included in navbar and actived, dropdown-toggle have a border in Firefox 76 : 

![navbar_dropdown_firefox_76](https://user-images.githubusercontent.com/11083657/81819140-35647900-952f-11ea-9f66-33d9116b3549.png)

Whereas no borders in chrome 81, Chromium, Firefox Klar ...  (that is expected I think) :

![navbar_dropdown_chrome_81](https://user-images.githubusercontent.com/11083657/81819492-ac9a0d00-952f-11ea-8c05-f6d2e90c4723.png)

Thanks,

Eric

**Comment by mdo** [comment]
This is Firefox's focus style and isn't a bug as far as I know. Firefox has an odd focus style unfortunately.

> * Bootstrap V5-alpha1

There's also no v5 release yet. 😁

**Comment by eldk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=140562
