### ISSUE TITLE
docs v5: switch to ES6

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#30818]
[Hugo v0.70.0](https://github.com/gohugoio/hugo/releases/tag/v0.70.0) introduced the ability to use [Babel](https://gohugo.io/hugo-pipes/babel/), which means we can finally use ES6 everywhere in the codebase for v5.

There's still a bug that needs to be fixed, but should only affect Windows: <https://github.com/gohugoio/hugo/issues/7251>

**Comment by developerhb** [comment]
Hello @XhmikosR I would like to start contributing to Bootstrap. I went through the Contributing Guidelines and found that for issues with label `help wanted` you would love to get help from community. 

I would like to contribute in this issue.

To better understand issue, I would like to have more insights of the issue.

**Comment by Bam92** [comment]
I was about to open such an issue, but I found this to be very similar to mine.

I've read the source code for `bootstrap.js` and I've noticed that you're still using an old fashioned JS style. So, I wish I helped to start the migration to  ES6+. I've seen that there's a  PR, but for the doc only. I wish I helped w/ `bootstrap.js`. Any comment?
