### ISSUE TITLE
.user-select In the case of DOM attribute inheritance

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#30826]
[DEMO](https://codepen.io/zhangchenglin/pen/eYpLZoe)

The above is the effect of the current CSS sequence.

In a multi-level DOM, such as the case where the entire document is prohibited from selecting, all and auto can no longer be combined. Inline styles should work. Should classes without \"! Important\" be added?

**Comment by zhangchenglin** [comment]
Nice to see 4.5.0

**Comment by mdo** [comment]
I don't think there's anything we'd change here—nearly all our utilities use this approach and _could_ have similar issues of one class coming before the other. I also think this issue would exist outside our utilities if you used the property-values in custom CSS yourself.

Feel free to re-open and gut check me on that though, @twbs/css-review.
