### ISSUE TITLE
Search is not working on Bootstrap 4.3.1 documentation

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/bootstrap#30820]
Search is not working on Bootstrap 4.3.1 documentation
Windows 10
Chrome 81
Anything i searches it does says "ABC" is not found etc.

https://getbootstrap.com/docs/4.3/components/modal/

**Comment by XhmikosR** [comment]
https://github.com/algolia/docsearch-configs/issues/1951#issuecomment-628585979

**Comment by XhmikosR** [comment]
Should be fixed now.
