### ISSUE TITLE
Active Breadcrumb icon

### ISSUE THREAD

**Issue by Oznogco** [twbs/bootstrap#30825]
Hi,

Génial, a new version of Bootstrap is always good news, especially when it comes to a bridge to version 5!

I changed the version in my development and everything seems perfect. Apart from a small detail, the  icon into active breadcrumb element (not the separator). It works in a link but not in the active element,

Of course we can add an alignment (my-auto), but it seems to me that it should be automatic,

```
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#"><i class="fas fa-user-plus"></i> Good</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user-plus"></i> Not good</li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user-plus my-auto"></i> Good but...</li>
  </ol>
</nav>
```

Tx, nice job...

**Comment by mdo** [comment]
Bootstrap doesn't do anything with Font Awesome icons, and without a live demo, we can't help much here.

**Comment by Oznogco** [comment]
Wow, sorry man, It's was just for help !
It's the last email à send about Bootstrap you be sure !

Sorry again !
Coock-a-doodle Doo !
________________________________
De : Mark Otto <notifications@github.com>
Envoyé : 14 mai 2020 12:31
À : twbs/bootstrap <bootstrap@noreply.github.com>
Cc : Oznogco <oznog@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [twbs/bootstrap] Active Breadcrumb icon (#30825)


Bootstrap doesn't do anything with Font Awesome icons, and without a live demo, we can't help much here.

**Comment by mdo** [comment]
There as no negativity or anything in my comment :). Our issue templates clearly state how best to get help here, though. When folks skip steps, we and others tend to either ignore or close until more details and a test case are provided.

If you still need help, please reread the issue templates and provide a live demo and more details. We’ll happily reopen.
