### ISSUE TITLE
Toast background filter blur rendering issue in Safari

### ISSUE THREAD

**Issue by Katrienvh** [twbs/bootstrap#30844]
Rendering issue toast in safari only visible when there's an image behind the toast.

The background blur is broken at the left side of the toast. When you don't use a header, it's also broken at the top. 
![image](https://user-images.githubusercontent.com/12270833/82203834-22252500-9904-11ea-8244-3b761882d714.png)

I also found out, that when you remove the box-shadow of the toast, the issues disappears. As a box shadow for a toast is a must in my eyes, this is not a solution.

I made a codepen to as example: https://codepen.io/katrienvh/pen/JjYebmy

- Operating system and version: macOS Catalina version 10.15.4
- Browser and version: Safari version 13.1

**Comment by mdo** [comment]
Yeah, I've been noticing some issues in Safari with this CSS in a few locations. Will look into it further to see if there's a fix, and if not, I'll likely just remove it.
