### ISSUE TITLE
No scss variable to change color for a .nav-item inside a .nav

### ISSUE THREAD

**Issue by thebspin** [twbs/bootstrap#30847]
- Windows 10
- Chrome  81.0.4044.138
- Bootstrap 4.7.0

After fiddeling around with a vertical nav, i found out there is no scss variable to change the color of these. There is `$link-color` but that changes all the links. I expected there to be a `$nav-color` or something. A nav is different than a navbar, and also different than just normal links. So should there be a scss variable to change the color, hover etc for an a href inside `.nav-item` thats inside `.nav`

**Comment by Tmajor97** [comment]
i also noticed the same but i'll do further research to see if there any other alternative

**Comment by thebspin** [comment]
> i also noticed the same but i'll do further research to see if there any other alternative

Well you could make your own scss variable and use that with some css classes to overwrite it. But in my opinion it should be part of the framework!
