### ISSUE TITLE
Simultaneous table-striped and table-hover aren't different enough

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#30853]
Having a table with both ```table-striped table-hover```

The hover color is almost the same as one of the stripe colors (darker one). 
Could these please be more different, so it's more clear when one hovers over a row with that stripe color?

Thanks

(could be changed in v5 only)

**Comment by mdo** [comment]
This is fixed in v5, yes. First alpha for that drops soon.

**Comment by vanillajonathan** [comment]
@mdo, was it fixed? Where is the commit that fixes this?
It doesn't *look* fixed.
It kind of looks same like as in Bootstrap 4, not much different.

Bootstrap 4.6.0
https://jsfiddle.net/jnLpucxq/

Bootstrap 5.0.0-beta2
https://jsfiddle.net/8pk3robq/
