### ISSUE TITLE
Not required inputs should not be affected by the class ".was-validated"

### ISSUE THREAD

**Issue by maikycourse** [twbs/bootstrap#30865]
line: 33
`.was-validated #{if(&, "&", "")}[required]:#{$state},`
I have added "[required]" to prevent it from affecting inputs that are not required. 

I think the code that is generated by adding "[required]" is more appropriate.
I would like you to take it into account in future versions.
Thanks.

**Comment by mdo** [comment]
This has been discussed in other issues and we won't be going this route at this time. Thanks though!
