### ISSUE TITLE
Nested Tables Getting Striped

### ISSUE THREAD

**Issue by wilecoyte78** [twbs/bootstrap#30869]
I would like to not have nested tables to get the parent tables classes imposed on them.

In this example The table looks like this [http://x-v.it/0q782g](http://x-v.it/0q782g)
`
<div class="table-responsive">
	<table class="table table-striped learnworlds" data-new-id-ceiling="99999999">
		<thead class="thead-dark">
			<tr>
				<th style="width: 45%">Inventory Item</th>
				<th style="width: 45%">Course</th>
				<th style="width: 10%">Delete</th>
			</tr>
		</thead>
		<tbody>
			<tr id="learnworlds_start_4">
				<td colspan="3">
					<div class="table-responsive">
						<table class="table">
							<tbody><tr>
								<td style="width: 45%">One Time Purchase</td>
								<td colspan="2"><button class="btn btn-secondary add_lwcourse" data-stockid="4"><i class="freycon freycon-plus-circle"></i> <span>Add Course</span></button></td>
							</tr>
							<tr class="learnworlds_row" id="learnworlds_row_100000000" data-lwid="100000000">
								<td style="width: 45%">&nbsp;</td>
								<td style="width: 45%">
								</td>
								<td class="text-center" style="width: 10%">
								</td>
							</tr>
							<tr class="learnworlds_row" id="learnworlds_row_100000001" data-lwid="100000001">
								<td style="width: 45%">&nbsp;</td>
								<td style="width: 45%">
								</td>
								<td class="text-center" style="width: 10%">
								</td>
							</tr>
						</tbody></table>
					</div>
				</td>
			</tr>
			<tr id="learnworlds_start_5">
				<td colspan="3">
					<div class="table-responsive">
						<table class="table">
							<tbody><tr>
								<td style="width: 45%">6 Monthly Payments</td>
								<td colspan="2"><button class="btn btn-secondary add_lwcourse" data-stockid="5"><i class="freycon freycon-plus-circle"></i> <span>Add Course</span></button></td>
							</tr>
						</tbody></table>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>
`

When I change the _table.scss

From

`
.table-striped {
  tbody tr:nth-of-type(#{$table-striped-order}) {
    background-color: $table-accent-bg;
  }
}
`

To:

`
    .table-striped {
      > tbody > tr:nth-of-type(#{$table-striped-order}) {
      background-color: $table-accent-bg;
     }
    }
`

It looks like this [http://x-v.it/w84n57](http://x-v.it/w84n57)

We should always only make the children of parents not inherit their parent's classes

**Comment by mdo** [comment]
Nested tables inherit styles in v4. This cannot change because of backward compatibility, but we are changing this in v5.
