### ISSUE TITLE
Docs : Examples : Blog : blog-sidebar is not used or set

### ISSUE THREAD

**Issue by eldk** [twbs/bootstrap#30878]
Hello,

https://github.com/twbs/bootstrap/blob/c9cd3e4a083a69bcd2eefb1d1b62e6106e2ce469/site/content/docs/5.0/examples/blog/index.html#L158

blog-sidebar class is not set in https://github.com/twbs/bootstrap/blob/master/site/content/docs/5.0/examples/blog/blog.css nor in site/content/docs/5.0/examples/blog/index.html .

So not used :  not needed or missing.

Thanks,

Eric

Same with blog-main : https://github.com/twbs/bootstrap/blob/c9cd3e4a083a69bcd2eefb1d1b62e6106e2ce469/site/content/docs/5.0/examples/blog/index.html#L87

**Comment by XhmikosR** [comment]
You can ignore those, they are probably leftovers from refactoring on master. PRs welcome.
