### ISSUE TITLE
Documentation is unclear what data-toggle"collapse" and data-toggle="false"

### ISSUE THREAD

**Issue by bholtbholt** [twbs/bootstrap#30877]
![Screen Shot 2020-05-21 at 3 01 57 PM](https://user-images.githubusercontent.com/4933622/82563241-fa89c300-9b76-11ea-943b-28e4e59b9b97.png)

The [documentation in Collapse Options](https://getbootstrap.com/docs/4.5/components/collapse/#options) is unclear. It says options can be passed in with data attributes and lists `toggle` as an option, but I can't have two `data-toggle` attributes, and `data-toggle` doesn't appear to take multiple arguments.

The documentation suggests this will work (reduced options for clarity):
```html
<button data-toggle="collapse false" data-target="#collapseExample">
  No collapse toggle
</button>

<button data-toggle="collapse" data-toggle="false" data-target="#collapseExample">
  No collapse toggle
</button>
```

But neither do. The first doesn't trigger any collapse functionality and the second is invalid HTML.

### Expectations
I expect `data-toggle="collapse false"` will trigger collapse one time in one direction, rather than toggle back and forth. It should function the same as `.collapse('show')` or `.collapse('hide')`, and show/hide depends on the target element.

### Suggestion:
- Update the documentation to explicitly state `data-toggle` won't work and can only be passed as an option with JavaScript
- Update the plugin to take `data-toggle="collapse false"` or `data-toggle-state="false"` options

### Reproduction
- Create an collapse element with `data-toggle="collapse false"`
- Collapse no longer works for that element

**Comment by mdo** [comment]
Look to the examples in the docs for how these attributes work: https://getbootstrap.com/docs/4.5/components/collapse/#example.

`data-toggle` is a convention we have across the project—included in collapse and dropdowns at least. It's not the same as `show`/`hide` and there's currently no data attributes for those two methods. There are JS methods though for you: https://getbootstrap.com/docs/4.5/components/collapse/#methods.

Not sure there's something we'd change here. Thoughts @twbs/js-review?

**Comment by mdo** [comment]
Closing as stale. Happy to see more suggestions or PRs to improve things though.
