### ISSUE TITLE
Modal and Tooltip cannot coexist

### ISSUE THREAD

**Issue by JIMhackKING** [twbs/bootstrap#30881]
Bootstrap version: 4.4.1
Operation System: Windows
Browser: Chrome

When importing bootstrap.min.js first and then bootstrap.bundle.min.js, the tooltip runs normally and the modal displays only the mask but not the div. When first importing bootstrap.bundle.min.js and then importing bootstrap.min.js, the modal runs normally, but the tooltip is not displayed (the tooltip div is rendered).

The modal's html:

```html
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
...
</div>
```

The tooltip's html:

```html
<a href="#" id="custom-paragraph-btn" class="dropdown-item" data-toggle="tooltip"
                            data-placement="right" title="xxxxx">
xxx
</a>
```

And I found it the cause of this problem is that when the action is triggered, the 'show' class is not added to the DOM, normally it should be `<div class="modal fade show" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">`(take modal as an example), I haven't call any javascript of modal(the documentation does not state that this is needed)

### Snipshot

tootip normally:

Import js file
![Import js file](https://user-images.githubusercontent.com/23214854/82704289-cb26a380-9ca7-11ea-8ffa-645f2e1a5b51.png)

button
![button](https://user-images.githubusercontent.com/23214854/82704398-01fcb980-9ca8-11ea-9266-981c57a7cb19.png)

modal
![modal](https://user-images.githubusercontent.com/23214854/82704434-15a82000-9ca8-11ea-92a2-78f4fa450be4.png)

after click
![image](https://user-images.githubusercontent.com/23214854/82704807-ef36b480-9ca8-11ea-9c4a-af3556db3286.png)

![image](https://user-images.githubusercontent.com/23214854/82704579-7172a900-9ca8-11ea-8b1e-f1674f84aa01.png)

These phenomena are reversed when the modal is normal

(Because my English is not very good, this text was translated by Google, sorry)

**Comment by asyncdesign** [comment]
Why do you include the bootstrap.bundle.min.js and also include bootstrap.min.js and jquery separately? The bootstrap.bundle.min.js file should have all that you need. Alternatively, you could just include bootstrap.min.js and jquery, but you might want to include popper also in this case.

**Comment by XhmikosR** [comment]
Yeah, what @asyncdesign said above :)

You should only include the bundle **OR** bootstrap.min.js + popper.min.js.
