### ISSUE TITLE
.nav-item is not required on .nav-link inside .navbar-nav

### ISSUE THREAD

**Issue by rohit2sharma95** [twbs/bootstrap#30880]
When list-based approach is not used for the navbar, class `.nav-item` is not required on `.nav-link` inside `.navbar-nav`. Link for the [docs](https://getbootstrap.com/docs/4.5/components/navbar/#nav).

See [this comment](https://github.com/twbs/bootstrap/issues/28423#issuecomment-630286599) in #28423

**Comment by XhmikosR** [comment]
Not sure what you mean by this issue? Is it a documentation issue?

**Comment by rohit2sharma95** [comment]
Yup @XhmikosR. I mean docs should be updated and `.nav-item` class should be removed from `.nav-link`. (Only when the list-based approach is not used for the navbar)

**Comment by XhmikosR** [comment]
Fixed in #30973.
