### ISSUE TITLE
Update jQuery 3.5.0 to 3.5.1

### ISSUE THREAD

**Issue by forghan89** [twbs/bootstrap#30895]
jQuery 3.5.1 Released

please update jQuery 3.5.0 to jQuery 3.5.1 for v4.x-next
- [Changes log in jQuery 3.5.1](http://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/)

**Comment by knoobie** [comment]
Bootstrap 4.5.0 already uses jQuery 3.5.1.
