### ISSUE TITLE
Bootstrap or browser(s) bug ? modal close button with frame ? 

### ISSUE THREAD

**Issue by wwwfactory** [twbs/bootstrap#30916]
go to Bootstrap page : 
https://getbootstrap.com/docs/4.0/components/modal/

Then click on sample modal dismiss button (right upper corner). See the frame around ? Wasn't there two days ago. 
it is in Chome  83.0.4103.61 Win7 64, new Edge based on chromium engine,  Chrome 75.
When set css element from 
pointer-events:auto 
to 
pointer-events: none

frame gone, but loose some visual behaviour.

regards.

**Comment by XhmikosR** [comment]
v4.0 is ancient. https://getbootstrap.com/docs/4.5/components/modal/

**Comment by wwwfactory** [comment]
Someone post  one miniute ago that v4.0 is ancient
well,
in 4.5 same behaviour....
https://getbootstrap.com/docs/4.5/components/modal/


regards
