### ISSUE TITLE
Bootstrap 4.5 or browser(s) bug ? modal close button with frame ?

### ISSUE THREAD

**Issue by wwwfactory** [twbs/bootstrap#30917]
go to Bootstrap page :

https://getbootstrap.com/docs/4.5/components/modal/
https://getbootstrap.com/docs/4.0/components/modal/

Then click on sample modal dismiss button (right upper corner). See the frame around ? 
**Wasn't there two days ago.**

it is in 
Chome 83.0.4103.61 Win7 64, 
new Edge based on chromium engine, 
latest Firefox 75.

When set css element from
pointer-events:auto
to
pointer-events: none

frame gone, but loose some visual behaviour.

regards.

@XhmikosR, next time check before You close an issue. I Know what ama writing. This problem is new.

**Comment by XhmikosR** [comment]
I can only check what info you provide. You provided the wrong info in #30916.

**Comment by ffoodd** [comment]
@wwwfactory are you talking about the `outline`, like in this screenshot (Firefox)?

![Screenshot_2020-05-28 Modal](https://user-images.githubusercontent.com/2890570/83113256-b131fa00-a0c7-11ea-926e-ff07e1cd648a.png)

If so, it's been here for years. And at least, since v4.0 (which we didn't released again, obviously). Moreover, it's not an issue: it's meant indicate `:focus`ed state.

If not, could you please provide screenshot of what you're considering a bug?

**Comment by patrickhlauke** [comment]
chrome made their focus outline stronger in the latest release. the focus outline has always been on those "X" close buttons. nothing new here.

**Comment by alecpl** [comment]
The button could be re-sized/moved so the outline rectangle does not look misplaced. What do you think? I.e. make the button height to use full height of the dialog header or add the same margin on top,right and bottom.

**Comment by TammyCT** [comment]
> @wwwfactory are you talking about the `outline`, like in this screenshot (Firefox)?
> 
> ![Screenshot_2020-05-28 Modal](https://user-images.githubusercontent.com/2890570/83113256-b131fa00-a0c7-11ea-926e-ff07e1cd648a.png)
> 
> If so, it's been here for years. And at least, since v4.0 (which we didn't released again, obviously). Moreover, it's not an issue: it's meant indicate `:focus`ed state.
> 
> If not, could you please provide screenshot of what you're considering a bug?

Could you have any idea how to remove the outline when i focus on certain component, beacuse I fond it not only show ontline in button , it also will show in grid cell and input field etc. I want to remove this black frame when i focus on the compnents globally.

**Comment by caseyjhol** [comment]
Are you referring to the changes Chrome 83 made to form controls?

https://developers.google.com/web/updates/2020/05/nic83#forms

![image](https://user-images.githubusercontent.com/2874325/84085541-0a8d0980-a9a3-11ea-94bc-49525b49036a.png)
