### ISSUE TITLE
Some versions of Bootstrap have some classes and some others don't ( including latest 4.5 )

### ISSUE THREAD

**Issue by oscl** [twbs/bootstrap#30919]
What is going on with different versions of Bootstrap ? Bootstrap 4.3.1 have sidebar and 4.5 doesn't. I've been trying to find out this from a lot of articles but I saw this change in nowhere. Plz reply, is sidebar a bad component to be removed from the latest version ?
Then why ? if you had missed to the class to add, please fix it

**Comment by mdo** [comment]
No features have been removed from v4.5—that'd be a breaking change. Some features have been removed or renamed in v5 though as it's a major release with intentional changes.
