### ISSUE TITLE
Switch button firing change event 3 times in BS 4.5.0

### ISSUE THREAD

**Issue by dkwebtec** [twbs/bootstrap#30924]
I have tried this issue under version 4.5.0 and the method seems working but the change event is fired 3 times on each button click

[https://codepen.io/DK568/pen/MWYxWMO](https://codepen.io/DK568/pen/MWYxWMO)

try to click the button

_Originally posted by @dkwebtec in https://github.com/twbs/bootstrap/issues/30077#issuecomment-636015174_

**Comment by XhmikosR** [comment]
@Lausselloic is this the same issue as #30849?

**Comment by Lausselloic** [comment]
it's not the same issue but yes event is propagate to childrens inside the label. I could give a try to handle that

**Comment by mdo** [comment]
#31000 targets `v4-dev`, but what about this change in v5?

**Comment by XhmikosR** [comment]
@Lausselloic can you confirm please that this issue does not affect v5? I believe we removed most of the Button JS so this doesn't seem to apply to v5.

**Comment by Lausselloic** [comment]
Sorry for the late reply, that doesn't affect v5 at time, there's a need to backport @patrickhlauke fixes (https://github.com/twbs/bootstrap/pull/28952 and https://github.com/twbs/bootstrap/pull/28834) those accessibility fixes are not present's in v5 I will give a try to port it

**Comment by XhmikosR** [comment]
Fixed by #31000, thanks @Lausselloic!
