### ISSUE TITLE
Bootstrap 4.5.0 modal "keyboard: false" don't work

### ISSUE THREAD

**Issue by GuxMartin** [twbs/bootstrap#30929]
- Operating system: Ubuntu 20.04
- Browsers: Chrome 83.0.4103.61, Firefox 76.0.1
- Bootstrap version: 4.5.0

https://jsfiddle.net/4sujahx5/

**Comment by zdroid** [comment]
I am strongly convinced you are missing `data-backdrop="static"` in your `.modal` div.

**Comment by zdroid** [comment]
The docs say Escape won't close the modal if the modal is static.

**Comment by GuxMartin** [comment]
In version 4.4.1 "keyboard: false" works fine without data-backdrop="static"

https://jsfiddle.net/q23up7n8/

**Comment by XhmikosR** [comment]
@Johann-S I guess this is the intended behavior, right?

**Comment by rohit2sharma95** [comment]
This issue is with v5 also @XhmikosR
https://codepen.io/rohit2sharma95/pen/XWKQmYj
