### ISSUE TITLE
input-group-sm with select.form-control display issue in Chrome

### ISSUE THREAD

**Issue by johnaau** [twbs/bootstrap#30921]
On input-group with input-group-sm for the smaller size, a strange border is showing in Chrome. Other browsers are okay.

Failed with Chrome Version 83.0.4103.61 (Official Build) (64-bit).

Sample markup:

```html
<div class="input-group input-group-sm">
    <input name="for" class="form-control" type="text" placeholder="Search for">
    <select name="type" class="form-control">
        <option value=""></option>
    </select>
    <span class="input-group-append">
        <button class="btn btn-light" type="submit">Search</button>
    </span>
</div>
````

Sample screen capture of issue:

![Capture](https://user-images.githubusercontent.com/6590573/83222741-6e058300-a1bc-11ea-9528-d577790292a1.JPG)

**Comment by ffoodd** [comment]
I made a [reduced test case on CodePen](https://codepen.io/ffoodd/full/MWaMdmb) without noticing any issue with Chrome 83.

Don't you have any custom style applying here?

**Comment by mdo** [comment]
Closing as stale. Please comment or open an new issue once confirmed with a reduced test case.

**Comment by johnaau** [comment]
Sorry, I forgot about this. Just did some further testing and found it only happens inside a navbar.

Codepen sample: https://codepen.io/johnaau/pen/NWxRwgj

![Capture](https://user-images.githubusercontent.com/6590573/84730681-3bd88b80-afda-11ea-8d22-4c86bbe68ffe.JPG)

If I remove the navbar-brand DIV or the BUTTON then the SELECT looks correct.

Reproduced with Bootstrap 4.5.0 from CDN, no changes or extra CSS.

**Comment by bharatmakvana** [comment]
Hello @mdo  & @XhmikosR  & @ffoodd 

I have checked code on provided codepen https://codepen.io/ffoodd/full/MWaMdmb and found that the

 `background-clip: padding-box;` 

property of form-control class causes  of this issue. 

**Before Screenshot:**

![backgound-clip](https://user-images.githubusercontent.com/23608908/101240922-3dd8f880-36a7-11eb-948b-471d254f7a25.jpg)

**After Screenshot with fixed issue** 

![backgound-clip-border-box](https://user-images.githubusercontent.com/23608908/101240980-82fd2a80-36a7-11eb-8ea8-f8a540b2f6f6.jpg)

Can I change the background-clip: padding-box to borer-box on .form-control class. 

Please provide your valuable feedback.

Thanks!

**Comment by johnaau** [comment]
@bharatmakvana, your fix works for me and the issue I was seeing in navbars.

**Comment by mdo** [comment]
Regular select menus aren't supported in our input groups, but custom ones are. https://codepen.io/emdeoh/pen/dypgmGp

https://getbootstrap.com/docs/4.5/components/input-group/#custom-forms
