### ISSUE TITLE
Bootstrap 4.5 Scrollspy does not update proper active link when page refresh

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#30933]
I was use Scrollspy with below smooth scrolling function and It working fine with in **Bootstrap 4.4**.

But, Does not proper update active link when page refresh with **Bootstrap 4.5**. It does working fine first time on page load. but, after refresh page. it does not work proper.

What should i do?

```
$('.navbar li a').on('click', function(event) {
	event.preventDefault();
    var sectionTo = $(this).attr('href');
	$('html, body').animate({
      scrollTop: $(sectionTo).offset().top - 50}, 1500, 'easeInOutExpo'
	);
});
```

**Comment by mattbag** [comment]
Works for me, review your function and try to go backwards

**Comment by harnishdesign** [comment]
Please check this live demo here: http://demo.harnishdesign.net/test/
Does update proper navigation active link when first time on page load. but, after page refresh page. it does not work proper. 

Please try below steps in my demo. You will realize. what happen there.

- First Open my demo. then, You can testing. It will working fine.

- then, Go to Contact section and **then page refresh.**

- then, click on another section link(about, services, etc...) from navigation. So, You can realize. does not update active link in navigation. Which you have click on section.

Here, I am not understand. why this happens. It is working fine with bootstrap 4.4.

**Comment by XhmikosR** [comment]
We need a simpler codepen example. You have so much JS that I can't tell if something is causing your issue.

**Comment by harnishdesign** [comment]
I realized that, I was accidentally implement Bootstrap v5.0.0-alpha1. It is working fine with v4.5. Thanks.
