### ISSUE TITLE
Formatting for $sizes sass map

### ISSUE THREAD

**Issue by tez123z** [twbs/bootstrap#30961]
Hey guys i've been looking for the formatting of the $sizes sass map used for width and height relative sizing https://getbootstrap.com/docs/4.5/utilities/sizing/#relative-to-the-parent. Is there supposed to be one in _variables.scss ? Am I way off base?

**Comment by Hiws** [comment]
Looks like it has been removed from the master branch.
But if you look at `v4.5.0` it's there.

https://github.com/twbs/bootstrap/blob/7a6da5e3e7ad7c749dde806546a35d4d4259d965/scss/_variables.scss#L155-L166

**Comment by ffoodd** [comment]
I think you searched on the `master` branch, which is v5. The doc (and latest release) is v4, on the `v4-dev` branch: [here's the `$sizes` map](https://github.com/twbs/bootstrap/blob/4e685e70b7a042ebf266e4475013291c0c3fb500/scss/_variables.scss#L154).

If this is what you were looking for, please close this issue :)

**Comment by tez123z** [comment]
Thanks!
