### ISSUE TITLE
add .text-xs-center .text-xs-left .text-xs-right

### ISSUE THREAD

**Issue by hxtree** [twbs/bootstrap#30968]
There are no xs options for text alignment which causes text to default to the wrong alignment when moving from sm to xs.  Please add the following:
```
.text-xs-center {}
.text-xs-left {}
.text-xs-right {}
```

**Comment by mdo** [comment]
`.text-center`, `.text-left`, and `.text-right` are the classes to use. All `xs` breakpoint classes have no infix/breakpoint.

**Comment by hxtree** [comment]
@mdo, thank you.
