### ISSUE TITLE
Rename class .input-group-text

### ISSUE THREAD

**Issue by rohit2sharma95** [twbs/bootstrap#30967]
`.input-group-text` does not contain text only, it contains form elements as well. It would be good if this class name is changed to the appropriate one.

```html
<div class="input-group mb-3">
  <div class="input-group-text">
    <input class="form-check-input" type="checkbox" value="" aria-label="Checkbox for following text input">
  </div>
  <input type="text" class="form-control" aria-label="Text input with checkbox">
</div>

<div class="input-group">
  <div class="input-group-text">
    <input class="form-check-input" type="radio" value="" aria-label="Radio button for following text input">
  </div>
  <input type="text" class="form-control" aria-label="Text input with radio button">
</div>
```

**Comment by mdo** [comment]
Agreed it could be renamed, but we'll skip this for v5 given how close we are to the alpha and that we'd like to keep things as easily upgradable as possible. Thanks!

**Comment by zhangchenglin** [comment]
Personal opinion, regardless of the meaning of the name, in v4 and v5, the same class name, but the purpose is completely different, will it cause trouble to people?

Now that the changes have been made here, why not do it in one step and it is still alpha1
