### ISSUE TITLE
Revisit floating example for IE/Edge

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#30964]
About the floating labels example, I'm a bit confused: there's an old patch for IE that seems to… break the example.

If I remove it, the example works fine in IE11 (tested on BrowserStack, W7 & W10). 
However the Edge patch seems required. Both were introduced in #25919, but [MDN compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown#Browser_compatibility) seems clear: IE10 & 11 did support their vendor version.

I'd be in favor of removing it (but should probably be another PR, souldn't it?).

_Originally posted by @ffoodd in https://github.com/twbs/bootstrap/pull/30836#issuecomment-638711684_

**Comment by XhmikosR** [comment]
I haven't checked master BTW.

**Comment by ffoodd** [comment]
I made 2 PRs:
- Improve the Edge fallback, affects both v5 and v4 (should be backported, #30966 )
- Remove the IE fallback, affects only v4 (#30965 )
