### ISSUE TITLE
Use scrollspy on docs pages

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#30977]
On the docs pages, the sidebar on the right side of the page should use scrollspy.

**Comment by pcmourya** [comment]
Hello sir,
I'm just a beginner and I want to resolve this issue. May I take this.

Thanks

**Comment by techboyg5** [comment]
> Hello sir,
> I'm just a beginner and I want to resolve this issue. May I take this.
> 
> Thanks

Sure.Add [this](https://getbootstrap.com/docs/4.5/components/scrollspy/) functionality to the sidebar on the right of the docs pages.

**Comment by ffoodd** [comment]
@pcmourya Sure, feel free to open a PR :)

**Comment by techboyg5** [comment]
> Hello sir,
> I'm just a beginner and I want to resolve this issue. May I take this.
> 
> Thanks

For reference purposes, [here is the docs for the scrollspy component](https://getbootstrap.com/docs/4.5/components/scrollspy/).

**Comment by raina02** [comment]
I would like to work on it.

**Comment by ffoodd** [comment]
@raina02 feel free to open a PR :)

**Comment by RHSebregts** [comment]
Hi, so are PR's still welcome for this? If so, I'd gladly see what I can do!

**Comment by techboyg5** [comment]
> 
> 
> Hi, so are PR's still welcome for this? If so, I'd gladly see what I can do!

Feel free to!

**Comment by XhmikosR** [comment]
IIRC the problem is that we can't customize the ToC markup. Might be worth making an upstream FR in the Hugo repo.

I definitely think this would be a nice addition.

**Comment by sdkdeepa** [comment]
Hello! I would like to contribute to this as it is still open. Please let me know
