### ISSUE TITLE
v4.0.0-alpha.6 -  Does not close when using a dropdown in modal when using Safari browser

### ISSUE THREAD

**Issue by jiniC** [twbs/bootstrap#30978]
In version [4.0.0-alpha.6](https://v4-alpha.getbootstrap.com/ ) there is an error when using a dropdown component inside a modal.
Opening a dropdown once and then clicking it again to close will not close it.

Deleting the tabindex -1 attribute in the modal area works fine.
However, it should still work properly even when the tabindex -1 attribute is maintained.
The bootstrap user guide also provides a tabindex -1 attribute in the modal area.
: https://v4-alpha.getbootstrap.com/components/modal/#live-demo

- macOS / Safari
- code: https://codepen.io/jiniC/pen/MWKawKB

**Comment by ThomasBerends** [comment]
Alpha versions are not stable and can have bugs. I would recommend upgrading to 4.5.0 to fix your issue.

**Comment by mdo** [comment]
Yes, please update to the latest and open a new issue if it persists. v4.5 is the latest and we're moving onto v5 alphas soon too.
