### ISSUE TITLE
Bootstrap has unmet peer dependency jquery

### ISSUE THREAD

**Issue by GiovanniGiampaolo** [twbs/bootstrap#30988]
I Got this using `yarn` on my `react `project.

`bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3"
`
```
"dependencies": {
.... some others,
    "bootstrap": "^4.5.0",
.... some others,
  }
```

This is a simple warning that means that I should have into my dependencies jquery 1.9.1 al least or is there some dependencies missing from bootstrap?

**Comment by XhmikosR** [comment]
You are missing the jquer dependency. If you are adding it via another way, like HTML CDN, you can ignore that.

**Comment by GiovanniGiampaolo** [comment]
> You are missing the jquer dependency. If you are adding it via another way, like HTML CDN, you can ignore that.

Thanks so much
