### ISSUE TITLE
Inline forms with form groups do not display correctly on xs screens

### ISSUE THREAD

**Issue by RudeySH** [twbs/bootstrap#30982]
The documentation states the following:

> Controls **only appear inline in viewports that are at least 576px wide** to account for narrow viewports on mobile devices.

This does not appear to be true when using `.form-group`. I think that's a bug. The documentation itself exhibits this bug:

![image](https://user-images.githubusercontent.com/3918757/84071060-640a2e00-a9cd-11ea-9bed-d392e92010e1.png)
https://getbootstrap.com/docs/4.0/components/forms/#help-text

The password field should be 100% width because the viewport width is below 576px, but `.form-group` is preventing that from happening because it has `display: flex;`.

The example above shows it works correctly when `.form-group` is not being used:

![image](https://user-images.githubusercontent.com/3918757/84071288-b9ded600-a9cd-11ea-9dd6-605780ce8811.png)

---

Microsoft Windows 10.0.18363 Build 18363
Google Chrome 83.0.4103.97

**Comment by mdo** [comment]
This behavior is intentional. Inline forms are meant to have multiple form fields on a single line/row, so to accomplish that we need to limit their width.

**Comment by RudeySH** [comment]
The documentation states controls should only appear inline in viewports that are at least 576px wide. But form controls inside form groups are always appearing inline, even in viewports smaller than 576px. That doesn't seem intentional at all.
