### ISSUE TITLE
Collapse isn't compatible with HTML 5.0

### ISSUE THREAD

**Issue by CallMarl** [twbs/bootstrap#31005]
windows 10 Pro 1903
google chrome

link : https://mathiasbynens.be/notes/html5-id-class#:~:text=The%20HTML%204.01%20spec%20states,there%20is%20no%20such%20limitation.

Hello, 
I have id's auto generated then, I note if id start with numbers collapse doesn't work, then event like `show.bs.modal` are never called. Perhaps is the same with other component like tabs.

Thank you.

**Comment by mdo** [comment]
Does this need a docs mention? I feel like this it outside our wheelhouse.

**Comment by CallMarl** [comment]
I think, yes, because you can build collapse, tabs... only based on HTML.

**Comment by XhmikosR** [comment]
We already have a mention but improvements are welcomed.

https://getbootstrap.com/docs/4.5/getting-started/javascript/#selectors

**Comment by mdo** [comment]
Closing per last comment then—already have something to point folks to for now and can revisit if others find room for improvement here.
