### ISSUE TITLE
Option for switch label to display on the left

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#31002]
It would be really useful to have the label on the left of the toggle. If it's possible to update this so the order of the `label` and `input` determine the order they are displayed would one option.

When I have right-aligned switches, it looks a lot better when the text is on the left of the switch.

**Comment by mdo** [comment]
v5 adds the ability to have switches (plus checks and radios) without labels, so you can place them anywhere, but maybe there's more to be done so that positioning/placement can be easier.
