### ISSUE TITLE
Carousel transition flicker on mobile

### ISSUE THREAD

**Issue by fw636** [twbs/bootstrap#31018]
I have a number of sites using bootstrap 4 carousel, which used to be fine, but recently they have all started to show a flicker on transition, this happens randomly.  This is happening on fully up to date iPhone and iPad on safari and firefox, and also on chrome anf firefox on android tablets, although the flicker seems to be less extreme on that.  Upon investigation I have found that the exact same thing occurs with the bootstrap example on https://getbootstrap.com/docs/4.5/examples/carousel/ so I know it's nothing I am doing.  Video of what i see the bootstrap carousel example do on my iphone is in the attched zip.
[bootstrapcarouselissue.zip](https://github.com/twbs/bootstrap/files/4770781/bootstrapcarouselissue.zip)

**Comment by patrickhlauke** [comment]
can't reproduce on iPhone 7 / iOS 13.5.1. could it be you're running an older version, or have some different configuration?

**Comment by fw636** [comment]
As I said in my OP, all devices fully up to date with OS.  Experiencing it on iPhone SE/iOS 13.51, and iPad (6th gen) IOS 13.5.  If configuration, what, because this is the standard bootstrap demo on a standard iOS device.

**Comment by patrickhlauke** [comment]
i now also tried on an iPhone SE / iOS 13.5.1, and I still can't see the same issue as in your video when going to https://getbootstrap.com/docs/4.5/examples/carousel/ - works completely smoothly for me with no flicker/jumps/etc. so ... not quite sure why you're experiencing that problem. could it be a slow connection? no other app running that might be interfering somehow?

**Comment by fw636** [comment]
Shouldn't be a connection speed issue - measurements indicate 49Mb/s.  Nothing else running, have restarted device.  Weird.  Not only happening on the bootstrap example, but on any example I can find on the net that is using bootstrap carousel - like any site built with Mobirise for example (it's sliders use bootstrap).  So something about my devices doesn't like bootstrap or vice versa, but what it is I have no idea.  I've been investigating this for over 2 months, have tried all the suggestions people had about fiddling with z-index and backface visbility etc but none of them work.  I've even ripped out bits of html and css on a line by line basis to see if it has any effect.  There is no consistent behaviour.  I'm presuming it must be a race condition going on, but I can't figure it out, so am probably going to have to abandon using bootstrap carousel and find an alternative as I can't be 100% sure any sites I build are behaving correctly.

**Comment by graouts** [comment]
Happy to look at any WebKit/Safari issues related to animations, but I'd rather issues were filed on bugs.webkit.org so that we can fix the bug appropriately. That said, just like @patrickhlauke, I couldn't reproduce the reported issue with an iPhone 11 Pro running iOS 13.6 beta.
