### ISSUE TITLE
css location support absolute and fixed

### ISSUE THREAD

**Issue by kythuatwebso** [twbs/bootstrap#31015]
Hello,

I see there is currently a class called "position-absolute" but there are no classes like: "top: 0", "left: 0", "right: 0" ... I think there should be support classes Support for "position-absolute" and "position-fixed"

For example:
.top-0
.top-25
.top-50

The same goes for bottom, left, and right

Thanks

**Comment by mdo** [comment]
I could see us adding those `0` values as classes (e.g., `.top-0`), but I don't see us adding any other values. Rest of the suggested ones here feel too random.

**Comment by dsaw** [comment]
This looks something like Tailwind utility classes. Having support for common values like `top-auto` would also be good along with that.

**Comment by mdo** [comment]
Added in #31280
