### ISSUE TITLE
 Bootstrap v4.5.0 collapse doesn't work with jQuery v3.5.1

### ISSUE THREAD

**Issue by diegojrq** [twbs/bootstrap#31017]
jQuery [v3.5.1](https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/) was released a few hours ago. This should work with Bootstrap 4.x fine.

_Originally posted by @XhmikosR in https://github.com/twbs/bootstrap/issues/30553#issuecomment-623866824_

I'm having the same issue that was reported on #30553: Uncaught TypeError: Cannot convert object to primitive value

Tried many combinations of jQuery an Bootstrap, but none worked. Here's my actual config:

"devDependencies": {
        "axios": "^0.19",
        "bootstrap": "^4.5.0",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.13",
        "popper.js": "^1.12",
        "resolve-url-loader": "^3.1.0",
        "sass": "^1.15.2",
        "sass-loader": "^8.0.0",
        "vue-template-compiler": "^2.6.11"
    },
    "dependencies": {
        "jquery": "^3.5.1"
    }

**Comment by XhmikosR** [comment]
Works fine here and for everyone else, so I'd say your local deps are not properly updated. Try deleting any lockfiles and doing an install again.

If it still doesn't work, please post a Codepen demonstrating the problem.
