### ISSUE TITLE
Fixing error in navbar 

### ISSUE THREAD

**Issue by pranaypr6** [twbs/bootstrap#31022]
I had encountered an issue a month ago.
Since there no fix I'm sending this request to you.
There is no closing tag for input tag in first navbar component.
I had attached a image highlighting the error.
Once go through it. 
Thanks

![IMG_20200613_072332](https://user-images.githubusercontent.com/61660436/84557199-a8d3f300-ad46-11ea-8086-7fad4c71a1fd.jpg)

**Comment by mdo** [comment]
> There is no closing tag for input tag in first navbar component.

Inputs do not require closing tags, or even a trailing slash.
