### ISSUE TITLE
Custom checkbox doesn't work with implicit label association

### ISSUE THREAD

**Issue by cdalexndr** [twbs/bootstrap#31021]
Using implicit label association renders the checkbox inoperable:
```
<div class="custom-control custom-checkbox">
  <label class="custom-control-label">
    <input type="checkbox" class="custom-control-input">
    Check this custom checkbox
  </label>
</div>
```
https://codepen.io/cdalxndr/pen/BajKEpG

**Comment by mdo** [comment]
Yes, this is the case for native and custom checks/radios to support the custom forms appearance and make native/custom forms as similar as possible.

**Comment by patrickhlauke** [comment]
probably worth documenting (the checkbox itself is actually triggered correctly, just that the "faked" checkbox is not visually updated as it relies on the sibling selector/the specific structure) or, if possible, extending the styles to cater for implicitly nested label/input.
