### ISSUE TITLE
Carousel slide flicker with Safari (macOS and iOS)

### ISSUE THREAD

**Issue by scottini** [twbs/bootstrap#31038]
Bootstrap 4.5.0, only with Safari, on both macOS (tested 10.15.5) and iOS (tested 13.5.1)

On all my carousels, demo based on bootstrap components website:

![carousel_glitch](https://user-images.githubusercontent.com/2796426/84698654-7269c400-af50-11ea-90a9-2b00b4142445.gif)

**Comment by mdo** [comment]
I can't reproduce this myself (same Safari and macOS version). Do you have any extensions enabled by chance? Also, can you try on the latest v4.5 docs? https://getbootstrap.com/docs/4.5/components/carousel/#with-indicators

**Comment by patrickhlauke** [comment]
this reminds me of https://github.com/twbs/bootstrap/issues/31018 ... similar weirdness (that I was unable to reproduce). wondering if there's something systemic going on here with Safari...

**Comment by mdo** [comment]
@patrickhlauke Definitely been seeing other issues with transitions and animations—we had something with the spinner, too. Makes me think something has changed here.

**Comment by bruecksen** [comment]
Same here. I have the problem on a production site with bootstrap 4.1 on ios and safari and can reproduce it https://getbootstrap.com/docs/4.1/components/carousel/#with-captions here on safari. Anyone have an idea? I also tried to update to 4.5 but its the same.

**Comment by graouts** [comment]
For with Safari Technology Preview 108, I see an issue with [v4.1](https://getbootstrap.com/docs/4.1/components/carousel/#with-captions) where clicking on the right arrow to go from slide 1 to slide 2 shows the animation partially restart after completing. However, I see no such issue with [v4.5](https://getbootstrap.com/docs/4.5/components/carousel/#with-captions).

Looking at v4.1, toggling Experimental Features > CSS Animations via Web Animations shows that the behavior is different prior to switching to the Web Animations engine. I filed [WebKit bug 213376](https://bugs.webkit.org/show_bug.cgi?id=213376) to diagnose the issue.

**Comment by scottini** [comment]
Sorry, my fault (more or less...): I was using Cloudflare as CDN for bootstrap framework, I switched to "official" Bootstrap CDN and now no more flickering :-O

**Comment by graouts** [comment]
> I filed [WebKit bug 213376](https://bugs.webkit.org/show_bug.cgi?id=213376) to diagnose the issue.

The WebKit bug just got fixed.

**Comment by brainomite** [comment]
I can confirm this issue still exists on iOS 13.5.1 on my iPhone Xs Max both chrome and safari, but they use the same browser engine. This is not an issue on my mac OSx Safari. I've tried both bootstrap 4.3 and 4.5.2
