### ISSUE TITLE
No black color

### ISSUE THREAD

**Issue by pas9x** [twbs/bootstrap#31044]
Hi. At latest bootstrap version I found there is no --black color in $colors enumeration at https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss#L46
This can upset blacks. Please add $black #000 color.

**Comment by patrickhlauke** [comment]
"This can upset blacks" i'm going to put this down to an awkward choice of wording from a non-native english speaker, rather than an attempt at being funny.
