### ISSUE TITLE
Select: Uneven padding in Chrome 83

### ISSUE THREAD

**Issue by ranneyd** [twbs/bootstrap#31059]
OS: Mac OS X Catalina
Chrome 83 (Chrome 81 in BrowserStack)

The padding on the `select` form control looks really asymmetrical. Specifically, the dropdown arrow is butting up against the right side of the component, whereas there's a decent amount of padding on the left side. This is Chrome 83. Looking at Chrome 81 (via browserstack), the select menu has a different drop arrow. Though the right-side padding is marginally, if at all, greater in 81, the left padding is much greater in 83, giving a very jarring asymmetrical look.

[This is almost certainly related to the updated form control UI in Chrome 83](https://developers.google.com/web/updates/2020/05/nic83#forms).

You can see it in the example [in the Bootstrap docs](https://getbootstrap.com/docs/4.5/components/forms/).

[I've uploaded screenshots to imgur.](https://imgur.com/a/DE4046s) This should be reproducible in browserstack.

**Comment by mdo** [comment]
Will have to look to see what we can do for v4 since we only have custom forms in v5.

**Comment by ranneyd** [comment]
@mdo upon further investigation in browserstack, this appears to be an ironic anti-bug, because the `select` in Chrome 81 actually does not respect padding (which comes from `.form-control`). `select` in Chrome 83 does, but it doesn't apply to the little dropdown.

**Comment by altescape** [comment]
@ranneyd @mdo Just adding to this on Chrome 83 (plus 84 beta, 85 dev)

A selected option in the select dropdown box now has a black border and a slightly uneven vertical alignment in the selected element. Pretty fugly...

![Screenshot (18)](https://user-images.githubusercontent.com/811806/85114601-e25aa180-b211-11ea-9f44-d54aecce721d.png)

**Comment by patrickhlauke** [comment]
The black outline is likely due to the recent improvements to Chrome's focus ring https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html - and yes, I believe currently it can't be overridden via CSS (though focus indication can be modified for form controls themselves...just not the actual select's dropdown which is pretty much under the sole control of the browser and offers little to no styling hooks)

**Comment by ROGERIO-RIOS** [comment]
Firefox
![firefox](https://user-images.githubusercontent.com/68031153/86966952-510b8a80-c140-11ea-86b4-c09b897d994d.png)
Edge 
![edge](https://user-images.githubusercontent.com/68031153/86966968-5668d500-c140-11ea-88c7-42382cd43786.png)

**Comment by mdo** [comment]
Closing this as a can't fix as far as I can tell. v5 gets around this with a completely custom `.form-select`. For v4, you'll want to use `.custom-select` and sidestep the styling of the default element entirely.
