### ISSUE TITLE
Can you re-license scss files in site/assets/scss/ folder to MIT?

### ISSUE THREAD

**Issue by danny-laa** [twbs/bootstrap#31055]
By keeping license and copyright notice in bootstrap CSS files, we already included proper attribution for the MIT license,

If you you re-license documentation scss files to MIT too, we can reuse those css in our bootstrap projects without further attributions to comply the CC-BY license.

**Comment by XhmikosR** [comment]
The Sass files are MIT like the rest of the project and they do have the license header (the main Sass files, not the partials).

/CC @mdo

**Comment by danny-laa** [comment]
@XhmikosR The license header in site/assets/scss/docs.scss indicate that the file is licensed under CC-BY-3.0 instead of MIT.

https://github.com/twbs/bootstrap/blob/main/site/assets/scss/docs.scss#L5

**Comment by XhmikosR** [comment]
The docs use a different license on purpose.

**Comment by XhmikosR** [comment]
You aren't supposed to use them, or rather, you shouldn't need to use them. I still don't see why one would need to use **our** docs-specific assets.

**Comment by danny-laa** [comment]
> You aren't supposed to use them, or rather, you shouldn't need to use them. I still don't see why one would need to use **our** docs-specific assets.

Bootstrap is a open source project and the official website is a good demonstration/example of how to use the framework, just like the [example you have written for users](https://v5.getbootstrap.com/docs/5.0/examples/).

Some styles/components may also be reusable in other projects, like sidebar, table of content, or the styled navbar.

**Comment by XhmikosR** [comment]
If those were supposed to be reused we'd have them in core, though. The examples can be reused of course.

**Comment by danny-laa** [comment]
> If those were supposed to be reused we'd have them in core, though. The examples can be reused of course.

When you license those scss files under Creative Commons, you have already granted general public the permission to reuse them in their own project. 

However, If you you re-license documentation scss files to MIT, we are allowed to reuse them more easily and without further attributions

**Comment by XhmikosR** [comment]
@mdo it's up to you. I personally don't know if we can even re-license the files.

**Comment by danny-laa** [comment]
@XhmikosR @mdo Any news?

**Comment by mdo** [comment]
Relicensing is a huge pain in the ass unfortunately. I’m not very interested in taking that on right now or anytime soon. It involves getting permission from every single contributor. Not a priority I’m afraid.

**Comment by Ashkar-Aras** [comment]
If I use this code in my project, does any attribution required? What's required to use the code?
https://github.com/twbs/bootstrap/blob/main/site/static/docs/5.0/assets/js/validate-forms.js

and If I want to copy a part of CSS or SCSS code from Bootstrap to modify it for my project, what's required to do according to the license?
