### ISSUE TITLE
Beta/Stable v5 tasks

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#31057]
Tracking for before we go stable with v5—we'll need to update `robots.txt`.

TODO:

- [x] Redirect `v5.getbootstrap.com` pages or add a callout at the top of each page
- [ ] Make sure there are no page overrides on v4-dev docs; we should be careful after we move v5 docs to the main site and when we release the next 4.x version
- [ ] Unmark RTL as experimental?

Beta 1:

- [x] ~~Revert 723cd8d12bdd48f389234b5fc40c3b1789807b4d (not blindly)~~ - Done in #32255
- [x] ~~Revert #32099~~ - Done in #32255
- [ ] ~~Remove unneeded docs redirects? We may skip this~~

Stable:

- [ ] Revert fc74a0d91589c120bf8b9a3913fbceb016733c61 (when we switch to the `latest` npm tag)
- [ ] Revert #32194

**Comment by mdo** [comment]
Adding to both v5-stable and v5-beta in case we do what we did with v4 and put the beta docs on the main site.

**Comment by XhmikosR** [comment]
For reference https://github.com/twbs/bootstrap/commit/723cd8d12bdd48f389234b5fc40c3b1789807b4d#diff-d7f6c1ca03bd330a561f8e674d577ee8

We'll need to revert all those changes when we are ready to move the v5 docs to the main repo.

**Comment by Curious-Ujjwal** [comment]
I want to highlight the common issue I am facing. 
The recent version of Bootstrap CSS as specified in this [link](<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">) is either behaving badly or not working properly.

Please pay some attention to this.

**Comment by Curious-Ujjwal** [comment]
HI
I want to highlight the issue I am facing with the current CSS link on the Bootstrap website, which is as given below:
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

Using this NO CSS files are loaded onto the browser, I have checked this on Google Chrome and Microsoft Edge.
Please look into this matter.

**Comment by FaridAghili** [comment]
Sorry to bother, just wanted to ask is there any schedule for v5 release date?

**Comment by zhangchenglin** [comment]
> Sorry to bother, just wanted to ask is there any schedule for v5 release date?

https://github.com/twbs/release
