### ISSUE TITLE
Docs: Add arrow function instead of normal function

### ISSUE THREAD

**Issue by NishargShah** [twbs/bootstrap#31056]
Suggestion request!! 

Why normal function?

It would be nice if you use the `arrow function` instead of normal function with `let/const` and `querySelector`

```
var myCarousel = document.getElementById('myCarousel');

myCarousel.addEventListener('slide.bs.carousel', function () {
  // do something...
})
```

with

```
const myCarousel = document.querySelector('#myCarousel');

myCarousel.addEventListener('slide.bs.carousel', () => {
  // do something...
})
```

Also, it would be nice if all the places have the same selector because `method` section has `querySelector` where `event` section has `getElementById`

**Comment by XhmikosR** [comment]
Because we can't know the exact target browsers everyone might be using and when we made the v5 docs we did support IE 11.

**Comment by NishargShah** [comment]
Ok, your reason is valid for arrow function what about replace with `querySelector`?

**Comment by XhmikosR** [comment]
`getElementById` is still faster and personally I don't want to get into these micro-optimizations. The snippets exist as a starting point.

**Comment by NishargShah** [comment]
Yes, `getElementById` is still faster but it would be nice if all places have the same selector, Thanks 😀

**Comment by XhmikosR** [comment]
But the snippets only have one ID. When we expect more than one we do use `querySelectorAll`.

**Comment by mdo** [comment]
Per the discussion, closing as a won't fix. If there are repeating snippets or recurring patterns we could optimize around, I'm down to continue hearing about them and even see PRs as appropriate. Thanks!
