### ISSUE TITLE
Favicon color doesn't mach new navbar background

### ISSUE THREAD

**Issue by babobski** [twbs/bootstrap#31068]
Just a small pointer.
Noticed the purple background has changed to be a bit brighter.
Only the background used in the favicon is still the old purple.
Would be nice if it matches.

**Comment by XhmikosR** [comment]
The favicons are new, you are probably seeing cached files.

Otherwise please link directly to the file.

**Comment by babobski** [comment]
I checked for that, but the favicon has still the darker purple background:
The file I'm looking at:

https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon.ico

And a screenshot of the situation on my end:
![afbeelding](https://user-images.githubusercontent.com/3530262/84897980-cc7c9d80-b0a6-11ea-9a1b-33bc0b2fab82.png)

**Comment by XhmikosR** [comment]
Yeah, that's the old docs, we haven't changed the favicons there.

**Comment by babobski** [comment]
Ah i see, it's oke in the V5 docs:

https://v5.getbootstrap.com/
