### ISSUE TITLE
Search form not working in v5 Docs page.

### ISSUE THREAD

**Issue by Mosallamy** [twbs/bootstrap#31060]
The search form in the v5 Docs page does not work at all. It displays [no result found for query “any query”]

- Operating system and version ( macOS, Android, iPadOS) (latest version on all devices)
- Browser and version (Chrome, Safari) (latest version on all devices)

![DC0C99B1-EAA4-4CF3-9C93-F77015E12467](https://user-images.githubusercontent.com/49591985/84832329-b8e51e80-b035-11ea-8d27-983e19118cfc.jpeg)

**Comment by mdo** [comment]
Gah, oversight on our part I think.

@XhmikosR do we need to register a new index because of our new subdomain?

**Comment by XhmikosR** [comment]
I don't think so. But this is a subdomain so we'll probably need to make some changes upstream. I'll make a new issue

**Comment by XhmikosR** [comment]
Fixed upstream.
