### ISSUE TITLE
Modernize caret

### ISSUE THREAD

**Issue by inwardmovement** [twbs/bootstrap#31069]
What about modernizing a bit the caret? The following style outputs something like this:
![image](https://user-images.githubusercontent.com/9438102/84885058-c8468500-b092-11ea-958d-1bf9989ad058.png)

```
.dropdown-toggle::after {
  content: "";
  display: inline-block;
  margin-left: .45em;
  vertical-align: 0.2em;
  border: solid $body-color;
  border-width: 0 2px 2px 0;
  padding: 3px;
  transform: rotate(45deg);
}
```

Maybe we could even use the [Chevron down](https://icons.getbootstrap.com/icons/chevron-down/) BS Icon.

I swear I tried (not for a long time though) to directly make a PR for this to integrate all directional variations and variables, but I couldn't properly figure out how the project pipeline works (I managed to launch the server but changes were not taken into account).

**Comment by Hiws** [comment]
> but I couldn't properly figure out how the project pipeline works (I managed to launch the server but changes were not taken into account).

Did you refresh your browsers cache after making a change? Since the generated files don't have a random hash, the browser is gonna cache your files and changes wont be reflected before the cache is refreshed.

**Comment by inwardmovement** [comment]
Preview: https://deploy-preview-31101--twbs-bootstrap.netlify.app/docs/5.0/components/dropdowns/

I was using the `docs-serve` command, but now I'm using `start` and it works.

So I made a dirty PR as I just disabled the CSS linting to work more freely, so you can see the general idea and adapt it properly to the project if need be (I don't have in mind every aspect of the project, especially I never used linting yet). Sorry for poor quality, see it as a rough sketch, not a real PR. Hope I'm not wasting your time.

**Comment by mdo** [comment]
Closing this for now. Feel free to revisit when you want :).

**Comment by inwardmovement** [comment]
Can you consider this issue as a suggestion to use the same caret icon for dropdowns as for the [v5 accordions](https://getbootstrap.com/docs/5.0/components/accordion/)?
