### ISSUE TITLE
Accordion sidebar for docs

### ISSUE THREAD

**Issue by inwardmovement** [twbs/bootstrap#31072]
I suggest we use the accordion alternative of the Collapse plugin for the docs' sidebar.

At first sight I think it may be more practical and pleasant to use (+ resulting in a less long sidebar ; is it useful to have more than one section expanded at a time?)

https://github.com/twbs/bootstrap/pull/30230 for reference

**Comment by mdo** [comment]
I like the ability to expand any section to jump around. In v4, only one section was viewable at a time, and since we show/expand the current section already at all times, this could be difficult with the accordion.

My vote is for keeping it as is.

**Comment by patrickhlauke** [comment]
while tempting, i find that accordions can be annoyingly when the current open panel is quite long, and you trigger/open a new subsequent one, and end up having to scroll back up to find the start of the new panel (mostly an issue on smaller screens/if you're zoomed in too)..

separately though, i'd say it's worth changing the links that trigger the current disclosure widgets to actual buttons - no real good reason for them being links with `role="button"`. will make a separate PR about it
