### ISSUE TITLE
v5 docs: brand guidelines need update (and question about the brand colors explanation)

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#31092]
obviously, https://v5.getbootstrap.com/docs/5.0/about/brand/ needs to show the new logo, rather than the old one.

however, skimming over them, I also stumbled across this part https://v5.getbootstrap.com/docs/5.0/about/brand/#colors

> Our docs and branding use a handful of primary colors to differentiate what is Bootstrap from what *is in* Bootstrap. In other words, if it’s purple, it’s representative of Bootstrap.

I'm not quite sure this has ever been obvious to me while going over the docs. Is that actually still the case?

/cc @mdo

**Comment by mdo** [comment]
> > Our docs and branding use a handful of primary colors to differentiate what is Bootstrap from what _is in_ Bootstrap. In other words, if it’s purple, it’s representative of Bootstrap.
> 
> I'm not quite sure this has ever been obvious to me while going over the docs. Is that actually still the case?

Since I wrote that docs page, I have indeed kept that in my mind. It's less about the specific colors and more about differentiating what's documentation vs framework/toolkit. It's definitely why I customize the docs navbar, use purple in the left sidebar links, etc. Maybe I should clarify there.

**Comment by patrickhlauke** [comment]
> more about differentiating what's documentation vs framework/toolkit

maybe i'm being dense, but i'm still not following here about what differentiation this is referring to. do you mean the actual parts that make up the getbootstrap site itself, and that there's some differentiation between "straight out of bootstrap" versus any special docs.scss customisation? if so, i never even noticed that before. too subtle perhaps? and also...if this does refer to, essentially, "you can recognise things on this site as being vanilla bootstrap components that you will be able to use right away as well", is the "branding" page the best place for this info? might be better off in the getting started section (maybe introduction?)

> use purple in the left sidebar links

not seeing this...they're gray, no?

**Comment by patrickhlauke** [comment]
i see #31248 removes the weird bit about "Our docs and branding use a handful of primary colors" ... so that PR closes this
