### ISSUE TITLE
V5: input-group overwrites col-* sizing

### ISSUE THREAD

**Issue by knoobie** [twbs/bootstrap#31091]
###  Example to reproduce:

```html
<div class="row">
    <label for="test" class="col-3">Test</label>
    <div class="input-group col-9">
        <span class="input-group-text" id="basic-addon1">@</span>
        <input id="test" type="text" class="form-control" aria-describedby="basic-addon1">
    </div>
</div>
```

### Expected behaviour (V4):

Label is left of the input group. 

###  Current behaviour (V5 alpha):

Label is above the input group.

I think it's related to way col-* creates the flex properties. 
v4 has `flex: 0 0 75%;` and with v5 it is `flex: 0 0 auto;`.

- Ubuntu 20.04
- Firefox 78

**Comment by knoobie** [comment]
Thanks for your feedback, @mdo! 

Would you be willing to accept a pr that allows for customizing of the width of input-group with a variable? (This would allow adding null as value to get the width property removed?) - without the 100% width everything is working properly.

I know that I shouldn't mix layout and components, but adding break points to an input-group sounded totally legit to me in the past or is there a better way to achieve the same without adding additional divs? (Sadly out of my scope..)

**Comment by mdo** [comment]
If you can create a Codepen to demo what you're looking at, and the issues it faces, maybe I can give more guidance. Not sure how many folks look to restrict the width of input groups though—this is similar to our `.form-control` where they are all block level and fill available width.

**Comment by knoobie** [comment]
Thanks for your offer! I created two simple codepens to demonstrate the behaviour of v4 and v5. My goal is to create a responsive form with a simple label (left or above the input-group depending on the current view port) 

Created a mock up from our real ui: 

![preview](https://user-images.githubusercontent.com/3968629/85108024-4334aa80-b20f-11ea-9771-55d1a13a51ad.jpg)

Bootstrap 5: https://codepen.io/knoobie/pen/ZEQLyGL
* the label is always above the field 

Bootstrap 4: https://codepen.io/knoobie/pen/bGEgREG
* the label changes depending on the view port 

The challenge for me is to get the v4 behaviour with v5 without adding an additional layer of divs. (restriction; out of my hands)
