### ISSUE TITLE
V5 Plugin bs-custom-file-input not work 

### ISSUE THREAD

**Issue by NatachaH** [twbs/bootstrap#31095]
Hi,

With the new Bootstrap 5.0.0-alpha1 the plugin  bs-custom-file-input doesn't work anymore for the input file.

Version of the plugin: 1.3.4
Browser: Chrome

**Comment by Johann-S** [comment]
`bs-custom-file-input` will be included in our next alpha see: https://github.com/twbs/bootstrap/pull/31085
