### ISSUE TITLE
Dynamic Tabs, where href starts with number, not working

### ISSUE THREAD

**Issue by PackeTsar** [twbs/bootstrap#31099]
Example: https://jsfiddle.net/wcq4L2fr/1/

When the nav-link href starts with a number, or is only a number (`<a class="nav-link" data-toggle="tab" href="#1">`), it will not expose the referenced contents (`<div class="tab-pane fade" id="1">`).

If the nav-link href is simply alpha, or begins with an alpha character, it works fine.

**Comment by PackeTsar** [comment]
This may be a duplicate of #1956, but it doesn't seem the issue was resolved there

**Comment by patrickhlauke** [comment]
this falls under the same umbrella as this https://github.com/twbs/bootstrap/issues/31005

short version: HTML5 now allows ids to start with a number. but then when you use them in your CSS, or in JS when using things like `querySelector` (which under the hood BS uses), you'd need to do extra work to escape these id references first. BS currently doesn't do that (and hints at this with https://getbootstrap.com/docs/4.5/getting-started/javascript/#selectors), but admittedly this could be made clearer / BS could try and auto-escape references in its functions.

**Comment by XhmikosR** [comment]
I'm not sure what we can do in the JS side to allow this? Personally, I always follow the specs in all my projects so I never had the need for such thing.

**Comment by XhmikosR** [comment]
You are welcome to look into it. As long as we follow the specs, and we can fix this on our side without lots of code, I don't see why not adding support for this.

**Comment by Johann-S** [comment]
Being able to use the native: `CSS.escape` would be the best option, but not really supported currently

**Comment by ffoodd** [comment]
@Johann-S Just checked [on MDN](https://developer.mozilla.org/fr/docs/Web/API/CSS/escape) and [CanIUse](https://caniuse.com/mdn-api_css_escape), support is pretty good. Only missing Legacy Edge, for v5…

Also [Mathias Bynens wrote a lightweight polyfill](https://github.com/mathiasbynens/cssesc) (only 3.43kb unminified): might it be used?

**Comment by XhmikosR** [comment]
I guess this is one of the reasons we should consider regarding dropping Legacy Edge support.

**Comment by mdo** [comment]
Let's drop it then :). We've been teetering on the decision for awhile now, I think Alpha 3 is the time to do it.

**Comment by XhmikosR** [comment]
Now with Legacy Edge dropped, any PRs to switch to CSS.escape are welcome!

**Comment by alpadev** [comment]
> Now with Legacy Edge dropped, any PRs to switch to CSS.escape are welcome!

@XhmikosR can you elaborate on the scope of this? Do you want this to work only for tabs or in general?

**Comment by XhmikosR** [comment]
@alpadev sorry for the late reply :/ I'd say we could use this across all components.

**Comment by pierresouchay** [comment]
Ok, I have seen that CSS escape is not yet supported by some browsers (most notably MSIE and old Android), we might use this to be sure to support old browsers: https://github.com/mathiasbynens/CSS.escape/blob/master/css.escape.js

@GeoSot what do you think?

**Comment by XhmikosR** [comment]
Sorry, no pollyfils should be needed.

Also, we don't support IE or such ancient Android versions.
