### ISSUE TITLE
Gutters start are 1.5rem (20px) wide.

### ISSUE THREAD

**Issue by erperion** [twbs/bootstrap#31104]
[According to docs](https://v5.getbootstrap.com/docs/5.0/layout/gutters/) So 1rem = 13.3px? Really? I always thought that 1rem is 16px. If so it should be 24px not 20px.

**Comment by mdo** [comment]
Should def be `24px`—likely a my bad on that. Wanna submit a PR?

**Comment by erperion** [comment]
No, I'm new to github and it's late here so I don't have time to learn how to do it right now. If you could please submit it by yourself. Cheers.
