### ISSUE TITLE
:disabled selector does not apply when input is read-only.

### ISSUE THREAD

**Issue by utilmind** [twbs/bootstrap#31103]
Hello! This issue can be related to https://github.com/twbs/bootstrap/issues/30890, however my problem is different.

It's very easy to reproduce. ":disabled" style for .form-control does not applies if the control is in "readonly" state.

My fix in overriding CSS was following:

```
.form-control:disabled:read-only {
  background-color: #e9ecef;
  opacity: 1;
}
```
So .form-control:disabled selector is not enough. You should also add .form-control:disabled:read-only, to make the disabled background applied in readonly state.

**Comment by MusicDev33** [comment]
Going back through the referenced issues, it looks like this has been mentioned and there seems to be a PR for this problem. [Here](https://github.com/twbs/bootstrap/pull/30941) is the original PR, and I'm not entirely sure if the comment in [this file](https://github.com/twbs/bootstrap/blob/main/scss/forms/_form-control.scss) is referencing the issue

**Comment by ffoodd** [comment]
Could you please provide a reduced test case using CodePen or JSBin, as stated in our issue template?

FWIW, according to your explanations I don't think this is the same issue: my bet would be that `:read-only` might be declared after `:disabled`, thus overriding it. But I'd need a reduced test case to play with :)

**Comment by mdo** [comment]
Thinking this isn't a problem? The pair of these look the same as `disabled` and `disabled readonly` (placeholder on top two, value on bottom two).

<img width="819" alt="Screen Shot 2020-09-16 at 9 46 26 PM" src="https://user-images.githubusercontent.com/98681/93421426-2dfb0680-f866-11ea-858d-2481676c63a5.png">

**Comment by XhmikosR** [comment]
@twbs/css-review is this still valid?

**Comment by MartijnCuppens** [comment]
Readonly inputs seem to work as expected in v4 and v5
