### ISSUE TITLE
Wrong behaviour media-breakpoint-down() mixin

### ISSUE THREAD

**Issue by 4javier** [twbs/bootstrap#31118]
Arch Linux
Firefox 77.0.1
Bootstrap 4.5.0

I would use this simple class to make an element disappear for viewport's width under 768px.
`.my-class {
	@include media-breakpoint-down(md) {
		display: none;
	}
}`

Instead, to reach my goal I need to pass "sm" to media-breakpoint-down. Considering that I left variables untouched, I thought that media-breakpoint-down(md) should work as expected. Same thing for media-breakpoint-down(lg): it triggers at 1200px and not at 992 as the name would suggest.

I think there's inconsistency with media-breakpoint-up, where i.e. media-breakpoint-up(md) gets triggered when viewport's width reaches 768px.

**Comment by ysds** [comment]
This addressed in #29148 (v5). But we can't apply this change to v4 for keep compatibility.
