### ISSUE TITLE
Modals that include tooltip/popover throws error on close

### ISSUE THREAD

**Issue by Hiws** [twbs/bootstrap#31110]
A modal with a tooltip/popover throws an error on close, if the tooltip/popover wasn't shown while the modal was open.
`Uncaught TypeError: Cannot read property 'destroy' of null`

Steps to reproduce:

1. Go to [modal w/ tooltip example](https://v5.getbootstrap.com/docs/5.0/components/modal/#tooltips-and-popovers)
2. Open dev console (i used chrome on windows)
3. Open the modal, and close it again.
4. Notice 3 errors in the console.
5. Open the modal again, hover the one of the links to show a tooltip.
6. Close the modal again.
7. Notice only 2 errors are displayed in the console now, since one tooltip was shown.

The error isn't limited to the docs.
[Codepen example](https://codepen.io/Hiws/pen/qBbRjvg)

**Comment by Johann-S** [comment]
Nice catch @Hiws 👍 

do not hesitate to submit a PR 😉

**Comment by Rukeith** [comment]
I got the same issue in v5

**Comment by zhangchenglin** [comment]
Your repair is great. I haven't found why the modal box has problems when it is closed. It turned out to be caused by popover. 👍
