### ISSUE TITLE
Module not found: Can't resolve 'popper.js' - NodeJS

### ISSUE THREAD

**Issue by arturproj** [twbs/bootstrap#31128]
Initial actions:
npm i bootstrap 
npm i @popperjs/core { https://popper.js.org/ }

import 'jquery';
import 'bootstrap';
import '@popperjs/core';

Return Bug:
Module not found: unable to resolve "popper.js" in "........\MyApp\node_module\bootstrap\dist\js".

My question:
As I tell bootstrap to read the pkg "popperjs/core" ?

**Comment by Deckluhm** [comment]
As stated [here](https://v5.getbootstrap.com/docs/5.0/components/dropdowns/#overview), you must include Popper **before** Bootstrap.
