### ISSUE TITLE
Prevent docs pages from being embedded in iframes

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31127]
Block embedding of docs pages inside iframes. Embedding these pages inside iframes is basically the same thing as copying and pasting from the docs pages.

**Comment by Deckluhm** [comment]
I'm not a license expert but since documentation is under CC BY 3.0 license (https://creativecommons.org/licenses/by/3.0), anyone can freely copy it.

Or maybe your issue is about something else and I'm missing your point? :man_shrugging:

**Comment by techboyg5** [comment]
> I'm not a license expert but since documentation is under CC BY 3.0 license (https://creativecommons.org/licenses/by/3.0), anyone can freely copy it.
> 
> Or maybe your issue is about something else and I'm missing your point? 🤷‍♂️

Yeah but I think that X-Frame-Options would be good.

**Comment by XhmikosR** [comment]
We'll pass on this right now since GitHub Pages does not allow us to modify any headers and Cloudflare's workers feature costs money.

**Comment by ide-editor** [comment]
I don't think GitHub allows us to add response headers

**Comment by ide-editor** [comment]
> منع تضمين صفحات المستندات داخل إطارات iframe. إن تضمين هذه الصفحات داخل إطارات iframe هو في الأساس نفس عملية النسخ واللصق من صفحات المستندات.

لا اظن ذلك تعتبر العناصر مثل iframe و embed طريقة أخرى لإرسال الطلب عوضآ عن سطر الرابط الموجود في المتصفح ، و لكن كل المواقع على الانترنت تمنع ذلك و ليس هناك طريقة لتخطى رأس x-frame-options
