### ISSUE TITLE
Update the remaining assets SVG to use the new logo

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#31144]
* bootstrap-outline.svg
* bootstrap-punchout.svg
* bootstrap-solid.svg

**Comment by developerhb** [comment]
Hello @XhmikosR . I have used bootstrap for designing websites and it is very much useful.

I would like to start contributing to bootstrap. I find this issue interesting and want to work on this. Can you please provide more information about what needs to be done?

**Comment by XhmikosR** [comment]
@developerhb this is mostly an internal issue so that we don't forget about it. I just need @mdo to send me any assets and I'll take care of it, but thanks for the offer!

**Comment by developerhb** [comment]
Thank you @XhmikosR for reply. I will be actively looking for any issues to solve in this repository.
