### ISSUE TITLE
Bootstrap 4.5.0. Problem in /mixins/_border-radius.scss

### ISSUE THREAD

**Issue by GloomyCoder22** [twbs/bootstrap#31142]
Function `@function valid-radius ($radius)`
```
Sass Compiling Error
"Incompatible units: "rem" and "".
```

**Comment by ysds** [comment]
Please give us more information :) How to reproduce this?

**Comment by GloomyCoder22** [comment]
> Please give us more information :) How to reproduce this?

The preprocessor on the PHP was used http://leafo.github.io/scssphp

**Comment by ffoodd** [comment]
You probably modified a variable used for a radius. Could you share your code, please?
We have an issue template requesting a reduced test case and a few other informations.

**Comment by GloomyCoder22** [comment]
> You probably modified a variable used for a radius. Could you share your code, please?
> We have an issue template requesting a reduced test case and a few other informations.

My "variables.scss"
`
// Grid breakpoints
$grid-breakpoints: (
        xs: 0,
        sm: 576px,
        md: 768px,
        lg: 992px,
        xl: 1200px,
        xx: 1440px,
        // xga: 1600px,
        // fhd: 1920px,
);
$container-max-widths: (
        sm: 540px,
        md: 720px,
        lg: 960px,
        xl: 1140px,
        xx: 1200px,
        //xga: 1530px,
        // fhd: 1830px,
);

$grid-columns:                12;
$grid-gutter-width:           0;
$grid-row-columns:            6;


$spacer: 1rem;
$spacers: ();
$spacers: map-merge(
                (
                        0: 0,
                        1: ($spacer * .25),
                        2: ($spacer * .5),
                        3: $spacer,
                        4: ($spacer * 1.5),
                        5: ($spacer * 3)
                ),
                $spacers
);


// Color
$white:                       #fff;
$black:                       #000;
$color-1:                     #D0000F;
$color-1l:                    lighten($color-1, 15%);
$color-2:                     #11bD56;
$color-3:                     #3d3d3d;
$color-4:                     #b8b8b8;
$color-5:                     #F3F3F3;


// Body
$body-bg:                     $white;
$body-color:                  $black;


// Links
$link-color:                  $body-color;
$link-decoration:             none;
$link-hover-color:            darken($link-color, 15%);
$link-hover-decoration:       none;
$link-border:                 1px solid $color-4;
$link-hover-border:           1px solid darken($color-4, 15%);


// Paragraphs
$paragraph-margin-bottom:     0.625rem;


// Typography
$font-family-base:            'Inter', sans-serif;
$font-size-base:              1rem;
$font-size-lg:                $font-size-base * 1.25;
$font-size-sm:                $font-size-base * .875;
$font-weight-base:            400;
$line-height-base:            1.6;

$h1-font-size:                $font-size-base * 2.5;
$h2-font-size:                $font-size-base * 2.1875;
$h3-font-size:                $font-size-base * 1.5;
$h4-font-size:                $font-size-base * 1.3125;

$headings-margin-bottom:      0.5rem;
$headings-font-family:        Montserrat, sans-serif;
$headings-font-weight:        700;
$headings-line-height:        1.4;
$headings-color:              #3d3d3d;


// Navs
$nav-link-padding-y:                1.3rem;
$nav-link-padding-x:                0;
$nav-link-disabled-color:           $color-4;

$nav-divider-color:                 $color-5;
$nav-divider-margin-y:              $spacer / 2;


// Navbar
$navbar-padding-y:                  $spacer / 2;
$navbar-padding-x:                  $spacer;

$navbar-nav-link-padding-x:         .5rem;

$navbar-toggler-padding-y:          .25rem;
$navbar-toggler-padding-x:          .75rem;
$navbar-toggler-font-size:          $font-size-lg;

$navbar-light-color:                $body-color;
$navbar-light-hover-color:          rgba($black, .7);
$navbar-light-active-color:         $body-color;
$navbar-light-disabled-color:       rgba($black, .3);
// $navbar-light-toggler-icon-bg:      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'><path stroke='#{$navbar-light-color}' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/></svg>");
$navbar-light-toggler-border-color: rgba($black, .0);



// Tooltips
$tooltip-font-size:                 $font-size-sm;
$tooltip-max-width:                 200px;
$tooltip-color:                     $white;
$tooltip-bg:                        $color-1;
// $tooltip-border-radius:             $border-radius;
$tooltip-opacity:                   .9;
$tooltip-padding-y:                 .25rem;
$tooltip-padding-x:                 .5rem;
$tooltip-margin:                    0;

$tooltip-arrow-width:               .8rem;
$tooltip-arrow-height:              .4rem;
$tooltip-arrow-color:               $tooltip-bg;
`

My "templates.scss"
`
@import "variables";
@import 'vendor/bootstrap-4.5.0/bootstrap-reboot';
@import "vendor/bootstrap-4.5.0/type";
@import 'vendor/bootstrap-4.5.0/bootstrap-grid';
@import 'vendor/bootstrap-4.5.0/transitions';
@import 'vendor/bootstrap-4.5.0/nav';
@import 'vendor/bootstrap-4.5.0/navbar';
@import "vendor/bootstrap-4.5.0/dropdown";
`

**Comment by ffoodd** [comment]
You commented `$tooltip-border-radius`: I suggest you define its value to `null` instead. Please let me know if that helps.

**Comment by GloomyCoder22** [comment]
Apparently the problem was in the preprocessor http://leafo.github.io/scssphp. Updated to the latest version and the problem was solved.
