### ISSUE TITLE
col-phone

### ISSUE THREAD

**Issue by oselow** [twbs/bootstrap#31154]
Hello team, I'm here today to propose a grid that can be triggered on the phone thanks to the pixel ratio. Indeed, your grids are based on the number of pixels and therefore do not offer a display for phone. So I have created the attached (incomplete) form gathering some features of the "-xs" "-sm" "-md" "-lg" "-xl" in a "-phone". I hope my idea will be interesting.

Good continuation
PS: not being able to attach a css file, I put it in Word format.

[css phone.docx](https://github.com/twbs/bootstrap/files/4819577/css.phone.docx)

**Comment by morrissey-ingenious** [comment]
The bootstrap framework is mobile first — meaning that col- is your first 'breakpoint' targeted at mobile platforms, you go up from there adding -xs, -sm, -md, -lg.

**Comment by oselow** [comment]
Oooooh, I see, I thought col- was for any resolution below xs... My bad, thank you very much for your responsiveness...
