### ISSUE TITLE
popover template

### ISSUE THREAD

**Issue by valtido** [twbs/bootstrap#31174]
https://github.com/twbs/bootstrap/blob/acdeaed47df69c134154235b902fd12761b03f22/js/src/popover.js#L31

The `data-template` is dead! 

The code is a dead code it's not actually used at all on the page or referenced. Providing a new template is ignored altogether.

**Comment by Johann-S** [comment]
Hi @valtido,

it's used thanks to inheritance in our Tooltip.

> Providing a new template is ignored altogether.

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link, Bootstrap version, and specific browser and OS details.
