### ISSUE TITLE
Docs: carousel, collapse, navs (tabs), popovers should use buttons rather than faked link buttons

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#31186]
There's no good reason (other than ease of styling) for https://v5.getbootstrap.com/docs/5.0/components/carousel/, https://v5.getbootstrap.com/docs/5.0/components/collapse/, https://v5.getbootstrap.com/docs/5.0/components/navs/#javascript-behavior, https://v5.getbootstrap.com/docs/5.0/components/popovers/#dismiss-on-next-click  to use `<a href="#..." role="button">...</a>` pseudo-buttons. While sure, BS can still support this, it'd be good to lead by example and use the correct `<button>` element for this (though I don't believe we have a neutral-enough button style out of the box to support carousel buttons...or at least, the current carousel controls need to be extended to neutralise the remaining button styles that creep in when swapping out the elements).

**Comment by divya661** [comment]
@XhmikosR I would like to work on this part of improving the documentation. I'll update the team regarding it as soon as possible. Can you assign this to me?

**Comment by XhmikosR** [comment]
We don't assign issues to people and there's no need to ask for permission :) Just grab an issue, work on it and make a PR when ready.

**Comment by divya661** [comment]
@patrickhlauke I'm currently working on it and got struck in this https://v5.getbootstrap.com/docs/5.0/components/navs/#javascript-behavior Could you please provide any advice about replacing the anchor tag with button on this part, if I have understood this issue properly.

**Comment by patrickhlauke** [comment]
Carousels will be addressed by https://github.com/twbs/bootstrap/pull/32627
Dynamic tabs will be addressed by https://github.com/twbs/bootstrap/pull/32630
Collapse components now already use buttons in the examples, though it should be made clear that that's the preferred option https://github.com/twbs/bootstrap/pull/32632
Popovers can't currently be changed to buttons due to a bug/shortcoming of Safari and Firefox/macOS (as buttons there don't fire focus event when clicked with the mouse...urgh)

**Comment by patrickhlauke** [comment]
Closing this as - apart from popovers using links, which is still necessary with our current approach due to Safari/macOS's odd duck behaviour, copied by Firefox/macOS - all major things are now sorted.
