### ISSUE TITLE
[Bug | Bootstrap 4] select down arrow too close to box

### ISSUE THREAD

**Issue by indraraj26** [twbs/bootstrap#31198]
- OS - Windows 10 Pro- 64bit
- Chrome Version 83.0.4103.116 (Official Build) (64-bit)

with class form-control
![image](https://user-images.githubusercontent.com/23274631/85999635-0b590e80-ba2a-11ea-8488-815333c405b6.png)

without class form-control]
![image](https://user-images.githubusercontent.com/23274631/85999669-1c098480-ba2a-11ea-9e4d-98bc18b79da7.png)

codepen: https://codepen.io/indraraj26/pen/YzwrQmr

**Comment by alecpl** [comment]
Use `.custom-select`. Use Bootstrap 4.5.0.
