### ISSUE TITLE
Bootstrap 5.0 : Problem with icon inside button with tooltip

### ISSUE THREAD

**Issue by laukerkillian** [twbs/bootstrap#31195]
Hello, 
I tried Bootstrap 5.0 in the development for my small web app but when I've added tooltip, I noticed a small problème because when I put the mouse on the icon inside the button, the tooltip disable with bootstrap 5.0 but when I set Bootstrap 4.5, when I put my mouse on the icon inside the button, the tooltip is always enabled.
So that could be cool if u correct this small problem.
( Sorry for my English, I'm French student ).
Good luck,
Sincerely Killian.

**Comment by laukerkillian** [comment]
with bootstrap 4.5 ( the mouse is on icon ) :
![image](https://user-images.githubusercontent.com/51342912/85955596-e4460280-b97f-11ea-9994-999bb49e815e.png)
with bootstrap 5.0 ( the mouse is on icon ) :
![image](https://user-images.githubusercontent.com/51342912/85955613-0b9ccf80-b980-11ea-8cec-d7773ddb1d5d.png)

**Comment by isteiger** [comment]
pull request #30928 fixes this i think, i had the same issue. could you build and test this to see if it works? otherwise, this will be fixed in Bootstrap v5 Alpha 2

**Comment by XhmikosR** [comment]
Already fixed in main
