### ISSUE TITLE
Add media-breakpoint-below to mean "less than this breakpoint" to avoid media-breakpoint-down confusion

### ISSUE THREAD

**Issue by popnoodles** [twbs/bootstrap#31214]
When I use `media-breakpoint-up(lg)` I'm given `@media (min-width: 992px) ` which is sweet. 
But when I use `media-breakpoint-down(lg)` that returns `@media (max-width: 1199.98px)` which is the next breakpoint up, not the one I specified.

Up means "equal to or greater than this number," but down does not mean "less than this number" it means "less than some other variable." Breakpoints are each a single value but `media-breakpoint-down` is finding another value to then deduct 0.02px from. That's odd; it should use the variable given (less 0.02px).

To work around this behaviour I need to set two variables instead of one. 

In variables.scss
```
// In case we change the breakpoint threshold, store it in a variable
$layout-breakpoint-down: lg; 
$layout-breakpoint-up: xl;
```
And then in many places
```
include media-breakpoint-down($layout-breakpoint-down){
    ...
}

include media-breakpoint-up($layout-breakpoint-up){
    ...
}

```

But I shouldn't' have to define two variables.

In variables.scss
```
$layout-breakpoint: lg;
```
In many places
```
include media-breakpoint-below($layout-breakpoint){
    ...
}

include media-breakpoint-up($layout-breakpoint){
    ...
}

```

Call it what you like, media-breakpoint-below, media-breakpoint-lessthan, media-breakpoint-downfrom, but please add this to solve the problem where two different variables need to be used for one breakpoint threshold.

**Comment by XhmikosR** [comment]
@twbs/css-review your call

**Comment by MartijnCuppens** [comment]
Hi @popnoodles,

This also confused me in `v4`. We've decided to change the implementation in `v5`, see https://github.com/twbs/bootstrap/pull/29148. I think that's the behaviour you wanted?

**Comment by mdo** [comment]
Closing per referenced PR and comment above.
