### ISSUE TITLE
Bootstrap v5 conflict with WooCommerce

### ISSUE THREAD

**Issue by imbewater** [twbs/bootstrap#31220]
I used Bootstrap v5 with wp-bootstrap-navwalker, it's work. But after I install WooCommerce, the dropdown navbar not working.

**Comment by mdo** [comment]
As v5 isn't stable, and we have nothing to do with this plugin, I'm closing this out. I suggest contacting the maintainer of that plugin, and I also suggest that maintainer wait for v5 to go stable first (or at least beta) before updating.
