### ISSUE TITLE
Vertical timeline component

### ISSUE THREAD

**Issue by webdev3301** [twbs/bootstrap#31226]
How about a vertical timeline component with a header and a paragraph? Many frameworks already have it and it would be nice to have it in Bootstrap.

**Comment by mdo** [comment]
Like a split-column with timeline down the middle? Or a left aligned timeline with content on the right? What about a horizontal timeline variant? Any other details or behaviors?

**Comment by suchislife801** [comment]
Here is the CodePen reference [Simple Responsive Timeline](https://codepen.io/brady_wright/pen/NNOvrW)

This is a fully responsive example.

**Comment by alanmehio** [comment]
It would be nice  if the title reflects a more generic approach like time line component.

**Comment by subrayamallya** [comment]
Would it make sense to have this timeline component (vertical) and a multi-step process (horizontal) the same, by having an Orientation attribute?

**Comment by MauricioHernanCabrera** [comment]
Wooow it is a great feature

**Comment by MauricioHernanCabrera** [comment]
I can do that function, if you are interested

**Comment by MauricioHernanCabrera** [comment]
I can do that feature, if you are interested @suchislife801

**Comment by subrayamallya** [comment]
There is also another issue for this #31014 - Duplicate?

**Comment by mdo** [comment]
Closing this as stale. If someone wants to take a fresh pass at this, happy to see a minimal draft PR to help get some feedback on directions we could go with it. Mostly I still think this could be an example vs a component.
