### ISSUE TITLE
Increase Grid Cut Options (request).

### ISSUE THREAD

**Issue by SomeProgrammerGuy** [twbs/bootstrap#31228]
No issue as such. 

I personally am always finding (I'm not sure if others do, maybe I'm OCD...) that having 12 'cuts' in the grid is never enough to stop **stuff** being chopped in some form.  

Could we not have 24 (like some older 'other' frameworks had). It just gives that extra flexibility to make things fit.

As its simply an addition it shouldn't have any impact on backwards compatibility.

**Comment by mdo** [comment]
> As its simply an addition it shouldn't have any impact on backwards compatibility.

What you're asking for breaks backward compatibility. If I have `.col-6`, which is `width: 50%` today, changing to 24 columns becomes `width: 25%`. You're able to change this yourself by modifying source Sass files, though.

**Comment by SomeProgrammerGuy** [comment]
Fair point. I hadn't really thought about it in that sense.
