### ISSUE TITLE
Collapse doesn't work with bundled version of bootstrap 

### ISSUE THREAD

**Issue by ihorbond** [twbs/bootstrap#31235]
Hi, I've recently switched to bundled (bootstrap.bundle.min.js) version of bootstrap (to have popper.js included among other things) and noticed my collapse panels stopped working. They work again if I switch to unbundled, please see CodePen

- Tried v4.0 and v4.5
- Windows 10 Home v1909
- Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- CodePen: https://codepen.io/ihorbond/pen/MWKrMXX

**Comment by Johann-S** [comment]
Hi @ihorbond 

I'm unable to reproduce it see: https://codepen.io/Johann-S/pen/gOPvRKr

BTW your `<script>` should be at the end of your body

**Comment by ihorbond** [comment]
@Johann-S hmm looks like the integrity check in my <script> tag was the culprit on CodePen. but in my project I've downloaded the library and using it locally

**Comment by Johann-S** [comment]
so there is something else, BTW our docs use the `bundle` version

**Comment by nikduvall** [comment]
I am also having an issue where collapse stopped working.  Added details to Issue #28807 as my problem seemed to be closer aligned to that issue.

**Comment by ihorbond** [comment]
Thanks, I'll try to investigate more on my end and will open a new issue if there is one

**Comment by lapak10** [comment]
@ihorbond Have you tried using any CDN provider?

**Comment by mdo** [comment]
Check your `integrity` values and what not. I removed them all and it works.
