### ISSUE TITLE
Blog: Navbar text not wrapping

### ISSUE THREAD

**Issue by ksatyarth2** [twbs/bootstrap#31238]
To reproduce:

- Goto: https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/
- Observe the Navbar Text
![Screenshot from 2020-07-04 16-38-57](https://user-images.githubusercontent.com/47723310/86511333-b3e5e480-be15-11ea-9a1c-bc1ab9384030.png)

My PC:

- Operating system and version (Ubuntu 18.04)
- Browser and version (Chrome Version 83.0.4103.97)

Would you like to work on it?
- [x] Yes

**Comment by mdo** [comment]
File issues against the blog in the blog repo, please. There's already an issue there for this: https://github.com/twbs/blog/issues/151.
