### ISSUE TITLE
Modal show 2x with js, modal-blackdrop is always here

### ISSUE THREAD

**Issue by laukerkillian** [twbs/bootstrap#31247]
Hello,
when I show 2x a modal like that:
`
let modalPreview = new bootstrap.Modal(document.getElementById('modalPreview'), {
                keyboard: false
            });
            modalPreview.show();

let modalPreview2 = new bootstrap.Modal(document.getElementById('modalPreview'), {
                keyboard: false
            });
modalPreview2.show();
`
And when I close that modal the modal-blackdrop is always here.

**Comment by patrickhlauke** [comment]
multiple/concurrent modals are currently not supported in Bootstrap

**Comment by Johann-S** [comment]
From our docs:

> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

See: https://v5.getbootstrap.com/docs/5.0/components/modal/

**Comment by laukerkillian** [comment]
ok thanks
