### ISSUE TITLE
Columns not displayed in order in a nested container on small devices

### ISSUE THREAD

**Issue by garydale** [twbs/bootstrap#31256]
The problem is demonstrated on https://www.lionsclub.ca/masks.html. I built the site so I know how it operates. It uses Bootstrap 4. The main template is a header then a "container" with a collapsible left menu column and a main area where custom content resides.

In this case, the main area contains another container which sets the background colour. It contains two "row"s - the first has a single "col" that sets a background image and holds an inner container for the actual content. The second row continues the content over the background colour.

The inner container also has two rows. The first contains a logo and a "buy now" button, while the second is intended to overlay yet another background over the right-most 11/12 of the area (a "col-1" element occupies the first 1/12 of the area).

This displays accurately on Firefox and Chromium, and other browsers that I've tried. However when I switch to a phone or Responsive Design Mode. the 11/12 column shifts to the left.

This doesn't happen with Chromium's Developer Tools mode but does happen on all the phone browsers I've tried, including Chrome, Firefox and Safari.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by mdo** [comment]
Happy to re-open once we have a reduced test case. Otherwise feel free to ask around SO or Slack :).
