### ISSUE TITLE
bootstrap.css v4.5.0 card typo

### ISSUE THREAD

**Issue by arod1286** [twbs/bootstrap#31262]
The following styles have spaces (1 0 0% v 100%) between the numbers.

.card-deck .card {  -ms-flex:  1 0 0%;  flex: 1 0 0%;
 .card-group > .card {  -ms-flex: 1 0 0%;  flex: 1 0 0%;

**Comment by patrickhlauke** [comment]
> /* Three values: flex-grow | flex-shrink | flex-basis */

https://developer.mozilla.org/en-US/docs/Web/CSS/flex
