### ISSUE TITLE
Changed font-size-base distorts radio and check boxes (v5 alpha1)

### ISSUE THREAD

**Issue by iMattPro** [twbs/bootstrap#31269]
MacOS High Sierra
Safari/Chrome

I changed the SCSS variable `$font-size-base` to be `0.875rem`

With this new font size base, form radio and check boxes are distorted, they are stretched horizontally.

![Screen Shot 2020-07-09 at 1 09 02 PM](https://user-images.githubusercontent.com/303711/87085856-6f779180-c1e5-11ea-9753-f0efc462a5de.png)
![Screen Shot 2020-07-09 at 1 09 10 PM](https://user-images.githubusercontent.com/303711/87085860-71415500-c1e5-11ea-82cd-dcda19d9fb3d.png)

https://codepen.io/matt_codez/pen/zYrjQWG

**Comment by alecpl** [comment]
Firefox and Chrome shows the size is 17.5 x 17.5. However, the dot/check inside is indeed not in the middle in Chrome. No issue in Firefox for me.

**Comment by iMattPro** [comment]
I see this problem in all my browsers:
![image](https://user-images.githubusercontent.com/303711/87185497-b5446080-c29e-11ea-8121-9c0a5db6a763.jpg)

**Comment by mdo** [comment]
Might need to revisit the sizing of checks and radios. `1.25em` leads to some rough math and uneven pixels when paired with `.875rem` root font size. I recall some feedback about them feeling a bit too large previously... @twbs/css-review thoughts on shrinking things?

**Comment by mdo** [comment]
Closed by #31383.
