### ISSUE TITLE
Docs minor typo: Scrollspy "Example with nested nav"

### ISSUE THREAD

**Issue by marianorapa** [twbs/bootstrap#31270]
In the scrollspy docs https://getbootstrap.com/docs/4.0/components/scrollspy/#example-with-nested-nav the navbar displays the right index "Item 1-2", but the one in the example text is mistaken, showing "Item 2-2".

![image](https://user-images.githubusercontent.com/47857311/87107037-1fc0b680-c235-11ea-85e6-429debe692bd.png)

The id seems ok, it's just the html. 

![image](https://user-images.githubusercontent.com/47857311/87107150-64e4e880-c235-11ea-9115-5de23d33437b.png)

**Comment by florianlacreuse** [comment]
You use an outdated version of the docs. It's already fix in the latest versions of BS4 : https://getbootstrap.com/docs/4.5/components/scrollspy/#example-with-nested-nav

**Comment by mdo** [comment]
Closing as already fixed in later release.
