### ISSUE TITLE
v5 breakpoints divisible by 12

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#31288]
I see this line in the v5 (and v4) docs:
`Each breakpoint size was chosen to be a multiple of 12 and to be representative of a subset of common device sizes and viewport dimension`

I have run into fractional pixel issues myself when stuff isn't divisible by 12 (column count), so I get the reasoning.

However, I am noticing that the new xxl breakpoint is 1400px, NOT divisible by 12. Just figured the explanation should be updated, or the default breakpoint should be changed to something like 1440px

**Comment by mdo** [comment]
Wording needs an update, values are correct. The containers are divisible by 12, but viewports are slightly random based on those values to ensure there's proper negative space and room for scrollbars.

**Comment by mdo** [comment]
I believe this only affects v5—some of the content in `breakpoints.md` doesn't exist in v4.
