### ISSUE TITLE
Bootstrap 4 carousel controls block YouTube controls

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31294]
Tested on all major browsers on Windows and Chrome OS.

Steps to reproduce:
1. Go to https://codepen.io/techboyg5/pen/mdVGexx?editors=1000
2. Play a video
3. Click the Pause or Full Screen control

Expected results:
Pause or enter full screen more respectively.

Actual results:
Go to the previous or next video.

**Comment by Deckluhm** [comment]
Not really a bug imo, prev and next controls are just full height and in front of the video.

You can fix this by reducing prev and next controls height.

**Comment by techboyg5** [comment]
> Not really a bug imo, prev and next controls are just full height and in front of the video.
> 
> You can fix this by reducing prev and next controls height.

How?

**Comment by techboyg5** [comment]
> 
> 
> Not really a bug imo, prev and next controls are just full height and in front of the video.
> 
> You can fix this by reducing prev and next controls height.

It seems like a bug.

**Comment by Deckluhm** [comment]
> > Not really a bug imo, prev and next controls are just full height and in front of the video.
> > You can fix this by reducing prev and next controls height.
> 
> It seems like a bug.

You can put pretty much anything you want in a carousel so even if we fix it for Youtube videos, it will still be a problem for another type of media.

In my opinion, it's not Bootstrap responsibility to handle 3rd party integrations, Bootstrap should just provide generic ways to do things.

If you are using a media where the CSS fix shown above doesn't work (like something with clickable things on the left and right sides of the slide), you can recreate controls yourself with `.carousel('prev')` and `.carousel('next')` JS methods.

**Comment by techboyg5** [comment]
> You can put pretty much anything you want in a carousel so even if we fix it for Youtube videos, it will still be a problem for another type of media.

I'm just using YouTube videos as an example. Any iframe-based media inside a carousel is affected.

**Comment by techboyg5** [comment]
> This isn't a bug so much as a collision of two competing components. Honestly never thought folks would put youtube videos in there that you'd want folks to click around on and control. You do have some options though:
> 
> * You could change the dimensions of the carousel controls as mentioned.
> * You could modify the carousel controls to place them outside the carousel.
> * You could remove the carousel controls outright.

OK, closing this now :)
