### ISSUE TITLE
Modals shown using JavaScript is not animated

### ISSUE THREAD

**Issue by ecnepsnai** [twbs/bootstrap#31290]
When showing a modal using the Javascript API it does not use any animations. The data-* API is animated though.

https://codepen.io/ecnepsnai/pen/GRoBLZe

This is using v5 alpha1 (from cdnjs). I've reproduced this in Chrome, Firefox, and Safari on macOS.

**Comment by Deckluhm** [comment]
Isn't it because your are missing the `fade` class on 1st modal?

**Comment by florianlacreuse** [comment]
I confirm, @ecentinela If you want the animation you need to keep the `.fade` class.

See https://v5.getbootstrap.com/docs/5.0/components/modal/#remove-animation

**Comment by ecnepsnai** [comment]
Whoops, thanks folks!

**Comment by patrickhlauke** [comment]
no worries, glad it worked out :)
