### ISSUE TITLE
flex-*-column & flex-*-row in bootstrap 5.0.0-alpha1

### ISSUE THREAD

**Issue by jeancharlesamey** [twbs/bootstrap#31307]
Looked in the [bootstrap.css](https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.css) but did not find a trace of this useful bootstrap 4 class

- .flex-*-row to display flex items horizontally on different screens 
- .flex-*-row-reverse to display flex items horizontally, and right-aligned, on different screens 
- .flex-*-column to display flex items vertically on different screens
- .flex-*-column-reverse to display flex items vertically, with reversed order, on different screens screens

Are they in a roadmap or a new way to deal with changing row to column on different screens in bootstrap 5 ?

best regards

**Comment by mdo** [comment]
https://v5.getbootstrap.com/docs/5.0/utilities/flex/#direction

**Comment by jeancharlesamey** [comment]
b5.0.0 alpha-1 👍 
https://jsbin.com/javuwaj/4/edit?html,output
