### ISSUE TITLE
Smooth scroll feature while using overflow scroll properties 

### ISSUE THREAD

**Issue by Krishna01992** [twbs/bootstrap#31305]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by alecpl** [comment]
Feature requests must include:

    As much detail as possible for what we should add and why it's important to Bootstrap
    Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by mdo** [comment]
There's a CSS property for this that covers a decent amount of browsers, but not enough for us to make it an official utility. See https://css-tricks.com/almanac/properties/s/scroll-behavior/. Beyond that, I don't see us adding JS to do this when it's been done by others a few times over.
