### ISSUE TITLE
Date range type in input field

### ISSUE THREAD

**Issue by Krishna01992** [twbs/bootstrap#31304]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by juhas96** [comment]
Hey I want to contribute on this issue.

**Comment by mdo** [comment]
Inputs support a `date` type in most browsers, and it's up to the browser how those get styled beyond a `.form-control` class we provide. https://codepen.io/emdeoh/pen/BazWjwy
