### ISSUE TITLE
Import Bootstrap.bundle.js

### ISSUE THREAD

**Issue by andresfdel17** [twbs/bootstrap#31306]
Hello, how can i import bootstrap.bundle.js with npm webpack . I tried and i can not use new bootstrap class.
When i import "bootstrap" don get that file

**Comment by AlanSweden** [comment]
Hi,

Have you tried to post on  [Stackoverflow](https://stackoverflow.com/search?q=bootstrap.bundle.js)

**Comment by Johann-S** [comment]
@andresfdel17 we need more information, like which version of Bootstrap are you trying to import ?

**Comment by andresfdel17** [comment]
bootstrap 5.0 alpha

**Comment by Johann-S** [comment]
`import Bootstrap from 'bootstrap/dist/js/bootstrap.bundle.min.js'`
