### ISSUE TITLE
Dropdown not working inside toast

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31302]
Dropdowns do not work when inside toasts.

**Comment by isteiger** [comment]
which version of Bootstrap is this on?

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by techboyg5** [comment]
> 
> 
> Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.
> 
> _This is a saved reply._

[Nothing's wrong :)](https://codepen.io/techboyg5/pen/RwreBmj)

**Comment by gauravbehere** [comment]
`.overflow-visible` can be used in combination with `.toast`. We have overflow-auto but that injects a scroll within the toast.
We can have `overflow-visible` as util. What say @mdo ?

**Comment by techboyg5** [comment]
> which version of Bootstrap is this on?

It is on Bootstrap 4.5.0.
