### ISSUE TITLE
v3.4.1 button looks ugly when :focus on Chrome 84

### ISSUE THREAD

**Issue by mercury233** [twbs/bootstrap#31317]
Windows7, Chrome 84
Test case: https://jsbin.com/jogejuxota/edit

Chrome changed its default element styles in recent versions, and the default appearance of button in v3 looks ugly when focused.

Chrome 84:
![GIF](https://user-images.githubusercontent.com/13391795/87760481-62404f80-c842-11ea-8130-ede0dff4226e.gif)

Earlier chrome (What I excepted):
![GIF](https://user-images.githubusercontent.com/13391795/87760489-640a1300-c842-11ea-9d52-3114bdcd1632.gif)

**Comment by Deckluhm** [comment]
As you can see [here](https://github.com/twbs/release), Bootstrap 3 isn't supported anymore so this probably won't be fix.

Maybe it's time to upgrade!

**Comment by patrickhlauke** [comment]
That appears to be related to Bootstrap 3.x, which we're not changing anymore. v4 and the upcoming v5 define their own focus styles. https://getbootstrap.com/docs/4.5/components/buttons/

**Comment by patrickhlauke** [comment]
(hah, @Deckluhm beat me to it)
