### ISSUE TITLE
Firefox warning message

### ISSUE THREAD

**Issue by AniTarloyan** [twbs/bootstrap#31312]
In firefox, the console has a warning message

 "This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.".

Please change CSS zoom property to transform,  transform-origin.

**Comment by isteiger** [comment]
which version is this on?

**Comment by AniTarloyan** [comment]
78.0.2

**Comment by isteiger** [comment]
oh sorry meant bootstrap too. could you provide that version too?

**Comment by AniTarloyan** [comment]
3.4.1

**Comment by isteiger** [comment]
3.4.1 is end of life, please look at upgrading to bootstrap 4.5.0

**Comment by patrickhlauke** [comment]
Yup, what @isteiger said. Afraid we're not going to touch/address old versions of bootstrap.
