### ISSUE TITLE
Invalid US-ASCII character "\xE2"

### ISSUE THREAD

**Issue by bigrepository** [twbs/bootstrap#31318]
_functions.scss contains

`  @warn "Found no color leading to #{$min-contrast-ratio}:1 contrast ratio against #{$background}…";`

on line 114.

The **…** character causes my scss preprocessor to throw an error: **Error: Invalid US-ASCII character "\xE2"**
Removing the character and/or replacing it with ... helps.

**Comment by patrickhlauke** [comment]
you should really be using UTF-8 though ... not quite sure why your preprocessor defaulted to US-ASCII

**Comment by mdo** [comment]
Closing since I feel like we should be just supporting UTF-8.
