### ISSUE TITLE
Free Social Share Buttons

### ISSUE THREAD

**Issue by thekodester** [twbs/bootstrap#31327]
**Reason:**
I think it would be really cool to have a builtin tool for sharing content that is privacy minded so you don't have to use third party plugins that track users.

I have actually developed a fairly simple tool using bootstrap that I think anyone could simply adjust to make it work directly with bootstrap.

**GitHub Repo with Code:**
https://github.com/thekodester/socialshare

**GitHub Repo Demo Page:**
https://thekodester.github.io/socialshare/

**Live Site Demo:**
https://thekodester.ca/about

**Full Screen Screenshot:**
<img width="1792" alt="Screen Shot 2020-07-19 at 1 33 18 AM" src="https://user-images.githubusercontent.com/23484460/87867978-e9371a00-c95f-11ea-83b4-d85dbf7703ef.png">
<img width="1792" alt="Screen Shot 2020-07-19 at 1 32 36 AM" src="https://user-images.githubusercontent.com/23484460/87867979-ec320a80-c95f-11ea-9472-d1d4345892d2.png">

**Paged Resize Screenshot:**
<img width="616" alt="Screen Shot 2020-07-19 at 1 32 49 AM" src="https://user-images.githubusercontent.com/23484460/87867984-f8b66300-c95f-11ea-950e-a9de614605af.png">
<img width="616" alt="Screen Shot 2020-07-19 at 1 32 57 AM" src="https://user-images.githubusercontent.com/23484460/87867985-fc49ea00-c95f-11ea-86b7-4e0df1edcb57.png">

**Comment by mdo** [comment]
Thanks, but we'll pass on this :).
