### ISSUE TITLE
Container selectors on navbar

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#31334]
https://github.com/twbs/bootstrap/blob/cc76849d0dfccfbffc761e8ef3e8cf66a7e4f71b/scss/_navbar.scss#L39-L49

it may could be replaced by [class*="container"]

**Comment by rohit2sharma95** [comment]
Or maybe `[class^="container"]` is better :thinking:

**Comment by mdo** [comment]
We could do this, yes, but it does introduce some ambiguity if someone has a custom class like `.container-custom` that does something else. Chance is slim, but it's there.

Thoughts @twbs/css-review on embracing a shorthand here? I'd be down to take the chance.

**Comment by MartijnCuppens** [comment]
> We could do this, yes, but it does introduce some ambiguity if someone has a custom class like `.container-custom` that does something else. Chance is slim, but it's there.

Indeed, would leave it as is.
