### ISSUE TITLE
Site: push update for v5alpha to versions page?

### ISSUE THREAD

**Issue by tomByrer** [twbs/bootstrap#31331]
I knew v5 alpha was released, but had to dig though the blog to find the new v5 docs URL.

Perhaps a v4 front page banner should NOT be introduced until the beta, but would be nice that the [change you already made](https://github.com/twbs/bootstrap/blob/main/site/data/docs-versions.yml) gets pushed to the live [v4 versions page](https://getbootstrap.com/docs/versions/) now please?

**Comment by mdo** [comment]
I think we'll hold off until v5 goes beta because at that point we'll have a firm decision on the URLs (not just subdomain, but features and docs pages).
