### ISSUE TITLE
How to use the icons of bootstrap 4.5 version by typing it on the <div class=""></div> or etc...

### ISSUE THREAD

**Issue by vandamiees** [twbs/bootstrap#31340]
Hi!, good day, 

      I don't know how to apply the icons of bootstrap 4.5 version without downloading the .svg format, I just want to mention it to the codes and it will appear directly to my web pages. 

      I am looking forward to your guide, stay safe always, thank you very much.  

Best regards,

Van

**Comment by lapak10** [comment]
@vandamiees From the [Bootstrap docs](https://getbootstrap.com/docs/4.5/extend/icons/), ..**Bootstrap doesn’t include an icon library by default**

But you can add it by yourself, by adding <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> to <head></head> of your html 
You can use (and you should as per best practices ) CDN hosted version of FontAwesome (or any other library) directly, and then simply use icon classes to show icons. Using CDN hosted version, theres no need to download svg.

**Comment by mdo** [comment]
As mentioned, there are no icons included in Bootstrap. If you're talking about the separate project, [Bootstrap Icons](https://github.com/twbs/icons), there's usage guidelines on that project's site: https://icons.getbootstrap.com.

**Comment by vandamiees** [comment]
> As mentioned, there are no icons included in Bootstrap. If you're talking about the separate project, [Bootstrap Icons](https://github.com/twbs/icons), there's usage guidelines on that project's site: https://icons.getbootstrap.com.

I knew but how can I down the zipped bundle of icons? so I can declare to my codes so it will work.

**Comment by vandamiees** [comment]
> @vandamiees From the [Bootstrap docs](https://getbootstrap.com/docs/4.5/extend/icons/), ..**Bootstrap doesn’t include an icon library by default**
> 
> But you can add it by yourself, by adding `<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">` to `<head></head>` of your html
> You can use (and you should as per best practices ) CDN hosted version of FontAwesome (or any other library) directly, and then simply use icon classes to show icons. Using CDN hosted version, theres no need to download svg.

but these are not for free you have to pay before you will use their icons.

**Comment by lapak10** [comment]
@vandamiees It has both Free and Paid set of icons, if you have any icon which falls under Premium one, then only you have to pay otherwise FontAwesome Free version has many icons which you use for free.

**Comment by vandamiees** [comment]
> As mentioned, there are no icons included in Bootstrap. If you're talking about the separate project, [Bootstrap Icons](https://github.com/twbs/icons), there's usage guidelines on that project's site: https://icons.getbootstrap.com.

Thanks man, I got it the zipped icons of bootstrap now.

**Comment by vandamiees** [comment]
> @vandamiees It has both Free and Paid set of icons, if you have any icon which falls under Premium one, then only you have to pay otherwise FontAwesome Free version has many icons which you use for free.

Thanks man too man, I had a lot of options now.
