### ISSUE TITLE
Card with only one paragraph element in the card-body has unnecessary margin at the bottom

### ISSUE THREAD

**Issue by Doogiemuc** [twbs/bootstrap#31348]
When a bootstrap card only contains one paragraph element `<p>` in its card-body, then the paragraph still has its default margin-bottom: 1rem;     This should be removed for the last(!) paragraph in a card.

### Simple example HTML
```
<div class="card">
  <div class="card-body">
    <p>This paragraph has a default margin-bottom. It shouldn't</p>
  </div>
</div>
```

### Solution
Add the following CSS
```
.card-body p:last-child {
  margin-bottom: 0;
}
```

### JSFiddle
https://jsfiddle.net/qhv016wa/

**Comment by Doogiemuc** [comment]
Pull request: https://github.com/twbs/bootstrap/pull/31349

**Comment by rohit2sharma95** [comment]
There is already a class `card-text` for it. Or you can use utility class `mb-0`.

https://github.com/twbs/bootstrap/blob/c7bc7a31bbc11c3f9af3ad317581cbd13c7bb5f1/scss/_card.scss#L62-L64

**Comment by Deckluhm** [comment]
There is the exact same issue with form inside card, last `.form-group` having an unnecessary `margin-bottom`.

You can see it in the doc on this specific form: https://getbootstrap.com/docs/4.5/components/forms/#horizontal-form

It's probably trickier tho, since it's not mandatory to wrap submit button inside a `.form-group`.

**Comment by rohit2sharma95** [comment]
In v5 `.form-group` has been [dropped](https://v5.getbootstrap.com/docs/5.0/migration/#forms) for margin utilities

**Comment by florianlacreuse** [comment]
And what if the last item is an `.alert` for instance? Since `.alert` has a bottom margin it will be the same issue. Same for many more components. IMHO, you should use margin utilities, as @rohit2sharma95 said.

**Comment by Doogiemuc** [comment]
Ok. Thank you for the card-text hint. Didn't see that one. 
Of course manually setting a (non-)margin is always possible.

**Comment by Doogiemuc** [comment]
An alert has a default bottom margin. A bootstrap card doesn't.   => Should at least be mentioned in the docs.

**Comment by mdo** [comment]
This should ideally be addressed with the `.card-text` class, or with utilities IMO. People customize Bootstrap's HTML all the time, and we never really know what folks will do with it that could break our CSS.

For example, this code affects every `<p>` within nested content, not just the immediate paragraphs.

```scss
.card-body p:last-child {
  margin-bottom: 0;
}
```

Of course we could limit it with a child selector `>`, but then that locks the HTML and creates a more specific selector.

**Comment by mdo** [comment]
Closing as a won’t fix per the above comment.
