### ISSUE TITLE
Accordion scroll behavior in Chrome 

### ISSUE THREAD

**Issue by sonjastrieder** [twbs/bootstrap#31341]
Since a recent Chrome update the accordion feature of the collapse component started to scroll down the entire page when opening a collapse area below the currently active collapse area. 

Video - Comparison of scroll behavior in Firefox v77.0.1, where it works as expected, and Chrome v84.0.4147.89: 
https://streamable.com/ojle0t

This can be replicated on the collapse page of the Bootstrap docs:
https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example

OS: macOS and Windows
Browser: Chrome v84.0.4147.89

**Comment by patrickhlauke** [comment]
as this is browser behavior (Chrome choosing to always anchor on what you clicked if it results in the document's length changing), there's likely little that can be done on Bootstrap's part I think.

**Comment by patrickhlauke** [comment]
ah, it seems this may be suppressable with https://drafts.csswg.org/css-scroll-anchoring/

**Comment by sonjastrieder** [comment]
Scroll anchoring does fix the issue for me. Thank you!
`overflow-anchor` has been around for a while in Chrome though. Wondering what has changed in one of the latest updates.

**Comment by patrickhlauke** [comment]
i think they moved it from being behind a flag to now being enabled by default perhaps?
