### ISSUE TITLE
Add profile README to twbs

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31352]
I think that adding a profile README to `twbs` would be good idea.

**Comment by Deckluhm** [comment]
I'm pretty sure this feature isn't available for organizations, only for individual users.

**Comment by mdo** [comment]
Yup, what @Decklumn said.

**Comment by techboyg5** [comment]
> Yup, what @Decklumn said.

How about add one to @mdo then?

**Comment by mdo** [comment]
There's nothing to add, the feature isn't available for the type of account we have on GitHub.

**Comment by techboyg5** [comment]
> 
> 
> There's nothing to add, the feature isn't available for the type of account we have on GitHub.

OK, thanks!
