### ISSUE TITLE
Upgraded Bootstrap from v4.3.1 to v4.4.1-Error: Invalid CSS after “…ponsive-21by9by”: expected selector, was “(x: 21, y: 9)”

### ISSUE THREAD

**Issue by MezaVanessa** [twbs/bootstrap#31351]
I upgraded Bootstrap from v4.3.1 to v4.4.1. When my CSS compiles, I get the below error. 

Message:
 lib/bootstrap/scss/utilities/_embed.scss
` Error: Invalid CSS after "...ponsive-21by9by": expected selector, was "(x: 21, y: 9)"`

The variable appears to be missing from the Bootstrap _varibles.scss file.

I found the below code in the Bootstrap GitHub and have tried copying and pasting it into the _varibles.scss file, and I'm still receiving the above error. 

Lines 395-414 is the code I copied and pasted over. I tried commenting and uncommenting 371-393 that didn't seem to make a difference. I am on macOS Catalina v10.15.5, Google Chrome v83.0.4103.116

 ```
// scss-docs-start embed-responsive-aspect-ratios
   $embed-responsive-aspect-ratios: (
   "21by9": (
   x: 21,
   y: 9
   ),
   "16by9": (
   x: 16,
   y: 9
   ),
   "4by3": (
   x: 4,
   y: 3
   ),
   "1by1": (
   x: 1,
   y: 1
   )
   ) !default;
   // scss-docs-end embed-responsive-aspect-ratios

```

![VS Code Screenshot](https://user-images.githubusercontent.com/67923895/88302591-08bda200-ccd4-11ea-99b9-31032ac8d7aa.jpg)

**Comment by mdo** [comment]
Seems like an issue with your Sass compiler or linter? This compiles fine on our end, so we'll need to know more about your setup before we can offer any other help.

**Comment by techboyg5** [comment]
Why not upgrade to 4.5.0?

**Comment by mdo** [comment]
Closing since we haven't heard anything else.
