### ISSUE TITLE
Button is shown through dropdown list.

### ISSUE THREAD

**Issue by ajkr195** [twbs/bootstrap#31353]
I have a weird issue. I am using Bootstrap 5.0. Alpha's nav-bar and just down below that I have a file upload form having an upload button like below:

```
<div class="input-group">
<input type="file" class="form-control form-control-sm" id="files" placeholder="Upload Multiple Files" name="files" 										multiple required />
<button type="submit" class="btn btn-danger"><i class="fas fa-file-upload"></i> Upload</button>
<div class="invalid-feedback">Please select at least one file.</div>
</div>


```

All is good but when I open the drop down from my navbar, the button at my form appears right through it. Please take a look at the attached screenshot. Kindly do let me know if need more details.

![Bootsrap](https://user-images.githubusercontent.com/34718091/88358534-56bac000-cd3d-11ea-941a-fca389c7b948.png)

**Comment by isteiger** [comment]
hm. try setting the zindex for the dropdown-menu to a high number then set the zindex for the button to a lower number

**Comment by ajkr195** [comment]
Okay, this is what I tied in my css file:
```
.topbar .dropdown-list {
	padding: 0;
	border: none;
	overflow: hidden;
	 z-index: 1000;
}

.buttonfix {
	 z-index: 1;
}
```

Still no luck. Please suggest.

**Comment by isteiger** [comment]
the numbers don’t have to be this high but just to be sure it overrides stuff; 
for the dropdown menu add:
`style="z-index:3000;"`
for the button add:
`style="z-index:2500;`

**Comment by isteiger** [comment]
hm try putting it on the style element like i suggested

**Comment by ajkr195** [comment]
```
<button type="submit" class="btn btn-danger" style="z-index:2500;"><i class="fas fa-file-upload"></i> Upload</button>
<div class="dropdown-list dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown" style="z-index:3000;">
```

this is what I tried. Still no luck.

**Comment by isteiger** [comment]
could you make a codepen?

**Comment by ajkr195** [comment]
I will try for a codepen as and when I get time.

**Comment by MartijnCuppens** [comment]
Looks like a `z-index` issue with custom styles
