### ISSUE TITLE
Add scroll-behavior utility

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31357]
`.smooth`
should be equal to:
`scroll-behavior: smooth;`

**Comment by kunal22012001** [comment]
I would like to work on this issue.

**Comment by techboyg5** [comment]
> 
> 
> I would like to work on this issue.

Sure you can! Feel free to start a PR and link to it here :)

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/31413#issuecomment-668474723.
