### ISSUE TITLE
Modal fade effect not working on bootstrap 4.1 or higher

### ISSUE THREAD

**Issue by JuanErroa** [twbs/bootstrap#31364]
If I go to modal examples page to 4.1 or higher version in my PC The modal appears directly whithout any fade animation, even if I try clear the cache using (win + R) or using CCleaner. However it works in my smartphone...

Now I realized that it works if I use bootstrap 4.0 or lower... I don't know if it's important but I recently formatted the PC but I'm sure it has all its drivers and I have also a problem using facebook in this computer, when I'm playing a video I usually use right click on it to copy its url and now nothing happens when I use right click on any facebook video.

What could be the problem?

**Comment by patrickhlauke** [comment]
> The animation effect of this component is dependent on the prefers-reduced-motion media query. See the [reduced motion section](https://getbootstrap.com/docs/4.5/getting-started/accessibility/#reduced-motion) of our accessibility documentation.

Older versions of bootstrap didn't take that into account, but newer versions do disable animation when `prefers-reduced-motion` is signalled by the browser. You likely turned this on accidentally? https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/

**Comment by JuanErroa** [comment]
That solved my problem, thank you very much!!! ^^
