### ISSUE TITLE
Bootstrap need CSS Variable Support

### ISSUE THREAD

**Issue by themeix** [twbs/bootstrap#31363]
In my project i need to use CSS Variables. But if i use css variables with bootstrap it does not working as its using lighten, darken etc functions.

So please make a solution to give support css variables which is very essential for color configuration ( Ex. Dark mode, light mode for template )

Ref. https://github.com/twbs/bootstrap/issues/26596
Can't use primary color in css variable : https://codepen.io/themeix/pen/LYGvjdP

**Comment by MartijnCuppens** [comment]
Duplicate https://github.com/twbs/bootstrap/issues/26596
