### ISSUE TITLE
Bootstrap columns are not compatible with Firefox 68.11.0esr

### ISSUE THREAD

**Issue by hamedgasemi200** [twbs/bootstrap#31373]
Bootstrap 4 is not compatible with Firefox 68.11.0esr (64-bit)

```
<div class="row card-columns bg-warning">

    <div class="col-lg-3 bg-secondary">
        <div class="card">
            <div class="card-body">Hello</div>
        </div>
    </div>

    <div class="col-lg-9 bg-primary">
        <div class="card">
            <div class="card-body">World</div>
        </div>
    </div>

</div>
```

It looks like this in Firefox:

![image](https://user-images.githubusercontent.com/33207312/88747956-bb429a00-d104-11ea-89fd-3b1cfcf8360f.png)

**Comment by Deckluhm** [comment]
I think you need to use either `.card-columns` or `.row` + `.col`, not both.

**Comment by mdo** [comment]
> I think you need to use either `.card-columns` or `.row` + `.col`, not both.

Correct!

**Comment by hamedgasemi200** [comment]
But it works correctly on Chrom!
