### ISSUE TITLE
The Bootstrap Navbar changes color to #1c2331 between resolution 800px to 850px 

### ISSUE THREAD

**Issue by dh00mk3tu** [twbs/bootstrap#31377]
The Bootstrap Navbar changes color to #1c2331 between resolution 800px to 850px 

The standard bootstrap Navbar changes color when testing; 

I was testing my site's responsiveness and was squeezing the width down from 1920.
In the range; from 850px to 800px, the Navbar's colour changes to #1c2331.

I checked the project thoroughly if there might be some Media query that might be doing so but that wasn't the case at all apparently. 

- Operating system Ubuntu 20.04.1 LTS
- Browser Firefox Developer Edition Version 79.0b9 (64-bit)

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by mdo** [comment]
Closing until we hear more.
