### ISSUE TITLE
4.5 Inconsistent button height

### ISSUE THREAD

**Issue by la-ruby** [twbs/bootstrap#31376]
When adding a `form-control-sm` to the the 3  items at https://codepen.io/swconsult1ng/pen/VweJLza
you end up with a bigger height for the submit button: https://codepen.io/swconsult1ng/pen/GRobJOm

![image](https://user-images.githubusercontent.com/55279023/88809026-76e8e580-d168-11ea-85d2-db5e5f36e7c8.png)

OS: Mac OS
Browser: Chrome / Safari

**Comment by MartijnCuppens** [comment]
Add `.btn-sm`: https://codepen.io/MartijnCuppens/pen/OJMeXBq?editors=1000
