### ISSUE TITLE
.img-thumbnail with width attribute

### ISSUE THREAD

**Issue by migliori** [twbs/bootstrap#31375]
Hi,

When we set an image width with .img-thumbnail class the displayed image is .5em smaller than it should be.
This is caused by the .img-thumbnail padding + the box-sizing.

Here's [a codepen](https://codepen.io/migli/pen/mdVYNGJ)

**Comment by MartijnCuppens** [comment]
Just increase your width

**Comment by migliori** [comment]
You closed the ticket but I'm sorry, increasing a width is just a dirty quick solution:

- Not clean at all to set false img widths in the code
- If you remove the img-thumbnail class you must always remember to add .5em to the images (who will?)
- Many coding apps. add the img size automatically
- if you generate dynamic images in any language you 'll have to parse the dom and make strange calculation to add .5 em to each .img-responsive

`box-sizing` solves all these problems.

If you don't want to change `box-sizing` (which I can understand) there's probably another way to get the same result with `:before` and/or `:after`

**Comment by ffoodd** [comment]
@twbs/css-review Both issue and suggested fix seems legit to me: I reopen it in order to discuss it again. Please step in again @MartijnCuppens if you still think there's no issue.

**Comment by mdo** [comment]
`.img-thumbnail` is an optional class for displaying images. If the styling isn't what you want, I'd say don't use it. Changing the width, changing the `box-sizing`, using `calc` or negative margins, and other options are all appropriate I'd say. You could also build your own `.img-thumbnail-wrapper` or something that'd behave slightly differently so that the `padding` and `border` aren't on the `<img>`.

**Comment by migliori** [comment]
I changed the box-sizing and all's prefect with this, but in my opinion most Bootstrap users won't do it and the result will be wrong image sizing on many websites all over the world.
What would be the inconvenient to add this to the Bootstrap CORE CSS?

**Comment by XhmikosR** [comment]
So, what's a viable proposed fix for this?

**Comment by MartijnCuppens** [comment]
> `box-sizing` solves all these problems.

Nope, it won't. `.img-fluid` wouldn't work anymore since it would require additional CSS.

Wrapping the image in in a `div.img-thumbnail` also works, even with the responsive class
https://codepen.io/MartijnCuppens/pen/RwaeRXz?editors=1000

**Comment by mdo** [comment]
Closing as a won't fix—the thumbnail component is opt-in and comes with the same styling and box-sizing as virtually every other component in Bootstrap. If someone wants to clarify something in our docs, I'm open to a PR, but otherwise, no planned changes here in v5.
