### ISSUE TITLE
Make the docs a single-page application

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31388]
How about making the Bootstrap docs a single-page application?

**Comment by Deckluhm** [comment]
I don't see any benefit about making a docs website an SPA and it would probably require some work (and introduce additional maintenance cost moving forward).

**Comment by techboyg5** [comment]
> I don't see any benefit about making a docs website an SPA and it would probably require some work (and introduce additional maintenance cost moving forward).

OK, interesting. But there are many pages with content repeated over them, like methods and events categories, so it's not just the assets.

**Comment by mdo** [comment]
Thanks, but not interested. Static pages are just fine by us.
