### ISSUE TITLE
Random class added to body on every page load

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31389]
A random class is added to the `body` element on every page load. Can this be fixed?

**Comment by Deckluhm** [comment]
Can you provide a repro?

That looks like something caused by another lib or framework.

**Comment by techboyg5** [comment]
> Can you provide a repro?
> 
> That looks like something caused by another lib or framework.

Only jQuery, Popper.js and Bootstrap JS here. https://projects.techboyg5blog.com/

**Comment by techboyg5** [comment]
Update: It looks like the "I don't care about cookies" extension is the problem. Never mind!
