### ISSUE TITLE
Docs says <options> are not styled, but they are

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31394]
On [this page](https://v5.getbootstrap.com/docs/5.0/forms/select/), you see the following text:
> Custom <select> menus need only a custom class, .form-select to trigger the custom styles. Custom styles are limited to the <select>'s initial appearance and cannot modify the <option>s due to browser limitations.

However, the &lt;options> are also styled as well on all major browsers. Can you please fix this?

**Comment by mdo** [comment]
Options are not styled by us. Every browser applies their own default look and feel.

**Comment by techboyg5** [comment]
> Options are not styled by us. Every browser applies their own default look and feel.

The size of the `&lt;option&gt;`s is styled, however, in all major browsers.
