### ISSUE TITLE
a:not([href]) styles too strong/override .btn-* color definition

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31391]
The button text at https://getbootstrap.com/docs/4.5/components/popovers/#dismiss-on-next-click should be white instead of black.

**Comment by patrickhlauke** [comment]
https://codepen.io/patrickhlauke/pen/gOPVNOW

**Comment by techboyg5** [comment]
> https://codepen.io/patrickhlauke/pen/gOPVNOW

Dismiss on next click only works with `<a>` elements. Read the docs please.

**Comment by patrickhlauke** [comment]
> Read the docs please.

lose your attitude please. i've just rewritten your issue title to actually hone in on the problem, and added that as a demonstration.

**Comment by ffoodd** [comment]
@patrickhlauke @techboyg5 The popover example works fine now, it's been fixed in #30830 (and this issue duplicates #30531).

We assume that in Bootstrap, links without targets imlement one of our components—thus should have a `class`.
