### ISSUE TITLE
Creating 'col' class automatically

### ISSUE THREAD

**Issue by mayur-ekbote** [twbs/bootstrap#31398]
Currently, make-col requires a positive argument. However, it seems there is no way to let the column grow to fill the entire width (as shown in https://getbootstrap.com/docs/4.0/layout/grid/#setting-one-column-width )

```
<div class="container">
  <div class="row">
    <div class="col">
      1 of 3
    </div>
    <div class="col-6">
      2 of 3 (wider)
    </div>
    <div class="col">
      3 of 3
    </div>
  </div>
  <div class="row">
    <div class="col">
      1 of 3
    </div>
    <div class="col-5">
      2 of 3 (wider)
    </div>
    <div class="col">
      3 of 3
    </div>
  </div>
</div>
```

make-col-auto creates a column that fits the content width.

**Comment by Wowosz** [comment]
What do you mean as "Grow to entire width" ? Just use create single col, it should take all entire width.

**Comment by mayur-ekbote** [comment]
If there are two columns, how do you create "col" using mixin?

make-col has to have an argument between 1 and 12. 
First column is created with the following mixin:

```
.foobar{
    @include make-col-ready(0);
    @include make-col(1);
 }
```

what about the other?

**Comment by mdo** [comment]
A mixin exists for this: `make-col-auto()`.

**Comment by mayur-ekbote** [comment]
Is there a tutorial for it? Simply using make-col-auto() like make-col(1) etc doesn't work

**Comment by laneparton** [comment]
I'm hoping to achieve the same thing. I'd like to use make-col to setup equal width columns like the documentation outlines, but I don't see how it's possible?

https://getbootstrap.com/docs/4.5/layout/grid/#equal-width
