### ISSUE TITLE
Include jQuery examples as well

### ISSUE THREAD

**Issue by igll** [twbs/bootstrap#31402]
It would be great to have all examples of plain JavaScript code with **their jQuery equivalent**. E.g. at https://v5.getbootstrap.com/docs/5.0/components/navs/#via-javascript

At least at https://v5.getbootstrap.com/docs/5.0/getting-started/javascript/#still-want-to-use-jquery-its-possible
showing in parallel the jQuery code with the equivalent plain JavaScript code.

JFYI: I was not able to get `$('[data-toggle="tooltip"]').tooltip()"` working because I don't see its connection with the code at https://v5.getbootstrap.com/docs/5.0/components/tooltips/#example-enable-tooltips-everywhere

**Comment by divya661** [comment]
@XhmikosR  @igll I would like to work on it. Can I be assigned to this task?

**Comment by juniorRubyist** [comment]
I have an example for the instance in question at https://v5.getbootstrap.com/docs/5.0/components/navs/#via-javascript, so I'll make a PR.

**Comment by XhmikosR** [comment]
After discussing this with @mdo on Slack, we'd prefer to have a separate section in docs with a couple of examples and link to it from each component. We believe it's cleaner this way than adding a jQuery example in each component.

So, perhaps a new partial linking to the javascript examples.

**Comment by sdkdeepa** [comment]
Hello! I would like to contribute to this as it is still open. Please let me know

**Comment by GeoSot** [comment]
Based on this documentation section https://getbootstrap.com/docs/5.2/getting-started/javascript/#optionally-using-jquery, I suppose we can close this issue

/cc @mdo
