### ISSUE TITLE
Add sass variables for primary colors

### ISSUE THREAD

**Issue by marlongerson** [twbs/bootstrap#31412]
Currently v5 now includes [all color shades as sass variables](https://v5.getbootstrap.com/docs/5.0/customize/color/#all-colors). This is great, but it would be nice to have shades of our $primary color. Add this to _variables.scss:

```
$primary-100: tint-color($primary, 8) !default;
$primary-200: tint-color($primary, 6) !default;
$primary-300: tint-color($primary, 4) !default;
$primary-400: tint-color($primary, 2) !default;
$primary-500: $primary !default;
$primary-600: shade-color($primary, 2) !default;
$primary-700: shade-color($primary, 4) !default;
$primary-800: shade-color($primary, 6) !default;
$primary-900: shade-color($primary, 8) !default;
```

(Maybe add $secondary, $danger, $success, $info, $warning, $danger, $light, $dark?)

**Comment by mdo** [comment]
Plan is to leave these as names colors for now. Duplicating the variables doesn't seem super useful right now. Happy to revisit with more feedback in the future though!
