### ISSUE TITLE
Give more priority to d-none

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#31426]
Similar to #29880...

We use `d-none` to control visibility of the element by adding/removing this class programmatically. However, it does not work if the element is at the same time using e.g. `d-flex`.

A simple solution to this use-case would be to give `d-none` more priority by putting it at the end of the display utilities. What do you think about that?

**Comment by MartijnCuppens** [comment]
I'm ok with that, feel free to open a PR.
