### ISSUE TITLE
Bootstrap documentation pointing to incorrect resource

### ISSUE THREAD

**Issue by avukonkepeter** [twbs/bootstrap#31430]
Currently the bootstrap documentation site: https://getbootstrap.com/docs points to:

```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
```

as the library files from the official CDN. However accessing the links to these files leads to a xml file as the response (error). This is for both the CSS and JS files.

The official CDN site: https://www.bootstrapcdn.com/ points to v4.5.0 as the version whereas on the documentation, reference is made to v4.5.1 which might be leading to the break in the documentation.

**Comment by XhmikosR** [comment]
Yeah, the CDN takes some time to be updated, please be patient.

**Comment by XhmikosR** [comment]
This was fixed yesterday.

**Comment by avukonkepeter** [comment]
Thanks.
