### ISSUE TITLE
RubyGems main Installations is not Working !

### ISSUE THREAD

**Issue by Korak-997** [twbs/bootstrap#31437]
**On the main page for downloading Bootstrap with [RubyGems](https://getbootstrap.com/docs/4.5/getting-started/download/#rubygems):**

It says to use : ```gem 'bootstrap', '~> 4.5.1'``` or ```gem install bootstrap -v 4.5.1``` 
Unfortunately those versions are yet not available ! 

But by going to the [Readme File ]( https://github.com/twbs/bootstrap-rubygem/blob/master/README.md#a-ruby-on-rails) it seems there the version is 4.5.0. 

Version 4.5.0 is available so i will suggest weather change the versions on the [Main Page](https://getbootstrap.com/docs/4.5/getting-started/download/#rubygems) to 4.5.0 or add that new version into the Rubygems website . 

Thanks

**Comment by XhmikosR** [comment]
It takes some time for RubyGems to be updated. Regardless, we need to release a 4.5.2 later today.

@glebm

**Comment by mdo** [comment]
Resolved I believe.
