### ISSUE TITLE
4.5.1 Breaking change, removed Mixing make-container-max-widths

### ISSUE THREAD

**Issue by Zryru** [twbs/bootstrap#31436]
### Version 4.5.1 made a breaking change removing a mixing 

The mixin is called: `make-container-max-widths`

ERROR LOG:

>>ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: no mixin named make-container-max-widths
        on line 13 of node_modules/@my-components/styles/grid/_grid-container.scss
        from line 1 of C:\~\src\styles.scss
  @include make-container-max-widths();
 >>  -----------^

### OS/environment:
Windows, Angular 9, SCSS/SASS, bootstrap, node-sass

How to reproduce:

`.your-container {
    @include make-container-max-widths();
}`

### stackblitz example
https://stackblitz.com/edit/angular-ivy-2t6deq?file=src%2Fapp%2Fapp.component.scss

**Comment by XhmikosR** [comment]
Fixes in 4.5.2.
