### ISSUE TITLE
Bootstrap 4.5.2 bug/update popper.js out-of-date new way is popperjs/core

### ISSUE THREAD

**Issue by redbeard2** [twbs/bootstrap#31451]
Hello, Co devs,

npm bootstrap 4.5.2 and up 

It is not ready for @popperjs/core

I'm looking for someone to help me fix the bootstrap.js 

as a temporary fix for 

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in 'C:\Users\nodefion\Desktop\Website\Wordpress-Websites\Website-1\thema\wp-content\themes\Dolzon-2\node_modules\bootstrap\dist\js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:101-121
 @ ./src/app.js
 @ multi ./src/app.js ./src/app.scss

Because npm I popper.js not work.

I can delete de  require('popper.js') in the bootstrap.js file

But I want to include the new @popperjs/core

without having to wait a month or 2 for the fix.

Share your thoughts with us

best regards,
Nodefion.com dev team

**Comment by isteiger** [comment]
bootstrap does not support Popper v2 yet, please use 1.16

**Comment by redbeard2** [comment]
> bootstrap does not support Popper v2 yet, please use 1.16

That won't work for our clients we need to have a fix for it npm i popper.js is not working anymore ...

**Comment by isteiger** [comment]
npm i popper.js@1.16.0 should work

**Comment by SeanMGonzalez** [comment]
Yes, popper.js@1.16.0 works, but the rest of the app requires popperjs/core. Without a fix for popper, we would have to downgrade the rest of our apps and likely refactor.

**Comment by Johann-S** [comment]
Bootstrap 4 won't upgrade to Popper.js v2 because of browser compatibility, Bootstrap 5 will support Popper.js v2
