### ISSUE TITLE
Modal is not scrollable in the docs

### ISSUE THREAD

**Issue by rohit2sharma95** [twbs/bootstrap#31459]
[Example for the scrollable modal](https://v5.getbootstrap.com/docs/5.0/components/modal/#scrolling-long-content) in the docs is not scrollable in real :thinking:

![bs-modal](https://user-images.githubusercontent.com/26922866/89777706-d0b6bb80-db29-11ea-85d5-29a7cb754f5d.gif)

**Version:** v5.0.0-alpha1
**OS:** Ubuntu 20.04.1
**Browsers:** Chrome 84 and Firefox 78.0.2

**Comment by Johann-S** [comment]
Hi @rohit2sharma95,

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link.

**Comment by rohit2sharma95** [comment]
@Johann-S 
Here is a [Demo](https://codepen.io/rohit2sharma95/pen/YzqyWwd?editors=1000) to reproduce the issue.

**Comment by Johann-S** [comment]
Yep already fixed here: https://github.com/twbs/bootstrap/pull/31151

Thanks anyway @rohit2sharma95 👍
