### ISSUE TITLE
Bootstrap 5 modal {show: true} fail?

### ISSUE THREAD

**Issue by mjau-mjau** [twbs/bootstrap#31452]
Unless I have misunderstood, shouldn't a modal show immediately when instantiated from JS?
`var myModal = new bootstrap.Modal(document.getElementById('myModal'), {show: true});`

According the docs, `{show: true}` is default anyway.
https://v5.getbootstrap.com/docs/5.0/components/modal/

Yet the modal does not show unless one triggers `myModal.show()`:

```js
var myModal = new bootstrap.Modal(document.getElementById('exampleModal'), {show:true});
myModal.show(); // <- required
```

Codepen
https://codepen.io/mjau-mjau/pen/OJNPGYB

**Comment by Johann-S** [comment]
Hi @mjau-mjau you're right the behavior changed thanks 👍

**Comment by Deckluhm** [comment]
This is still the behavior if you instantiate modal using jQuery tho: https://github.com/twbs/bootstrap/blob/a3f27c67e8e3041858e18ac201a384332be14303/js/src/modal.js#L560

**Comment by rohit2sharma95** [comment]
The only modal was a component in bootstrap that could be shown automatically when it is constructed. All other components require the `show()` method to be called on the instance. So to keep the consistency this change is fine IMO even it was not intended (Now modal also require the `show()` to be called) @Johann-S 

So now the updates are required only in the docs and jQueryInterface 🤔
