### ISSUE TITLE
Bootstrap v4.5.x example starter-template has some syntax errors

### ISSUE THREAD

**Issue by qaz5823091** [twbs/bootstrap#31454]
Operating system and version : ArchLinux Manjaro
Browser and version : Chromium

Issue : 

There are some syntax errors in the example starter-template !

In line  78 : 
```
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
```
There is  a unnecessary slash :
< **\\** /script>

and in line 79 :
Before `</html>` , it missed `</body>`

It's my first time to submit a issue :worried: , please take it easy !

**Comment by Deckluhm** [comment]
You should close this issue and open one in the starter template repo: https://github.com/twbs/bootstrap-npm-starter

**Comment by mdo** [comment]
This snippet of code doesn't exist in either code base as far as I know.
