### ISSUE TITLE
Some kind of calendar or page for future Bootstrap versions/releases/features dates

### ISSUE THREAD

**Issue by terremoth** [twbs/bootstrap#31467]
Initially, I tought something like PHP does on his wiki: https://wiki.php.net/todo/php80  
This would be a good idea for preparing teams to plan and implement Bootstrap 5 and so on.
Sorry if you guys already have this somewhere and maybe I don't know.  
This idea could come in a HYSTORY.md ou TODO.md file or on the main bootstrap website somewhere.

Thanks o/

**Comment by morrissey-ingenious** [comment]
https://github.com/twbs/release

**Comment by mdo** [comment]
I think the release repo covers this. We're pretty flexible overall—v5 is still in development and v4 is still stable and active. No hard dates at this point :).
