### ISSUE TITLE
missing dot '.' on h4 .small css

### ISSUE THREAD

**Issue by Timelessprod** [twbs/bootstrap#31468]
Hi,

I've read the code from [https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css](url) and realize there's a missing dot '.' for the class small on h4 element. It's written "h4 small {...}" instead of "h4 .small {...}".

**Comment by mznet** [comment]
@Timelessprod `h4 small` doesn't seem to be `small` class on h4 element, but for `small` [element](https://www.w3schools.com/tags/tag_small.asp) on h4 element. It's not dot missing.

**Comment by isteiger** [comment]
v3 is end of life, please look at upgrading to v4

**Comment by mdo** [comment]
Closing per above comments.
