### ISSUE TITLE
Collapse dont work as expected if somewhere in document is a element with class "mix"

### ISSUE THREAD

**Issue by SvenBudak** [twbs/bootstrap#31469]
Bootstrap v4.2.1

I have found a problem with collapse. If somewhere is a class in document named `mix` then collapse also close this one. I cant find any informations about this. so i think its a bug...

Just to inform ;)

**Comment by patrickhlauke** [comment]
Please provide a reduced test case. Also, please check using 4.5.2 as 4.2.1 is now quite outdated

**Comment by SvenBudak** [comment]
I realized that the problem was because another script we have implemented in our project: https://www.kunkalabs.com/mixitup/
So this can be closed :)
