### ISSUE TITLE
Can't toggle checkbox button when label contains html elements

### ISSUE THREAD

**Issue by TRowbotham** [twbs/bootstrap#31463]
When the label of a checkbox button contains an HTML element, clicking on the label text will not toggle the checkbox. Clicking in the empty area around the text properly toggles the checkbox. Radio buttons appear to work fine. This works with v4.4.1, so I'm assuming this is a regression from 8b6dd449d7553410dce7ecd2e78580928a6c082f.

- Bootstrap version: 4.5.2
- Operating system: Windows 10
- Firefox Nightly 81 and Edge (Chromium) 84.0.522.52
- Test case: https://jsbin.com/tizopasamu/edit?html,console,output

**Comment by mrlife** [comment]
Confirmed on Safari 14 for macOS.

**Comment by ZarPeter** [comment]
I have a similar problem!
The label encapsulates an input, as well as two span elements. 
The change event is listened to via Javascript.

**Comment by patrickhlauke** [comment]
a workaround for the moment is to make the child elements "invisible" to pointers, so a click goes through to the actual `<label>`.

```
label span { pointer-events: none; }
```

**Comment by ZarPeter** [comment]
Works for me! Many Thanks!

Cheers!

**Comment by mdo** [comment]
This isn't a bug with Bootstrap, as this happens without Bootstrap's CSS being included in Chrome and Safari on Mac. Not sure what to do with this other than maybe a note in our docs. Thoughts on what and where we'd include something? This applies to not just buttons, but any checkbox/radio/label combo it seems.

**Comment by patrickhlauke** [comment]
don't believe that's native behavior, @mdo ... just having a simple

```
<label>
  <input type="checkbox" checked> <span>Check me</span>
</label>
```

works fine (does for me on Win/Chrome and Win/Firefox at least)

I believe it's due to JS in v4 bootstrap that does the whole checking of what element was clicked and applies the CSS to the faked toggle - the JS can't deal with the fact that the event target was not the label directly, but a child element of the label. so it's either a CSS solution as above, or fixing the JS to account for the fact that the click may have originated not on the label, but some child element of label.

**Comment by patrickhlauke** [comment]
i believe this is actually fixed already in 4.5.3 - stackpath.bootstrapcdn doesn't seem to have 4.5.3 at this point for some reason, but try and point your script to https://getbootstrap.com/docs/4.5/dist/js/bootstrap.bundle.min.js in that js bin ... seems to work.

see https://jsbin.com/caxiquloji/1/edit?html,console,output

**Comment by mrlife** [comment]
@patrickhlauke FYI, CDN moved to jsDelivr: https://github.com/twbs/bootstrap/issues/31887

**Comment by patrickhlauke** [comment]
ah yes, in hacking that jsbin i forgot about the move of the CDN.

anyway, the fix that makes this checkbox toggle thing work again was likely this https://github.com/twbs/bootstrap/commit/24572b157793c0d762f56314786df18aba3d6212#diff-a22b41902b9c646b10d73b2e41540b93e2544fd7f3887f9e05035b6901d49e16
