### ISSUE TITLE
pagination color

### ISSUE THREAD

**Issue by Hasan-23** [twbs/bootstrap#31477]
Introduce different pagination color.Currently pagination only support primary color.

Like
**'.pagination .pagination-primary'**

**Comment by Deckluhm** [comment]
I'm pretty sure `.pagination-primary` doesn't exist, `.pagination` is just using the primary color as his color.

The problem of creating color variants of each component is that it increases CSS bundle size (and therefore impacts performances).

**Comment by dev0mhm** [comment]
pagination is most common and most useful features in all **the blog website.**

Hope, we will see this class soon.
`.pagination-colorName`    ( colorName are : -primary, secondary, success, info, warning etc. )

**Comment by SrilalS** [comment]
i agree with @dev0mhm . adding this small feature wont effect CSS bundle size in a huge manner.

**Comment by MauricioHernanCabrera** [comment]
I agree with @dev0mhm, if do you interesting I can to do this pull request

**Comment by dev0mhm** [comment]
aye

**Comment by MauricioHernanCabrera** [comment]
I finished of develop this feature [pagination-color](feature https://github.com/twbs/bootstrap/pull/31482)

**Comment by MauricioHernanCabrera** [comment]
> aye

I finished of develop this feature https://github.com/twbs/bootstrap/pull/31482

**Comment by Deckluhm** [comment]
> adding this small feature wont effect CSS bundle size in a huge manner.

It's not but I don't know how the core team decides about adding (or not adding) that kind of things to library core.

It doesn't look like a popular demand/feature to me so I'm advocating a mixin (you can use to generate colored pagination yourself) without adding this to the core of the lib.

**Comment by MauricioHernanCabrera** [comment]
I have create a pull request with mixin and class with theme colors, If interested, I can just add the mixin

**Comment by MauricioHernanCabrera** [comment]
I have create a pull request with mixin and class with theme colors, If interested, I can just add the mixin @Deckluhm

**Comment by axzx** [comment]
Usually, the pagination should look the same throughout the site.
It would be better to be able to set the color you want in variables.

**Comment by ffoodd** [comment]
Pagination colors are customizable through Sass variables, both [in v4](https://github.com/twbs/bootstrap/blob/5f2480a90ab911babc53039835fe78c6fc12646d/scss/_variables.scss#L797) and [v5](https://github.com/twbs/bootstrap/blob/ed9c481ef4b018f77ebc5108071f2e92e6e8ea1a/scss/_variables.scss#L950).

This has not been requested much, and as @axzx said I'm not sure it should be part of the core.

FWIW, customization might be easier soon whilst v5 moves to CSS custom properties. Using custom properties for pagination colors would make adding variant much easier.

**Comment by MauricioHernanCabrera** [comment]
okasss

**Comment by MusicDev33** [comment]
I agree with @ffoodd, I think it's a good idea to change the color of pagination with CSS variables. I think this is generally a good direction for Bootstrap to keep going in, as it is getting to be rather large.

**Comment by ydmitry** [comment]
If will implement this https://github.com/twbs/bootstrap/issues/29853 with new versions of SCSS we could add new variants with additional colors without Bootstrap code change like:

```
@use '~bootstrap/scss-modular/pagination' with (
  $color: green
);
```

or 

```
@include meta.load-css('~bootstrap/scss-modular/pagination', (
  color: green
));
```

**Comment by mdo** [comment]
Thanks, but for now we'll pass on adding color schemes for this. Would rather implement CSS vars for configuring the colors and direct folks to Sass variables for more.
