### ISSUE TITLE
Typo in bootstrap.css file

### ISSUE THREAD

**Issue by montorino** [twbs/bootstrap#31470]
.was-validated .custom-select:valid ~ .valid-feedback,
.was-validated .custom-select:valid ~ .valid-tooltip, .custom-select.is-valid ~ .valid-feedback,
.custom-select.is-valid ~ .valid-feedback {
  display: block;

Here on ".custom-select.is-valid ~ .valid-feedback {" it looks like there should be ".custom-select.is-valid ~ .valid-tooltip{" because there is already ".custom-select.is-valid ~ .valid-feedback" before in previous line.

**Comment by alecpl** [comment]
This is fixed in most recent version. https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L2286
