### ISSUE TITLE
row class child elements take full width

### ISSUE THREAD

**Issue by saisk73** [twbs/bootstrap#31488]
Browser and version (Chrome Version 84.0.4147.125)
Bootstrap Version: 5.0 alpha
Codepen Link: https://codepen.io/saisk73/pen/vYGKBzm

The child elements of row class takes full width of the screen. 

```
<div class="row">
    <a href="/" class="btn btn-primary btn-sm">Return Home</a>
</div>
```

**Comment by tu4mo** [comment]
Rows are wrappers for columns. You should either remove the row or add the content inside a column.

**Comment by saisk73** [comment]
> Rows are wrappers for columns. You should either remove the row or add the content inside a column.

When we need to center the element using classes row justify-content-center the button takes full width unlike Bootstrap 4 which centers elements inside it.

**Comment by neralex** [comment]
> When we need to center the element using classes row justify-content-center the button takes full width unlike Bootstrap 4 which centers elements inside it.

As t4umo pointed, the class: row is an wrapper for columns. You have to replace the class **row** with **d-flex**:
```
<div class="d-flex justify-content-center p-3">
    <a class="btn btn-primary btn-sm">a small Button</a>
</div>
```

**Comment by mdo** [comment]
Closing per above comments.
