### ISSUE TITLE
Add styling for <select multiple> options

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31501]
When using a single `<select>`, the dropdown menu is generated by the browser, and thus the options cannot be styled. However, when using a `<select multiple>`, the options are actually part of the page content, and can be styled with CSS.

So, can styling for options of `<select multiple>` be added to Bootstrap?

[CodePen](https://codepen.io/techboyg5/pen/XWdKQJR)

**Comment by MartijnCuppens** [comment]
> However, when using a <select multiple>, the options are actually part of the page content, and can be styled with CSS.


Not always, mobile browsers don't show these for example.
         
![image](https://user-images.githubusercontent.com/11559216/90645612-74911d00-e236-11ea-8b6a-e21e50b60a96.png)
![image](https://user-images.githubusercontent.com/11559216/90645838-bb7f1280-e236-11ea-8ed6-df089de20c2f.png)

Actually, the browser decides how this is rendered, it could be risky to provide theming for this, because implementations of the browsers can change over time

**Comment by techboyg5** [comment]
> 
> 
> > However, when using a `<select multiple>`, the options are actually part of the page content, and can be styled with CSS.
> 
> Not always, mobile browsers don't show these for example.
> 
> ![image](https://user-images.githubusercontent.com/11559216/90645612-74911d00-e236-11ea-8b6a-e21e50b60a96.png)
> ![image](https://user-images.githubusercontent.com/11559216/90645838-bb7f1280-e236-11ea-8ed6-df089de20c2f.png)
> 
> Actually, the browser decides how this is rendered, it could be risky to provide theming for this, because implementations of the browsers can change over time

I'm talking about `<select multiple>`, not just a plain `<select>`.

**Comment by ffoodd** [comment]
@techboyg5 Those are screenshots of multiple select on iOS and Android :)

**Comment by techboyg5** [comment]
> 
> 
> @techboyg5 Those are screenshots of multiple select on iOS and Android :)

OK, got it! Let's still add the styling because Firefox and Chromium (desktop) support it.

**Comment by MartijnCuppens** [comment]
> OK, got it! Let's still add the styling because Firefox and Chromium (desktop) support it.

"Support it" is a dangerous term to use here. I know Chrome and Firefox can handle colors differently on single selects for example which introduced this bug:

![image](https://user-images.githubusercontent.com/11559216/90680836-c18ae880-e262-11ea-96bf-250ae4e5b34d.png)

As I said before, the browser decides how the options are rendered. We can't know for sure what the effects on all OS/browser combinations with (dark & light modes) will be now and in the future.

**Comment by techboyg5** [comment]
> > OK, got it! Let's still add the styling because Firefox and Chromium (desktop) support it.
> 
> "Support it" is a dangerous term to use here. I know Chrome and Firefox can handle colors differently on single selects for example which introduced this bug:
> 
> ![image](https://user-images.githubusercontent.com/11559216/90680836-c18ae880-e262-11ea-96bf-250ae4e5b34d.png)
> 
> As I said before, the browser decides how the options are rendered. We can't know for sure what the effects on all OS/browser combinations with (dark & light modes) will be now and in the future.

But with multiple selects, everything works. Color, background color, margin, padding and cursor all work.

**Comment by mdo** [comment]
Safari, Firefox, and Chrome on macOS.

![Screen Shot 2020-08-19 at 1 29 51 PM](https://user-images.githubusercontent.com/98681/90686421-26711f00-e220-11ea-8b9b-8b2a039c04f9.png)

**Comment by techboyg5** [comment]
> 
> 
> Safari, Firefox, and Chrome on macOS.
> 
> ![Screen Shot 2020-08-19 at 1 29 51 PM](https://user-images.githubusercontent.com/98681/90686421-26711f00-e220-11ea-8b9b-8b2a039c04f9.png)

Safari is known for doing things a bit differently. Like transparent black. But on Firefox, Chrome, Edge, Opera, and Vivaldi they all look right.
