### ISSUE TITLE
Vertically center carousel caption

### ISSUE THREAD

**Issue by FreddyCrugger** [twbs/bootstrap#31510]
Hello,

I find something very important missing with Boostrap 4(4.5 in this case), the inability to simply move the captions vertically in the center of the carousel.

Thank you.

**Comment by Hiws** [comment]
There might be a better solution, but you can center it using mostly flex utility classes on the `carousel-caption` div.

```html
<div class="carousel-inner">
  <div class="carousel-item active">
    <img src="http://placehold.it/600x300" class="d-block w-100" alt>
    <div class="carousel-caption d-flex flex-column justify-content-center h-100" style="top: 0">
      <h3>First slide label</h3>
    </div>
  </div>
</div>
```

![chrome_NLQGcnVH3b](https://user-images.githubusercontent.com/7057431/91172942-4d769780-e6dd-11ea-9f73-3fcc7b8aa691.png)

**Comment by FreddyCrugger** [comment]
Thanks, I tried your code, the only problem is that the buttons look like block inside it(stretched out). I tried to add btn-sm classes in the buttons but they still stretch.

**Comment by mdo** [comment]
This is possible with utilities and inline/custom styles as the above comment suggests. It'll be even easier when new position utilities ship in v5.

For now, add `d-flex flex-column justify-content-center` to the `.carousel-caption` and add `top: 0`.

```
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-flex flex-column justify-content-center">
        <h5>First slide label</h5>
        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-flex flex-column justify-content-center">
        <h5>Second slide label</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-flex flex-column justify-content-center">
        <h5>Third slide label</h5>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>
```

In the future, you'll be able to use only utilities with `d-flex flex-column justify-content-center top-0`.

**Comment by saadhossain** [comment]
add an extra class on the carousel caption wrapper dive.
align-items-center.

like this: 
<div class="carousel-caption d-flex flex-column justify-content-center h-100">
     <h1>First slide label</h1>
     <p>Some representative placeholder content for the first slide.</p>
     <div class="btn btn-primary">Book Now</div>
</div>

**Comment by anayet2243** [comment]
thanks a lot
