### ISSUE TITLE
Collapse, pass hidden/show event even when element is already in final state

### ISSUE THREAD

**Issue by seb-witt** [twbs/bootstrap#31511]
OS: Windows 10
Chrome 84
Bootstrap: 5 alpha

Issue or intended?
Hidden/shown, do not trigger when element is already hidden/shown.

I have a usecase where i have a default empty element. I init collapse using js on pageload with toggle: false
Right before an ajax call i have a need to hide the element, you can think of it as

1) empty element
2) button click -> hide collapse
3) ajax, on error listen for hidden event -> show collapse
4) correct error, button click -> hide error
5) confirm page shows with possibility to go back to previous page to edit data

Now for example on step 5, i have to integrate useless code to make step 2-3 work again.
The only way to make this functionality is to clear the error element and call show() again, cause the hidden event is not passed when the element is already hidden
And the same issue applies on pageload, i have to pass "collapse show" instead of only "collapse" in order to make the initial step 2 work

Proposed behaviour:
Pass the final events ( hidden, shown ) when you call hide() / show() on an already hidden/shown element so you not have to clear an element and show it with empty content just to be able to call hide again

Bit in a rush at the moment, so no test case, but it should be easy reproducable by simply making
- element with class "collapse"
- Init collapse on element
- call hide() on the element
- setup a hidden listener to alert something ( which does not work cause event is not passed when already hidden )

Proposed code change - collapse.js ( same for show() )
`    if (this._isTransitioning ||
      !this._element.classList.contains(CLASS_NAME_SHOW)) {
      return
    }`

Seperate this bit of code to return only if transitioning, and instead do another if when it now has class "show" to directly emit the event

Thanks, Seb

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by mdo** [comment]
Please let us know when you have a live demo if this is still an issue and we can reopen to revisit it. Thanks!
