### ISSUE TITLE
Cursor pointer

### ISSUE THREAD

**Issue by Arowne** [twbs/bootstrap#31524]
Hello, i want to ask if we can had the cursor-pointer class  wich i manually implement to each project i think it can be usefull :) !
`
.cursor-pointer {
  cursor: pointer
}
`

**Comment by florianlacreuse** [comment]
I think it will not happen, for good reasons, as explained here:

* https://github.com/twbs/bootstrap/pull/30563
* https://github.com/twbs/bootstrap/issues/23709#issuecomment-571290182

However this change has been made: https://github.com/twbs/bootstrap/pull/31040/.

**Comment by Arowne** [comment]
Thank you for your reactivity !
