### ISSUE TITLE
Add responsiveness for ".fixed-bottom"

### ISSUE THREAD

**Issue by yurikfirst** [twbs/bootstrap#31532]
Hello!
I propose such an idea - to add adaptability of stickers, for fixing any elements like - ".fixed-bottom", not only navbar, also using prefixes **{-sm | -md | -lg | -xl}**. 
For example, it opens when "sm", it turns out like this: **.fixed-bottom-sm**
**And immediately disappears in another place.**
Thank!
P.S. Of course, I could offer an idea in the code, but I lack experience a little ...

**Comment by hashnimmo** [comment]
I was in a similar situation where I needed these type of stickies, so I had to make a new class `sticky-top-lg-none` for the required screen size. But as you have said, it's better to wait for an official response.

**Comment by MauricioHernanCabrera** [comment]
I can do that!

**Comment by GilbertoDev** [comment]
but this idea what fix in the code? could you show us your idea in the code? because fix something with  stickers

**Comment by yurikfirst** [comment]
> I can do that!

Hello! Very interesting, do you have a ready-made code?

**Comment by mdo** [comment]
Let's skip this for now—v5's utilities can be easily expanded, so folks can enable this as they like.
