### ISSUE TITLE
npm run test fail (5.0.0-alpha1)

### ISSUE THREAD

**Issue by bluedge** [twbs/bootstrap#31539]
lint issue when installing 5.0.0-alpha1

- Code cloned from repo (https://github.com/twbs/bootstrap.git)
- `npm install`
- `npm run test`

Error
0 info it worked if it ends with ok
1 verbose cli [ '/Users/nico/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/Users/nico/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@6.14.8
3 info using node@v10.15.3
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle bootstrap@5.0.0-alpha1~pretest: bootstrap@5.0.0-alpha1
6 info lifecycle bootstrap@5.0.0-alpha1~test: bootstrap@5.0.0-alpha1
7 verbose lifecycle bootstrap@5.0.0-alpha1~test: unsafe-perm in lifecycle true
8 verbose lifecycle bootstrap@5.0.0-alpha1~test: PATH: /Users/nico/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/nico/Desktop/test - bt 5/bootstrap/node_modules/.bin:/Users/nico/bin:/Users/nico/.nvm/versions/node/v10.15.3/bin:/usr/local/share/npm/bin:/Applications/MAMP/bin/php/php7.0.15/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
9 verbose lifecycle bootstrap@5.0.0-alpha1~test: CWD: /Users/nico/Desktop/test - bt 5/bootstrap
10 silly lifecycle bootstrap@5.0.0-alpha1~test: Args: [ '-c', 'npm-run-all lint dist js-test docs-build docs-lint' ]
11 silly lifecycle bootstrap@5.0.0-alpha1~test: Returned: code: 1  signal: null
12 info lifecycle bootstrap@5.0.0-alpha1~test: Failed to exec test script
13 verbose stack Error: bootstrap@5.0.0-alpha1 test: `npm-run-all lint dist js-test docs-build docs-lint`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/nico/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/nico/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid bootstrap@5.0.0-alpha1
15 verbose cwd /Users/nico/Desktop/test - bt 5/bootstrap
16 verbose Darwin 19.6.0
17 verbose argv "/Users/nico/.nvm/versions/node/v10.15.3/bin/node" "/Users/nico/.nvm/versions/node/v10.15.3/bin/npm" "run" "test"
18 verbose node v10.15.3
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error bootstrap@5.0.0-alpha1 test: `npm-run-all lint dist js-test docs-build docs-lint`
22 error Exit status 1
23 error Failed at the bootstrap@5.0.0-alpha1 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Deckluhm** [comment]
It works fine on my machine:

- **Ubuntu** 20.04.1
- **Node** 10.17.0
- **NPM** 6.11.3

**Comment by bluedge** [comment]
Still not working on mine
**OSX** 10.15.6
**Node** 10.15.3
**NPM** 6.14.8

**Comment by mdo** [comment]
Our tests pass here on our repo, so it seems like this is another problem outside our codebase.
