### ISSUE TITLE
Wrong link in 4.5.1 release description

### ISSUE THREAD

**Issue by djibe** [twbs/bootstrap#31530]
Hi,
in your awesome 4.5.1 doc release, it looks like there is a small glitch.

Docs
#30957: Add .card-img-bottom example

But this reference is linking to #30957: Nullify custom form states' box-shadow

Thanks.

**Comment by XhmikosR** [comment]
/CC @mdo

I guess we'd need to update the blog post too

**Comment by mdo** [comment]
Removed the change in both spots for now.
