### ISSUE TITLE
Navbar squeezing itself

### ISSUE THREAD

**Issue by hydroper** [twbs/bootstrap#31543]
#### Specs

OS: Windows 10
Browser: Opera 70.0

#### Issue

This [navbar](https://codepen.io/hydroper/pen/rNemYXo) is squeezing (inenr-collapsing, then expading back) its items (_Some item_) when you click on it, on desktop viewport.

#### Expected behavior

No squeezing on desktop viewport.

**Comment by Hiws** [comment]
Remove the navbar collapes  data-attributes from the `<nav>` (`data-toggle="collapse" data-target="#navbarSupportedContent"`).

Don't think they're meant to go on the navbar itself, but a button inside the navbar. Like all examples on the docs has it.
<https://getbootstrap.com/docs/4.5/components/navbar/>

**Comment by hydroper** [comment]
True, I've not perceived this...
