### ISSUE TITLE
v5: flex-wrap classes not working

### ISSUE THREAD

**Issue by fveltmann** [twbs/bootstrap#31541]
The flex-wrap classes in the utilities are not working.

I am importing the bootstrap-grid.scss that imports all the utilities. All the utilities are working then, also the flex classes in general, but the flex-wrap classes are not.

Also checked the compiled css output. No flex-wrap classes.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by fveltmann** [comment]
I have set up a quick angular project on [stackblitz](https://stackblitz.com/edit/angular-import-scss-uzsuhd)

Have double checked on what version this issue occurs and it seems like 4.5.2 ist working fine. This demo has 5.0-alpha1 installed, the grid is imported in the root styles.scss and the simple flex container in app.component.html uses .d-flex and .flex-wrap. Inspecting that container shows, that .d-flex works and .flex-wrap doesn't.
I have no other styles loaded except those from the import bootstrap-grid.

**Comment by mdo** [comment]
A live example would be a reduced test case, not a test app :).

`flex-wrap` wouldn't show anything in your example, either. There's nothing to wrap—no children elements. See our docs for how they work: https://getbootstrap.com/docs/4.5/utilities/flex/#wrap.
