### ISSUE TITLE
Add the ability to download the documentation

### ISSUE THREAD

**Issue by alannt777** [twbs/bootstrap#31547]
I think there should be an option to download the docs as pdf on my local machine

**Comment by coliff** [comment]
I don't think PDFs would really make for a good reference guide if you're at your computer.

If you really need offline access of the Bootstrap docs on your local machine you could checkout: https://devdocs.io/bootstrap~4/. It can download the docs and store them in a service-worker so it works offline and the search functionality works great and it has 1-click copy+paste for the code snippets . I think you'd have a better experience using that than a PDF could.

**Comment by alannt777** [comment]
@coliff Thank you for your suggestion.
