### ISSUE TITLE
v5: <sup> <sub> inconsistent styling

### ISSUE THREAD

**Issue by misterybodon** [twbs/bootstrap#31546]
**Context**
* Booststrap Version: `5.0.0-alpha1/css/bootstrap.min.css`
* Mozilla FIrefox 79.0, either locally or codepen:

**CODE**
```
<ul class='breadcrumb'>
  <li class='breadcrumb-item'>
    <sub>0</sub>H
    <sup>0</sup>
  </li>
</ul>
```

* Minimal working example: https://codepen.io/misterybodon/pen/gOrWqVN

**Output**
![screen](https://user-images.githubusercontent.com/64955604/91525555-ad498a00-e8f9-11ea-9e5d-441ed90ef5ae.png)

**Comment by mznet** [comment]
sub tag should be located at lower of a character and sup tag should be located at upper. like below the image.
![image](https://user-images.githubusercontent.com/9622730/91699028-a008f580-ebae-11ea-9431-a74436243275.png)

This problem can be occurred when the parent element has `display:flex` property.

**Comment by mznet** [comment]
@misterybodon The inconsistency could be fixed if `align-items-baseline` class is added to the parent tag which has `display: flex`

**Comment by Rachitatrey** [comment]
<sub>0</sub><var>H<sup>0</sup>
this may work you should try this

**Comment by Rachitatrey** [comment]
actually i am new to it ...
so what did you ask actually about the code that symbolise H or something else ...
if no please correct me

**Comment by mdo** [comment]
See #31692.
