### ISSUE TITLE
Tooltips won't be destroyed when applied to button that will be disabled on click

### ISSUE THREAD

**Issue by thomasreiser** [twbs/bootstrap#31549]
**Bootstrap v5.0.0-alpha1**

Tested with latest Chrome, Chromium-Edge, Firefox.

When the click event of e.g. a button disabled the clicked element, and if the tooltip is visible at this time, the tooltip will never be destroyed, even after the mouse lefts the elements or triggers other tooltips.

https://codepen.io/thomasreiser/pen/ExKXYqb

**Comment by webwamp** [comment]
hi @thomasreiser you should add this to your code:

`.on("click mouseleave mousedown").tooltip("hide);`

**Comment by thomasreiser** [comment]
Hi @webwamp,

thank you.
But well, this seems to be

**a)** a workaround for a functionality I expect to work internally in the Bootstrap JS framework

and

**b)** some jQuery stuff I do no more use/support. Of course I can handle this with VanillaJS, but imho this is a bug to be fixed by Bootstrap itself. I am also not sure if this still works for Bootstrap v5.

**Comment by webwamp** [comment]
i have this same issue from Bootstrap v3.5 to now and this problem is in target blank links, so i fix this problem by this way
i contact to Bootstrap in twitter but not fix that, if you find a way to fix this, please write here to others can use that.

**Comment by mdo** [comment]
From https://v5.getbootstrap.com/docs/5.0/components/tooltips/#overview:

> Tooltips for .disabled or disabled elements must be triggered on a wrapper element.

Not ideal, I know, but unless @Johann-S has an idea for a fix, this is the behavior we have.
