### ISSUE TITLE
v5: Variable for button hover contrast

### ISSUE THREAD

**Issue by codiak** [twbs/bootstrap#31544]
https://github.com/twbs/bootstrap/blob/a1708ec2a38d331c4c9eacac08ce9c9839649476/scss/mixins/_buttons.scss#L10

Howdy! Would it be possible to either darken or accept a custom variable for the button hover contrast?

For the meantime, we can override the "button-variant" mixin, but it seemed like an element others might find useful to adjust as well.

Thanks!

**Comment by ydmitry** [comment]
But this is the variable as a mixin argument, or do you mean to call `button-variant` with global variable `$btn-hover-background` ?

**Comment by mdo** [comment]
Closing for #32290 since that one's more specific.
