### ISSUE TITLE
Accordion example in docs is missing accordion class

### ISSUE THREAD

**Issue by daveerwin1** [twbs/bootstrap#31551]
The bootstrap 4 docs show an accordion example here: https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example

The div that has id="accordion" should also have class="accordion".
Here's a couple screenshots showing the difference:

<img width="850" alt="accordion-1" src="https://user-images.githubusercontent.com/44251817/91611446-27950100-e930-11ea-9840-7a0e1215eab1.png">
<img width="849" alt="accordion-2" src="https://user-images.githubusercontent.com/44251817/91611453-2bc11e80-e930-11ea-829c-d9853e4e538b.png">

**Comment by patrickhlauke** [comment]
that example you link to does have the `class="accordion"` ?

**Comment by daveerwin1** [comment]
oh, that was quick, thanks to the person that fixed it!
