### ISSUE TITLE
v4: Replace the :visible pseudo selector 

### ISSUE THREAD

**Issue by dilyanpalauzov** [twbs/bootstrap#31550]
In version 4.5 dropdowns use the :visible sizzle-jquery-pseudo-selector.

Please remove the dependency on :visible, so that Bootstrap can run with JQuery, that does not include the sizzle selector (but uses the browser native selector).

Jquery without sizzle leads to less code, transmitted to the browser.

**Comment by mdo** [comment]
We dropped jQuery in v5. v4 will keep it.

**Comment by dilyanpalauzov** [comment]
Proposed patch: https://github.com/twbs/bootstrap/pull/33678
