### ISSUE TITLE
Dev tools return: Source map error : 404 and at times Pagespeed returns error as well 

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#31552]
I noticed this error when pagespeed was unable o generate a report for www.tomastestart.cl
Here's the full console message:

> Source map error: Error: request failed with status 404
> Resource URL: https://www.tomastestart.cl/wp-content/cache/autoptimize/css/autoptimize_d8b7c6de4d903332029cd43a14773f66.css
> Source Map URL: bootstrap.min.css.map

That site is using Bootstrap v4.4.1 and same happens with another v4.x site, while www.otzerling.com using v3.x is not having the error.

**Comment by mdo** [comment]
Without knowing more about your setup, this sounds like you might be missing the source map. You can delete the reference to it and not include it if that's what you want. I don't recall if the older versions of Bootstrap had an issue with source maps, but maybe someone on the team recalls.

Beyond that, I don't think we have this issue in our docs, so hard to do much more here.

Thoughts @twbs/css-review?

**Comment by XhmikosR** [comment]
Yeah, it's a user implementation issue.
