### ISSUE TITLE
Generic form control size classes

### ISSUE THREAD

**Issue by napei** [twbs/bootstrap#31553]
In v5, would there be a chance of cleaning up the size modifiers for `form-control`?

I've never actually had to use small form controls before, until now because I'm working on some form-heavy pages with >50 fields, and wishing to make everything small. I've noticed a few little things that make it a tiny bit painful to work with.

Currently if I want a small text input it's `form-control form-control-sm` which makes sense, but is twice as much typing. If I want a form control I can specify `form-control`, and if I want a small form control I can specify `form-control-sm`. It's also a little confusing using the same type of convention as responsive breakpoints, so `form-control form-control-sm` might imply that `form-control-sm` does something at the `sm` breakpoint, which it doesn't. Maybe using specific terms like `form-control-small` would be easier to understand?

For example: 

```html
<input type="text" class="form-control form-control-sm" placeholder="Example" />
```
could become

```html
<input type="text" class="form-control-small" placeholder="Example" />
<!--OR-->
<input type="text" class="form-control small" placeholder="Example" />
<!--OR-->
<input type="text" class="form-control-sm" placeholder="Example" />
```

This could also be extended to what was once the `form-group` style, with a div surrounding a label and an input. You could specify `small` or something similar to the parent element and elements inside would use small sizing. This could become generic enough to perhaps be applied form-wide, say if I wanted my entire form to use small controls.

```html
<div class="mb-3 small">
  <label for="formGroupExampleInput" class="form-label">Example label</label>
  <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
</div>
```

```html
<form class="small">
  <div class="mb-3">
    <label for="formGroupExampleInput" class="form-label">Example label</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
  </div>
  <div class="mb-3">
    <label for="formGroupExampleInput" class="form-label">Example label</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
  </div>
</form>
```

```scss
.small {
  label,
  input {
    // small css properties
  }
}

```

For labels too there's no `form-label-sm` class you have to use `col-form-label-sm` which makes no sense because I should be able to use small labels outside column layout. Further to that `col-form-label-sm` requires no use of `form-label col-form-label-sm` like `form-control` does, making it inconsistent.

I'm no expert on scss or any of this, but just my suggestion as I've noticed it's a littly clunky.

As an ultimate extension to this, controlling global default control size would be great too through a scss variable. And even getting rid of the need for `form-control` alltogether using a scss variable would be cool too, because if I want to use bootstrap then unless I specifically need it why would I want default form UI. It could always still be available with a `default` class if it's specifically wanted. 

Hope this all makes sense :smile:

**Comment by mdo** [comment]
Specificity, especially with our base and modifier classes, is an important aspect to Bootstrap's approach. As you've mentioned, we used to have `.form-group` size classes as well, which meant we had at least two ways of doing things.

> As an ultimate extension to this, controlling global default control size would be great too through a scss variable.

What kind of variables would you like to see? Our Reboot stylesheet could perhaps be modified to do more here, provided we didn't create too much overlap with our actual `.form-control`s. We also have a number of global options already, so adding more where appropriate is straightforward enough :).

**Comment by napei** [comment]
I think sizing should be moved to more semantic names like small, medium and large. That way you can specify a form control size like `form-control small` or `form-control medium`. This could be extended to other things too that use the same small/medium/large types. It also saves confusion with `form-control form-control-sm` which is, perhaps, too specific, more typing, and can be confused with breakpoints. This could also be extended to buttons, and anything else that is resized. 

I'm not sure how a default size could be specified, but to explain it, I would think it would be similar to base font-size, but more specific to only form elements, or only buttons. Perhaps a `I want every form control to be this size by default` whether that's too much complexity I don't know.

Most definitely, a normalisation of size specification would be great to avoid confusion and extra work.

**Comment by MauricioHernanCabrera** [comment]
I can do that, if you are interested

**Comment by mdo** [comment]
I hear you on wanting something more generic instead of specific classes per component/item, but that is against the approach we use elsewhere. For now, closing as a won't fix.

**Comment by napei** [comment]
> I hear you on wanting something more generic instead of specific classes per component/item, but that is against the approach we use elsewhere. For now, closing as a won't fix.

@mdo Understandable and thanks for looking into it.

Along with the original issue, I also mentioned consistency amongst the `form-label` sizing.

> For labels too there's no `form-label-sm` class you have to use `col-form-label-sm` which makes no sense because I should be able to use small labels outside column layout. Further to that `col-form-label-sm` requires no use of `form-label col-form-label-sm` like `form-control` does, making it inconsistent.

Sorry if that got lost inside the long post, but wondering if at least that could be looked into?
