### ISSUE TITLE
Modal behind backdrop when parent is position:sticky

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#31573]
I have a menu with `.position-sticky` and a few menu buttons. One of them opens a `.modal` -- a sibling element due to the nature of my development environment. The modal's `.modal-backdrop` is appended to the `body` and covers the modal.

Here is a similar issue and PR punted from v3 to v4 but never used. The PR simply appended the backdrop to the modal's parent instead of the `body`. https://github.com/twbs/bootstrap/issues/16148 -- fixed by https://github.com/twbs/bootstrap/pull/16432

Proposal to fix in v4 and v5.

Current `modal.js` line 355
```
document.body.appendChild(this._backdrop)
```

Proposed `modal.js` line 355
```
this._element.parentNode.appendChild(this._backdrop)
```

- Operating system and version (Windows, macOS, Android, iOS): macOS 10.15.6
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser): Safari 13.1.2

**Comment by mdo** [comment]
I feel like this isn't something we'd change. Thoughts @Johann-S?

**Comment by mrlife** [comment]
Are there pros for appending `.modal-backdrop` to `body` and/or cons for appending to parent?

**Comment by mdo** [comment]
Closing as stale.
