### ISSUE TITLE
Broken link from Readme to download the latest release

### ISSUE THREAD

**Issue by Klemart3D** [twbs/bootstrap#31585]
"Download the latest release" link from Readme to `https://codeload.github.com/twbs/bootstrap/zip/v5.0.0` is broken and returns `404: Not Found`

Operating system and version: macOS Catalina
Browser and version: Firefox 80.0

**Comment by hashnimmo** [comment]
> "Download the latest release" link from Readme to `https://codeload.github.com/twbs/bootstrap/zip/v5.0.0` is broken and returns `404: Not Found`

Confirmed and same here.

**Comment by ffoodd** [comment]
You're right, it's missing `-alpha1` in filename. This'll be fixed soon, thanks :)
