### ISSUE TITLE
Tooltip: placement undefined error after 4.0 migration

### ISSUE THREAD

**Issue by luisfdgon** [twbs/bootstrap#31581]
Hi,

After migrating bootstrap from 3.3.6 to 4.5 tooltip stopped working with the following error:

"placement is undefined"

After some research I figured out that I cannot use 'auto top' any more. 

According to documentation https://getbootstrap.com/docs/4.5/migration/#global-changes "Moving from Beta 3 to our stable v4.x release, there are no breaking changes, but there are some notable changes."
For me this is a breaking change...

Still, I couldn't find anywhere in documentation mentioning that we cannot use 'auto top' any more. 

That said, this is a bug that need to be fixed. 

Thanks!

Operating system: Ubuntu Server 16.04
Browser version: (Chrome 85, Firefox 80.0)

**Comment by Deckluhm** [comment]
I think you misinterpreted "Beta 3" as "v3 beta" while it means "v4 beta 3" (v4, 3rd iteration of beta).

For projects (like Bootstrap) following Semantic Versioning (https://semver.org), increment of the MAJOR part of the version (1st number) means there are breaking changes.

**Comment by luisfdgon** [comment]
Hi Deckluhm,

Thank you for your contribution. You might be correct although cannot find anywhere mentioned that it's not possible to use 'auto top' any more. So, I'm I doing something wrong? is this the expected behaviour or is a bug?

Thank you.

**Comment by Deckluhm** [comment]
The tooltip component was fully rebuilt using Popper (https://popper.js.org) in v4 and it probably changed some things (that's pretty weird their is no note about that in the migration guide).

I don't really know about your exact issue (`auto top`) but maybe you can look at the `popperConfig` config (https://getbootstrap.com/docs/4.5/components/tooltips/#options) you can use to customize Bootstrap default tooltip behavior.

**Comment by mdo** [comment]
Moving from v3 to v4 is a decently large step, and as mentioned there are tons of breaking changes between major versions. The comments here are likely the most helpful.
