### ISSUE TITLE
public_html/platform/storage/passport/oauth-public.key" does not exist or is not readable

### ISSUE THREAD

**Issue by niang77** [twbs/bootstrap#31591]
i get this error for my site (tiensira.org)
please help if you have solution

**Comment by patrickhlauke** [comment]
Nothing to do with Bootstrap I'm afraid.

**Comment by niang77** [comment]
what is a solution ?

    Le vendredi 4 septembre 2020 à 17:06:16 UTC+2, Patrick H. Lauke <notifications@github.com> a écrit :  
 
 


Nothing to do with Bootstrap I'm afraid.

**Comment by niang77** [comment]
no have solution with my problem
