### ISSUE TITLE
download a version 3  

### ISSUE THREAD

**Issue by niang77** [twbs/bootstrap#31593]
hello 
i need to download a version 3 to ushaihidi
thanks

**Comment by patrickhlauke** [comment]
https://getbootstrap.com/docs/3.4/getting-started/#download

**Comment by niang77** [comment]
thanks for all

    Le vendredi 4 septembre 2020 à 17:37:42 UTC+2, Patrick H. Lauke <notifications@github.com> a écrit :  
 
 


https://getbootstrap.com/docs/3.4/getting-started/#download
