### ISSUE TITLE
Responsive font-weight-bold

### ISSUE THREAD

**Issue by a61829437** [twbs/bootstrap#31609]
Is there a way to make font-weight bold responsive?

For instance: 
```
<p class="font-weight-bold font-weight-md-normal"> This is bold, but on >= medium it is normal.... </p>
```

Or apply bold to only >= medium width: 
```
<p class="font-weight-md-bold"> This text is only bold on >= medium... </p>
```

**Comment by MauricioHernanCabrera** [comment]
I can do that @a61829437

**Comment by ydmitry** [comment]
I think this should be disabled by default and turn on by variable. If we add this and many-many styles with breakpoints it can bloat CSS utilities

**Comment by ffoodd** [comment]
FYI in v5 it'd simply require you to add `responsive: true` in our [`font-weight` utility map](https://github.com/twbs/bootstrap/blob/f3e81f8cae3e4917dab9d7812dd376ac4ba10f87/scss/_utilities.scss#L362), and build dist on your own.

**Comment by mdo** [comment]
Yes, we're not going to add this ourselves.
