### ISSUE TITLE
The CSS does not validate and throws error in chrome

### ISSUE THREAD

**Issue by djeraseit** [twbs/bootstrap#31605]
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css

**Comment by Deckluhm** [comment]
What do you mean "does not validate"? And what error?

Please provide a reproduction case or at least more info.

**Comment by patrickhlauke** [comment]
assuming this is about https://jigsaw.w3.org/css-validator/ note that the validator there is wildly out-of-date (only validates up to CSS Level 3 stuff) and is ignorant of things like CSS custom variables and a few recent CSS properties.
