### ISSUE TITLE
BUG: Focus box shadow variable not used when input is validated 

### ISSUE THREAD

**Issue by StemateF** [twbs/bootstrap#31604]
Hello there,
I noticed that the `$input-focus-box-shadow` is not used when the input has the `.is-valid` or `.is-invalid` class.
Instead it has a hardcoded shadow ` box-shadow: 0 0 0 $input-focus-width rgba($color, .25);`.

Maybe there is a way to extract this into a variable so users can customize it.

Thanks for the great work on this.

**Comment by mdo** [comment]
Not sure we can since if it's a global variable, `$color` would be undefined. Open to ideas though if there's something I'm not seeing immediately :).
