### ISSUE TITLE
Bug in modal.js: defaultPrevented called on jQuery.Event instead of isDefaultPrevented()

### ISSUE THREAD

**Issue by joakimriedel** [twbs/bootstrap#31615]
Tried to prevent the `hidePrevented.bs.modal` event using `e.preventDefault()`, but it won't work since the code checks for `defaultPrevented` instead of `isDefaultPrevented()`. 

The bug on this line: https://github.com/twbs/bootstrap/blob/v4.5.2/js/src/modal.js#L237

All the other events are properly using `isDefaultPrevented()` see for example this line: https://github.com/twbs/bootstrap/blob/v4.5.2/js/src/modal.js#L117

Here's a simple fix: https://github.com/twbs/bootstrap/compare/v4.5.2...joakimriedel:joakimriedel/defaultPrevented?expand=1

Patch for 4.5.2 ?

**Comment by joakimriedel** [comment]
As a hacky workaround, I now do `Object.assign(e, { defaultPrevented: true })` together with `e.preventDefault()` to prevent the animation.

**Comment by XhmikosR** [comment]
@Johann-S can you have a quick look please? Also please add the v4/v5 labels if this applies to both versions.

**Comment by Johann-S** [comment]
it's just in v4 here, in v5 we use `defaultPrevented` because we use Vanilla JS

**Comment by XhmikosR** [comment]
@joakimriedel can you please make a new PR against the v4-dev branch along with a test?

**Comment by joakimriedel** [comment]
@XhmikosR sure https://github.com/twbs/bootstrap/pull/31696

**Comment by XhmikosR** [comment]
Thanks for the bug report and the PR. #31696 was merged.
