### ISSUE TITLE
Website Jongeleen.nl

### ISSUE THREAD

**Issue by Jongeleen** [twbs/bootstrap#31617]
Dear Bootstrap dev team.

I am currently trying to get in touch the person who owns the domainname Jongleen.nl. I'am running a company with the same name and noticed that the website has been under development for about 4 years now. Since i dont know if the website will ever come online, i was wondering if i could get the info from the one who currently owns the domainname. So i can notify him/her of my interest. I really hope u can help me since the domain was registerd via your website. 

Thank you in advance!

Maarten van der Voort
Jongeleen Infra

**Comment by patrickhlauke** [comment]
This has nothing to do with bootstrap (we don't know, nor control, who uses bootstrap on their site/holding pages)
