### ISSUE TITLE
Are toolchips and modals incompatible?

### ISSUE THREAD

**Issue by famibee** [twbs/bootstrap#31628]
Are tool chips and modals incompatible?
ツールチップスとモーダルは両立できない？

 Currently, tool chips and modals use the same attribute "data-toggle", so it seems that they cannot be used at the same time.
　現状では、ツールチップスとモーダルが同じ属性「data-toggle」を使用するので、同時に使用できないようです。

```HTML
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#...">
BUTTON
</button>

<a href="#" data-toggle="tooltip" title="Some tooltip text!">Hover over me</a>
```

 Isn't it possible to make one into a form of "data-modal" that allows you to specify "data-toggle =" modal "" and "data-target" at the same time?
　片方を例えば「data-toggle="modal"」と「data-target」指定を一度に出来る「data-modal」という形にできないでしょうか。

```HTML
<button type="button" class="btn btn-primary" data-modal="#..." data-toggle="tooltip" title="Some tooltip text!">
BUTTON
</button>
```
 I think it is possible to add this method while keeping the current specifications.
　現状の仕様を残しつつ、この方式の追加、でも可能だと思います。

**Comment by mdo** [comment]
For now this stays the as it's built—you'll want to wrap the buttons in another element and put the tooltip on that, then the modal trigger on the button.
