### ISSUE TITLE
Backdrop not closed with Bootstrap Dialog any more (in 4.5.1)

### ISSUE THREAD

**Issue by jogibear9988** [twbs/bootstrap#31622]
I use this Bootstrap Dialog:
https://github.com/GedMarc/bootstrap4-dialog

When I update to Bootstrap 4.5.1 or 4.5.2 open a dialog and click on the backdrop, the backdrop stays open.

When I switch back to bootstratp 4.5.0 it works

**Comment by Deckluhm** [comment]
I don't think this is Bootstrap responsibility to stay compatible with 3rd-party plugins but the other way around (unless there is a undocumented breaking change?).

**Comment by jogibear9988** [comment]
see http://jsfiddle.net/qu6r3shn/1/

**Comment by jogibear9988** [comment]
@Deckluhm maybe someone can help out to find the root of the problem.

**Comment by jogibear9988** [comment]
seems to be fixed with updateing bootstrap in bootstrap dlg
