### ISSUE TITLE
.table-responsive class not functioning when wrapped in display:grid

### ISSUE THREAD

**Issue by euro** [twbs/bootstrap#31620]
### Bootstrap @ 4.5.2

- Operating system and version (macOS 10.15.6)
- Browser and version (Chrome 85.0.4183.102, Firefox 80.0.1, Safari 13.1.2)
- A reduced test case has been provided: [CodePen](https://codepen.io/euro/pen/jOqzqQL)

If an element upstream has the property ```display: grid``` applied the ```.table-responsive``` class is not functioning as expected.

**Comment by mdo** [comment]
Not much we can do about this in Bootstrap since we can't know the parent or root's display and react to that. https://css-tricks.com/preventing-a-grid-blowout/ has your answer though, add `min-width: 0` to `.container`.

**Comment by spathon** [comment]
Could be worth adding a notice/warning in the v5 docs?
