### ISSUE TITLE
Problem with header and menu on iOS

### ISSUE THREAD

**Issue by prsolucoes** [twbs/bootstrap#31637]
Hi,

This is a great library.

I'm using latest version and on iOS browser the header buggy and menu go out of screen, scroll don't work and a lot of problems .

On android it work nice.

Demo:

https://y2aa.prsolucoes.com/

![image](https://user-images.githubusercontent.com/395096/92999728-ab86e580-f4f9-11ea-8d57-1354b6863093.png)

Thanks.

**Comment by mdo** [comment]
This is because of your flex and height classes on the body. You'll need to rearrange some of that to solve this issue.
