### ISSUE TITLE
Request, loading screen and image lazy load 

### ISSUE THREAD

**Issue by AlisterBaroi** [twbs/bootstrap#31647]
I don't know if this request already exists or not, but it would be great to have functionalities to have **custom loading screen animations** before the page loads, and having **image lazy loading** to reduce traffic requests and loading time in bootstrap 5 websites (using JS).

**Comment by coliff** [comment]
Spinners can be used for nice looking loading screens - especially If they are centered horizontally and vertically.
https://getbootstrap.com/docs/4.5/components/spinners/

Native lazy-loading of images is available in nearly all modern browsers now with no JavaScript required. Just add `loading="lazy"` to the img.
https://caniuse.com/loading-lazy-attr

**Comment by mdo** [comment]
Agreed with @coliff.
