### ISSUE TITLE
bootstrap version 4 custom download like version 3

### ISSUE THREAD

**Issue by amarg26** [twbs/bootstrap#31645]
we can download custom download for bootstrap version 3 `https://getbootstrap.com/docs/3.4/customize/` but same thing is missing for version 4, It will be really great if we can custom download and their will be easy for us for page speed optimization.Thanks.

**Comment by XhmikosR** [comment]
Sorry, we have no plans to bring this back. There's @Johann-S's project you can use, but it seems it's a little outdated: https://johann-s.github.io/bs-customizer/
