### ISSUE TITLE
Add GitHub Issue Button to docs pages

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31655]
Hi there!
I made a dropdown button for GitHub Pages sites called the GitHub Issue Button.
Are you interested in replacing your basic "View on GitHub" button with my custom button?
If yes, then I can start a PR.
https://github.com/techboyg5/php-scripts/blob/master/gh-issue-button.md

**Comment by mdo** [comment]
Cool! But no thanks :).

**Comment by techboyg5** [comment]
> 
> 
> Cool! But no thanks :).

Why?

**Comment by mdo** [comment]
We don't need a dependency or script for this button.

**Comment by techboyg5** [comment]
> We don't need a dependency or script for this button.

Got it!
