### ISSUE TITLE
Skeleton loading screens

### ISSUE THREAD

**Issue by StanMenten99** [twbs/bootstrap#31665]
Hi,

I would love to see something like a skeleton loading screen for specific elements (paragraphs, buttons, images, headings etc).
The reason why I want this is because its very handy to show the user that there is something loading, without placing spinners.

I'm aware of other solutions, but it would be nice to see it included in Bootstrap.

Examples:
[Example CSS tricks](https://css-tricks.com/building-skeleton-screens-css-custom-properties/)
[Example Youtube](https://miro.medium.com/max/700/0*ABjKedHjIe8El9RJ.png)

Hope my request is clearly and understandable.

Anyway, thanks in advance!
Stan.

**Comment by TheDevJulian** [comment]
Oh I would love that feature! Good thinking!

**Comment by juhas96** [comment]
Hey, I want to contribute on this issue.

**Comment by jaumesala** [comment]
I've created a pull request, share your thoughts #31859

**Comment by StanMenten99** [comment]
Is there any update about this, will this be a feature in near releases?

**Comment by jaumesala** [comment]
> Is there any update about this, will this be a feature in near releases?

Take a look at #31859
