### ISSUE TITLE
Email input validation is not working correctly

### ISSUE THREAD

**Issue by elnath78** [twbs/bootstrap#31669]
Replicated the issue on Windows:FF/Chrome I have a really simple form with a "email" field in it, here is the relative markup:

`<input type="email" class="email requiredField form-control" id="email" aria-label="Email Address" aria-describedby="email" autocomplete="email" placeholder="Email Address" required>              `

When I enter partial email address it is still being validated, example: `jon@doe` now if I add a `.` it is again invalid, but the partial email is still being validated, as also for example: `a@b` is considered a valid e-mail address.

**Comment by ffoodd** [comment]
Bootstrap does not provide form validation script, only some styles.

If you didn't implement any validation by yourself, this is most likely your browsers  which is validating your form.

**Comment by elnath78** [comment]
@ffoodd but what is the `class=email` used for then?

**Comment by ffoodd** [comment]
There's no class `email` in Bootstrap. So I don't know!

**Comment by elnath78** [comment]
ok thanks!
