### ISSUE TITLE
[v5] Negative margins not generated properly from negativify-map() function

### ISSUE THREAD

**Issue by istvanp** [twbs/bootstrap#31678]
**Problem:**
The generated negative margins (once enabled via the `$enable-negative-margins` variable) generate values that are all the same regardless of the specified size. `m*-n1` through `m*-n11` give me `-0.25rem` as a value.

**Bootstrap version:**
`5.0.0-alpha1`

**Gemfile.lock:** (relevant parts)
```
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
```

**Problematic Code:**
https://github.com/twbs/bootstrap/blob/390ce245cc8612707d6bd136214ebfbc2860e5c6/scss/_functions.scss#L41
The value is coerced into a negative value but somehow it's not done as expected after the first iteration (compiler bug?).

**Proposed Fix:**
```scss
      $result: map-merge($result, ("n" + $key: -#{$value}));
```

**BEFORE Fix:**
Output of `$result` using `@debug` in the `negativify-map()` function:
```
/node_modules/bootstrap/scss/_functions.scss:44 DEBUG: ("n1": -0.25rem, "n2": -0.25rem, "n3": -0.25rem, "n4": -0.25rem, "n5": -0.25rem, "n6": -0.25rem, "n7": -0.25rem, "n8": -0.25rem, "n9": -0.25rem, "n10": -0.25rem, "n11": -0.25rem)
```

**AFTER Fix:**
```
/node_modules/bootstrap/scss/_functions.scss:44 DEBUG: ("n1": -0.25rem, "n2": -0.5rem, "n3": -1rem, "n4": -1.8rem, "n5": -3rem, "n6": -4rem, "n7": -5rem, "n8": -7.5rem, "n9": -10rem, "n10": -12.5rem, "n11": -15rem)
```

I can submit a PR with my suggested fix if this is a confirmed bug.

**Comment by mdo** [comment]
Enabling the option locally and running `npm run css` outputs the correct sizes to me:

```diff
diff --git a/dist/css/bootstrap-utilities.css b/dist/css/bootstrap-utilities.css
index 0d5b3fde1..6e41cb5e5 100644
--- a/dist/css/bootstrap-utilities.css
+++ b/dist/css/bootstrap-utilities.css
@@ -667,6 +667,156 @@
   margin-left: auto !important;
 }
 
+.m-n1 {
+  margin: -0.25rem !important;
+}
+
+.m-n2 {
+  margin: -0.5rem !important;
+}
+
+.m-n3 {
+  margin: -1rem !important;
+}
+
+.m-n4 {
+  margin: -1.5rem !important;
+}
+
+.m-n5 {
+  margin: -3rem !important;
+}
```

**Comment by istvanp** [comment]
🤔 it did seem more of a issue with scss or something in the environment I'm generating this in... What's the sassc version you tried this with @mdo? I'm using https://github.com/rails/webpacker to generate mine though - not straight up.

**Comment by mdo** [comment]
We use node-sass currently, but the normal Dart Sass compiler works fine, too, I believe.

**Comment by mdo** [comment]
Happy to keep discussing here, but going to preemptively close since this sounds outside the realm of our tooling :).

**Comment by elemis** [comment]
Having the exact same issue. Couldn't understand how to fix it though?
