### ISSUE TITLE
Wrong border radius on custom-switch using SASS files

### ISSUE THREAD

**Issue by eduardduran** [twbs/bootstrap#31674]
When using SCSS files to build, the custom-switch, the border-radius property is not parsed properly.

Specifically, the `.custom-switch .custom-control-label::before` selector has a property value of `border-radius: 1rem / 2;`, where it should be `border-radius: 0.5rem;`

From what I've been able to debug, the [`_custom-forms.css`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L184) file contains several properties values of `border-radius: $custom-switch-indicator-border-radius;`, where it should be `@include border-radius($custom-switch-indicator-border-radius);`. Changing that locally fixes the rounded border custom switch.

**Comment by mdo** [comment]
The computed value in our compiled CSS is correct. Not sure what issue you're running into with how you're compiling, but using our build tools, there's no issue that we can resolve.
