### ISSUE TITLE
`tfoot` has a bottom border even without table-bordered

### ISSUE THREAD

**Issue by DataTables** [twbs/bootstrap#31672]
## Summary

* Operating system and version: Ubuntu 20.04 (reproducible in others though)
* Browser and version: Chrome 85, Firefox 80
* Reduced test case
  * With Bootstrap 5 alpha 1: https://jsfiddle.net/w5kpx96q/1/
  * With current build: https://jsfiddle.net/1rLt56wu/
* Possibly related to 28480, although I don't see any direct mention of it there and that is closed with this issue still present.

## Description of issue

Using a `<table>` with a `<tfoot>` cases there to be a border at the bottom of the table, which is asymmetrical to the top (which does not have a matching border):

![image](https://user-images.githubusercontent.com/278219/93349253-29ffc200-f82f-11ea-9a1e-aa0d1df002b3.png)

This is caused by:

```css
  > :not(caption) > * > * {
    padding: $table-cell-padding-y $table-cell-padding-x;
    background-color: var(--bs-table-bg);
    background-image: linear-gradient(var(--bs-table-accent-bg), var(--bs-table-accent-bg));
    border-bottom-width: $table-border-width;
  }
```

In the table.scss file.

I feel this is a bug in v5 since the `thead` does not have a matching top border. By my reading of the docs, I'd expect only a table with `table-bordered` to have a border at the bottom of the footer.

**Comment by mdo** [comment]
As shown in https://v5.getbootstrap.com/docs/5.0/content/tables/, we have bottom borders on basically every table, so I don't see this as a bug at this time. Happy to revisit in the future though if more folks disagree :).
