### ISSUE TITLE
Navbar/Dropdown display issue, not always displaying dropdown background (BS 4.5.2); Usage of position: static

### ISSUE THREAD

**Issue by herbalite** [twbs/bootstrap#31683]
- OS W10, Android
- Browsers latest FF, Chrome, Edge
- This is a very specific case, that I couldn't reproduce with a simple JSbin. if you need more info, I can give you the URL to one of my customers site to have a look at it. 

The page in question needs to show a compacted navbar (hamburger icon visible) and the navbar has a background-color.

Can't even take a screenshot, because when taking a screenshot, the browser windows loses focus, and the dropdown menu display shows correctly!  This even happens when I am switching to the browsers dev tools. ( Awe and wonder... )

So I spent a day debugging on this one. Here the summary of my findings. 

In one sentence: **Why use position: static in navbar-nav at all?** 

The details:
In _drowdown.scss there is
```
.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: $zindex-dropdown;
...
```
in _navbar.scss there is
```
.navbar-nav {
...
  .dropdown-menu {
    position: static;
    float: none;
  }
}
```
The position: static, according to W3C does the following https://www.w3.org/wiki/CSS_static_and_relative_positioning?viewType=Print&viewClass=Print#Static_positioning
> This is really a misnomer. Boxes with position:static are not really “positioned” at all in the CSS sense. They are simply laid out in the order they occur in the markup and take up as much room as they need—this is the default behavior you get when you don’t apply any CSS at all to your HTML.

The important thing here is, **position: static** drops among others, the top and left position and the z-index. The dropping of the z-index one is causing the issue I've been seeing.  z-index only works on positioned elements, **position: static** removes that. I removed position: static in the _navbar.scss file shown above, and everything is working fine. Which begs the question, that is highlighted further above.

**Comment by mdo** [comment]
This styles the dropdowns so that they don't pop out of the navbar. Longstanding behavior in Bootstrap since v3 or so I believe. The main point here is to keep dropdowns as accessible as possible and avoid positioning issues.
