### ISSUE TITLE
Book table of contents list

### ISSUE THREAD

**Issue by Psixodelik** [twbs/bootstrap#31698]
Hi

This may seem interesting. Often on sites with goods, a block of characteristics is used. In them, the name and meaning are separated by a dotted line.

Maybe add some markup for this type of list? I made an example with a list like this

https://codepen.io/Psixodelik/pen/qBZJERv

**Comment by mdo** [comment]
Inclined to pass on this—looks like a great thing to keep as an add-on or in custom CSS :). Thanks though!
