### ISSUE TITLE
[feature][v5] rounded-* class Utilities for Responsive

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#31697]
Round borders for switch the media breakpoints.
https://github.com/twbs/bootstrap/issues/22001#issue-207903078

also, have not possible currently `.rounded-left` with `.rounded-lg`.

`<img src="..." class="rounded-left rounded-lg" alt="...">`

Please improve and add in V5.

**Comment by mdo** [comment]
With v5, you can enable responsive classes on any utility class.
