### ISSUE TITLE
4.5.2 Modal with Fade never loads with prefers-reduced-motion

### ISSUE THREAD

**Issue by lwrcase** [twbs/bootstrap#31690]
Bootstrap 4.5.2
Modal

Modal never seems to load when using .fade on a browser/environment that has 'prefers-reduced-motion' enabled. The backdrop loads but the modal never finishes adding the 'display: block;' to the modal object, leaving a screen with just the backdrop loaded.

Adding 'display: block;' to the modal object displays the modal but you aren't able to interact with the modal: ie. Cancel button doesn't work, escape doesn't close.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by lwrcase** [comment]
Examples can be seen here:
https://www.wrappixel.com/demos/admin-templates/material-pro/material/ui-modals.html

Bootstrap: 4.5.2
Browser: Chrome latest
OS: Windows 10 Ent 1803

**Comment by mdo** [comment]
That's a problem for that project. Modals show up fine for us on our docs site: https://getbootstrap.com/docs/4.5/components/modal/#live-demo. Just tested this—works for us, not for Material. I suggest filing an issue with them.
