### ISSUE TITLE
Initially collapsed button with radio - error

### ISSUE THREAD

**Issue by michalhorak** [twbs/bootstrap#31713]
When initially collapsed button contains radio input, on the load of page button.js triggers error "Uncaught TypeError: Cannot read property 'checked' of null" (line 174). Seems check whether 'input' is undefined at the beginning of if(... could solve it.

- Bootstrap version: 4.5.2
- Operating system: Windows 10
- Chrome 85.0.4183.102 x64
- Test case: https://jsbin.com/yofuviv/edit?html,output
(described error appears in console of developer tools)

**Comment by mdo** [comment]
This isn't a super clear example—there's a good amount of unrelated HTML in there. Recreating this from scratch the way I'd do it, I see no errors. https://codepen.io/emdeoh/pen/yLOQjvo?editors=1100

Some of the problems I see:

- Mixing button classes with dropdown classes
- Rogue `.collapse` class in there
- Custom classes not found in Bootstrap
- Mismatched CSS and JS versions of Bootstrap

If you can reduce it down to completely vanilla Bootstrap code and still have a problem, we'd be happy to look again.
