### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by SankarBala** [twbs/bootstrap#31714]
Other css framework have so many color variant where bootstrap has only primary, secondary, info, warning, danger, dark, light. 
But it is  extremely need more colors. 
So I am requesting to add more than 50 colors in bootstrap.

**Comment by mdo** [comment]
We have tons of colors, but we don't create classes for every single one.

v4: https://getbootstrap.com/docs/4.5/getting-started/theming/#color
v5: https://v5.getbootstrap.com/docs/5.0/customize/color/
