### ISSUE TITLE
Add Negative margin

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#31719]
Negative margin is absent in bs-5.
Add negative margin feature in bootstrap 5 like bootstrap 4.

for example,
```
m-n(1-5)
mt-n(1-5)
mr-n(1-5)
mb-n(1-5)
ml-n(1-5)
```

Thanks in advance.

**Comment by mznet** [comment]
@ExpertHasan you can use negative margin if you set `enable-negative-margins`  to `true`. Default value is set to false.
https://v5.getbootstrap.com/docs/5.0/utilities/spacing/#negative-margin

**Comment by ExpertHasan** [comment]
set default value **true** from false.

**Comment by mdo** [comment]
You're more than welcome to do that yourself :).

**Comment by apeksha0513** [comment]
not working
