### ISSUE TITLE
Spacing Not Working for Ordered List

### ISSUE THREAD

**Issue by hashnimmo** [twbs/bootstrap#31721]
I'm trying the spacing utility for this ordered list. I will use all `-n3` for this test case. It works for every other resolution except for the `ml-sm-n3` class. It only works for `sm` resolution if I use `ml-n3` instead of `ml-sm-n3` class.

Here's the code;
```
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
</head>
<body>
<p>Spacing utility</p>
<div>&nbsp;&nbsp;&emsp;&darr;</div>
<ol class="ml-sm-n3 ml-md-n3 ml-lg-n3 ml-xl-n3">
<li>Item</li>
<li>Item 2</li>
</ol>
</body>
</html>
```

Preview;
![bs-spacing](https://user-images.githubusercontent.com/24617729/93853659-e21ae800-fcd1-11ea-9afa-ad1dc38197e8.png)

I'm using;
Bootstrap: Version 4.4.1
Operating system: Microsoft Windows 10 Version 2004 (OS Build 19041.508) (64-bit)
Browser: Microsoft Edge Version 85.0.564.51 (64-bit)

What am I doing wrong here?

**Comment by razh** [comment]
That appears to be an iPhone SE (1st generation) or iPhone 4 style device (power button on top), which has a horizontal width of 320px (640px with a 2&times; device pixel ratio).

The `sm` breakpoint is at 576px: https://getbootstrap.com/docs/4.5/layout/grid/#grid-options

**Comment by hashnimmo** [comment]
> That appears to be an iPhone SE (1st generation) or iPhone 4 style device (power button on top), which has a horizontal width of 320px (640px with a 2× device pixel ratio).
> 
> The `sm` breakpoint is at 576px: https://getbootstrap.com/docs/4.5/layout/grid/#grid-options
Thank you. Anyway, in **Web Browser** > **Inspect**, there are devices from Moto G4 to iPhone X. Which Bootstrap resolution class can I use to cover those type of devices?

**Comment by razh** [comment]
`.ml-n3` would work.

There's no need for all of the other breakpoints since each class applies to all breakpoints above:

```html
<ol class="ml-n3 ml-sm-n3 ml-md-n3 ml-lg-n3">
```

Is the same as:

```html
<ol class="ml-n3">
```

**Comment by mdo** [comment]
> It only works for `sm` resolution if I use `ml-n3` instead of `ml-sm-n3` class.

That's by design. See the above comments for more information on this as well. Beyond that, you're using negative margin to override the default `padding-left` on `<ol>`s when you could change the padding instead.

**Comment by hashnimmo** [comment]
> `.ml-n3` would work.
> 
> There's no need for all of the other breakpoints since each class applies to all breakpoints above:
> 
> ```
> <ol class="ml-n3 ml-sm-n3 ml-md-n3 ml-lg-n3">
> ```

> That's by design. See the above comments for more information on this as well. Beyond that, you're using negative margin to override the default `padding-left` on `<ol>`s when you could change the padding instead.

Thank you very much for these clarifications.
