### ISSUE TITLE
card-header-tabs has no other background color demo

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#31732]
https://v5.getbootstrap.com/docs/5.0/components/card/#card-styles
https://v5.getbootstrap.com/docs/5.0/components/card/#navigation

**Comment by mattonit** [comment]
I think they're not necessary there

**Comment by YlmRdm** [comment]
Yes, Not necessarily as @mattonit said.

**Comment by XhmikosR** [comment]
@mdo your call if this is valid

**Comment by mdo** [comment]
Closing as a won't fix.
