### ISSUE TITLE
Responsive font sizes section - Version mentioned in docs site is still 4.3

### ISSUE THREAD

**Issue by dbybanez** [twbs/bootstrap#31736]
"Bootstrap v4.3 ships with the option to..."

Should it be v4.5 instead of v4.3? 

[https://getbootstrap.com/docs/4.5/content/typography/#responsive-font-sizes](https://getbootstrap.com/docs/4.5/content/typography/#responsive-font-sizes)

**Comment by mdo** [comment]
Could be updated to use the version, or perhaps more helpful, "As of v4.3.0, Bootstrap ships..."

**Comment by dbybanez** [comment]
Your version is better. Thanks! @mdo

**Comment by XhmikosR** [comment]
Fixes in #31734
