### ISSUE TITLE
Bootstrap collapse is not working if target element Id starts with number

### ISSUE THREAD

**Issue by imnikhilp** [twbs/bootstrap#31745]
Steps to reproduce.
Use following mark up to create collapse component and click on link with href link.

```
<p>
  <a class="btn btn-primary" data-toggle="collapse" href="#1collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Link with href
  </a>
</p>
<div class="collapse" id="1collapseExample">
  <div class="card card-body">
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
  </div>
</div>
```
document.querySelector(selector) is used in following method which will not work number.Need to use  document.getElementById(selector) for this instance

```
getSelectorFromElement(element) {
    let selector = element.getAttribute('data-target')

    if (!selector || selector === '#') {
      const hrefAttr = element.getAttribute('href')
      selector = hrefAttr && hrefAttr !== '#' ? hrefAttr.trim() : ''
    }

    try {
      return document.querySelector(selector) ? selector : null
    } catch (err) {
      return null
    }
  },

```

**Comment by ffoodd** [comment]
Thanks for reporting :) 

[ID starting with numbers are invalid CSS selectors](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier), [as mentionned in our docs](https://getbootstrap.com/docs/4.5/getting-started/javascript/#selectors). There're [tons of issues like this](https://github.com/twbs/bootstrap/issues?q=is%3Aissue+ID+number+is%3Aclosed) with explanations.

However we now that HTML5 now allows this kind of values, so [there's an open issue to link into](https://github.com/twbs/bootstrap/issues/31099). I'm closing this one as duplicate but you may follow #31099 for updates.
