### ISSUE TITLE
Bootstrap 4.5.2 - input type=image with class form-control has padding applied.

### ISSUE THREAD

**Issue by skotfred** [twbs/bootstrap#31766]
Only noted while building out a demo of some permutations of input tags for a legacy website, found that the form-control class  from _forms.scss adds the padding for .form-control as  padding: .375rem .75rem;
 
Recommend excluding for just the input[type=image] with:

```
input[type=image].form-control {
  padding:0;
}
```

Example:

```
<input type="image" src="https://www.giantgeek.com/images/button-login.gif" class="form-control" />
```

**Comment by skotfred** [comment]
![input-image-border-bootstrap](https://user-images.githubusercontent.com/959745/94367110-1e6b9100-00a2-11eb-940d-0c0ffb5713b3.png)
Example - the red button is for comparison as an <input type="reset" class="form-control" value="Reset" />

**Comment by mdo** [comment]
I don't see this element get used that often, but I _feel_ like that's what I'd expect if you're using Bootstrap's form components. This feels pretty consistent with the rest of our form controls, and I wouldn't expect something edge-to-edge or custom beyond that.

Thoughts @twbs/css-review?

**Comment by patrickhlauke** [comment]
this goes back to the discussions about how opinionated the reset should be, and whether or not some of its styles should be moved to the explicit `.btn` class.

**Comment by ffoodd** [comment]
My two cents: in that case, simply use `.p-0` or do not use `.form-control` at all: `input[type="image"]` just works like `img`, there's probably no need for our form styles, is it?

**Comment by MartijnCuppens** [comment]
> I don't see this element get used that often, but I feel like that's what I'd expect if you're using Bootstrap's form components. This feels pretty consistent with the rest of our form controls, and I wouldn't expect something edge-to-edge or custom beyond that.

Agreed 

If you don't want `<input type="image" />` to look like `.form-control`, than just leave out the `.form-control` class?

**Comment by patrickhlauke** [comment]
as sorry, missed that the original had `.form-control`. in that case yes, agree...if you don't want the standard styling for `.form-control`, don't use `.form-control` - no need to special-case it (again, because some authors may well want the image plus the standardised/normalised padding)

**Comment by MartijnCuppens** [comment]
Gonna close it now, guess we gave enough feedback here 🙂
