### ISSUE TITLE
Media (not @madia) is missing in bootstrap 5 alpha

### ISSUE THREAD

**Issue by Molla143** [twbs/bootstrap#31763]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Feature requests must include:
media

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by patrickhlauke** [comment]
no idea what this even means, sorry
