### ISSUE TITLE
Modal still open instead of explicit close statement

### ISSUE THREAD

**Issue by hanatole** [twbs/bootstrap#31764]
I am using Chrome on Ubuntu 20.4. Bootstrap 4.5 and jQuery 3.5.1
I aim open the modal while ajax is loading the data and close it as soon as the request is completed. But unfortunately, the modal still opened whereas the request is completed. This is my code

`$.ajax({
        url: "data/devices.json",
        method: "GET",
        dataType: "JSON",
        success: function(devices) {
            for (let device of devices) {
                $("#devices").append(
                    $(`<option value=${device.type}>${device.type}</option>`)
                );
            }
            $("#loadingModal").modal("hide");
        },
        beforeSend: function() {
            $("#loadingModal").modal("show");
        }
    });`

**Comment by rafalp** [comment]
If this is happening on your dev machine, it looks like a race condition where  modal didn't finish transition to `open` state when `hide` is called.

**Comment by hanatole** [comment]
Thanks Rafalp. I were developing an preloading system. I fortunately added a timer, and everything went well. But I don't know if there is a better way to do it.

**Comment by mdo** [comment]
> If this is happening on your dev machine, it looks like a race condition where modal didn't finish transition to `open` state when `hide` is called.

Sounds about right from our end. If there were a live demo, maybe someone could weigh in here with more options. You're also welcome to ask around in the Discussions or Slack channel for other ideas.
