### ISSUE TITLE
"badge rounded-pill" is surrounded by underscores (_) 

### ISSUE THREAD

**Issue by KGS-Rastede** [twbs/bootstrap#31765]
- Linux: nginx, Windows: WAMP
- Happens in all Browsers

You can see the issue here:

![grafik](https://user-images.githubusercontent.com/17048988/94364436-77025480-00c9-11eb-8706-38309b3ee587.png)

As you can see there is a small underscore (_) between the pills.

This is my code:

```
    <?php foreach ($item->tags()->split() as $tag) : ?>
        <a href="<?= url('blogs', ['params' => ['tag' => $tag]]) ?>">
            <span class="badge rounded-pill bg-info"><?= $tag ?></span>
        </a>
    <?php endforeach ?>
```

So the issue is inside this:

`            <span class="badge rounded-pill bg-info"> FOO </span>`

**Comment by patrickhlauke** [comment]
either apply the bade classes to the links directly (see https://getbootstrap.com/docs/4.5/components/badge/#links) or remove any space in the outer link (that "underline" is the link styling), since your links currently have extra whitespace

```
<a href="<?= url('blogs', ['params' => ['tag' => $tag]]) ?>"><span class="badge rounded-pill bg-info"><?= $tag ?></span></a>
```
