### ISSUE TITLE
Show cancel icon for input type search

### ISSUE THREAD

**Issue by apiweb** [twbs/bootstrap#31787]
I think it would be quite interesting to go back to showing (or at least allowing the user to configure via sass) the display of the cancel button of the input type search.
This type of functionality helps a lot for those who access search-based systems on mobile.

![image](https://user-images.githubusercontent.com/5881027/94501030-3133b200-01d7-11eb-9e9d-fa643405ad54.png)

**Comment by hashnimmo** [comment]
I have a search in my site and the cancel button shows on mobile and everywhere.
```
<input class="form-control" type="search" name="q" placeholder="Search" aria-label="Search" />
```
![search](https://user-images.githubusercontent.com/24617729/94508767-5274bc80-0230-11eb-80c9-9974ef7c93b3.png)

I'm using;
Bootstrap: Version 4.4.1
Operating system: Microsoft Windows 10 Version 2004 (OS Build 19041.508) (64-bit)
Browser: Microsoft Edge Version 85.0.564.51 (64-bit)

**Comment by Deckluhm** [comment]
It's not a feature provided by Bootstrap but by **some** browsers.

It's present on Chromium based browsers but not on Firefox.

**Comment by patrickhlauke** [comment]
Yup, exactly what @Deckluhm said. Bootstrap is not, as far as I'm aware, suppressing this actively in any way?
