### ISSUE TITLE
Confusion on the "nextWhenVisible()" method on Carousel Component

### ISSUE THREAD

**Issue by JudgedPluto** [twbs/bootstrap#31788]
Hi everyone, I am currently using bootstrap 5 and while browsing through documentation, I have found that in the carousel component documentation, `carousel.prototype.nextWhenVisible()` function is not accurate with its description. Although `carousel.prototype.to()` function seems to be matched with the description (which is not found in the carousel component documentation, but can be found in the code).

I think that the function has been mismatched with the description, that have led me to a confusion.

The section that I am referring to:
https://v5.getbootstrap.com/docs/5.0/components/carousel/#methods

**Comment by Johann-S** [comment]
Nice catch @JudgedPluto 👍 

You're right, the `to` method is missing and `nextWhenVisible` description is wrong

**Comment by JudgedPluto** [comment]
Cool, Thank you for the clarification :)

**Comment by suliskh** [comment]
@JudgedPluto @XhmikosR @Johann-S Is it okay for me to work on this?

**Comment by XhmikosR** [comment]
There's no need to ask for such things. Just grab an issue and submit a PR when ready.

I'm thinking we should add this statement somewhere...

**Comment by cankitm** [comment]
#31809
