### ISSUE TITLE
Setting $input-btn-font-size scss variable in pixels does not work

### ISSUE THREAD

**Issue by thampinox** [twbs/bootstrap#31782]
- Windows 10 Pro 19041.508
- Chrome 85.0.4183.102
- Bootstrap 4.5.0

I am trying to override $input-btn-font-size variable and set it to 12px, but in the output, the actual font-size for inputs and buttons is set to 0.75rem which is 11.25px. The responsive font sizes option is disabled.

**Comment by MartijnCuppens** [comment]
You've set your font size of `html` to `15px` which influences the value of rem. If you want to change your default font size, you should alter th `body` font size.

**Comment by thampinox** [comment]
Thanks for the reply @MartijnCuppens . 
This is not really obvious, I thought `font-size` changes automatically only when `$enable-responsive-font-sizes` is set to `true`.
Is there any way to set static `12px` font-size for btn using variables without modifying `html` `font-size`?

**Comment by mdo** [comment]
Nearly everything in Bootstrap is designed to use relative units for easy scaling and sizing. You can shoe-horn in pixels, but it'll take a decent amount of work since we make the assumption of `rem` quite globally.
