### ISSUE TITLE
Cannot work with modals programmatically: “Uncaught TypeError: this._getConfig is not a function”

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap#31807]
I’m having difficulties working with modals programmatically in alpha 2. I’m trying to close one using `modalInstance.hide()`, but I get the following error in the console:

> Uncaught TypeError: this._getConfig is not a function

Reduced test case: https://codepen.io/martinbean/pen/VwaJbrQ

**Comment by XhmikosR** [comment]
Your code seems wrong. You need to do `var modalInstance = new bootstrap.Modal(modal);`
