### ISSUE TITLE
Form selects not styled correctly on Safari with Sass

### ISSUE THREAD

**Issue by 0xTim** [twbs/bootstrap#31819]
It looks like the form selects are missing webkit/mozilla specific stylings when installing Bootstrap 5 via Sass. It seems fine when viewing selects on the Bootstrap website, but when installing locally they don't look correct. 

Diffing the generated CSS on getbootstrap.com and what I had locally it looks like the code here https://github.com/twbs/bootstrap/blob/main/scss/forms/_form-select.scss#L25 is missing:

```scss
-moz-appearance: none;
-webkit-appearance: none;
```

Operating System:
macOS 10.15.6
Browser Version
Safari 14

Happy to do a PR if I'm not missing anything!

**Comment by patrickhlauke** [comment]
Bootstrap uses an autoprefixer. I guess it's not part of your build process? https://v5.getbootstrap.com/docs/5.0/getting-started/build-tools/#autoprefixer

**Comment by 0xTim** [comment]
🤦 yep missed that step in the docs, thanks for point it out

**Comment by Luke-SF** [comment]
I downloaded Bootstrap 5.3 and within it I see

```
button,
[type=button],
[type=reset],
[type=submit] {
  -webkit-appearance: button;
}
```

but if a button has background-color it needs -webkit-appearance:none 

to override the Safari styles. I don't think this is fixed?

**Comment by patrickhlauke** [comment]
> if a button has background-color it needs `-webkit-appearance:none` to override the Safari styles. I don't think this is fixed?

do you have an actual test case showing your problem? because I'm not seeing any issues in Safari when going through getbootstrap.com's documentation examples with buttons that have both a custom background colour, *and* use `-webit-appearance: button`
