### ISSUE TITLE
Remove js/dist/index.js and js/dist/index.js.map since they seem unused?

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#31823]
/CC @Johann-S the thing we were discussing the other day

**Comment by XhmikosR** [comment]
/CC @Johann-S the thing we were discussing the other day

**Comment by Johann-S** [comment]
we should do the same in v5 too

**Comment by XhmikosR** [comment]
I'm mostly concerned about v4 because it really seems unused and the map file is definitely redundant and not auto-generated. Just keep in mind we don't want any accidental breaking changes in v4, though :)

**Comment by XhmikosR** [comment]
Fixed by #32001
