### ISSUE TITLE
Range Inputs are not styled on mobile.

### ISSUE THREAD

**Issue by mehmetalianil** [twbs/bootstrap#31833]
The range sliders are not styled at all on Chrome and Edge on mobile on Bootstrap 4.5
It is partially styled on Firefox mobile, lacking the blue strip. 

I was planning to make a simple demo, but realized that it is already visible on bootstrap 4.5 documentation on forms.
I thought that it would be enough for a demo. 

I tried them on: 
Edge version 45.08.2.5074
Chrome 85.0.4183.127
Firefox 81.1.1 (Build #2015764545)

On a: Samsung SM-G611F
Android 9 on Kernel 3.18.91-15922581

Chrome: ![image](https://user-images.githubusercontent.com/551129/95026631-0348e480-0693-11eb-8f91-6fea786c99db.png)
Edge: ![image](https://user-images.githubusercontent.com/551129/95026651-296e8480-0693-11eb-8364-f37aa65a65d7.png)
Firefox: ![image](https://user-images.githubusercontent.com/551129/95026639-0c39b600-0693-11eb-8f87-8d168b22f10b.png)

**Comment by mehmetalianil** [comment]
I checked on Bootstrap 5 alpha page that it is rendered correctly there.

**Comment by mdo** [comment]
@coliff's comment is correct.

**Comment by mehmetalianil** [comment]
Thanks, that helped.
