### ISSUE TITLE
Add a namespace for classes

### ISSUE THREAD

**Issue by Sir-Genius** [twbs/bootstrap#31837]
How do you feel about adding the namespace for classes as you have done it for CSS variables?

**Comment by florianlacreuse** [comment]
Duplicate of #29547.

It won't happen: https://github.com/twbs/bootstrap/issues/29547#issuecomment-561025723

You will need to handle it with post-processors.

**Comment by florianlacreuse** [comment]
I think we can close this one?

**Comment by mdo** [comment]
Closing for now. Maybe in a future major release.
