### ISSUE TITLE
Circle Buttons in Bootstrap 4/5

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [twbs/bootstrap#31850]
I think adding circle buttons to Bootstrap 4/5 will be a great Idea. I think you should go with the default colors, hovering and click effects. In my opinion it would be a pretty neat concept to have them. Let me know what you think.

Here's the CodePen prototype
https://codepen.io/michaelg_2k05/pen/qBNBpPQ

**Comment by florianlacreuse** [comment]
You can use `.rounded-circle` on `.btn`, do you need more?

**Comment by MichaelGrigoryan25** [comment]
That sounds great! Also what do I need?🙂

**Comment by mdo** [comment]
We'll pass on adding something extra for this right now. Feels right to have this be custom CSS for now.
