### ISSUE TITLE
Clicking outside vertically centered Modal with static backdrop results in unwanted vertical scrollbar glitch

### ISSUE THREAD

**Issue by cduff** [twbs/bootstrap#31857]
Steps to reproduce:

- Navigate to https://getbootstrap.com/docs/4.5/components/modal/#static-backdrop.
- Click 'Launch static backdrop modal' button.
- Open dev tools and inspect displayed modal div with `modal-dialog` class.
- Add `modal-dialog-centered` class to this div (the documented way to create a vertically centered modal).
- Exercise the static backdrop feature by clicking outside the modal.
- Note that the modal's scale animation causes a vertical scrollbar to pop in and out of existence. This also pushes the modal left creating an undesirable UI experience.

Reproduced using:

- Bootstrap version: 4.5
- OS: Windows 10
- Browser: Chrome 86.0.4240.75

**Comment by cduff** [comment]
I'm currently working around this issue by modifying Bootstrap's CSS so that the scale animation occurs on the `modal-content` div rather than the usual `modal-dialog` div.

Sass:
``` sass
.modal {
  .modal-content {
    transition: transform 0.3s ease-out;
  }
}
.modal.modal-static {
  .modal-dialog {
    transform: none;
  }
  .modal-content {
    transform: scale(1.02);
  }
}
```

**Comment by XhmikosR** [comment]
Please make a CodePen. Also:

1. does the issue happen in v5 too?
2. feel free to submit a PR with your proposed fix

**Comment by XhmikosR** [comment]
@ffoodd @rohit2sharma95 can you guys reproduce with with 4.6.0 and or v5?

**Comment by rohit2sharma95** [comment]
For me, it only happens when you increase the value for scale a bit (In the official docs as well)

**Comment by XhmikosR** [comment]
@ffoodd @mdo this might be a CSS issue judging by @cduff's workaround above

**Comment by cduff** [comment]
I can no longer reproduce this so have removed the workaround from my project. Should the issue be closed?

**Comment by rohit2sharma95** [comment]
It only happens when opening dev tools and manually increasing the value for the scale (Closing the dev tools does not reproduce it). Generally, it cannot be reproduced.
