### ISSUE TITLE
Lots of errors when following Tooling Setup for BS5

### ISSUE THREAD

**Issue by MontyHu** [twbs/bootstrap#31862]
I downloaded Bootstrap 5 alpha 2 directly from the Bootstrap website. Then [followed the directions](https://v5.getbootstrap.com/docs/5.0/getting-started/build-tools/) for Tooling Setup in the docs (macOS version 10.15.7).

When I ran **npm start**, I got a pile of errors. Not really sure what most of it means, but, here it is: 

	Montys-MacBook:bootstrap monty$ sudo npm start

	> bootstrap@5.0.0-alpha2 start /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> npm-run-all --parallel watch docs-serve

	> bootstrap@5.0.0-alpha2 watch /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> npm-run-all --parallel watch-*

	> bootstrap@5.0.0-alpha2 docs-serve /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> hugo server --port 9001 --disableFastRender

	Start building sites … 

	> bootstrap@5.0.0-alpha2 watch-css-main /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> nodemon --watch scss/ --ext scss --exec "npm-run-all css-lint css-compile css-prefix"

	> bootstrap@5.0.0-alpha2 watch-css-docs /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> nodemon --watch site/assets/scss/ --ext scss --exec "npm run css-lint"

	> bootstrap@5.0.0-alpha2 watch-js-main /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> nodemon --watch js/src/ --ext js --exec "npm-run-all js-lint js-compile"

	> bootstrap@5.0.0-alpha2 watch-js-docs /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> nodemon --watch site/assets/js/ --ext js --exec "npm run js-lint"

	[nodemon] 2.0.4
	[nodemon] to restart at any time, enter `rs`
	[nodemon] watching path(s): js/src/**/*
	[nodemon] watching extensions: js
	[nodemon] starting `npm-run-all js-lint js-compile`
	[nodemon] 2.0.4
	[nodemon] to restart at any time, enter `rs`
	[nodemon] 2.0.4
	[nodemon] watching path(s): scss/**/*
	[nodemon] watching extensions: scss
	[nodemon] starting `npm-run-all css-lint css-compile css-prefix`
	[nodemon] to restart at any time, enter `rs`
	[nodemon] watching path(s): site/assets/scss/**/*
	[nodemon] watching extensions: scss
	[nodemon] starting `npm run css-lint`
	[nodemon] 2.0.4
	[nodemon] to restart at any time, enter `rs`
	[nodemon] watching path(s): site/assets/js/**/*
	[nodemon] watching extensions: js
	[nodemon] starting `npm run js-lint`

	> bootstrap@5.0.0-alpha2 css-lint /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> npm-run-all --continue-on-error --parallel css-lint-*

	> bootstrap@5.0.0-alpha2 js-lint /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .

	> bootstrap@5.0.0-alpha2 js-lint /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .

	> bootstrap@5.0.0-alpha2 css-lint /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> npm-run-all --continue-on-error --parallel css-lint-*

	> bootstrap@5.0.0-alpha2 css-lint-stylelint /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> stylelint "**/*.{css,scss}" --cache --cache-location .cache/.stylelintcache

	Oops! Something went wrong! :(

	ESLint: 7.10.0

	ESLint couldn't find the config "../.eslintrc.json" to extend from. Please check that the name of the config is correct.

	The config "../.eslintrc.json" was referenced from the config file in "/Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap/build/.eslintrc.json".

	If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! bootstrap@5.0.0-alpha2 js-lint: `eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the bootstrap@5.0.0-alpha2 js-lint script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/monty/.npm/_logs/2020-10-10T05_54_52_012Z-debug.log
	[nodemon] app crashed - waiting for file changes before starting...

	> bootstrap@5.0.0-alpha2 css-lint-vars /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	> fusv scss/ site/assets/scss/

	Oops! Something went wrong! :(

	ESLint: 7.10.0

	ESLint couldn't find the config "../.eslintrc.json" to extend from. Please check that the name of the config is correct.

	The config "../.eslintrc.json" was referenced from the config file in "/Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap/build/.eslintrc.json".

	If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! bootstrap@5.0.0-alpha2 js-lint: `eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the bootstrap@5.0.0-alpha2 js-lint script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/monty/.npm/_logs/2020-10-10T05_54_52_358Z-debug.log
	ERROR: "js-lint" exited with 2.
	[nodemon] app crashed - waiting for file changes before starting...
	Built in 8281 ms
	Error: Error building site: "/Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap/site/content/docs/5.0/getting-started/browsers-devices.md:19:4": failed to render shortcode "rf.inline": failed to process shortcode: template: _inline_shortcode/docs/5.0/getting-started/browsers-devices.md/rf.inline:2:4: executing "_inline_shortcode/docs/5.0/getting-started/browsers-devices.md/rf.inline" at <readFile ".browserslistrc">: error calling readFile: file ".browserslistrc" does not exist
	npm ERR! code ELIFECYCLE
	npm ERR! errno 255
	npm ERR! bootstrap@5.0.0-alpha2 docs-serve: `hugo server --port 9001 --disableFastRender`
	npm ERR! Exit status 255
	npm ERR! 
	npm ERR! Failed at the bootstrap@5.0.0-alpha2 docs-serve script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/monty/.npm/_logs/2020-10-10T05_54_52_639Z-debug.log
	ERROR: "docs-serve" exited with 255.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! bootstrap@5.0.0-alpha2 start: `npm-run-all --parallel watch docs-serve`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the bootstrap@5.0.0-alpha2 start script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 143
	npm ERR! bootstrap@5.0.0-alpha2 watch-css-main: `nodemon --watch scss/ --ext scss --exec "npm-run-all css-lint css-compile css-prefix"`
	npm ERR! Exit status 143
	npm ERR! 
	npm ERR! Failed at the bootstrap@5.0.0-alpha2 watch-css-main script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 143

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/monty/.npm/_logs/2020-10-10T05_54_52_818Z-debug.log
	npm ERR! bootstrap@5.0.0-alpha2 watch-css-docs: `nodemon --watch site/assets/scss/ --ext scss --exec "npm run css-lint"`
	npm ERR! Exit status 143
	npm ERR! 
	npm ERR! Failed at the bootstrap@5.0.0-alpha2 watch-css-docs script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	Montys-MacBook:bootstrap monty$ 
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/monty/.npm/_logs/2020-10-10T05_54_52_839Z-debug.log

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/monty/.npm/_logs/2020-10-10T05_54_52_848Z-debug.log

This is the contents of the debug.log mentioned above: 

	0 info it worked if it ends with ok
	1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
	2 info using npm@6.14.8
	3 info using node@v10.16.3
	4 verbose run-script [ 'prestart', 'start', 'poststart' ]
	5 info lifecycle bootstrap@5.0.0-alpha2~prestart: bootstrap@5.0.0-alpha2
	6 info lifecycle bootstrap@5.0.0-alpha2~start: bootstrap@5.0.0-alpha2
	7 verbose lifecycle bootstrap@5.0.0-alpha2~start: unsafe-perm in lifecycle true
	8 verbose lifecycle bootstrap@5.0.0-alpha2~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node$
	9 verbose lifecycle bootstrap@5.0.0-alpha2~start: CWD: /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects$
	10 silly lifecycle bootstrap@5.0.0-alpha2~start: Args: [ '-c', 'npm-run-all --parallel watch docs-serve' ]
	11 silly lifecycle bootstrap@5.0.0-alpha2~start: Returned: code: 1  signal: null
	12 info lifecycle bootstrap@5.0.0-alpha2~start: Failed to exec start script
	13 verbose stack Error: bootstrap@5.0.0-alpha2 start: `npm-run-all --parallel watch docs-serve`
	13 verbose stack Exit status 1
	13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:3$
	13 verbose stack     at EventEmitter.emit (events.js:198:13)
	13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.$
	13 verbose stack     at ChildProcess.emit (events.js:198:13)
	13 verbose stack     at maybeClose (internal/child_process.js:982:16)
	13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
	14 verbose pkgid bootstrap@5.0.0-alpha2
	15 verbose cwd /Users/monty/Library/Mobile Documents/com~apple~CloudDocs/Projects/AdminTest/bootstrap
	16 verbose Darwin 19.6.0
	17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
	18 verbose node v10.16.3
	19 verbose npm  v6.14.8
	20 error code ELIFECYCLE
	21 error errno 1
	22 error bootstrap@5.0.0-alpha2 start: `npm-run-all --parallel watch docs-serve`
	22 error Exit status 1
	23 error Failed at the bootstrap@5.0.0-alpha2 start script.
	23 error This is probably not a problem with npm. There is likely additional logging output above.
	24 verbose exit [ 1, true ]

**Comment by XhmikosR** [comment]
Why would you use sudo?

Either way this is something specific to your setup, you are better off asking on SO.
