### ISSUE TITLE
First button is shifted when using btn-group-vertical

### ISSUE THREAD

**Issue by JohnyL** [twbs/bootstrap#31865]
First button is shifted when using `btn-group-vertical`. Here's the sample HTML:
```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <style>
        body {
            margin: 5px;
        }
    </style>
</head>
<body>
    <div class="btn-group btn-group-vertical mb-2">
        <button id="run" class="btn btn-primary">Run!</button>
        <button class="btn btn-primary">Sec</button>
        <button class="btn btn-primary">Third</button>
    </div>
</body>
</html>
```
The `body` margin is to see the left shift. Here's the result:
![First button offset in btn-group-vertical](https://user-images.githubusercontent.com/7391680/95655703-dde42c80-0b11-11eb-92c5-634888cde7bd.png)

The bug is reproducible on:
1. Google Chrome 86.0.4240.75
2. Opera Developer 73.0.3834.0
3. Firefox Developer 82.0b9
4. Microsoft Edge 86.0.622.38

**Comment by mdo** [comment]
Remove `.btn-group` and it should fix things: https://getbootstrap.com/docs/4.5/components/button-group/#vertical-variation.

**Comment by JohnyL** [comment]
@mdo Thanks, that works! 😊
