### ISSUE TITLE
Issues find in code scanning report

### ISSUE THREAD

**Issue by Sree2043** [twbs/bootstrap#31876]
Hi Team,
We've developed page using Bootstrap v4.3.1. We've done the '**Fortify**' code scan for pages and find the few issues. Please find the scan report and give me the solution for the issues report. 

[Related_js_issues.pdf](https://github.com/twbs/bootstrap/files/5370344/Related_js_issues.pdf)

**Comment by ffoodd** [comment]
Hi there,

First of all, thanks for using Bootstrap and opening a PR, this is appreciated.
I just read your report though, and there's not a single error coming from our sources: they all relates to either [Popper](https://github.com/popperjs/popper-core) or [jQuery](https://github.com/jquery/jquery). I suggest you open issues on they respective repositories, to help them fix their issues (or get a decent and appropriate workaround if any).
