### ISSUE TITLE
Vertical radio button group missing border-radius

### ISSUE THREAD

**Issue by Hiws** [twbs/bootstrap#31879]
The docs example of a vertical radio button group, has a missing top `border-radius`.
The issue also looks to appear outside of docs.

Docs: https://v5.getbootstrap.com/docs/5.0/components/button-group/#vertical-variation (scroll down)
Repro: <https://codepen.io/Hiws/pen/zYBvzpg>

It also appears that in the codepen, there's an issue with one of the buttons having a thicker border than the others. However that does not appear on the docs, so I might be missing something.

**Comment by ffoodd** [comment]
Nice catch, this is due to `.btn:not(:first-child)` used to reset `border-top-*-radius`.

**Comment by rohit2sharma95** [comment]
It is already reported in #31255 :)

**Comment by Hiws** [comment]
@rohit2sharma95 
Oh dear, looks like it didn't search thoroughly enough.

**Comment by ffoodd** [comment]
Thanks @rohit2sharma95 ;)
