### ISSUE TITLE
Using .sr-only inside a responsive table creates white space outside of body

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#31885]
### Description

Giving an element descended from `.table-responsive` the `.sr-only` class will cause the browser window to scroll horizontally due to `.sr-only`'s `position: absolute`.

I checked the docs and don't see any limitations of using `.sr-only` listed. https://getbootstrap.com/docs/4.5/utilities/screen-readers/

Is there a workaround or can something be added to the docs?

### Reduced test case

Reduce the browser width to its smallest and notice that the browser window scrolls, revealing white space to the right of the table. If you remove the `.sr-only` class from the top-right table cell, things behave normally.

https://www.codeply.com/v/0xzRkENQaH

### Config

- Bootstrap 4.5.2
- macOS 10.15.7
- Safari 14.0

**Comment by mdo** [comment]
Anything that's `position: absolute` will be positioned relative to the nearest parent with another `position` or block formatting context. In this case, it's the parent `.table-responsive`. Not sure how to account for this if at all in Bootstrap core, but you can fix it by adding `position: relative` to the `<td>` I believe.

/cc @twbs/css-review for thoughts

**Comment by mrlife** [comment]
@mdo Thanks, I can confirm that is a working solution. Just curious, is @twbs/css-review an internal group mention?

For anyone else who may have this issue, here is the CSS for that:

```
.table-responsive td {
    position: relative;
}
```

**Comment by patrickhlauke** [comment]
coming back to this a bit late, but: would adding the `position: relative` in bootstrap's core CSS cause any other unforeseen problems? if not, we could probably add it directly.

are there any other situations where the `.sr-only` / `.visually-hidden` class would cause similar problems, do we know?

**Comment by jordisan** [comment]
> coming back to this a bit late, but: would adding the `position: relative` in bootstrap's core CSS cause any other unforeseen problems? if not, we could probably add it directly.
> 
> are there any other situations where the `.sr-only` / `.visually-hidden` class would cause similar problems, do we know?

I'm afraid it creates problem when used together with elements using display: table-anything; :/

**Comment by mrlife** [comment]
> coming back to this a bit late, but: would adding the `position: relative` in bootstrap's core CSS cause any other unforeseen problems? if not, we could probably add it directly.
> 
> are there any other situations where the `.sr-only` / `.visually-hidden` class would cause similar problems, do we know?

Looks like it causes the issue seen at https://github.com/twbs/bootstrap/issues/33636, such that the solutions to that issue no longer work.

**Comment by mdo** [comment]
Closing as a stale / won't fix for v4 given our focus on v5.

**Comment by mrlife** [comment]
If this is still an issue in v5, could this please be reopened and relabeled?

**Comment by Boberro** [comment]
This issue is still a thing in 5.3
