### ISSUE TITLE
Failed to execute 'querySelector' on 'Document': 'javascript:void(0);' is not a valid selector.

### ISSUE THREAD

**Issue by Yusufzai** [twbs/bootstrap#31897]
Having the same issue with drop-down as we are previously facing in bootstrap 4.2.1 but the old solution did not work

https://stackoverflow.com/questions/53921939/bootstrap-4-2-1-failed-to-execute-queryselector-on-document-javascriptv

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by XhmikosR** [comment]
Closing, but you should try to use valid selectors; `javascript:void(0);` isn't valid.
