### ISSUE TITLE
Content loading placeholder

### ISSUE THREAD

**Issue by apiweb** [twbs/bootstrap#31909]
I think it is interesting if bootstrap natively supports content loading placeholder components.
Giving to developer standard content placeholders to using when content is loading.

![image](https://user-images.githubusercontent.com/5881027/96264170-4ca20980-0f9a-11eb-91a0-cd48a3f688a0.png)

Another examples

![image](https://user-images.githubusercontent.com/5881027/96265454-d43c4800-0f9b-11eb-9bac-5ea7d479b478.png)

**Comment by ffoodd** [comment]
Hi there, a PR is currently under devlopment for such things: #31859. Feel free to have a look :)

**Comment by patrickhlauke** [comment]
duplicate/similar to https://github.com/twbs/bootstrap/issues/31665
