### ISSUE TITLE
v5: custom file inputs not showing file name after choosing a file

### ISSUE THREAD

**Issue by m-elewa** [twbs/bootstrap#31900]
v5: custom file inputs not showing file name after choosing a file.
I had this issue on Firefox, Microsoft Edge, and Chrome when I use the file inputs in this doc page:
https://v5.getbootstrap.com/docs/5.0/forms/file/
I'm using Windows 10.

**Comment by m-elewa** [comment]
Also, here:
https://v5.getbootstrap.com/docs/5.0/forms/input-group/#custom-file-input

**Comment by techboyg5** [comment]
A Javascript plugin is required: [bs-custom-file-input](https://www.npmjs.com/package/bs-custom-file-input)

The file input is difficult to style using CSS only, so you need this Javascript plugin.

**Comment by m-elewa** [comment]
@techboyg5 but why it's not included on the documentation website? 
In v4 documentation, it's included and working fine, see here:
https://getbootstrap.com/docs/4.5/components/forms/#file-browser

**Comment by mdo** [comment]
Duplicate of #30265.

It doesn't work in v5 right now because we rewrote the file input.
