### ISSUE TITLE
Use Git pre-commit hook?

### ISSUE THREAD

**Issue by ffoodd** [twbs/bootstrap#31907]
Requires a new dev dependencies:
- [git-precommit-checks on NPM](https://www.npmjs.com/package/git-precommit-checks) and [Husky](https://www.npmjs.com/package/husky)
- [Trick shared by Maxime Bréhin on Twitter](https://twitter.com/mbrehin/status/1248155892333383680)

This might help us and our contributors to:
- not commit `dist/` files
- not commit unresolved conflicts,
- etc.

This might help to reinforce our contributing guidelines. Only nice-to-have, though—but wanted to share and get some opinions :)

**Comment by mdo** [comment]
I'm very down to see this explored!

**Comment by XhmikosR** [comment]
I personally dislike hooks because they slow me down. Assuming this can be implemented in a way that doesn't cause any slowdown, I'd be in favor of this, otherwise against it.

**Comment by MartijnCuppens** [comment]
Following @XhmikosR here. I used to be a fan of this, but it slows us down more than we'll gain from it. Concerning the dist files, we could add an GH action which checks this I guess?

**Comment by ffoodd** [comment]
Nice idea, we might do something like a bot auto-responding to the PR if dist files are commited.
Thanks for sharing experiences with hooks, what looks like a good idea might not be :D

**Comment by XhmikosR** [comment]
I had a quick look and I couldn't find any existent action to block a PR. But maybe I missed something.

https://github.com/sdras/awesome-actions

**Comment by ffoodd** [comment]
Making the action required would block the PR in case of failure. But that may be too much?

**Comment by XhmikosR** [comment]
I don't mind blocking the PR if it includes dist file modifications :) Ping me if you find an action and we'll see about setting it up.

**Comment by rohit2sharma95** [comment]
I think it can be done by creating a workflow file that runs tests (Maybe shell script) to check if dist files are modified and you can then mark this test as required in branch protection rules 🤔

**Comment by XhmikosR** [comment]
It's a tricky thing. Basically, we don't want people to commit any `dist/*` files, but we as team members should be able to bypass this. Ideally, the action should listen to a comment from another team member apart from the person who made the PR and allow us to bypass the check, otherwise should fail the build and block the PR.

**Comment by mdo** [comment]
Closing as stale.
