### ISSUE TITLE
DomPDF Support

### ISSUE THREAD

**Issue by ejaz-ul-haq** [twbs/bootstrap#31905]
Hi, 
I am Ejaz WordPress & Laravel Developer.

Bootstrap is an efficient FrontEnd development framework but
Developer communities are facing issues in V4 regarding PDF libraries support
like DomPDF is widely used By Laravel and WordPress Developers with Bootstrap 3.3.6 But
But Bootstrap V4 is not comfortable anymore.
I hope this issue will be resolved in V5, that we can enjoy Bootstrap everywhere. 

Thanks.

**Comment by alecpl** [comment]
You don't expect Bootstrap community to work on DomPDF, do you? If not, then what would you expect?
