### ISSUE TITLE
Dropdown Events Not Firing

### ISSUE THREAD

**Issue by bluedge** [twbs/bootstrap#31935]
OSX 10.15.7
Chrome 86.0.4240.80
Bootstrap 5.0-beta-2

Events not firing: `shown.bs.dropdown`, `hide.bs.dropdown`, `hidden.bs.dropdown`
Note: I can't get a simple `click` event either.

Test on the v5 live doc in Console. (https://v5.getbootstrap.com/docs/5.0/components/dropdowns/)

```
const d = document.getElementById('dropdownMenuButton');
d.addEventListener('show.bs.dropdown', (e) =>  console.log(e) );
d.addEventListener('shown.bs.dropdown', (e) => console.log(e) );
d.addEventListener('hide.bs.dropdown', (e) => console.log(e) );
d.addEventListener('hidden.bs.dropdown', (e) => console.log(e) );
```

**Comment by hashnimmo** [comment]
There are CSS only solutions for `dropdown`s, like shown [here](https://codepen.io/markcaron/pen/wdVmpB). This will make the `dropdown` element independent from JavaScript.

**Comment by XhmikosR** [comment]
@MartijnCuppens @Johann-S assuming the code is right, shouldn't we update the docs to remove outdated info? Otherwise, we are missing something in JS.

**Comment by patrickhlauke** [comment]
> All dropdown events are fired at the .dropdown-menu’s *parent element*

https://v5.getbootstrap.com/docs/5.0/components/dropdowns/#events

**Comment by patrickhlauke** [comment]
now, conceptually, i guess it would be nice/less confusing if the events were fired on the button/trigger and the actual menu as well, and then bubble up?

**Comment by bluedge** [comment]
@patrickhlauke I agree that is the way to go. Fire on the actual element and bubble up.
It is common practice and it would avoid recurrent confusion.

**Comment by QQ1968115437** [comment]
haha

**Comment by XhmikosR** [comment]
If we make such a change, it needs to happen before v5 hits stable. I don't have a personal preference, although it does seem to make more sense to fire on the trigger element. But maybe we are missing something regarding why we have the current situation.

/CC @Johann-S

**Comment by Johann-S** [comment]
I'm don't sure neither, it was like that since the beginning, the events are triggered on the trigger element on our components
