### ISSUE TITLE
Add variable to set blur for form :focus box shadows

### ISSUE THREAD

**Issue by samwilliscreative** [twbs/bootstrap#31940]
I am trying to style my buttons and forms using v5, but running into issues with setting my focus styles. This is due to the way box shadow variables are built up;

```
$input-btn-focus-width:         .25rem !default;
$input-btn-focus-color-opacity: .25 !default;
$input-btn-focus-color:         rgba($component-active-bg, $input-btn-focus-color-opacity) !default;
$input-btn-focus-box-shadow:    0 0 0 $input-btn-focus-width $input-btn-focus-color !default;
```

As you can see, the `blur` value for the `$input-btn-focus-box-shadow` variable is explicitly set to `0`. This is fine in this instance as I can manually re-declare this variable with my own prop;

```
$input-btn-focus-box-shadow:    0 0 $custom-blur $input-btn-focus-width $input-btn-focus-color;
```

However, there are issues when it comes to validation. The problem is that the `.form-control` class that includes the validation state selector mixin explicitly sets the `box-shadow`, meaning there is no way for me to overwrite the property using variables:

```
bootstrap\scss\mixins\_forms.scss line 60

&:focus {
    border-color: $color;
    box-shadow: 0 0 0 $input-focus-width rgba($color, $input-btn-focus-color-opacity);
}
```
I am therefore asking that a `$input-btn-focus-blur` variable be added so that the mixin can still work as intended, whilst giving users the ability to blur if they wish. Thanks.

**Comment by mdo** [comment]
For now, going to pass on this. Our goal is to keep focus styles consistent and obvious. Adding a blur makes them look like default box-shadows IMO.

**Comment by samwilliscreative** [comment]
> For now, going to pass on this. Our goal is to keep focus styles consistent and obvious. Adding a blur makes them look like default box-shadows IMO.

Sure, that makes sense, but for those developers that need to customise Bootstrap, the additional variable would allow us to set a consistent value for the blur.

You could even initialise the variable with a value of 0 so as to keep the base Bootstrap styles that you mention.

**Comment by mdo** [comment]
Feel like opening a PR by chance? I wouldn't mind reviewing and thinking about it again.

**Comment by samwilliscreative** [comment]
@mdo I have opened a PR here: [#33031](https://github.com/twbs/bootstrap/pull/33031)
