### ISSUE TITLE
On the interaction of data

### ISSUE THREAD

**Issue by wawasai** [twbs/bootstrap#31946]
Can the generated page generate the corresponding data format at the same time, such as Ajax or JSON format。
I am now trying to write a front-end code generation system. The problem I am facing now is how to make the generated front-end page automatically generate the corresponding interactive data format
生成的页面能否同时生成相应的数据格式，如Ajax或JSON格式
我现在在尝试编写一个前端代码生成系统，我现在面临的问题就是如何让生成的前端页面自动生成相对应的交互数据格式

**Comment by hashnimmo** [comment]
> such as Ajax or JSON format

I suggest you to use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) as it's a better alternative.

**Comment by XhmikosR** [comment]
This seems unrelated to Bootstrap.
