### ISSUE TITLE
Googling for most questions returns v4.0 docs

### ISSUE THREAD

**Issue by adampatterson** [twbs/bootstrap#31945]
Almost everything I search for relating to Bootstrap is returning content from v4.0.

Those c4 pages show v4.1 as the latest but even if v4.5 was listed and I change to it, I lose the page that I'm on and I have to do the search agian.

It is really frustrating.

**Comment by hashnimmo** [comment]
> Almost everything I search for relating to Bootstrap is returning content from v4.0.
Yes, I have noticed this too. I had to bookmark the correct version link.

> Those c4 pages show v4.1 as the latest but even if v4.5 was listed and I change to it, I lose the page that I'm on and I have to do the search again.
The version `dropdown` links are linked to the first page of each version. It should have grabbed the current user page link and then switch between versions.

**Comment by XhmikosR** [comment]
Known issue, and we have plenty of issues about this. We still haven't found a proper fix.

**Comment by adampatterson** [comment]
@XhmikosR  

Can you use robots.txt to block Google from indexing those older versions?

Can you update the Algilia search index to include multiple versions or indexes and then prioritize the latest version? 

Losing my results when you change versions isn't a huge issue if you're getting the proper version in the first place.

I would de-index all V4 docs except for the latest.

I typically search for Bootstrap 4 _____ or Bootstrap 5 ____

But I come across this issue multiple times a week.

**Comment by mdo** [comment]
Opened #31980 to track version linking across docs pages.
