### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by Saurabhjrl** [twbs/bootstrap#31941]
Add `font-display: swap;` to the default fonts to fix the Google **PageSpeed Insights** issue.

**Comment by XhmikosR** [comment]
We use the system font stack so this is invalid.

**Comment by Saurabhjrl** [comment]
Still, PageSpeed Insights detect Roboto font being served from fonts.gstatic.com

**Comment by XhmikosR** [comment]
Which is unrelated to Bootstrap.
