### ISSUE TITLE
BS 5.0 can't import modal.js in type script

### ISSUE THREAD

**Issue by Stajor** [twbs/bootstrap#31942]
Bootstrap 5 alpha 2

I am trying to import modal.js into my typescript application.

```
import {Modal} from 'bootstrap/js/src/modal.js';
```

But there was an error: 

```
export 'Modal' not found in 'bootstrap/js/src/modal.js'
```

The issue was fixed by changing

```
export class Modal {
...
// export default Modal
```

it is possible to change 'export class' in next alpha?

**Comment by nrayburn-tech** [comment]
Without looking at how the modal is exported, just going off of your code example.

If the modal is exported with `export default Modal`, then you should import it with `import Modal from 'bootstrap/js/src/modal.js`

**Comment by Stajor** [comment]
@nrayburn-tech Thanks. The ticket can be closed

**Comment by ffoodd** [comment]
Closing per last comment.
