### ISSUE TITLE
Where should the font-family of the body be placed?

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#31958]
https://github.com/twbs/bootstrap/blob/ed2f43e1b9e160ccc7a887527448a0f19e455a9c/scss/_reboot.scss#L48

[font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family)

The font-family should be placed on the html tag, like the following example.

```
html {
  font-family: $font-family-base;
}
```

the reason:
In general web page structure design, especially on multi-language websites, there will be a lang attribute in the html tag. When switching the page language, the value of this attribute will be switched. Of course, it will not be modified, and there will generally be no problems. . The design should be switched. Different language types should use different font files to display the corresponding content to conform to the reading visual habits of the corresponding people, rather than the same font style.
In the current Bootstrap design, this font-family is set on the body, and other child elements will inherit attributes. I think the font-family attribute should not be set in the body, but should be placed in the html tag. If there are other needs in the future, you can also set up different languages. In the body, when defining different font files in different languages, you need to set one more layer, as shown in the following example.

```css
html[lang^='zh-'] body {
    font-family: 宋体, serif;
}
```

The correct approach is that pages in different languages ​​use different lang values.

---

Of course there are also :lang pseudo-elements. But it is not used to tell the browser the language of the page.

[:lang](https://developer.mozilla.org/en-US/docs/Web/CSS/:lang)

Some personal thoughts, I hope to bring a little thought.

**Comment by patrickhlauke** [comment]
i don't quite get what the advantage would be in moving the font family definition to `html` rather than `body`. if you do want/need to switch fonts based on the `lang` attribute on `html`, you can already use the exact same suggest CSS that you then show as an example, no?

**Comment by zhangchenglin** [comment]
> i don't quite get what the advantage would be in moving the font family definition to `html` rather than `body`. if you do want/need to switch fonts based on the `lang` attribute on `html`, you can already use the exact same suggest CSS that you then show as an example, no?

The benefits seem to be insignificant, but it will bring a little inconvenience to some situations. Besides, shouldn't he be put on the top label?

**Comment by MartijnCuppens** [comment]
> The benefits seem to be insignificant

Indeed.

Everything that is rendered on the page is in the body tag anyway, so I don't think there is a reason to move this.
