### ISSUE TITLE
Media object is not reposnive in mobile

### ISSUE THREAD

**Issue by gobi004** [twbs/bootstrap#31956]
Hi,
Why media(https://getbootstrap.com/docs/4.5/components/media-object/#media-list) are not responsive ie.if resize the window or in the developer tool to mobile views of all devices, it should be full width like image on top title and descriptions are below the image in mobile or according the device width.but its not changing from its actual.

And cant use col classes here, using it making the problem.So give the option for that.

**Comment by bardiharborow** [comment]
You should be able to achieve something satisfactory with flex utilities, e.g. `.flex-wrap`. I don't think this behaviour is something we'll add as the media object has somewhat different goals – it's much less about the media being the primary content and more about content with an secondary associated image, e.g. comments.

> Bootstrap’s media object to construct highly repetitive components like blog comments, tweets, and the like.

> The media object helps build complex and repetitive components where some media is positioned alongside content that doesn’t wrap around said media.
