### ISSUE TITLE
Add context menu dropdown support

### ISSUE THREAD

**Issue by techboyg5** [twbs/bootstrap#31966]
[This code](https://codepen.io/techboyg5/pen/dyXvVeY?editors=1000)

Gives you a context menu dropdown. How about adding support for this into Bootstrap?

**Comment by Deckluhm** [comment]
You should provide a demo instead of just providing the code, it's way easier for people to test.

**Comment by patrickhlauke** [comment]
proper context menus also need to handle focus - they act like a modal, so when opened, move focus to the first menu item, keep focus contained inside the modal menu, on closing return focus to where it was before the menu was invoked, etc.

**Comment by techboyg5** [comment]
> proper context menus also need to handle focus - they act like a modal, so when opened, move focus to the first menu item, keep focus contained inside the modal menu, on closing return focus to where it was before the menu was invoked, etc.

Yeah. I'm just giving a rough example of what I want.

**Comment by techboyg5** [comment]
> proper context menus also need to handle focus - they act like a modal, so when opened, move focus to the first menu item, keep focus contained inside the modal menu, on closing return focus to where it was before the menu was invoked, etc.

https://codepen.io/techboyg5/pen/dyXvVeY?editors=1000

**Comment by mdo** [comment]
Could be interesting to extend the Dropdown plugin to support something like this.

**Comment by patrickhlauke** [comment]
conceptually it's closer to a modal, with its focus moving/trapping/resetting behaviour

**Comment by Paptoos** [comment]
It is great . You can add fade in dropdown menu

**Comment by mdo** [comment]
Closing as stale.
