### ISSUE TITLE
Migration guide from 3 to 4 misses tabs

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#31971]
The migration guide from Bootstrap 3 to 4 does not mention that tabs needs the `.nav-item` on the `li` and `nav-link` on the `a`.

**Comment by XhmikosR** [comment]
Isn't this sufficient? https://getbootstrap.com/docs/4.5/migration/#navs

**Comment by vanillajonathan** [comment]
My bad, you're right.
