### ISSUE TITLE
Floating label rendering issue

### ISSUE THREAD

**Issue by ffoodd** [twbs/bootstrap#31991]
As mentionned ~~in [#31955 (comment)](https://github.com/twbs/bootstrap/pull/31955#issuecomment-716665220)~~ and [#30449 (comment)](https://github.com/twbs/bootstrap/pull/30449#discussion_r512595176), it seems we have a few quriks related to fonts on Ubuntu.

Could relate to #31657 but I don't think so: this need to test things again, comparing our previous font-stack and probably try another one.

~~Maybe introduce `font-size-adjust` to lock this a bit more?~~

**Edit**: only striking through obsolete sutff just in case, but file input relates to a Firefox bug. Only leaving this one with a floating label rendering issues.

- Ubuntu 18, Firefox 84 / Chromium 86
- when ending the `transition`, there's a little quirk where text seems to struggle a bit to get its final position and aspect.

**Comment by MartijnCuppens** [comment]
> Maybe introduce `font-size-adjust` to lock this a bit more?

Feels like a hack, just to fix Ubuntu.

**Comment by ffoodd** [comment]
It's what this property is for: [harmonizing fonts measures in the same font stack](https://drafts.csswg.org/css-fonts-3/#propdef-font-size-adjust). Doesn't feels like a hack to me.

However as I said, I definetely need to check things using our previous stack, and try alternatives for the Ubuntu part, before trying anything else.

**Comment by MartijnCuppens** [comment]
Hmm, maybe 😛

The question is: does it fix the issues you mentioned above?

**Comment by alecpl** [comment]
I think the stack might be ok. Here's more info on the file input issue https://github.com/twbs/bootstrap/pull/31955#issuecomment-717729880. I tried `font-size-adjust:0.5` on the button, it fixed the issue for normal size input, but not for large. Putting it on the body element does not do anything. So, I'm not sure that's a solution.

**Comment by ffoodd** [comment]
Indeed, the file input thing is different. Still remains the floating label rendering issue to tackle (renaming the issue).

**Comment by mdo** [comment]
Have any screenshots/videos of the issue here, if we're still looking to fix?

**Comment by ffoodd** [comment]
I can't reproduce this, either on  Chrome or Firefox. I'm closing this, we'll see if anyone reproduces or complains for something similar.
