### ISSUE TITLE
Heading Space Left

### ISSUE THREAD

**Issue by hashnimmo** [twbs/bootstrap#31998]
There is a tiny space to the left of `h1`, `h2`, `h3`, `h4`, `h5`, and `h6` in their default state. Why is this?
```
<html>
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
</head>
<body>
<h1>Hello</h1>
<p>Hell naw</p>
</body>
</html>
```
![h1-left-space](https://user-images.githubusercontent.com/24617729/97464855-70385d00-1967-11eb-85f4-35fcac626801.png)

I'm using;
Bootstrap: 4.5.3
Microsoft Edge: 86.0.622.51
Microsoft Windows 10: 20H2 Build 19042.572

**Comment by mdo** [comment]
That's just how the fonts are rendered, nothing in our control.

**Comment by hashnimmo** [comment]
Oh, anyway thanks for that clarification.
