### ISSUE TITLE
Issue with collapse classe

### ISSUE THREAD

**Issue by djoulilamine** [twbs/bootstrap#32028]
Hello,

i have got an issue transforming from bootstrap v3.4.1 into the latest version v4.x . The issue is represented in the collapse effect used in bootstrap. the problem is shown in the images :
![Capture1](https://user-images.githubusercontent.com/26381739/97783965-8890bd80-1b9b-11eb-9192-966e80ff8287.PNG)
![Capture2](https://user-images.githubusercontent.com/26381739/97783967-89c1ea80-1b9b-11eb-9f5b-df0b221ac56b.PNG)
![Capture3](https://user-images.githubusercontent.com/26381739/97783968-8a5a8100-1b9b-11eb-885b-adb18dbafbdc.PNG)
![Capture4](https://user-images.githubusercontent.com/26381739/97783970-8af31780-1b9b-11eb-8886-d6e75c8d6bd5.PNG)
![Capture5](https://user-images.githubusercontent.com/26381739/97783971-8b8bae00-1b9b-11eb-975e-f9adcb006f5e.PNG)
![Capture6](https://user-images.githubusercontent.com/26381739/97783972-8c244480-1b9b-11eb-8b91-c205b131d405.PNG)
![Capture7](https://user-images.githubusercontent.com/26381739/97783973-8cbcdb00-1b9b-11eb-9e1a-33a8ceb87957.PNG)
![Capture8](https://user-images.githubusercontent.com/26381739/97783975-8d557180-1b9b-11eb-99db-aafc117bf459.PNG)

the images show before and after change the version of bootstrap. waiting for your reply!

Regards!

**Comment by patrickhlauke** [comment]
those images make very little sense. please describe, in words, what your actual issue is, and provide a working example (in codepen or similar) of the problem

**Comment by mdo** [comment]
Please bear in mind, v4 is a major departure from v3 and requires some work in migrating. It's not a drop-in replacement. And as Patrick mentions, we can't help with screenshots. Please update your issue with a live example of things not working, or ask around in Slack or StackOverflow.
