### ISSUE TITLE
Bootstrap's v4.5 checkbox cannot be aligned Horizontally or Vertically when next to an input

### ISSUE THREAD

**Issue by arcanisgk** [twbs/bootstrap#32029]
Bug reports must include:

- Windows 10
- Chrome

I have detected in V4.5 that it is not the only problem; even if we want to place the checkbox in the same row as an input or a Label of normal dimensions; it turns out that the checkbox goes crazy and does not align vertically or horizontally in the markup:

https://stackoverflow.com/questions/64579724/bootstraps-v4-5-checkbox-cannot-be-aligned-horizontally-or-vertically-when-next

**Comment by mdo** [comment]
The SO question has an answer on this: add `align-items-center` to the `.row` and your content will be properly aligned. We don't do this automatically because some layouts could cause additional alignment issues. See https://codepen.io/emdeoh/pen/MWeGgEz with it fixed.
