### ISSUE TITLE
Something collapsing whitespace?

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap#32022]
Has something been changed in the v5 beta in how whitespace is handled by browsers? I seem to have an issue with whitespace “collapsing”:

<img width="334" alt="Screenshot 2020-10-30 at 16 17 58" src="https://user-images.githubusercontent.com/167312/97730327-a42c9300-1acb-11eb-8507-fa314bf192f1.png">

These are inline elements, that have space in the mark-up, so used to be “spaced” in the browser:

<img width="1552" alt="Screenshot 2020-10-30 at 16 20 24" src="https://user-images.githubusercontent.com/167312/97730578-f372c380-1acb-11eb-9f5d-8dae6f87e38f.png">

But now, it seems that whitespace the browser would normally insert is being negated or collapsed.

Has something been added to the Bootstrap reset or anything that would cause this?

**Comment by mdo** [comment]
> Has something been changed in the v5 beta in how whitespace is handled by browsers?

Don't think anything in our alphas would affect that. 🤔 Are there some flex styles that are being inherited or applied here? Usually I only see this if the parent is a flex container, but could be something else I suppose. Any chance for some kind of live demo?

**Comment by Madhvan28** [comment]
Hi, I am actually new to Github.
I think that this is happening due to different rendering of Whitespaces in different Browsers.
adding &nbsp; before and after the line 

`<span>or</span>`

should do the trick

**Comment by martinbean** [comment]
@Madhvan28 This is happening in both Safari and Chrome. It’s the first time I’ve seen this behaviour in nearly 15 years of web development.

If it is a browser suddenly changing how it handles whitespace between inline elements, then I imagine a _lot_ of websites will start looking different.

**Comment by mdo** [comment]
Anything more to share @martinbean regarding possible flexbox usage here? Maybe you can look at the computed styles for the parent container in inspector and share that? Anyway to reproduce otherwise?

**Comment by martinbean** [comment]
@mdo I’ve used the browser’s web inspector and it’s not flexbox. The elements have `display` values of `inline`, and sit in a container with `display: block`.

Unfortunately there’s nothing I can share as it’s currently a development version I’m seeing this in.

**Comment by mdo** [comment]
Tried to replicate the markup from your screenshots: https://codepen.io/emdeoh/pen/NWrMJvE. Not seeing an immediate issue with the latest CSS from `main`.

**Comment by martinbean** [comment]
I’ll try and upload the HTML and CSS I have as a pen somewhere today. Thanks for bearing with me on this!

**Comment by martinbean** [comment]
So, I’ve tracked it down to, not something in the CSS, but something in my _JavaScript_ file 😕

I’ve put the HTML, CSS, and JavaScript in a JSFiddle here: https://jsfiddle.net/martinbean/z6ph1mkg/1/

When I added the CSS, the whitespace looked fine, but when I add the JavaScript, the whitespace then collapses. I can’t see from the browser dev tools in the computed CSS what would be causing this. Can any one else see what the issue may be?

**Comment by martinbean** [comment]
…and this appears to be an issue with the `preserveWhitespace` option in Vue 3. Still trying to work out how to enable it in Laravel Mix (a Laravel-provided wrapper around Webpack), so I’m going to close this Issue since it’s an issue with that and not Bootstrap itself. Sorry to bother you!

**Comment by patrickhlauke** [comment]
No worries @martinbean ... glad you managed to zero in on at least the source of the problem.
