### ISSUE TITLE
Nav shown.bs.tab is not getting triggered (v5 alpha2)

### ISSUE THREAD

**Issue by xbaha** [twbs/bootstrap#32038]
using exact same JS and HTML, the code below is triggered on Bootstrap4, but not v5.alpah2

$('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
//code
});

**Comment by rohit2sharma95** [comment]
@xbaha There may be some other issue in your use case but the event is working here:
https://jsbin.com/qapalukufa/edit?js,console,output

**Comment by Johann-S** [comment]
Btw @rohit2sharma95 when we detect jQuery we trigger events with jQuery.

But it still works without jQuery: https://jsbin.com/rekediboha/1/edit?js,console,output

**Comment by rohit2sharma95** [comment]
Yes @Johann-S, I added the example with jQuery because the snippet in the first comment was using jQuery. :smile:

**Comment by xbaha** [comment]
here is an example:
https://jsfiddle.net/60zmncxa/

it was not triggered

**Comment by rohit2sharma95** [comment]
> here is an example:
> https://jsfiddle.net/60zmncxa/

Due to the order of the scripts, you need to put jquery before the bootstrap's script. 😄

**Comment by xbaha** [comment]
> > here is an example:
> > https://jsfiddle.net/60zmncxa/
> 
> Due to the order of the scripts, you need to put jquery before the bootstrap's script. 😄

My understanding is Bootstrap is not dependent on JQuery, so it should be anywhere.
but anyway, i had to put jquery after bootstrap because if i don't,  this line gives error:

===>bootstrap.Tab.getInstance(triggerEl).show();
jquery.min.js:2 Uncaught TypeError: Cannot read property 'show' of null

example: 
https://jsfiddle.net/6ythfagd/

**Comment by Johann-S** [comment]
Hi @xbaha,

It's written in our documentation here: https://v5.getbootstrap.com/docs/5.0/getting-started/introduction/#js
> Place one of following <script>s near the end of your pages, right before the closing </body> tag, to enable them.
