### ISSUE TITLE
Navbar-brand text are not vertically centred

### ISSUE THREAD

**Issue by ayan9051** [twbs/bootstrap#32047]
![IMG_20201102_181714](https://user-images.githubusercontent.com/63101155/97869530-abf06f80-1d37-11eb-9f35-20b30e26d3b3.jpg)

brand text not vertically centred.

OS - Android 6.0.1
Browser - Chorme 86.0.4240.110

live demo - https://codepen.io/Ayan90510/pen/RwRyYjd

**Comment by mdo** [comment]
You added `d-inline-block align-top` to the `.navbar-brand`. Take that off and it's fine.
