### ISSUE TITLE
Navbar with card and form has whitespace to the right

### ISSUE THREAD

**Issue by jay20162016** [twbs/bootstrap#32051]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
done
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
done
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
done

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
macOS Catalina
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
Chromium 85.0.4183.121
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
https://jsbin.com/xosikumuca/edit?html,output

<img width="635" alt="Screen Shot 2020-11-02 at 2 24 48 PM" src="https://user-images.githubusercontent.com/20290260/97910056-2b217b80-1d17-11eb-9063-eccbf8176447.png">
<img width="520" alt="Screen Shot 2020-11-02 at 2 25 18 PM" src="https://user-images.githubusercontent.com/20290260/97910184-602dce00-1d17-11eb-89b3-212e6495c872.png">

**Comment by mdo** [comment]
Wrap your `.row` in `.container`.
