### ISSUE TITLE
Sticky footer example not working since v4.1

### ISSUE THREAD

**Issue by Grnd365** [twbs/bootstrap#32073]
Ok, first time using GitHub and first time using Bootstrap so hope this is right.
In version 4.1, the sticky footer example worked fine.
https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/
https://getbootstrap.com/docs/4.1/examples/sticky-footer/sticky-footer.css

But in version 4.2 onward including the latest 4.5 it does not work.
https://getbootstrap.com/docs/4.5/examples/sticky-footer-navbar/
https://getbootstrap.com/docs/4.5/examples/sticky-footer/sticky-footer.css

Looks like the sticky-footer.css was changed inadvertently and is now missing the properties that make it "sticky".
Actually, it would be nice to incorporate this ability into the general release so a separate css is not required but either way the example should be fixed.  Thanks.

**Comment by mdo** [comment]
Wonder if this was a change when we started processing those CSS files @XhmikosR?

**Comment by XhmikosR** [comment]
@mdo We use the core utils, I don't think it's related to processing at all. Also, it seems to work fine, I'm not sure what the OP means by it does not work.

**Comment by mdo** [comment]
Oh well I'm a dummy, I should've checked the actual links first lol. Was just running through notifications and didn't check. Closing out!
