### ISSUE TITLE
input lg to sm for mobile?

### ISSUE THREAD

**Issue by onigetoc** [twbs/bootstrap#32088]
How can i swith to desktop input-lg to input-sm for mobile?
same with input-group-lg to sm and also submit button size.
Should i use javascript?

```
<div class="input-group input-group-lg">
          <input type="url" name="url" id="fetchurl" class="form-control input-lg" value="" placeholder="hello">
          <span class="input-group-btn input-lg">
            <button class="btn btn-primary btn-lg" type="submit">ShareIt</button>
          </span>
          <div class="validate"></div>
</div>
```

**Comment by leecollings** [comment]
Make your own media queries

https://stackoverflow.com/questions/22138708/how-to-make-input-group-responsive-search-and-dropdown

**Comment by onigetoc** [comment]
@leecollings 
This is what i didn't want but i did it this way. 
everything smaller than 414 for new phone size viewport

**Comment by hashnimmo** [comment]
> Should i use javascript?

I'm no expert, but don't use JavaScript when something is exactly possible with just CSS. By "exactly" I mean, if CSS can do it exactly the way you want it, definitely use just CSS for that. [Progressive enhancement](https://google.com/search?q=progressive+enhancement) is what you need.

**Comment by mdo** [comment]
No plans to add this by default, sorry! I'd recommend doing your own media query and extending the classes as needed.
