### ISSUE TITLE
Alert with count-down timer (with time decreasing progress bar below)

### ISSUE THREAD

**Issue by vigneshksaithal** [twbs/bootstrap#32127]
Alert with count-down timer loader

Why needed?
Because alerts are used to display errors, success message,e.t so, they are used for short amount of time. And after few seconds they should fade. So, alerts should should have this feature.

Example : https://bootstrap-vue.org/docs/components/alert#overview

**Comment by rohit2sharma95** [comment]
In bootstrap vue you can actually place your markup somewhere that can be dynamically removed and inserted into DOM, but bootstrap does not support this behaviour 🙂 
IMO it can be done in bootstrap by placing a hidden alert somewhere in the HTML and just use `show()` method to show that alert and then automatically hide it (And again that same alert can be shown).

What you would suggest @patrickhlauke

**Comment by vigneshksaithal** [comment]
We just need to hide it that's all no need of removing from DOM. Like in every web app, alerts are used only for short amount of time after that they are removed (I don't mean removing from DOM, instead I mean, display: none) 
So, it will be useful if it had a countdown like timer for alert and removed after the specified timer, is what I think.

**Comment by mdo** [comment]
No plans to add this ourselves—perfect for an addon!
