### ISSUE TITLE
Animations not working on Mac (chrome, safari)

### ISSUE THREAD

**Issue by keeema** [twbs/bootstrap#32128]
MacOS 10.15.7
Chrome 86
Safari 14

Animations do not work on Mac. Carousel just switches the images with no slide animation.
https://getbootstrap.com/docs/4.5/components/carousel/#with-controls
Same with e.g. Collapse.

On PC with Windows 10 and same version of chrome it works fine. 
Also works in Safari iOS.

**Comment by patrickhlauke** [comment]
> The animation effect of this component is dependent on the `prefers-reduced-motion` media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/4.5/getting-started/accessibility/#reduced-motion).

I'll assume that on the Mac you've got reduced motion enabled. https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/

**Comment by keeema** [comment]
It was exactly the reason of issue. 
Solved. Thank you very much.
