### ISSUE TITLE
Popover is not a function

### ISSUE THREAD

**Issue by krosoftware** [twbs/bootstrap#32132]
Hello
version v5.0.0-alpha3 have problem with popover.
It display this error: Uncaught TypeError: $(...).popover is not a function - on line 15 ($(".pop").popover({)

Here is the complete HTML:

```html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Popover</title>
  <link rel='stylesheet' href='css/bootstrap.min.css'>
  <script src='js/jquery.min.js'></script>
  <script src='js/bootstrap.bundle.min.js'></script>
</head>
<body>
  
  <button type="button" class="btn btn-info pop" data-container="body" data-placement="right" >HOVER OVER ME... </button>

  <script>
    $(".pop").popover({
      trigger: "manual",
      content: function() {
        var data = ''+
          '<ul class="list-group" style="font-size:16px;">'+
            '<a href="#" class="list-group-item list-group-item-action xxx" >xxxxxDin</a>'+
            '<a href="#" class="list-group-item list-group-item-action xxx" >Morbi leo risus</a>'+
            '<a href="#" class="list-group-item list-group-item-action xxxy" >Porta ac consectetur ac</a>'+
          '</ul>';
        return data;
      },
      html: true,
      sanitize: false,
      animation: true
    }).on("mouseenter", function() {
      var _this = this;
      $(this).popover("show");
    }).on("mouseleave", function() {
    })  
  </script>
</body>
</html

```

**Comment by XhmikosR** [comment]
@tidusIO: any ideas? If I go back to alpha2 and put jQuery and Bootstrap in body then it works, but with alpha3 regardless of the scripts' position I get the TypeError

@krosoftware please make a Codepen in the future

**Comment by krosoftware** [comment]
> @tidusIO: any ideas? If I go back to alpha2 and put jQuery and Bootstrap in body then it works, but with alpha3 regardless of the scripts' position I get the TypeError
> 
> @krosoftware please make a Codepen in the future

OK.

**Comment by tidusIO** [comment]
Probably it's because it's async. We're waiting for DomContentLoaded now to extend jQuery.
It could be, that the script is executed before DomContentLoaded.
It should work, if you wrap your code with 
```
$(function() {
  // Handler for .ready() called.
});
```

**Comment by krosoftware** [comment]
> Probably it's because it's async. We're waiting for DomContentLoaded now to extend jQuery.
> It could be, that the script is executed before DomContentLoaded.
> It should work, if you wrap your code with
> 
> ```
> $(function() {
>   // Handler for .ready() called.
> });
> ```

Yes, it works on that way.
Also, it works on this way:
$(document).ready(function(data){
  $(".pop").popover({
  ...
}); 

Thanks!

**Comment by XhmikosR** [comment]
We definitely need a separate section with jQuery examples and all these pitfalls so that we link in each component's examples section. Any PRs welcome!

**Comment by mdo** [comment]
We have a PR for jQuery examples (see #31402), so closing this out.

**Comment by schappaughc** [comment]
doesn't work
