### ISSUE TITLE
Floating labels: label and sizing

### ISSUE THREAD

**Issue by 2acode** [twbs/bootstrap#32130]
Floating labels are really useful, thanks.

But I think they really take up a lot of space.
A behavior similar to Material Design 2.0 would be preferable with the label going over the edge:
https://mdbootstrap.com/docs/jquery/forms/inputs/#outline-inputs

Also it would be useful to have the ability to change the size (form-floating-sm).

Thanks again
Alessandro

**Comment by mdo** [comment]
No plans to put labels over the borders. Sizes maybe, so we'll leave this open for that.

**Comment by hidegh** [comment]
The **sizing** indeed is an issue...
![image](https://user-images.githubusercontent.com/6331063/158774692-32c467f2-1087-4607-a2c3-262131752177.png)

...also if there would be a convenient way to alter paddings as well (both for control and floating label)!

**Comment by mdo** [comment]
Going to close a won't fix for now. If someone wants to take a stab at this, please feel free to open a PR :).

**Comment by jacekk015** [comment]
In case someone still needs that here's the custom CSS code

![image](https://github.com/user-attachments/assets/d28377d0-e797-4bf8-acac-6d372596707b)


```
.form-floating.form-floating-sm>.form-control,
.form-floating.form-floating-sm>.form-control-plaintext {
  padding: inherit;
}

.form-floating.form-floating-sm>.form-control,
.form-floating.form-floating-sm>.form-control-plaintext,
.form-floating.form-floating-sm>.form-select {
  padding: 0.32rem .75rem;
  background-color: white;
  min-height: auto;
  height: inherit;
  /* min-height: inherit; */
  line-height: inherit;
}

.form-floating.form-floating-sm>.form-control-plaintext~label,
.form-floating.form-floating-sm>.form-control:focus~label,
.form-floating.form-floating-sm>.form-control:not(:placeholder-shown)~label,
.form-floating.form-floating-sm>.form-select~label {
  color: rgba(var(--bs-body-color-rgb), .65);
  transform: scale(.9) translateY(-0.9rem) translateX(0.1rem);
  background-color: white;
  padding-left: 0.1rem;
  padding-right: 0.1rem;
  line-height: 1;
}

.form-floating.form-floating-sm>label {
  position: absolute;
  top: 0;
  left: 0.75rem;
  margin-bottom: 0;
  z-index: 2;
  padding: 0 0;
  height: auto;
  font-size: 14px;
  padding-top: 0.37rem;
  overflow: hidden;
  text-align: start;
  text-overflow: ellipsis;
  white-space: nowrap;
  pointer-events: none;
  border: var(--bs-border-width) solid transparent;
  transform-origin: 0 0;
  transition: opacity .1s ease-in-out, transform .1s ease-in-out;
}
```
