### ISSUE TITLE
Remove shrink-to-fit from meta tag viewport

### ISSUE THREAD

**Issue by DesigningStudios** [twbs/bootstrap#32148]
I am creating this issue as per my conversation:
https://twitter.com/sandeepgovada/status/1326986360570458115

As per bootStrap [documentation](https://getbootstrap.com/docs/4.5/getting-started/introduction/#starter-template) we have to write "shrink-to-fit=no" at "meta name="viewport" but we dont need to write it anymore. Please update your documentation accordingly.

`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

Reference:
https://support.google.com/webmasters/thread/24918854
https://stackoverflow.com/questions/33767533/what-does-the-shrink-to-fit-viewport-meta-attribute-do

**Comment by patrickhlauke** [comment]
well, documentation didn't really say you *have* to use it...it was just part of the suggested starter template. But yes, it's probably safe to strip that out of our docs now.

**Comment by patrickhlauke** [comment]
though in fact, based on the list of supported browsers for 4.5, we probably do need to leave that in as nominally we support down to iOS 9.0 https://getbootstrap.com/docs/4.5/getting-started/browsers-devices/ (unless I'm misreading it ... @XhmikosR ?)

**Comment by XhmikosR** [comment]
Correct, we've discussed this in the past.
