### ISSUE TITLE
please bring back form-file-text

### ISSUE THREAD

**Issue by Pearseak** [twbs/bootstrap#32159]
so that we can replace 'No file chosen' with something useful.
the latest alpha version leaves me with 'Choose file', 'No file chosen', and a large label that can't be inline
btw why am I using a css framework that told me to write more css on my own!

**Comment by mdo** [comment]
We have a new file input in v5: https://v5.getbootstrap.com/docs/5.0/forms/form-control/#file-input.

**Comment by charlesfries** [comment]
![Screenshot_2020-11-17 Form controls](https://user-images.githubusercontent.com/2275005/99431533-c68e2100-28bf-11eb-8d01-2217f46f4c9e.png)

I feel like this is a step backwards...or is there some bug causing the CSS to not work?

**Comment by XhmikosR** [comment]
@charlesfries a screenshot without the browser version does not help anyone. Nor does it help commenting on old issues...

**Comment by charlesfries** [comment]
Firefox 78.0.2 (64-bit) Windows 10

> Nor does it help commenting on old issues...

@XhmikosR Says who?

**Comment by patrickhlauke** [comment]
Firefox 83.0 (64-bit) Windows 10 ... so either FX fixed a lot of bugs, or there's something blocking styles at your end.

> ![Screenshot 2020-11-17 192039](https://user-images.githubusercontent.com/895831/99437242-1abdf300-290a-11eb-83e1-537384bfffdf.png)

And as for commenting ... your comment was not about `form-file-text`, so better to start a new issue instead of just piggy-backing on an already closed issue

**Comment by charlesfries** [comment]
Understood

**Comment by ffoodd** [comment]
@charlesfries the pseudo-element used to progressively enhance file inputs styles is only supported from Firefox 82 — so your screenshots is the expected behaviour on older Firefox.
