### ISSUE TITLE
Missing border radius  on input group

### ISSUE THREAD

**Issue by mahdim8m** [twbs/bootstrap#32150]
border radius is inverted
![search](https://user-images.githubusercontent.com/58599664/99105744-2355b700-25f4-11eb-895b-d3b58b1efaaf.jpg)
[Preview](https://mahdim8m.github.io/)

**Comment by mdo** [comment]
This is likely because RTL isn't officially supported yet. This also isn't a reduced test case, which our bug report template requires.
