### ISSUE TITLE
docs: add live toast example

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#32157]
on that topic, it would be nice if our documentation had an actual live example of a toast that starts out hidden, and is then triggered (just by a simple button). just to see it actually in action (and to potentially debug things like this). or failing that, a live example/demo that's linked from the docs.

_Originally posted by @patrickhlauke in https://github.com/twbs/bootstrap/issues/28752#issuecomment-490859956_

**Comment by saideepesh000** [comment]
@XhmikosR, do you mean like this. If so(or something similar) I would do this.

**Comment by XhmikosR** [comment]
Actually we have #31330, so this is a duplicate issue
