### ISSUE TITLE
Jumbotron example missing in v5

### ISSUE THREAD

**Issue by 9mido** [twbs/bootstrap#32161]
https://v5.getbootstrap.com/docs/5.0/examples/

https://getbootstrap.com/docs/4.0/examples/jumbotron/

The jumbotron example from v4 is missing in the v5 examples. Can the bootstrap team please create a replacement example on the v5 example webpage for users who wish to upgrade from the v4 jumbotron example to a compatible v5 example?

**Comment by josephcrowell** [comment]
There is no Jumbotron in v5 but the functionality can be recreated easily enough per: https://stackoverflow.com/questions/63141494/how-to-create-jumbotron-in-bootstrap-5

I believe this is also documented somewhere in the migration docs but can't find where at the moment.

**Comment by 9mido** [comment]
Thanks for that stackoverflow link. But are the answers in that link bootstrap team recommendations and best practices?

Well, if it is not in the docs it should be added, and perhaps more easily found if you cannot find it.

**Comment by XhmikosR** [comment]
https://v5.getbootstrap.com/docs/5.0/migration/#jumbotron

**Comment by XhmikosR** [comment]
Or do you mean, you want a clear example how to do this in v5 with the utility examples in our docs?

@mdo: perhaps we should expand the migration notes or something?

**Comment by 9mido** [comment]
@XhmikosR 

Yes I saw that link you provided already. 

Yes a clear example and expanding the migration notes would be nice. 

It is sort of like a missing piece where a full example was shown in v4 but nothing except one sentence was shown in v5 it will leave people confused how to upgrade their v4 jumbotrons to v5 without showing a full example. Plus, not all websites would prefer to use the 'product' example and would rather have the look and feel of the old jumbotron v4 example in v5.

**Comment by mdo** [comment]
https://codepen.io/emdeoh/pen/ZEpmOPE

There’s a quick pass at doing something in a Codepen with nothing but utilities. Bringing back an example would be helpful I think.
