### ISSUE TITLE
Little more right-margin for "info icon" in <select> when class is "is-invalid"

### ISSUE THREAD

**Issue by vigneshksaithal** [twbs/bootstrap#32188]
[Reference](https://v5.getbootstrap.com/docs/5.0/forms/validation/#server-side)

**Comment by bharatmakvana** [comment]
Hello @vigneshksaithal ,

I am working to resolve this issue. Its issues only on while is-invalid class present. I found the solution for that just we need to change the background-position value https://prnt.sc/vry5ff  but problem is that the value come form the same variable so I can't change if I change this value then it also effect on normal state also like - https://prnt.sc/vry6450  Can I declare a new variable for select in-valid state with new value. 

Please provide your valuable feedback

**Comment by vigneshksaithal** [comment]
I think we can use

**Comment by mdo** [comment]
Duplicate of #32356.
