### ISSUE TITLE
Warning when installing for Angular 11

### ISSUE THREAD

**Issue by maerni** [twbs/bootstrap#32199]
Hi

We installed **bootstrap 4.5.3** and **@popperjs/core 2.5.4**.

But then comes a warning, that bootstrap 4.5.3 needs **popper.js 1.16.1**.

When bootstrap will be updated for that this dependency to the old popper.js will not be there anymore?

Thanks very much.

Best regards
Mike

**Comment by XhmikosR** [comment]
#29842
