### ISSUE TITLE
v5: Prepend and append items into floating-labels

### ISSUE THREAD

**Issue by bernalandres** [twbs/bootstrap#32200]
Congratulations on the great work. Would the version 5 include prepend and append elements within the form-floating, as in the traditional input-groups?. Thank you.
![image](https://user-images.githubusercontent.com/51427948/99670538-7645c900-2a4f-11eb-813f-78b8ffd6a5cd.png)

**Comment by mdo** [comment]
No plans to include floating label support in input groups.
