### ISSUE TITLE
Bootstrap Carousel Not Working

### ISSUE THREAD

**Issue by DaleMFrancis** [twbs/bootstrap#32248]
I’ve been unsuccessful in making the Bootstrap Carousel plug-in work… although I followed the online example.

The most relevant code (HTML, CSS, .ts) can be accessed at JSFiddle:

https://jsfiddle.net/DaleFrancis/23w0m5k6/4/

JSFiddle doesn’t allow for all of the files and folders necessary to provide a “working demo” of a JavaScript framework (Angular)… but the most relevant code is there to examine. (Don’t try to make something happen in the 4th “results” quadrant.)

Basically there are two problems. First, clearly, the Bootstrap Carousel is not working at all. Why?

A secondary problem, although not trivial, is that most of my images don’t load, returning a “404 (not found)” error. I believe this to be a timing issue where the page loads before the image file (…/src/assets folder) can be resolved. But although I sort of understand the problem I haven’t been able to figure out a solution. (See the NOT WORKING comment in the JSFiddle html quadrant. )

So, two issues, but first it would be good to get a working carousel!

Thank you. If you can contribute you are a very good and smart person.

Dale Francis

**Comment by ffoodd** [comment]
Please provide a reduced test case which at least tries to work?
You're not even loading Bootstrap in that Fiddle.

Our carousel works fine on our side ([see our docs](https://getbootstrap.com/docs/4.5/components/carousel/)) so without any reduced test case to help a possible diagnosis, we can't do anything.

**Comment by mdo** [comment]
This sounds beyond our help as it may fall under the category of general troubleshooting. Please consult the Discussions tab or our community Slack.

**Comment by DaleMFrancis** [comment]
Rather than attempt CodePen or JSFiddle, I would simply like to zip up my entire project and send this in a zip file as an email attachment.

My thinking is that Angular offers many files that reference a complex folder structure, plus many .ts files.  I am also concerned about my limited experience with JSFiddle and CodePen.  It should be simpler to supply you with the whole project that you can unzip to a “cats” project starting on a "cats" folder.

Can you accommodate me on this approach? 



Dale Francis
Angular Developer
dalemfrancis@gmail.com <mailto:dalemfrancis@gmail.com>
571.326.7227

**Comment by patrickhlauke** [comment]
This is already in discussions https://github.com/twbs/bootstrap/discussions/32219 ... locking
