### ISSUE TITLE
Removing background(blue square) when .btn-close is clicked in v5

### ISSUE THREAD

**Issue by vigneshksaithal** [twbs/bootstrap#32241]
It doesn't look good when the background blue square comes when the .btn-close is clicked. 
Expecting what others think...

**Comment by patrickhlauke** [comment]
assume you mean the focus indicator. which is needed for keyboard users, so unlikely to be removed for now (until we make a decision on using `:focus-visible` with a polyfill)

**Comment by ffoodd** [comment]
However it's customizable thanks to `$btn-close-focus-shadow`… So I'd say, customize it?

**Comment by mdo** [comment]
Closing as a won't fix.
