### ISSUE TITLE
CDN error in the Boostrap starter template

### ISSUE THREAD

**Issue by piper9** [twbs/bootstrap#32261]
This CDN link does not load in the browser - the https://code.jquery.com site appears to be down. 

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

Thank you for looking into this. Please advise - is this a temporary problem or should I use a Google CDN link instead?

**Comment by XhmikosR** [comment]
It seems it works for me now.
