### ISSUE TITLE
[bug] card disappear in side card-columns on Mac using chrome browser

### ISSUE THREAD

**Issue by VietDucPhan** [twbs/bootstrap#32267]
Using card-columns to create Masonary layout but the card is not display.

bootstrap: @4.5.3
Chrome version: 87.0.4280.67 (Official Build) (x86_64)

Live url: https://tiarian.me/tagged/stumblinin

**Comment by mdo** [comment]
You haven't provided much information here. I see some three columns though.

**Comment by VietDucPhan** [comment]
> You haven't provided much information here. I see some three columns though.

Sorry, I was not very descriptive, Follow the url, on Chrome you should see only 3 cards, two on the first row with a big space in between but there is a card in between not showing.if I change remove _position:relative_ into position:static the card is show again.
If open with safari or firefox it appeared normal with 3 cards on a row and masonary like grid.
