### ISSUE TITLE
Reboot: remove margin only in directly nested lists

### ISSUE THREAD

**Issue by babielmam** [twbs/bootstrap#32265]
[Code-Reference from reboot.scss](https://github.com/twbs/bootstrap/blob/c63aebc86ba05f0ebb420add653b80804c6a0cff/scss/_reboot.scss#L193)

I see why removing the margin of a nested list is a good idea. However I think, it should be done with direct child selectors in a way like this: `ul > li > ul`.

We currently have a problem where we list a lot of teasers in an unordered list. Deeply nested inside the text of one of the teasers, there is another list, which has no margin at all thanks to the code linked above.

**Comment by mdo** [comment]
For now, I think this stays in for v5. We've done this since v4 and it feels too late in v5's development to try to make a change. Plus I think the styles are worthwhile still.
