### ISSUE TITLE
[bug] The Close Button: focus Color does not change dynamically

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#32260]
The Close Button focus Color does not change dynamically it show the default Color based on `$input-btn-focus-box-shadow` variable it should change the color based on what color are using.

**Here is an Example :** 

Let's imagine that I have Alert Component that used the alert-danger class, the focus close button it should be the color that the alert using in this case is danger.

![Example](https://i.imgur.com/6swWf7D.png)

**Comment by rexarvind** [comment]
Use this, change is respect of matching color with alerts.

```
.btn-close:hover, .btn-close.active,
.btn-close:active {
    box-shadow:0 0 0 0.25rem rgba(22,22,22,0.25) !important
}
```

**Comment by devhoussam** [comment]
> Use this, change is respect of matching color with alerts.
> 
> ```
> .btn-close:hover, .btn-close.active,
> .btn-close:active {
>     box-shadow:0 0 0 0.25rem rgba(22,22,22,0.25) !important
> }
> ```

I prefer the **bootstrap** team do this option officialy in sass code.

**Comment by mdo** [comment]
I don't see us styling the dismiss focus shadow any more than it already is. We do it for our buttons and certain forms, but that's with the intention of conveying appropriate context and states. Here I don't think it's very important, and would require component-specific code to override. One option would be more themes for the close button itself, but I'm not as into that.

**Comment by mdo** [comment]
Closing as a won't fix for now.
