### ISSUE TITLE
Deadline on https://getbootstrap.com/  button to "View on Github" 

### ISSUE THREAD

**Issue by gretchunkim** [twbs/bootstrap#32283]
Deadline  on "View on GitHub"
<a class="btn btn-sm btn-bd-light my-2 my-md-0" href="https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.5/getting-started/introduction.md" title="View and edit this file on GitHub" target="_blank" rel="noopener">View on GitHub</a>
![Capture](https://user-images.githubusercontent.com/8564035/100566842-10e6a900-3295-11eb-8cdf-93c84828e768.PNG)

<a class="btn btn-sm btn-bd-light my-2 my-md-0" </a> href="https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.5/getting-started/introduction.md" title="View and edit this file on GitHub" target="_blank" rel="noopener">View on GitHub</a>

**Comment by XhmikosR** [comment]
It's already fixed in thev4-dev branch after the [Switch to Hugo PR](https://github.com/twbs/bootstrap/pull/32077)

Preview: https://v4-dev--twbs-bootstrap.netlify.app/docs/4.5/about/team/
