### ISSUE TITLE
Some cards with box-shadow are disappearing in card-columns when carousel changes image.

### ISSUE THREAD

**Issue by davood89** [twbs/bootstrap#32288]
When the carousel switches to the next image, some of the cards in the card-columns are disappearing for a short moment. This only appears when the cards have box-shadow and in Chrome. 

Here is an [example codepen](https://codepen.io/davood89/pen/RwGPRBO?editors=1000) where you can see the issue.

Any ideas how I can fix this?

- maxOS Catalina (10.15.6)
- Google Chrome (87.0.4280.67)

**Comment by marianayap** [comment]
Hello! @davood89 I'll like to try this issue!

**Comment by neralex** [comment]
Same here on Win10 20H2 with Google Chrome (87.0.4280.66) and Edge Chromium (87.0.664.47)-

**Comment by XhmikosR** [comment]
Looks like a browser issue since Firefox behaves right. I can reproduce on Windows with Chromium Edge, but not with Firefox.

**Comment by XhmikosR** [comment]
v5 seems to be fine from a quick look https://codepen.io/XhmikosR/pen/a65c36f2091630ab67fb6a77b31b960d?editors=1000

**Comment by ffoodd** [comment]
Don't get the diagnosis for now but it's related to shadows: if you drop `shadow` class on your cards, it behaves normally. 
Seems like a browser renderging bug, but needs more digging.

**Comment by patrickhlauke** [comment]
box shadows futz with rendering/compositing in some browsers. agree this looks like a bug, possibly worth checking chromium bug tracker for similar?

**Comment by XhmikosR** [comment]
Is there anything we can do on our side? If not, someone should report the issue upstream and we close this.

**Comment by mdo** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=420350 or https://bugs.chromium.org/p/chromium/issues/detail?id=269061 maybe?

Maybe even https://bugs.webkit.org/show_bug.cgi?id=101184 should there be problems in Safari?
