### ISSUE TITLE
Variables for button hover+active states

### ISSUE THREAD

**Issue by quasipickle** [twbs/bootstrap#32290]
A bit of a duplicate of #31544, but that issue seems to be abandoned.

In my opinion, the background color change between normal & hover states on buttons isn't enough to provide visual feedback that the button has been hovered/clicked.  Currently I'm re-defining the necessary rules, but it would be nice to be able to use the mixin.

I propose a bunch of new variables to allow us to set the amount by which a colour is tinted or shaded.

```scss
$btn-hover-bg-shade-amount:        15%!default;
$btn-hover-bg-tint-amount:         15%!default;
$btn-hover-border-shade-amount:    20%!default;
$btn-hover-border-tint-amount:     10%!default;
$btn-active-bg-shade-amount:       20%!default;
$btn-active-bg-tint-amount:        20%!default;
$btn-active-border-shade-amount:   25%!default;
$btn-active-border-tint-amount:    10%!default;
```

**Comment by mdo** [comment]
Feel free to open a PR for this. I personally think it's variable overload, but I agree it'd be nice to tweak things without having to modify the mixin itself.
