### ISSUE TITLE
Redirect v5.getbootstrap.com pages to getbootstrap.com/docs/5.0/

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#32325]
Wondering if we can do a rebuild of our docs where every page includes a new redirect in the front matter that points to its `getbootstrap.com/docs/5.0/` equivalent, and deploy it to the `v5.getbootstrap.com` site. Ideally we're looking at 301 redirects and then we take the site down entirely.

Thoughts @XhmikosR?

**Comment by XhmikosR** [comment]
Added this in #31057
