### ISSUE TITLE
RTL: Carousel wrong direction on keyboard and touch

### ISSUE THREAD

**Issue by FaridAghili** [twbs/bootstrap#32329]
- Windows 10
- Google Chrome 87

@ffoodd 
Carousel direction is wrong in RTL when changed by keyboard or touch, however left/right icons works correct on click.

**Comment by XhmikosR** [comment]
@FaridAghili let's try and use one issue to track your findings please. Choose one of the 3 you have open and list there all your issues.

**Comment by FaridAghili** [comment]
@XhmikosR 
Thanks, listed them all in #32327 and closed others
