### ISSUE TITLE
RTL bugs

### ISSUE THREAD

**Issue by FaridAghili** [twbs/bootstrap#32327]
- Windows 10
- Google Chrome 87

- [x] a weird bug in `form-switch`:
  <img src="https://user-images.githubusercontent.com/8607021/101142310-ae8dff80-362a-11eb-8cff-bb914a2ed6f2.png" alt="image" width="350">
  
  Notice the switch circle which isn't vertically centered.
  It only happens in unchecked unfocused state, not when checked or when it has focus.
- [ ] In this [url](https://twbs-bootstrap.netlify.app/docs/5.0/examples/cheatsheet-rtl/), please take a look at this:
  <img src="https://user-images.githubusercontent.com/8607021/101141505-a1244580-3629-11eb-9f88-d5020c4e094f.png" alt="image" width="350">

  I guess we should flip this chevrons like this:

  <img src="https://user-images.githubusercontent.com/8607021/101141605-c5802200-3629-11eb-8542-d3ec2d834a6e.png" alt="image" width="350">

  Which can be done with `transform: rotate(180deg)`.  Also the `transform-origin` can be increased to `.6em` to have more space between chevron and text.
- [ ] Carousel direction is wrong in RTL when changed by keyboard or touch, however left/right icons works correct on click [See fix](https://github.com/twbs/bootstrap/issues/32327#issuecomment-739673942)

**Comment by FaridAghili** [comment]
- Windows 10
- Google Chrome 87

@ffoodd
In this [url](https://deploy-preview-30980--twbs-bootstrap.netlify.app/docs/5.0/examples/cheatsheet-rtl/), please take a look at this:
![image](https://user-images.githubusercontent.com/8607021/101141505-a1244580-3629-11eb-9f88-d5020c4e094f.png)

I guess we should flip this chevrons like this:

![image](https://user-images.githubusercontent.com/8607021/101141605-c5802200-3629-11eb-8542-d3ec2d834a6e.png)

Which can be done with `transform: rotate(180deg)`:
![image](https://user-images.githubusercontent.com/8607021/101141737-f4969380-3629-11eb-84d5-6b66d886c9f4.png)

Also the `transform-origin` can be increased to `.6em` to have more space between chevron and text.

**Comment by FaridAghili** [comment]
- Windows 10
- Google Chrome 87

@ffoodd 
Carousel direction is wrong in RTL when changed by keyboard or touch, however left/right icons works correct on click.

**Comment by FaridAghili** [comment]
I can confrim first bug is fixed (switch circle)

**Comment by FaridAghili** [comment]
About the carousel keyboard and touch which currently changes slide in wrong direction in RTL layout, It can be fixed to behave as expected in both RTL and LTR with very little change:

1.
https://github.com/twbs/bootstrap/blob/be8539170943dddfd52fff53d6b77858fd0183ec/js/src/carousel.js#L37
Change to:
```js
const ARROW_LEFT_KEY = isRTL ? 'ArrowRight' : 'ArrowLeft'
```

2.
https://github.com/twbs/bootstrap/blob/be8539170943dddfd52fff53d6b77858fd0183ec/js/src/carousel.js#L38
Change to:
```js
const ARROW_RIGHT_KEY = isRTL ? 'ArrowLeft' : 'ArrowRight'
```

These 2 changes fix keyboard direction.

Now for fixing touch direction:
1.
https://github.com/twbs/bootstrap/blob/be8539170943dddfd52fff53d6b77858fd0183ec/js/src/carousel.js#L257
Change to:
```js
isRTL ? this.next() : this.prev()
```

2.
https://github.com/twbs/bootstrap/blob/be8539170943dddfd52fff53d6b77858fd0183ec/js/src/carousel.js#L262
Change to
```js
isRTL ? this.prev() : this.next()
```

Also make sure to import `isRTL` from `util`:
```diff
// /js/src/carousel.js

import {
  getjQuery,
  onDOMContentLoaded,
  TRANSITION_END,
  emulateTransitionEnd,
  getElementFromSelector,
  getTransitionDurationFromElement,
  isVisible,
+  isRTL,
  reflow,
  triggerTransitionEnd,
  typeCheckConfig
} from './util/index'
```

@ffoodd @XhmikosR

**Comment by XhmikosR** [comment]
You can always make PRs @FaridAghili. But most importantly, we need to add JS tests for the changes in the JS changes in the RTL PR as mentioned in #32330.
