### ISSUE TITLE
docs(components/input-groups): add hint that custom file inputs require js to display the selected file name

### ISSUE THREAD

**Issue by thetric** [twbs/bootstrap#32334]
As a ng-bootstrap user (Angular + Bootstrap) I was confused that the custom file input component requires Bootstrap's JS to display the file name. ng-bootstrap does [not require Bootstrap's JS](https://ng-bootstrap.github.io/#/getting-started#installation). Bootstrap's documentation should clarify this.

# Repro
- Go to https://getbootstrap.com/docs/4.5/components/input-group/#custom-file-input
- Disable JS via the browser's dev tools
- select a file in an upload dialog
- the original placeholder is still visible

Tested under Arch Linux with Firefox 84.0b4

**Comment by XhmikosR** [comment]
It does not require Bootstrap's JS; it requires bs-custom-file-input and it's already documented: https://getbootstrap.com/docs/4.5/components/forms/#file-browser

**Comment by patrickhlauke** [comment]
> It does not require Bootstrap's JS; it requires bs-custom-file-input and it's already documented: https://getbootstrap.com/docs/4.5/components/forms/#file-browser

not explicitly on https://getbootstrap.com/docs/4.5/components/input-group/#custom-file-input though, maybe worth adding some small note there? maybe cross-reference to https://getbootstrap.com/docs/4.5/components/forms/#file-browser ?

**Comment by XhmikosR** [comment]
Feel free to add a note/callout, sure :)

**Comment by XhmikosR** [comment]
#32457
