### ISSUE TITLE
Remove Unused JavaScript (Tree Shaking)

### ISSUE THREAD

**Issue by rexarvind** [twbs/bootstrap#32336]
Separate javascript related to different features in different files. For example, have one essential file to support the other features and keep those other features in separate files. Something like this:

- bootstrap.essential.min.js
- bootstrap.navbar.min.js
- bootstrap.modal.min.js
- bootstrap.tooltip.min.js
- bootstrap.anotherFeature.min.js

And for those who don't want to reduce the size, can download `bootstrap.bundle.min.js` just like we already have.

**Comment by XhmikosR** [comment]
https://getbootstrap.com/docs/4.5/getting-started/javascript/#individual-or-compiled
