### ISSUE TITLE
View on GitHub button -> broken link

### ISSUE THREAD

**Issue by letzfets** [twbs/bootstrap#32338]
The "view on GitHub" button on [https://getbootstrap.com/docs/4.5/](https://getbootstrap.com/docs/4.5/) is a broken link:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/44865639/101198982-8f13c880-3664-11eb-86f6-e2f4084a6a91.png">

gives that:

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/44865639/101199270-ec0f7e80-3664-11eb-9f3b-09dc634db8d3.png">

**Comment by XhmikosR** [comment]
Work for me and is redirected to https://getbootstrap.com/docs/4.5/getting-started/introduction/

**Comment by letzfets** [comment]
tried in safari and in chrome: when clicking the button, I end up here: [https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.5/getting-started/introduction.md](https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.5/getting-started/introduction.md)
which says "Page not found" as in screenshot above

**Comment by XhmikosR** [comment]
Ah, that's OK, because v4-dev has the files moved around after #32077.

**Comment by XhmikosR** [comment]
Refs #32283
