### ISSUE TITLE
is-invalid not changing border color of input-group

### ISSUE THREAD

**Issue by guizoxxv** [twbs/bootstrap#32340]
The class `is-invalid` does not change the border color of `input-group` to red as shown in the documentation [https://getbootstrap.com/docs/4.5/components/forms/#supported-elements](https://getbootstrap.com/docs/4.5/components/forms/#supported-elements).

- Bootstrap version: 4.5.0
- Operating system and version: Linux Ubuntu 20.04.01
- Browser and version: Chrome 87.0.4280.66
- Reduced test case: [https://codepen.io/guizo/pen/mdrPbYW](https://codepen.io/guizo/pen/mdrPbYW)

**Comment by XhmikosR** [comment]
You need to use the `was-validated` class in the `form` as shown in the documentation.

**Comment by guizoxxv** [comment]
Sorry, I did not pay attention to the `form` element as I'm using React SPA so the submition occurs with a button `onClick` handler. I think that this approach is not intuitive. Generally a `is-invalid` class is used along with the `form-control` element.

Also the `was-validated` class add styling for success and fail. I wanted to only show the invalid style. It seems that the invalid style border only show in this case because the input has a `required` property. I'm not using HTML validation but custom validation rules.

What this example does not show is that you can use `input-group is-invalid` with a `custom-file-input is-invalid` inside to achieve the desired result. I thought about adding a note about this in the documentantion but do not know where.

**Comment by XhmikosR** [comment]
> What this example does not show is that you can use `input-group is-invalid` with a `custom-file-input is-invalid` inside to achieve the desired result. I thought about adding a note about this in the documentantion but do not know where.

You can submit a PR to our docs and we can review.
