### ISSUE TITLE
v5 a3: Tooltip fires when I call modal

### ISSUE THREAD

**Issue by VReunov** [twbs/bootstrap#32351]
![Снимок экрана 2020-12-06 в 11 11 09](https://user-images.githubusercontent.com/2165575/101275111-3f441700-37b4-11eb-9d40-f2bfd750c427.png)
js:
`  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-toggle="tooltip"]'))
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl)
  })`

example https://jsfiddle.net/msqypuza/

**Comment by XhmikosR** [comment]
You are including both bootstrap.js, popper.min.js and bootstrap.bundle.min.js.

You only need bootstrap.bundle.min.js.
