### ISSUE TITLE
modal-backdrop does not disappear

### ISSUE THREAD

**Issue by Pearseak** [twbs/bootstrap#32359]
if show and hide interval is less than Modal fade animation duration modal-backdrop will stay in DOM and prevent further interact with the page.

- v5 alpha 3
- Window 10 20H2
- Chrome 86

https://codepen.io/pearseak/pen/YzGWzmE

it will happen when fetch() at line 27 resolve too fast.

**Comment by rohit2sharma95** [comment]
Can you please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link? :slightly_smiling_face:

**Comment by Pearseak** [comment]
https://codepen.io/pearseak/pen/YzGWzmE

it will happen when fetch() at line 27 resolve too fast.

**Comment by XhmikosR** [comment]
Is the issue present on v4 too?

**Comment by MartijnCuppens** [comment]
> it will happen when fetch() at line 27 resolve too fast.

Check its if the modals `display` value is `none`, else use the `hidden.bs.modal` event or do something alike.

This seems to be a custom implementation of the modals though, so I'm closing this
