### ISSUE TITLE
Toasts: `.hide` CSS can conflict with utilities

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#32350]
1. Close this toast https://twbs-bootstrap.netlify.app/docs/5.0/components/toasts/#color-schemes
2. Notice that its `display` is not set to `none`

Probably affects v4 too, I haven't checked. We should use `!important` I guess? - **EDIT**: might not be so simple, we need to consider the use cases.

**Comment by MartijnCuppens** [comment]
There doesn't seem to be a v4 version of this example: (https://getbootstrap.com/docs/4.5/components/toasts/#stacking).

We could just wrap the toast content in an additional `<div>` with the flex classes?

**Comment by XhmikosR** [comment]
If that works, sure go ahead :)

BTW it feels weird that we don't use the core utils, but that's a different discussion.

**Comment by sijusamson** [comment]
Well, it seems [https://twbs-bootstrap.netlify.app/docs/5.0/components/toasts/#custom-content](https://twbs-bootstrap.netlify.app/docs/5.0/components/toasts/#custom-content) also has the same issue. its `display` is not set to `none`, when we close toast.
