### ISSUE TITLE
Documentation does not mention the mark element

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#32362]
Bootstrap styles the `mark` element, but the documentation does not mention it or have any reference to the element.

**Comment by rohit2sharma95** [comment]
It is mentioned in the docs :slightly_smiling_face: 
Here: https://getbootstrap.com/docs/4.5/content/typography/#inline-text-elements

**Comment by vanillajonathan** [comment]
My apologies, you're right. I missed this when searching in the search bar since Algolia did not pick up on it.

Since the `mark` element is a semantic equivalence to the [marker pen](https://en.wikipedia.org/wiki/Marker_pen) which comes in different colors, it might be of interest to illustrate using the `mark` element together with classes.

```html
<p>You can use the mark tag to <mark>highlight</mark> text.</p>
<p>You can use the mark tag to <mark class="bg-success">highlight</mark> text.</p>
<p>You can use the mark tag to <mark class="bg-danger">highlight</mark> text.</p>
<p>You can use the mark tag to <mark class="bg-warning">highlight</mark> text.</p>
<p>You can use the mark tag to <mark class="bg-info">highlight</mark> text.</p>
```

**Comment by mdo** [comment]
No plans to add `mark`-specific classes or to document it with `.bg-` utilities since that'd most likely require text utilities as well, which is covered on the utilities docs :).
