### ISSUE TITLE
Field validation background-image is not displayed when autocomplete (v5)

### ISSUE THREAD

**Issue by bernalandres** [twbs/bootstrap#32366]
Microsoft Windows 10 Home 19042.662, Google Chrome 86.0.4240.198...
![input_validator](https://user-images.githubusercontent.com/51427948/101388225-6a0a9a00-389e-11eb-863c-eab6549f2665.gif)

**Comment by septatrix** [comment]
This would probably mean hacking into `input:-webkit-autofill` as that presumably covers the background. However modifying such elements generally results in bad user experience as they are used to the light blue background. It may be possible to change the z-index but besides the reboot styles I think bootstrap tries to not modify such things.

**Comment by bernalandres** [comment]
> Esto probablemente significaría piratear, `input:-webkit-autofill`ya que presumiblemente cubre el fondo. Sin embargo, la modificación de dichos elementos generalmente resulta en una mala experiencia del usuario, ya que están acostumbrados al fondo azul claro. Puede ser posible cambiar el índice z, pero además de los estilos de reinicio, creo que bootstrap intenta no modificar tales cosas.
In firefox works perfectly without modifying something. In Google Chrome, it is not possible to display the background image, the browser simply does not have it in time (even with !Important)...

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by bernalandres** [comment]
Microsoft Windows 10 Home 19042.662, Google Chrome 86.0.4240.198...
This is the example in website. In Mozilla Firefox works fine. 
I consider that the problem would be in the blue background that is assigned when interacting with an element of the autocomplete list, since the browser overrides the background image style no matter how important it is pointed out.
[https://getbootstrap.com/docs/5.0/forms/validation/#server-side](url)

**Comment by mdo** [comment]
Not sure we want to override this. Thoughts from @twbs/css-review?

**Comment by mdo** [comment]
Closing this for now. Happy to revisit in the future if there’s a clear path to preventing this without it being super hacky or adding new problems.
