### ISSUE TITLE
[v5] Checkbox background and transition

### ISSUE THREAD

**Issue by robinheidrich** [twbs/bootstrap#32367]
I have two suggestions for the checkbox.

1. Currently the Sass variable `$form-check-input-bg` uses `$body-bg` as default, I think using `$input-bg` would be better.

2. Remove the transition for `background-color` (probably also for `border-color`) from `.form-check-input`. The background color should be applied immediately when you release the mouse button to make it look smoother.

**Comment by mdo** [comment]
Coming in #32793.
