### ISSUE TITLE
Color functions not working as expected?

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#32360]
I'm using SASS and bootstrap the new version V5 as CSS Framework in some of my academic project in color part I stuck because the color functions not working as I expected I will explain where is the issue with images in next lines.

**first of all take a look to the current result :**

![Current Result](https://i.stack.imgur.com/OG8QV.png)

as you can see in current result it's an alert component with orange in background and border color but the issue the text it should be white not black but in this example is black I want to change the color to be with dynamicly without using any custom css only editing the bootstrap color functions to be white color instead of black color.

**What I expected :**

![Expected Result](https://i.stack.imgur.com/SpYnM.png)

**Live Example on codepen**

[Codepen Example](https://codepen.io/themes4all/pen/YzGqOaJ)

[Stackoverflow issue](https://stackoverflow.com/questions/65170317/sass-scss-bootstrap-5-color-functions-not-working-well)

**Note:** _I know that I can use some custom css classes to change that but I want to know How to do that in core of bootstrap._

**Comment by mdo** [comment]
I think the color functions are working as intended here—it's using the `color` with the highest contrast (either white or black) against the `background-color` you've specified. Quick check on the colors here show a massive difference in contrast grading between black and white.

<img width="474" alt="Screen Shot 2020-12-07 at 8 47 54 AM" src="https://user-images.githubusercontent.com/98681/101379415-16318e00-3869-11eb-9436-238a07309a0a.png">
<img width="474" alt="Screen Shot 2020-12-07 at 8 47 58 AM" src="https://user-images.githubusercontent.com/98681/101379419-1762bb00-3869-11eb-91a3-e5bfa8ca554d.png">

**Comment by devhoussam** [comment]
can you share this tool

**Comment by mdo** [comment]
Those are screenshots from a Mac app called Contrast. https://usecontrast.com

Another fun tool is Colorable:

- https://colorable.jxnblk.com/000000/fd7e14
- https://colorable.jxnblk.com/ffffff/fd7e14
