### ISSUE TITLE
Popper emits warning for dropdowns due to non-zero margin styles

### ISSUE THREAD

**Issue by septatrix** [twbs/bootstrap#32379]
Originated in #32354:

> I also noticed that popper shows a warning in the console (at least when referencing the scripts manually and not using the minified bundle). Look inside the console of [this pen](https://codepen.io/Septatrix/pen/dypXKgx?editors=1111) when clicking the button. This is due to `.dropdown-menu` specifying a margin which poppler overwrites anyway. Do you want to track this here or create a new issue?

The simplest fix would be to get rid of the margin as popper set to margin to 0 inline by default. If however the styling is important the margin/offset has to be passed as a config option to the popper constructor.

**Comment by septatrix** [comment]
The simplest fix would be to get rid of the maring as popper set to margin to 0 inline by default. If however the styling is important the margin/offset has to be passed as a config option to the popper constructor.

**Comment by rohit2sharma95** [comment]
Popper overrides this margin:
https://github.com/twbs/bootstrap/blob/764e5298dea17e15bbcbf792204a45a761bedc0a/scss/_dropdown.scss#L25

Is this required even when using Popper with dropdowns? @twbs/css-review :thinking:

**Comment by MartijnCuppens** [comment]
There is a static option which needs this (https://getbootstrap.com/docs/5.0/components/dropdowns/#options). Also, popper is disabled in navbars and responsive navbars (https://getbootstrap.com/docs/5.0/examples/navbars/)

**Comment by septatrix** [comment]
If you to `data-bs-offset` then you should know that this option seems to be nonfunctional currently. While being mentioned in the paragraph before the options table it is actually not listen in the table and the example further up in the page also does not  work.

Or I misunderstood you and you actually knew that. Nevertheless the css margin should now get passed to the popper configuration which accepts an offset parameter during construction IIRC.

Regarding the dropdown in the navbar would it be possible to use css margins for only those, i.e. differentiate between a dropdown outside and inside a navbar? Or if their position also gets calculated using css anyhow then it would probably be more consistent to get rid of the css margins and forward the offset information to popper and the script for navbar dropdowns respectively.

**Comment by rohit2sharma95** [comment]
This is happening with popover as well (Not with tooltip since tooltip use padding for spacing)
