### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cyberneer** [twbs/bootstrap#32373]
Error in the Russian description on the page
https://bootstrap-4.ru/docs/4.0/content/tables/#

Incorrectly -
Добавьте класс .table-hover в < tbody > для активации :hover у рядов таблицы.

Correctly - Добавьте класс .table-hover в < table > для активации :hover у рядов таблицы.

![screenshot](https://user-images.githubusercontent.com/59159777/101456915-d12f5980-3945-11eb-9630-c0e2322f126f.jpg)

**Comment by XhmikosR** [comment]
Yeah, nothing to do with our repo. Translations are **not** handled by us.
