### ISSUE TITLE
Popover overflows container (regression)

### ISSUE THREAD

**Issue by christianboyle** [twbs/bootstrap#32384]
Operating system and version (Windows, macOS, Android, iOS)
- Windows 10, Build 19042 (10.0.19042)

Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- Google Chrome, Version 87.0.4280.88 (Official Build) (64-bit)

--

_Note: This bug seems to have been introduced [during the transition](https://github.com/twbs/bootstrap/commit/adfdf7160b5822aae12eea677e7dd3128d2569bf) from `"popper.js": "^1.16.1"` to `"@popperjs/core": "^2.5.4"`._

### Steps to reproduce the problem

1. Visit https://getbootstrap.com/docs/4.5/components/popovers/#four-directions
2. Trigger "Popover on Left" and "Popover on Right"
3. Notice both adjust their position to be fully visible inside the body when viewport is sufficiently narrow
4. Visit https://getbootstrap.com/docs/5.0/components/popovers/#four-directions
5. Trigger "Popover on Left" and "Popover on Right"
6. Notice both overflow the body when viewport is sufficiently narrow

![456](https://user-images.githubusercontent.com/1605754/101505935-79d7bc00-393a-11eb-97e8-11a6b4ba92d9.png)

### What is the expected behavior?

Expected behavior is for popovers to not overflow their container (like in Bootstrap 4.5.1).

### What went wrong?

It seems like there's been some change in the inline styles that are applied by Popper where we no longer perform:
`transform: translate3d(x, y, z)` 
and instead use:
`transform: translate(x, y)`.

![123](https://user-images.githubusercontent.com/1605754/101506119-ac81b480-393a-11eb-9643-7374e442dbb0.png)

### Any other comments?

Maybe [this change](https://github.com/popperjs/popper-core/blame/671f71e2b6990765e5ca780daaea7d1f7175beb6/src/modifiers/computeStyles.js#L106) from 10 months ago had something to do with it.

**Comment by MartijnCuppens** [comment]
It seems we got to explicitly define our fallback behaviour. See this demo, based on [popper's tutorial](https://popper.js.org/docs/v2/tutorial/) https://codepen.io/MartijnCuppens/pen/QWKKmLg?editors=1010 (Uncomment js for fix)

**Comment by christianboyle** [comment]
That was fast, thanks everyone!
