### ISSUE TITLE
Modal does not open on v5.0.0-beta1

### ISSUE THREAD

**Issue by krosoftware** [twbs/bootstrap#32386]
Hello
I made 2 simple examples with identical code, for 5.0.0-alpha3 and 5.0.0-beta1
Here is link (which works) using 5.0.0-alpha3:
http://code.reloado.com/oeasyrik1/287/edit#html,live

same code, but using 5.0.0-beta1 does not work:
http://code.reloado.com/oeasyrik1/286/edit#html,live

what is the problem?
Thanks.

**Comment by XhmikosR** [comment]
All data attributes are prefixed, i.e. `data-bs-toggle`.
