### ISSUE TITLE
Dropdown does not work, wrong position v5.0.0-beta1

### ISSUE THREAD

**Issue by krosoftware** [twbs/bootstrap#32387]
Hello
I made 2 simple examples, here is 5.0.0-alpha3 version which works:
http://code.reloado.com/oeasyrik1/288/edit#html,live
and here is 5.0.0-beta1 which does not work correctly:
http://code.reloado.com/oeasyrik1/290/edit#html,live

on beta1 example, search, button and dropdown are positioned on left which is wrong.
Additional, on beta1 dropdown does not open.
Thank you.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/issues/32386#issuecomment-740913517

**Comment by krosoftware** [comment]
Thanks, but why is everything moved to left instead of right?

**Comment by XhmikosR** [comment]
Please read https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/#rtl

@mdo we should probably edit the GH release and add HUGE BUG RED warnings and link to sources with more info

**Comment by XhmikosR** [comment]
And https://getbootstrap.com/docs/5.0/migration/#rtl

**Comment by krosoftware** [comment]
Awesome, thanks.
