### ISSUE TITLE
v5: Enable negative margins by default

### ISSUE THREAD

**Issue by morrissey-ingenious** [twbs/bootstrap#32385]
Can we please have

`$enable-negative-margins: true` enabled by default in v5  [ v4.x has this enabled by default and having to custom build bootstrap v5 to enable this seems like a step backwards ]

Thanks

**Comment by XhmikosR** [comment]
@mdo @MartijnCuppens might be worth checking how much this adds again? I don't recall the exact reasons we dropped this.

**Comment by MartijnCuppens** [comment]
File size & it becoming less relevant since we only used (read: documented) it for the responsive grid gutters.

I'm ok enabling it by default if that doesn't hurt file size to much and if we add some decent documentation.

**Comment by mdo** [comment]
I think it's better to leave it disabled for now. No need to rush back into it in the beta process.

**Comment by XhmikosR** [comment]
I only added it in beta2 so that we track it; we can add it later if needed.

**Comment by milesimarco** [comment]
I would appreciate negative margins enabled by default too.

**Comment by harnishdesign** [comment]
> 
> 
> I would appreciate negative margins enabled by default too.

Yes, We also.

**Comment by mdo** [comment]
Still planning to skip this for now. I don't feel comfortable adding these given the gutter classes cover our biggest use case IMO, and that it's easy to customize.

**Comment by harpreetsb** [comment]
Is this resolved or never gonna happen?
I am not an expert to compile bootstrap. It would be nice of you can provide a CDN link with negative margins

**Comment by Roffa23** [comment]
So, where do I put the $enable-negative-margins: true ?

**Comment by morrissey-ingenious** [comment]
_variables.scss

https://github.com/twbs/bootstrap/blob/367caea501b77b23afee9d49a1f678040767f341/scss/_variables.scss#L353

**Comment by harnishdesign** [comment]
how can i enable negative margins for RTL version ? @mdo

**Comment by ffoodd** [comment]
@harnishdesign Enable it as already mentionned, then postprocess the compiled CSS using RTLCSS as explained in our RTL doc.

**Comment by harnishdesign** [comment]
@ffoodd I have try something below in my custom (stylesheet.scss) file. it does enable and generate negative margin css. but, it does not generate any RTL css. Here, I am confused. can you please guide with an example. It would be great.

**stylesheet.scss** 
```
@import "bootstrap/functions";
@import "bootstrap/variables";
@import "bootstrap/mixins";
@import "bootstrap/vendor/rfs";

$enable-negative-margins: true #{/* rtl:true */};

@import "bootstrap/bootstrap";

// Initialize
@import "variables";
@import "mixins";

// Core CSS
@import "reset";
@import "helpers";
@import "layouts";

// Content Blocks
@import "header";
@import "profile";
@import "blog";
@import "elements";
@import "footer";
@import "extras";
```

**Comment by ffoodd** [comment]
You need to postprocess your CSS output using RTLCSS, as [explained in our docs](https://getbootstrap.com/docs/5.1/getting-started/rtl/#approach). RTLCSS is a dependency, just like Sass, and it runs on your CSS files to generate their RTL counterparts.
