### ISSUE TITLE
v5 Beta text-right doesn't work

### ISSUE THREAD

**Issue by fawazahmed0** [twbs/bootstrap#32382]
It was working fine in alpha version.

**Bootstrap Alpha 5 (works fine):**
![BS Alpha](https://user-images.githubusercontent.com/20347013/101500547-a0c2dc00-3994-11eb-8593-c077c38071af.jpg)

**Bootstrap Beta 5 (Not working properly):**
![BS beta bug](https://user-images.githubusercontent.com/20347013/101500576-ac160780-3994-11eb-804f-e21ae1963a85.jpg)

**Codepen:**
[Alpha 5(works fine)](https://codepen.io/fawazahmed0/pen/BaLzMZo)

[Beta 5 (Don't work)](https://codepen.io/fawazahmed0/pen/qBaNgrJ)

Thanks

**Comment by MichiBeck** [comment]
Hello @fawazahmed0 ,

perhaps this documentation helps:
[https://getbootstrap.com/docs/5.0/getting-started/rtl/](https://getbootstrap.com/docs/5.0/getting-started/rtl/)

The new Beta is with RTL support so this migrations are important to notice:
[https://getbootstrap.com/docs/5.0/migration/#v500-beta1](https://getbootstrap.com/docs/5.0/migration/#v500-beta1)

**Comment by ffoodd** [comment]
`.text-right` is replaced with `.text-end` in beta 1, precisely to ease with RTL implementation. Please read our [migration guide with a comphrensive list of what changed to support RTL in beta 1](https://getbootstrap.com/docs/5.0/migration/#rtl).

Basically every `left` and `right` related classes are renamed to `start` and `end` equivalents.

**Comment by fawazahmed0** [comment]
Thanks
