### ISSUE TITLE
Browser autocomplete options obscure .form-text

### ISSUE THREAD

**Issue by AmProsius** [twbs/bootstrap#32403]
## The Problem
I recently came across the usability problem that the browser's autocomplete options obscure the help text of form elements. This seems like an old issue that has been discovered before ([Avoid messages under fields](https://adrianroselli.com/2017/01/avoid-messages-under-fields.html "by Adrian Roselli"), [Form design](https://gerireid.com/forms.html#text-input "by Geri Reid")).

![alt text][issue 1]
![alt text][issue 2]

## The Solution
The solution would be to move the `.form-text` up. This seems to be an easy fix as it is mostly docs related. The CSS changes would only include removing the `margin-top` from `.form-text` and adding a `margin-bottom: .5rem`.
``` html
<div class="mb-3">
  <label for="exampleInputEmail1" class="form-label">Email address</label>
  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
</div>
```
``` css
.form-text {
    /* margin-top: .25rem; */
    margin-bottom: .5rem;
    font-size: .875em;
    color: #6c757d;
}
```

![alt text][solution 1]
![alt text][solution 2]

## Development

If that is something of interest here, I would like to work on a pull request. Of course I am open for discussion on this matter.

[issue 1]: https://amprosius.de/issue_form_text_1.jpg
[issue 2]: https://amprosius.de/issue_form_text_2.jpg
[solution 1]: https://amprosius.de/issue_form_text_3.jpg
[solution 2]: https://amprosius.de/issue_form_text_4.jpg

**Comment by mdo** [comment]
I think this entirely depends on your setup. You're more than welcome to put form text anywhere—I suggest embracing some utilities if you need them, too, for optimal positioning.
