### ISSUE TITLE
[Feedback] new names of utilities classes look weird in bootstrap 5.0 beta-1.

### ISSUE THREAD

**Issue by TanvirArjel** [twbs/bootstrap#32402]
`.ms-*` for `margin-left` does not make sense. There is nothing called `margin-start`.`.ml-*` looks more readable and meaningful for margin-left.

Please keep all the utilities classes names as same as bootstrap 4.x. 

Most importantly, changing the utilities classes names will make v4.x to v5.0 upgradation impossible.

Thank you.

**Comment by patrickhlauke** [comment]
the new shorthands work in combination with the RTL work, which replaces terms such as "left" and "right" with more universally applicable ("start" and "end").

**Comment by patrickhlauke** [comment]
> Most importantly, changing the utilities classes names will make v4.x to v5.0 upgradation impossible.

there are many more differences between 4.x and 5.x - jumping between major versions always requires fundamental changes
