### ISSUE TITLE
Dropdown offset option is ignored v5

### ISSUE THREAD

**Issue by joke2k** [twbs/bootstrap#32418]
With v5 the dropdown feature doesn't work with offset property.
Maybe related to #32354

It doesn't work also in the documentation:
https://getbootstrap.com/docs/5.0/components/dropdowns/#dropdown-options

The v5 version of dropdown doesn't collect the offset:
https://github.com/twbs/bootstrap/blob/1edec546cb28baf68691f0eb9e43997901359ba5/js/src/dropdown.js#L292-L308

The v4 yes:
https://github.com/twbs/bootstrap/blob/1edec546cb28baf68691f0eb9e43997901359ba5/js/src/dropdown.js#L292-L308

**Comment by XhmikosR** [comment]
As you can see on https://getbootstrap.com/docs/5.0/migration:

>Removed offset option from our Tooltip/Popover and Dropdown plugins; this can still be achieved using the popperConfig parameter.

I guess we need to fix the docs, though.

**Comment by joke2k** [comment]
HI @XhmikosR thank you

In this way is not possible to use with data-bs- attributes anymore?
In order to use `offsets` for dropdown i should put 
```
{
  modifiers: [
    {
      name: 'offset',
      options: {
        offset: [10, 20],
      },
    },
  ],
}
```
into the `data-bs-popperConfig="???"` attribute?

**Comment by XhmikosR** [comment]
Yeah, although TBH I'm not sure how one would use an object in `data-bs-popperConfig`.

I'm open to any suggestions/improvements!

**Comment by peheje** [comment]
> Yeah, although TBH I'm not sure how one would use an object in `data-bs-popperConfig`.
> 
> I'm open to any suggestions/improvements!

You can set it in javascript after you have loaded bootstrap js

`bootstrap.Dropdown.Default.popperConfig = {
  modifiers: [
    {
      name: 'offset',
      options: {
        offset: [0, 14],
      },
    },
  ]
}`

**Comment by peheje** [comment]
> HI @XhmikosR thank you
> 
> In this way is not possible to use with data-bs- attributes anymore?
> In order to use `offsets` for dropdown i should put
> 
> ```
> {
>   modifiers: [
>     {
>       name: 'offset',
>       options: {
>         offset: [10, 20],
>       },
>     },
>   ],
> }
> ```
> 
> into the `data-bs-popperConfig="???"` attribute?

You can set it in javascript after you have loaded bootstrap js

`bootstrap.Dropdown.Default.popperConfig = {
  modifiers: [
    {
      name: 'offset',
      options: {
        offset: [0, 14],
      },
    },
  ]
}`
