### ISSUE TITLE
rename accordian class

### ISSUE THREAD

**Issue by imithu** [twbs/bootstrap#32422]
# Accordion

rename the class of `.accordion-button` to `.btn-accordion`

Thanks for the beautiful bootstrap framework.
**Love Bootstrap**

**Comment by mdo** [comment]
Since going beta, we cannot rename things as they'd account as breaking changes. In this case, I'm also of the opinion that the class name is correct. The suite of classes is `.accordion-*` whereas `.btn-*` signals a different type of component.

**Comment by patrickhlauke** [comment]
FWIW agree with @mdo ... it's not a button variant, but rather the button is an instrinsic part of an accordion
