### ISSUE TITLE
Bootstrap@5.0.0-beta1 color clash with active list-group + link

### ISSUE THREAD

**Issue by michalbachowski** [twbs/bootstrap#32433]
When `list-group-item` is `active` and contains a link (`<a />`) inside, the color of link and background are the same. See [example for Bootstrap@5.0.0-beta1](https://jsbin.com/hagapitoru/2/edit?html,output)

**Comment by mdo** [comment]
We can't unilaterally change link colors unfortunately. if you had custom markup, even a dropdown menu, it could override that on accident. Best course here is a utility class IMO.

**Comment by michalbachowski** [comment]
When `active` class is added, the text color is changed to white, but links are left intact - I would expect some more consistent behavior.
Using utility classes adds some additional work when trying to manage the state dynamically (it is just more to do than simply toggling one class).
But ofc, if changing this is a problem, then using `.text-info` for the `active` state would be the simplest solution.

**Comment by aribudin** [comment]
build custom scss
`.list-group-item {
  &.active {
    a {
      color: #fff;
      text-decoration: none;
      &:hover {
        color: #fff;
        text-decoration: underline;
      }
    }
  }
}`

**Comment by michalbachowski** [comment]
OK, so I know how to change the default behavior.
But still he default behavior is--in my opinion--sub-optimal.
But as @mdo stated - changing the default behavior might be surprising for others.
Given that I think this ticket can be closed.

Thanks!

**Comment by mdo** [comment]
Closing per last comment.
