### ISSUE TITLE
Bootstrap issue on v5.0.0-beta1

### ISSUE THREAD

**Issue by Manu785** [twbs/bootstrap#32432]
In the v5.0.0-beta1 the modifier classes .table-light or .table-dark won't work.

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

**Comment by ffoodd** [comment]
BTW they do work on our side: https://getbootstrap.com/docs/5.0/content/tables/#variants — so please fill our issue template requirement if you want some help.

**Comment by Manu785** [comment]
Hi,
it didn't work for me so I used a previous version of Bootstrap and
everything worked as should. If it works for you then it's all good.
I'm going to test it to once more and let you know.

Il ven 11 dic 2020, 10:56 Gaël Poupard <notifications@github.com> ha
scritto:
