### ISSUE TITLE
v5: Update docs to add system-ui to beginning of native font stack

### ISSUE THREAD

**Issue by alanorth** [twbs/bootstrap#32447]
Since Bootstrap v4 the native font stack has used Roboto on Linux. [According to the docs](https://getbootstrap.com/docs/5.0/content/reboot/) it is the same in v5 (beta1 currently), but in my Arch Linux environment it ends up selecting Cantarell in both Firefox and Chromium.

v4.5 Album example with Roboto:

![2020-12-12T15:45:42,196713687+02:00-fs8](https://user-images.githubusercontent.com/191754/101985748-8c335c00-3c92-11eb-8a95-a16be6329742.png)

v5.0 Album example with Cantarell:

![2020-12-12T15:56:39,897765933+02:00-fs8](https://user-images.githubusercontent.com/191754/101985777-b84edd00-3c92-11eb-9d40-ea41f255814f.png)

My environment is:
- Arch Linux
- Firefox 84.0b8 (but behaves the same in Chromium)
- Wayland
- Sway window manager

**Comment by XhmikosR** [comment]
Can you try <https://v4-dev--twbs-bootstrap.netlify.app/docs/4.5/examples/album/> too?

I wonder if it's related to the changes you made @ffoodd? BTW those are backported to v4-dev too right now.

**Comment by septatrix** [comment]
I guess the documentation is not up-to-date. `system-ui` is listed at the front of the font stack in the devtools. Also Cantarell is not listed in the fonts. Do you by any chance have that font set as your system font.

This would explain the behaviour for Chromium at least (as I could not reproduce it). Firefox however does not seem to support `system-ui` yet but only supports `-apple-system` on MacOS only. My guess for Firefox would be that Arch maybe has some flags enabled in their builds?

**Comment by septatrix** [comment]
Maybe check on MDN what font is used when you select `system-ui`: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by alanorth** [comment]
@septatrix Yes you are correct! When I check `system-ui` on MDN the browser uses Cantarell indeed.

![2020-12-12T17:57:35,233732080+02:00-fs8](https://user-images.githubusercontent.com/191754/101988737-42537180-3ca4-11eb-8af3-e0fe06285bf5.png)

So this is a platform issue, not a Bootstrap issue. It's unclear to me how Firefox/Chromium determine that my system font is Cantarell as I'm not using GNOME and my Sway font is Source Sans Pro, but that's not Bootstrap's problem. :)

I think we can close this?

(And yes, it seems the docs are out of date and `system-ui` is now at the front of the font stack)

**Comment by septatrix** [comment]
I think you should leave this open (and maybe adjust the title) until the docs are fixed.

**Comment by alanorth** [comment]
@septatrix I changed the title to something more appropriate. Not sure if there is anything Bootstrap can do here. At least in my environment it behaves the same way on Firefox stable (83), Firefox Developer Edition (84), Firefox Nightly, and Chromium 87.0.4280.88.

**Comment by septatrix** [comment]
No the behaviour is definitely correct. Bootstrap defaults to you system font if you browser exposes it. However Bootstrap should fix the documentation which does not list `system-ui` in the font stack nor do they mention it anywhere (which I think is important as different fonts may lead to layout shifts etc.). In v4 this only applied to MacOS and probably iOS but now this is also the behaviour on other operating systems.

**Comment by alanorth** [comment]
OK, I think I understand this now. On Linux it all comes down to fontconfig's configuration, which may be managed by the desktop environment (GNOME, KDE, etc) in your home directory or by the defaults shipped in the distro's fontconfig itself (`/etc/fonts`). In my case, on Arch Linux, the default configuration for Latin sets `Cantarell` as the alias for `system-ui`, see:

- /etc/fonts/conf.avail/45-latin.conf
- /etc/fonts/conf.avail/60-latin.conf

Cantarell is required by gtk-3.0 so I can't remove it, but I overrode the defaults to use a different font in `~/.config/fontconfig/fonts.conf`. This solves the mystery and makes Bootstrap v5 look better in my environment. For all the other Linux users I am not sure they will notice—they will just see things a little bland with Cantarell, but at least it's native.

The v5 docs still need to be updated to reflect the fact that `system-ui` was moved to the beginning of the font stack. And caniuse.com should be updated to say that `system-ui` works on Firefox now...

**Comment by septatrix** [comment]
Following you explanation it rather seems like arch sets `system-ui` to be a font(-alias) which firefox uses instead of firefox actually supporting `system-ui`

**Comment by alanorth** [comment]
@septatrix Oh yes, you're right: it's just an alias, so Firefox _doesn't_ support `system-ui`. I will try to submit a pull request to update the docs about the font stack.
