### ISSUE TITLE
duplicate “pe-auto”

### ISSUE THREAD

**Issue by xiaohulu** [twbs/bootstrap#32444]
version v5.0.0-beta1

there is a `pe-auto` in utilities/spacing，and `pe-auto` in utilities/interactions/.

**Comment by ffoodd** [comment]
As mentionned [in our Spacings documentation](https://getbootstrap.com/docs/5.0/utilities/spacing/), `auto` does not exist for `padding`s—only for `margin`s.

I checked our dist file to ensure, but there's a single `.pe-auto` for `pointer-events`.
