### ISSUE TITLE
Modal problem on Chrome/IOS

### ISSUE THREAD

**Issue by tansut** [twbs/bootstrap#32454]
Steps to reproduce:

1. Goto https://getbootstrap.com/docs/4.0/components/modal using iPhone/Chrome
2. Scroll to Live Demo
3. Click Launch
![IMG_4547F76A2A72-1](https://user-images.githubusercontent.com/3591623/102006620-65793200-3d33-11eb-89b2-567df5ca270e.jpeg)

**Comment by patrickhlauke** [comment]
can't replicate on iPhone 7. what phone are you seeing the problem on? additionally, worth noting that Bootstrap 4.0 is quite an outdated version at this point - i'd check https://getbootstrap.com/docs/4.5/components/modal/

**Comment by tansut** [comment]
![6260D59B-EFA9-412B-ABB3-B19D165BB7E9](https://user-images.githubusercontent.com/3591623/102017017-3f748180-3d75-11eb-8e1f-744a691f6389.png)

Similar problem for 4.5.

**Comment by patrickhlauke** [comment]
tried on an iPhone 11 now as well, and can't repro I'm afraid.

**Comment by PeakVisionMediaKLG** [comment]
Maybe clear the browser cache?

**Comment by XhmikosR** [comment]
Closing per @patrickhlauke's comments.
