### ISSUE TITLE
[v5] sliding items for list views

### ISSUE THREAD

**Issue by spahno** [twbs/bootstrap#32456]
Hey, how about adding sliding items to bootstrap? I really enjoy using them, when I use Ionic. Especially for mobile views, it would be really helpful to have this feature **out of the box**.

Feel free to discuss... 😊

<img width="385" alt="sliding item" src="https://user-images.githubusercontent.com/56961433/102013546-31146e80-3d51-11eb-8af3-ad62b31f27c7.png">

Image source: https://ionicframework.com/docs/v3/api/components/item/ItemSliding/

**Comment by mdo** [comment]
Don't think we'd provide the JS for this, which makes it kind of moot overall. Closing with no plans to implement it ourselves. Seems perfect for a community plugin/addon.
