### ISSUE TITLE
V5 Beta 1: consider keeping left & right as aliases for start & end utilities

### ISSUE THREAD

**Issue by bestguy** [twbs/bootstrap#32450]
The RTL support is very nice and appreciated, however I think it would be helpful to ease in a big change like this for utilities such as `ml-* mr-* pl-* pr-*` and keep them as aliases to start and end.

This will be a point of confusion for many and result in a lot of changes given we are still keeping the top and bottom utilities.

Search and replace is not necessarily trivial for these short class names.

I realize local, in app overrides are an option for some, but this is more than a few classes to generate and requires a full custom build to pick up the correct values.

**Comment by ffoodd** [comment]
Hi there,

This is [already discussed](https://github.com/twbs/bootstrap/discussions/32402) and you may want to share your thougts there. Aliasing defeats the whole point of switching to logical names, as explained in the discussion.

FWIW, [as mentionned in the discussion too](https://github.com/twbs/bootstrap/discussions/32402#discussioncomment-194697), using our utility API makes it a breathe to either alias or rename utilities.

Upgrading to a major release is never trivial: we made several breaking changes and renamings that you'll need to handle while upgrading. We did our best to ease upgrading, and [our migration guide contains a comprehensive list of changes](https://getbootstrap.com/docs/5.0/migration/).

**Comment by bestguy** [comment]
Thanks for the link, but if your comment stands:

> To sum up, we won't roll this back and if you want to upgrade, you'll need to read our migration guide

Then no need in discussing further I'd assume?   Feel free to close if so.

My opinion is that if still CSS supports both `margin-block-start` and more common `margin-left` that seems reasonable to alias ml to ms and support both for margins, etc.   RTL support is great, but many sites are not i18n capable anyways in the language text needed for RTL, so making people think start/end in Bootstrap V5 isn't enough on its own.

**Comment by ffoodd** [comment]
@bestguy I see your point, however aliasing would have major drawbacks:

- codebloat, obviously: we're talking about utilities with many, many variants and that would impact filesize;
- clarity: having two names for the same things would confuse more than simply get used to a new name;
- consistency: this would result in `.float-left { float: right; }` in RTL, even if it's an alias it'd still be absurd;
- maintainability: more things to check, and to support.

Moreover it's really easy to change in a custom build: we may enforce our docs in this way, to ensure anyone understand how to rename things—but keeping both in our core doesn't make any sense.

Other team members may weigh in at some point, however we've been working and questionning this for months now and this felt the better way to support RTL in Bootstrap.

**Comment by ffoodd** [comment]
So, I'm gonna close this in favor or [the existing discussion](https://github.com/twbs/bootstrap/discussions/32402) and [issue regarding remaining RTL tasks](https://github.com/twbs/bootstrap/issues/32330).

There're several ways to handle this on your side using Sass, and I aim at improving and mentionning those ways in our docs.
