### ISSUE TITLE
Tooltip disappears BS5 Beta1

### ISSUE THREAD

**Issue by pwagsc** [twbs/bootstrap#32470]
Windows 10 Chrome or Edge on Intel 9900

Go to bootstrap 5 documentation for Tooltip on BS site https://getbootstrap.com/docs/5.0/components/tooltips/ .  Move cursor rapidly on and off a tooltip exposing element - any on page, they will all fail eventually.  At first it will flash on and off with cursor moving on and off hover (normal), then it will stop appearing whether hovering or not until browser refresh.  Occasionally the tooltip will show up elsewhere on the page permanently until browser refresh.

Go to bootstrap 4 docs, repeat, and it will keep working just fine.

Initially appeared on custom web app but discovered it fails the same on your own site so thought that would be easier for you to troubleshoot.

Also noticed that placing a tooltip on a TD element that contains an INPUT element fails rapidly (compared to you site).  It also does not display if hovering over the INPUT element, only on the TD element.  On BS4 it displayed when hovering over either.  Thought this might be a helpful clue.

**Comment by florianlacreuse** [comment]
Duplicate #32372

**Comment by patrickhlauke** [comment]
Indeed.

**Comment by pwagsc** [comment]
Don’t know how to comment on issue in Github so am replying.

Agree this was a duplicate.

Found problem if you haven’t already.  Issue is that BS is starting to process a tooltip “leave” before the delay expires on the previous enter/show (thus the ‘complete’ function has not been executed yet).  So you start processing the leave and the show complete occurs immediately after the leave executes its leave transition. (or a show may kick off before a leave executes its complete)  Depending on timing this sometimes causes the tooltip object to be deleted but the tooltip element remains in the show state.  So the enter and leave will not execute (enter because the element says its showing and leave because the tooltip object has been destroyed.  Simply add data-bs-animation='false'  and everything works fine.  I will leave it to you to add appropriate code to flag a previous show or hide is pending and process the new request appropriately (kill the animation event and execute the complete before processing new event??).

Cheers,  Paul
