### ISSUE TITLE
Dropdown menu not positioned correctly with .dropstart

### ISSUE THREAD

**Issue by kyletsang** [twbs/bootstrap#32484]
When using `.dropstart`, the dropdown menu will cover most of the toggle button.  

Seems like this is caused by this style:
https://github.com/twbs/bootstrap/blob/042a4a255f3c994ee8285df9a14fe0fbd95df83c/scss/_dropdown.scss#L36-L39

If I disable this style, the menu is positioned correctly.

This can be reproduced on the docs page:
https://getbootstrap.com/docs/5.0/components/dropdowns/#dropleft

- Operating system and version: Windows
- Browser and version: All

**Comment by XhmikosR** [comment]
@ffoodd @MartijnCuppens any ideas?

**Comment by ffoodd** [comment]
I confirm the bug. From my understanding, `.dropstart` should be an exception here and set `left` to `auto` instead of `right`—but cannot check it out for now.

**Comment by martinbarilik** [comment]
Dropstart is meesy at the moment, when can we expect a fix ?
