### ISSUE TITLE
"Start" = left?

### ISSUE THREAD

**Issue by cbglobe** [twbs/bootstrap#32482]
I think you have made a bad choice changing to start/end. The terms change with the situation while left/right, especially on a web page, are obvious. A paragraph does not start at the left, it starts at the top. You could say a heading starts at the left but it still has a top, bottom, left and right. An image has neither a start nor stop, but, again, has a top, bottom, left and right. I think you may want to rethink those changes.

**Comment by mdo** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

Naming comes from the CSS spec.
