### ISSUE TITLE
Popover arrow styling issues

### ISSUE THREAD

**Issue by kyletsang** [twbs/bootstrap#32485]
Looking at the examples in https://getbootstrap.com/docs/5.0/components/popovers/#four-directions, I noticed a couple issues:

- The popover arrow isn't centered with the toggle button
- The border from the popover body is visible between the arrow and the popover.

![image](https://user-images.githubusercontent.com/6854874/102179629-56da6a00-3e5c-11eb-8420-d24c85763ead.png)

- Operating system and version: Windows
- Browser: Firefox 83.0

**Comment by XhmikosR** [comment]
I recall discussing this with @MartijnCuppens the other day. I don't think this is fixed right now on main.

**Comment by wojtask9** [comment]
@XhmikosR 
Some time ago i tried to fix these issues. See https://github.com/twbs/bootstrap/pull/23936 but my MR was closed without merge. This issues occurs also in BS4.

With my fix (probably BS4-beta) see old codePen https://codepen.io/anon/pen/gxNxZw

**Comment by XhmikosR** [comment]
@wojtask9 That PR is pretty old and this specific issue is for v5.

But if you think you have a solution for main, please make a PR against main. If the PR lands, we can backport it on v4-dev, assuming it's a non-breaking change.

**Comment by wojtask9** [comment]
@XhmikosR border it is not related to only v5. It occurs in v4 if you change "zoom" in browser. See

![image](https://user-images.githubusercontent.com/6099236/102191706-0f82c680-3eba-11eb-811b-aa78a8036ac0.png)

I'm unsure about arrow position.

I'll try to do MR but unsure what is "braking change" in terms of css :)

**Comment by alecpl** [comment]
You could try setting `margin: 0` on `.bs-popover-auto[data-popper-placement^="right"] > .popover-arrow, .bs-popover-end > .popover-arrow`

**Comment by devfakhzan** [comment]
> Looking at the examples in https://getbootstrap.com/docs/5.0/components/popovers/#four-directions, I noticed a couple issues:
> 
> * The popover arrow isn't centered with the toggle button
> * The border from the popover body is visible between the arrow and the popover.
> 
> ![image](https://user-images.githubusercontent.com/6854874/102179629-56da6a00-3e5c-11eb-8420-d24c85763ead.png)
> 
> * Operating system and version: Windows
> * Browser: Firefox 83.0

Has this been resolved? Because in my Firefox 83.0 (64-bit) on Windows 10, I cannot replicate this issue, even when zooming in:

![image](https://user-images.githubusercontent.com/74360680/103189607-664fbd80-4908-11eb-9f3c-634204affe39.png)

> You could try setting `margin: 0` on `.bs-popover-auto[data-popper-placement^="right"] > .popover-arrow, .bs-popover-end > .popover-arrow`

Also like @alecpl have mentioned, the non-center arrow head is not actually a bug from what I can see, it's purposely set to have `.3rem` margin from the center (either vertically or horizontally, depending on the side of the the arrow head) and setting `margin: 0` to the appropriate selector like the above will make the arrow head centered.

**Comment by alecpl** [comment]
I didn't say it's not a bug. My opinion is the opposite. It needs to be fixed.

**Comment by mdo** [comment]
Opened #32787 to address this.
