### ISSUE TITLE
Please add negative space default

### ISSUE THREAD

**Issue by veeruk0217** [twbs/bootstrap#32505]
Please add negative space default

**Comment by patrickhlauke** [comment]
meaning...what exactly? You'll have to provide a bit more information here rather than this very generic statement...

**Comment by Hiws** [comment]
Maybe he refers to enabling the negative margin utilities by default.
The same as this issue: https://github.com/twbs/bootstrap/issues/32385

**Comment by XhmikosR** [comment]
Duplicate of #32385
