### ISSUE TITLE
Popper fallback leads to worse layouting

### ISSUE THREAD

**Issue by septatrix** [twbs/bootstrap#32506]
Commit f132400865217ccc83dd31bb53bb8f584a1a6f2f introduced a regression (or at least I would classify it as such).
Dropdowns close to the right screen edge overflow instead of being show the the left.
I simply used a `textarea` and the example code from the docs with an inline utility class.
This allows me to simple move the button to the right edge.

The following screenshots show the behaviour (with the black area being the devtools).

Dropdown not shown
![Screenshot from 2020-12-16 15-50-49](https://user-images.githubusercontent.com/24257556/102365674-1a238580-3fb8-11eb-84e9-c3e7a4092011.png)

Dropdown behaviour after the commit.
![Screenshot from 2020-12-16 15-50-54](https://user-images.githubusercontent.com/24257556/102365680-1b54b280-3fb8-11eb-9583-129a48269998.png)

Dropdown behaviour before the commit.
![Screenshot from 2020-12-16 15-52-11](https://user-images.githubusercontent.com/24257556/102365682-1b54b280-3fb8-11eb-8af2-c7981777853c.png)

<hr>

- Operating system and version: Linux - Ubuntu 20.10
- Browser and version: Chrome 87

I am unable to give an example to reproduce as the changed code is not yet in a release (and I currently do not have the time to compile and self-host).

**Comment by XhmikosR** [comment]
Should be fixed by #32437 already, /CC @rohit2sharma95

**Comment by rohit2sharma95** [comment]
@septatrix can you please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) :slightly_smiling_face: 
@XhmikosR That PR is just for Tooltip/Popover and updates the docs and default value. Although, default fallback placement has been changed in dropdown also and should be mentioned in the docs.

**Comment by XhmikosR** [comment]
Oh, indeed. Can you make a PR referencing the PR that changed it and adapting the docs later please?

**Comment by septatrix** [comment]
Test: https://jsbin.com/nabugatehu/edit?html,output (Output panel was set to 1200px width)

As explained earlier I had to compile the current state of the main branch as it is not in npm yet.
To switch between the `beta-1` release and the current state of `main` (which still has the regression) toggle the comments in the header.
The referenced files were generated by running `npm run dist` and uploaded to a fork.

**Comment by NightZan999** [comment]
Happens to me too.

**Comment by NightZan999** [comment]
You could try the float : left; in CSS with the class to fix the issue  @septatrix

**Comment by septatrix** [comment]
Disabling `right: auto!important;` for `.dropdown-menu[style]` seems to fix the issue partially. It leads to a better result than currently but still worse than beta-1 IMO.

**Comment by septatrix** [comment]
> Disabling `right: auto!important;` for `.dropdown-menu[style]` seems to fix the issue partially. It leads to a better result than currently but still worse than beta-1 IMO.

This is also a suggested fix for #32484

**Comment by rohit2sharma95** [comment]
Fixed in #32843 and #32986

https://jsbin.com/goparegilu/edit?html,output
