### ISSUE TITLE
Update Translations application

### ISSUE THREAD

**Issue by zoomla** [twbs/bootstrap#32500]
We are the maintenance team of the bootstrap Chinese Language website,Glad to see Boostrap 5 published beta1.
This is A exciting news！

Now， We apply to Update Translations page's Chinese Language website link,
Here is the new information：
Title:   Bootstrap 5 · 全球最流行的 HTML、CSS 和 JS 工具库
Url:  http://code.z01.com/bootstrap

At the same time, we will continue to optimize Chinese translation, so that our products can be known and adopted by more users, and contribute to the development of the Internet!

Thinks!

-- by Zoomla! CMS Team(boostrap Chinese Language website maintainer)

**Comment by XhmikosR** [comment]
We only accept PRs regarding the translations. You can make a PR if you want.
