### ISSUE TITLE
Bug in margin left auto

### ISSUE THREAD

**Issue by imranbarbhuiya** [twbs/bootstrap#32514]
I was trying to place all the link parts in the navbar to the right using ml-auto, but it is not going to the right. it is only happening in 5.0.0 beta1 version. Hope you will fix it.

**Comment by patrickhlauke** [comment]
> Bug reports must include:
>
>- Operating system and version (Windows, macOS, Android, iOS)
>- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
>- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by ffoodd** [comment]
`.ml-auto` is renamed to `.ms-auto`, standing for `margin-start`—and every horizontal spacing properties are renamed this way.

Please read [our migration guide](https://getbootstrap.com/docs/5.0/migration/) while upgrading.

**Comment by imranbarbhuiya** [comment]
Thank you.
