### ISSUE TITLE
(BS 5) Radio and checkbox buttons not being properly styled on mobile using the SASS files

### ISSUE THREAD

**Issue by tiagorocha1979** [twbs/bootstrap#32522]
### [UPDATED]
Apparently the issue was with the **.form-check-input** selector, around line 2233, where it should have **-webkit-appearance: none;** but it doesn't. Once I've added that line, everything came back to normal. 

### Original issue
I've downloaded both source and compiled files (Bootstrap 5) to test both scenarios.
Here's what's happening:

Compiling the SASS files ends up giving me a shorter CSS file (I used all other files, no scss file is left "un-imported"). I even "beautified" both CSS files (both the precompiled and the one compiled by me) to make them look as similar as possible. Even used a tool online to compare both and there are slight differences between them.

When viewing the website on my laptop, no issues. When viewing on mobile, it styles the checkbox and radio buttons properly when I use the precompiled file (longer css), but not when I use the file compiled using the SASS files. Also used the Autoprefixer online to add support to the file compiled from the SASS files, thinking that would solve the problem, but no luck.

Everything seems to be styled properly, at least so far. Only those two seem to be having this bug.

**How it looks like**
![IMG_0619](https://user-images.githubusercontent.com/60773713/102546511-a82e6780-40af-11eb-9ee0-1ffd0e76651c.png)

**How it was supposed to look like**
![IMG_0620](https://user-images.githubusercontent.com/60773713/102546513-a95f9480-40af-11eb-9ac8-f4689d875605.png)

Any idea why this happens and how to fix it?

**Comment by mdo** [comment]
If you're compiling the source Sass files yourself, make sure you're running Autoprefixer.
