### ISSUE TITLE
[v5] bg-dark class disappears when overriding $theme-colors

### ISSUE THREAD

**Issue by adro21** [twbs/bootstrap#32538]
- macOS
- Chrome Version 87.0.4280.88 (Official Build) (x86_64)

When overriding $theme-colors, the .bg-dark class is no longer found in the compiled CSS. I'm not sure what other classes are missing, but I can confirm .bg-dark no longer appears. If I remove the $theme-colors override, and just simply use 

`@import "../node_modules/bootstrap/scss/bootstrap"; `

On it's own, the .bg-dark class is present in compiled CSS.

**Comment by hvsh** [comment]
Make sure your $theme-colors map has dark key value

**Comment by adro21** [comment]
@hvsh If I'm overriding just a few values in $theme-colors, do I need to list every possible one? I thought that I could just override the ones I wanted to change..?

**Comment by hvsh** [comment]
If you are only changing values of variables that are already present in the $theme-colors, you don't have to add $theme-colors to your scss file. If you are wanting to add more colors to the $theme-colors that are not already present then yes you should have all the key value pairs. You are basically overriding the map with your own.

**Comment by adro21** [comment]
Ahhh ok, thanks! Sorry, a bit new to customizing Bootstrap... If I'm trying to add a new color to the $theme-colors map using map-merge, I'm getting an error that $theme-colors is undefined. Does this mean I need to declare $theme-colors and all possible values in my scss file in order to add a color to it?

This is what I have:

```
$custom-colors: (
  "custom-color": #900
);

$theme-colors: map-merge($theme-colors, $custom-colors);
    
@import "../node_modules/bootstrap/scss/bootstrap";
```

Which throws this error:

```
Compilation Error
Error: Undefined variable: "$theme-colors".
        on line 8 of sass/Users/adam/Dropbox (Personal)/current-projects/bqnext/sass/custom.scss
>> $theme-colors: map-merge($theme-colors, $custom-colors);
```

**Comment by hvsh** [comment]
No apologies needed! Its probably because you are importing your Scss file before the bootstrap variables file where $theme-colors is defined. 

I would just use $theme-colors in your scss and just add all the values you need.
`
$newvar1 = #fff;
$newvar2 = #000;

$theme-colors: (
  "primary":      $primary,
  "secondary":  $secondary,
  "success":      $success,
  "info":            $info,
  "warning":     $warning,
  "danger":      $danger,
  "light":          $light,
  "dark":          $dark,
  "newvar1":   $newvar1,
  "newvar2":   $newvar2
) ;`

**Comment by Northwestor** [comment]
thanks so much,really new to this
just trying to set up a viewbot of 60 people.and messed alot of stuff up

**Comment by adro21** [comment]
@hvsh Oh ok! Does that mean the @import needs to always go above the $theme-colors override? I also tried something like this and it seems to have worked:

```
// Required
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";

$custom-colors: (
  "custom-color": #900
);

$theme-colors: map-merge($theme-colors, $custom-colors);
    
// Optional
@import "../node_modules/bootstrap/scss/alert";
@import "../node_modules/bootstrap/scss/badge";
@import "../node_modules/bootstrap/scss/breadcrumb";
@import "../node_modules/bootstrap/scss/button-group";
@import "../node_modules/bootstrap/scss/buttons";
@import "../node_modules/bootstrap/scss/card";
...
```
I'm guessing this is probably a better way to do it anyway since in production I probably wouldn't want to import the entire bootstrap scss if I'm not using every part...?

**Comment by hvsh** [comment]
I copy the entire bootstrap variable file to my own and import that one with whatever changes I need.

**Comment by adro21** [comment]
Oh interesting! Has that caused problems in the past if you've ever tried to update bootstrap?

**Comment by hvsh** [comment]
Nothing that I can recall causing hassle

**Comment by adro21** [comment]
@hvsh Thanks! Hate to keep bugging you, but had one more question I just can't seem to figure out along similar lines. 

Following the docs [here](https://getbootstrap.com/docs/5.0/utilities/api/) I'm trying to add a cursor utility class in my scss file. I have _utilities.scss loaded first and then I have this (as per the docs):

```
@import "bootstrap/scss/utilities";

    $utilities: map-merge(
      $utilities,
      (
        "cursor": (
          property: cursor,
          class: cursor
          responsive: true,
          values: auto pointer grab,
        )
      )
    );
```

I'm then adding this class to my element:

`<a href="#" class="cursor-grab">Grab this</a>`

However, the cursor-grab class is nowhere to be found in the CSS output. Any idea what I'm doing wrong?
