### ISSUE TITLE
Utility API docs: missing comma in Add utilities example

### ISSUE THREAD

**Issue by iatek** [twbs/bootstrap#32542]
- Operating system and version: all
- Browser and version: all
- Test case: The provided example code doesn't compile in SASS and produces a "unclosed parenthesis" SASS error

The fix is to simply add a trailing comma on line 257 of utilities\api.md

`class: cursor,`

**Comment by XhmikosR** [comment]
The time you took to write this, you could just have edited the file yourself :)

Anyway, #32543

**Comment by iatek** [comment]
You beat me to it.. I was just submitted the PR
