### ISSUE TITLE
Purple attention text and background colors 

### ISSUE THREAD

**Issue by Dygear** [twbs/bootstrap#32549]
I've always added purple as attention myself in the code later on in my own CSS code and it's such a simple thing, that I thought it should maybe actually land in the main bootstrap theme for v5. I've used a color callout `text-attention` and `bg-attention` for the purple color. The actual `$purple` color `#6f42c1` used within the official theming options is actually perfect for this.

I use the purple color whenever I want to call attention to something that is neither good nor bad. It's purely an informational color unlike the connotation that a danger red (`#dc3545`) or success green (`#198754`) or even a warning yellow (`#ffc107`) would have.

Formula 1 uses the color purple to indicate whenever someone goes fastest on their Timing and Scoring screens in a given sector or over all lap time as well.

It's also the only ECMA-48 color (magenta) that is not available by default in Bootstrap. ECMA-48 is the color codes used by the Linux terminal in order to convey information to the user. It would be nice to display this information using default bootstrap markup.

- Relevant links to prior art, screenshots, or live demos whenever possible
![F1 Sector Time Colors](https://i.redd.it/03n746fkzfm21.png)
![ECMA-48 Linux Console Colors](https://user-images.githubusercontent.com/367860/102708277-ce9b0100-426f-11eb-8e14-04637aa498d1.png)

**Comment by mdo** [comment]
We'll likely leave the theme colors as-is by default. We use teal/cyan for some info purposes and you can modify that or extend as needed. I do appreciate the love for purple though! :D

**Comment by vanillajonathan** [comment]
Bootstrap have purple color in the Sass map. From `$purple-100` to `$purple-900`.
https://getbootstrap.com/docs/5.0/customize/color/#all-colors
