### ISSUE TITLE
Utility API docs: Add @import functions, variables to the examples.

### ISSUE THREAD

**Issue by iatek** [twbs/bootstrap#32557]
Utility API docs: Add `@import` functions, variables to the examples.

Since `_utilities` references, `_variables`, and `_variables` references `_functions`, in order to [use the API](https://getbootstrap.com/docs/5.0/utilities/api/#using-the-api) you must import like..

```
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/utilities";

$utilities: map-merge(
  $utilities,
  (
    "cursor": (
      property: cursor,
      class: cursor,
      responsive: true,
      values: auto pointer grab,
    )
  )
);
```

Should this be mention in the Using the API section, perhaps explain in the text that says "Make sure our _utilities.scss is imported first,"? Or, simply add the correct `@imports` in each of the examples?

**Comment by adro21** [comment]
@iatek Following the docs for v5 exactly I'm trying to add a cursor utility. I have _functions.scss, _variables.scss, and _utilities.scss loaded first and then I have this (as per the docs):

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/utilities";

    $utilities: map-merge(
      $utilities,
      (
        "cursor": (
          property: cursor,
          class: cursor
          responsive: true,
          values: auto pointer grab,
        )
      )
    );

I'm then adding this class to my element:

`<a href="#" class="cursor-grab">Grab this</a>`

However, the cursor-grab class I'm trying to add is nowhere to be found in the CSS output. Any idea what I'm doing wrong?

**Comment by iatek** [comment]
The docs don't currently show all the needed imports. But in you case, the `class: cursor` is missing the trailing comma as mentioned in #32542 which will be fixed beta 2.

**Comment by adro21** [comment]
@iatek Sorry, I actually fixed that in my code...I noticed it was wrong in the docs. But that's not the issue. The issue is that I don't want to have to import the entire bootstrap.scss file. I'm currently doing it parts like this (for optimial load time):

```
// Required
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/utilities";


$utilities: map-merge(
  $utilities,
  (
    "cursor": (
      property: cursor,
      class: cursor,
      state: hover,
      responsive: true,
      values: auto pointer grab,
    )
  )
); 
    
// Optional
@import "../node_modules/bootstrap/scss/alert";
@import "../node_modules/bootstrap/scss/badge";
@import "../node_modules/bootstrap/scss/breadcrumb";
@import "../node_modules/bootstrap/scss/button-group";
@import "../node_modules/bootstrap/scss/buttons";
@import "../node_modules/bootstrap/scss/card";
@import "../node_modules/bootstrap/scss/carousel";
@import "../node_modules/bootstrap/scss/close";
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/dropdown";
@import "../node_modules/bootstrap/scss/forms";
@import "../node_modules/bootstrap/scss/grid";
@import "../node_modules/bootstrap/scss/helpers";
@import "../node_modules/bootstrap/scss/images";
@import "../node_modules/bootstrap/scss/list-group";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/modal";
@import "../node_modules/bootstrap/scss/nav";
@import "../node_modules/bootstrap/scss/navbar";
@import "../node_modules/bootstrap/scss/pagination";
@import "../node_modules/bootstrap/scss/popover";
@import "../node_modules/bootstrap/scss/progress";
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/root";
@import "../node_modules/bootstrap/scss/spinners";
@import "../node_modules/bootstrap/scss/tables";
@import "../node_modules/bootstrap/scss/toasts";
@import "../node_modules/bootstrap/scss/tooltip";
@import "../node_modules/bootstrap/scss/transitions";
@import "../node_modules/bootstrap/scss/type";
@import "../node_modules/bootstrap/scss/bootstrap-grid";
@import "../node_modules/bootstrap/scss/bootstrap-reboot";
@import "../node_modules/bootstrap/scss/bootstrap-utilities";
```

Shouldn't this work? I can't imagine that the only way to add custom utilities is to be forced to always load the entire bootstrap.scss file...

**Comment by iatek** [comment]
It does work as I mentioned here: https://stackoverflow.com/a/65386748/171456

**Comment by adro21** [comment]
Importing the entire bootstrap scss file is not optimal for load time in a production environment. When my project is complete, I plan to remove all the imports that I don't need. Bootstrap docs even recommend this: "When using Sass in your asset pipeline, make sure you optimize Bootstrap by only @importing the components you need."

I shouldn't have to import the entire bootstrap.scss file for this to work right?

**Comment by iatek** [comment]
Are you _all_ of Bootstrap? .. or just the Bootstrap utilities?

**Comment by adro21** [comment]
I'm using various parts of bootstrap, but just for example, there's several parts I won't need and plan to remove from the imports.

**Comment by iatek** [comment]
The you would @import those other parts after the changes, and yes would work as long as you @import bootstrap-utilities after

**Comment by adro21** [comment]
See my code above, I am making all my imports after the changes, except for:

```
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/utilities";
```

**Comment by iatek** [comment]
For me it seems to work: https://codeply.com/p/m14Nzv3jVX

Make sure you paths are all correct and the SASS compiler has the correct includePaths

**Comment by adro21** [comment]
Hah! That's so weird. I'm pretty sure my paths are correct...wouldn't my compiler throw an error if they weren't? (it's currently not throwing any errors). I'm using the Live Sass Compiler extension in VSCode. I'm not really sure where to find the includePaths, but everything other than this seems to be working for me...

**Comment by adro21** [comment]
I'm referencing/including my compiled css file in my html file. All other parts of bootstrap seem to be rendering correctly (at least that I've tried so far), but not this utility class ('cursor-grab') that I'm trying to add.

**Comment by adro21** [comment]
Ok, kind of odd, if I remove all the parts except bootstrap-utlities like you have in your exmaple, cursor grab works:

```
// Required
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";


$utilities: map-merge(
  $utilities,
  (
    "cursor": (
      property: cursor,
      class: cursor,
      state: hover,
      responsive: true,
      values: auto pointer grab,
    )
  )
); 
    
@import "../node_modules/bootstrap/scss/bootstrap-utilities";
```

But if I inlude all the other parts, it does not get compiled in my css file... hmmmm

**Comment by iatek** [comment]
Because if you just want to optionally add the grid classes you should only `@import "../node_modules/bootstrap/scss/grid"`. `bootstrap-grid` is for building a grid/flexbox only version, and therefore also imports utilities which is resetting your utility overrides. It's all explained in the [customize docs](https://getbootstrap.com/docs/5.0/customize/sass/)

https://codeply.com/p/m14Nzv3jVX

**Comment by iatek** [comment]
Anyway, @XhmikosR I didn't intend for this issue to be hijacked with SASS debugging. If you think my aforementioned feature request (to mention the other required @imports) is legit I'd be happy to open a PR.

**Comment by adro21** [comment]
@iatek Sorry, didn't mean to hijack the thread! Appreciate your help and the explanation, but anyway, your example still isn't working for me: https://d.pr/v/harXWd
