### ISSUE TITLE
Use display: flow-root instead of the clearfix hack

### ISSUE THREAD

**Issue by MichaelRushton** [twbs/bootstrap#32550]
https://caniuse.com/flow-root

Supported by the latest version of the major browsers. It's a much cleaner solution.

**Comment by ffoodd** [comment]
I like the idea, however [changing `display` on semantic elements might remove their semantics (content by Adrian Roselli)](https://adrianroselli.com/2020/10/a11yto-conf-css-display-properties-versus-html-semantics.html). I'd say it needs some deep thinking before using this as a basis, and at least deep testing of various behaviours using this value.

**Comment by mdo** [comment]
Getting some help testing this out to verify @ffoodd's comment would be nice. We can go from there and perhaps add something as another utility and offer up alternatives depending on needs/situation.

**Comment by mdo** [comment]
Closing as stale.
