### ISSUE TITLE
Responsive typography for standard text

### ISSUE THREAD

**Issue by Teacup5000** [twbs/bootstrap#32561]
I would love to see additional typography classes, for:

- responsive standard text
- responsive lead text

I know this is very simple to do by myself, but as I'm not a designer and would strongly prefer some preset from bootstrap.

Furthermore, all header classes are currently responsive, except H5, H6 - I would prefer to have all of them responsive, unless there is an actual reason why you left these out?

Thanks

**Comment by mdo** [comment]
All headings use the `font-size()` mixin, as does `.lead`. There are also `.fs-` classes for `font-size` based on headings. Beyond that, you can modify the root/body font-size and easily scale anything, either with utilities or custom code.
