### ISSUE TITLE
Example Templates

### ISSUE THREAD

**Issue by bbmibrown7** [twbs/bootstrap#32565]
So I am working with bootstrap for a course I am doing and I wanted to use one of the examples but when I pulled a copy of the .html and the .css and put them in a different folder and tried to do a preview they don't work.  What am I doing wrong?

**Comment by nicosammito** [comment]
maybe the path to the css file is wrong

**Comment by bbmibrown7** [comment]
I can try and reroute the file path. I though i did that. But what would it be for those examples that do not have a .css? 

~ Brandon Chanon

**Comment by mdo** [comment]
Moving the files around you'll definitely need to update that paths to all CSS and JavaScript files.
