### ISSUE TITLE
Missing btn-close SCSS of Bootstrap version 4.5.3

### ISSUE THREAD

**Issue by ahoba2002** [twbs/bootstrap#32572]
Hi,
I found that btn-close is not available in all SCSS files of Bootstrap version 4.5.3
I don't know if some other elements are missing as will!

Regards,

**Comment by mdo** [comment]
Different versions, different names. https://getbootstrap.com/docs/4.5/utilities/close-icon/

**Comment by ahoba2002** [comment]
I mean in the source
https://github.com/twbs/bootstrap/archive/v4.5.3.zip

The class btn-close  should be there. Why it has been removed from there?

**Comment by ffoodd** [comment]
There's no `.btn-close` in 4.5.3, please follow the provided link and read the docs.

**Comment by ahoba2002** [comment]
I see
