### ISSUE TITLE
Docs for flex-grow-N

### ISSUE THREAD

**Issue by guettli** [twbs/bootstrap#32576]
The docs about "grow" only explain the numbers zero and one:

https://getbootstrap.com/docs/5.0/utilities/flex/#grow-and-shrink

But flex-grow can have any positive number. See [mozilla docs flex-grow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow)

Please explain in the docs if `flex-grow-4` is supported or not.

If it is not supported, it would be kind, if you could document a work-around.

Thank you very much.

**Comment by mdo** [comment]
The docs are pretty clear on what's supported IMO as there is a list of supported properties below the demo.
