### ISSUE TITLE
Dropdown problem in rtl version

### ISSUE THREAD

**Issue by mortezafs** [twbs/bootstrap#32578]
- Windows 10 pro x64 - build 19041.685
- Tested at this browsers:
- Firefox Developer Edition Version 85.0b4 (64-bit)
- Google Chrome Version 87.0.4280.88 (Official Build) (64-bit),
- Microsoft Edge Version 87.0.664.66 (Official build) (64-bit)

- [https://codepen.io/mortezafs/project/editor/ZgGJby](https://codepen.io/mortezafs/project/editor/ZgGJby)

I am testing the bootstrap RTL version. There are a number of bugs in this version, one of the most important of which is the drop-down menus.
In the RTL version, the popper does not work properly, and when the dropdown is in the corner of the screen, the dropdown pops out of the view port space and does not change to the display direction. And sometimes it causes horizontal scrolling.

To better understand the subject, I edited your example of your RTL dashboard and uploaded it to the CodePen.
and attached some screenshots.

![Screenshot_2020-12-21 قالب لوحة القيادة · Bootstrap v5 0(1)](https://user-images.githubusercontent.com/6403102/102769522-01d8af80-4398-11eb-9c54-4547c6e7a9b3.png)
![Screenshot_2020-12-21 قالب لوحة القيادة · Bootstrap v5 0](https://user-images.githubusercontent.com/6403102/102769525-043b0980-4398-11eb-928d-925549b3373a.png)
![Screenshot_2020-12-21 ورود به سامانه](https://user-images.githubusercontent.com/6403102/102769532-069d6380-4398-11eb-86e9-7e91f6350c7d.png)

**Comment by XhmikosR** [comment]
Please try the main branch; there have been some fixes and your issue is probably fixed.

If you don't want to build the main dist files yourself, you can use these ones:

* https://twbs-bootstrap.netlify.app/docs/5.0/dist/css/bootstrap.rtl.min.css
* https://twbs-bootstrap.netlify.app/docs/5.0/dist/js/bootstrap.bundle.min.js

**Comment by mortezafs** [comment]
The problem was solved in my own source, But when i replaced the branch version with current version of bootstrap that used in dashboard example, everything's messed up.
We want to report the bugs of the current rtl version to fix and have a stable version of rtl.
Now what we should to do? check on the branch version or on the latest release?

**Comment by XhmikosR** [comment]
Always check the main branch please.

**Comment by ffoodd** [comment]
[Here's an updated CodePen using current](https://codepen.io/ffoodd/project/editor/AbYGdG).
I recall dropdowns in navbar do not use Popper.js, am I wrong @twbs/js-review ?

**Comment by XhmikosR** [comment]
What's the problem here? The overflow when the dropdown is open? It shouldn't happen if you use `dropdown-menu dropdown-menu-start`

**Comment by mdo** [comment]
This isn't technically a bug—navbars require manual positioning (even responsively and by viewport) for dropdowns as mentioned above.
