### ISSUE TITLE
Keep interim class name the same.

### ISSUE THREAD

**Issue by kerryj89** [twbs/bootstrap#32577]
For instance in the Collapse module, the CSS states are:

- `.collapse`
- `.collapsing`
- `.collapse.show`

It would be better if it was:

- `.collapse`
- `.collapse.interim`
- `.collapse.show`

That way if we have styles on the `.collapse` class they are kept through each state which I think would be the normal case.  And if we want to make exceptional styles happen in between the hidden/shown states, we can attach that to the `.interim` class just as we would currently do with the `.collapsing` class.  By calling it `.interim` we also abstract the name to be used consistently within any component that has this transitioning state.

The counter argument would be to create a class for the collapsible and attach styles to that instead.  That may be true but I think doing this would make for a more consistent experience.

**Comment by hvsh** [comment]
I would go one further and suggest using **is** and **has** for all state related classes, while keeping the main class the same through out. 
.collapse
.collapse.is-collapsing
.collapse.is-visible 

.is-active
.is-disabled
.is-scrollable

so on

**Comment by mdo** [comment]
At this point, this would be a breaking change for v5. Tagging for v6 and closing out as a won't fix for now.
