### ISSUE TITLE
old bootstrapcdn cdn link broken many times

### ISSUE THREAD

**Issue by Yang09701194** [twbs/bootstrap#32579]
Hi, the old cdn `https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css` broken few days ago, and I report to 
`@rossipedia` after minutes it's fixed,  

but today, it brokens again, and the `bootstrapcdn` site also lost css, could you make this cdn more stable, or consider to close this site and only allow new cdn `cdn.jsdelivr.net`?

--- 

![img1](https://i.imgur.com/dzSbCCs.png)

.

![img2](https://i.imgur.com/xhak3y3.png)

**Comment by XhmikosR** [comment]
You should report such issues to them not here.
