### ISSUE TITLE
Checkbox toggle buttons does not work properly

### ISSUE THREAD

**Issue by pickatag** [twbs/bootstrap#32597]
The Toggle Buttons functionality in v5 does not work properly.

I have found two errors (first and third problem) and one usability issue (second), but I keep them in the same Issue since I suspect they are related.
Please note that I do not know if the errors are in the framework or the documentation.

### First problem
Single button does not work.
Reproduce:

1. Use any major desktop browser (see below, not tested on Safari).
2. Go to [Forms / Checks & radios](https://getbootstrap.com/docs/5.0/forms/checks-radios/#checkbox-toggle-buttons) documentation and Toggle buttons section.
3. Click with mouse on "Single toggle" or "Checked". Nothing happens. Expecting the button to toggle.

### Second problem
Mouse over hides the action.
Reproduce:

1. Use any major desktop browser (see below, not tested on Safari).
2. Go to [Outlined styles](https://getbootstrap.com/docs/5.0/forms/checks-radios/#outlined-styles).
3. Hover mouse over "Single toggle", the bg color changes to primary.
4. Click the button "Single toggle", the frame around the button changes, the bg color still primary.
5. Click the button again, the frame remains as the bg color as primary.
6. Click the button again, no difference.

This is bad user experience. The user need to remove the mouse from the button to see the outcome of the action.
Expected behaviour: It should be possible to see the result of the action directly after mouse click.

Note: I'm new to Bootstrap, maybe different configurations solves this, but it should work "out of the box" from the Documentation, for newbies like me.

### Third problem
Checkbox button group does not work on iOS device.
Reproduce:

1. Use iOS 14.2 device (not tested on other version). Use any browser, Safari, Firefox or Chrome (see below).
2. Go to [Checkbox and radio button groups](https://getbootstrap.com/docs/5.0/components/button-group/#checkbox-and-radio-button-groups).
3. Click on "Checkbox 1" and it is selected.
4. Click again on "Checkbox 1", nothing happens. Expected behaviour: It should deselect.
5. Click on "Checkbox 2". Now "Checkbox 1" is deselected and "Checkbox 2" is selected. Expected behaviour: When using checkbox behaviour, only the button pressed should be affected, "Checkbox 2" should be selected and "Checkbox 1" should remain selected.

Please note: Third problem works as expected on major desktop browsers (see below).

**First and second problem:**
Operating system: Windows 10 Education 64-bit, Version 1909, OS build 18363.1256
Desktop browsers:

- Google Chrome / Version 87.0.4280.88 (Official Build) (64-bit)
- Firefox / Version 84.0.1 (64-bit)
- Microsoft Edge / Version 87.0.664.66 (Official build) (64-bit)

**Third problem:**
Operating system: iOS 14.2 / HW iPhone 7
Browsers (for iOS):

- Safari (as in iOS 14.2)
- Firefox Daylight 30.0 (3279)
- Chrome Version 87.0.4280.77

**Comment by XhmikosR** [comment]
I feel like you are confusing the docs with actual components. The links on the docs don't do anything hence why this happens.

Moving to a discussion.
