### ISSUE TITLE
Wrong left margin with the label of a form-floating component

### ISSUE THREAD

**Issue by maroquio** [twbs/bootstrap#32602]
If I use a **form-floating** component inside a **fieldset** HTML element with **row** class, the left margin of the floating label is wrong. 

Code example:

```
<fieldset class="row">      
      <div class="form-floating mb-3">
          <input class="form-control" type="text" id="txtName" placeholder=" "/>
          <label for="txtName">Name</label>
      </div>
...
```

My temporary solution was to include this CSS style in the head element of the page: 

```
fieldset.row .form-floating > label {
    margin-left: calc(var(--bs-gutter-x) * 0.5);
}
```

I hope it helps.

Regards.

**Comment by mdo** [comment]
Our docs mention you cannot and should not blend grid classes with other components. Without seeing a live example, I'm assuming that's the issue. Drop the row class from the parent, or add another wrapping element.
