### ISSUE TITLE
Show/Hide Password Feature

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#32606]

**Comment by pushprajsinghjadoun** [comment]
here is code of feature


//html


Password: <input type="password" value="FakePSW" id="myInput">


<input type="checkbox" onclick="myFunction()">Show Password 





//javascript


function myFunction() {
  var x = document.getElementById("myInput");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}

**Comment by mdo** [comment]
This isn't something we'd do, sorry. Too prescriptive for us.
