### ISSUE TITLE
Add sticky-top-none class with Responsive variations for Sticky top

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#32612]
Here, Have new features added Responsive variations classes for Sticky top in bootstrap 5. This is great.

But, If, We want to add sticky top only for Extra small device. So, Here, It will not possible with responsive classes.

It would be great. if, You will added `sticky-top-none` class with Responsive variations.

`.sticky-top-none`
`.sticky-top-sm-none`
`.sticky-top-md-none`
`.sticky-top-lg-none`
`.sticky-top-xl-none`
`.sticky-top-xxl-none`

**Something like:**
```
<header class="sticky-top sticky-top-sm-none">
 ........
</header>
```

**Comment by mdo** [comment]
This feels like a case that can be handled with custom utilities/helpers. Closing as a won't implement for now.
