### ISSUE TITLE
Floating label touch input left border

### ISSUE THREAD

**Issue by arpanpatel** [twbs/bootstrap#32615]
- Operating system : (Windows, macOS, Android, iOS)
- Browser and version : (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- Suggested fix [CodePen](https://codepen.io/arpanpatel/pen/XWjzVOg)

Floating label touch input left border when bootstrap grid `col-*` class use with `form-floating` class.

**Comment by mdo** [comment]
Don't mix grid classes with component classes, it'll never end well and we've long advised against it.

**Comment by arpanpatel** [comment]
> Don't mix grid classes with component classes, it'll never end well and we've long advised against it.

got it @mdo
