### ISSUE TITLE
textarea with floating labels overrides height of textarea

### ISSUE THREAD

**Issue by SatheesA** [twbs/bootstrap#32628]
Bug reports must include:

- windows 10
- Chrome  87.0.4280.88
- Bootstrap 5 beta 1

link to demo: https://codepen.io/SatheesA/pen/qBapBNW

when using floating labels with textarea the height of the textarea is overridden by bootstrap css styles.

`.form-floating>.form-control, .form-floating>.form-select {
    height: calc(3.5rem + 2px);
    padding: 1rem .75rem;
}`

This is not desired effect since textareas usually has more space.

**Comment by linhub15** [comment]
For now I think the only way is to set the height.

The docs: https://getbootstrap.com/docs/5.0/forms/floating-labels/#textareas

> To set a custom height on your `<textarea>`, do not use the `rows` attribute. Instead, set an explicit height (either inline or via custom CSS).

**Comment by mdo** [comment]
Closing per comment above—this is covered in our docs.
