### ISSUE TITLE
Regression: carousel `data-touch="false"` not working

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#32629]
A fresh version of this https://github.com/twbs/bootstrap/issues/28025#issuecomment-634603003

It seems somehow the code that was added here #28046 has been lost at some point. 

[edit: correction, as @rohit2sharma95 pointed out, the code is actually still there - i somehow managed to miss it while checking the code yesterday. so the problem may be deeper somehow]

**Comment by rohit2sharma95** [comment]
But the check (added in #28046) still exists in the main branch:
https://github.com/twbs/bootstrap/blob/a48a29a7a5878d2a88acbca6ec4e189c1c068d4a/js/src/carousel.js#L281-L283

**Comment by patrickhlauke** [comment]
where is the actual `data-touch` data attribute queried? is that part of some more generic "grab anything that's a data attribute and shove it into the `_config` object" type logic?

**Comment by patrickhlauke** [comment]
as I always find it difficult to debug this sort of thing easily, and also because it would be nice to actually provide a live example, i made this provisional PR here to add a carousel without touch to the docs https://github.com/twbs/bootstrap/pull/32638

**Comment by patrickhlauke** [comment]
using the added example from #32638 I can confirm that https://deploy-preview-32638--twbs-bootstrap.netlify.app/docs/5.0/components/carousel/#suppressing-touch-swiping when tested on iOS, Android, and a Surface with touchscreen still reacts to touch/swipe despite the `data-touch="false"` attribute

**Comment by patrickhlauke** [comment]
turns out i was being a moron - this actually works in v5 if using the correct `data-bs-touch="false"`. now wondering how to test the reported issue in 4.5...

**Comment by patrickhlauke** [comment]
ok, having now tested this in v4.5 as well, it seems there is no actual problem with `data-touch="false"`. https://github.com/twbs/bootstrap/pull/32639

closing.
