### ISSUE TITLE
RTL mode dropdown

### ISSUE THREAD

**Issue by ArashArzandeh** [twbs/bootstrap#32622]
in bootstrap version 5 when we set RTL on the page, dropdown menu not working correctly, .dropdown-menu absolute position has a wrong left propery.
 
```
.dropdown-menu[style] {
    /* left: auto!important; */
}
```

_dropdown.scss line 38

**Comment by XhmikosR** [comment]
It's probably already fixed in main

**Comment by rohit2sharma95** [comment]
Similar to #32484 IMO

**Comment by ArashArzandeh** [comment]
Hi
it's fixed in bootstrap.min.js bot when I include bootstrap.rtl.min.css
it's broken yet.

**Comment by ArashArzandeh** [comment]
Sorry,
I had wrong type in previous mail.
bootstrap.min.css is correct  in rtl mode dropdown but in
bootstrap.rtl.min.css it has left: auto!important which cause to fail

**Comment by ffoodd** [comment]
@ArashArzandeh Could you please test [RTL cheatsheet on main](https://main--twbs-bootstrap.netlify.app/docs/5.0/examples/cheatsheet-rtl/#dropdowns)? Seems good to me.

It's solved by #32415, so I'll close this issue but feel free to comment again if not, I'll reopen it.
