### ISSUE TITLE
Floating label's initial color

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#32633]
Let me start off by saying that in general, having placeholder text in a form field is not recommended.  Here's [just one source](https://www.nngroup.com/articles/form-design-placeholders/#:~:text=Summary%3A%20Placeholder%20text%20within%20a,with%20visual%20and%20cognitive%20impairments.) to explain why.

However, if we are going to be doing it in our floating labels, let's at least not make the user think that the field is already filled out; which currently is the perception:
![Screen Shot 2020-12-27 at 5 07 29 PM](https://user-images.githubusercontent.com/2222751/103180854-d0645600-4867-11eb-8f01-d00617a0da2a.png)

So I propose that the initial color of the label, match that of the placeholder color: `$input-placeholder-color`.  That will probably mean adjusting the opacity of the label onfocus:
![Screen Shot 2020-12-27 at 5 18 43 PM](https://user-images.githubusercontent.com/2222751/103180860-d78b6400-4867-11eb-9fad-ff221f782486.png)

On a side note, I'd even say that the placeholder color is too dark but I'm guessing we went with that because of accessibility?

**Comment by ffoodd** [comment]
Floating labels are using labels, not placheolders — because placeholders cannot replace a label, indeed.
And as they're labels, they need sufficient contrasts ratios, and to stay consistent with other labels out there.

Am I missing something?

**Comment by LarryAzevedo** [comment]
Hey @ffoodd. Regarding your comment:
> And as they're labels, they need sufficient contrasts ratios, and to stay consistent with other labels out there.

I hear what you're saying but users are not thinking about what something technically is. They go by what is perceived. And currently, the perception is that the field already has a value in it, which can lead to confusion.

**Comment by ffoodd** [comment]
Indeed, that's why I usually don't recommend using floating labels. Sufficient contrasts are needed, so I'd say we may try something to make more obvious that label is not a value. 

But this is an issue inherent to this pattern, and I never see any solution for this.

Any help or suggestion is welcome, but we cannot reduce labels' contrasts.

**Comment by mdo** [comment]
I'm inclined to leave as-is for now. It's customizable via Sass, so for now it can be worked around.
