### ISSUE TITLE
The links in the navbar (docs and examples) of the blog page are linking to the old version (v4.5)  

### ISSUE THREAD

**Issue by saifeddin1** [twbs/bootstrap#32637]
The "Docs" and the "Examples" navbar links in the bootstrap blog page are linking to the docs and the examples of bootstrap v4.5 not the v5.0.  

![Screenshot_2](https://user-images.githubusercontent.com/34710727/103214661-54bee380-4911-11eb-9d1b-9a13fe8a6202.png)

**Comment by XhmikosR** [comment]
Irrelevant to this repo.
