### ISSUE TITLE
Carousel still autoplays after first interaction when `data-slide` / `data-bs-slide` omitted

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#32640]
From the documentation, I would assume that a carousel only autoplays if it either has `data-bs-ride="true"` (autoplays after the first interaction) or `data-bs-ride="carousel"` (autoplays on load).

When testing this on https://deploy-preview-32638--twbs-bootstrap.netlify.app/docs/5.0/components/carousel/#suppressing-touch-swiping and https://deploy-preview-32639--twbs-bootstrap.netlify.app/docs/4.5/components/carousel/#suppressing-touch-swiping it seems that omitting the `data-bs-ride` (or `data-` for 4.5) altogether still ends up behaving like `data-bs-ride="true"`, i.e. after first interaction with the prev or next button, it starts autoplaying anyway (even though the default is, supposedly, `false`)

Is this...expected?

**Comment by patrickhlauke** [comment]
or is this controlled via the `.slide` class as well? i.e. the presence of `.slide` will act like `data-bs-slide="true"`? if so, this is not currently documented anywhere

**Comment by patrickhlauke** [comment]
tried to work out what the logic here is, but seem to have gotten myself utterly confused in the process...

in v4.5, the options table talks about `ride` as the option. this seems wrong, it's likely `slide`.

now for both my v4.5 and v5.0 examples in #32638 and #32639 i removed the `.slide` class from the examples...and yet, they still autoplay after the first interaction. not sure what is going on...if it's me missing something, or if our code is just borked, or...

**Comment by patrickhlauke** [comment]
also, it sounds like the `.slide` class should really be renamed to `.carousel-slide` ?

**Comment by patrickhlauke** [comment]
now getting a weird suspicion...is there perhaps, by design, no way to actually stop autoplaying at all? but just a choice of autoplaying after interaction (default) or right on page load (carousel)? if so, that seems a horrendous omission

**Comment by thenomadicmann** [comment]
Did you try adding `data-interval="false"` to the [carousel](https://getbootstrap.com/docs/5.0/components/carousel/#options)?

**Comment by patrickhlauke** [comment]
urgh, good call @thenomadicmann ... that's rather obtuse design, i have to say... (same for using `ride` as an option, makes no sense). I'll give it a shot
