### ISSUE TITLE
import bootstrap from 'bootstrap' - "export default was not found"

### ISSUE THREAD

**Issue by demiavaliani** [twbs/bootstrap#32642]
I have Angular 11 & Bootstrap 5 project.

Following the documentation from here: [Package managers > NPM](https://getbootstrap.com/docs/5.0/getting-started/download/)

1. "import bootstrap from 'bootstrap'" to expose the plugins. 

2. Now having "bootstrap" object, I go ahead and try to get instance of Modal for example:
`bootstrap.Modal.getInstance(myModal);`

Received following error:
**"export 'default' (imported as 'bootstrap') was not found in 'bootstrap'**

Looks like there is no default export in bootstrap library. Instead **import * as bootstrap from 'bootstrap'** fixed the issue.

Also, it would be good to have a mention of how to import properly the plugins inside the website Components section itself.
For example, [Components > Modal > getInstance](https://getbootstrap.com/docs/5.0/components/modal/#getinstance) just mentions that we can get instance of a Modal. But it does not say how to properly import the plugins first.

**Comment by lukasjuhrich** [comment]
Note also that this is in the official docs concerning [how to find out the version number](https://getbootstrap.com/docs/5.0/getting-started/javascript/#version-numbers).  In particular, bootstrap-table [uses `bootstrap.Tooltip.VERSION`](https://github.com/wenzhixin/bootstrap-table/blame/4fd95f9eae804e62349916a19c97f975e2e6d46a/src/constants/index.js#L18) to determine whether someone uses v5.

I was not aware of the `import * as bootstrap from 'bootstrap'` workaround and have not bene able to try it out.

**Comment by benkoshy** [comment]
@mdo is it worth having a default export boostrap object? Or should the documentation be updated directing users to export the specific components they require: e.g. `import {Modal} from "bootstrap"` - pls LMK - and I can (try to) put in the PR.

**Comment by mdo** [comment]
@geosot Any thoughts here beyond what we're doing in our updated guides and #36414?

**Comment by negentropicdev** [comment]
Documentation still seems to be incorrect 
![image](https://user-images.githubusercontent.com/59840835/218294212-7bfd1346-c1ed-4dc2-af71-fb757362cae0.png)
