### ISSUE TITLE
bootstrap v5 alpha - "accordion" js is not working, bootstrap v5 beta yes

### ISSUE THREAD

**Issue by ShlomiRex** [twbs/bootstrap#32656]
Windows 10, Chrome

Is it just me?

Code:
```
<div class="accordion" id="accordionExample2">
	<div class="accordion-item">
		<h2 class="accordion-header" id="headingOne">
			<button class="accordion-button" type="button" data-bs-toggle="collapse"
				data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
				Accordion Item #1
			</button>
		</h2>
		<div id="collapseTwo" class="accordion-collapse collapse show"
			aria-labelledby="headingOne" data-bs-parent="#accordionExample2">
			<div class="accordion-body">


				<div class="list-group" id="list-tab" role="tablist">
					<a class="list-group-item list-group-item-action active" id="list-home-list"
						data-toggle="list" href="#list-home" role="tab"
						aria-controls="home">Home</a>
					<a class="list-group-item list-group-item-action" id="list-profile-list"
						data-toggle="list" href="#list-profile" role="tab"
						aria-controls="profile">Profile</a>
					<a class="list-group-item list-group-item-action" id="list-messages-list"
						data-toggle="list" href="#list-messages" role="tab"
						aria-controls="messages">Messages</a>
					<a class="list-group-item list-group-item-action" id="list-settings-list"
						data-toggle="list" href="#list-settings" role="tab"
						aria-controls="settings">Settings</a>
				</div>


			</div>
		</div>
	</div>
</div>
```
It's quite a bummer, because of:
https://github.com/twbs/bootstrap/issues/32655

There I must use alpha 1 instead of beta 1 because list-group activation js code is not working
But in this can I need to use beta 1
So I need to use both alpha and beta for accordion and list-group active

**Comment by Andres6936** [comment]
In **Bootstrap v5.0.0-beta1** the follow message is showed for MS Edge:

```js
Uncaught TypeError: _this._getConfig is not a function
    at Object.Carousel (carousel.js:123)
    at (index):302
Carousel @ carousel.js:123
(anonymous) @ (index):302
```

**Comment by mdo** [comment]
`data-toggle` is now `data-bs-toggle`. Check your markup, we had a breaking change to namespace data attributes.

**Comment by huzaifaamir** [comment]
Same issue my code is below


<div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Accordion Item #1
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Accordion Item #2
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Accordion Item #3
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>
