### ISSUE TITLE
bootstrap 5 beta 1 list-group not toggled, alpha 1 yes

### ISSUE THREAD

**Issue by ShlomiRex** [twbs/bootstrap#32655]
Windows 10, Chrome

So I use the following example from official bootstrap v5 documentation:

```
<div class="list-group" id="list-tab" role="tablist">
	<a class="list-group-item list-group-item-action active" id="list-home-list"
		data-toggle="list" href="#list-home" role="tab"
		aria-controls="home">Home</a>
	<a class="list-group-item list-group-item-action" id="list-profile-list"
		data-toggle="list" href="#list-profile" role="tab"
		aria-controls="profile">Profile</a>
	<a class="list-group-item list-group-item-action" id="list-messages-list"
		data-toggle="list" href="#list-messages" role="tab"
		aria-controls="messages">Messages</a>
	<a class="list-group-item list-group-item-action" id="list-settings-list"
		data-toggle="list" href="#list-settings" role="tab"
		aria-controls="settings">Settings</a>
</div>
```

When I click it, it should toggle the item selected in blue color
I tested it on bootstrap v3, v4 and it works
But in v5 beta 1 it doesn't work (the first item is always selected, active) using the following include:
```
<script src="../bootstrap-5.0.0-beta1-dist/bootstrap-5.0.0-beta1-dist/js/bootstrap.min.js"></script>
```
Note: I downloaded bootstrap locally, some functionality like Accordion works (i.e. the script is working)

I found a solution:
```
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
crossorigin="anonymous"></script>
```

Now I don't know why is that, that alpha1 from CDN works but in beta1 not workinhg.

![image](https://user-images.githubusercontent.com/17744127/103448808-8e665600-4c53-11eb-9877-7295a9df1466.png)

As you can see I can toggle items on the list.

EDIT:
I also tested with the official link in the doc (and it doesn't work either, strengthening my assumption that the issue is in beta):
```
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
```

Simillar issue:
https://github.com/twbs/bootstrap/issues/32656

**Comment by mdo** [comment]
`data-toggle` was changed to `data-bs-toggle` in Beta 1. That's likely the issue.

**Comment by ShlomiRex** [comment]
> `data-toggle` was changed to `data-bs-toggle` in Beta 1. That's likely the issue.

Thanks!
