### ISSUE TITLE
Row gutter classes also affect container gutters

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap#32658]
Operation system: all
Browser: all
Reduced test case: https://codepen.io/martinbean/pen/gOweLmQ?editors=1000

If you have a container within a row, and that row has gutters removed (`.row.g-0`), the gutters are _also_ removed from containers anywhere within that row (as it uses the `--bs-gutter-x` CSS variable, and the `.g-0` class sets the value of that variable to zero).

I would expect containers to still retain its padding. Is this intended or not?

Example:

```html
<div class="row g-0">
  <div class="col-12">
    <div class="container">
      <p>Container (now with no gutters)</p>
    </div>
  </div>
</div>
```

**Comment by rohit2sharma95** [comment]
You can use the container directly without wrapping it in a `.row` :thinking: 
```html
<div class="container">
  <p>Container (with padding)</p>
</div>
```

**Comment by martinbean** [comment]
@rohit2sharma95 I’m aware I can, but that’s not what I require for my layout.

**Comment by mdo** [comment]
Hmm I'm not 100% sure honestly, and I think we can go either way on it. Updated the CodePen to show a default `.container` along side Martin's example. https://codepen.io/emdeoh/pen/XWjyrOO?editors=1100

Any thoughts from @twbs/css-review?

**Comment by ffoodd** [comment]
Well, I guess I don't get it. Containers are meant to, well, contain, by defining widths mostly. IMHO, they have nothing to do inside a row (which defines its own widths automatically or through cols).

What am I missing?

**Comment by martinbean** [comment]
@ffoodd Well, the container acts differently whether it’s inside a row or not. Sometimes it has gutters, some times it doesn’t.

My example is, I’m using a gutter-less row for an admin panel layout:

```html
<div class="row g-0">
  <div class="col col-">
    <!-- Header -->
    <!-- Navigation -->
  </div>
  <div class="col">
    <div class="container">
      <!-- Content -->
    </div>
  </div>
</div>
```

I have a fixed-width, left-hand column that holds a logo and navigation menu, and then a flexible right-hand column that holds the content. But because this row is the full width of the screen, I don’t want the content to just keep on expanding as well—I want it contained. So I wrapped it in a container.

The problem is on “medium”-sized screens (i.e. tablets) where the container has a max-width greater than the width of the right-hand column. The container is now butted up against the left-hand column and the right-hand side of the screen, instead of having spacing either side like I would expect, and like it would have in the previous four major versions of Bootstrap.

**Comment by mdo** [comment]
I _think_ this is fine as-is? If you need the container's padding when nested, I'd assume you could add another `.g-*` class to it like so:

```html
<div class="row g-0">
  <div class="col">
    <div class="container g-3">
      <p>Container (now with no gutters)</p>
    </div>
  </div>
</div>
```

Would that suffice?

**Comment by martinbean** [comment]
@mdo It works in that it’ll re-add padding, but isn’t going to match if I’ve set my column gutters to be something other than `1rem`.

**Comment by alpadev** [comment]
Shouldn't be the `$gutters` variable based on the `$grid-gutter-width` rather than `$spacers`? (https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L349) 

Based on @martinbean's comment we have gutters set to `1.5rem` by default so there is a mismatch in general with this `.g-*` approach.
