### ISSUE TITLE
RTL dropdown menu alignment issue

### ISSUE THREAD

**Issue by adnanaddy** [twbs/bootstrap#32657]
in RTL "dropdown-menu-end" is not working fine.

**Comment by XgggCalled** [comment]
good

**Comment by rohit2sharma95** [comment]
Can you please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details. :slightly_smiling_face:

**Comment by omoridi** [comment]
I had this problem with version 4, add this class dropdown-menu-right or dropdown-menu-left to dropdown div

**Comment by ffoodd** [comment]
@adnanaddy Could you please test [RTL cheatsheet on main](https://main--twbs-bootstrap.netlify.app/docs/5.0/examples/cheatsheet-rtl/#dropdowns) —fourth row with a single item? Seems good to me.

It's solved by #32415, so I'll close this issue but feel free to comment again if not, I'll reopen it.
