### ISSUE TITLE
Close button broken in Alert (5.0.0-beta1)

### ISSUE THREAD

**Issue by san-kumar** [twbs/bootstrap#32667]
The close button inside the Alert seems broken in 5.0.0-beta1 as you can see here:

https://codepen.io/superasn/pen/XWjEwdX

![image](https://user-images.githubusercontent.com/33421306/103530769-0760ea00-4eae-11eb-8109-cc5648f758d2.png)

This is working in the alpha release (5.0.0-alpha1) though:

https://codepen.io/superasn/pen/qBaoGNr

![image](https://user-images.githubusercontent.com/33421306/103530712-eef0cf80-4ead-11eb-9282-1de8ffcdc11b.png)

I couldn't find a duplicate in the open issues, so I'm reporting this here.

**Comment by coliff** [comment]
The close button should have the class `btn-close` (not `close`).

Working example code is here:
https://getbootstrap.com/docs/5.0/components/alerts/#dismissing

**Comment by mdo** [comment]
@coliff is correct.
