### ISSUE TITLE
??? Dom must have data-bs-toggle='collapse'

### ISSUE THREAD

**Issue by zhangchenglin** [twbs/bootstrap#32717]
https://github.com/twbs/bootstrap/blob/8095de20ea1f32c866a2dd228f1d328dd14647ab/docs/5.0/components/collapse/index.html#L433

Do I need to write data-bs-toggle='collapse' in Dom through Javascript in 5.0?

**Comment by mdo** [comment]
Collapse requires the `data` attributes, yes.
