### ISSUE TITLE
build fails for v5-beta1 because build folder is missing

### ISSUE THREAD

**Issue by dkern** [twbs/bootstrap#32719]
When installing v5-beta1 via `npm` and try to build it by `npm run dist` some errors occurred. Mostly related because the `build/` directory is missing and so the files `build-plugins.js` and `rollup.config.js`.

Operating system: Windows 10

**Installation:**

```BASH
$ npm install bootstrap@next
$ cd node_modules/bootstrap/
$ npm install
$ npm run dist
```

**Errors:**

```
...

> bootstrap@5.0.0-beta1 js-compile-standalone-esm C:\...\Bootstrap\node_modules\bootstrap
> rollup --environment ESM:true,BUNDLE:false --config build/rollup.config.js --sourcemap

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\...\Bootstrap\node_modules\bootstrap\build\build-plugins.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.0.0-beta1 js-compile-plugins: `node build/build-plugins.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 js-compile-plugins script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_468Z-debug.log
[!] Error: Could not resolve entry module (build\rollup.config.js).
Error: Could not resolve entry module (build\rollup.config.js).
    at error (C:\...\Bootstrap\node_modules\bootstrap\node_modules\rollup\dist\shared\rollup.js:5265:30)
    at ModuleLoader.loadEntryModule (C:\...\Bootstrap\node_modules\bootstrap\node_modules\rollup\dist\shared\rollup.js:18470:20)
    at async Promise.all (index 0)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
[!] Error: Could not resolve entry module (build\rollup.config.js).
npm ERR! bootstrap@5.0.0-beta1 js-compile-bundle: `rollup --environment BUNDLE:true --config build/rollup.config.js --sourcemap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 js-compile-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Error: Could not resolve entry module (build\rollup.config.js).
    at error (C:\...\Bootstrap\node_modules\bootstrap\node_modules\rollup\dist\shared\rollup.js:5265:30)
    at ModuleLoader.loadEntryModule (C:\...\Bootstrap\node_modules\bootstrap\node_modules\rollup\dist\shared\rollup.js:18470:20)
    at async Promise.all (index 0)


npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_525Z-debug.log
npm[!] Error: Could not resolve entry module (build\rollup.config.js).
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.0.0-beta1 js-compile-standalone: `rollup --environment BUNDLE:false --config build/rollup.config.js --sourcemap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 js-compile-standalone script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Error: Could not resolve entry module (build\rollup.config.js).
    at error (C:\...\Bootstrap\node_modules\bootstrap\node_modules\rollup\dist\shared\rollup.js:5265:30)
    at ModuleLoader.loadEntryModule (C:\...\Bootstrap\node_modules\bootstrap\node_modules\rollup\dist\shared\rollup.js:18470:20)
    at async Promise.all (index 0)


npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_541Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.0.0-beta1 js-compile-standalone-esm: `rollup --environment ESM:true,BUNDLE:false --config build/rollup.config.js --sourcemap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 js-compile-standalone-esm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_558Z-debug.log
ERROR: "js-compile-plugins" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.0.0-beta1 js-compile: `npm-run-all --parallel js-compile-*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 js-compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_579Z-debug.log
ERROR: "js-compile" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.0.0-beta1 js: `npm-run-all js-compile js-minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_601Z-debug.log
ERROR: "js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.0.0-beta1 dist: `npm-run-all --parallel css js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.0.0-beta1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dkern\AppData\Roaming\npm-cache\_logs\2021-01-07T13_53_04_693Z-debug.log
```

**Comment by XhmikosR** [comment]
You are not supposed to use things like that. The npm package only includes the needed files for people to consume the project. For everything else you should clone the repo.

**Comment by michaelkrieger** [comment]
The documentation should clearly indicate that then, as right now the documentation is a big vague as far as what steps need to take place in order to download BS5 in order to then customize colours and recompile it.  On https://getbootstrap.com/docs/5.0/customize/overview/ it shows the package manager as a valid way to download BS5 for customization.

**Comment by ffoodd** [comment]
As mentionned in the docs, you have to use your own Sass compiler (meaning [you only import our source files in your Sass project](https://getbootstrap.com/docs/5.0/customize/sass/#importing)).

Our npm scripts are for internal use, as for any npm dependencies.

**Comment by dkern** [comment]
@ffoodd That's not completely true. The docs say I can  _use Bootstrap’s included npm scripts to build our documentation, compile source code, run tests, and more._

https://getbootstrap.com/docs/5.0/getting-started/build-tools/

But as you posted another way ... what is the correct one?! It's very misleading right now. How should anybody know.

**Comment by ffoodd** [comment]
Using Bootstrap, either customized or not, is not the same than building Bootstrap core and docs.

If you want to customize and use, you need to know Sass and how to compile it. Our doc is very clear, you simply need to import our scss files in your Sass project.

I don't see how we could get this clearer ATM, would you have any suggestion?

**Comment by dkern** [comment]
My suggestion then is to fully remove the "Build Tools" page from the docs! If I as a user want to "build" BS, this is the page I would going for (as I did). And the page even say everything I would expect, when I would want to build BS by myself. If this page is only relevant for people who want to work on the bootstap core files, this should be much more explained. I mean, the page also says:

> Bootstrap uses npm scripts for its build system. Our package.json **includes convenient methods for working with the framework**, including compiling code, running tests, and more.

And:

> Learn how to use **Bootstrap’s included npm scripts to build**

It's still not clear to me, why this page is in the docs then, if this has nothing directly to do with working with (not for) BS and has nothing to do with customization too. I would expect something like this page to be located on GitHub then. I mean, if the first thing I hear after try to do what the page described is "You are not supposed to use things like that.", then this page should not be located in the docs too.

Just my point ...

**Comment by michaelkrieger** [comment]
> I don't see how we could get this clearer ATM, would you have any suggestion?

I'm more than happy to take a stab at a documentation page.

There is a lot of assumed knowledge in the customization documentation as to the entire build toolchain.

While it's true that every build environment is different depending on the environment, having documentation that someone in a standard linux (or windows) environment could follow step-by-step to result in a built BootStrap5 with one colour change.

People will adapt it to their own setup, and that's fine. A working example that will show how it's possible after installing npm in any standard linux distribution should be a page or block in the documentation.

Happy to take a stab at it if there is interest.

**Comment by dkern** [comment]
@ffoodd No further response ?!

**Comment by michaelkrieger** [comment]
Continuing my comment from recently, I did go through the many steps to figure out a good way to build BS5 in a contained environment, which doesn't assume the user has a full node build chain on their system already, knowledge of sass and of the specific dependencies and locations where node ecosystems install things.

I made this project in Docker because it stops someone who might not use these tools otherwise from 'tainting' their environment with a whole raft of dependencies, some of which don't come from distro packages. For many people, the only time they will touch sass and node is to make a change to Bootstrap and then go back to their world of regular CSS/HTML/Photoshop.

My package.json and the same steps can be put into documentation and followed on a vanilla system without the Docker element of it. It would probably be appropriate to NOT have the docker elements of it in the bs5 docs, but the code I have installs node, git, installs all dependencies, and includes a basic package.json in it that creates the full dist folder with minified output.

As stated above, happy to take a stab at writing and contributing a documentation page if there is interest in including one.

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap-npm-starter shows you how to build something _with_ Bootstrap, as opposed to building Bootstrap itself (which is what the build tooling is really about right now). Check out that repo and it should show you what you need.

Perhaps we need to explore adding more “guide” content to go with all this?

**Comment by michaelkrieger** [comment]
> how to build something _with_ Bootstrap

This is fine if someone is building an node project and wishes to incorporate Bootstrap. Again, many folks (at least me on many occasions) has wanted to take a css/js file and copy it elsewhere. Into a web site, Wordpress template, or something else that will never see any other component.

> Perhaps we need to explore adding more “guide” content to go with all this?

Take for example what I did to make a quick and dirty compile at https://github.com/michaelkrieger/bootstrap-docker . The dependencies that were needed, that the npm download isn't sufficient to build?  Needless to say, there are many reasons to just want to build bootstrap without integrating it into a node project.

Now I wouldn't think Docker is necessary for the guide but that the sass-compile commands or a prebuilt project.json to have a minified css/js aren't in the docs really surprises me @mdo .

**Comment by ffoodd** [comment]
NPM is a dependency manager: you use it to consume Bootstrap as a dependency, not to build its documentation.

I guerss this is the main cullprit here: our "Build Tools" are for contributing (building docs, ensuring quality, etc.), not related to using Bootstrap as a dependency.

So maybe we may add a callout to mention this, and that our NPM package only contains what it needs as a dependency?

**Comment by carstenfuchs** [comment]
I agree with @dkern: https://github.com/twbs/bootstrap/issues/32719#issuecomment-757046759: This is very confusing. I understood the build page exactly as he did.

**Comment by steainsworth** [comment]
As others have mentioned, what's the purpose of this page https://getbootstrap.com/docs/5.0/getting-started/build-tools/ if that's not the correct way of customizing/compiling bootstrap.
