### ISSUE TITLE
No sample code provided

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#32715]
https://github.com/twbs/bootstrap/blob/8095de20ea1f32c866a2dd228f1d328dd14647ab/docs/5.0/components/tooltips/index.html#L491-L499

No sample code provided

**Comment by mdo** [comment]
Do you mean that there's no included code snippet below the example in the rendered docs?

**Comment by zhangchenglin** [comment]
> Do you mean that there's no included code snippet below the example in the rendered docs?

Yes, I didn't see it.

**Comment by XhmikosR** [comment]
I don't think it makes sense to add the snippet here. We added this to visual test if an edge case was fixed. I guess we should either remove the example or make it a proper one.

**Comment by zhangchenglin** [comment]
> I don't think it makes sense to add the snippet here. We added this to visual test if an edge case was fixed. I guess we should either remove the example or make it a proper one.

Perhaps when adding, I want to tell people who read the document to support the use of svg images.
 I am afraid that only the person who added can explain the reason.

**Comment by XhmikosR** [comment]
For reference #30928

**Comment by mdo** [comment]
Visual tests shouldn't be in our docs IMO. So I'd say let's add the code and ensure the example works correctly (that's another open issue I think, yeah?), or move it somewhere else.

**Comment by XhmikosR** [comment]
I'm going to move this to the visual tests.

**Comment by mdo** [comment]
@XhmikosR Still want to move this? I'm also 100% happy just closing this out and living with it lol.

**Comment by XhmikosR** [comment]
I don't have the time to fix it, but let's keep it open for a little more.

/CC @tkrotoff in case you can move this to the visual tests.

**Comment by mdo** [comment]
Closing as stale since it's been a little while longer 😅
