### ISSUE TITLE
Tooltip not appearing for SVG in bootstrap example docs

### ISSUE THREAD

**Issue by fhnsjw** [twbs/bootstrap#32724]
Operating system: Linux
Browser: Chromium Version 87.0.4280.66

The tooltip appears once on the initial hover and then quickly disappears and does not appear again. This is in the Bootstrap docs for 5.0 (https://getbootstrap.com/docs/5.0/components/tooltips/#examples).

https://user-images.githubusercontent.com/77143498/103988019-00a6d100-5153-11eb-8c47-1ffd6dc4bfbc.mp4

**Comment by Mister-42** [comment]
Please see https://github.com/twbs/bootstrap/issues/32372
