### ISSUE TITLE
Dropdown with tooltip breaks on click, with errors

### ISSUE THREAD

**Issue by fhnsjw** [twbs/bootstrap#32725]
Operating system: Linux
Browser: Chromium Version 87.0.4280.66

When a dropdown is also given a tooltip, the tooltip works properly on hover. But once you click the dropdown, it breaks: the dropdown refuses to close and the tooltip will not disappear. Errors appear when the cursor hovers in/out:

```
Uncaught TypeError: Cannot set property 'hover' of undefined
    at o.r._enter (tooltip.js:117)
    at HTMLButtonElement.<anonymous> (tooltip.js:553)
    at HTMLButtonElement.n (event-handler.js:101)
Uncaught TypeError: Cannot set property 'hover' of undefined
    at o.r._leave (tooltip.js:117)
    at HTMLButtonElement.<anonymous> (tooltip.js:554)
    at HTMLButtonElement.n (event-handler.js:101)
```

https://jsfiddle.net/9q8xn40r/

**Comment by mdo** [comment]
Both components require the usage of `data-bs-toggle`, which cannot exist on the same element. You'd need to wrap the element I believe so that the two separate behaviors can function as desired.

/cc @twbs/js-review for confirmation.

**Comment by rohit2sharma95** [comment]
Tooltip can be initialized without `data-bs-toggle`, it is just a selector for initializing the tooltips.
But the main problem is that Bootstrap does not allow multiple plugins to be used on a single DOM element.
Ref: https://github.com/twbs/bootstrap/issues/32123#issuecomment-731020351

But it can be supported in #32180

/CC @XhmikosR

**Comment by XhmikosR** [comment]
I'm unsure if we should allow multiple plugins on the same element. And #32180 as is does not change this AFAICT.

We should close all issues about multiple plugins and create a new one to discuss it for v5.

**Comment by rohit2sharma95** [comment]
Yes, #32180 does not change the behavior yet. :+1:
But that's why that PR is pending IMO

**Comment by XhmikosR** [comment]
I'd rather not change the behavior in that PR. We need to have this in a separate PR with unit tests and further discussion. As long as the change is not a breaking one, we can land it on v5.
