### ISSUE TITLE
v5: SCSS btn-primary color: #000 is incorrect when NPM RUN DEV or NPM RUN PRODUCTION

### ISSUE THREAD

**Issue by networxx** [twbs/bootstrap#32731]
If I do btn-dark, btn-secondary, etc... the color is white or #fff but when I do btn-primary the font is black.

I did:  

```
npm install bootstrap@next
npm run dev or production

my app.scss
  // Bootstrap
  @import '~bootstrap/scss/bootstrap';


my index.html
 <button type="submit" class="btn btn-primary">
   Register
 </button>   
```

**Comment by mdo** [comment]
Colors automatically change based on the contrast level of the background-color.

**Comment by networxx** [comment]
That really doesn’t answer why btn-primary is not white


Warren

**Comment by networxx** [comment]
If I download the zip instead of npm run blah.... btn-primary color is correct - white

Not sure what bug is causing it to be incorrect.

**Comment by ffoodd** [comment]
Well, it does, in fact: `.btn-primary` background color does not provide sufficient contrast with white, thus it gets a black foreground.

Our core colors are used in a way that ensures accessibility.

**Comment by networxx** [comment]
Nope not buying it.  Look at the docs.  Btn-primary always was white and using the zip version of beta1 it's correct.  Running via npm it is not

**Comment by ffoodd** [comment]
You changed primary color, obviously.

Docs are built from sources, so if you didn't change anything you'd have the same output.

**Comment by networxx** [comment]
Ok, not getting same output.   So if the process I am doing is not wrong, there must be a bug.  I do understand that if you use a variant of blue or any of the default colors you have to determine somehow to use black or white as a font color.   I get it in that regard.   Any of the default colors should be hardcoded to white font per the docs.

![Screen Shot 2021-01-16 at 5 05 48 AM](https://user-images.githubusercontent.com/5412030/104812640-8280a500-57b8-11eb-8089-de219e287f26.png)

**Comment by networxx** [comment]
Where would I find the code that determine the font color to fix it?

**Comment by networxx** [comment]
> Well, it does, in fact: `.btn-primary` background color does not provide sufficient contrast with white, thus it gets a black foreground.
> 
> Our core colors are used in a way that ensures accessibility.

Did you ever use Bootstrap before?   btn-primary doesn't provide enough contrast?   At a loss here to understand what you are saying, sorry.

**Comment by networxx** [comment]
If I do NPM RUN DEVELOPMENT or PRODUCTION I am seeing this:

![Screen Shot 2021-01-16 at 6 39 13 AM](https://user-images.githubusercontent.com/5412030/104814809-9d0d4b00-57c5-11eb-8ef8-8b5225ae3fbc.png)

**Comment by networxx** [comment]
Looking at _variables.scss:

// The contrast ratio to reach against white, to determine if color changes from "light" to "dark". Acceptable values for WCAG 2.0 are 3, 4.5 and 7.
// See https://www.w3.org/TR/WCAG20/#visual-audio-contrast-contrast
$min-contrast-ratio:  3.0 !default;


The default is 4.5, changing this to 3.0 causes the default colors to work as expected.

**Comment by networxx** [comment]
Well 3.0 value didn't quite work
![Screen Shot 2021-01-16 at 6 58 05 AM](https://user-images.githubusercontent.com/5412030/104815250-46554080-57c8-11eb-9ce0-6d218f79877f.png)

But 2.0 did:

![Screen Shot 2021-01-16 at 6 58 22 AM](https://user-images.githubusercontent.com/5412030/104815255-4bb28b00-57c8-11eb-8cec-6623216e51a9.png)

What is the negative of having the colors match the expected colors?  Will other areas look incorrect?

**Comment by ffoodd** [comment]
Your blue does not provide sufficient contrasts with white, thus black is used as foreground color.

Lowering the threshold means that every component using our core `contrast-color()` function is likely to get insufficient contrasts too.

You're basically ruining your projects accessibility.

Since you seem to be able to use Sass to customize your build, I'd suggest you try to exclude your primary color  in the `color-contrast()` function instead.

**Comment by networxx** [comment]
Should be resolved before this gets out of Beta.    "your blue"?  It's the primary color of bootstrap for years.   Not my blue.   I can see what is trying to be accomplished and it's not working.  With 10 shades per color for sure the font color will need to adjust to provide sufficient contrast.

How many bootstrap websites depend on the core colors working as they always have?   To replace with v 5 will cause unnecessary issues.   

Or are you saying since 2011 when Bootstrap was released with these colors all the websites have had poor insufficient contrast?  That's nonsense....

So please stop arguing this bug is how it should be... it is what it is... WRONG.

This "Feature" needs to be flushed out and fixed.

**Comment by ffoodd** [comment]
> Or are you saying since 2011 when Bootstrap was released with these colors all the websites have had poor insufficient contrast?

This is exactly what I'm saying. We made several changes in v5 to improve the overall accessibility, including major changes to our core colors and functions related to contrasts.

BTW our current primary color evolved a bit in v5 to reach 4.5:1 and pass WCAG 2.1 success criterion. [Our doc page about colors](https://getbootstrap.com/docs/5.0/customize/color/) even displays contrast ratios against white and black to help you figure out their respective accessibility.

As [seen in our buttons doc](https://getbootstrap.com/docs/5.0/components/buttons/#examples), using Bootstrap as-is will use white foreground for `.btn-primary`.

Either you don't use our values for colors, or maybe your configuration to compile Sass does not match our (e.g. precision might influence the contrast ratio computation) but this clearly works as intended.

Moreover, you keep talking about your npm scripts but that's unrelated to Bootstrap, only with your own project and environment.

You didn't respect our issue template since you didn't provide a reduced test case. From our perspective, you didn't highlight any bug.

**Comment by mdo** [comment]
Hey @networxx, please provide a bit more context here and try not to get upset with us as maintainers. @ffoodd is only trying to help, and as he mentioned, you haven't given us much to work with. From your screenshot at https://github.com/twbs/bootstrap/issues/32731#issuecomment-761577130, it appears to me you've changed the `$theme-colors` and/or more default variables. Without full context of your code, dev environment, a live demo, or even a Sassmeister demo, we're not really able to give you much help other than "yes, that's how button color works."

Our buttons use a color contrast function to attempt to always create accessible `color`/`background-color` combinations. With modified colors, you're very likely to encounter different `color`s on our buttons.

Are you able to provide any other context here?

**Comment by networxx** [comment]
Ok, I have not changed any colors/themes.   What I did was download the ZIP file and everything works as expected.  The default colors work as they have from Bootstrap 1 forward.  When I do the npm run dev or npm run production on the SCSS files the default colors no longer work.

I do understand you all are trying to get it so you don't have to rely on default colors but could easily put your own and build it and the system would auto determine the font color to make it sufficient contrast.  That feature is broken as it breaks the default colors.

To be told "That's they way it is suppose to work" is nonsense.   Clearly there is insufficient contrast if you use the default color's in SCSS.    

So at a loss as to why the team there feels it's unnecessary to get this particular issue revisited.

Clearly the default way btn-primary works in beta 1 provides insufficient contrast and breaks almost 10 years of bootstrap default colors.

![Screen Shot 2021-01-17 at 4 43 52 AM](https://user-images.githubusercontent.com/5412030/104843276-9c84bb00-587e-11eb-93ef-b8ac134a5c42.png)

**Comment by networxx** [comment]
Bootstrap 1 Default Colors, which does provide sufficient contrast... has for 10 years?


![Screen Shot 2021-01-17 at 4 45 29 AM](https://user-images.githubusercontent.com/5412030/104843323-dce43900-587e-11eb-898d-b610e5e0c540.png)

**Comment by mdo** [comment]
![image](https://user-images.githubusercontent.com/98681/104850097-e16e1900-58a1-11eb-8fb9-919eeb32c0a3.jpeg)

I just don't understand how those are the v5 Beta 1 default colors for you when this is what is in our docs.

**Comment by networxx** [comment]
https://getbootstrap.com/docs/5.0/customize/color/

**Comment by mdo** [comment]
Don't know what to tell you... I just created a new test, imported Bootstrap via npm, included it into a test `.scss` file, compiled the Sass, and this is how the buttons look. You've clearly customized the `background-color`s—either directly, through variables, through the `$theme-colors` Sass map, or something else—because those really aren't our default colors.

<img width="2560" alt="Screen Shot 2021-01-17 at 5 02 14 PM" src="https://user-images.githubusercontent.com/98681/104861760-f7053200-58e5-11eb-8a2a-663c10257a04.png">

**Comment by networxx** [comment]
I used: **npm install bootstrap@next**

What could cause it to be different on my system?

Here's my package.json contents:

{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "bootstrap": "^5.0.0-beta1",
        "cross-env": "^7.0.3",
        "jquery": "^3.5.1",
        "laravel-mix": "^5.0.9",
        "lodash": "^4.17.20",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.32.4",
        "sass-loader": "^8.0.0",
        "vue": "^2.6.12",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "@popperjs/core": "^2.6.0"
    }
}

**Comment by networxx** [comment]
Well... you all are correct.   I just started looking at the _variables.scss file in the node_modules directory vs in my app's directory and that's where the color changed happened.   I overwrote the values in the app's scss file and presto... back to normal bootstrap colors.     

I'm using Laravel and not sure how those colors got whacked.

Thank you for hanging in there with me and showing me.  That helped a bunch.

**Comment by cotiga** [comment]
I overwrote the $primary value with #007bff and black text is now in the btn-primary

I recovered the white text by overwriting the value $min-contrast-ratio to 3.0 (4.0 by default)

I'm not sure that the default value of $min-contrast-ratio is correct, it seems to me that the text #fff is more readable on #007bff

Voila, it's just how I feel
