### ISSUE TITLE
was-validated should not override is-invalid

### ISSUE THREAD

**Issue by matejskubic** [twbs/bootstrap#32733]
When form is validated (`was-validated`) fields with error (`is-invalid`) shows green border with green check.

As [documentation](https://getbootstrap.com/docs/4.5/components/forms/#how-it-works) reads javascript should not override server side validation.

> As a fallback, .is-invalid and .is-valid classes may be used instead of the pseudo-classes for server side validation. They do not require a .was-validated parent class.

![image](https://user-images.githubusercontent.com/839965/104074623-e03d4c00-5210-11eb-96d7-97ec575f4aba.png)

[sample](https://output.jsbin.com/licanunaqe)

bootstrap version: 4.5.3

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <title>was-validated should not override is-invalid</title>
</head>
<body>
  
<form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-4">
      <label for="validationCustom03">needs-validation</label>
      <input type="text" class="form-control is-invalid" value="x" id="validationCustom03" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
  </div>
</form>
  <hr />
<form class="was-validated" novalidate>
  <div class="form-row">
    <div class="col-4">
      <label for="validationCustom03">was-validated</label>
      <input type="text" class="form-control is-invalid" value="x" id="validationCustom03" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
  </div>
</form>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by YisusCore** [comment]
If you wants to control the validations states with js yo need to replace  `is-invalid` to `is-valid` each input form control, but if you  remove the `is-invalid` class so these automatically change with css

```html
 <form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-4">
      <label for="validationCustom03">needs-validation</label>
      <input type="text" class="form-control" value="x" id="validationCustom03" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
  </div>
</form>
  <hr />
<form class="was-validated" novalidate>
  <div class="form-row">
    <div class="col-4">
      <label for="validationCustom03">was-validated</label>
      <input type="text" class="form-control" value="x" id="validationCustom03" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
  </div>
</form>
```


```html
<input type="text" class="form-control" value="x" id="validationCustom03" required>
```


Regards

**Comment by mdo** [comment]
What @YisusCore said :).

**Comment by fhughes90** [comment]
I agree with OP. If you have a specific input with a class `.is-invalid`, then the parent `.was-validated` CSS should not override this input's CSS.

For example: one of my inputs is using server-side validation and it is independent from the rest of the form's submission (its necessary information for the form, but it handles unique error messages), and the rest of the inputs are static values that have no validity, just that they are required. If I submit my form with the .is-invalid input, I get both valid and invalid feedbacks. See my example.

![Screen Shot 2022-04-27 at 11 48 24 PM](https://user-images.githubusercontent.com/43258357/165672543-5d5f93c7-6fa1-4c56-92f8-7498bc7cd11b.png)

**Comment by Seraffimo** [comment]
@mdo Curious why this was closed. Agree with both @fhughes90 and @matejskubic 

The specific issue for me occurs on a form used in an AJAX POST.  I have a date field that I want to validate on the server side. Client side validation is not required for this form element (type="text"). I have five other elements in the form that require client side validation. When all form elements pass client validation,  all six elements are marked as valid (e.g. was_validated on form triggers styling) and the POST is submitted. If the date field has an error as noted on the server, the date field <input> classList has (is-invalid) added and in my case the <div id="id_trade_view_fromdtTooltip" class="invalid-tooltip"> is triggered. 

However, the original client side validation remains. In the same way client side validation can selectively mark invalid fields, the same option should be available if an individual field needs server side validation. Maybe there is a way to do this, but I do not see how. i.e. is-invalid should be equivalent to client side validation :invalid. 

![image](https://user-images.githubusercontent.com/6089321/196812932-201e234a-eff6-42ee-89d7-342ceda94593.png)

**Comment by blasticbe** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/55191529/202272013-edf7966e-7a28-48af-804a-f73d394ae392.png)

The `.form-control.is-invalid` selector does not carry enough weight and becomes "valid" by the `.was-validated .form-control:valid` state.

Replacing the `is-invalid` with `is-valid` makes no sense to me as I put it there.
Stating that those classes are for backend sounds nice, but in practice it gives false feedback.
So to me this is also a bug.

`/* dirty override caused by ".was-validated .form-control:valid" outweighing ".form-control.is-invalid" */
.form-control {
    &:valid {
        &.is-invalid {
            background-image: escape-svg($form-feedback-icon-invalid);
            background-repeat: no-repeat;
            background-position: right calc(0.375em + 0.375rem) center;
            background-size: calc(0.75em + 0.75rem) calc(0.75em + 0.75rem);
            border-color: $form-feedback-invalid-color;
            padding-right: calc(1.5em + 1.5rem);

            &:focus {
                border-color: #dc3545;
                box-shadow: 0 0 0 0.25rem rgb(220 53 69 / 25%);
            }
        }
    }
}`

**Comment by timver** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/55191529/202272013-edf7966e-7a28-48af-804a-f73d394ae392.png)

The `.form-control.is-invalid` selector does not carry enough weight and becomes "valid" by the `.was-validated .form-control:valid` state.

Replacing the `is-invalid` with `is-valid` makes no sense to me as I put it there.
Stating that those classes are for backend sounds nice, but in practice it gives false feedback.
So to me this is also a bug.

`/* dirty override caused by ".was-validated .form-control:valid" outweighing ".form-control.is-invalid" */
.form-control {
    &:valid {
        &.is-invalid {
            background-image: escape-svg($form-feedback-icon-invalid);
            background-repeat: no-repeat;
            background-position: right calc(0.375em + 0.375rem) center;
            background-size: calc(0.75em + 0.75rem) calc(0.75em + 0.75rem);
            border-color: $form-feedback-invalid-color;
            padding-right: calc(1.5em + 1.5rem);

            &:focus {
                border-color: #dc3545;
                box-shadow: 0 0 0 0.25rem rgb(220 53 69 / 25%);
            }
        }
    }
}`

**Comment by SteveLogan206** [comment]
@Seraffimo did you ever find a solution?  I'm hitting the exact same problem you illustrated above with was-validated overriding the is-invalid on a field that validates with a ajax call.

**Comment by ffoodd** [comment]
If your field should be invalid, you need to trigger the `:invalid` pseudo-class through JavaScript using `setCustomValidity()` ([example in SO](https://stackoverflow.com/questions/10777970/can-i-mark-a-field-invalid-from-javascript) and some docs on MDN).

If your server validation does not handle client-side validation, you should not use `.was-validated` on your form but only `.is-invalid` on your fields. 

On the browser side, if your field matches its `type` and `pattern` rules, it is valid. So it is.

**Comment by LeDoanh** [comment]
> If your field should be invalid, you need to trigger the `:invalid` pseudo-class through JavaScript using `setCustomValidity()` ([example in SO](https://stackoverflow.com/questions/10777970/can-i-mark-a-field-invalid-from-javascript) and some docs on MDN).
> 
> If your server validation does not handle client-side validation, you should not use `.was-validated` on your form but only `.is-invalid` on your fields.
> 
> On the browser side, if your field matches its `type` and `pattern` rules, it is valid. So it is.

Nice, you saved my day, thank you!
