### ISSUE TITLE
[Docs] v5 migration guide doesn't mention removal of .rounded-sm/lg

### ISSUE THREAD

**Issue by kylefox** [twbs/bootstrap#32734]
It looks like #31687 removed `.rounded-sm` and `.rounded-lg` and introduced `.rounded-0`-`.rounded-3`

This change totally makes sense, but I think maybe it's missing from the [Migrating to v5](https://getbootstrap.com/docs/5.0/migration/) docs?

**Comment by k99sharma** [comment]
Hi this is my first time contributing. I tried to solve this issue can anyone check if its right.
