### ISSUE TITLE
Fuck Twitter.  I Love Trump.

### ISSUE THREAD

**Issue by kkkkiwi** [twbs/bootstrap#32741]
Twitter is pure evil. 
What you are doing is disgusting.
Fire your Boss. Worry jobs?  You are the best programmers in the world. Let the fool suck Biden's cock.

**Comment by mdo** [comment]
User has been reported to GitHub and has been blocked from the organization here.

_And in case you're wondering, Twitter hasn't had anything to do with Bootstrap for eight years and no one there will see this._
