### ISSUE TITLE
Dropdowns stopped working after using const modal = new Modal()

### ISSUE THREAD

**Issue by FotiadisM** [twbs/bootstrap#32749]
package.json:
```json
    "@popperjs/core": "^2.6.0",
    "@types/bootstrap": "^5.0.0",
    "bootstrap": "^5.0.0-beta1",
```
I am using html to toggle the dropdown menu using the `data-bs-toggle="dropdown"` attribute, as shown in the docs, and it work fine.
However, in a completely different state of my application, I am trying to show a Modal using javascript.

```javascript
import { Modal } from "bootstrap"

const showModal = (): void => {
    const modal = new Modal(document.getElementById("newDateModal")!);
    modal.show();
  };
```

And this causes all the Dropdown to stop working. The line of code that creates the problem is
```javascript
const modal = new Modal(document.getElementById("newDateModal")!);
```
Tested on:
nodejs v10.19.0
typescript 4.0.3
amd64 / Ubuntu 20.04
Chromium 87.0.4280.141 snap
Mozilla Firefox 84.0.2

**Comment by omares** [comment]
@FotiadisM Hey we are encountering the same issue, mind sharing how you solved the problem? Thank you!

**Comment by omares** [comment]
After a bit of more research, I stumbled upon the Stackoverflow post [Bootstrap 5 with Angular 12 : bootstrap (navbar, dropdown) interactions are blocked after get/create bootstrap instances by JavaScript](https://stackoverflow.com/a/68664655/550640) which provides the solution for the problem by importing directly from the dist folder: 

> I found the solution that is answered in another question where the dropdown is broken when a modal instance is created. In my case, the dropdown and also the navbar was broken!
> 
> Instead of the
>
> `import { Modal } from 'bootstrap';`
> 
> needed
>
> `Import { Modal } from 'bootstrap/js/dist/modal';`

**Comment by RuiQiHuang1832** [comment]
> import Popover from "bootstrap/js/dist/popover"

Omg thank you so much, was having this problem and this fixed it

**Comment by programarivm** [comment]
This worked for me: 

```js
import Modal from 'bootstrap/js/dist/modal.js';
```
