### ISSUE TITLE
Bootstrap forms new version 5.0.0 not behaving like version 4.5.0

### ISSUE THREAD

**Issue by LamiaChiguer** [twbs/bootstrap#32742]
Hello Bootstrap Team,

I am new to bootstrap and while doing a homework for Html forms I copied the css line for version 5.0.0 and I was removing some lines from the form which gives me this and modified just the button with a submit input: 

```html
<form>
            <div class="form-group">
              <input
                type="text"
                placeholder="Enter your username"
                class="form-control"
                autofocus
              />
            </div>
            <div class="form-group">
              <input
                type="password"
                placeholder="Enter your password"
                class="form-control"
              />
            </div>
            <input type="submit" value="Login" class="btn btn-success" />
          </form>
```

When I use the line for bootstrap 5.0.0 there is no spacing between the boxes but my professor Matt used version 4.5.0 which when I use that line it does work.
I think in the new version there is a problem with the classes.

I hope this will be fixed.
Thank you

**Comment by mdo** [comment]
v4 and v5 are a bit different. `.form-group` was dropped for utilities like `.mb-3`.
