### ISSUE TITLE
Single card within accordion is missing bottom border

### ISSUE THREAD

**Issue by Rhobal** [twbs/bootstrap#32757]
I have a single card within an accordion
In this case, the `.accordion .card:last-of-type` and `.accordion .card:first-of-type` classes both apply and mess with the borders

The selector `.accordion.card:first-of-type` should be changed to `.accordion.card:last-of-type:not(:only-of-type)`; same for last-of-type

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by Rhobal** [comment]
Ok, it seems I cannot easily reproduce it in a live demo, as https://github.com/twbs/bootstrap/blob/main/scss/_card.scss does not contain the .accordion dependenend card classes my browser tells me I got from https://stackpath.bootstrapcdn.com/bootstrap/scss/_card.scss, so the demo based on 4.5.2 does not collapse cards at all.
I therefore retract the issue.
