### ISSUE TITLE
Error when trying to build example code

### ISSUE THREAD

**Issue by jeanlucaslima** [twbs/bootstrap#32777]
I just tried downloading example "Starter Template" [from this page](https://getbootstrap.com/docs/5.0/examples/). Got the zip file, expanded it in a folder, ran `git init && npm install`, everything installed correctly. When running  `npm start` I got the following error: 

```
Error: Error building site: "/Users/username/dev/project-folder/site/content/docs/5.0/getting-started/browsers-devices.md:19:4": failed to render shortcode "rf.inline": failed to process shortcode: template: _inline_shortcode/docs/5.0/getting-started/browsers-devices.md/rf.inline:2:4: executing "_inline_shortcode/docs/5.0/getting-started/browsers-devices.md/rf.inline" at <readFile ".browserslistrc">: error calling readFile: file ".browserslistrc" does not exist
```

[Here's the log](https://gist.github.com/jeanlucaslima/391ce3b7fca0bb31a0d0a496590e9a92).

- OS: macOS X Big Sur 11.1
- Browser: Firefox
- Suggested fix: add `.eslintrc.json` file and/or adapt the npm script.

**Comment by XhmikosR** [comment]
You are not supposed to use our scripts if you use the zip file. The zip file offers the built examples for people to use without anything else.

If you want to use our build scripts, you should use your fork.

**Comment by jeanlucaslima** [comment]
@XhmikosR it is not clear then for the users, cloning/forking the repo is not exposed on the website as a suggestion or tip to use it. Could we make it clear(er) to the user?

**Comment by XhmikosR** [comment]
Feel free to submit any PR to improve things but please make sure it's not covered already.

**Comment by prodkt** [comment]
Same issue here.
