### ISSUE TITLE
Docs: Standard Select Chevron Not Aligned Correctly When Compared to Custom Select

### ISSUE THREAD

**Issue by Joyrex** [twbs/bootstrap#32783]
Standard Selects as defined here in the Docs: https://getbootstrap.com/docs/4.5/components/forms/#form-controls

The chevron is misaligned/too close to the edge of the input in comparison to the Custom Select in BS:

Standard select:
![image](https://user-images.githubusercontent.com/651646/104512917-88a63400-55b4-11eb-9b79-83e253b5ae78.png)
Custom select:
![image](https://user-images.githubusercontent.com/651646/104513011-a4a9d580-55b4-11eb-88d1-dbd8a468ed65.png)

Standard select in Chrome looks like this (thanks to W3C Schools):
![image](https://user-images.githubusercontent.com/651646/104513244-f05c7f00-55b4-11eb-8709-1acbd409aae6.png)

Appears this way on both MacOS 11 and Win 10 Google Chrome, latest stable build

- Win 10 and Mac OS 11
- Google Chrome (both OSes)
- See 4.5.3 docs (and screenshots)

**Comment by mdo** [comment]
#31198 and #31059

Only solution we can recommend is using `.custom-select` instead.
