### ISSUE TITLE
Order breakpoints

### ISSUE THREAD

**Issue by Sin3W** [twbs/bootstrap#32780]
Good day,

I'm starting with Bootstrap 5 after a few years using bootstrap. 

I think I've found an issue, with ordering classes, they are not set for all breakpoints, I cannot reorder with order-lg-XX or order-xl-XX,

For example, I have the following:

`<div class="order-1 order-lg-2">1 on sm, 2 on lg</div>`
`<div class="order-2 order-lg-1">2 on sm, 1 on lg</div>`
`<div class="order-3">3 on sm, 3 on lg</div>`

And when LG screens is not ordering, I've checked the CSS applying and order-lg-2 does not appear as class.

Could you please check?

Thanks!

**Comment by mdo** [comment]
Without a live demo, we can't say. However, our `order` utilities do exist and are enabled by default.

https://getbootstrap.com/docs/4.5/utilities/flex/#order

https://getbootstrap.com/docs/5.0/utilities/flex/#order
