### ISSUE TITLE
Boostrap 5 modal close all modals

### ISSUE THREAD

**Issue by zolyyy** [twbs/bootstrap#32786]
If i have 2 modals and i click on second modal close, close both modal

**Comment by mdo** [comment]
Multiple modals are still not supported in Bootstrap, this is expected.

**Comment by zolyyy** [comment]
i found solution: 
<div class='modal-header'>
   <script>var modal_name = new bootstrap.Modal( document.getElementById( 'id' ) );</script>
   <h5 class='modal-title'>title</h5>
   <button type='button' class='btn-close' onclick='modal_name.hide();' aria-label='Close'></button>...
