### ISSUE TITLE
Cannot access https://stackpath.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css, but http is OK

### ISSUE THREAD

**Issue by HelenChen-2021** [twbs/bootstrap#32790]
Hi,

I am not able to access below URLs with **https** while it says **timed-out**, but **http** is OK. At the mean time, in the same machine and same browser, other websites with https are OK to be accessed without problem.

I am not the only person who meet this issue, but at least other 3 people around me have the same problem.

```
https://stackpath.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
https://stackpath.bootstrapcdn.com//bootstrap/3.3.4/css/bootstrap.min.css
```

OS: Mac 10.15.7, Win10
Browser: Chrome 87.0.4280.141, Safari 14.0 (15610.1.28.1.9, 15610) , Edge 87.0.664.75

Is there might be some settings I need to change in order to access them? Any tips is much appreciated.
Thank you.

**Comment by mdo** [comment]
Use jsDelivr instead: https://www.jsdelivr.com/package/npm/bootstrap.

The BootstrapCDN team is basically no more and we now recommend this new CDN

**Comment by HelenChen-2021** [comment]
Hi @mdo ,

Much appreciated for your fast reply. I will forward back to our team about it. 

Regards,
Helen

**Comment by HelenChen-2021** [comment]
Hi @mdo,

Update to you that the new CDN works well for us.
Much appreciated for your great help. :)

Regards,
Helen
