### ISSUE TITLE
Add class for XS only space utilities in order to separate them and not applyting it to all other sizes

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#32803]
Sop basically for example to use a class like "pl-xs-5"

While I googled a solution I found this topic that explains it very clearly:
https://stackoverflow.com/questions/50879179/apply-bottom-margins-in-bootstrap-4-only-in-xs-smartphone-and-iphone

**Comment by mdo** [comment]
`xs` is the same as no infix.

So `pl-xs-5` is actually `pl-5`. And your request of limiting them to a specific breakpoint isn't how we've architected Bootstrap, so no plans to make that change or add additional classes to do that.

**Comment by tomasts248** [comment]
But then I have to resort to this hack: <div class="mb-4 mb-sm-0"></div>

**Comment by mdo** [comment]
That's not a hack, that's by design :).

**Comment by tomasts248** [comment]
Oh I see, and what happens when I add it to a .col that originally has padding, it will remove those :(

**Comment by mdo** [comment]
Consider the gutter utilities for that :). v4 had some problems with inconsistent sizes between a gutters and spacer utilities, but we ironed that out in v5.

**Comment by tomasts248** [comment]
That's great thank you :-)
