### ISSUE TITLE
Select with Search option 

### ISSUE THREAD

**Issue by imprathamesh** [twbs/bootstrap#32801]
Why there is no select with search option ?
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by mdo** [comment]
Please actually read and respond to the issue templates instead of including them in your comment :).

> Why there is no select with search option ?

No idea what that actually would be. 😬 Please provide some examples or something.

**Comment by mdo** [comment]
Closing until we hear more.

**Comment by goodwin74** [comment]
Yes, I was looking for a similar one too. And I was surprised that this was not implemented!

Here is an example of what the author is talking about and what I am talking about: [](https://jsfiddle.net/t8oLmr96/)

**Comment by goodwin74** [comment]
> Closing until we hear more.

I would like to see something like this in the documentation, a very necessary element! I think many will be happy about this!
