### ISSUE TITLE
BootStrap is not rendering properly on IE11. 

### ISSUE THREAD

**Issue by justinjalandoniiwest** [twbs/bootstrap#32802]
Here it is on Firefox:

![image](https://user-images.githubusercontent.com/75491773/104633604-5858b580-56da-11eb-9651-7105e5c95dbc.png)

and here it on IE11 (it's not rendering properly)

![image](https://user-images.githubusercontent.com/75491773/104633639-6575a480-56da-11eb-8eab-1ab8ec4d4bc8.png)

Here are other comparisons. The button is not rendering properly

![image](https://user-images.githubusercontent.com/75491773/104634004-fba9ca80-56da-11eb-8324-15595529b0c3.png)

![image](https://user-images.githubusercontent.com/75491773/104634033-06fcf600-56db-11eb-9b7b-4cd03c6d8688.png)

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by justinjalandoniiwest** [comment]
> 
> 
> Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.
> 
> _This is a saved reply._

Is this a bot?

**Comment by justinjalandoniiwest** [comment]
![X1Kv1oiXc7](https://user-images.githubusercontent.com/75491773/104634930-36f8c900-56dc-11eb-9f5e-ee89db97cbbb.gif)

If you need to test it view this [link](http://itg.iwestgroup.com/) on IE and any other modern browser

**Comment by mdo** [comment]
It's a saved reply. And our issue template guidelines mention this stuff before you post :).

Also worth noting, if this is with v5, we don't support IE11.

**Comment by mdo** [comment]
Posted that around the same time as your last comment. You need to create a reduced test case that shows this problem is from our project's default code base, which rules out anything you've modified or added. Please open a new issue when you've done that and we can help. Otherwise, head to the Slack community, Discussions tab, or StackOverflow.

**Comment by justinjalandoniiwest** [comment]
Do you still have support for BootStrap 3?

**Comment by mdo** [comment]
Nope, we haven't for years.
