### ISSUE TITLE
Use of `.bg-white` class in docs makes theming difficult in v5 - replace with `.bg-body`

### ISSUE THREAD

**Issue by vinorodrigues** [twbs/bootstrap#32810]
A few of the example files make use of the **`.bg-white`** class to define visual aspects of the examples.  Using this makes theming tests problematic without modification either to the docs source, or defining theme colors unintuitively (e.g. `.bg-white` is black?)

Use of directly calling color classes should be discouraged - i.e for the examples, **`.bg-body`** should be used instead.

The following files make use of `.bg-white`:
* `site/content/docs/5.0/utilities/shadows.md`
* `site/content/docs/5.0/examples/product/index.html`
* `site/content/docs/5.0/examples/offcanvas/index.html`
* `site/content/docs/5.0/examples/cover/index.html`
* `site/content/docs/5.0/examples/pricing/index.html`
* `site/content/docs/5.0/examples/cheatsheet/index.html`
* `site/content/docs/5.0/examples/cheatsheet-rtl/index.html`

Also, `site/content/docs/5.0/utilities/colors.md` file does not document the use of the **`.bg-body`** class ... it's missing.

**Comment by ErlendCat** [comment]
If nobody is working on this, I am able to. 
For me this dosent look like that big of a job? Just replace some stuff?
Note this would be my first contribution, so please say if I am doing anything wrong!

\- Erlend

**Comment by ffoodd** [comment]
@ErlendCat PR welcome 👌 Please read our contributing guidelines carefully before you start.

**Comment by mdo** [comment]
Would love a `.bg-body` class—great idea.

**Comment by vinorodrigues** [comment]
@mdo ... it's already there.  Gets generated in `_utilities.scss`, line 474 (beta 1 code).
Just never been documented.

**Comment by mdo** [comment]
Hahaha, I'm the one that added it too lol. #29511

**Comment by vinorodrigues** [comment]
Created a pull request if you need one...  #32815

**Comment by ErlendCat** [comment]
Oh, I guess you guys fixed it before me. 🥇 😺

**Comment by vinorodrigues** [comment]
PR #32815 generated

**Comment by ffoodd** [comment]
Issue will close automatically as soon as the PR gets merged.
