### ISSUE TITLE
Card has extra margin when shown in column in card group

### ISSUE THREAD

**Issue by Kerndog73** [twbs/bootstrap#32814]
Cards in a card group are shown in a row until the extra small breakpoint, where the cards are shown in a column. The cards are spaced out in the column using a bottom margin. However, the bottom card also has a bottom margin which can leave a bit of extra space at the bottom of a container.

See this [CodePen example](https://codepen.io/kerndog73/pen/yLaGXrw). If you resize the browser window to be narrower than 576px, the cards will be in a column but there's an extra bit of space at the bottom. The example also includes a commented out workaround that will be repeated here.

```css
.card-group > .card:last-child {
  margin-bottom: 0;
}
```

My proposed solution is to change [`_card.scss:162`](https://github.com/twbs/bootstrap/blob/bb19b08fbe41157c5a6e8238ecefda064adda318/scss/_card.scss#L162) to the following.

```scss
> .card:not(:last-child) {
```

**Comment by mdo** [comment]
Think we've had this requested before and we defer to using our margin utilities instead of adding additional CSS.
