### ISSUE TITLE
Better Input range support

### ISSUE THREAD

**Issue by Benoit1980** [twbs/bootstrap#32813]
Hello,

It would be really nice to have a better support for the range input fields.
ie:
Let's say that instead of having a numeric range, you need a predefined range as:

Very slow
Slow
Medium
Fast 
Very Fast

Having the possibility to place values as above would be fantastic.

Thank you

**Comment by mdo** [comment]
Our range component is built on the range input, so when that component has better support, we'll be able to do something more there :). Until then, I imagine there are some JS solutions out there. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by Benoit1980** [comment]
Got it! Thanks for the update Mdo :-)
