### ISSUE TITLE
nav-tab anchors does not work when starting with numbers

### ISSUE THREAD

**Issue by yannickpschroeder** [twbs/bootstrap#32826]
A client of mine uses nav-tabs to navigate through products of a specific category. Some of the product names start with a number.
I added an code example which uses the example from https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior .
I just edited the first tab using the anchor id `1home` instead of `home` and the tab will not be activated anymore.

- Operating system: Ubuntu 20.04
- Browser and version: Mozilla Firefox 84.0.2 (64-Bit)
- A reduced test case: https://codepen.io/yannickpschroeder/pen/zYKeEMR

**Comment by alecpl** [comment]
Such an identifier is not a valid HTML identifier.

**Comment by thednp** [comment]
This is (afaik) an HTML5 limitation, which is that Element attributes are declared invalid when starting with a number, also CSS classes cannot start with a number.

**Comment by XhmikosR** [comment]
Yeah, we have an issue somewhere open to support this. #31099

**Comment by XhmikosR** [comment]
BTW v4.0 is pretty old, you should always try to use the latest 4.x version.
