### ISSUE TITLE
[v5] Remove font weight from dropdown items

### ISSUE THREAD

**Issue by robinheidrich** [twbs/bootstrap#32831]
The dropdown items have an unnecessary font weight set. ([See here](https://github.com/twbs/bootstrap/blob/main/scss/_dropdown.scss#L131))

It should be removed, or atleast should be given its own Sass variable ($dropdown-item-font-weight).

**Comment by SyDe-10** [comment]
hey I am new to open source, and would love for this issue to be my first.

**Comment by mdo** [comment]
Starting place would be identifying why we added it in the first place :).

**Comment by harshad71** [comment]
if it is not resolve should i work on it?

**Comment by mdo** [comment]
Similar to tooltips and popovers, I believe this is to prevent style bleeding. Leaving as-is unless someone wants to take a deeper dive into it.
