### ISSUE TITLE
Add ".bs-rtl" and at-rule supports also at-rule supports not for "inset" logical property

### ISSUE THREAD

**Issue by HNafiii** [twbs/bootstrap#32841]
Hi Bootstrap
Thank you for Bootstrap v5beta1 release
For your request to a bootstrap.css, a CSS Logical Properties: inset shorthand property and "bs-rtl"  class into bootstrap.css. My browser has supports inset-[block|inline]-[start|end] properties. Add at-rule supports for "inset" and non-"inset". For non-"inset" supported, add ".bs-rtl <<any-classes>>" and ":not(.bs-rtl) <<any-classes>>" for selector, and also left, right, top, and bottom for properties.

PS:
- Remove comments syntax RTLCSS on non-rtl css file.
- Remove any rtl css file.

Thanks.

**Comment by ffoodd** [comment]
We thought about logical properties to implement RTL (see #30918) however it does not cover reliably all of our use cases and browser support for now.

And regarding your `.bs-rtl` suggestion, we also evoked that and concluded it would be a nightmare to maintain and work with. It had also been requested again (e.g. in # #32666) and we won't implement this— however I documented a pretty simple way to make this in a custom build.

So I'm closing this as duplicate.
