### ISSUE TITLE
[v5] Please make the margin left and right back to mt and ml

### ISSUE THREAD

**Issue by lambasoft** [twbs/bootstrap#32847]
In version 5 the margin left and right got renamed to:

s - for classes that set margin-left or padding-left in LTR, margin-right or padding-right in RTL
e - for classes that set margin-right or padding-right in LTR, margin-left or padding-left in RTL

Why s & e?  l & r were so much easier to remember and is there a specific reason for this change? can we make it backward compatible with v4?

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.0/migration/#rtl

**Comment by gabriel-gn** [comment]
Should not be closed, as stated by bootstrap "The RTL feature is still experimental and will probably evolve according to user feedback".
Algo, "start" and "end" should be documented on the [Spacing Documentation](https://getbootstrap.com/docs/5.0/utilities/spacing/), as no one would ever think of those words. Top and Bottom are css standards for margin/padding, start and end are not (also, previous versions had "l" and "r" for left and right)

**Comment by ffoodd** [comment]
Please search other issues and discussions on the topic. Short things first: we changed them to ease working with RTL. 

Also start and end are standards, known as "logical properties".

Moreover incoming in our docs: how-tos to either rename or alias utilities thanks to our utility API. It only requires you make your custom build using Sass.
