### ISSUE TITLE
v5: negative margins not works...

### ISSUE THREAD

**Issue by anonymuos1** [twbs/bootstrap#32851]
Hi!

.mx-n1, .mx-n2, .mx-n3 not works...

I use bootstrap CDN.

**Comment by CyrilKrylatov** [comment]
Hi,

Did you tried to [enable this Sass variable to true](https://getbootstrap.com/docs/5.0/utilities/spacing/#negative-margin) as expected from the doc?

**Comment by mdo** [comment]
Correct, they're not enabled by default in v5.

**Comment by harpreetsb** [comment]
can we get the compiled version for same?

**Comment by harpreetsb** [comment]
Or atleast provide them in CDN or make 2 different versions.
