### ISSUE TITLE
how i can build two .css file with webpack for rtl and ltr

### ISSUE THREAD

**Issue by vahidalvandi** [twbs/bootstrap#32854]
hi . how i can active bootsrap 5 rtl with scss?

**Comment by ffoodd** [comment]
You need to run RTLCSS on your compiled CSS files, [as mentionned in our docs](https://getbootstrap.com/docs/5.0/getting-started/rtl/#customize-from-source). RTLCSS post-processes your CSS files.
I'd recommend you check [RTLCSS getting started page](https://rtlcss.com/learn/usage-guide/install/).

We're constantly improving our docs so if you have any suggestion (explanations or examples), feel free to open a PR or discuss them in this issue.

**Comment by vahidalvandi** [comment]
i want use scss version for change variables

**Comment by ffoodd** [comment]
Did you read our docs?

There's a single scss source for both directions. We use RTLCSS comments syntax to tweak things for RTL, but you need to run Sass then RTLCSS to get your RTL outputs. Please read our docs.
