### ISSUE TITLE
Why is "white" in the color palettes but not "black"?

### ISSUE THREAD

**Issue by vinorodrigues** [twbs/bootstrap#32859]
There are several color related CSS items that contain the "white" color. These include:

- (CSS var) `--bs-white`
- `.border-white`
- `.text-white`
- `.bg-white`

One can argue that this is the contradictory of `-dark` elements, but it's not.  The opposite of `-dark` is `-light`.  The opposite of "white" is "black" 

Also, "light", "dark" are color aliases, and theme makers would used these to tune their palettes, but named colors should remain logical... i.e. "blue" should be *(a shade of)* blue.  In BS core the `white` is often used as the antidote for `dark` (#32810), because the palette is white and one needs something that is not "light" (has a different tint) - but this does not account for alternate themes.

BTW - there is a "white-50" and a "black-50", so it's been thought about... just no "black".

Adding black should be a quick change to the '_utilities.scss' and '_variables.scss' files.  *(I can create a PR if you agree.)*

**Comment by mdo** [comment]
Pure black is rarely needed and often avoided in color palettes. As far as I know this is the first request for adding it, so not in a hurry to make the change just yet.

**Comment by vinorodrigues** [comment]
Ok

**Comment by 11bits** [comment]
I agree with this proposal. "Black" hasn't necessarily to be pure black, but the darkest color of the palette, in contrast with "white."
