### ISSUE TITLE
Page auto scrolls up 

### ISSUE THREAD

**Issue by offlineC** [twbs/bootstrap#32861]
The page auto scrolls up after refreshing/hard refreshing. This happens with the v5 beta version. It does not happen when I use v4.6.

**Comment by anitaparmar26** [comment]
Yes, we are facing the same issue in the bootstrap v5 beta version.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by anitaparmar26** [comment]
I found a link from a page of Bootstrap 5 examples. Click on the footer link and also the hero section button. It will scroll on top.
[page](https://getbootstrap.com/docs/5.0/examples/product/#)

**Comment by ffoodd** [comment]
Those are links to anchor that does not exist (`href="#"`) so this is the standard behaviour, [you may compare with v4.6](https://getbootstrap.com/docs/4.6/examples/product/#). 

What you describe is a standard browser behaviour. Are you able to provide an example that works differently in v5 compared to v4?

**Comment by mdo** [comment]
Closing per last comment.
