### ISSUE TITLE
Adding padding to a fixed navbqr doesn't work

### ISSUE THREAD

**Issue by nickperks** [twbs/bootstrap#32860]
I'm tried to create a fixed never in version 5.0 but it overlaps my content.  So I added padding to the body but this didn't work.  Is this an issue with version 5 or am I doing something wrong.  I looked for an answer butvtheyvsll related to version 4.  

Thanks for any help you might give.

Regards

Nick

**Comment by mdo** [comment]
Should work the exact same way. I'd suggest providing a live demo of the problem next time though so we can better help you.
