### ISSUE TITLE
Swipe on open Modal, using in small devices (tablet, cellphone)

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#32876]
A thing I told by a UX expert the previous days, is that modals on small devices, act as a new screen/page. 
So they must act the same (as page) on the swipe event.
Now if a user swipes, it will be transferred on previous page, instead of simple close the modal

Do you find a good idea to support this behavior?

Native code may be borrowed from carousel.js or [here](https://stackoverflow.com/questions/2264072/detect-a-finger-swipe-through-javascript-on-the-iphone-and-android), and shared on both components

**Comment by mdo** [comment]
I don't think we should explicitly support swiping on modals to navigate pages. That kind of behavior feels very contextual, with the right design and content affording that kind of behavior. I think we'll pass on that :).
