### ISSUE TITLE
when data live search is enabled, tabindex is not working

### ISSUE THREAD

**Issue by lijuthn** [twbs/bootstrap#32879]
Hi,

We are facing a tabindex issue in the Select when data live search is enabled. Tabindex is not working while enabling the data live search. After the focus goes to the textbox when we press the down arrow it is not navigating to the select options.

We are using bootstrap select v1.6.2, checked in windows OS and chrome browser Version 87.0.4280.141

**Comment by mdo** [comment]
You need to open this issue with the maintainer of that project—we don't maintain `bootstrap select` here.
