### ISSUE TITLE
Bootstrap 5 row width Problem

### ISSUE THREAD

**Issue by eldanizguluzade** [twbs/bootstrap#32878]
--bs-gutter-x: 1.5rem;

For row Have a  width problem.
For fix --bs-gutter-x: 0;

**Comment by Danser901** [comment]
> --bs-gutter-x: 1.5rem;
> 
> 
> 
> For row Have a  width problem.
> 
> For fix --bs-gutter-x: 0;
> 
>

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
