### ISSUE TITLE
CDN missing .mr-{0,1,2,..} CSS classes 

### ISSUE THREAD

**Issue by ajs11174** [twbs/bootstrap#32887]
file: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css

The above file does not contain any of the margin right classes. It does have the margin left, top and bottom classes. 

The above file is listed as the CDN on this page: https://getbootstrap.com/docs/5.0/getting-started/introduction/

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.0/migration/#rtl
