### ISSUE TITLE
Dropdown not working with Bootstrap.js(beta version) this Javascript file is the cause

### ISSUE THREAD

**Issue by thor456** [twbs/bootstrap#32898]
I was trying to switch to the latest Bootstrap 5 beta with the newly features added. 

**Bootstrap 5 beta** does not support dropdown, dropdown not working with bootstrap 5. 

I have previously built Bootstrap 5 templates, which I have tested to build Wordpress Theme. But for unknown reason, latest Bootstrap version does not working or supporting **dropdown**

To test the cause under the issue, I have tested with individual `js` and `css` files with each Wordpress theme and one file change with the name, like changing bootstrap0.css and the bootstrap.css. 
Found out dropdown is working smooth with the Previous Bootstrap versions, but latest Bootstrap does not because of bug or any hidden feature, does not support directly. 

The issue was resolved only with rollbacking `bootstrap.js` to previous bootstrap JavaScript version.

**Comment by mdo** [comment]
Check the migration guide, you've likely missed a renamed data attribute. Also, please provide demos next time. We can't help without more information.

**Comment by thor456** [comment]
I think I missed some demos, building theme is so stressful thing. 

After copying code from Bootstrap 5 Dropdown the dropdown works now with the latest bootstrap beta version JavaScript. 

How to put example here. Do github support html engine like w3school or Stackoverflow?

Or just put directly only the MWE(minimum working example) so that developers test them.
