### ISSUE TITLE
V5, popover not working on webpack project

### ISSUE THREAD

**Issue by navalex** [twbs/bootstrap#32897]
Operating System: Windows 10
Browser: Chrome

Packages on package.json:
```json
{
"@popperjs/core": "^2.6.0",
"bootstrap": "^5.0.0-beta1"
}
```

I'm creating a popover with this line:
```javascript
import '@popperjs/core'
import 'bootstrap'
import {Popover} from 'bootstrap'

const powered = new Popover(document.querySelector('#label-powered'), {
        html: true,
        trigger: 'hover',
        container: 'body',
        title: 'test',
        content: 'test',
        placement: 'top'
})
```

No error in console, no content created on HTML when I hover

**Comment by juanbautista0** [comment]
I also have a related problem, my Bootstrap V5 tabs are not working.

**Comment by juanbautista0** [comment]
I had to uninstall the **beta** version and reinstall the alpha version "^5.0.0-alpha1".

**Comment by GeoSot** [comment]
@navalex  @juanbautista0 

Is it fixed right now?

**Comment by mdo** [comment]
Closing as stale.
