### ISSUE TITLE
Bootstrap Error In Mailerlite

### ISSUE THREAD

**Issue by KredaMcCullough** [twbs/bootstrap#32900]
Hi...I was having issues with mailerlite.  When I went to inspect the Java Console, everything that came up was an error. They tried to assist me, but they could not and told me to contact you guys.  Here's the error that I'm receiving
"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" please help.  Thank you!

**Comment by ffoodd** [comment]
This is a URL, not an error. What kind of error do you have?

BTW BootstrapCDN is not recommended anymore, you may try to use JsDelivr instead: `https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css` for the said file.

**Comment by KredaMcCullough** [comment]
I know it's a URL, however, this is what I was told to send to you from Mailerlite. Here's a screenshot of the Java Console.
![image](https://user-images.githubusercontent.com/26209896/105889019-ef6f1880-5fca-11eb-9df4-80aba781d4d2.png)
![image](https://user-images.githubusercontent.com/26209896/105889024-f1d17280-5fca-11eb-958a-e2b42a09313c.png)

![Screenshot 2021-01-26 113827](https://user-images.githubusercontent.com/26209896/105889135-12013180-5fcb-11eb-91ab-624da331f990.png)

**Comment by KredaMcCullough** [comment]
didn't mean to post it three times...

**Comment by mdo** [comment]
Could be that Stackpath just is no more basically? Try moving your CDN links to jsDelivr instead—BootstrapCDN is essentially no more.

Beyond that, we can't help debug further without a live demo reproducing the problem.

**Comment by KredaMcCullough** [comment]
How do I move my CDN links?
ᐧ

**Comment by KredaMcCullough** [comment]
I'm just trying to use my email marketing system without issues.
ᐧ

**Comment by ffoodd** [comment]
@KredaMcCullough You may simply change the URL you have with the one I gave: `https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css`

This should work fine.
