### ISSUE TITLE
Old Website Removal

### ISSUE THREAD

**Issue by ElainaSpiekermann** [twbs/bootstrap#32905]
I am a part of an organization called the Zell Lurie Commercialization Fund through the University of Michigan. Several years ago, members of our team developed an unofficial website for our organization's page that we would like to permanently remove (all student org websites must be hosted through the University of Michigan). The site appears to be developed through Bootstrap  and we were hoping that you would be able to permanently remove the website since we no longer have the password

Website: http://www.zlcfund.com/node/

Thank you!
Elaina

**Comment by xdvarpunen** [comment]
@ElainaSpiekermann Bootstrap is not site hosting service. You need to ask the members of your team what is the site hosting service in use and continue from there.

**Comment by mdo** [comment]
Yup, see last comment.
