### ISSUE TITLE
Carousel  data-bs-interval='false'

### ISSUE THREAD

**Issue by pww41900** [twbs/bootstrap#32916]
I have three carousels per page.
I can't make 1 immobilized carousel without changing slides. 

`<div class='carousel-item active' data-bs-interval='false'>`  this line does not work.

I made a delay of 25 seconds.  This is the way the carousel works.
```
<div class='carousel-item active' data-bs-interval='25000'>
    <img src='...' .jpg' class='d-block w-100' alt='...'>
 </div>
```

I believe in your help to me.

**Comment by mznet** [comment]
@pww41900  To stop automatic cycle, you should add data-bs-interval="false" in carousel element, not carousel-item element.

https://jsfiddle.net/mznet/qyt1ghz4/

**Comment by pww41900** [comment]
mznet  OK.

**Comment by axelkennedal** [comment]
This does not work. If I make my carousel like this:
`<div class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">` it autoplays as when the interval is set to zero (very fast, no delay).

**Comment by GeoSot** [comment]
@axelkennedal please open a new issue, adding a testcase

**Comment by axelkennedal** [comment]
I solved it with the pause method and don't really have time to make a testcase. Glhf.

**Comment by w461** [comment]
same issue here
`<div id="albumCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">`

rotates like crazy using bootstrap@5.3.2
