### ISSUE TITLE
Bootstrap 5 carousel not responsive and responsive example missing in documentation

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap#32929]
Hi,

In Bootstrap 4 all the examples in the docs have a fluid design meaning ready for the use of responsive images with art direction.

The Bootstrap 5 docs/examples about the carousel only show sliders with a fixed height. No explanation about making the carousel responsive. Don't understand why they are not responsive adaptive in the first place.

 Now when you use different art directions and sizes for images the carousel caption, indicators and arrows don't center vertical and horizontal with the design/image. 

Hope this is changed soon because this reminds me of sliders from 15 years ago!

Warm Regards,

David

**Comment by harshpandey002** [comment]
Hey, I wanna work on this issue.
I'm new to open source so this can be my first contribution.
Can I start working ?

**Comment by Allmedialab** [comment]
Hi harshpandey002,
Hope you understand the issue! Now when you want to use the Bootstrap 5 slider with text overlay and you use different sizes images in `picture` and `srcset` for example 3 sizes 4:1 for desktop, laptop and tablets and 3 sizes 4:3 for mobile phone portrait you have to use heavy media queries to keep the carousel caption, indicators and arrows in the propper place. When you have modern sliders like https://flickity.metafizzy.co/ they work out of the box. And the overlay text, indicators etc. etc. adjust automatically when the image size is changed. What I think we need is a simple CSS JavaScript solution so the Bootstrap 5 carousel works out of the box.  Instead of letting everybody invent the wheel! Don't know if the Bootstrap staff is open for this modification?
Regards,
David

**Comment by ffoodd** [comment]
Hi @Allmedialab, would you mind providing a test case to demonstrate what's wrong?

> Now when you use different art directions and sizes for images the carousel caption, indicators and arrows don't center vertical and horizontal with the design/image.

This makes me think our `position` utilities could be a solution—and we may provide a dedicated example— but I need to be sure I fully understand your goal.

**Comment by Allmedialab** [comment]
Sure @ffoodd,

Thanks for your reply!
https://yourweblab.nl/interactions-2/

This is a example of a Bootstrap 4 carousel I made with `<picture>`  `<srcset>` and the animation comes from Greensock animations. I used images from 1400px -  5k pixel-ratio 4:1 wide images and 600px - 1200px pixel ratio 4:3 portrait images The best way to see it working is to open the Chrome dev responsive app and switch devices.

This is the most common way to use responsive images in a slider that adapt to any device .

Now when I try the same with Bootstrap 5, the carousel caption, indicators and arrows don't get adapted to the image size and go even out of the image field due to the design of the slider when different image sizes are used. Of course I tried the align and other Bootstrap 5 classes, but it didn't work out. My question is: Please show how it can be done with the Bootstrap 5 classes or build the slider in a way that the height is always adaptive (auto height) and the image responsive without having to add anything.

Hope this makes sense!

Warm Regards,

David

**Comment by counterpointideological** [comment]
https://csser.space/questions/how-to-align-image-in-the-middle-using-bootstrap-4 Here’s the response to consider
