### ISSUE TITLE
how to use default font in v5.0 like v4

### ISSUE THREAD

**Issue by lignanosabbiadoro** [twbs/bootstrap#32921]
Hello, 
today i get migration from v4 to 5, i had problems with new default font.
the font of version 4 it's more clear of v5 and i prefer it, how i can get old font?
if i go on chrome developer, then in tag body style:  **font-family: var(--bs-font-sans-serif);**

**the VAR are:** system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";

if delete **system-ui** i get the right old font.

how i can modify by css for delete **system-ui** or get old font?

**Comment by mdo** [comment]
You can override the `--bs-font-sans-serif` variable, or set your own custom styles on the `body` element.

**Comment by lignanosabbiadoro** [comment]
ok, thank you

**Comment by vhs-dev** [comment]
Keep in mind there might be a thoughtful reason not to remove `system-ui`:

![bootstrap-4](https://user-images.githubusercontent.com/97140109/148226904-cd350beb-7ab0-4b75-ba49-750926208a8a.png)
