### ISSUE TITLE
Footer in Bootstrap 5.0.0 Beta

### ISSUE THREAD

**Issue by kevinmahrous** [twbs/bootstrap#32920]
Hi ..
I have been updated my site from Bootstrap 2.2.2 to 5.0.0 Beta 
Everything works okay .. but in documantion their is no Footer code 
I need to make footer what is code , 
and please add in Documantion
Thanks

**Comment by mdo** [comment]
We’ve never had a footer component—you can easily make your own with utilities and more though.
