### ISSUE TITLE
bootstrap web fonticons not working properly

### ISSUE THREAD

**Issue by armanab** [twbs/bootstrap#32928]
I have problem bootstrap 4 or 5 some svg web font icons not working

for example : 
```
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
```

**Comment by XhmikosR** [comment]
Probably wrong repo, you should report such issues upstream in bootstrap-icons.

**Comment by armanab** [comment]
> Probably wrong repo, you should report such issues upstream in bootstrap-icons.

Yes, you are right and I did the same
