### ISSUE TITLE
v5 - Tooltip customClass doesn't appear

### ISSUE THREAD

**Issue by Callixor** [twbs/bootstrap#32935]
When I use `customClass` as `data-bs-customClass` it doesn't appear anywhere - see fiddle.
Link to [fiddle](https://jsfiddle.net/jeqogdzk/2/)

I'm using it on Windows, with latest Firefox (85.0) and Bootstrap Bundle JS (Latest v5.0.0-beta1) with jQuery 3.5.1

**Comment by Callixor** [comment]
When I'm using it with jquery like this:

`$('[data-bs-toggle="tooltip"]').tooltip({ customClass: 'class-1' });`

it works!

I noticed when I use it as a data attribute that the `data-bs-customClass` outputs in lower case! See example.

Example:
`<a href="#" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-customClass="class-1" title="Test">Test</a>`

Outputs:
`<a href="#" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-customclass="class-1" title="" data-bs-original-title="Test">Test</a>`

Maybe that's the fault?

**Comment by mznet** [comment]
@Callixor Being Converted from uppercase to lowercase is correct behavior. According to [HTML spec](https://html.spec.whatwg.org/multipage/dom.html#dom-dataset), characters behind `data-` should not include any ASCII upper alphas.

**Comment by Callixor** [comment]
@mznet Ok. So something else is broken or missing.

**Comment by XhmikosR** [comment]
Yeah, the right attribute it's `data-bs-customclass`.

/CC @rohit2sharma95 if you think it should be reopened.

**Comment by rohit2sharma95** [comment]
> Yeah, the right attribute it's `data-bs-customclass`.

But `data-bs-customclass` does not work either. It should be `customClass` in javaScript and `data-bs-custom-class` in HTML. Needs to be consistent.

@Callixor You can use `data-bs-custom-class="class-1"` until it is not fixed :slightly_smiling_face:

**Comment by Callixor** [comment]
@rohit2sharma95 Okay, thanks for the feedback.

**Comment by rohit2sharma95** [comment]
But the right way is to change the case type of the option name when using via data-attributes (From `customClass` to `custom-class`)
