### ISSUE TITLE
Dropdown position is not correct in RTL

### ISSUE THREAD

**Issue by netsmertia** [twbs/bootstrap#32931]
Dropdown position in RTL is not correct. The calculation for x-transformation seems incorrect. 
https://codepen.io/netsmertia/pen/zYoYPYX

**Comment by ffoodd** [comment]
Did you check in LTR? We have plenty of bugs regarding dropdowns.

**Comment by ffoodd** [comment]
@netsmertia Bootstrap doesn't support bidi layout. 

Using RTL requires another CSS file. We should make this clearer in our docs, I guess: [docs for beta2 explains how to wrap outputs to allow using the two files at the same time](https://main--twbs-bootstrap.netlify.app/docs/5.0/getting-started/rtl/#ltr-and-rtl-at-the-same-time) but I think we can make it more obvious by mentionning it in our "Approach" section.

I added this to #32330 (RTL remaining tasks, mostly docs).
