### ISSUE TITLE
Accordion gets center aligned when text is too long 

### ISSUE THREAD

**Issue by rexarvind** [twbs/bootstrap#32938]
Accordion header gets center aligned when too long, see this codepen link.

check live: https://codepen.io/rexwebmedia/pen/eYBYLaW

![Screenshot_2021-01-30-08-57-19-648](https://user-images.githubusercontent.com/63487995/106345973-96102d80-62d9-11eb-9c8a-ddfd81a9f30c.jpeg)

**Comment by devhoussam** [comment]
nice example **rexarvind** this is a good idea I hope the bootstrap team apply that in next version...

**Comment by rexarvind** [comment]
This is a **bug report**, not a feature request.
Accordion header should not change alignment on its own.

**Comment by ffoodd** [comment]
Good catch, thanks @rexarvind!

It's inheriting `text-align` from browser's default styles.
