### ISSUE TITLE
[BUG] CARDS 

### ISSUE THREAD

**Issue by sauravkr818** [twbs/bootstrap#32932]
**BOOTSTRAP 5**
**Under the section HORIZONTAL in CARDS**

Changes Suggested 
- add class `card-img` in the `<img>` tag to make the image fit into the column `col-md-4` (there).

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
