### ISSUE TITLE
Collapse on page with thousands of collapsable divs kills the browser

### ISSUE THREAD

**Issue by liord2c** [twbs/bootstrap#32934]
I have a page with thousands of cards that contain some collapsable elements. collapse.js is looping through all of them to collapse a single item. Here's a link to a [video displaying the issue](https://drive.google.com/file/d/1H9xqfjJPqei06w9f7V5Z88p5Vo0RJJlR/view?usp=sharing)

Sorry for the potato quality but in essence I put a break point and show that the collapse call is on a single element. I then put a break point in collapse.js and show that in the constructor it's looping through ~4500 elements and during that loop the browser is just locked up and unusable. Even after that loop is done the browser is sluggish as hell. 

Let me know if you need anything else to debug

**Comment by XhmikosR** [comment]
Without a CodePen or a demo it's hard to know, but my guess is the same thing as #30976

**Comment by liord2c** [comment]
I think it's most likely related, I tried creating a codepen for you but to really see the issue you need a lot of divs and codepen limits it to 1Mb. The obvious issue is my page is overly complex and I'll fix that but in the collapse.js constructor there is a loop through the entire DOM for no reason. That is probably the reason for bug 30976. 

In case you want to actually see the issue, here's a [link](https://drive.google.com/file/d/1E_MXmZl79Nr_vTU3VtNths7dcp5B_lrD/view?usp=sharing) to a 7.5MB HTML page that you can run that will show the issue

**Comment by XhmikosR** [comment]
I don't think it's due to the constructor loop, or at least the issue I
referenced is not about that.

Feel free to submit a PR, if you pinpoint the root cause.

**Comment by XhmikosR** [comment]
@liord2c can you try with jQuery 3.5.1, Bootstrap 4.6.0 and use our bundle file instead of the separate ones?

Please try to fix any HTML validation and parsing errors. They shouldn't affect the performance, but at this point I'm not sure if it helps.

The attached HTML file behaves faster for me, tested with the latest Firefox and Edge Chromium.

[test.collapse2.zip](https://github.com/twbs/bootstrap/files/5904882/test.collapse2.zip)

Regardless, if you pinpoint the root cause, please make a PR.

PS. Apart from the above and the traditional techniques of CSS, JS and HTML minification, you might want to experiment with https://web.dev/content-visibility/.

**Comment by liord2c** [comment]
@XhmikosR will try and take a look at it this afternoon. I will also try and find time to do a PR, collapse.js constructor does way too much and should be reduced. Although I'm pretty sure it's not the issue, it's definitely related to the complexity of the HTML. Chrome starts dying with over 40K divs on a page. I will also try the content visibility as what I'm seeing is chrome drawing non-visible divs non-stop.

**Comment by XhmikosR** [comment]
Let me know how it goes. What I mentioned did help, but still Chromium suffers.

Might also be worth checking v5 with the demo page to see if things are better.

**Comment by liord2c** [comment]
Ok definitely faster but still dies once I get around 25K divs. Also even at 10K divs I see serious lag on the collapse, it's the browser that is struggling to draw. I need to test with content-visibility as if browser skips drawing non-visible divs it will be super fast.

**Comment by mdo** [comment]
I don't think this is a particularly common use case, but if there's something to document in say our Optimize docs at https://getbootstrap.com/docs/5.1/customize/optimize/, I'd love to see a PR. Otherwise, not sure what else we plan to do here, so closing as stale.
