### ISSUE TITLE
Document HTML sanitization in tooltip

### ISSUE THREAD

**Issue by terrymorse58** [twbs/bootstrap#32933]
A review of tooltip.js reveals that it sanitizes any HTML in the title attribute, allowing only the tags and attributes in a whitelist defined in sanitizer.js.

Please consider mentioning this in the docs. It may save someone else several hours of debugging when their HTML isn't showing up in a tooltip.

**Comment by XhmikosR** [comment]
We already have this documented https://getbootstrap.com/docs/5.0/components/tooltips/#options

**Comment by XhmikosR** [comment]
Actually, perhaps we should have a callout too.

**Comment by terrymorse58** [comment]
Yes, please add a callout to alert the user that tootip custom HTML is sanitized, and what that means. The only hint of this on the tooltips page is the word "sanitize" in the options, with no explanation of its impact.

**Comment by XhmikosR** [comment]
It's already documented in https://getbootstrap.com/docs/5.0/getting-started/javascript/#sanitizer but I guess linking to that section from each component probably makes sense.

**Comment by PRO-BROS** [comment]
HI!

Can anyone suggest me improvement in my website [See Here](https://prhocoding.com/)

**Comment by patrickhlauke** [comment]
popover https://getbootstrap.com/docs/5.3/components/popovers/ and tooltip https://getbootstrap.com/docs/5.3/components/tooltips/ documentation now includes an info callout

> By default, this component uses the built-in content sanitizer, which strips out any HTML elements that are not explicitly allowed. See the [sanitizer section in our JavaScript documentation](https://getbootstrap.com/docs/5.3/getting-started/javascript/#sanitizer) for more details.

I believe this addresses this issue.
