### ISSUE TITLE
table-response clips dropdown-button menu

### ISSUE THREAD

**Issue by aimeos** [twbs/bootstrap#32947]
Browser: Chrome 87
OS: Ubuntu

If a dropdown button is part of a table inside a container with table-reponsive, the dropdown menu isn't shown (only by scrolling down):

https://codepen.io/aimeos/pen/vYyEeOv

**Comment by mznet** [comment]
@aimeos `table-responsive` class has `overflow-x` property, which specifies whether to clip the content, add a horizontal scroll bar. The dropdown menu is located at the outer space of `table-responsive` element, thus, `overflow-x` property make the menu invisible. 

If the height of `table-responsive` element is enough tall , the dropdown menu will be shown. 

https://jsfiddle.net/mznet/Lcjo2wpf/6/

**Comment by aimeos** [comment]
@mznet Sure, but what if the table contains not enough or no content? Is there a solution for that case?

**Comment by mznet** [comment]
@aimeos `table-responsive` class is needed when the contents go beyond the right edge of table. But if the table doesn't have any contents, this class is not needed. So, why don't add table-responsive class dynamically when the table has enough contents? Or Setting min-height of table would be another solution, imho.

**Comment by aimeos** [comment]
@mznet Even if the table doesn't have enough content (e.g. only one or two rows), the table header is still beyond the right edge, so dynamically adding `table-responsive` doesn't help.
Setting the min-height of the node containing the `table-responsive` class to 100% doesn't work because the drop-down uses position:absolute

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/issues/29313#issuecomment-758412385

**Comment by aimeos** [comment]
@mdo The suggested fix in #29313 doesn't work for Bootstrap 5-beta even when using `data-bs-display="static"` instead of `data-display="static"`:
https://codepen.io/aimeos/pen/vYyEeOv

**Comment by 719media** [comment]
I have a way to do it by overriding popper strategy, example:
https://jsfiddle.net/pk3mL1af/

I don't think the "strategy" configuration is available in any of the data-bs attributes, tho, so you have to use explicit javascript I believe, which is unfortunate
