### ISSUE TITLE
dropdown-end causes horizontal scrollbar

### ISSUE THREAD

**Issue by aimeos** [twbs/bootstrap#32946]
Browser: Chrome 87
OS: Ubuntu

Dropdown menus with class "dropdown-end" for alignment to the right are place partly out of the viewport before they are moved to the left with translate(). This leads to a horzontal scrollbar:

Example: https://codepen.io/aimeos/pen/jOVELyo

**Comment by harshpandey002** [comment]
Hi @aimeos 
I'm new to open source projects.
I wanna fix this issue and make my first contribution.
Can I start working ?

**Comment by aimeos** [comment]
Sure! :-)

**Comment by harshpandey002** [comment]
Hello @aimeos,
Sir,

The class ""dropdown-menu-end" seems to work fine, cause even after removing it, same problem occurs.
Moreover, the amount of space occurring on the right of dropdown was too much in case of tables.
I tried the same with FlexBox, scrollbar is still occurring, but if you add more text to any dropdown list. scroll bar goes away.

I'm lost, please guide me 

Please Check: https://codepen.io/harshpandey002/pen/OJbyjNj?editors=1100

**Comment by 5ulo** [comment]
This bug is still present in Bootstrap 5.0.1. It definitely causes the `transform` on dropdown open event.


https://user-images.githubusercontent.com/4980919/118161290-b050c000-b41f-11eb-9f73-c09a00aa000f.mp4

**Comment by mdo** [comment]
Is this still an issue?

/cc @rohit2sharma95 as our Popper export 😅

**Comment by rohit2sharma95** [comment]
@aimeos, that's because you have a very short width of the second column IMO.
You can use the `fixed` strategy in that case to fix the behavior (Or change the layout to have enough space)

AFAICT, `dropdown-menu-end` is not the issue here, https://jsbin.com/siriyoquki/edit?html,output

**Comment by mdo** [comment]
Thinking we can close this out then. Happy to re-open if there's more we can do.
