### ISSUE TITLE
My image isn't responsive and the img-fluid class doesn't seem to work!!!

### ISSUE THREAD

**Issue by glosnick** [twbs/bootstrap#32955]
I'm sure my problem is painfully simple but I'm trying to make my image responsive in bootstrap 4.6.  I tried img-fluid as advised on the getbootstrap.com site but it doesn't work.  I do hope you can help.

My code:

<!doctype html>

	<head>

	
		<title>Test</title>
		
		<meta charset="utf-8>
		
        <meta name="viewport" content="width=device-width, initial-scale=1" />
		
		<meta http-equiv="x-ua-compatible" content="ie=edge">

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
		
		<link rel="stylesheet" type="text/css" href="restless-inc.css">
	
	</head>
	
	<body>
	
		<div class="container-fluid">
		
		<img src="images/dog3.jpg" class="img-fluid" style="max-width:100%; height:auto;" alt="...">
		
		</div>
		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
	
	</body>
	
</html>

Thanks for any help you might be able to offer.

Regards

Nick

**Comment by mdo** [comment]
There must be something else going on for you because the code works in our docs. https://getbootstrap.com/docs/4.6/content/images/

**Comment by glosnick** [comment]
If it has been closed does that mean I can't respond?

**Comment by ffoodd** [comment]
Not at all, feel free to elaborate if you need.

**Comment by glosnick** [comment]
I fear I owe you an apology.  I thought when you had closed the question I was unable to respond, I thought that a little rude. So you have my apologies.  I am new to all this and am finding my way somewhat.  I raised another question as I thought I couldn't answer this one so please bare with me, I'm sure I'll get there in the end.  I think I managed to solve my problem.  It was the max-width statement that was the problem.  When I changed it to width:100% the picture was more responsive.

Thank you for your indulgence.

Regards

Nick

**Comment by mdo** [comment]
I think the issue you might be describing—you want the image to be 100% wide at all times. Our `.img-fluid` class only ensures the image doesn't break out of the parent element on smaller devices. It doesn't enlarge an image, it prevents it from being too wide.

**Comment by glosnick** [comment]
Thanks for the response.  So is there a class that is more suitable for my needs.

Regards

Nick

**Comment by ffoodd** [comment]
@glosnick You should find what you need [in our docs ' sizing utilities page](https://getbootstrap.com/docs/5.0/utilities/sizing/), mostly `.w-100` if I understood your need.
