### ISSUE TITLE
dropdown keyboard fixes

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#32954]
BTW does it make sense to open the dropdown but not select the first/last element depending on the arrow key?

I feel like it's an extra key. But that's for later too. :)

_Originally posted by @XhmikosR in https://github.com/twbs/bootstrap/pull/32750#issuecomment-770921055_

**Comment by XhmikosR** [comment]
I guess for v5 that's OK to do, for v4 not sure if it's a considered a breaking change. But the current situation does not make a lot of sense to me.

**Comment by sijusamson** [comment]
I would be working on this :-)

**Comment by XhmikosR** [comment]
Thanks! See if you can deduplicate the code to get rid of the linting warning too :)

**Comment by sijusamson** [comment]
@XhmikosR I was able to fix the issue, but I couldn't find any alternate solution to remove the linting warning.
