### ISSUE TITLE
Problem in dropdown menu [RTL version]

### ISSUE THREAD

**Issue by mahmoodi2016** [twbs/bootstrap#32969]
Hello
Right now I'm using the latest version of RTL.
I tried to create Buttons with dropdowns based on [the guide](https://getbootstrap.com/docs/5.0/forms/input-group/#buttons-with-dropdowns). Unfortunately it doesn't work in RTL version, actually dropdown menu is not being shown. 
I think the problem is in the CSS file [bootstrap.rtl.css] because there is no such problem in the LTR version of bootstrap.

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by ffoodd** [comment]
There're several bugs related to dropdowns right now, but they work the same in RYl than in LTR, as you may see in [our current RTL cheatsheet](https://main--twbs-bootstrap.netlify.app/docs/5.0/examples/cheatsheet-rtl/#dropdowns).

Please elaborate and provide a test case.

**Comment by mahmoodi2016** [comment]
Thanks for you attention.
[Here](https://codepen.io/mahmoodi2016/pen/JjbdaVN) you can see my sample code with RTL [bootstrap.rtl.css]. It doesn't work.
[Here](https://codepen.io/mahmoodi2016/pen/jOVPvQo) I just replaced LTR CSS file [bootstrap.css] without any other change and it Works!

**Comment by ffoodd** [comment]
Thanks for the test case, it helped a lot! FYI this has been fixed on `main`  in #32415 — so you only need to wait for beta2. :)
