### ISSUE TITLE
Bootstrap 5.0.0-beta1: Modals with static backdrop static dismissable when created using modal.show()

### ISSUE THREAD

**Issue by Steve-3d** [twbs/bootstrap#32970]
I try to create a Modal Dialog with a static backdrop. The Dialog should not be dismissed when the backdrop is
clicked. But every time I open the Dialog using show() it is dismissable by clicking the backdrop.

The only way this works is when the Modal is created using data-bs-toggle='modal' on the button (as it is in the
Documentation).

I created a JSFiddle to show this: https://jsfiddle.net/triple5even/y69xeh5t/12/

This Bug was tested an confirmed on Linux Mint 20, 64Bit using 
- Chromium 88.0.4324.96 Official Build
- Opera 73.0.3856.344
- Firefox 85.0

**Comment by kyletsang** [comment]
When you create the modal, the options should be passed as the second parameter in the constructor, not the `show` func.

Try with this:
`new bootstrap.Modal(document.getElementById('modal1'), {backdrop: 'static'}).show()`

**Comment by Steve-3d** [comment]
You are right! Omg I don't know how I managed to overlook this. Tried for hours and could not find the reason why it wasn't working and was so sure this was a bug. This is embarrassing :)
Thank you!
