### ISSUE TITLE
doc: typo in dropdown options

### ISSUE THREAD

**Issue by Chaostheorie** [twbs/bootstrap#32977]
In the docs for boostrap 5 (5.0 - See link below) the description of a javascript description is contradicting the defaullt on the left. Not too sure which is more accurate as the handling of defaults may vary between popper and bootstrap in e.g. navbar. 

Specific Section: [Dropdowns #Options](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/components/dropdowns.md#options)

Specific conflicting option: boundary
default: 'scrollParent'
description: Overflow constraint boundary of the dropdown menu. By default it's *'clippingParents'* and can accept an HTMLElement reference (JavaScript only).

**Comment by mdo** [comment]
@twbs/js-review Which is the correct default? :)

**Comment by kyletsang** [comment]
This looks like a remnant from Popper v1.

Popper v2's `boundary` only accepts `clippingParents` or HTMLElement.

Ref: https://popper.js.org/docs/v2/utils/detect-overflow/#boundary

I'll open a PR for this.
