### ISSUE TITLE
Missing a coma in example code

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#32975]
The code for https://getbootstrap.com/docs/5.0/utilities/api/#add-utilities is missing a coma here:

![Screen Shot 2021-02-02 at 6 58 11 PM](https://user-images.githubusercontent.com/2222751/106678417-ac8fe080-6588-11eb-8fae-cf324aa6352a.png)

**Comment by XhmikosR** [comment]
It's already fixed in main. #32543
