### ISSUE TITLE
Media Object Missing

### ISSUE THREAD

**Issue by mohanrc13** [twbs/bootstrap#32980]
Hi, 
Why did you remove the **Media Object** in 5.0. That's important component . We used that media object many places in our theme. Why don't you add media object again?.

**Comment by ffoodd** [comment]
Duplicates #32142. Please read our issue template carefully before opening an issue.

Also take a look at [the migration guide](https://getbootstrap.com/docs/5.0/migration/#grid-and-layout) — which would have led you to #28265 (in which you might see utilities to use).
