### ISSUE TITLE
dropdown.dispose() does not remove event listeners

### ISSUE THREAD

**Issue by jirikanda** [twbs/bootstrap#32983]
Dropdown has a dispose() function which contains:
```
super.dispose()
EventHandler.off(this._element, EVENT_KEY)
...
```

Unfortunatelly, in the base class BaseComponent there is the dispose() function which contains

```
Data.removeData(this._element, this.constructor.DATA_KEY)
this._element = null
```

When dropdown dispose() function is called
1. this._element is set to null in the super.dispose()
2. EventHandler.off function(...) cannot remove event listener because the this._element is null.

**Comment by hakenr** [comment]
...and in `EventHandler.off(this._element, EVENT_KEY)`, the `EVENT_KEY` is weird: `.bs.carousel`

**Comment by XhmikosR** [comment]
Can someone submit a PR please? Thanks!
