### ISSUE TITLE
Bootstrap 5 requires offcanvas

### ISSUE THREAD

**Issue by thor456** [twbs/bootstrap#33001]
Bootstrap 5 requires offcanvas sidebar like Zurb's Foundation.

**Comment by mdo** [comment]
There are issues and PRs for this.

**Comment by thor456** [comment]
LOL : Mark Auto (Original Author). 

Bro, I am, not a single person, but a community of peoples, who need flexible and robust sidebar, auto-hide in mobile screen. 

Uses: 

1. (top use) Admin and Dashboard themes
2. General use

**Comment by kukac7** [comment]
@thor456 i will use the search... https://github.com/twbs/bootstrap/pull/29017
