### ISSUE TITLE
Collapse on navbar broken 

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#33021]
@ffoodd
Collapse on navbar broken since https://github.com/twbs/bootstrap/pull/32899

here a example
https://jsfiddle.net/jonnysp/zwgbotmq/

**Comment by ffoodd** [comment]
Thanks, I confirm the behaviour. The best fix as far as I can tell is introducing `flex-basis: 100%` but only when navbar is **not** expanded, otherwise we'd run into #32383 again (which was the initial bug #32899 was fixing).
