### ISSUE TITLE
Large floating select cuts off text

### ISSUE THREAD

**Issue by abibell** [twbs/bootstrap#33033]
**Large floating select** cuts off the bottom part of the text
- Doesn't seem to occur if the select is not large
- Windows & Chrome latest
- See [JS Bin](https://jsbin.com/jeyukohefu/1/edit?html,output)
- v5.0.0-beta1

![image](https://user-images.githubusercontent.com/544653/107450077-bae98800-6b98-11eb-83ab-e1573af49fc3.png)

**Comment by XhmikosR** [comment]
It seems fixed on main, tested with `https://twbs-bootstrap.netlify.app/docs/5.0/dist/css/bootstrap.min.css`

**Comment by XhmikosR** [comment]
Oops NVM, I mixed the browsers while testing. I can reproduce with Edge Chromium on  Windows

**Comment by vincentcaitech** [comment]
Hi, I'm currently working on this issue. I was able to reproduce it.

**Comment by alecpl** [comment]
Duplicate of #32672 ?

**Comment by ffoodd** [comment]
@alecpl is right, closing this as duplicate. Feel free to comment again in the initial issue.

**Comment by jaxramus** [comment]
yeah this is still happening even on the latest version: https://stackblitz.com/edit/hxnclf?file=index.html
