### ISSUE TITLE
E-mail Validation Does Not Detect Missing TLD

### ISSUE THREAD

**Issue by avestella** [twbs/bootstrap#33034]
The bootstrap default form validator for input of type="email" returns valid for e-mail addresses without a TLD on them. E.g. "test@testcom" returns valid.

**Comment by XhmikosR** [comment]
That's not the bootstrap validator, that's your browser's validation.

**Comment by avestella** [comment]
Hi there.

Thank you for your feedback. I was pretty sure I disabled the default form validation using the novalidate attribute on the form, and because I was following the documentation here: https://getbootstrap.com/docs/5.0/forms/validation/ 

However, I'm sure I am wrong. Is it because bootstrap does not do e-mail validation and although the rest of the form is being validated, it defaults to the browser for that input type?

**Comment by XhmikosR** [comment]
Yeah, we don't offer any validation in core so what you see it's the browser.
