### ISSUE TITLE
SCSS compiling error - Invalid CSS after

### ISSUE THREAD

**Issue by codepaints** [twbs/bootstrap#33046]
Bug reports must include:

### Operating system and version (Windows, macOS, Android, iOS)
macOS Big Sur - Version 11.2.1

### Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
The issue is not browser-specific

### A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

I have installed `bootstrap` using node. `npm i bootstrap@next` and imported `bootstrap.scss` into my custom stylesheet to customize. `styles.scss` 

When I try to compile it gives the following kind of errors

`error scss/styles.scss (Line 9 of node_modules/bootstrap/scss/mixins/_table-variants.scss: Invalid CSS after "... #{$background}": expected "{", was ";")`

I have also posted a question on the StackOverflow 
https://stackoverflow.com/questions/66148648/bootstrap-5-beta-scss-compiling-error-invalid-css

**Comment by ffoodd** [comment]
What Sass compiler do you use?

Our CI checks both sass (dart-sass) and node-sass and, obviously, successfully compiles.

**Comment by thor456** [comment]
Put Any screenshot, did you search in other forums, 

This question/complain contain little information about your problem.

**Comment by storywriter** [comment]
I had the similar trouble with doing `npm run css-compile`.

![image](https://user-images.githubusercontent.com/4524652/109178616-623b0180-77cc-11eb-872a-3363bf8f5feb.png)

and I delete `bootstrap-5.0.0-beta2` directory, then unzip `bootstrap-5.0.0-beta2.zip` again, try `npm run css-compile`. I solved the problem... 
I can't find different between the source files...

**Comment by mdo** [comment]
Closing due to lack of information.

**Comment by seballot** [comment]
I had the same issue, you just need to update your sass compiler

**Comment by akuma6099** [comment]
Just wanted to confirm it is a sass/scss compiler issue. I had "Sass 3.4.23 (Selective Steve)" from "apt-get install ruby-sass". Had to remove it and grab the latest Dart Sass 1.32.11 @ https://github.com/sass/dart-sass/releases/tag/1.32.11

Problem solved.

**Comment by loopy3025** [comment]
I'm getting this error with 
 - node-sass 7.0.1
 - grunt 1.5.2
 - grunt-sass 3.1.0
 
Which are all fairly recent.

Am I missing a dependency?

```
Running "sass:dist" (sass) task
Fatal error: Error: Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"
        on line 369 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
        from line 8 of node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss
        from line 2 of scss/style.scss
>> vbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !defa
   ------------------------------------------^
```

**Comment by milan322** [comment]
> I'm getting this error with
> 
> * node-sass 7.0.1
> * grunt 1.5.2
> * grunt-sass 3.1.0
> 
> Which are all fairly recent.
> 
> Am I missing a dependency?
> 
> ```
> Running "sass:dist" (sass) task
> Fatal error: Error: Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"
>         on line 369 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
>         from line 8 of node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss
>         from line 2 of scss/style.scss
> >> vbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !defa
>    ------------------------------------------^
> ```
> 
> I've also attempted switching from node-sass to dart-sass and I get the same error, just formatted nicer.
> 
> ```
> 
> Fatal error: Error: Undefined function.
>     ╷
> 369 │ $navbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !default;
>     │                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ╵
>   node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss 369:42  @import
>   node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss 8:9               @import
>   scss/style.scss 2:9                                                              root stylesheet
> ```
> 
> However, that is with dart-sass 1.25.0. npm doesn't think that 1.32.11 exists.
> 
> Rolling back to bootstrap-sass 3.3.7 solves it for now.

Thanks a lot. This solved my problem. I have been struggling to fix this. Thanks

**Comment by brokerstir** [comment]
> Just wanted to confirm it is a sass/scss compiler issue. I had "Sass 3.4.23 (Selective Steve)" from "apt-get install ruby-sass". Had to remove it and grab the latest Dart Sass 1.32.11 @ https://github.com/sass/dart-sass/releases/tag/1.32.11
> 
> Problem solved.

How did you remove Selective Steve? When I run `gem uninstall sass` it prompts me with:
```
You have requested to uninstall the gem:
	sass-3.4.25
foundation-rails-5.5.3.2 depends on sass (>= 3.3.0, < 3.5)
sass-rails-5.0.6 depends on sass (~> 3.1)
If you remove this gem, these dependencies will not be met.
```
I want to remove it and try Dart Sass but am concerned by this prompt.

**Comment by brokerstir** [comment]
> > Just wanted to confirm it is a sass/scss compiler issue. I had "Sass 3.4.23 (Selective Steve)" from "apt-get install ruby-sass". Had to remove it and grab the latest Dart Sass 1.32.11 @ https://github.com/sass/dart-sass/releases/tag/1.32.11
> > Problem solved.
> 
> I have a similar issue. My error says `Error: Invalid CSS after "...ame}: #{$value}": expected "{", was ";"` when I try to compile.
> 
> How did you remove Selective Steve? When I run `gem uninstall sass` it prompts me with:
> 
> ```
> You have requested to uninstall the gem:
> 	sass-3.4.25
> foundation-rails-5.5.3.2 depends on sass (>= 3.3.0, < 3.5)
> sass-rails-5.0.6 depends on sass (~> 3.1)
> If you remove this gem, these dependencies will not be met.
> ```
> 
> I want to remove it and try Dart Sass but am concerned by this prompt.

I proceeded to remove it. Despite the prompt, I have not had issues.
