### ISSUE TITLE
Adjust Breakpoints Threshold For Medium?

### ISSUE THREAD

**Issue by herbertmilhomme** [twbs/bootstrap#33047]
It's always bothered me for years, but never considered the thought of directly requesting for change from source until now. My monitor resolution is 1920x1080; on a Windows OS (7 and higher) you can snap browsers and application windows to fit screen display. When monitor and resolution are at that size, it's [visually] comfortable to stack two browser windows side-by-side, dividing screen size in half, and each fill up both halves. (The browser is not too big, and not too small, the contents can fit well within dimensions without feeling cluttered or crammed, and great for multi-tasking). 

My problem and reasoning is the following: 

- All website running bootstrap that are snapped to half screen at that resolution, take on the appearance of a tablet or mobile layout. 
  - Burger Stack Navigation UI 
  - Menus hidden behind left or top collapse (burger stack)
  - Oversized UI (feels like websites are zoomed-in by default)
  - Grids only display a column of 1 (instead of 3+)
  - Unutilized and super exaggerated side margins (because the screen is big, and columns are small)
- Every website i visit, i have to drop zoom between 90% and 75% because designers use "small" (sometimes "medium") for mobile layouts. 
  - Sometimes that's a difficult balance, between mobile UI on desktop, and font text too small to read.
  
...I had some more issues to present, but i lost track of what they were while typing. Might re-edit if there's still a need to continue on...

![image](https://user-images.githubusercontent.com/15901670/107629549-47935500-6c30-11eb-9226-39b35b833b76.png)

My proposed solution:

- Change the threshold numbers from ~970 to maybe ~940 (if i zoom-out, 941 goes to 1045 @ 90%)

![image](https://user-images.githubusercontent.com/15901670/107630305-4f072e00-6c31-11eb-866b-6d21434daa91.png)

![image](https://user-images.githubusercontent.com/15901670/107629829-ac4eaf80-6c30-11eb-87f5-20d279a0eaf4.png)

**Comment by mdo** [comment]
Your screenshots are showing Bootstrap 3.x, which hasn't been maintained for several years now. No changes will be happening to that codebase anytime soon. Separately, we have iterated on our breakpoints in v4 and v5, but they likely don't meet your needs. We don't have any plans to change those either though :).

**Comment by herbertmilhomme** [comment]
the url isnt important... the point of the image was the breakpoint for medium sized breakpoints... i just screenshot whatever page google directed me to when i looked up the css chart. My argument was that **_EVERY_** site that uses bootstrap has the **_SAME_** problem.

**Comment by herbertmilhomme** [comment]
the problem isnt resolved, and still persist across ALL versions.

I feel like i wasted time and energy typing if all you did was look at image and go "ah, the url is the problem, you're using outdated tech"

![image](https://user-images.githubusercontent.com/15901670/107704182-d8971a00-6c8a-11eb-949a-a568ab5b7481.png)

![image](https://user-images.githubusercontent.com/15901670/107704283-ff555080-6c8a-11eb-8f5f-358c64e61349.png)

**Comment by herbertmilhomme** [comment]
940 pixels is a fairly large screen size, and close to standard monitor sizes. if user buys a 1080 or 10xx monitor, whether their window is fully expanded or not, should still yield similar results...

![image](https://user-images.githubusercontent.com/15901670/107704661-a3d79280-6c8b-11eb-993e-b99f4f9d2484.png)

**Comment by ffoodd** [comment]
The answer explained clearly that we won't change v4 nor v5.

What you're asking for would lead to thousands of users pointing regressions everywhere, and be considered as a massive breaking change.

Moreover, websites using Bootstrap are totally able to change their behaviour since any responsive component we provide can target any breakpoint we provide.

If this become a frequently asked cha'ge, we may reconsider it—but for now your usage seems very specific and kind of exotic.

**Comment by herbertmilhomme** [comment]
wouldnt the only people affected be client devices registering a different responsive layout? And, the "fix" doesnt have to be an "override" to any current versions... it can just be an "update" to future releases. I dont think it's exotic that the numbers used to standardize your breakpoints be reevaluated. Also, the division between the breaks get wider and wider as the threshold goes increases.

**Comment by mdo** [comment]
Yeah, I mean, I didn't think the point was the URLs—I was just mentioning you're referencing a super old version of Bootstrap and we're focused on v5 right now. That, and the differences between the two are discernible even at the breakpoint level. I did understand that you're asking us to re-evaluate our breakpoints, and my comment was in response to that—no plans to make any changes to the breakpoints for v4 or v5. That'd be a breaking change at this point.

Maybe we get more fine-grained in v6.

**Comment by herbertmilhomme** [comment]
Ah, that's a fair response. The problem has persisted for years, so there's no urgency or expectation to see it resolved any time soon. It's just something i noticed, and never knew there was a channel that a ticket couldve been submitted to until now. i havent reviewed too much of source, but i have used bootstrap for my own websites. Cant the solution to issue be a Ctrl+F and Replace?

**Comment by mdo** [comment]
> Cant the solution to issue be a Ctrl+F and Replace?

The issue isn't that we don't know how to make the change, we definitely do lol. The issue is that we abide by semantic versioning and reasonable expectations around breaking changes. We only introduce breaking changes in major releases, and we're too close to the next stable major release of v5 to depart from it.

You're more than welcome to change it for your own projects—the grid breakpoints are all customizable via Sass.

**Comment by herbertmilhomme** [comment]
Shouldnt this "feature" be unclosed and reopened so that it can be considered for the next major update, if that is the case it is "breaking changes" to functionality by adjusting screen resolution parameters? If the idea proposed is to be taken under consideration for next updates but isnt a "bug" that will be fixed in current releases, then it isnt a matter that has been resolved?...
