### ISSUE TITLE
form-floating label is not aligned correctly when placed in .row element

### ISSUE THREAD

**Issue by birko** [twbs/bootstrap#33040]
I wanted to create horizontal form as given in example using the grid and using the floating labes. Probably some negative margin is calculated wrongly.

OS: Windows 10:
Browser: Microsoft Edge (Chromium based -  88.0.705.63)
```
<div class="row">
    <div class="form-floating col">
        <input type="text" class="form-control text-end" value="0" />
        <label>Cena od</label>
    </div>
    <div class="form-floating col">
        <input type="text" class="form-control text-end" value="100" />
        <label>Cena do</label>
    </div>
</div>
```
this is the result:

![image](https://user-images.githubusercontent.com/1064302/107536845-868ac180-6bc2-11eb-9814-745533ff99e4.png)

**Comment by mdo** [comment]
Our docs cover this—don't mix grid classes with components. You're facing some clashing `padding` values here.
