### ISSUE TITLE
Why Did Bootstrap change replace "left" and "right" with "start" and "end".   

### ISSUE THREAD

**Issue by awbottrel** [twbs/bootstrap#33053]
This makes no sense.

**Comment by ffoodd** [comment]
Duplicates tons of previous issues.

Please read [our migration guide, especially the RTL section in beta1](https://getbootstrap.com/docs/5.0/migration/#rtl) and [the dedicated discussion](https://github.com/twbs/bootstrap/discussions/32402), which is full of explanations and resources.
