### ISSUE TITLE
Class .btn Buttons in a carousel-item

### ISSUE THREAD

**Issue by jinglebells80** [twbs/bootstrap#33052]
Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS): Windows 10
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser): Firefox

Hi!

In Bootstrap V5 if you have a button like this in order to switch to the next or previous slide

`<button class="btn btn-primary">Previous Slide</button>`

the current slide disappears before the other slide comes in. As soon as I delete the class "btn" the carousel works smoothly again. So this button (without "btn" class):

`<button class="btn-primary">Previous Slide</button>`

makes the carousel move the slides smoothly.

Cheers

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
