### ISSUE TITLE
Please explain how we replace "media"

### ISSUE THREAD

**Issue by awbottrel** [twbs/bootstrap#33054]
"media" was my favorite component from v4.  I see it's been dropped in this version.  (you guys are killing me).  

Your site points to this document for what utilities replace "media", but i don't see any answers in that document.  just a long chat discussion... 

Please provide guidance

**Comment by mdo** [comment]
This is a duplicate a few times over (give it a search). https://github.com/twbs/bootstrap/pull/28265 has a snippet down in the thread about how to replace with utilities. We should get this in the docs somewhere though as a snippet.

**Comment by awbottrel** [comment]
I see that now.  Thank you.   This question can be removed.
