### ISSUE TITLE
list-group-item cut off with margins horizontal

### ISSUE THREAD

**Issue by IslandRhythms** [twbs/bootstrap#33055]
Operating System: Windows 10
Browser: Checked Chrome and Firefox

1. create a row
2. create colums
3. create a list-group list-group-horizontal
4. in every list-group-item include a margin for left or right or both so mx-1 for example
5. see that every item after the first has a border cut off problem

Here is a picture
![capture](https://user-images.githubusercontent.com/39510674/107682031-d4103880-6c6d-11eb-9be3-8a77aadb77e9.png)

it lights up when hovering over .list-group-item and you can see that the second and third list item are missing a side.

and here is code that makes the steps more clear
```
 <div class="container-fluid">
    <div class="row">
      <div class="col-6">
        <h3 class="ml-3">Connections</h3>
        <div class="card" style="width: 75%">
          <div class="card-body">
            <h5 class="card-title">Connection 1<sup class="circle"></sup></h5>
            <h6><b>Hosts:</b> localhost:27017</h6>
            <h6><b>Database:</b> test</h6>
          </div>
        </div>
      </div>
      <div class="col-6">
        <h3 class="mx-3">Models</h3>
        <ul class="list-group list-group-horizontal">
          <li class="list-group-item mx-1">
            test.User<sup class="circle"></sup>
          </li>
          <li class="list-group-item mx-1">
            test.Role<sup class="circle"></sup>
          </li>
          <li class="list-group-item mx-1">
            test.Role<sup class="circle"></sup>
          </li>
        </ul>
      </div>
    </div>
```

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by mdo** [comment]
Don't add the margins and you won't have that problem. 😆 But seriously, the list group components are designed to be attached to one another, so to do that in our CSS, we remove one of the borders and/or overlap them (depending on the component). Closing as a won't fix.
