### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by RezaSeyyed19** [twbs/bootstrap#33062]
Hi,
Please check the responsive of this page(RTL Examples):
https://getbootstrap.com/docs/5.0/examples/blog-rtl/

Thanks.

**Comment by ffoodd** [comment]
Could you please describe what's wrong, in your opinion?

**Comment by rahulshah100** [comment]
It seems to be working fine till the width in website's aspect ratio remains above **560px** @lower width text's are being overlapped & some text are moving out of the screen.You can check this exact width dimensions after which your site is messing up using _chrome's developers tool_ .
Tho for most devices your site will load just fine but u could further optimize it's display for devices with smaller screen width using [mediaqueries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) 

Hope this solves your issue

**Comment by ffoodd** [comment]
Everything just seems fine using Firefox and Chrome on Ubuntu. Without more details I'll close this issue.

**Comment by mdo** [comment]
Closing per last comment.
