### ISSUE TITLE
V5 Checkout RTL example "email" field it still on LTR mode.

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33066]
[Checkout RTL example](https://getbootstrap.com/docs/5.0/examples/checkout-rtl/)

![Image](https://i.imgur.com/TxMY2tt.png)

[bootstrap.rtl.css](https://getbootstrap.com/docs/5.0/dist/css/bootstrap.rtl.css)

```
[type="tel"],
[type="url"],
[type="email"],
[type="number"] {
  direction: ltr;
}
```

it should be :

```
[type="tel"],
[type="url"],
[type="email"],
[type="number"] {
  direction: rtl;
}
```

**Comment by ffoodd** [comment]
This is done on purpose, following [RTL Styling recommendations](https://rtlstyling.com/posts/rtl-styling#form-inputs)—which is our main reference regarding RTL. It's been confirmed by kind people in #30980 and we got an overall agreement.

Would you have any opposite insights to share?

**Comment by MousaAlqarni** [comment]
Its okay for email and tel or url  to be the same

**Comment by Mrahmani71** [comment]
Usually, people write their emails in Latin alphabet and LTR is correct.

**Comment by ffoodd** [comment]
Closing this per last comment, then. @devhoussam Feel free to share any resources you'd have on this topic, there'll never be too much docs and refs in Bootstrap. :)
