### ISSUE TITLE
[v5] Option in select with floating label is not high enough

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#33061]
In chrome (and opera) option is not high enough and letters are cut like "p" in docs:
https://getbootstrap.com/docs/5.0/forms/floating-labels/#selects

<img width="576" alt="opera_2021-02-12_10-14-36" src="https://user-images.githubusercontent.com/420691/107749755-5b67b580-6d1b-11eb-9e39-a7137ffb632f.png">

**Comment by vincentcaitech** [comment]
I'm working on Issue #33033, which seems to be causing the same bug.

**Comment by XhmikosR** [comment]
Duplicate of #33075
