### ISSUE TITLE
Bootstrap 5 Beta 1 & 2 JS-dependent components don't work during local development?

### ISSUE THREAD

**Issue by tristanbiesecker** [twbs/bootstrap#33078]
I am experiencing some weird behavior in Bootstrap 5 Beta 1 & 2. It seems as though various components which use JS don't work properly when developing my website locally (i.e., `localhost:<dev port>`). Take the _Modal Example_ code (below). When I click on the button to trigger the modal, I get a `TypeError` in the console: `TypeError: Can only call Element.querySelector on instances of Element`. Another example is the _Navbar Example_ (below). For this one, if I click on the burger button to expand the `navbarSupportedContent` element, nothing happens (no errors either). However, **everything seems to work fine in JSFiddle**, surprisingly.

It seems as though something isn't working properly in a local development setting, which baffles me. Perhaps I'm missing something obvious, but I've been staring at this for two days with no luck. It seem as though [someone else](https://github.com/twbs/bootstrap/discussions/32773#discussion-1733711) might be having a similar issue.

**Operating System:** macOS Big Sur 11.2.1
**Browser Versions:** Safari 14.0.3, Chrome 88.0.4324.150 (No extensions/addons to worry about)

---

**Modal Example**
```html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>

<body>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>
```

---

**Navbar Example**
```html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by XhmikosR** [comment]
Works fine for me on Windows with Firefox and Edge. I can't test macOS.

@mdo can you test this please?

**Comment by ffoodd** [comment]
Wouldn't it be related your dev setup? What's your environment?

**Comment by tristanbiesecker** [comment]
> Wouldn't it be related your dev setup? What's your environment?

My current development environment for this project is [Vapor](https://vapor.codes). No modifications to it of any kind. Just spinning up a local server (which produces the code examples above) and serves it at `localhost:8080`.

**Comment by tristanbiesecker** [comment]
Here is a short screen recording of the navbar issue.
https://user-images.githubusercontent.com/12146879/107986789-c70b8600-6f9a-11eb-896b-98b35dd6d391.mov

**Comment by XhmikosR** [comment]
Yeah, that's something in your dev workflow and unrelated from what I see to Bootstrap itself.

**Comment by tristanbiesecker** [comment]
@XhmikosR but there is no "dev workflow" really. My local server is just serving the static HTML above.

**Comment by XhmikosR** [comment]
Well, it works fine when the page is opened locally with or without a server, so it's something on your system and outside of Bootstrap's scope.

**Comment by ffoodd** [comment]
@tristanbiesecker Well, our docs' dev environment is exposed through `localhost:9001` and everything's working fine.

So this is clearly unrelated to localhost.

If you're not able to provide a reduced test case or give us a better diagnostic, there's not much we can do.

**Comment by tristanbiesecker** [comment]
I _believe_ I have found the issue! It turns out that the Vapor framework doesn't like having the `#` character start the value of a `data-*` attribute. I have [filed a bug](https://github.com/vapor/leaf-kit/issues/89#issue-808793839) on their side. I'm closing this issue out. Thanks all!

**Comment by jcervant0611** [comment]
For some reason on the copy and paste it added an extra <link href=" to the link, try checking if it is that typo.
