### ISSUE TITLE
Tabs: Syntax Error on Edge Legacy

### ISSUE THREAD

**Issue by fnicastri** [twbs/bootstrap#33118]
Bootstrap-5.0.0-beta2
Windows 10 1809
Edge Legacy 44.19041

When switching tab:
Syntax Error.    bootstrap.bundle.js (974,6)

```
    find: function find(selector, element) {
      var _ref;

      if (element === void 0) {
        element = document.documentElement;
      }

      return (_ref = []).concat.apply(_ref, Element.prototype.querySelectorAll.call(element, selector));
    },
```

Tried both bubdle and just bootstrap plus popper, same result.
Tried current repo from github, same result.

Edge Legacy is still used in corporate environments.

Is this a bug or a design choice?
Is there a way to fix it?

Thanks,
Francesco

**Comment by mdo** [comment]
We don't support Edge Legacy in v5, sorry. /cc @XhmikosR for possible ideas, if any, here.

**Comment by XhmikosR** [comment]
We don't support Edge Legacy in v5. You might be able to use some polyfills, but I'm not sure about the details. Also, do note that some features might still be broken on the CSS side.

**Comment by fnicastri** [comment]
> We don't support Edge Legacy in v5. https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/#supported-browsers
> 
> You might be able to use some polyfills, but I'm not sure about the details. Also, do note that some features might still be broken on the CSS side.

I understand but this is a JS syntax error, any idea how to fix it?
I don't know the inner structure of bootstrap's js

**Comment by XhmikosR** [comment]
My guess is that said browser doesn't support `NodeList.forEach`: https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by fnicastri** [comment]
Thank you, eventually my only way is to convert all the project to Bootstrap 4.
