### ISSUE TITLE
<img> inside HTML tooltip is only displayed every other hover.

### ISSUE THREAD

**Issue by nikonthethird** [twbs/bootstrap#33124]
Reproduction:

https://jsfiddle.net/3k4cL51w/

Steps:

The `Test` button has a tooltip with `data-bs-html="true"` on it and an `<img>` tag in the title. When you hover your mouse multiple times over the button, you will see that the the image in the tooltip will only be shown every other hover.

I tested this on Ubuntu 20.04 on Firefox and Chromium.
It worked on 5.0 beta 1, the issue only started appearing after I upgraded to 5.0 beta 2.

**Comment by nikonthethird** [comment]
I investigated some more, and it appears to have to to with sanitization. When I initialize the tooltips with `sanitize` set to `false`, it does not happen:

```
new bootstrap.Tooltip(element, { sanitize: false }) // This fixes it.
```

**Comment by nikonthethird** [comment]
I figured out what's wrong. [This commit](https://github.com/twbs/bootstrap/commit/1b46601ce8461fbafc5c33d7b9030ea0ad306671#diff-f994f4b278594d44219f9b7310bf2f69f01cc56bd86da6aa6ab7dd535d40cfb3L40) switched from using the `match` method on strings to the `test` method of the `SAFE_URL_PATTERN` regex.

Well, the `match` and `test` methods behave differently. The problem is the `g` (global) modifier. [See the example here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) to see that the `test` method returns `true`, then `false` when presented with the same string:

```js
// This is the regex that's causing the problem.
const SAFE_URL_PATTERN = /^(?:(?:https?|mailto|ftp|tel|file):|[^#&/:?]*(?:[#/?]|$))/gi
```

To fix the issue, simply remove the `g` modifier (which, btw is not present on the `DATA_URL_PATTERN` regex, so no issue there). Furthermore, the regex is faulty, because slashes have to be escaped with a backslash (see [here](https://regex101.com/r/spYxnr/1)).

The correct regex would be:

```js
const SAFE_URL_PATTERN = /^(?:(?:https?|mailto|ftp|tel|file):|[^#&\/:?]*(?:[#\/?]|$))/i
```

And that fixes the issue on my end and I can leave the sanitizer turned on. I'll make a pull request if that's ok.

**Comment by MicroAnswer** [comment]
我也遇到相同的问题，看了你这波操作属实流弊，所以我就直接借用了。\
I had the same issues, thanks your idea.

**Comment by nikonthethird** [comment]
I opened an issue over at [the eslint unicorn plugin](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1114) so that the rule that introduced this bug can get fixed.
