### ISSUE TITLE
Dropdown dividers are styled with a wrong property

### ISSUE THREAD

**Issue by simzikov** [twbs/bootstrap#33143]
`$dropdown-divider-bg` controls the border color of the dropdown divider, instead of controlling its background color:

```
// Dividers (basically an `<hr>`) within the dropdown
.dropdown-divider {
  height: 0;
  margin: $dropdown-divider-margin-y 0;
  overflow: hidden;
  border-top: 1px solid $dropdown-divider-bg;
}
```

Since the `hr` color in Bootstrap v5 is controlled with `background-color`, this causes issues when overriding `$dropdown-divider-bg` with a semi-transparrent color values.

**Comment by mdo** [comment]
We do this because the `height: 1px` doesn't always render as best as possible, especially on scaled or retina displays. For now, we'll leave this as-is (which I believe is the same in v4, I don't recall having touched this).
