### ISSUE TITLE
Weird blur effect with floating labels in Firefox

### ISSUE THREAD

**Issue by stijn7621** [twbs/bootstrap#33142]
When I click in the v5 docs page on the textbox the floating labels are a bit blurry. After about a second the label is not blurry anymore. 

In the example for v4.3 (https://getbootstrap.com/docs/4.3/examples/floating-labels/) is this not the case.

Only happens in Firefox (Tested in Chrome and Firefox).

**Comment by mdo** [comment]
Could be the CSS transforms that are causing it. Are you by chance zoomed in at all? And what version of Firefox?

**Comment by stijn7621** [comment]
Possibly caused by multiple overriden css transforms. I have experienced delay in transform when developing before.

I’m not zoomed in (100%). It happens on the current version of firefox. Also, the label is not blurry in the given example for v4.3.

**Comment by mdo** [comment]
Yeah we changed the way we do it in v5 so it'd be quite different than v4 :).
