### ISSUE TITLE
Vertical harmony for headings(and other elements)?

### ISSUE THREAD

**Issue by mibocs** [twbs/bootstrap#33145]
https://getbootstrap.com/docs/4.0/content/typography

Could you tell me why you use same margin(margin-bottom: .5rem;) in every heading? Have you ever heard about vertical rhythm?
https://www.smashingmagazine.com/2012/12/css-baseline-the-good-the-bad-and-the-ugly
https://jhildenbiddle.github.io/vertical-rhythm-reset

How come the so called perfect Bootstrap doesn't know about this?

**Comment by mdo** [comment]
> How come the so called perfect Bootstrap doesn't know about this?

Who said Bootstrap was perfect? And who says we don't know about it? Please consider checking the attitude at the door—we're just maintaining an open source project.

---

> Could you tell me why you use same margin(margin-bottom: .5rem;) in every heading? Have you ever heard about vertical rhythm?

We're optimizing for a few things with our heading styles, chief among them Bootstrap's use in more complex sites and apps where vertical rhythm across all components and columns isn't exactly as important. We reset the styles to provide a consistent baseline and provide utilities for folks to customize as needed.

By the way, one of the examples you included use a similar approach to singular margin values on all elements:

```css
blockquote, dl, form, h2, h3, h4, h5, h6, ol, p, pre, table, ul {
  margin-top: 1.50001rem;
  margin-bottom: 1.50001rem;
}
```

It's unlikely we'll make significant changes here for every heading and other elements, but we do have some issues open for creating a "content component" where we apply more typographically sound spacing and sizing specifically designed for longer content. That might be where we start for something like this, but I'm not 100% sure this would help you.

Lastly, Issues are for bug reports and feature requests. Please consider using Discussions next time for open ended questions :).

**Comment by mibocs** [comment]
> Please consider checking the attitude at the door—we're just maintaining an open source project.
Ok maybe my attitude was not proper but it just annoys me that something so basic/important thing is not taken into account in Bootstrap.

> Who said Bootstrap was perfect?

Nobody said but i think most of developers use it. So this is why Bootstrap should use every modern and important technology and Bootstrap shouldn't be just a "reset" framework.

> We're optimizing for a few things with our heading styles, chief among them Bootstrap's use in more complex sites and apps where vertical rhythm across all components and columns isn't exactly as important.
The vertical rythm should be applied to the headings at least. Not important? Yes it is not because nobody(neither the developers) knows about it.

> By the way, one of the examples you included use a similar approach to singular margin values on all elements:

If you looked closely style of all headings is overriden and other elements like p, ul, table so on can be set globally.

> but we do have some issues open for creating a "content component" where we apply more typographically sound spacing and sizing specifically designed for longer content.

At least this is a good news and I hope it will be implemented soon.

> Lastly, Issues are for bug reports and feature requests. Please consider using Discussions next time for open ended questions :).
I didn't know where i should put this, because it is both bug report and feature request i guess.
