### ISSUE TITLE
Missing base-component.js in visual tests (beta2)

### ISSUE THREAD

**Issue by bigbaldy** [twbs/bootstrap#33158]
The visual tests in bootstrap-5.0.0-beta2/js/tests/visual are missing base-component.js. As an example the alert.html file generates the following console log error in Microsoft Edge browser.

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at _inheritsLoose (alert.js:35)
    at alert.js:45
    at alert.js:50
    at alert.js:9
    at alert.js:10

**Comment by ajaychandel730** [comment]
I am interested
