### ISSUE TITLE
table-hover regression

### ISSUE THREAD

**Issue by Techtonictools** [twbs/bootstrap#33172]
![Bootstrap4_tablehover](https://user-images.githubusercontent.com/49133697/108635733-d3c62900-7435-11eb-9952-0856a96dbf5c.png)
![Bootstrap5_tablehover](https://user-images.githubusercontent.com/49133697/108635734-d4f75600-7435-11eb-877b-ca830cfa3cfe.png)

The behavior of bootstrap 4 when doing a mouse-over on a table row, the row would get a light gray background color. That gray color filled the row perfectly and the gray color is the same shade throughout.

With bootstrap 5, the table hover gray color has two shades. An outer block shade that is the light gray I'm familiar with then an inner block shade that is a darker gray and it doesn't look right. 

FireFox 85.02 on Microsoft Windows [Version 10.0.19042.804]

    
    <div class="container">
        <table id="blockedBrandsTbl" class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">
                        Brand Name
                    </th>
                    <th scope="col">                        
                    </th>
                </tr>
            </thead>
            <tbody class="table table-sm">
              <tr>
                  <td>
                      <div id="brandName" class="my-2">
                          brand name goes here
                      </div>
                  </td>
                  <td>
                      <div class="my-2">
                          delete button goes here
                      </div>
                  </td>
              </tr>
            </tbody>
        </table>
    </div
    
    
In <header>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
    

At bottom of <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    <script src="~/js/jquery-3.4.1.min.js"></script>

**Comment by mdo** [comment]
This appears to be because of the `.table` class on the `<tbody>`. Removing that clears the issue for me.

**Comment by mdo** [comment]
Example: https://codepen.io/pen
