### ISSUE TITLE
Make "Sizing" responsive

### ISSUE THREAD

**Issue by svenignor** [twbs/bootstrap#33177]
May it be useful to add media-queries to: https://getbootstrap.com/docs/5.0/utilities/sizing/ like w-100, w-md-75, w-lg-50 and so on?
Use case:
There is an image which floats on bigger viewports and should have a width of 50%, but on smaller viewports it should take the available space.

**Comment by mdo** [comment]
We made the call in v5 to use our column sizing utilities for this. `.col-6` is 50%, for example, and no longer has padding applied.

**Comment by svenignor** [comment]
oh, i didn't see that. Thx for your replay and sorry
