### ISSUE TITLE
Dropdowns initialized using javascript (without data-bs-toggle) are shown on click to the button but cannot be hidden.

### ISSUE THREAD

**Issue by loxi5** [twbs/bootstrap#33182]
Dropdowns initialized using javascript can be shown by clicking to the button but re-clicking doesn't hide the dropdown. The button doesn't have "data-bs-toggle" attribute.

[https://codepen.io/hsyndrsn/pen/oNYGVvo](https://codepen.io/hsyndrsn/pen/oNYGVvo)

Operating System: Pardus 19.4-1 Gnome
Browser: Chrome 88.0.4324.182

**Comment by rohit2sharma95** [comment]
> `data-bs-toggle="dropdown"` still required
> Regardless of whether you call your dropdown via JavaScript or instead use the data-api, `data-bs-toggle="dropdown"` is always required to be present on the dropdown’s trigger element.

https://getbootstrap.com/docs/5.0/components/dropdowns/#via-javascript

Because there are some events attached by `data-bs-toggle="dropdown"` selector.

**Comment by XhmikosR** [comment]
Right, @rohit2sharma95 so this is a non-issue? if so feel free to close.

**Comment by rohit2sharma95** [comment]
The requirement of this selector can be omitted in the future though.
