### ISSUE TITLE
Button-based navs not growing with fill/justified

### ISSUE THREAD

**Issue by Kramb** [twbs/bootstrap#33196]
**OS**: Windows 10 Pro v1909 build 18363.1256
**Browser**: Google Chrome v88.0.4324.182 & Mozilla Firefox v85.0.1
**Summary**: When creating a nav with nav-tabs or nav-pills in combination with nav-fill or nav-justified the tabs grow as expected along with any anchors with the nav-link class applied. If you attempt to apply the nav-link class to a button in the same scenario the tabs still grow but the buttons do not.
**Use-case**: [Nav Pills/Tabs fill/justify issue](https://codepen.io/Kramb/pen/VwmyYLq?editors=1100)

**Comment by ffoodd** [comment]
After a few researches, I learned [that a button with `display: block;` won't get full width](https://stackoverflow.com/questions/9699039/button-with-displayblock-not-stretched) and this is [in the specification](https://html.spec.whatwg.org/multipage/rendering.html#button-layout).

The easiest workaround would be to mimic our old `.btn-block` class by explicitly adding `width: 100%;` to buttons, either through our `.w-100` utility or by adding into our `.nav-fill` variant. I don't think any side-effect would appear. any opinion, @mdo?

**Comment by mdo** [comment]
Adding the style works for me! No need to require the utility here IMO.
