### ISSUE TITLE
## Describe the bug

### ISSUE THREAD

**Issue by Sal430** [twbs/bootstrap#33202]
## Describe the bug

There is an error when checking the changed files:
`File:{fatal: master...dad356fc1a8f8fe0ed036fb518762fd1f32a9c2b: no merge base} existed in commit data, but not found on file system, skipping...`

This means there are 2 bugs. 
The command is failing fatally, but the script continues to work as if it didn't fail.
And also, the command is broken in some way and not finding the merge base.

## Expected behavior

The linter should continue to work as expected. We have yet another broken release :/

## Steps to Reproduce

I think the problem is related to squash commits. But also the way it is being used, makes that if the command fails, it is not properly handled.

## Additional context

__Originally posted by @GaboFDC in https://github.com/github/super-linter/issues/1258__

**Comment by XhmikosR** [comment]
Not sure how this is related to Bootstrap?
