### ISSUE TITLE
tooltip data-bs-toggle="tooltip" doesn't work

### ISSUE THREAD

**Issue by ScotsScripts** [twbs/bootstrap#33216]
The docs say that data-bs-toggle="tooltip" triggers a tooltip, but only the older style data-toggle="tooltip" works.

**Comment by aribudin** [comment]
hello sir
please check your bootstrap version

**Comment by ScotsScripts** [comment]
My error - I had the old tooltip js init which used data-toggle. When I changed it to the init in the bs 5 docs it worked as expected.
