### ISSUE TITLE
Subheading for Navbar Brand Title

### ISSUE THREAD

**Issue by rexarvind** [twbs/bootstrap#33215]
Subheadings are quite useful to quickly tell about what industry or service the website relates to. So this might be useful for almost everyone. 

I presented my solution for this, you guys might wanna include this as an in-built bootstrap class so that this feature is useful out of the box for everyone.

Coodepen: <https://codepen.io/rexwebmedia/pen/jOVZgvr>

[![Screenshot_2021-02-27-18-18-16-001](https://user-images.githubusercontent.com/63487995/109387614-6d0aa900-7928-11eb-82fa-fb6be4d22156.jpeg)](https://codepen.io/rexwebmedia/pen/jOVZgvr)

**Comment by mdo** [comment]
Thanks for the suggestion—we'll pass on this for now :).
