### ISSUE TITLE
Button group containing checkbox/radio button with an icon

### ISSUE THREAD

**Issue by daniel-p-tech** [twbs/bootstrap#33228]
Hi,

I am looking for a way to style a button group checkbox with an icon rather than text. Think of a typical text editor with a toolbar containing group of Bold/Italics/Underscore buttons with respective icons that can be checked. As far as I can tell, there is no built-in way in B5 to achieve this, or is there? If not, what workaround do you suggest and are you considering to add this feature in the upcoming release?

![image](https://user-images.githubusercontent.com/29497049/109550596-1ff81580-7a95-11eb-9805-30bd46a85a81.png)

Same idea with radio buttons:

![image](https://user-images.githubusercontent.com/29497049/109550647-2e463180-7a95-11eb-8571-404771d98cdb.png)

Thanks.

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.0/components/button-group/#checkbox-and-radio-button-groups

Use the link above, but instead of button text, place an icon within the label.

**Comment by philiprgbel** [comment]
ya iv just seen them so what do i habd to o

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
