### ISSUE TITLE
-webkit-appearance: button on anything but actual button-element makes it loose styling

### ISSUE THREAD

**Issue by bitnissen** [twbs/bootstrap#33229]
Tested on:
- Safari Version 14.0.3 (16610.4.3.1.4)

Steps to reproduce:
- Create a div, span, a-tag etc. and give it a button-class, for instance `<div class="btn btn-primary"></div>`

Expected:
- The div shows a blue button.

Actual behaviour:
- A grey button with white text is displayed.

Additional information:
- By disabling the `-webkit-appearance: button` the div renders with the proper styling.

Attached example where I modified the examples from the Bootstrap 5-docs to use a div and a span-element:
<img width="662" alt="CleanShot 2021-03-01 at 21 30 41@2x" src="https://user-images.githubusercontent.com/629954/109555418-d2e86380-7ad5-11eb-88bd-04f045d5a467.png">

**Comment by mdo** [comment]
Weird bug, possibly from our Reboot styles vs the button components. Using divs/spans though with the `type="button"` attribute is what causes it. In generally, you shouldn't be using those elements with these classes though.

**Comment by bitnissen** [comment]
@mdo I agree. I had accidentally left a `type="button"` in some code, where I had changed a button to a div, and when testing in Safari, I noticed this. I can't say if this even merits a fix, but it is inconsistent behaviour across browsers nonetheless, so it got a bug report ;-)

**Comment by ffoodd** [comment]
Thanks for reporting, indeed.

I don't think we should fix this: there's no valid reason to not use actual `button` when using Bootstrap since all styles are free of charge. We should not provide support for inaccessible markup, IMHO.

**Comment by mdo** [comment]
Closing for now per last comment :).

**Comment by firstflask** [comment]
add this ...

button,
input:where([type='button']),
input:where([type='reset']),
input:where([type='submit']) {
  -webkit-appearance: button; /* 1 */
  appearance: button;          /*<--added this*/  <<<<
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}  

or

[type='search'] {
  -webkit-appearance: textfield; /* 1 */
  appearance: textfield;           /*<-- added this*/ <<<<
  outline-offset: -2px; /* 2 */
}
