### ISSUE TITLE
When the sample code in the v5.0 document is too wide, the Copy button will block the code

### ISSUE THREAD

**Issue by summertzz** [twbs/bootstrap#33224]
### System Info

- Operating system and version:  All/Unrelated
- Browser and version: All/Unrelated

### Steps to reproduce

1. open (https://getbootstrap.com/docs/5.0/getting-started/introduction/#css)
2. view sample code
3. the rightmost code is blocked

### What is expected?

The code on the right is not blocked, just like the old version of the document, see (https://getbootstrap.com/docs/4.6/getting-started/introduction/#css)

### What is actually happening?

the rightmost code is blocked

**Comment by lsbbd** [comment]
| Environment | Info |
|---|---|
| bootstrap | 5.0 |
| Browser | chrome 88.0.4324.192 |

![image](https://user-images.githubusercontent.com/18237955/109513829-7474b280-7ae0-11eb-877b-5ff85d57f664.png)

**Comment by mdo** [comment]
Closing this as a won't fix, the copy button is meant to overlap content that overflows.
