### ISSUE TITLE
When the sample code in the v5.0 document is clicked to copy, the style is wrong and messy

### ISSUE THREAD

**Issue by summertzz** [twbs/bootstrap#33225]
### System Info

- Operating system and version:  All/Unrelated
- Browser and version: All/Unrelated

### Steps to reproduce

1. open (https://getbootstrap.com/docs/5.0/getting-started/introduction/)
2. click the copy button at the top right of the sample code
 ![image](https://user-images.githubusercontent.com/27355995/109514961-83a83000-7ae1-11eb-8f1f-12cc2aa2e0ca.png)

### What is expected?

 Just like the old version of the document, see (https://getbootstrap.com/docs/4.6/getting-started/introduction)

**Comment by XhmikosR** [comment]
The root cause is the same as #32372 AFAICT
