### ISSUE TITLE
Offcanvas — Remaining things

### ISSUE THREAD

**Issue by rohit2sharma95** [twbs/bootstrap#33244]
Things to do after #29017

- [x] Accept `data-bs-body` option in the configuration object as well (PR — #33248)
- [x] Add a navbar offcanvas example too ( closed by #34273)
- [x] Fix/tweak/remove the existent offcanvas separate example
- [ ] Improve snippets in offcanvas page to remove `...`?

**Comment by GeoSot** [comment]
_Accept data-bs-body option in the configuration object as well_ can be closed with this #33248

**Comment by mdo** [comment]
Closing this as done enough for now—I'm fine with the `...` in the docs examples and we dropped the separate example for the docs examples.
