### ISSUE TITLE
V5 Placeholder Utilities :

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33254]
I hope the Bootstrap Core team take in consideration to add the placeholder utilities to control Color and Opacity the same utilities is exist in **[tailwind css](https://tailwindcss.com/docs/placeholder-color)**.

**Placeholder Color :** 

```
<input class="placeholder-gray-500 ..." placeholder="jane@example.com">
<input class="placeholder-red-300 ..." placeholder="jane@example.com">
```

**Placeholder Opacity**

```
<input class="placeholder-gray-500 placeholder-opacity-100 ..." placeholder="jane@example.com">
<input class="placeholder-gray-500 placeholder-opacity-75 ..." placeholder="jane@example.com">
```

**Comment by mdo** [comment]
No plans to add this ourselves—the utilities API exists for these kind of customizations :).
