### ISSUE TITLE
npm package dosent include .form-label

### ISSUE THREAD

**Issue by lenni-io** [twbs/bootstrap#33255]
Hey Bootstrap Team,

like the title says, it seems like the npm package dosent include the .form-label class at "./scss/_forms.scss"

**Comment by ffoodd** [comment]
Well, it does obviously: see either in our docs or in [JSDelivr CDN](https://cdn.jsdelivr.net/npm/bootstrap@next/dist/css/bootstrap.css)(search for `.form-label`).

So I guess you need to provide more insights.

**Comment by lenni-io** [comment]
Okay, i just noticed my problem: I was refering to [bootstrap/scss/_forms.scs](https://cdn.jsdelivr.net/npm/bootstrap/scss/_forms.scss)  and not  [bootstrap@next/scss/_forms.scss)](https://cdn.jsdelivr.net/npm/bootstrap@next/scss/_forms.scss): so changing the package actualy solves my problem for me.

At [npm](https://www.npmjs.com/package/bootstrap) the installation is still documented with `npm i bootstrap`  which lead to the problem.
