### ISSUE TITLE
Bootstrap 3x Objects disappear when the ajax call is processing

### ISSUE THREAD

**Issue by lrochaoliveira** [twbs/bootstrap#33262]
I have an application in Bootsptrap 3.3.0, and the objects like buttons, input text, and so one, disappear during a jQuery ajax call and affter the process too. I need to pass the mouse over the objects to appear again. It's strange. What could be happening?

**Comment by mdo** [comment]
We're not maintaining Bootstrap 3 unfortunately. You'll need to ask around in our Slack or on StackOverflow.
