### ISSUE TITLE
Skip validation on certain fields

### ISSUE THREAD

**Issue by PubliAlex** [twbs/bootstrap#33260]
Hello,

The bootstrap replacement of browser default validation looks cool, but sometimes, you don't want to apply validation to some fields.

Look that example : 
![image](https://user-images.githubusercontent.com/55833027/109942187-3d66f280-7cd4-11eb-9b78-d49cb514e392.png)

When I submit the form, I want to display the error on the email and password fields, cause we are on a login page and that fields are empty, so it make sense. But putting in green the "remember me" checkbox is not relevant at all.

I didn't see anything in the documentation that show how to skip some fields from validation.

I use the default code actually, here is it : 

```
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function () {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
```

And this is my form : 

```
        <form class="needs-validation" novalidate>
            
            <div class="form-floating mb-3">
                <input class="form-control" type="email" id="field-email" name="email" placeholder="&nbsp;" required />
                <label class="form-label" for="field-email">Email</label>
                <div class="invalid-feedback">Veuillez indiquer une adresse email valide</div>
            </div>
            
            <div class="form-floating mb-3">
                <input class="form-control" type="password" id="field-password" name="password" placeholder="&nbsp;" required />
                <label class="form-label" for="field-email">Mot de passe</label>
                <div class="invalid-feedback">Veuillez indiquer votre mot de passe</div>
            </div>
            
            <div class="row justify-content-between">
                <div class="col-auto">
                    <div class="form-check mb-3">
                      <input class="form-check-input" type="checkbox" name="remember_me" id="field-remember-me" />
                      <label class="form-check-label" for="field-remember-me">Se souvenir de moi</label>
                    </div>
                </div>
                <div class="col-auto">
                    <a href="#">J'ai oublié mon mot de passe</a>
                </div>
            </div>
            
            <button class="btn btn-primary" type="submit">Connexion</button>
```

**Comment by ffoodd** [comment]
You may simply try to add the `.was-validated` class on a wrapper around your instead of your form, [here's a codepen demonstrating this](https://codepen.io/ffoodd/pen/LYbBYYM?editors=1010).

FYI that doesn't skip the validation but only prevents the styles from applying.

I'm closing this since Bootstrap does not provide any validation mechanism (relying on browsers ones) and only provide helper classes to styles validation states. Feel free to comment back if this demo doesn't fit your need.

**Comment by mrlife** [comment]
@ffoodd Hi, the codepen doesn't seem to disable the styles. I'm also interested in disabling the bootstrap validation styles from applying. Is there a supported way to do so? Thank you.
