### ISSUE TITLE
I am not able to use the Bootstrap tour with latest version of bootstrap . Is there any plan to make it compatible with Bootstrap 5, and when?

### ISSUE THREAD

**Issue by Amolbharambe** [twbs/bootstrap#33266]
Hi Team,
I am not able to use the Bootstrap tour with the latest version of bootstrap. Is there any plan to make it compatible with Bootstrap 5, and when?

**Comment by ffoodd** [comment]
Please report such issue to [Bootstrap Tour](https://github.com/sorich87/bootstrap-tour), we don't maintain nor provide support for it.
