### ISSUE TITLE
V5 Utilities : Add Letter Spacing

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33269]
```
ls-normal
ls-2
ls-3
ls-4
ls-5
```

Based on `$spacers` map.

**Comment by ffoodd** [comment]
I doubt that `letter-spacing: 1rem` makes any sense, would you mind elaborating a bit?

Moreover this is exactly what our utility API is for, so feel free to extend your build by adding your own utilities.

**Comment by devhoussam** [comment]
> I doubt that `letter-spacing: 1rem` makes any sense, would you mind elaborating a bit?
> 
> Moreover this is exactly what our utility API is for, so feel free to extend your build by adding your own utilities.

thank you
