### ISSUE TITLE
HTML5 details tag support

### ISSUE THREAD

**Issue by hellow554** [twbs/bootstrap#33268]
This is very hard to search for, so please forgive me if this has been proposed or asked before.

HTML5 introduced the [`<details>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).
This is in some regards very similar to an accordion with only one card, but it's usecase is different.

Currently, I don't see any css support for the details tag in bootstrap.

My request is to support this tag and style it properly.

**Comment by ffoodd** [comment]
Well, in fact there's not much to do regarding styles: we use `details` in our docs ([e.g. in "Introduction"](https://getbootstrap.com/docs/5.0/getting-started/introduction/#components) and it's pretty straightforward.

Using our utilities for colors, fonts, spacings et all, you're able to customize it as you intend to.

Waht would you like to see in Bootstrap exactly?

**Comment by hellow554** [comment]
Indeed. What I was missing is in fact the summary decoration, e.g. `fw-bold`. 
I thought it would look different, much more like an accordion with cards.

I guess this issue could be closed then?
