### ISSUE TITLE
Carousel data-ride / data-interval / data-pause bugs

### ISSUE THREAD

**Issue by epignosis567** [twbs/bootstrap#33275]
Hi. I spent several hours testing different Bootstrap 4.5 carousel options configuration because I thought I sensed a bug and this is what I've found:

The behavior of the “default” values of data-ride and data-interval often result in different behavior if those “default” values are entered manually.

I’ve indicated after each result whether or not it conforms to the expected behavior according to the defaults as stated in the docs. 
OK = functions as expected
X? = does not function as expected

If no **data-ride / data-interval / pause** is present
then according to the docs the defaults are 
**data-ride=“false” data-interval=“5000” pause=“hover”**
RESULTS
carousel will not start on its own - OK
carousel will continue once started - X?
(I assume the data-interval default is overriding the data-ride value, even though this isn't made clear in the docs.)

For all of the following tests I set **pause=“false”** 
meaning that the focus/mouse location should have no effect on whether or not the carousel advances

**data-ride="carousel" + data-interval="false"**
will not start on its own - X? 
will not continue once started - X?
(I again assume that data-interval="false" is preventing carousel from starting/advancing, overriding the data-ride setting.)

**data-ride=“false” (with default data-interval=“5000”)**
will not start on its own - OK
will continue once started - X?
(Contradicts previous test where the data-interval value overrides the data-ride value)

**data-ride=“false” + data-interval=“1000”** 
will not start on its own - OK 
will continue once started AND pause on hover - X?
(Contradicts previous test where the data-interval value overrides the data-ride value _AND_ causes a pausing error)

So the question seems to be, does the data-interval value override the data-ride setting, because sometimes it does and sometimes it doesn't.
And additionally, what's up with that weird pause error?

(I'm especially interested because while these questions are important on their own, putting a carousel inside of a modal DEFINITELY has it's own weird bugs that arise, so I'm hoping to get an answer on this first, and then start working on the carousel inside of a modal issues, which are my real concern.)

macOS 10.15.6
Chrome 89.0.4389.72

**Comment by epignosis567** [comment]
Bump?

**Comment by alpadev** [comment]
From what I can tell `data-ride="carousel"` is only used to decide if the carousel should cycle automatically (if `data-interval` isn't set to false) after the page loads. It has no effect once the carousel got started.

Pretty much as is described in the documentation:
> Autoplays the carousel after the user manually cycles the first item. If set to 'carousel', autoplays the carousel on load.

The naming is a bit misleading maybe. A better name could be autorun or run-after-load and to make it binary.

Btw. "Bump?" after 3 days already rather makes me want to ignore your question.. 🙄 This is open source where you either contibute to solve problems or got patience.

**Comment by epignosis567** [comment]
Thanks. Learning how to code and just starting to file github issues, didn't know the appropriate bump time frame.

Still not understanding why sometimes 'data-interval' overrides the 'data-ride' setting and sometimes it doesn't. But the main problem is that weird pause error, maybe it's a problem somewhere in my file, or maybe it's a bug. I uploaded the file to github so others can test but it seems pretty straight forward to me. Like I said I'm still learning though.

**Comment by alpadev** [comment]
Well we do this for fun and in our spare time so maybe you should lower your expectations.. And I can guarantee you there are people on this project who take care it's not lost somewhere.

Again `data-ride` only has the effect of kicking off the cycle automatically after the page loads. Once it got started `data-ride` has no effect on the functionality.

**Comment by alpadev** [comment]
And welcome to the dev community. Writing issues is a good starting point but you sometimes have to wait weeks or even months to eventually get a response. (Not on this project tho 😉)

Since you're in the progress to learn things - this is the source of the carousel: https://github.com/twbs/bootstrap/blob/v4.6.0/js/src/carousel.js

You can try to look there and figure the logic for yourself or maybe propose some changes to the documentation if you feel there is need to explain something better.

**Comment by alpadev** [comment]
Please reopen the ticket if you still feel there is a bug.
