### ISSUE TITLE
Bootstrap 5 table on dark background

### ISSUE THREAD

**Issue by mc0re** [twbs/bootstrap#33286]
Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
- Windows
- 
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- Microsoft Edge Chromium 89.0.774.45
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
https://jsbin.com/renawib/edit?html,js,output

On a dark background the table text disappears. Do I really need to define all tables as `table-dark`, if I use `bg-dark`?

**Comment by mdo** [comment]
Check the docs for an example of a dark table: https://getbootstrap.com/docs/5.0/content/tables/#accented-tables
