### ISSUE TITLE
Badge and a few other components missing

### ISSUE THREAD

**Issue by tguimmaraess** [twbs/bootstrap#33298]
I was working on my scss files and everything was ok, but then, I had to reinstall bootstrap using `npm`, when I reinstalled it, a lot of things didn't work, such as badges and some other components as well as margins. I'm using version Bootstrap version 5.0. I tried including bootstrap from CDN but same issue...

**Comment by mdo** [comment]
Check the migration guide in our docs. There were some meaningful changes between betas and v5 isn't fully stable yet.
