### ISSUE TITLE
V5 Dropdowns : Rotate caret on toggle

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33299]

**Comment by WinterSilence** [comment]
@devhoussam you can do it now, just add
~~~scss
&.show {
  @include caret(up);
}
~~~
after
https://github.com/twbs/bootstrap/blob/e50c11b8c6434b6d68ea5897771e4d35fe12f5c3/scss/_dropdown.scss#L13

**Comment by mdo** [comment]
Punting on this for now.
