### ISSUE TITLE
Background shines through in input-group leaving small spots

### ISSUE THREAD

**Issue by nwittstruck** [twbs/bootstrap#33295]
Hey! Thanks for the great work on bootstrap :wave:

I've noticed small dark spots in an input field when a background-color is set:

<img width="58" alt="Screenshot 2021-03-07 at 15 18 57" src="https://user-images.githubusercontent.com/1283061/110243038-01908f00-7f59-11eb-8149-28b2498cb694.png">

https://jsbin.com/viweracaju/edit?html,output

This seems to be only happening in Safari. Is this a rendering issue in Safari that I should report to them or is there an issue with my markup?

It seems to be related to this setting - disabling the border-bottom-right-radius removes the stains.

<img width="304" alt="Screenshot 2021-03-07 at 15 29 55" src="https://user-images.githubusercontent.com/1283061/110243299-043fb400-7f5a-11eb-941b-854fd8318408.png">

- Operating system and version
macOS 10.15.7

- Browser and version
Safari 14.03. Seems to be fine in Firefox

**Comment by mdo** [comment]
Definitely seems like a rendering glitch. If this was just in the corners that'd be one thing (and perhaps linked to background clipping), but this seems like something outside our codebase.
