### ISSUE TITLE
V5 Dropdowns : Add the scrollbar possibility when dropdown menu contains many items

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33309]
**Something similar to this class :**

`.dropdown-menu-scrollable { ... }`

**Comment by devhoussam** [comment]
> I think it is unnecessary to add an additional class for this. You can use the `overflow-auto` class along with setting a height and/or max-height on your dropdown.
> 
> ```
> <ul class="dropdown-menu overflow-auto" style="max-height: 200px;" aria-labelledby="dropdownMenuButton1">
>     ...
> </ul>
> ```
> 
> See working example on [CodePen](https://codepen.io/Blakej115/pen/VwmEqpZ).

I know but it will be more efficient if there was a dropdown class to do this the same thing is exist for modals

**Comment by mdo** [comment]
Leaving this one for the utilities for now.
