### ISSUE TITLE
Does V5 will support the new SASS module system using @use instead of @import?

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33303]

**Comment by XhmikosR** [comment]
Nope.

**Comment by devhoussam** [comment]
> Nope.

in my opinion I think it will be more efficient to support the new SASS module system
because many Front end developers who use SASS Preprocessor now think to switch to use the new SASS module system among them am I. 

thank you.

**Comment by XhmikosR** [comment]
There are other issues for this request. Search and you will find more answers :)

**Comment by devhoussam** [comment]
> There are other issues for this request. Search and you will find more answers :)

I will thank you so mush for your answer.

**Comment by jamiebarrow** [comment]
I came across this one by searching for existing issues :P Took me a while to find the below, so adding a comment, hope it helps others :)

https://github.com/twbs/bootstrap/issues/29853
