### ISSUE TITLE
V5 SassError: Undefined mixin : while move up from @import to @use the new SASS module system

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33304]
I'm moving up to new **SASS module system** from **[@import](https://sass-lang.com/documentation/at-rules/import)** to **[@use](https://sass-lang.com/documentation/at-rules/use)** but I have some issues while I do that with **bootstrap v5** :

![Image](https://i.imgur.com/4UPBv4j.png)

**from :**
```
@import "~bootstrap/scss/bootstrap";
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
```

**to :**

```
@use "~bootstrap/scss/bootstrap";
@use "~bootstrap/scss/functions";
@use "~bootstrap/scss/variables";
@use "~bootstrap/scss/mixins";
```

**Comment by mdo** [comment]
We don't support the module system.

**Comment by devhoussam** [comment]
> We don't support the module system.

Unfortunately, I wish you would have thought of support the module system on future.

SASS core team bring new things to who using it

**Comment by mdo** [comment]
Yeah, we did. There are other issues discussing this. The old way is not being deprecated for a couple years, and supporting the new module system would've meant rewriting and changing a lot about how Bootstrap works. Not something we wanted to do in v5.

**Comment by devhoussam** [comment]
> Yeah, we did. There are other issues discussing this. The old way is not being deprecated for a couple years, and supporting the new module system would've meant rewriting and changing a lot about how Bootstrap works. Not something we wanted to do in v5.

You convinced me with your answer, thank you so much 👍

**Comment by mrFANRA** [comment]
@import is deprecated now in Sass. How to solve this problem?
