### ISSUE TITLE
V5 Utilities : Add Object Fit & Position

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33316]
I think the BS Core team should be taken in consideration to add the both **Utilities (Object Fit & Position) in V5.**

**Why Object Fit & Position ?**

> The object-fit CSS property sets how the content of a replaced element, such as an <img> or <video>, should be resized to fit its container.

> The object-position CSS property specifies the alignment of the selected replaced element's contents within the element's box.

**more info :** 

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit 
https://developer.mozilla.org/en-US/docs/Web/CSS/object-position

**Comment by mdo** [comment]
I believe there was an issue about this before and similar to some other utilities issues recently opened, we'll pass on it for now.
