### ISSUE TITLE
Sanitizer strips href from even numbered links

### ISSUE THREAD

**Issue by freddyheppell** [twbs/bootstrap#33317]
OS: macOS Big Sur 11.2.2
Browser: Firefox 86 & Chrome 88

If HTML containing multiple links is passed to the sanitizer (e.g. via creation of a Popover), even numbered links will get their href stripped, but other attributes will remain

Test case: https://codepen.io/freddyheppell/pen/RwoeXOG

**Comment by alecpl** [comment]
Confirmed. Note that the bug exists in v5 only. No issue in v4.

**Comment by alpadev** [comment]
This is already fixed with https://github.com/twbs/bootstrap/pull/33136

**Comment by mdo** [comment]
Closing per above comment.
