### ISSUE TITLE
V5 Utilities : Add Border Opacity

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33320]
**Why Border Opacity?**

> The Border Opacity Utilities for controlling the opacity of an element's border color.

**Border Color Changes :**

```
.border-primary {
  --bs-border-opacity: 1;
  border-color: rgba(13, 110, 253, var(--bs-border-opacity))
}

.border-indigo {
  --bs-border-opacity: 1;
  border-color: rgba(102, 16, 242, var(--bs-border-opacity))
}

.border-purple {
  --bs-border-opacity: 1;
  border-color: rgba(111, 66, 193, var(--bs-border-opacity))
}
...
```

**Border Opacity Example :**

```
.border-opacity-0 {
  --bs-border-opacity: 0
}

.border-opacity-5 {
  --bs-border-opacity: 0.05
}

.border-opacity-10 {
  --bs-border-opacity: 0.1
}

.border-opacity-20 {
  --bs-border-opacity: 0.2
}

.border-opacity-25 {
  --bs-border-opacity: 0.25
}
...
```

> The same thing is supported by Tailwind CSS V2.03

https://tailwindcss.com/docs/border-color
https://tailwindcss.com/docs/border-opacity

**Comment by samarmohan** [comment]
I'll PR this.

**Comment by Farzin3** [comment]
<!-- wp:cover {"url":"https://shap165691762.files.wordpress.com/2021/06/qi-bin-w4hbafegiac-unsplash.jpg","id":28,"dimRatio":10,"align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-10 has-background-dim"><img class="wp-block-cover__image-background wp-image-28" alt="" src="https://shap165691762.files.wordpress.com/2021/06/qi-bin-w4hbafegiac-unsplash.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"textAlign":"center","level":1,"className":"margin-bottom-half"} -->
<h1 class="has-text-align-center margin-bottom-half">Welcome to your new site.</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","className":"margin-top-half","style":{"color":{"text":"#ffffff"}}} -->
<p class="has-text-align-center margin-top-half has-text-color" style="color:#ffffff">For more information about customizing your site check out&nbsp;<a href="https://href.li/?http://learn.wordpress.com/">learn.wordpress.com</a></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"style":{"border":{"radius":2}}} -->
<div class="wp-block-button"><a class="wp-block-button__link" href="http://learn.wordpress.com" title="learn.wordpress.com" style="border-radius:2px">Learn more</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":177} -->
<div style="height:177px" aria-hidden="true" id=".border-primary-{-----bs-border-opacity:-1;---border-color:-rgba(13,-110,-253,-var(--bs-border-opacity))-}--.border-indigo-{-----bs-border-opacity:-1;---border-color:-rgba(102,-16,-242,-var(--bs-border-opacity))-}--.border-purple-{-----bs-border-opacity:-1;---border-color:-rgba(111,-66,-193,-var(--bs-border-opacity))-}-..." class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:syntaxhighlighter/code -->
<pre class="wp-block-syntaxhighlighter-code"></pre>
<!-- /wp:syntaxhighlighter/code -->

<!-- wp:syntaxhighlighter/code {"language":"jscript"} -->
<pre class="wp-block-syntaxhighlighter-code"></pre>
<!-- /wp:syntaxhighlighter/code -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:group {"align":"wide"} -->
<div class="wp-block-group alignwide"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"33%"} -->
<div class="wp-block-column" style="flex-basis:33%"><!-- wp:list -->
<ul><li>فهرست بخش ها</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>فروشگاه/انواع کالاها را میتوتونید با ما ارزان تر راحت تر بخرید.دست خالی نمیروید</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>چالش</strong>/چالش های ما را شرکت کنید و اول تا سوم جایزه بگیرید و با هر چالش مبلغی رو بابت ورودی خواهید پرداخت که در صورت نبردن هم شما در هفته از ما دو برابر میگیرید یا در هر ماه</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>گردشگری/برای سفر با ما تجربه جدید را امتحان کنید </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>یاران/یاران .کسانی که قدرت خرید اجناس را ندارند به ما اطلاع میدن و ما هم به کاربران از ۱۰۰۰تومن تا هر چقدر که بتوانید کمک کنید و با این کار امتیاز چند برابری پول خود را ببینید</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>هنرمندان/هنرمندان میتوانند به یکدیگر کمک کنند و ایده های خوب را خود ما نیز پشتیبانی خواهیم کرد</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"right"} -->
<p class="has-text-align-right">و...درآمد با نابغه/در صورت وجود همکاری دوشخص ما توانایی این کمک ها و افزایش پول شمارا داریم کسانی که هوش سرمایه گذاری دارند .</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"67%"} -->
<div class="wp-block-column" style="flex-basis:67%"><!-- wp:heading {"level":3,"style":{"typography":{"fontSize":30,"lineHeight":"1.2"}}} -->
<h3 style="font-size:30px;line-height:1.2">Latest from the Blog</h3>
<!-- /wp:heading --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:jetpack/contact-form {"subject":"]وزیر آفرین] Home","to":"fazin.hadi1371@gmail.com","customThankyouHeading":"ثبت نام"} -->
<!-- wp:jetpack/field-name {"required":true} /-->

<!-- wp:jetpack/field-email {"required":true} /-->

<!-- wp:jetpack/field-textarea /-->

<!-- wp:jetpack/button {"element":"button","text":"ارسال مشخصات"} /-->
<!-- /wp:jetpack/contact-form --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"style":{"color":{"background":"#ba0c49","text":"#fffffa"},"border":{"radius":2}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="border-radius:2px;background-color:#ba0c49;color:#fffffa">هم‌اکنون شرکت کنید</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"#ba0c49"},"border":{"radius":2}}} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color" style="border-radius:2px;color:#ba0c49">در خصوص پیشنهادات</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">فروشگاه</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">چالش</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">گردشگری</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">هنرمندان</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">یاران</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">درآمد با نابغه</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:a8c/blog-posts {"imageShape":"uncropped","showAuthor":false,"showAvatar":false,"postLayout":"grid","typeScale":3,"align":"wide"} /-->

<!-- wp:spacer {"height":58} -->
<div style="height:58px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"align":"full","backgroundColor":"foreground-dark"} -->
<div class="wp-block-group alignfull has-foreground-dark-background-color has-background"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"45%"} -->
<div class="wp-block-column" style="flex-basis:45%"><!-- wp:paragraph {"align":"left","style":{"typography":{"fontSize":20,"lineHeight":"1.3"}}} -->
<p class="has-text-align-left" style="font-size:20px;line-height:1.3">Get new content delivered directly to your inbox.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"55%"} -->
<div class="wp-block-column" style="flex-basis:55%"><!-- wp:jetpack/subscriptions {"buttonBackgroundColor":"primary","textColor":"background","fontSize":"16px","customFontSize":"16px","borderRadius":2,"borderWeight":1,"padding":16} -->
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">[jetpack_subscription_form show_subscribers_total="false" button_on_newline="false" custom_font_size="16px" custom_border_radius="2" custom_border_weight="1" custom_padding="16" custom_spacing="10" submit_button_classes="has-16-px-font-size has-text-color has-background-color has-background has-primary-background-color" email_field_classes="has-16-px-font-size" show_only_email_and_button="true"]</div>
<!-- /wp:jetpack/subscriptions --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":60} -->
<div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":71}}} -->
<p style="font-size:71px"><strong>Menu</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p><strong>Awesome Burger</strong><br>The burger that made us famous. 100% pure lean beef grilled to perfection.<br><strong>$8.00</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p><strong>Chicken Sandwich</strong><br>Cajun chicken breast with lettuce and tomato on a freshly toasted bun.<br><strong>$8.00</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p><strong>Veggie Burger</strong><br>A delicious, soy, boca patty, served on a freshly toasted, whole-wheat bun.<br><strong>$8.00</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p><strong>Garden Salad</strong><br>Fresh greens with cheddar cheese diced tomatoes, and honey mustard dressing.<br><strong>$8.00</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":60} -->
<div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

**Comment by Farzin3** [comment]
### 16c999e8c71134401a78d4d46435517b2271d6ac
mojombo@16c999e8c71134401a78d4d46435517b2271d6ac
mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac

-[https://pulapczsmw.casa/play ] [@VazirAfarin30](https://pulapczsmw.casa/play)

**Comment by mdo** [comment]
Was added in #35428.
