### ISSUE TITLE
V5 Tabs Component : Add Scrollable Tabs

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33336]
https://codesandbox.io/s/n5uch

**Comment by FANMixco** [comment]
This is a great idea! When you have too many tabs, they don't like great in mobile devices.

**Comment by FANMixco** [comment]
This is a potential solution developed for Bootstrap 4 with jQuery:
https://codepen.io/srees/pen/pgVLbm

It looks okay in my opinion since Bootstrap is not Material Design.

What do you think @devhoussam?

**Comment by FANMixco** [comment]
Hi @devhoussam,

I translated the plugin to pure JS:
https://github.com/SupernovaIC/scrollable-tabs-bootstrap-5

Here you can see it in action:
https://supernovaic.github.io/scrollable-tabs-bootstrap-5/

It might not be perfect, for sure, it needs some fixes and, find a way to replace the `move.js` library, but overall, it works the same and I'd be glad if something like this could be added to Bootstrap

**Comment by mdo** [comment]
We'll pass on doing this ourselves, but it's not _too_ difficult to do on your own. I put together a small demo of something a few weeks back: https://markdotto.com/2022/03/10/horizontal-scrolling-nav/. Most of this kind of thing depends on your own situation and framework. Maybe this is something we tackle in v6, but I'm not 100% convinced. Could be helpful to make navs more responsive perhaps?

/cc @twbs/css-review for any other thoughts
