### ISSUE TITLE
Add some extra function to js nodelist

### ISSUE THREAD

**Issue by pejman-hkh** [twbs/bootstrap#33331]
Hi,
Add some function to nodelist js cause to easy usage in bootstrap, I have writed some functions for it, For example all events and some function like each.

My tiny and usable project link is : https://github.com/pejman-hkh/nodelist

In bootstrap instead this defination : 
```js
var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl)
})
```
We can use this : 
```js
document.querySelectorAll('[data-bs-toggle="popover"]').each(function() {
	return new bootstrap.Popover(this)
})
```

Or use some events like jquey : 

```js
document.querySelectorAll('.mytabs > li').click(function() {
	document.querySelectorAll(this).data('aaa', 'bbbb');
	console.dir(  document.querySelectorAll(this).data('aaa', 'bbb') );

	console.log( document.querySelectorAll(this).data('aaa') );

   	document.querySelectorAll('.tab-content > div.active').each(function() {
    	console.log( this );
    }).removeClass('active');
    document.querySelectorAll('.tab-content '+this.dataset.target+'').addClass('active');
})

```

I think this project can help developers for fast and simple usage of javascript.
For simple usage, I equals document.querySelectorAll to $ sign and i have rewrited document.querySelectorAll for accept object so.

**Comment by XhmikosR** [comment]
Thanks, but our goal is to move away from any libraries and just use vanilla APIs. If someone wants to use a project like the one you mention, that's fine.
