### ISSUE TITLE
BS website search that saves results

### ISSUE THREAD

**Issue by nathan-daugherty** [twbs/bootstrap#33338]
This isn't related to Bootstrap code, but to the documentation website, so I apologize if this isn't the right place to submit that kind of feature request.

The search can be cumbersome because you type in a topic like "Lists" and multiple results show without any distinction. Click one and find it's not the one you want, so you have to re-type "lists." What is a better user experience in my opinion is to somehow save the search so you can just go back to see the results and click on another one.

**Comment by alpadev** [comment]
@mdo The next version of DocSearch (currently [alpha](https://github.com/algolia/docsearch/tree/next) - [documentation](https://autocomplete-experimental.netlify.app/docs/docsearch-js/)) features recently searched items.

![image](https://user-images.githubusercontent.com/2838324/111249998-df5bd880-860c-11eb-8f41-b4b12c135416.png)

As a workaround for the current version we could open links in a new tab (maybe not the best but simpliest thing to do). Alternatively save the search value in the local storage or manipulate the url e.g. `...?search=value` and make docsearch aware of that. 

Not sure whats the best thing to do. AFAICT there are already some projects using it e.g. those based on [Docusaurus 2](https://v2.docusaurus.io/showcase)

**Comment by XhmikosR** [comment]
I think the best solution would be moving the new docsearch versions as soon as it's stable. Right now we do have custom styles, so we'd need to adapt our docs to drop any no-longer needed stuff.

**Comment by mdo** [comment]
Agreed on the next stable Algolia version.
