### ISSUE TITLE
.btn-check on mobile devices has confusing behavior

### ISSUE THREAD

**Issue by vkrapotkin** [twbs/bootstrap#33347]
Go to https://getbootstrap.com/docs/5.0/forms/checks-radios/#outlined-styles using mobile device.
Try to check and uncheck outline buttons.
When you uncheck button it looks as still checked because the :hover style looks the same as a checked one.
On a desktop usually you move cursor immediately and hover effect goes away. A mobile device doesn't have a cursor so hover effect stays until you click outside explicitely.

**Comment by ffoodd** [comment]
Kind of duplicates #26804 and relates to #31149 too, isn't it? Could you please confirm?

**Comment by vkrapotkin** [comment]
Yes, it is. I didn't found it somewhy.
