### ISSUE TITLE
Docs for the collapse component do not include example for data-bs-parent

### ISSUE THREAD

**Issue by danielkauffman** [twbs/bootstrap#33345]
The [v5 docs for the collapse component](https://getbootstrap.com/docs/5.0/components/collapse/#via-data-attributes) state:

> To add accordion-like group management to a collapsible area, add the data attribute data-bs-parent="#selector". Refer to the demo to see this in action.

However, the example on that page does not show how to use the `data-bs-parent` attribute.

The [example from the v4 docs](https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example) shows how to use the `data-parent` attribute to get accordion-like group management.

The `data-bs-parent` attribute works in v5, but I had to parse the docs for v4 in order to figure out how to use it.

I'm doing accordion-like group management, but not wanting the accordion markup, so using collapse with the `data-bs-parent` attribute works perfectly for me.

This appears to be a regression arising from moving the accordion to a separate section in the docs. Ideally, I think the v5 docs for the collapse component should have an example showing the use of the `data-bs-parent` attribute and the v5 docs for the accordion component should describe the `data-bs-parent` attribute as critical for accordion behavior.

See also #33214.

**Comment by mdo** [comment]
Down to see additional examples for just about any component :). If you have a snippet you've put together for v5, would you mind opening a PR for it? Happy to help see it over the finish line.

**Comment by danielkauffman** [comment]
@mdo Awesome. Like so? It's my first contribution to Bootstrap so I might have missed something. :-)

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/pull/33348#issuecomment-882232825
