### ISSUE TITLE
Issue when control is inside modal with overflow: scroll 

### ISSUE THREAD

**Issue by ppr-odoo** [twbs/bootstrap#33342]
The date picker pop-up appears 'inside' the modal when it is shown with overflow set to scroll. 
Here is an example:
https://drive.google.com/file/d/13Sf2DckjfXvVy7MqvG90brtiVnMeQ5WY/view?usp=sharing

**Comment by mdo** [comment]
Whatever that date picker is, you'll need to consult with them. This is because we use overflow to make the scroll happen. Ideally the date picker library you use can change how/where the popover is placed to avoid this issue.
