### ISSUE TITLE
Undefined CSS variables

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#33358]
Missed CSS variables in `_root.scss`:
~~~scss
--#{$variable-prefix}gutter: $container-padding-x;
--#{$variable-prefix}gutter-x: $container-padding-x;
--#{$variable-prefix}gutter-y: 0;
--#{$variable-prefix}scroll-height: 75vh;
--#{$variable-prefix}breadcrumb-divider: $breadcrumb-divider;
--#{$variable-prefix}table-...-bg: ...;
--#{$variable-prefix}aspect-ratio: null;
~~~

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by WinterSilence** [comment]
@ffoodd this is only collection of missed css values used in bs5 scss files. it's don't change any current values or displayed only in browser's dev tools.

**Comment by mdo** [comment]
Ah okay, it's a feature request for adding more CSS vars. Noted.

**Comment by mdo** [comment]
Oh I see, it's not even a request for more variables, it's about the ones that are used throughout our components. Most of these will not be at the `:root` level as there's no need for them there. Instead the configuration happens at the component/instance level. #32424 will add some more variables though, too.

**Comment by WinterSilence** [comment]
@mdo yes, but
1. custom properties set by reference, for example:
~~~css
.ratio::before {
  display: block;
  padding-top: var(--bs-aspect-ratio);
  content: "";
}
.ratio-1x1 {
  --bs-aspect-ratio: 100%;
}
~~~
2. some vars(gutter for example) uses not in many files

**Comment by WinterSilence** [comment]
@mdo also, need check `feature-exists("custom-property")`, some mobile browsers not so good(
