### ISSUE TITLE
Missed notice: _root.scss is required

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#33357]
In documentation not written that `_root.scss` is required. Also, removing ` @import "root";` from `bootstrap.scss` not generate warning/notice about it.

**Comment by mdo** [comment]
It recompiles fine for me without it included. What error do you see with our npm scripts?

**Comment by WinterSilence** [comment]
@mdo 
>It recompiles fine for me without it included.

Look, you define `--#{$variable-prefix}font-monospace: #{inspect($font-family-monospace)};` in `_root.scss` whats happened if you remove file from list? it's change compiled styles. This file required because this vars uses in other files.

**Comment by ffoodd** [comment]
@mdo Not a compilation issue, "variable" stands for custom properties here 🙂

**Comment by WinterSilence** [comment]
@ffoodd 
> Custom properties (sometimes referred to as CSS variables or cascading variables)

**Comment by WinterSilence** [comment]
@ffoodd yes, only  custom properties _defines by SASS variables_

**Comment by ffoodd** [comment]
This file is not required on the Sass side, you wouldn't be able to compile otherwise. What's missing in our docs is that this file is required for e.g. our reboot which uses font related custom props.

**Comment by WinterSilence** [comment]
@ffoodd some SASS values defines by CSS custom properties, removing file have "backside" effect.

**Comment by WinterSilence** [comment]
@ffoodd i think need something like this:
~~~scss
// `scss/_root.scss`:
...
$root-custom-properties: true;
@function root-css-var($name) {
  @if global-variable-exists("root-custom-properties") == false {
      @error "File 'scss/_root.scss' not required.";
  }
  @return "var(--"+$name+")";
}
~~~
~~~scss
// `scss/_*.scss`
$a: root-css-var("gradient");
~~~

**Comment by mdo** [comment]
We don’t label this as required anywhere in Bootstrap proper, that comment is only in the npm starter project, so closing this out.

**Comment by ffoodd** [comment]
@mdo If I'm right, this is the issue: if we don't include the root files, some of our custom properties won't be set (font families mostly).

It's not required on the Sass side but it is on the CSS one.
