### ISSUE TITLE
4.6: Popper causes the dropdowns to leave the draw area

### ISSUE THREAD

**Issue by dilyanpalauzov** [twbs/bootstrap#33367]
The files https://mail.aegee.org/bs460-popper/b2-mod.html and https://mail.aegee.org/bs460-popper/b2.html are almost identical.  They both load 
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
```
and contain on the right corner a question mark.  When the question mark is clicked a menu opens.  b2.html opens the menu outside of the screen with Firefox, WebKit and Chromium.  b2-mod.html opens the menu within the browser.

The only difference between b2.html and b2-mod.html is that the former loads bootstrap.orig.js and the latter loads bootstrap.mod.js .

bootstrap.orig.js is identical to https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.js . bootstrap.mod.js differs from bootstrap.orig.js by
```diff
--- bootstrap.orig.js	2021-03-15 19:18:30.856838944 +0200
+++ bootstrap.mod.js	2021-03-15 19:20:14.399526326 +0200
@@ -1686,7 +1686,7 @@
           $__default['default'](parent).addClass(CLASS_NAME_POSITION_STATIC);
         }
 
-        this._popper = new Popper__default['default'](referenceElement, this._menu, this._getPopperConfig());
+     //   this._popper = new Popper__default['default'](referenceElement, this._menu, this._getPopperConfig());
       } // If this is a touch-enabled device we add extra
       // empty mouseover listeners to the body's immediate children;
       // only needed because of broken event delegation on iOS

```
which is in the function js/src/dropdown.js:class Dropdown.show() .

That said, the only difference between b2.html and b2-mod.html is, that the latter does not call `this._popper = new Popper__default['default'](referenceElement, this._menu, this._getPopperConfig());`.

Please align bootstrap 4.6 to show the menu within the browser.

**Comment by alpadev** [comment]
The problem isn't caused by Popper but by the fact that you load the content of that dropdown after it got initialized.

If you add
```js
jQuery('#dropdownMenu-help').dropdown('update');
```
after `x.innerHTML = "";` it should work as expected.

**Comment by dilyanpalauzov** [comment]
You are right!  Thank you very much!
