### ISSUE TITLE
"Client Hardcoded Domain" , "Client JQuery Deprecated Symbols", "Client Remote File Inclusion" issues  on bootstrap3

### ISSUE THREAD

**Issue by camuserro** [twbs/bootstrap#33364]
In bootstrap v3 the "Client Hardcoded Domain" and "Client JQuery Deprecated Symbols" have been identified:

1) Client JQuery Deprecated Symbols  in files: 
- bootstrap.js line 946
- bootstrap.min.js line 374
- modal.js line 114

2) Client Hardcoded domain in files: 
bootstrap3-dialog-master/examples/play/tabindex.html	4
bootstrap3-dialog-master/examples/play/tabindex.html	6
bootstrap3-dialog-master/examples/play/tabindex.html	7
bootstrap3-dialog-master/examples/play/tabindex.html	9
bootstrap3-dialog-master/examples/play/reopen-dialog.html	4
bootstrap3-dialog-master/examples/play/reopen-dialog.html	6
bootstrap3-dialog-master/examples/play/reopen-dialog.html	7
bootstrap3-dialog-master/examples/play/reopen-dialog.html	9
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	4
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	6
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	7
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	9
bootstrap3-dialog-master/examples/index.html	4
bootstrap3-dialog-master/examples/index.html	6
bootstrap3-dialog-master/examples/index.html	7
bootstrap3-dialog-master/examples/index.html	9
bootstrap3-dialog-master/examples/play/only-one-dialog.html	4
bootstrap3-dialog-master/examples/play/only-one-dialog.html	6
bootstrap3-dialog-master/examples/play/only-one-dialog.html	7
bootstrap3-dialog-master/examples/play/only-one-dialog.html	9
bootstrap3-dialog-master/examples/play/append-to-div.html	4
bootstrap3-dialog-master/examples/play/append-to-div.html	6
bootstrap3-dialog-master/examples/play/append-to-div.html	7
bootstrap3-dialog-master/examples/play/append-to-div.html	9
bootstrap3-dialog-master/examples/play/button-event.html	4
bootstrap3-dialog-master/examples/play/button-event.html	6
bootstrap3-dialog-master/examples/play/button-event.html	7
bootstrap3-dialog-master/examples/play/button-event.html	9
bootstrap3-dialog-master/examples/play/spinning-icon.html	4
bootstrap3-dialog-master/examples/play/spinning-icon.html	6
bootstrap3-dialog-master/examples/play/spinning-icon.html	7
bootstrap3-dialog-master/examples/play/spinning-icon.html	9

3) Client Remote file inclusion in files: 
bootstrap3-dialog-master/examples/play/tabindex.html	6
bootstrap3-dialog-master/examples/play/tabindex.html	7
bootstrap3-dialog-master/examples/play/tabindex.html	9
bootstrap3-dialog-master/examples/play/reopen-dialog.html	6
bootstrap3-dialog-master/examples/play/reopen-dialog.html	7
bootstrap3-dialog-master/examples/play/reopen-dialog.html	9
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	6
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	7
bootstrap3-dialog-master/examples/play/custom-dialog-id.html	9
bootstrap3-dialog-master/examples/index.html	6
bootstrap3-dialog-master/examples/index.html	7
bootstrap3-dialog-master/examples/index.html	9
bootstrap3-dialog-master/examples/play/only-one-dialog.html	6
bootstrap3-dialog-master/examples/play/only-one-dialog.html	7
bootstrap3-dialog-master/examples/play/only-one-dialog.html	9
bootstrap3-dialog-master/examples/play/append-to-div.html	6
bootstrap3-dialog-master/examples/play/append-to-div.html	7
bootstrap3-dialog-master/examples/play/append-to-div.html	9
bootstrap3-dialog-master/examples/play/button-event.html	6
bootstrap3-dialog-master/examples/play/button-event.html	7
bootstrap3-dialog-master/examples/play/button-event.html	9
bootstrap3-dialog-master/examples/play/spinning-icon.html	6
bootstrap3-dialog-master/examples/play/spinning-icon.html	7
bootstrap3-dialog-master/examples/play/spinning-icon.html	9

Best reagards

**Comment by mdo** [comment]
`bootstrap3-dialog-master` isn't from us.
