### ISSUE TITLE
Browser freezes when using .custom-select or select.form-control

### ISSUE THREAD

**Issue by Liero** [twbs/bootstrap#33378]
I'm experiencing poor performance when a select element with only couple of options uses .custom-select class.

When I open and close the select, the browser freezes for couple of seconds.

1. When I remove 'custom-select' selector, it wont freeze.
2. It freezes only when there is a data table that uses display: grid on the page, although the custom-select is outside the grid's element.

![bug](https://user-images.githubusercontent.com/3494407/111296059-582e5500-864c-11eb-8d3d-6be6396690f5.gif)

The performance recording in chromium edge shows Event Log
![image](https://user-images.githubusercontent.com/3494407/111295628-e6560b80-864b-11eb-8361-6271dcfc569b.png)

What's going on? it is a bug in chromium, or on bootstrap?

My Environment:
- Win10
- Chromium Edge Version 89.0.774.54 and Chrome
- A reduced test case: https://codepen.io/Lieroo/project/full/XwPeNz

**Comment by alecpl** [comment]
I see no problem in Firefox 86 nor Chromium 89.0.4389.82 on Linux.

**Comment by alpadev** [comment]
Can't reproduce this with the test case you posted. It works without problems on my end. Although my dropdown looks different to yours.

![modal](https://user-images.githubusercontent.com/2838324/111453389-d1dd4600-8713-11eb-9ea7-2da6618116a1.gif)

Win10 + Microsoft Edge Version 89.0.774.54

**Comment by Liero** [comment]
Ok, I think this is related to a specific device. I was able to reproduce it on two high end HP Spectre laptops, but each different model. 
I've reported a bug in chromium.
