### ISSUE TITLE
Scrolling breaks when switching a modal window

### ISSUE THREAD

**Issue by Mrreadiness** [twbs/bootstrap#33370]
Bootstrap v5.0.0-beta.

Sample code:

```
currentModal.hide ();
newModal.show ();
```

The windows change, but instead of `<body class = "modal-open">` we get
`<body class>`

**Comment by GeoSot** [comment]
Hey Mrreadiness,
My draft trial, doesn't agree.

![Capture](https://user-images.githubusercontent.com/22406063/111219884-2cc25080-85e1-11eb-9336-1e37697ebd6b.PNG)

Can you provide a sample code that replicates the issue?
(Please correct me, if I am doing something wrong)

**Comment by Mrreadiness** [comment]
Hey! Inside the auth modale, the button that should change the modal.
Through attributes:
```
<a type = "button" class = "text-decoration-none" data-bs-dismiss = "modal" data-bs-toggle = "modal"
data-bs-target = "# modalRestore"> Recover password </a>
```

Or via JS:
`<a type="button" id="restorePassBtn"> Restore password</a>`
```

var authModal = new bootstrap.Modal (document.getElementById ('modalAuth'));
var restoreModal = new bootstrap.Modal (document.getElementById ('modalRestore'));

var restoreBtn = document.querySelector ("#restorePassBtn");

restoreBtn.addEventListener ("click", function () {
     authModal.hide ();
     restoreModal.show ();
})
```

**Comment by Moosjon** [comment]
@GeoSot : I think the problem here is that when toggling modal windows the scrollbar becomes visible instead of remaining hidden.

See https://getbootstrap.com/docs/5.0/components/modal/#toggle-between-modals

Click "Open first modal": scrollbar is **hidden**.
Click "Open second modal": scrollbar is **visible**.
Click "Back to first": scrollbar is **visible**.

The body class "modal-open" seems to disappear when toggling these modals.
And I think that's the problem described here.

**Comment by Mrreadiness** [comment]
Thanks, @Moosjon! I haven't seen this place in the documentation before. A great example of a bug.

**Comment by Jacquesvw** [comment]
Was about to report this issue as well.

**Comment by benben994** [comment]
Facing same issue here

A quick solution: adding .modal-open when switching to second modal

```
const secondModal = document.getElementById('modal-id');
secondModal.addEventListener('shown.bs.modal', (event) => {
     document.body.classList.add('modal-open');
});
```

**Comment by GeoSot** [comment]
@Moosjon  @Mrreadiness  can you confirm the issue again? 
Please try to be explicit about the error. Is a **scrollbar** issue or a **class toggling** issue? 
thanks a lot guys

**Comment by Mrreadiness** [comment]
@GeoSot Everything is fixed in the current release! I close the issue.
