### ISSUE TITLE
Border utilities dont seem to be working with breakpoints

### ISSUE THREAD

**Issue by WilliamStam** [twbs/bootstrap#33379]
windows 10
chrome latest / firefox dev latest
bootstrap 5.0.0-beta2

(apologies if this is already reported. best i could find was someone asking how to remove a border in 4 on breakpoint)

seems the border breakpoints arent working.

````
<section class="bg-white border border-5 p-4">
<div class="p-2 border-md-1">
  show border on md+
</div>
<div class="p-2 border border-md-0">
  hide border on md+
</div>
</section>
````
small
![image](https://user-images.githubusercontent.com/182800/111302583-42c12700-865c-11eb-9653-808248c987ca.png)

large
![image](https://user-images.githubusercontent.com/182800/111302737-6d12e480-865c-11eb-9780-a0b8333b241d.png)

https://jsfiddle.net/583gp9b7/3/

(this is using the cdn for the bootstrap css - https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css)

**Comment by WilliamStam** [comment]
actualy i cant even get 4.6 to do this. so im closing this issue cause my mind is obviously totaly blown and i cant get the most simple things right.

**Comment by WilliamStam** [comment]
updating the _utilities.scss file to include `responsive: true,` for borders makes this work. now just to figure out how to overwrite the border stuff without duplicating the entire utilities file....

**Comment by ffoodd** [comment]
@WilliamStam Start with the docs, everything's explained : https://getbootstrap.com/docs/5.0/utilities/api/#modify-utilities

**Comment by WilliamStam** [comment]
o that worked!

for anyone else trying to get response borders

````
@import "node_modules/bootstrap/scss/functions";
@import "node_modules/bootstrap/scss/mixins";
@import "node_modules/bootstrap/scss/variables";

/* bits we're interested in */
@import "node_modules/bootstrap/scss/utilities";

$utilities: map-merge(
  $utilities,
  (
    "border": map-merge(
      map-get($utilities, "border"),
      (
        responsive:true,
      ),
    ),
    "border-top": map-merge(
      map-get($utilities, "border-top"),
      (
        responsive:true,
      ),
    ),
    "border-end": map-merge(
      map-get($utilities, "border-end"),
      (
        responsive:true,
      ),
    ),
    "border-start": map-merge(
      map-get($utilities, "border-start"),
      (
        responsive:true,
      ),
    ),
    "border-bottom": map-merge(
      map-get($utilities, "border-bottom"),
      (
        responsive:true,
      ),
    ),
  )
);

/* lost interest again */
@import "node_modules/bootstrap/scss/bootstrap";
````

**Comment by mmohajer9** [comment]
> o that worked!
> 
> for anyone else trying to get response borders
> 
> usage would be `.border-md-1`, `.border-top-md-0` etc
> 
> ```
> @import "node_modules/bootstrap/scss/functions";
> @import "node_modules/bootstrap/scss/mixins";
> @import "node_modules/bootstrap/scss/variables";
> 
> /* bits we're interested in */
> @import "node_modules/bootstrap/scss/utilities";
> 
> $utilities: map-merge(
>   $utilities,
>   (
>     "border": map-merge(
>       map-get($utilities, "border"),
>       (
>         responsive:true,
>       ),
>     ),
>     "border-top": map-merge(
>       map-get($utilities, "border-top"),
>       (
>         responsive:true,
>       ),
>     ),
>     "border-end": map-merge(
>       map-get($utilities, "border-end"),
>       (
>         responsive:true,
>       ),
>     ),
>     "border-start": map-merge(
>       map-get($utilities, "border-start"),
>       (
>         responsive:true,
>       ),
>     ),
>     "border-bottom": map-merge(
>       map-get($utilities, "border-bottom"),
>       (
>         responsive:true,
>       ),
>     ),
>   )
> );
> 
> /* lost interest again */
> @import "node_modules/bootstrap/scss/bootstrap";
> ```

This is not actually working for me :(
Any fix on this?
