### ISSUE TITLE
navbar-toggle problem

### ISSUE THREAD

**Issue by Jaider-TT** [twbs/bootstrap#33384]
Hi, how are you.
I am writing this message because i have a problem, i'm creating a web site and i'm usin Bootstrap 5, i'm doing a main menu that when the website is running in a mobile it gets small, and when it gets small the menu is hidden and at that moment apear the toggle button, but when y clic on the button nothing happens, i believe i have the code right so i don't know wath si happening.

I really hope you help me, thank you very much.
(However i attach my code in case i have something wrong)

Code below:

This is the button:
`<button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">`
                `<span class="navbar-toggler-icon"></span>`
            `</button>`

And this is the nav  i want to show:
`<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">`
*another code goes here
`</nav>`

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

Also, make sure you've included the JS.
