### ISSUE TITLE
Responsive classes for offcanvas

### ISSUE THREAD

**Issue by iainhallam** [twbs/bootstrap#33387]
I've got a sidebar down my page that I'd like to move into an offcanvas (looking forward to the full release of v5 to use that), but I'd like it to be "oncanvas" when the page is above a certain width (as a part of the page, rather than overlaid like a shown offcanvas). For an example, see the current version of Slack via the web - as you shrink the window the sidebar becomes an offcanvas element with a button to show it.

![Slack-bar-oncanvas](https://user-images.githubusercontent.com/282030/111393269-54ccb500-86b0-11eb-8123-4918922b417b.png)
> _Sidebar shown on the page_

![Slack-bar-offcanvas](https://user-images.githubusercontent.com/282030/111393278-58603c00-86b0-11eb-9957-dc1fe37c5993.png)
> _Sidebar moves to offcanvas, with toggle button in the header_

I'm imagining something like the existing responsive classes in Bootstrap would be a possible way of using this: `offcanvas`, `offcanvas-sm`, ..., `offcanvas-xxl`. When used with a breakpoint, the element would only have the offcanvas styles applied below the breakpoint.

**Comment by rexarvind** [comment]
Something like Halfmoon sidebar component
<https://rexarvind.github.io/sidebar/>

**Comment by fabiopacheco18** [comment]
I need the same thing like "https://rexarvind.github.io/sidebar/" . Has anyone found a solution?

**Comment by florianlacreuse** [comment]
IMHO this seems like a relevant need, and there have already been several duplicate tickets with this same request. A responsive admin dashboard may need a responsive sidebar, always visible on large screens and the existing offcanvas behavior on small screens. I would use it in many of our client projects.
