### ISSUE TITLE
Modal - Illegal Invocation (selector-engine.js)

### ISSUE THREAD

**Issue by ur-creed** [twbs/bootstrap#33388]
Operating system: Windows & macOS
Browser: Chrome (Version 89.0.4389.82)

When trying to implement a simple modal we are met with the following error:

HTML example modal code from the Bootstrap v5.0 Documentation:
![image](https://user-images.githubusercontent.com/32341553/111408493-bfc7bd00-86ab-11eb-8171-d59a3d485b87.png)

Console error:
![image](https://user-images.githubusercontent.com/32341553/111408695-09180c80-86ac-11eb-90cc-219fdb7f718e.png)
![image](https://user-images.githubusercontent.com/32341553/111408826-3a90d800-86ac-11eb-8839-35c3159b3fb2.png)

**Comment by alpadev** [comment]
You forgot to add `data-bs-target="#SignUpModal"` to that element that triggers it (`data-bs-toggle="modal"`).

**Comment by XhmikosR** [comment]
@ur-creed You should always fill the required issue template info...

@alpadev if you have time, please jump on our Slack :)

**Comment by ur-creed** [comment]
@alpadev I did have that in the element. The issue was that I was missing the '#' in the "data-bs-target". Thanks for the assist! 😄
