### ISSUE TITLE
Automatically publish a nightly or weekly pre-release

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#33393]
There are some nice Actions out there that could help us do this, but my intent is to encourage others to help us test our builds more regularly, helping us to land important changes and communicate what we're working on. Would love if someone wanted to jump in and help us by drafting something or stirring the conversation.

---

**More thoughts:**

- Using same prelease name or tag could be nice? Something like Chrome's `canary`? `nightly`, `weekly`, or `preview` also could work...
- I think this would only really apply to v5 and our `main` branch.
- Automating the changelog and publishing on a cron job feels straightforward enough?

**Comment by WinterSilence** [comment]
[Github remommended](https://github.com/actions/create-release):

* [elgohr/Github-Release-Action](https://github.com/elgohr/Github-Release-Action)
* [marvinpinto/action-automatic-releases](https://github.com/marvinpinto/action-automatic-releases)
* [softprops/action-gh-release](https://github.com/softprops/action-gh-release)
* [ncipollo/release-action](https://github.com/ncipollo/release-action)

**Comment by korki43** [comment]
@mdo should the build be published to npm as well, or only as a github pre-release?

**Comment by mdo** [comment]
Maybe just GitHub? Unless we use the same tag over and over again... not 100% sure.

**Comment by whizzsfe** [comment]
I don't see using the same tag over again. It would make issue tracking hard....
Then again I just use a plain _git pull_ to get current changes.

**Comment by korki43** [comment]
I did a bit of research and it seems like `release-drafter` can not be run in scheduled github actions (release-drafter/release-drafter#783). So we would need to get the changelog from the drafted release. (Or switch to another changelog generator.)

**Comment by korki43** [comment]
@whizzsfe I'm totally with you.
I think it would attract more people to test the nightly version if it was released directly on npm. It's way more comfortable to just install it with npm and have it integrate with all the other modules, than to build the whole project yourself or download it from the releases.
