### ISSUE TITLE
Need add class feature in Tooltip using data attribute.

### ISSUE THREAD

**Issue by shurvir49** [twbs/bootstrap#33408]
Request for a minor feature in Tooltip, It's very honest request to add class using data attribute like **data-tooltip-class="bg-success"**

e.g.
```
<div data-tooltip-class="bg-success" class="btn" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
  Tooltip on top
</div>

```

**Comment by rohit2sharma95** [comment]
There is already an option available named `customClass`. You can use it like: `data-bs-custom-class="🔥"`
https://getbootstrap.com/docs/5.0/components/tooltips/#options
Thats what you want?

**Comment by shurvir49** [comment]
Ok great, It's in Bootstrap version 5, I was asking on version 3-4 . Anyway glad to hear about this. Thanks... 👍 🎉
