### ISSUE TITLE
v3.3.7  modals looses backdrop when used with React

### ISSUE THREAD

**Issue by comm644** [twbs/bootstrap#33416]
Use case:
When we have jsx code like:  
`{!isClosed` && <div id="modal">...</div>}

and try to very fast  open/close modal (faster than animation), then backdrop is not deleted.
Because **this.$backdrop**  already contains created DIV, but we replace reference by new DIV

patch: remove reference before replace it

<pre>
Index: bootstrap.js
===================================================================
--- bootstrap-orig.js
+++ bootstrap.js    
@@ -1105,6 +1105,7 @@
     if (this.isShown && this.options.backdrop) {
       var doAnimate = $.support.transition && animate
 
+      if (this.$backdrop) this.$backdrop.remove();
       this.$backdrop = $(document.createElement('div'))
         .addClass('modal-backdrop ' + animate)
         .appendTo(this.$body)
</pre>

I will pleasure  If somebody will merge patch to main 3.3.7  (migrating to BS4 not so easy)

Alexey.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community).
