### ISSUE TITLE
Html mark with error

### ISSUE THREAD

**Issue by JulioCesarSF** [twbs/bootstrap#33414]
Hello, How are you?

There is a typo error in bootstrap webpage for navs-tabs.
https://getbootstrap.com/docs/5.0/components/navs-tabs/

1- Go to the "And with vertical pills." sub topic.
2- Check the html, There is a extra "a" in a button line there.

From:
`<button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</buttona>`

To:
`<button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</button>`

Regards,

**Comment by ivebeenlinuxed** [comment]
This is fixed in 51c7075

**Comment by ffoodd** [comment]
Yeah docs are only deployed for each release.
