### ISSUE TITLE
Docs: Accordion: "Hidden by default"?

### ISSUE THREAD

**Issue by guettli** [twbs/bootstrap#33427]
![image](https://user-images.githubusercontent.com/414336/112060657-c21f9080-8b5d-11eb-86b9-273a0c0bfee0.png)

Source: https://getbootstrap.com/docs/5.0/components/accordion/

The text is confusing. The first element is not hidden by default, it is visible. The second and third item are hidden by default.

**Comment by rajesh2kumar96** [comment]
# # #33495
