### ISSUE TITLE
Accordion flush have background and borders

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#33422]
since comit   https://github.com/twbs/bootstrap/commit/c198eb6319d63c5414dbe3036ad160bd78d4cf01 Accordion Flush have background and borders?

### **Before:**
![grafik](https://user-images.githubusercontent.com/1651241/111952355-513c9200-8ae5-11eb-8256-0b7e2179eb48.png)

### **After:**
![grafik](https://user-images.githubusercontent.com/1651241/111952435-703b2400-8ae5-11eb-9133-83c1a7863972.png)

**Comment by mdo** [comment]
Fix coming in #33426.
