### ISSUE TITLE
color-contrast() coming in CSS

### ISSUE THREAD

**Issue by ffoodd** [twbs/bootstrap#33423]
Still a draft but supported in some browsers (ATM Safari TP), [`color-contrast()` CSS function](https://drafts.csswg.org/css-color-5/#colorcontrast) will conflict with our internal function using the same name.

Here're a few demos around it:
- [Dave Rupert's one](https://twitter.com/davatron5000/status/1372973144131186689)
- [Adam Argyle's ones](https://twitter.com/argyleink/status/1372634187866378243)

Not sure what issue could appear but definetely something to keep an eye on.  If we manage to use the exact same signature, it might ensure to workaround any trouble.

**Comment by davidscotson** [comment]
I was looking into color contrast in general, and was suprised to find that WCAG is producing some research to highlight some flaws in their contrast calculation (also mentioned by someone on one of the twitter links given above).

I only just learned of the work, but I find the demos very compelling:

https://www.myndex.com/WEB/WCAG_CE14size

https://github.com/Myndex/SAPC-APCA

https://www.myndex.com/SAPC/

I think this may account for some of the reluctance to embrace WCAG contrast guidlines in the past, people perhaps sensing that vome of the numbers didn't quite add up. It might be an interesting excercise to go back and evaluate the original Bootstrap color choices against this new metric to see whether the designer's eye or the WCAG2 algorithm was closer to the WCAG3 suggestions.

Another relevant things pointed out by a twitter response is that the spec chooses the most contrasted color, not the least above some threshold, which I think the current Bootstrap v5 algorithm gets right.

**Comment by mdo** [comment]
Closing out for now since this feels pretty far off. Only other factor here might be embracing more PostCSS plugins to add such support if it makes sense. That seems far off though too: https://github.com/csstools/postcss-plugins/issues/177.
