### ISSUE TITLE
V5 Utilities : Add border-style-hidden

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33441]
**It's a commonly used setting for tables without outer borders**

```
table {
     border-collapse: collapse;
     border-style: hidden;
}
 table td, table th {
     border: 1px solid black;
}
```

**References :** 

https://stackoverflow.com/questions/1257430/how-can-i-apply-a-border-only-inside-a-table
https://developer.mozilla.org/en-US/docs/Web/CSS/border-style
https://getbootstrap.com/docs/5.0/utilities/borders/

**The Utility :**

```
.border-hidden {
     border-style: hidden;
}
```

**Comment by mdo** [comment]
We'll pass on this for now.
