### ISSUE TITLE
offcanvas Toggle doesn't trigger if it has image inside (Event doesn't bubble?)

### ISSUE THREAD

**Issue by Kloptoe** [twbs/bootstrap#33457]
Toggle being picky on whats it on https://gyazo.com/99dca53751898f9714f8347ecafc0ffa

you cannot use images as a trigger it needs text to work......

**Comment by mdo** [comment]
You have to share a live demo, videos don't help us.

**Comment by Kloptoe** [comment]
@mdo https://codepen.io/KT_NETWORK/pen/BapNKMJ

**Comment by dernst-art** [comment]
I had the same problem when using icons in the toggle button. As workaround you can add `data-bs-target` to the element inside the toggle-button/toggle-link also. For your codepen example you have to add `data-bs-target="#user-sidebar"` to your `img` element. For me it worked this way.

**Comment by webglisten** [comment]
Only text triggers working properly, font icons, svg, img are not working as triggers. here is an example: https://mis.gumatech.com/

if you click on the icon it won't open but if you click on the padding of the button it will work.

**Comment by GeoSot** [comment]
I think is a problem of eventHandler here :/

**Comment by Ri-Dearg** [comment]
Hi!
I came across this issue myself and was in a hurry, so I recompiled the JS with this pull request. However, now I find the offcanvas always works the first time. If I close the offcanvas by clicking on the backdrop it continues to work, however if I use the X to close, it won't reopen at all, even on the padding. I don't know if that's useful at all or if I've just jumped the gun, but I thought I'd mention it.

**Comment by weiserhei** [comment]
I came across this by combining the Navbar Example which is putting a `<span>`-icon inside. The workaround mentioned by @dernst-art seems to fix it, thanks!

```html
<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
      <span class="navbar-toggler-icon" data-bs-target="#offcanvasExample"></span>
</button>
```

**Comment by dtrunk90** [comment]
The workaround works for SVG images, too. But you have to add the `data-bs-target` attribute to all sub-elements:
```html
<a class="nav-link" href="#sidebar" data-bs-toggle="offcanvas" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle sidebar">
    <svg class="icon fs-4" data-bs-target="#sidebar">
        <use href="#icon-menu" data-bs-target="#sidebar"></use>
    </svg>
</a>
```

**Comment by themesbrand** [comment]
Hi,

Looks like this is a z-index issue for the Icon, SVG or any other tag you used inside the anchor tag.
Give the `z-index: -1;`  to the Icon, SVG or any other tag you are using, and check it out.

Thank you
