### ISSUE TITLE
v5.0.0-beta3 Utilities : Border Style still missing ??

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33450]
I'm wondering about why the `border style` **utility** still missing even if there is a success **[pull request](https://github.com/twbs/bootstrap/pull/33321)** ?

https://getbootstrap.com/docs/5.0/utilities/borders/

**Comment by ffoodd** [comment]
And why don't you ask on your own PR?

**Comment by devhoussam** [comment]
> And why don't you ask on your own PR? Things may take time, and adding utilities is far from being a priority since the utilities API provide an easy way for anyone to add utilities to their custom build.
> 
> Please wait and ask for review on the PR itself instead of spamming thousands of watchers. Thanks.

Im' not spamming I'm asking
