### ISSUE TITLE
v5: popover examples on Bootstrap website stay open forever

### ISSUE THREAD

**Issue by jakubmuda** [twbs/bootstrap#33455]
Popovers are not working properly in v5-beta3. It happens on Bootstrap website too: https://getbootstrap.com/docs/5.0/components/popovers/#example

Popovers appear as usual, but stay open forever.

Browser: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36 OPR/74.0.3911.232`

![popovers](https://user-images.githubusercontent.com/40349972/112230851-010c1f80-8c0c-11eb-8292-cc40729f1168.png)

**Comment by XhmikosR** [comment]
They are supposed to stay open until you close them?
