### ISSUE TITLE
Bootstrap modal no dark overlay on iOS 14.4.1

### ISSUE THREAD

**Issue by petia182** [twbs/bootstrap#33467]
It seems like the dark overlay doesn't work on iOS 14.4.1 Safari
I tested the modal directly from the bootstrap demo [here](https://getbootstrap.com/docs/4.0/components/modal/#live-demo) - screenshot below.

- Operating system and version  - iOS 14.4.1
- Browser and version - Safari 14

![IMG_398422C88B37-1](https://user-images.githubusercontent.com/22330133/112369961-7e579300-8ce5-11eb-9e05-242e0bd508ba.jpeg)

**Comment by XhmikosR** [comment]
You are using an unsupported version, please try with the latest 4.6.0 or 5.0-beta3.

* https://getbootstrap.com/docs/4.6/components/modal/#live-demo
* https://getbootstrap.com/docs/5.0/components/modal/#live-demo

**Comment by petia182** [comment]
Thank you very much. 
On 4.6 it works!
