### ISSUE TITLE
V5 Offcanvas Header : dropdown-menu with w-100 sizing issue

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33464]
I'm trying to add the brand logo as **[dropdown](https://getbootstrap.com/docs/5.0/components/dropdowns/)** inside the **[Offcanvas](https://getbootstrap.com/docs/5.0/components/offcanvas/)** header.

but I get some issues while I add the `w-100` Utility to **dropdown-menu** to create full width.

**Here is the Issue :** 

![Image](https://i.imgur.com/Uc7gXjz.png)

**What I expected :**

![Image](https://i.imgur.com/EM4W0C9.png) 

Live Example in **[codepen.io](https://codepen.io/themes4all/pen/BapNMXm)**

**Just for notice** what I want to achieve is work great in **Modal example** but in **Offcanvas** it bring some issues.

![Image](https://i.imgur.com/V1WxxBh.png)

I made some changes in **[live example](https://codepen.io/themes4all/pen/BapNMXm)** I add the **Modal example** to it.

**Comment by mdo** [comment]
Looks like your modal example is already using `data-bs-offset`, so adding that to the offcanvas one with `data-bs-offset="-18,18"` makes it work like the modal. I think that covers the situation here, so closing out!
