### ISSUE TITLE
V5 Offcanvas : Add offcanvas-footer

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33461]
```
  <div class="offcanvas-footer">
    ...
  </div>
```

```
.offcanvas-footer{
    padding: 1rem 1rem;
    border-top: 1px solid #dee2e6;
}
```

**Comment by mdo** [comment]
Punting on this for now. Doesn’t really add much value as-is without implied contents of the footer. Unlike the header, which houses an explicit title and escape hatch.

**Comment by reqwire** [comment]
why was this punted? this should be a feature.

**Comment by mdo** [comment]
Offcanvas was added awhile ago. We just didn't add a footer. You can do that with utilities. https://getbootstrap.com/docs/5.2/components/offcanvas/

**Comment by wellol** [comment]
That should do it:

`
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">Offcanvas right</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body p-0">
        <div class="d-flex flex-align-start flex-column h-100 w-100 ">
            <div class="w-100 h-100 mb-auto overflow-y-auto p-3 ">
                
              OFFCANVAS BODY<br>
                
            </div>

            <div style="max-height: 60px; min-height: 60px" class="d-flex justify-content-center bg-light order-2 w-100">
                <div class="align-self-center">
                    <button type="button" class="btn btn-primary btn-sm">FOOTER</button>
                </div>
            </div>

        </div>
    </div>
</div>`

**Comment by ianhughesfs** [comment]
> That should do it:
> 
> https://codepen.io/wellol/pen/oNEarzR

Thanks for this!  

Just an observation that might be helpful to others but this only works when the offcanvas modal is fixed.  The footer gets covered up if you allow vertical scrolling. (long list of options, etc.)

![GH](https://user-images.githubusercontent.com/93460821/176786499-6e3d26b2-d521-4188-9483-a73f57fdc68b.jpg)

**Comment by vidalweb** [comment]
Offcanvas Footer 
The solution is here, for those who need it. It was tested with version 5.3 Bootstrap.

link:
[https://codepen.io/sfmartin/pen/KKGBqrp](url)

**Comment by PPaivank** [comment]
@vidalweb theres nothing there

**Comment by luukskeur** [comment]
Of course, in the end, everything is possible with utilities.

I could see a scenario where a footer is useful. For example: in an e-commerce website where the (mini)cart is an offcanvas with an offcanvas-footer which houses the cart summary/buttons.

Shopware (6.5) has their own version applied: https://github.com/shopware/platform/blob/6.5.0.0/src/Storefront/Resources/app/storefront/src/scss/component/_offcanvas.scss#L40-L44

**Comment by vidalweb** [comment]
> @vidalweb theres nothing there

Link: 
https://codepen.io/sfmartin/pen/KKGBqrp
