### ISSUE TITLE
V5 Offcanvas: Opening link can't have children

### ISSUE THREAD

**Issue by dgsiegel** [twbs/bootstrap#33477]
Using the example given in the docs works fine:

```
<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
  Link with href
</a>
```
However adding classes to the content of the link, breaks the offcanvas and it won't open:

```
<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
  Link with href <em>clicking here will not work</em>
</a>
```

However clicking on the first part of the text will still work.

This also happens for `<button>`

**Comment by TangLiang** [comment]
i have the same issue,
![image](https://user-images.githubusercontent.com/486703/112489993-f2636b00-8db9-11eb-99d1-2baf571cc194.png)
when i try to use svg in html not as office use as background.it's break the offcanvas,it's opened and auto closed.

so try to use background imgage to solved this,but it's a bug.

**Comment by devhoussam** [comment]
Duplicate [#33457](https://github.com/twbs/bootstrap/issues/33457)

**Comment by GeoSot** [comment]
Thank you guys for reporting this. It is very helpful for to know and fix any issues. 

I close it as duplicate
