### ISSUE TITLE
V5 Offcanvas : a problem with the button when clicking on it more than once to open the offcanvas

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33470]
I found a problem with offcanvas while trying to open it more than once I click multiple times to the button but in second time instead of displaying the offcanvas it display the background overlay.

Here is a live preview for more details try to click many times on button and you will see what I'm talking about.

[Live preview](https://codepen.io/themes4all/pen/bGgVeBM)

[Video Preview](https://streamable.com/kowq1j)

**Comment by GeoSot** [comment]
Thank you @devhoussam for your report
Unfortunately if you replace the icon with text, works fine.
This make me believe it is EventHandler's issue. Same as #33457
