### ISSUE TITLE
V5 Offcanvas/Modal : Open the Offcanvas/Modal using switches

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33473]
I hope the **BS core team** try to support the possibility opening of **[Offcanvas](https://getbootstrap.com/docs/5.0/components/offcanvas/)** & **[Modal](https://getbootstrap.com/docs/5.0/components/modal/)** using **[Switches](https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches)**.

**something similar to this example :**

[codepen.io](https://codepen.io/themes4all/pen/jOybvRr)

**Comment by alpadev** [comment]
:-1: you can implement this by yourself if you really need this.

**Comment by rohit2sharma95** [comment]
Agree with @alpadev here, this feature is not needed really IMO.

/CC @XhmikosR
