### ISSUE TITLE
V5 Alerts Component : Add the icon space

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33480]
**[Live Example](https://codepen.io/pen/define/)** 

![Image](https://i.imgur.com/Aq0cCVa.png)

**Comment by rohit2sharma95** [comment]
Your example link is not working, can you please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details. :slightly_smiling_face:

**Comment by devhoussam** [comment]
thank you but I already push a PR about this feature **[#33485](https://github.com/twbs/bootstrap/pull/33485)**
