### ISSUE TITLE
v5-beta3: Closure Compiler fails on bootstrap.bundle.js

### ISSUE THREAD

**Issue by haengle** [twbs/bootstrap#33484]
Our projects use composer & apache ant with Closure Compiler v20210202 to build our JS files. Upgrading from beta2 to beta3 results in this compiler error: 
![Screen Shot 2021-03-26 at 10 18 15 AM](https://user-images.githubusercontent.com/68566446/112653827-ce854100-8e1c-11eb-87c2-da9851625601.png)

The JS compiles fine with the beta2 file. I have tried changing the beta3 JS file to the other files in the /dist/js folder with the same compiler error. Please advise, thank you

**Comment by alpadev** [comment]
With beta3 we changed some compatibility settings to reduce the overhead that comes from supporting some legacy browsers. This means that parts of our code are not transpiled anymore from es6 into es5.

According to [this wiki entry](https://github.com/google/closure-compiler/wiki/ECMAScript6):
> If you find that the Closure Compiler does not support your favorite feature, you can file an issue, but please be aware that supporting the entire ECMAScript specification is a non-goal for the Closure Compiler.

So looks like Closure Compiler got a problem with our code or particularly es6 object destructuring in that case.

Pinging @XhmikosR for any thoughts about this.

Meanwhile, you can try your luck and file an issue [here](https://github.com/google/closure-compiler/issues).

**Comment by haengle** [comment]
Update: I changed our language_out setting from ECMASCRIPT_2016 to ECMASCRIPT_2018 and the beta3 code compiled correctly. Thanks for checking in to this!
