### ISSUE TITLE
Opacity  classes (.opacity-25 opacity-50 .opacity-75) don't work

### ISSUE THREAD

**Issue by vnikolay** [twbs/bootstrap#33483]
Opacity classes (.opacity-25 opacity-50 .opacity-75) don't work.
I downloaded last bootstrap (beta-3).
I need to apply opacity to div. But there is no opacity classes in compiled CSS file.

**Comment by jonnysp** [comment]
As far as I know, there has never been an opacity class.
On the [documentation page](https://getbootstrap.com/docs/5.0/utilities/api/#api-explained) there is only an instruction for the implementation of one.

**Comment by vnikolay** [comment]
> As far as I know, there has never been an opacity class.
> On the [documentation page](https://getbootstrap.com/docs/5.0/utilities/api/#api-explained) there is only an instruction for the implementation of one.

Thank you, I didn't know. That's sad.

**Comment by devhoussam** [comment]
you can use your **Utility API** to add that

**Comment by ffoodd** [comment]
Closing per latest comments. As for other utilities, we encourage you use the utility API to add them.

**Comment by alvinkonda** [comment]
I'm trying to use the Utility API to create some opacity classes as stated on the docs, but it is not working. It used to work fine on the Beta 2 though. 

```
$utilities: map-merge(
    $utilities, (
        "opacity": (
            property: opacity,
            values: (
                0: 0,
                25: .25,
                50: .5,
                75: .75,
                100: 1,
            )
        )
    )
);
```

**Comment by alvinkonda** [comment]
... and I agree, the opacity classes should be a core feature. There are all of these utility classes like a rounded, shadow, etc, but none for opacity, which I suppose is used very often.

**Comment by mdo** [comment]
I’m down to revisit. Feel like there have been a good number of these requests for opacities. Wondering if there’s something we can do there that also considers any CSS variables?

**Comment by alvinkonda** [comment]
The funny thing is that the first example on the docs for the utilities API is in fact for opacities, and in fact they don't exist in BS.

I'm not sure what relatation you have in mind for opacities and css variables... 

What i think is important is that it should be given more importance on the utility classes, they are so handy, not that i prefer Tailwind though. I don't want to add a third monitor just to view my classes. Lol.

**Comment by devhoussam** [comment]
> The funny thing is that the first example on the docs for the utilities API is in fact for opacities, and they don't exist in BS.
> 
> I'm not sure what relatation you have in mind for opacities and css variables...
> 
> What i think is important is that it should be given more importance on the utility classes, they are so handy, not that i prefer Tailwind though. I don't want to add a third monitor just to view my classes. Lol.

And I am in what you said the BS team should care more about the Utilities Classes.

**Comment by mdo** [comment]
Ah yeah, I can see the confusion for sure there. https://getbootstrap.com/docs/5.0/utilities/api/#api-explained was meant to reference how you could add utilities, but it has evolved since then and definitely doesn't anymore (that's further down the page now).

I'm in favor of bringing these utilities into `main` for v5 or v5.1. Anyone want to open the PR?
