### ISSUE TITLE
V5 beta3 - deselecting button group checkbox on ios safari doesn't work.

### ISSUE THREAD

**Issue by alexgodin** [twbs/bootstrap#33481]
On any mobile browser (I just checked in latest iPhone Chrome on iPhone SE 2020) deselecting a checkbox inside a button group doesn't deselect until you re-select another component. We also see this on Android.

To reproduce open this codepen on an iPhone: https://codepen.io/alexgodin/details/gOgPRpL Select an option and then try to deselect it.

**Comment by rohit2sharma95** [comment]
That is unselected in real, just the color is there because of the hover rule. :thinking:
And when you click somewhere else, that color is removed because the hovered style are removed then.

/CC @patrickhlauke

**Comment by patrickhlauke** [comment]
@rohit2sharma95 indeed. see also https://github.com/twbs/bootstrap/issues/31149

**Comment by alexgodin** [comment]
Hey! I'm looking for a workaround in the interim. Will a pure css fix like this work?

```
@media (hover: none) {
  div:hover { background-color: inherit; }
}
```

Or is there something else I should do?

**Comment by patrickhlauke** [comment]
i wouldn't rely on `hover` queries https://css-tricks.com/interaction-media-features-and-their-potential-for-incorrect-assumptions/

might be worth tweaking/patching the core styles to just suppress the hover and possibly focus background change altogether.

**Comment by alexgodin** [comment]
Hey all, is there any interest/plan to fix this? Or should I work on my own fix locally?

**Comment by amarinediary** [comment]
Noticed that issue too. @alexgodin @patrickhlauke @rohit2sharma95 Issue can be seen straight from the [Bootstrap Website Checks & Radios, Outlined styles](https://getbootstrap.com/docs/5.0/forms/checks-radios/#outlined-styles). and from the [Checkbox & Radio Button Groups](https://getbootstrap.com/docs/5.0/components/button-group/#checkbox-and-radio-button-groups).

A working workaround to the current behavior while waiting for an official fix is to use the  [`:not()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) pseudo-class combined to the [`:checked`](https://developer.mozilla.org/en-US/docs/Web/CSS/:checked) pseudo-class and finally the [`:focus`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) pseudo-class.

```
/**
 * Fix for button Bootstrap v5.0.0-beta3 checkbox and radio button groups and  form checkbox and radio outlined styles.
 *
 * @link https://github.com/twbs/bootstrap/issues/33481
 */
.btn-check:not(:checked):focus + .btn-outline-primary {
  background-color: inherit !important;
  color: inherit !important;
}
```

**Comment by alexgodin** [comment]
Hey Amarine! I just tried your codepen on my iphone (SE 2020, latest software) and the issue persists. Are you seeing it o your phone?

**Comment by amarinediary** [comment]
@alexgodin Indeed the :active state was also messing up the behavior, I've updated the Codepen and the answer. It should work properly. Also, thanks to you, I realized that the Chromium device emulator isn't displaying accurate behavior.

**Comment by alexgodin** [comment]
Got it! This does fix the behavior, but it doesn't hide the checkboxes.

![IMG_9E8F70C0441C-1](https://user-images.githubusercontent.com/405271/115306973-9250b200-a136-11eb-9c22-56308e0d5c14.jpeg)

**Comment by amarinediary** [comment]
The checkbox is only displayed for the codepen demo. @alexgodin

**Comment by alexgodin** [comment]
🎊 🎊 
It works!!!

Big ups to @amarinediary -> the hero we needed!

**Comment by amarinediary** [comment]
This issue is back in 5.2, my initial fix isn't working anymore.

**Comment by patrickhlauke** [comment]
This *should* finally be resolved more thoroughly here https://github.com/twbs/bootstrap/pull/37026 - taking https://deploy-preview-37026--twbs-bootstrap.netlify.app/docs/5.2/forms/checks-radios/#toggle-buttons and https://deploy-preview-37026--twbs-bootstrap.netlify.app/docs/5.2/components/button-group/#checkbox-and-radio-button-groups for a spin in Safari/iOS, it seems to behave correctly (without styling sticking) - and it makes it clearer even for mouse users.
