### ISSUE TITLE
v5-beta3: Dropdown not working on Ipad/Iphone devices using Safari browser

### ISSUE THREAD

**Issue by honey-swellfox** [twbs/bootstrap#33490]

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
