### ISSUE TITLE
Ajaxify Bootstrap 5 scroll top conflict in BS CSS help needed

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap#33504]
Hi,

Test website: https://www.yourweblab.nl/scroll-top/index.html (this test site contains only BS5 CSS and no BS5 JavaScript is added!)

We have been using https://github.com/arvgta/ajaxify and Bootstrap 4 for years without a problem. But now with Bootstrap 5 there seems to be a scroll problem that is caused by something in the CSS of Bootstrap 5. At first we looked at the Javascript of course, but even when we take out all BS5 JavaScript the scroll top problem is still there.

To replicate the issue use Firefox because in that browser you see the most artifacts:

* Open the test page  https://www.yourweblab.nl/scroll-top/index.html
* Scroll down the **Large Page** till the bottom of the page
* Click on  **Smaller Page** (that is a smaller page indeed)
* See the page only scrolled up half way
* Now when you click from the **Smaller Page** to the larger page all is normal again

This problem only occurs when you click from a larger page to a smaller page. 

Removing the BS5 CSS makes it work normal again.

We also tried to shut off the scroll top part of Ajaxify thinking that BS5 would take over but that is  not the case.

Hope someone who is reading this knows what's going on in BS5 CSS that can cause this?

Regards & Thanks,

David

**Comment by arvgta** [comment]
Hi,

I am the author of Ajaxify and would like to confirm that it would be great to fix this issue.
We would be very eager to provide another appropriate switch especially for these kind of scenarios within Ajaxify's settings.
Thanks for your excellent work as well and


Regards,
Arvind

**Comment by ffoodd** [comment]
One major change regarding scroll on the CSS side is the addition of `scroll-behavior: smooth;` on `:root`. Would you mind trying to drop it (setting `$enable-smooth-scroll` to `false` in your Sass build, or simply using your devtools) to confirm it relates to this property?

FYI, it's set in `_root.scss`, both behind a configuration variable and a media-query checking for user preference: https://github.com/twbs/bootstrap/blob/main/scss/_reboot.scss#L31

**Comment by Allmedialab** [comment]
@ffoodd,

That solves the problem many thanks!!!!

Only strange thing is that I had to remove
`html {
scroll-behaviour: smooth;
}`
From the HTML my self. When I add:
`enable-smooth-scroll: false !default`
to my bootstrap_variable_overrides.scss or
to my custom:  _variables.scss
My build system doesn't stop from spitting out in the dist CSS
`html {
scroll-behaviour: smooth;
}`

Regards & Thanks again,

David

**Comment by ffoodd** [comment]
You should not add the `!default` flag to override a value; I think that's the reason. Could you confirm?

**Comment by Allmedialab** [comment]
Removing the !default flag doesn't change a thing. Even when I set:
enable-smooth-scroll: false !default in the original Bootstrap 5 _variables.scss and compile it doesn't remove anything from the CSS.

**Comment by ffoodd** [comment]
Based on your previous comment, aren't you adding  CSS other than Bootstrap?

We currently set `scroll-behavior: smooth;` on `:root`, not `html` —which ends up as the same element in HTML, but not the same selector in CSS— but your comment suggests it's applied to `html` in your case.

BTW the first link you shared seems to not use `scroll-behavior` anymore.

**Comment by Allmedialab** [comment]
To be clear I had to remove:
 `html { scroll-behaviour: smooth; }`
manually from the CSS to solve the problem.

How do I achieve the same with SASS?
Obviously `enable-smooth-scroll: false' doesn't remove or change that part of the CSS!?

Can that part only be overwritten by CSS?

The demo in this post got the above CSS removed by me manually from the CSS.

**Comment by Allmedialab** [comment]
Yes it works now! Thanks very much for helping to solve this issue!
