### ISSUE TITLE
Mistake in the Documentation for tab shown event.

### ISSUE THREAD

**Issue by iaroslavglodov** [twbs/bootstrap#33509]
At the end of the [Navbar documentation](https://github.com/twbs/bootstrap/edit/main/site/content/docs/5.0/components/navs-tabs.md), there is an example of weird behavior. When using the same code only the first tab event is treigerring. If using as `tabEl` parent `<ul>` element it works as expected.

```js
var tabEl = document.querySelector('button[data-bs-toggle="tab"]')
tabEl.addEventListener('shown.bs.tab', function (event) {
  event.target // newly activated tab
  event.relatedTarget // previous active tab
})
```

—— macOS 11.2.3, Chrome Version 89.0.4389.90 (Official Build) (arm64)

**Comment by yunweneric** [comment]
Hello I will like to fix this issue.
