### ISSUE TITLE
Beta 3 SUCKS

### ISSUE THREAD

**Issue by unpococloco** [twbs/bootstrap#33506]
Just updated my development to beta 3 and had to fall back to 2. The CSS in beta3 completely broken EVERYTHING in my sites. Was there a major syntactical difference I wasn't aware of? If so, why was it introduced in the 3rd beta instead of in a 6.0 release?

**Comment by ffoodd** [comment]
Either start with [the dedicated changelog](https://github.com/twbs/bootstrap/releases/tag/v5.0.0-beta3) or   try to provide a reduced test case.

Or stay stuck.

**Comment by unpococloco** [comment]
Actually, I suck in this case. 

As I was building my test case for you, I realizedI had simply changed the beta number in the old <LINK> and <SCRIPT> calls to your CDN, forgetting the sha= argument would have to be different between the 2 versions.

Once I changed out the entire tag contents, everything worked as advertised. 

My humblest apologies for shooting off my mouth!
