### ISSUE TITLE
V5 Beta 3 - Floating labels bad overflow

### ISSUE THREAD

**Issue by andimg93** [twbs/bootstrap#33502]
Floating labels are buggy in Bootstrap 5 Beta 3:
The textarea content is overlapping the label, please refer to the attached screenshot from the official Bootstrap 5 documentation page:
[![image.png](https://i.postimg.cc/TPpwnf0Y/image.png)](https://postimg.cc/WDcTvRxQ)

**Comment by andimg93** [comment]
Searched again for that issue and found the following: https://github.com/twbs/bootstrap/issues/32800 - Should be it, already known since 14. January

**Comment by mdo** [comment]
Closing as a dupe
