### ISSUE TITLE
Problems printing in Beta 3

### ISSUE THREAD

**Issue by unpococloco** [twbs/bootstrap#33508]
#33507 was closed prematurely without giving me a chance to respond informing you they were not the culprit.

Removed all deprecated print classes from HTML tags. 

Identical results. 

This is still a bug in 5 Beta

And if the print classes have been deprecated, why are they still in the 5 Beta documentation? Did you think I just pulled them out of thin air?

**Comment by ffoodd** [comment]
There are no print styles in v5, and we won't provide support for print.

If you found any mention of print styles in v5 docs, please report them so that we remove them.

**Comment by unpococloco** [comment]
Obviously, you did not see my apology in #33506. Please read it and drop the obvious hostility? I need help here!

Im not asking you to support print in Bootstrap as far as features are concerned. I'm asking you to fix the problems with Bootstrap which are causing the reported problem all of which has ZERO to do with print classes or any other feature or lack thereof. 

Bootstrap should be media transparent. If I'm printing a page, Bootstrap should not affect the output in any way. Point of fact: it does.

As for the documentation issue, I just did report them. They're in a database somewhere on your end.

**Comment by ffoodd** [comment]
As I said, Bootstrap does not provide print styles so it doesn't affect print output.

However you added your own set of styles, both for screen and print, and browsers all have their own default print stylesheets that may mess up you expectations.

Print styles are a hard topic, as CSS in emails can be.

Reading your first issue again, I don't even know what's the bug you're pointing and what are your expectations. 

Please try to provide a reduced test case (using CodePen for example) to ease both the discussions and the diagnosis.

**Comment by unpococloco** [comment]
Stripping out all Bootstrap code from the page and clearing the cache produces the same problem, so I have to concede this is not your problem to solve. Thanks anyway!
