### ISSUE TITLE
Printing Tables Issues in Beta 2

### ISSUE THREAD

**Issue by unpococloco** [twbs/bootstrap#33507]
There is a serious bug when attempting to print HTML tables in Betas 2 & 3.

I am trying to create a printer-friendly means of for our students to print a hard-copy of their personal information on file with our university.

The <BODY> section of the page's HTML is as follows:
`	<body>
		<div id="CONTAINER" class="container-fluid">
			<div class="row d-lg-block">
				<div id="HEADER" class="col-lg-6 offset-lg-3 col-md-12">
					<img src="/_globals/images/logos/20th_anniversary_lcu_logo_and_logotype_grayscale.jpg" alt="LCU Logo & Logotype"> 
					<h2><?php echo PAGE_TITLE . BR . PAGE_SUBTITLE; ?></h2>
				</div>
			</div>

			<div id="PERSON" class="row d-lg-block">
				<div class="col-lg-6 offset-lg-3 col-md-12">
					<div class="table-responsive">
						<table class="table table-bordered border-dark d-print-table">
							<caption>PERSONAL INFORMATION</caption>
							<tbody>
<?php echo $person_tbody; ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		
			<div id="CAMPUS" class="row d-lg-block">
				<div class="col-lg-6 offset-lg-3 col-md-12">
					<div class="table-responsive">
						<table class="table table-bordered border-dark d-print-table">
							<caption>CAMPUS INFORMATION</caption>
							<tbody>
<?php echo $campus_tbody; ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>

			<div id="BUTTONS" class="row d-print-none">
				<div class="col-lg-6 offset-lg-3 col-md-12">
					<button id="PRINT" type="button" class="btn btn-default float-end" tabindex="32765"><?php insertSvgSprite( PRINT_ICON,  BUTTON_CLASS ); ?>Print</button>&nbsp;&nbsp;
					<button id="CLOSE" type="button" class="btn btn-link    float-end" tabindex="32766"><?php insertSvgSprite( CANCEL_ICON, BUTTON_CLASS ); ?>Close</button>
				</div>
			</div>
			<footer>&nbsp;</footer>
		</div>
	</body>
`
The screen-only CSS is as follows:
`
body {
	background-image:  none;
}

#HEADER {
	display: 			block;
	margin-bottom: 	18pt;
}

#HEADER img {
	display: 			block;
	width: 			100%;
	margin: 			12pt auto 	!important;
}

#HEADER h2 {
	display: 			block;
	text-align: 		center 		!important;
	color: 			#000000 	!important;
	font-weight: 		700;
	font-size: 		24pt;
	margin-bottom: 	12pt;
}

#PERSON {
	margin-bottom: 	36pt 			  !important;
}

table {
	border: 			3pt solid #000000 !important;
}

tr {
	border-bottom: 	2pt solid #000000 !important;
}

th {
	padding-right: 	 9pt				  !important;
	border-right: 		 2pt solid #000000 !important;
	background-color:  #DDDDDD		  !important;
}

td {
	padding-left: 		9pt !important;
}

caption {
	caption-side: 	top;
	padding-bottom: 	14pt;
	padding-bottom: 	9pt;
	font-size:		18pt;
	font-weight: 		700;
	text-align: 		center;
	color: 			#000000;
}

tr {
	border-top: 		1.5pt solid #000000;
	border-bottom: 	1.5pt solid #000000;
}

.btn {
	margin: 			0			!important;
}

#BUTTONS {
	padding-top: 		12pt		!important;
}

footer {
	border: 			none;
	height: 			48pt;
}
`

The print-only CSS is identical except for the following 3 rules:

`body {
	width:				8.5in;
	height:				11in;
	margin:				.5in 1in 1in 1in;	
	background-image: 	none;
}	/* end body rule */

#PERSON {
	margin-bottom: 		36pt 	!important;
       page-break-after: 		always 	!important;
}

#BUTTONS, footer {
	display: 				none;
}
`
It's rendered output in the browser window is as shown in this screenshot:

![Safari Screenshot 2021-03-29 11 52 55](https://user-images.githubusercontent.com/61477993/112887753-65a20100-9088-11eb-989b-a97174e01a68.png)

However, whenever I try to print this page to a printer and/or save it as a PDF, I get the following (the attached is a JPG of the PDF output (the black bar is the page break, not part of the print):

![Sample Printout-1](https://user-images.githubusercontent.com/61477993/112887774-6d61a580-9088-11eb-8706-b7cf57102a61.jpg)

Thanks!

**Comment by unpococloco** [comment]
After successfully getting Beta 3 running, the symptoms are identical

**Comment by ffoodd** [comment]
v5 [dropped support for print styles since the very first alpha](https://getbootstrap.com/docs/5.0/migration/#v500-alpha1). If you want specific styles for print, you'll have to implement them by yourself.
