### ISSUE TITLE
Cannot read property 'closest' of undefined at Popover._setListeners

### ISSUE THREAD

**Issue by AnthonySharamitaro** [twbs/bootstrap#33500]
**OS and Version:** Windows 10 (64-bit)
**Browser and Version:** Chrome 89
**Suggested and Working Fix:** https://codepen.io/anthonysharamitaro/pen/dyNXpOp

Bootstrap code is version 5 from latest download this evening as beta-3 and unmodified except the fixed code.  @twbs-grunt, please recompile and add the fix so that _datalists work with popovers_.

**Attachments:**
![1](https://user-images.githubusercontent.com/1290515/112741404-92083100-8f53-11eb-92b9-4ee207a47f8c.png)
![2](https://user-images.githubusercontent.com/1290515/112741405-92a0c780-8f53-11eb-80ee-0bd6faf63f47.png)

**Comment by mdo** [comment]
Not seeing any errors on my end when viewing this. Closing out for now, but please share more details if you find them.
