### ISSUE TITLE
Floating labels: allow to force raised state / add support for input type="file"

### ISSUE THREAD

**Issue by caub** [twbs/bootstrap#33523]
When using https://getbootstrap.com/docs/5.0/forms/floating-labels/, the label is raised either if the input is focused or if the input has a value

It'd be interesting to still force the label in this position, using a class or attribute, maybe

```html
<div class="form-floating">
  <input class="form-control" id="floatingInput" type="file" style="opacity:0;position:absolute;left:0">
  <i class="far fa-plus"></i>
  <label for="floatingInput" className="raised">Photo</label>
</div>
```

My use case is a form where I use floating labels, but one of the field is a type="file" input, and in that case, I want the label to be always raised

**Comment by mdo** [comment]
Closing out for now as this example was solved and I don't plan to add support for file inputs at this time.
