### ISSUE TITLE
V5 Navbar & Dropdowns : Add Multi-level Dropdown Menu

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33525]
![Image](https://www.codehim.com/wp-content/uploads/2019/02/Bootstrap-4-multilevel-dropdown-menu-on-hover.jpg)

![Image](https://i.stack.imgur.com/CaK3B.png)

https://getbootstrap.com/docs/5.0/components/dropdowns/
https://getbootstrap.com/docs/5.0/components/navbar/

**Comment by mdo** [comment]
#27659
