### ISSUE TITLE
Carousel with cards

### ISSUE THREAD

**Issue by sebaherrera** [twbs/bootstrap#33533]
This type of component is useful for e-commerce websites, but there isn't a very straightforward way to achieve it by merging Bootstrap carousel and cards. 

Alternatives considered: 

* There are lots of javascript + CSS hacks, but they have so many issues with responsiveness or cannot be applied to an unknown number of cards (e.g: generated by PHP).
* Slick Slider: not-so compatible with Bootstrap cards and needs jQuery.
* Flickity: very compatible and vanilla-based, which makes it a good example for integrating the feature in Boostrap.
* Example of [this discussion](https://github.com/twbs/bootstrap/discussions/33425) just hides two cards on mobile.

Thank you.

**Comment by mdo** [comment]
You can put whatever you want in the carousel items—this should be all doable right now :).

**Comment by sebaherrera** [comment]
I'm aware, but there isn't an easy way to show multiple cards at once, since you have to wrap it into a slide
