### ISSUE TITLE
Collapsible navs

### ISSUE THREAD

**Issue by sebaherrera** [twbs/bootstrap#33534]
Hi. It would be very nice to hace a feature that makes nav lists work in similar way than navbars, in regard to responsiveness.

For example:

* Mobile breakpoint: show a button that works like collapse.
* Desktop breakpoint: expanded like current nav examples.

Alternative considered: 

1) Wrap nav into a `collapse`
2) Create a duplicated header, with and without button, using `d-none` and `d-flex` for the desired breakpoints
3) Apply following CSS hack to `collapse` class in desktop breakpoint to avoid collapsing:  

`display: block; height: auto!important; visibility: visible`

Thank you!

**Comment by mdo** [comment]
We have collapsible navbars already :).
