### ISSUE TITLE
Created offcanvas component for navbar collapse example

### ISSUE THREAD

**Issue by craftwerkberlin** [twbs/bootstrap#33531]
Hello,

the new offcanvas is a stand-alone component, but it should be able to display collapsed navbar as well. Created a navbar example which shows menu <992px (class navbar-expand-lg) in offcanvas component instead of the top open default navbar. navbar-expand{-sm|-md|-lg|-xl|-xxl} class can be used to set the breakpoints.

Demo: https://examples.bootscore.me/bootstrap-offcanvas-navbar/
Code: https://github.com/craftwerkberlin/bootstrap-offcanvas-navbar

**Comment by devhoussam** [comment]
I take a look to preview example it look like a good idea try to create a pull request.

**Comment by craftwerkberlin** [comment]
@devhoussam @mdo I created a PR https://github.com/twbs/bootstrap/pull/33537, so this Issue can be closed.

Thank you
