### ISSUE TITLE
offcanvas don't remove events on dispose (trigger js error on document click)

### ISSUE THREAD

**Issue by markusilmer** [twbs/bootstrap#33535]
I create and destroy (use `dispose()`) Offcanvas with JS. After destroy i get JS errors on every click

Here is a simple Codepen example
https://codepen.io/maz1989/pen/abppYVL

**Comment by GeoSot** [comment]
Will be fixed with #33535

[Demo codepen](https://codepen.io/GeosSV/pen/GRryNze)
