### ISSUE TITLE
Buttons and other html tags in popover body

### ISSUE THREAD

**Issue by vnikolay** [twbs/bootstrap#33538]
Buttons and other html tags are being cut in popover body.
For example, my code:
new bootstrap.Popover(document.getElementById('some_id'), {
	content:  'some text <button type="button" class="btn btn-outline-primary">test</button>',
	html : true
})

And popover shows only text, button is cut. I tried other tags, textarea is cut too, but div and anchors aren't cut. I need to put buttons.

**Comment by ffoodd** [comment]
This is mentioned in [popover's docs](https://getbootstrap.com/docs/5.0/components/popovers/).

> By default, this component uses the built-in content sanitizer, which strips out any HTML elements that are not explicitly allowed. [See the sanitizer section in our JavaScript documentation](https://getbootstrap.com/docs/5.0/getting-started/javascript/#sanitizer) for more details. 

Does it help?

**Comment by vnikolay** [comment]
Thanks, I didn't know that.

Option :
**sanitize : false**
is turning it off.

It helped.
