### ISSUE TITLE
Border indicating failed input field validation in input group is hidden behind its neighbor element

### ISSUE THREAD

**Issue by n01337** [twbs/bootstrap#33541]
In contrast to a focused input element, the invalidity indicator border (red by default) is hidden behind its neighboring elements. It would be worthwhile to optionally allow to show this border around the whole input group or otherwise raise its zIndex appropriately.

Applies to the bootstrap v5.0.0-beta3.

[What it looks like](https://imgur.com/oHwTH58)
[How it should look like](https://imgur.com/ly4ufoX)

The images are a combination of an input and a select element put within an input group.

**Comment by korki43** [comment]
Example Codepen: https://codepen.io/korki43/pen/ExZmwNr

**Comment by korki43** [comment]
The following lines in `mixins/_forms.scss` seem to cause the problem:
https://github.com/twbs/bootstrap/blob/bfafabfd53c330fd341cac97ba07e85abba698ab/scss/mixins/_forms.scss#L135-L140

This was added in #33211 to make the right border of invalid elements in form groups also appear red.

Ref: #33204 #33211

**Comment by jatinmehta** [comment]
@mdo I will be creating a PR for this.

**Comment by jatinmehta** [comment]
I have raised a PR for this here - https://github.com/twbs/bootstrap/pull/33644
