### ISSUE TITLE
V5 Navbar : navbar-toggler button not move to right side without brand

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33544]
my navbar doesn't have a brand so I tried to move the `navbar-toggler` button to right side but unfortunately it didn't work even if I use `.float-end` utility class and also I tried to use `.position-absolute` `.end-0` it bring another issue to navbar.

**Here a live example :** 

https://codepen.io/themes4all/pen/LYxydqz

**What I want to achieve :** 

https://www.codeply.com/p/t0Fau4H1h7

**Comment by korki43** [comment]
@devhoussam you can use `margin-left: auto`. The bootstrap utility class for this is `ms-auto` ([example](https://codepen.io/korki43/pen/MWJmPbG?editors=1000)).

**Comment by devhoussam** [comment]
> @devhoussam you can use `margin-left: auto`. The bootstrap utility class for this is `ms-auto` ([example](https://codepen.io/korki43/pen/MWJmPbG?editors=1000)).

thank you for your help
