### ISSUE TITLE
Can we Add something like owl carousel or splide.js 

### ISSUE THREAD

**Issue by Anoopkumarseth** [twbs/bootstrap#33547]
I'm facing an issue in the bootstrap since all version of bootstrap to make something like owl carousel or splide.js 

Can we add a plugin in the source of the bootstrap source to add this js in bootstrap.js?
something like this lite weight and easy to use. reference link: splidejs.com

![image](https://user-images.githubusercontent.com/30388576/113516395-b5f0f580-9597-11eb-977b-d9d45011fe99.png)

**Comment by korki43** [comment]
https://getbootstrap.com/docs/5.0/components/carousel/ ?

**Comment by mdo** [comment]
This is all possible by putting cards inside the carousel. I don't see us making it so the carousel can slide multiple slides at a time, nor do I think that's necessary for something like this, but if someone wants to spike it out in a draft PR, that'd be cool too!

**Comment by Anoopkumarseth** [comment]
yeah, putting cards inside the carousel will make it possible but if we want to call 4 cards at one time. and then slide one by one. / slide using the mouse wheel. /drag using mouse/ auto set width o f cards. an example of this should be in the documentation.
(:
