### ISSUE TITLE
$font-weight-bolder can't find in bootstrap 5 beta3

### ISSUE THREAD

**Issue by anitaparmar26** [twbs/bootstrap#33559]
In bootstrap 5 beta3 _reboot.scss, $font-weight-bolder declared where i can't find this in _variables.scss 

// Strong
//
// Add the correct font-weight in Chrome, Edge, and Safari

```
b,
strong {
  font-weight: $font-weight-bolder;
}
```

Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by korki43** [comment]
`$font-weight-bolder` is defined on line 436 in `_variables.scss`.
https://github.com/twbs/bootstrap/blob/220139a89ffc3864bbb6e1b35471667318eadc1f/scss/_variables.scss#L436

**Comment by anitaparmar26** [comment]
Thank you
