### ISSUE TITLE
`$btn-box-shadow` is not properly disabling shadows when `$enable-shadows: true` is set.

### ISSUE THREAD

**Issue by Ltchoc221** [twbs/bootstrap#33565]
Version: 
"5.0.0-beta3"

Environment
Google Chrome (89.0.4389.72) on Windows 7, Using a CRA Application

Issue: 
When setting `$enable-shadows: true`, and `$btn-box-shadow: null;`, box shadows are still appearing.  When `$btn-box-shadow: null, null;` is set, then the box shadows finally disappear.  

I believe this is due to the default of `$btn-box-shadow` being an array of values, and when a single 'null' is passed in, the second value of the array is getting added on somewhere in the import/compilation chain and still gets processed by the scss/mixins/_box-shadow.scss mixin.  When I set the variable to '$btn-box-shadow: none', I see the warning spit out about 8 times from that mixin, so I know it is being processed at least once. 

I'm not a Sass expert so I was unable to reproduce in a fiddle outside of my application, and I'm not sure if this fully qualifies as a bug or is a needed update to the documentation that the end-user must null-out both array entries in order to fully remove the shadows. We want to selectively disable shadows in our application, so we are setting $enable-shadows as we want them on certain components.

**Comment by mdo** [comment]
I believe this is because we force the "outline" box shadow on focus at all times. Would need to dig in further to confirm.

**Comment by mdo** [comment]
Change `$btn-box-shadow` to `null`.

**Comment by Ltchoc221** [comment]
Was there a change made to correct this, because setting it to null does not work as noted in the original issue?

**Comment by mdo** [comment]
I tested this locally with the latest `main` but I don't believe there were additional changes there since beta 3.

**Comment by carstenfuchs** [comment]
Why has this been closed?
I see the exact same problem with 5.0.2.

**Comment by valentin-anamorphik** [comment]
@mdo 
Why has this been closed?
I have the same problem with version 5.1.3.

Thanks.

**Comment by ffoodd** [comment]
This is intended and explained quite a few times in issues and discussions: shadows used as focus indicators are not disabled with `$enable-shadows: false` since they're not decorative but mandatory to provide an accessible focus indicator.

If you really want to disable them, do as explained in the latest comment before the close event: use `$btn-box-shadow: null`—but you then should to provide an accessible focus indicator for your users in another way.

**Comment by valentin-anamorphik** [comment]
Hi,

Thank you for your reply.
I understand the use of shadow for accessibility in focus mode.

I want to disable the shadow in the default button state. (see picture)

![image](https://user-images.githubusercontent.com/32865180/160548570-48f7348d-a733-4262-aec2-18505e788fcd.png)

**Comment by ffoodd** [comment]
As explained several times already, you need to nullify `$btn-box-shadow` in your custom build. This should work out of the box.
