### ISSUE TITLE
Bootstrap tooltip with wrong position inside a .table-responsive

### ISSUE THREAD

**Issue by pbuttelli** [twbs/bootstrap#33579]
**Operating system:** Ubuntu 20.04.2 LTS
**Browser:** Firefox 87.0
**Reduced test case:** https://jsfiddle.net/3r9z1o84/

I'm having a problem while using Bootstrap tooltips inside a parent with `overflow: auto`, more specifically inside a `.table-responsive` div. Both buttons are inside a `<td>` and have `data-bs-placement="top"`, so the tooltip should be placed in the top of them, not anywhere else.

This is what is happening:
![image](https://user-images.githubusercontent.com/11038642/113937069-043c0980-97cf-11eb-902c-a080f246285c.png) ![image](https://user-images.githubusercontent.com/11038642/113937077-069e6380-97cf-11eb-9ead-0ffd290f43bf.png)

This is the expected behavior (when `overflow-x` is removed):
![image](https://user-images.githubusercontent.com/11038642/113937184-27ff4f80-97cf-11eb-9745-101c1f674580.png) ![image](https://user-images.githubusercontent.com/11038642/113937242-377e9880-97cf-11eb-9f2b-9a77c4887bd1.png)

**Comment by rohit2sharma95** [comment]
Okay, this is not an issue. Instead a feature of Popper. :slightly_smiling_face:
By default, the boundary for the flip modifier is `clippingParents`, so Tooltip gets flipped. If you want to prevent this behavior you need to change the boundary in the flip modifier using the `popperConfig`.

```js
{
  name: 'flip',
  options: {
    altBoundary: true,
    boundary: document.body,
    fallbackPlacements: ['top', 'right', 'bottom', 'left']
  }
}
```

PS: You can not use the boundary option provided by bootstrap since it is used for the `preventOverflow` modifier only.

**Comment by pbuttelli** [comment]
@rohit2sharma95 Got it. Thank you for you explanation!
How can I do that using `bootstrap.Tooltip`? I've tried this way but the problem continues.

```js
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl, {
    popperConfig: {
      name: 'flip',
      options: {
        altBoundary: true,
        boundary: document.body,
        fallbackPlacements: ['top', 'right', 'bottom', 'left']
      }
    }
  });
});
```

**Comment by amarinediary** [comment]
This seems to be related to #33463.

**Comment by jasonlewis** [comment]
@pbuttelli I had success with the following `popperConfig`.

```js
popperConfig: function (config) {
  const flip = config.modifiers.find(({ name }) => name === 'flip')

  flip.options = {
    ...flip.options,
    boundary: 'window'
  }

  return config
}
```
