### ISSUE TITLE
Collapsible mini mode for offcanvas

### ISSUE THREAD

**Issue by iainhallam** [twbs/bootstrap#33575]
If the offcanvass drawer could remain on-screen at all times (issue #33491), rather than closing when a click is made outside, it could act as a Material UI drawer: https://material.io/components/navigation-drawer#standard-drawer.

In this case there is a nice specialistation that Quasar have implemented: a mini mode that allows the drawer to show a column of icons that can be expanded into a full drawer on various triggers. While I much prefer working in Bootstrap and CSS, I'm particularly interested in this example for site navigation:

https://quasar.dev/layout/drawer#mini-to-overlay

Is this mini mode something that could be added to Bootstrap?

**Comment by GeoSot** [comment]
Please continue on #33491 to avoid duplication
