### ISSUE TITLE
I see some changes in v 4.6.0 in breadcrumb, like float: left; That wasn't in the previous vers 4.5.3

### ISSUE THREAD

**Issue by yourchoice** [twbs/bootstrap#33572]
I see some changes in breadcrumb, in v4.6.0, like float: left;, That generate some problems in some cases:

```
.breadcrumb-item+.breadcrumb-item::before {
    float: left;
    ...
}
```

Why was added it in v4.6.0 ? I think was better without it (v4.5.3)!

Thank You

**Comment by mdo** [comment]
Was added to collapse white space if I recall. You can check the history and changes in each project and by each file (using GitHub's blame view).
