### ISSUE TITLE
V5 Offcanvas - Closing offcanvas programmatically does not work within the canvas

### ISSUE THREAD

**Issue by charleslana** [twbs/bootstrap#33577]
I didn't find a way to close it programmatically using the hide method and there is no feedback on the screen, below is the code.

https://codepen.io/charleslana/pen/Bapwxor

**Comment by GeoSot** [comment]
try this code

```js


  var myOffcanvas =       document.getElementById('offcanvasRight');
  var bsOffcanvas = new   bootstrap.Offcanvas(myOffcanvas);

  bsOffcanvas.show();

setTimeout( ()=> bsOffcanvas.hide(),3000)
```

**Comment by charleslana** [comment]
Oh, first I must call the show method and then run the hide, but I find it strange since the offcanvas is already visible, thanks.
