### ISSUE TITLE
Looking for detailed documentation about changing fonts in Bootstrap 5

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap#33573]
Hi,

Despite the fact that I have been reading the documentation, I can't find a detailed hands on example about how to change fonts in Bootstrap 5 in the SASS files of course. Is this part missing?

Regards,

David

**Comment by ffoodd** [comment]
Did you read [Typography docs oage](https://getbootstrap.com/docs/5.0/content/typography/)? It mentions font related variables and sources files that matter.

Mostly `_variables.scss` and `_reboot.scss`. I suggest you check them to get a better undestanding on how to handle fonts.

Feel free to ask again for other details or to close the issue if that helps enoufh.

**Comment by Allmedialab** [comment]
Thanks @ffoodd for your quick reply!

Yes I have been reading it all!

This is what I did in Bootstrap 4:

`@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');`
`@import url('https://fonts.googleapis.com/css2?family=Catamaran&display=swap');`
`@import url('https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap');`

`$font-family-sans-serif: Catamaran, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";`
`$headings-font-family: 'Oswald', serif;`

How does this translates to Bootstrap 5 (the fontstack part confuses me)?

Regards,

David

**Comment by ffoodd** [comment]
You should be able to do the exact same thing. What kind of troubles are you facing?

**Comment by Allmedialab** [comment]
**What kind of troubles are you facing?**
The fact that when I look in to the Bootstrap 5 SASS code there is a difference compare to Bootstrap 4.

Would this be the way to change the base font in the  Catamaran font in BS 5? 

@import url('https://fonts.googleapis.com/css2?family=Catamaran&display=swap');

` bs-font-sans-serif: Catamaran, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";

` bs-font-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", `monospace;`

**Comment by ffoodd** [comment]
I still don't get it: [as mentioned in the docs](https://getbootstrap.com/docs/5.0/content/typography/), those are [the exact same Sass variables](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L419) than [in v4](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L277). This is literally the same code [and the same docs](https://getbootstrap.com/docs/4.6/content/typography/).

Your code sample using `bs-` suggest that you're confused with the CSS custom properties, but [they're added based on the core Sass variables](https://github.com/twbs/bootstrap/blob/main/scss/_root.scss#L13) so you don't have to do anything around them. 

Simply add your `@import` or `@font-face` rule and modify your `$font-family-*` Sass variables and you're good to go, just like you did in v4.

Does this sound clearer to you?

**Comment by Allmedialab** [comment]
I try to explain that I get confused by the little difference in the Stack Fonts and the article about it in Smashing Magazine that has a link in the Bootstrap 5 docs. When I compare Bootstrap 4 and 5 there is a small difference in it I just showed you with the examples.

My question is: The stack fonts are they always the same and left like they are now in the example I showed you? No matter what font you are changing?

Sorry if I was not clear!

**Comment by ffoodd** [comment]
Each font-stack has its own variable, and each variable is the entire stack. So it's up to you to either drop the stack or simply add a custom font on top of it. In your example,  you could set `$font-family-sans-serif: Catamaran, sans-serif;` and it'd work similarly (as long as your font is loaded obviously).

The only difference between v4 and v5 regarding native sans-serif font stack is the addition of `system-ui` keyword, only because of browser support: [see `system-ui` support](https://www.caniuse.com/font-family-system-ui).

**Comment by Allmedialab** [comment]
Thanks very much for your detailed explanation!

David
