### ISSUE TITLE
V5 beta3 - in RTL the select tag with class "form-select" the arrow should be on the left #css

### ISSUE THREAD

**Issue by mostafakasem** [twbs/bootstrap#33587]
In RTL the select tag with class "form-select" the arrow should be on the left not to the right side.
 
**FIX**

`[dir="rtl"] .form-select{
  background-position: left .75rem center;
  padding: .375rem .75rem .375rem 2.25rem;
}`

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by ffoodd** [comment]
Back on this, [based on our RTL cheatsheet](https://getbootstrap.com/docs/5.0/examples/cheatsheet-rtl/#forms) the arrow is left aligned. Please provide more insights and a reduced test case, I'm closing this for now.
