### ISSUE TITLE
Modal.js: adjustDialog misaligns the dialog box

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#33584]
When modal is open and after window resize, it can be seen that modal is not aligned properly on x-axis 

Replicate:
* open dev-tools inspector and make the browser available space small, so to be easy to spot the difference
* any modal you open, it gets a padding right (cause of bodyOverfloating or ModalOverfloating)
* try to resize window. Same behavior again

Tried on win-10 & linux  chrome|firefox  

Reference: #33245, #31845

Fully explained [here](https://github.com/twbs/bootstrap/pull/33245#issuecomment-814635916)

Example below 

https://user-images.githubusercontent.com/22406063/113994977-7dcf0880-985e-11eb-9d34-2866fbf52e0f.mp4

**Comment by XhmikosR** [comment]
Does this affect v4 too? Please add the related labels :)

**Comment by GeoSot** [comment]
Seems fixed in 5.2.0
