### ISSUE TITLE
offCanvas: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by borakuldeep** [twbs/bootstrap#33594]
getting above error on console when click to open offCanvas.
 - first time the canvas does not open and gives two errors:
 1. Cannot read property 'defaultPrevented' of null (offCanvas.js line 102)
 2.  Cannot read property 'contains' of undefined (offCanvas liine 207)

 - second time, the canvas opens/closes but getting second error everytime.
 - sometimes, the image inside offCanvas does not display at all and needs refresh page to work.
 
The offCanvas component is shared in app using React context.

windows 10, google chrome v89

**Comment by GeoSot** [comment]
Hello @borakuldeep . Please can you provide a codepen example?

**Comment by borakuldeep** [comment]
@GeoSot  I will try to create codepen for it. Meanwhile, is it suppose to be implemented as global modal  like component and shared via context? I have to show offCanvas for many items as a one click info. Hence I want to create only one offCanvas component and share it down the tree. If there is any such examples, please point me to it. Thanks for bootstrap 5 btw. It's great. :)

**Comment by borakuldeep** [comment]
Closing issue. The offCanvas was not properly insterted in component tree.
