### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for bootstrap.bundle.js.map

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33595]
Version of Bootstrap : **v5.0.0-beta3**
Version of Node.js : **v14.15.1**
Version of Browser : **Google Chrome 89.0.4389.114**
Operating System : **Windows 10 Latest Update**

**DevTools Console Message :** 

![Image](https://i.imgur.com/Hux9KSK.png)

**Comment by ffoodd** [comment]
Well, seems like you're using a local file, so you need to add the map file: either the static one in our dist files, or ensure you're asking for sourcemaps in your build process.

On our side sourcemaps are distributed, so I'm closing this since there's nothing we can do in your dev environment.
