### ISSUE TITLE
carousel-item-dark

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [twbs/bootstrap#33601]
I like the new carousel-dark class, but I think it would also be useful to have darker or lighter controls, etc. on a slide-by-slide basis.

I would recommend something like a carousel-item-dark and carousel-item-light class available on each carousel-item.

This would allow slides to override the carousel setting, if necessary.

**Comment by mdo** [comment]
Controls and indicators are outside each slide, so it'd be difficult to style those based on the slides. One method could be sibling selectors, however the HTML order is never guaranteed. Blend modes or something might be useful depending on the context?

**Comment by jmacdonald-spectacle** [comment]
I was just concentrating on the captions, but you're right. the controls and indicators wouldn't work. Might need a class change on the carousel element itself.

If I get something working, I'll submit a solution.

**Comment by mdo** [comment]
Might be able to do something with `mix-blend-mode`? https://codepen.io/emdeoh/pen/YzNRYKW

**Comment by aentwist** [comment]
I can't wait til [`:has`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) comes out...

**Comment by alpadev** [comment]
Not sure if this can be achieved with CSS only. 🙁

I had a try on `mix-blend-mode` and with simple backgrounds it works more or less fine. Figured one problem is gray tho, e.g. setting the background to `#808080`. 

With pictures it's a whole different story. The more details and contrast changes they contain the harder it is to see the navigation. Colors in general have an impact on the outcome of `difference` too. Black and white images share issues with the gray backgrounds.

For the details and color problem I tried to add some `backdrop-filter` with `blur()` and `grayscale()` which solved that to some extent.

But there are pictures that still don't work. I played around by adding `backdrop-filter`s like `invert()`, `brightness()`, `contrast()` and `saturate()` with mixed results. For some pictures it works for some it doesn't.

My CSS magic is just not stronk enough to solve this 🧙‍♂️✨💩.

If you want to do it with JS tho maybe I can help 😁.

**Comment by jakubmuda** [comment]
How about adding `background-color` to controls on carousel hover? It would make controls fully visible.

`.carousel:hover .carousel-control-prev,`
`.carousel:hover .carousel-control-next{}`

![carousel](https://user-images.githubusercontent.com/40349972/117232576-6d736480-adef-11eb-85c7-cfe6f661cd91.png)

**Comment by mdo** [comment]
I think we close this as a can't/won't fix.
