### ISSUE TITLE
Setting border radius size using rounded-X overrides rounded-end

### ISSUE THREAD

**Issue by danroth27** [twbs/bootstrap#33619]
- Operating system and version (Windows, macOS, Android, iOS): Windows 10
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser): Edge 89
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

With Bootstrap 5.0 Beta2:

```html
<div class="border rounded-end rounded-3">Test</div>
```

Expected: Rounded border on end corners with large radius
Actual: Rounded border on all four corners.

**Comment by ffoodd** [comment]
Those class cannot be complementary, however you may want to introduce new utility like `rounded-end-3` to to do what you want.

I'm not in favor of such things in our core, but it can easily be added on a custom build using our Utility API.

**Comment by mdo** [comment]
Agreed with @ffoodd. Utilities don't modify one another at this time.
