### ISSUE TITLE
Modal.js:Toggle between modals problem

### ISSUE THREAD

**Issue by lamfan** [twbs/bootstrap#33613]
css : https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css
js : https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js
html : https://getbootstrap.com/docs/5.0/components/modal/

Toggle between modals work fine on the link page, but when I run it from localhost, the modal2 won't remove when click the modal button.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
