### ISSUE TITLE
form range Min Max  with two point in slider

### ISSUE THREAD

**Issue by lignanosabbiadoro** [twbs/bootstrap#33639]
if possible add to form range double selection in slider with Min Max value.

**Comment by mdo** [comment]
We use the browser-based `range` input, and as far as I know, two draggable points is not possible. `min` and `max` is allowed though.

**Comment by saeednoruzi** [comment]
for making it you need 2 range selector I think it would be easy but need some java script and css like modals our any other component

**Comment by saeednoruzi** [comment]
> We use the browser-based `range` input, and as far as I know, two draggable points is not possible. `min` and `max` is allowed though.

how jquey ui did did this dud
