### ISSUE TITLE
Dropdown inside responsive table row clipped even with data-bs-boundary set

### ISSUE THREAD

**Issue by wadih** [twbs/bootstrap#33636]
A dropdown inside a responsive table row gets clipped even with data-bs-boundary set

Removing the table-responsive class from the parent div solves the issue, but we lose responsiveness.

Another workaround is to add style="position:static" to the dropdown class div, and it doesn't clip after.

Not sure if that's expected or should be considered an issue.

OS: Ubuntu 20.04
Browser: Firefox 87
Bootstrap: bootstrap@5.0.0-beta3

Example:

```
<div class="table-responsive">
    <table class="table">
        <tr>
            <td>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                       data-bs-toggle="dropdown"
                       data-bs-boundary="viewport"
                       aria-expanded="false"
                    >
                        Options
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="#">Item</a></li>
                        <li><a class="dropdown-item" href="#">Item</a></li>
                        <li><a class="dropdown-item" href="#">Item</a></li>
                        <li><a class="dropdown-item" href="#">Item</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Item</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    </table>
</div>
```

**Comment by korki43** [comment]
I think this is expected, due to `overflow-x: auto` in `.table-responsive`.
Anyways, [here's an example codepen](https://codepen.io/korki43/pen/mdRGgMK?editors=1000).

**Comment by mrlife** [comment]
@korki43 @mdo This explanation makes sense. When encountering this issue, is there a workaround?

**Comment by wadih** [comment]
@mrlife I just tested it in the codepen above and it still works. You can add position: static to the .dropdown div and it should not clip anymore.

**Comment by mrlife** [comment]
@wadih Thanks, I don't know if it's just the version I'm on (4.6) but I can't get that to work. It does work great in the codepen.

**Comment by mrlife** [comment]
@wadih Thanks, looks like my cause for this issue was due to implementing a solution to another issue here: https://github.com/twbs/bootstrap/issues/31885#issuecomment-717970534.

**Comment by SoftCircuits** [comment]
I've been struggling with this issue for days. But, for me, if I just remove the outer `dropdown` div (just delete it), it seems to work fine. Does that not work for anyone?

**Comment by GreathostRo** [comment]
After more than a few hours and various attempts I found the working version:

```
const dropdowns = document.querySelectorAll('.dropdown-toggle')
const dropdown = [...dropdowns].map((dropdownToggleEl) => new bootstrap.Dropdown(dropdownToggleEl, {
    popperConfig(defaultBsPopperConfig) {
        return { ...defaultBsPopperConfig, strategy: 'fixed' };
    }
}));
```

**Comment by wadih** [comment]
I found that on iOS it starts clipping again IF and only IF the table is horizontally longer and has a scrollbar . If not, there is no clipping. 

My solution now is to avoid using "table-responsive", and instead use a regular div with style = "overflow: auto" 

That solves the clipping on iOS when the table is long enough to have a scrollbar horizontally 

My solution has 2 components now: 

1) Wrap the table in a div with style="overflow:auto" instead of using the table-responsive class

2) On the dropdown give class="position-static"

And that fixes the conditional clipping on iOS as well

**Comment by AshikurRahman-Peters** [comment]
<div class="table-responsive"> applies overflow-x: auto, which creates a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), causing any absolutely positioned content (like dropdowns) inside it to get clipped if it overflows the container.

The data-bs-boundary="viewport" only works for Popper.js positioning logic, not for visibility or overflow clipping, so it doesn't help when the parent has overflow: auto
