### ISSUE TITLE
Allow any navbar to contain a dropdown-menu

### ISSUE THREAD

**Issue by AdamWillden** [twbs/bootstrap#33631]
- Operating system and version (Windows, macOS, Android, iOS): Windows/Any
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser):Chrome/All
- Bootstrap version: 5.0.0-beta3

Trying to use dropdown on a navbar that does not expand & collapse. The fact the `dropdown-menu` is `position: absolute` is tied to the fact it is expandable/collapsable - I don't see a reason for this.

You can see this in the scss snippet here: https://getbootstrap.com/docs/5.0/components/navbar/#loop

I see this as a bug but be happy to be told I've missed something.

**Comment by mdo** [comment]
We "inline" the dropdowns in collapsed navbars by design—helps ensure mobile screens can access those items. We've done this since v4 and possibly earlier if memory serves. We also use absolute positioning here as the positioning is quite basic and doesn't strictly require Popper.js as a dependency.

**Comment by AdamWillden** [comment]
> We "inline" the dropdowns in collapsed navbars by design—helps ensure mobile screens can access those items. We've done this since v4 and possibly earlier if memory serves. We also use absolute positioning here as the positioning is quite basic and doesn't strictly require Popper.js as a dependency.

The docs talk of the usage of the feature as if it’s optional. I still don’t see the relation between collapsing and dropdown menus so I was suggesting you can remove the duplication of the rule set. I have no problem with absolute positioning.
