### ISSUE TITLE
Cumulative Shift Layout Issue

### ISSUE THREAD

**Issue by NeilSTSRecycle** [twbs/bootstrap#33633]
Hello all,

This is Neil Dayton of marketing at STS Electronic Recycling, Inc. and I am posting on this forum because the template for our homepage at https://www.stselectronicrecyclinginc.com/ creates an unacceptable amount of Cumulative Layout Shift, a key metric which Google uses in it's SEO algorithm.

Contained in this message is a video of the issue. The download and upload speed have been throttled for the sake of clarity. Please let me know if there is anything besides login credentials that I need to supply, and I will do so to the best of my ability.

This template was purchased from https://agethemes.com/. We've already reached out to them for support but have only received broken-english responses that we cannot decipher. However, through debugging we believe the issues lies with the template. I'm hoping for more luck from this forum, so if anyone can help I would greatly appreciate it.

If this is not the correct forum for this, or if I left out any important information, I apologize as this is my first time using GitHub.

Thank you,

Neil Dayton

**Here is the video:**
https://we.tl/t-ZH4XoK0P7k

- Happens on any OS
- Happens on all browsers

**Comment by korki43** [comment]
Hello @NeilSTSRecycle,

It seems like the template your company is using relies on bootstrap `v3.3.2`. This version has reached [End of Life](https://github.com/twbs/release#readme) in July 2019.

Also please note that bootstrap is not responsible for issues in third party themes (except an issue with the bootstrap library itself occurs).

In the future, please use the ['discussions' feature](https://github.com/twbs/bootstrap/discussions) to ask a question.

Regards, korki
