### ISSUE TITLE
4.0 -> 4.6 is-invalid breaks for me

### ISSUE THREAD

**Issue by DRobinson93** [twbs/bootstrap#33645]
Hi everyone! I am using npm to install bootstrap and gulp to compile. I updated from 4.0 to 4.6 and now is-invalid does not work for me. Do I need to set some sort of scss variable to get this to work? This is my bootstrap.scss file: 
// custom changes
$font-size-base : 0.9rem;/*match bootstrap 3 font size*/

@import "node_modules/bootstrap/scss/bootstrap";

I see the class 'is-invalid' in the minified css but it does not work like your example in the 4.6 documentation. 

This is how I am attempting to use it: 
`<input type="text" class="form-control is-invalid" />`

**Comment by mdo** [comment]
Here they are in v4.6's docs: https://getbootstrap.com/docs/4.6/components/forms/#server-side. Shouldn't need anything more than that.
