### ISSUE TITLE
`<pre>` tag is not adapting the column width in bootstrap

### ISSUE THREAD

**Issue by thelovekesh** [twbs/bootstrap#33641]
I am using `Bootstrap 5` to style my page. When I am using the `<pre>...</pre>` tag inside the `class="col"` then it is not adapting the width of the column instead of that it is increasing the width of the whole column. But when I am using the `class="col-lg-8"` it is working fine.

### HTML CODE
```html
<div class="col">
    <pre>
          <code>
             ...
          </code>
    </pre>
</div>
```

### With `<pre>` tag and `class="col"`
![image](https://user-images.githubusercontent.com/54371619/114841491-8773e580-9df5-11eb-8a72-7268038bd731.png)

### With `<pre>` tag and `class="col-lg-8"`
![image](https://user-images.githubusercontent.com/54371619/114841577-a1152d00-9df5-11eb-97e3-e5562dc87423.png)

### Without `<pre>` tag
![image](https://user-images.githubusercontent.com/54371619/114841642-b4c09380-9df5-11eb-9dce-9df52560d1fe.png)

### Check it live here
https://thelovekesh.github.io/cbtheme-debug/blog/

_Originally posted by @thelovekesh in https://github.com/twbs/bootstrap/discussions/33640_

**Comment by alpadev** [comment]
This is a _feature_ of flex box. [This](https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size#answers-header) explains the behaviour pretty well.

We could add `min-width: 0` to our columns to override the default behaviour but not sure if that's really preferred in every situation 🤔

**Comment by thelovekesh** [comment]
`min-width: 0` didnt work here. :(

**Comment by mdo** [comment]
Closing as a won't fix per comment above. All depends on the situation, so keeping the solution as such. <3
