### ISSUE TITLE
Bootstrap Scrollspy - not working properly with zoom or transform

### ISSUE THREAD

**Issue by Gardens18** [twbs/bootstrap#33653]
I have a sticky menu which needs to be always in the top and page has several sections. And the menu is for single page section wise navigation. I used Bootstrap 4 scrollspy to achieve that but the problem is in windows laptop which has low resolution of 1275px, so i need to use either

html{ zoom: 0.75} or html {transform : scale(0.75)} . it made the look same like high resolution monitors,

Now the problem is with scrollspy that it could not identify the offset correctly, so active button in the navigation for that particular section is not correctly active. Also when i press the menu button it goes to the section but with some jerking animation.

Please help me on this

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
