### ISSUE TITLE
Offcanvas: Cannot be Opened From Link That Contains <i>...</i> Tags

### ISSUE THREAD

**Issue by gahorn** [twbs/bootstrap#33654]
OS: Windows 10
Browsers: Edge Version 89.0.774.76, Chrome Version 90.0.4430.72

Links and buttons cannot show offcanvas when they contain text with `<i>` tags. This e. g. prevents the use of icons via icon fonts.

Example:
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Hello, world!</title>
</head>
<body>

<div class="offcanvas offcanvas-start" id="foo">
    TEST
</div>

<a href="#foo" data-bs-toggle="offcanvas">works</a>
<a href="#foo" data-bs-toggle="offcanvas"><i>DOES NOT WORK</i></a>
<a href="#foo" data-bs-toggle="offcanvas">click <i>!EXACTLY HERE!</i> does not work</a>

<button data-bs-toggle="offcanvas" data-bs-target="#foo">
    same behavior as link - click <i>!EXACTLY HERE!</i> does not work - rest does
</button>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by devhoussam** [comment]
> OS: Windows 10
> Browsers: Edge Version 89.0.774.76, Chrome Version 90.0.4430.72
> 
> Links and buttons cannot show offcanvas when they contain text with `<i>` tags. This e. g. prevents the use of icons via icon fonts.
> 
> Example:
> 
> ```
> <!doctype html>
> <html lang="en">
> <head>
>     <meta charset="utf-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
>           integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
>     <title>Hello, world!</title>
> </head>
> <body>
> 
> <div class="offcanvas offcanvas-start" id="foo">
>     TEST
> </div>
> 
> <a href="#foo" data-bs-toggle="offcanvas">works</a>
> <a href="#foo" data-bs-toggle="offcanvas"><i>DOES NOT WORK</i></a>
> <a href="#foo" data-bs-toggle="offcanvas">click <i>!EXACTLY HERE!</i> does not work</a>
> 
> <button data-bs-toggle="offcanvas" data-bs-target="#foo">
>     same behavior as link - click <i>!EXACTLY HERE!</i> does not work - rest does
> </button>
> 
> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
>         integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
>         crossorigin="anonymous"></script>
> </body>
> </html>
> ```

Duplicate **[#33457](https://github.com/twbs/bootstrap/issues/33457)**
