### ISSUE TITLE
List Group JavaScript behavior : W3C validation error - The aria-controls attribute must point to an element in the same document!

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33650]
![Image](https://i.imgur.com/rz3IahP.png)

**Comment by ffoodd** [comment]
Does it come from our docs?

**Comment by mdo** [comment]
Looks like it's in reference to https://getbootstrap.com/docs/5.0/components/list-group/#javascript-behavior. `validator.w3.org` passes for me though. There are those IDs in the page.

**Comment by devhoussam** [comment]
> Does it come from our docs?

yes from the Docs

**Comment by devhoussam** [comment]
> passes for me though. There are those IDs in the page.

I use the "JavaScript behavior" Example in List Group Component while I try to validated in W3C Validator it show me this errors!

**Comment by ffoodd** [comment]
I see, this example's `aria-controls` need to be prefixed with `list-` since they should match `tabpanel`s ids.

Feel free to submit a PR if you dare, otherwise we'll fix that later.

**Comment by k99sharma** [comment]
I tried to solve the issue by adding `list-` as prefix in `aria-controls` value. Can you check if it's right or not?

**Comment by devhoussam** [comment]
> I tried to solve the issue by adding `list-` as prefix in `aria-controls` value. Can you check if it's right or not?

It's Correct try to create a PR
