### ISSUE TITLE
`Alert.getInstance` returns `null`

### ISSUE THREAD

**Issue by aentwist** [twbs/bootstrap#33651]
I was under the impression that when including the classes for alerts on an element, an `Alert` was instantiated for handling JavaScript interactions. This does not seem to be the case. When using `Alert.getInstance(alertNode)`, `null` is returned. If instead `new Alert(alertNode)` is used then there are no problems. The docs do not describe the situations to use one of these over the other very well - maybe that is the issue?

Here is an [example](https://codepen.io/aentwist/pen/PoWamej) using two snippets from the docs: one for a [simple alert](https://getbootstrap.com/docs/5.0/components/alerts/#examples), and one for [closing alerts using JavaScript](https://getbootstrap.com/docs/5.0/components/alerts/#methods).

**Comment by aentwist** [comment]
docs, js, confirmed

**Comment by GeoSot** [comment]
@aentwist `Alert.getInstance(alertNode)` returns only initialized components, these that have already initialized using the `new Alert(alertNode)`. So it is natural to return null

**Comment by aentwist** [comment]
That makes sense. I just thought Bootstrap did the initialization given that Bootstrap would probably want to use instance `Alert` methods for convenience. Evidently that is not the case. Thanks for the help, this can be closed @GeoSot

**Comment by o-alquimista** [comment]
Is this new behavior already documented? I couldn't find any mention of it in the v5 migration guide or in the Alert documentation, so I searched for the error message `Alert.getInstance returns null` and it got me here.

**Comment by emololftw** [comment]
How to use method `.close()` on element? `bootstrap.Alert.getInstance()` returns always null (element exists)

**Comment by Gregory-Ledray** [comment]
I had the same experience as @o-alquimista. It looks like the right thing to do now is `Alert.getOrCreateInstance` since that doesn't require `new` and also won't create a new instance if one already exists.

**Comment by TheBitWizard** [comment]
@Gregory-Ledray Thank you for your comment. Just added Alert.getOrCreateInstance in my code and It worked the way I expected.
