### ISSUE TITLE
Carousel  will  overlap

### ISSUE THREAD

**Issue by vuvivian** [twbs/bootstrap#33656]
When the left and right directions of the carousel graph on the mobile phone are switched quickly, two carousels will overlap。
![image](https://user-images.githubusercontent.com/28998321/114981451-9ecbd500-9ec0-11eb-9233-73e9ac9baddd.png)

**Comment by korki43** [comment]
Please provide a minimal example, for example via [codepen](https://codepen.io).

**Comment by mdo** [comment]
Closing because no live demo.
