### ISSUE TITLE
Carousel direction on swipe different from v4

### ISSUE THREAD

**Issue by deLisle** [twbs/bootstrap#33657]
On macOS and iOS chrome and Safari(haven't tested other browser but pretty sure it's the same problem there)

When you use the swipe function on a carousel it goes in the opposite direction from where you have swiped from.
Why is that? It seems to be wrong.
Since when you swipe from the right to left you wanna get the carousel item from the right to swipe in.

It's easy to test if you check the documentation on the carousel for v4 or v5 on bootstraps website.

Choosing what direction you want would be optimal but at least having the same direction as v4 has on v5 would be great. Now it just messes with your head when you try to swipe :)

**Comment by GeoSot** [comment]
Hey @deLisle make a check on this
https://deploy-preview-33499--twbs-bootstrap.netlify.app/docs/5.0/components/carousel/

Does it feels right?

**Comment by deLisle** [comment]
> Hey @deLisle make a check on this
> https://deploy-preview-33499--twbs-bootstrap.netlify.app/docs/5.0/components/carousel/
> 
> Does it feels right?

Yes this feels right.
Is this a future release?

**Comment by GeoSot** [comment]
This is the fix of 5-beta-3 that will be released in 5-stable ;)
