### ISSUE TITLE
V5 Heroes example responsive layout issues

### ISSUE THREAD

**Issue by KohheePeace** [twbs/bootstrap#33660]
I found some issues at heroes examples
https://getbootstrap.com/docs/5.0/examples/heroes/

### 1.  Image should be centered or stretched for tablet and mobile
![issue-1](https://i.imgur.com/GsaFEsc.gif)
at "Responsive left-aligned hero with image" example

### 2. Sign Up form is too narrow for mobile
![2021-04-16_23h05_12](https://user-images.githubusercontent.com/29557494/115036229-48828480-9f08-11eb-9586-243c74547ec9.png)

at "Vertically centered hero sign-up form" example

## 📌 Fixed Codesandbox demo
This is a codesandbox demo URL which fixes these issues.
https://9oihf.csb.app

I only added Bootstrap's classes to fix these issues. (*It measns I **didn't** add custom css)

### 1.  Image should be centered or stretched for tablet and mobile
![issue-1-fixed](https://i.imgur.com/oFo657I.gif)

### 2. Sign Up form is too narrow for mobile
![2021-04-16_23h03_51](https://user-images.githubusercontent.com/29557494/115035976-0b1df700-9f08-11eb-9f1b-3e7171f77734.png)

## PR
If this is an issue that needs to be fixed, I'd like to send a PR.

Thanks !

## Environment
- Operating system and version: **Windows**
- Browser and version: **Chrome 89.0.4389.114**

**Comment by mdo** [comment]
Leaving the image as-is, but will fix the sign up form for sure.
