### ISSUE TITLE
form-floating & textarea

### ISSUE THREAD

**Issue by jfsv** [twbs/bootstrap#33680]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
Microsoft Windows [Versión 10.0.18363.1500]
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
Google Chrome Versión 90.0.4430.72 (Build oficial) (64 bits)
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
Bug:
<div class="col-12">
<div class="form-floating">
  	<textarea class="form-control" id="Observaciones" rows="5"></textarea>
  	<label for="Observaciones" class="form-label">Observaciones</label>
  </div>
</div>
When it is used in this way, the label in textarea is hidden by the one written in textarea
![2021-04-18 193219](https://user-images.githubusercontent.com/14055694/115165646-e39c6b00-a07c-11eb-9c92-244d0fa85d52.png)

**Comment by mdo** [comment]
#32800
