### ISSUE TITLE
Collapse with a nested input that is focused while closing, causes transition issues.

### ISSUE THREAD

**Issue by Eelisland** [twbs/bootstrap#33682]
Hi,

Collapse seems to not transition properly with an input text focus.

Codepen: [https://codepen.io/eelisland/pen/wvgEeym](https://codepen.io/eelisland/pen/wvgEeym)

Chromium Version 89.0.4389.72 (Developer Build) (64-bit)

**Comment by korki43** [comment]
I can confirm this for Firefox 88 & Chrome 90.
A collapse with a focused input will disappear immediately when retracting, instead of transitioning properly. 

I'm looking into this. Seems to be an issue with the flow of events in the JS.
