### ISSUE TITLE
card-body and card-header not padded to 0 when using p-0

### ISSUE THREAD

**Issue by martinbarilik** [twbs/bootstrap#33697]
I have no idea if this is the bug but it is a strange behaviour

https://jsfiddle.net/mArtinko5MB/0v4rxoqt/3/

**Comment by ffoodd** [comment]
Your fiddle does not contain any card, and `.p-0` is working fine on your container. Closing this since there's no bug nor description to use.

**Comment by martinbarilik** [comment]
sorry i have forgot to change the title ... can't you see the bottom scroll bar ? there is a space on the right side next to div.col
