### ISSUE TITLE
[B5] Disable progress bar smooth transition

### ISSUE THREAD

**Issue by daniel-p-tech** [twbs/bootstrap#33696]
Hi,

I'd like to disable the progress bar animation effect when the width of the progress bar changes. How can I do this? Setting ``transition: none`` completely hides the progress bar.

Thank your for your help.

**Comment by alpadev** [comment]
The only transition on progress bars is width so setting `transition: none;` should work without hiding anything.

Do you mind posting an example (e.g. on [jsfiddle](https://jsfiddle.net/), [jsbin](https://jsbin.com/), ...) where it is hidden? [Can't reproduce](https://jsfiddle.net/eq1ofrnc/) it on my end.

**Comment by mdo** [comment]
Can't reproduce and as @alpadev mentioned, we'd need a live demo showing the problem. We can re-open and revisit when that's provided, if this is still valid.

**Comment by daniel-p-tech** [comment]
I apologize, this was a false alarm - the issue was with how I was setting up the progress bar component in the UI framework of my choice.

Thank you for your attention.
