### ISSUE TITLE
[v5] Full control on font weight

### ISSUE THREAD

**Issue by Seb33300** [twbs/bootstrap#33701]
Hello,

Can you please add full control on font weight in Bootstrap v5?

I mean:
- `fw-100`
- `fw-200`
- `fw-300`
- `fw-400`
- ...
- `fw-900`

Thank you

**Comment by ffoodd** [comment]
This is a typical use case for our utility API, I dont think we'll add this to the core as it's rarely needed.

Anybother opinion is welcome 🙂

**Comment by Seb33300** [comment]
I am not sure what what do you mean by `This is a typical use case for our utility API`?

**Comment by ffoodd** [comment]
Using a Sass custom build, adding such utilities is a breathe. [See our docs for more informations](https://getbootstrap.com/docs/5.0/utilities/api/#add-utilities).

**Comment by mdo** [comment]
Most fonts don't have those values all included, so it doesn't make sense IMO to include them by default. As @ffoodd mentioned, we have a way to extend our utilities for your own needs and it's documented on our site.
