### ISSUE TITLE
Arabic search-input problem

### ISSUE THREAD

**Issue by mahdi1dev** [twbs/bootstrap#33704]
Hello
I am translating Bootstrap into Arabic and encountered a problem with search-input not working well with Arabic language

![Screenshot_٢٠٢١٠٤٢٠-١٥٤٠٢٦_QuickEdit+](https://user-images.githubusercontent.com/58599664/115397635-fd5dbf80-a1ee-11eb-8c69-f96260bbae29.jpg)

It should be like this

![Screenshot_٢٠٢١٠٤٢٠-١٥٤٣٢٣_QuickEdit+](https://user-images.githubusercontent.com/58599664/115397879-39912000-a1ef-11eb-9876-0b6b9d16764b.jpg)

But I can only do this when I remove id="search-input"

[Experiment](https://bootstrap.mahdi.style/docs/5.0/getting-started/introduction/)

html
```
<form class="bd-search position-relative me-auto">
	<input type="search" class="form-control" id="search-input" placeholder="البحث في المستندات..." aria-label="البحث في المستندات..." autocomplete="off" data-bd-docs-version="5.0">
</form>
```
css
```
.bd-search{position:relative}
.bd-search::after{position:absolute;top:.4rem;left:.4rem;display:flex;align-items:center;justify-content:center;height:1.5rem;padding-left:.25rem;padding-right:.25rem;font-size:.75rem;color:#6c757d;content:"Ctrl + /";border:1px solid #dee2e6;border-radius:.125rem}
@media (max-width: 767.98px){.bd-search{width:100%}
}
.bd-search .form-control{padding-left:3.75rem}
.bd-search .form-control:focus{border-color:#7952b3;box-shadow:0 0 0 3px rgba(121,82,179,0.25)}
```

**Comment by ffoodd** [comment]
The search input is powered by Algolia, their very own scripts adds `direction: ltr` to the wrapping span.

Please seek after Algolia's DocSearch documentation and settings.
