### ISSUE TITLE
How to open a pull request for Arabic language

### ISSUE THREAD

**Issue by mahdi1dev** [twbs/bootstrap#33708]
Hello
I am creating a bootstrap arabic language I am not done with yet.
How can I open a pull request for it?
repo: [mahdi1dev/arbootstrap](https://github.com/mahdi1dev/arbootstrap)
site: [bootstrap.mahdi.style](https://bootstrap.mahdi.style/)
Bootstrap team who knows Arabic can check the quality of the language.

**Comment by mdo** [comment]
You can add an entry to https://github.com/twbs/bootstrap/blob/main/site/data/translations.yml and open a PR for it.
