### ISSUE TITLE
table-responsive cause wrong positioning of popper.js

### ISSUE THREAD

**Issue by realnot** [twbs/bootstrap#33714]
- Operating system and version: macOS 11.2.3
- Browser and version: Chrome 89.0.4389.128

The bug appear when you have a dropdown item wrapped into table-responsive container. In this particular case, the dropdown menu increase the height of the parent instead to overflow it.

I have reproduced it here: [https://jsfiddle.net/s143rxof/2/](https://jsfiddle.net/s143rxof/2/)

I though it was a popper.js bug, but popper fixed it in version 2.0.0-rc.1

Fixed version 2.0.0-rc.1: [https://codesandbox.io/s/blissful-shamir-8ylom?file=/index.html](https://codesandbox.io/s/blissful-shamir-8ylom?file=/index.html)
Bugged version 2.0.0-next-17 [https://codesandbox.io/s/prod-flower-64vr2?file=/src/index.css](https://codesandbox.io/s/prod-flower-64vr2?file=/src/index.css)

I'm struggling to figure out if this is a problem of popper.js or bootstrap. I opened this [issue](https://github.com/popperjs/popper-core/issues/1283) on popper.js but after many attempt to reproduce it I guess this is a bootstrap bug.

**Comment by alpadev** [comment]
Add some `id` to the dropdown and add this to your JS.

```js
new bootstrap.Dropdown(document.querySelector('#dropdownbtn'), {
  popperConfig: {
    strategy: 'fixed'
  }
});
```

That should fix it.
