### ISSUE TITLE
Use const in js examples

### ISSUE THREAD

**Issue by fulldecent** [twbs/bootstrap#33713]
In the documentation at:

https://github.com/twbs/bootstrap/blob/f61a0218b36d915db80dc23635a9078e98e2e3e0/site/content/docs/5.0/examples/sidebars/sidebars.js#L2

https://github.com/twbs/bootstrap/blob/4d973259f55834ef9c9543fbcc265f11219ba8b2/site/content/docs/5.0/components/tooltips.md#example-enable-tooltips-everywhere

there are examples of using JavaScript to drive Bootstrap. That's great.

These use `var` where `const` can be more appropriate.

Recommending to prefer using `const` whenever possible.

**Comment by daveaditya** [comment]
Hello,
If no one is contributing to this issue, I would like to contribute to it.

Note: I am new to open source and looking for areas when I can contribute. It would be great start for me.

Thanks,

**Comment by KamilSynowiec** [comment]
Hi, do you still need any help?

**Comment by tkrotoff** [comment]
Related issue: https://github.com/twbs/bootstrap/issues/30818

**Comment by mdo** [comment]
Closing out since https://github.com/twbs/bootstrap/pull/31607 was merged.
