### ISSUE TITLE
Not Working on Chrome

### ISSUE THREAD

**Issue by juanjzb** [twbs/bootstrap#33712]
The template is not working on Google Chrome

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by mdo** [comment]
Yeah, I'm not going to wait for the demo on this one 😅. Bootstrap works on Chrome. Check your URLs and integrity SHAs, check that you're using Bootstrap itself vs a theme, etc.
