### ISSUE TITLE
BS5 - Floating Labels + Select - Text is cut off

### ISSUE THREAD

**Issue by JustDoItSascha** [twbs/bootstrap#33711]
I couldn't find an open ticket for that, so here it is:

Letters which are going a little bit under the baseline are cut off (like y g j). Screenshot attached.
![image](https://user-images.githubusercontent.com/8389022/115519332-64c84d80-a289-11eb-9e46-145f8ebde248.png)

**Comment by alecpl** [comment]
Duplicate of #32672

**Comment by jaxramus** [comment]
yeah this is still happening even on the latest version: https://stackblitz.com/edit/hxnclf?file=index.html
