### ISSUE TITLE
Accordion - open all section option

### ISSUE THREAD

**Issue by mleathem** [twbs/bootstrap#33728]
Boostrap 5 Accordion:

Feature request: Show all sections of accordion open.
Should be possible to configure a Button to "open all" sections.  (presumably "close all" is also a reasonable request).

I would suggest adding a class for this function as an option on the accordion container. 
This would also useful for print.css

**Comment by mleathem** [comment]
I made this work - by implementing a class "accordion-open-all-sections" that forces all sections to be open.
eg. `<div class="kw-module accordion accordion-open-all-sections" id="accordionExample">`

Feel free to use:

SCSS:
`.accordion {
  &.accordion-open-all-sections {

    // force to show all unopened sections:
    .collapse:not(.show) {
      display: block;
    }

    .accordion-button:not(.collapsed) {
      // disable click to close (that wont stay closed)
      pointer-events: none;

      // button icon: show as open.
      &:after {
        transform: rotate(0deg);
      }
    }
  }
}`

**Comment by mdo** [comment]
Closing as a won't implement at this time, but if anyone wants to take on adding an example to the docs, I'm down to review a PR that uses our JS to accomplish this.
