### ISSUE TITLE
V5 Alert: Breaks SSR in Gatsby

### ISSUE THREAD

**Issue by yshterev** [twbs/bootstrap#33722]
Using `bootstrap@^5.0.0-beta3` as ES6 modules in React/Gatsby.js

In node `window` and `document` are `undefined`. There should be a check for these so they work in similar cases.
https://github.com/twbs/bootstrap/blob/main/js/src/alert.js#L130

**Comment by yshterev** [comment]
Sorry, this can be fixed by conditional dynamic import. Don't think it is relevant to bootstrap.
In case someone needs it:

```
const bootstrap = typeof window !== `undefined` && import("bootstrap")

useEffect(() => {
    bootstrap?.then(({ Modal }) => {
      const modalEl = modalRef.current
      setModal(new Modal(modalEl, { keyboard: false, backdrop: "static" }))
    })
  }, [])

```

Seems to work.

**Comment by TCB13** [comment]
> Sorry, this can be fixed by conditional dynamic import. Don't think it is relevant to bootstrap.

We can't always depend on dynamic imports, this has everything to do with BS. Read this: https://github.com/twbs/bootstrap/pull/34989#issuecomment-1507443744
