### ISSUE TITLE
Support for input-group containing form-floating elements in Boostrap 5

### ISSUE THREAD

**Issue by oatsandcoffee** [twbs/bootstrap#33721]
I would love to use form-floating elements in an input group but ran into issues. 

Both in Firefox (87.0 (64-bit) Ubuntu) and Chrome (Version 90.0.4430.72 (Official Build) (64-bit) Ubuntu), the floating label disappears when the input field is active. Also, on Chrome, the initial empty state is already showing the floating label above the input field.

Here is a minimal example using the current Bootstrap 5.0 version:

https://codepen.io/oatsandcoffee/pen/oNBQPJW

My apologies if this is already known or expected behavior.

Thanks!

**Comment by WinterSilence** [comment]
you must include containers
~~~
<div class="input-group">
    <div class="form-floating">
        <input type="password" class="form-control" id="input-password" placeholder="Password">
        <label for="input-password">Password</label>
    </div>
    <button type="button" class="btn btn-primary">Save</button>
</div>
~~~

**Comment by oatsandcoffee** [comment]
Thank you. I could swear it didn't work when I tried it first. Anyhow, thank you!

**Comment by laszloolah91** [comment]
@WinterSilence , The border radius of the input field is not attached to the buttons/.input-group-text span properly.
