### ISSUE TITLE
Offcanvas Sidebar Menu like Halfmoon UI

### ISSUE THREAD

**Issue by rexarvind** [twbs/bootstrap#33739]
Offcanvas Sidebar component like Halfmoon UI. I tried to make one using Offcanvas component and Sidebar example but failed. Here's a live example of sidebar from Halfmoon UI which expands on medium screen.

- [Live Demo of Halfmoon Sidebar](https://rexarvind.github.io/sidebar/)
- [Offcanvas Component of Bootstrap](https://getbootstrap.com/docs/5.0/components/offcanvas/)
- [Sidebar Examples of Bootstrap](https://getbootstrap.com/docs/5.0/examples/sidebars/)

Thanks

**Comment by mdo** [comment]
#33387

**Comment by fabiopacheco18** [comment]
I need the same thing. Has anyone found a solution?
