### ISSUE TITLE
BUG: Mixing form-floating input-group -> no label

### ISSUE THREAD

**Issue by ptibogxiv** [twbs/bootstrap#33741]
when mixing form-floating input-group, label disappear (in v5)

test with all browsers

`<div class="form-floating input-group"><input type="password" class="form-control" id="pwd0" name="pwd0" placeholder="Password"><label for="pwd0">'.__( 'Confirm your password', 'doliconnect').'</label><button id="toggle-password" type="button" onclick="myFunction()" class="btn btn-outline-secondary" type="button" aria-label="Show password as plain text. Warning: this will display your password on the screen.">
<i id="toggle-password-fa" class="far fa-fw fa-eye-slash"></i></button></div>`

![image](https://user-images.githubusercontent.com/3135833/115987938-960d8a00-a5b7-11eb-93fa-46503a50c2b9.png)

**Comment by mdo** [comment]
Input groups are not supported with floating forms at this time. #floating

**Comment by Trickscenique** [comment]
Here is my working code. input-group-text must be declared after <label> and <input> elements.
`<div class="input-group mb-3">
  <div class="form-floating flex-fill">
    <input type="text" id="form_test_form_60d1b91ae08ec" name="60d1b91ae08ec" class="form-control color-picker" form="form_test_form" placeholder="core\html\form\elements\ColorpickerElement" title="core\html\form\elements\ColorpickerElement">
    <label id="form_test_form_60d1b91ae08ec_lbl" for="form_test_form_60d1b91ae08ec">
      core\html\form\elements\ColorpickerElement
    </label>
  </div>
  <div class="input-group-text">
    <svg class="svg-inline--fa fa-tint fa-w-11" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="tint" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512" data-fa-i2svg=""><path fill="currentColor" d="M205.22 22.09c-7.94-28.78-49.44-30.12-58.44 0C100.01 179.85 0 222.72 0 333.91 0 432.35 78.72 512 176 512s176-79.65 176-178.09c0-111.75-99.79-153.34-146.78-311.82zM176 448c-61.75 0-112-50.25-112-112 0-8.84 7.16-16 16-16s16 7.16 16 16c0 44.11 35.89 80 80 80 8.84 0 16 7.16 16 16s-7.16 16-16 16z"></path></svg>
  </div>
</div>`
