### ISSUE TITLE
Easily position a form validation tooltip like a regular tooltip

### ISSUE THREAD

**Issue by dosstx** [twbs/bootstrap#33743]
I would like the ability to position a form validation tooltip. Right now, when using the following class on a form element, the tooltip message overlaps the next form element's label. 

```

            <div class="invalid-tooltip">
              Please provide a valid 2 letter alpha code
            </div>
```

Screenshot:
![image](https://user-images.githubusercontent.com/6342102/115991706-55017f80-a58f-11eb-993a-652012b0ce63.png)

**Comment by alecpl** [comment]
It does not overlap for me. What version? What browser? We really need a live example of a simplified case.

**Comment by mdo** [comment]
We're not using any positioning library or extra JS on these to configure the alignment of the tooltip. You're welcome to modify yourself with custom CSS and make any suggestions back here based on your own project :).
