### ISSUE TITLE
add stepper for wizards and similar things

### ISSUE THREAD

**Issue by realrecordzLab** [twbs/bootstrap#33747]
I use bootstrap since v3 was released. 
As a backend developer I love it because it give me the ability to quickly create responsive UI for websites or mobile/desktop app. The new features added in v5 are awesome, finally the offcanvas is part of the framework and there is no need to do tricky things to achive it, also the removal of jquery from dependencies is a great deal. 

I've looked ath the documentations but the component I was looking for seems not existing at the moment. It will be nice to have a stepper like the one from [this site](https://mdbootstrap.com/docs/standard/components/stepper/), it can be useful to create wizards or other things that are divided into steps. Also if is possible, it will be great if `popper.js` is removed from dependencies, this thing in particular will make the framework more lighter and I think better.

**Comment by mdo** [comment]
#31014
