### ISSUE TITLE
top-bar

### ISSUE THREAD

**Issue by MoyaMaria** [twbs/bootstrap#33745]
i did a top-bar in an earlier version of Bootstrap and in version 5 it does not work.  how do i do a top-bar in BS5?  Thanks

<div class="top-bar">
  <div class="container">
    <div class="col-12 text-right">
      <p><a href="Name">Top Bar</a></p>
    </div>
  </div>  
</div>

**Comment by mrjatinchauhan** [comment]
Checkout Documentation here
https://getbootstrap.com/docs/5.0/components/navbar/

**Comment by MoyaMaria** [comment]
Thanks but that link is for a  nav bar.  i am asking about the bar above that.  
Thanks
![image](https://user-images.githubusercontent.com/14041677/116004574-5a7fb980-a5d1-11eb-933c-b25a25329275.png)

![top](https://user-images.githubusercontent.com/14041677/116004539-1ee4ef80-a5d1-11eb-9fb6-874d3f2a5def.JPG)

**Comment by mdo** [comment]
Check the docs—our available components are listed there. The navbar is our our "top bar" component. If you're asking about that blue bar at the top, you can easily create that with utilities.
