### ISSUE TITLE
Navbar Dropdowns are adding a horizontal scrollbar with "navbar-nav ms-auto"

### ISSUE THREAD

**Issue by daire-dev** [twbs/bootstrap#33758]
- Chrome 90 on Windows 10
- https://codepen.io/drourke2020/pen/vYgPJxY

**Comment by alpadev** [comment]
Looks fine to me 🤔

**Comment by daire-dev** [comment]
Sorry I forgot to add, it's at a particular viewport width. 
![screenshot](https://user-images.githubusercontent.com/62646514/116193920-69c94900-a730-11eb-81f5-cf3ae014723f.png)

**Comment by daire-dev** [comment]
I will close this issue. I just saw that there are these classes for exactly this situation: "dropdown-menu dropdown-menu-end".
