### ISSUE TITLE
on Bootstrap5, browser default validation message does not showed when the page is so long

### ISSUE THREAD

**Issue by kikikiblue** [twbs/bootstrap#33757]
- Operating system and version : macOS
- Browser and version : Chrome (Firefox, Safari is ok)
- [JS Bin](https://jsbin.com/losunumaya/edit?html,output)

I am using bootstrap 5 and was validating with browser defaults.

As you can see at [JS Bin](https://jsbin.com/losunumaya/edit?html,output), when the input element is located on top and the submit button is located too low, if you click the button, the page is scrolled on top but the html5 default invalid message is not showed. 
But if you comment out the bootstrap5 css like this, 
```
<!--link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"-->
```
You can see the browser default html5 validation message. 

Yes it can be the chrome browser's problem but any advice for avoiding this is welcome.

**Comment by alpadev** [comment]
The cause for this seems to be `scroll-behaviour: smooth;`.

**Comment by kikikiblue** [comment]
@alpadev You saved my day!! 
Thank you very much!!
