### ISSUE TITLE
RTL support for SCSS

### ISSUE THREAD

**Issue by manikantanapplab** [twbs/bootstrap#33751]
Sensible variables for direction RTL

**Comment by ffoodd** [comment]
Without further details on your request, I suggest you have a look at [our RTL documentation page, specifically the "Customize from source" part](https://getbootstrap.com/docs/5.0/getting-started/rtl/#customize-from-source).

Feel free to comment back if that doesn't match your needs, providing more background and maybe examples to tour request.
