### ISSUE TITLE
How do I extend / overwrite a specific popover / tooltip show function

### ISSUE THREAD

**Issue by vrushank** [twbs/bootstrap#33764]
In v4, you can overwrite any function by changing the prototype, for example:

var defaultShowPopover = bootstrap.Popover.prototype.show
bootstrap.Popover.prototype.show = function () {
    defaultShowPopover.apply(this, arguments);
    // Your custom stuff here
}

But I'm not able to achieve the same in 5. How can we do the same in v5?

**Comment by alpadev** [comment]
Still works the same. Closing this as there is no example provided that would show otherwise.
