### ISSUE TITLE
No closing transition for modal when clicked button is btn btn-primary

### ISSUE THREAD

**Issue by mnoop** [twbs/bootstrap#33763]
Operating system: Linux
Browser: Chromium Version 89

There is no closing transition for a modal when, after being allowed to finish its opening transition, a button with the `data-bs-dismiss="modal"` attribute and the `btn btn-primary` classes is clicked in the modal, as opposed to a similar button with just one class (just `btn`, or a `btn-close` button).

https://jsfiddle.net/bdy73erw/

**Comment by alpadev** [comment]
Pretty much same the problem as with #33682 😔
