### ISSUE TITLE
conflict between navbar and other toggles

### ISSUE THREAD

**Issue by songtzu** [twbs/bootstrap#33791]
if import Modal/Popover/Toast/Collapse from bootstrap，the navbar collapsed can not expand nor collapse.

Windows
chrome 90.0.4430.93/edge 90.0.818.49/firefox 88.0

[reduced test case](https://www.codeply.com/p/w8zXD5jMJx) 

in this test case, if button with text 'Show toast' clicked more than once, the navbar collapse icon works.

**Comment by GeoSot** [comment]
Hello @songtzu 

Your problem is related to #28752.
Toast needs the 'hide' class
