### ISSUE TITLE
V5 Offcanvas : data-bs-keyboard="false" not working!!

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33790]
I'm using `.offcanvas.show` to shows content the problem that I got when I try to disable Closes the off-canvas when escape key is pressed by adding this `data-bs-keyboard="false`" but as I see is not working?

Live Example:

https://codepen.io/themes4all/pen/OJWYqGr

Try to click outside the off-canvas box to see the issue!

**Comment by GeoSot** [comment]
Hey @devhoussam 

The scripts you try to replicate the issue are these of beta-3. There have been some fixes till then

Try with some updated scripts. (I tried too, and seems working)

https://deploy-preview-33782--twbs-bootstrap.netlify.app/docs/5.0/dist/css/bootstrap.min.css
https://deploy-preview-33782--twbs-bootstrap.netlify.app/docs/5.0/dist/js/bootstrap.bundle.min.js

**Comment by devhoussam** [comment]
> Hey @devhoussam
> 
> The scripts you try to replicate the issue are these of beta-3. There have been some fixes till then
> 
> Try with some updated scripts. (I tried too, and seems working)
> 
> https://deploy-preview-33782--twbs-bootstrap.netlify.app/docs/5.0/dist/css/bootstrap.min.css
> https://deploy-preview-33782--twbs-bootstrap.netlify.app/docs/5.0/dist/js/bootstrap.bundle.min.js

this is work better I update the preview link with this update : https://codepen.io/themes4all/pen/OJWYqGr

**Comment by GeoSot** [comment]
So now works or not? Can we close the issue?

**Comment by devhoussam** [comment]
> So now works or not? Can we close the issue?

it's work better you can close this issue
