### ISSUE TITLE
Solving a tiny Accordion issue when using it on a Carrd website

### ISSUE THREAD

**Issue by mrlockyer** [twbs/bootstrap#33808]
Hello!

Please tread softly! I've installed the code for Accordion feature on a Carrd website I've built. It's for a puzzle project, so I want ot be able to reveal hints for the puzzles using Accordion.

How do I have it keep the top Hint closed by default? I've tinkered with true/false to no avail.

Here is the specific page link: https://atraso.carrd.co/#accordion

All help would be appreciated!

(I'm assuming that I can add the formatting of text/color afterwards or in the CSS).

**Comment by mrlockyer** [comment]
I should also add, the arrow controls don't appear to collapse/expand. There is always one box open.

**Comment by mdo** [comment]
Open/close is toggled by a class name—replace the classes of `accordion-collapse collapse show` with `collapsed` to hide any accordion item's content.

**Comment by mrlockyer** [comment]
Tried several adjustements, to no avail.

https://atraso.carrd.co/#accordion
