### ISSUE TITLE
Carousel page disappears while scrolling if it contains an element which has focus

### ISSUE THREAD

**Issue by nadjibkrim** [twbs/bootstrap#33826]
- Operating system and version (Windows, macOS, Android, iOS): Issue visible on Windows 10 and Android
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser): Chrome 90.0.4430.93, Edge 89.0.774.75, Chrome mobile 90.0.4430.91 (Android 11)
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/):
To reproduce the issue, check this example: [https://getbootstrap.com/docs/5.0/examples/carousel/#](https://getbootstrap.com/docs/5.0/examples/carousel/#)

Steps:
      - Click on a button in a carousel item.
      - Immediately click on next or previous button.
      - The carousel item disappears before finishing scrolling.

**Comment by GeoSot** [comment]
@alpaDev does this sounds familiar to #33695 #33682?

**Comment by alpadev** [comment]
> @alpadev does this sounds familiar to #33695 #33682?

Yeah same story 😓
