### ISSUE TITLE
<dl> tag dosen't work in bootstrap popover

### ISSUE THREAD

**Issue by Aleeeksy** [twbs/bootstrap#33827]
- Issue visible in Windows 10
- Chrome, Firefox
- Reproductions:
    - Bootstrap v3.4.1 [Example](https://jsbin.com/molucitepo/edit?html,output)
    - Bootstrap v4.6.0 [Example](https://jsbin.com/fuxopediwa/1/edit?html,output)

When in "data-content" we put `<dl>` element it isn't visible in popover. 

For version 4.2.1 it work fine([Example](https://jsbin.com/wideconuqa/1/edit?html,output))

**Comment by ffoodd** [comment]
Popover content gets sanitized, as well as tooltips'. You can [read more about sanitization in pour docs](https://getbootstrap.com/docs/4.6/getting-started/javascript/#sanitizer).

To support `dl`, `dt` and `dd` you need to add them to the whitelist.
