### ISSUE TITLE
Layout option is missing when we press the print button.  

### ISSUE THREAD

**Issue by prensmiskin** [twbs/bootstrap#33836]
Layout option is missing when we press the Print button. 
The reason for this error is the page size in the css style file.

![a](https://user-images.githubusercontent.com/40228440/117187441-95a99600-ade4-11eb-9803-b335bb9687b4.png)

In the css file on the page I wrote below
If you change the code of` @page {size: a3}` to `@page {size: auto}`, the problem goes away.

https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css

![ddddd](https://user-images.githubusercontent.com/40228440/117188138-647d9580-ade5-11eb-85bf-569a432a6b1d.jpg)
Best regards.

**Comment by alecpl** [comment]
For eeference: this css code was added by https://github.com/twbs/bootstrap/pull/25164.

**Comment by prensmiskin** [comment]
> Referans için: bu css kodu [# 25164](https://github.com/twbs/bootstrap/pull/25164) ile eklendi .
> 
> BTW, baskı stillerinin kaldırıldığı v5'te alakasız, ancak v4.6'da hala var.

Thanks Aleksander.

**Comment by mdo** [comment]
Closing as stale and a won't fix in v4. If someone wants to do the user testing and suggest a change in a PR, we can revisit. However, since this isn't an issue in v5, it's not a priority.
