### ISSUE TITLE
form-group and ml-auto class not applying

### ISSUE THREAD

**Issue by Vishal-Mali** [twbs/bootstrap#33848]
- Operating system: Windows 10  
- Browser: (Chrome 90.0.4430.93, Firefox 88.0.1, Microsoft Edge  90.0.818.51)

**Issue:**
I am using bootstrap for my angular application, While troubleshooting I get to know that **form-group** and **ml-auto** classes not applying while using the bootstrap 5.0 version.  If we used the bootstrap 4.6.0 version it's working properly.

**Comment by ffoodd** [comment]
Please read the migration guide while upgrading: [`.ml-auto` is renamed to `.ms-auto`](https://getbootstrap.com/docs/5.0/migration/#utilities) and [`.form-group` has been dropped in favor of utilities](https://getbootstrap.com/docs/5.0/migration/#forms).
