### ISSUE TITLE
Possible mistakes at https://getbootstrap.com/docs/5.0/examples/heroes/

### ISSUE THREAD

**Issue by 4skinSkywalker** [twbs/bootstrap#33847]
## Centered hero
button.btn.btn-primary.btn-lg.px-4 **.me-sm-3** // _margin right is not needed, .gap-N can be used instead_

## Border hero with cropped image and shadows
.col-lg.offset-lg-1.p-0.position-relative.overflow-hidden.shadow-lg // _.position-relative is not needed_
    **.position-lg-absolute** .top-0.left-0.overflow-hidden // _.position-lg-absolute does not exists and it's not needed, .overflow-hidden is repeated_
        img **.d-block** .rounded-lg-3 // _.d-block is not needed_

**Comment by ffoodd** [comment]
Thanks for reporting! Feel confident enough to submit a PR? [Here's the markup source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/examples/heroes/index.html).

**Comment by jrn2778** [comment]
Hello,

I know I'm not the original author but I was available so I figured I'd take a stab at the issue with PR #33850
