### ISSUE TITLE
NaN in background svg of .btn-close

### ISSUE THREAD

**Issue by wa3x** [twbs/bootstrap#33857]
When i concat sass files by "gulp-dart-sass": "^1.0.2" svg code in .btn-close look like this:

```
background: transparent url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M.293.293a1 1 0 11.414 0 NaN NaNlNaN NaN NaN NaNa1 1 0 111.414 1.414 NaN NaNlNaN NaN NaN NaNa1 1 0 1-1.414 NaN NaNlNaN NaN NaN NaNa1 1 0 1-1.414 NaN NaNlNaN NaN NaN NaNa1 1 0 10-1.414 NaN NaNz'/%3E%3C/svg%3E") 50%/1em auto no-repeat;
```

BUT!
All ll other svg (in .accordion, .carousel-control and etc.) are not crashed, compiled and work fine.

=======

- Operating system Ubuntu 20.04
- Browser and version  - Firefox 88.0 (64-bit) ;)

**Comment by ffoodd** [comment]
I'd say that's more a `gulp-dart-sass` issue than our, since we use dart-sass to compile and don't have this issue.

**Comment by mdo** [comment]
Yeah, I think this is on `gulp-dart-sass`, too. I do think I can optimize our SVG though, so might push another PR for that. Unlikely that it'll help you much, but maybe!

**Comment by wa3x** [comment]
I don't know how it works, but after optimization this line worked (I took the code from the patch 
a33034d and optimize it here **svgviewer.dev**)

`$btn-close-bg:               url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><path d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/></svg>") !default;`

and I didn't touch **gulp-dart-sass** at the same time.

**Comment by pine3ree** [comment]
@wa3x, I have the same issue (twbs v.5.0.2)...but it appears only in the minified (via gulp-cssnano) version.

**Comment by thewebartisan7** [comment]
@mdo This happen also outside gulp with webpack and sass-loader.

**Comment by narkoze** [comment]
Thank you @wa3x 👍
