### ISSUE TITLE
Is it possible to have a migration guide/doc from Bootstrap 3 to 5?

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#33864]
Or is better approach to upgrade to 4 and then to 5? To me in my ignorance seems less effort to directly migrate to 5.

**Comment by tomasts248** [comment]
But what about things that has dramatically changed from 4 to 5, it means changing that twice, I would rather recreate the code directly in B5 syntax.

**Comment by samarmohan** [comment]
But just look at both migration docs (3-4, 4-5) and make the changes accordingly. It's not that hard but it _is_ hard to add extra docs.

**Comment by mdo** [comment]
No plans to do this ourselves. As mentioned it'd be a bit of work on our end, and v3 hasn't been maintained in years, so it's not a priority for us unfortunately. Sorry!

**Comment by tomasts248** [comment]
Understood, thanks!
