### ISSUE TITLE
Modals break after release 5.0

### ISSUE THREAD

**Issue by MichalHecko** [twbs/bootstrap#33867]
OS: Windows 10
Browser: Opera 76

I did an upgrade from Bootstrap 5.0-beta3 to Bootstrap 5.0.

Code, that worked in Beta3 is now not working. It is that part, when modal's constructor initializes Backdrop...

```
this.modal = new bootstrap.Modal($('div.modal')[0], {
    backdrop: 'static'
});
```

I've got:

```
TypeError: BACKDROP: Option "rootElement" provided type "null" but expected type "element". 
    at index.js:130
    at Array.forEach (<anonymous>)
    at l (index.js:124)
    at xe._getConfig (backdrop.js:92)
    at new xe (backdrop.js:33)
    at Ne._initializeBackDrop (modal.js:218)
    at new Ne (modal.js:84)
```

**Comment by mscdex** [comment]
I just ran into this same exact issue coming from beta3. Except I only have something like:

```js
var modal = new bootstrap.Modal('#modalThatExists');
// or
var modal = new bootstrap.Modal(document.getElementById('modalThatExists'));
```

Neither of them work in 5.0 final but do in 5.0-beta3.

@MichalHecko How did you resolve this?

**Comment by MichalHecko** [comment]
Move your <script> with bootstrap at the end of the <body>.
But i am waiting for the official fix

**Comment by MichalHecko** [comment]
Duplicate of 33840
