### ISSUE TITLE
V5 - Disappearing label when editing text using floating-label and input-group

### ISSUE THREAD

**Issue by aderrose** [twbs/bootstrap#33871]
When using an input group and floating labels the label disappears when the input is active (focused):

![image](https://user-images.githubusercontent.com/41271480/117434025-0f946900-af24-11eb-88f6-c4021ce494d5.png)
Once the input looses focus the floating label works as expected, showing above the content:

![image](https://user-images.githubusercontent.com/41271480/117433900-ed025000-af23-11eb-846e-7fc57e8810e6.png)
Or without any content:

![image](https://user-images.githubusercontent.com/41271480/117434227-51bdaa80-af24-11eb-90c8-7f3ad5273610.png)

I've replicated the issue in JS Bin which is linked below.

- Operating system and version (Windows)
- Browser and version (Microsoft Edge 90.0.818.56, Chrome 90.0.4430.93, Firefox 88.0.1)
- [JS Bin](https://jsbin.com/tasavuy/edit?html,output)

**Comment by alecpl** [comment]
It's because `.input-group > .form-control:focus { z-index:3; }`. Floating labels inside input-groups will have to also update their z-index.

**Comment by aderrose** [comment]
Brilliant thanks, I had looked through the CSS to see if I could find the issue but I'm far from an expert.

After a bit of trial and error `.form-floating > label { z-index: 3; }` seems to do the trick :)
