### ISSUE TITLE
V5 Navs and tabs : JavaScript behavior move from tab to another inside tab content

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33883]
I hope that I can explain exactly what I mean by that so let's imagine that I have a button inside tab content that button has JavaScript behavior while I click on it it will send me to another tab from that tabbed content.

**here is a simple example:** 

https://codepen.io/themes4all/pen/jOBEvpe

**Comment by alecpl** [comment]
In other words. Make `data-bs-target` on any button to trigger click on the targeted element. I guess that we would also need an extra attribute e.g. boolean `data-bs-link`.

**Comment by devhoussam** [comment]
> In other words. Make `data-bs-target` on any button to trigger click on the targeted element. I guess that we would also need an extra attribute e.g. boolean `data-bs-link`.

exactly something like that

**Comment by rohit2sharma95** [comment]
It is not a common use case :slightly_smiling_face:

For such scenarios bootstrap provides javascript methods to use, like `show`:
```js
const pillsContactButton = document.getElementById('pills-contact-button');
const pillsContactTab = document.getElementById('pills-contact-tab');
pillsContactButton.addEventListener('click', () => {
  new bootstrap.Tab(pillsContactTab).show();
});
```

Updated codepen: https://codepen.io/rohit2sharma95/pen/XWMJLLx

/CC @twbs/js-review

**Comment by GeoSot** [comment]
Agree with the above opinion. Tab component, has a specific philosophy to its functionality. 

you may can try to use `data-bs-trigger` with `data-bs-target` on this extra button html markup, but I cannot ensure you for the result
