### ISSUE TITLE
Jombotron help!!

### ISSUE THREAD

**Issue by jgreenwo34** [twbs/bootstrap#33897]
I am learning Bootstrap, and when it comes to learning Jumbotron code, i get this: "[Bootstrap has] dropped the jumbotron component as it can be replicated with Utilities. See our new Jumbotron example for a demo."   None of the links for jumbotron examples are working.  Where can  i find code of the latest version of Bootstrap Jumbotron code.........

Than you.

**Comment by rohit2sharma95** [comment]
It is available in the examples :slightly_smiling_face: 
See here: https://getbootstrap.com/docs/5.0/examples/jumbotron/
And the code is here: https://github.com/twbs/bootstrap/tree/main/site/content/docs/5.0/examples/jumbotron

**Comment by jgreenwo34** [comment]
rohit2sharma95 
Thank you for the quick response and for the code, I appreciate your help....

The Example links at https://getbootstrap.com/docs/5.0/examples/jumbotron/ do not send me anywhere, they are not working, which is why I created this Issue.  I'm using Chrome browser on Windows 10 Home OS.

**Comment by rohit2sharma95** [comment]
Ah, but that's a valid link :smile:
You should see a page like below:
![image](https://user-images.githubusercontent.com/26922866/117542662-27104680-b037-11eb-8312-eb531e131077.png)
