### ISSUE TITLE
Weird behavior with split dropdowns on iOS 

### ISSUE THREAD

**Issue by TKDKid1000** [twbs/bootstrap#33907]
I recently made a little site with bootstrap 5. It worked fine on my computer, but looked weird on ios. https://github.com/TKDKid1000/tkdkid1000-website/blob/main/views/root.liquid Has the source code for that page. What happens is the button seems to lose it’s css in ios. 
![22E2E8EA-AFDA-49AD-8D95-45507625DD8B](https://user-images.githubusercontent.com/69736165/117563064-35bb2580-b058-11eb-9dee-e2125edd1acf.jpeg) is an image. I am using ios 14 chrome `87.0.4280.163`

**Comment by alpadev** [comment]
Can you try to remove `type=button` from the `<a>` element?

**Comment by TKDKid1000** [comment]
> Please try to remove `type=button` from `<a type="button" class="nav-link dropdown-toggle dropdown-toggle-split" data-bs-toggle="pagesDropdown" aria-expanded="false">`.

Yea, that works.
