### ISSUE TITLE
Menu with sub menu does not open.

### ISSUE THREAD

**Issue by MarksEliel** [twbs/bootstrap#33902]
- Operating system and version: Windows 10
- Browser and version: Last version new edge, chrome, vivaldi

When accessing the demo itself, in any layout you can go to:
Interface -> Authentication and the sub menu will not open.

I'm using bootstrap 5

**Comment by alpadev** [comment]
As mentioned in our issue template - please provide us with a [reduced test case](https://css-tricks.com/reduced-test-cases/) on e.g. [CodePen](https://codepen.io/), [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/), so we can reproduce your problem.

**Comment by MarksEliel** [comment]
Just go to the demo site https://preview.tabler.io/

If you try to go to the sub menu:
Interface -> Authentication

it will not work.

print: https://prnt.sc/12opcq3

**Comment by mdo** [comment]
Nested dropdowns haven't been supported since v4 shipped. There's an open issue for that.
