### ISSUE TITLE
isVisible utility function returning false positives

### ISSUE THREAD

**Issue by RyanBerliner** [twbs/bootstrap#33914]
The current implementation of [`isVisible`](https://github.com/twbs/bootstrap/blob/main/js/src/util/index.js#L137) is currently not thorough enough. It is claiming certain elements are visible when they clearly are not. [Here is a demo](https://jsfiddle.net/q4s7Lcr1/) of the function thinking that a dropdown item is visible, even when the dropdown is closed.

**Comment by alpadev** [comment]
@RyanBerliner not sure. Are you on this or do you want someone else to have a look?

**Comment by RyanBerliner** [comment]
@alpadev If you or anyone else wants to take this on, you are welcome to - otherwise, you may assign it to me.
