### ISSUE TITLE
Not work config in Dropdown for "new bootstrap.Dropdown(element, ...config)" v.5

### ISSUE THREAD

**Issue by alexshnur** [twbs/bootstrap#33930]
- Operating system and version (Windows)
- Browser and version (All)
- https://codepen.io/alexshnur/pen/qBrOPNb?editors=1010

**Comment by alpadev** [comment]
The `autoClose` parameter needs to be camel case, not lower case. In addition, as described in the [documentation](https://getbootstrap.com/docs/5.0/components/dropdowns/#via-javascript), `data-bs-toggle="dropdown"` must always be present.

**Comment by alexshnur** [comment]
Please look again at the link, the auto position does not work correctly when the dropdown is in the nav

**Comment by alpadev** [comment]
Remove the `<nav>` element and click the other dropdown you added. The result will be the same because popper is setup to flip the dropdown if there is not enough space.

Your issue lacks any description of what isn't working as expected, so hard to say what's not working for you.
