### ISSUE TITLE
Remove Modal Backdrop

### ISSUE THREAD

**Issue by silviodelgado** [twbs/bootstrap#33946]
After close a modal, the ```dispose``` method is triggered.

The line 117 of file ```backdrop.js``` contains:

```this._getElement().parentNode.removeChild(this._element)``` 

(This code is also on line 2633 of ```bootstrap.js``` file)

But when we handle modals manually (create and trigger dynamically),```this._getElement().parentNode``` is null.
Then, a TypeError is thrown.

Before this call (line 117 of ```backdrop.js``` file, should add an element checking (if is null).

**Comment by GeoSot** [comment]
@silviodelgado  Pleaseee, provide a live example and steps to reproduce
