### ISSUE TITLE
v5: Error - Bootstrap doesn't allow more than one instance per element.

### ISSUE THREAD

**Issue by jakubmuda** [twbs/bootstrap#33940]
I have this error:

> Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.

using this code:

`<button class="btn btn-dark" type="button" data-bs-toggle="dropdown" data-bs-auto-close="true" data-bs-toggle-2="tooltip" data-bs-placement="bottom" title="Lorem Ipsum" aria-expanded="false">
`

It looks like you can't have dropdowns and tooltips together, but it should be possible.

**Comment by ffoodd** [comment]
No, from an accessibility perspective it should not exist so we don't support it.

To elaborate:
- when using a keyboard to navigate, where does clicking and tabbing would lead to? Tooltip, or dropdown? Cannot be both, obviously.
- someone using a screenreader wouldn't know what has been expanded.

AFAIK that's not something we'll consider.

**Comment by NimaFx** [comment]
> No, from an accessibility perspective it should not exist so we don't support it.
> 
> To elaborate:
> 
> * when using a keyboard to navigate, where does clicking and tabbing would lead to? Tooltip, or dropdown? Cannot be both, obviously.
> * someone using a screenreader wouldn't know what has been expanded. BTW which one of tooltip ans dropdown would update the `aria-expanded` attribute?
> 
> AFAIK that's not something we'll consider.

Are you assuming the click shows the tooltip? But the tooltip shows on mouse hover! Tooltip is not for keyboards or touch screens.

**Comment by ffoodd** [comment]
So you assume someone using only keyboard to navigate would never be able to access tooltip's content?

Of course tooltips are operable with keyboard.

**Comment by NimaFx** [comment]
It's possible to trigger tooltips on the focus, shortcut key or add an extra icon just for tooltips. I'm aware of that. but still, your assumption is false! It's a focus, long tap, or click. But not all!

It's a dropdown that has a tooltip too! How should I handle on touch screen or keyboard is a framework independent decision. 
<select name="cars" id="cars" title="Cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
</select>

**Comment by zahedkamal87** [comment]
@NimaFx, I'm having the same issue. Have you found any solution? Thank you

**Comment by NimaFx** [comment]
@zahedkamal87 I used [tippy](https://atomiks.github.io/tippyjs/) Both Bootstrap and Tippy use Popover so the result is the same.

**Comment by gidzr** [comment]
> So you assume someone using only keyboard to navigate would never be able to access tooltip's content?
> 
> Of course tooltips are operable with keyboard.

Why does tab not tabulate through both, one after the other? I don't understand why a tab can only open one or the other.. why isn't it cycling through like it does for inputs, text areas, buttons, etc?

**Comment by aldwinp35** [comment]
Put the ``tooltip`` inside a ``span`` element

```html
<button class="btn btn-dark" type="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">
    <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="Lorem Ipsum"><Your-Icon-Here /></span>
</button>
```

**Comment by karolyi** [comment]
@ffoodd 

> when using a keyboard to navigate, where does clicking and tabbing would lead to? Tooltip, or dropdown? Cannot be both, obviously.

This goes directly against what you guys state in the [V5 documentation](https://getbootstrap.com/docs/5.2/components/dropdowns/#overview):
> They’re toggled by clicking, not by hovering; this is [an intentional design decision](https://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/).

As for the screen readers, I can't vouch in any direction. I'm just pointing out that you're wrong on your first point.

I too think that dropdowns and tooltips should be able to be presented on the same element.

**Comment by MohammedMubeen** [comment]
Hi Folks,

Please help me, I am also facing error more than one instance.

Bootstrap doesn't allow more than one instance per element. Bound instance: bs.popover.
Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.

Also, tooltip and popover overlapped. 

![image](https://user-images.githubusercontent.com/26380140/218720339-5bb6fa52-b042-4d97-9424-06125294dfef.png)
![image](https://user-images.githubusercontent.com/26380140/218720385-37582291-c3ea-44a5-ab47-4bd578562e71.png)
![image](https://user-images.githubusercontent.com/26380140/218720413-0f3d5c67-b5d8-4435-b324-a7432a5947f9.png)

**Comment by julien-deramond** [comment]
@MohammedMubeen Please don't create duplicates. Your question is already in https://github.com/twbs/bootstrap/discussions/38047. Moreover, this is a closed issue.
