### ISSUE TITLE
Bootstrap v5 : Border style issue

### ISSUE THREAD

**Issue by ImAbhishekTomar** [twbs/bootstrap#33950]
Hi,

I think this is a issue. When i am adding border classes  then is not enabled displaying border because "border-x" is not adding "border-style"  props & because of this border is not displaying and there is not class for border style like "border-solid". 

Bug reports must include:

- Operating system and version (macOS Big Sur 11.1)
- Browser and version (Chrome 90.0)
-  suggested fix using [JSFiddler](https://jsfiddle.net/JackRyu/5m6ou1wg/4/)

**Comment by alecpl** [comment]
That's not a bug. You have to use "additive" `border` class(es). `border-X` classes define only the width as documented.

**Comment by ffoodd** [comment]
As mentionned, you have to use `.border`  to get border style. [Check out our border utilities docs](https://getbootstrap.com/docs/5.0/utilities/borders/#additive).

**Comment by ImAbhishekTomar** [comment]
Thanks
