### ISSUE TITLE
Bootstrap5 and Masonry example: I get gaps under cards when using example code

### ISSUE THREAD

**Issue by dosstx** [twbs/bootstrap#33963]
I am trying to use the Masonry plugin with Bootstrap5 and NuxtJS. When I follow the example here
https://getbootstrap.com/docs/5.0/examples/masonry/ and incorporate it into my own codesandbox, I notice that my demo is not in the correct masonry format. See the gaps? 

> My example:

![image](https://user-images.githubusercontent.com/6342102/118121551-443a7180-b3b7-11eb-807a-b9a76aab6ea3.png)

> Bootstrap's example:

![image](https://user-images.githubusercontent.com/6342102/118121591-51eff700-b3b7-11eb-81b4-6ee6eef9ca79.png)

What do I need to do to get my demo into format shown on the Bootstrap Masonry example page?

My codesandbox demo link: https://codesandbox.io/s/nuxt-masonry-issue-fx7g6

  [1]: https://masonry.desandro.com/
  [2]: https://codesandbox.io/s/nuxt-masonry-issue-fx7g6
  [3]: https://i.stack.imgur.com/1aLtq.png
  [4]: https://i.stack.imgur.com/9XSKM.png

- Operating system and version (Windows, macOS, Android, iOS)
   Windows 10
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
 Microsoft Edge Version 90.0.818.56 (Official build) (64-bit) (haven't tried other browsers)
- Live sandbox: https://codesandbox.io/s/nuxt-masonry-issue-fx7g6

**Comment by kissu** [comment]
This question was also asked on SO: https://stackoverflow.com/questions/67518659/how-to-properly-load-bootstrap5s-masonry-into-nuxt

**Comment by alpadev** [comment]
Thx @kissu for having a look into this.

Closing this, as there is a solution provided on SO.

**Comment by dosstx** [comment]
> This question was also asked on SO: https://stackoverflow.com/questions/67518659/how-to-properly-load-bootstrap5s-masonry-into-nuxt

Thanks very much, @kissu !
