### ISSUE TITLE
Responsive borders

### ISSUE THREAD

**Issue by AlessandroVecchi** [twbs/bootstrap#33974]
It would be useful to configure responsive variants to target specific viewports for "border", in the same way as "margin" and "padding"
e.g. 
border-sm
border-md
border-sm-top
border-sm-top-0

**Comment by jeremyvii** [comment]
This and responsive variants of the `rounded` class would be very useful.

**Comment by ffoodd** [comment]
For now we don't have any need for that. We'll see if this request gain any interest; meanwhile it's pretty easy to support this in your own build by using our utility API.

**Comment by mdo** [comment]
Closing as a won't fix for now

**Comment by ytilotti** [comment]
> For now we don't have any need for that. We'll see if this request gain any interest; meanwhile it's pretty easy to support this in your own build by using our utility API.

There are bugs if we use utility API and responsive attribute on border.

**Comment by sovetski** [comment]
Any update on it? A simple example where we can get a problem with it:
Adding sidebar with a "right border", but on mobile, the sidebar will be at the bottom of the screen so we should not see the right border
