### ISSUE TITLE
Native font stack missing BlinkMacSystemFont

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [twbs/bootstrap#33977]
The variables.scss file seems to be missing BlinkMacSystemFont or the documentation is incorrect and should be updated.

variables.scss:
$font-family-sans-serif:      system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji" !default;

https://getbootstrap.com/docs/5.0/content/reboot/#native-font-stack:
$font-family-sans-serif:
  // Cross-platform generic font family (default user interface font)
  system-ui,
  // Safari for macOS and iOS (San Francisco)
  -apple-system,
  // Chrome < 56 for macOS (San Francisco)
  BlinkMacSystemFont,
  // Windows
  "Segoe UI",
  // Android
  Roboto,
  // Basic web fallback
  "Helvetica Neue", Arial,
  // Linux
  "Noto Sans",
  "Liberation Sans",
  // Sans serif fallback
  sans-serif,
  // Emoji fonts
  "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji" !default;

Bootstrap 5.0.0 / 5.0.1

**Comment by ffoodd** [comment]
It's a doc issue, we don't support Chrome 56 in v5 anymore so it's been dropped.
