### ISSUE TITLE
v5 Form-control disabled by default

### ISSUE THREAD

**Issue by 9mido** [twbs/bootstrap#33981]
I along with this other person on stackoverflow ran into a problem with form-control being disabled by default:

https://stackoverflow.com/questions/67447259/bootstrap-button-in-form-control-changes-directly-to-disabled

Is this a bug and is there a workaround?

For me, it happens on stripe.js card-element but nothing else. With mine, you can still type into the card element but it has the greyed out disabled look.

`<div id="card-element" class="form-control">`

**Comment by mdo** [comment]
This should be fixed with v5.0.1 which shipped today. We reverted a selector change from `:read-only` back to `[readonly]` which I don't believe has that issue.

**Comment by 9mido** [comment]
Wow great thanks for the quick response. Here is a jsfiddle I just made in case you need to further test it.

https://jsfiddle.net/esr4u2ht/
