### ISSUE TITLE
Provide separate built with negative margins

### ISSUE THREAD

**Issue by harpreetsb** [twbs/bootstrap#33988]
Since the negative margins are not provided by default.
I would be nice to provide a separate built with same.
Some people like myself are not proficient enough to compile sass.

**Comment by ffoodd** [comment]
IMHO we won't do that, because we'll get request for every possible build with different kind of options.

This is a good idea for another open source project I guess, I think it existed for v3 and v4.

**Comment by harpreetsb** [comment]
How can I get a compiled Bootstrap with negative margins enabled?
Or am i missing something?

**Comment by ffoodd** [comment]
You need to compile Sass by yourself, or wait for someone to provide a build. As I said I don't think we'll provide every possible build.

**Comment by harpreetsb** [comment]
Did it myself after some struggle,
thanks for motivating.
