### ISSUE TITLE
Floating labels break placeholder attribute

### ISSUE THREAD

**Issue by broofa** [twbs/bootstrap#33999]
## SSCCE

The "Floating Label" [example in the docs](https://getbootstrap.com/docs/5.0/forms/floating-labels/#example) actually shows this.  The example has `placeholder="name@example.com"` in the docs, but the placeholder value (`name@example.com`) isn't shown anywhere...

![image](https://user-images.githubusercontent.com/164050/118399329-6111b780-b5f8-11eb-9e36-76924f55feb8.png)
![image](https://user-images.githubusercontent.com/164050/118399333-65d66b80-b5f8-11eb-83e9-41d33400e378.png)

I've found myself working around this by adding a span in the label with the placeholder text.  For example:
![image](https://user-images.githubusercontent.com/164050/118398982-ad5bf800-b5f6-11eb-8b0d-413c0f3f418b.png)

... which renders like this:
![image](https://user-images.githubusercontent.com/164050/118399019-d7151f00-b5f6-11eb-9844-4a3d20b46c96.png)

![image](https://user-images.githubusercontent.com/164050/118399004-c95f9980-b5f6-11eb-9bfb-f28a17d90f91.png)

This isn't ideal, obviously. It would be preferable for the input to behave as it does normally (showing placeholder text until user starts typing).

## Env info
```
$ npx envinfo --system --browsers --npmPackages --binaries

npx: installed 1 in 0.845s

  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 29.40 MB / 16.00 GB
    Shell: 5.1.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.2
  npmPackages:
    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.1823 => 2.0.0-nightly.1823
    @parcel/transformer-sass: 2.0.0-beta.2 => 2.0.0-beta.2
    @types/react-dom: 17.0.3 => 17.0.3
    @types/react-router-dom: 5.1.7 => 5.1.7
    @typescript-eslint/eslint-plugin: 4.20.0 => 4.20.0
    @typescript-eslint/parser: 4.20.0 => 4.20.0
    bootstrap: 5.0.1 => 5.0.1
    checkcss: 1.0.1 => 1.0.1
    eslint: 7.21.0 => 7.21.0
    eslint-config-standard: 16.0.2 => 16.0.2
    eslint-plugin-import: 2.22.1 => 2.22.1
    eslint-plugin-node: 11.1.0 => 11.1.0
    eslint-plugin-promise: 4.3.1 => 4.3.1
    eslint-plugin-react: 7.22.0 => 7.22.0
    eslint-plugin-react-hooks: 4.2.0 => 4.2.0
    fast-levenshtein: 3.0.0 => 3.0.0
    firebase: 8.4.2 => 8.4.2
    firebaseui: 4.8.0 => 4.8.0
    nanoid: 3.1.22 => 3.1.22
    parcel: 2.0.0-beta.1 => 2.0.0-beta.1
    react: ^16.13.1 => 16.14.0
    react-bootstrap: 2.0.0-alpha.1 => 2.0.0-alpha.1
    react-dom: ^16.13.1 => 16.14.0
    react-router-bootstrap: 0.25.0 => 0.25.0
    react-router-dom: 5.2.0 => 5.2.0
    sass: 1.32.12 => 1.32.12
    typescript: 4.2.3 => 4.2.3
```

**Comment by mdo** [comment]
This is by design, though we should drop the `placeholder` content in our docs for these. There's not really a way to include the placeholder as well without removing the overall effect of the label being small once a value is entered.

**Comment by alpadev** [comment]
Too bad FF doesn't support transitions on placeholder (anymore 😞). I tried to make the placeholder only transparent while the input isn't focused, and to show it with some delay. In Chrome this seem to work fine.

![input-placeholder](https://user-images.githubusercontent.com/2838324/118672939-e794e780-b7f8-11eb-8a49-29287b47b094.gif)

**Comment by broofa** [comment]
Consider reopening?  It looks like changing the `.form-floating > .form-control::placeholder` rule to only apply when input is not focused (i.e. so it reads `.form-floating > .form-control:not(:focus)::placeholder`), restores the default `placeholder` behavior.

![Untitled](https://user-images.githubusercontent.com/164050/118719632-6ae81600-b7c4-11eb-9f7a-da3a16ca19ef.gif)

https://codepen.io/broofa/pen/gOmwVPz

**Comment by alpadev** [comment]
Yeah that's pretty much the same approach. :+1:

There is a transition on the label when it moves up. So my intention wasn't to transition the placeholder but rather delay its appearance. The transform duration for the label is (by our defaults) 0.1s. In FF the label will overlap the placeholder during this time, but maybe that's negligible.

In theory we could make use of a pseudo element to overlap that placeholder during that time so to make it work x-browsers. Although, in case someone uses a different background color for their forms, it would look certainly weird.

**Comment by broofa** [comment]
> In FF the label will overlap the placeholder during this time, but maybe that's negligible.

It appears to be negligable.  If you open up that CodePen in FF and play with it, the experience is (imho) okay.  'Not really much actual overlap there.

> make it work x-browsers

That codepen seems to work in all modern browsers.  (Have not tested IE)

So is there any reason not to just change the existing `&:focus::placeholder` rule to read `&:not(:focus)::placeholder`?  The experience can be refined later on, if needed, but this would at least fix what is (imho) the much more serious issue of placholder text not working.

**Comment by DionPotkamp** [comment]
This might be a topic for another issue, but if you remove the placeholder tag entirely the label is always floating. 

Also by design, or a bug?

**Comment by broofa** [comment]
@DionPotkamp From [the Floating label docs](https://getbootstrap.com/docs/5.0/forms/floating-labels/):

> A placeholder is required on each <input> as our method of CSS-only floating labels uses the :placeholder-shown pseudo-element.

So... "working as designed", I expect.

**Comment by gastlich** [comment]
@mdo could you elaborate on this, please?
> There's not really a way to include the placeholder as well without removing the overall effect of the label being small once a value is entered.

based on what @broofa  and @alpadev  provided it looks like it might be possible to show the placeholder after focusing on an input.

I came up with a similar solution working on multiple browsers:
```scss
.form-floating > .form-control:focus {
  &::placeholder {
    color: $input-placeholder-color !important;
  }
}
```

Is there something we are missing to make it working?

--- 

As far as I know the floating labels were promoted by Google's Material Design, so I wanted to double check if they support placeholders:
https://material.io/components/text-fields#outlined-text-field

Based on their screenshots it looks like it's supported by the Material Design
![first](https://user-images.githubusercontent.com/1146430/147696256-142e6b1f-1e73-4e8d-b1aa-dddb0a906012.png)
![second](https://user-images.githubusercontent.com/1146430/147696252-316a6b5d-8e77-4492-9ea3-88f01dbad997.png)

From my perspective... hiding placeholders fully, breaks their purpose and makes it impossible to give users further valuable hints about the inputs, which they are working with.

To give you an example:
British post codes contain a space and some inputs require the space to be provided. The ideal input would have label `Postcode` and placeholder `eg. CR0 3RL`.

<img width="530" alt="Screenshot 2021-12-29 at 19 29 37" src="https://user-images.githubusercontent.com/1146430/147697068-ee12cd22-36b1-41ef-a5b5-f655ea552cad.png">
<img width="531" alt="Screenshot 2021-12-29 at 19 29 46" src="https://user-images.githubusercontent.com/1146430/147697067-2bb6ca29-2d19-443c-b7f6-35a6fd373cc9.png">

Without the space ` ` it's more likely users will type their postcodes lazily: `CR03RL`.

**Comment by PerryCodes** [comment]
I consider Boostrap implementation of Floating Labels completely unusable.  Selecting the field results in the "invisible" placeholder all of a sudden being shown simultaneously.
![Bootstrap Floating Label](https://github.com/twbs/bootstrap/assets/2401573/93ab1f89-aa97-4ac0-b3b8-1a6be6aceb23)
