### ISSUE TITLE
Undesirable Navbar behavior in Versions after BS 4.5.3

### ISSUE THREAD

**Issue by Printninja** [twbs/bootstrap#34002]
In BS 4.5.3, Nav Items would wrap to a new line when they exceeded screen width. Now they stack vertically, and once the screen width is too narrow, they overflow the browser window, creating a horizontal scroll bar on the x-axis. This should never happen in a responsive framework. Old (desirable) behavior can be restored by setting Flexbox Wrap on the Nav to Wrap. 

Example can be seen at this link.
https://thelightwavegroup.com/na/

Windows 7x64 platform, in 64bit Chrome Version 90.0.4430.212 as well as 64bit Firefox Version 88.0.1 and Android 11 using Chrome Version 90.0.4430.210 and Firefox

**Comment by ffoodd** [comment]
First of all, please reproduce your test case using the latest v4—something might have changed since v4.5.3.

When you say it used to work, with which version are comparing the behavior exactly?

**Comment by Printninja** [comment]
First of all, did you even look at the link I posted, or read what I wrote on it? Did you look at the version of Bootstrap being used in my example? I've been building websites with Bootstrap since version 3. I know how to diagnose problems when something isn't working correctly with a CSS framework.  If you read and follow what I wrote on the posted example, you will be able to reproduce the problem yourself.

**Comment by alpadev** [comment]
Hm this your example with v4.0 but the behaviour seems to be the same 🤔
https://jsfiddle.net/o681cr0m/

**Comment by Printninja** [comment]
I cannot explain it. Maybe they updated the pre 4.6 versions of bootstrap.min.css on all the CDNs, but below is a website that uses a locally hosted bootstrap.min.css from December 2020, and as you can see, if you shrink the browser window below 1188 pixels, the Nav Items do not stack, they wrap, and definitely I did not alter the nav flexbox settings. You can inspect the nav using F12 developer tools, and you'll see that the stock setting for the `.nav` in the bootstrap.min.css file is `flex-wrap: wrap;`

This site was last updated Dec 5, 2020. 

https://santascott61.com/

**Comment by alpadev** [comment]
But your example from above (https://thelightwavegroup.com/na/) lacks the `.nav` class 😯

**Comment by Printninja** [comment]
You're correct, my example doesn't have the .nav class, and since you have pointed that out, I'm at a complete loss as to understand why. I need to investigate this some more. Something weird is going on.

**Comment by Printninja** [comment]
I believe I have figured out the problem. I think it's a bug in the software builder I'm using, not Bootstrap. But I would not have discovered it without your help alpadev, so thank you.

**Comment by Printninja** [comment]
Apologies to ffoodd for jumping to conclusions.

**Comment by ffoodd** [comment]
Sharing is caring! Thanks for your report and researches.
