### ISSUE TITLE
Color not working on Bootstrap 4 input

### ISSUE THREAD

**Issue by TonyScarpelli** [twbs/bootstrap#34000]
I am using NSB AppStudio version 8.5.4.0  which uses Bootstrap 4 controls.
This is my code for an input control.
**txtTSodium.style.color = "red"**
This doesn't seem to be working right, no red color is visible.
I was wondering if the code is wrong, or is the color option not working correctly in the control. I can't find out.
Can someone help me on this?
Thanks.

**Comment by ffoodd** [comment]
I suggest you ask on Slack or StackOverflow. This doesn't seem related to Bootstrap at all, so I'm closing this on our side—feel free to comment back if it happens to be a Bootstrap bug.
