### ISSUE TITLE
Apply .text-dark for .badge with some .bg-* classes

### ISSUE THREAD

**Issue by theonlypwner** [twbs/bootstrap#34016]
In Bootstrap 4, `class="badge badge-light"` was enough, but in Bootstrap 5, it's `class="badge bg-light text-dark"`. This is less convenient when switching between `badge bg-dark` and `badge bg-light`, since `text-dark` also has to be added or removed.

Bootstrap 5 should apply the styles for `text-dark` to `.badge.bg-light` and `.badge.bg-warning`. The Bootstrap 5 docs also recommend `text-dark` for `bg-info`, but I find that one is not necessary.

One workaround is to add this to our SCSS files, which is what [Bootswatch](https://github.com/thomaspark/bootswatch) does:
```scss
@import "~bootstrap/scss/bootstrap";

.badge {
  &.bg-warning,
  &.bg-info, /* optional */
  &.bg-light {
    @extend .text-dark;
  }
}
```

**Comment by ffoodd** [comment]
We removed it on purpose since it's basically duplicated code: it's even more flexible since you can mix background and foreground colours as you need.


I don't think we'll get this back, then.

Also using dark text colour is recommended to ensure sufficient contrats against light background. Using our core colours, other theme colours would fail regarding accessibility. Si Ils recommend to stick with it, obviously.

In my opinion, `color` and `background-color` should always be paired to ensure contrats. That's what I did [in a branded fork called Boosted](https://www.github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/tree/v5-dev/scss%2Fmixins%2F_utilities.scss).

Keeping this open to discuss!

**Comment by florianlacreuse** [comment]
We don't use yet BS5 in real development projects but I agree with @theonlypwner, having to specify the color makes the use of badges less simple (imho).

We had already planned to add an override on our side to fix this. @ffoodd Thanks for the idea used in your BS fork (nice project btw), I'll use it if BS don't add pairing constraints for `color` and `background-color`.

So +1 to not have to add text color css class while using BS `badge`, `background`, etc., whatever the solution is.

**Comment by theonlypwner** [comment]
Also, there is a similar issue with `card` requiring `text-white`, introduced in Bootstrap 4.

**Comment by ffoodd** [comment]
@theonlypwner This issue concerns v5 and badges, could please open another issue for what you found please?

**Comment by theonlypwner** [comment]
@ffoodd I opened #34200 for `card`. Would #34045 already fix it, as some `bg-*` classes would set `color` and effectively apply `text-white`?

**Comment by ffoodd** [comment]
Yes it would but I doubt it gets merged.

**Comment by crdo** [comment]
@ffoodd why don't you apply the same approach with the Buttons?

**Comment by ffoodd** [comment]
Because for buttons we need to handle states, so it'd require to add states support top color utilities.

**Comment by crdo** [comment]
I thought it the other way around - badges could leverage the color-contrast function as well and keep the text-color utility classes for special cases…

**Comment by florianlacreuse** [comment]
With this issue still open, what's the status of the problem on the Bootstrap team side?
For end users, the previous badge color scheme was much simpler. IMHO, for badges we should not have to choose the color of the text.

If there are too many side effects by changing the backgrounds utilities, may be `badge-${color}` should be reintroduced?

**Comment by mdo** [comment]
Thinking it might make sense to revisit this for v5.3.0. Going to leave open for now—please feel free to open any PRs you think might be helpful in the mean time :).

**Comment by septatrix** [comment]
Maybe this can be closed with the new `text-bg-*` classes?

**Comment by mdo** [comment]
Yes, it definitely can!
