### ISSUE TITLE
5.0.1: row and cell background colours broken when using a non-transparent $table-bg (regression)

### ISSUE THREAD

**Issue by legoadk** [twbs/bootstrap#34012]
Caused by fix for #33817.

If I have a $table-bg set via sass that's something other than transparent (for example, white), I can no longer change the cell background colour; it remains white.

Reversing the fix to #33817 resolves all of these issues.

**Comment by ffoodd** [comment]
Would you mind a reduced test case, please?

FWIW I think we need to introduce a new variable dedicated to accent background, to decouple it from standard backgrouns  🤔

**Comment by legoadk** [comment]
> Would you mind a reduced test case, please?
> 
> FWIW I think we need to introduce a new variable dedicated to accent background, to decouple it from standard backgrouns 🤔

I'll build a quick version of Bootstrap with $table-bg set to white to provide an example, along with a simple html table. Stand by.

**Comment by legoadk** [comment]
> Would you mind a reduced test case, please?
> 
> FWIW I think we need to introduce a new variable dedicated to accent background, to decouple it from standard backgrouns 🤔

Here you go. Style.css is a quick 'n dirty 5.0.1 built from the "bootstrap-npm-starter" package, with `$table-bg: white` set before the bootstrap imports, and the table scss imported.

https://playcode.io/769137/
