### ISSUE TITLE
Adding space between utilities

### ISSUE THREAD

**Issue by bastinald** [twbs/bootstrap#34015]
We can currently use the new `gx-*` classes for flexbox and grids, but what about spacing between other elements?

Right now, we have to use margin utilities for every item. Sometimes we want an even spacing between items without having to worry about last items in loops.

Example with CSS code: https://tailwindcss.com/docs/space

Having some handy classes like `s{x/y}-{sm-xxl}-{0-5}` utilities would be amazing.

It can be used in conjunction with the spacing SCSS variables.

Thoughts?

**Comment by ffoodd** [comment]
Makes sense, could relate to #33986 at some point, too.

Would be pretty easy thanks to our utility API.

**Comment by mdo** [comment]
Using `.d-grid` or `.d-(-inline)-flex` with `.gap-*` utilities should cover this depending on your browser support. For example, Safari just added the support for gap on flexbox but only for v14-ish and up.
