### ISSUE TITLE
Docs: Readonly input example should have a value

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#34017]
This isn't really a big deal or anything, but the first example for the readonly input at: https://getbootstrap.com/docs/5.0/forms/form-control/#readonly doesn't have a value. The text displaying is the placeholder. I think it'd be more like a real-world example if the input had that text as a value instead.

REF: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly

Let me know what you think - happy to open a quick PR.

**Comment by rajesh2kumar96** [comment]
#34040
