### ISSUE TITLE
Toast is hidden under offcanvas

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#34028]
If you have a offcanvas open and show a toast then the toast gets hidden under the offcanvas. I expected to the toast to always be visible on top of everything else.

Browser: Firefox 88, Chrome 90, Edge 92
Demo: https://jsfiddle.net/zrtv9f0d/

**Comment by jasonsperske** [comment]
the `toast-container` doesn't define a z-index, in the docs they specify add `style="z-index: [number]"` to the element, and if you want it to appear over the `offcanvas` element (which has a `z-index` of `1050`) you can use a number greater than it like this: https://jsfiddle.net/kftu40cw/

**Comment by vanillajonathan** [comment]
I only found 1 reference to `z-index` in the [Toast](https://getbootstrap.com/docs/5.0/components/toasts/) documentation and that was in the example code without any paragraph mentioning it. I did not find any reference to `z-index` in the [offcanvas](https://getbootstrap.com/docs/5.0/components/offcanvas/) documentation.

My expectation was that toasts would always show regardless of any condition, but my expectation may be wrong and the current behavior might be the intended behavior.

**Comment by jasonsperske** [comment]
It would be pretty easy to add a z-index-toast to https://github.com/twbs/bootstrap/blob/55a0f9af2738daafe8d961ca35c22800c710bb27/scss/_variables.scss#L906, I don't know if there is an official stance on this though, could always try and make a pull request and see if it gets approved.

**Comment by jasonsperske** [comment]
Or you can think of Toasts as a form of popover which is defined with a higher z-index than offcanvas.  What would be cleaner, a separate value so people can customize it or a semantic equivalent to an existing value?

**Comment by jasonsperske** [comment]
This branch adds the zindex-toast and applies it to the .toast element

  https://github.com/jasonsperske/bootstrap/tree/toast-z-index

  demo:https://jsfiddle.net/1a9tw706/

**Comment by vanillajonathan** [comment]
Yeah, this looks good, then I can just raise a toast while having a offcanvas open and it just works without having to manually mess with any z-index.

**Comment by jasonsperske** [comment]
Oh, this is interesting, if you look at _toasts.scss there is this class: https://github.com/twbs/bootstrap/blob/main/scss/_toasts.scss#L22-L30 however if you look at the examples in the docs (https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/components/toasts.md#live) the class isn't applied to the outer div.  This draft pull request looks about right to me when I test it locally https://github.com/twbs/bootstrap/pull/34054 but a propper bootstrap maintainer would need to weigh in on if it's right to create a new variable for this.

**Comment by ffoodd** [comment]
As mentionned in the PR, I think a modal should be shown above a toast, but I mau be wrong too.

Regardless, positionning toast seems an edge IMHO, since each project may want a different placement. That's why we recommend using `position` utilities ans dont set defaults.

If we're going this way, I think we need to  set a default `position` alongside `z-index`. All of those could then be overriden with utilities (apart from `z-index` for now, PR exists tonadd them).

Any thought?

**Comment by vanillajonathan** [comment]
> As mentionned in the PR, I think a modal should be shown above a toast, but I mau be wrong too.

But a modal may contain a button that triggers a toast.

**Comment by ffoodd** [comment]
Then the toast lives inside the modal and you're safe — otherwise you're doing it wrong since everything behind a modal is made inert as recommended for accessibility.

**Comment by mdo** [comment]
I'm not 100% sure what we should do, but maybe we add `position: relative` and `z-index` to the `.toast-container` for now. Could resolve the immediate issue of not having an answer to "how does this behave inside our overall system?", which feels like an oversight on our part for sure. I'd go with a `$zindex-toast: 1090` I think to treat it like tooltips and popovers as it's a traditionally an important notification type that I expect to overlay everything else in iOS and macOS.
