### ISSUE TITLE
Use nav theme classes for nav elements?

### ISSUE THREAD

**Issue by matthijsleenen** [twbs/bootstrap#34032]
I would like to be able to use the nav-dark class on a nav element with pills inside. Is it possible to extend the navbar theme to nav elements?

**Comment by mdo** [comment]
I don't think we'll go this route given the upcoming CSS variables changes we're hoping to implement. That'd tackle the customization and theming angle better IMO. Until then, you could `@extend` the `.navbar-dark` class and see if that gets you close to what you need.
