### ISSUE TITLE
invalid property id

### ISSUE THREAD

**Issue by jettheme** [twbs/bootstrap#34030]
Hi Bootstrap,
since update 5.0.0-beta2 to 5.0.0-beta3
I found an error warning for my old browser using firefox 5.2, but for modern browsers it is still fine.

(invalid property id) on bootstrap.bundle.js: 1208: 17
(invalid property id) on bootstrap.bundle.min.js: 6: 11338

(invalid property id) on bootstrap.js: 1230: 17
(invalid property id) on bootstrap.min.js: 6: 11689 

- Browser and version (Firefox version 5.2)

Thanks

**Comment by ffoodd** [comment]
Thanks for reporting, but v5 only supports Firefox 60 and above.

If that does not concern Firefox 60, we'll close this as won't fix.

Could you provide a reduced test case, so that we can check?

**Comment by mdo** [comment]
Closing as a won’t fix ahead of any reply on this one :). If this issue persists in supported versions, please let us know.

**Comment by jettheme** [comment]
yes i just want to report. and hope if possible it will be fixed in future updates.
Thank you
