### ISSUE TITLE
Community IRC: move from freenode to libera

### ISSUE THREAD

**Issue by midzer** [twbs/bootstrap#34049]
> freenode infrastructure will soon be transferred to Freenode Limited and its agents

via https://libera.chat/news/welcome-to-libera-chat

Docs recommend freenode IRC on https://getbootstrap.com/docs/5.0/getting-started/introduction/#community

Meanwhile I've setup `#bootstrap` on `irc.libera.chat`. I welcome others to join as well.

**Comment by XhmikosR** [comment]
We can do it, sure. Just make sure please you notify the users of the current channel by changing the channel message.

A PR is welcome, and I can take care of backporting it to v4-dev if merged.

**Comment by midzer** [comment]
I just left a message there for the new channel. Afaik (only?) hoek on IRC can change the channel topic.

Will do PR in a minute...

**Comment by bardiharborow** [comment]
You beat me to it! I will be in touch with Libera soon so they don't kick the channel; they like to have a project contact in place for first-level channels. @midzer in the meantime would you be okay adding me (NickServ: bardi) as an admin to the channel?

**Comment by XhmikosR** [comment]
Just registered too, ideally I should also have admin rights. :)

**Comment by bardiharborow** [comment]
@XhmikosR Libera have registered us. I'll get you, and any other team who want admin sorted when I get back from camping. ⛺
