### ISSUE TITLE
Unreachable arrows for input numbers in Firefox

### ISSUE THREAD

**Issue by ns-group-dev** [twbs/bootstrap#34042]
We've been reported by Firefox users (mainly Windows) that, during March or April, they couldn't click anymore on arrows of input numbers (with class ".form-control").

`<input type="number" class="form-control">`

Indeed after some tests, the ".form-control" class adds a right padding inside the input, causing the arrows to appear with a padding (that was intended), but not the "click" area! Actually, you need to target the right of the arrows with the cursor, to be able to click on them.

I guess this is considered as a browser issue?
However a quick fix (until a next Firefox update) is to cancel the right padding for input numbers using the ".form-control" class.
Like...
`input[type="number"].form-control { padding-right: 0; }`

**Comment by GeoSot** [comment]
Closed as duplicated of #34021 #33725
