### ISSUE TITLE
Create Dropdown Searchable and should be like combobox

### ISSUE THREAD

**Issue by imprathamesh** [twbs/bootstrap#34059]
We need some feature like this in bootstrap 5 quickly. 
check this https://developer.snapappointments.com/bootstrap-select/ 
we need similar to this inbuild in bootstrap 5. 

Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by alecpl** [comment]
This is extra 60KB of minified code. I don't think this is a good idea, better to keep it separate.

**Comment by imprathamesh** [comment]
In BS 5 they deprecated the Jumbotron and some other stuff too. I know that not gonna be big thing to BS to do combobox. 
I think they should add and then give dev to choose which js function. If we need it in our project then we will add into it.
