### ISSUE TITLE
Sass deprecation warning: Using `/` for division is deprecated

### ISSUE THREAD

**Issue by btakita** [twbs/bootstrap#34051]
dart-sass has deprecated `/` in favor of `math.div`. Compiling https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss now results with many sass warnings.

```
368 │ $navbar-padding-horizontal:        floor(($grid-gutter-width / 2)) !default;
    │                                           ^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss 368:43  @import

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($grid-gutter-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

**Comment by ralphjesy12** [comment]
Same issue. Builds now crashing because of warnings.

**Comment by Acmion** [comment]
Same issue. 

Especially annoying since you can not "mute" sass warnings. This is a problem with Sass and not Bootstrap, but still affects the user experience.

**Comment by XhmikosR** [comment]
@ffoodd I just hit this in the npm starter project with sass 1.33.0. Now, it is a warning only, but it's annoying because it's repeated many times. My understanding is that the proposed methods don't work with node-sass which is OK for v5.0.0, but for v4 we need to think about it... I was planning to switch to sass in v4 too but perhaps we should do it in a minor version bump.

PS. I run dependabot so that we get the updated PR and see the warnings.

**Comment by DhyeyMoliya** [comment]
Getting the same ton of warnings.

**Comment by lothargrieb** [comment]
Same problem here... hopefully not to much work for the boostrap team.

**Comment by Onefivefournine** [comment]
Hope that the team will fix it soon! I am now unable to start dev build because of huge amount of warnings.

Guys from sass refuse to add any silencer for warnings, because they think that warnings are critical, and you should never silence them, even if there are 100k warning lines in your dev build.
https://github.com/sass/libsass/issues/2822#issuecomment-482914373

**Comment by vbarden** [comment]
> **UPDATE:** Solved by manually downgrading sass to 1.32.*

Can confirm downgrade works. 

Thanks @Onefivefournine

**Comment by jeremy-holt** [comment]
I'm using gulp-dart-sass. How would I downgrade to sass 1.32 (I don't think gulp-dart-sass uses sass)?

**Comment by rivajunior** [comment]
> I'm using gulp-dart-sass. How would I downgrade to sass 1.32 (I don't think gulp-dart-sass uses sass)?

@jeremy-holt yes, gulp-dart-sass uses sass package

**Comment by XhmikosR** [comment]
Please everyone stop spamming the issue. We will find a solution for v5. You should bug though the Sass devs to allow to hide these warnings. IMHO it's pretty bad right now.

**Comment by acantepie** [comment]
Senseless. Insta revert to 1.32 ... A feature request was already created but ignored

**Comment by apolopena** [comment]
See https://github.com/sass/dart-sass/issues/1319

**Comment by vinorodrigues** [comment]
[sass/dart-sass](https://github.com/sass/dart-sass/releases/tag/1.34.0) has released v1.34.0 that adds a `--quiet-deps` flag.
Amend this to `package.json`, line #26 under `"css-compile"`

* `--quiet-deps` still has warnings, but not so many (recommended)
* `--quiet` gets rid of all the warning, but may not be a good idea

**Comment by exeptionerror** [comment]
[[Solved] Using / for division is deprecated and will be removed in Dart Sass 2.0.0 in Nuxtjs](https://exerror.com/solved-using-for-division-is-deprecated-and-will-be-removed-in-dart-sass-2-0-0-in-nuxtjs/)

**Comment by exeptionerror** [comment]
[[Solved] Laravel Mix | Bootstrap DEPRECATION WARNING: Using / for division is deprecated and will be removed](https://exerror.com/laravel-mix-bootstrap-deprecation-warning-using-for-division-is-deprecated/)

**Comment by xzhz** [comment]
很无语

**Comment by exeptionerror** [comment]
[[Solved] Using / for division is deprecated and will be removed in Dart Sass 2.0.0 in Nuxtjs
](https://exerror.com/solved-using-for-division-is-deprecated-and-will-be-removed-in-dart-sass-2-0-0-in-nuxtjs/)

**Comment by bramceulemans** [comment]
@exeptionerror has been spamming the same link already 5 times or something.

**Comment by mmarton** [comment]
"solution"... by fixing sass compiler to an older version... 

a solution would be something like a polyfilling math.div() for node-sass and replaceing it everywhere in the code

**Comment by ffoodd** [comment]
Polyfilling isn't an option IMHO, this is simply not compatible.
The best way I can think off for now is to add a new dedicated function for `div()` —just like we already have `add()` and `subtract()`— and ensure every division uses it in our core. Then anyone willing to use latest Dart Sass could just change this function to use `math.div`. We may even add this variant in our core, without including it in our default build.

AFAIK there's no way to either check for `@use` support nor switch code depending on compiler, so the best we'll be able to do is to facilitate using one or the other on dev side.

Any thoughts or ideas are welcome, obviously!

**Comment by ngekoding** [comment]
> Hope that the team will fix it soon! I am now unable to start dev build because of huge amount of warnings.
> 
> Guys from sass refuse to add any silencer for warnings, because they think that warnings are critical, and you should never silence them, even if there are 100k warning lines in your dev build.
> [sass/libsass#2822 (comment)](https://github.com/sass/libsass/issues/2822#issuecomment-482914373)
> 
> **UPDATE:** Solved by manually downgrading sass to 1.32.*

Thanks, solved for Element Plus also.

**Comment by e200** [comment]
Just update your sass version to exatcly **1.32.13**

**Comment by vince7488** [comment]
Downgrading may be a solution that works, but it's bad advice.  

The real solution is actually posted on the SASS warning on the terminal.  

`Recommendation: math.div($grid-gutter-width, 2)`

## full solution:

```scss
@use "sass:math";   //must be placed on top of your scss file

div.sample {
     width: math.div(100%, 2)
}
```

**Comment by ffoodd** [comment]
That won't happen soon, as it'd break Libsass compatibility, as stated above.

**Comment by apolopena** [comment]
Libsass is depricated, time to cut the cord?

**Comment by bramceulemans** [comment]
What would be the deprecation plan for libsass in Bootstrap?

**Comment by shehi** [comment]
You guys just released 5.x - better get rid of LibSass at this point, before it gets too late.

**Comment by alpadev** [comment]
Please people, calm down.. You need to understand that it's less about us but rather that we care about our users.. The situation is completely awkward for us too, because we try as much as possible to support both, libsass and dart-sass, without breaking peoples' setup. The Sass team decided to deprecate the default way of doing division, without providing a real option to do this in a graceful way. Considering that a lot of setups broke because of those warnings.

Like @ffoodd pointed out already, in theory, there would have been the possibility to script around this problem by adding necessary functionality into the language upfront. However, at this point we're still trying to find a way that would work with both compilers, so we don't have to break the compatibility.

It's actually not that hard for us to go through the files and replace things, but we don't give a damn about people still using libsass for whatever reason..

**Comment by shehi** [comment]
@alpadev , many of us here are open-source devs already. We are calm, and we already know the topics you are advocating here. We are rather calm.

My argument was: Bootstrap 5 was just released, with a new major version. The fact that a deprecated tech was still actively supported in this new version without considering the possibility that others might move on (like Dart Sass did, which is the future of Sass). Now clearly as far as I can see, that "backfired". That's why I suggested to fix that "mistake" as fast as possible, dropping a clarification/reasoning blogpost behind this decision to your users. Otherwise, we will have to live with it until Bootstrap 6. Otherwise, as I already mentioned, we understand your points.

**Comment by Erbolking** [comment]
`yarn add sass@1.32.*`

This fixed the problem for me.

**Comment by maartenelgar** [comment]
> `yarn add sass@1.32.*`
> 
> This fixed the problem for me.

Massive help thanks! Fixed all the warnigngs

**Comment by forgetallpast** [comment]
It's the one fixed all this warnings...  Cost about half to one hour ....
[https://github.com/forgetallpast/bootstrap-scss-v5.0-no-warning](https://github.com/forgetallpast/bootstrap-scss-v5.0-no-warning)

**Comment by LoranKloeze** [comment]
If you use Rails, add this to your package.json as a **temporary** solution:
```
  "resolutions": {
    "@rails/webpacker/**/sass": "1.32.12"
  }
```

Don't forget to run ```yarn install``` afterwards.

Did I already mention this is a **temporary** solution? Because downgrading is bad and this is downgrading so it's bad.

**Comment by UsamaAshraf82** [comment]
+1

**Comment by mdo** [comment]
I've been slow to respond because of some travel lately, so apologies. In talking with the maintainer team over Slack off and on the last few days, we still don't have a single bulletproof solution. Here's a summary from my perspective on past decisions and current status.

**Our default and preferred Sass compiler is Dart Sass.** [See our docs for a mention of this.](https://getbootstrap.com/docs/5.0/getting-started/build-tools/#sass) Libsass is tested via CI to ensure compatibility, but we don't really need it IMO. We test for it to ensure compatibility, but I think we can call that covered with v4.x being maintained for a little while longer. If we completely drop Libsass (we technically already did, we just test for it as a nicety here), we can use the `math.div()` function.  I'm in favor of this.

Alternatively, and still incomplete and somewhat complicated, **I've prepped a [branch to change most division to multiplication](https://github.com/twbs/bootstrap/compare/drop-sass-division)** where I can. For example, ` $variable / 2` is now `$variable * .5`. However, the incomplete part is our grid columns mixin, RFS, and some color functions use much more complicated math. Not as simple as the rest. I don't know how best to tackle that unless we implement some clever custom `divide()` function (which @alpadev has spiked out elsewhere). This approach doesn't feel right IMO.

Putting it all together, I think we do the following:

1. Convert what we can to multiplication for clarity and brevity.
2. Use the `math.div()` function for things that cannot be as easily converted and for RFS (which is vendor-ed into our `_scss` folder).
3. If needed, update our documentation to clarify Dart Sass.

Let me know your thoughts, folks. I'd love to get this fixed and then ship v5.0.2 so we can move onto v5.1.0.

**Comment by cverond** [comment]
> Alternatively, and still incomplete and somewhat complicated, **I've prepped a [branch to change most division to multiplication](https://github.com/twbs/bootstrap/compare/drop-sass-division)** where I can. For example, ` $variable / 2` is now `$variable * .5`. However, the incomplete part is our grid columns mixin, RFS, and some color functions use much more complicated math. Not as simple as the rest. I don't know how best to tackle that unless we implement some clever custom `divide()` function (which @alpadev has spiked out elsewhere). This approach doesn't feel right IMO.

it shouldn't have been `/ 255` equivalent to `* 0.004` (choose the preferred rounding)?

**Comment by ffoodd** [comment]
Shouldn't dropping Libsass support be considered as a breaking change? Releasing this in a patch version doesn't feel right.

Other consideration: starting to use Dart Sass newest features probably needs an overall refactor. My concern is: do we simply use `math.div()` for support, or do we fully embrace Dart Sass syntax and features?

**Comment by mdo** [comment]
> Shouldn't dropping Libsass support be considered as a breaking change? Releasing this in a patch version doesn't feel right.

We don't explicitly support it, and we talk about it like we dropped it. Another example: https://blog.getbootstrap.com/2020/11/11/bootstrap-5-alpha-3/.

> Other consideration: starting to use Dart Sass newest features probably needs an overall refactor. My concern is: do we simply use `math.div()` for support, or do we fully embrace Dart Sass syntax and features?

I think we iterate our way forward. I'm not opposed to Sass modules, but that stuff is wildly verbose IMO and we don't need to address a full migration just yet.

**Comment by mistic100** [comment]
I hope you will be able to publish a 4.7.0 compatible with Dart Sass. I guess I am not alone working with many v4 plugins not yet compatible with v5 but have our build chain upgraded do newer versions of sass (in my case ng-packagr for an Angular librairy)

**Comment by dgpokl** [comment]
> Shouldn't dropping Libsass support be considered as a breaking change? Releasing this in a patch version doesn't feel right.

In my perspective, users who really want to stick with libsass can pin bootstrap at the previous (the present) version. In the long term, sass making this choice to break API compatibility does mean that if anyone's super serious about staying on libsass, they will very, very soon have to weigh whether they love libsass enough to perhaps pay someone to maintain a hypothetical "bootstrap-libsass" fork starting right about now, or if they are also willing to just stop getting updates to bootstrap. With bootstrap being pretty mature that's a pretty fair and not too burdensome ask.

I'm not really knowledgeable enough about libsass to judge whether that's a reasonable decision nowadays compared to updating your build process to use dart-sass and moving on, all I know is that switching to dart-sass was a huge speedup so 🤷‍♂️

**Comment by mistic100** [comment]
polyfill implemented by angular components https://github.com/angular/components/commit/a4043f41f539ed910c80c780e1815f5625282b94#diff-4b0d3692fae1e26970f5365a78db4ff81acb362f79ef12252081df8b285d38e8

**Comment by alpadev** [comment]
@mistic100 That's not a polyfill.. They make use of SASS modules in there. Libsass wouldn't compile with that code.

**Comment by mdo** [comment]
Slightly altered approach has arrived in #34245.

**Comment by VArsenyan** [comment]
Is there any fix? or not yet?

**Comment by corny** [comment]
Is anyone working on a fix for the `v4` branch?

**Comment by XhmikosR** [comment]
@mdo we actually need to fix rfs upstream in the 9.x branch too and update then update it here.

**Comment by wszydlak** [comment]
I've found near perfect solution to work out with supporting both libsass and dart-sass.

```
@function private-div($a, $b) {
	@if not variable-exists("__legacy-libsass") and call(get-function("function-exists"), "div", "math") {
		@return call(get-function($name: "div", $module: "math"), $a, $b);
	} @else {
		@return $a / $b;
	}
}
```

This only need's in libsass usage adding variable before any imports `$__legacy-libsass: true;`, eg.

```
$__legacy-libsass: true;

@import "~bootstrap/scss/_variables.scss"; // this needs to use private-div function
```

I think that for now this is the best solution to have compatibility both with libsass and dart-sass without any warnings.

**Comment by alpadev** [comment]
@wszydlak if you're ok with the output of `@use` to the CSS by using libsass you could also do it like so there is no need to add some variable:
```scss
@use 'sass:math' as *;

@function private-div($a, $b) {
	@if function-exists('div') {
		@return div($a, $b);
	} @else {
		@return $a / $b;
	}
}
```

**Comment by cesarkohl-voxie** [comment]
I hope 5.0.3 is released soon.

**Comment by castellinosoftware** [comment]
Is the deprecation expected to be resolved in branch 4 as well?
I know this means switching from libsass to dart, but there are projects that directly import bootstrap4 scss sources

**Comment by slavede** [comment]
I've opened PR for v4-dev here https://github.com/twbs/bootstrap/pull/34386

**Comment by aditya8762** [comment]
we can update using below code:

$ npm install -g sass-migrator
$ sass-migrator division **/*.scss

**Comment by nhhockeyplayer** [comment]
I been blocked for weeks on fortawesome in node_modules not fit with latest sass-migrator
webpack gang broke builds too
its been reckless for past 90 days

so I think Im going to ditch fontawesome

**Comment by onataliaduran** [comment]
> we can update using below code:
> 
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss

It didn't work for me, I think there are fewer warning messages, but some are still showing

**Comment by Jobin-S** [comment]
how can i solve this issue?

**Comment by brandlumin** [comment]
> `yarn add sass@1.32.*`
> 
> This fixed the problem for me.

I don't know if I did correct but ... I am on Node 12, tried it after adding sass@1.32.12 and the gulp reported no warning from sass. I know it is a bad thing to downgrade but it was highly needed at present.

**Comment by yktoo** [comment]
It would really be nice if you backported the fix to the actual mainline `4.x` version, as this is the only one used in production at the moment.

**Comment by mistic100** [comment]
@yktoo it was already done https://github.com/twbs/bootstrap/pull/34571  
Now we just wait for 4.6.1 and/or 4.7.0 release

**Comment by KKrisu** [comment]
Do you know maybe, when the release is going to happen @mistic100  ?

**Comment by mistic100** [comment]
I am not working for Bootstrap 😉

Sent from MailDroid

-----Original Message-----

**Comment by yktoo** [comment]
FYI Bootstrap 4.6.1 is out, but the issue is still there.

**Comment by darrinmn9** [comment]
@yktoo repro with the sass warning logs similar to the original issue would be helpful. Also, make sure the warning isn't originating other dependencies you may be using (or your own sass files). 

After updating to `v4.6.1`, these deprecation warnings no longer appear for me.

**Comment by yktoo** [comment]
@darrinmn9 Indeed, it was my own stylesheet that caused the warnings, after I replaced division with multiplication all warnings were gone.

**Comment by rob-mathieu** [comment]
Adding the `~` worked for me
`"sass": "~1.26.11"`

**Comment by najathi** [comment]
`npm i sass@^1.32.11`

**Comment by RamakantSonkhedkar** [comment]
[11:53:25] Starting 'build:compile-css'...
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
298 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 298:31  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2) or calc($input-padding-y / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
493 │ $input-height-inner-quarter:            calc(#{$input-line-height * .25em} + #{$input-padding-y / 2}) !default;
    │                                                                                ^^^^^^^^^^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 493:80  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2) or calc($custom-control-indicator-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
560 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 560:49  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
706 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 706:37  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
711 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 711:37  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

[11:53:29] 'build:compile-css' errored after 3.58 s
[11:53:29] Error in plugin "sass"
Message:
    build\_css\compat\components\_dropdowns.scss
Error: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
Details:
    formatted: Error: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
    line: 29
    column: 11
    file: D:\Git_Repo\Erasmith_Repo\Liferay-Theme-Workspace\themes\erasmith-theme\build\_css\compat\components\_dropdowns.scss
    status: 1
    messageFormatted: build\_css\compat\components\_dropdowns.scss
Error: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
    messageOriginal: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
    relativePath: build\_css\compat\components\_dropdowns.scss
    domainEmitter: [object Object]
    domainThrown: false

[11:53:29] 'build' errored after 9.13 s

**Comment by lcgaravito** [comment]
UPDATE: After fixing the warnings in my own code, as if I were using bootstrap v5 with sass, I was checking that the latest version of sass that bootstrap uses so far is `"1.71.0"`. So I decided not to use the latest version of sass but to switch to the same version of bootstrap, and all bootstrap related _warnings_ disappeared:

`npm i sass@1.71.0`
