### ISSUE TITLE
Enable optional flex buttons

### ISSUE THREAD

**Issue by lekoala** [twbs/bootstrap#34058]
Currently the buttons have this default style

```css
display: inline-block;
text-align: center;
vertical-align: middle;
```
It would be great if there was a new variable called $enable-flex-buttons that would default to false that would change these styles to

```css
display: inline-flex;
align-items: center;
justify-content: center;
```

It makes working with buttons much easier (like, having svg icons in them becomes much easier) and there are no drawbacks to my knowledge to do this instead of regular inline-block.

Demo to play with
https://codepen.io/lekoalabe/pen/JjWExoN

Remove the css to see the layout shifting. With inline-flex it works nicely.

**Comment by ffoodd** [comment]
There are a few drawbacks in fact, see #30923 and [linked CodePen](https://codepen.io/MartijnCuppens/pen/LYpwjXy) for an example.

Still in favor of this, but definitely could break things.

**Comment by lekoala** [comment]
Ok I should have done more research on this one :-D I wasn't aware of the whitespace space issue and the issue with the long texts.

For the collapsing whitespace, I think it could be fixed, mostly, with 

```
.btn-flex > * {
  margin-right: 0.5ch;
}
```

provided than you also use span tags if necessary (not necessary for leading icon for example). Not ideal nevertheless... 

`flex-flow: wrap;` fixes also mostly the issue with long content but again it doesn't behave exactly the same. Mhh so it has advantages but also drawbacks. Still interesting to have. Maybe a btn-flex class would be better than enabling this globally.

**Comment by ffoodd** [comment]
Any suggestion welcome 🙂 For now it looked easier to use flex utilities for such cases.

**Comment by mdo** [comment]
Closing as a won't fix at this time :).
