### ISSUE TITLE
Navbar collapse transition glitchy after toggling dropdown within

### ISSUE THREAD

**Issue by o-alquimista** [twbs/bootstrap#34066]
The navbar collapse transition is glitchy after you have toggled a dropdown within. It collapses abruptly.

Can be reproduced anywhere. Bootstrap Navbar example: https://getbootstrap.com/docs/5.0/examples/navbar-bottom/

![Peek 21-05-2021 17-14](https://user-images.githubusercontent.com/25424263/119193824-984cf200-ba58-11eb-88f6-90eae8137548.gif)

It's more noticeable when you collapse the navbar with an open dropdown.

Ubuntu Desktop 20.04 LTS
Firefox 88.0.1 and Chromium 90.0

**Comment by alpadev** [comment]
@o-alquimista can you please try to reproduce that via this url? https://deploy-preview-33845--twbs-bootstrap.netlify.app/docs/5.0/examples/navbar-bottom/

I could imagine that this will be solved by #33845.

**Comment by o-alquimista** [comment]
Yep, it's fixed there :)

**Comment by alpadev** [comment]
Thanks, appreciate it! :heart:
