### ISSUE TITLE
data-bs-backdrop and data-bs-keyboard not functioning on v5.0.1

### ISSUE THREAD

**Issue by javierian1313** [twbs/bootstrap#34069]
Trying to use the data-bs-backdrop="static" and data-bs-backdrop="false" to manipulate how the modal backdrop is working. It worked on the 5.0.0-beta2 version. However, it does not seem to be working on the 5.0.1 version. The data-bs-keyboard also seems to not be working.

Since finding the issue, I confirmed once more that the 5.0.0-beta2 version allows for data-bs-backdrop and data-bs-keyboard to be used. Seems to be only on the 5.0.1 version as far as I am aware.

**Comment by GeoSot** [comment]
Hey @javierian1313 

Please can you provide any live examples of this issue?

**Comment by javierian1313** [comment]
![example](https://user-images.githubusercontent.com/62947072/119206684-1ad5b180-ba59-11eb-94d0-7c95fe4ae89c.gif)

And here is a snippet of the code powering it.

```
<div
      className="link-danger cursor text-decoration-underline"
      data-bs-toggle="modal"
      data-bs-target="#modal_remove_item"
      data-bs-backdrop="false"
      data-bs-keyboard="false">
      Remove
</div>
```

Not sure if that helps any.

**Comment by javierian1313** [comment]
Also, changing the data-bs-backdrop="static" has the same behaviour as shown.

**Comment by javierian1313** [comment]
![example2](https://user-images.githubusercontent.com/62947072/119207203-b0257580-ba5a-11eb-8133-fa4bb91af993.gif)

Here is another example of it working on the 5.0.0-beta2 version.

I only changed the data-bs-backdrop="static" to show it functioning. Other than that, the snippet provided has been unmodified. Only the Bootsrap Version.

**Comment by GeoSot** [comment]
Tried it now on doc page and works.
Please try to replicate it using this [codepen template](https://codepen.io/GeosSV/pen/poeeyOb)

**Comment by javierian1313** [comment]
It works in there great!

I am using the cdn version in my application.

The links that work:
```
<link
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
     crossorigin="anonymous"
/>
<script
     src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
     crossorigin="anonymous"
></script>
```

The links that don't work:
```
<link
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
     crossorigin="anonymous"
/>
<script
     src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
     crossorigin="anonymous"
></script>
```

Do you think the issue is more with this?

**Comment by GeoSot** [comment]
The template I provide you uses v5.0.1 scripts too 😕

**Comment by javierian1313** [comment]
Weird. Well, it may be something in my application? Not sure. Cause the only thing that changes is the cdn. I will dive in more and see if it is an external problem rather than a problem with the behavior of the Bootstrap Modal.

I appreciate you looking into this! Let me know if you find anything else out.

**Comment by GeoSot** [comment]
Ok. closing it for now. Do not hesitate to reopen it if you find something new
