### ISSUE TITLE
Support for sass@1.33.0

### ISSUE THREAD

**Issue by wilo-ahadi** [twbs/bootstrap#34068]
https://github.com/twbs/bootstrap/blob/a2b5901efc6de12bb828f8dda118ddccbcd545cf/scss/_functions.scss#L140

This code work fine for **sass@^1.32.13**

For **sass@^1.33.0** support we need to use **math.div($number1, $number2)** for division : [https://sass-lang.com/documentation/breaking-changes/slash-div](url)

Or the **Sass migrator** to automatically update stylesheets to use math.div() and list.slash()
$ npm install -g sass-migrator
$ sass-migrator division **/*.scss

**Comment by mdo** [comment]
#34051
