### ISSUE TITLE
after an element with a Tooltip is removed, the Tooltip is still displayed

### ISSUE THREAD

**Issue by git-Charlie** [twbs/bootstrap#34072]
After an element with a Tooltip is removed, the Tooltip is still displayed

For example, a button has a tooltip, and when the button is clicked, the button removes itself, but the tooltip is not removed.

code see:

https://jsbin.com/golejufige/1/edit?html,css,js,output

**Comment by mdo** [comment]
From the docs:

> Tooltips must be hidden before their corresponding elements have been removed from the DOM.
