### ISSUE TITLE
Pushing body content with offcanvas

### ISSUE THREAD

**Issue by kallewesterling** [twbs/bootstrap#34093]
Could there be an option for offcanvas to push the content of the body like [here](https://www.jasny.net/bootstrap/examples/navmenu-push/)?

**Comment by Viktor-VERA2020** [comment]
I would like to build this feature! I read in the guide “Contributing to Bootstrap” that I should ask before I start a pull request for implementing features. Can I do it here or where should I ask? First time contributing to a project so unsure how to proceed...

**Comment by mdo** [comment]
Closing as stale. Still could be a rad thing to implement, so if folks want to jump in with a PR, I'd be happy to see it!
