### ISSUE TITLE
On Components/Spinners page, link to "text alignment" utility has incorrect path

### ISSUE THREAD

**Issue by AndrewSRea** [twbs/bootstrap#34113]
On the Components/Spinners page, under the "Placement" header, the link to the "text alignment" utility leads to Content/Typography page, not the Utilities/Text page (to the header "Text alignment"). 
Just thought you should be aware of this.

**Comment by annsudhart** [comment]
Newbie here, would it be okay if I give this a try? I believe the correct link should be [here](https://getbootstrap.com/docs/5.0/utilities/text/).
