### ISSUE TITLE
Bootstrap CSS conflicts with HTML5 modal dialogs

### ISSUE THREAD

**Issue by codetuner** [twbs/bootstrap#34121]
The Bootstrap CSS (5.0.1 and 4.6.0) conflicts with HTML5 dialogs in modal mode: when the Bootstrap CSS is loaded, HTML5 dialogs opened with the showModal() method seem to have a transparant overlay over it making it impossible to click on the dialog.

OS=Windows 10 19042.508
Browser=Chrome 91.0.4472.77 (64-bit)

Sample:
https://jsbin.com/suyupimato/edit?html,output
Click the link, then try to click on te input controls to change the focus.

Also:
https://jsfiddle.net/bxwr84qf/  (Bootstrap 5.0.1)
https://jsfiddle.net/29mc63bj/   (Bootstrap 4.6.0)

**Comment by mdo** [comment]
The modal shouldn't be mixed with HTML's native `<dialog>` element. You're using one class out of several—this is bound to cause issues :).

**Comment by codetuner** [comment]
Sorry, you're right. I wasn't aware "modal-dialog" is a bootstrap class. Is should have seen this...
