### ISSUE TITLE
Bad tooltip "triangle" location in RTL mode

### ISSUE THREAD

**Issue by NatanBagrov** [twbs/bootstrap#34125]
- Win 10
- Chrome latest

![image](https://user-images.githubusercontent.com/20153650/119842192-228cce80-bf0f-11eb-98a3-1a141d9b65e3.png)

```html
<a class="pointer"
  data-bs-toggle="tooltip"
  data-bs-placement="right"
  title="הצג רשומות של המשתמש הנוכחי">
            <i class="fas fa-user"></i>
</a>
```

**Comment by ffoodd** [comment]
Could you please provide a reduced test case? 

Seems to work fine [in our RTL cheatsheet](https://getbootstrap.com/docs/5.0/examples/cheatsheet-rtl/#tooltips). FYI regarding `date-bs-placement`, remember left and right are mirrored.

**Comment by NatanBagrov** [comment]
> Could you please provide a reduced test case?
> 
> Seems to work fine [in our RTL cheatsheet](https://getbootstrap.com/docs/5.0/examples/cheatsheet-rtl/#tooltips). FYI regarding `date-bs-placement`, remember left and right are mirrored.

Hey @ffoodd , please see a reproduced test case [here](https://codepen.io/natanz/pen/WNpXEmx).
Below is how I see it, hope you see the same:
![image](https://user-images.githubusercontent.com/20153650/120106112-7ba17000-c164-11eb-9f5b-cc91ead383de.png)

Also, suggested fix: swap `.bs-tooltip-start` with `.bs-tooltip-end` and vice-versa (lines: ~5535-5569).
https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.rtl.css#L5535-L5569

 I can PR against this issue. However, please note that this is more of a 'patch' in my side, since I'm not familiar with all the bits and bytes of this repo.

**Comment by alpadev** [comment]
There is no `dir` attribute with a value of `rtl` on the `html` element. Because of this, our JS fails to recognize that the document is in RTL mode and therefore does not use appropriate classes.

**Comment by ffoodd** [comment]
@NatanBagrov Can you please confirm adding `dir="RTL"` on your `html` fixes the issue?

**Comment by NatanBagrov** [comment]
@alpadev , @ffoodd - that doesn't work as well.
I've edited the code (https://codepen.io/natanz/pen/WNpXEmx) - can see for yourselves.

**Comment by ffoodd** [comment]
`dir` needs to be set on `html`— [seems to works fine](https://codepen.io/ffoodd/pen/PopEBJJ) then.

**Comment by NatanBagrov** [comment]
> `dir` needs to be set on `html`— [seems to works fine](https://codepen.io/ffoodd/pen/PopEBJJ) then.

Yea, sorry =\ just edited the comment.
