### ISSUE TITLE
Bootstrap V5.0.1 and Angular 12

### ISSUE THREAD

**Issue by hugoebarboza** [twbs/bootstrap#34135]
Is there a guide to add Bootstrap v5.0.1 in Angular 12? I have been working with Bootstrap 4.6.0, but recently I upgrade to v5.0.1, and all Bootstrap functionality crash. Thanks in advance.

**Comment by mdo** [comment]
Please stop opening duplicate threads. https://github.com/twbs/bootstrap/discussions/34127 covers this and is in the correct place. Please consult StackOverflow or our Slack channels if you need more assistance.

**Comment by hugoebarboza** [comment]
Hi @mdo, I don't find any information about this topic neither Stackoverflow, Slak, etc.

**Comment by tungphan995** [comment]
lon

**Comment by JamesVanWaza** [comment]
@hugoebarboza refer to the following link - https://ng-bootstrap.github.io/#/home

**Comment by hugoebarboza** [comment]
Thanks @JamesVanWaza , but I just use Bootstrap in my Angular App.

**Comment by hugoebarboza** [comment]
Thanks @JamesVanWaza , but I just use Bootstrap in my Angular App.
