### ISSUE TITLE
Can't compile without jquery in webpack/encore setup :-(

### ISSUE THREAD

**Issue by Defcon0** [twbs/bootstrap#34130]
Hello,

I have the following setup:

```
"@babel/plugin-transform-object-assign": "^7.12",
"@popperjs/core": "^2.9",
"@symfony/webpack-encore": "^1.3",
"autoprefixer": "^10.2",
"postcss-loader": "^5.3",
"sass": "^1.32",
"sass-loader": "^11.1",
"webpack-notifier": "^1.13"
```

My js file looks this way:

```
import 'bootstrap';

class MyClass {
...
```

Now I run `yarn encore dev` in order to generate the final js but I get the following error message causing that I can't compile:

```
"./node_modules/bootstrap/dist/js/bootstrap.esm.js" contains a reference to the file "jquery".
This file can not be found, please check it for typos or update it if the file got moved.
```

It seems that the simple occurence of the keyword `jquery` leads to that error although it won't be used anyway. But adding jquery to my package.json is not an option because this would cause jquery to be loaded which I want to avoid.

Thanks in advance for clearification what I can do.

Bye Defcon0

Meta info:

- Operating system and version (Windows, macOS, Android, iOS): Linux Mint 19.1
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser): Chrome (latest)
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/): not possible in this context

**Comment by alpadev** [comment]
That seems to be related to Encore. Are you using `Encore.autoProvidejQuery()` by any chance?

**Comment by Defcon0** [comment]
omg. You're totally right :-) I forgot, to remove that one. Big thanks for your help!
