### ISSUE TITLE
Bootstrap alert autoclose

### ISSUE THREAD

**Issue by atoaugustyn** [twbs/bootstrap#34138]
Would it be possible if Options can be passed via data attributes or JavaScript. For example,  using of **data-bs-auto-close="true"** for alerts to be closed automatically after 5 seconds

**Comment by jjoel1630** [comment]
Let me try to work on that @atoaugustyn.

**Comment by ffoodd** [comment]
Alerts are not supposed to close automatically: the toast component is the correct pattern for this.

**Comment by atoaugustyn** [comment]
@ffoodd if I may ask, why are alerts not supposed to close automatically?

**Comment by ffoodd** [comment]
Mostly for accessibility concerns: content appearing dynamically is sensitive and requires the `alert` role, but timed content is a step above and requires ot ensure that content can be accessed and read while it's shown. Alert component does not handle this, toast component does thanks to a few attributes: `aria-live="assertive" aria-atomic="true"`.

Moreover [as mentioned in the toast docs](https://getbootstrap.com/docs/5.0/components/toasts/#accessibility), you need to define a delay that allows any user to read content.

As a matter of fact, a component able to autohides already exists so I'd recommend you to simply style it the way you need it. :)

**Comment by atoaugustyn** [comment]
Alright that's fine
