### ISSUE TITLE
Suggestion: add a corner label layout example on the badge page

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#34131]
https://getbootstrap.com/docs/5.0/utilities/position/#examples
https://getbootstrap.com/docs/5.0/components/badge/

Add a corner label example to the badge page to use the new positioning class for layout.

**Comment by jjoel1630** [comment]
Hey @ZhangChengLin, would it be possible to elaborate a little bit more?

**Comment by ZhangChengLin** [comment]
> Hey @ZhangChengLin, would it be possible to elaborate a little bit more?

徽章组件页面，添加角标使用的示例。

就是圆形的徽章在图标的右上角的位置出现。徽章内为数字，用以表示信息的数量。这在手机中是很常见的提示方法。

**Comment by jjoel1630** [comment]
Hey, can you please provide an example of the corner badge. I am not sure how it looks like. Sorry about that.

**Comment by ZhangChengLin** [comment]
> Hey, can you please provide an example of the corner badge. Would it look something like this? The blue badge on the top right  corner?
> 
> ![image](https://user-images.githubusercontent.com/68816736/120052092-65ff3f80-bfd8-11eb-8575-708f1cf138fd.png)
> 

![Screenshot_20210529_095440_com.huawei.android.launcher.png](https://user-images.githubusercontent.com/30773389/120054705-0c445700-c064-11eb-9b64-211a7d72475d.png)

**Comment by jjoel1630** [comment]
Thank you. Can someone please assign me to this issue, or may I just start working on this right now?

**Comment by jjoel1630** [comment]
Before submitting a PR, was this what @ZhangChengLin would like to see on the documentation? Please let me know so that I can submit a PR. 

![image](https://user-images.githubusercontent.com/68816736/120058404-7d055800-bfff-11eb-88a8-84cf0bf94873.png)

**Comment by ffoodd** [comment]
@jjoel1630 I think you're right, feel free to open a PR 👌

Please read pour contribution guidelines first, so that it's clean from the beginning. Thanks!

**Comment by ZhangChengLin** [comment]
> Before submitting a PR, was this what @ZhangChengLin would like to see on the documentation? Please let me know so that I can submit a PR. 
> 
> ![image](https://user-images.githubusercontent.com/68816736/120058404-7d055800-bfff-11eb-88a8-84cf0bf94873.png)
> 

Another more mainstream usage is to replace the button with an a element, the a element is a font icon, and then the digital badge is placed in the upper right corner.

**Comment by ffoodd** [comment]
We don't use font icon anymore and prefer to use Bootstrap Icons' SVG instead. You're welcome to add exemples, we'll see if they make sense or not 🙂

**Comment by ZhangChengLin** [comment]
> We don't use font icon anymore and prefer to use Bootstrap Icons' SVG instead. You're welcome to add any example, we'll see if they make sense or not 🙂

For example, the PC version of the GitHub site, the bell icon in the header, and the corner marker in the upper right corner, if you add a digital corner marker inside.
 How to achieve with svg?  This should be the more common way.
 In other words, add a digital superscript prompt for the svg icon.

**Comment by jjoel1630** [comment]
> @jjoel1630 I think you're right, feel free to open a PR 👌
> 
> Please read pour contribution guidelines first, so that it's clean from the beginning. Thanks!

Great thank you! I will be submitting a PR very soon.

**Comment by jjoel1630** [comment]
I have created a PR. Hopefully it will get merged on to the main branch.

**Comment by tungphan995** [comment]
marion

**Comment by ZhangChengLin** [comment]
https://github.com/twbs/bootstrap/pull/34143
