### ISSUE TITLE
Model's Links not clickable when using fixed-top class or sticky-top

### ISSUE THREAD

**Issue by shsarv** [twbs/bootstrap#34141]
I am using bootstrap5 and used a model for a button in my navbar but when I am making my navbar fixed-top or sticky-top, the model appears but I am not able to perform any action on that as well as my screen; also, my screen opacity is getting decreased

![done](https://user-images.githubusercontent.com/55739302/120078335-a5a75380-c0cc-11eb-973a-63d6e69ea0d5.png)

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by shsarv** [comment]
here is the **Live demo** available on codepen [https://codepen.io/shsarv/pen/NWpwRaq](https://codepen.io/shsarv/pen/NWpwRaq) . Click on the logout or signup or sign in button to see.

**Comment by craftwerkberlin** [comment]
@shsarv You must place the modal outside of the navbar, then it works. Toggler button can be inside navbar.

**Comment by shsarv** [comment]
@craftwerkberlin thank you. i got it.
