### ISSUE TITLE
V5 : [BUG] Horizontal Cards

### ISSUE THREAD

**Issue by sauravkr818** [twbs/bootstrap#34145]
**BOOTSTRAP V5**

- [x] Operating System = **Windows 10**
- [x] Browser = **Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)**

**Under horizontal section in Card Component** ,i.e., https://getbootstrap.com/docs/5.0/components/card/#horizontal

- image is not fit to the `col-md-4`
- **LIVE example** = https://codepen.io/sauravkr818/pen/vYxWmEo

**Comment by abirana** [comment]
This is not a bug, this is how image appears if you do not set width to the images.

Image doesn't automatically get fitted within a block. If you do not apply any width it will appear in its actual width and height. In your case image width is greater than your parent **col-md-4** width, so it is overflowing.

So usually with Bootstrap you use **img-fluid** class on images or you can use **w-100** class as well.

By the way **img-fluid** applies **max-width: 100%** and **w-100** applies **width: 100%**, which makes sure that your image will not be over 100% width of the parent element.

**Comment by tungphan995** [comment]
segamat

**Comment by ffoodd** [comment]
I confirm everythign works fine , [see a forked CodePen](https://codepen.io/ffoodd/pen/oNZpyeV)—however we'd better add the `img-fluid` class in our doc example I guess.
