### ISSUE TITLE
Tooltip & Pophover: In RTL attachment is getting changed

### ISSUE THREAD

**Issue by ajaypatelaj** [twbs/bootstrap#34148]
Hi there,

This is a tricky one as you won't be able to find the issue in RTL Cheatsheet as RTL CSS solve this issue. But actually, this is the JS issue.

Bug reports must include:
Operating system: MACOS Big Sur11.3.1 (20E241)
Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64)
Codepen: https://codepen.io/ajaypatelaj/pen/qBrPXQL?editors=1111

To explain I have attached the below Images to understand it easily.  

Now in RTL, AttachmentMap is getting updated with  with isRTL condition. 
`const AttachmentMap = {
  AUTO: 'auto',
  TOP: 'top',
  RIGHT: isRTL() ? 'left' : 'right',
  BOTTOM: 'bottom',
  LEFT: isRTL() ? 'right' : 'left'
}`

In Tooltip.js (Maybe the same as in Pophover.js) function `_getAttachment` is getting called twice which works fine with LTR. But, in RTL it is changing the value from right to left and vice-versa. Due to this condition ` RIGHT: isRTL() ? 'left' : 'right',`

For more details check the below image. Ideally, it's getting changed already in show() function and `_handlePopperPlacementChange()` function change it again.

It should not be changed again, else the arrow in RLT will appear in the wrong direction. (NOTE: If you use the RTL style, then the style will make the arrow position correct which may confuse you with the issue.)

<img width="1677" alt="Screenshot 2021-05-31 at 5 37 03 PM" src="https://user-images.githubusercontent.com/749684/120191413-8547d800-c237-11eb-8864-744aff8917ea.png">chi

<img width="1679" alt="Screenshot 2021-05-31 at 5 37 12 PM" src="https://user-images.githubusercontent.com/749684/120191375-7c570680-c237-11eb-8a91-90dae1326058.png">

Hope It can help you to understand. Let me know if you need more details.

Stay Safe~

**Comment by ffoodd** [comment]
Probable related to #34125

**Comment by alpadev** [comment]
The example is using the regular CSS (bootstrap.min.css) file. With the RTL CSS (bootstrap.rtl.min.css) this seems to work fine.

**Comment by ffoodd** [comment]
@ajaypatelaj Can you confirme you're not using RTL CSS file? If so, are we safe to close the issue?

**Comment by ajaypatelaj** [comment]
> The example is using the regular CSS (bootstrap.min.css) file. With the RTL CSS (bootstrap.rtl.min.css) this seems to work fine.

I know that that's the reason I have mentioned this is related to JS. 
Using RTL CSS will fix the issue, but check how AttachmentMap is getting change in RTL in the tooltip.JS 

@ffoodd Yes, Codepen is not using the RTL CSS, AS I mentioned it seem JS issue.

**Comment by ffoodd** [comment]
Well I'm missing the point, why would it be an issue if it works fine with CSS altogether? You're not supposed to use only our JS. 

@twbs/js-review does this issue make any sense for some of you?

**Comment by vrushank** [comment]
Yes, I also do have the same issue. JS behavior is not as expected. It is just working bacause of RTL css. I agree with @ajaypatelaj

**Comment by alpadev** [comment]
@ffoodd I don't get it either. The tooltip uses the class bs-tooltip-start (while positioned on the right hand side) which seems to be the correct class to use in RTL mode. The tip of the arrow is positioned using CSS which properly sets is to be on the left side of the tooltip when used together with the correct CSS file.

Both agreeing that it works with the RTL CSS file, so I don't see the problem here.

**Comment by ajaypatelaj** [comment]
@alpadev If you check for Tooltip on right in RTL, class is bs-tooltip-end, is it correct? In RTL I think it should be bs-tooltip-start.


![Screenshot 2021-06-02 at 11 37 32 AM](https://user-images.githubusercontent.com/749684/120432017-edf99680-c396-11eb-86b2-4d1e0a191078.png)

**Comment by alpadev** [comment]
![dir-reading](https://user-images.githubusercontent.com/2838324/120449399-ae7b7c00-c38f-11eb-8bc3-655df50dfd3b.jpg)
(Source https://ishadeed.com/article/css-logical-properties/)


So assuming the class is based on the side it is located at, it would be `bs-tooltip-end`, no?

**Comment by rohit2sharma95** [comment]
> If you check for Tooltip on right in RTL, class is bs-tooltip-end, is it correct? **In RTL I think it should be bs-tooltip-start.**

That's not correct, tooltip on the right side will always have `bs-tooltip-end` class (in both directions). Understand **right** as **end**, so in both cases, tooltip is on the right (end) side, it should have the `bs-tooltip-end` class.
@ffoodd? 

BTW, if you are not using RLT CSS in the example, why you are using dir="rtl" :slightly_smiling_face:

**Comment by ffoodd** [comment]
`end` means right in LTR but left in RTL. Si `bs-tooltip-end` means right aligned in our default build and left aligned in RTL. 

But I think it's handled from the beginning in our JS by specifying which direction is aliased, isn't it?

**Comment by ajaypatelaj** [comment]
@rohit2sharma95 Thanks for the clarification, I understood that the classes are not going to change in RTL same as utils classes i.e `ml-*`, `pl-*`. I have got confused because it's managed in JS and CSS also. 
And in JS it's like show() function make it `bs-tooltip-right` and `_handlePopperPlacementChange` make it again `bs-tooltip-left ` I guess if we're handling it with CSS do we need RTL condition in JS (tooltip.js)?

@alpadev https://ishadeed.com/article/css-logical-properties/ informative. But in bootstrap do I think class remains the same in RTL i.e `ml-*`, `pe-*` and we're changing their style here to make it RTL. 

@ffoodd I was thinking the same "end means right in LTR but left in RTL."

I think I should also do this with CSS and not concentrate on class :) Apology if I misunderstood and made you guys crazy due to this dilemma.

You can close the issue as the conclusion as per me is that we're changing the style in RTL and not the class. 

Stay Safe~
