### ISSUE TITLE
Docs: Wrong color value is displayed for secondary color in v4

### ISSUE THREAD

**Issue by abirana** [twbs/bootstrap#34146]
This is really a minor issue, since we are already moving with v5 but haven't noticed till today. Similar color mismatch happen to our own templates/implementation as well, so I just wanted to post it.

In the **Theme Color** section, color value of **secondary color** is shown as **#868e96** which is wrong. It should be **#6c757d** according to Bootstrap color values. 

Please check the page here: https://getbootstrap.com/docs/4.6/getting-started/theming/?#theme-colors

<img width="1158" alt="Bootstrap4 wrong value of Secondary color" src="https://user-images.githubusercontent.com/20278933/120106818-4d308e80-c17e-11eb-9dd5-3d5f317e5c28.png">

**Comment by jjoel1630** [comment]
Great, I can fix that very soon!
