### ISSUE TITLE
form-control-color should not use validation icons

### ISSUE THREAD

**Issue by bastinald** [twbs/bootstrap#34151]
ugly: 

![](https://i.imgur.com/vVmQlEh.png)

**Comment by mdo** [comment]
I agree that's not idea. Wondering if we need to override for a ton of `type` values, or if there's a more selective way to apply your form validation to individual controls?

**Comment by alecpl** [comment]
Maybe color inputs should NOT have `max-width`.

**Comment by bastinald** [comment]
> Maybe color inputs should NOT have `max-width`.

They look better when they are not full width like other inputs.

I think the solution is to simply have a CSS rule just for color inputs which does not use the validation icon.

That would be the easiest and cleanest solution. Thoughts?
