### ISSUE TITLE
dropdown-menu-dark inside a navbar in responsive mode has text invisible

### ISSUE THREAD

**Issue by caub** [twbs/bootstrap#34150]
https://jsfiddle.net/caub/qd0ent1z/

- bootstrap version: 5.0.1
- browser: chrome

![2021-05-31-213904_1461x969_scrot](https://user-images.githubusercontent.com/3134574/120234600-a53bc380-c258-11eb-862b-c3b53444d743.png)

**Comment by annsudhart** [comment]
Does it show up when you remove `translate-middle-x` and you should see it? Fixes it for me

**Comment by caub** [comment]
Right thanks, I'll try to apply this translate effect only on large screens

Thanks!
