### ISSUE TITLE
V5 Uncaught TypeError: Illegal invocation 

### ISSUE THREAD

**Issue by InnovativeStudios** [twbs/bootstrap#34152]
I'm getting an Uncaught TypeError: Illegal invocation when I select my link that's supposed to open a modal with the specified event id from my calendar. I'm using the twig 3.0 template engine, and I built my website from scratch using a PHP MVC approach. Here's my log: 
[localhost-1622521500131.log](https://github.com/twbs/bootstrap/files/6573396/localhost-1622521500131.log)

I'm hosting a Dev Environment of my website here: http://147.219.134.46

**Comment by alpadev** [comment]
The ids don't match. The link references some `#viewEventModal-1` (containing a number) and the modal got an id of `viewEventModal-` (missing the number).
