### ISSUE TITLE
Modal Backdrop Z-Index should be higher than Offcanvas Z-index.

### ISSUE THREAD

**Issue by jeddtobee023** [twbs/bootstrap#34164]
By default,
$zindex-modal-backdrop: 1040;
$zindex-offcanvas: 1050;
$zindex-modal: 1060;

I think it should be like this:
$zindex-offcanvas: 1040;
$zindex-modal-backdrop: 1050;
$zindex-modal: 1060;

So that when a button in offcanvas supposed to open a modal, the offcanvas would not overlap to the modal backdrop.

**Comment by ffoodd** [comment]
I guess we need a separate variable for offcanvas' backdrop then, since offcanvas uses a backdrop too. @GeoSot am I right?

**Comment by GeoSot** [comment]
On a first thought, seems valid, as modal backdrop z-index is less that offcanvas
And if we go with this, we have to take a look on #34149

**Comment by mdo** [comment]
This was done awhile back.

https://github.com/twbs/bootstrap/blob/63f75bccd8d206bb59b0e8421258ce03d298b784/scss/_variables.scss#L1031-L1039
