### ISSUE TITLE
Row div inside Card Body with px-0 places content outside of card frame

### ISSUE THREAD

**Issue by MightyCheeto** [twbs/bootstrap#34162]
<div class="card">
        <div class="card-body px-0">
            <div class="row">
                <div class="col bg-dark text-white">
                    <span>XXX</span>
                </div>
            </div>
        </div>
    </div>
![image](https://user-images.githubusercontent.com/85179976/120347132-a1905700-c2c1-11eb-833e-7489ad40553d.png)

I did find however that if you put g-0 in the row div class it moves the content back into the card frame, is this expected?
`<div` class="row g-0">
![image](https://user-images.githubusercontent.com/85179976/120347385-d7354000-c2c1-11eb-8f86-8c43cd0c29f3.png)

Windows 10
Microsoft Edge

**Comment by mdo** [comment]
Yes, this is expected. Rows use negative margins to outdent and align the content, so they expect a parent container with some padding.
