### ISSUE TITLE
Animated stripes

### ISSUE THREAD

**Issue by Milej** [twbs/bootstrap#34165]
Progress bar animation doesn't work for me. Is a bug? Maybe I am implementing wrong. Sorry for my bad english. Best regards

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by mdo** [comment]
Just tried it out, works for me.
