### ISSUE TITLE
Docs: Wrong customize sass setting info in v5

### ISSUE THREAD

**Issue by Kevin660** [twbs/bootstrap#34176]
There is a sentence said "**Variable overrides must come after our functions, variables, and mixins are imported, but before the rest of the imports**" in [customize/sass#variable-defaults](https://getbootstrap.com/docs/5.0/customize/sass/#variable-defaults).

But in the Example below I copied from the same page.
```
// Required
@import "../node_modules/bootstrap/scss/functions";

// Default variable overrides
$body-bg: #000;
$body-color: #111;

// Required
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";

// Bootstrap and its default variables

// Optional Bootstrap components here
@import "../node_modules/bootstrap/scss/root";
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
// etc
```

It seem just not like way the page said "**Variable overrides must come after our functions, variables, and mixins are imported,**"

**Comment by ffoodd** [comment]
Indeed this sentence has been missed when we last updated the examples. Thanks for reporting it!
