### ISSUE TITLE
How to override (green) color using scss

### ISSUE THREAD

**Issue by Dacesilian** [twbs/bootstrap#34171]
Can someone please tell me, how can I override color? I've used code from here (https://getbootstrap.com/docs/5.0/customize/sass/):

custom.scss:
```
$green: #28a745;
@import "bootstrap";
```

File is placed in scss folder and then `npm run dist`. But color is not changed in result.
Thanks.

_Originally posted by @Dacesilian in https://github.com/twbs/bootstrap/discussions/32651#discussioncomment-816007_

**Comment by mdo** [comment]
Yes, that's how you override the variable defaults. https://github.com/twbs/bootstrap-npm-starter/blob/main/scss/starter.scss has a good example showing how this works (this shows for v4, but v5 works the same).

**Comment by Dacesilian** [comment]
1. I git clone repository
2. Place custom.scss to /scss subfolder
![image](https://user-images.githubusercontent.com/823994/120532951-849e7580-c3e0-11eb-9279-f9f360383d68.png)
![image](https://user-images.githubusercontent.com/823994/120533129-b44d7d80-c3e0-11eb-83d5-59a8e705feb1.png)

3. npm install, npm run dist
4. dist/css/bootstrap.css is generated, but $green is #198754 and not my #28a745.

**Comment by mdo** [comment]
Did you tell the npm scripts to compile the new Sass file? Our build tooling has no concept of new files, it only builds `bootstrap-*.scss` files.

**Comment by Dacesilian** [comment]
Where is this specified, please? I think it's compiling all files from scss folder. Is this in tutorial somewhere, how to do this exactly? Thanks.
