### ISSUE TITLE
Element.setCustomValidity no longer gives element red outline in Firefox 88.0+

### ISSUE THREAD

**Issue by kwerty** [twbs/bootstrap#34197]
Prior to Firefox 88.0, when setting custom validity on a form element (as demonstrated below), bootstrap would give that element a red outline. 

`
document.getElementById('test').setCustomValidity('wtf');
`

Now, there is no outline, and the user is none the wiser to the fact that there is an error.

Firefox 87.0 -
![Firefox 87.0](https://i.imgur.com/TsYn1mz.jpg)

Firefox 88.0 -
![Firefox 88.0](https://i.imgur.com/AJps1uh.jpg)

Reduced test case -
https://jsbin.com/cerarenonu/edit?html,output

I'm running Windows 10, Firefox 88.0

Both versions of Firefox are available for download here (tip: run in Windows Sandbox to avoid mucking up your Firefox profile)

https://ftp.mozilla.org/pub/firefox/releases/87.0/win64/en-US/
https://ftp.mozilla.org/pub/firefox/releases/88.0/win64/en-US/

**Comment by mdo** [comment]
Our `:valid` and `:invalid` styles are scoped to the `.was-validated` styles. Not sure what's going on with differences between versions of Firefox, but all the other browsers do what v88 does here until that class is added.
