### ISSUE TITLE
How to initialize the tooltip component.

### ISSUE THREAD

**Issue by lopey66** [twbs/bootstrap#34190]
trying to get the tooltip to work
```html
    </style>
	<script>
		var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]')); //tooltips bootstrap 5.0
		var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {return new bootstrap.Tooltip(tooltipTriggerEl);}); //tooltips bootstrap 5.0
	</script>
  </head>

<button class="btn btn-outline-success"  data-bs-toggle="tooltip" data-bs-placement="bottom" title="Click to Submit the Selections" type="submit">Search</button>
```

**Comment by alpadev** [comment]
Can you please add a full example? That code seems to work.

Be sure to add the initialization after the script block that loads the bootstrap bundle. E.g.

```html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-qWA2B5R/3ElH2sp6UfBayUPu0bn0vW1qqINjOjDA3W0c8Ix0J3gIPg5d2AbpF7zr" crossorigin="anonymous"></script>

<script>
  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]')); //tooltips bootstrap 5.0
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {return new bootstrap.Tooltip(tooltipTriggerEl);}); //tooltips bootstrap 5.0
</script>
```

**Comment by lopey66** [comment]
Resolved

the javascript has to be placed on the end before the closing </body>



<!DOCTYPE html>
<html>
<head>
<link href="
***@***.***/dist/css/bootstrap.min.css"
rel="stylesheet"
integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
crossorigin="anonymous">
</head>
<body>
<main>
<div>
<h1> Test </h1>
<button type="button" id="mybutton" class="btn btn-primary btn-block"
 data-bs-toggle="tooltip" data-bs-placement="bottom" title="test
tooltip">Test</button>
</div>
</main>
<script src="
***@***.***/dist/js/bootstrap.bundle.min.js"
integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
crossorigin="anonymous"></script>
<script>
//__________________________________________________________________________
var tooltipTriggerList =
[].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
//tooltips bootstrap 5.0
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl)
{return new bootstrap.Tooltip(tooltipTriggerEl);}); //tooltips bootstrap 5.0
</script>
</body>

</html>





kind regards,

*Luis Lopez*

[image: Picture]*[image: 🏊][image: 🚴][image: 🏃]*

*M |*+61 *0422 089 813*

*Msg | *https://www.facebook.com/messages/t/lopey66

*Strava |*
*https://www.strava.com/athletes/412790
<https://www.strava.com/athletes/412790>*

**Comment by lopey66** [comment]
Resolved by placing the bootstrap.bundle.min.js  and script at the end of the body


<!DOCTYPE html>
<html>
	<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
	</head>
	<body>
	<main>
		<div>
		<h1> Test </h1>
		<button type="button" id="mybutton" class="btn btn-primary btn-block"  data-bs-toggle="tooltip" data-bs-placement="bottom" title="test tooltip">Test</button>
		</div>
	</main>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
	<script>
		var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]')); //tooltips bootstrap 5.0
		var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {return new bootstrap.Tooltip(tooltipTriggerEl);}); //tooltips bootstrap 5.0
	</script>
	</body>
</html>
