### ISSUE TITLE
Syntax error in bootstrap.js

### ISSUE THREAD

**Issue by MBurtsev** [twbs/bootstrap#34191]
Hi,
I always see this error then I start my project in debugger.

![image](https://user-images.githubusercontent.com/41398/120931317-b3c32880-c6f9-11eb-8b5c-ef7a8dd58486.png)

**Comment by alecpl** [comment]
This is  ECMAScript 2015 methods short syntax. What version of Visual Studio are you using?

**Comment by XhmikosR** [comment]
Closing as per the above comment.
