### ISSUE TITLE
Floating labels aren't very customizable

### ISSUE THREAD

**Issue by Bojmaliev** [twbs/bootstrap#34198]
I really love floating labels but: 

- I can't append or prepend things like normal Input groups.
- Use different label and placeholder.

**Comment by alecpl** [comment]
This probably should be two tickets. Could you elaborate on the first issue?

**Comment by Bojmaliev** [comment]
When using normal input-groups you can use `input-group-prepend` and `input-group-append` classes to easily append and prepend other inputs to your input. 
For floating labels according to documentation you should use standard bootstrap row and col classes to have more inputs in one row, but the effect isn't the same.

**Comment by 719media** [comment]
I don't understand. What are you doing different than this

https://jsfiddle.net/mvp3yL0r/
