### ISSUE TITLE
Apply .text-white for .card and .card-header with some .bg-* classes

### ISSUE THREAD

**Issue by theonlypwner** [twbs/bootstrap#34200]
In Bootstrap 3, `class="panel panel-primary"` was enough, but in Bootstrap 4 and 5, it's `class="card-header bg-primary text-white"`.

The styles for `text-white` should be applied automatically, since the card text would be hard to read without it.

This is similar to #34016, where Bootstrap 5 started to require `text-dark` with certain `badge` colors.

**Comment by mdo** [comment]
Going to punt on this one for now. Maybe we revisit the variants in v6.
