### ISSUE TITLE
table-responsive is not working v5.0.1

### ISSUE THREAD

**Issue by heathism** [twbs/bootstrap#34216]
I write example ref from v5.0.1 document.
```
<div class="table-responsive">
  <table class="table">
...
  </table>
</div>
```
but the table is still resized when I change the width of chrome, opera...etc.
No x scroll bar appears.

**Comment by tungphan995** [comment]
elias

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
