### ISSUE TITLE
Floating label in border

### ISSUE THREAD

**Issue by TanvirArjel** [twbs/bootstrap#34218]
One of the cool features of **bootstrap 5.0** is **floating labels.** The current implementation floats the label inside the input border. But it would be greater if there is another option for floating labels in border:

Existing version: (with class: `form-floating`)

![Capture](https://user-images.githubusercontent.com/14342773/121358818-b5d4f380-c954-11eb-9887-fdb914ec0aa2.PNG)

Another expecting version( with class: `form-floating-border` ):

![Capturhhhhe](https://user-images.githubusercontent.com/14342773/121359459-51666400-c955-11eb-875b-8ffddb265ebc.PNG)

![Capture111](https://user-images.githubusercontent.com/14342773/121358877-c38a7900-c954-11eb-8ace-eb48e5770a34.PNG)

Thank you.

**Comment by mdo** [comment]
This has been requested before and we've kindly declined—one floating label form design is enough for us :).
