### ISSUE TITLE
Bootstrap v5: Migration docs - breaking change related to media-breakpoint-down() is not included

### ISSUE THREAD

**Issue by petia182** [twbs/bootstrap#34219]
- Operating system and version (Windows, macOS, Android, iOS) - **N/A**
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser) - **N/A**

I noticed there is a breaking change, related to the `media-breakpoint-down()` mixin, which is not included in the [Migration Documentation](https://getbootstrap.com/docs/5.0/migration/#grid-updates)

In Bootstrap v4 the `media-breakpoint-down()` was triggered at the _next_ larger breakpoint, but in Bootstrap v5 this is changed.
 
**Example:** 
Bootstrap v4 - when using `media-breakpoint-down(md)` - the breakpoint is equal to `@media (max-width: 991.98px)` Bootstrap v5 - when using `media-breakpoint-down(md)` - the breakpoint is equal to `@media (max-width: 767.98px)`

 **Codepen Example:**
 Bootstrap v4 - https://codepen.io/petia182/pen/qBrMBKo
 Bootstrap v5 - https://codepen.io/petia182/pen/wvJEvLa

**Comment by alpadev** [comment]
The information used to be there 🙁 Looks like they got lost in the nether.

> - The `media-breakpoint-down()` uses the breakpoint itself instead of the next breakpoint. Use `media-breakpoint-down(lg)` instead of `media-breakpoint-down(md)` to target viewports smaller than the `lg` breakpoint.
> - The `media-breakpoint-between()` mixin's second parameter also uses the breakpoint itself instead of the next breakpoint. Use `media-between(sm, lg)` instead of `media-breakpoint-between(sm, md)` to target viewports between the `sm` and `lg` breakpoints.

PR that changed the behaviour: https://github.com/twbs/bootstrap/pull/29148
PR that removed the migration notes: https://github.com/twbs/bootstrap/pull/33834

**Comment by petia182** [comment]
Thank you!
