### ISSUE TITLE
Carousel controls broken in `main`

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#34226]
currently the carousel **prev and next buttons not working**, the indicators are working.

can anyone confirm this problem?

https://jsfiddle.net/jonnysp/dfz3x7at/

**Comment by mdo** [comment]
I cannot open your JS Fiddle for some reason, but everything seems to work fine here: https://getbootstrap.com/docs/5.0/components/carousel/.

**Comment by jonnysp** [comment]
@mdo 
not the actual release. checkout the latest main branch, compile and try.

**Comment by tungphan995** [comment]
acmebar

**Comment by alpadev** [comment]
The issue is actually valid 😥
Looks like https://github.com/twbs/bootstrap/pull/33276 broke it. See https://deploy-preview-33276--twbs-bootstrap.netlify.app/docs/5.0/components/carousel/#with-captions

**Comment by mdo** [comment]
Ah yes, I see it now. /cc @GeoSot as the PR author

I think we either patch that PR or revert it so we can ship v5.0.2 later this week. Up to you, @alpadev @GeoSot et al.
