### ISSUE TITLE
Fullscreen classses for offcanvas

### ISSUE THREAD

**Issue by SafaAlfulaij** [twbs/bootstrap#34236]
Add similar modal classes for fullscreen on different breakpoints to offcanvase for better viewport support (fullscreen on mobile).
Related: #28683

**Comment by GeoSot** [comment]
Hey @SafaAlfulaij 
Have you try width helpers (for side/vertical offcanvas) or height helpers for horizontal?

**Comment by SafaAlfulaij** [comment]
It's possible yes, but then I have to use 4 classes, two for width responsiveness, and two for border responsiveness...
I'm also thinking along with this #34247 to have modal and offcanvas similar (or exact) in functionality, since an offcanvas is actually a modal placed at the edge.

**Comment by mdo** [comment]
Going to close as a won't add/fix. Customizing the width of the overlay feels like it's helpful enough here and provides more flexibility than predefined options.
