### ISSUE TITLE
Width with breakpoints (w-lg-50 w-md-75 w-100)

### ISSUE THREAD

**Issue by ikender** [twbs/bootstrap#34230]
There are times where on a desktop an element would look best at 50% width, while on tablet or laptop it might need a little more of the available space (say, 75% width) and on a mobile device you don't want to restrict it, so keep it at 100%

so I was hoping to have breakpoints for the width classes

w-25, w-sm-25, w-md-25, w-lg-25, w-xl-25
w-50, w-sm-50, w-md-50, w-lg-50, w-xl-50
w-75, w-sm-75, w-md-75, w-lg-75, w-xl-75
w-100, w-sm-100, w-md-100, w-lg-100, w-xl-100

very helpful if there is a small bit of content for an element, and you want it to span a couple of lines, but as the screen gets smaller the element will naturally create those breaks so the class is no longer needed

**Comment by Luke-zhang-04** [comment]
See https://github.com/twbs/bootstrap/pull/31323, unless they've changed their mind. Also, it's not hard to implement yourself, just add a property to the utilities.

**Comment by mdo** [comment]
Yup, the grid classes get you this for free in v5 without the need for extra utilities.

**Comment by lonix1** [comment]
Do you mean the `col-x` in freeform mode (not inside a container->row).

So `col-6` is like `w-50`, and `col-4` is like `w-25`, etc.?

**Comment by narenkram** [comment]
I definitely need this.

**Comment by rackycz** [comment]
Can someone show how to do it in Bootstrap 5? This is tricky for us, non-designers. "w-md-50" is perfectly understandable, but Bootstrap 5 does not support this as stated above.

**Comment by petschki** [comment]
@rackycz what about this:

```html
<div class="col-12 col-md-6 col-lg-3">
    <input class="form-control" value="12" name="username" type="text" >
</div>
```
