### ISSUE TITLE
Permission to use Bootstrap logo on baseball caps

### ISSUE THREAD

**Issue by andrewrobles** [twbs/bootstrap#34246]
To Whom It May Concern,

I'm starting a clothing brand that designs baseball caps for programmers.

Is it possible to obtain permission to sell baseball caps with the Bootstrap logo (see attached image)?

If so, what is the process of obtaining such permission?

Best regards,

Andrew Robles

<img width="484" alt="bootstrap-hat" src="https://user-images.githubusercontent.com/70864612/121832416-d7005180-cc7e-11eb-9a86-8bfd9e886ffd.png">

**Comment by mdo** [comment]
Sorry, but no, please do not sell merchandise with our logo on it :).
