### ISSUE TITLE
Allow static backdrop in offcanvas

### ISSUE THREAD

**Issue by SafaAlfulaij** [twbs/bootstrap#34247]
Offcanvas components should also be able to prevent the user from closing them by having a static backdrop.
This will make modal and offcanvas share more code and similar functionality.

**Comment by sajagjain** [comment]
Is there any update on this?

**Comment by sajagjain** [comment]
- [ ] Add Static Backdrop support for offcanvas

**Comment by clandher** [comment]
Should inherit the same behavior as a modal.

**Comment by charlesfries** [comment]
Bump

**Comment by TheAustinG** [comment]
Bump. This would be really nice to have. I don't want my users to be able to dismiss the offcanvas by clicking outside of it.

**Comment by SafaAlfulaij** [comment]
Are you aware all that "bumping" will only notify the users here and not get the issue up the list?
If someone have the time, open a PR.

**Comment by TheAustinG** [comment]
@SafaAlfulaij Yes, I am well aware. It was more of a "virtual" bump. The more activity this issue gets the more eyes that will be on it in the future.

**Comment by chefarbeiter** [comment]
I need this feature too, so I implemented it and created a PR.

But for a quick fix you can also implement the behavior with a workaround / hack:
```js
let offcanvasDOM = document.getElementById("offcanvasExample")
let offcanvas = new bootstrap.Offcanvas(offcanvasDOM)
let isAllowedToHide = true

offcanvasDOM.addEventListener("shown.bs.offcanvas", event => {
  // Reset
  isAllowedToHide = false

  // Add click handler to dismiss buttons for allowing the exit and repeat the hide action
  offcanvasDOM.querySelectorAll("[data-bs-dismiss=offcanvas]").forEach(button =>
    button.addEventListener("click", event => {
      isAllowedToHide = true
      offcanvas.hide()
    }))

  // If you want to allow ESC exit add this handler for allowing the exit and repeat the hide action
  offcanvasDOM.addEventListener("keydown", event => {
    if (event.key === "Escape") {
      isAllowedToHide = true
      offcanvas.hide()
    }
  })

  // If you have a save button allow the exit and call hide after saving
  offcanvasDOM.querySelector("#saveButton").addEventListener("click", event => {
    // Save logic...

    // Allow to hide the offcanvas and hide
    isAllowedToHide = true
    offcanvas.hide()
  })
})

// Checks if hide is allowed and prevents the event if not
offcanvasDOM.addEventListener("hide.bs.offcanvas", event => {
  if (!isAllowedToHide) {
    event.preventDefault()
  }
})
```
[Live-Version](https://jsfiddle.net/ektf0awq/)

A minor drawback of this hack is that the hide handler for intentional calls (Dismiss buttons or ESC key) is called twice: once by the normal bootstrap code - here the hide is prevented - and then by our special handler after we allow the hide. So if you have further logic in hiding the element, you need to use the hidden event for that. This will only be called when the offcanvas is actually hidden.

**Comment by markocrni** [comment]
For workaround:
```
el.addEventListener('shown.bs.offcanvas', function(){
bsOffcanvas._backdrop._config.clickCallback = function(){};
});

```
