### ISSUE TITLE
V5 Modal flickering when within .list-group-item

### ISSUE THREAD

**Issue by mathiasrabe** [twbs/bootstrap#34241]
Hi everybody,

the following was testet with the current Crome and Safari on Mac OS 11.4.

If I use a modal inside .list-group-item the screen is flickering. Here is an example: https://codepen.io/Matrab/pen/XWMyXxZ

I don't know if this equals  https://github.com/twbs/bootstrap/issues/25206

**Comment by ycoder-23** [comment]
Hey @mathiasrabe ,include the below line to fix that flickering
.list-group-item, .list-group-item:hover{ z-index: auto; }

**Comment by mathiasrabe** [comment]
This worked, thanks!

**Comment by traveller255** [comment]
Sorry if I chose the wrong topic, I have the same problem but with the card group (bootstrap 5.3.2) .
The problem occurred after I modified the loading of cdn scripts with another script.
