### ISSUE TITLE
B5 - modal not open on $('#myModal').show();

### ISSUE THREAD

**Issue by DigitalAndSEO** [twbs/bootstrap#34267]
I have been able to verify that, if there is no other problem, by calling the function `$ ('# myModal').show();` it does not show the modal, and one of the things that happens is that it does not add the class "show" so it stays in opacity 0.

I could not check if something similar happens in "hide".

Thanks.

**Comment by GeoSot** [comment]
Hew @DigitalAndSEO  let's try something. 

Try:
```js

var x= new bootstrap.Modal('#myModal')
x.show()

```

**Comment by DigitalAndSEO** [comment]
it worked perfect.
But, in Bootstrap 5, from now on, must manners be declared first and then do a `show ()` or is it a bug that needs to be fixed so that it only places the class "show"? (since the rest of the functionality works perfect).

**Comment by GeoSot** [comment]
Pretty sure that this work too

```js
var x= new bootstrap.Modal('#staticBackdropLive2').show()
'''

**Comment by alecpl** [comment]
Was `$('#myModal').show()` ever supported? As far as I know official way to open a modal was `$('#myModal').modal('show')`. Since Bootstrap v5 is not using jQuery you have to use `.show()` method of the `Modal` object. But I'm not an expert.

**Comment by GeoSot** [comment]
>  As far as I know official way to open a modal was $('#myModal').modal('show')

You are right on this

> Bootstrap v5 is not using jQuery you have to use .show() method of the Modal object. 

not using jQuery (by default), but can yet used like you proposed too 😉 



In general, the Bootstrap components can be used with the following ways

```js

// native call
arg = 'any-selector | HTMLElement object | jQuery object'
new bootstrap.Modal(arg).method()

// After 5.0.2 will be possible to use it via the static accessor too
arg = HTMLElement object
Modal.getOrCreateInstance(arg).method()

// JQuery call
arg = configuration object | method name
$('selector').modal(arg).
```
