### ISSUE TITLE
Floating Labels issue, and how to fix it (BS 5.0.1)

### ISSUE THREAD

**Issue by guzats** [twbs/bootstrap#34275]
When we use a "floating label" with one of the bootstrap colors, it disappears whan the textbox is active. : 

*LIVE DEMO* : https://codepen.io/guzats/pen/wvJOaow
*Operating System:* Windows 10
*Browsers:* Chrome 91 and Mozilla Firefox 89

`<input type="text" name="s" class="form-control form-control-lg  bg-light" id="buscar_no_site14" placeholder="">`

This problem can be fixed just by adding a z-index parameter in CSS:

```
.form-floating>label {
        **z-index:10;** 
	position: absolute;
	top: 0;
	left: 0;
	height: 100%;
	padding: 1rem .75rem;
	pointer-events: none;
	border: 1px solid transparent;
	transform-origin: 0 0;
	transition: opacity .1s ease-in-out, transform .1s ease-in-out
}
```

Sometimes the problem persists when the Label is activated, so, to solve the problem, just change the label's color .

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by guzats** [comment]
Edited, now with a live demo on codepen.

**Comment by mdo** [comment]
You cannot mix the floating forms classes with the input group classes. Drop those and there's no issue. If you need an input group version, you can create that with some rounded corner utilities.
