### ISSUE TITLE
Cloud type list. with support of Tabs, badge, Icon, icon to remove, checkbox.

### ISSUE THREAD

**Issue by Anoopkumarseth** [twbs/bootstrap#34284]
![image](https://user-images.githubusercontent.com/30388576/122509221-09180780-d021-11eb-8ad9-91aad6786384.png)

I'm finding this kind of list in bootstrap. How I can do this. 
It might be good if it supports Tabs, badge, Icon, an icon to remove, checkbox etc.

**Comment by mdo** [comment]
Looks like badges. If you're talking about chips, we have an issue for that #31033.
