### ISSUE TITLE
Text inputs inside collapse - if input is in focus and collapse button is clicked, animation breaks

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#34293]
- Operating system and version
macOS Big Sur 11.0.1

- Browser and version
Latest Chrome, FF and Safari

- Steps to reproduce
1. Go here - https://jsfiddle.net/s0h167nb/
2. Click on Search icon
3. Type something in text field
4. Move cursor to search icon and click again keeping input in focus
5. Animation is triggered, but it collapses way too fast and is partially broken at the end

**Comment by GeoSot** [comment]
Hey @Kopyov 

Please make one more try:

use the following script instead of 5.0.1

ttps://deploy-preview-33845--twbs-bootstrap.netlify.app/docs/5.0/dist/js/bootstrap.bundle.min.js

I think you will find this problem solved by #33845

**Comment by Kopyov** [comment]
hey @GeoSot 

Yes that works, thanks. I hope the fix will be included in 5.0.2
