### ISSUE TITLE
ltr to rtl convert  ms-auto problem.

### ISSUE THREAD

**Issue by cihaniko** [twbs/bootstrap#34295]
**Hi there,**

I have a little problem.
I may be wrong or incomplete. I am using the Bootstrap rtl library. I refresh my page as rtl or ltr according to the user's choice. For ltr when I use flex structure, 2 left 1 right div. For rtl; I need to create 1 left 2 right divs. You can check the jsbin example below for this case.
My question is, bootstap generally manages to pass almost everything from left to right for me, but when I do ltr from rtl while in flex structure, all 3 divs are merged. 1 left 2 right does not exist. For this reason, where I use this situation manually, I need to delete the css with the help of jquery and add a new one. Is there an easier way to do this? Is this a bug or does it really have to be like this?
Doesn't Bootstrap make ms-auto me-auto after rtl conversion for me? Or is there a particular reason why it doesn't?

[jsbin example](https://jsbin.com/yuwotoqosi/1/edit?html,output)

Thank you for your help.

Note: you have to change the dir attribute in the jsbin file to rtl to ltr to be able to test it.

**Comment by mdo** [comment]
> For this reason, where I use this situation manually, I need to delete the css with the help of jquery and add a new one

I'm assuming you mean flipping between the stylesheets? In which case, yes, you need to change from the default LTR stylesheet to RTL.
