### ISSUE TITLE
Getting Error Unexpected character '@' while importing bootstrap css in React SSR

### ISSUE THREAD

**Issue by shivam201312** [twbs/bootstrap#34306]
Hi, i have react app which is currently client side rendering . i have to convert client side rendering to server side rendering .After converting application to SSR. When i am compiling code i am getting following error due to bootstrap.css file.
**Error message**
```
ERROR in ./node_modules/bootstrap/dist/css/bootstrap.min.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @charset "UTF-8";/*!
|  * Bootstrap v5.0.1 (https://getbootstrap.com/)
|  * Copyright 2011-2021 The Bootstrap Authors
 @ ./src/client.js 5:0-46
```
**Webpack configuration**
```
const path = require('path');

module.exports = {
    mode: 'development',
    target: 'node',
    entry: './src/client.js',
    output:{
        filename: 'client_bundle.js',
        path: path.resolve(__dirname, 'build/public'),
        publicPath:'/build/public'
    },
    module:{
        rules:[
            {
                test: /\.svg$/,
                use: 'file-loader'
            },
            {
                test:/\.js$/,
                loader:'babel-loader',
                exclude:'/node_modules/',
                options:{
                    presets:[
                        '@babel/react',
                        ['@babel/env',{
                            targets:{browsers:['last 2 version']}
                        }]
                    ]
                }
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                use: [ 'style-loader', 'css-loader' ]
            },
            {
                test: /\.(gif|svg|jpg|png)$/,
                loader: "file-loader"
            },
            {
              test: /\.ico(\?v=\d+\.\d+\.\d+)?$/,
              loader: 'url-loader'
            }
        ]
    }
}
```
Client.js
```
import React from "react";
import ReactDOM from "react-dom";
import {BrowserRouter} from 'react-router-dom';
import App from "./App";
import 'bootstrap/dist/css/bootstrap.min.css';
ReactDOM.hydrate(
    <BrowserRouter>
        <App/>
    </BrowserRouter>,document.querySelector("#root"));
```
Command that i have used for building package : 
```
webpack --mode=development --config webpack.client.js --env development --watch
```
Environment details : 
```
NodeJS version : v14.16.1
react : 17.0.2
webpack : 5.37.1
bootstrap : 5.0.1
OS : Windows
```
If i manually remove @charset "UTF-8" from the bootstrap.min.css then other error pops up so what would be the best way to import bootstrap.css file ?
**Note** : Code is compiling if i am removing import statement of bootstrap.min.css file. Custom CSS which i have created is working fine

**Comment by alpadev** [comment]
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

The error message clearly says what isn't working. If you exclude the CSS processing for the node_modules folder it's not going to process 3rd party CSS you're importing thus throwing a parsing error.

**Comment by shivam201312** [comment]
Thank you @alpadev  for replying. After removing following line : 
```
exclude: /node_modules/,
```
Now application is building but there is also server.js file .Which is building without issues . In serverwebpack i have used ignore-loader for ignoring .css, .ttf, . eot file
but when i am running following command : 
```
node build/bundle.js
```
i am getting same error. bundle.js file is output of server webpack
