### ISSUE TITLE
Navbar dropdown has blue border when clicked in Safari

### ISSUE THREAD

**Issue by mapattacker** [twbs/bootstrap#34300]
This was not apparent in Bootstrap v3 which I am using. 
But exists in Bootstrap 4 & 5.

<img width="494" alt="Screenshot 2021-06-19 at 8 40 03 PM" src="https://user-images.githubusercontent.com/13524596/122642881-38249b00-d13f-11eb-89fa-331a7ab99906.png">

Operating System: macOS Big Sur 
Browser: Safari 14.0.3

**Comment by alpadev** [comment]
I guess that's expected because it highlights the focused element. This is for better a11y AFAIK.

**Comment by mdo** [comment]
Yup, this isn't a bug, focus states have to be indicated.
