### ISSUE TITLE
Issue with responsive tables

### ISSUE THREAD

**Issue by anubedam** [twbs/bootstrap#34315]
When you wrap a table with Table-Responsive, the Scroll appears correctly, but the space of the columns do not conform to its content, but shrink and the content is not seen. 

Operating system: Windows-10; browser mozilla firefox.

Thank you.

**Comment by mdo** [comment]
Without a live demo, I can only guess as to what you're seeing, but it sounds about right. Responsive columns aren't bulletproof and may require more code to fine-tune to your exact purposes.
