### ISSUE TITLE
Add feature support: row-gap and column-gap

### ISSUE THREAD

**Issue by ishnechmad** [twbs/bootstrap#34314]
Feature requests must include:

The [current version of Bootstrap (5.0.1)](https://getbootstrap.com/docs/5.0/) supports the CSS [gap](https://getbootstrap.com/docs/5.0/utilities/spacing/#gap) feature, But does not support a separate 'gap' for [rows ](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap)and [columns](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap).

Can you add it?
Are you planning to add this?

**Comment by Rajatb04** [comment]
yes

**Comment by mdo** [comment]
I think for the time being, starting with our next release (v5.1.0), we'll punt on these as the experimental opt-in CSS grid support lands. `gap` accepts a shorthand for two values as it is already, and our CSS grid implementation recommends inline styles and variable overrides over additional utilities.

**Comment by ishnechmad** [comment]
> I think for the time being, starting with our next release (v5.1.0), we'll punt on these as the experimental opt-in CSS grid support lands. `gap` accepts a shorthand for two values as it is already, and our CSS grid implementation recommends inline styles and variable overrides over additional utilities.

Why is it different from padding and margin that allows for **py** and **px**, **my** and **mx**?

**Comment by newclaus** [comment]
What about supporting css row-gap and column-gap? Will this be implemented?

**Comment by kimdv** [comment]
If you want row and column gap with bootstrap spacings, it can be added in SCSS

```scss
@each $key, $value in $spacers {
    .row-gap-#{$key} {
        row-gap: #{$value};
    }

    .column-gap-#{$key} {
        row-gap: #{$value};
    }
}
```

**Comment by ffoodd** [comment]
If you're doing your custom Sass build, I'd recommend you use [the utilities API to add New utilities](https://getbootstrap.com/docs/5.1/utilities/api/#add-utilities) instead of such loop.

**Comment by mdo** [comment]
Closing as a won't fix until v6 when we do more with our opt-in CSS Grid.
