### ISSUE TITLE
[Bootstrap 5] Progress-bar interior no longer respects container width

### ISSUE THREAD

**Issue by mayhew3** [twbs/bootstrap#34323]
OS: Win10 64-bit
Browsers tested: Firefox 89.0.1, Chrome 91.0.4472.114

I am upgrading my app from Bootstrap 4 to Bootstrap 5. I used code inside a progress-bar component to display the percentage centered on the entire progress bar, not just the completed section. In Bootstrap 5, this broke because when calculating width 100% it stopped using the width of the progress bar's container, and started using what I can only guess is the top-level container for the page?

I put together a simple StackBlitz to demonstrate:
[Bootstrap 4](https://stackblitz.com/edit/progress-bar-4)
[Bootstrap 5](https://stackblitz.com/edit/progress-bar-5)

In Bootstrap 4, the text is centered within the progress bar element, but in Bootstrap 5, it is centered in the page instead.

**Comment by GeoSot** [comment]
Hey @mayhew3  Thanks for putting live examples of your problem.  It helped a lot

Unfortunately it is not the progress bar, that causes you troubles. 
In both markups you have used absolute position (see attached image)

On **BSv4** every `col-*` had `position: relative` but doesn't continued on **BSv5**. 
So you may solve you problem by using a relative wrapper or a relative class on any parent of your absolute element

![image](https://user-images.githubusercontent.com/22406063/122924620-a56a4300-d36e-11eb-8fae-f3832da8b396.png)

**Comment by mayhew3** [comment]
Thanks, that worked!
