### ISSUE TITLE
The negative margin doesn't work

### ISSUE THREAD

**Issue by davidtovt** [twbs/bootstrap#34329]
The negative margin doesn't work in Bootstrap 5. There is in the documentation: https://getbootstrap.com/docs/5.0/utilities/spacing/#negative-margin
but missing from the CSS.

**Comment by ffoodd** [comment]
As written in the docs you linked, negative margins are disabled in our default build. You need to run your own build and set `$enable-negative-margin` to `true`>

**Comment by davidtovt** [comment]
It would be good to have it enabled in the CSS version. I often use that.

**Comment by carc1n0gen** [comment]
I stumbled across this issue after having no luck with the negative margin utility classes. The docs do **_not_** mention having to enable `$enable-negative-margin` in our own build. They just say that negative margins were added in 4.2
