### ISSUE TITLE
v5.0.2 regression: grid col-N now overrides col-breakpoint

### ISSUE THREAD

**Issue by danielkauffman** [twbs/bootstrap#34335]
Between v5.0.1 and v5.0.2, the col-breakpoint declarations were moved above the col-N declarations. This breaks automatic column sizing. For example, a class declaration of "col-6 col-md" now creates a column that is always six columns wide and the column width does not become automatic at the breakpoint. Previously, the column width was six columns at the small sizes, and became automatic at the breakpoint.

Here is the diff showing the change in the compiled CSS: https://github.com/twbs/bootstrap/commit/688bce4fa695cc360a0d084e34f029b0c192b223#diff-1e4f2454c1c043f0cf31f56b51ec891c6bc0ff1c88985b82c7f89c0d8f78c4ba

This **might** be a result of this commit, although my guess is based mainly on the title of the commit, which describes changing the declaration order for cols: https://github.com/twbs/bootstrap/commit/f2b47e1c8a263f4406255991af9fd55984c22a0e#diff-41667d8b9901aa9fa52483b538bb9026c287f2c663d2fdc01acffa06888cc087

**Comment by Qonstrukt** [comment]
This breaks quite some of our layouts actually over a minor upgrade, I do hope your reconsider moving this to a hot fix instead of 5.1.0.
