### ISSUE TITLE
Adding a png image with no background[transparent] always shows border and even after overriding it with CSS it shows very faint border

### ISSUE THREAD

**Issue by kingx619** [twbs/bootstrap#34346]
The html along with bootstrap I used is

             <img class="img-fluid my-auto" src="images/telogo.png" alt="mylogo">
         
The output I am getting is

![1](https://user-images.githubusercontent.com/75287291/123252247-b3a09680-d509-11eb-9819-7d1355db3b1e.png)

After overriding bootstrap with internal css the border is still prominent..This image worked fine till bootstrap 5.0 beta 3

     <img class="img-fluid my-auto" src="images/telogo.png" alt="mylogo" style="border : none ;">
Visible border even after border removal

![11](https://user-images.githubusercontent.com/75287291/123252296-c1eeb280-d509-11eb-9d7c-7c0642f93d5d.png)

If however I upload the image with style attribute inside div tag it works fine.. 

    <div class="col-xxl-4 border border-danger" style="background-image: url('images/telogor.png'); background-repeat: no- 
        repeat;height:300px;"></div>

Here is the output

![3](https://user-images.githubusercontent.com/75287291/123252579-12fea680-d50a-11eb-8d07-736134f37bec.PNG)

Seems like a bug to me

**Comment by coliff** [comment]
Bootstrap doesn't add a border to the `img-fluid` class. You should inspect the image in your browser dev tools to see what's happening. It would be either custom CSS or perhaps your image has a slight border.

Here's a codepen with Bootstrap 5.0.2 with a transparent background PNG (no border).
https://codepen.io/coliff/pen/RwpXBoy
