### ISSUE TITLE
V5 Carousel: Typed.js not displayed in other carousel items?

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34355]
I'm using the **Typed.js** plugin for text effect inside bootstrap's latest release carousel items the issue that I get is the typed.js not displayed in other items only in the first item.

**Here is a live example:** 

https://codepen.io/themes4all/pen/KKmPaew

**Note: try to move to next item to see the issue**

**Comment by GeoSot** [comment]
It is not a bootstrap case, however this is your solution

```js

[...document.querySelectorAll('.typed')].forEach(el=>{
      var typed = new Typed(el, {
        strings: ["PHP Developer.", "Laravel Developer.", "Tall Stack Developer."],
        typeSpeed: 60,
        startDelay: 600,
        backSpeed: 20,
        backDelay: 500,
        loop: true,
        showCursor: false,
        cursorChar: "|",
    });
})
```


It is handful to follow the code sometimes :wink: 
With a simple search, you can see the is initialized **only** on the first element 
https://github.com/mattboldt/typed.js/blob/a8c8686576dc52d416d1e734b3b3eeffcc28bd93/src/initializer.js#L15-L20
