### ISSUE TITLE
Bootstrap 5 modal not animating properly?

### ISSUE THREAD

**Issue by Chico3001** [twbs/bootstrap#34354]
I'm upgrading from v4 to v5 and fixing the bs namespace on the modals used on my projects I realized that in [v4](https://getbootstrap.com/docs/4.0/components/modal/#live-demo) the background of the screen slowly darkens and the modal slowly fades in from the top of the screen (which is nice btw)

But in [v5](https://getbootstrap.com/docs/5.0/components/modal/#live-demo) the modal just pops and there is no animation, is this by design or just a bug?

Regards...

**Comment by ThatMother1** [comment]
Well, they didnt design you... so real recognize real

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by jasonkena** [comment]
@Chico3001 try disabling `prefers-reduced-motion` on your browser. Enabling it seems to disable the transitions.
