### ISSUE TITLE
Minify NullReferenceException

### ISSUE THREAD

**Issue by williambuchanan2** [twbs/bootstrap#34368]
Just installed v5.0.2 in Visual Studio. Get a null reference error when the bundles are being rendered. No information on what the error is but can confirm it is in bootstrap.js.

Thanks

**Comment by tanvirehsan** [comment]
I also got the same error in visual studio 2019.

Thanks

**Comment by williambuchanan2** [comment]
It seems to be an error in that file which is preventing the minimising from taking place.

**Comment by mdo** [comment]
Visual Studio, or Visual Studio Code? Any additional details on the error? Is this our source files or compiled files?

**Comment by williambuchanan2** [comment]
Hi mdo

This is Visual Studio 2019 Professional. 

I first installed this version of the package via nuget. As soon as it installed I pressed the Build button and got this error. I then downloaded the source file and copied it into place but got exactly the same error. 

I then installed 'Bundler and minifier' (https://github.com/madskristensen/BundlerMinifier) - same error when this tried to minify the file.

I rolled back to the latest of version 4 and everything was ok. I then upgraded to version 5.0 the error happened again.

Unfortunately there is very little information in the error. It says it is a null reference on line 1 but that doesn't really help.

Let me know if you need more info.

Thanks

**Comment by tanvirehsan** [comment]
Hi @williambuchanan2,
The visual studio error can be resolved by Replacing "ScriptBundle" with "Bundle" in "BundleConfig.cs". 
Let me know if that helped you.
.. Thanks

**Comment by williambuchanan2** [comment]
Thanks Tanvirehsan
That temporary workaround does seem to solve the problem for now, although it does introduce other problems which I will need to work around until a proper solution is found.
Thanks

**Comment by XhmikosR** [comment]
We only use terser. We also tested uglify-js. The issue seems to be unrelated to our code but rather to your tooling.

**Comment by williambuchanan2** [comment]
Whoa.. Really? You are going to blame the tool? One of the most widely used development tools which has ever existed? And not only that tool but but also the other tool I mentioned, which has exactly the same problem with your code? 

Unbelievable, and completely amateur response.

**Comment by XhmikosR** [comment]
The fact that you think a tool is popular doesn't mean anything, sorry. As for the amateur response I'm not going to comment at all.

That's open source for you. We only test what we can test and support only that. We are not going to fix all the tools out there, but you can start by reporting the issue to the appropriate place, them.
