### ISSUE TITLE
Row g-* mess up the view in Firefox but works fine on Chrome and Safari (Android and PC versions bugged)

### ISSUE THREAD

**Issue by eliezra236** [twbs/bootstrap#34362]
Hi,
I am using bootstrap for my website, and there seem to be a problem when trying to load the site on firefox.
Here are pictures:
Chrome (works fine):
https://i.imgur.com/J4sEHTy.png

Firefox (through dev tools):
https://i.imgur.com/ej1zG98.png
https://i.imgur.com/FSjpfld.png

It seems like the it won't take the whole space of the div, and I can't figure out why.

The HTML looks like this:
`<div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-6 g-2 g-sm-3">${view}</div>`

And the view variable looks like that (the card). One after the other 
  ```
<div class="col">
    <div class="card h-100 games-card">
      <img class="card-img-top table-card-image" src="%IMAGE%" loading="lazy" alt="%IMAGE-ALT%">
      <span class="date-badge badge">%DATE%</span>
      <div class="games-card-body card-body">
        <h6 class="card-title"><a href="%LINK%" target="_blank">%NAME%</a></h6>
      </div>
      <div class="games-card-footer card-footer">
        <i class="%PLATFORM-ICON%"></i>
      </div>
    </div>
  </div>
```

If I remove the g-* from the row, it "fixes" it, and stretch the row to fill the entire parent div, but as long as it there it's squshed to the middle.
It happened on both PC and Android version of firefox (look much worse on phone view).

Anything I am missing here or is it a bug on bootstrap/firefox?

Edit:

A link to where this problem is happening:
https://www.gamepasscompare.com/games/XboxGamePass

**Comment by eliezra236** [comment]
I manage to "fix it" in 2 ways:
1. Added a class to the row div, and set it as margin: auto;
2. Removed g-* and added p-* in col div instead.


But I am still not sure what cause it or why it only happened in firefox

**Comment by mdo** [comment]
It looks like, based on your screenshots, that you're using some CSS grid and the content is getting stuck instead of expanding to fill the viewport. Without a _reduced_ test case demonstrating the problem, I can't dig in and help. Closing out for now since you may have resolved it for yourself.

**Comment by eliezra236** [comment]
> It looks like, based on your screenshots, that you're using some CSS grid and the content is getting stuck instead of expanding to fill the viewport. Without a _reduced_ test case demonstrating the problem, I can't dig in and help. Closing out for now since you may have resolved it for yourself.

Hi mdo, 
I did some more research and what brough this problem on firefox is the negative margtin top that was applied to the row element.
Once it was removed the firefox problem was fixed.
