### ISSUE TITLE
V5 Modal: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by onEXHovia** [twbs/bootstrap#34367]
Hello everyone, when migrating to version 5 noticed that if you call modal that does not exist, there will be an animation error. I don't think this is the correct behavior, the call should be ignored as in version 4.

![image](https://user-images.githubusercontent.com/3332033/123625668-6b46e880-d829-11eb-86b2-e2a7e1f7448e.png)

**Comment by GeoSot** [comment]
Please add at least a codepen example and do not forget to include a **modal element** .  

The code you have attached, indicates that there is not any element to initiate

**Comment by onEXHovia** [comment]
> Please add at least a codepen example and do not forget to include a modal element .

The problem is, if there is no modal it does not need to be initialized on click. My use case is that there is no modal on the page, modal is loaded on click via ajax.

**Comment by GeoSot** [comment]
Hm, if you need to do custom things, you may have to remove the the markup from the trigger btn or add it later. 
The code is written supposing there is no js magic there. :confused: 

To be more clear, there is a thought to throw exceptions if user tried to initialize Components on null elements
