### ISSUE TITLE
V5 Navbar & Dropdowns: Dropdowns Directions not working with Navbar Component!!

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34366]
I'm trying to create a multilevel dropdown and that's a cool thing I hope the BS team adds an example about it in the official doc.

I'm using the dropdown directions classes such as `dropend `but it looks like it's not working...

**here is a live example of what I get:**

https://codepen.io/themes4all/pen/MWmWaZa

![Image](https://i.imgur.com/zJLd5Pe.png)

**Comment by GeoSot** [comment]
Closed as duplicated of #27659
