### ISSUE TITLE
Form inline is not inline anymore

### ISSUE THREAD

**Issue by VirginieGarcin** [twbs/bootstrap#34363]
This happens with 5.0.2.

Example from [documentation](https://getbootstrap.com/docs/5.0/forms/layout/#inline-forms): 
![image](https://user-images.githubusercontent.com/27735708/123545624-07111f80-d76a-11eb-83e7-42632c6a64d8.png)

.`row-cols-lg-auto > * { width:auto }` is overridden by `.col-12 { width: 100%; }`

Might be linked to #34335.

**Comment by Seb33300** [comment]
I am encountering similar issue with the following code after upgrading to Bootstrap 5.0.2

``` html
<div class="row g-4">
<div class="col-12 col-lg"></div>
<div class="col-12 col-lg-5 col-xl-4"></div>
</div>
```

`col-12` takes the priority on `col-lg`

**Comment by Ayush2020012016** [comment]
can you tell me how this is problem???
