### ISSUE TITLE
Modal has not fullscreen

### ISSUE THREAD

**Issue by 89823** [twbs/bootstrap#34378]
Yandex.Translate
-----------

I am developing a website and ran into a problem. The .modal-dialog .modal-fullscreen-md-down class is specified. And when the minimum screen size is reached, the modal does not become full-screen. But if you set the .model-full screen-lg-down class, then everything works.
![image](https://user-images.githubusercontent.com/59954819/123826767-bd127000-d908-11eb-8900-0cb4d82ef155.png)

**Comment by Prasanna0908** [comment]
Hey, I am new at Open Source. Can you instruct me on how to reproduce this error? Can I work on this issue?

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
