### ISSUE TITLE
regression in hr rendering since bootstrap 5

### ISSUE THREAD

**Issue by kusma** [twbs/bootstrap#34374]
The rendering of horizontal rulers have completely changed in Bootstrap 5 vs Bootstrap 4, and the change is not documented in the [migration guide](https://getbootstrap.com/docs/5.0/migration/).

In Bootstrap 4:
 - 1 px border top was used
 - The border-color was set to black with 10% opacity

However, in Bootstrap 5:
- 1 px height is used.
- The background color is set to `currentColor` with 25% opacity.

The result is:
- Inconsistent width, even on the same page if display scaling isn't a multiple of 100% (eg 125%, 150%, 250%) on Windows
   - The rulers flickers when resizing the window on Firefox under these conditions
- Darker ruler color, which change depending on current color

Operating system: Windows
Browser: Mozilla Firefox 89.0.1, Microsoft Edge 91.0.864.59, Google Chrome 91.0.4472.77
[test case](https://codepen.io/kusma/pen/MWmWZvj)

**Comment by kusma** [comment]
Here's a screenshot of how this renders for me:

![image](https://user-images.githubusercontent.com/47073/124597604-f8122780-de63-11eb-8f5d-a879c74f18f0.png)

Notice the inconsistent height and the darker color compared to the old rendering.

**Comment by XhmikosR** [comment]
@mdo is this the same as #34292?

**Comment by kusma** [comment]
I don't think it is, no. It's related, but not quite the same. #34292 seems to be about how padding makes the `<hr>` itself wider instead of padding around it, like we used to.
