### ISSUE TITLE
V5 Navbar Component & Dropdowns: data-bs-offset="" not working in navbar component!!

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34375]
live example: https://codepen.io/themes4all/pen/dyWyLzK

Reference: https://getbootstrap.com/docs/5.0/components/dropdowns/#dropdown-options

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.0/components/dropdowns/#menu-alignment

Dropdowns in navbars aren’t positioned with Popper.
