### ISSUE TITLE
Docs: Add a Tools Page

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34390]
I think it will be great if the core team made some special tools with bootstrap the same thing already exists in MDB but I prefer to use bootstrap without material design.

Reference: https://mdbootstrap.com/docs/standard/tools/

**Comment by Chaostheorie** [comment]
@devhoussam do you mean a page with general bootstrap related tools, similar to an awesome list, or do you want a page with tools built by the bootstrap team for bootstrap 5/6? 
Both seem like doable, though the later might be out of scope for the main bootstrap docs/ framework, maybe a dedicated site, similar to bootstrap themes, might be a good place for this instead.

**Comment by mdo** [comment]
Happy to see a PR here if there's a list somewhere we could pull from, but I'm not too keen on maintaining and organizing that kind of list in our main docs :).
