### ISSUE TITLE
Collapse elements do not respect data attribute configurations when manually instantiated

### ISSUE THREAD

**Issue by RyanBerliner** [twbs/bootstrap#34408]
If you manually instantiate a Collapse, than data attribute configuration (either `data-bs-parent` or `data-bs-toggle`) are not respected. They are completely ignored.

At glance it looks like [`_getConfig()`](https://github.com/twbs/bootstrap/blob/v5.0.2/js/src/collapse.js#L258) does NOT spread `Manipulator.getDataAttributes(element)` like it does in other components [`_getConfig()` (modal example)](https://github.com/twbs/bootstrap/blob/v5.0.2/js/src/modal.js#L209) methods, or even the collapses own [`static collapseInterface()`](https://github.com/twbs/bootstrap/blob/v5.0.2/js/src/collapse.js#L312).

Reduced test case
https://jsfiddle.net/owxdrvtf/3/

**Comment by GeoSot** [comment]
@RyanBerliner  thanks for pointing out this.

Take a look on #34220. I think it will resolve this issue

**Comment by RyanBerliner** [comment]
Yup, looks like that pr will address this issue. Thanks!
