### ISSUE TITLE
Bootstrap V5 : Nested Dropdowns (Submenu, Multilevel, Megamenu) 

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34407]
I made this Navbar example with **Nested Dropdowns** (Submenu, Multilevel, Megamenu) there are some issues it can be fixed but it will be helpful to all bootstrap users.

https://codepen.io/themes4all/full/abWvBwE

![Image](https://i.imgur.com/bjnceEb.png)

**Comment by mdo** [comment]
Closing as a duplicate of #27659
