### ISSUE TITLE
Bootstrap prevents 'X' element of search input boxes to clear value

### ISSUE THREAD

**Issue by danisztls** [twbs/bootstrap#34411]
Environment: Linux, Chromium latest

When a input element with `type=search` is used as the trigger of a dropdown menu the shadow DOM element 'X' will not work as expected, the input will not be cleared. It looks like Bootstrap is preventing click event propagation.

**Comment by mdo** [comment]
We nuke the &times; icon from search inputs in Reboot for standardizing the appearance of input types. I think we could potentially bring it back in v6, but for now, it'll stay as-is. This isn't a problem with dropdowns as far as I know, but the search input itself.
