### ISSUE TITLE
Should maintain standard code in example

### ISSUE THREAD

**Issue by naim886** [twbs/bootstrap#34425]
`<img src="..." class="card-img-top" alt="...">`
should be 
`<img src="..." class="card-img-top" alt="..."/>`

**Comment by ffoodd** [comment]
No need for the training slash, please see [HTML5 specification](https://html.spec.whatwg.org/multipage/syntax.html#start-tags). `img` is a void tag, meaning trailing slash can be used but doesn't have any effect nor meaning.

Better to drop it as long as you're using HTML5 `doctype`.
