### ISSUE TITLE
Add box shadow to cards

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#34421]
Following the logic of other components ($popover-box-shadow, $dropdown-box-shadow, $toast-box-shadow etc), would be very handy to have $card-box-shadow variable to set default box shadow for cards globally. Currently it can be set only with shadow utility class, but having default option set to null would be much better option

**Comment by sudhanshuranjanAki** [comment]
The best way to have box-shadow to cards for your [website UI/UX](https://srchout.com/website-development-company) is to write you custom CSS and add it in your bin folder we have done it using your own code you can visit check this link https://srchout.com/website-development-company we have also achieved the same thing

**Comment by Kopyov** [comment]
@mdo thanks for a quick action!
