### ISSUE TITLE
Add `cache` to workflows using `actions/setup-node`

### ISSUE THREAD

**Issue by oscard0m** [twbs/bootstrap#34422]
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

**Comment by sudhanshuranjanAki** [comment]
where are you using it can you send me the screen shot is this for [software development](`https://srchout.com/website-development-company`) or this is anything else please send the screen shot then only it is possible to solve the error
