### ISSUE TITLE
V5: use $variable-prefix in components

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34439]
**for example :**

instead of: `alert` class use `bs-alert` `bs` is the **bootstrap** `$variable-prefix` the same thing used in vuetify framework.

**Comment by mdo** [comment]
This has been requested before in other issues, we'll pass for now. There are tools that help with this.

**Comment by jeremywhittington** [comment]
@mdo what is a tool that helps?

**Comment by magiccDev** [comment]
Find and replace is the tool?

**Comment by letanloc1998** [comment]
Very cool feature. But does it apply for js script?
