### ISSUE TITLE
Changing the CSS variable prefix to change it dynamically without touching the code

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34437]
I was looking in the **bootstrap scss** file and I find that there are some **CSS variables** such as `--bs-position: start;` what about changing it to this example `--#{$variable-prefix}-position: start;` because someday someone who want to customize the prefix from `bs` (bootstrap) to  `tw` (tailwind) it will be easy to change it just in `_variables.scss` file without touching other files.

**Comment by ffoodd** [comment]
If I recall correctly, those are exceptions since they are only used consumed from our JS depending on Popper.js. Can someone from @twbs/js-review confirm?

**Comment by alpadev** [comment]
> If I recall correctly, those are exceptions since they are only used consumed from our JS depending on Popper.js. Can someone from @twbs/js-review confirm?

Yep https://github.com/twbs/bootstrap/pull/31178/commits/4fee5d040cc436927724e90c19d5ea2e85323aaa

**Comment by mdo** [comment]
Closing as a won't fix for now.
