### ISSUE TITLE
V5 Dropdowns Menu alignment: Add .dropdown-menu-center class

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34436]
I hope the core team adds the `.dropdown-menu-center` utility class to make the `.dropdown-menu` centered.

Reference : https://getbootstrap.com/docs/5.0/components/dropdowns/#menu-alignment

**Comment by mdo** [comment]
@GeoSot Is this more of a CSS thing for us, or something we'd have to add with Popper?

**Comment by GeoSot** [comment]
It is more a popper thing @mdo 
https://github.com/twbs/bootstrap/blob/a7942190c746b4aeefc5e7680cb396b1885670aa/js/src/dropdown.js#L239-L259
