### ISSUE TITLE
Padding-Right vs Padding...End??

### ISSUE THREAD

**Issue by fsimmons** [twbs/bootstrap#34448]
Why the change? Padding-right is a CSS property. Padding-end is not.

Same with 'padding-start'. What am I missing? LTR stuff?

https://github.com/twbs/bootstrap/blob/47bbd945f0f92f50dd2f2dbdd78d10ada39a41cb/scss/_utilities.scss#L421

**Comment by mdo** [comment]
This is for RTL, yes. Please see our v5 blog post.
