### ISSUE TITLE
Floating Label z-index error in input group

### ISSUE THREAD

**Issue by Kapsonfire-DE** [twbs/bootstrap#34449]
```html
<div class="input-group form-floating mb-3 has-validation ">
    <input type="text"
           id={idHash}
           bind:value={value}
           class="form-control  is-invalid"
    >
    <label for={idHash}>{label}</label>
    <button disabled="disabled" class="btn btn btn-outline-primary" type="button">
        <i class="fad fa-fw fa-save"></i></button>
    <div id="feedback" class="invalid-feedback">{error}</div>
</div>
```

If input-group and floating label is used together, the floating label becomes invisible on focus and or invalid/valid feedback.
It's behind the input box - adding a z-index to css solves this problem.

EDIT:
Talking about Verison 5.0.2

**Comment by foorschtbar** [comment]
Same problem here :)

**Comment by mdo** [comment]
Floating labels aren't supported in input groups, no estimate on a timeline for that changing either.
