### ISSUE TITLE
Система файлов.

### ISSUE THREAD

**Issue by sliva-name** [twbs/bootstrap#34444]
Необходимо поместить каждый набор стилей, чтобы предоставить пользователю возможность самостоятельно выбирать файлы, которые нужны ему на проект, например: слайдер поместить в отдельный файл. Пользователь сам выбирает скачивать его или нет, нужен ли он ему на проекте. Это существенно позволит ускорить загрузку страницы сайта.

**Comment by mdo** [comment]
No plans to change how we package and organize files.

**Comment by sliva-name** [comment]
But why? This is not done for long, but it brings great benefits.
