### ISSUE TITLE
Keen Themes Misspelt Word

### ISSUE THREAD

**Issue by varunmulay22** [twbs/bootstrap#34442]
Keen themes Demo1 has a word misspelt.

Keen Theme ->Profile -> Profile 1 -> Change Password

https://preview.keenthemes.com/keen/demo1/custom/apps/profile/profile-1/change-password.html
![image](https://user-images.githubusercontent.com/35381801/124683127-323df200-de81-11eb-8218-1752bff06bd9.png)

**Comment by mdo** [comment]
Themes aren't maintained by us.
