### ISSUE TITLE
offcanvas: causes re-focus of trigger element after hidden

### ISSUE THREAD

**Issue by iatek** [twbs/bootstrap#34447]
- Operating system: Windows, iOS
- Browser: All

After closing the offcanvas, the hidden event re-focuses on the trigger element. What is the reason for this, and is there a way to disable/prevent this?

offcanvas.js line 247:
```js
  EventHandler.one(target, EVENT_HIDDEN, () => {
    // focus on trigger when it is closed
    if (isVisible(this)) {
      this.focus()
    }
  })
```

So for example, if you want to navigate to an anchor from the offcanvas (like a TOC use-case), closing the offcanvas refocuses the trigger element which resets any previously performed navigation/scrolling

Test case: https://codeply.com/p/oRdIodlBVy

**Comment by iatek** [comment]
A workaround is to make the trigger element always visible using fixed positioning. Are there any other options?

**Comment by GeoSot** [comment]
Hello @iatek 

I am pretty sure that it is not a bug, as modal and collapse have the same behavior, to indicate in purpose the trigger element.

**Comment by PetersOtto** [comment]
Hi
This behavior makes my current project difficulty.
Perhaps it is no  bug but it would be great to have the possibility to disable re-focusing.
Best regards

**Comment by y377** [comment]
> Hi This behavior makes my current project difficulty. Perhaps it is no bug but it would be great to have the possibility to disable re-focusing. Best regards

## me too！
#### It caused my interaction design to stagnate, everyone, please help me, a poor person.

**Comment by y377** [comment]
> * Operating system: Windows, iOS
> * Browser: All
> 
> After closing the offcanvas, the hidden event re-focuses on the trigger element. What is the reason for this, and is there a way to disable/prevent this?
> 
> offcanvas.js line 247:
> 
> ```js
>   EventHandler.one(target, EVENT_HIDDEN, () => {
>     // focus on trigger when it is closed
>     if (isVisible(this)) {
>       this.focus()
>     }
>   })
> ```
> 
> So for example, if you want to navigate to an anchor from the offcanvas (like a TOC use-case), closing the offcanvas refocuses the trigger element which resets any previously performed navigation/scrolling
> 
> Test case: https://codeply.com/p/oRdIodlBVy

How did you solve it? I also encountered this problem, if you would like to share your experience, I would be very grateful, because I also use [jekyll-toc](https://github.com/toshimaru/jekyll-toc)
