### ISSUE TITLE
V5 Modal disappears when using vue v-if & v-model logic inside modal

### ISSUE THREAD

**Issue by Rouzy777** [twbs/bootstrap#34459]
Bootstrap v5.0.1 & v5.0.2 bug
Demo: https://streamable.com/gvp33d

- Operating system: Mac OS Catalina
- Browser and version: Chrome 91.0.4472.114

**Comment by GeoSot** [comment]
Hey @Rouzy777  

You better ask this, on the proper repo , as it is a Vue issue. If you come up to a solution, and we can help somehow, do not hesitate to indicate us the problem
