### ISSUE TITLE
Change the icon size of carousel next and previous button.

### ISSUE THREAD

**Issue by tanaysankhe** [twbs/bootstrap#34456]
I added a 'carousel with controls' from Bootstrap. I wanted to change the size of the control arrow but after inspecting, it looks like that arrow is an image placed in background-image: url() property. I tried changing the padding but it didn't work. Have a look at the control buttons here: [https://snipboard.io/7JhmXu.jpg](url)

This arrow icon doesn't look that appealing on the website. So I want to change the size of the arrow icon. Is there any way to do so? If not, then what's the reliable alternative to that?

Thank you!

**Comment by mdo** [comment]
You can change the width, height, and background-size as needed of the icon wrappers.
