### ISSUE TITLE
in minified CSS why not combine and merge classes to be less size of code?

### ISSUE THREAD

**Issue by webwamp** [twbs/bootstrap#34450]
### Discussed in https://github.com/twbs/bootstrap/discussions/34409

<div type='discussions-op-text'>

<sup>Originally posted by **webwamp** July  3, 2021</sup>
why in minified CSS version, you not combine / merge classes to have less size of code?
for example **Padding** and **Margin** and ... here this example:

`.py-0{padding-top:0!important;padding-bottom:0!important}`
`.pt-0{padding-top:0!important}` and `.pb-0{padding-bottom:0!important}`

so you can easily do this:
`.py-0,.pt-0{padding-top:0!important}` and `.py-0,.pb-0{padding-bottom:0!important}`

in this combine you have very minified and less size codes, so why you not do that? anybody can explain to me?

</div>

**Comment by mdo** [comment]
Two things: your suggestion doubles the number of selectors and could lead to specificity issues if class order is changed.

**Comment by mdo** [comment]
Two things: your suggestion doubles the number of selectors and could lead to specificity issues if class order is changed.
