### ISSUE TITLE
Change text-muted value and bind color to body-color

### ISSUE THREAD

**Issue by Psixodelik** [twbs/bootstrap#34457]
Hi

I've been doing a lot of website accessibility lately. I am very happy that Bootstrap provides a lot of possibilities for ensuring correct accessibility.

But I've been worried about the `text-muted` class for a long time. Right now, it is just a gray color, which has nothing to do with the default `body-color`.

Because of this, WCAG color contrast is only provided against a white background.

I suggest using the ready-made `tint-color` function and defining the `text-muted` color by mixing the `body-color` and white color.

You end up with something like this:

```
tint-color($body-color, 30%);
```

What do you think of it? If necessary, I will do a PR

**Comment by julien-deramond** [comment]
Reopening after reverted change that closed this issue.

**Comment by mdo** [comment]
In #35857, I'm looking at replacing the `$text-muted` value from `#666` to a new CSS variable that's responsive to color modes with `--bs-secondary-color`. This will effectively deprecate `$text-muted` and `.text-muted` which will then be removed in v6. Commit for that coming soon!
