### ISSUE TITLE
Switching rapidly between 2 floating labels break the page

### ISSUE THREAD

**Issue by joooKiwi** [twbs/bootstrap#34467]
While I was working on some testing, I tried to test my labels and all of a sudden, my page just froze.

Then after further investigation. On another page, the same situation happen.

As a reference, it does happen on them while switching between multiple floating labels.

Here is the browser render of the elements' templates:

    <div class="form-floating"><input type="text" inputmode="text" id="testInput" class="form-control" name="acronym" placeholder="Test label" aria-placeholder="Test label" data-bs-toggle="tooltip" title="" aria-readonly="false" aria-hidden="false" aria-disabled="false" required="" aria-required="true" data-bs-original-title="Test label" aria-label="Test label"><label id="testInput_label" class="form-label" aria-hidden="false" for="testInput"><span>Test</span></label></div>
 
And basically, it is just:

1. a div with the class `form-floating`
2. an input with the class acronym
3. a label associated to the input with some text
4.     <div class="form-floating"><input id="testInput" class="form-control"><label class="form-label" for="testInput"><span>Test</span></label></div>

That's really weird that happen and I don' know why it happen just while switching rapidly between 2 different floating labels.

Hope this could be resolved.

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._
