### ISSUE TITLE
Use CSS Variables

### ISSUE THREAD

**Issue by HybridSolutions** [twbs/bootstrap#34466]
I read your documentation [https://getbootstrap.com/docs/5.0/customize/css-variables/](https://getbootstrap.com/docs/5.0/customize/css-variables/) and I don't quite understand why isn't bootstrap 5 using variables for colors all over the component styling. Having concrete color values in hundreds of properties doesn't make any sense, since it forces to recompile Sass version to change them. I liked to read that you are already using some CSS variables for tables, but why not colors?!

Would love to hear why you took this approach and what are the plans for the next version. For me, this is the way to go [https://codyhouse.co/blog/post/css-custom-properties-vs-sass-variables](https://codyhouse.co/blog/post/css-custom-properties-vs-sass-variables) and hope to see it in our much appreciated Bootstrap :)

Regards

**Comment by mdo** [comment]
There are open issues and PRs that explain this, and more of our plans for them.
