### ISSUE TITLE
Bootstrap carousel 

### ISSUE THREAD

**Issue by Shmuli2015** [twbs/bootstrap#34477]
I am using the carousel and when the first slide happens is jumps to the top of the page

**Comment by smc181002** [comment]
it would be better to create a [reduced test case](https://css-tricks.com/reduced-test-cases/) in [codepen](https://codepen.io/) so that it would be easy to find out what is happening so the devs.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
