### ISSUE TITLE
Responsive variants for list-group

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [twbs/bootstrap#34479]
list-group-horizontal has responsive variants, allowing me to switch to horizontal at the different breakpoints. 

However, there's no way to switch back to vertical.

Additionally, while flex utilities can be used for direction, the borders are not correct.

I recommend a new class list-group-vertical with responsive variants.

**Comment by mdo** [comment]
For the time being, we'll pass on this as the most common use case to us has been stacking for narrow mobile viewports and expanding at larger viewports.
