### ISSUE TITLE
Accordion won't close after been opened (v5.0.2)

### ISSUE THREAD

**Issue by superdeeid** [twbs/bootstrap#34478]
hi all, 

I'm testing the new version (5.02).
I'm using **the default JS bundle + the default css**.
I'm parsing the accordion code from your website into my test html.
All accordion-item are closed but the first one at loading.
The accordion open on every accordion-item but i can't close them after.

While testing on your site, it's working... but not on my page... what am i missing?

thx in advance !

**Comment by GeoSot** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details.

**Comment by superdeeid** [comment]
i finally found the problem, sorry about that. Too much hours coding. The problem was that i was parsing 2 times the html template.
