### ISSUE TITLE
Card columns clipping

### ISSUE THREAD

**Issue by cdalexndr** [twbs/bootstrap#34473]
Using responsive `card-columns` by changing `column-count` depending on device width.

`column-count` 3 clipping:
![image](https://user-images.githubusercontent.com/22418250/125172195-f7112b00-e1c0-11eb-9724-2d13c66dfc85.png)
`column-count` 2 clipping:
![image](https://user-images.githubusercontent.com/22418250/125172216-1740ea00-e1c1-11eb-87dc-b55904349f7e.png)

Test case: https://codepen.io/cdalxndr/pen/xxdEPWP

Bootstrap 5.0.2
Win 10, 19041.1083
Firefox 89.0.2

**Comment by ffoodd** [comment]
First of all, you don't describe anything so I'm not even sure what you're considering buggy. Moreover Bootstrap 5 does not provide any styles based on CSS columns, so whatever you think is a bug: it's not in Bootstrap.

I recommend to use [Bootstrap grid and columns classes](https://getbootstrap.com/docs/5.0/layout/columns/) to fit your needs without browser inconsistencies.
