### ISSUE TITLE
Stepper arrows shift down when `input[type=number]` with floating label is focused

### ISSUE THREAD

**Issue by sumanthratna** [twbs/bootstrap#34476]
# Environment
- macOS Monterey 12.0 Beta (21A5268h)
- Chrome Version 91.0.4472.114

# Reproduction

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>form-floating</title>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
  <fieldset class="form-floating mb-3">
    <input type="number" class="form-control" id="floatingInput" placeholder="2004">
    <label for="floatingInput">Birth year</label>
  </fieldset>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>

</html>
```

https://user-images.githubusercontent.com/31281983/125177672-97f4eb80-e1ab-11eb-9097-a80f55ec8606.mov

not sure if this is fixable. I tried setting `step="any"` to see if the input's stepper arrow buttons would disappear, but they didn't so I don't know of a workaround

**Comment by ffoodd** [comment]
I made [a reduced test case on CodePen](https://codepen.io/ffoodd/pen/gOWLmJr) to better show this. It's because our `input`'s `padding-top` is increased when `label` is floated.

I'm not sure there's much we can do here, it'd require a way to trigger stepper specifically in a way that's consistent between browsers. I'll keep that in mind for later researches.

**Comment by mdo** [comment]
Yeah, there's nothing we can do here in my opinion. I don't really know if we explicitly support these `type`s beyond the textual ones either. Getting into customizing these browser-specific pseudo-element controls isn't maintainable.
