### ISSUE TITLE
Missing data-bs-show attribute in Modal

### ISSUE THREAD

**Issue by zur4ik** [twbs/bootstrap#34494]
In [Migration to v5](https://getbootstrap.com/docs/5.0/migration/) not mentioned Modal data attribute `data-bs-show`.
It was supported in v4 as `data-show`, but missing in v5
If it this attribute will not be supported, than this should be mentioned in migration docs I think.

**Comment by GeoSot** [comment]
Thanks @zur4ik  for pointing this out. 

Please feel free to make a merge request

**Comment by mdo** [comment]
This is covered by our migration guide already—we mention that we've added namespacing to all our data attributes. Closing as a won't fix.

**Comment by zur4ik** [comment]
@mdo Agree that it's mentioned in migration docs about namespacing, but that's not a point. Point is that, attribute `data-show` not migrated from v4 to v5 as `data-bs-show` it's gone completely.
Here is options list for v5:
![image](https://user-images.githubusercontent.com/140321/127058734-73e6942b-e116-40d5-99f9-8676f3e0f6a3.png)
As you can see there is no `show` option at all. 
Maybe I'm missing something from migration docs, but definitely can't find any mention about option depreciation.
