### ISSUE TITLE
Bootstrap V5 Alerts: Add auto dismiss with animated progress bar

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34498]
**example:** https://www.jqueryscript.net/demo/alert-nice-toast/

**Comment by swarup4741** [comment]
Here is a [sanbox](https://codesandbox.io/s/toast-j3yb7?file=/src/index.js) i just created as an example ... Although it needs modification... please do check it out

**Comment by swarup4741** [comment]
> **example:** https://www.jqueryscript.net/demo/alert-nice-toast/

 Here is a [sanbox](https://codesandbox.io/s/toast-j3yb7?file=/src/index.js) i just created as an example ... Although it needs modification... please do check it out

**Comment by mdo** [comment]
Closing as stale, plus we have an open draft PR for adding progress to toasts. Unsure if we'd bring the same to alerts, I don't see the use case tbh.
