### ISSUE TITLE
RTL & LTR CSS files

### ISSUE THREAD

**Issue by Alaa84kh** [twbs/bootstrap#34502]
I prefer to divide bootstrap.css to three files:
1. **bootstrap.general.css** for properties not effects by direction or alignment between RTL and LTR. It is shared between RTL & LTR pages.
2. **bootstrap.rtl.css** for RTL pages
3. **bootstrap.ltr.css** for LTR pages

By this structure, when user switch between RTL and LTR pages small file (bootstrap.rtl.css or bootstrap.ltr.css ) will download. not override whole file.

**Comment by mdo** [comment]
This would be a breaking change for us to make now, so closing as a won't fix. I also don't think we'd go this route anyway.
