### ISSUE TITLE
Latest Sass - variables .math instead of / *

### ISSUE THREAD

**Issue by creativeDM** [twbs/bootstrap#34508]
Hi Team Bootstrap!
I just installed gulp-sass and sass for Bootstrap5 Compilation

Its throwing the error and consuming the time while compilation

> $headings-margin-bottom: $spacer / 2 !default;
    │                          ^^^^^^^^^^^
    ╵
    src\scss\custom\variables\ _variables.scss 416:26  @import
    src\scss\theme.scss 6:9                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2)

Please update the variables according to latest SASS-Lang support!

Thanks!

**Comment by ffoodd** [comment]
Please read our issue template before opening an issue. There're already dozens of this, this is fixed in our main branch and a PR is opened for v4.

**Comment by tordans** [comment]
For anyone how comes here from search: https://github.com/twbs/bootstrap/pull/34571
