### ISSUE TITLE
ml-* , mr-* , pl-* , pr-* classes no longer working!

### ISSUE THREAD

**Issue by power-f-GOD** [twbs/bootstrap#34518]
Seems these utility classes were removed in v5. But I can't see a place that tells/says what their equivalents are or why they were removed!

**Comment by skmedix** [comment]
https://getbootstrap.com/docs/5.0/migration/#utilities

**Comment by ffoodd** [comment]
You can have a look at the spacing utilities docs page, too, and previous issues and discussions.

**Comment by power-f-GOD** [comment]
Hmm... that's a whole lot of migration. Thank you.
