### ISSUE TITLE
V5 Navbar: Update the navbar-toggler icon to hamburger

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34511]
**Example:**

![Image](https://i.imgur.com/UfjvYvR.gif)

Live Preview: https://mmenujs.com/mburger/

**Comment by mdo** [comment]
Navbar toggler is an SVG background-image. I don't see that changing anytime soon in v5, and since this is a Sass variable you can override, I think it'll stay as an external add-on for developers.
