### ISSUE TITLE
Accessibility issue in Bootstrap 3.x and above

### ISSUE THREAD

**Issue by madhavonebcg** [twbs/bootstrap#34528]
## Type of report
Hi team,
We are using Bootstrap v3.4.1 in our web application. We are providing Accessibility support to our clients in all the projects. There are some issues raised by the clients regarding accessibility. If these issues are fixed then they can enhance the overall experience for visually impaired users. So as a loyal and responsible user of Bootstrap, we are requesting the devs at Bootstrap to add these issues as soon as possible and when we can expect these issues to be fixed and even these issues are in the roadmap for development as these issues are becoming the bottleneck the project delivery.

## Provide detailed reproduction steps (if any)
1. Open any screen reader. Recommend to use NVDA/ JAWS
2. Navigate to the dropdown button via the tab key.
3. Press enter to open the dropdown sub-menu.
4. Navigate through the submenu items using tab/ arrow keys.
5. Notice the focus is not trapped inside the dropdown sub-menu when pressing the tab/ arrow keys on the last sub menu item instead focus goes outside the dropdown sub-menu.

### Expected result
The focus should be trapped inside the dropdown sub-menu until the user presses the Esc key or select a value.

### Actual result
The focus is going outside the dropdown sub-menu.

## Other details

* Browser: …
* OS: Windows, macOS, Android, iOS
* Bootstrap version: 3.4.1

**Comment by ffoodd** [comment]
v3 is EOL: we won't fix it now. As far as I can remember, Paypal or Ebay wrote a Bootstrap v3 plugin to enhance accessibility. You may have a look at it.

Accessibility was improved in v4 and even more in v5, so I can only encourage you to upgrade. 

Thanks for your support though!
