### ISSUE TITLE
Accessibility issues in Dropdown in Bootstrap version 4 and 5

### ISSUE THREAD

**Issue by madhavonebcg** [twbs/bootstrap#34530]
## Provide detailed reproduction steps (if any)

Open any screen reader. Recommend to use NVDA/ JAWS
Navigate to the dropdown button via the tab key.
Press enter to open the dropdown sub-menu.
Navigate through the submenu items using tab/ arrow keys.
Notice the focus is not trapped inside the dropdown sub-menu when pressing the tab/ arrow keys on the last submenu item instead focus goes outside the dropdown sub-menu.

## Expected result

The focus should be trapped inside the dropdown sub-menu until the user presses the Esc key or select a value.

## Actual result

The focus is going outside the dropdown sub-menu.

## Other details

Browser: …
OS: Windows, macOS, Android, iOS
Bootstrap version: 4 and 5

**Comment by 0388324575** [comment]
> ## Cung cấp các bước tái tạo chi tiết (nếu có) 
> Mở bất kỳ trình đọc màn hình nào. Khuyến nghị sử dụng NVDA / JAWS 
> Điều hướng đến nút thả xuống thông qua phím tab. 
> Nhấn enter để mở menu phụ thả xuống. 
> Điều hướng qua các mục menu con bằng cách sử dụng các phím tab / mũi tên. 
> Lưu ý rằng tiêu điểm không bị mắc kẹt bên trong menu phụ thả xuống khi nhấn các phím tab / mũi tên trên mục menu con cuối cùng thay vì tiêu điểm sẽ nằm ngoài menu phụ thả xuống.
> 
> ## Kết quả mong đợi 
> Tiêu điểm sẽ được giữ lại bên trong menu phụ thả xuống cho đến khi người dùng nhấn phím Esc hoặc chọn một giá trị.
> 
> ## Kết quả thực tế 
> Tiêu điểm nằm ngoài menu phụ thả xuống.
> 
> ## Chi tiết khác 
> Trình duyệt:… 
> Hệ điều hành: Windows, macOS, Android, iOS 
> Phiên bản Bootstrap: 4 và 5

**Comment by XhmikosR** [comment]
@patrickhlauke I think we have a similar issue we are tracking this?

**Comment by alpadev** [comment]
Hm it looks like with NVDA enabled, when the button is focused it is (still) using the _browse mode_. The arrow keys are swallowed and our JS stuff won't kick in. If I switch to _focus mode_ manually the arrow keys properly trap (focus always allows to jump out of the menu).

For testing I added `role="combobox"` to the `.dropdown` which fixed the arrow keys at least.

**Comment by patrickhlauke** [comment]
the implementation of dropdown menus is along the lines of a disclosure widget. it's not necessary to have focus contained/cycling inside the open disclosure/dropdown. https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure

cursor key support is an addition that we built on top. a nice-to-have. @alpadev it's normal for cursor keys to be ignored in browse mode, and it's expected behavior for disclosure widgets to remain in browse mode. a `role="combobox"` is completely separate type of widget, and does not match a dropdown.

long story short: this issue can be closed.

**Comment by patrickhlauke** [comment]
@runarberg glad to hear
