### ISSUE TITLE
V5 Dropdowns Docs: Get selected dropdown item value in the dropdown button 

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34534]
I hope the core team adds an example to the dropdowns component to make getting the **selected dropdown item value** in the **dropdown button.**

**jQuery Example:**

https://codepen.io/themes4all/pen/vYmZMWJ

**Comment by ffoodd** [comment]
That's not how a dropdown works: our dropdown implements the disclosure pattern.

What you shared acts as a select, and should be a select. Styling `option`s can be done by creating a fake select (or however you call it: select rich, etc.) but it needs to implement the related WAI-ARIA design pattern.

This would be a whole new component.

**Comment by devhoussam** [comment]
> That's not how a dropdown works: our dropdown implements the disclosure pattern.
> 
> What you shared acts as a select, and should be a select. Styling `option`s can be done by creating a fake select (or however you call it: select rich, etc.) but it needs to implement the related WAI-ARIA design pattern.
> 
> This would be a whole new component.

it will be great and helpful to all bootstrap users

**Comment by mdo** [comment]
Plenty of options out there for other projects that already support this.

**Comment by alpadev** [comment]
> Plenty of options out there for other projects that already support this.

+ it's super easy to add this with a few lines of JS and the provided events.

**Comment by devhoussam** [comment]
> > Plenty of options out there for other projects that already support this.
> 
> plus it's super easy to add this with a few lines of JS and the provided events.

Share it with us
