### ISSUE TITLE
background-image class in bootstrap 5

### ISSUE THREAD

**Issue by IslamZazoe** [twbs/bootstrap#34535]
background image in bootstrap 5 when I use it in RTL doesn't work
so to make it work normally should make position like this 

background-position: right top;
then add your own code to use it in RTL correctly

**Comment by ffoodd** [comment]
There's no `backround-image` classes in Bootstrap. Does it relate to your own code?

FWIW pour RTL version is post-processed using RTLCSS, that may be the part you're missing?

**Comment by mdo** [comment]
No plans to implement any `background-position` classes.
