### ISSUE TITLE
V5 Modals: Add loading spinner before displaying content

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34542]
I hope the core team adds **loading spinner functionality** to the **modal** before **displaying content** something similar to this example:

**Live Example:** https://codepen.io/themes4all/pen/oNWeYzp

**Comment by XhmikosR** [comment]
That's outside of the component's scope.

**Comment by devhoussam** [comment]
> That's outside of the component's scope.

it's a merge between two components

**Comment by alpadev** [comment]
To explain it with different words, it doesn't make any sense because our modal doesn't load any content that would require to show a spinner.
