### ISSUE TITLE
Carousel ignores every attempt to crop images from center

### ISSUE THREAD

**Issue by HaxtonSale1** [twbs/bootstrap#34556]
I am trying to make a carousel that:
- Works with different sized images.
- The images should Cover the carousel
- The crop should leave the center part intact, cropping equally from both directions

Since this is my first time writing webpages, I simply searched the web and cobbled together snippets to do so. However carousel does not seem to respond to any of my attempts.

Those are my 4 attempts, I got the furthest for the 4th attempt, but still very far from the desired result.

https://pastebin.com/KPVftL6D

**Comment by ffoodd** [comment]
You may also keep your `img` and try `object-fit` and `object-position`.

**Comment by XhmikosR** [comment]
Closing since this isn't an issue.

**Comment by alpadev** [comment]
> You may also keep your `img` and try `object-fit` and `object-position`.

Never heard of them 😮

**Comment by HaxtonSale1** [comment]
Sorry, the pastebin link should work now.

**Comment by HaxtonSale1** [comment]
edit: As embarrassing as it is, I'll leave the pastebin open. Thanks for your help.
