### ISSUE TITLE
Override Scss Variable value when body direction rtl

### ISSUE THREAD

**Issue by vinay1260** [twbs/bootstrap#34559]
I want to Override Scss Variable value when body direction rtl. I tried like below but its not working. I have used $FONT_REGULAR variable in lot of components, now we want to change the font name arabic version but its not working.

$FONT_REGULAR: "Roboto-Regular";

body[dir='rtl'] {
   $FONT_REGULAR: "FSAlbertArabicWeb-Regular";
}

**Comment by ffoodd** [comment]
This is not how Sass works, it doesn't now on compile time what the context is.

We use RTLCSS to post-process our compiled CSS, as [mentioned in our docs](https://getbootstrap.com/docs/5.0/getting-started/rtl/#approach).

You basically need to first use RTLCSS directive to amend tour value, then compile your CSS and finally run RTLCSS.

This will output a second CSS file, dedicated to RTL.

If you want to keep your single file and use `[dir]` selector, you need to create another variable.

**Comment by sg1asgard** [comment]
> 

Unfortunately after reading carefully the documentation and trying to implement I am having a similar issue.
It seems it does not work. Are there any examples somewhere end-to-end so i can see how it is properly implemented in a simple HTML file?

Much appreciated

**Comment by ffoodd** [comment]
You need three steps.

In your sources, this should be something like:

```scss
$FONT_REGULAR: "Roboto-Regular" #{/* rtl:"FSAlbertArabicWeb-Regular" */}
}
```

Then compile your Sass to get your LTR CSS file (which should contain the RTL comment).

Finally run RTLCSS on your LTR CSS file to postprocess RTL comments. This will output another CSS file for RTL.

You may have a look at Bootstrap's `package.json` to see how we run this.
