### ISSUE TITLE
Feature Request: Tiny buttons

### ISSUE THREAD

**Issue by sbconslt** [twbs/bootstrap#34555]
It would be useful to have a button size smaller than `btn-sm`, say `btn-tiny`, with a footprint comparable to a badge. Right now, even a `btn-sm` button expands the vertical size of its parent to taller than just text, link, and badge content would occupy.

**Comment by chaziz94** [comment]
Back in the early days of Bootstrap, there were tiny buttons. They were removed in Bootstrap 4, and for good reason. Tiny buttons would just create accessibility issues.

**Comment by XhmikosR** [comment]
Yeah, I think we'll pass on this for the aforementioned reasons.

/CC @mdo
