### ISSUE TITLE
Ability to add margin to flex items removed in v5?

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#34558]
Adding a margin to a flex item doesn't seem to work the same way in v5 as it does in v4. Is this still supported?

- Operating system and version: macOS 11.4
- Browser and version: Safari 14.1.1
- A reduced test case

[Bootstrap 4](https://www.codeply.com/p/bJkvkaRpH4)

[Bootstrap 5](https://www.codeply.com/p/43x5GPdZDU)

**Comment by mdo** [comment]
Class names changed in v5, check the migration guide.
