### ISSUE TITLE
When using btn class, you can't tell it's a button.

### ISSUE THREAD

**Issue by Maelstorm1973** [twbs/bootstrap#34569]
**Issue**

When just using the `.btn` class for `<button>`, `<input type="button">`, etc... one cannot tell that it's a button.  It's just naked text with no outline, fill, or anything.  Here's a JSFiddle to demonstrate the issue.

[https://jsfiddle.net/Maelstorm/ztmc6rfb/8/](https://jsfiddle.net/Maelstorm/ztmc6rfb/8/)

The first button shows the problem.  The border highlights when you click on it, but otherwise nothing.  The second button uses custom CSS to fill the button.  The third and fourth buttons include a border, which is how it should look, either filled or unfilled.  So it appears that a `.btn-default` class is missing, or things should be added to the `.btn` class and be overridden by any of the other button classes (ex: `btn-primary`, `btn-outline-primary`, etc...)

**Information**

Windows 10 Pro 20H2 64-bit
Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Bootstrap 5.0.3
jQuery 3.6.0

**Comment by Nightmare120** [comment]
You can also use the `btn-light` class to get a slightly grey background button.

**Comment by mdo** [comment]
Yes a modifier class is required.

**Comment by Maelstorm1973** [comment]
I see.  I was thinking that might be the issue since all the examples in the docs had modifier classes.  Part of the confusion was that requirement was not explicitly spelled out in the docs.
