### ISSUE TITLE
Bootstrap 5's  autosizing .col-breakpoint do not apply properly if a .col-number is present too

### ISSUE THREAD

**Issue by amyspark** [twbs/bootstrap#34564]
Hey!

Bootstrap v5.0.2 is unable to apply properly `.col-breakpoint` in the presence of `.col-number`. The intended effect is shown in the v4 fiddle; make sure the columns are only maximum width on xs up to the specified breakpoint, and then they split the row width among each other.

Example v4: https://jsfiddle.net/qn1f5y46/

Example v5: https://jsfiddle.net/35u72Lhy/

**Comment by momo3685** [comment]
h9eaa eerfjitictdftrxc  ietjoh vjtgiietgixcvietgicierif

erigiOAAIOERGAGITDFJI 45934895e$%^&*()_JIG JNAA TR FU TADGFTRR8 V935FJYJVJRISXXXJRI3F
>>>RTWWWBFG785_1112232

<btt>
>>>qschhyrcferietg67676776vjff





>>>001100011011101111110000001100110100101101011101101101010010101000001111011101111000011100101010101010101010010001010100101010100101001010000001000011111011101110111010010101010101010101011010101100001111011110000000001011010101010100011101111011111011111101111111100000011100010101

**Comment by momo3685** [comment]
nice
