### ISSUE TITLE
Form select not styled correctly on Safari

### ISSUE THREAD

**Issue by suhailkc** [twbs/bootstrap#34587]
macOS Big Sur
Safari 14.1.1
Bootstrap 5.0.2

[Screenshot](https://ibb.co/SN6nqk4)

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
