### ISSUE TITLE
Button Group classes are missing border-radius properties

### ISSUE THREAD

**Issue by elixirgraphics** [twbs/bootstrap#34598]
The Button Group (`btn-group`) classes are missing border-radius values. While the Buttons (`btn`) contained within the Button Group have their own border radius values, the Button Group itself also needs matching values. The problem is not apparent until a Shadow class is applied to a Button Group.

Applying a `shadow` or `shadow-lg` class to the `btn-group` produces a Button Group with a squared off white corners showing on all four corners of the Button Group, like so:

<img width="510" alt="127210855-73e183d2-f5ca-448e-bf20-be52b7194919" src="https://user-images.githubusercontent.com/2013801/127211429-f837e558-5409-4697-a053-3a5090ee7e73.png">

To remedy this we just need to add border-radius values to the following classes:

- `btn-group` : 0.25rem
- `btn-group-sm` : 0.2rem
- `btn-group-lg` : 0.3rem

Doing so fixes the problem and eliminates the squared off corners of the `btn-group`, producing a Button group with the desired results:

<img width="530" alt="CleanShot 2021-07-27 at 14 57 25@2x" src="https://user-images.githubusercontent.com/2013801/127212011-c6382222-fe13-44cb-9664-6945b5efd0bc.png">

**Comment by Palash-Vishnani** [comment]
Hey I can work on this issue. Actually I am new to this bootstrap repository, soo can anyone tell me which files or which sections of this repository do I need to modify for this issue. And also:

- btn-group : 0.25rem
- btn-group-sm : 0.2rem
- btn-group-lg : 0.3rem

These are the values that I need to apply to the above classes right.?

**Comment by Darkace01** [comment]
I think this has been fixed already

**Comment by elixirgraphics** [comment]
It looks like v5.1 might fix the border radius for `btn-group-lg` and `btn-group-sm` but I'm not seeing a border radius for `btn-group` applied anywhere.

**Comment by AndyJiang99** [comment]
Hey, if nobody's actively working on this at the moment, I'll give it a shot

**Comment by AndyJiang99** [comment]
Hey @XhmikosR , opened a PR (https://github.com/twbs/bootstrap/pull/35467) to address this issue. I wasn't able to add a reviewer directly on the PR so I figured this might be a better way to bring your attention to this. Thanks! :)

**Comment by Darkace01** [comment]
> Hey @XhmikosR , opened a PR (#35467) to address this issue. I wasn't able to add a reviewer directly on the PR so I figured this might be a better way to bring your attention to this. Thanks! :)

Can I work with you on this?

**Comment by AndyJiang99** [comment]
> > Hey @XhmikosR , opened a PR (#35467) to address this issue. I wasn't able to add a reviewer directly on the PR so I figured this might be a better way to bring your attention to this. Thanks! :)
> 
> Can I work with you on this?

Thanks for reaching out. I think the PR is pretty much done now, just waiting for approval for it to be merged into the main branch so this issue should be good to go. I don't think there is anything else to do, so I don't need help for anything for this issue. Thanks anyways though
