### ISSUE TITLE
Tooltip position issue

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#34595]
Bootstrap 5.0.2
Firefox and Chrome.

Tooltip position is wrong when top/bottom placement falls back to 'left'.

https://jsfiddle.net/1vtymkqh/1/

**Comment by alecpl** [comment]
The position fixes itself after e.g. a scroll. So, it looks like the same timing issue as in #34350.

**Comment by mdo** [comment]
Just capturing a screenshot for posterity.

<img width="304" alt="Screen Shot 2022-04-07 at 1 28 56 PM" src="https://user-images.githubusercontent.com/98681/162293711-e06e9815-3132-4cc5-8eab-43133ea965d8.png">

**Comment by GeoSot** [comment]
@alecpl  can you test one more time if this issue continues to exist in many branch after merging #36277 ?

**Comment by alecpl** [comment]
@GeoSot I confirm it's fixed in 5.2.0-beta1.

**Comment by GeoSot** [comment]
Thank you guys. 

Closing it as per above
