### ISSUE TITLE
CSS Variables and Multi Themes

### ISSUE THREAD

**Issue by Psixodelik** [twbs/bootstrap#34596]
Hey

Would like to know why CSS variables are still not used? They are generated, but the colors are taken from the already compiled ones.

If you replace everything with CSS variables, then it will be possible to create multi themes (for example, color schemes that depend on the root class)

If you suddenly need help here, then I'm always ready to help.

**Comment by mdo** [comment]
There are multiple issues and PRs addressing this already :). We're making more use of them in each release of v5. For example, #34100 and #34443.
