### ISSUE TITLE
Bootstrap JavaScript causing Issue notice in Google Chrome

### ISSUE THREAD

**Issue by Maelstorm1973** [twbs/bootstrap#34599]
**System**

Windows 10 Professional RTM x64 20H2
Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Test Case: [https://jsfiddle.net/Maelstorm/upw78zs0/](https://jsfiddle.net/Maelstorm/upw78zs0/)

**Issue**

Google Chrome is giving notice that changes are being made that will affect the functionality of software that uses several properties in the navigator class:

![bootstrap-bug](https://user-images.githubusercontent.com/12518894/127220317-fcaeb1b8-b993-4d2a-b3d6-c4733a37bfd4.png)

This appears to only affect Chrome and Chromium based browsers.

> <html>
> <body>
> <ol class="tree-outline hide-selection-when-blurred issues" role="tree" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; padding: 0px; margin: 0px; z-index: 0; position: relative; overflow: auto; --issue-indent: 8px; list-style-type: none; color: rgb(32, 33, 36); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li role="treeitem" class="issue parent expanded" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; padding-top: 0px; padding-right: 8px; padding-bottom: 0px; padding-left: var(--issue-indent); overflow: hidden; flex: 0 0 auto; transition: background-color 200ms ease 0s; border-top-color: ; border-top-style: ; border-right-color: ; border-right-style: ; border-bottom-color: ; border-bottom-style: ; border-left-color: ; border-left-style: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-width: 0px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: center; background: var(--color-background);"><div class="header" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row; align-items: center; padding: 6px 0px; cursor: pointer; width: 732.188px;"><div class="title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; font-size: 14px; color: var(--color-text-primary); font-weight: 450; user-select: text;">Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform</div></div></li><ol class="children body issue-kind-improvement expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding-left: calc(var(--issue-indent) + 43px); border-bottom: 1px solid var(--color-details-hairline-light); padding-top: 6px; position: relative; padding-bottom: 26px; padding-right: 8px; display: block;"><li role="treeitem" class="always-parent" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: center;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><devtools-markdown-view style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="message" style="line-height: 20px; font-size: 14px; color: var(--color-text-secondary); margin-bottom: 4px; user-select: text;"><p style="margin-bottom: 16px; margin-block-start: 2px;">A page or script is accessing at least one of<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.userAgent</code>,<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.appVersion</code>, and<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.platform</code>. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">To fix this issue, replace the usage of<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.userAgent</code>,<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.appVersion</code>, and<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.platform</code><span> </span>with feature detection, progressive enhancement, or migrate to<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">navigator.userAgentData</code>.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">Note that for performance reasons, only the first access to one of the properties is shown.</p></div></devtools-markdown-view></li><li role="treeitem" class="always-parent parent expanded affected-resources-label" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; margin-top: 5px; font-size: 10px; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase; color: var(--color-text-primary); display: flex; text-overflow: ellipsis; white-space: normal; position: relative; align-items: center;">AFFECTED RESOURCES</li><ol class="children expanded affected-resources" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 3px 0px 0px; position: relative; user-select: text; display: block;"><li role="treeitem" class="parent expanded" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: center; margin-top: 0px; padding: 2px 5px 0px; background: var(--color-background-elevation-0);"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><div class="affected-resource-label" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-size: 14px; line-height: 20px; color: var(--color-text-primary); position: relative; cursor: pointer;">1 source</div></li><ol class="children expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 6px 0px 9px 5px; display: block; background: var(--color-background-elevation-0); margin-bottom: 10px;"><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: center;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span>
> 
> bootstrap.bundle.min.js:1
> --
> 
> 
> </li></ol></ol><li role="treeitem" class="always-parent link-wrapper selected" tabindex="0" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; outline-width: 0px; margin-top: 15px; user-select: text; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: center;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><ul class="link-list" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; list-style-position: inside; padding-inline-start: 0px;"><li style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: center;"><x-link class="link devtools-link" tabindex="0" role="link" href="https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html" style="box-sizing: border-box; min-width: 0px; min-height: 0px; cursor: pointer; text-decoration: underline; color: var(--color-link); font-size: 14px; padding-top: 4px; display: inline;"><devtools-icon class="link-icon" style="display: inline-block; white-space: nowrap; box-sizing: border-box; min-width: 0px; min-height: 0px; vertical-align: sub; margin-right: 0.5ch;"><div class="icon-basic" style="width: 16px; height: 16px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/Images/link_icon.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--color-link));"></div></devtools-icon>Learn more: User-Agent String Reduction</x-link></li></ul></li></ol></ol>
> </body>
> </html>
>

**Comment by alpadev** [comment]
Thanks for reporting this but it's unlikely to cause any problems.

We're not browser sniffing but the `Popper` dependency does. Those detections are very basic and don't target informations that are affected by those changes. At least according to https://www.chromium.org/updates/ua-reduction.

**Comment by y377** [comment]
I have the same problem, my use case is to load [popper.js](https://github.com/floating-ui/popper.js.org) separately, for OCD developers, it is best to solve it
