### ISSUE TITLE
Email validation does not work correctly

### ISSUE THREAD

**Issue by chusmsanchez** [twbs/bootstrap#34603]
### Discussed in https://github.com/twbs/bootstrap/discussions/34602

<div type='discussions-op-text'>

<sup>Originally posted by **chusmsanchez** July 28, 2021</sup>
Hi all.

When I use form validation for an email type field, this validation does not work correctly in my opinion.

Example:

If I write: name @ domain, it validates it as being written correctly, when that is not a valid email since it is missing, for example .com or .es or .net ...

Is it possible to quickly correct this part? I think it is important to give this solution.

Greetings</div>

![image](https://user-images.githubusercontent.com/28975800/127316006-6ea7b5aa-180b-49d3-961f-ad5d31b51bbf.png)

**Comment by mdo** [comment]
This isn't on us, that's the browser verifying it or something else on your end. We don't have any specific validation JS, but instead rely on the browser to do it for us.
