### ISSUE TITLE
In RTL spacer classes wrong if $spacers are changed.

### ISSUE THREAD

**Issue by miguelesquirol** [twbs/bootstrap#34606]
I added an extra spacer under the variable: $spacers. As expected in bootstrap-grid.css is correct, with 6 options for margin and padding.

In RTL this option doesn't work and it stays at 5. Manual modifications are needed to make it work properly.

Files attached.

[Archive.zip](https://github.com/twbs/bootstrap/files/6893761/Archive.zip)

**Comment by ffoodd** [comment]
[Our RTL files are post-processed using RTLCSS](https://getbootstrap.com/docs/5.0/getting-started/rtl/#approach): I guess this is the step you're missing?

**Comment by mdo** [comment]
Assuming the last comment is the problem, closing out. <3
