### ISSUE TITLE
Changing value of $modal-inner-padding causes errors in sass compiling

### ISSUE THREAD

**Issue by garak** [twbs/bootstrap#34616]
OS: Ubuntu 20.04
Browser: n/a
Bootstrap: 5.0.2
node-sass: 4.14.1
webpack: 5.47.0

When defining `$modal-inner-padding: 2rem 1rem !default;` in my sass file, I get the following errors when compiling:

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation: "2rem 1rem times 0.5".
        on line 113 of node_modules/bootstrap/scss/_modal.scss
        from line 35 of [redacted, it's my sass file where I have above definition]
>>     padding: ($modal-header-padding-y * .5) ($modal-header-padding-x * .5);

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation: "2rem 1rem times 0.5".
        on line 113 of node_modules/bootstrap/scss/_modal.scss
        from line 35 of [redacted, see above]
>>     padding: ($modal-header-padding-y * .5) ($modal-header-padding-x * .5);

```

**Comment by mdo** [comment]
`$modal-inner-padding` only accepts a single value, not multiple values. The `padding` in the variable name is a bit misleading. Tagging as a potential improvement for v6.

**Comment by garak** [comment]
> `$modal-inner-padding` only accepts a single value, not multiple values. The `padding` in the variable name is a bit misleading. 

Well, it's perfectly working in bootstrap 5.0.1
I guess that breaking in a patch version is not so fair...
