### ISSUE TITLE
Shadow utility naming: collission when trying to make responsive, resulting in two different .shadow-sm

### ISSUE THREAD

**Issue by levu42** [twbs/bootstrap#34613]
Shadows have 4 values: [null], sm, lg, none. I tried making them responsive with this code (adapted from the documentation on how to make utilities responsive):

```css
$utilities: map-merge(
  $utilities, (
    "shadow": map-merge(
      map-get($utilities, "shadow"),
      ( responsive: true ),
    ),
  ),
);
```

The result is that I get two classes "shadow-sm" which have different meanings, one is a generic shadow[no breakpoint]-[sm for small shadow] for a small amount of shadow, another is a shadow-[sm breakpoint][-null].

**Comment by mdo** [comment]
Unfortunately not much we can do about that until v6 when we change class names (breaking changes only happen in major releases). You're welcome to change this yourself until then.
