### ISSUE TITLE
Add Bootstrap 5 customizer like it was in 3.4

### ISSUE THREAD

**Issue by radimkohout** [twbs/bootstrap#34623]
### Discussed in https://github.com/twbs/bootstrap/discussions/34610

<div type='discussions-op-text'>

<sup>Originally posted by **radimkohout** July 28, 2021</sup>
Is there something like customizer that was in for example [3.4](https://getbootstrap.com/docs/3.4/customize/) for Bootstrap 5? I have tried finding it, but I can't.</div>

**Comment by mdo** [comment]
No plans to build this ourselves, sorry. Haven't had one since v4.
