### ISSUE TITLE
Bootstrap 5 responsive table and dropdown issues

### ISSUE THREAD

**Issue by Omiod** [twbs/bootstrap#34633]
- Windows 10
- Chrome 92.0.4515, Edge 92.0.902.55, Firefox 90.0.2
- Test case: https://codepen.io/Omiod/pen/WNjJRbz

I'm trying to have a responsive table with dropdowns at the end of each row (please see the test case)
The table container needed to handle the responsiveness makes the dropdown behave badly.

I also tried to init the dropdowns via Javascrirpt to use the boundary and even the popperConfig with no avail.

The solution would be to have the dropdowns to be child of the body node, option available in other frameworks (Angular bootstrap components too...)
Maybe it is possible but I missed the right configuration?
Thank you.

**Comment by tilimac** [comment]
Hello, you have try to put `.position-absolute` on class ` .dropdown` ?

**Comment by mdo** [comment]
There are several closed issues about this, so they may be able to help you more, but you can change the `boundary` to not let the dropdown be cut off. https://getbootstrap.com/docs/5.0/components/dropdowns/#options
