### ISSUE TITLE
data-bs-boundary="viewport" doesn't work inside responsive tables.

### ISSUE THREAD

**Issue by bastinald** [twbs/bootstrap#34638]
Using BS5, I'm using `data-bs-boundary="viewport"` in my dropdown (which is inside a responsive table) and it has no effect. The dropdown still gets clipped by the `table-responsive` container.

How to fix?

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
