### ISSUE TITLE
Wide text like W3.CSS w3-wide

### ISSUE THREAD

**Issue by MrinmoyHaloi** [twbs/bootstrap#34648]
It would be great if we have a class for adding spaces between text. It looks good in some places. I saw this in w3.css. Another CSS library. Here is the demo https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_text_wide

**Comment by ffoodd** [comment]
This is `letter-spacing` and `word-spacing`. I don't think we add something for this in our core since it's not so common — but it's pretty easy to add on the Sass side using our utilities API.

**Comment by mdo** [comment]
Yup, closing as a won't fix/implement.
