### ISSUE TITLE
Button group bug in RTL mode

### ISSUE THREAD

**Issue by yasinarabi** [twbs/bootstrap#34645]
Hello every body.
I'm using Bootstrap 5 for my new project. My project is in Persian language so I'm using Bootstrap 5 RTL support.
As you can see in image bellow. In a button group that includes two buttons. Rounded corners and sharp corners are swapped.
![Screenshot from 2021-08-02 06-08-52](https://user-images.githubusercontent.com/30830629/127793816-6e19b5e4-c7a3-4559-b418-7c2727768cd3.png)

**Comment by rishabh2030** [comment]
what kind of issue you are facing tell me I can fix that

**Comment by yasinarabi** [comment]
In my project I changed direction of button group tag to ltr to fix this. But sorely that's not a clean way to fix this problem.
I reported this to aware bootstrap developers of the bug.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
