### ISSUE TITLE
Responsive dropdowns placement

### ISSUE THREAD

**Issue by SafaAlfulaij** [twbs/bootstrap#34650]
### The Current
Bootstrap uses Popper for dropdown and tooltip positioning.
This works great when you don't care a lot about responsive.

### The Should
Bootstrap should offer a way to specify the default location of a dropdown/tooltip on the different supported breakpoints, similar to how it supports different values for paddings and margins.

### The Why
Yes, Popper supports changing the placement when there is no space, but that is less than optimal.

### The Case
I have a nav menu at the bottom left, that has a dropdown which is shown to the right of the button. (It's not rendered by BS, but by Popper). On mobile, I move the nav bar to top. There, popper detects that there is no space to the right anymore, and renders it on the left. It would be much better to have it below it's button (bottom) instead.

### Simple mockup

![bootstrap-popper (Small)](https://user-images.githubusercontent.com/3509617/127912736-3b457c3f-e9bc-4bae-b10d-ff74175d5f8f.png)

_Or I'm not finding the right piece of documentation..._

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.0/components/dropdowns/#responsive-alignment is available for horizontal alignment, but you'd have to add additional CSS or JS to reposition it from side to bottom. Doing this via CSS would add a ton of compiled code and isn't worth it in my opinion.

**Comment by SafaAlfulaij** [comment]
Well, it isn't that complex.
All what we need is some new classes (dropdown-md dropend-xl), and utilize `window.matchMedia` in JS, add more suger.

I just added the proper classes based on the element attributes.

^ This is for future if anyone needed this.
