### ISSUE TITLE
[5.1.0] Adding colors to $theme-colors no longer works

### ISSUE THREAD

**Issue by charlesfries** [twbs/bootstrap#34680]
Windows 10
Chrome 92.0.4515.107
Bootstrap 5.1.0

Previously (in 5.0.2), I used the following code to add custom colors to `$theme-colors`:

```
@import "node_modules/bootstrap/scss/functions";
@import "node_modules/bootstrap/scss/variables";

$theme-colors: map-merge($theme-colors, (
  "disabled": grey,
));

@import "node_modules/bootstrap/scss/bootstrap";
```

However, applying `text-disabled` to an element now does nothing in 5.1.0. Did the API change? Do I need to generate these theme color classes manually now, like the basic color classes?

**Comment by mdo** [comment]
I'm guessing your import is overriding the variables again? You seem to be doing a blend of the import strategies mentioned at https://getbootstrap.com/docs/5.1/customize/sass/#importing.

I don't think anything should be interfering with this, but if so, we'd need a bit more of an example to be clear.

**Comment by RyanABuckley** [comment]
Using a mixture of [Option B](https://getbootstrap.com/docs/5.1/customize/sass/#importing) and [modifying maps](https://getbootstrap.com/docs/5.1/customize/sass/#modify-map), additional custom theme colors will not be added the to the `$theme-colors-rgb` map:

```
@import "node_modules/bootstrap/scss/functions";

$custom-theme-colors: (
   "custom": #ffffff
);

@import "node_modules/bootstrap/scss/variables"

$theme-colors: map-merge($theme-colors, $custom-theme-colors);

//Import utilities, mixins, components.
```
Utilities uses the new RGB variables from 5.1.0, and the `$theme-colors` are merged after the `$theme-colors-rgb` map is created in `_variables.scss`. This means `$theme-colors-rgb` will never contain the colors from `$custom-theme-colors` unless the Bootstrap `_variables.scss` is modified - which is generally a bad idea.

```
$utilities-colors: map-merge(
  $theme-colors-rgb,
  (
    "black": to-rgb($black),
    "white": to-rgb($white),
    "body":  to-rgb($body-color)
  )
) !default;
```

This means no [text or background classes](https://blog.getbootstrap.com/#updated-bg--and-text--utilities) will be created for custom theme colors, because they will always be merged after `_variables.scss` is imported.

**Comment by RyanABuckley** [comment]
As long as the `$theme-colors` map contains custom colors before importing `_variables.scss` the utilities should be generated correctly.

```
@import "node_modules/bootstrap/scss/functions";

//Define color variables

$theme-colors: (
  "primary":    $primary,
  "secondary":  $secondary,
  "success":    $success,
  "info":       $info,
  "warning":    $warning,
  "danger":     $danger,
  "light":      $light,
  "dark":       $dark,
  "custom":     #fff
);

@import "node_modules/bootstrap/scss/variables";

//Import utilities, mixins, components.
```

This then generates `.text-custom` and `.bg-custom` correctly.

**Comment by wpchannel** [comment]
I was in same situation but the doc is updated here and solved this issue: https://getbootstrap.com/docs/5.1/customize/color/#generating-utilities

**Comment by o-alquimista** [comment]
> I was in same situation but the doc is updated here and solved this issue: https://getbootstrap.com/docs/5.1/customize/color/#generating-utilities

Is there a migration guide for minor releases? That would be very useful. It took way too long for me to find this information. Frustrating.

A simple example to generate a simple `bg-custom` class without any levels would also help. The example in the documentation is so complex.

**Comment by dotnetshadow** [comment]
Looks like there needs to be clarification here about what is the correct way going forward.
In the documentation it clearly states the following: https://getbootstrap.com/docs/5.1/customize/sass/#add-to-map
Yet as others have found out this no longer works, therefore a migration step needs to be provided

**Comment by ineluki00** [comment]
> As long as the `$theme-colors` map contains custom colors before importing `_variables.scss` the utilities should be generated correctly.
> 
> ```
> @import "node_modules/bootstrap/scss/functions";
> 
> //Define color variables
> 
> $theme-colors: (
>   "primary":    $primary,
>   "secondary":  $secondary,
>   "success":    $success,
>   "info":       $info,
>   "warning":    $warning,
>   "danger":     $danger,
>   "light":      $light,
>   "dark":       $dark,
>   "custom":     #fff
> );
> 
> @import "node_modules/bootstrap/scss/variables";
> 
> //Import utilities, mixins, components.
> ```
> 
> This then generates `.text-custom` and `.bg-custom` correctly.

Yes but if you want to import $xxx from bootstrap, you must import it before $theme-colors declaration...

That's why i ended up with:

```scss
// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "~bootstrap/scss/functions";

// Importing custom previously declared variables
$custom-colors: (
  'critical': $critical,
  'high': $high,
  'medium': $medium,
  'low': $low,
  'trivial': $trivial
);

$min-contrast-ratio:   4.5 !default;

// 3. Include remainder of required Bootstrap stylesheets
@import "~bootstrap/scss/variables";

// Importing Bootstrap variables
$theme-colors: (
  'primary': $primary,
  'secondary': $secondary,
  'light': $light,
  'dark': $dark,
  "success":    $success,
  "info":       $info,
  "warning":    $warning,
  "danger":     $danger
);
$theme-colors: map-merge($theme-colors, $custom-colors);
$colors: map-merge($colors, $custom-colors);
// $theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
// Merging maps for colors utilities generation
$utilities-colors: map-merge($utilities-colors, $theme-colors);
$utilities-text-colors: map-loop($utilities-colors, rgba-css-var, "$key", "text");

@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/root"; // Required

// 4. Include any optional Bootstrap components as you like
@import "~bootstrap/scss/utilities";
...
```

**Comment by ray73864** [comment]
Having the same problem since updating to v5.1.1.

Prior to changing my custom scss file to try and solve the problem, it looked like the following:

```
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";

$grid-columns: 48;
$grid-gutter-width: 8px;

$font-family-sans-serif: "Helvetica Neue",Helvetica,Arial,sans-serif;

$link-decoration: none;

$body-bg: #EBEAEA;

$table-hover-color: #90EE90;

$vblue: #0000ff;
$vlightpink: #ffb6c1;
$vlightpink-20: #FFE9F4;
$vlime: #33ff00;
$vred: #ff0000;
$vyellow: #ffff00;
$vwarning-20: #FFFFD3;

$custom-colors: (
  "vred": $vred,
  "vyellow": $vyellow,
  "vlime": $vlime,
  "vlightpink": $vlightpink,
  "vblue": $vblue,
  "vlightpink-20": $vlightpink-20,
  "vwarning-20": $vwarning-20,
);

$colors: map-merge($colors, $custom-colors);
$theme-colors: map-merge($theme-colors, $custom-colors);

@import '../node_modules/bootstrap/scss/bootstrap.scss';
```

This resulted in me being able to use things like 'text-vred', etc... I don't want to override the red because I prefer the softer nature of it, but for some things I needed the RGB version of red.

With 5.0.0-alpha1 (I think it was alpha1 I was using), this worked 100%.

Since upgrading to 5.1.1 today (04/10/2021), my css file no longer has any custom text colours in it. It still has custom border colours.

I changed my scss file to be

```
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";

$grid-columns: 48;
$grid-gutter-width: 8px;

$font-family-sans-serif: "Helvetica Neue",Helvetica,Arial,sans-serif;

$link-decoration: none;

$body-bg: #EBEAEA;

$table-hover-color: #90EE90;

$vblue: #0000ff;
$vlightpink: #ffb6c1;
$vlightpink-20: #FFE9F4;
$vlime: #33ff00;
$vred: #ff0000;
$vyellow: #ffff00;
$vwarning-20: #FFFFD3;

$custom-colors: (
  "vred": $vred,
  "vyellow": $vyellow,
  "vlime": $vlime,
  "vlightpink": $vlightpink,
  "vblue": $vblue,
  "vlightpink-20": $vlightpink-20,
  "vwarning-20": $vwarning-20,
);

$colors: map-merge($colors, $custom-colors);
$theme-colors: map-merge($theme-colors, $custom-colors);
$utilities-colors: map-merge($utilities-colors, $custom-colors);
//$utilities-text-colors: map-loop($utilities-colors, rgba-css-var, "$key", "text");

//@import '../node_modules/bootstrap/scss/bootstrap.scss';

@import "../node_modules/bootstrap/scss/root";
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
@import "../node_modules/bootstrap/scss/images";
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/grid";
@import "../node_modules/bootstrap/scss/tables";
@import "../node_modules/bootstrap/scss/forms";
@import "../node_modules/bootstrap/scss/buttons";
@import "../node_modules/bootstrap/scss/transitions";
@import "../node_modules/bootstrap/scss/dropdown";
@import "../node_modules/bootstrap/scss/button-group";
@import "../node_modules/bootstrap/scss/nav";
@import "../node_modules/bootstrap/scss/navbar";
@import "../node_modules/bootstrap/scss/card";
@import "../node_modules/bootstrap/scss/badge";
@import "../node_modules/bootstrap/scss/alert";
@import "../node_modules/bootstrap/scss/list-group";
@import "../node_modules/bootstrap/scss/close";
@import "../node_modules/bootstrap/scss/toasts";
@import "../node_modules/bootstrap/scss/modal";
@import "../node_modules/bootstrap/scss/tooltip";
@import "../node_modules/bootstrap/scss/popover";
@import "../node_modules/bootstrap/scss/spinners";

@import "../node_modules/bootstrap/scss/helpers";

@import "../node_modules/bootstrap/scss/utilities/api";
```

But that hasn't fixed my issue, I looked at https://getbootstrap.com/docs/5.1/customize/color/#generating-utilities but it didn't really help me at all :(

**Comment by RobineSavert** [comment]
Still the same issue in Bootstrap 5.2.3, the bg or text class don't get generated. This is my code:

$custom-colors: (
  "purple": $purple
);

// Merge the maps
$theme-colors: map-merge($theme-colors, $custom-colors);

No errors in compilation, no existing bg-purple classes available..

**Comment by wpchannel** [comment]
@RobineSavert you have to put these lines between $custom-colors and $theme-colors too.

```
@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/variables";
@import "../../node_modules/bootstrap/scss/mixins";
```

**Comment by kyartun** [comment]
> Still the same issue in Bootstrap 5.2.3, the bg or text class don't get generated. This is my code:
> 
> $custom-colors: ( "purple": $purple );
> 
> // Merge the maps $theme-colors: map-merge($theme-colors, $custom-colors);
> 
> No errors in compilation, no existing bg-purple classes available..

In Bootstrap 5.2, first import scss/functions

$custom-colors: (
"purple": $purple
);

$theme-colors: map-merge($theme-colors,$custom-colors);

This only generate theme color like primary, which is not applied to bg, text. You must import the following to make it work.

@import "../bootstrap-5.2.3/scss/maps";
@import "../bootstrap-5.2.3/scss/mixins";
@import "../bootstrap-5.2.3/scss/root";

@import "../bootstrap-5.2.3/scss/helpers";
@import "../bootstrap-5.2.3/scss/utilities";
@import "../bootstrap-5.2.3/scss/utilities/api";

It work for me.

**Comment by MIvanIsten** [comment]
The main issue here is that in v4 _variables.scss `$theme-colors` was defined this way
```scss
$theme-colors: () !default;
$theme-colors: map-merge(
  (
    "primary":    $primary,
    "secondary":  $secondary,
    "success":    $success,
    "info":       $info,
    "warning":    $warning,
    "danger":     $danger,
    "light":      $light,
    "dark":       $dark
  ),
  $theme-colors
);
```

this allowed you to define and load your defaults before bootstrap and everything worked fine
```scss
# _my_variables.scss
  $my-color: #123456;
  $custom-colors: (
    "my-color": $my-color
  );
  $theme-colors:  $custom-colors;
```
```scss
# style.scss
@import '_my_variables.scss';
@import '~bootstrap4/scss/bootstrap';
```

But v5 changed to 
```scss
$theme-colors: (
  "primary":    $primary,
  "secondary":  $secondary,
  "success":    $success,
  "info":       $info,
  "warning":    $warning,
  "danger":     $danger,
  "light":      $light,
  "dark":       $dark
) !default;
```
Now you have to:
```scss
# _my_variables.scss
  $my-color: #123456;
  $custom-colors: (
    "my-color": $my-color
  );
```
```scss
# _my_overrides.scss
  $theme-colors:  $custom-colors;
```
```scss
# style.scss
@import '_my_variables.scss';
@import '~bootstrap5/scss/functions';
@import '~bootstrap5/scss/variables';
@import '_my_overrides.scss';
@import '~bootstrap5/scss/bootstrap';
```
So, you have to put your defaults in 2 separate files, and double load bootstrap functions and variables.
There must be a reason behind this change, but the old way seems better to me.
