### ISSUE TITLE
Docs: background color example for bg-body has invisible text

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#34688]
RE: https://getbootstrap.com/docs/5.1/utilities/background/

Looks like the `.bg-body` example here should have `.text-white` class so the text is visible.

![image](https://user-images.githubusercontent.com/1212885/128306467-2f602cae-0858-4111-86df-29ec0179106d.png)

**Comment by coliff** [comment]
Related issue on Shadows page examples:
https://getbootstrap.com/docs/5.1/utilities/shadows/

![image](https://user-images.githubusercontent.com/1212885/128334414-e7acbf32-a3eb-493e-b5dc-7c7b363e5dc5.png)

**Comment by GeoSot** [comment]
Nice catch @coliff  :smiley:

**Comment by ffoodd** [comment]
`.bg-body` is not supposed to be darkish, [see 5.0](https://getbootstrap.com/docs/5.0/utilities/background/).

Can't debug for now but we somehow missed that in latest reviews 😞

**Comment by mdo** [comment]
Ugh, my fault y'all 😞. Possible solution at #34699.
