### ISSUE TITLE
Problem in Documentation Bootstrap V5.1

### ISSUE THREAD

**Issue by nkamlesh** [twbs/bootstrap#34689]
The example of flex under utilities, has made use of class "bd-highlight"
e.g: <div class="d-flex p-2 **bd-highlight**">I'm a flexbox container!</div>
I have not found anything with respect to class "bd-highlight".
Output shown on documentation page of example of flex is different, than it is showed there.
output on online editor
![image](https://user-images.githubusercontent.com/46484920/128308914-ae971e5d-a4b3-442f-a593-86edeeb1aa8f.png)

output on your webpage
![image](https://user-images.githubusercontent.com/46484920/128309171-f0514184-5955-4b89-bafe-3a747c3d652e.png)

**Comment by coliff** [comment]
This isn't a bug - `.bd-highlight` is a class just for the Bootstrap Docs to highlight the divs in the examples and isn't included within Bootstrap itself.

```
.bd-highlight {
    background-color: rgba(86,61,124,0.15);
    border: 1px solid rgba(86,61,124,0.15);
}
```

**Comment by nkamlesh** [comment]
Thank you christian,
But I was not able to get any information regarding that on documentation
search box at top on left side of the webpage.

I was new in learning that and wasn't aware of, that's why raises a issue.

Thanks for your reply and thanks to all developers and contributors for
such a wonderful and powerful tool for creating responsive webpage.
