### ISSUE TITLE
Tab content of active tab (inside a Accordion) disappears after opening the Accordion.

### ISSUE THREAD

**Issue by sebastianbrosch** [twbs/bootstrap#34698]
**Operating system:** Windows 10
**Browser:** Google Chrome 92.0.4515.131

Since Bootstrap 5.1.0 the tab content of the first tab inside a Accordion isn't visible anymore.

Demo Bootstrap 5.0.2 (working): https://codepen.io/sebastianbrosch/pen/NWjONrJ
Demo Bootstrap 5.1.0 (not working): https://codepen.io/sebastianbrosch/pen/LYyBXpa

After reopening the Accordion the content of the first Tab disappears. Opening the Accordion is removing `.show` class from `.tab-pane` (and also adds a `.collapse` class to `.tab-pane`). The content of the active tab disappears after reopening the Accordion.

It looks like this commit caused the issue: https://github.com/twbs/bootstrap/pull/34220/commits/bb668550b19610b5f438d6d98be7eec4efbb0a26. If I revert this commit and try the example above the tabs are working again.

**Comment by alexandreapis** [comment]
Issue happening here too with any tab-pane parent when there is a collapse inside....

**Comment by dariocarbone** [comment]
any workaround doable at this time?

**Comment by GeoSot** [comment]
@sebastianbrosch  thank you for your examples,

I have made a regression MR #34835 .
Please use the following script and confirm that it works fine 
https://deploy-preview-34835--twbs-bootstrap.netlify.app/docs/5.1/dist/js/bootstrap.bundle.min.js

**Comment by dariocarbone** [comment]
Now it works flawless, hoping it will be a new official release soon, thanks. Sorry for bothering you, but could you please link even a bootstrap.esm.min script?

**Comment by sebastianbrosch** [comment]
@dariocarbone https://deploy-preview-34835--twbs-bootstrap.netlify.app/docs/5.1/dist/js/bootstrap.esm.min.js

**Comment by sebastianbrosch** [comment]
@GeoSot It is working fine using the deploy preview: https://codepen.io/sebastianbrosch/pen/OJgVRbP

**Comment by GeoSot** [comment]
Really, thank you both guys
