### ISSUE TITLE
CSS variables should bind to :host instead of :root (discussion?)

### ISSUE THREAD

**Issue by hugo-vrijswijk** [twbs/bootstrap#34692]
Bootstrap sets CSS variables on the `:root` element (see [here](https://github.com/twbs/bootstrap/blob/main/scss/_root.scss)). 

This can cause issues when using [shadow root](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) and loading bootstrap inside the shadow document. As CSS variables on `:root` inside the shadow document are silently thrown away. This creates some broken styling (like `text-*`, which uses CSS variables since `5.1.0`).

Reproduced on codepen: https://codepen.io/hugo-vrijswijk/pen/wvdEbyb?editors=1010

Here, Bootstrap CSS is loaded inside the shadow root. The `p` next to it has access to all bootstrap styling, except CSS variables. `fw-bold` works as it doesn't use any variables. The `text-primary` doesn't work because `--bs-primary-rgb` doesn't exist inside the shadow root.

Workaround: for the `text-*` issue, reverting to `5.0.2` works. Or, when building the SCSS manually, copy-pasting `_root.scss` and replacing it with `:host` also does the trick. Loading bootstrap _outside_ any shadow roots also works, but is not an option in my case.

Browser: Firefox 90 & Chrome 92
OS: Windows 10

![image](https://user-images.githubusercontent.com/10114577/128344065-9940330c-ba65-42c5-ae04-a3267fd8569a.png)

![image](https://user-images.githubusercontent.com/10114577/128344122-cb22ac92-1e16-4229-9258-5f7ffeaffe9d.png)

**Comment by mdo** [comment]
I don't think we'll be making this change in v5, and given v6 is likely a ways away, going to close out. We'll be revisiting all issues labeled `v6` when the time is right :).
