### ISSUE TITLE
Toggle between modals has issue

### ISSUE THREAD

**Issue by sameerparmar** [twbs/bootstrap#34691]
Toggle between modals has an issue it can't close the first modal and the second modal open on it. it was worked fine on Bootstrap Version 5.0.0. But issue faced in the latest version 5.1.0.
![Screenshot 2021-08-05 at 6 30 02 PM](https://user-images.githubusercontent.com/54928081/128354075-cdd3bc40-f04d-4f29-92c7-81cfe82984c7.png)

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by mdo** [comment]
Yeah the docs demo is broken. I think something changed with the modal triggers/toggles and we need to update this. @GeoSot might know exactly what changed.

**Comment by GeoSot** [comment]
Yes @mdo you are right.
#33403 was the first commit that changed this attitude. 

On our docs we have used some  **tricky** markup

```html
 <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Back to first</button>
    
```

As bs-dismiss wasn't searching for data-target it was closing the second modal, and bs-toggle was toggling the first modal. 
I will make a patch, to fix it and we can decide how to proceed

**Comment by thoasty-dev** [comment]
Isnt this a breaking change for anybody that uses modals inside modals?

**Comment by XhmikosR** [comment]
@thoasty-dev please make a new issue.

**Comment by Sun3** [comment]
It's also broken for me too. Any ideas when I fix might be released?

Thanks...
