### ISSUE TITLE
Navbar destroys the accordion embedded in it (5.1)

### ISSUE THREAD

**Issue by antonsmolko** [twbs/bootstrap#34704]
- Operating system and version - macOs
- Browser and version - Chrome
- A [reduced test case](https://codepen.io/antonsmolko/pen/poPxOxQ)

### Bootstrap 5.1
If the accordion is placed in the navbar, the accordion breaks - the panels stop automatically closing

![2021-08-06_19-16-01](https://user-images.githubusercontent.com/20865516/128540784-d3d24da3-da51-4aa8-90d2-f1bfbcf3e3cb.jpg)

**Comment by christinavoudouris** [comment]
Interesting idea, placing the accordion in the navbar. I don't think it's really supposed to fit in there, though, considering it's not quite wide enough. If you add options or list items to the nav, it will extend down on mid to small screens. 

Maybe try the collapse component inside the nav?

**Comment by antonsmolko** [comment]
So the collapse works without problems in .navbar-collapse. And accordion worked in version 5.0 too.
I need exactly the behavior of the accordion.
But after updating to 5.1 the accordion stopped working inside .navbar-collapse

**Comment by mdo** [comment]
It works fine for me—the accordion renders as intended and it expands and collapses without issue. What's the problem?

**Comment by bewards** [comment]
@antonsmolko gave a codepen of the issue that you can see on mobile. When the navbar is opened and you click on any of the collapses accordion items, the already expanded accordion item does not close, even though the data-bs-parent attributes are supplied. 

Why was this closed @mdo?
