### ISSUE TITLE
Add a shadow-top and shadow-hover css classes

### ISSUE THREAD

**Issue by sergeytolkachyov** [twbs/bootstrap#34700]
### .shadow-top
Sometimes we need in shadows for elements but not only by bottom side. If element places on bootm side of screen - it's shadows must be inverted from bottom to top. So I suggest to add a **.shadow-top** classes.
.shadow-top-sm{
  box-shadow: .125rem 0 .25rem rgba(0,0,0,.075)!important
}
.shadow-top {
  box-shadow:.5rem 0 1rem rgba(0,0,0,.15)!important
}
.shadow-top-lg{
  box-shadow: 1rem 0 3rem rgba(0,0,0,.175)!important
}

### .shadow-hover
It is often required to mark elements by :hover - product card in products listing, blog item in blog articles list. For this could very useful .shadow-hover classes.

.shadow-hover-sm:hover {
    box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;
}

.shadow-hover:hover {
    box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
}

**Comment by mdo** [comment]
The utility API exists for these kind of situations, so for now we'll defer you to customizing Bootstrap to add those :).
