### ISSUE TITLE
Importing v5 _utilities.scss doesn't make them added

### ISSUE THREAD

**Issue by anton-white** [twbs/bootstrap#34708]
Bootstrap version: 5.1
OS: MacOS Big Sur
Node: 16

`@import '~bootstrap/scss/utilities';` inside a SCSS file no longer adds utility classes to the stylesheets in v5.

A workaround is to add compiled CSS:
`@import '~bootstrap/dist/css/bootstrap-utilities.min.css';`

Expected behavior:
Utilities should be added as other modules imports do.

**Comment by ffoodd** [comment]
You need a few other files to compile utilities, eg. functions and utilities mixins. Please [have a look at some of our code examples](https://getbootstrap.com/docs/5.1/utilities/api/#add-utilities).

However I think it should be more obvious in our docs.

**Comment by anton-white** [comment]
@ffoodd 
thanks, but here is the full imports list I'm using prior to importing other components:
```
@import '~bootstrap/scss/functions';
@import '~bootstrap/scss/variables';
@import '~bootstrap/scss/mixins';
@import '~bootstrap/scss/reboot';
@import '~bootstrap/scss/type';
@import '~bootstrap/scss/utilities';
```
