### ISSUE TITLE
Error: get-function generated in CSS in 5.1.0

### ISSUE THREAD

**Issue by harms-tbd** [twbs/bootstrap#34719]
SASS compilation was working fine until upgrading to 5.1.0.  Now bg- classes appear like this in the resulting css

> `get-function(grba-css-var)("warning",text)`

Reverting to the previous release and recompiling SASS still works.  Do I need to change something to get this to work with the latest release?

**Comment by cklenk** [comment]
I too have this issue. Here is a ss of my diff from last version to 5.1.0
![image](https://user-images.githubusercontent.com/12185742/128718335-137ffa20-b736-43dd-9f06-c378fdf70f4a.png)
and here is my scss stack
![image](https://user-images.githubusercontent.com/12185742/128718429-ba0128c5-487f-45d8-a279-bfcb75673897.png)

**Comment by ffoodd** [comment]
Duplicates #34693. Follow-up there to get more insights.
