### ISSUE TITLE
Bootstrap 5 SCSS Hugo Module Error

### ISSUE THREAD

**Issue by tfsomrat** [twbs/bootstrap#34713]
Hi, I want to let you know that when we build a theme using Bootstrap 5 SCSS, it works fine. But when we connect this theme as a Hugo Module, then the error appears. It shows `/assets/scss/bootstrap/_mixins.scss", line 6, col 1: File to import not found or unreadable: vendor/rfs` this error message. 

It becomes fixed when we add `vendor/rfs` in local files. So the problem is `vendor/rfs` always need to be in local files. can you fix it? so we don't need to add this file again to the local machine.

**Comment by ffoodd** [comment]
Our dist files only contains compiled CSS so this error only exists if you build your CSS from Sass sources.

RFS is in our sources, so make sure to grab all of our sources before compiling.

Or am I missing something?

**Comment by tfsomrat** [comment]
We actually import the SCSS file, not the generated css file. and it works fine when we compile it. It only showing this error when we add this theme as a Hugo module. then all the file comes from theme GitHub repository. then if we add `vendor/rfs` locally, only then it works. otherwise, it shows this error.

**Comment by tfsomrat** [comment]
We need to add this file like this https://github.com/themefisher/documentation/tree/master/assets/scss, otherwise it shows this error.

check that, we didn't add any bootstrap file, only this rfs file needs to be attached.

**Comment by ffoodd** [comment]
Then as I said, `vendor/rfs` is in our sources, so make sure to grab all of our sources in your theme.

We already provide what you're asking.

**Comment by tfsomrat** [comment]
Maybe I could not able to understand you. we already provide everything in sources, check it out https://github.com/themefisher/core-docs/tree/master/assets/scss

**Comment by ffoodd** [comment]
Obviously `rfs` is where we call it, it wouldn't compile otherwise. I guess your issue is with Hugo compiler.

How would you think we could do simething, here?
