### ISSUE TITLE
bootstrap-reboot.css variables not defined in 5.1

### ISSUE THREAD

**Issue by jaryn-kubik** [twbs/bootstrap#34710]
Looking at https://github.com/twbs/bootstrap/blob/fd92e353d078175074af35a94b7a237c64d6767a/dist/css/bootstrap-reboot.css for example body.font-family is defined using css variable var(--bs-body-font-family).

But these variables are not defined anywhere. Shouldn't bootstrap-reboot.scss also import _root.scss that defines these?
Maybe I'm missing something but including just bootstrap-reboot.css no longer works on it's own and it did before.

**Comment by ffoodd** [comment]
That's right, indeed. Using `_reboot` solely needs to import `_root` on its own.

**Comment by xiejay97** [comment]
@ffoodd I think provide a default value for css variables would be better.
As `font-family: var(--#{$variable-prefix}body-font-family);`, if we provide a default value just like this: `font-family: var(--#{$variable-prefix}body-font-family, $font-family-base);`, we wont need the `--#{$variable-prefix}body-font-family` variable, it means we can set css variables only when we need.
