### ISSUE TITLE
can I add breakpoingts to fs (font size) in Bootstrap 5?

### ISSUE THREAD

**Issue by squashking** [twbs/bootstrap#34712]
I'm new to Bootstrap. I am trying to implement responsive font size using the below method, but it doesn't work at all (Bootstrap v5.0.2):

    <p class="fs-1 fs-md-3">Test text</p>

It seems that adding breakpoints to "fs" is not allowed, so "fs-md-3" cannot be recognized. And I have read the bootstrap docs on RFS, but I don't quite understand it (because I have little knowledge about scss and mixins). The docs say RFS is enabled by default in Bootstrap 5. Does it mean I don't need to add any classes to my text and text size is responsive by default? I tried :

    <p>Test text</p>

But it's not responsive. If I want to make it responsive using RFS, what classes shall I add to it or do I have to write an scss file or a mixin? Thank you very much and sorry for asking such a newbie question.

**Comment by mdo** [comment]
RFS is another project and doesn't mean you have the responsive classes for a particular property like `font-size`. We do have font-size utilities, but they're not responsive like other classes are. Typography and text in general are "responsive" in v5 as they scale up and down in size automatically. There's no class to change.

But, you can customize the utilities API to add the breakpoint classes if you wish. https://getbootstrap.com/docs/5.1/utilities/api/

**Comment by squashking** [comment]
@mdo Thank you！But I  don't see any "responsive" behavior for my text. I see my text in <P> tag and <a> tag always have the same size 16px regardless of the size of the viewport. 16px is the root font size I guess. Can you tell me how to make the font size smaller for smaller viewpoint? Thank you very much!
