### ISSUE TITLE
body-bg class color issue

### ISSUE THREAD

**Issue by chirumist** [twbs/bootstrap#34730]
Hi,
In cheatsheet page body color issue.
https://getbootstrap.com/docs/5.1/examples/cheatsheet/

This issue fixed with one variable in line number 418.
```
- "body":  to-rgb($body-color)
+ "body":  to-rgb($body-bg)
```

Also change in _root.scss file in line number 26
```
- --#{$variable-prefix}body-rgb: #{to-rgb($body-color)};
+ --#{$variable-prefix}body-rgb: #{to-rgb($body-bg)};
```

**Comment by ffoodd** [comment]
Duplicates #34688, closed by #34699.
