### ISSUE TITLE
Stacks with Gaps don't have gaps in all supported browsers (e.g. iOS 12)

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#34737]
The new Stacks helpers (https://getbootstrap.com/docs/5.1/helpers/stacks/) are neat, but they don't work in all Bootstrap-supported browsers due to using Flexbox Gap which doesn't have wide browser support. https://caniuse.com/flexbox-gap

![iOS 12.5.4 screenshot](https://user-images.githubusercontent.com/1212885/129193757-018713c3-31e2-4edf-aa36-617bed2d2129.png)

The Gap Spacing Utilities (https://getbootstrap.com/docs/5.1/utilities/spacing/#gap) are fine in iOS 12.5.4 since they use Grid Gap which is better supported.
![iOS 12.5.4 screenshot](https://user-images.githubusercontent.com/1212885/129193602-068e2a1e-39d5-4175-9d74-a57c699888ad.png)

I wonder if there should be a compatibility warning added to the Stacks docs page.

**Comment by mdo** [comment]
> I wonder if there should be a compatibility warning added to the Stacks docs page.

And to the gap utilities section, too. Want to take a stab?

**Comment by coliff** [comment]
Sure, lets agree on the wording before I open a PR.
I was thinking of something like this for the Stacks page, but not too sure - open to suggestions:

> Note: gap utility classes used with stacks use flexbox gap which isn't supported in all browsers. See https://caniuse.com/flexbox-gap for more details.

Should this be a callout with callout-warning? 14% of active browsers don't support gap property for flexbox, so it's quite a lot.
