### ISSUE TITLE
Regression in Tooltip: content doesn't update after first show

### ISSUE THREAD

**Issue by astappiev** [twbs/bootstrap#34736]
We are using a function to retrieve the content of the tooltip according to documentation.

But since bootstrap `5.1` it doesn't work anymore. It creates a `tip` element only once calling our function, but then after each new interaction (show-hide), it just reuses an existing `tip` element without updating its content.

The regression was created by [this commit](https://github.com/twbs/bootstrap/commit/a6a2d1e2df4f97486d1715a709f40f85193c4ef6#), because `this.setContent()` was removed from `show()` method.

**Comment by astappiev** [comment]
Of course, I can create a simple PR to just restore call to `setContent`, but maybe @GeoSot have a better idea

**Comment by astappiev** [comment]
I think the best solution will be to check if a result of `getTitle()` is equal to the content of an existing `tip` and update it if doesn't. 

And in the best case, we should also call `getTitle()` only once, now it is called on any `show` from `isWithContent()`.

**Comment by GeoSot** [comment]
Hello @astappiev 

Please can you be more specific?
>We are using a function to retrieve the content of the tooltip according to documentation.
> The regression was created by this commit, because this.setContent() was removed from show() method.

 I cannot understand which documented method was changed by [this](https://github.com/twbs/bootstrap/commit/a6a2d1e2df4f97486d1715a709f40f85193c4ef6#) commit

**Comment by nathan-appere** [comment]
@GeoSot this behaviour was not documented.

But the regression broke the Bootstrap doc itself. The text in the tooltip doesn't update anymore when clicking "Copy" buttons (even though the code to handle it is still there https://github.com/twbs/bootstrap/blob/v5.1.0/site/assets/js/application.js#L159 ).

Maybe `update` should work on position + content ?
