### ISSUE TITLE
Rowspan affects tbody border color

### ISSUE THREAD

**Issue by ArthurShlain** [twbs/bootstrap#34732]
Second `tbody` has wrong `border-color` on cells having `rowspan` attribute.

![image](https://user-images.githubusercontent.com/2047645/129033484-ae2323d2-b2ad-46e9-b661-1eb424c0e636.png)

<details>
<summary>HTML</summary>

```html
<table class="table table-sm">
  <thead>
    <tr>
      <th></th>
      <th class="text-end">
        <span class="fw-bold">Длина</span>
        <br>
        <span class="fw-normal">мм</span>
      </th>
      <th class="text-end">
        <span class="fw-bold">Толщина</span>
        <br>
        <span class="fw-normal">мм</span>
      </th>
      <th class="text-end">
        <span class="fw-bold">Высота</span>
        <br>
        <span class="fw-normal">мм</span>
      </th>
    </tr>
  </thead>
  <tbody class="">
    <tr>
      <td>ПСТ 60.9.2,5-Т</td>
      <td class="text-end" rowspan="3">5890</td>
      <td class="text-end" rowspan="3">250</td>
      <td class="text-end">880</td>
    </tr>
    <tr>
      <td>ПСТ 60.12.2,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1180</td>
    </tr>
    <tr>
      <td>ПСТ 60.15.2,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1480</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td>ПСТ 60.9.3-Т</td>
      <td class="text-end" rowspan="3">5890</td>
      <td class="text-end" rowspan="3">300</td>
      <td class="text-end">880</td>
    </tr>
    <tr>
      <td>ПСТ 60.12.3,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1180</td>
    </tr>
    <tr>
      <td>ПСТ 60.15.3,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1480</td>
    </tr>
  </tbody>
</table>
```
</details>

**Comment by ffoodd** [comment]
Made [a test case on CodePen](https://codepen.io/ffoodd/pen/YzQqKOz) for this.

The issue does not relate to multiple `tbody`: the selector leading to confusion is `.table > :not(:last-child) > :last-child > *`, which cannot take `rowspan` into account. It basically sets a dark border-bottom color on last children in direct table children except the last.

In other words, it takes multiple `tbody` [or more specifically `tfoot`](https://getbootstrap.com/docs/5.1/content/tables/#table-foot) into account, but cannot handle `rowspan` since we can't know if a `rowspan`ed column will be the last one in its column.

I suggest you use [our `border` utilities](https://getbootstrap.com/docs/5.1/utilities/borders/) to patch this (`border-bottom` and `border-dark` on your cells), as there's no way for us to take such case into account.

@mdo If you have any suggestion, go for it — but otherwise I'd recommend to close this as won't fix.

**Comment by ArthurShlain** [comment]
Solved with custom CSS.

**Comment by adityadees** [comment]
> Made [a test case on CodePen](https://codepen.io/ffoodd/pen/YzQqKOz) for this.
> 
> The issue does not relate to multiple `tbody`: the selector leading to confusion is `.table > :not(:last-child) > :last-child > *`, which cannot take `rowspan` into account. It basically sets a dark border-bottom color on last children in direct table children except the last.
> 
> In other words, it takes multiple `tbody` [or more specifically `tfoot`](https://getbootstrap.com/docs/5.1/content/tables/#table-foot) into account, but cannot handle `rowspan` since we can't know if a `rowspan`ed column will be the last one in its column.
> 
> I suggest you use [our `border` utilities](https://getbootstrap.com/docs/5.1/utilities/borders/) to patch this (`border-bottom` and `border-dark` on your cells), as there's no way for us to take such case into account.
> 
> @mdo If you have any suggestion, go for it — but otherwise I'd recommend to close this as won't fix.

I guess he just move from bootstrap 4 to 5  

you should to check this  for boostrap 4
https://codepen.io/adityadees/pen/jOwqqwB

and this for boostrap 5
https://codepen.io/adityadees/pen/mdwPPqd

the difference from bootstrap 4 and 5 is

![b4](https://user-images.githubusercontent.com/37553901/131607150-c0ef5178-358b-48bb-a735-8684af7247d9.png)

![b5](https://user-images.githubusercontent.com/37553901/131607162-0a1bef15-124a-4f0c-b5cd-5c2a14b470ab.png)

on bootstrap 4 you have `tbody + tbody`
but not on bootstrap 5
and here I give that #34764

**Comment by ffoodd** [comment]
Yes you're right, the move to the selector I quoted was good but targetted last children. 

Either we get `tbody + tbody` back (see my comment on your PR) or we switch `.table > :not(:last-child) > :last-child > *` and its `border-bottom` to target adjacent siblings and use `border-top`, eg. `.table > * + * > :first-child > *`. 

`tbody + tbody` feels redundant to me with the new rule targetting last children, do I'd be in favor of the other solution.

Andy thoughts?
