### ISSUE TITLE
Add data-bs-dismiss="dropdown" to close dropdown on button click

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#34749]
We have similar options for modal, offcanvas and alert, where components can be dismissed on button click. But there's no way to close dropdown menu with `data-bs-auto-close="inside"` from the dropdown itself. A simple example would be individual action button like Apply or Close/Cancel in dropdown with a form - user can fill out the form and click Apply to submit the form and close the menu. In that scenario, having an option to dismiss the menu by clicking the button that has `data-bs-dismiss="dropdown"` would be super handy.

**Comment by suhasthegame** [comment]
Hi, 
I would love to work on this. I'm a first time contributor. Can you help me?

**Comment by GeoSot** [comment]
I am not sure it is a valid request. 
**CC/** @mdo, @rohit2sharma95  your opinions please

**Comment by Kopyov** [comment]
> I am not sure it is a valid request.

I would disagree, if i may. Now with `data-bs-auto-close="inside"` we can use dropdowns instead of modals more often, especially when we need to display forms (filters, login/registration forms etc). And "Cancel" or "Close" buttons work as intended in modals and offcanvas, where we also can show same forms. So the ability to click "Close" button within dropdown menu is quite a good thing for more complex use cases

**Comment by bharatribadiya** [comment]
@mdo  Looking forward to this feature.

I have a similar case, I have used dropdown for notifications and want to use it as a fullscreen mobile view. Now I have to close the dropdown from inside then there is no option currently to close the dropdown.

**Comment by rohit2sharma95** [comment]
It seems a very unique requirement @Kopyov 😅
But that can be achieved via a small script by attaching the event on the button inside the dropdown menu. Bootstrap already provides javascript methods for flexibility and these kinds of requirements.

**Comment by Kopyov** [comment]
Well, closing modals and alerts can be also achieved via a small script, but we have data-dismiss thing for some reason. Why don’t we have it also for dropdowns? 😁

**Comment by mdo** [comment]
Closing as a won't fix. If folks have suggestions for demos and snippets to add to the docs to show this though, we'd be happy to review and merge.
