### ISSUE TITLE
modal button always deletes first item in a list in React

### ISSUE THREAD

**Issue by christinavoudouris** [twbs/bootstrap#34742]
Hello! I encountered this issue initially in a MERN stack app I'm working on. I have a list of items with the option to delete each, plus a modal asking 'Are you sure?' etc. When I use the modal, it always deletes the first item rather than the one selected.

I tried moving the delete handler to the button that opens the modal, and that works.  So the issue seems to be the modal.

Mac OS Big Sur 11.5, Chrome Version 92.0.4515.131
Test - https://bootstrap-react-test.glitch.me
View source - https://glitch.com/edit/#!/bootstrap-react-test

Alternate possible solution: If the button inside the modal is nested too far away somehow, perhaps I need to divide the component into two, and use another hook. I feel like this would create more complexity than is necessary though.

**Comment by christinavoudouris** [comment]
Update: I just made another test case with the components broken out into smaller ones, and had the same result. I guess not surprising, but incase it's useful:

Test - https://bootstrap-react-test2.glitch.me
View source - https://glitch.com/edit/#!/bootstrap-react-test2

**Comment by WinterSilence** [comment]
Your code wrong. I'm just add `data-id={meal._id}` to `.btn-success` - id always `1`

**Comment by WinterSilence** [comment]
@christinavoudouris :facepalm you create only one modal, need fix:
table `data-bs-target={'#staticBackdrop' + meal._id}`
modal `id={'staticBackdrop' + meal._id}`

**Comment by christinavoudouris** [comment]
@WinterSilence Can you remix my code and send back something that works? If so, I'd love to see it. Thanks.

**Comment by WinterSilence** [comment]
@christinavoudouris https://aback-night-lathe.glitch.me ?

**Comment by christinavoudouris** [comment]
@WinterSilence this is great! Thank you. I'm glad it's not a bug after all. Closing this issue now.

**Comment by WinterSilence** [comment]
@christinavoudouris learn write normal test cases..
