### ISSUE TITLE
Cheatsheet example page has wrong background color in 5.1

### ISSUE THREAD

**Issue by ouw-devs** [twbs/bootstrap#34744]
Since the launch of 5.1, the Cheatsheet example has some styling issues that are quite evident. The background color is set incorrectly to a very dark shade.

Compare the following:

- 5.1: https://getbootstrap.com/docs/5.1/examples/cheatsheet/
- 5.0: https://getbootstrap.com/docs/5.0/examples/cheatsheet/

This seems to be a result of the switch to the CSS custom property system for the "bg" utility. In 5.0, the value of .bg-body defaulted to #fff, now it is --bs-body-rgb, which evaluates to that dark grey color rgb(33, 37, 41).

I am not certain if this is an issue with the Example's code or an issue with 5.1 itself. Is this variable supposed to be light or dark by default? Is it being used incorrectly in the example?

- Label: examples
- Operating system: All
- Browsers: All
- Since: version 5.1

**Comment by ffoodd** [comment]
This is fixed in #34988 if I recall correctly. Thanks for reporting, though 👌

**Comment by ouw-devs** [comment]
@ffoodd ahhh I even searched "cheatsheet" and a few other things before reporting! Thanks my friend.
