### ISSUE TITLE
$dropdown-link-hover-color uses color variable instead of $dropdown-link-color

### ISSUE THREAD

**Issue by robinheidrich** [twbs/bootstrap#34746]
If you change the Sass variable $dropdown-link-color, you also have to change $dropdown-link-hover-color, because this variable uses $gray-900 instead of $dropdown-link-color. ([Check here](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L1170))

Currently:
```
$dropdown-link-color: $gray-900 !default;
$dropdown-link-hover-color: shade-color($gray-900, 10%) !default;
```

Corrected:
```
$dropdown-link-color: $gray-900 !default;
$dropdown-link-hover-color: shade-color($dropdown-link-color, 10%) !default;
```

**Comment by k99sharma** [comment]
So, only this line needs to get changed?
