### ISSUE TITLE
Toggling between Modals does not work correctly.

### ISSUE THREAD

**Issue by andreseduardop** [twbs/bootstrap#34755]
Apparently this is a problem that arose as of version 5.1.0

### Steps to reproduce the problem

1. Open [https://getbootstrap.com/docs/5.1/components/modal/](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals).
2. Go to section [Toggle between modals](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals).
3. Click the button `Open first modal`.
4. In modal 1, click on the button `Open second modal`.
5. In modal 2, click on the button `Back to first`.
6. **The problem occurs.** Modal 2 does not close and modal one is not seen.

### Conditions in which it occurs

**Browser:** Chrome.
**OS:** Android and Windows.
**Bootstrap version:** 5.1.0

**Comment by WinterSilence** [comment]
@GeoSot broke my example (:
https://github.com/twbs/bootstrap/commit/1e5e65567049cc5a7521530fbc1149f8c35b96f9

**Comment by Anay-v2** [comment]
Yes the second modal is there and the first one appers behind
this is a big issue

**Comment by tmeduho** [comment]
yeah I'm also having issues with this.

Anyone have a workaround?

**Comment by WinterSilence** [comment]
@tmeduho rollback that's unusable PR, it's worked without any additional changes in js.

**Comment by WinterSilence** [comment]
@tmeduho add `data-bs-dismiss="modal"` to button: `<button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Back to first</button>`

**Comment by tmeduho** [comment]
> @tmeduho add `data-bs-dismiss="modal"` to button: `<button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Back to first</button>`

This is what I was doing in my own code, but it was still not working. I'll look at undoing code from the commit you posted above for now.

**Comment by thoasty-dev** [comment]
What do you think about this? https://github.com/twbs/bootstrap/pull/34776

**Comment by GeoSot** [comment]
@andreseduardop 
@WinterSilence 
@Anay-v2 
@tmeduho 

Please help me a bit here.
Can you try this preview? 
https://twbs-bootstrap.netlify.app/docs/5.1/components/modal/#toggle-between-modals
Is it working for you?

**Comment by andreseduardop** [comment]
@GeoSot, it works for me.
Thanks.

**Comment by WinterSilence** [comment]
@GeoSot it's works for anybody

**Comment by GeoSot** [comment]
Closing as per above

**Comment by Sun3** [comment]
I also tested the preview and it worked. Any ideas when this fix is released? It's causing serious issues with our site... 

Thanks.
