### ISSUE TITLE
Dynamic Check-Uncheck not working after Manual Check-Uncheck

### ISSUE THREAD

**Issue by arvindmittal** [twbs/bootstrap#34754]
BS v 5.1

Dynamic Check-Uncheck works fine except
when i manually check-uncheck,
after this even though attribute CHECKED is added or removed, checkbox doesn't change!

Please see attached screen-recording

https://user-images.githubusercontent.com/60504052/129478404-06b6eb78-a85c-4739-9bdc-d1c456086558.mov

- Operating system and version (Windows 10)
- Browser and version - tested in (Chrome 92.0.4515.131 (Official Build) (64-bit), Firefox 91.0 (64-bit))

**Comment by smares** [comment]
You shouldn't set the checked or unchecked state of the checkbox in JavaScript by adding or removing the `checked` attribute, that is only meaningful to the browser on initial render. Without code, I cannot help much, but just use `element.checked = true` or `element.checked = false` or if you use jQuery, use `$(element).prop('checked', true)` or `$(element).prop('checked', true)` (note `prop` not `attr`).

**Comment by arvindmittal** [comment]
Thanks, 
Resolved!
