### ISSUE TITLE
v5 tabs don't respond to dynamic click event

### ISSUE THREAD

**Issue by TinoDidriksen** [twbs/bootstrap#34767]
On v4.6.0 one can `jQuery.click()` a tab to make it show itself. This no longer works in v5.1.0.

Testcases:
v4.6.0: https://codepen.io/tinodidriksen/pen/eYWwvPJ
v5.1.0: https://codepen.io/tinodidriksen/pen/xxdoqoL

Tested on Windows 10 with both Chrome 92 and Firefox 78.

I am aware of the workaround with `bootstrap.Tab.getOrCreateInstance(jQuery.get(0)).show()` but that feels extremely clunky when it used to just work. As far as I can see, nothing regarding this was mentioned in https://getbootstrap.com/docs/5.1/migration/ - just because jQuery is no longer required, it should still work.

**Comment by adityadees** [comment]
you can use selector like this

```
$(function() {
  $('button').click(function() {
        $('.nav-tabs a[href="#profile"]').tab('show');
  });
});
```

**Comment by TinoDidriksen** [comment]
`jQuery.tab('show')` is certainly shorter than `bootstrap.Tab.getOrCreateInstance(jQuery.get(0)).show()`, but I depend on `jQuery.click()` in other ways.

I have other events also tied to the tab's `click`, so I need that line regardless - I would just very much prefer not having to add a separate line just to trigger the tab.

**Comment by neha200** [comment]
hi, I would like to know is this issue still open? And how can I contribute to it. Can you give me some context to this issue?

**Comment by Iftimasum1** [comment]
Hi ...how are you? Maybe are well
...V5 also me ...can u see me ...

**Comment by Iftimasum1** [comment]
My phone don't have charge and what do you have for dinner ... thank you..

**Comment by GeoSot** [comment]
You can try   
```js 
 $('#profile-tab').get(0).click(); 
```

It works.

_If anyone knows the explanation of this, I would like to learn it too_


**also**, you can use:

 bootstrap.Tab.getOrCreateInstance(jQueryElement).show()

and it is not a work around as you working over a given library. It is more valid to use documented methods that "random" event triggering

**Comment by danielkerr** [comment]
sorry referenced wrong project
