### ISSUE TITLE
Collapse glitches after being shown from JavaScript

### ISSUE THREAD

**Issue by andersmmg** [twbs/bootstrap#34762]
I can't figure why this happens, nothing seems to be wrong but maybe I'm doing something weird. The Codepen linked below shows the issue.

- Manjaro Linux
- Vivaldi 4.1.2369.16 (also happens on Chrome 92)
- [Reduced test case](https://codepen.io/andersmmg/pen/VwbOodQ) (codepen)

**Comment by smares** [comment]
https://codepen.io/smares/pen/xxdvqbK

**Comment by andersmmg** [comment]
Is there not a way to trigger it from a jQuery object then? The way I'm choosing which to open is all jQuery logic for this part

**Comment by smares** [comment]
I'm afraid I don't understand what you mean. jQuery is just a bunch of helper methods for DOM interaction. What do you mean with jQuery logic? The equivalent of your one-liner is `bootstrap.Collapse.getOrCreateInstance($('#home-collapse'), { toggle: false }).show()`. Or if you really want to do it "manually", use `$("#home-collapse").addClass('show');` However, using the Bootstrap Collapse instance also handles togging the `aria-expanded` property which you should use and also animates the accordion whereas add the `show` class will simply display the accordion element expanded.

**Comment by andersmmg** [comment]
Ohh I see, I was misunderstanding. I thought it just wouldn't work with a jQuery reference, but now I see what the difference is. It got it to work how I need it!
