### ISSUE TITLE
Set initial value to range

### ISSUE THREAD

**Issue by JoaquinDecima** [twbs/bootstrap#34772]
Ranges should be allowed to set an initial value. Because it is not efficient to be in the middle. Or does not represent what you want to show

For example we can find this function in MetroCSS, where it gives us the option to put the initial data.

```html
<input data-role="slider" data-value="20" />
```
https://metroui.org.ua/slider.html#_slider_buffer

Although it is not a range, or it is not defined as such, the functionality is the same.

**Comment by ffoodd** [comment]
Shouldn't a simple `value` attribute do the job?

FWIW we don't provide any JavaScript for range input, and only apply some styles. It's not likely to change any time soon.

**Comment by mdo** [comment]
Yup, closing per last comment.
