### ISSUE TITLE
5.1 - Vertical Rule (.vr) inherits padding from .row parent

### ISSUE THREAD

**Issue by fosterdouglas** [twbs/bootstrap#34788]
When using a .vr class inside of a row, for example:

```
<div class="row">

  <div class="vr"></div>   //thick line

  <div class="col-auto"> xyz </div>

  <div class="vr px-0"></div>   //thin line

</div>
```

<img width="74" alt="Screen Shot 2021-08-20 at 8 55 02 AM" src="https://user-images.githubusercontent.com/7971443/130261286-67194171-a74b-4e67-9af4-e50b0d149fbe.png">

It seems to inherit padding-right and padding-left from the `.row > *` selector. 

As a temporary workaround, adding a `.px-0` fixed for my purposes, but not quite sure if this is intended/expected behavior or not.

Thanks!

macOS 11.5 - Apple M1
Chrome 92.0

**Comment by mdo** [comment]
We have a requirement in our grid docs that only columns can be immediate children of `.row`s, so this isn't something we'd strictly update to support and encourage. That `.row > *` selector is a prime reason why :). Using the padding utilities is a good workaround, but you could also replace the `.row` with `.d-flex` and possibly some additional utilities.

**Comment by fosterdouglas** [comment]
Makes sense. Thanks !
