### ISSUE TITLE
Enhance  .min-vh-100 / .vh-100

### ISSUE THREAD

**Issue by udf2457** [twbs/bootstrap#34786]
Currently Boostrap uses the following syntax:

```
.min-vh-100 {
  min-height: 100vh !important;
}
.vh-100 {
  height: 100vh !important;
}
```

I wanted to draw your attention to [this blog post](https://www.bram.us/2020/05/06/100vh-in-safari-on-ios/) which details the following as a more suitable alternative for ensuring `min-height` works correctly on iOS Safari:

```
.min-vh-100 {
  min-height: 100vh !important;
  @supports (-webkit-touch-callout: none) {
      min-height: -webkit-fill-available;
  }
}

.vh-100 {
  height: 100vh !important;
  @supports (-webkit-touch-callout: none) {
      height: -webkit-fill-available;
  }
}
```

**Comment by mdo** [comment]
Utilities are purposefully single `property-value` pairings, and these utilities are generated by our utility API, so no plans to add this ourselves.
