### ISSUE TITLE
5.1.0 - Incorrect variable reference in _reboot.scss

### ISSUE THREAD

**Issue by PaddyShiel89** [twbs/bootstrap#34789]
On line 30 of `_reboot.scss`

The CSS variable is named `var(--#{$variable-prefix}-root-font-size)`, however there shouldn't be a hyphen before "root". This stops custom root font sizes from working.

The correct variable is `var(--#{$variable-prefix}root-font-size)`.

Thanks

**Comment by ffoodd** [comment]
Already fixed in #34679 — thanks for reporting, though! 👌
