### ISSUE TITLE
select / form-select does not honor text-end

### ISSUE THREAD

**Issue by mmarras** [twbs/bootstrap#34797]
I expect a right-aligned drop-down menu after adding `text-end` class to `<select class='form-select'>` instead I get flush-left (standard).

Minimal example here: 
[Jsfiddle](https://jsfiddle.net/24oqk8x7/)
`text-end` is not applied, other text decorators are like e.g. `text-primary`.
______
-Windows 10.0.19041.868
-Edge Version 92.0.902.78

**Comment by mdo** [comment]
This is a CSS/browser limitation as far as I can tell, have a quick Google/StackOverflow search and you'll see what people have run into around this. Color can be changed and more, but not alignment.
