### ISSUE TITLE
why there are no classes to control the sizes of form components ?

### ISSUE THREAD

**Issue by squashking** [twbs/bootstrap#34796]
Hi, I have recently started learning Bootstrap and I'm trying to use it,  but I often find that I have to write my own classes to make the font sizes of tags like `<p>, <input>, <select>` responsive by adding media query. For example, in order to make the font size of` <p> `tag smaller on small devices I have to write something like this:

```
.my_ptag
{
font-size: 1rem;
@include media-breakpoint-down(md) {font-size: 0.7rem;};
} 

```

And I have to do similar things for `<input>, <select>.....`and all those fontsize-sensitive tags to make them responsive. But, shouldn't these features be very basic and included in Bootstrap? Doesn't Bootstrap have some classes in the form of "fs-breakpoints(sm/md/lg)-value" to implement this? OR do I miss something?

I have tried using RFS, but RFS only works for font size > 20px. But in most cases we don't use such big fonts. We only use big fonts for headings. If i want to make RFS work for small font sizes, i'll have to override it.

Thank you very much！

**Comment by squashking** [comment]
i don't know why I cannot add code in my post. it's like this:
.my_ptag
{
font-size: 1rem;
@include media-breakpoint-down(md) {font-size: 0.7rem;};
}

**Comment by WinterSilence** [comment]
[$enable-rfs](https://getbootstrap.com/docs/5.1/customize/options/)

**Comment by squashking** [comment]
@WinterSilence This feature has nothing to do with RFS.  And In fact, RFS is enabled in Bootstrap 5 by default.

**Comment by squashking** [comment]
@wackerm  RFS is already enabled by default. But it does not work as expected. For example,  for the same `<p>` element, on large device it is one line but on small device it becomes 2 lines, so i'll have to write my own classes to make the font smaller on smaller devices to make it also occupy one line as on large devices.

**Comment by ffoodd** [comment]
Indeed. RFS (and Bootstrap) considers that `16px` is small already, so only text above `20px` is able to reduce.

However please read our docs and RFS's one: you're able to customize this threshold with `$rfs-base-value`.

Moreover what you're describing (keeping text on a single line) is not encouraged nor what RFS does : your text will become unreadable since its size would depend on its lentgh.

We won't change our default settings nor provide a way to keep text on a single line (without truncating it visually) so I'm closing this and can only encourage you to take a deeper look at RFS and how it works.

**Comment by squashking** [comment]
@ffoodd Thanks for the suggestion, but "keeping text in the same line" is not actually my goal, it's just an example. My goal is to keep the layout neat and clean. I find every so often that the layout looks good on large screens but very messy on small screens (unfortunately i cannot post pics here to demonstrate the issue), that's why I have to reduce the font size of these font-related elements. It's very strange that Bootstrap does not have such features which I assume is very basic. I don't know if I have missed something in Boostrap since I'm a novice.

**Comment by squashking** [comment]
16px is small on big screens. But on a cellphone it's way too big, especially for non-English texts (e.g., Asian scripts)
