### ISSUE TITLE
V5.1.0 dropdown is not appending show class to <button> and <div class='dropdown-menu'>

### ISSUE THREAD

**Issue by joneldiablo** [twbs/bootstrap#34807]
the dropdown works ok in V5.0.X-beta2 but when I update to V5.1.0 they don't work

**Comment by GeoSot** [comment]
Please @joneldiablo , bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link

**Comment by Iftimasum1** [comment]
#34807
