### ISSUE TITLE
v5.1 cheatsheet is totally broken

### ISSUE THREAD

**Issue by Superhands89** [twbs/bootstrap#34806]
I was looking to download the Boostrap 5.1 cheatsheet example from getbootstrap.com but it appears to be in some sort of broken dark theme state...

https://getbootstrap.com/docs/5.1/examples/cheatsheet/

Tested on Windows 10 latest stable Chrome and Firefox.

![image](https://user-images.githubusercontent.com/16403756/130510680-e5c23b2e-89c1-457e-8821-6ce2ae6aea46.png)

**Comment by ffoodd** [comment]
Thanks for reporting, this is already fixed in #34699. Expect a new release in the coming weeks 👌
