### ISSUE TITLE
The default font-width of .lead looks too thin on Windows

### ISSUE THREAD

**Issue by honzajavorek** [twbs/bootstrap#34813]
I hope this hasn't been discussed, I tried searching issues before opening this. I use default styling of `.lead`, and the `font-weight` looks way too thin on Chrome on Windows (my friend's machine):

![image](https://user-images.githubusercontent.com/283441/130639179-add798d1-7ae6-4aec-a155-6187796dc70c.png)

Compare to Firefox on macOS (my default):

![image](https://user-images.githubusercontent.com/283441/130639266-3f17af67-1794-4e11-b8b3-4d9451208fa2.png)

I don't mind it's not pixel-perfect, that's okay. I mind that this way the `font-width` is **close to unreadable** for possibly a large portion of users, ruining **accessibility** of the text to a certain degree.

I can override the style and make the text bolder, but one of the main reasons why I use Bootstrap is a certain level of security that I don't have to check everything everywhere, and that Bootstrap's defaults are sensible to use out of the box. For that reason I think this is a bug.

**Specs**
Bootstrap v5.1.0
Live preview of the page: https://junior.guru/club/

**Comment by liskin** [comment]
Some more arguments for avoiding font-weight 300:
* https://css-tricks.com/font-weight-300-considered-harmful/
* https://work.lisk.in/2020/07/18/font-weight-300.html

**Comment by mdo** [comment]
Closing as stale, going to keep this as-is for now.
