### ISSUE TITLE
Popover option trigger 'focus' doesn't work in Safari (bootstrap 5)

### ISSUE THREAD

**Issue by hailie-rei** [twbs/bootstrap#34837]
Hi,
I'm using Bootstrap 5.1.
It seems that the option `trigger="focus"` breaks popover in Safari.
I created a Codepen example https://codepen.io/hailie-rei/pen/PojPRRB. When I click the button in Chrome and Firefox, I see the popover. But when I click the button in Safari, nothing happens. Maybe it's important that I'm using html in popover content.

Safari version: Версия 13.1 (15609.1.20.111.8),
Chrome version: 92.0.4515.159
Firefox version: 91.0.1

**Comment by jnizet** [comment]
As the [documentation](https://getbootstrap.com/docs/5.1/components/popovers/#dismiss-on-next-click) indicates, your a tag needs to have a tabindex attribute.
