### ISSUE TITLE
Add d-sticky class

### ISSUE THREAD

**Issue by AkramiPro** [twbs/bootstrap#34839]
hi . please add d-sticky class for position: sticky . 
i know that threre is sticky-top class but if we want to stick on bottom we need sticky-bottom or d-sticky.

**Comment by ffoodd** [comment]
Use `.position-sticky` and `.bottom-0`, they already exist.

**Comment by florianlacreuse** [comment]
@ffoodd With [`.sticky-top`](https://getbootstrap.com/docs/5.1/helpers/position/#sticky-top) we have a custom z-index value and responsive variations (e.g. `.sticky-lg-top`). It would be convenient to have the same utilities for a bottom sticky, like `.sticky-${breakpoint}-bottom`.

**Comment by ffoodd** [comment]
That's another feature, feel free to open a new issue to discuss this.

**Comment by AkramiPro** [comment]
i open new issue :
https://github.com/twbs/bootstrap/issues/35503

**Comment by florianlacreuse** [comment]
@ffoodd OP was talking about `d-sticky` but also about `sticky-bottom`, so I thought I could talk about `.sticky-${breakpoint}-bottom` here. With the new issue opened by OP everything is back in order.
