### ISSUE TITLE
btn-toggle collapse content stutters when expanding

### ISSUE THREAD

**Issue by dk-raw** [twbs/bootstrap#34838]
When expanding a collapsed menu, the content stutters when it reaches the bottom and then the animation stops. You can see it for yourself in [this sidebar](https://www.mathflare.xyz/ "mathflare.xyz"). 

- Operating system: Windows 10 Pro 21H1
- Browser: Mozilla Firefox 91.0.2
_The bug is still there in chromium and Android 10._

**Comment by GeoSot** [comment]
@dk-raw  It would really help to make a reduced test case example on codepen where we can experiment

**Comment by dk-raw** [comment]
Sure, here you go https://codepen.io/dk-raw/pen/LYLGYpG

**Comment by crftwrk** [comment]
Replacing the my-2 classes by py-2?

**Comment by GeoSot** [comment]
Closing as per above
