### ISSUE TITLE
group button issue in RTL

### ISSUE THREAD

**Issue by mjaber** [twbs/bootstrap#34849]
Hello

in bootstrap v5.1.0, this class

.input-group>:not(:first-child):not(.dropdown-menu):not(.valid-tooltip):not(.valid-feedback):not(.invalid-tooltip):not(.invalid-feedback) {
margin-left: -1px;
border-top-left-radius: 0;
border-bottom-left-radius: 0;
}

should be right

[https://codepen.io/mjaber-the-looper/pen/ExXPeqQ](https://codepen.io/mjaber-the-looper/pen/ExXPeqQ)

**Comment by ffoodd** [comment]
You need to use our RTL CSS file. See [your updated CodePen](https://codepen.io/ffoodd/pen/WNOwpXV), everything's working fine. 
Please read [our RTL docs](https://getbootstrap.com/docs/5.1/getting-started/rtl/#required-html) carefully. :)
