### ISSUE TITLE
Flex shrink utility class's explanation in the docs of bootstrap 4.6 is not good.

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#34844]
### Discussed in https://github.com/twbs/bootstrap/discussions/34843

<div type='discussions-op-text'>

<sup>Originally posted by **AnupamKhosla** August 30, 2021</sup>
In bootstrap 4.6 docs, [Grow and Shrink](https://getbootstrap.com/docs/4.6/utilities/flex/#grow-and-shrink) usage is not explained properly for `.flex-shrink-*`.    

We know by default any flex-item gets `flex-shrink: 1` as their initial value. So in the example given in the docs as below:  

```
<div class="d-flex bd-highlight">
  <div class="p-2 w-100 bd-highlight">Flex item</div>
  <div class="p-2 flex-shrink-1 bd-highlight">Flex item</div>
</div>
```
Removing ` flex-shrink-1` would not change anything. This situation is not a good example for the usage illustration of `.flex-shrink-*` utility classes. The authors need to add a better example.
</div>

**Comment by Sarfraz-droid** [comment]
```
<div class="d-flex bd-highlight">
  <div class="p-2 w-100 bd-highlight">First Flex item</div>
    <div class="p-2 flex-shrink-0 bd-highlight">Second flex item</div>
    <div class="p-2 w-100 bd-highlight">Third Flex item</div>
      <div class="p-2 bd-highlight">Fourth flex item</div>
</div>
```

Can we add this?

**Comment by mdo** [comment]
@Sarfraz-droid If you still want this added, please open a PR.
