### ISSUE TITLE
Buttons don't have inset shadow on active.

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#34859]
The [Bootstrap 4.6 spec says](https://getbootstrap.com/docs/4.6/components/buttons/#active-state)

> Buttons will appear pressed (with a darker background, darker border, and **inset shadow**) when active 

On inspecting I didn't see any inset box shadow being applied. Not only that, doing `ctrl + F` on the whole [bootstrap css file](https://getbootstrap.com/docs/4.6/dist/css/bootstrap.css)  for `inset` keyword doesn't match anything.

Are we really supposed to have an inset/inner shadow, or is it a typo?

**Comment by mdo** [comment]
Nearly all shadows are disabled by default. We could update the docs messaging to reflect that.

**Comment by AnupamKhosla** [comment]
@mdo On top of that there should be at least one demo of how would the button look like after setting the scss variable `yes` for the inset shadow. People might make a decision on the basis of looks, rather recompiling the scss yourself to see how it looks with inset shadow and then probably not deciding to use it.

**Comment by mdo** [comment]
That's a little tough tbh, since it's a global setting. Either all shadows are enabled or none are right now. This might be possible when we move to more CSS variables, but until now, it'll have to be a docs mention.

**Comment by XhmikosR** [comment]
Fixed by #34966
