### ISSUE TITLE
Issues with bootstrap 5 API

### ISSUE THREAD

**Issue by S8F** [twbs/bootstrap#34867]
I have just installed Bootstrap 5 using npm.
And I am running into a small but annoying problem. After everything is setup and installed, I want to test if I am able to change some of the default colors in bootstrap into my own.

A simple example:

```
@import "/node_modules/bootstrap/scss/bootstrap.scss";

$primary: red;
```

But when I compile the project, it's still blue. However when I change the primary color directly in the _variables.scss inside node-modules, it works fine. But from what I understand it's not recommended to work inside bootstraps default sass files.

What am I doing wrong?

**Comment by fchiumeo** [comment]
https://getbootstrap.com/docs/5.1/customize/sass/#variable-defaults

**Comment by mdo** [comment]
Yeah, this is well documented as linked above. Always open to improvements though!
