### ISSUE TITLE
Why use px units for default gutter, but then rem units in px-lg-* and mx-lg-* to modify gutters?

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#34862]
I have asked this originally as a question on [stackoverflow](https://stackoverflow.com/q/68981775/3429430).  

If you inspect any bootstrap 4 `container > row > col` structure, you will notice that bootstrap 4 uses `15px` paddings and `-15px` margins on left and right. I think the reasoning for not using `rem` is that if user changes default browser size, e.g. by going in chrome://settings/appearance, bootstrap doesn't want to change the **gutter** size as well. _And,_ if you choose to change the font-size of the whole website by modifying `font-size` on the root element(`html` in this case), bootstrap 4 wants to still have 15px gutters regardless.

Fair enough makes sense, e.g. Nobody wants a navigation/layout to break by increasing navitem links' padding too much(paddings in `rem`) if user opts for extra large font size in the browser settings.

Surprisingly, reading the [gutter section of bootstrap 4 docs](https://getbootstrap.com/docs/4.6/layout/grid/#gutters), I found out they suggest using `px-lg-5` and `mx-lg-n5` to customize gutter width for screen sizes >= 992px. The irony is these classes use paddings and margins in `rem` as following:  

    .ml-lg-n5, .mx-lg-n5 {
        margin-left: -3rem!important;
    }
    
    .pr-lg-5, .px-lg-5 {
        padding-right: 3rem!important;
    }

So this brings me to ask the question:  

**What's the rationale of bootstrap 4 using `px` units for default gutter sizing, but then rem units in `.px-lg-*` and `.mx-lg-*` to modify the gutter sizing?**

**Comment by florianlacreuse** [comment]
Just to clarify that this behavior has been changed in Bootstrap 5. The default gutter is now expressed in `rem`.

https://getbootstrap.com/docs/5.0/layout/gutters/#how-they-work

**Comment by mdo** [comment]
Yup, v4's approach has been iterated on for v5. No good reason other than sometimes we don't get it all right in each major version :).
