### ISSUE TITLE
Smooth scrolling documentation

### ISSUE THREAD

**Issue by DeltaNove** [twbs/bootstrap#34866]
Hi! Is there any option to enable "scroll-behavior: smooth" and attach to html element?
Would it be possible to do?
Thank you

**Comment by ffoodd** [comment]
It's already implemented, as you may notice in [our accessibility docs](https://getbootstrap.com/docs/5.1/getting-started/accessibility/#reduced-motion). As explained, it's only enabled for people who don't ask for reduced motion through their system settings.

**Comment by ffoodd** [comment]
We also check for `$enable-smooth-scroll` and it's not documented ATM in [our Sass options page](https://getbootstrap.com/docs/5.1/customize/options/) so it's something to add, obviously.

**Comment by alan-oliv** [comment]
> We also check for `$enable-smooth-scroll` and it's not documented ATM in [our Sass options page](https://getbootstrap.com/docs/5.1/customize/options/) so it's something to add, obviously.

I'd love to help here and document, if you guys like

**Comment by ffoodd** [comment]
Sure, give it a shot 👌

**Comment by alan-oliv** [comment]
> Sure, give it a shot 👌

it's [done](https://github.com/twbs/bootstrap/pull/34877)! 🚀
