### ISSUE TITLE
In Bootstrap 5 using the class form-control in the element input of a checkbox will produce a checkbox with different shape

### ISSUE THREAD

**Issue by vtamara** [twbs/bootstrap#34873]
- Operating system and version: It doesn't depend on Operating system although I use OpenBSD/adJ 6.9
- Browser and version: It doesn't depend on browser I reproduced the problem with Chromium 90.0.4430.72 and with Firefox 88
- Reduced test case:
```
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">
    Standard checkbox
  </label>
</div>

<div class="form-check">
  <input class="form-check-input form-control" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">
    Element input has class form-control
  </label>
</div>
```

Will produce:
![Class form-control in checkbox changes shape of checkbox 2-9-2021 6-12-58 a- m-](https://user-images.githubusercontent.com/701221/131833966-4bcbb5cf-ce1c-46ea-ba0f-808598057d04.png)

This test case is available at  https://codepen.io/vtamara/pen/BaZzyrv

**Comment by ffoodd** [comment]
Indeed, you're not supposed to use `.form-control` in that case, but only `.form-check`.

Check [our form checks docs](https://getbootstrap.com/docs/5.1/forms/checks-radios/) for valid examples.
