### ISSUE TITLE
Issues when Upgrading from Boostrap 4 to Bootstrap 5

### ISSUE THREAD

**Issue by rdipronio-99** [twbs/bootstrap#34876]
I wanted to upgrade my django desktop application to the latest python/django/boostrap.  I am at Bootstrap 4 and rely heavily on jQuery scripts.  Upgrading Python to 3.9 and Django to 3.2 went exceedingly well.  Upgrading to Bootstrap 5 was a fiasco. You introduced multiple breaking changes and did not provide a good path for jQuery other than to re-code them in javascript or utilize some obscure method.  This is an unacceptable burden on my time and reflects very poorly on your product roadmap decisions!  I reverted to Bootstrap 4 and everything works as it should.  I will be staying on Bootstrap 4 until I find a replacement for bootstrap.
Cheers,
"One Disgruntled User"

**Comment by ffoodd** [comment]
This is a major release, meaning breaking changes. Everything is documented in our migration guide and in each component's docs.

Sorry to get such feedback without any sepcific issues we may help with.

Good luck with your framework migration.
