### ISSUE TITLE
Responsive image height overflow

### ISSUE THREAD

**Issue by cdalexndr** [twbs/bootstrap#34885]
While using `.img-fluid`, if the image height is larger than the container's , then the image can overflow:
![image](https://user-images.githubusercontent.com/22418250/131922832-e4929019-25df-4c99-9697-10b88e89def7.png)

Codepen: https://codepen.io/cdalxndr/pen/gORMGPE

Also, it would be nice for the [docs](https://getbootstrap.com/docs/5.1/content/images/) should include samples for all types of image sizes:

- width too large
- height too large
- both too small
- both too large

Bootstrap 5.1.0
OS: Win10 19043
Browser: Firefox 90.0

**Comment by cdalexndr** [comment]
The following seems to fix it:
```
.img-fluid{
  object-fit:contain;
  height:100%;
}
```

**Comment by mdo** [comment]
Implementing something like that might not be the best solution for everyone, so we don't use it by default. Definitely an add-on individual developers and designers should choose to use :).

**Comment by cdalexndr** [comment]
Seems bad that responsive images are broken by default...

**Comment by mdo** [comment]
They're not broken by default, they specifically are designed to keep the aspect ratio of an image while preventing it from being too wide. There's no assumption of scaling an image based on a fixed height container. Changing to include additionally properties would potentially break images for everyone else.

**Comment by cdalexndr** [comment]
Then [docs](https://getbootstrap.com/docs/5.1/content/images/) should be changed to reflect this.

From docs:

- `...responsive behavior (so they never become larger than their parent elements)`
- `...image so that it scales with the parent element.`

From the above statements I understand that a responsive image is expected to not have a height greater than it's parent (see `larger than their parent` statement), but this is **incorrect** as I demonstrated.

Statements should be changed to reflect that only width is taken into account.
