### ISSUE TITLE
Offcanvas not showing with class .show

### ISSUE THREAD

**Issue by frosadev** [twbs/bootstrap#34894]
Hi all,

I'm trying to use the offcanvas opened by default but adding the class .show is not working (it is closed as default).
Using these versions:
https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css
https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js

```
<div class="offcanvas offcanvas-start show" data-bs-scroll="true" tabindex="-1" id="offcanvas" data-bs-backdrop="false" aria-labelledby="offcanvasNavbarLabel" style="width:300px;">
	<div class="offcanvas-header">
		<a href="/">
			<img src="assets/logo.png" alt="Logo">
		</a>
		<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
	</div>
	<div class="offcanvas-body">
	</div>
</div>
```

Adding on the style "visibility:visible;" starts showing by default but the buttons for dismiss and toggle seems not working on the first click.

Using it inside the main navbar (exactly as the example provided on the docs).

Am I missing something?
Could you help, please?

- Windows 10
- Edge latest version

**Comment by GeoSot** [comment]
@frosadev take a look on this codepen. https://codepen.io/GeosSV/pen/WNOxKJd
Does it works for you?

**Comment by frosadev** [comment]
@GeoSot thanks for the reply.
Your example works on codepen but not on my environment.

I'm having these error messages on the console (not always).

![image](https://user-images.githubusercontent.com/26621392/132001185-907bb565-9ed5-43e5-aa8b-4541936e5652.png)

The strange thing is that starts working after.
Maybe an initialization issue?

**Comment by recursivecodes** [comment]
> @frosadev take a look on this codepen. https://codepen.io/GeosSV/pen/WNOxKJd
> Does it works for you?

This codepen works, but - open the console and try this:

```
new bootstrap.Offcanvas(document.getElementById('offcanvasTop')).hide()
```

It won't close programmatically - I think this is a separate bug?

**Comment by GeoSot** [comment]
> new bootstrap.Offcanvas(document.getElementById('offcanvasTop')).hide()
 Try:
```js

bootstrap.Offcanvas.getOrCreateInstance('#offcanvaTops').hide()
```




>Your example works on codepen but not on my environment.

I managed to find windows 10 with Edge latest version. Unfortunately, I successfully opened codepen example, plus a demo of the same code , as an html file.
So I do not know how to help you, without replicating it

**Comment by recursivecodes** [comment]
Thanks!
