### ISSUE TITLE
Navbar: transparent line flickers as you scroll

### ISSUE THREAD

**Issue by dejurin** [twbs/bootstrap#34908]
macOS BigSur 11.3
Version 93.0.4577.63 (Official Build), (arm64)

Hello, 
I noticed this problem: when you scroll down or up, there is a transparent bar at the top of the window above the navigation links; It flickers as you scroll.

<img width="528" alt="Снимок экрана 2021-09-04 в 19 06 59" src="https://user-images.githubusercontent.com/4470015/132101023-24130629-abd6-49d0-9bb8-9f3e3f4f8b0a.png">

Example: https://jsfiddle.net/yuridarwin/kndp534y/5/ 

https://user-images.githubusercontent.com/4470015/132101140-0bc88840-c53c-43f9-a554-e58bc258dc6a.mov

**Comment by mdo** [comment]
This works smoothly on my end in every browser. Perhaps there's some browser zooming or something else interfering with the scroll? I've seen both have an impact on such things in the past.

**Comment by dejurin** [comment]
> This works smoothly on my end in every browser. Perhaps there's some browser zooming or something else interfering with the scroll? I've seen both have an impact on such things in the past.

I have a 5k monitor, and I'm always watching the browser in a relatively small window,  I'm constantly changing the size of the browser in dev. I drag the browser window to another monitor, and it's fine. Fantastic.
