### ISSUE TITLE
bootstrap 5 scrollspy misbehaves if you reload on middle of a page

### ISSUE THREAD

**Issue by amirsarfar** [twbs/bootstrap#34905]
I have scrollspy in one of my pages. The scroll element is body.
It works all fine on the first load, but if you reload the page in the middle (scroll and then reload), all scrollspy stuff gets buggy !!

**Comment by Sahib111** [comment]
Well, all problems require a demo on codepen or jsfiddle.
Anyways, my question is placeholders also works with scrollspy?
Load placeholder on page scroll.
That would be excellent if it does.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by amirsarfar** [comment]
[bootstrap 5 scrollspy problem](https://codepen.io/amirsarfar/pen/QWgGJby?editors=1111)
This is the pen i wrote 
to recreate the situation i am suffering from:
1. scroll to the middle of the page
2. in the console of codepen  run this `window.location.reload()`
after this reload checkout the scrollspy navbar :)
