### ISSUE TITLE
Empty state placeholder illustration

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#34907]
I realize this request is out-of-scope for both Bootstrap and Bootstrap Icons, but I'll request it anyways.

Often you have a application where you have a empty table or a list of cards but there is no data to show. So you're left with an table without any rows in it, or a blank page instead of a list of cards, maybe a paragraph stating there is no data.

Here a placeholder illustration would come in very handy.

Something like when you have no notifications on GitHub:
https://github.githubassets.com/images/modules/notifications/inbox-zero.svg

Here is a Pinterest I found:
https://www.pinterest.com/ritmoniz/empty-states-placeholders/

I would be happy with just one generic illustration, but ideally there could illustrations to to represent collections of different things.

- Empty collection
  - Files & folders
  - Notes
  - Notifications
  - Cards (credit, bank, loyalty, library, access, id)
  - Events (on a calendar)
  - Documents
  - Photos
  - Videos
  - Basket
  - Shopping cart
  - Inbox / mails
  - Search results
- Offline / no internet / disconnected

**Comment by mdo** [comment]
We could perhaps add a new [snippets example](https://getbootstrap.com/docs/5.1/examples/#snippets) if folks want something like it, but I don't see us adding an illustration for this to Bootstrap proper :).

**Comment by vanillajonathan** [comment]
Yeah, a snippet example would be better than nothing.

I don't think this should be added to proper Bootstrap either, because it is out-of-scope, but I think it could be another Bootstrap project, like Bootstrap Icons is a sibling project to Bootstrap so there could be another sibling project called Bootstrap Illustrations.

**Comment by mdo** [comment]
Closing as a won't fix.
