### ISSUE TITLE
Defer in scripts

### ISSUE THREAD

**Issue by Anay-v2** [twbs/bootstrap#34901]
In the bootstrap documentation it says that you need to place the script tag at the end of the body. There is a better looking and more convenient way. It is to use defer. To use defer you can add defer in the script tag like this
<script defer>
what defer does that it doesn't load the script until it has loaded the DOM. I always use defer in my projects and nothing has ever gone wrong. So I just want you to remove the part saying it has to be at the end of the body tag and add defer in your code examples.

**Comment by mdo** [comment]
We mention this in our Optimize docs: https://getbootstrap.com/docs/5.1/customize/optimize/#nonblocking-files.

**Comment by ghusta** [comment]
Correct link is : https://getbootstrap.com/docs/5.1/customize/optimize/#non-blocking-files
