### ISSUE TITLE
Toggle between modals not working 

### ISSUE THREAD

**Issue by josephchesterton** [twbs/bootstrap#34909]
- macOS 11.5.2. Chrome, Firefox 91
- Bootstrap 5.1

When you open a modal, it does not successfully switch to the other modal when toggling between modals.
See example: https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals

Sorry I don't have a solution.

**Comment by adityadees** [comment]
hello I think your issue same as this #34755 please use search box to check your issue.

**Comment by josephchesterton** [comment]
Sorry I obviously didn't search back enough. Its the same as this issue: https://github.com/twbs/bootstrap/issues/34755
