### ISSUE TITLE
Wrong RGB values being created from theme colours

### ISSUE THREAD

**Issue by motifsmedia** [twbs/bootstrap#34919]
Using Bootstrap 5.1.0 on Windows 11 and viewing in Chrome.

I set the `$secondary` variable to `#c4b497` and after it compiles I get the following result from `.bg-secondary`:

```
.bg-secondary {
    --bs-bg-opacity: 1;
    background-color: rgba(var(--bs-secondary-rgb), var(--bs-bg-opacity)) !important;
}
```

That's great and all, but `--bs-secondary-rgb` is not the correct colour.

This is correct `--bs-secondary: #c4b497;`, but this is not `--bs-secondary-rgb: 108, 117, 125;`. 

The RGB value for `#c4b497` should be `196, 180, 151`

**Comment by mdo** [comment]
We'll need more information on your setup. There are a few issues around this right now and most of it seems to be focused around the import order and what not. See https://github.com/twbs/bootstrap/issues/34756#issuecomment-904685333.
