### ISSUE TITLE
Toggle between modals - not working correctly

### ISSUE THREAD

**Issue by kubiqsk** [twbs/bootstrap#34915]
Just compare this:

https://getbootstrap.com/docs/5.0/components/modal/#toggle-between-modals

with this:

https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals

In new version 5.1 first modal will not close - which is wrong

**Comment by mdo** [comment]
Please search first next time, this is fixed and is coming in our next release.

**Comment by kubiqsk** [comment]
sh*t... i always forget to delete these default "is:issue is:open" while searching
