### ISSUE TITLE
Allow styling .input-group-text based on validation state of the related form control

### ISSUE THREAD

**Issue by HunteRoi** [twbs/bootstrap#34917]
I have opened a feature request in **react-bootstrap** and got redirected here. 

In order to give more context to this issue, I will explain it briefly. If you need more details, please take a look at the issue I opened here: react-bootstrap/react-bootstrap/issues/6016. You may as well ask clarification from me if needed!

___

I would like to customize the styles of my `input-group-text` elements based on the validation state of the related form control.

Here is an example:
```html
<div class="input-group has-validation">
  <span class="input-group-text" id="inputGroupPrepend">@</span>
  <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
  <div class="invalid-feedback">
    Please choose a username.
  </div>
</div>
```
The input element is marked as required, which would force the `:invalid` CSS pseudo-class to trigger in case there is no data provided to the input.

**I would like to be able to style the element _above_ the input (currently with the id "inputGroupPrepend") depending on the validation state of the input.**

I tried a few things, but as you say yourself on the website:
[![image](https://user-images.githubusercontent.com/32441291/132390233-32996b5f-b4f5-42d6-b4af-bb73814b10bf.png)](https://getbootstrap.com/docs/5.1/forms/validation/#how-it-works)

Do you have any plan or any idea how I could get the styles I want applied to my span element? Previously, it was possible to style the add-on (bootstrap v3, way back in time, right?):
![image](https://user-images.githubusercontent.com/32441291/132390470-7f3791a8-0dda-48dc-950a-69cc5a481f8c.png)

As of now, I'm stuck with this:
![image](https://user-images.githubusercontent.com/32441291/132390491-b0ece0aa-11d6-42dd-b9fa-1a57539bc74a.png)

**Comment by HunteRoi** [comment]
Just passing by, posting a little 🆙 in hope of getting some attention to this issue 👀

**Comment by mdo** [comment]
You could play with `order` and some other selector adjustments to make such a change happen, but it's too clever of a solution for us to broadly adapt. Until we have something like `:has()` support, our hands are a bit tied I'm afraid.
