### ISSUE TITLE
Cheatsheet unusable

### ISSUE THREAD

**Issue by shakethatweight-simon** [twbs/bootstrap#34916]
Most of the cheatsheet example page is unreadable due to the dark background that has been applied to the `.bg-body` via `--bs-body-rgb` - any lighter colour would be ok. I wasn't able to see any reason why the dark background was intentionally chosen.

![Screenshot 2021-09-07 102513](https://user-images.githubusercontent.com/62300999/132320580-bff2b37a-b996-4e90-890e-2944e5e812a2.png)

**Comment by ffoodd** [comment]
It was not, it's a regression in 5.1. it's already fixed in #34699 and will be delivered in the next release. Thanks for reporting though!
