### ISSUE TITLE
Why does .accordian have overflow-anchor: none;?

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#34929]
If you inspect [bootstrap 4.6 accordian](https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example) you will see the following:  
```

.accordion {
    overflow-anchor: none;
}
```

What's the point of that? Why would you not want `overflow-anchor: auto`? Suppose you got a lot of images in the accordion panel, wouldn't you want the viewport set to the content you are reading, when those pictures load?

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/pull/31347 and https://github.com/twbs/bootstrap/pull/31346
