### ISSUE TITLE
Bootstrap scss files using deprecated "/" for division

### ISSUE THREAD

**Issue by LaurelineP** [twbs/bootstrap#34925]
| Using  |      Version      |
|----------|:-------------:|
| react |  17.0.2 |
| bootstrap |  4.6.0 |
| react-boostrap |   1.6.3  |
| sass | 1.39.0 |
| sass-laoder | 12.1.0 |
| webpack | 5.51.2 |
| node | 14.16.1 |
| npm | 7.21.0 |

**Context / Description**
	  Updating my project by re-installing bootstrap and react-bootstrap;
	  it ended up in the terminal listing plenty of deprecation warnings
	  about how the package bootstrap was handling the division within the
	  scss file at this path node_modules/bootstrap/scss/ for the following files
**Terminal output related to divisions :** 
![image](https://user-images.githubusercontent.com/32878345/132491388-944c69dc-b7a7-4bad-9b10-b27eba65a359.png)

**Solution related to divisions:** 
- [According to Sass any division should be written using "math.div( <dividend> / <diviser> )"](https://sass-lang.com/documentation/breaking-changes/slash-div)
- Can use the autonatic Migration,
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss

---- 
After Doing so, the terminal will complain again and say " WARNING: math.div() will only support number arguments in a future release. "
I guess at this stage, all the variables used within division will need to provide number instead or "list.slash" ?
![image](https://user-images.githubusercontent.com/32878345/132493214-5d2a460e-fdfe-4361-b3ae-afe085b05ffb.png)

**Comment by fchiumeo** [comment]
https://github.com/twbs/bootstrap/search?q=deprecated+division&type=issues

**Comment by ffoodd** [comment]
Fixed in #34571. Thanks for reporting!
