### ISSUE TITLE
Why does bootstrap 4.6 forbid zooming on its carousels?

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#34930]
### Discussed in https://github.com/twbs/bootstrap/discussions/34879

<div type='discussions-op-text'>

<sup>Originally posted by **AnupamKhosla** September  2, 2021</sup>
If you inspect [bootstrap 4.6 carousel](https://getbootstrap.com/docs/4.6/components/carousel/#slides-only) you'll find the following css rule:  

    .carousel.pointer-event {
        -ms-touch-action: pan-y;
        touch-action: pan-y;
    }

What this does is, one it stops zooming touch gesture, two it forbids any default user agent horizontal scrolling behaviour. I assume horizontal scrolling is overridden by javascript to allow sliding of slides with horizontal swiping on touch devices.  

What I don't understand is, why disable zooming on the slides at all? Whats the rationale? Bootstrap 3 didn't forbid zooming, and you can still zoom elsewhere on the page and then scroll to the zoomed-in carousel.</div>

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/pull/27582

Btw, using the blame feature in Git/GitHub is a great way to track down the history of lines of code :).
