### ISSUE TITLE
Switching to CSS Grid should keep container classes

### ISSUE THREAD

**Issue by Sir-Genius** [twbs/bootstrap#34933]
The optional CSS grid introduced in version 5.1.0 does not include container classes. I think that the best solution to this issue is to create a separate option _$enable-containers_ because sometimes developers don't need any kind of grid but need containers.

**Comment by mdo** [comment]
Containers are separate from the flex and CSS grid system, but in looking at it, it is problematic that `$enable-grid-classes` toggles the containers as well. Good point, will revisit.
