### ISSUE TITLE
How to initialize bootstrap 4.6 collapse with javascript?

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#34939]
[Bootstrap 4.6 docs mention](https://getbootstrap.com/docs/4.6/components/collapse/#via-javascript) that we can enable/initialize the collapse menu with eaither `data-` attributes or javascript. I assume `data-target` is still necessary to link a button to the collapsable element. This leaves me with `data-toggle="collapse"`, which I assume further is equivalent of the javascript initilization. So lets try it out:

    $("#demo").collapse() //doesn't work

    $("#demo").collapse({
      toggle: false
    }) //doesn't work either!!

    $("#demo").collapse("toggle"); //doesn't do nothing

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <div class="container-fluid">
      <button id="mybtn" type="button" class="btn btn-primary"  data-target="#demo">Simple collapsible</button>
      <div id="demo" class="collapse">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      </div>
    </div>

As you can see, I am unable to initialize the collapse function through javascript alone. So my question is:  

1. How to enable/initialize bootstrap 4.6 collapse without `data-` attributes, using javascript?  
2. What does passing the options object in the initialization do? Especially what's the difference between passing `{toggle: false}` and `{toggle: true}`? Can I pass `{toggle: "collapse"}`?
----------------------------

P.S: Originally [asked on stackoverflow](https://stackoverflow.com/q/69105972/3429430).   

Please note that I am aware that you can enforce toggle behaviour using jquery click function as:  

```
$('#mybtn').on('click', function() {
  // toggles a collapsible element to shown or hidden
  $('#demo').collapse('toggle');
});
```

This is not the correct explanation.  There's nothing getting activated. When you initialize bootstrap carousel with $('.carousel').carousel(), you don't need to explicitly use $('.carousel').carousel('next'), with a timeout of `5000ms` the carousel just runs automatically like it was initialized with `data-` attributes. Same should be true of the collapse.

**Comment by GeoSot** [comment]
There is a point where you have to choose the functionality you like. 
So Js scripting can handle collapse itself, but not foreign triggers, and data attributes are used to create triggers around the doc.

So you may try the proposed markup, or something like 
```html
<button id="mybtn" type="button" class="btn btn-primary"  onclick="$('#demo').collapse('toggle')">Simple collapsible</button>
``` 

Wish to give you a proper answer here
