### ISSUE TITLE
There is lot of errors in the documentation of Toast (doc V5.1)

### ISSUE THREAD

**Issue by NaturelLaurent** [twbs/bootstrap#34941]
Hello,

#### [https://getbootstrap.com/docs/5.1/components/toasts/](https://getbootstrap.com/docs/5.1/components/toasts/)

```
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <img src="..." class="rounded me-2" alt="...">
```
**< img src="..." class="rounded me-2" alt="...">** 
was incorrect because it's not a image but a svg and 3 dots for the source or alternatif are not correct

every img in this page, must be replace by
`<svg class="bd-placeholder-img rounded me-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#007aff"></rect></svg>`

#### [https://getbootstrap.com/docs/5.1/components/toasts/#live-example](https://getbootstrap.com/docs/5.1/components/toasts/#live-example )
```
var toast = new bootstrap.Toast(toastLiveExample)
toast.show()
```
new bootstrap.Toast() don't give a instance 

#### [https://getbootstrap.com/docs/5.1/components/toasts/#getinstance](https://getbootstrap.com/docs/5.1/components/toasts/#getinstance)
```
var myToastEl = document.getElementById('myToastEl')
var myToast = bootstrap.Toast.getInstance(myToastEl) // Returns a Bootstrap toast instance
```
If you add 
`myToast.show();`
It's doesn't work

**Comment by morrissey-ingenious** [comment]
I think this can be closed I believe @NaturelLaurent  is confused on how the documentation works and how to use the provided examples.

**Comment by GeoSot** [comment]
> every img in this page, must be replace by

maybe you are right on this

>var toast = new bootstrap.Toast(toastLiveExample)
toast.show()
new bootstrap.Toast() don't give a instance

You are mistaken on this, as if you try it, it initializes and returns an instance

>var myToast = bootstrap.Toast.getInstance(myToastEl) // Returns a Bootstrap toast instance
If you add myToast.show(); It's doesn't work

If it is not initialized, it will not do something. You need to initialize it first
