### ISSUE TITLE
Focus first incorrect field when form validation is used

### ISSUE THREAD

**Issue by sumanthratna** [twbs/bootstrap#34943]
# Feature Request

If my form does not fit within ~`100vh` (e.g., https://www.eabsentee.org/form), then if a user submits an invalid form, the page currently does not show the first incorrect field. This leaves the user confused because it looks like the page is just doing nothing when the submit button is clicked. 

# Implementation

perhaps something like this: https://github.com/1000hz/bootstrap-validator/issues/52#issuecomment-71472662

but rather than animating to the right position, I think focusing the field instead could work

**Comment by mdo** [comment]
Thanks for the suggestion, but I think that's outside the scope of the project :).
