### ISSUE TITLE
[Change class name start with "bs-" or something like that]

### ISSUE THREAD

**Issue by letanloc1998** [twbs/bootstrap#34953]
Does any way to change all class name start with `bs-` ? (because some class is duplicate name with other library)
Thanks

**Comment by devhoussam** [comment]
> Does any way to change all class name start with `bs-` ? (because some class is duplicate name with other library)
> Thanks

go to `_variables.scss` and search for `$variable-prefix` you will find `bs-` change it to anything you want

**Comment by Abhi591** [comment]
Hey , can I replace it with vp- ??

**Comment by letanloc1998** [comment]
> > Does any way to change all class name start with `bs-` ? (because some class is duplicate name with other library)
> > Thanks
> 
> go to `_variables.scss` and search for `$variable-prefix` you will find `bs-` change it to anything you want

Thank you a lot.
