### ISSUE TITLE
Button colour is black instead of white if you override the primary colour

### ISSUE THREAD

**Issue by rossm6** [twbs/bootstrap#34955]
I have this custom.scss file -

```
$primary: #1877F2;

@import "../node_modules/bootstrap/scss/bootstrap";
```

A primary coloured button now has colour of black instead of white.

Expected outcome - colour should be white like it is when I remove my primary colour from the scss file.

Ubuntu 20.04 OS
Latest firefox
Bootstrap version is 5.0.0-beta3

**Comment by ffoodd** [comment]
As pointed out, this is not a bug but a feature ensuring sufficient contrasts for accessibility. You may lower the threshold with `$min-contrast-ratio` if that's what you really want.

Be aware that this is used all around out codebase so it might change other values, depending on your color overrides.
