### ISSUE TITLE
Big bug.  myModal.hide() dosen't work.

### ISSUE THREAD

**Issue by farsunset** [twbs/bootstrap#34952]
v5.1
when handle finsh.  call myModal.hide(). but not work.

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by farsunset** [comment]
/*
success
*/
function showDiloag(){
 var dialog = new bootstrap.Modal(document.getElementById('EditDialog'), {
  keyboard: false
 });
dialog.show();
}

/*
 not work
*/
function dismissDiloag(){
 var dialog = new bootstrap.Modal(document.getElementById('EditDialog'), {
  keyboard: false
 });
dialog.hide();
}

**Comment by GeoSot** [comment]
Although you are not including  a live demo, again, I 'll try to give you a tip.

a)  check you console for an error like `Bootstrap doesn't allow more than one instance per element. Bound instance .....`

b) try something like this:

```js 

function getInst( id ){
  return getOrCreateInstance( document.getElementById( id ) , {keyboard: false} )
}

function showDiloag(){
   getInst('EditDialog').show();
}

function dismissDiloag(){
    getInst('EditDialog').hide();
}
```
