### ISSUE TITLE
bootstrap 5 scrollspy misbehaves if you reload on middle of a page (2)

### ISSUE THREAD

**Issue by amirsarfar** [twbs/bootstrap#34958]
I have scrollspy in one of my pages. The scroll element is body.
It works all fine on the first load, but if you reload the page in the middle (scroll and then reload), all scrollspy stuff gets buggy !!

[bootstrap 5 scrollspy problem](https://codepen.io/amirsarfar/pen/QWgGJby?editors=1111)
This is the pen i wrote 
to recreate the situation i am suffering from:
1. scroll to the middle of the page
2. in the console of codepen  run this `window.location.reload()`
after this reload, scroll and checkout the scrollspy navbar :)

**Comment by GeoSot** [comment]
Try to use the https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js script and please confirm if it works correctly

**Comment by amirsarfar** [comment]
Using version 5.1.1 solved the problem. Thanks !

**Comment by amirsarfar** [comment]
Using version 5.1.1 solved the problem. Thanks !
