### ISSUE TITLE
Unexpected focus on number input

### ISSUE THREAD

**Issue by akinuri** [twbs/bootstrap#34962]
When I use a number input element and click/drag (anywhere) below the input element, the element gets focused.

Things that I've noticed so far:

* This seems to happen only with the `number` input.
* Removing the `form-control` class form the element prevents the issue.
* If there's an element after the input element (e.g. `.input-group-append`), this "auto focus" doesn't happen.
* If there are multiple number inputs, only the last one gets focused.
* This seems to happen in Chrome and Opera. Firefox works as expected.

I'm using Windows 10 Pro 64-bit and up-to-date browsers. Here's a [test case](https://output.jsbin.com/xucuzibibo).

Also here's a recording of the issue. I'm clicking and dragging below the input element.

![](https://i.ibb.co/vVBSJwn/2021-09-13-15-15-36.gif)

This is not something that I've noticed recently. I've been ignoring it for at least several months.

What is the cause of this? It doesn't appear to be JS related. Click/drag events were the first thing(s) that I've checked. I had to work my way down from the actual page to a single number input. It seems CSS related, but currently I have no idea why/how it happens.

**Comment by mdo** [comment]
Are you single clicking or double/triple clicking when it gets selected? I'm only able to reproduce this when spamming clicks relatively close to the input, which makes me think it's something related to text selection trigging the field's focus state. Doesn't happen in Safari.

**Comment by akinuri** [comment]
I didn't really examine the clicks, but now that I did, it's as follows:

* If I'm already on the page, I need to triple click to focus.
  * There are some inconsistencies. Sometimes a single or double click is enough.
* If I'm switching back to the page (from other tab or window), a single click is enough.
* Dragging seems to always work.

This behaviour especially annoying when I have multiple cards in the page and the last elements in the cards are number inputs. It's chaos :)

Weird thing is this happens only with the number input. Other type of inputs work as expected.

I hid the spin buttons in the number input thinking it might help, but it didn't.

Could this be a browser related issue? If so, what is the role of `form-control` class here? If I remove it, it doesn't happen.

**Comment by akinuri** [comment]
I took  a look into the rules in the `form-control` class and noticed that the `display: block` rule is causing the issue. I'll be disabling that rule wherever I can to get around the issue.

[Number input with block display](https://jsbin.com/sudugaqica) (JSBin)

**Comment by akinuri** [comment]
I tried to set the number input's `display` back to `inline-block` but that didn't help with inputs in `.input-group`s. [JSBin](https://jsbin.com/nopaxiyego)

This time setting the `.input-group`'s `display` back to `block` fixed the issue. But then there's the issue of sizing. [JSBin](https://jsbin.com/fedisovecu)

These solutions are not good enough. There should be a simpler one. So I decided to give `user-select` a go. 

```
input[type=number].form-control {
    user-select: none;
}
```

This seems to work without side effects so far.

**Comment by mdo** [comment]
Delayed in coming back to this, but I _think_ this makes sense as a browser behavior.

- Double click selects latest word
- Triple click selects all words

This behavior is the same for me on macOS with Safari and Chrome, and it seems to apply to the nearest element as well.

Based on all that, I'm inclined to close as a won't fix.
