### ISSUE TITLE
Build errors with Dart Sass 1.40.0

### ISSUE THREAD

**Issue by boris-petrov** [twbs/bootstrap#34969]
Updating from Dart Sass 1.39.2 to 1.40.0 leads to build errors when building Bootstrap 5:

```
Build Error (PostcssCompiler) in /home/boris/project/node_modules/bootstrap/scss/mixins/_border-radius.scss:9:36

0.2rem and 0 are incompatible.
  ╷
9 │       $return: append($return, max($value, 0));
  │                                    ^^^^^^ 0.2rem
  │                                            ━ 0
  ╵
  node_modules/bootstrap/scss/mixins/_border-radius.scss 9:36                                                           valid-radius()
  node_modules/bootstrap/scss/mixins/_border-radius.scss 20:20                                                          border-radius()
  node_modules/bootstrap/scss/_reboot.scss 322:3                                                                        @import
  node_modules/bootstrap/scss/bootstrap.scss 17:9                                                                       @import
```

There are perhaps more cases of this, I guess this is just the first one.

OS is Linux.

**Comment by jakeparker7** [comment]
+1

**Comment by zinader** [comment]
The if condition doesn't work.

**Comment by PieterBollen87** [comment]
same, any idea how to resolve the issue? (downgrading?)

**Comment by zinader** [comment]
> same, any idea how to resolve the issue? (downgrading?)
> 
> (NVM i should check before asking, :p resolved ;))

@PieterBollen87 how did you solve it?

**Comment by renspr** [comment]
Same here. Downgrading to sass 1.39.2 fixed it.

**Comment by veneliniliev** [comment]
+1

**Comment by b8ne** [comment]
+1 Same issue with Bootstrap v4.  I didn't upgrade anything but build started failing.  Forcing `"sass": "1.39.2"` fixed it.

**Comment by caugner** [comment]
There will be a patch release reverting the backwards incompatiblity soon, see: https://github.com/sass/sass/issues/3142#issuecomment-918923271

**Comment by XhmikosR** [comment]
Yeah not an issue on our side. See the upstream issue.

Pin sass to an older version until a fix is released.
