### ISSUE TITLE
Broken GitHub link in Bootstrap 5.0 Docs

### ISSUE THREAD

**Issue by ManuLFE** [twbs/bootstrap#34976]
Bootstrap documentation on Github linked in the [Boostrap Docs](https://getbootstrap.com/docs/5.0/getting-started/introduction/) send to a 404.
[Dead link](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/getting-started/introduction.md)

Problem seems to come from the deleted /blob directory on the Bootstrap repo.

**Comment by XhmikosR** [comment]
That's normal since the repo structure has changed.
