### ISSUE TITLE
Bootstrap 5 page scrolls smoothly on desktop browsers, but ABRUPTLY jumps to anchor points on iOS

### ISSUE THREAD

**Issue by brad-barnes** [twbs/bootstrap#34975]
Bootstrap 5 appears to have issues smoothly scrolling to anchor points on all iOS browsers that I've tried, including Safari, Chrome, Brave, and Firefox.

The same page scrolls smoothly on all desktop browsers.

Try https://brad-barnes.github.io/portfolio with both iOS and desktop browsers to see the contrast between smooth scrolling and abrupt changing to anchor points pointed to in the navbar.

**Comment by mdo** [comment]
Smooth scrolling is enabled via CSS, and not every browser supports it. When the browser doesn't, you get the jump to effect.
