### ISSUE TITLE
Row inside a container doesn't respect container padding

### ISSUE THREAD

**Issue by surpriseassociate** [twbs/bootstrap#34978]
Operating system: Windows 10 Pro

Browser and version

- Edge Version 93.0.961.47 (Official build) (64-bit)
- Firefox 92.0 (64-bit)

A row inside a container will not respect the containers padding. This can be visible by placing a container containing a row under a container with nothing fancy added to it. Inspecting the elements will show that `.container` applies it's padding, but `.row` negates it. `.col` has the padding applied to it but setting a background color breaks the perceived layout of the page as the background color includes the padded area.

```html
<div class='container'>
  <div class='row'>
    <div class='col'>foo</div>
    <div class='col'>bar</div>
  </div>
</div>
```

In testing for this issue, I noticed that you can get the site to display the way you would expect it to by doing the following:

```html
<div class='container'>
    <div class='row'>
        <div class='col-3'>
            <div class='border'>a</div>
        </div>
        <div class='col-3'>
            <div class='border'>a</div>
        </div>
        <div class='col-3'>
            <div class='border'>a</div>
        </div>
        <div class='col-3'>
            <div class='border'>a</div>
        </div>
    </div>
</div>
```

I dont know if this is intended behavior and I'm just not doing things correctly, but the [example code](https://getbootstrap.com/docs/5.1/layout/grid/#example) doesn't demonstrate the need for the additional nested element.

**Comment by mdo** [comment]
This is how the flexbox grid has worked since v4: https://getbootstrap.com/docs/5.1/layout/grid/#how-it-works.

Our opt-in CSS Grid layout would avoid this and give you what you want, though.
