### ISSUE TITLE
Rename breakpoints infixes based on the  actual breakpoint

### ISSUE THREAD

**Issue by catchmyfame** [twbs/bootstrap#34998]
Tangentially related:

- https://github.com/twbs/bootstrap/pull/8165
- https://github.com/twbs/bootstrap/issues/9868

Over the years, new breakpoints infixes have been added, e.g. `xs`, `xl`, and now `xxl`. Using the current scheme, at some point we'll end up with breakpoint infixes like `xxxs`, `xxxxxl`, etc. Sometimes breakpoint names stay the same but the underlying breakpoints change, as seen in BS4. The issue is that it can be difficult to easily recall what breakpoint designation corresponds to what pixel value, so I'd propose that we add new breakpoint names that correspond directly to their pixel values. 

For example, where we have now:

<html>
<body>

Breakpoint | Class infix | Dimensions
-- | -- | --
X-Small | None | <576px
Small | sm | ≥576px
Medium | md | ≥768px
Large | lg | ≥992px
Extra large | xl | ≥1200px
Extra extra large | xxl | ≥1400px

</body>
</html>

I'd propose:

<html>
<body>

Breakpoint | Class infix | Dimensions
-- | -- | --
X-Small | None | <576px
Small | 576px | ≥576px
Medium | 768px | ≥768px
Large | 992px | ≥992px
Extra large | 1200px | ≥1200px
Extra extra large | 1400px | ≥1400px

</body>
</html>

We'd then be able to use `col-768px-6` versus `col-md-6` which makes it immediately clear what breakpoint the class refers to.

**Comment by mdo** [comment]
Thanks, but we'll leave them as is :).
