### ISSUE TITLE
g-5 class in 5.1.1 creates horizontal scrolling in mobile

### ISSUE THREAD

**Issue by surajgupta59** [twbs/bootstrap#34999]
g-5 class in row creates horizontal scrolling in mobiles

for ex. 
```
<div class="row g-4">
  <div class="col-12 col-md-6">Lorem ipsum dolor sit amet.</div>
  <div class="col-12 col-md-6">Lorem ipsum dolor sit amet.</div>
</div>
```

works fine,  but when I do something like

```
<div class="row g-5">
  <div class="col-12 col-md-6">Lorem ipsum dolor sit amet.</div>
  <div class="col-12 col-md-6">Lorem ipsum dolor sit amet.</div>
</div>
```
it creates horizontal scrolling in mobile.

**Comment by coliff** [comment]
I think that's expected - check the docs - you may need to add a padding utility to the parent container.

https://getbootstrap.com/docs/5.1/layout/gutters/#horizontal-gutters

**Comment by mdo** [comment]
@coliff is correct.

This can be avoided by using the experiment CSS Grid layout option instead, but otherwise, the flexbox layout requires a little bit of work still when modifying gutters :). Wrap it in `<div class="px-5"></div>` and you should be set.
