### ISSUE TITLE
4.6.0 media print with text-white on td/th

### ISSUE THREAD

**Issue by anotherCoward** [twbs/bootstrap#34994]
The `_print.scss` style rule overrides custom classes, even if they are marked as important. 

This applies to any chromium based browser with bootstrap 4.6.0.

The browser and printer won't display the text if background-graphics printing is enabled, due to `color: #fff!important;` of class `text-white` and
```
@media print {
   [...]
    .table {
      border-collapse: collapse !important;
     

/* this causes the issue */
      td,
      th {
        background-color: $white !important; 
      }
    }
   [...]
}
```
of the `_print.scss` and the calculation of the rule priority as declared in https://www.w3.org/TR/CSS2/cascade.html#specificity.

The part mentioned is the only part that forces a white background on elements when printing and it should apply to `tr` not `td/th`. Bootstraps own table-related classes like `.table-striped` modify the `tr` element only. No css rule touches `th/td` explicit except the one above. 😐

Example:
```html
<html><head>
<style>
 .custom {
  background-color: #666!important;
 }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head><body>
<table class="table">
  <thead>
    <tr>
<!-- no text displayed @media print if "w/ background-graphics" is active -->
      <th class="text-white custom">Some text</th>
    </tr>
  </thead>
  <tbody>
    <tr>
<!-- no text displayed @media print if "w/ background-graphics" is active -->
      <td class="text-white bg-dark">Some text</td>
    </tr>
  </tbody>
</table>
</body></html>
```

It's frustrating to add a lot of `more specific custom class-combinations`, bloating the style sheet for no real reason.

**Comment by mdo** [comment]
Yeah, these kind of printing collisions are part of why we dropped print styles in v5. I don't know if we'd make the change here yet, but it could be worth exploring more to see if we can drop some styles.

**Comment by mdo** [comment]
Closing as a won't fix.
