### ISSUE TITLE
text-align: justify

### ISSUE THREAD

**Issue by sean-pwd** [twbs/bootstrap#34993]
It would be great to add the option of justified text. 

Currently this is the scss code:
scss/_utilities.scss

```
"text-align": (
      responsive: true,
      property: text-align,
      class: text,
      values: (
        start: left,
        end: right,
        center: center,
      )
    ),
```
I am happy to handle the PR and docs if the idea is supported. 

currently I have to use
```
 style="text-align: justify;"
```

text-justify would be much easier.'

Can someone have a look at the following link and see if the browser support for start and end fit in with bootstrap targeted browser support?

That would be easier for LTR/RTL support
https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#browser_compatibility

**Comment by ffoodd** [comment]
It use to exist but was removed for accessibility: justified text cannot be made accessible so we don't provide it in our core and don't plan to add it either.

You're still able to add it in your custom build thanks to our utilities API.
