### ISSUE TITLE
something about dropdown-menu on version 3.3.5

### ISSUE THREAD

**Issue by wrh4585** [twbs/bootstrap#34990]
when i use dropdown-menu and click, it would add class name ‘show‘ and some attrs in styles like this

![image](https://user-images.githubusercontent.com/45685551/133458420-5029bd33-7795-452f-8a75-730239bc5c6e.png)

I only want the min-width, but other properties will make the drop-down box display error. Specifically, the li in ul exceeds the ul range and the background color is transparent(The display is visually similar to no background color and is transparent).

I want to know how these inline properties are added to facilitate modification in the project。

chrome 74.0.3729

**Comment by coliff** [comment]
Bootstrap v3 is unsupported but if you must use it then I'd recommend you at least update to the latest version of Bootstrap 3 (v3.4.1) as soon as possible. It fixes a number of bugs including some security issues. 

Those inline styles are added by Bootstrap's JavaScript, I'd suggest you use custom CSS to change the styling of your dropdown box to suit your project.

**Comment by wrh4585** [comment]
> Bootstrap v3 is unsupported but if you must use it then I'd recommend you at least update to the latest version of Bootstrap 3 (v3.4.1) as soon as possible. It fixes a number of bugs including some security issues.
> 
> Those inline styles are added by Bootstrap's JavaScript, I'd suggest you use custom CSS to change the styling of your dropdown box to suit your project.

Thanks!Other modules in my project also use this version. This problem occurs after pulling dependencies again through NPM. Thank you for your suggestion. I tried to use custom CSS style to define, but it will affect other locations. Anyway, thank you for your reply!
