### ISSUE TITLE
Form switch with theme color

### ISSUE THREAD

**Issue by flohw** [twbs/bootstrap#35001]
In our project we took the advantage of `.form-swich` component.
But we would like to be able to be able to customize colors when the subsequent checkbox is checked or not. Not only with the data image/colors variable available but by using `.bg-<theme color name>` classes.

Is it a feature that can be implemented?

I would be happy to create a PR for this but I need some clue how to implement this. I think I can handle this easily with BS4 (the version we use for now) but I am not sure how to proceed with BS5. As BS5 is live for a while now, I think the feature would not be accepted for a previous version, wouldn't it? :wink: 

Thank you

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/pull/35004#issuecomment-1049369949

**Comment by flohw** [comment]
As commented in https://github.com/twbs/bootstrap/pull/35004#issuecomment-1049596991 is it possible to reopen issue and pr or get some feedback? @mdo @GeoSot @ffoodd 

Thank you.
