### ISSUE TITLE
Padding-right and margin-right being added to .card-heard.sticky-top when modal is opened

### ISSUE THREAD

**Issue by Kenshinofkin** [twbs/bootstrap#35006]
When opening a modal, bootstrap is adding padding-right and margin-right to .card-heard.sticky-top elements. Closing the modal removes the padding/margin.

-Windows 10
-Chrome 93.0.4577.82
-https://jsfiddle.net/9768u4wn/1/

**Comment by GeoSot** [comment]
Hello @Kenshinofkin  
Did you find any issue over this?

`padding-right` & `margin-right` is added by intention by ScrollBar.js https://github.com/twbs/bootstrap/blob/60d3eb34f8a1aabe5d2a2308bb841f30cf16c9c4/js/src/util/scrollbar.js#L12

It is being there at least, till v4 and its purpose is to trick the UI and while the scrollbar is hidden, the sticky & fixed elements to remain in the same position.

**Comment by mdo** [comment]
I think in terms of the scrollbar behavior, it should only affect navbars and modals. I don't think it makes sense to unilaterally apply this to the position utilities. Thoughts @ffoodd?

**Comment by ffoodd** [comment]
We need to double check if it's needed, I guess. A CodePen sample might help to compare behaviours across browsers and use cases.

For V6 we'd need to consider `scrollbar-gutter` property (alongside scrollbar customization) to handle this, depending on browser support.

**Comment by mdo** [comment]
Just realized the demo here is for v4, so going to close this out as a won't fix for v4. If the issue still exists in v5, let's get a new issue opened with a new demo. Thanks!
