### ISSUE TITLE
5.1.1 Popperjs SHA-256 integrity

### ISSUE THREAD

**Issue by alexvrv** [twbs/bootstrap#35000]
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js' with computed SHA-256 integrity 'zMDueDFY0as65ZDvjJgqgn446Lgv0SFVHN1MIAQfzRs='. The resource has been blocked.
index.js:52 [WDS] Live Reloading enabled.

And using the bundle script, dropdowns still don't work!
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

Windows 10 21H1 x64, Chrome 93.0.4577.82 (latest), using Bootstrap 5.1.1

**Comment by mdo** [comment]
Doesn't sound like a bug in our code, but something else in your setup.

Also note that if you're using the bundle build of our JS, you don't need to include Popper separately.

**Comment by alexvrv** [comment]
How it is my setup bad if the SHA-256 integrity can't be validated? xD
