### ISSUE TITLE
Importing bootstrap.scss breaks SASS compilation

### ISSUE THREAD

**Issue by heydarm** [twbs/bootstrap#35018]
- Operating system and version: WIndows 10
- Browser and version: Chrome 93
- Suggested fix: Use ```math.max()``` instead of ```max()```.

I have create-react-app project (react-scripts@4.0.3). It works if I do ```npm start```, but not when ```npm run build```.
This error occurs if you're using [Dart SASS](https://www.npmjs.com/package/sass) 1.40.0 and higher.
```
SassError: 0.2rem and 0 are incompatible.
  ╷
9 │       $return: append($return, max($value, 0));
  │                                    ^^^^^^ 0.2rem
  │                                            ━ 0
  ╵
  node_modules\bootstrap\scss\mixins\_border-radius.scss 9:36   valid-radius()
  node_modules\bootstrap\scss\mixins\_border-radius.scss 20:20  border-radius()
  node_modules\bootstrap\scss\_reboot.scss 322:3                @import
  node_modules\bootstrap\scss\bootstrap.scss 17:9               @use
  src\styles\custom.scss 1:1                                    @use
  src\styles\index.scss 1:1                                     root stylesheet
```

**Comment by danielmatthew** [comment]
That error was supposedly resolved in [1.40.1](https://github.com/sass/dart-sass/releases/tag/1.40.1).

However, while that particular error has been resolved, something else within the Bootstrap partials results in a build fail across the following versions – when using CRA. 

- 1.40.1
- 1.41.0
- 1.41.1
- 1.42.0

Dropping Sass back to 1.39.2 means it works again. 

```
> Executing task: yarn run build <

yarn run v1.22.11
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/index.scss
ParserError: Syntax Error at line: 1, column 25
```

```scss
// index.scss
@import "bootstrap/scss/bootstrap";
```

```json
{
  "name": "bootstrap-cra-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "bootstrap": "5.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "devDependencies": {
    "sass": "1.42.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by danielmatthew** [comment]
Were I to delve into `node_modules/bootstrap/bootstrap.scss`, and comment out everything under "Layout & Components", the project builds successfully.

**Comment by danielmatthew** [comment]
Narrowed it down to here:

https://github.com/twbs/bootstrap/blob/60d3eb34f8a1aabe5d2a2308bb841f30cf16c9c4/scss/_grid.scss#L5-L13

**Comment by kris2kris** [comment]
> Narrowed it down to here:
> 
> https://github.com/twbs/bootstrap/blob/60d3eb34f8a1aabe5d2a2308bb841f30cf16c9c4/scss/_grid.scss#L5-L13

Hello,

I have created a ticket in sass (I don't know if it is correct) because I have identified the problem
https://github.com/sass/dart-sass/issues/1496

**Comment by danielmatthew** [comment]
I think what makes this gnarlier to suss out is that a basic set-up compiles with no errors thrown:

```json
{
  "name": "bootstrap-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "npx sass style.scss style.css --load-path=node_modules"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "sass": "1.42.0"
  },
  "dependencies": {
    "bootstrap": "5.1.1"
  }
}
```

```scss
@import "bootstrap/scss/bootstrap";
```

**Comment by heydarm** [comment]
Still researching, but it could be because of [sass-loader that ```create-react-app```](https://github.com/facebook/create-react-app/blob/08dc7ab0f520f680b678556edeb702a5791af20e/packages/react-scripts/package.json#L69) uses

**Comment by heydarm** [comment]
It seems like SASS fixed it in the [latest version (1.42.0)](https://github.com/sass/dart-sass/releases/tag/1.42.0)

**Comment by kris2kris** [comment]
> It seems like SASS fixed it in the [latest version (1.42.0)](https://github.com/sass/dart-sass/releases/tag/1.42.0)
> Checked locally, it really works now

For me it does not work with 1.42.0, 1.39.2 is the last version I can use.

**Comment by bjermeland** [comment]
A temporary fix is to wrap the negative values in parenthesis.

`margin-top: calc(var(--#{$variable-prefix}gutter-y) * (-1)); // stylelint-disable-line function-disallowed-list
  margin-right: calc(var(--#{$variable-prefix}gutter-x) * (-.5)); // stylelint-disable-line function-disallowed-list
  margin-left: calc(var(--#{$variable-prefix}gutter-x) * (-.5)); // stylelint-disable-line function-disallowed-list`

**Comment by Nzamuyejoram** [comment]
@kris2kris  so great . nice for the success

**Comment by baijifeilong** [comment]
Uninstall `sass`, install `node-sass`.

**Comment by kris2kris** [comment]
> Uninstall `sass`, install `node-sass`.

On the GitHub page of node-sass it's written than node-sass is deprecated and to use dart-sass instead

**Comment by XhmikosR** [comment]
This is an issue with postcss-values-parser, see https://github.com/shellscape/postcss-values-parser/issues/138.

We have a #35033 which is supposed to work around the issue.
