### ISSUE TITLE
The data-bs-delay='{"show": 500}' kills the tooltip style

### ISSUE THREAD

**Issue by ereator** [twbs/bootstrap#35020]
Hi,
I have recently updated from Bootstrap 4.6.x to 5.1.1.  for my web-site[ www.uvvo.club](www.uvvo.club) 
When migrating I have changed data-* to data-bs-*, including change `data-delay='{"show": 500}'` to `data-bs-delay='{"show": 500}'` With this line, the appearance of a tooltip is delayed for a half a second, however the style of the tooltip becomes just a grey box with text.
with `data-delay='500'` it works fine, but I want the tooltip to disappear immediately after moving the mouse away. 

OS: Windows 10
Browser: MS Edge
Bootstrap v.5.1.1 is used via via jsDelivr

In the developer tools of the browser I get also:

> jquery.min.js:2 Uncaught TypeError: TOOLTIP: Option "delay" provided type "string" but expected type "(number|object)".
>     at index.js:134
>     at Array.forEach (<anonymous>)
>     at r (index.js:128)
>     at Ye._getConfig (tooltip.js:680)
>     at new Ye (tooltip.js:142)
>     at profile?id=5f22c0c45c2e592e90429dfc:62
>     at Array.map (<anonymous>)
>     at HTMLDocument.<anonymous> (profile?id=5f22c0c45c2e592e90429dfc:61)
>     at e (jquery.min.js:2)
>     at t (jquery.min.js:2)

**Comment by GeoSot** [comment]
I am not sure if is not clear, but data attributes parsing, cannot handle json/object. Only a number value. 
If you need to pass both options, you need to initialize it using javascript

**Comment by ereator** [comment]
At the official page: [https://getbootstrap.com/docs/5.1/components/tooltips/#options](https://getbootstrap.com/docs/5.1/components/tooltips/#options) it is written that `data-bs-delay` may be a number or object (I interpret vertical bar "|" as "or"). The following example is also presented on the page: 
> Object structure is: `delay: { "show": 500, "hide": 100 }`

If I use such object, the style brakes. In version 4.6.x it was working fine, so that's why I think this is a bug.

**Comment by GeoSot** [comment]
It would really help to provide here an example using codepen, where you replicate your problem

**Comment by XhmikosR** [comment]
You need to use a string there, not an object. If you think the docs could be clearer feel free to make a PR and we can discuss it there.

**Comment by ereator** [comment]
All right.
My question then: why it was working in v.4.6 and how to make appearance of the tooltip to be delayed for 500ms ?

**Comment by GeoSot** [comment]
The answer is that was working, cause jquery can handle json string parsing , however wasn't so much safe to do it using vanilla js.
You will make it using a script like the following

```js

const config = {
    delay: {
      show : 500
    }
}
new Tooltip(element, config)
```

**Comment by ereator** [comment]
@GeoSot thank you for the hint. Following your advise, I've added the following code to my layout file:
```
$(function () {
    const config = {
        delay: {
        show : 500
        }
    }                
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl, config)
    });
});
```
which delays all the tooltips on the page and works fine. 
I do not know the best way, how to delay only some of the tooltips and leave other tooltips to appear immediately.

**Comment by GeoSot** [comment]
You may try something custom like a custom markup

```html
<div data-bs-show-delay="500" data-bs-toggle="tooltip"></div>
```

and initialize it like 
```js


    const config = (el) => {
        delay: {
        show : el.getAttribute('data-bs-show-delay')|| 0
        }
    }                
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {

        return new bootstrap.Tooltip(tooltipTriggerEl, config(tooltipTriggerEl))
    });

```


I know it is not the best way, but it will work. Hope I helped you

**Comment by jonnybradley** [comment]
I know there's a comprehensive looking PR (#35077 thanks @GeoSot) to address this regression but i thought i'd make a codepen to demonstrate cleanly, which is here:

https://codepen.io/jonnybradley/pen/yLpqLbP

Note that this worked fine in bootstrap 3 and 4 but presumably then jQuery was doing the JSON parsing for us?

Meanwhile i guess we'll work round it...
