### ISSUE TITLE
Add password change validation to Validation documentation

### ISSUE THREAD

**Issue by TechOverflow** [twbs/bootstrap#35021]
Hi everyone,
There isn't much of a concencus online on how to use Bootstrap validation to compare two new password fields (new password, retype new password).
I think that this type of form is so ubiquitous now that an example should be mentioned in the documentation.

I propose showing a form with three fields - Old Password, New Password, Retype New Password. 
The example could then show how comparison/validation of the New Passwords should be handled.

Thanks for condsidering!

**Comment by ramanjitsingh-hub** [comment]
Hi am I am new to the open-source side of Coding I have heard of Bootstrap a million Times and now I want to contribute to this project , It would be really helpful if you could help me in getting this issue solved and making my first contribution on Github

**Comment by mdo** [comment]
We don't do the validation ourselves, we use the browser's built in validation APIs to tell if a required input is valid or not. It's up to you as a developer using Bootstrap to implement those kind of things.
