### ISSUE TITLE
Popover dynamic content issue on bootstrap 5.1

### ISSUE THREAD

**Issue by Syone** [twbs/bootstrap#35029]
There is a regression between v5.0.x => https://codepen.io/syone7/pen/xxrjoWP

And v5.1.x => https://codepen.io/syone7/pen/eYRraxY

On the example 2 and 3, the popover content is supposed to be updated everytime you close and reopen the popover

**Comment by XhmikosR** [comment]
@GeoSot have you checked this issue?

**Comment by blaskognia** [comment]
Still not working in version 5.1.3 :( this very bad

**Comment by PavloParafiloCricut** [comment]
Hope this will be fixed/improved

Tried different options even with touching _popper internals, but only setTimeout(100+) works (because of that "deffers" inside popper.js?).

As a workaround can try this
```
const popover = bootstrap.Popover.getInstance(element);
popover.tip.querySelectorAll(".popover-body")[0].innerHTML = contentElement.innerHTML;
popover.update();
```
