### ISSUE TITLE
Bootstrap 5 throws "Object reference not set to an instance of an object" error.

### ISSUE THREAD

**Issue by vinaybaros** [twbs/bootstrap#35031]
Bootstrap 5 throws "Object reference not set to an instance of an object" error. 
Whereas its working fine the older versions.

Working in:
Microsoft Visual Studio Professional 2019
Version 16.11.3
Microsoft .NET Framework
Version 4.8.04084

**Comment by vinaybaros** [comment]
{
      "outputFileName": "wwwroot/js/site.min.js",
      "inputFiles": [
        "wwwroot/lib/tether/latest/tether.min.js",
        "wwwroot/lib/bootstrap5.0.2/js/bootstrap.min.js",
      ],
      "minify": {
            "enabled": true,
            "renameLocals": true
      }
}

**Comment by vinaybaros** [comment]
Using jQuery  v3.6.0

**Comment by GeoSot** [comment]
@vinaybaros Please take it form the beginning, and try to be more descriptive. An example would help too

**Comment by mdo** [comment]
Closing until we get a test case and more details.
