### ISSUE TITLE
Slash as division will be removed by Dart Sass and shows now depraction warning during compiling Bootstrap 4 SCSS

### ISSUE THREAD

**Issue by medarob** [twbs/bootstrap#35037]
We updated to Dart Sass 1.42 recently and got many deprecation warnings in Bootstrap 4.

**For example:**
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```
    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    ../var/www/staging/packages/my_global/Resources/Public/Plugins/bootstrap4/scss/_variables.scss 302:31  @import

```

There is a new math.div() function which should be used, maybe Bootstrap4 can be adapted in the next 4.6.1 release or so, to use this function?

**Comment by seyoon20087** [comment]
Please see #34353

**Comment by medarob** [comment]
ah cool, thank you for the hint. I will close this issue then.
