### ISSUE TITLE
Hiding elements in Breakpoints

### ISSUE THREAD

**Issue by ferhado** [twbs/bootstrap#35035]
Currently to hide an Element on mobile we should use for example: 

`.d-none .d-md-block`

In this situation we must override the original display and rewrite it again.

### Solution:
I suggest to use instead of it this way: `.d--md-none ` with double dashes, this class should hide the element when screen is smaller than Medium, so we don't need to override the original display and rewrite it again

Here is an example on Codepen: https://codepen.io/ferhado/pen/KKqeQGb

**Comment by yurj** [comment]
https://getbootstrap.com/docs/5.1/layout/breakpoints/#max-width

https://getbootstrap.com/docs/5.1/utilities/api/#responsive

https://github.com/twbs/bootstrap/blob/main/scss/utilities/_api.scss

https://github.com/twbs/bootstrap/blob/main/scss/mixins/_breakpoints.scss#L48

this are useful pointers to implement them.

**Comment by mdo** [comment]
We'll skip on doing this ourselves—we decided long ago to keep these classes simpler and not over every variation on them for file size.
