### ISSUE TITLE
Bootstrap 5 Toggle between modals not working when .fade present

### ISSUE THREAD

**Issue by realtydev** [twbs/bootstrap#35034]
Toggling between modals will not work when the animation class .fade is present in the html

https://getbootstrap.com/docs/5.0/components/modal/#toggle-between-modals

with fade: https://codepen.io/alexgibson/pen/QWgxdRy

without fade (not working): https://codepen.io/alexgibson/pen/GREGrbL

**Comment by GeoSot** [comment]
Hello @realtydev .
Try to replace `data-bs-dismiss` with ` data-bs-toggle`. I think you will be fine.

**Comment by realtydev** [comment]
that fixed it thanks! perhaps docs need to be updated to this or maybe i just seeing older doc version

**Comment by GeoSot** [comment]
It is written properly on [5.1](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals) docs. that was changed. So I think we are fine for now :smiley:

**Comment by realtydev** [comment]
looks like it was only fixed for the return to first modal button (which is on the second modal) in the documentation but not the open second modal button

`<button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Open second modal</button>`
