### ISSUE TITLE
Bootstrap 5 Sass-variable $tooltip-margin not clear or not working

### ISSUE THREAD

**Issue by prietveld** [twbs/bootstrap#35039]
When setting the V5 Sass-variable $tooltip-margin to anything but it's default 0 there seems to be no discernable effect on actual tooltips. Forcing the value by adding !important results in an offset in both x and y directions, which would be of little practical use (though noted that !important could have overriden other definitions down the line in this case).

If this behavior was replaced by the JS offset option, which is how I interpreted it, this variable should probably be removed. But feel free to close / remove this issue if this is simply lack of understanding of it's intended use.

See [this Pen](https://codepen.io/PatrickKennisnet/pen/KKqBPZB) for simulated use of the variable.

Confirmed in Chrome, Edge, Firefox on Windows 10.

**Comment by GeoSot** [comment]
@prietveld  you are very right on this. It is a left over that will be fixed soon by #34627
