### ISSUE TITLE
scss flag to disable generation of btn-outline classes

### ISSUE THREAD

**Issue by meriturva** [twbs/bootstrap#35040]
I would like to have a flag like `$enable-btn-outline` to disable the generation of `btn-outline` classes.
Another approach could be to separate `button.scss` file so the developer could decide which kind of button to import.

**Comment by XhmikosR** [comment]
@twbs/css-review is this something we plan to do?

**Comment by ffoodd** [comment]
As far as I know, no. As for other components, the recommended way to drop some of them is to make a custom Sass build (eg. not importing some partials before compiling). If you're able to change a variable, you're able to override a few partials—so the need for this is (IMHO) very low.

**Comment by meriturva** [comment]
Thanks @ffoodd so basically I have to duplicate all _button.scss content on my custom build removing 5 lines of code here:

https://github.com/twbs/bootstrap/blob/main/scss/_buttons.scss#L65

right?

**Comment by ffoodd** [comment]
Indeed, that's what I recommend for now.

You may also use a tool like PurgeCSS to remove unused CSS based on your templates. That'd also drop other unused CSS, which is interesting— and it processes your compiled CSS, which may avoid you to differ from our sources (thus simplify updating your Bootstrap sources).

**Comment by meriturva** [comment]
Actually, PurgeCSS is not usable for us due to the fact that we are building our internal theme based on bootstrap.
So for maintaining purposes, we would like to reduce our SCSS customizations in favor of SCSS variables/mixin/CSS custom variables.
