### ISSUE TITLE
Bootstrap 5.1.0 tooltip not refreshing

### ISSUE THREAD

**Issue by lopey66** [twbs/bootstrap#35043]
Using 5.1.0 when I tried to update the title/tooltip, it would updated on loading the page, though afterwards when I updated the title 

found this site https://stackoverflow.com/questions/67247233/how-does-the-text-of-the-tooltip-change-when-the-button-is-clicked

I ran their example and noticed 5.0.0-beta3 when I re ran the example with version 5.1.0 it did not update.

source tested https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js
source tested https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js

**Comment by GeoSot** [comment]
Hello @lopey66 , you can refer to #34842 for details. Note down that it is working for 5.1.1 but it is a trick we are not include in BS documentation, and probably is going to be eliminated in favor of a more official way
