### ISSUE TITLE
Add a feature To access color by using hex code of the color

### ISSUE THREAD

**Issue by Aditya-Narayan-Nayak** [twbs/bootstrap#35044]
1. The problem arises where we can only use limited text color/background
    So if you add color by using hex code that will help to add more color 
    for ex, if I want text color white then I can add like this

class=" text-#ffffff "
        or 
<h1 class = " text-#ffffff" >My heading</h1>
         or
<p class = " text-#ff9f00" >My Paragraph<p>

**Comment by tanboyupoints** [comment]
just a test

**Comment by mdo** [comment]
Thanks, but we'll pass on this.
