### ISSUE TITLE
Carousel inner div is not identified by the carousel-inner class

### ISSUE THREAD

**Issue by ETVO** [twbs/bootstrap#35057]
Hello. 

I have been using Bootstrap for a while now. Recently I designed a multiple item carousel, with each carousel-item containing two images. And it works just fine.

It worked quite well in my ```xl``` viewport (>=1200px). I realized, however, that the carousel would require some work to be fully responsive. As my goal is displaying the images clearly, I need to show only one image per item once the user is in a viewport smaller than the ```lg``` breakpoint (<992px). 

I'll admit my idea to solve this was not necessarily the most "render-effective", but I expected it to work. 
My approach was rendering the carousel-inner two times: one for the viewports greater than ```lg``` and another for the rest. 

So the code looks a bit like this:
```html
<div class="carousel">
    <div class="carousel-inner d-none d-lg-block">
        <!-- first carousel-items here -->
    </div>

    <div class="carousel-inner d-block d-lg-none">
        <!-- second carousel-items here -->
    </div> 

    <!-- carousel-controls here -->
</div>
```

The problem I'm facing is that the controls fail to move the carousel items once we get to the other viewport. The controls seem to be associated with the first ```.carousel-inner``` div. Which would be totally fine and reasonable, if it stopped there.

So I made a test: I tried removing the ```carousel-inner``` class from the first div, leaving it only with the ```d-none d-lg-block``` classes. 
It is not shown to the user **(which is what I want)**, but the controls are still moving its items instead of the div that actually has the ```carousel-inner``` class.

So, even if I do this:
```html
<div class="carousel">
    <div class="not-a-carousel-inner">
        <!-- first carousel-items here -->
    </div>

    <div class="carousel-inner d-block d-lg-none">
        <!-- second carousel-items here -->
    </div> 

    <!-- carousel-controls here -->
</div>
```

If you use the <  > controls, Bootstrap will move the items inside of the ```not-a-carousel-inner```, even though it is not identified as a carousel inner.

This doesn't seem like a problem if you want to do a normal carousel, but in my case I see no alternative other than running a JS script to manually remove the first div once we get to another viewport. Just changing its class is not enough.

You can check this out in [this CodePen](https://codepen.io/ETVO/pen/XWgodbN) I made. The div identified as ```.carousel-inner``` is styled correctly, but the one that Bootstrap controls and moves is the first div.

The issue is: if the ```carousel-inner``` class does not have the priority when the ```carousel-controls``` are used, then why even bother having a class, other than for styling. I'm still having a hard time understanding how Bootstrap manages to move the right carousel-items when they aren't even wrapped by a identifiable div. Unless it is just doing something like 
```javascript
$('.carousel').find('div').get(0).find('.carousel-item')...
```

Thank you very much!!!

**Comment by GeoSot** [comment]
Maybe you can experiment, on a branch and with a MR, tweaking `carousel.js`. 
I suspect, that your problem is hiding somewhere there
https://github.com/twbs/bootstrap/blob/b991a6b8510216ba25cff02e0cc6c338f9f76113/js/src/carousel.js#L278-L282

Where the selectorEngine searches `.carousel-item` inside `.carousel` 😉

**Comment by mdo** [comment]
Closing this as stale and a won't fix since we haven't heard anything back.
