### ISSUE TITLE
Too light button

### ISSUE THREAD

**Issue by KES777** [twbs/bootstrap#35050]
![image](https://user-images.githubusercontent.com/799021/134727680-f67d40c6-9111-4562-bd57-8c626a5f50a7.png)

Bug reports must include:

- Linux Mint v19.3
- FF v90.0.2
- https://getbootstrap.com/docs/5.0/components/buttons/#outline-buttons

**Comment by Paper-Folding** [comment]
Hey, I was once thinking about this issue, too, but I figured out that if you use that button in dark theme, it'll be just amazing.

**Comment by AB-Jeet** [comment]
May I work on this issue ??

**Comment by coliff** [comment]
@KES777 - your screenshot is from v4 docs, but the link you posted was to v5 docs. It states in a call-out box:

> Some of the button styles use a relatively light foreground color, and should only be used on a dark background in order to have sufficient contrast.

So I don’t think this is a bug/issue that needs to be addressed. As @Paper-Folding suggests, the ban-outline-light would be suitable for use on a dark theme/background.

**Comment by coliff** [comment]
It's up to you how you use the components and everything is customizable so you are best to adapt the colors to suit your project.
