### ISSUE TITLE
Please use show on visible elements 

### ISSUE THREAD

**Issue by philiprbrenan** [twbs/bootstrap#35083]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am getting the message: "Please use show on visible elements". Please tell me how to avoid this error?

Referrer: Runtime: 276.638 Position: https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js:6:37848 
Error: **Uncaught Error: Please use show on visible elements** Stack: Error: Please use show on visible elements at i.t.show (https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js:6:37854) at i.t._fixTransition (https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js:6:44714) at HTMLDivElement.c (https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js:6:39256) at HTMLDivElement.i (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:39362) at HTMLDivElement.handle (https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js:6:2723) at HTMLDivElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:41772) at HTMLDivElement.y.handle (https://ajax.googleapis.com/ajax/li bs/jquery/3.3.1/jquery.min.js:2:39791)

### Reduced test cases

I do not know of any proposed fixes.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

4.3.1

**Comment by GeoSot** [comment]
Hello @philiprbrenan 

For start you can create a codepen **example**, following the issue template suggestion, and you may also use the not minified versions, to make it easier to follow.


A quick thought is that you are trying to show a `hidden` tab
