### ISSUE TITLE
remove the "list-group-item" class in <li> tags

### ISSUE THREAD

**Issue by Delve-Delos-Santos** [twbs/bootstrap#35081]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I hate this feature, because it gives my work. harder. please instead of using
```css
.list-group-item {
  ...
}
```
please use
```css
.list-group > li {
  ...
}
```
so we can save much time, thanks!

### Motivation and context

it's help a lot, like you don't need to add a class manually.

**Comment by Kopyov** [comment]
That would significantly limit possibilities of list group. With class names you can use list group with any tag - li, div, span etc. You can also use list group item separately with no relation to direct parent

**Comment by mdo** [comment]
No changes happening here—we use classes to avoid requiring specific HTML whenever possible.
