### ISSUE TITLE
Validation styling for .form-range

### ISSUE THREAD

**Issue by jrd-lewis** [twbs/bootstrap#35088]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently in Bootstrap 5.1.1, there is no ```.is-invalid``` or ```.is-valid``` styling for the ```.form-range``` class. It was previously brought up in #27354 a few years ago, but nothing came of it. Ideally, at least the range's dot would be color matched to the validation colors for the other Bootstrap form classes.

Demo:
https://codepen.io/jslewis90/pen/PojLroV

### Motivation and context

It would be nice to provide some visual indication of a ```.form-range``` input either being given ```.is-valid``` or ```.is-invalid``` classes.

While I understand the concept that range inputs should always be valid, there is a chance that a user could bypass the valid values before submitting a form which would then be caught during validation.

**Comment by mdo** [comment]
As I understand it, there will never be a valid or invalid state of a range input. https://stackoverflow.com/questions/52036229/is-there-invalid-state-of-input-range/52036796

**Comment by ffoodd** [comment]
You may use [`:out-of-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range) to trigger this specific invalidation case, however. We don't handle it — should we? —, but you may try it by yourself.

**Comment by mdo** [comment]
Does it only get out of range if programmatically altered? I'm not sure how or why that'd come up in a form. 🤔 If there's a valid use case I'm down to reconsider.

**Comment by ffoodd** [comment]
TBH I don't think there's a valid use case. AFAIK it's only programmatic (just like the `:indeterminate` pseudo-class on checkboxes).
