### ISSUE TITLE
Breakpoints for button sizes

### ISSUE THREAD

**Issue by seanvandermolen** [twbs/bootstrap#35087]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add breakpoints to button sizes
.btn.-{breakpoint}-{value}

example: btn-md-sm btn-lg-lg

### Motivation and context

Have a case where I have a DIV with a section title, then a bar fills the page with a button at the end.  The button size and padding is setting the height of that bar while the Title using display typography is setting the size of it's container which is slightly larger.  

That display value is smaller on smaller breakpoints, but the button is too large and the concept is lost as now the bar height is taller than the title container.

There are solutions of course, conceptually it seems like this would be useful.

**Comment by Allmedialab** [comment]
Always wondered why this feature is missing!

**Comment by mdo** [comment]
For the time being, I think font-size and padding utilities accomplish this.
