### ISSUE TITLE
Custom values not getting added through map-merge() in Bootstrap 5

### ISSUE THREAD

**Issue by vedPrakashGit** [twbs/bootstrap#35096]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am using the following codes in style.scss file:-

-------------------------------------------------------
@import "../node_modules/bootstrap/scss/_functions";
@import "../node_modules/bootstrap/scss/_variables";

$custom-theme-colors: (
    "altlight": red,
    "altdark": green
);

$theme-colors: map-merge($theme-colors, $custom-theme-colors);
@import "../node_modules/bootstrap/scss/bootstrap";

----------------------------------------------------------------------

When I use the "bg-altlight" class in my html file, I can't see the this class added to the compiled css file. What can be the reason. Am I using it in a wrong manner?

![Screenshot 2021-10-03 at 3 20 33 PM](https://user-images.githubusercontent.com/91825651/135748563-c6e29b82-4b12-4a63-8199-6a43bba2ecc3.png)

### Reduced test cases

I have no reduced test cases for this.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

5.1.1

**Comment by yurj** [comment]
It is not a bug but it is not documented. You should do:
```

$custom-theme-colors: (
"altlight": red,
"altdark": green
);

// Merge the maps
@import "bootstrap/scss/functions"; // Required
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

$theme-colors: map-merge($theme-colors, $custom-colors);
$theme-colors: map-merge($theme-colors, $colors);
$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
$utilities-colors: map-merge($utilities-colors, $theme-colors-rgb);
$utilities-text-colors: map-loop($utilities-colors, rgba-css-var, "$key", "text");
$utilities-bg-colors: map-loop($utilities-colors, rgba-css-var, "$key", "bg");

// other imports below
```

**Comment by vedPrakashGit** [comment]
> It is not a bug but it is not documented. You should do:
> 
> ```
> 
> $custom-theme-colors: (
> "altlight": red,
> "altdark": green
> );
> 
> // Merge the maps
> @import "bootstrap/scss/functions"; // Required
> @import "bootstrap/scss/variables";
> @import "bootstrap/scss/mixins";
> 
> $theme-colors: map-merge($theme-colors, $custom-colors);
> $theme-colors: map-merge($theme-colors, $colors);
> $theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
> $utilities-colors: map-merge($utilities-colors, $theme-colors-rgb);
> $utilities-text-colors: map-loop($utilities-colors, rgba-css-var, "$key", "text");
> $utilities-bg-colors: map-loop($utilities-colors, rgba-css-var, "$key", "bg");
> 
> // other imports below
> ```

Thank you @yurj, it works!
