### ISSUE TITLE
Bootstrap 4.0 CSS issues

### ISSUE THREAD

**Issue by zamzurihanizan** [twbs/bootstrap#35092]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi BS Team and Community. 
I am here to query regarding the issues that I'm facing with Bootstrap 4.0 in my previous website that I developed for my FYP. The CSS is not as it was when I'm using latest browser (Chrome on Windows, Safari on Mac). However, in my MS Edge browser, the CSS is working. Please help.  As attached, you can see the differences of the website in two different browser. you may browse to https://bcgtalenthub.thekzs.com and check out if you have the latest browser. 

![244202607_4727507477299748_7672671296094694008_n](https://user-images.githubusercontent.com/90409113/135645435-b7f16f18-e3a2-4164-98b5-87f27ee8791a.jpg)

![243376122_4727510073966155_3293440867139569922_n](https://user-images.githubusercontent.com/90409113/135645420-258a1f72-0e3b-4497-892e-a35adee3d8da.jpg)

### Reduced test cases

https://bcgtalenthub.thekzs.com

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v4.5.2

**Comment by XhmikosR** [comment]
Sorry, that seems unrelated to Bootstrap.
