### ISSUE TITLE
Input group escaping to new line on validating

### ISSUE THREAD

**Issue by LocalHeroPro** [twbs/bootstrap#35106]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When validate input, green checkbox is showing and button from input group step to second line.
Before validation:
![image](https://user-images.githubusercontent.com/42643563/135925503-a3ec5598-262b-4cad-84ee-4df80263ebd4.png)

After validation:
![image](https://user-images.githubusercontent.com/42643563/135925455-5e78042c-8081-4032-80fa-7372951294cd.png)

### Reduced test cases
```
<dl id="order-addresses-1" class="row cpt-dl">
  <dt class="col-sm-4"><label for="order-billing-tin">TIN</label></dt>
  <dd class="col-sm-8">
    <div class="input-group mb-3">
      <input id="order-billing-tin" type="text" class="form-control form-control-sm" aria-describedby="tin-addon" name="order_addresses[1][tin]" value="23452222">
      <button id="tin-addon" class="btn btn-sm btn-outline-secondary" type="button" data-bs-toggle="tooltip" title="Some action txt">icon</button>
    </div>
  </dd>
</dl>
```
### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Opera

### What version of Bootstrap are you using?

5.1.1

**Comment by mdo** [comment]
Closing as we don't explicitly support Opera and I haven't seen a reproducible live demo here to check elsewhere.
