### ISSUE TITLE
RTL-SCSS

### ISSUE THREAD

**Issue by tayebehsafdari** [twbs/bootstrap#35100]
Hi,
How can I use the right-to-left feature on my scss and webpack (Uncompiled version)?

**Comment by ffoodd** [comment]
You can't from our sources, since the RTL version is postprocessed from our CSS dist files using RTLCSS.

If you need RTL, you'd have to work with our LTR sources and postprocess the output by yourself, using RTLCSS in your build chain.

**Comment by tayebehsafdari** [comment]
Thanks alot :)

**Comment by mshima** [comment]
I could not find how to implement this nowhere so for future visitors, we are testing https://www.npmjs.com/package/postcss-rtlcss.
Our use case is simple, and we need the combined approach.
Simple as:
```
const postcss = require('postcss');
...
rules: [
    {
        test: /\.css$/,
        use: [
            { loader: 'style-loader' },
            { loader: 'css-loader' },
            {
                loader: 'postcss-loader',
                options: {
                    postcssOptions: {
                        plugins: [
                            postcssRTLCSS()
                        ]
                    }
                }
            }
        ]
    }
]
```

**Comment by HasanMothaffar** [comment]
It would be deeply appreciated if you could explicitly indicate that one cannot use RTL features of uncompiled Bootstrap files without postprocessing the CSS output on one's own. I thought there was a SASS variable that enabled this feature, but after hours of searching I came across this issue on Github and things started to become clear.

Perhaps providing a sample Webpack config file, like the one @mshima provided, might clear things up a bit.

**Comment by ffoodd** [comment]
This is mentionned in [the RTL docs page](https://getbootstrap.com/docs/5.1/getting-started/rtl/). This is how RTLCSS works, and looking at Bootstrap's `package.json` could have been clearer.

We may try to make it more obvious, since a few people seems to struggle a bit with this process.
