### ISSUE TITLE
Can bootstrap 4 add placeholders?

### ISSUE THREAD

**Issue by bbhxwl** [twbs/bootstrap#35121]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can bootstrap 4 add placeholders?

The cost of upgrading from 4 to 5 seems relatively high. But 4 there is no placeholder function.

### Motivation and context

The cost of upgrading from 4 to 5 seems relatively high. But 4 there is no placeholder function.

**Comment by mdo** [comment]
Not against doing it, it's been a goal to continue to bridge the gap. If you want to take a stab at it, we'd love to review a PR! Otherwise it's as time allows for us as maintainers :).
