### ISSUE TITLE
New `align-self: center` default for btn class causes regression in vertical button stacks inside flex containers

### ISSUE THREAD

**Issue by andreas-venturini** [twbs/bootstrap#35126]
Consider the following snippet (slightly modified example from https://github.com/twbs/bootstrap/pull/34834#issue-981860825)

```html
<div class="d-flex flex-column">
  <button type="button" class="m-2 btn btn-primary">Default</button>
  <button type="button" class="m-2 btn btn-primary btn-sm">Small</button>
  <button type="button" class="m-2 btn btn-primary btn-md">Medium</button>
  <button type="button" class="m-2 btn btn-primary btn-lg">Large</button>
</div>
```
Bootstrap 5.1.1 produces the following output:

![image](https://user-images.githubusercontent.com/4801917/136264069-c6053b69-8e13-4bfb-bc36-1ce19859bc8d.png)

With Bootstrap 5.1.2 and `align-self: center` this results in the following:

![bs_5 1 2](https://user-images.githubusercontent.com/4801917/136263983-eedd3ede-34fe-41e8-a57f-ad5cd2ee4a51.png)

**Comment by XhmikosR** [comment]
We reverted the offending patch in #35143 and we'll release 5.1.3 later today.

**Comment by XhmikosR** [comment]
[v5.1.3](https://github.com/twbs/bootstrap/releases/tag/v5.1.3) is out 🙂
