### ISSUE TITLE
Horizontal collapse bounce inside flex element

### ISSUE THREAD

**Issue by frosadev** [twbs/bootstrap#35131]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

I'm trying to use the horizontal collapse component but it bounces when inside a flex div.
This is the Html that I have:

```
<button type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-collapse" aria-expanded="true" aria-controls="sidebar">toggle</button>

<div id="app">
    <div class="d-flex flex-row">
        <div class="collapse collapse-horizontal show" id="sidebar-collapse">
            <div class="vh-100" style="min-width: 300px; width: 300px;">
                <div>Some Sidemenu</div>
            </div>
        </div>

        <div class="container-fluid bg-light vh-100 p-0">
            <div id="content-wrapper" class="h-100 w-100 p-3">
                <div class="row">
                    <div class="col">
                        <p>test content</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

Am I doing something wrong or is it a bug here?
Thanks in advance.

### Reduced test cases

```
<button type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-collapse" aria-expanded="true" aria-controls="sidebar">toggle</button>

<div id="app">
    <div class="d-flex flex-row">
        <div class="collapse collapse-horizontal show" id="sidebar-collapse">
            <div class="vh-100" style="min-width: 300px; width: 300px;">
                <div>Some Sidemenu</div>
            </div>
        </div>

        <div class="container-fluid bg-light vh-100 p-0">
            <div id="content-wrapper" class="h-100 w-100 p-3">
                <div class="row">
                    <div class="col">
                        <p>test content</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.1 (latest from the examples)

**Comment by frosadev** [comment]
Managed to solve this out.
The problem was the container-fluid there.
Replaced it with d-flex flex-grow-1 and it solve it.

;)

**Comment by uzungil** [comment]
<button type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-collapse" aria-expanded="true" aria-controls="sidebar">toggle</button>

<div id="app">
    <div class="d-flex flex-row">
        <div class="collapse collapse-horizontal show" id="sidebar-collapse">
            <div class="vh-100" style="min-width: 300px; width: 300px;">
                <div>Some Sidemenu</div>
            </div>
        </div>

        <div class="container-fluid bg-light vh-100 p-0">
            <div id="content-wrapper" class="h-100 w-100 p-3">
                <div class="row">
                    <div class="col">
                        <p>test content</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
