### ISSUE TITLE
Optimize section

### ISSUE THREAD

**Issue by Mannuel25** [twbs/bootstrap#35140]
![IMG_20211008_092415](https://user-images.githubusercontent.com/68563757/136524389-846d83af-dc67-4252-9b5a-0be87e821f8f.jpg)

I'd like to make a contribution in the Unused CSS section, but I want to be cleared on what help is needed. If it's an article or blog post to be added or something else. 

Thanks.

**Comment by mdo** [comment]
Closing as stale. Happy to see any PRs still!
