### ISSUE TITLE
Table striped row color setting for included elements - Bootstrap version 5.1.1 vs. 5.1.3

### ISSUE THREAD

**Issue by ZeEmEs** [twbs/bootstrap#35158]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Up to version 5.1.1 it was this in the stylesheet

`.table-striped > tbody > tr:nth-of-type(odd) {
  --bs-table-accent-bg: var(--bs-table-striped-bg);
  color: var(--bs-table-striped-color);
}`

from 5.1.2 on it is

`.table-striped > tbody > tr:nth-of-type(odd) > * {
  --bs-table-accent-bg: var(--bs-table-striped-bg);
  color: var(--bs-table-striped-color);
}`

Now all child elements get a color. Often enough this color setting overrides the one given to the element.
Is there a special reason for the change?
Now it's more difficult setting ones own colors for the elements in a table row. And Bootstrap is more opinionated in regard to the color setting in table row.

Btw. same applies to the setting for the `.table-hover > tbody > tr:hover` vs. `.table-hover > tbody > tr:hover > *`

### Reduced test cases

see description

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.1.1 vs. 5.1.3

**Comment by maciek-szn** [comment]
#34799 seems to be a breaking change.

**Comment by dippas** [comment]
This was discussed here - https://stackoverflow.com/questions/72757301/applying-text-success-to-a-bootstrap-5-table-row-that-is-striped-has-no-effect/72757379

**Comment by G2G2G2G** [comment]
@dippas thanks for linking a stackoverflow that links to this thread...
