### ISSUE TITLE
Separator for table direct children @5.1.2

### ISSUE THREAD

**Issue by PerseusTheGreat** [twbs/bootstrap#35152]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi.
After updating to 5.1.2, in tables that have `<colgroup>` before `<thead>`, a border appears above `<thead>`.
I think the new added rule (#34861) needs to be extended.

### Reduced test cases

Current situation:
https://codepen.io/laylazi/pen/MWvWjaM

My proposal:
https://codepen.io/laylazi/pen/dyzypQd

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.1.2

**Comment by danielmatthew** [comment]
If a `<caption>` is included too, this causes the `<thead>`'s top border to render, as `.table>:not(:first-child)` matches. 

See reproduction: https://codepen.io/danielmatthew/pen/zYdROzJ

**Comment by ffoodd** [comment]
Yup, that's covered by the latest linked PR.

**Comment by mbrodala** [comment]
Since the link is very easy to miss: #35200

**Comment by mdo** [comment]
Resolved through #35908.
