### ISSUE TITLE
The DIV drop down  within <nav> not working

### ISSUE THREAD

**Issue by Awakenedcoder001** [twbs/bootstrap#35166]
<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="https://readmanganato.com/manga-if985362/chapter-85" target="_blank">Manga</a>
                  <a class="dropdown-item" href="https://getbootstrap.com/docs/5.1/components/navbar/" target="_blank">Bootstrap</a>
                  <a class="dropdown-item" href="https://novelfull.com/the-tutorial-is-too-hard/chapter-47.html" target="_blank">Light Novel</a>
             </div>
![image](https://user-images.githubusercontent.com/92351601/136889534-45a218eb-f8fc-4db1-9ae9-ae66996ac32a.png)

![image](https://user-images.githubusercontent.com/92351601/136889554-58900209-ae1c-439b-b9bf-bf8a7d320520.png)

**Comment by ffoodd** [comment]
I suppose this duplicates #35169. Please  use our JavaScript and read the [Getting starter](https://getbootstrap.com/docs/4.6/getting-started/introduction/) page.
