### ISSUE TITLE
Using COLGROUP in a table results in unexpected top border

### ISSUE THREAD

**Issue by ramzypro** [twbs/bootstrap#35162]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Use of colgroup in a table with class table results in an unexpected border on the top of the table.

### Reduced test cases

https://jsfiddle.net/hLor7q9w/2/

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
Duplicatas #35152.
