### ISSUE TITLE
Error when upgrading from 4.5.3 to 5.1.3

### ISSUE THREAD

**Issue by Joossensei** [twbs/bootstrap#35177]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I was upgrading the Bootstrap dependency for the open-source CMS I am working on and when I ran `npm install bootstrap@latest` this installed everything like it should. 
But when I tried to run `npm run build` I got an error saying `SassError: $color: var(--background) is not a color`. 
I looked into it and it seems this is something that breaks in `node_modules/bootstrap/scss/_functions.scss`.

Compiler error:
![Screenshot 2021-10-12 at 13 48 21](https://user-images.githubusercontent.com/40595903/136950481-d2325e16-10b2-424e-8cbe-29f7e1793134.png)

`_functions.scss`:
<img width="559" alt="Screenshot 2021-10-12 at 13 48 50" src="https://user-images.githubusercontent.com/40595903/136950549-9aebfacd-802d-4a28-acca-b9c4fd4e711f.png">

`_variables.scss`:
<img width="362" alt="Screenshot 2021-10-12 at 13 49 22" src="https://user-images.githubusercontent.com/40595903/136950617-a5bb3c3c-5d8a-4534-8c36-4e12ca632afe.png">

### Reduced test cases

To test this you need to git clone the open-source CMS https://github.com/bolt/core and checkout to the `bootstrap-upgrade-5.0` branch. Then run `npm install && npm run build`. Then see the errors

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.5.3 -> v5.1.3

**Comment by kaushikshukla** [comment]
do we have solution for this problem, because i have also faced similar problem while upgrading bootstrap from 4.5.3 to 5.2.3.
When the error comes as variables as undefined.
