### ISSUE TITLE
Carousel fade in fade out text transition is not smooth (v5.1.3)

### ISSUE THREAD

**Issue by sinjuangajan** [twbs/bootstrap#35181]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Carousel fade in fade out transition is not smooth when using text only. please fix this. 
Please check codepen link below
Bootstrap v5.1.3
Chrome  94.0.4606.81 (64-bit)
Windows 10 Pro 19042.1237

![Animation](https://user-images.githubusercontent.com/4011140/137070947-f8e71670-6349-4128-8436-151ecf5251de.gif)

### Reduced test cases

[Codepen](https://codepen.io/sinjuangajan/pen/QWMbdwE)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Set a `background-color` on `.carousel-item` and it'll be smooth. The problem arises from no background being set by default, which we're unlikely to change. Perhaps we need to mention this in our docs.

**Comment by hermbo** [comment]
This is related to `_carousel.scss` on line `81`

```css
@include transition(opacity 0s $carousel-transition-duration);
```

Setting the opacity `0s` to at least `1s` solves it, or removing it.

@mdo Please fix if possible by providing it a variable if it needs to remain.
