### ISSUE TITLE
Bootstrap 5 Dropdown: Window.getComputedStyle: Argument 1 is not an object.

### ISSUE THREAD

**Issue by chilled-capybara** [twbs/bootstrap#35199]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Despite the `dropdown-menu` class and the `data-bs-toggle="dropdown"` property, unlike Bootstrap 4, there is currently no flexibility in the order in which the dropdown menu and trigger button should be used within the `dropdown` wrapper.

From the [docs](https://getbootstrap.com/docs/5.1/components/dropdowns/#examples;);
> Wrap the dropdown’s toggle (your button or link) and the dropdown menu within .dropdown, or another element that declares position: relative;.

I've added two tests cases, one for button-then-menu and one menu-then-button;
```html
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
    aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
  </ul>
</div>
```

```html
<div class="dropdown">
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
  </ul>
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
    aria-expanded="false">
    Dropdown button
  </button>
</div>
```

If the button is the second element, it will throw;
```
Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object.
```

Whilst there is a way to avoid the error (by changing the order), I'm not sure whether there should be the adaptability that was present in Bootstrap 4?

### Reduced test cases

Working example (button then dropdown);
https://codepen.io/chilled-capybara/pen/rNzOjrJ

Example with error (dropdown then button);
https://codepen.io/chilled-capybara/pen/ExvVZep

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.1.3

**Comment by GeoSot** [comment]
plus 
```
    const getToggleButton = this.matches(SELECTOR_DATA_TOGGLE) ? this : SelectorEngine.prev(this, SELECTOR_DATA_TOGGLE)[0]

```

But the real question is: Do we have a reason to mess the mark up when the docs provide a specific one?

**Comment by rilrom** [comment]
I think it's more about what reason was there behind restricting the order in v5 when it was already present in v4.
