### ISSUE TITLE
Modal events not working for JQuery .on()

### ISSUE THREAD

**Issue by UgoFlamarion** [twbs/bootstrap#35215]
**Context** : Symfony 5.3.9 project / Boostrap 5.1.3

This works :
 `document.getElementById('myModal').addEventListener('hidden.bs.modal', function() { alert('ok'); });`

This doesn't :
`$("#myModal").on('hidden.bs.modal', function() { alert('ok'); });`

Same goes for any modal event. Did I miss something ?

**Comment by alecpl** [comment]
I have no time to create a demo, but I can confirm I had the same issue in the past using B5. I switched to addEventListener(). It's likely caused by the fact that in jQuery `.bs.modal` (or `.modal`) is a namespace suffix.

**Comment by XhmikosR** [comment]
Happy to fix any issue as long as someone provides a PR with an accompanied test case

**Comment by alecpl** [comment]
I'm unable to reproduce the issue right now. https://codepen.io/alecpl/pen/vYJPLQz Maybe that has something to do with the order of code execution somewhere, but it does not look like a Bootstrap bug anymore.

**Comment by XhmikosR** [comment]
The order shouldn't matter either. I recall we landed a fix at some point, unsure if we covered everything, though.

**Comment by alecpl** [comment]
The detection depends on existence of `window.jQuery`. I guess, in some cases it might just not exist. As this is mentioned in https://getbootstrap.com/docs/5.0/getting-started/javascript/#still-want-to-use-jquery-its-possible (and #events) I suggest to close this ticket. Maybe every page mentioning addEventListener() should have a link ("How to do this with jQuery?") to this getting started page section.

ps. I once worked with `cash-dom` which is a tiny jQuery replacement. The way it was imported created only `window.$`.

**Comment by jayaddison** [comment]
This is affecting a `shown.bs.modal` jQuery event handler [here](https://github.com/openculinary/frontend/blob/2765f56ba4e98e8027929b1f7aea74ca62b07861/src/app/dialogs/about.ts#L10), I think.  More findings within the next few hours, hopefully.

**Comment by jayaddison** [comment]
Without having tracked down the cause precisely, adding a workaround in https://github.com/openculinary/frontend/commit/dcfef5dd29fd4b7c7fe142b0a50925212a9453d6 has resolved this short-term (thank you @alecpl for the pointer towards the `window.jQuery` detection mechanism).
