### ISSUE TITLE
The V4 version sets the width of the modal

### ISSUE THREAD

**Issue by bbhxwl** [twbs/bootstrap#35212]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Setting the height of the modal-body is OK, but after setting the width of the modal-content, it cannot be displayed in the middle.

<div class="modal fade"    id="AddUserGroup"  tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:800px;">
        <div  class="modal-content"   >
            <div class="modal-header" >
                <h5 class="modal-title" id="exampleModalLabel">修改用户信息</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="height:500px;"  >
                <iframe class="w-100 h-100 border-0" src='/SportsDoctorAPI/App/EditUserInfo?EnterpriseId=@(Model.EnterpriseID)&IdNum=@(Model.IDNum)&dt=@(dt)&sign=@(Html.Raw(Common.Encryption(Model.IDNum+dt,"AiDeLi66")))'></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

### Reduced test cases

Setting the height of the modal body is OK, but after setting the width of the modal dialog, it cannot be displayed in the middle.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.6

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
