### ISSUE TITLE
Can you pass an open or closed collapse state to another web page on your site?

### ISSUE THREAD

**Issue by BillyBobBell** [twbs/bootstrap#35245]
Change the state of a collapsed panel on another page depending if it was open or closed when the next page is opened in the same site.
My first thought was to just make two separate pages, one opened and one closed. Then do a script on the original first page that directs you to either page.

**Comment by ffoodd** [comment]
Bootstrap doesn't provide such things (so I'm closing this). 

I suggest you search around the `postMessage` API and the `message` event, or the `broadcastChannel` API.
