### ISSUE TITLE
Need refund for Order #99665

### ISSUE THREAD

**Issue by chetanmaharishi** [twbs/bootstrap#35241]
Hey Support

I bought hyper theme in React(https://themes.getbootstrap.com/product/hyper-react-admin-dashboard-template/).

While my intention was buying it in bootstrap html(https://kinsta.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/). My order number is #99665.

Can you please provide me HTML theme and cancel my this React theme license?
I have already emailed(themes@getbootstrap.com) same request 3 days back but i have not received any reply.
Please resolve this thing soon.

Hope you understand.

Thanks

**Comment by mdo** [comment]
Sorry, but this isn't the place to get help with the Themes marketplace.
