### ISSUE TITLE
RFS incorrectly applied on body

### ISSUE THREAD

**Issue by AdrianRichardson** [twbs/bootstrap#35251]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In Bootstrap 5.1.3, the use of `@include font-size()` to set a responsive font size to body in [_reboot.scss (line 52)](https://github.com/twbs/bootstrap/blob/1a6fdfae6be09b09eaced8f0e442ca6f7680a61e/scss/_reboot.scss#L52) is not working.

The value being passed to font-size(), ie `var(--#{$variable-prefix}body-font-size)`, is not something that the rfs() functions consider to be numeric.  With the change in commit [4d7911a27bf9591c1f4dee53fe0b1f053646d0fd](https://github.com/twbs/bootstrap/commit/4d7911a27bf9591c1f4dee53fe0b1f053646d0fd#diff-1a18889ae3c2fbdc988fd3df1faea3e8a6ebcf581025c8be8ea4843db53e6253R52), when compiling you can no longer have a responsive value on body based on the `$font-size-base` SCSS variable, you now have to override the CSS custom property `--bs-body-font-size`.

I think moving the font-size()/rfs() function from _reboot.scss to [_root.scss (line 44)](https://github.com/twbs/bootstrap/blob/612d235faf3515dacceb19df04f1d32b9ef62c55/scss/_root.scss#L44) should fix this, so instead of 

```
:root {
  --#{$variable-prefix}body-font-size: #{$font-size-base};
}
body {
  @include font-size(var(--#{$variable-prefix}body-font-size));
}
```

you would have
```
:root {
  @include rfs($font-size-base, --#{$variable-prefix}body-font-size);
}
body {
  font-size: var(--#{$variable-prefix}body-font-size); 
}
```

### Reduced test cases

[CodePen showing how the existing approach for RFS on body compares with the proposed solution](https://codepen.io/AdrianRichardson/pen/NWvbeaV)

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Fixed by #35326
