### ISSUE TITLE
Simplify bundle customization: optional components (v5)

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#35254]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add components  to `package.json`: 
~~~json
"bsComponents": {
    "component 1": ["scss filename", "js module"],
    "component 2": ["scss filename"],
    ...
}
~~~
and use list to generate bundle (`bootstrap.scss` and `bootstrap.js`) 

### Motivation and context

Simple mechanism to exclude unused components and minimize asset files. 
Bundle customization without changes in `build/` and `scss/`.

**Comment by GeoSot** [comment]
@WinterSilence, please feel free to open an MR, and guide the way to this 😃

**Comment by WinterSilence** [comment]
@GeoSot at first I would like to get consent of package owners as you - I would not like PR to be closed after I spend many time on this update

**Comment by ffoodd** [comment]
Not sure about the approach: you're already able to only import the files you need from your `node_modules`, this is pretty straightforward.

Moreover listing components this way won't cover dependency files (e.g. root and reboot, on the Sass side).

How is this proposal supposed to handle such cases? And how is it better or simpler than importing from `node_modules`?

**Comment by WinterSilence** [comment]
@ffoodd 
> Moreover listing components this way won't cover dependency files (e.g. root and reboot, on the Sass side).

~~~json
"bsComponents": {
    "component 1": ["scss filename", "js module"], // "active" components
    "component 2": ["scss filename"], // root and reboot, on the Sass side
    ...
}
~~~

> How is this proposal supposed to handle such cases? And how is it better or simpler than importing from node_modules?

yes, yes.. import better, but  BS not use it by default. it's solution to build custom bundle.

**Comment by WinterSilence** [comment]
@ffoodd i'm planed add interactive script to selecting components generates custom bundle

**Comment by ffoodd** [comment]
I still don't see the point for Bootstrap. All the files are distributed so IMO this proposal only lists what's distributed.

Would you be able to explain how you'd use that on a project depending on Bootstrap?

**Comment by WinterSilence** [comment]
@ffoodd for example in current application you no use carousel and offcanvas. you run `npm` script  to customize bundle, excludes this components and generates custom `bootstrap.scss` and `bootstrap.js`

**Comment by ffoodd** [comment]
That's not an example. 

To do what you describe, simply import the JS and scss files you need and that's it, there's no need for such new entry on our side.

**Comment by WinterSilence** [comment]
@ffoodd then explain what example do you expect? it's scaffold script to fast & handy configure BS. This approach eliminates mechanical errors.  `import { Toast } from 'bootstrap.esm.min.js'` You still load "all in" JS file with unused components+ need import components for every page.

**Comment by GeoSot** [comment]
@WinterSilence I did the following test:

Using webpack, I imported only modal and build a script `public\...\app.js`

![image](https://user-images.githubusercontent.com/22406063/145905449-682b0560-60bb-4e79-8be7-88c0c7fab3ac.png)
And I load this script in a dummy page

![image](https://user-images.githubusercontent.com/22406063/145905657-edc5cc68-669c-4281-8cde-d40bb709a932.png)


I didn't had any problem. I tested to use an offcanvas (expecting to fail, as it did) and some modal markup that worked as I was expecting. 


It didn't fetch other js than these I was needed . 😵 

Of course you are right on the **css** part, that has to be loaded in separate. And I am not sure if your proposal would solve this somehow

**Comment by WinterSilence** [comment]
@GeoSot

> I didn't had any problem.

cheater (:  it's not same to `import { Toast } from 'bootstrap.esm.min.js` + in this case JS not compressed (by default)

> And I am not sure if your proposal would solve this somehow

why?

**Comment by ffoodd** [comment]
On the Sass side, we already want to document the dependencies required for each component, but FWIW our Sass docs already explains the required files and their respective order.

I can't see how your suggestion could help with this, but if you're convinced feel free to open a PR so that we have something to try.

**Comment by mdo** [comment]
Closing as a won't fix/implement, although it'd be rad to have some kind of `create-bootstrap` repo similar to other projects that'd allow us to have a CLI for starting Bootstrap-powered projects.

**Comment by WinterSilence** [comment]
@mdo we don't need another repo for this, I can update `build` to generate `bootstrap.custom.scss` and `bootstrap.custom.js` by `bootstrap` list in `package.json`, `build/bootstrap.json`: `{component: scss files, component2: js and scss files, ...}`
