### ISSUE TITLE
Suggest a new feature

### ISSUE THREAD

**Issue by Dezmonter** [twbs/bootstrap#35261]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

In the documentation CSS GRID did not notice such a useful function as grid-row for working with different screen resolutions, I think it would be very useful!

### Motivation and context

grid-row is part of the CSS GRID functionality that the community needs

**Comment by mdo** [comment]
Rows are adjustable: https://getbootstrap.com/docs/5.1/layout/css-grid/#adding-rows.
