### ISSUE TITLE
Changing --bs-gutter-x create an overflow issue on mobile

### ISSUE THREAD

**Issue by MathieuAlphamosa** [twbs/bootstrap#35282]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Changing CSS variable `--bs-gutter-x` on the **row** component like this:
```
.row {
	--bs-gutter-x: 2rem;
}
```
cause an overflow issue on mobile (x axis). See test case for a demo.

This might be related to this:
`--bs-gutter-x` is used in **container** component without being defined previously.
```
.container,
.container-fluid,
.container-xxl,
.container-xl,
.container-lg,
.container-md,
.container-sm {
  width: 100%;
  padding-right: var(--bs-gutter-x, 0.75rem);
  padding-left: var(--bs-gutter-x, 0.75rem);
  margin-right: auto;
  margin-left: auto;
}
```
Note that it should be `padding-right: calc(var(--bs-gutter-x, 1.5rem) / 2);` anyway... or am I missing something?

Not sure if it should be fixed, but it should be explained in the documentation as it's complicated overflow issue to tackle.

### Reduced test cases

https://codepen.io/mathieualphamosa/pen/LYjygme

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Looking at this more closely, for some reason we halved the container padding in the variable reassignment instead of in the properties, like we do everywhere else. Definitely a bug/complication.

**Comment by donquixote** [comment]
I would like to know why does `.container` use --bs-gutter-x` at all?
I created this Q/A hoping for the answer. https://github.com/twbs/bootstrap/discussions/35807

**Comment by mdo** [comment]
All the grid gutters line up to align text with the outer bounds of the rows. It's a complicated mess I'm afraid, and one that would be rectified with CSS Grid thanks to `gap` support. Flexbox does support `gap`, but it hasn't been as widely used and I'm not 100% sure our browser support allows it. Plus it'd be a breaking change to adjust at this point I think.

Basically it goes like this with the current grid system:

- Grid gutters are cut in half and evenly applied to grid columns.
- Rows, as immediate parents of grid columns, use negative margins (the same half gutter width) to undo the "indentation" of the column padding.
- Containers, the wrappers above rows, must then provide a buffer again of horizontal padding to make room for the negative margin.

**Comment by donquixote** [comment]
> It's a complicated mess I'm afraid
I actually like the technique :) although it is a learning step for every new developer, and something 

> Containers, the wrappers above rows, must then provide a buffer again of horizontal padding to make room for the negative margin.

I assume the idea is to prevent horizontal scrollbars? If this is the goal, the container padding must be equal or bigger than half the gutter width. Which comes naturally if we use the default settings, but may no longer be the case if designers set custom values - as is the case in our project.
To compensate, we are setting overflow-x: hidden on (I think) html element.

The scrollbars can also be prevented by using one-sided grid spacing, 
https://stackoverflow.com/questions/67453548/horizontal-scrollbar-for-div-sticking-out-on-one-side-but-not-the-other
(I mentioned this in #33911 in the past, just want to mention it here again for reference. Not asking to change this now)

**Comment by donquixote** [comment]
> Flexbox does support gap, but it hasn't been as widely used and I'm not 100% sure our browser support allows it. 

How do we control column widths, if the gutter is controlled with gap?
E.g. let's say you want one 50% width column and two 25% width columns?
With the current solution with negative margin on .row + positive padding on each column, the width is controlled on each column _including_ the gutter. But with .gap we would need to use a formula for the width?

**Comment by mdo** [comment]
No, there's no need for magic formulas. Gaps are subtracted and the remaining width is equally distributed.

**Comment by donquixote** [comment]
> No, there's no need for magic formulas. Gaps are subtracted and the remaining width is equally distributed.

I tried in codepen, and it does not seem to work like this. But perhaps I am wrong..
https://codepen.io/donqi/pen/rNYYqpJ

But even if it were the case, this still would lead to a wrong result if e.g. you want 2 columns with 1/4 width and one column with 1/2 width.
