### ISSUE TITLE
Border radius in buttons group

### ISSUE THREAD

**Issue by fabienwnklr** [twbs/bootstrap#35280]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, small issue when i use `.btn-group` and the last element is dropdown with class `.dropwdown` not `.dropdown-toggle` border radius do not apply.

Screen : 
![image](https://user-images.githubusercontent.com/49644785/139017132-8fb367fd-4de3-4bb5-9e80-6fe2b25eedd0.png)

### Reduced test cases

Live demo : [https://codepen.io/fab_wnklr/pen/OJjmozO](https://codepen.io/fab_wnklr/pen/OJjmozO)

### What operating system(s) are you seeing the problem on?

Windows, Android, iOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1.0

**Comment by baaska23** [comment]
had no idea

**Comment by ffoodd** [comment]
You're supposed to use `.dropdown-toggle` here: why not using it? [It works fine](https://codepen.io/ffoodd/pen/YzrWzRK) if you use our component as recommended.

BTW the `role="group"` seems inappropriate, here.

**Comment by ffoodd** [comment]
This arrow is needed for the dropdown to be discovered by users, so I'd recommend to keep it visible.

If you insist on dropping the arrow, the simplest way (without altering our codebase) is to use [the `border-radius` utilities](https://getbootstrap.com/docs/5.1/utilities/borders/#border-radius), in your case `rounded-end`. [It works fine, too](https://codepen.io/ffoodd/pen/NWarPdX?editors=1000).

Does it seem like a reasonable solution to you?

**Comment by fabienwnklr** [comment]
Yes, i think it's a good solution ! But since the `dropdown` class exists I thought I should use it instead of override

**Comment by ffoodd** [comment]
Well, it didn't help you much, did it? 😄

Utilities are meant to apply any style easily. Using the `.dropdown` class this way, you may get conflicts with any further dropdown update we might make. 

Using utility does exactly what you want, and only that.

So if you agree with this suggestion, may we close your PR?
