### ISSUE TITLE
Wrong Behavior? Clicking in Modal

### ISSUE THREAD

**Issue by scath999** [twbs/bootstrap#35301]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Note:**_I'm assuming this is a problem with my understanding of Bootstrap, not a problem with Bootstrap itself. However, if this is an issue I'm hoping it's ok to post it here._

I cannot click anywhere inside a Bootstrap 5 modal dialog box without closing it.

If I set data-bs-backdrop="static", the modal will bounce when clicked inside but will not close. Input is still not allowed.

Including a short JS to give focus to the first input field allows keyboard input, but I cannot click on the next input.

Tabbing between fields *does* allow input.

I'm sorry if this is a known issue - I'm relatively new to GitHub. I have searched all over the place, including stack and here (both open and closed issues), but cannot find an answer.

Cheers!

### Reduced test cases

```html
<div class="navbar-nav">
   <a class="nav-item nav-link" data-bs-target="#register-modal" data-bs-toggle="modal">Register</a>
</div>

 <div class="modal fade" id="register-modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" >
    <div class="modal-dialog">
        <div class="modal-header" style="background-color: white;">
            <h1 class="modal-title">Create an Account</h1>
        </div>
        <div class="modal-body" style="background-color: white;">
            <form>
              <div class="form-group">
                <label for="email_address" class="col-form-label required">Email Address</label>
                <input type="text" id="email_address" class="form-control" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="password" class="col-form-label required">Email Address</label>
                <input type="password" id="password" class="form-control" placeholder="Password">
              </div>
            </form>
        </div>
        <div class="modal-footer" style="background-color: white;">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-success">Register</button>
        </div>
    </div>
</div>

<script type='text/javascript'>
  var myModal = document.getElementById('register-modal')
  var myInput = document.getElementById('email_address')

  myModal.addEventListener('shown.bs.modal', function () {
    myInput.focus()
  })

</script>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1; 5.1.3

**Comment by GeoSot** [comment]
@scath999 you have just missed  ` <div class="modal-content">` on  your markup ;)

**Comment by scath999** [comment]
Thanks, Geo - I did figure this out, but forgot to close. My bad, and thanks so much for responding anyway to such an inane issue - your patience is really appreciated :)
