### ISSUE TITLE
A version typo 

### ISSUE THREAD

**Issue by ednawig** [twbs/bootstrap#35303]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In site/content/docs/5.1/examples/grid/index.html line 113, it says The Bootstrap **v4** grid system has five tiers of classes. Looks like it should be v5.

### Reduced test cases

nothing

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v5.1

**Comment by coliff** [comment]
RE: https://getbootstrap.com/docs/5.1/examples/grid/

good spot. I think that sentence should read:

> The Bootstrap v5 grid system has five tiers of classes: xs (extra small, this class infix is not used), sm (small), md (medium), lg (large), xl (x-large), and xxl (xx-large).

The naming above will then match the container docs page: https://getbootstrap.com/docs/5.1/layout/containers/#how-they-work

I'll make a PR.
