### ISSUE TITLE
Modals in a div

### ISSUE THREAD

**Issue by Anoopkumarseth** [twbs/bootstrap#35311]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

![image](https://user-images.githubusercontent.com/30388576/139674671-1f4fa18c-745a-466a-9860-5f60310ae2e7.png)
Can we have an example to show bootstrap modal in a div instead of full-body because Single page application we want to show modal on a particular component only but we couldn't find any proper example to show that

### Motivation and context

bootstrap is used in most Single page applications like Angular and React.js so maybe most people will find it useful. maybe it's possible with the bootstrap but we just need a BS 5 example to know how we can make it perfectly like Sidebar.

**Comment by GeoSot** [comment]
Hey @Anoopkumarseth. As far as I know Modal doesn't support different rootElement than body. #33018 tried to implement it, but is still pending

**Comment by mdo** [comment]
Closing as stale alongside the issue.

**Comment by AndrewElans** [comment]
If you place your modal in another container than `body', boostrap's `<div class="modal-backdrop fade show"></div>` is always appended to `body'.

I fixed as follows on `bootstrap.bundle.js` version `v5.3.3`

1. Find `class Backdrop extends Config`, there `_configAfterMerge(config)`
2. Replace `config.rootElement = ... `  with `config.rootElement = getElement(config.rootElement) || document.body;` with will fallback to `body' if rootElement is not found (null returned from getElement()
3. Find `class Modal extends BaseComponent`, there `_initializeBackDrop()`
4. add after `isAnimated: this._isAnimated()` a new property ` rootElement: this._config.rootElement`

When initializing your bootstrap with `new bootstrap` add `rootElement: <your container: HTMLElement as object or string selector`, for example: 

```javascript
const rootElement = document.getElementById('your-div);
const myModal = new bootstrap.Modal(
    document.getElementById('myModal'))
    , {
        backdrop: "static", 
        rootElement
    }
)
myModal.show()
```
or
```javascript
const myModal = new bootstrap.Modal(
    document.getElementById('myModal'))
    , {
        backdrop: "static", 
        rootElement: '#your-div'
    }
)
myModal.show()
```
