### ISSUE TITLE
How to map spacers using dart sass with use instead of import

### ISSUE THREAD

**Issue by TannerS** [twbs/bootstrap#35312]
### Discussed in https://github.com/twbs/bootstrap/discussions/35302

<div type='discussions-op-text'>

<sup>Originally posted by **TannerS** October 29, 2021</sup>
When using node-sass with import, we would use bootstrap with setting the spacers as such within our scss file.

```
$spacer: 1rem !default;

$spacers: (
  0: 0,
  // 2px
  1:
    (
      // 4px
      $spacer * 0.25
    ),
  2: (
    // 8px
    $spacer * 0.5
  ),
  3: $spacer,
  4: (
    // 24px
    $spacer * 1.5
  ),
  5: (
    // 32px
    $spacer * 2
  ),
  6: (
    // 48px
    $spacer * 3
  ),
  7: (
    // 64px
    $spacer * 4
  ),
  8: (
    // 80px
    $spacer * 5
  ),
  9: (
    // 100px
    $spacer * 6.25
  )
);

@import "~bootstrap/scss/bootstrap";
```

While switching to dart-sass (sass), they are slowly moving to replace `import` with `use`, so while doing that, I did it like this 

`@use "~bootstrap/scss/bootstrap";` but that doesn't work and the spacers don't exist, when I tried doing 

```
@import "~bootstrap/scss/bootstrap" as *;
```

I get this error

```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: This module and the new module both define a variable named "$spacer".
   ╷
42 │ @use "~bootstrap/scss/bootstrap" as *;
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/client/app.scss 42:1  root stylesheet
```

Any idea how to properly do this using `use`?  Please and thanks in advance and sorry about my naiveness in the matter. </div>

**Comment by mdo** [comment]
Unfortunately there's not much we can help with here because we're not using Dart Sass's modules system yet. I've had very little experience with it, other than a couple test runs during early v5 development. Closing this out and keeping it as a discussion. Perhaps give it a bump in the Bootstrap Slack?

**Comment by TannerS** [comment]
Never knew you guys had a slack, but thanks for the reply!

**Comment by TannerS** [comment]
@mdo hey, what is the bootstrap slack?

**Comment by ffoodd** [comment]
There's a link in our docs, at least in the footer community section: [Bootstrap Slack](https://bootstrap-slack.herokuapp.com/).
