### ISSUE TITLE
`:autofill` match doesn't work with `bg-*` classes

### ISSUE THREAD

**Issue by Yash-Singh1** [twbs/bootstrap#35321]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have a form control, and I applied the `bg-dark` class to it. However, when users use autofill and autocomplete their input, the form control turns white background because that is the browser default.

![Screenshot from 2021-11-02 20-17-28](https://user-images.githubusercontent.com/53054099/140005537-1b88ba69-d748-4a77-9297-a75da3088e9d.png)
![Screenshot from 2021-11-02 20-17-23](https://user-images.githubusercontent.com/53054099/140005536-56364ba0-53f8-49e3-8300-56c28cc08c6e.png)

![Screenshot from 2021-11-02 20-16-20](https://user-images.githubusercontent.com/53054099/140005532-a80bfef0-14de-4df4-999d-30c47ef406c2.png)

### Reduced test cases

```html
<input class='form-control bg-dark text-white' />
```

Simply that, but the text that is usually put in needs to be cached by Chrome. The best reproduction would be to give the `input` an ID and put it in an `index.html` and host a directory with that HTML using `python -m http.server`.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
I believe there's no way to change this: https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill.
