### ISSUE TITLE
.form-floating, .was-validated and z-index

### ISSUE THREAD

**Issue by rmullaney77** [twbs/bootstrap#35323]
_input-group.scss

Upon validation ".was-validated" applies "z-index:1" to child inputs, causing the label to be displayed behind input.

".form-floating" labels need "z-index:2" (or higher) to remain visible

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
