### ISSUE TITLE
need  to give position relative to manually to Col for align inner absolute div in Col ?

### ISSUE THREAD

**Issue by khushmohammad** [twbs/bootstrap#35332]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

How to handle position relative for all col, because previous version position relative added default in col , generally i am getting problem with div align inside a div.

so ,  basically i giving position absolute then my div not align properly in col.

 need give position relative to manually to col ?

### Motivation and context

How to handle position relative for all col, because previous version position relative added default in col , generally i am getting problem with div align inside a div.

so ,  basically i giving position absolute then my div not align properly in col.

 need give position relative to manually to col ?

**Comment by mdo** [comment]
The docs and migration guide to v5 mention this. Use `.position-relative`.
