### ISSUE TITLE
Creating Dark Mode Button

### ISSUE THREAD

**Issue by nshah1729** [twbs/bootstrap#35333]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Creating a Dark mode button applicable to all pages

### Motivation and context

As a user, I always use Dark mode for navigating websites

**Comment by sambhavsaxena** [comment]
Its easy to implement dark mode by a toggle button, which will switch the classes on bootstrap from 'light' or 'danger' or anything  else to say 'dark', why need an integrated function for that?

**Comment by guys1444** [comment]
Hi , please upload an image of an example to get an idea of the dark mode button you are asking for and where do you want it to be be , thanks
