### ISSUE TITLE
Tooltip rendering bug

### ISSUE THREAD

**Issue by Grumvol** [twbs/bootstrap#35340]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Rendering bug in case there is not enough space on the side.

![QIP Shot - Screen 1186](https://user-images.githubusercontent.com/20611667/140797758-bb503107-cdf9-45bc-a469-e991819e32c1.png)
![QIP Shot - Screen 1187](https://user-images.githubusercontent.com/20611667/140797789-1176a8d5-a075-449c-b703-996ef0026866.png)

### Reduced test cases

Window 10
Chrome 95.0.4638.69
Bootstrap 5.1.3

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by nkdas91** [comment]
#34595
