### ISSUE TITLE
Removing Non-Inclusive Terms In Code

### ISSUE THREAD

**Issue by amanda-delongchamp** [twbs/bootstrap#35347]
### Discussed in https://github.com/twbs/bootstrap/discussions/35095

<div type='discussions-op-text'>

<sup>Originally posted by **amanda-delongchamp** October  1, 2021</sup>
Hello - it appears that even bootstrap v5.1.0 still has the word "master", the following is in bootstrap.js file within the very latest version of .Net nuget package, on line 2515.  Is there plans in a future release soon to remove or rename this?  My company is in process of trying to remove all non-inclusive terms in our code, terms that could be considered offensive.

* Bootstrap (v5.1.0): util/backdrop.js
   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)</div>

**Comment by akx** [comment]
This seems to have been fixed in 5cc633dfabf3687bbbae9344725435031b022e81, #34932 and released in #35114 (Bootstrap 5.1.2).
