### ISSUE TITLE
Bootstrap 4 Tabs is not working inside Popover Html Content

### ISSUE THREAD

**Issue by abdulrazakshaikh** [twbs/bootstrap#35344]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

Tabs do not seem to be working for me when used within Popover. if i add tabs outside the popover it is working fine.

What happens is following:
1. Popover opens
2. Tab content is not changing **<-- PROBLEM**

### Reduced test cases

.Issue Demo Link : [https://codepen.io/abdulrazakshaikh/pen/xxLzQeB](https://codepen.io/abdulrazakshaikh/pen/xxLzQeB)

**return $('#popover-content').remove().html();**
if i write remove like this the tabs is working fine but after closing the popover & re-opening popover doesn't work. 
Show some error below

sanitizer.js:93 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at ke (sanitizer.js:93)
    at o.e.setElementContent (tooltip.js:410)
    at o.a.setContent (popover.js:116)
    at o.e.show (tooltip.js:255)
    at o.e._enter (tooltip.js:580)
    at o.e.toggle (tooltip.js:190)
    at HTMLDivElement.<anonymous> (tooltip.js:504)
    at HTMLDivElement.dispatch (jquery.slim.min.js:2)
    at HTMLDivElement.v.handle (jquery.slim.min.js:2)

I hope somebody provides a solid and effective workaround.

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.6.0

**Comment by GeoSot** [comment]
@abdulrazakshaikh try this

```js

var content = $('#popover-content').html(); // cache the content
$('#popover-content').remove(); // remove it not to mess with same selectors on same doc

$('[data-toggle="popover"]').popover({
  html: true,
  container : 'body',
  // trigger : 'focus',
  sanitize : true,
  sanitizeFn: function (content) {
    return DOMPurify.sanitize(content);
  },
  // delay: { "show": 100, "hide": 400 },
  placement: 'bottom',
  // template : '<div>lorem</div>',

  content: function() {
      return content;
  }
});


$(document).on("click", ".popoverclose", function () {
  $(this).parents(".popover").popover('hide');    
});


```


The explanation is that in your example you ended up with two same elements , and probably tab was picking the hidden


Another solution is to  use the 


```js

  content: function() {
      return $('#popover-content').css('display','block')
  }
```

as it will get the element itself, removing the hidden state, and use it
