### ISSUE TITLE
The existence of 2 types in Input group

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#35355]
https://getbootstrap.com/docs/5.1/forms/input-group/#multiple-inputs

https://getbootstrap.com/docs/5.1/forms/input-group/#custom-select

Can two types of input types be placed in the same input group? On the left is select, and on the right is input. The select on the left does not require format verification.

Requirements such as: input the information of the mobile phone number, when the mobile phone number has the country prefix selection. You need to select the country prefix and enter the mobile phone number in the same row. Obviously, it is a reasonable choice for them to be in the same row. However, the current bootstrap does not fit perfectly.

**Comment by nkdas91** [comment]
@ZhangChengLin Yes you can.
Check this [CodePen](https://codepen.io/neeraj-kumar-das/pen/gOxvddq)

**Comment by ZhangChengLin** [comment]
Hmm, no verification, the drop-down menu is in good form

The border color of the button form is better adapted

**Comment by GeoSot** [comment]
Thank you @nkdas91
