### ISSUE TITLE
v5 affix features

### ISSUE THREAD

**Issue by newyhj** [twbs/bootstrap#35351]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

is any plan devopment affix  function?

### Motivation and context

It's too useful

**Comment by XhmikosR** [comment]
I don't think we are going to bring it back, it was removed in v4.0.0, see https://getbootstrap.com/docs/4.6/migration/#components
