### ISSUE TITLE
tracking end of transition collapse on multiple element

### ISSUE THREAD

**Issue by arcanisgk** [twbs/bootstrap#35350]
### Discussed in https://github.com/twbs/bootstrap/discussions/35317

<div type='discussions-op-text'>

<sup>Originally posted by **arcanisgk** November  2, 2021</sup>
i  am try to implemente a check (type [switches](https://getbootstrap.com/docs/5.1/forms/checks-radios/#switches)) to collapse multiple element:

```
let atsu_enable = document.getElementById('act-url');
atsu_enable.addEventListener("change", function (e) {
    let collapseElementList = [].slice.call(document.querySelectorAll('.atsu-options'));
    if (atsu_enable.checked) {
        collapseElementList.map(function (collapseEl) {
            new bootstrap.Collapse(collapseEl, { hide: false });
        });
    }else{
        collapseElementList.map(function (collapseEl) {
            new bootstrap.Collapse(collapseEl, { show: false });
        });
    }
})
```

but if i click to fast the switches collides with the collapse transition:

Fine:

![image](https://user-images.githubusercontent.com/1207306/139909409-efed4970-07ff-41fd-acc0-48ec7bbd6f91.png)

collides transition result:

![image](https://user-images.githubusercontent.com/1207306/139909587-d33cb473-adf3-4bc1-9525-4341f03f7d5f.png)

I have seen that when it comes to an element it can be detected when the transition ends with [this](https://getbootstrap.com/docs/5.1/getting-started/javascript/#asynchronous-functions-and-transitions).

 **_but in my case they are multiple elements, how can I track multiple elements?_**

</div>

**Comment by XhmikosR** [comment]
`Promise.race` maybe?

Either way this should be a discussion.
