### ISSUE TITLE
Allow user to configure default table head vertical alignment

### ISSUE THREAD

**Issue by trentprynn** [twbs/bootstrap#35367]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently bootstrap has the `$table-cell-vertical-align` variable which sets table row `(<tr>)` vertical alignment but there is does not have another variable to set table head `(<th>)` vertical align

I would like another variable (perhaps `$table-th-vertical-align` to match the `$table-th-font-weight` variable that already exists) that sets the vertical alignment of table head `(<th>)` cells. 

[Here is a stackblitz](https://stackblitz.com/edit/bootstrap-5-xqmue3?devtoolsheight=33&file=src/styles.scss) that shows the problem
- **note:** must view stackblitz using chrome

below is an image of the problem
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/22459581/142230545-840e7ee2-ada4-4dd3-8fc9-b8b730e9fc53.png">

### Motivation and context

Currently in my bootstrap modification .scss file I have to do the following

```
// adjust tables to vertically center content in both
// header and row cells -- unfortunately bootstrap only offers
// a variable for setting row cell (<tr>) vertical alignment so we
// must manually set header (<th>) vertical alignment
// https://getbootstrap.com/docs/5.1/content/tables/#variables
$table-cell-vertical-align: middle;
th {
  vertical-align: middle;
}
```

I'd prefer to have another bootstrap variable I can set that handles this or have this behavior included with `$table-cell-vertical-align: middle` though that may be considered a breaking change

**Comment by mdo** [comment]
We apply `$table-cell-vertical-align` to the `.table`, not the individual cells. I think this will stay as-is.
