### ISSUE TITLE
.hide() won't dismiss modal if fade class is present

### ISSUE THREAD

**Issue by lolbat** [twbs/bootstrap#35361]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If a modal has the `fade` class on it then it won't respond to a call to the  `.hide()` method.

This modal

```html
<div class="modal fade" id="loadingModal" tabindex="-1" aria-hidden="true">
  
  <div class="modal-dialog">
      
    <div class="modal-content">
        
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Loading </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <div class="modal-body" id="loadingModalText">
        Loading JSON and HTML data for the document.
      </div>

    </div>
    
  </div>
  
</div>
```

Will respond to the `.show()` method but when called using the `.hide()` method it will not dismiss. 

The only way to get this to work is to remove the `fade` class from the modal. 

I am declaring the modal with this code

```js
        this.loadingModal = new bootstrap.Modal(document.getElementById('loadingModal'), {
            backdrop:"static",
            keyboard:false,
            focus:true
        });
```

and then using this code (obviously in different functions) to show and hide it

```js
this.loadingModal.hide();

this.loadingModal.show();
```

### Reduced test cases

I tried to build a test case but CodPen and JS Bin have an issue with modal display. 

I have this issue on two projects. One using Bootstrap via npm and the other using the code via the CDN. 

### What operating system(s) are you seeing the problem on?

Windows, macOS, iOS

### What browser(s) are you seeing the problem on?

Safari, Firefox

### What version of Bootstrap are you using?

Bootstrap v5.1.3

**Comment by GeoSot** [comment]
Hey @lolbat do me a favor. As your modal is animated you have to listen to the proper events before trigger the next action.

Try use something like:


```js

this.loadingModal.show();
document.getElementById('loadingModal')l.addEventListener('shown.bs.modal', function (event) {
   this.loadingModal.hide();
})
```

**Comment by AYB-CHA** [comment]
I have the same issue my modal dosen't hide when I call .hide() methon on it.
``

**Comment by lolbat** [comment]
I'll give that a try and see what happens.

**Comment by lolbat** [comment]
Hi @GeoSot 

I just wanted to qualify something.

I assume that what you are saying is that the `fade` class is animated and therefore needs to have a listener attached to the modal to trigger the `hide()` method?

If so, then the Bootstrap modal docs need to be a) clarified a bit a b) lose the `fade` class from the examples because as it stands if you use the sample code on the docs site you run into this error.

**Comment by GeoSot** [comment]
> lose the fade class from the examples because as it stands if you use the sample code on the docs site you run into this error.

Hey @lolbat I am not so sure about this suggestion. 

Although, if you still feel it should be clarified, please help, making a MR, sharing your thoughts

**Comment by HeyWrecker** [comment]
I have just recently run into this issue using Bootstrap v. 4. From the documentation on the site, it's not immediately clear that applying `fade` to the `modal` div will prevent calls to the `.modal('hide')` method from working.

My case scenario is that on a jQuery ajax `.fail` I want to close the Bootstrap modal. Calling `$('#ajaxContentModal').modal('hide')` from within the `fail` callback only closes the modal IF I don't have the `fade` class applied. By all outward appearances that presents as a bug.

**Comment by lolbat** [comment]
The issue as I understand it is that the .fade class is an animation and that requires code to have an eventListener to wait for the end of the animation and then trigger the .hide method.  @GeoSot mentions this in his comment above.

The problem is that all of the examples starting with the [Live Demo](https://getbootstrap.com/docs/5.1/components/modal/#live-demo) example in the documentation add this unnecessary .fade class to the code samples but don't reference this need for an eventListener and so none of the modal sample code will work.

**Comment by HeyWrecker** [comment]
@lolbat MR possibly equals a Merge Request. Same as a PR. At least insofar as I've heard it used.

I don't find  `fade` to  be useless useless, it creates a nice transition effect. But IMO it presents as a bug to the end user precisely as you said, there is no documentation indicating that you need to set-up an event listener in order to call `modal('hide')` when the `fade` class is applied.

**Comment by mdo** [comment]
Revisiting this quite late, but I'm not sure what we need to add to the docs here as this 1) doesn't seem super widespread of a problem, and 2) feels pretty standard when dealing with animations (you can't interrupt them or act on an animating element until it's done animating I believe).

**Comment by jjchirinos2688** [comment]
This saved my life. I had been presenting the problem for a whole day. You have to eliminate the fade class and the hide method works.
