### ISSUE TITLE
--bs-scroll-height   What is the use of?

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#35366]
https://github.com/twbs/bootstrap/blob/1a6fdfae6be09b09eaced8f0e442ca6f7680a61e/dist/css/bootstrap.css#L4098

https://github.com/twbs/bootstrap/blob/b21c7ccbb7e3d955fd5043aae6d426cef5765dfa/scss/_navbar.scss#L153

https://getbootstrap.com/docs/5.1/components/navbar/#scrolling

`
max-height: var(--bs-scroll-height, 75vh);
`

It is understandable in the code. How can I see the effect in the example?

**Comment by ZhangChengLin** [comment]
https://github.com/twbs/bootstrap/blob/31998dfd1e972faf46ab23c26533d3e1a5f5e4bf/site/content/docs/5.1/components/navbar.md#L505

style="--bs-scroll-height: 100px;"

The critical value change seen is 40px

**Comment by mdo** [comment]
Narrow your viewport and you'll see the customized vertical scroll height. This CSS var allows you to change how tall the scrollable area is within an expanded navbar.
