### ISSUE TITLE
$input-disabled-color variable is missing

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#35372]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

We have $form-select-disabled-color variable, that allows us to change select text color in disabled state. But we don't have the same in .form-control. To keep form styling consistent, we either need to add $input-disabled-color or remove $form-select-disabled-color

### Reduced test cases

-

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment]
Making a note for future me: `$form-select-disabled-color` is set to `null` currently, so we can likely do the same for `.form-control`.
