### ISSUE TITLE
popover with empty string throws null error

### ISSUE THREAD

**Issue by open-admin-org** [twbs/bootstrap#35371]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

<button type="button"
    class="btn btn-secondary"
    title="Title"
    data-bs-container="body"
    data-bs-toggle="popover"
    data-bs-placement="left"
    data-bs-content=''>
  Popover
</button>

popover with empty data-bs-content throw Null error:
Uncaught TypeError: TOOLTIP: Option "content" provided type "null" but expected type "(string|element|function)".
    l index.js:136
    l index.js:130
    _getConfig tooltip.js:677
    Fe tooltip.js:143
    Qe popover.js:67

### Reduced test cases

https://codepen.io/open-admin-org/pen/porGJNr

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.0.2 / latest

**Comment by GeoSot** [comment]
thank you for opening this issue. 😃  Please you are more than welcome to open an MR solving this

**Comment by XhmikosR** [comment]
I'm not sure I understand the issue. Why should it work? I mean, it clearly has no content...

**Comment by open-admin-org** [comment]
Although i could think of situations where the error might help it think its up to programmer to decide is he would like show empty popovers.

A couple of reasons for showing empty:
- only want to display the title
- show that something is empty
- an empty value is still a value

Possible use case: In a list of an admin panel; Show a popovers with text content when clicking on a 'view text' button. Sometimes this text value might be empty, in this case you like the user to know that there is no content.

**Comment by GeoSot** [comment]
After some testing, I cross-checked that popover works if: 
* it has empty title but, has content (this seems to be a side effect that live in the shadows for many years)
* has title and content 

And always checks if it has content
```js

  _isWithContent() {
    return this._getTitle() || this._getContent()
  }


  show() {
    if (this._element.style.display === 'none') {
      throw new Error('Please use show on visible elements')
    }

    if (!(this._isWithContent() && this._isEnabled)) {
      return
    }
......
}

```
The only sure thing here is that we cannot have an empty popover, so we are guided to the big question, if we have only title, isn't or not a tooltip?

**Comment by open-admin-org** [comment]
Thanks for looking in to this. Much appreciated.

Here my use case:
![image](https://user-images.githubusercontent.com/86517067/144621132-a1328f38-16be-4f49-94a1-b8865732daf4.png)

To make the above possible i have to "hack" and pass a "space" as value to allow the second popover to show.

Like this.
`data-bs-content=" "`

**Comment by GeoSot** [comment]
@patrickhlauke  is it valid to show a popover without body and only title? please give us your opinion

**Comment by patrickhlauke** [comment]
as the popover as a whole is referenced via `aria-describedby`, it will read out whatever content it find in there - even if it's just the title/heading. so from that point of view, there's no issue i'd say. but yeah whether it's sensible to do in the first place... shrug
