### ISSUE TITLE
Adjascent popovers overlap each other

### ISSUE THREAD

**Issue by lenormf** [twbs/bootstrap#35378]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

It’d be nice if popover windows could be made to reflow automatically whenever they would overlap an adjacent one upon being triggered.

HTH.

### Reduced test cases

```html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-auto">
            <button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Velit consequatur neque repellendus aut animi. Aut ut et nam dolorem unde cupiditate. Dolor eligendi dolor expedita nulla officiis ad.">
                button one
            </button>
        </div>

        <div class="col-auto">
            <button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Repellat est officia sit optio ad id aut. Odit quos est est. Reiciendis aspernatur nesciunt est eum eligendi. Eveniet ipsam et quia minus voluptatem debitis est.">
                button two
            </button>
        </div>
    </div>
</div>

<script type="text/javascript">
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (el) {
        return new bootstrap.Popover(el, {trigger: "manual"})
    })
    popoverList[0].toggle()
    popoverList[1].toggle()
</script>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.1.3

**Comment by GeoSot** [comment]
Hey @lenormf. Unfortunately, Popper handles automatically the popover elements. We will appreciate if you have any specific proposal on this

**Comment by lenormf** [comment]
My proposal is the issue report:

>It’d be nice if popover windows could be made to reflow automatically whenever they would overlap an adjacent one upon being triggered.

**Comment by mdo** [comment]
I think @GeoSot's comment answers this, you'd have to raise with Popper.
