### ISSUE TITLE
Tooltip: this.tip.querySelector(...) is null

### ISSUE THREAD

**Issue by jwiesler** [twbs/bootstrap#35375]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Changing `data-bs-original-title` of an empty html tooltip to some nonempty string causes [this](https://github.com/twbs/bootstrap/blob/9c0163329f60246452f7b95eae8fa947e83a5d51/js/dist/tooltip.js#L493) `querySelector` to return `null` on hover.

This happens since `_sanitizeAndSetContent` removes the `.tooltip-inner` element and the `tip` does not get updated before while the `isWithContent` check passes now. This might be fixed by regenerating the tooltip on hover.

### Reduced test cases

https://codepen.io/OptimalSloth/pen/NWvJmbE

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.1.3

**Comment by GeoSot** [comment]
I can confirm the case, but it is a bit strange case here. You want an empty tooltip to work, but with a 'custom not documented' way. 

Anyway, Maybe changing this check,  
`this.getTitle() !== this.tip.querySelector(SELECTOR_TOOLTIP_INNER).innerHTML`  
with 
`this.getTitle() !== this._resolvePossibleFunction(this._config.title)`

would help.


I would suggest not to use it, this way, but you can also try to make an MR with proposed changes

**Comment by jwiesler** [comment]
I just want to change the content of the tooltip but setContent is not exported and not documented, even though it exists and searching for a way to do this brings up using this undocumented attribute.

If there is no way, I will just do a MR.

**Comment by GeoSot** [comment]
You are very right on what you said, and I do not know any valid way right now.
I am also trying to launch  #34519 on next version, that may could do the job. You may give it a try

**Comment by jwiesler** [comment]
Ok, I think I will wait for that, thank you.
