### ISSUE TITLE
Add badge-* classes

### ISSUE THREAD

**Issue by AmProsius** [twbs/bootstrap#35408]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

To make the badge component less intrusive, I recommend to add `badge-*` classes to give them a more alert-like style. If  a user wanted a bolder badge, they can always omit the `badge-*` class and style the badges the classic `bg-*` way.

Essentially, the `badge-*` classes would give a style like `background-color: $color-100` and `color: $color-700` with maybe a few tweaks where needed.

**Before**
![badges_before](https://user-images.githubusercontent.com/2817152/143678657-91edb7b7-cfae-43d4-b6d9-772895025e98.jpg)

**After**
![badges_after](https://user-images.githubusercontent.com/2817152/143678658-89f257bb-a7f3-4586-8187-a10e8d716cbe.jpg)

### Motivation and context

There's currently no option to de-emphasize badges with the current utility classes. Also the badge component looks rather outdated and this is an attempt to get back to modern design principles.

As a plus, adding these classes is a non-breaking change and can be applied anytime. If you are interested in the `badge-*` classes, I'd be happy to create a PR.

**Comment by AYB-CHA** [comment]
you can do that using bg-opacity-25 class and the original badge classes 
eg: <span class="badge bg-primary bg-opacity-25">primary</span>. 
thais how I do it.

**Comment by AYB-CHA** [comment]
you can do that using bg-opacity-25 class and the original badge classes 
eg: `<span class="badge bg-primary bg-opacity-25">primary</span>` . 
thais how I do it.

**Comment by AmProsius** [comment]
> you can do that using bg-opacity-25 class and the original badge classes
> eg: `<span class="badge bg-primary bg-opacity-25">primary</span>` .
> thais how I do it.

That may work on a white background, but not so good on a slightly off-white one. Also you can’t change the ‘color’ that way.

**Comment by falcon71** [comment]
I preferred the BS4 way. Now with bg-* we have to adjust the text color manually and badges as links also require additional styling now. It would be nice to have the old badge-* classes back that took care of everything.

**Comment by QuintinWillison** [comment]
Perhaps related but I'm trying to upgrade a site (one I maintain in a personal capacity for a friend of mine, who runs a small business) from BS4 to BS5 and this is a major pain point. I've tried `badge bg-success` and the background colour is simply not being set. I've also tried `text-dark` on top and that doesn't get set either.

I remember a few years ago when I adopted BS4 for this site that everything just worked out of the box and came with sensible defaults. It just worked, mostly. My impression of BS5 is that it's a serious step backwards. I'm on the edge of ditching it and finding something different. I'm not a web developer by trade, so the breaking changes - and lack of any objective help for how to overcome them - are going to _literally_ break me.

Very disappointing. I could go on to complain about the default of underlining links by default too, but I suspect that'll fall on deaf ears. I'm sure there are _reasons_ for all of this but the end result is that this just alienates existing users - those of us just trying to keep our sites alive.

**Comment by crftwrk** [comment]
@falcon71 I preferred BS4 way as well. But you can use `badge btn-danger text-decoration-none` or `badge btn btn-danger border-0` classes to create the same badges in BS5.

**Comment by mdo** [comment]
The badges are largely the same between versions in their overall aesthetics. We dropped some confusing extraneous styles on them and opted to add more explicit controlling to them. Maybe we overdid it, but I think the component is so simplistic overall that it's an often a difficult balance to hit. Providing the utility override though for `color` feels great to me and is definitely an improvement overall.

There's a PR to add additional features via an Extend > Snippets page and I've included lighter colored buttons for that. I can add something there for light colored badges, too. See https://deploy-preview-33627--twbs-bootstrap.netlify.app/docs/5.1/extend/snippets/ via https://github.com/twbs/bootstrap/pull/33627.

```scss
@each $color, $value in $theme-colors {
  $btn-light-bg: shift-color($value, -80%);
  $btn-light-border: shift-color($value, -80%);
  .btn-light-#{$color} {
    @include button-variant($btn-light-bg, $btn-light-border, shift-color($value, 50%));
  }
}
```

**Comment by mdo** [comment]
Two mins of trying it out got me this:

<img width="800" alt="Screen Shot 2021-11-29 at 2 00 19 PM" src="https://user-images.githubusercontent.com/98681/143949657-fbc56a0a-c2fc-40cf-981c-4459ecd0d44d.png">

```scss
@each $color, $value in $theme-colors {
  $badge-light-bg: shift-color($value, -80%);
  .badge-light-#{$color} {
    background-color: $badge-light-bg;
  }
}
```

**Comment by mdo** [comment]
Added to #33627.

**Comment by AmProsius** [comment]
> Tailwind looks amazing.

Be sure to check out the [badge components](https://tailwindui.com/components/application-ui/elements/badges#component-33af74234e5e7ecf9e07993f4bd47449). That's where the inspiration came from anyway.
