### ISSUE TITLE
Bootstrap examples 5.1.3

### ISSUE THREAD

**Issue by temabu** [twbs/bootstrap#35426]
Hi, I am in the process of learning react etc.  I downloaded your examples source code, extracted them and ran npm install followed by npm run.  However, they do not run a temporary server and the examples do not load.

Attached is the output.   Why doesnt it load a server and display the landing page?  Do I misunderstand how the examples would be shown?

[outputerror.txt](https://github.com/twbs/bootstrap/files/7621356/outputerror.txt)

**Comment by temabu** [comment]
I also tried npm start and npm test.  No joy.

**Comment by ffoodd** [comment]
Exemples are static HTML files, there's nothing to install. Just open it in your browser.

**Comment by JamesVanWaza** [comment]
@temabu use the following link - https://react-bootstrap.github.io/getting-started/introduction

**Comment by temabu** [comment]
James thanks. I figured out what I want to do. download the examples sources code, then run VIsualCode.  Open the Bootstrap examples root folder, from the VC menu, run " Terminal->run tasks->npm" 

You will then get a list of npm options (these I think are included in the package.json file?).  Select the task which states "npm: docs-serve" 

This will compile and then run a temporary hugo localhost server (on port 9001) and display the content.

Thats was what I really wanted.
