### ISSUE TITLE
Popover bug

### ISSUE THREAD

**Issue by louismaximepiton** [twbs/bootstrap#35433]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On main branch : 

When a popover is displayed, there's an issue with the arrow, it is not well centered.
![image](https://user-images.githubusercontent.com/91960143/144018072-773266af-ccbb-4f3c-bd0c-a3c44f0aa744.png)

It's maybe related to #34519.

### Reduced test cases

Switch to main branch, `npm run start` and go to Docs > Popovers. Click on any button that displays a popover in the page.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.1.3

**Comment by XhmikosR** [comment]
This is caused by #34519
