### ISSUE TITLE
.btn-close in .modal-header with {direction: rtl}

### ISSUE THREAD

**Issue by louismaximepiton** [twbs/bootstrap#35435]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On main branch : 

Modal's close button doesn't display well in rtl direction.
![image](https://user-images.githubusercontent.com/91960143/144020289-4961121a-62ba-4781-8d01-9ddd0096c232.png)

I think it's related to its margin. I don't know if it just requires a fix for Modals or for other components too.

### Reduced test cases

Switch to main branch, `npm run start` and go to Docs > Modals. Add direction: rtl in any tag that contains a modal.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
You also need to switch to our RTL CSS file. Changing `dir` in markup or `direction` in styles does not trigger any style change.

Please have a look at [the RTL Doc page](https://getbootstrap.com/docs/5.1/getting-started/rtl/).
