### ISSUE TITLE
[Docs] Make SASS variable defaults section more precise

### ISSUE THREAD

**Issue by sfadschm** [twbs/bootstrap#35449]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The docs state how the variable default values work and how we can overwrite them in our own SASS files.
However, it is not possible to overwrite default values with other variable content before importing the variables first (see test cases).

I think this should be extended in the docs, as there are several question around for some time, but this just does not seem to be possible with SASS.

Refs.:
https://github.com/twbs/bootstrap/issues/27338#issuecomment-427959303
https://github.com/twbs/bootstrap/issues/30790

### Reduced test cases

This is the problem test case:

    // 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
    @import "../vendor/twbs/bootstrap/scss/functions";

    // 2. Include any default variable overrides here
    $body-color: #1a171b; // this works
    $body-bg:    $primary; // this gives "Undefined variable"

    // 3. Include remainder of required Bootstrap stylesheets
    @import "../vendor/twbs/bootstrap/scss/variables";
    @import "../vendor/twbs/bootstrap/scss/mixins";
    @import "../vendor/twbs/bootstrap/scss/utilities";

This is a possible approach, but has other downsides and makes the custom SASS quite messy (e.g., if we want to redefine theme-colors this way, we need to call the map-loop function afterwards to make it work):

    // 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
    @import "../vendor/twbs/bootstrap/scss/functions";
    @import "../vendor/twbs/bootstrap/scss/variables";
 
    // 2. Include any default variable overrides here
    $body-color: #1a171b; // this works
    $body-bg:    $primary; // this works, too

    // 3. Include remainder of required Bootstrap stylesheets
    @import "../vendor/twbs/bootstrap/scss/mixins";
    @import "../vendor/twbs/bootstrap/scss/utilities";

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.1.0

**Comment by mdo** [comment]
Yes, this is a limitation of Sass itself, not just Bootstrap. Once a variable has been used, it cannot be updated. That's why you have to put variable overrides before you import the `variables` file. We've since moved our Sass maps into a separate stylesheet to help alleviate some issues here around re-use, but that's coming in v5.2.0. Until then, it's a balancing of your implementation needs and how Sass works.
