### ISSUE TITLE
V5 Utilities: Add Border Style

### ISSUE THREAD

**Issue by nkdas91** [twbs/bootstrap#35464]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can we add utility classes for Border Styles (Ex: ```border-solid```, ```border-dashed```, ```border-dotted```)?

### Motivation and context

Right now, we can only add a Solid border using the utilities. It would be nice to have classes for Border Style as well.

**Comment by ffoodd** [comment]
You can use [the Sass utility API](https://getbootstrap.com/docs/5.1/utilities/api/#add-utilities) to add this. It only requires you to make your own Sass build.

We don't plan to add new utilities in the default build for now, AFAIK.
