### ISSUE TITLE
Add style classes for border and text decoration

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#35485]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

"smarty" style classes: '.double' '.dotted' '.dashed'.
if style class added to element with class `.text-decoration-underline` or `.text-decoration-line-through`, then change `text-decoration-style`, else, `border-style`.
or "utility":
Border style classes (change `border-style`): '.border-double' '.border-dotted' '.border-dashed'
Text decoration style classes (change `text-decoration-style`): '.text-decoration-double' '.text-decoration-dotted' '.text-decoration-dashed'.

### Motivation and context

We already have have utilities for border and decoration of text, but can't change decoration/border style by that's utilities

**Comment by amankumar11** [comment]
I would like to work on this issue.

**Comment by WinterSilence** [comment]
@amankumar11 What you mean? Sending PR adding something like this:
```scss
    "border-style": (
      property: border-style,
      class: border,
      values: double dotted dashed
    ),
    "text-decoration-style": (
      property: text-decoration-style,
      class: text-decoration,
      values: double dotted dashed
    ),
```
to `scss/_utilities.scss`?

**Comment by amankumar11** [comment]
Yes

**Comment by mdo** [comment]
We'll pass on this for now as the Utility API exists for this very reason.

**Comment by WinterSilence** [comment]
@mdo
> "smarty" style classes: '.double' '.dotted' '.dashed'.
if style class added to element with class .text-decoration-underline or .text-decoration-line-through, then change text-decoration-style, else, border-style.
