### ISSUE TITLE
Animation of progress bar is not working

### ISSUE THREAD

**Issue by vjdv** [twbs/bootstrap#35499]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Animated stripes are not working, looks like `progress-bar-animated` is not having any effect.

The same can be noted in [official documentation](https://getbootstrap.com/docs/5.1/components/progress/#animated-stripes).

### Reduced test cases

<div class="container py-5">
  <h1>Progress Bar</h1>
  <p>Animation on stripes of progress bar is not working/moving</p>
  <div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
  </div>
</div>

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
Animations are working fine. Did you change your system setting regarding animation ans/or performance?

We have [a little explainer about `prefers-reduced-motion` in the accessibility docs](https://getbootstrap.com/docs/5.1/getting-started/accessibility/#reduced-motion).

**Comment by ffoodd** [comment]
Feel free to comment back if I'm missing something, but AFAIK it's working fine in our docs.
