### ISSUE TITLE
v5: Offcanvas ESC keypress doesn't prevent default

### ISSUE THREAD

**Issue by Moeriki** [twbs/bootstrap#35490]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Pressing "Escape" in an open Offcanvas closes it. But the event is propagated to the browser which (ao) makes the browser leave fullscreen mode.

This behaviour is correct in other overlay components such as dropdown and modal.

### Reduced test cases

https://codepen.io/moeriki/pen/rNGLBvW

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari, Firefox

### What version of Bootstrap are you using?

v5.1.3

### Fix

The fix _might_ be just adding `event.preventDefault()` here…

https://github.com/twbs/bootstrap/blob/main/js/src/offcanvas.js#L194

**Comment by GeoSot** [comment]
Hey @Moeriki, can you help my a bit more to replicate this? I tried to put my browser on fullscreen & the 'pen' itself but didn't find something there :/

**Comment by Moeriki** [comment]
Do you mean the Codepen doesn't load? It was the first time trying codepen so I'm not sure I did it right.

Alternatively you can open the Offcanvas bootstrap docs and replicate the issue as reported just the same.

https://getbootstrap.com/docs/5.1/components/offcanvas/#live-demo

1. Set browser in fullscreen
2. Open the offcanvas
3. Press "Escape"

**Comment by GeoSot** [comment]
Excuse me for the inconvenience. I meant, I couldn't replicated 
Unfortunately on my win10, chrome & Firefox & edge I cannot replicate this, either on docs demo or the codepen example 

Probably winnows toggle browser with F11. So if you can replicate it using another example, I will appreciate it

**Comment by Moeriki** [comment]
Ah I see. It might be a macOS issue only then. Fullscreen on macOS is something more native to the OS than on Windows I think.

I know it's probably not very clear but here's a video.

https://user-images.githubusercontent.com/38758/145655857-368f9587-a7b0-424f-a33f-92333695ad85.mp4

Googleing for this issue does reveal a handful of questions and answers pointing towards `event.preventDefault()`.

https://stackoverflow.com/questions/20916109/prevent-esc-key-from-exiting-fullscreen-app-mode-on-website

Looking at the code of the Offcanvas, compared to eg. the Dropdown and Modal, this does add up. For the latter 2 components (where `preventDefault` is called) this exit-on-escape is not the case.

**Comment by Moeriki** [comment]
Closed for perfectly viable work-around.

```ts
onMounted(() => {
  function preventEscape(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      event.preventDefault();
    }
  }

  window.addEventListener('keydown', preventEscape);

  return () => {
    window.removeEventListener('keydown', preventEscape);
  };
});
```

This is Vue.js code. Run this in the root of your App.
