### ISSUE TITLE
Suggest a new feature

### ISSUE THREAD

**Issue by alirezakasirzare** [twbs/bootstrap#35502]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

hello 

please add to carousel tochable

### Motivation and context

carousel come to best version !

**Comment by XhmikosR** [comment]
Not sure what you mean?

**Comment by alirezakasirzare** [comment]
i say the bootstrap carousel can not touch in mouse just touch in scrool bar 

i need the carousel can touch with mouse like smart phone

**Comment by XhmikosR** [comment]
Touch is supported just fine in carousel, if that's what you mean. If you mean something else, please try to explain it better.
