### ISSUE TITLE
`npm i bootstrap@next` or `yarn add bootstrap@next` is currently working?

### ISSUE THREAD

**Issue by mirumirumi** [twbs/bootstrap#35521]
I tried `npm i bootstrap@next` on a clean project and got the following. Of course, I want to use bootstrap 5.

```sh
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bootstrap@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mirumirumi/.npm/_logs/2021-12-10T13_42_16_152Z-debug.log
```

The tutorial below describes `npm i bootstrap@next`, 
https://getbootstrap.jp/docs/5.0/getting-started/download/#npm

but npmjs.com says: 
`npm i bootstrap`
https://www.npmjs.com/package/bootstrap

What is the status of this?

**Comment by WinterSilence** [comment]
@mirumirumi something strange with dns npm.com redirect to nasdaq

**Comment by mirumirumi** [comment]
sorry, i fixed

**Comment by mirumirumi** [comment]
@WinterSilence  sorry, i fixed

**Comment by WinterSilence** [comment]
@mirumirumi `npm install bootstrap` install latest/5.1.3 version

**Comment by mirumirumi** [comment]
@WinterSilence What do you mean?
I asked if the "@next" written in the tutorial was correct.

**Comment by WinterSilence** [comment]
@mirumirumi use [official tutorial v5](https://getbootstrap.com/docs/5.1/getting-started/download/#npm)

**Comment by mirumirumi** [comment]
@WinterSilence 
Aah! It's just that the Japanese site was in an incorrect state. I'm very sorry about that.
I appreciate your response!
