### ISSUE TITLE
order-* classes don't work, only order-first and order-last do their job

### ISSUE THREAD

**Issue by geerdes** [twbs/bootstrap#35524]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Using Bootstrap 5.1.3 I got into an issue with the `order-*` classes.

Having 5 columns inside a `row` and the last `col` got an `order-2` class, the last div is not changing position.

### Reduced test cases

This is my code:
<pre>
&lt;div class=&quot;container&quot;&gt;
  &lt;div class=&quot;row gy-3&quot;&gt;
    &lt;div class=&quot;col-md-6 col-xl-4&quot;&gt;1&lt;/div&gt;
    &lt;div class=&quot;col-md-6 col-xl-4&quot;&gt;2&lt;/div&gt;
    &lt;div class=&quot;col-md-6 col-xl-4&quot;&gt;3&lt;/div&gt;
    &lt;div class=&quot;col-md-6 col-xl-4&quot;&gt;4&lt;/div&gt;
    &lt;div class=&quot;col-md-6 col-xl-8 order-2&quot;&gt;5&lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</pre>

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by florianlacreuse** [comment]
The default value for `order` property for a flex child is `0`.

Your code is the same as:

```scss
<div class="container">
  <div class="row gy-3">
    <div class="col-md-6 col-xl-4 order-0">1</div>
    <div class="col-md-6 col-xl-4 order-0">2</div>
    <div class="col-md-6 col-xl-4 order-0">3</div>
    <div class="col-md-6 col-xl-4 order-0">4</div>
    <div class="col-md-6 col-xl-8 order-2">5</div>
  </div>
</div>
```

What you need for instance:

```scss
<div class="container">
  <div class="row gy-3">
    <div class="col-md-6 col-xl-4 order-0">1</div>
    <div class="col-md-6 col-xl-4 order-1">2</div>
    <div class="col-md-6 col-xl-4 order-3">3</div>
    <div class="col-md-6 col-xl-4 order-4">4</div>
    <div class="col-md-6 col-xl-8 order-2">5</div>
  </div>
</div>
```

**Comment by geerdes** [comment]
Ah, that should bei mentioned in the Docs, thank you
