### ISSUE TITLE
Problem with CDN, expire ssl certificate

### ISSUE THREAD

**Issue by Terxeno** [twbs/bootstrap#35526]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

It's trouble load CSS file from https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css because expire SSL certificate frome **Sectigo Limited**
Certificate expire Tue, 12 Oct 2021 23:59:59 GMT

### Reduced test cases

https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

4.4.1

**Comment by ffoodd** [comment]
We do not recommend to use StackPath anymore. Please [use JSDelivr instead, as we now mention in the docs](https://getbootstrap.com/docs/4.6/getting-started/introduction/).
