### ISSUE TITLE
Bootstrap 5 + Jquery animate scrollTop laggy on Chrome only

### ISSUE THREAD

**Issue by fire0594** [twbs/bootstrap#35536]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Bootstrap 5.1.3 and Jquery 3.6.0 scrollTop animation not start immediately after click on Chrome, but works normlly on other browser(Firefox).
Sometimes the animation start after a while (maybe 500 ms) after click, sometimes it start with slow speed then as normal.

### Reduced test cases

I tried this minimal code below (Bootstrap 5.1.3) and the problem appears. I also tried several code with other versions of Bootstrap (from 5.0.0 to 5.1.2) and the problem still appears.

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>
  <body>
    <div class="bg-secondary" style="height:2500px;"></div>
    <p class="mb-0 text-center"><a href="javascript:;" id="scroll-top" class="text-dark text-decoration-none">Back to Top</a></p>
  </body>
  <script>
    $(document).ready(function (){
      $("#scroll-top").click(function() {
        $("body,html").animate({
          scrollTop: 0
        },500);
      });
    });
  </script>
</html>
```

I tried another code below (older version of Bootstrap 4.6.1), animation works normally.

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>
  <body>
    <div class="bg-secondary" style="height:2500px;"></div>
    <p class="mb-0 text-center"><a href="javascript:;" id="scroll-top" class="text-dark text-decoration-none">Back to Top</a></p>
  </body>
  <script>
    $(document).ready(function (){
      $("#scroll-top").click(function() {
        $("body,html").animate({
          scrollTop: 0
        },500);
      });
    });
  </script>
</html>
```

So this problem may only appears on Bootstrap 5 and Chrome, I have no idea what caused it and how to fix it.

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by crftwrk** [comment]
jQuery scroll script has conflict with `scroll-behavior: smooth` in `_reboot.scss` line 33. Just override it with css.

```css
html {
  scroll-behavior: auto !important;
}
```

**Comment by ArthurShlain** [comment]
You can also add inline style using jQuery `css()` method:

```js
$(document).ready(function (){

  $("html").css('scroll-behavior', 'auto');

  // click handler here

}};
```

**Comment by XhmikosR** [comment]
If anyone thinks this should be in our docs, please make a PR. Thanks!

**Comment by adrienfr** [comment]
Hi guys, FYI I encountered an issue with Behat tests when upgrading to Bootstrap 5 and it seems Panther users have the same issue, see https://github.com/symfony/panther/issues/502. 
@crftwrk's fix solved my issue, thanks!

**Comment by ffoodd** [comment]
To disable smooth scroll, I'd recommend you set `$enable-smooth-scroll` to `false` in a custom Sass build.

Since there's a core option to handle this and a simple CSS workaround, I'm closing this for now.

FWIW `scroll-behavior` is standard CSS, so I'd say the jQuery plugin should support it.

**Comment by Gawrion** [comment]
Lol. I was migrating from 4 to 5. I changed my code, classes, scripts... Many hours of not creative work that i hate :D Finally I find out that my scrollTop animations are not working good with my custom easings... Another 3 hours of scratching my head... Finally got here :D Ty for explaining the problem cause :D
