### ISSUE TITLE
Carousel currently swipes in the opposite direction on mobile

### ISSUE THREAD

**Issue by johnhorsema** [twbs/bootstrap#35531]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When swiping on the carousel, the items are moving opposite the direction the swipe action is taken.
For example, when doing a right-swipe, the items move to the left.

I suggest a toggle in the carousel option named `animate-as-swipe` where the developer can provide a boolean value to indicate the animation direction should be the same as swipe direction.

### Reduced test cases

https://codepen.io/johnhorsema/pen/oNGYZgJ

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.0

**Comment by GeoSot** [comment]
Did you try the latest version 5.1.3?

**Comment by johnhorsema** [comment]
Hi @GeoSot that did the trick. Upgrading to 5.1.3 fixed the issue.
