### ISSUE TITLE
bootstrap-rtl.min.css -->modal--> Does not display

### ISSUE THREAD

**Issue by mb-real** [twbs/bootstrap#35530]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Only the bootstrap-rtl.min.css library has the problem that it does not display modal

Note the file I uploaded. Indicates a problem
[index.txt](https://github.com/twbs/bootstrap/files/7697979/index.txt)

### Reduced test cases

noting

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
Please make your test case usable, by uploading it to CodePen or similar.

FWIW [modals work fine in the RTL cheatsheet](https://getbootstrap.com/docs/5.1/examples/cheatsheet-rtl/#modal) so I'll close the issue until you're able to describe an issue or give an actual reduced test case.
