### ISSUE TITLE
Nested containers in Bootstrap 5 have extra space added to the left and right margins

### ISSUE THREAD

**Issue by JSieffert** [twbs/bootstrap#35541]
The behavior of nested containers has changed from Bootstrap 4.6 to 5. Previously nesting containers with zero-padded columns would properly remove/add the proper padding to the container element.

I've attached two "html" examples. Run both of these in a browser and you will see the difference in behavior.

[bootstrap-5-example.txt](https://github.com/twbs/bootstrap/files/7714425/bootstrap-5-example.txt)
[bootstrap-4.6-example.txt](https://github.com/twbs/bootstrap/files/7714426/bootstrap-4.6-example.txt)

**Comment by WinterSilence** [comment]
use gap, for example: `row g-0` instead `p-0`

**Comment by JSieffert** [comment]
Using gutters on the row causes these two containers to overlap each other. Using padding on child containers compounds this issue. There must be an incorrect calc somewhere in the mixins causing this issue.

**Comment by WinterSilence** [comment]
@JSieffert I'm mean you problem in diff between `$container-padding-x:` and `$grid-gutter-width`:
~~~scss
$container-padding-x: $grid-gutter-width * .5 !default;
~~~

**Comment by WinterSilence** [comment]
@JSieffert but this problem happened because you wrap nested `.row` in redundant `.container`
https://getbootstrap.com/docs/4.6/layout/grid/#nesting
https://getbootstrap.com/docs/5.1/layout/grid/#nesting

**Comment by JSieffert** [comment]
It's not a redundant container. The outer container is fluid to span the width of the page and the child container is not fluid so the content panel is width constrained. 

In my example it uses the exact same code and just includes different versions of bootstrap.

Is there somewhere in the documentation that i missed that explains this difference?

**Comment by WinterSilence** [comment]
@JSieffert 
1. `.container`: padding-left/padding-right:  gutter-width
  `.row`: margin-left/margin-right: -0.5 * gutter-width
  `.col`: padding-left/padding-right:  0.5 * gutter-width
2. classes like as `.p-*` changes CSS of current tag and no effect on CSS of inner tags

let's calculate horizontal padding/margin of nested tag, set `gutter-width: 1` for example:
`col p-0`:  padding 0, margin 0
 `container`: padding +1 margin 0
`row`: padding 0 margin -0.5
 `col p-0`: padding 0 margin 0
as total, `.col > .col `: 1 padding  - 0.5 margin = 0.5

**Comment by JSieffert** [comment]
@WinterSilence 

I appreciate you trying to explain this to me but it doesn't solve my issue.

In BS 4.6 I was able to used distinct div.containers anywhere on the page, including nested inside each other if need be and have the padding helper classes behave consistently. 

The padding helper class p-{#} has always worked simply by removing/adding the appropriate spacing inside the div.col. This appears to have changed in BS 5. The padding helper classes still work as designed if the div.container doesn't have another nested div.container. Nesting div.containers causes these helper classes to miscalculate the negative margins causing unwanted space to be rendered in the col.p-0.

We can debate how all of these calculations should or shouldn't happen but ultimately I'm looking for a bug report to be generated, a working example showing how I'm using this incorrectly, or possibly something added to the published documentation (or migration documentation) better explaining the change or how it always behaved.

**Comment by WinterSilence** [comment]
> This appears to have changed in BS 5. 

You incorrect used classes in BS4, you still do it in BS5. Fact that default values of SASS variables has changed does not mean that class behaviors has changed.

**Comment by ffoodd** [comment]
Would you mind embedding your code examples in CodePen or something, please? I'm still unsure what you mean and try to do.

**Comment by WinterSilence** [comment]
@ffoodd By default, in BS5
https://github.com/twbs/bootstrap/blob/4a66f229ed701d4ed8d6d5b7469984ab11d822f0/scss/_variables.scss#L470
in BS4 `$container-padding-x: $grid-gutter-width` (it's not real code, simply code to comparison)

**Comment by JSieffert** [comment]
**Bootstrap 4.6 Nested Containers**
https://codepen.io/jsieffert/pen/poWeMme

**Bootstrap 5 Nested Containers**
https://codepen.io/jsieffert/pen/vYexovP

**Comment by WinterSilence** [comment]
@JSieffert add `.bg-success` to containers may be it's help you understand. I have already tried all variants

**Comment by JSieffert** [comment]
I'm convinced this is a bug and have generated a new codepen to illustrate the problem.

This example uses the example code from the [BS 5 Grid page](https://getbootstrap.com/docs/5.1/layout/grid/). 

I've only added borders to the containers, rows, and cols to help you understand the problem.
https://codepen.io/jsieffert/pen/MWEmWZW

Both of these containers should look the same but the nested container gets some extra padding.

![BS-5-Containers](https://user-images.githubusercontent.com/46004112/146429504-87c99d80-358e-456f-9695-c92e6e04446e.PNG)

If I'm using anything wrong in this example then it's wrong in the documentation.

**Comment by WinterSilence** [comment]
@JSieffert 
> This example uses the example code from the BS 5 Grid page.

it's not true

**Comment by JSieffert** [comment]
Okay. I understand the intended use for the grid. Nesting div.containers is not supported.

My point was that previously, by dumb luck it appears, nested containers were working.

**Comment by WinterSilence** [comment]
@JSieffert
> Nesting div.containers is not supported.

"works not as I'm think" not same to "not supported" + "changes in variable defaults" not same to "changes in behavior"
Why don't you understand that variables can be changes? You can customize BS as you wish.

**Comment by JSieffert** [comment]
@WinterSilence 

Nesting the container control shouldn't cause it to behave differently. 

The code sample I provided shows the padding utility class is ignored when it is applied to a column of a nested container. It didn't do this prior to version 5. 

Do what you will with this information.

**Comment by hadrien-thomas-zenika** [comment]
I'm adding some extra opinion on this matter as I'm struggling with this too.

I use a framework where my html is split in several components which I want autonomous and reusable everywhere in my app.
Including nesting each other.

Therefore, I want their code to be independant of each other.
If I want that, I want to repeat container class in each one of them so the behaviour is right wherever I use it in my app.
If I was to remove container from a parent component, then it would obviously affect the child, which is not good.

The documentation is really lacking examples on that subject, which I face everytime I use boostrap grid system because its behaviour seems erratic between versions (for the same reason mentioned here: we are maybe not using it as intended).

Nevertheless, I'm pretty sure many many bootstrap users would like to know how to address that issue.
Who has a single page html in their code in 2022?

Anyone having tips?

Thanks in advance for your reply.

**Comment by JSieffert** [comment]
Very well stated @hadrien-thomas-zenika! This is the exact problem I'm having. I don't always know if I have a parent container. Nested or not I expect the UI control to behave the same.

**Comment by ffoodd** [comment]
Please open a new issue and provide a test case, so that we have a chance to help.

This specific issue was closed before any team member could answer anything helpful. 

I mostly think you'd need to handle your global layout and your inner layout separately, but without knowing anything about your goals and constraints there's no chance anyone could help.

**Comment by arifulmamun** [comment]
Using BS5 nested grid row-col cause problem. Col is not stack on it's position. Can anyone resolve this issue. I'm using BS5 CDN not download my assets folder.
![bs5 nested grid row and col](https://user-images.githubusercontent.com/98890931/212467330-3fad3a18-b129-444c-8efc-415e926c7384.jpg)
![nested grid row and col](https://user-images.githubusercontent.com/98890931/212467349-2efa06b3-860e-4580-b67e-07e80c6743c2.jpg)
