### ISSUE TITLE
Line height rendering issue on Chromium 94+ and higher, and Firefox.

### ISSUE THREAD

**Issue by pricop** [twbs/bootstrap#35553]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hey guys,

Not sure if you were aware, but starting with Chromium 94.0.4584 and higher, the Chromium got a fix related to the way they were calculating line-heights: https://chromium-review.googlesource.com/c/chromium/src/+/2824938

This change affects all Blink based browsers (Chrome, Edge, Opera, etc), but also Firefox.

Safari is NOT affected by this.

So what happens in recent versions, they're including the subpixels of line-height (when a line height has subpixels) when calculating the container's total height.

This comes with an unexpected behavior, which breaks any pixel perfect designs when using classes that have a line-height set to a ratio based unit, unless the `line-height` value calculated happens to be a number with no decimals.

I've created 2 simple tests that which can be seen at:

16px base font on the Browser's settings: https://codepen.io/pricop/pen/ExwWZJZ
17px base font on the Browser's settings: test: https://codepen.io/pricop/pen/bGoqgZJ

I've took screenshots of each of them, and measured what the browser has rendered, and the results are as follows:

16px results: https://i.imgur.com/swLGjh4.png
17px results: https://i.imgur.com/h3eOZZi.png

The culprit in this particular case, is the "small" helper class that Boostrap includes. This class has the `font-size` set to `80%`. When a browser has the default font size set to 16px (which is what the vast majority of browsers have), the line-height in newer versions will not be floored, as in previous versions, so rather than the `line-height` being calculated at `19px`, it is now calculated at `19.2px`, which causes the issues presented in the results.

The fix would be have the `line-height` for classes that are using ratio based values (such as `small`, `display-*`, etc. classes) to a value with no decimals when the browser's calculates it.

This issue can be followed at: https://bugs.chromium.org/p/chromium/issues/detail?id=1278566 - but by the looks of it, this is something that's here to stay, and I've been instructed to adjust my CSS instead.

### Reduced test cases

https://codepen.io/pricop/pen/ExwWZJZ
https://codepen.io/pricop/pen/bGoqgZJ

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

4.0.0 but it affects all the others.

**Comment by folknor** [comment]
Can you please drag and drop the screenshots you linked into a github comment? First of all I have no reason to trust imgur. Secondly, their servers are apparently too busy anyway so I can't see the images.

**Comment by pricop** [comment]
![Chrome BS4 16px](https://user-images.githubusercontent.com/920945/147116757-9a8e0bb3-e87d-409e-9d3d-ccc49c943727.png)
![chrome BS4 17px](https://user-images.githubusercontent.com/920945/147116758-58cd7aaa-faa4-4cb9-ab7c-4243a4f340c8.png)

**Comment by mdo** [comment]
I see a computed height of `69.2` when hovering over the DOM nodes in Chrome's web inspector (Chrome v100.x). Safari renders it as `69` even.

Do you still see this with the latest Chrome? Is it the computed height shown in inspector tools that's the issue, or a rendered height that's different than that shown value?

**Comment by pricop** [comment]
I hope you're doing well. Yes, the issue persists with the latest version of Chrome.

Safari still does line-height clamping like Chrome used to do (which was to round down the computer height), but they'll probably eventually switch to the same render method Chromium and Gecko do.

The 69.2 height value that you're seeing, is the correct computed height. However, since the browser can't render .2s of a pixel, it has it rounds the number down when rendering for some of the columns, and the remaining sum of decimals are being added (I presume arbitrary) to other columns so that the final container has the correct height.

In the example provided, the ```small``` class from Bootstrap 4 has the height set to 80%. 80% of 16 is 12.8, added with the rest of the heights paddings and borders equals to 69.2.

By setting the ```$small-font-size``` to ```.875rem``` (for 14px) or ```.8125rem``` (13px), the height becomes a round number, which fixes this issue.

Boostrap 5 already uses REM units and is not affected by this. I see no reason why this couldn't be backported to Bootstrap 4.

**Comment by mdo** [comment]
Want to open a new PR to change the small font-size?

**Comment by pricop** [comment]
Done.
