### ISSUE TITLE
font size class is working in reverse order fs-1

### ISSUE THREAD

**Issue by rahulsureshiringal** [twbs/bootstrap#35557]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have checked bootstrap-5,

In the document,
fs-1 = small
..
fs-6 = big

But actually it working in reverse order,

fs-1 = big
..
fs-6 = small

### Reduced test cases

f

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.0

**Comment by XhmikosR** [comment]
The docs say `fs-1` is the big one: https://getbootstrap.com/docs/5.1/utilities/text/#font-size
