### ISSUE TITLE
v5.2 Alert color is disabled

### ISSUE THREAD

**Issue by cccabinet** [twbs/bootstrap#35569]
The alert setting was changed to a CSS variable in #35401, but the alert color is disabled.

ｖ5.1.3（https://getbootstrap.com/docs/5.1/components/alerts/#examples）
![v5 1 3 Alerts](https://user-images.githubusercontent.com/26200725/146645341-3aa22d94-30f6-4455-9e8c-9d586b9632b6.png)

ｖ5.2.0（https://deploy-preview-35401--twbs-bootstrap.netlify.app/docs/5.1/components/alerts/#examples）
![v5 2 0 Alerts](https://user-images.githubusercontent.com/26200725/146646020-3639dccb-c764-4d6f-8520-71a424222737.png)

Please correct it.

**Comment by ffoodd** [comment]
You're right, there're at least two errors we didn't catch:
- `--bs-alert-color` is weirdly set with padding values in the defaults,
- `color` isn't set anymore.

We need to set `color`, and we may drop the default declaration since it's not needed.
