### ISSUE TITLE
scrollspy with nested divs and hidden nav links

### ISSUE THREAD

**Issue by svenignor** [twbs/bootstrap#35567]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Situation:
navigation:

```html
<ul class="nav nav-pills">
  <li class="nav-item d-none d-md-block"><a href="#c1" target="_self" class="nav-link active">c1</a></li>
  <li class="nav-item d-block d-md-none"><a href="#c2" target="_self" class="nav-link">c2</a></li>
  <li class="nav-item d-block d-md-none"><a href="#c3" target="_self" class="nav-link">c3</a></li>
</ul>
```

it could be splitted into 2 different navs - one for case 1 and one for case 2

elements to observe:

```html
<div class="container">
  <div id="c1" class="row">
    <div id="c2" class="col-12 col-md-6">left or top content</div>
    <div id="c3" class="col-12 col-md-6">right or bottom content</div>
  </div>
</div>
```

### Motivation and context

on desktop, there will be shown some links targeting the "rows" due to the horizontal alignment of the cols.
on mobile, there will be shown some links targeting the "cols" due to their vertical alignment.
It doesn't make much sense to target the "rows" on mobile - their content may be too large for one anchor

Is it possible to achieve this with the given functionality of scrollspy?
if not, may it be a possible feature for a request?

**Comment by mdo** [comment]
This seems as much of a how-to question as it does a feature request, so I'm not sure how to proceed. I also don't have a clear idea of what you're asking for because there is no live demo or approximation of your request.

If you're willing and able to better explain, we can revisit.
