### ISSUE TITLE
Recommend cdnjs instead of jsdelivr ( or both are provided ) in document ?

### ISSUE THREAD

**Issue by JoeHorn** [twbs/bootstrap#35578]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

My website has layout problem because of SSL certificate error occurred on jsDelivr.

They said ( on twitter , ref. https://twitter.com/jsDelivr/status/1472870623051456522 ) :
> Unfortunately today jsDelivr unexpectedly lost its ICP license in China. As effect the regional CDN disabled our account.
> 
> This resulted in the extended outage we had in mainland China and Taiwan.
> 
> Other regions were unaffected.

Then I found resources on cdnjs may help.
Ref. https://cdnjs.com/libraries/bootstrap

May you please provide this info. on document ?

Thanks anyway.

### Reduced test cases

None

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.6.1

**Comment by jimaek** [comment]
The issue with jsDelivr was limited to mainland China and was quickly fixed by routing all Chinese traffic to a different CDN. If you still have issues you need to purge your DNS cache.

**Comment by JoeHorn** [comment]
> The issue with jsDelivr was limited to mainland China and was quickly fixed by routing all Chinese traffic to a different CDN. If you still have issues you need to purge your DNS cache.

Yes, the issue was resolved.
Thanks for your contribution and works.

I meant the document on Bootstrap official site.
Reference to the document on jQuery official site , they provide more than one CDN.
( https://jquery.com/download/#using-jquery-with-a-cdn )

BTW, Chinese traffic to jsDelivr now routed to Fastly, but ICMP RTT was not so good ( as before ).

**Comment by XhmikosR** [comment]
We don't have any plans on offering any other CDN at this point. I strongly believe @jimaek can solve any issues that might arise :)
