### ISSUE TITLE
Syntax error in bootstrap javascript

### ISSUE THREAD

**Issue by eugenedonaghy** [twbs/bootstrap#35570]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello  Dreamweaver has identified a syntax error in the javascript 

 const toType = obj => {
    if (obj === null || obj === undefined) {
      return `${obj}`;
    }

the error is on the top line  looks like a missing curly bracket somewhere where about how can this error be corrected

### Reduced test cases

link to code picture  https://gyazo.com/236abef62d8e2643e79153e7e45e69ed

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.1.3

**Comment by XhmikosR** [comment]
The code is fine, update your tools to work with arrow functions, or use another tool.
