### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by foofoo5** [twbs/bootstrap#35576]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On the documentation page, "Position," in the section "[Fixed Top](https://getbootstrap.com/docs/4.0/utilities/position/#fixed-top)," there is a spelling error: "you may need to add aditional CSS."

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

4.0

**Comment by florianlacreuse** [comment]
Hi,

Good catch but this typo has already been fixed: https://twbs-bootstrap.netlify.app/docs/5.1/helpers/position/#fixed-top

**Comment by ffoodd** [comment]
Closing per last comment—thanks to both of you !

**Comment by foofoo5** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/18026179/146808476-d8361d38-defc-4e60-82b2-8b61d40f7e10.png">

Not to be rude, but I am looking at the [section](https://getbootstrap.com/docs/4.0/utilities/position/#fixed-top) I previously described in real time and the error has not been corrected.

**Comment by florianlacreuse** [comment]
Arg sorry, I didn't notice. I'll fix it on v4 for you. Thanks!

**Comment by florianlacreuse** [comment]
It is fixed in the latest version of the BS4 doc: https://getbootstrap.com/docs/4.6/utilities/position/#fixed-top
