### ISSUE TITLE
Refresh Modal Body

### ISSUE THREAD

**Issue by math-boy11** [twbs/bootstrap#35581]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I think Bootstrap's Modals should refresh every time the modal is shown so the inputs are refreshed.

### Motivation and context

The inputs are kept the same every time the modal is shown. These inputs are kept the same because css is using visibility. It would be pretty easy to fix in the main javascript.

**Comment by folknor** [comment]
Holy smokes. I also have forms in modals and I hadn't even tested it properly :-) Thank you for the heads up.

**Comment by GeoSot** [comment]
As modal is agnostic of its content, how is it possible to 'refresh' this content, and how ideally would be achieved?

**Comment by folknor** [comment]
I appreciate that there's no real way of "fixing" this that doesn't potentially cause problems for others, and also any attempt would likely require a major version bump.

But the simple solution for me is something like (pseudocode, untested, etc):

```js
function reset(modal) {
	modal.querySelectorAll("input").forEach(el => {
		if ( typeof el.checked === "boolean" ) {
			el.checked = el.defaultChecked
		} else {
			el.value = el.defaultValue
		}
	})
}
```

**Comment by florianlacreuse** [comment]
IMHO, this is not a job to be done by Bootstrap itself.

**Comment by ffoodd** [comment]
I tend to agree. You're already able to listen to [modal events](https://getbootstrap.com/docs/5.1/components/modal/#events) and make anything you need.

BTW if that's applicable I'd recommend you use the `formData` API and its `reset` instead of overriding values.

@GeoSot Your call to close this or try something, but my opinion is we already provide what's needed here.

**Comment by math-boy11** [comment]
You could also just add a show listener to the modal and then reset the HTML like this:
`
myModal.addEventListener('shown.bs.modal', function () {
var body = myModal.querySelector('.modal-body')
  body.innerHTML = body.innerHTML;
})
`

**Comment by GeoSot** [comment]
I am glad, we came up to an agreement (and you gave me an idea for #34043 :smile: )
