### ISSUE TITLE
Make a dark theme for the docs

### ISSUE THREAD

**Issue by MadhanDevlpr** [twbs/bootstrap#35582]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

It will be fulfilled if you do this

### Motivation and context

Make it faster

**Comment by ffoodd** [comment]
Duplicates #29720.
