### ISSUE TITLE
Version 5.3 not having the {property}{sides}-{breakpoint}-{size} rules on NPM package

### ISSUE THREAD

**Issue by felipearmat** [twbs/bootstrap#35597]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

PROBLEM:
Rules like {property}{sides}-{breakpoint}-{size} pointed on the [documentation](https://getbootstrap.com/docs/5.0/utilities/spacing/) are not working on version 5.1.3 when using scss imports with npm package.

POSSIBLE REASONS:
I might be equivocated, but it seems that the file _spacing.scss, that is present on [version 4.6](https://github.com/twbs/bootstrap/blob/v4.6.1/scss/utilities/_spacing.scss) is missing on version 5.3.
There's no other place where the rules like {property}{sides}-{breakpoint}-{size} are set, so maybe it is actually a bug.
Or it might be some problem with the /mixins/_utilities.scss logic wich I couldn't identify.

POSSIBLE SOLUTION:
Adding the same file as the version 4.6 and importing it on the main scss file does make rules {property}{sides}-{breakpoint}-{size} work again. Maybe revisiting the  /mixins/_utilities.scss file might be an issue also.

### Reduced test cases

Should create a hello world using any scss pre-processor and using scss import for bootstrap.
There, elements with the class "px-sm-3" shouldn't work properly

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Opera

### What version of Bootstrap are you using?

v5.1.3

**Comment by XhmikosR** [comment]
These are still there, they have been renamed in v5.0.0: https://getbootstrap.com/docs/5.1/migration/#utilities

**Comment by arnaud-deprez** [comment]
Hi @XhmikosR,

I think this issue should be reopened.
For some reasons the class is not present when using `sass` directly but I can indeed see the class `px-sm-3` for instance in the non minified css.

**Comment by ffoodd** [comment]
We're using Sass to compile our dist files and they are compiled, so either you have an issue with your setup (e.g. something like purgecss working after Sass) or you're disabling utilities in some way.
