### ISSUE TITLE
Offcanvas navbar expand leaves stray overlay

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#35594]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A follow-up from https://github.com/twbs/bootstrap/issues/35577 - in the same scenario (an offcanvas navbar with `.navbar-expand-${breakpoint}`), if the offcanvas is opened, but then the browser window is resized, the offcanvas disappears but the semi-transparent overlay remains.

/cc @florianlacreuse 

### Reduced test cases

https://codepen.io/florianlacreuse/pen/wvreVxN

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by patrickhlauke** [comment]
Video of the issue

https://user-images.githubusercontent.com/895831/147275224-9c9b4c65-ffae-4a24-9600-acc5b6b3aaef.mp4

**Comment by patrickhlauke** [comment]
Solution likely involves some kind of resize listener somewhere that toggles the proper "close the offcanvas" logic. Unless we feel it's too much of an edge case...

**Comment by GeoSot** [comment]
Note: In case of a resize listener we might want to address #33561 too

**Comment by florianlacreuse** [comment]
Also related to #34720.

**Comment by mdo** [comment]
This should be fixed with the JS changes coming in #35736.
