### ISSUE TITLE
Customized css does not have -webkit-appearence: none for form-select

### ISSUE THREAD

**Issue by shaozi** [twbs/bootstrap#35614]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When customize bootstrap with sass, class `.form-select` does not have `-webkit-appearence: none;` in final css. That makes the select uses the default style in Safari. See screenshot.

<img width="369" alt="Screen Shot 2021-12-27 at 5 25 09 PM" src="https://user-images.githubusercontent.com/417833/147512866-12da22f1-54e8-42f8-bb58-cd4e4aa9d263.png">

### Reduced test cases

use `customize.scss` with a simple import:

```scss
@import 'bootstrap';
```

To work around the issue, add the missing style:

```scss
@import 'bootstrap';
.form-select {
  -webkit-appearance: none;
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v5.1.3

**Comment by XhmikosR** [comment]
You need to use autoprefixer when you are building the CSS yourself as our docs mention: https://getbootstrap.com/docs/5.1/getting-started/download/#source-files
