### ISSUE TITLE
Drop Down Z-Index Changes When Appearing on the Top vs the Bottom

### ISSUE THREAD

**Issue by nathanjoyes** [twbs/bootstrap#35626]
When the drop down menus on this page appear on the bottom of the button, they appear behind other objects on the page, and are unable to be clicked on. When unable to open below, the menu pops above the button and is functional. Only significant observable change is in the element's custom style. Below it is: 'inset: 0px auto auto 0px', and above is 'inset: auto auto 0px 0px'.

Attached are a couple of sample images of the effect.

![Screenshot from 2021-12-31 11-48-09](https://user-images.githubusercontent.com/22805022/147833756-d6dfc556-6aa7-470f-b791-07e34fbcfa9e.png)

![Screenshot from 2021-12-31 11-48-20](https://user-images.githubusercontent.com/22805022/147833758-89e45d10-b746-43b4-9ea7-277b079ff1b6.png)

**Comment by pandeyprashant123-coder** [comment]
i am new in open source i think i can solve this isse can i work on it

**Comment by nathanjoyes** [comment]
That would be great. I as well am new to filing issues with GitHub, and applying fixes in the Open Source community.

What else do you need to look at fixing this issue?

**Comment by GeoSot** [comment]
It would help as all to include a reduced test case, replicating the bug you found.

You may start using this template https://codepen.io/team/bootstrap/pen/qBamdLj

**Comment by pandeyprashant123-coder** [comment]
> It would help as all to include a reduced test case, replicating the bug you found.
> 
> You may start using this template https://codepen.io/team/bootstrap/pen/qBamdLj

this is great help thank you

**Comment by pandeyprashant123-coder** [comment]
but how can I access that bug tempelete

**Comment by ffoodd** [comment]
You need to log into Codepen using your GitHub account, then you should be able to fork the bug template (using the "Fork" button in the bottom right corner). Then set the HTML that's not working and try to reproduce your issue there.

Thank you :)

**Comment by nathanjoyes** [comment]
I was able to replicate the bug in a [CodePen](https://codepen.io/njoyes/pen/NWazLaQ), it is not until the custom CSS is applied to the page that the issue appears, so not likely a bootstrap bug.

I am going to continue to debug to see if I can figure this out.

**Comment by nathanjoyes** [comment]
The transform and margin-bottom custom styling for html .row elements were the cause of this issue. I have resolved in my project by rebuilding the source css that was overriding the bootstrap values.

Thank you everyone who took a look and helped out moving this forward.
