### ISSUE TITLE
Name issues in component documentation

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#35646]
Why are so many names in the component document plural? Is there any special meaning?
Is it good to be unified?

such as

|    plural    |
|:------------:|
|    Alerts    |
|   Buttons    |
|  Dropdowns   |
|     tabs     |
| Placeholders |
|   Popovers   |
|   Spinners   |
|    Toasts    |
|   Tooltips   |

**Comment by aryankeluskar** [comment]
Since Bootstrap has multiple types of buttons or toasters, they use plural for those words.

**Comment by mdo** [comment]
Definitely just something we haven't locked in on with a single way of naming. Honestly it's all just ad hoc and I go with what sounds right hah. We'll look again in v6 though because the same applies to our Sass partials.
