### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by hlam812003** [twbs/bootstrap#35643]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The problem with navbar text color 
So i have the issue today's when I use the class of navbar ( navbar-light ) but the text color is dark and the ( navbar-dark ) but the color is turn into white. Here is my picture 
![image](https://user-images.githubusercontent.com/68631787/147911379-123d24ec-a7e4-4861-95e4-3e71b2a39350.png)
![image](https://user-images.githubusercontent.com/68631787/147911440-a24e0f76-a255-43bb-861c-7ae47611dfde.png)
![image](https://user-images.githubusercontent.com/68631787/147911465-4ed8c52d-e2c6-47de-81b6-7031848c5422.png)

### Reduced test cases

https://codepen.io/hlam812003/pen/JjrvjRR

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v4.5.2

**Comment by nkdas91** [comment]
@hlam812003 

```.navbar-light``` and ```.navbar-dark``` classes are used to specify whether the Navbar's **"background color"** is dark or light. So, if we have a Navbar with a dark background, we should use a light **"text color"** and vice versa.

It is an expected behaviour to have a white text color on a dark Navbar (```.navbar-dark```) and a dark text color on a light Navbar (```.navbar-light```)

**Comment by ffoodd** [comment]
Indeed. Closing this per last comment.
