### ISSUE TITLE
Button group styles incorrectly when end buttons are hidden

### ISSUE THREAD

**Issue by rconnaughton** [twbs/bootstrap#35660]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If the first button of a button group is hidden for a given screen resolution, I expect the "new" first button in the group to be styled as the first button (ie rounded corners).   Instead, the button is still styled as a middle button, with sharp corners.    Same occurs for the last button.

### Reduced test cases

From the button group docs, the original example is 
```
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-primary">Left</button>
  <button type="button" class="btn btn-primary">Middle</button>
  <button type="button" class="btn btn-primary">Right</button>
</div>
```

modifying this to 
```
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-primary d-none d-sm-block">Left</button>
  <button type="button" class="btn btn-primary">Middle</button>
  <button type="button" class="btn btn-primary">Right</button>
</div>
```
and shrinking the browser window reproduces the issue at the xs resolution

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.0

**Comment by ffoodd** [comment]
It's barely impossible to take such cases into account, since it'd need to handle when the first / last is hidden, then the two first / last, etc.

I'd recommend using our utilities to accomplish this. That's a case for responsive `border-radius` utility, so I'm keeping this open for now.

**Comment by anubhav2102** [comment]
Hey! Can i work on this issue?

**Comment by mdo** [comment]
Closing per @ffoodd's comment. Agreed that it's extremely difficult to build completely bulletproof button groups with this in mind.
