### ISSUE TITLE
New Border classes

### ISSUE THREAD

**Issue by Dayer5** [twbs/bootstrap#35669]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap has already added "border-top-0", "border-bottom-0", "border-start-0" and "border-end-0" but it should also allow changing the 0 to other numbers from 1-5.

### Motivation and context

This will make changing the thickness of one specific side of the border much easier.

**Comment by ffoodd** [comment]
It already exists, you can eg. combine `.border-bottom` and `.border-3`. Check out [border utilities documentation](https://getbootstrap.com/docs/5.1/utilities/borders/#border-width).
