### ISSUE TITLE
Utilities: separate text color from background color

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#35693]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

For better color themes support, users need to be able to use different colors in text and background. How it's currently implemented:
```
.text-primary {
    --text-opacity: 1;
    color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity));
}

.bg-primary {
    --bg-opacity: 1;
    color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity));
}
```

If i override `--bs-primary-rgb` in `.text-primary`, the following scenario fails:
```
<div class="bg-primary bg-opacity-25 text-primary">
```
Because `.bg-primary` also inherits new RGB value. In dark theme, text color should be lighter than background color. And current implementation makes it impossible to apply different color without introducing a new color map for text color specifically and a bunch of new color classes. 

### Motivation and context

To improve theming support

**Comment by ffoodd** [comment]
This scenario is supposed to fail since `primary` represents a color and you're using the same for background and foreground.

There's no need to allow finer tuning since this use-case does not match how and why our utilities (and color palette) work.

Simply use another utility for one of tour color.

**Comment by Kopyov** [comment]
Why is it suppose to fail? What if primary color is very dark red? In that case in dark theme, dark red text won't be visible, but background color will be. Having an ability to adjust lightness of primary color would be very useful. 
And using another utility for primary text color is not a solution. What's the point of introducing CSS variables for better customization, if color customization is very limited?

**Comment by ffoodd** [comment]
You're using the same color token for background **and** foreground, what do you expect as a result?

**Comment by Kopyov** [comment]
but that's the point :) Let's say I use $blue-500 for both text and background colors in light theme. In dark theme I would like to make the text a bit lighter by using $blue-300 and keep background with $blue-500. How it is currently implemented - if i change global $primary to $blue-300, I also need to update .text-white and other classes/elements so that their colors are fully inversed.
And by changing text color to lighter tint, I can adjust contrast ratio so that it doesn't fail when main colors are inversed.
