### ISSUE TITLE
checkbox button (outlined) doesnt seem to function correctly on iOS

### ISSUE THREAD

**Issue by edmandell** [twbs/bootstrap#35690]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have used checkbox buttons to select a bunch of flags on my website and it seems to work ok on Windows 10 and Linux browsers but it doesnt seem to work correctly on iOS devices (ipad and iphone). I've tried Safari and Chrome on iOS and both appear to be the same

1. Click the button first time and the button is selected i.e. the background colour changes
2. Click the button a 2nd time (to unselect it) and on ios it remains selected but on anything else it becomes unselected i.e. the background goes back to being clear (which is what expect)

### Reduced test cases

http://mandell.org.uk/tester.html

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Safari and Chrome

### What version of Bootstrap are you using?

v5.0

**Comment by edmandell** [comment]
Same problem on Android

**Comment by edmandell** [comment]
worked around the issue

**Comment by 505-notfound** [comment]
how did you solve this issue? im having trouble...

**Comment by edmandell** [comment]
it was a while ago, but I think I did something with putting the checkbox inside the label, here's some of my code (php), it gave me what I needed 

    echo "<div class='btn-group' role='group'>\n";                  
        echo    "<div class='col'>\n";
        $items = $data['nose']['primary'][$tag];
        foreach ($items as $item) {
            echo "<label class='btn btn-sm btn-outline-primary' for='{$item['html_id']}'>{$item['attr_name']}\n";
            echo "<input type='checkbox' class='form-check-input' name='nose-primary' id='{$item['html_id']}' value='{$item['html_id']}'>\n";
            echo "</label>\n";
        }

        echo    "</div>\n";
        echo  "</div>\n";
