### ISSUE TITLE
Boostrap grid only module

### ISSUE THREAD

**Issue by Enzodtz** [twbs/bootstrap#35691]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Unfortunately, when we are installing bootstrap, we need to import all the css that comes with it. And this is bad, because sometimes I would like to have my own styles, but using bootstrap's awsome grid system.

Ex: anchor underlines, text paddings, nav tags usage and etc.

It would be nice to separate the style and the layouting, to remove unnecessary imports.

### Motivation and context

I'm developing a resposive strongly UI based website to have its own design, but I need bootstrap's respositivity, and unfortunately, when I've added it, I needed to override a bunch of bootstrap styles with `!important` flag. And there are ones that I may not even notice.

**Comment by florianlacreuse** [comment]
`bootstrap-grid.css` should do the job?

* https://getbootstrap.com/docs/5.1/getting-started/contents/#css-files
* https://github.com/twbs/bootstrap/blob/main/scss/bootstrap-grid.scss

Or you can make your own scss file: https://getbootstrap.com/docs/5.1/customize/sass/

**Comment by ffoodd** [comment]
Closing this per last comment. This is already doable and documented.
