### ISSUE TITLE
Multiple Select layout does not show current selections

### ISSUE THREAD

**Issue by arcanisgk** [twbs/bootstrap#35701]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Multiple Select layout does not show current selections:
on the BS documentation and examples page [Link](https://getbootstrap.com/docs/5.1/forms/select/)

When clicking on more than one option, only the last one remains blue (Selected):

click first option:
![image](https://user-images.githubusercontent.com/1207306/150208347-dd47f157-d58d-4bad-8761-521adc5c112e.png)

after clicking a second option:

![image](https://user-images.githubusercontent.com/1207306/150208445-22435e94-4cba-4862-9779-ae7df81bcd69.png)

the first option lost the blue color or the gray color (when it is out of focus).

### Reduced test cases

tested in bootstrap doc site [Link](https://getbootstrap.com/docs/5.1/forms/select/).

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.X

**Comment by florianlacreuse** [comment]
On Windows users must press and hold the ctrl key to select multiple values.

**Comment by arcanisgk** [comment]
> On Windows users must press and hold the ctrl key to select multiple values.

I'm almost sure, that it's not the expected functionality, having to press CTRL to select multiple functions... is counterintuitive...

**Comment by florianlacreuse** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#selecting_multiple_options

**Comment by arcanisgk** [comment]
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#selecting_multiple_options

I still think it's counterintuitive... if bootstrap is supposed to work on mobile devices where there is no physical keyboard. as the user is supposed to do the multiple selection.

**Comment by florianlacreuse** [comment]
On mobile devices it's an other behavior, you can try it.

**Comment by mdo** [comment]
Yeah, there's nothing we're doing to multiple selects. This is browser behavior as mentioned.
