### ISSUE TITLE
Popover + Tooltip : js error multiple instances with selector option.

### ISSUE THREAD

**Issue by florianlacreuse** [twbs/bootstrap#35710]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using `selector` option for both popovers and tooltips this way:

```js
new bootstrap.Tooltip(document.body, {
  selector: '[data-bs-toggle="tooltip"]'
});

new bootstrap.Popover(document.body, {
  selector: '[data-bs-toggle="popover"]'
});
```

We get the following js error (check browser console to see the error):

> Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.

https://github.com/twbs/bootstrap/blob/520cc8de92ca48d7ac60102d992d7afe9788b239/js/src/dom/data.js#L16-L28

Because we use `document.body` in both cases.

### Reduced test cases

https://codepen.io/florianlacreuse/pen/jOaNzVm

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by florianlacreuse** [comment]
This code alone selects several elements but it doesn't throw an error:

```js
new bootstrap.Tooltip(document.body, {
  selector: '[data-bs-toggle="tooltip"]'
});
```

By adding this code that selects several different elements we get the error:

```js
new bootstrap.Popover(document.body, {
  selector: '[data-bs-toggle="popover"]'
});
```

I never instanciate a tooltip AND a popover for the same element.

**Comment by GeoSot** [comment]
Probably it is the document.body element

You are trying to initialize two different components on the same element

**Comment by florianlacreuse** [comment]
If I am not mistaken i'm not trying to initialize two different components on the same element. I'm trying to intialize one tooltip (or more) and one popover (or more) but never on the same element. As in my reduced test case, no element has both attributs `data-bs-toggle="tooltip"` and `data-bs-toggle="popover"`.

I need `document.body` because I need to select all the `data-bs-toggle="tooltip"` and all the `data-bs-toggle="popover"`  in the current page (always on different elements).

The pattern `document.body` + `selector` option is used in [this informative example](https://codepen.io/team/bootstrap/pen/zYBXGwX?editors=1010) provided by Bootstrap (from docs).

**Comment by GeoSot** [comment]
Yes you are right, but unfortunately, this is a big trick.
You firstly try to initialize one instance on document.body, and during initialization, you ask it to be aware of these selectors. 

You may try to initialize them on a different element than body

To be honest it would be redundant if we had figure an idea of document listeners over selectors, but it is something that needs planning as tooltip can be triggered on focus|hover|click|manual and we do not have selectors for this differentiation

**Comment by florianlacreuse** [comment]
First of all, thank you for your help. I am pleased that we agree on this tricky issue.

Trying to bypass the check by using different elements than `body` seems to be a hack.

Maybe we shouldn't do any verification / check when using the `selector` option because it's almost impossible to know what's going on? Like this code should be ignored in this case (just a quick idea, I don't know if it's smart):

https://github.com/twbs/bootstrap/blob/957c1dd6eaacc7a8b17a68ecb78b3134d449b5c1/js/src/dom/data.js#L22-L28

Moreover, on the other hand, it is possible to fool the verification with two different elements instead of "`document.body`" and two different `selector` options actually targeting the same element.

**Comment by GeoSot** [comment]
These are deep water changes, specially for a minor version. Let's stay to safety. The real hack is the "selector" thing, so you'd better follow the standard way , that can initialize everything

```js

var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
tooltipTriggerList.forEach(function (tooltipTriggerEl) {
  bootstrap.Tooltip.getOrCreateInstance(tooltipTriggerEl)
})
```

**Comment by HybridSolutions** [comment]
Sorry to bring this up again, but using Blazor and the selector option is really required for both the components to work since most of the times elements may not be present on the page. So, if I can't use this

```
new bootstrap.Tooltip(document.body, {
            selector: '[data-bs-toggle="tooltip"]'
        });

        new bootstrap.Popover(document.body, {
            selector: '[data-bs-toggle="popover"]'
        });
```

what is the official alternative since this is the approach mentioned in documentation?

Thank you in advance!

**Comment by pallu** [comment]
Same problem as @HybridSolutions.

**Comment by florianlacreuse** [comment]
We are on the same boat with this one. On my side it's with the Java framework Apache Wicket, a lot of dynamic contents (ajax), many elements may also not be present on the page on init.

**Comment by Nudasoft** [comment]
Any solution for this?

**Comment by florianlacreuse** [comment]
Unfortunately no (afaik).

**Comment by HybridSolutions** [comment]
> for those looking for a solution, it should be easy enough to add a delegated listener for mouse overs and initialize things on the fly no ?
> 
> otherwise, I can offer this solution: https://bs-companion.vercel.app/bs-toggle.html the idea is to wrap your html with a custom element that will take care of initializing the tooltip or popover himself. that kind of solution is very easy and you don't need to know the content of the page in advance.

Does it work with elements that don't even exist in DOM yet?

**Comment by lekoala** [comment]
@HybridSolutions that's precisely the point. you inject through ajax the html element wrapped in the custom element, and the browser will initialize everything by himself without need of any custom callback or js code. it's basically set it and forget it.

**Comment by WinterSilence** [comment]
@GeoSot they want something like this `$('#main-content').on('...', '[data-bs-toggle="tooltip"]', function (event) {...})`

**Comment by GeoSot** [comment]
As I am aware of, on 5.2.2 it works ok. 

The suggested workaround of @lekoala, works too, as it handles the initialization of each new instance by itself


@WinterSilence do I miss something else?

**Comment by WinterSilence** [comment]
@GeoSot same way: my example attach event handler to container and calls for inner tooltips. it's "expensive", but no need re-attach events after every AJAX request

**Comment by guillaumebriday-pa** [comment]
Hey @florianlacreuse @GeoSot any solutions since last time? 👍 

The documentation still refer to https://codepen.io/Johann-S/pen/djJYPb saying that we can do:

```js
$('body').popover({
  selector: '.has-popover'
})
```
But we can't do `popover` and `tooltip` at the same time

**Comment by gokhanozgezer** [comment]
If anyone still has problems, this solution solved my problem.

```
document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach((el) => {
    new bootstrap.Tooltip(el)
})

document.querySelectorAll('[data-bs-toggle="popover"]').forEach((el) => {
    new bootstrap.Popover(el)
})
```

**Comment by evlo** [comment]
that does not solve actual issue with popover and tooltip at the same element at all
another example, that does not use two data-toggle properties would be
```
const popoverTriggerList = document.querySelectorAll('.popover-form-edit-link');
const popoverList = [...popoverTriggerList].map(popoverTriggerEl => {
new bootstrap.Popover(popoverTriggerEl)
}
```
```
const tooltipTriggerList = document.querySelectorAll('.tooltip-form-edit-link');
const tooltipList = [...popoverTriggerList].map(tooltipTriggerEl => {
new bootstrap.Tooltip(tooltipTriggerEl)
}
```
while `.tooltip-form-edit-link`  and `.popover-form-edit-link` are on the same element.

I think using two data-toggle properties one elements might be more confusing as I do not think that is valid?
