### ISSUE TITLE
dropdown list item for nav bar not linking to other pages

### ISSUE THREAD

**Issue by AubreySine0** [twbs/bootstrap#35728]

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by AubreySine0** [comment]
I have created a reduced test case here:
https://codepen.io/aubreysine/pen/qBVJwaX
<https://urldefense.com/v3/__https://codepen.io/aubreysine/pen/qBVJwaX__;!!NCc8flgU!NjEQWU4f8f7A_1Q9oouQHw6_H7iaGtjNa6Nc2AY13yG2bsNaLzCmItJqC9S5$>
.

The issue is that the dropdown menu item will not redirect to other pages
of the website. I can only reference other areas inside the given HTML
file.
*Aubrey Sine  *
Solutions Architect
<https://segment.com/>
EMAIL ***@***.***
