### ISSUE TITLE
Dropdown autoClose="false" close on ESC, but shouldn't

### ISSUE THREAD

**Issue by sirpatrick2** [twbs/bootstrap#35756]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

According to the documentation example on:
https://getbootstrap.com/docs/5.1/components/dropdowns/
Setting autoClose="false" and pressing ESC shouldn't close the dropdown. But actually it closes by pressing ESC button.
See also the example "Manual Close" on
https://getbootstrap.com/docs/5.1/components/dropdowns/#auto-close-behavior

### Reduced test cases

See also the example "Manual Close" on
https://getbootstrap.com/docs/5.1/components/dropdowns/#auto-close-behavior

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by devCharaf** [comment]
.

**Comment by ffoodd** [comment]
That's the expected behaviour. The doc mentions clicking outside, not disabling `Esc` key.

When navigating with the keyboard, the `Esc` key is the most common and used way to close components, and an actual requirement regarding ARIA design patterns. In other words, the `Esc` key should always close the component.

**Comment by sirpatrick2** [comment]
Ok, reading further on the doc I am reading that setting autoClose to false, the dropdown will not be closed by pressing the ESC key. Maybe this sentence conlicts with ARIA design requirements.
Thanks in any case.

<html>
<body>




autoClose | boolean \| string | true | Configure the auto close behavior of the dropdown:true - the dropdown will be closed by clicking outside or inside the dropdown menu.**false - the dropdown will be closed by clicking the toggle button and manually calling hide or toggle method. (Also will not be closed by pressing esc key)**'inside' - the dropdown will be closed (only) by clicking inside the dropdown menu.'outside' - the dropdown will be closed (only) by clicking outside the dropdown menu.
-- | -- | -- | --



</body>
</html>

**Comment by ffoodd** [comment]
Oh Indeed, I missed this sentences. I think the docs should be updated then, thanks for pointing this out!
