### ISSUE TITLE
Problem with Samsung Internet Browser and CSS

### ISSUE THREAD

**Issue by assachs** [twbs/bootstrap#35760]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The following problem can be reproduced with Android Samsung Internet Browser. I cannot reproduce the problem with google chrome (android). I think it's a bug of Samsung Internet Browser, but maybe there is a solution to circumvent the problem. I also reported the bug to Samsung.

If you click a button( `[button type="button" class="btn btn-primary"] xxCancel [/button]`)  and the next element contains a number, the dialer of the smartphone opens. 

I tracked down the problem to "user-select: none" which is part of the btn-class.

### Reduced test cases

https://api.volley.de/b2/index-ohne.html

### What operating system(s) are you seeing the problem on?

Android

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by assachs** [comment]
Html was removed:  [button type="button" class="btn btn-primary"] xxCancel [/button]

**Comment by mdo** [comment]
I don't believe we support the Samsung browser explicitly, correct @XhmikosR? I also don't have another device to test this specific browser either. Feels like a won't fix.

**Comment by XhmikosR** [comment]
Typically, it's supported since it's Chromium-based, but I don't use it either. Your best bet is to report the issue to Samsung.
