### ISSUE TITLE
no events to track transitions when using carousel-fade

### ISSUE THREAD

**Issue by michaeladamkatz** [twbs/bootstrap#35762]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This is somewhere between a bug and a feature request, but I think it's missing a basic use case, so I'm calling it a bug.

When I use `carousel-fade`, I no longer receive `slide.bs.carousel` and `slid.bs.carousel` events. That's a problem because I want to add some effects to the text as each new slide is shown. I understand that the slide didn't actually slide, so I don't know if it's better to use those event names as-is, or create new events `fade.bs.carousel` and `faded.bs.carousel`.

### Reduced test cases

Create a carousel with a div header like:

`<div id="MainPageCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-pause="false">
`
Add JavaScript:

```
	document.getElementById( "MainPageCarousel" ).addEventListener( "slide.bs.carousel", HandleCarouselSlide );
	document.getElementById( "MainPageCarousel" ).addEventListener( "slid.bs.carousel", HandleCarouselSlid );
```

and

```
function HandleCarouselSlide()
{
	console.log( "slide" );
}

function HandleCarouselSlid()
{
	console.log( "slid" );
}
```

When the page loads, those event handlers are never called as the carousel transitions from one slide to another.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.0

**Comment by GeoSot** [comment]
@michaeladamkatz please try to provide a 'working' demo to help us debug there
