### ISSUE TITLE
add a range component with two handle

### ISSUE THREAD

**Issue by saeednoruzi** [twbs/bootstrap#35779]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

add a range component with two Handel for setting min range and max range

### Motivation and context

most of times when people try to filter products by  price they want to set a minimum price and maximum price for the products there for we really need something like jquery UI range component of course with more options and customization and we want to use only bootstrap library not others

**Comment by ffoodd** [comment]
Duplicates #33945 and #33639.

We already declined the feature request, there's no need to open the same one.
