### ISSUE TITLE
Consider changing the logic of CSS variables

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#35783]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Spent some time reviewing the logic of CSS variables that you guys implemented, and i'm constantly facing a problem with an ability to re-use variables globally, especially in custom components. This leads to a very heavy bundle size and tons of repeated and hardcoded values in production.

The problem here is CSS variables are not re-used in SASS variables. This means all color values are in HEX/RGBa, all spacing values are in REM, sizes are in PX. While i understand the goal to provide extra customization options that don't require build process, customization itself will become a real mess. A simple example would be if you want to override border radius globally in all components, you need to do it in each component by changing values in component-specific '[component]-border-radius' variables. This for sure will lead to a huge bundle size. And if you also need to introduce dark theme, for color vars you need to do it twice.

The proposal here would be why don't we extend global CSS variables, such as border-color, border-radius, component-active-bg|color, color theme etc. And simply re-use them in values of SASS variables? In that case instead of this:

```
// SASS variables
$modal-content-bg:                          $white;
$modal-content-border-color:         $border-color;
$modal-content-border-width:        $border-width;
$modal-content-border-radius:       $border-radius;

// CSS variables
--#{$variable-prefix}modal-content-bg: #{$modal-content-bg};
--#{$variable-prefix}modal-content-border-width: #{$modal-content-border-width};
--#{$variable-prefix}modal-content-border-color: #{$modal-content-border-color};
--#{$variable-prefix}modal-content-border-radius: #{$modal-content-border-radius};

// Modal CSS
.modal-content {
  background-color: var(--#{$variable-prefix}modal-content-bg);
  border: var(--#{$variable-prefix}modal-content-border-width) solid var(--#{$variable-prefix}modal-content-border-color);
  @include border-radius(var(--#{$variable-prefix}modal-content-border-radius));
}
```

... we can simply have this:

```
// Root CSS variables
--#{$variable-prefix}border-width: #{$border-width};
--#{$variable-prefix}border-color: #{$border-color};
--#{$variable-prefix}border-radius: #{$border-radius};

// SASS variables
$modal-content-bg:                          var(--#{$variable-prefix}white);
$modal-content-border-color:         var(--#{$variable-prefix}border-color);
$modal-content-border-width:        var(--#{$variable-prefix}border-width);
$modal-content-border-radius:       var(--#{$variable-prefix}border-radius);

// No CSS variables on component level

// Modal CSS
.modal-content {
  background-color: $modal-content-bg;
  border: $modal-content-border-width solid $modal-content-border-color;
  @include border-radius($modal-content-border-radius);
}
```

This solution gives same customization options, but here at least you can now change border-color or border-radius globally for all components at once. And if you want to customize border-radius for modal only, you can override root variable in .modal-content class individually. The benefit also would be a very clean CSS with much less repeating CSS variables.

Before you push CSS variables, please consider a different logic as what it is now will bring devs lots of headache.

### Motivation and context

To improve the logic of CSS variables, reduce bundle size and provide developers a cleaner and more readable code

**Comment by mdo** [comment]
While I understand what you're going for, I think the answer is ultimately somewhere between your suggestion and our direction. I've known for a long time we need more root level variables and those are coming. Once those are in place, we can make better use of them throughout our Sass and more. However, I still plan to ship CSS variables to each component. More and more should end up using CSS variables though in their values. I'm just not 100% sure the timing or exactly implementation yet.

**Comment by mdo** [comment]
Cross referenced this with my tracking issue for implementing CSS variables. Will circle back as our approach evolves :).

**Comment by Kopyov** [comment]
thanks @mdo .
I actually tried that locally and it's working just fine, with a few exceptions. There are certain issues, but nothing that can't be fixed.
One thing popped up that was breaking build process (apart from color functions) - calculations in SASS, e.g.:

```
// Margins
margin-left: -$btn-border-width;

// Size
padding-left: $btn-padding-x * .75;
```

If we change that to this:
```
// Margins
margin-left: calc(#{$btn-border-width} * -1);

// Size
padding-left: calc(#{$btn-padding-x} * .75);
```
we can use both CSS and SCSS vars. Would be also handy when #35428 is merged and we can re-use `--bs-border-width` in component vars. I can create a PR in addition to that one and replace border calculations with calc(), if that makes sense
