### ISSUE TITLE
[FEATURE] automatic-class-sorting-with-prettier

### ISSUE THREAD

**Issue by daniel007enirman** [twbs/bootstrap#35799]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

something like https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

### Motivation and context

This plugin scans your templates for class attributes containing Bootstrap CSS classes, and then sorts those classes automatically following our recommended class order

**Comment by WinterSilence** [comment]
it's only sugar to do `class` attribute more readable, this no any effects on element's style

**Comment by ffoodd** [comment]
Indeed, this is not related to Bootstrap core.

If anyone wants to give it a shot, feel free to create a repo and mention it here. ❤️

**Comment by mdo** [comment]
Closing for low priority—happy to see any PRs if folks want this :).

**Comment by Hnnx** [comment]
I wish we had some sort of ordering standard to follow. Making Inline styles more readable is not low priority :(
