### ISSUE TITLE
Scroll spy on body breaks page when no scrollbar present

### ISSUE THREAD

**Issue by AvWoN** [twbs/bootstrap#35796]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**The issue**

When adding scrollspy to the body element with something like `<body data-bs-spy="scroll" data-bs-target="#navbar-scrollspy" data-bs-offset="0" tabindex="0">` the page will break when there is no scroll bar and be fine if there is a scrollbar. This becomes a problem when you don't know if the viewport will be able to fit the full page or if it needs a scrollbar. The error in console:

```
Uncaught TypeError: i is null
    _activate scrollspy.js:224
    _process scrollspy.js:191
    An scrollspy.js:80
    <anonymous> scrollspy.js:283
    <anonymous> scrollspy.js:283
    i event-handler.js:102
    N event-handler.js:207
    on event-handler.js:241
    <anonymous> scrollspy.js:281
    <anonymous> bootstrap.bundle.min.js:6
    <anonymous> bootstrap.bundle.min.js:6
```

**What is expected to happen**

The page should behave the same way if the page is fully displayed and if the page has a scrollbar.

**What exactly breaks**

Not sure, something in scrollspy but the main issue for me is that it inexplicably deletes `active` class from nav-link items in an unrelated (nothing points to it) `<ul>` masthead with nav.

**Sharing initial findings**

- Missing element of `data-bs-target` is not the root issue. The correct nav and nav-link targets can exist on the page, but **IF** (the nav-link element target, e.g. the element with `<div>id="about"</div>` targeted by `<a class="nav-link " href="#about">`, does not exist ) **&&** ( the html fits in the viewport) **THEN** scrollspy breaks. It basically breaks when both: no nav-link item is present, declared or undeclared, and when the page does not have a scroll bar.

I could avoid this being an issue if I only enabled scrollspy in `<body>` on pages that actually utilize it but with my current suboptimal but simple php templating structure which has a "top.php" (html, body, header) and "bottom.php" (footer, /body, /html) structures it is a bit much to change the entire structure and flow of this site to address this unique bug. I would expect it to work on my pages that utilize it and on my pages that do not utilize it.

**Why should this be fixed, a potential valid use case separate from mine:**

Lets say someone has a scrollspy activated on body because they will utilize it on the page, but the page is not fully populated yet so for now viewport fits the entire page (*X*). But upon further user input the page shows new content and the scrollspy is refreshed by the page as specified and the scrollspy is engaged. Problem is the page already broke where I marked the (*X*).

### Reduced test cases

Reduced test case: https://codepen.io/avwon/pen/GRONdbd (reload page when resizing to show a scrollbar or when to show the entire page)

How to test:

- **NO BREAK (browser resized for scrollbar to show)**
![22-02-06_10-14-41_explorer(2022-02)](https://user-images.githubusercontent.com/61403188/152697653-0f0d3a43-a75d-46e1-be45-310a2d832cc8.png)
 
- **BROKEN (browser resized for no scrollbar)**
![22-02-06_10-14-21_firefox(Bootstrap_v5_Bug_Report_Template_—_Mozilla_Firefox)](https://user-images.githubusercontent.com/61403188/152697649-c6ff94fe-6e97-4c00-afe3-8320ad543ce2.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.3

**Comment by AvWoN** [comment]
I slightly misdiagnosed the cause of the issue. Its not that there does or doesn't need to be a scroll bar for it to break. Its that when you reach the end of the page and don't have any targets it will break.

So it comes down to, should we be able to enable the scrollspy `<body>` without actually utilizing it on the page and have it not break itself?

**Comment by AvWoN** [comment]
Thank you @GeoSot,

Tried it on my project, replaced:
```<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>```
with:
```<script src="https://deploy-preview-33421--twbs-bootstrap.netlify.app/docs/5.1/dist/js/bootstrap.bundle.js"></script>```

The uncaught type error is no longer triggered when reaching the end of page on pages not utilizing it.
But, the Scrollspy no longer functions as it did before on pages utilizing it, it is now simply stuck (active nav-link) on my second item no matter where I am on the page as soon as the page is loaded in.

**Comment by GeoSot** [comment]
Can you provide me a demo to help me debug it?

**Comment by AvWoN** [comment]
https://codepen.io/avwon/pen/GROWEMb

Sorry, was busy. So, I basically copied and pasted 80% of my site. You can see that when your preview script is enabled the second item is active right out of the get go but starts functioning properly once you start scrolling. If you go down to the bottom and swap it to 5.1.3 release it will not be active on page load and behave as expected.

**However,** I was not able to replicate the other bug with this that I am experiencing on my project where for me it does not get unstuck at all even tho its almost the exact same page layout. The only difference is that I have a script which populates part of the document after the page is loaded. Perhaps there is an additional bug that happens after you make element additions to the document which makes scrollspy stop tracking all together. It works as expected if I used 5.1.3 release.

**Comment by GeoSot** [comment]
Thank you for this demo.

If you use scrollspy.refresh() in both cases, it should re-calculate everything

_As for the preview version, you helped me debug,  the problem is caused because IntersectionObserver  scans  whole `body` (observable) , and body is not restricted in vh. So it pick ups the latest item in view. I 'll try to hack it a bit._

**Comment by AvWoN** [comment]
I will try refreshing scrollspy in a bit, thanks!
Small correction to what I said earlier, on my personal project my scripts that generates additional DOM elements are executed before the bootstrap bundle is executed since scripts are executed in order they are encountered in the page. So I am still not sure why there is a different behavior between the codepen (gets stuck on item 2, unstuck when scrolling) and my personal project (gets stuck on item 2, remains stuck when scrolling), but hopefully one is just the byproduct of the other and the current fix you are working on fixes both.

**Comment by GeoSot** [comment]
If you achieve to replicate the issue on your codepen demo, I could give it a look. Thanks again for your help

**Comment by GeoSot** [comment]
To be honest, I do not want to get involved with the existing scrolspy implementation, as I am trying to get approval for the IntresectionObserver implementation (the last 6 months :P), and it is so close. 

As for the difference, I think is the IntresectionObserver that picks the first element, but I cannot figure out a solution, yet

**Comment by AvWoN** [comment]
Oh okay, got it. If I have the the time I will see if I can reproduce the perma stuck situation with another codepen eventually and then we can leave it at that until you get the opportunity/approval to implement what you need.
