### ISSUE TITLE
JS bootstrap error on mobile.

### ISSUE THREAD

**Issue by JoaoEmanuell** [twbs/bootstrap#35803]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello, having an error when using the bootstrap javascript.

In the desktop browser when clicking on the icon of the 3 bars of the navbar it expands and collapses without any problem, but on mobile it does not work at all.

So I decided to connect my cell phone to the pc to use chrome inspect and check the console, here I come across the following error:

![Captura de tela de 2022-02-07 17-59-18](https://user-images.githubusercontent.com/81983803/152872903-f91b8351-9702-4866-8632-14e6716592fc.png)

I'm using the cdn javascript and css code that is available in the documentation, I also tried to use the code by downloading it and adding it directly to my code, but the error persists.

The navbar example is also the same as the documentation, only changing the color palette, depending on the color palette used I have another error.

In both cases the error is as follows:

```
Uncaught SyntaxError: Unexpected token ...
```

![Captura de tela de 2022-02-07 18-06-03](https://user-images.githubusercontent.com/81983803/152873265-f1a4b7d5-6898-4eb7-8c9b-56da2b81e03c.png)

The error is found on line 1851 of the bootstrap.js file

Note: I used python to open the server on the local network to be able to access it with my cell phone.

Note 2 : I tested it on 3 different browsers, chrome, the default cell phone and via it, and on 2 different cell phones, both reported the same error.

Note 3 : All javascript code works normally except bootstrap code.

Thanks for listening! 

### Reduced test cases

[Html Code](https://github.com/JoaoEmanuell/Meus-Estudos-HTML5-CSS-JS/blob/master/Bootstrap%20erro/index.html)

### What operating system(s) are you seeing the problem on?

Android

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
What are your Android and Chrome for Android versions, please?

**Comment by JoaoEmanuell** [comment]
> What are your Android and Chrome for Android versions, please?

I ended up finding that the error was from the browsers, when updating chrome to the latest version the error was corrected, it was in version 52 [using android 6.0.1].

In the other browser [which depends on android WebView to work] it was at version 55, I updated it to version 95 and the site started to work normally [using android 5.1.1]

It was my mistake, sorry for my lack of attention with the issue of browser updates and thank you very much for your attention.

**Comment by ffoodd** [comment]
Nice, FYI [Bootstrap 5 only supports Chrome >= 60.](https://github.com/twbs/bootstrap/blob/8f11c52919fb9b7142ebf9b5797f9cc1538194d2/.browserslistrc#L6).
