### ISSUE TITLE
bootstrap hijacks the css formatting of my website

### ISSUE THREAD

**Issue by dbeusee** [twbs/bootstrap#35812]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I include bootstrap, I do not expect it to define how the h1 - h6 tags are formatted, box sizing, and so many other things.  Instead, bootstrap should have a class, like "bs", that pulls in bootstrap css formatting.  I only use it for the modal stuff, so I had to take all the modal classes out and put into my own css file. I shouldn't have to do this, and I'll have to do it every time I upgrade.  I think most people won't expect a plugin like bootstrap to hijack all the formatting on the entire site.  Trying to override ALL of bootstrap's formatting just so you can use the supplied css file is a more daunting task that most people won't do.  An alternate to the "bs" class suggestion is to put all classless css in a separate file that users who want to use it can include separately from the main bootstrap css.

### Reduced test cases

Here's a very simple test case, just to demonstrate that the bootstrap css changes the result:
https://codepen.io/dbeusee/pen/JjOWvox

Without the bootstrap css, it looks like this:
https://codepen.io/dbeusee/pen/xxPqjzv

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by GeoSot** [comment]
As you describe above, you only need some specific features of bootstrap. Have you ever think of just include and build what you want?

Par example:

```scss
@import "~bootstrap/scss/functions";
@import "variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/modal";

```

OR you could modify your variables file before include bootstrap, to cover your needs

**Comment by dbeusee** [comment]
Why should I have to build a custom bootstrap just to work around this issue? The full version still should not mess up a website! Are you saying people who don't want a messed up website must build a custom bootstrap? That seems silly. I want to use the dist files.

**Comment by ffoodd** [comment]
If you're using Bootstrap, you need to know what it does or does not. Bootstrap doesn't claim what you're requesting and explains very clearly what it does in the docs.

Our reboot (which seems to annoy you) is the basis of millions of websites. If you need other parts of Bootstrap but don't want the reboot, you need to make a custom Sass build from our sources—but we won't break our default build for your single purpose.
