### ISSUE TITLE
Carousel component will not accept custom slide indexes

### ISSUE THREAD

**Issue by millerthegorilla** [twbs/bootstrap#35813]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am trying to create a bootstrap carousel that presents items in a random order.

To do this, I have created an array of indexes, shuffled it, and then use a custom iterator to present me with the next active slide index.

I have been able to get this working by manually sliding using setTimeout with carousel.to(i).  I then have difficulty with the indicators set with data-bs-slide-to on them.   

However, I am under the impression from the docs that I should be able to set 'data-bs-slide-to' to the next index, which I set on the carouselElement as well as on both the prev indicator and the next indicator with the appropriate slide indexes.
No matter what I try though, and I have also tried setting the class 'carousel-item-next' and 'carousel-item-prev' on the appropriate slides, the carousel simply cycles to the next child of carousel-inner.

I have tried absolutely everything that I can think of to get this working, but with no luck.  Could someone check to see if the carousel is broken, or let me know where and when I can set the custom index for the next slide in a way that will override the default behaviour of simply cycling to the next sibling?

Many thanks.

### Reduced test cases

https://codepen.io/millerthegorilla/pen/eYevjPe?editors=1111

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.1.3 via cdn

**Comment by millerthegorilla** [comment]
This is sort of a moot point, as after several days of hair tearing, I discovered that I can randomize the child node list of carousel-inner, and then set carousel._items to that child node list, and the whole thing works perfectly.
I would sort of like to know if the data attributes can be set manually though, as I couldn't get them to work and the docs recommend that that is the correct way of doing things.

**Comment by WinterSilence** [comment]
you can do it by adding `.order-*` to `.carousel-item`, see https://getbootstrap.com/docs/5.1/layout/columns/#order-classes

**Comment by mdo** [comment]
Closing as stale and a won't fix. I don't see us supporting random orders, though the suggestion above may be a good one (I haven't tested it).
