### ISSUE TITLE
Change class="table" to class="bootstrap"!

### ISSUE THREAD

**Issue by yecril71pl** [twbs/bootstrap#35824]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Change the class name `table` to `bootstrap`! (of course, keeping the old one for compatibility 😞 )
Another less specific alternative: `class="responsive"`.

### Motivation and context

The documentation says:

> Bootstrap’s tables are opt-in. Add the base class `.table` to any `<table>`

But `<table class="table" >` does not state that it is a table that should be handled by [Bootstrap](https://getbootstrap.com/docs/5.1/content/tables/).  It is confusing to the reader, in that it conveys no information at all.

**Comment by mdo** [comment]
No plans to change this.

**Comment by yecril71pl** [comment]
So much for *open and welcoming environment*.

**Comment by mdo** [comment]
Sorry, didn't mean to be unfriendly, I'm just super brief more often then not these days :). Your suggestion of renaming a component class to the name of the project itself doesn't make sense though. It's a table, and just as say a modal is a `.modal`, it's named appropriately. We also couldn't rename it until the next major version anyway, if there were a more appropriate name.

**Comment by ffoodd** [comment]
Class name can be whatever, as tout pointed out. So inside a CSS framework, the class name to style table can be table. It makes things obvious: this class is meant for tables.

It's also opt-in since it's a class: you use it or you don't. We cannot target the table  element itself since there are many cases where those styles shouldn't apply: layout tables, tables used as charts, etc.

We cannot change a class name between major versions because it'd break millions of tables in websites using current class names. That's the purpose of semantic versionning.

> However, it is a pain to the eyes and it is introducing bad habits to coder’s practice, so it would be a good thing to have it fixed at some point in future.

Bootstrap's tables are using this class for years, hundred thousands developers used it for years. May we assume so much eyes agree this can be a best practice?

Naming things is hard, but Bootstrap has its naming conventions. They are documented,  and consistent since the very beginning.

And while maintaining such popular framework, consistency is probably the most important thing to care about.

**Comment by yecril71pl** [comment]
> Class name can be whatever, as tout pointed out. So inside a CSS framework, the class name to style table can be table. It makes things obvious: this class is meant for tables.

If it is important that the class has a `table` in its name, it should be named `bootstrap-table`. 

> 
> It's also opt-in since it's a class: you use it or you don't. We cannot target the table element itself since there are many cases where those styles shouldn't apply: layout tables, tables used as charts, etc.

Layout tables are evil, charts are best done as embedded graphic objects.

> 
> We cannot change a class name between major versions because it'd break millions of tables in websites using current class names. That's the purpose of semantic versionning.

That is why I am asking you to provide a less offensive class name that does the same thing; I am not asking you to kill the legacy one because I understand it is impossible.

> > However, it is a pain to the eyes and it is introducing bad habits to coder’s practice, so it would be a good thing to have it fixed at some point in future.
> 
> Bootstrap's tables are using this class for years, hundred thousands developers used it for years. May we assume so much eyes agree this can be a best practice?

No, of course we cannot.  If something is illogical, it is illogical no matter how many people have persuaded themselves that it is normal.

> 
> Naming things is hard, but Bootstrap has its naming conventions. They are documented, and consistent since the very beginning.

Could you point out the convention that says that a class used to mark up **Bootstrap** tables should be named `table`?  Do we also use `h1 class="h1"`?  or `blockquote class="blockquote"`?

> 
> And while maintaining such popular framework, consistency is probably the most important thing to care about.

:+1: of course.

**Comment by ffoodd** [comment]
We do have `.h1` indeed. 🤷

**Comment by yecril71pl** [comment]
> We do have `.h1` indeed. 🤷

I cannot find it at [Headings and paragraphs](https://getbootstrap.com/docs/5.1/content/reboot/#headings-and-paragraphs).

**Comment by mdo** [comment]
Here's the heading classes: https://getbootstrap.com/docs/5.1/content/typography/#headings

Bottom line though is that we're not going to be renaming the class :). There's no better name for a table than table in this situation. There's the possibility of prefixing classes, but I don't see much of a need there when there are also tools that can help with that.

**Comment by yecril71pl** [comment]
> Here's the heading classes: https://getbootstrap.com/docs/5.1/content/typography/#headings

Those classes are not for saying `h1 class="h1"`.  It is explicitly stated in the doc.

> Bottom line though is that we're not going to be renaming the class :). There's no better name for a table than table in this situation.

All 3 names I have given are better.  Maybe someone can think of even better names.

> There's the possibility of prefixing classes, but I don't see much of a need there when there are also tools that can help with that.

What tools do you have in mind?
