### ISSUE TITLE
Set min.width of dropdown menu  by navigation item

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#35823]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Vote to set min.width of drop down menu(`.dropdown-menu`) by parent's navigation item(`.nav-item`).
~~~html
<ul class="nav">
  <!-- navigation item -->
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
    <!-- drop down menu -->
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
    </ul>
  </li>
~~~
solution:
~~~css
.nav-item > .dropdown-menu {
   min-width: 100%;
}
~~~

### Motivation and context

This style using in many themes i.e. peoples think it's more stylish (:

**Comment by Emeka-Ugbanu-hub** [comment]
i would love to help with this

**Comment by mdo** [comment]
We'll pass on this, thanks though! Dropdowns will be sized by their contents.

**Comment by WinterSilence** [comment]
@mdo nope, now BS5 use variable to set `min-width`, if I change this variable, then I'm change min.width for all dropdowns, can't customize it for navigation.

**Comment by mdo** [comment]
Sorry I should've been clearer. I think having a reasonable and consistent min-width is best. I don't see that aspect of the component changing because it's being used in another component.
