### ISSUE TITLE
Rework `.list-group`

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#35826]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Need rework classes `.list-group` and `list-group-item-action` to uses separately:
~~~html
<ul class="list-group">
  <li class="list-group-item">
     <a href="#" class="list-group-item-action">A first item</a>
  </li>
  <li class="list-group-item">
     <a href="#" class="list-group-item-action">A second item</a>
     <ul class="list-group">
        <li class="list-group-item">
           <a href="#" class="list-group-item-action">A first sub-item</a>
        </li>
     </ul>
  </li>
</ul>
~~~
~~~html
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action">A first item</a>
  <div class="list-group-item">
     <a href="#" class="list-group-item-action">A second item</a>
     <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action">A first sub-item</a>
     </div>
  </div>
</div>
~~~

### Motivation and context

Current implementation not support styling for nesting groups and hard to integrate sorting(drag&drop)

**Comment by mdo** [comment]
Thanks, but no plans to go this direction. I'm unclear why sorting is difficult when list groups are just vertically (and sometimes horizontally) stacks of elements that are always inside a parent wrapper. Seems pretty easy to me. Nesting is intentionally not supported.

**Comment by WinterSilence** [comment]
@mdo problem with sorting nested lists

> Nesting is intentionally not supported.

what's reason?
