### ISSUE TITLE
Carousel skipping from middle of transition to end of transition

### ISSUE THREAD

**Issue by M3g4n-P107r0wsk1** [twbs/bootstrap#35835]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### **Issue**
When using version 5.1.3 of the Bootstrap CSS to make a Carousel, the transition for switching slides does not start from the beginning, rather it skips from the middle to the end

### Expected Result
The slides should smoothly scroll in the desired direction (e.g. pressing the right arrow scrolls smoothly from slide 1 to slide 2) as it does when using Bootstrap CSS v4.0.0

### Steps to Reproduce
1. Follow the tutorial to create a Carousel found in Bootstrap's documentation (https://getbootstrap.com/docs/5.1/components/carousel/)
2. Use Bootstrap CSS v5.1.3 in the head section (`<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">`)
3. Press the arrows on the sides of the slide and the image does not slide smoothly

### Reduced test cases

Reduced test case using Bootstrap CSS v5.1.3 (broken): https://codepen.io/MeganPiotrowski/pen/zYPdvdq
Reduced test case using Bootstrap CSS v4.0.0 (not broken): https://codepen.io/MeganPiotrowski/pen/YzExyee

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by GeoSot** [comment]
@M3g4n-P107r0wsk1 please check again your 5.1.3 demo. It has some wrongs and some duplicated imports

**Comment by mdo** [comment]
Still waiting on an update here per last comment, so closing out for now.
