### ISSUE TITLE
Floating labels textarea

### ISSUE THREAD

**Issue by iitsmateen** [twbs/bootstrap#35851]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![391ADDAE-6D35-41F3-B2AA-A123F950144D](https://user-images.githubusercontent.com/61585018/154330976-70b796af-f0c2-4413-beb7-ca91d04c7ef4.jpeg)

### Reduced test cases

![58143417-39E6-441B-B80C-7E4C70F47867](https://user-images.githubusercontent.com/61585018/154331145-c90eb79e-9502-47e8-87b2-d3e52632dda5.jpeg)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
Duplicates #32800.
