### ISSUE TITLE
Bootstrap 5 : Event stopPropagation() or stopImmediatePropagation() is not working in According

### ISSUE THREAD

**Issue by Yusufzai** [twbs/bootstrap#35867]
### Description

I am trying to apply a span tag with some click event inside my according header 

but, 

I do not want to show or collapse my according.

So I have used stopPropagation() and stopImmediatePropagation() but they both did not work.

```
window.foo = function(e) {
      e.stopPropagation();
     console.log('test')
}
```

### Reduced test cases

Below is the working example which replicates the issue - https://jsfiddle.net/9pL40roz/1/

I want to achieve something mentioned in the link below - https://stackoverflow.com/a/24469635

### What operating system(s) am I using?

Windows, macOS

### What browser(s) am I seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge

### What version of Bootstrap am I using?

v5.1.3

**Comment by Shakti1001** [comment]
I think you are using div tag inside your accordion that is why all the div's inside your accordion get's expanded while clicking on accordion or on click me button.
I have modified and tested the code on JSFiddle while updating the div to button and it works fine for me.
Please have a look at the above jsfiddle link.
You can do it like defining button like below
https://jsfiddle.net/v527a4gs/3/
 <button type="button" class="btn btn-primary" onclick="foo(event);">
        click me
        </button>
or
define an anchor tag to get your desired result.
https://jsfiddle.net/v527a4gs/4/
 <a type="button" class="btn btn-primary" onclick="foo(event);">
        click me
        </a>

**Comment by Yusufzai** [comment]
@Shakti1001 Thanks for your reply but don't you think it's a bug as this does not happens with BS 4. I mean I am currently converting a BS 4 Project to BS 5 that's why I personally think it's a bug

**Comment by mdo** [comment]
You're putting a clickable element inside a button and that isn't valid HTML or allowed by browsers. You'd need to drastically change your markup to make something like this work.

**Comment by clemorphy** [comment]
For those looking for a solution, this worked for me : https://stackoverflow.com/a/70664716/2352838
