### ISSUE TITLE
List group item hover issue

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#35869]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hovering over a list item seems to lose color. Not sure if it's intentional.

### Reduced test cases

* https://getbootstrap.com/docs/5.1/components/list-group/#links-and-buttons (works)
* https://twbs-bootstrap.netlify.app/docs/5.1/components/list-group/#links-and-buttons (doesn't work)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

main

**Comment by gdibble** [comment]
Also noticing this on macOS Monterey 12.1 in Safari, Chrome and Firefox

**Comment by gdibble** [comment]
I'm running this locally and getting the same outcome as on the netlify [deployment](https://twbs-bootstrap.netlify.app/docs/5.1/components/list-group/#links-and-buttons).  Trying to get a build locally to match the getbootstrap [output](https://getbootstrap.com/docs/5.1/components/list-group/#links-and-buttons).  I find the cascading order (and thus the line-number differences interesting and quite telling.

@XhmikosR, if I do not submit a PR before you then please let me know what I can do if anything at all to assist. 👍 

![image](https://user-images.githubusercontent.com/906846/155078859-1fe1c605-5bd2-4a04-844a-aa76394ea345.png)

_Note that my working code via `npm run docs-serve` produce the same cascading order and line-numbers as those on the getbootstrap site, however my hover effect matches that on netlify._

![image](https://user-images.githubusercontent.com/906846/155079680-9ed8be24-7935-487f-8502-2f72e6f4adb7.png)

![image](https://user-images.githubusercontent.com/906846/155080202-495eb123-b61e-4dcb-8f77-f038cb460561.png)

**Comment by gdibble** [comment]
Cascading order in `/scss/_list-group.scss` looks correct.
Is it possible that the main site deployment is out of date with Anton's fix?
![image](https://user-images.githubusercontent.com/906846/155082087-d66ce28e-f10b-4ffa-b945-e88066284464.png)

Ah! @XhmikosR was right about v5.2. Fixed in https://github.com/twbs/bootstrap/pull/35759/files#diff-5acbd4a53dcb8f76abf2cef498ae5a8c5d173ff48ae537c825afa5739a5b5bf0R85

**Comment by gdibble** [comment]
btw ty @WinterSilence 🙌

**Comment by WinterSilence** [comment]
@gdibble yes, my fix can be not complete, sometimes it's happening :) p.s. what's is "btw ty"?

**Comment by gdibble** [comment]
> @gdibble yes, my fix can be not complete, sometimes it's happening :) p.s. what's is "btw ty"?

@WinterSilence I understand ☺️ _Just wanted to help a bit; hope that's okay_

[btw] By The Way, meaning "also..."
[ty] Thank You

**Comment by gdibble** [comment]
Thanks @mdo, you rock 🙌
