### ISSUE TITLE
Italics not applied via bootstrap.reboot as per Typography docs 

### ISSUE THREAD

**Issue by jrkd** [twbs/bootstrap#35874]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`<em>` and `<i>` tags are not styled via boostrap reboot. 

When using boostrap in combo with normalize.css, this means italic text is unstyled. 

### Reduced test cases

See [bootstrap's own typography docs - Heading 'Inline Styles'](https://getbootstrap.com/docs/5.0/content/typography/#inline-text-elements) suggesting that em/i should be set, similar to how strong is, in the reboot css. 

If you inspect the `<p><em>This line rendered as italicized text.</em></p>`, youll see that the user agent stylesheet (at least in chrome) is setting font-style: italic. 

Compared to the bold live above, which is being set correctly by bootstrap.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.0.2

**Comment by mdo** [comment]
Is the problem that we are not explicitly styling the italicized text, and that the browser is? If so, I don't see a problem with this as we don't need to override that with unnecessary styles. I'm not at my computer but I believe we reset `b` and `strong` elements to use `bolder` instead of `bold`.

**Comment by jrkd** [comment]
> Is the problem that we are not explicitly styling the italicized text, and that the browser is? 

Yeah thats right. I wouldve thought that the use of both reset.css & bootstrap is pretty widespread, and in that case you cant expect the browser to be providing anything. 

Unless Ive misunderstood and reset shouldnt be used at all with bootstrap?

**Comment by mdo** [comment]
We have our own normalizer and rest with Reboot, which is forked from Normalize. We don't reset every style, especially if the browser already supplies it.
