### ISSUE TITLE
a:visited style

### ISSUE THREAD

**Issue by Alimzfr** [twbs/bootstrap#35876]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The new bootstrap library has no override style for a:visited

### Motivation and context

Complete overriding of default styles

**Comment by mdo** [comment]
Yea and that is intentional.

**Comment by Alimzfr** [comment]
Ok, Thanks for answer.

**Comment by jesus2099** [comment]
It's actually a bug, not a feature.

**Comment by jesus2099** [comment]
So all bootstrap based sites have this issue.

I fixed with:

```css
a:visited {
	color: revert;
}
```

I would have made a general Stylus userstyle for bootstrap sites...
But it seems I just use one such site.
