### ISSUE TITLE
Update to 5.1.4 and include css variables for styling

### ISSUE THREAD

**Issue by oakleaf** [twbs/bootstrap#35888]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I can see that there were an update 8 days ago that replaces coloring with css custom properties (var(--bs-color-success)) for buttons. Can we maybe release this?

https://github.com/twbs/bootstrap/tree/ef9d8538a06f43f74f49d6829cbf301773381488

### Motivation and context

We're building dark mode, this would save us a ton of files that overwrites this customly for our project

**Comment by mdo** [comment]
The next release is v5.2.0 and we're getting close to sharing that :). Sorry we don't have an ETA.

**Comment by oakleaf** [comment]
Do you think it’s within a week?
