### ISSUE TITLE
An addition to /docs/5.1/content/typography/

### ISSUE THREAD

**Issue by la-ruby** [twbs/bootstrap#35887]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

To make something like this [1] easier, how about adding something like this [2] to the typography features at
mentioned at /docs/5.1/content/typography/.

![1](https://user-images.githubusercontent.com/55279023/155326984-e7ea5922-a3bf-4354-b41f-bf0b7c2f09fe.png)

![2](https://user-images.githubusercontent.com/55279023/155327000-f0c47afd-d510-44d0-920d-8399302e2173.png)

### Motivation and context

To make something like this [1] easier.

**Comment by mdo** [comment]
Thanks, but we'll pass on this.
