### ISSUE TITLE
<select> fields not displaying accurately in modal dialogs

### ISSUE THREAD

**Issue by unpococloco** [twbs/bootstrap#35885]
I have a modal dialog in BS v5.x. It allows users to update their mailing addresses.

There are 2 `<select>` fields, one for the state, the other for the country. All field values are retrieved from the database via PHP/MySQL.

When the modal is shown, the values for the `<input>` fields show up with no problems. However, the `<select>` fields do not display their respective values which have the selected argument set. It's as if the selected argument is not even present. Have checked the HTML and the correct values for the `<select>` fields indeed have the selected argument set.

There appears to be nothing allowing me to refresh the modal once it has been shown.

How do I solve this?

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
