### ISSUE TITLE
Readonly form need to different variable of color 

### ISSUE THREAD

**Issue by chiragmistry007** [twbs/bootstrap#35899]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

$input-disabled-bg this variable is mention as disabled property so need to separate readonly & disabled

 &:disabled,
  &[readonly] {
    background-color: $input-disabled-bg;
    border-color: $input-disabled-border-color;
    // iOS fix for unreadable disabled content; see https://github.com/twbs/bootstrap/issues/11655.
    opacity: 1;
  }

Thank you!

![image](https://user-images.githubusercontent.com/90891363/155497249-c5cf331b-27ce-4bf0-a191-245c23ef14d0.png)

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.0

**Comment by mdo** [comment]
Closing for #33925.
