### ISSUE TITLE
Bootstrap's modal steals focus, when an element outside modal subtree is focused, e.g. CKE's tooltip

### ISSUE THREAD

**Issue by Liero** [twbs/bootstrap#35916]
### Describe the issue

* **GIVEN** that I use the basic bootstrap modal sample from your page: https://getbootstrap.com/docs/5.1/components/modal/#live-demo

* **WHEN** I use CKE editor inside the bootstrap which creates an input in a balloon outside modal subtree

* **THEN**  I'm not able to focus the input (e.g Add Link baloon/popover)

It seems to be related to bootstrap modal's focus feature, because if I specify data-bs-focus="false", it works fine.

However, "focus" feature should not steal focus, when the modal is already initialized
 > Puts the focus on the modal **when initialized.**

It is a bug IMO.

See also https://github.com/twbs/bootstrap/issues/6996
https://github.com/ckeditor/ckeditor4/issues/3583
https://github.com/ckeditor/ckeditor4/issues/3827
https://stackoverflow.com/questions/31678662/ckeditor-issue-with-bootstrap-modal
https://stackoverflow.com/questions/22637455/how-to-use-ckeditor-in-a-bootstrap-modal

### Reduced test cases

https://codepen.io/Lieroo/pen/GROGyVr

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

v.5.1.3

**Comment by patrickhlauke** [comment]
The modal code tries to maintain focus inside the modal once opened. It seems CKE creates its own little popup but inserts it dynamically outside of the container for the modal. Unfortunately, I don't think that's something that can be fixed at Bootstrap's level (as it needs to enforce its focus to remain inside the modal itself), and it's specific to what CKE does in how it generates its extra tooltips etc - it should ideally do them as sibling elements of its regular UI (which *is* inside the modal).

**Comment by pmishev** [comment]
This issue still exists in 5.3.3. Are there any plans to fix this?

Setting the `focus` option to false has the side effect of not being able to close the modal with the `ESC` key.
The documentation still states that the option `Puts the focus on the modal when initialized.`. It would have been fine if it was doing it only on initialize - why does it need to steal the focus constantly?

**Comment by patrickhlauke** [comment]
it doesn't "steal" the focus, it maintains it inside the modal dialog, which is what it should do to be a conformant accessible modal dialog. the core issue here are components that, when inside a dialog, still assume they can generate their containers on the fly and just put them at the end of the DOM
