### ISSUE TITLE
dropdown overflow

### ISSUE THREAD

**Issue by danny007in** [twbs/bootstrap#35926]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

overflow of dropdown
![Screen Shot 2022-03-01 at 17 11 23](https://user-images.githubusercontent.com/50356015/156163174-46167504-9ffc-4d2e-96c8-f7f51d36c194.png)

### Reduced test cases

overflow of dropdown
![Screen Shot 2022-03-01 at 17 11 23](https://user-images.githubusercontent.com/50356015/156163174-46167504-9ffc-4d2e-96c8-f7f51d36c194.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Screenshots are not reduced test cases.

---

Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
