### ISSUE TITLE
$min-contrast-ratio not working as expected.

### ISSUE THREAD

**Issue by MaxxDelusional** [twbs/bootstrap#35920]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using a primary color of #D53F1C, and a text color #fff, I would expect primary buttons to have white text. What I am seeing is the button text is black by default.

If I use a calculator to calculate the contrast between these two colors, I get a value if 4.6. https://contrast-ratio.com/#white-on-%23D53F1C

If I set the $min-contrast-ratio bootstrap variable to 4.5 (the default), I would expect the text to be white, as the contracts is higher than the min value.

### Reduced test cases

If I lower the min-contrast ratio down to 2, I see white text. It seems that bootstrap is not calculating the contrast value correctly.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
I think this is the expected behavior, since [we return the first sufficiently contrasted color in the list, and the light colors come first in the list](https://github.com/twbs/bootstrap/blob/main/scss/_functions.scss#L154).

Our function do not return the most contrasted color. Maybe that's what you expected, wasn't it?

**Comment by MaxxDelusional** [comment]
If light colors come first, then I would expect my button to have white text, but it doesn't, it has black text.

I *want* my button to have white text.
