### ISSUE TITLE
When the Dropdown is in a scrollable container and the position is set to absolute, the Dropdown is not properly aligned

### ISSUE THREAD

**Issue by wenmin92** [twbs/bootstrap#35939]
### Prerequisites

- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![image](https://user-images.githubusercontent.com/6901815/156506408-6b1aaf73-bff9-45c5-9e1b-631cd724e63e.png)

This is caused by adding the `overflow: auto;` to the dropdown container:

![image](https://user-images.githubusercontent.com/6901815/156506840-d29a029b-31b5-4131-9ec6-6f925b093215.png)

### Reduced test cases

Live Demo: https://stackblitz.com/edit/js-wsjcz1

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Add `data-bs-boundary="body"` to the trigger `<button>`.
