### ISSUE TITLE
focus ring 

### ISSUE THREAD

**Issue by pinggi** [twbs/bootstrap#35946]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The focus ring differs for a button and a list item also in Chrome's Developer Tools while in "device toolbar" mode. It's the mode for testing a responsive design.

See: [focus-ring](https://i.postimg.cc/pVQdqt0Q/focus-ring.png)

Left: button focus (:focus)
Middle: item focus (:focus + :focus-visible)
Right: item focus (:focus + :focus-visible) in Chrome's "device toolbar" mode

The :focus-visible style is set by browser and not by bootstrap:
```
:focus-visible {
    outline: -webkit-focus-ring-color auto 1px;
}
```

Shouldn't the focus ring be the same across all elements?
And :focus-visible set by Bootstrap similarly like the button's focus is?

### Reduced test cases

1. Go to [https://getbootstrap.com/docs/5.1/components/dropdowns/#single-button](https://getbootstrap.com/docs/5.1/components/dropdowns/#single-button)
2. Click "Dropdown link" and you can see the button focus (:focus)
3. Press "tab" key and you can see the item focus (:focus + :focus-visible)
4. Click "Toggle device toolbar" in Developer tools, find the "Dropdown link" again, click it and press "tab" key to see the item focus again but now with different color.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v.5.1.3

**Comment by AgentSmith0** [comment]
I also think that the outline when pressing tab on a dropdown menu should be removed. It doesn't look very well.

**Comment by patrickhlauke** [comment]
when in device toolbar mode, chrome uses a different `-webkit-focus-ring-color` to mimic what is actually used on android/chrome by default, which is different from the two-tone black/white default focus ring on desktop. as we're not forcing/redefining the focus ring for everything, but leaving it up to the browser to deal with it on links etc, you're seeing this discrepancy between regular desktop view and device toolbar simulation in devtools.
