### ISSUE TITLE
bootstap nav bar drop down menu doesnt work after first navigation 

### ISSUE THREAD

**Issue by ameliaxjones** [twbs/bootstrap#35963]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

i am using the 5th one down default styling of a nav bar https://getbootstrap.com/docs/5.1/examples/headers/# 

the white one with the image near the search bar.

When you use the drop down menu one time it will bring you to where you have to go however when you try to use it again for the second time nothing happens. You cant even get it to drop down anymore. I took away the scss thinking the black hover might have something to do with it but that didn't work. 

Any help would be appreciated.

I have also manually installed bootstrap, jquery and popper thinking that might help but it did not 

### Reduced test cases

```
<%# #nav bar added %>

<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="images/logo.png"><use xlink:href="/"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <a class="navbar-brand" href="/">Eorzea Homes</a>
          <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
          <li><a href="/listings"" class="nav-link px-2 link-dark">Listings</a></li>
          <li><a href="/listings" class="nav-link px-2 link-dark">My Listings</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>
        <% if user_signed_in? %>  
        <div class="dropdown text-end">
          <a href="/" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="/listings">My listing</a></li>
            <li><a class="dropdown-item" href="/listigns">New listing</a></li>
            <li><a class="dropdown-item" href="/users/edit">Settings</a></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %></li>
          </ul>
        </div>
        <%else%>
        <div class="dropdown text-end"> 
        <%= link_to "Login", new_user_session_path, :class => 'dropdown-item'  %>
        </div>
        <%end%>
      </div>
    </div>
  </header>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._
