### ISSUE TITLE
Scrollspy: support content in an `iframe` as well

### ISSUE THREAD

**Issue by dakur** [twbs/bootstrap#35965]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Make scrollspy work also when element which is being spied on is inside of an iframe. Currently, it relies on working in the same window/document context.

### Motivation and context

Scrollspy can be then used together with WYSIWYG editors like tinymce which encapsulate their DOM into an iframe. You can then have ToC next to the editor and spy onto editor's content.

I've already commented it in https://github.com/twbs/bootstrap/pull/33131#issuecomment-783342009 and https://github.com/twbs/bootstrap/pull/33131#issuecomment-864773680, but it was not noticed probably.

**Comment by mdo** [comment]
I don't think we'd support this—seems like an uncommon use case. Closing as a won't implement for now, but cc-ing @geosot if he has any ideas anyway.
