### ISSUE TITLE
Modal does not work and presents the following errors in the console

### ISSUE THREAD

**Issue by darmon77** [twbs/bootstrap#35975]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am upgrading from version v4.0 to version v5.1.3 where I only have this problem, I should add that I am using jquery v3.6.0 and popper v2.11.2
   `  <a  href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#<?php echo controller_esc_html(controller_category_id()) ; ?>"><label style="color: #ddd;"class="fa fa-<?php echo controller_mel_html(incubus_category_icon( controller_category_id() )); ?> category-icon fa-lg"></label></a>
`
**print console**
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#2' is not a valid selector.
    at r (https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js:6:920)
    at HTMLAnchorElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js:6:35242)
    at HTMLDocument.s (https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js:6:4721)

details
```
const getElementFromSelector = element => {
  const selector = getSelector(element)

  return selector ? document.querySelector(selector) : null        //problem
}
```

I would be very grateful if you give me some clues on how to solve this problem that I have been looking for and is reported in previous versions but that have no solution for me.

### Reduced test cases

codepen does not have an optimal development environment to fully reproduce my problem

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.3

**Comment by GeoSot** [comment]
Just try to put a string prefix to your ids and you 'll be fine ;) 
(document.queryselector doesn't support numeric id selectors)

**Comment by patrickhlauke** [comment]
to add to this: while the html spec removed restrictions on `id`, allowing any kind of string (as long as it has at least one character, and doesn't contain spaces), CSS3 still disallows `id` values that start with a number. and as `document.querySelector` effectively runs a CSS query, any `id`s that start with a number will fail.
