### ISSUE TITLE
Carousel with indicators not sliding in recent PR

### ISSUE THREAD

**Issue by MewenLeHo** [twbs/bootstrap#35978]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

After recent work on the Carousel component, I noticed a possible issue with the carousel with indicators.

It seems that the carousel is stuck and does not start sliding to the next slide until you `hover` the carousel with your cursor.
The cycling of the carousel will then start on `mouseleave`.

### Reduced test cases

After investigation, it seems that this issue was caused by the commit [https://github.com/twbs/bootstrap/commit/a247fe9b27ec57152f07aaa5dfc79f633d2b6d10](https://github.com/twbs/bootstrap/commit/a247fe9b27ec57152f07aaa5dfc79f633d2b6d10) included in PR [https://github.com/twbs/bootstrap/pull/35753](https://github.com/twbs/bootstrap/pull/35753)

To see the bug, it is possible to use [https://deploy-preview-35753--twbs-bootstrap.netlify.app/docs/5.1/components/carousel/#with-indicators](https://deploy-preview-35753--twbs-bootstrap.netlify.app/docs/5.1/components/carousel/#with-indicators)

Possible solution: revert this commit.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.2.0

**Comment by GeoSot** [comment]
Thank you @MewenLeHo for pointing out this issue. 
I did some search over this, and according to [docs ](https://getbootstrap.com/docs/5.1/components/carousel/#options)  and will fix it soon
