### ISSUE TITLE
Will bootstrap add material design style?

### ISSUE THREAD

**Issue by 1211ciel** [twbs/bootstrap#35985]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Will bootstrap add material design style?

### Motivation and context

material style is beautiful

**Comment by mdo** [comment]
Nope! 😅
