### ISSUE TITLE
can not inject bootstrap css file into WKWebView IOS

### ISSUE THREAD

**Issue by fukemy** [twbs/bootstrap#35989]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have a local css file named "bootstrap.css" with about ~10k lines

[bootstrap css pastebin link](https://pastebin.com/C0GigaHT)

I want to apply this css file to WkWebView using userContentController:
```
func getCSSFile(name : String) -> String{
        if let path = Bundle.main.path(forResource: name, ofType: "css"){
            guard let cssString = try? String(contentsOfFile: path).components(separatedBy: .newlines).joined() else {
                print("can not load css file: \(name)")
                return ""
            }
            
            return """
            var style = document.createElement('style');
            style.innerHTML = '\(cssString)';
            document.head.appendChild(style);
            """
        }else{
            return ""
        }
        
    }
```
Here is method to add:
```
let scrip = append(WKUserScript(source: getCSSFile(name: "bootstrap"), injectionTime: .atDocumentEnd, forMainFrameOnly: false))

webView.configuration.userContentController.addUserScript(script)
```
But when web loaded, i check the web websource code but can not find this bootstrap content inside. With other file css (~1000 lines) it's work normally. Can someone help my problem? Thanks

### Reduced test cases

im using WKWebView, when checked page source, i did not found bootstrap 

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v4.3.1

**Comment by ffoodd** [comment]
`let scrip` should be `let script`, I guess?

If that's not so simple, I'm afraid this is not something related to Bootstrap— so I suggest you try on StackOverflow or something.
