### ISSUE TITLE
Table borders look bad in dark mode

### ISSUE THREAD

**Issue by j-f1** [twbs/bootstrap#35982]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I’m super excited to see #35857 and have built a copy of it to try out on my website. However, in dark mode, the borders of table cells remain black (or dark gray). 

I think the best solution here would be to update the default `.table` class to use `--bs-border-color` as its border color, then add a new class (`table-white`?) that continues to use the current border colors, but also adds an explicit white background to table cells.

### Reduced test cases

See the docs for tables: https://deploy-preview-35857--twbs-bootstrap.netlify.app/docs/5.1/content/tables/

<img width="854" alt="Screenshot_2022-03-09 16 11 06" src="https://user-images.githubusercontent.com/25517624/157536739-292ef581-803b-46f4-bda4-4b8d852e5165.png">

In light mode, the very first table looks good. But in dark mode, its borders do not change color.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

3790ed0ec

**Comment by mdo** [comment]
Yeah, there's going to be a ton that's incomplete there—nearly all components aren't ready for it yet. No need to report issues on that branch/PR just yet :).

**Comment by j-f1** [comment]
Sounds good! I only reported it because I saw no other issues with my (admittedly not super complex) website.

**Comment by mdo** [comment]
All good! Appreciate the extra eyes on it :). I'm very excited to see it evolve and improve!
