### ISSUE TITLE
bootstrap should added scroll to top button 

### ISSUE THREAD

**Issue by SINGHSAPNA** [twbs/bootstrap#35993]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

the scroll to top button  will help us as other components do please look into that matter

### Motivation and context

![Introduction · Bootstrap v5 1](https://user-images.githubusercontent.com/100429835/157708230-31220385-0afe-4292-a1ba-af8abeafc814.png)

**Comment by ffoodd** [comment]
If really needed, you might have a look at [Orange branded fork, Boosted](https://boosted.orange.com), which includes this component in both v4 (JavaScript based) ans v5 (CSS bases).

**Comment by mdo** [comment]
Yup, no plans to add that here ourselves when there are plenty of keyboard shortcuts and more to do it across devices.

**Comment by SINGHSAPNA** [comment]
THANKS FOR THIS @ffoodd
