### ISSUE TITLE
Use of "adjacent sibling" with "universal selector" triggers performance issue in Chrome

### ISSUE THREAD

**Issue by paharvey** [twbs/bootstrap#36014]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

<p>The CSS selector <code>legend + *</code> was added in commit <a href="https://github.com/twbs/bootstrap/commit/c51e9fa4ee8fe8020decec064803e686eb9e1dde">c51e9fa4ee8fe8020decec064803e686eb9e1dde</a> to fix a wrapping bug for Bootstrap v5.</p>
<p>Unfortunately, Google Chrome will re-check the styles of every <b>sibling</b> element when:</p>
<ul>
  <li>the CSS selector <code>legend + *</code> is used; <b>and</b></li>
  <li>we insert an element into any existing container element</li>
</ul>
<p>This means that using Bootstrap v5 and dynamic DOM updates can create a performance issue in Google Chrome. For example, when using React virtualization we may have thousands of elements in a container and then add/remove a few sibling elements on each scroll event. The <code>legend + *</code> selector causes Chrome to recalculate the styles of every element, not just the newly added ones. This happens even if our DOM contains no legend elements.</p>
<p>This issue has already been reported to <a href="https://bugs.chromium.org/p/chromium/issues/detail?id=1305839">Chromium as issue 1305839</a>.

### Reduced test cases

https://codepen.io/paharvey/pen/rNpaaGe

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Not too concerned with this, so closing as stale.

**Comment by ffoodd** [comment]
As a sidenote on the topic, one may try to use CSS containment on the added elements to mitigate the issue.

**Comment by paharvey** [comment]
Sorry, but based on my reading I don't understand how CSS containment could mitigate the problem.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment
