### ISSUE TITLE
docs: The docs for `position-*` is missing

### ISSUE THREAD

**Issue by zetaraku** [twbs/bootstrap#36022]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

We had a **Common values** section on the **Position** page in v4.6

https://getbootstrap.com/docs/4.6/utilities/position/

which documents the usage of:

```html
<div class="position-static">...</div>
<div class="position-relative">...</div>
<div class="position-absolute">...</div>
<div class="position-fixed">...</div>
<div class="position-sticky">...</div>
```

but the section is missing in v5.1

https://getbootstrap.com/docs/5.1/helpers/position/

### Reduced test cases

None

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment]
It's in "utilities", just like in v4: [v5 position utilities docs](https://getbootstrap.com/docs/5.1/utilities/position/).
