### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by Buratos** [twbs/bootstrap#36023]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Just try to click these checkboxes in a PC browser or mobile one and see that they work wrong. So it is impossible to use them :(

### Reduced test cases

<p>Just see documentation and try to click these checkboxes </p>
https://getbootstrap.com/docs/5.1/forms/checks-radios/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Opera

### What version of Bootstrap are you using?

5.1.3

**Comment by mamdasan** [comment]
i tested the thing you said, and they are all working fine. and i cant find any clue to why you have this problem. the only thing i can think of is that your webpage is loading incomplete.

**Comment by Buratos** [comment]
You're right :)
I once again tried to use _<input type="checkbox" class="btn-check"_. I was sure that nothing would change. After all, earlier on the PC and in the mobile browser it worked incorrectly but this time for some reason it worked correctly. I do not understand the reason. Aliluja!
:)
