### ISSUE TITLE
Fixefor bug: `user-select` inputs in not relative container

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#36039]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![изображение](https://user-images.githubusercontent.com/3521094/159052358-fbec8360-da32-4974-b1a4-3b2bfbc60144.png)

**Updated** Same problem with anchors/links.

### Reduced test cases

open forms in ff, click on input border

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by WinterSilence** [comment]
@ffoodd https://codepen.io/WinterSilence/pen/xxpVxgp?editors=1100

**Comment by mdo** [comment]
Can't reproduce on Windows or Mac.

**Comment by WinterSilence** [comment]
@mdo stupid question, but.. you check it in firefox? set cursor in input, click on input border or near
![изображение](https://user-images.githubusercontent.com/3521094/159381304-501a8c88-6341-4087-9463-902ff9adbb71.png)

**Comment by mdo** [comment]
Yes I did.

Do you have any browser extensions installed that may be interfering?

**Comment by WinterSilence** [comment]
@mdo doh! really extension( my extension...
