### ISSUE TITLE
Border classes with breakpoints

### ISSUE THREAD

**Issue by iamsajidjaved** [twbs/bootstrap#36032]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I found one deficiency in bootstrap while working with borders. 

The deficiency is no breakpoint option with border rounding classes.

On the desktop(larger screen), I already used `round-start` class but for mobile now I need `round-top` class for the same border. There is no way in bootstrap to acheive this.

Thanks

### Motivation and context

It will help us with responsiveness.

**Comment by ffoodd** [comment]
Duplicates #33974.

FYI [`border` utilities are the exact example of using the utilities API to enable responsive](https://getbootstrap.com/docs/5.1/utilities/api/#enable-responsive) for a said utility.

It requises to make a custom Sass build, though.
