### ISSUE TITLE
Blazor and Popover inconsistent results

### ISSUE THREAD

**Issue by HybridSolutions** [twbs/bootstrap#36034]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This is so weird that I hope I succeed explaining it.

I'm using .NET 6 Blazor with a Bootstrap table with rows generated dynamically. I have implemented a pager and sorting features that work perfectly. On each row, I have 1 column with an element setup to trigger Popover and another column with an element setup to trigger a Tooltip.

Here's the table tag:

`<table id="myTable" class="table table-row-bordered table-row-dashed gy-5 ecm-table">`

and a row from my Blazor demo source:

`<div id="user-@user.Id" class="symbol-label fs-3 fw-bold bg-success bg-gradient text-inverse-success" data-bs-toggle="popover" data-bs-trigger="click" data-bs-placement="top" data-bs-custom-class="popover-dark" title="@user.FullName" data-bs-content="I'm the Platform Administrator">@user.FirstName</div>`

Due to the way Blazor works, I know I have to initialize BS components each time there's changes to the page so that all present elements get events attached. 

I'm doing exactly that by using the following recommended method:

```
protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            await base.OnAfterRenderAsync(firstRender);
            await JSRuntime.InvokeVoidAsync("blazorInit");     // Calls my javascript function that inits BS components      
        }
```

My initialization script:

```
function blazorInit() {
    
    // Tooltips Init
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })

    // Popover Init
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
        return new bootstrap.Popover(popoverTriggerEl)
    })

    console.log(popoverList)
    console.log("Bootstrap Components Initialized!");
}
```

Running the application I get my table with 5 default rows per page (total of 11 entries) and with Tooltips and Popovers working perfectly on each row. here's console log:

(5) [gn, gn, gn, gn, gn]
Bootstrap Components Initialized!

I change to page 2, and components get initialized again. Here's console log:

(5) [gn, gn, gn, gn, gn]
Bootstrap Components Initialized!

Tooltips work fine on all rows, showing the correct data according to each row, but Popover only shows up on the first row.

Changing back to page 1, Popovers and Tooltips work on all 5 rows.
Changing to page 2, once again, Popovers only work on the first row. Tooltips on all 5 rows.
Changing to page 3, with only 1 row, Popovers still do not work. Tooltip works fine.
Changing back to page 2, now all 5 rows work with correct data from each row. Tooltips work on all 5 rows.
Changing back to page 1, now Popovers only work on the first row. Tooltips work on all 5 rows.

Any idea what's going on here? Can't understand why Popovers don't work properly and Tooltips do, and why some are showing and others are not?!

I attach a video of this behaviour. 

https://user-images.githubusercontent.com/8672899/158901783-606c20ca-ce6b-49b5-b853-156c89cb2f37.mp4

### Reduced test cases

Couldn't do a demo yet of this issue isolated.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by HybridSolutions** [comment]
UPDATES

changing data-bs-trigger="click" to data-bs-trigger="focus" solves the issue completely. Seems like with "click" elements are not getting disposed properly. So, tried to force to dispose each existing popover element:

```
// FIX: Popover force dispose
var disposeList = document.querySelectorAll('[data-bs-toggle="popover"]')
for (var popoverEl of disposeList) {
    var clean = new bootstrap.Popover(popoverEl);
    clean.dispose();         
}

// Popover Init
var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl)
})
```

This fixed things and now after changing page or sorting, all rows present their popovers correctly. 
There is still a side effect that I didn't manage to find how to solve. If I change a page or sort a column with a popover opened, it stays opened and can't close it even if I go back to it's page and click on the respective element.

There's definitely something wrong with popover and "click" trigger.

**Comment by mdo** [comment]
Closing as stale.
