### ISSUE TITLE
No Rounded Borders on Last Input Group Item

### ISSUE THREAD

**Issue by dday9** [twbs/bootstrap#36049]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Reproduction of the problem
1. Create an input group
2. In the input group, include four child elements:
   1. Input
   2. Button
   3. Button
   4. Button
3. Add the `d-none` class to the last button

### Current behavior
The last visible element does not have the rounded borders because it is not the last element of the input group.

### Expected/desired behavior
The rule to set the border radius to 0 should not apply to elements that are not last (or first in the case of prepended elements) if the last (or first) element is not visible.

### Reduced test cases

- JSFiddle: https://jsfiddle.net/3tyuh75o/1/
- CodePen: https://codepen.io/dday9/pen/QWaKddo

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.1.3

**Comment by florianlacreuse** [comment]
See:

* https://github.com/twbs/bootstrap/issues/29249#issuecomment-521306456
* https://github.com/twbs/bootstrap/issues/36047#issuecomment-1074182907

**Comment by dailytabs** [comment]
What if the following element is a div.invalid-feedback? The only way to resolve is to manually place a .rounded-end on the last button.
Putting the invalid-feedback anywhere else seems breaks the flow or the parent validation classes that show/hide the feedback.
