### ISSUE TITLE
text-start and text-end have wrong behavior in RTL

### ISSUE THREAD

**Issue by beyzad-asa** [twbs/bootstrap#36051]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

in RTL pages, the text-start and text-end classes ignores RTL and text-start is left as text-end is right aligned.

### Reduced test cases

```html
<html dir="rtl" lang="fa">

<body class="text-center">
  <h1>Hello BS</h1>
  <p class="text-start">This paragraph used to go right</p>
  <p class="text-end">This paragraph used to go left</p>
</body>

</html>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment]
Are you using the RTL CSS file, `bootstrap.rtl.min.css`?

**Comment by florianlacreuse** [comment]
Everything looks good with these reduced test cases:

* LTR : https://codepen.io/florianlacreuse/pen/QWaKBoL
* RTL : https://codepen.io/florianlacreuse/pen/eYydjXz

**Comment by ffoodd** [comment]
Thanks @florianlacreuse !

**Comment by beyzad-asa** [comment]
Oh stupid me. was using ltr css. sorry and good luck
