### ISSUE TITLE
Publish cspell file as a package

### ISSUE THREAD

**Issue by owenbendavies** [twbs/bootstrap#36066]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

We use cspell in a number of our projects. Currently we manually copy the cspell dictionary from this repository into each of our projects that use Bootstrap. We could create our own package, however it could be useful for other people to have an official package.

### Motivation and context

Help speed up development for people who use Bootstrap and cspell

**Comment by mdo** [comment]
No plans to tackle this ourselves just yet, so closing out. Thanks!
