### ISSUE TITLE
Tooltip bug

### ISSUE THREAD

**Issue by louismaximepiton** [twbs/bootstrap#36069]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

<details>
  <summary>Short behavior gif</summary>

![screen-recording](https://user-images.githubusercontent.com/91960143/160408341-64344097-e7b5-48f0-8345-704492127ef7.gif)

</details>

As you can see above in the short video, there is a small bug for tooltips:

Once a tooltip needs to replace, if the replace location is in `right` (or `left`), the tooltip seems to twinkle a bit between two positions while scrolling. Furthermore, as illustrated below, the tooltip seems not to be initialized well while twinkling.

<details>
  <summary>Tooltip not well initialized</summary>

![image](https://user-images.githubusercontent.com/91960143/160408283-4b5153a9-fa08-46a5-9a7d-4ab943238a17.png)

</details>

### Reduced test cases

Go on the main branch : https://twbs-bootstrap.netlify.app/docs/5.1/components/tooltips/
Click to make a tooltip appear on top
Scroll the page until the tooltip is nearly out of the screen then scroll slower.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

main

**Comment by LuukLeijtens** [comment]
The bug also seems to occur when you make the viewport smaller.

![Animatie](https://user-images.githubusercontent.com/33413601/164610057-8adb7e52-21c9-4664-8d20-e48e62232c51.gif)

**Comment by GeoSot** [comment]
I am not sure if I have understood well, but this bug exists in [5.1.3](https://getbootstrap.com/docs/5.1/components/tooltips/) version too, right?

**Comment by GeoSot** [comment]
Experimenting a bit, changing position of popper modifiers, and adding `altAxis`, seems to give better results. If anyone want to check and contribute, is fine by me

![image](https://user-images.githubusercontent.com/22406063/166574320-83b20dea-bf12-4df1-a6e7-a302a88b7a04.png)

**Comment by atomiks** [comment]
This is caused by putting `padding` on the tooltip which isn't supported (especially conditionally). The size ends up changing when the placement changes which causes problems like that — the size needs to remain constant regardless of the placement. Popovers don't seem to have any padding and therefore don't have the issue.
