### ISSUE TITLE
Table row sometimes has a thicker border

### ISSUE THREAD

**Issue by segments-tobias** [twbs/bootstrap#36072]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When creating a table in Bootstrap 5, the bottom border of a row sometimes looks thicker.
I guess this might be a Chrome rendering issue, but I'm wondering if it's something we can do something about in Bootstrap too.

See the borders of this example (I just refreshed the page and was able to see thicker borders under different rows):
![image](https://user-images.githubusercontent.com/89590365/160473320-8cd7bb9c-58c6-4ec5-a061-2dc2308549dc.png)
![image](https://user-images.githubusercontent.com/89590365/160506838-1af6e305-057f-4c16-a3c0-5a3944cd696c.png)

### Reduced test cases

Cannot reproduce in Codepen immediately.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.0

**Comment by ffoodd** [comment]
Do you have a zoom enabled? Or any extension that could mess with CSS?

**Comment by segments-tobias** [comment]
Unfortunately I can reproduce this in an incognito tab, so it's not due to my extensions.
The zoom causes the thick border to change sometimes, but the issue doesn't disappear.
See this screencap: [https://watch.screencastify.com/v/MF3YEY6Ut2nAbQ5cCWi1](https://watch.screencastify.com/v/MF3YEY6Ut2nAbQ5cCWi1).
Also, my initial screenshots were taken at the default 100% zoom.

**Comment by mdo** [comment]
I can't reproduce it myself in Chrome, but this could be an issue of pixel rounding maybe?

**Comment by mdo** [comment]
Coming back to this, this still has to be pixel rounding I think as Safari and Chrome's inspectors are showing a computed height of `41.5px` despite the box-sizing tooltip showing `42px`. Fiddling there shows this may be a bug from `border-collapse: separate` where the height gets an extra half pixel from the collapsed borders. I don't yet have a solution though other than removing that property, which causes issues everywhere else.

**Comment by AndreasMietk** [comment]
this seems to fix the issue
`border-spacing: 0px`

taken from here https://stackoverflow.com/a/22869877

**Comment by AndreasMietk** [comment]
I noticed that with my previous approach the `table-bordered` gets messed up. I don't really know how to fix it, but setting `$table-border-width: 0.1px` atleast gets rid of sometimes thicker borders
