### ISSUE TITLE
Border color & inputs work differently with CSS vars

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#36087]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Using border color utility classes with inputs works differently since the adding of CSS vars for border colors (see https://github.com/twbs/bootstrap/commit/de0dfca9a1749990319cdfcbb7f1584df09d7091).

This issue was Initially spotted by @louismaximepiton.

## Before
1. Go to https://getbootstrap.com/docs/5.1/forms/form-control/
2. Add `.border-danger` to the first input in the page
3. Result: the border is now red

<img width="336" alt="Capture d’écran 2022-03-30 à 13 24 40" src="https://user-images.githubusercontent.com/17381666/160823830-85c6a73c-a012-49a7-a72d-4e23ff96af0c.png">

## Now (_main_ branch)
1. Go to https://twbs-bootstrap.netlify.app/docs/5.1/forms/form-control/
2. Add `.border-danger` to the first input in the page
3. Result: the border stays gray

<img width="439" alt="Capture d’écran 2022-03-30 à 13 26 04" src="https://user-images.githubusercontent.com/17381666/160824045-f76b1c4b-3462-4475-87cf-1ac107630f9e.png">

because `.border-danger` value is `--bs-border-color: rgba(--var(--bs-danger-rgb), var(--bs-border-opacity));` and `.form-control border: 1px solid #ced4da;`. `.form-control border` doesn't use the CSS var so doesn't change the color.

4. Add `.border` as well
5. Result: the border is now red

<img width="336" alt="Capture d’écran 2022-03-30 à 13 24 40" src="https://user-images.githubusercontent.com/17381666/160824408-c23c37b1-c4fa-4ae8-9125-8ff08b67e2eb.png">

because by adding `.border` the border will use the color defined in the CSS var and will override the border color specific to the form control.

## Is it expected?

I'm not sure this is an issue to fix or if it is expected. But if it is expected, we should maybe mention it in the Migration page because some projects could observe a regression since adding a `.border` was not mandatory before.

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0 (current _main_ branch)

**Comment by mdo** [comment]
Hmm, this one is a little tougher. `.border-{color}` has always required the based `.border` class as shown in our utilities docs. Not every use case has followed that I'm sure, such as situations like this. Not sure how best to proceed here other than perhaps including the CSS var in the forms CSS as a starting point?

```scss
.form-control {
  border: 1px solid var(--bs-border-color, {$form-control-border-color});
  //
}
```

I was hoping to leave form CSS vars for v5.3.0, but maybe it all needs to happen now? Or at least some of it?

**Comment by julien-deramond** [comment]
Some tests done with the [current 5.1 version](https://getbootstrap.com) and the [current _main_ version](https://twbs-bootstrap.netlify.app).

Before, I can observe this rule:
1. If the component already has a border by design, using `.border-{color}` will change the color ([alerts](https://getbootstrap.com/docs/5.1/components/alerts/), [buttons](https://getbootstrap.com/docs/5.1/components/buttons/), `<input>`, etc.) 
2. If the compoent doesn't already have a border by design, using `.border-{color}` is not enough and need `.border` as well ([badge](https://getbootstrap.com/docs/5.1/components/badge/#headings), `<span>`, [close button](https://getbootstrap.com/docs/5.1/components/close-button/#example), etc.)
In the [border color utility documentation](https://getbootstrap.com/docs/5.1/utilities/borders/#border-color) we have both `.border` and `.border-{color}` because the "component" is a simple `<span>`.

Now, in the _main_ branch:
1. All "basic components" that have already a border by design like `<input>`s need an extra `.border`.
2. All components already migrated with CSS vars need an extra `.border` as well.

Indeed the alerts for example are defined like this: `border: var(--bs-alert-border)` with `--bs-alert-border: 1px solid var(--bs-alert-border-color);` with `--bs-alert-border-color: #b6d4fe` (for example).
Adding a `.border-danger` to this alert will do `--bs-border-color: rgba(var(--bs-danger-rgb), var(--bs-border-opacity));` which won't override the border color since the border will still use the `--bs-alert-border-color`. To override this behavior, `.border` must be added as well.

**Note:** We don't have the same issue with `.bg-{color}` because it will do for example `background-color: rgba(var(--bs-danger-rgb),var(--bs-bg-opacity)) !important;`. **I haven't tested it** so it is maybe something stupid but maybe we could do the same with borders. Instead of just changing the CSS var do something like:
```scss
.border-danger {
   border-color: var(--bs-danger-rgb) !important;
}
```
