### ISSUE TITLE
colgroup cause wrong UI

### ISSUE THREAD

**Issue by ArgoZhang** [twbs/bootstrap#36085]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

the following class is not correct cause by add the `colgroup` node into `Table`. so there is a border on the head top
```
.table>:not(:first-child) {
    border-top: 2px solid currentColor;
}
```

### Expected

the border under `thead` node

### Reduced test cases

```
<table class="table">
    <colgroup>
        <col width="180">
        <col>
        <col>
    </colgroup>
    <thead>
        <tr>
            <th><div class="table-cell"><span class="table-text">日期</span></div></th>
            <th><div class="table-cell"><span class="table-text">姓名</span></div></th>
            <th><div class="table-cell"><span class="table-text">地址</span></div></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <div class="table-cell"><!--!--><div generateelement="false">2022/3/30 13:59:35</div></div>
            </td>
            <td>
                <div class="table-cell"><!--!--><div generateelement="false">张三 0001</div></div>
            </td>
            <td>
                <div class="table-cell"><!--!--><div generateelement="false">上海市普陀区金沙江路 1322 弄</div></div>
            </td>
        </tr>
    </tbody>
</table>
```

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment]
This already evolved the main branch, where we now use `> ​:not​(​caption​) > ​*​ > ​*​ {` but we need to handle `colgroup` too.
