### ISSUE TITLE
text-muted not visible on bg-dark

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#36096]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

current release looks good https://getbootstrap.com/docs/5.1/components/navbar/#external-content
![grafik](https://user-images.githubusercontent.com/1651241/161207700-35bc4ec0-add0-4849-bd54-62df9c781987.png)

current brunch looks bad https://twbs-bootstrap.netlify.app/docs/5.1/components/navbar/#external-content
![grafik](https://user-images.githubusercontent.com/1651241/161207792-b55f3330-7a37-4e18-b25a-b7843703b522.png)

### Reduced test cases

https://getbootstrap.com/docs/5.1/components/navbar/#external-content
https://twbs-bootstrap.netlify.app/docs/5.1/components/navbar/#external-content

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.3 and Current main Brunch

**Comment by mdo** [comment]
Hmm, definitely a complication from the move to an `rgba()` value based on the `body-color`. The color contrast here is too low as it stands... but maybe safest and friendliest move is to revert that change for now?

/cc @ffoodd
