### ISSUE TITLE
navbar-nav to small on collapsed navbar

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#36097]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

current release looks good https://getbootstrap.com/docs/5.1/components/navbar/#color-schemes
![grafik](https://user-images.githubusercontent.com/1651241/161208463-e69ff0b9-b3d5-4c70-861d-efdc7df9eead.png)

current brunch looks bad https://twbs-bootstrap.netlify.app/docs/5.1/components/navbar/#color-schemes
![grafik](https://user-images.githubusercontent.com/1651241/161208552-fb851fdb-ad07-42d2-a0c2-f7076d9ce8ff.png)

### Reduced test cases

https://getbootstrap.com/docs/5.1/components/navbar/#color-schemes
https://twbs-bootstrap.netlify.app/docs/5.1/components/navbar/#color-schemes

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.3 and Current main Brunch

**Comment by mdo** [comment]
Problem is the CSS variables added are used on `.nav` and aren't present on `.navbar-nav`, which is another container for `.nav-link` and `.nav-item`.
