### ISSUE TITLE
Bootstrap installed via npm gives error in console

### ISSUE THREAD

**Issue by YarkinGulacti** [twbs/bootstrap#36109]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've installed bootstrap, jquery and popper.js with npm. Then i called them with `require`. When assets are compiled, there was no error. But when i reloaded the page, it gave me `Cannot read properties of undefined (reading '.alert')` error in console.

### Reduced test cases

```
	window.Popper = require('popper.js').default;
	const jQuery = require('jquery');
	window.$ = window.jQuery = jQuery(window);
	require('bootstrap');
```
and i load scripts in HTML like this;

```
<script defer src="assets/js/app.js"></script>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by zishiwu123** [comment]
@YarkinGulacti thank you for reporting this issue. Can you also provide the versions you used for: npm, JQuery, popper? That information can help the maintainers troubleshoot your error.

**Comment by mdo** [comment]
v5 also doesn't require jQuery. Beyond that, I'm not sure how we can help you with so little context here. I'd suggest asking around Slack or the Discussions tab.
