### ISSUE TITLE
Docs: Modal > Tooltips and Popovers missing data-bs-toggle

### ISSUE THREAD

**Issue by whotookzakum** [twbs/bootstrap#36110]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

5.0 Docs > Modal page > Tooltips and popovers
The example doesn't have the attribute `data-bs-toggle="tooltip"` on the anchor tags. 
I've checked for syntax errors in my code, but the tooltip only displays correctly when this data attribute is added. I thought this might be an error in the docs.

### Reduced test cases

https://getbootstrap.com/docs/5.0/components/modal/#tooltips-and-popovers

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment]
This is because those are triggered via JavaScript as opposed to data attributes. I suppose we could replace them but I'm not sure if we did it that way for a reason.

**Comment by WinterSilence** [comment]
@mdo is fake html, in real example displayed:
~~~html
<div class="modal-body">
    <h5>Popover in a modal</h5>
    <p>This <a href="#" role="button" class="btn btn-secondary popover-test" title="" data-bs-content="Popover body content is set in this attribute." data-bs-container="#exampleModalPopovers" data-bs-original-title="Popover title">button</a> triggers a popover on click.</p>
    <hr>
    <h5>Tooltips in a modal</h5>
    <p><a href="#" class="tooltip-test" title="" data-bs-container="#exampleModalPopovers" data-bs-original-title="Tooltip">This link</a> and <a href="#" class="tooltip-test" title="" data-bs-container="#exampleModalPopovers" data-bs-original-title="Tooltip">that link</a> have tooltips on hover.</p>
</div>
~~~
