### ISSUE TITLE
Pagination active page-item overlays toasts

### ISSUE THREAD

**Issue by FabianKoestring** [twbs/bootstrap#36122]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

As you can see in the screenshot below the active pagination `page-item` overlays toast messages.

![Bildschirmfoto 2022-04-06 um 10 27 24](https://user-images.githubusercontent.com/1252701/161930941-728f1138-5a88-4329-98d1-3f9f484a9ce2.png)

### Reduced test cases

https://codepen.io/team/bootstrap/pen/qBamdLj

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.0

**Comment by mdo** [comment]
This doesn't happen in our `main` branch assuming you're using the `.toast-container`, which has some positioning applied to it. I'm guessing, since you didn't include a live demo of the problem, that you're missing a `z-index` or `position`.

**Comment by FabianKoestring** [comment]
#37118 fixes the described problem. 😉
