### ISSUE TITLE
Unable to locate :hover selector in bootstrap 5

### ISSUE THREAD

**Issue by rohit0122** [twbs/bootstrap#36132]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi Team,

I was going through the utility classes provided in bootstrap 5 but I am unable to locate :hover selector in the library.

My simple requirement is, I have a button:
`<button class="btn text-light bg-info">Hello World</button>`

And on hover of it, I simply want to change the bg color and text color. Kindly guide how to achieve this?

Looking for some classes like hover:text-dark & hover:bg-light something similar.

Looking forward for your valuable response.

### Reduced test cases

Hi Team,

I was going through the utility classes provided in bootstrap 5 but I am unable to locate :hover selector in the library.

My simple requirement is, I have a button:
`<button class="btn text-light bg-info">Hello World</button>`

And on hover of it, I simply want to change the bg color and text color. Kindly guide how to achieve this?

Looking for some classes like hover:text-dark & hover:bg-light something similar.

Looking forward for your valuable response.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1

**Comment by rohit0122** [comment]
Currently this is the button: `<button class="btn text-light bg-info">Hello World</button>`

and I want on hover effect like `<button class="btn text-light bg-info hover:text-dark hover:bg-light">Hello World</button>`

**Comment by mdo** [comment]
We don't provide those utilities by default. You can enable them yourself in our utilities API. Have a look at the docs for that and you'll see some examples for how to get started.
