### ISSUE TITLE
Tabs in `navbar-nav` (wide dropdown menu)

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#36139]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add https://codepen.io/WinterSilence/pen/PoEeyeo?editors=1100 to navbar examples and maybe create short-hands classes to create equal navigation.

### Motivation and context

Wide menu in header is popular solution

**Comment by mdo** [comment]
Looks cool as is, but I don’t see us adding this to the core project. Maybe an example or snippet example? Want to open a PR for that?

**Comment by WinterSilence** [comment]
@mdo after NY, ok?
