### ISSUE TITLE
[docs] Add getInstance and getOrCreateInstance methods to documentation

### ISSUE THREAD

**Issue by spustlik** [twbs/bootstrap#36131]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please add to the doc how to use bootstrap javascript components without jQuery, specially getInstance and getOrCreateInstance static methods.

### Motivation and context

I searched documentation about how to use bootstrap javascript components without jQuery, but without luck. So I used new bootstrap.tooltip(ele) and behaviour was weird. Then I searched sources and found createInstance and getOrCreateInstance methods and it solved my problems. So please add it to the docs.

**Comment by mdo** [comment]
Every component page has a mention of both methods.
