### ISSUE TITLE
jQuery not working closed.bs.alert event

### ISSUE THREAD

**Issue by BaHeK1994** [twbs/bootstrap#36147]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

jQuery event not working
```
$(document).on('closed.bs.alert', function () {
    console.log('closed.bs.alert');
});
```

but is ok
```
$(document).on('close.bs.alert', function () {
    console.log('close.bs.alert');
});
```

https://github.com/twbs/bootstrap/blob/main/js/src/alert.js#L52-L53
The element is deleted before the event is executed, because of this it is impossible to track the event in jQuery.

### Reduced test cases

https://codepen.io/BaHeK/pen/GRyBpdo

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by GeoSot** [comment]
Hey  @BaHeK1994 .  Your case is right but according to docs https://getbootstrap.com/docs/5.1/components/alerts/#events event listeners should be attached on the specific items and not the document itself. 

If you try the following, it works every time
```js

 document.getElementById('myAlert').addEventListener('closed.bs.alert', () => {
   console.log('is closed')
})

```

**Comment by BaHeK1994** [comment]
I use $(document) to catch events when elements appear dynamically.


Updated the code https://codepen.io/BaHeK/pen/GRyBpdo

**Comment by GeoSot** [comment]
I can understand but this is not a bug. Is more like a feature and need more opinions

/cc @XhmikosR  please tell us your opinion here
