### ISSUE TITLE
Using position sticky popovers inside the referenced code doesn't display the popover

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#36167]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I applied this to a container-fliud div containing the menu..
```
.custom-sticky-menu-container-fluid {
    position: -webkit-sticky;
    position: sticky;
    top: 0px;
    z-index: 99999;
```
after doing so it the popover are no longer displayed for an item inside the sticky div, removing this class causes the popover to work again.

### Reduced test cases

Tomorrow I shall push the code live providing the link for it, I apologize for any inconvenience.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.1

**Comment by mdo** [comment]
Probably something to do with your `z-index: 99999;`. Check our z-index scale and make adjustments accordingly :).

**Comment by tomasts248** [comment]
Thank you so much, that was indeed! :)
