### ISSUE TITLE
Add a footer to the Docs page

### ISSUE THREAD

**Issue by jurgengjoncari** [twbs/bootstrap#36177]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I think that the docs need a footer. When you scroll to the bottom of the content page, it seems very weird that the content doesn't stop a bit higher. I think that this issue would be fixed by adding a footer to the docs page. 

At the same time, I noticed that the navigation bar of the docs page, has the links to GitHub, Twitter, etc., which is another issue. Usually they these kind of links are not placed at the top but on the bottom of a page. I suggest to add a footer which includes these links. 

### Motivation and context

Make the docs HTML more semantic.

**Comment by mdo** [comment]
We do have a footer, not sure what you're looking for that's not already there in our latest docs.

**Comment by jurgengjoncari** [comment]
My bad, I was in the version 4 apparently and I thought it was the latest, since in the top navbar it said so.
