### ISSUE TITLE
File to import not found or unreadable: ../node_modules/bootstrap/scss/maps

### ISSUE THREAD

**Issue by Yulinn233** [twbs/bootstrap#36180]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Source files 和 npm 的 Sass 文件夹下 没有 _maps.scss 文件
使用 @import "../node_modules/bootstrap/scss/maps"; 会报错

There is no _maps.scss file in the Sass folder of Source files and npm
Using @import "../node_modules/bootstrap/scss/maps"; will report an error

### Reduced test cases

```
// Custom.scss
// Option B: Include parts of Bootstrap

// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "../node_modules/bootstrap/scss/functions";

// 2. Include any default variable overrides here

// 3. Include remainder of required Bootstrap stylesheets
@import "../node_modules/bootstrap/scss/variables";

// 4. Include any default map overrides here

// 5. Include remainder of required parts
@import "../node_modules/bootstrap/scss/maps";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/root";

// 6. Optionally include any other parts as needed
@import "../node_modules/bootstrap/scss/utilities";
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
@import "../node_modules/bootstrap/scss/images";
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/grid";
@import "../node_modules/bootstrap/scss/helpers";

// 7. Optionally include utilities API last to generate classes based on the Sass map in `_utilities.scss`
@import "../node_modules/bootstrap/scss/utilities/api";

// 8. Add additional custom code here
```

```
Error: File to import not found or unreadable: ../node_modules/bootstrap/scss/maps.
        on line 31 of custom.scss
        from line 1 of App.scss
  Use --trace for backtrace.
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
The maps file isn’t part of any official release yet. It’s coming in v5.2.0.
