### ISSUE TITLE
Provide a "latest" URL for docs

### ISSUE THREAD

**Issue by folknor** [twbs/bootstrap#36189]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I propose (though I don't know what build system or static generator you're using, so I don't know if it's possible) that
1. getbootstrap.com docs provide a "latest" URL that points to the latest version of the docs
2. the current version number becomes a bit more prominent in the docs

So for #1, for example https://getbootstrap.com/docs/latest/layout/columns/ would redirect (right now) to https://getbootstrap.com/docs/5.1/layout/columns/ but would redirect to https://getbootstrap.com/docs/5.2/layout/columns/ when the time comes, etc.

Or even just omit "latest", so https://getbootstrap.com/docs/layout/columns/

And for #2, I'm not sure where it should be shown. It might be enough that the dropdown in the top right that currently says either "Bootstrap 5.1" or "5.1" depending on viewport size simply says "Latest" instead whenever you're browsing the latest docs - this of course means that when a new version is published the old docs will have to be updated.

### Motivation and context

3 times now over the past few years I've noticed that I'm suddenly browsing the docs for an older release, because they're stored in my browser history. I work with the scss and js source files directly in my projects, so the reason I notice is that the docs don't match up to the code I have. Which confuzzles me a bit, and then I realise the version disparity :-P

Thank you!

**Comment by folknor** [comment]
Might be worth noting that all my dozens of projects always use the "latest" (or equivalent, like "nightly") tag in package.json so I'm never on old versions. I fix breakage immediately and stay up to date on all dependencies on a daily basis.

**Comment by mdo** [comment]
#31980
