### ISSUE TITLE
invalid-feedback class changes input border and margin

### ISSUE THREAD

**Issue by ToshY** [twbs/bootstrap#36209]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Short and descriptive example bug report title**

Having an element with the `invalid-feedback` class above an input element, changes the input elements top-left border, bottom-left border, and margin-left..

**Example**

```html
<article class="card-body p-0 m-5">
  <form name="test_show_form" method="post">
    <div id="test_form">
      <div class="form-group mb-3">
        <div class="input-group">
          <div class="invalid-feedback d-block">123 already exists.</div>
          <input type="number" required="required" class="form-control is-invalid" value="123">
        </div>
      </div>
    </div>
  </form>
</article>
```

![image](https://user-images.githubusercontent.com/31921460/164774690-bf60f4d0-914f-4a20-b327-5a733e6b4a5f.png)

**Expected result**
No changes in border and margin for the given input element.

### Reduced test cases

[Codepen](https://codepen.io/toishy/pen/JjMVrqx)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Don't put the invalid feedback within the `.input-group` like that. Our selectors for it are rather difficult, but there's not much of a cleaner way to do things.
