### ISSUE TITLE
Text and background color utilities broken in 5.1.3 for print media

### ISSUE THREAD

**Issue by gdvalderrama** [twbs/bootstrap#36201]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Trying the same code on v5.0.2 and v5.1.3, when printing colors from text (eg text-dark) and background (eg bg-dark) utilities are ignored in the later version.

I can see in the [v5.1 release](https://github.com/twbs/bootstrap/releases/tag/v5.1.0) "Updated .bg-* and .text-* utilities to use CSS variables and new RGB CSS variables for real-time customization".
Could this have somehow broken these utilities when printing using bootstrap "out of the box" (no config, just using the cdn)?

### Reduced test cases

```
<div class="container">
  <div class="row">
    <div class="col bg-dark">
      1 of 2
    </div>
    <div class="col bg-primary">
      2 of 2
    </div>
  </div>  
</div>
```

When trying to print this html using weasy print, colors aren't shown.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment]
Bootstrap v5 doesn't support print styles, as mentionned in [the v5 migration guide](https://getbootstrap.com/docs/5.1/migration/#sass).

No idea what's happening here, but we probably won't do anything regarding this.

I encourage you to share your findings, in case we could effectively deliver an easy fix or if anyone comes across this issue.

**Comment by gdvalderrama** [comment]
> Bootstrap v5 doesn't support print styles, as mentioned in [the v5 migration guide](https://getbootstrap.com/docs/5.1/migration/#sass).

@ffoodd 
Yeah, true, maybe I didn't explain the issue clearly.
This happens when printing, independent of media print clauses.

The example case given has no CSS styles defined, just uses bootstrap out of the box.
The color utilities work with no problem on v5.0.2, so I doubt it has any relationship with the mayor version.

Could the issue be related to not defining CSS, and the new RGB CSS variables?

**Comment by ffoodd** [comment]
It could, but we won't investigate since we don't aim at supporting print.

If anyone has a suggestion or comes with a fix, we'll have a look.
