### ISSUE TITLE
need multilevel dropdown in navbar and in responsive make smooth dropdown

### ISSUE THREAD

**Issue by sohelmalek** [twbs/bootstrap#36214]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

like this
https://adnantopal.github.io/slimmenu/

### Motivation and context

https://adnantopal.github.io/slimmenu/
make navbar like this with responsive

thank u

**Comment by mdo** [comment]
#27659
