### ISSUE TITLE
Material Input Field in which the placeholder becomes label on click

### ISSUE THREAD

**Issue by iamzaidsoomro** [twbs/bootstrap#36216]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please add a material input field in which the placeholder becomes a label on click. It has a border and a placeholder. When the input field is focused, the placeholder moves to the label. It is in the materialize.css framework, but I want it in my favorite framework Bootstrap.

### Motivation and context

This feature is used in modern web development and gives a interactive look to the static forms.an

**Comment by mdo** [comment]
Think floating labels cover this: https://getbootstrap.com/docs/5.1/forms/floating-labels/
