### ISSUE TITLE
Bug on select options

### ISSUE THREAD

**Issue by MatheusNep** [twbs/bootstrap#36222]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

- MacOS 11.6.5
- Chrome +Version 100.0.4896.127

![Captura de Tela 2022-04-22 às 14 06 22](https://user-images.githubusercontent.com/40609807/165135115-8ffe620e-b80e-4a2f-ae64-875a7118c563.png)

Scenario:
I'm using two monitors, the primary is a mac laptop(13.3 inches - 2560 × 1600) and the other one is a LG ultrawide screen(28.5 inches - 2560 × 1080). When i try to open the select options on the laptop screen it works fine, but when I open on wideScreen there is a problem. This problem just happens on mobile mode and does not happen on Safari and Firefox.

### Reduced test cases

https://getbootstrap.com/docs/5.0/forms/select/

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

**Comment by mdo** [comment]
This is very likely an issue with the dev tools mobile mode or the OS itself as we do not (and cannot) modify how select menus display their options. There's no positioning or styling on those from us.
