### ISSUE TITLE
Logo Different Size on Different Devices? 

### ISSUE THREAD

**Issue by davidhunternyc** [twbs/bootstrap#36234]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,
I'm trying to help my friend build a website on getbootstrap.com. I am having problems with her logo. On my MacBook Pro the "LEAF" logo is the perfect size. On my iPhone, the logo is way too small. On different devices and browsers the logo is many different sizes. What his the solution so that the logo is the same size relative to the device it is on? Your help is greatly appreciated. 

https://www.r-leaf.cz/en/home/

<img width="1728" alt="Screen Shot 2022-04-26 at 3 03 02 PM" src="https://user-images.githubusercontent.com/6060878/165374607-5d8d84ca-1031-4bd3-b7ce-02dd4afbfc92.png">

![IMG_0008](https://user-images.githubusercontent.com/6060878/165374620-84031eeb-689b-4ac6-b285-f5511ee3f7d5.jpg)

### Reduced test cases

https://www.r-leaf.cz/en/home/

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.1.0

**Comment by mdo** [comment]
This isn't a Bootstrap bug, so closing out.

That aside, your problem is likely that you're using a blanket `background-size: 25%` when you may need something additional for responsive behavior across mobile and desktop. Maybe only apply the background size styles at a particular media query?
