### ISSUE TITLE
RTLCSS doesn't compile as expected

### ISSUE THREAD

**Issue by christianboyle** [twbs/bootstrap#36232]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

According to the docs, it seems as if RTLCSS processing is broken:

For example, here in `_carousel.scss` we ignore lines `46-55`: https://github.com/twbs/bootstrap/blob/v5.1.3/scss/_carousel.scss#L45=

Presumably that would result in this block not appearing in the processed `bootstrap.rtl.css`, but that's not the case: https://github.com/twbs/bootstrap/blob/v5.1.3/dist/css/bootstrap.rtl.css#L6005=

Is there something I'm missing?

### Reduced test cases

No CodePen needed, due to the output being identical to the input.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment]
Yep: the ignore directive says RTLCSS to not proceed the code (eg. don't transform `left` to `right`), not to remove it. The remove directive says so.

Please have a look at RTLCSS documentation to learn more about the tool.

**Comment by christianboyle** [comment]
@ffoodd Ah, somehow I missed that in the RTLCSS docs. Thanks for pointing me in the right direction.
