### ISSUE TITLE
Negative margin

### ISSUE THREAD

**Issue by ct-viral** [twbs/bootstrap#36246]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

i have need **Negative margin** in my project,
i am using "**bootstrap": "^5.1.3**", vertion of bootstrap in my project,
i am change value of variable "**$enable-negative-margins:     true;**" wich mention in below given link

https://getbootstrap.com/docs/5.1/utilities/spacing/#negative-margin

and **recomplile the scss** but **Negative margin class are not avalable** in css file before compliing scss.

can you help me for that

### Reduced test cases

https://getbootstrap.com/docs/5.1/utilities/spacing/#negative-margin

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment]
This works as intended, so there may be something else off. Hard to know without seeing your setup. I'd suggest asking in Slack or a Discussion.

**Comment by mdo** [comment]
As I said already, this works as intended. Enable the variable and recompile the Sass. I've tested it myself locally.
