### ISSUE TITLE
Suggest a new feature

### ISSUE THREAD

**Issue by python-coding-404** [twbs/bootstrap#36251]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

please implement a esm file with popperjs esm

 

### Motivation and context

I found out that popperjs has esm files 
it be helpful for people that need esm

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.1/getting-started/javascript/#using-bootstrap-as-a-module
