### ISSUE TITLE
Font Awesome icons cause menu titles to move to second line

### ISSUE THREAD

**Issue by Mythotical** [twbs/bootstrap#36256]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When implementing font awesome manually instead of built-in, adding icons to navbar items causes the titles to move to a second line as seen in the screenshot.

![Serenity Development](https://user-images.githubusercontent.com/7572268/166134255-877ad768-3991-4fd4-8ddd-56fc9447f266.png)

### Reduced test cases

I have no idea for a solution or any test cases.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Can't help without a reduced test case or live example. I'm guessing the images are block-level or something from some other custom styles.

**Comment by Mythotical** [comment]
> Can't help without a reduced test case or live example. I'm guessing the images are block-level or something from some other custom styles.

Yes, they are block but I have used them on another site utilizing Bootstrap and they display on the navbar perfectly fine.

**Comment by Mythotical** [comment]
So I had to move the classes from where they were to the <li> tag which fixed everything.
