### ISSUE TITLE
Truncate floating labels

### ISSUE THREAD

**Issue by gerhard-lechner** [twbs/bootstrap#36270]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I realised that floating labels tend to get ugly if the label text is longer than the input field, pls see my pen link below.

This can be fixed by adding .w-100 and .text-truncate to the label. However, I would like to suggest that this should be the default without the need for any additional classes as a multiline floating label is never desirable.

### Reduced test cases

https://codepen.io/gerhard-lechner/pen/GRQgQyW

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1

**Comment by mdo** [comment]
What's the typical use case for super long labels like that?

**Comment by gerhard-lechner** [comment]
Sorry about the title.

My real-world scenario is more a combination of a smaller field (on mobile) and a somewhat longer label: In a registration form you can enter a name prefix like "Dr." and also a name suffix like "MBA". These fields are typically not very large as the input value is most likely short too. In German one would use labels like "Titel vorangestellt" and "Titel nachgestellt". So not super long, but can be a bit longer than the field on mobile, see screenshots attached.

<img width="927" alt="desktop" src="https://user-images.githubusercontent.com/270320/166553458-bdb47637-c344-4c3e-91c4-fd557e43107f.png">

<img width="374" alt="mobile" src="https://user-images.githubusercontent.com/270320/166553466-fafafb7c-09bf-410a-acda-282914000c62.png">

When cutting these labels you still get what the input value ought to be and avoid kind of a UI bug ...

<img width="376" alt="fixed" src="https://user-images.githubusercontent.com/270320/166553776-efde382d-7b40-4ab4-90ad-70a16897d113.png">
