### ISSUE TITLE
Doc: Extra top padding after having clicked on anchor links

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#36278]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

An extra padding top is created for each section after having clicked on the anchor links in the documentation.

#### Basic rendering

<img src="https://user-images.githubusercontent.com/17381666/166955253-c241abc0-cbd0-4d19-ba09-18cd7b46d29f.png" width="400"/>

#### Rendering after the manipulation (with the extra top padding)

<img src="https://user-images.githubusercontent.com/17381666/166955716-f5c50bae-6e38-4382-b8f4-eb5aa1d66429.png" width="400"/>

I haven't looked at the issue precisely but this is probably related from near and far to:

```scss
.bd-content>:target {
 padding-top:5rem;
 margin-top:-5rem
}
```

It has changed in https://github.com/twbs/bootstrap/commit/195440f2fb1e94c014a9cf08f3eae40f3d224620.

Nothing has been tested yet on my side but there was another system in place before apparently based on:
```scss
// Offset for the sticky header
@include media-breakpoint-up(md) {
  :root {
    scroll-padding-top: 4rem;
```

**Note:** It happens with all breakpoints.

#### 1st test case

After having clicked on "Importing", the padding-top stays on top until the page is refreshed.

![Peek 2022-05-05 08-43](https://user-images.githubusercontent.com/17381666/166874949-985e4124-53b9-4a95-9136-42f5d6fed228.gif)

#### 2nd test case

It is maybe more obvious in this video. We can directly see the extra padding on top of "CSPs and embedded SVGs" that's added even if the content is not near the header.

![Peek 2022-05-05 08-43 (2)](https://user-images.githubusercontent.com/17381666/166875054-308e27d5-9cb5-459a-b463-5f70e7df9f14.gif)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0 (current _main_ branch)

**Comment by Catalyst497** [comment]
I think I am have found a solution to this. 
Please assign it to me.

**Comment by julien-deramond** [comment]
Hey @Catalyst497 . We don't affect issues but you can create a PR to provide a solution :)
