### ISSUE TITLE
Move away from Google Universal Analytics

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#36279]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

[Google Universal Analytics is deprecated and will stop tracking all hits from next year](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/#:~:text=All%20standard%20Universal%20Analytics%20properties%20will%20stop%20processing%20new%20hits%20on%20July%201%2C%202023%2C%20and%20360%20Universal%20Analytics%20properties%20will%20stop%20processing%20new%20hits%20on%20October%201%2C%202023.%20After%20that%2C%20you%E2%80%99ll%20be%20able%20to%20access%20your%20previously%20processed%20data%20in%20Universal%20Analytics%20for%20at%20least%20six%20months). There is no way to import the UA analytics to GA4 either :-( . The Bootstrap site should switch to a different analytics provider.

I personally recommend: https://plausible.io/ for many reasons:

- You can connect to Google and do a one-time import of your Universal Analytics data for a seamless transition
- lightweight (1 KB) and open-source script
- It doesn't use cookies at all (so GDPR and CCPA cookie law compliant)
- It doesn't track individual users
- I think the dashboard is faster and easier to use.
- If hosting on Netlify you can easily setup a proxy to avoid adblockers from negatively impacting your pageview stats. (https://plausible.io/docs/proxy/guides/netlify)

### Motivation and context

I'm not affiliated with Plausible, but just a big fan :-)  I think https://usefathom.com/ offers a similar service...  or you could stick with Google and switch to GA4. This issue really was just to keep track that some change will be needed sooner or later due to UA closing.

**Comment by mdo** [comment]
I’ve been a fan of Fathom for awhile and even tested it out last year or so. Thinking after talking to them on Twitter that I’ll bring that back and drop GA. Might try to squeeze it into v5.2.0 as well. Thanks for prompting!

**Comment by coliff** [comment]
hey @mdo - Now that [Google's Universal Analytics is going to stop processing data in a few weeks time](https://support.google.com/analytics/answer/11583528?hl=en#:~:text=On%20July%201%2C%202023%2C%20standard%20Universal%20Analytics%20properties%20will%20stop%20processing%20data) I think it makes sense to completely remove the Google tracking script from the site templates.
