### ISSUE TITLE
Returning focus to page after clicking anchor link in offcanvas menu

### ISSUE THREAD

**Issue by cfenwick76** [twbs/bootstrap#36289]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Some of the links in the offcanvas menu on the the site I'm developing here https://helenboardman.com/home/ are anchor links that jump to specific sections on the page. I'm using the following code to close the offcanvas menu when one of these links is clicked...

`// Hide offcanvas menu when nav link is clicked
	$('.offcanvas .nav-link').on('click', function() {
        $('.offcanvas').removeClass('show');
		$('.offcanvas-backdrop').removeClass('show');
		$('#offcanvasNav').css('visibility', 'hidden');
		$("#offcanvasNav").removeAttr('role');
    });`

...which works ok. But it seems that the page loses focus after this happens. So you have to first click the page to return focus, and then click on whatever link or element you want to interact with. Is there anything I can do to automaticlly return focus to the page when the menu closes after clicking an anchor?

### Reduced test cases

https://helenboardman.com/home/

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by CastorCZ** [comment]
Hello, 

i have the same problem. I try to solve the problem around 6 hour and now i have solution. Like as always pretty easy... I use timeout to trigger on button with data-bs-toggle.

`<button class="navbar-toggler" id="bs_button" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas">`
`<span class="navbar-toggler-icon"></span>`
`</button>`

`$('#offcanvas .nav-link').on('click', function() {`
`$('#offcanvas').removeClass('show');`
`$('#top').css('overflow', ''); // <body>`
`$('#top').css('padding', ''); // <body>`
`$('.navigace').css('padding', ''); // set padding 0 to my navbar div, you can escape this line`
`$('#offcanvas').css('visibility', 'hidden');`
`$("#offcanvas").removeAttr('role');`
`$("#offcanvas").removeAttr('aria-modal');`
`setTimeout(function () {`
		 `$("#bs_button").trigger("click");`
`}, 800);`
`});`

**Comment by cfenwick76** [comment]
Thanks very much Dan, this worked a treat!!!

**Comment by y377** [comment]
> // Hide offcanvas menu when nav link is clicked $('.offcanvas .nav-link').on('click', function() { $('.offcanvas').removeClass('show'); $('.offcanvas-backdrop').removeClass('show'); $('#offcanvasNav').css('visibility', 'hidden'); $("#offcanvasNav").removeAttr('role'); });
## Can we make good use of code highlighting? So the same problem is easy for others to refer to, multiple lines of code please use **```**and end with**```**
```js
// Hide offcanvas menu when nav link is clicked
$('.offcanvas .nav-link').on('click', function() {
    $('.offcanvas').removeClass('show');
    $('.offcanvas-backdrop').removeClass('show');
    $('#offcanvasNav').css('visibility', 'hidden');
    $("#offcanvasNav").removeAttr('role');
});
```

**Comment by julien-deramond** [comment]
Agree with @y377. I've edited both messages in the thread. Please keep that in mind for the next ones ;)
