### ISSUE TITLE
Responsive font size issue

### ISSUE THREAD

**Issue by StefanGhiban** [twbs/bootstrap#36287]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi! I have an issue regarding overriding font sizes. Locally I do not have any issues overriding variables, but on a staging environment with docker, the font-sizes that I am overriding are becoming negative. 
This image represents the local version. The responsive font sizes variable is enabled and the overridden value for the display 2 is represented by that 1.75rem value.
<img width="294" alt="image" src="https://user-images.githubusercontent.com/47953165/167111226-63e13d40-4fb7-4238-b521-b96816892c2c.png">

And this is the staging environment with docker where the display 2 font size is negative, but the same 1.75 rem as in the photo above. Because the value is negative, bootstrap turns to the default from the node modules file.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/47953165/167114165-63409ff8-23a5-4720-98bc-3f7acc40b7da.png">

### Reduced test cases

-

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.5.0

**Comment by mdo** [comment]
It looks like you have double the CSS perhaps? Hard to say without any kind of demo or extra details. How are values becoming negative?

**Comment by mdo** [comment]
Closing for now until we hear more since this isn't an issue in our docs usage.
