### ISSUE TITLE
Long content scrolling in v5.2.0 Modal does not work

### ISSUE THREAD

**Issue by cccabinet** [twbs/bootstrap#36295]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Long content scrolling in v5.2.0 Modal does not work in Chrome & Edge.
But it works in Firefox.

I hope for a solution.

### Reduced test cases

ｖ5.1.3
https://getbootstrap.com/docs/5.1/components/modal/#scrolling-long-content
![v5 1 3](https://user-images.githubusercontent.com/26200725/167255346-49f9775f-60f3-4615-8a23-ded9b2e599b6.gif)

v5.2.0
https://twbs-bootstrap.netlify.app/docs/5.1/components/modal/#scrolling-long-content
![v5 2 0](https://user-images.githubusercontent.com/26200725/167255374-f45fb417-e316-4e3c-acac-3da4d3c0665d.gif)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.2.0（main)

**Comment by beyzad-asa** [comment]
Propably https://github.com/twbs/bootstrap/pull/35554

**Comment by cccabinet** [comment]
Have you already raised the issue? I didn't notice it because it was merged. sorry.

**Comment by julien-deramond** [comment]
> Propably https://github.com/twbs/bootstrap/pull/35554

Good catch for the origin. Scrolling in https://github.com/twbs/bootstrap/commit/aa650f0f1e30279f0868433a4afab9c3efa93b2c works and the next one (https://github.com/twbs/bootstrap/commit/dcbe7b6f31d5383ea9e0203fd68c0a5e99fa97b7) coming from this PR don't.

**Comment by julien-deramond** [comment]
Actually this issue is mentioned in this thread beginning with https://github.com/twbs/bootstrap/pull/35554#discussion_r769868597. The issue comes from https://github.com/twbs/bootstrap/blob/4207544c0e392ba375d584c993641d7f410d2fa6/scss/_modal.scss#L44

Removing it makes the scroll works again in Chrome.

I don't know the details about it but if it is not possible to remove this CSS rule, one option would be maybe to force `.pe-auto` (used at the same level than `.modal`) only for the scrolling long content example.

**Comment by GeoSot** [comment]
Unfortunately, if we remove 'pointer-events:none' it will not be able for the backdrop element to catch the click event, so wishing I am not wrong, is one way or the old way (reverting the PR)
