### ISSUE TITLE
vstack changing to hstack on medium-sized devices

### ISSUE THREAD

**Issue by titouandk** [twbs/bootstrap#36290]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello,

I think it would be nice to have a vertical stacking on mobiles changing to a horizontal stacking on PCs.

**Pseudocode**

```html
<div class="vstack hstack-md gap-2 ...">
    <button ...>
    <button ...>
</div>
```

**Render on small screens**
![image](https://user-images.githubusercontent.com/5413308/167143343-51dc1328-3035-4e44-8562-3c7c2bbbee48.png)

**Render on larger screens**
![image](https://user-images.githubusercontent.com/5413308/167142851-db7a3cd6-1c16-4a26-b4e5-e89516689925.png)

### Motivation and context

It may be usefull to easily fit buttons next to each others on large screens, but on top of each others on larger screens.

**Comment by mdo** [comment]
This could likely be best done via utilities on top of the helpers, just to keep things tidier. Try some of our flex utilities for now while we look into it, `.flex-md-row` on a `.vstack` for example.

**Comment by mdo** [comment]
Going to leave this as a won't fix for now since the flex utilities address it for now.
