### ISSUE TITLE
Add smooth scroll option to Scrollspy

### ISSUE THREAD

**Issue by SamuelMiller** [twbs/bootstrap#36291]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please consider adding a smooth scroll option to Bootstrap 5's Scrollspy.  Currently enabling CSS smooth scrolling does not work with Scrollspy. Clicking on links continues to jump right to the id anchor. 

### Motivation and context

A common solution, somewhat outdated, is to use the smooth scrolling functionality in jquery. After some searching, I came across a simple Javascript solution, which also updates the URL to id anchors,  that works in Chromium and Firefox-based browsers but not Safari. The JS smooth option, ([Element.scrollIntoView(), is not supported by Safari--Web APIs | MDN 192](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#browser_compatibility)).

Simple Smooth Scrolling Javascript (does not work in Safari):
```
let anchorlinks = document.querySelectorAll('a[href^="#"]')

for (let item of anchorlinks) { // relitere 
    item.addEventListener('click', (e)=> {
		let hashval = item.getAttribute('href')
		let target = document.querySelector(hashval)
		target.scrollIntoView({
			behavior: 'smooth'
		})
		history.pushState(null, null, hashval)
		e.preventDefault()
	})
}
```
A forum suggested https://www.npmjs.com/package/seamless-scroll-polyfill to get smooth scrolling working in Safari/Apple browsers, but I haven't been able to get to work yet in Bootstrap. 

It would be great if Boostrap offered a quick and simple solution to enable smooth scrolling with Scrollspying in all browsers.

**Comment by GeoSot** [comment]
[v5.2](https://github.com/twbs/bootstrap/projects/32) is coming,,,,,, ❄️ 

New scrollspy with smooth-scroll addition, is merged https://github.com/twbs/bootstrap/pull/33421

https://github.com/twbs/bootstrap/blob/6b49d26b21cabb7322a820183c6d925263cddba1/js/src/scrollspy.js#L116-L139


However, instead `target.scrollIntoView`, `scrollTo` is used (can be changed of course)


And `history.pushState(null, null, hashval)` is another 'feature' we can discuss too

**Comment by SamuelMiller** [comment]
Github-actions, dIdn't GeoSot already submitted a patch which has been merged. Do you still want me to demonstrate the issue on CodePen or JS Bin? Or was your statement for next time I submit a bug?

**Comment by GeoSot** [comment]
I can close the issue as the 'smoothScroll` is already implemented, however I would like your opinion regarding this (if there is any special reason)
> And history.pushState(null, null, hashval) is another 'feature' we can discuss too

**Comment by SamuelMiller** [comment]
I am happy to test it. Is there an already bundled beta js file I can access?

**Comment by SamuelMiller** [comment]
Popping in the beta bootstrap.bunddle.js into my site, replacing the last stable version, disables the auto highlighting of the menu item as one scrolls through the id-marked sections of the page. In addition, the URL is not updated as one scrolls through the sections id. 

I think that is where "history.pushState" could be helpful in keeping the URL updated to where the user is on the page. 


Regarding,  I am across "history.pushState(null, null, hashval)" as a way to deal with URLs not updating on the same page:
"One of the most common problems with long scrolling is that sharing a URL to a particular spot on the page is impossible: The user’s scroll position isn’t reflected in the URL, and the URL leads to the top of the page. The user will become easily frustrated when they can’t easily switch between devices to continue browsing from their current spot because the URL doesn’t capture that spot. Starting with HTML5, changing the URL displayed in the browser without reloading the page is possible. The [history.pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API) function enables us to invoke a URL change without reloading the page, thus allowing us to match the scrolling behaviour to the user’s expectation." 

I think we need to test this more before releasing 5.2. I'll see if I can put up a test on Codepen to share here.

**Comment by SamuelMiller** [comment]
Here is an example, using Jquery, of the URL change on scroll feature I am suggesting for bootstrap's js library. 
As you scroll down to the below sections, the section is appended to the URL.
http://scrollsample.appspot.com/items
