### ISSUE TITLE
Bug: btn-link box-shadow visible on focus

### ISSUE THREAD

**Issue by bodydisplaynone** [twbs/bootstrap#36308]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I just noticed a bug on Bootstrap 4.6 where the buttons scss is missing the box-shadow: 0 declaration for btn-link.

BS 4:
![image](https://user-images.githubusercontent.com/22660372/167412883-1a3e8d76-083a-4045-81e0-78258a88e367.png)

BS 4.6
![image](https://user-images.githubusercontent.com/22660372/167412952-d962b535-f34f-44a1-a32a-5238c31f4c73.png)

This causes a weird button outline when leaving or toggling the button in :focus state.

### Reduced test cases

https://codepen.io/team/bootstrap/pen/yLabNQL

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

4.6

**Comment by mdo** [comment]
Not a bug: #30036.
