### ISSUE TITLE
Impossible to search on mobile with new DocSearch v3

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#36306]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

As soon as the DocSearch v3 popup is displayed from the offcanvas under 991px breakpoint, it is impossible to use the input and so to search in the documentation.

I don't think it is an issue coming from DocSearch v3 since search in https://docsearch.algolia.com/docs/how-does-it-work works pretty well on mobile. This is maybe coming from the fact that it is triggered from the offcanvas in the menu :shrug: 

### Reduced test cases

Set your browser in responsive design mode at a width of 991px or under; or try it from a mobile phone.

1. Go to https://twbs-bootstrap.netlify.app/docs/5.1/getting-started/introduction/
2. Click on the "..." menu
3. Click on "Search" → Search popup is displayed
4. The input doesn't gain automatically the focus and clicking on it neither

_You don't see it in the following .gif but I'm trying to click on the input_ :innocent: 

![Peek 2022-05-08 13-02](https://user-images.githubusercontent.com/17381666/167293264-b89b3fb4-55b4-44d9-999d-ad139391a01c.gif)

### What operating system(s) are you seeing the problem on?

Android, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.0 (current _main_ branch)

**Comment by mdo** [comment]
Oh well crap, that's no good. Will dig in more (like tomorrow).
