### ISSUE TITLE
Migrate use of @import in scss to @use

### ISSUE THREAD

**Issue by SamuelMiller** [twbs/bootstrap#36304]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently, Bootstrap scss uses the @import command, which is being phased out according to sass-lang.com

https://sass-lang.com/documentation/at-rules/import
"The Sass team discourages the continued use of the @import rule. Sass will [gradually phase it out](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline) over the next few years, and eventually remove it from the language entirely. Prefer the [@use rule](https://sass-lang.com/documentation/at-rules/use) instead. (Note that only Dart Sass currently supports @use. Users of other implementations must use the @import rule instead.)"

They offer a migrator tool, which would make updating the scss files fairly easy: https://sass-lang.com/documentation/cli/migrator

### Motivation and context

To keep up with the times, man! :)

**Comment by ffoodd** [comment]
Duplicates #29653.

On our roadmap for ages, but would be a breaking change in v5. Easy to migrate Bootstrap's core, not really to force  a dependency update for millions of users. 😉
