### ISSUE TITLE
Sass compiler warning

### ISSUE THREAD

**Issue by chen900804** [twbs/bootstrap#36336]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Sass compiled newspaper

1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 1 warning

### Reduced test cases

I tried to modify the file

_ form-check. scss

  //color-adjust: exact; // Keep themed appearance for print

If I comment out this code, there will be no warning.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment]
Duplicates #36259.
