### ISSUE TITLE
Their is a vocabulary mistake in Doc page

### ISSUE THREAD

**Issue by dheerajsingh544** [twbs/bootstrap#36349]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

vocabulary mistake in `Doc>Introduction> Next steps`

### Reduced test cases

doc

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by julien-deramond** [comment]
The associated PR is closed. IMO this issue can be closed as well.
