### ISSUE TITLE
Offcanvas transition on mobile is wonky

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#36347]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When opening offcanvas menus on the docs when on a phone or narrow viewport, the transition is a little wonky. It looks like the backdrop is fading in first and then the drawer is coming in. What should happen is the fade and draw happen at the same time.

### Reduced test cases

https://getbootstrap.com

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by XhmikosR** [comment]
Confirmed I see it on Windows 10 with Firefox. It's like the backdrop fires up immediately but the offcanvas hasn't finished transitioning.

**Comment by justinkruit** [comment]
Noticing the same on Chrome on Android.

**Comment by Nudasoft** [comment]
Yeah! it's slow.
