### ISSUE TITLE
Remove rules duplicate `.img-fluid` from `.img-thumbnail`

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#36359]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Remove 
https://github.com/twbs/bootstrap/blob/46bb9e78d74e0c7f4fa6f6fa611f3d9f8f28860b/scss/_images.scss#L22

### Motivation and context

`<img class="img-fluid img-thumbnail" ...>` looks more correct in Bootstrap context

**Comment by mdo** [comment]
This would be a breaking change, so it'd have to be for v6. That said, I'm not opposed, but I'm not sure how much it saves us vs the developer inconvenience. Labelling and closing for now, thanks!
