### ISSUE TITLE
Bootstrap 5 | "boundary" option not working on Dropdowns

### ISSUE THREAD

**Issue by jfmdev** [twbs/bootstrap#36358]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm can't change the `boundary` option (mentioned in the [docs](https://getbootstrap.com/docs/5.0/components/dropdowns/#options)) from Dropdowns to be the body (or any other element rather than the default value), I'm doing something like:

```js
import { Dropdown } from "bootstrap";
...
new Dropdown(document.getElementById('my-dropdown'), { 
  boundary: document.querySelector('body')
});

```

But the `boundary` parameter is completely ignored.

### Reduced test cases

Codepen example: https://codepen.io/jfmdev/pen/oNEYdBr

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by jfmdev** [comment]
Related to https://github.com/twbs/bootstrap/issues/35774

**Comment by sot-geo** [comment]
You are probably searching ofr this

```js

new Dropdown(document.getElementById('my-dropdown'), { 
  boundary: document.querySelector('body'),
  popperConfig: function (defaultBsPopperConfig) {
            return { ...defaultBsPopperConfig, strategy: "fixed"};
        }
});

```

right?

**Comment by GeoSot** [comment]
You are probably searching ofr this

```js

new Dropdown(document.getElementById('my-dropdown'), { 
  boundary: document.querySelector('body'),
  popperConfig: function (defaultBsPopperConfig) {
            return { ...defaultBsPopperConfig, strategy: "fixed"};
        }
});

```

right?

**Comment by jfmdev** [comment]
@GeoSot Yes! That seems to solve the issue. Thanks!

**Comment by GreathostRo** [comment]
After more than a few hours and various attempts I found the working version:

```
const dropdowns = document.querySelectorAll('.dropdown-toggle')
const dropdown = [...dropdowns].map((dropdownToggleEl) => new bootstrap.Dropdown(dropdownToggleEl, {
    popperConfig(defaultBsPopperConfig) {
        return { ...defaultBsPopperConfig, strategy: 'fixed' };
    }
}));
```
