### ISSUE TITLE
Docs header seems flashing when scroll in Firefox

### ISSUE THREAD

**Issue by Guleixibian2009** [twbs/bootstrap#36354]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The purple header in the newest docs(v5.2) seems to be flashing when scrolling the page *but only in Firefox*. Looks normal in `-webkit-` browsers. I dunno if it's a bug or it doesn't have anything to do with `Bootstrap` but my browser.

### Reduced test cases

Maybe.. Just try scrolling?

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0-beta.1

**Comment by beyzad-asa** [comment]
I can't confirm it. using v100 and its ok

**Comment by Guleixibian2009** [comment]
Well I'm using 99.0. I am updating it now to retry that.

**Comment by Guleixibian2009** [comment]
I have updated Firefox but the problem is still there. Hey @beyzad-asa did you test that only in the homepage or in **one of the docs pages**(e.g. [Get started with Bootstrap](https://getbootstrap.com/docs/5.2/getting-started/introduction/))? This problem doesn't exist in the homepage... :sweat:

**Comment by beyzad-asa** [comment]
> I have updated Firefox but the problem is still there. Hey @beyzad-asa did you test that only in the homepage or in **one of the docs pages**(e.g. [Get started with Bootstrap](https://getbootstrap.com/docs/5.2/getting-started/introduction/))? This problem doesn't exist in the homepage... sweat

Tested in doc page. May be you installed some addons? try in private window. idk

**Comment by Guleixibian2009** [comment]
> Tested in doc page. May be you installed some addons? try in private window. idk
> PS: I use ubuntu

Still flashing in private window... I'll give you a gif later

**Comment by Guleixibian2009** [comment]
U can find an example [here](https://github.com/Guleixibian2009/Guleixibian2009/blob/GitHub-Drive/2022-05-15-20-20-45.mp4).

**Comment by Guleixibian2009** [comment]
![](https://user-images.githubusercontent.com/79316026/168472735-2fdcb34b-56e2-425a-9fe8-72af3cfa33b9.mp4)

**Comment by Guleixibian2009** [comment]
The recording is not that authentic... But still U can see flashing in that

**Comment by mdo** [comment]
Struggling to reproduce this myself, so going to close out for now. If someone has any ideas what might be going on, I'm more than happy to take another look.
