### ISSUE TITLE
Modal focus trap is not working the same way it does in documentation page

### ISSUE THREAD

**Issue by wisniewski94** [twbs/bootstrap#36368]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If you open this page and launch the first modal, tab through it you should be able to stay inside that modal, meaning no other parts of the browser & page should be focused:

https://getbootstrap.com/docs/5.0/components/modal/

and this is working as expected. However, if you look into that StackOverflow question and a demo you will notice that after moving to the last focusable element the browser UI is selected:

https://stackoverflow.com/questions/72215340/bootstrap-modal-focus-trap-behaving-differently-on-bs-webpage

### Reduced test cases

https://jsbin.com/hutuhufuyi/edit?html,output

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment]
Your JSBin uses Bootstrap 4.1, not 5.1. Seems legit it doesn't work the same.

**Comment by codee202** [comment]
> Your JSBin uses Bootstrap 4.1, and you're linking 5.0 documentation. Seems legit it doesn't work the same.
> 
> BTW the latest v5 is 5.2-beta-1.

Even if you use the v 4.6 the same issue is present. 

https://jsbin.com/zadavagifo/edit?html,js,output

VS

https://getbootstrap.com/docs/4.6/components/modal/

**Comment by lalmeras** [comment]
My feedback as I just stumble into this, and it is quite frustrating. Seems that bootstrap focustrap can work only if modal is not the last focusable element in page.

Focus behavior is OK on bootstrap documentation as there is plenty of buttons or links after each modal. Adding a `<a href=""></a>` at body's end on the provided broken examples made it work as expected.

I think this focusable element outside modal allows to trigger bootstrap focustrap mechanism to bring back focus to modal. If there is no focusable element, then focus is passed to browser UI and bootstrap cannot override it.
