### ISSUE TITLE
`.h-*` classes change color of anchor

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#36365]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`.h-*` classes adds to `<a>` tags must keep anchor color.
Need fix like this:
~~~scss
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 {
  margin-top: 0;
  margin-bottom: .5rem;
  font-weight: 500;
  line-height: 1.2;
}
h1, h2, h3, h4, h5, h6,
.h1:not(a), .h2:not(a), .h3:not(a), .h4:not(a), .h5:not(a), .h6:not(a) {
  color: var(--bs-heading-color);
}
~~~

### Reduced test cases

~~~html
<a href="#" class="h5">Link-title</a>
<a href="#" class="link-danger h5">Link-title</a>
~~~

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.2.0

**Comment by Kopyov** [comment]
Alternatively you can use 
```
<h5>
    <a href="#" class="link-danger">Link title</a>
</h5>
```
where link color doesn't get overridden by heading color

**Comment by WinterSilence** [comment]
@Kopyov I'm aware, captain Obvious

**Comment by Kopyov** [comment]
@WinterSilence So use it like this then. Following your suggestion and for the sake of consistency we would also need to re-use this logic in other elements such as dropdown items, nav links etc.

**Comment by mdo** [comment]
That's an interesting suggestion, but I don't think one we'll implement. It adds a good amount of specificity to what's otherwise a set of helpful utilities.

> @Kopyov I'm aware, captain Obvious

There's no need for name calling or attitude either, so please skip posting comments like that :).

**Comment by WinterSilence** [comment]
@mdo Current implementation of `.h*` classes does not correspond to concept of utilities. Utilities changes something one: color, size, padding and yet.

**Comment by mdo** [comment]
Yes, my bad, they're helpers.

**Comment by WinterSilence** [comment]
@mdo I don't think undocumented modification of existing helpers is a good idea, it's BC for me

**Comment by mdo** [comment]
> @mdo I don't think undocumented modification of existing helpers is a good idea, it's BC break for me

We haven't made any undocumented changes.

**Comment by WinterSilence** [comment]
@mdo i can't find this changes in https://github.com/twbs/bootstrap/releases/tag/v5.2.0-beta1

**Comment by mdo** [comment]
There have been no changes to our heading classes in v5.2.0-beta1. I don't know what you're looking for or expecting to see.

**Comment by WinterSilence** [comment]
@mdo
in 5.2.:
~~~css
.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
  margin-top: 0;
  margin-bottom: .5rem;
  font-weight: 500;
  line-height: 1.2;
  color: var(--bs-heading-color);
}
~~~
in 5.1:
~~~css
.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
  margin-top: 0;
  margin-bottom: .5rem;
  font-weight: 500;
  line-height: 1.2;
}
~~~
https://codepen.io/WinterSilence/pen/KKQvKPQ?editors=1000

**Comment by WinterSilence** [comment]
@mdo it's your changes https://github.com/twbs/bootstrap/blame/main/scss/_reboot.scss#L90

**Comment by mdo** [comment]
Sorry, I knew I should've been more specific. There's been no _functional_ change to the headings in v5.2.0-beta1. Heading color has always been a `null` value, and now so is `color: var(--bs-heading-color)`. Look at `:root` and you'll find `--bs-heading-color: ;`. There's no new color being set here, despite the addition of the CSS variable.

In v5.2.0-beta1, now with CSS variable:

https://github.com/twbs/bootstrap/blob/fca04c07131a81e625a516cf7b98a8c7df0df1c1/scss/_reboot.scss#L83-L91

And in the browser, you can see that it takes no effect because the variable is empty:

<img width="446" alt="Screen Shot 2022-05-21 at 10 25 07 AM" src="https://user-images.githubusercontent.com/98681/169662633-b210db88-0bc5-4e2a-bff4-78261cb0f016.png">

In v5.1.3, with the Sass variable (also set to `null` in `_variables.scss`):

https://github.com/twbs/bootstrap/blob/1a6fdfae6be09b09eaced8f0e442ca6f7680a61e/scss/_reboot.scss#L88-L96

Sass takes a property with `null` value and removes it from the compiled CSS. But that doesn't happen with CSS variables, they just get rendered out there. We could perhaps do a null CSS variable check and remove the property entirely, but that prevents the use case of CSS variables entirely.

**Comment by WinterSilence** [comment]
@mdo as I'm already say, your changes style of `<a class="h*">`.

**Comment by WinterSilence** [comment]
@mdo in 5.2:
![изображение](https://user-images.githubusercontent.com/3521094/169662881-244c0deb-2d61-4fb5-a3e0-e822b8c34a5d.png)
in 5.1:
![изображение](https://user-images.githubusercontent.com/3521094/169662952-907bb094-fb94-44bf-9836-742b76b20b25.png)

**Comment by mdo** [comment]
Ah, I see it now. Sorry for the back and forth—next time please include actual Codepen demos vs just snippets here :). Or include those kind of screenshots. I should've looked more closely though, too.

Let me reopen this and jump back into it for our stable release to see if there's a more logical fix than a slew of more specific `:not()` selectors.

**Comment by WinterSilence** [comment]
@mdo 
> next time please include actual Codepen demos vs just snippets here :). Or include those kind of screenshots. I should've looked more closely though, too.

Ok, no problem. Please, if you don't understand issue reasons,  don't close it - you can always ask clarifying questions.

**Comment by WinterSilence** [comment]
@mdo 👍🏻

**Comment by UtkarshVerma** [comment]
I think this has surfaced again in v5.3.0. Could you please reopen this? @mdo

**Comment by julien-deramond** [comment]
@UtkarshVerma Would you mind creating a new issue with a CodePen (or other) to show the problem? We tend not to reopen issues closed by a PR so that future selves are able to read easily the complete history and find stuff in the past.

**Comment by UtkarshVerma** [comment]
@julien-deramond Sure, here is the pen: https://codepen.io/UtkarshVerma/pen/MWzopyq

**Comment by maritto** [comment]
are there plans to address this issue and if so could you share an ETA for it?
if there is already another issue open regarding this could you please link it here ? @mdo @julien-deramond
