### ISSUE TITLE
Fix behavior of "Open on StackBlitz" button

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#36364]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Need normalize copied examples:
1. Remove "doc" classes like as `.bd-placeholder-img` 
2. Replace svg placeholders to images displaying svg file(`<img src="/path/to/placeholder.svg" alt="">`) like as:
~~~svg
<svg xmlns="http://www.w3.org/2000/svg">
<rect width="100%" height="100%" fill="#868e96"></rect>
<text x="50%" y="50%" text-anchor="middle" fill="#dee2e6">Image</text>
</svg>
~~~

### Motivation and context

Get an example as close as possible to the real code.

**Comment by mdo** [comment]
Closing this one out as it's covered in #36391.
