### ISSUE TITLE
Switch not working

### ISSUE THREAD

**Issue by mmonteiroc** [twbs/bootstrap#36375]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The switches are not working on firefox mobile - Only in the ipad version.

This screenshot is from your own documentation, meaning that the issue is unrelated to our implementation, and that you have a reproducible code 
![image](https://user-images.githubusercontent.com/28816737/168743435-9aa5c7b2-6359-4588-9b30-ac7b9baf84e9.png)

### Reduced test cases

Open the switches documentation in a firefox - ipad 

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Firefox - ipad version
### What version of Bootstrap are you using?

5.2

**Comment by mdo** [comment]
Checked on both iPhone and iPad—no issues here for me. Perhaps there's some setting enabled or something else going on for you?
