### ISSUE TITLE
New smooth scroll option in ScrollSpy not working

### ISSUE THREAD

**Issue by SamuelMiller** [twbs/bootstrap#36372]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Using the latest js and css beta 5.2 Bootstrap, I am unable to get the new smooth scroll option in Scrollspy to work on the website I am starting to develop, using ` <div data-bs-spy="scroll" data-bs-target=".navbar" data-bs-smooth-scroll="true">` Clicking on scroll-to links in the top menu jumps to the anchor sections rather than smoothly scroll as it did before. There is no difference. I thought there might be a conflict with CSS scroll snap. But disabling that class in the CSS does not change anything. 

### Reduced test cases

I've duplicated the issue on Codepen, including custom Javascript:
https://codepen.io/sam-miller-the-flexboxer/pen/BaYpvPL

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

beta 5.2v

**Comment by GeoSot** [comment]
Maybe `smoothScroll` is misleading, as its main purpose is to stop doc scrolling. 
Although, here is the place you could experiment on https://github.com/twbs/bootstrap/blob/416f4905f13c2ca3096343e0a5a4934c8c0ced3f/js/src/scrollspy.js#L130:L145

changing to something like `root.scrollTo({ top: height, behavior: 'smooth' })` and open a PR 😃

**Comment by SamuelMiller** [comment]
The documentation (https://getbootstrap.com/docs/5.2/components/scrollspy/) is not clear. It states that smooth scroll "enables smooth scrolling when a user clicks on a link that refers to ScrollSpy observables." The term "smooth scrolling" usually refers to the animated smooth scrolling effect when clicking on a link to a different part of the page. For an example, see https://codepen.io/prvnbist/pen/GQMPZq  click on a menu item in the top right and see how the page slowly scrolls to the section. If that's not the effect that "smooth scroll" does in ScrollSpy bootstrap 5.2 then the term should be changed IMHO.
