### ISSUE TITLE
Cannot reduce select with `form-control-sm`

### ISSUE THREAD

**Issue by lonix1** [twbs/bootstrap#36373]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A `select` tag cannot be made smaller with the `form-control-sm` class, when used in conjunction with `form-select`.

The reason is `form-select` overrides the rules in `form-control-sm`.

### Reduced test cases

From [docs](https://getbootstrap.com/docs/5.1/forms/form-control/#sizing), but with addition of `form-control-sm`:

````html
<div class="row">
  <label for="test" class="col-sm-2 col-form-label form-control-sm">Test</label>
  <div class="col-sm-10">
    <select id="test" class="form-select form-control-sm">
      <option></option>
      <option>Foo</option>
      <option>Bar</option>
      <option>Baz</option>
    </select>
  </div>
</div>
````

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.1.3

### Workaround
Manually apply rules (from `form-control-sm`) to the select:
````css
padding: .25rem .5rem;
font-size: .875rem;
border-radius: .2rem;
````

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.2/forms/select/#sizing

**Comment by lonix1** [comment]
Awesome... new version! Thank you! :smile:
