### ISSUE TITLE
v5.2 Modal hides if selecting text and dragging off the modal

### ISSUE THREAD

**Issue by ryanmortier** [twbs/bootstrap#36394]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

See test cases. Selecting text or an input while dragging off the modal will cause the modal to hide. This behaviour was correct in v5.1.3 and broken in v5.2.

#### v5.1.3 - Working correctly

https://user-images.githubusercontent.com/2053960/169150832-8e62e7be-9326-4af2-bc51-dc8a5f4666b1.mp4

#### v5.2 - Broken

https://user-images.githubusercontent.com/2053960/169150856-8207be6c-c5cb-4ed2-9e7d-b78508017863.mp4

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.2

**Comment by GeoSot** [comment]
Many thanks @ryanmortier for this  😉
