### ISSUE TITLE
Missing sticky-bottom and its responsive css classes

### ISSUE THREAD

**Issue by feng-xiao** [twbs/bootstrap#36396]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The documentation shows usage for sticky-bottom, but the classes are not generated in **bootstrap/scss/helpers/_position.scss** file

### Reduced test cases

![image](https://user-images.githubusercontent.com/3407775/169303644-9c8623bb-2f4d-45dd-80ed-021e3905c956.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by julien-deramond** [comment]
> What version of Bootstrap are you using?
>
> v5.1.3

> The documentation shows usage for sticky-bottom, but the classes are not generated in bootstrap/scss/helpers/_position.scss file

[In 5.1.3, only `.sticky-top` is available](https://getbootstrap.com/docs/5.1/helpers/position/) - see [corresponding bootstrap.css](https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.css) that only contains `.sticky-*-top` classes.
We can see that in the code shared in the issue where the rule is `.sticky#{$infix}-top`.

`.sticky-bottom` was added in 5.2.0 (see https://getbootstrap.com/docs/5.2/helpers/position/#sticky-bottom) - see [corresponding bootstrap.css](https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.css) that contains both `.sticky-*-top` and `.sticky-*-bottom` classes.
