### ISSUE TITLE
Broken link in footer

### ISSUE THREAD

**Issue by luc122c** [twbs/bootstrap#36407]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The Swag Store link in the footer is broken on the main site. The href is blank `<a href="">Swag Store</a>`

It looks correct in the [config](https://github.com/twbs/bootstrap/blob/416f4905f13c2ca3096343e0a5a4934c8c0ced3f/config.yml#L68) and [layout](https://github.com/twbs/bootstrap/blob/d6064264fe3a52f6bf0862b270978e1de4f1d261/site/layouts/partials/footer.html#L23). It seems to be recently reported in #36370 and fixed in #36376 but still isn't working.

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

5.2

**Comment by ffoodd** [comment]
It's not released yet, the docs release depends on our core releases.

Thanks though!
