### ISSUE TITLE
Tipo in CSS variable name in accordion.sass : --#{$prefix}accordion-color: #{color-contrast($accordion-bg)};

### ISSUE THREAD

**Issue by deneuxa** [twbs/bootstrap#36409]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

```
.accordion {
  // scss-docs-start accordion-css-vars
  --#{$prefix}accordion-color: #{color-contrast($accordion-bg)};
```

This variable is incorrect, it should be : 

`--#{$prefix}accordion-color: #{color-contrast($accordion-color)};`

### Reduced test cases

It seems there is a tipo in the accordion module.

The two first variables are duplicated with the same name.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.beta01

**Comment by ffoodd** [comment]
The `color-contrast()` function returns a contrasting color with another color: in that case we're defining the foreground color as the color contrasting with the background (thus `$accordion-bg`), so everything's fine here.

Thanks though!

**Comment by deneuxa** [comment]
It means you can't properly define the font color of the text inside the accordion.
I think a dedicated variable should have been better :)
