### ISSUE TITLE
How to deal with those issues?

### ISSUE THREAD

**Issue by AndreMarschalek** [twbs/bootstrap#36415]
using Microsofts Chromium based Edge Browser and "Issues" from Development Tools some compatibility issues are shown
![image](https://user-images.githubusercontent.com/39925052/169614161-e24a79ca-60fb-4fcd-a847-2d6a1f17d026.png)
at least it would make sense to solve the Error marked items as it should be easy to add the the missing things to support more browsers
and this one
![image](https://user-images.githubusercontent.com/39925052/169617747-a46c3997-9b97-49ec-8044-a095e073997f.png)

what do you think?
[5.1.3]

**Comment by mdo** [comment]
From the looks of it, you're using Bootstrap with Sass and are not including Autoprefixer. That would solve the majority of those errors I believe.
