### ISSUE TITLE
Issue rendering nested tables with card in Chrome

### ISSUE THREAD

**Issue by itsthejoker** [twbs/bootstrap#36419]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, all. I have a page with a specific look that involves a navbar, a floating (mostly) vertically centered element, and a sticky footer. On Firefox (latest) it looks perfect and works flawlessly. In Chrome, the sizing of the center card is all wrong.

In mobile mode, elements don't seem to be anchored to the card anymore and when the keyboard pops up, both the text bar and the button fall off the card entirely. See attached screenshots for quick examples:

<details>
  <summary>Screenshot of testing mobile rendering on desktop</summary>
  
  ![image](https://user-images.githubusercontent.com/5179553/169678131-e793c5ac-77e5-46a5-bc4b-df4a9b61a363.png)
</details>

<details>
  <summary>Pixel 6 w/ Firefox & keyboard up (displaying correctly)</summary>
  
![image](https://user-images.githubusercontent.com/5179553/169678322-81b053f9-b824-4bc8-ac56-8cea211bcac5.png)
</details>

<details>
  <summary>Pixel 6 w/ Chrome & keyboard up (incorrect rendering)</summary>

![image](https://user-images.githubusercontent.com/5179553/169678348-25ff0afe-1af3-4f75-b474-50172acc81a2.png)
</details>

I believe this is a bug in Bootstrap but if this is a user error issue then please let me know -- I really love this project and appreciate your time.

### Reduced test cases

Using bootstrap direct from `main`: https://itsthejoker.github.io/testpage/index2.html

Using bootstrap 5.2.0-beta1 from CDN: https://itsthejoker.github.io/testpage/

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

Latest & 5.2.0-beta1

**Comment by mdo** [comment]
Your custom `height: 50%;` is to blame. You'll need to adjust that.

**Comment by itsthejoker** [comment]
omg. Thank you very much, sorry for the bother. Cheers!
