### ISSUE TITLE
Bootstrap 5.2 remove utilities not working.

### ISSUE THREAD

**Issue by aboutjquery** [twbs/bootstrap#36436]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am using gulp to compile scss.
I used the following code directly from the documentation.
```
$utilities: map-merge(
  $utilities,
  (
    "width": null
  )
);
```

if I put this code after

```
@import "bootstrap/scss/utilities/api";
// HERE
```
nothing happens.

And if I put it in, an error occurred
```
@import "bootstrap/scss/utilities";
// HERE
@import "bootstrap/scss/utilities/api";
```

`$map1: null is not a map.`

Thanks.

### Reduced test cases

```
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";
...other components scss
@import "bootstrap/scss/utilities/api";
$utilities: map-merge(
  $utilities,
  (
    "width": null
  )
);

// nothing happens.

or

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";
...other components scss
$utilities: map-merge(
  $utilities,
  (
    "width": null
  )
);
@import "bootstrap/scss/utilities/api";

// error: $map1: null is not a map.
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by mdo** [comment]
Blah, the docs are definitely wrong on this—the customization of the `$utilities` map needs to come before the `api` import, but after the rest of the imports. Your section example should work—it did for me at least testing locally. If you can confirm one more time, I'll open a PR.

Also, I think this might work, too:

```scss
$utilities: map-remove($utilities, "width");
```

If you could confirm that, we might want to update our docs to include that and fix the import order.

**Comment by aboutjquery** [comment]
Thanks for reply.

I did a test, this working before utilities api import.

```
@import "bootstrap/scss/utilities";
$utilities: map-remove($utilities, "width");
@import "bootstrap/scss/utilities/api";
```

But not working after api, also without any warning.

Thanks.

**Comment by mdo** [comment]
See https://github.com/twbs/bootstrap/pull/36444. The utilities map overrides should go between those two imports as shown in your first example.
