### ISSUE TITLE
Bootstrap 5.2 update Tooltip Title with Javascript is not working

### ISSUE THREAD

**Issue by moshair** [twbs/bootstrap#36432]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello
Update Tooltip Title with Javascript was working fine in version v5.1.3 of bootstrap.bundle.js, but now it is not working using version v5.2.0-beta1 of the same file.

This is the code I use
```
$(function () {
 $('[data-toggle="tooltip"]').tooltip()
  document.getElementById('tt').setAttribute('data-bs-original-title', 'New Tooltip Title');
})
```
[stackoverflow: Bootstrap 5 update Tooltip Title with Javascript](https://stackoverflow.com/questions/65862446/bootstrap-5-update-tooltip-title-with-javascript)

### Reduced test cases

with version 5.0.0
https://codepen.io/moshair/pen/ExQweey

with version 5.2 beta
https://codepen.io/moshair/pen/zYREJmq

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by Supportic** [comment]
## What is your goal? Keep the old title or just overwrite it?
I couldn't find any line in the documentation talking about the `data-bs-original-title` Attribute.
The title attribut is now responsible for displaying the tooltip content. If you first set the title and then initialize the tooltip, everything is working.

```js
document
  .getElementById("tt")
  .setAttribute("title", "New Tooltip Title");
new bootstrap.Tooltip(jQuery('[data-toggle="tooltip"]'));
```


## Your examples seems to be a bit odd.

Your 5.0 example includes beta source Links which might not represent a stable behaviour.
Since 5.0 Tooltips are getting initialized like this `new bootstrap.Tooltip(jQuery('[data-toggle="tooltip"]'));` [ref](https://getbootstrap.com/docs/5.0/components/tooltips/#example-enable-tooltips-everywhere)

Bootstrap should according to documentation only initialize with jQuery by searching for the `jQuery` Object on window instead of `$`. [ref](https://getbootstrap.com/docs/5.0/getting-started/javascript/#still-want-to-use-jquery-its-possible)

Both if your button markups include the `data-placement` which should be `data-bs-placement` in 5.0. [ref](https://getbootstrap.com/docs/5.0/components/tooltips/#examples)

**Comment by Supportic** [comment]
@moshair 
I see what you are trying to do. I downloaded the source code and unfortunately it seems that they dropped support for that attribute.
![Code_E6RBpbVGeA](https://user-images.githubusercontent.com/20886239/171258944-54662fbd-5bb1-4ba4-82de-980eb3d9f5f9.png)

**Comment by moshair** [comment]
Thank you [Supportic](https://github.com/Supportic) , your solution works. Also I found another method from this demo
https://www.codeply.com/p/L9CMTcrJkU 
But it is for popover I modified it.

```
let carsArr = ["", "Saab", "Volvo", "BMW"];
function Showtt(v){
const bsTooltip = new bootstrap.Tooltip(document.getElementById('tt_'+v), {
//settings
});
bsTooltip._config.title= carsArr[v];
}
```
Regards,

**Comment by bert-w** [comment]
For anyone still needing a solution, you can hook into the Popper event and modify the tooltip contents yourself and update the contents manually. Prerequisite: create all your tooltips using `data-bs-title=""` like `<span data-bs-toggle="tooltip" data-bs-title="my tooltip title"></span>`:

```js
// Initialize all tooltips.
new window.bootstrap.Tooltip(document.body, {
    selector: '[data-bs-toggle~="tooltip"]',
    container: 'body',
    // @see https://popper.js.org/docs/v2/modifiers/
    popperConfig: function(defaultBsPopperConfig) {
        defaultBsPopperConfig.modifiers.push({
            name: 'FixDynamicTitles',
            enabled: true,
            phase: 'beforeRead',
            fn({state}) {
                // Fix for dynamic titles using `data-bs-title`.
                let title = state.elements.reference.dataset.bsTitle;
                if(title) {
                    state.elements.popper.querySelector('.tooltip-inner').innerHTML = title;
                }
            }
        });
        return defaultBsPopperConfig;
    }
});
```

It is quite dirty but I couldn't find another way to do this, neither using `window.bootstrap.Tooltip.getOrCreateInstance()` or Popper related functions.

**Comment by sayajin101** [comment]
> For anyone still needing a solution, you can hook into the Popper event and modify the tooltip contents yourself and update the contents manually. Prerequisite: create all your tooltips using `data-bs-title=""` like `<span data-bs-toggle="tooltip" data-bs-title="my tooltip title"></span>`:
> 
> ```js
> // Initialize all tooltips.
> new window.bootstrap.Tooltip(document.body, {
>     selector: '[data-bs-toggle~="tooltip"]',
>     container: 'body',
>     // @see https://popper.js.org/docs/v2/modifiers/
>     popperConfig: function(defaultBsPopperConfig) {
>         defaultBsPopperConfig.modifiers.push({
>             name: 'FixDynamicTitles',
>             enabled: true,
>             phase: 'beforeRead',
>             fn({state}) {
>                 // Fix for dynamic titles using `data-bs-title`.
>                 let title = state.elements.reference.dataset.bsTitle;
>                 if(title) {
>                     state.elements.popper.querySelector('.tooltip-inner').innerHTML = title;
>                 }
>             }
>         });
>         return defaultBsPopperConfig;
>     }
> });
> ```
> 
> It is quite dirty but I couldn't find another way to do this, neither using `window.bootstrap.Tooltip.getOrCreateInstance()` or Popper related functions.

Thank you, this working 100%, have the same issue with 5.2.3

**Comment by moshair** [comment]
Hi,

I found changing the tool-tip text is back to work as before in the last version 5.3.0 using the old method :)

`setAttribute('data-bs-original-title','new tip')`

Is that permanent or it will be removed a gain?

Regards,
