### ISSUE TITLE
Accordion header background  color doesn't obey css

### ISSUE THREAD

**Issue by N6REJ** [twbs/bootstrap#36445]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using an accordion attempting to change header background color via class ( bg-dark ) or via css ( background: black !important ) does not change its color.
css shows that the background should change but it doesnt
![image](https://user-images.githubusercontent.com/1850089/170578438-f1115314-b0f5-4476-92ea-9fee974d08b4.png)

### Reduced test cases

https://codepen.io/SitePoint/pen/qBmGryV

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment]
The styling is on `.accordion-button`, not `.accordion-header`.

**Comment by N6REJ** [comment]
ok, that does work.. text doesn't follow stated button color for some reason but I can adjust the accordion class

**Comment by N6REJ** [comment]
@mdo still not getting it quite right.  What I want is the expanded header to have a different background color and different hoover color.  Right now its all or none.

**Comment by mdo** [comment]
What you need to do then is write two new CSS selectors to change the default and hover state. If you look at the source CSS or source Sass, you can piece together what the selector might need to be.

https://codepen.io/team/bootstrap/pen/XWZVpRZ
