### ISSUE TITLE
Put back in the theme-colors variable map-merge() (and others too)

### ISSUE THREAD

**Issue by bertoost** [twbs/bootstrap#36442]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please put back in the map-merges() on variables like in v4.6 (and probable before).

### Motivation and context

In older versions of Bootstrap you could define just your additional color which got merged into the theme-colors list.
Now days you have to copy all of the mappings (including level up variables) to add just one theme-color for example.. That's kinda annoying.

https://github.com/twbs/bootstrap/blob/v4.6.1/scss/_variables.scss#L76-L89

vs

https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L312-L321

I also tried to include the bootstrap variables before I declare my own variables, but that doesn't work either. For example the button hovers are then not taken over the configured `$primary` color variable.

**Comment by mdo** [comment]
You can read more about why we removed this by starting at https://github.com/twbs/bootstrap/issues/28506.

> In older versions of Bootstrap you could define just your additional color which got merged into the theme-colors list.
> Now days you have to copy all of the mappings (including level up variables) to add just one theme-color for example.. That's kinda annoying.

This isn't true. If you wanted to add another color to `$theme-colors`, you declare it after `_variables.scss` and before `_maps.scss` (in v5.2.0-beta1).

```scss
$theme-colors: map-merge(
  $theme-colors,
  (
    custom: $pink-500
  )
);
```

And if you want to remove something from the `$theme-colors`, you'd do this:

```scss
$theme-colors: map-remove($theme-colors, "primary");
```
