### ISSUE TITLE
.table-group-divider SASS compiled with variable, not with value. v 5.2.0

### ISSUE THREAD

**Issue by shankyag** [twbs/bootstrap#36441]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

.table-group-divider sass variable in calc, so it is not detecting the sass value after compiled in a gulp.

### Reduced test cases

```
.table-group-divider {
  border-top: calc(2 * $table-border-width) solid currentcolor;
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by mdo** [comment]
Thanks for filing! Saw this and forgot to open an issue for myself. Needs to be escaped and then it should be good to go.
