### ISSUE TITLE
Suggest a new feature

### ISSUE THREAD

**Issue by Anoopkumarseth** [twbs/bootstrap#36474]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap is a very popular framework since 2011. Now it has very powerful JS plugins. but now can be extended to very high-level and the common things Like data fetch, routers components rendering and too much development can be done using the Bootstrap can be done.
1. routers advance  (using tabs)
2. fetch data from any API and put it in a table/list
3. page content instead of page reload.
4. basic interpolation
5. validation of a number/date

This means Basic activity which we can perform using react or angular.
As you added powerful CSS control it may have powerful JS support.

it can come under bsExtend.js  which allows the user to do common activities and users will support that then it can be scaled to a high level also.

if we can contribute something to that so let us now 

### Motivation and context

1. It can increase more popularity of bootstrap.
2. less dependency on another framework.
3. Bootstrap will know as grate CSS & JS library (because it's not dependent on jQuery)
4. will be easy to use on bigger than small projects.
5. usage of bootstrap will become broader.
6. users and already familiar with bootstrap so they will easily grab that features without shifting to any other frameworks.
and Much More.

these are the idea which was thought by my team in the company and some other company members while they start new projects and looking into a bootstrap and couldn't find any way to do such kind of things using bootstrap. and the project was not so big so we can do it on angular/react.

Thanks & Regards

**Comment by bert-w** [comment]
this idea is probably out of scope of Bootstrap; when all these features are added the project becomes unmanageable. Every new feature you add is another feature to maintain.

**Comment by mdo** [comment]
Yup, this is outside the scope of what we're willing and able to do here. Plenty of other projects handling these things :).
