### ISSUE TITLE
`node-sass` workflow in v5

### ISSUE THREAD

**Issue by louismaximepiton** [twbs/bootstrap#36478]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Remove the `node-sass` workflow in v5.

### Motivation and context

Here are my two motivations:
- According to the [documentation](https://twbs-bootstrap.netlify.app/docs/5.2/getting-started/contribute/#sass), `node-sass` is deprecated in Bootstrap v5. Is there any reason to keep it ? Is that a check for the retro-compatibility of this library ?
- The second motivation needs a bit more context. I'm trying to build a [component](https://deploy-preview-1281--boosted.netlify.app/docs/5.1/components/stepped-process/) that needs to [concatenate strings inside a CSS variable](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1281) (something that could happen in Bootstrap). The first issue here comes from the way that Sass compiles its variables inside a `#{}`, Sass unquotes strings inside. A workaround exists : [`@use "sass:meta"`](https://sass-lang.com/documentation/breaking-changes/css-vars). However, `node-sass` doesn't compile `@use` and so the CI fails as you can see [here](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/runs/6684306412?check_suite_focus=true) (We are using the same CI as Bootstrap).

I'm open to any thoughts.

**Comment by ffoodd** [comment]
V5 does not fully handle Dart Sass, trying only to stay compatible with both compilers.

In your case, you may use the `inspect()` Sass function, which existed before Dart Sass and is already used through Bootstrap and Boosted, if I recall correctly.
