### ISSUE TITLE
Here is a design bug on the website. This is the Z-INDEX issue

### ISSUE THREAD

**Issue by dhavalkapadiya** [twbs/bootstrap#36498]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Here is a design bug on the website.
This is the Z-INDEX issue.

Same issues in all browsers.
Attached is Mozilla Firefox And Google Chrome Browser. 

### Reduced test cases

Here is a design bug on the website.
This is the Z-INDEX issue.

Same issues in all browsers.
Attached is Mozilla FIrefox And Google Chrome Browser. 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.2

**Comment by mdo** [comment]
You haven't described any issue here. Please update this when you can tell us what the problem is.
