### ISSUE TITLE
Floating labels input not changed direction for RTL 

### ISSUE THREAD

**Issue by zanyar3** [twbs/bootstrap#36496]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I want use **Floating labels** with **Input** for **Right to left direction (RTL design)**,
But input pointer not changed to right

### HTML Code

```
<div class="form-floating mb-3">
       <input type="email" class="form-control"  id="email" name="email" required placeholder="ئیمەڵ">
       <label for="email">ئیمەڵ </label>
       <span for="UserName" class="invalid-feedback">
                   ئیمەڵ بنووسە
       </span>
</div>
```

![Capture](https://user-images.githubusercontent.com/45498591/171923749-a6a5eb6d-6554-46cb-a6e6-7fdfeac151e5.PNG)

### Fixed code by change css code

```
.form-floating > .form-control, .form-floating > .form-control-plaintext {
    padding: 1rem 0.75rem;
    text-align: right;  /*   <---- add text align */
}
```

### Reduced test cases

[https://getbootstrap.com/docs/5.2/forms/floating-labels/#example](https://getbootstrap.com/docs/5.2/forms/floating-labels/#example)

https://github.com/twbs/bootstrap/blob/8965b11dd5ec9f6d353c53b58e256880d6a96703/dist/css/bootstrap.rtl.css#L2691

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by ffoodd** [comment]
Hi there.

This has nothing to do with floating labels, and is intended: [email inputs remain in LTR, as recommended in RTLstyling 101](https://rtlstyling.com/posts/rtl-styling#form-inputs).

**Comment by amirhosseindesigner** [comment]
i did your Proposal But the problem was not solved !

**Comment by zanyar3** [comment]
> i did your Proposal But the problem was not solved !

Hi,

You must change from the ` bootstrap.css` file or put the below code in your custom CSS  file

```
.form-floating > .form-control, 
.form-floating > .form-control-plaintext {
    padding: 1rem 0.75rem;
    text-align: right !important; 
}
```
