### ISSUE TITLE
Include ".active" navbar breaking change in v5 migration docs

### ISSUE THREAD

**Issue by jhthompson** [twbs/bootstrap#36514]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

- Add description of a navbar breaking change to the v5.0 migration documentation [navbar section](https://getbootstrap.com/docs/5.0/migration/#navbars)
  - Change: https://github.com/twbs/bootstrap/pull/32730
  - I am willing to open a PR to fix, but could not find source file to edit (is there a v5.0 branch to make the PR against?)

### Motivation and context

Navbar breaking change[^1] was not listed in the v5 migration docs under the [navbar section](https://getbootstrap.com/docs/5.0/migration/#navbars). It would nice to have it listed for easier migration as I almost missed this breaking change. Other related doc fixes[^2][^3]

[^1]: https://github.com/twbs/bootstrap/pull/32730
[^2]: https://github.com/twbs/bootstrap/pull/32589
[^3]: https://github.com/twbs/bootstrap/issues/32583

**Comment by jhthompson** [comment]
(oops, accidentally added under feature label, should be docs instead)

**Comment by julien-deramond** [comment]
Thanks for opening an issue @jhthompson :)

> I am willing to open a PR to fix, but could not find source file to edit (is there a v5.0 branch to make the PR against?)

You can create a branch against our _main_ branch and modify [migration.md](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.2/migration.md).
If the modification is approved/merged, the latest version of the 5.x documentation will contain your modification in "Migrating to v5".
However I'm not sure if we will be able to modify as well the already shipped migration guide for 5.1 and 5.0.

**Comment by jhthompson** [comment]
> Thanks for opening an issue @jhthompson :)
> 
> > I am willing to open a PR to fix, but could not find source file to edit (is there a v5.0 branch to make the PR against?)
> 
> You can create a branch against our _main_ branch and modify [migration.md](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.2/migration.md). If the modification is approved/merged, the latest version of the 5.x documentation will contain your modification in "Migrating to v5". However I'm not sure if we will be able to modify as well the already shipped migration guide for 5.1 and 5.0.

Sounds good! IMO it really should be applied to the 5.0 migration guide as it is broken at that version, but if there's no way to update the already shipped migration guide then adding it to the latest 5.x documentation is the next best thing.

**Comment by jhthompson** [comment]
Ahh I see that the new docs are for all of 5.x, not just the future versions. I think this is the appropriate place to add this then.
