### ISSUE TITLE
Vertical Pill Nav - With dropdown or sub menu compatibility

### ISSUE THREAD

**Issue by SupremeSimon** [twbs/bootstrap#36527]
Pills nav with dropdown is supported: https://getbootstrap.com/docs/5.2/components/navs-tabs/#pills-with-dropdowns

But seemingly not when they are in a vertical list.  It would be great to have as we are left aligned, vertical tab list.

![vertical pill example  screenshot](https://user-images.githubusercontent.com/37977734/172580017-80e8232f-8843-48cd-bc5f-05a9c2b77471.png)

As you can see with my screenshot, I'm trying to work something functional in, but it's doesn't work natively.
e.g. The parent item doesn't highlight correctly.  Clicking on a child item, then a parent item doesn't unselect the child item.

I'd really like this as a feature if it's possible.

**Comment by SupremeSimon** [comment]
With a bit more tinkering I think I've got it working by adding the following code.

The idea being that when the tab changes, I check if the click option has the class dropdown-item.  If not, then I remove the active classes from the button elements.

Seems to work so far, but would be great if this was just apart of Bootstap.

$('button[data-bs-toggle="pill"]').on('show.bs.tab', function(){
    if (!$(this).hasClass("dropdown-item")){
        $(".muven_menu .dropdown-toggle").removeClass("active");
        $(".muven_menu .dropdown-item").removeClass("active");
    }
});

**Comment by mdo** [comment]
Dropdowns work just fine, but we don't set the active class for you inside whatever application or site you're building. https://stackblitz.com/edit/1bu1xy?file=index.html
