### ISSUE TITLE
customize/sass.md doc doubt/typo?

### ISSUE THREAD

**Issue by pine3ree** [twbs/bootstrap#36534]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

the best position for altering maps

### Reduced test cases

In the **Remove from map** section https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.2/customize/sass.md#remove-from-map, shouldn't the `_root.scss` import be placed after altering default maps, since it is using the defined maps itself?
kind regards

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

5.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @pine3ree. The example provided with `$theme-colors` doesn't seem to work. https://github.com/twbs/bootstrap/pull/36535 is a proposal to fix the docs.

**Comment by pine3ree** [comment]
@julien-deramond , maybe we should put a comment like `// maps customization here!!!` in `bootstrap.scss` between `// Configuration` and `// Layout & components`
