### ISSUE TITLE
transform CSS Custom Properties(CSS variables) syntax into a static representation

### ISSUE THREAD

**Issue by mtamhi** [twbs/bootstrap#36547]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

hello,
I use bootstrap sass with my project and try transform CSS Custom Properties(CSS variables) syntax into a static representation.

I used many plugins like postcss-css-variables, but the result is (undefined) with some codes like:
```
.navbar-brand{padding-top:undefined;padding-bottom:undefined;margin-left:undefined;margin-bottom:0;font-size:undefined;text-decoration:none;white-space:nowrap}
```

### Reduced test cases

Try it in the playground [postcss-css-variables](https://madlittlemods.github.io/postcss-css-variables/playground/) or [cssnet](https://cssnext.github.io/playground/) 

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by mdo** [comment]
This isn't something we can help you with here. You'll have to check with the PostCSS community I'd think.
