### ISSUE TITLE
Password type input box shape edge on top

### ISSUE THREAD

**Issue by MrPavle** [twbs/bootstrap#36541]
below is the snippet is from a form, please see the top left and right on the password input box and the square edges, whilst the bottom edges are rounded.

      <div class="mb-1">
        <input type="text" name="username" class="form-control" placeholder="Username..." required autofocus>
      </div>
      <div class="mb-1">
        <input type="password" name="password" class="form-control" placeholder="Password..." required>
      </div>
      <button class="btn btn-md btn-primary btn-block" type="submit" name="submit">Sign in</button>

![image](https://user-images.githubusercontent.com/5743975/173012792-c1b472df-e165-4826-81c0-123ff935c601.png)

I did add `style="border-radius:4px;"` to the input and solved my problem but thought i would log this.

**Comment by yuyuqiu** [comment]
![image](https://user-images.githubusercontent.com/37923403/173027808-ea4b7128-4396-4811-9893-c9bfca0473c6.png)
![image](https://user-images.githubusercontent.com/37923403/173027968-224ff3bb-4f38-46de-9e5e-029b6326294f.png)
I tried, it is OK！I did not add style="border-radius:4px;" to the input

**Comment by richardoey** [comment]
I also tried, everything is fine 👍
https://codepen.io/RichardOey/pen/wvyQMzm
