### ISSUE TITLE
Add example of template with navbar and sidebar

### ISSUE THREAD

**Issue by iitsmateen** [twbs/bootstrap#36542]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please add example of template with responsive navbar and sidebars.

### Motivation and context

Please add example of template with responsive navbar and sidebars.

**Comment by Jyotiraditya24** [comment]
hey ,could I work on this ?

**Comment by iitsmateen** [comment]
> hey ,could I work on this ? 

Yes please, I need responsive template with fixed sidebar and navbar Thanks

**Comment by Jyotiraditya24** [comment]
do you need hover effects on the the sidebars and navbar?

**Comment by iitsmateen** [comment]
yes
