### ISSUE TITLE
Unable to set dropdown boundary in Bootstrap 5

### ISSUE THREAD

**Issue by SoftCircuits** [twbs/bootstrap#36560]
### Discussed in https://github.com/twbs/bootstrap/discussions/36383

<div type='discussions-op-text'>

<sup>Originally posted by **SoftCircuits** May 17, 2022</sup>
I had the following markup working in Bootstrap 4.

    <div class="dropdown">
        <span type="button" class="dropdown" data-toggle="dropdown" data-boundary="viewport">
            <img src="~/images/menu.png" title="Menu" />
        </span>
        <div class="dropdown-menu dropdown-menu-right">
            <a asp-page="AddBol" class="dropdown-item">Manual Entry</a>
        </div>
    </div>

However, when I upgraded to Bootstrap 5, the dropdown no longer opens.

I figured out that I need to change the `data-toggle` attribute to use the `data-bs-toggle` attribute instead. Now the dropdown works.

However, the `data-boundary="viewport"` attribute no longer works. This attribute allows the dropdown to extend outside the container element. As it is now, the dropdown is cut off when its bounds fall outside of the container.

I tried using `data-bs-boundary="viewport"` and `data-bs-boundary="body"` as suggested in [this Stackoverflow question](https://stackoverflow.com/questions/70098157/bootstrap-5-1-3-dropdown-data-bs-boundary-no-longer-works).

Does anyone know how to use this attribute in Bootstrap 5?
</div>

-----

#### More Details

I have a dropdown within a table. It works fine unless the table is empty, in which case the dropdown is clipped where it would extend outside of the table area.

This was fixed before by setting `data-boundary="viewport"`. But I upgraded to Bootstrap 5 and now the problem is back.

I tried updating this attribute to `data-bs-boundary="viewport"` but that has no effect.

Does anyone know the reason? Is this related to popper? Where I should post about this?

Thanks. Below is my markup (it's ASP.NET/Razor Pages).

``` html
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.TruckBols[0].TruckNumber)</th>
                <th>@Html.DisplayNameFor(m => m.TruckBols[0].BoxNumber)</th>
                <th>@Html.DisplayNameFor(m => m.TruckBols[0].PurchaseOrder)</th>
                <th>@Html.DisplayNameFor(m => m.TruckBols[0].Product)</th>
                <th>@Html.DisplayNameFor(m => m.TruckBols[0].InboundWeight)</th>
                <th>@Html.DisplayNameFor(m => m.TruckBols[0].ArrivalTime)</th>
                <th class="text-end">
                    <div class="dropdown">
                        <span type="button" class="dropdown" data-bs-toggle="dropdown" data-bs-boundary="viewport">
                            <img src="~/images/menu.png" title="Menu" />
                        </span>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a asp-page="AddBol" class="dropdown-item">Manual Entry</a>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            @if (truckCount > 0)
            {
                foreach (TruckSummaryModel truck in Model.TruckBols!)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => truck.TruckNumber)</td>
                        <td>@Html.DisplayFor(m => truck.BoxNumber)</td>
                        <td>@Html.DisplayFor(m => truck.PurchaseOrder)</td>
                        <td>@Html.DisplayFor(m => truck.Product)</td>
                        <td>@Formatter.Number(truck.InboundWeight)</td>
                        <td>@truck.GetFormattedArrivalTime(Model.UserContext.TimeZoneId)</td>
                        <td class="text-end">
                            <a asp-page="ArriveTruck" asp-route-id="@truck.Id"><img src="/images/edit.png" title="Edit" /></a>
                            <a asp-page="DepartTruck" asp-route-id="@truck.Id"><img src="/images/depart.png" title="Depart Truck" /></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
```

-----

This online example demonstrates the issue.

https://codepen.io/korki43/pen/mdRGgMK?editors=1000

**Comment by kadsyy** [comment]
Try adding 'position-static' class inside here

` <div class="dropdown position-static">`

Please try if its work on other browser as well.

**Comment by SoftCircuits** [comment]
> Try adding 'position-static' class inside here

In fact, that *does* work for me. Do you have any idea why?

I will do more testing. Thanks.

**Comment by kadsyy** [comment]
> > Try adding 'position-static' class inside here
> 
> In fact, that _does_ work for me. Do you have any idea why?
> 
> I will do more testing. Thanks.

It's a normal behavior if you have position absolute element (dropdown) inside an overflow div (table-responsive). You can remove table-responsive class and see the dropdown will work fine but I believe you need the class to cater for responsiveness in smaller screen.

Also regarding `data-bs-boundary="viewport"` yes it got to do with popper because the way it works in BS5 is different. I'm afraid I can't help you much on this because I don't know much about JavaScript.

**Comment by SoftCircuits** [comment]
@kadsyy Thanks. I have it working. Although I also found that if I delete the outer `dropdown` class altogether, then it works fine without the `position-static` or `data-bs-boundary` classes! Doesn't make a lot of sense to me.

**Comment by GeoSot** [comment]
@SoftCircuits  have you tried to change the popper strategy to `fixed`?
```js



new Dropdown('#my-dropdown', { 
  boundary: document.querySelector('body'),
  popperConfig: defaultBsPopperConfig => {
             ...defaultBsPopperConfig, strategy: 'fixed'
        }
});
```

**Comment by GreathostRo** [comment]
After more than a few hours and various attempts I found the working version:

```
const dropdowns = document.querySelectorAll('.dropdown-toggle')
const dropdown = [...dropdowns].map((dropdownToggleEl) => new bootstrap.Dropdown(dropdownToggleEl, {
    popperConfig(defaultBsPopperConfig) {
        return { ...defaultBsPopperConfig, strategy: 'fixed' };
    }
}));
```

**Comment by DmitryBielov** [comment]
> Try adding 'position-static' class inside here
> 
> ` <div class="dropdown position-static">`
> 
> Please try if its work on other browser as well.

unfortunately it doesn't work on ios

**Comment by jsponceA** [comment]
this worked for me
`<button
                              class="btn btn-primary btn-sm dropdown-toggle"
                              type="button"
                              data-bs-config='{"popperConfig":{"strategy":"fixed"}}'
                              data-bs-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              Actions
                            </button>`

**Comment by xenon-96-31-10** [comment]
You can use this method 

```js
        jQuery(document).ready(function($) {
            let crudTable = $('#crudTable')
            crudTable.on('shown.bs.dropdown', function () {
                let dropdownMenu = $('div.dropdown-menu.dropdown-menu-left.show')
                let dataTables_scrollBody = $('.dataTables_scrollBody')

                $('.dataTables_scrollFoot').css("margin-top", "-" + dropdownMenu.outerHeight() + "px")

                dataTables_scrollBody.height(dataTables_scrollBody.outerHeight() + dropdownMenu.outerHeight())
            });
            crudTable.on('hide.bs.dropdown', function () {
                let dropdownMenu = $('div.dropdown-menu.dropdown-menu-left.show')
                let dataTables_scrollBody = $('.dataTables_scrollBody')

                $('.dataTables_scrollFoot').css("margin-top", "0px")

                dataTables_scrollBody.height(dataTables_scrollBody.outerHeight() - dropdownMenu.outerHeight())
            });
        });
```

When click on dropdown-button to increase height for body with table row

**Comment by SoftCircuits** [comment]
@xenon-96-31-10 No JavaScript is required.

**Comment by xenon-96-31-10** [comment]
@SoftCircuits why?

**Comment by SoftCircuits** [comment]
@xenon-96-31-10 Because  I solved it without any JavaScript. This issue is 3 years old. But if you read it, you can see it was solved with markup.

**Comment by xenon-96-31-10** [comment]
I get it @SoftCircuits 
But i try to show new way for other people and it must be helpfull. More over your last way not work now at least me
