### ISSUE TITLE
Modals  class="fade" doesn`t  works

### ISSUE THREAD

**Issue by NereoToro** [twbs/bootstrap#36579]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Modals  class="fade" doesn`t  works

Don't have transition

### Reduced test cases

@media (prefers-reduced-motion: reduce)
.fade {
    transition: none;
}

.fade {
    transition: opacity .15s linear;
}

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by mdo** [comment]
Modals are fading properly for me in our docs. If you have reduced motion enabled, it won't animate. You also haven't included a proper test case either so we can't help more.
