### ISSUE TITLE
Button groups last button outline is thick/double when compared to earlier buttons

### ISSUE THREAD

**Issue by Shashank-Bhatt1** [twbs/bootstrap#36575]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi I have tried to take button outline variants inside button group but it looks like there is small bug when the last button's left side outline is double.

We can see at this sections in this doc page where the last button;s outline is thicker than earlier two. 

https://getbootstrap.com/docs/5.0/components/button-group/#outlined-styles

Reference screenshot is attached here.
<img width="243" alt="Screenshot 2022-06-14 170452" src="https://user-images.githubusercontent.com/24728257/173568045-cea91089-8f26-4cd6-a6f3-a31855711d3c.png">
/button-group/#outlined-styles

 

### Reduced test cases

https://getbootstrap.com/docs/5.0/components/button-group/#outlined-styles

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.0

**Comment by mdo** [comment]
Are you zoomed in or out at all? This can happen due to pixel rounding—it's not a thicker border, but rather two borders overlapping improperly.

**Comment by abhishekkmukherjee** [comment]
I don't see any bug in this , It looks fine in my browser. I have checked it on chrome and brave also.

**Comment by ManojTGN** [comment]
> Are you zoomed in or out at all? This can happen due to pixel rounding—it's not a thicker border, but rather two borders overlapping improperly.

On My Display It Is Clean
![Capture](https://user-images.githubusercontent.com/42494649/182318083-bf53c7ed-f6b5-43ac-8ff0-9ba924747ef6.PNG)

But When I Tried To Zoom In/Out A Little Bit The Border Is Uneven
![2](https://user-images.githubusercontent.com/42494649/182324677-8adf9a95-0ad0-4ab8-b49b-810f0925739f.PNG)
![3](https://user-images.githubusercontent.com/42494649/182324684-01e417ee-f986-421d-9b44-d7814b79f807.PNG)

**Comment by mdo** [comment]
Closing as a zoom issue—there's really nothing we can do for that I'm afraid.
