### ISSUE TITLE
RTL issue, .navbar-brand is using margin-right not margin-inline-end | V5.1.3

### ISSUE THREAD

**Issue by 0proboy0** [twbs/bootstrap#36600]
![image](https://user-images.githubusercontent.com/14108109/174448350-a3ae745f-5ce4-412c-ba91-e6308d5c80d8.png)

**Comment by ffoodd** [comment]
Bootstrap doesn't use logical properties to handle RTL (incompatible with V5 browsers target), but instead uses RTLCSS to transform `margin-left` to `margin-right`.

In other words, everything works as intended. 👌

Logical properties will eventually be used for Bootstrap V6.
