### ISSUE TITLE
Button group: problem with hover from one button to the next

### ISSUE THREAD

**Issue by Blucher83** [twbs/bootstrap#36605]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When you hover first one button and then move the mouse cursor to the next button and then back, you will see a white vertical line between these buttons for a very short moment.

This CSS fixed it:
`.btn-group > .btn:hover { z-index: auto; }`

_Tip: Add support to switch horizontal button group to vertical with build in class._

### Reduced test cases

https://getbootstrap.com/docs/5.2/components/button-group/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @Blucher83. Would you be able to capture the rendering in a .gif (or something else)? I'm not seeing this on my OS.

**Comment by mdo** [comment]
This is how we prevent double borders in button groups, so it's unlikely to change. Toggling borders off and on leads to it's own issues, and there aren't many other solutions after that :). Closing as a won't fix.
