### ISSUE TITLE
Pseudo element ::before does not work and applying ::after instead

### ISSUE THREAD

**Issue by usama7628674** [twbs/bootstrap#36606]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue does not occur in bootstrap 4, only happens in bootstrap 5.
Here's the html code
 ```
<div id="testimonials" class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="section-head">Testimonials</h2>
                </div>
                <div class="col-md-6">
                    <div class="testimonial">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo, omnis?
                            Iure architecto neque
                            quae molestiae?
                        </p>
                        <img src="images/bill-gates.jpg" alt="">
                        <div class="author">Bill Gates</div>
                        <div class="author-company">Microsoft</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="testimonial">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo, omnis? Iure architecto neque
                            quae molestiae?
                        </p>
                        <img src="images/steve-jobs.jpg" alt="">
                        <div class="author">Steve Jobs</div>
                        <div class="author-company">Apple</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
```

Here's the css
```
#testimonials{
    background-image: url("../images/phone.jpg");
    background-size: cover;
    background-repeat: no-repeat;
    padding: 50px 0;
    position: relative;
    background-position-x: left;
    background-position-y: center;
    color: #fff;
    
    
}

#testimonials::before{
    background-color: rgba(52, 73, 94,0.7);
    content: "";
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
}
```

With bootstrap 5 it is applying film on image after the image and text
![image](https://user-images.githubusercontent.com/29252277/174511344-ade1e9da-8aed-4228-a0f5-bd58431f15cc.png)

Here's the result with bootstrap 4.6.1
![image](https://user-images.githubusercontent.com/29252277/174511411-60b3b58b-ee56-4932-83b7-6ef5e39a1dc6.png)

### Reduced test cases

Code with bootstrap 5.2.0 (bug)
https://codepen.io/usama7628674/pen/wvyZZea

Code with Bootstrap 4.6.1 (Works perfectly)
https://codepen.io/usama7628674/pen/XWZQQeV

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Opera

### What version of Bootstrap are you using?

5.2.0

**Comment by mdo** [comment]
This has nothing to do with Bootstrap, but rather the stacking order of your content. Adjust the `z-index` property and you should be fine, but you might need more.
