### ISSUE TITLE
Docs: missing migration issue with active class for navbars

### ISSUE THREAD

**Issue by madman-81** [twbs/bootstrap#36610]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

As of Bootstrap version 5(.0?), the `.active` class needs to be added to the `.nav-link` item, where version 4 supported both the `.nav-link` and the `.nav-item` items.

https://getbootstrap.com/docs/4.6/components/navbar/#nav
https://getbootstrap.com/docs/5.1/components/navs-tabs/#base-nav 

This (breaking) change isn't mentioned in the migrations documentation:
https://getbootstrap.com/docs/5.1/migration/#navbars

### Reduced test cases

From the BS4 documentation: this wouldn't work anymore with BS5:
```html
...
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
    </ul>
...
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/issues/36514
