### ISSUE TITLE
Calling Tab.show() on multiple tabs results in content of multiple tabs showing at same time rather than last tab .show() was called on 

### ISSUE THREAD

**Issue by unicornsoftwareinc** [twbs/bootstrap#36621]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Issue:** Having multiple tabs and then calling Tab.show() on multiple tabs "around the same time" results in the tab content of those tabs showing at the same time rather than only the last tab .show() was called on. This appears related to using .fade class

**Expected behavior:** I believe only the content of the last tab that had .show() called on should show. Only 1 tab content should ever be shown at one time.

In my app, the user can choose to display tabs at a specific time. So if they set multiple tabs to show at the same minute/second, it leads to this issue where the multiple tab contents are displaying at once. See attached screenshot: 
<img width="410" alt="Screen Shot 2022-06-21 at 8 49 34 PM" src="https://user-images.githubusercontent.com/33875309/174920204-b21e934d-fb31-4e6c-9753-e572f5efcd6e.png">

You can also see the behavior in this codepen here: https://codepen.io/phil917/pen/zYRVxqZ

**How to reproduce:** Set up tabs in Bootstrap 5 using .nav and .nav-tabs. Add multiple tabs using .nav-item and .nav-link. Add corresponding tab content using .tab-content and .tab-pane and crucially, .fade

Using javascript, instantiate the various tabs and then call .show() all at the same time. You'll probably notice multiple tabs are showing their content at once now.

I believe there is some race condition going on which is causing the issue.

### Reduced test cases

Link to codepen: https://codepen.io/phil917/pen/zYRVxqZ

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5

**Comment by GeoSot** [comment]
@unicornsoftwareinc please try it using this script, and feedback me
`https://deploy-preview-36622--twbs-bootstrap.netlify.app/docs/5.2/dist/js/bootstrap.bundle.min.js`

Based on some trials I've made, I think it will be ok

**Comment by GeoSot** [comment]
Just to note here, that is more a Dev's exaggeration than a bug, as it should be controlled somehow. However the fix is combined with a more generic approach, so it fits nice 😅

Thank you a lot for your feedback 😊
