### ISSUE TITLE
ScrollIntoView doesn't function with NavBar

### ISSUE THREAD

**Issue by antinucleon** [twbs/bootstrap#36634]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

d3-graphviz will generate a few g node such as 
```
<g id="my_node" class="node">
<title style="">my_node</title>
<polygon fill="none" stroke="#ab82ff" points="666.35,-9612 663.35,-9616 642.35,-9616 639.35,-9612 509.86,-9612 509.86,-9576 666.35,-9576 666.35,-9612" style=""></polygon>
<text text-anchor="middle" x="588.11" y="-9589.8" font-family="Times,serif" font-size="14.00" style="">my_node</text>
</g>
```

After execute:

```
const obj = document.getElementById("my_node");
obj.scrollIntoView({ block: 'center',  behavior: 'smooth' });
```

The view is moved to the node as expected. However, the NavBar is gone from the top. If we use scrollIntoView for NavBar, we find the NavBar is at the location we manually drag the figure.

### Reduced test cases

HTML Source: https://gist.github.com/antinucleon/28d85cf9cd2c0a99e5e1e1949b6da575

Reproduce step:  in the search bar type a node name, such as "conv2d_bias_relu_50", then click search, the view will jump to the node and navbar will be gone.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

4.0.0 and 5.2.0

**Comment by mdo** [comment]
There's no bug here. If you want a sticky or fixed navbar, you'll need to add the appropriate class. https://getbootstrap.com/docs/5.2/components/navbar/#placement
