### ISSUE TITLE
Move all $-color-variables into separate _colors.scss

### ISSUE THREAD

**Issue by NielsHolt** [twbs/bootstrap#36639]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi

In the documentation "Customize everything with Sass" it is descried how to change eq. `$border-color` to `red `and that will also change `$some-other-border-color: $border-color`
But if I want to change `$border-color` using some of the color-variables in `_variables.scss` eq. `$border-color: $orange;` I need to inport `_variables.scss` before changing `$border-color` and `$some-other-border-color` will not be changed as it is already set in `_variables.scss`

#### Works fine:
```
$border-color: red;
@import bootstrap/scss/variables
```

#### Do not work
```
@import bootstrap/scss/variables
$border-color: $orange;
@import bootstrap/scss/variables
```
`$some-other-border-color` will still have the original value of `$border-color`

The problem could be solved by having all colors in a separate scss-file `_colors-scss`
#### Would work
```
@import bootstrap/scss/colors
$border-color: $orange;
@import bootstrap/scss/variables
```

### Motivation and context

Would make it easy to use other colors for $-variables

**Comment by mdo** [comment]
This is a known limitation of Sass itself, and less of a bug with Bootstrap. For now, we'll be leaving our variables as-is in v5, which means no separate file. We may revisit this in v6 whenever that comes.
