### ISSUE TITLE
Input Tags aren't closed in Docs

### ISSUE THREAD

**Issue by philippneugebauer** [twbs/bootstrap#36666]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Unfortunately, the input tags in https://getbootstrap.com/docs/5.2/forms/overview/#overview aren't closed. I tried to find the html examples in the code, but I couldn't find them. Otherwise I would have directly provided a PR.

### Reduced test cases

https://getbootstrap.com/docs/5.2/forms/overview/#overview

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

v5.2

**Comment by philippneugebauer** [comment]
Hm, you could argue it's fine according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text but my linter in VS Code still considers that wrong.

**Comment by julien-deramond** [comment]
As you point out in your last comment self-closing tags are valid.
Maybe you can change the configuration of your linter to consider that right.
