### ISSUE TITLE
div class="rounded-start" - why on the right?

### ISSUE THREAD

**Issue by Demessfor** [twbs/bootstrap#36670]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue
rounded-start
```
<div class="col-3 d-flex align-items-end justify-content-center bg-primary rounded-start rounded-5">
......
</div>
```
if set in CSS, and add to styles
```
.my_class {
    border-top-left-radius: 2rem;
    border-bottom-left-radius: 2rem;
    }

<div class="col-3 d-flex align-items-end justify-content-center bg-primary my_class">
......
</div>

```
is correct.

### Reduced test cases

Why is the radius on the right and not on the left d-flex  ? what to use always - rounded-end ? it's inconvenient

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.2 b1

**Comment by julien-deramond** [comment]
IMO it is the same issue as https://github.com/twbs/bootstrap/issues/36536 that could be fixed by https://github.com/twbs/bootstrap/pull/36540. Could you please confirm @Demessfor?

**Comment by Demessfor** [comment]
Oh, sorry I didn't notice the discussion thread

**Comment by julien-deramond** [comment]
No problem it is sometimes difficult to find related issues :).
I'm closing this one as duplicate. You can follow the state by subscribing to https://github.com/twbs/bootstrap/issues/36536 and/or https://github.com/twbs/bootstrap/pull/36540.
