### ISSUE TITLE
row-cols-# (where # is greater than 6) is ignored

### ISSUE THREAD

**Issue by awbottrel** [twbs/bootstrap#36691]
I've found that row-cols stops at 6.  If you try row-cols-7 or greater, it will just be ignored. 
Curious if this is a bug or something I'm misunderstanding about the grid.   Is there currently a way around it (still using row-cols)?

**Comment by hadouin** [comment]
I'm guessing you will need to customize the sass import by changing this variable: 
```scss
$grid-row-columns:            6 !default;
```  
However this is not inlcuded in [grid documentation](https://getbootstrap.com/docs/5.2/layout/grid/#variables)
