### ISSUE TITLE
Extract background images into icon classes

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#36718]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Many components have background images(icons): `.accordion-button`, `.form-select`, `.dropdown-toggle` and etc. I vote to convert background images into classes like as `.navbar-toggler-icon` or generates svg files.

### Motivation and context

The icons are reuseable and as a consequence of reducing bundle size. Current classes don't have duplicate background images, but it's can be usable for future versions and user's custom components.

**Comment by Kartikeyy-singh** [comment]
I want to work on this, please assign it to me.

**Comment by mdo** [comment]
No plans to do this, but in v6 I may move us to using SVGs in HTML instead of CSS in v6. It'll be impossible to really do for inputs, selects, and other form components though. Custom components, totally doable though.

**Comment by mmolica2** [comment]
Background images that convey meaning is considered a failure when testing for accessibility for individuals with disabilities. Using an image with an alt tag is generally considered the way to go.
