### ISSUE TITLE
File Upload function does not work on Chrome anymore

### ISSUE THREAD

**Issue by ZaferUnal** [twbs/bootstrap#36713]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

File Upload function does not work on Chrome anymore -  everything seems fine on safari.

### Reduced test cases

https://getbootstrap.com/docs/5.2/forms/form-control/

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5

**Comment by mdo** [comment]
There's no logic to support file uploads, there's only the rendering/styling of the form control.
