### ISSUE TITLE
node:events:505       throw er; // Unhandled 'error' event     

### ISSUE THREAD

**Issue by shersial** [twbs/bootstrap#36723]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

 hugo server --port 8300 --disableFastRender

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\10016\IdeaProjects\bootstrap\node_modules\hugo-bin\vendor\hugo.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\10016\\IdeaProjects\\bootstrap\\node_modules\\hugo-bin\\vendor\\hugo.exe',
  path: 'C:\\Users\\10016\\IdeaProjects\\bootstrap\\node_modules\\hugo-bin\\vendor\\hugo.exe',
  spawnargs: [ 'server', '--port', '8300', '--disableFastRender' ]

### Reduced test cases

[Download the latest release](https://github.com/twbs/bootstrap/archive/v5.2.0-beta1.zip)
Clone the repo: git clone https://github.com/twbs/bootstrap.git
Install with [npm](https://www.npmjs.com/): npm install bootstrap@v5.2.0-beta1
Install with [yarn](https://yarnpkg.com/): yarn add bootstrap@v5.2.0-beta1
after this yarn start or npm start 
same error get 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.2

**Comment by ffoodd** [comment]
FWIW I understood you cloned the repo **and**  installed Bootstrap through npm. I don't know what you're trying to do but this is incorrect, for sure.

Either you use our sources and run the local docs site (using Hugo) in order to contribute, or you install Bootstrap as a dependency and use it, but you can't do both.

**Comment by Benja1512** [comment]
ijust got the same error.... but i changed the port. have a look
 i had the port: 3000 firstly.
![image](https://user-images.githubusercontent.com/103325697/200066053-9fe155a2-8a2c-45f6-8914-9419e7a67491.png)
 then i changed to another port: 8080.
![image](https://user-images.githubusercontent.com/103325697/200066121-897a1427-d7e1-4142-8eb3-ce52f9459d03.png)
 and this disappeared. perhaps it ll work on your problem.
