### ISSUE TITLE
Form validations are not working in react!

### ISSUE THREAD

**Issue by Harmouch101** [twbs/bootstrap#36746]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Form validations are not working in react. 

### Reduced test cases

You can refer to [codesandbox](https://codesandbox.io/s/react-bootstrap-form-validation-fhsscy?file=/src/App.js) to interact with the app live. What's shown in the console must be reflected on the UI.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Implementing form validation in React isn't something we explicitly provide, and we have no official React implementation, so we can't help you here. Try asking around in a discussion if you can :).

**Comment by Harmouch101** [comment]
Hey @mdo, thanks for the response. It turns out it works in react with some little tweaks. So, basically, we have to add the validation function mentioned in [the docs](https://getbootstrap.com/docs/5.0/forms/validation/) within a jquery wrapper.

So instead of:

```javascript
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function () {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
```

I moved it within jQuery:

```javascript
(function ($) {
  "use strict";
  function validate_form() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll(".needs-validation");
    console.log(forms)
    // Loop over them and prevent submission
    Array.prototype.slice.call(forms).forEach(function (form) {
      form.addEventListener(
        "submit",
        function (event) {
          if (!form.checkValidity()) {
            event.preventDefault();
            event.stopPropagation();
          }

          form.classList.add("was-validated");
        },
        false
      );
    });
  }
  // Dom Ready
  $(function () {
    validate_form();
  });
})(jQuery);
```

And of course, we also need to import jquery in `index.html`:

```html
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
```

And it is working like a charm! let's gooo!

![Screenshot from 2022-07-16 10-10-49](https://user-images.githubusercontent.com/62179149/179344600-aa247d0f-8124-4927-9a78-79d5c8465a0b.png)

I am not sure if using jquery is considered cheating in the react world. Some folks don't like the idea. But, at least it is working!

Besides, I would be happy to contribute to the docs to guide fellow reacticians on how to use forms validation in react. Looking forward to your response.

**Comment by Harmouch101** [comment]
Take a look at how nice and clean my form looks now thanks to Bootstrap:

![Screenshot from 2022-07-16 10-41-39](https://user-images.githubusercontent.com/62179149/179346196-692f0deb-1852-48ab-82dc-db8df360c62c.png)

Bootstrap to the moon 📈. Oh! wait a sec... It is already there. Next destination: Beyond the milky way...
