### ISSUE TITLE
btn-link no longer has an outline when clicked

### ISSUE THREAD

**Issue by imaperson1060** [twbs/bootstrap#36744]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using `.btn-link` in v5.2.0 Beta 1, the button looks like a normal link instead of having the blue button outline when clicked (this worked in v5.1.3).

### Reduced test cases

```html
<button class="btn btn-sm btn-link">Text</button>
```

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @imaperson1060. Confirm this regression that happened with https://github.com/twbs/bootstrap/commit/ef9d8538a06f43f74f49d6829cbf301773381488. The outline is no more displayed when active and the text becomes black.

**Comment by imaperson1060** [comment]
Sooooo 5.2.1 kinda broke this again lol.
If it helps here's the only difference I found in inspect elements:
5.2.1:
![image](https://user-images.githubusercontent.com/68653653/189553155-9e43faa0-5026-4186-a996-318d7418fbb9.png)
5.2.0 (stable):
![image](https://user-images.githubusercontent.com/68653653/189553160-0f44ecee-cb5f-4ba8-afff-fafba1a1e443.png)
Sorry for bothering you again!😅

**Comment by julien-deramond** [comment]
@imaperson1060 In v5.2.1, in https://github.com/twbs/bootstrap/pull/37026, this behavior has been voluntarily changed:

> for all `.btn`s, it changes the `:focus` styling to `:focus-visible` - this way, the focus style doesn't take effect and "stick" (until you click somewhere else) for mouse/touch users
