### ISSUE TITLE
EventHandler JS test fails on Mac

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#36749]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

We are used to see BrowserStack tests fail randomly but since https://github.com/twbs/bootstrap/commit/505e0235b91052e7b9e4e542d8cd5639cba03de6 it fails 100% of the time. 
ref: #36386

I checked the logs of BrowserStack (while working on https://github.com/twbs/bootstrap/pull/36748) and could see:
```
Firefox 102.0 (Mac OS 10.15) EventHandler general functionality should hydrate properties, and make them configurable FAILED
	TypeError: setting getter-only property "originalTarget" thrown
	Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 8072)
	<Jasmine>
Firefox 102.0 (Mac OS 10.15) EventHandler general functionality should hydrate properties, and make them configurable FAILED
	TypeError: setting getter-only property "originalTarget" thrown
	Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 8072)
	<Jasmine>
```

I tried to launch this test locally only on a Mac (macOS 12.4) with Firefox (102.0.1 / 64 bits) and get the same exact error.

_Note: From the logs, it should be reproductible on Windows 10+Firefox as well_

/CC @GeoSot 

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0 (current _main_ branch)

**Comment by GeoSot** [comment]
closed via #36772
