### ISSUE TITLE
anchor tag href doesn't work with data-bs-dismiss

### ISSUE THREAD

**Issue by TrulyBright** [twbs/bootstrap#36753]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`href` of an `<a>` tag with `data-bs-dismiss` being an attribute doesn't work.
```html
<button
  class="navbar-toggler"
  id="navbar-toggler"
  type="button"
  data-bs-toggle="offcanvas"
  data-bs-target="#offcanvasNavbar"
  aria-controls="offcanvasNavbar"
>
  open a nav
</button>
<nav class="offcanvas" id="offcanvasNavbar">
  <a href="/foo" data-bs-dismiss="offcanvas">close and go somewhere</a>
</nav>
```
When I click the `<a>` tag, the offcanvas closes, but the tag doesn't lead me to `/foo`.
This issue especially matters when [`<router-link>` of Vue Router](https://router.vuejs.org/api/) is involved. User must close the `nav` manually after navigating to another page. I'd like it to close automatically.

### Reduced test cases

Test case (same as above):
```html
<button
  class="navbar-toggler"
  id="navbar-toggler"
  type="button"
  data-bs-toggle="offcanvas"
  data-bs-target="#offcanvasNavbar"
  aria-controls="offcanvasNavbar"
>
  open a nav
</button>
<nav class="offcanvas" id="offcanvasNavbar">
  <a href="/foo" data-bs-dismiss="offcanvas">close and go somewhere</a>
</nav>
```

One workaround I found is to put `data-bs-dismiss` elsewhere:
```html
<button
  class="navbar-toggler"
  id="navbar-toggler"
  type="button"
  data-bs-toggle="offcanvas"
  data-bs-target="#offcanvasNavbar"
  aria-controls="offcanvasNavbar"
>
  open a nav
</button>
<nav class="offcanvas" id="offcanvasNavbar">
  <a href="/foo"><span data-bs-dismiss="offcanvas">close and go somewhere</span></a>
</nav>
```

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by GeoSot** [comment]
> When I click the <a> tag, the offcanvas closes, but the tag doesn't lead me to /foo.

This is not a bug :/ . By design `data-bs-dismiss` has to do one job => close the offcanvas and do not affect something else

**Comment by TrulyBright** [comment]
> > When I click the  tag, the offcanvas closes, but the tag doesn't lead me to /foo.
> 
> This is not a bug :/ . By design `data-bs-dismiss` has to do one job => close the offcanvas and do not affect something else
> 
> So if you want to achieve both behaviors, I think you workaround is the 'right' one

Umm...so `href` of an anchor tag by design does nothing if it has `data-bs-dismiss`?

**Comment by GeoSot** [comment]
`href` or `data-bs-target` are used to target a specific element https://getbootstrap.com/docs/5.2/components/offcanvas/#toggle

And if you check this line, which is responsible for handling the dismiss action you will notice a check to prevent default events 
https://github.com/twbs/bootstrap/blob/ed448925daa4fb20344f94e35c37dded9e0af8af/js/src/util/component-functions.js#L14-L18

**Comment by TrulyBright** [comment]
Oh, so `href` works as an *indicator*, not a hyperlink, if the tag is used as a bootstrap component. I see. Sorry to bother you and thank you for such careful explanation :)
