### ISSUE TITLE
Minor variables scss cleanup ($btn-focus-box-shadow)

### ISSUE THREAD

**Issue by 719media** [twbs/bootstrap#36779]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

there is a variable in use `$btn-focus-box-shadow` that looks like its only use is just to be used as default for `$accordion-button-focus-box-shadow`
seems like probably should just remove the singular instance use of `$btn-focus-box-shadow` and replace it with the much more widely used `$input-btn-focus-box-shadow`

### Reduced test cases

No test case, just a variable cleanup

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

v5.2.0

**Comment by 719media** [comment]
PR #36780

**Comment by mdo** [comment]
See https://github.com/twbs/bootstrap/pull/36780#issuecomment-1194687401.
