### ISSUE TITLE
Webpack build fails with "SassError: Undefined variable" when updating 5.1.3 -> 5.2.0

### ISSUE THREAD

**Issue by gndk** [twbs/bootstrap#36785]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When updating 5.1.3 -> 5.2.0 our webpack build fails with the following error:

```
error  in ./assets/scss/app.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
    ╷
142 │       values: $utilities-border-colors
    │               ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/_utilities.scss 142:15  @import
  assets/scss/app.scss 14:9                           root stylesheet
```

That line just imports the utilities `@import "~bootstrap/scss/utilities";`

### Reduced test cases

Don't know how to provide a test case for this as we don`t even use that variable.

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

5.2.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @gndk. There is a [new `_map.scss` in v5.2.0](https://getbootstrap.com/docs/5.2/migration/#new-_mapsscss). Don't have the details regarding your Webpack build but you probably just need to `@import "~bootstrap/scss/maps";` (that's where $utilities-border-colors is defined) before `@import "~bootstrap/scss/utilities";`.

**Comment by gndk** [comment]
Thanks for the quick reply @julien-deramond ! That did the trick 👍. I only looked at the patch notes in the GitHub release, so I completely missed that. Will remember to check the migration page more in the future 🙂

**Comment by turkic-dev** [comment]
Hello, I have this problem, how can I solve it? @gndk @julien-deramond 

https://github.com/svelte-add/svelte-add/issues/222

**Comment by fun2life** [comment]
@turkic-dev: It is important to load the modules in the exact same order as in node_modules/bootstrap/scss/bootstrap.scss
Also, the following modules must be loaded

```
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/maps";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/utilities";
@import "~bootstrap/scss/helpers";
@import "~bootstrap/scss/utilities/api";
```

**Comment by wfd2018** [comment]
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";

use of the ~ is bad practice.  Unless you show as I always do, you will generate errors.  Here is what I always use:

ex:    @import "../node_modules/bootstrap/scss/_variables.scss"; 

I know there are little shortcuts available -- but why?

**Comment by julien-deramond** [comment]
> Hello, I have this problem, how can I solve it? @gndk @julien-deramond
> 
> [svelte-add/svelte-add#222](https://github.com/svelte-add/svelte-add/issues/222)

FYI it's been solved in https://github.com/svelte-add/svelte-add/issues/222#issuecomment-1192777356

**Comment by dasler-fw** [comment]
> @turkic-dev: It is important to load the modules in the exact same order as in node_modules/bootstrap/scss/bootstrap.scss Also, the following modules must be loaded
> 
> ```
> @import "~bootstrap/scss/functions";
> @import "~bootstrap/scss/variables";
> @import "~bootstrap/scss/maps";
> @import "~bootstrap/scss/mixins";
> @import "~bootstrap/scss/utilities";
> @import "~bootstrap/scss/helpers";
> @import "~bootstrap/scss/utilities/api";
> ```

The problem was that I did not import 'scss/maps', 'scss/helpers' and 'scss/utilities/api' files

**Comment by ahmadasjad** [comment]
Event fails after adding the map.scss in react project
https://github.com/twbs/bootstrap/issues/36851#issuecomment-1200792342

**Comment by BearCooder** [comment]
I know I can just add the import `@import "~bootstrap/scss/maps";` in node_modules/bootstrap/scss/_utilities.scss and then it works but this is annoying as I need to repeat it everytime I do a fresh install with npm i. Will this be fixed?

**Comment by tomrutgers** [comment]
@BearCooder You should not change anything in node_modules, ever. Add `@import "~bootstrap/scss/maps";` to your own css instead.

**Comment by BearCooder** [comment]
So I understanded it wrong in this thread. But still adding the import @import "~bootstrap/scss/maps"; in node_modules/bootstrap/scss/_utilities.scss resolved the issue that was mentioned at the beginning.
Anyway I got rid of bootstrap, I removed it in my project as it caused to much problems

**Comment by MEETPATEL322** [comment]
fgjfgjfgj

**Comment by featuriz** [comment]
Check the Doc at: [https://getbootstrap.com/docs/5.2/customize/sass/#importing](https://getbootstrap.com/docs/5.2/customize/sass/#importing)
Download: [https://getbootstrap.com/docs/5.2/getting-started/download/#source-files](https://getbootstrap.com/docs/5.2/getting-started/download/#source-files)
From the file: **bootstrap-5.2.2/scss/bootstrap.scss**
**Copy from** _// scss-docs-start import-stack_ 
**Copy to** _// scss-docs-end import-stack_ 
to your new scss main file and set all the @import ""; to **correct path.**
**Ex:** 
**@import "functions";** -> **@import "../../../../../themes/contrib/bootstrap5/dist/bootstrap/5.2.2/scss/functions";**

**Comment by hyphen81** [comment]
I was having the same issue locally, so I added the `@import "~bootstrap/scss/maps";` line to my imports file and it worked locally, however now when I push it out to github it fails the build step:

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
11 │ @import "~bootstrap/scss/maps";
   │         ^^^^^^^^^^^^^^^^^^^^^^
   ╵
  resources/sass/app.scss 11:9  root stylesheet
    at processResult (/home/runner/work/momentum/momentum/node_modules/webpack/lib/NormalModule.js:758:19)
    at /home/runner/work/momentum/momentum/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/runner/work/momentum/momentum/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /home/runner/work/momentum/momentum/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/home/runner/work/momentum/momentum/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/runner/work/momentum/momentum/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/home/runner/work/momentum/momentum/node_modules/sass/sass.dart.js:95825:16)
    at _render_closure1.call$2 (/home/runner/work/momentum/momentum/node_modules/sass/sass.dart.js:8[38](https://github.com/hyphen81/momentum/actions/runs/3605932411/jobs/6076775872#step:8:39)82:12)
    at _RootZone.runBinary$3$3 (/home/runner/work/momentum/momentum/node_modules/sass/sass.dart.js:28060:18)
    at _FutureListener.handleError$1 (/home/runner/work/momentum/momentum/node_modules/sass/sass.dart.js:26590:21)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
Error: Process completed with exit code 1.

**Comment by chowais181** [comment]
> 

yes it's also work for me

**Comment by chowais181** [comment]
> I know I can just add the import `@import "~bootstrap/scss/maps";` in node_modules/bootstrap/scss/_utilities.scss and then it works but this is annoying as I need to repeat it everytime I do a fresh install with npm i. Will this be fixed?

yes it's also work for me

**Comment by sureshtakeda** [comment]
In the _utilities.css, you can import the maps.

@import "maps";
