### ISSUE TITLE
Card border color inconsistency

### ISSUE THREAD

**Issue by crdo** [twbs/bootstrap#36787]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`Card` cap (header/footer) border color is different than border color of the `Card` itself.

As the default cap background is `rgba($black, .03)` and the default cap border color is inherited from the `Card` via `$card-border-color` the transparent derivates of black are added up to shade of gray that is different than the `Card` border.

Therefore I suggest to introduce a new var `card-cap-border-color` whose default will be rgba($black, .145).

I have crated PR with suggested change.

### Reduced test cases

The bug can bee seen on the docs itself https://getbootstrap.com/docs/5.2/components/card/#header-and-footer.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.2

**Comment by mdo** [comment]
I'm going to close this and leave it as-is for now. The difference is quite subtle right now, and the purpose of these global styles is to _limit_ further per-component customization. Lightening the `border-color` would address a small color layering issue, but introduces new complexity to the overall system. It also reduces the contrast in the cards with `.bg-*`/`.bg-text-*` utilities applied.

I'll keep this in mind though for future theming updates—definitely want a more nuanced color system like the one I'm developing in #35857.
