### ISSUE TITLE
addEventListener is not a function error accure

### ISSUE THREAD

**Issue by ct-viral** [twbs/bootstrap#36796]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

hi,
i have do some code wile i close offcanvas but it will accure error like "addEventListener is not a function" in console.
i am use below given method in my code
https://getbootstrap.com/docs/5.2/components/offcanvas/#events

### Reduced test cases

https://codepen.io/pcodedviral/pen/qBomxJj?editors=1000

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2

**Comment by GeoSot** [comment]
Hello @ct-viral . The issue you are facing is very natural, as you are trying to attach an `eventListener` to an offcanvas Instance

```js

  const calendaroffcanvas = new bootstrap.Offcanvas('#calendar-addeditevent');
      calendaroffcanvas.addEventListener('hidden.bs.offcanvas', event => {
      console.log("event call");
    })
```

So if you change your code according to the following snippet, you will be fine

```js

  const calendaroffcanvas = new bootstrap.Offcanvas('#calendar-addeditevent');
      document.querySelector('#calendar-addeditevent').addEventListener('hidden.bs.offcanvas', event => {
      console.log("event call");
    })
```

**Comment by ct-viral** [comment]
thanks , its working
