### ISSUE TITLE
You can tab to and click disabled links

### ISSUE THREAD

**Issue by imaperson1060** [twbs/bootstrap#36795]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using the `disabled` class on links, you can still tab to them and press enter to trigger them. This also applies to `btn-link` and `nav-link`.

### Reduced test cases

```html
<a href="https://example.com" class="disabled">Link text</a>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

**Comment by rjpaulsen** [comment]
Making something like that work would be a mess. A "disabled" anchor tab isn't supported by HTML (so it's not a Bootstrap limitation). If you really-really want to do it, here is all you need to know:

https://css-tricks.com/how-to-disable-links/
