### ISSUE TITLE
Add card background colours to match other elements (e.g. alerts, tables)

### ISSUE THREAD

**Issue by rickselby** [twbs/bootstrap#36808]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

[Card backgrounds and colours](https://getbootstrap.com/docs/5.2/components/card/#background-and-color) are set up to match the theme colours directly, whereas [alert colours](https://getbootstrap.com/docs/5.2/components/alerts/#examples), [table colours](https://getbootstrap.com/docs/5.2/content/tables/#variants) and [list group items](https://getbootstrap.com/docs/5.2/components/list-group/#contextual-classes) are scaled by 80%.

I propose that similar colours are added to allow cards to be styled in a similar way to the other elements. 

### Motivation and context

This will allow more consistent theming between elements used across a site.

**Comment by noobyogi0010** [comment]
@rickselby I would like to work on this issue if no one else has taken it up.
Thanks!

**Comment by mdo** [comment]
Going to pass on this for now.
