### ISSUE TITLE
Percentage height not working on .progress

### ISSUE THREAD

**Issue by TrulyBright** [twbs/bootstrap#36806]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I tried to make a 'thick' progress bar that fits to its parent's height (i.e. `100%`), but height in percent didn't work on `.progress`:
```html
<div class="progress" style="height: 100%;">
  <div class="progress-bar"></div>
</div>
```
Neither did`.h-25`:
```html
<div class="progress h-25">
  <div class="progress-bar"></div>
</div>
```

### Reduced test cases

same as above

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by julien-deramond** [comment]
Doesn't seem to be an issue, the parent's height must be determined in order for a `height: 100%` to work.
For example something like that:
```html
<div style="height: 400px">
  <div class="progress" style="height: 100%">
    <div class="progress-bar" role="progressbar" aria-label="Basic example" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>

<div style="height: 400px" class="mt-5">
  <div class="progress h-25">
    <div class="progress-bar" role="progressbar" aria-label="Basic example" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>
```

**Comment by mdo** [comment]
Closing per @julien-deramond's example.
