### ISSUE TITLE
Add html feature to change the text colors on different screen-sizes 

### ISSUE THREAD

**Issue by maureenblack** [twbs/bootstrap#36801]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi. I am new to the world of Bootstrap and I recently discovered that it is possible to change column widths depending on screen sizes, like this:
<div class="col-md-8 d-lg-flex d-sm-block">
            <h2 class="text-info">For everything important</h2>
My question is this; would it be possible to change the text colors as the screen width changes - as we are able to with the widths themselves?

Something like this;
 Large Screens- color-red, Medium, color-blue, Small Screens, color-yellow.

### Motivation and context

This would save time as I wouldn't have to write media queries for them.

**Comment by rjpaulsen** [comment]
Hi @maureenblack -- I hear you say that you want to an element's style based on the screen width (aka, current break point). If BS were to support the change of text color based on break point, there would then be the need to support background-color and font weight, etc. This would be hard to support and make the BS markup on elements messy.

There already exists easy to use methods to accomplish what you want. METHOD 1 is good if you want minor changes (like Text color). METHOD 2 is good if you have substantial changes.

METHOD 1: Not related to BS, is the use of media queries. This works very well and lets you change any style based on the screen width and gives you everything (and more!) of what you are looking for. 

https://codepen.io/rjpaulsen/pen/xxWdMMq

You could easily expand the example to reflect Bootstrap's break points (listed on this page):

https://getbootstrap.com/docs/5.2/layout/breakpoints/

METHOD 2: If you have drastic changes between screen resolutions, the BS "Display" property could be used to toggle different screen elements based on the BS breakpoints. For example you could use an `<div class=alert` for mobile and a `<div class=card` for the desktop. I often used this for hiding images on mobile devices.

```
<div class="d-lg-none">Elements formatted for large screens</div>
<div class="d-none d-lg-block">Elements formatted for small screens</div>
```

Several examples here:

https://getbootstrap.com/docs/5.2/utilities/display/
