### ISSUE TITLE
Customize color after CDN include

### ISSUE THREAD

**Issue by Sab-tech-lab** [twbs/bootstrap#36807]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Possibility to change colour variables after css inclusion from CDN, not all variables can be overwritten e.g. button colour variables cannot be overwritten

### Motivation and context

By using a configuration-only file for variables, one could always have the updated css from the CDN without having to recompile it with custom variables.

**Comment by mdo** [comment]
This is the intention behind CSS variables vs Sass variables, which are happening as of v5.2.0. More work there will be coming in v5.3.0 and beyond as well.

**Comment by Sab-tech-lab** [comment]
OK, maybe I am not clear on how to use the variables for the button colours, are they already active?

**Comment by mdo** [comment]
https://blog.getbootstrap.com/2022/05/16/using-bootstrap-css-vars/

**Comment by Sab-tech-lab** [comment]
I really am an idota programmer, thank you very much and congratulations on your work!
