### ISSUE TITLE
Non-working .sticky-top

### ISSUE THREAD

**Issue by maofree** [twbs/bootstrap#36800]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi
I'm testing the utility
sticky-top
but it is not working
I tested it with a simple code

`<div class="sticky-top">Stick to the top on viewports sized SM or wider</div>
`

but nothing happen
instead fixed-top works

I tested it on arch linux with chrome Versione 103.0.5060.134 (Build ufficiale) (a 64 bit)
and firefox 102.0.1 (64-bit)

thanks

### Reduced test cases

`<div class="sticky-top">Stick to the top on viewports sized SM or wider</div>
`

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

**Comment by maofree** [comment]
Hi
https://stackblitz.com/edit/bootstrap-5-bhc7mq?file=src%2Findex.html

I've seen that it works but only in simple condition, in this example I use two div.
I'm developing a web site with grav cm, nothing of big, but it doesn't work.

now I've done other tests
if I add

`<div style="height: 333rem">Stick pppppppppp d SM or wider</div>`

under my div, it goes down in the right mode, without this div no

look here
they have the same problem
https://github.com/twbs/bootstrap/issues/21919

at the bottom one says that it is present also on bootstrap 5, it is something join with the height
in other form I read about the same problem


I hope you can understand the problem and fix it

**Comment by mdo** [comment]
Closing due to no live example.
