### ISSUE TITLE
[DOCS] Search is not working on mobile

### ISSUE THREAD

**Issue by ThibaultVlacich** [twbs/bootstrap#36822]
### Prerequisites

* [x]  I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc) for duplicate or closed issues
* [ ]  I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
* [x]  I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

It's impossible to use the search field of the new docs on mobile (Safari on iOS).

When I touch the search field, keyboard is not opening.

https://user-images.githubusercontent.com/334940/180612391-693527fa-cb8e-45fb-a4c5-57eed9dc4361.MOV

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Safari
### What version of Bootstrap are you using?

N/A

**Comment by mdo** [comment]
@GeoSot @julien-deramond I think we changed something here between beta and stable. Any ideas?

**Comment by julien-deramond** [comment]
This regression comes from https://github.com/twbs/bootstrap/commit/713d7140f18514c916f75be34e809ebe00c1691c

**Comment by GeoSot** [comment]
FocusTrap blocks everything outside offcanvas :/

Choices:
 * find a way to open algolia inside offcanvas Wrapper
 * add `data-bs-backdrop="false"`

**Comment by julien-deramond** [comment]
With `data-bs-backdrop="false"` we get the same result than before. Might be a quick win.
However, something doesn't work very well, when the search modal is closed by Escape key, the offcanvas doesn't get the focus automatically.

**Comment by mdo** [comment]
Maybe we move the search out of offcanvas and keep it visible at all times?

**Comment by mdo** [comment]
Example of search being outside the offcanvas:

<img width="564" alt="Screen Shot 2022-07-23 at 10 58 18 AM" src="https://user-images.githubusercontent.com/98681/180615136-78dda761-c106-44a1-8566-73b9f1309561.png">

**Comment by GeoSot** [comment]
I would prefer it, as it is the most frequent functionality I use
