### ISSUE TITLE
5.2.0: Popover - Unable to use `getInstance` on `.popover` element

### ISSUE THREAD

**Issue by leettaylor** [twbs/bootstrap#36837]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Regression from `v5.1.3`. Can no longer get the Popover instance from the `.popover` element itself.

e.g.
```javascript
const popover = bootstrap.Popover.getInstance('.popover');

// popover will be null
```

it now only works when using it on the trigger, e.g.

```javascript
const popover = bootstrap.Popover.getInstance('.popover-trigger');

// popover will contain the popover element
```

### Reduced test cases

v5.2.0: https://stackblitz.com/edit/h7ep9y?file=index.html,index.js
v5.1.3: https://stackblitz.com/edit/h7ep9y-vtddun?file=index.html

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by it-can** [comment]
I have a similar problem with the Carousel. My fix was using ```getOrCreateInstance```

**Comment by GeoSot** [comment]
In both cases, you are initializing the popover Instance using the following script

```js
  document.querySelectorAll('[data-bs-toggle="popover"]').forEach((popover) => {
    new bootstrap.Popover(popover);
  });
```
So, programmatically thinking if you want to use the methods of this instance, you have to keep it as a variable or to refer to it, using the same selector
```js
bootstrap.Popover.getInstance('[data-bs-toggle="popover"]');
```

Of course, you are right saying that you had found out a trick in where you could use the dynamic created element just to refer to the same instance, but as it was an intrusive and not documented way, I suppose you have to avoid it.  
Worst case scenario, you can travel to the initial instance element using something like:
```js

const x= document.querySelector(`.popover`).getAttiribute('id')

const initialElem = document.querySelecto('[aria-describedby="'+ x +'"]')
```


**/cc** @julien-deramond any different opinion on this?

**Comment by leettaylor** [comment]
> Of course, you are right saying that you had found out a trick in where you could use the dynamic created element just to refer to the same instance, but as it was an intrusive and not documented way, I suppose you have to avoid it.

I think updating my code to use the documented method that you've suggested makes the most sense. 

Is it worth updating the migration guide to mention the removal of the undocumented way?

**Comment by GeoSot** [comment]
> Is it worth updating the migration guide to mention the removal of the undocumented way?

I think is controversial, to document (mention) a change on  an undocumented way :wink:

**Comment by GeoSot** [comment]
Something like ???

```js
  document.querySelectorAll('[data-bs-toggle="popover"][aria-describedby]').forEach((popover) => {
    bootstrap.Popover.getOrCreateInstance(popover).hide();
  });

```
(same for tooltip)
