### ISSUE TITLE
SCSS _variables.scss file has misspelled variable: heading-color (node package)

### ISSUE THREAD

**Issue by UAK-35** [twbs/bootstrap#36847]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The current version (5.2.0) SCSS _variables.scss file has following statement at line 1363:
`$popover-header-color:              var(--#{$prefix}heading-color) !default;`

It should be as follows:
`$popover-header-color:              var(--#{$prefix}headings-color) !default;`

Note the **s** just before hyphen right before the word **color**, and I have used node to install bootstrap using following command:
`npm i bootstrap`

The effect of this bug is that dart-sass still compiles this file successfully but $popover-header-color variable has no value.

Thanks.

### Reduced test cases

You can change line 1363 as follows:
`$popover-header-color:              $heading-color !default;`

and it will not compile. It should be as below to compile sucessfully:
`$popover-header-color:              $headings-color !default;`
 
Note the **s** just before hyphen right before the word **color**.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @UAK-35! You're right `--#{$prefix}heading-color` isn't defined anymore anywhere due to recent changes. I've created a PR to fix it.
