### ISSUE TITLE
Tooltip not displayed properly

### ISSUE THREAD

**Issue by RihabEA** [twbs/bootstrap#36841]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

When we update the bootstrap from 5.1.3 to 5.2.0, there is an issue with position of the tooltip, related to an icon within a cell.

Kindly find below the two plunkers created to display the issue:

1- Current Behavior (bootstrap: 5.2.0): when we click the icon in the cell (price column), the tooltip appears in the wrong place

https://stackblitz.com/edit/current-behav-tooltip-not-dislaying-properly-in-the-grid?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

2- Expected behavior (using the old version 5.1.3): when we click the icon in the cell, the tooltip open in the right place

https://stackblitz.com/edit/expected-beha-tooltip-dislaying-properly?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

Note:
Angular version: 14.0.6
Ag-grid version: 28.0.2
Bootstrap: 5.2.0
ngx-bootstrap: 9.0.0

### Reduced test cases

1- Current Behavior (bootstrap: 5.2.0): when we click the icon in the cell (price column), the tooltip appears in the wrong place

https://stackblitz.com/edit/current-behav-tooltip-not-dislaying-properly-in-the-grid?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

2- Expected behavior (using the old version 5.1.3): when we click the icon in the cell, the tooltip open in the right place

https://stackblitz.com/edit/expected-beha-tooltip-dislaying-properly?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

Bootstrap: 5.2.0, ngx-bootstrap: 9.0.0

**Comment by GeoSot** [comment]
Hello @RihabEA :smiley: 

As you are not using the 'native' bootstrap library (only the css), I think it would be better to ask first on https://github.com/valor-software/ngx-bootstrap

In case, you can replicate the same problem using bootstrap js & css, I could give it a look

**Comment by RihabEA** [comment]
Okay, I'll check, Thanks for your reply!
