### ISSUE TITLE
customize Bootstrap 5 rtl 

### ISSUE THREAD

**Issue by grahhal** [twbs/bootstrap#36842]
IIts not clear how to use customize bootstrap 5 RTL , I read the documentation on bootstrap & RTLCSS but it is still not clear, 
I am designing a pure frontend template, and I cant implement the RTL Bootstrap 5

1. I download bootstrap through NPM,
2. I used SCSS  to customize the colors theme and generate main.css from main.scss file
3. I added the following to my main.scss
  body[dir='rtl']{
    direction: rtl !important;
}
4. I added RTL dir & lang Ar to my body tag

Still, the design is LTR when it comes to text-end & text-strat,,, ms & me it's not reversed, padding and margins, could you please assist and post clear steps on how to use it! I searched on Overstack Website all are asking the same and there is no clear way!

**Comment by ffoodd** [comment]
You don't need to add any CSS: once you compiled your `main.scss` file to `main.css`, you need another task running RTLCSS to generate `main.rtl.css` from `main.css`.

As seen in our default build, you need two separate CSS files for LTR and RTL.

Then in tour RTL page markup, you simple need  to switch `main.css` to `main.rtl.css`.

Dors it help?

We may need to improve the docs regarding those steps, indeed.
