### ISSUE TITLE
5.0 documentation "View on Github" hyperlink is 404ing

### ISSUE THREAD

**Issue by KartoffelCheetah** [twbs/bootstrap#36853]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In some versions the "View on GitHub" hyperlink inside documentation goes to Github's 404 page.

Example:

The following page https://getbootstrap.com/docs/5.0/components/modal/ includes a hyperlink near the top of the page to the md file at https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/components/modal.md . Since the link does not point to a fixed tag, but the main branch it cannot find the "5.0" folder which was since renamed to "5.2".

At least in the current version it's generated like this:

```html
{{ .Site.Params.repo }}/blob/main/site/content/{{ .Page.File.Path | replaceRE `\\` "/" }}
```

https://github.com/twbs/bootstrap/blob/713d7140f18514c916f75be34e809ebe00c1691c/site/layouts/_default/docs.html#L19

### Reduced test cases

1. Open the page https://getbootstrap.com/docs/5.0/components/modal/ 
2. Click the button "View on Github"
3. The 404 Github page is displayed.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.0

**Comment by julien-deramond** [comment]
Oh good catch @KartoffelCheetah! Thanks for reporting this one!
As you mentioned we could try to point to the tag rather than the _main_ branch. In this case it would be nice to modify our _gh-pages_ branch to fix it for previous versions as well.
