### ISSUE TITLE
v5.1.3: Scrollable Form inside Modal not working

### ISSUE THREAD

**Issue by ianoel230982** [twbs/bootstrap#36856]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have the same issue as this post - [https://github.com/twbs/bootstrap/issues/34672](https://github.com/twbs/bootstrap/issues/34672) - where by I have a form inside a modal and the 'modal-dialog-scrollable' class does not seem to be doing what it should. There is no scrolling on the modal body.

I have tried altering a few css properties in browser but unable to get it working.
I'm hopeful this can be fixed easy enough or can be pointed in the right direction to get it working manually for the time being.

### Reduced test cases

Live demo here -  [https://codepen.io/ianoel230982/pen/XWEzbWq](https://codepen.io/ianoel230982/pen/XWEzbWq)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by GeoSot** [comment]
Hello @ianoel230982 
Just a small change and you are fine to go. The `<form>` element has to be inside `.modal-body`

**Comment by ianoel230982** [comment]
> Hello @ianoel230982 Just a small change and you are fine to go. The `<form>` element has to be inside `.modal-body`

Hi, thanks for that.

Left me with another issue, being that by form submit buttons are in the modal-footer so cannot directly submit the form in the modal body. I've got round that now with some Javascript :-)

Thanks again @GeoSot :-)

**Comment by GeoSot** [comment]
You may try to use the form as '.modal-content' , but I cannot be sure of the results
