### ISSUE TITLE
Scrollbar click closes modal with long content

### ISSUE THREAD

**Issue by IvanVasquez** [twbs/bootstrap#36855]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Previously on v5.1 when a modal was open, I was able to scroll throw the content by clicking any part of the window scrollbar, now on 5.2 clicking the scrollbar closes automatically the modal.

I tested on bootstrap docs page just to be sure I wasn't doing anything different and the issue can be tested by opening the demo modal for long content and clicking the scrollbar.

### Reduced test cases

v5.1 (scroll bar click works)
https://getbootstrap.com/docs/5.1/components/modal/#scrolling-long-content

v5.2.0 (scroll bar click closes modal)
https://getbootstrap.com/docs/5.2/components/modal/#scrolling-long-content

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.2.0

**Comment by julien-deramond** [comment]
This issue seems to come from https://github.com/twbs/bootstrap/commit/d05c42a3979be30efc7a932c3c0f483098841b19.

**Comment by dgibbs64** [comment]
I cant confirm this behaviour as well.
