### ISSUE TITLE
Newsletter subscription is successful with invalid email id

### ISSUE THREAD

**Issue by Sinha1994** [twbs/bootstrap#36864]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On [themes.getbootstrap.com](https://themes.getbootstrap.com/) newsletter section, allows email subscriptions with invalid emails as well. 

### Reduced test cases

1. Open page [themes.getbootstrap.com](https://themes.getbootstrap.com/) 
2. Scroll to the bottom newsletter section
3. Enter invalid emails like #agdkkar@d.y
4. Click on subscribe, it's giving a subscription successful message

<img width="925" alt="bootstrap_2" src="https://user-images.githubusercontent.com/28135546/181904938-8601b49e-31aa-43f5-9de8-6e6efe1c7a20.png">

<img width="824" alt="bootstrap_3" src="https://user-images.githubusercontent.com/28135546/181904942-71289e9a-43ee-4642-9439-af1a0ef8f7d7.png">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5

**Comment by mdo** [comment]
This should be sent via email to the Themes support email address. Thanks!
