### ISSUE TITLE
Detach $card-border-width and $card-border-color from card header and footer

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#36862]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Not sure if that's a bug or an improvement. Currently we have 2 component-level variables that are re-used in inner elements:

```
.card {
    border: var(--#{$prefix}card-border-width) solid var(--#{$prefix}card-border-color);
}
.card-header {
    border-bottom: var(--#{$prefix}card-border-width) solid var(--#{$prefix}card-border-color);
}
.card-footer {
    border-top: var(--#{$prefix}card-border-width) solid var(--#{$prefix}card-border-color);
}
```

If i need to remove or override card border by setting width or color values to null, i would expect the border to disappear only from main container, but not from header and footer. 

### Motivation and context

To be able to remove border from parent container and child elements separately

**Comment by mdo** [comment]
No plans to separate these—these feels like a solid convenience to include by default.
