### ISSUE TITLE
Same code examples in different versions

### ISSUE THREAD

**Issue by akinuri** [twbs/bootstrap#36878]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I believe there's an issue with the documentation. Version [4.5](https://getbootstrap.com/docs/4.5/components/forms/#checkboxes-and-radios) and [5.1](https://getbootstrap.com/docs/5.1/forms/checks-radios/#checks) seem to provide the same code examples even though the usage differs between them.

### Reduced test cases

I see that in the recent versions, the syntax changed a little. For example, this is from the 5.1:

```html
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">
    Default checkbox
  </label>
</div>
```

but the same syntax is also in the 4.x versions. However, it doesn't work. I checked my code and some online examples, and in the version 4, one has to use the following:

```html
<div class="custom-control custom-checkbox">
    <input type="checkbox" class="custom-control-input" id="defaultCheck1" />
    <label class="custom-control-label" for="defaultCheck1">Default checkbox</label>
</div>
```

Am I missing something here?

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

4.5.2

**Comment by mdo** [comment]
Class names changed between v4 and v5, so they're not interoperable. All the custom forms changed to just regular forms in v5 as a way to simplify everything.
