### ISSUE TITLE
The `active` class of `dropdown-item` is not being switched correctly after 5.2.

### ISSUE THREAD

**Issue by maliming** [twbs/bootstrap#36894]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The `active` class of `dropdown-item` is not being switched correctly.

### Reduced test cases

Try to select the item on the dropdown menus.

![image](https://user-images.githubusercontent.com/6908465/182605345-b055b9e7-7df9-4bd5-b1ea-4857fc528831.png)

Bootstrap 5.1
https://stackblitz.com/edit/web-platform-kwgudn?file=index.html

Bootstrap 5.2
https://stackblitz.com/edit/web-platform-tqeusi?file=index.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2

**Comment by omkarpawar2001** [comment]
Can you send me repo link where i can fork and send pull request? I have fixed the issue.. Kindly assign it to me

**Comment by julien-deramond** [comment]
> Can you send me repo link where i can fork and send pull request? I have fixed the issue.. Kindly assign it to me

We don't assign tasks. You can propose a PR to fix this issue. You have the info to fork the repo directly in https://github.com/twbs/bootstrap.

**Comment by GeoSot** [comment]
I suppose is solved on #37151

@maliming please try to use the following script and give us some feedback
https://deploy-preview-37151--twbs-bootstrap.netlify.app/docs/5.2/dist/js/bootstrap.bundle.min.js

**Comment by maliming** [comment]
Thanks @GeoSot I will test it asap.

**Comment by maliming** [comment]
Solved by https://github.com/twbs/bootstrap/pull/37151
