### ISSUE TITLE
Dropdown module constructor globally initializes all JS modules

### ISSUE THREAD

**Issue by sreigle** [twbs/bootstrap#36898]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`new Dropdown('#myId');` initializes all bootstrap js modules. Passed in one id to the constructor and noticed both dropdowns work. Along with other modules such as Alert dismissal and Collapse.

### Reduced test cases

https://github.com/sreigle/bootstrap-global-bleed

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

**Comment by GeoSot** [comment]
Hello @sreigle,

Please try to read carefully the docs, specially the two section below, and I think you will get the reason and that it is done by design

https://getbootstrap.com/docs/5.2/components/dropdowns/#usage

https://getbootstrap.com/docs/5.2/components/dropdowns/#via-data-attributes
