### ISSUE TITLE
Floating label with arbitrary sibling element to `<input>`

### ISSUE THREAD

**Issue by septatrix** [twbs/bootstrap#36896]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently styles hardcode `.form-floating > label` and `... ~ label`. The selector should instead target a new class `.floating-label` or similar.

### Motivation and context

At my company we have the policy to avoid `<label>`s with an explicit `for=elementId` attribute and instead use implicit references by nesting the input inside the label. This is not compatible with floating labels and also inconsistent with all other label styling provided by bootstrap which can be applied using a class.

**Comment by mdo** [comment]
This would be a breaking change to modify the selector and require a class on the labels. I also believe we _need_ the adjacent selector because we're targeting the label when the input is focused and the placeholder isn't shown. No way around that one.

**Comment by septatrix** [comment]
If there are no other aspects to consider I could work on this myself (though only in a few weeks) and create a PR if this feature is desired.

**Comment by mdo** [comment]
For now we'll leave this as-is. Let's revisit for v6 :).
