### ISSUE TITLE
Intermediate max-width and/or flex-grow utilities

### ISSUE THREAD

**Issue by 4javier** [twbs/bootstrap#36905]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Adding `mw-25 mw-50 mw-75` and/or `flex-grow-25 flex-grow-50 flex-grow-75` classes.
Alternative solution addressing `.input-group` specific usecase:
adding `.form-control-25 .form-control-50 .form-control-75` setting relative `flex-grow` properties.

### Motivation and context

Some times it could be handy having a quick solution to limit growing of specific flex items to render some kind of "grid" with mixed width elements, without having to relies on the whole BS Grid layout.

My specific usecase is for an `.input-group` with multiple `input` elements with different width requirements.
At the moment `.form-control` will arrange the elements equally due to `flex-grow:1`.
Imagine a form group letting the user input an ingredient and its content percentage: you don't want an allegedly long string having the same available space of a two (or five, if a couple decimals) digits number.

You could probably style it through BS Grid layout but you'd end up with:
a) adding `col-*` classes to the element directly, that looks a bit out-of-spec to me (I see `col*` as something to be assigned only to the **container** of the actual element)
or
b) adding a bunch of overwhelming `.row > .col` polluting your template and being "conceptually wrong" considering that `.input-group` already set the element as a flex container.

This is my mockup
![immagine](https://user-images.githubusercontent.com/459381/182918947-0b0a100d-23c9-4fff-8041-fbff27711a33.png)
(padding on `.input-group-text`s has been zeroed for the sake of rendering on mobile.)
Here's the link if you want to puzzle around with it (I was too lazy to use mixins. I'll do that if ever you'll suggest a pull request)
https://codepen.io/team/bootstrap/pen/qBamdLj

**Comment by mdo** [comment]
Thanks for the feedback! Stuff like this is why we have the utility API so you can add your own custom utilities whenever you need them. Have a look at that in our docs :).
