### ISSUE TITLE
bootstrap popover & tooltip on hover doesn't display when cursor enters button at the edge where the popover-caret would be placed

### ISSUE THREAD

**Issue by folsze** [twbs/bootstrap#36901]
When doing exactly what is described below, this happens 95% of the time. However I noticed sometimes there are periods where it doesn't happen 10x in a row.

This happens even on the bootstrap example itself:
https://ng-bootstrap.github.io/#/components/popover/examples

This only happens when entering **slowly** with the cursor at the red marked line here:
![image](https://user-images.githubusercontent.com/81622754/182820161-8f6ad22c-a251-4c49-af68-8adcf10e63a6.png)

This also only happens if the movement of the cursor is **slow**.

It is especially problematic with small buttons, as the popover-caret size is absolute and thus takes up a bigger percent of the button-edge.

Also you can see the cursor quickly switching between default and pointer around 100 times per second when exactly over the red line. This is likely a byproduct of the bug.

**Comment by GeoSot** [comment]
I see the gif, but I cannot replicate it in windows & linux (chrome, brave, firefox) . Can you provide more details?

**Comment by Nudasoft** [comment]
I think it's not a big deal. It's only happening when the mouse enter so slowly.

![tooltip__1](https://user-images.githubusercontent.com/30935025/183259586-85b40ff9-d479-4f9f-aea9-d9c47ef590a2.gif)

**Comment by folsze** [comment]
> I see the gif, but I cannot replicate it in windows & linux (chrome, brave, firefox) . Can you provide more details?

Yes I guess it doesn't happen on all devices. I tried it on my work laptop with chrome and it happened but now on my personal (newer/better) one it doesn't happen. 

My work laptop is a think pad.



> I think it's not a big deal. It's only happening when the mouse enters so slowly.
> 
> ![tooltip__1](https://user-images.githubusercontent.com/30935025/183259586-85b40ff9-d479-4f9f-aea9-d9c47ef590a2.gif) [ ![tooltip__1](https://user-images.githubusercontent.com/30935025/183259586-85b40ff9-d479-4f9f-aea9-d9c47ef590a2.gif) ](https://user-images.githubusercontent.com/30935025/183259586-85b40ff9-d479-4f9f-aea9-d9c47ef590a2.gif) [ ](https://user-images.githubusercontent.com/30935025/183259586-85b40ff9-d479-4f9f-aea9-d9c47ef590a2.gif)

Cleary this doesn't happen 95% of the time on your setup (but it did on the bootstrap wesbite using my work laptop). 

This does happen like 80% of the time on my application actually, and this even without going "unrealistically" slow, just normal user speed slow.

**Comment by folsze** [comment]
https://user-images.githubusercontent.com/81622754/183368666-8375c580-b1a0-402e-9c8f-89420fff1429.MOV

This is what it looks like in my application. As you can see it only appears twice when trying like 15-20 times.

(Sry no screen record/gif cause no ShareX cause work laptop)

**Comment by dkrnl** [comment]
same issue after update `bootstrap@5.1` to `bootstrap@5.2`

![image](https://user-images.githubusercontent.com/734622/183543539-9541af21-3255-4405-bc34-f221cf467fa8.png)

**Comment by folsze** [comment]
> same issue after update `bootstrap@5.1` to `bootstrap@5.2`
> 
> ![image](https://user-images.githubusercontent.com/734622/183543539-9541af21-3255-4405-bc34-f221cf467fa8.png)

How exactly is this the same issue? Should the popover/tooltip appear on top of the caret you circled but it doesn‘t? Where is the mouse cursor, from where did you enter etc. from the picture you sent not much can be related for me.

**Comment by folsze** [comment]
Is there any chance of this getting fixed soon or rather not?

Can I provide any additional information for you to be able to fix this? 

@GeoSot 
I see the gif, but I cannot replicate it in windows & linux (chrome, brave, firefox) . Can you provide more details?

What details exactly would be helpful to solve this? I will try listing some:

![image](https://user-images.githubusercontent.com/81622754/183637479-4dae0dfe-f728-410e-be84-ebb1508baaa4.png)

We are using ng-bootstrap for our application. But as @Nudasoft commented it also happens on the general boostrap tooltip-page.

I am eager to help solving this, can also use discord if this helps to provide more information or better explain the problem scenario.

**Comment by folsze** [comment]
Was this fixed by adding this gap between the element and the tooltip/popover-caret-arrow?

![image](https://user-images.githubusercontent.com/81622754/188842789-be62e5a1-9a5e-497a-918d-25d1e800f56b.png)

If so, if someone could confirm, then I think this can be closed.
