### ISSUE TITLE
@Import function being deprecated from SASS

### ISSUE THREAD

**Issue by gautam071** [twbs/bootstrap#36909]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

In Scss the `@import` will be deprecated in favour of `@use` and `@forward`, and support will be dropped by October 2022 at the latest [to know more](https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline)`

### Motivation and context

I have seen some bootstrap files use the `@import` function. The SCSS is going to deprecate. We need to use `@use` and `@forward`

**Comment by ffoodd** [comment]
Duplicates #28953
