### ISSUE TITLE
Shadows and Pagination - apply breaking points

### ISSUE THREAD

**Issue by lars-lindstrom** [twbs/bootstrap#36907]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Shadows are a great feature, and the choice of sizes are fine. But I think breakpoints are missing. While shadows look great on larger screens, the tend to have less use on smaller devices i.e. cell phones. Thus a `shadows-none`, `shadows-none-sm`, `shadows-none-md`, `shadows-none-lg`, `shadows-none-xl` and `shadows-none-xxl would be fantastic`.

The same request would be nice on `pagination` and make responsive designs easier

### Motivation and context

se above

**Comment by mdo** [comment]
Shadows you can enable via utility API. Pagination would need to be done manually—no plans to tweak that ourselves.
