### ISSUE TITLE
Suggest a new feature - responsive padding & margin is not available

### ISSUE THREAD

**Issue by prakharisg** [twbs/bootstrap#36913]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

like p-sm-0, p-md-0

### Motivation and context

i need this type of things in my projects

**Comment by crftwrk** [comment]
They already there https://getbootstrap.com/docs/5.2/utilities/spacing/

p-0 p-md-4 p-lg-5

**Comment by ffoodd** [comment]
Closing per last comment. Our default build contqins responsable spacing utilities.

**Comment by prakharisg** [comment]
thankyou all for precious information
