### ISSUE TITLE
list-group change in behavior between v4.3.1 and v4.4.0 for paragraph tag

### ISSUE THREAD

**Issue by clach04** [twbs/bootstrap#36919]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://getbootstrap.com/docs/4.0/components/list-group/ shows samples with both ul/li list tags and div with other tag types.

:heavy_check_mark: In version 3.4.1 of bootstrap (and earlier) paragraph/p tags work fine. See 
[bootstrap_431_working.html.txt](https://github.com/twbs/bootstrap/files/9277730/bootstrap_431_working.html.txt)
![image](https://user-images.githubusercontent.com/424032/183314488-e66cb7af-60af-4172-93f1-940616dd0b5a.png)

:x: However in v 4.4.0 (the next following version) the "boxes" don't connect and have gaps/holes. See 
[bootstrap_440_bad_lines.html.txt](https://github.com/twbs/bootstrap/files/9277733/bootstrap_440_bad_lines.html.txt)
![image](https://user-images.githubusercontent.com/424032/183314535-d4b76655-4dc7-49bc-b557-8e6e5aed05d0.png)

:heavy_check_mark: Using list ul/li tags can be used as a workaround. See [bootstrap_440_li_instead_of_p.html.txt](https://github.com/twbs/bootstrap/files/9277736/bootstrap_440_li_instead_of_p.html.txt)
![image](https://user-images.githubusercontent.com/424032/183314588-e3568971-97db-477e-8315-3e61912bfafb.png)

I think this is a bug, but from docs it's not clear on expected behavior for p tags *but* it used to work with the earlier versions.

NOTE I used https://validator.w3.org/nu/#file Version: 22.8.7 for validation

### Reduced test cases

See attached, inline below:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>bootstrap 5 issues</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    </head>
    <body>

        <div class="container">
            <div id="datalist">
                <div class="list-group">
                    <p class="list-group-item list-group-item-action">
                        tz : tanzania, united republic of
                    </p>
                    <p class="list-group-item list-group-item-action">
                        ae : united arab emirates
                    </p>
                    <p class="list-group-item list-group-item-action">
                        gb : united kingdom
                    </p>
                    <p class="list-group-item list-group-item-action">
                        us : united states
                    </p>
                    <p class="list-group-item list-group-item-action">
                        um : united states minor outlying islands
                    </p>
                </div>
            </div>
        </div>

    </body>
    </html>

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v3.3.6, v3.4.1, v4.4.0, v5.2.0

**Comment by clach04** [comment]
I skimmed https://github.com/twbs/bootstrap/compare/v4.3.1...v4.4.0 file diffs in the list-group files but nothing jumped out at me :crying_cat_face:

**Comment by mdo** [comment]
Both versions mentioned here are out of date and not actively maintained. Also, you're using `<p>` elements which have `margin-bottom` by default, perhaps messing up the default `.list-group` styling. Generally speaking, you should be building this content with more semantic markup at the very least. Closing as a won't fix given all this.
