### ISSUE TITLE
The text color of the navbar is not changing to white for bg-dark (background color: dark)

### ISSUE THREAD

**Issue by Samadrita-Shaw** [twbs/bootstrap#36920]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The navbar with bg-dark is supposed to change the background color of the navbar to dark and the text color to light. 
But now, even after trying and reloading the website several times, I have observed that the background color is changing to dark, but the text color is remaining dark instead of changing to light. 

### Reduced test cases

<nav className= "navbar navbar-expand-lg bg-dark">
This was supposed to change the navbar to dark navbar, but it is not changing the text-color.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.x

**Comment by florianlacreuse** [comment]
You also need to add `.navbar-dark`.

https://getbootstrap.com/docs/5.2/components/navbar/#color-schemes

**Comment by mdo** [comment]
Correct, `.bg-dark` only changes the `background-color`.
