### ISSUE TITLE
Scrollspy doesn't work with CJK, Greek language targets

### ISSUE THREAD

**Issue by razonyang** [twbs/bootstrap#36939]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Related issue twbs/bootstrap#10205(v2/v3)

```text
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#%E8%83%8C%E6%99%AF%E5%9B%BE%E7%89%87' is not a valid selector.
    at Object.findOne (https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:9928)
    at mn._initializeTargetsAndObservables (https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:72435)
    at mn.refresh (https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:70756)
    at new mn (https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:70629)
    at mn.getOrCreateInstance (https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:8197)
    at https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:73489
    at i (https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js:6:4253)
```

### Reduced test cases

https://codepen.io/razonyang/pen/rNdZBjg

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by razonyang** [comment]
@GeoSot Hi, this issue still exists on the main branch, but I've no permission to re-open this issue.

**Comment by GeoSot** [comment]
According to  #35566 tests, it shouldn't exist. Please, Update your codepen, or open a new issue (with the given example) 

Thank you @razonyang

**Comment by razonyang** [comment]
@GeoSot Thanks for the quick response. Since it's hard to import the latest change of `main` branch in CodePen, I fork and create a new branch called [scrollspy](https://github.com/razonyang/bootstrap/tree/scrollspy), which include [examples](https://github.com/razonyang/bootstrap/tree/scrollspy/dist) inside the `dist` folder.

The `index.en.html` works fine, but the `index.html`(with Chinese characters anchors) doesn't.

> I've run the `npm run dist` for compiling the source code to `dist` folder.

**Comment by razonyang** [comment]
👀 Hi, is there any updates?
