### ISSUE TITLE
Docs - Migrating to v5 - Missing dropdown-menu-right => dropdown-menu-end

### ISSUE THREAD

**Issue by GarethPrattCv** [twbs/bootstrap#36937]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, in this guide:
https://getbootstrap.com/docs/5.0/migration/

There's no mention of dropdown-menu-right having been removed.  It has been replaced with dropdown-menu-end.

### Reduced test cases

n/a

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5

**Comment by Geuchmann** [comment]
The guide is good enough in my opinion:

![1](https://user-images.githubusercontent.com/39516415/184019748-6cf25b16-3160-4da7-829e-413b17fc5f68.png)

**Comment by julien-deramond** [comment]
It is mentioned as well in [Migration > RTL](https://getbootstrap.com/docs/5.2/migration/#rtl)

https://github.com/twbs/bootstrap/blob/29332a954f86671d39f60007fb0c2ea633731e88/site/content/docs/5.2/migration.md?plain=1#L255-L257
