### ISSUE TITLE
Collapse.Options.parent default value: Type 'boolean' is not assignable to type 'string | Element | JQuery'

### ISSUE THREAD

**Issue by eyesofkids** [twbs/bootstrap#36936]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`Collapse.Options.parent` default value is `false`. It is `boolean` type.
`Collapse.Options.parent` type is `string | Element | JQuery` and can't defined as `boolean` type.

`options: Collapse.Options = { parent: false, toggle: true }`

ts error:

> Type 'boolean' is not assignable to type 'string | Element | JQuery'.

### Reduced test cases

from: https://getbootstrap.com/docs/5.2/components/collapse/#options

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by GeoSot** [comment]
Hello @eyesofkids and thank you for reporting this
Seems our docs need to be fixed there. Just use `null` or an HTMLelement

**Comment by monsterRocky** [comment]
Extract expand and then update API
