### ISSUE TITLE
Accordion body color

### ISSUE THREAD

**Issue by refius** [twbs/bootstrap#36945]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

My accordion body color suddenly shows white after upgrade BS 5.1.3 to 5.2

Looks like color and bg use the same variable in `_accordion.scss` ... hmm?
`--#{$prefix}accordion-color: #{color-contrast($accordion-bg)};`
`--#{$prefix}accordion-bg: #{$accordion-bg};`

#### Variable setup:
`$body-bg:                                 $white;`
`$body-color:                              $dark;`

#### Fixed it by override scss:
`.accordion {
    --#{$prefix}accordion-color: $accordion-color;
}`

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

**Comment by mdo** [comment]
Fixed by #36921.
