### ISSUE TITLE
missing css variables for modal element ^5.0.0

### ISSUE THREAD

**Issue by adb-sh** [twbs/bootstrap#36975]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

i'm using vue3 with vite.
bootstrap is imported like this in `main.ts`:
```
import "bootstrap/scss/bootstrap.scss";
```

(gray values are undefined:)

![image](https://user-images.githubusercontent.com/38115351/184872040-f6d16a28-a323-4dfd-a456-5b3f7c97ff91.png)
![image](https://user-images.githubusercontent.com/38115351/184872076-5f9d15d9-1711-43c3-96a2-f129df0d0844.png)
![image](https://user-images.githubusercontent.com/38115351/184872122-16e7773c-5784-4781-a21b-bb51db958e19.png)
![image](https://user-images.githubusercontent.com/38115351/184872172-41e7f943-4ba7-4b8d-b0cc-0e5374860f5e.png)
![image](https://user-images.githubusercontent.com/38115351/184872201-e1c2edca-6ad7-4d7b-bd95-2f26c899e1e4.png)

### Reduced test cases

-

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.0.2, v5.2.0

**Comment by Geuchmann** [comment]
Sounds like a local problem. Working fine on https://getbootstrap.com/docs/5.2/components/modal/.

![2022-08-16 18_26_32-Modal · Bootstrap v5 2](https://user-images.githubusercontent.com/39516415/184930637-25b25007-e08f-42d8-8639-a8845cbd0238.png)

**Comment by tungphan995** [comment]
Thank you for believing in me.

**Comment by v1r0x** [comment]
I have the same problem. Also some of my overwritten sass variables are ignored (e.g. `breadcrumb-divider`)

**Comment by Geuchmann** [comment]
https://github.com/twbs/bootstrap/issues/36973#issuecomment-1217995398 can maybe help.

**Comment by v1r0x** [comment]
Unfortunately, not. I As @adb-sh I simply import the whole bootstrap sass code

**Comment by Geuchmann** [comment]
Variables working fine on https://codepen.io/randomName77/pen/gOeZqqP.

**Comment by mdo** [comment]
All the variables are present and functioning correctly. Please make sure you're using v5.2.0.

**Comment by crftwrk** [comment]
I can confirm this issue in 5.2.0 too, tested with CDN as well. In my case a JS generated Cookie Modal doesn't fetch the variables while the normal Modals are fine. Fixed it by adding variables to the root.

| Broken | Default | Fixed  |
| :-------------: | :-------------: | :-------------: |
| ![broken-1](https://user-images.githubusercontent.com/51531217/185683649-ebdeef4b-3bde-4a33-adb9-68d494bf9bc3.png) | ![default](https://user-images.githubusercontent.com/51531217/185680398-55132df2-2b70-4a76-9c28-41b7c15a3e26.png) | ![fixed](https://user-images.githubusercontent.com/51531217/185680462-3e0236fb-f1d0-419e-93e2-34e357aa45ff.png) |

Broken: https://dev.bootscore.me/cheatsheet/, scroll to the footer and click "Cookie preferences"

Default Modal: https://dev.bootscore.me/cheatsheet/#modal, click the "Launch demo modal" button



Adding variables to root in an additional scss file fixes this:

```scss
:root {
  --#{$prefix}modal-zindex: #{$zindex-modal};
  --#{$prefix}modal-width: #{$modal-md};
  --#{$prefix}modal-padding: #{$modal-inner-padding};
  --#{$prefix}modal-margin: #{$modal-dialog-margin};
  --#{$prefix}modal-color: #{$modal-content-color};
  --#{$prefix}modal-bg: #{$modal-content-bg};
  --#{$prefix}modal-border-color: #{$modal-content-border-color};
  --#{$prefix}modal-border-width: #{$modal-content-border-width};
  --#{$prefix}modal-border-radius: #{$modal-content-border-radius};
  --#{$prefix}modal-box-shadow: #{$modal-content-box-shadow-xs};
  --#{$prefix}modal-inner-border-radius: #{$modal-content-inner-border-radius};
  --#{$prefix}modal-header-padding-x: #{$modal-header-padding-x};
  --#{$prefix}modal-header-padding-y: #{$modal-header-padding-y};
  --#{$prefix}modal-header-padding: #{$modal-header-padding};
  --#{$prefix}modal-header-border-color: #{$modal-header-border-color};
  --#{$prefix}modal-header-border-width: #{$modal-header-border-width};
  --#{$prefix}modal-title-line-height: #{$modal-title-line-height};
  --#{$prefix}modal-footer-gap: #{$modal-footer-margin-between};
  --#{$prefix}modal-footer-bg: #{$modal-footer-bg};
  --#{$prefix}modal-footer-border-color: #{$modal-footer-border-color};
  --#{$prefix}modal-footer-border-width: #{$modal-footer-border-width};
}
```

**Comment by Geuchmann** [comment]
@crftwrk 
It's because the buttons trigger the `#modal` dialog and the "preferences link" trigger the `#dialog` dialog.
The JS work same by both, but by the `#dialog` dialog is missing the `.modal` class.
So you have missing variables, because your html have invalid bootstrap syntax.

**Comment by Geuchmann** [comment]
@crftwrk 
It's because the buttons trigger the #modal dialog and the "preferences link" trigger the #dialog dialog.
The JS work same by both, but by the #dialog dialog is missing the .modal class.

**Comment by mdo** [comment]
Yes, as mentioned above, all the variables for each component are on specific classes, on this case `.modal`. This is shown in our documentation for each component.

**Comment by crftwrk** [comment]
@Geuchmann oops, my bad. This plugin wasn't updated since Bootstrao 5.0 and I simply forgot about the different trigger. Added `.modal` class and works like  charm. Thank you for figuring this out so quickly.

**Comment by v1r0x** [comment]
Same for me. I think as a workaround I had to remove `.modal` class from my component to make it works in bs5. Adding `.modal` works fine. My bad.
Sorry about that!

**Comment by adb-sh** [comment]
thanks for the help. just updated from bootstrap 4 to 5 and didn't notice, that some variables got scoped in another way.
as you have to set the `.modal`-class, which also sets `display: none;` you'll have to overwrite it, when you're using a js framework. f/e/ like this:
```html
<div class="modal d-block">
  <div class="modal-dialog">...</div>
</div>
```
in Vue3 i'm doing smth like this for dynamic modals:
![image](https://user-images.githubusercontent.com/38115351/186705979-7de9c753-1487-4491-9015-2b561e8bde4f.png)
