### ISSUE TITLE
Set variable is undefined in browser

### ISSUE THREAD

**Issue by KBGeo** [twbs/bootstrap#36973]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I defined the variable $list-group-disabled-bg in my variables.scss but the background color doesn't appear in the browser and it states that the variable is undefined when I use the inspection tool
![screenshotUndefined](https://user-images.githubusercontent.com/108745424/184846739-c3ec959e-9aba-4090-9784-ad7c83d5790a.PNG)
.

### Reduced test cases

`$list-group-disabled-bg:  #eeeeee;`

is in the variables.scss other variables like overwriting $primary etc. work.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by Geuchmann** [comment]
Sounds like a local problem. Working fine on https://getbootstrap.com/docs/5.2/components/list-group/.

![2022-08-16 18_19_05-List group · Bootstrap v5 2](https://user-images.githubusercontent.com/39516415/184929319-ebbb27a7-1757-47e5-a87d-23406d5241d6.png)

**Comment by KBGeo** [comment]
@Geuchmann if my variable can't overwrite it then it should at least be the default, right? Do you have an idea why neither is set? I also tried removing my overwriting from the css but it is still undefined..

**Comment by Geuchmann** [comment]
Have you imported the `"~bootstrap/scss/list-group"` file? The declaration of the variable is made there.
Your customization file must look similar to https://getbootstrap.com/docs/5.2/customize/sass/#importing.

**Comment by KBGeo** [comment]
yes, i import this.
It does look similar to the example in the link. I compared it again..

**Comment by mdo** [comment]
Closing as it's fine in our docs and there's no reduced test case here.

**Comment by tungphan995** [comment]
Thank you for believing in me.
