### ISSUE TITLE
Modal doesn't respect responsive rule

### ISSUE THREAD

**Issue by dzpt** [twbs/bootstrap#36987]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I use grid system and it works fine without putting them in the modal.
I gotta scale whole window to see the responsive working

### Reduced test cases

Example code.
column won't fall inside modal, gotta scale the window to see the effect
https://codepen.io/tom29/pen/ExErxNJ

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

4.6

**Comment by mdo** [comment]
Every media query in Bootstrap is responsive to the viewport.
