### ISSUE TITLE
Activatable button

### ISSUE THREAD

**Issue by paulkorir** [twbs/bootstrap#36985]
### Discussed in https://github.com/twbs/bootstrap/discussions/36984

<div type='discussions-op-text'>

<sup>Originally posted by **paulkorir** August 18, 2022</sup>
Greetings,

I would like to propose an addition to the button groups that we could for now refer to as an **activatable button**. 

The idea of an activatable button is inspired by emergency buttons which have a protective cover like this:
https://www.securitysafetyproducts.co.uk/images/upload/products_image5-11545-d.jpg

The button is off by default but cannot be accidentally clicked until activated. I have made a rough example here:
https://stackblitz.com/edit/3tkzv2-8fjkd4?file=index.html

The advantages of working with an activatable button are:
- no need for confirmation modals, whose action can be anywhere on the page (violation of Fitt's law);
- safety: no fear of accidentally triggering whatever action is behind the button as it is off by default;

It may be improved by using a switch instead of a checkbox or simply a checkbox to activate.

I don't think I've seen this before but I'm happy to be proved wrong. 
</div>

**Comment by mdo** [comment]
Thanks, but we'll pass on this—sounds perfect for your own plugin or code depending on your project's setup :).
