### ISSUE TITLE
Cannot read properties of undefined (reading 'backdrop')

### ISSUE THREAD

**Issue by 5ulo** [twbs/bootstrap#36989]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I get an error in the console using WebPack & Bootstrap 5.2

```
bootstrap.esm.js:3318 Uncaught TypeError: Cannot read properties of undefined (reading 'backdrop')
    at Offcanvas._initializeBackDrop (bootstrap.esm.js:3318:1)
    at new Offcanvas (bootstrap.esm.js:3192:1)
    at HTMLDocument.<anonymous> (scroll-to-anchor.js:7:25)
```

first error says
`const isVisible = Boolean(this._config.backdrop);`
second one
`this._backdrop = this._initializeBackDrop();`
third one
`const bsOffcanvas = new Offcanvas('myOffcanvas');`

I tried to simulate it in Codepen but it is without any error. https://codepen.io/5ulo/pen/BarMQBg
Everything is the same.

### Reduced test cases

This is in my js
```
import { Offcanvas } from 'bootstrap';

document.addEventListener('DOMContentLoaded', function () {

    const myOffcanvas = document.getElementById('offcanvas');
    const bsOffcanvas = new Offcanvas('myOffcanvas');

});
```

Here's Codepen example but shows no errors
https://codepen.io/5ulo/pen/BarMQBg

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by GeoSot** [comment]
You have some mistakes in you javascript code

Change to this and you are fine

```js

import { Offcanvas } from 'bootstrap'
document.addEventListener('DOMContentLoaded', function () {
  const bsOffcanvas = new Offcanvas('#offcanvasNav');
});
```

**Comment by tanmayd-icpl** [comment]
have same problem and i check my javascript code also it's working fine.
anyone have other solution for this problem

**Comment by Swolie** [comment]
I have the same problem and I initialized via data attribute. 
Fixed by adding a bs-target attribute, even though close btn is inside the canvas. 

%button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "offcanvas", type: "button", "data-bs-target" => "#style-sidebar"}

**Comment by BenjaminBeck** [comment]
I have the same Problem.
Here is a minimal Example:
https://codepen.io/Benjamin654/pen/KKrERbd

If you use the navbar-toggle button (not the blue one) in breakpoint < sm -> js error
If you open the offscreennavbar with the blue button and try to close it with X -> js error

**Comment by ZuK94** [comment]
i had the same problem and as @Swolie  suggested, correct data-bs attributes fixed it

**Comment by papatechlabs** [comment]
Yep same problem here; attempting to cause bootstrap mobile menu to hide when you click a link on it and I also had to add both

`data-bs-toggle="offcanvas" data-bs-target="#offcanvas"`

to each a tag.

Thanks for the tip @Swolie you're a star
