### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Vaishak-1997** [twbs/bootstrap#36991]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Sir, I found an error in code written on Bootstrap 4 under Input Groups (Prepend & Append) which is used to show the text in front & back of the input.  What I found is that we will get the exact output, Even if we  are not calling  the mentioned code of prepend & append by just calling Span Class (1st) and Input Type (2nd), In the case of Prepend,
And Input Type 1st & Span Class  (2nd) in the case of Append. 
Here the basic coding rule  itself is not maintained/Not followed while developing this code for Input Group, As we are getting output without calling Prepend and Append Class. 
I am requesting the Bootstrap Officials to rectify this error in Bootstrap 4 as soon as possible.
Please find the attached Screen Shot Below....

_Thanks & Regards
Vaishak.P
![Screenshot (1)](https://user-images.githubusercontent.com/111595746/185679896-7a993b48-1e6c-49dd-ad05-5f442692ed05.png)
_

### Reduced test cases

Issue can be resolved by making correction in the code built for Input Groups.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

4

**Comment by mdo** [comment]
This is not a reduced test case and we're not really actively maintaining v4 unless it's a critical bug. Please provide a live example of the issue and we can consider it for our next patch release.

**Comment by Vaishak-1997** [comment]
> This is not a reduced test case and we're not really actively maintaining v4 unless it's a critical bug. Please provide a live example of the issue and we can consider it for our next patch release.

sir I am uploading a video demonstration the issue. please watch.




https://user-images.githubusercontent.com/111595746/185778909-568d3906-5d8f-4bb3-b553-9e4b4d625708.mp4

**Comment by mdo** [comment]
That's not a reduced test case, but I see the problem—your markup is incorrect. Check the docs again. https://getbootstrap.com/docs/4.6/components/input-group/
