### ISSUE TITLE
Tabindex Stopped Working in 5.2 for "Javascript Behavior" Example in Docs

### ISSUE THREAD

**Issue by queejie** [twbs/bootstrap#36992]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In 5.0.2, tabbing with the keyboard works fine in nav tabs.  In 5.2 it no longer works.  The proof is in the document page itself (https://getbootstrap.com/docs/5.2/components/navs-tabs/), under the "Javascript Behavior" example, which does not tab correctly.

### Reduced test cases

https://getbootstrap.com/docs/5.2/components/navs-tabs/
Go to Javascript Behavior example.  Try tabbing between nav tabs with the keyboard.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by julien-deramond** [comment]
With the [tab JavaScript plugin in v5.2.0](https://getbootstrap.com/docs/5.2/components/navs-tabs/#javascript-behavior), tab key allows you to focus the content and left/right keys to focus the tabs.

@GeoSot Maybe we could enhance the docs to explain this behavior and mention it in the migration guide?

**Comment by queejie** [comment]
Thank you.  I'm not a WCAG expert.  Was this done to be more in keeping with WCAG compliance?  It seems a little  counterintuitive to me, although I can see the benefit.

**Comment by patrickhlauke** [comment]
the behavior is described in the second para here https://getbootstrap.com/docs/5.2/components/navs-tabs/#accessibility ... but perhaps it's a bit buried

**Comment by queejie** [comment]
@patrickhlauke Thank you.  Sounds like it was done with WCAG in mind.
