### ISSUE TITLE
docs 5.1.3 page says 5.1.3 is the latest version with no ability to go to 5.2

### ISSUE THREAD

**Issue by VividLemon** [twbs/bootstrap#36990]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Version 5.1 says 5.1 is latest https://getbootstrap.com/docs/5.1/getting-started/introduction/
![image](https://user-images.githubusercontent.com/31498096/185661404-ce695092-eb21-4271-866c-65e6a1e8c75d.png)

The only way to view that 5.2 is out is clicking on all versions https://getbootstrap.com/docs/versions/
![image](https://user-images.githubusercontent.com/31498096/185661478-e80aa7b0-3cf3-40bb-9983-2847668c33ac.png)

By clicking on all versions, it actually sends you to a v5.2 page, so it has the correct dropdown
![image](https://user-images.githubusercontent.com/31498096/185661644-7f489a36-76c4-47f9-b6a1-fc3b84a01f98.png)

An updated dropdown would be nice.

### Reduced test cases

Not applicable

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1 -- not applicable

**Comment by mdo** [comment]
Nearly every version is like this unfortunately. We haven't gone back to manually edit our previous docs to update the release dropdown. You're welcome to open a PR to help with that, as it's really low on our priority list.

**Comment by VividLemon** [comment]
> Nearly every version is like this unfortunately. We haven't gone back to manually edit our previous docs to update the release dropdown. You're welcome to open a PR to help with that, as it's really low on our priority list.

Where do you keep the 5.1 docs repo at?

**Comment by mdo** [comment]
All hosted docs are in this repo in the `gh-pages` branch.
