### ISSUE TITLE
$card-box-shadow this variable does not work.

### ISSUE THREAD

**Issue by maikycourse** [twbs/bootstrap#37001]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**$card-box-shadow**
this variable does not work because it is not being used

### Reduced test cases

Neither the scss variable nor the css variable is used

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

bootstrap@5.2.0

**Comment by julien-deramond** [comment]
`$card-box-shadow` is used here:
https://github.com/twbs/bootstrap/blob/c3c65911665ab64bdaa15d405db65ee81655dbf3/scss/_card.scss#L13

`--#{$prefix}card-box-shadow` is used here:
https://github.com/twbs/bootstrap/blob/c3c65911665ab64bdaa15d405db65ee81655dbf3/scss/_card.scss#L36

If you change `$card-box-shadow` to `10px 5px 5px #fd0 !default` and `$enable-shadows` to `true`, you'll see a yellow shadow on cards.
