### ISSUE TITLE
Dropdowns in Input groups are not showing correct drop down menu

### ISSUE THREAD

**Issue by shivam091** [twbs/bootstrap#37015]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hey.
I am having one input group in one dropdown on left and other on right side. Upto Bootstrap 5 both of these drop downs were showing me correct menu after clicking on the dropdown button.
but when I have upgraded to bootstrap 5.2, It's showing me left side menu for both left and right dropdowns.

For reproducing this issue, please check 3rd example of below website
https://getbootstrap.com/docs/5.2/forms/input-group/#buttons-with-dropdowns

Here documentation itself not showing correct menu.

Thanks

### Reduced test cases

No Test

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2

**Comment by louismaximepiton** [comment]
Duplicate of #36803 ?

**Comment by julien-deramond** [comment]
Duplicate of #36803

**Comment by embellishmentround-trip** [comment]
@louismaximepiton https://lyrical-brunch.github.io/fSypWaohhWVBKAMZKXFNONBttO9NHCK9QYiZN2Ew4/
