### ISSUE TITLE
Not able to change font size of accordion 

### ISSUE THREAD

**Issue by prakharisg** [twbs/bootstrap#37024]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

not able to change the font size of accordion

### Reduced test cases

.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What version of Bootstrap are you using?

5.2

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @prakharisg. Could you please add more details and context to your request?

**Comment by prakharisg** [comment]
Hi Julien-deramound,
I am not able to change the font size of accordion via variables because its not present.
currently i am using fs-* like (fs-1,fs-2) class for achieving it

Please check given doc content


$accordion-padding-y:                     1rem;
$accordion-padding-x:                     1.25rem;
$accordion-color:                         var(--#{$prefix}body-color);
$accordion-bg:                            $body-bg;
$accordion-border-width:                  $border-width;
$accordion-border-color:                  var(--#{$prefix}border-color);
$accordion-border-radius:                 $border-radius;
$accordion-inner-border-radius:           subtract($accordion-border-radius, $accordion-border-width);

$accordion-body-padding-y:                $accordion-padding-y;
$accordion-body-padding-x:                $accordion-padding-x;

$accordion-button-padding-y:              $accordion-padding-y;
$accordion-button-padding-x:              $accordion-padding-x;
$accordion-button-color:                  $accordion-color;
$accordion-button-bg:                     var(--#{$prefix}accordion-bg);
$accordion-transition:                    $btn-transition, border-radius .15s ease;
$accordion-button-active-bg:              tint-color($component-active-bg, 90%);
$accordion-button-active-color:           shade-color($primary, 10%);

$accordion-button-focus-border-color:     $input-focus-border-color;
$accordion-button-focus-box-shadow:       $btn-focus-box-shadow;

$accordion-icon-width:                    1.25rem;
$accordion-icon-color:                    $accordion-button-color;
$accordion-icon-active-color:             $accordion-button-active-color;
$accordion-icon-transition:               transform .2s ease-in-out;
$accordion-icon-transform:                rotate(-180deg);

**Comment by mdo** [comment]
This isn't a live example showing a bug. Please read and complete the template when opening an issue. Until we see a live demo of the problem, we can't help.

**Comment by prakharisg** [comment]
Hi @mdo 
https://instyle-direct-next-js.vercel.app/gold-furniture-pack

please check live url
