### ISSUE TITLE
Border Radius Incorrectly Applying to Vertical Buttons Groups

### ISSUE THREAD

**Issue by SeenIsHere** [twbs/bootstrap#37030]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Top-Right corner of the top button and Bottom-Left corner of the bottom button being overridden to 0 border radius. This only happens when the `btn-group-vertical` class is applied to the `btn-group` div.

### Reduced test cases

https://codepen.io/seenishere/pen/wvmbpGJ?editors=1010 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by nkdas91** [comment]
Hi @SeenIsHere 

As per docs, you don't need both ```.btn-group``` and ```.btn-group-vertical``` classes. Just remove the ```.btn-group``` class and it should work fine.

https://getbootstrap.com/docs/5.2/components/button-group/#vertical-variation

This
```html
<div class="btn-group btn-group-vertical" role="group">
```

Should be
```html
<div class="btn-group-vertical" role="group">
```
