### ISSUE TITLE
Broken codeblock at _root.scss -> ln: 20 

### ISSUE THREAD

**Issue by devhiko** [twbs/bootstrap#37037]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

// @each $color, $value in $theme-colors-rgb {
  //   --#{$prefix}#{$color}-rgb: #{$value};
  // }

There is no colormap for theme-colors-rgb and when imported _root at other custom file is not working.

### Reduced test cases

// @each $color, $value in $theme-colors-rgb {
  //   --#{$prefix}#{$color}-rgb: #{$value};
  // }

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.0

**Comment by mdo** [comment]
You're likely missing the new maps stylesheet. Double check our release notes, migration guide, or blog post.

**Comment by mdo** [comment]
Also please don't open a discussion and issue for the same problem. Choose one and if it's wrong, we can convert it.

**Comment by devhiko** [comment]
Sorry my failure for opening both, but i did not sure about it is a bug or discussion topic for giving info yu know, but thanks for enlightening for it. Actually i did not notice that **_maps.scss** file and not thought there was. It gave me an error about that when i import and i reached here because. I am newly exploring github and environments like discussion, issues like so. :) **And there was a line about $theme-colors-rgb at _root maybe it stemmed from this,** maybe you will fix this at a minor bug fix ;)

Here is line at _root : 

 ```
// @each $color, $value in $theme-colors-rgb {
  //   --#{$prefix}#{$color}-rgb: #{$value};
  // } 
when i comment out this like so, it works proper i say otherwise throws error.
```
and _variables : there is no line about $theme-colors map..
and so, when i tried this at **https://getbootstrap.com/docs/5.2/customize/sass/#variable-defaults**

```// Required
@import "../node_modules/bootstrap/scss/functions";

// Default variable overrides
$body-bg: #000;
$body-color: #111;

// Required
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/maps";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/root";

// Optional Bootstrap components here
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
// etc
```
root is throwing error :( and i can not customize bootstrap in my way. Maybe you can advice any way to work with it.

And so, thanks for all help. Have a nice day !
