### ISSUE TITLE
Auto-generate columns

### ISSUE THREAD

**Issue by doanhquang2005** [twbs/bootstrap#37043]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I have an idea like this: If we set the value for the div tag = 400px:
+ If the parent element has a width of 900px, the row will have 2 div tags with a width of 450px
+ If the parent element has a width of 1200px, the row will have 3 div tags with a width of 400px
+ If the parent element has a width of 700px, the row will have 1 div tag with a width of 700px
Is there a way to write css or use bootstrap to solve the above problem?

### Motivation and context

Responsive flexibly

**Comment by mdo** [comment]
You can accomplish things like this with the current grid system with our auto columns.
