### ISSUE TITLE
Bootstrap Nuget package latest version still at 5.2.0-beta1

### ISSUE THREAD

**Issue by jason1208419** [twbs/bootstrap#37050]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap Nuget package latest version still at 5.2.0-beta1 for prerelease and 5.1.3 for stable.

Could you please update the Nuget package?

### Motivation and context

I'm using Nuget package and can't get the latest stable version 5.2.0

**Comment by supergibbs** [comment]
Done! Sorry for the delay
