### ISSUE TITLE
Bootstrap 5.2.0 - Dropdown Methods are not working.

### ISSUE THREAD

**Issue by Yusufzai** [twbs/bootstrap#37055]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Dropdown Methods are not working when the "data-bs-toggle" is attached to the button element.

### Reduced test cases

Kindly check the jsFiddle links mentioned below.

1- with " data-bs-toggle " attribute.

Fiddle -> https://jsfiddle.net/0c59kpbr/

Explanation -> This first example have "data-bs-toggle" attribute on the dropdown button.

2- without " data-bs-toggle " attribute.

Fiddle -> https://jsfiddle.net/ascq8Le0/

Explanation -> This second example does not have "data-bs-toggle" attribute on the dropdown button.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.2.0 stable

**Comment by Yusufzai** [comment]
@jonnysp  it's not working as expected 

When you will destroy the dropdown it will no longer accessible through the buttons but the dropdown will still work when you click directly to the dropdown button

So your solution does not work.

But thank you for your suggestion

**Comment by GeoSot** [comment]
I don't have the time to check if this behavior is changed on 5.2, or it was like this ...

However, your **solution**

```js

document.addEventListener("DOMContentLoaded", function(){
    var showBtn = document.getElementById("showBtn");
    var hideBtn = document.getElementById("hideBtn");
    var toggleBtn = document.getElementById("toggleBtn");
    var updateBtn = document.getElementById("updateBtn");
    var disposeBtn = document.getElementById("disposeBtn");
    
    // Create a dropdown instance
    var myDropdown = () =>bootstrap.Dropdown.getOrCreateInstance("#myDropdown");
    
    showBtn.addEventListener("click", function(){
        myDropdown().show();
    });
    
    hideBtn.addEventListener("click", function(){
        myDropdown().hide();
    });
    
    toggleBtn.addEventListener("click", function(){
        myDropdown().toggle();
    });
        
    updateBtn.addEventListener("click", function(){
        myDropdown.update();
    });
    
    disposeBtn.addEventListener("click", function(){
        myDropdown().dispose();
    });
});

```

> When you will destroy the dropdown it will no longer be accessible through the buttons but the dropdown will still work when you click directly to the dropdown button

**explanation:** because you have cached the instance and when you destroy it, you keep referring to the old instance



Thank you @jonnysp, you gave me a quick hint here

**Comment by Yusufzai** [comment]
@GeoSot  You solution is also destroying the instance! 

Is there any solution to destroy the original as it has no effect

**Comment by GeoSot** [comment]
As you use `dispose` it will destroy the instance for sure

**Comment by Yusufzai** [comment]
@GeoSot  Ok can you tell me one thing 

How can I convert bs dropdown into bs collapsible ( according )

As my main goal is the convert the dropdown into collapsible when button is clicked

**Comment by GeoSot** [comment]
You can ask this question on [discussions](https://github.com/twbs/bootstrap/discussions), as it is not an issue. 

The main thing you have to do is to change the proper classes
