### ISSUE TITLE
Tooltips show in wrong position when hovered from above on Safari

### ISSUE THREAD

**Issue by nwalters512** [twbs/bootstrap#37068]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm adding a tooltip to an icon. On macOS Safari, when the icon is hovered by starting the mouse below the icon and moving up towards it, it shows correctly:

<img width="369" alt="Screen Shot 2022-09-01 at 15 03 16" src="https://user-images.githubusercontent.com/1476544/188020843-50aaff93-84fd-4e0c-98bd-5dc9e9ffccfc.png">

However, when the mouse starts above the icon and moved down toward it, it shows in the wrong place:

<img width="383" alt="Screen Shot 2022-09-01 at 14 58 48" src="https://user-images.githubusercontent.com/1476544/188020852-1ad5a635-7408-4cff-aff6-125bfe06aec7.png">

Here's a video illustrating the issue:

https://user-images.githubusercontent.com/1476544/188021232-15dcf3ab-a46f-4870-8846-79b795a246a5.mov

I cannot reproduce this bug in Chrome or Firefox.

### Reduced test cases

Here's a JSFiddle illustrating the problem: https://jsfiddle.net/nwalters512/Lns1b9kj/4/.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v5.2.0

**Comment by nalakapws** [comment]
Tooltips and popovers in Bootstrap are a nightmare.

**Comment by easypronunciation** [comment]
A related bug in Chrome on MacOS.
If I carefully hover to the tooltip from above, it doesn't show up at all on the **first** hover.
By "carefully" I mean the cursor should be exactly above the tooltip and the movement should start from considerable distance.
Bootstrap 5.2.1

**Comment by GeoSot** [comment]
**/cc** @atomiks can you help on this please? I cannot replicate it with linux or win11

**Comment by florianlacreuse** [comment]
I can reproduce the issue randomly with Fedora + Chrome.

**Comment by julien-deramond** [comment]
Reproduced on macOS with Safari, Firefox and Chrome. However it is less frequent with Firefox.
To reproduce, I simply move very fast the cursor outside and on the warning icon.

Information that might be useful.

When the tooltip is well displayed:
<img width="773" alt="Screenshot 2022-10-01 at 00 19 37" src="https://user-images.githubusercontent.com/17381666/193364102-851c6d9c-b541-44f7-87cf-b91846c37da8.png">

When the tooltip is not well displayed, there's no `style`.
<img width="765" alt="Screenshot 2022-10-01 at 00 19 28" src="https://user-images.githubusercontent.com/17381666/193364104-9b9c6abb-b1d6-4b6e-be76-6bc5980c6f94.png">

**Comment by GeoSot** [comment]
Guys, I would like your feedback using the following script 
https://deploy-preview-37235--twbs-bootstrap.netlify.app/docs/5.2/dist/js/bootstrap.bundle.min.js


or experimenting on this page
https://deploy-preview-37235--twbs-bootstrap.netlify.app/docs/5.2/components/tooltips/#custom-tooltips

**Comment by florianlacreuse** [comment]
On my side, I can no longer reproduce the issue on the preview page.

**Comment by julien-deramond** [comment]
@GeoSot Can no longer reproduce the issue by replacing `bootstrap.bundle.min.js` in https://jsfiddle.net/nwalters512/Lns1b9kj/4/ by your version. Patch seems to work well :)

**Comment by GeoSot** [comment]
Wonderful news guys and many thanks for your help 😄 
#37235 will close this issue

**Comment by TechOverflow** [comment]
I am still experiencing this, BS 5.2.2, Safari latest. Thought I was going crazy or had a mistake in my elements.
I believe the problem only happens when placement is "top" (or default) and when the mouse move _from_ the top.
In my case coming from the body of the card to the icon in the footer.
https://jsfiddle.net/pru7gv1y/

<img width="631" alt="test" src="https://user-images.githubusercontent.com/40919041/201910030-193ab817-ef03-4363-9772-13c227a9772b.png">
