### ISSUE TITLE
Convert link colors to rgb

### ISSUE THREAD

**Issue by Sir-Genius** [twbs/bootstrap#37081]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

```
a {
  color: rgba(var(--bs-link-color), var(--bs-link-opacity));
}

a:hover {
  color: rgba(var(--bs-link-hover-color), var(--bs-link-hover-opacity));
}
```

### Motivation and context

It will help with link styling. Also we will be able to do something like this:
```
a {
  text-decoration: var(--bs-link-line, underline) var(--bs-link-style, initial) rgba(var(--bs-link-color), var(--bs-link-line-opacity, 1));
  // and for the hover state
}

@each $style in (solid dashed dotted) {
  .link-#{$style},
  .link-#{$style}-hover:hover {
    --bs-link-style: #{$style};
  }
}
```

**Comment by mdo** [comment]
This would be a great candidate for v5.3.0—adding to that for now!

**Comment by barrett28** [comment]
For hovering : 
when hovering over the link the color will be changing
a:hover {
  color: black; background-color: transparent; text-decoration: underline;

**Comment by Ruchita-01** [comment]
Solution: Converting link colors to RGB
`a:link {
  color: green;
  background-color: transparent;
  text-decoration: none;
}
a:visited {
  color: blue;
  background-color: transparent;
  text-decoration: none;
}
a:hover {
  color: red;
  background-color: transparent;
  text-decoration: underline;
}
a:active {
  color: grey;
  background-color: transparent;
  text-decoration: underline;
}`
Description:
An unclicked link will be green and ununderlined in this instance. 
Links that have been visited will be blue and not underlined. 
A link that is active will be highlighted in grey. 
In addition, a link will turn red and be highlighted when you mouse over it (a:hover).

**Comment by Gayatri-Shahane** [comment]
Can I work on this??

**Comment by barrett28** [comment]
We selected this one for my mini project

**Comment by bharat-ahead** [comment]
Good

**Comment by Jyotiraditya24** [comment]
hey, could I work on this issue?
