### ISSUE TITLE
modal and offCanvas don't work when CSS backdrop-filter is used

### ISSUE THREAD

**Issue by mef** [twbs/bootstrap#37085]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Whenever a `.container` has a CSS rule containing `backdrop-filter`, then the modals and offCanvas do not behave as expected.

#### Steps to reproduce

1. Put an off-canvas and/or a modal inside a `.container` (with trigger button(s)),
2. Define a `backdrop-filter` CSS rule on the `.container` class,
3. Visit the page in a window wider than the `.sm` breakpoint so that some spacing is available at the left and right of the `.container`.

#### Observed situation

With off-canvas:

* The off-canvas panel slides from the edge of the _container_
* The off-canvas backdrop does not cover the area outside of the container

With modal:

* the modal's backdrop is shown _over_ of the modal
* It is not possible to close the modal or to interact with its content

#### Expected situation

With off-canvas:

* The off-canvas panel slides from the edge of the window
* The off-canvas backdrop cover the area outside of the container

With modal:

* the modal's backdrop is shown below of the modal
* It is possible to close the modal and to interact with its content

The same issue happens whenever the container has a  `filter` CSS rule.

#### Workaround

A workaround this issue is to place the offcanvas and/or modal divs outside of the container, directly nested below `body`. This is not so convenient when programming with frameworks structured around components.

### Reduced test cases

[This codepen](https://codepen.io/mef1/pen/gOzpMeW) illustrates the described problems.

It should be viewed in a window wider than the `.sm` breakpoint so that some spacing is available at the left and right of the `.container`.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2

Edit: formatting and precised which rule causes the problem.

**Comment by asyncdesign** [comment]
The backdrop-filter style seems to be creating a new stacking context for the container and the element with the class ".modal-backdrop" comes after it in the root stacking context. You could remove the positioning on the modal backdrop, place it before the container, or put the modal dialog outside the container. There are various ways to address it.

**Comment by sfxyz** [comment]
I have face the same problem, I have a navbar styled using `backdrop-filter` property,  with menu items on offcanvas below the large view-port, when mobile menu button clicked offcanvas won't show properly , the visible part only the top part of it. Browser inspect show offcanvas has height dimension same as it's container (`.navbar`). Then I try made a modification to define offcanvas height: 

```
  .offcanvas-lg {
    background-color: var(--s-primary);
    border-left: 0;

    @include media-breakpoint-down(lg) {
      box-shadow: $box-shadow-lg;
    }
  }
```

Modification:

```
    @include media-breakpoint-down(lg) {
      box-shadow: $box-shadow-lg;
      height: 100vh;
    }
```
all part Offcanvas now visible on mobile view. The problem was look like on how the dimension of offcancas defined, I am not sure. But the modification that I've tried work. 
Note: the modification seem make _hidden_ extra space since horizontal scrolls appears.

**Comment by mdo** [comment]
@asyncdesign is correct, and there's not really a great way to work around this. One solution I found, which is applied in #35857, is to use a pseudo-element for the backdrop blur.

**Comment by ereator** [comment]
I also have the same problem. Please fix.
