### ISSUE TITLE
Remove padding from col-x on mobile with a class

### ISSUE THREAD

**Issue by CedricBeausseron** [twbs/bootstrap#37094]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

You can remove padding on larger screens by using for example px-lg-0 but it seems that you can't get the same result with smaller screen.

I tryed px-0 px-lg-1, px-0 px-lg-2 or px-0 px-lg-3 but none of them have the same padding as the original column padding.

Here is an example I posted on [Stackoverflow](https://stackoverflow.com/questions/72740694/is-there-a-way-to-remove-padding-x-from-bootstrap-column-on-mobile-without-custo).

### Motivation and context

Because Bootstrap gives the possibility of managing styles from classes, I was wondering if I could remove the column padding on mobile only with bootstrap classes.

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.2/layout/gutters/#no-gutters
