### ISSUE TITLE
Tooltips doesn't hide properly

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [twbs/bootstrap#37097]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If you don't remove the element with the DOM, the tooltip is properly hidden. But if you remove the element or clear the HTML of the parent if it is a child element, it stays stuck on the page. 

Probably this could be considered expected behavior since the item has already been removed, but I think this should be handle on the bootstrap library.

![tooltip](https://user-images.githubusercontent.com/55924924/188839138-9f1f658f-abf2-41b7-8bc0-7ae285c6fab8.gif)

### Reduced test cases

https://codepen.io/g-u-r-k-a-n/pen/WNJQdyL

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Firefox, Opera

### What version of Bootstrap are you using?

v5.2

**Comment by g-u-r-k-a-n** [comment]
Yes, I really back to over 1 million commits. :zany_face:  Hello to maniac people like me!

**Comment by mdo** [comment]
This is addressed in the overview section: https://getbootstrap.com/docs/5.2/components/tooltips/#overview
