### ISSUE TITLE
`.dropdown-header` not affected by HTML headings tags.

### ISSUE THREAD

**Issue by GKHN1925** [twbs/bootstrap#37100]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

.dropdown-header was not affected by HTML headings tags.

Thanks.

### Reduced test cases

https://codepen.io/GKHN1925/pen/gOzadrx

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4, v5

**Comment by julien-deramond** [comment]
I suppose that doesn't change the rendering but in your example you open `<h1>` and `<h6>` but close them with a `</h5>`:
```html
<h1 class="dropdown-header">Dropdown header 1</h5>
<h6 class="dropdown-header">Dropdown header 2</h5>
```

**Comment by GKHN1925** [comment]
The link has been updated.

**Comment by mdo** [comment]
Indeed, this is by design. Omit the class if you need different styling.
