### ISSUE TITLE
Homepage broken https://getbootstrap.com

### ISSUE THREAD

**Issue by LocalHeroPro** [twbs/bootstrap#37101]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![image](https://user-images.githubusercontent.com/42643563/188920697-c4958722-fa7c-4cd9-ad8c-09ee4aa36783.png)

### Reduced test cases

https://getbootstrap.com

### What operating system(s) are you seeing the problem on?

Android, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Opera

### What version of Bootstrap are you using?

5.2.1

**Comment by MisatoTremor** [comment]
I get this error in the console:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css' with computed SHA-384 integrity 'gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx'. The resource has been blocked.
```
And similarly for `bootstrap.bundle.min.js`

**Comment by XhmikosR** [comment]
Works fine here, try ctrl+F5 or command+R.

**Comment by MisatoTremor** [comment]
Tried that yesterday to no avail. But it seems to be fixed now. Probably a Cloudflare hiccup
