### ISSUE TITLE
5.2.1 broke .btn:focus box-shadow behaviour

### ISSUE THREAD

**Issue by oakleaf** [twbs/bootstrap#37106]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Upgraded from 5.2.0 and quickly noticed that the box-shadow disappeared from all my buttons when :focus(ing).

The options (https://getbootstrap.com/docs/5.2/customize/options/) clearly states;
`$enable-shadows | true or false (default) | Enables predefined decorative box-shadow styles on various components. Does not affect box-shadows used for focus states.`

Could this be the issue?
https://github.com/twbs/bootstrap/blob/main/scss/_buttons.scss

#21, the "--#{$prefix}btn-focus-shadow-rgb" variable doesnt seem to exist

### Reduced test cases

https://github.com/twbs/bootstrap/blob/main/scss/_buttons.scss

#21, add default value to 
--#{$prefix}btn-focus-shadow-rgb

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.1

**Comment by julien-deramond** [comment]
Isn't your issue linked to the following modification https://github.com/twbs/bootstrap/pull/37026?

> for all `.btn`s, it changes the `:focus` styling to `:focus-visible` - this way, the focus style doesn't take effect and "stick" (until you click somewhere else) for mouse/touch users

When you're talking about ":focus(ing)`, is it focusing with the mouse or the keyboard (or both)?

**Comment by oakleaf** [comment]
Okey, sorry - was not aware that the :focus was removed. Are there any solution to bring it back? We love the focus-shadows.

**Comment by julien-deramond** [comment]
I'm closing it since the issue seems to be resolved.

> Are there any solution to bring it back? We love the focus-shadows.

You'll have to create your own `:focus` rules to override the behavior offered by our rules linked to `:focus-visible`. Here is the corresponding diff: https://github.com/twbs/bootstrap/pull/37026/files.

**Comment by daftspunk** [comment]
> You'll have to create your own :focus rules to override the behavior offered by our rules

Super simple for restoring this here:

```
.btn:focus {
    box-shadow: 0 0 0 0.25rem rgb(97 109 133 / 50%);
}
```
