### ISSUE TITLE
Buttons bug

### ISSUE THREAD

**Issue by govorov-top** [twbs/bootstrap#37115]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

> **Buttons**
> Added a transparent default hover border color CSS variable for buttons to fix a visual regression

Update 5.2.1 came out. In our projects after the transition to this version, all the buttons are broken.
I think that the promblem is in the component  `@import "bootstrap/scss/buttons";`

In version 5.2.0 it was like this:

![Screenshot_1](https://user-images.githubusercontent.com/36326923/189341637-8cc9f956-06be-4f1f-8507-e421527dfa02.png)

In version 5.2.1 it is like this:

![Screenshot_2](https://user-images.githubusercontent.com/36326923/189341890-ef27dd36-53b6-40c2-9335-cbec6a13237e.png)

Which overrides all styles and breaks the layout and logic.
![Screenshot_3](https://user-images.githubusercontent.com/36326923/189342054-af729eba-f92c-47b9-aea4-d162e218c108.png)

### Reduced test cases

Exemple: [https://codepen.io/rgameshow/pen/zYjqoRK](https://codepen.io/rgameshow/pen/zYjqoRK)

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.2.1

**Comment by space900** [comment]
The same problem

**Comment by lucifer694u** [comment]
hey guys i am new here can you tell me what is this issue

**Comment by lildeadprince** [comment]
Not sure how what stands for a "breaking change" in CSS community, but from my point of view changing the specificity of a selector to a more specific one is maybe not a "major", but indeed is _breaking_. 
(And looking into issues tab, that's probably not the only one example in 5.2.1)

Of course we always take SemVer with a grain of salt in web development, but I wouldn't expect such changes in _patch (\*.\*.X)_ release.
I'd say such changes must be released only under a _feature (*.X.0)_ version bump.

**Comment by patrickhlauke** [comment]
> from my point of view changing the specificity of a selector to a more specific one is maybe not a "major", but indeed is breaking

in hindsight, sure. we just didn't catch the implications for people who then customise things on top in that particular way. we're only human, so no need for a big discussion on SemVer ;)
