### ISSUE TITLE
Since 5.2.1 modals closes on content removal

### ISSUE THREAD

**Issue by jbroutier** [twbs/bootstrap#37126]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Since version 5.2.1, when a button in the modal body triggers the removal of the button itself or its parent, the modal closes. It worked correctly with version 5.2.0.

**Edit:**

Definitely related to #36863, reverting it fixes the issue.

### Reduced test cases

For both test cases, click on the "Open modal" button then click on any "Remove row" button.

- With Bootstrap 5.2.0: https://codepen.io/jbroutier/pen/JjvKzqZ
- With Bootstrap 5.2.1: https://codepen.io/jbroutier/pen/dyeXrLQ

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.2.1

**Comment by joelstein** [comment]
Bootstrap 5.2.1's modal change introduced in #36863 is causing problems for me, too, as described in this issue.

In modals, I have buttons and dropdowns hidden after a click. With Bootstrap 5.2.1, the modal dismisses after clicking these things, which is naturally surprising to our users.

The fix in #37128 resolves the issue for us.

**Comment by joelstein** [comment]
Thanks for fixing and merging this!

**Comment by neoteknic** [comment]
release a 5.2.2 ? Or remove 5.2.1 because it broke many projets with modal boxes. Force 5.2.0 in package.json to fix
