### ISSUE TITLE
Add support for font-feature-settings CSS property

### ISSUE THREAD

**Issue by aa1874** [twbs/bootstrap#37124]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

There should be support for the `font-feature-settings` CSS property in Bootstrap so that stylistic sets can be implemented with ease

### Motivation and context

I already tried to implement `font-feature-settings` with a customized Bootstrap implementation to no avail, while I want to use a stylistic set of a certain font

**Comment by mdo** [comment]
Given our usage of system fonts out of the box, and that this can be accomplished with the utility API I think, I'm closing as a won't fix.
