### ISSUE TITLE
Toast z-index css variable not used

### ISSUE THREAD

**Issue by manuelhenke** [twbs/bootstrap#37136]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The variable for the z-index of a toast gets defined here in `.toast`:
https://github.com/twbs/bootstrap/blob/6e55fa929797a2d1d5250e1630615f515c45d0db/scss/_toasts.scss#L3

And it gets later used in `.toast-container`:
https://github.com/twbs/bootstrap/blob/6e55fa929797a2d1d5250e1630615f515c45d0db/scss/_toasts.scss#L42

However, the documentation says that a `.toast-container` wraps the `.toast` element. Due to that the variable defined in `.toast` will never be available inside `.toast-container`:
- https://getbootstrap.com/docs/5.2/components/toasts/#stacking
- https://getbootstrap.com/docs/5.2/components/toasts/#placement

### Reduced test cases

https://codepen.io/manuelhenke/pen/ExLgRvq

### What operating system(s) are you seeing the problem on?

macOS, iOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

v5.2.1

**Comment by julien-deramond** [comment]
Thanks for opening this issue @manuelhenke.
This might be tackled by #37118. @flavio-b do you confirm?
If so you can add "Fixes #37136" in the description to link the PR to this issue.

**Comment by flavio-b** [comment]
@julien-deramond, yes I've added the issue code to the PR now.
