### ISSUE TITLE
update Jquery v3.5.1 to v3.6.1 for Bootstrap 4.6.2

### ISSUE THREAD

**Issue by forghan89** [twbs/bootstrap#37131]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello
Please update Jquery v3.5.1 to v3.6.1 for Bootstrap 4.6.2

https://github.com/jquery/jquery/releases/tag/3.6.1

### Motivation and context

https://blog.jquery.com/2022/08/26/jquery-3-6-1-maintenance-release/

**Comment by julien-deramond** [comment]
The end of life of the v4 is planned for the January 1, 2023. Unless there are major issues in the v4 until then, we don't plan to release another v4.
