### ISSUE TITLE
BS5 - Disabled buttons prevent setting cursor like 'not-allowed'

### ISSUE THREAD

**Issue by morrow95** [twbs/bootstrap#37154]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Finally getting around to changing one of my bigger sites over to BS5.  BS5 sets the following for disabled buttons : 

```
.btn:disabled, .btn.disabled, fieldset:disabled .btn {
  color: #fff;
  pointer-events: none;
  background-color: var(--bs-btn-disabled-bg);
  border-color: var(--bs-btn-disabled-border-color);
  opacity: var(--bs-btn-disabled-opacity);
```

While `pointer-events: none;` prevents visual actions on the button like hover it also prevents setting a different cursor such as : 

```
cursor: not-allowed;
```
which I was personally doing for added visual context to users that this button is disabled when they mouse over it.

I get the reasoning behind the change, but at the same time I am thinking of user experience.  A visitor comes to your website, that they are not familiar with, and a disabled button shows a lighter opacity (which they might not even realize) and has no function (no click, no color change on hover, etc).  Is everyone going to realize this button is disabled this way?  This is why I always set custom css to show `pointer-events: none;` on my disabled buttons.  Now, the visitor sees a red 'x' cursor when they mouse over the button and it is very clear to them that this button is disabled.

Not saying BS4 or BS5 way is better or worse and I'm sure people will have differing opinions on this, but for me personally it was nice setting the 'not-allowed' cursor on my disabled buttons so it was clear to my visitors what was happening.

### Motivation and context

See above.

**Comment by patrickhlauke** [comment]
surely if you're manually setting `cursor: not-allowed` in your styles, you can then also set `pointer-events: auto` in your custom styles?

**Comment by morpolspc** [comment]
@patrickhlauke Which would also remove the new button functionality that prevents any visual button changes on hover/focus/etc for disabled buttons.

**Comment by morrow95** [comment]
@patrickhlauke Which would also bring back the disabled button changing visually on hover/focus/etc.  This is one of the side effects of using pointer-events with them in BS5 compared to BS4.

**Comment by mdo** [comment]
Yes, it's a bit of a trade-off, but one we felt was worth it. We won't be changing that at this point in v5 because it'd be a major and breaking change, so you might need to modify things further for your specific use case. We'll keep it in mind for v6 as well.

**Comment by xploSEoF** [comment]
I'm sorry, but what is gained from disabling all pointer events on a disabled button? As far as I can see, no click events fire on a disabled button, so you've chosen to prevent accessibility things like tooltips for no gain?

Disabled buttons should not have pointer events disabled.

I'm fairly sure the same could be said for many other things like inputs as this adds a lot of bloat, disables accessibility across the board, and doesn't actually provide any benefit when using inputs and buttons. Perhaps a lot of `:not(input,button,select)` to make sure you don't disable pointer events where there's no need?

**Comment by patrickhlauke** [comment]
>  you've chosen to prevent accessibility things like tooltips for no gain?

how would you trigger a tooltip on a disabled button using the keyboard? disabled buttons can't be focused with the keyboard... the only way then would be to "fake disable" the button to keep it effectively active, cram in `aria-disabled="true"`, and rely on the author preventing regular click action...
