### ISSUE TITLE
All css --bs-XX moved to :root

### ISSUE THREAD

**Issue by NielsHolt** [twbs/bootstrap#37161]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi

Declare all `--bs- ` in `:root` to allow reuse in other domains/classes

### Motivation and context

At the moment the css-var regarding eq. modal are in `.modal {...}` witch makes it impossible to reuse in other cases. 
Since the vars are already named `--bs-DOMAIN-XX` (eq. `--bs-modal-font-size`)  there would be no conflict with other vars.

**Comment by mdo** [comment]
This would be a breaking change now in v5, so it'd be a consideration for v6. However, I don't think it's wise to have ALL variables at the root level—that's some serious noise level. Our root variables are instead focused on shared global styles. Wouldn't mind more thoughts from @twbs/css-review though as we continue to work on v5.

**Comment by NielsHolt** [comment]
Hi
Thanks :-)
Just a comment - I do not follow you on the note that it need a new major version. All the css-vars are named `bs-DOMAIN-xx` so `root: { --bs-btn-font-size: 1rem; }` would not break anything from `.btn { --bs-btn-font-size: 1rem; }`

**Comment by mkleehammer** [comment]
One use case (which I'm dealing with) for everything being in root is when trying to implement new components that you want to look like existing ones.  For example, we have some custom dropdowns and would like to use things like `--bs-dropdown-border-radius`.
