### ISSUE TITLE
Error compiling bootstrap.scss

### ISSUE THREAD

**Issue by ViralAgency** [twbs/bootstrap#37185]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,
i am trying to integrate bootstrap stylesheets into my stylesheet, but as soon as I try to compile bootstrap.scss file through the sass command it gives me the following error:

`Error: Invalid CSS after "...ame}: #{$value}": expected "{", was ";"
        on line 61 of mixins/_utilities.scss
        from line 21 of _mixins.scss
        from line 10 of bootstrap.scss`

The problem affects bootstrap scss files, even if compiled by themselves. I tried various versions of sass, both from the command line and from javascript, the result is the same.

### Reduced test cases

**Via command line, using Sass 3.4.23 (Selective Steve):**

```
root@viral:/var/www/my_website/node_modules/bootstrap/scss# sass bootstrap.scss bootstrap.css
Error: Invalid CSS after "...ame}: #{$value}": expected "{", was ";"
        on line 61 of mixins/_utilities.scss
        from line 21 of _mixins.scss
        from line 10 of bootstrap.scss
  Use --trace for backtrace.
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.1

**Comment by julien-deramond** [comment]
Just tried this quickly and seems to work pretty well:
```sh
npm i bootstrap
npm i sass
echo "@import './node_modules/bootstrap/scss/bootstrap';" > fake.scss
node_modules/.bin/sass fake.scss > fake.css
```

There's no error.

```sh
$ node_modules/.bin/sass --version
1.54.9 compiled with dart2js 2.18.0
```

Could you please provide more information so that we can reproduce the issue like the sass version or other?

**Comment by ffoodd** [comment]
Sass selective-steve is a Ruby Sass release: really, really old. I don't think we support this.

**Comment by julien-deramond** [comment]
Oh I missed in the description the part where the version is mentioned: "using Sass 3.4.23 (Selective Steve)". Sorry for that.
As said by @ffoodd, this is a really old release. On top of that Ruby Sass reached its end of life as of 26 March 2019 and so is no longer supported ([source](https://sass-lang.com/ruby-sass)).
You should migrate to another more recent implementation @ViralAgency.
