### ISSUE TITLE
[css] Variable --bs-{name}-rgb should reflect {name} theme color

### ISSUE THREAD

**Issue by Leonardonline** [twbs/bootstrap#37191]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

By setting the `primary`, `secondary`, etc variables like indicated [here](https://getbootstrap.com/docs/5.2/customize/sass/#modify-map) the relative variables `--bs-primary-rgb`, `--bs-secondary-rgb` do not correspond to the set values.

### Reduced test cases

```
--bs-primary: #00833c;
--bs-primary-rgb: 13, 110, 253; // sholud be 0, 131, 60
--bs-secondary: #CF5B15;
--bs-secondary-rgb: 108, 117, 125; // sholud be 207, 91, 21
```

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.2.1

**Comment by mdo** [comment]
Yeah, there's no way to do this in CSS itself, and we can't alter the CSS variable with a Sass function if I recall. You'll need to use our `to-rgb()` function within the variable.
