### ISSUE TITLE
Verically align checkbox/radio input

### ISSUE THREAD

**Issue by MikeAlhayek** [twbs/bootstrap#37196]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently, checkbox and radio button are aligned to the bottom of the label.

![image](https://user-images.githubusercontent.com/24724371/192032103-a037c697-f156-4c83-b7d0-a507bd2efea3.png)
![image](https://user-images.githubusercontent.com/24724371/192032154-fd3797b9-1d49-4ae9-bc1e-13d606e1069d.png)

I am wondering if we can vertically align the checkbox/radio to the middle of the label just so it does not look like it's sticking much over the text?

This could be done using something like this

```
.form-check-input {
  margin-top: .30rem; /* 0.30 instead of .25 */
}
```

### Motivation and context

To improve the default alignment and it would look like this instead

![image](https://user-images.githubusercontent.com/24724371/192033386-2b6fa5f9-3158-4afb-be35-14571ead4a44.png)

**Comment by mdo** [comment]
They're vertically aligned in macOS—the font for Windows is causing this issue. Fix it in one, break it in the other :).
