### ISSUE TITLE
Can't use bootstrap event types with typescript

### ISSUE THREAD

**Issue by rocifier** [twbs/bootstrap#37209]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm importing bootstrap 5 with webkit via npm ("bootstrap": "^5.1.3"). I have built a carousel and now I'm trying to type an event listener for it but I see the below error (No overload matches the call). It seems to be able to read the interface type but won't compile. What is the correct way to do this? I also tried CustomEvent<Carousel.Event> as the event type for `bsEvent` and it had the same error.

I was expecting the below code to compile.

![image](https://user-images.githubusercontent.com/1772304/192395127-c16f6e74-dfa5-4bc6-a502-54ea53d31913.png)

```
    carousel?.addEventListener('slid.bs.carousel', (bsEvent: any) => {
      this.isCurrentNoticeSevere = this.notices.at(bsEvent.to)?.severity === 1
      this.activeCarouselItem = bsEvent.to
    })
```
My only workaround at the moment is to use `any`

### Reduced test cases

Obvious as per screenshot

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.1.3

**Comment by julien-deramond** [comment]
We don't provide TypeScript definitions ourselves.

BTW there is a type definition maintained here: https://www.npmjs.com/package/@types/bootstrap.
Example of their interface for the Carousel: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bootstrap/js/dist/carousel.d.ts.

**Comment by rocifier** [comment]
wouldn't it make sense to export some of the internal types so that we can just import and use them?

**Comment by GeoSot** [comment]
If you have any good ideas or suggestions on this we would gladly accept a PR. Just keep mind we don't use Typescript yet
