### ISSUE TITLE
button sizes (btn-lg, btn-small) don't work with outlined buttons.

### ISSUE THREAD

**Issue by trusktr** [twbs/bootstrap#37228]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This code,

```html
<button type="button" class="btn-lg btn-outline-primary">Primary</button>
<button type="button" class="btn btn-outline-secondary">Secondary</button>
<button type="button" class="btn-lg btn-outline-success">Success</button>
```

results in bigger outlined buttons with funky borders:

<img width="378" alt="Screen Shot 2022-09-29 at 3 05 47 PM" src="https://user-images.githubusercontent.com/297678/193150495-f7675f18-4d4d-4ba9-a871-0889d9bdbd61.png">

### Reduced test cases

```html
<button type="button" class="btn btn-outline-secondary">Secondary</button>
<button type="button" class="btn-lg btn-outline-success">Success</button>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

4.0.0

**Comment by mdo** [comment]
You need the `.btn` class as well.
