### ISSUE TITLE
.btn-link is not documented

### ISSUE THREAD

**Issue by douglas-legulas** [twbs/bootstrap#37230]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`.btn-link` isn't on the docs.

### Reduced test cases

.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What version of Bootstrap are you using?

5.2

**Comment by ffoodd** [comment]
Yes, it is, with other buttons variants: https://getbootstrap.com/docs/5.2/components/buttons/

What's missing, for you?

**Comment by douglas-legulas** [comment]
Sorry, I hadn't seen it.
