### ISSUE TITLE
@mixin box-shadow($shadow...) => warning if $shadow contains > 1 values and first = 'none'. But "none !important" is valid

### ISSUE THREAD

**Issue by NielsHolt** [twbs/bootstrap#37243]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi
`@mixin box-shadow($shadow...)` returns a warning if `$shadow` contains > 1 values and first = `'none'`. 

But `"none !important"` is valid as `$shadow` and should not give a warning

Thanks :-)

### Reduced test cases

@include box-shadow("none !important");

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.2

**Comment by julien-deramond** [comment]
Thanks for opening this issue @NielsHolt.
Have you tried without the double quotes (`@include box-shadow(none !important);`?

**Comment by NielsHolt** [comment]
Hi @julien-deramond 
Sorry - I should have check the newest version of the mixin.
It has already been fixed and both `@include box-shadow(none !important);` and `@include box-shadow("none !important");`

Thank you

Kind regards

Niels Holt
