### ISSUE TITLE
Switch-style checkbox variables missing in documentation

### ISSUE THREAD

**Issue by xorinzor** [twbs/bootstrap#37276]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The [documentation](https://getbootstrap.com/docs/5.2/forms/checks-radios/#variables) lists the sass variables for the checkboxes, but the [switch-style variables](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L903) are missing.

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

N/A

**Comment by julien-deramond** [comment]
Yes indeed. Good catch @xorinzor!
