### ISSUE TITLE
Primary Outline Button creates one side with radius, other side not. 

### ISSUE THREAD

**Issue by TwoThreeTwo** [twbs/bootstrap#37274]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using 

`<button type="button" class="btn btn-outline-primary">Sign In</button>`

It creates the regular btn like it shows yes... but when moving it, the left side border radius becomes 0% instead of the one bootstrap provides causing it to look ugly.

![image](https://user-images.githubusercontent.com/83801755/194685512-71b58938-3407-4c13-b2dd-c00e7e72b369.png)
![image](https://user-images.githubusercontent.com/83801755/194685519-79e412e8-2007-4b14-a07f-e49aa4ad3054.png)

### Reduced test cases

happens only when using VsCode Live server? Works in codepen.io could not find a proper solution

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

V5.2.1

**Comment by TwoThreeTwo** [comment]
Okay, I just tested it, again, anything that gets connected and then deconnected by moving it automatically looses it's border radius and it is not possible to even change it.

**Comment by julien-deramond** [comment]
Thanks for opening this issue @TwoThreeTwo. I'm not sure to catch the use case, what do you mean by "moving it"?

**Comment by TwoThreeTwo** [comment]
So pretty much what I mean is that when I create the button, and use  class="btn btn-outline-primary" it creates it right next to a previously created form-control input.

when I change the position of it using CSS (not modifying bootstrap css), the position of the button does change but half the border radius gets lost and I am stuck with that image I have shown. 

Fortuantly this issue can be closed as I can just use divs to change the actual position of the button.

**Comment by mdo** [comment]
The only reason this would be happening is if the button is in an input group or something else is affecting it. Closing out given the lack of live example.
