### ISSUE TITLE
Disabled floating labels look bad after merging #37125

### ISSUE THREAD

**Issue by AgentSmith0** [twbs/bootstrap#37297]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I noticed that a disabled floating label looks pretty bad due to the changes in https://github.com/twbs/bootstrap/pull/37125.
![grafik](https://user-images.githubusercontent.com/67276662/195120246-99c55367-08a5-4e48-b939-6275db6b6a2b.png)

And this is how it looks with dark mode enabled (https://github.com/twbs/bootstrap/pull/35857):
![grafik](https://user-images.githubusercontent.com/67276662/195110461-edaf790e-24db-4008-9ce0-7584428aa09a.png)

### Reduced test cases

Look at any floating label with a disabled input element.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

main branch

**Comment by jonnysp** [comment]
the css must

.form-floating::before{
	pointer-events: none;
	background-color:transparent;
}

**Comment by jonnysp** [comment]
can not activate the input in the upper area make the pointer even none for the :before element.
