### ISSUE TITLE
TypeError Cannot read properties of undefined (reading 'backdrop') - bootstrap v5.2.1 modal

### ISSUE THREAD

**Issue by rohith2810** [twbs/bootstrap#37305]
### Discussed in https://github.com/twbs/bootstrap/discussions/37304

<div type='discussions-op-text'>

<sup>Originally posted by **rohith2810** October 12, 2022</sup>
While using bootstrap modal I am facing this error ( **TypeError Cannot read properties of undefined (reading 'backdrop')** ) , which is tracked by our **bug tracker**, but I am unable to recreate this error. I tried recreating error with various browsers, browser versions, OS. This issue is not showing up on all browsers.

Bootstrap version used - v5.2.1

I initialized modal using JavaScript

```
if (bootstrap == undefined) {
    document.getElementById("browser-not-supported-container").classList.remove("d-none");
} else {
    modal1 = new bootstrap.Modal(document.getElementById('modal1'));
    modal2 = new bootstrap.Modal(document.getElementById('modal2'));
    modal3 = new bootstrap.Modal(document.getElementById('modal3'));
}
```

Html code for these modals
```
<!-- Modal 1-->
<div class="modal fade text-start" data-bs-backdrop="static" data-bs-keyboard="false" id="modal1" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <!-- Header -->
            </div>
            <div class="modal-body">
                <!-- Body -->
            </div>
        </div>
    </div>
</div>

<!-- Modal 2-->
<div class="modal fade text-start" id="modal2" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <!-- Body -->
            </div>
        </div>
    </div>
</div>

<!-- Modal 3-->
<div class="modal fade text-start" id="modal3" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <!-- Body -->
            </div>
        </div>
    </div>
</div>
```

The exact error is:
```
TypeError Cannot read properties of undefined (reading 'backdrop') 
    https://example.com/:lineNo3:colNo3 Ni._initializeBackDrop
    https://example.com/:lineNo2:colNo2 new Ni
    https://example.com/:lineNo1:colNo1 HTMLDocument.<anonymous>
```
**Note**: lineNo1 is where modal2 is initializing

I also tried with modal options but error is still persisting
```
modal1 = new bootstrap.Modal(document.getElementById('modal1'), { backdrop: "static", keyboard: false });
modal2 = new bootstrap.Modal(document.getElementById('modal2'), { backdrop: "static", keyboard: false });
modal3 = new bootstrap.Modal(document.getElementById('modal3'), { backdrop: "static", keyboard: false });
```

**Comment by rohith2810** [comment]
Hello @GeoSot , I can't recreate the issue but we are getting exceptions in our bug tracker

**Comment by rohith2810** [comment]
I will try and let you know

**Comment by bay-jacewhitten** [comment]
This is happening due to an invalid / or non existing DOM element being passed. I discovered this today by mistakenly passing the wrong selector.

"myModal" !== "#myModal"  when using the getOrCreateInstance method.

What happens is it gets to base-component js and tries to set up `this._element` and `this._config`, but fails. Then modal js kicks in and attempts to build the modal and backdrop, but the `this._element` is undefined. You can see here the `this` context is missing the config object as well as the rest of the keys.

Hopes this helps someone :) 

![Screen Shot 2022-10-28 at 10 59 58 AM](https://user-images.githubusercontent.com/79159096/198706570-2fc946d7-05d2-4f97-9ebc-d23da6f04135.png)

**Comment by gartenkralle** [comment]
I am receiving this error when doing something like this:

```
    document.querySelector('#heart').addEventListener('click', function () {
        new bootstrap.Modal(document.getElementById('donate-modal')).show();
    });
```

**Comment by selfguard** [comment]
still facing this issue

**Comment by lekoala** [comment]
Since i also get this error in my bug tracker, i think it's related to my other issue here
https://github.com/twbs/bootstrap/issues/37265

in my case, it believe it's due to the element being removed

when there is no element, config is never set
https://github.com/twbs/bootstrap/blob/9013c9884e53be23f58e00026035baa38f2a31a2/js/src/base-component.js#L27-L33

and therefore, it crashes...

**Comment by hightowertech** [comment]
My first progress on this error was removing data-bs-toggle="modal" since im already showing/hiding modals via a click handler.

Upon further examination, this error is being shown to me because of data-bs-target being wrong.

**Comment by lekoala** [comment]
@hightowertech yes that's exactly what's happening. i think it's very counter intuitive that in the constructor, you have a check for !element, but in any other components, the check is not done again and since the super call is not returning anything, it proceeds as if there was a valid element.

what would make sense: enforce a type check and throw error for invalid elements in the base component. at least we would get a meaningful error

**Comment by faridmumtaz** [comment]
@rohith2810 
Make sure 
document.getElementById('modal#')
is not returning null in else block

**Comment by LinusPratiwi** [comment]
> My first progress on this error was removing data-bs-toggle="modal" since im already showing/hiding modals via a click handler.
> 
> Upon further examination, this error is being shown to me because of data-bs-target being wrong because on some pages im going modal to modal and on other pages im not. dont be like me.

Thanks, it works for me!

**Comment by pixeljae** [comment]
> My first progress on this error was removing data-bs-toggle="modal" since im already showing/hiding modals via a click handler.
> 
> Upon further examination, this error is being shown to me because of data-bs-target being wrong because on some pages im going modal to modal and on other pages im not. dont be like me.

Such a simple oversight but thank you for saving me time!

Easy to overlook but for anyone else seeing this, it says in the [docs](https://getbootstrap.com/docs/5.2/components/modal/#via-data-attributes) that `data-bs-toggle="modal"` is for cases where JS is not used.

> Activate a modal without writing JavaScript. Set data-bs-toggle="modal" on a controller element, like a button, along with a data-bs-target="#foo" or href="#foo" to target a specific modal to toggle.

**Comment by ServiGram** [comment]
> My first progress on this error was removing data-bs-toggle="modal" since im already showing/hiding modals via a click handler.
> 
> Upon further examination, this error is being shown to me because of data-bs-target being wrong because on some pages im going modal to modal and on other pages im not. dont be like me.


Thanks, this worked for me with angular.

**Comment by VishalGurudasani** [comment]
I have created a button and giving the id in this works for me {data-bs-target="#yourModalId"} it means that when you create multiple modals to see it you have to change your id otherwise it will show similar results so when you are changing your id you have to change the target too

**Comment by redati** [comment]
define data-bs-backdrop="static" :)

**Comment by gensart-x** [comment]
> define data-bs-backdrop="static" :)

I've tried on my select, not working, still gives an error on console shown.
![image](https://github.com/twbs/bootstrap/assets/165239315/24f76bff-2cfb-47f8-86a7-4e7e1863b85d)
![image](https://github.com/twbs/bootstrap/assets/165239315/4529e285-4097-4435-8e77-da7c21bf3e8f)


Btw, is my problem related to Bootstrap ?

**Comment by vaishaliv0403** [comment]
<a type="button" class="btn btn-sm mx-5 p-0" data-bs-toggle="modal" data-bs-target="#exampleModal" 
                   data-bs-backdrop="static" (click)="openModal(i)"
                  style="color: #0F67B1;" aria-expanded="false"  >
                    Edit
                </a>
                getting the same error
                Cannot read properties of undefined (reading 'backdrop')
                what should i do?

**Comment by lekoala** [comment]
it means your element is not valid

i don't get why they don't add a proper check for this with a meaningful error

**Comment by domensam** [comment]
Kind of unrelated: If you copied a modal’s code from one file to another and it worked in the original but not in the new file, try refreshing your browser cache (Windows: Ctrl + Shift + R / Mac: Cmd + Shift + R). 

This TypeError appeared on my new file, and a little refresh did the magic :D
