### ISSUE TITLE
Request: A responsive way to use floating labels

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#37310]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Ideally, I would like to have classes like `.form-floating-md` on a standard `<label>` and `<input>` combination.  However, the order when using floating labels is `<input>` before `<label>` so the same layout may not be used for both regular and floating labels.

I worked a workaround using JavaScript but required setting an **attribute** (`disabled`) depending on the break point as explained in the motivation below.

### Motivation and context

The motivation is to have floating labels on phones but regular ones when there is more screen space.

A workaround is to have both layouts present in the `<form>`, perhaps each enclosed in a `<fieldset>` as in the following example (I don't know how to indent code in this request, I apologize):
`<div class="row mb-3">`
`  <fieldset class="d-none d-md-flex">`
`    <label class="col-6 col-form-label text-end>some label</label>`
`    <div class="col-md-5 col-lg-3">`
`      <input class="form-control" type="text" name="fieldname" placeholder="some label" required>`
`      <div class="invalid-feedback">some msg</div>`
`    </div>`
`  </fieldset>`
`  <fieldset class="form-floating d-md-none">`
`    <input class="form-control" type="text" name="fieldname" placeholder="anything" required>`
`    <div class="invalid-feedback">some msg</div>`
`    <label class="col-form-label">some label</label>`
`  </fieldset>`
`</div>`

The problem is that, although only one input is seen at a time, by the use of display helper classes, we end up with two `<input>`s with the same `name` attribute!

I tried to "mirror" the value to an `<input type="hidden" name="fieldname">`  using JavaScript, omitting the `name` attribute from the `<input>`s, which is a partial solution. Now, the form will never validate because only one `required`  will have a value!

What is needed is to add the `disabled` attribute on the `<fieldset>` that is not being shown.  I worked out a "solution" (a hack, really) using a pair of `data-{breakpoint}` attributes for adding and removing attributes.  The `<fieldset>`s become:
`<fieldset class="d-none d-md-flex" disabled data-qt-md-unset="disabled">` and
`<fieldset class="form-floating d-md-none" data-qt-md-set="disabled">`, respectively. The `qt` is the project prefix.

If you have a better workaround, I'm all ears.  Thanks in advance.

**Comment by mdo** [comment]
No plans to add this ourselves—we'll keep the form layouts separate for the foreseeable future.
