### ISSUE TITLE
The alert borders ignore border-width

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#37326]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The alert borders use `--bs-alert-border` which explicitely sets, both, the width and the style of the border to `1px` and `solid`, respectively. In particular, it doesn't make use of `--bs-border-width` so utilities like `.border-2` have no effect.

### Reduced test cases

From bootstrap.css, we find: `--bs-alert-border: 1px solid var(--bs-alert-border-color);` and `.border-2` simply sets: `--bs-border-width: 2px;` which has no effect in the alert.

My workaround was a class `.alert-border` setting `--bs-alert-border: var(--bs-border-width) solid var(--bs-alert-border-color);` although it should probably have `--bs-border-style` instead of `solid`, but there are no utilities to set that variable.

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.1

**Comment by rxbracho** [comment]
I don't know how to use CodePen or StackBlitz, so I resort to a photograph of the bootstrap.css in the dist/ directory of v5.2.2 next to the documentation about alerts in the same version.  You can see that the documentation says one thing and the code does another. 

![20221019_160027](https://user-images.githubusercontent.com/47257701/198853244-c3e54ebf-d2f9-4988-8a22-6416ef1bffbc.jpg)

I hope it helps.

**Comment by jonnysp** [comment]
the changes are currently in development and will be updated later. to use the version already follow the instructions at https://github.com/twbs/bootstrap#documentation or wait for the release of version 5.3.
