### ISSUE TITLE
There must have a react version of every component

### ISSUE THREAD

**Issue by Rancho2002** [twbs/bootstrap#37325]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

It is difficult for a user to modify the copied code everytime in a react file. So if we can give that user a react version of that bootstrap code, the productive time will be increased for that user. So please assign it to me @twbs-grunt

### Motivation and context

I faced difficulties myself while learning react with bootstrap. Here I get the motivation to improve this thing by contributing.

Before fixing code the navbar inside a react app:
![image](https://user-images.githubusercontent.com/92109154/195978249-c305107b-3fc0-452f-8a3e-690c780850a4.png)

After fixing code the navbar preview inside a react app: 
![image](https://user-images.githubusercontent.com/92109154/195978046-cc6bf007-1730-4134-b76c-4063b2f11b72.png)

Here is the code URL :
https://codepen.io/rancho2002/pen/rNvRGro

And this type of change is necessary for all the other components.

**Comment by Rancho2002** [comment]
@samadpls pls look into this issue and assign it to me

**Comment by Rancho2002** [comment]
Hi @julien-deramond pls check this isse

**Comment by julien-deramond** [comment]
Hi @Rancho2002 please check [the documentation](https://getbootstrap.com/docs/5.2/getting-started/javascript/#usage-with-javascript-frameworks). Among the popular options, you can check [React Bootstrap](https://react-bootstrap.github.io/).

**Comment by Rancho2002** [comment]
> Hi @Rancho2002 please check [the documentation](https://getbootstrap.com/docs/5.2/getting-started/javascript/#usage-with-javascript-frameworks). Among the popular options, you can check [React Bootstrap](https://react-bootstrap.github.io/).

Sorry, I have not notice this documentation earlier. Thanks for your reply.
