### ISSUE TITLE
Box shadows have disappeared from the active state of buttons

### ISSUE THREAD

**Issue by fabiochelly** [twbs/bootstrap#37327]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Since version 5.2, all box-shadows have disappeared from the active state of buttons. Is it a bug?
If not, is there a way to get them back? This focus rect was one of the things that make Bootstrap buttons beautiful.

### Reduced test cases

Just install Bootstrap 5.2. Buttons No box-shadow anymore on the active state of buttons

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.2.0

**Comment by julien-deramond** [comment]
Thanks for opening this issue @fabiochelly.
The active state hasn't changed between v5.1 and v5.2; there's no box-shadow for the active state but rather a darker color.
Maybe you're talking about the focus state which has changed. For all `.btn`s, the `:focus` styling has changed to `:focus-visible` - this way, the focus style doesn't take effect and "stick" (until you click somewhere else) for mouse/touch users.

**Comment by fabiochelly** [comment]
Yes, I was effectively referring to the focus state.
Is there a way to go back to the previous mode (even by adding some custom CSS to the btn class) ?

**Comment by mdo** [comment]
Going to close for now as we'd like this change to stick around. Let's wait on getting some more feedback here and decide what to do after that. Thanks!

**Comment by vinibiavatti1** [comment]
So, is there some documentation explaining the reason about this change? I noticed now too, and wanted just to know why this features was removed for the buttons. I tryed to find something in the blog but could not find enything.

**Comment by julien-deramond** [comment]
> So, is there some documentation explaining the reason about this change? I noticed now too, and wanted just to know why this features was removed for the buttons. I tryed to find something in the blog but could not find anything.

You'll probably find more information in https://github.com/twbs/bootstrap/pull/37026 and maybe in the corresponding closed issues as well.

**Comment by vinibiavatti1** [comment]
Thanks @julien-deramond
