### ISSUE TITLE
Color variables can't be overridden perfectly

### ISSUE THREAD

**Issue by dwiesign** [twbs/bootstrap#37339]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

That is the css of the button primary in my bootstrap.css. At a later date I override the value of the new primary variable not via sass. So the background color of btn-primary is not the same as bg-primary. Is there any solution for this?

### Reduced test cases

```
/* Boostrap.css */
.btn-primary {
    --dg-btn-color: #fff;
    --dg-btn-bg: #6f42c1;
    --dg-btn-border-color: #6f42c1;
    --dg-btn-hover-color: #fff;
    --dg-btn-hover-bg: #5e38a4;
    --dg-btn-hover-border-color: #59359a;
    --dg-btn-focus-shadow-rgb: 133, 94, 202;
    --dg-btn-active-color: #fff;
    --dg-btn-active-bg: #59359a;
    --dg-btn-active-border-color: #533291;
    --dg-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
    --dg-btn-disabled-color: #fff;
    --dg-btn-disabled-bg: #6f42c1;
    --dg-btn-disabled-border-color: #6f42c1;
}

/* My override in custom.css */
:root {
    --dg-primary: #0284c7;
    --dg-primary-rgb: 2, 132, 199;
}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.x

**Comment by mdo** [comment]
This has been highlighted in our docs, migration guide, and blog posts, but perhaps there's more we can do. We're limited by backwards compatibility for enabling what you're looking for :). It's planned for v6 to be able to control everything via CSS variables.
