### ISSUE TITLE
Enable OpenSSF Scorecard Github Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [twbs/bootstrap#37343]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi, I'm Joyce from Google and I'm working on behalf of the [Open Source Security Foundation][ossf] (OpenSSF) to help essential open-source projects improve their supply-chain security.

The OpenSSF has developed, [in partnership with GitHub][sc-blog], a tool called [Scorecards][sc]. Scorecards runs dozens of automated security [checks][checks] to help maintainers better understand their project's supply-chain security posture. 

I would like to suggest the adoption of the [Scorecard GitHub Action][sc-gha], which was developed by the OpenSSF to make it easier to run the Scorecard checks on projects hosted in Github. The action is very lightweight and runs on every change to the repository's main branch. 

[checks]: https://github.com/ossf/scorecard#scorecard-checks
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action

### Motivation and context

The results of the Scorecard's checks are available on the project's [security dashboard](https://github.com/twbs/bootstrap/security), and include suggestions on how to solve any issues (see examples below). The Action does not run or interact with any workflows, but merely parses them to identify possible vulnerabilities. This Action has been adopted by 1800+ projects already, having some prominent users like [Tensorflow][tensorflow], [Angular][angular], [Flutter][flutter], [sos.dev][sos-dev] and [deps.dev][deps-dev].

The Bootstrap project is already following most of the supply-chain security best practices (the top 6.6% greatest scorecard scores), but the Scorecard would still help to track other security posture improvements, to guarantee the already followed ones would still be followed, to be up to date to new security best practices since Scorecard is in continuous improvement and, if you opted for the [badge][badge], it would also show to the users the project's commitment to security best practices.   

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows the previously mentioned [badge][badge] with the project's score to be added to the README file.

In case of doubts or concerns you can check out the [Scorecards FAQ][faq]. Anyway, feel free to reach me out.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[checks]: https://github.com/ossf/scorecard#scorecard-checks
[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[faq]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions 
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

[tensorflow]: https://github.com/tensorflow/tensorflow
[angular]: https://github.com/angular/angular  
[flutter]: https://github.com/flutter/flutter 
[sos-dev]: https://sos.dev/ 
[deps-dev]: https://deps.dev/

**Comment by XhmikosR** [comment]
BTW, as for the badge, ideally we should use the one from shields.io so that we have a consistent look and less domains to query in our README.md.

**Comment by julien-deramond** [comment]
> shields.io

Shouldn't be a problem (source: https://shields.io/category/analysis)

<img width="932" alt="Screenshot 2022-10-25 at 20 34 10" src="https://user-images.githubusercontent.com/17381666/197854160-2e316c61-43c9-491a-a90f-0647306477d7.png">
