### ISSUE TITLE
Error with a generated value

### ISSUE THREAD

**Issue by Faridsc** [twbs/bootstrap#37340]
it should be:
```
.col { 
   flex: 100%; 
 }
```
found in the bootstrap.css file 
```
.col { 
   flex: 1 0 0%; 
 }

```

**Comment by julien-deramond** [comment]
Thanks for opening an issue @Faridsc. This definition of `.col` is normal, it shouldn't be `flex: 100%`.
You'll find more information in:
- [Docs > Layout > Columns](https://getbootstrap.com/docs/5.2/layout/columns/)
- [Docs > Layout > Grid](https://getbootstrap.com/docs/5.2/layout/grid/)
