### ISSUE TITLE
`&amp;` displayed in Algolia search results titles

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#37342]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`&amp;` is displayed instead of `&` in Algolia search results titles in violet (`.DocSearch-Hit-source`).
We can see in the following screenshot: "Color **\&amp;** background" and "Color **\&amp;** Webpack".

![Screenshot 2022-10-13 at 13 10 55](https://user-images.githubusercontent.com/17381666/195581608-21f60e98-abee-464a-b0d0-8ed2a65a1f9f.png)

Interesting thing is that it is not the case for `.DocSearch-Hit-title` in the results:

![Screenshot 2022-10-19 at 20 26 03](https://user-images.githubusercontent.com/17381666/196774417-a0f09ab9-3272-4715-b26a-0c33f18fe1dc.png)

### Reduced test cases

Go to https://getbootstrap.com/docs/5.2/getting-started/introduction/:
1. Click on the search button
2. Type "color back"

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2.2

**Comment by manuelmeurer** [comment]
Another Algolia search box issue: when you enter "mo", it shows a lot of weird text below the search field: https://monosnap.com/file/gPJNuQlc0Ft73L2tQqqc6oHDIz4JHa

(sorry for piggybacking, should I create a separate issue?)

**Comment by julien-deramond** [comment]
Thanks for reporting that @manuelmeurer. It's already in https://github.com/twbs/bootstrap/issues/37312 and we're trying to find a solution. It is apparently due to the fact that we have several `<h1>`s in this modal page.

**Comment by mdo** [comment]
Changing the title of the page is the easiest fix here, PR coming.

**Comment by CyrilKrylatov** [comment]
Hello people,

I see you merged a fix for that but I think I found a new issue related. Indeed when i'm looking for `mo`, I have this result:

![ss_ 6119](https://user-images.githubusercontent.com/1059657/199693190-2c0c2ee8-4f86-4679-8fce-79eab494598b.jpg)

I also tested it on https://deploy-preview-37400--twbs-bootstrap.netlify.app/docs/5.2/getting-started/webpack/ from #37400 and it's broken there too.

Cheers! ✌️

**Comment by julien-deramond** [comment]
Yep @CyrilKrylatov. It's already tracked in https://github.com/twbs/bootstrap/issues/37312.
