### ISSUE TITLE
Masonry fails when first element is a .col-12

### ISSUE THREAD

**Issue by rolleric** [twbs/bootstrap#37357]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When the first column in the masonry-marked `.row` is a `div.col-12`, all columns are placed underneath each other on the left-hand side of the row (whereas they should fill the available space).

To reproduce, change the first column in the [Masonry example page](https://getbootstrap.com/docs/5.2/examples/masonry/) from `class="col-sm-6 col-lg-4 mb-4"` to `class="col-sm-12 mb-4"` (and if the edit was done in the browser's inspector resize the page to trigger a re-layout).

### Reduced test cases

...can't get this to work on CodePen.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.2.2

**Comment by julien-deramond** [comment]
IDK if this is the best solution but the following seems to work:

```diff
diff --git a/site/content/docs/5.2/examples/masonry/index.html b/site/content/docs/5.2/examples/masonry/index.html
index b4aecaa17..df5198e9f 100644
--- a/site/content/docs/5.2/examples/masonry/index.html
+++ b/site/content/docs/5.2/examples/masonry/index.html
@@ -22,7 +22,7 @@ extra_js:
   <hr class="my-5">
 
   <div class="row" data-masonry='{"percentPosition": true }'>
-    <div class="col-sm-6 col-lg-4 mb-4">
+    <div class="col-sm-12 mb-4">
       <div class="card">
         {{< placeholder width="100%" height="200" class="card-img-top" text="Image cap" >}}
         <div class="card-body">
@@ -31,6 +31,8 @@ extra_js:
         </div>
       </div>
     </div>
+  </div>
+  <div class="row" data-masonry='{"percentPosition": true }'>
     <div class="col-sm-6 col-lg-4 mb-4">
       <div class="card p-3">
         <figure class="p-3 mb-0">
```

**Comment by rolleric** [comment]
Yes, that is my current workaround, but it requires knowledge of what size the first box will be. In a system with user-supplied content and dynamic sizes, this can be difficult to support in code.

**Comment by julien-deramond** [comment]
Found something that might be related to this issue: https://masonry.desandro.com/faq.html#the-first-item-breaks-the-grid.

Could an adapted version of the following work in your case?

```diff
diff --git a/site/content/docs/5.2/examples/masonry/index.html b/site/content/docs/5.2/examples/masonry/index.html
index b4aecaa17..0b04ec6e8 100644
--- a/site/content/docs/5.2/examples/masonry/index.html
+++ b/site/content/docs/5.2/examples/masonry/index.html
@@ -21,8 +21,8 @@ extra_js:
 
   <hr class="my-5">
 
-  <div class="row" data-masonry='{"percentPosition": true }'>
-    <div class="col-sm-6 col-lg-4 mb-4">
+  <div class="row" data-masonry='{"percentPosition": true, "columnWidth": ".col-lg-4" }'>
+    <div class="col-sm-6 col-lg-12 mb-4">
       <div class="card">
         {{< placeholder width="100%" height="200" class="card-img-top" text="Image cap" >}}
         <div class="card-body">
```
