### ISSUE TITLE
Disabled form-floating input uses wrong colour

### ISSUE THREAD

**Issue by lonix1** [twbs/bootstrap#37362]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A disabled form-floating input uses the wrong colour.

### Reduced test cases

Demo shows:
- disabled input in grey - correct
- disabled form-floating input in black - incorrect

https://codepen.io/vwhzvdkyrlmuapzyih/pen/MWXgVmm

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.2.2

**Comment by mdo** [comment]
I think we do risk that, but generally that's okay I think as the end result is the same—an input with a label is disabled. I merged your other PR without seeing this—want to cut a new one if you're able?
