### ISSUE TITLE
Gap for flexbox

### ISSUE THREAD

**Issue by saltnpixels** [twbs/bootstrap#37384]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Flexbox has the gap property just as css grid does. And its available across all browsers. Why does bootstrap still use paddings and negative margin hacks...

you can even remove the row class and div altogether now...

### Motivation and context

Cause tha future is here!

**Comment by mdo** [comment]
This will be coming in v6. It'd be a major breaking change to modify the grid's behavior mid-flight :).

**Comment by gumbarros** [comment]
@saltnpixels  how do you solved your problem to apply gap in a flexbox without Bootstrap?
