### ISSUE TITLE
Outlined radio buttons are not changing background color on mouse hover since 5.2.1.

### ISSUE THREAD

**Issue by JimiRecard** [twbs/bootstrap#37386]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Since version 5.2.1, [outlined radio buttons](https://getbootstrap.com/docs/5.2/forms/checks-radios/#outlined-styles) only change color after a click, no longer on mouse hover. Expected behavior can be checked on version [5.1 docs](https://getbootstrap.com/docs/5.1/forms/checks-radios/#outlined-styles).

### Reduced test cases

Working on [version 5.1](https://getbootstrap.com/docs/5.1/forms/checks-radios/#outlined-styles)

Not working since [version 5.2.1](https://getbootstrap.com/docs/5.2/forms/checks-radios/#outlined-styles)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.2

**Comment by julien-deramond** [comment]
Seems to be linked to https://github.com/twbs/bootstrap/pull/37165. @patrickhlauke could you please confirm that it was done on purpose even for the outlined radio buttons?

**Comment by patrickhlauke** [comment]
sorry, on the road. quick answer: yes, it was done on purpose to avoid the visual confusion we originally hadOn 28 Oct 2022, at 06:41, Julien Déramond ***@***.***> wrote:﻿
Seems to be linked to #37165. @patrickhlauke could you please confirm that it was done on purpose even for the outlined radio buttons?
