### ISSUE TITLE
Disposing a modal after hiding it triggers an error.

### ISSUE THREAD

**Issue by ernestob** [twbs/bootstrap#37409]
It is necessary to check if the focus value exists before trying to read it.
Without this, disposing of a modal after hiding it triggers the following error.
```
Uncaught TypeError: Cannot read properties of null (reading 'focus')
```
https://github.com/twbs/bootstrap/blob/961d5ff9844372a4e294980c667bbe7e0651cdeb/js/src/modal.js#L191

Here is the example: https://codepen.io/ernestobr/pen/zYarvQq

**Comment by GeoSot** [comment]
The "wrong" approach here, is that `hide` method is asynchronous as the modal is faded, so you have to add an event listener before disposing the modal. Try it and you will be more than fine :wink:
