### ISSUE TITLE
Uncaught Error 

### ISSUE THREAD

**Issue by Denspain32** [twbs/bootstrap#37407]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

### Reduced test cases

![16672393372053945847465471910562](https://user-images.githubusercontent.com/92932813/199077643-3126073b-189f-4722-88b5-9fbfbf88536b.jpg)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v3.3.6

**Comment by julien-deramond** [comment]
Thanks for opening this issue @Denspain32 but Bootstrap v3 is EOL. You should try to update your project or change the dependencies to respect what was defined in the v3.

**Comment by Denspain32** [comment]
Please how can I go about the up dates, because I don't know what I need to
update
