### ISSUE TITLE
Floating labels for selects with same behaviour as inputs

### ISSUE THREAD

**Issue by lonix1** [twbs/bootstrap#37416]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Floating labels works for selects, but are always shown as "floated".

Is there a technical limitation for this behaviour? If not, it would be nice to have it behave as inputs do - to be shown "normally" until the select is populated, and only then to be floated.

### Motivation and context

In a form that has both inputs and selects, not all floating labels behave in the same way. That can cause confusion for some users.

**Comment by nkdas91** [comment]
_"A placeholder is required on each ```<input>``` as our method of **CSS-only** floating labels uses the ```:placeholder-shown``` pseudo-element."_

The ```:placeholder-shown``` pseudo-element is used to determine the ```<label>```'s floating state.  And since Selects don't have a placeholder, they are programmed to always show the ```<label>``` in its floated state.
