### ISSUE TITLE
Breaking down the border-radius property in SCSS

### ISSUE THREAD

**Issue by webprogramozo** [twbs/bootstrap#37420]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I recommend to take advantage of the opportunities offered by SCSS: with some functions, mixins and map data structures, BS gives users the ability to specify the different corners even separately, while can still use this complex value in the components to format some of its parts.

I created some mixins to show a possible solution for this feature request: [border_radius_helper.scss](https://gist.github.com/webprogramozo/de19dcc0843906b90a8cbbbcde416741)

I deliberately did not combine the values of the different corners where possible, because in the case of a null value, they will not be included in the finished CSS, so they can be overwritten. Another solution can be good for the same problem, where only the CSS variables are split up in the part before the component and they are used when setting the values of the final property.

I'm still pretty new to SCSS, so there might be a simpler solution than mine.
I am also happy to participate in the preparation of the final solution, if there is a need for it.

### Motivation and context

When I tried to customize my BS design with editing the SCSS variables, the Card component started looking weird. This happened because I tried to apply different values for the different corners but still in the `border-radius` property which caused invalid value in other places. 

I added an override value for `$border-radius` variable:
`$border-radius:  0.75rem 0.2rem 0.75rem 0.2rem;`

Most of the simple places this worked but somewhere not. 
The card component' has the following style:
```
.card-header {
    --bs-card-inner-border-radius: calc(0.75rem 0.2rem 0.75rem 0.2rem - 1px);
}
.card-header:first-child {
    border-radius: var(--bs-card-inner-border-radius) var(--bs-card-inner-border-radius) 0 0;
}
.card-footer:last-child {
    border-radius: 0 0 var(--bs-card-inner-border-radius) var(--bs-card-inner-border-radius);
}
```

The result is a not-working `border-radius` property as you can see.

![image](https://user-images.githubusercontent.com/4670604/199474057-c7625270-b6ee-4e4b-8092-800549dced95.png)

Because of BS is constantly evolving, I do not want to make changes to the central files locally for customization but because of the `border-radius` propagation in SCSS files is static, I should override every component manually and then debug, if any part of the component is still looks bad.

**Comment by webprogramozo** [comment]
I am also open to approaching the possibility of improvement from the direction of the CSS variables, border-radius values should also be available for the :root variables, just like the colors, which could then be used by the different components. Or is that planned?

**Comment by mdo** [comment]
I don't think this needs such a complicated mixin. Here's a reduced example: https://codepen.io/emdeoh/pen/QWBjemO. This is basically supported in our existing `.card` component, but maybe needs different selectors to properly target. Set the outer `border-radius` to what you want, then reset the inner `border-radius` on those particular selectors. There might be some optimization we could do in v6 around the styles here, but I don't see us making any major change just yet. Open to more ideas though!
