### ISSUE TITLE
emergency risk:  twitter.com not available for js file encoutering CORS 

### ISSUE THREAD

**Issue by scil** [twbs/bootstrap#37423]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

sorry.

it's not about bootstrap.

it's about website twitter.com and very serious.

this problem have been at least half day. 

maybe some laid-off employee..

I have no other way to call twitter.  just post here to tell more people to spread this serious problem.

![image](https://user-images.githubusercontent.com/2786775/199904478-9ef7f4f6-1e5c-4028-a024-02b3801d0e78.png)

### Reduced test cases

...

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5

**Comment by julien-deramond** [comment]
Not related to Bootstrap so I'm closing this issue.
