### ISSUE TITLE
Modal not working on mobile.

### ISSUE THREAD

**Issue by mihai-vp** [twbs/bootstrap#37422]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am using the modal bootstrap class. Copied the code off the bootstrap website. The code works on desktop and when i make my screen resolution to a mobile's one it still works. However, after testing on my mobile it seems the tint it adds when the modal pops up, comes ontop of the modal. Meaning you can edit/click off it only by refreshing the page. This has only been touched previously, but that was while using bootstrap 4.0.0.  

I have tried editing and removing classes to help with this, but nothing worked, not sure of this is a issue allready discussesd in the community as ive not seen much on it.

In the attached images you can see on desktop the dark tint is behind the content, but on mobile is the other way around.
https://github.com/twbs/bootstrap/issues/21546 
Here is a previous "work around", but that is unstable and not good option. However this issue has been traced back since bootstrap 3.0.0

### Reduced test cases

![Screenshot 2022-11-03 163316](https://user-images.githubusercontent.com/110549189/199779255-469bb818-20ba-42e8-918a-0762264bf4fa.png)
![image0311202216323993](https://user-images.githubusercontent.com/110549189/199779328-eb596954-ce87-4262-96fe-7115c7a4fbb4.PNG)

### What operating system(s) are you seeing the problem on?

Windows, iOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.2.2

**Comment by mdo** [comment]
Closing as stale.
