### ISSUE TITLE
Incompatible with sass 1.56.0

### ISSUE THREAD

**Issue by simPod** [twbs/bootstrap#37424]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Sass v1.56.0 gives following warning:

```
Deprecation $weight: Passing a number without unit % (100) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units
```

### Reduced test cases

Compile:

```
bootstrap/scss/_functions.scss 201:11  opaque()
bootstrap/scss/_functions.scss 175:18  contrast-ratio()
bootstrap/scss/_alert.scss 64:8        @import
```

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.2.2

**Comment by Gal0n** [comment]
I have the same issue with tint-color() function. Sass v1.56.1.

```
Deprecation Warning: $weight: Passing a number without unit % (0) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
207 │   @return mix(white, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src\scss\vendor\bootstrap\_functions.scss 207:11  tint-color()
    src\scss\vendor\bootstrap\_functions.scss 217:57  shift-color()
    src\scss\vendor\bootstrap\_variables.scss 702:17  @import
    src\scss\modules\reviews.scss 5:9                 root stylesheet
```
