### ISSUE TITLE
Enhance dropdown link examples

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#37426]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

[Dropdown documentation > Single Button](https://getbootstrap.com/docs/5.2/components/dropdowns/#single-button) shows the example of the dropdown link which uses `<a>` instead of `<button>`.

```html
<a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  Dropdown link
</a>
```

IMHO I don't think of any use cases where it could be actual links.

As discussed with @patrickhlauke we might want to reinforce the idea (you can use it, doesn't mean you should).

We could add an info callout here but remove in all the documentation the examples where we use `<a>`s instead of `<button>`s.

### Motivation and context

Prefer the approach with buttons so this one is rather propagated in websites rather than the `<a>` approach.

**Comment by patrickhlauke** [comment]
agree on this, but forgot after our chat to submit a PR...oops
