### ISSUE TITLE
Deprecation warning $weight: Passing a number without unit % (100) is deprecated.

### ISSUE THREAD

**Issue by MtnBiker** [twbs/bootstrap#37430]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Deprecation warning when compile

Deprecation Warning: $weight: Passing a number without unit % (100) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
201 │   @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 201:11            opaque()
    node_modules/bootstrap/scss/mixins/_table-variants.scss 4:28  table-variant()
    node_modules/bootstrap/scss/_tables.scss 147:3                @import
    bootstrap/scss/bootstrap.scss 20:9                            @import
    app/assets/stylesheets/application.bootstrap.scss 1:9         root stylesheet

### Reduced test cases

Although a browser is asked for this is compiling in iTerm in a Ruby on Rails application

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.2

**Comment by jakeboone02** [comment]
This was already fixed by #37425.

**Comment by martinschaible** [comment]
What i can i do until 5.3 is released?

**Comment by w4sevens** [comment]
i met the same question!!!

**Comment by julien-deramond** [comment]
> i met the same question!!!

[Answer's here](https://github.com/twbs/bootstrap/discussions/37467#discussioncomment-4199573)
