### ISSUE TITLE
Bug in the Bootstrap Support Team

### ISSUE THREAD

**Issue by byturna** [twbs/bootstrap#37440]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am trying to get a refund for a theme purchased from themes.getbootstrap.com

Order #117364 purchased on September 22nd

I have been trying to contact the theme developer since September (after my purchase). But didn't get any response. After I tried getting in touch with the Bootstrap team from the website (themes@getbootstrap.com). No succes. 

I want a refund and after doing some research I can see that there are more people with this problem.

I understand that this is not the place to ask for this but I can't get anyone to respond. Fix your support team. I want my money back ASAP!

### Reduced test cases

None

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.2.2

**Comment by mdo** [comment]
Closing as this isn't the place to ask about Themes as that's separate from the open source project.

@byturna Please forward me your email though and I'll see what I can do separately to ping the Themes team.
