### ISSUE TITLE
Get the latest version # automatically?

### ISSUE THREAD

**Issue by gasolinehorse** [twbs/bootstrap#37487]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi,

I am the owner of htmlboilerplates.com and am constantly checking getbootstrap.com to make sure I am offering the latest bootstrap version on my site. Is there an API I can use to call the latest version number? If not, what do you suggest to make sure my site always offer the latest version?

Lastly, thank you all for the significent contribution to the dev world!

Thanks,
Al

### Motivation and context

This can make sure any 3rd party tools that is suggesting bootstrap (like mine) to their users suggest the latest version.

**Comment by GeoSot** [comment]
Hello @gasolinehorse does this api call works for you https://api.github.com/repos/twbs/bootstrap/releases/latest?

**Comment by gasolinehorse** [comment]
@GeoSot I believe it does! Thanks so much for helping out!

**Comment by GeoSot** [comment]
Wishing just all the issues were easy, like this 👼
