### ISSUE TITLE
Deviantart iconSuggest a new feature

### ISSUE THREAD

**Issue by mpaglia0** [twbs/bootstrap#37489]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can you please draw Deviantart icon?

### Motivation and context

Deviantart is a big and active community of artist

**Comment by julien-deramond** [comment]
Thanks for creating this issue @mpaglia0. For the icons, there is a specific repository where such a request is already in the backlog: https://github.com/twbs/icons/issues/1388.

**Comment by mpaglia0** [comment]
I am sorry!!
Thank you for the info
