### ISSUE TITLE
Can't close modal if there is a javascript Modal object created after shown.

### ISSUE THREAD

**Issue by mfazekas** [twbs/bootstrap#37500]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Sometime the `data-bs-dismiss="modal"` doesn't work and doesn't closes the modal

### Reduced test cases

1. Open https://getbootstrap.com/docs/5.2/components/modal/ in browser
2. In console execute this:
   ```js
   modal = new bootstrap.Modal(document.querySelectorAll('#exampleModal')[0]) 
   modal.show()
   modal2 = new bootstrap.Modal(document.querySelectorAll('#exampleModal')[0])
   ```
3. Try to close the modal with the `x` button.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.2.2

**Comment by mfazekas** [comment]
Also related to #33727

Note that for this exact case, using `bootstrap.Modal.getOrCreateInstance(...)` instead of `new bootstrap.Modal` works. But in our app the issue is that the modal opened with new bootstrap.Modal(...).show() then a PATCH request is used with unpoly to perform a partial update on the content of the modal, and then we can no longer close the modal. As bootstrap.Modal.getInstance is `null`

**Comment by keshavmittal7974** [comment]
👍
