### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by edlingao** [twbs/bootstrap#37505]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

# A11y not working properly on [Navs and tabs](https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior)

When selecting a new tab-nav button with enter or space, the next element focus should be on the tab-content rather than the next tab-nav button

> References: [[Tabs (W3C)](https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/)](https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/)

### Reduced test cases

- https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior
  - When navigating through the tab options and selecting the next tab button trigger should focus on the content rather than the next nav tab

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.1.3

**Comment by julien-deramond** [comment]
Hi @edlingao
I know that work has been done in the v5.2 on the navs and tabs. Is your issue still there in our latest release? (see https://getbootstrap.com/docs/5.2/components/navs-tabs/#javascript-behavior)

**Comment by edlingao** [comment]
Hi, @julien-deramond thanks for the quick response!

I can see the issue is no longer happening on 5.2 and it is working as expected A11y speaking, thanks!
