### ISSUE TITLE
Release additional minimal version bootstrap-pure.js without jquery support

### ISSUE THREAD

**Issue by nailarch** [twbs/bootstrap#37507]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can you release additional minimal version bootstrap.js without jquery code support?

### Motivation and context

Because more and more developers don't use jquery at all )

**Comment by mdo** [comment]
v5's JS doesn't really include much extra code for jQuery. I don't see much value in this for v5, but what little code is there will be dropped in v6 most likely.
