### ISSUE TITLE
Generating background-color utilities doesn't output the correct value (CSS variable ignored)

### ISSUE THREAD

**Issue by Macxim** [twbs/bootstrap#37517]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The documentation says the following:

```
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";

$all-colors: map-merge-multiple($blues);

$utilities: map-merge(
  $utilities,
  (
    "background-color": map-merge(
      map-get($utilities, "background-color"),
      (
        values: map-merge(
          map-get(map-get($utilities, "background-color"), "values"),
          (
            $all-colors
          ),
        ),
      ),
    ),
  )
);

@import "bootstrap/scss/utilities/api";
```

Output is:

```
.bg-blue-100 {
  --bs-bg-opacity: 1;
  background-color: #cfe2ff !important;
}
```

But expected output should really be:

```
.bg-blue-100 {
  --bs-bg-opacity: 1;
  background-color: rgba(var(--bs-blue-100-rgb), var(--bs-bg-opacity)) !important;
}
```

This is an issue because when doing this, it doesn't work, opacity isn't taken into account.
```
<div class="bg-blue-100 bg-opacity-25"></div>
```

What am I missing here?

### Reduced test cases

I haven't been able to set up a Codepen for this but will try to provide a dedicated repo as soon as possible.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.2

**Comment by mdo** [comment]
For those, you'll need to use the right functions that we use ourselves to convert the hex values to `red, green, blue` so we can consume them in a CSS variable. For example, from `_maps.scss` using `rgba-css-var()` in `map-loop()`:

```scss
$utilities-bg: map-merge(
  $utilities-colors,
  (
    "black": to-rgb($black),
    "white": to-rgb($white),
    "body": to-rgb($body-bg)
  )
) !default;
$utilities-bg-colors: map-loop($utilities-bg, rgba-css-var, "$key", "bg") !default;
```
