### ISSUE TITLE
CSS accent-color property does not work

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#37515]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) CSS property sets the accent color for user-interface controls generated by some elements such as checkboxes and radio button.

I apply this to my stylesheet as:
```css
body {
    accent-color: var(--accentColor);
}
```

At runtime I set the `accentColor` variable used above to a color which depends on what tenant is in use through JavaScript.
```javascript
function setBranding(accentColor) {
  const root = document.querySelector(':root');
  root.style.setProperty('--accentColor', accentColor);
}
```

This worked fine in Bootstrap 4 but no longer works in Bootstrap 5 because the `form-check-input` class sets the `appearance` property to `none`.

### Reduced test cases

https://jsfiddle.net/d9Lt27e8/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.2.2

**Comment by mdo** [comment]
This won't be something we support in v5, but might come as an evolution of the root CSS variables. I thought about adding a `--accent-bg`, `--accent-color`, etc variables, but that's just an alias for `primary` right now and the `$component-` Sass variables. It's a little wonky right now, but hoping to address soon :).
