### ISSUE TITLE
Arbitrary values for margin and padding

### ISSUE THREAD

**Issue by ssakib4040** [twbs/bootstrap#37523]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi Bootstrap. 
I want a feature where I can add custom padding & margin values for example: `mt-[5px]` will add 5 px margin on top or `pb-[10px]` will add 10px padding to bottom.
Thanks

### Motivation and context

I was trying to add custom padding/margin but bootstrap doesn't support this feature yet so.

**Comment by CyrilKrylatov** [comment]
You can already do that by using the `m-` and `p-` class utilities. You can also overide the `$spacer` variable to suits your needs.

You'll find everything you need to know in the [Spacing doc](https://getbootstrap.com/docs/5.2/utilities/spacing/).

**Comment by exactstate** [comment]
I don't think Bootstrap supports this. You can override `$spacer` and add to the `$spacers` sass variable but that's about it.

I would question why you need/want apply styling like this. TailwindCSS does support this which may be better for your use case.

**Comment by julien-deramond** [comment]
You can do the following to have access then in your project to `m-5px` or `m-13px` for example if you don't want to touch the `$spacer` var:

```scss
$utilities: (
  "margin": (
    responsive: true,
    property: margin,
    class: m,
    values: map-merge($spacers,
    (
      auto: auto,
      5px: 5px,
      13px: 13px
    ))
  ),
);
```

But no, it is not possible atm to use arbitrary values (`mt-[5px]`, `m-[123px]`, and so on) on the fly without having introduced them manually before as utilities.

**Comment by mdo** [comment]
Not possible as mentioned above, but if you ever figure out a way with Sass or CSS variables, we're open to ideas!
