### ISSUE TITLE
carousel touch does not work until using arrows

### ISSUE THREAD

**Issue by gartenkralle** [twbs/bootstrap#37546]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

touch of carousel does not work until using arrows

### Reduced test cases

https://codepen.io/gartenkralle/pen/qBKpgOm

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3

**Comment by julien-deramond** [comment]
Can confirm this issue on Android + Firefox as well. Whatever the example in our [Carousel docs](https://getbootstrap.com/docs/5.2/components/carousel/), the user needs to first go to the next slide with the control, and only from there the user can swipe/touch.

**Comment by julien-deramond** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/37354 so closing it

**Comment by bowingman** [comment]
Good job!
