### ISSUE TITLE
Carousel crossfade doesn't fade-out if text is used instead of image

### ISSUE THREAD

**Issue by AnupamKhosla** [twbs/bootstrap#37540]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The official documentation uses svgs in crossfade animation, but in real project when we use text, there is a different behaviour observed. In official docs, when one slide is changed to another, the first slide fades out and the second slide fades in. Instead when we use text in slides, the first slide **doesn't fade out**, but the second slide still fades in. 

There is a css rule `transition: opacity 0s $carousel-transition-duration`, this adds a delay to the opacity transition on first slide and makes the `transition-duration` 0. I don't know why it doesn't affect the svgs used in the official docs, but I have reproduced the bug on my private server: http://sikhwarriors.xyz/docs/5.2/components/carousel/#crossfade-no-svg -- I am using `$carousel-transition-duration: 8s;`, and recompiled bootstrap 5.2 scss, you'll see the text `1111111` not fading out and after 8s it just goes to display none and the second slide text `2222222` fades in.  Strangely enough, the example on top using svgs still have the fade out: http://sikhwarriors.xyz/docs/5.2/components/carousel/#crossfade  

P.S: I tried to use github pages for the demo, but I was not able to correctly sync `root` to my reponame: 
https://anupamkhosla.github.io/bootstrapCarouselFadeBug/
https://github.com/AnupamKhosla/bootstrapCarouselFadeBug

### Reduced test cases

http://sikhwarriors.xyz/docs/5.2/components/carousel/#crossfade-no-svg

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2

**Comment by AnupamKhosla** [comment]
I need to update the variable scss again to 6s transition duraion, please wait. atm the demo is using .6secs instead.

**Comment by patrickhlauke** [comment]
Looking at http://sikhwarriors.xyz/docs/5.2/components/carousel/#crossfade-no-svg i can see the fade behaviour working as expected. Note that for your text examples, you should define an solid background colour for your slides, as it says in the description for crossfades...

> Depending on your carousel content (e.g., text only slides), you may want to add `.bg-body` or some custom CSS to the `.carousel-items` for proper crossfading.

Note: crossfades work by displaying the next slide on top of the currently active slide, making that next slide progressively more opaque. Once the next slide is fully opaque, the underlying slide gets flipped to `display:none`. They don't crossfade by making the current slide less opaque.
