### ISSUE TITLE
Scrollspy doesn't work with Chinese anchor targets

### ISSUE THREAD

**Issue by razonyang** [twbs/bootstrap#37545]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Related issue #10205(v2/v3)
Related issue #36939

```log
bootstrap.bundle.min.js:6 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#%E8%83%8C%E6%99%AF%E5%9B%BE%E7%89%87' is not a valid selector.
    at Object.findOne (https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:9928)
    at bn._initializeTargetsAndObservables (https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:73068)
    at bn.refresh (https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:71320)
    at new bn (https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:71193)
    at bn.getOrCreateInstance (https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:8197)
    at https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:74122
    at i (https://cdn.jsdelivr.net/gh/twbs/bootstrap@main/dist/js/bootstrap.bundle.min.js:6:4253)
```

### Reduced test cases

https://codepen.io/razonyang/pen/poKKWEK

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.3

**Comment by asyncdesign** [comment]
You have to follow the W3C selector rules as defined below:

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

In CSS, identifiers (including element names, classes, and IDs in [selectors](https://www.w3.org/TR/CSS21/selector.html)) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

**Comment by mdo** [comment]
Closing per above comment.

**Comment by JadynWong** [comment]
I hope this issue can be reconsidered

Based on #10205 have a different opinion

https://dev.w3.org/html5/spec-LC/elements.html#the-id-attribute
https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute
