### ISSUE TITLE
Race Condition in Grunt for Bootstrap 3.4

### ISSUE THREAD

**Issue by divya002** [twbs/bootstrap#37541]
There is security vulnerabilities issue with **bootstrap 3.4** because its using **grunt version less than 1.5.3.**

Please go through this below link for details
https://github.com/advisories/GHSA-rm36-94g8-835r

Please suggest to fix this issue.

**Comment by julien-deramond** [comment]
Thanks for opening this issue @divya002 but Bootstrap 3 reached its end of life in 2019 (source: https://github.com/twbs/release#release-schedule).
