### ISSUE TITLE
Select arrow doesn't hide the content when direction is different

### ISSUE THREAD

**Issue by MauricioFauth** [twbs/bootstrap#37567]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![Screenshot from 2022-11-30 11-16-19](https://user-images.githubusercontent.com/120970/204820721-356d323e-d9c2-4f58-bfe2-f1096e2e10d0.png)

![Screenshot from 2022-11-30 11-18-30](https://user-images.githubusercontent.com/120970/204820750-69943df4-6f4c-46e7-98ce-106242e03bb7.png)

### Reduced test cases

The page and Bootstrap are LTR and the select field is RTL:

```html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
  <div class="container mt-3">
    <h1>Bootstrap LTR</h1>
    <div class="mb-3" style="width: 200px;">
      <label for="exampleSelect" class="form-label">Select menu LTR</label>
      <select class="form-select" id="exampleSelect">
        <option selected>Open this select menu</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
      </select>
    </div>
    <div class="mb-3" dir="rtl" style="width: 200px;">
      <label for="exampleSelect2" class="form-label">Select menu RTL</label>
      <select class="form-select" id="exampleSelect2">
        <option selected>Open this select menu</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
      </select>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>
```

The page and Bootstrap are RTL and the select field is LTR:

```html
<!doctype html>
<html lang="en" dir="rtl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css" integrity="sha256-+bNAolFvt6YB2LgXdEQJhKQUw4T0XbrBxLf0lH4NYDo=" crossorigin="anonymous">
  </head>
  <body>
  <div class="container mt-3">
    <h1>Bootstrap RTL</h1>
    <div class="mb-3" style="width: 200px;">
      <label for="exampleSelect" class="form-label">Select menu RTL</label>
      <select class="form-select" id="exampleSelect">
        <option selected>Open this select menu</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
      </select>
    </div>
    <div class="mb-3" dir="ltr" style="width: 200px;">
      <label for="exampleSelect2" class="form-label">Select menu LTR</label>
      <select class="form-select" id="exampleSelect2">
        <option selected>Open this select menu</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
      </select>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.2.3

**Comment by julien-deramond** [comment]
Hey @MauricioFauth

In order to make it work in RTL you also need to include `bootstrap.rtl.min.css` instead of `bootstrap.min.css` (see [Getting started > RTL > Required HTML](https://getbootstrap.com/docs/5.2/getting-started/rtl/#required-html))
Here is [a CodePen](https://codepen.io/julien-deramond/pen/yLqMNKV) showing that the rendering is OK in RTL as well.

I'm closing it for now. Don't hesitate to add comments if my answer doesn't cover what was reported in the issue.

**Comment by ffoodd** [comment]
This is the expected result for v5 since RTL and LTR are different builds. They aren't meant to be used at the same time, even though [it's possible with some edge cases](https://getbootstrap.com/docs/5.2/getting-started/rtl/#ltr-and-rtl-at-the-same-time). It's not a good idea since it requires to load both builds, final CSS gets really heavy.

V6 should allow us to drop RTLCSS and use logical properties, which would solve the kind of issues you're facing.

**Comment by MauricioFauth** [comment]
Thank you, @ffoodd and @julien-deramond. 
Makes sense. This edge case is not worth the trade-off as this can be fixed with custom CSS.
You can close this issue.
