### ISSUE TITLE
Alignment issue with form-select/floating label

### ISSUE THREAD

**Issue by lcsqlpete** [twbs/bootstrap#37564]
I have a couple of issues showing up when using a form-select with floating labels inside a modal. Here's a screenshot of the issue.

![Screen Shot 2022-11-29 at 5 19 23 PM](https://user-images.githubusercontent.com/8495380/204684238-ab3a4ab0-0d55-4fb7-801e-8d321c845954.png)

The left side of the Product select control on the last row is slightly off compared to the left side of of all the other controls above it even though they have the same offset. IN addition the Product select is not as wide as the other inputs even though they have the same col specs.

If I move the Product select to appear on the row after the Location name input, both issues go away. I've attached a file of the complete html for the page.

[BS5 issue.txt](https://github.com/twbs/bootstrap/files/10118543/BS5.issue.txt)

**Comment by mdo** [comment]
This needs to be a reduced test case with a live demo, not a comprehensive text file that doesn't isolate the issue within our code base. I'm going to close this out for now, but please feel free to comment or open a new issue once you're able to provide that. Please read through our issue template for reporting bugs as well—it mentions all of this. Thanks!
