### ISSUE TITLE
d-none on option element does not work on iOS

### ISSUE THREAD

**Issue by lcsqlpete** [twbs/bootstrap#37585]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

THe html in the reference codepen woks on OSX and mobile devices but Chrome and Safari on iOS devices display the option elements of the Track and Ceiling select elements with d-none class.  I'm guessing this is an iOS issue but need to check here first.

### Reduced test cases

Codepen is at https://codepen.io/lcsqlpete/pen/dyKwbRK

I'm not sure pointing an iOS browser to codepen will show the issue.  If not please copy the html into a file and point your iOS browser to it.

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

5.1.2

**Comment by julien-deramond** [comment]
Thank you for opening this issue @lcsqlpete.
Just tried on a simulator with iPhone 14 + Chrome and the input with its associated `d-none` is not displayed (so the feature works as expected).
Could you please provide a specific iOS version and Chrome or Safari versions as well?

**Comment by lcsqlpete** [comment]
I tried it on an iPhone 7 with iOS 15.7.1.  My understanding is that the Safari version is the same as the iOS version but please correct me if I'm wrong.

I just tried the codepen running on the iPhone 7 and the the d-none does not work.
