### ISSUE TITLE
npm bootstrap@next (for next 5.3 release)

### ISSUE THREAD

**Issue by marceloverdijk** [twbs/bootstrap#37588]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

It would be nice to have `next` tag in the [npm registry](https://www.npmjs.com/package/bootstrap?activeTab=versions) to easily start working/trying with Bootstrap `5.3`.

Note this should not be limited to `5.3` and after it's release move forward to next version.

Currently I see only a `next-5` which points to `5.2.0-beta1`.

This proposal is to maintain a proper `next` tag in npm registry.

### Motivation and context

This way we can always keep up with the latest (unreleased) Bootstrap development using it as a npm dependency.

**Comment by XhmikosR** [comment]
`npm i bootstrap@5.3.0-alpha1` or `@next-5`

**Comment by marceloverdijk** [comment]
Just wondering, will `@next-5` updated automatically (taking latest) or manually on a regular basis?

**Comment by XhmikosR** [comment]
No, `next-5` will not point to `latest`. It's for testing releases only. But if `alpha2` is out, I'll update the tag too.

**Comment by marceloverdijk** [comment]
Clear and makes sense. Just wanted to know how it will be used.
