### ISSUE TITLE
No published NuGet version for 5.2.3 release

### ISSUE THREAD

**Issue by phenning** [twbs/bootstrap#37599]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I didn't see a more appropriate way to report this, but there is no 5.2.3 release published to NuGet. The last version published is 5.2.2

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.2.3

**Comment by supergibbs** [comment]
Sorry for the delay, I was traveling. This is updated now and can be closed.
