### ISSUE TITLE
spinner-border not spinning in webkit or iOS webviews

### ISSUE THREAD

**Issue by jertje260** [twbs/bootstrap#37606]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

We have a simple spinner-border. This spins fine in any browser & in a webview on android, however on iOS it doesn't spin.

I was able to reproduce this issue on windows using webkit from [Playwright](https://playwright.dev/docs/browsers) (through Cypress). This displayed the exact same behaviour as experienced in the iOS webview.

I'm not 100% sure if this is a bootstrap or a webkit bug. I was able to fix it by adding the `from` part in the keyframes

### Reduced test cases

You can find the codepen here: 
https://codepen.io/jertje260/pen/MWXLqZx

### What operating system(s) are you seeing the problem on?

Windows, iOS

### What browser(s) are you seeing the problem on?

Webkit based (WKWebView & Playwrights Webkit)

### What version of Bootstrap are you using?

v4.3.1, but on v5.2.x its also not working

**Comment by mdo** [comment]
Seems to work just fine for me. Could be reduced motion? Or a bug in whatever tool you're using?
