### ISSUE TITLE
Add `.text-small` and `.text-big` CSS classes

### ISSUE THREAD

**Issue by RogierVC** [twbs/bootstrap#37605]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Text styling classes, like `.text-end` and `.text-muted` have a prefix of `.text-` because they're about text. `.text-small` and `.text-big` are also text styling classes and should also be accepted. Instead of using `.small` and `.big`, which are not consistent with other text styling classes.

### Motivation and context

I understand `small` and `big` are HTML elements and therefore deserve separate classes without a prefix like `.text-` but in my opinion this isn't consistent with the rest of the text styling classes. When styling text, I often make this mistake by already typing `text-small` as a CSS class.

I'm happy to make a PR for this, if people agree.

**Comment by UnfixedSun** [comment]
Should we change the existing .small and .big file or is it recommended that I create .text-small or .text-big file.

**Comment by julien-deramond** [comment]
For future selves, let's not forget our `<mark>` which has `.mark` as a style alias as well and so that follows the same logic as `<small>` and `.small`.
