### ISSUE TITLE
$input-bg must be a string in latest Bootstrap version

### ISSUE THREAD

**Issue by robinheidrich** [twbs/bootstrap#37620]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I installed the Bootstrap GitHub repository via npm to try darkmode.

If I change the `$input-bg` in my `_variables.scss` to `#fff` I get the following error message:

```
[plugin:vite:css] [sass] $string: #fff is not a string.
    ╷
132 │   @if str-index($string, "data:image/svg+xml") {
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\bootstrap\scss\_functions.scss 132:7            escape-svg()
  node_modules\bootstrap\scss\forms\_form-check.scss 30:32     @import
  node_modules\bootstrap\scss\_forms.scss 5:9                  @import
```

This is not the case in the current Bootstrap version, so I assume it is a bug.

### Reduced test cases

The problem occurs in SCSS therefore I could not create a working test case on CodePen.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3 (main branch)

**Comment by julien-deramond** [comment]
Thanks for the feedback @robinheidrich. I'm adding it into our https://github.com/twbs/bootstrap/issues/37549 to take a look at it :)
