### ISSUE TITLE
box-shadow did not come out in the buttons, that is

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [twbs/bootstrap#37646]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello! It would be nice if we corrected the Bootstrap in version 5.2.3 that box-shadow did not come out in the buttons, that is, there is a bug that is not working.

![image](https://user-images.githubusercontent.com/83509440/207595893-7de14d5a-b709-463e-a01f-fe6b56420ab9.png)

### Reduced test cases

![image](https://user-images.githubusercontent.com/83509440/207596365-efaf96ee-3d08-493b-8e2a-da2b6cddb4cc.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3

**Comment by julien-deramond** [comment]
There's no more box shadow when the button are focused (mouse). Please check [the blog article of the v5.2.1](https://blog.getbootstrap.com/2022/09/07/bootstrap-5-2-1/) and https://github.com/twbs/bootstrap/pull/37026.
