### ISSUE TITLE
`modal.hide()` not work

### ISSUE THREAD

**Issue by posilya** [twbs/bootstrap#37645]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

```js
let solved_modal = document.getElementById("solved-modal");
// ...
let modal = new bootstrap.Modal(solved_modal);
modal.hide();
```
And modal not hidden. I tried to do this in DevTools, it didn't work either.
And I tried to do so, it didn't work either:
```js
let modal = new bootstrap.Modal("#solved-modal");
modal.hide();
```

### Reduced test cases

https://codepen.io/posilya/pen/mdKZaQZ

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.2

**Comment by priyashpatil** [comment]
Also Offcanvas not working. Toggle method is also now working.

**Comment by priyashpatil** [comment]
It doesn’t work when creating Js instances under a function: 
```js
    <script>
      function toggleOffcanvas() {
        const bsOffcanvas = new bootstrap.Offcanvas("#offcanvasExample");
        bsOffcanvas.hide();
      }

      function toggleModal() {
        const bsModal = new bootstrap.Modal("#exampleModal");
        bsModal.hide();
      }
    </script>
```

But the following works:
```js
    <script>
      const bsOffcanvas = new bootstrap.Offcanvas("#offcanvasExample");
      const bsModal = new bootstrap.Modal("#exampleModal");
      
      function toggleOffcanvas() {
        bsOffcanvas.hide();
      }

      function toggleModal() {
        bsModal.hide();
      }
    </script>
```

**Comment by patrickhlauke** [comment]
i'll hazard a guess that what you want to do is `getInstance` for the modals that are already created (in those functions, which presumably execute later, once those modals have already been instantiated), rather than defining them/instantiating them as new modals?

**Comment by posilya** [comment]
@patrickhlauke thank you very much, everything worked!
