### ISSUE TITLE
breakpoint xs

### ISSUE THREAD

**Issue by andreas-web** [twbs/bootstrap#37652]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

What about an additional breakpoint e.g. at 380px?

### Motivation and context

Very often we have the problem that we have to design pages for small smartphones like iPhone SE. Unfortunately, the smallest breakpoint at 576px offers too much leeway, so it either looks good at 500px or at 300px but not at both.

**Comment by mdo** [comment]
No plans to add this ourselves, but you can by modifying the Sass map.
