### ISSUE TITLE
I'm following step by step guidelines for a workshop and the link I am using in Bootstrap isn't working. CSS isnt working on any project I have submitted thus far. 

### ISSUE THREAD

**Issue by tvr3n33** [twbs/bootstrap#37653]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I thought it was a user problem but as I follow Matt's solutions on SheCodes. I am still not getting the results needed to pass my courses.

I believe I have acquired a bug and need assistance to move forward with my courses before I fall too far behind.

### Reduced test cases

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link ref="stylesheet" href="src/styles.css" />
    <title>Sandbox Parcel</title>
  </head>
  <body>
    <div class="container">
      <h1>Hello World</h1>
    </div>
  </body>
</html>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5

**Comment by mdo** [comment]
Works fine for me. https://codepen.io/emdeoh/pen/poKMOeJ

**Comment by tvr3n33** [comment]
I understand it works for you but I am still not getting results through this link... why would that be?

**Comment by tvr3n33** [comment]
> Works fine for me. https://codepen.io/emdeoh/pen/poKMOeJ

I tried your exact replica and computer did not respond the same. What would that mean?

**Comment by tvr3n33** [comment]
My CSS is refusing any commands for styling. This has happened now in multiple projects with bootstrap. Why would this be an issue? Do I need to start my computer over? Someone commented back that the link was working fine for them, yet they styled "hello world" blue without any CSS which left me confused.

I am not tech savvy. Pointed comments won't be useful. I need babysitting as this is my first workshop outside of basic HTML and CSS.

**Comment by mdo** [comment]
First off, super cool you're learning all this—major props! But this isn't the best place to get help on learning the ins and outs of HTML and CSS. Hopefully there are resources from the course you're doing.

What are you trying to do exactly? The demo I linked to just shows some text that's colored blue via what we call a "utility class" in the HTML. That's just a fancy phrase for a class that does one thing, in this case make something blue.
