### ISSUE TITLE
 pagination  components not support RTL

### ISSUE THREAD

**Issue by asfarmed** [twbs/bootstrap#37668]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When pagination  is used, the first and last page-item border-radius appear in reverse
![Screenshot_12](https://user-images.githubusercontent.com/6324103/208268124-a7012f9c-5a77-4f3d-968d-6aa14b824056.png)

### Reduced test cases

```
<div class="bd-example" style="direction: rtl;">
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">السابق</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">التالي</a></li>
  </ul>
</nav>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.x.x 5.2

**Comment by ffoodd** [comment]
Setting `direction` in CSS is not enough to use Bootstrap RTL: you need to use `bootstrap.rtl.css` file. Please read [RTL docs page](https://getbootstrap.com/docs/5.2/getting-started/rtl/) to get started.

**Comment by julien-deramond** [comment]
Closing it based on the answer provided in https://github.com/twbs/bootstrap/issues/37668#issuecomment-1356621814. The rendering in our [RTL cheatsheet example page](https://getbootstrap.com/docs/5.2/examples/cheatsheet-rtl/#pagination) seems OK.
