### ISSUE TITLE
Setting $color-mode-type to media-query (rather than data) causes a Sass compilation erro

### ISSUE THREAD

**Issue by RichDeBourke** [twbs/bootstrap#37673]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I downloaded the Bootstrap GitHub repository (version from 12/19/2022) to try dark mode.

Compiling Sass with the default value (data) compiles successfully (I’m using Glenn Marks’ Live Sass Compiler for VS Code).
     `$color-mode-type:             data !default;`

If I set $color-mode-type to `media-query` (overriding the default data) in my _site_variables.scss file, the compiler generates the following error:

```
Compilation Error
Error: Declarations may only be used within style rules.
    ╷
135 │     --#{$prefix}body-color: #{$body-color-dark};
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  c:\wamp64\www\f3-5\node_modules\bootstrap\scss\_root.scss 135:5             @content
  c:\wamp64\www\f3-5\node_modules\bootstrap\scss\mixins\_color-mode.scss 5:7  color-mode()
  c:\wamp64\www\f3-5\node_modules\bootstrap\scss\_root.scss 133:3             @import
  c:\wamp64\www\f3-5\src\scss\style.scss 25:9                                 root stylesheet
--------------------
```
I was expecting to have the Sass output something like:
```
@media (prefers-color-scheme: dark) {
    :root {
        --bs-body-color: #adb5bd;
    }
}
```

### Reduced test cases

I don't have a suggested fix and I'm not sure how to do a test case since this version (5.3.0?) is available on a CDN yet.

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks a lot @RichDeBourke for having created this issue. I can confirm the issue. I'll try to provide a patch before the 5.3.0 alpha is released.

@mdo I'm adding in the task lists to try to add something in our automatic build to check that. Otherwise, we will probably introduce some other bugs in the future.
