### ISSUE TITLE
Dark mode polyfills

### ISSUE THREAD

**Issue by kodz1** [twbs/bootstrap#37688]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Will dark mode provide support for inputs that are generated by the browser such as datalist, input type="range", or input type="date"?

Current example at https://deploy-preview-35857--twbs-bootstrap.netlify.app/ from https://github.com/twbs/bootstrap/pull/35857 does not seem to support date, but have not played around with the others.

### Motivation and context

Currently most browser will switch browser to dark colour scheme if the operating system is in dark mode, but implementation can vary wildly which not great for user experience.

**Comment by mdo** [comment]
At present, no plans to do that, but I get the concern. We'll keep an eye on options for that.
