### ISSUE TITLE
Search stopped from inside the doc - V5.3

### ISSUE THREAD

**Issue by ahmed-menisy** [twbs/bootstrap#37708]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The search feature inside the doc has stopped 
With the release of version 5.3

### Reduced test cases

https://getbootstrap.com/docs/5.3/getting-started/introduction/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
Fixed. Had to manually recrawl the docs for Algolia.
