### ISSUE TITLE
Add color-scheme for dark mode

### ISSUE THREAD

**Issue by robinheidrich** [twbs/bootstrap#37710]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap should make use of `color-scheme` to display browser elements (scrollbar, select, etc.) in dark mode as well.

### Motivation and context

Here's a preview of what scrollbars currently look like in the Bootstrap documentation, and what they would look like if color scheme were used.

![image](https://user-images.githubusercontent.com/23118399/209453066-def0ad19-d160-4d5a-a539-47fcb654d176.png)
![image](https://user-images.githubusercontent.com/23118399/209453068-55479b03-8bc0-4183-b8f7-8c28a8e36635.png)

**Comment by mdo** [comment]
We just shipped color mode support in v5.3.0.

**Comment by coliff** [comment]
@mdo I think this is a valid issue. Dark mode in Bootstrap 5.3 alpha doesn't currently add the colour-scheme so UI elements are not dark (see screenshots in original post)

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

**Comment by ffoodd** [comment]
Agreed, `color-scheme` is basically a global `accent-color` for browser UI, and makes thé overall color modes smoother.

**Comment by mdo** [comment]
Oh, my bad! I didn't see the second image, thanks for reopening fam :).

**Comment by mdo** [comment]
Do we just need to add `color-scheme: dark` to the `:root` for dark mode? I'm unclear of what's in scope for the changes coming from the property's inclusion. I see scrollbars change when I use it, but the `<select>` menu when shown doesn't change from light to dark. Am I missing something?

**Comment by coliff** [comment]
> Do we just need to add `color-scheme: dark` to the `:root` for dark mode? I'm unclear of what's in scope for the changes coming from the property's inclusion. I see scrollbars change when I use it, but the `<select>` menu when shown doesn't change from light to dark. Am I missing something?

It affects a few other things too, such as browser-based autofill which typically changes the background of a form inout to indicate to the user that it was autofilled. Here's a quick example from the docs which autofilled on email address of mine (Edge v108 on macOS). If the CSS had specified `color-scheme: dark` then the autofill background would have been dark to better match the theme.

<img width="1190" alt="Untitled" src="https://user-images.githubusercontent.com/1212885/209646032-dac413cd-6298-4923-95ee-3252874d8edb.png">

**Comment by julien-deramond** [comment]
Let's try a PR to add `color-scheme` for light and dark color modes (not 100% sure because haven't tried it yet but probably to the `:root`).

We must double-check everything in this PR:
* Behavior with default `$color-mode-type` and when set to `media-query`
* All elements that can be rendered differently: scrollbars, inputs (with autofill and/or options), textareas, selects, etc. (don't have an exhaustive list yet 😄)
* Browsers/OSs compatibility; some browsers seem to handle it better than others even without `color-scheme`

**Comment by mdo** [comment]
See #37734.
