### ISSUE TITLE
Dark Mode: `btn-outline-dark` is not visible and `btn-dark` has no border for user discoverability

### ISSUE THREAD

**Issue by jadeops** [twbs/bootstrap#37711]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

* Bug 1 : `btn-outline-dark` https://getbootstrap.com/docs/5.3/components/buttons/#outline-buttons from example code

![Peek 2022-12-25 14-25](https://user-images.githubusercontent.com/85561678/209462221-0f5d4137-90a1-4c83-ab11-dbdf9044ab4e.gif)

* Bug 2:  `btn-dark` in dark mode needs a border I think. How would the user know it is a button? https://getbootstrap.com/docs/5.3/components/buttons/ 

![Peek 2022-12-25 14-29](https://user-images.githubusercontent.com/85561678/209462310-4c6d7a7b-dfe3-45f3-86eb-849e27238829.gif)

### Reduced test cases

See above 

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0-alpha

**Comment by mdo** [comment]
This is intentional for now, as you've mentioned :).
