### ISSUE TITLE
Missing box-sizing:border-box style in self compiled css v5.2.3

### ISSUE THREAD

**Issue by mrunalpittalia** [twbs/bootstrap#37721]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am using bootstrap 5.2.3 version & had  some strange issue with grid. I was getting horizontal scroll bar in browser while implementing nested grid columns.

When I compared with precompiled version & example of grid at bootstrap docs, I found below specific style in bootstrap docs site's loaded bootstrap.min.css but missing in my self compiled using webpack.

When I looked at npm installed package bootstrap 5.2.3 package, I found it in all precompiled css files but it has no mention in scss files which are using self compiled version.

`*,::after,::before{box-sizing:border-box}`

Adding it in webpage independently, it solved my scrollbar & over width issue of container.
Sorry If I am missing any more technical information, you can ask me anytime!

Is there anything I am doing wrong Or there is anything really missing at bootstrap@5.2.3

### Reduced test cases

@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";

$body-color: #005487;
$app_lblue : #00A1DF;

$custom-colors: (
    "app_lblue": $app_lblue,
    'white'    : $white,
    'black'    : $black,
);
$theme-colors: map-merge($theme-colors, $custom-colors);
$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
@import "~bootstrap/scss/maps";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/utilities";
@import "~bootstrap/scss/root";

$tooltip-bg     : #8C8989;
$tooltip-opacity: 1;
$enable-rounded              : false;
$enable-shadows              : true;
$enable-gradients            : true;
$enable-responsive-font-sizes: true;
$input-focus-box-shadow      : 0 0 0;

$link-color        : $app_lblue;
$table-border-color: $app_lblue;
$hr-border-color   : $app_lblue;
$border-color      : $app_lblue;
$input-border-color      : $app_lblue;
$input-focus-border-color: $app_lblue;
$input-color             : $app_lblue;
$input-plaintext-color   : $app_lblue;
$input-focus-color       : $app_lblue;
$input-placeholder-color : $secondary;
$form-check-input-checked-bg-color : $app_lblue;

@import 'bootstrap/scss/bootstrap';
@import "~@fortawesome/fontawesome-free/css/all.min.css";

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.3

**Comment by julien-deramond** [comment]
Hey @mrunalpittalia.

If I understand this issue correctly, what you're looking for is in https://github.com/twbs/bootstrap/blob/492187de6468efe8ac774ff25f00522181364af1/scss/_reboot.scss#L16-L20.

You can find some help in [Customize > Sass documentation](https://getbootstrap.com/docs/5.2/customize/sass/#importing) where it is recommended to also include `reboot` which seems to be missing in your reproducible example.

You need to remove `import 'bootstrap/scss/bootstrap';` as well since you've chosen to import things yourself.

**Comment by mrunalpittalia** [comment]
Hey Juliean,

Thanks for quick action!
I will make changes & respond here in next few hours.

**Comment by mdo** [comment]
Including Reboot is the right move here, it's where we set box-sizing as mentioned by @julien-deramond. Either include that stylesheet or your own box-sizing.

**Comment by mrunalpittalia** [comment]
Yeah, the suggestion worked fine.

Can be closed now
