### ISSUE TITLE
Styling Password Fields

### ISSUE THREAD

**Issue by maroufali** [twbs/bootstrap#37732]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Better readability of the password field for the dots with basic CSS styling. 
It will be easier to see the number of each dot in the field.

`input[type='password'] {
    font-family: Verdana;
    letter-spacing: 0.14em;
}`

### Motivation and context

It is a lot easier to see the individual dots and separate it nicely with more spaces in the field.

**Comment by mdo** [comment]
Thanks, but we'll pass on making any changes there.
