### ISSUE TITLE
Unclear dockality

### ISSUE THREAD

**Issue by wojtekxtx** [twbs/bootstrap#37744]
https://github.com/twbs/bootstrap/blob/993ad97fdc0bcbc0fb63dcafb466f81e5be004e6/dist/css/bootstrap-utilities.css#L715

End of what?

**Comment by julien-deramond** [comment]
[Utilities > Position > Arrange elements](https://getbootstrap.com/docs/5.3/utilities/position/#arrange-elements)

**Comment by wojtekxtx** [comment]
@julien-deramond thanks man :) Appreciate
