### ISSUE TITLE
Bootstrap 5: Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.

### ISSUE THREAD

**Issue by guillaumebriday-pa** [twbs/bootstrap#37749]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm trying to upgrade my app from Bootstrap 4 to 5

I have something like that in my JS:

```js
  $('body').tooltip({
    selector: '[rel=tooltip], [rel*=tooltip]',
    html: false,
    animation: false,
    trigger: 'hover'
  })

  $('body').popover({
    selector: '[rel=popover], [rel*=popover]',
    html: true,
    trigger: 'hover',
    animation: false
  })
```

It works perfectly fine in BS4 but I got an error in BS5:
```
Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.
```

I use this syntax because I add a lot a element in the DOM dynamically with Rails-ujs and Hotwire.

According to the doc:
<img width="838" alt="Screenshot 2022-12-28 at 12 16 46" src="https://user-images.githubusercontent.com/89008587/209848830-e6232bac-d590-43ce-8bd4-f13e4c82be9c.png">

And this https://codepen.io/Johann-S/pen/djJYPb

We should be able to attach multiple instances to body in this case no?

The problem is that this error block the code after

Thanks you in advance

### Reduced test cases

https://codepen.io/guillaumebriday/pen/PoBZLPd

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.2.x

**Comment by mdo** [comment]
The error message is correct—this is to prevent issues where say you want to put a tooltip and popover on a single button. You can only have one hover interaction on those, for instance.

I imagine you could do something like we do in our docs instead of attaching things to the body like that:

https://github.com/twbs/bootstrap/blob/1a043b55bcfe3b9b1f327fe78639b82321f38633/site/assets/js/snippets.js#L20-L27

**Comment by guillaumebriday-pa** [comment]
I get it, but how do you deal with elements that are added in the DOM dynamically in AJAX or JS?
