### ISSUE TITLE
Different padding for selects on Firefox

### ISSUE THREAD

**Issue by enogael** [twbs/bootstrap#37748]
Hi, maybe there's already an open issue for this, but I couldn't find anything.

This is directly related to this fix [#32636](https://github.com/twbs/bootstrap/issues/32636) that removes some padding on `<select>` specifically for Firefox with a negative `-moz-padding-start`.

But it seems this bug has been addressed in Firefox, and now there isn't enough padding ?

Screenshots from the docs either in 5.2 or 5.3 :
![select](https://user-images.githubusercontent.com/92934165/209842470-64da9022-1ae3-4ad0-a81a-1c00dcf2bf99.png)
![floating-label-select](https://user-images.githubusercontent.com/92934165/209842472-221fbe93-46e9-496c-9a32-21ad54026149.png)

Thanks for looking into it :)

**Comment by mdo** [comment]
@julien-deramond I think Firefox shipped an update to address their padding issue. Wondering if we should remove that custom override now?
