### ISSUE TITLE
Docs: callouts have horribly low contrast

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#37745]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the new docs, info and warning callouts have text colour contrast that's below minimum 4.5:1 threshold.

### Info callout

![info callout](https://user-images.githubusercontent.com/895831/209829848-fd457bd6-3d5b-4fd5-a6d2-e14ca7fc1741.png)

Text: `#087990`
Background: `#CFF4FC`
Contrast: 4.34:1

---

Link: `#0D6EFD`
Background: `#CFF4FC`
Contrast: 3.86:1

---

Code: `#D63384`
Background: `#CFF4FC`
Contrast: 3.86:1

### Warning callout

![warning callout](https://user-images.githubusercontent.com/895831/209829864-f0c0fb68-0d0b-4c7b-85a2-b1bba19af8c0.png)

Text: `#997404`
Background: `#FFF3CD`
Contrast: 3.9:1

---

Link: `#0D6EFD`
Background: `#FFF3CD`
Contrast: 4.06:1

---

Code: `#D63384`
Background: `#FFF3CD`
Contrast: 4.06:1

### Reduced test cases

https://getbootstrap.com/docs/5.3/components/popovers/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
Overall colors and their links in default light mode are good now in `main`.

<img width="330" alt="CleanShot 2023-01-01 at 22 15 29@2x" src="https://user-images.githubusercontent.com/98681/210199716-6a9d13d8-10e2-4eb1-b1a7-d9422325a5b2.png">

<img width="331" alt="CleanShot 2023-01-01 at 22 17 20@2x" src="https://user-images.githubusercontent.com/98681/210199810-d7a58ad5-2985-43d4-9289-d26aa11697a8.png">

Pushing a PR to address the code color though, which will look like this:

<img width="817" alt="CleanShot 2023-01-01 at 22 22 53@2x" src="https://user-images.githubusercontent.com/98681/210200071-a397a2dd-e892-4a34-aa53-6504f4defc0c.png">

<img width="828" alt="CleanShot 2023-01-01 at 22 22 36@2x" src="https://user-images.githubusercontent.com/98681/210200072-eef08ace-5391-4626-93c3-933a160fb86e.png">

**Comment by patrickhlauke** [comment]
lovely, thank you!
