### ISSUE TITLE
NPM: `_variables-dark.scss` is missing 

### ISSUE THREAD

**Issue by teaca-sebastian** [twbs/bootstrap#37756]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Tried using the import boilerplate from https://getbootstrap.com/docs/5.3/customize/sass/#importing but it wouldn't work because of this error:

`@import "../node_modules/bootstrap/scss/variables-dark";`

![image](https://user-images.githubusercontent.com/120113707/209961399-dc048a2b-6d90-45a3-b088-90e6098aa9c4.png)

After thorough investigation I've found that the npm package is missing the `_variables-dark.scss`, while the github repo has it.

![Screenshot_20221229_034157](https://user-images.githubusercontent.com/120113707/209962090-8e5a7e6c-6a51-49d6-9b37-b0042502c3af.png)

![image](https://user-images.githubusercontent.com/120113707/209962060-eb685aac-5b3a-4e66-8c64-336eef08caf9.png)

### Reduced test cases

See above

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment]
> After thorough investigation I've found that the npm package is missing the _variables-dark.scss, while the github repo has it.

Are you using it with `bootstrap@latest` (5.2) or `bootstrap@next-5` (5.3.0-alpha1). Only the alpha contains this new SCSS file.

**Comment by teaca-sebastian** [comment]
> > After thorough investigation I've found that the npm package is missing the _variables-dark.scss, while the github repo has it.
> 
> Are you using it with `bootstrap@latest` (5.2) or `bootstrap@next-5` (5.3.0-alpha1). Only the alpha contains this new SCSS file.
> 
> ```
> ߷ /tmp ➤ npm i bootstrap@next-5
> ߷ /tmp ➤ ls node_modules/bootstrap/scss/_variables-dark.scss                                                                                                                                    
> node_modules/bootstrap/scss/_variables-dark.scss
> ```

`
{
  "dependencies": {
    "bootstrap": "^5.2.3"
  }
}`

**Comment by julien-deramond** [comment]
OK so you need to follow the corresponding version of the docs: https://getbootstrap.com/docs/5.2/customize/sass/#importing.
The link you provided in the description (that mentions __variables-dark.scss_) is for the new alpha version (`5.3.0-alpha1`).
