### ISSUE TITLE
Text on cards don't respect data-bs-theme

### ISSUE THREAD

**Issue by kusma** [twbs/bootstrap#37765]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When setting `data-bs-theme` to `dark` on a Card, the background color changes, but not the foreground colors.

I'd expect either neither or both to change.

### Reduced test cases

https://codepen.io/kusma/pen/ZEjWxyb

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.0-alpha1

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @kusma.
Indeed your live example only works when `data-bs-theme="dark"` is set to `<html>` but not contextually 🤔 
I haven't looked at why yet but it definitely need to be fixed.
