### ISSUE TITLE
Dropdowns not working even after being initialized

### ISSUE THREAD

**Issue by VottusCode** [twbs/bootstrap#37773]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I initialized the dropdowns (using the `.dropdown-toggle` selector), based on the example in the docs, yet it does not work when I click on it. There are no errors or anything.

### Reduced test cases

JS:

```js
import { Dropdown } from "bootstrap";

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll('.dropdown-toggle').forEach(el => new Dropdown(el))
})
```

HTML:

```html
<div class="dropdown">
  <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Sort By
  </button>
  <div class="dropdown-menu dropdown-menu-end">
    <a class="ajax dropdown-item" type="button">Created at</a>
     <a class="ajax dropdown-item" type="button">Title</a>
   </div>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.3

**Comment by GeoSot** [comment]
For sure, you can try 

```js
const inst = bootstrap.Collappse.getOrCreateInstance('yourSelector')
inst.toggle()

```
