### ISSUE TITLE
Docs: light mode code snippets have very low contrast

### ISSUE THREAD

**Issue by teaca-sebastian** [twbs/bootstrap#37770]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The title describes the issue well enough. It happened that I had light mode on, and this one JS snippet I've come across really made me squeeze my eyes because it was hard to distinguish the comments from actual code. Although dark mode has really nice contrast, some people might prefer lightmode.

![image](https://user-images.githubusercontent.com/120113707/210086647-d5796b05-8dcd-46ff-9d63-a1251c8f8edc.png)
![image](https://user-images.githubusercontent.com/120113707/210087150-72c5a333-b80e-4dd6-b005-1c0e667ac6c6.png)

### Reduced test cases

Any snippet on light mode, including HTML and CSS.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment]
Thx for the feedback @teaca-sebastian.
It actually changed in the v5.2
* https://getbootstrap.com/docs/5.2/components/modal/#live-demo
* https://getbootstrap.com/docs/5.1/components/modal/#live-demo

In v5.1, maybe the content was a little more contrasted. Let's see maybe if we can improve that.
/cc @mdo
