### ISSUE TITLE
Get an error anytime I try to use Tabs show() method

### ISSUE THREAD

**Issue by counteragent** [twbs/bootstrap#37845]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Trying to programmatically show a tab using javascript:
`bootstrap.Tab.getInstance(document.getElementById('#tab_4')).show()`

I get the following error.
`Uncaught TypeError: Cannot read properties of null (reading 'show')`

### Reduced test cases

Recreated the issue here on Codepen https://codepen.io/counteragent/pen/VwBpaZQ

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.2

**Comment by julien-deramond** [comment]
In your CodePen, it's rather `getElementById("profile-tab-pane")` than `getElementById("#profile-tab-pane")` (remove the `#` otherwise it is actually null.

Then, depending on what you're trying to achieve, you'll maybe need to wait for the complete loading of the page and rather use `getOrCreateInstance()`.

Something like the following:
```js
window.addEventListener("load", (event) => {
	bootstrap.Tab.getOrCreateInstance(
		document.getElementById("profile-tab-pane")
	).show();
});

```

**Comment by counteragent** [comment]
My bad, fixed that, but the problem still persists.

I tried what you suggested, but still get an error, just a different one on the show() method.
`Uncaught TypeError: Illegal invocation`

**Comment by julien-deramond** [comment]
Seems to work like this: [CodePen](https://codepen.io/julien-deramond/pen/wvxJGPw).

**Comment by counteragent** [comment]
You're right. It works. Thanks. Not sure if this should close the ticket or not since the original error still exists, this is just a work around using a different solution.

**Comment by julien-deramond** [comment]
I'll let @GeoSot close it or not depending on if he thinks there's something more to do somewhere.

**Comment by counteragent** [comment]
Just realized my big mistake. I thought the element ID I was supposed to reference was the tab-pane content div, not the ID of the actual button/link. I'm closing this ticket and thanks for the help and patience.

**Comment by counteragent** [comment]
const triggerEl = document.querySelector('#myTab button[data-bs-target="#profile"]')
bootstrap.Tab.getInstance(triggerEl).show() // Select tab by name

**Comment by counteragent** [comment]
@GeoSot You're right, it worked! Awesome.
https://codepen.io/counteragent/pen/mdjWPxo
