### ISSUE TITLE
Embed classes not showing up

### ISSUE THREAD

**Issue by LinardsLiepenieks** [twbs/bootstrap#37840]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi
When I launch my page on localhost the embed-item and embed-responsive classes are not showing up
I do not have any duplicate classes or overrides - when i go into inspect element they are not showing up when I check styles but are showing up if I make my own with the same name - everything else is working fine
I'm on mac OS using chrome and have added the css from official bootstrap cdn 5.0.3.-alpha
When I change it to bootstrap 4.6.2. it works as it should

So i suppose it is an error for v5

### Reduced test cases

		<section class="container">
			<div class="row h-100">
				<div class="col-md-6">
					<div>
						<div class="embed-responsive embed-responsive-16by9">
							<iframe
								width=""
								class="embed-responsive-item"
								src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0"
								allowfullscreen></iframe>
						</div>
					</div>
				</div>

				<div class="col-md-6"></div>
			</div>
		</section>

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5

**Comment by mdo** [comment]
Major versions always come with changes to class names. You want the new ratio helper. https://getbootstrap.com/docs/5.3/helpers/ratio/
