### ISSUE TITLE
[docs] missing warning for offcanvas dark classes

### ISSUE THREAD

**Issue by bastienmoulia** [twbs/bootstrap#37853]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the offcanvas doc, there is some dark classes without the warning to use `data-bs-theme="dark"`.

Also in close button, the **Heads up!** is an info and not a warning.

### Reduced test cases

https://getbootstrap.com/docs/5.3/components/offcanvas/#dark-offcanvas

https://getbootstrap.com/docs/5.3/components/close-button/#dark-variant

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @bastienmoulia and for reporting these inconsistencies. We'll try to uniformize everything in a PR soon.
