### ISSUE TITLE
Accordion scrolls somewhere but not into the visible area

### ISSUE THREAD

**Issue by cgahmann** [twbs/bootstrap#37860]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If the content of the accordion is too long and you click on another item, for example, it does not scroll into the visible area, but scrolls somewhere.

https://getbootstrap.com/docs/5.3/components/accordion/ 

### Reduced test cases

https://jsfiddle.net/fpv235yn/

![bug](https://user-images.githubusercontent.com/13014767/211851327-512718ee-413f-4892-8b71-cafe848da1a6.gif)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by Sumit-Singh-8** [comment]
Hi @julien-deramond i want to work on this issue

**Comment by cgahmann** [comment]
Thanks. This works: https://github.com/twbs/bootstrap/pull/38082
