### ISSUE TITLE
Navbar not working with CSS grid

### ISSUE THREAD

**Issue by danielniccoli** [twbs/bootstrap#37875]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Navbar is not working with the experimental CSS grid.

- Navbar is flex, even when adding the `.grid` class.
- After forcibly setting the navbar to grid with `style="display: grid;"` the columns do not align with the grid, as you can see in the following screenshot. The second row is a regular div with `.grid` and you can see it working fine there.

![grafik](https://user-images.githubusercontent.com/2971735/212425220-2e5d0d82-23dc-4669-93c8-ff81bbdee708.png)

### Reduced test cases

```html
<header class="grid navbar navbar-expand-lg border border-2 border-danger" style="display: grid;">
  <a class="navbar-brand g-col-3 bg-danger" href="#">Company name</a>
  <button class="navbar-toggler g-col-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse g-col-8" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <button class="btn btn-link nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">BTN</button>
        <ul class="dropdown-menu dropdown-menu-dark">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </li>
    </ul>
  </div>
</header>

<div class="grid border-2 border-info">
  <a class="g-col-3 bg-danger" href="#">BS CSS Grid</a>
  <button class="btn" type="button" >BTN</button>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
Changing the `display` will definitely break things—the same properties that apply to `flex` by default don't necessarily apply to `grid`. This will definitely require more changes than just what you've included, and as such, we'll be closing as a won't fix.
