### ISSUE TITLE
Add Color Modes to Display Utilities

### ISSUE THREAD

**Issue by Hemphill** [twbs/bootstrap#37879]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I'm thinking something along the lines of `d-dark-none` and `d-light-none`. I presume it would clover all the standard display types like block, inline and etc. 

As to responsive, I'm thinking we'd have responsive variants, something like `d-dark-sm-none` and `d-dark-md-block`.

 Here is a very basic example of how this could work.

```html
<style type="text/css">
  [data-bs-theme="dark"]  .d-dark-none   { display: none;  }
  [data-bs-theme="dark"]  .d-dark-block  { display: block; }
  [data-bs-theme="light"] .d-light-none  { display: none;  }
  [data-bs-theme="light"] .d-light-block { display: block; }
</style>

<div data-bs-theme="dark">
  <p class="d-dark-none">I'm in light mode.</p>
  <p class="d-light-none">I'm in dark mode.</p>
</div>

<div data-bs-theme="light">
  <p class="d-dark-none">I'm in light mode.</p>
  <p class="d-light-none">I'm in dark mode.</p>
</div>
```

I can see Bootstrap uses mixins for utility classes, I haven't figured out how they work yet. I started to figure out how to add this using the mixins, but realized it's fairly complicated. I decided I should probably see if this is something desired before I figure out how to do it in the Bootstrap way and put in a PR.

I'm looking to see if the core team would like this feature added, and if they me want to dive in and figure out how to do it in the Bootstrap way.

### Motivation and context

The need for this became apparent when I had some images which look really bad on a dark background, but the changes to make it look good in a dark background didn't look good on a light one. This isn't as much of a problem with SVG images since you can fairly easily inverse colors via CSS, but raster images like a transparent PNG or JPEG aren't so easy to adjust via just CSS. With the proposed utility classes we can tailor the content displayed to best suit the current color mode.

**Comment by mdo** [comment]
Going to skip on this for now, and wait for more feedback on color modes. Thanks though!

**Comment by P4KM4N** [comment]
I was searching for this feature too.
