### ISSUE TITLE
Table hover is not working when the code is used in the jsx

### ISSUE THREAD

**Issue by pavanchinna96535** [twbs/bootstrap#37882]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I imported the code in my react project , in table property I tried using table-hover , but table hover is not working.

### Reduced test cases

http://localhost:3000/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v 5.1.0

**Comment by mdo** [comment]
Closing due to missing example.
