### ISSUE TITLE
data-bs-theme="auto" does not work in 5.3.0-alpha1

### ISSUE THREAD

**Issue by eiskalteschatten** [twbs/bootstrap#37884]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have been trying out the latest version of Bootstrap (5.3.0-alpha1) and in particularly playing with dark mode. Unfortunately, I have not been able to get `data-bs-theme="auto"` to work at all. It just always shows light mode.

I have taken the HTML code directly from the Getting Started documentation (https://getbootstrap.com/docs/5.3/getting-started/introduction/) and simply added `data-bs-theme="auto"` to the HTML tag:

```html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>
```

I feel like I'm missing something though since it doesn't work. I have searched the docs for quite a while to try to find any information about the `auto` mode, but there doesn't seem to be anything other than that it exists. Of course, I've also found the recommended JavaScript for building a color mode toggle (https://getbootstrap.com/docs/5.3/customize/color-modes/#javascript), but that doesn't have any information about the `auto` setting.

Is this just missing documentation or is it actually a bug? I realize this version is still in alpha, which is why I thought I would report it.

### Reduced test cases

CodePen only allows HTML within the `<body>` tag, so I can't post the example there.

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

v5.3.0-alpha1

**Comment by Hemphill** [comment]
I think you have to use the javascript in order for the auto value to do anything.

**Comment by mdo** [comment]
Yes, you need to include the JS mentioned at https://getbootstrap.com/docs/5.3/customize/color-modes/#javascript. I've pushed an updated example to https://github.com/twbs/examples/tree/main/color-modes to show how this can be done.

**Comment by eiskalteschatten** [comment]
Ok, perfect. I just wasn't sure whether it was a bug or if I just wasn't understanding the documentation correctly. 

It might be nice though to have a quick blurb specifically about how to use `auto` since it appears in examples, but there isn't anything specific about the fact that you need to implement the logic for it. It's implied in the JavaScript example, but when you aren't planning on building a toggle switch and just want to rely on the browser's settings, you might not necessarily read through the example on how to build a toggle switch, as was in my case...
