### ISSUE TITLE
HTML Tooltips not showing inline SVG

### ISSUE THREAD

**Issue by leo-mesbah** [twbs/bootstrap#37883]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When you put some inline SVG inside tooltips they're not added to the tooltip html (`<div class="tooltip-inner">`). They're missing from the tooltip content. However it works with `<img .../>.`

### Reduced test cases

`<a href="#" 
data-bs-toggle="tooltip"
data-bs-placement="right"
data-bs-title="<div><a><svg role='img' focusable='false' width='28' height='28' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 28 28'><circle cx='14px' cy='14px' r='14px' fill='currentColor'></circle></svg></a>Some Content</div>" 
data-bs-html="true">
<span class="text-secondary">Hello</span>
</a>`

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.0

**Comment by mdo** [comment]
Given the HTML you're including, you're probably running into an HTML parsing error first and our sanitizer second. https://getbootstrap.com/docs/5.3/components/tooltips/#options

**Comment by leo-mesbah** [comment]
It appears that the issue is caused by Bootstrap's sanitizer rather than the HTML included. I have done some unit testing and the SVG does not seem to be passed through in any case - as soon as there is an SVG tag, it does not pass through.
