### ISSUE TITLE
Popover hide issue in bootstrap 5.2+

### ISSUE THREAD

**Issue by yaras6** [twbs/bootstrap#37892]
I used to hide popovers in this way:

`$(".popover").popover("hide");`

In bootstrap 5.1.3 this piece of code hides popover without issue. For Bootstrap 5.2+ hiding popovers with jQuery stopped workin. Could you fix it or advise how can I hide a popover and how can I hide all popovers?

**Comment by mohammadizanloo55** [comment]
I tested your issue and there was no problem for me
This is the code with which I tested your problem and everything was correct 
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <button
      type="button"
      class="btn btn-lg btn-danger example"
      data-bs-toggle="popover"
      data-bs-title="Popover title"
      data-bs-content="And here's some amazing content. It's very engaging. Right?"
    >
      Click to toggle popover
    </button>
    <br />
    <button id="popoverHider">close !!</button>
  </body>

  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
    integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
    integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
    crossorigin="anonymous"
  ></script>

  <script>
    const popoverTriggerList = document.querySelectorAll(
      '[data-bs-toggle="popover"]'
    );

    const popoverList = [...popoverTriggerList].map(
      (popoverTriggerEl) => new bootstrap.Popover(popoverTriggerEl)
    );

    const popoverHiderButton = document.querySelector("#popoverHider");

    popoverHiderButton.addEventListener("click", () => {
      $(".example").popover("hide");
    });
  </script>
</html>

```

**Comment by mdo** [comment]
Closing per second comment, but also...

Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by yaras6** [comment]
I prepared example. 
https://jsbin.com/nojolosiko/1/edit?html,output

This code with version 5.1.3 hides popover. But after switch to 5.2.x it stops working
https://jsbin.com/diquwuxiqi/1/edit?html,output

It looks like I may refer to bad element (popover window instead button which initialized), but it is interesting that older version working with that. It was a bug or a feature :)?

**Comment by GeoSot** [comment]
Try  
```js
...
    hideAll: function () {
	    $("[data-bs-toggle=\"popover\"]").popover("hide");
    }
....
```

**Comment by GeoSot** [comment]
For some reason, the old version, could forward calls from the popover element to the initial Popover instance, although the instance was registered on the trigger element.
But this was causing double instance registrations, and swept out (by me) during a cleanup.

**Comment by yaras6** [comment]
Great, thanks for clarification @GeoSot. Regards.
