### ISSUE TITLE
 HTML Tooltips not showing inline SVG

### ISSUE THREAD

**Issue by leo-mesbah** [twbs/bootstrap#37908]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When you put some inline SVG inside tooltips they're not added to the tooltip html (<div class="tooltip-inner">). They're missing from the tooltip content. However it works with <img .../>.

### Reduced test cases

CONSIDER THIS CODEPEN BEFORE CLOSING FOR NOTHING:
[https://codepen.io/leo-mesbah/pen/ZEjXRaw](url)

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.0

**Comment by mdo** [comment]
As mentioned in #37883, this is because of the sanitizer preventing potentially malicious code. You'll need to modify the allowList to enable support for SVG elements in your code. https://getbootstrap.com/docs/5.3/getting-started/javascript/#sanitizer

**Comment by leo-mesbah** [comment]
thank you!
