### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by marcomarsala** [twbs/bootstrap#37914]
Here https://getbootstrap.com/docs/5.3/layout/gutters/#horizontal--vertical-gutters
".g-* classes can be used to control the horizontal gutter widths"
should be
".g-* classes can be used to control the horizontal and vertical gutter widths"

**Comment by rohitmit98** [comment]
Noticing a lot of these. Missed closing tags also.

Here are the one's I have found: 
https://getbootstrap.com/docs/5.3/components/navbar/ 
Line 8 should be ms-auto, instead shows me-auto 

Also,  the bottom of this page, there are lots of unclosed <hr> tags when using for dropdown dividers.

**Comment by JatinKumar001** [comment]
Hey, can I start working on it?

**Comment by Shubham1450** [comment]
Can I work on this issue.

**Comment by mdo** [comment]
Fixed by #37918
