### ISSUE TITLE
Clicking on Nav Tabs creates many detached DOM elements that don't get cleaned up

### ISSUE THREAD

**Issue by naviln** [twbs/bootstrap#37910]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi team,

Roughly 2 weeks back I upgraded my Angular 14 web app from bootstrap 4.5.2 to 5.2.3 (latest).

Unfortunately my team have found a strange issue that was missed in our initial review.

After clicking on any nav tab in bootstrap 5, and then navigating to another page/component, it creates detached DOM elements.

Back in bootstrap 4.5.2, within 40-180 seconds the detached DOM elements would get cleaned up.

In bootstrap 5, unfortunately, they do not, and it keeps stacking up!!

I have managed to create a small scale repro demonstrating the issue in stackblitz.

Bootstrap 4:
[BS4 StackBlitz Editor](https://stackblitz.com/edit/bootstrap4navtabtest)
[BS4 StackBlitz Demo](https://bootstrap4navtabtest.stackblitz.io/)

Bootstrap 5
[BS5 StackBlitz Editor](https://stackblitz.com/edit/bootstrap5navtabtest)
[BS5 StackBlitz Demo](https://bootstrap5navtabtest.stackblitz.io/)

To reproduce, 

- navigate to the nav tabs page, 
- click on a nav tab, and then 
- return to the home page.
- repeat as many times as you like.

Return to the home page, and wait a few moments for the DOM count to subside.

Here are some screenshots showing the DOM numbers from the Chrome console.
On bootstrap 4, things look ok. It does create detached nodes, but at least they are periodically cleaned up, the number goes below 100:

![image](https://user-images.githubusercontent.com/7679723/213073588-5dfc3423-fb55-4da9-b78c-94fa7f802b2d.png)

On bootstrap 5, I simply can't get the DOM nodes to decrease. I managed to inflate it up to 1000 and it just keeps growing!

![image](https://user-images.githubusercontent.com/7679723/213073666-db25abe5-a4a4-40d9-b665-666510f8fbe2.png)

My production app has up to 20 tabs, each one with hundreds of elements and nested elements inside it. As you can imagine, it has a big impact in a short amount of time.

Is there something wrong in my implementation that can be adjusted to solve this issue? Or is it a bug with bootstrap?
Any suggestions on how to address this would be greatly appreciated.

Thanks!

### Reduced test cases

Repro projects are on stackblitz here:

Bootstrap 4:
[BS4](https://stackblitz.com/edit/bootstrap4navtabtest)
[BS4 demo](https://bootstrap4navtabtest.stackblitz.io/)

Bootstrap 5
[BS5](https://stackblitz.com/edit/bootstrap5navtabtest)
[BS5 demo](https://bootstrap5navtabtest.stackblitz.io/)

To reproduce, 

- navigate to the nav tabs page, 
- click on a nav tab, and then 
- return to the home page.
- repeat as many times as you like.

Return to the home page, and wait a few moments for the DOM count to subside.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

Tried 5.2.3 and 5.3.0-alpha1

**Comment by kyletsang** [comment]
I've tested the sandbox with the profiler and the nodes do eventually get garbage collected.  There might be something in your application's code that is not getting collected properly.  Could you try the debugging steps listed here on your page?

https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks#identify-the-javascript-code-that-retains-detached-elements

**Comment by naviln** [comment]
> I've tested the sandbox with the profiler and the nodes do eventually get garbage collected. There might be something in your application's code that is not getting collected properly. Could you try the debugging steps listed here on your page?
> 
> https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks#identify-the-javascript-code-that-retains-detached-elements

Thanks for the response. What do you mean by sandbox? Did you try the sample repro project on stackblitz that I created? Exactly how long did you have to wait for it to get garbage collected?

I waited for over 10 minutes, and the nodes never get cleared, even after clicking the "Collect garbage" button on the memory tab:

![image](https://user-images.githubusercontent.com/7679723/220518576-0f71028a-8d3b-4b9d-a4f6-29377882b12f.png)

**Comment by kyletsang** [comment]
Yes I've tested with the same stackblitz repro.  Another thing I've tried is increasing the node count by repeatedly clicking the button to go between pages. As soon as the node count hits about 2000, it gets garbage collected and drops back to under 100.  Can you try running this test in incognito and see if that makes any difference in your testing?  

Also since you're running Angular, but using the vanilla Bootstrap JS, it might not be fully compatible due to how those frameworks manipulate the DOM.  Here's the [doc page](https://getbootstrap.com/docs/5.3/getting-started/javascript/#usage-with-javascript-frameworks) that talks briefly about this.

**Comment by naviln** [comment]
> Yes I've tested with the same stackblitz repro. Another thing I've tried is increasing the node count by repeatedly clicking the button to go between pages. As soon as the node count hits about 2000, it gets garbage collected and drops back to under 100. Can you try running this test in incognito and see if that makes any difference in your testing?
> 
> Also since you're running Angular, but using the vanilla Bootstrap JS, it might not be fully compatible due to how those frameworks manipulate the DOM. Here's the [doc page](https://getbootstrap.com/docs/5.3/getting-started/javascript/#usage-with-javascript-frameworks) that talks briefly about this.

Thanks, I've tried it in incognito and its the same problem. Were you clicking on some of the nav tab headers before you clicked between the pages? I got it up to 3000, tried clicking garbage collection multiple times, and it still doesn't go away.

In any case, my team have started to move away from using this library, and using ngIf and ngClass in angular instead.

![image](https://user-images.githubusercontent.com/7679723/220820227-4b5dae32-ed10-4530-bf5f-5a5b78dd4f85.png)

**Comment by naviln** [comment]
Closing as we are no longer using this library
