### ISSUE TITLE
Default text doesn't follow contextual data-bs-theme attribute settings

### ISSUE THREAD

**Issue by realthemes** [twbs/bootstrap#37917]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I set `data-bs-theme="light"` attribute in `html` tag and contextual `data-bs-theme="dark"` for my `footer` section, default text color (like `span` or `p`) inside `footer` doesn't follow `data-bs-theme="dark"` settings, color keep changing from dark to light when I switch `data-bs-theme` attribute in `html` tag. Is color must be fixed in dark theme or should I add for every text additional class .text-body?

### Reduced test cases

```
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <footer data-bs-theme="dark">
        <span>This text doesn't respect contextual data-bs-theme="dark" attribute</span>
    </footer>
</body>
</html>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by mdo** [comment]
For now, this is addressed by https://getbootstrap.com/docs/5.3/customize/color-modes/#nesting-color-modes. We can't reset the `color` and `background-color` on the `data-bs-theme="dark"` alone because we also allow folks to apply that to specific components. As such, you need to add `.text-body` and `.bg-body`.
