### ISSUE TITLE
New variant of Badge - Outline mode

### ISSUE THREAD

**Issue by subrayamallya** [twbs/bootstrap#37928]
Just like buttons have btn-outline modes can we add outline mode for badges.

Buttons have

- btn-primary and corresponding btn-outline-primary
- btn-danger and corresponding btn-outline-danger

It would be great to be able to have badges support similar outline mode
- badge outline-primary 
- badge outline-danger

**Comment by devhoussam1998** [comment]
nice idea

**Comment by mdo** [comment]
I think for the time being, using utilities to accomplish this is the best approach. Closing out for now, but will consider revisiting for v6 and beyond.
