### ISSUE TITLE
grid breaks for nested col with text-truncate on a long text

### ISSUE THREAD

**Issue by saranglakare** [twbs/bootstrap#37922]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

For a layout like this:
- row
  - col-auto
  - col
    - row
      - col w/ text-truncate

The two columns do not show side by side when the text is larger than the available width (that is, truncate comes into use).

How it displays:
![Screen Shot 2023-01-21 at 6 45 07 PM](https://user-images.githubusercontent.com/4996891/213868532-cd016415-9634-41b8-86f0-65808a3dee29.png)

Expected behaviour:
![Screen Shot 2023-01-21 at 6 45 13 PM](https://user-images.githubusercontent.com/4996891/213868539-a382f329-0376-4d25-8f15-38909f7572b5.png)

Why is this important? Two layered layouts are very common. Just adding text-truncate should not break the powerful grid layout Bootstrap has!

### Reduced test cases

Sample code showing the problem:
https://o1jjvb.stackblitz.io

Note that 
1. without nested col it works with truncate
2. with nested col but without truncate it works

As it turns out, this code actually works only on `v4.5.0` of Bootstrap!
https://o1jjvb-o1zlws.stackblitz.io

On investigating the changes made around `4.5.0` I found that adding `min-width:0` to `.col` is what solved the problem. Here is that one change showing a working version:
https://o1jjvb-kchnnp.stackblitz.io

I traced why the `min-width` change was reverted and found these (adding here just for reference):
https://github.com/twbs/bootstrap/pull/30999
https://github.com/twbs/bootstrap/issues/31094

So may be `min-width:0` is the wrong way to fix it. Can anyone tell me how to fix it properly or can we get this fix into Bootstrap?

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
The best solution here is to nest the truncation:

```html
<div class="col">
  <div class="text-truncate">...</div>
</div>
```

It's annoying for extra HTML, but given the side effects from the previous solution, this feels right. Would love to find another solution to this flex-ish bug if there is one, but I've yet to see it :).

**Comment by Bibendus83** [comment]
the only way to fix it I found was to apply text-truncate to the col element

```
<div class="col text-truncate">
  ...
</div>
```

The problem is that the `overflow:hidden` style it applies can cause issues if you are using elements that need to go out of the col.

For instance I'm using the [vue-multiselect](https://github.com/shentao/vue-multiselect) plugin with an ellipsis applied to reduce the max width of the select.

When i try to open the select it gets cut
![immagine](https://github.com/user-attachments/assets/3ce3c61d-0f95-4400-9d6f-d900b949aa17)


So is there no other fix other than forcefully applying `min-width:0` where needed?
