### ISSUE TITLE
Suggest a new feature: Sidebars RTL Support

### ISSUE THREAD

**Issue by ahmedaabuwarda** [twbs/bootstrap#37938]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello Bootstrab,

It would be great if you added Sidebars RTL Support to Examples on your page.
I will wait for the results.

Thanks

### Motivation and context

I it common for us to use both LTR and RTL in our websites and it will be helpful if you added this feature ready to be used directly.

**Comment by ChellyAhmed** [comment]
Hello,
Thank you for your comment. RTL Support is indeed an important feature. However, it seems like Bootstrap already has RTL support. I hadn't realized that until I tried to open a pull request and it was closed.

Please check this link to Bootstrap documentation about RTL support : 
https://getbootstrap.com/docs/5.0/getting-started/rtl/
