### ISSUE TITLE
dropup within collapsed navbar displays upward caret instead of downward

### ISSUE THREAD

**Issue by Hopper262** [twbs/bootstrap#37954]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Within a navbar, one can use the `.dropup` class for upward-expanding dropdowns, which works great for footer navigation. When the dropup is collapsed behind a toggler, it always expands downward (which makes sense), but the caret still points up. I expected the downward-pointing caret to be used when it's in the collapsed state.

I'm not sure whether the dropup case is officially supported -- there are no examples showing it -- but it's super helpful and I've noticed no problems aside from this minor cosmetic glitch.

### Reduced test cases

https://stackblitz.com/edit/xkvnwe?file=index.html

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v5.2.3

**Comment by SunnyChaware** [comment]
I have seen the issue and tried to do it, 
i thought using the javascript to change the class as screen width changes will help.
but i can say that way can work but may be m not doing it correctly, here is my code:

`$(window).on('resize', function () {`
 ` if ($(window).width() < 400) {`
    `$('#toggleArrow').addClass('dropdown');`
    `$('#toggleArrow').removeClass('dropup');`
`  } else {`
 `   $('#toggleArrow').addClass('dropup');`
    `$('#toggleArrow').removeClass('dropdown');`
`  }`
`});`

**Comment by julien-deramond** [comment]
I'd say we don't need to handle this very specific use case directly within the framework. I'll let other members of the core team express themselves on the topic.

One solution would be to use JavaScript as mentioned by @SunnyChaware by adding/removing the `.dropup` dynamically.

Maybe you can try another solution directly in CSS.
First add an id to the `<li>`: `<li id="mydropup" class="nav-item dropup">`.
Then you could add something like this:

```scss
@media (max-width: 576px) {
  #mydropup {
    .dropdown-toggle {
      @include caret(down);
    }
  }
}
```

**Comment by mdo** [comment]
Agreed with @julien-deramond, let's pass on this for now. That said, I'm wondering if we need to re-evaluate our static dropdowns in the navbars in v6. Let's discuss when we're ready @julien-deramond.
