### ISSUE TITLE
Border width class affecting the children as well

### ISSUE THREAD

**Issue by Al-Ki-Lee** [twbs/bootstrap#37963]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I use the border width class, the effect go to all the children elements having a border as well.

Here is an exemple :
```
<div class="container border border-5 border-primary">
        <div class="border">Test</div>
</div>
```

The solution I found is to override the border width class directly in each children element's class :
```
<div class="container border border-5 border-primary">
        <div class="border border-1">Test</div>
</div>
```

I expected that the border of the children would not be affected as well. Is that normal ?

### Reduced test cases

None

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by whatbird** [comment]
looks to me (5.2.3) that the `.border-5` classes are setting `--bs-border-width` when perhaps they should be setting `border-width`

**Comment by mdo** [comment]
Yeah this was changed in v5.2.0 with the massive introduction of CSS variables. I can see how this is a problem, so going to open a PR to fix. Thanks!
