### ISSUE TITLE
No visual differentiation between active and disabled links in dark mode dropdown menus

### ISSUE THREAD

**Issue by Sanx78** [twbs/bootstrap#37974]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In 5.3 Alpha 1, there is no visual differentiation between active and disabled links in dark mode dropdown menus. This has been tested in Safari on iOS and in Chrome/Edge on Windows.

Active links are set to` --bs-dropdown-link-color`, which itself inherits `--bs-body-color`. Disabled links are set to `--bs-dropdown-link-disabled-color` which is set to **#adb5bd**. In dark mode, `--bs-body-color` is also set to **#adb5bd**.

This can be seen on the Bootstrap 5.3 doco page for dropdowns: https://getbootstrap.com/docs/5.3/components/dropdowns/#disabled

### Reduced test cases

Issue demo here:
https://codepen.io/Sanx78/pen/YzjjLEy

My personal fix (likely to be hated as it is a large sledgehammer for a very small nut) is here:
https://codepen.io/Sanx78/pen/GRBBdOj

However, what I imagine will be the "correct" way of fixing it is to make `--bs-dropdown-link-disabled-color` theme aware.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.0 Alpha 1

**Comment by MaruthiKo** [comment]
I would love to work on this issue

**Comment by Sanx78** [comment]
Sorry, https://codepen.io/Sanx78/pen/GRBBdOj updated to actually contain the proposed fix.

**Comment by MaruthiKo** [comment]
Oh okay cool
I will work on this now

**Comment by MaruthiKo** [comment]
I'm planning on adding the changes to [bootstrap](https://github.com/twbs/bootstrap)/[scss](https://github.com/twbs/bootstrap/tree/main/scss)/_dropdown.scss would that be fine to fix this issue

**Comment by MaruthiKo** [comment]
There is a variable that defines the color of the disabled dark dropdown

**Comment by MaruthiKo** [comment]
@Sanx78 Please have a look at my pull request and let me know if it solves your issue
