### ISSUE TITLE
node-sass 7 not compatible with node18/19

### ISSUE THREAD

**Issue by BnitoBzh** [twbs/bootstrap#37975]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Bootstrap 4.6 use node-sass@7 as dependency, but node-sass does not work anymore with node@18

### Reduced test cases

nothing here

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

v4.6.2

**Comment by mdo** [comment]
We're no longer actively maintaining v4.
