### ISSUE TITLE
Spinner-border-reverese: A spinner that rotates in a reverse direction

### ISSUE THREAD

**Issue by ChellyAhmed** [twbs/bootstrap#37989]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The feature proposal is to add a new class "spinner-border-reverse" to the existing spinner-border component in the Bootstrap framework. This class would allow the spinner-border to rotate in the other direction, providing a visual cue of activity in the opposite direction.

### Motivation and context

The spinner-border component is widely used in Bootstrap applications to indicate activity or loading. However, in some cases, a user may want to indicate activity in the reverse direction. For example, when we are talking about two different types of spinners, to establish the contrast between them, we may give them different colors, and different rotating directions as well. It may also be useful to differentiate between the loading state of a component. For instance, if changes are uploading (loading) a spinner can be shown. Yet, it will be very useful to change the spinner with a reversed one once the changes fail to commit and we go to the rolling back state.

These are cases in which having a spinner that rotates in the reverse direction provides a clear visual cue and helps to improve the user experience. It also allows developers to be more creative and provide unique experiences for their users.

More importantly, having a separate class for reverse rotation reduces the complexity of using custom CSS to achieve the desired effect. It also provides a consistent and well-documented approach, making it easier for other developers to understand and maintain the code.

**Comment by mdo** [comment]
Closing for now per #37990.

**Comment by ChellyAhmed** [comment]
@mdo  Thank you for your review, and for your comment.
I can work on a modifier class that if we add to any spinner, it makes it rotate in the other direction. Same thing for the spinner-grow, it makes it shrink instead of grow. Should I start working on it, or let it go as it is considered not planned?
