### ISSUE TITLE
Navbar `fixed-top` placement does not work

### ISSUE THREAD

**Issue by a-kriya** [twbs/bootstrap#37987]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The `position` declaration of `.fixed-top` gets overridden by `.navbar`'s:

![image](https://user-images.githubusercontent.com/26761352/215730557-883d719e-c032-47b7-8459-171d5bd3c5a7.png)

### Reduced test cases

The StackBlitz link for the `fixed-top` demo: https://getbootstrap.com/docs/5.3/components/navbar/#placement

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by ChellyAhmed** [comment]
Hello, @a-kriya 

I checked the StackBlitz link, and it did not work, just like you described.
However, when I tried the same code on my computer locally, the navbar placement was perfect as expected. (Chrome, Firefox, or Safari on MacOS).

So I do not think the problem is with the code itself. Maybe there is an issue related to the StackBlitz link.

**Comment by a-kriya** [comment]
@ChellyAhmed Thanks for taking a look. The screenshot I pasted above is from my local setup. I'm using v5.3.0-alpha1. Which version did you try it with?

**Comment by ChellyAhmed** [comment]
I'm used v5.3.0-alpha1 too.

**Comment by a-kriya** [comment]
Then it may be the order I import the scss files in, in my custom build. I'll verify and confirm.

I couldn't reproduce on JSFiddle with the CDN version: https://jsfiddle.net/4r1xz8uh/show

**Comment by a-kriya** [comment]
Confirmed. `scss/navbar` has to be imported before `scss/helpers` in a custom build for the placement classes to apply.

Which is how it's documented at https://getbootstrap.com/docs/5.3/customize/optimize/#lean-sass-imports. I just had an older setup I'd copied over. Closing.
