### ISSUE TITLE
docs/5.2/forms/form-control/#color element is not supported in most UA and AT

### ISSUE THREAD

**Issue by Aniort** [twbs/bootstrap#37991]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The form element color picked is not well supported by most UA/AT couples (https://a11ysupport.io/tests/tech__html__input__input-color#assertion-html-input(type-color)_element-convey_name)
Perhaps we should warn devs in docs about the insufficient robustness  of this element so it must be used with caution and it must have an alternative when used (just a text field to input a hex color code, for example)

### Reduced test cases

https://getbootstrap.com/docs/5.2/forms/form-control/#color

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.2

**Comment by mdo** [comment]
I don't think we do this for any other browser-native elements... unsure if we should start. Thoughts @patrickhlauke?

**Comment by patrickhlauke** [comment]
I'd say it's up to developers to know this themselves. For what it's worth, on browsers that don't support particular `<input>` types, they will revert back automatically to display a text input

**Comment by mdo** [comment]
Agreed, closing as a won't fix.
