### ISSUE TITLE
V5: Handling Hover, Focus, and Other States by using only utility classes

### ISSUE THREAD

**Issue by devhoussam1998** [twbs/bootstrap#37995]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

For example, to apply the `bg-blue-500` class on hover, use the `hover:bg-blue-700` class:

```
<button class="btn btn-lg bg-blue-500 hover:bg-blue-700 ...">
  Click on me
</button>
```

for more details about this feature: [Check this out](https://tailwindcss.com/docs/hover-focus-and-other-states)

### Motivation and context

it will be great to have something like this in bootstrap

**Comment by ffoodd** [comment]
It already exists [thanks to the utilities API](https://getbootstrap.com/docs/5.3/utilities/api/#states).

As far as I know, this isn't used in the default build but building from Sass on your own would do the trick.
