### ISSUE TITLE
Reporting bug in modal

### ISSUE THREAD

**Issue by VitorErnandes** [twbs/bootstrap#38026]
Hello, I work with bootstrap and I love it, so first I would like to thank you for the tool.

I'm working with modal and found a bug, where when I open a modal over another and close it, the scroll of the primary modal is broken, this is because the "modal-open" class of the body is removed.

I managed to solve it with the following command, but I would like to report it so I don't have to do it anymore.

Command:

$('#modal').on('hidden.bs.modal', function(e){
  $("body").addClass("modal-open");
});

My version is: 4.6.1.

**Comment by julien-deramond** [comment]
Thanks for reporting it @VitorErnandes.
Bootstrap v4 is EOL since the beginning of 2023 so no fix will be done for the v4.
Regarding the v5, it might correspond to https://github.com/twbs/bootstrap/issues/36463.
