### ISSUE TITLE
Increase the number of size value of Spacer 

### ISSUE THREAD

**Issue by sinjuangajan** [twbs/bootstrap#38021]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can you please increase the number of _size_ value of spacer at least to `6`. Now it is limited to `5`

```
$spacer: 1rem;
$spacers: (
  0: 0,
  1: $spacer * .25,
  2: $spacer * .5,
  3: $spacer,
  4: $spacer * 1.5,
  5: $spacer * 3,
  
  // Suggession
  6: $spacer * 6,
);
```

### Motivation and context

For CDN users it will be very useful. For modern web design need lots of spaces which is quite difficult to achieve using this limited number of spacer sizes.

**Comment by mdo** [comment]
This can be done in the utility API, so no changes to v5 for now for the spacing scale.
