### ISSUE TITLE
Border problem in RTL

### ISSUE THREAD

**Issue by AminEsmaeily** [twbs/bootstrap#38031]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The class `.border-end-0` works as expected with the default (LTR) version, but when using the RTL version, it points to the right border of the element but it should get changed to the left.
The following is the RTL input box sample:
![image](https://user-images.githubusercontent.com/11803924/218057397-6c7be7bb-6b63-4a38-833f-583c35076302.png)

The style comes from the following part:
![image](https://user-images.githubusercontent.com/11803924/218057733-ca700e5f-04f4-4fb9-9237-dbaeca077bb1.png)

### Reduced test cases

For the RTL version, it needs to be changed to the following:
``` CSS
.border-end-0 {
  border-left: 0 !important;
}

.border-start-0 {
  border-right: 0 !important;
}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.0
v5.2.3

**Comment by julien-deramond** [comment]
Thanks for opening this issue @AminEsmaeily.
Tried to reproduce quickly the issue in https://codepen.io/julien-deramond/pen/vYaqqev but it seems to work well.
Could you please create a reproducible example via CodePen (or any other tool)?

**Comment by AminEsmaeily** [comment]
Dear @julien-deramond ,
Kindly you can find the reproducible here:
[CodePen](https://codepen.io/AminEsmaeily/pen/BaPgXNz)

**Comment by julien-deramond** [comment]
In your CodePen example, you're loading `bootstrap.min.js` and `bootstrap.rtl.min.js`. Only `bootstrap.rtl.min.js` is necessary.

**Comment by AminEsmaeily** [comment]
Ok, it worked. Thank you, dear.
