### ISSUE TITLE
[5.3.a1] Fixed top navbar dark/light mode without explicit color bleeds text 

### ISSUE THREAD

**Issue by marceloverdijk** [twbs/bootstrap#38030]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using a fixed top like:

```
<nav class="navbar navbar-expand-lg fixed-top mb-4">
```

without explicit bg the text bleeds through in the header:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/197004/218045333-d470641c-6c39-4397-905b-bd0c8df3b5a9.png">

As in the screenshot I used Bootstrap docs and removed the `bd-navvar`
(`<header class="navbar navbar-expand-lg bd-navbar sticky-top">`) which gives the same result.

A header with out explicit colour is very useful with the the new dark/light mode support in which you don't want to have an explicit header colour, but white for light mode, and black for dark mode (so no coloured header).

I wonder if this is a bug or how the fixed navbar should be used in combination with a colourless head when using the new dark/light mode support.

### Reduced test cases

.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.alpha1

**Comment by Alex-Toucan** [comment]
To get padding on your navbar, you can use the padding or margin on your body, main, or what hosts your main content, tag, using the pixels from the header. Otherwise without additional CSS, you can use the sticky-top class on your header instead.

**Comment by marceloverdijk** [comment]
Here is the codepen: https://codepen.io/marceloverdijk/pen/jOpgqPv

To explain, the main content is pushed down with margin, but when scrolling you will see the text appears in the header unfortunately.

Now when adding `navbar-dark bg-dark` to the header , the text is not visible inside the header when scrolling:
See also this pen: https://codepen.io/marceloverdijk/pen/vYaoGLx

But I only want a dark header in dark mode, and in light mode a white header.
It seems some z-index issue?

**Comment by julien-deramond** [comment]
> But I only want a dark header in dark mode, and in light mode a white header

`.bg-body` should do the job and so you could do `<nav class="navbar navbar-expand-md fixed-top bg-body">`. Is it better?

**Comment by marceloverdijk** [comment]
Absolutely (and so simple). Thx a lot for your help
