### ISSUE TITLE
Padding and Margin for specific screens

### ISSUE THREAD

**Issue by Hissan147** [twbs/bootstrap#38033]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

<div class="mb-0 mb-md-3 mb-lg-5 mb-xl-5">
<div class="pb-0 pb-md-3 pb-lg-5 pb-xl-5">

### Motivation and context

 As per my client's request many times, I manually add the margin and padding for different screens by creating custom classes for each project.

**Comment by julien-deramond** [comment]
Could you please add technical details to the proposal for this feature? Not sure to understand what you suggest here.

**Comment by Hissan147** [comment]
<div class="mb-0 mb-md-3 mb-lg-5">
<div class="pb-0 pb-md-3 pb-lg-5">

**Comment by julien-deramond** [comment]
It already exists as you can see in [Utilities > Spacing > Notation](https://getbootstrap.com/docs/5.3/utilities/spacing/#notation) where you can do `{property}{sides}-{breakpoint}-{size}`.
