### ISSUE TITLE
Add the purple color used by Docs on Bootstrap

### ISSUE THREAD

**Issue by muchirajunior** [twbs/bootstrap#38066]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The purple color is widely used even on the Bootstrap Docs page which makes me view it as a necessary to be added just for text, background and buttons
![image](https://user-images.githubusercontent.com/56454064/219198188-2b505386-d5e6-4d50-847b-788479f00e5d.png)

### Motivation and context

we should have utility classes like 

> text-purple
> btn-purple
> bg-purple

The purple keyword should be replaced with another relevant key as other color names in Bootstrap

**Comment by mdo** [comment]
Thanks, but we'll keep the docs specific purple to ourselves :). We already have some purple and other colors available to create custom utilities and more though.

**Comment by muchirajunior** [comment]
Thank you (:
