### ISSUE TITLE
Dropdown from Bootstrap 5.3.0 alpha1 is not allowing href to redirect

### ISSUE THREAD

**Issue by silvioprog** [twbs/bootstrap#38078]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This is my code:

```html
<ul className="dropdown-menu dropdown-menu-end">
  <li>
    <hr className="dropdown-divider" />
  </li>
  <li>
    <a href="/payment-type" className="dropdown-item text-end">
      Payment type
    </a>
  </li>
  <li>
    <hr className="dropdown-divider" />
  </li>
</ul>
```

When I click to the `Payment type`, the page is not redirected to `/payment-type`.

### Reduced test cases

You can navigate to https://getbootstrap.com/docs/5.3/components/dropdowns/, get and test and try to add a link. Notice your link is not redirecting, even a simple `/#`, like in the examples.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0-alpha1

**Comment by silvioprog** [comment]
For sure @julien-deramond, I'm going to provide one in few minutes...

**Comment by silvioprog** [comment]
@julien-deramond, I found a weird behavior. Seems related when running Bootstrap + Vite (latest version). I was not able to reproduce in environments like CodePen and StackBlitz, but I have the full steps for how to reproduce in Vite world.

Let's go to the steps to create a minimal example to reproduce the problem.

1. Create a Vite application (TypeScript template):

```bash
npm create vite@latest my-app -- --template react-ts
```

2. Open the existing file `src/App.tsx` and replace its entire existing content as following:

```tsx
import './App.css'
[my-app.zip](https://github.com/twbs/bootstrap/files/10768101/my-app.zip)

function App() {
  return (
    <div className="App">
    <div className="container py-1">
      <div className="d-flex justify-content-between">
        <ul className="nav">
          <li className="nav-item dropdown">
            <button
              className="btn nav-link text-success"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <div className="bi bi-gear text-center fs-4"></div>
              <span className="d-none d-md-block">Settings</span>
              <ul
                className="dropdown-menu dropdown-menu-end show"
                data-popper-placement="bottom-end"
              >
                <li><a href="https://google.com" className="dropdown-item text-end">Google</a></li>
              </ul>
            </button>
          </li>
        </ul>
      </div>
    </div>
    </div>
  )
}

export default App
```

3. Replace the entire HTML file `index.html` as following:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
```

4. Install the dependencies and run the application:

```bash
yarn install
yarn dev
```

5. Navigate to [localhost:5174](http://localhost:5174), and try to navigate do Google via menu `Settings | Google`, as following:

https://user-images.githubusercontent.com/1456829/219690216-4557c900-6ca5-4eb5-8fca-22173f79c75d.mov

<hr>

Entire project to reproduce the problem:

[my-app.zip](https://github.com/twbs/bootstrap/files/10768108/my-app.zip)

**Comment by silvioprog** [comment]
Weird, even a minimal code is not working:

```tsx
import './App.css'

function App() {
  return (
    <ul className="nav">
      <li className="nav-item dropdown">
        <button
          className="btn nav-link text-success"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          <span className="d-none d-md-block">Settings</span>
          <ul className="dropdown-menu">
            <li><a href="https://google.com" className="dropdown-item">Google</a></li>
          </ul>
        </button>
      </li>
    </ul>
  )
}

export default App
```

**Comment by silvioprog** [comment]
The same for (video below):

```tsx
import "./App.css";

function App() {
  return (
    <ul>
      <li>
        <div data-bs-toggle="dropdown">
          Settings
          <ul>
            <li>
              <a href="https://google.com">Google</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  );
}

export default App;
```

Video:

https://user-images.githubusercontent.com/1456829/219703208-0e9ea4d0-0435-4ffa-b6b9-b3b447eb5aa8.mov

**Comment by Mattttyyyy** [comment]
This is making me curious as well; I tried doing onClick on the button, console log is working fine, redirection aint

**Comment by aksdevac** [comment]
@silvioprog where did you find such example where dropdown `ul` is inside of button element if you put it inside button it does not work with older 5.2 version too. 

you need to put menu `ul` outside of `button` like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.css"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Test</title>
  </head>
  <body>
    <ul class="nav">
      <li class="nav-item dropdown">
        <button
          class="btn nav-link text-success"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          <span class="d-none d-md-block">Settings</span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="https://google.com" target="_blank" class="dropdown-item">Google</a></li>
        </ul>
      </li>
    </ul>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

```

**Comment by julien-deramond** [comment]
Thanks for the repro steps @silvioprog. I was writing an answer and @aksdevac was faster than me 😄 
I can confirm that you're using

```html
<button class="btn nav-link text-success" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  <span class="d-none d-md-block">Settings</span>
  <ul class="dropdown-menu">
    <li><a href="https://google.com" class="dropdown-item">Google</a></li>
  </ul>
</button>
```

but the `<ul class="dropdown-menu">` must be outside the `<button>` as mentioned in https://getbootstrap.com/docs/5.3/components/dropdowns/#single-button.
If you have copied this HTML markup from somewhere in our doc, I'm interested to know where so that we can fix it. Otherwise, I'll close the issue.

**Comment by silvioprog** [comment]
Thanks a lot for the feedback! I'm out of office, but will test as soon as I back to laptop and let you know if it worked...

**Comment by silvioprog** [comment]
Guys, just to confirm, after following the steps provided by @aksdevac, it worked like a charm.

Maybe a wrong copy/paste from [docs/examples/headers](https://getbootstrap.com/docs/5.3/examples/headers).

Thanks once again guys, and sorry for noising! 😅
