### ISSUE TITLE
list-group-item can't be hidden with hidden attribute

### ISSUE THREAD

**Issue by AucT** [twbs/bootstrap#38077]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

List-group-item can't be hidden with hidden attribute if it has badges (using d-flex)

### Reduced test cases

https://codepen.io/AucT/pen/ExejLZN

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.0.2-5.3.0 alpha1

**Comment by AucT** [comment]
this is because of

```css
.d-flex {display: flex!important}
```

I've solved for myself using inline `style="display:flex"`

One can fix it with additional class that not important (which nicely translates in ukrainian as "no" xD)
```css
.d-flex-ni {display:flex}
```

Anyway If there is no solution or it will break something, you better mark in docs how to solve this. I wasted 40-60 minutes to get to the point (yeah, yeah I'm really noob in css).

**Comment by ffoodd** [comment]
May you use `.d-none` alongside `[hidden]`? It'd be the cleaner way to handle this, I guess.

**Comment by AucT** [comment]
That's also work. 
I'm used to make el.hidden and already made it work.

**Comment by ffoodd** [comment]
Yeah I understand, however if you don't handle specificity it's expected. I'm used to extend `.d-none` with `[hidden]` to ease this attribute usage with Bootstrap.

As far as I'm concerned, utilities are meant to override anything so that's the expected result.

**Comment by mdo** [comment]
Yeah, this makes sense to me—if you're using one utility to affect a property, you really need to use another to override it (or remove the original in some way).
