### ISSUE TITLE
Bootstrap-bundle-js script not executing(v.5.0.2)

### ISSUE THREAD

**Issue by lolngh** [twbs/bootstrap#38084]
- [ ] Prerequisites:
-  I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
-  I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

- [ ] Error Description:
Currently the project is using bootstrap-v5.0.2. Its working fine across all browsers, but it's throwing an error in MS Team's embedded browser(In VM). 
Error - Expected ':' at line no-26. Script - bootstrap.bundle.js

- [ ] Environment Details:
MS team embedded browser details - '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Teams/1.6.00.1381 Chrome/96.0.4664.174 Electron/16.2.8 Safari/537.36'.
VM - Windows server 2016.
Currently the project is using require.js to load the bootstrap. It was working fine till v4.6.2 or below versions. Upgrading is causing this issue. Could you check into this and provide a solution.

Have attached the image for your reference.
![Error](https://user-images.githubusercontent.com/73459979/220083462-e6d12d35-c75c-4276-84be-a45d249b50f5.PNG)

**Comment by julien-deramond** [comment]
Thanks for opening this issue @lolngh.
Apparently, this `bootstrap-5.0.2.bundle.js` is stored somewhere which doesn't belong to Bootstrap and seems to be associated to a template of something.
For using Bootstrap 5.0.2, please refer to https://getbootstrap.com/docs/5.0/getting-started/introduction/.
Without a minimal reproducible project with [CodePen](https://codepen.io) (or any other tool), we won't be able to help.

**Comment by lolngh** [comment]
Hi @julien-deramond ,
Actually its same module, team had renamed to bootstrap-5.0.2.*. Will check with team for an example(test-case or live demo).

**Comment by lolngh** [comment]
Hi @julien-deramond ,
Team is working on setting-up a demo(example) for the issue caused.
Meanwhile wanted to cross-verify few things:

- Currently issue is being caused in **OS - Windows 2016**. Its working fine in **web-browser(chrome)**, but when the same page is navigated/called in **MS Team's/PowerShell script to connect O365 services - embedded web browser** bootstrap-script error is being thrown. 
- With respect to above environment, embedded browser is able to execute bootstrap-script for versions below **4.6.2**.
- But when the same way the page is navigated to embedded browser in **OS - Windows 10** , is working fine.

Could you please let me know if there is the issue with OS - Microsoft's embedded browser compatibility ?

**Comment by julien-deramond** [comment]
I'm not aware of such an issue with OS - Microsoft's embedded browser compatibility but never tried it myself.
If possible, depending on your context, you could also try to load the latest version of Bootstrap instead of v5.0.2 just to see if you got the same errors.

**Comment by lolngh** [comment]
Hi @julien-deramond ,
We did try with latest bootstrap versions(5.2.3 and 5.3.0), it threw syntax error. The script is not able to execute from v5.0.0. 
Syntax error is around **lambda** expression :(for version 5.2.3)
**const toType = object => {**

Have attached the error screenshot for reference:
![error_bootstrap](https://user-images.githubusercontent.com/73459979/220278149-d87cee45-5f18-48ad-a387-60bd96ade878.PNG)

**Comment by kyletsang** [comment]
Haven't played with embedded browser controls on Windows in a while, but I do recall they used to run with whatever version of IE that's installed in the system.  It's possible that Bootstrap 5 isn't working because the embedded browser doesn't support ES6.

Could you try loading a simple script with a single arrow function and see if it works?

```
const testFunc = () => {
  // Empty
}
```

**Comment by lolngh** [comment]
Hi @kyletsang ,
Well it didn't work for the above function, it gave same syntax error for this expression(=>).

**Comment by kyletsang** [comment]
Unfortunately this is a limitation with the embedded browser control since it doesn't support modern JS/CSS.  MS Teams v2 is rumored to come out soon, so hopefully that will change things?

**Comment by lolngh** [comment]
Hi @kyletsang ,
Let me check that with team. However, I have a query - does bootstrap-4.6.2 have any kind of vulnerabilities ?

**Comment by kyletsang** [comment]
No there shouldn't be any in 4.6.2

**Comment by lolngh** [comment]
Hi @kyletsang , @julien-deramond ,
Thanks for your support. Issue was in embedded browser of MS Team's and Windows OS compatibility. Hence closing this issue/ticket.
