### ISSUE TITLE
Only h-100 and h-50 is working but not others

### ISSUE THREAD

**Issue by redkarsanket** [twbs/bootstrap#38090]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Unable to set viewport height using h- class but working with vh. Displaying just two columns in container-fluid and row with h-100 but it is working with 10vh and 90vh but not with h-10 and h-90.
**Code with 10vh and 90vh (Working):-**
```
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-lg-12" style="background-color: blue; height: 10vh;">Div 1</div>
    <div class="col-md-12 col-lg-12" style="background-color: green; height: 90vh;">Div 2</div>
  </div>
</div>
```

**Code with h-10 and h-90 (Not Working):-**
```
<div class="container-fluid h-100">
  <div class="row h-100">
    <div class="col-md-12 col-lg-12 h-10 bg-primary">Div 1</div>
    <div class="col-md-12 col-lg-12 h-90 bg-secondary">Div 2</div>
  </div>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.3

**Comment by mdo** [comment]
These utilities don't exist in Bootstrap by default. You'll have to add them with the utility API. https://getbootstrap.com/docs/5.3/utilities/sizing/
