### ISSUE TITLE
Dark theme does not change scroll bar colors to match

### ISSUE THREAD

**Issue by burdittw** [twbs/bootstrap#38129]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using the new theming methods, everything seems to be working as expected until you get to some scrollbars. The scrollbars can be for the page itself or a component with scrollbars. When you select theme to be dark the scrollbars will be white for the light theme. This issue has come up in the [AdminLTE v4 project ](https://github.com/ColorlibHQ/AdminLTE/issues/4522) and I have tested it with just a simple page with nothing but theme dark and show scrollbars.

### Reduced test cases

1. Set theme to dark mode.
2. Set a div or the page to have scrollbars.
3. Observe scrollbars not the right color.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3 Alpha 1

**Comment by julien-deramond** [comment]
Thanks @coliff. I wasn't 100% sure it was the same issue but I think so too so I'm going to close it as duplicate.
@burdittw If it is different, add a comment here and I'll reopen it :)
