### ISSUE TITLE
Dropdown menu not working on 5.3.0-alpha1

### ISSUE THREAD

**Issue by tk-425** [twbs/bootstrap#38120]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The dropdown menu feature is not functioning properly on version 5.3.0-alpha1. The dropdown menu selection is not appearing when clicked on. The dropdown menu works on 5.2 but not on 5.3.0-alpha1.

### Reduced test cases

Codepen v5 Test
https://codepen.io/tk4982/pen/oNPYZGO

Codepen v4 Test
https://codepen.io/tk4982/pen/gOdLmXa

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by aksdevac** [comment]
See the [example in docs](https://getbootstrap.com/docs/5.3/components/dropdowns/#single-button) you need to use `data-bs-toggle` attribute.

**Comment by tk-425** [comment]
@aksdevac I used `data-bs-toggle` in my project, it didn't function properly with version 5.3.0-alpha1. However, when I reverted back to version 5.2, the dropdown menu worked correctly.

**Comment by aksdevac** [comment]
Ok but in codepen link you have used data-toggle so its not working.

**Comment by tk-425** [comment]
@aksdevac I just noticed that, sorry about that. 
I just made a basic React app with Bootstrap's dropdown menu using version 5.3.0-alpha1, it functioned correctly (using the same code as my project). However, in my project, the dropdown menu selection only displays properly with version 5.2. Maybe something is missing/incorrect from my project.
