### ISSUE TITLE
Brand icon area too large in third header example

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#38122]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The brand icon area is too large in the [third header example](https://getbootstrap.com/docs/5.3/examples/headers/) from 769px breakpoint:
<img width="367" alt="Screenshot 2023-02-27 at 08 01 12" src="https://user-images.githubusercontent.com/17381666/221496216-4d825436-d88a-4e07-bb20-ac01ca508ca2.png">

1. The visible focus outline is very large when one's using the keyboard to navigate.
2. The clickable area where one's using the mouse to navigate is very large. One can click on it without even noticing.

### Reduced test cases

Can be seen directly in the documentation: https://getbootstrap.com/docs/5.3/examples/headers/.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2

**Comment by xarcode** [comment]
Hi, I have a possible solution for this issue. Will I get assigned to this or should I open a PR directly?

**Comment by julien-deramond** [comment]
Hey @xarcode. We don't assign issues in this repo so you can create a PR directly. Thanks :)
