### ISSUE TITLE
Dropdown issue with webpack and bootstrap

### ISSUE THREAD

**Issue by xKZL** [twbs/bootstrap#38137]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

I am using webpack entries that are loading two bootstraps version.
There is an automatic loading of the dropdown list when importing the "Dropdown" piece of code. 
It seems there is no way to disable this autoloading. Additionally this make that the dropdown list doesn't close/open
(it seems to be calling some sort of double action open->close or close->open)

### Reduced test cases

I don't have fix, but disabling autoloading of dropdown menu 

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.0

**Comment by benwallis** [comment]
I had a similar issue - see if this is relevant: https://stackoverflow.com/questions/75661065/bootstrap-javascript-in-webpack-5-only-working-as-esm

Or maybe try removing data-bs- attributes and initialise manually?

**Comment by xKZL** [comment]
@benwallis I tried to remove data-bs- attributes, but bootstrap seems not to be loading my element when using `.dropdown()` in that case. I will try to see further why, this is not happening for tooltip and popover

Using the line below is not working neither, as it is loaded from two different webpack entry, the two configurations doesn't know from each other, so 1+1 = 0 here. Fun fact is that if I create a third webpack entry, then it works, but this means the process is running 3 times:
```
import Dropdown from 'bootstrap/js/dist/dropdown'
```

NB: This is same for Collapse.
