### ISSUE TITLE
Set default bg color navbar sass

### ISSUE THREAD

**Issue by stijn7621** [twbs/bootstrap#38156]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I would like to have the option to set a default bg color for the navbar somewhere inside the variables sass file. The navbar colors should be in the dark or light variant based on that setting.

### Motivation and context

I have created a custom css-rule where i have set a custom background-color for the navbar, however the navbar text always shows default up in black, while it supposed to be in white.

**Comment by mdo** [comment]
Maybe in v6, thanks!
