### ISSUE TITLE
Bootstrap 4.6.2 issue with Numeric Class

### ISSUE THREAD

**Issue by jdinartejesus** [twbs/bootstrap#38163]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've being trying to use `sass` with Bootstrap 4.6.2, and it's impossible since I've always the error due to numeric class's. Eg: `.100{` since I'm moving our project to use `sass` module instead of `node-sass`. I know the issue would be solved by escaping the values (https://github.com/sass/sass/issues/2956, https://github.com/sass/sass/issues/255), but would be needed to add this to the core library.

Modules Versions:
```
bootstrap-scss: v4.6.1
sass-loader: v8.0.2
sass: v1.58.3
```

Variables creating the issue:
```
_variables.scss
$grays: map-merge(
  (
    "100": $gray-100,
    "200": $gray-200,
    ...
  ),
  $grays
);
```

Error message:
```
SassError: Expected identifier.
6 │   .100{
```

### Reduced test cases

 I know the issue would be solved by escaping the values (https://github.com/sass/sass/issues/2956, https://github.com/sass/sass/issues/255), but would be needed to add this to the core library.

Variables creating the issue:
```
_variables.scss
$grays: map-merge(
  (
    "\100": $gray-100,
    "\200": $gray-200,
    ...
  ),
  $grays
);

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

_No response_

### What version of Bootstrap are you using?

v4.6.2

**Comment by julien-deramond** [comment]
Hello @jdinartejesus 
[Bootstrap v4 is EOL](https://github.com/twbs/release#release-schedule) so we won't make any new releases for v4.
