### ISSUE TITLE
Base CSS Variables Do Not Impact Buttons

### ISSUE THREAD

**Issue by ddelella** [twbs/bootstrap#38170]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Overriding a base variable, such as --bs-primary, does not impact the equivalent button btn-primary. The expended behaviors would be to use the same primary color set as the background colors for btn-primary. The primary text color should also be linked to the btn-primary color property. I would think this should apply to all buttons.

### Reduced test cases

https://codepen.io/team/bootstrap/pen/qBamdLj

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.2.3

**Comment by mdo** [comment]
The problem here is that we can't generate new colors from a CSS variable right now. We're working on a solution, but might not have one until v6 at the earliest.

**Comment by ddelella** [comment]
> The problem here is that we can't generate new colors from a CSS variable right now. We're working on a solution, but might not have one until v6 at the earliest.

I am not sure what you mean by generate new colors. To simply the issue and just look at the primary color variable (--bs-primary). If I set the primary color for my website, I would expect the btn-primary and btn-outline-primary (as an example) to reflect that same color. Same goes for all the rest of the colors. (secondary, success, danger, etc.) It would greatly simplify color schemes if those propagated throughout the variables. People can always override a button, or other classes, if they want to be specific about their color pattern but for those who just want to generate a color palette and apply the basic color overrides it would be nice for it to apply everywhere.

You should keep this open as it can easily be done. I am doing it all with manually overrides now whereas the defaults should just be set out-of-box. 

OUT OF BOX

```
.btn-success {
  --bs-btn-color: #fff;
  --bs-btn-bg: #198754;
  --bs-btn-border-color: #198754;
}
```

RECOMMENDED (EXAMPLE)


```
.btn-success {
  --bs-btn-color: var(--bs-white);
  --bs-btn-bg: var(--bs-success);
  --bs-btn-border-color: var(--bs-success);
}
```

**Comment by mdo** [comment]
Sorry, my point is the buttons generate new colors with Sass for each button state. On hover, the background-color changes to be darker, and then even darker for active state. These extra colors (which apply to borders too) can't be regenerated with CSS, only with Sass right now. So for example we can shade the primary blue in Sass, but we can't in CSS. That means that even if the primary button background color is blue, we can't programmatically use CSS to create the darker blues for hover or active states.
