### ISSUE TITLE
Show Vue3 component in bootstrap5 light box.

### ISSUE THREAD

**Issue by ifarooq** [twbs/bootstrap#38178]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've attempted a few various methods to display a Vue3 component in a Bootstrap 5 lightbox, but none of them have been successful. My code is given below.
`<p><a class="my-lightbox-toggle" href="#" data-src="<SuggestionForm />" data-type="html" data-title="Custom HTML 2" data-toggle="lightbox" data-gallery="custom-html">Custom HTML 1</a></p>`

### Reduced test cases

No such test cases. 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by mfsbo** [comment]
@ifarooq you have not mentioned 
1. which lightbox plugin you are using
2. You have not specified vue3 code here
Here is a [jsfiddle](https://jsfiddle.net/farrukhsubhani/pyb6zqLh/5/) that shows bootstrap css and js loaded alongside a vue3 component.

I feel like this is a non bootstrap issue and should be something raised on stackoverflow where wider javascript communit can help you.

**Comment by mdo** [comment]
We don't have a lightbox, we just have our modal and offcanvas. Closing as this doesn't seem to a problem on our end.
