### ISSUE TITLE
Bootstrap v5.1.x causes 10x performance decrease.

### ISSUE THREAD

**Issue by Mike-Benoit** [twbs/bootstrap#38206]
We recently upgraded our application from Bootstrap v4.6.2 to v5.2.3 and immediately noticed a severe rendering/"Total Blocking Time" performance degradation. Oddly enough, our application only makes light use of Bootstrap.

Here are the numbers for each Bootstrap version:
v4.6.2: Total Blocking Time: 232ms
v5.0.2: Total Blocking Time: 385ms
v5.1.3: Total Blocking Time: 2744ms
v5.2.3: Total Blocking Time: 2872ms
v5.3.0-alpha1: Total Blocking Time: 3024ms

The Total Blocking Time is almost entirely taken up by Rendering in the profiler due to a large number of forced reflows compared to older versions.

I should also mention these times also do not include any load times, this is simply after our single-page application is fully loaded and launching an edit screen with some input fields on it. 

Any ideas what would be causing this when going from v5.0.2 to v5.1.3?

**Comment by mdo** [comment]
Hard to say without more more insight into how you're measuring this and under what other circumstances. We don't see any of these issues on our docs or based on our own experience. If you want to dig in more, we'd be happy to review your findings and see if there's some changes we can make.
