### ISSUE TITLE
Can't have input group with input not at end if using validation message

### ISSUE THREAD

**Issue by tbenfitz** [twbs/bootstrap#38210]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Issue is that validation message div append itself as direct sibling of input control. 

If you had: 
`<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <span class="input-group-text" id="basic-addon2">@example.com</span>
</div>` 

 as on [https://getbootstrap.com/docs/5.3/forms/input-group/](url) and decided to add validation,
it would become

`<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
<div class="invalid-feedback d-block">Must enter username</div>
  <span class="input-group-text" id="basic-addon2">@example.com</span>
</div>` 

This causes the span holding @example.com to wrap to the next line

### Reduced test cases

Ensure validation div is always last element in input group. 

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.0

**Comment by mdo** [comment]
Indeed, and we mention this in our docs. https://getbootstrap.com/docs/5.3/forms/validation/#server-side
