### ISSUE TITLE
progress-stacked classes missing

### ISSUE THREAD

**Issue by jedgar1mx** [twbs/bootstrap#38238]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

It looks like classes for multi progress bars are missing from 5.2.3.

https://getbootstrap.com/docs/5.3/components/progress/#multiple-bars

It looks like `main` has the missing classes. 

### Reduced test cases

Probably just a quick release to add missing classes.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.2.3

**Comment by julien-deramond** [comment]
Hey @jedgar1mx 
The link you're providing is the v5.3-alpha1 so the doc is talking about the new way of handling multi-progress bars in this v5.3-alpha1: https://getbootstrap.com/docs/5.3/migration/#progress-bars.
So, indeed, classes are new and not in v5.2.3.

**Comment by jedgar1mx** [comment]
Ahh thanks for the clarification I see that now. It looks like the default docs on [bootstrap.com](https://getbootstrap.com/) are the `5.3` but the default package pulled with npm is `5.2.3`. Just FYI

**Comment by julien-deramond** [comment]
Yes, it's not very handy I agree. Unfortunately, we don't have another way of doing it for now when we have alpha versions. Sorry for the inconvenience :)
Closing this issue.
