### ISSUE TITLE
Add utility for `overflow: clip`

### ISSUE THREAD

**Issue by alexandergitter** [twbs/bootstrap#38240]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add utility support for the `clip` value in `overflow` / `overflow-x` / `overflow-y`.

### Motivation and context

I just ran into a situation where `overflow-x: clip` comes in very handy since it doesn't cut off overflowing content on the y axis (in contrast to `overflow-x: hidden`, which hides overflowing content in both directions).

**Comment by mdo** [comment]
Closing as a won't fix for now given the above. You can use the utility API for adding this yourself though.
