### ISSUE TITLE
link color dark should use $primary like non-dark links do

### ISSUE THREAD

**Issue by jerothor** [twbs/bootstrap#38258]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

regular links work great when changing the primary color:

```scss
$link-color: $primary !default;
$link-hover-color: shift-color($link-color, $link-shade-percentage) !default;
```

however, when in dark mode, they always default to blue:

```scss
$link-color-dark: $blue-300 !default;
$link-hover-color-dark: $blue-200 !default;
```

i propose they use `$primary`, like regular links:

```scss
$link-color-dark: $primary !default;
$link-hover-color-dark: lighten($primary, 10%) !default;
```

### Motivation and context

normally when i change the primary color i want that reflected in all elements of the UI like it does in light mode.

in dark mode, the links are hard coded to blue by default.

**Comment by mdo** [comment]
Already addressed in `main`, coming in our next release.
