### ISSUE TITLE
Bootstrap incompatibility issues with latest version of chrome

### ISSUE THREAD

**Issue by PavanSaiSheshetti** [twbs/bootstrap#38273]
Hello team,
       I'm facing few in-appropriate styling issues with latest version of chrome browser from the past few days. Please find further details below.

The latest version of google chrome i.e., Version 111.0.5563.65 (Official Build) (64-bit) is not compatible with bootstrap. Google chrome with Version 109.0.5414.120 is working fine .

Note: I tried with multiple bootstrap versions but faced same issue in all the bootstrap versions.

Please let me know what is causing these kind of issues.

Thanks,
Pavan

**Comment by mdo** [comment]
You haven't provided any information on meaningful regarding what's not working for you. Bootstrap won't just stop working in a browser, that's not how rendering websites works thankfully :). Guessing this is user error.

**Comment by PavanSaiSheshetti** [comment]
Ok, The actual issue is overlap of parent content on side nav bar. That couldn't let me to click on nav bar options . 
The wierd thing is, same code is working fine on older version of browser as I mentioned above but in the latest version it's getting failed. It's started failing from the past few days only. 
Not only that, alignement is getting changed and the whole application is not at all looking good. But as I mentioned the same code is working fine in older version of browser. No nav bar issue and no alignment issues in older version of browser. Tried with multiple bootstrap versions and still facing the same issue. 

Thanks,
Pavan

**Comment by mdo** [comment]
You'll have to follow the issue template instructions and produce a reduced example you can link us to. Otherwise we can't help.

**Comment by PavanSaiSheshetti** [comment]
Please find attached document with screenshots from different browsers.
Please check and let me know if you need further details .

Thanks,
Pavan 
[App_Css_Issue_Screenshot.docx](https://github.com/twbs/bootstrap/files/11021060/App_Css_Issue_Screenshot.docx)

**Comment by julien-deramond** [comment]
@PavanSaiSheshetti Please don't upload `docx` files (or any other zip files). For security purposes, I've edited your comment. Please upload your screenshots directly via the GitHub interface as images.

**Comment by PavanSaiSheshetti** [comment]
Ok, Adding the screenshot here. Please check and update me on the same.

Thanks,
Pavan
![Screenshot_20230321_081349](https://user-images.githubusercontent.com/70468631/226506677-e7f43857-a996-48ab-be10-1356379258e5.jpg)

**Comment by PavanSaiSheshetti** [comment]
Hello team,
    Any update on this issue, please revert back if any further details needed.

Thanks,
Pavan

**Comment by julien-deramond** [comment]
Hello @PavanSaiSheshetti 
As said before, without any reproducible example, we won't be able to help or answer.

> Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using CodePen ([v4 template](https://codepen.io/team/bootstrap/pen/yLabNQL) or [v5 template](https://codepen.io/team/bootstrap/pen/qBamdLj)).

Screenshots are not enough without any corresponding source code.
