### ISSUE TITLE
node-sass calc($val) issue

### ISSUE THREAD

**Issue by danny007in** [twbs/bootstrap#38278]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![image](https://user-images.githubusercontent.com/50356015/226170620-e5abad67-af41-44a6-860b-12c0993bbeae.png)

### Reduced test cases

https://codepen.io/danny007in/pen/LYJBqKa

solution is https://stackoverflow.com/questions/17982111/sass-variable-in-css-calc-function

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0-alpha1

**Comment by julien-deramond** [comment]
There's no description for reproduction. So, based on your screenshot, I suppose that you are in the Bootstrap repository.

There's no issue because running `npm run dist` generates our `dist/css/bootstrap.css`, which doesn't have any Sass var in the `calc` part: 
https://github.com/twbs/bootstrap/blob/a6d8aa827d645796cf986e289b7311360318a21f/dist/css/bootstrap.css#L1873-L1875

**Comment by danny007in** [comment]
please trigger this event 
```console
npx --package node-sass@latest node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/ -o dist-sass/css/
```
https://github.com/twbs/bootstrap/blob/cf9454caa00872899215603e5e036d9a824b1b11/.github/workflows/node-sass.yml#L35

**Comment by julien-deramond** [comment]
Thanks @danny007in  for adding new precisions in this issue. I could reproduce with your command and node-sass.
I'll try to add interpolation around Sass variables - `#{$myVariable}` where we can see errors.
And I'll check if there's a way that we compile it like this in our workflow to trigger errors if we can find any `$` in the generated file.

**Comment by mdo** [comment]
Do we explicitly support Node Sass? I feel like @XhmikosR and I talked about that ages ago before v5 went stable and it wasn't making the cut for us.

**Comment by XhmikosR** [comment]
We didn't drop support for node-sass because it was a breaking change IIRC, but we merely test if our Sass compiles with it. It's basically on a best effort case, so we try to make it work but there's no guarantee.

**Comment by julien-deramond** [comment]
In best-effort, I've added an extra check in https://github.com/twbs/bootstrap/pull/38283 that could allow us to help folks with node-sass. Using interpolation shouldn't be a particular issue or difficult to maintain. Let me finish the PR and we can decide if it is worth it or not maybe 🤷
