### ISSUE TITLE
V5 bootstrap@5.3.0-alpha1: Add default border-bottom to dropdown-item

### ISSUE THREAD

**Issue by devhoussam1998** [twbs/bootstrap#38272]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

```
.dropdown-menu {
  > .dropdown-item:not(:last-child),
  > li:not(:last-child) .dropdown-item {
    border-bottom: var(--#{$prefix}dropdown-border-width) solid
      var(--#{$prefix}dropdown-border-color);

    &:hover,
    &:focus {
      border-bottom-color: var(--#{$prefix}dropdown-link-hover-bg);
    }

    &:active,
    &:active {
      border-bottom-color: var(--#{$prefix}dropdown-link-active-bg);
    }
  }
}
```

### Motivation and context

-

**Comment by SantiagoPVazquez** [comment]
I would like to work on this issue. Is it just to implement the proposal code or to add more to it?

**Comment by devhoussam1998** [comment]
> I would like to work on this issue. Is it just to implement the proposal code or to add more to it?

yeah try to do it, thanks

**Comment by SantiagoPVazquez** [comment]
I'm sorry, I'm new at this. Could you point me to the file where I have to implement this? I think it's in _dropdown.scss file, am I right?

**Comment by devhoussam1998** [comment]
> I'm sorry, I'm new at this. Could you point me to the file where I have to implement this? I think it's in _dropdown.scss file, am I right?

you just need to fork the bootstrap repository and work on this feature then create a new PR make sure you follow the BS PR rules.

**Comment by SantiagoPVazquez** [comment]
Oh yeah I already have that done, but I'm a little lost in which file this code goes. I believe it goes in the **_dropdown.scss** file but I'm not sure.

**Comment by devhoussam1998** [comment]
> Oh yeah I already have that done, but I'm a little lost in which file this code goes. I believe it goes in the **_dropdown.scss** file but I'm not sure.

yeah in **_dropdown.scss**

**Comment by SantiagoPVazquez** [comment]
I posted a PR. I'm open to any changes or observations. Thanks for letting me contribute!

**Comment by mdo** [comment]
https://github.com/twbs/bootstrap/pull/38276#issuecomment-1475458749
