### ISSUE TITLE
Add a Timer Picker component to Bootstrap

### ISSUE THREAD

**Issue by yassin014** [twbs/bootstrap#38299]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

 **A time picker component** is a user interface element that allows users to select a specific time of day. It typically appears as a pop-up modal or a drop-down menu with options for selecting the hour, minute, and possibly AM/PM format.
Time pickers are commonly used in web applications for tasks such as setting the start or end time of an event or appointment, selecting a time range for filtering data, or setting a reminder or alarm. 

![68747470733a2f2f692e6962622e636f2f425a30566e79622f696d6167652e706e67](https://user-images.githubusercontent.com/118993199/226772981-4652e30c-46a3-44fd-a32b-5288c42e6037.png)

**In this example**, you can select the time with the hour and the minute and you can also select the AM/PM format also!

### Motivation and context

**Time pickers** are a common user interface element, Adding a time picker component to Bootstrap could make it more versatile and adaptable to a wider range of design needs, and provide developers with a new tool for creating more sophisticated and functional web applications. Time pickers can be implemented using HTML, CSS, and JavaScript.
A time picker component can provide users with a more convenient and intuitive way to interact with time-based data, Without a time picker, users may have to manually enter time values, which can be time-consuming and error-prone. A time picker component can help streamline this process and make it more user-friendly.

**Comment by mdo** [comment]
See https://github.com/twbs/bootstrap/pull/38312#issuecomment-1482208233.

**Comment by abhinav2712** [comment]
I am a bit confused, is this opened or closed? Since I dont see timer component in bootstarp(latest version)

**Comment by CyrilKrylatov** [comment]
> I am a bit confused, is this opened or closed? Since I dont see timer component in bootstarp(latest version)

It's closed as it's been answered in https://github.com/twbs/bootstrap/pull/38312#issuecomment-1482208233 😉
