### ISSUE TITLE
:first-child & :last-child remove the padding-top, padding-bottom from list-group

### ISSUE THREAD

**Issue by devhoussam1998** [twbs/bootstrap#38297]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

-

### Motivation and context

-

**Comment by yassin014** [comment]
hello devhoussam1988 can you please elaborate more about this feature so we can help you ?

**Comment by mdo** [comment]
No plans to make this change. Next time, please elaborate more on what you're proposing, and why. It's still not clear to me, but I don't see how this would be helpful in any situation.
