### ISSUE TITLE
Navs on iOS takes two lines

### ISSUE THREAD

**Issue by DorianCoding** [twbs/bootstrap#38306]
Hello and sorry if this issue is irrelevant or not in the right place.

I’m using bootstrap navs on my website but using iOS (Safari chrome or Firefox), the navbar takes two lines with nav-fill and nav-justify, even with Bootstrap own code on the website.
Is it a bug and if not, how to restrict on one line (make all elements smaller)?

Thank you!
A81F7D63-1EAE-4868-8DF9-14F69F8CC7DE
https://user-images.githubusercontent.com/108593662/227025054-b420831f-6263-45f1-b81b-a0fd7efc5913.png

**Comment by mdo** [comment]
This is expected, we don't set any automatic overflow or different wrapping for the nav links. Use the flex utilities and more to change this behavior as you need.
