### ISSUE TITLE
[Bootstrap v5.2.3][Minor bug][Modal] Initializing Modal through JS throws Uncaught TypeError: BACKDROP

### ISSUE THREAD

**Issue by gustaveWPM** [twbs/bootstrap#38307]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

```
Uncaught TypeError: Cannot read properties of undefined (reading 'backdrop')
    at Ni._initializeBackDrop (modal.js:158:39)
    at new Ni (modal.js:69:27)
    at Ni.getOrCreateInstance (base-component.js:65:41)
    at HTMLAnchorElement.<anonymous> (modal.js:364:22)
    at HTMLDocument.n (event-handler.js:118:19)
```

### Reduced test cases

Initialize a modal with:
```
      const m = document.querySelector(`#${lightboxId}`);
      new bootstrap.Modal(m).show();
      // Same issue with this code
      // const m_instance = new bootstrap.Modal(m);
      // m_instance.show();
```

### :information_source: Related issues

https://github.com/twbs/bootstrap/issues/33840

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2.3

**Comment by tertek** [comment]
> Ok, that was my fault. I was BOTH triggering modal with `data-bs-toggle="modal"` and `new bootstrap.Modal('#silly-me')`.

This was also the case for me. Thanks for sharing your solution!

**Comment by tonyschwartz** [comment]
This was killing me for a good while, but this gave me a tip.  In my case, I didn't realize I was calling show TWICE because of a duplicate listener on the button!!!  ( i.e., new bootstrap.Modal( document.getElementById('DivPersonModal'), {} ).show() )
