### ISSUE TITLE
Documentation Display on v4 Website

### ISSUE THREAD

**Issue by ryanwake01** [twbs/bootstrap#38311]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Nothing super important - just wondered if anyone had noticed that the display of your documentation on v4 has a big gap at the top of the page? The content is not at the top of the page you have to scroll to the bottom. 

### Reduced test cases

na

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

4

**Comment by mdo** [comment]
We're not actively maintaining v4 anymore, and without screenshot, link, or more info, we're not sure what exactly you're seeing that looks broken.
