### ISSUE TITLE
CSS variables approach in components not the best one

### ISSUE THREAD

**Issue by HybridSolutions** [twbs/bootstrap#38323]
For those who just want to customize BS using the provided CSS variables, they face a problem.
Since the generated variable values are concrete values, overriding component styles forces to a duplication of CSS code for each of the components to restyle and it's variants and also, a deep understanding of how the components mix with each other.

Why are these values being set as concrete values instead of using the color variables?

if color variables were used in components, changing colors across all of them would only require to change the color variables avoiding CSS like 

.btn-primary {
    --bs-btn-bg: red;
}
.btn-info {
    --bs-btn-bg: green;
}

Even some base BS variables use concrete values instead of color variables:

--bs-primary: #0d6efd; instead of --bs-primary: var(--bs-blue);

If the issue for not using color variables is because you need to generate lighter or darker colors, you can also do that using just CSS:

[Check this example of darkening a color set in a variable and using it on hover state](https://codepen.io/HybridSolutions/pen/JjaweoJ)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.2.3

**Comment by mdo** [comment]
Yes, this has been covered in our blog posts and issues—we're limited by backwards compatibility in changing key components like buttons and more. We're also limited by color manipulation in vanilla CSS vs Sass.
