### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by janswist** [twbs/bootstrap#38333]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Navbar dropdown (when on mobile or when screen is reflecting mobile viewport size) after selecting a link is not collapsing after link click with same page link by id.

It's basic standard Navbar from here: https://getbootstrap.com/docs/5.2/components/navbar/

Issue brought up in those places:
- https://stackoverflow.com/questions/42401606/how-to-hide-collapsible-bootstrap-navbar-on-click (one wrong answer got here over 200 upvotes)
- https://stackoverflow.com/questions/65341620/navbar-dropdown-collapse-is-not-working-in-bootstrap-5
- https://dev.to/ara225/bootstrap-collapsing-menus-without-jquery-4l8l

### Reduced test cases

```html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#somepage">Link</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2

**Comment by mdo** [comment]
You'll need to create a live example, not just a snippet of code. Please create a CodePen or similar demo.

**Comment by janswist** [comment]
Official [TWBS Vue](https://github.com/twbs/examples/tree/main/vue) example has this issue: https://stackblitz.com/github/twbs/examples/tree/main/vue?file=index.html 

Or is it a feature to NOT collapse menu after menu item click?

**Comment by mdo** [comment]
> Or is it a feature to NOT collapse menu after menu item click?

It is not, and if that's the issue you're referring to, I'll close this out.
