### ISSUE TITLE
Documentation: 4.3 page should inform about v5

### ISSUE THREAD

**Issue by clindh** [twbs/bootstrap#38331]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The documentation for version 4 should have a note about it beong older version and a link to version 5 doc

### Motivation and context

When I search for various Boostrap terms, Google gives me links to the version 4 documentation for example https://getbootstrap.com/docs/4.3/components/alerts/

IMHO these pages should have a note about outdated information, and a link to the most recent documentation - like on https://fontawesome.com/v5/docs

**Comment by mdo** [comment]
Want to take a stab at opening a PR? We've done similar banners on older versions: https://getbootstrap.com/docs/4.0/getting-started/introduction/.

**Comment by julien-deramond** [comment]
Tried something via https://github.com/twbs/bootstrap/pull/38410. Huge but seems to work rather well.
