### ISSUE TITLE
helpers/_color-bg.scss helpers/_colored-links.scss switch to css variables

### ISSUE THREAD

**Issue by robertzajda** [twbs/bootstrap#38347]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Switch from static color definitions to css variables.

Now we have:
```
.text-bg-primary {
  color: #fff !important;
  background-color: RGBA(13, 110, 253, var(--bs-bg-opacity, 1)) !important;
}

.link-primary {
  color: #0d6efd !important;
}
```

### Reduced test cases

--

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3-alpha

**Comment by mdo** [comment]
These already use CSS variables since alpha 2 shipped.
