### ISSUE TITLE
unistalling bootstrap

### ISSUE THREAD

**Issue by CajetanJohn** [twbs/bootstrap#38350]
How do I unistall bootsrap?

**Comment by CajetanJohn** [comment]
Its just sticking there even after nmp unistall, even after deleting allllllllllllllllllllllllllllllllllllllllllllllllllllllllll of its folders. I mean allllllllll. I even tried rebooting my desktop....It's stilll there

**Comment by julien-deramond** [comment]
If you installed it with `npm i bootstrap`, running `npm uninstall bootstrap` should be enough.
Without much information on how you installed it, it's going to be difficult to help :p
