### ISSUE TITLE
Scrollspy and French anchor links

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#38367]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Scrollspy behavior has changed between the v5.1 and the v5.2 regarding the handling of characters in anchor links/ids.
It was possible before to do the following:

```html
<nav id="navbar-example2" class="navbar bg-body-tertiary px-3 mb-3 rounded-2">
    <a class="navbar-brand" href="#">Navbar</a>
    <ul class="nav nav-pills">
      <!-- -->
      <li class="nav-item">
        <a class="nav-link" href="#présentation">Présentation</a>
      </li>
      <!-- -->
   </ul>
</nav>
<div class="scrollspy-example bg-body-tertiary p-3 rounded-2" data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" tabindex="0">
  <!-- -->
  <h4 id="présentation">Second heading</h4>
  <!-- -->
</div>
```

Now, using an id like "présentation" throws an error in the console:

> Uncaught DOMException: Element.querySelector: '#pr%C3%A9sentation' is not a valid selector

It is linked to https://github.com/twbs/bootstrap/issues/37545 and other issues in the past. Different opinions have been raised in comments on these issues and maybe not have been studied because the issues were already closed. Maybe we can reconsider it and provide a final answer based on more recent data.

I don't know what they use but for example, Wikipedia has such ids when the page is in French (e.g. https://fr.wikipedia.org/wiki/Bootstrap_(framework)#G%C3%A9n%C3%A9ralit%C3%A9s).

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier was mentioned as an answer but is more linked to CSS isn't it? But if I create the following, its works:

```css
#présentation {
  color: red
}
```

https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute seems more permissive and more linked to this issue considering only HTML.

---

/cc @Lausselloic

### Reduced test cases

- In v5.1: https://codepen.io/julien-deramond/pen/ExeJWEo
- In v5.2: https://codepen.io/julien-deramond/pen/OJoGpOK

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2

**Comment by ffoodd** [comment]
This is because [the `hash` property isn't URL decoded](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI). 

Using `decodeURI(anchor.hash)` in [our scrollSpy component](https://github.com/twbs/bootstrap/blob/bb33b4bb8fe0d9ce52e6e2753a514700ce58f1bc/js/src/scrollspy.js#L203) should solve this (but might be used elsewhere too, as long as we use the `hash` property).
[
Check your fixed Pen](https://codepen.io/ffoodd/pen/dygGxZK) to see the difference (in the console).

**Comment by alemendoza-v** [comment]
Could I work on this issue?

**Comment by alemendoza-v** [comment]
Im testing on the codepen created by @julien-deramond and it is not throwing an error

**Comment by alemendoza-v** [comment]
This is my first time creating a PR to this repository, could someone review it please? #38463

**Comment by alemendoza-v** [comment]
I added tests :)

**Comment by alemendoza-v** [comment]
Are the tests ok? :)

**Comment by julien-deramond** [comment]
@alemendoza-v Please wait until someone has the time to review https://github.com/twbs/bootstrap/pull/38463. The comments will be directly within the PR :) We'll get back to you as soon as possible.

**Comment by julien-deramond** [comment]
This issue can be closed. It has been fixed by https://github.com/twbs/bootstrap/pull/38502 in v5.3.0.
Here's a CodePen showing that it works again: https://codepen.io/julien-deramond/pen/dyLPjwK.
