### ISSUE TITLE
.colour-primary : set text, background, link and border colour in one go

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#38375]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

In would be nice to set all the colour attributes in one 
(so use  `.colour-primary` rather than `.text-primary .bg-primary .link-primary, .border-primary`  also sets the subtle colour for `.text-muted`)

Variations: `.colour-primary, .colour-outline-primary, .colour-subtle-primary`
```
<p class="colour-primary>now the <a href...>link colour is set to match</a>
and <span class="text-muted"> now its subtle primary</span></p>

<a class="btn colour-outline-info">button with blue text and borders on a white bg</a>
<span class="badge color-outline-danger">...</span>
<div class="alert colour-muted-success">green text and borders on a subtle green bg
<p class="colour-reset">back to black text on a white background with black borders if set</p>
```

Could simply use `.primary` to avoid the spelling issue

### Motivation and context

Simplify the colour options

**Comment by Firas-HadjKacem** [comment]
Hello, do you mean you would like to add the new classes colour-primary, colour-outline-primary, and colour-subtle-primary and style them as follows? 
.color-primary {
color: rgb(13, 110, 253);
background-color: transparent;
border-color: rgb(13, 110, 253);
}
.color-primary {
color: rgb(13, 110, 253);
background-color: transparent;
border-color: rgb(13, 110, 253);
}
.color-subtle-primary {
color: rgb(108, 117, 125);
background-color: rgb(248, 249, 250);
border-color: rgb(248, 249, 250);
}

**Comment by saturdaywalkers** [comment]
@Firas-HadjKacem

Not quite.
Set link and .text-muted colours as well

```
.colour-primary {
  color: rgb(13, 110, 253);
  background-color: transparent;
  border-color: rgb(13, 110, 253);
}
.colour-primary a { ... }
.colour-primary a: hover { .. }
.colour-primary .text-muted { ... }
```

**Comment by mdo** [comment]
We won't be adding this ourselves, thanks!
