### ISSUE TITLE
When my bootstrap is upgraded from 5.2.0 to 5.2.1, there will be a problem when the button is active. 

### ISSUE THREAD

**Issue by peipei818** [twbs/bootstrap#38379]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

when version is 5.2.0,.btn:active attribute is overridden.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/128784268/228754254-0da992f7-6e84-4480-98c5-ba82c34b7144.png">

But when version is 5.2.1,btn:first-child:active attribute cant overridden. 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/128784268/228754301-98cdb097-24e7-4986-ab90-dcad6a438de0.png">

How should this problem be solved?

### Reduced test cases

none

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0 to 5.2.1

**Comment by peipei818** [comment]
This is caused by the weight of the selector, but the weight of many button selectors in the project needs to be re-modified after the upgrade.

**Comment by mdo** [comment]
These selectors were changed back in v5.2.2, please upgrade.
