### ISSUE TITLE
Form-floating element have a before pseudo-element that overlaps the label

### ISSUE THREAD

**Issue by maikycourse** [twbs/bootstrap#38377]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

```css
.form-floating:not(.form-control:disabled)::before {
...
}
```
I have used the bootstrap@5.3.0-alpha2 with the css of the CDN "cdn.jsdelivr.net".
The form-floating elements have a before pseudo-element that overlaps the label and the input and prevents focusing on the input.
  I have also verified it with the form-floating elements of your documentation.

### Reduced test cases

https://getbootstrap.com/docs/5.3/forms/floating-labels/#example

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0-alpha2

**Comment by julien-deramond** [comment]
Thanks for opening this issue @maikycourse 
Could you try with the deployment of our current _main_ branch: https://twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/#example.
We have made some modifications yesterday. Might be fixed already.

**Comment by mdo** [comment]
This is fixed in `main` and alpha3 that's coming soon.
