### ISSUE TITLE
Add the new react example in docs

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#38370]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://github.com/twbs/examples/tree/main/react-nextjs

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

unrelated

**Comment by himanshusharma27** [comment]
Please assign me this issue .

**Comment by julien-deramond** [comment]
@himanshusharma27 we don't assign issues in this repo. If you think you can provide a solution, you can directly create a PR with a detailed description of your approach.

**Comment by mdo** [comment]
I think we should add them in both places @julien-deramond. Want to take a stab at that, plus the color modes one?

**Comment by julien-deramond** [comment]
Yep I'll create a PR soon
