### ISSUE TITLE
Copy button not consistently visible on Edge browser when window size is reduce

### ISSUE THREAD

**Issue by mootezaloui** [twbs/bootstrap#38382]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've noticed that when reducing the size of the browser window in the Edge browser, the copy button for code snippets in Bootstrap does not always appear. Sometimes it's visible, but other times it's hidden and requires scrolling to become visible.
![image](https://user-images.githubusercontent.com/77841233/228798723-82d45ba6-c5ca-4c22-bfc1-7125110f469f.png)

The copy button should always be visible on the page, regardless of the window size or device used to access the page.
![image](https://user-images.githubusercontent.com/77841233/228798798-e2ad8ce1-6ded-4b0a-b21a-494cee446b9d.png)

The copy button is not consistently visible on the page when reducing the size of the Edge browser window, making it difficult for users to copy code snippets.

### Reduced test cases

The addition of a media query that particularly targets Edge and makes sure the button is always displayed at all window widths is one potential fix. Another option would be to change the button's CSS to increase its adaptability to various screen widths.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.3(alpha)

**Comment by julien-deramond** [comment]
Confirmed issue. Can see the same thing on Firefox (macOS). Thanks for reporting this issue @mootezaloui.

**Comment by XhmikosR** [comment]
We hide the button on small screens IIRC. It's unrelated to the browser but was decided at some point to be this way.

**Comment by surajgjadhav** [comment]
Hi @julien-deramond , @XhmikosR ,
can I take this issue ?
I have found its root cause.
as mentioned by @XhmikosR, we just need to remove that `display: none` for small view and set `display:block` property for all view
Please do let me know
Thanks

**Comment by XhmikosR** [comment]
This was done by design by mdo, unsure what his take is now.
