### ISSUE TITLE
Tooltip not disposed after ajax request

### ISSUE THREAD

**Issue by HybridSolutions** [twbs/bootstrap#38388]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using tooltips on elements that cause a postback using ajax, tooltips do not hide and do not get disposed, leaving the tooltips in the DOM. Because I'm using ajax, I need to invoke the tooltip init script on every request causing for duplicate tooltip objects while the old ones lay around in the screen. There were some fixes for versions <=4 of BS but didn't find any for BS 5.3.

### Reduced test cases

As you can see, the tooltip remains in DOM after pressing that green button that causes an ajax request to load data and open a window.
![image](https://user-images.githubusercontent.com/8672899/229205904-b946886c-b6c0-4bc0-b206-5da60a74d6a7.png)

I'm using this code in a function to initialize tooltips:

`const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
 const tooltipList = Array.from(tooltipTriggerList).map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));`

What can I do to fix this issue?  

For now I'm manually cleaning the dom before initializing but it would be nice to have this controlled out of the box.

```
// Get all the tooltip elements that may exist in DOM and remove them
 const tooltipElements = document.querySelectorAll('.tooltip[role="tooltip"]');

// Loop through each tooltip element and remove it from the DOM
tooltipElements.forEach((tooltipElement) => {
      tooltipElement.remove();
});
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.0.alpha2

**Comment by regional83** [comment]
> Hello [@HybridSolutions](https://github.com/HybridSolutions). Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md), please create a reduced test case on [CodePen](https://codepen.io/) or [StackBlitz](https://stackblitz.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details.





https://acquaintance-flattering.github.io/tjnc0YZvZ80tM0UKqy8cfO0K6I2U9X7FlknwD0SrRpav7voz2AphfLAKUIobeU/
