### ISSUE TITLE
More consistent increments in padding and margin values

### ISSUE THREAD

**Issue by HybridSolutions** [twbs/bootstrap#38384]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Why the choice was made of incrementing .25 in padding values but in p-4 the value is incremented to x1.5 instead of 1? Even chatGPT agrees with me :) Here's the answer i got when asking to explain padding and margins increments in BS 5.3.0:

> In Bootstrap 5.3.0, the padding values in the px-* classes use a fixed increment of 0.25rem (which is equivalent to 4px in most modern browsers, assuming a default font size of 16px).
> 
> The px-* classes are shorthand classes for setting padding on all sides (top, right, bottom, left) of an element, where the * value ranges from 0 to 5 (inclusive) and represents the amount of padding to apply. Here are the specific values of padding (in rem) for each of the px-* classes:
> 
> .px-0 -> padding: 0;
> .px-1 -> padding: 0.25rem;
> .px-2 -> padding: 0.5rem;
> .px-3 -> padding: 0.75rem;
> .px-4 -> padding: 1rem;
> .px-5 -> padding: 1.25rem;
> As you can see, each increment of * (i.e., each higher px-* class) increases the padding by 0.25rem or 4px. This allows for consistent and predictable spacing between elements in your layout.

It's confusing that the x.25 ratio is not respected. What would be the value of a .px-6 and .px-7?

### Motivation and context

It's not intuitive.

**Comment by mdo** [comment]
It's not a linear scale, and it never has been. The scale is as follows:

- .p-0: 0
- .p-1: .25rem
- .p-2: .5rem
- .p-3: 1rem
- .p-4: 1.5rem
- .p-5: 3rem

And to expand that to additional steps, you might have something like:

- .p-6: 4.5rem
- .p-7: 6rem

Or you might have something like:

- .p-6: 6rem
- .p-7: 9rem

That all depends on how you want to scale the spacing. The original idea here is that you usually need a range of tighter spaces more often, and then even more options for creating white space at large sizes. Like having a 80px font size with 4px of padding isn't right, you need something to match the scale of that text.
