### ISSUE TITLE
examples - input fields in forms not user friendly - cannot click in large part of the input area

### ISSUE THREAD

**Issue by gregjotau** [twbs/bootstrap#38390]
https://getbootstrap.com/docs/5.3/examples/sign-in/

Say you click here: 

<img width="1470" alt="Screenshot 2023-04-01 at 16 29 13" src="https://user-images.githubusercontent.com/13047497/229295277-75882c13-2764-4242-b9a6-0b7fe6d6574c.png">

It does not work, it makes *no* sense and is user hostile IMO. Many times I by mistake clicked on the non-clickable area in the input field.

**Comment by julien-deramond** [comment]
Thanks for opening this issue @gregjotau.
It was linked to an issue of the floating labels.
It has been fixed recently in our main branch (see https://twbs-bootstrap.netlify.app/docs/5.3/examples/sign-in/) and will be available in the next v5.3.0-alpha3.
