### ISSUE TITLE
Update UI fixes

### ISSUE THREAD

**Issue by kumarankit999** [twbs/bootstrap#38408]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

In the dark mode footer section Font is in grey in color which is not looking so good .It should be in more lighter white, So that it will looks better and having Contrast.

![bootstrap](https://user-images.githubusercontent.com/111564362/229880042-6c172381-31e5-4b1d-94e6-e7e3a58a20b5.jpg)

### Motivation and context

if it is happened it will look Aesthetic and having contrast, such like white and black combination.

**Comment by igmtz** [comment]
Hey @kumarankit999 @julien-deramond ! Can I work on this issue? Is there any color palette I could follow for a lighter white?

**Comment by julien-deramond** [comment]
I can see that some PRs have already been created. But let's wait for @mdo thoughts here regarding chosen design.

**Comment by mdo** [comment]
Thanks, @julien-deramond! Footer is great as-is and meets minimum contrast ratios, especially for secondary text.
