### ISSUE TITLE
Text not displayed in dark mode in a navbar

### ISSUE THREAD

**Issue by offnikofficial** [twbs/bootstrap#38406]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The text is not displayed in dark mode, but in light mode it is displayed normally.

> Dark Mode:
>
> ![browser_RoXARs2cwk](https://user-images.githubusercontent.com/89143494/229841072-303cc3c8-1864-4cc3-83a2-d55fd0868cf3.png)

> Light mode:
> 
> ![browser_ZOCnuErkBH](https://user-images.githubusercontent.com/89143494/229841358-843bb333-4974-4d2c-bd81-9176faa47b7f.png)

### Reduced test cases

I fixed it with a new css style (.text-dark-light): _https://codepen.io/msmak-github/pen/YzJKGRx_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0-alpha3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @offnikofficial. Could you please update your CodePen? If I remove the `.text-dark-light` class, the rendering is OK because the body text color is based on `var(--bs-body-color)`. This is probably not how the navbar is implemented.

**Comment by offnikofficial** [comment]
Okay
