### ISSUE TITLE
Setting is-invalid on all parent nav-link buttons

### ISSUE THREAD

**Issue by Hvass-Labs** [twbs/bootstrap#38417]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Thanks for making Bootstrap, it has saved me a lot of time when making a nice-looking web-app, and I would not have been able to make it look this good myself!

I am using Bootstrap 5.2 and I have several nested tab-panes with many input-fields. When an input field is marked as `is-invalid`, I also need to mark all its parent tab `nav-link` buttons as invalid, so the user can easily see where the error is, without having to go through all the many nested tab-pages.

It would be very useful if I could set a class in the `nav-link` buttons such as `track-invalid-children`, which would set the class `is-invalid` if any child element has that class set.

As far as I know, this is currently not possible in Bootstrap, so I made the following solution, which almost took me a day to make as I'm not a Javascript programmer and had to investigate how everything works. Perhaps you can use this idea in Bootstrap, or at least it may be useful to other people who have the same need in the future. You should add the following to the bottom of your HTML page:

    <script>
    /** Recursively set the class "is-invalid" on all parent nav-link buttons.
      * This shows the user which nested tabs have errors in their input-fields.
      * @param elm: Starting HTML element object for the recursion.
      */
    function setParentTabsInvalid(elm) {
      // Get parent tab-pane.
      var tab_pane = elm.closest("div.tab-pane");

      // Does the tab-pane exist?
      if (tab_pane) {
        // Get HTML ID for the parent tab-pane.
        var id_tab = tab_pane.attr('id');

        // Does the HTML ID exist?
        if (id_tab) {
          // Get nav-link button for this tab.
          var button = $("button.nav-link[data-bs-target='#" + id_tab + "']");
  
          // Does the nav-link button exist?
          // Stop recursion if it has already been set to 'is-invalid'.
          if (button && !button.hasClass('is-invalid')) {
            // Add class 'is-invalid' to the tab-nav button.
            button.addClass('is-invalid');
            
            // Trigger a user mouse-click event on the button to select tab.
            button.trigger('click');

            // Recursively set parent nav-link buttons to 'is-invalid'.
            setParentTabsInvalid(button);
          }
        }
      }
    }

    // Extend jQuery with a reverse function that can be used before `each()`.
    jQuery.fn.reverse = [].reverse;

    /** Iterate over all input-elements with the class 'is-invalid' set, and
      * recursively set the class 'is-invalid' on all parent tab-nav buttons.
      */
    function setAllParentTabsInvalid() {
      // Process in reverse order to bring focus to elements in left-right order.
      $("input.is-invalid").reverse().each(function() { setParentTabsInvalid($(this)); });
    }

    // Run this at the bottom of the page after the page has been rendered.
    setAllParentTabsInvalid();
    </script>

The following should go in your CSS file:

    /* Tab contains invalid input-fields. Adapted from Bootstrap 5.2 */
    button.nav-link.is-invalid, button.nav-link.is-invalid.active {
       color: #dc3545;
       padding-right: calc(1.5em + 0.75rem);
       background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 12 12' width='12' height='12' fill='none' stroke='%23dc3545'%3e%3ccircle cx='6' cy='6' r='4.5'/%3e%3cpath stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/%3e%3ccircle cx='6' cy='8.2' r='.6' fill='%23dc3545' stroke='none'/%3e%3c/svg%3e");
       background-repeat: no-repeat;
       background-position: right calc(0.375em + 0.1875rem) center;
       background-size: calc(0.75em + 0.375rem) calc(0.75em + 0.375rem);
     }

This works as intended. Unfortunately I cannot show screen-shots as the web-app is still under "Top Secret" development :-)

### Motivation and context

-

**Comment by mdo** [comment]
Fun solution, but no plans to implement something like this on our end :).
