### ISSUE TITLE
Bootstrap's dark table heads become hoverable

### ISSUE THREAD

**Issue by NadChel** [twbs/bootstrap#38422]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I noticed that if I include the `table-dark` class in my `<thead>` element in my Bootstrap 4 page, it becomes hoverable as if it's a body row (which is silly)

If I remove it, everything's fine

If I add the `table-dark` class to the `thead tr` element, it gets hovered over on a permanent basis

Is it a bug worth fixing? It seems so to me

### Reduced test cases

<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <title>Admin Page</title>
        </head>
        <body>
        <div class="container">
            <div class="row">
                <table class="table table-hover text-center">
                          <thead class="table-dark">
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Last name</th>
                                    <th scope="col">Department</th>
                                </tr>
                          </thead>
                          <tbody>
                                <tr>
                                    <td>John</td>
                                    <td>Doe</td>
                                    <td>IT</td>
                                </tr>
                                <tr>
                                    <td>Jane</td>
                                    <td>Doe</td>
                                    <td>HR</td>
                                </tr>
                         </tbody>
                  </table>
              </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
        </body>
        </html>

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.3.1

**Comment by mdo** [comment]
**Sorry, but Bootstrap 4 is no longer being officially developed or supported.** We're only supporting v5 at this time. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding!

<3,
@mdo and team
