### ISSUE TITLE
Google Font Import In Bootstrap SASS Not Working

### ISSUE THREAD

**Issue by clarnx** [twbs/bootstrap#38429]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am using Bootstrap v 5.3.0-alpha1 with Next.js v 13.1.1. Every variable I add works well excess Raleway Google Font does not override the default Bootstrap font.

Below is the code in my sass file.

```scss
@import url("https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");

@import "bootstrap-icons/font/bootstrap-icons.css";

$success: #17c964;
$danger: #f21361;
$warning: #f5a623;

$font-weight-bolder: 900;

$font-family-sans-serif: "Raleway", system-ui, -apple-system, "Segoe UI", Roboto,
    "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
$font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas,
    "Liberation Mono", "Courier New", monospace;

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";
@import "bootstrap/scss/utilities/api";
@import "bootstrap/scss/bootstrap";
```

### Reduced test cases

```scss
@import url("https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");

@import "bootstrap-icons/font/bootstrap-icons.css";

$success: #17c964;
$danger: #f21361;
$warning: #f5a623;

$font-weight-bolder: 900;

$font-family-sans-serif: "Raleway", system-ui, -apple-system, "Segoe UI", Roboto,
    "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
$font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas,
    "Liberation Mono", "Courier New", monospace;

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";
@import "bootstrap/scss/utilities/api";
@import "bootstrap/scss/bootstrap";
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by julien-deramond** [comment]
Thanks for opening an issue @clarnx.

Please include a **live demo** of the issue by creating a reduced test case on [StackBlitz](https://stackblitz.com/) for example.

I tried your example in a Bootstrap Vite project, and the font is correctly downloaded and displayed on the page.

Few improvements in what you provided (but it has probably no impact on your use case):
- Don't `@import "bootstrap/scss/bootstrap";` at the end since you're importing before only what you need already
- `@import "bootstrap/scss/functions";` must be placed before the override of your functions
