### ISSUE TITLE
margin is not provided properly to clipboard component in small screen view

### ISSUE THREAD

**Issue by surajgjadhav** [twbs/bootstrap#38427]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

right margin is not set properly for clipboard in mobile view.
![image](https://user-images.githubusercontent.com/31582237/230725351-db5a9fa8-ff71-4820-bbec-8bf817e3e05e.png)

right now it has negative margin, but it should be positive
also from aesthetic point of view, it should ideally in line with the paragraphs.
![image](https://user-images.githubusercontent.com/31582237/230725606-7f08e29f-3f4f-4258-bc75-49543673a37b.png)
 
Please Suggest
Thanks

### Reduced test cases

it should ideally in line with the paragraphs.
we can do that by setting left and right margin of clipboard to 0rem in mobile view as below:
![image](https://user-images.githubusercontent.com/31582237/230725806-07af7e34-4bb7-4808-9aac-80187f1e4f44.png)

if you are considering this as an issue, then I will be happy to fix it.
Please do provide your feed back 
Thanks

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

v5.3.x

**Comment by mdo** [comment]
Eh, I kind of like it how it is—our code snippets go full width on mobile when not nested in list items. This is indented, but goes to the right edge entirely. Let's leave as-is for now :).
