### ISSUE TITLE
Selected options in .form-select[multiple] have poor styling

### ISSUE THREAD

**Issue by bggardner** [twbs/bootstrap#38454]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The styling of selected options for multiple selects appears out-of-family as the highlight is restricted to the `<option>` tag, inside padding of the parent `<select>`.  Removing the `<select>` padding and adding padding to the `<option>` tags would result in a better appearance.  See the CodePen for comparison to possible fixes, which have been verified in multiple browsers:
* **Poor**: As-is
* **Good**: Move horizontal padding from `<select>` to `<option>`
* **Better**: Move all padding from `<select>` to `<option>`

### Reduced test cases

https://codepen.io/bggardner/pen/GRYpLeg

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by hamzakhalidchouhdary** [comment]
can I take this issue @julien-deramond?

**Comment by julien-deramond** [comment]
We don't assign issues @hamzakhalidchouhdary.
We haven't checked the content of this issue yet but if this is obvious that a modification is needed, you can propose a PR :)

**Comment by hamzakhalidchouhdary** [comment]
ok thanks, @julien-deramond 
I will work on this.

**Comment by mdo** [comment]
As far as I know, this is still not addressable with vanilla CSS across all browsers. For example, none of these options look any kind of good in Safari. If that ever changes, we could implement some improvements here.
