### ISSUE TITLE
 Issue with Hardcoded Height of Form-Controls in Bootstrap 5's Floating Labels

### ISSUE THREAD

**Issue by owaisahmed5300** [twbs/bootstrap#38456]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,
I noticed that in Bootstrap 5, the form-control heights are hardcoded when using floating labels. Specifically, the following CSS lines are responsible:

```
.form-floating>.form-control, .form-floating>.form-control-plaintext, .form-floating>.form-select {
    height: calc(3.5rem + var(--bs-border-width)*2);
    line-height: 1.25;
}
textarea.form-control {
    min-height: calc(1.5em + 0.75rem + var(--bs-border-width)*2);
}
```

These lines prevent us from setting the height of a textarea using the rows attribute, as we would normally do. Instead, we are forced to define the height for each text area individually, which is not ideal.

I would suggest considering a modification to these CSS rules to allow the use of the rows attribute for setting the height of Textareas wherever possible, as this is a more convenient and intuitive method.

This isn't as urgent but I just enclosed this issue so you can release a fix in upcoming version of bootstrap.

Thank you for your attention to this matter.

### Reduced test cases

rows="" attribute doesn't work on textarea when inside bootstrap floating labels. We need to manually specify the height of each texatrea which is inconvenient.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
For consistency with other form controls—text and select—we'll keep it as height only for this component.

**Comment by owaisahmed5300** [comment]
Hi,
Is there any possibility to exclude textarea with attribute rows?

**Comment by owaisahmed5300** [comment]
keep height auto on textarea with form control class under floating labels? or we can use height auto on textarea with attribute rows specified? this is the preferred way because right now we are overriding the behavior of the rows attribute and making it completely useless.  Use the min-height instead and keep space for the row attribute.
