### ISSUE TITLE
Propagating shown.bs.tab event into nested tabs

### ISSUE THREAD

**Issue by Hvass-Labs** [twbs/bootstrap#38457]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Thanks again for making Bootstrap!

I am using Bootstrap 5.2 in a web-app with large input-forms, some of which have more than 200 input-fields and about 40 plots. These are organized in nested tabs. Because the backend plotting is a bit slow, and it is unlikely the user is going to look at all 40 plots, I want to lazy-load the plots. But as they need to use data from the input-fields, this is apparently not supported by typical lazy-load features in HTML and Bootstrap.

## Solution 1

My first solution was to catch the Javascript event `onFocus` in the tab-button, but this does not work for nested tabs, because the event only fires in the outer tab and does not propagate into the inner nested tabs that become visible. Similarly the Bootstrap event `shown.bs.tab` also does not propagate into the nested tabs that become visible.

So I had to render the plots in each of the first nested tabs, but the other plots could be lazy-loaded using the `onFocus` event, as the user would have to click those nested tab-buttons so the event would fire.

## Solution 2

My second solution was to catch the `shown.bs.tab` event in the tab-button, and recursively follow the `active` tab-buttons into the nested tabs, until we get to the inner-most tab-pane where there are no more nested tabs, at which point we find a `div` element with a certain class such as `lazy`, and then call the lazy-load function with that element's ID.

## Load-Time

The load-time was around 30 seconds without any lazy-loading. With the 1st solution above the load-time was around 3 seconds, and with the 2nd solution it was only around 0.1 second! So this makes a huge difference in user-experience!

Of course, the plots still have to be rendered when the user clicks a tab-button, but it is fast enough when it is just one plot at a time.

## Bootstrap Solution?

My solution is probably too specific for inclusion into Bootstrap, but perhaps you could make a more elegant and general solution, e.g. by having a class `propagate-shown` which would propagate `shown.bs.tab` events into the *active* nested tabs?

## Code

Even if you don't want to make support for this in Bootstrap, I thought I would share my solution, because I have spent a long time trying to figure out how to do this best. So this may save someone else a lot of time, especially people like myself who are not really web-developers.

The following script should go in your Javascript-file or at the bottom of your HTML-file.

    <script>
    /** Setup event-handler to lazy-load HTML elements, also inside nested tabs.
      * This is necessary because the `onFocus` and `shown.bs.tab` events that fire
      * when the user switches tabs, do not propagate into the nested tabs. So this
      * catches the Bootstrap event 'shown.bs.tab' in 'nav-link' tab-buttons, and
      * then recursively follows the *active* nested tab-buttons to the bottom,
      * where it then finds the element <div class='lazy' id='XYZ'> and
      * then calls `ajaxLazy(id='XYZ')`
      */
    function setupHandlerLazy() {
      // Catch the Bootstrap event 'shown.bs.tab' on all tab-buttons.
      // We could make a specific class to only catch the event for nested tabs,
      // but that would make the HTML templates more complicated, and this is so
      // fast to execute even for tab-buttons that don't have nested tabs.
      $('button.nav-link').on('shown.bs.tab', function (event) {
        // Get the tab-button that was activated.
        var button = $(event.target);

        // Tab-pane that the tab-button targets. This will be found below.
        var tab_pane = null;

        // Find the inner-most nested and *active* tab-pane.
        while (button) {
          // Get the HTML ID for the button's target tab-pane.
          var tab_id = button.attr("data-bs-target");

          // Terminate the iteration unless we find a nested active button below.
          button = null;

          // Does the tab-ID exist?
          if (tab_id) {
            // Get the tab-pane.
            tab_pane = $(tab_id);

            // Does the tab-pane exist?
            if (tab_pane) {
              // Find the first nested and *active* tab-button.
              // This will continue the while-loop into the nested tab.
              button = tab_pane.find('button.nav-link.active:first');
            }
          }
        }

        // If we found a tab-pane, it must be the inner-most / bottom nested tab.
        if (tab_pane) {
          // Find the "lazy" <div> element inside this tab-pane.
          var lazy = tab_pane.find('div.lazy:first');

          // Does the lazy element exist?
          if (lazy) {
            // Get the HTML ID for the lazy element.
            var lazy_id = lazy.attr('id');

            // Does the HTML ID exist?
            if (lazy_id) {
              // AJAX lazy-loading of the element. (Function not shown here.)
              ajaxLazy(id=lazy_id);
            }
          }
        }
      })
    }
    </script>

You should then call the function `setupHandlerLazy()` in a script at the bottom of your HTML-file to enable it.

### Motivation and context

-

**Comment by lekoala** [comment]
@Hvass-Labs don't bother too much, it's just much easier to use intersection observer. it will trigger as soon as the tab is active and you can setup relevant init code there
you can find an example here https://bs-companion.vercel.app/bs-tabs.html (where i have a custom lazy-loader custom element that does exactly just that)

**Comment by Hvass-Labs** [comment]
@lekoala Thanks very much! I came across the `IntersectionObserver` API when trying to find a solution for lazy-loading, but it looked very complicated as I am not a web-developer. But you're right that it was fairly easy to implement and it works great!

Here's my solution that may perhaps help others in the future:

    <script>
    /** Setup event-handler to lazy-load HTML elements, also inside nested tabs.
      * This registers all the HTML elements with an IntersectionObserver, which
      * triggers an event whenever the element becomes visible to the user,
      * so the element's contents can be lazy-loaded.
      */
    function setupHandlerLazy() {
      // Create a new observer object that triggers when elements become visible.
      const observer = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
          if (entry.intersectionRatio > 0) {
            // Element became visible to the user.

            // Get the HTML ID for the lazy element.
            var lazy_id = entry.target.id;
            
            // Does the HTML ID exist?
            if (lazy_id) {
              // AJAX lazy-loading of the element. (Function not shown here.)
              ajaxLazy(id=lazy_id);
            }
          }
        });
      });

      // Register the HTML elements that need lazy-loading.
      document.querySelectorAll("div.lazy").forEach((element) => {
        observer.observe(element);
      });
    }
    </script>

As this solves my problem, I currently don't have any need for propagating `shown.bs.tab` events anymore, so I have closed this issue.
