### ISSUE TITLE
Navs and Tabs nav-underline issue

### ISSUE THREAD

**Issue by tomtomu** [twbs/bootstrap#38465]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Difference between your cdn link and download to server

```html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
```

When adding the above link to the head of html page, the nav nav-underline class does not work.

If I download bootstrap to my server they work, but floating labels have a white background. This is noticeable when the browser puts in a background color on the input for saved password etc. 

The white background does not show when using the cdn link only when using the downloaded version. The white background seems undesirable.

### Reduced test cases

![Sample](https://user-images.githubusercontent.com/96202544/232190247-58896831-a4fe-4af5-a8e1-aeef6e9a344d.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by julien-deramond** [comment]
Thanks for opening this issue @tomtomu but you got a problem with the `href` value. From what I know, it can be `//cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css` or `https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css` but not without any protocol like you have: `cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css`.

Is it something we have in our documentation? That's not the case in the [CDN via jsDelivr](https://getbootstrap.com/docs/5.3/getting-started/download/#cdn-via-jsdelivr) docs but it can be somewhere else.

**Comment by tomtomu** [comment]
Not sure how to provide a better example than the screenshot I uploaded. Seems pretty clear.
