### ISSUE TITLE
CSS: Some custom properties are not declared or initalized

### ISSUE THREAD

**Issue by lecaregmbh** [twbs/bootstrap#38474]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the css file multiple custom properties are not declared and not initialized. 

```
body {
...
  text-align: var(--bs-body-text-align);
....
}
```
**bs-body-text-align** is not declared.

```
.nav-link {
...
  font-size: var(--bs-nav-link-font-size);
...
}
```
**bs-nav-link-font-size** is not declared.

```
.navbar-nav-scroll {
...
  max-height: var(--bs-scroll-height, 75vh);
...
}
```

**bs-scroll-height** is not declared

```
.breadcrumb {
...
  font-size: var(--bs-breadcrumb-font-size);
...
}
```
**bs-breadcrumb-font-size** is not declared.

```
.breadcrumb-item + .breadcrumb-item::before {
... 
 content: var(--bs-breadcrumb-divider, "/") /* rtl: var(--bs-breadcrumb-divider, "/") */;
...
}
```
**bs-breadcrumb-divider** is not declared.

And additionally, mutiple custom properties are declared, but not initalized. 

For example: 

```
.card {
...
  --bs-card-cap-color: ;
  --bs-card-height: ;
  --bs-card-color: ;
...
}
```

### Reduced test cases

The bugs are also included in the compiled version 5.2.3

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.2.3

**Comment by mdo** [comment]
Most of these are because we have `null` value Sass variables. This is especially true for `color` and `font-size` values where we assume an inherited value. The breadcrumb divider and nav max-height are there as optional override variables, so there's no default assigned value needed.
