### ISSUE TITLE
Improve tab navigations accessibility with `Home` and `End` keys

### ISSUE THREAD

**Issue by Rezyan** [twbs/bootstrap#38471]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I suggest to improve tab navigations (e.g. `.nav-tabs`) accessibility with the keyboard:
- `Home`: moves focus to the **FIRST** tab and activates it.
- `End`: moves focus to the **LAST** tab and activates it.

The idea is taken from the [W3C example](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/#kbd_label).

### Motivation and context

This could be useful for users using keyboards, and this enhancement would be the continuation of https://github.com/twbs/bootstrap/pull/33079 (keyboard accessibility with arrow keys).

I've already implemented it in one of my website. This is much the same as the [implementation for arrow keys](https://github.com/twbs/bootstrap/blob/bb33b4bb8fe0d9ce52e6e2753a514700ce58f1bc/js/src/tab.js#L153-L167). My jQuery code looks like below:

```js
$(document).on('keydown', '.nav-link[data-bs-toggle="tab"]', (event) =>
{
	if (['Home', 'End'].includes(event.key))
	{
		event.preventDefault();
		const $tabs = $(event.currentTarget).parents('.nav[role="tablist"]').find('.nav-link[data-bs-toggle="tab"]').not('.disabled');
		const $tabToShow = (event.key === 'Home') ? $tabs.first() : $tabs.last();
		$tabToShow.get(0).focus({
			preventScroll: true
		});

		$tabToShow.tab('show');
	}
});
```

**Comment by yashviradia** [comment]
Hi, 
I would like to work on this issue. 
Could you pl assign it to me?

**Comment by Harrypotter19876** [comment]
> Hi, I would like to work on this issue. Could you pl assign it to me?

 Hoi kan ja me helben

**Comment by Harrypotter19876** [comment]
Wat zijn we aan het doen
