### ISSUE TITLE
key.split("+") at is not a function in safari

### ISSUE THREAD

**Issue by abhilash-linkites** [twbs/bootstrap#38472]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In safari I am getting below error 
key.split("+") at is not a function
![Screenshot 2023-04-17 at 12 11 34 PM](https://user-images.githubusercontent.com/98375367/232404607-e59259b8-0e7a-481e-bb43-fe990e8a0fd5.png)

### Reduced test cases

install bootstarp and run it on safari

### What operating system(s) are you seeing the problem on?

macOS, iOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

^5.2.3

**Comment by enumiton** [comment]
<img width="461" alt="Screenshot 2023-04-17 at 9 56 48 AM" src="https://user-images.githubusercontent.com/41439661/232421593-506c3626-6684-4ac0-b5df-882a6c117a87.png">

**Comment by abhilash-linkites** [comment]
No worries I fixed it.
