### ISSUE TITLE
The svg image code should contain a title tag, which is good for SEO

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#38487]
https://developers.google.com/search/docs/appearance/google-images#descriptive-alt-text

https://github.com/twbs/bootstrap/blob/be0206fe31481b8f300a7001411835497200dade/site/layouts/partials/docs-navbar.html#L95-L117

This change will affect many places where svg images are used
such as the following and more

https://github.com/twbs/bootstrap/blob/main/site/layouts/partials/icons.html
https://github.com/twbs/bootstrap/blob/main/site/static/docs/5.3/assets/js/color-modes.js
https://github.com/twbs/bootstrap/tree/main/site/layouts/partials/icons

Of course, this is not a key issue, it is just beneficial to SEO, it will not determine the effect of the picture, it is just for reference.

**Comment by mdo** [comment]
Super low priority, but if you want to jam on it, we can review PRs.

**Comment by Redoni18** [comment]
PR for issue: https://github.com/twbs/bootstrap/pull/39273

**Comment by patrickhlauke** [comment]
I'd say this is highly unnecessary, as there is already adjacent text that acts as the accessible name for controls etc that then contain the `<svg>`s.
