### ISSUE TITLE
form-select-sm cuts off bottom border of a select in Chrome

### ISSUE THREAD

**Issue by Nuklon** [twbs/bootstrap#38492]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A screenshot is worth a thousand words:

![image](https://user-images.githubusercontent.com/23340481/233692474-c7789b71-a602-4b92-9c22-9fd54934ea0c.png)

### Reduced test cases

https://stackblitz.com/edit/bootstrap-5-kxk9or?file=src%2Findex.html

Or in codepen (can't save, no account):

```html
<div class="container py-5">
   <select id="quantity" class="form-select form-select-sm">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3

**Comment by DenisLopatin** [comment]
Hi! Windows 10, Chrome 112.0.5615.138, the problem could not be reproduced... Current link `https://stackblitz.com/edit/bootstrap-5-kxk9or?file=src%2Findex.html` it also displays everything correctly.

Maybe this problem is taken out of some context? Bootstrap v. 5.2.3

**Comment by Nuklon** [comment]
Not for me (also in Edge). It might be due to DPI scaling? I run at 150%.

**Comment by DenisLopatin** [comment]
> Not for me (also in Edge). It might be due to DPI scaling? I run at 150%.

You can easily check this. Just go back to 100%))

**Comment by mdo** [comment]
This isn't something we can change, the options shown from a `<select>` aren't customizable in CSS.
