### ISSUE TITLE
Bootstrap UI Library - Reducing Unused CSS and JS

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/bootstrap#38490]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal
Bootstrap is a widely used UI library for web development, but it comes with a large size of CSS and JS files, including many features that may not be necessary for all users. For example, the library includes multiple color variations for tables, buttons, spinners, progress bars, placeholders, navbars, list groups, cards, and alerts, but users typically use only one or two colors.

#### Problem:
Problem:
The size of Bootstrap's CSS and JS files is too large and may cause slower loading times and increased page weight. Additionally, including unnecessary features can make the library more complicated to use and require more customization.

#### Proposal:
- Reduce the number of color variations and components included in Bootstrap.
- Only include the most commonly used components, such as buttons, forms, and typography.
- Allow users to customize their own color scheme or choose from a few pre-defined options.
- Create a lightweight version of Bootstrap with only the most essential components.

#### Context:
- Bootstrap library is very large in size due to various color variations and components.
- Most users only need one or two colors and only use a few components.

#### Motivation:
- Smaller file sizes will improve website load times and performance.
- A simplified version of Bootstrap will be easier for developers to use and navigate.
- More customization options will allow developers to create unique designs while still using the Bootstrap framework.
- Improving user experience will lead to more satisfied users and increased usage of Bootstrap.

**Comment by mdo** [comment]
You can already accomplish the size improvements by properly configuring your Sass and JS imports. This gives you complete control over what comes in and gets compiled to browsers. Color theme improvements are coming in v5.3+ and v6. No plans to create a lightweight version of Bootstrap beyond our existing grid, utilities, and Reboot options that we already include.

**Comment by ayoubkhan558** [comment]
> You can already accomplish the size improvements by properly configuring your Sass and JS imports. This gives you complete control over what comes in and gets compiled to browsers. Color theme improvements are coming in v5.3+ and v6. No plans to create a lightweight version of Bootstrap beyond our existing grid, utilities, and Reboot options that we already include.

Ok that's fine, but what about removing additional colors for "tables, buttons, spinners, progress bars, placeholders, navbars, list groups, cards, and alerts"
