### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by BaljitSinghDeveloper** [twbs/bootstrap#38501]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://getbootstrap.com/docs/5.2/components/toasts/

problem in Toasts Page at some close card remove Style  z-index  and after solve this problem permanent 
 

### Reduced test cases

https://getbootstrap.com/docs/5.2/components/toasts/

problem in Toasts Page at some close card remove Style  z-index  and after solve this problem permanent 
 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

latest

**Comment by julien-deramond** [comment]
Closing it since there's no detail in the description. Can't confirm what "problem in Toasts Page at some close card" is.
What problem? In which example(s)?
