### ISSUE TITLE
Sanitizer doesn't allow sip in href. Sip links are used for messaging like in Microsoft Teams.

### ISSUE THREAD

**Issue by Banner-Keith** [twbs/bootstrap#38519]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I wasn't sure if this would be considered a bug or feature request.

The sanitizer doesn't recognize sip as a valid type of url.

https://github.com/twbs/bootstrap/blob/1fcae4393c9a723fffa5d8e923ab9f2050ac6273/js/src/util/sanitizer.js#L24

The pattern should be 
`const SAFE_URL_PATTERN = /^(?:(?:https?|mailto|ftp|tel|file|sms|sip):|[^#&/:?]*(?:[#/?]|$))/i`

An example of how this is used is like this:

`<a href="sip:name@example.com">Chat</a>`

And when you click the link an application such as Microsoft Teams can open a direct chat to that person.

### Motivation and context

I am trying to show a chat link in a popover and this is keeping me from being able to do that while still sanitizing the popover.

I'd love to see this make it into 5.3.0. Happy to open a PR if you'd like. Where this change has such low impact I'm hoping it can be added quickly.

**Comment by julien-deramond** [comment]
I haven't checked in detail the topic but I can see in the comments that we currently rely on the `SAFE_URL_PATTERN` which was defined in https://github.com/angular/angular/blob/12.2.x/packages/core/src/sanitization/url_sanitizer.ts (so Angular 12.2.x).

So maybe we could switch to the new one present for example in the Angular source file: https://github.com/angular/angular/blob/main/packages/core/src/sanitization/url_sanitizer.ts which seems to offer more freedom (it has been modified one month ago via https://github.com/angular/angular/pull/49659/files):

`const SAFE_URL_PATTERN = /^(?!javascript:)(?:[a-z0-9+.-]+:|[^&:\/?#]*(?:[\/?#]|$))/i;`

Thoughts @twbs/js-review?
