### ISSUE TITLE
Does the form-control type="time" have a 24 hour function?

### ISSUE THREAD

**Issue by navysoccer23** [twbs/bootstrap#38533]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

When using the class = "form-control" type = "time" it defaults to 12 hour format. Is there any way to switch to 24 hour format? Thank you.

### Motivation and context

<div class="col-6 mx-1">
                              <label for="inputOnTime" class="">On Time Lnch</label>
                              <input data-type="entry" data-id="OnLnchTime" type="time" class="form-control px-1" 
                              id="inputOnTime">
</div>

**Comment by chetna-22** [comment]
Can i work on this issue?

**Comment by mdo** [comment]
That's an HTML spec question, and not something that we have control over. Appears to be based on user's locale. https://stackoverflow.com/questions/13523060/how-to-change-the-time-format-12-24-hours-of-an-input/13523302#13523302
