### ISSUE TITLE
Placeholder component wave animation not working in Edge

### ISSUE THREAD

**Issue by StepanMynarik** [twbs/bootstrap#38544]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

I'm using Bootstrap 5.2.3 in my Vite project. Installed based on Vite Getting started guide from the docs approximately a year ago.

Everything has been working great so far, except for the placeholder-wave animation.

I noticed that the **mask** attributes located in the `placeholder-wave` class have `-webkit` prefixed variants on the docs site where the animation works for me in the same browser, but are missing on my site.

As soon as I add the prefixed variants the animation starts working.

Any idea what might be wrong? Why are these prefixes not added to the bootstrap final css on my site?
It's like I'm not getting Autoprefixer sanitized Bootstrap css on my website. But I thought Bootstrap.scss I'm referencing from the Bootstrap package is already supposed to be sanitized?

### Reduced test cases

v5 template:
```
<div class="container py-5">
  <h1 class="h2">Bootstrap v5 Bug Report</h1>
  <p class="placeholder-wave">
    <span class="placeholder col-12"></span>
  </p>
</div>
```
Here it works so I'm not sure what I'm doing wrong on my site. Followed the Vite Getting started guide to bit.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.2.3

**Comment by Michael-Du-521** [comment]
# 1

# 2

# 3

**Comment by ffoodd** [comment]
I think you need Autoprefixer. We use it under the hood to keep vendor prefixes up-to-date based on supported browsers (defined in `.browserlistrc`).

**Comment by StepanMynarik** [comment]
Oooh... I thought it's somehow being used by Bootstrap npm package to postprocess bootstrap code so I don't have to integrate it (autoprefixer) at all.

So it's not like there is a bug in Bootstrap and it's just problem on my end by not using Autoprefixer? Hence all Bootstrap code is without any vendor prefixes on my end?

**Comment by StepanMynarik** [comment]
With **Vite** I just added the following into the _vite.config.ts_ and it works now.
```
  css: {
    postcss: {
      plugins: [autoprefixer()],
    },
  },
```

**Comment by mdo** [comment]
I haven't seen too many issues on the missing Autoprefixer, let's leave things as they are unless there's a recommendation. Happy to accept new PRs.
