### ISSUE TITLE
Modals do not work within sticky-top or fixed-top DIVs

### ISSUE THREAD

**Issue by neoschronos** [twbs/bootstrap#38561]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When opening a modal from within a sticky-top or fixed-top div, the backdrop of the modal is placed on top, rendering the modal unusable.

### Reduced test cases

https://codepen.io/neoschronos/pen/NWOybmx

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by julien-deramond** [comment]
Thanks for opening this issue @neoschronos 
For security purpose, I've edited your description to remove the link to the `.docx` file. Please use directly Markdown and/or add a reproducible reduced test case via CodePen, StackBlitz or any other tools.

**Comment by neoschronos** [comment]
hi @julien-deramond 
Here us the pen https://codepen.io/neoschronos/pen/NWOybmx

**Comment by julien-deramond** [comment]
Depending on what you're trying to achieve, can't you let the text and the button in the `.sticky-top` `<div>` and then declare the modal outside of it? I don't see easily a use case where the modal would need to be in the `.sticky-top` `<div>`.

```html
<div class="sticky-top">
  Test of modal within sticky-top, fixed-top does not work	
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button>
</div>

<!-- Big content -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <!-- ... -->
  </div>
</div>
```

**Comment by neoschronos** [comment]
Hi @julien-deramond,

The use case I have is a page structure like this

```
<header class="fixed-top"></div>
<aside class="sticky-top">...</div> <main>...</div>
<footer>...</footer>
```

Pretty much like the structure in https://getbootstrap.com/docs/5.3/getting-started/introduction/

In the `<aside>` element I have functions like **Import**, **Export**, **Delete**, that call Modals. In my opinion the modals are reasonably positioned within the `<aside> ` element, _near_ the buttons that trigger them. `<main> ` does not seem appropriate.

I appreciate the workaround (many thanks!) which works. I still maintain this is a bug.

I hope this makes sense.

**Comment by mdo** [comment]
@julien-deramond is right, closing per https://github.com/twbs/bootstrap/pull/38590#issuecomment-1571234922.
