### ISSUE TITLE
themes.getbootstrap.com - missing account, login/register/reset bug

### ISSUE THREAD

**Issue by bbprojectnet** [twbs/bootstrap#38579]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

Month ago i purchased a theme at themes.getbootstrap.com, now...

When i try to login to themes.getbootstrap.com i get "Login failed, please try again"
when i try to reset my password i get "Invalid username or email."
when i try to generate re-download link i get "We couldn't find any orders for that email address"
finally, when i try to create a new account i get "Error: **An account is already registered** with your email address. Please log in."

so, how i can access to my account to re-download purchased theme?

I can't get any answer or help from themes@getbootstrap.com since few days.

### Reduced test cases

Look at issue description.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

Any

**Comment by julien-deramond** [comment]
Sorry, but this isn't the place for Themes support. This website is not handled in this repository.

**Comment by bbprojectnet** [comment]
So how else can I get help if address themes@getbootstrap.com is dead? This repository is the only other way of contact that exists, so don't mind me.
