### ISSUE TITLE
Dark mode - manually using the ‘class’ strategy

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#38571]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I have realized in dark mode. I can't set dark mode manually using the ‘**class**’ strategy.

have any available option of Something like below example ?  according to [Tailwind css dark mode](https://tailwindcss.com/docs/dark-mode).

```
<!-- Dark mode not enabled -->
<html data-bs-theme="light">
<body>
  <!-- Will be white -->
  <div class="bg-white dark:bg-dark">
    <!-- ... -->
  </div>
</body>
</html>

<!-- Dark mode enabled -->
<html data-bs-theme="dark">
<body>
  <!-- Will be black -->
  <div class="bg-white dark:bg-dark">
    <!-- ... -->
  </div>
</body>
</html>
```

### Motivation and context

if you are any provide option something like. that will great for dark mode easily manage.

**Comment by julien-deramond** [comment]
There are no `dark:*` class utilities. You can contextually use `data-bs-theme="dark"` in the DOM wherever you want. There's an example in https://getbootstrap.com/docs/5.3/customize/color-modes/#example.

**Comment by harnishdesign** [comment]
@julien-deramond I know. but, How can i manually force to override class? When I will need in some elements.
have not changes color in dark mode when i use class `.bg-white` `.bg-light` `.text-dark` `.text-black` etc....

**Comment by julien-deramond** [comment]
Right now, you can use utilities that automatically switch colors depending on the chosen theme:
* `.bg-light-*`, `.bg-dark-*` and `.bg-body-*` classes for background
* `.text-body-*` classes for text

**Comment by mdo** [comment]
Yup, right now, no plans to allow for moving from dark mode to light mode in a nested setting. The CSS selectors unfortunately are just too rough to deal with based on how things are currently implemented.
