### ISSUE TITLE
Tooltip Arrow on top of Tooltip Box if adding popperConfig modifiers

### ISSUE THREAD

**Issue by tz7** [twbs/bootstrap#38578]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've noticed that as soon as I add 

modifiers: [
                ],
                
to my popperConfig, the tooltip arrow is suddenly positioned on top of the tooltip box. I've also tested this in chrome and with v5.3 Alpha but the display remains the same.

### Reduced test cases

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>

<br>
<br>
<br>
<br>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-placement="top" title="Tooltip on top">
    Tooltip on top
</button>

<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
<script>
    // Initialize the tooltip
    $(document).ready(function () {
        $('[data-bs-toggle="tooltip"]').tooltip({
            // placement: 'top',
            popperConfig: {
                modifiers: [
                ],
            },
        });
    });
</script>
</body>
</html>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.3

**Comment by julien-deramond** [comment]
Thanks for opening an issue @tz7.
I haven't executed the example but just by looking at it, I can see a `data-placement="top"`. It should be `data-bs-placement="top"`.  Does it change anything if you make this modification?

**Comment by julien-deramond** [comment]
Just tried a few things in https://codepen.io/julien-deramond/pen/dygevyE.

First (`////////// TEST 1 ///////////`), without `popperConfig`:

```js
$('[data-bs-toggle="tooltip"]').tooltip({
   placement: 'right',
   offset: [0, 100],
   html: true
})
```

Tooltip is well displayed on the right with the offset in italics and the arrow is correctly displayed.
With `offset: [60, 100]`, the offset is right but the arrow is not vertically centered.

Other test (`////////// TEST 2 ///////////`) based on the default config used in Bootstrap:

```js
$('[data-bs-toggle="tooltip"
]').tooltip({
        popperConfig: {
    "placement": "right",
    "modifiers": [
      {
        "name": "flip",
        "options": {
          "fallbackPlacements": [
            "top",
            "right",
            "bottom",
            "left"
          ]
        }
      },
      {
        "name": "offset",
        "options": {
          "offset": [
            0,
            60
          ]
        }
      },
      {
        "name": "preventOverflow",
        "options": {
          "boundary": "clippingParents"
        }
      },
      {
        "name": "arrow",
        "options": {
          "element": ".tooltip-arrow"
        }
      },
      {
        "name": "preSetPlacement",
        "enabled": true,
        "phase": "beforeMain"
      }
    ]
  }
})
```

Tooltip is well displayed on the right with the offset (not in italic because no `html: true` equivalent) and the arrow is correctly displayed.
With `offset: [60, 60]`, the offset is right but the arrow is not vertically centered.

Final test (`////////// TEST 3 ///////////`) is based on the previous one but uses your values for placement and offset.

Does it help?

**Comment by tz7** [comment]
Test 2 is working perfectly and the only difference I can spot is that the modifiers are wrapped in quotation marks. I guess I missed it when going through on how to do custom modifiers. 

Thanks a lot for the help!
