### ISSUE TITLE
Image Carousel with Thumbnails

### ISSUE THREAD

**Issue by Firas-HadjKacem** [twbs/bootstrap#38589]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

A new component that allows users to display a carousel of thumbnailed photos. The component should have the option of customizing the number of images shown on each slide, the size of the thumbnails, and the animation used to change slides.

### Motivation and context

Currently, Bootstrap offers a carousel component that allows users to display a slideshow of images. However, this component does not include thumbnails, which can make it difficult for users to navigate through the images. By adding an Image Carousel with Thumbnails component, users would have an easy way to navigate through a collection of images, such as a product gallery or a portfolio. This would make it more convenient for users to find the specific image they are looking for.
The Image Carousel with Thumbnails component would be useful for showcasing a collection of images, such as a product gallery or a portfolio. The thumbnails allow users to easily navigate to specific images, while the carousel provides a visually engaging way to display the images. This would enhance the user experience by making it easier for users to view the images and find the ones they are interested in.

**Comment by Firas-HadjKacem** [comment]
The outcome desired looks something like the picture: 
<img width="819" alt="image" src="https://github.com/twbs/bootstrap/assets/77494332/b9fc2d9e-7e10-4402-a08a-d18c1d3c55bd">
Also, I tried a case where I used the existing carousel and added js code to generate the thumbnail automatically with the carousel. 
`<div id="carouselId" class="carousel slide carousel-with-thumbnails">
    <div class="carousel-inner">
      <div class="carousel-item active ">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(45).webp" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(131).webp" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(32).webp" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target=".carousel-with-thumbnails" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target=".carousel-with-thumbnails" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
    <div class="carousel-indicators">
    </div>
  </div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      var carousels = document.querySelectorAll('.carousel-with-thumbnails');
      carousels.forEach(function(carousel) {
        var carouselId = carousel.getAttribute('id');
        var indicators = carousel.querySelector('.carousel-indicators');
        var carouselItems = carousel.querySelectorAll('.carousel-item');
        carouselItems.forEach(function(item, index) {
          var img = item.querySelector('img');
          var imgSrc = img.getAttribute('src');
          var activeClass = (index === 0) ? 'active' : ''; 
          var indicator = document.createElement('button');
          indicator.setAttribute('type', 'button');
          indicator.setAttribute('data-bs-target', `#${carouselId}`);
          indicator.setAttribute('data-bs-slide-to', index);
          indicator.className = activeClass;
          indicator.setAttribute('aria-label', 'Slide ' + (index + 1));
          indicator.style.width = '100px';
          var indicatorImg = document.createElement('img');
          indicatorImg.setAttribute('src', imgSrc);
          indicatorImg.className = 'd-block w-100 img-fluid';
          indicator.appendChild(indicatorImg);
          indicators.appendChild(indicator);
        });
        carousel.addEventListener('slide.bs.carousel', function (e) {
          let index = e.to;
          document.querySelector(`#${carouselId} .carousel-indicators .active`).classList.remove('active');
          document.querySelector(`#${carouselId} .carousel-indicators [data-bs-slide-to="${index}"]`).classList.add('active');
        });
      });
    });
    </script>
  ` I added a new class name called carousel-with-thumbnails in order to handle the thumbnails behavior. Any thoughts on this community & maintainers? Shall it be added to the existing features of the carousel? NB: The carousel styling is in _carousel.scss and the carousel js is in  the src\carousel.js.

**Comment by mdo** [comment]
No plans to add this ourselves—sounds like a great third party thing :).
