### ISSUE TITLE
Show password at forms

### ISSUE THREAD

**Issue by Predrag** [twbs/bootstrap#38581]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

I have a problem with displaying a password in Forms. If you write some password to 

`<input type="password" class="form-control" id="exampleInputPassword1">`

and than you click on Eye the password is displayed. This is ok. But when you lost focus (if you click somewhere else) and than you click back to input field the eye is not displayed anymore. What can you do is to clear password and start to write a password again.

### Reduced test cases

You can try steps above on this page.

[bootstrap forms](https://getbootstrap.com/docs/5.2/forms/overview/?)

video:

https://github.com/twbs/bootstrap/assets/460694/84fa9b4b-da7a-432e-a203-352f051f0e82

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge, Firefox, Samsung Internet

### What version of Bootstrap are you using?

v5.2.3, v4

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @Predrag.
Unfortunately, it comes from Microsoft Edge itself. If you go to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#try_it for example, you're going to see the same behavior (and Bootstrap is not used there).

**Comment by coliff** [comment]
@Predrag - I made a little library for Bootstrap which fixes that issue and adds the view/hide password toggle to all browsers: https://github.com/coliff/bootstrap-show-password-toggle

**Comment by Predrag** [comment]
> Thanks for reporting an issue @Predrag. Unfortunately, it comes from Microsoft Edge itself. If you go to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#try_it for example, you're going to see the same behavior (and Bootstrap is not used there).

I see, than we can close this issue

**Comment by Predrag** [comment]
> @Predrag - I made a little library for Bootstrap which fixes that issue and adds the view/hide password toggle to all browsers: https://github.com/coliff/bootstrap-show-password-toggle

Thank you. I will use your library.
