### ISSUE TITLE
Add an on hold feature on the next and previous buttons for pagination on large lists 

### ISSUE THREAD

**Issue by ruiarii** [twbs/bootstrap#38596]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

when having a large number of pages and you want to reach a faraway page, holding the press on the next button should enable you to keep navigating to the next pages until releasing the button. it should also work the same for the previous button and icon-designed pagination.

This is a short video for visualising the behavior: 

https://github.com/twbs/bootstrap/assets/77841717/0a81836f-fef4-4943-b6ef-ec774d3193ac

### Motivation and context

it is needed when having a large set of pages.

**Comment by mdo** [comment]
That's outside the scope of Bootstrap.
