### ISSUE TITLE
Bug in the Browse Feature on Bootstrap Website

### ISSUE THREAD

**Issue by mootezaloui** [twbs/bootstrap#38595]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using the browse feature on the Bootstrap website, the hover does not accurately highlight the section of the page that the user is currently in, especially in large pages. While scrolling, the browse feature should update the highlight to show the current section, but it fails to do so.
![image](https://github.com/twbs/bootstrap/assets/77841233/31f851f0-185d-48f0-8726-2f5b8073d413)

here you can see that the hover indicates where I am 
![image](https://github.com/twbs/bootstrap/assets/77841233/9dd6a183-daa0-4cb9-8d5c-7f7683678ebc)

here there is no hover it does not show where I am I can see the problem is some pages but not all of them 

### Reduced test cases

https://codepen.io/mootezaloui/pen/LYgrKam

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Opera

### What version of Bootstrap are you using?

V5.3

**Comment by julien-deramond** [comment]
Table of Contents is using Bootstrap Scrollspy which sometimes behaves weirdly with the current implementation. I'd say it's linked to #36431 and should be fixed when this other issue will be.

**Comment by mootezaloui** [comment]
Thank you @julien-deramond  for your response. I understand that the issue with the hover in the Bootstrap Scrollspy is related to the JavaScript implementation and may be linked to issue #36431. I agree that it would be best to wait for a fix for this issue, as it seems to be a known problem with the Scrollspy component. I appreciate your help in looking into this and providing a possible explanation for the issue. If there are any updates or workarounds for this issue in the meantime, we will see what are the updates of the other issue

**Comment by mdo** [comment]
Closing for that issue.
