### ISSUE TITLE
Why does the drop-down menu have a minimum width setting?

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#38615]
https://github.com/twbs/bootstrap/blob/fc3f4b67d65c575daa661ecf31cf59b4ff3cced5/scss/_dropdown.scss#L22

https://github.com/twbs/bootstrap/blob/fc3f4b67d65c575daa661ecf31cf59b4ff3cced5/scss/_dropdown.scss#L52

Is the width of this dropdown menu mandatory?

Have you considered removing this restriction in the future?

**Comment by mdo** [comment]
This is to avoid making the dropdowns look a little too small or awkward. Safe to override though!
