### ISSUE TITLE
Adding pop and highlights

### ISSUE THREAD

**Issue by Coding-whiz** [twbs/bootstrap#38618]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

<p align ="center">
<img width="400" alt="image"  src="https://github.com/twbs/bootstrap/assets/94162536/06cd5727-856c-4143-8009-ca9b06490722" >
<br>
</p>
<h1 align = "center"><u>d-none d-sm-block mx-auto mb-3</u></h1>
<p align = "center">
In this <em>class</em> the bootsrap logo is placed in the center, to add on to the Ui it would be better if when the cursor is placed on the image it pops out, this can be done by adding shadow as soon as the cursor is moved over it.
</p>
<hr>
<h1 align = "center"><u>Class: text-body-secondary mb-0</u></h1>
<p align = "center">
In this section on hovering cursor on top of it the text or the section is darkened which does not shows a significant change and is not that prominent. Thus on hovering it is suggested to add a lighter color of the same shade or a contrasting color from the palette of site.
</p>

### Motivation and context

This change will help in adding on to the Ui designing. Hovering over images and color changing or pop may seem to be a very basic change or minute change but these minute changes effect the grade of how pleasant the site is to users.

**Comment by Coding-whiz** [comment]
Greetings @julien-deramond sir

I have added this issue can you please help me by telling me what to do next. Other than this I really want to know about earning github batches more currently I am having 2 batches and I want to get the YOLO batch too👀 Can you pls guide me how to get that batch too.

I will be really grateful🙂

**Comment by julien-deramond** [comment]
> I have added this issue can you please help me by telling me what to do next. 

Thanks for opening this issue @Coding-whiz but our designer closed it as "not planned", meaning this proposal won't be developed in Bootstrap documentation.

> Other than this I really want to know about earning github batches more currently I am having 2 batches and I want to get the YOLO batch too👀 Can you pls guide me how to get that batch too.

Sorry, but this is not the place to discuss this kind of thing.
