### ISSUE TITLE
Datalist description is scary

### ISSUE THREAD

**Issue by kant2002** [twbs/bootstrap#38627]
https://github.com/twbs/bootstrap/blob/a6dc107dfd19f1e804b833a46b2d3f4045679452/site/content/docs/5.3/forms/form-control.md?plain=1#LL158C13-L158C13

If you read whole section about `datalist` usage it gives impression that browser support is lacking and point to https://caniuse.com/datalist where all supported browser are green and no even issues with them. Except Opera Mini and UIWebView which probably should be discounted (am I wrong?). I do not think that datalist has great ergonomics, and maybe one issue which is left is styling across browsers (is this still an issue?).

So I think it would be great rephrase this section is less scary way. 
What's your opinion on that?

**Comment by ffoodd** [comment]
Styling and support are inconsistent, indeed: `<option>` is almost unstylable and `<datalist>` does not work equally depending on input type, browser and system.

Color input on Firefox Ubuntu supports datalist for a few month only, for example.

**Comment by mdo** [comment]
Description feels right :).
