### ISSUE TITLE
Media queries for iMac and TV or extra Large Monitors

### ISSUE THREAD

**Issue by sinjuangajan** [twbs/bootstrap#38621]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Any plan to add this feature.

### Motivation and context

`*-xxl` not working as expected for extra large monitors.

**Comment by julien-deramond** [comment]
Thanks for suggesting this feature @sinjuangajan.
Breakpoints don’t specifically target every use case or device so `xxl` (`≥1400px`) might not fit the exact values needed for iMac and TV or extra Large Monitors.
Except if someone has a strong argumentation suggesting a new value, we don't plan to change it.
However, you can [customize the breakpoints via Sass](https://getbootstrap.com/docs/5.3/layout/breakpoints/#available-breakpoints) with `$grid-breakpoints`.
