### ISSUE TITLE
Inactive area between checkbox and its label

### ISSUE THREAD

**Issue by wscourge** [twbs/bootstrap#38630]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using inline `.form-check`, clicking the red area does not check the checkbox

![image](https://github.com/twbs/bootstrap/assets/16985871/6d0f5b71-5fa1-4c53-9bc1-47062730d669)

### Reduced test cases

Adding this styles to the `label.form-check-label` helps

```
.form-check-label {
  margin-left: -0.5rem;
  padding-left: 0.5rem;
}
```

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3

**Comment by YaminiVijay** [comment]
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="exampleCheckbox">
  <label class="form-check-label" for="exampleCheckbox">
    <span class="red-area"></span> 
    Check me
  </label>
</div>

In the above code, I added a <label> element around the checkbox and the red area. The for attribute of the label is set to the id of the checkbox, which establishes the association between the two elements. Now, when you click on the red area or the label text, it will check the checkbox.

**Comment by YaminiVijay** [comment]
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="exampleCheckbox">
  <label class="form-check-label" for="exampleCheckbox">
    <span class="red-area"></span> 
    Check me
  </label>
</div>

**Comment by wscourge** [comment]
Yes. I'd like it to work the way you described it for the following HTML with Bootstrap's CSS classes:
```
<div class="form-check">
  <label for="select_all" class="form-check-label">Select all</label>
  <input id="select_all" type="checkbox" class="form-check-input" />
</div>
```

**Comment by mdo** [comment]
I get this, and it's been asked before, but it's an odd one to me. Clicking negative space shouldn't trigger things. That's much clearer when you consider the _proximity_ of the negative space, but it's something to think about. I might revisit this in v6, but for now we'll leave as-is.

**Comment by flack** [comment]
just to chime in: I've discovered this after thinking a few times that my checkbox code is broken, since they didn't react when I clicked. Only after a while I noticed that this is a margin vs. padding thing.

I'm not exactly sure what the definition of "negative space" is, but for me the empty space between checkbox and label is the same as a whitespace in a multiword label, i.e. I'd argue that checkbox + label are one logical element with whitespaces to improve readability, and if I have something like `[x] Option 1` then a click on the first empty space should behave the same as a click on the second empty space.

**Comment by flack** [comment]
or maybe have the current version working with

```html
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="exampleCheckbox">
  <label class="form-check-label" for="exampleCheckbox">
    Check me
  </label>
</div>
```

and the no-gap version with

```html
<div class="form-check form-check-inline">
  <label class="form-check-label" for="exampleCheckbox">
    <input class="form-check-input" type="checkbox" id="exampleCheckbox">
    Check me
  </label>
</div>
```
