### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#38646]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://getbootstrap.com/docs/5.3/components/card/#list-groups

https://getbootstrap.com/docs/5.3/components/list-group/#horizontal

dir="rtl"

When testing, please set the dir of the corresponding page from right to left.

It is mainly caused by the border and margin problems of the list-group list.

There is also icon overlap on the main navigation bar.

browser version 113.0.5672.127

### Reduced test cases

https://codepen.io/zhangchenglin/pen/qBJvdmX

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0-alpha3

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by ZhangChengLin** [comment]
> Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md?rgh-link-date=2023-05-24T21%3A34%3A36Z), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.
> 
> _This is a saved reply._

Already edited

**Comment by ffoodd** [comment]
If you set `dir="rtl"`, you need to use our RTL stylesheet: `bootstrap.rtl.min.css`.

Should be enough to solve your issues.
