### ISSUE TITLE
Font sizes compiling into wrong values

### ISSUE THREAD

**Issue by prateekthapa-gurzu** [twbs/bootstrap#38652]
Currently working on SASS Bootstrap v5.3.0-alpha3.

The heading font sizes are changing into completely different values compared to what has been set.
I have RFS to false (`$enable-rfs: false !default;`). So I'm not sure what do I do next.

At the moment, I've set the heading font sizes as follows:

```
$font-size-base:             1rem !default;
$h1-font-size:                $font-size-base * 2.5 !default;
$h2-font-size:                $font-size-base * 2.25 !default;
$h3-font-size:                $font-size-base * 2 !default;
$h4-font-size:                $font-size-base * 1.75 !default;
$h5-font-size:                $font-size-base * 1.5 !default;
$h6-font-size:                $font-size-base * 1.25 !default;
```
The expect result of h5 is 1.5rem or 24px, and of H6 is 1.25rem or 20px.
As you can see in the compiled CSS below, all the values are incorrect, which you can see below:

```
h6, .h6, h5, .h5, h4, .h4, h3, .h3, h2, .h2, h1, .h1 {
  margin-top: 0;
  margin-bottom: 1.25rem;
  font-family: "Gilroy", system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-weight: 700;
  line-height: 1.2;
  color: var(--bs-heading-color, inherit);
}
h1, .h1 {
  font-size: 2.625rem;
}
h2, .h2 {
  font-size: 2.125rem;
}
h3, .h3 {
  font-size: 1.75rem;
}
h4, .h4 {
  font-size: 1.375rem;
}
h5, .h5 {
  font-size: 1rem;
}
h6, .h6 {
  font-size: 0.875rem;
}
```

**Comment by Shekharcodess** [comment]
Do you need help with this? If yes I am up for it

**Comment by prateekthapa-gurzu** [comment]
Yes, thank you. A few more issues have come up revolving around font sizes.

**Comment by mdo** [comment]
Seems like this is maybe a problem on your end with the RFS setup. I see no issues when changing the values in `main` to what you've included here.

**Comment by prateekthapa-gurzu** [comment]
Since this framework was part of a bigger project, I moved the code outside of that project and that seemed to have fixed the issues. It seems there were conflicts arising because of other sass files that were included in that project.

Thank you for your help.
