### ISSUE TITLE
Modal wrong working

### ISSUE THREAD

**Issue by obtulowiczl** [twbs/bootstrap#38663]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Its not possible to close a modal opened with button, with a java script if a targeted modal wasnt initialized before open it with button

### Reduced test cases

https://codepen.io/nexiuuu/pen/jOeRYKz

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by chefarbeiter** [comment]
There is a static [method](https://getbootstrap.com/docs/5.3/components/modal/#methods) `getInstance` which allows you to get the modal instance associated with a DOM element. If you change the line `let bootstrapModal = new bootstrap.Modal(modal);` from your example to `let bootstrapModal = bootstrap.Modal.getInstance(modal);`, your example is working and the modal closes.

(There is also a static `getOrCreateInstance` method in case you cannot ensure that the modal has already been initialised by the call via the button)

**Comment by obtulowiczl** [comment]
Thank you very much! :)
