### ISSUE TITLE
Background-color not transparent

### ISSUE THREAD

**Issue by EvenEasy** [twbs/bootstrap#38660]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

hi, i make a WebApp for telegram bot using bootsrap
and i wanna make background-color of the page transparent
but i can't (
background-color still white (
i tried .bg-transparent and in css style

```
<style>
            html, body, main {
                background-color: transparent !important;
            }
 </style>
```
but its not working (

my html code 

![image](https://github.com/twbs/bootstrap/assets/75838378/01f3fe35-0a2d-4b1a-8734-5263368068db)

### Reduced test cases

![image](https://github.com/twbs/bootstrap/assets/75838378/01f3fe35-0a2d-4b1a-8734-5263368068db)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Opera

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by CyrilKrylatov** [comment]
Hi, can you provide us a codepen link of the reduced case so we can see for ourselves?
