### ISSUE TITLE
dark mode bug in /examples/sidebars/

### ISSUE THREAD

**Issue by endcoreAK** [twbs/bootstrap#38679]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

if you switch to dark mode on the example page, the background on sidebar 2 +3 is lighter than the others, also the blue on the active pills is different than the icons (3rd sidebar) and last but not least I noticed that under account (4th sidebar) the links are dark.

### Reduced test cases

https://getbootstrap.com/docs/5.3/examples/sidebars/

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by mdo** [comment]
Only plan is to fix link color. Rest of the changes are good to keep—we change link color in dark mode, but we don't (yet) change the main theme colors.
