### ISSUE TITLE
$navbar-dark-icon-color missing?

### ISSUE THREAD

**Issue by endcoreAK** [twbs/bootstrap#38671]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

There is a variable for `$navbar-light-icon-color` but not `$navbar-dark-icon-color` is that the way it's supposed to be?

### Reduced test cases

https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L1209

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.3.0-alpha3

**Comment by julien-deramond** [comment]
> There is a variable for $navbar-light-icon-color but not $navbar-dark-icon-color is that the way it's supposed to be?

For consistency, I think `$navbar-dark-icon-color` should be introduced as a new variable. It's handled in https://github.com/twbs/bootstrap/pull/38673. Thanks for reporting this issue @endcoreAK!
