### ISSUE TITLE
alert alert-success is not working on tr tag when using bootstrap@5.3.0

### ISSUE THREAD

**Issue by visruth** [twbs/bootstrap#38700]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`alert alert-info` is style is not working on `tr`  (Eg: `<tr class="alert alert-success" role="alert">`) when using `bootstrap@5.3.0` but it works in `bootstrap@5.3.0-alpha3`

### Reduced test cases

```
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Bootstrap demo</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
   </head>
   <body>
      <table class="table">
         <thead>
            <tr>
               <th>First</th>
            </tr>
         </thead>
         <tbody>
            <tr class="alert alert-success" role="alert">
               <td>Mark</td>
            </tr>
         </tbody>
      </table>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
   </body>
</html>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0

**Comment by mdo** [comment]
We've always advised not to mix components with one another, but rather to nest within. In this case, we've slightly modified how we handle table coloring to ensure better styling with _table_ classes. Try modifying the styling here with the table variants as shown in our docs. Or, nest an alert within the table cell.
