### ISSUE TITLE
NavBar dropdown doesn't work from Javascript module

### ISSUE THREAD

**Issue by michaelcress** [twbs/bootstrap#38701]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Using the NavBar example code from the latest Bootstrap v5.3 documentation, I can see the Navbar dropdown menu clearly working. However, if I encapsulate it within a Javascript module, it no longer functions.

### Reduced test cases

The attached Zip file contains an HTML+JS project that shows the issue. Within index.html, the example code from the documentation, along with the JS module tag, are included. You can comment/un-comment each respectively to observe the issue.

[MJS_Navbar_Example.zip](https://github.com/twbs/bootstrap/files/11644292/MJS_Navbar_Example.zip)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.3

**Comment by mdo** [comment]
Please create a Stackblitz or something similar for us to look at this properly without having to download or setup anything on our end :).

**Comment by nenadvicentic** [comment]
I had similar issue after updating from Bootstrap 5.2.3 to 5.3.0.

It turned out that I had leftover, no longer existing element in the `data-bs-target` attribute.

```html
<button class="navbar-toggler" data-bs-target="#top-navbar-collapse, aside">
</button>
```
`<aside>` element has been removed a while ago, but navigation bar collapse functionality continued to work in the version of Bootstrap lower than `5.3`. Navbar collapse in version `5.3` does not working until the extra element reference has been removed from the  `data-bs-target` attribute.

**Comment by michaelcress** [comment]
I tried, but the website doesn't work to show the issue. Thus, I created
the bare bones sample that you have.


Regards,

Michael

**Comment by michaelcress** [comment]
Thanks Nenad. In the sample I provided, I have the (working) code pasted
directly from the docs commented out as a known good test case. That same
code, when placed within the JS module, doesn't work.

Michael

**Comment by cedx** [comment]
Same issue here (...and I didn't succeed to create a minimal project in Stackblitz to show it).
Basically, that code does not work anymore with v5.3.0 (without producing any error in the browser console):

```js
// navbar.js
import { Dropdown } from "bootstrap";
for (const element of document.querySelectorAll(".dropdown-toggle")) new Dropdown(element);
```
