### ISSUE TITLE
Documentation of navbar, Color schemes: border-bottom

### ISSUE THREAD

**Issue by Flachdachs** [twbs/bootstrap#38706]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the [documentation of the navbar, section Color schemes](https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes), the first example has two additional classes. They are not used in the other examples nor in the 5.2 docs. The first is `border-bottom`. Why is there a border? It's not explained. And it seems to me that it is not really needed. The second is `border-bottom-dark`. AFAIK this is not a Bootstrap class. I also can't see that it is used for the example.

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @Flachdachs. Created https://github.com/twbs/bootstrap/pull/38707 to tackle it.

**Comment by mdo** [comment]
I added them to give some indication of the bounding box for the navbar when in dark mode. Up to you @julien-deramond if you want to keep them or remove them.

**Comment by Flachdachs** [comment]
But a dark border around/below a dark background only expands the background a bit. Especially when the example is displayed on a white background.

It would make sense if the page's background has the same darkness as the navigation bar, to give it a bottom border with a light color for a visual separation of both parts.
