### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by msftedad** [twbs/bootstrap#38718]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

<html>
<body>

Repro Steps:
1.Launch  [Angular powered Bootstrap (ng-bootstrap.github.io)](https://ng-bootstrap.github.io/#/components/datepicker/examples)
2.Tab to Date picker
3.Tab to Example and press enter.
4.Run accessibility insights tool and check for the results.

Actual Result: 
Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds

Expected Result:
Color contrast of the text with respect to background ratio should be greater than or equal to 4.5:1

![204024](https://github.com/twbs/bootstrap/assets/93735775/cfcbde9d-3e74-4e65-a615-814117de7428)
<br class="Apple-interchange-newline">
</body>
</html>

### Reduced test cases

**More information:**
Issue: 
Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds (color-contrast - https://accessibilityinsights.io/info-examples/web/color-contrast)

Target application: Daily Recommender(17) - https://tscppe.azurewebsites.net/opportunitydetails

Element path: .ngb-dp-weekday.small:nth-child(2)

Snippet: 
<div class="ngb-dp-weekday small"> Tu </div>
How to fix:
Fix any of the following:
  Element has insufficient color contrast of 2.88 (foreground color: #17a2b8, background color: #f8f9fa, font size: 9.6pt (12.8px), font weight: normal). Expected contrast ratio of 4.5:1

Environment: Chrome version 106.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.35.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

6.1.8034

**Comment by julien-deramond** [comment]
Thanks for opening an issue @msftedad but this is not the right repository. Here's the good one: https://github.com/ng-bootstrap/ng-bootstrap.
