### ISSUE TITLE
Custom popover no longer works after upgrading to 5.3.0

### ISSUE THREAD

**Issue by bioworkflows** [twbs/bootstrap#38720]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I used to pass a function to the `content` option of `Popover` as follows, 

```javascript
new bootstrap.Popover(popoverTriggerEl, {
    content: get_popover_content,
  });
```

to trigger a popover defined as 

```html
<a role="button" data-bs-html="true"
        data-bs-trigger="focus" data-bs-container="body" data-bs-toggle="popover"
        data-bs-placement="bottom"
        data-tag-info='{}' >click me</a>
```

where `this.dataset` contains the `data` of the field

```javascript
function get_popover_content() {
  if (this.dataset.tagInfo) {
     //
  }
  //
}
```

This no longer works after upgrading to bootstrap 5.3.0 (`this` points to `document` and `this.dataset` is `null` now) so I am wondering what is the proper way to do it with the new version. Note that the [documentation](https://getbootstrap.com/docs/5.3/components/popovers/) says

> If a function is given, it will be called with its this reference set to the element that the popover is attached to.

and `this` is supposed to be the `<a>` element.

### Reduced test cases

[codepen](https://codepen.io/bopeng/pen/XWyWRra)

The key to look is `console.log(this)`, which points to the document and not the `<a>` element. If you change the `bootstrap` version to `5.2.3`, `this` points to the button itself.
 
### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0

**Comment by nwalters512** [comment]
It appears as though the `content` function now receives the element as an explicit argument. I don't see this documented, and it's definitely unfortunate to have this breaking change in a minor release, but this should allow folks to work around this in the meantime.

**Comment by kczx3** [comment]
Yeah, that's a big miss...
