### ISSUE TITLE
Why does the page fail to render

### ISSUE THREAD

**Issue by Seanxwy** [twbs/bootstrap#38742]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I used bootstrap in asp.net core project. 
 I used svg html code (from bootstrap-icons) in the item link under dropdown-menu. The page appears blank and does not load properly. There are other cases where blank pages appear as well. When I remove the svg html code, it is back to normal. Or I remove the js reference. It's also back to normal. Why is this?

### Reduced test cases

no

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.3

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by mdo** [comment]
Closing for now since you didn't follow the contributing guidelines and I don't see a bug here.
