### ISSUE TITLE
Examples download "bootstrap-5.3.0-examples.zip" is missing file for dark mode "color-modes.js"

### ISSUE THREAD

**Issue by mark2016** [twbs/bootstrap#38746]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The Examples downloadable zip file found at
https://github.com/twbs/bootstrap/releases/download/v5.3.0/bootstrap-5.3.0-examples.zip
is missing JavaScript file "color-modes.js", which is referenced by the starter template (bootstrap-5.3.0-examples.zip\bootstrap-5.3.0-examples\starter-template).  It is used for Dark/Light mode toggle.

A work-around is to copy the file from the Demo starter template at https://getbootstrap.com/docs/5.3/assets/js/color-modes.js

Would be a nice idea for convenience to include it in the download so that the Dark/Light mode examples work out of the box.

### Motivation and context

It would allow the downloadable examples to work out of the box without any additional work.

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @mark2016, good catch!
It's tackled in https://github.com/twbs/bootstrap/pull/38747
