### ISSUE TITLE
Bootstrap npm link down

### ISSUE THREAD

**Issue by 0utc0ntr0l2021** [twbs/bootstrap#38743]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
It's down

### Reduced test cases

https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
Is down

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5

**Comment by mdo** [comment]
Works fine for me. Also, we don't run any CDN ourself, so if there's an issue with a hosted file there, it's very likely an issue with the CDN itself.
