### ISSUE TITLE
the cdn that are provided on access  bootstrap is down 

### ISSUE THREAD

**Issue by mina20088** [twbs/bootstrap#38764]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

when i tried to access bootstrap using cdn  i received errors on phpstorm to download the lib and also when accessing thos links from the browser i get error error screenshots are uploaded below and access the bootstrap from this provider website give me error all of them it seems like the links is done or there are somthing wrong please check 
```
CSS | https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
JS | https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
```
when try to download from IDE
![Screenshot 2023-06-08 224408](https://github.com/twbs/bootstrap/assets/39167278/f638efb2-2860-4ef6-b2f9-1d6026329f1e)
this when i try to access the cdn from browser
![Screenshot from 2023-06-14 02-13-56](https://github.com/twbs/bootstrap/assets/39167278/8b304343-8376-4e64-bc51-579052feccb0)
also i got this in the bowsers inspector when added the cdns links 
![Screenshot from 2023-06-14 01-33-50](https://github.com/twbs/bootstrap/assets/39167278/2a875c81-172c-4e59-9830-363310f411c6)
Note :Same happiens for the popperjs lib 

### Reduced test cases

the only way that i can access the link from the browse is through vpn also there are some one that have the same issue and here is the link for the chats 
https://github.com/orgs/twbs/discussions/38732#discussioncomment-6151998

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.0

**Comment by julien-deramond** [comment]
Closing it since it's an integration error. The integrity value is probably not the right one. We use the CDN everywhere without any issues.
More details in https://github.com/orgs/twbs/discussions/38732#discussioncomment-6170502.

**Comment by jimaek** [comment]
In general if anyone notices any CDN issues please report them directly to us https://github.com/jsdelivr/jsdelivr :)
In most cases its an overly active LAN firewall breaking things
