### ISSUE TITLE
text-bg-primary does not respect --bs-primary color

### ISSUE THREAD

**Issue by Pitel** [twbs/bootstrap#38769]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I set `--bs-primary` variable in my custom CSS and use `text-bg-primary` class, it is defined as `background-color: RGBA(13,110,253,var(--bs-bg-opacity,1))!important;`, basicaly ignoring the variable.

### Reduced test cases

```css
:root {
  --bs-primary: red;
  --bs-primary-rgb: 255, 0, 0;
}
```

```html
<div class="text-bg-primary">This should be red, but is still blue</div>
<div class="bg-primary">This is red</div>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.0.3

**Comment by harnishdesign** [comment]
also, `btn-primary` and `btn-outline-primary` class ignoring the variable (`--bs-primary`).
