### ISSUE TITLE
Move from bs-primary-bg-subtle to bs-primary-bg for primary alert in dark mode

### ISSUE THREAD

**Issue by khalyomede** [twbs/bootstrap#38784]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently alerts render like this on dark mode 

![Capture d’écran du 2023-06-18 22-26-54](https://github.com/twbs/bootstrap/assets/15908747/8c7873e3-43a3-46e7-875d-27dd9f701855)

It seems the background is a little bit too much blue. As I notice, the variable used is `bg-primary-bg-subtle` when I think a simple `bs-primary-bg` would be sufficient enough in dark mode.

### Motivation and context

This is to keep a color coherent for primary across various elements (like shown in the screenshot above).

**Comment by Akash1965** [comment]
I am a beginner. Can I try solving this issue??

**Comment by julien-deramond** [comment]
Thanks @Akash1965, but before launching any development, we need to define beforehand whether this change is wanted or not.

**Comment by Akash1965** [comment]
Okay

**Comment by mdo** [comment]
This styling matches the light mode color contrast and overall design, so going to leave it as-is.
