### ISSUE TITLE
@extend bootstrap class gives "The target selector was not found".

### ISSUE THREAD

**Issue by LeahPike** [twbs/bootstrap#38787]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm trying to extend a bootstrap class but I get the error "The target selector was not found".

I would expect to be able to @extend bootstrap classes when importing parts of bootstrap.

### Reduced test cases

I have made a new angular 14 project and added bootstrap. I have updated the styles.scss with the following:

```typescript
// https://getbootstrap.com/docs/5.3/customize/sass/#importing

// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "bootstrap/scss/functions";

// 2. Include any default variable overrides here


// 3. Include remainder of required Bootstrap stylesheets (including any separate color mode stylesheets)
@import "bootstrap/scss/variables";
@import "bootstrap/scss/variables-dark";

// 4. Include any default map overrides here


// 5. Include remainder of required parts
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/root";

// 6. Optionally include any other parts as needed
@import "bootstrap/scss/utilities";
@import "bootstrap/scss/reboot";
@import "bootstrap/scss/type";
@import "bootstrap/scss/images";
@import "bootstrap/scss/containers";
@import "bootstrap/scss/grid";
@import "bootstrap/scss/helpers";

// 7. Optionally include utilities API last to generate classes based on the Sass map in `_utilities.scss`
@import "bootstrap/scss/utilities/api";

// 8. Add additional custom code here
.my-alert {
  @extend .alert;
  @extend .alert-primary;
}
```

I have noticed that if I do the simple import it works, but this is not what I want as I want to override variables etc..

This works:
```
@import "bootstrap/scss/bootstrap";

// 8. Add additional custom code here
.my-alert {
  @extend .alert;
  @extend .alert-primary;
}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks for opening this issue @LeahPike 
I think you forgot to import the alert file: `@import 'bootstrap/scss/alert';`.
See https://stackblitz.com/edit/github-4yvpse?file=scss%2Fstyles.scss,index.html.

**Comment by LeahPike** [comment]
Ah so the "6. Optionally include any other parts as needed" is just giving examples, it is not listing them all!

Thanks

**Comment by julien-deramond** [comment]
Yes, you can have the complete list in our source code at https://github.com/twbs/bootstrap/blob/main/scss/bootstrap.scss.

Basically, when you're doing stuff like that, you can embed only what you really need, which is good in terms of eco-design because your final CSS bundle will be reduced.
