### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by ThomasGrant08** [twbs/bootstrap#38810]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

CDN versions from 5.2.3 upwards don't toggle accordions.

Steps to replicate: 

use cdn versions of 5.2.3, 
copy example accordion code to page.
try and toggle 1 of the accordion items open then closed. 

This issue was replicatable on 5.3.0. Had to go back to 5.2.0 to get this working again.

### Reduced test cases

.

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.3

**Comment by mdo** [comment]
Closing due to lack of example.
