### ISSUE TITLE
Google 1st hits are very old Bootstrap versions

### ISSUE THREAD

**Issue by wkoszek** [twbs/bootstrap#38831]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I Google Twitter Bootstrap, the first several pages listed in the results page are very old versions of the framework. It might be SEO or popularity, but v5 looks so much better

### Reduced test cases

Just Google :-)

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5

**Comment by mdo** [comment]
Searching for "twitter bootstrap" vs "bootstrap" is likely yielding different results. I do know we have some more work to do on downplaying older versions, but it seems there's not really a great way to do this in Google Search Console (at least in a bulk management way). Would love it if folks have suggestions!

**Comment by wkoszek** [comment]
@mdo I think the simplest change would be to put "You're looking at old documentation. Newer version is HERE" warnings in the 1.x-4.x docs. I suspect adding redirects is hard.
