### ISSUE TITLE
Custom pattern for email in Bootstrap Form Validator is not working

### ISSUE THREAD

**Issue by bpsbais** [twbs/bootstrap#38843]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The default behavior of email validation is just checking `any number of characters` then an `@` symbol and `any character` that's it.
I want to check for a correct validation so I tried to put a `pattern` tag in email input with following pattern.
`pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"` But the pattern is working (still default behavior) and Browser throwing error as follow:
`Pattern attribute value [a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/v: Invalid character in character class`

I tried to remove `novalidate` from `form` tag to bypass the Bootstrap's Javascript. But same error.
As soon as I hit the `@` key browser throwing same error.

Could anyone check where I am wrong?

Suggestion: Please upgrade `https://getbootstrap.com/docs/5.3/forms/validation/` page to provide in depth detail for form validator. I also wanted to use my custom javascript code along with Bootstrap's form validator but It is not working.

Similar Issue here: https://stackoverflow.com/questions/69894643/custom-validation-with-bootstrap-v5

### Reduced test cases

[Live Demo on Codepen](https://codepen.io/bpsbais/pen/RwqpGGj)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0

**Comment by julien-deramond** [comment]
> Pattern attribute value [a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/v: Invalid character in character class

This error doesn't come from Bootstrap.
If you go on Chrome to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern#try_it, change the pattern to `pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"`, you'll see the same error in the console.

**Comment by kczx3** [comment]
For future readers, the literal dashes within the character classes needed to be escaped in the pattern string.
