### ISSUE TITLE
Element.setCapture() is deprecated. Use Element.setPointerCapture() instead

### ISSUE THREAD

**Issue by moshair** [twbs/bootstrap#38841]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

I got a warning in the developers tool in Firefox in mobile view simulation, I thought that it is in my code, I tried the official bootstrap website, I got he same warning.

`Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture`

![setcapture_firefox](https://github.com/twbs/bootstrap/assets/13575753/bffe7322-a0fb-4bc9-9be6-df11045240e6)

### Reduced test cases

[](https://getbootstrap.com/)

Click on the the dots.

Chat GPT
------------------------
If you're seeing the warning "Element.setCapture() is deprecated. Use Element.setPointerCapture() instead" in Firefox when using Bootstrap, you can solve it by updating your version of Bootstrap to a newer version that uses `setPointerCapture()` instead of `setCapture()`.

Alternatively, you can add the following code to your JavaScript file to replace all instances of `setCapture()` with `setPointerCapture()`:

```
if (typeof Element.prototype.setPointerCapture === 'undefined') {
  Element.prototype.setPointerCapture = Element.prototype.setCapture;
}

```
This code checks if `setPointerCapture()` is supported by the browser, and if not, it creates an alias to `setCapture()`. This way, any code that uses `setCapture()` will still work without generating the deprecation warning.

You can add this code to your JavaScript file before any other code that uses `setCapture()`, or you can add it to a separate file and include it in your HTML file before your other JavaScript files.
-----------

That didn't solve the warning :(

----------------

If updating to a newer version of Bootstrap or adding the code to replace `setCapture()` with `setPointerCapture()` did not solve the problem, you can try the following:

1. Check if any other JavaScript libraries or plugins you are using are also using `setCapture()`. If so, update those libraries or plugins to a version that uses `setPointerCapture()` instead.

2. If you are using a custom script that uses `setCapture()`, you can update it to use `setPointerCapture()` instead. Here's an example of how to update the code:

   Before:
   
```
   element.setCapture();
   document.addEventListener('mousemove', handleMouseMove);
   document.addEventListener('mouseup', handleMouseUp);

```

   After:
   
```
   element.setPointerCapture(pointerId);
   document.addEventListener('pointermove', handleMouseMove);
   document.addEventListener('pointerup', handleMouseUp);
```

   In this example, `pointerId` is the ID of the pointer that you want to capture. You can use `null` to capture all pointers.

3. If you are unable to update the code to use `setPointerCapture()`, you can disable the deprecation warning in Firefox. To do this, type `about:config` in the Firefox address bar and press Enter. Search for the preference `dom.events.testing.asyncClipboard.setCapture.warning` and set it to `false`. This will disable the warning for all websites.

Note that disabling the warning is not recommended, as it may hide other important warnings related to deprecated features. It's always best to update your code to use the latest, non-deprecated features.
------------------------

Is there will be an update to bootstrap to fix that waning? 
Does that mean some bootstrap function using touch on mobile will stop working using current bootstrap version 5.3?

Regards,

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks for opening this issue @moshair 
This warning is displayed as soon as one is clicking on the touch simulation button in Firefox. On the right-hand side of the warning, the corresponding file "generating" the warning is mentioned: here it's `view-source:resource://devtools/server/actors/emulation/touch-simulator.js`. This file doesn't come from Bootstrap, so it's not an issue on our side, and probably on Firefox side.

**Comment by moshair** [comment]
> Thanks for opening this issue @moshair This warning is displayed as soon as one is clicking on the touch simulation button in Firefox. On the right-hand side of the warning, the corresponding file "generating" the warning is mentioned: here it's `view-source:resource://devtools/server/actors/emulation/touch-simulator.js`. This file doesn't come from Bootstrap, so it's not an issue on our side, and probably on Firefox side.

Thank you.
👍
