### ISSUE TITLE
Scroll-up button

### ISSUE THREAD

**Issue by abrehan2** [twbs/bootstrap#38859]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello, I plan to incorporate a scroll-up button into the pages in order to improve the overall user experience.

![image](https://github.com/twbs/bootstrap/assets/100872683/cc77ea3b-7daf-410f-aff7-1711aab47b5d)

### Motivation and context

I find great fulfillment in making open-source contributions, as they provide a remarkable platform for pursuing excellence.

**Comment by mdo** [comment]
No plans for us to add this.
