### ISSUE TITLE
Vertical rule not the correct border width

### ISSUE THREAD

**Issue by simo026q** [twbs/bootstrap#38856]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When changing the `$border-width` the horizonal ruler changes. However, the vertical ruler does not because it's hardcoded to use `1px`:
```scss
// helpers/_vr.scss
.vr {
  /* .. */
  width: 1px;
  /* .. */
}
```

Could it maybe be changed to use something like the existing `$hr-border-width`?

### Reduced test cases

https://codepen.io/simo026q-the-reactor/pen/dyQRpXY

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5.3.0

**Comment by Jyoticharan** [comment]
Can I work  on this issue
