### ISSUE TITLE
Button changes size when clicked

### ISSUE THREAD

**Issue by ikibiki** [twbs/bootstrap#38877]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Button changes size when clicked

### Reduced test cases

`<button class="btn btn-success" type="button">Copy</button>`

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.0

**Comment by Samthomaskkkkkkklk** [comment]
What's going on with the changes?

**Comment by ffoodd** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by ikibiki** [comment]
hi im sorry. after careful adjustments in my asset list. an outdated bootstrap flavor (MDB Bootstrap) is causing the error. after i removed all conflicting files its already working normally.
