### ISSUE TITLE
Tab fade is not fading out tab content

### ISSUE THREAD

**Issue by ferflorespinto** [twbs/bootstrap#38871]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This is a minor issue with the fade animation and it appears to be a new issue with the latest version 5.3. When toggling tabs with the fade effect, the tab content no longer fades out before the new content fades in. The content just disappears before the fade in. This does not appear to be an issue with version 5.0.

The easiest way to confirm this issue is to check the Bootstrap docs page here:
https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior
And to see that it's not an issue in 5.0:
https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior

### Reduced test cases

https://codepen.io/ferflorespinto/pen/xxQLjVM

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3.0

**Comment by XhmikosR** [comment]
I cannot reproduce. I can reproduce only if I disable animations on Windows. Are you sure you haven't turned off animation on your OS settings?
