### ISSUE TITLE
--bs-breakpoint variables are defined but not used

### ISSUE THREAD

**Issue by gobijan** [twbs/bootstrap#38910]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The compiled css (unminified) defines starting from line 774:

    :root {
      --bs-breakpoint-xs: 0;
      --bs-breakpoint-sm: 576px;
      --bs-breakpoint-md: 768px;
      --bs-breakpoint-lg: 992px;
      --bs-breakpoint-xl: 1200px;
      --bs-breakpoint-xxl: 1400px;
    }

The media queries for the containers do not make use of the variables though.

### Reduced test cases

@media (min-width: 576px) {
  .container-sm, .container {
    max-width: 540px;
  }
}
@media (min-width: 768px) {
  .container-md, .container-sm, .container {
    max-width: 720px;
  }
}
@media (min-width: 992px) {
  .container-lg, .container-md, .container-sm, .container {
    max-width: 960px;
  }
}
@media (min-width: 1200px) {
  .container-xl, .container-lg, .container-md, .container-sm, .container {
    max-width: 1140px;
  }
}
@media (min-width: 1400px) {
  .container-xxl, .container-xl, .container-lg, .container-md, .container-sm, .container {
    max-width: 1320px;
  }
}
:root {
  --bs-breakpoint-xs: 0;
  --bs-breakpoint-sm: 576px;
  --bs-breakpoint-md: 768px;
  --bs-breakpoint-lg: 992px;
  --bs-breakpoint-xl: 1200px;
  --bs-breakpoint-xxl: 1400px;
}

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.3.0

**Comment by mdo** [comment]
CSS custom properties cannot be used in media queries. https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries https://bholmes.dev/blog/alternative-to-css-variable-media-queries/

**Comment by gobijan** [comment]
So then the breakpoint variables shouldn't be in the compiled css?
Or what purpose do they serve? Reference for custom css?

**Comment by mdo** [comment]
Reference, JavaScript, and other use cases are all possible. Just not CSS, yet.
