### ISSUE TITLE
Using `hidden` attribute with `d-flex`

### ISSUE THREAD

**Issue by MiniGod** [twbs/bootstrap#38936]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The display property of `.d-flex` overrides the display property of `[hidden]`.

E.g. this div should be hidden, but is not: `<div class="d-flex" hidden>`

I can use the the `d-none` class, and it overrides `d-flex` because it's defined later, but IMO, `[hidden]` should also override `d-flex`.

Essentially, the `hidden` attribute works for all elements except those with `d-*, so it's more of a consistent results issue than anything else.

### Reduced test cases

https://codepen.io/minigod/pen/KKrePaV

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.0

**Comment by mdo** [comment]
I believe we settled on the opposite—if you're using display utilities, expect to continue to have to use them. Mixing one utility set with another becomes a little odd IMO. `[hidden]` is just setting `display: none` anyway, so there's nothing special about it overall.
