### ISSUE TITLE
Floating labels: the label does not shift to right with "dir=rtl"

### ISSUE THREAD

**Issue by MiladAbdullah** [twbs/bootstrap#38935]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The floating label is required to shift to the right side of the input when `dir=rtl` in the upper level of the element.

### Reduced test cases

```html
<div class="container" dir="rtl">
   <form class="form-floating">
        <input type="email" class="form-control" id="floatingInputValue" placeholder="name@example.com" value="test@example.com">
        <label for="floatingInputValue">Input with value</label>
   </form>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3

**Comment by MiladAbdullah** [comment]
Hello,
The example can be seen here:
[View on CodePen](https://codepen.io/MiladAbdullah/pen/mdQLgvK)

Where there are two inputs (one English and one Kurdish), the Central Kurdish is written Right to Left, but the label is shown on the left side of the input. Assigning `dir=rtl` to any element level does not change the behavior of the floating label.

**Comment by julien-deramond** [comment]
Thanks @MiladAbdullah 
Apparently, you don't use the RTL version of Bootstrap CSS file: `bootstrap.rtl.min.css` (source: https://getbootstrap.com/docs/5.3/getting-started/rtl/#required-html).

**Comment by julien-deramond** [comment]
Thanks @MiladAbdullah 
You're mixing LTR and RTL at the same time, are you following what's mentioned in https://getbootstrap.com/docs/5.3/getting-started/rtl/#ltr-and-rtl-at-the-same-time?
Otherwise, if you only need RTL, you should load `bootstrap-rtl.min.css` and not `bootstrap.min.css` (source https://getbootstrap.com/docs/5.3/getting-started/rtl/#required-html).

**Comment by MiladAbdullah** [comment]
Hi @julien-deramond 

The issue was I needed both RTL and LTR on the same page, which is why I did not load the related `css`. 
Now, since the issue is on my side, I close this.

Thanks
