### ISSUE TITLE
Column widths don't always work with 7 columns

### ISSUE THREAD

**Issue by thatcode** [twbs/bootstrap#38942]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I was trying to produce a calendar, which obviously has 7 columns. This bug doesn't reproduce with 3 or 5 columns - only 7! I've added borders to my days, and mostly it looks fine.

In MD and XL sizes as the window is resized sometimes the columns fill the row, and sometimes there's a pixel gap on the right hand side. I'm not sure how these sizes are calculated (and 7 is obviously a hard number!), but it does look as if something isn't quite right?

### Reduced test cases

[minimal.html](https://github.com/twbs/bootstrap/files/12104943/minimal.txt) - Sorry, I wasn't allowed to upload an HTML file so I renamed it to .txt. It's likely not actually minimal (in particular, it's got a debug panel to show you the viewport size!) but hopefully minimal enough?

I've added a testcase to [CodePen](https://codepen.io/Robert-Sworder/pen/jOQKaQZ) - I hope this works as it's my first time using it!

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

V5.3.0

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @thatcode. Could you please try to embed your reproduction example in [CodePen](https://codepen.io) or any other tools like this one so we have something ready to analyze?

**Comment by thatcode** [comment]
(I noticed my code had div's in the order container-row-row. I've now removed the outer row but it still shows up!)

I *think* I've worked this out. And there's likely nothing you can do that would work on all browsers.

XS
- We use 100% of the screen width, so everything is always squashed right next to each other. So no problem.

SM
- Viewport Width is 540px
- Container has 12px padding, so is 516px wide
- Row has 2px border, so is 512px wide.
- Col has 2px border, so is 69 1/7px wide, which browser calls 69.141px.
- Note that 0.141*7 = 0.987, just less than a whole number.
- Problem is seen when browser width is odd.

MD
- Viewport Width is 720px
- Container has 12px padding, so is 696px wide
- Row has 2px border, so is 692px wide.
- Col has 2px border, so is 94 6/7px wide, which browser calls 94.859px.
- Note that 0.859*7 = 6.013, just more than a whole number.
- Problem is not seen.

LG
- Viewport Width is 960px
- Container has 12px padding, so is 936px wide
- Row has 2px border, so is 932px wide.
- Col has 2px border, so is 129 1/7px wide, which browser calls 129.141px.
- Note that 0.141*7 = 0.987, just less than a whole number.
- Problem is seen when browser width is odd.

XL
- Viewport Width is 1140px
- Container has 12px padding, so is 1116px wide
- Row has 2px border, so is 1112px wide.
- Col has 2px border, so is 154 6/7px wide, which browser calls 154.859px.
- Note that 0.859*7 = 6.013, just more than a whole number.
- Problem is not seen.

XXL
- Viewport Width is 1320px
- Container has 12px padding, so is 1296px wide
- Row has 2px border, so is 1292px wide.
- Col has 2px border, so is 180 4/7px wide, which browser calls 180.578px.
- Note that 0.578*7 = 4.046, just more than a whole number.
- Problem is not seen.

So we see the problem when the browser width is odd and the residual column width, across all 7 columns, is just less than a whole number. Here's my theory:

1) When the browser width is odd, it has an odd number of pixels to divide over the two sides. It decides to reduce the pixel width on the right hand side.
2) This pulls the border on the row a pixel to the right.
3) When the residual is just *over* a whole number, it goes with.
4) When the residual is just *less than* a whole number, it doesn't - and a gap is seen.

If I'm right:
1) I'm not quite sure where this bug is, or how best for you to fix this for all number of columns. It'll likely show up differently on e.g., 11 columns.
2) I've no idea how Edge works out these widths. I note that 1/7 is 0.1428, rounded to 0.143, so Edge calling it 0.141 is wild...
3) I can likely work around this by strategically adding padding to the row on different viewport sizes so that the rounding is always in my favour.

Up to you what you do with this issue - if you think you can help the browser do better I'm happy to keep it open. If you think it's beyond what Bootstrap can do, I'm happy for you to close it :)
