### ISSUE TITLE
Improve button press feedback

### ISSUE THREAD

**Issue by twoco** [twbs/bootstrap#38951]
### Improvement

Bootstrap looks really interessting and nice. But the button press feedback feels boring.

<img src="https://github.com/twbs/bootstrap/assets/53160891/648a5788-1350-4c47-8a03-a6da4c1d59a8" width="300" />

Did I pressed the button? I'm not sure. The click behavior feels like disabled. Like pressing a stone.

It can be optional. But it would be great if the button feedback got better.

Suggestions:

**A**

<img src="https://github.com/twbs/bootstrap/assets/53160891/396d5f6d-a3f5-4f97-a077-1d660470028c" width="300" />

**B**

<img src="https://github.com/twbs/bootstrap/assets/53160891/4d61a29a-52a7-4610-80bf-b624535f6b76" width="300" />

**C**

<img src="https://github.com/twbs/bootstrap/assets/53160891/b9c721df-3d74-45c6-82fa-d3de3279e663" width="300" />

(Inspired by Material Design)

At best, the user should see that the button has been pressed when lift their finger from the touchscreen. Event if the button is pressed again. For example with the wave effect, which disappears after a certain time.

### Workaround

Quick and dirty... to simulate a RL button clicked you can use the following. But it's not optimal. I would delay the release state. And btw. this behavior is maybe not the best, if you want to embed your button. It works better for floating buttons. I would prefer the ripple effect.

```css
button.btn:active {
  transform: translateY(1px);
}
```

There are only CSS (pure) implementations of the ripple effect. But with some quirks or limitations. For example with overflow hidden you cannot use badges on edge anymore. Maybe with a wrapper...

**Comment by mdo** [comment]
This is why we don't over style our buttons—because just as many folks don't want something like this :). Appreciate the feedback, but we'll keep them lightweight for the time being :).
