### ISSUE TITLE
Official Bootstrap and Vite Guide Causes 404.

### ISSUE THREAD

**Issue by scottonanski** [twbs/bootstrap#38959]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The official guide, when followed exactly, produces a 404.

https://getbootstrap.com/docs/5.2/getting-started/vite/

### Reduced test cases

I don't know what this means.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @scottonanski 
Which part exactly?
I've retested it quickly and it it works perfectly. On top of that, you have https://stackblitz.com/github/twbs/examples/tree/main/vite?file=README.md which is the result of this guide, and it works.

**Comment by vidipsingh** [comment]
@scottonanski @julien-deramond Hi I am new to Open Source so can you please provide me some guidance on how can I be helpful in contributing in this Project.

**Comment by julien-deramond** [comment]
Most of the information is gathered in our [Contributing Guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md).

Regarding this issue, you can be helpful by explaining what's the problem with the Vite guide. Otherwise, please close it.
