### ISSUE TITLE
Table-dark deprecated, or no?

### ISSUE THREAD

**Issue by VividLemon** [twbs/bootstrap#38966]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The documentation is a bit unclear about which "dark" classes are deprecated. It would be my understanding that all dark classes have been deprecated after 5.3, however, the one that stands out is table-dark

Which creates bigger questions on if all dark classes are deprecated, or only some. 

If it is deprecated, a note for the docs would be appreciated

If it is not deprecated, nothing else is really required, except maybe an explanation on why it isn't :thinking: 

### Reduced test cases

na

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

na

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @VividLemon 

Our migration guide mentions which `*-dark` are deprecated (source: https://getbootstrap.com/docs/5.3/migration/#color-modes-1):

> **Deprecated** Color modes replace dark variants for components, so `.btn-close-white`, `.carousel-dark`, `.dropdown-menu-dark`, and `.navbar-dark` are deprecated.

For each variant, normally, you should have a warning callout like this one https://getbootstrap.com/docs/5.3/components/dropdowns/#dark-dropdowns explaining if the dark variant is deprecated.

For the table variants, there's an info callout in https://getbootstrap.com/docs/5.3/content/tables/#variants:

> **Heads up!** Because of the more complicated CSS used to generate our table variants, they most likely won’t see color mode adaptive styling until v6. 

However, I can easily understand that it's not that clear since v5.3 is the first step toward better color modes integration.

IDK if it brings more clarity.
Maybe you have some ideas on how and where to explain it better in the documentation?

**Comment by VividLemon** [comment]
> Thanks for reporting this issue @VividLemon
> 
> Our migration guide mentions which `*-dark` are deprecated (source: https://getbootstrap.com/docs/5.3/migration/#color-modes-1):
> 
> > **Deprecated** Color modes replace dark variants for components, so `.btn-close-white`, `.carousel-dark`, `.dropdown-menu-dark`, and `.navbar-dark` are deprecated.
> 
> For each variant, normally, you should have a warning callout like this one https://getbootstrap.com/docs/5.3/components/dropdowns/#dark-dropdowns explaining if the dark variant is deprecated.
> 
> For the table variants, there's an info callout in https://getbootstrap.com/docs/5.3/content/tables/#variants:
> 
> > **Heads up!** Because of the more complicated CSS used to generate our table variants, they most likely won’t see color mode adaptive styling until v6.
> 
> However, I can easily understand that it's not that clear since v5.3 is the first step toward better color modes integration.
> 
> IDK if it brings more clarity. Maybe you have some ideas on how and where to explain it better in the documentation?

It does help with things. I don't think anything will need to be improved. It is really just me not reading well enough. 

Do you happen to have any idea on when v6 will be released? I'm not looking for anything exact, I'm only wondering about an expected time frame.

**Comment by julien-deramond** [comment]
> Do you happen to have any idea on when v6 will be released? I'm not looking for anything exact, I'm only wondering about an expected time frame.

Unfortunately not. The roadmap looks like we'll have a v5.3.2 first to fix some remaining color modes issues and architecture, and hopefully, no other v5.3.x. After that a v5.4.0 to include at least some Sass utilities. And only after we'll start the v6 with a lot of refactoring.
So I don't have any idea of when v6 will be released, but not before months IMHO.

Feel free to close this issue if everything's answered in this discussion 🙏
