### ISSUE TITLE
Deprecation warning $weight: Passing a number without unit % (2) is deprecated

### ISSUE THREAD

**Issue by aaronhernan** [twbs/bootstrap#38960]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Deprecation Warning: $weight: Passing a number without unit % (2) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

212 │   @return mix(black, $color, $weight);
     │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    node_modules\bootstrap\scss\_functions.scss 212:11  shade-color()

There are serveral "mix" function calls, with the same deprecation warning message.

### Reduced test cases

Can be fixed like issue #37430,

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.0

**Comment by miken32** [comment]
@aaronhernan why did you close this? It hasn't been fixed

**Comment by aaronhernan** [comment]
@miken32 i dont remember exacly why... but after hours, i think it was my fault. I was able to run my code without any warning just changing the include order or bootstrap scss functions. I did a lot of things, and blaming myself at the end.

**Comment by miken32** [comment]
It's not your fault. For some reason they only seem to be fixing this on a one-off basis, rather than finding all uses of the `mix()` function. Was going to open my own bug but figured since this one is already here...

```none
vite v4.5.0 building for production...
transforming (1) resources/js/rampuser.jsDeprecation Warning: $weight: Passing a number without unit % (48) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
212 │   @return mix(black, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 212:11  shade-color()
    node_modules/bootstrap/scss/_functions.scss 217:27  shift-color()
    resources/sass/rampuser.scss 172:12                 root stylesheet

Deprecation Warning: $weight: Passing a number without unit % (72) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
207 │   @return mix(white, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 207:11  tint-color()
    node_modules/bootstrap/scss/_functions.scss 217:57  shift-color()
    resources/sass/app.scss 173:17                 root stylesheet
```
