### ISSUE TITLE
Collapse with multiple target stopped working in 5.3.0

### ISSUE THREAD

**Issue by fisharebest** [twbs/bootstrap#38974]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Until v5.2.3, the collapse plugin allowed a button to control several targets.
e.g. `data-bs-target="#hello,#world"`

Since v.5.3.0, it only appears to work with a single selector.  With multiple selectors, there are no errors, but no collapsing

I did read https://getbootstrap.com/docs/5.3/migration/ to see if this was an intentional change.

### Reduced test cases

5.2.3 - https://codepen.io/fisharebest/pen/dyQgwGr
5.3.0 - https://codepen.io/fisharebest/pen/GRwYPjR

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @fisharebest.
On my side, I don't have all the history in mind for this component so I don't know if this was something really supported voluntarily or not. The JS team will add more information later on.
In the meantime, the following could probably help you to have a workaround based on the [multiple targets documentation](https://getbootstrap.com/docs/5.2/components/collapse/#multiple-targets) where a common class is used as an example:  https://codepen.io/julien-deramond/pen/RwqedgY
