### ISSUE TITLE
Range form element track background is practically invisible on a white background

### ISSUE THREAD

**Issue by sallen-wiley** [twbs/bootstrap#38999]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The [range form element track](https://getbootstrap.com/docs/5.3/forms/range/#overview) is practically invisible on most of the screens I have tested. It uses the tertiary background colour which on a white background is very difficult to see.

$form-range-track-bg: var(--#{$prefix}tertiary-bg);

[Contrast check](https://snook.ca/technical/colour_contrast/colour.html#fg=F8F9FA,bg=FFFFFF)

This can be a user experience issue because at first glance, it just looks like a floating circle and the extent of the range cannot be seen.

### Reduced test cases

https://codepen.io/sallen/pen/NWeKjpB

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

v5.3

**Comment by mr-molecule** [comment]
Hi Folks,

Kindly Assign this issue to me, I am a beginner but i will try to solve this issue

**Comment by JOKER-ADitya** [comment]
![bootstrap](https://github.com/twbs/bootstrap/assets/87077815/7c44ffc8-c270-4b0b-b114-e6b110c8f5a4)
this problem?

**Comment by JOKER-ADitya** [comment]
![bootstrap1](https://github.com/twbs/bootstrap/assets/87077815/0790b5ac-320f-408b-99c0-798a8e562f1f)

it looks fine

**Comment by sallen-wiley** [comment]
> ![bootstrap1](https://user-images.githubusercontent.com/87077815/258901401-0790b5ac-320f-408b-99c0-798a8e562f1f.png)
> 
> it looks fine

That isn't how it looks on bootstrap's docs or in the reduced test case - perhaps you are overwriting the styles or using a different setup?

This is how it looks for me across my devices on the bootstrap docs and in the reduced test case:

![image](https://github.com/twbs/bootstrap/assets/22146491/029afa58-9930-4332-be35-84d72fd23715)

**Comment by boutetnico** [comment]
Workaround using [pre 5.3 method](https://github.com/twbs/bootstrap/blame/a1a9895aac0d65ab3cb64a2a64563a645ddb8a31/scss/_variables.scss#L975): 

```scss
$form-range-track-bg: $gray-300;
```
