### ISSUE TITLE
We are waiting for the navbar update

### ISSUE THREAD

**Issue by Gorbulev-Sergey** [twbs/bootstrap#39001]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

2. Guys, in navbar brand name and menu items are at different heights, it looks crooked. You can, of course, add styles to the navbar and tweak it, but you don't want to do it every time.

1. Guys, maybe somehow update the style of the components a little, and navbar too. In general, it's so good, but so many Bootstrap versions have already come out, I want some changes in appearance, neither co-ordinate, but small, adding grace.

### Motivation and context

I'm used to bootstrap. I want to see updates to the appearance of the components.

**Comment by Ahmadjajja** [comment]
Hi, I want to work on this

**Comment by mdo** [comment]
This is a super vague issue, so closing it out. You can adjust the alignment of the items in the navbar yourself. Like most other components, the styling is intentionally limited.
