### ISSUE TITLE
Replace deprecated`@import`

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [twbs/bootstrap#39027]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I recommend replacing the use of `@import`, which is deprecated and will be phased out in a few years, with `@use` or something of the like.

### Motivation and context

Since `@import` will be removed eventually, and the feature comes with some [issues](https://sass-lang.com/documentation/at-rules/import/), it would make sense to migrate before the breaking change takes place.

**Comment by mdo** [comment]
#29853
