### ISSUE TITLE
dart-sass deprecation warning: Passing percentage units to the global abs() function is deprecated.

### ISSUE THREAD

**Issue by rallets** [twbs/bootstrap#39028]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

While using the latest bootstrap with dart-sass and including bootstrap via scss, the latest dart-sass is warning about a deprecation:
```
DEPRECATION WARNING: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent
```
the stacktrace they show is:
```
node_modules\bootstrap\scss\mixins\_grid.scss 59:12        row-cols()
node_modules\bootstrap\scss\mixins\_grid.scss 85:13        @content
node_modules\bootstrap\scss\mixins\_breakpoints.scss 68:5  media-breakpoint-up()
node_modules\bootstrap\scss\mixins\_grid.scss 72:5         make-grid-columns()
node_modules\bootstrap\scss\_grid.scss 38:3                @import
node_modules\bootstrap\scss\bootstrap.scss 20:9            @import
```
I hope this helps. Tks for your work.

### Reduced test cases

@import '../../node_modules/bootstrap/scss/functions';
@import '../../node_modules/bootstrap/scss/_variables';
@import '../../node_modules/bootstrap/scss/bootstrap';

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.3.1

**Comment by Dreanad** [comment]
mixins\_grid.scss
the mixin row-cols need to be :  
```
@mixin row-cols($count) {
  > * {
    flex: 0 0 auto;
    width: divide(100, $count);
  }
}
```

the divide function need an integer instead of a percentage

**Comment by blankse** [comment]
@rallets @Dreanad I created a PR https://github.com/twbs/bootstrap/pull/39030

**Comment by featuriz** [comment]
From: https://sass-lang.com/documentation/breaking-changes/
`Passing a percentage unit to the global abs() is   deprecated beginning in Dart Sass 1.65.0.`
**Temporary solution** is to stay in v[1.64.2](https://www.npmjs.com/package/sass/v/1.64.2)

**Comment by AvigdorB** [comment]
line 59 change to
width: math.div(100%, $count)

**Comment by vince7488** [comment]
I will second this:

```
LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/components/Header/Header.scss
<w> Deprecation Passing percentage units to the global abs() function is deprecated.
<w> In the future, this will emit a CSS abs() function to be resolved by the browser.
<w> To preserve current behavior: math.abs(100%)
<w> To emit a CSS abs() now: abs(#{100%})
<w> More info: https://sass-lang.com/d/abs-percent
<w>
<w> src/components/Header/Header.scss 1:1                      divide()
<w> node_modules/bootstrap/scss/mixins/_grid.scss 59:12        row-cols()
<w> node_modules/bootstrap/scss/mixins/_grid.scss 85:13        @content
<w> node_modules/bootstrap/scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
<w> node_modules/bootstrap/scss/mixins/_grid.scss 72:5         make-grid-columns()
<w> node_modules/bootstrap/scss/_grid.scss 38:3                @import
<w> src/custom.scss 58:9                                       @import
<w> src/App.scss 2:9                                           @import
<w> src/components/Header/Header.scss 1:9                      root stylesheet
<w>

LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/App.scss
<w> Deprecation Passing percentage units to the global abs() function is deprecated.
<w> In the future, this will emit a CSS abs() function to be resolved by the browser.
<w> To preserve current behavior: math.abs(100%)
<w> To emit a CSS abs() now: abs(#{100%})
<w> More info: https://sass-lang.com/d/abs-percent
<w>
<w> src/App.scss 1:1                                           divide()
<w> node_modules/bootstrap/scss/mixins/_grid.scss 59:12        row-cols()
<w> node_modules/bootstrap/scss/mixins/_grid.scss 85:13        @content
<w> node_modules/bootstrap/scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
<w> node_modules/bootstrap/scss/mixins/_grid.scss 72:5         make-grid-columns()
<w> node_modules/bootstrap/scss/_grid.scss 38:3                @import
<w> src/custom.scss 58:9                                       @import
<w> src/App.scss 2:9                                           root stylesheet
<w>
```

Could you have a fix ASAP, please?

Deprecation warning issued by SASS: https://sass-lang.com/d/abs-percent

### Motivation and context

I just don't want LOGs and warnings like these when running yarn start.

**Comment by junaidfarooqui** [comment]
[8:09:00 PM] Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
57 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    node_modules/bootstrap/scss/vendor/_rfs.scss 57:14         divide()
    node_modules/bootstrap/scss/mixins/_grid.scss 59:12        row-cols()
    node_modules/bootstrap/scss/mixins/_grid.scss 85:13        @content
    node_modules/bootstrap/scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
    node_modules/bootstrap/scss/mixins/_grid.scss 72:5         make-grid-columns()
    node_modules/bootstrap/scss/_grid.scss 38:3                @import
    node_modules/bootstrap/scss/bootstrap.scss 20:9  
    
    
    NPM: "bootstrap": "^5.3.1",
    
    Seems like problem is not solve fully, please fix this as well.

**Comment by payalord** [comment]
> $dividend: abs($dividend);
> ```
> NPM: "bootstrap": "^5.3.1",
> 
> Seems like problem is not solve fully, please fix this as well. 
> ```

I have the same problem with bootstrap `5.3.1` in `_rfs.scss`, I hope it will be fixed fast. Proposed solutions:
```
math.abs(100%)
or
abs(#{100%})
```

**Comment by sezginriggs** [comment]
getting the same warning

**Comment by n-rodriguez** [comment]
Hi there! I have the same warning with bootstrap 4.6.2.

Thank you!

**Comment by rallets** [comment]
@VictorQueiroz I'm not involved in this project, and I don't want to speak out for the maintainers, but I don't think so. 
As this is a minor issue, it just logs a warning for a sass deprecated function, and it's not a breaking change, I think has a very low priority. You can keep an eye on the related issue, and see there is already some work in progress.

**Comment by n-rodriguez** [comment]
> As this is a minor issue, it just logs a warning for a sass deprecated function, and it's not a breaking change

I agree with you that it's just a warning but still, it's a warning and the warning says : 

>  In the future, this will emit a CSS abs() function to be resolved by the browser.

Since I'm not a CSS expert I don't know / can't measure the impact it will have on the app I'm maintaining : it could break something... or not 😄 

That's why i'm asking to maintainers if a fix on BS 4.x could be planned.

**Comment by jdion84** [comment]
vite HMR is spamming my terminal with this warning

can we get the PR pushed and released please

**Comment by blankse** [comment]
@jdion84 You can downgrade the sass dependency in your packages.json to remove the warnings:
```
    "sass": "~1.64.2",
```

My PR don't fix all warnings. This topic will take time.

**Comment by HNazmul-IV** [comment]
what preventing you to resolve this issue.. its not any hard issue.  getting bored by fixing it manually all the time. please solve it.

**Comment by epicserve** [comment]
> what preventing you to resolve this issue.. its not any hard issue. getting bored by fixing it manually all the time. please solve it.

@HNazmul-IV, I understand that it can be frustrating when things aren't working as expected. It's worth noting that many of us who contribute to open source projects do so voluntarily in our spare time. We're committed to resolving issues, and your patience and understanding go a long way in fostering a positive and collaborative environment. If you have any suggestions or insights regarding the problem, that might be more helpful than your demanding attitude.

**Comment by bdkjones** [comment]
@epicserve By the same token, it's worth noting that a PR with a fix has been open and ready-to-commit for three weeks. (Although from reading above, that PR may not remove all instances of the warning.) The community *has* chipped in, which makes the approval bottleneck frustrating.

**Comment by epicserve** [comment]
@bdkjones, I acknowledge how frustrating it is, but there is no reason to take a demanding and entitled attitude. To me, saying, "Please solve it," sounds demanding and entitled.

**Comment by SheldonWBM** [comment]
"Deprecation" does not mean that it doesn't work as intended.
"Deprecation" does not mean that it is a security issue.
"Deprecation" is only a warning for the near future that can get annoying to look at in the logs/console but, does no harm.
There is no reason to panic. Patience is a virtue.
They are aware of the issue, and have a PR and, a development process to go through.

**Comment by jdion84** [comment]
its unusable with vite, you literally get spammed non stop when running the dev server. it makes proper debugging impossible. the only fix is to downgrade sass or use something 10x slower than vite.

i might just go all in on tailwind, i been 50/50 hanging on to bootstrap for some projects (probably cause of nostalgia / familiarity) but this type of thing seems to happen all the time. someone deprecates something for no reason and then its weeks before an update.

**Comment by SheldonWBM** [comment]
I am using Vite as well. I know that Vite can get blamed for anything and everything, including Google Chrome not working for fast refresh; not a Vite issue as it was also an issue in CRA, i.e. look at the code, i.e. an ESLint rule to help with that but, I digress. Vite isn't the bogeyman here (you would get the same warning using CRA). It is a SASS warning (i.e. you can downgrade SASS) that Bootstrap is using a deprecated function. I am using SASS (not dart-sass). Vite is a lot faster, currently minimalistic and, having more control of the cleaner configuration is better than CRA (Internet Explorer era). I have only briefly tried Tailwind.  If the warning SPAMS too much, I would spend a little bit of time looking for a way to temporarily suppress the warning, until it is patched by Bootstrap (up to a month or two).  
https://stackoverflow.com/questions/68147471/how-to-set-sassoptions-in-vite
```
To hide the warnings, update your vite.config.js like this:

export default defineConfig({
  css: {
    preprocessorOptions: {
      scss: {
        quietDeps: true
      }
    }
  }
})
```

**Comment by musaab-abdalla** [comment]
**Immediate Solution:**
1. Open the **bootstrap/vendor/_rfd.scss** file.
2. At the beginning of the file, insert the following line: **@use "sass:math";**
3. Locate instances of the **abs()** function within this file and replace them with **math.abs()**.

**Comment by nsmithdev** [comment]
> From: https://sass-lang.com/documentation/breaking-changes/ `Passing a percentage unit to the global abs() is deprecated beginning in Dart Sass 1.65.0.` **Temporary solution** is to stay in v[1.64.2](https://www.npmjs.com/package/sass/v/1.64.2)

I applied the temp fix mentioned by @featuriz three weeks ago and pinned the sass package version to 1.16.2 by adding `"sass": "~1.64.2",` to my package.json.  It fixed the problem for my entire team with no manual node_module edits.  We will remove that one line when the new bootstrap version is released.

**Comment by lazaraslobo** [comment]
> getting the same warning

rm -rf node_modules
"sass": "~1.64.2"
npm i

**Comment by VictorQueiroz** [comment]
I don't even think we should be posting about this warning here. It's not about the framework. It's about the new and slow implementation of Sass in Dart. If you're willing to use bad software, that is ultimately up to you. It definitely has nothing to do with this project. Let's close this.

**Comment by n-rodriguez** [comment]
@VictorQueiroz it's painfully obvious that you don't know how to use your tools

**Comment by rallets** [comment]
It's very sad to see people complaining about an open source project, where you get everything for free, you have access to the source code, you have documentation, you can participate/contribute with a PR, and so on. 
Nope, still someone think you are their slave and work for free and asap. It's a "cultural" problem that I hope it will change soon. It's true the most important skills for a developer are soft skills, and very difficult to find nowadays. 😶
And we are speaking about bootstrap, one of the most used and supported framework in the last 12 years. 
I feel the pain of the maintainers. 😔
I understand why many choose to go closed source. Open source will not last long sadly...

**Comment by sbaechler** [comment]
To add @musaab-abdalla's fix to git (until a new version is released) use patch-package:

> **Immediate Solution:**
> 
> 1. Open the **bootstrap/vendor/_rfd.scss** file.
> 2. At the beginning of the file, insert the following line: **@use "sass:math";**
> 3. Locate instances of the **abs()** function within this file and replace them with **math.abs()**.

4.     npx patch-package bootstrap

**Comment by SheldonWBM** [comment]
@rallets I agree with you mostly however, "Open source will not last long" is wrong. Linus Torvald still argues for the "Open Source" concept with coding and the sciences (not necessarily politics and other "grey" areas). We use open-source resources to create and enhance private products and services. When code is no longer maintained, if there is no better alternative, being open-source, anyone with the qualified skills can pick up the project and continue it. https://www.youtube.com/watch?v=7XTHdcmjenI

**Comment by runphp** [comment]
I also encountered this issue. It's just a warning and I didn't notice any actual impact. But I'm still waiting for it to be fixed officially. 

```sh
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
57 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    D:\blog.runphp.net\node_modules\bootstrap\scss\vendor\_rfs.scss 57:14         divide()
    D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_grid.scss 59:12        row-cols()
    D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_grid.scss 85:13        @content
    D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_breakpoints.scss 68:5  media-breakpoint-up()
    D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_grid.scss 72:5         make-grid-columns()
    bootstrap\scss\_grid.scss 38:3                                                @import
    _style.scss 47:9                                                              @import
    D:\blog.runphp.net\css\main.scss 2:9                                          root stylesheet
                    ...done in 29.6915673 seconds.

      Regenerating: 1 file(s) changed at 2023-09-05 11:14:29
                    _sass/_style.scss
       Jekyll Feed: Generating feed for posts

**Comment by lusacramento** [comment]
> [runphp](/runphp)
> I also encountered this issue. It's just a warning and I didn't notice any actual impact. But I'm still waiting for it to be fixed officially.
> 
> ```shell
> Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
> In the future, this will emit a CSS abs() function to be resolved by the browser.
> To preserve current behavior: math.abs(100%)
> To emit a CSS abs() now: abs(#{100%})
> More info: https://sass-lang.com/d/abs-percent
> 
>    ╷
> 57 │   $dividend: abs($dividend);
>    │              ^^^^^^^^^^^^^^
>    ╵
>     D:\blog.runphp.net\node_modules\bootstrap\scss\vendor\_rfs.scss 57:14         divide()
>     D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_grid.scss 59:12        row-cols()
>     D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_grid.scss 85:13        @content
>     D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_breakpoints.scss 68:5  media-breakpoint-up()
>     D:\blog.runphp.net\node_modules\bootstrap\scss\mixins\_grid.scss 72:5         make-grid-columns()
>     bootstrap\scss\_grid.scss 38:3                                                @import
>     _style.scss 47:9                                                              @import
>     D:\blog.runphp.net\css\main.scss 2:9                                          root stylesheet
>                     ...done in 29.6915673 seconds.
> 
>       Regenerating: 1 file(s) changed at 2023-09-05 11:14:29
>                     _sass/_style.scss
>        Jekyll Feed: Generating feed for posts
> ```

I using Nuxt v3.7.1 with bootstrap 5.3.1 and I fixed this error following the [AvigdorB](https://github.com/AvigdorB)'s tips:

1 - In node_modules/bootstrap/scss/vendor/_rfs.scss file, add to top:

> ```shell
> @use 'sass:math';

2 - In line error, replace:

> $dividend: abs($dividend);

to
> ```shell
>$dividend: math.abs($dividend);

**Comment by hashimaziz1** [comment]
> To add @musaab-abdalla's fix to git (until a new version is released) use patch-package:
> 
> > **Immediate Solution:**
> > 
> > 1. Open the **bootstrap/vendor/_rfd.scss** file.
> > 2. At the beginning of the file, insert the following line: **@use "sass:math";**
> > 3. Locate instances of the **abs()** function within this file and replace them with **math.abs()**.
> 
>     4. ```
>        npx patch-package bootstrap
>        ```
> 
> 
> Be aware that this fix does not work under Libsass so the definitive fix for this issue will be something different.

This is mostly right the but the file is `_rfs.scss`.

**Comment by SheldonWBM** [comment]
@hashimaziz1 The fixed version of Bootstrap is 5.3.2 which is why this PR was closed.
After bumping Bootstrap to 5.3.2, if you still have the error, create a new PR? 

"Passing a percentage unit to the global abs() is deprecated since Dart Sass v1.65.0. It resulted in a deprecation warning when compiling Bootstrap with Dart Sass. This has been fixed internally by changing the values passed to the divide() function. The divide() function has not been fixed itself so that we can keep supporting node-sass cross-compatibility. In v6, this won't be an issue as we plan to drop support for node-sass." https://github.com/twbs/bootstrap/releases/tag/v5.3.2

**Comment by MohammedSalama** [comment]
Hey there , i have the same problem 
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
54 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    node_modules\bootstrap\scss\vendor\_rfs.scss 54:14             divide()

● Mix █████████████████████████ emitting (95%)
 emit

Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
54 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    node_modules\bootstrap\scss\vendor\_rfs.scss 54:14             divide()

× Mix
  Compiled with some errors in 5.71s

Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loade
rs
> <template>
|     <div class="container">
|         <div class="row justify-content-center">

webpack compiled with 1 error
![Capture](https://github.com/twbs/bootstrap/assets/32281997/4da0e54b-92e5-40df-8ce9-e9dd357a2068)

**Comment by Eldio-Neto** [comment]
if u are with the same error just follow what the user [musaab-abdalla](https://github.com/musaab-abdalla) says.

**Comment by FDiskas** [comment]
1. `npm i -D patch-package`
2. `npx -yes sass-migrator division node_modules/bootstrap/scss/**/*.scss`
3. `npx -yes patch-package bootstrap`
4. `npm set-script postinstall patch-package`

1. This will automatically change and update all deprecations (more info)[https://sass-lang.com/documentation/breaking-changes/slash-div/#automatic-migration]
2. This command will create a diff - what was changed
3. This script will apply that diff every time installing/updating node_modules

Yarn v1 users (more info)[]https://www.npmjs.com/package/patch-package#yarn-v1

1. `yarn add -D patch-package postinstall-postinstall`

**Comment by b1z3rr4** [comment]
For those using earlier versions of Bootstrap and encountering the warning related to the `abs` function, this solution addresses the issue in Bootstrap v4.5.0.

To resolve this warning, I implemented a custom SCSS solution that defines an `abs` function using `sass:math` and imports this custom file before the Bootstrap SCSS files. This approach ensures compatibility and resolves the warning without requiring an update to Bootstrap.

Here’s the detailed solution:

1. **Create a Custom SCSS File with `abs` Function**

   File: `src/styles/scss/_functions.scss`

   ```scss
   @use 'sass:math';

   @function abs($value) {
     @return math.abs($value);
   }
   ```

2. **Import Custom SCSS File Before Bootstrap Imports**

   File: `src/styles/scss/global.scss`

   ```scss
   @import './functions';
   @import 'bootstrap/scss/functions';
   @import 'bootstrap/scss/variables';
   @import 'bootstrap/scss/mixins/breakpoints';
   @import 'bootstrap/scss/mixins/grid-framework';
   @import 'bootstrap/scss/mixins/grid';
   @import 'bootstrap/scss/grid';
   @import 'bootstrap/scss/utilities/display';
   @import 'bootstrap/scss/utilities/flex';
   @import 'animate.css/source/_vars.css';
   @import 'animate.css/source/_base.css';
   @import 'animate.css/source/sliding_entrances/slideInUp.css';
   ```

By defining the `abs` function in the custom `_functions.scss` file and importing it first, any calls to `abs` within Bootstrap’s SCSS will use this custom implementation. This approach effectively addresses the warning encountered in Bootstrap v4.5.0.

**Comment by jquery-ajax-differing3** [comment]
> From: https://sass-lang.com/documentation/breaking-changes/ `Passing a percentage unit to the global abs() is deprecated beginning in Dart Sass 1.65.0.` **Temporary solution** is to stay in v[1.64.2](https://www.npmjs.com/package/sass/v/1.64.2)





https://stackdev.space/questions/ways-to-remove-all-breakpoints-in-bootstrap-5
