### ISSUE TITLE
variables --bs-nav-link-padding-y / --bs-nav-link-padding-x);  or --bs-* are not defined 

### ISSUE THREAD

**Issue by TaoufikR** [twbs/bootstrap#39067]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On my blazor web projet i'm using bootstrap v5.1.0 everything works fine, I want to upgrade to the latest bootstrap version v5.3.1 so I have replaced both bootstrap.min.css" and bootstrap.bundle.min.js" and now I'm getting 
![image](https://github.com/twbs/bootstrap/assets/38187683/26a0690f-d9c9-4c4e-a475-c8a79db9c3e9)
 so therefore i'm not getting the correct padding on my elements, I have many other issues related to this variables that are not been detected

### Reduced test cases

![image](https://github.com/twbs/bootstrap/assets/38187683/5c614913-b40e-42f4-9303-62f767b2e0b7)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.1

**Comment by TaoufikR** [comment]
Code example : https://stackblitz.com/edit/web-platform-zxccn3?file=index.html

**Comment by htmled** [comment]
I have the same issue, except with "--bs-border-width" using 5.3.1.

If I use the CSS file on the Bootstrap CDN, it does not occur. However, I see it when generating a .css file using nothing but "@import "../../../node_modules/bootstrap/scss/bootstrap";" in my SCSS file.

**Comment by TaoufikR** [comment]
I have noticed that this happens once i upgrade to a bootstrap version > 5.1.0 it's does not matter if the css comes from cdn or a downloaded file

**Comment by julien-deramond** [comment]
The reproducible example is a bit difficult to analyze without the images and stuff. But I can say that you don't use the `.navbar`, `.navbar-nav` nor `.navbar-collapse` classes mentioned in https://getbootstrap.com/docs/5.3/components/navbar/ so some custom properties are not defined. Regarding the `.nav-link` specific issue, `.navbar-nav` is probably missing here.

**Comment by TaoufikR** [comment]
I have updated the stackblitz link, yes you're right I have to add a "nav" class to my <nav> element that was the issue so it's really not applying logic on specific HTML5 elements

**Comment by julien-deramond** [comment]
Then, can I close this issue, or is there anything else to do here?

**Comment by TaoufikR** [comment]
Yes you can close it, I still have issue but not on this component though, if i encounter another one i'll post it, Thanks a lot !
