### ISSUE TITLE
Add CSS to print in black color while in dark mode

### ISSUE THREAD

**Issue by ghanchi2000** [twbs/bootstrap#39084]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Print text color in dark mode is grey. Please add css to print in black color while in dark mode

### Reduced test cases

Print text color in dark mode is grey. Please add css to print in black color while in dark mode

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.1

**Comment by julien-deramond** [comment]
We dropped all our print styles in https://github.com/twbs/bootstrap/pull/28339 because of the complexity of maintaining it as it depends often on the exact page design and layout.
We don't see us adding more here.
