### ISSUE TITLE
On form floating inputs, the labels are not truncated anymore but they go outside the input box instead

### ISSUE THREAD

**Issue by hanneswylaers** [twbs/bootstrap#39080]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In v5.3.0, when using a form floating input with a long label, the label is going outside of the the input field. 
![image](https://github.com/twbs/bootstrap/assets/15179013/f7e70d01-73b0-4046-a906-6405ae472f58)

In v5.2, the label got truncated.
![image](https://github.com/twbs/bootstrap/assets/15179013/2fb2fd3e-64e0-4a11-a483-333ab4d6aa78)

### Reduced test cases

https://codepen.io/hwy/pen/mdayMmg

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.x

**Comment by hanneswylaers** [comment]
It seems that in the latest version on `form-floating>label` there is a `z-index:2;` being added which wasn't there in earlier versions. Changing this back to `width:100%;` like before seems to solve it.

**Comment by roneymoon** [comment]
make sure you use the style property including the `overflow: hidden;` if even that doesn't work try using this 
`<label for="floatingInput" style="max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">`
this shall make sure your text stays inside the input box and doesn't overflow.
