### ISSUE TITLE
Super duper simple RTL support

### ISSUE THREAD

**Issue by jayzalowitz** [twbs/bootstrap#39102]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

add rtl support with dir='auto' on inputs and text areas

Ref: https://mough.xyz/312/psa-add-dir-auto-to-your-inputs-and-textareas

### Motivation and context

RTL languages need love too.

**Comment by mdo** [comment]
We have RTL support.
