### ISSUE TITLE
Tooltip and blinking cursor

### ISSUE THREAD

**Issue by shuashuai** [twbs/bootstrap#39106]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The Tootips component moves into the mouse on the side of the corresponding placement, and the mouse cursor will continue to blink！

![20230824-155440](https://github.com/twbs/bootstrap/assets/30591202/6de0ced4-871b-48f2-8d57-dfdf0fd1001f)

### Reduced test cases

You can test it from the official website example

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.x

**Comment by mdo** [comment]
This is most likely a pixel rounding issue and the browser is trying to determine what element you're actively hovering over. Closing as a won't fix.
