### ISSUE TITLE
Suggest a new feature

### ISSUE THREAD

**Issue by ssmalek6520** [twbs/bootstrap#39131]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello bootstrap team,
Please fix the default blue border for control, and make it thin just 1px with the primary color.
Thank you.

### Motivation and context

Because sometimes it's not designed properly with a blue border.

**Comment by julien-deramond** [comment]
I'm not sure to catch this feature request @ssmalek6520. Are you talking about the focused blue border color of form controls? Or something else?

**Comment by ssmalek6520** [comment]
Yes, I'm talking about the focused blue border color of form controls.
It's better with a 1px border.
