### ISSUE TITLE
Tooltips does not work in safari browser

### ISSUE THREAD

**Issue by AbtafAhamed** [twbs/bootstrap#39166]
### Prerequisites

- [ ] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [ ] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In my requirement whenever to hover on that should enable tooltips. so I have added `data-bs-trigger=" hover"`. but it's working in Chrome browser, not Safari. It stays whenever click previous items. 

### Reduced test cases

nill

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.3.1

**Comment by CyrilKrylatov** [comment]
Can you provide us a reduced test cases on codepen.io ?

Furthermore, does the tooltips are working for you on their documentation page? https://getbootstrap.com/docs/5.3/components/tooltips/

**Comment by AbtafAhamed** [comment]
Hi, Now it's working fine in Safari. I have updated the config after that is working
