### ISSUE TITLE
Missing v4.6.2 in NuGet

### ISSUE THREAD

**Issue by andrenevesgomes** [twbs/bootstrap#39184]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi!

Im trying to install v4.6.2 from [NuGet ](https://www.nuget.org/packages/bootstrap) into my project but this version doesn't appear to exist.

![image](https://github.com/twbs/bootstrap/assets/48434290/0163a628-94ef-4fd9-92ca-f4f0cb1aa66b)
![image](https://github.com/twbs/bootstrap/assets/48434290/c0800ac7-c5ea-419a-8b17-9c63d854297a)

### Reduced test cases

Theres none 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v4.6.2

**Comment by supergibbs** [comment]
Hmm, not sure how I missed that. Just uploaded it and it should be available soon.

**Comment by andrenevesgomes** [comment]
Thank you @julien-deramond @supergibbs
