### ISSUE TITLE
React Build Fails Using Bootstrap SCSS v5.3.2

### ISSUE THREAD

**Issue by alexfromsocal** [twbs/bootstrap#39185]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

It should be noted that this issue wasn't encountered when running in localhost, only when I attempted to make a product build. By running `npm run build-dev` (our build script for inserting dev environment variables, same issue replicated with prod), the following error was encountered:

```
alexfromsocal@Stevens-MacBook-Pro % npm run build-dev

> <project name and location>
> firebase use dev && env-cmd -f .env.development.json npm run build

Now using alias dev (<project environment>)

> <project name and location>
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/assets/scss/theme.scss
ParserError: Syntax Error at line: 1, column 29


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <project name> build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the<project name> build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexfromsocal/.npm/_logs/2023-09-15T00_23_25_256Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <project name> build-dev: `firebase use dev && env-cmd -f .env.development.json npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the <project name> build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexfromsocal/.npm/_logs/2023-09-15T00_23_25_299Z-debug.log`
```

Based on the given issue and what I had read on some other Github Issues and Stackover Flow posts, it may have regarded SCSS syntax of `#{$my-variable-name}` wrapping, as opposed to `$my-variable-name`.

### Reduced test cases

I combed through the initial theme.scss file, commenting out every import. As I uncommented each import, I further reduced it down to this import: `@import "~bootstrap/scss/bootstrap";`. By not including bootstrap, my builds would complete.

In this node module file `bootstrap/scss/bootstrap`, I further narrowed it down to to the `_pagination.scss` file. Again, commented out the file and the program built. 

FIX:
I found that by changing line 75 `margin-left: $pagination-margin-start;` to `margin-left: #{$pagination-margin-start};`, react-scripts built the app successfully. 

SUGGESTED FIX:
Wrap the variable so that _pagination.scss line 75 is now `margin-left: #{$pagination-margin-start};`

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3.2

**Comment by mdo** [comment]
I feel like this has come up a few times depending on the compiler. 🤔

**Comment by fewlme** [comment]
I still have the same issue... changing line 75 of pagaination.scss doeesn't do the trick ! Still a 
`ParserError: Syntax Error at line: 1, column 29`
