### ISSUE TITLE
<dialog>: The Dialog element

### ISSUE THREAD

**Issue by suchislife801** [twbs/bootstrap#39191]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Implement native `<dialog>` element in Bootstrap for enhanced accessibility and usability.

## Proposal to Implement Native `<dialog>` Element in Bootstrap

[MDN - The dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

## Introduction
The native HTML `<dialog>` element has recently gained full browser support. It offers built-in accessibility and usability features, making it an ideal choice for modal dialogs. This proposal suggests that Bootstrap should adopt the `<dialog>` element to enhance its dialog components.

## Benefits
- **Accessibility**: Implicit `aria-modal="true"` for modal dialogs.
- **Usability**: Built-in `.showModal()` and `.show()` methods for rendering.
- **Standardization**: Native HTML element, no need for custom implementations.

## Example Code
```html
<dialog id="myDialog">
  <p>Dialog content here</p>
  <button id="closeBtn">Close</button>
</dialog>
```
### `.show()`
- Opens the dialog as a non-modal.
```javascript
const dialog = document.getElementById("myDialog");
dialog.show();
```

### `.showModal()`
- Opens the dialog as a modal, making all other elements inert.
```javascript
const dialog = document.getElementById("myDialog");
dialog.showModal();
```

### `.close([returnValue])`
- Closes the dialog and optionally sets a return value.
```javascript
const dialog = document.getElementById("myDialog");
dialog.close("User clicked OK");
```

### Conclusion

Incorporating these built-in methods will enhance Bootstrap's dialog components in terms of usability and accessibility.

### Motivation and context

I love bootstrap and have used it for years. Anything I can do to make it smaller. =)

**Comment by julien-deramond** [comment]
Thanks for this feature request @suchislife801
It's not easy to find in our tracker but there's already an issue for this one in https://github.com/twbs/bootstrap/issues/33804.
To avoid duplicates, could you please copy your detailed proposal as a comment in https://github.com/twbs/bootstrap/issues/33804 so we can study your suggestion when we start the implementation in v6?
