### ISSUE TITLE
Placeholder for textarea not displayed.

### ISSUE THREAD

**Issue by pburndorfer** [twbs/bootstrap#39202]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

It seems like the placeholder of textarea elements is not working properly in combination with the form-floating class, as it is not shown in any case.
This is even the case on the official documentation:

Textarea without focus:
![image](https://github.com/twbs/bootstrap/assets/30462296/6d3f7f6b-5dfe-4235-a5d6-1b139190f63a)

Textarea with focus:
![image](https://github.com/twbs/bootstrap/assets/30462296/7a6a8338-c1fa-4ee2-bdf2-d77520f2e6bf)

Textarea with some sample text:
![image](https://github.com/twbs/bootstrap/assets/30462296/e90c1ebd-7849-4bde-9e65-82fd60e42f42)

The placeholder text "Leave a comment here" is not shown in any case.

### Reduced test cases

```
<div class="form-floating">
  <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea"></textarea>
  <label for="floatingTextarea">Comments</label>
</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3.1

**Comment by mdo** [comment]
This is by design in our floating forms.

**Comment by mrlife** [comment]
> This is by design in our floating forms.

Hi @mdo, it looks like all floating label inputs do not display the placeholder, meaning it's either have a floating label or a shown placeholder value?

**Comment by Cheerioalec** [comment]
@mrlife https://blazor-current.github.io/foreign-key-relationship/
