### ISSUE TITLE
When large amount of content is in the accrodion the collapse function is broken.

### ISSUE THREAD

**Issue by keondra2018** [twbs/bootstrap#39215]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If a large amount of content is in an accordion section and you open the first one and read to the bottom then click on the second accordion item the user is scrolled to the middle of the second accordion item and has to scroll back up to the top.

### Reduced test cases

To test is the issue was my local or bootstrap I went to the bootstrap accordions web page and modified the html making the content of the accordion more. Once I did that I was able to recreate the same issue I see on my site in the bootstrap accordion web page.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.0

**Comment by froboy** [comment]
I've been able to reproduce this issue... yay!

https://stackblitz.com/edit/fr5fwebg
using Bootstrap 5.3.3

Tested on 
- Chrome Version 133.0.6943.99 (Official Build) (arm64)
- Safari Version 18.2 (20620.1.16.11.8)

https://github.com/user-attachments/assets/01cc3744-36ac-4bc8-ba34-fbcfba1d0ed3
