### ISSUE TITLE
Dropdown Dark: Active Background change in variables.scss do not work. 

### ISSUE THREAD

**Issue by 0wczar** [twbs/bootstrap#39226]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

1. I did change in `_variables.scss`: `$dropdown-dark-link-active-bg: red !default`
2. Still change do not work.
![image](https://github.com/twbs/bootstrap/assets/2330394/adcad1e5-9bbc-4f47-9f73-4a0ac9d1e89a)
3. Also when I change this Dropdown to `dropdown-menu-dark` looks like this:
![image](https://github.com/twbs/bootstrap/assets/2330394/297803c3-7a7b-4c13-b3a5-1ff2bbbd31c6)

### Reduced test cases

https://airframe-c0ize5hn9-tomaszowczarczyk.vercel.app

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.3.2

**Comment by 0wczar** [comment]
Please see example: https://stackblitz.com/edit/github-kbdg1n?file=index.html

Problem:
1. Good: In Light Mode I have Red color active state.
2. **Problem**: In Dark Mode I have **Yellow Color Active State** added to `scss/_variables_dark.scss ` (`$list-group-active-bg-dark: yellow !default;`) and `scss/_root.scss` but still I see Red Color.


![2023-09-24_18-01-09 (1)](https://github.com/twbs/bootstrap/assets/2330394/ad8b3a1b-47f8-4bb5-851c-16a3b6b70cf6)

**Comment by julien-deramond** [comment]
Right now, there's nothing done especially for the dark mode for the list groups. In your case, you'll have to add a new rule like this one:

```scss
@if $enable-dark-mode {
  @include color-mode(dark) {
    .list-group .list-group-item.active {
      --#{$prefix}list-group-active-bg: yellow;
    }
  }
}
```

I've used `yellow` here but you could use a Sass variable instead with the right naming and setting it to `yellow` or any other color.

**Comment by 0wczar** [comment]
@julien-deramond I did add your snippet to `_root` and with color `yellow` - works.

But when I change to `$orange` *do not work*.

Link: https://stackblitz.com/edit/github-kbdg1n?file=scss%2F_variables-dark.scss

**Comment by julien-deramond** [comment]
You have to interpolate it like this: `--#{$prefix}list-group-active-bg: #{$orange};`

**Comment by 0wczar** [comment]
@julien-deramond Thanks! I just did upgrade my old project from BS4 to latest BS. I am very happy. 
Video: https://www.loom.com/share/8ff8bb95bc124c3ebafc9568fba60320?sid=1444a6b7-d9b5-4129-a4d7-aefd13d16d14

Later I will send link to this.
