### ISSUE TITLE
Bootstrap online builder tool

### ISSUE THREAD

**Issue by sovetski** [twbs/bootstrap#39227]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Unfortunately, because of bad developers who misused bootstrap, it became a sort of troll between developers. “Ah do you use bootstrap for that? lol” “If your site is slow it’s because of bootstrap” etc.

Indeed, there were and are quite a few developers who loaded the entire bootstrap just to stylize a button.

Many developers don't take the time to load only the SCSS or JS files they need, they load all the compressed CSS and JS for a simple trick.

My idea is: Create a tool on the bootstrap site (and maybe a sort of bundler later) that allows you to choose which component you want to use, for example: Navbar, Button, and/or Badge, and then we offer you which files you should call automatically.

Or as a bundler, CLI or something similar who detects our HTML and loads related JS, CSS etc.

Or we can add on each component documentation page the related files to load?

What do you think? If there are enough developers who agree with me and especially if it risks being accepted by bootstrap I can volunteer to start

### Motivation and context

It will improve developer experience, websites performance and bootstrap image for all developers trolling us 😅

**Comment by mdo** [comment]
We used to have one and it's just easier to handle via our ow build tools instead of wrapping it in a UI. Having a CLI would be fun, but we don't have the time to build that ourselves at this point.
