### ISSUE TITLE
RE: Spinner Feature

### ISSUE THREAD

**Issue by arnavnagpurkar** [twbs/bootstrap#39225]
### Prerequisites

- [ ] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [Kinda] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

v4.2 features spinner. They can be embedded inside a button: https://getbootstrap.com/docs/4.3/components/spinners/#buttons

Would be nice to be able to also embed a spinner inside an input.

Sometimes you have fields that perform async actions, a spinner inside the input would give feedback to the user (something is pending).

Example: https://github.com/tkrotoff/bootstrap-spinner

It would be very useful for the users if this feature is added!!

**Comment by coliff** [comment]
I'd love to see icons within form inputs too. @mdo made a PR for this a while back and that solution seems to work well.
https://github.com/twbs/bootstrap/pull/31667

Hope to see it revisited and merged before long. :-)
