### ISSUE TITLE
Border width problem for sub elements

### ISSUE THREAD

**Issue by ibragims** [twbs/bootstrap#39296]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi have one problem in **Bootstrap 5** css.
```
<div class="card border-5">
	<div class="card-body">
		<a class="btn btn-outline-primary" href="...">Link</a>
	</div>
</div>
```

When main div has class border-5, the child btn has too border 5px. So the parameter --bs-border-width: 1px will be overwritten to 5px and all sub elements has border 5px.

```
.border-1{--bs-border-width:1px}
.border-2{--bs-border-width:2px}
.border-3{--bs-border-width:3px}
.border-4{--bs-border-width:4px}
.border-5{--bs-border-width:5px}
```

I hope you understand me :D
Thanks

### Reduced test cases

**Bootstrap 5**
Solution for me was:
```
.border-1{border-width:1px}
.border-2{border-width:2px}
.border-3{border-width:3px}
.border-4{border-width:4px}
.border-5{border-width:5px}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.0

**Comment by jonnysp** [comment]
Hello @ibragims,

the current version does not use css variables. this bug has already been fixed.
https://github.com/twbs/bootstrap/blob/ce114117a8710016022c40e717cb1f3ec95a5d7f/dist/css/bootstrap.css#L7639

can closed
