### ISSUE TITLE
Table foot - Incorrect documentation

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#39319]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**In [Documentation](https://getbootstrap.com/docs/5.3/content/tables/#table-foot)**

You are show `table-light` for Table head `<thead>` for preview example in [Table foot](https://getbootstrap.com/docs/5.3/content/tables/#table-foot) point. but, Has not been added `table-light` class to table head for example code.

![table-foot](https://github.com/twbs/bootstrap/assets/2634085/1903d101-ff33-4d12-94a8-17252e3aafdd)

### Reduced test cases

Documentation problem.

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment]
Good catch @harnishdesign, thanks for reporting it. I've created #39320 to fix it.
