### ISSUE TITLE
Huge mess in documentation. Can it be resolved?

### ISSUE THREAD

**Issue by smileBeda** [twbs/bootstrap#39313]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Search google for "anything" related to Bootstrap. Even make the effort and add in `Bootstrap 5`, just to be sure you are not picking up Bootstrap 3, 4 ...

Find results, and - even if I develop almost daily - always realise you are probably on the _wrong_ documentation.

There is https://getbootstrap.com/docs/5.3/, which has a "latest" option to choose from.
There is https://getbootstrap.com/docs/5.2/, which has a "latest" option to choose from, but it is _not_ the latest! Above is! Yet the darn thing features the same "older" versions as the 5.3 doc does! 

(And many more other doc pages, all for a bit of version)

I would suggest, please, pretty please, put that stuff onto one page, make it default to the _latest_ first and open and active, and the user can then select _older_, _any older_ from the dropdown - without having to have nightmares to doubt if they are or not on the right doc.

This is really horrific.

Thank you.

### Reduced test cases

Navigate the web. Search for Bootstrap.

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

LATEST

**Comment by smileBeda** [comment]
And where is said duplicate?

**Comment by julien-deramond** [comment]
Maybe not in the same exact words but https://github.com/twbs/bootstrap/issues/28581 and https://github.com/twbs/bootstrap/issues/39212 are already mentioning this issue.

We did something as a first step in that direction by adding a "There's a newer version of Bootstrap!" in almost all the previous versions. Changing the dropdowns would mean changing the previous versions of the documentation that are generated at the release time: not everyone in the team is in favor of doing it.

We still need to work on it obviously, but we're currently focusing on finalizing the color modes right now.

**Comment by bluepuma77** [comment]
Why would you keep an old version of bootstrap doc with a dropdown saying "this is the latest", even if it is wrong?

It seems there is a new banner "There's a newer version of Bootstrap" on top, that's a great start. But that defies the purpose of the version dropdown. I googled to come to a specific page, now you bring me to latest homepage, and I need to start searching again for the content I was initially looking for. The version dropdown should just bring me to the latest version of that dedicated page.
