### ISSUE TITLE
.form-floating with parent .row causes floating label to left align

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#39317]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

.form-floating with parent .row causes floating label to left align

### Reduced test cases

Using 5.3.2: first code block works as expected, but adding `row` in the second code block causes the issue.

```html
<div class="justify-content-start">
<form class="form-floating col-4">
  <input type="email" class="form-control" id="floatingInputValue" placeholder="name@example.com" value="test@example.com">
  <label for="floatingInputValue">Input with value</label>
</form>
</div>

<div class="row justify-content-start">
<form class="form-floating col-4">
  <input type="email" class="form-control" id="floatingInputValue" placeholder="name@example.com" value="test@example.com">
  <label for="floatingInputValue">Input with value</label>
</form>
</div>
```

Repro: https://jsfiddle.net/ea5qp6fj/

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @mrlife 
I've just taken a look really quickly but given how the floating label is positioned, I'm not sure we can do anything to fix this behavior generically.
Would it be possible for you to use for instance the following instead?

```html
<div class="row justify-content-start">
  <div class="col-4">
    <form class="form-floating">
      <input type="email" class="form-control" id="floatingInputValue" placeholder="name@example.com" value="test@example.com">
      <label for="floatingInputValue">Input with value</label>
    </form>
  </div>
</div>
```

**Comment by ProffGideon** [comment]
unsubscribe

**Comment by mrlife** [comment]
Thanks, @julien-deramond and @mdo, this makes sense.
