### ISSUE TITLE
Update navbar with Brand text and icons and add profile dropdown and toggle ico

### ISSUE THREAD

**Issue by timid0x** [twbs/bootstrap#39329]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi, if possible add for next release on examples for:
https://getbootstrap.com/docs/5.3/examples/dashboard/

That navbar (top), it will have: brand ico, brand text, link text, profile icon dropdown and toggle ico.

### Motivation and context

I try to get template, but to upgrade more example navbar, because modern UI, use profile photo with dropdown items.

**Comment by julien-deramond** [comment]
Thanks for opening this feature request @timid0x.
It seems to me that we already have this kind of header in other examples. This dashboard is just one example of how things could be done but it needs to be adapted to one needs by combining other elements in the documentation or by creating the missing ones.

**Comment by mdo** [comment]
Yeah plenty of other examples, likely skipping this, but maybe we revisit some examples in v6.
