### ISSUE TITLE
Missing "dispose" method for Offcanvas in Documentation

### ISSUE THREAD

**Issue by MeeDNite** [twbs/bootstrap#39339]
Hello everyone.

I've noticed missing documentation for "dispose" method in Offcanvas Documentation in Official website docs.

[Offcanvas ](https://getbootstrap.com/docs/5.3/components/offcanvas/#methods)

But here this method exists on Code

[dispose Method declaration in source](https://github.com/twbs/bootstrap/blob/f7426c08e7818ff3eb77f7c7cde54ca6d28009b2/js/src/offcanvas.js#L160)

Can anyone confirm this please?

**Comment by julien-deramond** [comment]
Good catch @MeeDNite, thanks for reporting this issue. It's going to be fixed by https://github.com/twbs/bootstrap/pull/39340.
