### ISSUE TITLE
The input type date is displayed by default with a dark theme in the firefox browser in incognito windows (private windows)

### ISSUE THREAD

**Issue by ComandPromt** [twbs/bootstrap#39349]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the Firefox browser, the dark theme is always displayed in the date inputs when we view it in an incognito window or private window.

It even has the "form-control-light" class and still shows the dark theme

![bug](https://github.com/twbs/bootstrap/assets/17002667/125ecfc4-3d1b-421e-bbe5-d2434e8a67c6)

![bug_1](https://github.com/twbs/bootstrap/assets/17002667/c96c28ae-591d-4f18-a2de-045327a0098d)

### Reduced test cases

![bug_1](https://github.com/twbs/bootstrap/assets/17002667/9769aa91-d1ef-4715-be0d-8259f7efb353)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v.5.2.3

**Comment by julien-deramond** [comment]
While waiting for your reduced test case to check the issue, I can already say that `.form-control-light` doesn't exist in Bootstrap.

**Comment by ComandPromt** [comment]
> While waiting for your reduced test case to check the issue, I can already say that `.form-control-light` doesn't exist in Bootstrap.

Thanks for answering. The case is very simple to reproduce because I use the date type input by default
