### ISSUE TITLE
hover for dropdowns

### ISSUE THREAD

**Issue by muchirajunior** [twbs/bootstrap#39348]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

i thing it would be a great feature to add more hover functionality that trigger opening drop downs or pop overs or something like alignment changes. also utility class like 
`bg-primary hover-bg-warning`

### Motivation and context

I have seen it in other web CSS libraries and its pretty much cool

**Comment by mdo** [comment]
No plans to add this.

**Comment by muchirajunior** [comment]
ok thank you
