### ISSUE TITLE
Require path in vite.config.js gives error

### ISSUE THREAD

**Issue by hiamitchaurasia** [twbs/bootstrap#39396]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Require path in vite.config.js gives error. Check documentation on page https://getbootstrap.com/docs/5.3/getting-started/vite/.

Error Dynamic require of "path" is not supported.
It is listed here: https://github.com/Subwaytime/vite-aliases/issues/33

NPM Version: 10.1.0
Node Version: v20.5.0
Bootstrap Version: 5.3

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @hiamitchaurasia 
I tried to reproduce it with node v20.9.0 and npm 10.1.0 without any success.
Would you mind updating the description to indicate your vite version and also maybe your exact configuration?
