### ISSUE TITLE
type input min max

### ISSUE THREAD

**Issue by khanhnam99** [twbs/bootstrap#39414]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

type input min max

![image](https://github.com/twbs/bootstrap/assets/575720/b9620426-61ac-455e-92ba-51793e483c88)

### Motivation and context

up & down input 

![image](https://github.com/twbs/bootstrap/assets/575720/b9620426-61ac-455e-92ba-51793e483c88)

**Comment by julien-deramond** [comment]
Thanks for opening this issue @khanhnam99 
However, due to the lack of details, I'm going to close it. Please re-open something with more details and complete sentences.
