### ISSUE TITLE
Sass Color Scheme mixin incorrectly claims it supports custom schemes 

### ISSUE THREAD

**Issue by Stan-Stani** [twbs/bootstrap#39410]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://github.com/twbs/bootstrap/blob/v5.3.2/site/content/docs/5.3/customize/sass.md#color-schemes

```sass
@mixin color-scheme($name) {
  @media (prefers-color-scheme: #{$name}) {
    @content;
  }
}

.custom-element {
  @include color-scheme(dark) {
    // Insert dark mode styles here
  }

  @include color-scheme(custom-named-scheme) {
    // Insert custom color scheme styles here
  }
}
```

Using custom-named-scheme compiles to @media(prefers-color-scheme: custom-named-scheme) { } but schemes with custom names aren't supported by prefers-color-scheme.

### Reduced test cases

n/a

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v.5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @Stan-Stani 
You're right, [Media Queries Level 5](https://www.w3.org/TR/mediaqueries-5/#prefers-color-scheme) mentions that the values are either `light` or `dark`.
However, it's also mentioned the following making our `color-scheme` rather generic enough for the future:

> The values for this feature might be expanded in the future (to express a more active preference for light color schemes, or preferences for other types of color schemes like "sepia").

I'm going to propose a PR to fix the description which is wrong in the sense that `custom-named-scheme` is not custom at all but limited to `light` and `dark` values, and will probably limited to fixed values in the future as well (not custom).
