### ISSUE TITLE
Suggestion: `fs-normal` to set font-size to its "normal" (i.e. body) value

### ISSUE THREAD

**Issue by ThomasLandauer** [twbs/bootstrap#39422]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

New class `.fs-normal`

### Motivation and context

I'm missing a way to reset the font-size to normal body text size, analogous to the existing "-normal" class for font-weight ([`.fw-normal`](https://getbootstrap.com/docs/5.3/utilities/text/#font-weight-and-italics)) and font-style ([`.fst-normal`](https://getbootstrap.com/docs/5.3/utilities/text/#font-weight-and-italics)).
Was this just forgotten in https://github.com/twbs/bootstrap/pull/30571 or left out on purpose?

**Comment by mdo** [comment]
This would be `.fs-6` by default in the docs. And there's no `font-size: normal` value in CSS, so we don't provide a utility like that.

**Comment by mdo** [comment]
We could maybe do a `.fs-body` or something, but that might just be duplicative of what we provide with `.fs-6`.

**Comment by ThomasLandauer** [comment]
> And there's no `font-size: normal` value in CSS

Yeah, that's a good point against calling it `-normal`!

On the other hand:
If you override the default font-size by setting:
```css
--bs-body-font-size: 1.2rem;
```
then `.fs-6` still results in `1.0rem`.
So what would be nice would be a way to do something like `<h1 class="fs-body">` which resets the size to the "normal" body size.
