### ISSUE TITLE
Button group border has gaps

### ISSUE THREAD

**Issue by Clemens0** [twbs/bootstrap#39434]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If I try to set `.border border-dark` on a `.btn-group`, there is a small corner gap between the `.btn-group` and the first/last `.btn`

### Reduced test cases

```html
<div class="btn-group border border-dark">
    <a href="#" class="btn btn-dark">1</a>
    <a href="#" class="btn btn-dark">2</a>
    <a href="#" class="btn btn-dark">3</a>
</div>
```
![image](https://github.com/twbs/bootstrap/assets/29501691/2ae6d503-6640-4ab0-ac7e-37affab6e739)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.2

**Comment by mdo** [comment]
This is an issue with nested border radii unfortunately. If you add `border-radius: calc(var(--bs-border-radius) + 1px)` to the button group, that should fix it for you. TBD on if we'd revisit anything here or provide any fixes. Hard to account for the 1px border affecting radii everywhere.
