### ISSUE TITLE
Add Next/Previous Floating Button for Improved Documentation Navigation

### ISSUE THREAD

**Issue by seenivasanb** [twbs/bootstrap#39438]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

**Add Next/Previous Floating Button for Improved Documentation Navigation**

### Description:

I've encountered challenges when navigating to the next or previous page in the documentation. Despite having a sticky and scrollable sidebar, I find it inconvenient to locate the current page and then click the corresponding next/previous page.

To enhance user experience and streamline navigation, I propose the implementation of a new feature: Next/Previous floating buttons in the documentation page footer.

### Request Details:
- **Feature:** Next/Previous Floating Buttons
- **Location:** Documentation Page Footer
- **Purpose:** Facilitate seamless navigation between pages
- **Benefits:** Improved user experience for readers

### Labels:
- **feature**
- **docs**
- **UX**

Thank you for your attention to this matter.

### **Motivation:**
Adding Next/Previous floating buttons would eliminate the need to search for the current page and enhance the overall navigation experience for users. This feature is particularly valuable for readers who want to move between pages quickly and efficiently.

### **Feasibility:**
If feasible, please consider implementing the Next/Previous floating buttons. I believe this enhancement would be highly beneficial to our users and contribute to a more user-friendly documentation experience.

**Comment by mdo** [comment]
We'll pass on this, thanks though.
