### ISSUE TITLE
Deprecation warning (passing a number without unit)

### ISSUE THREAD

**Issue by miken32** [twbs/bootstrap#39432]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Same issue as #37424 where the function is missing units, but problem is in `shade-color()` and `tint-color()` instead of `opaque()`. Seems like the whole codebase should be searched for any uses of `mix()` without units.

```none
Deprecation Warning: $weight: Passing a number without unit % (48) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
212 │   @return mix(black, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 212:11  shade-color()
    node_modules/bootstrap/scss/_functions.scss 217:27  shift-color()
    resources/sass/app.scss 172:12                 root stylesheet

Deprecation Warning: $weight: Passing a number without unit % (72) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
207 │   @return mix(white, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 207:11  tint-color()
    node_modules/bootstrap/scss/_functions.scss 217:57  shift-color()
    resources/sass/app.scss 173:17                 root stylesheet
```

### Reduced test cases

```css
div.foo {
    color: shift-color($success, 48);
    background: shift-color($success, -72);
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.3.2

**Comment by julien-deramond** [comment]
Thanks for opening this issue @miken32 
The fix has been done for `opaque` because we used `100` instead of `100%` within this function and the modification was:
```diff
@function opaque($background, $foreground) {
-  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
+  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100%);
}
```

For `tint-color()` and `shade-color()`, we call `mix()` with the same exact parameter without transforming it; for example:
```scss
@function tint-color($color, $weight) {
  @return mix(white, $color, $weight);
}

@function shade-color($color, $weight) {
  @return mix(black, $color, $weight);
}
```

My first feeling would be to keep that as-is. It seems more logical to have the exact same type of parameter as Sass itself.

**Comment by miken32** [comment]
So I can just update my CSS to use % and it will work? Good to know; I’ll leave it to your team to decide whether to change anything or just update documentation. Thanks for the quick reply. On Nov 23, 2023, at 11:25 PM, Julien Déramond ***@***.***> wrote:﻿
Thanks for opening this issue @miken32
The fix has been done for opaque because we used 100 instead of 100% within this function and the modification was:
@function opaque($background, $foreground) {
-  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
+  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100%);
}
For tint-color() and shade-color(), we call mix() with the same exact parameter without transforming it; for example:
@function tint-color($color, $weight) {
  @return mix(white, $color, $weight);
}

@function shade-color($color, $weight) {
  @return mix(black, $color, $weight);
}
My first feeling would be to keep that as-is. It seems more logical to have the exact same type of parameter as Sass itself.

**Comment by julien-deramond** [comment]
Yep, based on your example, you'll just have to use % in order to make disappear the warnings:

```scss
.foo-warnings {
  color: shift-color($success, 48);
  background: shift-color($success, -72);
}

.foo-no-warnings {
  color: shift-color($success, 48%);
  background: shift-color($success, -72%);
}
```

> I’ll leave it to your team to decide whether to change anything or just update documentation.

This is something already mentioned in [Customize > Sass > Colors](https://twbs-bootstrap.netlify.app/docs/5.3/customize/sass/#colors) with the following:

```scss
.custom-element {
  color: tint-color($primary, 10%);
}

.custom-element-2 {
  color: shade-color($danger, 30%);
}
```

But let's suggest a PR to add a `.custom-element-3` additional example with `shift-color()` usage too: https://github.com/twbs/bootstrap/pull/39435
