### ISSUE TITLE
can't compile because of @popperjs/core issue

### ISSUE THREAD

**Issue by shaharsol** [twbs/bootstrap#39459]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://stackoverflow.com/questions/77580374/using-bootstrap-modal-in-a-typescript-simple-webapp?noredirect=1#comment136778920_77580374

### Reduced test cases

?

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.6

**Comment by mdo** [comment]
Sounds like an issue with the Bootstrap types project, which we don't maintain.
