### ISSUE TITLE
The first button in a input group of buttons is not rounded

### ISSUE THREAD

**Issue by iRoman1** [twbs/bootstrap#39475]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Reproduction of the problem
1. Create an input group
2. In the input group, include four child elements:
        i. input[type=checkbox].btn-check
       ii. label for this input with btn-outline-* class
      iii. Repeat previous two steps. 
### Current behavior
The first button in a input group of buttons is not rounded if there is an input before it.
### Expected/desired behavior
The rule to set the border radius to 0 should not apply to elements that are second if the first element is input[type=checkbox] or input[type=radio].

### Reduced test cases

Codepen: https://codepen.io/i-Roman/pen/bGzzXEv

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.2

**Comment by mdo** [comment]
> Thanks for reporting this issue @iRoman1 Just quickly looked at your CodePen, wouldn't be possible for you to use [Button group > Checkbox and radio button groups](https://getbootstrap.com/docs/5.3/components/button-group/#checkbox-and-radio-button-groups) instead?

This is the right move.
