### ISSUE TITLE
Missing are styles for the navbar toggler icon

### ISSUE THREAD

**Issue by PawelPatyk** [twbs/bootstrap#39476]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Missing from Bootstrap's CSS are styles for the navbar toggler icon, among others (e.g., the --bs-navbar-toggler-icon-bg value).

Also missing is the "max-width: 100%" value for images.

### Reduced test cases

https://codepen.io/PabloArtist/pen/gOqEabb

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.2

**Comment by josvleeuwen** [comment]
I ran into the same problem for the navbar toggler icon. For me it was not visible in regular/light mode, but it did become visible in dark mode. In my case I had the .navbar-toggler in a div in my header tag, separate from the .navbar in my header.

When inspecting _navbar.scss I discovered that `--#{$prefix}navbar-toggler-icon-bg` variable is only set in the .navbar selector, but not in the .navbar-toggler-icon selector.

Then for the dark mode it is set in both the `.navbar-dark, .navbar[data-bs-theme="dark"]` and `.navbar-toggler-icon` if color-mode is dark.

That last line adds the variable to the .navbar-toggler-icon, making it visible when in dark mode in my case.

When I added the following variable to the .navbar-toggler-icon selector it also worked in light mode:

```
.navbar-toggler-icon {
  --#{$prefix}navbar-toggler-icon-bg: #{escape-svg($navbar-light-toggler-icon-bg)};
}
```
