### ISSUE TITLE
Small buttons inside d-flex no longer small

### ISSUE THREAD

**Issue by Adria-indico** [twbs/bootstrap#39486]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

After updating to 5.3.0, buttons with class btn-sm are no longer small if inside a d-flex (or d-sm-flex).

The issue was marked as fixed in 2021: https://github.com/twbs/bootstrap/pull/34834

### Reduced test cases

<img width="220" alt="Screenshot 2023-12-12 at 11 31 24 AM" src="https://github.com/twbs/bootstrap/assets/64407827/4ac180b8-2b96-453a-a8cc-34475551ae9a">
<img width="988" alt="Screenshot 2023-12-12 at 11 31 02 AM" src="https://github.com/twbs/bootstrap/assets/64407827/445b92dc-dff2-4327-a93e-4615fa19ebeb">

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of Bootstrap are you using?

v5.3.0

**Comment by GopalDeyDev** [comment]
Hi, please assign me this issue

**Comment by julien-deramond** [comment]
@GopalDeyDev As mentioned in our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md#issues-assignment), we don't assign issues. Moreover, in this case, this issue doesn't have any live demo yet and hasn't been analyzed.
