### ISSUE TITLE
The "<use xlink:href>" code in the icon-link examples do not work

### ISSUE THREAD

**Issue by rob-stoecklein** [twbs/bootstrap#39499]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Some StackBlitz examples on the https://getbootstrap.com/docs/5.3/helpers/icon-link/ page do not work.

### Reduced test cases

1. Go to the given Bootstrap page (see above)
2. Click on any of the StackBlitz links that display an associated icon along with the text link
3. On the StackBlitz page, the icon does NOT appear

This perhaps is related to https://github.com/twbs/bootstrap/issues/36146,
which refers to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href, which says that `xlink:href` is deprecated.
This page suggests replacing `xlink:href` with `href`, but that change does not show the icon either.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.3.2

**Comment by rob-stoecklein** [comment]
Here's the image I forgot to post in the original:

![StackBlitz](https://github.com/twbs/bootstrap/assets/2582936/b5ba29af-696a-4ceb-8a9e-3833188d4244)

**Comment by WOLFRIEND** [comment]
I've noticed that this happens due to the absence of the `<svg/>` element on StackBlitz. If you'll open the [documentation](https://getbootstrap.com/docs/5.3/helpers/icon-link/) page, inspect it, found this `<svg/>` element, copy and paste it to StackBlitz, everything will work.
<img width="1310" alt="Screenshot 2023-12-16 at 11 59 41" src="https://github.com/twbs/bootstrap/assets/41586082/131781e6-2400-4a6d-8943-feabc3e01d0c">

**Comment by julien-deramond** [comment]
As said by @WOLFRIEND, this is because the `<svg>` containing the images is not transferred to StackBlitz. We'll look at how to do it without complexifying the system that does everything around this feature. Thanks for reporting it @rob-stoecklein.

**Comment by rob-stoecklein** [comment]
Thank you so much!
