### ISSUE TITLE
Add Floating Label or Label Outside on progress bar

### ISSUE THREAD

**Issue by moshetanzer** [twbs/bootstrap#39508]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I think it would add to have a floating label with current percentage at point of current progress on top of progress bar - similar to a message bubble with the percentage. If this is not possible should have an option like in tailwind of label in or outside progress

### Motivation and context

This solves issues with mutli colored progress bars where text isnt visible or progress bar that have a height that is too small.

**Comment by TommasoAllegretti** [comment]
I could be wrong but isn't this achievable with a regular `label`?

**Comment by goldbergmoshe** [comment]
Don't think so. Please reproduce.

**Comment by TommasoAllegretti** [comment]
https://codepen.io/TommasoAllegretti/pen/yLwBVEx

Is this the behavior you were trying to reproduce?

**Comment by goldbergmoshe** [comment]
Hi. Nope. Floating label at current percentage. Almost like a message bubble that stays with current percentage doesn't that make sense?

**Comment by TommasoAllegretti** [comment]
You could just add a `text-align: right` style to the `label` in the example I shared so that it matches the progress bar
