### ISSUE TITLE
Add a Timeline component.

### ISSUE THREAD

**Issue by Abhith-S** [twbs/bootstrap#39516]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

There is no timeline component available naively in  bootstrap.
 This is component is available in mdbootstrap and also materialUI.

example of component to be created :
![timeline](https://github.com/twbs/bootstrap/assets/75518181/0681ad0f-8a5d-4b31-b91a-82c450825193)

### Motivation and context

Mdbootstrap has a timeline component with different styles. It will be beneficial if bootstrap can replicate it.

link to mdbootstrap timeline - https://mdbootstrap.com/docs/standard/extended/timeline/

**Comment by mdo** [comment]
No plans to add this ourselves.

**Comment by Abhith-S** [comment]
Can I create this for you ?
