### ISSUE TITLE
Navbar only working in stackblitz demo

### ISSUE THREAD

**Issue by scottlocknet** [twbs/bootstrap#39518]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Was trying out 5.3.2 and the navbar. Noticed on the documentation page that it didn't appear to be rendering correctly.
![image](https://github.com/twbs/bootstrap/assets/133116675/20955199-5e2e-4821-9fd4-5ba4d64e69ed)

Went to the stackblitz demo page for it and it is working there.
![image](https://github.com/twbs/bootstrap/assets/133116675/71830c52-49ac-446f-9039-f5918669f0c3)

Put the same code in a single page in my project and it doesn't work (looks like the documentation page).

Then created a codepen page and copied the same code over to it. It also had the same issue.
https://codepen.io/scottlocknet/pen/poYovjJ

Appreciate any thoughts on what is going on.

### Reduced test cases

https://codepen.io/scottlocknet/pen/poYovjJ

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @scottlocknet 
Could you please provide a more precise definition of what you mean by 'that it didn't appear to be rendering correctly'? I'm not quite sure about the nature of the issue here.

**Comment by scottlocknet** [comment]
Sorry for not being more precise. In the first screenshot, you can see that the hamburger menu didn't collapse up and instead spreads out to the right. The bootstrap documentation site (https://getbootstrap.com/docs/5.3/components/navbar/), CodePen example and looking locally at a generic page all show the subitems spread out to the right.

When I viewed in stackblitz, it rendered as expected, with it collapsed and then able to expand.

**Comment by scottlocknet** [comment]
Ok, this is a user issue. I didn't even notice the nav class the example was generating. I've been stuck in legacy code for the past two years and just took the example code without looking through ever line... :)

<nav class="navbar navbar-expand-lg bg-body-tertiary">

Expand in there is forcing it out. Removing that fixed my issue. Odd that it worked in one testing tool and not anything else. No biggy though.
