### ISSUE TITLE
Instead of selecting in the code box, it is redirecting me to the bottom. (in the code snippet of any component)

### ISSUE THREAD

**Issue by huzaifaasim017** [twbs/bootstrap#39517]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I am selecting some code from the codebox so instead of selecting that code in the bootstrap v5.3, it is redirecting me to the bottom of the page, but if i use the copy button so it is copying the code and working fine.

### Reduced test cases

<img width="837" alt="image" src="https://github.com/twbs/bootstrap/assets/64212910/8c9d7b92-902b-4a6c-96ea-eb868aaf3fd7">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @huzaifaasim017 
On my side, I can't reproduce on macOS + Chrome.
Could you please provide a .gif or a small video just to be sure to understand the issue?
What version of Windows + Chrome are you using?

**Comment by huzaifaasim017** [comment]
If you see here in this video, if I am clicking on the copy button so it is fine, it is copying the code, but if I want to select only the button, not the whole modal, so I can not select that, and whenever I'm trying to selecting the only button, it is redirecting me at the bottom of the page, and this is not only with the button, it is with the all code snippets in the bootstrap docs...

https://github.com/twbs/bootstrap/assets/64212910/447b58ad-1c4d-4bb8-93b1-732335dcceed

**Comment by julien-deramond** [comment]
Thanks for the video @huzaifaasim017.
Could you please update the description so that we know what versions of Windows and Chrome you are using?
On my side, can't reproduce it with macOS 14.2.1 + Chrome 120.0.6099.129.

**Comment by huzaifaasim017** [comment]
**Operating System:** Windows 11 Pro 23H2 (pen and touch support).
**Browser:** Google Chrome 121.0.6167.16 (Official Build) beta (64-bit) (cohort: Beta).
**Hardware:** Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz (HP Elitebook).

---

I am using google chrome beta version,  but remember while testing in chrome beta i have faced some issues in my website as well and it was for coockie and local storage, and after some days when this chrome update come "120.0.6099.130", so i see the same issue in the actual chrome, so there is a chance that you will face this in the official chrome soon. or you can test in the chrome beta. [Download Chrome Beta Version](https://www.google.com/intl/en_pk/chrome/beta/)

**Comment by mdo** [comment]
I'm unable to reproduce in a newer version of Chrome, 120.0.6099.199.
