### ISSUE TITLE
 Attribute 'data-bs-delay' and JS not working on .toast

### ISSUE THREAD

**Issue by bavosadev** [twbs/bootstrap#39523]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The attribute **data-bs-delay** it isn't working how it should on toasts.  In the documentation, it's stated that we can change options via JS or data-bs but it's not working either way. I'm using JS script to trigger as it's said in the documentation.  The normal behavior would be the toast disappear after 5s as set in the attribute.

```js
const toastElList = document.querySelectorAll('.toast')  

const toastList = [...toastElList].map(toastEl => new bootstrap.Toast(toastEl, option))
```

![image](https://github.com/twbs/bootstrap/assets/144450824/3d932e1f-3a72-4667-b845-e7f8619c5fbe)

### Reduced test cases

https://codepen.io/viniciusbavosa/pen/QWoWGLG

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @bavosadev 
Your CodePen doesn't seem to be exactly the same thing as described with the source code screenshots. I've created a quick CodePen too to make a button triggering a toast that stays displayed 5 sec: https://codepen.io/julien-deramond/pen/XWGWMJK.

**Comment by bavosadev** [comment]
Thank you @julien-deramond  and i apologize about my CodePen, i've made another to illustrate better my example. I noticed on your CodePen that you implemented a JavaScript verification to display a live toast, but what i'm looking for is a basic toast that disappear after a set timer. 

### Reduced test case for error 1 - attribute 'data-bs-delay' not working
https://codepen.io/viniciusbavosa/pen/QWoWGLG

I set to fade out in 5s. Taking the documentation as ref it should be working fine. 

I also tested your CodePen on my Visual Studio Code and to my surprise it didn't work either, i click the trigger button  but nothing happens, it doesn't return a error in the console and all the libraries are imported fine. I looked on stackoverflow and followed some instructions there like setting a 'type="module" in my script but also didn't work out. I'm using local CDN to import Bootstrap 5 and it's working fine for all others elements, such as carousels, dropdowns, alerts, forms, buttons, etcs (I isolated the toast code within a new html file to make it easier to visualize, image below) . 

It's weird because on CodePen your live toast example works just fine but on my browser don't, and my example of a basic toast with delay doesn't work on neither of them



### Code for error 2 - JS not working
![image](https://github.com/twbs/bootstrap/assets/144450824/ad98f3ab-e5d0-4dd2-86c5-a59a220ff029)

### Libraries status on console
![image](https://github.com/twbs/bootstrap/assets/144450824/4055153a-9b4b-4856-803a-9a5de45685f0)



So now there are two errors, but they are related by js. 
### First Error: attribute 'data-bs-delay' not working
## Second Error: Javascript not working/not being called

Thank you again for you help!

**Comment by bavosadev** [comment]
I sorted it out. Instead of placing the Bootstrap script last in the body, I put it in the head without the defer attribute, so it loads first, and with that, everything worked perfectly. Thank you @julien-deramond for your time and help
