### ISSUE TITLE
Padding inconsistent in bootstrap5.3 

### ISSUE THREAD

**Issue by JigarDhaduk7** [twbs/bootstrap#39534]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In bootstrap5.3 I have face issue in modal-header, modal-body, card-header, card-body etc. everywhere spacing is 16px classes padding left 16px and padding right 16px if I used inside class .row then row minus margin left 12px and margin right 12px, rest 4px both side create issue.

![bootstrap5_spacing_issue_2](https://github.com/twbs/bootstrap/assets/73926342/bcbc1b52-7c3a-4c5a-b40d-ecf33c5f3e38)

### Reduced test cases

https://codepen.io/team/bootstrap/pen/qBamdLj?editors=1100

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

Latest (5.3.x)

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @JigarDhaduk7 
There seems to be an issue with your reduced tests case CodePen link which contains the default Bootstrap CodePen without any modifications.

**Comment by JigarDhaduk7** [comment]
> Thanks for reporting this issue @JigarDhaduk7 There seems to be an issue with your reduced tests case CodePen link which contains the default Bootstrap CodePen without any modifications.

@julien-deramond please check mentions screen short. I have mention in this screen

**Comment by JigarDhaduk7** [comment]
> Thanks for reporting this issue @JigarDhaduk7 There seems to be an issue with your reduced tests case CodePen link which contains the default Bootstrap CodePen without any modifications.

https://codepen.io/jigardhaduk7/pen/mdoVmyX?editors=1100

please check above codepen link for Reduced test cases

**Comment by mdo** [comment]
The grid is different than your other component overrides—we use some negative margin to make the text line up, not the elements themselves. No plans to explicitly revisit component sizing to make it the same as the grid, if that's what you're asking.
