### ISSUE TITLE
Radio inputs break out of .form-contol containers when using floating labels

### ISSUE THREAD

**Issue by mimmi20** [twbs/bootstrap#39546]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using multiple radio inputs inside a `.form-control` div and using floating labels, the radio inputs will break out of form-contol div.

This can be solved by this change:
```css
.form-floating > .form-control {
    height: fit-content;
}
```

### Reduced test cases

https://codepen.io/mimmi20/pen/JjzYYrV
https://codepen.io/mimmi20/pen/ExMVZrJ - with validation

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Opera

### What version of Bootstrap are you using?

5.3.2

**Comment by Johnylab** [comment]
Checking the source code and examples, it looks like the `form-control` class is intended to be assigned to the `input` elements instead of being a wrapper for them.

If you need a border around them, I'd consider using a combination of `card` with padding or a `card-body` inner element.

**Comment by mimmi20** [comment]
I dont want just a border around the checkboxes and radios. I also want to use floating labels and form validation (I added a second examle for that, but that includes more changes, which are not part of this ticket).

If this way handling radio inputs or checkboxes with floating labels is not intended, I would like have examples in the documentation for that.

**Comment by manviyadu1shi** [comment]
hey! @mimmi20 , I'm a new contributer , can I get to know what exactly do you want. For example , if you just want to fix the radio inputs break out, you can add a size specifier such as mb-3 in the form check label tag. It will then look like the image i've attached. I just wanted to know if you wanted to fix that other than the fixes in the documentation.
![image](https://github.com/twbs/bootstrap/assets/155363925/0f3d2c75-cf24-46a6-aa96-2db891dcc776)

**Comment by manviyadu1shi** [comment]
Really sorry ,if I've misunderstood the issue , I'm just a newbie figuring out here :')

**Comment by mimmi20** [comment]
> hey! @mimmi20 , I'm a new contributer , can I get to know what exactly do you want. For example , if you just want to fix the radio inputs break out, you can add a size specifier such as mb-3 in the form check label tag. It will then look like the image i've attached. I just wanted to know if you wanted to fix that other than the fixes in the documentation.

As you can see, there are two radio inputs. The second one is breaking out of `.form-contol` container. The reason is simple, that the `.form-control` in combination with `.form-floating` has a fixed height.

**Comment by manviyadu1shi** [comment]
> > hey! @mimmi20 , I'm a new contributer , can I get to know what exactly do you want. For example , if you just want to fix the radio inputs break out, you can add a size specifier such as mb-3 in the form check label tag. It will then look like the image i've attached. I just wanted to know if you wanted to fix that other than the fixes in the documentation.
> 
> As you can see, there are two radio inputs. The second one is breaking out of `.form-contol` container. The reason is simple, that the `.form-control` in combination with `.form-floating` has a fixed height.
> 
> The result should look like in [this pen](https://codepen.io/mimmi20/pen/MWxyWxr)

Oh! Gotcha. Thanks for clearing this out. This should definitely be added into the documentation.

**Comment by mdo** [comment]
We don't support radio inputs on floating forms.
