### ISSUE TITLE
Alert with icons example is broken

### ISSUE THREAD

**Issue by huseeiin** [twbs/bootstrap#39548]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://getbootstrap.com/docs/5.3/components/alerts/#icons
![image](https://github.com/twbs/bootstrap/assets/122984423/c3b41e9a-7753-4917-bf86-7fa756b7ee3e)
using bootstrap 5.3.2 the alert with icons example copied from bootstrap docs like like this ^

### Reduced test cases

https://codepen.io/huseeiin/pen/XWGmpVx

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @huseeiin 
This alert variant uses Bootstrap icons that require setting its size correctly in this example.

> Depending on your icons and content, you may want to add more utilities or custom styles.

We are using here the `.bi` class that is defined in the CSS of the documentation as the following:

```css
.bi {
  width: 1.5rem;
  height: 1.5rem
}
```

If you add this CSS to your CodePen example, it'll work as in our documentation.
I'm closing this issue as this comment resolves it.

**Comment by huseeiin** [comment]
> Thanks for reporting this issue @huseeiin This alert variant uses Bootstrap icons that require setting its size correctly in this example.
> 
> > Depending on your icons and content, you may want to add more utilities or custom styles.
> 
> We are using here the `.bi` class that is defined in the CSS of the documentation as the following:
> 
> ```css
> .bi {
>   width: 1.5rem;
>   height: 1.5rem
> }
> ```
> 
> If you add this CSS to your CodePen example, it'll work as in our documentation. I'm closing this issue as this comment resolves it.

i'm using `<div role="alert" class="alert alert-danger alert-dismissible fade show">
  <i class="bi bi-exclamation-triangle-fill"></i>
  Hello
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
` which solves it but there is no space between the icon and the text. is there a solution?

**Comment by julien-deramond** [comment]
Yes, in https://getbootstrap.com/docs/5.3/components/alerts/#icons, we're using `.me-2` for the SVG so that it adds a right margin.
