### ISSUE TITLE
Tabindex issues on Firefox and Safari

### ISSUE THREAD

**Issue by levipadre** [twbs/bootstrap#39562]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

By using Tab it's not possible to go through the links on Safari and Firefox.
Also, when a modal is open, Safari stucks at the close button, can't navigate further down with Tab.
Chrome seems fine.
Same issue on https://getbootstrap.com/docs/5.3/components/modal/ and https://getbootstrap.com/docs/5.3/components/navbar/ pages.

### Reduced test cases

https://codepen.io/levipadre/full/GReoMVe

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari, Firefox

### What version of Bootstrap are you using?

v5.3

**Comment by louismaximepiton** [comment]
Hey there, thanks for your contribution to Bootstrap.

I can't reproduce the issue you just mentioned on https://getbootstrap.com/docs/5.3/components/modal/ nor https://getbootstrap.com/docs/5.3/components/navbar/ using Browserstack.

However, I can reproduce the issue on the Codepen you link.

Could you please indicate the version of your OS and browsers you use to ease the searchs ?
Thanks in advance.

**Comment by levipadre** [comment]
IOS: Sonoma 14.2.1
Firefox: 121.0 (64-bit)
Safari: Version 17.2.1 (19617.1.17.11.12)

I also made a video for the two browsers (where you can't see jump between elements, I'm pressing Tab :)
https://app.screencast.com/adcMJKz3bUCyM

**Comment by mdo** [comment]
Might be that Safari's tabbing is different—it sometimes requires a change in the app's settings to be able to tab through all elements on the page.

![CleanShot 2024-01-08 at 15 37 15@2x](https://github.com/twbs/bootstrap/assets/98681/78cd06ce-cd94-483f-b0e7-e5299d073f61)

**Comment by levipadre** [comment]
Thanks @mdo. I didn't think it was a browser issue, but thanks for checking it.
Firefox has similar settings and it's turned off by default.
<img width="496" alt="Screenshot 2024-01-09 at 09 56 17" src="https://github.com/twbs/bootstrap/assets/357974/ba0348ad-f1af-486b-9b22-ce7ab3a428f3">
