### ISSUE TITLE
Navbar not clickable on Mobile when using data-bs-hover!

### ISSUE THREAD

**Issue by kotakomputer-ceo** [twbs/bootstrap#39564]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Navbar not clickable on Mobile when using _data-bs-hover_.

```
<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-hover="dropdown" aria-expanded="false">
    Parent Dropdown
</a>

```
Above code works fine on Desktop, we are able to Click "Parent Dropdown". But on Mobile we can not click "Parent Menu".

HOW TO SOLVE THIS ISSUE?

Bootstrap must separated the Dropdown Icon on Mobile, so:
1. User can click the Parent Menu
2. User can click the Dropdown Icon to open Dropdown-Items

Please try the menu of https://drupalnesia.com/ on Mobile for demonstration of how to fix this issue.

### Reduced test cases

```
<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-hover="dropdown" aria-expanded="false">
    Parent Dropdown
</a>

```
### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.3.x

**Comment by manviyadu1shi** [comment]
Hey! @kotakomputer-ceo , Are you talking about the hamburger icon is not working in mobile mode? Just confirming , cause mine works completely fine , as for the website you've linked.

**Comment by mdo** [comment]
There is no `data-bs-hover` in Bootstrap.
