### ISSUE TITLE
Bootstrap Modals not animated in Firefox 121 / Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by sekirkity** [twbs/bootstrap#39565]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Modals are no longer animated in Bootstrap 5.3.x in the most recent version of Firefox (121), on Ubuntu 22.04.3 LTS (and possibly other versions). I downgraded my Firefox version to 120.0.1 and confirmed that modal animations resumed functioning. 

### Reduced test cases
`<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">`

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.x

**Comment by mdo** [comment]
I'm guessing there's something here about reduced motion being enabled.

**Comment by sekirkity** [comment]
Hi @mdo , I can confirm that the "Enable Animations" option is enabled on my Ubuntu device. As far as I'm aware, Ubuntu Linux does not have an option for "Reduced Motion", and this option is only present on iOS/macOS operating systems. Have you been unable to confirm this issue is present in Ubuntu 22.04.3 LTS? Please let me know if there's any additional troubleshooting steps I can take to assist, thanks.

**Comment by sekirkity** [comment]
Quick update, I was able to get animations working in Firefox 121 for Ubuntu 22.04.3 LTS by setting the "ui.prefersReducedMotion" property to 0 in about:config. I'm unsure why the Firefox updated caused this setting to be necessary, but it's definitely not an issue on the Bootstrap side. Thank you for your time, and I hope this assists anyone else who runs into this issue.
