### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by lucianor** [twbs/bootstrap#39615]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Update all references in Bootstrap code that makes use of non inclusive language terms. Many guides are available online [1]

[1] https://itconnect.uw.edu/guides-by-topic/identity-diversity-inclusion/inclusive-language-guide/
[2] https://www.aswf.io/blog/inclusive-language/

### Motivation and context

Within technology, one of the ways to drive a more diverse, equitable, and inclusive culture is to replace “offensive” language in code bases and documentation. This involves assessing existing code bases and documentation, identifying potentially problematic language, and replacing terms with more acceptable language. By using more inclusive and intentioned language in code and documentation, we create an environment for developers where differences are welcomed and identified as strengths.

Above copied from https://www.aswf.io/blog/inclusive-language/

There are other sites which reference this becoming more important with many companies adopting efforts for that:

https://www.forbes.com/sites/carolinamilanesi/2021/06/29/the-importance-of-inclusive-language-and-design-in-tech/?sh=703530adb167

https://www.aswf.io/blog/inclusive-language/

**Comment by julien-deramond** [comment]
Thanks for suggesting this enhancement @lucianor 
I've associated it with the "help wanted" label to see if folks in the community could help us spot the problematic wording in the documentation and code. IMO it would be the first step to tackle this topic. And then, discuss the possibilities of replacements. What do you think?

**Comment by mdo** [comment]
Feel free to open PRs to fix anything y'all find!

**Comment by zabeer12** [comment]
интересный
