### ISSUE TITLE
Add support for clearing floats in the Float utility class

### ISSUE THREAD

**Issue by ProCycleDev** [twbs/bootstrap#39610]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add a `.float-clear` class that applies `clear: both` to an element
Optionally add a `.float-clear-start` and `.float-clear-end` class that applies `clear: left` and `clear: right`

### Motivation and context

Bootstrap offers utility classes for floating and also one to apply clearfix. However it does not offer a float clear class.

The `clear` css rule is useful for when you've floated an element and you have text or other items wrapping the floated element but you want to add another block that does not flow around the element and instead creates a "new line".

### Example
Here is an example use case. A set of step by step instructions with pictures for certain steps.

**Without clearing right floats:**
![Without clearing right floats](https://github.com/twbs/bootstrap/assets/18075290/c9fa18ba-9c9e-4264-8ca3-ccadc7eea978)
It's unclear which image applies to which step. Also get some float weirdness because they're attached to steps that are close together.

**Clearing the right floats:**
![Clearing the right floats](https://github.com/twbs/bootstrap/assets/18075290/a06c469f-fe14-4cce-9ccc-7afb21928e82)
Applying `clear: both` to the next step causes it to drop below the floated image. Desired behavior. Would need to either create a custom class to do this or add an inline style to the `<li>` element.

So why not use .clearfix? Because it is not designed for this purpose and gives strange results
**Using clearfix:**
![Using clearfix](https://github.com/twbs/bootstrap/assets/18075290/7204e642-eb00-48cd-bccf-16349b9adf56)

What about `.float-none`? `float: none` does not behave the same way as `clear` and is only useful in the context of not floating elements in certain breakpoints.

**Comment by Shankar009378** [comment]
Please assign me I am doing this

**Comment by mdo** [comment]
https://getbootstrap.com/docs/5.3/helpers/clearfix/
