### ISSUE TITLE
Vertically Tabs

### ISSUE THREAD

**Issue by wisamidris7** [twbs/bootstrap#39613]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can Bootstrap Contains Vertically Tabs

### Motivation and context

Just Like That

**Comment by mdo** [comment]
No plans to do this.
