### ISSUE TITLE
when clicking in a code sample box it scrolls all the way to the bottom of web page

### ISSUE THREAD

**Issue by yesitisme** [twbs/bootstrap#39635]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

in the current docs a div with class .bd-code-snippet that has a bottom scroll bar because the content is to long, scrolls to bottom of page when I want to select the code in the div.

### Reduced test cases

https://getbootstrap.com/docs/5.3/getting-started/introduction/

check it out yourself

I have it on chrome and edge, I didnt test other browsers

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.3

**Comment by ManasSingh77** [comment]
Could you please further elaborate the issue as well as provide the file address to work on?

**Comment by ManasSingh77** [comment]
Could you further elaborate the issue as well as provide the file address to work on?

**Comment by Kyzerbread** [comment]
This happens to me as well. Edge browser. Certain code fields, when click+dragged to highlight portions of the code, the page will  scroll to the bottom instantly.

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @yesitisme 
It's already been reported in https://github.com/twbs/bootstrap/issues/39605
More details are present in this issue's discussion
Closing this one as duplicate
