### ISSUE TITLE
Form validation with input group not changing input-group-text border color

### ISSUE THREAD

**Issue by Tazman845** [twbs/bootstrap#39645]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using form validation and you have an input-group on the form and validation triggers the input-group-text portion of the input-groups border doesn't change color to indicate it's current state like the input. Refer to the image attached.

![Bootstrap Validation](https://github.com/twbs/bootstrap/assets/32995/a1a0e6c5-5688-403a-b1fa-6d0cc7ca5742)

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
That's correct, and intended. See the example from the docs:

![CleanShot 2024-02-05 at 20 11 37@2x](https://github.com/twbs/bootstrap/assets/98681/ae4f7b38-91a8-43ad-bc97-3d3f8bdfe7af)
