### ISSUE TITLE
Trying to copy code from the docs forces the page to scroll to the bottom

### ISSUE THREAD

**Issue by BaeFell** [twbs/bootstrap#39647]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hey there -

When trying to copy part of an example on https://getbootstrap.com/docs/5.3/forms/input-group/ the page scrolls all the way to the bottom. Happens on Chrome (Version 121.0.6167.140 (Official Build) (64-bit)) and Edge

### Reduced test cases

None

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
#39605
