### ISSUE TITLE
Bugs inside "Cover Template" and "Product Template"

### ISSUE THREAD

**Issue by gipic** [twbs/bootstrap#39656]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

There are two small bugs inside these webpages published on bootstrap v 5.3

- "Cover template": light-dark toogle does not work
- "Product example": when screen is small (mobile for example), menu does not work. I click the button but nothing happens.

I am new to bootstrap and I was looking to some examples for the first time.
I am unable to solve these small bugs.
Thank you very much.

### Reduced test cases

https://getbootstrap.com/docs/5.3/examples/cover/

https://getbootstrap.com/docs/5.3/examples/product/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3

**Comment by julien-deramond** [comment]
Thanks for reporting this double-issue @gipic 

> "Cover template": light-dark toogle does not work

This example was created to be always dark. The theme selector well changes the `data-bs-theme` to "light" and "dark" values. However, this example uses all the time `.text-bg-dark` to define the background as dark in all cases.

> "Product example": when screen is small (mobile for example), menu does not work. I click the button but nothing happens.

Good catch! I've created https://github.com/twbs/bootstrap/pull/39657 to fix it
