### ISSUE TITLE
focus-ring is not displayed on a button applied shadow class

### ISSUE THREAD

**Issue by yonta** [twbs/bootstrap#39668]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Applying the shadow class to a button prevents the display of the focus-ring.
Using the test case code and accessing the HTML in a browser, attempt to focus on the button using the keyboard's Tab key.

## expected

![image](https://github.com/twbs/bootstrap/assets/849256/254032f3-bf28-4a1f-8ac6-90aca52d0130)

## actual

![image](https://github.com/twbs/bootstrap/assets/849256/468bf991-e73c-44db-8269-666fd3ef6929)

### Reduced test cases

```html
<button class="btn btn-primary shadow">Button</button>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3.2, main(commit 4e35f64fdc96e505fa659a41ee2e1c1cc87df0d8)

**Comment by mdo** [comment]
Yeah, our focus outlines are built with `box-shadow` so you're overriding them with a utility. Modify the button CSS variable, or use a wrapper element (less ideal).

**Comment by yonta** [comment]
Thanks to reply.
I will remove shadow class from button element of my application.
