### ISSUE TITLE
Search Button not responding

### ISSUE THREAD

**Issue by ani0525** [twbs/bootstrap#39665]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

[Bootstrap Documentation](https://getbootstrap.com/docs/5.3/getting-started/javascript/)

- **Search button not working**: When I scroll down the page, the search button on the top right corner becomes unresponsive and does not open the search box when clicked.

I have attached a video with a demo. Please note that I _**split my screen**_ 1/2 (so the issues might be only for smaller screen sizes).
Update: I made the window size smaller without splitting it directly, and it worked. It becomes unresponsive only when I use the windows split screen feature. 

[Video](https://github.com/twbs/bootstrap/assets/149315714/233973e6-2df9-4428-bbd6-707e87f67f11)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.0

**Comment by cwssrhryjlekejrhellehrjwh** [comment]
lolli
