### ISSUE TITLE
Add class for change hover color variants on a buttons and Links

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#39666]
it will great option. if, you will add class for change hover color variants on a buttons and Links. same as [Link Opacity Hover variants](https://getbootstrap.com/docs/5.3/utilities/link/#hover-variants).

Here, We are use `btn-secondary` & `link-secondary` and want to change it's buttons and links hover color to primary color in any particular section. So, have not option available with css class. 

So, I am requested you. it will great option. if, you will add something like class `btn-primary-hover` and `link-primary-hover`.

**Something like:** 

`<button type="button" class="btn btn-secondary btn-primary-hover">Secondary</button>`

`<p><a href="#" class="link-secondary link-primary-hover">Secondary link</a></p>`

**Comment by mdo** [comment]
No plans to add this.
