### ISSUE TITLE
`npm install` hangs on Windows 11, clean node install

### ISSUE THREAD

**Issue by ChristosMylonas** [twbs/bootstrap#39670]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`npm install` hangs and remains in console without apparent reason.
Steps to reproduce:
- Uninstall nodejs, npm.
- git clone bootstrap
- install nodejs version v20.11.0
- npm version is 10.2.4
- Windows version is  `Microsoft Windows [Version 10.0.22631.3085]`
- `npm install`
Installation starts and stops at:
```
[#########.........] - reify:fsevents: timing reifyNode:node_modules/@rollup/rollup-android-arm-eabi Completed in 189ms
```

### Reduced test cases

-

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.3.2

**Comment by mdo** [comment]
Perhaps an issue on that package then?
