### ISSUE TITLE
Website documentation. Code blocks and Apple trackpad scrolling issue

### ISSUE THREAD

**Issue by webtop** [twbs/bootstrap#39677]
Hey, All.

I have noticed that lately when I'm looking at the documentation for v5+ on my iMac, and I try to highlight a block of code in an example, using my Apple trackpad, as soon as I swipe the page scrolls all the way to the bottom.
This does not happen on the v4 documentation, just v5.

Not a show-stopper, just an annoyance and thought I'd mention it.

Thanks.

**Comment by julien-deramond** [comment]
Hey @webtop 
Thanks for reporting this issue. It's already been reported in #39605, you'll find more information there.
Closing this one
