### ISSUE TITLE
Scrolling long content code missing in the documentation of modal

### ISSUE THREAD

**Issue by shantovai024** [twbs/bootstrap#39687]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

![Screenshot_65](https://github.com/twbs/bootstrap/assets/56038258/cf806a84-201d-46bc-96bb-5ed92cf45f08)

The Scrolling long content effects works fine. But you forget to mention the code snippet in this section. As I am a developer I inspect the code and use it in my project.

You mention all the effects code snippets in your documentation except this. Hope you update your documentation as soon as possible.

### Motivation and context

If you add the code of the  Scrolling long content effect it will be helpful for others.

**Comment by julien-deramond** [comment]
Thanks for this suggestion of docs enhancement @shantovai024 
This use case is just to show that it works automatically, this is just a basic modal with a lot of content in it.
It would be just something like this:

```html
<!-- Normal modal with long content -->
<div class="modal-dialog">
   ...
</div>
```
Is it worth it? Would it be clearer?

**Comment by shantovai024** [comment]
Ok Thank You. After your replay I checked & observed that it works
automatically.

**Comment by julien-deramond** [comment]
I'm closing it. If someone has a strong opinion about it, I'll reopen the discussion :)
