### ISSUE TITLE
.table-striped not working in light mode

### ISSUE THREAD

**Issue by seanterry** [twbs/bootstrap#39696]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The zebra striping of the `.table-striped` class (at least to my eyes) is not appearing in light mode.

I checked my sanity and see the same thing on the official example: https://getbootstrap.com/docs/5.3/content/tables/#accented-tables

<img width="844" alt="Screenshot 2024-02-20 at 4 46 40 PM" src="https://github.com/twbs/bootstrap/assets/7458627/eaf35ac5-4f65-4472-974a-9da3f82b3c52">

Seems to be okay in dark mode.
<img width="844" alt="Screenshot 2024-02-20 at 4 46 48 PM" src="https://github.com/twbs/bootstrap/assets/7458627/b6a301e2-6d8b-4ab1-b839-c0e47280888e">

### Reduced test cases

```
<table class="table table-striped">
  <thead>
    <tr>
      <th>Header</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Item 1</td>
    </tr>
    <tr>
      <td>Item 2</td>
    </tr>
  </tbody>
</table>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.2

**Comment by jomarcardoso** [comment]
You need to calibrate your monitor. Decrease the contrast setting.

Or you can customize the zebra color in your project.

**Comment by seanterry** [comment]
@jomarcardoso Thanks. I feel like an idiot now 😆
