### ISSUE TITLE
Flex gap

### ISSUE THREAD

**Issue by SharkMachine** [twbs/bootstrap#39705]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Classes for setting Flex gap, for example:

- `flex-gap-3` - sets the gap to be the same as `mb-3`
- `flex-gap-4-2` - sets the vertical gap to be the same as `mb-4` and horizontal to be the same as `mb-2`

### Motivation and context

Flex gap is useful when using flex and supported by modern browsers: https://caniuse.com/flexbox-gap

**Comment by mdo** [comment]
`gap` can be used on flexbox parents. Not sure about that `4-2` syntax, but interesting idea!

**Comment by SharkMachine** [comment]
> `gap` can be used on flexbox parents. 

@mdo Can you enlighten me? The [documentation](https://getbootstrap.com/docs/5.3/utilities/flex/) doesn't mention gap.

**Comment by julien-deramond** [comment]
Gap documentation is around there: https://getbootstrap.com/docs/5.3/utilities/spacing/#gap

**Comment by SharkMachine** [comment]
Thanks. What about mentioning the gap documentation in flex documentation?
