### ISSUE TITLE
Padding left and right utilities not working as expected

### ISSUE THREAD

**Issue by manojdeevi** [twbs/bootstrap#39718]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Padding left and right utilities not working 
ex: pl-1,pr-2

### Reduced test cases

padding left and right shoule be available
I have tested px , py , pb , pt are working fine

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.0

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @manojdeevi 
However, this was done on purpose in Bootstrap 5 (see https://getbootstrap.com/docs/5.3/migration/#rtl).
