### ISSUE TITLE
input-group + <input type=color> doesn't use whole height

### ISSUE THREAD

**Issue by ChrisHSandN** [twbs/bootstrap#39737]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

An `input-group` combined with `<input type="color">` does not style correctly and leaves a gap between the bottom of the `input` compared to the height of the `input-group-text`.

![image](https://github.com/twbs/bootstrap/assets/13466620/86c19c6b-6b9d-42c2-a868-d3f5303e4f26)

### Reduced test cases

```html
<div class="input-group mb-3">
  <span class="input-group-text">text</span>
  <input type="text" class="form-control">
</div>

<div class="input-group mb-3">
  <span class="input-group-text">color</span>
  <input type="color" class="form-control">
</div>
```

Testcase: https://jsfiddle.net/chris_h/k4cdfw2e/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.3

**Comment by louismaximepiton** [comment]
Hey there,

I think you're not using it right here. The `<input type="color">` is missing the class `.form-control-color` as mentioned [here](https://getbootstrap.com/docs/5.3/forms/form-control/#color). 
So the following code should work fine:

```html
<div class="input-group mb-3">
  <span class="input-group-text">text</span>
  <input type="text" class="form-control">
</div>

<div class="input-group mb-3">
  <span class="input-group-text">color</span>
  <input type="color" class="form-control form-control-color">
</div>
```

I don't have any issue after that. Can you confirm ?

**Comment by ChrisHSandN** [comment]
Ah my bad, I hadn't spotted the `form-control-color` class. Closing as that resolves the issue.

Many thanks 👍

**Comment by HybridSolutions** [comment]
Sorry to open this again, but is this documented in recent documentation? Shouldn't an example of this be in the Forms > Input group section [https://getbootstrap.com/docs/5.3/forms/input-group/](https://getbootstrap.com/docs/5.3/forms/input-group/)
