### ISSUE TITLE
accent-color can reduce the style size of the current input check box, radio button, and slider.

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/bootstrap#39758]
https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

**Comment by julien-deramond** [comment]
Closing it, @ZhangChengLin please use the [right template for new features](https://github.com/twbs/bootstrap/issues/new?assignees=&labels=feature&projects=&template=feature_request.yml&title=Suggest+a+new+feature) by adding some description, motivation and context.
