### ISSUE TITLE
Can a react web app have both a Modal Component, and Off-canvas nav menu. When I use both strip and Import. the drop-down toggle in Off-canvas nav does not respond

### ISSUE THREAD

**Issue by PixelJunkie33** [twbs/bootstrap#39754]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A developer can not use the strip import for Modal Component and Import Bootstrap.bundle.min.js files in the same app. The functionality for the Off-canvas dropdown nav menu needs the import.

To render a Modal component the developer must in `<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>` into the HTML file.  

when using the Off-canvas nav, I insert `import "bootstrap/dist/js/bootstrap.bundle.min.js` at the top of the file. This import govens many things including this button:

```html
  <button
            type="button"
            className="btn-close text-reset"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
          ></button>
```

Are there any solutions? 

### Reduced test cases

N/a

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.0

**Comment by Codenuclei** [comment]
**_Same Name issue use different names_**





Please check if there are same function or ids or anything same because two files if they have same some function name or something same in their data they might give unwanted errors try changing the name of the id or class of your elements and try again.
