### ISSUE TITLE
Loading of an image is failed under status heading in README.md

### ISSUE THREAD

**Issue by Shekhar-Dangi** [twbs/bootstrap#39771]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

An image is not loaded due to violation of some policy in the README.md file of [webpage](https://github.com/twbs/bootstrap/tree/v4-dev)

### Reduced test cases

<img width="1710" alt="Screenshot 2024-03-10 at 11 24 22 PM" src="https://github.com/twbs/bootstrap/assets/76780858/b6aea5d2-df01-4558-b28d-144341736bfc">

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v4.5.2

**Comment by Shekhar-Dangi** [comment]
Can I work on this? I can change the link of image provided on the main branch

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @Shekhar-Dangi but our v4 has been deprecated since 2023-01-01, we don't make modifications to the `v4-dev` branch anymore.
