### ISSUE TITLE
Carousel returns incorrect (reversed) directions

### ISSUE THREAD

**Issue by timothee-dhenain-zenika** [twbs/bootstrap#39770]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Checking the Codepen I linked: 

- open the console
- navigate through the carousel
- the carousel returns incorrect directions (left when it should be right and the opposite)

### Reduced test cases

https://codepen.io/Tim-arts/pen/gOyrrEa

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3

**Comment by timothee-dhenain-zenika** [comment]
Hello @CyrilKrylatov , thank you for your feedback. It still feels a bit counter-intuitive as a 'right' click produces a 'left' value

**Comment by CyrilKrylatov** [comment]
> Hello @CyrilKrylatov , thank you for your feedback. Not looking at the documentation at first makes it counter-intuitive as a 'right' click produces a 'left' value

it's not a 'right' click but 'next' click, maybe like this it'll sounds less counter-intuitive. :)
