### ISSUE TITLE
System Default Select Box Design

### ISSUE THREAD

**Issue by ionurboz** [twbs/bootstrap#39796]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ]  Done

### Proposal

**System Default Select Box Design**
https://codepen.io/ionurboz/full/rNbjBKO

### Motivation and context

-

**Comment by julien-deramond** [comment]
Closing this issue as there's no description nor motivation and context for this new feature.
