### ISSUE TITLE
border-primary shows wrong color (lighter color)

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap#39860]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`border-primary` doesn't show the proper border color,  but a lighter color 

### Reduced test cases

border border-primary

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by coliff** [comment]
The border-primary utility class works as expected. It uses the variable `--bs-primary-rgb` which uses: `--bs-primary-rgb: 13, 110, 253;` which is the same color as `bg-primary` (https://getbootstrap.com/docs/5.3/customize/color/#theme-colors).

**Comment by julien-deramond** [comment]
As explained by @coliff (thanks for that), the border-primary utility works as expected. Closing this issue.
