### ISSUE TITLE
Active nav links with default style look inactive

### ISSUE THREAD

**Issue by willfaught** [twbs/bootstrap#39882]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Seen [here](https://getbootstrap.com/docs/5.3/components/navs-tabs/#base-nav), active nav links with no tab, pill, or underline style look the same as inactive ones:

<img width="345" alt="Screenshot 2024-04-08 at 11 41 39 PM" src="https://github.com/twbs/bootstrap/assets/63830/6fca1792-147a-407d-8154-1059b94b013b">

However, active nav links with tab, pill, and underline styles look different than inactive ones:

<p>
<img width="343" alt="Screenshot 2024-04-08 at 11 41 59 PM" src="https://github.com/twbs/bootstrap/assets/63830/e2c48090-0055-4b69-8c6a-1f42c2d20d36">
</p>

<p>
<img width="326" alt="Screenshot 2024-04-08 at 11 42 10 PM" src="https://github.com/twbs/bootstrap/assets/63830/c207102d-dd07-4895-973e-b79ab75b5f3b">
</p>

<p>
<img width="269" alt="Screenshot 2024-04-08 at 11 42 21 PM" src="https://github.com/twbs/bootstrap/assets/63830/806bc3ae-6f34-4268-bfba-3a58888e80d9">
</p>

It would be useful if the unstyled active nav links looked different than inactive ones, in a similar way. Perhaps a dark font color for light mode, and a light font color for dark mode, similar to the tab and underline styles? And a bold font weight, like with the underline style?

Also, looking at these screenshots now, it's strange to me that with the underline style, the links are closer together. Could the spacing for that style be made consistent with that of the other styles? Happy to make a separate issue if needed.

### Motivation and context

Consistency with other nav styles. Clarity of which nav link is active.

**Comment by mdo** [comment]
There's no active on the base `.nav` on purpose. See https://getbootstrap.com/docs/5.3/components/navs-tabs/#base-nav.

> Also, looking at these screenshots now, it's strange to me that with the underline style, the links are closer together. Could the spacing for that style be made consistent with that of the other styles? Happy to make a separate issue if needed.

I feel like the underline style is space nicely, but you're more than welcome to put up a PR that changes it to what your more comfortable with and we can try it out!

**Comment by willfaught** [comment]
But there is on the

```html
<nav class="nav">
  <a class="nav-link active" aria-current="page" href="#">Active</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link disabled" aria-disabled="true">Disabled</a>
</nav>
```

example, and it has the same look.

>I feel like the underline style is space nicely, but you're more than welcome to put up a PR that changes it to what your more comfortable with and we can try it out!

Wouldn't we need this issue to be open to justify the PR?
