### ISSUE TITLE
System UI font not used on WebKit

### ISSUE THREAD

**Issue by qvignaud** [twbs/bootstrap#39905]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On WebKit the system font is not called by Bootstrap, making some apps using Bootstrap and WebKit looking “weird” and not well-integrated on Linux systems, such as projects built with Tauri. 

While this is mostly due to WebKit not supporting `system-ui` value yet (https://bugs.webkit.org/show_bug.cgi?id=178624), Bootstrap should probably use `-webkit-system-ui` within the default `$font-family-sans-serif` list.

As such, here are examples on Linux Mint with WebKitGTK 2.38.6.

Not-integrated display:
![without_system_ui](https://github.com/twbs/bootstrap/assets/4092937/98d1550e-9f83-441c-a7a1-f87ee5c79e3b)
Well-integrated display:
![with_system_ui](https://github.com/twbs/bootstrap/assets/4092937/ddfc2018-acc1-4ef1-b128-ced8a80192cb)

Please let me know if I should open a PR as the change seems simple, but may impact many things that I don't even have knowledge of.

### Reduced test cases

_N/A because not reproducible that way_

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
This was discussed years ago with the very different Linux default font causing unexpected and inconsistent rendering issues. https://fonts.google.com/specimen/Ubuntu is the font I believe, and it's just so different looking. There are some old threads somewhere here that I can't find right now, but changes were made to deliberately _not_ support that font.

**Comment by qvignaud** [comment]
While I don't feel competent to argue about UI support of Ubuntu (or any other) font, I don't understand the relationship with deliberately not supporting `-webkit-system-ui` value.

1. Actually, pages using “vanilla” Bootstrap on Linux systems will use the system font on Firefox/Chrom(e|ium), but not on raw WebKit (that is used by local web-rendered apps).
2. Consistent behavior between renderers on same platform seems to be the good thing to do.
3. Considering default font is Ubuntu on many Linux distributions, Bootstrap currently render with that font on web browsers anyway for consequent amount of users.

These points tends for me to consider adding `-webkit-system-ui` as fallback for `system-ui`, even if it refers to a font that not fit well for Bootstrap, because this is the most consistent and user-compliant option.

Also, pure question of taste, I don't see what is wrong with Bootstrap + Ubuntu Font, the render looks quite good to my eyes :)
