### ISSUE TITLE
README: `img.badgesize.io` badges are not rendered

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#39954]
### Description

In our README, there is a rendering issue with some badges present in the [Status section](https://github.com/twbs/bootstrap/?tab=readme-ov-file#status).

![Screenshot 2024-05-02 at 19 03 06](https://github.com/twbs/bootstrap/assets/17381666/c2cc62b8-fe8d-49d4-a317-a53a2493f575)

These badges are all using https://img.badgesize.io where there is an open issue apparently linked to an expired registry: https://github.com/ngryman/badge-size/issues/113

Several options:
* Let these badges as they are now, and wait for an upstream fix
* Switch to another badge provider
* Drop these badges, and re-include them when the upstream issue is fixed

**Comment by itsmesuraj20** [comment]
I tried to fix it statically by brute-forcing it. I simply created another badge with the same link, but I couldn't understand the badge design. I'm unable to match the design of the badge.

Could you please provide the badge design model or style query for it?

Here's what I have tried to build 
![image](https://github.com/twbs/bootstrap/assets/109140592/cf60ec59-9098-484b-9dc1-5bb46e0b2bc9)

**Comment by itsmesuraj20** [comment]
Please do assign me for this issue

**Comment by julien-deramond** [comment]
It's back to normal thanks to https://github.com/ngryman/badge-size/issues/113#issuecomment-2126523910. I'll reopen this issue if the issue comes back.
