### ISSUE TITLE
CDN Downtime

### ISSUE THREAD

**Issue by Christelle97** [twbs/bootstrap#39952]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello, I'm using the CDN to serve bootstrap files, and I guess there's a downtime, because all my websites are not displaying right.

### Reduced test cases

these are in the <head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

https://www.chateaudeferrieres.com
https://www.chateaudeferrieres.com/evenements/
https://www.lechai-restaurant.com/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Hello @Christelle97 
This is a temporary jsdelivr issue referenced in https://github.com/twbs/bootstrap/issues/39947.
https://github.com/twbs/bootstrap/issues/39947#issuecomment-2089721026 provides a temp solution for Bootstrap users.
Closing this issue as duplicate.
