### ISSUE TITLE
bootstrap not working

### ISSUE THREAD

**Issue by josmbolomnyoi** [twbs/bootstrap#39953]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://site.flexi-personnel.com/index.html
bootstrap not working... it was working yesterday and stopped

### Reduced test cases

https://site.flexi-personnel.com/index.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v.51

**Comment by julien-deramond** [comment]
Hello @josmbolomnyoi 
This is as temporary jsdelivr issue referenced in https://github.com/twbs/bootstrap/issues/39947.
https://github.com/twbs/bootstrap/issues/39947#issuecomment-2089721026 provides a temp solution for Bootstrap users.
Closing this issue as duplicate.
