### ISSUE TITLE
Splitter component - Suggest a new feature

### ISSUE THREAD

**Issue by Helder-Machava** [twbs/bootstrap#39962]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

# Splitter component

Hello *Bootstrapp team*, i'd like to ask for `splitter component - feature ` for the next version of bootstrap

### Motivation and context

> It allows users to resize panes according to their preferences

**Comment by mdo** [comment]
We'll pass on this, thanks.
