### ISSUE TITLE
Base Bootstrap on TailwindCSS

### ISSUE THREAD

**Issue by martinszeltins** [twbs/bootstrap#39975]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently it is very difficult when we need to override Bootstrap components or create new ones. It requires writing plain CSS files. Bootstrap already has great utility classes, it would make more sense to base Bootstrap on Tailwind. It would make it much easier to override styles and create new components.

### Motivation and context

TailwindCSS has become the de facto CSS library in modern frontend developement that makes it easy to write maintainable CSS.

**Comment by julien-deramond** [comment]
Thanks for creating this feature request, but we have no plans to move in this direction.

>  it would make more sense to base Bootstrap on Tailwind.

Both approaches are for now different, so it wouldn't make sense to base Bootstrap on Tailwind.

> Currently it is very difficult when we need to override Bootstrap components or create new ones.

We plan to improve that in v6 with a better customization.
