### ISSUE TITLE
Column width auto is not always spaced evenly

### ISSUE THREAD

**Issue by 2dareis2do** [twbs/bootstrap#39979]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using column width auto it should resize to fill the available space. 

However, say I have three columns that all use `.col` class. they do not always space them selves to fill the available screen space

e.g. we have 

```
.row > * {
flex-shrink: 0;
width: 100%;
max-width: 100%;
padding-right: calc(var(--bssk-gutter-x) * .5);
padding-left: calc(var(--bssk-gutter-x) * .5);
margin-top: var(--bssk-gutter-y);
}
```

From what I can tell the width property is simply not required. In fact this seems to be the source of the problems. i.e. the width does not adjust accordingly.

If I override this and set it explicitly to 0, the flex box seems to behave and respond correctly.

Please see attached screenshots

<img width="1491" alt="Screenshot 2024-05-13 at 15 19 53" src="https://github.com/twbs/bootstrap/assets/1718370/aaa89f8d-cba9-4fc4-83ef-83e6e955b1d8">

<img width="1369" alt="Screenshot 2024-05-13 at 15 21 34" src="https://github.com/twbs/bootstrap/assets/1718370/9d10d7e8-e15d-4864-b1ae-d5652f5258b6">

<img width="1437" alt="Screenshot 2024-05-13 at 15 28 32" src="https://github.com/twbs/bootstrap/assets/1718370/3feba87d-9889-4cc9-90da-46ed9894ad90">

<img width="1549" alt="Screenshot 2024-05-13 at 15 33 28" src="https://github.com/twbs/bootstrap/assets/1718370/cf967418-5309-4135-b2fe-289fdea36fd4">

<img width="1456" alt="Screenshot 2024-05-13 at 15 33 54" src="https://github.com/twbs/bootstrap/assets/1718370/af376840-14bf-4755-ac89-a9ffd7bd59e3">

### Reduced test cases

```
.row > * {
width: 100%;
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.3.3

**Comment by 2dareis2do** [comment]
Actually the above fix needs to be more specific e.g.

```
.row > .col {
width: 0;
}
```

**Comment by 2dareis2do** [comment]
Thanks for your quick response. 

Ok I have tried to recreate the issue here

https://codepen.io/twodareis2do/pen/xxNGKPd

However I can't seem to replicate the same issue as on my local.

I  have tried switching JavaScript off in my browser, and that seems to rectify the problem as well!

Will try and investigate further as it seems likely that something else is causing this behaviour (i.e. not bs)

**Comment by 2dareis2do** [comment]
Ok, I was trying to reproduce the wrong page!

I have updated the demo (same link as per my previous post)

There should be three columns viewable and it is showing only two on page load.

If you uncomment the last line of the css, the 3 columns are alligned correctly.

**Comment by mdo** [comment]
Your example is not a reduced test case—it's a rather complex page full of extra HTML. Closing until we get a more defined test case we can isolate to Bootstrap's components.
