### ISSUE TITLE
In .btn class font-family is missing in bootstrap v5.3.3

### ISSUE THREAD

**Issue by orangzaibKhan** [twbs/bootstrap#39981]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In .btn class font-family is missing in bootstrap v5.3.3.

### Reduced test cases

In .btn class font-family is missing in bootstrap v5.3.3.

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.3.3

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @orangzaibKhan 
`font-family` is defined in v5.3.3 for `.btn`s:

https://github.com/twbs/bootstrap/blob/72d3b6efc4b92e83a4abca6f5bc0cd7e6fd25931/dist/css/bootstrap.css#L2993

`--bs-btn-font-family` being voluntarily empty by default:

https://github.com/twbs/bootstrap/blob/72d3b6efc4b92e83a4abca6f5bc0cd7e6fd25931/dist/css/bootstrap.css#L2978

So, I'm closing this issue
