### ISSUE TITLE
d-sm-none not working in ul

### ISSUE THREAD

**Issue by Maryamdeveloper** [twbs/bootstrap#39986]
_Note: edited by maintainer for using backticks for the HTML code_

### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

d-sm-none not working inside the ul or even if it is put on the ul itself I have tried it in an empty HTML still no changes
![image](https://github.com/twbs/bootstrap/assets/74108363/f91b0301-fab3-4a1c-895d-74bd466f8b3e)

### Reduced test cases

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <h1>Hello, world!</h1>
    <!-- 1st try -->
    <ul class="d-md-block d-sm-none">
      <li>Item 1</li>
      <li>Item 2</li>
      <li>Item 3</li>
    </ul>
    <!-- 2nd -->
    <ul>
      <li class="d-md-block d-sm-none">Item 4</li>
    </ul>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
```

### What operating system(s) are you seeing the problem on?

Windows, Android, iOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.3.0

**Comment by Maryamdeveloper** [comment]
![image](https://github.com/twbs/bootstrap/assets/74108363/80ad868f-6dd0-496b-a523-badaf8bb3180)

**Comment by julien-deramond** [comment]
Hello @Maryamdeveloper 
Tried quickly your code in a CodePen, it seems to work as expected
* Before 576px, nothing is set, so the list is displayed
* Between 576px and 768px, `.d-sm-none` (so `display: none`) is applied, so the list is not displayed
* After 768px, `.d-sm-block` (so `display: block`) is applied, so the list is displayed
