### ISSUE TITLE
Could you integrate popper.min.js as well? Right now popper is not available as a package for composer. 

### ISSUE THREAD

**Issue by steamonimo** [twbs/bootstrap#40417]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

For the time being twbs/bootstrap depends on popper.min.js (perhaps floating-ui will replace that in the future). Could you integrate this lib into your composer package for distribution in dist?

### Motivation and context

This package is only available via npm but not via composer. At my company we try to minimize the tool stack and node is not available. The popper library is the only component in our php project we can not maintain with composer update.

**Comment by carlosmintfan** [comment]
Popper should be included in bootstrap.bundle(.min).js

**Comment by steamonimo** [comment]
> Popper should be included in dist/js/bootstrap.bundle(.min).js

Thanks for pointing that out. Goot to know that bootstrap.bundle.js contains popper and bootstrap.min.js is keeping popper separate. I will close this request...

**Comment by carlosmintfan** [comment]
Just to clarify, as you wrote bootstrap.bundle.js and bootstrap.min.js in your answer: bootstrap.js and bootstrap.min.js keep popper separate, bootstrap.bundle.js AND bootstrap.bundle.**min**.js include popper.
