### ISSUE TITLE
Navs and Tabs - Tabs doesn't work correctly when nav-links are anchors <a>

### ISSUE THREAD

**Issue by Jedikops** [twbs/bootstrap#40438]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Please, verify whether achors on nav-tabs work correctly.
I've checked with button elements and that works fine, but when i use anchors - tabs doesn't switch.
The problem can be seen on bootstrap's pages as well.

https://getbootstrap.com/docs/5.0/components/navs-tabs/

Try switching tabs where nav-links are made of anchors.

### Reduced test cases

https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs

1. Open Dev tools - find elements
2. Switch tabs under "Tabs" section
3. Notice 'active' class doesn't switch.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### What version of Bootstrap are you using?

Found in 5.3.3, but 5.0.0 is affected too.

**Comment by carlosmintfan** [comment]
Please reopen this if you closed it accidentally. 😃
