### ISSUE TITLE
Dark Mode HTML tag Attribute is incorrect in the DOCUMENTATION and elsewhere on the web for Bootstrap 5.3.0+

### ISSUE THREAD

**Issue by k-kycia** [twbs/bootstrap#40437]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The ``<html lang="en" data-bs-theme="dark">`` is incorrect per the Javascript Source Code which uses ``<html lang="en" data-bs-theme-value="dark">`` to set the DEFAULT page them to the Dark Mode.  I've tested it and it works!  I also checked the TOGGLE Javascript code which worked when changing the default Theme from Light to Dark and Back.  So I went and searched through that code to find the CORRECT attribute:  ``data-bs-theme-value``.  The DOCUMENTATION is WRONG!

### Reduced test cases

 ``<html lang="en" data-bs-theme-value="dark">``  To default the theme to "Dark" on the webpage.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
Hello @k-kycia 
Thanks for reporting an issue here.

> The DOCUMENTATION is WRONG!

It's not. Maybe there's a misunderstanding about how it works.
* `data-bs-theme-value` is only used by our `color-modes.js` to handle the rendering of the buttons, not to handle the color modes (dark mode)
* `data-bs-theme` is the one to use. You can see in our own documentation that this is the one used near the `<html>` tag. More info at https://getbootstrap.com/docs/5.3/customize/color-modes/#enable-dark-mode.
