### ISSUE TITLE
Wrong border radius first element in `btn-group-vertical` is a dropdown

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#40487]
### Describe the issue

With horizontal button groups, the first button can be a dropdown and the border radius looks like expected:

> <img width="1063" alt="image" src="https://github.com/twbs/bootstrap/assets/111561/c621d162-3ade-480c-ab1c-6e661c4c0669">

With vertial button groups, the border radius breaks when the first item of the list is a dropdown:

> <img width="1056" alt="image" src="https://github.com/twbs/bootstrap/assets/111561/5acd18c9-7540-49ab-a704-92fe6524a3dd">

### Reduced test cases

https://stackblitz.com/edit/1vpwjr?file=index.html

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

https://getbootstrap.com/docs/5.2/components/button-group/

**Comment by PRERAKAGARWAL28** [comment]
I have resolved this issue
https://stackblitz.com/edit/jzsfzg?file=index.html
