### ISSUE TITLE
Unable to focus the input in the popup, and the popup closes immediately when placed inside the Offcanvas

### ISSUE THREAD

**Issue by UdhayaKumarDuraisamy** [twbs/bootstrap#40495]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have a custom dropdown that I rendered inside the Bootstrap Offcanvas. The dropdown's popup, which is rendered as a child to the body element outside of the Offcanvas, contains an input rendered within the popup element. When trying to open the popup and focus on the input, it immediately closes the popup.

Upon further investigation, it was observed that when the Offcanvas is opened, it enforces focus on itself if an element outside of the Offcanvas gains focus.

When searching on the web, I found that the same issue occurred with Bootstrap modal, and below I have shared it for reference.
https://github.com/twbs/bootstrap/issues/19971
https://github.com/sweetalert2/sweetalert2/issues/374

### Reduced test cases

I'm using "https://getbootstrap.com/docs/5.3/components/offcanvas/".

![337](https://github.com/twbs/bootstrap/assets/98140917/d32d6398-cb94-481e-acb8-264ce2666996)

[BlazorApp1-main.zip](https://github.com/twbs/bootstrap/files/15453128/BlazorApp1-main.zip)

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3

**Comment by julien-deramond** [comment]
Hi @UdhayaKumarDuraisamy 
Thanks for reporting an issue in this repository.
I can see that you provided a reduced test case in a .zip file. Could you please try to upload its content in [CodePen](https://codepen.io/), [StackBlitz](https://stackblitz.com/) or any other online tool? For security reasons, won't open the .zip file on my machine :)

**Comment by xebamart** [comment]
Hello,

GitHub link attached.

https://github.com/xebamart/BlazorApp1

**Comment by xebamart** [comment]
> Hola@UdhayaKumarDuraisamy Gracias por informar un problema en este repositorio. Puedo ver que proporcionó un caso de prueba reducido en un archivo .zip. ¿Podrías intentar cargar su contenido en [CodePen](https://codepen.io/) , [StackBlitz](https://stackblitz.com/) o cualquier otra herramienta en línea? Por razones de seguridad, no abro el archivo .zip en mi máquina :)

Hello, I have sent you the repository with the code that you mentioned when opening the incident. I have had the problem and I mentioned it to Syncfusion to see if the problem was with their component and they have opened the case. As you can see, I have left you the repository with the complete code so that you can reproduce the case.

Thank you.

**Comment by julien-deramond** [comment]
Thanks for your contribution, @xebamart. I reviewed the repository, but couldn't find instructions on how to run the project. Given our current workload with numerous PRs and issues, we can't handle this added complexity at the moment.

To streamline the process, could you please provide a live, reproducible example? This will help us understand and address the issue more efficiently. Platforms like CodePen or StackBlitz would be ideal.

If you can set up a working example there, I'll be happy to reopen the issue. Thanks for your understanding!
