### ISSUE TITLE
can't open right dropdown when DOM has more

### ISSUE THREAD

**Issue by laczka** [twbs/bootstrap#40512]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, 
on my site has two dropdown beside each other.
the second one i want open programmatically, but i cant, when i try, the first one is opening.

### Reduced test cases

https://codepen.io/Laczka-S-ndor-G-bor/pen/YzbZyWo

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by ac-mmi** [comment]
dropdown("toggle") method is invoked for dropdown button not the `<div id="second"></div>`
