### ISSUE TITLE
Order of bootstrap grid system wrong

### ISSUE THREAD

**Issue by RubeMeuleman** [twbs/bootstrap#40537]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I seem to have found a problem with bootstrap. I'm using v5.3.0 via node modules structure (rather than the cdn) and when using these classes in this order:
```<p class="col-12 col-sm-11 col-md-10 col-lg-9 col-xl-8 col-xxl-7">test</p>```
col-xl-* always seem to get skipped. (basicly you cant' use xl, cause it get's overridden by the rest.)

I looked into the file structure and it seems that bootstrap is importing it via this way:
- xl
- sm
- md
- lg
- xxl

I basicly can't use xl, since it get's overridden by the rest except for col-12

### Reduced test cases

/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

^v5.3.0

**Comment by Arifa105** [comment]
using a grid layout directly on <p> is not semantically appropriate. however applying so many classes might not achieve responsive behavior, usually you have to specify the few break points.

# Bootstrap Grid
Bootstrap gird means to create layout on the basis of row and column.
so your output should be like this

`<div class="container">
 <div class="row">
 <div class="col-12 col-sm-11 col-md-10 col-lg-9 col-xl-8 col-xxl-7">
   <p>Test</p>
</div>
</div>
</div>
 `

**Comment by mdo** [comment]
You'll need to check your compiling tools so that they match our own. In our compiled CSS, the order is correct. This can be done with Clean CSS, CSS Nano, or similar. See https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.css for example.
