### ISSUE TITLE
Carousel swiping does not work on Desktop browser

### ISSUE THREAD

**Issue by wutipong** [twbs/bootstrap#40531]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Basically `Swipe.isSupported()` returns `false` on the both Chrome (125.0.6422.141 (Official Build) (64-bit) ) and Firefox (126.0.1 (64-bit), with `MOZ_USE_XINPUT2=1` environment variable). This is tested on Lenovo Yoga 520 on Manjaro Linux (up-to-date). Because of this, touchevents are not registered and thus swiping the components won't do anything.

`Swipe.isSupported` is currently written as below

```js
static isSupported() {
      return 'ontouchstart' in document.documentElement || navigator.maxTouchPoints > 0;
}
```

Now if I change the code to make it always return `true`, swiping will work on both Chrome and Firefox.

### Reduced test cases

Plain Carousel example, with Boostrap 5.3.3 -- swipe does not work : https://codepen.io/wutipong-the-bashful/pen/YzbVRGR

The same example with modified Bootstrap 5.3.3 -- swipe works: https://codepen.io/wutipong-the-bashful/pen/ExzmOmQ

Edit: basically I changed `Switpe.isSupported()` to 

```js
static isSupported() {
      return true;
}
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.3

**Comment by wutipong** [comment]
To add more context. On Firefox, you can make the `Swipe.isSupported()` returns `true` by changing the browser flag `dom.w3c_touch_events.legacy_apis.enabled` to `true` (it's `false` by default.). I can't find the way to do the same with Chrome though.

**Comment by wutipong** [comment]
IMHO, I don't think checking if swipe is supported is really necessary. I mean, if the device does not support the touch events, the browser wouldn't trigger such events anyway. 

I haven't really looked into the case where touch events are no supported at all, but from a few quick tests there are not stuffs like Exceptions in the console.

**Comment by wutipong** [comment]
Update: I've just tried on Windows (using Wacom Cintiq Pro13). The current Swipe works. 

Digging a bit deeper, I find that on Windows, `navigator.maxTouchPoints` is 10 (as oppose to the Linux machine I tried, which the said value is 0). Guess I have to ask the browser instead (*sigh*).

**Comment by sanjeevmurmu** [comment]
did you find any solution to do this

**Comment by wutipong** [comment]
After more investigation on my end, it seems like Chrome on Linux behave differently from Windows regarding `navigator.maxTouchPoints`. I think it's should be considerred as a browser issue rather than JS issue. 

I'm closing this one now as a non-issue. Maybe I will ask about this one Chromium project instead. 

Again personally I don't really think testing for touchscreen is necessary before adding listeners to touchevents. It wouldn't kill performance all that much.
