### ISSUE TITLE
Dropdown is not working

### ISSUE THREAD

**Issue by Ravula-Swetha** [twbs/bootstrap#40538]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The dropdown isn't working, it's not even working on the website. Also the website dropdowns aren't working like changing mode (dark and light mode) and version change dropdown.
I hope this issue can be resolved quickly, thank you.

### Reduced test cases

https://codepen.io/codepen-io-swetha/pen/OJYjjKm

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3

**Comment by julien-deramond** [comment]
Hello @Ravula-Swetha 

> The dropdown isn't working, it's not even working on the website.

What do you mean by "it's not working"? When you click on it, the menu is not displayed?

If that's the case, you might try [alternative CDNs](https://getbootstrap.com/docs/5.3/getting-started/download/#alternative-cdns) as `jsdelivr` can be blocked in some countries or specific environments.

**Comment by Ravula-Swetha** [comment]
Yes, when I click on it, the menu isn't displayed. Thank you, I will try
using the alternative CDNs.
But why is it that the dropdowns aren't working on the bootstrap website
for me?

**Comment by julien-deramond** [comment]
> But why is it that the dropdowns aren't working on the bootstrap website for me?

I don't know. Could you check if there are some errors in your console or anywhere else?

**Comment by mdo** [comment]
Seems like you may have JS disabled or some other browser extension interfering? Works fine for us.
