### ISSUE TITLE
Multiple select doesn't seem to be working

### ISSUE THREAD

**Issue by PeterH2N** [twbs/bootstrap#40542]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The multiple attribute for select froms doesn't seem to be working on my 2020 M1 MacBook, even on your own website. The screenshot is from safari, but it looks the same on chrome. It does work on mobile
[From this page:](https://getbootstrap.com/docs/5.3/forms/select/)
<img width="838" alt="Screenshot 2024-06-10 at 14 39 52" src="https://github.com/twbs/bootstrap/assets/59964273/bf0e54b1-e3b7-4259-919a-4a40729d7e5b">

### Reduced test cases

doesn't work on your website

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v5.3.3

**Comment by julien-deramond** [comment]
Hello @PeterH2N 

> The multiple attribute for select froms doesn't seem to be working on my 2020 M1 MacBook, even on your own website.

What do you mean by "not working"?

**Comment by PeterH2N** [comment]
Sorry, I'll specify.
It doesn't open as a drop down menu, but displays the entire list by
default. It also isn't possible to select multiple options

**Comment by jipexu** [comment]
yes ! not working
it's seems to work only if you change the select class form-select by form-control  ?

**Comment by julien-deramond** [comment]
> It doesn't open as a drop down menu, but displays the entire list by default. It also isn't possible to select multiple options

This "multiple" variant is not specific to Bootstrap. This is the default behavior of browsers that you can find described in https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple for instance.

> When `multiple` is specified, most browsers will show a scrolling list box instead of a single line dropdown.

In https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#selecting_multiple_options, you'll also have some details about the different ways to select multiple options in a `<select>` element.

**Comment by PeterH2N** [comment]
Thank you so much, I'll check it out!
