### ISSUE TITLE
Search Bar Not Displaying and Screen Freezing on Double Click on Small Phone Devices

### ISSUE THREAD

**Issue by DevGajjar28** [twbs/bootstrap#40555]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Search Bar Not Displaying on Second Use:**

Initially, the search bar works as expected and displays the search input.
Upon attempting to use the search bar a second time, the search bar does not appear even though typing and searching still function in the background.

**Screen Freeze on Double Click:**

If the search icon is double-clicked, the entire screen freezes . We have to click back to come to normal state.

**Steps to Reproduce:**

On a small phone device, click on the search icon.

1. Enter a search term and observe the search bar displaying correctly.
2. Perform a search.
3. Click on the search icon again.
4. Notice that the search bar does not display, although typing and searching still occur.
5. Double click the search icon.
6. Observe that the screen freezes

**Expected Behavior:**

The search bar should display each time it is clicked.
The screen should not freeze upon double-clicking the search icon.

https://github.com/twbs/bootstrap/assets/145287513/eae214f7-5da6-4ec8-b8ce-737d5c4a8e54
https://github.com/twbs/bootstrap/assets/145287513/36eedc8c-34ec-466e-8592-34b5a4587907

### Reduced test cases

https://codepen.io/2107-Dev-Gajjar/pen/QWROmzR

### What operating system(s) are you seeing the problem on?

Android

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

https://getbootstrap.com/

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @DevGajjar28 
I can confirm the issue on Chrome and Microsoft Edge, while it works well on Firefox.

**Comment by niyasrad** [comment]
This issue is fixed with the PR #39739, and issue #39665

I've checked the application locally, and addition of the `position: fixed` over `.DocSearch-Container` class seemed to have fixed it. Removing that particular property causes the issue again.

**Comment by julien-deramond** [comment]
Thanks, @niyasrad 
You're right, I forgot we already fixed that :)
The fix can be seen at https://twbs-bootstrap.netlify.app/ (deployment of the _main_ branch), and will be embedded in the next release.
