### ISSUE TITLE
Please refund me for Bootstrap Theme

### ISSUE THREAD

**Issue by onlineoj** [twbs/bootstrap#40554]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Dear Bootstrap Team,

I have been attempting to contact the creator of the Bootstrap Theme and the Bootstrap Marketplace, including through themes@getbootstrap.com and their online form, without success. As a dissatisfied customer, this is my last resort to reach out to you.

My concerns include the lack of documentation, no response for technical support, and various issues with the code in the theme. Therefore, I kindly request a refund for Order #154715.

Thank you for your understanding.

Sincerely,

Onlineoj on GitHub

### Motivation and context

I kindly request a refund for Order #154715.

**Comment by mdo** [comment]
Hey there, super sorry to hear about the poor experience, but this isn't the place for Themes support—none of the maintainers here have access to Themes or the billing/order information of them.
