### ISSUE TITLE
const myModal = document.getElementById('myModal') doesn't work

### ISSUE THREAD

**Issue by wei886-tw** [twbs/bootstrap#40613]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm using Vue3 "^3.4.21" and "bootstrap": "^5.3.3", and I'm using `const myModal = document.getElementById('myModal')`  on mounted, but chrome devtool shows `[Vue warn]: Unhandled error during execution of native event handler`
![image](https://github.com/twbs/bootstrap/assets/74435691/1a17375d-dc06-4c86-a77f-d5ad54e64c37)

### Reduced test cases

I used 
```js
const myModal = document.getElementById('myModal')
const myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', () => {
  myInput.focus()
})
```

but doesn't work

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3

---

_Note: edited by maintainer for correct Markdown syntax_

**Comment by Hichem-elAbassi** [comment]
Can you try catch it just to see ?

**Comment by wei886-tw** [comment]
I use` import Modal from 'bootstrap/js/dist/modal'; `  solve the bug
