### ISSUE TITLE
Deprecation notices with latest Dart Sass 1.77.7

### ISSUE THREAD

**Issue by ptdev** [twbs/bootstrap#40622]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

We've just updated a project to the latest Dart Sass 1.77.7 and we are now receiving multiple deprecation warnings like these:

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules/bootstrap/scss/_reboot.scss
503 │     font-weight: $legend-font-weight;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules/bootstrap/scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    node_modules/bootstrap/scss/_reboot.scss 503:3  @import
    app/assets/css/bs.scss 97:9                     root stylesheet

```

The above is only one sample, but we get many more while building the project.

This is apparently a change on this latest version of Dart SASS to make it match with some CSS changes as [described here](https://sass-lang.com/documentation/breaking-changes/mixed-decls/#deprecating-the-old-way).

### Reduced test cases

We get this issue when using our own sass file to personalize our bootstrap deployment as [instructed on your own documentation](https://getbootstrap.com/docs/5.3/customize/sass/)

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @ptdev 
It has been reported almost at the same time in https://github.com/twbs/bootstrap/issues/40621
Closing this one as a duplicate
