### ISSUE TITLE
Bootstrap 5.3 - fixed-top navbar versus dark themeProvide a general summary of the issue

### ISSUE THREAD

**Issue by ozaarm** [twbs/bootstrap#40625]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I think there is an incompatibility between fixed-top navigation bar and dark and light themes. fixed-top seems to requires bg-light or bg-white or any bg- but when adding data-bs-theme="dark" and toggling to "dark" mode, the background stays light.

Code to store the theme : 

// JavaScript function to store theme in localStorage
function storeTheme(theme) {
  document.documentElement.setAttribute('data-bs-theme', theme);
  localStorage.setItem('theme', theme);
}

// Check for saved theme on page load
window.onload = function() {
  const theme = localStorage.getItem('theme') || 'light';
  storeTheme(theme);
}

A toggler allows for the switch. 

Sample code with theme ON : 
< nav class="navbar navbar-expand-lg fixed-top border-bottom border-2 mb-3" data-bs-theme="dark" >

When implemented, the content from the rest of the page flows visibly under the top navbar when theme is dark (or light). 
See here : https://codepen.io/ozaarm/pen/xxobMOJ 

Before implementing data-bs-theme="dark" my code worked as expected (top navbar was light and fixed) this way : 
 < nav class="navbar navbar-expand-lg bg-light fixed-top border-bottom border-2 mb-3" >

Now with data-bs-theme="dark" ON, when I toggle between light and dark, the top navbar stays light because of bg-light.  

I wonder if : 
1. I made a mistake in my implementation
2. I should built some JS workaround 
Thanks
PM

### Reduced test cases

Here is visualization of the issue where fixed-top does not work without bg-light/white and fixed-top + bg-light are not compatible with data-bs-theme="light" (or "dark")

https://codepen.io/ozaarm/pen/xxobMOJ 

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment]
Thanks for reporting an issue, @ozaarm.

You're using `.bg-light` for the navbar. If you go to [Bootstrap's documentation on background color utilities](https://getbootstrap.com/docs/5.3/utilities/background/#background-color) and check the rendering of `.bg-light` in both light and dark modes, you'll notice that the color remains the same. This behavior is intentional.

If you want the color to change, you could use `.bg-body`, for example.

**Comment by ozaarm** [comment]
Wow, that fixed it instantly !

I hadn't read about that bg-body and its behaviour before.

Thank you Julien

P
