### ISSUE TITLE
Regarding Border - start and end, not working!

### ISSUE THREAD

**Issue by RohanPawar1TR** [twbs/bootstrap#40629]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

<img width="483" alt="image" src="https://github.com/user-attachments/assets/2cd201ad-3a1a-49d6-8c51-1eb2f02d06de">

the docs of bootstrap v5 needs to get updated regarding border as the classed mentioned for border-start and border-end doesn't get applied, instead border-left and border-right works

### Reduced test cases

<span class="border-end"></span> 

<span class="border-start"></span>

fix is:
```
<span class="border-right"></span> 

<span class="border-left"></span>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @RohanPawar1TR 
However, border are well applied, even in your screenshot. They are light gray, but they are displayed.
Zoomed screenshot from https://getbootstrap.com/docs/5.3/utilities/borders/:
<img width="972" alt="Screenshot 2024-07-12 at 11 32 17" src="https://github.com/user-attachments/assets/2a6d9800-38fb-4cde-b6c7-4c9100fe4242">

`.border-left` and `.border-right` don't exist anymore in Bootstrap v5 (they were there in v4); see https://getbootstrap.com/docs/5.3/migration/#utilities-3
