### ISSUE TITLE
Hmm @mdo, my last comment seems to have been that snarky it filled out your brain so you couldn't think of anything else and it made you miss the point :) :) :)

### ISSUE THREAD

**Issue by carlosmintfan** [twbs/bootstrap#40665]
Hmm @mdo, my last comment seems to have been that snarky it filled out your brain so you couldn't think of anything else and it made you miss the point :) :) :) 
Cause the original (still existing) problem is that **it is not clear what the license for the bootstrap examples css is**, as it doesn't contain a license header.

_Ursprünglich gepostet von @carlosmintfan in https://github.com/twbs/bootstrap/issues/40631#issuecomment-2249315474_

**Comment by mdo** [comment]
One issue will suffice.
