### ISSUE TITLE
Dark-mode with <nav> element not working

### ISSUE THREAD

**Issue by gipic** [twbs/bootstrap#40681]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The situation is quite simple: if I add data-bs-theme="dark" to html element, then nav element is rendered in dark mode and that's fine (and of course all other elements).

If I add data-bs-theme="dark" only to nav element, then dark mode is not enabled and the navbar is completely white (default theme).

Things are different with other elements for example a generic card.
If I add data-bs-theme="dark" to div with card class, then it is rendered in dark mode.

### Reduced test cases

```html
<nav class="navbar navbar-expand-lg" data-bs-theme="dark">  <!-- NOT WORKING -->
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
</nav>

    <div class="card" data-bs-theme="dark">  <!-- THIS WORKS -->
    	<div class="card-body">
   		Some placeholder content.
        </div>
	</div>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @gipic 

The navbar needs to have a background color defined from "outside".
In your example, you'll need to add for instance a `.bg-body-tertiary` (like in our [Navbar documentation](https://getbootstrap.com/docs/5.3/components/navbar)), a `.bg-body`, or whatever other background color:

```diff
- <nav class="navbar navbar-expand-lg" data-bs-theme="dark">
+ <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
```

I'm closing the issue since, for now, it's a voluntary behavior. Hope it'll fix your issue.
Feel free to add comments here if I missed something :)
