### ISSUE TITLE
`npm audit` reports moderate XSS vulnerability with bootstrap 4.6.2

### ISSUE THREAD

**Issue by cduff** [twbs/bootstrap#40685]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`npm audit` is reporting a moderate severity XSS vulnerability with bootstrap 4.6.2.
See https://github.com/advisories/GHSA-vc8w-jr9v-vj7f

### Reduced test cases

```
npm i bootstrap@4.6.2
npm audit
```

Output:

```
# npm audit report

bootstrap  4.0.0 - 4.6.2
Severity: moderate
Bootstrap Cross-Site Scripting (XSS) vulnerability - https://github.com/advisories/GHSA-vc8w-jr9v-vj7f
fix available via `npm audit fix --force`
Will install bootstrap@5.3.3, which is a breaking change
node_modules/bootstrap

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force
```

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

4.6.2

**Comment by julien-deramond** [comment]
Thanks for reporting an issue, @cduff.

Please note that Bootstrap 4 reached its end-of-life (EOL) on January 1, 2023. As a result, we will no longer release new versions of Bootstrap 4. We recommend migrating to a newer version of Bootstrap.

If migration is not possible, please verify whether you are truly affected by this CVE. Review the Bootstrap elements you are using and compare them with the elements mentioned in the CVE.

**Comment by swapnil0545** [comment]
This has created a problem at many places as npm audit is now automatically upgrading to major breaking version. I wish this would have fixed as a patch.
