### ISSUE TITLE
Bootstrap Cross-Site Scripting (XSS) vulnerability

### ISSUE THREAD

**Issue by NormandoHall** [twbs/bootstrap#40693]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://github.com/advisories/GHSA-vc8w-jr9v-vj7f

### Reduced test cases

Latest 4.x branch

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

v4.6.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @NormandoHall 
This is a duplicated of #40685, so I'm closing it.
Corresponding answer at https://github.com/twbs/bootstrap/issues/40685#issuecomment-2264561511
