### ISSUE TITLE
Use gap property for flex box grid gutter

### ISSUE THREAD

**Issue by nightloewe1** [twbs/bootstrap#40709]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap should use the `gap`-property to manage the gutter between the columns and rows, so that you can easily customize the padding of the rows or columns without interfering with the gutter provided by bootstrap.

### Motivation and context

I sometimes get into weird problems with the grid when using custom padding/margin on the elements. The `gap`-property would introduce a clear distinction between padding, margin and the gutter.

**Comment by kumar200516** [comment]
> ### Prerequisites
> 
> - [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
> - [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
> 
> ### Proposal
> 
> Bootstrap should use the `gap`-property to manage the gutter between the columns and rows, so that you can easily customize the padding of the rows or columns without interfering with the gutter provided by bootstrap.
> 
> ### Motivation and context
> 
> I sometimes get into weird problems with the grid when using custom padding/margin on the elements. The `gap`-property would introduce a clear distinction between padding, margin and the gutter.

Yes

**Comment by mdo** [comment]
This is the goal for a v6 release—changing in v5 would be a breaking change.
