### ISSUE TITLE
data-bs-* attributes not working in Toast Component in v5.3.3 and v5.0.2

### ISSUE THREAD

**Issue by akhileshThapliyal** [twbs/bootstrap#40707]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Whenever I configure toast with the data-bs-* attributes such as autohide, delay and animation they are not parsed. I even tried the element but no luck. I also tried in both variations of bundle.js and with popper.js & bootstrap.js.

The expectation is that the data attributes should be parsed and the component should be initialized without me writing no additional Javascript. I also tried to initialize the toast div, but no outcome.

Please find the code below and advise.

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
</head>

<body>
    <div class="container">
        <h1 class="text-success">Test Bootstrap Data Attributes</h1>
        <h2>Bootstrap 5 Toasts Options</h2>

        <div>
            <button type="button" 
                       class="btn btn-success" 
                       onclick="showToast()">
                Show the Toast
            </button>

            <div id="toast_message" role="alert" aria-live="assertive" aria-atomic="true" class="toast mt-5" data-bs-autohide="false">
                <div class="toast-header">
                  <strong class="me-auto">Bootstrap</strong>
                  <small>11 mins ago</small>
                  <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                  Hello, world! This is a toast message.
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
    <script>
        var myToast = null;
        document.addEventListener('DOMContentLoaded', function () {
            var myToastEl = document.getElementById('toast_message');
            myToast = new bootstrap.Toast(myToastEl);
        });

        function showToast() {
            myToast.show();
        }
    </script>
</body>
</html>
```

### Reduced test cases

Please refer to the source code in the above issue description.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Bootstrap are you using?

v5.0.2, v5.3.3

**Comment by julien-deramond** [comment]
Hello @akhileshThapliyal 
I've created a [CodePen from your example](https://codepen.io/julien-deramond/pen/OJejRpQ), and `data-bs-autohide="true" data-bs-animation="false" data-bs-delay="200"` seem to work pretty well: the toast auto hides, has no animation, and is closed after 200ms.
I'm not sure to get what's the issue.

**Comment by akhileshThapliyal** [comment]
> data-bs-autohide="true"

I want to show the toast by default, when I use data-bs-autohide="false" and initialise the toast using the new bootstrap.Toast(myToastEl); it doesn't show up. I have to then explicitly call .show() API. This is the problem.

**Comment by louismaximepiton** [comment]
Hey there,

I feel like the title and description of this issue might not be related to your actual problem because I can't see any issue with the behavior of the `data-bs-*` attributes compared to what's in our documentation right now. If I understand well, you're asking for a new feature that would display the toast by default without writing any Javascript ?

**Comment by akhileshThapliyal** [comment]
> Hey there,
> 
> I feel like the title and description of this issue might not be related to your actual problem because I can't see any issue with the behavior of the `data-bs-*` attributes compared to what's in our documentation right now. If I understand well, you're asking for a new feature that would display the toast by default without writing any Javascript ?

yes, correct that is what the document also says's correct? The data attributes are parsed and evaluated by the bootstrap scripts. Hence, I thought that setting the autohide to false would show up on the page load by default :(.

**Comment by louismaximepiton** [comment]
As the documentation mentions, 

> `autohide` | boolean | true | Automatically hide the toast after the delay.

The `autohide` option avoid the toast to hide after the delay, but you need to display it first by calling the `show()` method. The documentation feels explicit enough to me. TBH I don't think we would implement such an option to avoid writing 3 lines of JS.

I'm closing it for now.

**Comment by akhileshThapliyal** [comment]
> As the documentation mentions,
> 
> > `autohide` | boolean | true | Automatically hide the toast after the delay.
> 
> The `autohide` option avoid the toast to hide after the delay, but you need to display it first by calling the `show()` method. The documentation feels explicit enough to me. TBH I don't think we would implement such an option to avoid writing 3 lines of JS.
> 
> I'm closing it for now.

Noted, thank you :)
