### ISSUE TITLE
Feature Suggestion: Add Support to Disable Closing on Backdrop Click

### ISSUE THREAD

**Issue by arthurrochamoreira** [twbs/bootstrap#40716]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Description:
This issue proposes adding a new configuration option to the Offcanvas component, allowing developers to disable the automatic closing of the offcanvas when a user clicks on the backdrop.

Suggested Feature:
Disable Closing on Backdrop Click:
Description: Currently, the offcanvas automatically closes when the user clicks on the backdrop surrounding it. This new option would allow developers to disable this behavior.

Expected Behavior:
A new option, closeOnBackdropClick, could be added to the offcanvas configuration. If set to false, the offcanvas would remain open even when the user clicks on the backdrop.

### Motivation and context

Motivation: This feature provides more control over the offcanvas behavior, particularly in situations where accidental closure should be prevented, such as with complex forms or when displaying critical information.

**Comment by louismaximepiton** [comment]
Hey there,

thanks for your contribution. I think the issue you mention here is already handled by the [static backdrop](https://getbootstrap.com/docs/5.3/components/offcanvas/#static-backdrop) we provide. Can you confirm this ?
