### ISSUE TITLE
Bootstrap floating labels are no longer respecting text-overflow: ellipsis

### ISSUE THREAD

**Issue by zigazuzek** [twbs/bootstrap#40729]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Bootstrap floating labels are no longer respecting text-overflow: ellipsis

This happens:

when the floating form input is smaller in width compared to the label text. It used to work normally in previous Bootstrap versions.

.form-floating>label requires to have width: 100% set, otherwise text-overflow: ellipsis doesn't work.

### Reduced test cases

You can test it in the Boostrap docs https://getbootstrap.com/docs/5.3/forms/floating-labels/

Make sure to test it with a smaller browser window,

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by theodorejb** [comment]
Duplicate of #39080. This is fixed in the master branch, but not in a released version yet.

**Comment by zigazuzek** [comment]
Missed it, thanks! Good to hear.
