### ISSUE TITLE
Cheatsheet horizontal scrolling

### ISSUE THREAD

**Issue by diafestivo** [twbs/bootstrap#40798]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello,

In the "Cheatsheet" example, there seems to be some padding that causes horizontal scrolling on mobile resolutions.

It might seem like a minor issue, but it can be uncomfortable for many users.

Thank you, and congratulations on your great work.

### Reduced test cases

The issue seems to be caused by content overflowing the width of the screen on mobile resolutions. A potential fix is to add the following CSS rule to prevent horizontal scrolling:

```css
@media (max-width: 768px) {
    body {
        overflow-x: hidden;
    }
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @diafestivo! 
I can also confirm the issue with Firefox on macOS.
I've tried a fix with https://github.com/twbs/bootstrap/pull/40799 but which handles only resolutions >= 272px which is kind of small already.
Is it fixing your issue on your side?
