### ISSUE TITLE
go fuck yourself

### ISSUE THREAD

**Issue by bs2727** [twbs/bootstrap#40830]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

title

### Motivation and context

title

**Comment by Alex-Toucan** [comment]
what was your issue??? @bs2727
