### ISSUE TITLE
Uncaught TypeError: $(...).modal is not a function

### ISSUE THREAD

**Issue by nongtan7898** [twbs/bootstrap#40847]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am having trouble closing the modal using jquery.

vite vue jquery bootstrap 5.3

```html
<template>
  <!-- Button trigger modal -->
  <button
    type="button"
    class="btn btn-primary"
    data-bs-toggle="modal"
    data-bs-target="#exampleModal"
  >
    Launch demo modal
  </button>

  <!-- Modal -->
  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">...</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" @click="close()">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const close = () => {
  window.$('#exampleModal').modal('toggle')
}
</script>

<style></style>
```

### Reduced test cases

- https://stackblitz.com/edit/vitejs-vite-lp48zk?file=src%2Fmain.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3

**Comment by nongtan7898** [comment]
this Reduced test cases
https://stackblitz.com/edit/vitejs-vite-lp48zk?file=src%2Fmain.js

**Comment by HabebNawatha** [comment]
If I understand correctly you want to close the modal using the 'Save Changes' button.
I have found 2 solutions for this:
1) try using the following script instead : 
<script setup>
const close = () => {
  window.$('#exampleModal').toggle();
}
</script>
it worked for me using stackblitz.
but this generates another problem which is the background stays blurry, I will try to look into that after.
2) you can give the close button inside the modal an id, and you can use the click function on that button inside your function.
like the following : 
the button : 
 <button
            type="button"
            id="closeBtn"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>

the script:
<script setup>
const closeModal = () => {
  /* Implementation needed */
  window.$('#closeBtn').click()
};
</script>

Hope this helps a bit :)

**Comment by julien-deramond** [comment]
I'd say that you need to get access to the instance of the modal. I'm not that familiar with Vue.js, but you could try to add this to the `main.js`:

```js
import * as bootstrap from 'bootstrap';
window.bootstrap = bootstrap;
```

And then, in `App.vue`, something like:

```js
const close = () => {
  const modalInstance = bootstrap.Modal.getOrCreateInstance('#exampleModal');
  modalInstance.hide();
};
```
