### ISSUE TITLE
"justify-content-end" does not align flex items to the right

### ISSUE THREAD

**Issue by s0rin** [twbs/bootstrap#40848]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

After update Bootstrap from 5.3.2 to 5.3.3 "justify-content-end" does not align flex items to the right (on any browser i.e. Chrome, Firefox, MS Edge). This has worked for the close buttons of modal windows until 5.3.2

### Reduced test cases

```html
    <div class="d-flex justify-content-end">
      <%= content_tag :button, nil, :class => 'btn-close', :aria_label => "Close",
                      :data => {:bs_dismiss => "modal", :bs_title => "Close window", :bs_placement => "right",
                      	        :bs_toggle => "tooltip"} %>
    </div>
```

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @s0rin 

Here's the CSS rule of `bootstrap.css` in 5.3.3: https://github.com/twbs/bootstrap/blob/6e1f75f420f68e1d52733b8e407fc7c3766c9dba/dist/css/bootstrap.css#L7783-L7785

Here's the CSS rule of `bootstrap.css` in 5.3.2: https://github.com/twbs/bootstrap/blob/344e912d04b5b6a04482113eff20ab416ff01048/dist/css/bootstrap.css#L7794-L7796

Nothing has changed specifically for this class.

Please try to create a reproducible live example of your issue with CodePen or StackBlitz so we can analyze the real problem :)

**Comment by s0rin** [comment]
Here the reproducible live examples as requested:
[Bootstrap 5.3.2 modal popup] (https://codepen.io/s0rin/pen/VwJoWpo)
[Bootstrap 5.3.3 modal popup] (https://codepen.io/s0rin/pen/yLdmXLo)

**Comment by julien-deramond** [comment]
OK, I get it. We changed the CSS of the modal in 5.3.3 (see https://github.com/twbs/bootstrap/pull/39373/files).
On your side, you don't need this extra `<div>` and use the HTML markup provided in our [Modal documentation](https://getbootstrap.com/docs/5.3/components/modal/#modal-components).
To fix the issue, you can remove the surrounding `<div class="d-flex justify-content-end">`.

**Comment by s0rin** [comment]
That's right, the fix works, thank you!
