### ISSUE TITLE
When using input-group splits when form.field is added

### ISSUE THREAD

**Issue by jbhrfx9280** [twbs/bootstrap#40850]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

             <div class="input-group input-group-sm mb-1">
                <span class="input-group-text">With textarea</span>
                {{ form.social_title }}
                <textarea class="form-control" aria-label="With textarea"></textarea>
              </div>
See below example with {{ form.field }} added
![image](https://github.com/user-attachments/assets/5331cc25-e8e2-4fa2-98d7-ae5e44df8253)

FYI - I'm new to bootstrap 5 and HTML design, more of a coder so clearly I can be doing this wrong.
Framework: Django

### Reduced test cases

             <div class="input-group input-group-sm mb-1">
                <span class="input-group-text">With textarea</span>
                <textarea class="form-control" aria-label="With textarea"></textarea>
              </div>

see below without form.field added

![image](https://github.com/user-attachments/assets/029aa7dd-b6bb-4fbd-8b5f-06d70abaeff6)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.3.3

**Comment by AadiSharma49** [comment]
Changing behavior to the textarea 
<div class="input-group input-group-sm mb-1">
    <span class="input-group-text">With textarea</span>
    <textarea class="form-control" id="myTextarea" aria-label="With textarea"></textarea>
</div>
<button id="btn">Set Text</button>
**And handling form data from textarea**
<script>
    document.getElementById('submitBtn').addEventListener('click', function() {
        let textareaValue = document.getElementById('myTextarea').value;
        console.log('Textarea value:', textareaValue);
        // You can then do something with the textarea value like validation or sending it via AJAX
    });
</script>

**Comment by omishah** [comment]
``{{ form.social_title }}`` is rendered with what value? Check in page source.
