### ISSUE TITLE
What happened to negative margins in Bootstrap 5 and above?

### ISSUE THREAD

**Issue by JackSzwergold** [twbs/bootstrap#40890]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

_**Note**: Entered “macOS” and “Safari” in the drop downs since they are required. But I feel that stuff is not needed for what this issue is reporting._

What happened to negative margins in Bootstrap 5 and above?

A quick check of Bootstrap 4.6.2 still shows them in place. But apparently they are missing from Bootstrap 5.3.3 despite[ the docs still referencing their use](https://getbootstrap.com/docs/5.3/utilities/spacing/#negative-margin).

The CSS for these classes are as follows; taken from Bootstrap 4.6.2:

```
.mt-n1,
.my-n1 {
  margin-top: -0.25rem !important;
}

.mr-n1,
.mx-n1 {
  margin-right: -0.25rem !important;
}

.mb-n1,
.my-n1 {
  margin-bottom: -0.25rem !important;
}

.ml-n1,
.mx-n1 {
  margin-left: -0.25rem !important;
}

.m-n2 {
  margin: -0.5rem !important;
}

.mt-n2,
.my-n2 {
  margin-top: -0.5rem !important;
}

.mr-n2,
.mx-n2 {
  margin-right: -0.5rem !important;
}

.mb-n2,
.my-n2 {
  margin-bottom: -0.5rem !important;
}

.ml-n2,
.mx-n2 {
  margin-left: -0.5rem !important;
}

.m-n3 {
  margin: -1rem !important;
}

.mt-n3,
.my-n3 {
  margin-top: -1rem !important;
}

.mr-n3,
.mx-n3 {
  margin-right: -1rem !important;
}

.mb-n3,
.my-n3 {
  margin-bottom: -1rem !important;
}

.ml-n3,
.mx-n3 {
  margin-left: -1rem !important;
}

.m-n4 {
  margin: -1.5rem !important;
}

.mt-n4,
.my-n4 {
  margin-top: -1.5rem !important;
}

.mr-n4,
.mx-n4 {
  margin-right: -1.5rem !important;
}

.mb-n4,
.my-n4 {
  margin-bottom: -1.5rem !important;
}

.ml-n4,
.mx-n4 {
  margin-left: -1.5rem !important;
}

.m-n5 {
  margin: -3rem !important;
}

.mt-n5,
.my-n5 {
  margin-top: -3rem !important;
}

.mr-n5,
.mx-n5 {
  margin-right: -3rem !important;
}

.mb-n5,
.my-n5 {
  margin-bottom: -3rem !important;
}

.ml-n5,
.mx-n5 {
  margin-left: -3rem !important;
}
```

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
> But apparently they are missing from Bootstrap 5.3.3 despite[ the docs still referencing their use](https://getbootstrap.com/docs/5.3/utilities/spacing/#negative-margin).

Hello @JackSzwergold 
In this same link, it is mentioned that "These negative margins are **disabled by default**, but can be enabled in Sass by setting `$enable-negative-margins: true`."
So if you want to get them back, you'll need to compile Bootstrap with Sass and enable this option.

**Comment by JackSzwergold** [comment]
Makes sense.

> > But apparently they are missing from Bootstrap 5.3.3 despite[ the docs still referencing their use](https://getbootstrap.com/docs/5.3/utilities/spacing/#negative-margin).
> 
> Hello @JackSzwergold In this same link, it is mentioned that "These negative margins are **disabled by default**, but can be enabled in Sass by setting `$enable-negative-margins: true`." So if you want to get them back, you'll need to compile Bootstrap with Sass and enable this option.

Makes sense. Thanks for the quick response!
