### ISSUE TITLE
Column width (data-width) not working when table has scroll

### ISSUE THREAD

**Issue by Thang1PV** [twbs/bootstrap#40902]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Column width not working when table has scroll

### Reduced test cases

https://live.bootstrap-table.com/code/Thang1PV/18242

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

v5

**Comment by julien-deramond** [comment]
Hey @Thang1PV 
You're using Bootstrap Table project and not the tables directly provided by Bootstrap if I understand the live example correctly. I let you report an issue in their repository: https://github.com/wenzhixin/bootstrap-table/issues/new/choose.
Closing this issue as it is not apparently related to this repo.

**Comment by fluttering-tampering** [comment]
> Hey [@Thang1PV](https://github.com/Thang1PV) You're using Bootstrap Table project and not the tables directly provided by Bootstrap if I understand the live example correctly. I let you report an issue in their repository: https://github.com/wenzhixin/bootstrap-table/issues/new/choose. Closing this issue as it is not apparently related to this repo.





https://stingingfirebaseui.github.io/gannon/
