### ISSUE TITLE
Auto URL Sync While Scroll

### ISSUE THREAD

**Issue by MohamadSalman11** [twbs/bootstrap#40913]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Normally, when we scroll through the documentation, the corresponding section link on the right sidebar is highlighted so that the user knows where they are. It would be great if, in addition to the highlighting, the address bar is also automatically updated. For example, when I’m on the page **https://getbootstrap.com/docs/5.3/getting-started/introduction**, the address bar should change to **https://getbootstrap.com/docs/5.3/getting-started/introduction/#cdn-links** when I scroll down to the **"CDN links"** section. This would allow the URL to update not only when I click on the link in the right sidebar but also while I scroll through the document.

### Motivation and context

Provides more user experience

**Comment by julien-deramond** [comment]
Thanks for the suggestion, @MohamadSalman11, but we'll pass on this. Automatically updating the URL while scrolling isn't standard web behavior, as URLs usually reflect deliberate user actions. We prefer to keep navigation predictable for consistency across the documentation.
