### ISSUE TITLE
Docs: consider adding ngx-bootstrap as a JavaScript framework

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#40921]
In the 'Usage with JavaScript frameworks' section: https://getbootstrap.com/docs/5.3/getting-started/javascript/#usage-with-javascript-frameworks it lists [ng-bootstrap](https://ng-bootstrap.github.io/) as a solution for Angular.

I think it might be worth considering adding [ngx-bootstrap](https://github.com/valor-software/ngx-bootstrap) too. It has 5500 Stars and works great with Bootstrap 5. I'm not affiliated with the project but I have been using it.

**Comment by julien-deramond** [comment]
Personally, I don't mind adding it. I used it in a project for Orange back in the day with Bootstrap 4, and it worked great. Feel free to create a PR for it, @coliff, or I can take care of it if you're short on time. Let's see what the rest of the core team thinks once the PR is up.
