### ISSUE TITLE
Add Colors to Bootstrap Brand Section

### ISSUE THREAD

**Issue by MohamadSalman11** [twbs/bootstrap#40926]
In the [docs/5.3/about/brand/](https://getbootstrap.com/docs/5.3/about/brand/) section, it would be great to add the brand colors as well. Right now, it only has guidelines about the logo and name. Including the main Bootstrap colors would help users see right away what the main colors are for Bootstrap.

**Comment by anish21pgt** [comment]
@MohamadSalman11 I am taking this up.

**Comment by MohamadSalman11** [comment]
> @MohamadSalman11 I am taking this up.

Good Luck!

**Comment by mdo** [comment]
The colors page handles this fine.
