### ISSUE TITLE
Improve Footer Layout and Color for a More Professional and Attractive Appearance

### ISSUE THREAD

**Issue by SuhaniBh** [twbs/bootstrap#40967]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The current footer design in Bootstrap is quite functional but lacks a modern and professional appeal. I would like to propose a change to the footer layout and its color scheme to make it more visually appealing and aligned with modern web design trends.

Proposal: Here are some suggested improvements to the footer layout and design:

1)Color Scheme Update: Use a more vibrant and modern color palette to give the footer a sleek and professional look.
2)Layout Reorganization: Enhance the structure of the footer by organizing content into columns and using responsive design techniques to ensure that the footer adapts well to all screen sizes.
3)Spacing and Alignment: Increase the spacing between sections for better readability and use consistent alignment for a polished finish.

### Motivation and context

The current footer feels somewhat outdated and can be improved to align with modern design principles. A more visually appealing footer will help improve user experience and maintain a cohesive look throughout the Bootstrap framework.

**Comment by julien-deramond** [comment]
Closing the issue as you provided a PR directly

**Comment by SuhaniBh** [comment]
Thanks for the feedback! That makes sense—I'll hold off on any code changes until we hear back from @mdo regarding the design. I appreciate your input on the light version too, and I agree that toning down the colors might help. Once we get clarity on the design direction, I can make adjustments to the logo and text as well.
