### ISSUE TITLE
Accordion flush in card has missing corners on bottom

### ISSUE THREAD

**Issue by ianw** [twbs/bootstrap#40991]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I put an accordion in flush mode inside a card the bottom is slightly broken up

![Screenshot from 2024-10-29 14-10-06](https://github.com/user-attachments/assets/b2b86ee9-c743-4f29-8c8d-d41ae8e68c78)

![Screenshot from 2024-10-29 14-10-06-2](https://github.com/user-attachments/assets/51e9b0e4-d5d0-4b32-8949-f7ed6d8973a9)

There isn't an exact example of the accordion in a card, but there is a of flush list-group in https://getbootstrap.com/docs/5.3/components/card/ and I feel like I'm doing the same thing where you basically have the accordion after the `card-header`

```
 <div class="card">
    <div class="card-header">
         Header
     </div>
      <div class="accordion accordion-flush" id="accordionExample">
     ... accordion follows ...
```

I see this in Firefox and Chrome on the codepen example below

### Reduced test cases

A codepen example of this is https://codepen.io/iwienand/pen/LYwdELE

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.3

**Comment by coliff** [comment]
Cards have border-radius by default so I'd suggest simply adding the '[rounded-0](https://getbootstrap.com/docs/5.3/utilities/borders/#radius)' utility class to the .card to fix it.

**Comment by julien-deramond** [comment]
> Cards have border-radius by default so I'd suggest simply adding the '[rounded-0](https://getbootstrap.com/docs/5.3/utilities/borders/#radius)' utility class to the .card to fix it.

Thanks, coliff! This is definitely the way to go. Since a card is treated as a simple container, the framework doesn't apply special CSS for handling specific combinations of components within the card.
I'm closing this issue.
