### ISSUE TITLE
Alignment issue with floating labels and small select (form-select-sm) padding in Bootstrap 5.3

### ISSUE THREAD

**Issue by patrickzzz** [twbs/bootstrap#41008]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have encountered an alignment issue when using Bootstrap 5.3’s floating labels with the small select element (form-select-sm). The selected value is misaligned, appearing further to the left than the floating label due to the reduced padding applied to the small select.

Steps to reproduce:

	1.	Create a form with a floating label using the form-floating class.
	2.	Include a select element with the class form-select-sm.
	3.	Observe that the selected value does not align with the floating label.

Expected behavior:
The selected value should align correctly with the floating label, regardless of the select size.

Actual behavior:
The selected value is offset to the left, causing misalignment with the label.

For a reduced test case demonstrating this issue, please refer to my CodePen link: [[VIew on Code Pen].](https://codepen.io/patrickzzz/pen/GRVXjLK)

### Reduced test cases

https://codepen.io/patrickzzz/pen/GRVXjLK

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3 (latest)

**Comment by louismaximepiton** [comment]
Hey there, thanks for your contribution!

I confirm that it doesn't work well with select sizes [as mentioned in the doc](https://getbootstrap.com/docs/5.3/forms/floating-labels/#selects). 

That said, I'm fine having it in Bootstrap since it looks more logical. Feel free to open a PR around this subject.

**Comment by patrickzzz** [comment]
Hi @louismaximepiton, thanks!
I added the PR: https://github.com/twbs/bootstrap/pull/41013
I kept the change minimal, as i saw, also in other places, a "*-padding-x" variable is only applied to either left/right (e.g.: https://github.com/twbs/bootstrap/blob/main/scss/forms/_form-select.scss#L11 ). Of course, the right padding shall not be changed, as it is place of the select-dropdown-arrow.

Regards,
Patrick
