### ISSUE TITLE
order-7 to order-12 missing?

### ISSUE THREAD

**Issue by audaki** [twbs/bootstrap#41029]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Older bootstrap had order-1 to order-12

The documentation still says that 1 to 12 is supported: https://getbootstrap.com/docs/4.1/layout/grid/

But after upgrading bootstrap these classes failed, and when looking at the code, it seems like actually only 1-6 are generated: https://github.com/twbs/bootstrap/blob/main/scss/_utilities.scss#L335

### Reduced test cases

No test cases

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v4+

**Comment by julien-deramond** [comment]
Hello @audaki 

The documentation of Bootstrap 4.1 states that `order` class support is from 1 to 12. It was the case until the latest Bootstrap v4.

However, that's not the case anymore in Bootstrap 5. In the [Flex > Order section](https://getbootstrap.com/docs/5.3/utilities/flex/#order):

> As `order` takes any integer value from 0 to 5

https://github.com/twbs/bootstrap/blob/cbbb567b637e24882fd0fad62bca49e248afb9a4/dist/css/bootstrap.css#L7871-L7901

In our [migration guide](https://getbootstrap.com/docs/5.3/migration/), it's mentioned that:

> **Breaking** Dropped several `.order-*` classes that often went unused. We now only provide `.order-1` to `.order-5` out of the box.

Hope it can help :) I'm going to close this issue. Feel free to comment it if there are elements that I missed.

**Comment by louismaximepiton** [comment]
To complete what was said, as mentioned by our [utility API](https://getbootstrap.com/docs/5.3/utilities/api/#modify-utilities), you can still get them back using:

```scss
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/variables-dark";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";

$utilities: map-merge(
  $utilities,
  (
    "order": map-merge(
      map-get($utilities, "order"),
      (
        values: map-merge(
          map-get(map-get($utilities, "order"), "values"),
          (6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, last: 13),
        ),
      ),
    ),
  )
);

@import "bootstrap/scss/utilities/api";
```

**Comment by audaki** [comment]
Thanks, you’re right, I just saw that the node package was updated to Bootstrap 5, like you guessed, and the documentation for 5 correctly states order levels 1 to 5

And thanks @louismaximepiton for the workaround!
