### ISSUE TITLE
Bootstrap 5.3 Alerts are dispersing in  Chrome Version 131.0.6778.70 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by Behseini** [twbs/bootstrap#41032]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Using Chrome Version 131.0.6778.70 (Official Build) (64-bit) when I navigate to Bootstrap 5.3 Alert components at following link

https://getbootstrap.com/docs/5.3/components/alerts/#examples

the alerts flash and fade out quickly! this is not happening in Incognito mode or on other bowsers

![ChromeBug](https://github.com/user-attachments/assets/b79c7510-5bda-4c26-807a-a206978687f6)

### Reduced test cases

Navigate to 

https://getbootstrap.com/docs/5.3/components/alerts/#examples

![ChromeBug](https://github.com/user-attachments/assets/58dcedbd-8dd7-4bac-a0e2-4795bb966f9c)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

131.0.6778.70

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @Behseini

I don't reproduce on:
- Chrome Version 131.0.6778.70 (Official Build) (arm64) on macOS Sequoia 15.1.
- Chrome Version 130.0.6723.59 (Official Build) (64-bit) on Windows via BrowserStack (I can't test on the 131.0.6778.70; it's not available yet)

If anyone else is able to reproduce, please let us know 🙏 

> this is not happening in Incognito mode

This is weird.
Do you have some errors in the dev tools?
Maybe there's a collision with an extension?

**Comment by Behseini** [comment]
Sorry guys! it was this Chrome extension which was causing the issue  `FastSave 3.7.7` disabling this fix the performance on browser

**Comment by julien-deramond** [comment]
No problem at all, glad you found a solution :)
Closing this issue, then.
