### ISSUE TITLE
Themes Purchase Support

### ISSUE THREAD

**Issue by khandelwal-aman** [twbs/bootstrap#41040]
I recently made a purchase of https://themes.getbootstrap.com/product/messenger-responsive-bootstrap-application/

However, after purchasing I realized the theme hasn't been updated in last 3 years. I was of the opinion that themes are upto date on official portal. I am not gonna need or use such outdated theme.
![image](https://github.com/user-attachments/assets/177a3361-7b21-4f44-85af-434203cdf903)

I wrote to support to cancel the purchase, however, no response so far.

Please help in cancelling the purchase.

Order #160460

**Comment by julien-deramond** [comment]
Hello @khandelwal-aman 
I'm sorry to hear that, but this repository is related to Bootstrap development. The core team doesn't develop Bootstrap Themes. Please try to re-contact them using the Help Center from their website.
/cc @mdo if there's anything you can do

**Comment by Kr-LeeSangMin** [comment]
I agree with the comment above.
I trusted it because it was a link from the official Bootstrap website, but it turns out to be independent... On top of that, it's a poorly maintained theme site, which is very disappointing.

**Comment by JamesVanWaza** [comment]
> https://themes.getbootstrap.com/product/messenger-responsive-bootstrap-application/

Also try contacting the owner of theme - web-master72@yandex.com this is their email below.
