### ISSUE TITLE
Stacks was automatically wrapped when inputting Chinese

### ISSUE THREAD

**Issue by fangjunai** [twbs/bootstrap#41045]
Microsoft Edge v131.0.2903.51 (x64)
Bootstrap  v5.3.3

![22](https://github.com/user-attachments/assets/454efe9e-41cd-4c9f-a14d-89c23dc1feb9)

<form class="row g-1">
	<div class="col-12">
		<div class="hstack gap-3">
			<label for="phone1" class="form-label">手机</label>
			<input type="text" class="form-control" id="phone1" value="1234567890" />
		</div>
	</div>
	<div class="col-12">
		<div class="hstack gap-1">
			<label for="phone2" class="form-label">iPhone</label>
			<input type="text" class="form-control" id="phone2" value="1234567890" />
		</div>
	</div>
</form>

### Reduced test cases

```html
<form class="row g-1">
	<div class="col-12">
		<div class="hstack gap-3">
			<label for="phone1" class="form-label">手机</label>
			<input type="text" class="form-control" id="phone1" value="1234567890" />
		</div>
	</div>
	<div class="col-12">
		<div class="hstack gap-1">
			<label for="phone2" class="form-label">iPhone</label>
			<input type="text" class="form-control" id="phone2" value="1234567890" />
		</div>
	</div>
</form>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Hey @fangjunai 
In this case, you could add a `.text-nowrap` to the label containing chinese characters:
```html
<div class="hstack gap-3">
  <label for="phone1" class="form-label text-nowrap">手机</label>
  <input type="text" class="form-control" id="phone1" value="1234567890" />
</div>
```
See https://codepen.io/julien-deramond/pen/BaXgxLB

**Comment by fangjunai** [comment]
Thank you.
