### ISSUE TITLE
BS Modal on mobile view, throwing error on close button click

### ISSUE THREAD

**Issue by alaksandarjesus** [twbs/bootstrap#41090]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On Mobile View, click on the close button, we get 

Blocked aria-hidden on an element because its descendant retained focus. ....

![image](https://github.com/user-attachments/assets/cb625909-110d-4f4b-82b2-693394ab36d2)

### Reduced test cases

Can test in https://getbootstrap.com/docs/5.3/components/modal/#how-it-works

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by LittleRookie1115** [comment]
I met this too!

**Comment by ALiaoHaolong** [comment]
I met this too!

**Comment by julien-deramond** [comment]
I can confirm the presence of this message while triggering the modals in our own documentation (but not all the times) in Chrome only:

Example of error message:
```
modal/#live-demo:1 Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: button
Ancestor with aria-hidden: 
```
```html
<div class="modal fade" id="exampleModalLong" tabindex="-1" aria-labelledby="exampleModalLongTitle"
  style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">flex<div class="modal-header">…</div>flex<div class="modal-body"
        style="min-height: 1500px">
        <p>"This is some
          placeholder content to show the scrolling behavior for modals. Instead of repeating the text in the modal, we
          use an inline style to set a minimum height, thereby extending the length of the overall modal and
          demonstrating the overflow scrolling. When content becomes longer than the height of the viewport, scrolling
          will move the modal as needed."</p>
      </div>
      <div class="modal-footer">flex<button type="button" class="btn
          btn-secondary" data-bs-dismiss="modal">Close</button><button type="button" class="btn btn-primary">Save
          changes</button></div>
    </div>
  </div>
</div>
```

**Comment by bravedave** [comment]
already reported here: #41005

**Comment by julien-deramond** [comment]
Thanks @bravedave, hadn't spotted it was a duplicate. So I'm closing this one.
