### ISSUE TITLE
`!important` does not allow to override when using with CSS layers

### ISSUE THREAD

**Issue by martinszeltins** [twbs/bootstrap#41105]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

There are several places in the codebase where `!important` is used. This makes it impossible to override it when using CSS layers because `!important` works in the opposite direction with CSS layers. `!important` should be removed.

If the `bootstrap` layer contains `!important` then it will be more important than any other important in more important layers.

```css
@layer bootstrap, base, utilities;

@import "node_modules/bootstrap/scss/bootstrap" layer(bootstrap);
```

### Reduced test cases

n/a

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.3

**Comment by julien-deramond** [comment]
Could you clarify which specific use cases are problematic for you (or if it’s global)? `!important` is intentionally used in Bootstrap to ensure critical styles are applied consistently and cannot be accidentally overridden.
Depending on the contexte, if it helps, Bootstrap provides an option to disable `!important` for utility classes via the `$enable-important-utilities` variable (see the documentation here: https://getbootstrap.com/docs/5.3/utilities/api/#importance).

**Comment by martinszeltins** [comment]
The use of `!important` is generally considered bad practice and should be avoided. It messes with CSS @layers feature.

There are still many places where `!important` is used

![image](https://github.com/user-attachments/assets/6445dfe8-0e52-48d9-b83f-1bf61711a723)

**Comment by mdo** [comment]
We're not getting around that anytime soon, sorry. We could move utilities to a layer in v6 and theoretically avoid the `!important`, but that's a breaking change in either case.

**Comment by jcoyne** [comment]
One reason this is problematic for me is my colors don't have commas, but `.bg-dark` sets `background-color` expecting commas. Since BS uses `!important`, we can't override the rule. 😬
