### ISSUE TITLE
breakpoints interact badly with devicePixelRatio for DPI that are slightly above 96.

### ISSUE THREAD

**Issue by RichardNeill** [twbs/bootstrap#41118]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Most regular desktop, non-retina monitors are about 90-120 dpi (not the nominal 96 dpi). Recently, Firefox/Chrome now take this into account, so that the screen-width is measured in CSS pixels, not true pixels. As a result, the breakpoints now trigger one level too low. 

Here's what I measured:

Physical screen: 4k, 3840x2160, at 43" diagonal. The physical DPI is 103. 
[This setup is ideal for web development, as a quadrant is the typical 1920x1080].

Case 1. 
DPI  set to 96 (default).
Fonts are a bit small.
An element with "style='width:3in'" is in fact 2.8 inches wide (with a ruler). 
window.screen.width is 3840
window.devicePixelRatio is 1.

Case 2. 
DPI set to 103 (the reality).
Fonts are exactly the right size
An element with "style='width:3in'" is in fact 2.99 inches wide (with a ruler). 
window.screen.width = 3584
window.devicePixelRatio is 1.0714

Consequence: my 1920-wide (half-screen), now identifies itself as -xl  rather than -xxl,  and so we get the multicolumn-layout totally messed up (in my case, 2 cols, not 3 cols). 

Suggestion 1:
Please document this behaviour on the bootstrap site - it took me ages to debug. 
It seems to be a recent change in the web-browser behaviour.

Suggestion 2:
Reduce the breakpoint sizes to about 85% of their present values (when above 1200). This means that we will always catch the 110-dpi monitors in the right category. 

Finally,  it may help to give my experimental values, which work for most standard devices; and which account for DPI up to 15% greater than 96, (as well as allowing for modal dialogs at 98% of screen size).

```scss
$grid-breakpoints: (	
  xs: 0,
  sm: 576px,     //phone.  (including high resolution, 2x devices)
  md: 768px,
  lg: 992px,       //tablet.
  xl: 1200px,     //small desktop monitor.
  xxl:1610px,    //normal "good" desktop monitor, nominally above 1920px. 
  gg: 2140px,   //gigantic desktop monitor, nominally 2560px.
  4k: 3200px    //4k, wallmount or developer machine, nominally 3840px.
)
```

 (This bug is most likely to affect web-developers who will carefully calibrate for their own systems, then design to make it perfect for themselves, and consequentially worse for normal users).

### Reduced test cases

See: https://whatismyviewport.com/

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment]
Seems like a rather annoying Linux issue. https://www.reddit.com/r/chrome/comments/izwtx8/chrome_scales_a_bit_in_linux_if_xfce_dpi_isnt/

Not sure how this would be solved by us without affecting other platforms.

**Comment by RichardNeill** [comment]
This isn't just Chrome - it's also Firefox, and it's a current issue rather than an old one.  (I only saw it for the first time a few days ago, though it may not be quite that new). I'm using Mate, not XFCE. Also, I think that Firefox is now actually doing the right thing, and the previous behaviour, relied on by Bootstrap, is not.

Firefox: "your DPI is a little bit above 96, so, in order to make sure that a CSS inch (96 CSS pixels) is always a physical inch (measured with a ruler), we will treat your monitor as if it is slightly fewer (CSS) pixels wide than it is in physical pixels."

Bootstrap: "I'll reflow your layout as if your screen is smaller"

User: "No! You adjusted my font correctly, but I'm still using a big screen;  the column-grid layout should be according to the (real) number of pixels of my screen"


I think there is actually a reasonably good solution here, that should work for everyone.

1. Let's say that we want  monitors of 1920 (and wider) to be in class "-xxl", while monitors at 1200px are in "-xl"
2. Currently, the breakpoint is defined at  <= 1919,   >= 1920.
3. But there's no such thing as a monitor between 1601 and 1919 inclusive. So, we can set our breakpoint in the middle of the range, rather than right at one end, and choose 1610 as the breakpoint. 
4. As a result, a 1920 monitor (anything >= 1610) is -xxl, while a 1200px monitor (anything <= 1609) is -xl.

Changing this only affects 2 cases: monitor resolutions that don't exist, and web-designers who drag windows into convoluted positions on screen! Besides which, we already have to have a fudge-factor, to account for the presence or absence of a vertical scrollbar.  HTH.

Either way, whatever is planned, please can there be a note on the website to explain this issue, so that others don't have to debug it. Thanks.
