### ISSUE TITLE
Scrollspy component js error issue

### ISSUE THREAD

**Issue by gaojianzhuang** [twbs/bootstrap#41124]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

scrollspy component javascript error.
![image](https://github.com/user-attachments/assets/96d099c4-b0ff-4c67-b6d0-13f9b3eb560e)

### Reduced test cases

we should check the find result first, if found then add the CSS class.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
No live example, not using latest version—please open a new issue once done.
