### ISSUE TITLE
Bluesky icon

### ISSUE THREAD

**Issue by guillemmaya92** [twbs/bootstrap#41123]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bluesky icon is missing... could you add it to your list of icons? Thanks  a lot

### Motivation and context

Some tools to build html pages as Quarto are working with Bootstrap icons and it will be helpful to add icons directly in your list.

**Comment by mdo** [comment]
Yeeesh, y'all don't quite. The icon request is in the icons repo. See https://github.com/twbs/icons/issues/1886.
